### ISSUE TITLE
{{each}}'s emptyView Broken in 1.9?

### ISSUE THREAD

**Issue by jherdman** [emberjs/ember.js#10019]
I think `{{#each}}`'s `emptyViewClass` argument is broken. Sample JSBin http://emberjs.jsbin.com/galivadoja/2/. This was working just fine and dandy in 1.8.1 using both the `emptyView` and `emptyViewClass` arguments.

**Comment by jherdman** [comment]
I've posted a fix at #10061

**Comment by mmun** [comment]
I pulled it into beta and stable /cc @rwjblue.
