### ISSUE TITLE
[meta] Ember.js should run ember data's tests as well

### ISSUE THREAD

**Issue by fivetanley** [emberjs/ember.js#10033]
See this build: https://travis-ci.org/emberjs/data/builds/44989660

The recent container refactor broke pretty much all of our tests on canary. It would be nice to know ahead of time if we have a lot of work to do. This has happened a few times (see the Map/Set/OrderedSet changes from a while back, I can look and cross reference when I have time). Since Ember and Ember Data have a tight dependency i think it makes sense to test them together. Ember Data's test suite also doesn't take too long either.

**Comment by stefanpenner** [comment]
Seems reasonable, but i believe a larger effort exists to run many ember addons nightly against canary via a combination of travis support and ember try
