### ISSUE TITLE
fillIn() test helper does not focus its target element

### ISSUE THREAD

**Issue by ForSpareParts** [emberjs/ember.js#10034]
The `fillIn()` helper fills in its target without ever causing the element to be focused. Here's a JSBin with a failing test:

http://emberjs.jsbin.com/sogesonedo/2/edit

This issue makes it difficult to test application logic that depends on the focused state. In my case, I have validation logic that triggers only when an input field loses focus: because the focus state of the input element never changes, my validation logic is never triggered in tests.

**Comment by rwjblue** [comment]
I have been bitten by this as well.

We should extract the input focusing behavior from the `click` helper ([here](https://github.com/emberjs/ember.js/blob/9233641859cc3505e683f6bc3166ca27dffc54b2/packages/ember-testing/lib/helpers.js#L58-L72)) into a separate function and use it from `fillIn` (right after finding the `$el` [here](https://github.com/emberjs/ember.js/blob/9233641859cc3505e683f6bc3166ca27dffc54b2/packages/ember-testing/lib/helpers.js#L140)).

@ForSpareParts - Would you mind taking a stab at fixing this?

**Comment by rwjblue** [comment]
Closing in favor of https://github.com/emberjs/ember.js/issues/10132.
