### ISSUE TITLE
View events bubbling to actions

### ISSUE THREAD

**Issue by bcardarella** [emberjs/ember.js#10040]
Not sure if this should go into issues but it might be nice if I have:

```hbs
{{input value=foo keyUp="myAction"}}
```

if the `keyUp` is not handled then the event is sent as an action along with the event handler. Otherwise opening up the component is not ideal. It implies setting a global handler for specific cases. Extending into a new component then registering that specific helper feels like over-kill for something like this.

**Comment by rwjblue** [comment]
`Ember.TextField` does bubble `key-up` as an action if passed in.

http://emberjs.jsbin.com/rwjblue/192/edit

@bcardarella - Is this what you were looking to do?

**Comment by bcardarella** [comment]
Yes, I suspect my issue was with the camelcasing. Thanks!

**Comment by rwjblue** [comment]
In this case `keyUp` is the actual view function that is invoked on the `Ember.TextField` instance, and it calls `this.sendAction('key-up`, currentValue, event)`.  It is annoying that we have the conflicting between method name and action name.

**Comment by bcardarella** [comment]
confirm, another WTF/minute

**Comment by rwjblue** [comment]
Some of the conflict here can be resolved in 2.0 when we can drop setting properties on the root of View's/Component's from the template (they will be set at `this.attrs` sometime soonish, but we will have to maintain both the root properties and `this.attrs` properties throughout 1.x for SemVer).
