### ISSUE TITLE
API Docs don't mention that a link-to helper can be used inline

### ISSUE THREAD

**Issue by lolmaus** [emberjs/ember.js#10041]
The `link-to` helper can be used either as a block helper or an inline helper.

The two variants have different helper arguments. Only the block variant is documented.

I figured out that the syntax for the inline variant is `{{link-to <label> <route_name>}}`, with the second argument defaulting to current route.

We should document the inline use of `link-to` and it's arguments.

http://emberjs.com/api/classes/Ember.Handlebars.helpers.html#method_link-to

**Comment by petrvolny** [comment]
I guess that this can be closed.

**Comment by lolmaus** [comment]
Why? The documentation has not been updated to reflect actual behavior.

**Comment by petrvolny** [comment]
@lolmaus I am not sure what is the policy here but it is already updated in the master (see #10086) branch so I consider it done. I believe it will be updated on the web with the next stable release.

**Comment by lolmaus** [comment]
Ah, okay. I see the reference up in the thread, but those references don't produce email notifications. Thx for pointing out.
