### ISSUE TITLE
Better deprecation for `Registry.prototype.lookup` from within an Initializer.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#10067]
[This](https://github.com/emberjs/ember.js/blob/e48ea574f1c7112b21b141f873fb1fa26205a2fc/packages/container/lib/registry.js#L139) deprecation is pretty cryptic when dealing with initializers that call `lookup` on the first argument (because the [documented API](http://emberjs.com/api/classes/Ember.Application.html#toc_initializers) for the initializer is to receive the container). Perhaps we should provide a custom wrapper or message for that specific case.

@dgeb - Thoughts?

**Comment by ilkkao** [comment]
I may miss something but wouldn't it be good also to rename the first parameter to initializers in doc examples and ember-cli generators to `registry`?

**Comment by stefanpenner** [comment]
@ilkkao once this is in stable yes

**Comment by dschmidt** [comment]
So currently there is no proper way to do this? 

What I'm doing: I'm getting a service from the container to register a global callback for a popup window. I came up with instantiating it myself and using instantiate: false. Is there a better way? 
And of course I could just bypass this for the moment with _defaultContainer.lookup if you say the real solution is only coming up.

**Comment by tomdale** [comment]
This should be addressed emberjs/website#1951.

**Comment by stefanpenner** [comment]
this seems to have gone stale
