### ISSUE TITLE
Refreshing model in a different route based on query params behavior has changed

### ISSUE THREAD

**Issue by kimroen** [emberjs/ember.js#10081]
We have a case in our app where we have filters in a `products`-route, and then display the result of those filters in `products/index`.

We achieve this by having query-params on the `products`-controller

```js
// controllers/products.js
queryParams: ['category'],
category: null
```

and then have the model in `products/index` refresh when this changes

```js
// routes/products/index.js
queryParams: {category: {refreshModel: true}}
```

The model stopped refreshing when we updated to Ember 1.9.1 yesterday. I didn't see anything about this change in the changelog, so I'm assuming it's not intentional. Please correct me if I'm wrong.

---

Here is a simplified example of this that works in 1.8.1:
http://emberjs.jsbin.com/konuze/2/edit

and doesn't work in 1.9.1:
http://emberjs.jsbin.com/kepudu/2/edit

(and in 1.10.0-beta.3 for good measure: http://emberjs.jsbin.com/divaqe/1/edit)

**Comment by vicentereig** [comment]
@kimroen I've got a similar set up to your server-side filtering/sorting: I defined the `queryParams` in the `parent` route while manipulating them from the `parent/index` controller.

After updating today from `1.8.1` to `1.11.1` started seeing exactly the same issue: query params in the URL were being updated without reloading the model in the route.

As @andrewbranch, by moving my `queryParams: {}` definition to the `parent/index` route and aliasing some computed properties to let the `parent` controller persist the filtering criteria I've got everything working as expected again.

Also @andrewbranch big thanks, haven't touch this part of the code in months already, and I found myself clueless with a bunch of tests failing. :+1:

**Comment by sethkinast** [comment]
@vicentereig how are you communicating the state of the query params up to the parent controller? Are you coupling the two controllers together?

**Comment by jfelchner** [comment]
@kimroen all you have to do is move the `refreshModel` bit also into the parent route and it'll work as you expect.

**Comment by rwjblue** [comment]
From the last few comments this issue looks to be resolved.
