### ISSUE TITLE
discussion about swapping out top level dynamic segments while preserving others

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember.js#10094]
I didn't get much love on [SO](http://stackoverflow.com/questions/27710301/ember-js-swap-out-a-nested-resource-from-any-route), so I created [ember-cli-transition-to-dynamic](https://github.com/kellyselden/ember-cli-transition-to-dynamic/) as an addon.

The problem was with a route system like `/:locale/products/:product_id/items/:item_id`, I want to swap out locales while preserving the rest of the route's state. Here is the implementation I came up with:

```javascript
function transitionToDynamic(name, segments) {
  var routes = this.router.router.currentHandlerInfos;
  var models = [];
  for (var i = 0; i < routes.length; i++) {
    var params = routes[i].params;
    for (var param in params) {
      if (params.hasOwnProperty(param)) {
        models.push(segments[param] || params[param]);
      }
    }
  }

  var args = models.slice();
  args.unshift(name);
  this.transitionTo.apply(this, args);
}
```

And it would be called like:

```javascript
actions: {
  localeChanged: function(locale) {
    var currentRouteName = this.controllerFor('application').get('currentRouteName');
    this.transitionToDynamic(currentRouteName, { locale: locale });
  }
}
```

You pass in a hash of matching segments to replace and the rest are preserved. A few questions I have are is there a better way to do this, is it flawed, does it have a place in the main ember code, or is it better suited as an addon?

**Comment by kellyselden** [comment]
@igorT care to take another look at this?

**Comment by rwjblue** [comment]
In general, we should transition the discussion to rfcs repo in https://github.com/emberjs/rfcs/issues/39.
