### ISSUE TITLE
Ember 1.9.1 IE8 Object does not support this property or method

### ISSUE THREAD

**Issue by zyllorion** [emberjs/ember.js#10113]
Ember 1.9.1
Ember-cli 0.1.5
jQuery 1.11.2
ember-data 1.0.0-beta.14.1

ember.js/packages/ember-runtime/lib/mixins/enumerable.js
```
Line 626:
      every: function(callback, target) {
>>>        return !this.find(function(x, idx, i) {
          return !callback.call(target, x, idx, i);
        });
      }
```
Object doesn't support this property or method.

Using the following in Brocfile.js
```
var app = new EmberApp({
    vendorFiles: {
        'es5-shim.js': 'bower_components/es5-shim/es5-shim.js',
        'es5-sham.js': 'bower_components/es5-shim/es5-sham.js'
    }
});
```

**Comment by zyllorion** [comment]
Closing - removal of shim/sham definition fixed it.

**Comment by runspired** [comment]
@zyllorion can you specify more clearly what fixed it?  I'm on the same packages as you are with this error, and I get it with or without including those vendorFiles.

**Comment by zyllorion** [comment]
I updated to latest versions and removed any manual devinition of the shim, Ember has migrated code directly across making another library unnecessary.
