### ISSUE TITLE
Legacy bindAttr throws "undefined is not a function"

### ISSUE THREAD

**Issue by mitchlloyd** [emberjs/ember.js#10116]
With the latest Canary (1.11.0-beta.1+canary.d13a87b4), I noticed that using the deprecated `bindAttr` helper threw an "undefined is not a function" error at this line:

https://github.com/emberjs/ember.js/blob/e1e8b72c0a46cf47f537c20dedbfb90b66919c28/packages/ember-htmlbars/lib/helpers/bind-attr.js#L225

It seems that the bind-attr helper is an object and not a function as expected.

My `bind-attr` helper looks like this in the console:

![screen shot 2015-01-02 at 2 40 17 pm](https://cloud.githubusercontent.com/assets/15169/5598981/513df8e0-928d-11e4-8b02-1029940c063a.png)

The `bind-attr` works without a problem, only using the deprecated `bindAttr` syntax throws an error.

**Comment by rwjblue** [comment]
Submitted https://github.com/emberjs/ember.js/pull/10118 to fix.

**Comment by rwjblue** [comment]
@mitchlloyd - Thanks for reporting!
