### ISSUE TITLE
Em.computed.sort triggers computed property twice

### ISSUE THREAD

**Issue by catc** [emberjs/ember.js#10133]
I'm having problems with `Em.computed.sort` which seems to be triggered twice and ends up causing a bunch of other issues in my app.

See [my SO question](http://stackoverflow.com/questions/27760775/em-computed-sort-triggers-computed-property-twice) or [my jsbin](http://jsbin.com/gejizuquku/1/edit?html,js,output) for a simplified version.

Basically, one of the components in my app copies or maps the model, sorts it, slices it, and then loops through the data.

```javascript
// initial property copied
initial: function(){
    return this.get('model').slice()
}.property('model'),

// sorted
sortProp: ['age:desc'],
sorted: Ember.computed.sort('initial', 'sortProp'),

// slice it and then loop through it - this function runs twice
final:  function(){
    return this.get('sorted').slice(0, 5)
}.property('sorted.[]'),
```

The issue is that the `final()` is triggered twice when the model is changed. The first time `final()` runs, `Em.computed.sort` is still using data from the old model (which contains 3 items). Only during the second time does `Em.computed.sort` use the new, updated model data (which contains 4 items). 

I'm not sure as to why the sort function runs twice - whether I messed something up or it's actually a bug.

**Comment by ahacking** [comment]
This is a known issue: https://github.com/emberjs/ember.js/issues/9462

**Comment by wagenet** [comment]
Closing in favor of the meta.
