### ISSUE TITLE
computed property not firing on change

### ISSUE THREAD

**Issue by joshpfosi** [emberjs/ember.js#10145]
So I have a lesson and student model with a one-to-one association and the following computed properties in my controller:

    unscheduledLessons: Em.computed.filterBy('content', 'student', null),
    upcomingLessons: function() {
        var lessons = this.get('content');
        return lessons.filterBy('student', this.get('student'));
    }.property('content@each.student'),

and actions: 

    actions: {
      scheduleLesson: function(lesson) {
        lesson.set('student', this.get('student'));
        lesson.save();
      },
      cancelLesson: function(lesson) {
        lesson.set('student', null);
        lesson.save();
      }
    }

When scheduling or canceling a lesson, `unscheduledLessons` gets appropriately updated but `upcomingLessons` is never called. It is called when page loads, but not when I am changing the student property via actions. I believe this idiom should work but I run into this issue a lot with Ember so I'm wondering if I'm doing something obvious wrong.

**Comment by brzpegasus** [comment]
Did you mean `content.@each.student` instead of `content@each.student`?

**Comment by joshpfosi** [comment]
Wooow, yes I did. Thank you!
