### ISSUE TITLE
1.10 beta packages do not include ember.debug.js

### ISSUE THREAD

**Issue by indirect** [emberjs/ember.js#10148]
Even though the [tagged builds page](http://emberjs.com/builds/#/tagged) includes `ember.debug.js`, in the Ember 1.10-beta.3 release, the bower package of 1.10.0-beta.3 does not include the file. Instead, the bower package only includes `ember.js`. This leads to a console warning about using `ember.debug.js`.

**Comment by rwjblue** [comment]
Fixed in components/ember@42b2b5c and updated the tagged build.

**Comment by indirect** [comment]
Thanks!
