### ISSUE TITLE
Removed 'content' property from relationships in ember 1.9.1

### ISSUE THREAD

**Issue by engma** [emberjs/ember.js#10142]
This used to work just fine in ember
```js
//each segment has many messages
var messages = segment.get("messages");

//then to get the plain array
var messagesArray = messages.get("content");
```

But now I need to do this

```js
var messagesArray = messages.get("currentState");
```

**Comment by fivetanley** [comment]
This should be mentioned in the blog post, but is there a reason you need to get at the plain array here?

**Comment by fivetanley** [comment]
Also, can you reopen on github.com/emberjs/data ? This is a beta.14 issue.

**Comment by engma** [comment]
Now its opened on github.com/emberjs/data [#2665](https://github.com/emberjs/data/issues/2665)
