### ISSUE TITLE
Add index as an optional parameter to #each block params

### ISSUE THREAD

**Issue by tim-evans** [emberjs/ember.js#10158]
I would like to change the DOM styling of items according to their position.
The following image is an example of doing so in our app:

![screen shot 2015-01-06 at 11 16 48 am](https://cloud.githubusercontent.com/assets/177701/5631552/8f41887c-9595-11e4-94ae-c7a0e6967bb4.png)

I would ideally like to write components that look at its index for rendering different display information:

```handlebars
{{#each emailAddresses as |emailAddress index|}}
  {{email-address-item email=emailAddress index=index}}
{{/each}}
```

**Comment by fivetanley** [comment]
this would be amazing. I wonder if you can have multiple block params. @mmun @mixonic @rwjblue

**Comment by stefanpenner** [comment]
@fivetanley you can (or will be able to). The index here would be lovely..

**Comment by mmun** [comment]
@tim-evans This should be easy to add if you're up for it. I think you can just add it here https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/views/collection_view.js#L360.

**Comment by tim-evans** [comment]
Ok! It seems strange that the test for this belongs in ember-htmlbars. It's a tad confusing
