### ISSUE TITLE
Disconect outlets issue

### ISSUE THREAD

**Issue by aexmachina** [emberjs/ember.js#10154]
When a `Route#redirect` method returns a Promise, it can lead to outlets being disconnected and not being reconnected when the Promise resolves with a `transitionTo()` the same path. See [example here](http://jsbin.com/tikaci/6/edit?html,js,output).

**Comment by stefanpenner** [comment]
can you confirm this on release/canary?

**Comment by stefanpenner** [comment]
@ef4 I believe you may have sorted this out (maybe)

**Comment by ef4** [comment]
The provided jsbin still reproduces the problem under 1.13.4.

**Comment by Serabe** [comment]
Still happening in [2.5.0](https://ember-twiddle.com/7ea8711ed5c55f6f4fc4054b70cbe353?openFiles=twiddle.json%2C&route=%2Ftest) and canary too (cannot show, saving to a gist returns commit invalid error).

**Comment by Serabe** [comment]
This is still happening in 2.11.0. Marking as inactive.

**Comment by pixelhandler** [comment]
Closing, this has been inactive for some time
