### ISSUE TITLE
HTMLBars helper passing SimpleStream in params (1.10.0-beta3)

### ISSUE THREAD

**Issue by QuantumKing** [emberjs/ember.js#10153]
I have a helper
```js
Ember.HTMLBars.registerHelper('human-readable-type', function(params) {
  switch (params[0]) {
    case 'information':
      return 'Information'
    case 'text':
      return 'Freeform Text'
    ...
  }
});
```
and I call it in my template as 
```hbs
{{unbound human-readable-type type}}
``` 
and it works but if I remove `unbound` it stops working and if I print params it gives me a `SimpleStream`. What's going on here?

**Comment by mmun** [comment]
@QuantumKing That's working as expected. If you want Ember to take care of the stream stuff for you then you should use

```
var helper = Ember.HTMLBars.makeBoundHelper(function(params) {
  switch (params[0]) {
    case 'information':
      return 'Information'
    case 'text':
      return 'Freeform Text'
    ...
  }
});

Ember.HTMLBars.registerHelper('human-readable-type', helper);
```

**Comment by QuantumKing** [comment]
@mmun So I need to do that for every bound helper now?

**Comment by QuantumKing** [comment]
Why not have a `registerBoundHelper` which wraps it for you?

**Comment by mmun** [comment]
We could.

**Comment by mmun** [comment]
I think we will. You can shim it yourself for now:

```js
Ember.HTMLBars.registerBoundHelper = function(name, helper) {
  var boundHelper = Ember.HTMLBars.makeBoundHelper(helper);
  Ember.HTMLBars.registerHelper(name, boundHelper);
};
```

**Comment by mmun** [comment]
@QuantumKing Out of curiosity, are you using `Ember.Handlebars.helper` to register helpers?

**Comment by QuantumKing** [comment]
@mmun No I'm not. In your previous example, for registering view helpers, would you replace `Ember.HTMLBars.makeBoundHelper` with `Ember.HTMLBars.makeViewHelper`?

**Comment by QuantumKing** [comment]
Right now I'm using
```js
  var registerBoundHelper =  function (name, helper) {
    return Ember.HTMLBars.registerHelper(name,
      helper.prototype instanceof Ember.View ||
      helper === Ember.View ? 
        Ember.HTMLBars.makeViewHelper(helper) :
        Ember.HTMLBars.makeBoundHelper(helper));
  };
```
to simulate previous behaviour.

**Comment by mmun** [comment]
I don't want to conflate bound helpers with view helpers (which will become deprecated anyways). I prefer a separate registerViewHelper.

**Comment by QuantumKing** [comment]
Ok, well thanks for you help @mmun . Really appreciate it!

**Comment by MichaelVdheeren** [comment]
This needs some serious documentation. But I like the new approach with streams and how the arguments are passed to the helper. Much cleaner.

**Comment by rwjblue** [comment]
I am not in favor of separate `registerBoundHelper` and `registerViewHelper` functions.  In a modules world (ember-cli specifically), you simply `export default Ember.HTMLBars.makeBoundHelper(fn)` or `export default Ember.HTMLBars.makeViewHelper(SomeViewOrComponent)`.  Once that is done, all you do is `registerHelper('whatevername', importedThing);`  no need for separate functions at all, and keeping the API relatively small and composable has much better results than trying to make every single possible scenario a single function call.

**Comment by rwjblue** [comment]
`registerBoundHelper` and `registerViewHelper` are absolutely possible to make as an addon if folks want a "everything but the kitchen sink" style API.  I strongly prefer to keep our public API very focused at this point.

**Comment by fivetanley** [comment]
'registerBoundHelper` being:

```javascript
Ember.HTMLBars.registerBoundHelper = function(name, callback){
  Ember.HTMLBars.registerHelper(name, Ember.HTMLBars.makeBoundHelper(callback);
};
```

Doesn't seem to crazy for the common glue you would normally do for this sort of thing. To me, it's the kind of common patterns Ember wraps up and does the glue code for you, rather than you manually wiring things together yourself. It seems like a burden to put on the user for upgrading to 2.0 if they are not using ember-cli in a 2.0 world.

**Comment by rwjblue** [comment]
@fivetanley - In ember-cli you are supposed to `export default Ember.HTMLBars.makeBoundHelper(fn)` from your helper module, at that point `Ember.HTMLBars.registerHelper` is **exactly** what you want.
