### ISSUE TITLE
Ember application not booting when in safari private mode

### ISSUE THREAD

**Issue by KillaPL** [emberjs/ember.js#10167]
Hello everyone.

I have the most interesting problem which I cannot solve. I have been able to come to an agreement with Ember about everything I needed (very well done job and thanks for all of it!). The problem I'm having is that the app will simply not start when opened in safari private mode. There is no bug, no error in console, nothing. I am aware of the localStorage issue, as it was problem before (then the application would load properly).

What I know:
  - App works properly in private mode in chrome and firefox
  - App works properly in safari in non-private mode
  - Application used to initialize and work properly in one earlier versions. We started development at ember 1.6.0 and current version is at 1.8.0.

The url for current production version (though not very impresive) is mytennishotel.com

I am aware that I'm giving not very useful informations, but most of our users is likely to use this 
configuration. My boss is willing to donate to ember if you guys help us to solve this problem.

I can provide a whole lot more details if asked.

**Comment by fivetanley** [comment]
Can you try with a more up to date version of ember?

* 1.9.1
* 1.10 beta
* Canary

**Comment by KillaPL** [comment]
Will do. I'll get back to you once I've updated the thing to 1.9.1.

**Comment by fivetanley** [comment]
I'll start looking into more advanced ways to debug this, I'm hoping someone from the webkit/safari teams has some info. @stefanpenner do you know anybody?

**Comment by KillaPL** [comment]
I did the update and initial checks on iphone show no change. I should be able to push these changes to production tomorrow.

**Comment by KillaPL** [comment]
After update to 1.9.1 the console does indeed return an error:

    QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.

And as one would expect, I did find a localStorage calls in our application code. safari/private localStorage issue is really a pain in the back.

As far as the issue goes, the problem is actually fixed. 

Question that remains is: Why was there no error in 1.8.0? 
Once localstorage was removed from the place I used it, I had an infinite page reload loop in chrome. Maybe ember killed the error message on the way up?

On mytennishotel.com there is still a version that does not load and throws the error. It seems to leak in ember file, do you guys want to investigate it or do we close the issue?

**Comment by jayphelps** [comment]
@KillaPL just in case it wasn't known: `localStorage` is *not* available in Safari's Private Browsing mode by design. You'll need to feature detect whether it's available or not and act accordingly. See here for more info, unrelated to ember: https://github.com/marcuswestin/store.js/issues/42

**Comment by stefanpenner** [comment]
> Question that remains is: Why was there no error in 1.8.0?

i wonder if ember swallowed the error but it was their all along.

**Comment by KillaPL** [comment]
Sure, thanks for your time and sorry It didn't actually bring any value.

**Comment by jayphelps** [comment]
@KillaPL you might actually be surprised at the value! I'm sure you're not the only one who will notice this change and this ticket helps others correlate and diagnose their symptoms, so your debugging certainly isn't in vain.
