### ISSUE TITLE
attribute binding override

### ISSUE THREAD

**Issue by miguelcobain** [emberjs/ember.js#10176]
Couldn't find any information on this.

I'm trying to extend some behaviour of `Ember.TextField`. I'm trying to add some logic for `type="datetime-local"` inputs, to be able to bind date-typed variables directly.

As we know, input values are strings, not dates. So in my new class that extends `Ember.TextField` I need a new property to be bound to the input that is basically a date converted to a string that the input expects.
Ideally I would like to reopen `Ember.TextField` and then only apply this logic *if the input type is `datetime-local` and the bound value is a `Date`*.

My 2 questions are:

1. Is there any way to change an attribute binding defined in a superclass?
If it were possible I could just write `attributeBindings:['value:textValue']` in my View/Component subclass. This would override the previous `value` binding definition from `Ember.TextField`.
2. Is this date binding support feature desired in the core?

**Comment by trek** [comment]
This is a great question for StackOverflow. We try to use Issues only for reporting bugs. You can check the contributing guidelines https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md for information about ways to post.

Please link the StackOverflow question back here when you've posted.

**Comment by trek** [comment]
@miguelcobain where you able to post this to SO and get help?

**Comment by miguelcobain** [comment]
@trek, yes: http://stackoverflow.com/questions/27906553/how-to-override-attribute-bindings-in-emberjs/27921578#27921578

There is a working solution, but I'd rather see Ember supporting something like "overridable concatenated properties", or "overridable attribute/class bindings".

**Comment by miguelcobain** [comment]
Is a pull request for this feature desired?
