### ISSUE TITLE
Parent component willDestroyElement not called

### ISSUE THREAD

**Issue by neverfox** [emberjs/ember.js#10189]
I have a component that is an extension of another, and while the willInsertElement chain works when I uses `@_super()`, the `willDestroyElement` chain doesn't.

```coffeescript
MyComponent = Ember.Select.extend
    didInsertElement: ->
      console.log "Did Insert MyComponent"
      @_super()

    willDestroyElement: ->
      console.log "Will Destroy MyComponent"
      @_super()

MyExtendedComponent = MyComponent.extend
    didInsertElement: ->
      console.log "Did Insert MyExtendedComponent"
      @_super()

    willDestroyElement: ->
      console.log "Will Destroy MyExtendedComponent"
      @_super()
```

```
Did Insert MyExtendedComponent
Did Insert MyComponent
Will Destroy MyExtendedComponent
// nothing about destroying MyComponent
```

I'm on 1.7.0-beta.5

**Comment by neverfox** [comment]
Arg! There was a typo. My parent had a `willDest**or**yElement`

**Comment by trek** [comment]
It would be nice if there was some way, possible through inspector, to have not just logging but stepping through view/route, etc lifecycle on demand. @teddyzeenny does that sound reasonable or just I'm just handwaving around describing magic?

**Comment by teddyzeenny** [comment]
@trek if I understand correctly, you mean something like "pause on lifecycle hook", where we can click "next hook" to continue?  Unless we can use something like a `debugger` breakpoint that halts JS execution, we'd need built-in async support, where we can return blocking promises to halt a transition (which seems currently more feasible in routes than in views). 
I don't have enough info to know if it's possible, but let's look into it.

**Comment by trek** [comment]
@teddyzeenny that's exactly it. With all the automatic resolution of objects, it's very easy to get trolled with silent failures from misspellings or placing items in the wrong place. After a while you get used to double checking, but I think it would very obvious if you walked through lifecycle and we had messages like "called didInsertElement on view 1212, subclass of <View>, generated by the framework"
