### ISSUE TITLE
Using '.[]' syntax in notEmpty computed properties can cause computed arrays not to function

### ISSUE THREAD

**Issue by bendemboski** [emberjs/ember.js#10181]
# Summary
Creating an ```Ember.computed.notEmpty``` whose source property uses the ```'.[]'``` syntax produces a property that will cause array computed properties that reference it to misbehave. The same is true of ```Ember.computed.empty```, and I believe that this means that https://github.com/emberjs/ember.js/commit/32a4df8865850793d37dd75bc76bf7e26f2d9047 (and the ```Ember.computed.empty``` change in Ember 1.6 that this commit references) were actually breaking changes. This may actually be a more general problem with any computed property that depends on ```.[].length```.

# Sample code
Also in this jsfiddle: http://jsfiddle.net/NQKvy/1575/

```javascript
var Item = Ember.Object.extend({
        children: null,
        hasChildren1: Ember.computed.notEmpty('children.[]'),
        hasChildren2: Ember.computed.notEmpty('children')
    }),
    Collection = Ember.Object.extend({
        items: null,
        withChildren1: Ember.computed.filterBy('items', 'hasChildren1', true),
        withChildren2: Ember.computed.filterBy('items', 'hasChildren2', true)
    }),
    col = Collection.create({ items: [ Item.create({ children: [] }) ] });

Ember.assert("First item doesn't have children (1)", !col.get('items.firstObject.hasChildren1'));
Ember.assert("First item doesn't have children (2)", !col.get('items.firstObject.hasChildren2'));
Ember.assert("withChildren1 is empty", col.get('withChildren1.length') === 0);
Ember.assert("withChildren2 is empty", col.get('withChildren2.length') === 0);

col.get('items.firstObject.children').pushObject(1);

Ember.assert("First item has children (1)", col.get('items.firstObject.hasChildren1'));
Ember.assert("First item has children (2)", col.get('items.firstObject.hasChildren2'));
Ember.assert("withChildren1 is not empty", col.get('withChildren1.length') !== 0);
Ember.assert("withChildren2 is not empty", col.get('withChildren2.length') !== 0);
```

None of the assertions should fire, but the second-to-last one does. In other words, when an aggregated property in an array computed property is a ```notEmpty``` that uses the ```.[]``` syntax, the array computed property will not update properly.

# Severity
This causes array computed properties using these computed properties as their keys to not function, which I think is pretty severe. I know that there is no need to use the ```.[]``` syntax anymore, but there used to be, and this bug caused a nasty regression in some of my code that was still using the ```.[]``` syntax. In other words, it looks like the change that removed the need for ```.[]``` was an unintentionally-breaking change. So I think this bug should be fixed -- or at the very least there should be a deprecation warning about using the ```.[]``` syntax.

# Investigation of the cause
I did some further investigation to get closer to the source of the issue. It looks like the immediate problem is that ```DependentArraysObserver.itemPropertyWillChange``` fires twice for ```hasChildren1```, but ```DependentArraysObserver.itemPropertyDidChange``` only fires once, ```changedItemCount``` remains at ```1``` and the array changes for ```withChildren1``` are never flushed.

```itemPropertyWillChange('hasChildren1')``` is firing twice with the following two pseudo-stacks:

```
DependentArraysObserver.itemPropertyWillChange('hasChildren1')
...
propertyWillChange('hasChildren1')
...
propertyWillChange('children.[].length')
...
propertyWillChange('[]')
...
Array.enumerableContentWillChange()
...
Array.pushObject()
```

and

```
DependentArraysObserver.itemPropertyWillChange('hasChildren1')
...
propertyWillChange('hasChildren1')
...
propertyWillChange('children.[].length')
...
propertyWillChange('length')
...
Array.enumerableContentWillChange()
...
Array.pushObject()
```

```itemPropertyDidChange('hasChildren1')``` looks like it should fire twice because ```enumerableContentDidChange``` calls ```propertyDidChange``` for ```length``` and then for ```[]```, but it doesn't.

When we reach the following pseudo-stack:

```
propertyDidChange('hasChildren1')
...
propertyDidChange('children.[].length')
...
propertyDidChange('length')
...
Array.enumerableContentDidChange()
...
Array.pushObject()
```

```desc.didChange()``` is executing, which calls ```removeDependentKeys()```, so that by the time we get here:

```
propertyDidChange('[]')
...
Array.enumerableContentDidChange()
...
Array.pushObject()
```

we are no longer watching (```m.watching['[]'] === 0```) and we return instead of calling back through to ```itemPropertyDidChange()``` again.

At this point I'm pretty well out of my depth, and hoping to hand this off to an expert that can further diagnose and fix the problem :)

**Comment by stefanpenner** [comment]
computed arrays / reduce computed are gone, in-favour of naive sort/filter/map in GP, with glimmer using is data diffing to efficiently handle render
