### ISSUE TITLE
set() uses strict equality

### ISSUE THREAD

**Issue by ryanbradynd05** [emberjs/ember.js#10182]
Currently, Ember.set() uses strict equality (!==) to compare the current and new values to determine if the object should be updated. This works for primitives, but not for dates and objects.  If you call set('objectName', objectVal) it will update since the strict equality will always fail. Ember.isEqual already has a method to compare objects that implement the .isEqual() function. By using the same check in set(), the object's object and date properties would only be updated if the values have actually changed.

I've modified my ember fork to fix this issue and added tests. All tests are passing [here](https://github.com/ryanbradynd05/ember.js/commit/741703da0cadcb9570a98da4939416d3278eb1ad)

Is there any reason why this shouldn't be included in the core Ember build?

**Comment by cowboyd** [comment]
see #10166

**Comment by rwjblue** [comment]
Closing in favor of the PR.

**Comment by ryanbradynd05** [comment]
@cowboyd Thanks, not sure how I missed your PR. I applied the code from your PR to my repo and all the tests still ran. Looks good.
