### ISSUE TITLE
IE8: WARNING: You're attempting to render a view by passing propertyBinding to a view helper without a quoted value, but this syntax is ambiguous. You should either surround propertyBinding's value in quotes or remove `Binding` from propertyBinding.

### ISSUE THREAD

**Issue by zyllorion** [emberjs/ember.js#10196]
IE8
Ember 1.10.beta4
ember-cli 1.0.6

```
WARNING: You're attempting to render a view by passing propertyBinding to a view helper without a quoted value, but this syntax is ambiguous. You should either surround propertyBinding's value in quotes or remove `Binding` from propertyBinding.
```
for code snippet:
```
{{#with model.myModel.details as detail}}
{{dl-property label="testlabel" property=detail.category}}
```
Works fine in Chrome with no errors.  If I wrap detail.category in quotes it doesn't give the warning but of course just passes the string not the object.

I also get the following two errors I havn't yet isolated but very likely related as they also do not appear in Chrome:
```
WARNING: You're attempting to render a view by passing dataSourceBinding to a view helper without a quoted value, but this syntax is ambiguous. You should either surround dataSourceBinding's value in quotes or remove `Binding` from dataSourceBinding.
```
```
WARNING: You're attempting to render a view by passing textBinding to a view helper without a quoted value, but this syntax is ambiguous. You should either surround textBinding's value in quotes or remove `Binding` from textBinding.
```

**Comment by trek** [comment]
Can you use a property name other than `property` and let us know if the problem persists? I suspect that is the issue.

**Comment by zyllorion** [comment]
Sorry no luck!

WARNING: You're attempting to render a view by passing ddBinding to a view helper without a quoted value, but this syntax is ambiguous. You should either surround ddBinding's value in quotes or remove `Binding` from ddBinding.

Wouldn't be surprised if it's related to the setAttribute comment on this:
https://github.com/tildeio/htmlbars/issues/241#issuecomment-69059652

**Comment by mmun** [comment]
@zyllorion: This is only happening in IE8?

**Comment by wagenet** [comment]
@zyllorion have you given it a try on canary?

**Comment by rwjblue** [comment]
Based on @zyllorion's comments in a related HTMLBars issue, I believe this is resolved.

Closing (but happy to reopen if needed).

**Comment by rjfranco** [comment]
I'm actually running into this issue now, I tried to follow @zyllorion 's comment under htmlbars, but I couldn't find anything similar that I was doing, any tips on narrowing down what in my code could be causing this issue?



![selfie-4](http://i.imgur.com/9BBUl1x.png)

**Comment by zyllorion** [comment]
Update to latest canary of Ember, there was a bug in htmlbars
