### ISSUE TITLE
{{link-to}} classname `ember-transitioning-in` stuck

### ISSUE THREAD

**Issue by zeppelin** [emberjs/ember.js#10195]
When:

- ember-canary
- The link is pointing to the same route
- `active=false` is set

Repro:

http://emberjs.jsbin.com/guvugalopa/1/edit?html,css,js,output

- Click link `Foo`
- Page transitioned to `Foo route`
- Click link `Foo` again
- Link `Foo`'s background is red (see CSS tab)

`ember-transitioning-in` is removed after transitioning to another route, yet the correct behavior should be to not to show this classname at all, if already on the target route.

**Comment by DerToti** [comment]
This seems stll to be a problem in ember 1.11 beta version.
Is there any workaround for this or is it possible to disable this feature?

**Comment by machty** [comment]
@DerToti a fix is coming shortly, but since all this feature does is apply a CSS class name, you can "disable" the feature by not supplying CSS for `.ember-transitioning-X`.

**Comment by rwjblue** [comment]
Closing in favor of https://github.com/emberjs/ember.js/issues/13164.
