### ISSUE TITLE
queryParams: pluses aren't converted to spaces

### ISSUE THREAD

**Issue by oriSomething** [emberjs/ember.js#10190]
as you can see in this link:
http://uploads.orilivni.com/ember/query-params/

technically it's not a bug because there is no standard to what supposed to be encoded / decoded. but `decodeURIComponent` doesn't convert `+`s to spaces. so right now if i send a link through *facebook* i the receiver will get a link where `%20` is converted to `+` and the link is broken.

the link is ember canary. but i had the same problem with version 1.9.1

thanks

**Comment by wagenet** [comment]
Looks like this is fixed by https://github.com/tildeio/route-recognizer/pull/40.

**Comment by jayphelps** [comment]
@wagenet Can we keep this ticket open until this fix lands in ember.js/master? Since it requires that PR be merged, a version cut, a PR made for ember.js updating it and then it merged, I think it's important to have a record open.

**Comment by rwjblue** [comment]
Reopening until the dep is updated.

**Comment by meghasharma13492** [comment]
I am facing the problem of conversion of space to + in queryParams..
