### ISSUE TITLE
Replace foreach(Array.slice()) in DependentArraysObserver.dependentArrayDidChange

### ISSUE THREAD

**Issue by JHawkley** [emberjs/ember.js#10191]
I noticed a big performance bottleneck in the `ReduceComputedProperty` implementation, primarily in regards to working on larger data sets.

It seems that under certain circumstances, using `Array.slice()` in `DependentArraysObserver.dependentArrayDidChange` to iterate over a sub-section of an array creates a ton of unnecessary work and doubles garbage collection time.  The slice is otherwise not used for anything; an obvious candidate for optimization.

In my case, I am chaining `DS.FilteredRecordArray` -> `Em.computed.sort` -> `Em.computed.filter` on a dataset that grows by 100, for every page retrieved, to 4000 items.

Replacing `forEach(dependentArray.slice(), ...)` with a simple iterator function that traverses `dependentArray` from `normalizedIndex` to `endIndex` improved the performance of the method by nearly 4 times, according to Chrome's performance profiling.

Example implementation:
```javascript
// In packages/ember-runtime/lib/computed/reduce_computed.js...
function runThrough (arr, start, end, ctx, fn) {
  var index, sliceIndex;
  index = start;
  sliceIndex = 0;
  while (index !== end) {
    fn.call(ctx, arr.objectAt(index), sliceIndex);
    sliceIndex++;
    index++;
  }
};

DependentArraysObserver.prototype = {
  //...
  dependentArrayDidChange: function (dependentArray, index, removedCount, addedCount) {
    //...
    runThrough(dependentArray, normalizedIndex, endIndex, this, function(item, sliceIndex) {
      //...
    });
};
```

In my usage case, described above, this refactor took the average time of propagating the changes to the record array, after inserting the 100 items into the store, from around 412ms to 73ms.  That's more than a 5x boost in average performance!

**Comment by stefanpenner** [comment]
reduce/array computed are gone in-favor of naive map/filter/sort + glimmers data diffing.
less bugs, and much faster :)
