### ISSUE TITLE
`attributeBinding` with properties not available in element prototype do not get set.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#10202]
We do a `attrName in element` check to see if a property exists for a given attribute, and if it does we set it as a prop, but if not we use `setAttribute`.  In the case of `novalidate` on `<form>` elements, it is not a property, so we fallback to `setAttribute` (which leads to it not being added to the DOM).

![screenshot](http://monosnap.com/image/KRXWTeYPrE3vViopdH20hRodYE7r38.png)

Demo: http://emberjs.jsbin.com/rwjblue/203/edit

**Comment by rwjblue** [comment]
@mixonic - Can you confirm my summary (I may have the prop/attr thing backwards)?

**Comment by wagenet** [comment]
By the way, it looks like `noValidate` (camelcased) is a property. So `document.createElement('form').noValidate = true` does what is expected. If I camel-case the property then it looks like it works: http://emberjs.jsbin.com/yadawejase/1/edit.

**Comment by mixonic** [comment]
@wagenet there is normalization code that should have caught that. I believe the issue would be in `setProperty`. There are tests around it elsewhere (using maxLength as an example), but perhaps you have unearth a bug in the caching code or something.

**Comment by wagenet** [comment]
It turns out this is not a new regression. It last worked in 1.7 where it rendered `<form novalidate='novalidate'>`.

**Comment by wagenet** [comment]
http://emberjs.jsbin.com/muyakafodi/1/edit

**Comment by kiwiupover** [comment]
I was seeing the same issue in #10183 

Is there anything I can do to help?

**Comment by rwjblue** [comment]
There is no normalization for `attributeBindings` (in 1.9, 1.10, or canary at this point).  The good news is that https://github.com/emberjs/ember.js/pull/10186 should fix this (since it would then go through the normalization that happens in AttrNodes), but sadly I do not think that it will make it to beta (it is a pretty big change to make so late in the beta cycle).

**Comment by rwjblue** [comment]
@kiwiupover - Off the top of my head I do not believe #10183 is related to this, but I'll try to dig around to confirm/deny.

**Comment by kiwiupover** [comment]
@rwjblue thanks. Thanks heaps for all you are doing.

**Comment by mmun** [comment]
Looks like this is working now: http://emberjs.jsbin.com/xuyubejida/edit?html,js,output
Can you confirm @rwjblue ?

**Comment by stefanpenner** [comment]
this behavior is now exactly what we want (and exactly the opposite of what it was.)
