### ISSUE TITLE
Returning a rejected promise prevents the URL from being updated (eagerly)

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#10219]
JSBIN: http://emberjs.jsbin.com/popane/3/edit?html,js,output

To reproduce:

1. Try clicking on "It works". It updates the URL as you would expect.
2. Go back to the index page (back button) and click on "Boom from server". While this causes an error (a 401 response – rejected promise), the URL is still eagerly updated. This allows the back button, refresh button, etc to work correctly.
3. Go back to the index page (back button) and click on "Boom from client". This again causes an error (rejected promise), however the URL was not updated, which breaks the back button (there is no way to go back from here).

I'm not sure where this falls between a bug/improvement/question, so if this is not the right place for it feel free to close it.

From what I can tell in the code, this *might* be "working as expected", because the eager URL update code is aborted if the transition is aborted *in the same runloop*.

However, it is unclear to me *why* this is happening within the same runloop, or how I can work around it. I was under the impression that all the promise publication stuff is happening asynchronously, so I was assuming that returning `RSVP.reject` would return a "in progress" promise, then reject it (or more accurately, publish its rejection) on the next tick, essentially the same semantics as a AJAX request would have.

I suppose I can use a `setTimeout` to work around it, but it feels a bit strange that I need to go out of my way to do that here. It seems like you would almost always want the URL to update eagerly when an error occurs (locally or not), otherwise you would end up with the broken back button problem I mentioned.

There are probably good reasons that it can't work that way though.

cc @machty

**Comment by chancancode** [comment]
In case it helps to understand the context, I came across this and #10218 while working on a tutorial/blog post. I pushed a [draft here](https://github.com/BrewhouseTeam/brewhouseteam.github.io/commit/5da5c78f0ec401b2f188e32afb4217607aa51e68) in case you want to dig deeper into the actual use cases.

**Comment by rwjblue** [comment]
Eager url updating has been removed due to a number of bugs that have cropped up over the last few releases.

**Comment by rwjblue** [comment]
This removal will land in 1.11 initially.

**Comment by chancancode** [comment]
Ah. That's a bummer.

I read up on the related issues leading up the removal of the feature. I completely agree it's a tricky issue a complex one to solve.

This might turn out to be an issue completely unrelated to eagerness of updating the URL, though. The fundamental problem here is that whenever we transition into an error substate, we should have updated the URL at some point, eagerly or otherwise. The reason (as shown in the JSBIN) is that in the final state, the UI of the original route has been torn down and replaced by the error template, and people will probably instinctively reach for the back button, hoping that it will bring them back to the last working state of the app.

This is probably just "temporarily solved by accident" via eager URL updates. (It appears that most of the discussion around the feature is around the loading use case.) As shown here, this already doesn't work for "synchronous" errors today even with eager URL update.

I imagine the "correct" solution here is to make sure we update the URL when we *settled* on an error state. I am not 100% sure *what* that URL would be, though.

**Comment by rwjblue** [comment]
@chancancode - My initial response was a bit "from the hip" (was on my mobile and couldn't really review the JSBin in detail) mostly just to let you know that the eager updating feature was removed in case that was fundamental to the issue. I'll try to review in more detail soon.

**Comment by chancancode** [comment]
That response was very helpful :) I was able to find the related materials and understand the background for this!

**Comment by chancancode** [comment]
Since eager URL is on its way out, I'm closing this for now! I'll open a new ticket about the other issue (that URL/history state should change when entering the error state, so back button works).

**Comment by lnaravindan** [comment]
@chancancode @rwjblue I am too facing the same issue. My use case is similar as I need the URL to be updated whenever a transition goes to error state. 

Whenever we end up at a error page, as a user we tend to do two things. 
1. Press back button to go the previous ( page. 
2. Press refresh button to retry the failed page. 

With url not updated, both these can't be done. 

Any suggestions on how to resolve this?
