### ISSUE TITLE
End-to-End Testing using Selenium WebDriver

### ISSUE THREAD

**Issue by jefflage** [emberjs/ember.js#10216]
We're starting to think about using an approach similar to Protractor to allow writing end-to-end acceptance tests in Node that use the Selenium WebDriverJS bindings.  From looking through the Protractor guides/source, I've noticed that angular directly exposes a way to know that all timers/events/pending updates have been flushed and the application is back in steady state.  is there an official way to do the same with ember?

**Comment by stefanpenner** [comment]
good question, but this seems like a better question for stackoverflow, or our discourse forum, as it is not a bug.

If something is broken that prevents this from working, please feel to reopen.

**Comment by marcenuc** [comment]
For reference, here's the question on StackOverflow: http://stackoverflow.com/q/26811282/453605
And here's the related discussion on Protractor tracker: https://github.com/angular/protractor/issues/1507
