### ISSUE TITLE
Include `features.json` in development build

### ISSUE THREAD

**Issue by tomdale** [emberjs/ember.js#10212]
Currently, doing a dev build of Ember.js does not take `features.json` into account. This is bad because it means that there will be features missing, even those that have been promoted to the beta channel. This is exacerbated on master right now due to the fact that Handlebars support has been removed, but HTMLbars is still behind a feature flag, so development builds are broken out of the box.

(This ticket filed at the request of @rwjblue.)

**Comment by twokul** [comment]
@tomdale @rwjblue should we move this issue to emberjs-build?
