### ISSUE TITLE
Click testing helper doesn't trigger focusIn on contenteditable element

### ISSUE THREAD

**Issue by paddyobrien** [emberjs/ember.js#10229]
See: http://jsfiddle.net/tdc6tx2j/1/

It [looks like](https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/helpers.js#L41) `focusIn` is only fired on inputs, however it seems to me to make sense to fire it on any element with contenteditable.

Happy to fix myself if this seems reasonable.

**Comment by mixonic** [comment]
@paddyobrien having only looked at how contenteditable and focus work together for a few moments, this seems a reasonable thing to support. Focusing on a contenteditable is indeed a thing, as I demo here (in case anyone else is curious):

http://jsfiddle.net/tdc6tx2j/2/

**Comment by paddyobrien** [comment]
Sweet, I'll get a PR together over the weekend.
