### ISSUE TITLE
Weird issue with Mixin.detect()

### ISSUE THREAD

**Issue by aexmachina** [emberjs/ember.js#10222]
Issue #1146 provides instructions for checking whether a class has a Mixin. I've found the following weirdness though when trying to use these methods:

http://emberjs.jsbin.com/pokemu/1/edit

I'd love to offer a suggestion, but it just doesn't make sense to me :)

**Comment by xtian** [comment]
@aexmachina I think this might better demonstrate the issue you're running into here: http://emberjs.jsbin.com/zulapusuqi/1/edit?js,output

Calling `create` on a class with a mixin seems to cause its prototype to be mutated such that `Mixin#detect` returns true. When your `check` function calls `extend` on `klass` a second time, a new class isn't created, thus the side-effects from calling `create` persists.

In your second test, a new class *is* being created, however, so `Mixin#detect` returns false for that prototype.

**Comment by aexmachina** [comment]
Okay, so the outcome here is that `FooMixin.detect(Klass.PrototypeMixin)` is the only bulletproof way to detect whether a class contains a given Mixin. It'd be nice to improve this, or we can just close the issue and leave it at that.

**Comment by stefanpenner** [comment]
This is working as expected.

Class inherits from Mixin, Classes have different Mixins then Instances.


```
var MyMxin = Ember.Mixin.create();
var MyOtherMIxin = Ember.Mixin.create();

MyObject.reopen(MyMixin); // apply the mixin to the eventual mixins
MyObject.reopenClass(MyOtherMIxin); //  apply the mixin to the class
```
