### ISSUE TITLE
Sortable Mixin assuming arrangedContent is always sorted

### ISSUE THREAD

**Issue by Vincz** [emberjs/ember.js#10225]
The Sortable Mixin assume that the arrangedContent array is always sorted.
This leads to invalid ordered results if the sortProperties are modified in bulk (using beginPropertyChanges / endPropertyChanges).

All the performed sort operations are using comparaisons between an item and the item on the left and on the right. This is invalid if the underlying data have already been updated.

Here is a jsbin illustrating the problem. Click on the "reorder" link multiple times and check the console to see the problem.

http://emberjs.jsbin.com/ciparonami/1/edit

**Comment by stefanpenner** [comment]
SortableMixin and ArrayControllers are deprecated, so this bug is now invalid.

Since glimmer landed, it is suggested to just sort/filter in a CP, and let glimmers data diffing handle the rest.
