### ISSUE TITLE
 Documentation for Child Routes in Getting Started guide is unclear

### ISSUE THREAD

**Issue by egardner** [emberjs/ember.js#10220]
Hi there-

I am trying to wrap my head around Ember.js for the first time, and am working my way through the [Getting Started Guide](http://emberjs.com/guides/getting-started/).

Things are pretty clear until the [Adding Child Routes](http://emberjs.com/guides/getting-started/adding-child-routes/) section. At this point I'm presented with the following instructions:

> Next we will split our single template into a set of nested templates so we can transition between different lists of todos in reaction to user interaction.
>
> In index.html move the entire `<ul>` of todos into a new template named `todos/index` by adding a new Handlebars template `<script>` tag inside the `<body>` of the document:
>...

Where should this file be moved, exactly? Should the user create a `todos/index.html` file? Should it have an extension of `.hbs` instead? I'm coming at this without any prior knowledge of how Handlebars works (a typical situation for newcomers, I'd imagine). The docs just say "move the `<ul>` into a new template", but it's not clear where templates should go or how they should be named.

It would be really helpful if the file structure were more clearly explained at each stage of the process (a tree diagram on each page would be great – the JS Bin has all the HTML in a single file, so it's not clear how things should be organized in the real world).

**Comment by electricgraffitti** [comment]
You would use the .hbs if you are using templates as their own file. I have not dome the tutorial, but most of the time they just add another template in the body tag of the page.

So this would give me two templates

```
<body>
<script type="text/x-handlebars" data-template-name="MYTEMPLATENAME">
  ...html here
</script>

<script type="text/x-handlebars" data-template-name="MYOTHERTEMPLATENAME">
  ...more html here
</script>
</body>
```

Each script tag set is considered a template.

**Comment by egardner** [comment]
Okay, that makes a lot more sense – thanks for clarifying.

It might still be good to emphasize in that guide that templates != individual files. This is a notion of "template" that is quite a bit different from something like Rails. More elaboration on this point in the "Getting Started Guide" would be a good addition I think.

**Comment by mixonic** [comment]
fwiw the guides live in the https://github.com/emberjs/website repo. Please track issues for them there :-)
