### ISSUE TITLE
Opening Ember application from a link with 'target="_blank"' attribute failed to load

### ISSUE THREAD

**Issue by TopQualityUA** [emberjs/ember.js#10233]
I have an Ember application using Torri, and when I open this application from other page with a link whose target attribute has "_blank" tab opens but the application failed to load.

**Comment by TopQualityUA** [comment]
Very similar to this issue https://github.com/Vestorly/torii/issues/92

**Comment by mixonic** [comment]
@TopQualityUA can you recreate this without Torii?

**Comment by TopQualityUA** [comment]
@mixonic i'll try today to recreate without Torii, but i don't think that Torii is reason why ember application is not running.

**Comment by TopQualityUA** [comment]
@mixonic iv'e updated torii to 0.2.2 and all works great.
