### ISSUE TITLE
Router supports didTransition, but not willTransition

### ISSUE THREAD

**Issue by asakusuma** [emberjs/ember.js#10235]
Currently the Router supports the Route [didTransition](http://emberjs.com/api/classes/Ember.Route.html#event_didTransition) event:
```
App.Router = Ember.Router.extend({
      myAfterTransitionHook: function() {
            //stuff       
      }.on('didTransition')
});
```
However, the Router does not support the Route [willTransition](http://emberjs.com/api/classes/Ember.Route.html#event_willTransition) event. In other words, you can't do this:
```
App.Router = Ember.Router.extend({
      myBeforeTransitionHook: function() {
            //stuff       
      }.on('willTransition')
});
```

Is there a specific reason for not supporting willTransition? If not, I'd be happy to submit a PR. I'd like to be able to save/record state right before a transition happens, on a general level, not specific to an individual route. Something along the lines of intercepting any time {{link-to}} happens.

**Comment by chadhietala** [comment]
@asakusuma I think you might be able to achieve what you want using the "activate" and "deactivate" hooks. 

https://github.com/emberjs/ember.js/pull/5569
[Blog Post](http://emberjs.com/blog/2014/12/08/ember-1-9-0-released.html#toc_activate-and-deactivate-events)

**Comment by asakusuma** [comment]
@chadhietala just tried activate/deactivate on Ember 1.9.1, works on Route, as expected, but not on a Router.

Not sure if there's more router code distributed elsewhere, but in [router.js](https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/router.js#L184), there appears to be a line triggering the 'didTransition' event, but I don't see any other events like deactivate or willTransition.

**Comment by jayphelps** [comment]
It would need to be added to [tildeio/router.js](https://github.com/tildeio/router.js/blob/master/lib/router/router.js) since that's where the actual `didTransition` is originally invoked on the router.

Seems fairly trivial, I'll gladly PR (or you can) if core is OK with the addition.

**Comment by asakusuma** [comment]
@jayphelps thanks, I'll wait for an OK from core and then open a PR.

**Comment by stefanpenner** [comment]
seems very reasonable, lets check with mr router to be sure.

**Comment by machty** [comment]
@asakusuma Seems like a good idea to add to router.js/Ember router. :+1: for a PR

**Comment by asakusuma** [comment]
Awesome, I'll submit a PR shortly

**Comment by asakusuma** [comment]
Here's teh tildeio/router PR: https://github.com/tildeio/router.js/pull/144

Once that's in, I'll open another PR in Ember.js

**Comment by chadhietala** [comment]
@asakusuma Looks like tildeio/router.js#144 was merged.

**Comment by asakusuma** [comment]
PR merged, closing, thanks.

**Comment by steph643** [comment]
I have just tried the `willTransition` event in the router and noticed that `transition.abort()` doesn't work (whereas it works as expected in the `willTransition` action in a route). Am I missing something?

**Comment by steph643** [comment]
Also, it seems the `willTransition` event in the router is called for the initial (startup) route, whereas the `willTransition` action is not.
