### ISSUE TITLE
Using protocol relative URLs in REST Adapter can cause issues

### ISSUE THREAD

**Issue by jdreux** [emberjs/ember.js#10248]
When using a protocol relative URL in a REST Adapter, issues happen when attempting to retrieve related models. Example:

Library Adapter:
```
store = DS.Store.extend
    adapter: DS.RESTAdapter.extend
      namespace: ''
      host: '//my.library.com'

  app.register 'library:main', store
  app.inject 'route', 'library', 'library:main'
```

Library Model:

```
Library = DS.Model.extend
  name: DS.attr 'string'
  groups: DS.hasMany 'group', {async: true}
```

When iterating over `library.groups` in a template, I get the following errors: 

`Cannot load http://my.library.com//my.library.com/groups/12341234/assets `

The problem is that the URL is wrong, `http://my.library.com/groups/12341234/assets` is the correct URL. 

Forcing a protocol (`host: window.location.protocol+...`) in the adapter declaration fixes the issue.

**Comment by jherdman** [comment]
I believe your ticket belongs here: https://github.com/emberjs/data/

**Comment by jdreux** [comment]
Opened https://github.com/emberjs/data/issues/2714
