### ISSUE TITLE
Firefox bug: "parentView is undefined"

### ISSUE THREAD

**Issue by QuantumKing** [emberjs/ember.js#10241]
I'm able to run my ember app in both Safari and Chrome but it fails with the error "parentView is undefined" in Firefox. The function in Ember causing the error is
```js
`line: 29809`

function appendView(route, view, options) {
  if (options.into) {
    var parentView = route.router._lookupActiveView(options.into);
    var teardownOutletView = generateOutletTeardown(parentView, options.outlet);
    if (!route.teardownOutletViews) { route.teardownOutletViews = []; }
    replace(route.teardownOutletViews, 0, 0, [teardownOutletView]);
    parentView.connectOutlet(options.outlet, view);
  } else {
    var rootElement = get(route.router, 'namespace.rootElement');
    // tear down view if one is already rendered
    if (route.teardownTopLevelView) {
      route.teardownTopLevelView();
    }
    route.router._connectActiveView(options.name, view);
    route.teardownTopLevelView = generateTopLevelTeardown(view);
    view.appendTo(rootElement);
  }
}
```

**Comment by Dremora** [comment]
I can confirm the same error occurs in Chrome, but only in a built application.

**Comment by QuantumKing** [comment]
@Dremora What do you mean by "built"?

**Comment by Dremora** [comment]
Created by `ember build`. Serve the `dist` folder — you're likely to get the same issue in Chrome.

**Comment by stefanpenner** [comment]
can you provide some steps to reproduce?

**Comment by QuantumKing** [comment]
@stefanpenner Unfortunately its a very big project; I don't know where to start to reproduce the error. It happens on every single route. Also, I'm using Ember 1.10.0-beta.4 with HTMLBars 0.8.1.

**Comment by Dremora** [comment]
In my case it happens on selected routes.
Steps to reproduce:

1. Go to http://my-music.dremora.com/
2. Look up "test'
3. Click on the album which appears in the list
4. Check out the error in the console

The source code is [here](https://github.com/Dremora/my-music-client). To serve, run `ember serve --proxy https://my-music-api.herokuapp.com`. Please note that the bug does not occur while running `ember serve`.

**Comment by evrowe** [comment]
I can confirm this as well; I've seen it in both Ember 1.7 and 1.8.1. Firefox did just release a new version on January 13th, perhaps some change in that release has more to do with the issue? It seems unlikely that this issue would just be lurking around in Ember for this long without notice until suddenly multiple people stumbled across it at the same time.

**Comment by rwjblue** [comment]
We need a reproducible case (JSBin or demo ember-cli app with steps to reproduce the error) to help track it down.

**Comment by evrowe** [comment]
@rwjblue Here is a JSBin demonstrating the problem: http://emberjs.jsbin.com/qubajadino/1/edit

This code works fine in Chrome but fails in Firefox. In this particular case, it appears to have something to do with trying to use `get` to grab the value of a property on the global app object; if you make the following changes to line 19, the errors cease and the app functions normally:

Before:

    if ( !App.get('isAuthenticated') ) {

After:

    if ( !this.get('isAuthenticated') ) {

**Comment by alexdiliberto** [comment]
@Dremora Interesting that you state some things that I'm seeing recently as well. 

My issue is a little similar, it's happening in IE only after you log out of my app, then reload the app homepage in the same browser session you'll get the `Cannot call method 'connectOutlet' of undefined` error. 

But you mentioned that it's not happening when you run `ember serve`, it is only happening on your built app. Wanted to confirm that I'm seeing this behavior as well.

**Comment by ianhoolihan** [comment]
Same issue, though I don't believe it's related to firefox.

I believe the issue is an unknown "into" in `this.render({into: ...})` (motivated by third line of code pasted by @QuantumKing). I've managed to figure out how to use JSbin, so [here's](http://emberjs.jsbin.com/mayiduquti/1/edit?html,js,console,output) a reproducible example (based mainly off the Ember.js guide example). Note the error arises from setting `into: "abc"` in `App.PostRoute`, which is resolved on change to `into: "application"`.

Not sure if this is actually a bug, but maybe a more useful error message could be displayed.

**Comment by QuantumKing** [comment]
@ianhoolihan I am seeing the error without any "into" in my application

**Comment by Dremora** [comment]
I've found the reason this bug appeared in my app. Due to improperly upgraded index.html, both `app.js` and `vendor.js` were included on the page twice (and the markup was slightly broken). [Removing the dupes and fixing the markup](https://github.com/Dremora/my-music-client/commit/d0d994a05f05aa1c756e0dcd9e76fcab7f8ae2ff) has mitigated the issue.

**Comment by wagenet** [comment]
To reiterate, it's unlikely that we'll be able to fix any issue without a JSBin reproduction.

**Comment by evrowe** [comment]
Given that this has only happened for me in one particular project, I'm not convinced that this is a bug any longer. In my case, it seemed to be to do with trying to run `advanceReadiness()` when `deferReadiness()` had not previously been called. Removing `advanceReadiness()` or adding `deferReadiness()` resolved the issue in my case. Oddly, I can't seem to recreate this set of circumstances in a JSBin.

At present, I'm leaning toward this not being a bug so much as user error.

**Comment by wagenet** [comment]
I'm going to go ahead and close. Will gladly reopen with a failing JSBin.
