### ISSUE TITLE
Bug in ember data beta 14.1 unlabeled debug version

### ISSUE THREAD

**Issue by TauranJanitor** [emberjs/ember.js#10253]
I started a new app declaring the script dependencies for jquery-1.11.2.min, handlebars-2.0.0, ember-1.9.1.debug, ember-data-1.0.0-beta.14.1.debug, and localstorage_adapter. Nothing else but the html head, and body tags. Ember data debug throws an error Uncaught SyntaxError: Unexpected token typeof at ember data:11348. If I switch to ember data.prod or ember data.min, the bug doesn't appear. I guess I'll just use one of the other two versions.

**Comment by stefanpenner** [comment]
this is likely an issue on ember-data and not on ember.js itself

**Comment by wagenet** [comment]
@TauranJanitor, can you recreate the issue on ember-data? Thanks :)
