### ISSUE TITLE
[RFC] Make computed.or return truthy object rather than true

### ISSUE THREAD

**Issue by soulcutter** [emberjs/ember.js#10251]
[The current behavior of `Ember.computed.or` will return `true`](https://github.com/emberjs/ember.js/blob/a31c9aeb36fe1eefd43cd270a76777f0f4a8d25a/packages/ember-metal/lib/computed_macros.js#L446)

I propose that it would be useful to instead return the truthy object, which more-closely matches the semantics of JavaScript `||`. This could make `computed.or` more-useful for rendering templates (you seldom want to render `true`, but may want to render one of the `or`ed objects).

Example use case:

```javascript
export default DS.Model.extend({
  shortDescription: DS.attr('string'),
  verboseDescription: DS.attr('string'),
  description: Ember.computed.or('verboseDescription', 'shortDescription')
})
```

I can see this tripping people up who have written implementations depending on a `computed.or` property being `=== true`. In other words it has potential to break apps depending on the existing behavior.

**Comment by stefanpenner** [comment]
i would also love this :+1:  we should see if this has backwards compatible issues.

also, `and` should do the same

**Comment by tonycoco** [comment]
Would this be something that could get a PR quickly and move it forward? Extremely useful!

**Comment by stefanpenner** [comment]
likely yes

**Comment by soulcutter** [comment]
I have no problem putting a PR up for this, expect one tonight if nobody else gets to it first.

**Comment by stefanpenner** [comment]
> I have no problem putting a PR up for this, expect one tonight if nobody else gets to it first.

:+1:

**Comment by ahacking** [comment]
How is this different from ``Ember.computed.any`` ?

**Comment by stefanpenner** [comment]
@ahacking it isn't, we should deprecate any, no reason to have both.

**Comment by ahacking** [comment]
@stefanpenner OK cool, I support deprecating ``Ember.computed. any`` and calling it ``Ember.computed.or``.

When getting up to speed on Ember I first reached for ``Ember.computed. or`` on numerous occasions and only later discovering ``any`` after implementing my own CP to get the or semantics I wanted.

+1

**Comment by Kuzirashi** [comment]
This week I came across this issue and even searched through API but couldn't find method that returns `object` instead of `bool` so I ended up writing:
~~~~
application: Em.computed 'controllers.application', 'targetObject.controllers.application', ->
  @get('controllers.application') or @get('targetObject.controllers.application')
~~~~
I've noticed `.any` because of @ahacking's comment.

**Comment by soulcutter** [comment]
Implementation-wise `any` is slightly different in that it returns `null` rather than `false`. Not sure that matters to anyone, but there you have it.

**Comment by soulcutter** [comment]
Thinking about this a little more, the null return value probably is important in template rendering. The way javascript `||` works is that it returns the last value, so 

```javascript
undefined || null // => null
null || undefined // => undefined
null || false // => false
```

It makes sense to me to do that in `computed.or` as well
