### ISSUE TITLE
QueryParams set bound variable to undefined

### ISSUE THREAD

**Issue by rudi911** [emberjs/ember.js#10257]
In my controller I bind the destination property to a global variable, and I use that destination property as a queryparam. The variable is empty by default (""). In the route the desitination property is still empty in te model hook, on init of the controller it is also still empty, but then it gets corrupted (from empty to undefined). When I remove the desitnation property from the queryparams it is working fine.

Hope this helps.

    App = Ember.Application.create({
      destination: ''
    });
    
    App.SearchIndexController = Ember.ArrayController.extend({
      needs: ['currentUser'],
      queryParams: ['destination'],
    
      destinationBinding: 'App.destination',
    });

**Comment by mmun** [comment]
`destinationBinding: 'App.destination',` is a pattern that hasn't been used for a long time. A service + injection would be better.

**Comment by mmun** [comment]
I tried to reproduce the issue but I couldn't find any problems: http://emberjs.jsbin.com/woqemurihi/edit

If the problem is still persisting please share a JSBin and steps to reproduce so we can fix the bug!
