### ISSUE TITLE
When using Mandatory-setters, Observing a non-existent property can result in the value being "undefined" even after the property exists

### ISSUE THREAD

**Issue by Taytay** [emberjs/ember.js#10252]
Here's a demonstration of the issue:
http://jsbin.com/wamuhiguqu/1/edit?html,js,output

To copy the relevant stuff here:
```Javascript
var Person = Ember.Object.extend({

    firstName: null,
    //lastName: null,

    lastNameChanged: function() {
    }.observes('lastName')
});


var person = Person.create({
    firstName: 'Yehuda',
    init: function(){
      // Since I'm not using the setter, I'm doing this behind Ember's back
      // Yes, it's wrong, but it exposes up interesting behavior later
      // Mandatory setters can't protect against this of course.
      this.lastName = 'Katz';
      this.unwatchedProperty = 'Foo';      
    }
});

// Works as expected:
person.get('unwatchedProperty')); // 'Foo'

// Since this property was "watched" before it existed, the getter is broken, and will return undefined (if mandatory setters are enabled):
person.get('lastName'); // undefined

```

`person.get('lastName')` returns `undefined` even though the property exists on the underlying object. 
And at this point, you might be thinking "Who cares? You went behind Ember's back when you set those properties in the init method. Stop doing that."

We use Typescript, and I wrote a base Typescript class that allows the Typescript object model work with Ember's object model. The ability to manually set properties like this at object creation time (not after), was key in getting the Typescript object model to work with Ember. In Typescript, properties on classes are simply assigned in the object's constructor. The ability to do that at construction time, but still use Ember's `get` and `set` methods later for those properties works fine long as we don't use mandatory setters with observers. And, it would still work, if it weren't for a subtle bug in mandatory-setter.

This only happens for properties that are observed at creation time, but that don't exist on the object yet.  The reason comes down to these lines of code in Ember's `get`:
```Javascript
if (Ember.FEATURES.isEnabled('mandatory-setter')) {
      if (hasPropertyAccessors && meta && meta.watching[keyName] > 0) {
        // We fall in here, but meta.values doesn't have an entry in meta.values for our key yet, so we return undefined
        ret = meta.values[keyName];
      } else {
        ret = obj[keyName];
      }
    } else {
      ret = obj[keyName];
    }
```

Normally when we watch a property, the current value gets placed in `meta.values[keyName]`. However, if we watch a property at _construction_, and the property doesn't yet exist on the object, there is no entry to add to meta.values. So, we get to the code above, and return `meta.values[keyName]`, which is undefined, even though `obj[keyName]` is defined. 

There are 5 fixes/workarounds for this:

1) Add the following lines to `Ember.get`:
```javascript
          if (hasPropertyAccessors && meta && meta.watching[keyName] > 0) {
            ret = meta.values[keyName];
            if ((ret === undefined) && !(keyName in meta.values) && (keyName in obj)){
              // We started watching this property before it was set, and then it was set
              // without calling 'set', so we don't have this key in our values yet.
              ret = meta.values[keyName] = obj[keyName];
            }
          } else {
            ret = obj[keyName];
          }
```
That adds the property to meta.values, and things work as expected after that.
(However, it doesn't take care of defining the mandatory-setter for that property, as it would have if I had called `set` for this property.)

2) Make a custom debug build of Ember that compiles mandatory-setters out.

3) Allow me to disable mandatory-setters in the development build: Mentioned in issue #9897

4) Just debug using Ember.production, but we give up other niceties.

5) Try to find a workaround for our Typescript base class. It would involve some sort of iteration over all properties that Typescript initialized, and then calling `Ember.set` to make Ember aware of them. I'm not sure how feasible that is honestly, and since it's only required in debug mode, and would add overhead to every object created, I don't know that I'd want to jump through those hoops..

I'd prefer solution number 1, which makes sure that the mandatory setter code doesn't mask the underlying object to the point of returning `undefined` even though the property is defined on the underlying object. However, I realize that this is an obscure use case, and the fact that it worked was a happy accident. So, perhaps I can appeal to the principle of least surprise? I was surprised that debug vs production code would vary, and was certainly surprised to see property values be `undefined` according to Ember, even though the properties had value. :)

I know you might have bigger fish to fry, but I'd like to open source my Typescript base class to unite Typescript's object model with Ember's, and this (minor) bug will be a major impediment to any potential consumers. Any help or workaround you can offer would be greatly appreciated. :)

**Comment by cowboyd** [comment]
I don't know that it's so obscure. It's going to happen any time you try to integrate with an external object model. For example, I ran into the same issue when rendering a property from a native XHR that wasn't available until the `readyState` reached a certain point. Like your experience, it was really surprising and nasty to track down, and I'd vote for option (1) or something similar

**Comment by Taytay** [comment]
Thanks @cowboyd. I'm relieved to hear that I'm not the only one, and that there are other folks that might run into this.

(In the interest of full disclosure, I did just discover another workaround in my Typescript base class, but it digs into the internal guts of Ember, finds properties that are watched, but that don't have entries in meta.values yet, and inserts the values. That appears to work, however, it's as fragile and ugly as it sounds. :) )

**Comment by cowboyd** [comment]
No worries. btw, Says in your profile that you're in Austin? You should totally stop by and say hi... or come to the next EmberATX meetup :)

**Comment by rwjblue** [comment]
Seems to be working now: http://rwjblue.jsbin.com/baleva/edit?html,js,output
