### ISSUE TITLE
Generated acceptance test failing in newly created app

### ISSUE THREAD

**Issue by kevinansfield** [emberjs/ember.js#10264]
After creating a new app using ember-cli, updating to ember canary and adding a route, my generated acceptance test is failing with:

`Teardown failed on visiting /login: Requested keys of a value that is not an object`

I've pushed the failing example to https://github.com/kevinansfield/esa-acceptance-test. Everything in there is as generated by ember-cli 0.1.7 apart from minor template changes.

Ember: 1.11.0-beta.1+canary.8ca36b56
Ember Data: 1.0.0-beta.14.1

**Comment by kevinansfield** [comment]
Tested successfully with Ember 1.10.0-beta.4. Is there a breaking change between 1.10 and canary?

**Comment by joostdevries** [comment]
Do you have a full stack trace?  There have only been a [few changes](https://github.com/emberjs/ember.js/compare/v1.10.0-beta.4...beta)

**Comment by kevinansfield** [comment]
This is the stack trace as reported in the test failure:

```
TypeError: Object.keys called on non-object
    at Object.keys (native)
    at ember$data$lib$system$record_array_manager$$values (http://localhost:7357/assets/vendor.js:73049:24)
    at Ember.Object.extend.willDestroy (http://localhost:7357/assets/vendor.js:73042:113)
    at superWrapper [as willDestroy] (http://localhost:7357/assets/vendor.js:32140:22)
    at Queue.invoke (http://localhost:7357/assets/vendor.js:14404:18)
    at Object.Queue.flush (http://localhost:7357/assets/vendor.js:14469:13)
    at Object.DeferredActionQueues.flush (http://localhost:7357/assets/vendor.js:14274:19)
    at Object.Backburner.end (http://localhost:7357/assets/vendor.js:13699:27)
    at Object.Backburner.run (http://localhost:7357/assets/vendor.js:13754:20)
    at Object.run (http://localhost:7357/assets/vendor.js:30440:29)
```

**Comment by joostdevries** [comment]
Yeah so that's [this line](https://github.com/emberjs/data/blob/v1.0.0-beta.14.1/packages/ember-data/lib/system/record_array_manager.js#L279). But that's in Ember data and the error happens because of Ember canary right? I'll play around with it and see if I can figure out what's causing it.

**Comment by kevinansfield** [comment]
Confirm, it's definitely a result of using the canary branch with Ember Data. Removing Ember Data whilst still running canary resolves the issue.

The odd thing is that in the test app I haven't done anything other than include Ember Data, there's no ember data models and the routes are empty.

**Comment by joostdevries** [comment]
```
Ember        1.11.0-beta.1+canary.8ca36b56
Ember Data   1.0.0-beta.14.1
````
works fine for me.

**Comment by kevinansfield** [comment]
That's strange. I can reliably replicate the issue with the repository linked above.

Is there anything else that may be affecting my system? I'm currently on node `v0.10.35`

**Comment by joostdevries** [comment]
@kevinansfield I edited my post :$. Had to clear everything out.

**Comment by stefanpenner** [comment]
This is an ember data bug, please reopen on ember data

**Comment by joostdevries** [comment]
This should be fixed on the latest ember data canary. Could you check @kevinansfield?

**Comment by kevinansfield** [comment]
Confirmed fixed with latest ember data canary
