### ISSUE TITLE
1.11.0-beta.1+canary.8...  "Cannot call 'compile' without the template compiler loaded"

### ISSUE THREAD

**Issue by himansudesai** [emberjs/ember.js#10265]
Hi - I have a ember component wrapper library for jQueryUI with examples hosted on github.  It is not a CLI app.  Things used to work until 1.10 but with 1.11, I get an error: Cannot call 'compile' without the template compiler loaded.  Please load 'ember-template-compiler.js' prior to calling 'compile'.
I downloaded and included ember-template-compiler.js but of course without the full CLI machinery, it gives me a "ReferenceError: exports is not defined"

Has the on-the-fly compiling been taken out of the latest canary?  If so, how does one work around this.
Handlebars version = 2.0.0
Thanks
broken example at:  http://himansudesai.github.io/examples/slider-component.html

**Comment by thejchap** [comment]
Replicated here as well http://emberjs.jsbin.com/tafoyayalo/1/edit?html,output

**Comment by workmanw** [comment]
I think you guys just need to add include "ember-template-compiler.js".

@thejchap http://emberjs.jsbin.com/ludukidili/2/edit

**Comment by rwjblue** [comment]
Thank you @workmanw, that is absolutely correct.

**Comment by himansudesai** [comment]
Hi @rwjblue, @workmanw - I'll gladly retry including ember-template-compiler.js and report back.  However, as mentioned in the original issue, that leads to a "ReferenceError: exports is not defined" error.  It could be other ES6 related changes getting mixed into this, but simply including the ember-template-compiler does not do the trick.  If I switch from ember 1.11 back to 1.10 (both with Handlebars 2.0), everything works just fine.
Thanks

**Comment by thejchap** [comment]
@workmanw thanks!

Is this a temporary issue or is there documentation we/should can contribute somewhere?

**Comment by rwjblue** [comment]
FYI - Handlebars is no longer needed as of 1.10.

This is not temporary. I am supposed to be writing a blog post explaining the new template compilation process. Better get on that :)

**Comment by himansudesai** [comment]
@thejchap  Huh - that worked for you?  Which one of the many available ember-template-compiler.js did you use?  I used the one from npm and get "ReferenceError: exports is not defined.  Since my library has live examples, I'm desperate to get them working again.  Pl. advise offline at himansudesai@gmail.com if this is getting too voluminous for the issues page.
I'll try @rwjblue suggestion to remove handlebars

**Comment by himansudesai** [comment]
@rwjblue Will wait for your writeup and thanks for all the hard work and recent improvements.  Currently, I get a [ Uncaught TypeError: Cannot read property 'COMPILER_REVISION' of undefined ] at ember-template-compiler.js - LINE 38, if I include the compiler but not handlebars.  Thanks!

**Comment by rwjblue** [comment]
Please make sure you are using the ember-template-compiler.js that is published for your specific build.

**Comment by rwjblue** [comment]
That sounds like the old ember-template-compiler package, not the file thay is paired with your ember build.

**Comment by himansudesai** [comment]
@rwjblue I'll bet you are right.  Sorry for sounding like a noob (which I am) but I don't know how to find the right pairing.  I thought the one I am using might be old because it was published by you on npm 3 months ago.  I went to emberjs.com/builds/#canary and there is obviously no mention of ember-template-compiler there.  Thanks!!

**Comment by himansudesai** [comment]
@rwjblue Found the URL in one of your Ember JSBin Examples - nice!  <.../canary/ember-template-compiler.js>  Easy enough URL to remember.
P.S.  Some of your canary based examples are currently broken because they are missing the ember-template-compiler.  Can go through each and compile a list of broken ones for you, if you wish...

**Comment by ksnyde** [comment]
Hi folks, wanted to chime in that I have run into the same problem with `Ember 1.10.0-beta.4` and as I'm using CLI (v0.1.12) I thought the manual inclusion of the compiler mentioned above would simply be a matter of adding the following to my Brocfile:

     app.import('bower_components/ember/ember-template-compiler.js');

I've done that but am still getting the same compile error. In want amounts to an act of desperation I switched the HTMLbars on and off (all the while cursing under my breath) and noticed no variation in the message. That surprised me but then I'm not nearly close enough to the intricacies/dependencies of HTMLbars).

Anyway, with a small new project just starting I wanted to hit the cutting edge of Ember but am now wondering if I must step back from the edge a little. Any help getting back out on the edge would be very much appreciated.

**Comment by himansudesai** [comment]
@ksnyde As @rwjblue said, use the compiler that is paired with a particular release of ember.  I've identified a pattern for canary which should also work for 1.10.0-beta.4.

 I've verified that there is a ember-template-compiler.js at that URL.

The pattern is <prefix_to_emberxxx.js>/ember-template-compiler.js
In your case, it is:
http://builds.emberjs.com/beta/ember-template-compiler.js

**Comment by ksnyde** [comment]
@himansudesai I am I believe, unless I'm being thick the compiler version comes *with* the version of ember you've picked with bower. Doesn't it? What is the scenario where the compiler and Ember version become out of sync?

In my case, I tracked the problem down to my use of the `ember-cli-bootstrap-sass` plugin which was also including the now quite dusty `bootstrap_for_ember` components. I've created a [`ember-cli-bootstrap-sassy`](https://www.npmjs.com/package/ember-cli-bootstrap-sassy) plugin which removes this unwanted dependency and all is well again.

**Comment by himansudesai** [comment]
@ksnyde You are right.  In my case, I was using ember straight and had some trouble locating the correctly paired version of ember-template-compiler.  Since you were getting an identical error, I figured you had a mismatched pair as well.  Glad you tracked your issue down.

**Comment by jesuskwice** [comment]
@ksnyde -- how did you track down your problem? I'm not using bootstrap, so can't benefit from your plugin, but I am facing the same issue and curious how to identify what my culprit may be.. Any insight?

**Comment by ksnyde** [comment]
@jesuskwice for me it was just a matter of removing the aging "ember-cli-bootstrap-sass" plugin (see above) because it was loading "bootstrap_for_ember" which had dependency problems. Typically the compiler should automatically matchup without issue but I guess if you're doing some off-sheet template compiling maybe it is more complicated? Good luck getting this sorted.

**Comment by jesuskwice** [comment]
@ksnyde I don't really have any stringent limitations on my use case -- mainly just trying to get ember-cli to play nice with rails (tried a number of different approaches to no avail). Still tinkering around with this a bit before I have to drop hopes of this though. Thanks!

**Comment by sberan** [comment]
I ran into this issue as well, adding 

```
app.import('bower_components/ember/ember-template-compiler.js');
```

to my Brocfile.js fixed it.

**Comment by nitin-daffodil** [comment]
hey which brocfilte you are takin
