### ISSUE TITLE
STYLEGUIDE.md misleading notes (and unobvious perfomance improvement/degradation resulting from new Array)

### ISSUE THREAD

**Issue by Ginden** [emberjs/ember.js#10275]
[STYLEGUIDE.md](https://github.com/emberjs/ember.js/blob/master/STYLEGUIDE.md) contains following inadequate (anymore) statements:

> Don't re-assign the arguments.
`function (opt) {
opt = 3;
}`

Is perfectly fine in strict mode and doesn't result in any perfomance degrade. It CAN result in perfomance degradation if you are using direct `eval` in the same scope in sloppy mode, but I assume Ember contributors are sane.

Reference script: https://gist.github.com/Ginden/672cb07cc6445ad08615
Should be run with following command: `node --trace_opt --trace_deopt --allow-natives-syntax arguments.js`

Leaking `arguments` directly still results in deoptimisation.

> If you know the exact length and know that array is not going to grow, use new Array(n).

It isn't obvious deal and requires deeper thinking.

**In Firefox** it:
* results in [better perfomance when objects haven't got the same hidden class](http://jsperf.com/preallocating-array/11)
* results in [degraded perfomance when objects have got the same hidden class](http://jsperf.com/preallocating-array/10)

**In V8** it:
* results in [degraded perfomance when objects haven't got the same hidden class](http://jsperf.com/preallocating-array/11)
* results in [increased perfomance when objects have got the same hidden class](http://jsperf.com/preallocating-array/10)

Optimisation for SpiderMonkey is probably more important because it's a little bit slower engine.

**Comment by rwjblue** [comment]
> > Don't re-assign the arguments.
> 
> Is perfectly fine in strict mode and doesn't result in any performance degrade.

This is more about debugging than about performance.  In some cases reassigning an argument results in the dev tools not updating properly (or reflecting that `arguments[0]` was actually changed).  This leads to much more annoying debugging.

> > If you know the exact length and know that array is not going to grow, use new Array(n).
>
> It isn't obvious deal and requires deeper thinking.

Agreed.

**Comment by Ginden** [comment]
>In some cases reassigning an argument results in the dev tools not updating properly (or reflecting that arguments[0] was actually changed).
I consider this as DevTools bug - it's expected behavior in sloppy mode and buggy in strict mode.

**Comment by rwjblue** [comment]
> I consider this as DevTools bug - it's expected behavior in sloppy mode and buggy in strict mode.

Totally agreed, I would absolutely love for the upstream browser dev tool bugs to be fixed here! 

As it is written in the guide now, it does not impact performance, but has the potential to aid in debugging. I'd put this rule squarely in the camp of subjective style (which this guide is responsible for). Seems like win/win (or potentially win/tie) to me.
