### ISSUE TITLE
[Feature request] Indirect computed property

### ISSUE THREAD

**Issue by ssured** [emberjs/ember.js#10278]
I'd like to add a new indirect computed property. This is inspired by MS Excel `indirect` function. https://support.office.com/en-nz/article/INDIRECT-21f8bcfc-b174-4a50-9dc6-4dfb5b3361cd

What this makes possible is to have a property holding a path to another property, and then using a second property which is bound to this path. EG:

```javascript
o = Ember.Object.extend({
  source1: "foo",
  source2: "bar",
  path: "source1",
  value: Ember.computed.indirect("path")
}).create();

o.get("value"); // "foo"
o.set("value", "something");
o.get("source1"); // "something"
o.set("path", "source2");
o.get("value"); // "bar"
o.set("value", "anything");
o.get("source2"); // "anything"
```

My use case: I have a form builder in which a client can describe his own (nested) data structure and then input data using a form generated by that structure. All data is stored along with the format.  Right now I use 'magic' names for special properties, so I say to a client, when you name a field `title` then it will be used as a title when displaying all data in for instance a list.
What I want to do is to have to traverse the data format as provided by the client, find the path to first required text field and use that as a title. For me that is much more logical to explain to my customers: The first required text field will be used as title in the UI.

Excuse my coffeescript; here is a kind of working example http://emberjs.jsbin.com/qatoru/2/edit?html,js,output The technique behind this example is to dynamically create an extra bound property on the object and the to add an observer to that property. My guess is that there are easier ways; but I am not one of http://numberofpeoplewhounderstandembermetal.com/

Thanks for all wonderful work, you guys are amazing!

**Comment by mmun** [comment]
I would prefer this to bake as an Ember add-on.

**Comment by gordonkristan** [comment]
I've had the need for something like this before, but I've always cobbled together a custom solution. But I wanted a little bit of a challenge to spice up my Monday, [so I created a small Ember addon to do this](https://github.com/gordonkristan/ember-computed-indirect). I haven't published it yet as I want to make sure I didn't make any obvious mistakes, but I can if everything checks out. The implementation is pretty simple:

```js
export default function indirect(middlePropertyName) {
  var sourcePropertyObserver, lastSourceProperty;

  return function(key, value) {
    var sourceProperty = this.get(middlePropertyName);

    if (lastSourceProperty !== sourceProperty) {
      if (lastSourceProperty && sourcePropertyObserver) {
        this.removeObserver(lastSourceProperty, this, sourcePropertyObserver);
      }

      sourcePropertyObserver = function() {
        this.notifyPropertyChange(key);
      };

      this.addObserver(sourceProperty, this, sourcePropertyObserver);
      lastSourceProperty = sourceProperty;
    }

    if (arguments.length > 1) {
      this.set(sourceProperty, value);
    }

    return this.get(sourceProperty);
  }.property(middlePropertyName);
}
```

You can see it working with ssured's example code [here](http://emberjs.jsbin.com/hotexebixo/1/edit?js,console).

**Comment by ssured** [comment]
@gordonkristan Nice implementation, much more concise. One thing though is that it leaks observers, these should be removed on destroy. 
@mmun I'd prefer to have this code in core. Indirect is a primitive which enables for a lot of functionality, but takes only a little code to open up these possibilities.

**Comment by mmun** [comment]
@ssured Does it need to be in core?

**Comment by gordonkristan** [comment]
> One thing though is that it leaks observers, these should be removed on destroy.

Does it really? I would think that since all of the observers are on the same object, they would get cleaned up on destroy. If not, I could probably come up with something to remove that final observer on destroy. Can anybody give a definite answer on that?

**Comment by MarSik** [comment]
The proposed implementation has a flaw. It does not work properly when it is used in a component that is itself used multiple times on a page with the same middlePropertyName.

item-tree = export default Ember.Component.extend({
displayValue: Ember.computed.indirect('count')
});

{{item-tree item=box1 count='item.count'}}
{{item-tree item=box2 count='item.count'}}

I think that there is only a single shared "instance" of indirect in this case and so the sourcePropertyObserver and lastSourceProperty variables are also shared between all instances of item-tree.

I was able  to solve this using:

    var computedIndirect = function (middlePropertyName) {
        return function(key, value) {
            var sourceProperty = this.get(middlePropertyName);
    
            var lastSourceProperty = "_indirect_" + key + "_lastSourceProperty";
            var sourcePropertyObserver = "_indirect_" + key + "_sourcePropertyObserver";
    
            if (this[lastSourceProperty] !== sourceProperty) {
                if (this[lastSourceProperty] && this[sourcePropertyObserver]) {
                    this.removeObserver(this[lastSourceProperty], this, this[sourcePropertyObserver]);
                }

                this[sourcePropertyObserver] = function() {
                    this.notifyPropertyChange(key);
                };

                this.addObserver(sourceProperty, this, sourcePropertyObserver);
                this[lastSourceProperty] = sourceProperty;
            }

            if (arguments.length > 1) {
                this.set(sourceProperty, value);
            }

            return this.get(sourceProperty);
        }.property(middlePropertyName);
    };

**Comment by gordonkristan** [comment]
@MarSik You're right, it uses a closed over variable when it should use a variable on the instance. I will update the implementation and add a test for this soon. (Probably tomorrow sometime.) Thanks for pointing that out.

**Comment by endash** [comment]
Just to add another perspective I solved this problem (for various values of solved, really only in templates) via a 'follow' helper that would treat the value at the given path as a path itself. It was for much the same reason: a dynamic form builder/data complex. It was a while ago and I don't know if the approach would work with the very latest ember/*bars, or even which method I prefer, but I wanted to validate the 'path to a path' use case.

**Comment by gordonkristan** [comment]
I updated my addon to something similar to what MarSik did, but instead of storing properties on the object, I used some hashes in the module. It seemed better than adding random properties to an object.

```js
import Ember from 'ember';

var sourcePropertyObservers = {};
var lastSourceProperties = {};

export default function indirect(middlePropertyName) {
  return function(key, value) {
    var guid = Ember.guidFor(this);
    var sourceProperty = this.get(middlePropertyName);

    if (lastSourceProperties[guid] !== sourceProperty) {
      if (lastSourceProperties[guid] && sourcePropertyObservers[guid]) {
        this.removeObserver(lastSourceProperties[guid], this, sourcePropertyObservers[guid]);
      }

      sourcePropertyObservers[guid] = function() {
        this.notifyPropertyChange(key);
      };

      this.addObserver(sourceProperty, this, sourcePropertyObservers[guid]);
      lastSourceProperties[guid] = sourceProperty;
    }

    if (arguments.length > 1) {
      this.set(sourceProperty, value);
    }

    return this.get(sourceProperty);
  }.property(middlePropertyName);
}
```

**Comment by ssured** [comment]
Nice! :+1:

**Comment by mixonic** [comment]
I'd also like to see this bake in an addon. And please don't take that as a blanket "this will never land in core", just as what it is. Let's all kick it around in the minor leagues and see if any iteration is needed before locking the API and usage.

@rwjblue and I were writing something like this yesterday. I have a theory that the reactive rendering work will make this technique overkill in many cases.

In light of @gordonkristan's addon I'm going to close this for now. Let me know if I've missed anything.

**Comment by MarSik** [comment]
I am afraid the last version will leak references (and memory).

I am not primarily a javascript developer so correct me if I am wrong here, but I believe that since nobody ever deletes keys from sourcePropertyObservers and lastSourceProperties this will cause the references to the observer and to the ember object (by closure reference to this) to be kept in memory forever.

**Comment by gordonkristan** [comment]
@MarSik That's true. Shouldn't be a big deal for most people, but could cause issues if you're creating a lot of objects this way. I'll try to think of a way around that. If worse comes to worst I'll just add properties to the object like you did.
