### ISSUE TITLE
Add ability to know if proxied object is equal to an unproxied object.

### ISSUE THREAD

**Issue by martndemus** [emberjs/ember.js#10272]
```javascript
var object = getAProxiedObject();
Ember.isEqual(object, object.get('content')) // IMO should return true, actually returns false 
```
Something like that would make my life a whole lot easier.

**Comment by haydn** [comment]
:+1: I've come across this issue as well.

What's the best work around at this time? At the moment I'm checking if either of the objects are proxies and getting their content:

```javascript
a = (a instanceof Ember.ObjectProxy) ? a.get("content") : a;
b = (b instanceof Ember.ObjectProxy) ? b.get("content") : b;

Ember.isEqual(a, b);
```

**Comment by martndemus** [comment]
Yes, i'm using your workaround too, like this:

```javascript
// app/utils/proxy-equal.js
import Ember from 'ember';

function stripProxies(obj) {
  while (obj instanceof Ember.ObjectProxy) {
    obj = obj.get('content');
  }

  return obj;
}

export default function(a, b) {
  return Ember.isEqual(stripProxies(a), stripProxies(b));
}
```

But the real issue is that when is for instance have an (Ember) array of proxied objects and I have a reference to an object without proxies and I want to know at which index it is in the array. This won't work reliably.

```javascript
arrayWithProxies.indexOf(myObjectWithoutProxy); // -1 if the object is in the array, but with a proxy.
```

**Comment by rwjblue** [comment]
For the most part, dealing with proxied things is deprecated in 1.13 and removed in 2.0.0. 

I'm going to close, but if this is still a problem in 2.0.0+ I am happy to reopen.

**Comment by IAmJulianAcosta** [comment]
@rwjblue I'm using Ember 2.4 with Ember Data 2.4 and I'm having the same problem, comparing a `model` with a `belongsTo` relationship returns always false, because `belongsTo` returns a `ObjectProxy`

**Comment by bgentry** [comment]
I just encountered this as well, and I was surprised to learn that `ObjectProxy` doesn't implement a reasonable default for `isEqual`. Two objects of the same class with the same content should be considered equal IMO.
