### ISSUE TITLE
[FEATURE] Automated API Documentation

### ISSUE THREAD

**Issue by drewcovi** [emberjs/ember.js#10273]
This is a pipe-dream but I've found that working with an API team, it would be quite nice to have a tool that uses existing model information and serializer / adapter information to help create documentation that can be exported and hosted / shared.

It seems like all of the pieces are there, perhaps there's opportunity to leverage comments on a per-model basis to supplement each definition.

**Comment by stefanpenner** [comment]
Although a good idea, not really a bug report. I hope someone creates an addon that does this
