### ISSUE TITLE
Ember.Select in multiple mode will not trigger a computed property setter used as Ember.Select#selection

### ISSUE THREAD

**Issue by lolmaus** [emberjs/ember.js#10286]
A very simple app:

```js
App.IndexRoute = Ember.Route.extend({
  model: function() {
    return [
      {id: 1, name: 'Ember'},
      {id: 2, name: 'rocks'},
      {id: 3, name: 'the'},
      {id: 4, name: 'planet.'},
    ]
  }
});

App.IndexController = Ember.Controller.extend({
  foo: Ember.computed(function(key, value, prevValue) {
    console.log('Computed value!');

    // Stuff here
  })
});
```

```hbs
    {{view 'select'
      content=model
      optionValuePath='content.id'
      optionLabelPath='content.name'
      selection=foo}}
```

When i choose something in the selectbox, i see "Computed value!" in the console. This is expected.

But then i set my selectbox to multiple mode:

```hbs
    {{view 'select'
      content=model
      optionValuePath='content.id'
      optionLabelPath='content.name'
      selection=foo
      multiple=true}} <!-- new line -->
```

Now choosing items in the selectbox does not trigger the computed property and i see nothing in the console!

According to the [docs](http://emberjs.com/api/classes/Ember.Select.html#property_selection), `Ember.Select#selection` does support the multiple mode:

> ### `Ember.Select#selection`
> When `multiple` is `false`, the element of content that is currently selected, if any.
> When `multiple` is `true`, an array of such elements.

Here's a demo: :sparkles: http://emberjs.jsbin.com/bafafo/11/edit?html,js,output :sparkles:

There are two chunks of code, one for `multiple=false` and one for `multiple=true`. The only difference between the two chunks is that one deals with a single item and the other deals with an array of items.

Notice that every time you make a choice in the `multple=false` selectbox, the `singleId` property is updated from the computed property, and you can see a `console.log` message every time.

But when you make changes in the `multple=true` selectbox, the `multiIds` property is not updated and  `console.log` is not fired, though `{{#each item in mutli}} {{item.name}} {{/each}}` does get filled with newly selected content.

**Please confirm whether this is a legit bug.**

* * *

**PS** Some background.

In my use case, an array of records is displayed on the page. There's a selectbox for each record. The content of each select box comes from a property of the record. A user can configure each record to be either single-select or multi-select.

Example code:

```hbs
{{#each record in model}}
  {{view 'select'
    multiple=record.multipleMode
    content=record.content
    selection=record.selection
    ... }}
{{/each}}
```

I would make `record.selectionIds` a normal property and `record.selection` a computed property, but `record.selectionIds` is a `DS.attr()` and Ember Data attrs can not be computed properties. :(

There's another reason for `record.selection` to be a computed property: it also depends on `record.content`. The matter is that the content is dynamic, and when the content changes, removed items should not be listed as selected.

**Comment by lolmaus** [comment]
I've fixed a number of bugs in the demo and updated the link above. Here is the new link: http://emberjs.jsbin.com/bafafo/11/edit?html,js,output

And here's another demo which shows that the property associated with `Ember.Select#selection` in multiple mode can not be observed as well: http://emberjs.jsbin.com/bafafo/12/edit?html,js,output

**Comment by xtian** [comment]
@lolmaus Here's a simplified JSBin that I think accomplishes what you are trying to do: http://emberjs.jsbin.com/qineqolazo/2/edit

My first instinct was to use `Ember.computed.mapBy('selected', 'id')` but that doesn't seem to work. I'm not too familiar with `Ember.Select` so maybe that's a bug or someone more knowledgable than me can explain why it doesn't work.

**Comment by xtian** [comment]
This does seem to be a bug. Here's a JSBin that demonstrates the issue:
http://emberjs.jsbin.com/cawewivofu/4/edit

I think I've traced the problem as far as these lines:
https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/views/select.js#L583-586

When `EnumerableUtils.replace` is used instead of `set`, the value form doesn't get updated in the template.

**Comment by lolmaus** [comment]
@xtian, i also looked at that line carefully.

But if that's the line to blame, this means that it's not a bug in Ember.Select, but rather a more fundamental bug: when a property A changes, Ember does notify observers and computed properties depending on A, but it doesn't notify the computed property behind A.

This issue might exist in many other Ember classes, it's just computed property setters aren't very popular for us to discover all the issues. Also, code written in Ember will also be prone.

Is that a reasonable statement?

**Comment by xtian** [comment]
Yeah, this is the purpose of array computed properties (signified by the brackets in `selected.[]`). For instance, the button this code doesn't update the DOM either:

```handlebars
<button {{action "push"}}>Push</button>
{{array}}
```
```javascript
App.IndexRoute = Ember.Route.extend({
  array: [],
  actions: {
    push: => { array.push(Math.random()) }
  }
})
```

I'm not sure how to apply them in the case of `Ember.Select`, though.

**Comment by wagenet** [comment]
Closing in favor of #5259

**Comment by grantovich** [comment]
If anyone is interested in a more generic workaround for this issue, I came up with this *(probably inefficient, definitely not upgrade-safe)* monkey patch, which targets the problematic `replace` @xtian identified and wraps it in a property change notification:

```
Ember.Select.reopen({
  _changeMultiple: function() {
    if (Ember.isArray(this.get('selection'))) {
      this.propertyWillChange('selection');
      this._super();
      this.propertyDidChange('selection');
    } else {
      this._super();
    }
  }
});
```

Although undoubtedly more fragile than the observer solution, for me this solved the problem in one place for the whole app. YMMV.
