### ISSUE TITLE
Non Closing block matches wrong block: (Uncaught Error: audio-player doesn't match if)

### ISSUE THREAD

**Issue by greggawatt** [emberjs/ember.js#10294]
The following block of code
![screen shot 2015-01-24 at 6 30 17 pm](https://cloud.githubusercontent.com/assets/682680/5915045/2d622b92-a5a4-11e4-9cdb-1f2d311faf98.png)

Gave the follow error in the console.
![screen shot 2015-01-24 at 6 28 57 pm](https://cloud.githubusercontent.com/assets/682680/5915048/4362df5e-a5a4-11e4-8de7-09c8bb0715d0.png)

due to ```{{#audio-player}}``` not having matching ```{{/audio-player}}```. I feel the error message should be more verbose.

**Comment by mmun** [comment]
What version of ember are you using? The error messages should be better now.

**Comment by greggawatt** [comment]
v1.0.0-rc.6

**Comment by stefanpenner** [comment]
> v1.0.0-rc.6

oh that is quite old, we are on 1.9.1 now, and 1.10.x is in beta. I would suggest upgrading.
