### ISSUE TITLE
Sending actions from components to application does not work

### ISSUE THREAD

**Issue by ohcibi** [emberjs/ember.js#10298]
Considering this example: http://emberjs.jsbin.com/zemiwobaqi/1/edit?html,js,output

The expected result is that it alerts "first" and then "blub", however only "first" is alerted. If this example is wrong usage of components actions, the docs for that need updates on how to do this correctly.

**Comment by stefanpenner** [comment]
```hbs
{{#bla-blub blah="blah"}}hallo{{/bla-blub}}

```

**Comment by stefanpenner** [comment]
documented here: http://emberjs.com/guides/components/sending-actions-from-components-to-your-application/

it is likely that is unclear, if you have ideas to improve it let us know.

**Comment by ohcibi** [comment]
I read that section from top to bottom but its just not clear that you should pass the name of the property of the component which holds the name of the action to actually send. Now that I know that, the last paragraph from that section even makes more sense... Could we agree to re-open this issue but call it something like "improve documentation" or should I create a new one?

**Comment by stefanpenner** [comment]
feel free to open an issue on the website repo, which contains the guides https://github.com/emberjs/website

**Comment by ohcibi** [comment]
Ah ok. I confused this with the API which is generated from the doccomments from here 8-)

**Comment by ohcibi** [comment]
But again: Why is there no way to trigger an action directly from a component? One could even use `this.get("thatProperty")` and pass the return value to the send action logic.
