### ISSUE TITLE
Handlebars bind-attr doesn't preserve case

### ISSUE THREAD

**Issue by aquavitae** [emberjs/ember.js#10303]
I have noticed that `bind-attr` does not preserve case, e.g.``<input {{bind-attr placeHolder="placeHolder"}}>` will result in `<input placeholder=''>`.  Mostly, this is a minor annoyance, but doesn't really change since html is not case sensitive anyway.  However, I found something perculiar when using it on `svg` elements (see http://emberjs.jsbin.com/qehubi/1/edit).  In my controller, I have a property `viewBox` which is used with `bind-attr` on the `svg` element:

    <svg {{bind-attr viewBox="viewBox"}}>...</svg>
    
However, what is generated is:

    <svg viewbox="..." viewBox="..."></svg>

I don't really know what is going on here, but my guess is that the initial value of `viewBox` is inserted with the camelcase name, then when the value is updated it is inserted with the lowercase name.

**Comment by rwjblue** [comment]
This code path had changed significantly in 1.10 (beta channel) and canary, and I believe this exact case (viewBox with SVG elements is actually used as an example in some of the newer tests). Can you update the JSBin to beta and retest?=

**Comment by rwjblue** [comment]
Yep, looks like it works properly in canary: http://emberjs.jsbin.com/dimaki/2/edit?html,js,output

**Comment by rwjblue** [comment]
Closing as this works in beta (will be 1.10.0 shortly) and canary (will become 1.11.0-beta.1).

**Comment by kellysutton** [comment]
Alright, I'm running into an issue with 1.10 which is tangentially related to this one. Basically, case sensitivity is not respected when using `attributeBindings` in a view. This is an issue for the SVG `viewBox` property.

Here's a snippet:

```javascript
export default Ember.View.extend({
  attributeBindings: ['myViewBox:viewBox'],

  myViewBox: "0 0 100 100"
});
```

When rendered to the page, the `viewBox` property is inserted as `viewbox`. Thus, it is not respected by the browser. 

I should note that I'm currently using HTMLBars 0.6.0. Should this issue be reopened or brought into a new issue?

**Comment by mixonic** [comment]
@kellysutton have you tried Ember.js 1.11 beta?

**Comment by kellysutton** [comment]
Not yet. I'll give that a try and report back.
