### ISSUE TITLE
srcset attribute isn't supported when using bind-attr

### ISSUE THREAD

**Issue by deathbearbrown** [emberjs/ember.js#10301]
When using bind-attr with srcset:
`<img {{bind-attr srcset="medium.jpg 1000w, large.jpg 2000w"}} src="kitten.png"/>`

the resulting markup looks like this:
`<img data-bindattr-741="741" src="kitten.png">`

What I expect is:
`<img srcset="medium.jpg 1000w, large.jpg 2000w" src="kitten.png"/>`

Test here:  http://jsfiddle.net/j1njm36w/

I'm using a view as a work around, but since srcset is part of the responsive image spec, this should be something I can bind with bind-attr.

If you have any questions about how srcset works see the docs here: https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-srcset

or talk to @wilto if you want the human touch. 

Thanks! :frog:

**Comment by deathbearbrown** [comment]
Hrm, Ok so my issue was that I was passing in a string. If I pass it a function off a controller it works.
http://jsfiddle.net/deathbearbrown/j1njm36w/9/

**Comment by SlexAxton** [comment]
I don't think the test is working for me. It looks like a default ember jsfiddle start. Maybe wrong link?

My gut is that `{{bind-attr}}` is for dynamic data, not for a raw string (there's nothing to bind to).

So instead of 

```hbs
<img {{bind-attr srcset="medium.jpg 1000w, large.jpg 2000w"}} src="kitten.png"/>
```

You'd have some variable available in your view:

```js
{
...
srcsetSizes: 'medium.jpg 1000w, large.jpg 2000w',
...
}
```

And then bind that in the template:

```hbs
<img {{bind-attr srcset=srcsetSizes}} src="kitten.png"/>
```

Or even more fun, compute the string based on more fine grained pieces:

```js
{
...
mediumSrc: 'medium.jpg',
mediumSize: '1000w',
largeSrc: 'large.jpg',
largeSize: '2000w',

srcsetSizes: function() {
  var mSrc = this.get('mediumSrc');
  var mSize = this.get('mediumSize');
  var lSrc = this.get('largeSrc');
  var lSize = this.get('largeSize');

  return `${mediumSrc} ${mediumSize}, ${largeSrc} ${largeSize}`;
}.property('mediumSrc', 'mediumSize', 'largeSrc', 'largeSize'),
...
}
```

**Comment by fivetanley** [comment]
This definitely feels like a bug to me if you can't use a string.

**Comment by deathbearbrown** [comment]
I'm soooo sorry @SlexAxton , when i was fixing the jsfiddle, @bmac explained I couldn't use a string

**Comment by SlexAxton** [comment]
@fivetanley what are you binding the attribute to? A static string?

**Comment by SlexAxton** [comment]
(It just seems ripe for something to go wrong since strings could be property names or static strings, what if there's a collision, etc)

**Comment by fivetanley** [comment]
Perhaps we should warn if you pass in a string? seems like a footgun to me and a strange sense of confusion to me.

**Comment by Wilto** [comment]
I’m not clear on why `srcset` and `src` are handled differently in the first place. I can see `bind-attr` for something wholly custom like a data attribute, but shouldn’t a native `img` attribute work right out of the box?

**Comment by SlexAxton** [comment]
I think it'd be a great warning if you did something like:

```js
if (boundProperty not in context) {
  Ember.warn('We cant find anything to bind to called X.');
}
```

The only problem is that in her initial example, if you went and added a property to your view like this:

```js
{
...
'medium.jpg 1000w, large.jpg 2000w': 'foo'
...
}
```

Then that'd technically now bind for real. `<img srcset="foo" ...>`.

That's a silly example, but it probably wouldn't be *that* silly for lots of other cases

```hbs
<button {{bind-attr disabled="disabled"}}>
```

If you didn't initialize `disabled: false` in the view, it'd think it was a string, but then when you did a `.set('disabled', true)` all the sudden it'd be a property.

**Comment by SlexAxton** [comment]
@wilto there's no different handling. It just didn't need to be bound, just like the `src` attribute wasn't bound.

This is perfectly valid and works:

```hbs
<img srcset="medium.jpg 1000w, large.jpg 2000w" src="kitten.png"/>
```

This is equally invalid and doesn't work equally:

```hbs
<img {{bind-attr srcset="medium.jpg 1000w, large.jpg 2000w"}} {{bind-attr src="kitten.png"}} />
```

**Comment by Wilto** [comment]
Ahh, okay. Way outta my depth on Ember; I just make stretchy pictures.

**Comment by SlexAxton** [comment]
hi @wilto yes hi, id like to make my pictures wide-angle thnx

**Comment by Wilto** [comment]
wide stretchy pictures can be yours for the low low price of $19.99 directly to my paypal

order now

**Comment by rwjblue** [comment]
I believe that this is working properly in canary (and soon 1.11.0-beta.1).  http://emberjs.jsbin.com/rwjblue/289/edit?html,js
