### ISSUE TITLE
input helper and action does not work as expected

### ISSUE THREAD

**Issue by blessenm** [emberjs/ember.js#10305]
Im basically trying to get this to work. This is doable as per the docs http://emberjs.com/guides/templates/input-helpers/#toc_actions

    {{input value=firstName action="didType" on="key-press"}}

The problem is, when the action triggers, the value passed will always be 1 character short of actual value of the input element.
For eg: if input value is 'add', the value passed into the action is 'ad'.

Here is a failing bin. http://jsbin.com/lotete/3/edit

I also noted that using other events like `key-up` and `key-down` dont trigger that action.

I found this issue while solving this question on SO http://stackoverflow.com/questions/28191776/first-character-empty-using-ember-action-on-key-press

**Comment by lolmaus** [comment]
@blessenm, i've tried other events officially listed [here](http://emberjs.com/api/classes/Ember.View.html#toc_event-names) (i've dasherized them) and they don't work completely. E. g. `key-up`, `key-down`, `change`, `input` don't trigger the action completely! :astonished:

**Comment by MatrixZ** [comment]
@blessenm The behavior of `keyPress` is perfect. Input value will only be updated on `keyUp` ie) the moment when the key got released. The below one will work.

`{{input value=firstName action="didType" on="key-up"}}`

**Comment by blessenm** [comment]
@MatrixZ Like @lolmaus  mentioned, using `on="key-up"` doesn't seem to trigger the action.

**Comment by rwjblue** [comment]
Seems to be working properly here: http://emberjs.jsbin.com/rwjblue/278/edit

**Comment by blessenm** [comment]
@rwjblue so wont this syntax work `{{input value=firstName action="updateFirstName" on="key-up"}}`? I took that example from the input helper guides and just replaced the event name.

**Comment by rwjblue** [comment]
No, I wouldn't think that it would (or should be made to) work that way. Specifying the action that you want triggered along with the event/action seems much more straightforward (and is in line with how you would write your own components). 

Consider:

```hbs
{{input value=firstName key-up="updateFirstName"}}
```

Versus:

```hbs
{{input value=firstName action="updateFirstName" on="key-up"}}
```

The later example is disjointed, and fails to allow using multiple actions to trigger different events.  What if you wanted something like [this](http://emberjs.jsbin.com/rwjblue/284/edit):

```hbs
{{input value=firstName key-up="updateFirstName" focus-in="enterFirstName" focus-out="exitFirstName"}}
```

----

If this was confusing upon reading the API docs (I haven't read this part in some time, so I am unsure of their state) we should rewrite/restructure them to make this clearer.

**Comment by blessenm** [comment]
@rwjblue it makes sense. I guess the guides may need to be updated. FYI this is where I picked up the syntax I mentioned http://emberjs.com/guides/templates/input-helpers/

**Comment by ankushdharkar** [comment]
{{input value=firstName action="didType" on="input"}} is not working for me in Ember 1.12.0

**Comment by treyhunner** [comment]
`on="input"` is not working for me either.  "input" is in the [event names][] list, so I assumed it would.

[event names]: http://emberjs.com/api/classes/Ember.View.html#toc_event-names

**Comment by thilaktp** [comment]
Looks like a general bug for 'on' #11678 

Work around is to use Input directly as html and have action helper on it.

ex: <input type="text" {{bind-attr value=data}} {{action 'changed' on='change'}} />

Not the best solution, but it works.

**Comment by rwjblue** [comment]
Closing in favor of #11678 (I know it is newer, but I have an idea on a path forward that it made me think of).

**Comment by KurtRMueller** [comment]
Is there anywhere in the ember guides or api where the difference between `key-press` and `key-up` are explained? I can't seem to find any sort of entry. :(

**Comment by lolmaus** [comment]
@KurtRMueller Try googling it without mentioning Ember, there's tons of info.
