### ISSUE TITLE
application view rerender(): Uncaught TypeError: Cannot read property 'append' of null

### ISSUE THREAD

**Issue by zyllorion** [emberjs/ember.js#10304]
Ember-cli 0.1.9
ember.debug.js:4272 DEBUG: Ember      : 1.11.0-beta.1+canary.22d2afab
ember.debug.js:4272 DEBUG: Ember Data : 1.0.0-beta.14.1
ember.debug.js:4272 DEBUG: jQuery     : 1.11.2
ember-cli-i18n 0.0.5

Stack:
```
Uncaught TypeError: Cannot read property 'append' of null
Renderer_insertElement
Renderer_renderTree (anonymous function)
```
Called from here (the anonymous function above):
```
// TODO: should be scheduled with renderer
        run.scheduleOnce('render', function () {
          if (view.isDestroying) {
            return;
          }
          view._renderer.renderTree(view, view._parentView);
        });
```
Erroring on this line:
```
    function Renderer_insertElement(view, parentView, element, index) {
      if (element === null || element === undefined) {
        return;
      }

      if (view._morph) {
        view._morph.setContent(element);
      } else if (parentView) {
        if (index === -1) {
>>>>          view._morph = parentView._childViewsMorph.append(element);
        } else {
          view._morph = parentView._childViewsMorph.insert(index, element);
        }
      }
    }
```

I'm trying to refresh all views after modifying locale translations for ember-cli-i18n.
The code I'm using to refresh the top level application view is:
```
Ember.$.each(Ember.View.views, function(i, view) {
                    if (view.renderedName === "application") {
                        view.rerender();
                        Ember.Logger.debug('rerendering application view');
                    }
                });
```
Originally posted here:
https://github.com/tildeio/htmlbars/issues/271

**Comment by rwjblue** [comment]
A few JSBin's:

* without an `{{outlet}}` http://emberjs.jsbin.com/rwjblue/263/edit?html,js (no errors, works properly)
* with {{outlet}} http://emberjs.jsbin.com/rwjblue/264/edit?html,js (errors when setting `view.element` in the renderer)
* with an {{each}} in an outlet view http://emberjs.jsbin.com/rwjblue/265/edit?html,js (errors setting `_childViewsMorph` in `ContainerView`)

I was unable to replicate the exact error that @zyllorion is reporting though (but clearly there are some thing to fix).

@zyllorion - Can you tweak one of my JSBin's above to trigger the specific error that you are getting?

**Comment by krisselden** [comment]
@rwjblue this is a bug, the parent view destroys views connected to an outlet and when rendering again errors trying to reattach destroyed views

**Comment by dogawaf** [comment]
Hi!

I was updating an app from 1.7.1 to 1.8.1, and I found the same issue (or maybe another one).

With 1.7.1: rerender the application view works fine
With 1.8.1 or 1.9.1 : rerender throw an error: `Error while processing route: XXX Cannot read property 'connectOutlet' of undefined `
With canary: rerender works fine

Here is a simple jsbin to demonstrate how to reproduce my issue (just play with the set of script tags): http://emberjs.jsbin.com/naquvegali/3/edit
