### ISSUE TITLE
Chained computed map properties run map function too often

### ISSUE THREAD

**Issue by WCPetersen** [emberjs/ember.js#10309]
When computed map properties are chained together, the later properties call their map functions too often. It gets worse as the chain gets longer. I've created a [JS bin](http://jsbin.com/taxevoyoqa/1/edit?html,js,output) to demonstrate the issue.

There are really two problems. First, events are getting multiplied as they go down the chain. Second, the map functions are getting called on items which are about to be removed.

I can understand why you might need to trigger extra events on the first map property, but I don't think they should multiply as they go down the chain. I'm betting it's the extra events that are causing the items to get re-mapped so often.

**Comment by stefanpenner** [comment]
reduce computed / array computed have been overhauled in 2.0. They are implement now as simple CPs, so the lazy semantics should be correctly preserved all the way down.
