### ISSUE TITLE
Async test helper doesn't work as expected

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/ember.js#10306]
I've attempted to create a helper to pause test execution:

```js
Ember.Test.registerAsyncHelper('sleep', function(app, time){
    return Ember.run.later(function(){}, time || 500);
});
```

While it does stop QUnit (eventually), the `andThen()` helper executes before it.

```js
test('visiting /', function() {
  visit('/');
  sleep(10000);
  andThen(function() {
    equal(currentPath(), 'index');
  });
});

```

(cc @QuantumInformation)

**Comment by lolmaus** [comment]
This might be relevant: http://emberjs.com/api/classes/Ember.Test.html#method_wait

**Comment by teddyzeenny** [comment]
As @lolmaus mentioned, you should return `wait` from the helper:
```javascript
Ember.Test.registerAsyncHelper('sleep', function(app, time){
   Ember.run.later(function(){}, time || 500);
   return wait();
});
```

**Comment by olivierlesnicki** [comment]
Thanks

The naming of the "registerAsyncHelper" method is a bit confusing.

**Comment by teddyzeenny** [comment]
You did not return a promise from the `sleep ` helper, so there was no way to know how long to wait for it.
As for the name `async` it's about when this helper executes, here's the difference between async and sync helpers:

```js
Ember.Test.registerAsyncHelper('sleep', function(app, time){
   console.log('sleeping');
   Ember.run.later(function(){
     console.log('finished sleeping');
   }, time || 500);
   return wait();
});

Ember.Test.registerAsyncHelper('asyncLog', function() {
  console.log('async log');
});

Ember.Test.registerHelper('syncLog', function() {
  console.log('sync log');
});

sleep();
asyncLog();
syncLog();

// Output:  sync log, sleeping, finished sleeping, async log

**Comment by QuantumInformation** [comment]
Could this sleep help be added to the ember core?

**Comment by rwjblue** [comment]
@QuantumInformation - I don't really think so. Adding random sleep's into your tests is generally not a great idea. It is much better to wait for the actual time that you need (which is fairly straightforward by wrapping promises in an async helper).

**Comment by stefanpenner** [comment]
@QuantumInformation  `pauseTest();` helps in some situations (debugging/developing)
