### ISSUE TITLE
Documentation for Ember CLI, HtmlBars and the Ember.Handlebars.Compile function

### ISSUE THREAD

**Issue by cannect** [emberjs/ember.js#10307]
I found out that using the HTML Bars, Ember CLI and the use of the `Ember.Handlebars.Compile` function does not work out of the box.

I got a view where I have the following code:
```
 template: Ember.Handlebars.compile('<h2>{{day}}</h2>')
```

This does not work out of the box with HtmlBars. So maybe this behaviour should be documented elsewhere?

Maybe @rwjblue know where this documentation belongs?

**Comment by stefanpenner** [comment]
we don't include the template compiler in the browser by default, it is primarily meant as a build tool steps. Primarily because it is slow

**Comment by cannect** [comment]
@stefanpenner Thank you! 

I think if the compatibility is not that of Ember itself, I will rework my views to use normal templates via `templateName` in my views.
