### ISSUE TITLE
Split Ember.Set into its own module

### ISSUE THREAD

**Issue by matthewoates** [emberjs/ember.js#10312]
I remember reading in the release notes that Ember.set (https://github.com/emberjs/ember.js/blob/5fe2d63a7dab0484cad9e729886ac71b4c05f1fd/packages/ember-runtime/lib/system/set.js#L28) would be split into its own module to be included for those that need it. Is this still planned?

**Comment by trek** [comment]
Yes. This will happen with 2.0
