### ISSUE TITLE
Create a container on the registry (with `registry.container()`) before calling `lookupFactory`.

### ISSUE THREAD

**Issue by twokul** [emberjs/ember.js#10313]
Seems like latest changes to ember's registry resulted in some errors in the way ED registers. Ember canary + ED canary throws this error: `Assertion Failed: Create a container on the registry (with registry.container()) before calling lookupFactory`.

Here's a [demo repo](https://github.com/twokul/container-shenanigans).

@rwjblue @fivetanley thoughts?

**Comment by twokul** [comment]
seems like `this._defaultContainer` is not defined on Application's registry when [`runInitializers`](https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/application.js#L571) is being executed. But it is defined on the application's instance.

**Comment by rwjblue** [comment]
The container/registry + initializers/instanceInitializers code was recently changed in https://github.com/emberjs/ember.js/pull/10271 (just landed).  It *might* be related.

**Comment by rwjblue** [comment]
Failing [JSBin](http://emberjs.jsbin.com/rwjblue/268/edit)

The line causing the error in ember-data is [here](https://github.com/emberjs/data/blob/c1ea7f0d066ea28322799289b66a82cda3cbda99/packages/ember-data/lib/initializers/store.js#L18) in the store initializer:

```javascript
container.register('store:main', container.lookupFactory('store:application') || (application && application.Store) || Store);
```

This definitely seems like a regression from #10271.

@tomdale / @dgeb - Mind taking a look at this one?
