### ISSUE TITLE
Default block for components that use yield

### ISSUE THREAD

**Issue by opsb** [emberjs/ember.js#10319]
I'm creating a component where I sometimes want to use a block and other times not. 

	{{editable-text text=text}}

	{{#editable-text text=text as |text|}}
	  {{{markdown-text text}}}
	{{/editable-text}}

Is there any way to do this yet with the new block params, is the block stored somewhere on the component that I could check for? e.g.

	{{#if blockGiven}}
	  {{yield text}}
	{{else}}
	  {{text}}
	{{/if}}

**Comment by opsb** [comment]
I see it's available on the template so I can do

	blockGiven: function(){
		return this.get("template.blockParams") == true;
	}.property("template")

is this the best approach for now?

**Comment by mmun** [comment]
@opsb Yes that works for now.

**Comment by mmun** [comment]
I think this needs addressing.

**Comment by mixonic** [comment]
For sure.
