### ISSUE TITLE
New dependency injection syntax is counter-intuitive

### ISSUE THREAD

**Issue by buschtoens** [emberjs/ember.js#10339]
So, I just watched this great [talk on Ember 1.10](http://youtu.be/tFGFR8JRq-A?t=17m25s) by @ebryn. At the linked time mark he starts talking about the new dependency injection system, which is great - apart from a little detail.

I know this is probably a little late and my individual opinion is of no importance, but I ***heavily*** disagree with the logic of this implementation.

This is the example @ebryn was talking about:

```js
export default Ember.Controller.extend({
 anotherController: Ember.inject.controller() // injects "anotherContoller" as "anotherController"
});


export default Ember.Controller.extend({
 anotherController: Ember.inject.controller('foo') // injects "anotherController" as "foo"
});
```

Now take a look at the `Ember.computed.alias()` version of this.

```js
export default Ember.Controller.extend({
  needs: ['anotherController'],
  foo: Ember.computed.alias('controllers.anotherController') // injects "anotherController" as "foo"
});
```

Notice how the attribute name of the alias is on the left hand side and the controller "address" is on the right hand side.
  The new syntax does the exact opposite. It goes against the general idea of JavaScript syntax. You always assign the right hand value to the left hand variable / attribute and not the other way around.

To make it more obvious:
```js
// the plain old JS way:
// right hand side is assigned to left hand side
var foo = anotherController;

// the counter intuitive (and wrong) injection way:
// left hand side is supposed to be assigned to right hand side
anotherController = var foo; // ???
```

**Comment by rwjblue** [comment]
```javascript
export default Ember.Controller.extend({
 anotherController: Ember.inject.controller('foo') // injects "anotherController" as "foo"
});
```

The comment is incorrect, this will result in `FooController` being available under `anotherController`.

Example: http://emberjs.jsbin.com/rwjblue/274/edit?js,output (notice `logger2: Ember.inject.service('logger')`).

**Comment by buschtoens** [comment]
Oh god, you can't imagine how glad I am about your clarification! :)

But, if this is the case, am I just misunderstanding the presentation or is there an error?

**Comment by rwjblue** [comment]
I have not watched the presentation, not sure what was said...

**Comment by buschtoens** [comment]
It was my fault. I didn't pay enough attention to what @ebryn was saying. I was blinded by my own fear of stupid syntax. :D

Sorry for the buzz.

**Comment by ebryn** [comment]
Oops a typo on my part! Sorry!
