### ISSUE TITLE
ember.prod contains asserts

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#10347]
http://builds.emberjs.com/canary/ember.prod.js

for example:

```js
Ember['default'].assert('fullName must be a proper full name', this.validateFullName(fullName));
```

I suspect the `Ember['default']` that provides us with better cycle support in es6 modules is confusing defeaturify  (which I believe is remove the assert statements?)

**Comment by rwjblue** [comment]
This is another flavor of the defeatureify but I recently fixed in https://github.com/thomasboyt/defeatureify/pull/13.

**Comment by stefanpenner** [comment]
@rwjblue awesome, lets close when the canary build is updated.

**Comment by rwjblue** [comment]
Yep, will do.

**Comment by stefanpenner** [comment]
canary still contains these.

**Comment by stefanpenner** [comment]
http://builds.emberjs.com/canary/ember.prod.js

**Comment by ebryn** [comment]
confirm :(

**Comment by rwjblue** [comment]
The updates from https://github.com/emberjs/ember.js/pull/10348 do fix the issue, but the Travis build used a cached package instead of the defeatureify@0.2.2 that contains the fixes.  I cleared the cache, and retriggered the last Travis build.

**Comment by rwjblue** [comment]
Build is updated, and contains no debug statements.

**Comment by rwjblue** [comment]
I'll leave this open until @stefanpenner or @ebryn confirm.

**Comment by stefanpenner** [comment]
LGTM, thanks @rwjblue
