### ISSUE TITLE
Can't use xml namespaces in component attribute names

### ISSUE THREAD

**Issue by jdmarshall** [emberjs/ember.js#10359]
From the code:

      _applyAttributeBindings: function(buffer, attributeBindings) {
        var attributeValue;
        var unspecifiedAttributeBindings = this._unspecifiedAttributeBindings = this._unspecifiedAttributeBindings || {};

        forEach(attributeBindings, function(binding) {
          var split = binding.split(':');
          var property = split[0];
          var attributeName = split[1] || property;

          Ember.assert('You cannot use class as an attributeBinding, use classNameBindings instead.', attributeName !== 'class');

If you're trying to create a component that uses an XML Namespace (eg: 'xlink:href') this code splits the attribute name improperly, resulting in output of xlink="..."  instead of xlink:href="..."

Looking through the Ember and jQuery code I can't find any way to escape the colon to make Ember happy.

**Comment by oneeman** [comment]
Sounds related to https://github.com/emberjs/ember.js/pull/10186/files#r22773858

**Comment by jdmarshall** [comment]
I don't see any evidence in that PR that the problem is fixed.  The questionable code is still there, and although there is a discussion about it, it doesn't seem to be resolved.  I also don't see any tests covering that scenario.

**Comment by oneeman** [comment]
That's right.  Sorry, I didn't mean to suggest it'd been fixed already, just to point to where the problem has been referenced before.

**Comment by mixonic** [comment]
Closing this in favor of tracking it at https://github.com/emberjs/ember.js/issues/9298
