### ISSUE TITLE
Unknown helper error should be raised

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#10355]
The block hook should raise an assertion or throw an error if you call a helper that does not exist.

See: https://github.com/emberjs/ember.js/blob/88e6a95f4a379622f6a8a3ea2fd7280dece8bb08/packages/ember-htmlbars/lib/hooks/block.js#L19

Currently, if you try to use a helper not available, you get a cryptic error about calling `helperFunction` on undefined.

**Comment by suchitpuri** [comment]
Have opened a pull request https://github.com/emberjs/ember.js/pull/10362 for the same

**Comment by rwjblue** [comment]
Closed by #10362
