### ISSUE TITLE
Issue with nested query params and ObjectController

### ISSUE THREAD

**Issue by conrad-vanl** [emberjs/ember.js#10357]
I have an app that has what I'd describe as nested query params: My application controller has a query param that is used across the entire app, and then there are other routes/controllers that utilize other query params. I noticed today (on an app that has been recently upgraded to ember-canary + htmlbars, but haven't proven yet that the issue is new to those versions) that when using the `{{link-to}}` helper with query-params that just specify query-params for the current controller, the query-params for the application controller are actually cleared with the link is clicked. I noticed this is only happening when the `ApplicationController` is an `ObjectController`. I know the `ObjectController` has been deprecated, but as I am unsure yet if this could be causing other issues, I figured I'd go ahead and open a ticket with a JSBin demonstrating the issue.

http://emberjs.jsbin.com/dawacuguto

Notice after selecting a color if you try to select a shape it clears out the previous query param

**Comment by machty** [comment]
This is probably not worth fixing since ObjectController is deprecating and query params are shifting away from controllers shortly. Happy to reopen if there are any major disagreements.
