### ISSUE TITLE
link to arraycontroller fails when context is object

### ISSUE THREAD

**Issue by NetForce1** [emberjs/ember.js#10354]
When using link-to with an object as the context, to a route that extracts an array from that object, ember gives the following error:
`Uncaught Error: Assertion Failed: The value that #each loops over must be an Array. You passed <App.Order:ember280>`
When going directly to the url, all is well.

JSFiddle: http://jsfiddle.net/NetForce1/kdb7rtro/3/

**Comment by trek** [comment]
You've provided a model object, so the model hook is not called and the passed object is used instead. The object you're passing doesn't match the type of object you've previously used as a model. 

If your example the model for `orderlines` is not an order, but a collection of lines. Pass the collection of lines, not the order, to the link.

**Comment by NetForce1** [comment]
Sure, I could, but that sets the dynamic part in the url to undefined. So the url becomes `http://fiddle.jshell.net/_display/#/orders/undefined/lines`, see: http://jsfiddle.net/NetForce1/kdb7rtro/4/

**Comment by trek** [comment]
StackOverflow is a great place to get help and strategy tips on problems like this. You're seeing the intended behavior, so I don't think we'd consider this a bug.
