### ISSUE TITLE
'href' attribute of SVG 'image' element is not updated in template

### ISSUE THREAD

**Issue by uboot** [emberjs/ember.js#10368]
In a handlebar template the 'href' attribute of an image element inside an SVG is bound to the property of the controller. The property is set to a data URI, i.e. the complete image data is encoded in the property string. This setup worked with ember 1.9.1 but does not with ember 1.10.0-beta.x.

A minimal example is here:
http://emberjs.jsbin.com/dakitifori/6/edit?html,js,output

Change the version of ember to 1.9.1 to see the expected image.

**Comment by rwjblue** [comment]
Good news! This works properly on the latest beta builds: http://emberjs.jsbin.com/tuqayo/1/edit?html,js.
