### ISSUE TITLE
Reopen doesn't apply to previously created objects until new object is created.

### ISSUE THREAD

**Issue by brettburley** [emberjs/ember.js#10364]
Hi there,

I'm having trouble getting reopen to apply to previously created objects. Here's a jsbin that demonstrates the issue:
http://emberjs.jsbin.com/loqevidufu/3/edit

It appears that when calling `reopen` on a class, the new properties are not applied until a new object of that class is created. It also appears that manually invoking `Object.proto()` rather than creating a new object will also apply the new properties to previously created objects.

**Comment by stefanpenner** [comment]
@brettburley this is expected behavior.

Additionally, we actually are strongly considering removing the ability to re-open after the first instance has been created. This is extremely dubious and error prone functionality and the source of many of embers performance issues.
