### ISSUE TITLE
In model unit tests `this.subject().store` and `this.store()` are different

### ISSUE THREAD

**Issue by YoranBrondsema** [emberjs/ember.js#10367]
See this discussion on StackOverflow: http://stackoverflow.com/a/25945287/1269194. In a model unit test, the `Store` objects returned by `this.subject().store` and `this.store()` are not the same.

I only encountered this bug when upgrading our non-ember-cli project to ember-cli 0.1.11 so I'm not sure whether the bug lies in Ember.js, in ember-cli or even in ember-qunit.

**Comment by mixonic** [comment]
@YoranBrondsema I am nearly positive this is a bug in https://github.com/ember-cli/ember-cli-qunit, please open an issues there.

I've been burnt by the same!

**Comment by YoranBrondsema** [comment]
Thanks, I posted the issue there: https://github.com/ember-cli/ember-cli-qunit/issues/42
