### ISSUE TITLE
[FEATURE] debounce as an Ember.computed 'property'.

### ISSUE THREAD

**Issue by h55nick** [emberjs/ember.js#10361]
The idea here is the implementing an Ember.run.debounce is a bit more cumbersome than needed in certain cases. What I propose (and am willing to do as much legwork as my skills will allow) is that debounce becomes part of the Ember.computed api.

Example:
```javascript
filteredArray: function(){
  var regex = new RegExp(this.get('textInputFilter'), 'i');
  return this.get('modelArray').filter(function(item){
    return item.get('matchItem').match(regex);
  });
}.debounce('textInputFilter', 2000),
```

this would allow filteredArray to be treated as 'computed property' in templates, etc but would be delayed for the 2000ms (2 seconds) as the debounce would be defining. The default context would be 'this'- open to how would could allow this to be configurable.

I'm open to ideas on how the feel of this can be improved and please let me know if this is a terrible idea, great idea, etc. 

(first time contributor so if I am doing this wrong please let me know)

**Comment by h55nick** [comment]
@lukemelia this is my take on the direction of our chat after the last NYC meetup. Is this inline with your thoughts?

**Comment by lukemelia** [comment]
@h55nick there's a disconnect between your description of this as part of `Ember.computed` vs it being a Function prototype extension as shown in the example. As an `Ember.computed` macro, this would look like:

```js
filteredArray: Ember.computed.debounce('textInputFilter', function(){
  var regex = new RegExp(this.get('textInputFilter'), 'i');
  return this.get('modelArray').filter(function(item){
    return item.get('matchItem').match(regex);
  });
}, 2000),
```

I think this approach is better than adding an additional method to `Function.prototype`.

You can implement this as an addon, which I would suggest doing first. Then you and others can try it in real-world apps and vet the API and its usefulness. If it proves to be helpful to a good number of people, then we should consider it for addition to Ember core.

**Comment by cibernox** [comment]
I agree with @lukemelia. Extending the function prototype is somewhat aggressive, but as a computed property macro might be a good idea. Seems convenient.

If you want you can make a PR to https://github.com/cibernox/ember-cpm

**Comment by h55nick** [comment]
excellent. and agreed. Was thinking it would be defined as a computed macro but called as a Fn.prototype. See the confusion there. And good call on exploring usefulness before moving to core. Guess I was jumping the gun there.

@cibernox will try and get a PR to ember-cpm before/during ember-conf.

Thanks guys.

**Comment by brendan-rius** [comment]
@h55nick any progress here?
