### ISSUE TITLE
can't access service from another service, no documentation about it

### ISSUE THREAD

**Issue by mgenev** [emberjs/ember.js#10374]
I've done this before with controllers and an initializer, 'register' and 'after'.  This time, I'm using ember-cli, I generate a service. The blueprint also makes me an initializer. I do it again for another service.

The services cannot access each other even after I use 'after' like this:

```
export function initialize(container, application) {
    application.inject('route', 'first', 'service:first');
    application.inject('controller', 'first', 'service:first');
    application.inject('view', 'first', 'service:first');
};

export default {
    name: 'first-service',
    initialize: initialize
};
```

```
export function initialize(container, application) {
  application.inject('route', 'geoService', 'service:geo');
  application.inject('component', 'geoService', 'service:geo');    
}

export default {
  name: 'geo-service',
  after: 'first-service',
  initialize: initialize
};
```
Both services are accessible in a route, but first-service is not accessible from geo-service. If I misspell 'first-service' in the after, ember breaks saying there is no such service, so I know that is being evaluated but it makes no difference when the name is accurate.

It seems to me the issue might be because 'after''s logic depends on 'register'. I saw that this service generation from the blueprint is missing a 'register' line like you had to do with controllers, but here it says that I don't need that with services, and that's what I infer from some change logs in ember-cli
http://stackoverflow.com/questions/25387055/ember-cli-cannot-register-a-service

The Ember docs only make a reference to using controllers as a service here:
http://emberjs.com/guides/understanding-ember/dependency-injection-and-service-lookup/

But there is nothing that I can find about the services ember-cli generates and how to make them depend on other services.

The API docs entry for Service doesn't tell me anything about that either:
http://emberjs.com/api/classes/Ember.Service.html

Is this feature finished? Should I be using a regular controller and register it? Should this bug be filed with ember-cli because of the way it generates these services and initializers?

**Comment by rlivsey** [comment]
AFAICT you're injecting the `first` service into all routes, controllers and views, then you're injecting `geoService` into all routes and components. Nowhere are you injecting `first` service into `geoService` so it doesn't have access to it.

You should be able to do something like the following to hook this up:

```javascript
application.inject('service:geo-service', first', 'service:first'')
```

With the new services stuff in `ember-metal-injected-properties` you should be able to do this more easily without any of the injections, that's currently behind a feature flag in canary (and in beta?) but looks to be coming soon in #10373 

Eg to access `first` service from a controller:

```javascript
export default Ember.Controller.extend({
  first: Ember.inject.service()
});
```

And IIRC the same should work from other services too:

```javascript
export default Ember.Service.extend({
  first: Ember.inject.service()
});
```

**Comment by mgenev** [comment]
I tried injecting into all services like the routes and components, but it gave me an error, saying I can't do that. Am I supposed to inject it into every single service explicitly?

**Comment by rlivsey** [comment]
Hmm not sure, I'm injecting services into all other services too, but I'm currently going directly via the container as opposed to through application and that's frowned upon now (and deprecated I think).

Eg the following is from my app:

```javascript
import Ember from 'ember';

export default {
  name: 'current',
  initialize: function(container) {
    var current = Ember.Object.create();

    container.optionsForType('current', { instantiate: false, singleton: true });
    container.register("current:main", current);

    container.typeInjection('controller', 'current', 'current:main');
    container.typeInjection('route',      'current', 'current:main');
    container.typeInjection('component',  'current', 'current:main');
    container.typeInjection('service',    'current', 'current:main');
  }
};
```

The new style stuff is better though, so probably the preferred option going forwards.

**Comment by stefanpenner** [comment]
> Error: Cannot inject a `service:first` on other service(s). Register the `service:first` as a different type and perform the typeInjection.

this error message is terrible

**Comment by stefanpenner** [comment]
the following should work correctly

```js
app.inject('service:foo', 'bar', 'service:bar')
```

**Comment by mgenev** [comment]
@stefanpenner thanks,  but that forces me to do it for every service that needs it, right?

**Comment by stefanpenner** [comment]
@mgenev yes, you cannot inject something onto itself, which is what you are doing.

**Comment by stefanpenner** [comment]
https://github.com/emberjs/ember.js/pull/10375

**Comment by mgenev** [comment]
@stefanpenner doing it explicitly did work and thanks for opening the ticket to clean up the messaging. It will save people some time.

**Comment by stefanpenner** [comment]
@mgenev ya, i suspect more docs in this area are needed. Especially when it comes to best practices.
