### ISSUE TITLE
Non-context switching {{#with}} switches context inside of an {{#each}} loop

### ISSUE THREAD

**Issue by markprzepiora** [emberjs/ember.js#10370]
With the following controllers,

```javascript
App.FoosController = Ember.ArrayController.extend({
  itemController: 'foo'
});

App.FooController = Ember.Controller.extend();
```

and the following `foos` template,

```handlebars
     <p>Outside of the loop, "this" is {{this}}</p>
     {{#each this as |fooController|}}
       <p>Inside of the loop, "this" is still {{this}}</p>
       {{#with fooController.model as |foo|}}
         <p>But inside of the "with" within the loop, "this" is {{this}}</p>
       {{/with}}
     {{/each}}
```

and the `application` template being just,

```handlebars
    {{render "foos" items}}
```

Since I'm using the non-context-switching versions of all the helpers, I expect every `{{this}}` to be the same (namely, `FoosController`). But instead the first two `{{this}}` statements print out `FoosController`, but the third prints out `FooController`.

Is this a bug or am I completely misunderstanding something?

JSBin here: http://jsbin.com/fuqota/5/edit?html,js,output

**Comment by rwjblue** [comment]
I believe this is related to https://github.com/emberjs/ember.js/issues/10401.

**Comment by rwjblue** [comment]
This was fixed by https://github.com/emberjs/ember.js/pull/10489.
