### ISSUE TITLE
Custom attributes added via attributeBindings are always in lowercase.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#10376]
Example:

```javascript
App.IndexView = Ember.View.extend({
  attributeBindings: ['someStringAttribute'],
  someStringAttribute: 'foo'
});
```

Is generating the following in DOM inspector:

```html
<div id="ember235" class="ember-view" somestringattribute="foo"></div>
```

**Note that the property added is down cased.**

Beta: [JSBin](http://emberjs.jsbin.com/rwjblue/291/edit?html,js,output)
Canary: [JSBin](http://emberjs.jsbin.com/rwjblue/292/edit)

**Comment by rwjblue** [comment]
I believe that https://github.com/emberjs/ember.js/commit/5b1c277a3bb570817b185650255ba2e212907a10 is the culprit.

**Comment by rwjblue** [comment]
Same behavior: 

* 1.7.0: http://emberjs.jsbin.com/jivuye/1/edit?html,js,output
* 1.5.0: http://emberjs.jsbin.com/jivuye/2/edit
* 1.3.0: http://emberjs.jsbin.com/jivuye/3/edit
* 1.0.0: http://emberjs.jsbin.com/jivuye/4/edit

**Comment by rwjblue** [comment]
This [JSBin](http://jsbin.com/xuvitu/1/edit?html,js,output) (without Ember) exhibits the same behavior:

```javascript
var elem = document.createElement('div');
elem.setAttribute('someCamelThing', 'foo');

log(elem.outerHTML); //=> <div somecamelthing="foo"></div>
```

**Comment by GerritSommer** [comment]
For those with the same problem. There is a simple solution. I had the same problem with the viewBox of an SVG element. 
````javascript
Component.extend({
  attributeBindings: ['someStringAttribute:someStringAttribute'],
  someStringAttribute: 'foo'
});
````
(See the attributeBinding repeated with a double colon. Tested with ember 3.1)
