### ISSUE TITLE
`link-to` documentation request / confusing behavior with async realtionships

### ISSUE THREAD

**Issue by nichoth** [emberjs/ember.js#10385]
Loading related async models when using the `link-to` helper is confusing. From the documentation I should be able to return a promise for the related model in the `afterModel` hook in a route, and the related models will be resolved before the template is rendered. Given this router and models, entering the URL and loading the page fetches the related models, but navigating to route `nodes/:node_id` via the `link-to` helper does not fetch related models.

```js
// router.js
Router.map(function() {
  this.resource('index', {path: '/'}, function() {
    this.resource("nodes", function() {
    });
    this.resource('node', {path: 'nodes/:node_id'});
  });
});

// routes/node.js
export default Ember.Route.extend({
  afterModel: function(model) {
    var promise = model.get('relatedModels');
    return promise;
  },
});

// models/node.js
import DS from 'ember-data';
export default DS.Model.extend({
  type: DS.attr('string'),
  name: DS.attr('string'),
  relatedModels: DS.hasMany('relatedModel', {async:true}),
});

// models/related-model.js
import DS from 'ember-data';
export default DS.Model.extend({
  name: DS.attr('string'),
  node: DS.belongsTo('node', {async:true}),
});
```

If this is expected behavior, the documentation should be updated, because I cannot figure out how to fetch and access the related model when I click on a link.

The related models are being called in `templates/node.hbs`:

```hbs
{{model.name}}
{{#each related in model.relatedModels}}
  {{related.id}}, {{related.name}}
{{/each}}
{{outlet}}
```

**Comment by jbrown** [comment]
Did you originally try it without `afterModel` using that template and nothing loaded? Simply iterating through `model.relatedModels` like you're doing will fetch them and once they are loaded the template will update.

Can you make a jsbin to reproduce it?

**Comment by nichoth** [comment]
Arg. It works in JSBin. Could this be caused by jsbin loading the URLs differently? The docs say this JSbin shouldn't work. 

http://jsbin.com/mozexevaso/3/edit?html,js,output

**Comment by lolmaus** [comment]
Hey @nichoth, i haven't tried your repo, but i replaced fixtures with a backend mock in your JSBin, and it still works: http://jsbin.com/xivotu/3/edit?html,js,output

**Comment by lolmaus** [comment]
@nichoth, tried your repo. Works without any errors in the console. I tried both opening a link and refreshing the page (i. e. entering the child route via a direct link).

Please elaborate.

**Comment by nichoth** [comment]
To clarify: it doesn't show errors, but do you get the same data on the page whether you click a link or enter the URL for that link? Thanks for testing.

**Comment by lolmaus** [comment]
@nichoth, i think i do. Try it yourself here: http://jsbin.com/xivotu/3

**Comment by nichoth** [comment]
Yes, the jsbin works like I would expect. This is interesting. I will try it more in my environment soon.

**Comment by titofmax** [comment]
Hello, I do have the exact same issue working with sails as backend.

1) I am using link-to
2) The data is the same on both pages (the one I come from and the one I linked to)
3) All the data is here if I refresh the page

 Did anyone find a reason to this ?

**Comment by pixelhandler** [comment]
@nichoth the docs have been greatly improved since you created this issue, so has Ember Data. Please reopen if you still have this issue. Related docs: https://guides.emberjs.com/v2.7.0/templates/links/
