### ISSUE TITLE
Ember-data failing in test tearDown

### ISSUE THREAD

**Issue by technomage** [emberjs/ember.js#10388]
In migrating a shell app from 1.10 beta to 1.11 beta a passing test fails with an error in EmberData.  Note that at this point the app is not using EmberData (no models and no record arrays created).  EmberData is at beta 14.1.  My working assumption is that it needs a null check for there being no record arrays to process.

afterEach failed on Site navigation: Requested keys of a value that is not an object.@ 340 ms
Source: 	
keys@[native code]
ember$data$lib$system$record_array_manager$$values@http://localhost:4747/assets/vendor.js:68301:28
willDestroy@http://localhost:4747/assets/vendor.js:68294:163
superWrapper@http://localhost:4747/assets/vendor.js:30981:24
invoke@http://localhost:4747/assets/vendor.js:14416:22
flush@http://localhost:4747/assets/vendor.js:14481:19
flush@http://localhost:4747/assets/vendor.js:14286:24
end@http://localhost:4747/assets/vendor.js:13711:32
run@http://localhost:4747/assets/vendor.js:13766:23
run@http://localhost:4747/assets/vendor.js:29316:32
willDestroy@http://localhost:4747/assets/vendor.js:17213:21
superWrapper@http://localhost:4747/assets/vendor.js:30981:24
invoke@http://localhost:4747/assets/vendor.js:14416:22
flush@http://localhost:4747/assets/vendor.js:14481:19
flush@http://localhost:4747/assets/vendor.js:14286:24
end@http://localhost:4747/assets/vendor.js:13711:32
run@http://localhost:4747/assets/vendor.js:13766:23
run@http://localhost:4747/assets/vendor.js:29316:32
teardown@http://localhost:4747/assets/webui.js:774:27
runHook@http://localhost:4747/assets/test-support.js:2881:24
process@http://localhost:4747/assets/test-support.js:2538:24
begin@http://localhost:4747/assets/test-support.js:2583:9
http://localhost:4747/assets/test-support.js:2599:9

**Comment by bmac** [comment]
@technomage could you open this issue on the Ember Data repo? I suspect this has to do with [these changes](https://github.com/emberjs/ember.js/commit/685d9e36fee7a8d99f3811a9f99758a1231ffaa7) to Ember's Map class.

**Comment by rwjblue** [comment]
As @bmac mentioned, this belongs in the ember-data repo. Closing in favor of future issue over there....

**Comment by sameersegal** [comment]
@technomage, I can't find your issue on Ember Data repo. Is there a work around?
