### ISSUE TITLE
CPs now recompute/are accessible on destroyed objects

### ISSUE THREAD

**Issue by igorT** [emberjs/ember.js#10383]
Before the removal of `descs` from meta, destroying an object would render any CP as `undefined`. Now, you can still try and cause that CP to recompute.

Release -> http://emberjs.jsbin.com/mutidibere/1/edit?js,output
Canary -> http://emberjs.jsbin.com/deceze/1/edit?html,js,output

Notice how in the canary version we are actually returning from the CP.

**Comment by ebryn** [comment]
I consider the prior behavior undefined. Especially since there were no tests verifying this behavior.

I don't view computed properties any differently than simple properties / methods. Neither of which have this behavior.

**Comment by stefanpenner** [comment]
> Before the removal of descs from meta, destroying an object would render any CP as undefined. Now, you can still try and cause that CP to recompute.

this alone doesn't seem like a problem.

are their any other resulting issues, maybe like "do change events fire post deletion"?

**Comment by krisselden** [comment]
Change events should not fire to other objects that are flagged as isDestroying, the point of isDestroying is so you can teardown without causing a lot of churn, I'm hoping nothing was changed in regard to that.

**Comment by krisselden** [comment]
It is actually the whole reason why isDestroying is set and willDestroy is run async

**Comment by krisselden** [comment]
Also we don't want it to recreate the meta after it has already been destroyed

**Comment by ebryn** [comment]
I don't see how any change event related behavior would have changed. You'll still get an assert if Ember.set is ran while isDestroying is true.

**Comment by stefanpenner** [comment]
lots of bugs, in chains/bindings/meta in destruction. This whole area needs to be revisited and thoroughly cleaned up. This is likely something we will tackle post-glimmer.

**Comment by rwjblue** [comment]
We plan to move CP descriptors back into `meta` "soon". I recall that @stefanpenner had some initial work in progress in this area, but couldn't find it during a quick search.

We definitely intend to change the behavior so that this is less of an issue, but I do not consider the current behavior a "bug" at this point.

**Comment by stefanpenner** [comment]
@rwjblue ya, @krisselden is working on it now.
