### ISSUE TITLE
HTML character entities are escaped in the link-to helper

### ISSUE THREAD

**Issue by kimroen** [emberjs/ember.js#10392]
This used to work just fine in 1.9.1 and earlier, but doesn't any more in 1.10.0.

Using the inline version of `link-to`, HTML character entities are escaped.

Example:

```handlebars
{{link-to 'Go there &rarr;' 'index'}}
```

Before:
> Go there &rarr;

Now:
> Go there &amp;rarr; (`&amp;rarr;`)

http://emberjs.jsbin.com/bitori/1/edit

I can obviously get around this by using the block form here, but just wanted to share.

**Comment by mixonic** [comment]
Much of the logic that bindings and raw values pass through has been unified in the past few releases. It looks like we used to consider a raw string passed to link-to as HTML-safe.

I'm not crazy about having raw strings and bound ones have differing safe-ness. It seems more predictable to have them be unified as unsafe. I'll bring it up for discussion.

This may also point to a need for a `(safe-string 'Go there &rarr;')` nested helper. This would then be usable with any bound or un-bound values.

**Comment by mixonic** [comment]
I think an `html-safe` helper would be really well received. Flagging this as good for contribution, should be fairly straight ahead!

**Comment by lazybensch** [comment]
the triple curlies version applied on every inline helper will produce html-safe output as far as i can see.

so
```{{link-to 'Go <b>there</b> &rarr;' 'index' }}``` 
>`Go <b>there</b> &rarr;`

 ```{{{link-to 'Go <b>there</b> &rarr;' 'index' }}}``` 
>Go **there** &rarr;

**Comment by martypenner** [comment]
Can confirm the triple curly behaviour in Ember 1.11.3. Is it really necessary to add the `html-safe` helper?

**Comment by kimroen** [comment]
It seems unnecessary to me, considering the triple curlies exist. This issue was mostly about the regression, but the time has passed for that.

Please reopen if there is still a need for a `html-safe`-helper that would behave differently or have some other reason for existing.

**Comment by mwpastore** [comment]
Triple-curly use was discouraged by the Prototypal Training team during a recent Ember.js training session in Chicago. There may still be a need for such a helper.

**Comment by rwjblue** [comment]
There is an internal `-html-safe` helper.  I think that I would generally be :+1: if someone wanted to document it and feature flag exposing it as public API.

**Comment by mixonic** [comment]
Rolling a custom `(html-safe` helper is also quite trivial.

**Comment by mwpastore** [comment]
Of course, and I've done so, it just strikes me as one of things where if everyone has to do it anyway, maybe the framework should do it for them by default. :-)

**Comment by rwjblue** [comment]
Everyone definitely doesn't have to do it (I do not believe I have needed it yet for example), but even if everyone needed it all you need to do is make a nice addon and share it. :wink:
