### ISSUE TITLE
How to register helpers in Ember 1.10.0?

### ISSUE THREAD

**Issue by QuantumKing** [emberjs/ember.js#10394]
In the [CHANGELOG](https://github.com/emberjs/ember.js/blob/v1.10.0/CHANGELOG.md) for Ember 1.10.0 under "Cleanup HTMLBars public API" it claims to use `registerHelper` to create a helper, however this function is actually private. What is the preferred way of registering a helper then?

**Comment by rwjblue** [comment]
@QuantumKing - Registering Handlebars style helpers is still supported via the compatibility mode that we added (which has performance implications). If you want to use HTMLBars helpers without using the private `Ember.HTMLBars._registerHelper` API, you would need to allow it to be resolved.

Assuming the name `{{some-thing}}` you would have the following options:

* Globals: define `App.SomeThingHelper = Ember.HTMLBars.makeBoundHelper(function(params, hash, options, env) { /* your helper code here */ });`
* Modules: create a module at `app/helpers/some-thing.js` that contains: `export default Ember.HTMLBars.makeBoundHelper(function(params, hash, options, env) { /* your helper code here */ })

**Comment by panta82** [comment]
I'm also trying to make this work, and am getting `Assertion Failed: makeBoundHelper generated helpers do not support use with blocks `.

So what's the HTMLBars solution for making unbound helpers?

**Comment by dave8401** [comment]
@rwjblue Does that mean that with HTMLBars only helpers with a dasherized name can be registered via public APIs? I previously helped myself with *Ember.HTMLBars.registerHelper* as you pointed out [here](https://github.com/emberjs/ember.js/issues/10153). 

    Ember.HTMLBars.registerBoundHelper = function(name, callback){
      Ember.HTMLBars.registerHelper(name, Ember.HTMLBars.makeBoundHelper(callback);
    };

Renaming is not an issue, but right now all info about custom helpers within HTMLBars are somewhat dated.
