### ISSUE TITLE
Uncaught Error: Assertion Failed: A fragment cannot be pushed into a buffer that contains content

### ISSUE THREAD

**Issue by badazz91** [emberjs/ember.js#10400]
Hey,

after upgrading our app from ember 1.9.1 to 1.10.0 we get following error message:
```
Uncaught Error: Assertion Failed: A fragment cannot be pushed into a buffer that contains content
ember.debug.js:3940
Ember.assertember.debug.js:39926
_RenderBuffer.pushember.debug.js:44633
CoreView.extend.renderember.debug.js:14372
superFunctionember.debug.js:40659
_MetamorphView.extend.renderember.debug.js:18187
superWrapperember.debug.js:40279
EmberRenderer_createElementember.debug.js:8768
Renderer_renderTreeember.debug.js:8845
scheduledRenderTreeember.debug.js:854
Queue.invokeember.debug.js:919
Queue.flushember.debug.js:724
DeferredActionQueues.flushember.debug.js:149
Backburner.endember.debug.js:204
Backburner.runember.debug.js:16638
runmain.js:111 (anonymous function)jquery.js:3119
jQuery.Callbacks.firejquery.js:3231
jQuery.Callbacks.self.fireWithjquery.js:9275
donejquery.js:9685
jQuery.ajaxTransport.send.callback
```

**Comment by rwjblue** [comment]
Can you make a small reproduction (JSBin or repo) so we can try to help track this down?

**Comment by badazz91** [comment]
I'll try to reproduce something on a small scale (it's really hard to reproduce, if there is no idea, where it comes from ...). It is really strange, because our app works just fine with 1.9.1. It immediately breaks after launching with ember 1.10.0.

**Comment by badazz91** [comment]
Meanwhile I have found out, where the error is thrown. This code is located in ember.debug.js.

```javascript
      /**
        Adds a string of HTML to the `RenderBuffer`.

        @method push
        @param {String} string HTML to push into the buffer
        @chainable
      */
      push: function(content) {
        if (typeof content === 'string') {
          if (this.buffer === null) {
            this.buffer = '';
          }
          Ember.assert("A string cannot be pushed into the buffer after a fragment", !this.buffer.nodeType);
          this.buffer += content;
        } else {
          Ember.assert("A fragment cannot be pushed into a buffer that contains content", !this.buffer);
          this.buffer = content;
        }
        return this;
      },
```
The strange part is for instance, that we do not override the render()-method in a view and our template markdown also seems legit (it worked fine until now). Maybe this helps a bit.

**Comment by sergetab** [comment]
Same problem here. And the strange thing is that the value of this.buffer (which is supposed to not contain content) is
```
"<script id='morph-0' type='text/x-placeholder'></script>"
```
Is it generated by Handlebars? But I removed Handlebars after updating to 1.10.0

**Comment by rwjblue** [comment]
There are a number of ways to come across this issue, as I mentioned earlier we will need a reproduction (JSBin or repo) to be able to help further.

**Comment by badazz91** [comment]
I've traced down the issue. Our app depends heavily on ember-i18n. It seems that the 
```javascript
{{t 'somekey'}}
```
helper does break the app, when running the app against ember-1.10.0. I think that it also relates to this issue: https://github.com/emberjs/ember.js/issues/9961.

FYI: We're using the latest ember-cli 0.1.12

**Comment by fpauser** [comment]
After switching away from react (we used it in a component''s render-func) the problem went away and everything works fine with ember-1.10. Horray! ;)

I assume we either did something wrong in our components `render`. While thinking a bit more about it: After removing react from the application chrome-developer-tools stopped crashing each time when inspecting an SVG that was rendered by our application... 

Maybe react somehow behaves strange and does some nasty dom-trickery that confuses ember/chrome under specific circumstances?

/cc @badazz91

**Comment by fpauser** [comment]
@sergetab Maybe this is related to using a 2.x version of ember-i18n? See https://github.com/jamesarosen/ember-i18n/commit/58f7b0da1557c2acc3eea4b6ae6de1a88a7e191f

No problems here using the current 3.x of ember-i18n (beta) with ember-1.10.

**Comment by sergetab** [comment]
@fpauser I've traced it down. In my case it is caused by a component with a overridden "_yield" function to switch context. Luckily with the new syntax for {{yield}} I don't need it anymore. So for me problem is solved.

**Comment by badazz91** [comment]
Ok all problems solved. This issue can be closed.

**Comment by runspired** [comment]
+1 @sergetab thanks, I bumped into this as well and I also was overriding _yield for components to expose the `component` keyword.  I knew I needed to remove that for the upgrade but hadn't done it yet and hadn't traced that as the source of the problem.

**Comment by givanse** [comment]
I'm seeing this same error after upgrading an addon and I don't see any of the helpers or overrides mentioned above.

Repo that shows the error: https://github.com/givanse/ember-bootstrap-datetimepicker/tree/bump-libs

**Comment by givanse** [comment]
This are gone in v1.11.0-beta.5.

**Comment by perlun** [comment]
Apparently, `_yield` is gone in 1.13.7. I wonder what replaces it. :stuck_out_tongue:
