### ISSUE TITLE
Consider components with a / (and no -) in their name to be valid.

### ISSUE THREAD

**Issue by tim-evans** [emberjs/ember.js#10407]
This is a pain point with code organization on our app. We currently have 90 component definitions in `/components`, and I would like to push some of these components into a folder for organizational purposes.

For a small sample, we have `artwork-weight`, `artwork-piece`, `artwork-image`, `artwork-dimensions`, `artwork-image-approver`, as components organized under the artwork vertical.

I'm also willing to hear other organizational strategies (like pods), but I'll need some guidance, and I'm hesitant to move to pods unless there are major positives to this.

For current info on our app, we're on 1.8, upgrading to canary and running on ember-cli

I've been working also on refactoring our application in the process of upgrading to canary, since we were using workarounds and patterns that are no longer supported.

Thanks!

**Comment by rwjblue** [comment]
This should "just work" with Ember 1.9 and above.

**Comment by workmanw** [comment]
That's curious, how would the ES6 resolver know where to look for a component in a sub folder? I thought it pods and otherwise functioned by having predictable structures.

**Comment by chnn** [comment]
I'm also unable to get this to work. Do you still need a dasherized name when a component is nested? For example will moving a `reports-list` component to `reports/list` not work because it should be `reports/list-something`? Or maybe it's the combination of the component pod structure and the slash?

**Comment by tobscure** [comment]
Working fine for me. You do still need a dasherized name.

**Comment by rwjblue** [comment]
Made a demo repo. See this commit: https://github.com/rwjblue/components-in-subdirs/commit/21099392164f6ccc0c3742434266134eaddcdff5

**Comment by lolmaus** [comment]
> @workmanw:
> That's curious, how would the ES6 resolver know where to look for a component in a sub folder? I thought the pods and otherwise functioned by having predictable structures.

I [had](https://github.com/ember-cli/ember-cli/issues/3234#issuecomment-73544622) the same concern, but @nathanpalmer kindly [explained](https://github.com/ember-cli/ember-cli/issues/3234#issuecomment-73560164) that this is not an issue at all.

**Comment by workmanw** [comment]
@lolmaus Yea given that the subdirectory is part of the name that makes sense.

One thing I'm still curious about is how this will play out once HTMLBars has shed it's Handlebars templates. Will the following just keep working?

```html
<subdir1/template-only random-string="something passed in the application.hbs">
</subdir1/template-only>
```

**Comment by rwjblue** [comment]
Yes.

Also, htmlbars will not stop allowing the usage of mustaches. You will likely always use curlies for things like '{{if}}', '{{each}}', etc.

**Comment by workmanw** [comment]
@rwjblue Hey thanks for the quick reply!

**Comment by tim-evans** [comment]
@rwjblue I think you misunderstood. I would like to consider `artwork/weight` valid. I would like the regex to be dash -or- slash.

**Comment by rwjblue** [comment]
@tim-evans - Interesting idea.  Flagging for discussion at the next core team meeting...

**Comment by tim-evans** [comment]
Thanks! :3

**Comment by stefanpenner** [comment]
i like this

**Comment by rwjblue** [comment]
As do I.

**Comment by nathanpalmer** [comment]
Seems like this might already be partially supported.

  * emberjs/ember.js: [Document path based component/helper names](https://github.com/emberjs/ember.js/issues/10243)
  * wycats/handlebars.js: [helper names can be paths?](https://github.com/wycats/handlebars.js/issues/912)

**Comment by tim-evans** [comment]
@nathanpalmer nope, not yet https://github.com/emberjs/ember.js/blob/876eecf6ab29159b1ef5474f2c62da139bb636c0/packages/ember-htmlbars/lib/system/lookup-helper.js#L12

**Comment by stefanpenner** [comment]
basically this boils down to `/` isn't valid HTML, in theory we may be able to move to `:` or some other delimiter. This is a high priority to solve as part of the new angle components, stay tuned.
