### ISSUE TITLE
Wrong context when rendering a component instance with the {{view}} helper

### ISSUE THREAD

**Issue by tobscure** [emberjs/ember.js#10401]
When passing a view instance into the {{view}} helper, the context inside the view's template remains the same as that of the parent.

Demo (1.10, broken): http://emberjs.jsbin.com/widubeyuti/1/edit

Demo (1.9, working): http://emberjs.jsbin.com/nuracayaxu/1/edit

**Comment by tobscure** [comment]
The line causing the context to be overwritten is this one: https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/system/append-templated-view.js#L32

I think the issue here is that the component being passed in doesn't have a controller, so its context gets overwritten. But components have their own context, so the context *shouldn't* get overwritten.

**Comment by rwjblue** [comment]
I believe this is the underlying issue in https://github.com/emberjs/ember.js/issues/10370 also.

**Comment by tobscure** [comment]
I also noticed that any properties set on the {{view}} helper itself do not carry through. e.g.

```
{{view view.component text="Strawberries"}}
```
