### ISSUE TITLE
Fresh ember-cli application doesn't work with ember beta-11 and ember-data

### ISSUE THREAD

**Issue by johanobergman** [emberjs/ember.js#10403]
##### Steps to reproduce:
1. `ember new app`
2. Set `"ember": "beta"` in bower.json, and remove handlebars dependency
3. Remove `broccoli-ember-hbs-template-compiler` and add `"ember-cli-htmlbars": "^0.6.0"`
4. Fix bug with handlebars being required in Brocfile.js ```var app = new EmberApp({
	vendorFiles: {
		'handlebars.js': null
	}
});```
5. `rm -rf node_modules bower_components`, `npm cache clean`, `bower cache clean`, `npm install`, `bower install`

The error I get:

```Uncaught TypeError: undefined is not a function
ember-data.js:12506 (anonymous function)
ember-data.js:71 requireModule
ember-data.js:42 reify
ember-data.js:70 requireModule
ember-data.js:42 reify
ember-data.js:70 requireModule
ember-data.js:12944 (anonymous function)
ember-data.js:12944 (anonymous function)```

followed by:

```Error while processing route: index Cannot read property 'template' of undefined TypeError: Cannot read property 'template' of undefined
    at http://localhost:4200/assets/app.js:71:38
    at requireModule (http://localhost:4200/assets/vendor.js:77:29)
    at resolveOther (http://localhost:4200/assets/vendor.js:59644:20)
    at superWrapper [as resolveTemplate] (http://localhost:4200/assets/vendor.js:28012:20)
    at exports.default.EmberObject.default.extend.resolve (http://localhost:4200/assets/vendor.js:15411:43)
    at Object.resolve [as resolver] (http://localhost:4200/assets/vendor.js:15177:23)
    at resolve (http://localhost:4200/assets/vendor.js:12697:29)
    at Object.Registry.resolve (http://localhost:4200/assets/vendor.js:12241:21)
    at factoryFor (http://localhost:4200/assets/vendor.js:11811:28)
    at instantiate (http://localhost:4200/assets/vendor.js:11872:19)```

It seems to be caused by this line in ember-data: `Ember.Handlebars.helper('singularize', singularize);` Updating to ember-data 1.0.0-beta.14.1 does not help.

Everything seems to be working fine on ember#canary.

**Comment by Panman8201** [comment]
I just ran into this issue, seems the `bower install --save ember#beta` is borked, the beta tag. Running `bower install --save ember#1.11.0-beta.1` works. Also, I think you have to update ember-data `bower install --save ember-data#1.0.0-beta.14.1`

**Comment by al3x-edge** [comment]
@rwjblue, same setup as @johanobergman. Just have recently been trying to get more ready for Ember 2.0.  Updated to 1.10 beta just a few days ago and followed the directions to render with HTMLBars by removing hbs-template-compiler. Everything was okay.  Realized this morning that 1.11 dropped in beta and went to upgrade.  Removed `bower_components` and ran `bower install` again (didn't clean out npm though). That is when the error happened.

Ended up using what @Panman8201 suggested shortly after.  Looked like the beta tag wasn't quite right but wasn't sure. Hadn't come back to investigate more.

**Comment by TrueNorth** [comment]
May be related: https://github.com/emberjs/ember-dev/pull/148#issuecomment-73586294

I just dealt with the same incompatibility in several apps

**Comment by rwjblue** [comment]
Ember CLI 0.2.0-beta.1 ships with Ember 1.10 and Ember Data 1.0.0-beta.15 by default, and does not have these errors (boots just fine).

I'm going to close this now, but will happily reopen if it is still an issue.
