### ISSUE TITLE
Properties on nested objects in ember doesn't fire if the object key was in PascalCase

### ISSUE THREAD

**Issue by nadeemkhedr** [emberjs/ember.js#10414]
When i update a property inside a `PascalCase` object inside `Ember.Object` the properties related to it won't update.

Here is an example

When i update `WontWork.val`, `wontWorkProp` won't update.
I've included a fiddle

```javascript
App.CustomModel = Ember.Object.extend({
  workProp: function() {
    return this.get('work.val');
  }.property('work.val'),
  wontWorkProp: function() {
    return this.get('WontWork.val');
  }.property('WontWork.val')
});

App.IndexRoute = Ember.Route.extend({
  model: function() {
    return App.CustomModel.create({
      work: {
        val: 'Bar'
      },
      WontWork: {
        val: 'Bar'
      }
    });
  }
});
```

Fiddle: http://jsbin.com/lukahogeye/2/edit?html,js,output

**Comment by rwjblue** [comment]
Sadly, due to some pretty old (and on the way out) semantics, `Ember.get` assumes that any paths starting with a capital letter are globals.  We intend to phase this concept out, but are stuck supporting it due to SemVer concerns.

**Comment by stefanpenner** [comment]
@rwjblue we should add this to the 2.x milestone

**Comment by eibrahim** [comment]
I have the same issue :(

**Comment by srsgores** [comment]
Still not fixed.  Long debugging session with @SaladFork and @Grapho... [see jsbin](http://jsbin.com/damowe)

**Comment by grapho** [comment]
+1

**Comment by stefanpenner** [comment]
@mmun in my mind i have assigned you to this problem :P

**Comment by mmun** [comment]
Just checked and this is still broken. Chains and bindings still support globals.

**Comment by stefanpenner** [comment]
@mmun we must kill this for 2.0

**Comment by rwjblue** [comment]
Still broken on canary (will become 2.1.0 in 7 weeks): http://rwjblue.jsbin.com/kapoca/edit?html,js,output

**Comment by rwjblue** [comment]
Working properly now: http://rwjblue.jsbin.com/wemaxi/edit?html,js,output
