### ISSUE TITLE
mergedProperties needs documentation

### ISSUE THREAD

**Issue by cowboy** [emberjs/ember.js#10415]
I've been searching for `mergedProperties` documentation with little luck.

Typing `concatenatedProperties` into the emberjs.com search box gives me 10 API hits.
Typing `mergedProperties` gives me none.

I'm not sure #4844 made much of a difference!

**Comment by rwjblue** [comment]
@mixonic did a ton of work on this in https://github.com/emberjs/ember.js/pull/4851, but had to close due to timing and rebase issues.  

Anyone care to handle the rebase for us so we can get this documented?

**Comment by rwjblue** [comment]
@knownasilya - You commented on #4844, maybe you have time?

**Comment by knownasilya** [comment]
I'll have a look later today.

**Comment by mollerhoj** [comment]
@knownasilya Did the rebase, I hope that's alright with you :-)

I liked the documentation provided by @mixonic, I didn't know about mergedProperties, and the feature was crystal clear to me after reading this :-)
