### ISSUE TITLE
Helper Test Regression -- Cannot call `compile` without the template compiler loaded.

### ISSUE THREAD

**Issue by SlexAxton** [emberjs/ember.js#10419]
Our helper tests started failing, but it seems like the same failure is occurring the the Ember docs:

http://emberjs.com/guides/testing/test-helpers/#toc_example

I don't have a lot of insight as to why yet.

**Comment by michelle** [comment]
More specifically, this is for our tests that use this method of testing nested components: http://emberjs.com/guides/testing/testing-components/#toc_components-using-other-components

**Comment by rwjblue** [comment]
As mentioned in the blog posts (and the error message), if you need to compile at runtime you will have to load `ember-template-compiler.js`.

Assuming ember-cli and that you only need/want this for testing the following would work:

```javascript
// Brocfile.js

if (app.env !== 'production') {
  app.import('bower_components/ember/ember-template-compiler.js');
}
```

Posts:

http://emberjs.com/blog/2015/02/05/compiling-templates-in-1-10-0.html
http://emberjs.com/blog/2015/02/07/ember-1-10-0-released.html

**Comment by SlexAxton** [comment]
Ah, this ticket probably still serves as a good documentation ticket since there are tests actively failing in the site's example code for tests.

**Comment by rwjblue** [comment]
@SlexAxton - Great point! Looks like @fivetanley just opened https://github.com/emberjs/website/issues/1998 to track that one!
