### ISSUE TITLE
Cannot render into an outlet in the application template

### ISSUE THREAD

**Issue by markprzepiora** [emberjs/ember.js#10427]
This is a regression from stable (currently broken in beta and canary).

See this JSBin: http://jsbin.com/behev/2/edit?html,js,output

Very simple application. Templates:

```handlebars
{{!-- application --}}
<p>This is the application template. Below is an outlet.</p>
{{outlet "foo"}}

{{!-- foo --}}
<p>I am in the foo outlet!</p>
```

And route:

```javascript
App.ApplicationRoute = Ember.Route.extend({
  renderTemplate: function() {
    this._super.apply(this, arguments);
    this.render('foo', {
      into: 'application',
      outlet: 'foo'
    });
  }
})
```

The error occurs on this line:

```javascript
    if (into && into === parentRoute(route).routeName) {
      into = undefined;
    }
```

Since `route` is the application route, `parentRoute(route)` is undefined, causing the error.

**Comment by rwjblue** [comment]
The referenced line is from: [ember-routing/lib/system/route.js](https://github.com/emberjs/ember.js/blob/b186e6e3fa000f1960c8837530dff7416a1e7e0a/packages/ember-routing/lib/system/route.js#L1969-L1971).  Basically, when rendering into an outlet in the `application` route, there are is no parent route and we are calling `routeName` on `undefined`.

@ef4 - Should we just guard against this (`parentRoute(route)` being `undefined`), or is there a better solution?

**Comment by rwjblue** [comment]
Closing in favor of https://github.com/emberjs/ember.js/issues/10416 (same issue).
