### ISSUE TITLE
ember 1.10, precompile, render function problems

### ISSUE THREAD

**Issue by devlo** [emberjs/ember.js#10422]
I have updated to ember 1.10 and htmlbars. I was using ember 1.7 and handlebars before and everything worked fine. I am compiling templates using grunt-ember-templates 0.5. In my index template i have 3 different renders: {{render 'templateName'}} 

From ember inspector:

Transitioned into 'index'
ember.prod.js:47968 Transition #0: TRANSITION COMPLETE.
ember.prod.js:42627 Uncaught TypeError: object is not a function

From what i see it's error inside render function, here:

 `if (useHTMLBars) {
                        var env = Ember.merge(buildHTMLBarsDefaultEnv(), options);
            output = template.render(this, env, buffer.innerContextualElement(), this._blockArguments);
          } else {
                        output = template(context, options);
          }`

Exactly this line: output = template(context, options);
Which is weird because i am using htmlbars.

This is compiled index template (i have changed html into 'some html' so it will be more readable):

`Ember.TEMPLATES["index"] = Ember.HTMLBars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  var helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression, buffer = '';
  data.buffer.push("some html");
  data.buffer.push(escapeExpression(((helpers.render || (depth0 && depth0.render) || helperMissing).call(depth0, "chart", {"name":"render","hash":{},"hashTypes":{},"hashContexts":{},"types":["ID"],"contexts":[depth0],"data":data}))));
  data.buffer.push("some html");
  data.buffer.push(escapeExpression(((helpers.render || (depth0 && depth0.render) || helperMissing).call(depth0, "trans", {"name":"render","hash":{},"hashTypes":{},"hashContexts":{},"types":["ID"],"contexts":[depth0],"data":data}))));
  data.buffer.push("some html");
  data.buffer.push(escapeExpression(((helpers.render || (depth0 && depth0.render) || helperMissing).call(depth0, "addr", {"name":"render","hash":{},"hashTypes":{},"hashContexts":{},"types":["ID"],"contexts":[depth0],"data":data}))));
  data.buffer.push("\n</div>\n</div>\n</div>\n");
  return buffer;
},"useData":true});`

**Comment by rwjblue** [comment]
These templates are not HTMLBars templates, you need to configure grunt-ember-templates with the path to the template compiler.

**Comment by devlo** [comment]
You mean adding this? :
`templateCompilerPath:"/ember-template-compiler.js"`

ember-template-compiler.js is from starter kit /js folder

**Comment by rwjblue** [comment]
Something like the following:

```javascript
emberTemplates: {
  options: {
    templateCompilerPath: 'bower_components/ember/ember-template-compiler.js',
    handlebarsPath: 'bower_components/handlebars/handlebars.js'
  },
  files: {
    'tmp/templates.js': 'app/templates/**/*.hbs'
  }
}
```

**Comment by rwjblue** [comment]
References:

* http://emberjs.com/blog/2015/02/05/compiling-templates-in-1-10-0.html
* http://emberjs.com/blog/2015/02/07/ember-1-10-0-released.html

**Comment by devlo** [comment]
@rwjblue 
Thank you!
Following what you wrote i found what was wrong.. 

"IMPORTANT: These options must both be specified, or neither will take effect."

I only used templateCompilerPath but not handlebarsPath that's why it didn't work.
