### ISSUE TITLE
Clarify difference between binding and Ember.computed.alias()

### ISSUE THREAD

**Issue by aexmachina** [emberjs/ember.js#10429]
I've noticed some differences between binding and Ember.computed.alias(), but I can't seem to find any information about this. Can we clarify this, and maybe add it to the docs?

**Comment by mmun** [comment]
Aliases _synchronously_ link two different properties on a single object.

For example, `fooAlias: Em.computed.alias('foo')`. Any get/sets/watch/unwatch/addObserver/etc applied to `fooAlias` should be redirected and applied to `foo`. It should act as if they are the same key.

Bindings _asynchronously_ link two different properties on a single object. Moreover, bindings actually change the property on both sides of the binding (in contrast to aliases, which proxy).

When a property is declared to be a binding, the Object model will know to add two observers to each side of the binding (or one observer in the case of one way bindings) and schedule a synchronization of the values if either side changes. Specifically, when either side changes a synchronization of the binding is scheduled into the `sync` queue. In fact, this is this _only_ use of the sync queue.

What does this buy us? Well, Backburner / the run loop is configured to disable observer notifications during the sync queue and coalesce them into one observer notification. So it has the effect of "absorbing churn" if properties on both sides of the binding change many times before the `sync` queue is reached.

Another feature of bindings is that they break ties when both sides of the binding change. Consider this template

```hbs
{{my-component foo=bar}}
```

Imagine the component has a button which when clicked changes its internal `foo` property. Imagine that the component then immediately sends an action which is caught by a controller, causing this controller to change the property of `bar`. Assume this all happens before the `sync` queue is reached. Both sides of the binding changed - who wins? Bindings introduce determinism: "Down" always wins. In this case, the controller that set `bar` wins.

## But...

Please don't use bindings, especially two-way bindings if it can be avoided. I'd really really like to remove them entirely.

I also recommend against using aliases in favour of just writing out the full dependency key. Yes, it's more verbose but it makes your code much more `grep`able.

(While I'm at it, don't use `needs` either. Prefer explicitly passing data via `setupController` or use services).

**Comment by aexmachina** [comment]
That's a great response. Thanks very much! That's going in the bookmarks for the next I'm confused by this :)

**Comment by mmun** [comment]
Please feel free to ping me on IRC or twitter.

**Comment by aexmachina** [comment]
Awesome, thanks. No it's okay, that's all I need.

Funnily enough we just hit a subtle new bug that was fixed by changing from a Binding to an alias. Must be a result of something in another part of the codebase changing from a Binding to an alias.

**Comment by s12chung** [comment]
@mmun i'm wondering what your thoughts are on this? 
https://stackoverflow.com/questions/46108346/pass-computed-property-like-binding-to-ember-object-create
