### ISSUE TITLE
Properties on view and render helpers do not resolve

### ISSUE THREAD

**Issue by paullryan** [emberjs/ember.js#10426]
It appears this has been in the system for quite some time (saw a similar behavior in 1.1) that hash items/properties added to a render or view helper are not resolved prior to being passed unless they are directly set on the helper.

** The following is accessible in sometemplate as view.direct"
``` handlebars
{{render "sometemplate" content direct="direct content"}}
```

** The following is not accessible in sometemplate as view.parsed"
``` handlebars
{{render "sometemplate" content parsed=controller.someControllerValue}}
```
Full example using 1.9: http://jsbin.com/juqaji/3/edit

related to #10401

**Comment by stefanpenner** [comment]
this isn't supported, and render will be deprecated in 2.0. If you want this behavior please use a component.
