### ISSUE TITLE
Access controller in view in Ember 1.10.0

### ISSUE THREAD

**Issue by jcbvm** [emberjs/ember.js#10420]
Currently I'm facing the problem that my controller property in my views is undefined. In previous versions this property was automatically set to the corresponding controller. Is this behaviour changed in Ember 1.10.0? I could not find anything about it in the changelog. 

If not maybe something else is going wrong in my app. So I'd like to know before I start debugging.

**Comment by jcbvm** [comment]
Found the problem, in my view there was a reference to `this.controller` instead of `this.get('controller')`, seems like internal has moved from `controller` to `_controller`.

**Comment by btecu** [comment]
Ember is a framework that's currently undergoing some significant changes. For the most part they are really easy to take care of, from a version transition point of view.

It really helps to be more aware of plans and changes (follow relevant people on twitter, read blog posts, etc.). Probably starting on reading Ember 2.0 RFC would be the best.

It has been mentioned many times that controllers are going away and components are taking over. Actually 1.10 deprecates **ObjectController**. Also, you should not use views either.

**Comment by jcbvm** [comment]
I know the plans and the transition to components, I'm slowly transitioning to that way, but with a very large app this will take some time. I did not see any mention about the controller property change for version 1.10.0, but I was wrongly using `this.controller`. Will close this issue now, because I solved it. Thanks for the response.
