### ISSUE TITLE
Can't we get `@each` to support deep properties?

### ISSUE THREAD

**Issue by aexmachina** [emberjs/ember.js#10430]
Having a property dependency on `foo.@each.bar.quz`, doesn't work. You need to define `barQuzBinding: 'bar.quz'`. Can we can get `@each` to handle this transparently? Or at least throw an exception if a deep property is used.

**Comment by mixonic** [comment]
@aexmachina I think an exception or assert would be best. Deep chaining of observers can perform poorly. We're building Ember 2.0 around the idea that you won't need deep observation in new codebases.

**Comment by mmun** [comment]
Our goal is to flesh out the diffing story so that you never need to use `@each` again, let alone nested `@each`!

**Comment by aexmachina** [comment]
Awesome, that sounds great. But I think right now it should throw an
exception so people know that it's not supported.​

**Comment by mmun** [comment]
Agreed.

**Comment by archaeron** [comment]
yes please :+1:

**Comment by wagenet** [comment]
I remember trying to get an assertion in for this a long time ago. It was a huge pain in the butt then and I gave up. I'm not sure if it will have gotten any easier.

**Comment by endash** [comment]
If difficult to impossible to get an assert in-line, maybe a grep-based warning on build would suffice?

**Comment by stefanpenner** [comment]
should throw an exception if it isn't supported, as to not confuse users

**Comment by rwjblue** [comment]
Was talking to @krisselden about this the other day.  The recent refactor (for 2.0.0) for `@each` will unlock the ability to support `foo.@each.bar.baz`.

**Comment by rwjblue** [comment]
Helpful warning added in https://github.com/emberjs/ember.js/pull/12847.
