### ISSUE TITLE
For ember-canary (1.12.0-beta.1+canary.50206d0f) object proxy does not work

### ISSUE THREAD

**Issue by gonvaled** [emberjs/ember.js#10434]
Object proxy is supposed to be deprecated, but still working. For me it is not working anymore (at least in partials?) Details here: http://stackoverflow.com/q/28466018/647991

**Comment by rwjblue** [comment]
Seems to be working properly here: http://emberjs.jsbin.com/rwjblue/300/edit?html,js,output.

Can you provide a reproduction showing what you describe?

**Comment by gonvaled** [comment]
Here: http://emberjs.jsbin.com/takahe/1/

Seems to happen only when a controller is manually defined. I have added also a partial. Initially I thought it was related to partials, but it is not: just by extending a controller the problem appears.

**Comment by rwjblue** [comment]
You have the following: `App.ApplicationController = Ember.Controller.extend();` which means you are specifically saying you do **not** want an `Ember.ObjectController`.  If you want to use an object controller with a manually defined controller, you must extend from it (this is no different in all past versions).

http://jsbin.com/xafone/1/edit

**Comment by gonvaled** [comment]
One of the refactorings that I have performed while moving to canary (because of deprecation warnings), is that ObjectController must be changed to Controller. It is not clear (at least in the documentation / deprecation warnings) that by doing that we are also losing the property proxying.

**Comment by rwjblue** [comment]
@gonvaled - The only reason to use `Ember.ObjectController` is for the property proxying (that is its job). The deprecation warning that you received and started honoring instructs you to use `model.somePropertyName` and extend from `Ember.Controller` instead of `Ember.ObjectController`.

We definitely need more details about this in the deprecation guide (there is an open issue for that).

**Comment by gonvaled** [comment]
@rwjblue - fair enough. I probably oversaw the `model.somePropertyName` comment, and just did ObjecController -> Controller all over my code, to get rid of the obvious warnings which appear just by instantiating some controllers (probably related to `needs`) Since I have not tested all templates while doing that refactoring (most where anyway not working during the transition to canary - I have unfortunately no automatic testing) I did not realize that I was losing properties. I guess this could bite more people, so a more clear warning on the transition guide would help.
