### ISSUE TITLE
Why Ember community is actively repelling newbies?

### ISSUE THREAD

**Issue by Octagon** [emberjs/ember.js#10432]
After removing the Handelbars dependency, some builds could run without Ember CLI and some cannot producing the "Cannot call 'compile' without the template compiler loaded." error. There are several threads dedicated to the issue. Amazingly, nobody asked why the link to the compiler is missing where it should be: in http://emberjs.com/builds/#/beta and in http://emberjs.com/builds/#/release, everybody considered the recommended work around of guessing the correct download URL to be OK. It is not OK, it is the policy of actively repelling newbies. I wonder what is it necessary for?

**Comment by jgwhite** [comment]
Hi @Octagon 

You raise a very good point. There absolutely should be a link the new compiler on the builds page.

Ember is run entirely by good people volunteering their free time to the project. Chances are, the team hasn’t had a chance to add the link to the builds page yet :)

If you’re interested, this is a great opportunity to contribute. The builds page is itself an Ember app and the source is [here](https://github.com/emberjs/website/tree/master/source/javascripts/app/builds). I’m sure everyone would greatly welcome a pull request adding the link.

If you’d like to pair on it, let me know and I’d be happy to work through it with you :smiley:

**Comment by mixonic** [comment]
I'm going to fold this into the website with https://github.com/emberjs/website/issues/1998. @Octagon we work very hard at building a welcoming, civil community and a framework that is reliable and steady. Thanks for raising the website issue.
