### ISSUE TITLE
Ember.subscribe breaks backwards compatibility in 1.11.0

### ISSUE THREAD

**Issue by jgwhite** [emberjs/ember.js#10435]
According to the docs `Ember.subscribe` is part of the instrumentation API:

http://emberjs.com/api/classes/Ember.Instrumentation.html

However, in 1.11.0-beta.1 it appears to be part of ember-metal/streams.

I believe ember-inspector [depends upon `Ember.subscribe`](https://github.com/emberjs/ember-inspector/blob/f001daa050b259e9e82f6428051cf696a6c57fd7/ember_debug/render-debug.js#L38).

Will the instrumentation method be exposed in a different manner?

**Comment by rwjblue** [comment]
Ugh.  This is most likely due to the new transpiler being sane.  Good catch!

**Comment by jgwhite** [comment]
Closed by #10436
