### ISSUE TITLE
Meta: Upgrade retrospective from 1.8.1-beta to 1.11-canary

### ISSUE THREAD

**Issue by tim-evans** [emberjs/ember.js#10446]
# Note: still working on this; will review and provide fleshed out notes tomorrow

### Ember upgrade retrospective

Started on 1.8.1-beta. Couldn’t upgrade to 1.8.1 because Ember.Set API changed and the view layer changes didn’t support access to low-level helper functions.

I tried upgrading to 1.10-beta.3 and ember-data 1.0.0-beta.14, but had to downgrade to 1.9.1 due to compilation errors that were very obtuse. The HTMLBars parser wasn’t giving good info on a closing div tag that had no corresponding opening tag. Found that and fixed it.

I was using origContext on components to punch through to controllers and routers. This was added, then removed, so I had to change it to get that fixed.

I changed all of our helpers to use HTMLBars style helpers because the old-style Handlebars helpers were missing meta data that I was using to punch through to controllers / routes (by following how internal helpers to Ember did this). One instance of this was options.data.keywords.controller that was used.

In addition, all calls to chain helpers (ie. View helpers) changed their API signature to be Handlebars.helpers.view.helperFunction.call instead of Handlebars.helpers.view.call.

We have Handlebars helpers that don’t include any dashes (which was possible), but now I’m afraid to bump to 1.12-canary because the function for bypassing the linting of helper / component names is no longer public.

I spent a good deal of time taking the upgrade as a good time to refactor parts of our application to use components more heavily.

I encountered bugs around the {{render}} helper, where rendering a template with a model caused unexpected side effects. I solved this by refactoring templates that used this pattern to be components.

Acceptance tests involving CSS selectors suddenly broke (for some reason, vague selectors in tests that made tests pass in 1.8.1 broke tests in 1.11). I don’t consider this a bad thing, because now tests are more accurate.

I had some trouble working around a helper that needs to observe properties on a model. I needed to unwrap the model from a promise, and observe on keys that were being used in the helper. It wasn’t painful, but it was unexpected, coming from ‘makeBoundHelper’ just working with this use case.

I had a bug with our drag and drop / list animation code that was looking at the content of childViews, expecting to be able to access `content.content`, which I had to change to `context.content`.

All in all, I had about 60 commits of changes that I had to make to get our test suite passing. This app is **large**. We have around 100 routes, and around 80 components.

**Comment by rwjblue** [comment]
Thanks for the writeup!

I am unsure what the goal here is. Is there an issue that we need to address or is this something of a recap for others on some of the pain points that you have had?

**Comment by tim-evans** [comment]
It's a recap at the request of @wycats and @stefanpenner

**Comment by rwjblue** [comment]
Gotcha, thanks!!  Definitely some things here that could have been easier...

**Comment by endash** [comment]
Ugh it's now impossible to manually register a hyphenless helper or component? :-(

**Comment by tim-evans** [comment]
@endash No. Read carefully- it's still there.

**Comment by endash** [comment]
Sorry I was a bit hyperbolic, but making it a private API is effectively the same thing if you intend to circulate the code beyond your own projects. Not to start a discussion here arguing the merits but I can think of several use cases off the top of my head that extend Ember at a low level, conceptually, and for which you'd want very short hyphenless names.

**Comment by endash** [comment]
Oh as long as you can do it for helpers. Rereading the distinction still isn't clear to me but I'm happy to get clarification :)

**Comment by mixonic** [comment]
@endash @tim-evans can you fill me in on:

> We have Handlebars helpers that don’t include any dashes (which was possible), but now I’m afraid to bump to 1.12-canary because the function for bypassing the linting of helper / component names is no longer public.

`Ember.Handlebars.registerHelper` still works as it always have. Is there an issue here? Maybe I don't understand what you were doing pre-1.12?

**Comment by tim-evans** [comment]
@mixonic https://github.com/emberjs/ember.js/pull/10379

**Comment by endash** [comment]
Ah damn and I'm right back to being bummed that regular helpers need dashes now. Hopefully that re-publicing of the API isn't too far off.

**Comment by tim-evans** [comment]
Hey @mixonic, could you limit contributors to this discussion? I don't want this to be a big political mudslinging thing. And I didn't even copy-edit my issue.

**Comment by endash** [comment]
Sorry for barging in, was just first I'd heard of it :/

**Comment by tim-evans** [comment]
@endash- you're fine. I just don't want this to blow up with the whole community putting their 2 cents in

**Comment by mixonic** [comment]
#10379 refers to `Ember.HTMLBars.registerHelper`. You can still register a non-dasherized helper via `Ember.Handlebars.registerHelper`:

* 1.9.1: http://emberjs.jsbin.com/jinecutoqo/1/edit?html,js,output
* 1.10: http://emberjs.jsbin.com/jinecutoqo/2/edit?html,js,output

This API is supported because we have a strong commitment to semver. Fwiw, the `Ember.HTMLBars.registerHelper` API was removed because of the same reason. We've been locked into a few limiting API decisions in the past, and by making this one internal we have the time to explore new options before 2.0.

I regret that there may have been some miscommunication (on my behalf, I wrote the release blog posts) about our continuing support for the APIs of `Ember.Handlebars`. I want to be clear that we worked very hard to ensure those APIs still work, in accordance with our commitment to API stability. The `HTMLBars` APIs were kept in flux so we can have the room to iterate on exciting ideas before 2.0.

@tim-evans I've closed the issue, and I won't pull you back if you want to dis-engage, totally understand it. Definitely not thinking of this as a political issue. I just want to to write some great software, and see others keep doing the same :-) Thanks for the notes!

**Comment by tim-evans** [comment]
@mixonic Much appreciated. :+1: I'd like this to be a nice set of notes that we can all improve on with subsequent releases. I'll get my notes fleshed out more fully- I'm fine engaging. Just want to be careful about how I'm reporting these issues.

**Comment by stefanpenner** [comment]
I look forward to the whole post mortem. Thanks @tim-evans, I think we can use it to fully understand were the pain was and how to avoid it going forward.

**Comment by tim-evans** [comment]
Ok! I think I've done enough on this. (cc @wycats)
