### ISSUE TITLE
Assert on templates with a mis-matched Ember / template-compiler

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#10447]
* Add some sort of `template.COMPILER_VERSION` flag (as the `Ember.VERSION` of the template compiler used).
* Compare `template.VERSION` against running `Ember.VERSION`, and assert if different

**Comment by rwjblue** [comment]
Submitted https://github.com/tildeio/htmlbars/pull/296 to add this info into the templates.

**Comment by Octagon** [comment]
Please reopen, the expected version is hardcoded in many places and as off beta 2 that hardcoded versions differ rendering beta unusable.

**Comment by rwjblue** [comment]
@octagon - This should be working properly with the latest ember-source (1.11.0-beta.2.2).
