### ISSUE TITLE
Ember.TextField cursor position lost when setting new value.

### ISSUE THREAD

**Issue by JordyLangen** [emberjs/ember.js#10449]
We found a bug when using the input helper with 1.11.0-beta.1 and HTMLbars.

Sadly, We can't get a jsbin to work.

You can reproduce this by creating a new ember project using the ember cli and replace this in bower.json:
`"ember": "1.11.0-beta.1",`
and edit your Brocfile:
`var app = new EmberApp({
    vendorFiles: {
        'handlebars.js': null
    }
});`

Now just add a `{{input type=text}}` to the application.hbs, type some text, put your cursor in the middle and type some more text.
The cursor will automaticly jump to the last character instead of staying in the middle.

**Comment by rwjblue** [comment]
JSBins reproducing the problem:

latest canary: http://emberjs.jsbin.com/rwjblue/303/edit
latest beta: http://emberjs.jsbin.com/rwjblue/306/edit

1.10 seems to work properly: http://emberjs.jsbin.com/rwjblue/307/edit

**Comment by JordyLangen** [comment]
Thanks for the quick reaction, managed to create a jsbin aswell.
http://emberjs.jsbin.com/hedavewili/1/edit

**Comment by JordyLangen** [comment]
Would love to try and fix this if you push me in right direction

**Comment by rwjblue** [comment]
Reproductions by @mixonic in #10481. 

Some demonstrations:

* [repro with canary](http://emberjs.jsbin.com/jolaboyiye/4/edit?html,js,output)
* [repro with beta](http://emberjs.jsbin.com/jolaboyiye/3/edit?html,js,output)
* [stable is fine](http://emberjs.jsbin.com/jolaboyiye/5/edit?html,js,output)

**Comment by toranb** [comment]
I realize @rwjblue has a custom component to workaround this but with Glimmer2 will this bug be fixed (or a non issue) ?

**Comment by rwjblue** [comment]
This bug (cursor position with Ember.TextField) is not an issue (to my knowledge) with any stable versions of Ember.

**Comment by kybishop** [comment]
@rwjblue the bug persists when the property is used as a query param: https://github.com/emberjs/ember.js/issues/13023
