### ISSUE TITLE
afterEach failed on it exists

### ISSUE THREAD

**Issue by givanse** [emberjs/ember.js#10459]
I'm trying out **v1.11.0-beta.1** with ember-cli and all my unit tests for the models are giving  me this error:

    afterEach failed on it exists: Cannot convert undefined or null to object

    TypeError: Cannot convert undefined or null to object
    at Object.keys (native)
    at ember$data$lib$system$record_array_manager$$values (http://localhost:4200/assets/vendor.js:68303:24)
    at Ember.Object.extend.willDestroy (http://localhost:4200/assets/vendor.js:68296:113)

Even for the test of this model `ember generate model foobar` The default/empty test.

The libraries:

    "ember-cli": "0.1.15",
    "ember-cli-qunit": "0.3.7",

    "ember": "1.11.0-beta.1",
    "ember-data": "1.0.0-beta.14.1",
    "ember-qunit": "0.2.8",
    "qunit": "~1.17.1",

After reverting to **1.10.0-beta.4** everything works (everything else remaining equal).

**Comment by fivetanley** [comment]
Yeah I think we need a new release of ember data to address canary/beta concerns. We'll be releasing a new version today. @igorT @bmac is this one of the issues that requires a new release?

**Comment by bmac** [comment]
Yes this should have been fixed by this pr which is already merged into canary. https://github.com/emberjs/data/pull/2691

**Comment by fivetanley** [comment]
Closing in favor of emberjs/data#2691. Look out for beta.15 later today!

**Comment by givanse** [comment]
Awesome, thanks!
