### ISSUE TITLE
Handling subdirectories in ember-htmlbars-component-generation

### ISSUE THREAD

**Issue by asakusuma** [emberjs/ember.js#10456]
If I have a handlebars component:
```
{{home/home-page}}
```
How do I express this with ember-htmlbars-component-generation? This does not work:
```
<home/home-page></home/home-page>
```

Edit: here is the error
```
Invalid end tag: closing tag must not have attributes, in `home` (on line 1).
Error: Invalid end tag: closing tag must not have attributes, in `home` (on line 1).
```

**Comment by sberan** [comment]
I did a brief tour of the component syntax, and didn't see any way of instantiating a nested component in a directory. My preference would be to use `<folder1:folder2:my-component>` to traverse directories.

**Comment by sberan** [comment]
relevant discussion: https://github.com/emberjs/rfcs/pull/10#discussion_r19474370

**Comment by ballPointPenguin** [comment]
A part-way solution might be to resolve the component location by checking the folder in which the template that uses it resides, and if not found there, falling back to /components.
e.g. if I have app/pages/navigation-bar/component.js & app/pages/navigation-bar/template.hbs,
then I could just use <navigation-bar /> with my app/pages/template.hbs.

**Comment by chadhietala** [comment]
@rwjblue A solution to this might be to just introduce the `is` attribute from the web components spec.  For example you could do.

```
<td is="my-component"></td> 
<!-- or -->
<div is="path/to/my-component"></div>
```

cc/ @wycats @tomdale

**Comment by rwjblue** [comment]
Yep. That was definitely one of the ideas being tossed around.

I believe that @ebryn is opposed to 'is' though (I could be mistaken)...

**Comment by mixonic** [comment]
This feature is not enabled in 1.13, we've removed this from the milestone.

**Comment by rwjblue** [comment]
Still need to determine how this will be handled in angle-bracket land.

@wycats - ping....

**Comment by rwjblue** [comment]
This feature was removed (so that work could continue on glimmer 2 engine).  When the new angle bracket component RFC is introduced, please raise this concern there....
