### ISSUE TITLE
EmberJS queryParams not RFC compliant

### ISSUE THREAD

**Issue by rmhrisk** [emberjs/ember.js#10453]
RFC (http://tools.ietf.org/html/rfc3986#section-4.1) says the appropriate format for url is query string then anchors, aka:

```
relative-ref  = relative-part [ "?" query ] [ "#" fragment ]
```

But it seems the queryParams in Ember wants it to be fragment then queryString. Is there a reason the opposite approach was taken?

**Comment by mmun** [comment]
The router doesn't support URLs with fragments in the proper sense. The hash you're seeing is used for backwards compatibility with older clients. See http://emberjs.com/api/classes/Ember.Location.html.

**Comment by rmhrisk** [comment]
So what does this mean for me? I don't need to support older clients, do I create non-compliant URLs or can I tell ember to handle this in a compliant way?

**Comment by mmun** [comment]
Use HistoryLocation. It's described in the docs and guides.

Namely, in your router include

```
App.Router.reopen({
  location: 'history'
});
```

**Comment by rmhrisk** [comment]
Yes, sorry makes sense now... thanks
