### ISSUE TITLE
Ember.js Guide Issues: Testing Live Examples broken

### ISSUE THREAD

**Issue by step2yeung** [emberjs/ember.js#10455]
Under the Ember.js Guide, under the Testing Category,
There are quite a few of the Live Example where the test are broken.
Examples:
In http://emberjs.com/guides/testing/testing-user-interaction/
     error: Setup failed on root lists first page of posts: Cannot call `compile` without the template compiler loaded. Please load `ember-template-compiler.js` prior to calling `compile`.

In http://emberjs.com/guides/testing/testing-components/
     error: Uncaught ReferenceError: emq is not defined

**Comment by step2yeung** [comment]
Found the reason for these:
1) None of the html code has script tag that links to ember-template-compiler.js
2) emberq-unit/main.js has some issues: "Refused to execute script from 'https://raw.githubusercontent.com/rwjblue/ember-qunit/v0.1.8/dist/globals/main.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled."

**Comment by amedrz** [comment]
I noticed those jsbins were removed on v1.11.0 guides, is this still relevant? @wagenet

**Comment by jimbeaudoin** [comment]
@step2yeung This issue does not belong here. There is a [guides repository](https://github.com/emberjs/guides) where you can post issues related to the guides.

It would be great if you could update or close this issue and reopen a new one if needed in the guide repos.

Thanks!
