### ISSUE TITLE
1.11.0-beta.1: Why are docs telling me to use "{{#each foo in bar}}" when it doesn't work?

### ISSUE THREAD

**Issue by QuantumKing** [emberjs/ember.js#10457]
For example, under [deprecations](http://emberjs.com/guides/deprecations/#toc_more-consistent-handlebars-scope). However, using `{{#each bar as |foo|}}` does the trick. I am using HTMLBars.

**Comment by rwjblue** [comment]
`{{#each foo in bar}}{{/each}}` definitely works properly in the latest 1.11 beta build: http://emberjs.jsbin.com/rwjblue/312/edit?html,js,output

Closing for now (as demonstrated above, it does work in latest beta builds), happy to reopen with a reproduction demonstrating the issue...

**Comment by QuantumKing** [comment]
Does it make a difference if I'm precompiling with `require('htmlbars').compileSpec`?

**Comment by rwjblue** [comment]
@QuantumKing - Yep, you can't do that. But the good news is that I wrote a blog just for you ;)

http://emberjs.com/blog/2015/02/05/compiling-templates-in-1-10-0.html

**Comment by QuantumKing** [comment]
@rwjblue Got it working, cheers!
