### ISSUE TITLE
Please provide a way to test in production mode

### ISSUE THREAD

**Issue by shama** [emberjs/ember.js#10452]
Previously with `ember@1.7` our build server would compile our app in production mode, run the tests and upon passing, release to a staging server.

After upgrading to `ember@1.9`, it appears that `Ember.Test` is removed from production builds now: `Uncaught TypeError: Cannot read property 'registerAsyncHelper' of undefined`

Ember in production mode should behave the same but unfortunately it doesn't. As in the past we've had tests failing in production mode but passing in development.

Without an option to test in production, we're unable to catch those differences before releasing. It also just doesn't feel right releasing code that is effectively untested.

Could we add testing back to production mode or provide another solution? Thanks!

**Comment by rwjblue** [comment]
You need to include `ember-testing.js` (generated along with the rest of the build assets) when running your tests.  This is precisely what ember-cli is doing when running `ember test`.

https://github.com/components/ember/blob/master/ember-testing.js

**Comment by shama** [comment]
Awesome, thanks a bunch!
