### ISSUE TITLE
Change latest release on GitHub releases page?

### ISSUE THREAD

**Issue by Kuzirashi** [emberjs/ember.js#10460]
Why not to change latest release to more recent one, stable or beta, instead of hiding two most recent ones and displaying `Ember 1.10.0-beta.4` as latest release. It might be confusing for someone that regulary check for new releases. https://github.com/emberjs/ember.js/releases

**Comment by rwjblue** [comment]
Ya, good point. I'll get it updated.

**Comment by rwjblue** [comment]
Updated, thanks for the reminder!
