### ISSUE TITLE
renderTemplate behavior changed?

### ISSUE THREAD

**Issue by nullrocket** [emberjs/ember.js#10478]
Prior to the latest canary 1.12.0-beta.1+canary.f5873415 you could render common outlets on a parent routes renderTemplate and they would persist, now it seems like only the first call to render works.

This is the behavior a couple days ago, not sure of exact day. (using v1.91 but behavior the same on canary up til then)
http://emberjs.jsbin.com/gixiva/2/edit

This is the behavior now.
http://jsbin.com/fuzome/edit

Notice the "common" template isn't rendered in the latest.

**Comment by fivetanley** [comment]
cc @ef4

**Comment by ef4** [comment]
Thanks for the bug report. It looks to me like it's triggered by having only non-default renders, and no "main" render.

Here's a variation on your example that works, just by using a non-named outlet at the top:

http://jsbin.com/wuzufefira/1/edit?html,css,js,output

I will investigate further.

**Comment by nullrocket** [comment]
Thanks, that does fix things for me, easy enough to change if having a default outlet is a requirement.   

I have had the same structure in our app for over a year so it may need to make it into documentation or the change log on beta somewhere, or..... maybe not, since I don't see anyone else saying they are borked.

**Comment by ef4** [comment]
I think it's still a bug, and should just get fixed instead of documented.

**Comment by Leeft** [comment]
> since I don't see anyone else saying they are borked. 

It affects my application as well. Adding the plain outlet fixes some but not all of the errors.

**Comment by nullrocket** [comment]
Another issue I think may be related.  Templates with the name "main" will not render. Hooks like didInsertElement run but the output is empty.  I am not sure if this is related, but it showed up at the same time as the other issue.

**Comment by Soliah** [comment]
> since I don't see anyone else saying they are borked

Happening to our application as well with 1.11.0-beta.3.
