### ISSUE TITLE
New optional index in each helper doesn't allow for an itemView

### ISSUE THREAD

**Issue by QuantumKing** [emberjs/ember.js#10476]
http://emberjs.jsbin.com/siguverusa/1/edit?html,js,output

**Comment by omghax** [comment]
It works if you put the options before the `as`:

```handlebars
{{#each this itemView='summary' as |letter index|}}
  ...
{{/each}}
```

**Comment by rwjblue** [comment]
@omghax's example is correct, the block param is always the last parameter (just before the closing `}}`).
