### ISSUE TITLE
template compilation error in 1.11.0.beta.2

### ISSUE THREAD

**Issue by ashrafmajdee** [emberjs/ember.js#10471]
when using ember-source gem 1.11.0.beta.2.1, in rails i get the following error:

Uncaught Error: Assertion Failed: The template being rendered by `<LinkView:ember373>` was compiled with `Ember@v1.11.0-beta.2` which does not match `Ember@1.11.0-beta.2` (this revision).

**Comment by Octagon** [comment]
There current version in compiler is Ember@1.11.0-beta.2 and Emer expects either Ember@v1.11.0-beta.2 or Ember@1.11.0-beta.2. Just replace Ember@v1.11.0-beta.2 with Ember@1.11.0-beta.2 in Ember code for now.

**Comment by rwjblue** [comment]
Sorry for the issues. Will fix it ASAP.

**Comment by rwjblue** [comment]
ember-source-1.11.0.beta.2.2 should fix it
