### ISSUE TITLE
Promises should more consistently/eagerly call asyncStart/End for testing

### ISSUE THREAD

**Issue by machty** [emberjs/ember.js#10484]
https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/ext/rsvp.js#L26

The above is how Ember extends RSVP to notify QUnit about async, but there is a subtle issue here:

The `async` config hook doesn't get called until it's time to invoke callbacks subscribed via `.then` and friends. If you resolve asynchronously within the `new RSVP.Promise` callback, the QUnit test suite will have already left the test before the `asyncStart` is called. This makes Ember's attempt to pause your test case until all RSVP promises have settled very flimsy.

It seems the solution would be to call `asyncStart` from within an RSVP promise's constructor, or at least the moment a callback is subscribed (via `.then` et al), but I'm not sure how easily this can be hooked into, and I also have doubts that even if we did entirely catch/wait for every RSVP promise that this wouldn't just lead to more confusion when someone uses a non RSVP promise lib, or another lib uses non RSVP as a dependency. 

Either way, I'd like to hear from @stefanpenner on this one, I might be missing something.

**Comment by lolmaus** [comment]
In my humble addon, @agebhar1 kindly added a test that launches `record.save()`. Assertions should be run after `.save()` promise is fulfilled.

I was expecting this to work:

```js
record.save();

andThen(function() {
  ok(...);
});
```

But it totally didn't. Assertion did not run and test failed to teardown.

@agebhar1 came up with this clever solution:

```js
test('foo', function() {
  stop();
  record
    .save()
    .then( function() {
      start();
      ok(...);
    });    
});

which i refactored into this:

```js
test('foo', function(assert) {
  var done = assert.async();
  record
    .save()
    .then( function() {
      assert.ok();
      done();
    });    
});

My questions are:

1) Is my expectation valid that `andThen()` should wait for `model.save()` to complete?
2) Is this issue ticket related?

**Comment by pixelhandler** [comment]
@machty I think this question needs to be revisited or closed, considering [Grand Testing Unification](https://github.com/emberjs/rfcs/pull/119) and that QUnit v2 Doesn't use `stop`/`start` anymore. The test adapter interface mapped start/stop to asyncStart and asyncEnd. @rwjblue has a rfc that recommends async/await.

**Comment by machty** [comment]
I'm just going to close this. TBH i don't even remember posting this issue and I haven't been bitten by it since, and with the grand unification RFC I think it's even less a thing that needs to be on anyone's radar.
