### ISSUE TITLE
Cursors jump to the end of an input when new value set

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#10481]
Some demonstrations:

* [repro with canary](http://emberjs.jsbin.com/jolaboyiye/4/edit?html,js,output)
* [repro with beta](http://emberjs.jsbin.com/jolaboyiye/3/edit?html,js,output)
* [stable is fine](http://emberjs.jsbin.com/jolaboyiye/5/edit?html,js,output)

**Comment by rwjblue** [comment]
Duplicate of #10449.
