### ISSUE TITLE
Ember 11.beta-2 generated ObjectController for missing controllers.

### ISSUE THREAD

**Issue by cah-briangantzler** [emberjs/ember.js#10488]
I am getting the following message

 Ember.ObjectController is deprecated, please use Ember.Controller and use `model.propertyName`.

Tracking this down I found that this is a controller that ember generated. I would think that ember should be creating Controllers for missing controllers and not ObjectControllers

**Comment by rwjblue** [comment]
@cah-briangantzler - If we did that, then any applications built previously relying on the default proxying behavior would be broken.  If you do not define the controller, we **must** create an `Ember.ObjectController` instance for you (due to SemVer requirements).  But that generated controller will warn you if you attempt to use the proxying behavior.

**Comment by cah-briangantzler** [comment]
K, makes sense. In the mean time, We will have to manually create the controllers in order to get rid of the deprecations to know we are good. Its no problem creating another file. I want to remove all deprecations to know Im ready, so that means creating controllers where I didn't have to before. Might want to add a note about that somewhere so others know they have to do that as well.

**Comment by rwjblue** [comment]
You do not have to create controllers, to prevent deprecations.  Just don't use properties that are not defined on your controller (which trigger the proxying behaviors deprecations).

**Comment by cah-briangantzler** [comment]
I was getting the following warning

DEPRECATION: Ember.ObjectController is deprecated, please use Ember.Controller and use `model.propertyName`.

which seems to indicate that an ObjectController was created, not that I was using a proxy on the ObjectController.

**Comment by totallymike** [comment]
This is currently (with Ember 1.11.1) triggering deprecation warnings for me as well.  The difficulty I encounter is doing this in a Route

```javascript
model() {
  const model = this.store.find(...);
  return Ember.RSVP.hash({
    model,
    someDerivativeRecords: model.then((blah) => {
      return this.store.find(somethingElseFrom(blah));
    })
  });
},
setupController(controller, promiseHash) {
  //...
  controller.set('aProperty', promiseHash.someDerivativeRecords);
}
```

The deprecation warning assumes I'm trying to use the proxy behavior, where I just want to set an attribute on the controller, and let the template render it.

The simple solution is to add a controller definition:

```javascript
import Ember from 'ember';

export default Ember.Controller.extend({});
```

but that seems like a bit of a bummer.

**Comment by totallymike** [comment]
Oddly enough, the automatically generated `ObjectController` doesn't trigger a deprecation warning that it's generating an `ObjectController`.  You only get warnings about accessing or setting properties on the generated controller, not that it's generating an ObjectController.

**Comment by rwjblue** [comment]
> but that seems like a bit of a bummer.

Yep, it is annoying. SemVer sucks sometimes. :stuck_out_tongue_winking_eye: 

You can add a file at `app/controllers/object.js` to be `export default Ember.Controller;`, and that would make Ember not generate object controllers.

**Comment by IanVS** [comment]
So, I'm just beginning with Ember, but I understand that controllers will be removed entirely in 2.0, correct?  I am getting these deprecation errors and I want to do things the "Ember 2.0 way", so am trying to avoid creating controllers.  If I'm creating a new app today, is adding `app/controllers/object.js` as mentioned above a good way to prepare?

**Comment by jdhines** [comment]
Not sure where else I could post this, but I'm getting this error too, even when I remove the outlet from the application template and created an application controller as `Ember.Controller`

Could an add-on or package be causing this deprecation warning?
