### ISSUE TITLE
Wrapping {{#unless}} around {{yield}} does not pass through Controller properties

### ISSUE THREAD

**Issue by alvincrespo** [emberjs/ember.js#10497]
When we wrap an `{{#unless}}` around the `{{yield}}` helper, we seem to be losing the context since no controller properties are being passed through to the rendered template.

```
    {{#unless amIDone}}
      {{yield}}
    {{/unless}}
```

JSBin: http://emberjs.jsbin.com/cefahe

**Comment by ebryn** [comment]
This looks like a duplicate of https://github.com/emberjs/ember.js/issues/10402. Has been fixed in canary, beta, and there will be a 1.10.1 release with this fix.

**Comment by alvincrespo** [comment]
@ebryn Thanks for your work on this!
