### ISSUE TITLE
Throw a better error went passing a namespaced path to the view helper

### ISSUE THREAD

**Issue by jasonmit** [emberjs/ember.js#10496]
Currently it throw:
`Uncaught Error: Assertion Failed: foo@view:bar must be a subclass or an instance of Ember.View, not `

It would be helpful if we could detect the presence of a namespace and throw an error with:
`You passed a namespace into the view helper with the factory type, what you likely meant is {{view 'foo@bar'}}`

/cc @stefanpenner 

I'll send a PR tonight, feel free to modify my proposed error message.  I am guessing, we should only check & throw this in non-production env.

**Comment by stefanpenner** [comment]
> It would be helpful if we could detect the presence of a namespace and throw an error with:
> You passed a namespace into the view helper with the factory type, what you likely meant is {{view 'foo@bar'}}

this reads good to me.

**Comment by jasonmit** [comment]
@stefanpenner thinking about this a little more, would you agree this assertion is better suited for the ember-cli ember-resolver instead of the view helper?

**Comment by stefanpenner** [comment]
@jasonmit i can be convinced.

**Comment by stefanpenner** [comment]
seems to have gone stale
