### ISSUE TITLE
[HTMLBars] Subexpressions are not allowed as first argument in attribute bindings

### ISSUE THREAD

**Issue by iStefo** [emberjs/ember.js#10491]
I think it should be possible to use helpers as subexpressions when binding an attribute (`disabled` in this case), instead of throwing an exception:

```
Parse error on line 2:
...e="text" disabled={{(not value)}} />  
-----------------------^
Expecting 'STRING', 'NUMBER', 'ID', 'DATA', got 'OPEN_SEXPR'
```

Demonstration: http://emberjs.jsbin.com/muzevufiwi/1/edit?html,js,console,output
Tested with Ember 11.0-beta2

Using them inside the old `bind-attr` works:

```hbs
{{bind-attr disabled=(not newEmailAddress.length)}}
```

**Comment by zeppelin** [comment]
Subexpressions are just syntax for allowing calling helpers inside Handlebars expressions like helper params, which means if you leave out the parens they work just fine: `{{not value}}`

Subexpressions only required for cases like this: `{{not (not value)}}`
(I know the example is kinda silly) :)

Correct me if I'm wrong, though...

**Comment by zeppelin** [comment]
Also, even if what you're suggesting is a valid use-case, the issue most likely belongs to the Handlebars repo

**Comment by iStefo** [comment]
You are right, I am stupid. Calling `not` without the parentheses totally works.

**Comment by zeppelin** [comment]
@iStefo maybe me too, because the more I think about it, I'm getting convinced that the compiler should just ignore the parens instead of throwing an error :)
