### ISSUE TITLE
Text input behavior on android browser after upgrade to 1.11.0-beta.2

### ISSUE THREAD

**Issue by joshfester** [emberjs/ember.js#10508]
After upgrading from 1.10 to the 1.11 beta 2, all text inputs (with bound values) become impossible to use on my Galaxy S5. I'm not sure if this is an Android issue or if it's specific to my phone. As I type, characters get repeated, order gets jumbled, and the cursor jumps around. I tried both the Swype keyboard and the Samsung one. After going back to 1.10, the problem disappears.

**Comment by rwjblue** [comment]
Closing this in favor of https://github.com/emberjs/ember.js/issues/10449.  Please keep an eye over there for progress.
