### ISSUE TITLE
[BUG routing] Transition to changed query params

### ISSUE THREAD

**Issue by vinilios** [emberjs/ember.js#10504]
trying to transition to an updated query params state using `transitionTo` route method within the beforeModel hook, the transition promise seem to get rejected due to a kind of invalid state of handlerInfo objects. I'm not sure if its a bug or something that happens intentionally.

jsbin:
http://emberjs.jsbin.com/qojuve/1/edit?html,css,js,output

**Comment by locks** [comment]
The JSBin doesn't accurately reproduce the bug that you mention.

**Comment by vinilios** [comment]
@locks i checked on both chrome/firefox. The transition promise always gets rejected and additionally no url params are set on the window location.

**Comment by machty** [comment]
This bug looks legit; I'll keep it around but it'll probably disappear in the midst of upcoming query params refactorings.

**Comment by machty** [comment]
wrong button

**Comment by kmiyashiro** [comment]
I think this is a dupe of #12169, which has more detail now.

**Comment by mmun** [comment]
Closing as a dupe. Thanks @kmiyashiro.
