### ISSUE TITLE
routeName is undefined during init

### ISSUE THREAD

**Issue by martinthogersen** [emberjs/ember.js#10506]
I can see that routeName is assigned after init has been run:
https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/router.js#L443

Is it possible to change, so that we have routeName available in the init method?

```
export default Ember.Route.extend({
  init: function() {
    console.log(this.routeName); // => undefined
    var self = this;
    setTimeout(function() {
      console.log(self.routeName); // => correct value
    }, 1);
  }
})
```

**Comment by mixonic** [comment]
@martinthogersen not possible today without breaking dependency injections.

There must be an appropriate hook for your case. `activate`, `willTransition`, etc. In general I always aim to keep my routes fairly stateless.

**Comment by martinthogersen** [comment]
@mixonic Perhaps I'm being too creative.

I'm creating a listview, and I want to write as little code as possible, in order to create a sortable template with query-params. I've built a Mixin that takes care of everything (including the template). Ember needs a controller with queryParams to make that work, but I don't want to add that controller for all my routes, if I don't have to.

All I have to do, is to write this:

```
import MixinListRoute from '../../mixins/mixin-list-route';

export default Ember.Route.extend(MixinListRoute, {
  routeName: 'tourCategories.index', // this is needed because it's not available during init
  
  model: function() {
    return this.store.find('tourCategory');
  }
});
```

I've figured out, that I need to create the controller during init (if it's not defined by the user), in order to make queryParams work properly.

Is there a better way to do this?

```
export default Ember.Mixin.create({
  init: function() {
    var fullName = 'controller:' + this.routeName;
    var currentController = this.container.lookup(fullName);
    if (!currentController) {
      var f = this.container.lookupFactory('controller:basic').extend({
        isGenerated: true,
        queryParams: Ember.keys(this.get('queryParams')),
        toString: function() {
          return "(generated " + this.routeName + " controller)";
        }
      });

      f.reopen(MixinList);

      this.container._registry.register(fullName, f);
    }
  }

  // [ ... ]
});
```

**Comment by mixonic** [comment]
@martinthogersen Is this maybe a question better suited for the list-view issues? I'm still pretty confused as to what you are trying to achieve.

My only immediate thought is that you may be missing a call to `_super()` in a mixin's `init` method.

**Comment by martinthogersen** [comment]
@mixonic The question is related to auto generating a controller. I don't use the list-views project for this.
I need to autogenerate a controller, and set the queryParams for that controller.

The only way I've made that work, is by doing what I've posted in the issue above.
It looks like, that queryParams is initialized very early, and doesnt allow updating after the controller has been created. So I have to create the controller (with the queryParams setting) during the Route init method.

Regarding the missing _super(), you're right. I've added that.

**Comment by rwjblue** [comment]
@martinthogersen - Ember looks up `controller:basic`, `controller:object`, and `controller:array` when generating the controller to be used.  You can tweak those default controllers in your project if you like (assuming ember-cli) by adding controllers defined at these locations:

`app/controllers/basic.js`
`app/controllers/array.js`
`app/controllers/object.js`

**Comment by martinthogersen** [comment]
@rwjblue Thanks - that may help. I'll have a look later.

In order to achive my goal, I want to either:
a) Generate a controller, if it's not defined.
or
b) Modify queryParams after the controller is initialized. That isnt possible, right?

**Comment by rwjblue** [comment]
You can generate a controller as I mentioned in https://github.com/emberjs/ember.js/issues/10506#issuecomment-84213652. I don't think this is something we can change trivially, and I'm also not convinced it is a "bug" in the truest sense.

Closing for now (seems to have a resolution mentioned above), but I'm happy to reopen if needed.
