### ISSUE TITLE
No route in the address bar

### ISSUE THREAD

**Issue by Mak-Di** [emberjs/ember.js#10515]
Ember: v1.11.0-beta.1

Reproduction steps:

1. Generate new route
2. Add link-to helper with generated route to app/templates/application.hbs
3. Click on the link
4. Click to go back
5. Click again on the link

**Comment by lolmaus** [comment]
Works for me: http://emberjs.jsbin.com/cotoku

Can you reproduce it on JSBin?

**Comment by Mak-Di** [comment]
No, I can't.
I use ember-cli instead of Ember Starter Kit. You can check it on http://emberjs-199963.euw1.nitrousbox.com:4200/

Source code is here https://github.com/Mak-Di/someapp/commits/master

**Comment by lolmaus** [comment]
The repo is very helpful. Thx, comrade.

I see the behavior described in top post, yet there are no errors in the console.

This looks like a legit bug to me.

Here's the log: https://gist.github.com/lolmaus/bb0480d55b92023292c1

**Comment by wagenet** [comment]
@Mak-Di you gave a pretty specific example of how you can trigger this issue in an app. In general, it's very helpful if you put together a simple app in JSBin that reproduces the problem. The expectation is not for you to put your entire app into JSBin.

**Comment by wagenet** [comment]
To be clear, it's not normally realistic for us to jump through all of your code to track down bugs. Having a simplified reproduction in JSBin is pretty essential for prompt resolution of issues.

**Comment by lolmaus** [comment]
@wagenet, it's not reproducible on JSBin. But @Mak-Di has prepared a simplified reproduction in an ember-cli project. It's reduced to one route and one template.

**Comment by stefanpenner** [comment]
without a reproduction this is not actionable
