### ISSUE TITLE
Resolver creates multiple instances of controllers

### ISSUE THREAD

**Issue by xcambar** [emberjs/ember.js#10511]
The following [JSBin](http://emberjs.jsbin.com/fipafe/3/) explains it all, but as a quick recap:

* In our app, some controllers (and objects in general) have long names, _eg_ `DocumentPermissionController`
* When `needs`'ing one of these controllers, whether we use a dasherized name (`needs: ["document-permission"]`) or an underscored name (`needs: ["document_permission"]`) returns different instances of the controllers.
* The same behaviour is visible with `Ember.Route#controllerFor`, except it accepts the dotted notation.

Reading the code implies that the standard way to do it is with the underscore notation.

But shouldn't the resolver resolve to the same object no matter the notation? Or deprecate / warn / throw as the team would see fit depending on the notation?

**Comment by workmanw** [comment]
I think the resolver works fine. It resolves the same `DocumentPermissonController` factory. The problem here is that the container has no knowledge of the rules the specific resolver is using (ES6). The container uses string comparison to determine if it has a factory and/or instance is cached. 

In the case of the ES6 resolver, the dashized and underscore values resolve the same. But you could imagine a more exotic resolver where they were actually different files. So I think this ultimately a consequence that comes from the flexibility of the design.

I would say your best bet is to use constant [camel-case] naming across you app.

**Comment by xcambar** [comment]
We already use a consistent naming, and it is, as you suggested, camel case.

The issue we faced is that we had the `DocumentPermissionController` setup in the `DocumentPermissionRoute`, using `setupController`, therefore automatically resolved by Ember and provided as the first parameter.
And in another controller, we also needed the `DocumentPermissionController`, which was provided to the controller by `needs: ["document-permission"]`.

Instead of ending with the same instance of `DocumentPermissionController` at every place, we had 2 different instances.

I could build another JSBin for that. I just thought the former summed it up.

**Comment by lukemelia** [comment]
Hyphenated naming will be standard with Ember 2.x's module approach. In standard Ember 1.x, the DefaultResolver's `normalize` method ideally address the problem you're describing. A failing unit test against that would be a good way to test-drive a fix.

**Comment by workmanw** [comment]
Sorry, perhaps I misunderstood. Is there a reason you aren't using: `needs['documentPermission']` on your other controller?

**Comment by xcambar** [comment]
@workmanw There's no reason. Or maybe the reason is me failing to find guidelines on the `needs` syntax for "double worded" controllers. Or me making things overly complicated against my own will :unamused: 

Here's another JSBin that more precisely reproduces the experienced behaviour. Hopefully code will tell better than I do: http://jsbin.com/sanume/1/

@lukemelia I wanted to know whether the behaviour was expected or not before adding tests. I will work on a relevant test.

**Comment by lukemelia** [comment]
@xcambar definitely a bug.

**Comment by xcambar** [comment]
Hope you'll like it: https://github.com/emberjs/ember.js/pull/10513

**Comment by wagenet** [comment]
Nitpick, dasherized (foo-bar) is not the same as camelcased (FooBar). Anyway, dasherizing is probably the best default practice.

**Comment by wagenet** [comment]
Correction, I should say dasherizing is the best default for ember-cli apps, which will be the standard going forwards. Also, I suspect the use of `needs` will be going away. Nevertheless, we should see if we can improve this.

**Comment by wagenet** [comment]
After talking with the core team, it sounds like this isn't something that we can't improve in every case. Given that we'll be removing globals support Ember 2.0, I'm going to close this.
