### ISSUE TITLE
Observer triggers on unchanged property

### ISSUE THREAD

**Issue by phlppn** [emberjs/ember.js#10510]
Hello,

if i have a property like:

    someProperty: function() {
      return "always the same value";
    }.property("someValueA", "someValueB")

and an observer for this property:

    someObserver: function() {
      console.log("observing");
    }.observes("someProperty")

then the observer gets called if "someValueA" or "someValueB" changes even if "someProperty" will never change. The documentation says:

> Observers in Ember are currently synchronous. This means that they will fire as soon as one of the properties they observe changes.

So why is it that the observer is called?

Same i noticed for properties:

If i have property one:

    propertyOne: function() {
      return "always the same value";
    }.property("valueX")

And property two:

    propertyTwo: function() {
      console.log(this.get("propertyOne"));
    }.property("propertyOne")

And i change the value x:

    this.set("valueX", "someOtherValue");

Then property two gets called, even though propertyOne did not change.

It somehow feels like functions in both examples should not be called if nothing changes, or am i misunderstanding something?

**Comment by mixonic** [comment]
Computed properties in Ember do not re-compute their values eagerly. Instead, when a dependent key changes they are marked invalid. When consumed, they then re-compute.

Ember doesn't know if your observer is going to `get` every computed property it has as a dependent key. Computing all of them eagerly to compare values would often be wasteful.

Observers observe changes to paths. Ember does know that an observed path has changed, and thus it fires the observer. The execution of the observer is what causes the re-computation to occur. 

Your second example may be inaccurate, and colored by the fact that `propertyTwo` was used in a template. We would need to make a jsbin to discuss it in detail.

If you want to do something only when a value has really changed, I suggest you store the last value and compare it on subsequent observer calls. There is an example of this [in the beforeObserver deprecation guide](http://emberjs.com/guides/deprecations/#toc_deprecate-beforeobservers).

**Comment by phlppn** [comment]
Thanks. That made it clearer for me.
