### ISSUE TITLE
IE8 preset attributes that breaks bind-attr

### ISSUE THREAD

**Issue by yonjah** [emberjs/ember.js#10519]
It seems like IE8 automatically presets some attributes if they are not available on the original HTML tag.
if you bind those attributes using `bind-attr` helper it will throw an error for manually setting the attribute -
https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/helpers/bind-attr.js#L195

I think this `assert` should be changed to warning since `bind-attr` will overwrite the value and everything will work properly, in a case where s developer mistakenly set the attribute to some static value he will see the warning in the console, and will know what to fix.

Luckily this issue will not occur using production builds since asserts are removed, but it makes debugging IE8 issues impossible without removing this assert
 
sample code -
http://emberjs.jsbin.com/raxixituwu

**Comment by wagenet** [comment]
@rwjblue you added this in c340929a83495a945542d0884640a4fcae3ffa36. Can you take a look at this?
