### ISSUE TITLE
Keyboard shortcuts for special characters like î not working

### ISSUE THREAD

**Issue by rdossantos** [emberjs/ember.js#10512]
Keyboard shortcuts for special characters like "î" (option + i then i on Mac) are not working with 1.11 and htmlbars.  As soon as you press option + i the "ˆ" character is added to the textbox when it should wait for additional key strokes.

Issue seems to be browser specific as I could reproduce in Chrome and Safari but Firefox was fine.

You can try it out on the jsbins I stole from another issue

latest canary - not working: http://emberjs.jsbin.com/rwjblue/303/edit
1.10 - working:                    http://emberjs.jsbin.com/rwjblue/307/edit

EDIT 1:
Hmmn, they were definitely working differently when I posted.  I will update ASAP.

**Comment by rwjblue** [comment]
@rdossantos - I am seeing the same behavior between both JSBins on latest Chrome.  Can you double check them and potentially update the steps to reproduce?

**Comment by rdossantos** [comment]
Latest canary build fixes the issue!!!

**Comment by stefanpenner** [comment]
wooho!
