### ISSUE TITLE
[BUG] paramsFor does not work for nested routes in some cases

### ISSUE THREAD

**Issue by bakura10** [emberjs/ember.js#10521]
Hi,

I have a use case where my parent route force to set default query params in the setupController, that I then retrieve in the setupController of a nested route using the `paramsFor` method, however this does not work, and all the params are always "null".

I have created a JSBin that replicates the issue: http://emberjs.jsbin.com/yizewozute/1/ (JSBin uses 1.9, but I'm using 1.11 beta and experiencing the same issue).

NOTE: I'm not using default values in the controller because if I do so, EmberJS consider them as "default" values, and hence when a user change query params, and goes back to the default value, the default value does not appear anymore in the query params, which is highly problematic in my specific use case. Basically, in my application, it is either no query params at all (in which case I can use default values) or ALL the query params.

Thanks!

**Comment by wagenet** [comment]
@bakura10 I'm pretty sure this isn't a bug. According to the QP guides (http://emberjs.com/guides/routing/query-params/):

> Once inside the articles route, any changes to the category property on ArticlesController will cause the URL to update the query param. By default, a query param property change won't cause a full router transition (i.e. it won't call model hooks and setupController, etc.); it will only update the URL.

The `paramsFor` returns the initial params for the route transition. Since there is never an actual transition, `paramsFor('user')` returns the initial value upon entering that route, not the updated one.

**Comment by wagenet** [comment]
It sounds like you have a bit of an unusual setup. At this point I suggest asking a question about this on StackOverflow to see if you're approaching this issue in the correct way.
