### ISSUE TITLE
ember 'select' not binding value

### ISSUE THREAD

**Issue by zion03** [emberjs/ember.js#10522]
Example:

     export default Ember.Controller.extend({
        questionText: null,
        questionCategory: 0
     });

    {{view "select" content=model.categories
                                        optionValuePath="content.id"
                                        optionLabelPath="content.name"
                                        prompt="..."
                                        value=questionCategory}}

    {{textarea value=questionText name="" id="" cols="30" rows="10" }}

'select' not binding to questionCategory, but binding in textarea works fine.

DEBUG: Ember      : 1.10.0-beta.4 ember.debug.js:3975
DEBUG: Ember Data : 1.0.0-beta.14.1 ember.debug.js:3975
DEBUG: jQuery     : 1.11.2 ember.debug.js:3975

**Comment by trek** [comment]
Can you isolate this to a JSBin please

**Comment by zion03** [comment]
http://jsbin.com/nipewe/1/edit?html,js,output

**Comment by OrKoN** [comment]
@zion03  Do you want to have questionText updated whenever questionCategory is selected in the select box? I think you're missing some piece of code for this. For example:

```
    questionText: function () {
      var result = null;
      var questionCategory = this.get('questionCategory');
      this.get('model').forEach(function (item) {
        if (item.id === questionCategory) {
          result = item.name;
        }
      });
      return result;
    }.property('questionCategory')
```

Also the ids in the model should be unique.

**Comment by zion03** [comment]
Sorry, it's really works. Problem was in 'select' which was customized.
