### ISSUE TITLE
Initializer giving invalid router on container lookup

### ISSUE THREAD

**Issue by zyllorion** [emberjs/ember.js#10535]
Hi,

I have a problem trying to create an initialiser that allows me to control Embers router from outside of Ember#canary/cli in POJS.

This problem seems to occur mainly on deployed versions (using ember-cli `ember b`), and mainly seems to work on local `ember s` and through the same `ember b` when served through a local Apache.

My initializer is roughly the following:
```
export function initialize(container, application) {
    var router = container.lookup('router:main’);
	// above is incorrect – eager lookup
    var transitionTo = function() {
        var router = this.lookup('router:main’);
	//above is also incorrect – looked up way after initialization
        Ember.run.schedule('afterRender', function() {
            var router = this.lookup('router:main’);
	//guess what, this is also incorrect.
            .... router.transitionTo.apply(router, tempargs);
        }.bind(this));
        window._amdBridge.show();
    };
    window._amdBridge.transitionTo = transitionTo.bind(container);
```
The problem is that it gives a router with only the location property, whereas the same source run locally with `ember s` or through a local apache it's a fully populated router instance with router and targetState properties.  It does not seem to be consistent in either platform, and I have tried other ways (including much simpler than above), all with unreliable results.  I suspect there may be some kind of event that runs after the failing instance that initializes the router properly, maybe like https://github.com/emberjs/ember.js/blob/v1.10.0/packages/ember-application/lib/system/application.js#L343

I’m looking for a solution, not the bug, as this is blocking release.

1) is there a way to set the initializer to load last
2) is there a way to access the container or router instances completely outside of Ember.

Thanks

**Comment by stefanpenner** [comment]
initializers that `lookup` entities are going to break many things, you ideally want to let the app assemble itself before doing any lookups

**Comment by OrKoN** [comment]
@zyllorion Do you call transitionTo after the application is initialized? So in the last two cases, the lookup happens after the initialization, right? I think a similar code works for me in my app. You may try to debug the app with pausing on all (including caught) exceptions. Maybe something fails in the apps silently..

Also there is a way to control the order in which initializers are being loaded using `before` and `after` http://emberjs.com/api/classes/Ember.Application.html#method_initializer

**Comment by zyllorion** [comment]
Well I found a solution in doing the setup within the application router rather than initialiser, but to help others I'll continue...

@stefanpenner If you know another way to access the router instance or container instance so I can force a transition from outside of Ember please let me know!!  I'd happily look the router up after it's fully initialised but cannot find any documentation to guarantee when that happens

@OrKoN The transitionTo is run manually well after Ember initialises (I can transition internally in Ember just fine through link-to's etc.  This is why I think it may be creating a new instance of router after initialisation.

**Comment by OrKoN** [comment]
@zyllorion But do you make a lookup right before the transition? I've created a jsbin that is similar to how it works in my app http://emberjs.jsbin.com/lazizaxahu/4/edit?html,css,js,console,output
