### ISSUE TITLE
Is scheduleOnce supposed to create a run loop if one doesn't exist?

### ISSUE THREAD

**Issue by nathanpalmer** [emberjs/ember.js#10536]
According to [the documentation](http://emberjs.com/guides/understanding-ember/run-loop/#toc_what-happens-if-i-forget-to-start-a-run-loop-in-an-async-handler) `scheduleOnce` should automatically start a runloop. However I'm finding that in unit tests (ember-cli, qunit) this chunk of code will return an error.

```javascript
  variant_value_selected: function() {
    Ember.run.scheduleOnce('afterRender', this, this.set_product_variation);
  }.observes('childControllerCollection.@each.value')
```

> You have turned on testing mode, which disabled the run-loop's autorun. You will need to wrap any code with asynchronous side-effects in a run.

Digging into the source code it seems like this error could be intentional?

  * [run_loop.js#L388](https://github.com/emberjs/ember.js/blob/20be695adfb173ce7da92213b726dd3f8b13a9ee/packages/ember-metal/lib/run_loop.js#L388)

So, should we be doing something different in the test or is the documentation wrong? This seems to fix the problem but seems to be against what I've read is the right way to do it.

```javascript
  variant_value_selected: function() {
    var that = this;
    Ember.run(function() {
      Ember.run.scheduleOnce('afterRender', that, that.set_product_variation);
    })
  }.observes('childControllerCollection.@each.value')
```

**Comment by fivetanley** [comment]
Can you post an example of your unit test?

**Comment by stefanpenner** [comment]
> Digging into the source code it seems like this error could be intentional?

this is intentional, you must wrap the roots of your async in a run-loop.



> variant_value_selected: function() {
>     var that = this;
>     Ember.run(function() {
>       Ember.run.scheduleOnce('afterRender', that, that.set_product_variation);
>     })
>   }.observes('childControllerCollection.@each.value')

No this is also incorrect. I suggest referring to http://emberjs.com/guides/understanding-ember/run-loop/ as it should help you make the correct choice.

If further questions like this arise, please feel free to open a stackoverflow question and cross link here.

**Comment by nathanpalmer** [comment]
Thanks. I just posted a stackoverflow question since I was a little confused by your incorrect statement. I've read through the run-loop docs again but I wasn't sure what you were pointing at. http://stackoverflow.com/questions/28746145/what-is-the-proper-way-in-ember-to-use-scheduleonce-that-is-test-friendly
