### ISSUE TITLE
emberjs or ember.js

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/ember.js#10532]
Typing `ember` in Github repositories search doesn't return `emberjs/ember.js` in the first few results. Searching for `emberjs` yields the same results (or rather lack of).

Only `ember.js` actually resolves to this repository.

Raising this issue just to let you guys know. It might be worthwhile bringing consistency here - `emberjs/emberjs` (which corresponds to the .com domain too) instead of `emberjs/ember.js`.

**Comment by stefanpenner** [comment]
This seems like something we should make github aware of

**Comment by stefanpenner** [comment]
ember.js

**Comment by olivierlesnicki** [comment]
@github
