### ISSUE TITLE
Ember build isn't adding the template-compiler when building ember 1.10.0

### ISSUE THREAD

**Issue by MiguelMadero** [emberjs/ember.js#10537]
Steps to reproduce:

```
git clone emberjs/ember.js
cd ember.js
npm install && bower install && npm start
open http://localhost:4200/tests/index.html
```

**Comment by MiguelMadero** [comment]
Just tried master and v1.11.0-beta.1 and it works fine there.

**Comment by MiguelMadero** [comment]
I found a few related commits. Seem like 7607377 was the main one, but the way we build ember changed a lot between ember 1.10 and 1.11. I might just hack around this to manually add the ember-template-compiler in the right place.

**Comment by rwjblue** [comment]
From IRC:

```
19:21:17 <@rwjblue> mmadero: v1.10.0 only generates ember-template-compiler.js when running production builds
19:21:50 <@rwjblue> mmadero: `ember build --environment=production`
```
