### ISSUE TITLE
'application' is rendered twice when defined in the router mapping with 1.11.0-beta.3

### ISSUE THREAD

**Issue by JordyLangen** [emberjs/ember.js#10531]
I discovered this strange behaviour that worked previously:

My router looks like this:

```javascript
Router.map(function() {

    this.resource('application', {path: '/'}, function (){

    });
});
```

My `application.hbs`
```mustache
<h2 id="title">Welcome to Ember.js</h2>

{{outlet}}
```

The rendered html:
```html
<div id="ember336" class="ember-view">
    <h2 id="title">Welcome to Ember.js</h2>
    <h2 id="title">Welcome to Ember.js</h2>
    <!---->
</div>
```

I get the feeling that the `application` resource is always implicit and is not overriden if defined in the router.

jsbin: http://emberjs.jsbin.com/loricutuxa/1/edit

This is working (no double rendering) with `1.11.0-beta.1`

**Comment by rwjblue** [comment]
LOL, double the outlet fun!  I think we should make top level `application` name reserved, similar to `basic` and `array`.

**Comment by JordyLangen** [comment]
I agree, this was fixed by simply removing the `application` resource defined in the router. +1 for the fast reactions by the way.
