### ISSUE TITLE
Returning an Object from computed property can loose data binding.

### ISSUE THREAD

**Issue by raytiley** [emberjs/ember.js#10539]
This is a little bit weird, but basically In my app I'm returning the result of a ember data `find` from a computed property, and use the PromiseProxy flag `isPending` to show a loading spinner. When the route first loads this works fine.

On subsequent returns from the computed property the object is returned correctly (you can see this by the ember id increasing in my jsbins) but the isPending properties are never updated.

If I stash the promise on `window` and inspect it manually int he console `isPending` is changing, its just not reflected in the rendered output of the app.

Hope this makes sense.

Broken on Canary: http://emberjs.jsbin.com/repoqi/1/edit?html,output
Working on 1.9.1: http://emberjs.jsbin.com/zewule/1/edit?html,js,output

**Comment by stefanpenner** [comment]
seems like a regression.

**Comment by raytiley** [comment]
Playing around more with this looks like this commit is when it broke: https://github.com/emberjs/ember.js/commit/8714abad4da2d0f4ec7748077d6f3efaff594630
(http://emberjs.jsbin.com/repoqi/3/edit?js,output)

The previous commit works as expected:
https://github.com/emberjs/ember.js/commit/baa2c227622bc7ae8d76b91e58bfc3aa3c396856
(http://emberjs.jsbin.com/bexevi/1/edit?js,output)

I'm basing this on travis builds on master since that is the only way I know to get builds I can throw in JSbin.

I'm willing to put sometime to figure this out if anyone can point me in the right direction.

**Comment by rwjblue** [comment]
This was caused by the changes in https://github.com/emberjs/ember.js/pull/10494.

@wycats / @tomdale - Does this ring a bell?

**Comment by raytiley** [comment]
So this is my EmberConf project, to understand and hopefully fix this. Turns out its more pervasive than I originally thought. Returning a regular `Ember.Object` from a computed property will cause any data binding on that object to be lost.

http://emberjs.jsbin.com/yahobu/2/edit?html,js,output
