### ISSUE TITLE
Access failed transition in error substate

### ISSUE THREAD

**Issue by iStefo** [emberjs/ember.js#10542]
Trying to display better error messages, I would like to access the failed transition that led to entering the error substate. The goal is to display the URL the user wanted to enter to make it easier to debug the problem.

I tried the different hooks of the `error` route, but couldn't find a way to retrieve the failed transitions. Is there a way to do this, or do you think there should be one?

**Comment by stefanpenner** [comment]
This would be very nice cc @machty

**Comment by machty** [comment]
This seems like a good idea. There's some work being done to the router at the moment that touches on this stuff so I'll keep it in mind. For now, you can dig into some private API in and do something hacky like `route.get('router.router.activeTransition')`... I'm pretty sure that should have the errored transition you're looking for. If not, then there's probably stashing approach you could try.

**Comment by acorncom** [comment]
Per [API docs](http://emberjs.com/api/classes/Ember.Route.html#event_error) and [the guides page on this](https://guides.emberjs.com/v2.5.0/routing/loading-and-error-substates/#toc_code-error-code-substates), the transition object should be available in both error events and error substate templates.  Will close this now, but if I'm missing something, feel free to say something and we can re-open this issue
