### ISSUE TITLE
Input helper valueBinding not updated

### ISSUE THREAD

**Issue by ilkkao** [emberjs/ember.js#10541]
This code stopped working recently:

http://jsbin.com/cosogimulu/1/edit?html,js,output

Regression caused by https://github.com/emberjs/ember.js/pull/10525?

**Comment by ilkkao** [comment]
I checked that before #10525 was possible to use  ` this.set('message', '')` unlimited times to clear the user entered value.

**Comment by raytiley** [comment]
I'll take a look at this in a few hours as I'm the one that broke it. :(

**Comment by raytiley** [comment]
Pretty sure I know what this will write a test and submit a patch in a bit.

**Comment by ilkkao** [comment]
nice!, thanks @raytiley
