### ISSUE TITLE
Ember HTMLBars template compiled with undefined, Problem only with Ember 1.11 beta 

### ISSUE THREAD

**Issue by azsam** [emberjs/ember.js#10543]
Hi,

after precompilation my application templates looks like this:

Ember.TEMPLATES["application"] = Ember.HTMLBars.template((function() {
  return {
    isHTMLBars: true,
    blockParams: 0,
    cachedFragment: null,
    hasRendered: false,
    build: function build(dom) {
      var el0 = dom.createDocumentFragment();
      var el1 = dom.createTextNode("");
      dom.appendChild(el0, el1);
      var el1 = dom.createTextNode("");
      dom.appendChild(el0, el1);
      return el0;
    },
    render: function render(context, env, contextualElement) {
      var dom = env.dom;
      var hooks = env.hooks, content = hooks.content;
      dom.detectNamespace(contextualElement);
      var fragment;
      if (env.useFragmentCache && dom.canClone) {
        if (this.cachedFragment === null) {
          fragment = this.build(dom);
          if (this.hasRendered) {
            this.cachedFragment = fragment;
          } else {
            this.hasRendered = true;
          }
        }
        if (this.cachedFragment) {
          fragment = dom.cloneNode(this.cachedFragment, true);
        }
      } else {
        fragment = this.build(dom);
      }
      if (this.cachedFragment) { dom.repairClonedNode(fragment,[0,1]); }
      var morph0 = dom.createMorphAt(fragment,0,1,contextualElement);
      content(env, morph0, context, "outlet");
      return fragment;
    }
  };
}()));
But then again, I get the following Uncaught error:

 Uncaught Error: Assertion Failed: The template being rendered by `<(subclass of Ember.View):ember478>` was compiled with `undefined` which does not match `Ember@1.11.0-beta.3` (this revision).
Where should I begin to look for the problem? Could this be a bug? I dont get the error with 1.10

**Comment by clubajax** [comment]
Why was this closed without an explanation? I'm having this problem too.

**Comment by OrKoN** [comment]
@clubajax I believe you should use a proper ember-template-compiler that matches the Ember version you're using

**Comment by azsam** [comment]
Yes, I was using wrong version of ember-template-compiler.

**Comment by BenjaminHorn** [comment]
@azsam  Which version do i have to use for Ember 1.11.0-beta.5?

**Comment by rwjblue** [comment]
@BenjaminHorn - You must use the `ember-template-compiler.js` that ships with your specific Ember build.

**Comment by BenjaminHorn** [comment]
@rwjblue  Thanks Robert, my bad. had to restart the server. Now it works fine.
