### ISSUE TITLE
Value-binding on object causes HTTP request to 'undefined'

### ISSUE THREAD

**Issue by dj-hedgehog** [emberjs/ember.js#10558]
I've got a controller like this:

   ```
import Ember from 'ember';
    
export default Ember.ArrayController.extend({
  currentTrack: {'https://cdn.clougfront.com/superimage.jpg'}
})
```

and a template-file like this:
```
<div class="song">
  <img {{bind-attr src=currentTrack.artwork_url}} />
</div>
``` 
For some reason this causes Ember to send a HTTP-request to `http://localhost:4200/undefined` . It doesn't happen when currentTrack is just a string. 

**This doesn't happen when using currentTrack as a String**

How can I prevent that but still us currentTrack as an object (it normally has more attributes. I just left them out for the sake of simplicity)?

**Comment by btecu** [comment]
Did you mean `currentTrack: { artwork_url: 'https://cdn.clougfront.com/superimage.jpg' }`?

**Comment by dj-hedgehog** [comment]
Yeah, that wasn't the only issue though.
I had to initialize all object-values with at least an empty value.
