### ISSUE TITLE
input key-press action not sending event object. 

### ISSUE THREAD

**Issue by arenoir** [emberjs/ember.js#10569]
```
{{input type="test" key-press="keypress"}}
```
This should send an event object to an action named `keypress`.  However It is sending the current value on keypress.

Here is a [jsbin](http://emberjs.jsbin.com/yoxadixaqa).  

If I extend a Ember.TextField it works as expected.

```
//components/good-input.js
import Ember from 'ember';
export default Ember.TextField.extend({
  keyPress: function(e) { } //e is a event I can work with this yeah!
});

```

**Comment by mmelvin0** [comment]
I just ran into this today too, and though key-press should work like key-down and key-up. I created a pull request #10574 for this.

**Comment by joeczucha** [comment]
Also came across this today. As it stands we can't use the keypress event to work out whether it was <Enter> or <Escape> being pressed

**Comment by acorncom** [comment]
Based on the decision mentioned on the other issue linked above, looks like passing the raw event information isn't something core wants to support. Will close this now
