### ISSUE TITLE
Empty {{#if}} breaks rendering

### ISSUE THREAD

**Issue by btecu** [emberjs/ember.js#10565]
I accidentally had an `{{#if}}` block without a condition, which prevented the entire page to be rendered. 

If that's intentional, it may be useful to at least log an error.

**Comment by elwayman02** [comment]
@btecu can you provide a JSbin demonstrating this?  Also, can you tell us what version of Ember you are using, as well as whether you are using Handlebars or HTMLbars (and their respective version)?  Thanks!

**Comment by rwjblue** [comment]
http://emberjs.jsbin.com/rwjblue/336/edit shows that a nice assertion is made on canary (and I believe that assertion is in 1.10 also).

**Comment by elwayman02** [comment]
:+1:

**Comment by btecu** [comment]
I can't reproduce it right now and it may have been the case that the errors were swallowed somehow...
