### ISSUE TITLE
Is it possible to share query params between sibling routes?

### ISSUE THREAD

**Issue by SirZach** [emberjs/ember.js#10563]
My use case is this: I need to have shared time controls between sibling routes, that are structured like so: 
```javascript
this.resource('reports', function () {
  this.route('a');
  this.route('b');
});
```
I figured the best way to do this was to have a property on the <code>reports</code> controller and have the query params of the child controllers reference that as its query param like so:
```javascript
//reports controller
time: 3600

//a and b controllers
queryParams: [{
  'controllers.reports.time': {as: 'time'}
}]
```

I use these query params in the model hook to fetch specific ranges of data. All the above works well until I page refresh. I always get the default <code>time</code> value of the <code>reports</code> controller regardless of what's in the URL. Transitioning between routes works well and I have no issues there. I realize the problem probably has something to do with the name of the query parameter being a direct look up on the <code>reports</code> controller.

Is there an established design pattern for sharing query params between sibling routes or is this an unsupported use case?

PS - One of the big wins I get with the child controllers having the query params on them as opposed to the <code>reports</code> controller is that I can do this with the sibling routes:
```javascript
//a and b routes
queryParams: {
  time: {refreshModel: true}
}
```
Which will automatically call my model hook for me when the time controls update and I don't have to set up my own observers.

**Comment by machty** [comment]
This is a nice idea and there's talk of supporting something like this via an Ember-provided session service. I'll keep this around for reference, but I don't think we're going to have a fix soon.

**Comment by rwjblue** [comment]
I think the fix will be via the much discussed routing service, but I'm going to close this for now.  We need to keep the bug tracker focused on issues.
