### ISSUE TITLE
customEvents handlers only receive first argument

### ISSUE THREAD

**Issue by henrymazza** [emberjs/ember.js#10561]
When using customEvents only the event argument is passed to the handler, all others are suppressed. I’m using it to integrate typeahead.js as a component, but it’s hard to get rid of the jquery spaguetti code.

**Comment by rwjblue** [comment]
In theory it should be possible to update the event dispatcher to capture additional arguments and pass them through.  I'm not familiar with many popular use cases of this setup though, do you know of any?

**Comment by henrymazza** [comment]
__Use case__:
Any third party or first party that uses jQuery’s `.trigger( eventType [, extraParameters ] )` with the extra params or similar. Perhaps it's more DDAU friendly? 

__Motivation__:
By the time I opened this issue, was trying to make an Ember Component that encapsulates [Typeahead.js](https://github.com/twitter/typeahead.js) to respond to the ‘typeahead:select’ event, which asks for a handler like `function(obj, datum, name) { … }`. That is, the autocomplete library fires an event when something gets selected and passes the selection data with the event. 

I know it’s hard to justify the change once the most popular approach is to fire an event and inside the handler you have to hunt for the information you need, like a wrapper on Zurb’s Foundation Range Sliders:
```javascript
…
actions:
  'change.fndtn.slider': function(){
    $(‘#slider’).attr('data-slider'); // hunt down the element and asks for the value
  });
```

When dealing with extra parameters I got to make a proxy call to a handler function (which isn’t in the ‘actions’ attribute, but I guess could be), like so:
```js
this.$().on('customEvent:with:extraParaments', this.handlerFunction)
```
With Ember supporting custom parameters this could be a cleaner code. That's what I always love in Ember, every time I do something the Ember Way™ the code gets smaller. In this particular case it just gets uglier.

__Still Make Sense__?
Today using 1.13 I'm finding easier to just reimplement everything myself in _emberland_ than to integrate with third parties. It's not just that, but as Components gets to be the center of attentions it won't go the direction of further isolation and wildcard nature these integrations need.

**Comment by rwjblue** [comment]
Thank you for the detailed reply!  I think that it would be possible to thread extra arguments through the system (and I'd gladly review a PR updating `Ember.EventDispatcher` and `Ember.View`'s `handleEvent` code), but wasn't sure of the actual need.

@runspired - You have been working on event related things lately (both for capture work and gesture support), do you have any thoughts on if we should thread through extra arguments?

**Comment by runspired** [comment]
@rwjblue @henrymazza After much thought, I think this should be incorporated.  While actions are better for ember based code, we're trying to make 3rd party libs and events as easy as possible to use, and I often see attempts at emulating actions via events coming from 3rd party components.  We shouldn't break jQuery based eventing semantics given how prevalent it is.
