### ISSUE TITLE
Need a new base JSFiddle for 1.10+

### ISSUE THREAD

**Issue by jdmarshall** [emberjs/ember.js#10560]
Now that handlebars is gone by default, it's a little harder to set up a repro step with EmberJS.  

Could someone more sophisticated put up a placeholder JSFiddle config so the rest of us can copy it to file repro examples?

Thanks.

**Comment by pcjpcj2** [comment]
:+1:

**Comment by xtian** [comment]
@jdmarshall http://jsfiddle.net/a3zrbgvc/

**Comment by mixonic** [comment]
This is usually kept up to date in: https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md I've bumped the fiddle in https://github.com/emberjs/ember.js/pull/10588.

And emberjs.jsbin.com is usually updated shortly after release.

I'm going to close this for now.

**Comment by jdmarshall** [comment]
I may be wrong, but if we're talking a 1.10 compatible JSFiddle, shouldn't it not be peppered with handlebars script tags?
