### ISSUE TITLE
Confusion about childViews and @each with nested components

### ISSUE THREAD

**Issue by typeoneerror** [emberjs/ember.js#10573]
This may be a bug, but it also may just be me misunderstanding how the `childViews` array works in views. In any case, if I am using this incorrectly, I'd like to add this to documentation if possible, because this turned into a major time suck. 

To display the issue, here's a jsbin that works:

http://emberjs.jsbin.com/jebihegaye/1

Click any item to "start editing". The parent component has a property called `isAnyEditing` that watches `childViews.@each.isEditing`. This works great when...

A. You _only_ have the `{#each}` loop in the parent component template.
B. The `isAnyEditing {{isAnyEditing}}` snippet appears _after_ the `each` loop.

Here is the one line change failing version:

http://emberjs.jsbin.com/jebihegaye/2

In the second version, where the `isAnyEditing {{isAnyEditing}}` snippet is _before_ the `each` loop, isAnyEditing does not update at all and `childViews` is actually blank upon `didInsertElement` (you can check the log between the two demos to verify). 

Are we not supposed to have any other content in a component that uses an each loop? This seems unlikely and I've not found documentation for this "gotcha".

**Comment by lolmaus** [comment]
The interesting part is that when you have a `{{isAnyEditing}}` both before and after the `{{#each}}` loop, the behavior is broken for both of them.

This may indicate that the computed property depending on `childViews.@each.isEditing` is cached and never recalculated.

Requesting clarifications from Ember mainainers! :rotating_light:

**Comment by stefanpenner** [comment]
`childViews` isn't meant for observing, the overhead of correctly maintaining these observations in complex scenarios is quite high. Their exists a narrow path where it does work, but in general I would strongly suggest taking a different approach.

@krisselden r?

**Comment by lolmaus** [comment]
@stefanpenner, communication between a component and its block content has always been puzzling me. Is there a recommended way to do it?

**Comment by stefanpenner** [comment]
in latest ember, you can `yield` children forward. Alternatively, children can report to their parents.

**Comment by typeoneerror** [comment]
@stefanpenner ended up setting the "editing" property on the model this list view was representing. `@each` works great that way. any other better approach? It felt odd setting a property on the model that wasn't a database field.

**Comment by typeoneerror** [comment]
Also, this 

> childViews isn't meant for observing

Is exactly what I was thinking should be in the documentation. I think I will add and submit a pr.

**Comment by erichonkanen** [comment]
hello,

I just ran into this and am wondering what the recommended approach is? Here is my form and form field component in a template:
```
          {{#validated-form submit='changePassword' parent=this as |form|}}
            {{form.input type="password" id="currentPassword" value=currentPassword placeholder="enter your current password" label="Current Password"}}
            {{form.input type="password" id="new-password1" value=newPassword1 placeholder="enter a new password" label="New Password"}}
            {{form.input type="password" id="new-password2" value=newPassword2 placeholder="enter the password again" label="Confirm New Password"}}
          {{/validated-form}}
```
Here is my form component... I want to be able to detect a change to *any* child `{{form.input}}` and trigger some code...
```
ValidatedFormComponent = Ember.Component.extend
  classNames: ['validated-form']
  errors: null
  formObserver: (->
    debugger
  ).on 'childViews.@each.value'
```
