### ISSUE TITLE
Testing: how to assert between two sequential promises/run.laters? How to skip `run.later` waiting in tests?

### ISSUE THREAD

**Issue by lolmaus** [emberjs/ember.js#10580]
Hi!

I [asked](http://stackoverflow.com/questions/28782076/testing-how-to-assert-between-two-sequential-promises-run-laters-how-to-skip) on StackOverflow first and my bounty is expiring. Thus posting here.

I have a component which is a button which changes its state. The state determines its HTML classes, text and icon. Initially the button is in the `Ready` state. When clicked, it goes into `Pending` state and launches an action. When the action resolves its promise, the button changes it's state to `Finished` and launches a cooldown timer. When the timer triggers, the button returns to the `Ready` state.

Here's its code:

```js
App.FooBarComponent = Ember.Component.extend({   
  tagName: "button",   
  status: "Ready",
  revertStatusPeriodMs: 2000,

  click: function() {
    this.set('status', 'Pending');

    // A fake ajax
    this.run()
      .then( function() {
        this.updateStatus('Finished');
      }.bind(this))
      .catch( function() {
        this.updateStatus('Error');
      }.bind(this));
  },

  run: function() {
    // Imitating a time-consuming Ajax request
    return new Ember.RSVP.Promise( function(resolve) {
      Ember.run.later( function() {
        resolve();
      }, 500);
    });
  },

  updateStatus: function(statusText) {
    this.set('status', statusText); 

    var periodMs = this.get('revertStatusPeriodMs') || 1000;

    Ember.run.later( function() {
      this.set('status', 'Ready');
    }.bind(this), periodMs);
  }
});
```

This code works fine, but i'm unable to test it.

Here's my attempt:

```js
test('clicking the button should set the label', function(assert) {
  expect(4);

  visit('/');

  assert.equal( find('button').text().trim(), 'Ready', 'Should initially be "Ready"');

  andThen(function() {
    click('button');
    assert.equal( find('button').text().trim(), 'Pending', 'Should "Pending" right after click');
  });

  // This one fires too late!
  andThen(function() {
    assert.equal( find('button').text().trim(), 'Finished', 'Should become "Finished" after promise fulfills');
  });

  andThen(function() {
    assert.equal( find('button').text().trim(), 'Ready', 'Should eventually return to the "Ready" state');
  });
});
```

I have two problems:

1. I'm unable to test the Finished state. It seems that `andThen` waits for all promises and `run.later`s to finish, while i want to test an intermediate state. How do i run an assertion between two sequential promises/`run.later`s?

2. Times can be long, and tests can take forever to complete. I generally don't mind refactoring the code for better testability. I even agree to include some commands into the code to be detected by tests. But **i refuse to adjust times in the app based on the environment** (e. g. 2000 ms for dev/prod, 0 ms for test). Instead, i would prefer a stub timer or some other solution.

I've tried Sinon and failed: when i mock the timer, `andThen` never returns. Neither of [these](http://stackoverflow.com/questions/21896003/how-do-i-test-ember-run-later-with-sinon) solutions helped me.

JSBin: http://emberjs.jsbin.com/fohava/2/edit?html,js,output (Sinon is included)

**Comment by stefanpenner** [comment]
Reposting isn't needed SO is the best venue for this. We need to keep the bug tracker on topic, and focused on bugs or it will become more unwieldy.
