### ISSUE TITLE
How to avoid deprecation when using RSVP.hash from route in ember 1.11?

### ISSUE THREAD

**Issue by toranb** [emberjs/ember.js#10587]
I have a simple route that returns both a model and codes like so

```js
export default Ember.Route.extend({
    model: function() {
        var codes = [];
        codes.pushObject(Foo.create({code: "ABC", text: "SOME TEXT"}));
        return Ember.RSVP.hash({
            model: Bar.create(),
            codes: codes
        });
    },
    setupController: function(controller, hash) {
        controller.set("model", hash.model);
        controller.set("codes", hash.codes);
    }
});
```

In my template I use codes like so

```js
{{my-component-thing options=codes}}
```

But when I boot the app I'm told to use model.codes instead and codes is deprecated. I use RSVP.hash a ton like this and I'm looking for some guidance on how to avoid this deprecation warning in ember 1.11

thank you in advance!

**Comment by rwjblue** [comment]
So this is a funny one.  Basically, by setting `model` on the object controller first you are enabling the proxying behavior.  Then you set `codes` on the controller which falls back to actually setting `model.codes` unless `codes` is defined in the root of your controller.

Solutions:

* Change your controller to extend from `Ember.Controller` instead of `Ember.ObjectController`
* Add `codes: null` to your controller:

```javascript
export default Ember.ObjectController.extend({  // should use Ember.Controller here, this is just for illustration
  codes: null
});
```

**Comment by toranb** [comment]
Thanks for the quick and detailed reply @rwjblue !!!

**Comment by rwjblue** [comment]
The explanation above is one of the major reasons why we are removing `Ember.ObjectController`. In the case above, before the deprecation you would have had no idea that your model itself was being mutated to add `codes` (which was clearly not your intent).

**Comment by toranb** [comment]
Totally get it - I never use ObjectController but the "default behavior" actually forced this proxy to occur as you mentioned. I was able to get around it but I had to add a controller file and declare it as Ember.Controller (not something that adds value in this scenario) so I see the deprecation of ObjectController as a win/win :)
