### ISSUE TITLE
Documentation example tests broken

### ISSUE THREAD

**Issue by flyswatter** [emberjs/ember.js#10581]
The [example test helper jsbin](http://emberjs.com/guides/testing/test-helpers/) is broken, it doesn't pass its own tests.

**Comment by vire** [comment]
Weird is that [release/ember.js build](http://builds.emberjs.com/release/ember.js) in the JSBin does contain the **ember-template-compiler** module

and produces:

```
Error: Cannot call `compile` without the template compiler loaded. Please load `ember-template-compiler.js` prior to calling `compile`.
```

but if I add manually the template compiler 
```
<script src="http://builds.emberjs.com/tags/v1.10.0-beta.3/ember-template-compiler.js"></script>
```

the error is [gone](http://jsbin.com/luzexaximi/2/edit)

**Comment by rwjblue** [comment]
Fixed upstream in the guides repo.
