### ISSUE TITLE
error.stack behaves differently between 1.9.1 and 1.10.0

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember.js#10589]
[1.9.1 jsbin](http://emberjs.jsbin.com/gadegonivo/1/edit?html,js,output) and [1.10.0 jsbin](http://emberjs.jsbin.com/kezacubeba/1/edit?html,js,output)

The first shows the error.stack and the second error.stack is undefined. This is probably a difference between Handlebars and HTMLBars.

**Comment by stefanpenner** [comment]
i suspect its fixed by: https://github.com/tildeio/router.js/pull/151

**Comment by stefanpenner** [comment]
should be fixed (router.js fix was merged)
