### ISSUE TITLE
contentIndex not updated when an item is removed from ArrayController in ember 1.10

### ISSUE THREAD

**Issue by toranb** [emberjs/ember.js#10586]
http://emberjs.jsbin.com/vucufu/1/edit?html,js,output

In the jsbin above if you remove the middle item from the array controller by clicking the rm button you will notice that last item keeps the original contentIndex of 2 instead of getting updated to 1 like it did before ember 1.10/HTMLBars

Is this the expected behavior or should the index get updated as items are added/removed?

**Comment by zeppelin** [comment]
In newer Ember versions it should just be `{{#each model as |item index|}}`, no? Not sure if it should break the old semantics tho.

**Comment by toranb** [comment]
I just tried the syntax you mentioned but index is always undefined using 1.10

```js
{{#each model as |item index|}}
```

**Comment by zeppelin** [comment]
I don't know if it's enabled in the current beta, but it should work for sure judging by looking at this PR: https://github.com/emberjs/ember.js/pull/10160/files#diff-8600fa262132288b94b079e49d7e42a6R1044

**Comment by toranb** [comment]
Interesting - so if I'm using the stable 1.10 (not a beta release) how can I opt into this? The issue I have is that w/ 1.10 I don't have a valid index property inside my each loops that will update (unless this feature you mentioned is something I can turn on)

thanks again for all the help!

**Comment by toranb** [comment]
Looks like a quick bump to 1.11.0-beta.4 with ember-cli worked to get this index

**Comment by mmun** [comment]
> like it did before ember 1.10/HTMLBars

This is not true. See [1.7.1](http://emberjs.jsbin.com/saxeqizisu/1/edit?html,js,output), [1.8.1](http://emberjs.jsbin.com/zarajakave/1/edit?html,js,output) and [1.9.1](http://emberjs.jsbin.com/xuqupaqupe/1/edit?html,js,output).

The block params version has been approved for 1.11. :+1:

**Comment by toranb** [comment]
@mmun thanks for the quick reply and error correction! I'll stick w/ 1.11 for now!
