### ISSUE TITLE
Ember 1.11 beta:  input placeholder "undefined"

### ISSUE THREAD

**Issue by ssured** [emberjs/ember.js#10595]
When binding an input placeholder property to an undefined value, it will render the placeholder with the string "undefined"

http://emberjs.jsbin.com/xegoyofehi/1/

Does work in 1.10. Was occurring in all 1.11 betas I have tested

**Comment by rwjblue** [comment]
Seems related to the AttrNode work in https://github.com/emberjs/ember.js/pull/10186.  Flagging as a regression and marking for 1.11.0.
