### ISSUE TITLE
How to create and use Ember.Container() in unit tests with ember 1.11

### ISSUE THREAD

**Issue by toranb** [emberjs/ember.js#10593]
I have some unit tests that show a deprecation as of 1.11 for something like this

```js
var container = new Ember.Container();
container.register("store:main", Store);
```

How should I proceed going forward for tests like this?

**Comment by cowboyd** [comment]
One way might be to use `isolatedContainer()` from ember-test-helpers.

https://github.com/switchfly/ember-test-helpers#miscellaneous-helpers

**Comment by toranb** [comment]
@cowboyd I did see that in the warning but it mentioned "falling back for backwards compat" so I wasn't sure if this was the way forward (meaning beyond getting me to the next deprecation warning) :)

**Comment by workmanw** [comment]
I just upgraded and was bit by this one as well.

**Comment by toranb** [comment]
@cowboyd what is the import /syntax to new this up then?

**Comment by stefanpenner** [comment]
@toranb hint https://github.com/stefanpenner/ember-state-services/pull/11/files#diff-0636be8edc4135450aec63f7c18e4fc5R12 ?

This likely isn't a bug, rather a question for SO. Feel free to cross link

**Comment by toranb** [comment]
Agreed! thanks for the help guys!

**Comment by stefanpenner** [comment]
> Agreed! thanks for the help guys!

:+1:

**Comment by toranb** [comment]
Just a quick update for anyone who might find this issue in the future. I was able to update my simple container based projects like so :)

https://github.com/toranb/ember-cli-simple-store/commit/1fcc7001635f30907d14cf9ded7e60b8178774f7
