### ISSUE TITLE
Move logLibraryVersions() into an initializer

### ISSUE THREAD

**Issue by taras** [emberjs/ember.js#10591]
It would be helpful to show app version in library version logger that's displayed when app boots in development. This is done in [application#init](https://github.com/emberjs/ember.js/blob/v1.11.0-beta.4/packages/ember-application/lib/system/application.js#L282) by [lobLibraryVersions](https://github.com/emberjs/ember.js/blob/v1.11.0-beta.4/packages/ember-application/lib/system/application.js#L1106) function. 

[ember-cli-app-version](http://github.com/embersherpa/ember-cli-app-version) uses the initializer to register app version to make it available in Ember Inspector Info tab. If `logLibraryVersions` was executed via an initializer then it would be possible to use initializer's *before* property to register app version before `logLibraryVersions` is called. 

Here is original request that prompted this and @lukemelia's suggestion to add this as an initializer [https://github.com/embersherpa/ember-cli-app-version/issues/13](https://github.com/embersherpa/ember-cli-app-version/issues/13)

I can put together a PR for this.

**Comment by stefanpenner** [comment]
@taras i think ecli-app-versions could just have a guard, where it only runs once per page.

**Comment by taras** [comment]
@stefanpenner the problem is not that it runs multiple times but rather that it's not being injected early enough to be included in when `logLibraryVersions` is executed.

**Comment by stefanpenner** [comment]
ah

**Comment by stefanpenner** [comment]
cc @tomdale

**Comment by stefanpenner** [comment]
this seems to have gone stale

**Comment by shakeelss2009** [comment]
@taras not sure why this was never implemented. Do we have a workaround for this?

**Comment by taras** [comment]
I don't know. I'm not really maintaining ember-cli-app-version anymore. You could try to file a bug there.
