### ISSUE TITLE
Ember.inject.controller() doesn't work on Object/Array Controllers

### ISSUE THREAD

**Issue by joeruello** [emberjs/ember.js#10605]
I understand that controllers are going anyway soon,  but I think it's weird that `Ember.inject.controller()` it doesn't work on Object/Array controllers. [JSBin](http://emberjs.jsbin.com/wizocahudu/2/).

I think that it should either work as expected, or update the assertion message to explicitly mention that the injection will only work with basic controllers.

Would be happy to work on a PR for either :)

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/10612 should address this

**Comment by aleem076** [comment]
Where is the fix for it?
