### ISSUE TITLE
Deep computed.alias on null property breaks query params

### ISSUE THREAD

**Issue by novaugust** [emberjs/ember.js#10608]
A route whose controller has something like `computed.alias('bar.baz')` will prevent the route from loading successfully if `bar` is `null` with error 

> Error while processing route: index Property set failed: object in path "bar" could not be found or was destroyed. Error: Property set failed: object in path "bar" could not be found or was destroyed.

Example controller code:
```js
App.IndexController = Ember.Controller.extend({
  queryParams: ['foo'],
  foo: Ember.computed.alias('bar.baz'),
  bar: null
});
```

JSBIN:  http://emberjs.jsbin.com/xejajujamu/1/edit?js,console,output

**Comment by stefanpenner** [comment]
basically, QP can't be CP's. This is a fundamental issue with the current QP system, and is planned to be improved.

**Comment by novaugust** [comment]
Understood, thanks. I'll close it to keep things from getting polluted around here

**Comment by JackCA** [comment]
@stefanpenner I'm just running into this as well. Is this being tracked somewhere I can follow along?
