### ISSUE TITLE
Is `view.id` reserved in Ember 1.10?

### ISSUE THREAD

**Issue by herom** [emberjs/ember.js#10607]
I upgraded our app from Ember 1.8.1 with Ember App Kit to Ember 1.10.0 with Ember-CLI 0.2.0 and I saw the following behaviour which breaks my application (prior to Ember 1.10.0 this was working code!):

test.hbs
```
{{#each itemId in model}}
  {{view 'simple/test' id=itemId}}
{{/each}}
```

Where `view.id` was the value I expected in Ember 1.8.0, now with Ember 1.10.0 `view.id` is a `SimpleStream`!? If I change the param name to something other than `id`, everything is working like before. Is this intended behaviour?

See jsbin: http://emberjs.jsbin.com/kequkaregi/1/edit?html,js,output

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/10613.
