### ISSUE TITLE
_morph is null on AttrNode when moving one ContainerView into another ContainerView.

### ISSUE THREAD

**Issue by flubba86** [emberjs/ember.js#10601]
I've got a minimal JSBin reproduction of the issue here:
http://jsbin.com/gusokifero/9/edit

Run it, then click Load Container to dynamically create two new ContainerViews inside our main container each with a dummy child view (to get them to render and show where they are).

Then click Move Container to move the first generated ContainerView into the second ContainerView as its child.

When ember tries to render out the new DOM, it crashes on AttrNode._morph is null. 
Error in console is "Cannot read setContent of null". It occurs where the previous value of the attribute should be written back to the AttrNode value, but it cannot because _morph is null.

**Comment by krisselden** [comment]
@mixonic this seems to be an AttrNode issue.

**Comment by stefanpenner** [comment]
I believe this is fixed, if not we can reopen assuming a reproduction can be provided.
