### ISSUE TITLE
IE8 & IE9 fail on input type="search"

### ISSUE THREAD

**Issue by MichaelVdheeren** [emberjs/ember.js#10603]
Issue:
when using the input helper setting the type to search this results in an error in the metamorph code.

```
{{input type="search" classNames="form-control js-noPlaceholder" placeholder="Search" value=searchValue}}
```

What I expected it to do:
fallback to normal input element for IE8 and IE9 if possible.

Failing test:
need to add this.

**Comment by MichaelVdheeren** [comment]
Failing jsbin: http://jsbin.com/wacihaqake/1/

**Comment by MichaelVdheeren** [comment]
Related to #10458

**Comment by mixonic** [comment]
Sounds like a dupe of #10458

**Comment by MichaelVdheeren** [comment]
@mixonic but this one provides you with a failing test ;-)
