### ISSUE TITLE
Library "App" is already registered with Ember.

### ISSUE THREAD

**Issue by MichaelVdheeren** [emberjs/ember.js#10600]
Issue:
* Library "App" is already registered with Ember.
* When running tests

When:
* Running tests using ember-cli.
* First test works, second gives the issue above.
* Looks like teardown (or afterEach) did not work.

```
import Em from 'ember';
import { test } from 'ember-qunit';
import startApp from '../helpers/start-app';
var App;

module('Integration Tests', {
  setup: function() {
    App = startApp();
    visit('/');
  },
  teardown: function() {
    Em.run(App, App.destroy);
    
  }
});

test('I can post a comment', function(assert) {
  
});
```

**Comment by btecu** [comment]
I get the same warning if I call `App.reset()`. It's very easy to reproduce and it happens with `Ember 1.10+`.

**Comment by rwjblue** [comment]
This is an issue in an addon (not a bug in Ember itself), and https://github.com/embersherpa/ember-cli-app-version/pull/14 should fix it.  For now you can remove ember-cli-app-version from your ember-cli app...
