### ISSUE TITLE
[Regression] disconnectOutlet can't reach across routes

### ISSUE THREAD

**Issue by Soliah** [emberjs/ember.js#10606]
Disconnecting an outlet used to work even from a sub route. Now the element doesn't get removed from the DOM.

Modal doesn't get removed In Ember 1.11.0-beta.5: http://emberjs.jsbin.com/dofohetuhu/5/edit
Modal gets removed in Ember 1.11.0-beta.1: http://emberjs.jsbin.com/dofohetuhu/3/edit

Seems to have started from beta.2, after this change ba1d1a61731ca3f34f998ac122e65e3703dd6bb0

**Comment by mutewinter** [comment]
:+1: also experiencing this on 1.11.0-beta.5

**Comment by mutewinter** [comment]
My experience is that a controller triggering the disconnect via a triggerAction that hits the application controller fails. My temporary fix was to create a `bugFixDisconnectOutlet` function that calls `disconnectOutlet` twice with the same arguments.

**Comment by rudymacias** [comment]
I'm also experiencing this on 1.11.0-beta.5 ... @mutewinter can you explain how u call the disconnectOutlet twice since I attempted that and still didn't fix the issue.

**Comment by mutewinter** [comment]
> My experience is that a controller triggering the disconnect via a triggerAction that hits the application controller fails. My temporary fix was to create a bugFixDisconnectOutlet function that calls disconnectOutlet twice with the same arguments.

Actually, it turns out that I'm needing to call `disconnectOutlet` for every time the outlet was rendered.

http://emberjs.jsbin.com/xibuvaduzu/1/edit?html,js,output

1. Click Open Layer
1. Click Close
1. Modal closes fine

1. Click Open Layer
1. Click Open Layer Again
1. Click Close
1. Modal does not close
1. Click Close
1. Modal closes

Close needs to be clicked N number of times, where N is the number of times the outlet was rendered into.

**Comment by mutewinter** [comment]
And here's my temporary fix:

```coffee
  bugFixRender: (view, options) ->
    @disconnectOutlet(
      outlet: options.outlet
      parentView: options.into
    )
    @render(view, options)
```

**Comment by ef4** [comment]
PR #10683 addresses @mutewinter 's comment about stacking multiple calls to render.

The original issue reported by @Soliah is a regression and still open.

**Comment by ef4** [comment]
Now I've extended PR #10683 to also close the original issue.
