### ISSUE TITLE
disconnectOutlet doesn't disconnet nested templates

### ISSUE THREAD

**Issue by svox1** [emberjs/ember.js#10617]
I doenst know which version this behavior was changed.

http://emberjs.jsbin.com/busemameno/1/edit?html,js,console,output
Ember v1.11.0-beta.5

Click on "Open Layer" > "Open Next Layer" > "close".
=> nothing happens: "error"
"Script error. (line 0)"

Click on "Open Layer" > "close". 
=> the Layer is closed. 

Currently it works only if I close the second layer before:
```javascript
this.disconnectOutlet({
        outlet: 'nextLayer',
        parentView: 'layer'
      });
this.disconnectOutlet({
        outlet: 'modal',
        parentView: 'application'
      });
```

Is this a bug or did you change the behavior?

**Comment by btecu** [comment]
https://github.com/emberjs/ember.js/issues/10606

**Comment by trek** [comment]
Closing from duplication
