### ISSUE TITLE
App.Router.router is null

### ISSUE THREAD

**Issue by panta82** [emberjs/ember.js#10618]
As the title says, after update to 1.11.0-beta.5 (from 1.9), `App.Router.router` is `null`.

There's nothing about this in the change log. Bug? Or is there a different way to get the router instance now?

**Comment by stefanpenner** [comment]
cc @tomdale this is most likely related to the recent router + app boot related refactorings.

**Comment by stefanpenner** [comment]
@panta82 using and injection to get the router may be the best bet.

**Comment by panta82** [comment]
I made it work with injection, but there are other things broken, so I've given up on update for now.
I'll try again once 1.10.1 or 1.11 stable come out.

**Comment by stefanpenner** [comment]
im assigning tom, as i believe his most recent router/boot process refactoring may be the culprit

**Comment by rwjblue** [comment]
I am unsure that accessing the `router.js` instance off of `App. Router` is a public API?

**Comment by stefanpenner** [comment]
> I am unsure that accessing the router.js instance off of App. Router is a public API?

I don't believe it is, but people do rely on this behavior. We should be sure that an alternative exists, or fix ^^.

**Comment by panta82** [comment]
IMO, for what is worth, this always felt hackish. There should be a better way to get things that are 100% guaranteed to forever be singletons.

**Comment by leojh** [comment]
Just tried upgrading from 1.10 to 1.11 and I'm seeing this.

**Comment by stefanpenner** [comment]
> There should be a better way to get things that are 100% guaranteed to forever be singletons.

injections!

**Comment by stefanpenner** [comment]
cc @tomdale this was likely broken by the boot order stuff you guys changed

**Comment by tomdale** [comment]
`App.Router.router` was not public API, but I'd love to solve this use case for you all. @leojh, @panta82 would you mind explaining what you were needing the bare `router.js` instance for? Maybe there's a public API we could surface for you.

**Comment by leojh** [comment]
@tomdale @panta82 for me, I have an ember app embedded inside of an ASP.NET Web Forms app (I know). I was using the ``App.Router.router`` API in order to request route transitions to the ember app from the host app . After this breaking change: I achieved the same behavior by doing the following:

```js
var router = _emberApp.__container__.lookup('router:main').router;
router.replaceWith('/route');
```

**Comment by tomdale** [comment]
@leojh Thanks for the reply. It sounds like the work-in-progress routing service is exactly what you need. Once we wrap up some Glimmer loose ends I would love to try to get that prioritized for 2.2/2.3.

In the meantime, your fix is approximately correct, although it may be less brittle to register an instance initializer that exports the router rather than poking through `__container__`.

**Comment by leojh** [comment]
@tomdale I am aware that using ``__container__`` is not at all recommended so I will explore your suggestion :)

**Comment by stefanpenner** [comment]
@tomdale this is a breaking change, and should likely be fixed. in the 1.x series.

**Comment by tomdale** [comment]
@stefanpenner I don't believe it was ever public

**Comment by rwjblue** [comment]
@stefanpenner - I do not believe that `App.Router.router` was documented or public.

**Comment by stefanpenner** [comment]
then feel free to close
