### ISSUE TITLE
 An outlet was specified but was not found.

### ISSUE THREAD

**Issue by arenoir** [emberjs/ember.js#10611]
Upgrading from 1.10 to 1.11-beta-4 I ran into the following issue.

In the router when rendering templates in the  `renderTemplate` hook the `into` property used to default to the parent template. 

The following used to work.
```  
/routes/timecards/day.js
export default Ember.Route.extend(
  renderTemplate: function() { 
    this.render('timecards/day/title', { 
      outlet: 'timecardsTitle',
    });
    this.render('timecards/user/days');
},
```

It now throws an exception 
```
Error while processing route: timecards.day Assertion Failed: An outlet (timecardsTitle) was specified but was not found.
```

The error goes away if if add an `into` property to any render calls with an `outlet` property.

So it seems the render function doesn't have a default `into` property when the `outlet` property is specified.

**Comment by Soliah** [comment]
Some JSBins illustrating the issue:

1.11.0-beta.1 works: http://emberjs.jsbin.com/viyodiqobi/5/edit
1.11.0-beta.2 onwards doesn't work http://emberjs.jsbin.com/viyodiqobi/4/edit

**Comment by poetcyborg** [comment]
I was able to solve this issue by adding the name of the template where the outlet is located.
```
App.PostsShowRoute = Ember.Route.extend({
  renderTemplate: function() {
    this.render({
      outlet: "body",
      into: "posts"
    });
  }
});
```
