### ISSUE TITLE
Container: Deprecate camelCased/underscored lookups

### ISSUE THREAD

**Issue by fivetanley** [emberjs/ember.js#10619]
Prefer dasherized. We talked about this in the Ember Data meeting and making things loosy goosey all over the place makes things confusing and you end up wasting time trying to debug things because you used the wrong format for the model, controller, etc.

**Comment by stefanpenner** [comment]
should be in the resolver, resolver.normalize

**Comment by rwjblue** [comment]
I'm not sure what we can do here with this.  In theory we could add a debug only test that checks your modules (in the resolver repo) to ensure you are compliant with our "dashes rule the world" mentality.

Closing for now, happy to reopen if we can make this a bit more actionable.
