### ISSUE TITLE
Ability to augment properties of object in array

### ISSUE THREAD

**Issue by leepfrog** [emberjs/ember.js#10626]
I have a need to augment models with supplemental property data.  

The old-old school way of doing this is with `ArrayProxy` and managing a cache of `ObjectProxy` objects applied to content (so that you always get the same `ObjectProxy`).  This is tricky and requires good bookkeeping of your cache (managing array changes).  Works well, but debugging proxy issues is not fun.

The old school way of doing this is with `itemController`, but I heard this method is going away?  It's also not flexible enough to support my use case.

Is there a suggested way to handle this scenario?

**Comment by stefanpenner** [comment]
> Is there a suggested way to handle this scenario?

component, or service that when asked (given a specific model) returns a bucket of additional meta information.

**Comment by stefanpenner** [comment]
Likely better to ask this on stack-overflow, and don't forget to link from here to there. Ideally, if you can provide a one or more examples, good suggestions can be made.
