### ISSUE TITLE
Rendering error (IE 11 edge, Ember 1.10.0)

### ISSUE THREAD

**Issue by bsclifton** [emberjs/ember.js#10622]
I have an Ember CLI 0.2.0 app using Ember 1.10.  When loading my site in IE 11 (edge mode), I'm getting the following error:
"a fragment parent must have boundary nodes in order to detect insertion"

(full stack trace below)

t [Line: 18, Col: 14699], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
r [Line: 18, Col: 14993], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
E.createMorph [Line: 18, Col: 8730], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
E.createMorphAt [Line: 18, Col: 8988], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
render [Line: 2, Col: 29142], benz-guru-6ae84d7a39d726267e4af895f3813e61.js
render [Line: 17, Col: 23275], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
u.prototype.createElement [Line: 16, Col: 23405], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
r [Line: 9, Col: 2437], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
Anonymous function [Line: 9, Col: 4594], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
i.prototype.invoke [Line: 5, Col: 11392], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
i.prototype.flush [Line: 5, Col: 11917], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
r.prototype.flush [Line: 5, Col: 10072], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
s.prototype.end [Line: 5, Col: 5271], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
Anonymous function [Line: 5, Col: 4097], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
a [Line: 5, Col: 4046], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
s.prototype.defer [Line: 5, Col: 5993], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
Anonymous function [Line: 14, Col: 13898], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
p [Line: 20, Col: 18713], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
c [Line: 20, Col: 18472], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
h [Line: 20, Col: 18535], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
Anonymous function [Line: 20, Col: 18119], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
Anonymous function [Line: 2, Col: 9488], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
c [Line: 2, Col: 8111], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
h.fireWith [Line: 2, Col: 8872], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
send [Line: 4, Col: 28765], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
ajax [Line: 4, Col: 25520], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
e.default.GET [Line: 4, Col: 18380], benz-guru-6ae84d7a39d726267e4af895f3813e61.js
Anonymous function [Line: 1, Col: 11427], benz-guru-6ae84d7a39d726267e4af895f3813e61.js
Anonymous function [Line: 2, Col: 9488], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
c [Line: 2, Col: 8111], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
h.fireWith [Line: 2, Col: 8872], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
i [Line: 4, Col: 22915], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
t [Line: 4, Col: 29116], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
send [Line: 4, Col: 28765], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
ajax [Line: 4, Col: 25520], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
e.default.GET [Line: 4, Col: 18380], benz-guru-6ae84d7a39d726267e4af895f3813e61.js
model [Line: 1, Col: 11354], benz-guru-6ae84d7a39d726267e4af895f3813e61.js
i [Line: 11, Col: 3109], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
deserialize [Line: 12, Col: 8567], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
f [Line: 20, Col: 15536], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
r.prototype.runSharedModelHook [Line: 18, Col: 27451], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
getModel [Line: 18, Col: 30293], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
Anonymous function [Line: 20, Col: 14268], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
a [Line: 5, Col: 4046], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
s.prototype.defer [Line: 5, Col: 5993], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
Anonymous function [Line: 14, Col: 13898], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
h.prototype.then [Line: 20, Col: 29416], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
n.prototype.resolve [Line: 20, Col: 10869], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
n [Line: 20, Col: 11760], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
c [Line: 18, Col: 30838], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
u.prototype.transitionByIntent [Line: 20, Col: 3655], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
u.prototype.refresh [Line: 20, Col: 4592], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
refresh [Line: 12, Col: 7325], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
send [Line: 4, Col: 28765], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
ajax [Line: 4, Col: 25520], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
e.default.GET [Line: 4, Col: 18380], benz-guru-6ae84d7a39d726267e4af895f3813e61.js
actions.authenticate [Line: 1, Col: 5832], benz-guru-6ae84d7a39d726267e4af895f3813e61.js
send [Line: 14, Col: 17429], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
Anonymous function [Line: 11, Col: 10915], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
s.prototype.run [Line: 5, Col: 5612], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
l [Line: 10, Col: 26928], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
m.registeredActions[r].handler [Line: 11, Col: 10895], vendor-11f60fbfe321dca82f8892d29cd41fe8.js
Anonymous function [Line: 16, Col: 16564], vendor-11f60fbfe321dca82f8892d29cd41fe8.js

**Comment by bsclifton** [comment]
Can be reproduced by going to:

1. Load up IE 11 on Windows 8.1 (or using Remote IE)
2. Go to http://benz.guru
3. Click sign in, in the top right
4. Enter user/pass as bob@bob.com/Password1!
5. Error should happen

**Comment by bsclifton** [comment]
Site was built using `ember build --environment="production"`

Here's the part that makes narrowing it down tricky: I can edit my broc file like so...
```javascript
var app = new EmberApp({
    minifyJS: {
        enabled: false
    }
});
```
And I rebuild again... `ember build --environment="production"`
...and it works great :/ which makes me think there's an eval or something in there; basically something in which the variable/function name munging breaks IE

**Comment by mmun** [comment]
Can you get a stack trace with ember.debug.js?

**Comment by mmun** [comment]
and ideally isolate the bug to a JSBin so that we can rule out your app code.

**Comment by mmun** [comment]
Oops, just realized it wasn't happening with minifyJS disabled, seems bad :(

**Comment by bsclifton** [comment]
Thanks for the quick response; making a JSBin would be tough since it's using Ember CLI and like you noticed, it happens when it's minified

I got everything checked into a private Git, let me try stripping away bits and see if I can isolate the issue.  There's an identical version (except not minified) up at http://test.benz.guru

**Comment by bsclifton** [comment]
Got a minimal version of the site up here:
http://sandbox.benz.guru

I'm still stripping away as much as I can, hopefully isolate that error

**Comment by bsclifton** [comment]
Code is extremely stripped down. Logging in executes the following:
```javascript
var self = this, token = this.get('token'); //basic auth token
this.set('loading', true);
AjaxHelper.GET('/api/accounts/authenticate/%@'.fmt(token)).done(function (data, textStatus, response) {
    CookieHelper.set('email', 'bob@bob.com', false);
    CookieHelper.set('rememberMe', false, true);
    self.send('reloadAccount');
    self.transitionToRoute('index');

}).fail(function (response) {
    self.set('loading', false);
    switch (response.status) {
        case 404: self.handleFailure('Your email or password is incorrect.'); break;
        default: self.handleFailure('An unknown error occurred while processing your request. Please try again.'); break;
    }
});```

The reload account action is picked up by the Application route, which simply does:
```javascript
this.refresh();
```

That triggers the model() function being called again

**Comment by mmun** [comment]
Not sure if its related, but you should wrap your callbacks with Ember.bind to avoid autoruns.

**Comment by bsclifton** [comment]
Do you have an example of that? I'm not familiar with having to do that. I've done Ember.run for blocks of code that need to get fired after the run loop, is that what you meant?

**Comment by mmun** [comment]
It's not necessary. I see you are using ic-ajax which does it for you.

**Comment by bsclifton** [comment]
Actually, I'm just using a simple wrapper I wrote around $.ajax; could that be an issue?

**Comment by mixonic** [comment]
@bsclifton I'm not sure if this is related to your original issue, but this code is not using the runloop properly. It relies on jQuery's promises, which are not runloop safe. I suggest:

```javascript
//app/utils/ajax.js
import ENV from 'benz-guru/config/environment';
export default {
  POST: function (url, params) {
      return new Ember.RSVP.Promise(function(resolve, reject){
        $.ajax({
          type: 'POST',
          accepts: 'application/json',
          dataType: 'json',
          contentType: 'application/json; charset=utf-8',
          url: url,
          data: JSON.stringify(params),
          error: Ember.run.bind(null, reject),
          success: Ember.run.bind(null, resolve)
        });
      });
  },
  GET: function (url) {
    return new Ember.RSVP.Promise(function(resolve, reject){
      return $.ajax({
          type: 'GET',
          accepts: 'application/json',
          dataType: 'json',
          contentType: 'application/json; charset=utf-8',
          url: url,
          error: Ember.run.bind(null, reject),
          success: Ember.run.bind(null, resolve)
        });
      });
  },
  /// ...
```

Some guides for the runloop:

* http://stackoverflow.com/a/14296339/142061
* http://emberjs.com/guides/understanding-ember/run-loop/ 

But for now we should get make sure your code is correct so this can be ruled out as a possible cause.

**Comment by bsclifton** [comment]
Awesome, thanks for the heads up on that :)  I cleaned up all my $.ajax methods to be like that and then replaced my .done and .always handlers with .then (and tested).  It seems to make the issue happen more often now actually :disappointed: 

Latest version:
http://sandbox.benz.guru

**Comment by bsclifton** [comment]
Full source available here:
https://github.com/bsclifton/ember-issue-10622

**Comment by bsclifton** [comment]
Project source is fairly bare; I updated code to use ic-ajax since ember-cli-ic-ajax is being included by the default blueprints.

Going to go through the Ember source to track this down

**Comment by bsclifton** [comment]
Having a hard time finding the exact source, but in the compiled Ember.js 1.10 debug or prod source, the following lines are where it happens

```
enifed("morph/morph",
  ["exports"],
  function(__exports__) {
    "use strict";
    var splice = Array.prototype.splice;

    function ensureStartEnd(start, end) {
      if (start === null || end === null) {
        throw new Error('a fragment parent must have boundary nodes in order to detect insertion');
      }
    }

    //...

    // TODO: this is an internal API, this should be an assert
    function Morph(parent, start, end, domHelper, contextualElement) {
      if (parent.nodeType === 11) {
        ensureStartEnd(start, end);
        this.element = null;
      } else {
        this.element = parent;
      }
```

When the error occurs (inside the ensureStartEnd function), start is always populated with a #text DOM element and end is always null

**Comment by mixonic** [comment]
@bsclifton thanks for the research! If this is really only IE11 then you are likely wrestling with a bug in their DOM implementation. I'd like to find time to take a look after we get this release out.

**Comment by bsclifton** [comment]
Could definitely be- keep in mind, the error can be avoided by me setting minifyJS to false in my brocfile... definitely weird if that causes a DOM issue

**Comment by bsclifton** [comment]
Upgraded to Ember CLI 0.2.3 which uses Ember 1.11; now I'm getting this error:
`Unable to get property 'insertBefore' of undefined or null reference`

Easy to reproduce with IE live on http://sandbox.benz.guru

**Comment by bsclifton** [comment]
Upgrading to Ember 1.12 fixed the issue (per previous comment, upgrading to 1.11 did not). Closing the issue :smile:
