### ISSUE TITLE
Cannot name route "object"

### ISSUE THREAD

**Issue by axeljohnsson** [emberjs/ember.js#10623]
I'm using Ember CLI 0.2.0 with Ember 1.10.0. I want to name my route "object" but it doesn't work.

This is the error message:
```
"Error while processing route: object" "controller._updateCacheParams is not a function" "Route<.setup@http://localhost:4200/assets/vendor.js:34194:13
applyHook@http://localhost:4200/assets/vendor.js:60667:16
callHook@http://localhost:4200/assets/vendor.js:60661:14
handlerEnteredOrUpdated@http://localhost:4200/assets/vendor.js:59420:7
setupContexts/<@http://localhost:4200/assets/vendor.js:59387:18
forEach@http://localhost:4200/assets/vendor.js:60551:54
setupContexts@http://localhost:4200/assets/vendor.js:59386:9
finalizeTransition@http://localhost:4200/assets/vendor.js:59561:9
getTransitionByIntent/newTransition.promise<@http://localhost:4200/assets/vendor.js:58991:16
tryCatch@http://localhost:4200/assets/vendor.js:60990:16
invokeCallback@http://localhost:4200/assets/vendor.js:61002:17
publish@http://localhost:4200/assets/vendor.js:60973:11
@http://localhost:4200/assets/vendor.js:39112:9
Queue.prototype.invoke@http://localhost:4200/assets/vendor.js:11403:11
Queue.prototype.flush@http://localhost:4200/assets/vendor.js:11468:13
DeferredActionQueues.prototype.flush@http://localhost:4200/assets/vendor.js:11273:13
Backburner.prototype.end@http://localhost:4200/assets/vendor.js:10698:11
Backburner.prototype.run@http://localhost:4200/assets/vendor.js:10753:15
Backburner.prototype.join@http://localhost:4200/assets/vendor.js:10772:18
run.join@http://localhost:4200/assets/vendor.js:27228:14
run.bind/<@http://localhost:4200/assets/vendor.js:27280:16
jQuery.Callbacks/fire@http://localhost:4200/assets/vendor.js:3345:10
jQuery.Callbacks/self.fireWith@http://localhost:4200/assets/vendor.js:3457:7
.ready@http://localhost:4200/assets/vendor.js:3669:1
completed@http://localhost:4200/assets/vendor.js:3700:3
"
```
Is this something you've seen before? I do realize that "object" could be a reserved word, I just want to check.

jsbin: http://jsbin.com/gecacumave/1/edit?html,js,console

**Comment by rwjblue** [comment]
There are a few reserved route/resource names: object, array, basic, application.

A much better error message has been added to beta (and will be released in 1.11.0 soonish).  The error message says:

```
Assertion Failed: 'object' cannot be used as a route name
```

JSBin here: http://jsbin.com/doboli/1/edit?html,js

---

I would prefer not to have these reserved words at all, but I'm going to close this as this is already much better (messaging wise).

**Comment by axeljohnsson** [comment]
I see, OK. Great, thank you @rwjblue!

**Comment by ksnyde** [comment]
@rwjblue I'm still on 1.11.3 so am getting the old message, however I'm still uncertain why I'd be getting this error on routes called 'new' and 'show'. Also, strangely if I an explicit index controller I also get this error but the auto-generated one is fine. I've written this up with screen shots and full description on SO: http://stackoverflow.com/questions/30018815/updatecacheparams-is-not-a-function
