### ISSUE TITLE
Add wrapperClass to Component

### ISSUE THREAD

**Issue by johnnyshields** [emberjs/ember.js#10624]
It seems like there are certain cases where you'd want to wrap a certain components with a div for CSS purposes.

For example, I'd like to extend `Ember.Select`, but wrap it with a `<div class="select-wrapper">` for CSS styling purposes (specifically to add my own arrow design). Currently I have to do this in the template outside my component, but it would be much nicer to encapsulate this in the component itself.

Thoughts?

**Comment by stefanpenner** [comment]
this isn't something we plan to support directly, for now you can merely wrap it in another component that has this struture
