### ISSUE TITLE
2-stage ember testing helper - how to cleanup at end of test?

### ISSUE THREAD

**Issue by Twinkletoes** [emberjs/ember.js#10629]
I'm trying to build a clean test helper for Pretender. I want to be able to write
```
test('adapter makes correct API call', function (assert) {
  assert.expectAjaxGet({
    path: '/api/save',
    query: {
      id: 794,
      name: 'Steve',
  },
  {  // optional response
    200, 
    {'headers': 'go here'},
    {'response-body': 'goes here'}
  });

  adapter.save();

  assert.verifyAjaxCalls();
});
```

In my test helpers I do
```
Ember.Test.registerHelper('expectAjaxGet', 
	function (app, expectation, response)
	{
		// 1. add expectation to a list in app
		// 2. setup pretender and register expectation
		// 3. when call comes in, add it to a list in app

		// SOMEHOW, REGISTER HANDLER FOR TEST SHUTDOWN
		// TO CLEAN UP PRETENDER AND APP
	}
);

Ember.Test.registerHelper('verifyAjax', 
	function (app, expectation, response)
	{
		// check actual calls against expected calls (from lists in app) and assert
	}
);
```

Question is, how can the test helper guarantee to run at the end of the test to clean up? I can clean up if verify is called, but if it's not called, then we leak memory and worse, we've mocked Ajax so future tests may fail.

**Comment by stefanpenner** [comment]
questions are better asked on Stackoverflow or discourse, likely stackoverflow as it is a much better venue then an issue tracker.

If during the course of exploring this a bug appears, please feel free to report back.
