### ISSUE TITLE
Async before a redirect causes an entry to be added to history

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#10643]
See a repro:

http://emberjs.jsbin.com/wonuwiyajo/1

In this example, clicking the link takes you:
- To the cat route. This performs async on the `model` hooks.
- To the `cat/index` route. This redirects to the `cat/tail` route.
- To the `cat/tail` route.

When you click "back", the app goes:
- To the `cat/index` route, which redirects to the `cat/tail` route

Instead, it should be sending the user back to the `index` route. This works correctly without the async `model` hook.

**Comment by rwjblue** [comment]
Working properly on beta/canary: 

[Update JSBin](http://emberjs.jsbin.com/sibotuq/1)

![working demo gif](https://cloud.githubusercontent.com/assets/12637/20183592/e1ffc45a-a733-11e6-99fa-2e8752794ba1.gif)
