### ISSUE TITLE
ember-routing-named-substates doesn't take into account ember-cli resolver structures

### ISSUE THREAD

**Issue by tim-evans** [emberjs/ember.js#10645]
I would like to use `clients/loading.hbs` as the loading state instead of `clients_loading.hbs`. I believe that both should be valid template names.

**Comment by tim-evans** [comment]
Nevermind, this seems like it's ok. It's just an organizational pain for me with tons of routes.

**Comment by tim-evans** [comment]
Changed my mind again :)

When using pods, I would like to be able have the following structure:

```
/clients
  |-- template.hbs
  |-- loading.hbs
  +-- error.hbs
```

**Comment by stefanpenner** [comment]
@tim-evans yes absolutely, now. I am inclined to believe this is a resolver glitch. But we should investigate further.

**Comment by tim-evans** [comment]
@stefanpenner thanks! I just think that this isn't handled in https://github.com/ember-cli/ember-resolver

**Comment by rwjblue** [comment]
`clients-loading/template.hbs` is the correct path, currently. I suppose we could special case `clients/loading/template.hbs`, but that prevents anyone from having an actual `loading` route of their own (which seems fairly bad).

**Comment by tim-evans** [comment]
I actually disagree with it being bad. Having substates that are 'clients-loading' means that if I'm going to add any customization to my app, I'd explode the number of routes by a factor of 3 at a given level. We have an app with around 20 top level routes. If I'm migrating from what we have to ember built-in structures, I'd like it not to make it impossible to figure out what's being rendered due to having difficulty finding the file.

**Comment by rwjblue** [comment]
Ember removing terms/names that you can use is definitely not good. There are no two ways about it.  If we make `clients/loading/template.hbs` work, to prevent it from being ambiguous, we would have to reserve `loading` and `error` as a route names. This is absolutely not backwards compatible (many apps I have looked at use a global route named `error` that is unrelated to substate behavior).

Perhaps we could use `clients/-{loading,error}/template.hbs` or `clients/-{loading,error}-substate/template.hbs` instead, but I do not think `clients/loading/template.hbs` (or `clients/loading.hbs`) can be made a framework level default in a 1.X series.

**Comment by tim-evans** [comment]
@rwjblue I agree with your concerns with making it the default for the 1.x series. I just want to make sure that the pain points of the naming scheme is heard :)

**Comment by thejameskyle** [comment]
> Perhaps we could use `clients/-{loading,error}/template.hbs` or `clients/-{loading,error}-substate/template.hbs` instead.

It'd make more sense to me to use `clients/_loading` and `clients/_error` to me since _kinda_ follows some existing naming schemes with `application_loading` and `application_error`.

**Comment by JKGisMe** [comment]
Was this ever changed?

So for pods we need two additional routes(routeName-loading, routeName-error) for each route?

**Comment by jasonmit** [comment]
Has this been resolved?

**Comment by rwjblue** [comment]
I believe that this is not really a bug. There are updated docs in https://guides.emberjs.com/v2.5.0/routing/loading-and-error-substates/ and I think we are happy to flesh them out even more if folks have time. 

I've also made a demo ember-twiddle showing various usages: https://ember-twiddle.com/a77b3db275d91c7f34c2?numColumns=0
