### ISSUE TITLE
ember-routing-named-substates doesn't work

### ISSUE THREAD

**Issue by tim-evans** [emberjs/ember.js#10644]
I was trying to get this working; looks like how the resolver is created changed:

The resolver in ember-cli sets `moduleBasedResolver` to `true`:
https://github.com/ember-cli/ember-resolver/blob/master/packages/ember-resolver/lib/core.js#L138

But the core resolver is masked behind a function:
https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/application.js#L1073
https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/application.js#L1100

**Comment by rwjblue** [comment]
`ember-routing-named-substates` will only work properly with modules based resolvers (due to ambiguities in the resolver results). This is why we check for the presence of the `moduleBasedResolver` property on the resolver instance.

If you **must** make this work in a globals scenario, you could set `moduleBasedResolver` yourself when instantiating your application. Something like:

```javascript
App = Ember.Application.create({
  Resolver: Ember.Resolver.extend({ moduleBasedResolver: true })
});
```

But this is definitely **not** advised (due to conflicting paths in the globals resolver).

**Comment by tim-evans** [comment]
To illustrate my problems:

https://github.com/tim-evans/ember-routing-named-substates

I encourage you to play with removing the configuration that I had to do to make named substates work,
specifically:

https://github.com/tim-evans/ember-routing-named-substates/blob/master/app/router.js#L10
https://github.com/tim-evans/ember-routing-named-substates/blob/master/app/initializers/patch-resolver.js

Removing these makes the feature not work at all.

**Comment by rwjblue** [comment]
I'll try to take a look at the demo app tonight...

**Comment by ZebraFlesh** [comment]
Not sure if this is helpful or just my lack of understanding about how to test substates; feel free to ignore if not helpful.

Indeed the solution from @tim-evans makes the named substates work, but for some reason I can't fathom all of my acceptance tests are now breaking. It looks like the application is not being correctly cleaned up with your standard ember acceptance test code:

````javascript
module('acceptance test', {
  beforeEach() {
    application = startApp();
  },

  afterEach() {
    Ember.run(application, 'destroy');
  }
});
````
From a test perspective, the only difference is swapping the resolver out and triggering a loading state as part of visit().
