### ISSUE TITLE
Upgrading to latest version of Ember beta broke backwards compatibility.

### ISSUE THREAD

**Issue by chrism** [emberjs/ember.js#10646]
After upgrading from Ember 0.11.0-beta.2 to Ember 0.11.0-beta.5 my app stopped working.

It was an error from Liquid Fire library - you can see the kind of issue from here:
https://github.com/ef4/liquid-fire/issues/190
`Shows error Uncaught TypeError: Cannot read property 'container' of undefined`

There is a fix on the master version of Liquid Fire for this now, but my understanding was that beta updates to Ember shouldn't break backwards compatibility & just be bugfixes.

Sorry if I misunderstand but wanted to raise this issue in case its useful for others.

**Comment by rwjblue** [comment]
The `this` context in helpers was not previously specified as an API (it has changed a number of times throughout 1.x series).  In the initial HTMLBars effort we decided to change the helper context from the controller to the view (around Ember 1.9.0), but then in preparation for implementing Glimmer on top of HTMLBars it became clear that we could not guarantee `this` would always be the view instance so we change the `this` context to be `undefined`.

@chrism - In short, the context was not public API (even though some helpers relied upon it). This change is annoying (and I am sorry it caused you trouble), but necessary for continued progress forward.

**Comment by chrism** [comment]
@rwjblue Thanks (as always) for your clear explanation of the issue and reasons behind it.

I have rolled back to using Ember 0.11.0-beta.2, which is fine for me & just means I'm not really able to offer any feedback in beta testing this version.

Am really excited for glimmer (and fastboot) — many thanks for all your hard work on Ember, it really is an incredible achievement.

**Comment by jbrown** [comment]
@chrism I had the same issue and got it working by pointing to this commit on master. ef4/liquid-fire#187
