### ISSUE TITLE
Running destroy in a test teardown causes injected to show isDestroying true

### ISSUE THREAD

**Issue by toranb** [emberjs/ember.js#10656]
I have a simple app that invokes destroy using the run loop between tests like you would expect

```js
module('Acceptance: Moving', {
    setup: function() {
        application = startApp();
    },
    teardown: function() {
        Ember.run(application, 'destroy');
    }
});
```

My example route has a class injected into it like so

```js
var PeopleRoute = Ember.Route.extend({
    repository: Ember.inject.repositories('person'),
    model: function() {
        var repository = this.get('repository');
        return repository.find();
    }
});
```

This inject func is setup in a simple initializer like so

```js
export function initialize(container, application) {
    application.register("repositories:person", PersonRepository);
    application.inject("repositories", "store", "store:main");
    Ember.inject.repositories = function(name) {
         return function(propertyName) {
             var objectName = name || propertyName;
             return container.lookup("repositories:" + objectName);
         }.property();
    };
}
```

If I don't invoke the destroy between tests all is good. But ... if I try to run > 1 test destroy seem to kill this injected class (or a reference) at some point. I'm not sure if this is a true bug w/ the way destroy works or if I've just done something completely wrong in the initializer shown above. 

Either way - to reproduce this I threw together a simple ember-cli app (branch) that will console log the injected class each time the test runs. The first time you get a normal class as you'd expect ... but after the destroy runs you get something else entirely (during the 2nd test run)

https://github.com/toranb/ember-cli-store-dirty-tracking-example/blob/destoryBreaksTheThings/app/routes/people.js#L7

**Comment by toranb** [comment]
Also - using ember.js 1.11 beta 5 (plus ember-cli 0.2.0 stable)

**Comment by stefanpenner** [comment]
you are trolling yourself:

https://github.com/toranb/ember-cli-store-dirty-tracking-example/blob/destoryBreaksTheThings/app/initializers/repositories.js#L10

container is closed over, but you are over-writing by `Ember.inject.factories`

instead keep them separate
```js
export function initialize(_, application) {
    application.register("repositories:person", PersonRepository);
    application.inject("repositories", "store", "store:main");
};
```

and use the local (but remember power-user/private reference to container)
```js
Ember.inject.repositories = function(name) {
 return function(propertyName) {
   var objectName = name || propertyName;
   return this.container.lookup("repositories:" + objectName);
 }.property();
};
```

even better, don't put anything on the `Ember.inject` global, make a local module for it.

**Comment by toranb** [comment]
Wow what a detailed reply! Thank you 100x Stef !!!

**Comment by stefanpenner** [comment]
no problem, did my explanation make sense?

**Comment by toranb** [comment]
The only part I didn't yet understand is shown below (my assumption was to skip past it as you mentioned in the final solution). I still have some source diving to do yet before I grok the factory stuff :)

```
but you are over-writing by Ember.inject.factories
```

**Comment by williamsbdev** [comment]
I am also curious about this Ember.inject.factories over-writing. We are not over-writing any of the keys that are on the Ember.inject API (service or controller) and I was unable to find where Ember.inject.factories is exposed in the source.

Thanks for the quick answer on this question!

**Comment by rwjblue** [comment]
Issues that I see with this technique:

* Mutating a non-owned global === **BAD** -- Ember could change the way `Ember.inject` works in the future, and mutating it is **not** a good idea.
* The semantics of the monkey-patch are not the same as the rest of `Ember.inject` --  `Ember.inject.xxxx` does factory validation at class lookup time.  This ensures that if you are missing a collaborator it errors *before* you call the injected property.  In your example, if the lookup does not find anything the result of the computed property is `undefined` (what `container.lookup` returns when nothing was found).

**Comment by rwjblue** [comment]
What you have implemented will likely work fairly well for you, but it should be imported from your userland code and used. Not be inferred to come from Ember itself.  When you open this codebase after a few months away from it, will you remember where `Ember.inject.repositories` is coming from?  Will a new developer thing that joins this team realize that this isn't an Ember feature or will they try to track down in our API docs/guides where this is coming from?

I'd suggest something like the following:

```javascript
// app/utils/inject-repositiory
export default function(name) {
  return function(propertyName) {
    var objectName = name || propertyName;
    return container.lookup("repositories:" + objectName);
  }.property();
};
```

```javascript
import Ember from 'ember';
import injectRepository from '../utils/inject-repository';

var PeopleRoute = Ember.Route.extend({
    repository: injectRepository('person'),
    model: function() {
        var repository = this.get('repository');
        return repository.find();
    }
});
```

**Comment by stefanpenner** [comment]
> // app/utils/inject-repositiory

this is also more of a lookup, then an inject as it lacks the construction time validation.

**Comment by williamsbdev** [comment]
@rwjblue Thanks for the insight. I did see that Ember.inject.xxxx does the factory validation and would really like to have that functionality. I am curious if the Ember.inject API will ever be opened up so that we will be able to add our own keys/objects to be injected?

One of the reasons that I liked the monkey patch was that I did not have to do a special import for my own injection as I should have Ember in all the files that I would be trying to do the injection.

I understand what you are saying about the new developers being confused on this not being first class in the Ember.inject API and instead our own injection. Because of this, I will steer away from Ember.inject.

@rwjblue and @stefanpenner Thank you for your time!

**Comment by rwjblue** [comment]
> I am also curious about this Ember.inject.factories over-writing. We are not over-writing any of the keys that are on the Ember.inject API (service or controller) and I was unable to find where Ember.inject.factories is exposed in the source.

Not yet :wink:

**Comment by rwjblue** [comment]
> I am curious if the Ember.inject API will ever be opened up so that we will be able to add our own keys/objects to be injected?

I would like to expose it (and had issued a pull request to do so just before 1.10 shipped), but we are not sure that part of the API is ready for userland extension to their own factory types.

> One of the reasons that I liked the monkey patch was that I did not have to do a special import for my own injection as I should have Ember in all the files that I would be trying to do the injection.

Importing code that you wrote is not something to avoid, rather it is exactly the thing to embrace.  

> I understand what you are saying about the new developers being confused on this not being first class in the Ember.inject API and instead our own injection. Because of this, I will steer away from Ember.inject.

I am not saying that using `Ember.inject` is a bad thing (on the contrary I think it is a very good feature), what I am saying though is that creating a new (and different) concept but adding it to seem like an Ember feature will be confusing and potentially cause problems for you in the future.

**Comment by williamsbdev** [comment]
@rwjblue I am really excited how the Ember.inject API evolves and especially for it being exposed in userland. :)

I want to clarify my statement

> I understand what you are saying about the new developers being confused on this not being first class in the Ember.inject API and instead our own injection. Because of this, I will steer away from Ember.inject.

After reading this again, and your response, there was some miscommunication on my part. I will steer clear of the Ember.inject API for the stuff that I am doing and use the function that you and @stefanpenner provided for the injection. I want to fully embrace and explore the new Ember.inject API for how it is today and what it can be in future versions.

Thank you for breaking down each part of my response with answers.

**Comment by rwjblue** [comment]
Ahh, gotcha, now I see what you mean. Sorry for the miscommunication there...
