### ISSUE TITLE
options.helperName is undefined when makeBoundHelper invokes viewHelper

### ISSUE THREAD

**Issue by rvan1** [emberjs/ember.js#10653]
In a non-CLI (grunt) ember app, I have an Ember.TextField, in a view bound to an 'arrivalDate' property, and a viewHelper created with 'Ember.Handlebars.makeBoundHelper(function(options)'. The helper checks the navigator.userAgent and changes hash.type 'input' to 'date' if using mobile device browser (so binds to the devices native datepicker). Now with ember 1.10 and HTMLBars compiler, I have to change 'return Ember.Handlebars.helpers.view.call(this, DateInputView, options)' to 'return Ember.Handlebars.helpers.view.helperFunction.call(this, DateInputView, options)' because the 'view.call()' method has moved. But now when I compile I get 'options is undefined'. This happens in ember 'viewHelper() method where it references 'options.helperName'. So I DO have 'options' with 'options.hash', but 'hash' is missing properties it had like boundOptions, onEvent, valueBinding. I have no helperName (view), contexts, hashContexts, hashTypes, types and the data obj is different. I'm not able to set options.helperName in the helper, so is obviously set earlier such as by the Resolver as it wires up the View. It seems like my viewHelper (or input helper) needs to be wrapped by something else to fill in all the missing properties.

**Comment by rwjblue** [comment]
Calling another helper from within a `makeBoundHelper` helper is not really supported. I'd suggest changing this setup to a tiny component.  It would be much more future proof and relies on less internal privateish API's.

Demo: http://emberjs.jsbin.com/rwjblue/348/edit

**Comment by rwjblue** [comment]
If the above comment doesn't help, please provide more details (preferably with a JSBin demonstrating the issue) and I'm happy to reopen...

**Comment by rvan1** [comment]
Our 3rd party partner, who got us on ember, and who is no longer our
partner, developed it that way & apparently was once supported.

I know everyone is demoing things with jsbin, but I have no idea how to do
that.

I've already rewritten the date-input as a component as well as happened on
a blog which says that viewHelpers are going away and is best to do most
things with components, so seems I've figured that much out.

On Sat, Mar 21, 2015 at 7:05 PM, Robert Jackson <notifications@github.com>
wrote:

> If the above comment doesn't help, please provide more details (preferably
> with a JSBin demonstrating the issue) and I'm happy to reopen...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emberjs/ember.js/issues/10653#issuecomment-84494023>.
>



-- 
Best Regards,

Bob Van
