### ISSUE TITLE
Mismatched value of a computed property that is attributebound

### ISSUE THREAD

**Issue by richardbowman** [emberjs/ember.js#10654]
If you use a computed property on a property that is attribute-bound and can be changed by the browser, there is a situation in which the property can become desynchronized from the browser's value.

For instance, the `value` property of a `TextField` component. For example, let's say the value in the text box was "0", and then the user blanks it out. In the computed property, when the set call occurs, we check for blank and return "0" again as the desired value. Ember decides the cached value matches, and correctly returns "0" from the `value` property, but never goes back and updates the text box in the DOM to actually match, so the text input still shows blank.

**Comment by rwjblue** [comment]
I'm not sure I fully follow, can you throw together a JSBin that demonstrates this?

You can use http://emberjs.jsbin.com/rwjblue/248/edit?html,js,output as a starting point if you need a base JSBin...

**Comment by richardbowman** [comment]
To replicate the issue, just remove the value "1" in the textbox. It should change to zero the first time. Then remove that zero, and it will not replace it again with zero, instead it will just go to blank. If you put a new value in, you can keep repeating the scenario: 

http://emberjs.jsbin.com/rwjblue/248/edit?html,js

If you agree this is an issue, I have a test I could submit that replicates it too.

**Comment by stefanpenner** [comment]
Although strange this appears to be working as expected. If instead the example was written using data-down, actions up. It should work as expected
