### ISSUE TITLE
Root template ignored by router in 11-beta.5

### ISSUE THREAD

**Issue by sandstrom** [emberjs/ember.js#10658]
With 1.11 beta 5 the 'root' template/view is ignored in my route hierarchy. Images and code below (let me know if  I should clarify further).

Possibly after this change (haven't bisected though): https://github.com/emberjs/ember.js/commit/ba1d1a61731ca3f34f998ac122e65e3703dd6bb0

cc @ef4 Edward, any thoughts on what may cause this?
(I'm happy to provide more details, jump on Screenhero or similar)

```
// router
Router.map(function() {
  // ...
  this.resource('exports', function() {
    this.route('history');
  });
  // ...
});

// export route
// ...
renderTemplate: function() {
  this.render('exports/root');
},
// ...

// export index route
// ...
renderTemplate: function() {
  this.render('exports/index');
},
// ...
```

***
**Routes (same in both versions)**
![routes](https://cloud.githubusercontent.com/assets/122287/6711959/5e56c268-cd8a-11e4-958f-16daa4b1c40c.png)

**With 1.8**
![views-e1 8](https://cloud.githubusercontent.com/assets/122287/6711963/63b11a7e-cd8a-11e4-93d2-cdf8fa3dc691.png)

**With 1.11-beta5**
![views-e1 11b](https://cloud.githubusercontent.com/assets/122287/6711964/6785b114-cd8a-11e4-8a10-c2d5b9c54eb6.png)

**Comment by alexdiliberto** [comment]
Also going to put this here because I believe it's related https://github.com/emberjs/ember.js/issues/10602

**Comment by ef4** [comment]
I have a fix for this on in https://github.com/emberjs/ember.js/pull/10683

**Comment by sandstrom** [comment]
@ef4 That solved it, thanks Edward! :boat:
