### ISSUE TITLE
Audio is still playing after audio tag is removed from the DOM (second time).

### ISSUE THREAD

**Issue by SeyZ** [emberjs/ember.js#10651]
I have an audio tag in a route. When transitioning to this route the second time, the audio is still playing.
The bug appears in Ember `1.10.0`. I tested on the `1.9.0` version and it works well.

Here's a Ember JsBin to reproduce the problem: 

Ember v1.10.0 (not working). To reproduce, you need to transitionTo multiple times.
http://emberjs.jsbin.com/solobeliyu

Ember v.1.9.0 (working).
http://emberjs.jsbin.com/jaburi

**Comment by stefanpenner** [comment]
this actually seems like a browser bug?

**Comment by SeyZ** [comment]
Chrome and Firefox have the same behavior.

**Comment by alexdiliberto** [comment]
I'm seeing this issue reference in many browser bug reports. If you handle it in your route it would work...here's a crude implementation

http://jsbin.com/mukawa/2/edit?html,js,output

**Comment by SeyZ** [comment]
I have another workaround (using component). http://jsbin.com/rijiko/1/edit?html,js,output

Thoughts?

**Comment by stefanpenner** [comment]
this seems like a browser bug :(
