### ISSUE TITLE
Update documentation for 1.9 deprecations around context-switching blocks.

### ISSUE THREAD

**Issue by jdhines** [emberjs/ember.js#10659]
Just ran into this, probably because I'm still learning all this, but I have a sample application template and route, with a model defined on the route, and I was trying to transition from the context-switching `each` syntax. Following the instructions [here](http://emberjs.com/guides/deprecations/) I thought all I had to do was update my template, only to find that nothing rendered, and no console errors were given.

Here's a [gist](https://gist.github.com/jdhines/6ed644f21b680f35ec80) of what I tried, as well as my solution, which Grapho clued me in to.

I admit that this might be just due to my lack of really grokking how the template, route, and controller interact, but still I think it would be helpful to have a line there that the 'x' in `{{#each something in x}}` is referencing the controller, not what I named the return value in my route's model hook, which I realize sounds like a dumb thing to do to you pros, but I'm really learning JS along with Ember.

So maybe just an additional, alternative code block that uses the syntax of `{{#each something in model}}`

**Comment by jdhines** [comment]
Made a pull request to add an example that uses 'model': [2072](https://github.com/emberjs/website/pull/2072)

**Comment by rwjblue** [comment]
deprecation guides include context switching `{{with}}` and `{{each}}` information now.
