### ISSUE TITLE
Position of newly inserted element is incorrect at serialization time (in the snapshot) in beta.15

### ISSUE THREAD

**Issue by plcarmel** [emberjs/ember.js#10666]
This problem is present in ember-data 1.0.0-beta.15 but not in beta.14

Lets say we have a post object that contains an array of comments and the way we order the comments is by serializing the list of ids.

// models/post.js:
import DS from "ember-data";

export default DS.Model.extend({
  title: DS.attr('string'),
  comments: DS.hasMany('comment', { async: true })
});

// serializers/post.js:
import DS from "ember-data";

export default DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    products: {
      serialize: 'ids',
      deserialize: 'ids'
    }
  }
});

// Lets say we are in a controller and we want to change the position of a comment from 5 to 1:
var comments = this.get('comments');
var theComment = comments.objectAt(5);
comments.removeAt(5);
comments.insertAt(1, theComment);
// So far so good, the comment that was at position 5 is now at position 1 in the array
this.get('model').save()
// The problem is that, at serialization time (in the snapshot), the comment that was inserted at position 1 ends up being at the end of the array instead of being at the correct position.

That problem was not present in ember-data beta.14

At hack I tried to get the correct behavior is to clear the array of comments and insert them back in the desired order instead of doing a removeAt and then an insertAt operation.  However, it causes flickers on the screen because of the rerendering.

**Comment by rwjblue** [comment]
This sounds like an Ember Data issue, can you open it over at https://github.com/emberjs/data/issues instead?  Sorry for the trouble...

**Comment by plcarmel** [comment]
Done.
