### ISSUE TITLE
No model update from PUT request result in beta.15

### ISSUE THREAD

**Issue by plcarmel** [emberjs/ember.js#10665]
ember-data 1.0.0-beta.15 is not updating the model from the result of a PUT request anymore.

I downgraded ember-data to 1.0.0-beta.14 and the bug is not present in this version.

**Comment by btecu** [comment]
You may want to open the issue here https://github.com/emberjs/data/issues

**Comment by rwjblue** [comment]
@btecu is correct, can you open an issue on the Ember Data repo instead?

**Comment by plcarmel** [comment]
Ok, sorry about that.

**Comment by rwjblue** [comment]
No worries!
