### ISSUE TITLE
TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by givanse** [emberjs/ember.js#10674]
Tried to build master (44d5f188c96a7e94bb977b07558c93fda192232d) and got:

    Cannot convert a Symbol value to a string
    TypeError: Cannot convert a Symbol value to a string
        at RegExp.test (native)
        at Symbol.hasOwnProperty (/home/ivan/programming/ember.js/node_modules/emberjs-build/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:163:43)

Related, but closed: https://github.com/ember-cli/ember-cli/issues/2991

    node -v
    v0.12.0
    npm -v
    2.5.1

**Comment by rwjblue** [comment]
Can't use node > 0.10 while building this repo. 

Issue is with embarjs-build and will be tracked at: https://github.com/emberjs/emberjs-build/issues/87

**Comment by stefanpenner** [comment]
I'm making progress upgrading all our deps, so that we can upgrade ember. but fixing tooling issues as I go.
