### ISSUE TITLE
custom component creates empty dummy html tag NOT including actual content. 

### ISSUE THREAD

**Issue by kajafon** [emberjs/ember.js#10685]
i have something like this :

MyComponent = Ember.Component.extend({
  layoutName: 'my_layout',
  tagName: 'p'
  classNames: ['what-is-wrong-with-this-technology']
})

layout:

&lt;div&gt; my payload &lt;/div&gt;

rendered html:

&lt;p class="ember-view what-is-wrong-with-this-technology"&gt;
... some ember stuff ... 
&lt;/p&gt;
&lt;div&gt; my payload &lt;/div&gt;
 
i tried to remove tagName, because i don't really need it, but than something else tragically broke up and i decided not to dive into that for sake of my sanity. so i am back with my displaced tagNamed component. Any ideas to get sheep back to yard? Actually i want to manipulate child tags of component  but i can't because this.get('element') returns that empty dummy tag. there are nasty ways to do that but hey, its 21st century ... this shouldn't be so ...

**Comment by lolmaus** [comment]
Uhm, isn't `layoutName` deprecated for components?

**Comment by OrKoN** [comment]
@kajafon which version do you use? Seems to be working with Ember 1.10 http://emberjs.jsbin.com/vuwavadabi/1/edit?html,css,js,console,output

@lolmaus I have some components that use layoutName w/o any deprecations (Ember 1.11-beta.5) Do you know when it was/will be deprecated?

**Comment by rwjblue** [comment]
You are specifying that your component's tag is a `<p>`, but that can only contain phrasing content (which a `<div>` is not). Take a look at this JSBin with plain HTML showing that the browser is correcting your "invalid" markup to create the extra elements: http://jsbin.com/noduci/1/edit?html,output

* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p
* https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content

**Comment by kajafon** [comment]
rwjblue: thanks, that's REALLY surprising. i would have never expected this.

**Comment by stefanpenner** [comment]
Oh html. You so crazy

**Comment by lolmaus** [comment]
@OrKoN, i heard about it somewhere in the issue queue. I tried to google it up and failed. The official deprecation page does not mention it.

But i found this: http://emberjs.com/api/classes/Ember.ComponentTemplateDeprecation.html

If i understand it correctly, the case is the opposite: `templateName` is deprecated in favor of `layoutName` for components. Please correct me if i'm wrong.
