### ISSUE TITLE
Replacing item in bound array renders it briefly without it

### ISSUE THREAD

**Issue by dj-hedgehog** [emberjs/ember.js#10694]
I've got a playlist with artwork images. When I click on one the old current track is taking their place. Therefore I replace the item in the array.

When Ember re-renders the items for a very brief moment the replaced element disappears. This leads to an ugly effect where everything is re-positioned.

I made a JSFiddle only using jQuery but couldn't reproduce this behaviour http://jsfiddle.net/bhn8bko1/2/

**You can see the effect here**

- Go to http://ali.dj/blog
- Click on one of the three playlist-images 

This is my simplified **controller**:

    import Ember from 'ember';
    
    export default Ember.ArrayController.extend({
    
      playlist: null,
      currentTrack: null;
      actions: {
        replaceItem: function(){
          playlist.replace(index, 1, [self.get("currentTrack")])
        } 
      }
    }

This is the **template**:

    {{#each song in playlist}}
      <div class="song" {{action "changeTrack" song}}>
        <img {{bind-attr src=song.artwork_url}} />
      </div>
    {{/each}}

**Comment by stefanpenner** [comment]
using liquid-fire is the best possible way to get really good affects like this. Basically liquid-fire keeps the dom around long enough to do the animations cleanly. I would strongly recommend that approach is taken for animation.
