### ISSUE TITLE
Wrong context in custom handlebars helper

### ISSUE THREAD

**Issue by vvs-code** [emberjs/ember.js#10692]
Ember version - 1.9.1
Relative links:
http://stackoverflow.com/questions/29182806/ember-handlebars-boundif-didnt-call-calculated-property
http://discuss.emberjs.com/t/ember-handlebars-helper-doesnt-work-on-big-progect/7591
Note: code works fine at ember 1.7.0-beta.1.

I work on updating ember version and got an error - can-helper didn't call computed properties function

on debug i found that it's try search property in controller, but i override context on using boundIf helper

Helpers code is next ( i use ember-cli but the same when i use standart Ember.Handlebars.registerHelper at app.js )

````
var get = Ember.get, isGlobalPath = Ember.isGlobalPath, normalizePath = Ember.Handlebars.normalizePath,
  IS_BINDING = Ember.IS_BINDING;

export default function(permissionName, property, options) {
  var attrs, context, key, path, permission;

  // Here some logic 
  // find & create the permission with the supplied attributes
  permission = this.get('container').lookup('permissions:main').get(permissionName, attrs);
  // permission - instance of Ember.Object with computed property which didn't call

  // ensure boundIf uses permission as context and not the view/controller
  // otherwise it looks for 'can' in the wrong place
  options.contexts = null;

  this.unknownProperty = function(/* propName */) {
    // We'll stop here with propName === 'can'
   // below you can find stacktrace 
    debugger;
  }
  
  // bind it all together and kickoff the observers
  return Ember.Handlebars.helpers.boundIf.call(permission, "can", options);
}
````

To give more information  - stacktrace for debugger statement in unknownProperty

````
exports.default.unknownProperty (can.js:69)
get (ember.js:17589)
merge.valueFn (ember.js:38882)
Stream.value (ember.js:18657)
read (ember.js:18519)
merge.valueFn (ember.js:18565)
Stream.value (ember.js:18657)
read (ember.js:18519)
merge.valueFn (ember.js:38867)
Stream.value (ember.js:18657)
bind (ember.js:7576)
boundIfHelper (ember.js:8488)
exports.default (can.js:73)
````

**Comment by vvs-code** [comment]
Sorry if i post issue to the wrong place. I'm ready to move it were it should be

**Comment by rwjblue** [comment]
The `this` context inside of helpers has changed in various versions:

* `this` was the controller in 1.0.0 through 1.8.0
* `this` was the view in 1.9.0 and 1.10.0
* `this` is `undefined` in 1.11+

My guess is that the context change in 1.9 is causing this error, updating your helper to add the `unknownProperty` to the controller will fix the issue.

**Comment by vvs-code** [comment]
Thanks for information. What about fact that is set context manually with .call(need_context, params) ?

This should force setup need context

As i understand your message - the chenges shouldn't vary behavior of my code ( inside helper function i didn't use 'this' )

I call 
```
return Ember.Handlebars.helpers.boundIf.call(permission, "can", options);
```
but unknownProperty called on this ( whatever it is ) not on permission object ( permission has can property )

**Comment by vvs-code** [comment]
Into internal bind method passed right context, but then ember work with SimpleStream instance -  
````
      var view = data.view;

      // we relied on the behavior of calling without
      // context to mean this === window, but when running
      // "use strict", it's possible for this to === undefined;
      var currentContext = this || window;

      var valueStream = view.getStream(property);
````
- possible you talk about this ) and i can't guess logic on this manipulation. 

If so - can you give proposal how i can bound on object which not in current scope ( early it was possible )

Thanks

**Comment by vvs-code** [comment]
My current solution for this problem - i define unknownProperty which contains logic to find permission and return it's value ( early i work with PHP ant there it was magic method __get ) but i hope to find better way to solve it

**Comment by andrewfan** [comment]
@rwjblue can you please explain what it the best practices for working with custom helpers now?
Looks like documentation http://guides.emberjs.com/v1.11.0/templates/writing-helpers/ shows only the simplest examples.

**Comment by aroberts** [comment]
This documentation would be very helpful. I noticed that in 1.12.1 `this` in my helper is now pointing to a `_MetamorphView` instance, and `options.data.view` is not populated. Are we headed for stability on this issue?

**Comment by rwjblue** [comment]
As of 1.13 we have introduced official public API for these types of helpers. Take a look at `Ember.Helper` documentation, and RFC.
