### ISSUE TITLE
block param description on 1.10 and beta 1.11 release blog is confusing

### ISSUE THREAD

**Issue by mgenev** [emberjs/ember.js#10702]
http://emberjs.com/blog/2015/02/07/ember-1-10-0-released.html

Or it's that the syntax itself is confusing, but in my opinion, this makes no sense:
``` {{#x-customer customer=model birthday=model.birthday as |name age|}}```

It doesn't make it clear what 'as' refers to exactly -  customer, birthday, both, the component itself as 2 named properties? 

And does the order matter?

**Comment by mixonic** [comment]
@mgenev this syntax has shipped, and was debated rather extensively during design https://github.com/emberjs/rfcs/pull/3 Feel free to dig around in that discussion to better understand the motivations. There are some really good reads.

This question might be better for StackOverflow or IRC though.

Block params are yielded in to the nested scope from the layout. So for `|name age|` the layout of the component has called `{{yield someName model.someAge}}`.

We should improve the docs for this, but this repo is not the place for the discussion. Thanks!

**Comment by mgenev** [comment]
Thanks. So where is the place to report confusing or incomplete docs for ember?

**Comment by lukemelia** [comment]
@mgenev changes to API docs are PRs against this repo. Changes to the guides on the website are PRs against https://github.com/emberjs/guides

**Comment by mgenev** [comment]
@mixonic there actually is no justification in this rfc you linked for the confusing syntax, there was a much more logical variant offered and there was no explanation how
 ```<x-component blah={{meh}} as |a b c|>```
is better than:
```
<todays-date yields day month year>
  {{day}} / {{month}} / {{year}}
</todays-date>
```
Which right away makes it obvious what's going on, unlike what was shipped.

**Comment by lukemelia** [comment]
@mgenev there was extensive and good bikeshedding on the topic. Following that, a decision was made by the core team members who implemented the feature, and now we are a small number of days from shipping a stable release with the syntax. I think it be appropriate at this point to observe it in the wild for a while. Complaining about it at this particular juncture is likely unproductive.
