### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by pixelterra** [emberjs/ember.js#10708]
The docs at http://emberjs.com/guides/concepts/naming-conventions/ say:

"The rule of thumb is to use resources for nouns, and routes for adjectives (favorites) or verbs (edit)."

I just wanted to point out that "favorites" here is a noun, not an adjective.

**Comment by rwjblue** [comment]
This whole section needs to be reworked to remove usage of `resources` completely.  Can you re-open the issue on https://github.com/emberjs/guides?

**Comment by thejameskyle** [comment]
@rwjblue Created a new issue over here: https://github.com/emberjs/guides/issues/131

**Comment by rwjblue** [comment]
Awesome, thank you!
