### ISSUE TITLE
Ember.View.render removes certain tags from the buffer

### ISSUE THREAD

**Issue by robertolicious** [emberjs/ember.js#10707]
For some reason I am not able to use `td` and `tr` tags.
 
    import Ember from 'ember';
    export default Ember.View.extend({

        render: function(buffer) {
            buffer.push('<td>this does not work</td>');
        }

    });

I'm looking at the DOM in Chrome and can see that it creates divs, but no rows or cells.

This however works:

    import Ember from 'ember';
    export default Ember.View.extend({

        render: function(buffer) {
            buffer.push('<b>this works and is bold</b>');
        }

    });

Is this a bug or a feature? In case it is a feature, what is the common way to work around this? My View is logic heavy and I can't do it in Handlebars alone.

**Comment by mixonic** [comment]
@robertolicious Ember views are `div` tags by default. In your first snippet, you are pushing adding a `td` tag to a `div` via `innerHTML`. This is not permitted (by browsers and HTML), instead you should make the view a `tagName: 'tbody'` or another permitted parent for a `td` tag.

**Comment by robertolicious** [comment]
Thank you! This is exactly what I was looking for. Never found a use case for `tagName` until now!
