### ISSUE TITLE
Second call to {{render}} within the same template fails

### ISSUE THREAD

**Issue by andrewjmc** [emberjs/ember.js#10710]
Please see this code which works in the current release of Ember, but not in the current beta.

http://jsfiddle.net/yymrk2z3/

The error given is:

`Assertion Failed: You cannot provide a template block if you also specified a templateName`

My specific use-case is rendering tabs and their contents, which requires two calls to {{render}}

Thanks!

**Comment by stefanpenner** [comment]
this appears to be an issue on beta is this correct?

**Comment by stefanpenner** [comment]
@ef4 this _may_ be related to some of your work?

**Comment by rwjblue** [comment]
The error message is kinda silly in this case, but the issue here is that you have specified the template name twice.  

```
{{render "fish" this}} 
```

```
App.FishView = Ember.View.extend({
  templateName: 'fish'
});
```

Removing the duplicate template, fixes the issue in the demo. Working version: http://emberjs.jsbin.com/rwjblue/368/edit?html,js,output

**Comment by ef4** [comment]
As far as I can tell this is not related to my changes. It is fallout from htmlbars.

It does appear to be an unintended semantic change that we should fix if possible. Presumably the render helper shouldn't set a template when there's a view class.
