### ISSUE TITLE
TypeError: node is undefined in ChainNodePrototype.unchain

### ISSUE THREAD

**Issue by rvan1** [emberjs/ember.js#10717]
After transitioning through a few views, then submitting a form with an action helper, targeted at the view, I click a Back button using a link-to helper. The console indicates 'transitioned into' and 'transition complete', but the then there's a 'node is undefined' error and the View fails to load. This happens in ChainNodePrototype.unchain() which apparently unbinds and destroys event attachments to minimize memory leaks. I inspected the 'chainNode' objects and don't really see what's wrong with them. I wrapped the process inside with 'if (typeof node != 'undefined')' so my app would stop throwing TypeError when I navigate back.

**Comment by mitchlloyd** [comment]
I've been getting more familiar with this part of the code base and I'd be interested in trying to reproduce your issue. Obviously getting a JSBin or a simple project that reproduces the issue would be best, but is there anything else you could share to help?

**Comment by rvan1** [comment]
ChainNodePrototype.unchain seems to get called all the time during every transition. The method gets 'node' by chain key then tries to unchain or destroy. The chain key can be a reference to all sorts of properties native to ember as well as properties from the projects implementation code.

The project is a non-CLI app using grunt and api-stub, but upgraded to Ember 1.10 & HTMLBars. It's used to book hotel reservations. The issue occurs after filling out guest info, transitioning to a 'confirmation' screen and going back from there. If I refresh, then go back, it works OK. 

I took a closer look at the problem and the key with the undefined node is always 'HotelReservations'.  It seems that 'HotelReservations' is not normally a property needing to be processed this way as I don't see it in the console when transitioning around. Somehow it winds up in scope of this when going back from confirmation so causes problems. It's actually a JSON object provided by api-stub 'routes.js' and used to test reservation Views, so don't know why it winds up in the unchain process.

The 'chains' object in this case is of type 'content=ChainNode', not 'model=ChainNode', if that matters. It's difficult to see the pattern in this processing of nodes by chain key, chains and parent chainNodes. It seems a little like LinkedNode where every node has some reference the the nodes before and after. It seems like the the way it gets node by chain key might recursively go through all the child nodes until it finds it, and in the case of 'HotelReservations', it doesn't.

**Comment by mitchlloyd** [comment]
I was hoping there was some code that you could share otherwise it will be pretty hard to reproduce.

However I saw you mention that 'HotelReservations' is a property. When you begin a property with a capital letter, that key is treated as a global object and has some special behavior. You might be able to work around this issue by renaming the property to 'hotelReservations'.

In any case you're definitely experiencing a bug.

**Comment by krisselden** [comment]
This error means that there is an unbalanced call to removeObserver.  It is a symptom of a problem that happened earlier, some code expects to be removing an observer that is not present.

**Comment by rvan1** [comment]
Interesting. I encountered this after upgrading an EAK app to ember 1.10. Now that I've also migrated to Ember CLI (& Ember 1.11.1) I thought the issue went away but I see it still happens, so went and modified the 'unchain' function again. I'll have to research what your comment means and how it applies to my app to see if I can get to the root cause. Thx

**Comment by stefanpenner** [comment]
View/Component life-cycles had some quirks earlier, in 1.13.3 and beta/canary this are has been nicely re-worked.

If the issue is still present, please report back (be sure you are using once of the above versions). Ideally with some sort of reproduction repo/jsbin.
