### ISSUE TITLE
guide issue? i should use which kind of event_name style, keyPress or key-press?

### ISSUE THREAD

**Issue by Jokery** [emberjs/ember.js#10713]
in [input guide](http://emberjs.com/guides/templates/actions/)
it says Event Names must be dasherized when assigned to on.
and in [action guide](http://emberjs.com/guides/templates/actions/)
it says In general, two-word event names (like keypress) become keyPress.
i'm confused

**Comment by knownasilya** [comment]
@Jokery when using as an attribute on an element/in actions, use dasherized, but in code use camelCased.

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/guides/issues/418.
