### ISSUE TITLE
keys and values for Ember.Map

### ISSUE THREAD

**Issue by opsb** [emberjs/ember.js#10722]
As of https://github.com/emberjs/ember.js/commit/685d9e36fee7a8d99f3811a9f99758a1231ffaa7 Ember.Map#keys and Ember.Map#values are now private. Is there a blessed way to get these values?

**Comment by stefanpenner** [comment]
forEach until we add iterator support to ember (planned. But not quite ready yet)

**Comment by opsb** [comment]
Ok, thanks. Iterator support sounds good!

**Comment by stefanpenner** [comment]
@opsb ya, hopefully we get it in soon :)

**Comment by stefanpenner** [comment]
going to close this, as the iterator support will come eventually, and this was more of a question then a bug report.
