### ISSUE TITLE
Ember 1.8.1 on IE9, Promise undefined

### ISSUE THREAD

**Issue by shivamd** [emberjs/ember.js#10732]
```
DEBUG: -------------------------------
ember.js?body=1:15376 DEBUG: Ember      : 1.8.1
ember.js?body=1:15376 DEBUG: Ember Data : 1.0.0-beta.11
ember.js?body=1:15376 DEBUG: Handlebars : 1.3.0
ember.js?body=1:15376 DEBUG: jQuery     : 1.11.1
ember.js?body=1:15376 DEBUG: -------------------------------
```
Getting the following error when trying to load the app.
```
Cannot process route index. "Promise" is undefined
```
The code that it is trying to call is the following:
```
new Ember.RSVP.Promise (resolve, reject) =>
```
This works properly on Chrome,Firefox etc.

**Comment by stefanpenner** [comment]
> Cannot process route index. "Promise" is undefined

would indicate that you have a `Promise` that isn't on `Ember.RSVP.Promise` somewhere.

**Comment by shivamd** [comment]
@stefanpenner thank you. That was the issue, actually IE didn't reload the files appropriately.
