### ISSUE TITLE
v1.11 doc is missing (updated) TodoMVC-style guide

### ISSUE THREAD

**Issue by LionsPhil** [emberjs/ember.js#10738]
v1.10 docs have a pretty good lead-in with a small sample application:
http://guides.emberjs.com/v1.10.0/getting-started/planning-the-application/
It covers good starting matter like:
* Ember's opinion of what Model, View and Controller mean in a client-side world
* Data-binding between the model and view in both directions (read and edit)
* Binding of other actions ("delete completed")
* Non-persistent state, and the concept that the controller is a proxy for the model which can manipulate and infer data for the view
* Routing
* Data persistence layers (fixtures for inital template work vs. moving to some real storage, although expanding it to continue on to a ReST endpoint would be even better)

In particular it's impressive that it starts with a spec and static mockup, because this fits the real world and keeps the whole thing in firm context of the end goal.

v1.11 docs don't seem to have these pages, but should have something covering the same ground, e.g. an updated version of the v1.10 app since for a simple example it can already cover a lot of angles.

(Raised as issue per locks' suggestion on IRC.)

**Comment by stefanpenner** [comment]
i believe the appropriate repo is at: github.com/emberjs/guides

**Comment by LionsPhil** [comment]
Ah bother, didn't realize that was split out. Want me to re-file over there? I'm not aware of any way to migrate issues in GitHub.

**Comment by stefanpenner** [comment]
> Ah bother, didn't realize that was split out. Want me to re-file over there? I'm not aware of any way to migrate issues in GitHub.

re-file is unfortunately the best option.

**Comment by LionsPhil** [comment]
Done, closing as misfiled here.
