### ISSUE TITLE
API documentation alphabetical items alternate columns making scanning/using difficult

### ISSUE THREAD

**Issue by terryroe** [emberjs/ember.js#10741]
The API docs now have two columns and the alphabetical order alternates from column 1 to column 2 on each line.  It would be much nicer to at minimum go back to one column.  Or better, break the columns at a midpoint of the list and show the first half of the list in the first column and second half of the list in the second column.

**Comment by mitchlloyd** [comment]
That is pretty annoying. Also the CSS column count property might be a good solution:

http://caniuse.com/#feat=multicolumn

In any event, I believe you should close this issue and open one in the https://github.com/emberjs/website repo.

**Comment by terryroe** [comment]
Created issue on website project:  https://github.com/emberjs/website/issues/2100
