### ISSUE TITLE
_debugContainerKey should be a hash that has more contextual data

### ISSUE THREAD

**Issue by igorT** [emberjs/ember.js#10742]
Something like 
```
{ namespace: ...,
  type: ....
  name: ....
}
```
This would enable ED to get rid of typeKey and just look up the `modelName` through the `_debugContainerKey`

cc @stefanpenner @fivetanley

**Comment by stefanpenner** [comment]
someone should flesh this out as an RFC

**Comment by teddyzeenny** [comment]
The Ember Inspector uses this. It's a breaking change, I should update it to support the new format before/when we commit this change. The inspector would also benefit from this since we're currently parsing the value ourselves :+1:

**Comment by rwjblue** [comment]
I am also in favor, but it will need to be done behind a feature flag to help us ensure that all tooling is ready to go.

I do not think this needs to be an RFC, since it will still be considered private API (and is underscored as such already).

**Comment by igorT** [comment]
Private but used by ED

**Comment by hemp** [comment]
I know this property is internal but it has been so handy to leverage for two items in the app I work on:

1.  Tracking user actions and analytic events for any route, controller, or component.  The `_debugContainerKey` turns into a really good category in Google Analytics events.   We reopen Ember.ActionHandler and add the record analytic event into `send`.
2.  Logging client side errors/warns to something like SumoLogic via an API call.  We have a logging mixin that provides `this.logger.warn()/this.logger.error()` and the container will be leveraged there.  `Ember.Logger` is also decorated so log/debug/warn/error methods assume a "general" value for the container key.

In both of these cases the extra data in the hash might be useful :+1:

**Comment by rwjblue** [comment]
I agree, @teddyzeenny / @wycats / any objections to this?

**Comment by wycats** [comment]
I am in favor and do not mind making this a public API if fleshed out.

**Comment by teddyzeenny** [comment]
:+1:

**Comment by fpauser** [comment]
Any news on this?

**Comment by rwjblue** [comment]
@fpauser - Not really, I think we all generally agree that there is a public API we could make out of this, but it needs to be fleshed out in an RFC and I don't think anyone has had time...

**Comment by rwjblue** [comment]
Features are generally discussed in the https://github.com/emberjs/rfcs/ repository. You can create an issue there for feature requests or a pull request to propose a new feature.  I'm closing this issue (this isn't really a bug in the framework). If someone has the time please follow up with an RFC issue/PR.
