### ISSUE TITLE
Compare custom ember objects with SortableMixin?

### ISSUE THREAD

**Issue by vasilakisfil** [emberjs/ember.js#10759]
Shouldn't default compare method include a case for regular js objects here? 
https://github.com/emberjs/ember.js/blob/v1.12.0-beta.1/packages/ember-runtime/lib/compare.js
It should compare them by getting the result of valueOf.

My actual issue is described by another user here: http://stackoverflow.com/questions/26224920/sortablemixin-doesnt-sort-when-using-a-custom-transform

**Comment by mixonic** [comment]
Objects can mixin the Ember.Comparable class and override the [compare method](http://emberjs.com/api/classes/Ember.Comparable.html#method_compare) for custom serialization.

`valueOf` on an object just returns the object. I'm unfamiliar with the semantics of comparing objects, but I doubt they are useful. Do they address something specific for you?

**Comment by vasilakisfil** [comment]
Hi sorry for my late reply.
I think valueOf an object returns the object unless it is implemented. In my case I need to sort a number of moment objects ( which have valueOf implemented) but Ember.SortableMixin fails to do so cause there is no such case in the "case" switch. Why do I need to reimplement compare method since we have valueOf there? In my case I would like it to be possible to create an abstract sorting component:

```javascript
import Ember from 'ember';
import layout from '../templates/components/sort-records';

export default Ember.Component.extend(Ember.SortableMixin, {
  sortProperties: ['createdAt:desc'],
  layout: layout,

  sortedPosts: Ember.computed.sort('content', 'sortProperties')
});
```
sortProperties work only if the content is one of those types: https://github.com/emberjs/ember.js/blob/v1.12.0-beta.1/packages/ember-runtime/lib/compare.js#L74-L109

But I would like Ember.SortableMixin to work with any object that correctly implements valueOf.

**Comment by vasilakisfil** [comment]
Hey, any update on that? Did you understand my issue or you think there is no issue ?

**Comment by xcskier56** [comment]
@vasilakisfil `Ember.computed.sort...` was exactly what I was looking for. Thanks!

**Comment by stefanpenner** [comment]
SortableMixin is deprecated. Going-forward please just use `[].sort()` which works great with glimmer out of the box.

**Comment by dmitrizagidulin** [comment]
@stefanpenner - is there any more documentation about SortableMixin being deprecated? The only mention of its deprecation that I've been able to find is this issue, and a single StackOverflow answer ( http://stackoverflow.com/a/31614050/525338 ).
In the [1.x Deprecations doc](http://emberjs.com/deprecations/v1.x/), for example, it only mentions that ArrayController will be going, but not the mixin. And the [api docs for SortableMixin](http://emberjs.com/api/classes/Ember.SortableMixin.html) also don't yet mark it as deprecated.

So my question is twofold - is it official that the mixin is on its way out? And if so, any chance we can mark it as deprecated in the docs?
