### ISSUE TITLE
Trouble with template precompilation when upgrading to 1.11.0

### ISSUE THREAD

**Issue by matthooks** [emberjs/ember.js#10766]
Hi guys,

I'm getting the following error when trying to upgrade to 1.11.0. I'm using ember-rails 0.18.0.

```
Uncaught Error: Assertion Failed: The template being rendered by `<(subclass of Ember.View):ember652>` was compiled with `Ember@1.11.0` which does not match `Ember@1.11.0.72d2409e` (this revision).
```

```
DEBUG: -------------------------------
DEBUG: Ember                    : 1.11.0.72d2409e
DEBUG: Ember Data               : 1.0.0-beta.12-canary
DEBUG: jQuery                   : 2.1.3
DEBUG: Ember Simple Auth        : 0.7.2
DEBUG: Ember Simple Auth Devise : 0.7.2
DEBUG: -------------------------------
```

I've been trying to hunt down where the revision is inserted into the templates to submit a PR but I must admit the overall flow using ember-rails is still a bit of a maze to me. If someone can point me in the right direction, I'm more than happy to do some more digging.

**Comment by rwjblue** [comment]
It is possible that the gem was packed incorrectly.  That SHA is the same one that is tagged as v1.11.0, so I am thinking perhaps that it was built into the ember-source gem before I tagged the repo.

I'll try to confirm a bit (unless you can look in the ember-source gem and compare the versions of ember.debug.js and ember-template-compiler.js).

**Comment by matthooks** [comment]
Hmm, everything in dist looks like it has the right version string, but the assets downloaded by `rails g ember:install --channel=release` appends the SHA of the release to the version string. How are those generated?

**Comment by matthooks** [comment]
FYI -- I was able to work around this by modifying my vendored assets by hand. Looks it's an error in the build process.

**Comment by rwjblue** [comment]
Maybe `ember:install --channel=release` is not downloading the template compiler?

Either way, seems like an issue with ember-rails, would you mind opening an issue over there?

**Comment by matthooks** [comment]
I just checked and it seems the ember-template-compiler is, in fact, included. It's just that whatever is generating the builds that live at http://emberjs.com/builds/#/release is appending the SHA to the end of the version string. Where do those build files get generated?

**Comment by rwjblue** [comment]
Build assets for 1.13.x should be working properly (and I now pack the gem with the same assets that are published to S3).  Closing...
