### ISSUE TITLE
Regression in 1.11 when binding to element.id in components

### ISSUE THREAD

**Issue by jnfingerle** [emberjs/ember.js#10769]
I'm using   

    id: Ember.computed('element.id', function(){
        return "foo_" + this.get('element.id');
    }),

in components to generate unique ids for my components' markup.

Boiled down into a jsbin, this works in 1.10: http://emberjs.jsbin.com/sunigalodi/1/edit?html,css,js,output

The same doesn't work in 1.11: http://emberjs.jsbin.com/sunigalodi/2/edit?html,css,js,output

(Just follow the Foo links.)

**Comment by jnfingerle** [comment]
Just to let you know: I've changed this code to `elementId` which works and would have been better used in the first place. But I still think, that this regression shouldn't have happened.

**Comment by pixelhandler** [comment]
@jnfingerle not that you have a work around do you still think this is work fixing and backporting the change to the 1.11.x version of Ember? I'm not sure there are plans for releases to 1.11 other than security releases.

**Comment by rwjblue** [comment]
:+1: - to using elementId. Also, https://github.com/emberjs/ember.js/pull/11889 addresses this slightly (though not this exact use case).

**Comment by jnfingerle** [comment]
It breaks semVer. From what I understand, that should not happen. Having said that, I don't have a problem with this any more, so I'm fine with closing it, which @rwjblue already did.
