### ISSUE TITLE
chrome ember bug

### ISSUE THREAD

**Issue by kswope** [emberjs/ember.js#10771]
Asked about something in the ember.js forum and it was suggested I post it here.

http://discuss.emberjs.com/t/ember-chrome-bug-or-what/7667

I'll repost it below for posterity

I found some weird bug/condition that is almost impossible to goggle so I've dropped by here, looks like a good place to ask.  I'm following a great tutorial of ember-cli at http://ember.vicramon.com/

I didn't set it up exactly like the tutorial, I chose to go with a separate ember front end and rails backend.

Just when the tutorial was getting good, I had to create a page to display data, here's the hbs (the tutorial uses emblem, but I verified the problem exists in each)

```
<article id="leads">
  <h1>Leads</h1>
  <ul>
    {{#each lead in controller}}
      <li>{{lead.firstName}}</li>
    {{/each}}
  </ul>
</article>
```

So nothing displayed.  So I checked the data in the ember inspector.  Its all there.  I checked the dom elements, and the data is all there.  Its just not showing up on the page, not even the &lt;h1&gt;Leads &lt;/h1&gt; part.

Ok, so I figured the tutorial came with some questionable CSS.  So I nuked the CSS.  The styling went away, but the stuff was still missing.

I've viewing this on my chromebook.  So I jumped over to my mac and still no data on the screen.  Then I thought I'd give firefox a try (I had only been using chrome).  The data appears!  Same with safari!

Ok, so problem with all chrome browsers.  In desperation I changed the id="leads" to id="leeds", and it fixed the problem.

I tried a static html page and of course it worked.  So its got something to do with ember.js and chrome and possibly the code in this tutorial.  I could readily accept I'm doing something really stupid, I'm used to it, but only happening in chrome?  Maybe I need to start deleting chrome extensions common to both my chromebook and mac, maybe that could explain it

The author put up a demo app here http://embercrm.herokuapp.com/

I don't see anything except the orange header in chrome or safari, but I see a list in firefox and opera.  (chrome and safari both use webkit? for rendering?)

**Comment by mixonic** [comment]
I'm pretty positive you use the same ad-blocker that I do :-) try disabling it and load the page again. It worked for me in Chrome private mode with ad blocking disabled.

No idea why it is being blocked, but you can see the CSS rule:

![](https://api.monosnap.com/rpc/file/download?id=WCAfJNSPb7C8QAdI2NDUMpaVT6eI1v)

**Comment by kswope** [comment]
Yep that was it.

Hmm, is it a good sign that a newbie trying to struggle to learn ember is having his tutorial adblocked.

#main > #leads does look like something that would be adblocked though.

**Comment by rwjblue** [comment]
If this is the suggested structure in the tutorial, perhaps you could reach out to Vic and let him know?

**Comment by herom** [comment]
oh boy, I didn't think of that :smiley: thanks @mixonic for clarification :+1:
