### ISSUE TITLE
Query Param Flashing Problem

### ISSUE THREAD

**Issue by flyswatter** [emberjs/ember.js#10776]
Hi, I'm having an issue using Query Params in a scenario that I think must be fairly common, but I haven't seen a lot of discussion about it or how to deal with it.

## The Behavior

If I have a route, with some `queryParams` set to `reloadData` (reloading the model on query param change), and I have a button in the route's template that toggles the query param, and I click the button, the model does reload, but also, the button flickers.

## Ideally

The button shouldn't have to flicker.  It's a filter.

## The Problem

I understand that the route has a model, and the controller's lifecycle is tied to that model, and so is the template's, and so when we `reloadData`, we reload the template as well.

## Possible Solutions

 - Keeping a parent route or controller dedicated to managing the query params and filters for its child route and its model.
    - This has the problem of splitting the query params from the route whose model they are filtering, meaning the very convenient `reloadData` option is no longer sufficient to reload our model on data change, and another strategy is needed.
    - Also seems to violate some agreement on the separation of route concerns, and I'm not completely sure what communication method would be ideal for allowing this.
 - Managing the model on the controller
    - Pretty sure I'm just trolling by proposing this, as I'm pretty sure we're moving towards a component-only application structure, where only routes should possess models, but this is what I've done until now with some success, but some problematic caveats as well.
 - Edit Ember to provide some portion of a template that is not reloaded on model change, but is only responsible for managing query parameters.
    - Probably overkill and not necessary, but if this is a common enough problem, maybe it *should* be considered that a more fundamental change could be beneficial.

**Comment by lolmaus** [comment]
Can you please share a minimal reproduction case via http://emberjs.jsbin.com ?

**Comment by flyswatter** [comment]
[A simple example failed to replicate the problem](http://emberjs.jsbin.com/vafuvesoxe/1/edit?html,css,js,output), suggesting the problem is different than I initially thought.

**Comment by ahnbizcad** [comment]
Am I mistaken when I say there is no reloadData option, but it's refresh model?

**Comment by flyswatter** [comment]
That's correct, I used the right one in the jsbin.  Sorry I haven't written a reproduction yet.  I swear there is a context in which changing a refreshModel query param reloads the whole view.

**Comment by flyswatter** [comment]
The cause was that I had a `loading.hbs` file at the root of my Ember-CLI `templates` folder.

**Comment by flyswatter** [comment]
Just to expand a little bit, because of the convention that Ember-CLI assigns any `loading.hbs` template as the application-wide loading route template, any route whose model is loading automatically displays this template instead of its normal one, even when reloading from a query parameter.

I might say that query params shouldn't trigger a full-on `loading` route state, but allow for {{#if loading}} blocks in the template, but I'm not sure this argument would garner support.

**Comment by williamweckl** [comment]
@flyswatter I'm having the exact same problem! Also with loading.hbs... What did you do to fix it?

**Comment by flyswatter** [comment]
Use more local loading hbs files, not a root level one.

**Comment by williamweckl** [comment]
@flyswatter do you mean create a loading for every single route?

**Comment by flyswatter** [comment]
If you want the loading to appear for a sub-route, that loading template should be in that sub-folder. The global loading template will replace the whole view when loading.

**Comment by williamweckl** [comment]
I want the loading to appear for all routes but not when changing query params...

**Comment by flyswatter** [comment]
You could do the ol don't reloadData at the route level when changing the query Param and just hack that request into the controller.

But you're off the Ember happy path, as far as I understand.

I believe there may also be an undocumented router method you could override, like onQueryParamChange or something.

I haven't used Ember in 7 months, so it's a little hazy.

- Dan

**Comment by williamweckl** [comment]
Found the method `queryParamsDidChange`, basically it does a route refresh(), that will trigger loading.hbs. Any clues how could I change my model to filter with API without calling refresh?

**Comment by flyswatter** [comment]
No, this is a little too far behind me now, sorry. I don't even have access to the code I wrote for this anymore.

Good luck!

- Dan

**Comment by williamweckl** [comment]
that's ok. Thank you anyway :D
