### ISSUE TITLE
Missing classNames and classNameBindings from the docs.

### ISSUE THREAD

**Issue by givanse** [emberjs/ember.js#10777]
The docs for: http://emberjs.com/api/classes/Ember.View.html mention the use of the properties `classNames` and `classNameBindings`, but they are not listed at the bottom among the other properties.

I remmember seeing that pair there before. Is this intentional?

I see that the support for those properties is provided by a mixin. Was this refactored recently and maybe that is why the docs don't list them anymore?

**Comment by rwjblue** [comment]
No I do not think it was intentional.

Most likely when the core functionality for these things was moved into mixins (in the 1.11 cycle) we did not add the proper YUIDoc decorators to indicate that these mixins were being included.

Should be as simple as adding a few comments to the docs...

**Comment by givanse** [comment]
I'll do it. "YUIDoc decorators" is a special syntax/construct used by YUIDoc? Or, do you mean that what is needed are placeholders that document the properties. Like:
 
    /*
      usual doc
    */
    mixinProperty: null,

**Comment by rwjblue** [comment]
@givanse - `@uses SomeMixin`, something like https://github.com/emberjs/ember.js/blob/5fd2d035b30aa9ebfe73de824b3b283ec8e589cc/packages/ember-runtime/lib/system/object.js#L17

**Comment by Restuta** [comment]
Looks like most of the mixins from `/packages/ember-views/lib/mixins` are still not documented and not appearing anywhere on `http://emberjs.com/api/`. E.g. it's impossible to understand that view and components have `childViews` property without looking at the sources or playing with instances in runtime.

**Comment by givanse** [comment]
The docs are updated, but the site has not been updated.

**Comment by Restuta** [comment]
I see @givanse, how often site is getting updated?
