### ISSUE TITLE
Em.computed.filterBy macro not updating

### ISSUE THREAD

**Issue by voy** [emberjs/ember.js#10779]
I stumbled upon some confusing behavior working with chains of computed macros that include `Em.computed.filterBy`. I have isolated the problem [into a jsbin](http://jsbin.com/vowani/2/edit?html,js,console).

When you run my jsbin, the first logged value is:

    [object Object] {
      type: "date"
    }

Which is to be expected. After that, I swap the compound property for a different object, but the output is still the same. When you comment out `Em.computed.filterBy` and replace it with a custom implementation (provided in the jsbin), the value logged is now correct:

    [object Object] {
      title: "foo",
      type: "date"
    }

I'm not sure if this is a bug, but from my point of view it sure seems like one. Reading the docs, I was unable to explain this behavior nor was I able to work around it other way than needlessly reimplement filterBy. Sorry if this is some sort of PEBKAC.

Note that I'm using these properties from an observer function. I'm guessing that were I using them in a template, they will have been already updated and it would not be an issue. Maybe my use case for macros just isn't correct?

**Comment by gustavocabral** [comment]
If we look at https://github.com/emberjs/ember.js/blob/4f0c5b042837fe804730015b6e64c3406e5fa748/packages/ember-runtime/lib/computed/reduce_computed_macros.js#L347, `Em.computed.filterBy` only observes ```dependentKey + '.@each.' + propertyKey```, which means it does not get updated if the array changes.

Example when it changes: http://jsbin.com/gasapecapo/1/edit?html,js,console 

IMO, you are right, it should update on ```dependentKey + '.[]' ``` too!

**Comment by voy** [comment]
So how do we go about this, I can take care of the pull request if this change is approved by someone from the core team?

**Comment by stefanpenner** [comment]
reduce computer/array computed is gone, we now can simply use basic map/filter/sort/slice by utilizing glimmers data diffing

**Comment by gregwym** [comment]
@stefanpenner could you please elaborate? It is quite frustrating when a computed property does not update when its dependent value is changed. Are we deprecating `Ember.computed.filterBy` entirely?

**Comment by mmun** [comment]
@gregwym can you file a new bug if one exists?
