### ISSUE TITLE
Ember 1.11 warning triggered for bound style when value is SafeString

### ISSUE THREAD

**Issue by awaer** [emberjs/ember.js#10783]
Ember warns of XSS vulnerabilities when using a bound style property/attribute inside a handlebars template, even if the property is returned as SafeString. A warning is not triggered for styles applied by means of `attributeBindings`.

http://emberjs.jsbin.com/zitixa/1/edit?html,js,console,output

Is the expectation that all instances of style attributes in a handlebars template should employ an additional helper? The [documentation](http://emberjs.com/deprecations/v1.x/#toc_warning-when-binding-style-attributes) implies that returning a SafeString from the computed property should be sufficient.

**Comment by rwjblue** [comment]
Using quoted value results in a pass through `concat` helper method, which makes the final value not a `SafeString`.

```html
<p style={{textStyle}}></p>
```

Demo: http://emberjs.jsbin.com/pabesawedo/1/edit?html,js,console

**Comment by ianbale** [comment]
Why have you closed this? You've posted a work around [for SOME uses], not a fix...
What If I want style="{{textStyle}} {{anotherStyle}}" ? Or style="padding:0; {{textStyle}}" ?
These don't seem to be supported...?
Having to add extra function simply to bolt "padding:0;" onto the result of {{textStyle}} is far from elegant.

**Comment by MarkMurphy** [comment]
@ianbale subscribe to #10870

**Comment by chriscareycode** [comment]
For those who may stumble across this.. 
The deprecation will point you to the page http://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes which tells you to use return new Ember.Handlebars.SafeString() to get rid of the deprecation. This still does not work (at least, it did not for me). After looking at the jsbin I noticed that the solution is to not use return new Ember.Handlebars.SafeString() but rather use .htmlSafe() as in "return 'width:50px'.htmlSafe()"

**Comment by mixonic** [comment]
@chriscareycode I believe the best thing to use is `Ember.String.htmlSafe('someString')`, without prototype extensions. That deprecation guide is just out of date (it was written for 1.11 and things changed in 1.13).
