### ISSUE TITLE
Ember 1.12.0-beta.1: router.get('url') throws an error `undefined is not a function`

### ISSUE THREAD

**Issue by OrKoN** [emberjs/ember.js#10781]
The main code:

```js
    var router = container.lookup('router:main');
    router.get('url');
```
It seems it tries to call getUrl of the location property that is a string https://github.com/emberjs/ember.js/blob/v1.12.0-beta.1/packages/ember-routing/lib/system/router.js#L113.

Ember 1.12.0-beta.1:
http://emberjs.jsbin.com/nazaruyise/1/edit?html,js,console,output

Ember 1.11 (works):
http://emberjs.jsbin.com/katicaxuqu/2/edit?html,css,js,console,output

**Comment by rwjblue** [comment]
The `location` is not initialized until after the application boots (this is how we determine whether to use HistoryLocation or HashLocation for example).

**Comment by stefanpenner** [comment]
`container.lookup(` is totally power-user territory you should be extremely careful when using this, we strongly instead recommend using injections..

**Comment by rwjblue** [comment]
the `url` property of `router` is private, and accessing things before they are initialized is generally not supported...
