### ISSUE TITLE
1.12.0-beta.1 - Ember.computed.alias deprecated? 

### ISSUE THREAD

**Issue by svox1** [emberjs/ember.js#10799]
Hi,

I get a lot of warnings:
DEPRECATION: Using the same function as getter and setter is deprecated. See http://emberjs.com/deprecations/v1.x/#toc_deprecate-using-the-same-function-as-getter-and-setter-in-computed-properties for more details.

I am only use:
Ember.computed.alias

Nothing else as a computed Function.
Is Ember.computed.alias also deprecated and I have to change this to getter / setter?

Edit:
Oh maybe the warnings comes from Ember-Data 1.0.0-beta.15?

Regards, Sebastian

**Comment by rwjblue** [comment]
No `Ember.computed.alias` is not deprecated.  Most likely this is coming from Ember Data (which has just landed an update to avoid the deprecation in https://github.com/emberjs/data/pull/2961).
