### ISSUE TITLE
Using Ember with Spring the right way ?

### ISSUE THREAD

**Issue by cristiandley** [emberjs/ember.js#10793]
Hi i've been looking for a good way to use Ember with Spring without removing or avoiding framework properties. Is there a good way ?

This guy got it working but formating json
http://springember.blogspot.com.au/2014/08/using-ember-data-restadapter-with.html

**Comment by trek** [comment]
This is an excellent question for StackOverflow. Can you post there and then come back to share a link to your post?

**Comment by cristiandley** [comment]
good idea @trek
