### ISSUE TITLE
Can't avoid XSS vulnerability warning in 1.11.0

### ISSUE THREAD

**Issue by manufitoussi** [emberjs/ember.js#10794]
Making a content a safe string doesn't avoid XSS vulnerability warning.

```javascript 
 backgroundColorStyle: Em.computed(function() {
    return 'background-color: %@;'.fmt(this.get('color')).htmlSafe();
  }).property('color')

```
```html 
<div class="color" style="{{backgroundColorStyle}}">
</div>
```

Nor with `{{{...}}}`.

**Comment by pogopaule** [comment]
I can confirm this.

**Comment by rwjblue** [comment]
Duplicate of: https://github.com/emberjs/ember.js/issues/10783

Using quoted value results in a pass through `concat` helper method, which makes the final value not a `SafeString`.

The following works without a deprecation:

```html
<p style={{textStyle}}></p>
```

Demo: http://emberjs.jsbin.com/pabesawedo/1/edit?html,js,console
