### ISSUE TITLE
Scheduling a method that is `undefined` should throw

### ISSUE THREAD

**Issue by jclem** [emberjs/ember.js#10800]
If I do this:

```javascript
Ember.run(() => {
  Ember.run.schedule('afterRender', this, 'someMethod');
});
```

And `this.someMethod` is undefined, Ember should probably throw when the method is scheduled. I think an assert is warranted here, probably. Note that even when the scheduled method is called, there's no error or warning.

**Comment by tsharman** [comment]
I think I can take this.

I took a look at the run_loop and it looks like a lot of the work is handled by backburner(https://github.com/ebryn/backburner.js/issues). Should this check be happening in there?

**Comment by stefanpenner** [comment]
> took a look at the run_loop and it looks like a lot of the work is handled by backburner(https://github.com/ebryn/backburner.js/issues). Should this check be happening in there?

ya its all handled by that micro-lib

**Comment by OrKoN** [comment]
@stefanpenner This looks to be fixed

**Comment by stefanpenner** [comment]
i don't believe the BB update is sync'd over.

**Comment by rwjblue** [comment]
Updated in https://github.com/emberjs/ember.js/commit/260a81f978b2e36c020e1bfe6990c23e4bcb6adb which includes the changes made by @ksol in https://github.com/ebryn/backburner.js/pull/140.
