### ISSUE TITLE
Changes from #10256 break App.Router in initializers

### ISSUE THREAD

**Issue by martndemus** [emberjs/ember.js#10807]
The changes in #10256 breaks the following for me: (using ember-cli)
```javascript
export default {
  name: 'foo',
  initializer: function(container, app) {
    app.Router.map(function() {
       this.route('foo');
    });
  }
});
```
As the router used in the initializer is now destroyed/replaced when `app/router` is loaded.

This change fixed it for me:
```javascript
export default {
  name: 'foo',
  initializer: function(container, app) {
    var Router = container.lookupFactory('router:main');
    Router.map(function() {
       this.route('foo');
    });
  }
});
```

This issue is probably more of documentation for other people hitting this problem.

**Comment by rwjblue** [comment]
@martndemus - Is this still an issue?  Looking at the code, can you see a solution to fix this?  If not, how should we document?

**Comment by rwjblue** [comment]
This doesn't seem to be a common issue, so I'm going to close this. If someone is interested in pursuing this we can reopen...
