### ISSUE TITLE
guide suggestion - improve links on Installing Ember page

### ISSUE THREAD

**Issue by alexblakemore** [emberjs/ember.js#10804]
First, it would be helpful if the installing ember page in the guides had a link to http://www.ember-cli.com

That's a very important site with documentation that isn't available elsewhere. I'd mention it right up top when talking about installing ember-cli, but you could put it a little further on. Figuring out ember-cli from the --help text alone is pretty cryptic.

Second, in the same section, there is a link tied to NPM but it points back to the same paragraph that contains the link. A little strange and confusing. You can click it all day long and nothing seems to happen :-) Unless you are trying to play tricks on people, you might want to either actually link to a page about nom or remove the link.

**Comment by vectart** [comment]
@alexblakemore I absolutely agree that current front-page doesn't work, thus I would like to come up with an idea how to reflect the whole great Ember.js ecosystem.

Below you can see design mockup with three snippets of Ember.js, CLI and Data:
- Ember.js and Data snippet reflect latest versions and activity;
- Ember CLI snippet is looking more attractive and suggest newcomers to start with it.

![Ember Frontpage Suggestion](https://www.dropbox.com/s/3bkc55hw11cpe7d/ember.png?dl=1)

I suppose that such main part of Ember website may dramatically increase users' attraction and give clearer explanation of how to start with Ember ecosystem.

**Comment by vectart** [comment]
Probably, it's better to move the issue into https://github.com/emberjs/website

**Comment by alexblakemore** [comment]
good suggestion, I created this issue on the website tracker

**Comment by vectart** [comment]
I've created the mockup discussion https://github.com/emberjs/website/issues/2115
