### ISSUE TITLE
Ember 1.11.0 Regression: URL Not Updated When Visiting Same Route Twice When Using HistoryLocation

### ISSUE THREAD

**Issue by mutewinter** [emberjs/ember.js#10801]
## Demo

http://emberjs.jsbin.com/hasogomahi/2

1. Click "index"
1. Click the browser back button
1. Click "index" again
1. The URL will remain `http://emberjs.jsbin.com/hasogomahi/2`

Here's an example of this demo [working under Ember 1.10.0](http://emberjs.jsbin.com/yocodolire/1).

## Demo in the Wild

1. go to http://www.bustle.com
2. click an article
3. click browser back button
4. click _same_ article
5. url will be `http://www.bustle.com`

## Culprit

```javascript
    setURL: function(path) {
      var state = this._historyState;
      path = this.formatURL(path);

      // This check fails because _historyState has not been updated after the browser's popState event changed the URL.
      if (!state || state.path !== path) {
        this.pushState(path);
      }
    },

    pushState: function(path) {
      var state = { path: path };

      property_get.get(this, 'history').pushState(null, null, path);

      // history state is only set here and in replaceState, not on browser's popState event.
      this._historyState = state;

      // used for webkit workaround
      this._previousURL = this.getURL();
    },
```

This regression appears to have been added in [this commit](https://github.com/emberjs/ember.js/commit/7afdc4108ba0ee7d239417a1ac97f8aab44016f7#diff-dfe062cc6857a1454f76d9e28bda3400).

**Comment by tomdale** [comment]
@mutewinter Thanks, looking into this.
