### ISSUE TITLE
Descriptors on the monkeypatched arrays interferes with ace editor (and possibly other code)

### ISSUE THREAD

**Issue by panta82** [emberjs/ember.js#10810]
In 1.9 and earlier (before "metal", I think), your descriptor constructor was this:

```javascript
function Descriptor() {}
```

Now, you changed it to this:

```javascript
  function Descriptor() {
    this.isDescriptor = true;
  }
```

So Descriptor constructor now has to be called with `new Descriptor()`, while it used to work fine with just `Descriptor()`.

Not a big deal, you're calling it correctly inside your own code. But you also monkey-patch a bunch of properties using this onto javascript's built-in objects (eg. Array-s), which other code interacts with.

Code like this deepCopy() function in the [ace editor](http://ace.c9.io/):

```javascript
exports.deepCopy = function (obj) {
    if (typeof obj !== "object" || !obj)
        return obj;
    var cons = obj.constructor;
    if (cons === RegExp)
        return obj;
    
    var copy = cons();
    for (var key in obj) {
        if (typeof obj[key] === "object") {
            copy[key] = exports.deepCopy(obj[key]);
        } else {
            copy[key] = obj[key];
        }
    }
    return copy;
};
```

This line "`var copy = cons();`" now crashes when it tries to create Descriptor for properties on the monkey-patched arrays.

Ace editor authors are being a bit careless here, but since you were the ones who decided to mess with global built-ins, I figured a bug report belongs here more than on their page. :-)

Suggested fix:

```javascript
  function Descriptor() {
    if (!(this instanceof Descriptor)) {
        return new Descriptor();
    }
    this.isDescriptor = true;
  }
```

**Comment by rwjblue** [comment]
If you are having conflicts due to these global extensions, I would recommend turning them off.  You can disable global monkey patching by setting a `window.EmberENV = { EXTEND_PROTOTYPES: false }` before loading Ember.

Demo JSBin: http://emberjs.jsbin.com/rwjblue/379/edit

**Comment by panta82** [comment]
Fair enough. I already have a bunch of code using them, so I'll just patch my local ace.js and carry on. In the next project, though, I'll probably go with a firm "no global extensions of any kind" rule.

**Comment by wycats** [comment]
cc @wycats
