### ISSUE TITLE
errors occurring in superWrapper are swallowed higher in the stack -- undefined is not a function

### ISSUE THREAD

**Issue by robotarmy** [emberjs/ember.js#10814]
This is related to transition event that calls code that will generate an 'undefined is not a function error'

A reproduction of the error ( and a patch to log the error to demonstrate the crux of the problem) is here:
https://github.com/RAM9/ember-cli-ember-loader-bug

This isn't ember-cli specific but it was noticed during an upgrade to ember.

Essentially the problem is given programmer error: Calling a function that dosen't exist in some class
definition and then invoking that Class definition at runtime in an operation that will cause a transition
will result in a swallowed exception and a very generic albeit correct javascript error.

IE : programmer error
```
import DS from 'ember-data';

export default DS.Model.extend({
 name: DS.attr('string'),
 hose: DS.cake('string')
});
```

Using the programmer error
```
import Ember from 'ember';
import Item from 'ec-new/models/item';

export default Ember.Route.extend({
  model: function() {
    return Item.create();
  }
});
```

Result
```
Uncaught TypeError: undefined is not a function ember.debug.js:24804
```

Expected

Ember will not swallow stack traces or otherwise mangle the error stream.

The error in particular is actually happening in superWrapper 

Wrapping the error and re-raising it would be ugly but much more workable than the current overly
sanitized message.
```
try {
        if (length === 0) {
          ret = func.call(this);
        } else if (length === 1) {
          ret = func.call(this, arguments[0]);
        } else if (length === 2) {
          ret = func.call(this, arguments[0], arguments[1]);
        } else {
          var args = new Array(length);
          for (var i = 0; i < length; i++) {
            args[i] = arguments[i];
          }
          ret = apply(this, func, args);
        }

        if (this) {
          this.__nextSuper = sup;
        }
} catch(e) {
  console.log(e)
  throw e;
```

The stack is preserved :+1: 
```
TypeError: undefined is not a function {stack: (...), message: "undefined is not a function"}message: "undefined is not a function"stack: "TypeError: undefined is not a function↵    at http://localhost:4200/assets/ec-new.js:92:25↵
```

This is not intended as a suggested fix. I expect the ember team has a better idea of how to do this without mangling the error stack.

**Comment by stefanpenner** [comment]
I believe chrome canary now nicely names these errors.

![screen shot 2015-04-02 at 3 26 03 pm](https://cloud.githubusercontent.com/assets/1377/6975009/9a316bbc-d94c-11e4-979c-5af33204160f.png)

**Comment by stefanpenner** [comment]
im going to actually try your example app now, now sec.

**Comment by stefanpenner** [comment]
> A reproduction of the error ( and a patch to log the error to demonstrate the crux of the problem) is here:
> https://github.com/RAM9/ember-cli-ember-loader-bug

this app doesn't appear to obviously error, can you describe what one must do to see the error?

**Comment by jbrown** [comment]
If I remember correctly, you can't directly create a `DS.Model`. You need to create it through the store.

```javascript
import Ember from 'ember';

export default Ember.Route.extend({
  model: function() {
    return this.store.createRecord('item');
  }
});
```

**Comment by robotarmy** [comment]
@stefanpenner 
I have updated the project with reprosteps :+1: 


To reproduce this error in the transition handling you will need to start the ember server
```
ember s
```
And visit a route ( which creates a transition)
```
http://localhost:4200/items
```

In the console you will see two kinds of errors 'undefined is not a function': One is generated by a patch on superWrapper - you'll see in the stack property that there are clues to the actual file that generated the issue.

The second errors is what ember will do by default ( strip the stack and clobber the actual error details)

**Comment by robotarmy** [comment]
@jbrown 

Thank you for your consideration. You can directly create any ember object with create. When actually developing with Ember-Data you're right that all activity would be done through the store mechanism.
The issue is less about Ember Data and more about creating a generic object that happens to have a function name typo (or a correct function name accidentally being called on the wrong module)

I do a create simply to trigger execution of the internal code which purposefully generates an error. The purpose of writing incorrect code that generates an error is to point out that the transition handling code that eventually calls superWrapper is re-writing the error without the stack.

If you simply put Item.create in the app.js - the loader captures the error correctly without dropping the stack. It is only in the case of transitions where this 'Gotcha' gets you.

Best regards.

**Comment by robotarmy** [comment]
Ladies and Gentlemen -  my apologies.. i forgot to push the code into the repo!

**Comment by stefanpenner** [comment]
> Ladies and Gentlemen - my apologies.. i forgot to push the code into the repo!

:trollface:

**Comment by stefanpenner** [comment]
chrome canary output:

![screen shot 2015-04-03 at 11 37 24 am](https://cloud.githubusercontent.com/assets/1377/6986807/da125a8a-d9f5-11e4-9cef-aab9502265d5.png)

**Comment by paulirish** [comment]
hey yall. caught up with @stefanpenner on this and we came to an agreement.

1. it's a big regression that we don't provide a stack anymore in the re-throw.  i want us to fix that. 
  * (fingers crossed it was an accidental regression and not a necessary compromise for other work)
1. stack should be of the original error.
1. script location on the right should be the location of the re-throw.

@stefanpenner would love your help filing this on crbug.  
just attach https://cloud.githubusercontent.com/assets/39191/6987290/a49966b4-d9fa-11e4-87d1-0087633134ff.png to clarify. it's goood.

**Comment by stefanpenner** [comment]
crbug reported: http://code.google.com/p/chromium/issues/detail?id=473785&thanks=473785&ts=1428091786

**Comment by curtislinden** [comment]
@stefanpenner @paulirish 

Thank you both for your attention. I admit that I don't know the details of the promise/async/error conditions that you're working with. It would be really helpful if you need to catch and throw the error that there is some kind of logged evidence of this stack trace.

I really appreciate your attention to detail. 

It's true that Chrome doesn't provide any help with this, Safari has an incorrect stack trace as well ( while correctly printing the evaluation line that caused the issue), FirefoxNightly is somewhere in between.

If possible it would be interesting to try to hold http://c2.com/cgi/wiki?DontCatchRuntimeExceptions or alter the way that the thrown error is constructed ( including any exceptions that have been wrapped)

Thank you for your care and attention in making Ember easier to work with during development.

**Comment by stefanpenner** [comment]
> If possible it would be interesting to try to hold http://c2.com/cgi/wiki?DontCatchRuntimeExceptions or alter the way that the thrown error is constructed ( including any exceptions that have been wrapped)

we try to minimize this unfortunately, various things (like promises) force us to do this.

**Comment by stefanpenner** [comment]
- [ ] open webkit issue
- [ ] open FF issue

**Comment by curtislinden** [comment]
@stefanpenner Thank you for your attention.

It seems like other than manually logging the stack - working with the browser vendors is great move.

Appreciate your efforts!

**Comment by stefanpenner** [comment]
> It seems like other than manually logging the stack - working with the browser vendors is great move.

ya, lets just fix the issue at the source :)

**Comment by stefanpenner** [comment]
@curtislinden your user-icon is fantastic.

**Comment by curtislinden** [comment]
@stefanpenner hahahah thank you. that user-icon was a drawn while I was living in a buddhist temple. It's my reflection on a koan about moving towards the unknown.

**Comment by rwjblue** [comment]
The referenced chrome bug has been marked as fixed: http://code.google.com/p/chromium/issues/detail?id=473785&thanks=473785&ts=1428091786.

Closing this, as I don't think there is much more we can do here.
