### ISSUE TITLE
Observers on services

### ISSUE THREAD

**Issue by jskeate** [emberjs/ember.js#10821]
I'm trying something reducible to [this JSBin](http://emberjs.jsbin.com/metoyesole/3/edit?html,js,console,output). I have an observer on an injected service's value, but it doesn't get called when the value changes.

But, if we add `Ember.Evented` and set up a `trigger`/`on` pair ([like so](http://emberjs.jsbin.com/metoyesole/4/edit?html,js,console,output), then it actually gets called *twice*, (presumably) once for the `on` and once for the `observes`.

Seems like service values should be observable, but maybe I'm not doing it quite right? Or is this a bug?

**Comment by mitchlloyd** [comment]
Hello, @jskeate. You've hit on an awkward point of observers. They are not watched until someone `get`s them.  Here is a working JSBin.

http://emberjs.jsbin.com/wisusonepa/2/edit

This is documented here:

http://guides.emberjs.com/v1.11.0/object-model/observers/#toc_unconsumed-computed-properties-do-not-trigger-observers

This is a pretty rough gotcha.

**Comment by jskeate** [comment]
(note: your working JSBin doesn't seem to work; I realize in my original I still had ApplicationRoute, and by the functional one I'd changed it to ApplicationController. if I do that with your edit, it works)

That documentation refers to computed properties, and I've encountered this before with them. I guess I didn't make the connection because this is (afaict) not a computed property.

Does service injection somehow make computed properties? If so, this should probably be documented somewhere. For that matter, the docs on that topic in general probably need updating. The [page on Dependency Injection & Service Lookup](http://guides.emberjs.com/v1.11.0/understanding-ember/dependency-injection-and-service-lookup/) doesn't mention `Ember.inject.service` anywhere.

**Comment by mixonic** [comment]
The Ember.inject.service and controller APIs a eagerly validated, lazily 
looked up. So then the injected-onto factory is looked up and 
instantiated it is asserted that the injected factory exists and is 
correct. It isn't until you `Ember.get(this, 'myService')` that the 
service factory is actually instantiated (and the CP called so it can be 
observed).

In Ember 2.0 I expect to see fewer observers being used. Fewer people 
should be bit by the un-consumed computed property observation gotcha.

The DI guide absolutely needs updating.

**Comment by devinrhode2** [comment]
I ran into this, I assume it is still an issue. My final observer looks like:
```
  redrawChart: on('init', observer('sidebar.showSidebar 'chart', function() {
    // we need the on('init' and so we can then call this:
    this.get('brush');
    // to instantiate the service, and register the observer.. https://github.com/emberjs/ember.js/issues/10821
    let chart = this.get('chart');
    if (chart) {
      run.next(() => {
        chart.redraw();
      });
    }
  })),
```
(need to redraw highcharts chart after sidebar is hidden/shown)
