### ISSUE TITLE
Aliases are not enumerated in `eachComputedProperty`

### ISSUE THREAD

**Issue by cowboyd** [emberjs/ember.js#10823]
While the docs indicate that the return value of `computed.alias` and friends is a `ComputedProperty`, they are not enumerated with a call to `eachComputedProperty`. E.g.

```js
var AClass = Ember.Object.extend({
  foo: Ember.computed(function() {
    return "foo";
  }),  
  bar: Ember.computed.alias('foo')
});
```

will only yield one CP for `foo`, not `bar`

Demonstration here:

http://emberjs.jsbin.com/wadirumiti/1/edit?html,js,output

**Comment by stefanpenner** [comment]
https://github.com/emberjs/ember.js/blob/7a8a46be489871820ca100f536dd03b174788ddb/packages/ember-runtime/lib/system/core_object.js#L797-L802 should also check for https://github.com/emberjs/ember.js/blob/680f997ed0958c420abdcd0b1673111aee26afe7/packages/ember-metal/lib/alias.js#L23
