### ISSUE TITLE
Regression: Nested {{render}} helpers result in Uncaught TypeError

### ISSUE THREAD

**Issue by awaer** [emberjs/ember.js#10827]
Using nested {{render}} helpers results in `Uncaught TypeError: undefined is not a function.` It seems this began with the changes made in #10602 (d8a16a4) for 1.11.0. 

This JSBin reproduces a simple example: http://emberjs.jsbin.com/moxugi/1/edit?html,js,console,output

(*carried over from #10760*)

**Comment by JackCA** [comment]
I believe I just hit this as well

**Comment by michaeldeitcher** [comment]
I'm looking forward to a fix for this regression. Thanks

**Comment by alexdiliberto** [comment]
I can confirm this regression as well. After banging my head for a little big I realized this was the problem with the nested {{render}}

+ @ef4

**Comment by ef4** [comment]
I see the problem. The render helper impersonates an outlet, but not well enough for when it is its own recursive child. It needs to get a `_parentOutlet()` method too.

I don't know if I'll be able to get to this right away, if somebody else wants to take a stab at it it shouldn't be too difficult. Update the `impersonateAnOutlet` function to set `view._parentOutlet` to a function that works the same way OutletView's function of the same name works.

**Comment by dcheng168** [comment]
+1, having same problems

**Comment by phlppn** [comment]
+1

**Comment by awaer** [comment]
Here's the same example above using the PR build: http://emberjs.jsbin.com/jolisu/1/edit?html,js,console,output

**Comment by ryanjm** [comment]
Just hit the [same thing](http://emberjs.jsbin.com/lijuyu/4/edit).

**Comment by awaer** [comment]
I notice this issue was left open after the PR was merged. @rwjblue Is there anything left pending that I can help with?

**Comment by rwjblue** [comment]
@awaer - I need to cherry-pick the fix up from stable branch, so I left the issue open.  Just pulled in those commits, so closing now (thanks for the reminder!)...

**Comment by davidpett** [comment]
@rwjblue any info on a 1.11.2 release for this regression? is there anything I can help with?

**Comment by ChrisHonniball** [comment]
@rwjblue I'm getting bit by this bug in 1.11.2. Was there a solution somewhere? If so, I'm unable to locate it. Thanks!

**Comment by rwjblue** [comment]
@ChrisHonniball - Update to 1.11.3.

**Comment by ChrisHonniball** [comment]
> Update to 1.11.3.

Oh thank you! I read this post **SECURITY AND BUGFIX RELEASES - EMBER 1.10.1, 1.11.2, 1.11.3** and stopped at 1.11.2... Sorry.

Now on to deprecations! :fist:
