### ISSUE TITLE
Subsequent history is erased after transition to the page with queryParams

### ISSUE THREAD

**Issue by lessless** [emberjs/ember.js#10828]
Hello team,

here is a repo https://github.com/lessless/checktransition to quickly reproduce weird behavior of the queryParams and history location type. Here is the exact line that  do erase the history https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/location/history_location.js#L144 what is totally legit according to the documentation
http://www.w3.org/html/wg/drafts/html/master/browsers.html#dom-history-pushstate:

>  *  If the method invoked was the pushState() method:
>
>    *  Remove all the entries in the browsing context's session history after the current entry. If the current entry is the last entry in the session history, then no entries are removed.

Steps to reproduce: 
  *  enter any letters from the contact name in the input field, e.g. 'ja'
  * click on the contact name
  * click back in the browser toolbar to return on the previous page in history

**Outcome**:
the history entry for the contact page is erased - it's impossible to click 'forward' and get back onto it

**Expected outcome**: 
history entry for the contact page is not erased 

**How to fix**:
change location type from 'history' to 'hash'

**Notice**:
 it's possible to safely navigate without that side effect if queryParams are not applied - with empty input field click on any contact and then click back. The 'forward' link is preserved.

**Comment by pixelhandler** [comment]
@lessless can you provide an updated example (reproduction of the issue) using a current release of Ember.js or the LTS release (2.4.6) ?

**Comment by lessless** [comment]
@pixelhandler nope, happily left Ember.js behind :)
