### ISSUE TITLE
Issue when replaceWith is used, doesn't keep browser state

### ISSUE THREAD

**Issue by alexmngn** [emberjs/ember.js#10831]
Hello,
I just found out a bug when we use the method replaceWith.
The best thing to explain is an example.

Let's say I'm in a page called `login`, and this page has a link to `register`.

`login.hbs`
```html
{{#link-to 'register'}}Register{{/link-to}}
```

When I click the link, I am transitioned to the route `register`. My register happen to be in multiple steps, and the `login` page doesn't know anything about that, I decided to have the `register/index.js` route to redirect the user to the first step of the flow using `replaceWith`.

`routes/register/index.js`
```javascript
...
beforeModel: function () {
   this.replaceWith('register.step1');
}
...
```

Doing that, the user access the route `register.step1` without any problem.

But when the user press the browser back button, instead of going back to the `login` page, which was the page he's coming from, the user goes back to the page he was before he came to the `login`. I checked the browser state and it seems like the `login` page has been replaced by the `register.step1` page. The `login` doesn't appear anymore in the history.

I believe the browser should keep the state of the page the user is coming from, even though there is a `replaceWith` call in between the transition.

Thanks.

**Comment by jeradg** [comment]
I just encountered this problem.

In my case, I was able to work around this by using `redirect` with `this.transitionTo()` (instead of `beforeModel` with `this.replaceWith()`). So with @alexismangin's routes:

```js
//...
redirect: function () {
   this.transitionTo('register.step1');
}
//...
```

When I used this version, the register.index route does not appear in the history, and pressing the back button renders the login view.

This might work for you as well, @alexismangin.

**Comment by underoot** [comment]
@jeradg If you start your application in route `register.index` by copy&paste url of this route - this entry will shown in history and then your route redirect to `register.step1` by your transitionTo. When you click back-button in state `register.step1` in this case you will always redirect again into `register.step1`.

**Comment by jamesarosen** [comment]
possibly related to #12824

**Comment by nathanhammond** [comment]
@alexmngn Can you try `transition.abort()` inside of `routes/register/index.js`, followed by `this.transitionTo()`? I'd love to create a few new router tests for edge cases like this.

**Comment by acorncom** [comment]
Closing this in favor of #12824 If there are additional edge cases here that I've missed, please comment and we can reopen here...
