### ISSUE TITLE
Ember.Controller._calculateCacheKey() failure when routes nested

### ISSUE THREAD

**Issue by amurchick** [emberjs/ember.js#10838]
`JSBin` example for catch this - http://jsbin.com/zoyoqi#/potatoes/one?filter=filterValue&nextFilter=nextFilterValue

`_calculateCacheKey()` failure causes incorrect store/restore of `nextFilter` query parameter in `Ember.Controller` - if you see on links `href`'s in `JSBin` example - you will see:
```html
	<a id="ember296" class="ember-view" href="#/badgers/one?nextFilter=nextFilterValue">Badgers</a>
	<a id="ember297" class="ember-view" href="#/badgers/two?nextFilter=nextFilterValue">Badgers</a>
	<a id="ember298" class="ember-view" href="#/bears/one?nextFilter=nextFilterValue">Bears</a>
	<a id="ember299" class="ember-view active" href="#/potatoes/one?filter=filterValue&nextFilter=nextFilterValue">Potatoes</a>
```
In other words, `nextFilter` value for route `#/potatoes/one` sets same for all routes.

However value of `filter` correctly works as described by http://guides.emberjs.com/v1.11.0/routing/query-params/ in section `STICKY QUERY PARAM VALUES`.

What leads to failure?
Set breakpoint in http://builds.emberjs.com/beta/ember.debug.js in line `19744`:
```javascript
var value = property_get.get(values, part);
```
with condition `part === "team.tear.tear_menu_id"` and after debugger stops - execute line on which debugger stops.

Result: `value` will be set to `undefined`, because we are try get `team.tear.tear_menu_id`, but `values` contains:
```javascript
{
    "team.tear": {
        tear_menu_id: "one"
    }
}
```

Simplest example:
```javascript
Ember.get({'a.b': {c: 10}}, 'a.b.c')
```
returns `undefined`.

**Comment by amurchick** [comment]
Do you plan fix this issue?

**Comment by trek** [comment]
I've been trying to understand what this report is for about 30 minutes now. Can you provide more structure around descriptions of what you're seeing, what you expect to see, and steps to reproduce?

**Comment by rlivsey** [comment]
If I'm following correctly, I *think* this is a duplicate / along the same lines as #3638 and #9630

**Comment by trek** [comment]
@rlivsey that would be an underlying cause of the problem, but is really just implementation detail @amurchick uncovered. I'm still trying to figure out what the public API bug is based on the report.

**Comment by amurchick** [comment]
@trek I am very accurate describe problem, ok, I will try again...

### When the bug occurs?
When you use query parameters in nested routes.

### How to produce?
* Navigate to http://output.jsbin.com/zoyoqi#/badgers/one?nextFilter=nextFilterValue
* See elements in developer console and you will see, for all routes `nextFilter` has value `nextFilterValue`:
![screen shot 2015-06-22 at 10 59 45](https://cloud.githubusercontent.com/assets/1515699/8275367/fc062902-18cd-11e5-84cb-d77ab3334328.png)
* Try to change `nextFilterValue` for example on `newValue` - see elements again:
![screen shot 2015-06-22 at 11 03 22](https://cloud.githubusercontent.com/assets/1515699/8275381/54e0606a-18ce-11e5-977c-a717aa6e9d57.png)

### What I am expect?
I am expect value of query parameter `nextFilterValue` **will be** changed only for `/badgers/one`, not for **all** other routes.
For every `/:team_menu_id/:tear_menu_id` query parameter `nextFilter` **must** have own value as described at http://guides.emberjs.com/v1.12.0/routing/query-params/#toc_specifying-query-parameters

### Whats wrong?
For every `/:team_menu_id/:tear_menu_id` values of query parameter `nextFilter` are **equals**.

### There is any case exists, when this worked as described?
Yes, when we  do not use nested routes:
* Navigate to http://output.jsbin.com/zoyoqi#/badgers?filter=123
* We will see - all correct, since query parameter `filter` defined on `/:team_menu_id` level:
![screen shot 2015-06-22 at 11 23 12](https://cloud.githubusercontent.com/assets/1515699/8275503/1b679d8c-18d1-11e5-9c12-1a0213db8b90.png)
* Click on link `Bears` and URL will be changed to http://output.jsbin.com/zoyoqi#/bears/one
* Simply add `?filter=456` to URL (do not reload page, only write this at end of URL) and press enter and you will see:
![screen shot 2015-06-22 at 11 26 26](https://cloud.githubusercontent.com/assets/1515699/8275522/97b58f02-18d1-11e5-85fc-2c03d179e6f1.png)
E.g., for every `/:team_menu_id` route - query parameter `filter` has **own** value.

**Comment by jmurphyau** [comment]
Basically the bug is: query params are not sticky on nested routes.

The cacheKey is not being calculated correctly since nested routes have a dot in their name and `get` doesn't work with keys that have a dot..

@trek I've got a PR that has a failing test and fix but only for query params on controllers not for query params on routes (which is a feature that isn't enabled yet though).. Spent some time trying to figure it out but couldn't manage to and can't spend any more time on it..

 I'll push it within the next hr or so

**Comment by jmurphyau** [comment]
Didn't get a chance to push the PR but I may have got it for route defined query params.. Will push it tomorrow
