### ISSUE TITLE
Ember.computed.and possible regression 

### ISSUE THREAD

**Issue by kiwiupover** [emberjs/ember.js#10834]
In Ember 1.10.0 
For this code: 
```js 
App.ApplicationController = Ember.Controller.extend({
  max:1000,
  val:500,
  computedAnd: Ember.computed.and('max', 'val')
});
```
### In Ember 1.10.0 
computedAnd = true
http://emberjs.jsbin.com/qomiyegaya/1/edit?html,js,output

### In Ember 1.11.1
computedAnd = 500
http://emberjs.jsbin.com/vovayi/1/edit?html,js,output

Introduced here https://github.com/emberjs/ember.js/commit/0a2333539a5804fc7d0409975de5997d3794c37b

**Comment by stefanpenner** [comment]
this was done to mimic logical and `max && val === 400`

**Comment by kiwiupover** [comment]
Ok I will close this and rewrite my own code.
