### ISSUE TITLE
range slider does not update value position when max changes

### ISSUE THREAD

**Issue by justin-hackin** [emberjs/ember.js#10833]
http://emberjs.jsbin.com/yomozewore/17/edit?html,css,js,output demonstrates the issue I am having with the range slider (from input helper).  When you click the button, the max doubles but the slider does not reposition to 25%.    I tried to code some work-arounds in the following comments but neither of them worked, not even setting and re-setting the value ... must be some of that ember optimization magic ... any tips on implementing an alternative workaround would be appreciated.

**Comment by rwjblue** [comment]
Sorry for the delayed response here, but I just double checked the JSBin and it seems to update the value position properly upon update now.

Closing this issue, but happy to reopen if I am misinterpreting the JSBin.
