### ISSUE TITLE
Template is not reading html codes properly in Em.TextField

### ISSUE THREAD

**Issue by metalshan** [emberjs/ember.js#10830]
If the value has an html code (suppose & lt; or &#8482) the value is displayed as it is. Ember/Handlebars prevent the browser to do its default work it seems.

**Comment by rwjblue** [comment]
I just tested in http://emberjs.jsbin.com/rwjblue/387/edit?html,js and it seems to allow/handle `<` without an issue.

Can you modify this JSBin to replicate the issue?

**Comment by metalshan** [comment]
http://emberjs.jsbin.com/baqawiqexo/1/edit?html,js,output

The characters "<" etc works if you display them directly. But it won't work if "&lt;" is used.

**Comment by rwjblue** [comment]
I am unsure what you expect in this case. As you can see [here](http://emberjs.jsbin.com/hojuri/1/edit) using a plain `<input type="text" value="<&lt">` displays the same as the `{{input}}` helper.

**Comment by metalshan** [comment]
"<" is displayed as "<" that's fine.
but "& lt;" should also be displayed as "<" not as a code.

My exact problem is, I have to make a name filter (autosuggest). In the autosuggest dropdown where I am using {{{displayValue}}} is working fine but the moment I select something from the dropdown and the value appears in the input box, it displays html code, not the output.

Check the link: http://emberjs.jsbin.com/javixobehi/2/edit
In the input box also it should display "TM" not as &# 8482;

**Comment by rwjblue** [comment]
Based on http://jsbin.com/rifali/edit?html,js,output, it is not possible to get the behavior you want (parsing of HTML tokens) via either setting as a property, or setting as an attribute.  I suspect that the only reason it works in the `qux` case is that the tokens are transformed before the attributes are parsed (as an earlier step).

I doubt that there is much we can do here (at least not without impacting performance in the "normal case" today) so I'm going to close this issue.  Sorry for leaving it hanging so long...
