### ISSUE TITLE
[DOCS] need info on the accepted ember pattern for "new" and "edit" routes

### ISSUE THREAD

**Issue by foxnewsnetwork** [emberjs/ember.js#10849]
Suppose you have a DS.Model, Comment. There is a very common resourceful pattern of having a CommentsRoute, CommentRoute, CommetsNewRoute, and a CommentEditRoute . In the case of edit and new, the route needs something like:

```coffee
# 1.9 and above
CommentsNewRoute = Ember.Route.extend
  model: ->
    @store.createRecord "comment"

  tearDown: Ember.on "deactivate", ->
    model = @get "controller.model"
    model.deleteRecord() if model.get('isDirty')
```
or 
```coffee
# below 1.9
CommentsNewRoute = Ember.Route.extend
  model: ->
    @store.createRecord "comment"

  actions:
    willTransition: ->
      model = @get "controller.model"
      model.deleteRecord() if model.get('isDirty')
```
or
``` coffee
CommentsNewRoute = Ember.Route.extend
  model: ->
    {}
```
This need for a clean up on new (and a rollback on edit) is such a common requirement, that I feel the documentation on Ember's website should really just puts its foot down and recommend the Ember canon way of doing this ( considering deactivate was rolled in on 1.9, I'd assume the first one is what would be recommended ). 

Anyway, please let me know what you guys think, and if I should do a PR on the documentation or not.

**Comment by rwjblue** [comment]
Firstly, sorry for the delay in responding here. We've been a bit swamped lately...

This is something that [dockyard/ember-data-route](https://github.com/dockyard/ember-data-route) was created to make simple, but I do think documenting this pattern in the guides would be good.  I am unsure if that belongs in one of the existing guides or in one yet to be written. You might want to check in with the folks in the #documentation channel in community slack...
