### ISSUE TITLE
Cannot iterate over an object with {{each}} helper in 1.11.0

### ISSUE THREAD

**Issue by leejt489** [emberjs/ember.js#10845]
In Handlebars, we could iterate over an object with key/value pairs. In HTMLbars I get the error `Uncaught Error: Assertion Failed: The value that #each loops over must be an Array. You passed {prop1: prop1Value, prop2: prop2Valuel}`

By design or bug?

**Comment by kingpin2k** [comment]
This wasn't ever possible in Ember Handlebars/HTMLbars, by design, I believe it's related to the ability to observe the properties properly, but I could be lying about that.

**Comment by leejt489** [comment]
From http://handlebarsjs.com/builtin_helpers.html `{{each}}` section:

When looping through items in each, you can optionally reference the current loop index via `{{@index}}`
```handlebars
{{#each array}}
  {{@index}}: {{this}}
{{/each}}
```
Additionally for object iteration, `{{@key}}` references the current key name:
```handlebars
{{#each object}}
  {{@key}}: {{this}}
{{/each}}
```

**Comment by kingpin2k** [comment]
Yeah, I'm aware it exists in Handlebars by itself, but Ember Handlebars != Handlebars.

**Comment by rwjblue** [comment]
You can do this via a custom component [see example](http://emberjs.jsbin.com/rwjblue/388/edit), but @kingpin2k is correct: this is not supported by our default `{{each}}` helper (and that is intentional).

**Comment by mmun** [comment]
It will be fairly trivial to implement once glimmer has landed, since we will be relying on diffing instead of enumerable observation.

**Comment by localyost** [comment]
Hello,
could this be what you're looking for? 
http://handlebarsjs.com/builtin_helpers.html#with

**Comment by mixonic** [comment]
`each-in` ([api docs](http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_each-in)) was added to Ember. It was [added in Ember 2.1](http://emberjs.com/blog/2015/10/04/ember-2-1-released.html#toc_code-each-in-code-helper)
