### ISSUE TITLE
link-to support for map area-tag href attribute

### ISSUE THREAD

**Issue by kgish** [emberjs/ember.js#10847]
The following should also be supported for map area coordinates
```
{{link-to 'target' tagName='area' ... }}
```

**Comment by rwjblue** [comment]
Can you please provide a demo JSBin or ember-twiddle?

**Comment by kgish** [comment]
It's hard to create a demo because what I am requesting is not supported (yet). Therefore, allow me to explain the situation by providing a clear example.

Currently I have a `map.hbs` template which contains a map of the country divided into province polygons and looks like this:
```
<p>
    <img src="/assets/images/map-of-holland-300x346.png" class="img-responsive" usemap="#map-of-holland" />
    <map name="map-of-holland" id="map-of-holland">
        <area href="/meetings?filterProvince=Drenthe" shape="poly" coords="241,48,231,61,238,77,232,84,226,83,216,90,223,99,217,105,220,111,236,119,246,120,253,115,261,117,286,115,288,91,258,56,253,54" alt="Drenthe" title="Drenthe" />
        <area href="/meetings?filterProvince=Flevoland" shape="poly" coords="180,91,157,111,141,152,165,167,192,146,199,121,209,117,194,97" alt="Flevoland" title="Flevoland" />
        ...
        <area href="/meetings?filterProvince=Zeeland" shape="poly" coords="73,240,73,256,76,276,58,294,42,293,16,289,4,280,6,268,12,249,39,222" alt="Zeeland" title="Zeeland" />
    </map>
</p>
```
Of course, I would prefer not to hard code the `/meetings` link and point to a `route` instead. Something like this:
```
{{ link-to 'meetings' tagName='area' ...}}
```
This will not work because link-to does not support `tagname='area'` at least not when I originally created this issue.

**Comment by rwjblue** [comment]
Seems to generally work here: http://emberjs.jsbin.com/qoguda/edit?html,js

You could also use something like [ember-href-to](https://github.com/intercom/ember-href-to) to just set the `href` attribute as needed (instead of using a `link-to`).

**Comment by pixelhandler** [comment]
@kgish is this still an issue for you? did you find a workaround?

**Comment by kgish** [comment]
This is still an issue for me since it's hard-coded for now. Unless someone has a better way to deal with this, my ears are open to suggestions.

**Comment by Serabe** [comment]
@kgish what is the problem with @rwjblue's solution?

**Comment by rwjblue** [comment]
As of 2.2.0 you can extend from Ember.LinkComponent (and can therefore make your own with a custom tagName).

See https://emberweekend.com/blog/faef1058c3-inheriting-from-linkcomponent-in-ember-is-amazin

**Comment by kgish** [comment]
Excellent!

**Comment by rwjblue** [comment]
I'm going to close this now, we can reopen if that doesn't fit your needs.
