### ISSUE TITLE
View-rendering with {{outlet}} in views template fails in qunit-tests

### ISSUE THREAD

**Issue by ohcibi** [emberjs/ember.js#10840]
See this fiddle: http://jsbin.com/nuqosi/3/edit

The way I did this used to work in 1.10 and I also found it to be recommended [here](http://discuss.emberjs.com/t/how-create-a-unit-test-for-view-in-ember-cli-that-renders-the-view-like-components/6891).

However since `1.11.0`, I get the error as in the example. The error disappears if one removes the `{{outlet}}` or doesn't do `appendTo("#ember-testing")` in the tests. Looks like a regression to me.

**Comment by rwjblue** [comment]
This is a bug in ember-test-helpers please reopen in https://github.com/switchfly/ember-test-helpers.

We need to register `view:-outlet` in `lib/ember-test-helpers/isolated-container.js` (similar to [here](https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/isolated-container.js#L64)) like this:

```javascript
container.register('view:default', Ember.OutletView);
```

Pull request definitely welcome :smile_cat:...
