### ISSUE TITLE
container.has deprecation seems strange

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#10851]
https://github.com/emberjs/ember.js/blob/master/packages/container/lib/container.js#L166
whats the rationale?

**Comment by dgeb** [comment]
When the `Registry` and `Container` were split, functionality was moved to one or the other. I think the crux of the problem here is not the removal of `has` from `Container`, but that there's not a clean path from a container to its associated registry (only accessible as `_registry`).

Please see [this RFC](https://github.com/emberjs/rfcs/pull/46) for where I think we need to go with containers and registries to solve this problem properly.

**Comment by stefanpenner** [comment]
So I believe my concern with removing `has` from the container, is internals can check the container without have side-affects (lookup) etc.

Ultimately, I think this can be solved if we fix FactoryInjections

We essentially implemented it backwards, we currently inject instances onto factories, but actually most of the time we want the exact opposite. I would also argue in our paradigm, we should never put instance state on factories, but the opposite is absolutely fine.

This would not only remove the need I have for container.has, but also likely remove 90% of use-cases where container is exposed to user-land.

If you want to hash this out more, I would love to do a hangout.

**Comment by dgeb** [comment]
> So I believe my concern with removing has from the container, is internals can check the container without have side-affects (lookup) etc.

Under my proposal, internals could still check the registry via `container.registry.has`.

> We essentially implemented it backwards, we currently inject instances onto factories, but actually most of the time we want the exact opposite. I would also argue in our paradigm, we should never put instance state on factories, but the opposite is absolutely fine.

What you're saying seems correct.

> If you want to hash this out more, I would love to do a hangout.

Sounds great. Let me review the factory code some more based on what you said, and then let's do a hangout in the next day or two. I'm sure we can come up with something reasonable.

**Comment by stefanpenner** [comment]
> Sounds great. Let me review the factory code some more based on what you said, and then let's do a hangout in the next day or two. I'm sure we can come up with something reasonable.

sounds good

> Under my proposal, internals could still check the registry via container.registry.has.

this is fine, but abit hard to do for backwards compat, but we can tolate `(container.registry || container).has`
