### ISSUE TITLE
Ember.SortableMixin failing in 1.11.1 / CLI 0.2.3

### ISSUE THREAD

**Issue by ksnyde** [emberjs/ember.js#10855]
I've noticed that when I add the `SortableMixin` to a controller Ember Inspector immediately falls over with the now all-too-common "Uncaught TypeError: undefined is not a function". Taking out the mixin immediately restores it to ember-goodness (albeit w/o the sortable functionality).

This *might* be a ember-inspector defect but wasn't sure how to categorize it.

The stacktrace is:

    Uncaught TypeError: undefined is not a functionember.debug.js:28637
         (anonymous function)ember.debug.js:10357
         ComputedPropertyPrototype.getember.debug.js:15617
         getVM2881:2234
         (anonymous function)VM2881:2227
         (anonymous function)VM2881:2226
         calculateCPsVM2881:2030 
         EmberObject.extend.mixinsForObjectVM2881:1924
         EmberObject.extend.sendObjectVM2881:1865 EmberObject.extend.messages.inspectByIdember.debug.js:18044 applyember.debug.js:12385 sendEventember.debug.js:29739
         exports.default.mixin.Mixin.create.triggerVM2881:2414
         (anonymous function)VM2881:109 (anonymous function)VM2881:108
         exports.default.Ember.Object.extend._messageReceivedVM2881:249 (anonymous function)ember.debug.js:217
         Backburner.runember.debug.js:15925 runVM2881:248 (anonymous function)

**Comment by stefanpenner** [comment]
@ksnyde can you provide a running example that demonstrates your problem?

**Comment by ksnyde** [comment]
Would it be possible for me to proxy you a connection to my local installation? That would allow me to demonstrate without too much work involved in my part. I know it's not ideal but I'm pretty stretched at the moment so looking for shortcuts where available.

**Comment by ksnyde** [comment]
BTW, let me just make sure I have the very latest Inspector running and that the problem still exists where I do. I know there have been a few issues recently there and while my version is *pretty* recent I know there have been a few commits since I last updated.

**Comment by oskarrough** [comment]
I'm getting something similar when I attempt to inspect a component with Ember.SortableMixin: `this.nextObject is not a function`.

**Comment by ksnyde** [comment]
@oskarrough, have you found any workarounds to this? I just ran into this again and this time it appears to be of the variety you mentioned ...

- Took a working component. 
- Added Ember.SortableMixin

Page seems to load but when I try to inspect the component with the inspector I get the `this.nextObject is not a function` error:

![2015-05-08_10-14-02_01](https://cloud.githubusercontent.com/assets/980757/7533632/fa5a8f5c-f56a-11e4-9355-a9e719e124b0.png)

**Comment by ksnyde** [comment]
Note, I just upgraded to the latest Inspector and I can now load the component although the error remains:

![2015-05-08_10-24-37](https://cloud.githubusercontent.com/assets/980757/7533878/f79353d8-f56c-11e4-99fd-3dd53782b7b6.png)


Inspector now latest:
![image](https://cloud.githubusercontent.com/assets/980757/7533854/da996574-f56c-11e4-9e60-32d4db892df8.png)

**Comment by ksnyde** [comment]
Ok, I've "sorted" my problem at least for this second variant. @oskarrough for me it was a very basic mistake ... I hadn't populated the `content` property and the computed properties involved in populating `arrangedContent` were the ones doing the complaining. I'm going to close this issue unless there's any compelling reason to keep it open.
