### ISSUE TITLE
New class bindings discard other classes when they update

### ISSUE THREAD

**Issue by RustyToms** [emberjs/ember.js#10856]
Starting with Ember 1.10, if I am binding a class to an element and then later add a class to that element (through direct DOM manipulation using jQuery in this case), that class will be discarded when the bound value changes. Prior to 1.10 these classes were left alone.

[Here is a jsbin illustrating what is happening.](http://emberjs.jsbin.com/xaqepofawi/2/edit) Click on the lower button to add a border class to the text using jQuery. Then click the top button to add a red class to the text using Ember bindings. The border class is erased.
![ember_class_problem](https://cloud.githubusercontent.com/assets/5260472/7075117/86ddcc78-decd-11e4-9e8c-bf94f1e9287e.gif)

I understand that ideally we want to use Ember tools in an Ember app, but sometimes we need to use third party libraries or have other requirements that make this impossible. Since the fix is pretty simple, I believe we should preserve these alien classes when we update the Ember classes.

**Comment by rwjblue** [comment]
Closing... See conversation in https://github.com/emberjs/ember.js/pull/10857 for details.
