### ISSUE TITLE
Recommend changing EmberENV as the correct way to access the environment ( ember-cli guide)

### ISSUE THREAD

**Issue by curtislinden** [emberjs/ember.js#10852]
using EmberENV directly seems to always default to the configuration that is setup by the server when it boots.  This creates an issue in test environments where the code is configured directly out of the global.

The workaround is to use 'config' object from environment.

This will work in both /tests (test env) and "/" (development env)

```
`import Model from 'marketplace/base/data/model'`
`import config from '../../config/environment'`

Model.reopenClass
  host: config.EmberENV.MARKET_API_HOST 

`export default Model`
```

Are there any issues with using EmberENV this way? 

Thank you

@robotarmy

**Comment by rwjblue** [comment]
Nope, using `config.EmberENV` like this is perfectly fine.
