### ISSUE TITLE
'ember-htmlbars: class attribute' tests should be failing, but they are using the wrong assertion

### ISSUE THREAD

**Issue by RustyToms** [emberjs/ember.js#10858]
Many tests [in this file](https://github.com/emberjs/ember.js/blob/v1.12.0-beta.1/packages/ember-htmlbars/tests/attr_nodes/class_test.js) should be failing but their assertions are `ok` instead of `equal`. When the assertions are changed to `equal` it becomes clear that additional spaces are being added in the class names:
![screen shot 2015-04-09 at 3 51 14 pm](https://cloud.githubusercontent.com/assets/5260472/7075467/4ae60390-ded0-11e4-8ba8-b52c3c13651b.png)

That [last test](https://github.com/emberjs/ember.js/blob/v1.12.0-beta.1/packages/ember-htmlbars/tests/attr_nodes/class_test.js#L138-L152) in particular is either very broken or reveals that there is something wrong with the way HTMLbars is handling the classes.

![screen shot 2015-04-09 at 3 50 28 pm](https://cloud.githubusercontent.com/assets/5260472/7075461/371fca94-ded0-11e4-8055-2dbf153a4e30.png)

**Comment by mixonic** [comment]
My bad tests, I thought they had been updated in master but it looks like it was only [in Glimmer](https://github.com/emberjs/ember.js/blob/idempotent-rerender/packages/ember-htmlbars/tests/attr_nodes/class_test.js).

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/tests/attr_nodes/class_test.js tests are updated on master (and 1.13 beta).
