### ISSUE TITLE
Ember.View is not removing observers after destroy

### ISSUE THREAD

**Issue by tahaozket** [emberjs/ember.js#10869]
I noticed different behaviour after 1.7 to 1.11 migration. I am observing a controller property inside Ember.View like:

```javascript
export default Ember.View.extend({
	stepChanged : function () {
	}.observes("controller.step")
})
```

When I change the route state willDestroyElement method is being called but Ember is not removing observer. Because of that, when I open the same view again, stepChanged method is being called two times. If I do same thing again, stepChanged method is being called three times.

I need to add removeObserver inside willDestroyElement to work properly.

```javascript
willDestroyElement : function() {
	this.removeObserver("controller.step");
}
```

**Comment by wycats** [comment]
cc @wycats

**Comment by AO16** [comment]
:+1:

**Comment by rjhilgefort** [comment]
:+1:

**Comment by dwickern** [comment]
I'm also seeing this in my app. Aliasing the controller property did not fix it. Calling `removeObserver` in the `willDestroyElement` hook did fix it.

**Comment by eviltrout** [comment]
Just chiming in to say I have this error in one of our Discourse views too. The `removerObserver` hack worked for me, but I'm not sure if we have the pattern anywhere else in the app.

**Comment by IBue** [comment]
I see the same behaviour with EmberJS 1.11.3.
Creating an indirection through a computed property (instead of an Ember.computed.alias) also seems to be a possible workaround:

```javascript
export default Ember.View.extend({

step: function() {

        return this.get('controller.step');
    }.property('controller.step'),
    
stepChanged: function() {

        console.log('controller.step changed');
    }.observes('step'),

init: function() {

        this._super();
        this.get('step'); //this.step has to be consumed at least once
        console.log('init'); //called on route enter
    },

willDestroy: function() {

    console.log('willDestroy)'); //NOT called on route leave, even if willDestroyElement is called
}
});
```
By the way, `willDestroy` is NOT fired. Does this mean that the View object itself won't be destroyed at all on route transition (by purpose or by bug/memory leak)?

**Comment by NilsLattek** [comment]
I can reproduce this in Ember 1.12.

**Comment by stefanpenner** [comment]
I am unable to reproduce in 1.13.3 or 2.0.  Much work specifically around view/component life-cycle cleanup and leaks have been fixed.

If someone is able to demonstrate this, please provide a demo that demonstrates this and I will gladly reopen.
