### ISSUE TITLE
[Documentation] Async Test helpers not available in Unit Tests

### ISSUE THREAD

**Issue by dianhe2** [emberjs/ember.js#10866]
The documentation on the Ember testing page is not very explicit that async test helpers like click(), andThen(), find() are only available by default in Acceptance tests and NOT unit tests.

I think it would be useful to mention this very explicitly so that people don't get the two confused. Thanks!

**Comment by nathanhammond** [comment]
This might also be worth including as an inline assertion because they're often available in unit tests that run *after* acceptance tests, resulting in confusing failures.

**Comment by ForSpareParts** [comment]
If async test helpers aren't available in unit tests, what's the intended way to unit test promise-y behavior?

**Comment by lifeinafolder** [comment]
I would also like to understand how to test async responsibilities of a component? Is that something which should not be in a component unit-test and instead be an acceptance test?

Some pointers around how to think about separating acceptance tests from units tests would be very helpful.

**Comment by stefanpenner** [comment]
@lifeinafolder http://alisdair.mcdiarmid.org/2015/06/20/ember-component-integration-tests.html may be a good reference for you.

**Comment by lifeinafolder** [comment]
@stefanpenner Thanks! That is helpful in clearing some doubts.

**Comment by stefanpenner** [comment]
> That is helpful in clearing some doubts.

hopefully eventually they will mostly be cleared :)

**Comment by alexlafroscia** [comment]
@stefanpenner how would one go about testing async stuff with the component integration tests? I have a component that renders based on a promise, and am having a hard time getting the tests to wait until the promise has resolved before moving on to the next state.  A quick example is something like this:

```javascript
const deferred = RSVP.defer();
this.set('projects', deferred.promise');
this.render(hbs `{{project-item projects=projects}}`);

assert.ok( // Check that it is in the loading state );

deferred.resolve([
  // Array of projects
]);

assert.ok( // Component has loaded the projects );
```

**Comment by rwjblue** [comment]
I definitely agree that the guides for testing need to be updated.  There are a few issues open in the guides repo:

* https://github.com/emberjs/guides/issues/562
* https://github.com/emberjs/guides/issues/501

But it seems that we might want another one ("Overhaul of Testing Guide" or something). 

I'm closing this issue in favor of issues in the guides repo since this isn't really a bug in Ember itself.
