### ISSUE TITLE
Make  "calling set on destroyed object" error more descriptive and helpful in debugging.

### ISSUE THREAD

**Issue by rafalp** [emberjs/ember.js#10865]
I wish to request Ember.js developers to consider changing error raised when set() is called on destroyed to include information that would help developers isolate faulty part of application and thus debug it more easily.

While I am yet to be biten by this error by my app, I already experienced plenty of day-long debugging sessions when my tests suite exploded with this error, and I was left in the dark about origins of problem.

Most basic solution for this issue would be to include name of property that was attempted to be set on destroyed object:

``Assertion Failed: tried to set 'PROPERTY' on destroyed object. This is usually caused by asynchronous code (i.e. Ember.run.later) attempting to change object state after it was destroyed.``

This change alone would be great improvement towards current situation. However I would like to take this step further, and thus make dev builds of Ember.js also `console.log` new value for property as well as object for which ``set`` failed.

**Comment by wycats** [comment]
cc @wycats

**Comment by OrKoN** [comment]
+1 It would be great to improve this message. I've seen this error in my app: it occurs if one clicks through the app very quickly without waiting for transitions to complete fully. In my case, it didn't break anything (just an error in the console) but still it would be great to easily know which part of the app causes it.

**Comment by brianally** [comment]
+1 I just banged into this. The submitter, @rafalp, has posted a quick workaround here:
http://discuss.emberjs.com/t/could-calling-set-on-destroyed-object-error-be-more-descriptive/7730

**Comment by OrKoN** [comment]
PR for this change https://github.com/emberjs/ember.js/pull/11426

**Comment by eccegordo** [comment]
Anything come of this? 

After trying to upgrade numerous components tests in my project I am seeing numerous instances of 

```
Uncaught Error: Assertion Failed: calling set on destroyed object
```
Which seems hopelessly vague.

It seems #11381 was one PR attempt made but was closed for reasons that are not clear.

@wycats any higher level issue going on here?

Thanks

**Comment by wagenet** [comment]
See also #12264

**Comment by adambuczynski** [comment]
Any progress on this? Seems like a very simple fix to just include the keyname of the property...

**Comment by oswaldoacauan** [comment]
:+1:
