### ISSUE TITLE
App.reset() is broken

### ISSUE THREAD

**Issue by gerry3** [emberjs/ember.js#10867]
I noticed this in my app after we upgraded to ember 1.11.1 & ember-data 1.0.0-beta.16.1. We reset our app on sign out.

Also, I just created a new ember-cli (0.2.3) app, served it, and ran `App.reset()`. In both cases:

```
Uncaught Error: Cannot re-register: `store:main`, as it has already been resolved.
ember.debug.js:1720

**Comment by stefanpenner** [comment]
which version of ember-data and test helpers?

**Comment by slindberg** [comment]
Related/dupe: #10310
