### ISSUE TITLE
Document queryParamsDidChange

### ISSUE THREAD

**Issue by flyswatter** [emberjs/ember.js#10877]
Right now `Ember.Route` has an action `queryParamsDidChange` that is triggered when query params change.

This is useful when needing to override the usual query-param-changing behavior.

However, this method is not in the ember docs, I had to find mention of it in a discussion online.

**Comment by hparra** [comment]
:+1: Search to find in source turned this issue up.

**Comment by Gaurav0** [comment]
@rwjblue @stefanpenner Is this method intended to be public or private?

**Comment by rwjblue** [comment]
@Gaurav0 - I am unsure, we likely need to ask @machty....

**Comment by elidupuis** [comment]
FWIW, I'd like it to be public :D

**Comment by stefanpenner** [comment]
i suspect public, but @machty may be able to shed light. Will rope him in.

**Comment by machty** [comment]
I don't think I ever intended `queryParamsDidChange` to be public. It was needed as part of the somewhat convoluted contract with using router.js as a microlib, but it ended up serving as an escape hatch for folk who had unusual serialization/default needs while we figured out the correct APIs to build into Ember. I'd vote to keep it private, but we should start collecting feedback as to how people are using queryParamsDidChange for the next iteration of query params (probably as part of a routing service).

**Comment by elidupuis** [comment]
👍  to QP support in a routing service.

Currently, I'm basically using my own service to keep track of QPs. When they get set by user action I can easily intercept and update my service directly—at the same time as setting the controller properties that are bound to the URL. However, `queryParamsDidChange` is proving to be very useful on page load as it allows me to get my service up-to-date immediately. I tried doing this on `controller.init` instead but the QPs all still have their default value instead of what's in the URL.

I suppose all of this is moot if there was a standard routing service that held all this info.

**Comment by rwjblue** [comment]
@knownasilya's service addon is pretty nice for this: https://github.com/knownasilya/ember-query-params.  It is good to feel out the space of using a service for this, so we can learn the best patterns and try to incorporate them upstream...

**Comment by elidupuis** [comment]
Cool. I'll take a look.

**Comment by knownasilya** [comment]
> but we should start collecting feedback as to how people are using queryParamsDidChange for the next iteration of query params (probably as part of a routing service).

@machty I'm currently using that action for that exact purpose, see the link that @rwjblue posted above.

**Comment by knownasilya** [comment]
This can be closed, #13398 was merged.

**Comment by michaelklopf** [comment]
What is the current state for queryParamsDidChange? Docs were added for the feature, but it's still private and possible to vanish at some point?

**Comment by knownasilya** [comment]
I think it's called intimate API, meaning people are using it so most likely there would be a deprecation if it was to go away before they removed it. So you'd at least have some warning if using it.
