### ISSUE TITLE
[Proposal] get helper

### ISSUE THREAD

**Issue by BenjaminHorn** [emberjs/ember.js#10878]
I just love the this addon from @jmurphyau

https://github.com/jmurphyau/ember-get-helper
https://www.npmjs.com/package/ember-get-helper

Do you see any reason not to have it in the core?

**Comment by mmun** [comment]
Dynamic paths isn't a pattern I want to promote and judging by the number of downloads its not popular enough to merit inclusion in core.

**Comment by BenjaminHorn** [comment]
Fair enough. I think it still deserves some publicity. Maybe it will be popular by the time.

**Comment by mmun** [comment]
You could write a blog post about it! :)

**Comment by stefanpenner** [comment]
cool add-on, maybe something we will consider post 2.0.

**Comment by mmun** [comment]
I'm thinking about revisiting this with glimmer.

**Comment by jmurphyau** [comment]
@wycats had a similar line of thinking in the last few comments on [#10501 Implement Glimmer Engine](https://github.com/emberjs/ember.js/pull/10501)

> It also kind of makes sense for us to include this get helper in Ember itself honestly. It's a primitive, like {{component}}.

Would love to see this happen
