### ISSUE TITLE
Using Ember.computed.alias in a computed property

### ISSUE THREAD

**Issue by tp** [emberjs/ember.js#10872]
Adding a computed property to the return value of a computed property of my component (which shall contain settings to configure child components), fails in Firefox with a "Too Much Recursion" error.

Is this something that is not supported with Ember or should this work (in which case I am willing to write up a test case).

The component contains the following code for the property (which value is used to create child component to edit object properties):

```
editorComponents: function() {
    let topicObj = this.get('topicObj');

    let editingCulture = Ember.computed.alias('editingCulture'); // expect this to use the outer components "editingCulture"

    return [{
        component: 'translatable-string-property-editor',
        settings: {
          propertyPath: 'name',
          editingCulture: editingCulture
        },
        topic: topicObj
      }];
  }.property('topicObj'),
```

**Comment by spruce** [comment]
In the line with your comment why not use:
```javascript
let editingCulture = this.get('editingCulture');
```
I don't know if this fixes your problem or not, but Ember.computed should only be used at object space and not in functions, since they will be rerun when your depending keys change.

**Comment by stefanpenner** [comment]
`Ember.computed.alias` and other `descriptors` that reside on `Ember.computed.*` are intended to be used as part of the base class rather then on an instance.


for example, when approaching your demo. I would likely separate out the `Settings` object.

```js
var Settings = Ember.Object.extend({
  editingCulture: Ember.computed.alias('editingCulture')
});

editorComponents: function() {
    let topicObj = this.get('topicObj');

    return [{
        component: 'translatable-string-property-editor',
        settings: Settings.create({
          propertyPath: 'name'
        }),
        topic: topicObj
      }];
  }.property('topicObj'),
```

*note: it is technically possible to add computed properties to any object on the fly, but I would deem that off the happy path, and recommend against doing it*

**Comment by rwjblue** [comment]
Agreed with @stefanpenner.
