### ISSUE TITLE
ObjectController deprecation warning and ArrayController content array

### ISSUE THREAD

**Issue by weegeekps** [emberjs/ember.js#10887]
I've got some logic inside of an ArrayController to hide elements using a forEach loop on the content array which is throwing the ObjectController deprecation warning and I think it may be in error.

The code in question:

```javascript
import Ember from 'ember';

export default Ember.ArrayController.extend({
    actions: {
        hideMarkersExcept: function (markerToKeep) {
            this.get('content').forEach(function (marker) {
                if (marker.id === markerToKeep.id) {
                    return;
                }

                marker.set('isVisible', false);
            });
        },
        showAllMarkers: function () {
            this.get('content').forEach(function (marker) {
                marker.set('isVisible', true);
            });
        }
    }
});
```

A couple bits for context.  The `marker` variable is an item from my model.  Both of these actions are called from views; `hideMarkersExcept` is sent on mouseEnter and `showAllMarkers` on mouseLeave.

The warning I'm getting is saying that since I'm doing set on `isVisible` that it's deprecated and I should switch it to `model.isVisible`.  However, since I'm calling set on a model element itself `model.isVisible` won't work as its undefined from this context.

Is the deprecation warning in this case correct behavior?

**Comment by rwjblue** [comment]
My guess is that you are using `itemController` which would mean that `marker` in this case is actually an instance of `Ember.ObjectController`.

--

I am sorry this has sat so long without comment.  Both `ArrayController` and `ObjectController` have been removed from the codebase during the 2.0.0 efforts.

I am going to close now, but we can reevaluate if my comment above doesn't help...
