### ISSUE TITLE
v1.11.3 is not published for the ember-source gem

### ISSUE THREAD

**Issue by pixelhandler** [emberjs/ember.js#10885]
See: https://rubygems.org/gems/ember-source/

There is no version for v1.11.3, so apps using the ember-source gem will get an error trying to update to v1.11.3

```
bundle update ember-source
Could not find gem 'ember-source (= 1.11.3) ruby' in the gems available on this machine.
```

**Comment by rwjblue** [comment]
Working on it.

**Comment by pixelhandler** [comment]
@rwjblue thanks my friend sorry for the fire drill.

**Comment by pixelhandler** [comment]
Isn't this just `rake gem` https://github.com/emberjs/ember.js/blob/master/Rakefile#L16 ?

**Comment by pixelhandler** [comment]
I'm just getting back into the swing of a rails app with a few ember client apps which has asset pipeline managing the template recompilation, I think the barber gem handles that. So basically without the security patch available as a gem the security patch is not available to my apps build pipeline. so without the gem the apps cannot get a security update. Is there another way I should be compiling templates in an app that is driven by asset pipeline?

**Comment by CNDW** [comment]
any word on the progress of this one? 1.11.3 has some regression fixes in it that are keeping me from bumping to 1.11 :(

**Comment by pixelhandler** [comment]
cc/ @wagenet can you `rake gem` v1.11.3 ?

**Comment by fivetanley** [comment]
published!
