### ISSUE TITLE
The `form` (or any other readOnly) attribute is not able to be bound to a valid element (button).

### ISSUE THREAD

**Issue by SlexAxton** [emberjs/ember.js#10894]
```js
tagName: 'button',
attributeBindings: ['form'],
form: 'foobar-form-id',
```

I think this comes from the fact that the [`form` attribute as a property is readOnly](https://html.spec.whatwg.org/multipage/forms.html#the-button-element:htmlformelement). If you use `setAttribute('form', 'foobar-form-id')` things are properly updated, but the code path that htmlbars takes is [`setPropertyStrict`](https://github.com/tildeio/htmlbars/blob/d1237d1ad82920c98f363174def6b5b1a07c8e26/packages/dom-helper/lib/main.js#L244) which is just `element[name] = value;`.

Seems reproducible, but hopefully this screenshot is enough:

![https://s3.amazonaws.com/f.cl.ly/items/093o1g0m0X0r1b1O1u0X/Screen%20Shot%202015-04-17%20at%203.49.39%20AM.png](https://s3.amazonaws.com/f.cl.ly/items/093o1g0m0X0r1b1O1u0X/Screen%20Shot%202015-04-17%20at%203.49.39%20AM.png)

You'll notice there's no `form` attribute even though it is in the `attributeBindings` list and has a value.

I thought this might be related to this? https://github.com/emberjs/ember.js/pull/10186 unsure though. Not much context.

Here's a fairly reduced test-case of property setting vs. setAttribute: http://jsbin.com/cujani/edit?js,output (note that only button2 ends up with a `form` attribute). It does seem to be the case that it's intended to be able to be updated, since the [spec explicitly outlines how to handle updates](https://html.spec.whatwg.org/multipage/forms.html#association-of-controls-and-forms:category-form-attr-3).

To make matters worse, it appears that chrome dev, chrome canary, and chromium all throw an error at this line now (which is how I found this out). I didn't report that as the bug because I'm the one using beta browsers, but I think the error might be correct?

Screenshot of that:

![http://slex.me/image/1D3c1H303o0h/Screen%20Shot%202015-04-17%20at%203.41.27%20AM.png](http://slex.me/image/1D3c1H303o0h/Screen%20Shot%202015-04-17%20at%203.41.27%20AM.png)

The error message is: 

> Uncaught TypeError: Cannot set property form of #<HTMLButtonElement> which has only a getter

Which I mostly just paste here for google-ability for when other people hit this. It's not that helpful :D.

So I think we might need a whitelist of readonly attributes? Are there other ones?

**Comment by SlexAxton** [comment]
@mmun - just pinging to see if this premise sounds correct. If so, I might try my hand at patching it. Seems handlebars-y so I chose you, sorry for the direct ping.

**Comment by rwjblue** [comment]
@SlexAxton - I think this is essentially the same issue as https://github.com/emberjs/ember.js/issues/11221, can you confirm?

**Comment by SlexAxton** [comment]
Yea, look like the same thing. Though I spose this issue could have saved the first half of the sleuthing on that issue :smile: -- maybe I'll be brave and subscribe.

I agree with the whitelist approach, and I think it'd actually not be crazy to find a list of `readOnly` attributes which are the attributes that throw.

**Comment by stefanpenner** [comment]
> I agree with the whitelist approach, and I think it'd actually not be crazy to find a list of readOnly attributes which are the attributes that throw.

**Comment by stefanpenner** [comment]
Should be fixed now: https://github.com/tildeio/htmlbars/blob/d63b675a579bade22124d02415da7a996cda4ecb/packages/dom-helper/lib/prop.js#L42-L65
