### ISSUE TITLE
  Could not import MarkdownIt in Ember CLI

### ISSUE THREAD

**Issue by changeweb** [emberjs/ember.js#10898]
I've installed markdown-it via both bower and npm and trying to import it in my Ember app. But Could not import it.

I'm trying to use [Markdown-it][1] in Ember Helper. First I installed it with **Bower** and tried to import it. In `Brocfile.js`

    app.import('bower_components/markdown-it/dist/markdown-it.js');
In helper:

    import MarkdownIt from "markdown-it";
This is showing error `Could not find module: markdown-it`. Then I tried to use [Ember-browserify][2] and install `Markdown-it` via npm. I tried to import it in helper

    import MarkdownIt from "npm:markdown-it";
 
    export default Ember.Handlebars.makeBoundHelper(function(input){
        var result = MarkdownIt.render(input);
        return new Ember.Handlebars.SafeString(result);
    });
This is showing error `TypeError: a.default.render is not a function`.

I also tried using `/* global MarkdownIt */`. Nothing is working.

  [1]: https://github.com/markdown-it/markdown-it
  [2]: https://github.com/ef4/ember-browserify

**Comment by trek** [comment]
Hi @changeweb, this sounds like a great question for StackOverflow. The Ember.js community is very active there and you'll get an answer much faster in that venue. Can you post a link to your question here once you've asked it?

**Comment by changeweb** [comment]
I know this is not the right place to put question instead of issues. Actually I've posted it in StackOverflow and Ember Discuss but got no response. Here http://stackoverflow.com/q/29713298/2429040. I badly need a this to work for my project.

**Comment by trek** [comment]
>  I badly need a this to work for my project.

Totally understandable, but please don't repost to Issues with questions because nobody has responded in the 8 hours that were overnight Friday night/Saturday morning for half the planet. This is an all volunteer effort and even during the work week it's not unusual for a question to take a few days for someone to answer.

**Comment by trek** [comment]
There is a reply on SO now.
