### ISSUE TITLE
#each with index issue on 32 bit iOS

### ISSUE THREAD

**Issue by simonjefford** [emberjs/ember.js#10897]
We've seen an issue in one of our apps where `{{#each foos as |foo index|}}` only outputs an index the first time round. We've only seen this issue on 8.3 on an iPhone 4S and an iPad 2. On an iPhone 6 and an iPhone 5S it works fine. Which is what makes me suspect it's another issue with 32bit iOS 8.

I have a repro (an Ember-cli app that's as minimal as I could make it) at https://github.com/simonjefford/ios-each-with-index-issue. The commit at https://github.com/simonjefford/ios-each-with-index-issue/commit/b4bf0a76ac34c0e1e9d10d824f99a36dfcd95064 contains everything.

Interestingly this commit - https://github.com/simonjefford/ios-each-with-index-issue/commit/9bd1ae477c08add086f26d890464602264a1fb01 seems to make things work.

**Comment by simonjefford** [comment]
I've just reproduced it on canary as well - https://github.com/simonjefford/ios-each-with-index-issue/tree/canary

**Comment by stefanpenner** [comment]
Damnit. Is this sounds like the armv7 Safari bug again

**Comment by stefanpenner** [comment]
for reference the upstream bug report: https://bugs.webkit.org/show_bug.cgi?id=138038

I gotta take care of a few other things, then i'll circle back and look at this.

**Comment by stefanpenner** [comment]
actually this seems unrelated to the above issue (i think....) although it seems surprising

**Comment by simonjefford** [comment]
Any news? We've worked around it but I'd be interested to know if this is a bug or not.

**Comment by stefanpenner** [comment]
unfortunately I have not had a chance to investigate further.

**Comment by rwjblue** [comment]
@simonjefford - Would you mind checking against 2.0.0 (or canary)?

**Comment by rwjblue** [comment]
I'm unsure if this is still an issue, we haven't had any addition reports so I'm going to close for now.  I'm happy to reopen if it is still cropping up....
