### ISSUE TITLE
set and get methods are undefined 

### ISSUE THREAD

**Issue by chandruaskutty** [emberjs/ember.js#10909]
I am trying to change the property of ember object which found through the findBy api in that object get and set api are undefined but still browser's dev tool shows availability of those please refer the attached images.

![ember-object](https://cloud.githubusercontent.com/assets/885678/7224394/339255d6-e74f-11e4-9fe9-a5647447ef0c.png)

**Comment by changeweb** [comment]
Questions are better suited for stackoverflow.com. You should give some code.

**Comment by chandruaskutty** [comment]
Look at the changeDisplayName function 

<script type="text/x-handlebars">
		
			{{#each model.folders}} 

				<div {{action 'changeDisplayName' this}}>
          				{{display_name}}
				</div>

			{{/each}}

	</script>


<script type="text/javascript">
	var App  = Em.Application.create({});

	App.ApplicationRoute  = Em.Route.extend({

			model : function(){
				console.log(" Application route is ");

				return folders;  
			}

	})


	App.ApplicationController  = Em.Controller.extend({

			actions :  { 

				changeDisplayName	 : function(data){

						console.log(data.get," changeDisplayName ",data);   

						data['display_name'] = "Fun is here ";
 
				}
			} 

	})


var folders = {

   "folders":[
      {
         "is_visible":true,
         "display_name":"March",
         "folder_id":1,
         "link_name":"march",
         "module_id":1,
         "folders":[],
         "success":true,
         "elements":[],
         "is_home":true
      },
          
   ]
}
</script>

**Comment by chandruaskutty** [comment]
Look at the changeDisplayName function 


template
		
			{{#each model.folders}} 

				<div {{action 'changeDisplayName' this}}>
          				{{display_name}}
				</div>

			{{/each}}



script

	var App  = Em.Application.create({});

	App.ApplicationRoute  = Em.Route.extend({

			model : function(){
				console.log(" Application route is ");

				return folders;  
			}

	})

	App.ApplicationController  = Em.Controller.extend({

			actions :  { 

				changeDisplayName	 : function(data){

						console.log(data.get," changeDisplayName ",data);   

						data['display_name'] = "Fun is here ";
 
				}
			} 
	})

var folders = {

   "folders" :  [
            {
                   "is_visible":true,
                   "display_name":"March",
                   "folder_id":1,
                   "link_name":"march",
                   "module_id":1,
                   "folders":[],
                   "success":true,
                   "elements":[],
                 "is_home":true
          },          
       ]
}

**Comment by herom** [comment]
Your `data` is a POJO and therefore has no `set` or `get` method. If you want to use `set` and `get` on a POJO you have to use it from the Ember namespace like: `Ember.set(data, 'displayName', 'Fun is here!')`. If `data` happens to be an `Ember.Object` you can use it like `data.set('displayName', 'Fun is here!')`.

**Comment by chandruaskutty** [comment]
@herom  works fine , Thank you !
