### ISSUE TITLE
Ember.FEATURES should be merged

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#10901]
Otherwise, when using a custom development build of ember with an app that has feature flags enabled of its own, they will entirely overwrite those provided by ember.

So for example, `new-computed-syntax` flag is lost, an a custom build of canary is entirely un-usable. https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/computed.js#L587-L594 

the merge should likely happen here: https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/core.js#L100-L102

@rwjblue you mentioned some string replace in the build process, will changes also be needed there?

**Comment by rwjblue** [comment]
#10905 should take care of this.

**Comment by stefanpenner** [comment]
<3
