### ISSUE TITLE
Application resolver doesn't properly singularize / pluralize types

### ISSUE THREAD

**Issue by foxnewsnetwork** [emberjs/ember.js#10914]
I have the following folder structure in my app:
```
- app
...
|-- models
  |-- complex-thing.js
|-- strategies
  |-- complex-thing.js
...
```
In the case of strategies under the strategies directory:
```coffee
container.lookupFactory "strategy:complex-thing" # resolves null
container.lookupFactory "strategie:complex-thing" # resolves the correct factory
```
This leads to me believe somewhere in the resolver, Ember is just adding / taking away a "s" instead of properly using Ember.String.singularize. It'd be great if the resolver could handle the cases where users have directories with names like "elves", "calves", "oxen", etc.

**Comment by rwjblue** [comment]
@foxnewsnetwork - Assuming you are talking about an Ember CLI app, then this is done by the [ember-resolver](https://github.com/ember-cli/ember-resolver) and the ability to have custom pluralization was added in https://github.com/ember-cli/ember-resolver/pull/68.

You can add something like the following:

```javascript
import Resolver from 'ember/resolver';

export default Resolver.extend({
  pluralizedTypes: {
    'sheep': 'sheep'
    'config': 'config'
  }
})
```
