### ISSUE TITLE
Missing a public api for detecting whether a class extends a mixin

### ISSUE THREAD

**Issue by igorT** [emberjs/ember.js#10911]
Currently we hack around it in Ember and Ember Data by checking `factory.PrototypeMixin`, like for example https://github.com/emberjs/ember.js/pull/10612/files#diff-03921e1a2155be175f9ce59e0c470173R21

**Comment by stefanpenner** [comment]
If an API is added it should likely be: `Class.hasInstanceMixin(mixin)`

**Comment by rwjblue** [comment]
I'm happy to review + merge a feature adding `hasInstanceMixin`, but it doesn't seem to be an issue with the framework so I'm closing this issue for now...
