### ISSUE TITLE
[FastBoot] Memory leaks in FastBoot mode

### ISSUE THREAD

**Issue by joshvfleming** [emberjs/ember.js#10910]
Preliminaries
---

Simply stated, our use case is a small Ember application running in a Nashorn script engine on the JVM. Nashorn is an optimizing JIT JavaScript compiler, similar to V8. The test case is a medium-complexity page consisting of an update stream, similar to the news feed on sites like LinkedIn and Facebook. The figure below shows an example rendering of the test page.

<table>
<tr><td align="center">
<img src="https://cloud.githubusercontent.com/assets/212140/7230962/0ba024fe-e740-11e4-8e39-43ed6fa1a88d.png" alt="stream" height="300px"><br>
Rendered stream
</td>
<td align="center">
<img src="https://cloud.githubusercontent.com/assets/212140/7231029/955f0d86-e740-11e4-98d5-49f301176fcf.png" alt="stream-html" height="300px"><br>
Raw output
</td>
</tr>
</table>

The page continues on for 10 updates. Each update consists of a profile picture, headline, brief description, comments, and -- what will become important later -- a "like" action. The data for the page is fetched from static json files.

Our test methodology is very simple: use the Ember "visit" function to render the exact same page many times in a serial loop, and record the results for each iteration. This roughly approximates the conditions that the app will experience when running on a server. The figures below show the results of a test run.

<img alt="heap-leak" src="https://cloud.githubusercontent.com/assets/212140/7231126/58abfcfe-e741-11e4-91de-c9426ccf4ce6.png" height="300px">

The first thing to note here is the runaway heap usage. The figure above shows a dramatic increase in live heap allocations as time goes by, reaching nearly 4gb by the 2000th iteration. Each rendering of the page should be entirely independent of any previous render, so there should not be significant growth in memory consumption over time. Clearly there's a leak of some kind.

<img alt="render-time-leak" src="https://cloud.githubusercontent.com/assets/212140/7231241/344e478a-e742-11e4-9919-737821a79399.png" height="300px">

The figure above shows how long it takes to render the test page for each iteration of the test. Everything renders very slowly at first, since the script engine is still figuring out how to compile and optimize the code. After the 500th iteration or so, average performance is pretty good. Note the frequent and large vertical blips, however. These are caused by garbage collection pauses.

Leak 1: ActionHelper
---

Each item in the stream has a corresponding template that defines the layout for its view. One component of the layout for a stream item is the "like" button.

<img alt="actionhelper0" src="https://cloud.githubusercontent.com/assets/212140/7231284/66f54184-e742-11e4-92db-73f6607fe033.png" width="500px">

The figure above shows the part of the update template containing the "like" action. When the template is rendered, the "action" helper signals that we'd like to handle interactions with the button, and we eventually wind up in Ember's "actionHelper" function.

<img alt="actionhelper1" src="https://cloud.githubusercontent.com/assets/212140/7231311/8e420510-e742-11e4-9c82-8f23c95201d5.png" width="500px">

https://github.com/emberjs/ember.js/blob/ffedc10ea3c11ff17040175b28d3bbe3bfda24a3/packages/ember-routing-htmlbars/lib/helpers/action.js#L305

The "actionHelper" function receives all relevant information about the potential interaction, including the "view" in which it might happen. It then places the view into the "actionOptions" object, and passes this object to the "registerAction" function.

<img alt="actionhelper2" src="https://cloud.githubusercontent.com/assets/212140/7231328/a9f69834-e742-11e4-9d46-522ab14a6ac8.png" width="500px">

https://github.com/emberjs/ember.js/blob/ffedc10ea3c11ff17040175b28d3bbe3bfda24a3/packages/ember-routing-htmlbars/lib/helpers/action.js#L72

In the "registerAction" function, an event handler object is built and then placed into the global action registry object "ActionManager.registeredActions". ActionManager is not really exposed as a global, but it's always reachable from some global variable, so this registry object is never collected. And since the "handler" function for each action closes over the "options" object, which in turn contains the "view" object, the views, model objects, templates, etc. are also never collected.

We've temporarily worked around the leak by manually clearing the "registeredActions" object after each render, with something like the following:

```javascript
  for (var action in ActionHelper.registeredActions) {
    delete ActionHelper.registeredActions[action];
  }
```

Note that we can't simply set "registeredActions" to {}, because it's aliased in other places, and doing so would only wipe out this one reference to the object.

**Note:** As part of a follow-up investigation, @nathanhammond found that there actually is code in Ember that's meant to clean up the "registeredActions" object here:

https://github.com/emberjs/ember.js/blob/ffedc10ea3c11ff17040175b28d3bbe3bfda24a3/packages/ember-routing-htmlbars/lib/helpers/action.js#L111

It seems that the code path that triggers this event is never executed in FastBoot mode, however.

Leak 2: Application Creation
---

The node unit tests in Ember suggest that the proper usage is to create a new Application object for each run.

<img alt="app1" src="https://cloud.githubusercontent.com/assets/212140/7231379/f301d836-e742-11e4-98a9-b61735397e31.png" width="500px">

https://github.com/emberjs/ember.js/blob/ffedc10ea3c11ff17040175b28d3bbe3bfda24a3/tests/node/app-boot-test.js#L125

However, this usage leads to another leak. The figure below shows that the Application class extends the Namespace class.

<img alt="app2" src="https://cloud.githubusercontent.com/assets/212140/7231403/186b804a-e743-11e4-9a10-d9340ff18993.png" width="500px">

https://github.com/emberjs/ember.js/blob/ffedc10ea3c11ff17040175b28d3bbe3bfda24a3/packages/ember-application/lib/system/application.js#L196

The initial part of the Namespace definition is shown in the figure below.

<img alt="app3" src="https://cloud.githubusercontent.com/assets/212140/7231428/387cc560-e743-11e4-9cca-193f9831cfa5.png" width="500px">

https://github.com/emberjs/ember.js/blob/ffedc10ea3c11ff17040175b28d3bbe3bfda24a3/packages/ember-runtime/lib/system/namespace.js#L39

Whenever an Application object is created, the "init" function is called, and pushes the created application onto the global "NAMESPACES" array. If we create a new Application object for each render, then this array grows constantly over time, along with all the objects reachable from an Application.

We've worked around this one by creating a single Application instance and reusing it for each render. This seems to work fine, but it's not clear if it's the intended usage.

**Note:** We did try to use ```Ember.run(Application, 'destroy');```, but it fails here:

https://github.com/emberjs/ember.js/blob/a09f1440ba5cef825133c65ba2718ca1849710d5/packages/ember-application/lib/system/application.js#L765

with the following error:

```
TypeError: Cannot read property "destroy" from undefined
```
It seems that ```this.__deprecatedInstance__``` is never being set in the "visit" flow.

Conclusion
---

With both leaks patched, the graphs look very much better.

<img alt="heap-comparison" src="https://cloud.githubusercontent.com/assets/212140/7231464/5b7881e4-e743-11e4-9325-bd9f7d6543c5.png" height="300px">

The figure above shows a comparison of heap usage before and after the memory leaks are removed. Some amount of leakage remains that we haven't yet identified, but otherwise it's dramatically improved.

<img alt="render-time-comparison" src="https://cloud.githubusercontent.com/assets/212140/7231487/7eeb0692-e743-11e4-93d3-885ccc6c00de.png" height="300px">

The figure above shows the impact on render times. Most of the GC noise has been eliminated, and the overall render times are slightly lower.

Update: Test App
---
I've create an isolated test app that demonstrates the leak on node. You can find it here:

https://github.com/joshvfleming/fastboot-leaktest

Clone the repo, and do:

`npm install`
`bower install`
`ember build -prod`
`node scripts/test.js`

Select "ember#canary" if given an option in the third step. After running the last command, note the accumulation of action handlers, and watch the memory usage in your profiler.

**Comment by chadhietala** [comment]
Hey @joshvfleming, do you have the patch mentioned above? :+1: on the issue write up.

**Comment by joshvfleming** [comment]
@chadhietala Yes, but it's a temporary workaround patch on our internal wrapper api. I'm not yet confident enough to offer an Ember patch. :)

**Comment by stefanpenner** [comment]
> I'm not yet confident enough to offer an Ember patch. :)

submit it, that way we can provide feedback.

**Comment by stefanpenner** [comment]
A quick skim yields the latest work to separate, App and appInstances will not cause multiple namespaces to leak.

1. app is created
2. multiple appInstances are created
  * https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/application-instance.js#L35 
 

this feature is still behind a flag: https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/application.js#L796-L831 but may be a better starting point for your use-case.

**Comment by stefanpenner** [comment]
As for the actions stuff, this seems like it will still cause issues. Interestingly, that global isn't even really needed in fast-boot mode, as DOM events -> actions isn't a thing for SSR.

**Comment by joshvfleming** [comment]
@stefanpenner Sorry, I should've mentioned that -- I'm using the latest canary build of Ember.

As for sharing a repo, I'll see if I can put together a public version of the one I'm using. In the meantime, it should happen for any sample app that has a template "action" of some kind, if you call "visit" for the same route repeatedly.

**Comment by stefanpenner** [comment]
> Edit: you can also reproduce the Ember.run(Application, 'destroy'); thing by adding it to one of the tests in https://github.com/emberjs/ember.js/blob/master/tests/node/app-boot-test.js

i'll look into this now.

**Comment by stefanpenner** [comment]
@joshvfleming so I realized, nothing purges app instances after visits, so even with destroy. We likely continue to leak.

some cleanup: https://github.com/emberjs/ember.js/pull/10912
making destroy work: https://github.com/emberjs/ember.js/pull/10913

I only had a few moments today to look at this, and am off to do more pairing. But, I will dig into this more once I am back from pairing.

**Comment by joshvfleming** [comment]
Thanks @stefanpenner. I'm still working on a sample app that demonstrates the leak outside our environment. Should be ready by tomorrow.

**Comment by joshvfleming** [comment]
@stefanpenner I managed to get the test app repo up:

https://github.com/joshvfleming/fastboot-leaktest

Run `npm install`, `bower install`, `ember build -prod`, and then do:

`node scripts/test.js`

You should see the number of actionHelpers accumulating, and also a steady increase in memory usage.

**Comment by stefanpenner** [comment]
Awesome. Thanks for doing the leg work. My day is a bit busy, but I'll try to carve out time.

**Comment by stefanpenner** [comment]
I believe currently canary and fastboot are currently out of sync. Hopefully when they "work" with each other again, and now that https://github.com/emberjs/ember.js/pull/10913 is merged  i'll take another swing at fixing this leak.

**Comment by tomdale** [comment]
FastBoot should be back to good now (thanks to @rwjblue). I am working on making `{{{tripleCurlies}}}` work today and hopefully will have time to look into this this week.

**Comment by stefanpenner** [comment]
I believe several fixes have landed, that:

1. allow destroy to be called on the AppInstance
2. fix some unrelated to your analysis, but potentially related leaks

So, I have given your example a try, after [upgrading to latest canary](https://github.com/stefanpenner/fastboot-leaktest/commit/8db4d24b2e8f3758f5e7b37d90056883b229f9c2) and [ensuring the `instance` is destroyed](https://github.com/stefanpenner/fastboot-leaktest/commit/8db4d24b2e8f3758f5e7b37d90056883b229f9c2) the RSS levels out and stays stable.

I have submitted ahttps://github.com/joshvfleming/fastboot-leaktest/pull/1

**Comment by joshvfleming** [comment]
This is great, thanks @stefanpenner ! I'll check it out today.

**Comment by joshvfleming** [comment]
Confirmed:

![memory](https://cloud.githubusercontent.com/assets/212140/8678685/d8e9658a-2a23-11e5-99a5-864ee16e4000.png)

**Comment by tomdale** [comment]
Yessssss

**Comment by joshvfleming** [comment]
Whoops, it looks like there is actually a leak remaining: the NAMESPACES leak. This didn't appear in the test app previously, because it was creating and reusing only one application. I've updated it to create an application for each request.

You should see steadily increasing RSS if you run the test script now.

**Comment by chadhietala** [comment]
This may be related to issues with tests as well. https://github.com/emberjs/ember.js/issues/11748

**Comment by stefanpenner** [comment]
> Is the intended usage that you create a single Application and use it to service all the requests? If so there's not really a leak here.

yes

**Comment by joshvfleming** [comment]
Cool, thanks @stefanpenner . Looks like it's all sorted out then.
