### ISSUE TITLE
Could outlet be made to work with block params ?

### ISSUE THREAD

**Issue by toranb** [emberjs/ember.js#10922]
Today the outlet hbs helper will blow up if I push a non string value. But w/ block params it would be handy to pass in index for dynamic outlet names/etc.

I assume this isn't supported for a reason. If I'm incorrect ... would the team be open to a PR that allows block param index values (for outlet) ?

```js
{{#each model as |foo index|}}
    {{#link-to "foo.detail" index}}details{{/link-to}}
    {{outlet index}}
{{/each}}
```

**Comment by ef4** [comment]
I actually think this can be made to work just fine.

The assertion about using a non-quoted argument was due more to historical cleanup -- we used to treat {{outlet "name"}} and {{outlet name}} as equivalent, so the assertion is there to get people to stop doing that. If we think everybody has has time to move to quoted strings, it would be safe to offer the bound argument form.

**Comment by ef4** [comment]
In glimmer this feature would probably be about a 5 to 10 line change.

**Comment by toranb** [comment]
Understood - for now it seems like I'll need to fork/maintain my special outlet as this would conflict w/ the dep warnings in place for 1.x

**Comment by toranb** [comment]
Any tips for how to avoid forking it? I'm currently trying to see if I can invoke the original outlet after I "stringify" the index. The below blows up currently (mostly looking to let me know if I'm headed in the right direction).

```js
Ember["default"].Handlebars.helpers.outlet.helperFunction.call(this, someNewArgs)
```

**Comment by ef4** [comment]
I don't think you have to fork, you can just add a custom helper. Something like:

```js
export function specialOutletHelper(params, hash, options, env) {
  var view = env.data.view;
  var viewClass = view.container.lookupFactory('view:-outlet');
  hash._outletName = params[0];
  options.helperName = 'special-outlet'
  return env.helpers.view.helperFunction.call(this, [viewClass], hash, options, env);
}
```

This doesn't give you a bound name (if the outlet name parameter changes, we won't rerender). But it does work for your case when you just want to use array indices that will remain stable for the life of the outlet.

**Comment by ef4** [comment]
@wycats just pointed out to me that this feature is actually implemented in glimmer already, we just need to decide to remove the legacy assertion

**Comment by toranb** [comment]
So I don't need to make a custom HTMLBars helper /register it? (I'm using ember 1.11)

Ember.HTMLBars.registerHelper('custom-outlet', myOutletHelper);

**Comment by ef4** [comment]
Yes, you would register the function I showed above with something like

```js
Ember.HTMLBars.registerHelper('special-outlet', specialOutletHelper);
```

**Comment by toranb** [comment]
The confusing part is that in ES6 land w/ ember-cli you typically "export" out a fn from the helpers directory... but inside ember source I see Ember.HTMLBars.registerHelper for things like outlet. If I register this (as you showed above) how can I expose this for templates in the app itself?

**Comment by ef4** [comment]
I would call `registerHelper` from `app.js`.

**Comment by toranb** [comment]
This is what I have currently that *seems to work*

```js
export default Ember.HTMLBars.makeBoundHelper(function(params, hash, options, env) {
}
```

**Comment by toranb** [comment]
Quick update for anyone who might follow

I was able to "access" the custom hbs helper using the export default Ember.HTMLBars.makeBoundHelper syntax above ... but it wasn't providing me a stream like the vanilla outlet helper.

Instead I did what @ef4 suggested above (doing the below in my app.js file) and it works ... with (again) one exception. I had to use _registerHelper instead of registerHelper for some odd reason

```js
var wat = function specialOutletHelper(params, hash, options, env) {
  var view = env.data.view;
  var property = "main";
  if (params.length > 0) {
      property = params[0] + "";
  }
  var viewClass = view.container.lookupFactory('view:-outlet');
  hash._outletName = property;
  options.helperName = options.helperName || 'outlet';
  return env.helpers.view.helperFunction.call(this, [viewClass], hash, options, env);
};

Ember.HTMLBars._registerHelper('custom-outlet', wat);
```

**Comment by intuitivepixel** [comment]
@toranb current ember canary (including glimmer) breaks this `custom-outlet` hack lamentably, have you tried canary yet and got a workaround?

**Comment by rwjblue** [comment]
Canary allows for bound outlet names.

**Comment by intuitivepixel** [comment]
@rwjblue this sounds extremely elegant, but how do you use/implement them?

**Comment by toranb** [comment]
@rwjblue what is the syntax for "bound outlet names" like you mention? Does this mean the Ember assert that previously blew up was removed in canary?

**Comment by ef4** [comment]
Yes, the assertion is removed and `{{outlet foo}}` does the right thing.

**Comment by ef4** [comment]
https://github.com/emberjs/ember.js/pull/11029

**Comment by toranb** [comment]
@ef4 excellent! I'll verify my "hack" works in canary tonight and update the blog post I wrote about it -thanks again!

**Comment by intuitivepixel** [comment]
@toranb that's great - you have an early adopter for the hack right here :) thanks!!

**Comment by toranb** [comment]
@rwjblue @ef4 is it possible to use jsbin w/ glimmer yet? If so what is the src for ember to get that version?

**Comment by mixonic** [comment]
@toranb just use canary.

* builds.emberjs.com/canary/ember.debug.js
* builds.emberjs.com/canary/ember-template-compiler.js

**Comment by toranb** [comment]
@mixonic thanks! With your helpful js I was able to get a mostly working glimmer branch of my nested example

https://github.com/toranb/named-outlet-inside-each-loop-example/tree/glimmer

The only issue I'm still trying to fix/work through is the "index zero" (ie- the first item in the loop).

If anyone uses the example I link to above - be sure to throw out the ember.debug.js/and the compiler after you bower install and replace them with the latest canary build shown above.

**Comment by intuitivepixel** [comment]
@toranb I tried your example above, and also used canary versions as described, but accessing `env` in the custom helper still throws `Uncaught TypeError: Cannot read property 'data' of undefined`. (https://github.com/emberjs/ember.js/issues/11080) I didn't even came to the index problem you mention. Any hints?

**Comment by intuitivepixel** [comment]
@toranb I came around the `index 0` problem by using the id or the record I'm looping over like `{{outlet record.id}}` and then in the renderTemplate `'outlet': model.get('id'),`

**Comment by toranb** [comment]
@intuitivepixel would you mind doing a quick PR to the glimmer branch for that example?

https://github.com/toranb/named-outlet-inside-each-loop-example/tree/glimmer

I tried to use model.get("id") for the outlet but how did you disconnect outlet? I *could* reach into the controller.model to get that id but I'm curios what you did :)

**Comment by intuitivepixel** [comment]
@toranb there you go: https://github.com/toranb/named-outlet-inside-each-loop-example/pull/1

**Comment by toranb** [comment]
@intuitivepixel thanks for the pull request - I'll update my blog tonight and give you a legit mention :)

**Comment by intuitivepixel** [comment]
@toranb great! thx! :)

**Comment by toranb** [comment]
For anyone following along -here is the blog post I put together with help from @ef4 and @intuitivepixel 

http://toranbillups.com/blog/archive/2015/04/21/how-to-use-outlets-from-within-your-each-loop/

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
