### ISSUE TITLE
Ember does not render properly svg tags on other routes than index

### ISSUE THREAD

**Issue by vladuemilian** [emberjs/ember.js#10923]
Hello,

I have a weird issue using Ember 1.11 (built with ember-cli) and [D3 Pie chart][1].

The Pie Chart is not displayed properly on ember routes. It works only on 
index route (index.hbs).

The generated HTML code is the same on routes templates and index.hbs. I've used the same view/component on index.hbs as on routes.

You can fix this issue if you go to Inspect Element and remove entire <head></head> tag (removing it's content line by line does not fix it!). This is weird.

I've installed a sample Ember application on this address:
http://weird.ember.socketo.com/

On the index you will see the chart. On the menu routes, there is the same chart (rendered with same view as it was rendered on index.hbs), but not displayed properly (it works a bit when you hover over that area).

The HTML code generated by the Pie chart view is the same on all pages. If you copy the code from `<div id="pieChart">..</div>` and paste it in a empty static html page, the chart will be rendered correctly.

This issue can be reproduced using: Firefox/Chrome. In safari it seems to work.

[Here][2] is a paste2 with view that renders the chart.

The entire application code before build can be found [here][3].

  [1]: http://d3pie.org/
  [2]: http://paste2.org/C2ZDK7n3
  [3]: http://weird.ember.socketo.com/d3app.zip

**Comment by stefanpenner** [comment]
you likely have baseHREF set, a poor ember-cli default that is likely causing you grief.

cc @mixonic

**Comment by Little-Jon** [comment]
This is related to how d3pie fills its pie slices with a pattern, and it seems to be unrelated to Ember.

See the below response on GitHub (which, given that I'm relatively new to Ember, may be inaccurate regarding reasoning. The workaround, however, works just fine):

http://stackoverflow.com/questions/29780096/ember-error-while-rendering-d3-pie-chart-chart-are-not-displayed-properly/29782674#29782674

**Comment by vladuemilian** [comment]
Thank you Little-Jon. Your fix worked for me too.

**Comment by mariusleu** [comment]
@Little-Jon it worked for me as well. Thanks.
