### ISSUE TITLE
How to implement Ember.Copyable w/ Ember 1.11?

### ISSUE THREAD

**Issue by perlun** [emberjs/ember.js#10927]
Hi,

With Ember 1.8.1, we have been using a pattern like this (CoffeeScript):

```
copy: (deep) ->
  props = {}
  for key in Ember.get(@constructor, 'attributes.keys.list')
    props[key] = Ember.get(@, key)
  @get('store').createRecord('foo', props)
```

With 1.11, `attributes.keys` has been renamed to `attributes._keys` which indicates to me that it is a private API which I should not use. How do I implement `Ember.Copyable` in a proper way with Ember 1.11?

**Comment by perlun** [comment]
I think I solved this: `Ember.keys(this)` would be the "right" way to get the list of keys these days. Right? If so, just close this issue - thanks.

**Comment by truenorth** [comment]
Ember.keys is part of the [public API](http://emberjs.com/api/classes/Ember.html#method_keys), so you should expect it to stick around for at least Ember 1.x :)

**Comment by stefanpenner** [comment]
this is an ember-data question not an ember question.

i believe constructor.attributes is a Ember.Map, whos public API for enumeration is `.forEach`

**Comment by stefanpenner** [comment]
seems to have gone stale.
