### ISSUE TITLE
URL does not get updated when going back and forth with link-to' and back-button, location: history

### ISSUE THREAD

**Issue by Eptis** [emberjs/ember.js#10931]
Hey all,

this is a minor issue, but still an annoying one. I've attached example code below, since a jsbin won't display url updates. The issue is as follows:

If you go from the ColorsRoute to the ColorRoute with a link-to and then go back with the back-button and then to the same link again with the link-to, the url does not get updated.

https://dl.dropboxusercontent.com/u/4272749/emberjs_pushhistory_issues.zip
(run this with Python -m SimpleHTTPServer or something)

**Comment by Eptis** [comment]
Tested this in both of the latest versions of firefox and chrome.

**Comment by pixelhandler** [comment]
@Eptis I tried to download your code example but could not. Can you create a new example in a current version of Ember or using the LTS (2.4.6) version?
