### ISSUE TITLE
How to inject store using Ember.inject?

### ISSUE THREAD

**Issue by opsb** [emberjs/ember.js#10934]
Ember.inject.service / Ember.inject.controller are really useful but I can't seem to find a way to do the same for the store. Is there any way to do this yet?

**Comment by teddyzeenny** [comment]
The store would be registered as a service (`service:store`), which means we can do `Ember.inject.service('store')`. It seems ED already [registers it as a service](https://github.com/emberjs/data/blob/174fc94488d7e66ebb8b61e3bef142c0d051edca/packages/ember-data/lib/initializers/store.js#L40).

**Comment by opsb** [comment]
Ah, I'm using ember-orbit, that's why it's not there, I'll take a look at what ED does.
