### ISSUE TITLE
[Bug] queryParams issue when using a dynamic controller assignment

### ISSUE THREAD

**Issue by thec0keman** [emberjs/ember.js#10938]
We have a case where we need to load a different template / controller depending on various attributes of a model.  Currently we have been doing something like:

```
export default Ember.Route.extend({

  afterModel: function(model) {
    var controller = model.getControllerName();

    this.set('controllerName', controllerName);
  }
```

This works great, however we ran into an issue when one of those ad hoc controllers has a query-param.  The route doesn't properly setup the query-param and it raises the following exception when you try and change the query-param:

 `Cannot read property 'urlKey' of undefined`  [jsbin](http://jsbin.com/giyokipila/1/edit?html,js,output).  

What is interesting is if the controller that matches the route name isn't defined everything works as expected.  The short term solution is to define the query-param on the controller that matches the route name and everything works great, but it looks like either this approach isn't supported or there is a bug.

**Comment by codebruder** [comment]
I came across the same bug when i tried to render an other controller with queryParams inside the renderTemplate hook. I solved it the same way as @thec0keman .

**Comment by pixelhandler** [comment]
@thec0keman @codebruder can you provide an updated example (reproduction of the issue) using a current release of Ember.js or the LTS release (2.4.6) ?

**Comment by Serabe** [comment]
Closing this as inactive.
