### ISSUE TITLE
Error when defining Ember.computed.alias in Ember.Object.reopen()

### ISSUE THREAD

**Issue by herom** [emberjs/ember.js#10936]
I get an Error if I want to (re-) set a property to be of `Ember.computed.alias` of an `Ember.Object` with `this.reopen()` which is run after the `init` hook after the `init` hook:

```javascript
Uncaught TypeError: existingDesc.teardown is not a function
   defineProperty                                                             @ ember.debug.js:15184
  applyMixin                                                                     @ ember.debug.js:14124
  CoreObject.PrototypeMixin.mixin.Mixin.create.reopen @ember.debug.js:31888
  setup                                                                             @ calculator.js:84
```

The `setup` method reveals the following code around line 84:
```javascript
else if (element.isAreal) {
          this.reopen({ // this is line 84
            area: alias("__room.area"), // this is causing the error, as the `existingDesc` only consists of `{altKey: '__room.area', isDescriptor: true, __proto__: Object}`
            correctedArea: computedProperty("area", "correction", function correctedCalculatorArea() {
              var project = get(this, "__parent");
              var outerWallArea = get(project, "calculators").filterBy("__element.type", "wall_outer").reduce(function (prev, curr) {
                return prev + get(curr, "__element.usedDimension") * decimal_formatter.round10(get(curr, "width"), -3);
              }, 0);

              var area = decimal_formatter.round10(get(this, "__room.area"), -3);
              var corrected = 0;

              if (area > 0) {
                corrected = outerWallArea > 0 ? area + outerWallArea : area;
              }

              return corrected;
            })
          });
        }
```

Is my approach a total bullsh*t?

**Comment by herom** [comment]
Additional, if I try to re-`set` the `area`, I see another Error, stating that `desc.set` is not a function, which resolves to the `Ember.set` function when trying to invoke `desc.set` where `desc` is - again - "only" a POJO 

```javascript
{
  isDescriptor: true,
  altKey: '__room.area'
}
```

Here's the Error:
```javascript
Uncaught TypeError: desc.set is not a function
  set @ ember.debug.js:15796
  exports.default.mixin.Mixin.create.set @ ember.debug.js:30426
  setup @ calculator.js:84
```

In this particular case, line 84 of `calculator.js` points to the following code:
```javascript
this.set('area', Ember.computed.alias('__room.area'));
```

**Comment by jmurphyau** [comment]
I see you're calling `this.reopen` - what is `this` in your code? 

Could you create a [JSBin](http://emberjs.jsbin.com/) showing the issue?

**Comment by herom** [comment]
thanks for reaching out @jmurphyau!

`this` is acutally the `Ember.Object` instance itself. I'm working on a jsbin sample, but couldn't extract my code well enough... :(

**Comment by jmurphyau** [comment]
So it's an instance of an Ember.Object - not a class? If that's the case then that's the issue.. `reopen` is designed to reopen a class to add new functions/properties to all instances of that class - it's not designed to be used on an instance. 

If you want to redefine properties on an instance you should look into [`defineProperty`](http://emberjs.com/api/classes/Ember.platform.html#method_defineProperty)

**Comment by herom** [comment]
oh boy.... thanks @jmurphyau I don't know what I was thinking - if I look at the [example](http://emberjs.com/api/classes/Ember.CoreObject.html#method_reopen) given in the docs it's all clear :crying_cat_face: 

thanks again :+1: sometimes it would make sense to have another pair of eyes looking at the code one produces :smile:
