### ISSUE TITLE
MANDATORY_SETTER_FUNCTION assertion causes errors on Component teardown with HTMLBars

### ISSUE THREAD

**Issue by blesh** [emberjs/ember.js#10935]
I'm currently consistantly running into an issue where Ember setting `view.element = null;` apparently on [this line in HTMLBars](https://github.com/emberjs/ember.js/blob/a09f1440ba5cef825133c65ba2718ca1849710d5/packages/ember-views/lib/system/renderer.js#L144)

Causes an assertion error that is unhandled and breaking our app. Here's a screenshot:

![screen shot 2015-04-22 at 11 38 44 am](https://cloud.githubusercontent.com/assets/1540597/7282337/3e4df9d0-e8e4-11e4-8aea-8572018cd5fa.png)

**Comment by blesh** [comment]
This is specifically happening somewhere within [the ember-nf-graph nf-graph-content component](https://github.com/Netflix/ember-nf-graph/blob/e177e8bbc01a21f4518ab0d5ad41f1ab73687b7b/app/components/nf-graph-content.js)

... and it only started after I upgraded to Ember `1.11.1`.

**Comment by rwjblue** [comment]
`element` is not an observable property, observing it would cause this error

**Comment by rwjblue** [comment]
I did a quick scan through the repo, and do not see an instance of you observing `element`.  It could either be in a consuming application, or something like the inspector (having the inspector open can cause all properties on the object that is selected to be observed).

**Comment by blesh** [comment]
The only thing I can think of is that I'm accessing that DOM element via something like D3 in another component.

FWIW: I looked through version history and found that it used to use set in that area: https://github.com/emberjs/ember.js/commit/6af9b030a0da38a7515ed81bad495c64c1bb0251#diff-d8303a7a1692ae012d56a3c6dad4ed2dL139

**Comment by blesh** [comment]
... but access it via D3 wouldn't cause that right? 

It seems like something set up the `element` property on that component to have this default getter that does the assertion. I'm not sure where that is set up or why.

**Comment by rwjblue** [comment]
if you use another views `element` in a template somewhere else (I don't even know if that would work), the template usage would setup an observer on `element` and cause this error.

**Comment by rwjblue** [comment]
So, I suppose it depends how you use the element...

**Comment by blesh** [comment]
That's probably what's happening.  `nf-graph` get's the `nf-graph-content`'s element and sets up some events on it I think.

**Comment by blesh** [comment]
Bingo: https://github.com/Netflix/ember-nf-graph/blob/e177e8bbc01a21f4518ab0d5ad41f1ab73687b7b/addon/utils/nf/graph-mouse-event.js#L45

That's the culprit, I'd wager.  Thanks @rwjblue

**Comment by blesh** [comment]
FWIW: Because Ember is so consistent, this seems like a "wat" in Ember. Everything else in Ember is delightfully uniform or at least gives you clean errors/assertions if you abuse a thing. As an author, I just *assumed* that Ember, being Ember, would allow me to observe, depend on, or get damn near anything
