### ISSUE TITLE
[Feature ember-runtime ] More array macros - computed properties

### ISSUE THREAD

**Issue by gustavocabral** [emberjs/ember.js#10939]
Is there any reason we don't have these computed properties macros available in Ember? 
```
any(arrayProperty, function) : boolean
compact(arrayProperty) : array
contains(arrayProperty, property) : boolean
every(arrayProperty, function) : boolean
find(arrayProperty, function) : object 
findBy(arrayProperty, propertyName, value) : object
getEach(arrayProperty, propertyName) : array
isAny(arrayProperty, propertyName, value) : boolean
isEvery(arrayProperty, propertyName, value) : boolean
reduce(arrayProperty, function, initialValue) : array
reject(arrayProperty, function) : array
rejectBy(arrayProperty, propertyName, value) : array
sortBy(arrayProperty, propertyName) : array
```
(in https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/computed/reduce_computed_macros.js) ?

**Comment by stefanpenner** [comment]
We currently have a freeze on additional API like this. Largely because they can easily be added via community addons without bloating ember. Over time if these add-ons prove pivotal to the core, we can re-consider them.
