### ISSUE TITLE
value  Binding using handlebars and ember data

### ISSUE THREAD

**Issue by thiyagu06** [emberjs/ember.js#10940]
Hi All,

I am using ember data with rest adapters. Currently we have screen with below url.

View : myapp/view update : myapp/view/:id

I will display the list of items with user data with update/delete button. When user click on the udpate button i will show the update form with the values selected. Below the update form i will show the user information list also. When user changes the data in the udpate form, the changes also reflecting in the below list of items which i need to avoid? It should be like unbound helper and also should able to observe the property changes.

Do anyone have suggestion?

**Comment by stefanpenner** [comment]
This is a question based asked on StackOverflow, feel free to cross link so future travelers can find there way to the SO answer
