### ISSUE TITLE
{{{}}} MUCH slower than {{}}

### ISSUE THREAD

**Issue by anlumo** [emberjs/ember.js#10941]
I'm using ember 1.11.2. In one template, I have a simple entry:

`{{{model.note}}}`

The template was rendering very slowly, so I investigated. It takes 14ms to render this way. When I replace the `{{{}}}` with `{{}}` (so the HTML is escaped) without changing anything else, it takes 3ms to render (times were measured with the Ember inspector in Google Chrome).

The HTML in model.note is something like this:
`<p style='color: rgba(22, 103, 132, 1.000000); font: 21px "Helvetica Neue"; text-align: center; '>Note</p>`

Shouldn't the non-escaped string be faster, rather than MUCH slower?

**Comment by stefanpenner** [comment]
Although some investigation is needed. In theory the escaped version should be faster. As with htmlbars in this case isn't manually escapes rather the right DOM api is being used which ultimately leaves the content inert.

That being said, the difference is somewhat suspicious, we should be sure ember (or your app) isn't doing some extra strange

**Comment by anlumo** [comment]
I will try to create a minimal test case.

**Comment by mixonic** [comment]
`{{` sets the value directly as text on a dom node. `{{{` must convert the string to DOM with the correct context (for tr/td tags) then append that DOM. It isn't surprising the latter is slower.

14ms seems mildly suspicious. Please do report back!

**Comment by stefanpenner** [comment]
> 14ms seems mildly suspicious. Please do report back!

ya, I curious if we are doing something funky.

**Comment by anlumo** [comment]
It's 14ms per insert (in an #each block).

I just created a minimal example, but I'm unable to reproduce the issue there. Maybe it's related to the rather complicated css and svg that's rendered there… It could just be a browser thing and HTMLBars is innocent.

**Comment by stefanpenner** [comment]
> It's 14ms per insert (in an #each block).

it's worth noting, these times are really only useful for "Relative magnitude" not absolute times. As the existing of the enabled instrumentation itself is quite slow.

It is totally possible this is just an instrumentation glitch.

If you can share an example, I would love to see it in action.

**Comment by anlumo** [comment]
Unfortunately, this is on closed source software, so I can't show anything of that (yet, at least).

**Comment by stefanpenner** [comment]
> Unfortunately, this is on closed source software, so I can't show anything of that (yet, at least).

can you share the outputed HTML  of this snippet?

**Comment by anlumo** [comment]
Here: https://gist.github.com/anlumo/01f6c3329a1941c82a33

I removed the wrapping, this is just the view itself. It's a mind mapping tool, so I have nodes and connections between them.

**Comment by stefanpenner** [comment]
So in this case, I don't believe this is an issue with ember, rather the cost of inserting massive amounts of SVG at once.

**Comment by anlumo** [comment]
You might be right, I'll look into this more.
