### ISSUE TITLE
[docs] Toggling 'Inherited' in the methods tab gives inconsistent results.

### ISSUE THREAD

**Issue by dandehavilland** [emberjs/ember.js#10942]
I noticed this discrepancy on the [DS.ActiveModelAdapter](http://emberjs.com/api/data/classes/DS.ActiveModelAdapter.html) page.

On arrival, the method list looks like this:
![screen shot 2015-04-23 at 17 18 06](https://cloud.githubusercontent.com/assets/95854/7300489/c8697b1e-e9dc-11e4-90ff-707341ada882.png)

When unchecking 'Inherited':
![screen shot 2015-04-23 at 17 18 13](https://cloud.githubusercontent.com/assets/95854/7300490/c86f05f2-e9dc-11e4-9ce6-6e3ac1fa0df6.png)

And after re-checking 'Inherited' (note the addition of a few methods, including `ajax`, `findQuery` and `urlPrefix`):
![screen shot 2015-04-23 at 17 18 19](https://cloud.githubusercontent.com/assets/95854/7300493/c8d69d2a-e9dc-11e4-9ac7-f43e2ee4069b.png)

**Comment by rwjblue** [comment]
I believe this was fixed by https://github.com/emberjs/website/pull/2267.
