### ISSUE TITLE
Router's rootURL isn't working in 1.12 beta

### ISSUE THREAD

**Issue by tcjr** [emberjs/ember.js#10943]
I'm having a problem with the router in 1.12.0-beta.1.  I'm attempting an upgrade from 1.11.  

None of my routes are being recognized, and I believe it is because of this pr: #10483 .  It looks like the router is no longer accommodating a rootURL.  Our router is defined like this:

```
var Router = Ember.Router.extend({
  rootURL:  '/somepath/'
});
```

If I step through the router code, I see that the rootURL is still attached when it goes into the code trying to find a handler, and (unsurprisingly) can't find any.

**Comment by tcjr** [comment]
I've adapted one of @rwjblue jsbins to demonstrate the UnrecognizedURLError:

http://emberjs.jsbin.com/qivevu/1/edit?html,js,output

**Comment by himynameisjonas** [comment]
I have the same problem, couldn't test glimmer/canary with my app because of this issue

**Comment by matthooks** [comment]
+1 on not being able to test glimmer/canary because of this.

**Comment by rwjblue** [comment]
@tcjr  - That JSBin has roughly the same error in 1.11.3.  http://emberjs.jsbin.com/nubotu/1/edit.

I have no doubt that this is broken, I am just trying to get a minimal reproduction to start debugging.

**Comment by jesenko** [comment]
The error can be reproduced by creating new ember-cli app and just setting `rootURL` to some value - see https://github.com/jesenko/root-url-bug for example.

When using ember 1.11.3, `localhost:4200/test/` works, with ember 1.12.0-beta.3 it fails with
    
    UnrecognizedURLError: /test/

**Comment by himynameisjonas** [comment]
Ok, got the app working by adding `url = url.replace(this.get('rootURL'), '');` to the `handleURL` method in the ember router. I don't feel comfortable enough with the ember source code to do anything more (like a test and PR).

But now, I can at least start working on the deprecation warnings my app have :)

**Comment by tcjr** [comment]
@rwjblue I think my jsbin might not be illustrating the problem correctly.  I cannot get *any* routes in my app to work if a rootURL is set on the router.

**Comment by gdub22** [comment]
This is only broken with 'auto' location. 'history' location is still working correctly.

**Comment by rwjblue** [comment]
@gdub22 - Awesome, thank you for confirming!

**Comment by rwjblue** [comment]
That means this is almost certainly a result of https://github.com/emberjs/ember.js/pull/10483 (which mostly modified auto-location).

**Comment by himynameisjonas** [comment]
This is still an issue in the released 1.12 version, but as @gdub22 said: it works with `location: 'history'`.

**Comment by tcjr** [comment]
Does this mean `location: 'auto'` is no longer supported?

**Comment by mixonic** [comment]
this is definitely a regression

**Comment by davidpett** [comment]
having the issue as well with `location: 'auto'` my app loads at the correct `rootURL`, then quickly replaces with `/`, the app still runs as normal, but obviously at the wrong `rootURL`.

I just switched to `location: 'history'` and it works as expected, so can confirm it has to do with auto-location

**Comment by MichaelVdheeren** [comment]
This needs a quick fix because it breaks a lot of stuff :-(

**Comment by MichaelVdheeren** [comment]
Any idea when 1.12.1 will be out? This bug is in since beta 1

**Comment by rwjblue** [comment]
We could release 1.12.1 anytime (there are a few other fixes already queued up in the release channel), but this bug isn't fixed.  I would prefer to have this fixed before releasing.

**Comment by MichaelVdheeren** [comment]
Could the error be on line 122 here: https://github.com/emberjs/ember.js/pull/10483/files#diff-782353730e67c473ee6609c98230661dR122

Either way this resolves to true or false and not to the location...

**Comment by rwjblue** [comment]
Would would it be true or false? In general doing `&&` like that returns the last truthy value...

```javascript
var foo = { bar: 'stuff'};
var bar = null;

foo && foo.bar // => 'stuff'
bar && bar.bar // => undefined
```

See demo: http://emberjs.jsbin.com/rwjblue/561/edit

**Comment by acorncom** [comment]
@rwjblue Really appreciated :+1: Would love to have been able to help on this one ... :-/

**Comment by jayphelps** [comment]
Feel free to ping me in the future on location class issues, particularly with auto.. It's too bad this was broken for a month..had I heard I would have PR'd immediately to fix. Thanks @rwjblue for fixing!

**Comment by davidpett** [comment]
@rwjblue @jayphelps I just tested ember#beta and this seems to be an issue again, not sure why. ember#release is working fine now

**Comment by rwjblue** [comment]
@davidpett - Can you provide steps to reproduce?

**Comment by davidpett** [comment]
I'll work up a demo repo and link to it. Should have done it first, sorry.

**Comment by rwjblue** [comment]
> Should have done it first, sorry.

No worries really, I just want to make sure we are on the same page as to what we are talking about.  It took me a bit of time to replicate this issue in ember-cli originally because if you use `baseURL` it didn't occur (due to browser default behavior with the `<base>` tag).

**Comment by jayphelps** [comment]
Happy to investigate with reproduction steps. I'll take a look at diff and see if I see anything suspicious.

**Comment by davidpett** [comment]
@rwjblue @jayphelps https://github.com/davidpett/auto-location-base-url

**Comment by jayphelps** [comment]
@davidpett @rwjblue figured it out. The beta has not yet gotten this fix https://github.com/emberjs/ember.js/pull/11303. Basically, the concrete location class isn't getting `rootURL` in beta so it's not be excluded from the route recognizer.

Thanks for the demo app! Would have taken a lot longer to find this without it.

**Comment by davidpett** [comment]
awesome! it's a little harder with ember-cli and some of these issues, can't simply do a jsbin anymore

thanks

**Comment by davidpett** [comment]
@rwjblue any chance of getting that PR merged into the beta branch before 1.13 release tomorrow?

**Comment by acorncom** [comment]
@davidpett Re: ember-cli, no jsbin, there is a work-in-progress on that here: http://twiddle.joostdvrs.com  Might be helpful ...

**Comment by davidpett** [comment]
Yeah @acorncom, it's not there yet, but good start. Faster to run cli and create demo app

**Comment by acorncom** [comment]
@davidpett Sounds good, good to know ;-)

**Comment by rwjblue** [comment]
Great catch, sorry about the extra work tracking down my mistake :(

It is cherry-picked into beta now.

**Comment by davidpett** [comment]
confirm that it works, thanks @jayphelps for finding it and @rwjblue for pushing it!
