### ISSUE TITLE
Input helper action does not behave as action helper

### ISSUE THREAD

**Issue by igorsantos07** [emberjs/ember.js#10959]
It seems a bit non-standard that we are unable to pass in arguments to input actions. The standard `action` helper works as calling a function, that may have arguments. Why are we unable to do it the same way (or similarly) with `input`s? Why should they be less powerful than the traditional helper?

I would like to see some resoning on this, as that's something strange to see and that certainly brings more trouble to someone that's learning to work with Ember.

**Comment by clekstro** [comment]
A link to a JSBin would help everyone understand exactly what you're talking about.
