### ISSUE TITLE
elementId/viewName don't work

### ISSUE THREAD

**Issue by knownasilya** [emberjs/ember.js#10954]
This used to work. Trying it with 1.11.3 currently.

```hbs
{{input type='text' value=title viewName='titleInput'}}

{{! None of these work }}
<label for="{{titleInput.elementId}}">Title</label>
<label for={{titleInput.elementId}}>Title</label>
<label {{bind-attr for=titleInput.elementId}}>Title</label>
```

Even if I change the value of `elementId`, nothing, `{{log}}` logs `undefined`.
http://emberjs.jsbin.com/pofipodena/1/edit

**Comment by clekstro** [comment]
@knownasilya That JSBin doesn't appear to represent the issue. Could you update the link to a working example?

**Comment by sly7-7** [comment]
@knownasilya I think you must prepend titleInput by `view` here. http://emberjs.jsbin.com/kucoburixu/1/edit

**Comment by knownasilya** [comment]
@sly7-7 ah, that's new!

**Comment by sly7-7** [comment]
@knownasilya I don't think it's new (at least since 1.8 or 1.9), when doing 
`{{input type='text' value=title viewName='titleInput'}}`
you define a `titleInput` property on the current view, so in the template you must refer it by using `view.titleInput`.

**Comment by knownasilya** [comment]
Maybe since it's not a component? Since components don't require the `view.` portion.

**Comment by sly7-7** [comment]
Hm, yeah, if the current view is a component, maybe you don't have to put the `view.` prefix because the context is already the component, not the enclosing controller

**Comment by knownasilya** [comment]
@sly7-7 so it sounds like a regression somewhere around 1.8/9 because `view.` was never required before, since I remember `this.get('myViewName')` from the controller, and it working.

**Comment by krisselden** [comment]
If this particular example was supported in the past, it was an accident, if you move the label ahead of the input, you now will invalidate the rendering of the label you did when the input is created.  This example is an anti pattern, you should give the label and input an id from the parent component instead.

**Comment by rwjblue** [comment]
I gave a fairly detailed description (based on a conversation with @krisselden) of using `viewName` for this over in https://github.com/emberjs/ember.js/issues/11156#issuecomment-102896935.

---

@knownasilya - Using `view.fieldName` has always been required.  However, if you are in a component `this` happens to be the same as `view` so it works without the prefix.  Take a look at http://emberjs.jsbin.com/qulere/1/edit?html,js for a demo of that.

I definitely suggest reviewing my reply in #11156 and updating to a more declarative syntax.

**Comment by knownasilya** [comment]
@rwjblue thanks!
