### ISSUE TITLE
Route.refresh() does not work properly with error routes

### ISSUE THREAD

**Issue by mganzarcik** [emberjs/ember.js#10952]
Hello everyone,

we've discovered a weird behavior related to error routes in ember and the Route.refresh() method. 

Since an example is worth a thousand words, I've created a simple JSbin that quite clearly demonstrates the problem:

Output: http://emberjs.jsbin.com/jubed/1/

Sources: http://jsbin.com/jubed/1/edit?html,js

Just open the JSBin output and press the "fire refresh" button. Observe the URL.

Basically, if you call refresh() while on an error route where you ended up because of a rejected model promise, it will for some reason serialize the reason parameter of the promise reject call into the URL and change the route name to a _unused_dummy_error_path_route_[YOUR-LOCATION]. This will also cause you to lose the model of the error route. So for example, if you were displaying a REST error from the response in the error route, you will lose that after the refresh() call.

In our case, we use a refresh() call on the application route level to be able switch languages in our web application dynamically without having to do transitions. It works like a charm everywhere except error routes.

Any ideas on how to solve / circumvent this are more than welcome!

Thanks!

PS: I've replicated this on 1.11.1, but we are internally running 1.8.1. The issue there is the same.

**Comment by rwjblue** [comment]
The path you mentioned is used internally to represent the error/loading routes (because every route that can be transitioned into must have a URL). It was chosen to prevent naming conflicts in end user applications (it is pretty unlikely for `unused_dummy_error_path_route` to be a route in your actual app).  The behavior that you are seeing is what I would expect if you call `this.refresh()` inside the error route.

Ultimately, this isn't a bug so I'm going to clsoe this issue, but I'm happy to reopen if my explaination above doesn't address the issue properly.

**Comment by mganzarcik** [comment]
Hi @rwjblue, thanks for the explanation! 

Since unused_dummy_error_path_route is used internally and basically hidden from the outside world, I would expect it to remain hidden if calling any public method on the route. Calling refresh() in this case is akin to setting Godzilla loose in Tokyo. You lose the model, the URL and get raw JavaScript thrown at you via the location bar. This is inconsistent with how refresh behaves everywhere else. Could it at least be added to the documentation as not supported for error routes?

I realize the use case I've described is probably quite rare (even in our case, I do not expect this to pop up often on production), but I would still like to understand if there is anything we can do on our side to mitigate the problem and make error routes behave nicely with refresh calls. Having known issues like this in a live application makes me sad panda. Any ideas?

Cheers,
Michal

**Comment by rwjblue** [comment]
> Calling refresh() in this case is akin to setting Godzilla loose in Tokyo.

:smiling_imp: 

---

I am not 100% sure where an error route gets its model (generally folks don't put a `model` hook on it), so when calling `refresh` I don't really know what I would expect.

What are you trying to do with `this.refresh()` from the error route?

**Comment by mganzarcik** [comment]
Well, that's a long and really quite a sad story, but the short(ish) version is: we had to implement language switching for a non-trivial web application. 

The way it works is that `ApplicationRoute.model()` gets the json language file via a REST based on some global variable indicating current language. 

If you switch the language, we just call `refresh` on the `ApplicationRoute`, which will force it to refresh the model and get the new language file. Since we call `refresh` on the `ApplicationRoute` level, it will propagate downwards to all child routes. So if you are on an error route when you switch the language, this will also get called on the error route.

So we are not in fact directly calling `refresh` on the error route. We do not even know we are there. We just call `refresh` somewhere higher up and this is where it ends up. The error route itself is not customized in any way, its just the standard "built-in" ember error route (just like in the example).

Obviously switching languages this way is far from optimal, no argument there... as I said, it is quite a sad story. :)

Regarding what we would expect: while typing this all out, I kind of realized that there really is no easy way out of this, is there. It looks like the error route just tries to get the model again, serializing the original reason into the URL to use in `model`, but that kills everything, because the reason is apparently the `then` function of the failed promise (based on what I see in the URL, but I might be wrong). Ideally, I guess the error route should be able to use the original reason to refresh the model without this whole serialization shebang? Or am I completely misunderstanding everything? :)
