### ISSUE TITLE
ember-source 1.10.1 on Rubygems

### ISSUE THREAD

**Issue by nbibler** [emberjs/ember.js#10962]
Following the [Ember 1.10.1, 1.11.2, 1.11.3 security announcement](http://emberjs.com/blog/2015/04/14/security-and-bugfix-releases-ember-1-10-1-1-11-2-1-11-3.html), it seems as though there should be an [`ember-source`](https://rubygems.org/gems/ember-source/versions) v1.10.1 available for download. However, Rubygems does not currently list such a version:

![ember-source](https://cloud.githubusercontent.com/assets/3775/7348556/959dce42-ecc0-11e4-916e-3248740a84f3.jpg)

Should 1.10.1 be available on Rubygems?

**Comment by amedrz** [comment]
Mhmm not sure why it doesn't even appear on the [changelog](https://github.com/emberjs/ember.js/blob/master/CHANGELOG.md) anymore.

**Comment by fivetanley** [comment]
Published. Thanks for raising this!

**Comment by nbibler** [comment]
No problem. Happy to help. :)
