### ISSUE TITLE
#with helper don't work with `0`, `false` value and lost context

### ISSUE THREAD

**Issue by lexich** [emberjs/ember.js#10961]
[Demo](http://emberjs.jsbin.com/ziliro/4/edit?html,js,output)

Also reproduce for beta builds

**Comment by apaganobeleno** [comment]
should ember render 'false'/0 in these cases ? ( just to confirm )

**Comment by apaganobeleno** [comment]
He guys, not sure if this is the right approach, looking for guidance to make it better, at least it seems to solve it :)

**Comment by glagola** [comment]
Same problem with null, undefined. IMHO, **with** should not work as if helper

**Comment by rwjblue** [comment]
I believe that this is intentional behavior.  We use the same semantics as `{{if}}` to determine if the template block should be renderd.

**Comment by rwjblue** [comment]
We decided to go with the same `{{if}}` behavior for falsyiness, and that landed in https://github.com/emberjs/ember.js/issues/11035 (with docs added in https://github.com/emberjs/ember.js/pull/11075).

Thank you for reporting and taking a crack at fixing this issue!

**Comment by lexich** [comment]
very strange decision...
