### ISSUE TITLE
[QUESTION]: Ember.inject.route?

### ISSUE THREAD

**Issue by williamsbdev** [emberjs/ember.js#10967]
I was wondering if Ember.inject.route will ever be a thing? There are times when I do a `needs` in my routes for another route and it would be nice to have the `Ember.inject` syntax.

Thanks!

**Comment by rwjblue** [comment]
> There are times when I do a needs in my routes for another route

If I recall correctly, `needs` only works in controllers, so I am not sure what you mean.  Can you provide an example snippet/JSBin?

**Comment by btecu** [comment]
Correct, `needs` only works on controllers. @williamsbdev want's to be able access the route `a` from route `b`. Since routes are not singletons I'm not sure how helpful that may be. Perhaps for actions?

**Comment by williamsbdev** [comment]
@rwjblue @btecu Thank you for correcting me! We had some code on a work app where we were doing `needs` in the route and we thought it was required for the `modelFor`.
