### ISSUE TITLE
[Bug?] Unexpected behavior with Ember.computed.oneWay, Promises and Select view

### ISSUE THREAD

**Issue by EPadronU** [emberjs/ember.js#10970]
Given the following router, controller and template (the three are simplified):

```js
// Router
Ember.Router.extend({
  setupController: function(controller, model) {
    this._super(controller, model);

    this.store.find('user').then(function(data) {
      controller.set('users', data);
    });
  }
});
```

```js
// Controller
Ember.ObjectController.extend({
  selectedUsers: Ember.computed.oneWay('model.users.content'),
});
```

```hbs
{{! Template }}
{{view "select" content=controller.users selection=selectedUsers
  optionValuePath="content.id" optionLabelPath="content.name"
  multiple="true"
}}
```

I found out that when I change *selectedUsers*, *model.users* also changes. This behavior is not expected and is undesired as well. Could it be particular to my environment? Is there other cases similar to this one? If so: Is this behavior intentional?

I *fixed* my problem with the following code:

```js
// Controller
Ember.ObjectController.extend({
  _setSelectedUsers: function() {
    var self = this;

    this.get('model.users').then(function(data) {
      self.set('selectedUsers', data);
    });
  }.on('didInsertElement'), // Custom mechanism. This doesn't work out of the box I think.
});
```

I would rather prefer not to use this *trick* of course.

**Comment by knownasilya** [comment]
@EPadronU you should be resolving your models in the model hook, since that will wait till everything is resolved.

```js
export default Ember.Route.extend({
  model() {
    return Ember.RSVP.hash({
      model: this.store.find('mymodel', 1),
      users: this.store.find('user')
    });
  },

  setupController(controller, resolved) {
    this._super(controller.resolved.model);
    controller.set('users', resolved.users);
  }
})
```

**Comment by EPadronU** [comment]
Thanks for the advice @knownasilya. I forgot to mention that **model.users** is a model property of *type* *DS.hasMany* with **async** equal to *true*.

The undesired behavior I'm getting involve, as I said, the **model.users** model property, not the **users** controller property. Is there a way to implement the pattern you described with a model property of the nature I mentioned? Am I not seeing something obvious?

P.S. I apology for my English skills. I'm getting better though xD

**Comment by knownasilya** [comment]
@EPadronU just use `{{#if model.users.isFulfilled}} {{model.users.length}} {{/if}}` in your template

**Comment by EPadronU** [comment]
Thank you. As soon as I can I will try that with the select view and I let
you know how turned out.

2015-04-28 12:25 GMT-04:30 Ilya Radchenko <notifications@github.com>:

**Comment by rwjblue** [comment]
Ember.Select is deprecated as of 1.13 and removed from 2.0.0.  Closing...
