### ISSUE TITLE
model hook does not push data to store

### ISSUE THREAD

**Issue by zion03** [emberjs/ember.js#10974]
DEBUG: Ember      : 1.10.1
DEBUG: Ember Data : 1.0.0-beta.16.1 

The code below works fine:
 
     export default Ember.Route.extend({
           model: function(param){
               return this.store.find('user', 100);
            }
     });

But when I changed `return this.store.find('user', 100);` ->  `return this.store.find('user', {'id': 100});` REST request was made, but record was not pushed to data store.

**Comment by herom** [comment]
`{'id', 100}` isn't a valid JavaScript notation (if this wasn't a  typo), instead it should read `{id: 100}`.

**Comment by zion03** [comment]
thanks, it was typo in question, updated.

**Comment by knownasilya** [comment]
This should be in the [ember data repo](https://github.com/emberjs/data).

**Comment by clekstro** [comment]
@zion03 Can you close this issue and move as @knownasilya mentioned?

**Comment by zion03** [comment]
moved to ember data repo.
