### ISSUE TITLE
Ember.TextArea: Cannot set property list of #<HTMLInputElement> which has only a getter 

### ISSUE THREAD

**Issue by srsgores** [emberjs/ember.js#10981]
[JS Bin here](http://emberjs.jsbin.com/lalogo/4/).

``Ember.Textfield`` raises the following error when passed a ``list`` attribute via a custom ``Component``:

> Uncaught TypeError: Cannot set property list of #<HTMLInputElement> which has only a getter

This issue only seems to occur on Chrome dev, and Chrome for Android.

Tested on Chrome ``44.0.2383.0 dev-m`` on Windows 8.1 x64.

**Comment by stefanpenner** [comment]
should be fixed, we now specil case list
