### ISSUE TITLE
`ember-transitioning-in` CSS class applied incorrectly when passing ID instead of the whole model to {{link-to}} helper

### ISSUE THREAD

**Issue by mareksuscak** [emberjs/ember.js#10989]
I wasn't really sure if this is related to existing issue #10195 or not so here I am posting it as a new issue. I want to use `ember-transitioning-in` CSS class to display a spinner next to a link while loading the entity detail route. When I pass model ID to `{{link-to}}` helper `ember-transitioning-in` CSS class is applied incorrectly to all other links but the link it is supposed to be applied to and moreover it is not removed after the transition is finished. 

The reason why I'm passing model ID instead of the whole model is that I need to force the execution of Route's `model` hook because the list endpoint of our API (i use ember-data with REST adapter in) returns only a short version of the record with some attributes missing whereas the detail endpoint returns the same record including all missing attributes.

I was able to reproduce the error in a newly generated application, here's the related commit: mareksuscak/ember-bugs@88726f84601e1dd92505a0b3326ce5dafe00b81e.

**Comment by Jai-Sankar** [comment]
Any updates on this???
