### ISSUE TITLE
Ember.View with observes triggers multiple times

### ISSUE THREAD

**Issue by svox1** [emberjs/ember.js#10985]
Observers is triggered more times if you switch the page:
```javascript
App.IndexView = Ember.View.extend({
  _onModelChanged: function() {
    console.log('CHANGE');
  }.observes('controller.model'),
});
```

I get this Error with Ember 11, 12 and canary.

I create a jsbin for the problem:
http://emberjs.jsbin.com/funuxomaco/4/edit?html,js,console,output

Have a look to the console. CHANGE is triggering more and more you ofter switching the page.

1. Click Info
2. Click Index
- CHANGE is triggered - thats fine 
3. Click Info 
4. Click Index
- CHANGE is triggered two times!

If you switch between the pages is called often more.

Is it not possible to use observers within views?

Note: I have the same problem with ember-date instead of using Ember.A

**Comment by dwickern** [comment]
See #10869

As a workaround you can manually remove the observer in the destroy hook:
http://emberjs.jsbin.com/sapodosotu/1/edit?js,console,output

**Comment by svox1** [comment]
Oh I didnt see that there was already a open issue on that.

Thx for the Info! The hack works for now. 

Because its a duplicate of https://github.com/emberjs/ember.js/issues/10869 I close this issue.
