### ISSUE TITLE
Google Authentication on Ember Discuss no longer works

### ISSUE THREAD

**Issue by dcherman** [emberjs/ember.js#10987]
I apologize if I'm filing this in the wrong spot, but I couldn't find a repository specific to discuss.emberjs.com.

When I try to log in using my Google account as authentication, I'm given the following page that states that the authentication schema you're using is no longer supported:

https://support.google.com/accounts/answer/6206245?p=openid&rd=1

**Comment by fivetanley** [comment]
reached out to @eviltrout and @samsaffron on twitter, hope we can get back to you soon. I think Discourse is hosting the instance for us. https://twitter.com/fivetanley/status/593617807977230337

**Comment by fivetanley** [comment]
This looks like it's up to @tomdale, @wycats, @wifelette, or anyone else with admin access to the Discourse instance: https://twitter.com/samsaffron/status/593618744548528128

**Comment by tomdale** [comment]
@dcherman This was my fault; sorry! Everything should be working now. Let me know if you're still having trouble.
