### ISSUE TITLE
using bootstrap's $().dropdown('toggle') inside an action destroys subsequent action handling

### ISSUE THREAD

**Issue by jcope2013** [emberjs/ember.js#10998]
Having a button with a dropdown toggle and an action on that button, the action will only work one time and then get destroyed moving forward when using $().dropdown('toggle') inside that action, this feels somewhat unexpected as there is cases when you want to use that inside an action but subsequently keep the action binding so when the button is clicked again in the future the action triggers again

relevant example below, clicking the button the first time will increment the count from 0 to 1 but then clicking it again shows the count doesn't get incremented again as the action never gets triggered, commenting out  ``` Ember.$('#dLabel').dropdown('toggle');  ``` will show it to work as expected at least on how i thought it would work where the number keeps getting incremented and the action gets triggered each time you click on the button.

maybe this falls out of the scope of what is considered an ember core issue if so feel free to close the issue

```
<div class="dropdown">
  <button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" {{action 'triggerCount' }}>
    Dropdown trigger
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
    test
  </ul>
</div>
<div class="row">
  <h4>{{count}}</h4>
</div>

App.IndexController = Ember.Controller.extend({
 count: 0,
  
 actions: {
   triggerCount: function(){
       Ember.$('#dLabel').dropdown('toggle'); 
       this.incrementProperty('count');
   }
 }
```

http://emberjs.jsbin.com/qebamozufo/1/edit

**Comment by rwjblue** [comment]
This is not an Ember bug.  Bootstrap's `dropdown` implementation prevents the event from bubbling up to the root element of the Ember app (usually `body`).  In this case, once `Ember.$('#dLabel').dropdown('toggle');` is invoked [bootstrap sets up an event listener](https://github.com/twbs/bootstrap/blob/2aa102bfd40859d15790febed1939e0111a6fb1a/js/dropdown.js#L19) on the element.  Then when an event is triggered [bootstrap prevents the default bubbling from happening](https://github.com/twbs/bootstrap/blob/2aa102bfd40859d15790febed1939e0111a6fb1a/js/dropdown.js#L91).

For Ember to handle an event and dispatch an action, the event must bubble to the root element of the application (which is by default `body`).
