### ISSUE TITLE
Difference for syntax of {{#with}} and {{#each}} between API and blog

### ISSUE THREAD

**Issue by YoranBrondsema** [emberjs/ember.js#10994]
For the `{{#with}}` helper the API documentation says to use it as follows (see http://emberjs.com/api/classes/Ember.Handlebars.helpers.html#method_with):

````
{{#with user.posts as blogPosts}}
  ...
{{/with}}
````

However, the blog post about the release of Ember 1.10 says to use the following syntax (see http://emberjs.com/blog/2015/02/07/ember-1-10-0-released.html#toc_block-params):

````
{{#with user.posts as |blogPosts|}}
  ...
{{/with}}
````

I can imagine both are semantically equivalent (is that so?). However, what is the policy on documenting new syntax in the API documentation? I can understand if this would only happen if one of the syntaxes becomes deprecated, in order to avoid confusion. Is that the case? Otherwise, I'd be happy to update the documentation to reflect the new syntax.

The same is the case for `{{#each}}` helper.

**Comment by arnaldo2792** [comment]
[The Road to Ember 2.0](https://github.com/emberjs/rfcs/pull/15) said that the two special forms for `{{each}}` and `{{with}}` will be deprecated and that you should refactor your templates to use the new block parameters

**Comment by YoranBrondsema** [comment]
@arnaldo2792 OK but my point is more whether or not this should be documented in the API, which is the go-to documentation for Ember users.

**Comment by jayphelps** [comment]
@YoranBrondsema correct, the documentation is outdated as far as "best practice". It's also outdated on the Guides as well, which are found here https://github.com/emberjs/website

**Comment by YoranBrondsema** [comment]
@jayphelps I looked into updating the doc but it seems all the annotations in the source code have recently gone! The `each` helper for 1.11 (https://github.com/emberjs/ember.js/blob/v1.11.1/packages/ember-htmlbars/lib/helpers/each.js) and on master (https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/helpers/each.js). It's due to this commit: https://github.com/emberjs/ember.js/commit/816f252580e0e83d7453d6284a0741e99747fee3#diff-73383bbd890ddeededf700fe26370e0c.

Anyone knows what happened to the documentation annotations? Were they moved somewhere?

**Comment by jayphelps** [comment]
I imagine because it was outdated and since the helper was completely rewritten due to the recent [Glimmer Engine merge](https://github.com/emberjs/ember.js/pull/10501), and it was just not recreated yet. @wycats would have to confirm that, though.

But by all means, re-add them, updated.

**Comment by rwjblue** [comment]
Yes, please add them!! If they are completely gone (and not just moved), we need to bring them back and we would love help with it...

**Comment by stefanpenner** [comment]
docs where fixed in 11146
