### ISSUE TITLE
Store unloadAll on deactivate event, break the application

### ISSUE THREAD

**Issue by vladuemilian** [emberjs/ember.js#10996]
Hello,

I have a route with deactivate event. Inside this event, I have
some calls to this.store.unloadAll('model');

When I try to move on a new route (which fetch some of unloaded
models from the server) it's break with this error:

`Error while processing route: proposal.index Property set failed: object in path "isUpdating" could not be found or was destroyed. Error: Property set failed: object in path "isUpdating" could not be found or was destroyed.`

Stack trace:

`
at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:22563:21)
    at setPath (http://localhost:4200/assets/vendor.js:26389:15)
    at set (http://localhost:4200/assets/vendor.js:26301:14)
    at ember$data$lib$system$store$$Service.extend.didUpdateAll (http://localhost:4200/assets/vendor.js:70729:9)
    at http://localhost:4200/assets/vendor.js:65396:15
    at tryCatch (http://localhost:4200/assets/vendor.js:57486:16)
    at invokeCallback (http://localhost:4200/assets/vendor.js:57498:17)
    at publish (http://localhost:4200/assets/vendor.js:57469:11)
    at http://localhost:4200/assets/vendor.js:37788:7
`

Edit: There is a very strange fix. If I open Ember Inspect and click on Data, and then
try to move between those routes. The problem is gone.

Edit: This bug not happens every time.

**Comment by grapho** [comment]
i dont think this is a bug, but an improper use of `deactivate()` which does not trigger until the router completely leaves a route.  During the validation phase of the new route, the old route is still active, until the new route succeeds or fails.

What you are actually doing is unloading all the records... _after_ the new route model hook fetches from the server.

I might recommend you unloadAll() in the willTransition method.

**Comment by rwjblue** [comment]
This is fairly nebulous bug report, and will be extremely hard (if not impossible) to provide help without an example demonstrating the issue.

**Comment by pixelhandler** [comment]
@vladuemilian did you find a workaround? is this still an issue for you? if so, can you provide a reproducible code example, e.g. an ember-twiddle or a sample git repo?
