### ISSUE TITLE
DEPRECATION: `lookupFactory` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container.

### ISSUE THREAD

**Issue by sunil-shrestha** [emberjs/ember.js#11009]
Just updated my Ember.js app to latest and tried to get Ember FastBoot running. Somehow it managed to run server with "ember s" giving some warning on browser.

However, running "ember fastboot" produces following warnings on console and does not seem to go anywhere from here.

     Built project successfully. Stored in "dist".     
     DEBUG: -------------------------------
     DEBUG: Ember      : 1.13.0-beta.1+canary.1ab4ccb4
     DEBUG: Ember Data : 1.0.0-beta.17+canary.8c81d416c2
     DEBUG: -------------------------------
     Ember FastBoot running at http://0.0.0.0:3000
     DEPRECATION: `lookupFactory` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container. See http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers for more details.
    {anonymous}(ember)$data$lib$initializers$store$$initializeStore (<anonymous>:73828:48)
    {anonymous}(Object.ember)$data$lib$setup$container$$setupContainer [as initialize] (<anonymous>:74138:7)
    {anonymous}(<anonymous>:17751:23)
    {anonymous}(<anonymous>:17774:9)
    visit (<anonymous>:15781:7)
    visit (<anonymous>:15779:9)
    DAG.topsort (<anonymous>:15893:11)
    Namespace.default.extend._runInitializer (<anonymous>:17773:13)
    
    DEPRECATION: `lookup` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container. See http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers for more details.
    {anonymous}(ember)$data$lib$initializers$store$$initializeStore (<anonymous>:73846:28)
    {anonymous}(Object.ember)$data$lib$setup$container$$setupContainer [as initialize] (<anonymous>:74138:7)
    {anonymous}(<anonymous>:17751:23)
    {anonymous}(<anonymous>:17774:9)
    visit (<anonymous>:15781:7)
    visit (<anonymous>:15779:9)
    DAG.topsort (<anonymous>:15893:11)
    Namespace.default.extend._runInitializer (<anonymous>:17773:13)

Not quite sure if this issue belongs here or to ember-data but hopping that someone could guide to the right solution.

**Comment by sandstrom** [comment]
@sunil-shrestha Thanks for reporting!

AFAIK this is already solved on Ember Data master (https://github.com/emberjs/data/issues/2806). And if it isn't, an issue can be opened in that repo.

I think this issue can be closed.

**Comment by sunil-shrestha** [comment]
@sandstrom  Thanks, i will continue to ember-data

**Comment by sandstrom** [comment]
@sunil-shrestha You're welcome.

Please click **Close Issue** below this box.

**Comment by sunil-shrestha** [comment]
The issue is now addressed here. https://github.com/emberjs/data/issues/3051
