### ISSUE TITLE
Browse API docs by version (similar to Guides)

### ISSUE THREAD

**Issue by johnnyshields** [emberjs/ember.js#11005]
Hi, it's really nice how the Ember Guides can now be browsed by version (since 1.10). It would be great if we could get the same thing for the Ember and Ember Data API docs.

![image](https://cloud.githubusercontent.com/assets/27655/7439621/920f9e44-f0bd-11e4-8713-7782c709a216.png)

**Comment by rwjblue** [comment]
Yep, it is in the works.  We have been pretty busy with work on Glimmer and Ember 2.0 lately, but you can take a look at https://github.com/emberjs/api to see what we have so far (mostly working as needed)

**Comment by rwjblue** [comment]
Closing this for now, it is definitely in the works.

**Comment by johnnyshields** [comment]
@rwjblue thanks looking forward to it.
