### ISSUE TITLE
needs documentation

### ISSUE THREAD

**Issue by ksnyde** [emberjs/ember.js#11007]
I was struggling with a very basic `needs` use case where a nested route needs access to a parent and found the documentation missing some really important language nomenclature. I think the following SO post indicates the problem and solution very well:

> [SO description](http://stackoverflow.com/questions/29995005/ember-needs-objectcontroller-seems-inaccessible)

I hope for the future sake of others that this can be incorporated into future documentation. BTW, if there is a more helpful way to get this kind of suggestion into the team I'm very open to it. Still pretty new to this.

**Comment by acorncom** [comment]
@ksnyde I believe docs fixes are generally submitted to the `emberjs/website` repo instead. Thanks for the suggestion!

**Comment by ksnyde** [comment]
@acorncom thanks
