### ISSUE TITLE
Inflection is broken when word contains /

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/ember.js#11014]
I would expect to be able to mark foo as uncountable and see the rule match on folder/subfolder/foo. Instead it doesn't match and the regex rules are applied instead.

**Comment by stefanpenner** [comment]
not part of this repo

**Comment by stefanpenner** [comment]
also fixed in https://github.com/stefanpenner/ember-inflector/pull/78

**Comment by BryanCrotaz** [comment]
We'll see the update to package Json in cli 0,2,4?

**Comment by stefanpenner** [comment]
unclear, it depends on if ember-data upgrades or not.
