### ISSUE TITLE
Beta build page out of date

### ISSUE THREAD

**Issue by seanlinsley** [emberjs/ember.js#11011]
http://emberjs.com/builds/#/beta

![screen shot 2015-05-03 at 12 41 28 pm](https://cloud.githubusercontent.com/assets/688886/7446096/510f6bf6-f192-11e4-9ce3-c4c3c785aa0c.png)

<img width=40% src=https://cloud.githubusercontent.com/assets/688886/7446102/719619e2-f192-11e4-9847-f801baf7eb6b.png>

How is the public website updated? Ideally it'd automatically be updated when a new release is coined, so developers don't have to remember to change it.

**Comment by rwjblue** [comment]
Thanks for reporting! Should be up to date now...
