### ISSUE TITLE
[Glimmer BUG] controller property is not available on views for routes anymore

### ISSUE THREAD

**Issue by dschmidt** [emberjs/ember.js#11013]
Hey,

I just tried out the bower Glimmer build (#10501) and I saw a breaking change in behavior:
We are relying on the controller being available on views for routes in a bunch of places, e.g. the application view. I see it's probably code smell and something one automatically gets rid of once he ports to components completely, but it's still a breaking change for now.

I.e. /e.g.  this.get('controller') in application view init is null (interestingly not undefined) where it used to be the application controller.

BR,
Dominik

**Comment by sandstrom** [comment]
I just noted the same issue. CC @ef4, you're a grand master of routing, any thoughts on this?

**Comment by rwjblue** [comment]
I am working on this ATM.

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/commit/691a5b0eb7f2682091b6fcc3eb2a06dd34e38334.
