### ISSUE TITLE
Amber for indent syntax lovers

### ISSUE THREAD

**Issue by askucher** [emberjs/ember.js#11015]
Hi, I am AngularJs functional developer. I am open to new ideas like Amber and want to learn this framework. But first thing what I met that you don't follow html standard and created your own template standard. 
And it ok if don't like indented syntax like jade. Jade is indented language which could be transformed to simple html. And I can you jade for AngularJs templates easily. AngularJs doesn't dictate what to us.

So the question is: do you have solution for indent syntax lovers or you have strict vision and limits you only with your template engine and consider it as most efficient?

**Comment by topaxi** [comment]
Take a look at http://emblemjs.com/

**Comment by askucher** [comment]
That's it. Thx
