### ISSUE TITLE
[Glimmer] Controller not set on view inside each with `itemController`

### ISSUE THREAD

**Issue by sandstrom** [emberjs/ember.js#11025]
```(handlebars)
{{#each controller itemController='cat' as |cat|}}
  {{view 'cat'}}<!-- does not work -->

  {{view 'cat' controller=cat}}<!-- works! -->
{{/each}}

{{! I guess it's implicit controller-context switching that has stopped working }}
{{! `controller` is an array controller (may or may not matter)}}
```

The fix is easy and I know itemController is deprecated (we've moved away mostly already), but I'm adding this to aid in the bug-hunt.

**Comment by rwjblue** [comment]
Do you mean (no quotes):

```hbs
{{view cat}}
```

**Comment by rwjblue** [comment]
Oh, I see. You are always using the `cat` view, but the `controller` provided to `CatView` is not specified unless you manually wire it up?

**Comment by sandstrom** [comment]
@rwjblue yes, exactly! Obviously not in line with Ember 2.0. I found it in section that's barely been touched since Ember ~1.0.0-rc.2 (ages ago). That's why it's wonky :smile:

**Comment by bradleypriest** [comment]
This disappeared for me in the transition from `{{#each controller}}` to `{{#each controller as cat}}` rather than glimmer specifically

**Comment by rwjblue** [comment]
Reproduction:

* Glimmer: http://emberjs.jsbin.com/rwjblue/446/edit (broken)
* 1.11.3: http://emberjs.jsbin.com/rwjblue/447/edit (working)

**Comment by mitchlloyd** [comment]
For this specific case, the earlier behavior seems to break the semantics of using `as` to prevent context switching and the newer version seems more correct. For instance, in the 1.11.3 version of Ember, using `as` [still overrides the local controller property](http://emberjs.jsbin.com/facegedozi/1/edit?html,js,output). You can see that in the canary version, [using `as` preserves the context of the outer controller property](http://emberjs.jsbin.com/facegedozi/1/edit?html,js,output).

No doubt this is a breaking change in canary, but I'm just wondering if fixing this is really reintroducing a bug that was present in 1.11.3.

**Comment by mitchlloyd** [comment]
That being said, these versions without the `as` show a problem that should be fixed:

* [Glimmer](http://emberjs.jsbin.com/ronafesame/2/edit?html,js,output) (broken)
* [1.11.3](http://emberjs.jsbin.com/diwehorala/2/edit?html,js,output) (working)

And that is probably better described by https://github.com/emberjs/ember.js/issues/11098.

**Comment by rwjblue** [comment]
#11098 was fixed by https://github.com/emberjs/ember.js/pull/11106, and the context switching case has been removed from the codebase as part of 2.0.0 efforts.

Closing...
