### ISSUE TITLE
[Glimmer] Cannot read property 'forEach' in ember-inspector

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#11027]
I'm seeing the following error when Ember Inspector is installed.  If the inspector is not installed the exception is not thrown.

![](http://i.imgur.com/P30AOOC.png)

```
Ember.Object.extend.appendChildren	@	VM296:2893
Ember.Object.extend.viewTree	@	VM296:2814
(anonymous function)	@	VM296:2775
fn	@	ember.debug.js:377
Queue.invoke	@	ember.debug.js:878
Queue.flush	@	ember.debug.js:943
DeferredActionQueues.flush	@	ember.debug.js:748
Backburner.end	@	ember.debug.js:173
Backburner.run	@	ember.debug.js:228
executeTimers	@	ember.debug.js:610
(anonymous function)	@	ember.debug.js:599

```

**Comment by simi** [comment]
probably related to https://github.com/emberjs/ember.js/pull/10501#issuecomment-99147454

**Comment by rwjblue** [comment]
Yes, the ember-inspector needs some updates to work well with Glimmer.  I am sure that @teddyzeenny is aware, but would you mind making a tracking issue in the inspector repo and cross-link?   We'll keep both open to make sure this is working well by the time we get to beta branch point...

**Comment by chadhietala** [comment]
Closing in favor of https://github.com/emberjs/ember-inspector/issues/351

**Comment by rwjblue** [comment]
I would like to keep this open, as most folks will look here first.  We can close once Teddy has had a chance to look at it...
