### ISSUE TITLE
Inject into a helper

### ISSUE THREAD

**Issue by atomkirk** [emberjs/ember.js#11021]
I have this:

```
export function initialize(container, application) {
    application.inject('component', 'store', 'store:main');
    application.inject('component', 'application', 'application:main');
    application.inject('component', 'applicationController', 'controller:application');
    application.inject('helper', 'applicationController', 'controller:application');
    application.inject('model:device', 'application', 'application:main');
    application.inject('model:room', 'application', 'application:main');
    application.inject('model:setting', 'application', 'application:main');
    application.inject('route:application', 'application', 'application:main');
    application.inject('transform', 'application', 'application:main');
}

export default {
  name: 'injections',
  initialize: initialize
};
```

notice:

```
application.inject('helper', 'applicationController', 'controller:application');
```

but in the helper, `this.get('applicationController')` is not defined:

```
import Ember from 'ember';
import environment from '../utils/environment';

export function staticImg(path, options) {
    if (path) {
        var staticRoot = this.get('applicationController').get('model.staticRoot');
        return new Ember.Handlebars.SafeString('<img src="' + environment.staticHost() + staticRoot + path + '" class="' + ( options.hash.classNames || "" ) + '">');
    }
    else {
        return "";
    }
}

export default Ember.Handlebars.makeBoundHelper(staticImg);
```

In the docs it says you can inject onto helpers, and this exact setup working on other framework classes but not here…

**Comment by rwjblue** [comment]
You cannot inject into helpers. I believe that the docs have been updated, but please point me to where you noticed that it mentioned this was possible so we can fix the doc...

**Comment by atomkirk** [comment]
Ah crap, you did update them for 1.11. Thanks. Ok, then what is the direction we should go if we need access to container stuff form within helpers and especially plan Ember.Object instances (which have no container property)?

**Comment by atomkirk** [comment]
I realize issues i the wrong place to ask for advice or help, but I should be considered a huge evangelist for this framework and when I ask questions, it's because I have looked and looked through the docs, google searched, forum searched, and I simply cannot find how to accomplish a fairly basic task. So in asking my question above, I'm looking for an answer so that I can either contribute to the docs myself, or create an issue to help clarify the docs.

While I may not contribute much to the code base, I believe I can make a huge contribution to the popularity of this project by helping to keep the (already fantastic) docs up-to-date and comprehensive, so if you wouldn't mind, as a core designer of the framework, please shed some light on how the problem  I mention above should be approached in ember.js and I will try to contribute some content so it's not asked again in the future.

**Comment by atomkirk** [comment]
Or, let me know the appropriate place to ask the designers, who can give authoritative answers, questions that no one else in the community seems to know the answer to.

**Comment by mmun** [comment]
@atomkirk Instead of trying to inject something into a helper, you should inject into a controller/component and pass the injected object into the helper.

**Comment by devlo** [comment]
What if i am using helper inside component and i need to access user data too that i normally inject to routes and controllers ? It's not accessible inside that helper. 
Passing it to every component seems not efficient, i would need to make for example user.name for every component, while it's the same for all of them. So if i have 50 components i would need to pass the same value to 50 components to access it from helper inside component... 
Any way to resolve this ?

**Comment by mixonic** [comment]
This has been addressed in Ember.js 1.13 with closure actions. Please see:

* http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_closure-actions
* https://github.com/emberjs/rfcs/blob/master/text/0050-improved-actions.md

**Comment by rwjblue** [comment]
For anyone coming across this later, helpers in Ember 2.x are now "real" objects and can have access to services (via `Ember.inject.service` or initializer based injections).

Example:

```javascript
export default Ember.Helper.extend({
  i18n: Ember.inject.service('i18n'),

  compute(params, hash) {
    let i18n = this.get('i18n');
    // stuff here
  }
});
```
