### ISSUE TITLE
[Glimmer] - Data binding issue when using Ember.computed.alias

### ISSUE THREAD

**Issue by raytiley** [emberjs/ember.js#11023]
Here is a jsbin reproducing an issue in my app. The `action-checkbox` fires an action when clicked and the `x-item` component  then adds / removes it from an array to manage selection. 

My current implementation uses an alias inside the `action-checkbox` to alias `isChecked` to `checked` which is an attribute binding. After repeated checks the `selected` CP on the `x-item` component stops being calculated and is out of sync. You can see from the console logs that the `toggle` action on the `x-item` component is continuing to fire.

Broken: http://emberjs.jsbin.com/cisitoluho/1/edit?html,js,output

Working w/ out alias:http://emberjs.jsbin.com/docosi/1/edit?html,js,output

Worked with @rwjblue a bit on this and he asked me to open the issue.

**Comment by mixonic** [comment]
@raytiley this is different than https://github.com/emberjs/ember.js/issues/10992? Seems similar.

**Comment by rwjblue** [comment]
Thanks for opening this issue.  Will be working on this after #11013.

**Comment by raytiley** [comment]
@mixonic not sure... I didn't fully grok that other jsbin when I played around with it. In my case though its definitely a regression in glimmer... Works fine in canary.

**Comment by rwjblue** [comment]
I did a bit more work on this, and have a further reduction JSBin: http://emberjs.jsbin.com/rwjblue/461/edit?html,js,output.

**Comment by rwjblue** [comment]
Trying to work on a test that demonstrates the bug.

**Comment by rwjblue** [comment]
Even simpler repro: http://emberjs.jsbin.com/rwjblue/463/edit?html,js

---

This bug only exists when:

* using a `mut` binding backed by a CP
* the bound attribute exists in the component
* the upstream value is changed a second time :trollface:

**Comment by rwjblue** [comment]
Test added in https://github.com/emberjs/ember.js/compare/computed-attribute-updates.
