### ISSUE TITLE
Documention Clarification

### ISSUE THREAD

**Issue by atomkirk** [emberjs/ember.js#11020]
Here: 

http://guides.emberjs.com/v1.11.0/understanding-ember/dependency-injection-and-service-lookup/

it says "Ember's container should be viewed as an implementation detail, and is not part of the supported public API." But I see `this.container.lookup` being used and suggested as a solution all over these issues and forums. If container is being provided as a property on main framework objects, isn't that contradictory? 

Also, if I'm assuming using the container to lookup things is ok as long as it's accessed this way, I can't find any public API docs about accessing the container property on a controller, route, etc.

So, is `this.container.lookup(…)` discouraged or ok? And if so, why? And if so, where is the docs for the container property on framework classes?

**Comment by stefanpenner** [comment]
> If container is being provided as a property on main framework objects, isn't that contradictory?

It exists as a escape valve for use-cases not initially understood, but assumed to exist. Hence being discouraged. There is some work by @dgeb that should further remove more of the discovered use-cases.

**Comment by atomkirk** [comment]
Ok, that makes more sense. Is there any approved way to inject into general Ember.Object instances?

**Comment by rwjblue** [comment]
Please take a look at https://github.com/emberjs/rfcs/pull/46, and chime in with your thoughts.

I'm going to close this, as I believe that RFC directly addresses the concern.
