### ISSUE TITLE
Glimmer, performance regression when navigating/interacting with nested routes

### ISSUE THREAD

**Issue by Adriaaaaan** [emberjs/ember.js#11039]
Although Glimmer is MUCH faster at raw rendering, it seem that interacting with nested routes causes the whole view to be rerendered resulting in significantly reduced performance.

Glimmer
http://jsfiddle.net/6Evrq/518/

1.11.3
http://jsfiddle.net/6Evrq/520/

**Comment by rlivsey** [comment]
What browser are you seeing this in? 

I just took a quick look in Chrome and don't see the list re-rendering when navigating through items in either version.

**Comment by Adriaaaaan** [comment]
chrome, the glimmer version is slower for me

**Comment by Adriaaaaan** [comment]
hang on i seem to have made a messup of the js fiddles

**Comment by Adriaaaaan** [comment]
okay forget it, I'll have to try another way to replicate it, my app is much slower (~500ms) at interacting with anything in the nested route but this isnt showing it clearly
