### ISSUE TITLE
[Glimmer] classNameBindings don't update

### ISSUE THREAD

**Issue by dschmidt** [emberjs/ember.js#11034]
With Glimmer classNameBindings don't always work for me, this jsbin shows the issue:

http://emberjs.jsbin.com/mulomunave/1/

If you change `foobar` to `true` in the controller directly, you see the background changes to red, if it's set by the action after clicking click me, it doesn't.

**Comment by dschmidt** [comment]
Changing visible to `attrs.visible.value` makes it work, so it seems this is the same bug as #11037, just with a worse description :-)

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/11049.  Thanks for reporting!
