### ISSUE TITLE
ember.MutableArray.html#property_lastObject not always returning correct object

### ISSUE THREAD

**Issue by mylen** [emberjs/ember.js#11038]
> Ember      : 1.11.3
> Ember Data : 1.0.0-beta.16
> jQuery     : 1.11.2

When calling lastObject on an array, I get always the odd entry and not the even ones...
Here is an extract of my logs in order to illustrate my use case:

> commands :[{"label":"1S"}]
> commands.get("lastObject").options.label
> "1S"

> commands :[{"label":"1S"},{"label":"2P"}]
> commands.get("lastObject").options.label
> "1S"

> commands :[{"label":"1S"},{"label":"2P"},{"label":"3S"}]
> commands.get("lastObject").options.label
> "3S"

When using :

> commands.objectAt(commands.get('length') - 1)

I have the expected behavior

**Comment by aldhsu** [comment]
+1
I had the same problem while using an `observer` on `EmberProxy.[ ]`.
Will try and build a fiddle to reproduce.

**Comment by rwjblue** [comment]
Can you provide a JSBin/ember-twiddle for this?  I'm not certain that I understand...

**Comment by pixelhandler** [comment]
@aldhsu did you ever build a twiddle or an ember-twiddle to reproduce this issue? @mylen did you find a workaround?

**Comment by aldhsu** [comment]
@pixelhandler I ran into this when we were on 1.12. Haven't run into it again. What the conditions were have slipped my mind so I am of little help.

**Comment by pixelhandler** [comment]
@mylen I'll close this one out for now, if the issue pops up again in a newer release please reopen, thanks!
