### ISSUE TITLE
[Glimmer] link-to breaks mutable cell unwrap chaining

### ISSUE THREAD

**Issue by ef4** [emberjs/ember.js#11036]
1. Have a mutable attr that contains a pojo.
2. You can bind its properties into your template like this and it works: `{{attrs.model.name}}`.
3. Now wrap that in a `{{#link-to}}`. The binding breaks. To make it work, you need to switch it to `{{attrs.model.value.name}}`.

JSBin demonstrating the problem: http://jsbin.com/yubepopoja/1/edit?html,js,output

**Comment by mmun** [comment]
Looks like its happening with generic components as well.

**Comment by wycats** [comment]
A test would be super-helpful here. I suspect the bug is very simple (just a missing case somewhere where a mutable reference is accepted but not a mutable cell or vice versa).

**Comment by wycats** [comment]
The most troubling thing to me about this example is that the yielded block should be sharing streams with the outer block. The fact that the behavior is different implies to me that something else is going on here, and even if we can patch this case, that's a big problem for performance.

I'll investigate it this evening.

**Comment by wycats** [comment]
Upon further investigation, it appears that `scope.attrs` is undefined in `my-component`, which is most definitely wrong. It's falling back to `view.attrs`, while it looks like a similar object, is actually a snapshot rather than a hash of streams. More investigation forthcoming.

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/commit/60d942f0da90c1a17f6c1a937166f2a7000839f7.
