### ISSUE TITLE
ElementMorph does not have clear/destroy methods.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#11032]
This is essentially the same as https://github.com/emberjs/ember.js/issues/11030, but with `ElementMorph`.

Sample template:

```hbs
    {{input type="checkbox" checked=checked}}
    
    {{#if checked}}
      <span {{action 'trueClicked'}}>Click Me</span>
    {{else}}
      <span {{action 'falseClicked'}}>Click Me</span>
    {{/if}}
```

Demo: http://emberjs.jsbin.com/rwjblue/434/edit?html,js,output

**Comment by rwjblue** [comment]
Addressed upstream via https://github.com/tildeio/htmlbars/pull/337.

**Comment by dschmidt** [comment]
Do these fix https://github.com/emberjs/ember.js/pull/10501#issuecomment-98718023?

**Comment by rwjblue** [comment]
@dschmidt - One form of it yes, and https://github.com/emberjs/ember.js/issues/11030 fixed another form.  I think this should have resolved all of them, but definitely looking out for more issues reported....
