### ISSUE TITLE
1.11.3 update - Uncaught Error: Assertion Failed: calling set on destroyed object

### ISSUE THREAD

**Issue by ChrisHonniball** [emberjs/ember.js#11047]
I'm getting this error on v1.11.3 and it's not happening in v1.10.1:

![screen shot 2015-05-06 at 2 54 31 pm](https://cloud.githubusercontent.com/assets/3345374/7501129/fd3db5c6-f3ff-11e4-9de6-208a0961a0b3.png)

Any help would be greatly appreciated as it's preventing me from updating to v.1.11.3.

**Comment by ChrisHonniball** [comment]
Same result with v1.12.0-beat.3

**Comment by ChrisHonniball** [comment]
Seem to be getting a similar error on an alternate route:

![screen shot 2015-05-06 at 3 21 16 pm](https://cloud.githubusercontent.com/assets/3345374/7501647/9c4bf9e0-f403-11e4-994a-5512aebc6f6a.png)

Again, only in versions after 1.10.1.

**Comment by rwjblue** [comment]
Can you provide a reproduction/demo?  It will be very hard to track down the solution for your scenario without one....

**Comment by ChrisHonniball** [comment]
Closest I can find is this [StackOverflow Question](http://stackoverflow.com/a/23813373/3871193) which links to this [JSBin](http://jsbin.com/jumoy/2/edit?html,js,output).

> ... To see the effect uncomment the second ContainerView and comment out the first, you will notice in the console logs that the second time you go to the twoRoute, it has marked that initial property as state: destroying for the view.

The problem with this example is that I do not have anything being defined in this manner in my application.

Tests reveal that this only happens when you visit the route a *second* time after leaving this specific route.

**Comment by ChrisHonniball** [comment]
Ok, found something. If I comment out the *async* record relationships I do not get this error.

**Comment by ChrisHonniball** [comment]
After an entire day of diagnosis, I have been able to fix this on one of my routes by removing this:

```javascript
// route code
setupController: function(controller, model){
    this._super(controller, model);
    
    controller.setProperties({
        "model": model,
        "searchLimitReached": false,
        "leadResults": []
    });
},
/// other route code
```

**Comment by ChrisHonniball** [comment]
Some additional details using this code:

```javascript
  setupController: function(controller, model){
    this._super(controller, model);
    
    /* */
    console.log(
      "%c%s#setupController controller: %s, %O",
      "color: purple", // http://www.w3schools.com/html/html_colornames.asp
      this.toString(),
      controller.toString(),
      controller.getProperties('isDestroyed', 'isDestroying')
    );
    //*/
    
    /*
     controller.setProperties({
      "searchLimitReached": false,
      "leadResults": []
    });
    */
    
    /* */
    console.log(
      "%c%s#setupController Complete...",
      "color: purple", // http://www.w3schools.com/html/html_colornames.asp
      this.toString()
    );
    //*/
  },
```

I get no error as follows:

![screen shot 2015-05-07 at 3 20 43 pm](https://cloud.githubusercontent.com/assets/3345374/7524012/3648a272-f4cd-11e4-832b-d9b73bfbc417.png)

But if I uncomment the `controller.setProperties()`:

![screen shot 2015-05-07 at 3 19 53 pm](https://cloud.githubusercontent.com/assets/3345374/7524018/427ab29c-f4cd-11e4-92d5-49cead8b0d5f.png)

The expanded error:

![screen shot 2015-05-07 at 3 27 13 pm](https://cloud.githubusercontent.com/assets/3345374/7524070/98da4bc0-f4cd-11e4-8f3f-c0b538fe9d2e.png)

Hoping this helps diagnose.

**Comment by rwjblue** [comment]
My guess: your test is not waiting for the model hook promise to resolve, which means that the test has already been torn down (and therefore `controller` is destroyed) when the `setProperties` is called.

**Comment by ChrisHonniball** [comment]
This is directly related to the [above code](#issuecomment-99989202) and the `controller.setProperties()`. I can reproduce this error on *any* route in my application that has `controller.setProperties()` in the `setupController` hook. Then I can clear it up by removing the `controller.setProperties()`.

I attempted to move the `controller.setProperties()` inside a `Ember.run.later()` to see if I wait to set the variables it would avoid this error but once the `controller.setProperties()` runs I get the same error (not surprising but I'm attempting anything to get this to work).

> the test has already been torn down (and therefore controller is destroyed) when the setProperties is called

When returning to the route wouldn't the controller be re-setup? I'm a little confused why this would work fine in v1.10.1 and not in v1.11.3 since the `setupController` hook is where you are *supposed to* do this type of variable setting on your controller.

I've tried to create a JSBin to duplicate this issue but am unable to duplicate it. [JSBin here](http://jsbin.com/qiheqa/4/edit?html,js,output). The differences between the JSBin and my application are that I'm using Ember CLI (v0.2.3) to build, using the REST adapter rather than the Fixtures adapter, and my routes are nested a few steps deeper.

**Comment by ChrisHonniball** [comment]
Interestingly, once this error happens I can still navigate my application but the entire Ember Data layer is disabled. Assuming this is because the Ember Data script errored out.

**Comment by ChrisHonniball** [comment]
I was able to gain some insight to this error by modifying [this line](https://github.com/emberjs/ember.js/blob/8962e36f16a79e336371428fd265db3a2dbbdf8e/packages/ember-metal/lib/property_set.js#L68) to:

```javascript
    if(obj.isDestroyed){
      console.log(obj);
    }
    Ember['default'].assert("calling set `" + keyName + "` on destroyed object", !obj.isDestroyed);
```

[This JSBin](http://jsbin.com/qiheqa/8/edit) now produces a similar error but it is at the exact same moment that my `set` error is coming up. I'm assuming it's related.

To duplicate: Navigate to route one, then route two, then back to route one to duplicate.

**Comment by ChrisHonniball** [comment]
This is a widespread problem all over my application. Any help would be greatly appreciated. It's holding further development back. Thanks.

**Comment by ChrisHonniball** [comment]
Also applies to the new 1.12.0.

**Comment by ChrisHonniball** [comment]
[Updated JSBin](http://jsbin.com/qiheqa/20/)

**Comment by ChrisHonniball** [comment]
I have also found that if I wrap my `{{each}}` in an `{{if}}` then it doesn't happen.

**Comment by ChrisHonniball** [comment]
Above is inconsistent and works *sometimes*.

It can be seen with [This Bin](http://jsbin.com/qiheqa/21/edit?html,js,output).

However if you comment out the todos from the user model then all goes fine.

**Comment by ChrisHonniball** [comment]
More updates... I have found that it only happens on routes that have an Ember form element(e.g, `{{input}}`) on them. It seems they don't get torn down correctly. If I wrap the entire template in `{{#if model}}{{/if}}` I do not get the error.

**Comment by Amiedeep** [comment]
if you are using Ember.Instrumentation namespace for publishing your events and Ember.subscribe to listen to them in your code, when you publish events then it stack all the subscribers and call them even when they are destroyed. so basically, when for example your route is destroyed which is running subscribe statements it will fail and give above error. 

Here is a solution to this problem. Use Ember.Instrumentation.reset() to remove previous subscribers which are destroyed. This solution helped me in acceptance tests where app was destroyed after tests are finished. I wrote Ember.Instrumentation.reset() in startApp function of module-for-acceptance.js and it worked. Hope that helps.

**Comment by you-yas55** [comment]
I'm having the same problem, on a component that's initialized within a tabs component, didInsirtElement and similar hooks get called twice for some reason, first time is correct and second time with an element gets destroyed. 

`Assertion Failed: calling set on destroyed object`
