### ISSUE TITLE
[Glimmer] - Data binding issue when using {{component}}

### ISSUE THREAD

**Issue by raytiley** [emberjs/ember.js#11044]
Reproduction: http://jsbin.com/zafona/2/edit
Working w/out component: http://jsbin.com/rejuvu/1/edit?html,js,output

What is interesting here is the data displayed by the template is kept up to date, but data access from within the action of the component is not in sync.

**Comment by rwjblue** [comment]
Providing a `key` to the `{{each}}` invocation fixes the issue, but that is just a work around.  The component should have gotten the updated data for sure.

Demo with work around: http://jsbin.com/qugefo/1/edit?html,js

**Comment by rwjblue** [comment]
Added test in https://github.com/emberjs/ember.js/compare/component-helper-invalidation-in-each.
