### ISSUE TITLE
[Glimmer] `each` helper with `itemController` generates extra div tag

### ISSUE THREAD

**Issue by hibariya** [emberjs/ember.js#11056]
I know that `itemController` is deprecated. But current canary can break style for existing apps.

* canary: http://emberjs.jsbin.com/keyuxirejo/1/edit
* v1.11.3: http://emberjs.jsbin.com/picuxepepu/1/edit

We can workaround this by passing `tagName=''`. And I think that LegacyEachView's tagName can be empty-string by default, is it correct?

**Comment by rwjblue** [comment]
@hibariya - Sounds like a good solution, can you submit a pull request adding `tagName` along with a test?

**Comment by hibariya** [comment]
@rwjblue I'll try it :bulb:
