### ISSUE TITLE
[Glimmer] Mutable bindings flowing backward

### ISSUE THREAD

**Issue by ef4** [emberjs/ember.js#11054]
In this example:

http://jsbin.com/tanixu/2/edit?html,js,output

if you navigate among the three routes, the `{{next-page}}` component updates properly on the first two pages you visit, but after that remains stuck. If you change it from:

```handlebars
{{next-page nextItem=nextTopic}}
```

to:

```handlebars
{{next-page nextItem=(readonly nextTopic)}}
```

the problem goes away. This makes me guess that the two-way binding is feeding backward from the next-page component to the application controller, causing the value of `nextTopic` to be stuck.

**Comment by rwjblue** [comment]
@ef4 - The provided JSBin seems to be working properly, can you confirm and close if it is resolved?

**Comment by ef4** [comment]
Yes, it looks like recent changes already fixed this. I will bisect just to
understand and then close.

**Comment by rwjblue** [comment]
I am guessing that https://github.com/emberjs/ember.js/commit/60d942f0da90c1a17f6c1a937166f2a7000839f7 is the commit that fixes, but I would also love for confirmation.

**Comment by ef4** [comment]
Your guess was correct, 60d942f0da90c1a17f6c1a937166f2a7000839f7 fixed this issue.

**Comment by rwjblue** [comment]
Awesome, glad it is resolved.  On to the next things...
