### ISSUE TITLE
[Glimmer] ContainerView issue?

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#11062]
I'm not sure how best to describe this issue I'm experiencing, so I made two fiddles to demonstrate it:

1.12.0-beta.3: http://jsfiddle.net/amk221/dqf7qvzo/
1.13.0-beta.1: http://jsfiddle.net/amk221/1ecd458q/

I think what is happening is: The new ContainerView hbs template loops through its views using the `each` helper, re-rending them. This is causing the CSS animations to fire _each time_, when previously (pre-Glimmer) it did not.

**Comment by krisselden** [comment]
@amk221 you can solve by giving each a key prop that means the row should be stable with that key. Bonus this works if the underlying array is a new array but where the elements have been rendered before.

@wycats a default item key of index would at least match prior behavior for when the underlying array was stable and you pushed onto it.

**Comment by amk221** [comment]
@krisselden Is [this](https://github.com/emberjs/ember.js/blob/3aea201274e8d539c7c509896983960ba65d2a7e/packages/ember-htmlbars/lib/templates/container-view.hbs) what you mean. It already has a key.

**Comment by krisselden** [comment]
@amk221 sorry, I missed that, it does loop through each time but it shouldn't be recreating dom if the key is stable.

**Comment by amk221** [comment]
@rwjblue Might this have been fixed by the recent work on `each key` ? #11337

**Comment by rwjblue** [comment]
@amk221 - It is certainly possible, would you mind confirming with an updated JSFiddle/JSBin?

**Comment by amk221** [comment]
I just swapped the URLs for canary in the above fiddles, yes - issue has gone

**Comment by rwjblue** [comment]
Awesome! Thank you!
