### ISSUE TITLE
installation guide improvement

### ISSUE THREAD

**Issue by pedrojvrccosta** [emberjs/ember.js#11064]
Installation instructions needing update.

I just finished installing Ember following the instructions provided in the site and I faced an issue related to the version of nodejs to be installed. There is said to have the 0.10.xx and the steps to get it are there. Then is the installation of ember-cli and other tools. And here, the nodejs version required is 0.12.xx. Not knowing what was happening, I eventually had it ok, but I had to reinstall everything.

Now, let's see if I get what I hope from Ember.

BR

**Comment by rwjblue** [comment]
Great point! Would you mind re-opening this issue over at https://github.com/emberjs/guides (which is where the guides are maintained) with a link to the section that you found to be in error?

**Comment by pedrojvrccosta** [comment]
done
