### ISSUE TITLE
Glimmer: Checkbox "component" missing?

### ISSUE THREAD

**Issue by knownasilya** [emberjs/ember.js#11067]
Get this:

> HTMLBars error: Could not find component named "-checkbox" (no component or template with that name was found)

With the following canary build: 1.13.0-beta.1+canary.aace1051

Beta and latest work just fine.

**Comment by rwjblue** [comment]
Working demo using `{{input type="checkbox"}}`: http://emberjs.jsbin.com/rwjblue/454/edit

Can you provide a JSBin that demonstrates the error above?

If this is in tests, you need ember-qunit@0.3.2 (released yesterday) or above to use with Glimmer.

**Comment by knownasilya** [comment]
Yes in tests. Checking now.

**Comment by knownasilya** [comment]
All good now!
