### ISSUE TITLE
<input> value binding does't update when changed by password manager

### ISSUE THREAD

**Issue by BrianTMaurer** [emberjs/ember.js#11078]
The login I have looks like this:

```html
<form {{action "login" on="submit"}}>
  {{input id='email' type='email' name='email' value=email}}
  {{input id='password' type='password' name='password' value=password}}
  <input type="submit" value="Log In"/>
</form>
```

When the form is auto-filled and submitted by my password manager (Mitro), `this.get('email')` and `this.get('password')` are undefined in the controller and login fails. However, `Ember.$('#email').val()` and `Ember.$('#password').val()` are the correct email and password from the password manager.

Manually typing the email and password works as expected.

At the moment I have a workaround that sets the values to be the text in the input (retrived with jQuery) on submit.

**Comment by mixonic** [comment]
@BrianTMaurer the password manager is not triggering a change event on the inputs. I don't think there is a way Ember can know to update the bound values without an event of some kind being triggered.

**Comment by sandstrom** [comment]
@BrianTMaurer Maybe you can open an issue on their repo (https://github.com/mitro-co/mitro/).

As mixonic says, without the 'change' (or 'keyup', etc) event Ember won't know. You could write custom code that does manual work in the login action. Primarily a deficiency in the password manager.

**Comment by stefanpenner** [comment]
Does the `input` event fire?

**Comment by BrianTMaurer** [comment]
@mixonic Exactly, I am not overly familiar with ember's internals but I imagine other password managers work in a similar fashion – direct input value manipulation followed by form submission. No keyboard events would be fired.

@sandstrom Im not sure this is a deficiency in Mitro. The password manager is doing exactly what is expected, setting the username and password input values, then submitting the form. Triggering keyboard events or ember specific events would be an odd work-around for Mitro (or any automated form filler).

@stefanpenner The form submit event fires.

**Possible Solution** – on any form submit event, regardless of how it is triggered, ember could update bound values in the form. This would cover Mitro, as well as any other automated form filling extension.

That being said, I don't know ember's internals and am not the person to decide what to do. I just wanted to point out something I noticed during development in the chance that it would be helpful to someone working on ember.

**Comment by sandstrom** [comment]
@BrianTMaurer I haven't looked through the Mitro source, but I think if they did something like this it would work better:

```
el.value = 'newVal'; el.trigger('change');
var evt = document.createEvent('HTMLEvents');
evt.initEvent('change', true, true);
el.dispatchEvent(evt);
```

**Comment by mixonic** [comment]
> Possible Solution – on any form submit event, regardless of how it is triggered, ember could update bound values in the form. This would cover Mitro, as well as any other automated form filling extension.

I understand that this might address your immediate issue, but it would also be super unexpected and difficult to explain to new developers. I don't think we are comfortable making that change for this very narrow use-case.

**Comment by brettburley** [comment]
It looks like this is a result of how Micro's sending change events to inputs:
https://github.com/mitro-co/mitro/blob/ae43f8346de6c3e9818988a08cea448393e4af52/browser-ext/login/common/loginpage.js#L575

They're setting the input's value property directly, then sending a series of keydown, keypress, and keyup events manually, which doesn't trigger the oninput event.

**Comment by stefanpenner** [comment]
> @stefanpenner The form submit event fires.

but does the input event also fire?

**Comment by stefanpenner** [comment]
seems like a bug in the password lib, (1password appears to work correctly)
