### ISSUE TITLE
[Glimmer] willDestroyElement is sometimes called again when the outlet view destroys the toplevel view

### ISSUE THREAD

**Issue by krisselden** [emberjs/ember.js#11077]
I noticed this failing a unit test during App.reset() so this reproduction is based on that.
http://emberjs.jsbin.com/zuzamilapa/2/edit

There are other cases of it during a route transition that I haven't made a reduce reproduction yet. Just wanted to track this.

**Comment by rwjblue** [comment]
@krisselden - Any progress/updates on tracking this down?

**Comment by rwjblue** [comment]
Added test for ensuring `childViews` is maintained when render nodes are removed: https://github.com/emberjs/ember.js/compare/child-views-maintained.

**Comment by krisselden** [comment]
http://output.jsbin.com/didaqevibi/1

**Comment by krisselden** [comment]
the above illustrates the issue with childViews and willDestroyElement being called twice.

**Comment by runspired** [comment]
Any progress?

Encountered this this evening (via ember-wormhole), it quickly spirals into deathly recursion :'(
