### ISSUE TITLE
Retire commit tagging guidance in CONTRIBUTING.md?

### ISSUE THREAD

**Issue by eliotsykes** [emberjs/ember.js#11076]
[`CONTRIBUTING.md`](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md) recommends using commit tag prefixes like `[DOC]` and `[BUGFIX]`.

Looking at the last few days of commit history, not many follow this guideline.

Perhaps its time to consider retiring this information and shorten the contribution guide?

**Comment by rwjblue** [comment]
The contributing doc information on commit prefixes is correct... 

The last few days of activity have not been documentation or bug fixes.  :smile:
