### ISSUE TITLE
Modularize tests

### ISSUE THREAD

**Issue by johnnyshields** [emberjs/ember.js#11085]
It would be really nice if each Ember test file could be an ES6 module.

```coffeescript
# coffeescript, mocha
`import Ember from 'ember';`
`import startApp from '../helpers/start-app';`

test = ->

  describe 'Home', ->
    # do stuff

`export default test`
```

Currently I'm doing this but it requires a Bootstrap file for each type of test. (I'm using Mocha)

```js
import homeTest from './home';
import foobarTest from './foobar';

describe('Acceptance', function () {
  homeTest();
  foobarTest();
});
```

**Comment by rwjblue** [comment]
This is the repo for tracking issues with Ember itself.  This doesn't seem like an Ember issue so I am going to close this issue.  Perhaps you meant to open this in the ember-cli repo?

Also, as an aside, it should be pretty straight forward to change the test loader (used by ember-cli-mocha in your case) to do this for you automatically.

**Comment by johnnyshields** [comment]
Cool, thanks will try to modify the test loader.
