### ISSUE TITLE
Select views do not select the appropriate value

### ISSUE THREAD

**Issue by tpitale** [emberjs/ember.js#11082]
Based on this comment … the code below is broken, due to a failure to ever accurately compare using `===`.

https://github.com/emberjs/ember.js/blob/8962e36f16a79e336371428fd265db3a2dbbdf8e/packages/ember-views/lib/views/select.js#L53

Nothing I try to pass in to `content` and `selection` seem to match up sufficiently.

Data in `content` is coming from ember-data … the `valuePath` is for an `id`.

```javascript
{{view 'select'
  content=model.all_service_codes
  selection=problem.service_code
  optionLabelPath="content.description"
  optionValuePath="content.id"
  optionGroupPath="group"
  prompt="Select a Service Code ..."
```

I can make a jsbin if that is helpful … but it appears the solution is to match the comments.

**Comment by tpitale** [comment]
It's possible that should stay `===` but then the `id` values returned by ember-data need to be consistently integers (or consistently whatever), and the `object` value passed in would need to be passed as an integer and not an object.

**Comment by tpitale** [comment]
Oh, and I am sorting my `content` by the `group` attribute … so I'm pretty sure that's not to blame for the lack of selection.

**Comment by tpitale** [comment]
It's possible this could be the issue? https://github.com/emberjs/ember.js/issues/10492

I'm using Ember 1.12.0-beta.3.

**Comment by tpitale** [comment]
Also … may someday be resolved by https://github.com/emberjs/ember.js/issues/5259. So I guess I can close this?

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/11083.
