### ISSUE TITLE
[glimmer] SVG content not rendering

### ISSUE THREAD

**Issue by technomage** [emberjs/ember.js#11091]
The content in SVG elements is not rendering correctly under glimmer (canary).  In some cases the contents of the template are not being rendered under the primary element of a component, and in other cases the template is rendering, but in all cases the svg element shows as having 0px size in one or both dimensions even though they have explicit width and height (from bound values).  The elements in the chrome element inspector show the width and height on the element, but they are not showing that height/width when I hover over the element in the inspector.

**Comment by rwjblue** [comment]
Hmm, sounds pretty bizarre.  I realize it is likely a pain, but would you mind making a reproduction?

Thank you for reporting!

**Comment by technomage** [comment]
Sure. I need more tests on my addon anyway.

**Comment by technomage** [comment]
See failing test in cogility/ember-diagram.  There is 1 test that fails in canary and one that fails in 1.11.3 but passes in canary.

**Comment by chnn** [comment]
I ran into this issue in my app as well when Glimmer was first merged, but the latest canary seems to have fixed it.

**Comment by technomage** [comment]
This was failing at the time of my last comment. I will retest later today.

**Comment by ohnnyj** [comment]
Not sure if I am running into the same issue here. I have a component set with an svg tagName. When rendered the svg element shows up as a HTMLUnknownElement and so would result in the browser not rendering it as SVG and could explain the issues you (and myself) are having.

**Comment by salzhrani** [comment]
a jsbin would be very helpful

**Comment by ohnnyj** [comment]
Hopefully this will help. I don't have an example of my own but I based my code on this:

http://emberjs.jsbin.com/revocavixo/1/edit

If you inspect element on the svg, it will resolve as an HTMLUnknownElement.

Changing from canary to release or beta works as expected, the svg is an SVGSVGElement.

**Comment by salzhrani** [comment]
submitted a [PR](https://github.com/tildeio/htmlbars/pull/344) to htmlbars ... should fix this

**Comment by rwjblue** [comment]
OK, should have been fixed by https://github.com/tildeio/htmlbars/pull/344 upstream. Please let me know if this is still an issue and I'll reopen...

**Comment by ohnnyj** [comment]
:+1:

**Comment by technomage** [comment]
This does address the rendering issue in one of my tests, but now fails the foreign object that was passing in canary previously.

**Comment by salzhrani** [comment]
@technomage could you kindly make a jsbin please?

**Comment by mixonic** [comment]
@salzhrani I expect:

```
export default Ember.Component.extend({
  tagName: 'foreignObject'
});
```

`dom.detectNamespace(` should likely be called in the manual element. It is called in htmlbars [here](https://github.com/tildeio/htmlbars/blob/82f11703ec7a2d160ece6d29e41dad7b1d2ecda8/packages/htmlbars-runtime/lib/render.js#L22) but perhaps that path is skipped?

A simple reproduction is definitely the first step.

**Comment by technomage** [comment]
As stated earlier.  The tests in cogility/ember-diagram reproduces the foreign object issue

**Comment by salzhrani** [comment]
I have made a [jsbin](http://jsbin.com/qogenufoxe/1/edit?html,js,output) to show the issue. from what I gathered htmlbars doesn't have enough information to set the proper namespace. Specifically to reset the namespace after the `foreignObject` element, the current namespace need to be the svg namespace set by the parent... currently it is the default. Most likely require changes in ember. I think this issue should be reopened.

**Comment by mixonic** [comment]
@salzhrani this was definitely working. An HTMLBars template should always be running `detectNamespace` before it creates DOM. This would allow the dom helper to enter the SVG namespace before the `foreignObject` tag is encountered. HTMLBars should be outputting a `setNamespace` after the `foreignObject` to enter xhtml.

**Comment by technomage** [comment]
Note that this works when all the elements (SVG, foreign object) are in one template.  The failure is when components and templates are used to assemble the resulting set of elements.  In particular when the SVG element comes from one component and the nested foreign object is in a contained component or grand-child component in my case.

**Comment by salzhrani** [comment]
Maybe @mmun or @wycats could advise

**Comment by rwjblue** [comment]
Can someone confirm if this is still an issue?

**Comment by therocketforever** [comment]
@rwjblue I just ran into this issue today with 1.13.8

When I have a component with `tagName: "svg"` the html in a <foreignObject> is in the page source but not draw, the `namespaceURI` of the elements within the fO is still svg. 

When I change the `tagName` to `div`, add `<svg>` to the components template & the fO is rendered.

It appears that when the `<svg>` tag is set on the component the fO namespace is never reset.

**Comment by rwjblue** [comment]
I believe this is generally working properly with recent versions of Ember.  Closing for now, but am happy to reopen if I am incorrect.
