### ISSUE TITLE
[QUESTION] testing RSVP errors handled by Ember.RSVP.on("error", function(){...})

### ISSUE THREAD

**Issue by williamsbdev** [emberjs/ember.js#11094]
I was working on a feature where I do not have an error function in my `RSVP.then(function(){//success})`. When I was testing this functionality, I kept running into issues where the default `Ember.Test.Adapter.exception` was causing a test failure because I was handling the error by listening on `Ember.RSVP.on("error", function(){//handle all errors not handled by individual promises})`. What is the best way to test that my errors are handled by the global RSVP error handing? I am currently monkey patching `Ember.Test.adapter.exception` in my test to do nothing.

Thanks in advance for the help!

**Comment by stefanpenner** [comment]
On error isn't a way to handle such an error. That is last resort hook for tooling to inform you of issues. Please use the public promise API to handle these errors

**Comment by toranb** [comment]
@stefanpenner what is a good "catch all" pattern for apps to handle 401/403 like errors globally? Do you recommend adding a handler to the application routes "error" action or something else?

thanks for the guidance !

**Comment by stefanpenner** [comment]
Write code at your adapter level to handle that. Promise catch all is far to sweeping to be useful here. You will only experience pain.

**Comment by toranb** [comment]
@stefanpenner curious what that looks like for the base xhr helper I'm using today. Any idea how I should/could modify this to supply something to "catch all" like RSVP on but only when I use this method?

ie- I'm hoping to avoid something like this in production code today

```js
findAll: function() {
    var all = Ember.A([]);
    PromiseMixin.xhr(url).then(function() {
        //normal success stuff here
    }, function() {
        //this is what I prefer NOT to write w/ each low level xhr when 401 or 403 happens :(
    });
    return all;
}
```

**Comment by stefanpenner** [comment]
Seems like adding functionality to your Ajax utility should do the trixk

**Comment by stefanpenner** [comment]
This doesn't seems like a but. But the conversation can continue. (Or more to so)
