### ISSUE TITLE
Renderer didDestroyElement sets element to null

### ISSUE THREAD

**Issue by technomage** [emberjs/ember.js#11090]
An exception is thrown when a view is removed for setting element to null without using 'set'.  The view in question is a component hosted within an SVG element with tagName of 'g' and some child svg elements.  The component is removed by removing the object causing the view to render in a #each and added to the render using the component helper.

Renderer.prototype.didDestroyElement = function (view) {
  view.element = null;

**Comment by rwjblue** [comment]
It seems like you have an observer setup on `view.element`, and when the renderer sets it to `null` during destruction the mandatory setter assertion is triggered.

Can you provide a JSBin demo showing what is happening?

**Comment by technomage** [comment]
I will see what I can do.  I do not have any observers I am aware of, but will check.

**Comment by technomage** [comment]
Yes. I had 'element' as a dependency for a computed that was computing the bounding box of the element for computations (centering text etc).  removing that resolved the issue.

Thanks.

Do you still want a recreation?  If not you can close.

**Comment by rwjblue** [comment]
Awesome, I am glad you got it fixed. `view.element` is not intended to be observed, which is why it triggered that assertion when it was observed (and then set).

I'll go ahead and close now since you have a fix...

**Comment by ef4** [comment]
I hit this while helping update an app to 1.13. The error message is pretty unhelpful, I wonder if we could warn at the time the observer is created instead of exploding during view teardown.
