### ISSUE TITLE
[Glimmer] Need Documentation: Providing {{each}} a key.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#11117]
DOM elements are now maintained, and repositioned as needed based on the `key` provided to `{{each}}`.  The default key is the index within the `{{each}}`, but a user should provide a `key` when invoking `{{each}}` so that sorting will not automatically destroy and recreate elements needlessly.

Example:

```hbs
{{#each model key="id" as |post|}}
  {{some-thing post=post}}
{{/each}}
```

**Comment by martypenner** [comment]
I'll try to find some time in the next few days to update the API docs as well.

**Comment by rwjblue** [comment]
Implemented basic API docs, and there is a guide PR pending.
