### ISSUE TITLE
[Glimmer] Fix issues with ember-cli-fastboot.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#11115]
A few of the Fastboot related unit tests were skipped so that we could focus on the more mainstream client use case.  

This issue is intended as a tracking issue to get canary back up to speed with ember-cli-fastboot.

---

I believe that @wycats and @tomdale will be spending a bit of time getting things all wired back up properly in the next couple weeks.

**Comment by tomdale** [comment]
Awesome, thank you so much. We are planning to work on angular components tomorrow and will try to get this up and running afterwards.

**Comment by rwjblue** [comment]
Huge thanks to @code0100fun for tackling this!!!
