### ISSUE TITLE
[Documentation] Dependancy Injection guides not up to scratch

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#11114]
Please see [this post](http://discuss.emberjs.com/t/dependancy-injection-in-initializers-confusing-registry-container/7972) on the Emberjs forum.

**Comment by mixonic** [comment]
@amk221 we would love help adding a section on `Ember.inject` to the guides.

**Comment by amk221** [comment]
@mixonic there's nothing more I would love than to help! but I don't know the answers, hence the forum post.

**Comment by rwjblue** [comment]
Services are documented in the current guides: http://guides.emberjs.com/v2.0.0/services/.

I'd gladly help review PR's for any changes/tweaks to that guide (and the API docs), but I'm closing for now since a guide exists...
