### ISSUE TITLE
[Glimmer] `{{#with}}` no longer displays inverse template

### ISSUE THREAD

**Issue by bantic** [emberjs/ember.js#11118]
In Ember 1.12 the "else" block is rendered if a `{{#with}}` helper is given a falsy argument, e.g.

```
{{! foo is false}}
{{#with foo as |someName|}}
  This text is never shown.
{{else}}
   This text is displayed in Ember 1.12, but not displayed in Ember Canary.
{{/with}}
```

In Ember Canary the inverse template is no longer shown.

  * [Fiddle for Ember 1.12.0-beta.3](http://jsfiddle.net/bantic/szd0apo7/)
  * [Fiddle for Ember Canary](http://jsfiddle.net/bantic/sc9rgjjw/)

**Comment by rwjblue** [comment]
Should be fixed by https://github.com/emberjs/ember.js/pull/11119.

**Comment by bantic** [comment]
@rwjblue I knew I should have made a PR before submitting the issue. :)

It is also fixed in #11120 — apparently sometimes there is no `options.inverse.yield`, so that also checks that it exists before calling.

**Comment by rwjblue** [comment]
@bantic - Nah, just mention that you are working on the fix in a comment.  I am just trying to be as responsive as possible on the Glimmer regressions.  I got over-eager ;)

**Comment by bantic** [comment]
Yeah, will do. I got over-eager, too, when I realized how easy the fix was. :)
