### ISSUE TITLE
[Glimmer] Component `attrs` compat inconsistency

### ISSUE THREAD

**Issue by opichals** [emberjs/ember.js#11111]
There is inconsistency between the old component syntax and the angle bracket syntax use with regards to the value of `attrs` (Ember canary b49c442dc3).

Using this [template](https://github.com/opichals/ember-todo/blob/0e945c39fb6a925949e8c0a096aa206c18e32350/app/templates/application.hbs):

```
{{#each todos as |item|}}
  <!-- old syntax -->
  {{#todo-item todo=item}}
    <em>{{item.title}}</em>
  {{/todo-item}}

  <!-- angle bracket syntax -->
  <todo-item todo={{item}}>
    <em>{{item.title}}</em>
  </todo-item>
  <br>
{{/each}}
```

I see the [components](https://github.com/opichals/ember-todo/tree/0e945c39fb6a925949e8c0a096aa206c18e32350/app/components/todo-item)' {{title}} mustache referencing the Components' `titleBinding: 'attrs.todo.title'` not working properly whereas it seems to be working as expected when accessed accessed using {{attrs.todo.title}} mustache.

Component:
```
Ember.Component.extend({
  titleBinding: 'attrs.todo.title'
});
```

Component template:
```
working in both syntaxes: {{attrs.todo.title}}
not working in the old syntax: {{title}}
```

The above seems to work as expected with the new angle bracket syntax.

**Comment by rwjblue** [comment]
The underlying code here has had a few different iterations, and I believe this is working properly now.

Closing for now, but let me know if it is still broken (a JSBin would be very helpful) and I'll reopen...
