### ISSUE TITLE
[Glimmer] the render hook is no longer being called on components

### ISSUE THREAD

**Issue by tim-evans** [emberjs/ember.js#11128]
I'm using an old-style `render` function for backwards compatibility with https://github.com/paddle8/ember-document-title

I'm trying to patch my render code (https://github.com/paddle8/ember-document-title/blob/master/addon/components/document-title.js#L35) with an object that behaves like the old buffer / _morph attributes used to.

When debugging this, I found that the `render` hook isn't being called when the components are appended to the dom. Digging through the new view code, I found a curiously named method that isn't used anywhere, but implies backwards compatibility:

https://github.com/emberjs/ember.js/blob/8962e36f16a79e336371428fd265db3a2dbbdf8e/packages/ember-views/lib/compat/render_buffer.js#L112

I would love to get `ember-document-title` working on canary ASAP, since it's a fairly well-used addon.

Cheers!

**Comment by rwjblue** [comment]
Thanks for raising the issue, looking into it....

**Comment by rwjblue** [comment]
Should be resolved by https://github.com/emberjs/ember.js/pull/11130.

**Comment by tim-evans** [comment]
@rwjblue :+1: Thanks for the quickness!

**Comment by rwjblue** [comment]
No problem, please continue testing and report any issues that crop up...
