### ISSUE TITLE
1.11.3 -- Cannot pass classNameBindings to input as computed property

### ISSUE THREAD

**Issue by Samsinite** [emberjs/ember.js#11126]
Inside of an input component wrapper I am trying to pass dynamic class names to an inner input (`{{input classNameBindings=inputComputedClassNames}}`) and it errors out due to the split method not being available on a SimpleStream. Would be happy to provide more details if needed, thanks!

**Comment by rwjblue** [comment]
I am fairly certain that I understand the issue, but would you mind throwing a JSBin together to make sure I am on the right track?

**Comment by Samsinite** [comment]
Sure, I'll have one available soon.

**Comment by Samsinite** [comment]
Here you go: http://emberjs.jsbin.com/gizipu/1/

**Comment by rwjblue** [comment]
Sorry for the super long delay, seems to be working now...

**Comment by Samsinite** [comment]
lol no problem, thanks for the follow up. I have a feeling this has been
working since the 1.12 series.

-Sam
