### ISSUE TITLE
[Glimmer] application template without a view does not have a controller local in the template

### ISSUE THREAD

**Issue by teddyzeenny** [emberjs/ember.js#11121]
http://emberjs.jsbin.com/rixanu/1/edit?html,js,output

**Comment by teddyzeenny** [comment]
My guess is we should `lookupFactory` [here](https://github.com/emberjs/ember.js/blob/6af6fa4c6dd754fc722441602c1bc65a7e9359e0/packages/ember-htmlbars/lib/keywords/real_outlet.js#L53) instead of just `lookup`.

**Comment by rwjblue** [comment]
You are spot on, should be fixed by https://github.com/emberjs/ember.js/issues/11132.

**Comment by rwjblue** [comment]
@teddyzeenny - Thanks for tracking this down and making the fix easy?
