### ISSUE TITLE
[Glimmer] Ember.HTMLBars._registerHelper no longer 'backed' by a view

### ISSUE THREAD

**Issue by thoov** [emberjs/ember.js#11124]
We have a table addon internally that exposes a declarative syntax like so:

```handlebars
{{#my-table model=arrayOfPeople}}
    {{#my-column header='First Name'}}
        {{firstName}}
    {{/my-column}}
      
    {{#my-column header='Last Name'}}
        {{lastName}}
    {{/my-column}}
      
    {{#my-column header='Email'}}
        <a href="mailto:{{lastName}}">{{email}}</a>
    {{/my-column}}
{{/my-table}}
```

Which produces your standard HTML table. In order for this to work we used some internal/private apis which do not work/not supported in glimmer.

There was a call to show examples of addons using private apis that have broken so I have documented the issues I am facing in this jsbin (http://emberjs.jsbin.com/fazizu/16/edit?html,js,output) along with a working example in 1.12. If the example or comments do not make sense let me know and I will clarify. 

I am ok with changing any/all logic to get this functionality working. I just want to know the recommended way going forward with glimmer.

**Comment by stefanpenner** [comment]
it would be interesting if we could  (we may be able to) do the following:

```hbs
{{#component 'my-column' attrs=attrs }}
  {{yield}}
{{/component}}
```
