### ISSUE TITLE
Mixin with injected service fails

### ISSUE THREAD

**Issue by et** [emberjs/ember.js#11135]
If a mixin has an injected service, trying to instantiate an object that uses the mixin will fail with this error when trying to retrieve the service.

`Error: Assertion Failed: Attempting to lookup an injected property on an object without a container, ensure that the object was instantiated via a container.`

This [commit](https://github.com/et/mixin-with-service/commit/072bd8a1bec7c0149c675bd2b83e110e3a94a8b5) shows the setup, the line that fails is when the service is [retrieved in the mixin](https://github.com/et/mixin-with-service/commit/072bd8a1bec7c0149c675bd2b83e110e3a94a8b5#diff-7d184bfdaeb4e706fe5386ee012c34caR7).

**Comment by nullrocket** [comment]
I have the same issue with an object using a mixin.  The only difference is the service is injected on to the object and not on the mixin.

**Comment by mixonic** [comment]
@et This error is correct. When you create the object [here](https://github.com/et/mixin-with-service/commit/072bd8a1bec7c0149c675bd2b83e110e3a94a8b5#diff-0afd973487c4dfd74adaf9edbb458e5bR9), you have provided no container. Thus, the injection cannot be made. You will need to pull the object out of the container.

@nullrocket if the factory is instantiated by the container, and the injected factory is also in the container, the injection is expected to work. If it doesn't a reproduction would be great.

I'm going to close this ticket, but please re-open or make a new issue if I've missed something.

**Comment by joshforisha** [comment]
What was the actual solution here? I see in the original repo that a `needs` array was added to the module call, but that doesn't seem to solve my essentially identical problem in 1.13.

@mixonic What exactly should be done to "pull the object out of the container"?

**Comment by mixonic** [comment]
@joshforisha I mean using `container.lookup('type:name')` to fetch an instance instead of using `.create`. You can also pass the `container` to `create` directly and I think that would work for the purposes of your test.

**Comment by pwfisher** [comment]
Specifically, here's how you use `lookup` instead of `create`:
```
import Ember from 'ember';
import FooMixin from 'my-app/mixins/foo';
import { moduleFor, test } from 'ember-qunit';

moduleFor('mixin:foo', {
  needs: [
    'service:bar',
  ],
});

test('it works', function testItWorks(assert) {
  const FooObject = Ember.Object.extend(FooMixin);
  this.registry.register('test:subject', FooObject);
  const subject = this.container.lookup('test:subject');
  assert.ok(subject);
});
```

**Comment by alexmiddeleer** [comment]
@pwfisher Thanks for that. I would note that I scratched my head looking at that code until I realized I needed ember-qunit instead of qunit. http://www.chriskrycho.com/2016/testing-emberjs-mixins-with-a-container.html also helped.
