### ISSUE TITLE
Is there any chance ember will officially support emblem as an optional markup syntax?

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember.js#11147]
top of the readme says they are looking for a new maintainer https://github.com/machty/emblem.js/

emblem is much much less verbose than handlebars, which is nice. 
it would also be great to not have to convert everything over to handlebars if something happens with emblem like a incompatibility due to lack of maintenance.

**Comment by mixonic** [comment]
I don't believe Ember Core has the capacity to maintain two templating languages. Emblem will almost certainly remain a community project.
