### ISSUE TITLE
#each with else block causes problem

### ISSUE THREAD

**Issue by ilkkao** [emberjs/ember.js#11140]
Jsbin: http://jsbin.com/dirukazagi/3/edit?html,js,output

Browser error `Uncaught TypeError: Cannot read property 'insertBefore' of null`

It looks like the each helper mutates 'model` property and sets it to null.

**Comment by ilkkao** [comment]
In the jsbin I mean that if you remove `else` block, the problem disappears.

**Comment by rwjblue** [comment]
Thanks for the report!  The JSBin should help us isolate the cause...

**Comment by rwjblue** [comment]
Created a failing test case for this at: https://github.com/emberjs/ember.js/compare/each-inverse-to-template.

**Comment by hibariya** [comment]
I'm also facing this issue. Any updates?

**Comment by SebastianEdwards** [comment]
I'm also facing this issue. Any updates?
