### ISSUE TITLE
[Glimmer] Views should not receive new-style lifecycle hooks

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#11143]
Since https://github.com/emberjs/ember.js/commit/84c28755c457cc44d261c5bcbdb126ecc214184e, the lifecycle hooks are inconsistent between views and components. For example, the `willReceiveAttrs` hook has been renamed to `didReceiveAttrs` on components, but not on views. Talked to @wycats about it, the plan is "to remove all of the new lifecycle hooks from views", because "views are sufficiently crazy that I don't want to try to mix in new semantics".

Opening an issue for now, if someone wants to quickly do it please feel free to grab. Otherwise I'll do it later/soon :)

**Comment by rwjblue** [comment]
Closing this for now.  `Ember.View` is no longer exposed externally without the `ember-legacy-views` addon...
