### ISSUE TITLE
Error while processing route: property.index params is not defined ReferenceError: params is not defined

### ISSUE THREAD

**Issue by jimmyjamieson** [emberjs/ember.js#11145]
Hi, I have ember 1.11.3, ember-data 1.0.0-beta.16.1 and using ember-cli 0.2.3 with the pod structure.

I've done "ember g resource properties" which has created the /pods/properties and /pods/property folders.

In the main app/router.js

```
export default Router.map(function() {
  this.resource('properties', { path: '/' }, function() {
    this.resource('property' , { path: 'property/:property_id' }, function() {});
  });
});
```

Then under /pods/**property**/model.js I have

```
export default DS.Model.extend({
  name: DS.attr('string'),
  body: DS.attr('string'),
  price: DS.attr('number')
});
```

In the pods/**property**/route.js I have

```
export default Ember.Route.extend({
  model: function() {
    return this.store.find('property', params.property_id);
  }
});
```

pods/**properties**/route.js

```
export default Ember.Route.extend({
  model: function() {
    return this.store.find('property');
  }
});
```

pods/**properties**/controller.js

```
export default Ember.ArrayController.extend({
  sortProperties: ['name'],
  sortAscending: true,
});
```

pods/**properties**/template.hbs

```
<ul>
  {{#each property in controller}}
      <li>
        {{#link-to 'property' property}} {{property.name}} {{/link-to}}
      </li>
  {{else}}
      <li>No properties found.</li>
  {{/each}}
</ul>
```

If I click through to the page it shows the information fine. But when I **refresh**, it goes blank and displays the console error

**Error while processing route: property.index params is not defined ReferenceError: params is not defined**

I've been looking through the docs. and it looks all correct. So i'm not sure what's up. The error could do with a little more info.

If I change my main route to (For the sake of having a full detail page)

```
export default Router.map(function() {
  this.resource('properties', { path: '/' }, function() {});
  this.resource('property' , { path: 'property/:property_id' }, function() {});
});
```
I still get the error on refresh

How do I achieve this without the error?

**Comment by jimmyjamieson** [comment]
I've not updated my app/router.js to 
```
export default Router.map(function() {
  this.route('properties', { path: '/' }, function() {});
  this.route('property' , { path: '/properties/:property_id' });
});
```
and my pods/**property**/route.js to
```
export default Ember.Route.extend({
  model: function(params) {
    return this.store.find('property', params.property_id);
  }
});
```

But now I get the error

**Error while processing route: property Unexpected end of input SyntaxError: Unexpected end of input**

Either something weird, or the docs aren't explaining things correctly.

**Comment by stavarotti** [comment]
@jimmyjamieson, you are better served by opening this issue on the ember-cli repo.

**Comment by jimmyjamieson** [comment]
@stavarotti You think it's more of an CLI issue?

I'll give it a try

**Comment by rwjblue** [comment]
I'm going to go ahead and close this for now as it seems to have gone stale...
