### ISSUE TITLE
Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by juanjardim** [emberjs/ember.js#11159]
When i'm call notifyPropertyChange on an arrayProxy there are an error in the line "childView = childViews[idx];" (aprox. 37316) because this return an empty object. Possible solution will be check if the object is undefined.

Version 1.11.1

**Comment by rwjblue** [comment]
Can you provide a JSBin reproduction to help us understand the issue?

**Comment by stefanpenner** [comment]
without a reproduction or further information this issue isn't actionable. As this seems to have gone stale, I will be closing.


Will gladly reopen if some actionable information is provided
