### ISSUE TITLE
[Glimmer] id/class-names from dasherized to snake-case w/upgrade

### ISSUE THREAD

**Issue by h55nick** [emberjs/ember.js#11151]
Testing an app with glimmer and ran into a discrepancy. 

Example:

```
{{input value=startDate id='start-date'}}
```
used to become (1.10):

``` 
<input id="start-date" class="ember-view ember-text-field" type="text">
```
but now is (1.13.0)

```
<input id="ember1308" type="text" class="start_date ember-view ember-text-field"></input>
```

I am upgrading from 1.10 to 1.13.0-beta.1+canary.167fe589
htmlbars kept at 0.7.4

Feel like this would have broken 'something' prior to me hitting this. 

Let me know what other information I can provide!

Thanks

**Comment by rwjblue** [comment]
Thanks for reporting!  We'll get it fixed soon...

**Comment by rwjblue** [comment]
Hmm, this does not seem to be the case, in a [quick demo](http://emberjs.jsbin.com/rwjblue/483/edit?html,js,output) I get the proper `id` and `class` attributes.  Can you share a repro (feel free to tweak mine above)?

**Comment by h55nick** [comment]
Thanks for taking a look. I'll see if I can reproduce in the jsbin in the am (go rangers!!). Felt like this was a bit dramatic not to be noticed pre-canary.

**Comment by h55nick** [comment]
the demo does work as expected. going to close this and reopen when I can reproduce. 

Thinking that it has to do with my template compiler version or something of the sort but will investigate. 

Thanks for being so responsive and apologizes for not putting together the js-bin prior.

**Comment by rwjblue** [comment]
No worries! Please let us know if you do track down the cause...
