### ISSUE TITLE
1.12.0 "Using the same function as getter and setter is deprecated." on non computed properties

### ISSUE THREAD

**Issue by ChrisHonniball** [emberjs/ember.js#11162]
I'm receiving the:

```
Using the same function as getter and setter is deprecated.
```

on all of my *non-*computed properties for my models. It's triggering on my `DS.attr('type')` properties. When I click the Ember inspector link to view the related line it takes me to (just an example):

```javascript
auth_date: DS['default'].attr('datetime'),
```

It happens on *all* properties in my models no matter what `DS.attr('type')` they are declared as.

**Comment by wagenet** [comment]
This is an Ember Data issue. Are you using the latest version of it?

**Comment by ChrisHonniball** [comment]
I was using Ember Data v1.0.0-beta.16.1. Updated to v1.0.0-beta.17 and all is good! Thanks alot! :beers:
