### ISSUE TITLE
[Glimmer] {{each}} with itemViewClass = broken tagName & {{else}} 

### ISSUE THREAD

**Issue by owilliams** [emberjs/ember.js#11164]
When using `itemViewClass` with `{{each}}` in Ember 1.13-beta.1, the item view's `tagName` is not used and is always rendered with a `div`.

```html
<ul>
      {{#each model itemViewClass="listItem" as |item|}}
        <h4>{{item}}</h4>
      {{/each}}
</ul>
```
```js
App.ListItemView = Em.View.extend({
  tagName: 'li'
});
```

The above code should: 
```html
<ul>
  <li><h4>item #1</h4><li>
</ul>
```
But actually renders:

```html
<ul>
  <div><h4>item #1</h4><div>
</ul>
```
<hr>

When an `{{else}}` is used with and `{{each model itemViewClass ...}}`, the template is not rendered when model is falsey. It works fine when there is no ``itemViewClass``

```html
<ul>
      {{#each model itemViewClass="listItem" as |item|}}
        <h4>{{item}}</h4>
      {{else}}
        <h4>No Data</h4>
      {{/each}}
</ul>
```

Both issues are illustrated in this JSBin: http://emberjs.jsbin.com/xumihahiwa/1/edit

There's also seems to be an issue thrown with the toggle action I added in there to set the model data on the controller to illustrate the `{{else}}` issue.

Here's it functioning fine with Ember 1.12: http://emberjs.jsbin.com/fepavokome/1/edit

**Comment by rwjblue** [comment]
Thanks for the detailed bug report.  I'll try to investigate tonight, and see exactly what is going on...

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/11228 addresses the `tagName` + `itemViewClass` issue, still looking into the `{{else}}` one...
