### ISSUE TITLE
Uncaught Error: Assertion Failed: The value that #each loops over must be an Array. You passed gozooga@controller:array:, but it should have been an ArrayController

### ISSUE THREAD

**Issue by ChrisHonniball** [emberjs/ember.js#11165]
Updated this morning to:

* Ember v1.12.0
* Ember CLI v0.2.4
* Ember Data v1.0.0-beta.17

and am now getting:

```
Uncaught Error: Assertion Failed: The value that #each loops over must be an Array. You passed gozooga@controller:array:, but it should have been an ArrayController
```

when my template has:

```handlebars
{{#each item in items itemController="item"}}
    // ...
{{/each}}
```

Worked fine in Ember v1.11.3 and can't re-test in v1.11.3 because I handled all deprecations for the new computed property syntax.

**Comment by ChrisHonniball** [comment]
I'm not 100% on this but it may be related to ember-cli's update because [This JSBin](http://jsbin.com/wagipu/3/edit?html,js,output) works.

**Comment by ChrisHonniball** [comment]
Conversion method in the [deprecation guide](http://emberjs.com/deprecations/v1.x/#toc_deprecations-added-in-1-12).

**Comment by stefek99** [comment]
Hi @ChrisHonniball 

At the moment I'm struggling with the same error:
> Uncaught Error: Assertion Failed: The value that #each loops over must be an Array. You passed ___@controller:array:, but it should have been an ArrayController

I'm following the tutorial: http://thetechcofounder.com/getting-started-with-ember-js-using-ember-cli/

Their code: ```{{#each itemController="todo"}}```

My code: ``` {{#each model itemController="todo" as |item| }}```

Can you tell me what other changes have you made?

**Comment by hlubek** [comment]
I have the same problem after upgrading to Ember v1.12.0 and Ember CLI v0.2.5.

It does not depend on the deprecated syntax of the each helper as it seems. If I remove the "itemController" the error goes away, but that's no solution for me.

**Comment by ChrisHonniball** [comment]
Currently I have to use the `render` helper to get my controller functionality but that is going to be deprecated too. So this works for now:

```handlebars
{{#each foo as |bar|}}
  {{render 'bar' bar}}
{{/each}}
```

I know components are the *new* way but they can't be organized into the nice Ember CLI directory structure so this is my method for now.

**Comment by rwjblue** [comment]
> I know components are the new way but they can't be organized into the nice Ember CLI directory structure so this is my method for now.

Why can't components be in a nice directory structure?

**Comment by rwjblue** [comment]
> I have the same problem after upgrading to Ember v1.12.0 and Ember CLI v0.2.5.

You will have to remove [ember-disable-proxy-controllers](https://github.com/cibernox/ember-disable-proxy-controllers) from your `package.json`.  It changes `controller:array` to be an `Ember.Controller`, which is generally good for new apps, but it does break usage of `itemController`. 

> It does not depend on the deprecated syntax of the each helper as it seems. If I remove the "itemController" the error goes away, but that's no solution for me.

`itemController` is deprecated in 1.13, and will be removed at some point in the future.  I definitely suggest refactoring when you can to avoid using deprecated features...

**Comment by ChrisHonniball** [comment]
> Why can't components be in a nice directory structure?

Are you able to `ember g component path/to/some/thing`? I tried it in the past and it didn't work. Can't remember what version of Ember CLI it was back then though. Just adopted the `render` helper to compensate.

How would the component look with: `{{render 'path/to/some/thing' thing}}` being replaced?

```
{{component 'path/to/some/thing' model=thing}}
```

Or

```
{{path-to-some-thing model=thing}}
```

**Comment by hlubek** [comment]
Okay, thank you very much @rwjblue for the explanation.

**Comment by rwjblue** [comment]
> Are you able to ember g component path/to/some/thing?

Yes.

> I tried it in the past and it didn't work.

It was not supported by Ember until 1.9.  I am not sure when the blueprints were updated to support subdirectory paths though.

> How would the component look with: `{{render 'path/to/some/thing' thing}}` being replaced?
>
> `{{component 'path/to/some/thing' model=thing}}`

The later, but remember that components will need a hyphen to be looked up properly.  

```hbs
{{path/to/some-thing mode=thing}}
```

**Comment by asross** [comment]
> itemController is deprecated in 1.13, and will be removed at some point in the future. I definitely suggest refactoring when you can to avoid using deprecated features...

@rwjblue is `itemController` really deprecated in 1.13? It doesn't look like it [from the deprecation notes](http://emberjs.com/deprecations/v1.x/#toc_deprecations-added-in-1-13). I'd definitely believe you if you say it's deprecated in 2.0, though.

**Comment by rwjblue** [comment]
It is definitely deprecated for 1.13.  Apparently, the deprecation guide needs to be updated.

Demo: http://rwjblue.jsbin.com/rwjblue/626/edit?html,js

Deprecation message:

```
DEPRECATION: Using 'itemController' with '{{each}}' ('application' @ L4:C18) is deprecated.  Please refactor to a component.
        at http://builds.emberjs.com/tags/v1.13.3/ember.debug.js:39968:34
        at Walker.visit (http://builds.emberjs.com/tags/v1.13.3/ember-template-compiler.js:17975:7)
        at visitors.Program (http://builds.emberjs.com/tags/v1.13.3/ember-template-compiler.js:17985:16)
        at Walker.children (http://builds.emberjs.com/tags/v1.13.3/ember-template-compiler.js:18008:7)
        at Walker.visit (http://builds.emberjs.com/tags/v1.13.3/ember-template-compiler.js:17976:12)
        at TransformEachIntoCollection_transform [as transform] (http://builds.emberjs.com/tags/v1.13.3/ember.debug.js:39960:12)
        at Object.preprocess (http://builds.emberjs.com/tags/v1.13.3/ember-template-compiler.js:17374:27)
        at compileSpec (http://builds.emberjs.com/tags/v1.13.3/ember-template-compiler.js:12529:37)
        at compile (http://builds.emberjs.com/tags/v1.13.3/ember-template-compiler.js:12578:48)
```
