### ISSUE TITLE
[REGRESSION] currentURL() broken for acceptance testing in ember 1.12

### ISSUE THREAD

**Issue by toranb** [emberjs/ember.js#11175]
I have a great deal of tests that check the current url like so and upgrading to ember.js 1.12 seems to have broken this. After the upgrade each url is "" (empty string) for some odd reason. Is this deprecated/removed/broken ?

```js
   visit("/foo");
   click("button.edit");
   andThen(function () {
        assert.equal(currentURL(), "/foo/edit/1");
    });
```

I didn't see any mention of it in the blog post about 1.12 so I assumed it wasn't planned

http://emberjs.com/blog/2015/05/13/ember-1-12-released.html

thank you in advance

**Comment by toranb** [comment]
note: just built a completely new ember app using ember-cli 0.2.4 and this is *not* a problem.

I'll investigate further to see why all of our internal apps fail when we upgrade :)

**Comment by mixonic** [comment]
@toranb I believe this is a known issue with a ticket somewhere, cannot find it.

**Comment by toranb** [comment]
Found a related ticket that @rwjblue is already working on it seems

https://github.com/emberjs/ember.js/issues/10784

**Comment by tcjr** [comment]
Are you using `location: 'auto'`?  If so, it could be related to this: #10943

**Comment by toranb** [comment]
In the broken app I'm using location hash. In the new ember-cli app I tried both auto and hash and it seemed to make no difference.

**Comment by dustinfarris** [comment]
Fails in a brand new app with ember-cli:  https://github.com/ember-cli/ember-cli/issues/4097

**Comment by elskwid** [comment]
@toranb - take a look at the proposed PR above - I ran into this exact issue today and couldn't stop digging. It "fixes" the issue for me but more eyes on the code would make me feel better.

**Comment by rwjblue** [comment]
Fixed by #11201. Thanks @elskwid!

**Comment by toranb** [comment]
Awesome! any plans for a 1.12.1 release this week @rwjblue  ?

**Comment by rwjblue** [comment]
There will be a release, not sure exactly when. We have a small number of other regressions that need to be fixed also.  In the meantime you should be able to use `bower install ember#release` (which is always the latest build of the release channel) to get the fix...
