### ISSUE TITLE
Component `sendAction` doesn't handle `attrs. + action` correctly

### ISSUE THREAD

**Issue by jnhuynh** [emberjs/ember.js#11176]
I pass a route action name string to a component. That component will send that action when one of it's own actions is triggered. Refer to the example below.

```js
// In my route's template
{{some-component specialAction='NameOfActionInMyRoute'}}
```

```js
// components/some-component.js
...
actions: {
  rightButtonClick: function() {
     this.sendAction('specialAction');
  }
}
...

// Template
<button {{action 'rightButtonClick'}}>
  Mr. Right Button
</button>
```

Given the below implementation in Ember.1.13.0-Beta-1:

```js
 sendAction: function (action) {

      ...

      // Send the default action
      if (action === undefined) {
        ...
      } else {
        actionName = property_get.get(this, "attrs." + action) || property_get.get(this, action);
        Ember['default'].assert("The " + action + " action was triggered on the component " + this.toString() + ", but the action name (" + actionName + ") was not a string.", isNone['default'](actionName) || typeof actionName === "string" || typeof actionName === "function");
      }
```

`property_get.get(this, "attrs." + action)` will return an object of the following format:

```
Object {
  value: "NameOfActionInMyRoute",
  update: function,
  MUTABLE_CELL [id=__ember1431709265242204799127239]: true
}
```

Since the result is an `Object` it **fails** the assertion.

We can extract the value by changing the `actionName` assignment to:

```js
actionName = property_get.get(this, "attrs." + action + ".value") || property_get.get(this, action);
```

That's just a suggestion though, I'm not sure of the implications of the change.

**Comment by jnhuynh** [comment]
I reverted to Ember 1.12.0. Bug is gone. The implementation for `sendAction` is different of course.

**Comment by rwjblue** [comment]
I attempted to replicate the scenario you described in [this JSBin](http://emberjs.jsbin.com/rwjblue/507/edit?html,js), but it properly triggers the route action.

**Comment by rwjblue** [comment]
Ahh, so it appears that you are not passing the action name down as a string in the template, but rather as a bound property that resolves to a string (like `{{some-thing action=somePropertyHere}}`).  This is definitely triggering a bug in the sendAction code.

Demo: http://emberjs.jsbin.com/rwjblue/508/edit

**Comment by oskarrough** [comment]
Possibly related, I can't send actions to components since 1.13-beta.1: http://stackoverflow.com/questions/30274097/sending-actions-to-a-component-with-ember-js-1-13?noredirect=1#comment48650708_30274097 (isolated test cases included)

**Comment by mixonic** [comment]
Working through this now, I'll have a fix in an hour or two

**Comment by oskarrough** [comment]
@mixonic thanks a lot. Tried it out but no dice with the testcase here: http://jsbin.com/gohovifedi/2/edit

Any ideas?

**Comment by mixonic** [comment]
@oskarrough this issue was completely unrelated to #11192.

**Comment by jnhuynh** [comment]
@mixonic and @rwjblue Thanks for fixing this!
