### ISSUE TITLE
{{link-to}} not active until new route loads

### ISSUE THREAD

**Issue by flyswatter** [emberjs/ember.js#11180]
Is there a way of indicating "loading" via a `link-to` helper, other than the `active` class?  Some routes take a bit of time to load, and I'd like to give some visual indication to my users.

**Comment by topaxi** [comment]
There should be a class `ember-transitioning-in` on the new `link-to` element and a `ember-transitioning-out` on the old one..

**Comment by flyswatter** [comment]
I’m running Ember 1.9.1, and I don’t see either of these on my elements during transitions.

**Comment by flyswatter** [comment]
I agree, this seems like it should be available [as of this PR](https://github.com/emberjs/ember.js/pull/9919), not sure why I don't see it locally...

**Comment by flyswatter** [comment]
Ah, this was only added to master [six days ago](https://github.com/emberjs/ember.js/blob/master/FEATURES.md).

**Comment by rwjblue** [comment]
That PR landed quite a while ago, and is included in Ember 1.10.

I'm going to close, as it seems the question has been answered for newer versions (and there isn't much we can do about 1.9 at this point).
