### ISSUE TITLE
[1.13-beta.1] rerendering component after changing layout fails.

### ISSUE THREAD

**Issue by masda70** [emberjs/ember.js#11186]
I have the following component definition (details omitted):

```js
import Ember from 'ember';

var processRaw = function(raw){
   [...]
  return someTemplateContent;
};

var Component = Ember.Component.extend({
  raw: '',

  updateLayout: function() {
    var raw = processRaw(this.get('raw') || '');

    var layout =  Ember.HTMLBars.compile(raw);

    this.set('layout', layout);
    this.rerender();
  },

  observeRaw: function() {
    Ember.run.debounce(this, this.updateLayout, 250);
  }.observes("raw")
});

export default Component;
```

The component dynamically changes its layout based on the value of its `raw` attribute.

It works as expected with Ember 1.12.0. With Ember 1.13-beta.1, the `updateLayout` method executes fine (no error is thrown), but the component renders nothing. Am I doing some wrong?

**Comment by rwjblue** [comment]
Demo JSBin: http://emberjs.jsbin.com/rwjblue/530/edit

**Comment by cascalheira** [comment]
+1: Same problem here

**Comment by rwjblue** [comment]
Tracking in the failing test PR: https://github.com/emberjs/ember.js/pull/11315
