### ISSUE TITLE
Trouble with v1.12 Ember.Select and Arrays

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/ember.js#11185]
I'm following the [`Ember.Select` docs](http://emberjs.com/api/classes/Ember.Select.html).

I have
```js
// app/controllers/application.js
export default Ember.Controller.extend({
  locales: [
    { name: "English", code: "en" },
    { name: "Spanish", code: "es" }
  ]
});
```
and
```hbs
{{!-- app/templates/application.hbs --}}
{{view 'select'
       class='select-locale'
       content=locales
       optionLabelPath='content.name'
       optionValuePath='content.code'
       value=selectedLocale}}
```

But that causes the following exception:

> The value that #each loops over must be an Array. You passed [[Object object], [Object object]]

from [`_assertArrayLike`](https://github.com/emberjs/ember.js/blob/v1.12.0/packages/ember-views/lib/views/each.js#L62-L66).

If I force it to an `EmberArray` via `Ember.ArrayProxy.create({ content: [...] })`, then I instead get

> TypeError: this.__defineNonEnumerable is not a function

**Comment by jamesarosen** [comment]
While the browser error message in the latter case is `TypeError: this.__defineNonEnumerable is not a function`, I think the browser is confused. When I click on the stack trace, I'm taken to [`content.addArrayObserver`](https://github.com/emberjs/ember.js/blob/v1.12.0/packages/ember-runtime/lib/system/array_proxy.js#L192) in [`ArrayProxy.prototype._setupContent](https://github.com/emberjs/ember.js/blob/v1.12.0/packages/ember-runtime/lib/system/array_proxy.js#L184-L197).

One hypothesis: prototype extensions are off.

**Comment by rwjblue** [comment]
Does this happen to be in an ember-cli addon? We intentionally disable prototype extensions for addons while developing the addon...

**Comment by jamesarosen** [comment]
It is indeed.

**Comment by rwjblue** [comment]
This is done to help ensure that addon authors do not require extensions, since they cannot be guaranteed to be available in all applications that use the addon.

**Comment by jamesarosen** [comment]
So does `Ember.Select` require prototype extensions?

**Comment by rwjblue** [comment]
Ember.Select itself does not require prototype extensions, but it does use `{{each}}` which requires the thing being iterated to have things like `addArrayObserver` (and a few others).

In your case, wrapping the selects content in `Ember.A` is all you should need to do. 

We should likely remove this requirement (there is a PR by @stefanpenner to work on this) and update the docs in the meantime to use `Ember.A`.

**Comment by jamesarosen** [comment]
`Ember.A` does the trick! (I had assumed wrapping in `Ember.ArrayProxy` was what I wanted; I was just doing the wrong wrapping.)

Thanks.
