### ISSUE TITLE
[Glimmer] Inside component template, binding to the a property same as component's name in camelCase causes assertion error

### ISSUE THREAD

**Issue by XrXr** [emberjs/ember.js#11183]
If there is a component named `good-day`, and there is a property named `goodDay` in that component, trying to bind to `goodDay` inside the component's template will cause an assertion error

`Uncaught Error: Assertion Failed: You canot use 'goodDay' as a component name. Component names must contain a hyphen.`

[JSBin](http://emberjs.jsbin.com/bohajomeji/1/edit)

Currently reproducible on 1.13.0 beta 1 and Canary, works on 1.12.0

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/11222.
