### ISSUE TITLE
[Glimmer] Accessing view's elementId by viewName not working

### ISSUE THREAD

**Issue by jesenko** [emberjs/ember.js#11188]
In pre-glimmer version, it was possible to name view using `viewName` property and then access its `elementId` in parent template via `{{<viewName>.elementId}}`. In current beta/canary, it does not work any more.

[JsBin](http://emberjs.jsbin.com/rwjblue/269/edit?html,js,output)

**Comment by dschmidt** [comment]
We are using viewName to pass a component into another and use it as action target, which seems to be broken for the same reason: http://emberjs.jsbin.com/fogowacidi/2/edit

**Comment by rwjblue** [comment]
@dschmidt - Your description closely resembles #11192 (which is almost certainly related to the same issue here).

**Comment by rwjblue** [comment]
See comment in https://github.com/emberjs/ember.js/issues/11156#issuecomment-102896935 for a description of what is going on, a better go forward pattern, and another JSBin demoing it.
