### ISSUE TITLE
[1.13.0-beta.1] View context changed on {{each}}

### ISSUE THREAD

**Issue by igorsantos07** [emberjs/ember.js#11199]
When upgrading from 1.12 to 1.13, more than deprecation warnings, I saw a breaking change (bug?) in View context handling on `{{each}}`. [JSBin sample is here](http://emberjs.jsbin.com/yoheyevufe/1/edit?html,js,output).

In short:
Main template: `{{each item in model itemViewClass='sample'}}`
Sample view template: `<p>1.12: {{item.name}} || 1.13: {{name}}</p>`

On 1.12 the view's context would contain the iteration instance `item`. On 1.13 that's not there anymore, as that instance is itself the view context.

I saw nothing on this matter on docs, changelogs or deprecations list. Am I blindly searching or is this a real issue for who's moving to 1.13?

**Comment by rwjblue** [comment]
No, this is a bug and it should be fixed before 1.13.0 is final.
