### ISSUE TITLE
[1.13.0-beta1] Component-classNameBindings only adds first array element

### ISSUE THREAD

**Issue by mydea** [emberjs/ember.js#11193]
With 1.13.0-beta.1, all items in a classNameBindings-Array for a component after the first item are ignored.

This means that the following:

    classNameBindings: [":test1", ":test2"]

Will result in a component with the class test1, but not test2.

I made a quick jsbin to show the problem:

http://emberjs.jsbin.com/zoqexiyequ/1/edit

**Comment by mixonic** [comment]
Confirmed. Absolutely a regression.

**Comment by rwjblue** [comment]
Fixed by #11194.  Updated canary JSBin: http://emberjs.jsbin.com/jogaxa/1/edit?html,js.
