### ISSUE TITLE
Multiple apps break view -> controller bindings as of 1.12

### ISSUE THREAD

**Issue by botandrose** [emberjs/ember.js#11195]
Hi folks, thanks for Ember!

I just upgraded my app to the latest stable release (1.12) and noticed a regression: If you have multiple Ember apps on a single page, some of the view -> controller bindings stop working on the first app. Below is a JSbin reproducing the bug, with steps to reproduce.
 
http://emberjs.jsbin.com/topehoyewu/1/

If you change the links in the HTML to link to ember v1.11.3, the bindings work, so the regression was introduced in 1.12, so my guess is that its related to some of the fastboot groundwork. I've tried it in 1.13.beta.1 and 2.0 canary, and the bug is there as well.

I'd love to help get this fixed, but I'll need some guidance on how to turn this into a failing test, since it involves multiple apps. Any advice?

**Comment by botandrose** [comment]
Okay, got a big ugly integration test that reproduces the failure, and git bisect reveals that https://github.com/emberjs/ember.js/commit/6a71ff26042f2e6f9516f9616d88159a2acd8bec caused this regression. For completeness, here is the failing test: https://gist.github.com/botandrose/afe8cae68ec031362640

I don't understand Ember's internals well enough to know what's the best thing to do here. But I could always open a PR that adds the test and reverts that commit. What do you think?

**Comment by rwjblue** [comment]
@botandrose - That was very helpful, thank you for taking the time to bisect.

**Comment by botandrose** [comment]
No problem. Let me know if there's anything else I can do to help.
