### ISSUE TITLE
[glimmer] ariaRole not being applied

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#11215]
Some tests failing for my app because role="menu" isn't there...

v1.12.0-beta.3: http://jsfiddle.net/amk221/4xne94cf/ (works)
v1.13.0-beta.1: http://jsfiddle.net/amk221/4hq2un16/ (doesn't work)

**Comment by rwjblue** [comment]
Thanks for reporting!  Will try to get it fixed today...
