### ISSUE TITLE
Poor warning message: `Binding style attributes`

### ISSUE THREAD

**Issue by danmcclain** [emberjs/ember.js#11216]
![bindingwarning](https://cloud.githubusercontent.com/assets/144138/7705194/ce8ef832-fe10-11e4-9f0b-f8f18fbadabb.png)

```
Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see http://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes.
```

The warning message lacks context for where this warning is being raised (no filename/line number for warning)

**Comment by martndemus** [comment]
It also crashes my browser / slows down the app significantly when the console is open.
(I work on an app that uses a lot of computed element positioning)

**Comment by jcope2013** [comment]
is there any way/plans to provide more context to the warning?

**Comment by wkoffel** [comment]
As our app grows, this becomes a bigger and bigger headache.  We have started to do a manual binary-search through the templates by removing half of them at a time until we find the source of the warning.  Time consuming and error-prone.

Would also love an update if anyone has a way to add more context to this error.

**Comment by jcope2013** [comment]
@wkoffel stick a breakpoint in the deprecate function where that is called and then work back through the trace and you should be able to find the element that is causing it

**Comment by koreiklein** [comment]
@jcope2013 Using the backtrace worked splendidly.  None of the method names were useful, but a few frames up I found a function with a `value` variable set to `min-height: 971px;`. That information helped me track down the problem. Thanks.

**Comment by pixelhandler** [comment]
@danmcclain this seems to be related to 1.x versions  of Ember. I'll close this for now, please reopen if you think this is still an issue in 2.x
