### ISSUE TITLE
Cannot use 'error' as a component name

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#11214]
I have a component like this: `{{ui-form/field}}`
its template contains: `{{error}}` (error is a string)

I get the error ""Assertion Failed: You canot use 'error' as a component name. Component names must contain a hyphen."

It works in Ember 1.12 beta 3, but not 1.13. (I'm using ember-cli 0.2.5)

I tried to make a fiddle, but was unable to re-produce the error so I think it must be to do with the ember cli resolver?

My work around for the time being is to do this: `{{if error error}}`

**Comment by rwjblue** [comment]
I do not think this is related to the ember-cli resolver directly, and I am having trouble replicating the error in similar circumstances.   Simple JSBin attempt here: http://emberjs.jsbin.com/rwjblue/516/edit.

The assertion is triggered from [here](https://github.com/emberjs/ember.js/blob/23423536cfa1f7dcf70e427115ea53ab527226f1/packages/ember-views/lib/component_lookup.js#L10) (not the resolver) so it should be the same in JSBin if we can figure out the scenario that triggers it...

**Comment by mixonic** [comment]
I'm also seeing this in https://github.com/aptible/dashboard.aptible.com/blob/master/tests/acceptance/claim-test.js#L134-L145. Trying to create a reproducible case.

I've also noted that we are looking up many non-dashed things in the container:

![](https://api.monosnap.com/rpc/file/download?id=wYzIrgJMEhzNF275nl3jYF59IKMZxW)

If I add an `{{#if}}` to the template, we also look that up. Seems incorrect that these are requested from the container at all.

**Comment by devinus** [comment]
Am getting this as well.

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/11222.
