### ISSUE TITLE
Exporting wrong object type from a Route gives a hard to debug error

### ISSUE THREAD

**Issue by mitchlloyd** [emberjs/ember.js#11212]
I was pairing with someone today and stupidly exported a component instead of a route from a route file. The resulting message said that there was an error loading my route:

```
route._stashNames is not a function
```

The code we were dealing with had a lot going on, so we lost time debugging before we found that we had extended the wrong Ember object.

Would it be reasonable to check that an exported route is in fact an Ember.Route and give a helpful error message? Where would be a good place to put that kind of check?

**Comment by rwjblue** [comment]
I think the simplest thing to do would be to implement `resolveRoute` in the resolver, and do some sort of brand check (adding `isRoute: true`) on the returned factory. Then do an assert if the check doesn't pass...

**Comment by mitchlloyd** [comment]
Thanks for the info. I should be able to spend some time on this issue this week.

**Comment by rwjblue** [comment]
I'm going to go ahead and close this issue for now, I definitely look forward to reviewing your PR...
