### ISSUE TITLE
<input value={{mut value}}> binding not working

### ISSUE THREAD

**Issue by miguelmota** [emberjs/ember.js#11224]
I have a custom component `<my-component>`.

Inside that component I have an input field.

When the value of the input field gets updated, I have the property `value` in my-component to reflect the new value.

`{{input value=value}}` works, but

`<input value={{mut value}}>` does not work.

The property `value` in the latter does not get updated in my-component.

I have tried `this.get('value')` and `this.attrs.value.value` in my-component whenever an even occurs but it always comes back as undefined.

**Comment by rwjblue** [comment]
> `<input value={{mut value}}>`

Attribute bindings for standard built-in elements are one way. That is why you get the initial value but do not get automatic updates in your component.

I think we can definitely get `<input value={{mut thing}}>` working in the long run, but for now (and likely 2.0.0) you will have to use the `{{input}}` helper.  It was specifically created for wrapping `<input>` and adding the functionality we need for this...

**Comment by miguelmota** [comment]
I see, thanx @rwjblue

**Comment by imamjaferali** [comment]
{{input}} helper not works in IE8.
Can you help for the same issue

**Comment by miguelmota** [comment]
@imamjaferali http://emberjs.com/blog/2015/04/20/ie8-support-update.html

**Comment by topaxi** [comment]
```hbs
<input value={{value}} oninput={{mut value}}>
```

Should work though :)
