### ISSUE TITLE
Setting ApplicationAdapter to FixtureAdapter according to guide doesn't work

### ISSUE THREAD

**Issue by jonblack** [emberjs/ember.js#11232]
The `Using Fixtures` sections of the [guide](http://guides.emberjs.com/v1.11.0/models/the-fixture-adapter/) has the following:

>Simply attach it as the ApplicationAdapter property on your instance of Ember.Application:
>
>var App = Ember.Application.create();
>App.ApplicationAdapter = DS.FixtureAdapter;

I was unable to get this to work. I even tried `DS.FixtureAdapter.extend({});`. In the end, I ran `ember g adapter application` and changed the contents of `adapters/application.js` to:

    import DS from 'ember-data';
    
    export default DS.FixtureAdapter.extend({
    });

For the sake of reproducing the issue, here's all changes made to the default app created by ember-cli:

    // models/task.js
     
    import DS from 'ember-data';
     
    let Task = DS.Model.extend({
      summary: DS.attr('string')
    });
     
    Task.reopenClass({
        FIXTURES: [
            { id: 1, summary: 'Take out bin bags' },
            { id: 2, summary: 'Wash the car' }
        ]
    });
     
    export default Task;
     
    // routes/tasks.js
     
    import Ember from 'ember';
     
    export default Ember.Route.extend({
        model: function() {
            return this.store.find('task');
        }
    });
     
    // router.js
     
    import Ember from 'ember';
    import config from './config/environment';
     
    var Router = Ember.Router.extend({
      location: config.locationType
    });
     
    export default Router.map(function() {
      this.route('tasks');
    });
     
    // templates/tasks.hbs
     
    <ul>
        {{#each task in model}}
            <li>{{task.name}}</li>
        {{/each}}
    </ul>
     
    // app.js
     
    import Ember from 'ember';
    import DS from 'ember-data';
    import Resolver from 'ember/resolver';
    import loadInitializers from 'ember/load-initializers';
    import config from './config/environment';
     
    var App;
     
    Ember.MODEL_FACTORY_INJECTIONS = true;
     
    App = Ember.Application.extend({
      modulePrefix: config.modulePrefix,
      podModulePrefix: config.podModulePrefix,
      Resolver: Resolver
    });
     
    loadInitializers(App, config.modulePrefix);
     
    App.ApplicationAdapter = DS.FixtureAdapter;
     
    export default App;

For what it's worth, I think the documentation should be updated to use the ember-cli method (assuming that the current documented method can be made to work).

**Comment by rwjblue** [comment]
Yes, the guide should definitely be updated to use a more ember-cli focused narration.  This was done in https://github.com/emberjs/guides/pull/8 and should be deployed once the 1.12 guides are published.

Thanks for reporting!
