### ISSUE TITLE
Template/layout resolution docs

### ISSUE THREAD

**Issue by stavarotti** [emberjs/ember.js#11237]
The docs currently state that you can specify a different [layout/layoutName](http://emberjs.com/api/classes/Ember.Component.html#property_layout) however, specifying a different `layout` and/or `layoutName` seems to have no effect unless set within `init`.

Should the docs be updated or am I misunderstanding the usage?

**Comment by rwjblue** [comment]
Duplicate of https://github.com/emberjs/ember.js/issues/11186.

**Comment by stavarotti** [comment]
@rwjblue I saw that issue however, this does not work in 1.12.0
