### ISSUE TITLE
ember-source@1.13.0.beta.1 gem is not released yet

### ISSUE THREAD

**Issue by tricknotes** [emberjs/ember.js#11236]
It seems Ember.js [1.13.0-beta.1](https://github.com/emberjs/ember.js/tree/v1.13.0-beta.1) is released.
Could someone publish it to rubytgems.org ?

**Comment by rwjblue** [comment]
Ugh, this is turning into a habit for me; I need to update my release docs to properly do this.  Sorry for the troubles.

**Comment by tricknotes** [comment]
Confirmed https://rubygems.org/gems/ember-source/versions/1.13.0.beta.1
Thanks a lot :dizzy:
