### ISSUE TITLE
Documentation for @each and [] in computed properties?

### ISSUE THREAD

**Issue by topaxi** [emberjs/ember.js#11238]
Is there any documentation on `@each` and `[]` or any other special syntax other than dot notation (is there any?).

The following links to don't mention `@each` or `[]`
http://emberjs.com/api/classes/Ember.computed.html
http://guides.emberjs.com/v1.10.0/object-model/computed-properties/

The next one is especially for `@each` (just found out, never really looked through the guide, only API..)
http://guides.emberjs.com/v1.10.0/object-model/computed-properties-and-aggregate-data/

But still no `[]` in sight? Does it actually exist or is it some kind of private API?

**Comment by gordonkristan** [comment]
Yes. You can find the documentation for `@each` in the [Array documentation](http://emberjs.com/api/classes/Ember.Array.html#property__each) and the documentation for `[]` in the [Enumerable documentation](http://emberjs.com/api/classes/Ember.Enumerable.html#property__).
