### ISSUE TITLE
App.instanceInitializer receives undefined when App.reset()

### ISSUE THREAD

**Issue by hibariya** [emberjs/ember.js#11230]
JS Bin:

* [ember-1.12.0](http://emberjs.jsbin.com/radifi/2/edit?html,js,output)
* [canary](http://emberjs.jsbin.com/zicamo/1/edit?html,js,output)

On boot:
![selection_224](https://cloud.githubusercontent.com/assets/43346/7724607/eb48ada6-ff2d-11e4-8348-a83a74939442.png)

On reset:
![selection_225](https://cloud.githubusercontent.com/assets/43346/7724609/ef227696-ff2d-11e4-8910-27aac3ea637f.png)

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/11253
