### ISSUE TITLE
[Regression] Spaces inside the values of an attribute helper break.

### ISSUE THREAD

**Issue by martndemus** [emberjs/ember.js#11243]
```javascript
// helpers/add-margin.js
export default function() {
  return 'style="margin: 4px 8px"';
}
```

```html
<!-- templates/components/some-component.hbs -->
<div {{add-margin}}>X</div>
```

This would render as expected before 1.10, but it fails on the following loop in 1.10 up to 1.12:
[ember-htmlbars/lib/hooks/element.js#L28](https://github.com/emberjs/ember.js/blob/7fca048e0938be4ba29a8d5ceaaaff1b22776f75/packages/ember-htmlbars/lib/hooks/element.js#L28), because the string also gets split on the whitespace inside the value of the style attribute.

JSBin: http://emberjs.jsbin.com/cutivonoqu/2/edit
If you check the console you will see:
```
TypeError: undefined is not an object (evaluating 'attrValue.replace')
```

I verified that it is fixed in 1.13-beta.

**Comment by rwjblue** [comment]
Yeah, I reworked the way the attributes are calculated in a much saner way for 1.13.  I'll look into backporting that fix for 1.12, but at this point i doubt we can release another 1.10 or 1.11 with the fix...

**Comment by mixonic** [comment]
We must deprecate as well.

**Comment by rwjblue** [comment]
@mixonic - It is definitely deprecated already.

**Comment by rwjblue** [comment]
Was fixed by https://github.com/emberjs/ember.js/pull/11304.
