### ISSUE TITLE
[Glimmer] Angle-bracket components ignores tagName

### ISSUE THREAD

**Issue by Padchi** [emberjs/ember.js#11245]
Is this a bug or something that's deprecated?

**Comment by mixonic** [comment]
We're experimenting with making the tag name the `<tag-name`. More details will emerge shortly, I think they work is currently under way.

**Comment by Padchi** [comment]
@mixonic does that mean that I can in the future e.g. create a `<select` component?

    <select as |select submit|>
      <option select={{select}} on-select={{submit}} />
    </select>

**Comment by rwjblue** [comment]
We are very unlikely to allow overriding of a non-dashed element like in that example.

To the initial question: we intentionally do not support `tagName` for angle bracket components.  A bit more work is needed for some general use cases, but this is not currently a bug.  

Closing this issue for now, stay tuned for more updates :smile_cat:

**Comment by elucid** [comment]
Just to confirm, is there still a plan to allow creating components that render with alternate tag names? That is, the opt out mentioned in point 1. in https://github.com/emberjs/ember.js/pull/11141

**Comment by mixonic** [comment]
@elucid I expect we will still have an alternate tag name solution, yes. There will be discussion before we land anything.

**Comment by elucid** [comment]
*phew*

I'm not picky about the approach, just that this is eventually supported in some way. Not having the ability to override would be a HUGE limitation.

Thanks,
