### ISSUE TITLE
Deprecation Error when no Routes defined in 1.12

### ISSUE THREAD

**Issue by benedikt-d** [emberjs/ember.js#11248]
A deprecation warning is thrown when the the routes for a resource are not in the routes folder.

DEPRECATION: Using the same function as getter and setter is deprecated. See http://emberjs.com/deprecations/v1.x/#toc_computed-properties-with-a-shared-getter-and-setter for more details.

**Comment by rwjblue** [comment]
Will need a reproduction to be able to help here. The deprecation seems unrelated to the fact that a route is not present.

**Comment by benedikt-d** [comment]
You are right it is not related. I thought it was because the deprecation was gone for a short time somehow when I generated a new route. I'm just a beginner with ember so maybe this is just some stupid beginners mistake. https://github.com/benedikt-d/ember-calculator

**Comment by rwjblue** [comment]
After quick review, it doesn't seem like this deprecation is coming from your code.  It could be either the ember-inspector (issue was recently fixed there in https://github.com/emberjs/ember-inspector/pull/362), or some other addon that you might be using.

Regardless of the source it should have been clearer where this was coming from, https://github.com/emberjs/ember.js/issues/11048 was created to track fixing up that deprecation message.

I'm going to go ahead and close this for now then...
