### ISSUE TITLE
Expressions directly after HTML comment start are unbounded from the comments

### ISSUE THREAD

**Issue by petetnt** [emberjs/ember.js#11255]
Posted this in `ember-cli` but maybe this belongs more here (or in tildeio/htmlbars?)

Using the latest (0.2.5) Ember-CLI with ember-cli-htmlbars 0.7.4, any expression `{{ }}` starting directly from the HTML comment start `<!--` results to the expression being unbounded. Verified that this also happens anywhere else, so it isn't specific for those two.

For example,

``` html
  <!--{{input type="text" value="something">-->
```

Results in:

``` html
  <input type="text" value="something">
  <!---->
```

However, 

``` html
  <!-- Some comment here {{input type="text" value="something">-->
  <!--  {{input type="text" value="something"}} notice the space between - and { -->
```

results in:

``` html
  <!-- Some comment here <input type="text" value="something">-->  
  <!--  {{input type="text" value="something"}} notice the space between - and { -->
```

xref: ember-cli/ember-cli#4144

**Comment by mmun** [comment]
We should check if this is still an issue.

**Comment by petetnt** [comment]
@mmun Tried it ton `ember-twiddle` just now, still happens (on Ember 2.3.1):

https://ember-twiddle.com/2ce44197d934a47d2d73

```
DEBUG: Ember      : 2.3.1
DEBUG: Ember Data : 2.3.3
DEBUG: jQuery     : 1.11.3
DEBUG: -------------------------------
```

https://gist.github.com/petetnt/2ce44197d934a47d2d73

**Comment by petetnt** [comment]
Checked if this is still an issue with `2.9.0` and it is:

https://ember-twiddle.com/8e39462a29974c139be646c330a65d20?openFiles=controllers.application.js%2C

```
{
  "version": "0.10.6",
  "EmberENV": {
    "FEATURES": {}
  },
  "options": {
    "use_pods": false,
    "enable-testing": false
  },
  "dependencies": {
    "jquery": "https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.js",
    "ember": "2.9.0",
    "ember-data": "2.9.0",
    "ember-template-compiler": "2.9.0",
    "ember-testing": "2.9.0"
  },
  "addons": {}
}
```

**Comment by pixelhandler** [comment]
This is still an issue, https://ember-twiddle.com/e906b5ca35658c5657af4b308092a4de?openFiles=templates.application.hbs%2C as of v3.4.1

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still an issue on latest version? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by sandstrom** [comment]
Checked on 3.28.10.

It seems like this behavior still exist. Haven't tried on 4.x or 5.x though.

### Test 1

```hbs
HBS source

<!-- {{if true 'hello'}} -->
```

```html
Html output

<!-- {{if true 'hello'}} -->
```

### Test 2

```hbs
HBS source

<!--{{if true 'hello'}}-->
```

```html
Html output

hello
<!--{{if true 'hello'}}-->
```

***

Either way, this hasn't garnered much attention over the years, so likely isn't a big issue.

The reality is that this is an open-source project, and the time of core team members is very limited. We all want them to focus on moving the framework forward (high-leverage things).

I'll be closing this for now, to keep the list of open issues manageable. I hope you understand!

**Comment by petetnt** [comment]
🥲

**Comment by sandstrom** [comment]
@petetnt Sorry Pete, but there is a workaround. 

Also, happy to reopen if you want to PR a fix? (but if you do, it would likely be in another repo, e.g. the glimmer or starbeam repo, and I'd first check if this is still an issue on starbeam; upcoming rendering engine).

Congrats on NATO btw! At least one of us got in! 🇫🇮🇸🇪 

🙃

**Comment by petetnt** [comment]
It’s all good, I am fine with being in NATO even if the issue didn’t get fixed 😅
