### ISSUE TITLE
Add test to check for SemVer 2.0 validity of Ember.VERSION

### ISSUE THREAD

**Issue by truenorth** [emberjs/ember.js#11256]
The format of `Ember.VERSION` in the release channel (i.e., `1.12.0.94b8cb6c`) doesn't appear to be valid according SemVer 2.0.0.

A test like this should be added
```js
QUnit.test("Ember.VERSION is in alignment with SemVer v2.0.0", function () {
  ok(semver.valid(Ember.VERSION), 'Ember.VERSION is valid SemVer v2.0.0');
});
```

**Comment by rwjblue** [comment]
I believe that it should be `1.12.0+metadata-here`.  I dunno, I'll review the spec and see what needs to change.

**Comment by truenorth** [comment]
@rwjblue that's correct. I believe it's

`<major>.<minor>.<patch>-<prerelease>+<build>`

**Comment by rwjblue** [comment]
@truenorth - Can you double check me in https://github.com/cibernox/git-repo-version/pull/7?

**Comment by rwjblue** [comment]
OK, now we need to bump the git-repo-version version used in emberjs-build [here](https://github.com/emberjs/emberjs-build/blob/master/package.json#L57), then release and update emberjs-build dep in Ember [here](https://github.com/emberjs/ember.js/blob/master/package.json#L22).

**Comment by truenorth** [comment]
@rwjblue https://github.com/emberjs/emberjs-build/pull/99, and I'll open the second PR once we get a new version tagged

**Comment by truenorth** [comment]
This issue can be closed
