### ISSUE TITLE
[canary] unit tests for components with link-to fail

### ISSUE THREAD

**Issue by csantero** [emberjs/ember.js#11250]
Going from 1.12 to canary I found that components that use {{link-to}} fail their unit tests. The error occurs in `packages/ember-routing-views/lib/views/link.js` in `computeLinkViewHref` when it tries to generate the URL, but the `_routing` property is undefined.

I made a repo demonstrating the bug: https://github.com/csantero/link-to-error-demo

**Comment by rwjblue** [comment]
Duplicate of https://github.com/emberjs/ember.js/issues/11150.  Would you mind chiming in there with your repro?
