### ISSUE TITLE
Route vs Resource and the resetNamespace option

### ISSUE THREAD

**Issue by AhmadH** [emberjs/ember.js#11251]
Since 1.11.0, `this.resource` has been deprecated in favour of nested `this.route`. However, the difference in namespacing behaviour requires a large refactor involving moving route and template files and folders around and changing many references in `link-to` and `transitionTo` calls. In addition to requiring a refactor, it also breaks the analogy between the model tree and the route/template tree.

Passing `{ resetNamespace: true }` as an option to `this.route` results in the namespacing behaviour of a resource. This has been proposed as an easy way to remove the deprecated  `this.resource` usage from applications. (See [Erik Bryn's Ember 2.0 Talk] at 11:10 and this [StackOverflow Answer])

However, `resetNamespace` is not a documented public API and if I understand the code correctly, it is merely a flag for the router to differentiate between `this.route` and `this.resource`. Therefore, it would stand to reason that when `this.resource` is removed, `resetNamespace` will be removed with it.

An official statement regarding this may save the community a lot of unexpected grief as users follow the stability without stagnation plan.

[Erik Bryn's Ember 2.0 Talk]: https://www.youtube.com/watch?v=U1HEzVWseng
[StackOverflow Answer]: http://stackoverflow.com/questions/30301937/

**Comment by rwjblue** [comment]
> However, resetNamespace is not a documented public API and if I understand the code correctly, it is merely a flag for the router to differentiate between this.route and this.resource

Thanks for asking! I personally consider it a private API at the moment, but am not opposed to making it public if folks see a need for it longer term.  I am not sure that preventing a refactor to a nested layout justifies supporting both concepts long term (seems to me that the point of all deprecations is refactoring to a better pattern), but I definitely agree that we should formally decide so folks know what to do going forward.

**Comment by mixonic** [comment]
I am pretty strongly in favor of having a way to reset namespaces. A big app can get really gnarly without it (pods dirs 4 or 5 layers deep).

**Comment by mixonic** [comment]
An example: https://github.com/aptible/dashboard.aptible.com/blob/master/app/router.js#L13

I did not realize we currently have no public API for resetting namespace.

**Comment by rwjblue** [comment]
> I did not realize we currently have no public API for resetting namespace.

Technically, `this.resource` is not deprecated yet, and is still currently public API.  Though I think we would all agree that having both `this.route` and `this.resource` long term is not good.

**Comment by diogomafra** [comment]
I think this issue can be closed. The option `resetNamespace` is documented here: https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/router.js#L930

**Comment by rwjblue** [comment]
Thanks @diogomafra!

**Comment by tsmacdonald** [comment]
@diogomafra That's a dead link, the current version is [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/router.js#L1008-L1014). I do think that this should be documented somewhere more user-friendly than a source file, though. I expected to see it [in the Ember guide](https://guides.emberjs.com/v2.4.0/routing/defining-your-routes/), for example.

**Comment by marclundgren** [comment]
Linking to a blob like `master` will only be relevant for a short time.

Here: this points to a commit on master (today): https://github.com/emberjs/ember.js/blob/d3ceb22/packages/ember-routing/lib/system/router.js#L1168
