### ISSUE TITLE
1.13 Release Blog Post

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#11254]
This ticket is a summary of items to be discussed for the 1.13 release post. **Repo followers, please do not consider this a guarantee or even prediction of 1.13 behavior**. Just a place for notes.

This issue is locked to keep us focused. If you have commit bit please edit the description.

---
1.13:

* 

1.13 deprecations:

* 

---
2.0-beta:

* 

2.0-beta deprecations:

*

**Comment by stefanpenner** [comment]
we will need something for: https://github.com/emberjs/ember.js/pull/11213
