### ISSUE TITLE
[Angle Brackets] Co-exist with non-Ember web components and "x-foo" named elements

### ISSUE THREAD

**Issue by mike1o1** [emberjs/ember.js#11269]
I have a number of HTML elements in my Ember addon that follow the web component naming convention, but aren't actual web components or Ember. They just plain HTML elements, and are named that way to make the html and stylesheets more readable and semantic, but the elements have no functionality aside from that.

I'm running into a number of errors, because Ember throws an error that "x-foo" component isn't found.

Can Ember perhaps throw a warning when this happens, instead of throwing an error? Or can Ember fall back to just creating a regular html element or skipping them?

**Comment by rwjblue** [comment]
It should fall back for registered elements. Are the ones in question registered?

**Comment by mike1o1** [comment]
No, these are not registered with Ember as components. I was hoping to not have to create a number of "empty" Ember components with zero functionality.

**Comment by rwjblue** [comment]
This is definitely a thing we need to allow, but it will most likely be done via a whitelisting API.  We have disabled the angle bracket component invocation feature (in https://github.com/emberjs/ember.js/pull/11267), and a new RFC (https://github.com/emberjs/rfcs/pull/60) has been submitted to deal with many issues that were identified.

**Comment by krisselden** [comment]
@rwjblue it should bind() to registered components, it should fallback if there is no ember or no registered components.

I personally consider angle bracket tags blocked until they fallback, I don't think it is reasonable for ember to assume ownership of all of them, or error on a failed lookup (we could flag for a team discussion but I know that @wycats and @ebryn have told me in the past that fallback was a requirement). It is fine if we want to add a warning to lint typos that you can suppress with some declaration like /* global */ in js.

**Comment by krisselden** [comment]
Actually, I'm not sure if Model Driven Views is a web component thing, so ignore what I said about Node.bind()

**Comment by stefanpenner** [comment]
> Actually, I'm not sure if Model Driven Views is a web component thing anymore, so ignore what I said about Node.bind()

yes, I don't believe so.

**Comment by locks** [comment]
Given the current state of the union, namely https://github.com/emberjs/rfcs/pull/60#issuecomment-209960057, could this issue be closed?

**Comment by rwjblue** [comment]
Yes, closing for now. We will definitely have to readdress when we reintroduce angle bracket components.
