### ISSUE TITLE
Component block array iteration -- You modified XXX twice in a single render

### ISSUE THREAD

**Issue by Samsinite** [emberjs/ember.js#11277]
Hi Guys,

I have a set of calendar components that I've put together in an application that loop over sets of data and render the component block using values in those sets. Was hoping to see a really nice speed bump when updating to canary, but instead I am getting a `You modified XXX twice in a single render` warning along with the app crashing and locking my browser on a re-render.

It can be reproduced using the example app I've put together [here](https://github.com/Samsinite/example-issue) by clicking on the prev/next buttons. I would suggest opening the chrome inspector first before clicking a button as I have to force quit or pause the execution because it gets stuck in a loop spitting out warnings.

**Comment by Samsinite** [comment]
For what it is worth, this all works fine in Ember 1.12

**Comment by Samsinite** [comment]
Bump... Still an issue in canary and 1.13.0-beta.2

**Comment by sandstrom** [comment]
*This discussion may be helpful: https://github.com/emberjs/ember.js/issues/11156*

**Comment by Samsinite** [comment]
@sandstrom not really, a completely different issue. There is no elementId modification going on.

**Comment by Samsinite** [comment]
It says that [dayOfWeek](https://github.com/Samsinite/example-issue/blob/master/app/templates/components/calendar-month.hbs#L21) was modified twice in a single render. This worked fine on 1.12 and is a regression.

**Comment by Samsinite** [comment]
Looks like the issue goes away if I pass a POJO instead of null or a number.

**Comment by Samsinite** [comment]
Closing in favor of #11519 which has an attached JSBin as well.
