### ISSUE TITLE
render() regression in 'error' action v1.10.1 → ≥v1.11.0 

### ISSUE THREAD

**Issue by Soulou** [emberjs/ember.js#11282]
What I'm looking to do is to render custom errors without changing the URL path of the user, so using `this.transitionTo` is not an option.

So far the following method was working:

v1.10.1 - http://emberjs.jsbin.com/tezazakiye/1/edit

But since v1.11.0, there is no way to make it works

v.1.11.3 - http://emberjs.jsbin.com/rilenafaqe/1/edit

It seems to be related to #10884 and #11136 as the obtained error is: 

```
Error while processing route: stories.index Cannot read property 'push' of undefined TypeError: Cannot read property 'push' of undefined
```

If I well understood, it is normal, not being able to call `render()` from the `error` action now, but what is the good way to do it then?

Thank you very much.

**Comment by jcope2013** [comment]
same issue, ever find a solution?

**Comment by jcope2013** [comment]
how would i go about doing something like this, I want to render an error template but it errors out with ``` Cannot read property 'push' of undefined ``` and I get a white screen

```
ActiveModelAdapter.reopen({
    handleResponse(status, headers, payload) {
        if (this.isInvalid(status, headers, payload)) { // 422 check
            return new DS.InvalidError(payload.errors);
          }
          else if(status === 0)
          {
            var applicationRoute = this.container.lookup('route:application');
            applicationRoute.render('connectionError'); // Cannot read property 'push' of undefined
            return this._super.apply(this, arguments);
          }
       }
 });
```

**Comment by andrewjmc** [comment]
I'm heading away and unable to look in detail, but given that your problem fires what looks like an Ember Data error, I suspect this is unrelated to my own report.

**Comment by sammy007** [comment]
Tis is not ember data error. I have exactly the same issue without it. Can't render into outlet from action error. It seems we must look for a workaround or another framework with active developers, because if something floating since May it's unlikely gonna be fixed in future.

**Comment by locks** [comment]
I am closing this issue because I don't believe it is no longer relevant to current Ember versions.
Feel free to re-open the issue if you think it's still justified, thank you!
