### ISSUE TITLE
{{else}} blocks not rendered when {{#each}} block uses itemController

### ISSUE THREAD

**Issue by shawn42** [emberjs/ember.js#11284]
{{else}} blocks not rendered when {{#each}} block uses itemController

The {{else}} blocks rendered correctly in v1.11.3 but no longer renders in v1.13.0-beta.1
If I remove the itemController attribute, the {{else}} block starts rendering.

```html
<ul>
{{#each color in model itemController='thing'}}
  <li>{{color.label}}</li>
{{else}}
  <h2>no colors</h2>
{{/each}}
</ul>
```

```js
App.IndexRoute = Ember.Route.extend({
  model: function() {
    return [];//['red', 'yellow', 'blue'];
  }
});
App.ThingController = Ember.Controller.extend({
  label: function() {
    return this.get('model').slice(0,1);
  }.property('model')
});
```

I've attached a jsbin example:
http://emberjs.jsbin.com/ripoliwele/1/edit?html,js,output

I know components are the way to go here, but I want to at least make sure the issue is documented here for others.

**Comment by rwjblue** [comment]
> I know components are the way to go here

Agreed.

>  I want to at least make sure the issue is documented here for others.

This is absolutely a regression, and we definitely need to fix it.  Thank you for reporting (and for the reproduction)!

**Comment by rwjblue** [comment]
Seems to be working properly in current beta/canary builds:  http://emberjs.jsbin.com/firego/1.

We had a few PR's affect the legacy each view implementation (one was specifically related to `{{else}}` blocks), that fixed this.

**Comment by shawn42** [comment]
Great. I'll update to beta2 and try it out.
