### ISSUE TITLE
Mixin applied to Controller uses wrong `target`?

### ISSUE THREAD

**Issue by herom** [emberjs/ember.js#11287]
If I create a `Mixin` which I want to use in several `Controller`s, `Component`s, etc. I'd expect that any call to `this.send()` within the mixin is using the "right" `target` which would obviously be it's `route`, but it seems that always the main(?) route wins.

Is this expected behaviour, or is this a bug? Here is an [JSBIN example](http://emberjs.jsbin.com/heniqolijo/1/edit?html,js,console,output) demonstrating the issue (I hope).

Here's the console output:
```console
Error while processing route: foo.failing Nothing handled the action 'triggeredAction'. If you did handle the action, this error can be caused by returning true from an action handler in a controller, causing the action to bubble. Error: Nothing handled the action 'triggeredAction'. If you did handle the action, this error can be caused by returning true from an action handler in a controller, causing the action to bubble.
    at new Error (native)
    at Error.EmberError (http://builds.emberjs.com/tags/v1.11.3/ember.debug.js:12061:21)
    at Object.triggerEvent (http://builds.emberjs.com/tags/v1.11.3/ember.debug.js:24199:13)
    at trigger (http://builds.emberjs.com/tags/v1.11.3/ember.debug.js:46535:16)
    at Object.Router.trigger (http://builds.emberjs.com/tags/v1.11.3/ember.debug.js:45259:9)
    at EmberObject.default.extend.send (http://builds.emberjs.com/tags/v1.11.3/ember.debug.js:23682:27)
    at mixin.Mixin.create.send (http://builds.emberjs.com/tags/v1.11.3/ember.debug.js:27817:21)
    at null.didPullTrigger (http://null.jsbin.com/runner:29:11)
    at Object.applyStr (http://builds.emberjs.com/tags/v1.11.3/ember.debug.js:18110:27)
    at Object.sendEvent (http://builds.emberjs.com/tags/v1.11.3/ember.debug.js:12426:17)
```

**Comment by jmurphyau** [comment]
Looks like a timing issue.. You shouldn't be setting the property on `init` like you are.

If you change `on('init')` to `on('activate')` it works.

**Comment by herom** [comment]
@jmurphyau thanks a lot - when changing to `on('activate')` it's indeed not throwing an error anymore, but I also don't see any log output in the console(?)...

**Comment by herom** [comment]
Is there any resource explaining where I'm able to grab the `activate` hook? I can't find anything related to it within the docs... also, is it possible then to write a `Mixin` which is only used in controllers and make use of the `activate` hook?

**Comment by herom** [comment]
I updated the [JSBin example](http://emberjs.jsbin.com/motiqowaxe/2/edit) in order to fire `on('activate')`, now it seems that it gets never triggered at all?

**Comment by OrKoN** [comment]
@herom I believe the `activate` event is only available on routes http://emberjs.com/api/classes/Ember.Route.html#method_activate.

**Comment by jmurphyau** [comment]
So - question for you @herom.. When are you wanting to change this value/have this event fired? Do you want it to happen each time you enter the router? Do you want it to happen once when the controller is created (it's a singleton, so it will only be once during the app lifetime)? Or are you just using these events to demonstrate the issue?

If we can better understand when you want the behaviour to occur we might be able to find the right place.

There are a list of events in the [Ember.Route API docs](http://emberjs.com/api/classes/Ember.Route.html#event_activate) which give detail about when each event fires.. 

You can also log transitions [see doc](http://guides.emberjs.com/v1.10.0/routing/#toc_logging-route-changes) which log to the console the particular events and when they fire. There is also the options of LOG_TRANSITIONS_INTERNAL which gives even more detail (which hooks are called etc)

    App = Ember.Application.create({
      LOG_TRANSITIONS: true,
      LOG_TRANSITIONS_INTERNAL: true
    });

And finally, there is the setupController hook: [`setupController(controller, model)`](http://emberjs.com/api/classes/Ember.Route.html#method_setupController, transition). The transition param is not in the docs but it is in the source code. The basic functionality here is `controller.set('model', model)` - If you want to kick off some event or do some work on the controller right after the `model` property is set - you could play around in this function.

Again - not sure when you're trying to trigger the behaviour you're trying to trigger - but if you could shed some light on that I (or someone else) could suggest the best place to do what you're doing.

**Comment by jmurphyau** [comment]
So - question for you @herom.. When are you wanting to change this value/have this event fired? Do you want it to happen each time you enter the router? Do you want it to happen once when the controller is created (it's a singleton, so it will only be once during the app lifetime)? Or are you just using these events to demonstrate the issue?

If we can better understand when you want the behaviour to occur we might be able to find the right place.

There are a list of events in the [Ember.Route API docs](http://emberjs.com/api/classes/Ember.Route.html#event_activate) which give detail about when each event fires.. 

You can also log transitions [see doc](http://guides.emberjs.com/v1.10.0/routing/#toc_logging-route-changes) which log to the console the particular transitions between routes which might help. There is also the options of LOG_TRANSITIONS_INTERNAL which gives even more detail (which hooks are called etc)

    App = Ember.Application.create({
      LOG_TRANSITIONS: true,
      LOG_TRANSITIONS_INTERNAL: true
    });

And finally, there is the setupController hook: [`setupController(controller, model, transition)`](http://emberjs.com/api/classes/Ember.Route.html#method_setupController). The transition param is not in the docs but it is in the source code. The basic functionality here is `controller.set('model', model)` - If you want to kick off some event or do some work on the controller right after the `model` property is set - you could play around in this function.

Again - not sure when you're trying to trigger the behaviour you're trying to trigger - but if you could shed some light on that I (or someone else) could suggest the best place to do what you're doing.

**Comment by herom** [comment]
@jmurphyau thanks a lot for the follow up, I appreciate it a lot!

I happen to have a `controller` which is feeding several `components`. One of the components needs more than one "model" in order to show the relevant data output but the second model needs the first model in order to ask the backend for the accompanied data. Also, the user can change the current date to have data shown for a specific date (like a forecast). In order to show the user the most recent data of the current day, I have to set the date programmatically when the user enters the route.

I use `route#setupController` for most of the tasks to setup the controller (as it's name indicates :) ) and the `controller#init` for specific initialization as I want to move this into a `Mixin` and have a `setup` method which gets invoked once the `init` hook was fired so I can easily overwrite it without having to call `this._super`.

The "trigger" is pulled from several `observers` which are defined in the controller (e.g. the current date, etc.) - so, I never fire something directly on `init` the code in the JSBin was just to get something simle fiddled together to show my issue.

In the meanwhile I tend to believe that this issue has nothing to do with the `Mixin` itself as the same issue also comes up if I create a "proto" controller to extend from --> the `target` is the main router...

I'm afraid I can't tell more of the application as it's confidential and not open source.

**Comment by jmurphyau** [comment]
I think your issue might be the fact you're relying on the controllers `init`.. Controllers are singletons.. At a guess, the controller is initialised before its route is associated, meaning it can't get send events where you want.. Also, `init` will only ever happen once - likely the first time your user goes the page that uses that particular controller.. Every other time they navigate back to the same page you will notice there shouldn't be any more `init`s firing

**Comment by herom** [comment]
I'm not relying on the `init` to fire anything. I just use the `init` for setting things up which are only used in the particular controller - nothing is triggered in there. I'm sorry if I can't express myself clearly enough as I'm no english native I really lack of expressions... :(

On further investigation I don't think it has to do with the `init` as it's also failing if I explicitly set the controller's target to `this` (the route in question) in `route#setupController` which could be like 'publisher.book.author' (for example). 

If I now call `this.send('change')` in my controller the target is indeed the previously set `route` ('publisher.book.author'), **but** the first route which is going to be looked up for the action is not 'publisher.book.author' as one would expect, but 'publisher.book' which obviously can't provide the desired `action`. So, the routes which are looked up for the action are `application`, `publisher`, `publisher.book` (in reverse order), but the action is declared in `publisher.book.author` which gets checked... this is really strange...

**Comment by jmurphyau** [comment]
Ok.. To me it just sounded like that might be it but it's obviously not `init`.. Can you create a JSBin that reproduces the issue?

**Comment by herom** [comment]
I'll try my best to come up with a JSBin - could be that I need a few days to isolate it as I have several calls to the backend for data in order to get it running. Thanks a lot for your time & patience @jmurphyau you rule! :+1:

**Comment by acorncom** [comment]
@herom Is this still an issue for you or can we close this?

**Comment by herom** [comment]
sorry, I completely forgot about this issue. I solved my issue ever since, so I'll close it right away.
