### ISSUE TITLE
Ember.RSVP.hash in model hook does not return entire model if one part is loaded

### ISSUE THREAD

**Issue by typeoneerror** [emberjs/ember.js#11283]
I'm not sure if this is expected behavior with `hash`, but this has been perplexing me for some time. I've set up a jsbin here for explanation: http://emberjs.jsbin.com/nazagadere/1

You'll note that if you hit the main link, the colors are loaded via the route, and then the model returned in the ColorRoute (if you click on one of the color links) has only a "Color" object, whereas if you navigate directly to the child route, both keys of the hash are returned correctly: http://emberjs.jsbin.com/nazagadere/1#/color/1

Check the logs for the result of `model` in `setupController`.

I think I'm either totally not getting how the relationship with model and setupController works or something is up. It seems like if the "color" is already in the store, that the hash ingores the "things" promise and just returns the "color"? I'm confused and if this is expected behavior, how do I get the `model` to be consistent across transitions?

Thanks to anyone investigating.

**Comment by typeoneerror** [comment]
![screen shot 2015-05-26 at 12 57 12 pm](https://cloud.githubusercontent.com/assets/218700/7822046/c058b7ac-03a7-11e5-80da-4168a6e6b142.png)

Hmm, this makes it somewhat more clear that in this case I should always pass in an ID instead of the model loaded in the store. I think I foolishly assumed that the model hook would get called at least once if this was the first time entering that route.

**Comment by stefanpenner** [comment]
I don't believe this has anything to do with `RSVP.hash` rather, if you pass a model to link-to, you are *confusingly* telling ember, that you are providing "the model" and it does not need to call `model`.

I don't want to speak to soon, but there is general consensus that this wasn't such a great idea. I suspect, as we move to routable components, we will adjust the `route` api to amend this.

**Comment by typeoneerror** [comment]
@stefanpenner appreciate you giving it your time/thoughts. I agree that this is somewhat confusing. It's noted in different ways in the documentation, but, agree, feels like the route api could be more prescriptive here, especially w/regards to the link-to helper, maybe something like:

  {{#link-to 'color' color.id}}
  {{#link-to 'color color}}

both invoke model hook, whereas

  {{#link-to 'color model=color}}

would be you explicitly telling ember you want to override (or something).

**Comment by stefanpenner** [comment]
> would be you explicitly telling ember you want to override (or something).

ya something like that. Although, I suspect if you want to be `smart` doing it in the route is better then in the template.

**Comment by stefanpenner** [comment]
I don't believe this is actually an issue, although maybe some of the docs can be improved. Given you new-found understanding, do you have some doc improvement ideas?

**Comment by typeoneerror** [comment]
yeah, I'll submit a docs PR on Friday. usually my day to contribute.

**Comment by stefanpenner** [comment]
sounds good, should we close this issue?

**Comment by typeoneerror** [comment]
Yep.
