### ISSUE TITLE
`{{#unless}}` with array-like-object causes problem

### ISSUE THREAD

**Issue by hibariya** [emberjs/ember.js#11297]
I'm facing an unexpected behavior of `unless` helper.
`{{#unless arrayLikeObject}}` doesn't update when `arrayLikeObject` was updated from empty array. 

* [1.12.0](http://emberjs.jsbin.com/tutaju/4/edit)
* [canary](http://emberjs.jsbin.com/misope/2/edit) (broken)

I think [this patch](https://github.com/emberjs/ember.js/compare/master...hibariya:fix-unless-helper) fixes it.

**Comment by hibariya** [comment]
I fixed syntax warnings of reproduce codes.

**Comment by rwjblue** [comment]
The patch looks great!  Can you prefix the commit message with `[BUGFIX beta]`, and submit the PR?

**Comment by hibariya** [comment]
Thanks! I'll change the commit message and submit the PR.
