### ISSUE TITLE
Morph error: "unsupported content" on single binding

### ISSUE THREAD

**Issue by thehydroimpulse** [emberjs/ember.js#11296]
After upgrading from Ember 1.11 to 1.12, a single route in my app is throwing an error from the Morph class.

Here's the stack trace:

![screenshot 2015-05-27 20 14 57](https://cloud.githubusercontent.com/assets/565790/7852201/fed16eba-04b6-11e5-8f03-e9485188218c.png)

After tracking down the single route, it comes down to a single component and a single binding: `{{name}}` that triggers the error. `name` is just a property on the component, defaulting to 'Month'.

Any thoughts?

**Comment by rwjblue** [comment]
Can you share a few more details about your setup?  Things that *might* be important are:

* the component's `tagName`
* `attributeBindings` on the component (and any supporting CP's for those attributeBindings)
* the `name` value you are supplying

My completely naive guess: you are setting an attribute on the components element for `name` with an invalid value.

**Comment by thehydroimpulse** [comment]
Tag is just a div. The value of the name binding is either Month or Day.
The component is super bare, only has an observer and some actions.

Changing the binding to 'namea' fixed the error.

**Comment by rwjblue** [comment]
JSBin without `attributeBinding` for `name`: http://emberjs.jsbin.com/rwjblue/557/edit
JSBin with `attributeBinding` for `name`: http://emberjs.jsbin.com/rwjblue/558/edit

Neither of the JSBin's above trigger any errors, can you tweak them to simulate your scenario a bit more and hopefully we can get to the bottom of it...

**Comment by thehydroimpulse** [comment]
@rwjblue http://emberjs.jsbin.com/bokijacodi/1/

That matches my component. However, it's using ember canary in the jsbin, so that might affect things. I'll try upgrading ember to canary and see if the error persists.

**Comment by rwjblue** [comment]
I'm going to close for now, I'm happy to reopen when you can repro...

**Comment by michaeljonathan** [comment]
Hey I just encountered the exact same exception. I tried recreating what I did on jsbin and it won't render either, did I do a mistake somewhere?

Thanks for the help!

http://emberjs.jsbin.com/rakuxikeci/1
