### ISSUE TITLE
[1.13.beta-2 Regression] services can no longer extend Ember.Object

### ISSUE THREAD

**Issue by jakehow** [emberjs/ember.js#11292]
Our app has a session service defined in `app/services/session.js` by extending `Ember.Object`.

Our suite passes on v1.13.0-beta.1.

v1.13.0-beta.2 introduced a change that breaks this.  We see the following error in our test suite: `Assertion Failed: Expected service:session to resolve to an Ember.Service but instead it was (unknown mixin).`

While breaking, fixing this in app is a trivial change to extending from `Ember.Service` instead.

**Comment by pixelhandler** [comment]
@jakehow It makes sense to just use Ember.Service going forward. Essential its an Ember.Object with a class property `isServiceFactory: true`, see https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/system/service.js#L40-L46 and https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/system/object.js#L19-L24

**Comment by stefanpenner** [comment]
I believe this is a regression, I actually left a comment on the PR that introduced this.

**Comment by stefanpenner** [comment]
note: https://github.com/emberjs/ember.js/pull/11261#issuecomment-105604199

**Comment by rwjblue** [comment]
This was changed into a deprecation in #11273, which is included in the latest beta builds.  I am going to close now, but will happily reopen if it is still an issue with current beta or canary builds.

**Comment by jakehow** [comment]
:+1: working for me on master

**Comment by stefanpenner** [comment]
@jakehow whoop, thanks for confirming.
