### ISSUE TITLE
[Glimmer] - Assertion from {{link-to}} using when ember data is saving a record

### ISSUE THREAD

**Issue by raytiley** [emberjs/ember.js#11302]
Sorry for not having a jsbin for this one. I'm not so great and reproducing issues that involve ember data.

I have a model with a `belongsTo` relationship like so:

```js
App.Book = DS.Model.extend({
  author: DS.belongsTo('author')
});

App.Author = DS.Model.extend();
```

Then in my app I have a list of books. This list have buttons that will do an action that will modify and save the book. Each item in the list also has a link to its author. Something like this

```handlebars
{{#each books as |book|}}
  <tr>
    <td>{{book.name}}</td>
    <td>{{link-to book.author.name 'author' book.author.id}}</td>
    <td><button {{action 'updateBookModel'}}>This will call save() on book</button></td>
  </tr>
{{/each}}
```

When the action happens I'm guessing the book model goes into the loading state which throws the following assertion. Note in my app these actions also cause a render because the properties being changed cause the items to move around.

```
You modified (-join-classes "ember-view" (-normalize-class "active" view.active activeClass=undefined inactiveClass=undefined) (-normalize-class "loading" view.loading activeClass=undefined inactiveClass=undefined) (-normalize-class "disabled" view.disabled activeClass=undefined inactiveClass=undefined) (-normalize-class "transitioningIn" view.transitioningIn activeClass=undefined inactiveClass=undefined) (-normalize-class "transitioningOut" view.transitioningOut activeClass=undefined inactiveClass=undefined)) twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0
```

As far as I can tell I'm not doing anything special in my app that I can prevent this.

**Comment by OlaviSau** [comment]
https://github.com/emberjs/ember.js/issues/11156
Have a look at this :)

**Comment by raytiley** [comment]
@OlaviSau while the deprecation is similar I don't think the underlying issue is the same. I'm not setting a property of the `link-to` view besides passing in the parameter through the relationship. 

It seems to me this might be an ember data issue... since saving the record should happen in the `data` queue of the run loop so not sure why its changing a property during render. 

Ether way I think this needs to be addressed in ember / ember-data since linking to a related record / saving records is a normal behavor and shouldn't throw deprecations from framework code.

@igorT Any thoughts on this?

**Comment by raytiley** [comment]
This issue seems to be resolved in `canary`.
