### ISSUE TITLE
ember-radio-button addon not working with 1.13 betas (includes jsbins)

### ISSUE THREAD

**Issue by raycohen** [emberjs/ember.js#11301]
this came up trying to get the [ember-radio-button](https://github.com/yapplabs/ember-radio-button) addon working with the ember 1.13 betas.

I am [using](https://github.com/yapplabs/ember-radio-button/blob/master/addon/components/radio-button.js#L16) `if (this.get('template'))`  to detect if the component is being used with a block.  This is no longer working.

Some jsbins that help demonstrate the behavior change:

working in ember 1.12:
http://emberjs.jsbin.com/zihixaqaxo/2/edit?html,css,js,output

not working in beta:
http://emberjs.jsbin.com/zihixaqaxo/3/edit?html,css,js,output

**Comment by OrKoN** [comment]
@raycohen I think you should use `hasBlock` to check if there is a block http://emberjs.com/api/classes/Ember.Component.html#property_hasBlock 

`template` seems to be deprecated. http://emberjs.com/api/classes/Ember.Component.html#property_template

**Comment by raycohen** [comment]
@OrKoN `hasBlock` is not working for me either.  Substituting it for `template` in my jsbins has no effect

**Comment by OrKoN** [comment]
@raycohen I have only used it in the template like this: http://emberjs.jsbin.com/kixiteqiba/1/edit?html,css,js,output 

It looks like it's only available within templates...

**Comment by rwjblue** [comment]
you cannot use `hasBlock` in JS code. It is available only in template-land.

**Comment by raycohen** [comment]
ok.  so there's no way to do what I was doing in 1.12 in 1.13+?

**Comment by rwjblue** [comment]
In general, I think I would advise using the `hasBlock` helper to render one or the other component that you ultimately intend to render via the template instead of changing the `layout`/`attributeBindings` on demand.

**Comment by rwjblue** [comment]
However, I definitely consider it a regression that `if (this.get('template'))` used to work to detect if your component was invoked in block form and now it doesn't.  I trying to work out a fix with deprecation for that...

**Comment by rwjblue** [comment]
Also related to https://github.com/emberjs/ember.js/issues/11186.

**Comment by rwjblue** [comment]
I submitted https://github.com/emberjs/ember.js/issues/11313 to allow usage of `this.get('template')` to determine if a block was provided, and https://github.com/emberjs/ember.js/issues/11186 as a failing test for rerendering when `layout` changes.

**Comment by SirZach** [comment]
as of 13-beta.1, the actual implementation for <code>hasBlock</code> has been removed. The docs are still there but the property definition is gone. https://github.com/emberjs/ember.js/blob/v1.13.0-beta.2/packages/ember-views/lib/views/component.js do a find for <code>hasBlock:</code> and you'll see it's gone.

**Comment by mmun** [comment]
@SirZach It's implemented. See https://github.com/emberjs/ember.js/blob/6dba87afb90f836c5040d9dbece88572818889a8/packages/ember-htmlbars/lib/hooks/get-root.js#L13-L14.

**Comment by SirZach** [comment]
@mmun https://github.com/emberjs/ember.js/blob/v1.12.1/packages/ember-views/lib/views/component.js it's implemented in the class there. Nice find and thanks. With the newer implementation approach, is there any way to get a hold of <code>hasBlock</code> in the component's JS code?

**Comment by mmun** [comment]
@SirZach Oops, you're right. There isn't a way to get it _right now_. And I'm fairly convinced you shouldn't need this. Can your use case be accomplished within the template? If not, can you explain it? It would be helpful for me.

**Comment by SirZach** [comment]
My use case is for backwards compatibility. In pre 13, I could check for <code>template</code> to know if the component was being used in block form. In 13 and later, I have to use hasBlock. In order to have components that could work in block form with glimmer and non-glimmer apps, I was going to have a computed property on the component that would check these two properties.

**Comment by mmun** [comment]
@SirZach Yeah. We're planning on making `template` a boolean so that it's mostly backwards compatible with how people were using it. It is definitely a semver violation to break that. But in terms of adding a new API to the Component JS, `hasBlock`, I'm not convinced we need to.

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/11313 makes `template` a boolean, and is pending review.

**Comment by SirZach** [comment]
Thanks @rwjblue ! Sorry I realize now that's what you were talking about in this thread. Thanks @mmun for the quick replies!

**Comment by btecu** [comment]
I think this can be closed.
