### ISSUE TITLE
findWithAssert can't be used alone, or is poorly named

### ISSUE THREAD

**Issue by bcardarella** [emberjs/ember.js#11312]
The name `findWithAssert` implies an actual assertion is being run. In reality it is just calling `throw` if no match is found. Assume the following test:

```js
test('find foo', function(assert) {
   visit('/');
  andThen(function() {
    findWithAssert('.foo');
  });
})
```

If `.foo` is found the test actually fails because `assert.expect(0)` is necessary as no actual call on the `assert` object was made. This is confusing. I believe the method name should be changed or the `assert` object should be passed in as an argument. If the element is found call `assert.ok(true)` or something to that effect.

**Comment by OlaviSau** [comment]
Are you suggesting that you pass a custom assert?
The current code essentially does assert with a hardcoded param($el.length !== 0) and a hardcoded assert description aswell.
```javascript
//old
function findWithAssert(app, selector, context) {
  var $el = app.testHelpers.find(selector, context);
  if ($el.length === 0) {
    throw new EmberError("Element " + selector + " not found.");
  }
  return $el;
}
//I assume the solution could be to set the previous test to default with the previous one and add optional parameters for the custom assert?like this:
function findWithAssert(app, selector, context, desc, test) {
  var $el = app.testHelpers.find(selector, context);
  var desc = desc || "Element " + selector + " not found.";
  var test = test || element !== 0;
  Ember.assert(desc,test);
  return $el;
}


```

**Comment by bcardarella** [comment]
The current code does an `Ember.assert` which is misleading within the context of a test suite.

**Comment by rwjblue** [comment]
A few random thoughts:

* `Ember.assert` is roughly `throw new Error('....')`.
* When `findWithAssert` was created, QUnit terminology did not include `assert` (the suggested assert callback function argument was not added until a bit later).
* We do an `Ember.assert` so the name `findWithAssert` does technically do a "find" with an "assert" (even though now it seems silly).
* `findWithAssert` was mostly created as a private internal helper for other things that should error if an element was not found (like `click`, `fillIn`, `tiggerEvent`, etc).  It really was not meant to be used standalone as you mention in the intro description.

**Comment by OlaviSau** [comment]
NB: I'm new, so I went a bit offpath, didn't realize you were reffering to QUnit,, thank you :)
@rwjblue First off thanks a lot for the input.I kinda had some of the same thoughts, its good to know that I'm not completely off.
Secondly, do you think there is any point in changing it?
@bcardarella 
Is that what you meant?
(check edits)

**Comment by locks** [comment]
@rwjblue how does your recent RFC affect this?

**Comment by toddjordan** [comment]
Given `findWithAssert` is meant to be private, should we close?

**Comment by rwjblue** [comment]
Yeah, I'll close this issue, but it should be addressed in the testing RFC.
