### ISSUE TITLE
[Addons] make _registerHelper public

### ISSUE THREAD

**Issue by bcardarella** [emberjs/ember.js#11311]
I am using `_registerHelper` in several addons to get around the hyphenation requirement. can we get we get this method to be made public?

**Comment by mmun** [comment]
@bcardarella We're not going to expose that method because it exposes streams. @mixonic and @rwjblue have an RFC detailing the path to hyphenless helpers: https://github.com/emberjs/rfcs/pull/58.

**Comment by bcardarella** [comment]
@mmun what are the odds that this RFC is going to land for 2.0? Without a clear path on how my addons will work in 2.0 I'm pretty much stuck. Its nice that there is an RFC to add a better API for this eventually but in the meantime I don't think I can update my addons and test them against 1.13 in any way

**Comment by rwjblue** [comment]
@bcardarella we are planning on  to landing both https://github.com/emberjs/rfcs/pull/53 and https://github.com/emberjs/rfcs/pull/58 in 1.13.0.

**Comment by bcardarella** [comment]
this is good news, thank you

**Comment by tim-evans** [comment]
I find this very strange having versions of my addon that only work with subsets of ember versions. (ie. the most recent release of ember-document-title only works up to 1.12.0, and breaks on 1.13)

**Comment by samtsai** [comment]
@bcardarella looks like we can try confirming that your addons work with the helper updates that landed in 1.13 and close this issue out if all good.

**Comment by mmun** [comment]
Thanks @samtsai.
