### ISSUE TITLE
Can't look up template named "main"

### ISSUE THREAD

**Issue by aroberts** [emberjs/ember.js#11319]
I'm in the process of upgrading from 1.9 to 1.12.1, and I ran into some trouble.  

We have a top-level route called "main" that we use to wrap everything except for some user onboarding, which has a different look, and so doesn't want to share a layout-level template with the rest of the application.

In ember 1.12, my "main" template is skipped, and I see this console message:

```Could not find "main" template or view. Nothing will be rendered Object {fullName: "template:main"}```

In some standalone tests, renaming the template (and associated route, etc) to 'mai**m**' solved the issue. Here are some jsbins further illustrating the problem:

http://emberjs.jsbin.com/bixaqapiqi/3/edit?html,css,js,output - template called `main`
http://emberjs.jsbin.com/defavidewe/1/edit?html,css,js,output - template called `maim`

**Comment by mitchlloyd** [comment]
No fix in mind, but just so you know *why* this is happening: the Ember Resolver uses "main" as an indicator that it should lookup the base class of something. So resolver.resolve('controller:main') will lookup App.Controller.

https://github.com/emberjs/ember.js/blob/0d513645ba6eba7a783de3668b531eebc78dc141/packages/ember-application/tests/system/dependency_injection/default_resolver_test.js#L82

Templates don't use classes, so this could probably be fixed for the template case. However, I'm not sure how this is working for your Route. Are you sure you're actually loading that route and not the base Route class? I'm thinking that you probably can't have a "main" anything.

It looks like this behavior was added in this commit:
https://github.com/emberjs/ember.js/commit/0320b5a78142dee16b6c2c92c0c37bb295ae86ec

**Comment by stefanpenner** [comment]
yes, main has special meaning. (for better or worse)

**Comment by locks** [comment]
@stefanpenner is this a `wontfix`?

**Comment by locks** [comment]
I am closing this as a likely `wontfix`, mostly due to the fact that it seems to be a 1.x branch problem. Thanks everyone, let me know if it needs to be re-opened.
