### ISSUE TITLE
Ember + Chai expect = unusable

### ISSUE THREAD

**Issue by bjornstar** [emberjs/ember.js#11327]
We had some very simple unit tests timing out. A little investigation found that ember has some **very** bad interactions with chai.

``` javascript
console.time('expect');
for (var i = 0; i < 1000; i += 1) {
  expect(model).to.be.ok;
}
console.timeEnd('expect');
// expect: 5131.547ms

console.time('assert');
for (var i = 0; i < 1000; i += 1) {
  assert.ok(model);
}
console.timeEnd('assert');
// assert: 13.321ms
```

Has anyone else experienced something like this?

**Comment by stefanpenner** [comment]
Seems like an issue with chai. No reason assert(model) should be slow. I could see deepEqual being slow, due to complex structures

**Comment by bjornstar** [comment]
React uses chai and they don't seem to have any problems.

**Comment by stefanpenner** [comment]
Different object structures. But clearly something is wrong with chai is it can't do !!model quickly.


This is likely due to meta being enumerable, because browsers fail to make them quick. Let me grab my laptop to confirm.

**Comment by stefanpenner** [comment]
interestingly, my attempt to reproduce was not successful: http://emberjs.jsbin.com/libapuxopo/5/edit

100,000 iterations, ok: 48ms chai 102ms.

**Comment by bjornstar** [comment]
When I run that, I get a big warning in the console when I click on the chai run button:

`Exiting potential infinite loop at line 21. To disable loop protection: add "// noprotect" to your code`

I do not get that error when I click the ok button.

**Comment by stefanpenner** [comment]
Yup I get that as well, simply add `// noprotect` to the top. Results end up being the same.

**Comment by bjornstar** [comment]
![screenshot from 2015-06-03 14 41 40](https://cloud.githubusercontent.com/assets/20630/7953365/cdc2e644-09fe-11e5-8dbb-6bd2ef4854ca.png)

Adding `// no protect` at the top makes ember inside of chai an order of magnitude slower than ok.

ok: 2ms chai: 103ms

**Comment by stefanpenner** [comment]
@bjornstar yes, but chai is legitimately slower. If you replace `var foo = this.store.createRecord('foo')` with `var foo = new Object();` the times stay exactly the same.

**Comment by stefanpenner** [comment]
> As mentioned above, I suspect if your have timeouts, they are due to deepEquals of some sort, or something that generates a diff. But that does not appear to be what you snippet displays.

^^^^

**Comment by stefanpenner** [comment]
this seems to have gone stale
