### ISSUE TITLE
Unable to override model hook in error substate route

### ISSUE THREAD

**Issue by f3ndot** [emberjs/ember.js#11321]
Minimal example (using 1.12.0, also tested on 1.11.3): http://jsbin.com/mibeno/2/edit?html,js,console,output

I'm unable to override the `model` hook in `ErrorRoute`: the model is `null` in `setupController` and any reference to `this.get('model')` in the `ErrorController` is also null.

I can understand from a design perspective that maybe Ember shouldn't allow the `model` hook to be overridden on the `error` substate, but if that's the case we should have an assertion to point devs in the right direction. It took me a while to figure out the `model` hook wasn't being respected.

**Comment by f3ndot** [comment]
Potentially adding a sentence to the guides clarifying that you can't override the model hook on sub-states would also be beneficial.

**Comment by pixelhandler** [comment]
@f3ndot I added an ember-twiddle example in the current release of Ember https://ember-twiddle.com/3efd6e75cec2f79a688ae04e12c1af88?openFiles=routes.error.js%2C

**Comment by pixelhandler** [comment]
@locks Perhaps we just need to add to the docs at https://guides.emberjs.com/v2.5.0/routing/loading-and-error-substates/ that the model hooks of an error substate are NOT callled only the `setupController` method is called (since the model is already resolved as an error object). 

```js
setupController: function(controller, error) {
  Ember.Logger.debug(error.message);
  this._super(controller, error);
}
```

**Comment by pixelhandler** [comment]
@f3ndot looks like this issue can be moved over to the https://github.com/emberjs/guides repo

**Comment by pixelhandler** [comment]
@f3ndot @locks closing this one in favor of an issue in the guides repo: https://github.com/emberjs/guides/issues/1500 thanks @claubacher
