### ISSUE TITLE
TextFieldComponent Resolver Issue

### ISSUE THREAD

**Issue by rwwagner90** [emberjs/ember.js#11326]
We use the default globals resolver in our app, and we have an issue when trying to use the `{{input}}` helper in our app. We just upgraded to 1.13, and apparently, the default component name is now `-text-field`, which resolves to the `TextFieldComponent` that we defined ourselves in our app. I spoke with @rwjblue about this on slack, and we agreed it is a bug that should be looked at.

https://github.com/emberjs/ember.js/blob/bfcc15ee3ac2b2b3e4dad6aa0d7a447936302f5a/packages/ember-htmlbars/lib/keywords/input.js#L24

**Comment by rwjblue** [comment]
Thanks for reporting.  I'll try to look into it tonight....

**Comment by rwjblue** [comment]
The global resolver will resolve `component:-text-field` to `App.TextFieldComponent`, which in this case is conflicting with another component that you have.

Demo JSBin: http://emberjs.jsbin.com/rwjblue/573/edit

**Comment by rwwagner90** [comment]
Right, but how do we remedy this? Could we perhaps make the default component name something more specific, to reduce the likelihood that other people run into this?

**Comment by rwjblue** [comment]
The globals resolver should be looking for `App._TextFieldComponent` which would not conflict, I was explaining what was happening above (not saying y'all were doing something wrong).  Definitely a bug we need to fix.

**Comment by rwwagner90** [comment]
:+1:

**Comment by rwwagner90** [comment]
Any luck with this? I'd like to try to update to 1.13.0, but I still can't because none of our {{input}} work.

**Comment by rwwagner90** [comment]
If this isn't going to be fixed, please let me know, so we can move on and change our code to work with the broken resolver.

**Comment by rwwagner90** [comment]
Been a couple months now. Any progress on this? If it's an issue that will not be fixed, I would very much like to know, so we can proceed accordingly. This is one of the major hurdles we have updating to Ember 2.0.

**Comment by mixonic** [comment]
@rwwagner90 it doesn't look like anyone has had the time to prioritize this yet.

**Comment by rwwagner90** [comment]
@mixonic yeah, I understand there are higher priorities for you guys, but if the intention is never to fix this, that's fine too, I'm just stuck in limbo not knowing now. I'd like a definite, "we will eventually fix this" or a definite "you're the only one this effects and we're never going to fix this, just rework your naming of components so this conflict does not occur". Could someone answer that please?

**Comment by rwjblue** [comment]
Quoting from https://github.com/emberjs/ember.js/issues/11326#issuecomment-108432189:

> Definitely a bug we need to fix.

**Comment by rwwagner90** [comment]
Woo @skeate ! :smile:
