### ISSUE TITLE
v1.13.0-beta.2 - Uncaught Error: Assertion Failed: Expected component:chosen-select to resolve to an Ember.Component but instead it was (subclass of Ember.Select).

### ISSUE THREAD

**Issue by ChrisHonniball** [emberjs/ember.js#11324]
I'm getting:

```
Uncaught Error: Assertion Failed: Expected component:chosen-select to resolve to an Ember.Component but instead it was (subclass of Ember.Select).
```

I had the same error when extending the default Ember.View which was not a big deal because I just made it a Ember.Component and updated a few lines of code but what about if I want to extend Ember.Select or other built in components (i.e., Ember.TextArea). What is the right technique after 1.13.0? Thanks for the help!

**Comment by rwjblue** [comment]
This assertion has been changed to a deprecation, and will be updated in 1.13.0-beta.3 soonish.

You can use the latest from the beta channel for now.

**Comment by ChrisHonniball** [comment]
Since it's a deprecation is there a new method for extending existing components?

**Comment by rwjblue** [comment]
Extending from something that is an `Ember.Component` is totally fine, and doesn't have an issue.  If you are extending from `Ember.Select` though, it is an `Ember.View` (not a component at all) which is what triggers the deprecation.

**Comment by ChrisHonniball** [comment]
I see.

If I wanted to extend these controls am I still able to? I could just wrap them inside a component and do my necessary work on the wrapped elements if this isn't going to be something I have access to.

**Comment by rwjblue** [comment]
The change was made in https://github.com/emberjs/ember.js/pull/11261 and tweaked in https://github.com/emberjs/ember.js/pull/11300.  All you should need to do is:

```
var CustomSelect = Ember.Select.extend();

CustomSelect.reopenClass({
  isComponentFactory: true
});

export default CustomSelect;
```

To get rid of the deprecation.

**Comment by ChrisHonniball** [comment]
Good to go! As always, I seriously appreciate it! :beers:
