### ISSUE TITLE
Deprecate `{{each}}` without a key specified.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#11337]
The default key of `index` is confusing.  We should deprecate usage of keyless `{{each}}`.

**Comment by jayphelps** [comment]
A good number of each's in the various apps I've worked on do not have any stable unique prop to key to. It's quite a pain to have to decorate each item with a key. Can this be helped in some other way? What about auto-generating `Ember.guidFor` per item, perhaps stored in Ember.meta(arr)?

In testing canary with one of our apps, we noticed some incorrect dom-reuse when the array changed. (more info on that as we discover the cause, we'll create a ticket)

**Comment by rwjblue** [comment]
There will be "@index" and "@guid" that you can use (@index is what we are using now by default).

**Comment by rwjblue** [comment]
> In testing canary with one of our apps, we noticed some incorrect dom-reuse when the array changed. 

This is generally because of the default usage of the item's array index as key.

**Comment by knownasilya** [comment]
What about defaulting to "**@guid**"?

**Comment by rwjblue** [comment]
It has been done.

**Comment by rwjblue** [comment]
Whoops, sorry I thought you meant adding `@guid` as an option. It isn't the default because `Ember.guidFor` actually mutates the object you call it on (to add `__embermeta134124131` with the guid).  In the long term, we could use an ES6 Map but there isn't a good polyfill that I know of (that doesn't mutate the object).

**Comment by knownasilya** [comment]
Maybe instead of deprecating, we just spit out a warning whenever there is an each without a key.

**Comment by rwjblue** [comment]
@knownasilya - How is that much different?  People should be supplying a key, deprecation vs warning doesn't seem to make much difference there...

**Comment by knownasilya** [comment]
Because deprecation means eventual removal, but as in @jayphelps' case there is that case where there is no stable id. 

But I guess that's a small use case. Really if you have that, then just use guid, otherwise use a key? I guess I'm convinced :smile_cat:

**Comment by rwjblue** [comment]
> as in @jayphelps' case there is that case where there is no stable id

In either case `key` is always used. In his case, you would just use `@guid` as the key itself like: `{{#each thingsArray key="@guid" as |item|}}{{/each}}`.

> Because deprecation means eventual removal

Completely agreed.  I'll review with the rest of the team before deprecation.  If we intend to allow keyless usage long term (like when we can have native ES6 Map's and don't need to mutate the object) we should not deprecate.

**Comment by rwjblue** [comment]
I have implemented as warning for now, closing...

**Comment by christophermlne** [comment]
i feel like the syntax is looking a bit unfriendly... complicating what should be a simple looping construct.

opinion only.

**Comment by knownasilya** [comment]
simple=inefficient. Not sure how key='option' is unfriendly..

@guid is a generated guid, probably based on the item 
@index is the index of the item, hence it's not efficient, since if you sort your array you loose your key..

**Comment by akshayrawat** [comment]
+1 What @christophermlne said. The simple use case of iteration would now need guid in most of the use-cases.

**Comment by christophermlne** [comment]
if "@guid" is the new default, why are we required to specify it?

**Comment by knownasilya** [comment]
@christophermlne it's not the default. Previously it was @index, but that isn't performant so now you "must" specify a key or you see a warning.

**Comment by funtusov** [comment]
We must specify one key or another, so if the recommended "fast" option is @guid. why not make it a default?

**Comment by rwjblue** [comment]
Great point, I submitted a PR for exactly that :)

**Comment by ianwdunlop** [comment]
The each helper [documentation](https://github.com/emberjs/ember.js/blob/0ba7856ba1db595eb45689610793d98e6a508bfb/packages/ember-htmlbars/lib/helpers/each.js#L37) implies that this key is purely to help the renderer. I shouldn't have to care about that. Convention over configuration etc.....

**Comment by funtusov** [comment]
@rwjblue fixing code even before someone realize there's a problem with it since: 'xx :)

**Comment by gerry3** [comment]
This warning was removed in favor of a default key of `@identity` by #11461, but that isn't in 1.13.0 & maybe not even in (1.13.1)[https://github.com/emberjs/ember.js/pull/11461#issuecomment-112642077]

**Comment by rwjblue** [comment]
@gerry3 - Correct, I missed the commit when I released 1.13.1, I will be shipping a 1.13.2 within a day or two.

**Comment by gerry3** [comment]
Thanks @rwjblue! Just wanted to make sure anyone who came across this thread knew the plan.
