### ISSUE TITLE
Application template won't render when using pods structure

### ISSUE THREAD

**Issue by validkeys** [emberjs/ember.js#11331]
I moved my application template and route from:

```
app/templates/application.hbs
app/routes/application.js
```

to:

```
app/pods/application/route.js
app/pods/application/template.hbs
```

My env config is the following:

```
    modulePrefix: 'client',
    podModulePrefix: 'client/pods',
```

Is there something I'm doing wrong? The application route is not firing (i tried console logging in the beforeModel hook) and the template doesn't render -- therefore my app doesn't render.

Any help would be appreciated.

Thanks!

**Comment by balinterdi** [comment]
This is probably too little, too late, but your scenario works fine on an Ember 2.1.0 app.

**Comment by acorncom** [comment]
This seems to have grown stale. If there is still some bug here, feel free to comment here again and we can reopen the issue
