### ISSUE TITLE
Ember.computed is not cached, when accessed by nested set.

### ISSUE THREAD

**Issue by martndemus** [emberjs/ember.js#11334]
See: http://emberjs.jsbin.com/sapigibida/1/edit?html,js,console

I believe the y property should be cached after being called once for each instance of App.Foo created.

**Comment by pixelhandler** [comment]
@martndemus can you provide an updated example (reproduction of the issue) using a current release of Ember.js or the LTS release (2.4.6) ?

**Comment by martndemus** [comment]
Haven't seen the issue in a long long time, can be closed from my perspective.
