### ISSUE TITLE
emberjs.com search feature is broken in context of guides

### ISSUE THREAD

**Issue by jdbo** [emberjs/ember.js#11335]
To reproduce:

1. Navigate to http://guides.emberjs.com/v1.12.0/
2. Type "test" into the text field and enter
3. URL updates to reflect the query ( http://guides.emberjs.com/v1.12.0/#stq=test&stp=1 ), but nothing happens on the page; the following error displays in the developer console:

`Uncaught TypeError: Cannot read property 'query' of undefinedd @ swiftype_nocode-f97a44b44346c8640f6dc27d59c1da15.js:18Y.Callbacks.c @ swiftype_nocode-f97a44b44346c8640f6dc27d59c1da15.js:14Y.Callbacks.h.fireWith @ swiftype_nocode-f97a44b44346c8640f6dc27d59c1da15.js:14r @ swiftype_nocode-f97a44b44346c8640f6dc27d59c1da15.js:16Y.ajaxTransport.send.n.onload.n.onreadystatechange @ swiftype_nocode-f97a44b44346c8640f6dc27d59c1da15.js:16`

The search still appears to be working in (at least some) other areas of the emberjs.com, but it'd be great to be able to search within the guides!

**Comment by jdbo** [comment]
P.S. tested with Chrome (Version 43.0.2357.81 (64-bit) on Mac Yosemite)

**Comment by truenorth** [comment]
@jdbo - Probably want to file it against [emberjs/guides](https://github.com/emberjs/guides)

**Comment by trek** [comment]
Yes, please file against guides.
