### ISSUE TITLE
[Glimmer] Binding issue

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#11345]
I'm not sure if this is an issue or if it's just a difference in behaviour I wasn't aware of.
(Sorry about the bad title)

v1.12.0-beta.3 pre-glimmer [binding works](http://jsfiddle.net/amk221/fned5zzx/)
v1.13.0-beta.2 glimmer [binding doesn't work](http://jsfiddle.net/amk221/wsapgqrL/)

**Comment by amk221** [comment]
Further explanation of why this is an issue...

With {{old-style foo='bar'}} I used to be able to mutate foo on init.
Now I can't, because at init time, this.attrs are not mutable and this.set('foo', 'baz') is broken.
I could use didReceiveAttrs instead. However this hook can happen initially and many times subsequently. Which is not useful for me because I need it to happen once.
I could set a firstReceive flag on didReceiveAttrs, but it seems silly.

**Comment by rwjblue** [comment]
didInitAttrs is the hook you want (only fires once when attrs are initialized the first time)

**Comment by amk221** [comment]
Thankyou. It wasn't mentioned [here](http://emberjs.com/blog/2015/05/24/another-two-oh-status-update.html#toc_new-lifecycle-hooks).
