### ISSUE TITLE
How to inherit view's action helper in custom component

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/ember.js#11355]
I'd like to create a button component to make it more easy to manage button loading states. However when I use the component the view actions do not trigger as expected.
```
<button {{action ""}}></button>
// This action triggers when the user presses enter, submits a form, etc...
```

```
{{button-component action=""}}
// only trigger when I call .sendAction()
```

What do I need to do to enable the same actions on my component than the ones on the view without having to nest my template in a div? (angular replace:true works a charm)

**Comment by stefanpenner** [comment]
this is a question better asked on StackOverlfow, as it does not appear to be a bug.

**Comment by olivierlesnicki** [comment]
```
// button-component/component.js
Ember.Component.extend({
  tagName: '', // <- important ;-)
  actions: {
    action() {
      this.sendAction();
    }
  }
});
```

```
// button-component/template.hbs
<button {{action "action"}}>Boom!</button>
```
