### ISSUE TITLE
Test runner not working with PhantomJS 2.0

### ISSUE THREAD

**Issue by tomdale** [emberjs/ember.js#11378]
Could be something specific to my machine, but when I tried to run the Ember tests via the command line, I was getting this error message:

```
➜  ember.js git:(master) npm test

> ember@2.0.0-canary pretest /Users/tomdale/Code/ember.js
> ember build

version: 0.2.7
Building.[BABEL] Note: The code generator has deoptimised the styling of "ember/tests/routing/basic_test.js" as it exceeds the max of "100KB".
Built project successfully. Stored in "dist/".

> ember@2.0.0-canary test /Users/tomdale/Code/ember.js
> bin/run-tests.js

Running: phantomjs bower_components/qunit-phantom-runner/runner.js ./dist/tests/index.html?package=container
Unable to access network: fail
```

Once I downgraded to PhantomJS 1.9.8 everything worked as expected. This may be fixed by upgrading the `qunit-phantom-runner` dependency but I haven't investigated.

**Comment by rwjblue** [comment]
Thank you for reporting.

**Comment by stefanpenner** [comment]
Strange as CI runs the tests on phantomjs and all appears green. Are you confident your phantomjs works?

**Comment by stefanpenner** [comment]
I believe i've seen this issue before, in the past it has be file permission issues. I'll poke around tomorrow (or maybe tonight if i have a chance)

**Comment by stefanpenner** [comment]
so it appears, the runner tries to run

```
phantomjs bower_components/qunit-phantom-runner/runner.js ./dist/tests/index.html?package=container
```

the query param appears to confuse it, removing it prevents the "network fail"

**Comment by stefanpenner** [comment]
fixed
