### ISSUE TITLE
Deprecate views in 1.13, Addonize and remove from core in 2.0

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#11377]
This is a quest issue tracking the process of removing views from Ember 2.0.

* [x] In Ember 1.13 the following APIs will be deprecated:
  * [x] `{{view 'some-view'}}`
  * [x] `{{view.someProp}}`
  * [x] Using `Ember.Select` (which is a view) and `{{view "select"}}`
  * [x] Using `Ember.View` (except for internals)
* [ ] In Ember 1.13, using `Ember.Checkbox` will warn (once) that it will become a component in 2.0
* [x] In Ember 2.0, the following APIs will be removed from Ember:
  * [x] `{{view 'some-view'}}`
  * [x] `{{view.someProp}}`
  * [x] Using `Ember.Select` (which is a view) and `{{view "select"}}`
* [x] In Ember 2.0, `Ember.Checkbox` will become a component instead of a view
* [x] An addon will be released called `ember-legacy-views` with 2.0 (at the latest)
  * [x] provides `Ember.View`
  * [x] toggles a private flag that enables `{{view.someProp}}`
  * [x] provides (or toggles a private flag for) `{{view "some-view"}}`
  * [x] provides `{{view "select"}}`

Documentation updates will need to happen:

* [ ] Deprecation guide for views
* [ ] Deprecation guide for select. Since select will be removed in 2.0, alternative existing addons should be suggested
* [ ] Review guides to remove view documentation, select documentation

**Comment by krisselden** [comment]
viewName?

**Comment by jackmatt2** [comment]
Ember.Checkbox will become a component but what about Ember.Select?

**Comment by jackmatt2** [comment]
Why is Ember.Select not being converted into a component also like Ember.Checkbox?  Why will it be packaged as a separate addon?  It seems to me that an HTML select element is something pretty much all projects will use.

**Comment by Eptis** [comment]
not all of them, so I would prefer an addon for these things. But I also wonder, why not make Ember.Select a component as well (in the addon)?

**Comment by mixonic** [comment]
I would like to keep this ticket fairly tactical, but would happily discuss this in detail on discuss.emberjs.com if we can take the discussion there. I know some of the items here may be controversial.

The select view has terrible performance. Robert was showing me one of his versions the other day that was easily an order of magnitude faster. It has been pathological and we were not able to improve it within semver constraints. These constraints also limit us from just making it a component.

The select view also relies heavily on two way binding. This will not be an idiomatic development style in Ember 2.x, and the select view would quickly become an exception to the entire programming model of data-down actions-up we are excited about. Even if it we could just make it a component, it would be unlike what we expect components to be.

For these two reasons, it needs to go in 2.0. We do not have a viable component version that uses modern idiomatic style, so we will instead be pushing the select implementation back to addon-land where it can be iterates upon. There are already a few decent options, and I'm sure we will have a few more arise using the new 1.13 APIs and angle components when they land. In time, perhaps one of these could become official.

The select view will be part of the ember-legacy-views add-on, which will be supported until Ember 2.4. This should provide plenty of time for a well performing and modern option to mature.

**Comment by amk221** [comment]
With `view` going away, the migration to use `component` instead is not a simple swap.
I use `{{view myComponent}}` to render an already instantiated component. Will the component helper be able to do this in future?

**Comment by rwjblue** [comment]
2.0.0 has shipped.  Closing...
