### ISSUE TITLE
Error when there is a 'currentState' property on a component

### ISSUE THREAD

**Issue by gethinwebster** [emberjs/ember.js#11374]
In Ember 1.13.0-beta.2, having a component with both a `currentState` property and an `init` method with a call to `this.set` on any property causes the following error:
```
Uncaught TypeError: this.currentState.legacyPropertyDidChange is not a function
```

See: http://jsfiddle.net/as72hpe0/, extract:

```
App.MyComponentComponent = Ember.Component.extend({
    foo: 'bar',
    currentState: 'myOwnProperty',
    init: function(){
        this.set('foo', 'something');
        this._super();
    }
});
```

In the documentation, `currentState` is not specified as being a private property of `Ember.Component`, but it appears that it's being used as such internally.

Code ref:
https://github.com/emberjs/ember.js/blob/a3fad34a69564d8b4735e6574e10d0853db2dbcd/packages/ember-views/lib/compat/attrs-proxy.js#L119

**Comment by rwjblue** [comment]
Sadly, this was missed during the work for Ember 2.0.0.  I updated the internals in https://github.com/emberjs/ember.js/pull/12163 to move the reserved word to `._currentState`, and flagged the `.currentState` deprecation to be removed in 2.3.0 (after the next LTS release).
