### ISSUE TITLE
{{#each}} over an array of booleans doesn't work with {{input type="checkbox"}} binding.

### ISSUE THREAD

**Issue by nathanhammond** [emberjs/ember.js#11382]
Possibly a "CANT/WONTFIX" but unsure. Full reproduction:
http://emberjs.jsbin.com/kegabavaha/1/edit?html,js,output

**Comment by pixelhandler** [comment]
@nathanhammond Yeah still seems to be an issue on canary, do you have another bin with this working in a previous version?

**Comment by rwjblue** [comment]
I don't think this is a bug.  Bindings only really work for things that are mutable, boolean values in an array don't fit the bill. The same issue exists for an array of strings.

**Comment by locks** [comment]
@rwjblue can you review my triaging and confirm by closing the issue?
