### ISSUE TITLE
send event destroy when an EmberObject is destroyed

### ISSUE THREAD

**Issue by martndemus** [emberjs/ember.js#11385]
For `init` you can already do
```js
Ember.Object.extend({
  initX: Ember.on('init', function() {
    // do stuff
  })
});
```

So why not allow it for `destroy`?
```js
Ember.Object.extend({
  destroyX: Ember.on('destroy', function() {
    // do stuff
  })
});
```

My use case:
I don't like having to call `this._super` (in a mixin).

**Comment by stefanpenner** [comment]
-1 use super. Less caveats and much more performant.

**Comment by fivetanley** [comment]
I think you can currently do it on `willDestroy`, but I agree with @stefanpenner.

**Comment by martndemus** [comment]
If not destroy, then why enable `on('init', ...)`?

**Comment by stefanpenner** [comment]
I don't believe that was the correct thing to add.

With destroy/init ordering is often very important, unfortunately with events concise ordering is not possible. Especially when inheritance and various user provided mixins are provided. Luckily the super chain is concise and predictable.

**Comment by krisselden** [comment]
I added 'init' as a crutch for people relying on property change events to work out ordering of initialization, because property change events do not fire during init.  Add-on developers and framework developers should not use 'init' but should just initialize their object into a good initial state without relying on property change events.

**Comment by martndemus** [comment]
Ok, I can agree with that standing point. 

Is there a measurable performance hit on using init event vs overriding init?

**Comment by stefanpenner** [comment]
> Is there a measurable performance hit on using init event vs overriding init?
yes

willDestroy  + destroy methods (with super) are the API here.
