### ISSUE TITLE
{{link-to data-someattr="Some Value"}} no longer works

### ISSUE THREAD

**Issue by mfpiccolo** [emberjs/ember.js#11391]
In the [guides](http://guides.emberjs.com/v1.10.0/templates/binding-element-attributes/#toc_adding-data-attributes) to allow data attributes to be added to the link-to helper it suggests reopening Ember.View.  

This functionality no longer works in v1.13.0-beta.

This is most likely related to #11390 

JSBins:
[v1.13.0-beta](http://jsbin.com/befibi/2/edit?html,output)
[v1.12.0](http://jsbin.com/qukine/2/edit?html,output)

PS Thanks you @jmurphyau, I used your jsbins

**Comment by amk221** [comment]
Is this a bigger issue now affecting all components not just link views
`init` is called too early for access to attributes
`didInitAttrs` is called too late to get the attributes and add them to attributeBindings
http://jsbin.com/vidazi/edit?html,js,output

**Comment by aortbals** [comment]
This doesn't appear to affect other components, only the `LinkView` component. See https://github.com/emberjs/ember.js/issues/11763. This seems to affect all bound attributes on `link-to`.

Issues: `class` https://github.com/emberjs/ember.js/issues/11390, https://github.com/emberjs/ember.js/issues/11763, `tabindex`  https://github.com/emberjs/ember.js/issues/11763

**Comment by rwjblue** [comment]
Thanks @aortbals for doing the research here.  Closing in favor of #11699 (but will be updating with your summary of issues).
