### ISSUE TITLE
{{link-to}} class not updating

### ISSUE THREAD

**Issue by jmurphyau** [emberjs/ember.js#11390]
The contents of the {{link-to}} are being updated, but the class (passed in as `class` or `classNames` isn't).

I've built a JSBin that demonstrates this issue..

**1.13-beta.1 (fails)**: http://jsbin.com/wibonu/2/edit?html,js,output
**1.12 (works)**: http://jsbin.com/wibonu/1/edit?html,js,output

**Comment by aortbals** [comment]
This is the same issue as https://github.com/emberjs/ember.js/issues/11763.

**Comment by rwjblue** [comment]
Closing in favor of #11699 (trying to consolidate).

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/11960.
