### ISSUE TITLE
Binding style attributes warning

### ISSUE THREAD

**Issue by zyllorion** [emberjs/ember.js#11395]
```
WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see http://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes.
```

Unfortunately there doesn't seem to be a way to disable the warning on the link given.

Code for escapeCSS is not given so I cannot use this and should not need to as it is just a calculated RGB value.

I do return a ().htmlSafe()

Thanks.

**Comment by rwjblue** [comment]
Can you please provide a demo JSBin so we can help you a bit better here?

**Comment by bantic** [comment]
Here's a [demo jsbin](http://emberjs.jsbin.com/nonibe/edit?html,js) showing this behavior. Using a computed property inside a `style` string generates this warning even if the value of the CP is a safe string.

```
Ember.set('color', Ember.String.htmlSafe('blue');
<div style="color: {{color}};"></div> // generates console warning

Ember.set('myStyle', Ember.String.htmlSafe("color: blue;"));
<div style={{myStyle}}></div> // no console warning
<div style="{{myStyle}}"></div> // does show console warning
```

**Comment by rwjblue** [comment]
Yes, @bantic is correct.  You can return a `SafeString` from a CP and use that unquoted in the template to avoid a warning, but if you quote the property it will trigger this warning.  We would like to avoid this warning when concatenating all safe strings, but that will have to occur in a future version....

**Comment by mixonic** [comment]
Specifically, we would accept a patch that causes `<div style="{{mySafeStyle}}"></div>` to be treated as "safe". However `<div style="color: {{mySafeColor}};"></div>` should remain unsafe. It can probable get a better error message though.

**Comment by luxferresum** [comment]
@mixonic why would `<div style="color: {{mySafeColor}}; width:{{mySafeWidth}};"></div>` be unsafe? Seems like an unnecessary limitation to me.

**Comment by mixonic** [comment]
@luxferresum to know that `mySafeColor` is a color and that `color` is escaped/validated a certain way means we must parse CSS. Just like to know `<a href={{foo}}>` doesn't contain an XSS attack Ember parses HTML according to the spec and ensures the contents of `foo` are escaped properly. After parsing we need analysis for what properties (like `background-url`) have vulnerabilities and what they are so we can provide test cases.

It is just a big problem, and needs a champion to own it and execute.

**Comment by luxferresum** [comment]
@mixonic Well that would be awesome, but its only true if `mySafeColor` is not a safe string.
I think if `{{mySafeColor}}` is the result of `Ember.String.htmlSafe()` there should be no warning at all. Same with `{{{mySafeColor}}}`.

**Comment by Serabe** [comment]
Just think that, in general, the concatenation of two safe strings does not need to be a safe string. This currently happens in code too:

![2016-09-14 at 21 27](https://cloud.githubusercontent.com/assets/36221/18526759/22e29108-7ac2-11e6-9483-79577986ed3f.png)

If you were to move that to a property, you would need to mark the final string as safe, even if you don't think it is needed.

I think Ember should fall on the safe side and the only case where a safe string can be guaranteed to still be a safe string is in the `<div style="{{foo}}"/>` case.

**Comment by luxferresum** [comment]
It's an unnecessary warning, it works, and people like me will just go with the warning if there is no easy way around. Building the entire style property in JS is not really a fancy solution.

Also isn't that what @rwjblue said?

> We would like to avoid this warning when concatenating all safe strings, but that will have to occur in a future version....

That two safe strings are a normal string is normal and a JS limitation. There is no way to overload `+`.  A safe string is always safe. By creating a safe string you basically say "I know this is safe, believe me" to your framework. If you can't say this to your framework its highly annoying.
