### ISSUE TITLE
`_parentView` inside collectionView returns `null` - Ember 0.2.7

### ISSUE THREAD

**Issue by guatedude2** [emberjs/ember.js#11402]
After upgrading to Ember 0.2.7 I noticed that `ivy-sortable` wasn't working. Digging into the code I noticed that `_parentView` returns `null` even though the component does call `didInsertElement()`. I tried using 
`Ember.computed.alias('parentView'), this.get('parentView'), this.parentView;`
`Ember.computed.alias('_parentView'), this.get('_parentView'), this._parentView;`

but they all seem to return `null` or `undefined`.

**Comment by rwjblue** [comment]
What Ember version?  Also, `_parentView` is gone (you should generally use `parentView` if you must).

**Comment by guatedude2** [comment]
Here's my `ember -v` output
```
version: 0.2.7
node: 0.12.4
npm: 2.11.0
```
