### ISSUE TITLE
Select view does not work properly on initialisation

### ISSUE THREAD

**Issue by novtor** [emberjs/ember.js#11404]
The select view does not show the prompte message when its value is null. Instead, the last value in the content is shown
http://output.jsbin.com/xicoge/1

**Comment by rwjblue** [comment]
FYI - Ember.Select is deprecated in 1.13 and will be moved out of core into an addon in 2.0.0.

**Comment by veebs** [comment]
@rwjblue Is there are replacement for Ember.Select?  If not, what is the recommended way to implement select in Ember in order to bind the options and selected values to properties?  Thanks.

**Comment by novtor** [comment]
Ok, in the blog there is an example of select impletmentaion with references on some addons. Thnak you for the info

**Comment by novtor** [comment]
I think this one can be closed
