### ISSUE TITLE
transitioning to error page yields '_unused_dummy_error_path' in url

### ISSUE THREAD

**Issue by Eptis** [emberjs/ember.js#11427]
In my application I catch 404 errors from a subroute in its parent route:
```
actions:{
    error: function(error){
        if (error && error.status === 404) {
          this.transitionTo("participants.error", error.statusText);
        };
        // Keep bubbling the error if it's not a 404
        return true;
      }
    }
```
When transitioning to the error subroute I get a weird structured url: `participants/_unused_dummy_error_path_route_participants/Not Found`. Where is the `_unused_dummy_error_path_route_participants` coming from and how do I change/leave this out? Or am I handling the transition in the wrong way? Could not find any documentation on this

**Comment by artsyca** [comment]
I believe this should be `this.intermediateTransitionTo("participants.error")`

**Comment by rwjblue** [comment]
Fixed via @artsyca's suggestion (`intermediateTransitionTo` was made public in https://github.com/emberjs/ember.js/pull/12174).
