### ISSUE TITLE
Use action helper to grab route action

### ISSUE THREAD

**Issue by mitchlloyd** [emberjs/ember.js#11420]
Working with the new `action` helper in a top-level template, it seems that it isn't possible to grab and bind an action from a route. Given that controllers are sticking around for a while, would it make sense to implement action lookup that would first look on the controller and then on the route to mirror the behavior of the old string style?

[Example of the issue](http://emberjs.jsbin.com/giliwakide/1/edit)

/cc @mixonic

**Comment by mixonic** [comment]
@mitchlloyd you have stumbled on a failing of the current setup. Old `<button {{action "foo"}}>` helpers fire with sendAction, and new `<button onclick={{action "foo"}}>` helpers just create a closure over `actions.foo`.

You are correct that this is inconsistent. My immediate suggestion is to always use the nested helper invocation: `<button {{action (action "foo")}}>`. I would like to replace this with `<button on-click={{action "foo"}}>` early in the 2.x series, then deprecate the old style.

We have not be planning to implement action bubbling for routable components. Instead, a route would pass actions to the routable component in the same manner that any component passes actions down. In this ticket you have identified the awkwardness that will stick around until we land `on-click` and routable components.

**Comment by mitchlloyd** [comment]
Thanks for the response, it's good to know the plan! 

I think we might be talking about something slightly different because I'm not seeing the connection with the nested action invocation and the `on-click` behavior. I was hoping to have a way to close over a route's action like this so I could pass it to a component:

```javascript
  {{my-index getIt=(action 'doIt')}}
```

As it stands now in the JSBin I get the error:

```
Uncaught Error: An action named 'doIt' was not found in (generated index controller).
```

I was thinking that maybe it wouldn't be too hard to look into the route's actions as well as the controller's.

In any event this probably falls under "not worth implementing -- let's just get routable components already" :smile:

**Comment by mixonic** [comment]
Exactly- you must define `doIt` on the controller and call `sendAction` from there. The goal is that we have a better way to do this post routable components:

```
{{my-index getIt=attrs.someActionPassedToRouteableComponent}}
```

**Comment by mixonic** [comment]
Going to close this for now, but please re-open if appropriate

**Comment by waleedq** [comment]
I am facing the same issue here with the ember-dialog plugin, as we are creating the dialog component programmatically and we set the target property of that component to a custom context passed by the user. 
But using the closure actions won't bubble the action from that component to the target element.

As a suggested solution for this issue, why not to call the sendAction method for targets that implement this method,

so in https://github.com/emberjs/ember.js/blob/b1a1baf57cb1da177b7f5f68e69a5113d4120e59/packages/ember-glimmer/lib/helpers/action.js#L317

we add the following code
`
if(typeof target.sendAction == "function){
 action = function(){ target.sendAction(actionName, ...arguments) }
}
`
