### ISSUE TITLE
Ember freezes up when transitioning from `collection/:id/func` to `collection/:newID/func` && func accesses a collection on `collection/:id`'s model

### ISSUE THREAD

**Issue by anulman** [emberjs/ember.js#11424]
Believe I found a bug in canary + 1.13.0-beta.x, which was introduced in 1.13.0-beta.1:

When replacing a model mid-route—i.e. transitioning from `/collection/:id/func` to `/collection/:newID/func`—Ember 1.13.0-beta.x && canary freeze when the `.../func` route accesses a collection on `modelFor('collection.show')`.

- JSBin w/Canary: http://emberjs.jsbin.com/pujesidovo/1/edit?html,js,output
- JSBin w/1.13.0-beta.2: http://emberjs.jsbin.com/qinopupozu/1/edit?html,js,output
- JSBin w/1.13.0-beta.1: http://emberjs.jsbin.com/bumufihiho/1/edit?html,js,output

This freeze does not occur for subroutes that do not access the parent model's children, nor with Ember 1.12.x.

- JSBin w/1.12.0: http://emberjs.jsbin.com/wamiloxalu/1/edit?html,js,output
- JSBin w/1.12.1: http://emberjs.jsbin.com/juxowudece/1/edit?html,js,output

The deprecation being thrown leads me to believe something is causing an infinite loop by continuously invalidating / revalidating a view while rendering:

![screenshot 2015-06-11 15 18 57](https://cloud.githubusercontent.com/assets/721128/8123558/7304274c-1091-11e5-89cd-56ef76aea968.png)

If this was not intentional and is in fact a regression, I'd be interested in writing a failing test & trying to fix it. I've already taken a cursory look at the objects / methods hinted at above and nothing jumped out; would really appreciate if someone can point me in the right direction as I reason further.

**Comment by anulman** [comment]
Update: the regression only occurs when yielding the resource via block params. Using `{{resource.name}}` in the component vs. `{{yield resource}}` works fine, even if you use {{yieldedResource.name}} in the parent template.

JSBin (running Canary): http://emberjs.jsbin.com/wokeriyoqe/1/edit

**Comment by anulman** [comment]
Update: just checked again; this is fixed in Canary, not yet landed in 1.13.1

**Comment by anulman** [comment]
Closing issue; was resolved in 1.13.2

**Comment by rwjblue** [comment]
Awesome, thank you for confirming!
