### ISSUE TITLE
Ember.ObjectController deprecation error, but trace is not useful

### ISSUE THREAD

**Issue by jdhines** [emberjs/ember.js#11429]
In process of upgrading to 1.11.3 from 1.10.
I've removed all object controllers, but I know this warning can still happen because of not using model.property. However, I've combed through my code and can't figure out where this is happening because the trace seems to point only to internal Ember code. I know one of these errors is from the application controller, but I don't have anything in my application template besides an outlet, and I get the deprecation warning even if I remove the outlet there (however, not if I leave the outlet and am on my index route, which seems weird to me, but I'm no Ember pro yet).
![image](https://cloud.githubusercontent.com/assets/2855641/8137358/cfba9186-1110-11e5-99a9-05d8ba69a9b6.png)

Here's each line in the trace:
 **at exports.default.ObjectProxy.default.extend.init (https://starqa.fmr.com/assets/vendor.js:37328:24)**
````javascript
Ember['default'].deprecate(objectControllerDeprecation, this.isGenerated, {
    url: 'http://emberjs.com/guides/deprecations/#toc_objectcontroller'
});
````
**at superWrapper [as init] (https://starqa.fmr.com/assets/vendor.js:28066:20)**
````
if (length === 0) {
    ret = func.call(this);
}
````
**at new Class (https://starqa.fmr.com/assets/vendor.js:42313:14)**
````javascript
      if (length === 0) {
        this.init();
      } 
````
**at Function.ClassMixinProps.create (https://starqa.fmr.com/assets/vendor.js:42782:14)**
````javascript
return new C();
````
**at instantiate (https://starqa.fmr.com/assets/vendor.js:11868:24)**
````javascript
if (typeof factory.extend === 'function') {
    // assume the factory was extendable and is already injected
    return factory.create();
}
````
**at lookup (https://starqa.fmr.com/assets/vendor.js:11738:17)**
````javascript
var value = instantiate(container, fullName);
````
**at Object.Container.lookup (https://starqa.fmr.com/assets/vendor.js:11658:14)**
````javascript
    lookup: function(fullName, options) {
      Ember['default'].assert('fullName must be a proper full name', this._registry.validateFullName(fullName));
      return lookup(this, this._registry.normalize(fullName), options);
    },
````
**at EmberObject.default.extend.controllerFor (https://starqa.fmr.com/assets/vendor.js:33314:30)**
````javascript
controller = container.lookup('controller:' + name);
````
**at EmberObject.default.extend.setup (https://starqa.fmr.com/assets/vendor.js:32816:29)**
````javascript
var controller = this.controllerFor(controllerName, true);
````

**Comment by jdhines** [comment]
If this shouldn't be an "issue" and I should just post this on SO, please let me know; I'm still learning the right way to bring these kinds of things up.

**Comment by jherdman** [comment]
There's a good chance this is coming from a generated controller. You can either silence this warning by creating them, or by using [ember-disable-proxy-controllers](https://www.npmjs.com/package/ember-disable-proxy-controllers) (warning: the latter turns all ArrayControllers into normal controllers as well).

**Comment by jdhines** [comment]
It probably is coming (at least in one case) from the application controller, which is generated automatically in my application. But the fact that the warning still shows when there is nothing in the application template (not even any outlets, just a blank file) makes me think that either this warning is in error in this case, or perhaps it's from a package, but if that's the case I have no way of knowing which package, since the trace doesn't tell me.

**Comment by jdhines** [comment]
Aaahhhh!

Never mind. I missed my loading templates, which are, in fact, declared as ObjectControllers. I just hadn't ever done a Find All on ObjectController in my project for some reason.

Not sure if this is an edge case with the deprecation warnings not knowing about the substates or if this is just a newbie mistake on my part.

**Comment by acorncom** [comment]
@jdhines Is this still an issue for you?  Seems like we could probably close this at this point?

**Comment by acorncom** [comment]
I'm going to close this for now, but happy to reopen this if we need to 👍
