### ISSUE TITLE
`hasBlock` broken in 1.12.1

### ISSUE THREAD

**Issue by alexlafroscia** [emberjs/ember.js#11430]
It looks like `hasBlock` doesn't work in Ember `1.12.1`  While it looks like it's fixed in `1.13`, it's definitely broken in `1.12.1`.

[Here is a JSBin of the broken behavior in 1.12.1](http://emberjs.jsbin.com/tunipe/2/).

[Here is a JSBin with the same behavior working in 1.13](http://output.jsbin.com/tunipe/4/)

**Comment by mixonic** [comment]
I don't believe hasBlock is a feature in 1.12.1?

**Comment by alexlafroscia** [comment]
Really? It's [in the docs for 1.12](http://emberjs.com/api/classes/Ember.Component.html#property_hasBlock)

**Comment by mixonic** [comment]
@alexlafroscia the docs are incorrect :-/ That feature was still behind a feature flag:

* https://github.com/emberjs/ember.js/blob/v1.12.0/features.json#L18

I'm unsure how/why it is listed in the 1.12 docs.

**Comment by alexlafroscia** [comment]
Oh okay, I see.  I would have sworn I tried adding the feature flag, too, but maybe I need to restart the server when adding them?

**Comment by mixonic** [comment]
@alexlafroscia Disabled features are stripped from beta and release builds. You cannot opt into a feature flag unless you use canary.

**Comment by alexlafroscia** [comment]
Gotcha. Thanks for the help :smile: I'll go ahead and fix the docs, then.

**Comment by rwjblue** [comment]
FYI - It is in the docs, because our API doc generation doesn't remove feature flagged docs (it never has).

This is definitely something we intend to fix in upcoming versions.

**Comment by dschmidt** [comment]
I was facing the same problem, when I wanted to prepare for 1.13. This is the polyfill I came up with for  1.12:

```javascript
if(Ember.VERSION.startsWith("1.12")) {
    Ember.Component.reopen({
        hasBlock: Ember.computed.alias('template')
    });
}
```

**Comment by rwjblue** [comment]
@dschmidt - :+1:
