### ISSUE TITLE
1.13: CollectionView fails on init

### ISSUE THREAD

**Issue by MichaelVdheeren** [emberjs/ember.js#11434]
The error says: `Uncaught Error: Assertion Failed: You must use Ember.set() to set the 'childViews' property (of <inspiration@view:sea-of/nodes::ember1011>) to ''.`

When I check it it points to the following lines of code in the ChildViewSupportMixin:
```
init: function () {
      this._super.apply(this, arguments);

      // setup child views. be sure to clone the child views array first
      // 2.0TODO: Remove Ember.A() here
      this.childViews = _emberMetalCore.default.A(this.childViews.slice());
      this.ownerView = this;
    },
```

I know this is deprecated for 2.0, but it should at least work correctly in 1.13 not?

**Comment by krisselden** [comment]
@MichaelVdheeren are you trying to observe childViews?

**Comment by MichaelVdheeren** [comment]
Yes I am, but never had problems with that. I know the docs say you can't manipulate the childViews property directly, but there's nothing about observing it.

**Comment by MichaelVdheeren** [comment]
@krisselden Removing the observes fixes it indeed. The question now is how am I going to trigger masonry to re-render when a childView was added...

**Comment by krisselden** [comment]
@MichaelVdheeren on the didRender event or hook?

**Comment by MichaelVdheeren** [comment]
Does didRender trigger after a childView was added?
