### ISSUE TITLE
need to deprecate ArrayController

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#11450]
cc @mixonic

**Comment by adamesque** [comment]
Reminder: please add to the deprecations guide http://emberjs.com/deprecations/v1.x/

**Comment by stefanpenner** [comment]
@adamesque can you open another issue, s

**Comment by samselikoff** [comment]
this is all set right? http://emberjs.com/deprecations/v1.x/#toc_arraycontroller

**Comment by adamesque** [comment]
Thanks y'all!
