### ISSUE TITLE
deprecate arrayproxy ?

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#11457]

**Comment by rwjblue** [comment]
I do not think that we discussed this (I could be wrong).  What are the costs of maintaining it?

**Comment by stefanpenner** [comment]
> I do not think that we discussed this (I could be wrong). What are the costs of maintaining it?

not much i think actually, just many extra bytes

**Comment by stefanpenner** [comment]
I am more evaluating how we can move to es6 iterable, or iterable like

**Comment by igorT** [comment]
I think lots of apps rely on it, moving away for us wouldn't be too hard.

**Comment by stefanpenner** [comment]
> I think lots of apps rely on it, moving away for us wouldn't be too hard.

I think I can rewrite ArrayProxy as an iterable, while still exposing the existing API. Bonus, is we can then iterate over ES6 structures.
