### ISSUE TITLE
1.13: Context within each

### ISSUE THREAD

**Issue by MichaelVdheeren** [emberjs/ember.js#11475]
I'm having problems with the following:

1. I fetch my data from the store and add it to a variable in a controller
2. Whilst my template has a component passing through it's context in the 1.13-way, the name of the player is not rendered.

In my template I have the following
```
{{#each players as |player|}}
    {{player-card player=player}}
{{/each}}
```

The card component template looks like:
```
player-card
name: {{player.name}}
```

This is a short example btw, what I do get is a rendered list (yes apparently the each does know how many elements there are), but without the name filled in. Could this be an Ember-Data issue, ED not being up-to-date/ready for 1.13?

**Comment by thejameskyle** [comment]
Try logging `player` with `{{log player}}` and see what data you have.

**Comment by stefanpenner** [comment]
@MichaelVdheeren can you provide a jsbin, or repo to an ember-cli demonstrating this issue?

**Comment by MichaelVdheeren** [comment]
@thejameskyle This is what I get when using ```{{log player}}{{log player.name}}```

![screenshot 2015-06-16 09 30 35](https://cloud.githubusercontent.com/assets/375809/8177997/9fd7b91a-140a-11e5-8460-6146dc2d5a59.png)

**Comment by pangratz** [comment]
@MichaelVdheeren You shouldn't be seeing internal models here. How do you get your `players`?

**Comment by MichaelVdheeren** [comment]
@pangratz Using ```this.store.find('players').then(function(players) {})```

**Comment by pangratz** [comment]
Hmm, `players` doesn't look like a valid `modelName` since your model is called `player`. Can you change it to `this.store.find('player')` and check if everything works as expected... ?

**Comment by MichaelVdheeren** [comment]
@pangratz Sorry, was a typo here, I use player for the query

**Comment by MichaelVdheeren** [comment]
This is the code I use, we use it to implement sort of infinite scrolling and loading

![screenshot 2015-06-16 09 41 14](https://cloud.githubusercontent.com/assets/375809/8178131/d9c9d724-140b-11e5-8d02-97cd67e0c0f6.png)

**Comment by MichaelVdheeren** [comment]
@pangratz if I replace ```players.get('content')``` by ```players.slice()``` I do get the correct class and not an InternalModel. By doing so everything works. However, the documentation says that after an ArrayPromise resolved the result is in the ```content```.

**Comment by pangratz** [comment]
What ED version are you on?

**Comment by MichaelVdheeren** [comment]
@pangratz Canary

**Comment by pangratz** [comment]
Now that I see it, have you tried:

``` js
this.get('players').removeObjects(players);
this.get('players').addObjects(players);
```

The passed `players` is a `RecordArray` and it should not be needed to access the `content`.

**Comment by MichaelVdheeren** [comment]
@pangratz That works perfectly, thx

**Comment by pangratz** [comment]
Ok, great! I'm wondering where you found this in the documentation, since this shouldn't be documented that way. Can you point me there or open an issue over at https://github.com/emberjs/data?

**Comment by MichaelVdheeren** [comment]
@pangratz voila: https://github.com/emberjs/data/issues/3359

**Comment by pangratz** [comment]
@MichaelVdheeren wonderful! Thank you sir.
