### ISSUE TITLE
enrich all controllers with actions

### ISSUE THREAD

**Issue by BenjaminHorn** [emberjs/ember.js#11477]
In my app I use CRUD heavily, so I want to have "save" and "delete"  actions in all of my controllers.

Now I do in my **crud-controller initializer**
```javascript
export default {
  name: 'crud-controller',
  initialize: function() {
    Ember.Controller.reopen({
      saving: false,
      _actions: {
        save: function(){
          ...
        }
      } 
    });
  }
};
```
It works fine, but feels wrong to abuse the private property **_actions**.
Is there a reason why it is private? Is there a better way to do this?

**Comment by joeruello** [comment]
Why not just use inheritance?

```javascript
// app/controllers/basic.js
export default Ember.Controller.extend({
    ...junk
});
```

```javascript
// app/controllers/foo.js
import Controller from 'app/controllers/basic'
export default Controller.extend({
   ... specific stuff
}):
```

If export a `basic` controller (or any other ember type), automagically generated controllers with also use that class.

**Comment by BenjaminHorn** [comment]
@joeruello  I thought about it but
1. i did not know, that
>If you export a basic controller (or any other ember type), automagically generated controllers with also use that class.
That sounds like real magic. How will Ember know that automagically generated controllers should inherit from that class? The name **basis** does the trick?

2. I would like control this enrichment at one place. Import and inherit in each controller file is fine, but reopening Ember.Controller is more easier.

I still don't get why `_action` is private, and will it cause any problem, to use it? (Beside that ugly underscore)

**Comment by joeruello** [comment]
* Exactly, Ember first looks for `app/controllers/basic`, and the falls back to a Ember.Controller 
* Using private APIs is risky in that they aren't covered by SemVer and can be removed/changed/broken at any time.

Should probably close this as it is more of a StackOverflow question than an issue. Feel free to open a question there or email me if you want to talk more.
