### ISSUE TITLE
Beta channel not compatible with Ember Data beta channel

### ISSUE THREAD

**Issue by raytiley** [emberjs/ember.js#11472]
http://emberjs.jsbin.com/hajesi/edit?html,console,output

@stefanpenner went on a tear last night removing stuff from beta, some of which is still relied upon by Ember data. I don't have time to dig into all the specifics, will try to circle back around if I can.

**Comment by stefanpenner** [comment]
> @stefanpenner went on a tear last night removing stuff from beta, some of which is still relied upon by Ember data. I don't have time to dig into all the specifics, will try to circle back around if I can.

sounds like an ED bug?

**Comment by stefanpenner** [comment]
https://github.com/emberjs/ember.js/commit/4b02547106fdee4900df7513ba3d66ed30871160 may have been a culprit.

**Comment by raytiley** [comment]
> 4b02547 may have been a culprit.

Yeah... sorry wrong repo. I can move. The issue I was seeing this morning after `noming` was that `EnumerabUtils` wasn't found. I thought I saw a commit last night about that being removed?

**Comment by stefanpenner** [comment]
> . I thought I saw a commit last night about that being removed?

yup, its no present. as it was deprecated

**Comment by stefanpenner** [comment]
just started going through ED, making good progress. in-progress PR will land shortly

**Comment by stefanpenner** [comment]
started -> https://github.com/emberjs/data/pull/3345 will work to finish it tonight

**Comment by stefanpenner** [comment]
my branch of ember-data has 100% green tests on ember canary
