### ISSUE TITLE
ContainerView children fire observers on creation

### ISSUE THREAD

**Issue by gdub22** [emberjs/ember.js#11489]
In 1.13.0+ ContainerView child views are firing observers of a parentView property upon creation.

1.12.1: http://emberjs.jsbin.com/verodi/edit?html,js,output (working, observers don't fire)

1.13.1: http://emberjs.jsbin.com/xejiqe/edit?html,js,output (observer triggers alert upon startup)

**Comment by stefanpenner** [comment]
should be fixed with: https://github.com/emberjs/ember.js/pull/11685
