### ISSUE TITLE
Cannot remove a bound attribute by setting it to null in Firefox

### ISSUE THREAD

**Issue by huguesdk** [emberjs/ember.js#11485]
A regression that appeared in Ember 1.11 prevents to remove a bound attribute of an element by setting the property back to `null`.

I bound the `pattern` attribute of an `input` element (using the input helper). The initial value is `null`, and as expected, the element doesn’t have the attribute. Setting the property to another value correctly adds the attribute on the element with the correct value. However, setting the property back to `null` doesn’t remove the attribute as expected, but instead set its value to `"null"`.

This bug appeared with Ember 1.11, and is still present as of today in 1.13. It affects Firefox (tested with version 38.0.5). Chromium is not affected (tested with version 25.0.1364.172).

In Ember 1.10, setting the property to null correctly removes the attribute.

Here is a [JS Bin testcase](http://emberjs.jsbin.com/qoqibo/edit?html,js,output).

**Comment by pixelhandler** [comment]
Noticed that this is an issue in Chrome and Firefox but not Safari. (I only have a mac, didn't test PC)

**Comment by rwjblue** [comment]
Thank you for reporting! This is now working properly in beta/canary.
