### ISSUE TITLE
Error Installing Ember.js

### ISSUE THREAD

**Issue by Titou3477** [emberjs/ember.js#11482]
I'm interested in Ember and I have been trying to install it, but I get the following error every time (I am using a mac with OSX 10.10) : 

~ npm install -g ember-cli
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "ember-cli"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code E404

npm ERR! 404 Not Found: expresss
npm ERR! 404 
npm ERR! 404 'expresss' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ember-cli'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

I have tried many different things, but none worked (including downgrading node to version 0.10.38) by the way, isn't it express instead of expresss ?

**Comment by stefanpenner** [comment]
That expresss seems to have many s in the name

**Comment by Titou3477** [comment]
Complete uninstall of npm, node and ember then reinstall appear to have solved the issue.

**Comment by stefanpenner** [comment]
Silly npm :(
