### ISSUE TITLE
{{action}} helper doesn't allow for dynamic actions name - ember 1.13

### ISSUE THREAD

**Issue by mar20** [emberjs/ember.js#11483]
After update ember to 1.13 is problem with dynamic action name in component template.

error from console:
"You specified a quoteless path to the {{action}} helper which did not resolve to an action name (a string)"

**Comment by stefanpenner** [comment]
> "You specified a quoteless path to the {{action}} helper which did not resolve to an action name (a string)"

what did it resolve to?

**Comment by anmolagrawal** [comment]
facing the same issue. Although functionality is working but getting this error in console:

```
Uncaught Error: Assertion Failed: You specified a quoteless path to the {{action}} helper which did not resolve to an action name (a string). Perhaps you meant to use a quoted actionName? (e.g. {{action 'save'}}).
```

**Comment by anmolagrawal** [comment]
What fixed for me was this - 

Example:
I was making a clickable flash messages and although they might have same text, action triggered would be different. If controller action returned an object 'flash', I did something like

<a href="#" {{action flash.action flash.object}}>

That's what I did originally and though, functionality was working, I got error you just posted. Then I removed the href from <a> tag and everything worked fine.

**Comment by mixonic** [comment]
Closing this, as it is not enough to reproduce and seems to have stalled.

**Comment by fzdvincent** [comment]
In case anyone stumbles onto this same issue, double check if your initial action variable isn't being initialized to null. In my case, setting it to an empty string was enough to allow the renderer to proceed.

**Comment by shankarsridhar** [comment]
thanks a lot @fzdvincent. That worked.
