### ISSUE TITLE
Can't use underscore in route name

### ISSUE THREAD

**Issue by mauricioac** [emberjs/ember.js#11487]
Ember doesn't render template on route with underscore on name( replacing it with hyphen makes it work).
Ember inspector shows the proper current route, but it just doesn't get rendered.

```
this.route("levelone", function() {
  this.route("level_two", {path: "level-two"});
});
```

I'm using Ember.js 1.12 stable.

**Comment by stefanpenner** [comment]
The naming convention is to use dashes not underscores.

**Comment by mauricioac** [comment]
Yes, I quickly realized that. But a beginner wouldn't know that, since on the guides it's not said anywhere that you can't use underscores (just double checked the routing section), and failing silently doesn't help either.

**Comment by peec** [comment]
30 minutes wasted on this issue, silent error, so impossible to find what's up. Glad i found this issue in the end. Solution: use dashes like stefanpenner stated.

**Comment by franzliedke** [comment]
Wow, I just got bitten by this one. Lost more than an hour trying to find what I had done wrong, but apparently Ember was just looking for a file named "learning-room", not "learning_room"?

After all, the underscore is fine in the path, too - why should it not be allowed in the route name, too?

**Comment by locks** [comment]
Moved to guides repository for documentation.
