### ISSUE TITLE
ember's own test suites spew its own warnings.

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#11481]
> WARNING: Using `{{each}}` without specifying a key can lead to unusual behavior.  Please specify a `key` that identifies a unique value on each item being iterated. E.g. `{{each model key="@guid" as |item|}}`.

- [ ] ensure 1 test exists that tests that the warning occurs
- [ ] ensure all other occurrences are fixed / tested

**Comment by rwjblue** [comment]
A PR exists to remove this warning.

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/11461

**Comment by jayphelps** [comment]
This can be closed.
