### ISSUE TITLE
isAny and its companions in addons

### ISSUE THREAD

**Issue by stavarotti** [emberjs/ember.js#11488]
`anyBy` is deprecated in favor of `isAny` and works as expected when prototype extensions are turned on however when off, as with all addons, there seems to be no way to access `isAny` (or `isEvery`/`findBy`).  Am I missing something?  Additionally, there aren't any references to the methods on the 1.13 docs.

**Comment by stefanpenner** [comment]
they are disable, since they are part of the prototype extensions, which are disabled in addons. This is to ensure addons are written in a way that can be shared between all sorts of apps, even those with prototype extensions disabled

**Comment by stavarotti** [comment]
>
This is to ensure addons are written in a way that can be shared between all sorts of apps, even those with prototype extensions disabled

Agreed although, when viewing the api docs, [isAny](http://emberjs.com/api/classes/Ember.ArrayProxy.html#method_anyBy) is explicitly recommended although there aren't any `isAny` docs (EnumerableUtils, now deprecated, is where I would expect to find function and respective docs).

Shouldn't we have docs to back up the recommendation or perhaps remove it altogether?  FYI, I now use Lodash for all array manipulation hence the reason I closed the issue.
