### ISSUE TITLE
11% size increase in built ember.js file size on Jun 7

### ISSUE THREAD

**Issue by ilkkao** [emberjs/ember.js#11494]
I created [a chart](http://iao.fi/ember-size/) which currently tracks the size of built `ember.prod.js` file. 

It shows that on June 7th, https://github.com/emberjs/ember.js/pull/11367 got merged and the file size increased to 1809.631 kB from 1617.784 kB (~ +11%) Similar bump happened also in `ember.min.js` file size.

It would be good check if there's a way to avoid and undo it.

@rwjblue @mixonic

**Comment by rwjblue** [comment]
Thanks for spotting and reporting. I'll try to dig in and see what is going on...

**Comment by ilkkao** [comment]
prod.js before the merge: https://github.com/components/ember/blob/b76a5e02847a300c5a1a543d2d8be34d71351857/ember.prod.js (1617.784 kB)

prod.js after the merge:  https://github.com/components/ember/blob/087457cec091c5966005765244fd6d0d0d4f4709/ember.prod.js (1809.631 kB)

**Comment by rwjblue** [comment]
@ilkkao - I have reopened just to make sure all is well. Can you confirm it is fixed, and close?

**Comment by stefanpenner** [comment]
@ilkkao nice chat!

**Comment by ilkkao** [comment]
Thanks to @davidpett all release channels are tracked now. 

I can verify that the canary release is now back at 472 kB after the fix from @rwjblue. Issue solved.
