### ISSUE TITLE
View.rerender doesn't work in 1.13.0

### ISSUE THREAD

**Issue by moveniumville** [emberjs/ember.js#11499]
After updating to new version, changing templates for views doesn't seem to work anymore. 

v1.12.0 still works:
http://jsbin.com/zijigipihe/1/edit?html,js,output

but v.13.0 does not:
http://jsbin.com/getofiridi/1/edit?html,js,output

**Comment by kanongil** [comment]
I have the same issue where my custom render hook is not called (now in v1.13.2).

**Comment by rwjblue** [comment]
@kanongil - That does not seem related to this issue.

**Comment by rwjblue** [comment]
@moveniumville - Yes, specifying a template or layout dynamically after initial render does not work in 1.13. There are a couple open issues related to that, but I do not have a clear path forward to making it work.

**Comment by kanongil** [comment]
@rwjblue OK. Issue created here #11515.

**Comment by matthiasleitner** [comment]
Seeing the same issue with components dynamically changing the template/layoutName and calling rerender. Any suggestion on how to hotfix this behaviour or workaround?

**Comment by rwjblue** [comment]
Changing the template or layout after initial render is not currently supported (which is the bug being tracked in this issue), I submitted a failing test case in https://github.com/emberjs/ember.js/pull/11315.

**Comment by rwjblue** [comment]
Closing in favor of the failing test case PR https://github.com/emberjs/ember.js/pull/11315.
