### ISSUE TITLE
[REGRESSION] In 1.13.2 "TypeError: Cannot read property 'key' of null at advanceToKey"

### ISSUE THREAD

**Issue by toranb** [emberjs/ember.js#11504]
Yesterday I upgraded from 1.12.1 to 1.13.1 w/ no issue. Today I upgraded from 1.13.1 to 1.13.2 and get the error

```
TypeError: Cannot read property 'key' of null at advanceToKey
```

This occurs as I transition from a detail route to the parent that has a simple each loop like so

```js
{{#each sortedThings as |thing index| }}
{{/each}}
```

I have a special sort mixin that rolls through and sorts by a special attr

```js
var SortedThingsMixin = Ember.Mixin.create({
    sortedThings: Ember.computed(function() {
        return this.get("model").toArray().sort(function(a, b) {
            var first = a.get("foo");
            var second = b.get("foo");
            return Ember.compare(first, second);
        });
    }).property("model.@each.nestedThingArrayWatch") //hack to watch nested array
});
```

I realize a full jsbin is more useful here - I'll see if I can reproduce it for clarity. In the meantime I wanted to get this up quick for others who might be having the same issue

**Comment by rwjblue** [comment]
I believe this is related to @cibernox's issue mentioned in https://github.com/tildeio/htmlbars/commit/eeb4bf8b83a67db50a356cbc8b3face7188f333d#commitcomment-11742721.

**Comment by toranb** [comment]
@rwjblue Ah yes- that seek issue is what I'm seeing :) thanks dude!

**Comment by toranb** [comment]
@rwjblue I'll let you decide to close this out /or use this to track the regression :)

**Comment by rwjblue** [comment]
Will leave it open here to track.  I think we need a reproduction to properly track this down (and get whatever is going wrong under test).

**Comment by cibernox** [comment]
Keep this open. It's the same issue anyway. My scenario is complex and not easy to reproduce, but I'll try anyway.

**Comment by btecu** [comment]
Seems to be the same issue as #11500.

**Comment by rwjblue** [comment]
@btecu - Yep, agreed. I still need help reproducing so we can fix...

**Comment by btecu** [comment]
Here is a jsbin reproducing the error: http://jsbin.com/tuxugupoxe/edit?html,js,console,output

If you remove the `unshift` line, it should work.

**Comment by jamesarosen** [comment]
I don't have a JSBin of it, but I've run into it while working on an addon. If you pull down https://github.com/knownasilya/pagination-pager/pull/14 and click through the pagination with ellipses (click 50, 49, 48, 47, 46, 45), you'll get this error.

See also #11500

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/11525 provides a useful error in this case until we can fix it upstream in HTMLBars.
