### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by raytiley** [emberjs/ember.js#11501]
I think I've found a memory leak: http://emberjs.jsbin.com/toqiba#/complicated

If you navigate between `simple` and `complicated` taking a heap profile each time the memory usage steadily climbs. `EmberMorph` seems to be getting pretty high on the retained size.

![snapshots](https://cloud.githubusercontent.com/assets/41680/8232949/e96cd224-1598-11e5-947f-f646b3688237.png)

**Comment by mixonic** [comment]
I see built-in helper streams among the leaks:

![](https://api.monosnap.com/rpc/file/download?id=BcTuwOEmblzS0xDyw6S07VoLCRHESi)

But they would leak if the morphs were leaking.

**Comment by raytiley** [comment]
@mixonic Are you going to be looking into this some more? Would love to help out if I can and learn a little bit more about how to debug these issues.

**Comment by stefanpenner** [comment]
just a quick guess (not familiar with this code) but i don't see a corresponding unsubscribe to  https://github.com/emberjs/ember.js/blob/680f997ed0958c420abdcd0b1673111aee26afe7/packages/ember-htmlbars/lib/hooks/invoke-helper.js#L36

**Comment by stefanpenner** [comment]
actually they all look attrNode related

**Comment by stefanpenner** [comment]
interestingly, the non `{{input}}` variant, basically just using the DOM directly doesn't leak its attrNodes

http://output.jsbin.com/lemexuyudu#/simple

**Comment by stefanpenner** [comment]
I have found the problem, or at least found the source of one of the leaks. I need to spend some time tonight yet thinking about which solution puts on a better path...

**Comment by stefanpenner** [comment]
the leak demonstrated is fixed
