### ISSUE TITLE
1.13.2 Uncaught Error: There is no route named 

### ISSUE THREAD

**Issue by JarrodCTaylor** [emberjs/ember.js#11503]
I have a repo that functions properly with 1.12.1 it can be found at https://github.com/JarrodCTaylor/ember-batteries-included-token-auth changing the version to 1.13.2 breaks the app and the only error I can get is `Uncaught Error: There is no route named`. The tests will not run the app will not load. I am unsure how to go about debugging this issue.

**Comment by rwjblue** [comment]
???

**Comment by JarrodCTaylor** [comment]
@rwjblue Not sure if this is worthy of a separate issue or not. I had a situation with a log out menu item that was not a real route but just an action. It had a `link-to` with an empty string for the argument. This has always worked in previous versions. However moving to 1.13.2 it ceased to work and just gave the error `Uncaught Error: There is no route named`. Once we were able to track down the issue it made sense. However,  the error message was no help without any context and and not knowing what the issue was. Here is a jsbin that shows the 'issue' 

http://jsbin.com/jawemu/2/edit?html,js

**Comment by zen-tmq** [comment]
I am also seeing this issue! in 1.13.10. Did you ever get this resolved?

**Comment by locks** [comment]
@zen-tmq use a regular `a` and put an action on it. Passing an empty string to `link-to` was never a supported feature, as far as I know.
