### ISSUE TITLE
components in each don't see updates to external bound properties

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/ember.js#11508]
Given the following template:

```hbs
{{#each foos as |foo|}}
  {{some-component foo=foo bar=someExternalBar}}
{{/each}}
```

 1. each `some-component` gets the correct `foo` and the value of `someExternalBar` correctly on setup
 1. if `foos` change, the `each` behaves properly
 1. but if `someExternalBar` changes without changing the `foos`, the `some-component` instances don't get that update

In the case I'm working with, `foos` looks like `[ '1', '2', '3', '4', '5' ]`. I'm not sure that matters, but it does prevent me from attaching `someExternalBar` to the `foo`s and using a custom `key`.

**Comment by jamesarosen** [comment]
JSBin suggests that I'm wrong and something else is happening: http://jsbin.com/hudaxuxaxe/3/edit?html,css,js,output

**Comment by mixonic** [comment]
Wrote up some tests that showed our current behavior is correct: https://github.com/mixonic/ember.js/commit/0759b750ed9bcb713d54fb917fb58088c4a406bb

**Comment by jamesarosen** [comment]
Yay for thorough tests :)
