### ISSUE TITLE
Array observer not triggering on change

### ISSUE THREAD

**Issue by temo44** [emberjs/ember.js#11514]
I've created a JSBin to demonstrate my case. This is the link: http://emberjs.jsbin.com/xoxabewuma/edit?html,js,output

I'm trying to modify an array. It only triggers when I set a whole new array, whilst modifying the existing array does not trigger anything.

What am I doing wrong? Thanks.

Edit: I updated the ember version, as I saw it was on version 1.5. http://emberjs.jsbin.com/caveruqoba/1/edit?html,js,output

**Comment by herom** [comment]
You have to update the Array with `pushObject()` rather than `push()` and voila - it works :+1:

**Comment by temo44** [comment]
Aight it indeed works :D, thanks. However, can you tell me why 'push' doesn't work and why I need to search my butt off to eventually find nothing on the interwebs? Thanks :).

**Comment by btecu** [comment]
It's documented in the `api` (which should be your source of information instead of the *interwebs*):
http://emberjs.com/api/classes/Ember.MutableArray.html#method_pushObject
`Push the object onto the end of the array. Works just like push() but it is KVO-compliant.`

**Comment by temo44** [comment]
Hi btecu last time I checked the Ember documentation was on the interwebs. I suppose my answer like in the 'KVO-compliant' part.
