### ISSUE TITLE
Not able to create block helper in emberjs

### ISSUE THREAD

**Issue by bpcrao** [emberjs/ember.js#11520]
I want to create a link-to which has
dynamic route and dynamic segments 

I dont see any way to achieve this

**Comment by mixonic** [comment]
@bpcrao this seems very vague. Normally we would recommend a component for the cases where you might desire a block form helper.

There is already a `link-to` helper, but I don't think that is what you are looking for?

I'm going to close this, but please let me know if I've missed something!

**Comment by bpcrao** [comment]
{{#block-link-to route.name model }}
<strong>{{linkTitle}} </strong>
{{/block-link-to}}

and in "block-link-to" template
{#link-to route.name model}} yield {{}}  

i want to do that , which is not possible currently, the route.name i want to pass to link-to should be dynamic and the segments passed on should also be dynamic.
