### ISSUE TITLE
is willRender called correctly?

### ISSUE THREAD

**Issue by Orgil** [emberjs/ember.js#11532]
I'm having nested components. Here is demo jsbin: http://emberjs.jsbin.com/mosiyedone/edit?html,js,console,output
output is
>"init viewport"
>-->"will render from viewport"
>-->"init panel"
>"will render from panel"
>"did insert from panel"
>"did insert from viewport"

is container rendering fired early? i don't know if it intentional or not.
i'm expecting 
>"init viewport"
>-->"init panel"
>-->"will render from viewport"
>"will render from panel"
>"did insert from panel"
>"did insert from viewport"

Basically, is this correct that willRender not fired right before rendering component.

**Comment by rwjblue** [comment]
I believe the ordering is correct.

**Comment by Orgil** [comment]
Then how do i predict child views while parent rendering?

**Comment by Orgil** [comment]
i need to do layout calculation right before injecting to dom. seems hasElement state is proper point, but it doesnt have a hook. if i do it on willRender, parent doesn't know about its child components. Can you point me the right direction, where i should handle layout calculation?

**Comment by raytiley** [comment]
Relevant: https://github.com/emberjs/ember.js/issues/11506

**Comment by rwjblue** [comment]
@raytiley - Yes, exactly, that issue was created to track this exact scenario.  I'm closing this in favor of #11506.
