### ISSUE TITLE
currentView in ContainerView is not set properly

### ISSUE THREAD

**Issue by yeelan0319** [emberjs/ember.js#11534]
Our applicationis utilizing [ember-animation](https://github.com/gigafied/ember-animate/blob/master/ember-animate.js) addon and upgrade to Ember 2.0 break the library for some reason - animate-out never triggered. The reason seems come from the following code snippet in ember-animation.

```Ember.observer('currentView', function () {...```

which observe the changes of the ```currentView``` property in ```ContainerView``` and keep tracking of the new/old view and swap them as user step between routes. At meantime, this is not limited to ember-animation but containerView as whole since ```containerView``` has the hook 

```_currentViewWillChange: mixin.beforeObserver('currentView', function() {``` 

as well. This works until Ember 1.10 and after 1.11 ```currentView``` in ContainerView is never set. 

The issue seems coming from this specific [commit](https://github.com/emberjs/ember.js/commit/e047a9129dfc3404bdbe3865fd2b0eef44ab53a0) in Feb by @ef4. This commit removed ```currentViewBinding``` and changed that to ```_outletName``` in ember.js/packages/ember-routing-htmlbars/lib/helpers/outlet.js, which later on when the view class got created, the ```connectBindings``` method find no streamBindings attr in outlet view. That seems to me is the reason for why currentView is never set properly. I wonder if this is a bug or it have some reason for doing so?

Also, I looked at the 1.12 documentation about [ContainerView](http://guides.emberjs.com/v1.12.0/understanding-ember/the-view-layer/#toc_container-views), it still talks about the ```currentView``` attribute, which make me believe that this is not silently deprecated. Hope I chased down the right path, is there any attribute that I can observe instead of ```currentView```?

This may should be a separate question but I noticed that this file got removed as 1.13 came out and Ember is deprecating View in general. However, we are so heavy relied on the original route-controller-view structure, we may still need to rely on the Ember.view addon until we completely switch to routable components. Could any one provide some best practice to move forward to that? Thanks!

**Comment by btecu** [comment]
Views are definitely deprecated you shouldn't use them in 2.0.
https://github.com/ef4/liquid-fire is the official library for animations.

**Comment by ef4** [comment]
ember-animation is overriding private methods on ContainerView, so without some reworking it is not going to work under 1.13.

> we are so heavy relied on the original route-controller-view structure, we may still need to rely on the Ember.view addon until we completely switch to routable components. Could any one provide some best practice to move forward to that? Thanks!

We are still shipping View support in [this addon](https://github.com/emberjs/ember-legacy-views) until Ember 2.4, for exactly the reason you describe.

**Comment by yeelan0319** [comment]
Thanks @ef4 @btecu for providing the official information:) At the moment being, it seems the maintainer of the repo is not actively pursuing toward ember 2.0 standard. I will go and checkout the repo to see if we can possibly switch all existing staff to liquid fire.

However, I understand the overhead concern for reopen view class to have animation method mandatorily as stefanpenner pointed out. However, we liked about ember-animation is it is right out of the box and can be directly plugged into our code without any modification.I wonder if liquid-fire have any plan to provide the out-of-box feature like ember-animation in the future? What's you take on it?

**Comment by btecu** [comment]
Actually @ef4 is the main maintainer of `liquid-fire`. Indeed, `liquid-fire` is very easy to use *out-of-box*.
https://www.youtube.com/watch?v=p8aF-7-_cE8

**Comment by ef4** [comment]
> However, we liked about ember-animation is it is right out of the box and can be directly plugged into our code without any modification.

You need to update your code to take advantage of either library, either by deriving from a new base class and adding animation methods, or by updating a template to include an animation-aware helper. liquid-fire generally requires only a single line change to your template, after which you can design whatever animation you wish without impacting any of your existing code or templates.

I realize that experienced Ember people who have been heavily micromanaging `View` code for a long time have become used to that way of thinking. I've done a lot of that myself. But there are very good reasons we are moving Ember away from that model and toward component composition. Any time you can split behavior out into separate components and then compose them in a template, it's a win for clarity and performance.

**Comment by yeelan0319** [comment]
@ef4 I looked at the liquid-fire repo, it looks awsome so I decide to switch to it for our application.

I got one specific question during implementation and hope you may give me some clue on how you may tackle with it.

We have our application.hbs like this:

```
{{#if controllers.authenticated}}
    /*sidebar that will only show when user is authenticated*/
{{/if}}
{{liquid-outlet}}
```

In this case, if user is not authenticated, the content of ```{{liquid-outlet}}``` will take up the whole page; When the user is authenticated, ```{{liquid-outlet}}``` will take the ```window.width - sidebar``` width. The original logic works as the controller runs before the view render. But when I tried to switch to liquid-fire, since the hook is on route, so actually the first time when sidebar got rendered, ```{{liquid-outlet}}``` is not aware that sidebar will be there.

Is it possible somehow to defer the animation until controller compute and put sidebar there before I run the animation?

**Comment by yeelan0319** [comment]
If View will be deprecated in ember 2.0, I have no problem closing this issue since it seems to me that containerView will be deprecated together with View. 

@ef4 I have opened a issue on iquid-fire about the above conversation and hope you may help me out with it. Great thanks in advance https://github.com/ef4/liquid-fire/issues/317

**Comment by rwjblue** [comment]
I am sorry that this has lingered for so long, and that we were unable to solve this issue in time.  At this point `Ember.ContainerView` has been removed which makes this issue obsolete. Again, I apologize that it has lingered so long.

However, I am going to go ahead and close this...
