### ISSUE TITLE
Something cause a view to be destroyed/recreated instead of 'just' updated 

### ISSUE THREAD

**Issue by sly7-7** [emberjs/ember.js#11530]
I'm trying to migrate from 1.11 to 1.13, and it seems like when using the deprecated `view` helper inside a component block leads to this view's controller property being set to the component instead of the right controller.
It seems like the underlying cause is that this is not the same instance of the view.
The first time a property changes on the view, the view is not simply updated, it is destroyed, and recreated, with the top component ancestor as the controller.

See http://emberjs.jsbin.com/yecanekefi/edit?html,output

An other jsbin to illustrate the fact that the view is destroyed/recreated instead of updated:

http://emberjs.jsbin.com/meyucu/1/edit?html,js,output

**Comment by sly7-7** [comment]
@mmun @stefanpenner ping ? Would you consider this as a regression, or maybe I can just close ?

**Comment by stefanpenner** [comment]
> Would you consider this as a regression

sounds like a regression

**Comment by sly7-7** [comment]
I'm currently trying to update to the actual release channel (1.13.5+), and I encounter more and more symptoms like that.
Now I have to pass the current controller on each `{{view}}` helper call.

**Comment by sly7-7** [comment]
It seems like when the view rerender, it's controller property is set to the top component ancestor of the view.

**Comment by sly7-7** [comment]
Hmm, it seems like the underlying cause is that this is not the same instance of the view. The first one has the right controller, but when something cause a revalidation, then the view is destroyed, and recreated, with the top component ancestor as the controller.

This has an other bad side effect, the first time you modify a property on the view, you can't rely on this modification, since the view is recreated, so the related property is set to its initial value.

**Comment by sly7-7** [comment]
Also, maybe related, sometimes the parentView is wrong too.

Migrating those legacy Ember.View (and {{view}}  helper) to Ember.Component resolves all the issues

**Comment by mmun** [comment]
I confirm this bug.

**Comment by aertmann** [comment]
I've also stumbled upon this issue, specifically the destruction/recreation where the ``parentView`` view changes from being the actual parent to the owner view. Solved it by skipping initialization of the view if the parent view isn't the same as the owner view and triggering a re-render, which would happen next time the view needed to be updated. After the first re-render the update works fine. So it's a dirty workaround on the path to migrating to components.

**Comment by flexoid** [comment]
@aertmann could you please provide any example on how did you solve it? We're stuck on the same issue

**Comment by aertmann** [comment]
@flexoid: it's nasty, but here you go https://gist.github.com/aertmann/5275ea97ae8f7e6aabee

**Comment by locks** [comment]
I am closing this as 2.x doesn't have views anymore. Thanks everyone for reporting and for the reproductions.
