### ISSUE TITLE
Unable to define a service function without warnings/errors being thrown

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/ember.js#11531]
I want to expose the `window` global variable as a service (just like angular exposes $window) to improve testability of the code (setting `window.location` in the middle of a test has obvious disastrous impacts).

Since Ember 1.13 all services are required to be extensions of `Ember.Service` (ie. `isServiceFactory` should be set to true).

I'd like to register the window variable as a service:
```js
container.register('service', 'window', window)
```
without worrying about potential deprecations.

Any recommendations?

**Comment by stefanpenner** [comment]
This is not something we support.

**Comment by olivierlesnicki** [comment]
Way to get around it is to use `unknownProperty()` and `setUnknownProperty()` hooks of the Ember object.
