### ISSUE TITLE
Query-params only Link-Tos do not update anymore when route/url change

### ISSUE THREAD

**Issue by juggy** [emberjs/ember.js#11533]
Please consider http://output.jsbin.com/vexeho#/no-model

You will see that if you change the route from "no-model" to "model" the 2 query-params route will not refresh to show the new route (it will still have a href with /no-model?a=).

In the previous version of Ember, it would update based on the current page/url.

**Comment by jmurphyau** [comment]
Can you provide a JSBin with an older version where you demonstrate this working?

I can see the 'a' query param is set on the ApplicationController - which is always active.. Seems like normal behaviour having a=[something] for each route.

**Comment by juggy** [comment]
Here a version with 1.10 http://output.jsbin.com/dixigo

You will see that the first link (params 1) href will update when you move from route to route (by clicking the bottom 2 links).

This is not the case with the version using ember 1.13:  http://output.jsbin.com/vexeho

**Comment by juggy** [comment]
Update bins:
canary: http://jsbin.com/vexeho/9/edit?html,js,output
with PR #11535 : http://jsbin.com/jutako/4/edit?html,js,output

You should compare against working 1.10 version:
1.10: http://jsbin.com/dixigo/3/edit?html,js,output

Thanks

**Comment by juggy** [comment]
@jmurphyau are you familiar with the code behind this? I would try to fix this, but I do not know where to start...

**Comment by jmurphyau** [comment]
The `targetRouteName` of the `LinkComponent` isn't getting updated when `_routing.currentState` changes..

In 1.10, there is logic between:

`if (onlyQueryParamsSupplied) {`
...
`else`
...
`}`

That runs every time the URL changes - in 1.13 this only gets run on `willRender` which is run once... 

I'm wondering if `willRender` is meant to be triggered, or if the solution is to call `this.rerender()`? Or is the solution just to fix `targetRouteName` not being tracked correctly on route changes? It feels to me like the component should be rerendered and `willRender` called (which looks like it would solve this problem)

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/11561.
