### ISSUE TITLE
[Ember 1.13.1]willDestroyElement never called

### ISSUE THREAD

**Issue by patricklx** [emberjs/ember.js#11539]
I know the view is deprecated, but shouldnt this still work anyway?

here is a jsbin showing the issue, just change to 1.12.1 to see it work
http://emberjs.jsbin.com/puconuxita/edit?html,css,js,console,output

**Comment by berdof** [comment]
Ember 1.13.2 bumped into the same issue

**Comment by caseyjenks** [comment]
same issue. anybody have any luck?

**Comment by rwjblue** [comment]
Updated JSBin: http://emberjs.jsbin.com/pijebi/edit?html,js,console,output

It doesn't seem like route backing views are actually destroyed at all.

**Comment by dfreeman** [comment]
Also running into this; it's blocking our upgrade to 1.13 :(

**Comment by berdof** [comment]
Any workaround or hotfixes?

**Comment by BlakeWilliams** [comment]
Since this breaks compatibility, can we get a point release for this?

**Comment by rwjblue** [comment]
The fix for this is already in the stable branch, and will be included in 1.13.3.

**Comment by BlakeWilliams** [comment]
Thanks for letting me know, looking forward to 1.13.3. :smiley:

**Comment by jcbvm** [comment]
Is there a release date for 1.13.3? I'm waiting for this fix to move some code to production, preferably next week.

**Comment by stefanpenner** [comment]
> Is there a release date for 1.13.3? I'm waiting for this fix to move some code to production, preferably next week.

typically we do a weekly release, there is a good chance towards the end of this weekend / early this week.

**Comment by rwjblue** [comment]
Confirm

**Comment by jcbvm** [comment]
Thanks
