### ISSUE TITLE
[REGRESSION] In 1.13.2 `{{#each}}` fails with duplicate values

### ISSUE THREAD

**Issue by seanpdoyle** [emberjs/ember.js#11549]
http://emberjs.jsbin.com/hedunosumi/edit?html,js,console,output

Might be a duplicate of https://github.com/emberjs/ember.js/issues/11504

has https://github.com/emberjs/ember.js/pull/11525 landed in `1.13.2` yet?

**Comment by seanpdoyle** [comment]
ping: @rwjblue @cibernox @toranb

**Comment by stefanpenner** [comment]
Seems like a duplicate

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/11525 added a 'useful' error (the error previously was super obtuse if you take a look at the same JSBin for 1.13.1). It does not fix the issue with duplicates in general. 

In theory we could continue to add prefixes (like the index and/or a guid) to the key until we get a unique value (therefore avoiding a collision), but that feels like a kludge to me. I could easily submit a PR for this if others think it would be useful in 1.13.x. 

The proper path forward is understood by @krisselden and @wycats but it is not completely clear to me.

**Comment by seanpdoyle** [comment]
Duplicate data in a list is common enough to require a `1.13.x` fix, isn't it?

**Comment by rwjblue** [comment]
@seanpdoyle - I am unsure, this is the first issue for it :smiley_cat:.  Also, my "fix" is mostly a hack (just continue fiddling with the `key` until it is unique), but the real fix upstream is almost certainly more involved and will require too many changes for us to be comfortable landing in 1.13.

**Comment by seanpdoyle** [comment]
@rwjblue I tried to get a failing test before submitting this issue, but I couldn't.

Which test would good to copy and alter? I've looked in `packages/ember-htmlbars/tests/helpers/each_test.js` but [this module](https://github.com/emberjs/ember.js/blob/6130fa62ba1c52788593367f3456a882025a673e/packages/ember-htmlbars/tests/helpers/each_test.js#L88) has `[DEPRECATED]` in the title.

**Comment by rwjblue** [comment]
Failing tests are here: https://github.com/emberjs/ember.js/blob/6130fa62ba1c52788593367f3456a882025a673e/packages/ember-htmlbars/tests/helpers/each_test.js#L1305-L1337

Those tests should both be changed from `throws` to asserting the proper output

**Comment by sly7-7** [comment]
I'm encountering this as well during 1.11 to 1.13 migration. Just to be sure, is using `key=@index` or `key=@guid` good workarounds for now ?
Also, it seems like 1.13.2 from ember-source gem is not up to date with the useful warning

**Comment by pixelhandler** [comment]
@stefanpenner this is preventing me from updating from 1.12.1 to 1.13.5.

I'm getting the same error `Error: Duplicate key found ('ember850') for '{{each}}' helper, please use a unique key or switch to '{{#each model key="@index"}}{{/each}}'` when upgrading from 1.12.1 to 1.13.5

**Comment by stefanpenner** [comment]
@pixelhandler does the advice in the error help you?

**Comment by stefanpenner** [comment]
I believe the plan to make this transparent may or may not be backported, as it has not yet been implemented.  @krisselden or @mmun can likely speak more clearly.

**Comment by pixelhandler** [comment]
I tried it but still had the same error. I tried in my smallest app, so maybe need to do that everwhere in my core library and all 3rd party code too. Seems like the deprecation cased an breaking error

**Comment by stefanpenner** [comment]
> Seems like the deprecation cased a breaking error

That isn't a deprecation

**Comment by pixelhandler** [comment]
@stefanpenner so API change to `#each` ?

**Comment by krisselden** [comment]
@pixelhandler the plan is to make it transparent with binning like in a hash map collision

**Comment by stefanpenner** [comment]
This should be made transparent for the 1.13.x, as it is clearly a breaking change.

**Comment by rwjblue** [comment]
The error suggests using the following in the case of a duplicate:

```hbs
{{#each things key="@index"}}
  {{! your stuff here }}
{{/each}}
```

**Comment by pixelhandler** [comment]
@rwjblue so confirm, a breaking change in 1.13.x, **must NOT use duplicates** when iterating over an array using `#each`.  And the fix is to do as the error suggests use `key="@index"` (or guid).

Can that be added to the blog post as a breaking change (we broke your apps, lol) ? http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html

**Comment by rwjblue** [comment]
@pixelhandler - Feel free to PR an update to the blog post, I would love to get this fixed for real in a point release of 1.13, but I do not have the expertise required to fix it.

**Comment by stefanpenner** [comment]
> @rwjblue so confirm, a breaking change in 1.13.x, must NOT use duplicates when iterating over an array using #each. And the fix is to do as the error suggests use key="@index" (or guid).

@pixelhandler IMHO this is a bug

**Comment by pixelhandler** [comment]
@krisselden @rwjblue @stefanpenner - To handle the error why not just create a unique id on the fly? 

@stefanpenner no the company I work for values privacy, can't share the app. That's why I tinker with my blog project so I do have code to share. In that project I was able to add the `key` as suggested, it's a tiny app. Some background is that we have a core library with a few other 2rd party libs as well. The core lib is imported as a gem and all the apps require the same template compiler now (since htmlbars) so deps are tightly coupled. The templates are compiled in the core lib and the apps using asset pipeline so my guess is that some things aren't getting unique ids? but can't repro in a jsbin.

**Comment by stefanpenner** [comment]
> @stefanpenner no the company I work for values privacy, can't share the app.

a reproduction does not need to be a full app, a JSBIN or isolated repo would be best. I honestly don't want to sift through someones app unless it has to be.

**Comment by pixelhandler** [comment]
To me it seems better to generate a unique id on the fly instead of throwing an error, maybe it's the inline compiler I don't know.

**Comment by stefanpenner** [comment]
> To me it seems better to generate a unique id on the fly instead of throwing an error, maybe it's the inline compiler I don't know.

this isn't related to the compiler. It is a runtime concern, the list-dffing takes into account some key to identify how the list changes over time.

**Comment by pixelhandler** [comment]
@stefanpenner @rwjblue I knew our apps would find a regression. how much test coverage does ember have?

**Comment by stefanpenner** [comment]
> @stefanpenner @rwjblue I knew our apps would find a regression. how much test coverage does ember have?

11,000 tests

I believe this was a known regression, I'm not sure why it was deemed tolerable, but that choice wasn't made by me.

**Comment by krisselden** [comment]
@pixelhandler the generated id may collide with a future key, if based on the dup, may collide with a future key.

**Comment by pixelhandler** [comment]
@krisselden so the use of a guid may still fail, ok then. I'll update all the things in the apps and core libs and see if that works.

**Comment by krisselden** [comment]
could do a hash of (dup key + index)

**Comment by pixelhandler** [comment]
@stefanpenner any possibility of adding blanket or other test coverage tools to ember projects?

**Comment by krisselden** [comment]
you want to try to get some reuse, and pick reuses that are unlikely to result it a massive amount of diffs

**Comment by pixelhandler** [comment]
@krisselden that sounds like it can work.

**Comment by stefanpenner** [comment]
> @stefanpenner any possibility of adding blanket or other test coverage tools to ember projects?

Would be a good addition. Maybe someone can contribute lcov output -> coverals via istunbul

Although, its worth noting that this scenario isn't a missed branch in some test.

**Comment by pixelhandler** [comment]
I guess a good exercise for this regression would be to right a failing test.

**Comment by rwjblue** [comment]
From https://github.com/emberjs/ember.js/issues/11549#issuecomment-115040484 (above):

> #11525 added a 'useful' error (the error previously was super obtuse if you take a look at the same JSBin for 1.13.1). It does not fix the issue with duplicates in general.

**Comment by stefanpenner** [comment]
@pixelhandler there already is a failing example, the provided JSBIN offers it.

Everyone is aware of this issue, solving it is just a function of available time.

**Comment by pixelhandler** [comment]
@stefanpenner I offer my Friday all day @rwjblue and you can tell me what do fix do, etc. I have time. I think the question is of priority not time, we all have the same 24 hrs.

**Comment by stefanpenner** [comment]
@pixelhandler https://github.com/emberjs/ember.js/issues/11549#issuecomment-123484444

**Comment by stefanpenner** [comment]
@pixelhandler you seem very motivated capably and eager to help, lets plan for a hangout friday morning. I would love to harness some of your availability and time.

**Comment by raytiley** [comment]
Could #11856 work for this?

**Comment by pixelhandler** [comment]
@stefanpenner just spoke with @mmun in slack he mentioned maybe looking into tonight.

**Comment by stefanpenner** [comment]
@raytiley that looks similar to a bucketing approach @krisselden was talking about. We should get him to weigh in, to be sure this exact approach is what he was thinking about. Or if it was more elaborate.

**Comment by pixelhandler** [comment]
@stefanpenner sounds good, I'll send you an invite for Fri morning. I like take larger blocks of time for offering help. during the week have football with the kids meetings with teams at work, Meetup w/ Ember at night, a wife, 5 kinds and 94 yr old grandpa at the house so I understand juggling priority. Ember.js is my 1st priority on Friday, all day (unless we have server burnt with fire at work).

**Comment by stefanpenner** [comment]
> Ember.js is my 1st priority on Friday, all day (unless we have server burnt with fire at work).

Understood, i'll be mindful of that. I suspect once everyone motivations/costs/availiabity is hashed out we can work in harmony.

**Comment by krisselden** [comment]
@stefanpenner my suggestion though is to do it inside yieldItem, in the current map use binning, this is duplicating already a seen that is also inside yieldItem.

**Comment by krisselden** [comment]
seen: https://github.com/tildeio/htmlbars/blob/05226993a4e75b9827dc9abec1ebc8f21031311f/packages/htmlbars-runtime/lib/hooks.js#L227

map that needs binning https://github.com/tildeio/htmlbars/blob/05226993a4e75b9827dc9abec1ebc8f21031311f/packages/htmlbars-runtime/lib/hooks.js#L221

**Comment by pixelhandler** [comment]
@stefanpenner for use we tried the work around with `@index` as the key and that didn't work for us, oh well.

**Comment by pixelhandler** [comment]
@stefanpenner yeah it wasn't a deprecation is was a warning but that was removed here https://github.com/emberjs/ember.js/releases/tag/v1.13.2

**Comment by rwjblue** [comment]
Those are unrelated concerns. The warning in versions prior to 1.13.2 was for when no key was specified. During 1.13.0/1 you would have received a very hairy error message from deep inside htmlbars. 

The error that instructs you how to recover was added in 1.13.3 (from #11525) and is intended as a stop gap measure to provide at least a small amount of insight into the cause of the error that was happening in 1.13.0/1/2.

**Comment by stefanpenner** [comment]
Wooohoo. The magic of @mmun

**Comment by pixelhandler** [comment]
@rwjblue, @stefanpenner @mmun - Thanks for fixing the regression! So will this be in a patch release (v1.13.6) soon?

**Comment by rwjblue** [comment]
Yes, it will be in the next patch release.  "soon" is relative though :dancers:

**Comment by pixelhandler** [comment]
@rwjblue just curious for those of us with broken apps and blocked from upgrading to 1.13.x why what for a patch? What's the workaround use master branch? or just wait?

**Comment by stefanpenner** [comment]
@pixelhandler building ember is documented here: https://github.com/emberjs/ember.js/#building-emberjs

**Comment by krisselden** [comment]
@stefanpenner if it was backported to stable, it would be published to the release channel http://emberjs.com/builds/#/release

**Comment by stefanpenner** [comment]
> @stefanpenner if it was backported to stable, it would be published to the release channel http://emberjs.com/builds/#/release

ah, even unreleased but merely backported commits, Correct?

**Comment by pixelhandler** [comment]
@rwjblue I’m curious… the release version of ember on the website has `@version 1.13.5+4eb55108` in the source (ember.debug.js) and the release page says updated 2 days ago, the tag in the repo for 1.3.5 (95d42b8) was made 8 days ago.

What does that mean? Is there non-patch release code in the release?

So, I guess since this issue blocks me from upgrading to 1.13.5 I need to build from source? and manage my own fork (if there is something in the future that is back ported)?

Can someone tell me when I can expect an official release on the 1.13.x series that has this regression patched?

I'm really happy it's fixed but extremely bummed that it's not released. Am I missing something? I guess I was under the impression that a patch release was warranted from this regression (breaking 1.x) in 1.13

**Comment by stefanpenner** [comment]
* the big buttons (download 1.13.5) are for the tagged release
the list of builds bellow are (to quote the website) 

> The builds listed below are incremental improvements made since 1.13.5 and may become 1.13.6.

**Comment by rwjblue** [comment]
@pixelhandler:

>the release version of ember on the website has @version 1.13.5+4eb55108 in the source (ember.debug.js) and the release page says updated 2 days ago, the tag in the repo for 1.3.5 (95d42b8) was made 8 days ago.

> What does that mean? Is there non-patch release code in the release?

Every commit to `stable`, `beta`, and `master` branches are published to both S3 and bower.  You can use those builds at any time, no need to wait for a tagged release.  

The builds page (as you discovered) shows the asset paths for these, feel free to use them (they are quite literally what will become the next tagged version).  The release channel builds are generally always more up to date than the last tag.

> So, I guess since this issue blocks me from upgrading to 1.13.5 I need to build from source? and manage my own fork (if there is something in the future that is back ported)?

Nope. The builds that you have already discovered include the patch you want.  Feel free to use them :wink:.

> Can someone tell me when I can expect an official release on the 1.13.x series that has this regression patched?

Ember 1.13.6 will be the version that includes this regression fix.  It will be released when it is done.

> I'm really happy it's fixed but extremely bummed that it's not released.

It is available to use via the channel that you have already checked!

**Comment by stefanpenner** [comment]
We may have a UX issue here on the builds place (i was also confused), if someone is interested in pursuing it likely a discussion on the website repo is appropriate.

**Comment by pixelhandler** [comment]
@rwjblue ah that makes sense now our team did need clarity on…

> The builds listed below are incremental improvements made since 1.13.5 and may become 1.13.6

Thanks we'll get started with the latest 'release' channel update. :)

**Comment by stefanpenner** [comment]
> Thanks we'll get started with the latest 'release' channel update. :)

awesome, keep us posted!
