### ISSUE TITLE
Component computed properties can get clobbered

### ISSUE THREAD

**Issue by raytiley** [emberjs/ember.js#11542]
http://emberjs.jsbin.com/rihoxu/edit?html,js,output

Not sure exactly what is going on here because `set` is being called, but if you look at the template logs of the above jsbin the `extentions` property which should be an array is not the array value it should be but a string.

The clobbering ideas is @stefanpenner, just reporting the behavior I'm seeing in an addon running canary.

**Comment by mixonic** [comment]
@raytiley I believe this is related to https://github.com/emberjs/ember.js/pull/11225?

**Comment by raytiley** [comment]
@mixonic possibly? Although in myjsbin the computed is being consumed in the layout of the component which is internal correct? not sure how that relates?

**Comment by stefanpenner** [comment]
cc @tomdale @wycats

**Comment by tim-evans** [comment]
Any updates on this?

**Comment by stefanpenner** [comment]
@tim-evans sorry not yet

**Comment by tim-evans** [comment]
Okie dokey! Thanks for the quick response

**Comment by tim-evans** [comment]
Politely poking this. I would like users of https://github.com/paddle8/ember-plupload/issues/25 not to have to deal with having to understand this.

**Comment by rwjblue** [comment]
The latest release in all three channels seem to be working properly (or I am not understanding what the actual bug is :stuck_out_tongue: ):

1.13.7 -> http://rwjblue.jsbin.com/doraco/1/edit?html,js
2.0.0-beta.5 -> http://rwjblue.jsbin.com/doraco/2/edit?html,js
canary -> http://rwjblue.jsbin.com/doraco/3/edit?html,js

Will reopen if someone explains what I am missing :smiling_imp: ...

**Comment by tim-evans** [comment]
Tests now pass. Thanks for the confirmation :+1:

**Comment by rwjblue** [comment]
Please let me know if you think this should be reopened...

**Comment by tim-evans** [comment]
They're all things I needed to fix. Was there any deprecations for `findProperty`, `filterProperty`, etc? I seemed to have missed those when getting to 1.13

**Comment by tim-evans** [comment]
Thanks for the quick feedback :)

**Comment by rwjblue** [comment]
@tim-evans not sure, they should have been deprecated but it is possible it only happened in a late 1.13.x version (and not 1.13.0 itself).
