### ISSUE TITLE
Ember.set chaining removal needs to be blog posted about

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#11541]
cc @mixonic did we cover this?

**Comment by rwjblue** [comment]
@stefanpenner - There is a pending issue in the website repo (https://github.com/emberjs/website/issues/2212).

**Comment by rwjblue** [comment]
Maybe we need to open our "usual" locked issue for tracking the contents of the upcoming release blog post?

**Comment by stefanpenner** [comment]
@rwjblue c
