### ISSUE TITLE
Missing ember-data URL conventions for hyphenated model names

### ISSUE THREAD

**Issue by diogoko** [emberjs/ember.js#11548]
The [documentation for ember-data's URL conventions](http://guides.emberjs.com/v1.12.0/models/the-rest-adapter/) has examples for single-worded model names, but there is no example for multi-worded, hyphenated names (like "[admin-user-profile](http://guides.emberjs.com/v1.12.0/models/defining-models/)"). AFAIK, the URL is camelCased (eg: /adminUserProfile/123).

**Comment by rwjblue** [comment]
@diogoko - Can you open this as an issue on the https://github.com/emberjs/guides repo instead?
