### ISSUE TITLE
Cannot test component with yield block

### ISSUE THREAD

**Issue by mmahalwy** [emberjs/ember.js#11557]
Currently tried on ember 2.0.0.beta-1 and 1.13.2: 

I cannot get the compiled html to be inputted into the component via the yield block expression. See test:
```
import { moduleForComponent, test } from 'ember-qunit';

moduleForComponent('pro-tab-link', 'Unit | Component | pro tab link', {
  // Specify the other units that are required for this test
  // needs: ['component:foo', 'helper:bar'],
  unit: true
});

test('it renders', function(assert) {
  assert.expect(3);

  // Creates the component instance
  var component = this.subject({
    template: Ember.Handlebars.compile(
      "<h1>Hello world</h1>"
    )
  });

  console.log(component);
  assert.equal(component._state, 'preRender');

  var $component = this.append();

  Ember.run(function() {
   component.set('isOpen', true);
 });

  console.log(component);
  console.log($component.html());

  assert.equal(component._state, 'inDOM');
  assert.ok(component.isOpen);
});
```
And the template:
```
if isOpen
  == yield
```
For some reason, the h1 tag is not being passed into the yield of the component. How do I get this working? This is also missing from the docs for 1.11 and 1.12 but present in 1.10.

**Comment by mmahalwy** [comment]
I dug into things a little more and realized this too:
In the docs:
https://github.com/emberjs/ember.js/blob/v1.13.0/packages/ember-views/lib/views/view.js#L486

Where I tried in my test:
```
var component = this.subject({
Ember.Handlebars.compile("<div class='my-decorative-class'>{{yield}}</div>"),
    template: Ember.Handlebars.compile("I got wrapped")
  });
```

Resulted to: 
```
<div class="my-decorative-class"><!----></div>
```

**Comment by stefanpenner** [comment]
> unit: true

`integration: true`

**Comment by mmahalwy** [comment]
@stefanpenner I then get error: 
```
Error: component integration tests do not support 'subject()'.
```

**Comment by stefanpenner** [comment]
if your using a component, use an integration test

**Comment by mmahalwy** [comment]
how do i resolve `subject()` error?

**Comment by rwjblue** [comment]
`this.subject` is not used with component integration tests.

See https://github.com/yapplabs/ember-radio-button/blob/master/tests/unit/components/radio-button-test.js#L10-L25 for an example of the newer component integration test syntax.

**Comment by mmahalwy** [comment]
@rwjblue thanks for getting back to this so quickly and the reference. I found this to be a great blog about this for anyone else who stumbles upon this: http://alisdair.mcdiarmid.org/2015/06/20/ember-component-integration-tests.html

But what I still have confusion with (and excuse my ignorance with Ember, still learning) is when to decide on a unit test vs integration test, and more specifically for a component?

I think the general rule of thumb I have now is 'if it uses yield, integration' but when do I choose or let alone, when should I do both? 

Thanks!

**Comment by rwjblue** [comment]
@mmahalwy - For components, I would suggest using the new style integration tests for nearly all scenarios.
