### ISSUE TITLE
[REGRESSION] In Ember 1.13.0+ initial literal values of component attributes cannot be updated

### ISSUE THREAD

**Issue by OrKoN** [emberjs/ember.js#11559]
See jsbin http://emberjs.jsbin.com/likiqofaxa/1/edit?html,js,console,output

If you pass a literal as an attribute value, the component cannot update it:

```handlebars
    {{my-component test="initial-value"}}
    {{my-component}}
```

where MyComponent is

```
var MyComponent = Ember.Component.extend({
  test: null,
  init: function() {
    this._super();
    this.set('test', 'updated');
  }
});
```
The first does not work(`test` is not updated in the component template) and the second works as expected.

I am migrating from 1.12. jsbin http://emberjs.jsbin.com/tuhisokijo/1/edit?html,js,console,output

**Comment by stefanpenner** [comment]
i would assume:

```js
this.set('test', this.get('test') || 'updated');
```

would be the way to deal with defaults in `init`

**Comment by OrKoN** [comment]
@stefanpenner the problem is that one cannot override the defaults

**Comment by rwjblue** [comment]
Submitted https://github.com/emberjs/ember.js/pull/11572 to address this.

**Comment by OrKoN** [comment]
@rwjblue Thanks a lot! Will the fix appear in the 1.13.3 release? When may I expect it?

**Comment by rwjblue** [comment]
Yes, it will be in 1.13.3 (should be out in a day or two).

**Comment by OrKoN** [comment]
@rwjblue @stefanpenner This is happening again in Ember 2.1.0 (regression compared to 2.0.2) http://emberjs.jsbin.com/yinuqe/edit?html,js,console,output

**Comment by rwjblue** [comment]
@OrKoN - Can you open a new issue?

**Comment by OrKoN** [comment]
@rwjblue sure, opened a new one
