### ISSUE TITLE
Chains: Uncaught TypeError: Cannot read property 'willChange' of undefined

### ISSUE THREAD

**Issue by ilkkao** [emberjs/ember.js#11564]
After https://github.com/emberjs/ember.js/pull/11536 I'm seeing `TypeError: Cannot read property 'willChange' of undefined` error

![image](https://cloud.githubusercontent.com/assets/474587/8384621/7f60b336-1c42-11e5-8b17-bc9eb1ad5747.png)

I added the if and debugger statement to catch the error just before it happens. Is there a problem in the new logic? I'll try to debug this further.

@stefanpenner

**Comment by stefanpenner** [comment]
already fixed https://github.com/emberjs/ember.js/pull/11558

**Comment by ilkkao** [comment]
I only checked the issues, not PRs. My bad. I think I'm not familiar enough yet with ember unit tests and chaining implementation to add test right now unfortunately.

**Comment by rlivsey** [comment]
I'm still seeing this in latest Canary, will see if I can reduce it down to something reproducible.

It looks like #11558 [guarded in `didChange`](https://github.com/emberjs/ember.js/blob/9c52115bf3a2f20bf560dfe8b7b5d26aa1e8372c/packages/ember-metal/lib/chains.js#L358-L362) but [didn't touch `willChange`](https://github.com/emberjs/ember.js/blob/9c52115bf3a2f20bf560dfe8b7b5d26aa1e8372c/packages/ember-metal/lib/chains.js#L290-L294), does the same check need to be done there too?

Similar stack trace to the original report:

```
ChainNode.willChange (ember.debug.js:12816)
chainsWillChange (ember.debug.js:18177)
propertyWillChange (ember.debug.js:18027)
set (ember.debug.js:18562)
exports.default._emberMetalMixin.Mixin.create.set (ember.debug.js:32661)
(anonymous function) (indexed.js:158)
```

**Comment by rwjblue** [comment]
Yes, it seems reasonable that if we guard in didChange we should also guard in willChange. 

@stefanpenner - Any objections?

**Comment by stefanpenner** [comment]
Also appears reasonable feel free to add a todo to my pr

**Comment by rwjblue** [comment]
@stefanpenner - Your PR was closed when we merged the AC/RC PR (since that commit was on the branch).

**Comment by stefanpenner** [comment]
> rwjblue deleted the stefanpenner:only-invoke-still-present-chain-entries branch a day ago

**Comment by rwjblue** [comment]
Yes, I closed the duplicate PR. https://github.com/emberjs/ember.js/commit/9c52115bf3a2f20bf560dfe8b7b5d26aa1e8372c Is already in master.
