### ISSUE TITLE
ArrangedContent can re-add item even after the item is removed from the source array

### ISSUE THREAD

**Issue by Taytay** [emberjs/ember.js#11567]
If you make a change to the sortProperty of an ArrayController, while in a `beginPropertyChanges/endPropertyChanges` block, and then remove the modified item from the source array, after calling `endPropertyChanges`, the item can reappear in the ArrayController, even though it is no longer in the source array.

Link to JSBin of the following example: http://emberjs.jsbin.com/pohowuzupu/3/edit?js,console
```
songs = [
  Ember.Object.create({trackNumber: 4, title: 'Ob-La-Di, Ob-La-Da'}),
  Ember.Object.create({trackNumber: 2, title: 'Back in the U.S.S.R.'}),
  Ember.Object.create({trackNumber: 3, title: 'Glass Onion'}),
];

songsController = Ember.ArrayController.create({
  model: songs,
  sortProperties: ['trackNumber'],
  sortAscending: true
});

Ember.beginPropertyChanges();

var backInUSSR = songs[1];

// Set something to fire the trackNumber change event
backInUSSR.set('trackNumber',5);
// Now remove the item from the collection
songs.removeAt(1);

// Cool - the array controller heard about that change, and correctly removed the item:
console.log('After removing "Back in the U.S.S.R", controller has ' + songsController.get('length') + ' items (as expected)');

// But now we're going to fire any pending changes:
Ember.endPropertyChanges();

console.log('After calling endPropertyChanges:');
// Woah - the item reappeared in our arrangedContent array! That shouldn't have happened!
console.log('songsController length: ' + songsController.get('length')); // 3
console.log('songs length: ' + songs.length); // 2
// USSR appeared in our array controller even though it's not in the original array!
console.log('The last item in the songsController is: ' + songsController.get('lastObject.title')); // Back in the U.S.S.R
```

This is happening for two reasons.

Firstly, when the property gets changed, the change event is not fired, but queued, because we are currently deferring property change events (due to the `beginPropertyChanges` call).
Then, when the item is removed from the source list, this code runs:
https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/mixins/sortable.js#L237
```
 removeObserver(item, sortProperty, this, 'contentItemSortPropertyDidChange');
```

However, removing the observer does NOT remove the queued event, so the array is still going to hear about the property change when we call `endPropertyChanges`.

So then this code runs:
https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/mixins/sortable.js#L272-L284
```
  contentItemSortPropertyDidChange(item) {
    var arrangedContent = get(this, 'arrangedContent');
    var oldIndex = arrangedContent.indexOf(item);
    var leftItem = arrangedContent.objectAt(oldIndex - 1);
    var rightItem = arrangedContent.objectAt(oldIndex + 1);
    var leftResult = leftItem && this.orderBy(item, leftItem);
    var rightResult = rightItem && this.orderBy(item, rightItem);

    if (leftResult < 0 || rightResult > 0) {
      arrangedContent.removeObject(item);
      this.insertItemSorted(item);
    }
  },
```

and `arrangedContent.indexOf(item)` is -1, which means that the item isn't even in our arrangedContent anymore, but the code continues anyway to see if the item has "moved", and if the item is found to be sorted after the 0th element in the list of `arrangedContent`, it actually gets inserted, thus reappearing in the arrangedContent array.

Proposed fixes:
1) Make calls to `removeObserver` remove even calls that are currently queued. I believe that this would be the safest change, as an object shouldn't expect to hear about changes after it's stopped listening to that object.
2) In this particular case, simply early out of this function by adding the following line:
```
  contentItemSortPropertyDidChange(item) {
    var arrangedContent = get(this, 'arrangedContent');
    var oldIndex = arrangedContent.indexOf(item);
    if (oldIndex < 0) return;
    //...
```

**Comment by Taytay** [comment]
We have monkey patched this on our side, and I can verify that this line, as suggested above, works:
`if (oldIndex < 0) return;`

**Comment by stefanpenner** [comment]
FYI: ArrayController / Sortable are deprecated. Please transition to just a CP and array.sort`
