### ISSUE TITLE
ensure beforeObserver is deprecated

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#11565]
1.13

- [ ] internals should refer to _beforeObserver until its entirely removed.

**Comment by stefanpenner** [comment]
@cibernox got a sec to help transition internal usages + deprecate public? This seems related to the controller extraction.

**Comment by cibernox** [comment]
I already renamed this in this commit: https://github.com/cibernox/ember.js/commit/b30a7e58379cc504047f3e132b4bb64b503ed3a2

Are you suggesting to do that in a standalone PR?

**Comment by stefanpenner** [comment]
> Are you suggesting to do that in a standalone PR?

nope, just in addition we need to deprecate the public api's

**Comment by cibernox** [comment]
I'll do that when npm ends over tethering (read: tomorrow afternoon most likely)

**Comment by stefanpenner** [comment]
> I'll do that when npm ends over tethering (read: tomorrow afternoon most likely)

:(

**Comment by cibernox** [comment]
Apparent;y 90 minutes was enough: https://github.com/cibernox/ember.js/commit/8e37c677454f64565a08bf8da3a64ff6d18acb6e

**Comment by stefanpenner** [comment]
@cibernox is that commit attached to a PR?

**Comment by cibernox** [comment]
@stefanpenner It was attached to the PR removing arrayControllers, but I've extracted it to a separate one: https://github.com/emberjs/ember.js/pull/11671

**Comment by stefanpenner** [comment]
Thanks. I think we can get both pr in asap
