### ISSUE TITLE
No docs/guides about {{component}}

### ISSUE THREAD

**Issue by XrXr** [emberjs/ember.js#11568]
I ran into a case where using `{{component}}` was really useful recently. However I didn't know that it *existed* until I had implemented quite a bit of code with `{{partial}}` and bundling logic from (what should of been in) multiple component into one.

It's a great feature, it should really be part of the guide. Either under the "component" section or the "Rendering with Helpers" article, or both.

I think the feature has been available since [Ember 1.11.0](https://github.com/emberjs/ember.js/releases/tag/v1.11.0). Since Ember.View and friends are now deprecated in 1.13, {{component}} is even more useful and important! ([example](http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#comment-2079491525))

Are there plans for writing up a guide about it from the core team? If not I can make something :)

**Comment by joeruello** [comment]
Guides work is happening over at https://github.com/emberjs/guides. Feel free to make a PR.

**Comment by trek** [comment]
Closing. As @joeruello mentions, there is a guides repo for this issue
