### ISSUE TITLE
Acceptance testing - fillIn() helper does not support modals

### ISSUE THREAD

**Issue by rafaltrojanowski** [emberjs/ember.js#11562]
It seems to be fillIn() input is not possible when we have opened modal

![zrzut ekranu 2015-06-26 o 18 09 03](https://cloud.githubusercontent.com/assets/1567767/8381819/703abb5e-1c2e-11e5-8f07-52ac0ff5913e.png)

```
test("Allow add project with project system", function(assert) {
  assert.expect(1);

  authenticateSession();

  visit('/projects/');

  TestHelper.handleFindAll('workspace', 1);
  TestHelper.handleFindAll('project', 1);

  andThen(function() {
    assert.equal(find('.add-project-button').length, 1, "Page contains add project button");
  });

  var modalClick = find('.add-project-button')

  click('.add-project-button');

  waitForModalOpen(modalClick);

  andThen(function() {
    assert.equal(find('.modal-fade').length, 1, "We opened modal");
  });

  $('.modal-fade').focus(function() {
    console.log('If you see this, the focus event was triggered!')
    // fillIn('.project-system-select', 'with some project system');
    click('.button-primary');
  });

  fillIn('.project-input', 'New project');

  andThen(function() {
    assert.equal(find('.modal-fade').length, 1, "we have error");
  });
});
```

**Comment by MichaelVdheeren** [comment]
I have a similar issue, but only when running the tests in chrome. If I run them headless with phantomJS all is well. I don't know if it is the result of a modal because when adding a debugger statement in between it fills in the text perfectly. I guess it has something to do with run loops or rendering

**Comment by MichaelVdheeren** [comment]
@rwjblue I suspect this has also something todo with how TextField is implemented. When I replace my `{{input ...}}` with `<input >` statements all is just fine. Would this be somehow related to #11553 as well?

**Comment by praxxis** [comment]
@MichaelVdheeren @rafaltrojanowski random question, but do your issues go away when you run the tests in Ember `1.13.0-beta.2`? I'm seeing what might be a similar problem and think I've tracked it down to https://github.com/emberjs/ember.js/commit/456fdcbed7e407c35d957d4fa31e4f9a2ecd076d, which was added between beta 2 and GA.

**Comment by locks** [comment]
Hi, is this issue still valid?

**Comment by rwjblue** [comment]
Going to close for now. Happy to reopen if it's still an issue with 2.4 / 2.5...
