### ISSUE TITLE
Test suite ignores JSHint and JSCS errors in some files

### ISSUE THREAD

**Issue by ef4** [emberjs/ember.js#11574]
If you introduce a JSHint or JSCS failure into any of the `packages/*/lib/main.js` files, you will see it in the console but the test suite will still pass.

I noticed because there is a jshint failure in `packages/ember-metal/lib/main.js`.

**Comment by rwjblue** [comment]
Yes, 'package/*/lib/main.js' files are hinted to the console, but will not fail the build. This is due to globs used in emberjs-build for test file inclusion (we match thing/**/*.js but the main files end up as thing.js).

**Comment by rwjblue** [comment]
The main files have been moved to index.js files (and the loader falls back to index.js).

I believe this issue is resolved.
