### ISSUE TITLE
Is there a way to render a component instance?

### ISSUE THREAD

**Issue by QuantumKing** [emberjs/ember.js#11573]
Is it possible to achieve something like this?

```js
// app/controllers/index.js
Ember.Controller.extend({
  myComponent: Ember.Component.extend({})
});
```
```hbs
{{! app/templates/index.hbs }}
{{component myComponent}}
```

I can't find it in the documentation. It used to be possible using views.

**Comment by stefanpenner** [comment]
https://github.com/emberjs/ember.js/pull/10093

**Comment by QuantumKing** [comment]
I'm sorry, I don't see where my example comes up.

**Comment by QuantumKing** [comment]
Ok, so it's not possible from what I'm reading. What's the correct way of achieving something like this?

**Comment by csantero** [comment]
@QuantumKing https://github.com/emberjs/rfcs/pull/64 might be what you're looking for.

**Comment by rwjblue** [comment]
Component helper requires components to be looked up in the container (and does not allow locally defined components to be accessed). 

You should take a look at https://github.com/emberjs/rfcs/pull/64, which proposes a solution similar to your example code.

**Comment by rwjblue** [comment]
Closing this in favor of the RFC...

**Comment by chadian** [comment]
Hi,

Was just curious if this ever made it in? I've been trying to setup something twiddle with ember canary that would let me do something described by this issue. I've followed these references in trying to get this to work:
  [1]: https://github.com/emberjs/rfcs/pull/64
  [2]: https://github.com/emberjs/ember.js/pull/12285
  [3]: http://emberjs.com/blog/2015/11/16/ember-2-2-released.html#toc_contextual-components
  [4]: https://github.com/emberjs/ember.js/blob/04ec1c639e3ac7aa93ec24bf7fcf35e18c62fed6/packages/ember-htmlbars/lib/keywords/component.js#L52-L73

Both `{{component refToComp}}` and `{{refToComp}}` from something like:
```
import someComponent from 'someComponent';
export default Ember.Component.create({
  refToComp: someComponent.create({ changingDefaultProp: 'changed value' }) 
})
```
hasn't worked out for me.

Any guidance is greatly appreciated, thanks!

**Comment by rwjblue** [comment]
@chadian - Looks like you are mostly describing the new (in 2.3) contextual components feature.  You might want to check out the 2.3.0-beta blog post for details...
