### ISSUE TITLE
Component attributes shadow properties

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/ember.js#11571]
### JSBin

http://emberjs.jsbin.com/fuvozo/1/edit?html,js,output

### Summary

If a component takes in a property, `foo` and changes it (say, in `didReceiveAttrs`), then the component's template will see the original value.

**Comment by OrKoN** [comment]
@jamesarosen is it the same/similar issue https://github.com/emberjs/ember.js/issues/11559 ?

**Comment by rwjblue** [comment]
@OrKoN - Yes, they seem related.

**Comment by rwjblue** [comment]
Submitted https://github.com/emberjs/ember.js/pull/11572 to address this.
