### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by sandstrom** [emberjs/ember.js#11590]
There are a few stale branches. Although it's not a major nuisance, it would be cleaner to have (most of) them removed. Easier to browse the list of branches, better CLI auto-completion of remote branches, etc.

https://github.com/emberjs/ember.js/branches/stale

I'd also guess that nowadays people with commit bit mostly work on branches in forks, instead of directly on origin.

*Feel free to close this issue at will.*

**Comment by stefanpenner** [comment]
I'll delete the ones I created. We should double check with the authors before deleting the branches. Although I suspect most of them will be fine to delete

**Comment by stefanpenner** [comment]
* added this to the meeting agenda
* suggesting contributors cleanup there own branches
* removed my own stale branches

**Comment by stefanpenner** [comment]
most of them have been removed, I have pinged the last few (4 branches remain) owners

**Comment by stefanpenner** [comment]
thanks for bringing this to our attention.

**Comment by sandstrom** [comment]
Awesome! :boat:
