### ISSUE TITLE
[Bug] Additional attributeBindings on LinkView do not work as of 1.13.0

### ISSUE THREAD

**Issue by truenorth** [emberjs/ember.js#11593]
If developers wish to add attributes to their anchor tags, beyond the standard set supported by ember out of the box, 

```hbs
{{link-to "My link" "index" data-activates="activate-me"}}
```
the advised approach is something like this

```js
  Ember.LinkView.reopen({
    attributeBindings: ['data-activates']
  });
```

This approach [works in ember 1.12.x](http://emberjs.jsbin.com/vakiteritu/2/edit?html,js,output) but [does not in 1.13.x](http://emberjs.jsbin.com/sitoqoxulo/1/edit?html,js,output). This is due to the replacement of `LinkView` with `LinkComponent`.

My proposed fix is something like

```js
Ember.LinkView.reopenClass({
  reopen: function () {
    Ember.LinkComponent.reopen.apply(Ember.LinkComponent, arguments);
  }
});
``` 
which [seems to work](http://emberjs.jsbin.com/benebeheze/1/edit?html,js,output).

I'm happy to work on a PR once I get the "go ahead" on this approach

**Comment by ef4** [comment]
This seems like an acceptable way to provide backward compatibility. It looks a little WAT, but since accessing LinkView is already deprecated, I'm ok with it.

:+1:

**Comment by adentranter** [comment]
Is there a reason this can't be used for adding the 'onclick'?

[Example](http://emberjs.jsbin.com/dihodawage/edit?html,js,output)
