### ISSUE TITLE
Problem with classNames given to a component in a template (duplicates in DOM)

### ISSUE THREAD

**Issue by fpauser** [emberjs/ember.js#11600]
See http://jsbin.com/humehu/edit?html,js,output

Expected DOM:
`[..] class="ember-view test-comp test-comp-big" [..]`

Generated DOM:
`[..] class="test-comp-big ember-view test-comp test-comp-big" [..]`

**Comment by stefanpenner** [comment]
can confirm canary also fails: http://jsbin.com/funovotegi/edit?html,js,output

**Comment by fpauser** [comment]
Added a failing-test: #11609

**Comment by stacylondon** [comment]
I'm using 1.13.7 and not only am I seeing the class output twice, the 2nd is being output with a space between every letter.  Here is a jsbin for reference:  http://emberjs.jsbin.com/tiruwo/edit?html,css,js,output.  I would also expect the special-class case to include ember-view but it doesn't (additive, not completely replace).

**Comment by rwjblue** [comment]
This was fixed by https://github.com/emberjs/ember.js/pull/12073 and released in 1.13.8.

**Comment by stacylondon** [comment]
Thanks!  I updated my jsbin to point to 1.13.8 and the issue with spaces in between letters is fixed as well as the class names not being additive.  However, "special-class" is still being output twice.  http://emberjs.jsbin.com/tiruwo/edit?html,css,js,output

**Comment by rwjblue** [comment]
I vaguely think that there is another open issue for duplicated classes (but can't search ATM).  Can you double check, and open one if you can't find it?

**Comment by stacylondon** [comment]
Will do, thanks!

**Comment by stacylondon** [comment]
Didn't see anything that looked related so opened https://github.com/emberjs/ember.js/issues/12146.
