### ISSUE TITLE
AVG detected a virus

### ISSUE THREAD

**Issue by Dan503** [emberjs/ember.js#11607]
I seriously doubt You guys put a virus in your code. You seem far too legit for that. When I had my monthly scan though it came back with this:

<img src="http://grabilla.com/05701-e062f3e4-6e68-43fb-a8e4-ff02488201b7.png" alt="virus found"/>

I thought you guys should know.

**Comment by rwjblue** [comment]
This has identified [esperanto](https://github.com/esperantojs/esperanto) (one of Ember CLI's dependencies), would you mind opening an issue over there?

**Comment by stefanpenner** [comment]
lol, this really isn't a virus.
