### ISSUE TITLE
Ember router doesn't know that it's without router.router while testing.

### ISSUE THREAD

**Issue by nathanhammond** [emberjs/ember.js#11610]
This line interacts very oddly in our 1.13 (release channel edge) testing:
https://github.com/emberjs/ember.js/blob/master/packages/ember-routing-views/lib/views/link.js#L269

The `get` call fails with the `obj` in that call being `undefined` (nonsensically, it's clearly being passed in). However, if I change it to:
```js
var routing = get(this, "_routing") || this._routing;
```

... then it works. This seems counter to failure modes I'm familiar with in Ember. Error message is (since `routing` isn't set for the subsequent `get` call): "Assertion Failed: Cannot call get with 'targetState' on an undefined object."

(Posting this primarily for search engines.)

**Comment by nathanhammond** [comment]
[Here's the minimalist reproduction.](https://github.com/nathanhammond/flippyfloppy) I'll be tracing this tomorrow.

**Comment by nathanhammond** [comment]
Original report is a collection of symptoms from just one problem. The issue is simply this: [the container set up for testing doesn't resolve for `service:-router`.](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/injected_property.js#L31)... which means that this is `undefined` and results in a collection of failures depending upon where you were when you tried to grab the router.

Haven't decided how best to fix this, just documenting.

**Comment by rwjblue** [comment]
@nathanhammond - [these lines](https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/application.js#L1062-L1064) ensure that the default built registry contains `service:-routing`, and https://github.com/switchfly/ember-test-helpers/pull/49 (which is incorporated into ember-qunit@0.4.0) ensures that the registry contains all of these default items.  Are you using ember-qunit@0.4.0?

**Comment by nathanhammond** [comment]
Still an error moving to ember-qunit@0.4.0, just a different one. :) I've updated all dependencies to their latest versions in the [minimal reproduction](https://github.com/nathanhammond/flippyfloppy).

[emberRouter.router is `undefined` here.](https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/router.js#L873)

Untraced at this point, will continue to look...

**Comment by nathanhammond** [comment]
Two issues:
- #11522 never made it into the 1.13 branch. Compare [master](https://github.com/emberjs/ember.js/blob/master/packages/ember-routing-views/lib/views/link.js) to [stable](https://github.com/emberjs/ember.js/blob/stable/packages/ember-routing-views/lib/views/link.js). @rwjblue I don't know the build magic to fix that or if I should just submit an identical PR to the stable branch.
- We need to add [router.setupRouter();](https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module.js#L224) here.

**Comment by nathanhammond** [comment]
[Open cherry-picked PR.](https://github.com/emberjs/ember.js/pull/11639)

**Comment by rwjblue** [comment]
#11522 was not targeted for release branch, and we do not want to start routing for integration tests. With the latest beta builds, you should be able to use a {{link-to}} in your ember-qunit integration tests without calling 'startRouting'.

**Comment by nathanhammond** [comment]
The answer here can't be "don't use 1.13" or "move directly from 1.12 to 2.0." If 1.13 is going to actually receive first class support for the long term (and is our bridge for deprecations), we need testing of components with `{{link-to}}` in them to actually work. As it stands we still don't have a story for that.

I'm game to code up other solutions, this was the minimally-invasive approach. Proposals?

**Comment by rwjblue** [comment]
As I commented in that other PR, we need to vet the changes from #11522 to make sure they do not make matters worse in 1.13.

**Comment by nathanhammond** [comment]
Okay, and calling `setupRouter` (clarification: not `startRouting`) isn't kosher inside of ember-test-helpers? I'm doing that primarily to build router.js so that API surface is available (and `router.router` isn't `undefined`). Is there a better solution? Just landing #11522 doesn't fix everything.

**Comment by nathanhammond** [comment]
Offline conversation summary:
- Acceptance test with a generic `{{link-to}}` inside a component.
- Guard router.router instead of running `setupRouter`.
- And more...

**Comment by rwjblue** [comment]
Discussed a 'safe' solution (essentially adding a few more guards where we attempt to access 'router.router') with Nathan a few minutes ago. I think we can land those fixes into all branches (along with Tom's fix).

**Comment by tomdale** [comment]
While it isn't elegant, I'm OK with a pragmatic approach to returning compatibility to the 1.13 series. I'd like to revisit this entire code path in 2.x.

**Comment by nathanhammond** [comment]
Closed by #11639.
