### ISSUE TITLE
Removal of _label in bindings

### ISSUE THREAD

**Issue by sir-dunxalot** [emberjs/ember.js#11635]
I'm opening this issues in the spirt of "tell us what private properties/methods you're using so we can see if they should be public."

I have an addon that uses the `xBinding._label` property. For example, if a component looks like:

```hbs
{{input-group value=model.name}}
```

One could do:

```js
// app/components/input-group.js

export default Ember.Controller.extend({
  getBindingPath: function() {
    return this.get('valueBinding._label');
  },
});
```

However, since HTMLBars this functionality seems to have disappeared. There is an `attrs` property available but it has no info on the binding path.

Is the basic principle of exposing the binding 'label' something that would be considered as part of the Ember API (public or private)? Or should this strategy be abandoned?

Thanks.

**Comment by rwjblue** [comment]
> Is the basic principle of exposing the binding 'label' something that would be considered as part of the Ember API (public or private)

Streams (which is what I believe you are talking about) that are exposed outside of Ember internals should be considered a bug (and we should definitely fix them).

----

I think that a component/helper should care about the value that it was passed not the path of that value.  Using the path for later looking up the value is going to cause issues, because the template keyword scoping is non-trivial (e.g. if the path represent a yielded block param how could you look that up?). If you need a path, why not just make that your components API (instead of a bound value)?

You have described what you are trying to do, but can you make the case for why you want this functionality?

**Comment by sir-dunxalot** [comment]
Thanks for the quick response.

In this case I would like to associate the path of the input's bound property with various other properties without requiring a second `label` property to be bound to the component. For example, `model.name` should render some HTML like `<label>Name</label>` and should create a binding to `validations.model.name` in the controller. In every use case I'm not using the path to access the property but am manipulating the path string for other use cases.

It's plausible that the components API take care of both but if there is a plan for this idea to be part of the Ember API then that would be the preferred solution because it would minimize the boilerplate for each input.

**Comment by rwjblue** [comment]
I am assuming that you are talking about something like the ember-easyForm API:

```hbs
{{#form-for model}}
  {{labeled-input 'firstName'}}
{{/form-for}}
```

In this case, given the string path on the provided model you can use the (new in 2.0.0, but supported as an [addon](https://github.com/jmurphyau/ember-get-helper/) in versions prior to 1.13) `get` helper (e.g. `{{get model pathStringProvided}}`) to get the value portion off the `model`.

**Comment by stefanpenner** [comment]
Y! relies on this all over the place as-well. There is an ongoing effort to migrate away form this, unfortunately some core helpers utilized this functionality so changing is a hefty effort.

**Comment by sir-dunxalot** [comment]
Thanks, gents. So, to confirm it seems like one should move away from relying on such functionality ASAP?

**Comment by stefanpenner** [comment]
> So, to confirm it seems like one should move away from relying on such functionality ASAP?

Yes I would say, relying on private API is a big hazard.

**Comment by mmun** [comment]
@sir-dunxalot Yes, when you're digging into private APIs its very helpful to us to know what you're doing so we can cooperate and try to find/build public APIs that cover the use case.

**Comment by stefanpenner** [comment]
I have created a new label, for this category of report.

**Comment by sir-dunxalot** [comment]
Great, thanks guys and good idea with the issue label.

**Comment by stefanpenner** [comment]
@mmun should we leave this open or...

**Comment by mmun** [comment]
Using the label for anything besides debugging is wrong. If your API looks like `{{foo bar}}` and you want the label for bar, then you should change your API to be `{{foo "bar"}}`.

**Comment by stefanpenner** [comment]
> @stefanpenner Using the label for anything besides debugging is wrong.

This is obviously true, but not what I asked.  We have asked uses to report private API usage, what are the next steps? Provide some migration path, deprecating carefully, storing this state on a symbol ? I am merely concerned closing this before we acknowledge the path forward.

**Comment by mmun** [comment]
Streams are private let alone internal properties _on_ those private streams. I am not interested reopening this issue in an attempt to deprecate _label (we may want to use _label as a property in the future). The path forward is to rework the API.

For what its worth, `this.get('valueBinding._label');` won't work _at all_ in Gimmer, because we never set `valueBinding`.

**Comment by stefanpenner** [comment]
@mmun whats the point of users telling us they are using private API? We just tell them, noop don't do that.

**Comment by mmun** [comment]
@stefanpenner Actually, we said "noop, do this instead". Besides, this issue isn't representative of every single private API usage report to come.

**Comment by mmun** [comment]
The `valueBinding` not being set seems worse.
