### ISSUE TITLE
Canary/1.13.2: Value not bubbling back out to controller when using didReceiveAttrs vs didInsertElement

### ISSUE THREAD

**Issue by jcope2013** [emberjs/ember.js#11637]
on canary, is this intentional? setting properties in didReceiveAttrs will not bubble back out to controller level but in didInsertElement does?

didReceiveAttrs  (true property on controller stays at true)

http://jsbin.com/fisuwiwizu/1/edit?html,js,output

didInsertElement (true property on controller gets switched to false)

http://jsbin.com/ruyojodiqi/1/edit?html,js,output

**Comment by stefanpenner** [comment]
Just an FYI, when passing data up it is recommended using an action, not 2 way data-binding.

It may be the case the new hook does not support this older behavior, it is good to see the existing API does support this behavior.

I believe we are lacking docs for the new life-cycle hooks. cc @wycats @trek

**Comment by kitsunde** [comment]
This makes it pretty awkward when combined with `attributeBindings` where it assures me the rendered attribute is bound, but on the other end the components rendered state and the property value will be in an inconsistent state.

In my example if you click the image you can see that the components value for src is different from the one rendered: http://jsbin.com/puhuqefuxi/1/edit

**Comment by trek** [comment]
@stefanpenner Tom and Yehuda decided these weren't ready for public documentation yet https://github.com/emberjs/guides/issues/408#issuecomment-119733642

**Comment by stefanpenner** [comment]
@trek so not public until 2.0 correct?

**Comment by wycats** [comment]
@stefanpenner I think not until we have angle brackets.

**Comment by stefanpenner** [comment]
> @stefanpenner I think not until we have angle brackets.

sounds very reasonable, i think when i posted my comment (20 days ago) i wasn't clear on that. Thanks for clarifying.

**Comment by locks** [comment]
I am closing this issue as the new lifecycle hooks have been documented.

Feel free to re-open the issue if you think it's still justified, thank you.
