### ISSUE TITLE
Make jQuery Optional

### ISSUE THREAD

**Issue by sandstrom** [emberjs/ember.js#11631]
I use jQuery heavily and like it for many reasons! But decoupling it from Ember – making it optional – would be a good idea (as long as the core-team support this).

I've tried to track down the places where it's used and it's implications. There are some primary usage (around events) as well as some auxiliary usage (where it should be fairly easy to replace it, I hope).

**Primary use** *(will require insight from people with good knowledge of browser difference)*

- [ ] For event dispatching [(code)](https://github.com/emberjs/ember.js/blob/680f997ed0958c420abdcd0b1673111aee26afe7/packages/ember-views/lib/system/event_dispatcher.js)
- [ ] *Have I missed something?*

**Auxiliary use** *(these should be easier to replace)*

- [ ] basic DOM-operations for bootstrap [(code)](https://github.com/emberjs/ember.js/blob/680f997ed0958c420abdcd0b1673111aee26afe7/packages/ember-htmlbars/lib/system/bootstrap.js)
- [ ] Firefox 11 and outerHTML[1]. Is this still needed? Firefox is on v38 now. [(code)](https://github.com/emberjs/ember.js/blob/680f997ed0958c420abdcd0b1673111aee26afe7/packages/ember-views/lib/compat/render_buffer.js#L577)
- [ ] #findElementInParentElement [(code)](https://github.com/emberjs/ember.js/blob/49d58530527c9025b4bafe4f937b0c78cfe3818e/packages/ember-views/lib/views/view.js#L1133)
- [ ] #replaceIn [(code)](https://github.com/emberjs/ember.js/blob/49d58530527c9025b4bafe4f937b0c78cfe3818e/packages/ember-views/lib/views/view.js#L1038)
- [ ] #appendTo [(code)](https://github.com/emberjs/ember.js/blob/49d58530527c9025b4bafe4f937b0c78cfe3818e/packages/ember-views/lib/views/view.js#L961)
- [ ] event listening for location changes and a DOM-lookup [(code)](https://github.com/emberjs/ember.js/blob/680f997ed0958c420abdcd0b1673111aee26afe7/packages/ember-routing/lib/location/history_location.js)
- [ ] getElementById lookup [(code)](https://github.com/emberjs/ember.js/blob/680f997ed0958c420abdcd0b1673111aee26afe7/packages/ember-views/lib/views/states/has_element.js#L25)

**Library and access** *(these should remain even if the library is optional, with a friendly message if jQuery is not present)*

- [ ] For `Ember.$`. [(code)](https://github.com/emberjs/ember.js/blob/680f997ed0958c420abdcd0b1673111aee26afe7/packages/ember-views/lib/main.js#L55)
- [ ] Core library registration [(code)](https://github.com/emberjs/ember.js/blob/680f997ed0958c420abdcd0b1673111aee26afe7/packages/ember-application/lib/system/application.js#L1141)
- [ ] The view wrapper `this.$()` [(code 1)](https://github.com/emberjs/ember.js/blob/49d58530527c9025b4bafe4f937b0c78cfe3818e/packages/ember-views/lib/views/view.js#L918) and [(code 2)](https://github.com/emberjs/ember.js/blob/680f997ed0958c420abdcd0b1673111aee26afe7/packages/ember-views/lib/views/states/has_element.js#L16)

***

Please add to the list if I've missed something.

Since jQuery is good at patching over browser-difference, care must be taken to understand where it's being relied on for this.

[1] https://developer.mozilla.org/en-US/docs/Web/API/Element/outerHTML

**Comment by btecu** [comment]
Although I think this is a good idea, I remember core members stating that jQuery wasn't going away, at least not in 2.0.

**Comment by rwjblue** [comment]
We absolutely plan to support using Ember without jQuery at some point (this would be fully SemVer compliant because removing a required dependency doesn't break anything), but we will definitely *not* be making using Ember along with jQuery an error (that would be a SemVer violation IMHO).

**Comment by stefanpenner** [comment]
I would love to see thorough cross browser (ie9 +, and older mobiles) exploration.

**Comment by stefanpenner** [comment]
This seems like an RFC/ RFC issue

**Comment by chadhietala** [comment]
This just seems like Ember needs to use an abstract interface similar to how environment is used internally to allow ember to boot in a node context.

**Comment by jonnii** [comment]
@stefanpenner how possible is it do something like delay loading jquery until `this.$()` is used in a component or a view?

**Comment by stefanpenner** [comment]
> @stefanpenner how possible is it do something like delay loading jquery until this.$() is used in a component or a view?

Possible, but we also use jQuery for cross browser event delegation and the quirky bubbling cross browser behavior. Which currently still is eager, also could be made lazy.

**Comment by rwjblue** [comment]
I am hugely in favor of Ember not requiring jQuery, and this issue is wonderfully researched with links, but I believe this belongs as an issue in [emberjs/rfcs](https://github.com/emberjs/rfcs/issues) since it is not a "bug" per-se in Ember itself.

Closing with :heart: in favor of an issue there...

**Comment by sandstrom** [comment]
Done https://github.com/emberjs/rfcs/pull/73
