### ISSUE TITLE
Dynamically-added angle bracket components aren't recognized

### ISSUE THREAD

**Issue by courthead** [emberjs/ember.js#11649]
http://emberjs.jsbin.com/zahucoyara/edit?html,css,js,output

I have a component that builds a property that's a string with some angle-bracket components inside of it. The string is printed unescaped in the component's template. I would expect Handlebars to recognize the angle-bracket components, however they are treated as normal HTML tags. I'm not sure if this is a bug, if I'm doing something wrong, or if this functionality just isn't supported yet. I've attached a JSBin showing a potential use-case and the issue.

**Comment by stefanpenner** [comment]
Ya. This isn't something we support, I also suspect we won't as t would require all of the htmlbars compiler client side and would likely be pretty slow. If you wish to add components dynamically. The component helper may be your best bet.

You may also want to look at the context component rfc

**Comment by courthead** [comment]
@stefanpenner Okay makes sense, thanks for the response. I'll take a look at the context component RFC! Also, pre-glimmer, I was able to do something like this successfully:

```
App.SomeThingComponent = Ember.Component.reopen({
  _updateLayout: function () {
    const templateStr = '{{some-other-thing value="' + whatever + '"}}';
    const newTemplate = Ember.Handlebars.compile(templateStr);
    this.set('layout', newTemplate).rerender();
  }.observes('whatever').on('init')
});
```

Post-Glimmer, this still works on initialization. However, when `whatever` is changed and the function is run again, nothing is updated in the UI after the `rerender` call. Is this a regression or an intentional side effect of Glimmer?

Thanks again!

**Comment by stefanpenner** [comment]
> Also, pre-glimmer, I was able to do something like this successfully:

Just so you know, running the compiler in production really isn't something I would at all recommend.

I am unclear if this particular approach is ever something we intended to support.


> this.set('layout', newTemplate).rerender();

that being said, i suspect this line is the issue, are your trying to call rerender on the template or on the component?

**Comment by courthead** [comment]
The intention is to call it on the component. I'll see if I can come up with an alternative approach that doesn't use the compiler.

**Comment by rwjblue** [comment]
In 1.13 it is not possible to change layout after initial render. There is at least one issue open about this...

**Comment by courthead** [comment]
Got it, thanks, I'll follow those issues

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/11315 is a failing test for rerendering after updating layout.

**Comment by rwjblue** [comment]
Closing in favor of the failing test case PR mentioned above.
