### ISSUE TITLE
1.13.3 on ruby-gems

### ISSUE THREAD

**Issue by thec0keman** [emberjs/ember.js#11659]
Would it be possible to release 1.13.3 on ruby-gems?

**Comment by stefanpenner** [comment]
@fivetanley are you our rubygems guy? cc @tricknotes

**Comment by rwjblue** [comment]
I'll get it published in an hour or so.

**Comment by thec0keman** [comment]
@rwjblue any update on this?  Thanks

**Comment by rwjblue** [comment]
Published.
