### ISSUE TITLE
Include LICENSE in built assets and supply info in metadata files

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#11658]
This is dependant on https://github.com/emberjs/emberjs-build/pull/110 but I believe the bower.json and package.json need to be updated to include the license field and a homepage field that points back to this repo. I cannot find where the bower.json and package.json's are being generated. If someone can point me to where https://github.com/components/ember/blob/master/bower.json,  https://github.com/components/ember/blob/master/package.json and https://github.com/components/ember/blob/master/component.json are being generated I will go fix them.

**Comment by stefanpenner** [comment]
cc @tomdale / @wycats

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/blob/master/config/package_manager_files/bower.json

**Comment by rwjblue** [comment]
The updates to the package manager files have been updated, and the published assets do contain license information now (likely due to @chadhietala's hard work).

Closing...
