### ISSUE TITLE
[1.13.3 Regression] Link to with only query params doesn't work

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#11654]
In 1.13.1 link to with only query params (`{{link-to pageNum (query-params page=pageNum)}}`) used to link the the actual route with different query params, but in 1.13.3 this doesn't work anymore.

No sure if this is new or was introduced in 1.13.2 since I skipped that version.

**Comment by cibernox** [comment]
Update:
I've checked that this is only broken for the block-less version of link-to:
`{{link-to pageNum (query-params page=pageNum)}}` fails but `{{#link-to (query-params page=pageNum)}}{{pageNum}}{{/link-to}}` works

**Comment by rwjblue** [comment]
@cibernox - Could you post a JSBin when you have a minute?

**Comment by cibernox** [comment]
@rwjblue Sure: http://emberjs.jsbin.com/kuwupogihe/edit?html,js,console,output

**Comment by cibernox** [comment]
In that jsbin I confirmed that was added between 1.13.2 and 1.13.3
