### ISSUE TITLE
Naming Conventions Table CSS 

### ISSUE THREAD

**Issue by ashleygwilliams** [emberjs/ember.js#11652]
on http://guides.emberjs.com/v1.12.0/concepts/naming-conventions/
table exceeds 100% width, overflow is cut off, cannot read template column

<img width="814" alt="screen shot 2015-07-05 at 5 44 43 pm" src="https://cloud.githubusercontent.com/assets/1163554/8513531/cd01c2f4-233d-11e5-89fb-ad8fce5ff829.png">

in Chrome 43.0.2357.130 (64-bit)

**Comment by rwjblue** [comment]
Thanks for reporting! I am unsure if this is already fixed on master of the guides repo, but would you mind reopening this over on emberjs/guides?

**Comment by ashleygwilliams** [comment]
sure thing! sorry this was in the wrong place :grimacing:

**Comment by ashleygwilliams** [comment]
https://github.com/emberjs/guides/issues/399

**Comment by rwjblue** [comment]
No problem at all!
