### ISSUE TITLE
[REGRESSION] A property named "buffer" in a component comes up null in 1.10, 1.11, 1.12

### ISSUE THREAD

**Issue by chriscareycode** [emberjs/ember.js#11666]
```js
App.MyComponentComponent = Ember.Component.extend({
  buffer: 200,  
  didInsertElement: function() {
    console.log('buffer is: ' + this.get('buffer'));
  }
});
```
This will output "buffer is null"

http://emberjs.jsbin.com/jatacowexu/

**Comment by stefanpenner** [comment]
[edited: JS formatting]

**Comment by stefanpenner** [comment]
@chriscareycode i suspect the same is in 1.13?

**Comment by chriscareycode** [comment]
@stefanpenner Actually not an issue in 1.13. If you change the build to 1.13 in the jsbin, bug fixed. Due to a memory leak issue in 1.13 I can not go there just yet.

Perhaps with that in mind it's not worth your time to jump into this bug. This did break a feature on an existing app of mine that was working before, so I thought it was worth noting. The fix for the end user is simple enough, just rename the variable to something else.

**Comment by stefanpenner** [comment]
@chriscareycode this leak maybe https://github.com/emberjs/ember.js/pull/11667 ?

I am unclear if we will go back and fix 1.10, 1.11 1.12. Maybe if we have enough things.

**Comment by chriscareycode** [comment]
Yes on #11667 - anxiously awaiting a fix to test

**Comment by stefanpenner** [comment]
@chriscareycode that leak has been merged, are you able to check if this is an on 1.13.3 now?

**Comment by rwjblue** [comment]
It was not included in 1.13.3, it will be in 1.13.4.

**Comment by stefanpenner** [comment]
the jsbin works on 1.13.3

**Comment by stefanpenner** [comment]
@rwjblue ah yes, tonights release :)

**Comment by chriscareycode** [comment]
1.13.4 looks great so far. In Developer Tools timeline with 1.13.3 I see ever increasing JS heap usage. 1.13.4 looks flat.

**Comment by chriscareycode** [comment]
The "buffer is null" issue is also not an issue on 1.13.4 http://emberjs.jsbin.com/toqogayovi/1/

**Comment by stefanpenner** [comment]
yes. both should be addressed.
