### ISSUE TITLE
Issue about Ember.computed.oneWay

### ISSUE THREAD

**Issue by LucasZheng** [emberjs/ember.js#11670]
link: http://emberjs.jsbin.com/bazabe/edit?js,console

    var User = Ember.Object.extend({
      firstName: null,
      lastName: null,
      nickName: Ember.computed.oneWay('firstName')
    });
    var teddy = User.create({
      firstName: 'Teddy',
      lastName:  'Zeenny'
    });

    teddy.get('nickName');              // 'Teddy'
    teddy.set('nickName', 'TeddyBear'); // 'TeddyBear'
    teddy.set('firstName', 'lucas'); 
    teddy.get('nickName'); //'TeddyBear'
    teddy.get('firstName'); //'lucas'

When we set `firstname` as `lucas` again, it seems that `nickName` does not change accordingly, is the following code will block the `oneWay` behaviour? 

     teddy.set('nickName', 'TeddyBear'); // 'TeddyBear'

when I comment the above code, the `nickName` will shows `lucas`, it's the correct behaviour.

**Comment by maheshsenni** [comment]
It is the expected behaviour as per this statement from the [docs](http://emberjs.com/api/classes/Ember.computed.html#method_oneWay).

`This causes the downstream property to permanently diverge from the upstream property`.

When you directly set values on an `oneWay` property, it is no longer connected to the original property.

**Comment by LucasZheng** [comment]
Thanks for your explanation.  If I want to achieve the above behaviour(after set values on an one-way property, meanwhile it will also observer and update original property rather than disconnected),  is there an existed method in Ember can be used?

**Comment by mixonic** [comment]
@LucasZheng This case would require that you use an observer. Please follow up on stackoverflow or the community slack chat for details.
