### ISSUE TITLE
Symbol is not a supported type in Ember.typeOf(); returns "object"

### ISSUE THREAD

**Issue by notmessenger** [emberjs/ember.js#11673]
ember.js/packages/ember-runtime/lib/utils.js

**Comment by stefanpenner** [comment]
Is that a real es6 symbol or a polyfiled one

**Comment by rwjblue** [comment]
Most likely https://github.com/emberjs/ember.js/blob/41be946f26b1c232c183a9e42de74d2142042e5a/packages/ember-runtime/lib/utils.js#L108 needs similar treatment to https://github.com/emberjs/ember.js/pull/11239

**Comment by notmessenger** [comment]
Hrm...the polyfilled one

**Comment by notmessenger** [comment]
Aww man @rwjblue I looked for an issue that might have already addressed this and I missed it.  Sorry about that.

**Comment by stefanpenner** [comment]
> Hrm...the polyfilled one

embers or some other? There are potentially many

**Comment by notmessenger** [comment]
@stefanpenner Whatever the default babel configuration is with Ember CLI.  I have not made any modifications and am assuming that http://babeljs.io/docs/usage/polyfill/ is in play but perhaps there is a gap in my understanding.

**Comment by stefanpenner** [comment]
im not sure the polifil decorates itself correctly

**Comment by stefanpenner** [comment]
let me check

**Comment by stefanpenner** [comment]
perfect, seems like it does
```
% node -v                                                                                                                                                                  v0.10.35
```

```
> require('core-js/shim');
> Symbol
[Function: Symbol]
> Object.prototype.toString.call(Symbol)
'[object Function]'
> Object.prototype.toString.call(Symbol('a'))
'[object Symbol]'
>
```

**Comment by stefanpenner** [comment]
We have decided to freeze `Ember.typeOf` do to the broken landscape of `@@toStringTag`.

We can likely revisit at some future point in time, when the landscape has become reasonable.


#### Example insanity:

IE11:

```js
Object.prototype.toString.call(new Map()) === '[object Object]'
```

Chrome: Version 45.0.2449.0 canary (64-bit)
```
Object.prototype.toString.call(new Map()) === '[object Map]';
Object.prototype.toString.call(new Promise(function(){}))  === '[object Promise]';
```

Chrome: Version 43.0.2357.130 (64-bit)
```
Object.prototype.toString.call(new Map()) === '[object Map]';
Object.prototype.toString.call(new Promise(function(){}))  === '[object Object]';
```

**Comment by stefanpenner** [comment]
I would have loved to fix this, unfortunately requireing something like core-js to always 100% of time be on the page for a feature to work isn't something we can commit to. Especially for something like `Ember.typeOf`

**Comment by notmessenger** [comment]
If I'm understanding my research correctly for @@toStringTag we will run into the same problem you have listed by using typeof instead, correct?

**Comment by stefanpenner** [comment]
> same problem you have listed by using typeof instead

nope
