### ISSUE TITLE
ember-cli on windows

### ISSUE THREAD

**Issue by ORESoftware** [emberjs/ember.js#11684]
Thanks for your time in looking at this. I got a weird ENOENT error when I ran:

```
$> ember new my-ember-app
```

It's all in the screenshot, can you explain why I got the ENOENT error? I am Windows 7. It just doesn't make any sense that it was looking for a package.json file on my Desktop...

![screenshot 2015-07-07 23 47 43](https://cloud.githubusercontent.com/assets/11139560/8564644/e61fdffc-2502-11e5-84ce-5142e267b114.png)

**Comment by stefanpenner** [comment]
please be sure to read the window support section: www.ember-cli.com/#windows

also this is the incorrect repo, https://github.com/ember-cli/ember-cli

the ENOENT on initial install apepars to be a strange node race condition, typically users can remove the directory and try again and it works.

**Comment by ORESoftware** [comment]
ok thank you for that
