### ISSUE TITLE
Ember.Select doesn't update its initial selection binding in 1.13

### ISSUE THREAD

**Issue by jakesjews** [emberjs/ember.js#11681]
In 1.12 Ember.Select without a placeholder automatically selected the first item in its content and updated any selection binding along with it. In 1.13 it looks like the selection binding is not updated until a different item from the first option is selected.

[JS Bin replicating the issue](http://emberjs.jsbin.com/paceveregu/edit?html,js,output)

**Comment by stefanpenner** [comment]
just a headsup, select is deprecated and will be leaving us in 2.0.

Going forward, likely a better option is to use the DOM directly -> http://jsbin.com/febafarova/1/edit?html,css,js,output

**Comment by rwjblue** [comment]
I'm happy to review / entertain a PR for this, but since Ember.Select is removed from the public API in 2.0.0 I am closing this issue.
