### ISSUE TITLE
 positionalParams causing extra change notifications on initial render

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#11686]
So today, we must create the component, extract the position args and then place them on `attrs`. This means we currently always dirty `this.attrs` even on initial render. At the very best this results in wasteful changeEvents, at the worse may cause a hefty work amplification.

I feel strongly, we need to work hard to ensure `attrs` on initial render is in its fully formed initial state.

Some ideas:

* extract positionArgs to a static property so it is readable before creation of the component and can be passed into `create`.
* read positionArgs from the prototype so it can be passed to create, this feels icky and doing the same in QP has cause much pain.
* add positional args at some level during `component.init`

note: it is true that we also invalidate the keys on `this.attrs` on initial render, we also need to solve that. But both this and that are tightly related.

**Comment by stefanpenner** [comment]
@ef4 I've assigned you, to at least provide feedback, since you are likely most familiar with this.

**Comment by ef4** [comment]
I concur that the positionalArgs array itself is intended to be a static property of the class, and it should be fair game to access it before instantiation of a component instance.

**Comment by stefanpenner** [comment]
I will document + assert accordingly, and then take advantage of this concept to being addressing issues the compat code has introduced.

**Comment by stefanpenner** [comment]
Ok, i think we will treat positionArgs as if it was static, and write some assertions to ensure users don't use it any other way. The final resting place will likely be static, but we can support bothwithout cost today.

This will enable us to begin fixing https://github.com/emberjs/ember.js/issues/11502#issuecomment-119667735

**Comment by rwjblue** [comment]
Brain dump after discussing with @stefanpenner in chat:

Go forward would be:

```javascript
var Thing = Ember.Component.extend({
 // stuff here
});

Thing.reopenClass({
  positionalParams: ['stuff', 'here']
});

export default Thing;
```

Deprecated but functional:

```javascript
export default Ember.Component.extend({
  positionalParams: ['stuff', 'here']
});
```
