### ISSUE TITLE
Ember internals are generating deprecation warnings with no way to silence

### ISSUE THREAD

**Issue by jerel** [emberjs/ember.js#11680]
In v1.13.3 I get a ton of Ember.create and Ember.keys deprecations even though I'm not using them anywhere in my project.
![deprecations](https://cloud.githubusercontent.com/assets/322706/8561351/d7ceb248-24e9-11e5-8084-049a4639b71d.png)
And for some reason my usual approach of silencing deprecations that I can't do anything about does not work in this case. I'm assuming that they are coming from within Ember before my app even boots.
![deprecate](https://cloud.githubusercontent.com/assets/322706/8561448/5844aa8a-24eb-11e5-8837-b791537beff6.png)

**Comment by stefanpenner** [comment]
those all point to ember-data, github.com/emberjs/ember-data and i believe they are also all fixed on ember-data.

**Comment by jerel** [comment]
@stefanpenner oof, I *just* now realized that and of course I forgot to check that issue tracker this time.

I am running the latest ED, the fix is on master I believe but not in the v1.3.4 ED release.

**Comment by stefanpenner** [comment]
> I am running the latest ED, the fix is on master I believe but not in the v1.3.4 ED release.

I believe a PR exists (or was mergeD) to address these in 1.13.x (i remember giving feedback on it). Best to open an issue on ED to get that moving forward.

**Comment by jcope2013** [comment]
@jerel add ``` "ember-data": "#release" ``` until v1.13.5 gets released, it has the fixes that will be added in 1.13.5
