### ISSUE TITLE
[beta] Remove special case behaviors of global paths

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#11689]
`{{Foo}}` is a global lookup in Ember 1.13. This an several other special global behaviors based on capitalization should be removed from 2.0.

- [ ] Chains through globals: `.property('foo.App.bar')`
- [ ] Ember.binding to globals `fooBinding: App.bar`
- [ ] Ember.get'ing a global: `Ember.get('App.foo')`

**Comment by stefanpenner** [comment]
Moved this to the 1.13 milestone so we remember
  We must deprecate as a bugfix release and remove as a bugfix beta

**Comment by rwjblue** [comment]
@stefanpenner - Globals access from templates has been deprecated for a while (at least 2-3 minor versions). Unless we uncover something new that was not caught when we initially deprecated, I do not think this will require backporting to 1.13.x.

**Comment by mmun** [comment]
Chains through globals are not deprecated as far as I can tell, e.g.

```js
bar: function() {
  return this.get('Foo.bar')
}.property('Foo.bar')
```

**Comment by rwjblue** [comment]
@mmun - Gotcha, I mis-read and thought that this was for templates only (where things like `{{Foo.bar}}` should be deprecated).

**Comment by mmun** [comment]
Oops deleted my comment by accident. Chains through globals are functional and not deprecated. See this jsbin: http://emberjs.jsbin.com/wavawicabo/edit?html,js,output.

**Comment by stefanpenner** [comment]
> Unless we uncover something new that was not caught when we initially deprecated, I do not think this will require backporting to 1.13.x.

perfect, then only to release :)

**Comment by mixonic** [comment]
Looks like `Ember.get('App.foo')` is also not deprecated. We should keep the goal clear though- is it to remove **all** global references in paths?

**Comment by krisselden** [comment]
yes

**Comment by krisselden** [comment]
watch('a.B.c') is buggy because when split at some point it will watch(pathNode.value, 'B') which is wrong.

**Comment by krisselden** [comment]
@stefanpenner the above can be fixed by detecting can doing watch(pathNode.value, 'this.B') which when going through normalizeTuple will produce the right thing, if we want to backport to 1.13.x

**Comment by krisselden** [comment]
@stefanpenner to clarify the primary goal should be to drop normalizeTuple that watch() uses, that is the source of nasty bugs with uppercase props.  Prefixing 'this.' is supposed to be the disambiguator but the framework does not do this when splitting paths that were unambiguous, so they become ambiguous.

**Comment by mixonic** [comment]
I'm going to close this. I think @mmun did some of it.

**Comment by mmun** [comment]
Yes it should be completely removed now. Except for `fooBinding: Global.blah` which I left because we plan to deprecate bindings entirely.
