### ISSUE TITLE
TextField component shows a character if typed three times

### ISSUE THREAD

**Issue by zoltan-nz** [emberjs/ember.js#11687]
JSBin: http://jsbin.com/lupibe/8/edit?html,console,output

If you create a customized `TextField` component, and you would like to rewrite the `value` property with observer, than if you type the same character in the input field three times, that character stays there.

This happening only, if you connect that `value` property to an external property.

This issue exist in Ember version 1.13, and in the canary version as well.

**Comment by stefanpenner** [comment]
wow strange.

**Comment by sly7-7** [comment]
Seems like it has to do with changing the value during rerender. Scheduling the rewrite in the afterRender queue make the thing working well, and also remove the warning.
http://jsbin.com/wujase/edit?html,js,console,output

**Comment by rwjblue** [comment]
The reported JSBin does not exhibit issues on canary, closing for now (but I'm happy to reopen if I have misinterpreted)...
