### ISSUE TITLE
test skipped in Firefox, we should fix it

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#11698]
https://github.com/emberjs/ember.js/blob/8767515d65def291dfbf42b9ad7f48816f425a32/packages/ember-htmlbars/tests/integration/select_in_template_test.js#L156-L188

**Comment by mixonic** [comment]
This is a dupe of https://github.com/emberjs/ember.js/issues/10984. I'll move that to the release, it has more context.

**Comment by stefanpenner** [comment]
@mixonic awesome, i tried searching but GH search failed me. Thanks for the correction + link.
