### ISSUE TITLE
jQuery reference changes in 1.13

### ISSUE THREAD

**Issue by leojh** [emberjs/ember.js#11694]
I'm trying to migrate to 1.13.3 from 1.12 and one of the issues I'm seeing is that inside of a component, I no longer have the ability to do `this.$()` to get an element using jQuery.
I also noticed that `Ember.$`is undefined. `Em.$` seems to work tho.

I think this may be related to Views being deprecated but I have not read any direct mention of any changes to the way jQuery is referenced inside of components.

**Comment by rwjblue** [comment]
`this.$()` seems to be working in a simple JSBin: http://rwjblue.jsbin.com/rwjblue/624/edit?html,js,output for 1.13.3.

Can you tweak that JSBin to demo the issue you are describing?

**Comment by leojh** [comment]
Check it out: http://jsbin.com/ruxiqipiji/1/edit?html,js,console,output
It was working before this last upgrade... I would think that it has something to do with the new component hooks.

**Comment by stefanpenner** [comment]
observers can fire before stuff is in the DOM, please consider the new component hooks, and move away from observers.

**Comment by leojh** [comment]
@stefanpenner you're confirming my thoughts then. good deal.
