### ISSUE TITLE
The `classNameBindings` property for the {{link-to}} helper doesn't update in 1.13.x

### ISSUE THREAD

**Issue by courthead** [emberjs/ember.js#11699]
In Ember 1.12 you could do `{{#link-to "path" classNameBindings="model.property:some-class"}}...`, and when `model.property` changed the link's class would change accordingly. I'm finding that in Ember 1.13 the class is set initially, but doesn't update dynamically as `model.property` changes.

Here's a JSBin: http://emberjs.jsbin.com/duvocorodo/edit?html,css,js,output

**Comment by btecu** [comment]
I'm using `classNameBindings` successfully on 1.13.x, except my binding is just a property, not on an object.

**Comment by stefanpenner** [comment]
I believe we fixed this

**Comment by mixonic** [comment]
This seems like a regression. Confirmed on 1.13.3.

**Comment by mutewinter** [comment]
Confirmed, keeping us from migrating to 1.13.

**Comment by stefanpenner** [comment]
if someone has time to submit a PR with a failing test, that would help get the ball moving.

**Comment by aortbals** [comment]
I've submitted a failing test. I'm not entirely sure yet where in the stack the fix needs to be made. I'm looking into it. I'm happy to update the PR with the fix If I get to it before someone else. Any guidance on where this regression might have been introduced is also appreciated.

**Comment by raytiley** [comment]
Not sure if its helpful but this also fails using the newer inline if syntax, which I imagine just uses attributeBindings under the hood?

I tried debugging this but got lost pretty quickly. In the `ComponentNodeManager` I see the `attrs` are correct but once `block` is called somewhere down the line the `joinClasses` helper gets called and the array of classes it gets has the old data. So all the changes / rerendering is happening, just somewhere down the line the updated attrs isn't getting passed along correctly.

<img width="778" alt="edit html css js output 2015-07-15 08-14-15" src="https://cloud.githubusercontent.com/assets/41680/8698206/e4dbbaf4-2ac9-11e5-9627-13dd5d2c5569.png">

**Comment by aortbals** [comment]
Another few pieces of information:

After additional debugging, I wanted to confirm that this does seem to be specific to  `LinkComponent`. When a `link-to` is rerendered with class bindings like the following, it does not update:

```handlebars
{{#link-to 'home' classNameBindings='isHomeHighlighted:is-highlighted'}}Home{{/link-to}}
```

And as @raytiley mentions, an inline if subexpression also does not work. Side note: I'm not sure which is correct here, `class` or `classNames`, both render once and do not rerender correctly like the previous example:

```handlebars
{{#link-to 'home' classNames=(if isHomeHighlighted 'is-highlighted')}}Home{{/link-to}}
```

```handlebars
{{#link-to 'home' class=(if isHomeHighlighted 'is-highlighted')}}Home{{/link-to}}
```

However, the following cases do rerender correctly:

Binding on a normal `<a>` tag

```html
<a href='http://foo.bar' class={{if isHomeHighlighted 'is-highlighted'}}>Foo Bar</a>
```

A standard generated blank component with `classNameBindings`

```handlebars
{{#test-class-bindings classNameBindings='isHomeHighlighted:is-highlighted'}}Home{{/test-class-bindings}}
```

**Comment by rwjblue** [comment]
Nice summary of issues by @aortbals in https://github.com/emberjs/ember.js/issues/11391#issuecomment-127069856:

> This doesn't appear to affect other components, only the `LinkView` component. See https://github.com/emberjs/ember.js/issues/11763. This seems to affect all bound attributes on `link-to`.

> Issues: `class` https://github.com/emberjs/ember.js/issues/11390, https://github.com/emberjs/ember.js/issues/11763, `tabindex`  https://github.com/emberjs/ember.js/issues/11763
