### ISSUE TITLE
Routing conflict with multiple `this.resource()` or `this.route({resetNamespace: true})` routes

### ISSUE THREAD

**Issue by danmcclain** [emberjs/ember.js#11692]
[JSBin demo](http://emberjs.jsbin.com/cexazi/4)

With the following `router.js` definition:

```js
App.Router.map(function() {
  // put your routes here
  this.route('foo', function() {
    this.resource('baz');
    this.route('qux', { resetNamespace: true});
  });
  
  this.route('bar', function() {
    this.resource('baz');
    this.route('qux', { resetNamespace: true});
  });
});
```

You'd expect the following routes to be available:
 * /foo/baz
 * /foo/qux
 * /bar/baz
 * /bar/qux

Under the `/foo` route, you'd expect that `{{link-to 'Baz' 'baz'}}` would link to `/foo/baz`, but it links to `/bar/baz`. It seems as though it's only accepting the last resource or route. If you comment out the route/resource from `bar`, `foo` works as expected

This issue actually goes all the way back to 1.0, with nesting resources as well: [1.0 JSBin demo](http://output.jsbin.com/coyaqu#/bar/baz)

**Comment by btecu** [comment]
I'm not sure your case is expected to work, although I understand the premise.

`{{link-to 'Baz' 'foo.baz'}}` works and certainly being more explicit is probably preferred in this case.

**Comment by danmcclain** [comment]
The point of a resource or a route with the namespace reset is to use the same routes/controllers/templates for 2 separate routes. In my case, the 2 routes share everything

**Comment by ronco** [comment]
:+1: on this issue.  It'd be very useful to re-use a common nested route in different contexts.  And the guide documentation implies this is the behavior.

**Comment by ronco** [comment]
Here is a [twiddle](http://ember-twiddle.com/9db65d5d08f6705d7350) demonstrating the bug I wrote before finding this issue.

You can see that the link-to's under the apples index route take you into the fruit-detail route under oranges.

**Comment by danmcclain** [comment]
Any movement on classifying this issue? The documentation is wrong at minimum if this is no longer the intention of resetting namespaces

**Comment by rwjblue** [comment]
Since this has "never" worked properly, lets just update the documentation. It is unfortunate because I believe it was intended to work, but ¯\\\_(ツ)\_/¯.

**Comment by spinlock99** [comment]
I just ran into this too. Did resources have this behavior too? My understanding is that a route with `resetNamespace: true` should replace a resource. If this worked for resources and is broken for routes... then it seems like functionality has been lost from that deprecation.

**Comment by danmcclain** [comment]
@spinlock99: it was *supposed* to work for resources, but I tested all the way back to 1.0 and it has never worked correctly. The point @rwjblue was making was that the docs should reflect that it is not currently working

**Comment by spinlock99** [comment]
Got it. Thanks @danmcclain.

**Comment by sarus** [comment]
Got bitten by this as well.  Although updating the docs would prevent confusion having it work as advertised would be even cooler ;)

**Comment by alexspeller** [comment]
https://github.com/emberjs/guides/pull/1006

**Comment by alexspeller** [comment]
@rwjblue this issue should probably be closed now

**Comment by juggy** [comment]
One alternative is to import and export the routes/controllers/templates from the primary route for each of the sub route.

so in your example, have a route called `qux` in the root and have `foo.qux` and `bar.qux` import from that root route.

**Comment by spinlock99** [comment]
@juggy that's a great idea. Right now we have `app/templates/qux.hbs` that we would bring in as a partial from `foo.qux` and `bar.qux` and we would use `app/mixins/qux.js` and pull that into the relevant routes.

I like the solution of importing from a single file better because the mixin approach always felt a bit hacky to me.

**Comment by remkoboschker** [comment]
I suppose `resetNamespace` should be removed from the api documentation as well? http://emberjs.com/api/classes/Ember.Router.html#method_map

**Comment by remkoboschker** [comment]
And also removed from the ember cli route blueprint option `reset-namespace`?

**Comment by remkoboschker** [comment]
Happy to make pull requests for it

**Comment by remkoboschker** [comment]
and here http://emberjs.com/api/classes/Ember.ControllerMixin.html#method_transitionToRoute

**Comment by danmcclain** [comment]
@remkoboschker I don't think all documentation around `resetNamespace` should go away, just the bits that claim that you can multiple routes with that reset to the same root resources work correctly

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/13106 removes the notion of reuse in `Router.map`, the reference in `transitionToRoute` seems fine.
