### ISSUE TITLE
Ember array not properly updating in template

### ISSUE THREAD

**Issue by JarrodCTaylor** [emberjs/ember.js#11701]
In the JSBin click the button and it will add an item to the array. The loop in the template will display the new item but were we have only {{exmapleArray}} will not show the change. If you visit the distraction route when you return you will see the exampleArray has been updated.

http://emberjs.jsbin.com/dewuna/edit?html,js,output

**Comment by mattjmorrison** [comment]
Interesting... is this a Glimmer bug? @JarrodCTaylor this happens in 1.13 and not in 1.12, correct?

**Comment by jakesjews** [comment]
I think this is related to #11549. If you change the each to `{{#each exampleArray key='@index' as |thing|}}` then it works as expected.

**Comment by mattjmorrison** [comment]
@jakesjews I don't think that is the same problem. In this example the `#each` is working as expected, it's the `{{exampleArray}}` that is not working.

**Comment by jakesjews** [comment]
Now i see it. I was thinking it was the fact that 1.13 only lets you add one item while 1.12 added as many as you clicked.

It looks like it doesn't work in 1.12 either but interestingly it does work in 1.11 if you change the each to `{{#each thing in exampleArray}}`.

**Comment by JarrodCTaylor** [comment]
I have created another bin to exactly duplicate the production issue that I am experiencing with 1.13.X

http://emberjs.jsbin.com/qujeba/edit?html,js,output

In 1.12.X the if check on the array will update the class resulting in a color change to the <h4>. However, in 1.13.X you need to visit a different route and return in order to see the change reflected.

**Comment by mixonic** [comment]
@JarrodCTaylor I believe you want to bind to `exampleArray.length`. IMO the 1.13 behavior is correct- the array is always present, thus the `if` should evaluate true.

**Comment by JarrodCTaylor** [comment]
@mixonic the behavior is inconsistent. I updated the bin to have a
```
{{#if exampleArray}}
  <p>This is true now</p>
{{/if}}
```

Which is updated. However, the `<h4 class={{if exampleArray 'blue' 'red'}}>Example text</h4>` is not.

**Comment by mixonic** [comment]
I definitely agree they should behave consistently!

**Comment by krisselden** [comment]
I updated the jsbin here to clarify some of the examples: http://emberjs.jsbin.com/pobepubiba/4/edit?html,css,js,output

@mixonic the magic if conditional on length was I think to be consistent with #each else or Ember.isEmpty?

**Comment by rwjblue** [comment]
Will be fixed by https://github.com/emberjs/ember.js/pull/13359.
