### ISSUE TITLE
a property designated as a mergedProperties will mutate the prototype if set during create

### ISSUE THREAD

**Issue by krisselden** [emberjs/ember.js#11714]
https://github.com/emberjs/ember.js/blob/fb49fa0444215cdfb71d9f955f55661fc7176ae0/packages/ember-runtime/lib/system/core_object.js#L146

this should be value = merge({}, originalValue, value);

**Comment by Panman8201** [comment]
I'm running into this, trying to used an `options:{}` property as an attribute, with it defined as a `mergedProperties:['options']`. That way the Component could be extended to define "default" options but then allow usage in templates to override some options with the `(hash)` helper. Ex: `{{foo-bar options=(hash baz="overridden" zoo="new")}}` Any progress on this or a workaround?

As a side note, this could probably use the new `Ember.assign()` polyfil for `Object.assign()`. I'm sure you're fully aware, but just for reference: http://emberjs.com/blog/2016/02/29/ember-2-4-released.html#toc_code-ember-assign-code
