### ISSUE TITLE
deprecations exist in prod/min builds

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#11717]

**Comment by rwjblue** [comment]
I just did a quick search/scan of http://builds.emberjs.com/canary/ember.prod.js, and didn't notice any. Could you please link the build you are referring to, and if possible gist a snippet of what you saw that seemed wrong?

**Comment by stefanpenner** [comment]
Yes the built (for publishes) output is correct. But the obvious way to build prod (strong conventions and all) seems to still include them. I noticed this when trying to compare byte size changes in recent prod builds.

This isn't to say anything is busted, but we can improve it.

This is largely a reminder to myself

**Comment by rwjblue** [comment]
Please make this issue actionable. What command did you run that didn't work as expected? What output (filename, snippet, etc) did you look at that was incorrect?
