### ISSUE TITLE
Ember Component Functional Initializing Before The Component It Self.

### ISSUE THREAD

**Issue by shiv86** [emberjs/ember.js#11719]
I have upgraded to the latest version of ember. I noticed a potential issue that when a component function which observes an outercontext attribute it is actually initialized even before the actual component is initialized.

**$ember version**

```
version: 1.13.1
node: 0.12.6
npm: 2.12.1
```

To demonstrate I have the following hbs which inserts the test-component:

```{{test-component parentController=controller}}```

**Previous version of ember**

test-component.js
```javascript
feedLoadedChanged: function(){
        var self = this;
        alert("feedLoadedChanged and self initialized" + self.get('parentController').get('feedLoaded'));
}.observes('parentController.feedLoaded'),
```
In the previous versions of ember the above alert used to work successfully. However in the current version of ember the self/this variable referred to the Window object and NOT the component.

So I thought this was due the feedLoadedChanged function being initialized before the component it self was initialized.

**Current version of ember**

For the current version of ember I made the following changes. The didInsertElement captures the self component into the variable _self and the original alert function is only called if that variable exist.

The code below fixes the issue:

```javascript
export default Ember.Component.extend({
    didInsertElement: function(){
            var self = this;
            self.set('_self', this);
    },

    feedLoadedChanged: function(){
     var self = this.get('_self');
        alert('feedLoadedChanged');
     if(self){
        alert("feedLoadedChanged and self initalized" + self.get('parentController').get('feedLoaded'));
     } else {
        alert("feedLoadedChanged and self NOT initalized");
     }
}.observes('parentController.feedLoaded')
});
```
This is the sequence of alerts which occurrs during application loaded.

feedLoadedChanged
feedLoadedChanged and self NOT initalized
feedLoadedChanged
feedLoadedChanged and self initalizedtrue (this is the original alert)

The initialization of the component function before the component it self is an issue. Locks from IRC chat recommend me using the new component lifecycle hooks: http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html

**Comment by mitchlloyd** [comment]
Maybe you could show this bug with a JS Bin?

The first issue you described was this: The context (`this`) of an observer function inside of a component is `window`. Here is a JS Bin showing the context of an observer with the latest beta. I tried this with 1.13 and saw the same results. The context is the component.

http://emberjs.jsbin.com/gafifawere/1/edit?html,js,output

Reading through the rest of the issue, I don't see anything that appears out of line with how Ember claims to work. However, your narrative and code have a few confusing parts so I might not be following correctly. If you can show running code that will help people figure out what might be going wrong.

Also just as a tip, avoid using observers if at all possible (and it's possible 98% of the time).

**Comment by pixelhandler** [comment]
@shiv86 I'm curious about your use case.

>  I noticed a potential issue that when a component function which observes an outercontext attribute it is actually initialized even before the actual component is initialized.

and as @mitchlloyd says 'there be dragons' with observers. Perhaps this video shows some alternative implementations of your use case: http://www.confreaks.tv/videos/wickedgoodember2015-the-observer-tip-jar

**Comment by shiv86** [comment]
@mitchlloyd will provide a jsbin soon. @pixelhandler thanks for the vide will definitely go through it and attempt not to use observers

**Comment by locks** [comment]
@shiv86 can you reproduce it in a [Twiddle](http://ember-twiddle.com/)?

**Comment by pixelhandler** [comment]
@shiv86 This issue was reported in version 1.13 of Ember. That version was supported for much longer than originally promised and now that Ember has a LTS release it's very unlikely to have any patches applied to the 1.13.x release.

I think there is a workaround or alternate implementation you can try to avoid this issue, correct?

I'll close this out for now.
