### ISSUE TITLE
Remove root `div` for application view in 2.0

### ISSUE THREAD

**Issue by mmun** [emberjs/ember.js#11712]
The top-level application outlet should be "virtual" by default, like all other outlets are. This would make styling easier in some cases. You would also not need an ApplicationView to override the tag name -- you'd just put it in your application template if you needed it.

This would be a breaking change so it needs to happen in 2.0.

**Comment by stefanpenner** [comment]
I think currently the eventDispatcher requires tag root for delegation. When mounted on another element (other then body) the delegation should likely be scoped to the root of the app.

**Comment by rwjblue** [comment]
@stefanpenner -  `rootElement` (which is what the `EventDispatcher` users to attach event listeners) is different than the element created by the app's `ApplicationView`. [Demo JSBin](http://rwjblue.jsbin.com/rwjblue/627)

**Comment by stefanpenner** [comment]
i thought this was inherited to the eventDispatcher. a quick spelunk reveals this is not true.

**Comment by krisselden** [comment]
@stefanpenner the event dispatcher should always dispatch from body, tying this to the rootElement is actually frustrating, I've wished to be able to set the dispatch root apart from the append target.

**Comment by krisselden** [comment]
I'd also love to be able to dispatch from capture. :)

**Comment by krisselden** [comment]
We should just create a unique class for the app instance views instead of class "ember-view" and dispatch using that, this would greatly improve more than one app on the page and/or ember-wormhole stuff or ember-tether.

**Comment by stefanpenner** [comment]
> @stefanpenner the event dispatcher should always dispatch from body, tying this to the rootElement is actually frustrating, I've wished to be able to set the dispatch root apart from the append target.

yes that is what my comment agreed with.

**Comment by rwjblue** [comment]
We missed our chance to do this in 2.0.0. I think at this point we will need an RFC and a path forward.

I will try to tackle the RFC sometime this week. Closing as an issue though, since it is not a bug...

**Comment by drewcovi** [comment]
@rwjblue Did this ever get an RFC? or is there some way to get rid of the root div? Thanks!

**Comment by rwjblue** [comment]
Yep! Take a look at the 3.1 beta blog post for details...

**Comment by drewcovi** [comment]
:+1

**Comment by benedikt-d** [comment]
https://www.emberjs.com/blog/2018/04/13/ember-3-1-released.html
