### ISSUE TITLE
ember 1.13.3 - didInsertElement not fired after rerender (worked in 1.12.1)

### ISSUE THREAD

**Issue by MSzweda** [emberjs/ember.js#11729]
this works as expected in 1.12.1 which is our production environment - we've recently upgraded to 1.13.3 on lesser stage and this came up  
according to the doc:

> didInsertElement: Called when the element of the view has been inserted into the DOM or after the view was re-rendered.

this doesn't happen anymore in the recent version, rerender does not trigger didInsertElement in component

parent template:
```emblem
content-frame content=model.availableBody
```
relevant part of the component
```coffee
ContentFrame = Ember.Component.extend
  contentChanged: Em.observer "content", -> 
    console.log 'observer works correctly and calls rerender()'
    @rerender()

  didInsertElement: ->
    console.log 'this does not get called after rerender() is called in 1.13.3'
    # however it does work at initial insert
    # worked in 1.12, does not in 1.13
```

**Comment by juggy** [comment]
didInsertElement is only called once, didReceiveAttr and willRender are called when  the attrs are refreshed and when the DOM is about to refresh.

And why are you calling rerender? You should not have to do this anyway.

**Comment by MSzweda** [comment]
I'm working on some old code - it was taking html content from a model and inserting it into an iframe, setting heights, etc. It needed to be rerendered when different item was clicked.
Thanks for mentioning willRender, looks like a quickfix with using didRender instead of didInsertElement works in my case, so I will go with that for the time being.

I wanted to signal that a change occured 1.12->1.13 (possibly) that is contradicted by the doc. I didn't see it in the changelog.

**Comment by OrKoN** [comment]
@MSzweda the change is documented here http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_component-lifecycle-hooks I am not sure if the site docs keep up with the changes

**Comment by MSzweda** [comment]
@OrKoN thanks a lot, case solved then :)
