### ISSUE TITLE
[BUG angle-bracket-components] Boolean attrs are coerced to strings

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#11727]
I'm not sure if this is to be expected or not.

Repro:
http://emberjs.jsbin.com/yitaqafusi

**Comment by mixonic** [comment]
@chadhietala definitely seems like a regressions on angles. /cc @tom @wycats

**Comment by rwjblue** [comment]
I am not quite as sure it is a bug, consider the following:

```
<input disabled=false>
```

In that scenario the `<input>` would be `disabled`. This might be annoying, but it is the way boolean attributes work in plain HTML (which is what we are attempting to emulate with angle bracket components, right?).

Using the following works properly in the above JSBin (see [copy here](http://rwjblue.jsbin.com/hukadu/edit?html,js,output)):

```html
<foo-bar defaultBool={{false}} />
```

**Comment by chadhietala** [comment]
Seems weird if you have properties on component or controller that have booleans for property names. You then have to access them by doing `{{'false'}}`. I'm not sure if this even documented or people are aware this works.

**Comment by rwjblue** [comment]
> Seems weird if you have properties on component or controller that have booleans for property names. 

If a person has a `true` or `false` property on a component/controller they likely will have much bigger issues than what we are discussing.  Also, I believe that the handlebars parser interprets `{{false}}` as a specific boolean node, so using `Ember.Component.extend({ 'false': 'stuff' });` wouldn't work today anyways.

**Comment by mmun** [comment]
This is not a bug.

![](https://i.imgflip.com/oc2vi.jpg)

> Seems weird if you have properties on component or controller that have booleans for property names.

You can use {{[false]}} if you are doing crazy things like that.

**Comment by workmanw** [comment]
I don't think passing a value of "false" is really a crazy use case. Maybe I'm missing something.

**Comment by rwjblue** [comment]
@workmanw - The thing that would be crazy, is if you have a property on your controller/component named `true` or `false, something like:

```javascript
export default Ember.Component.extend({
  'true': 'LOL',
  'false': 'HAHAHAAH'
});
```

**Comment by mmun** [comment]
@workmanw Who said it's crazy? Just pass `{{false}}` like with every other value.

**Comment by workmanw** [comment]
Yea, sorry. I thought @mmun's comment was referring to the usage of `defaultValue=false` (or `defaultValue={{false}}`) as a crazy usecase. Got it.

**Comment by chadhietala** [comment]
I'm convinced this is not a bug.
