### ISSUE TITLE
Routable Components Status

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#11721]
It's about two weeks out from the 2.0 stable release and I'm wondering what the status is on routable components. I'm aware that routable components were [pushed back](http://emberjs.com/blog/2015/05/24/another-two-oh-status-update.html#toc_routeable-components) into the a 2.x release, however it appears the soonest they will land is 2.2.0. While this is fine, it's becoming confusing to people as to why they need controllers still and the ergonomics around it are pretty lousy. I've had to explain to numerous people who have taken "2.0.0 training" from @ebryn that routable components are not a thing but they are Coming Soon™. The sooner these can land the better. I don't consider the 2.0.0 programming model to be complete until they are there. Perhaps I should just wait 8 months like I did for HTMLBars. :trollface: 

/cc @tomdale @wycats

**Comment by rwjblue** [comment]
For routable components to land, we need an implementation of the RFC. I know at one point @ebryn was going to work on it, but I'm not sure of the status. 

This isn't really a bug, so likely the RFC is a better place for this conversation.

**Comment by rwjblue** [comment]
> Perhaps I should just wait 8 months like I did for HTMLBars.

Indeed.

**Comment by chadhietala** [comment]
Will post in RFC closing.
