### ISSUE TITLE
Component helper documentation missing

### ISSUE THREAD

**Issue by knownasilya** [emberjs/ember.js#11720]
The documentation existed here: https://github.com/emberjs/ember.js/blob/v1.11.0/packages/ember-htmlbars/lib/helpers/component.js#L14 but since the helper has been moved here: https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/keywords/component.js#L3 there is no longer any documentation.

**Comment by rwjblue** [comment]
Great catch, would you mind submitting a PR to bring them back?
