### ISSUE TITLE
[BUG angle-bracket-components] Unstable Top Level Elements 

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#11728]
In the following jsbin there are 2 weird behaviors.

1. Event handlers can become detached
2. Top level DOM becomes unstable for no reason

I believe this is due to having an if helper on the top level element. I noticed that class names do not get concated with the existing `ember-view` class which may be the reasoning around the event handlers being removed.

Repro:
http://emberjs.jsbin.com/naqodocahe/edit?html,css,js,output

**Comment by pixelhandler** [comment]
@chadhietala is there a way to add some logging to your jsbin example that demonstrates the event handlers no longer being attached. 

What are the steps you noticed that may have contributed to the event handler becoming detached?
How is the top level DOM unstable?
Would a screen recording, posted on dropbox or something, showcase the unstableness to help this issue be reproducible?

**Comment by rwjblue** [comment]
@chadhietala - Can you submit a failing test PR for this?  I'll add it to the checklist in #12011...

**Comment by wycats** [comment]
@rwjblue our branch is addressing exactly this case; it happens when the `ember-view` class becomes overridden by the inner template, which is really just a very special case of a much larger problem.

**Comment by rwjblue** [comment]
@wycats - AWESOME!  Then your branch will make the requested failing test pass :wink:

**Comment by chadhietala** [comment]
Confirm this was fixed in https://github.com/emberjs/ember.js/pull/12011
