### ISSUE TITLE
Ember 1.13 Route doesn't refresh model on paging

### ISSUE THREAD

**Issue by kottenator** [emberjs/ember.js#11726]
I'm using Ember w/ data v1.13

I have a Route:

```js
// app/routes/items.js
import Ember from 'ember';

export default Ember.Route.extend({
    queryParams: {
        page: {
            refreshModel: true
        }
    },

    model(params) {
        return this.store.query('item', params);
    },

    actions: {
        pagination(page) {
            this.transitionTo({
                queryParams: {
                    page: page
                }
            });
        }
    }
});
```

**This doesn't work** - AJAX is not sent, data isn't updated, nothing happens. It's fixed if I add:

```js
// app/controllers/items.js
import Ember from "ember";

export default Ember.ArrayController.extend({
    queryParams: ["page"]
});
```

But then it gives me deprecation warning - *"DEPRECATION: Ember.ArrayController is deprecated."*

I'm new to Ember and probably I'm doing something wrong. Could you help me?

**Comment by jcope2013** [comment]
ember controllers are needed for listing query params but will be deprecated in the 2.0 series once routable components land and moved to the route, until then change it to just a regular controller as arrayController and objectController are now deprecated and will be removed in 2.0 series and it is recommended that you only use Controller moving forward

```

import Ember from "ember";

export default Ember.Controller.extend({
    queryParams: ["page"]
});

```

**Comment by kottenator** [comment]
Thanks for the advice, not the warning has gone.

It was pretty complex for me to figure out how to make it work... I put many hopes on Ember 2.0, I hope it will simplify a lot of things.

Btw, in [Ember v1.12 docs](http://guides.emberjs.com/v1.12.0/routing/query-params/) all the route querying examples are broken (links at the bottom)
