### ISSUE TITLE
1.13.4 breaks some component unit tests

### ISSUE THREAD

**Issue by thec0keman** [emberjs/ember.js#11738]
In moving from 1.13.3 -> 1.13.4, some of our unit tests are breaking.

It is a bit hard to nail down exactly because it happens in random places, but the context for the test itself has `subject` set to nil:
```
test('it renders', function(assert) {
  var subject = this.subject();
});

=>

TypeError: this.subject is not a function
    at Object.<anonymous> (http://localhost:7357/assets/app.js:72630:26)
    at Object.wrapper (http://localhost:7357/assets/test-support.js:1821:29)
    at Object.Test.run (http://localhost:7357/assets/test-support.js:3502:28)
    at http://localhost:7357/assets/test-support.js:3631:11
    at process (http://localhost:7357/assets/test-support.js:3190:24)
    at begin (http://localhost:7357/assets/test-support.js:3235:2)
    at http://localhost:7357/assets/test-support.js:3251:4
```

Dropping in a debugger, and the test context is clearly different:
![image](https://cloud.githubusercontent.com/assets/4037898/8666777/ce917e7a-29aa-11e5-8e9a-60156cc92f5e.png)

**Comment by stefanpenner** [comment]
Can you provide a repo that demonstrates this. That will make it more actionable

**Comment by twokul** [comment]
@thec0keman which version of `qunit` are you on? in the newest version you need to specify `integration: true` in order to use `this.subject()`

**Comment by stefanpenner** [comment]
@twokul i suspect that is the issue.

**Comment by thec0keman** [comment]
Running 0.4.1.   We are using the `needs` array which should be flagging them as integration, which works for most of the tests most of the time, and all of the tests in 1.13.3.

@stefanpenner  I'll work on extracting some of the failing tests into a repo.  Thx.

**Comment by stefanpenner** [comment]
@thec0keman i believe your bug isn't with ember, and rather with the https://github.com/switchfly/ember-test-helpers

**Comment by mixonic** [comment]
@thec0keman the default test helper behavior changed from unit to integration a patch release of ember-test-helpers. I agree with @stefanpenner you may be hitting that.

Please confirm you bumped test-helpers as well to cause this. You can flag all your old component test modules `unit: true` to restore the old behavior.

**Comment by thec0keman** [comment]
Thanks for the suggestions.  After digging deeper, the problem was being obscured by something in our app munching RSVP errors for tests.  `this.subject` being null was a symptom of the prior test not tearing down correctly, so the app root element was trying to be reused.  

The real problem is a template like the following:
```
{{#if savedOption}}
  <button {{action "removeOption" on="click"}}></button>
{{else}}
  {{input value=inputValue}}
{{/if}}
```
where `removeOption` simply nullifies `savedOption`.  There is some weird interplay between removing the `button` element and adding the input that raises:
```
Uncaught Error: Assertion Failed: BUG: Render node exists without concomitant env.
```

I can post a repo demonstrating this if desired.

**Comment by stefanpenner** [comment]
This appears to be an issue with the test helpers. They should not end up in a bad state like this. Can you open the issue on that repo?

**Comment by thec0keman** [comment]
Absolutely.  Wouldn't the `BUG: Render node exists without concomitant env.` be Ember related though?

**Comment by rwjblue** [comment]
A recent update to test helpers should properly handle errors in setup (and not fail like this).

**Comment by rwjblue** [comment]
@thec0keman - Yes, I would say that would still be an ember issue (though not really related to this issues title or description), can you make a demo JSBin that reproduces?

**Comment by thec0keman** [comment]
I cannot reproduce this in JSBin.  It only seems to be happening with testing, so I'll move the issue to ember-test-helpers  [(here)](https://github.com/switchfly/ember-test-helpers/issues/76).

**Comment by egemon** [comment]
If somebody will every look at the similar issue, I had had one, because my willDestroyElement() hook had threw exception, so element was not destroyed.
