### ISSUE TITLE
[2.0.0-beta.2] `this` undefined in Ember.computed.map callback

### ISSUE THREAD

**Issue by SebastianEdwards** [emberjs/ember.js#11736]
`this` is undefined in the `Ember.computed.map` callback. Worked up until the latest beta.

**Comment by stefanpenner** [comment]
looking

**Comment by stefanpenner** [comment]
yup: https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/computed/reduce_computed_macros.js#L176

**Comment by stefanpenner** [comment]
writing a test now

**Comment by stefanpenner** [comment]
submitted fixed

**Comment by SebastianEdwards** [comment]
Wowzers, that is an impressive response time :smile: thanks Stefan
