### ISSUE TITLE
Cleanup Ember.get 

### ISSUE THREAD

**Issue by mmun** [emberjs/ember.js#11733]
- [ ] Remove support for globals: `Ember.get('App.foo')` and `Ember.get(null, 'App.foo')`
- [ ] Remove support for `this`: `Ember.get(object, 'this.foo')`
- [ ] Enforce strict usage with two arguments: `Ember.get(object, path)`
  - assert object is a non-null object & path is a string.

**Comment by martndemus** [comment]
I'm going to take a stab at this, if that's ok.

**Comment by stefanpenner** [comment]
> I'm going to take a stab at this, if that's ok.

ofcourse :)

**Comment by btecu** [comment]
Does this mean `this.get('foo')` will be deprecated?

**Comment by stefanpenner** [comment]
@btecu no

**Comment by martndemus** [comment]
Does `Ember.set` require the same cleanup?
