### ISSUE TITLE
Component hook for yielded content change

### ISSUE THREAD

**Issue by mitchlloyd** [emberjs/ember.js#11731]
In the current version of Ember I'm using (2.0.0-beta.1), none of the component lifecycle hooks fire when the yielded content of a component change. This created a bug in an application when I refactored a component from one that received its content as attributes to a block component:

```handlebars
{{! lifecycle hooks fire when model changes}}
{{doc-viewer article=model}}

{{! hooks no longer fire}}
{{#doc-viewer}}
  {{model}}
  {{! other markup things in here}}
{{/doc-viewer}}
```

The fact that the lifecycle hooks don't fire makes sense. The `attrs` of the component have not changed. However, what we have in `doc-viewer` seems like a valid use case. Whenever the yielded content changes, some DOM-manipulating behavior has to occur (syntax highlighting and updating URLs in the article). Here is [another example](http://stackoverflow.com/questions/29414189/observe-detect-change-in-ember-component-yield-block) where someone wanted to create an isotope wrapper component.

I was wondering how this works in React for components like [Magic Move](https://github.com/ryanflorence/react-magic-move). It appears that changing inner content works through `props.children` and fires hooks like `componentWillReceiveProps` (not sure about this).

Next I wondered how liquid-fire handles this sort of thing. It [uses `window.MutationObserver` to watch for changes on the component's element and call its own didMutate hook](https://github.com/ef4/liquid-fire/blob/85208d04238b54c38ed99be824d3ea6dafbdf403/addon/components/liquid-measured.js).

The current workaround I'm using is:

```handlebars
{{#doc-viewer triggerLifecycleHooks=model}}
  {{model}}
{{/doc-viewer}}
```

Would it be possible or practical to add a hook that would work here? Is there a better practice to handle this use case?

**Comment by mmun** [comment]
This is a weird use case. Ideally a component shouldn't interact with the block it is yielding to. It seems weird to have a hook that is triggered if any of your children (or grandchildren?) are rerendered. Using a MutationObserver seems correct.

**Comment by pixelhandler** [comment]
@mitchlloyd I'm curious if there may be more traction on discussing solutions for how yielded context should/does interact with the outer component(s). 

I imagine there also may be some solutions already being discussed in the current work on the website guide updates here https://github.com/emberjs/guides/tree/master/source/components

**Comment by mitchlloyd** [comment]
Just saw that this was still open. I think the best solution here is:

```
{{#doc-viewer document=model as |document|}}
  {{document}}
{{/doc-viewer}}
```

In other cases using various strategies to observe DOM mutation does seem to make sense.
