### ISSUE TITLE
Ember.beforeObserver is missing on 1.13.4

### ISSUE THREAD

**Issue by juggy** [emberjs/ember.js#11742]
Please see http://jsbin.com/hifopu/4/edit?html,js,output

The console output is: ```Uncaught TypeError: Ember.beforeObserver is not a function```

**Comment by stefanpenner** [comment]
Hmm strange. It should be deprecated, but not removed

**Comment by juggy** [comment]
Must be related to https://github.com/emberjs/ember.js/commit/399a84dfa30917b44be9345aa54cc81b2759c000

**Comment by stefanpenner** [comment]
Ya likely. I'm not going to be able to look at this today. It should be relatively easy to piece together the differences. Mind submitting a fix?

**Comment by juggy** [comment]
Voila.

**Comment by juggy** [comment]
Fix was merged to release. Thx.
