### ISSUE TITLE
1.13.x Component helper does allow rendering built-in input components

### ISSUE THREAD

**Issue by OrKoN** [emberjs/ember.js#11740]
For example,

```
{{component "textarea"}}
```

will throw an error: Uncaught Error: Assertion Failed: You cannot use 'textarea' as a component name. Component names must contain a hyphen. See [jsbin](http://emberjs.jsbin.com/gididefati/1/edit?html,css,js,console,output)

Probably an exception should be done for the built-in components. Or is there a reason why these cannot be rendered using the component helper?

**Comment by rlivsey** [comment]
`"textarea"` is actually a keyword, not the name of the underlying component which is [`-text-area`](ember.js/packages/ember-htmlbars/lib/keywords/textarea.js)

`{{component "-text-area"}}` should do the trick, but the leading `-` means it's a private component, so YMMV.

**Comment by stefanpenner** [comment]
Prefixed with a dash is private
