### ISSUE TITLE
[BUG RELEASE & BETA] Detached DOM Trees Between Application Runs

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#11748]
@trentmwillis and I believe there are memory leaks that only arise when running acceptance tests where a new application instance is created for each test. This has resulted in not being able to run our test suite (3500 tests) end to end because we simply run out of memory and fall over. To reproduce run the tests.

In the repro repo you will see something like the following: 

![](http://i.imgur.com/VDcLTB3.png)

This is 100 acceptance tests ran in a series. Both the listeners and nodes will continue to rise and only drop a fraction when GC comes along.

If a heap snapshot is taken you see several detached DOM trees as well

![](http://i.imgur.com/oEDN4Ky.png)

I have tested in both 1.13.4 and 2.0.0-beta-2.

__Update 7/15__
After looking at this with Stef last night, we concluded we should be have more DOM nodes retained per test as the test harness UI adds a row. However there seems to be retention from app instances in certain cases.

/cc  @stefanpenner @wycats 

__Repro Repo__
https://github.com/chadhietala/leaky-mcleakerson

**Comment by stefanpenner** [comment]
Thanks. I suspect some misalignment with the app and the app instances is leaking something likely the instance

**Comment by chadhietala** [comment]
It appears that `setupForTesting` introduces retained DOM nodes.

Without `setupForTesting` 100 test runs

![](http://i.imgur.com/dN0tsKS.png)

With `setupForTesting` 100 test runs

![](http://i.imgur.com/WAURz2a.png)

With `setupForTesting` looks really strange.

**Comment by stefanpenner** [comment]
I believe I have found and spiked solutions to the issues reported in the provided example.

This afternoon, I will start applying the appropriate solutions to the various offending projects.

![screen shot 2015-07-20 at 12 06 56 pm](https://cloud.githubusercontent.com/assets/1377/8784638/e285abc2-2ed7-11e5-923a-c35db66b346d.png)

**Comment by stefanpenner** [comment]
first patch: https://github.com/ember-cli/ember-export-application-global/pull/13

**Comment by stefanpenner** [comment]
Alright, I think this leak is fixed. Kinda many discrete parts, so we can close it now, or close it when all the above things are merged an released.

**Comment by stefanpenner** [comment]
It's worth noting, this problem is partially related to the fact that we don't purge modules are they are included. Doing so would only fix a small part of the larger leak, but maybe something worth exploring down the road.

**Comment by stefanpenner** [comment]
We are going to take an additional approach and fix the issue in QUnit, so we can release the modules and not force people to `null` out each var.

related issue: https://github.com/jquery/qunit/issues/841

\w @cibernox
