### ISSUE TITLE
Consider making `routeName` in `Ember.Route` public

### ISSUE THREAD

**Issue by SaladFork** [emberjs/ember.js#11759]
This private API is one I use frequently in my applications to programmatically get the current route's name to pass along to public APIs such as `paramsFor` or `modelFor`. This is especially useful for writing re-usable route code which needs to know the current route's name.

**Comment by davidgoli** [comment]
:+1:

**Comment by lukemelia** [comment]
I also find myself using this at least a few times in most apps.

**Comment by rwjblue** [comment]
@SaladFork - Just discussed at core team meeting, could you submit a `[DOC release]` PR updating to `@public`?
