### ISSUE TITLE
Handlebars Helpers Docs Missing Since 1.13.4?

### ISSUE THREAD

**Issue by jherdman** [emberjs/ember.js#11755]
I noticed today that the [Handlebar helpers docs](http://emberjs.com/api/classes/Ember.Handlebars.helpers.html) have gone missing since 1.13.4 was released. Is this intentional?

**Comment by mixonic** [comment]
Something is not right, cc @rwjblue This page:

* http://emberjs.com/api/classes/Ember.Handlebars.helpers.html

Should probably not exist, and this page:

* http://emberjs.com/api/modules/ember-templates.html

Should include `Ember.Helper.helpers`. Ugh, perhaps someone did not actually preview their documentation changes.

**Comment by rwjblue** [comment]
The docs were moved to http://emberjs.com/api/classes/Ember.Templates.helpers.html (because the `Ember.Handlebars` namespace is going away).

`linkTo`, `bind-attr`, and `bindAttr` need to be updated to use the new location...

**Comment by jherdman** [comment]
This looks to be resolved in the latest release to my eyes. Closing.
