### ISSUE TITLE
Ember 1.13.4 Component

### ISSUE THREAD

**Issue by pit-rpg** [emberjs/ember.js#11753]
when extend a custom Component or extend Ember.Component with mixin hooks: "didInsertElement", "willDestroyElement" not called... I need them in inherited class i not really shor is a bug or its should be....

**Comment by rwjblue** [comment]
Can you provide a JSBin demo showing what you mean?

**Comment by pit-rpg** [comment]
http://emberjs.jsbin.com/zejese/edit?js,console,output

**Comment by pit-rpg** [comment]
sorry my mistake ...
