### ISSUE TITLE
[BETA angle-bracket-components] Detect Mutative APIs On Attrs

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#11757]
I believe there should be a build time warning or failure if you are using mutative APIs on attrs in angle bracket components. In React props can be mutated as well but their is tooling around this suggests that you should not mutate props.

The example below shows mutating both arrays and objects. Arrays are clearly worst that mutating objects as object properties are not propagated.  It becomes hard to reason if the attrs can be mutated as they are passed along, we should do our utmost to shorten the conceptual gap between the static program and the dynamic process :wink:.

http://emberjs.jsbin.com/xahidifube

**Comment by stefanpenner** [comment]
this may be an RFC issue

**Comment by chadhietala** [comment]
Will close for now.
