### ISSUE TITLE
Remove Ember.View support when not using ember-legacy-views addon.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#11775]
* Only export the following when `Ember.ENV._ENABLE_LEGACY_VIEW_SUPPORT` is set:
  * [x] `Ember.CoreView` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/main.js#L65) removed in https://github.com/emberjs/ember.js/pull/11794
  * [x] `Ember.View` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/main.js#L66-L69) removed in https://github.com/emberjs/ember.js/pull/11794
  * [x] `Ember.Select` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/main.js#L74) removed in https://github.com/emberjs/ember.js/pull/11794
  * [x] `Ember._Metamorph` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/main.js#L86) removed in https://github.com/emberjs/ember.js/pull/11794
  * [x] `Ember._MetamorphView` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/main.js#L87) removed in https://github.com/emberjs/ember.js/pull/11794
  * [x] `Ember._LegacyEachView` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/main.js#L88) removed in https://github.com/emberjs/ember.js/pull/11794
* Only add the following AST Transforms when `Ember.ENV._ENABLE_LEGACY_VIEW_SUPPORT` is set:
  * [x] `TransformEachIntoCollection` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/main.js#L28)
  * [x] `DeprecateViewAndControllerPaths` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/main.js#L37)
  * [x] `DeprecateViewHelper` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/main.js#L38)
* Only add the following keywords/helpers when `` is set:
  * [x] `{{view}}` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/env.js#L94)
  * [x] `legacyEachWithControllerHelper` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/main.js#L80)
  * [x] `legacyEachWithKeywordHelper ` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/main.js#L81)
* Fix all the tests. :trollface:

**Comment by rwjblue** [comment]
I believe that @martndemus was interested in this one...

**Comment by martndemus** [comment]
![ITS A TRAP](http://gamesday.ca/wp-content/uploads/2011/07/ackbar.gif)

**Comment by rwjblue** [comment]
CONFIRM

**Comment by martndemus** [comment]
Hiding `Ember.View` behind a feature flag is easy. Finding a way to reload Ember with a feature flag enabled seems impossible. How was this done with other feature flags?

**Comment by martndemus** [comment]
![CELEBRATION](http://www.wired.com/wp-content/uploads/2014/05/deathstar-exploding-ft.jpg)

**Comment by mixonic** [comment]
![well done](http://i.imgur.com/9IvAT.jpg)

**Comment by pixelhandler** [comment]
@rwjblue perhaps add "Cleanup" label to this issue.

**Comment by rwjblue** [comment]
This was all fixed by @martndemus a few days.

**Comment by justinaray** [comment]
I came across this when I finally got around to upgrading my app to 2.0.  I was surprised to find that the deprecation is listed as `until: 2.4` but that you need the ember-legacy-views addon to actually utilize the deprecated classes, etc.

If someone is filtering out only 2.0 deprecations to make the jump, they could easily miss View-based deprecations.  Even worse if they missed the blog post and didn't know about the addon.

Sorry to comment on an old issue, but didn't know if this should be a new issue or added here.  Happy to open an issue and/or PR if you think it worthwhile.

Despite a little confusion with this one, feature-flag deprecations FTW!!! ;)
