### ISSUE TITLE
Deprecate using get/set with global lookup or with 'this' in path.

### ISSUE THREAD

**Issue by martndemus** [emberjs/ember.js#11789]
##### Global lookup
- [x] Deprecate `get` with global lookup. (`get('Global.foo')` and `get(null, 'Global.foo')`)
- [x] Deprecate `set` with global lookup. (`set('Global.foo', value)` and `set(null, 'Global.foo', value)`)

##### This with a special meaning
- [x] Deprecate `get` with this special meaning. (`get(obj, 'this.foo')`)
- [x] Deprecate `set` with this special meaning. (`set(obj, 'this.foo', value)`)

##### Strict arguments
- [x] Deprecate not strictly passing in two arguments to `get`, that are an object and a key-name.
- [x] Deprecate not strictly passing in three or four arguments to `set`, that are an object, a key-name, a value and a optional tolerant flag.

**Comment by martndemus** [comment]
cc @mmun

**Comment by mmun** [comment]
Wow. Awesome!

**Comment by krisselden** [comment]
@mmun I thought we were removing this stuff from 2.0?

**Comment by stefanpenner** [comment]
> @mmun I thought we were removing this stuff from 2.0?

yes, that is why the deprecations needed to exist in 1.13.x
