### ISSUE TITLE
Action helpers in Component bubbling.

### ISSUE THREAD

**Issue by jhr007** [emberjs/ember.js#11783]
I *think* I'm seeing a bug. 

Are `{{action}}` helpers supposed to bubble past the component that wraps them? 

### Background: 
http://emberjs.jsbin.com/nekulolovo/1/edit?html,output

I made a JSON Inspector using components to loop over key/vals. 

* `json-inspector` (routes to one of depending on typeOf passed in object ) 
  * `json-inspector-object` ( prints key, then calls `json-inspector` to display value)
  * `json-inspector-array` ( prints index, then calls `json-inspector` to display value)
  * `json-inspector-primitive` (finally displays value on right side of ':')

When you click on the formatted json output it should bubble up the path/route that value is at. Ex: `yourVar['batman']['car'][0]['name']` 

Each component has an `updatePath` action that sends the path up. 

### Problem
When I click a `<div {{action "updatePath" path }} > ...</div>`  it's passing the path back up the nested components using a passed in action like it should, but then it triggers this action at a higher level sending up that higher/shorter path. 

### Problem Observed when: 
Note:
* Path - The path being sent up from original context. 
* thisPath - The path currently logging the message. 

I click on bruce wayne in the output and get: 

```
"in:ji-primitive - path: yourVar['batman']['name'] - thisPath = yourVar['batman']['name']"
"in:ji-object - path: yourVar['batman']['name'] - thisPath = yourVar['batman']"
"in:ji-object - path: yourVar['batman']['name'] - thisPath = yourVar"

---->  should stop here, but doesn't....  and now passes in the higher context. 

"in:ji-object - path: yourVar['batman'] - thisPath = yourVar['batman']"
"in:ji-object - path: yourVar['batman'] - thisPath = yourVar"
"in:ji-object - path: yourVar - thisPath = yourVar"
```

### JSBin
http://emberjs.jsbin.com/xetunubima/1/edit?console,output

**Comment by jhr007** [comment]
Here's an easier example of nested `<div>` tags with `{{action ...}}`s: 
http://emberjs.jsbin.com/luribapine/1/edit?html,js,console,output
Clicking block 3 shows that the action is called from each component template. `sendAction` is commented out so only the `{{action}}` is left to bubble.
```
"mixin.theAction called from block 3 with value: 3"
"mixin.theAction called from block 2 with value: 2"
"mixin.theAction called from block 1 with value: 1"
```

If this `bubbles=false` is added to the `{{action}}`: 
```
"mixin.theAction called from block 3 with value: 3"
```

Some other examples written before the previous... leaving as a reference to scenarios tested. 

Here's an easier example of nested `<div>` tags with `{{action ...}}`s 
http://emberjs.jsbin.com/kodozorive/1/edit?html,console,output
Clicking block 3 gives: 
```
"3 says hello from 3"
"3 says hello from 2"
"3 says hello from 1"
"3 has hit  the controller"
"2 says hello from 2"
"2 says hello from 1"
"2 has hit  the controller"
"1 says hello from 1"
"1 has hit  the controller"
```

If you add bubbles=false to the `{{action}}` the event doesn't bubble:
http://emberjs.jsbin.com/walavupixu/1/edit?js,console,output
```
"3 says hello from 3"
"3 says hello from 2"
"3 says hello from 1"
"3 has hit  the controller"
```

Here's another example using `{{action ...}}` on a `<button>` nested inside `<divs>` with `action`. 
http://emberjs.jsbin.com/morazazehu/1/edit?html,js,console,output

```
same output as first
`

**Comment by mixonic** [comment]
@jhr007 I believe this is expected. An action you attach to an inner DOM node does not negate an action handled on a parent DOM node.

If you want to handle that kind of event bubbling, using DOM event handlers (with access to the event and bubbling controls) may be more appropriate.

**Comment by jhr007** [comment]
Thanks! 

I completely misread the guide to mean the event wouldn't bubble out of the component. :sweat_smile:
