### ISSUE TITLE
Passing computed property through to a component's template results in memory leak

### ISSUE THREAD

**Issue by jerel** [emberjs/ember.js#11802]
Using Ember 2.0.0-beta.2 the following example results in components stuck in a `destroying` state. My app adds and removes "items" from the model frequently.

``` js
// models/item.js
export default DS.Model.extend({
  speed: attr(),
  moving: function() {
    return this.get('speed') > 0;
  }.property('speed'),
});
```

``` html
<!-- route template where the model is an array of items -->
{{#each model as |item index|}}
  {{test-item instance=item}}
{{/each}}
```

``` js
// test-item.js
export default Ember.Component.extend({
  moving: Ember.computed.readOnly('instance.moving'),
});
```

``` html
<!-- test-item.hbs -->

<!-- leaks (prevents component from destroying)-->
<div class="{{if instance.moving 'moving' 'stationary'}}"></div>

<!-- does not leak (component is destroyed) -->
<div class="{{if moving 'moving' 'stationary'}}"></div>
```

Using a computed alias as shown above fixes the issue for me but I suspect this is a bug. If someone wants to work on this and would like memory profile dumps I can provide them.

**Comment by stefanpenner** [comment]
@jerel can you provide a demo application that demonstrates this? That would make this actionable

**Comment by stefanpenner** [comment]
Also be sure to test again canary.

**Comment by jerel** [comment]
Sure, sorry I didn't include that in the initial report. [Here is a jsbin](http://emberjs.jsbin.com/lamuwu/edit?html,js,output) using canary that demonstrates the problem. Note the html comment.

I just noticed now that it only seems to happen when the template tag is in an attribute. If the tag is inside an element teardown works fine.

**Comment by stefanpenner** [comment]
@krisselden I am pretty sure this is the leak we discussed the other day. Where chains can orphan child-nodes.

I'll try to get a failing test together this afternoon.

**Comment by stefanpenner** [comment]
After comparing two heap dumps (with and without leak) I am more confident in my above statement.

Going to attempt an isolated test next.

**Comment by stefanpenner** [comment]
interesting this as i explore this example further. It appears we are leaking every second set of listeners, this may indicate our cleanup code is enumerating by the wrong offset...

Quick little screenshot.

![screen shot 2015-07-27 at 11 43 34 am](https://cloud.githubusercontent.com/assets/1377/8914528/c2d07816-3454-11e5-96d1-ab6a7cf28413.png)

time for lunch.

**Comment by stefanpenner** [comment]
yesterday was quite busy (for other reasons) I ended up with a more reduced example: https://github.com/stefanpenner/_another_leak (and a failing test)

I'll find some time to transpose this into a test in the ember test suite.

**Comment by stefanpenner** [comment]
I have been swamped with other perf stuff. Hopefully get to this again soon.

**Comment by raytiley** [comment]
I think this explains a pretty gnarly leak in our app, sorry for the plus one comment, just want to follow along.

**Comment by raytiley** [comment]
@rwjblue has a fix incoming for this :beers:

**Comment by rwjblue** [comment]
See https://github.com/emberjs/ember.js/pull/12256.

@raytiley - Thanks for working with me to figure out the issue and fix.
