### ISSUE TITLE
ContainerView template is broken without `ember-legacy-views` addon.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#11818]
Maybe this is fine, I haven't thought through it too much yet, but the [container view template](https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/templates/container-view.hbs) uses `{{view someChildView}}` and does not work with 2.0.0-beta.3.

@mixonic - Do you have an opinion here? Should `Ember.ContainerView` also be conditionally exported only when `ember-legacy-views` addon is present?

**Comment by rwjblue** [comment]
I have thought a bit more about this, and I think we should add a deprecation for `Ember.ContainerView`  just like for [Ember.View](https://github.com/emberjs/ember.js/blob/stable/packages/ember-views/lib/views/view.js#L1546-L1551) in 1.13.x.

* [ ] Expose `Ember.ContainerView` as a deprecated `ContainerView` when not using the ember-legacy-views addon. This will need to land in master and cherry-picked down into stable.
* [ ] Remove export in beta and master when addon is not used.

@martndemus - Do you want to tackle this?

**Comment by martndemus** [comment]
@rwjblue sure!

**Comment by mixonic** [comment]
Big confirm. `Ember.ContainerView` should absolutely be deprecated in 1.13 and removed in 2.0

**Comment by martndemus** [comment]
Is there a upgrade path from container view?

**Comment by rwjblue** [comment]
Basically move from programmatically manipulating childViews to something like the container view template (`{{each}}` with `{{component}}` helper).

**Comment by mixonic** [comment]
@martndemus definitely seems deprecation guide worthy. In many cases an `{{#each` is sufficient. However there are two parts to a complete upgrade path:

* First, you must be able to dynamically render a component. The `{{component` helper addresses this.
* Second, you must be able to dynamically decide arguments. There is a proposal on handlebars for a syntax: https://github.com/wycats/handlebars.js/issues/1050 if we get that approved, then we can add the operator to Ember in time for 2.2 (at the latest).
