### ISSUE TITLE
instance initializer not being called during testing

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/ember.js#11811]
using ember-cli 0.2.7:

```javascript
import Ember from 'ember';
import {
  module,
  test
} from 'qunit';
import startApp from 'insm-ui/tests/helpers/start-app';

var application;

module('Acceptance: BaseTemplateInitialize', {
  beforeEach: function() {
    application = startApp();
  },

  afterEach: function() {
    Ember.run(application, 'destroy');
  }
});

test('Image template has been added to store', function(assert) {
  var store = application.__container__.lookup('store:main');

  var templates = store.all('template')
                  .toArray()
                  .filterProperty('displayName', 'Image');

  assert.equal(templates.length, 1);
});
```

The test checks that fixtures got added to the store in the instance initializer. A breakpoint in the instance initializer does not get hit during the test run. Any ideas?

**Comment by stefanpenner** [comment]
> using ember-cli 0.2.7:

which version of ember?

**Comment by stefanpenner** [comment]
ah, quickly read your issue. I believe doesn't fully initialize until the first `visit` occurs, this is to be sure the app boots directly into the URL specified in the test.

**Comment by BryanCrotaz** [comment]
Aha - that got it.
Rewrote test as
```javascript
test('Image template has been added to store', function(assert) {
  var store = application.__container__.lookup('store:main');

  visit('/');
  andThen(function() {
    var templates = store.all('template')
                    .toArray()
                    .filterProperty('displayName', 'Image');

    assert.equal(templates.length, 1);
  });
});
```

Perhaps that nugget should go in the docs where instance-initializers are explained?

**Comment by stefanpenner** [comment]
I am unsure where this should go. cc @trek / @locks

**Comment by BryanCrotaz** [comment]
Maybe a note against the deprecation warning for a start - that's where it's going to hit most users right now who are migrating? Separately in the main doc for instance initializers?

**Comment by mixonic** [comment]
Fetching the store from the application in this manner is definitely bending a lot of rules- most especially relying on semantics for an api that is flagged double-underscore.

I do not think we need to add this to the deprecation guide- this issue is likely helpful enough for wayward souls.

I'm going to close this issue for now, but please feel free to reopen if I have missed something.

**Comment by opsb** [comment]
We're using an in-browser data-store which we setup at the start of each test. This seems like a valid way to set things up (unless you're suggesting that even initial test state should be created using the UX). It also seems reasonable to expect that the startApp helper actually starts the app up. Is there some other way to kick off the instance-initializers without having to first visit a page?
