### ISSUE TITLE
Observer of bound property within component invoked twice (since 1.13)

### ISSUE THREAD

**Issue by timkendrick** [emberjs/ember.js#11821]
- Create a component that has a property binding
- Within the component, add a callback that observes the bound property
- Embed the component in a parent template, and hook the binding up to a field on the parent controller
- Update the property on the parent controller
- The component's observer callback is invoked twice

**Example:** http://emberjs.jsbin.com/qimagaciqu/edit?html,js,output
Open the console, and click the "next" or "previous" button. `Controller model updated` is only logged once (correct), whereas `Component model updated` is logged twice (incorrect)

This works fine in Ember 1.12.x, but is broken in 1.13.x.

**Comment by stefanpenner** [comment]
I believe this is a duplicate

**Comment by pixelhandler** [comment]
@timkendrick can you take a look at https://github.com//emberjs/ember.js/issues/11638 and see if that is the same issue? would be nice to coalesce this issue into that previously reported one.

**Comment by stefanpenner** [comment]
I will gladly reopen if this is demonstrated to not be a duplicate
