### ISSUE TITLE
One way binding is only effective on initializing

### ISSUE THREAD

**Issue by novtor** [emberjs/ember.js#11823]
Hi, it seems that Ember.computed.oneWay is effective only on initializing, when the original value is modified, the dependent value is not refreshed. JSBin:
http://emberjs.jsbin.com/mazohatago/edit?html,js,output
Type any value in the input field, submit it, the 'qp' and 'qpField' are synced. Click on 'Leave' (at this moment 'qp' is set to null) and then click on 'back to index'. The original value 'qp' is null but the 'qpField' yet holds the stale value.

**Comment by mixonic** [comment]
@novtor Correct. oneWay CP aliases are destroyed when you set a value over them. This is what we mean by "oneWay". I suggest you use the route hooks to set the `qbField` property directly when the page is loaded, that seems more like what you are looking for here.

Controllers are singletons- thus once the oneWay alias has been stomped it remains disconnected. I'm pretty positive this is in the docs.

I'm going to close this, but let me know if I've missed something.

**Comment by novtor** [comment]
Thank you @mixonic for info, did not see it in the docs, will look for it

**Comment by novtor** [comment]
Hi @mixonic, first of all I have not been able to find the doc on the oneWay bindings for controllers. But I am not able to find an appropriate hook for doing what I want. 
I will try to explain what I mean.
The use case is to really bind the queryParams to the template fields in a durable manner, for example, when a user uses a bookmark or clicks on the browser's back button, in this cases the fields got out of sync from the query parameters' values. 
I use a convention in my project where fields in templates have names as a corresponding queryParam with 'Field' suffix so, for example, in a PostController I have 'date' as query parameter and 'dateField' to be bound to the template so the initializing becomes a convention
```javascript
Ember.PostController.reopen({
   date: null,
   dateField: Ember.computed.oneWay('date')
})
```
I tried implementing 'activate' hook but queryParams are not set at this moment nor the controller is initialized, the 'didTransition' hook is not reachable in my app because I think lot of routes use this hook already and even if they bubble the event returning true, this does not result in calling this hook, so this implementation is never called:
```javascript
Ember.Route.reopen({
    actions: {
        didTransition: function () {
            "use strict";
            var controller = this.controller;
            if (controller) {
                var queryParams = controller.get('queryParams');
                if (queryParams) {
                    queryParams.forEach(function (qp) {
                        var qpField = qp + 'Field';
                        var qpFieldValue = controller.get(qpField);
                        if (typeof  qpFieldValue !== 'undefined' && qpFieldValue !== controller.get(qp)) {
                            controller.set(qpField, controller.get(qp));
                        }
                    });
                }
            }
            return true;
        }
    }
}
```
Could you advice easy way of keeping template fields synced with query parameters?
