### ISSUE TITLE
Computed properties new getter/setter in mixin don't access inheritor's properties properly

### ISSUE THREAD

**Issue by justin-hackin** [emberjs/ember.js#11831]
I have some particularly unusual computed properties in a mixin that alter the target property based upon another property.  My code works fine with the old syntax as such

```
regionTop: Ember.computed((key, value, previousValue) ->   
    target = if @.get('isScaleComponent') 
    then 'assetCmp.regionModel.scaleTop'
    else  'regionModel.top'
    if arguments.length > 1
      @.set(target, value)
    @.get(target)
  ).property('isScaleComponent','assetCmp.regionModel.scaleTop','regionModel.top')

  regionLeft: Ember.computed((key, value, previousValue) -> 
    target = if @.get('isScaleComponent') 
    then 'assetCmp.regionModel.scaleLeft'
    else 'regionModel.left'
    if arguments.length > 1
      @.set(target, value)
    return @.get(target)
  ).property('isScaleComponent','assetCmp.regionModel.scaleLeft','regionModel.left')
```

I have changed them to the following 
```
regionTop: Ember.computed('isScaleComponent','assetCmp.regionModel.scaleTop','regionModel.top',
    set:(key, value)->
      prop = if @.get('isScaleComponent') then 'assetCmp.regionModel.scaleTop' else  'regionModel.top'
      @.set(prop, value)
    get: ->
      prop = if @.get('isScaleComponent') then 'assetCmp.regionModel.scaleTop' else  'regionModel.top'
      @.get(prop)
  )

  regionLeft: Ember.computed('isScaleComponent','assetCmp.regionModel.scaleLeft','regionModel.left',
    set: (key, value)->
      prop = if @.get('isScaleComponent') then 'assetCmp.regionModel.scaleLeft' else 'regionModel.left'
      @.set(prop, value)
    get:->
      prop = if @.get('isScaleComponent') then 'assetCmp.regionModel.scaleLeft' else 'regionModel.left'
      @.get(prop)
  )
```

isScaleComponent is a property of the inheriting component.  What I noticed is that @.get('isScaleComponent') is different in the getter than in the setter (it appears to correct on the set and to be wrong on the get, as if its pointing to another component) .  

I am having a hard time debugging further as 'this' in the context of the component mixin is not the component itself which is what may be causing this issue.  I'm sorry I can't reproduce this, I can't find a working fiddle/bin example to work from.

**Comment by pixelhandler** [comment]
@justin-hackin are you able to mimic the scenario in a new jsbin perhaps based off the once from the contributing guides? http://emberjs.jsbin.com/?html,css,js,output

**Comment by stefanpenner** [comment]
the code looks functionality different

```coffee
    if arguments.length > 1
      @.set(target, value)
    @.get(target)
```

vs

```coffee
    set:(key, value)->
      prop = if @.get('isScaleComponent') then 'assetCmp.regionModel.scaleTop' else  'regionModel.top'
      @.set(prop, value)
```

the return values in setters do matter, be sure to port from one form to the other, while maintaining the same return values..

**Comment by justin-hackin** [comment]
Actually, I didn't follow the pattern properly, I need to return value in my set :/ , my bad, please ignore

**Comment by stefanpenner** [comment]
> Actually, I didn't follow the pattern properly, I need to return value in my set :/ , my bad, please ignore

no problem
