### ISSUE TITLE
It appears that toggling inherited checkbox enables private members in api docs

### ISSUE THREAD

**Issue by petey** [emberjs/ember.js#11830]

**Comment by pixelhandler** [comment]
@petey do you have a jsbin as an example to describe in more detail how to reproduce the issue?

**Comment by petey** [comment]
Here's a test case for you:
* Navigate to http://emberjs.com/api/classes/Ember.ArrayProxy.html
* Click on the checkbox labeled inherited
   * All methods disappear
* Click on checkbox labeled inherited
   * More methods appear than existed before (includes private methods)

**Comment by stefanpenner** [comment]
> @petey do you have a jsbin as an example to describe in more detail how to reproduce the issue?

@pixelhandler this ia actually a docs issue.

@petey I believe this should be reported @ https://github.com/emberjs/website

cc @locks

**Comment by stefanpenner** [comment]
relevant HTML: https://github.com/emberjs/website/blob/master/source/_api_options.html.erb
relevant JS: https://github.com/emberjs/website/blob/59837b08c5bbcbe6579094e78c4f0d15d0139a17/source/javascripts/app/api/api.js

**Comment by pixelhandler** [comment]
@petey Perhaps close this issue on the emberjs project and re-open on the https://github.com/emberjs/website project

Also I'm curious if that is an issue with yuidoc in general. 

Have you found a work around? can you refresh the page to see the correct info? I've also noticed some unexpected behavior using the generated YUI docs on the ember website. So I usually just refresh the page.

**Comment by petey** [comment]
Opened: https://github.com/emberjs/website/issues/2264
