### ISSUE TITLE
Ember.View.reopen() from guide for binding data-* attributes doesn't work since I updated ember to 1.13.x

### ISSUE THREAD

**Issue by imaxhung** [emberjs/ember.js#11849]
I just put that code form guide in application route before the upgrade, then start to use `data-*` attributes. Like:

```handlebars
{{input data-parsley-required="true" data-...}}
```

It works fine.

But it doesn't work after the upgrade.

Now, I must put those `data-*` attributes into `Ember.TextField.reopen()`'s `attributeBindings` one by one.
Did I missing something?

**Comment by rwjblue** [comment]
Which specific version of Ember?

**Comment by imaxhung** [comment]
ember 1.13.3
ember-cli 1.13.1

**Comment by stefanpenner** [comment]
@imaxhung it may be helpful if you are able to post a http://emberjs.jsbin.com demonstrating the issue.

**Comment by imaxhung** [comment]
@stefanpenner 
Ok, http://emberjs.jsbin.com/katefuwiju/edit?html,js,output
Check input field, its dom element should contain data-* attribute.But it doesn't.  That's what I say

**Comment by rwjblue** [comment]
The reason for this, is that we export a deprecated version of `Ember.View` to provide a "nice" warning message when you use it.  That deprecated version is placed at `Ember.View`, and is what your example is `reopen`ing.  Unfortunately, we use an internal non-deprecated version as the parent class for all other components and views used internally.  This is why `Ember.View.reopen` does not update/change the attributeBindings as you might expect.

---

To fix this, we would need to override `Ember.View.reopen`  (on the deprecated class that is currently exported as `Ember.View`) somewhere around [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/views/view.js#L1533-L1544).  This custom `reopen` would then call `reopen` on the main parent class as it did before.

**Comment by martndemus** [comment]
I think I can fix this. 
We should probably do the same for ContainerView, Select, etc..

**Comment by mixonic** [comment]
The issue seems be that components inherit from views in 1.13. We can support the fix in #11866 for 1.13, but the same code will break in 2.0 for sure. We should call it out in the release post.

**Comment by imaxhung** [comment]
I am very agree for deprecatting Ember.View.
Just suggest people  to migrate Ember.View to Ember.Component, it's easy and quick.
But I was very confused to something about attributeBindings, even now.
There are many libraries using element's attributes.
Most use cases, we want attributes to be fixed not like classnames. Sometime add or reduce them dynamicly.
We just add attributes to a element which just only needs them.
Why do ember.js reject those additional attributes firstly, then include them in the property attributeBindings one by one, but should accept them all at the beginning by default.
This seems be that we are doing a unnecessary step.
@rwjblue 
Any idea about this in ember 2.0?
