### ISSUE TITLE
Dynamic Segments / Query Params / Loading State Produces error with `cacheValuePrefix`

### ISSUE THREAD

**Issue by spencer516** [emberjs/ember.js#11857]
If a route has a Dynamic Segment, a query parameter, a Child Route with a slow-loading model and a loading template, an error occurs when a non-default query parameter is provided.

Please see http://emberjs.jsbin.com/xahiwi/edit?html,js,console,output 

Clicking on the "CLICK ME!" button produces the error `TypeError: null is not a valid argument for 'in' (evaluating 'cacheValuePrefix in values')` 

Error occurs here: https://github.com/emberjs/ember.js/blob/v1.13.5/packages/ember-routing/lib/ext/controller.js#L155 

This error does not occur in `1.13.2`, but occurs in `1.13.3` and after. 

Likely culprit is: https://github.com/emberjs/ember.js/commit/78c0edb103fb49a3a42b9d0df5cb5eedaa4b790b

**Comment by rwjblue** [comment]
@jmurphyau - Do you happen to have a little time to look into this one?

**Comment by jmurphyau** [comment]
Yep - will do

**Comment by mike-north** [comment]
Just hit this snag as well. Any way I can help expedite a fix?

**Comment by rwjblue** [comment]
@mike-north - I'd start along these lines:

1) failing test case
2) Understand what is failing and why
3) try fixing

Any or all of the above items would be super helpful.

**Comment by jmurphyau** [comment]
I seen that the issue is with `cacheValuePrefix in values` and my first instinct was to check if `values` was an object to fix this problem but I wanted to investigate if `values` being null was valid behaviour or not..

I didn't want to just chuck that check in and in doing so potentially hiding the actual problem..

Haven't had a chance yet but should get to this over the next few days

**Comment by jmurphyau** [comment]
So I don't think `values` should actually be a null value - but wow the scenario/code path is so complex that I've just decided to solve the issue at hand rather then trying to troubleshoot/debug why it's null. See PR #12037

**Comment by tobymarsden** [comment]
The result of `value` being null is that query params are no longer sticky.

As far as I can trace back, [`transition` inside `setup` on Route](https://github.com/emberjs/ember.js/blob/v1.13.8/packages/ember-routing/lib/system/route.js#L1117) is null, when it shouldn't be.
