### ISSUE TITLE
Option to get shorthand helper with array to refire on item property change

### ISSUE THREAD

**Issue by adam-knights** [emberjs/ember.js#11867]
When using an array with the new shorthand helper would it be possible to have an option/way to get it to refire when a property of an item in the array changes?

This JS BIN demonstrates what I am trying to do:

http://emberjs.jsbin.com/fukuha/edit?html,css,js,console,output

If you press 'test' the each knows the property has changed/is of interest and so the list updates, but it still says 'no purple'. If you change the first value to 'purple' from the start then it displays 'found purple' all ok. I'd like a way to tell my helper to refire when .value of an item in the array changes so that the text would also change from 'no purple' to 'found purple'.

(I understand I could write a computed or observer and observe 'model.@each.value', but thought I would see whether this would ever be considered? Or whether this will always be a computed/observer thing?)

**Comment by rwjblue** [comment]
This feels like it will always be something that needs to be implemented (Ember is unlikely to automatically observer the length of every array in the template for example) by the developer. 

You can use the "long form" of the `Ember.Helper` and call `recompute` as needed (when `model.@each.value` changes) from an observer.

Demo: http://rwjblue.jsbin.com/nodawo/1/edit?html,js

**Comment by mixonic** [comment]
In 2.0 you will be able to use:

```
{{if (purple (get model '[]') 'value') 'found purple' 'no purple'}}
```

Example (without ember-data): http://jsbin.com/fulologazo/1/edit?html,js,output

...to watch changes to array contents and still pass the array as an argument. We're still brainstorming better ways of handling this. You can also `set` the model property with the same array, and that would cause a recompute.

To watch a property on an array you must use an observer. We should document the best path for this. I would tweak Robert's suggestion slightly: http://jsbin.com/sanozinewe/1/edit?html,js,output

```js
export default Ember.Helper.extend({
  destroy() {
    if (this.teardown) this.teardown();
    this._super(...arguments);
  },
  setupRecompute(array, property) {
    if (this.teardown) this.teardown();
    var path = `@each.${property}`;
    array.addObserver(path, this, this.recompute);
    this.teardown = () => {
      array.removeObserver(path, this, this.recompute);
    };
  },
  compute([array, property]) {
    this.setupRecompute(array, property);
    return !!array.find((color) => {
      return color.get(property) === 'purple';
    });
  }
});
```

**Comment by rwjblue** [comment]
:+1: - On the tweaks.

**Comment by adam-knights** [comment]
Thanks @rwjblue and @mixonic. The Ember 2.0 looks exciting too. One non obvious thing to me - i looked under `ember help generate` and just see helper with no aliases. Is there still a way to generate in the long form with corresponding working test?

**Comment by rwjblue** [comment]
Not really, but the same style testing that is suggested in alisdair.mcdiarmid.org/2015/06/20/ember-component-integration-tests.html is perfect for testing helpers.  The key is to test the actual template invocation that you intend to use.  

I'd love to get the helper tests update in ember-cli to be integration tests and use this infrastructure.  /cc @trabus

**Comment by rwjblue** [comment]
Also, I'm going to close as it doesn't seem like we have a bug here (correct me if I am mistaken).

**Comment by trabus** [comment]
I'll create an issue to add this for helper tests.
