### ISSUE TITLE
Ember.Select value property stops working after three changes

### ISSUE THREAD

**Issue by nathan-osman** [emberjs/ember.js#11862]
I have [a very simple fiddle](http://jsfiddle.net/6Lqjct9g/3/) that demonstrates the problem:

**Template:**

    <script type="text/x-handlebars">
        {{view "select" content=sItems value=sValue}}
        {{sLabel}}
    </script>

**Application:**

    var ITEMS = ["Item 1", "Item 2"];

    window.App = Ember.Application.create();
    window.App.ApplicationController = Ember.Controller.extend({
        sItems: ITEMS,
        sValue: ITEMS[0],
        sLabel: Ember.computed('sValue', function() {
            return this.get('sValue') == ITEMS[0] ?
                "You picked item 1!" :
                "You picked item 2!";
        })
    });

<sup>* tested with v1.13.5</sup>

I have verified that the bug exists in a number of browsers (IE, Chrom(ium), Firefox, Safarai) on a number of different platforms (OS X, Windows, Linux) and they all exhibit the same behavior - after changing the value of the `<select>` element three times, the data binding between `value` and `sValue` stops working.

**Comment by stefanpenner** [comment]
I believe of a dupe of : https://github.com/emberjs/ember.js/issues/11817

**Comment by nathan-osman** [comment]
Ah, indeed. It's a duplicate - sorry about that.

**Comment by stefanpenner** [comment]
@nathan-osman not a problem, if you have time can you confirm the other issue contains all relevant info ?

**Comment by nathan-osman** [comment]
Just read through the other issue and it does appear to contain all of the relevant details from my issue. The JS Bin sample in the other issue demonstrates the exact same problem.
