### ISSUE TITLE
autocorrect off not working in input helper on mobile safari

### ISSUE THREAD

**Issue by thagul** [emberjs/ember.js#11869]
I've created an input field with attribute autocorrect="off" but it's ignored when I open the page in mobile safari. I've tested it with real iPhone 4s and iOS 8.1.3 but also using simulator with various iPhone and iOS versions.
The page contains just two elements:

    {{input type="search" autocorrect="off"}}
    <input type="search" autocorrect="off">

If I type in the `{{input}}` textfield autocorrect feature is still present, if I type in the standard html input the autocorrect feature is disabled as it should be

I've also created a jsbin to demostrate: http://emberjs.jsbin.com/dawuniluxu/edit?html,js

**Comment by pixelhandler** [comment]
@thagul I see the the input behavior is as expected in desktop Safari. Does, using the developer tools with your mobile device connected the desktop developer tools show the proper html?

I'm curious if this is an Ember Bug or a Mobile Safari Bug

**Comment by stefanpenner** [comment]
I have also seen some issues. With some attributes mutating after initial render. Basically some browsers have bugs that don't accept some attrs set in specific ways.

This could be the result of a fix I introduced in htmlbars directly.

**Comment by thagul** [comment]
The html generated in Mobile Safari for the `{{input}} tag with `autocorrect="off"` is the following
```
<input id="ember292" autocorrect="on" type="search" class="ember-view ember-text-field">
```
while the html generated for the standard `input` tag shown in the first post is
```
<input type="search" autocorrect="off">
 ```

I suppose it's a bug in Ember and not in Mobile Safari because the standard `input` tag works as it should.

**Comment by stefanpenner** [comment]
> The html generated in Mobile Safari for the {{input}} tag withautocorrect="off"` is the following
> 
> <input id="ember292" autocorrect="on" type="search" class="ember-view ember-text-field">

This is totally a mobile safari bug, as chrome and desktop Safari both work as expected. That being said, it is likely something they wont fix quickly, so we may have to find a work-around.

**Comment by stefanpenner** [comment]
Chrome 46.0.2464.0: `'autocorrect' in document.createElement('input') === false`
Safari 8.0.7: `'autocorrect' in document.createElement('input') === false`
Mobile Safari (iOS 8.4 simulator) : Safari: `'autocorrect' in document.createElement('input') === true`

**Comment by stefanpenner** [comment]
this will likely be addressed when we finish the disambiguatation work between attrs and props

**Comment by thagul** [comment]
@stefanpenner I thought that there is something that mobile safari "doesn't like" in the way the input tag is generated when using ember `{{input}}` tag, that's why I've written that it's an ember bug. Using normal `<input>` tag, mobile safari set the right value for autocorrect, it's just when using ember `{{input}}` that `autocorrect=off` is ignored.
