### ISSUE TITLE
Query params can fail if route name is on the object prototoype

### ISSUE THREAD

**Issue by raytiley** [emberjs/ember.js#11877]
Given the following router:

```js
Router.map(function() {
  this.route('watch');
});
```

Query params will fail in Firefox because `watch` is a function on the object prototype. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch

The offending line is here: https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/router.js#L607

This is easily avoided by changing the route name, but is tricky to figure out. This should probably be guarded against with `hasOwnProperty(leafRouteName)`

**Comment by stefanpenner** [comment]
cc @machty

**Comment by stefanpenner** [comment]
this._qpCache should just be Object.create(null)
