### ISSUE TITLE
You must use Ember.set() to set the `currentModel` property

### ISSUE THREAD

**Issue by QuantumKing** [emberjs/ember.js#11873]
I'm setting a binding to the `currentModel` property of a route.
```js
var route = container.lookup('route:' + routeName);
if (route) {
    var obj = Ember.Object.create({
      route: route
    });
    var binding = Ember.Binding.from('route.currentModel.' + property).to('name');
    binding.connect(obj);
    return obj;
}
```
This is run everytime I enter a new route. It works fine the first time I enter a route, but the second time I enter the same route I get an error: `You must use Ember.set() to set the 'currentModel' property`. What is going on here?

**Comment by QuantumKing** [comment]
Calling `binding.disconnect` before entering the route a second time gets rid of the error. Is this really necessary?

**Comment by stefanpenner** [comment]
i don't believe we intend for `route.currentModel` to be observable.

**Comment by QuantumKing** [comment]
Ok, I changed it to
```js
var route = container.lookup('route:' + routeName);
if (route) {
    var obj = Ember.Object.create({
      route: route
    });
    var binding = Ember.Binding.from('route.controller.' + property).to('name');
    binding.connect(obj);
    return obj;
}
```
and everything works fine. Thanks
