### ISSUE TITLE
container.lookup in InstanceInitializer causes "Cannot read property 'lookup' of undefined" error

### ISSUE THREAD

**Issue by mdehoog** [emberjs/ember.js#11879]
The container is no longer available in the ApplicationInstance passed to instance initializers. The issue was introduced in this commit: c353c383b666474e5fb2c2d6fa17934946dcc9ca.

Setting the `ember-registry-container-reform` feature to either `false`/`true` doesn't appear to have any effect.

An example instance initializer that exhibits this issue is `initialize-store-service` in Ember Data: https://github.com/emberjs/data/blob/master/packages/ember-data/lib/instance-initializers/initialize-store-service.js

**Comment by rwjblue** [comment]
Thank you for reporting. 

@dgeb - Could you take a look?

**Comment by dgeb** [comment]
Yep - just saw this. Will get a fix and tests in asap. Sorry @mdehoog and @rwjblue!

**Comment by rwjblue** [comment]
No worries, that's why we have canary :smiling_imp: 

Thanks for working on it!

**Comment by mdehoog** [comment]
Thanks for the speedy fix guys!
