### ISSUE TITLE
2.0 Blog post

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#11872]
This ticket is a summary of items to be discussed for the 1.13 release post. **Repo followers, please do not consider this a guarantee or even prediction of 1.13 behavior**. Just a place for notes.

This issue is locked to keep us focused. If you have commit bit please edit the description.

---
2.0:

* 

2.0 deprecations:

* 

2.0 breaking changes

* https://github.com/emberjs/ember.js/issues/11849

---
2.1-beta:

* 

2.1-beta deprecations:

*

**Comment by rwjblue** [comment]
:shipit:
