### ISSUE TITLE
ember.map and ember-template-compiler.map are missing in bower package

### ISSUE THREAD

**Issue by janmisek** [emberjs/ember.js#11876]
Hello Ember team

In current release 1.13.5 source map files are missing for ember and ember-template-compiler even they are referenced at the end of js files. checked bower package and release page.

Thanks.

**Comment by stefanpenner** [comment]
the source map files currently do not work, we are pending some of our transforms to be fully ported to babel to work.

We should be sure the hints to the files are removed from the output for now.

**Comment by rwjblue** [comment]
This was resolved some time ago, closing...
