### ISSUE TITLE
Deprecate Ember.CollectionView

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#11887]
Same process as https://github.com/emberjs/ember.js/pull/11826 (but needs the additional fixes added in https://github.com/emberjs/ember.js/pull/11866).

/cc @martndemus

**Comment by pixelhandler** [comment]
@rwjblue perhaps use "Cleanup" label ?

**Comment by martndemus** [comment]
Ill tackle this tomorrow morning!

**Comment by rwjblue** [comment]
Fixed by #11891
