### ISSUE TITLE
Action target to specific component 

### ISSUE THREAD

**Issue by abFx** [emberjs/ember.js#11886]
Targeting an action to an specific component it's not working anymore.
Currently using latest ember js release - "ember": "1.13.5",

Here is the complete environment

On application template

    <a href="#" class="nav-action" {{action 'open' target='view.appOverlay.categorySideMenu'}}><i class="fi-list"></i></a>

    {{#overlay-fx viewName="appOverlay" open="openSideMenu"}}

        {{#side-menu  open="open" use="toLeft" targetObject=view.appOverlay viewName="userSideMenu"}}
            {{partial "partial/user-side-menu"}}
        {{/side-menu}}

        {{#side-menu  open="open" use="toLeft" targetObject=view.appOverlay viewName="categorySideMenu"}}
	       {{partial "partial/category-side-menu"}}
        {{/side-menu}}

    {{/overlay-fx}}

Overlay-fx component

    import Ember from 'ember';
    import layout from '../templates/components/overlay-fx';

    export default Ember.Component.extend({
    actions: {
        // Action handler that enable component to catch send actions from outher components
  	    open: function(childViewName){
            this.sendAction('open', childViewName);
  	    },
      }
    });

Side-menu component

    import Ember from 'ember';
    import layout from '../templates/components/overlay-fx';

    export default Ember.Component.extend({
    actions: {
  	    open: function(childViewName){
            this.sendAction('open', this.get('viewName'));
  	    },
      }
    });

Application controller

    import Ember from 'ember';

    export default Ember.Controller.extend({
        actions: {
            openSideMenu: function(childViewName){
		      console.log('do something')	
            },
        }
    });

--

You can find all the code example at this jsbin - http://jsbin.com/qugipupuza/edit?html,js,output
but its a bit sluggish, don't recommend

**Comment by pixelhandler** [comment]
@abFx I noticed that the jsbin crashes the browser, so I tried running locally https://gist.github.com/pixelhandler/f22a67119b961dc8867c but that was problematic as well. This this gist work locally for you? Did it work with a previous release of Ember?

**Comment by abFx** [comment]
@pixelhandler no it didn't work, but I recreated the issue on this new fiddle and apparently it works if I remove the ' from the target on the action 

http://ember-twiddle.com/e5cc5e3620b02bb68665

**Comment by mixonic** [comment]
Passing `targetObject` is not something we intended to work, and it will likely not continue to work.

I strongly suggest you use improved actions here. Much easier to reason about:

```
{{#my-child-component open=(action "open" target=view.appOverlay) use="toLeft" viewName="userSideMenu"}}
```

I'm uncertain what the intended future of `viewName` is.

@abFx I'm going to close this as I believe you found the problem, but please re-open or let me know if I've missed something.

**Comment by abFx** [comment]
@mixonic thanks, so improved actions are the safe way to go to ember 2.0 road?

**Comment by rwjblue** [comment]
@abFx - Yes, absolutely.

**Comment by rwjblue** [comment]
> I'm uncertain what the intended future of viewName is.

@mixonic - it should be deprecated in 2.x, I do not think it is appropriate in a primarily component world...

**Comment by abFx** [comment]
@mixonic @rwjblue improved actions have to be inside a main controller? I can't pass a component parent action?
