### ISSUE TITLE
Nested Sub-routes are Broken

### ISSUE THREAD

**Issue by marksalpeter** [emberjs/ember.js#11888]
Im using eager loading with sub routes. I made a new ember cli project to demo the bug:

 https://github.com/marksalpeter/ember-nested-subroutes-bug.git

In the example,  the foo and /foo/bar routes work as expected but the foo/bar/baz route doesn't render the correct loading template or automatically fallback to templates/foo/bar/baz/index.hbs when templates/foo/bar/baz.hbs isn't found. If you change templates/foo/bar/baz/index.hbs to templates/foo/bar/baz.hbs baz will render, but templates/foo/bar/baz/loading.hbs will not be used for its loading state.

Let me know if there's anything else I can do to help debug.

**Comment by pixelhandler** [comment]
@marksalpeter do you think replacing `setTimeout` with `Ember.run.later` may help?

**Comment by pixelhandler** [comment]
@marksalpeter I think the issue you ran into is not documented well:

Instead of:

```javascript
Router.map(function() {
  this.route('foo', function() {
    this.route('bar', function() {
      this.route('baz');
    });
  });
});
```

Use a function with `this.route` so you can use the `index` and `loading` templates.

```javascript
Router.map(function() {
  this.route('foo', function() {
    this.route('bar', function() {
      this.route('baz', function() {});
    });
  });
});
```

**Comment by rwjblue** [comment]
@pixelhandler - Thanks for investigating and sending a PR showing the solution!

**Comment by marksalpeter** [comment]
Thanks!
