### ISSUE TITLE
Deprecate and remove function argument in Ember.assert/deprecate/etc

### ISSUE THREAD

**Issue by mmun** [emberjs/ember.js#11898]
The following should throw a deprecation:

```js
Ember.deprecate(msg, function() { return true; })
```

The message should be something like "Functional arguments are ambiguous with constructors. Please use `!!Constructor` for constructors, or an IIFE to compute the deprecation value. In a future version of Ember functions will be treated as truthy values instead of being executed."

Needs to be deprecated in stable (1.13), removed in beta (2.0).

**Comment by rodrigo-morais** [comment]
Hello @mmun and @rwjblue,

I'd love become me a new contributor, and I think this issue is a good one to start.
I can't find where I should work to solve this issue.

Would you mind giving me some tips?

Thanks.

**Comment by KevinTCoughlin** [comment]
I've attempted to partially resolve this issue in #11933. Would appreciate any advice for fully satisfying the issue and any problems with my PR. Thank you.

**Comment by Kuzirashi** [comment]
@rwjblue, @stefanpenner is it still possible to create pr with deprecation or you will just remove this functionality? @mmun has written that it should be remove in beta 2.0.

**Comment by mmun** [comment]
It's far too late for this, but we can do it now in preparation for Ember 3.0.

**Comment by kylemellander** [comment]
In researching this, it looks like @Kuzirashi has done a lot of great work moving this along in [https://github.com/emberjs/ember.js/pull/12370] (PR 12370).  I would love to help move this forward if it needs more work, or have it closed if Kuzirashi's work finished it.

**Comment by rwjblue** [comment]
@kylemellander - Thanks for doing the research on this, I think this is closed!
