### ISSUE TITLE
1.13.5 twice repeated className 

### ISSUE THREAD

**Issue by dmagunov** [emberjs/ember.js#11899]
Ember 1.13.5, then call component: 
```handlebars
{{#each list as |item|}}
  {{some-component classNames='row'}}
{{/each}}
```
it rendered as 
```html
<div id="ember2724" class="row ember-view row"></div>
```

**Comment by stefanpenner** [comment]
i recall another related issue, but cannot quicky find it :(

**Comment by pixelhandler** [comment]
@dmagunov @stefanpenner is this the issue https://github.com//emberjs/ember.js/issues/11600 that this one #11899 duplicates ?

**Comment by rwjblue** [comment]
Ya, closing this as a duplicate.
