### ISSUE TITLE
Route - transitionTo(url) bug

### ISSUE THREAD

**Issue by dmagunov** [emberjs/ember.js#11896]
Hello, 

If I use transitionTo() and pass URL inside it, then current route redraw itself and after that goes to another route.

**Comment by pixelhandler** [comment]
@dmagunov are you doing some kind of redirect? e.g. http://guides.emberjs.com/v1.13.0/routing/redirection/ also the api docs don't mention using a URL, see: http://emberjs.com/api/classes/Ember.Route.html#method_transitionTo

**Comment by locks** [comment]
I am closing this issue due to lack of information from the submitter.
Feel free to re-open the issue if you think it's still justified, thank you.
