### ISSUE TITLE
Ember reorder query params in url

### ISSUE THREAD

**Issue by dmagunov** [emberjs/ember.js#11894]
Hello,

Ember 1.13.5, if I url with random ordered query parameters, then ember sort it and update url (also push previous url with random ordered query params in history), so then I hit back button browser moves to page with random ordered query params.

**Comment by pixelhandler** [comment]
@dmagunov It sounds like the browser history has the 'url with random ordered query params' so I expect that the back button will resolve to that history 'url with random ordered query params' right?

Updating the URL doesn't necessarily push the url into browser history. How did you update the URL with the sorted params?

**Comment by dmagunov** [comment]
No, its not browser issue (same behavior in different browsers). I've made video to illustrate this issue https://youtu.be/Iv0vW2v0NZA.

**Comment by jayphelps** [comment]
@dmagunov Can you provide us with an emberjs.jsbin.com or sample code showing what you mean? It sounds like you're some how sorting query parameters, but I'm not aware of how this is possible or why you'd want to do so. Unless you're saying that Ember-itself is some how sorting them differently, which we'd still need example code to show how you reproduce this. Thanks!

**Comment by jayphelps** [comment]
Similar or same issue seems to have been previously reported and fixed a while ago: https://github.com/emberjs/ember.js/pull/4289 There doesn't seem to be any probable changes to route-recognizer in quite some time that would seem to impact this either https://github.com/tildeio/route-recognizer/commits/master/lib/route-recognizer.js so still not sure what he's experiencing. Still digging, but do provide example code to reproduce.

**Comment by dmagunov** [comment]
Can't create fully functional example via ember-twiddle or jsbin. Here http://ember-twiddle.com/d88f40dd01ef7b45fde6 only shows link-to issue (maybe related) query parameters sort order.

**Comment by dmagunov** [comment]
Here I created  sample application http://awwsoft.ua/ember/query/sub?project_id=2&progress_id=3&year=3  Git - https://github.com/dmagunov/ember-issues-query

**Comment by pixelhandler** [comment]
@dmagunov I'm curious if you still have this issue or found a work around. This issue is inactive and we weren't able to identify it as a bug.

I'll close this for now. Feel free to reopen if you need to.
