### ISSUE TITLE
[Documentation] "Rendering with Helpers" Comparison Tables Missing Headers

### ISSUE THREAD

**Issue by ennui93** [emberjs/ember.js#11901]
The comparison tables at the bottom of the "Rendering with Helpers" section of the documentation are missing the 'View' column header in v1.13.0. Version 1.12.0 docs don't have this issue.

http://guides.emberjs.com/v1.13.0/templates/rendering-with-helpers/

**Comment by EricSchank** [comment]
@ennui93 I believe this intentional -- views are deprecated in 1.13 and removed in 2.0
http://emberjs.com/deprecations/v1.x/#toc_ember-view

**Comment by truenorth** [comment]
Definitely should add documentation for the `{{component}}` helper in place of view though.

**Comment by pixelhandler** [comment]
@mike-north is using a `{{x-foo}}` or `<x-foo>` really a 'helper'? I don't think that using a component in a template is equivalent to rendering with a helper.

**Comment by rwjblue** [comment]
Yeah, https://github.com/emberjs/guides/pull/430 replaced the headers with a table view.  

In general, issues with the guides should be reported to http://github.com/emberjs/guides.
