### ISSUE TITLE
Setting an attribute to null does not removes that attribute

### ISSUE THREAD

**Issue by OrKoN** [emberjs/ember.js#11907]
Previously, when an attribute was null it was removed from the element:

```
var model =  {
  attribute3: null
};
```

```
<div {{bind-attr attribute3=model.attribute3}}>Test Attributes</div>
```

Attribute3 was not added to the element (see [jsbin](http://emberjs.jsbin.com/wivogumeja/1/edit?html,js,console,output)).

After migration to Htmlbars bound-style attributes, this does not work anymore (see [jsbin](http://emberjs.jsbin.com/pufizaceze/1/edit?html,js,console,output)):

```
<div attribute3="{{model.attribute3}}">Test Attributes</div>
```

renders `<div attribute3></div>` instead of `<div></div>`.

There is a test for this case in Htmlbars project https://github.com/bantic/htmlbars/blob/master/packages/htmlbars-compiler/tests/html_compiler_test.js#L116 So I assume it works with pure htmlbars.

Related issues: https://github.com/emberjs/website/issues/2178 https://github.com/tildeio/htmlbars/pull/73 https://github.com/tildeio/htmlbars/issues/68

**Comment by rwjblue** [comment]
When using quotes, Ember automatically concats each set of curlies and emits that combined source together as the attribute value.  This is how things like `<div data-name="{{firstName}} {{lastName}}"></div>` work.  I believe that the case where concat is called with a single argument (as you have above), we can simply return the input value to allow the above to work properly. 

The work around for now, is to not quote the attribute (it will then not attach `null` values):

```hbs
<div attribute3={{model.attribute3}}></div>
```

Demo JSBin: http://rwjblue.jsbin.com/voduxi/1/edit?html,js,output

---

Unfortunately, this advice is contrary to what I believe will be changing in support of angle bracket components.  Where quoted and non-quoted attributes when invoking components are treated differently.

**Comment by pixelhandler** [comment]
@OrKoN Looks like @rwjblue already made a bin, well here is another one: http://emberjs.jsbin.com/ruyana/3/edit?html,js,console,output I've added to the console log the attribute values see that the attribute3 is undefined as it's not present.

**Comment by rwjblue** [comment]
I'm going to go ahead and close, but keep an eye out for more details when the angle bracket component changes are enabled (changing the meaning of quoted vs non-quoted attributes).
