### ISSUE TITLE
Best Practice: Now Views are Deprecated, how should I setup the DOM for Application Template?

### ISSUE THREAD

**Issue by hhff** [emberjs/ember.js#11906]
Hi All!

Quick question about a 1.13.x onward best practice:

Say I want to add a class to my application template, so that it renders the class on the top level div.  I used to do this by creating an application view, and adding the custom attributes there.

What's the no-view way to do this?  This also applies to route views i guess!

:heart:

**Comment by dschmidt** [comment]
I just discussed this on slack last night and we came to no satisfactory solution ... apparently a clean solution will only be available, when routable components become a thing. 

Until then I hacked around it by creating a component that I invoke from the application template:
```javascript
import Ember from 'ember';

export default Ember.Component.extend({
    didInsertElement() {
        let applicationViewElement = this.$().parent();
        applicationViewElement.addClass('foobar-application');
    }
});
```
Pro:
It triggers no deprecation warning
Con: 
It works only fine for pure css, it gets messy if you want to do anything with JS based on that class and timing is somehow relevant.

**Comment by hhff** [comment]
feared as much!

**Comment by rwjblue** [comment]
Simplest thing (though annoying) to do right now is the following:

```javascript
// app/views/application.js
import Ember from 'ember';

export default Ember.Component.extend({
  classNames: [ 'foo-bar' ]
});
```

JSBin (Global) Demo: http://rwjblue.jsbin.com/rwjblue/636/edit?html,js

**Comment by rwjblue** [comment]
Closing as this isn't really a bug, and the above solution works fine as an interim solution until routable components land.

**Comment by hhff** [comment]
danke!

**Comment by dschmidt** [comment]
Be careful tho, I ditched my hack in favor of the solution @rwjblue proposed, but
after I made the ApplicationView a component in 1.12, I had no access to the controller anymore - it seems to only work in 1.13. 

So if you still need to support 1.12 (or want to incrementally migrate to 1.13), you're probably better off using something like this: (Gosh, I feel dirty)
```javascript
import Ember from 'ember';

if(Ember.VERSION.startsWith("1.12")) {
    var baseClass = Ember.View;
} else {
    var baseClass = Ember.Component;
}

export default baseClass.extend({
    classNames: ['foobar']
});
```
