### ISSUE TITLE
Using ApplicationView results in warning

### ISSUE THREAD

**Issue by quaertym** [emberjs/ember.js#11909]
```
DEPRECATION: Ember.View is deprecated. Consult the Deprecations Guide for a migration 
strategy. See http://emberjs.com/deprecations/v1.x/#toc_ember-view for more details.
```

Since views are deprecated, what is the suggested way to replace `ApplicationView`?

**Comment by geoffreyd** [comment]
The suggestions for ApplicationView are under the 'Routable Views' sections http://emberjs.com/deprecations/v1.x/#toc_routable-views 
What are you using your ApplicationView for?

**Comment by quaertym** [comment]
I don't see anything related to `ApplicationView` there and `ApplicationView` is not a routable view. It is a special top level view which I use for some body scroll animation and adding/removing classes to body tag.

**Comment by rwjblue** [comment]
> ApplicationView is not a routable view

It absolutely is.

> It is a special top level view which I use for some body scroll animation and adding/removing classes to body tag.

See https://github.com/emberjs/ember.js/issues/11906#issuecomment-125202100 for a viable work around for these use cases until routable components land.

**Comment by rwjblue** [comment]
Alternatively, you can structure your template to invoke a component directly in your application template. That way you can add a styled element as you'd like, and avoid using the somewhat bizarre work around above.

**Comment by quaertym** [comment]
@rwjblue I thought routable meant adding a route to the router, but I see now and of course there is `ApplicationRoute`.

Your suggestion is good for now (though feels like a hack):
```
// app/views/application.js or app/application/view.js
import Ember from 'ember';

export default Ember.Component.extend({

});
```

>Alternatively, you can structure your template to invoke a component directly in your application template.

@ryanflorence would be happy :) This is ok if everything is a component but the code below disturbs me:
```
{{#application-component}}
  {{render "users" model}}
{{/application-component}}
```

**Comment by rwjblue** [comment]
> Your suggestion is good for now (though feels like a hack)

Yep, agreed.

> This is ok if everything is a component but the code below disturbs me

Yep, agreed.

:smiling_imp:

**Comment by rwjblue** [comment]
I'm going to close this as it isn't an actionable bug at this point, and we have a clear path forward (routable components).
