### ISSUE TITLE
Can't extend LinkComponent in 1.13

### ISSUE THREAD

**Issue by dopin** [emberjs/ember.js#11912]
I tried to extend LinkComponent like this
```javascript
App.MyLinkComponent = Ember.LinkComponent.extend({
  init: function() {
    this._super.apply(this, arguments);
    Ember.Logger.log('Event is ' + this.get('eventName'));
  }
});
```

I followed [the doc](http://emberjs.com/api/classes/Ember.LinkComponent.html#method_init).
But, I get an error message: `Uncaught TypeError: Cannot read property 'slice' of undefined`.
jsbin is here: http://emberjs.jsbin.com/mavihisace/edit?html,js,console,output

Is it bad idea to extend LinkComponent? Should I reopen it?

**Comment by dopin** [comment]
Oops, I think that I mistook. :flushed:   Do I need to extend link-to helper for MyLinkComponent too?

**Comment by dopin** [comment]
I found that `{{link-to}}` is not a helper but a keyword of HTMLBars. It's very different, isn't it?

**Comment by rwjblue** [comment]
> I found that {{link-to}} is not a helper but a keyword of HTMLBars. It's very different, isn't it?

Yes, it is very different.   

---

You have to do a little extra "massaging" to make this work: 

```javascript
App.MyLinkComponent = Ember.LinkComponent.extend({
  positionalParams: 'params',

  init: function() {
    this._super(...arguments);
    Ember.Logger.log('Event is ' + this.get('eventName'));
  },
  
  didReceiveAttrs: function() {
    this.attrs.params = this.get('params');
    this.attrs.hasBlock = true;
  }
});
```

Demo: http://rwjblue.jsbin.com/ligiti/edit?html,js

There are a few downsides to the above approach:

* It is hard coded to "has block" mode (meaning you can't use the same component for inline `{{link-to}}`)
* You have to implement `positionalParams` along with `didReceiveAttrs` to ensure the `params` are available internally. This may be fixable in Ember if we start using `postionalParams`, but I am unsure.
* If you swap to using `this.attrs.hasBlock = false` it isn't properly escaped.
* This is likely somewhat private API. :disappointed: 

---

All of those caveats aside: I would like to make this work properly.  IMHO, users should be able to extend `Ember.LinkComponent` for their own custom links, and invoke them.

**Comment by dopin** [comment]
@rwjblue It works! Thank you very much for your very helpful instructions.
I didn't know that `postionalParams` and `didReceiveAttrs` exist. I couldn't find them in the doc.

>This is likely somewhat private API.

So there're some risk to use.

> IMHO, users should be able to extend Ember.LinkComponent for their own custom links, and invoke them.

Yes, I agree with you.

I think I should close this issue. Please reopen if needed. Thank you!
