### ISSUE TITLE
didInitAttrs uses same array across two instances of same component

### ISSUE THREAD

**Issue by adam-knights** [emberjs/ember.js#11913]
I've created a jsbin that shows this here http://emberjs.jsbin.com/fukuha/edit?html,css,js,output

Basically I add two objects to an array in the didInitAttrs of the component. If the component is on the page once it renders correctly and I see 'jon is one sam is two'. If I add the same component to the page twice (as in the bin) then it continues to add to the array of the previous component, and they both use that array.

Is this correct behavior or a bug? I expected the components to behave distinctly?

**Comment by rwjblue** [comment]
The JSBin is sharing the array on the component's prototype.

http://rwjblue.jsbin.com/docepa/edit?html,js,output

Small write up from a little while back: https://dockyard.com/blog/2014/04/17/ember-object-self-troll

**Comment by adam-knights** [comment]
That's a very good write up. I happened upon this in a much more complex component when 2nd, 3rd and 4th integration tests on it started blowing  up with weird behaviour in my /tests/. Following the above fixes this in both my simple case and real life case.
