### ISSUE TITLE
Documentation for isEvery is not clear

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/ember.js#11916]
http://emberjs.com/api/classes/Ember.Enumerable.html#method_isEvery
> Returns true if the passed property resolves to the value of the second argument for all items in the enumerable. This method is often simpler/faster than using a callback.

Expectation (based on definition) for [].isEvery('name', 'olivier') was false. 
Result is true.

While the isEvery method follows the implementation of javascript .every iterator, the definition in Ember doc could be a bit better.

**Comment by jimbeaudoin** [comment]
@olivierlesnicki There is a [guides repository](https://github.com/emberjs/guides) where you can post issues related to the guides.

It would be great if you could update or close this issue and reopen a new one if needed in the guide repos.

Thanks!

**Comment by olivierlesnicki** [comment]
@jimbeaudoin done ;)

**Comment by knownasilya** [comment]
Actually this should still be here, since the API is defined in the source code.

**Comment by jimbeaudoin** [comment]
@knownasilya yes you are right. 

It is defined here: https://github.com/emberjs/ember.js/blob/v1.13.5/packages/ember-runtime/lib/mixins/enumerable.js#L674

Do you think this is an issue? Maybe a PR with a new text?

**Comment by knownasilya** [comment]
If the OP cannot do a PR, then this issue is fine, till someone else does.
