### ISSUE TITLE
[Documentation] Meta-issue to improve API docs

### ISSUE THREAD

**Issue by locks** [emberjs/ember.js#11911]
I was checking the API docs and realized there's a lot of opportunity to improve the documentation with examples. This issue will serve as the coordination point.

Check out the sister Ember Data issue: https://github.com/emberjs/data/issues/3595

### Checklist:
- [ ] Temporary

### Notes
* Current pre-selection https://gist.github.com/SaladFork/8fafc629cae39ced45dd

**Comment by rwjblue** [comment]
@locks - Should I close or are you going to add things to be done in the checklist above?

**Comment by locks** [comment]
@rwjblue I'm still coordinating with @SaladFork. Will be resolved either way by the end of the week.
