### ISSUE TITLE
Need expectWarn test helper

### ISSUE THREAD

**Issue by EricSchank** [emberjs/ember.js#11924]
Similar to `expectDeprecation`, a handler for checking that the right `Ember.warn` happened during a test will lead to stronger tests and therefore an even stronger codebase.

**Comment by rwjblue** [comment]
:+1: - Can you open this over in the https://github.com/emberjs/ember-dev repo?

**Comment by EricSchank** [comment]
Moved issue to ember-dev:
https://github.com/emberjs/ember-dev/issues/157
