### ISSUE TITLE
Click Event Lost When Element Is Redrawn

### ISSUE THREAD

**Issue by sberan** [emberjs/ember.js#11922]
** *see below for working example* **

In our app, we have an input field which receives focus when it is added to the DOM. We also have a list of items whose value depends on the value of that input field. When we click an element in the list, the click event is simply lost! The problem is that the value of the input element is changed from `null` to `''`, which causes the list to be redrawn.

**Somehow, the click event is lost when redrawing the list of items!**

Fiddle: http://ember-twiddle.com/ec1626422607c7bfd69e

**Comment by pixelhandler** [comment]
@sberan Using Chrome the alert does fire the first time I click. Also I updated the twiddle to use the release channel of ember / ember-data http://ember-twiddle.com/ec1626422607c7bfd69e and I see the same, I click on the button and the alert is displayed.

I'm not sure why I'm not able to see the issue of a "lost click event" can you perhaps be more specific on the steps to reproduce the issue?

**Comment by tsteuwer** [comment]
@sberan It is working for me as well in both Chrome (42.0.2311.152) and FireFox (38.0).

**Comment by juggy** [comment]
Also modifying a property within the didInsertElement hook is deprecated (as stated by a lot of deprecation warnings).

**Comment by sberan** [comment]
I can't reproduce this anymore either. Very strange! Closing.
