### ISSUE TITLE
Ember 2.0 API docs 

### ISSUE THREAD

**Issue by aexmachina** [emberjs/ember.js#11923]
Is there any way that I can access the Ember 2.0 API docs?

**Comment by rwjblue** [comment]
Browse this repo. :)

**Comment by rwjblue** [comment]
They are built from the source here, also every build that Travis does automatically publishes a ember-docs.json file. You could use that file to build the API docs for any version. 

Also, we have a project (over at emberjs/api) that intends to make versioned API docs much easier.

**Comment by rwjblue** [comment]
This isn't really a bug though, so I'm going to close. We can continue the convo in community slack if you'd like.

**Comment by aexmachina** [comment]
Okay cool `npm run docs` inside a clone of this repo works for me. Thanks!
