### ISSUE TITLE
All component parameters Observers triggered when only one changes.

### ISSUE THREAD

**Issue by mandelcode** [emberjs/ember.js#11920]
I have this setup:

    {{component-1 param1=param1 sharedParam=sharedParam}}
    {{component-2 param2=param2 sharedParam=sharedParam}}

And I log all changes inside my components like this:

    onParam1Change: function() {
        log("param 1 has changed inside component 1");
    }.observes("param1"),

Here's what I get when I change **param1**:

    param 1 has changed inside component 1
    shared param has changed inside component 1
    shared param has changed inside component 1
    will render component 1

... and **sharedParam**:

    shared param has changed inside component 1
    will render component 1
    param 2 has changed inside component 2
    shared param has changed inside component 2
    param 2 has changed inside component 2
    shared param has changed inside component 2
    will render component 2

See this fiddle: https://jsfiddle.net/4bwsqcx1/8/

There are small differences depending on who updated the value (the parent view or one of the components).

This may causes logic issues, performances issues (when a parameter is updated often), and in the worst case infinite loops (for example if a parameter change triggers an ajax request which in turn modifies another parameter).

**Comment by jcope2013** [comment]
related https://github.com/emberjs/ember.js/issues/11638

**Comment by stefanpenner** [comment]
Ya this is a duplicate
