### ISSUE TITLE
[1.13.5] Computed properties recalculate on destroyed objects

### ISSUE THREAD

**Issue by dsokolowski** [emberjs/ember.js#11926]
During work on my project I just encountered problem caused by computed property that was recalculated for component that has been destroyed  (removed from the DOM and flag isDestroying set to true). For me it looks undesired to recalculate a bunch of computed properties on destroyed objects since it may cause exceptions or performance issues but maybe it is by design? 

Here is jsbin to give you better insight into the problem: http://emberjs.jsbin.com/radopigisa/edit?html,js,output

**Comment by stefanpenner** [comment]
CP are lazy and as such don't recalculate on there own. I suspect you have an eager observer or a run.schedule in your code causing the cp to be consumed

**Comment by dsokolowski** [comment]
Have you seen my jsbin?

**Comment by rwjblue** [comment]
Seems to work properly on beta (unless I am misinterpretting the console output): http://rwjblue.jsbin.com/zasihe/edit?html,js,output

**Comment by stefanpenner** [comment]
This is an issue with arrayComputed / reduceComputed. It is a non-trivial fix, that is part of 2.0

**Comment by dsokolowski** [comment]
I confirm, it works properly on beta :) I should have checked it before so sorry for your time and thanks for help.

**Comment by stefanpenner** [comment]
> so sorry for your time and thanks for help.

No need to be sorry, we are sorry this bug exists in 1.13.x. Thanks for reporting!
