### ISSUE TITLE
`Ember.keys` doesn't include computed / unchanged properties

### ISSUE THREAD

**Issue by timkendrick** [emberjs/ember.js#11921]
Computed properties don't show up when `Ember.keys` / `Object.keys` is called on an object instance.

This also applies to properties that are not explicitly initialized via `MyObjectSubclass.create()` and fall back to default values declared on the prototype.

Example: http://emberjs.jsbin.com/pasahiciko/edit?html,js,output

These properties don't even seem to show up when `Object.getOwnPropertyNames` is called on the instance.

Surely there should be a way to find out, given an object instance, what all its properties are (including computed/unchanged properties)?

**Comment by stefanpenner** [comment]
this is by design. computed properties and properties provided during `extend` are on the prototype of the object.

**Comment by timkendrick** [comment]
Ah ok, that makes sense – I didn't realize `Object.keys` skipped prototype fields, sorry about that.

Thanks for the `for...in` tip. My problem now though is that this gives me all the `"constructor", "__ember1438188980206", "__ember_meta__", "_super"` etc properties.

Do you know if there's a simple way to get the filtered version of the property names (i.e. just the keys passed into `Ember.Object.extend({...})`, minus the autogenerated metadata properties, but including custom-superclass property names)?

The reason I'm doing this is to try to create an assertion helper that determines whether two ember objects contain the same data – I guess it makes sense to skip computed properties in the comparison, but auto-initialized properties are causing me problems when one instance has not set the value, but the other instance has explicitly set it to the default value...

**Comment by stefanpenner** [comment]
> Ah ok, that makes sense – I didn't realize Object.keys skipped prototype fields, sorry about that.

Ya, for reference `Object.keys` is basically:

```
function keys(obj) {
  var result = [];

  if (obj && typeof obj === 'object' ) {
    for (var key in obj) {
      if (Object.prototype.hasOwnProperty.call(obj, key)) {
        result.push(key);
       }
     }
  }

  return keys;
}

> Do you know if there's a simple way to get the filtered version of the property names (i.e. just the keys passed into Ember.Object.extend({...}), minus the autogenerated metadata properties, but including custom-superclass property names)?

unfortunately not,

**Comment by timkendrick** [comment]
Great, thanks so much for the swift response and detailed examples!
