### ISSUE TITLE
Ember.ArrayProxy does not have the method `sort`

### ISSUE THREAD

**Issue by martndemus** [emberjs/ember.js#11936]
I think it should because an array should have a sort function.

``` js
Ember.A([2, 5, 1]).sort()
// -> [1, 2, 5]
```

``` js
Ember.ArrayProxy.create({ content: Ember.A([2, 5, 1]) }).sort()
// -> Uncaught TypeError: Ember.ArrayProxy.create(...).sort is not a function
```

**Comment by stefanpenner** [comment]
seems like it should, although we do encourage people to not use the proxy anymore.

**Comment by martndemus** [comment]
Ember Data uses it for it's `ProxyArray`

**Comment by pixelhandler** [comment]
@martndemus See this bin not sure if it's a good enough workaround or just another reason not to use the ArrayProxy http://emberjs.jsbin.com/notaxu/3/edit?js,output - uses an Ember.Array to give to the content of the ArrayProxy and when sorting uses the Ember.Array instance.sort method with `call`

**Comment by martndemus** [comment]
@pixelhandler I ended up with this snippet:
```js
// Ember.ArrayProxy has no sort method. 
// see: https://github.com/emberjs/ember.js/issues/11936
if (typeof list.sort !== 'function' && typeof list.toArray === 'function') {
  list = list.toArray();
}
```

Not sure if one api method missing warrants an RFC.

**Comment by stefanpenner** [comment]
> Not sure if one api method missing warrants an RFC (issue).

Ya, i don't think it needs an RFC. It feels like an omission/bugfix to me.

@emberjs/owners can I get a confirmation?

**Comment by jayphelps** [comment]
AFAIK `Ember.ArrayProxy` does not conform completely to native Array, IMO intentionally. Only Ember-specific mutation methods are proxied, like `pushObject`, `sortBy`, etc. Notice that `push` isn't proxied, the same reason `sort` isn't: they don't cause CP invalidation/observer notification.

**Comment by rwjblue** [comment]
I tend to agree with @jayphelps here. 

I'm happy to continue discussion in a PR if someone wants to push this forward, but since there hasn't been any movement / interest in this for a while, I'm going to go ahead and close.
