### ISSUE TITLE
Make Ember.merge public?

### ISSUE THREAD

**Issue by jhr007** [emberjs/ember.js#11938]
> Ember.merge 
> Merge the contents of two objects together into the first object.
> http://emberjs.com/api/#method_merge

This utility method should be public. It's similar to Ember.copy and Ember.create which are public. 

As a public method its purpose doesn't have to be reinvented nor found via another library.

**Comment by stefanpenner** [comment]
> .create which are public.

FYI: is deprecated

**Comment by mateuspv** [comment]
@stefanpenner deprecated in favor of Object.assign ? Should we add a deprection at log ?

**Comment by rwjblue** [comment]
@stefanpenner was saying that `Ember.create` was deprecated (not `Ember.merge`).

Generally, I would like to deprecate `Ember.merge` in favor of a new `Ember.assign`, but that is another story :smile_cat:

**Comment by stefanpenner** [comment]
We should likely merge this

**Comment by rwjblue** [comment]
Ya, this isn't a PR, but I'd definitely accept a PR making `Ember.merge` public.

**Comment by duggiefresh** [comment]
@rwjblue @stefanpenner Seems that `Ember.merge` is marked as public now. I think this issue can be closed.

API: http://emberjs.com/api/#method_merge

Here's the PR: https://github.com/emberjs/ember.js/pull/11978

**Comment by rwjblue** [comment]
@duggiefresh - Thank you for saving us from ourselves!!!

**Comment by duggiefresh** [comment]
Anything for you two! :rose: :bouquet: :tulip:
