### ISSUE TITLE
Canary – Computed properties not working with angle-bracked component

### ISSUE THREAD

**Issue by funtusov** [emberjs/ember.js#11948]
I'm not sure whether it's not implemented yet or I am missing something, but:

This works:
```javascript
// Template
{{my-component name=name}}

// component.js
someProp: Ember.computed.alias('name')
```

While this doesn't:
```javascript
// Template
<my-component name={{name}}></my-component>

// component.js
someProp: Ember.computed.alias('attrs.name')
```

Accessing ``{{attrs.name}}`` from the component template works fine.

**Comment by rwjblue** [comment]
Yes, I would expect this to work (though using `attrs.name` seems like a better choice vs using an alias).

**Comment by funtusov** [comment]
Of course, that's just an example – that happens with any computed property

**Comment by rwjblue** [comment]
@funtusov - Understood.  Definitely, seems like a bug, would you mind submitting a failing test case for this?

**Comment by ghwilson4456** [comment]
The following code worked a couple of days ago (8/3) from the canary build. As of this morning it still is not working.

**Template:**
```
<my-component names={{names}} />
```

**Component:**
```
export default Ember.Component.extend({
  outputNames: Ember.computed('attrs.names', function() {
    console.log(this.attrs.names);
  });
});
```

**Comment by rwjblue** [comment]
@ghwilson4456 - Yep, it is a known issue that has been fixed in the [glimmer-component](https://github.com/emberjs/ember.js/compare/glimmer-component) branch (in https://github.com/emberjs/ember.js/commit/019562211648098bfa0d1a411c10bca8d12086b1). That set of changes will be landing shortly after 2.1.0-beta.1 ships (about a week).

**Comment by funtusov** [comment]
Seems to be the same issue then and we can close?

**Comment by rwjblue** [comment]
@funtusov - It *might* be the same issue. I am unsure if it is though.  I'd love a PR with a failing test case though, that way we can ensure to get this exact scenario nailed down.

**Comment by funtusov** [comment]
here it goes :)

**Comment by rwjblue** [comment]
Awesome, thanks for submitting the failing test PR.  I'm going to close this issue and we can track it over there.
