### ISSUE TITLE
Ember.Date.parse() should interpret ISO 8601 strings without time zone offset as a local time

### ISSUE THREAD

**Issue by jelhan** [emberjs/ember.js#11951]
Currently `Ember.Date.parse()` interprets ISO 8601 strings without time zone offset as UTC time. This is correct following ECMAScript 5.1 specification:
> [15.9.1.15 Date Time String Format](http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15)
> (...)
> The value of an absent time zone offset is “Z”.

This is changed in ECMAScript 6:
> [20.3.1.16 Date Time String Format](http://www.ecma-international.org/ecma-262/6.0/#sec-date-time-string-format)
> (...)
> If the time zone offset is absent, the date-time is interpreted as a local time.

`Ember.Date.parse()` should follow ECMAScript 6.

This aspect is especially import if dealing with date-only ISO 8601 strings ("2015-08-02"). Current implementation results in unexpected behaviour like this one:
```js
new Date(Ember.Date.parse('2015-01-01')).toLocaleDateString();
// "31.12.2014"

new Date().getTimezoneOffset();
// 360
```

**Comment by rwjblue** [comment]
I believe this is an Ember Data thing, can you confirm and reopen over in the ember data repo?

**Comment by stefanpenner** [comment]
Yes it's ember

**Comment by rwjblue** [comment]
@jelhan - Can you open this over in ember-data.

**Comment by jelhan** [comment]
Yeah, you are right. Sorry.

There was already an ongoing debate in ember-data, which could be found here: https://github.com/emberjs/data/pull/2685
