### ISSUE TITLE
Why for partial template using a leading dash of the file name.

### ISSUE THREAD

**Issue by boyishwei** [emberjs/ember.js#11973]
i.e.: partial template "-form.hbs", if I'm using vim to edit the this file, I need to escape the "-" first, it's really confusing and inconvenient.

**Comment by runspired** [comment]
This is a question for ember-cli, not ember.

**Comment by stefanpenner** [comment]
> This is a question for ember-cli, not ember.

historically this is an ember.js choice. Partials to disambiguate with non-partials where prefixed with `_` ember-cli is only dasherized, so it became `-`

**Comment by boyishwei** [comment]
Yeah, to make partials differ to non-partials with add a leading _ would be okay, same style with Ruby on Rails, but with a leading dash really not that good to edit or operate with it. People work on a system with GUI, they could open it with a editor like sub lime or text mate, but what if they only have to edit it on a terminal, that's really inconvenient.
Anyway, just through out some thoughts.

**Comment by stefanpenner** [comment]
I believe the dash is optional, so if you choose to not use it it will "just work"

ember-cli has dasherize all the things rule, to simplify naming collisions. This is unlikely to change.
