### ISSUE TITLE
positionalParams doesn't override default values

### ISSUE THREAD

**Issue by MiracleBlue** [emberjs/ember.js#11979]
It appears in the latest Ember version (1.13.6), attributes that are passed values via use of positionalParams, and have a default value defined on the component, don't override the defaults with the new value, however named assignment does override them.

Example Twiddle is here: http://ember-twiddle.com/c9b651ad89228014eaee

Notice that in `my-component.js`, I have `positionalParams: ["thing"]` on my component, with the default value being set like so: `thing: "meow"`, and then in `application.hbs` I have two instances, the first passing the attribute value via the positionalParam, the second using named assignment.  Only the named assignment version successfully overrides the original default value.

**Comment by MiracleBlue** [comment]
There's a second interesting scenario.  If you remove the default value, the positionalParam sets the value just fine, however the named assignment does not work at all.

**Comment by mixonic** [comment]
@mmun @ef4 does should positional params be overwriting properties on a component? It does not appear they do.

**Comment by pixelhandler** [comment]
@MiracleBlue I update the ember-twiddle example using the release channel of ember see http://ember-twiddle.com/489a17779603326cb9f2 I noticed that the positional params seem to work but then passing in the named param and assigning a value no longer works.

By the way were is the documentation on Positional Params? This is the first time I heard about them.

**Comment by MiracleBlue** [comment]
Interesting.  I've seen a few different examples of specifying the
positionalParams as a class property, seems that they all have different
effects!

**Comment by rwjblue** [comment]
> By the way were is the documentation on Positional Params?

@pixelhandler - Can you please create a new issue "Document Positional Params" so we don't lose track of this? 

> This is the first time I heard about them.

You and I discussed them over slack (I was showing you a few examples of how to avoid helper deprecations in your app) a few days ago...

**Comment by pixelhandler** [comment]
@rwjblue I created #12012

**Comment by Serabe** [comment]
This issue is [fixed in 2.5.0](https://ember-twiddle.com/bf446d11530f19b6aefe86404ff095a5). If anyone wants to submit a PR against 1.13, it will be considered. Otherwise, we need to close this.

Thank you for your report!
