### ISSUE TITLE
Controller#needs deprecations

### ISSUE THREAD

**Issue by jcbvm** [emberjs/ember.js#11997]
Just a question, is needs going to be removed with the 2.0 release or later when views/controllers will be removed? The reason why I'm asking this is because I have a lot of needs in my app and replacing them will be a real pain. So if they stay until views and controllers will be removed, I'll just stick with the deprecations.

**Comment by rwjblue** [comment]
Specifying `needs` to a controller will not be in 2.0.0, it was removed in https://github.com/emberjs/ember.js/pull/11770.
