### ISSUE TITLE
[Bug] renderTemplate can cause a new controller instance to be instantiated

### ISSUE THREAD

**Issue by jasonmit** [emberjs/ember.js#11995]
## Issue

`renderTemplate` does not pass the instance of the controller on to `this.render`.

https://github.com/emberjs/ember.js/blob/ba723a188d84ccc765964830a8bb7c4ae0e7970e/packages/ember-routing/lib/system/route.js#L1820

This causes `render` to generate a new instance of the controller.

https://github.com/emberjs/ember.js/blob/ba723a188d84ccc765964830a8bb7c4ae0e7970e/packages/ember-routing/lib/system/route.js#L2111-L2117

Note, this only will be an issue in the case where you register a controller to not be a singleton.

## Proposal

Pass `controller` on to `render` inside of `renderTemplate`

## Demo

http://ember-twiddle.com/ba55734e925664e363f4

`var1` is undefined in the view

Original post: http://discuss.emberjs.com/t/setupcontroller-method-and-transient-controller/8517

I suspect perhaps this will be turned down due to the focus to move away from Controllers.  I'll send a PR once there is a thumbs up, otherwise please close.

**Comment by pixelhandler** [comment]
@jasonmit I think that the example in the ember-twiddle code that uses `application.register('controller:application', 'ApplicationController', { singleton: false }` should also include a `renderTemplate` method in the route. See: http://ember-twiddle.com/d109aab10ab19b7d12bd

I added the render template method to the example, like so:

```javascript
  renderTemplate: function(appController) {
  	this.render('application', {
    	controller: appController
    });
  }
```

If you use something non standard like a controller that is not a singleton your app will need to define how to render the template as well. I don't think the default `renderTemplate` can make the implementation choices automatically. it could, but that doesn't seem to be the intention of the renderTemplate method, it seems like if you plan to do any customization to how the wiring works you'll need to define that in the `renderTemplate` method as well.

Also it's great that you provided a thorough example and links to the source code.

I think if you feel strongly about changing the default implementation for the `renderTemplate` method it would be a great idea to create an issue on the ember rfc repo to discuss there. See: https://github.com/emberjs/rfcs/blob/master/README.md#gathering-feedback-before-submitting I think the plan going forward is to discuss all issues and proposals for api changes using the RFC process or just by creating an issue on the rfc repo. Also you can create a pull request to go with your proposal / issue if you like.

**Comment by jasonmit** [comment]
@pixelhandler not disputing the fact that it's entirely unconventional and it's not something I do myself.  

This was a question asked to me and while debugging saw that `renderTemplate` doesn't pass the instance of the controller it receives as an argument onward to `render`.  Instead, `render` attempts to do a container lookup based on the routeName which triggers a new instance of the controller to be generated.  It seems unnecessary since we already have the instance and can pass it explicitly to `render`

I don't believe it changes the behavior of the existing implementation, just eliminates an unnecessary lookup and as a side-effect, eliminates this problem.

**Comment by rwjblue** [comment]
I'd be open to a PR for this, but I'm going to close this for now as it doesn't seem to be a bug per-se...
