### ISSUE TITLE
Deprecation of needs: [controller] issue

### ISSUE THREAD

**Issue by linearza** [emberjs/ember.js#11996]
Were upgrading to 1.13.6, removing all the `needs:` controller includes and replacing them with `inject.controller()` - but for some reason we still get the needs required message error, its confusing since we just removed all the needs, what are we missing here?

```Uncaught ReferenceError: <client@controller:posts/active::ember1006>#needs does not include `application`. To access the application controller from <client@controller:posts/active::ember1006>, <client@controller:posts/active::ember1006> should have a `needs` property that is an array of the controllers it has access to.```

**Comment by rwjblue** [comment]
Most likely you either have a stray one sitting around in your repo or are using an addon that is using `needs`.  Can you take a look at the stack for the deprecation and trace what object is triggering it?

**Comment by pixelhandler** [comment]
@linearza also it may help to isolate the issue by creating a code example in jsbin, jsfiddle or ember-twiddle.

**Comment by rwjblue** [comment]
I'm going to close for now, but I'm happy to reopen if you can provide more details...

**Comment by linearza** [comment]
Yes sorry, havent gotten around to this again yet. I did search our complete repo, node modules and bower components included. The only instance I could find was the liquid-fire addon.js containing the `needs: [application]` for modals, which we dont use anyway. Uninstalling a liquid-fire didnt have any effect. Our current upgrade is rather major, having postponed deprecation fixes for a while. Ill reopen the issue once things are clearer. Thanks anyway!

**Comment by rwjblue** [comment]
@linearza - Understood.  Please let us know if you track it down (or need additional help).

**Comment by transitorytammy** [comment]
hi @rwjblue.  I am working on doing an Ember upgrade and am working on removing `needs:`  per https://www.emberjs.com/deprecations/v1.x/#toc_controller-needs

I am seeing that error mentioned above.  

```error-handler.js:15 ReferenceError: <builder@controller:distribute/link::ember2849>#needs does not include `survey`. To access the survey controller from <builder@controller:distribute/link::ember2849>, <builder@controller:distribute/link::ember2849> should have a `needs` property that is an array of the controllers it has access to.```


I had changed all the `needs:` in our project to use `Ember.inject.controller`.  The only stragglers I see would be within our `ember.prod.js` showing this `needs: _emberMetalProperty_get.get(controller, 'needs')` . Or within a couple of tests folder.  Even after changing that I am still getting this error.  

Would you be able to help or provide any insight on what I may be doing wrong?

**Comment by transitorytammy** [comment]
Oh...it seems like my issue was that our templates were still referencing `controllers.survey` and after updating to just `survey` it worked.  :)
