### ISSUE TITLE
Array methods marked as private

### ISSUE THREAD

**Issue by alexspeller** [emberjs/ember.js#12004]
https://github.com/emberjs/ember.js/pull/11362 marks lots of array methods, e.g. forEach and sortBy, as private. Surely this can't be correct?

@rwjblue is this intentional?

**Comment by mixonic** [comment]
@alexspeller this was with the goal of making all doc privacy settings explicit. `forEach` and `sortBy` both seem like public API to me and a PR would be welcome marking them public on beta.
