### ISSUE TITLE
classNames incorrectly split letter by letter with the {{input}} helper

### ISSUE THREAD

**Issue by perlun** [emberjs/ember.js#12008]
This is using 2.0 beta (2.0.0-beta.4+9f7082ba).

If I specify `{{input value=value classNames="form-control"}}`, the generated DOM contains `class="form-control f o r m - c o n t r o l"`.

The problem here is two-fold: first, `classNames` is split into one CSS class for each letter (probably treated as an array and not a string). Secondly, the `ember-view` and `ember-text-field` classes get missing that way, which causes e.g. value bindings to malfunction.

If I change it to use `class="form-control"` instead, it works, but I can't find no mention whatsoever of the `class` property. :smile: Is this the `classNames` being broken in `Ember.TextField` or elsewhere? Are you supposed to use `class`?

**Comment by stefanpenner** [comment]
is your classNames not an array?

**Comment by pixelhandler** [comment]
@perlun This guide page advocates use of `class` http://guides.emberjs.com/v1.13.0/templates/binding-element-class-names/

**Comment by peec** [comment]
I can reproduce this, before one could use {{x classNames="hello"}} and now it seems one must refactor to {{x class="hello}}

**Comment by stefanpenner** [comment]
> I can reproduce this, before one could use {{x classNames="hello"}} and now it seems one must refactor to {{x class="hello"}}

This may be a regression

**Comment by perlun** [comment]
> Seem that to use classNames http://emberjs.com/api/classes/Ember.View.html#property_classNames instead of class you may need to assign an array.
> 
> The input helper closely resembles the normal HTML input so I believe the preferred way to add a class name is to use class.

Possibly. But it used to work w/ Ember 1.11 or similar, so it is indeed a change in that sense.

@stefanpenner - I can live with us changing it to be `class`, but we should definitely add it to the list of breaking changes in 2.0 in that case.

**Comment by OrKoN** [comment]
This breaking behavior appears when upgrading from 1.13.6 to 1.13.7 too.

**Comment by stefanpenner** [comment]
> This may be a regression then.

Ya, this is a regression.
