### ISSUE TITLE
Creation of bindings with /^*Binding/-named properties broken on release branch

### ISSUE THREAD

**Issue by jcope2013** [emberjs/ember.js#12006]
textBinding on 1.13.6 works appropriately and sets a text property on the component of the content's text (http://emberjs.com/api/classes/Ember.Binding.html)

1.13.6 (Working): http://ember-twiddle.com/73822bb91fb4249fbb76
Release (Broken): http://ember-twiddle.com/95b0f137eaff3d619590

**Comment by rwjblue** [comment]
In general, `fooBinding` syntax should be avoided (it is deprecated/removed for template usage and will likely be deprecated for object/JS usage sometime in the 2.x cycle), but I agree that this is definitely not an intended change at this point and we should look into figuring out what is going on.

As a work around (you likely have already thought of this), you can use `Ember.computed.alias` instead.

Demo: http://ember-twiddle.com/06914fcc0bad356c04ed

**Comment by jcope2013** [comment]
yeah it is an addon code but there is definitely ways around it, 

a glance debugging shows me

1.13.6

```
this.get('textBinding')._direction 
'fwd'
```

release 

```
this.get('textBinding')._direction 
undefined
```

also it seems this method (https://github.com/emberjs/ember.js/blob/v1.13.6/packages/ember-metal/lib/binding.js#L219) never gets called on release, as it it relying on an observer that never gets triggered, compared to 1.13.6 (https://github.com/emberjs/ember.js/blob/v1.13.6/packages/ember-metal/lib/binding.js#L175)

**Comment by jcope2013** [comment]
interestingly it seems this only happens when passing a property from route/controller to component on >= 1.13.7

this still works

controllers/application.js

```
export default Ember.Controller.extend({
  appNameBinding: 'content.text'
});
```

and this still works

```
export default Ember.Component.extend({
  foo: 'Hello',
  textBinding: "foo"
});

```

**Comment by jcope2013** [comment]
release branch is working now, closed by https://github.com/emberjs/ember.js/pull/12073 I believe

**Comment by rwjblue** [comment]
Thanks for checking and confirming!
