### ISSUE TITLE
IE Edge: do tests pass (and can a SauceLabs build label be added)?

### ISSUE THREAD

**Issue by MichaelVdheeren** [emberjs/ember.js#12007]
Would it be possible to use Ember.js on the IE Edge browser. Do tests pass? Can a Saucelabs test label be added to show the current status?

**Comment by stefanpenner** [comment]
It should work fine. Last time i checked saucelabs did not yet support IE edge, if it does we should add the label.

**Comment by MichaelVdheeren** [comment]
Just checked, they do not have Windows 10 + Edge support yet :-(

**Comment by mixonic** [comment]
@MichaelVdheeren If this is an issue for adding sauce support please update the title and description. As it stands, the ticket is pretty vague and I'm not sure what the actionable steps are we could take to close it.

**Comment by stefanpenner** [comment]
@mixonic I'll run the tests against edge, if they are green I'll close for now.

@MichaelVdheeren be sure, as soon as we are aware the sauce supports edge, we will enable it.

**Comment by MichaelVdheeren** [comment]
@mixonic it was both a question if it works/has been validated and if the badge could be added. Last one is a no-no because SauceLabs doesn't support it yet. So just verifying if they are green would already help.
@stefanpenner agreed, just verifying the test again would already help us. Thanks for the help!

**Comment by stefanpenner** [comment]
yup seems good

**Comment by rwjblue** [comment]
@MichaelVdheeren:

Each of the channel pages on the emberjs.com/builds site include a link to run the full test suite. This allows you to run the test suite against any browser that you have available (it has been very helpful for various mobile platforms).  Please report any issues for supported browsers when you test them!

![screenshot](http://monosnap.com/image/Oxo6PbyoIlCxEsDV1h4JHY5Ux2tHqz.png)

**Comment by MichaelVdheeren** [comment]
@rwjblue Thanks for the tip, didn't know!

**Comment by jareware** [comment]
https://support.saucelabs.com/customer/portal/articles/2103514-windows-10-edge-for-automated-testing-has-been-released it's available now, though I'm not sure what you're supposed to set as the `version`.
