### ISSUE TITLE
[Documentation] Positional Params

### ISSUE THREAD

**Issue by pixelhandler** [emberjs/ember.js#12012]
Here is a twiddle with an example (working): http://jsbin.com/hohici/edit?html,js,output and another one with questions about expected usage or possible bug: http://ember-twiddle.com/489a17779603326cb9f2

It's hard to address issues without the documented behavior of positionalParams used with an Ember.Component

```javascript
XFooComponent.reopenClass({
  positionalParams: ['thing']
})
```

Source:
- packages/ember-htmlbars/tests/integration/component_invocation_test.js
- packages/ember-htmlbars/lib/node-managers/component-node-manager.js

Also see related issue: #11979

**Comment by MiracleBlue** [comment]
Thanks for this!  Documenting positionalParams would be great.  I'm actually looking for something to contribute to, so perhaps I can help.

**Comment by rwjblue** [comment]
Awesome, we'd love the help here!

**Comment by MiracleBlue** [comment]
@rwjblue Alright!  I assume there's some contributing guidelines I need to read first.  I'll do that and then have a go at documenting positionalParams.

Anything I need to know about where/how to write documentation for core ember functionality?
