### ISSUE TITLE
Pathological view teardown performance

### ISSUE THREAD

**Issue by ef4** [emberjs/ember.js#12016]
I started investigating this last night but haven't had a chance to finish, so I'm posting the issue in case anybody else sees this or wants to dig in.

@chadhietala created [a repo that reproduces this issue](https://github.com/chadhietala/liquid-if-change-amp). When you toggle between the routes, you'll see a massive delay.

The problem is somewhere in the legacy childViews support. The "controller:before" and "controller:after" actions are firing over 1.1 million times each during the render.

**Comment by runspired** [comment]
1.1million times o.O that's on a scale I'm not used to hearing.

**Comment by stefanpenner** [comment]
worst case, we can special case teardown. But this legacy stuff may be causing grief in any areas as well.

**Comment by asakusuma** [comment]
Did some digging. I don't think these two functions can co-exist, at least in their current state:

https://github.com/emberjs/ember.js/blob/4630cfac6bd65f2e455b45778a7049ed2b8b7e5f/packages/ember-views/lib/mixins/view_context_support.js#L98-L104

For the repro repo, if you get rid of _notifyControllerChange, you don't have million function calls. Trying to figure out if we can just axe one of them.

**Comment by runspired** [comment]
```
_legacyControllerDidChange: observer('controller', function() {
    this.walkChildViews(view => view.notifyPropertyChange('controller'));
  }),
```

I think if you can't axe this, the answer is wrapping this method in an `if legacy` clause if possible.  Seems like `_notifyControllerChange` is dependent on an event that wouldn't be present in the legacy case.

**Comment by asakusuma** [comment]
@runspired yea I've separately tried having each function check to make sure the other doesn't exist, haven't found anything that still passes this test:

https://github.com/emberjs/ember.js/blob/680f997ed0958c420abdcd0b1673111aee26afe7/packages/ember-views/tests/views/view/controller_test.js#L7

The first 4 assertions are fine, it's the last 4 that don't pass. Yo @tomdale, git blame implicates you on both the code and the tests, got any ideas?

**Comment by ryanlitalien** [comment]
@runspired @asakusuma For my app, I was having an issue with the `view` coming in as undefined.   Error: `Uncaught TypeError: Cannot read property 'notifyPropertyChange' of undefined`.

I removed the `walkChildViews` function as @runspired hinted at, and the route transitions were successful.  I'm using Ember 2.0.1.  I'm not sure what else I could provide to assist in this issue, please let me know.

```javascript
_legacyControllerDidChange: _emberMetalMixin.observer('controller', function () { }),
```

**Comment by asakusuma** [comment]
@ryanlitalien if you can figure out a way to fix the issue and have the tests still pass, that would be awesome. I tried the change you mentioned 3 weeks ago and it broke tests.

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/12414 fixed the issue reported here
