### ISSUE TITLE
[Glimmer] confused when changes made to DOM via jquery?

### ISSUE THREAD

**Issue by opsb** [emberjs/ember.js#12015]
I'm using jquery-sortable which modifies the DOM of the lists when you drag and drop. When dragging between lists glimmer seems to become confused and fails to render some items in the list where an item has just been dragged from (in the didRender hook the list of items in the {{each}} binding doesn't match the list of items in the DOM). 

I can detect when this happens in the didRender hook but a call to this.rerender() doesn't appear to clean up the problem. Is there a way to tell glimmer that the DOM has been modified or to tell it to do a fresh render?

**Comment by tomeknn** [comment]
Hi,
I had problem with jquery-sortable too. Here's the broken code:
https://ember-twiddle.com/aa20c8f873f779e7a982?openFiles=my-component.component.js%2Cmy-component.template.hbs

And here's fixed:
https://ember-twiddle.com/feec0ea8a5434a44ae54?openFiles=my-component.component.js%2Cmy-component.template.hbs

Changes that I've made:
- I've added key="@index" to the each helper
- and i've replaced data-id with span which contains item id

Hope it will help resolve your problem.

**Comment by acorncom** [comment]
Should this issue still be open? I'll close for now, but if it's still something that needs to be open please comment and we can revisit it.
