### ISSUE TITLE
classNames="" on a {{link-to}} cause a full app refresh in 1.13.7 and 2.0.0-beta.5

### ISSUE THREAD

**Issue by chriscareycode** [emberjs/ember.js#12039]
If you have a {{link-to}} with classNames= passed such as {{link-to "library.update" classNames="btn btn-primary btn-xs"}} this will cause a full app refresh. Removing classNames= from the {{link-to}} will not trigger the bug. This appears in 1.13.7 and 2.0.0-beta.5. This bug is not seen in 1.13.6 and 2.0.0-beta.4

**Comment by rwjblue** [comment]
I believe that this is related to https://github.com/emberjs/ember.js/issues/12008.  Basically, when specifying `classNames` today the `ember-view` class is being removed so the click event isn't properly handled (and the browser does a full refresh).

**Comment by cibernox** [comment]
I faced this too today. Basically i changed `classNames=` by `class=` in my templates. They work the same AFAIK.
