### ISSUE TITLE
Add documentation for link-to current-when attribute to public documentation

### ISSUE THREAD

**Issue by benkiefer** [emberjs/ember.js#12038]
Can we get current-when for a link-to documented with the link-to component examples?

**Comment by rwjblue** [comment]
I'd gladly accept a PR adding that documentation.

**Comment by Kuzirashi** [comment]
Shouldn't this be closed because of https://github.com/emberjs/ember.js/pull/12051 merged?

**Comment by rwjblue** [comment]
Seems good to me, thanks!
