### ISSUE TITLE
willDestroyElement is not always called

### ISSUE THREAD

**Issue by ilkkao** [emberjs/ember.js#12042]
Seeing this problem in my app:

http://emberjs.jsbin.com/cijamo/edit?html,js,console,output

Matching willDestroyElement call is missing.

**Comment by ilkkao** [comment]
Multiple button clicks in the example seem to cause also memory leak.

**Comment by EricSchank** [comment]
Looks like this works as expected in 1.12.1, but doesn't dispatch the `willDestroyElement` hook in 1.13.1

**Comment by elbeezy** [comment]
seems related to #12105 and #12080

**Comment by GavinJoyce** [comment]
I just tried the [jsbin](http://emberjs.jsbin.com/cijamo/edit?html,js,console,output) on 2.3 and it seems to be working. 

@ilkkao perhaps you could confirm that this is no longer an issue for you?
