### ISSUE TITLE
didInsertElement and route refreshing

### ISSUE THREAD

**Issue by mkorfmann** [emberjs/ember.js#12053]
Prior to Ember 1.13.0, didInsertElement was called when a route was refreshed.

After Ember 1.13.0, route refreshing only triggers didRender.

Is this intentional?

**Comment by rwjblue** [comment]
`didInsertElement` is only fired when a view/component is initially inserted into the DOM.  In prior versions of Ember `this.refresh()` in a route cause all the existing DOM elements to be removed, and new ones created.  Ember 1.13 now properly preserves the DOM (this is the reason that rerendering is so much faster in 1.13) so `didInsertElement` is not called again.

> Is this intentional?

Yes.

**Comment by rwjblue** [comment]
Closing as the question has been answered...
