### ISSUE TITLE
Observers in view broken since 1.13.4

### ISSUE THREAD

**Issue by jcbvm** [emberjs/ember.js#12064]
Since ember 1.13.4 the controller property in views gets changed before `willDestroyElement` is called, in ember 1.13.3 the change was called before `didInsertElement`. 

The problem I'm facing is when I have an observer in my view which listens to a property on the controller, it gets fired when the controller property gets changed. So the observer gets called because the controller property changes instead of the property on the controller.

Here is a JSBin showing my problem:
http://emberjs.jsbin.com/yivevureye/edit?html,js,output

NOTE: this problem occurs with and without ember-legacy-views addon

**Comment by mmun** [comment]
I've verified this bug continues to exist in 1.13.13.

**Comment by Mbehnam** [comment]
How does it work?

**Comment by locks** [comment]
@mmun does the 2.x branch suffer from the same problem?

**Comment by locks** [comment]
Closing as 1.13 is not actively supported anymore.
