### ISSUE TITLE
[BUG Release] DDAU with controllers and routes is not consistent

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#12068]
It is not obvious on how to do DDAU with controllers and routes. In general the expected behavior is that as a component sends an action to mutate some data, in this case an existing model, those changes should propagate downwards, however this depends on where you handle the mutation. For instance [this jsbin](http://output.jsbin.com/jeyeki) shows that when the action is handled in a controller (:-1:), the UI re-renders with the new items however the `didReceiveAttrs` hook is only called once.

An even odder thing happens when the action is handled in the route where I wholesale replace the existing model with a new copy.  Essentially the glimmer engine should not care if this is the old model or new model, it should just efficiently update the DOM based on the new attrs.  In [this example](http://output.jsbin.com/qedeba) the hooks fire but new items are not appended to the list.

I suspect that there are bugs here and the current experience is wildly different based upon where the action is handled.

/cc @pete-the-pete @wycats @chancancode

**Comment by wycats** [comment]
@chadhietala Both of these issues definitely seem like bugs to me.

**Comment by pete-the-pete** [comment]
Setting this.currentModel *and* using set('model') with the new data seems to work; it renders the new items and calls the attrs events.

building off @chadhietala's [jsbin](http://jsbin.com/rutesiyaca/edit?html,js,console,output)
