### ISSUE TITLE
[DOCS] Opening subpage breaks version chooser

### ISSUE THREAD

**Issue by spruce** [emberjs/ember.js#12079]
When using the guides on emberjs.com one can not switch back from v2.0.0 to other versions of the guides. Probably because it failes to match to the correct item

Steps to reproduce:
1. Open http://guides.emberjs.com/v2.0.0/testing/
1. try to switch to another version
1. it trys to open http://guides.emberjs.com/v2.0.0/v1.11.0

**Comment by swr** [comment]
Good catch. This has been opened over on the Guides repo: emberjs/guides#581

Might want to just close this one out and hop over there.
