### ISSUE TITLE
Remove Legacy Hooks?

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#12076]
Specifically ones labeled as "2.0TODO: Remove legacy hooks."

https://github.com/emberjs/ember.js/blob/d2c181edf15e66ff7ae1f55083288f60352ca3e7/packages/ember-htmlbars/lib/node-managers/view-node-manager.js#L100

https://github.com/emberjs/ember.js/blob/d2c181edf15e66ff7ae1f55083288f60352ca3e7/packages/ember-htmlbars/lib/node-managers/component-node-manager.js#L157

**Comment by rwjblue** [comment]
We should remove the comments, the hooks have to stick around...

**Comment by duggiefresh** [comment]
Seems like this issue can be closed! @rwjblue
