### ISSUE TITLE
this.lookup is not a function (Release)

### ISSUE THREAD

**Issue by jcope2013** [emberjs/ember.js#12077]
firing up a ember twiddle with the release branch at the moment doesn't load with the error

```
this.lookup is not a function 
```

this might be twiddle only related? maybe I should file it there?

http://ember-twiddle.com/c7b637fd7268f81b0626

**Comment by rwjblue** [comment]
Was fixed by https://github.com/emberjs/ember.js/commit/2cdc3c88deccf6c3c19f5bfa1759de3a5ae360a5, sorry about that!
