### ISSUE TITLE
Ember 1.13.8 upgrade from 1.12.1 leads to blank page

### ISSUE THREAD

**Issue by elwayman02** [emberjs/ember.js#12084]
I'm revisiting the 1.13.x series after the early versions seemed to be difficult to upgrade.  I've gone through the `ember init` process with Ember-CLI and tested each package upgrade one at a time to make sure the app still worked.  Everything has been upgraded to the latest version except for Ember and Ember-Data, which are still on `1.12.1` and `1.0.0-beta.18`, respectively.

When I flip the switch from Ember `1.12.1` to `1.13.8`, running `ember s` leaves me with a blank screen and no console errors (just expected deprecations since I'm using some outdated patterns and still need to update).  I expect that since Ember is following semver, no deprecated features would be removed between 1.12.x and 1.13.x, so I'm not sure why the page is failing all of a sudden.

My repository is here: https://github.com/elwayman02/jordan-hawker/tree/upgrade

It's a pretty small app, wanted to get the upgrade working on something simple before tackling my larger apps, but this is proving more difficult than expected.  Anyone have an idea what's going on here?

```
// package.json (snippet)
  "devDependencies": {
    "broccoli-asset-rev": "^2.1.2",
    "broccoli-merge-trees": "^0.2.1",
    "broccoli-static-compiler": "^0.2.1",
    "ember-analytics": "0.0.5",
    "ember-bug-widget": "0.2.1",
    "ember-cli": "1.13.8",
    "ember-cli-app-version": "0.5.0",
    "ember-cli-babel": "^5.1.3",
    "ember-cli-blanket": "0.5.3",
    "ember-cli-dependency-checker": "^1.0.1",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.2.0",
    "ember-cli-ic-ajax": "0.1.4",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.0.0",
    "ember-cli-sass": "~4.0.1",
    "ember-cli-sri": "^1.0.3",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "1.0.0-beta.18",
    "ember-data-model-fragments": "0.3.3",
    "ember-disqus": "0.2.0",
    "ember-export-application-global": "^1.0.3",
    "ember-intl": "2.0.0-beta.16",
    "ember-moment": "1.2.1",
    "ember-try": "0.0.8",
    "ember-watson": "^0.5.0",
    "liquid-fire": "^0.19.3"
  }
```

```
// bower.json
{
  "name": "jordan-hawker",
  "dependencies": {
    "ember": "1.13.8",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "0.2.0",
    "ember-data": "1.0.0-beta.18",
    "ember-data.model-fragments": "0.3.3",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.5",
    "ember-qunit": "0.4.9",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.18",
    "jquery": "~2.1.4",
    "loader.js": "3.3.0",
    "qunit": "1.18.0",
    "bootstrap-sass-official": "~3.3.4",
    "fontawesome": "~4.4.0",
    "moment": "~2.10.3",
    "ember-cli-moment-shim": "~0.2.0",
    "blanket": "~1.1.5"
  }
}
```

**Comment by btecu** [comment]
I suggest updating Ember Data to 1.13.x as well. I had a similar problem.

**Comment by elwayman02** [comment]
I was hoping to upgrade Ember before Ember-Data, because there are bigger issues with the Ember-Data 1.13.x series that I wanted to address separately from the Ember upgrade, rather than having to tackle them simultaneously.  Is there no way to use older E-D versions with Ember 1.13.x?

**Comment by stefanpenner** [comment]
Thanks for the submission, a quick look reveals the app appears to be functioning/loading/running correctly, merely not visible.

bumping liquid-fire to the latest version addresses this.

```
npm install --save liquid-fire
```

@ef4 if you have some moments, this may be worth taking a look at. Something appears to have gone side-ways, but no error or failure occurred. Maybe there exists some way to message this specific failure?

**Comment by elwayman02** [comment]
:+1: can confirm that liquid-fire was the culprit...though I was using a karat for my liquid-fire version, so I don't know why I wouldn't have picked up the latest version on a fresh install...

**Comment by elwayman02** [comment]
Going to close this, since the remaining issue pertains to liquid-fire rather than Ember as stef mentioned.
