### ISSUE TITLE
Broken query params in ember 2.0.0

### ISSUE THREAD

**Issue by Eptis** [emberjs/ember.js#12081]
I have the following implementation:
Route:
```
export default Ember.Route.extend( {
  queryParams: {
    step: true
  }
})
```

Controller:
```
export default Ember.Controller.extend({
  queryParams: ["step"],
  step: 2
})
```

Template:
```
{{#link-to "installation-step" (query-params step=1)}}
    Previous
{{/link-to}}

{{#link-to "installation-step" (query-params step=3)}}
    Next
{{/link-to}}
```

Now clicking the links doesn't change the query param. Also changing the query param in the adress bar does not do anything. Am I doing something wrong according to ember 2.0.0 standards or is this a regression?

**Comment by ebryn** [comment]
Your controller looks to be a Route subclass. A JSBin example would be better for reproduction, you can create one via http://emberjs.jsbin.com

**Comment by Eptis** [comment]
Whoops ie, will check! Thanks



—
Met vriendelijke groet / Kind regards,


Dennis Tel

**Comment by ebryn** [comment]
FYI, I updated my original comment

**Comment by Eptis** [comment]
Ok changed it according the docs, but still have the same issue:
(Would want to create a jsbin but how do you illustrate the query params?)
Route:
```
export default Ember.Route.extend( {})
```

Controller:
```
export default Ember.Controller.extend({
  queryParams: ["step"],
  step: 2
})
```

Template:
```
{{#link-to "installation-step" (query-params step=1)}}
    Previous
{{/link-to}}

{{#link-to "installation-step" (query-params step=3)}}
    Next
{{/link-to}}
```

**Comment by Eptis** [comment]
Also, I tried replacing the link-to helpers with actions and setting the `step` param, but this also does not update the queryParam in the adres bar.

**Comment by Eptis** [comment]
Ok my bad, didn't notice a deprecation warning in the ember inspector of the ember-document-title plugin which was still using `_actions` this can be closed.

**Comment by john-kurkowski** [comment]
Same symptom here. Same root cause: ember-cli-document-title. Couldn't figure out where the `_actions` deprecation was coming from or its significance. So thanks for this. Properly tracked over in [ember-cli-document-title#22](https://github.com/kimroen/ember-cli-document-title/pull/22).

**Comment by kimroen** [comment]
Is it correct that because of the deprecation warning, the query params didn't update? If so, I don't think that should be discarded as an issue.

**Comment by kimroen** [comment]
Talked about this with @rwjblue.

Here is a twiddle demonstrating this issue
http://ember-twiddle.com/49b18a5dd867cbda3a7d

Adding and removing `Ember.Route.reopen({_actions: {}});` in `routes/application.js` breaks and fixes the links

**Comment by rwjblue** [comment]
I am investigating further, feels like there is something going on here...
