### ISSUE TITLE
ArrayProxy mutation no longer notifying dependent keys between 2.0.0-beta.5 - 2.0.0

### ISSUE THREAD

**Issue by gdub22** [emberjs/ember.js#12083]
http://emberjs.jsbin.com/hanexihomo/1/edit?js,output // Ember 2.0.0 final (broken)
http://emberjs.jsbin.com/camajexebe/1/edit?js,output // Ember 2.0.0-beta.5 (works)

**Comment by rwjblue** [comment]
Based on the diff between versions, https://github.com/emberjs/ember.js/pull/12036 seems most likely to have caused an issue.

@krisselden / @ef4 / @stefanpenner - Would one of y'all be able to take a look?

**Comment by stefanpenner** [comment]
ill look now.

**Comment by stefanpenner** [comment]
I've created a relatively thorough failing test case: https://github.com/emberjs/ember.js/pull/12087/files

**Comment by stefanpenner** [comment]
it appears the issue originated with e25b57c997a8d70f1aa49dbc8a01ece189a2d979
