### ISSUE TITLE
parentView undefined during willDestroyElement

### ISSUE THREAD

**Issue by dylanmensaert** [emberjs/ember.js#12080]
This happens at least since v1.13.5. When changing to an older v1.11.1, assert never fails.

jsbin: http://emberjs.jsbin.com/lireho/edit?html,js,output

It would make sense that the parentView is still present since the event is called before the element gets destroyed.
So does this work as intended?

**Comment by elbeezy** [comment]
seems related to #12105 and #12042

**Comment by rwjblue** [comment]
Confirmed that this is still an issue with current canary (what will be 2.7): http://rwjblue.jsbin.com/dupafa/edit?html,js,output.

**Comment by jelhan** [comment]
Investigated a little bit when this bug occurs since I had to write a test if a work-a-round handles the bug correctly. Had confusing results: https://ember-twiddle.com/9319ab95eb9e1d33c7bdae19d57ccd66?openFiles=templates.application.hbs%2Ctemplates.components.parent-component.hbs

**Comment by rwjblue** [comment]
Added assertions to tests being added in #13775 to ensure that this does not regress again in the future.
