### ISSUE TITLE
Refactoring Ember.HTMLBars.makeBoundHelper not bound to change.

### ISSUE THREAD

**Issue by arenoir** [emberjs/ember.js#12085]
I am trying fix all deprecation warnings in my ember 1.13.8 application. 

I am currently hung up on refactoring my helpers.  It appears that the new helpers are not bound to change.

For example the following works but is deprecated:

````
//app/helpers/format-date.js
import Ember from 'ember';
export default Ember.Handlebars.makeBoundHelper( function(value) {
  if (value) {
    return moment(value).format('MM/DD/YYYY');
  }
});
````

The following formats on first render but doesn't change when the value changes.
````
//app/helpers/format-date.js
import Ember from 'ember';
export function formatDate(value) {
  if (value) {
    return moment(value).format('MM/DD/YYYY');
  }
}
export default Ember.Helper.helper(formatDate);
````

What am I missing? sI there a way to specify a helper be bound?

**Comment by mmun** [comment]
@arenoir New style helpers return an array of params as their first argument instead of spreading them. Try `export function formatDate([ value ]) {`.

**Comment by arenoir** [comment]
Thanks @mmun, that was it.
