### ISSUE TITLE
isArray returns true for objects with property of length

### ISSUE THREAD

**Issue by schreiaj** [emberjs/ember.js#12094]
This includes models that contain a property called `length`. 

Simple fix involves changing https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/utils.js#L51 

to be 

``` javascript
if ((!isNaN(obj.length) && 'object' === type) { return true; }
```

**Comment by stefanpenner** [comment]
Our recommendation is for people to use `Array.isArray` when wanting to know if something is an actual array.

That being said, your fix looks reasonable. We would likely consider a PR

**Comment by schreiaj** [comment]
The issue was manifesting itself inside `applyMergedProperties` when using a serializer for a model that has an attribute named `length`. I'll see if I can put together a PR this weekend.

**Comment by rwjblue** [comment]
Closing in favor of PR #12202.
