### ISSUE TITLE
Using `deprecateFunc` fails in development builds.

### ISSUE THREAD

**Issue by slindberg** [emberjs/ember.js#12097]
[jsbin](http://emberjs.jsbin.com/bozadazuza/edit?js,console)

Calling `Ember.EnumerableUtils.*` methods [should trigger deprecation warnings](https://github.com/emberjs/ember.js/blob/v1.13.8/packages/ember-metal/lib/enumerable_utils.js#L38), but they currently do not.

**Comment by stefanpenner** [comment]
looks like the deprecation was in the wrong place...

**Comment by stefanpenner** [comment]
the fix for this will likely need to be `[BUGFIX stable-1-13]`
and will need to add sufficient tests to ensure the deprecation was correctly triggered.

**Comment by rwjblue** [comment]
All instances of `deprecateFunc` need to be audited and replaced with a less tricky mechanism.

@SaladFork did a grep for various usage and came up with the following list:

- [ ] ember-debug/lib/main.js:4
- [ ] ember-htmlbars/lib/helpers.js:1
- [ ] ember-metal/lib/core.js:2
- [ ] ember-metal/lib/enumerable_utils.js:10
- [ ] ember-metal/lib/main.js:7
- [ ] ember-runtime/lib/ext/function.js:2
- [ ] ember-runtime/lib/system/core_object.js:1

**Comment by slindberg** [comment]
```js
export function map(obj, callback, thisArg) {
  return obj.map ? obj.map(callback, thisArg) : _map.call(obj, callback, thisArg);
}

var deprecatedMap = map;

Ember.runInDebug(function() {
  deprecatedMap = function() {
    Ember.deprecate('Ember.EnumberableUtils.map is deprecated, please refactor to use Array.prototype.map.');
    return map.apply(this, arguments);
  };
});
```

¯\_(ツ)_/¯

**Comment by rwjblue** [comment]
Sadly, we can't nest matching debug statements (sadly this is a limitation of `defeatureify` which we are working on replacing anyways) so you have to do something a little crazier:

```javascript
export function map(obj, callback, thisArg) {
  return obj.map ? obj.map(callback, thisArg) : _map.call(obj, callback, thisArg);
}

var deprecatedMap = map;

Ember.runInDebug(function() {
  deprecatedMap = function() {
    var deprecate = Ember.deprecate; // stashing this to prevent nested defefeatureify errors
    deprecate('Ember.EnumberableUtils.map is deprecated, please refactor to use Array.prototype.map.');
    return map.apply(this, arguments);
  };
});
```

**Comment by slindberg** [comment]
Looks like [only the `Ember.EnumerableUtils` methods are affected](http://emberjs.jsbin.com/bozadazuza/edit?js,console)

**Comment by rwjblue** [comment]
Closing for now, the debug system has been revamped a bit and we will continue iterating here...
