### ISSUE TITLE
[REGRESSION] Ember.computed.sum + null

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#12096]
working 1.x: http://ember-twiddle.com/ead0375694c976377027

I believe 1.x is correct, as JS coerces `null` to `0` -> `Number(null) === 0`

This likely applies to other computed array  macros

**Comment by wagenet** [comment]
Here's a working example from 1.x: http://ember-twiddle.com/ead0375694c976377027.

**Comment by stefanpenner** [comment]
It looks like `undefined` -> `0` but =Number(undefined) === NaN` I believe the existing ember behavior here is actually expected.

**Comment by wagenet** [comment]
We should also verify the behavior of other methods that operate on arrays of numbers.
