### ISSUE TITLE
[REGRESSION]: nested component state seems to bleed state when common mixin shared

### ISSUE THREAD

**Issue by toranb** [emberjs/ember.js#12091]
I just upgraded from ember 1.13.6 to ember 1.13.7 and it seems a regression has slipped in (or I've been hacking away at the internals without knowing it). I have a failing test in this tiny example project that shows the break.

https://github.com/toranb/pods-with-components-example

The actual stack shows an addon I use is the issue (on this exact line)

https://github.com/toranb/ember-cli-simple-validation/blob/master/addon/mixins/validate.js#L29

What's strange is that in ember 1.13.7 the parent component has "name" in the dynamicEachAttrs but in addition the child component (also using this mixin) suddenly has this each attr data causing the line above to execute in a non array (model) context.

In ember 1.13.6 this dynamicEachAttrs array is empty during the save ...

The funny part is that the "save" should only first for the child as that is the context in which I clicked the button.

Here is the parent list component showing that validateEach is used

https://github.com/toranb/pods-with-components-example/blob/master/app/components/customer-list/component.js#L10

Next the child component showing we only use validate (not the validateEach)

https://github.com/toranb/pods-with-components-example/blob/master/app/components/customer-detail/component.js#L10

Here is the detail hbs that has the action/button setup (save)

https://github.com/toranb/pods-with-components-example/blob/master/app/components/customer-detail/template.hbs#L5

Here is the JS code to go with

https://github.com/toranb/pods-with-components-example/blob/master/app/components/customer-detail/component.js#L12-L14

To be totally clear - the parent hbs has a save action but w/ a diff name

https://github.com/toranb/pods-with-components-example/blob/master/app/components/customer-list/template.hbs#L13

Any help to prove/disprove this as a true regression would be much much appreciated as this broke literally every app I work on :(

**Comment by stefanpenner** [comment]
`dynamicEachAttrs` appears to explicitly shared between all instances by having it scoped to the module root https://github.com/toranb/ember-cli-simple-validation/blob/master/addon/mixins/validate.js#L3

**Comment by toranb** [comment]
Any idea how this worked before 1.13.7 ? I looked over the ChangeLog and it didn't seem to show anything that would alter this behavior from 1.13.6 - no?

**Comment by toranb** [comment]
Also- just to clarify. Using a var like I did above will be shared across the mixin because it's a singleton?

**Comment by stefanpenner** [comment]
Correct, a var at the module root is essentially a singleton.

**Comment by toranb** [comment]
funny I didn't see this 6 months ago - I'll see if I can eventually grok why it work at all :)

**Comment by stefanpenner** [comment]
I suspect some timing related change merely exposed this pre-existing issue in the validation code. I have some ideas which it may be. But I would not consider them regressions in ember, rather luck that they did not manifest sooner.

That is of course if that singleton is the source of the problem. I merely scanned the available code for potential singleton leaks that could possible account for the behavior you have explained.

**Comment by stefanpenner** [comment]
Its likely some order/timing change

**Comment by toranb** [comment]
Agreed - I'll rework the flow to avoid any stateful interaction like it does today :)

Thanks for the "quick scan" as you labeled it - much appreciated!

**Comment by toranb** [comment]
For anyone following along - I fixed and released a patch for this over the weekend

https://github.com/toranb/ember-cli-simple-validation/commit/ae89493bc0dee1faa579e9ea7ab94c265426df55

**Comment by stefanpenner** [comment]
:+1:
