### ISSUE TITLE
concatenatedProperties works in 1.13.6 but not obliged in 1.13.7+ 

### ISSUE THREAD

**Issue by rondale-sc** [emberjs/ember.js#12099]
The issue can be seen here:

http://emberjs.jsbin.com/gaqujefuce/edit?html,css,js,output

Toggle the emberjs version string to see when it starts to fail.

---
`{{ x-foo bar="quux"}}`  when `bar` is set to `["baz"]` in component and `concatenatedProperties: ['bar']`

- 1.13.6: bar equals `['baz', 'quux']`
- 1.13.7 `bar` equals `quux'` 
  - I'm not entirely certain if this is the correct behavior and I'm missing some documentation somewhere.

This was exposed when I began digging into https://github.com/yapplabs/ember-modal-dialog/issues/71.

**Comment by rwjblue** [comment]
Ugh.  @mixonic told me so.

**Comment by rondale-sc** [comment]
@rwjblue I have time to help with this, but I don't really know where to begin.

**Comment by rwjblue** [comment]
@rondale-sc will ping you in an hour, we can pair on it

**Comment by rondale-sc** [comment]
:+1:
