### ISSUE TITLE
[Feature request] Promise: willDestroyElement

### ISSUE THREAD

**Issue by peec** [emberjs/ember.js#12105]
Currently the only way of animating a component away when component is closed seems to be something like this:

https://github.com/peec/ember-css-transitions/blob/master/addon/mixins/transition-mixin.js#L105-L114

```javascript
  _transitionDestroyElement: Ember.on('willDestroyElement', function () {
    var _self = this;
    // This is currently the only way of doing this ( since willDestroyElement is not promise based.).
    var clone = this.$().clone();
    var parent = this.$().parent();
    var idx = parent.children().index(this.$());
    Ember.run.scheduleOnce('afterRender', function () {
      Ember.$(parent.children()[idx - 1]).after(clone);
      _self.transitionDomNode(clone[0], 'leave', function () {
        clone.remove();
      });
    });
  }),
```

- Which will indeed clone the element, put it at the correct place and animate it out.

But, it would be really nice if we could have a promise that could stop the element from being destroyed until we resolve it ( that is passed to the `willDestroyElement`.). React has something [similar](https://github.com/facebook/react/blob/master/src/addons/transitions/ReactCSSTransitionGroupChild.js#L141-L147).

Is this possible the way internals works atm?

**Comment by elbeezy** [comment]
seems related to #12042 and #12080

**Comment by stefanpenner** [comment]
> Is this possible the way internals works atm?

i would recommend taking a look at how liquid fire does this, or just using liquid fire directly.

**Comment by locks** [comment]
I'm closing this as the previous comment gives a path forward.
Feel free to re-open the issue if you think it's still justified, thank you.
