### ISSUE TITLE
miss-naming of file-names

### ISSUE THREAD

**Issue by gitjf** [emberjs/ember.js#12101]
Situation:
Reproducing MDN-Worldclock https://developer.mozilla.org/en-US/Apps/Quickstart/Building_simple_functionality

1.Problem: view and select depreciated
1. Solution: use https://github.com/sukima/ember-cli-select-picker

2.Problem: ember serve gives:
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
DEPRECATION: The `bind-attr` helper ('wc3/templates/components/list-picker.hbs' @ L15:C7) is deprecated in favor of HTMLBars-style bound attributes.
      at isBindAttrModifier (/Users/lo/Documents/ember wc mdn/wc12c/wc3/bower_components/ember/ember-template-compiler.js:11729:34)
      at /Users/lo/Documents/ember wc mdn/wc12c/wc3/bower_components/ember/ember-template-compiler.js:11622:15

but I head to search the file in wc3/node_modules/ember-cli-select-picker/app/templates/components/list-picker.hbs ....

same for more deprec.-errors

Using CLI

**Comment by rwjblue** [comment]
Definitely seems like you should report that `{{bind-attr}}` is deprecated to the folks over in https://github.com/sukima/ember-cli-select-picker (you can recommend the same approach that ember-modal-dialog is using as a solution).

**Comment by rwjblue** [comment]
This doesn't seem like an ember bug though...

**Comment by gitjf** [comment]
Ember bug is more on the file and path-name, as said on the title!

**Comment by rwjblue** [comment]
This is somewhat fundamental to the way addons work. Anything from the addons app/ directory is merged with your application code, and the error's path is indicating that. 

I'm very sorry that this was confusing, but this isn't really a bug.  If you hop into the ember-cli channel in the community slack (or ask on stackoverflow) I'm sure folks can help explain it better than I have done here.
