### ISSUE TITLE
Ember.View.views doesn't include components in 1.13.x

### ISSUE THREAD

**Issue by workmanw** [emberjs/ember.js#12108]
`Ember.View.views` contains component instances in 1.12.x, but not in 1.13.x.

I know `Ember.View.views` wasn't really public or recommended for use, but it was one of the most valuable debugging tools for 1.x style views. Being able to grab an instance of a view and poke at it's state via the console has helped me solve hundreds of bugs.

I'm not sure if Glimmer complicates this at all with 1.13 and beyond, but it'd be really nice to have some mechanism to easily access component instances for debugging.

**Comment by rlivsey** [comment]
Still private, but you can get access to the view registry from the container:

```javascript
container.lookup("-view-registry:main")[element.id]
```

**Comment by stefanpenner** [comment]
> I know Ember.View.views wasn't really public or recommended for use, but it was one of the most valuable debugging tools for 1.x style views. Being able to grab an instance of a view and poke at it's state via the console has helped me solve hundreds of bugs.

ember inspector also works pretty well.

**Comment by workmanw** [comment]
@rlivsey Yeap, that's what I was looking for, thanks!

@stefanpenner It took me a bit longer than it should have to figure this out. I looked for a bit and just assumed it couldn't do it. That checkbox is kind of hiding up there. But that does the trick too.

Thanks!
