### ISSUE TITLE
Difference in 2 way binding behaviour

### ISSUE THREAD

**Issue by deepan83** [emberjs/ember.js#12119]
I am upgrading my app from 1.12 to 1.13.8 and noticed the following difference in 2 way binding behaviour.

With Ember 1.13.8, the application template in the following gist prints 'shanya' followed by 'deepan'

https://gist.github.com/deepan83/9e511bc590078fcdd255

However, with 1.12.1, the above gist prints 'shanya' followed by 'shanya'. Is this difference expected between the 2 versions?

**Comment by pixelhandler** [comment]
@deepan83 I'm not sure that the difference is expected, but it does seem odd to use the on 'init' event in both the app controller and in the component for the same property, seems like that is ripe for some sort of race condition.

**Comment by locks** [comment]
I am closing this issue since it won't get fixed even if it gets acknowledged.
Feel free to re-open the issue if you think it's still justified, thank you! Sorry it didn't get addressed at the time.
