### ISSUE TITLE
Cannot display API for Ember <2.0

### ISSUE THREAD

**Issue by kamil-jakubowski** [emberjs/ember.js#12126]
Since 2.0v has been released, I can't change API version on http://emberjs.com/api/. There is only API for 2.0 and no links to previous tags.﻿Thanks in advance!

**Comment by rwjblue** [comment]
This is definitely annoying, but it isn't a bug. The latest release version's API documentation is what is online at emberjs.com/api.  We are generally working on a versioned API documentation browser (that project is at emberjs/api), but it is not ready yet.

You have a few options if you want older versions of the docs:

* You can build the website locally prior to the 2.0.0 API docs update.
* You can use an app like Dash that allows you to have multiple documentation versions locally.
* You can use a YUIDoc browser along with the auto-published YUIDoc JSON output ([found here](http://builds.emberjs.com/tags/v1.13.8/ember-docs.json)).

Sorry for the troubles!
