### ISSUE TITLE
Computed properties are not getting the property changes on components when didReceiveAttrs is defined

### ISSUE THREAD

**Issue by rmmpaderes** [emberjs/ember.js#12127]
As the title says.

When I remove the didReceiveAttrs, computed properties will be able to detect the changes and fire.

Another workaround if you really need didReceiveAttrs to be defined is to explicitly set the property in the component rather than just being passed in through templates. So I'm guessing that this is somehow related to https://github.com/emberjs/ember.js/issues/12035 but I'm not entirely sure yet.

Is this an expected behavior? I'm using Ember 1.13.8.

Here's an ember-twiddle:

http://ember-twiddle.com/5eba0f9a6d22f61dacb6

**Comment by rwjblue** [comment]
You need to call `_super`.  Working: http://ember-twiddle.com/ffd42597613fa463720c

**Comment by rmmpaderes** [comment]
Thanks. I got confused that it's a bug since `didInitAttrs()` and other lifecycle hooks doesn't need the `_super` to get it to work.

**Comment by rwjblue** [comment]
Totally understood, I agree that you shouldn't *have* to call `_super`, but is generally always best practice to call `_super` in all framework hooks.
