### ISSUE TITLE
[Documentation] Code example does not match description

### ISSUE THREAD

**Issue by morganick** [emberjs/ember.js#12122]
The description on the example states that the action will be called upon blur but the example uses `focus-in`.

https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/keywords/input.js#L83

**Comment by rwjblue** [comment]
Great catch!  Would you mind updating to `focus-out` and submitting a pull request (the commit and PR title should be prefixed with `[DOC release]`)?
