### ISSUE TITLE
Bound style attribute warnings and `Ember.String.htmlSafe`

### ISSUE THREAD

**Issue by workmanw** [emberjs/ember.js#12137]
I'm not sure if this is a bug or not, but while upgrading our app to 1.13 we noticed a lot of the following warnings:

>WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped...

The release blog post for Ember 1.11 seemed to suggest that if you used `Ember.String.htmlSafe` you could avoid these warnings. See: [Ember 1.11.0 released (escaping content)](http://emberjs.com/blog/2015/03/27/ember-1-11-0-released.html#toc_escaping-content-in-htmlbars).

I built this quick JSBin to isolate attribute binding in question: http://emberjs.jsbin.com/xopiho/edit?html,js,console,output

It seems like anytime you have a style binding that utilizes string interpolation in the template (eg `<div style="width: {{width}}px; height: {{height}}px;"></div>`), you will receive this warning. 

The workaround is to just do the interpolation in a computed property and bind the style with: `style={{computedStyleValue}}`, but I was looking for some guidance on if this is a bug on not.

**Comment by rwjblue** [comment]
This is definitely annoying, but it isn't a bug. Eventually, I would like to remove the need for the warning (and do proper CSS sanitization).

Also, I definitely see how that blog post is confusing.  Sorry about that.

**Comment by rwjblue** [comment]
Demo without warning: http://emberjs.jsbin.com/moqiro/edit?html,js,console,output

**Comment by workmanw** [comment]
No worries. Thanks for clearing that up!

**Comment by mixonic** [comment]
@jonathanKingston has been teasing a plan to attack style sanitization. Basically making `style` accept an object. It would make this valid and safe:

```
<div style={{hash height=(concat someHeight "px") width="23px"}}></div>
```

Sanitizing actual CSS instead of styles will be harder, but given enough time it is possible.

**Comment by workmanw** [comment]
@mixonic @jonathanKingston Sounds good! One initial piece of feedback I have is that looks a bit verbose. Our app supports a lot of custom sizing and positioning of things. So we normally have `height`, `width`, `top`, `left` and `background` style bindings. Maybe we're an edge case in that area and using a CP is better for us. But I just wanted to provide that feedback.

**Comment by jonathanKingston** [comment]
@workmanw the hash isn't my focus certainly. As the style usage is so common within Ember addons and React is basically advocating it as a good thing (lets not get into that fight :goberserk:) providing security that works with restrictive CSP policies is my main aim.

So yeah I will be working on an RFC however I would rather get it right than have more headaches for the core Ember developers. I'm currently working on a talk for next week about security however I should be free after then to give this the real focus that it needs to get it correct.

**Comment by skitterm** [comment]
Are there still plans underway for tackling style attribute sanitization in Ember? I've had a hard time finding much of any CSS sanitizers for front-end, even outside of Ember-land. Definitely would be happy if there's one baked into Ember!

**Comment by skitterm** [comment]
If this is any help, it looks like Yahoo's "secure handlebars" library handles style property values: https://github.com/yahoo/secure-handlebars#supported-contexts

**Comment by lvl99** [comment]
I'm glad someone else posted on this recently. I have a background-image style which keeps getting the slashes in it escaped and I've tried marking as htmlSafe to no avail. 

The docs don't really explain much with styles and there are often needs to do this stuff within the view, even though one would prefer to separate the viz from the biz.
