### ISSUE TITLE
Logic to determine local `template` lookup is incorrect.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#12134]
When a `layout` property is not present on a component, a component is invoked without a block, and `defaultTemplate` / `template` / `templateName` are present we completely ignore the layout.

Demos:

1.13: http://jsbin.com/vowoti/edit?html,js,output
1.12: http://jsbin.com/pesehi/edit?html,js,output

---

https://github.com/emberjs/ember.js/blob/v1.13.8/packages/ember-htmlbars/lib/node-managers/component-node-manager.js#L168 should also be taking the `layout` looked up from the container (via `lookupComponent` [here](https://github.com/emberjs/ember.js/blob/v1.13.8/packages/ember-htmlbars/lib/node-managers/component-node-manager.js#L47)) into consideration.

Thanks to @elwayman02 for reporting.

**Comment by EricSchank** [comment]
@rwjblue I have a PR for this one.
I submitted it against `emberjs:stable-1-13` since this code no longer exists in `master` or 2.x -- but not sure if that's the right branch.
If not, can you point me to the correct branch I should have as the merge target?
Thanks!

**Comment by rwjblue** [comment]
stable-1-13 is the correct branch to target.

**Comment by EricSchank** [comment]
Here's the PR: #12164

**Comment by rwjblue** [comment]
Fixed by #12164
