### ISSUE TITLE
The refreshModel config property doesn't work properly in Safari.

### ISSUE THREAD

**Issue by coleythebest** [emberjs/ember.js#12139]
There seems to be an issue when using query-params and setting the refreshModel property to true in Safari. After further investigation, it appears it refreshes the page too quickly and the new query params are lost. I seemed to have fixed this issue with adding a timeout of 1 millisecond. I am sure there is a better solution to this issue but this is my temporary fix. 

      queryParamsDidChange: function(changed, totalPresent, removed) {
        var qpMap = property_get.get(this, '_qp').map;

        var totalChanged = keys['default'](changed).concat(keys['default'](removed));
        for (var i = 0, len = totalChanged.length; i < len; ++i) {
          var qp = qpMap[totalChanged[i]];
          if (qp && property_get.get(this._optionsForQueryParam(qp), 'refreshModel')) {
            var that = this;
            setTimeout(function(){ that.refresh(); }, 1);
          }
        }

        return true;
      }

**Comment by pixelhandler** [comment]
@coleythebest perhaps instead of using setTimeout use `Ember.run.next`. That should allow the current run queue to be processed then handle the refresh in the next queue.

**Comment by pixelhandler** [comment]
@coleythebest I'll close this one out for now, if the issue pops up again in a newer release please reopen, thanks!
