### ISSUE TITLE
Documentation in other languages

### ISSUE THREAD

**Issue by josenberg** [emberjs/ember.js#12140]
I am Brazilian, and I wonder if there is any initiative to translate the documentation.

If this is something useful, I could translate it to Portuguese.

I'm not a translator (and my English is not 100%), but it would be good to increase the size of the community here in Brazil , and I could help it.

**Comment by pixelhandler** [comment]
@josenberg perhaps join the embercommunity.slack.com chat room and join the #documentation channel I think they could let you know what plans exist for multi-language. My best guess is that a team of translators would be needed to ensure timely delivery of docs.

**Comment by mixonic** [comment]
There is indeed an ongoing guide localization effort organized on slack in #documentation. Closing this for now!
