### ISSUE TITLE
Really slow / hanging behaviour on transitioning _away_ from a route

### ISSUE THREAD

**Issue by topaxi** [emberjs/ember.js#12147]
I wasn't really able to create a smaller app to reproduce this yet, but I started working on a GUI rewrite prototype for an (for now internal, will be open sourced at some point) application at work.

Currently running with random data using ember-cli-mirage at http://symon.topaxi.ch/ (repo here https://github.com/topaxi/ember-symon)

When I transition away from http://symon.topaxi.ch/manage/hosts to http://symon.topaxi.ch/ or anywhere else really.. The browser hangs for a bit and I get reaaally big flamegraphs with jQuery events and Backburner stuff.

Overall screenshot:
![big](https://cloud.githubusercontent.com/assets/213788/9356915/4548e792-4684-11e5-882d-fef1dffdafe2.png)

A bit zoomed in:
![zoom](https://cloud.githubusercontent.com/assets/213788/9356919/487012b0-4684-11e5-8fa8-d6fa09a4793e.png)

I can reproduce this behavior in Firefox and Chrome. Maybe I'm doing something terribly evil or wrong..?

**Comment by pixelhandler** [comment]
@topaxi with a quick read of the issue description and without reading your example app code and running the app… IMO this issue sounds too big, like it really does need to be broken down so that an actionable solution can be discovered. 

What do you think is the problem? Is this a framework issue? Or, could it be an optimization issue? Maybe a Backburner or jquery issue? 

Perhaps ask someone to pair in the embercommunity.slack.com chat room maybe with a second set of eyes the issue may be identified.

**Comment by stefanpenner** [comment]
Which versions of stuff? Seems related to something @ef4 was digging into

**Comment by ef4** [comment]
Possibly the same as #12016

**Comment by topaxi** [comment]
@stefanpenner 
Ember 2.0.0
jQuery 2.1.4
Ember-Data 2.0.0-beta.2
liquid-fire 0.21.2

**Comment by topaxi** [comment]
Just tested without liquid-fire and I get fast, instant transitions.

**Comment by topaxi** [comment]
If I switch from `{{liquid-outlet}}` to `{{outlet}}` in `https://github.com/topaxi/ember-symon/blob/master/app/manage/hosts/template.hbs` the transition also get fast. I don't use any transitions or anything in this template (not even sure why I put a `{{liquid-outlet}}` there).

This issue might be more liquid-fire related?

**Comment by stefanpenner** [comment]
> This issue might be more liquid-fire related?

i believe its an issue with ember, liquid fire exposes.

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/12414 should have fixed this (as it also fixed https://github.com/emberjs/ember.js/issues/12016)
