### ISSUE TITLE
Route.intermediateTransitionTo should be public

### ISSUE THREAD

**Issue by mike-post** [emberjs/ember.js#12149]
The Route.intermediateTransitionTo function is currently marked as private.  Unfortunately there's no other way to manually transition into an error state. If you attempt just a straight up `this.transitionTo('error', new Error('ha HA!');` then your URL is changed to `_unused_dummy_error_path_route_participants/undefined` (which is pretty gross).

If you have both an error template and an error event handler, you're pretty much forced into this pattern (see #11427).

**Comment by pixelhandler** [comment]
@mike-post yeah this seems to be a regression, the same is true in Ember 2.0 I cloned your example here http://emberjs.jsbin.com/jajuvu/edit?html,js,output

Seems like the only workaround is to catch any code that is expected to return an error?

**Comment by mixonic** [comment]
Pretty sure @pixelhandler's comment here was meant for https://github.com/emberjs/ember.js/issues/12150
