### ISSUE TITLE
Documentation for route Transition object

### ISSUE THREAD

**Issue by fullsailor** [emberjs/ember.js#12142]
`Transition` is mentioned several times in the doucumentation for `Ember.Route`, but since it is defined in [tildeio/router.js](https://github.com/tildeio/router.js) it doesn't have documentation in Ember. 

There's brief documentation in [Route#beforeModel](http://emberjs.com/api/classes/Ember.Route.html#method_beforeModel), however its not everything. In particular I was looking for `Transition#send()` because an error mentioned it, but I didn't even know that was available.

/cc @locks

**Comment by fullsailor** [comment]
What would be the correct way to document something without code in the Ember codebase? Just a file with the documentation comments?

**Comment by rwjblue** [comment]
Transition comes from https://github.com/tildeio/router.js/blob/master/lib/router/transition.js and has some documentation there, but it needs cleanup to be properly parseable as YUIDoc.

Then we also need to update our `yuidoc.json` to include `bower_components/router.js/lib/` (similar to how we [include RSVP](https://github.com/emberjs/ember.js/blob/master/yuidoc.json#L19)).

**Comment by mixonic** [comment]
@rwjblue is this considered complete?

**Comment by iezer** [comment]
@rwjblue Looks like this was merged a while ago but the documentation is not on the website. If I build the docs locally off of `ember.js/master` I see the docs for `Transition` there. Maybe it requires a website release.

**Comment by iezer** [comment]
CC @Gaurav0 ^^

**Comment by Gaurav0** [comment]
@iezer Unless consensus is built to release earlier, I don't think it will appear before Ember 2.6 ish as it was only merged to canary. If you would like to see it sooner, please discuss on #documentation slack. cc/ @acorncom @locks

**Comment by iezer** [comment]
That's great. Thanks.

**Comment by Kerrick** [comment]
Unless I'm missing it, Transition is still not documented on emberjs.com -- and we're at 2.18.

**Comment by fullsailor** [comment]
@Kerrick You're right, it looks like it was removed from the documentation in 2.17. The last time it was there was in 2.16. 

https://emberjs.com/api/ember/2.16/classes/Transition

**Comment by toddjordan** [comment]
See #16153

**Comment by Gaurav0** [comment]
@rwjblue Would copying the docs from router microlib repo to ember-source be an acceptable way to get this documented again?

**Comment by rwjblue** [comment]
Ya, but I’d want to make sure that we understand why it “disappeared” to begin with first. I suspect that it’s only gone due to refactors (e.g. path changes) in the micro lib, and perhaps our yuidoc config just needs to be updated to match the new paths...

**Comment by Gaurav0** [comment]
@rwjblue Yes, probably, but I suggested that so it wouldn't happen again.

**Comment by wycats** [comment]
@rwjblue maybe it was removed because the class itself is marked private, and we did something to weed those classes out?

**Comment by fullsailor** [comment]
@wycats To my (limited) knowledge and scanning of the Ember Docs, no there's no examples of an "interface" in Ember.

Though there is at least one similar bit of API. `DS.Snapshot` is marked private, but its methods are documented in the Guides and therefore actually public. Like `Transition`, to me this is saying if you have one of these objects, you're allowed to call its methods, but don't go instantiate your own.

Can we redefine Transition as a public class with a private constructor? Though, you were only speculating that it being marked private is what removed it from the docs in the first place.

**Comment by Gaurav0** [comment]
@fullsailor @wycats Transition was marked private before and it was still in the docs (you would have to click the private/deprecated checkbox). I think what happened was a change in configuration, like @rwjblue said. I had to do some wacky things to get it documented in the first place, because we didn't want **ALL** of https://github.com/tildeio/router.js docs imported. That's why I think we should just copy the Transition docs into `ember-source` now, so it won't happen again.

**Comment by Gaurav0** [comment]
Ember.js 3.2.1 is released. Has api docs been updated?

**Comment by nelstrom** [comment]
It looks like the API docs for Transition are now working again:

* [2.16](https://emberjs.com/api/ember/2.16/classes/Transition) - works!
* [2.17](https://emberjs.com/api/ember/2.17/classes/Transition) - 404
* [2.18](https://emberjs.com/api/ember/2.18/classes/Transition) - 404
* [3.0](https://emberjs.com/api/ember/3.0/classes/Transition) - 404
* [3.1](https://emberjs.com/api/ember/3.1/classes/Transition) - works!
* [3.2](https://emberjs.com/api/ember/3.2/classes/Transition) - works!
