### ISSUE TITLE
Template value is not updated when the value is an alias of an aliased property [2.0.0]

### ISSUE THREAD

**Issue by ppcano** [emberjs/ember.js#12148]
http://jsbin.com/zejuro/12/edit?html,js,output reproduces this error which does not occur in version 1.13.8.

```
App.IndexController = Em.Controller.extend({
  model: null,
  customer: alias('model'),
  value: alias('customer.value')
  ...
});
```

The bound template `value` is not updated on the template when its value changes, however the controller properties are updated correctly.

In this specific case, it seems that the problem only affects to the rendering engine, however I have experienced other similar error aliased properties which depends on other CPs (still investigating).

**Comment by rwjblue** [comment]
This was fixed by https://github.com/emberjs/ember.js/pull/12093 in release channel, and https://github.com/emberjs/ember.js/pull/12100 in canary and beta.  It will be released in 2.0.1 in the next few days.

Working JSBin using release channel build: http://jsbin.com/wezulo/1/edit?html,js,output
