### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by AlexCoder25** [emberjs/ember.js#12153]
After upgrading to Ember version 2.0.0 console show error:
```Uncaught TypeError: Cannot read property 'forEach' of undefined```

First I thought it's problem in vendor JS that could have deprecated code or something (because one library in vendors.js doesn't work), but then I created new clean Ember app through ```npm install ember-cli && ember new app && npm start``` (also changed version of Ember to 2.0.0) and console still was showing this error (even in clean bootstrapped application). 

I guess the problem lays in ember-data as console shows. 
![Image]
(http://puu.sh/jHRd0/ccb59fb89d.png)
![Image]
(http://puu.sh/jHRuT/35e8e384fb.png)

**Comment by rwjblue** [comment]
You must use ember data 2.0.0-beta or canary with Ember 2.0.0. 

Ember Data 1.13.9 is not compatible with Ember 2.0.0.
