### ISSUE TITLE
[Glimmer] Errors in lifecycle hooks leave app in an unrecoverable state

### ISSUE THREAD

**Issue by gpoitch** [emberjs/ember.js#12150]
1.12.0: http://emberjs.jsbin.com/deciwudaki/1/edit?html,js,output
1.13.8: http://emberjs.jsbin.com/sixavayico/1/edit?html,js,output

Before glimmer, if a runtime error occurred, ember was able to continue properly executing and clean itself up when going to other routes.  Now it appears the same original exception is constantly thrown and no further code can be executed.

**Comment by pixelhandler** [comment]
@gdub22 This does seem like a regression, I cloned your example here http://emberjs.jsbin.com/jajuvu/3/edit?html,js,console,output and used the release version of Ember, 2.0.0 and the same happens as on 1.13.8 -> unrecoverable route is stuck on bad route.

It seems like the only workaround would be to catch any code that is expected to throw an error, or has the potential to throw an error.

**Comment by rwjblue** [comment]
Still seems to be an issue in 2.5.0: http://rwjblue.jsbin.com/tibuxe/edit?html,js,output.

**Comment by pixelhandler** [comment]
@gpoitch @rwjblue is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
