### ISSUE TITLE
When variable and helper shares the same name, the helper always wins

### ISSUE THREAD

**Issue by tim-evans** [emberjs/ember.js#12155]
Calling helpers should be unambiguous. If a template has a hash or positional parameter, it should call the helper, otherwise, it should lookup the variable.

See http://ember-twiddle.com/b3b796e77b72d2e6c816

Tracking issue paddle8/ember-document-title#20
Cross posted from https://github.com/ember-cli/ember-resolver/issues/108#issuecomment-133056086

cc @stefanpenner

**Comment by stefanpenner** [comment]
> it should lookup the variable.

What check on the variable?

```
get(content, variable) === undefned // should we display the helper or the var ?
get(content, variable) === null // display the var
get(content, variable) === something // display the var
```

ideally `in` could be used:

```
variable in content
```

unfortunately that doesn't work through our user-land proxies, especially for proxies who's content comes in async.

**Comment by tim-evans** [comment]
I think the variable should always be displayed, even if it's undefined. Ambiguity because of changes in context is weird. The use case for helpers 99% requires parameters of some kind. I can foresee cases where that's not the case, but I think the ambiguity of supporting those makes the semantics of helpers much more confusing.

**Comment by stefanpenner** [comment]
@tim-evans how do we detect that a variable exists? The second part of my above comment describe the problem i see.

**Comment by rwjblue** [comment]
This doesn't seem like a bug to me. Helpers always win (and have historically), this is intentional.

**Comment by tim-evans** [comment]
If this isn't a bug, could this be documented with the new helpers? Allowing dash-less helpers that are common words can cause problems (as I've encountered).

**Comment by rwjblue** [comment]
@tim-evans and I discussed this a bit more in slack, and having helpers "win" in this case is actually fairly important.

We should document this (both in API docs and the writing helpers guide), but I don't think it can be changed easily (we actually rely on ambiguous `{{something}}` to be able to be a helper call, specifically in the case of `{{outlet}}`).

**Comment by rwjblue** [comment]
@tim-evans handled this ambiguity in his addon by adding an AST transform that detected any usages of `{{title 'foo'}}` and rewrote them to `{{page-title 'foo'}}` (in [this commit](https://github.com/tim-evans/ember-page-title/commit/669ea8021eeb6057c0acdedd908335b784da3011)).

I am going to go ahead and close this.  As annoying as the behavior is, I do not think we can change it without majorly breaking things that rely on it today.  I'm happy to merge PR's making it clear in both API docs and guides that helpers will always be used first even if a local property exists with the same name.

**Comment by tim-evans** [comment]
I think we should also document the workaround for future travelers :)

**Comment by mixonic** [comment]
This was always the downside to allowing dashes helpers.

**Comment by TeknoFiend** [comment]
I think we're running into this with an addon we built. One of the components in our addon has a property called `max` which is referenced in the component's template. But one of our consuming apps has another addon installed that defines `max` as a helper.

Seems like this is just a case of inconveniently named helper but is there a way to disambiguate our property references in the template to protect from this problem?

**Comment by rwjblue** [comment]
You can use `{{this.max}}` to get the local property.

**Comment by TeknoFiend** [comment]
I was considering doing that but was afraid that usage might go away in the future b/c I don't see it in docs anywhere (anymore). Thanks!

**Comment by tcjr** [comment]
I guess "global first, local second" resolution is just something we have to be aware of when naming properties.  It makes me a little afraid to add libraries like the awesome _ember-composable-helpers_ to a reasonably sized project because it makes [so many simple words](https://github.com/DockYard/ember-composable-helpers#available-helpers) unavailable to presentation components.
