### ISSUE TITLE
Error event / substate

### ISSUE THREAD

**Issue by btecu** [emberjs/ember.js#12166]
A way to handle errors is to include an action on the route. If the errors are generic (unauthorized, forbidden, etc.) they can be handled in the application route.
This used to work perfectly and I'm not exactly sure when it broke, but probably in `1.13`.

The documentation has the following example (http://guides.emberjs.com/v1.13.0/routing/loading-and-error-substates/):
```
actions: {
  error: function(error, transition) {
    if (error && error.status === 400) {
      // error substate and parent routes do not handle this error
      return this.transitionTo('modelNotFound');
    }

    // Return true to bubble this event to any parent route.
    return true;
  }
}
```

1. There is no `status` on `error` anymore. Now `error` contains an array of `errors` - which seems to be fine, but it's not inline with the documentation.
2. `error.errors[0].status` is not a number but a string. This is very confusing and seems like an issue. Again, not specified in the documentation.
3. It seems that no matter what you return or how you handle it, the error will still be handled somewhere else and will be logged in the console. I tested with some Ember Data errors - `401` and `404`. I do `return this.transitionTo('login');` in an occasion, but the error is still logged. If I return true, the error gets logged twice!

For the first two I could submit a pull request to update the documentation but the third one seems to possibly be an issue. Also, was the `status` change from number to string intended?

**Comment by pixelhandler** [comment]
@btecu Yeah perhaps the docs can be improved for handling an error, I think the same example exists for the 2.0 docs too http://guides.emberjs.com/v2.0.0/routing/loading-and-error-substates/

Would you be open to creating a branch and pull request on the guides project ? see https://github.com/emberjs/guides/blob/master/source/routing/loading-and-error-substates.md

**Comment by rwjblue** [comment]
Can you provide a reproduction demonstrating this?

**Comment by btecu** [comment]
@pixelhandler yes, as stated, I can do a pull request once it's clear what I should change.

@rwjblue see https://github.com/btecu/error-state and thanks for looking into it.

**Comment by elithrar** [comment]
To indirectly +1 this: this definitely bit me.

I ended up overriding `handleResponse(status, headers, payload)` on the application Adapter to return a custom `APIError(status, headers, payload.error)` type when the response doesn't pass `if (this.isSuccess(...))`, but this felt (is) clunky compared to being able to directly grab the status itself and is far removed from the example in the docs.

Making the underlying HTTP status a `number` and making it available within the top level `error` object—rather than in an `errors.error[0].status` object—would make testing status codes much simpler.

**Comment by rwjblue** [comment]
@btecu: first two things seem like documentation things, and a PR would be very welcome for those.

@btecu: last thing seems like a legit bug, but I don't know exactly how it should work off the top of my head
