### ISSUE TITLE
Property doesn't have access to synced dependencies.

### ISSUE THREAD

**Issue by QuantumKing** [emberjs/ember.js#12161]
I have some code (Ember 2.0.0):

```js
  assignedBundles: Ember.computed.readOnly('controllers.patient.assignedBundles'),

  allAssessments: Ember.computed.readOnly('controllers.application.allAssessments'),

  otherAssessments: function() {
    var bundle_assessments = this.get('assignedBundles').mapBy('assessment');
    return this.get('allAssessments').reject(function(assessment) {
      return bundle_assessments.contains(assessment.get('id'));
    }, this);
  }.property('allAssessments.[]', 'assignedBundles.[]'),
```

But I get the error `Cannot read property 'mapBy' of undefined`. I check afterwards in the Ember inspector and `assignedBundles` is correctly an array, so something is up where `otherAssessments` seems to be computed before `assignedBundles`. Has anyone else seen this?

**Comment by stefanpenner** [comment]
> assignedBundles: Ember.computed.readOnly('controllers.patient.assignedBundles'),
> 
>   allAssessments: Ember.computed.readOnly('controllers.application.allAssessments'),

i assume `controllers` is undefined?

**Comment by QuantumKing** [comment]
@stefanpenner Where would I find that?

**Comment by QuantumKing** [comment]
In my package.json I have `"ember-disable-prototype-extensions": "^1.0.0"`

**Comment by QuantumKing** [comment]
But it isn;t in my node_modules directory for some reason..

**Comment by QuantumKing** [comment]
Oups. Nevermind, that was one of my add-ons. So, where do I find that :P?

**Comment by QuantumKing** [comment]
I think this has to do with `needs` not working as it used to. Whenever I do `needs: ['someController']`, I get nothing in `Ember.computed.alias('controllers.someController.someProperty')`

**Comment by QuantumKing** [comment]
Ok, I found the commit from the changelog. It was `needs` https://github.com/emberjs/ember.js/pull/11770
