### ISSUE TITLE
Wrong convention of event names

### ISSUE THREAD

**Issue by bratukham** [emberjs/ember.js#12162]
In the documentation to Ember 2.0.0 is written that it is necessery to use dashed name convention
for events (see http://guides.emberjs.com/v2.0.0/templates/actions/#toc_specifying-the-type-of-event), but actually it still uses the old convention that is listed here: http://emberjs.com/api/classes/Ember.View.html#toc_event-names .

See [here](http://ember-twiddle.com/0dd9916e9d81fd2d0775) an example.

Is it a bug or just a mistake in the docs to Ember 2.0.0?

**Comment by pixelhandler** [comment]
@bratukham yeah I cloned your twiddle example here http://ember-twiddle.com/1cf2c695d6ae8b1527e1 and see that using `mouse-down` for the event doesn't work http://guides.emberjs.com/v2.0.0/templates/actions/#toc_specifying-the-type-of-event

**Comment by acorncom** [comment]
This issue was fixed in the guides here: https://github.com/emberjs/guides/pull/961  I think we can close this issue at this point.

@bratukham In the future, if you want to open an issue on the guides repo, we'd love to hear about it over there.  We don't always catch issues over here :-)
