### ISSUE TITLE
Multi-level aliases don't work.

### ISSUE THREAD

**Issue by QuantumKing** [emberjs/ember.js#12165]
Here is a working EmberTwiddle http://ember-twiddle.com/3a59e4ff05ef386962b5

**Comment by QuantumKing** [comment]
It works if I get rid of `contr` and just use `word: Ember.computed.alias('targetObject.word')`.

**Comment by QuantumKing** [comment]
This is Ember 2.0.0 by the way.

**Comment by stefanpenner** [comment]
should be fixed: https://github.com/emberjs/ember.js/pull/12093

**Comment by rwjblue** [comment]
Fixed in v2.0.1: http://ember-twiddle.com/de60eb7b16ca5904626d
