### ISSUE TITLE
{{render}} docs lost during 1.13 rewrite

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#12168]
See original docs in https://github.com/emberjs/ember.js/blob/v1.12.1/packages/ember-routing-htmlbars/lib/helpers/render.js#L19

Most of those docs should be added to https://github.com/emberjs/ember.js/blob/master/packages/ember-routing-htmlbars/lib/keywords/render.js.

**Comment by mwils** [comment]
I've been using Ember for a while now. It's about time I start contributing. I will add those in and submit a PR.
