### ISSUE TITLE
Esperanto is deprecated

### ISSUE THREAD

**Issue by erbridge** [emberjs/ember.js#12185]
On starting a new ember project with `1.13.8`, I get the following warning:

```
[DEPRECATION NOTICE] Esperanto is no longer under active development. To convert an ES6 module to another format, consider using Babel (https://babeljs.io)
```

**Comment by rwjblue** [comment]
Yep, we are working on fixing/updating.  Please track this over in https://github.com/ember-cli/ember-cli/issues/4733.

**Comment by stefanpenner** [comment]
This is a dupe. Please see the ember-cli repo.

**Comment by erbridge** [comment]
Ah. Sorry about that.
