### ISSUE TITLE
Spurious or misleading "Using deprecated 'template' property on a view" warning printed

### ISSUE THREAD

**Issue by DaveDuchene** [emberjs/ember.js#12191]
See: http://emberjs.jsbin.com/bajenevuzu/edit?html,css,js,output

In the sample bin, _ENABLE_LEGACY_VIEW_SUPPORT: true is set, and there are two views toggled with the button. Both views are the same, except that the "WithLayoutView" has the layout property set. Every time the WithLayoutView is displayed, the "Using deprecated 'template' property on a view" deprecation warning is printed to the console.

Notably, if the views render templates set via x-handlebars script tags instead of via template properties, then having or not having a layout property makes no difference - no warning is printed.

**I'm actually not sure what the desired behaviour is here, but it seems to me that one way or another it shouldn't be driven by the presence of a layout.**

**Comment by rwjblue** [comment]
Yes, there should be a deprecation in both of the example views.

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/blob/release-1-13/packages/ember-htmlbars/lib/node-managers/view-node-manager.js#L65-L68 should be moved into `getTemplate` helper function so that it is triggered from both when layout is present and when it is not.

**Comment by rwjblue** [comment]
If someone wants to tackle this, it should target the `release-1-13` branch (since this code path is no longer present in 2.0.0+) and have the `[BUGFIX release-1-13]` commit prefix.

**Comment by davidtadams** [comment]
Myself and @wjohnson1000 were just working on this issue and we have a question. Here is the proposed fix that we came up with https://github.com/davidtadams/ember.js/commit/92a4524dfe7c224c4f6bd0e522011c61bed44c97

It appears that this addresses the desired behavior, however it creates the 'Using deprecated template property on a view' error, which is causing a lot of tests to fail. Is this the desired functionality? Thanks

**Comment by rwjblue** [comment]
Since this only affects 1.13, I'm going to go ahead and close this.  Sorry we couldn't get to it quicker 😿 .
