### ISSUE TITLE
Possible Windows - Ember CLI conflict? Evident by 404 when loading css assets

### ISSUE THREAD

**Issue by jaredcnance** [emberjs/ember.js#12199]
After making no notable changes, my CSS Stylesheets are no longer loading and I receive the following error. 
`404 GET http://localhost:4200/assets/my-app.css`

I have reverted my code back to a previously working version which is throwing the same error.

I have run `ember init` from the CLI, but the problem persisits.

I also can no longer create a new project in a totally different directory:
```
EPERM, rename 'C:\Users\me\AppData\Roaming\npm-cache\debug\2.2.0\package\package.json'
Error: EPERM, rename 'C:\Users\me\AppData\Roaming\npm-cache\debug\2.2.0\package\package.json'
    at Error (native)
```

```
$ ember version
version: 1.13.8
node: 0.12.7
npm: 2.13.4
os: win32 x64
```

bower.json:
```
"dependencies": {
    "ember": "1.13.7",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "1.13.8",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.5",
    "ember-qunit": "0.4.9",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.18",
    "jquery": "^1.11.3",
    "loader.js": "ember-cli/loader.js#3.2.1",
    "qunit": "~1.18.0",
    "semantic-ui": "~2.0.8"
  }
```
ember-cli-build.js
```
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
    var app = new EmberApp(defaults, {
        lessOptions: {
            paths: [
              'bower_components/semantic-ui'
            ]
        }
    });

  return app.toTree();
};
```

Not sure if this is related, but I did run CCleaner on my registry the same morning the error appeared.

**Comment by rwjblue** [comment]
We generally keep this repo's issues dedicated to bugs with Ember itself. It looks like this is an ember-cli related issue, would you mind reopening this over at https://github.com/ember-cli/ember-cli?
