### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sendEvent' of undefined

### ISSUE THREAD

**Issue by spinlock99** [emberjs/ember.js#12195]
I'm getting the following error when I upgrade from `1.13.6` to `1.13.7`. I've also verified that it happens in later versions of Ember as well:

    Uncaught TypeError: Cannot read property 'sendEvent' of undefined

I haven't tracked down what is causing the issue yet so I haven't been able to create a jsbin that shows this behavior. I did come across this piece of code in backburner:

![screen shot 2015-08-24 at 3 24 09 pm](https://cloud.githubusercontent.com/assets/453431/9454094/506e9f42-4a74-11e5-9b02-4e6ec773fc3f.png)

Which let me see a bit more of the state of the app when this is happening:

![screen shot 2015-08-24 at 3 23 14 pm](https://cloud.githubusercontent.com/assets/453431/9454124/823f328e-4a74-11e5-8039-358f82e0a25e.png)

Any help would be greatly appreciated.

Thanks!

**Comment by spinlock99** [comment]
OK, I found the culprit in `packages/ember-views/lib/views/view.js`:

https://github.com/emberjs/ember.js/compare/v1.13.6...v1.13.7#diff-a9aeff1ccd7f8ef823c5b1c347b9deb8R1327

I have no idea what that line does but it seems to be the cause of the error.

**Comment by rwjblue** [comment]
In general, that line is appropriate.  Can you please share a reproduction showing the error so we can help you track it down?

**Comment by spinlock99** [comment]
I will work on putting together an simple example tomorrow. Now that I know `componentInitAttrs()` is the root of this, I've put in some debug statements and determined which one of my views is failing to render. What does `componentInitAttrs()` do? We're upgrading from such an old version of Ember that we don't even have components in our app.

**Comment by rwjblue** [comment]
`Renderer.prototype.componentInitAttrs` is defined [here](https://github.com/emberjs/ember.js/blob/bdf819565c6dba1728146e69fd8b495c735902e1/packages/ember-metal-views/lib/renderer.js#L149-L154), and its job is to initialize the attributes of that view/component.  Its primary job is to copy attributes from `this.attrs.somePropName` into `this.somePropName` before object observation starts, and to fire the `didInitAttrs` and `didReceiveAttrs` hooks (which by default are noop's).

**Comment by rwjblue** [comment]
The way that those functions are fired is via `instance.trigger` which comes from `Ember.Evented` mixin [here](https://github.com/emberjs/ember.js/blob/981e3edcf22755d73252ee8e99651168b39d3d77/packages/ember-runtime/lib/mixins/evented.js#L123-L125).  `Ember.Evented` is using `sendEvent` which is defined [here](https://github.com/emberjs/ember.js/blob/981e3edcf22755d73252ee8e99651168b39d3d77/packages/ember-metal/lib/events.js#L203).

**Comment by rwjblue** [comment]
Complete guess based on your error message: for some reason `sendEvent` is undefined inside `Ember.Evented`.  Can you put a conditional breakpoint there, and see?

**Comment by spinlock99** [comment]
So, like you might have guessed, this wound up being a bug on my side. The issue is that I'm migrating our app to ember-cli using a script that assumes that all classes are named (i.e. `MyMixin = Ember.Mixin.create({...`) The issue wound up being that some of our mixins weren't given names. This was fine in the current version of our app (using RequireJS) but the script to translate our modules wound up exporting `Ember` from the mixin file. So, the view that was blowing up wound up trying to use `Ember` as a mixin.

Anyway, thanks for all of your help with this.

**Comment by rwjblue** [comment]
Awesome, glad you got it figured out!
