### ISSUE TITLE
Override ember provided helpers in 2.0

### ISSUE THREAD

**Issue by kamalaknn** [emberjs/ember.js#12201]
In versions prior to 2.0 we defined new helpers and registered them against ember provided helpers such as `{{loc "foo"}}` like [this](http://emberjs.jsbin.com/qocike/edit?html,js,output).

But similar approach doesn't seem to be working in 2.0 - when exporting our implementation as `export Ember.Helper.helper()` in `helpers/loc.js` as seen [here](http://emberjs.jsbin.com/qocike/2/edit).

Is it a bug, that it is not possible to register new helpers against the ember reserved ones or is it no longer allowed to do so?

**Comment by rwjblue** [comment]
It is intentional that internal helpers/keywords cannot be overridden, so I don't think this is really a bug (even though it is annoying for y'all).

**Comment by kamalaknn** [comment]
Thanks @rwjblue  just needed to ensure if it was intentional.
