### ISSUE TITLE
Switch assert, deprecate, etc. internal API to modules

### ISSUE THREAD

**Issue by mmun** [emberjs/ember.js#12204]
- [x] Packages
  - [x] container
  - [x] ember
  - [x] ember-application
  - [x] ember-debug
  - [x] ember-extension-support
  - [x] ember-htmlbars
  - [x] ember-metal
  - [x] ember-metal-views
  - [x] ember-routing
  - [x] ember-routing-htmlbars
  - [x] ember-routing-views
  - [x] ember-runtime
  - [x] ember-template-compiler
  - [x] ember-testing
  - [x] ember-views
- [x] Switch defeatureify to babel-plugin-filter-imports
- [x] Remove `defeatureify` from emberjs-build.
- [x] Audit production build output to confirm debug statements are properly stripped.

**Comment by btecu** [comment]
Is there a rfc related to this?

**Comment by stefanpenner** [comment]
@btecu i don't believe this is public API

**Comment by btecu** [comment]
I just wanted to know where this is leading (what future feature needs the changes).

**Comment by stefanpenner** [comment]
* internally removing dependency on globals
* use babel for defeaturify rather then two passes.

**Comment by mmun** [comment]
@btecu: @stefanpenner is exactly right.

**Comment by rwjblue** [comment]
Packages are done, now ready to work on the babel plugin.

**Comment by rwjblue** [comment]
Babel plugin is done, I added two more items to the checklist but this is nearly done.

**Comment by mixonic** [comment]
@mmun is this still outstanding? What remains?

**Comment by mmun** [comment]
@mixonic it's done. Good catch.
