### ISSUE TITLE
[Discussion] Reopen Classes In Instance Initializers Can Easily Lead To Memory Leaks

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#12200]
@joshvfleming has recently ran across several cases where developers were reopening classes within instance initializers and retaining application instance per initialization. While retaining can look obvious in some cases, in these cases it was not so obvious and only reveals it's self in tests and fastboot environments. This lead to something that looked like the following

![](https://dl.dropboxusercontent.com/u/23503375/memory-small.png)

I know in the past there were talks about not allowing classes to be reopened once they have been initialized and I was actually working on [re-writing the core-object](https://github.com/ember-cli/core-object/pull/24/files#diff-afc1b58965eccad5700f165fd5b82765R87) to throw if the class is reopened post initialization.

I know that during the 2.x series there will be a path to adopting ES2015 classes, but I'm wondering if we should prevent this footgun in the existing core object under a feature flag.

**Comment by rwjblue** [comment]
I am in favor of preventing reopen after instantiation.

It seems like a bug fix to me, but I think it probably needs to be behind a feature flag initially to allow us an easy way to back out of it if it negatively affects a bunch of apps.

**Comment by rwjblue** [comment]
FYI - We will have to fix the following locations in `app.setupForTesting()`:

* https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/test.js#L384-L386
* https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/test.js#L426-L431

I am unsure if the first is ran prior to instantiation (I vaguely think that the router is not instantiated until after this runs), but the second definitely is reopening the current instance to add `willDestroy`.

**Comment by stefanpenner** [comment]
The biggest effort is likely refactoring embers own tests (and maybe env boot) to not do this.

We are typically concerned about long running flags like this. Especially since it may bifurcate the addon community. So let's be careful

**Comment by Samsinite** [comment]
Why not add depreciation warning instead of throwing? Would also help prevent users from doing this when they see the warning.
