### ISSUE TITLE
[Canary] Actions don't bubble up to the route when using renderTemplate

### ISSUE THREAD

**Issue by funtusov** [emberjs/ember.js#12217]
I have the following setup to render content in a modal outlet:

```javascript
  renderTemplate(controller, model) {
    this.render();
    
    this.render(this.routeName, {
      into: 'application',
      outlet: 'modal'
    });
  },

  actions: {
    actionName() {
      // do something
    }
  }
```

The template (found at ``this.routeName``) errors with 
``Uncaught Error: An action named 'actionName' was not found in <app@controller:route-name::ember607>.`` if the requested action isn't found inside the controller, either auto-generated or created manually.

**Comment by rwjblue** [comment]
Can you provide a runnable demo (JSBin or ember-twiddle.com)?

**Comment by locks** [comment]
@funtusov can you address the previous comment? Thanks.

**Comment by acorncom** [comment]
I'm going to close this issue for now, but if we still have this issue it'd be great to get a Twiddle or JSBin showing the issue 👍
