### ISSUE TITLE
Problem with view deprecation

### ISSUE THREAD

**Issue by pendar747** [emberjs/ember.js#12225]
How is it possible to add class binding to the div element that a route inserts (e.g `<div id="ember720" class="uk-width-2-3 ember-view">)`, without using the routed view?

I understand in the guide here http://emberjs.com/deprecations/v1.x/#toc_routable-views , it suggests binding the attribute inside the template, but that doesn't work for the div that is automatically inserted by ember.

I'm using v1.13.0

**Comment by rwjblue** [comment]
I would generally just suggest that you use the ember-legacy-views addon.  There is not a non-hacky way to do this without the addon until routable components land (in some future version).

**Comment by tomoguisuru** [comment]
@rwjblue I'm curious, with the view deprecations, what you would do with classNames that are applied on the application view like so. 

`views/application.js`
```
import Ember from 'ember';

export default Ember.View.extend({
    classNames: ['core-wrapper']
});
```

**Comment by rwjblue** [comment]
@tomoguisuru - See the comment directly before yours where I suggested using the `ember-legacy-views` addon is the only non-hacky way to do this today.

**Comment by locks** [comment]
I am closing this because presently routes other than the application route do not insert a `div` in the DOM, so you can have a root element and style it.
As for the application view, `ember-legacy-views` is the current solution. Ember.js 2.4 LTS will support it until 2.8 LTS.

**Comment by mixonic** [comment]
2.4-LTS releases are supported w/ bug fixes for six releases (~36 weeks) and security fixes for 10 releases (~60 weeks), so depending on the level of support your require you can stick with ember-legacy-views for far longer than until 2.8! http://emberjs.com/blog/2016/02/25/announcing-embers-first-lts.html for details.
