### ISSUE TITLE
Remove unwatchKeys

### ISSUE THREAD

**Issue by lessless** [emberjs/ember.js#12249]
Hello, as https://github.com/babel/babel/issues/906 is closed is it possible to remove `unwatchKeys` function https://github.com/emberjs/ember.js/blob/bdf819565c6dba1728146e69fd8b495c735902e1/packages/ember-metal/lib/watch_key.js#L65 ?

**Comment by rlivsey** [comment]
I think that comment is just [referring to the semicolon](https://github.com/emberjs/ember.js/blob/bdf819565c6dba1728146e69fd8b495c735902e1/packages/ember-metal/lib/watch_key.js#L63), not to the entire `unwatchKeys` function below

**Comment by rwjblue** [comment]
Correct. That semicolon and comment can be removed (not the function itself).

**Comment by rwjblue** [comment]
@lessless - Mind submitting a PR to remove that comment and extra semicolon?

**Comment by lessless** [comment]
ah what a chance is missed! :(
