### ISSUE TITLE
Uncaught TypeError: Cannot read property 'enter' of undefined ,    while using transitionToRoute

### ISSUE THREAD

**Issue by srsh144** [emberjs/ember.js#12251]
I am getting an "Uncaught TypeError: Cannot read property 'enter' of undefined". This is when i am using transitionToRoute in a controller.
The transitionToRoute function in controller, 

transitionToRoute: function() {
        // target may be either another controller or a router
        var target = get(this, 'target');
        var method = target.transitionToRoute || target.transitionTo;
        return method.apply(target, arguments);
      },

here the target variable is being assigned a view instead of controller or router. I don't know if this is a issue or am i using transitionToRoute in a wrong way. Need help here.

EDIT: The above function can be found here, https://github.com/emberjs/ember.js/tree/v2.0.1/packages/ember-routing/lib/ext/controller.js#L41

EDIT: In the above function, it calls get function with a controller object as "this", looking for "target" key in it. When i log "this.target" in transitionToRoute it prints a route class, but if i log the same variable in get function i get a view class.

I have no clue how this is happening.

**Comment by rwjblue** [comment]
This is going to be pretty hard for us to help with.  Could you provide a JSBin or ember-twiddle.com example to help us narrow down what is going on?

**Comment by srsh144** [comment]
I am sorry to raise a issue, but it was a plugin which i was using causing the issue. Plugin was modifying the target key of controller and resetting it back.

**Comment by rwjblue** [comment]
No problem! Glad you got it figured out!
