### ISSUE TITLE
route.render() to outlet fails at application level when called from lower level route

### ISSUE THREAD

**Issue by andrewjmc** [emberjs/ember.js#12268]
A recent issue with an application highlighted what I believe to be an issue with route.render commands when called from different routes.

This https://jsfiddle.net/andrewmcardle/q7y45tw1/3/ fiddle shows the issue, with an application route, child route and a dummy modal outlet at application level.

In the child route, the first button shows modal 1 in the modal outlet, but is run on the child route. Subsequent call to show modal 2, whether from the application or modal button fail without an error (both call the action in the application route). This failure is persistent even if the modal is closed.

By contrast, if on resetting the application modal 2 is loaded (which occurs from the application route), then the modal 1 button succeeds (whether at application or modal level). If the modal button is used, then it is possible to switch between modal 1 and 2 indefinitely.

As soon as modal 1 is rendered from the child route, calls to render modal 2 fail.

I can only presume this is unintended, even if displaying modals by calling route.render at different levels is not usual practice.

I don't recall this failure before I upgraded to Ember 1.13.

Thanks for your help.

**Comment by pixelhandler** [comment]
@andrewjmc Can you create a second jsfiddle example with this working in 1.12 ?

**Comment by andrewjmc** [comment]
Ah, the perils of working on a train... the saved version is not the final version of the code and lacks the necessary handlers on different routes. I am on a tablet now but will try and produce the example for 2.0 and a previous successful version tomorrow.

**Comment by andrewjmc** [comment]
Sorry for delay. Here is the JSFiddle as it should have been with Ember 2.0

https://jsfiddle.net/andrewmcardle/q7y45tw1/9/

Open modal 1 from application route and you will find you can merrily switch between modal 1 and 2. If you open from child route you will not be able to switch.

**Comment by andrewjmc** [comment]
Here you will find how it works in Ember 1.10.1

https://jsfiddle.net/andrewmcardle/amn4z2oc/1/

(NB close fails in both at application level if opened from child route).

The behaviour of failing to render without an error is clearly wrong. However, whether it is intended that the render should fail with an error, or succeed, is not clear. It would seem most sensible to me that Ember be agnostic to the route a command to render a template or disconnect an outlet came from.

**Comment by jcope2013** [comment]
related? https://github.com/emberjs/ember.js/issues/11282 I am seeing similar issue

**Comment by toddjordan** [comment]
I reproduced on twiddle here for 2.5.1: https://ember-twiddle.com/f432539d50b641e90aea28b48a9f6785?openFiles=routes.application.js%2C&route=%2Fchild

Here's the steps/behavior
1. Click on child route link
2. Click to open modal 1 from either the child route button (which goes through the child route), or the app route button (which goes through the application route)
3. Click "Modal 2 (app route)" button - modal does not render.
4. Click the Close button for Modal 1
5. Click the "Open modal 1 (app route)" button

Clicking the current route actions always work, begging the question, Is the application route really always active, meaning, can you render on its outlet from any other route?

The answer to https://github.com/emberjs/ember.js/issues/10832 would indicate that the "active" route should be the only one that can render views.  Is this closable?

**Comment by pixelhandler** [comment]
@toddjordan @andrewjmc I'll close this for now. We were not able to identify this as a bug. 

@andrewjmc did you find a work around? 

Also, if you think it's necessary to reopen the issue at a later time feel free to do so.

**Comment by andrewjmc** [comment]
Gosh, I can barely remember this now... And no, I didn't find a workaround that I can remember -- moved on to different things!

Best wishes,

Andrew
