### ISSUE TITLE
Enable multiple dynamic keys with {{get}}

### ISSUE THREAD

**Issue by Panman8201** [emberjs/ember.js#12263]
Currently, I believe the `{{get}}` helper is limited to one dynamic key.

```
{{get someObject keyA}}
```

I have a case where there are multiple dynamic keys in a path. Eg: `foo.bar.baz` The current workaround is to use multiple, nested "get's".

```
{{get (get someObject keyA) keyB}}
```

What I propose is that the get helper use the remaining params as individual keys.

```
{{get someObject keyA keyB}} // == someObject.keyA.keyB
```

It almost acts like a concat helper, but that is [not allowed in the current implementation](https://github.com/emberjs/ember.js/blob/v2.1.0-beta.2/packages/ember-htmlbars/lib/keywords/get.js#L123).

```
{{get someObject (concat keyA '.' keyB)}}
```

**Comment by rwjblue** [comment]
Nested `(get`'s seem OK/appropriate here to me.  Why does that seem wrong to you?

**Comment by stefanpenner** [comment]
@rwjblue im curious why the path variation is disallowed .

**Comment by Panman8201** [comment]
@rwjblue It just seems like it would be a nice shorthand for deep key paths. And it just reads better, no? 

There is just something about nested gets, even using the concat option, that makes by brain go "ick". And the multiple params just seems logical to me. Perhaps others feel differently.

**Comment by mmun** [comment]
@rwjblue I don't like this (get should act like Ember.get) but on the other hand, this is something that's easy to ast-transform if we have a better solution in the future.

**Comment by Panman8201** [comment]
@mmun So `this.get('foo.bar.baz');` is not the same??

**Comment by mmun** [comment]
The same as?

**Comment by btecu** [comment]
What do you use the `{{get}}` helper for?

**Comment by mmun** [comment]
@btecu The `{{get}}` helper is used when you have a dynamic member lookup, much like `foo[bar]` in JS.  Examples:

- `{{get obj somePath}}` is the template equivalent of `Ember.get(obj, somePath)`.
- `{{get obj "foo.bar"}}` is equivalent to `{{obj.foo.bar}}`.

**Comment by Panman8201** [comment]
@mmun So, re-reading everything, sounds like you feel it should at least support `{{get obj "foo.bar"}}`, currently not allowed. That would then enable the use of `{{get obj (concat dynamicFoo '.' dynamicBar)}}`. But what do you mean about ast-transform?

**Comment by mmun** [comment]
@Panman8201 If that doesn't work I am sad. It should! Forget about the AST transform, I misunderstood the problem. We both agree that `{{get obj (concat dynamicFoo '.' dynamicBar)}}` should work.

**Comment by rwjblue** [comment]
@mmun - I believe @Panman8201 mentioned this in the intro description, but we currently disallow the key to include a period. See https://github.com/emberjs/ember.js/blob/v2.1.0-beta.2/packages/ember-htmlbars/lib/keywords/get.js#L123.

**Comment by Panman8201** [comment]
Is it as simple as removing that assert? I don't see anything else holding back periods.

As for multiple dynamic keys, could that all be handled in the `buildStream()` function? Maybe by changing [this line](https://github.com/emberjs/ember.js/blob/v2.1.0-beta.2/packages/ember-htmlbars/lib/keywords/get.js#L26) to something *like*:

```
const objRef  = params[0];
const pathRef = params.slice(1).join('.');
```

That would allow for either `{{get obj foo bar}}` or `{{get obj (concat foo '.' bar)}}`. I realize the multiple dynamic keys option isn't that popular with ya, but I'm just trying to figure out how that could be enabled.

**Comment by rwjblue** [comment]
Should be fully addressed by https://github.com/emberjs/ember.js/pull/12323.
