### ISSUE TITLE
Memory leak when transitioning to inverse block

### ISSUE THREAD

**Issue by raytiley** [emberjs/ember.js#12267]
Tried to make the reproduction as simple as possible. Basically if you have an `each` inside an `if` or an `unless` statement and then transition to the inverse you leak `BuiltInStreamHelpers` and a bunch of related morphs and DOM fragments.

Reproduction: http://output.jsbin.com/zusuno

If you do a heap snapshot you'll see when hiding the each the only thing that is cleaned up for the rendered templates is the `HTMLbarsMorph`. 50 of these are deleted coresponding to the 50 items in the list.

![shows-leak](https://cloud.githubusercontent.com/assets/41680/9612607/90dba700-50b4-11e5-83ea-83d43a41525f.png)

If you compare this to an `unless` statement without an inverse, much more is cleaned up when the list is removed.

![zusuno 2015-09-01 14-24-02](https://cloud.githubusercontent.com/assets/41680/9612736/3ed3b604-50b5-11e5-8800-ec8deb453029.png)

Thanks @rwjblue for batting this one back and forth, it was a pain to reproduce.

**Comment by rwjblue** [comment]
This seems similar conceptually (but definitely not exactly the same) to the issue fixed in https://github.com/emberjs/ember.js/pull/11667.

**Comment by rwjblue** [comment]
I have a bead on this.  Random mind dump as follows:

```
calling either `options.template.yield()` or `options.inverse.yield()` in `if` sets `renderState.morphToClear` to `null`
so when the `renderAndCleanup` code runs it doesn't clear
this is good generally, when rendering `template.yield()` after `template.yield()`
so if `morphToClear` was last populated by `template` and we are rendering `template` now, clobber (this is what it does now all the time)
but if `morphToclear` was last populated by `template` and we are rendering `inverse`, we need to clear before rendering
```

The solution is to ensure that if we are not the same template as was last yielded, we need to clear the morph before rendering.  I have the fix, and am working on the tests.

**Comment by rwjblue** [comment]
https://github.com/tildeio/htmlbars/pull/407 fixes this upstream
