### ISSUE TITLE
PromiseProxyMixin seems have wrong docs

### ISSUE THREAD

**Issue by oriSomething** [emberjs/ember.js#12261]
can't say if there is a mistake in the docs of `PromiseProxyMixin` or in `PromiseProxyMixin` itself (and maybe it's me doing something wrong).
from the docs, it seems that when `promise` is resolved the content automatically will appear as part of the object as in the the docs:

```js
// Assuming the following json:
{
  firstName: 'Stefan',
  lastName: 'Penner'
}

// both properties will accessible on the proxy
proxy.get('firstName') //=> 'Stefan'
proxy.get('lastName')  //=> 'Penner'
```

but i can get the content only via property `content`. which means:
```js
proxy.get('content.firstName')
```

Edit:
Ember version  2.0.1

**Comment by sly7-7** [comment]
Could you show how you create your object proxy ?

**Comment by oriSomething** [comment]
```js
var proxy = Ember.Object.extend(Ember.PromiseProxyMixin).create({
  promise: Ember.RSVP.Promise.resolve({ hello: 1 })
});

setTimeout(function() {
  console.log(proxy.get('content.hello')); // 1
  console.log(proxy.get('hello')); // undefined
}, 0);

```

**Comment by stefanpenner** [comment]
@oriSomething seems to be working as expected. `Ember.Object` does not proxy, `Ember.Object.Proxy` would

**Comment by sly7-7** [comment]
That's exactly how DS.PromiseObject is defined in ember-data: https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/promise-proxies.js#L64

**Comment by oriSomething** [comment]
thank you! :+1: 
and feel stupid :disappointed:
