### ISSUE TITLE
"readonly" cannot bound to boolean value in input helper in Ember 2.0.1

### ISSUE THREAD

**Issue by myjpa** [emberjs/ember.js#12271]
Ember version: 2.0.1

define `isReadonly=false` in controller

and in template:
`{{input type="text" readonly=isReadonly}}`

I'm expecting it's rendering a writable field because isReadonly is false, but it renders HTML like below(simplified), and it's essentially a readonly text field.
`<input type="text" readonly="false">`

It worked as expected in Ember 1.13.2, and I found the behavior changed at least from 1.13.8, is that intentional?

**Comment by ltouro** [comment]
possible related to #11828

**Comment by myjpa** [comment]
@ltouro thanks! This should be closed, then.
