### ISSUE TITLE
Support usage of app instances in test helpers

### ISSUE THREAD

**Issue by trentmwillis** [emberjs/ember.js#12277]
As previously discussed in #12231 and ember-cli/ember-cli#4504, it is desirable to be able to use app instances during acceptance tests to avoid recreating an entire application or calling `app.reset()` for every test.

Currently, you can use `app.visit()` to get this functionality mostly working in a testing environment, but you lose the ability to properly use most of the [test helpers](https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/helpers.js) since they are bound to the application itself rather than the app instance. This only applies to helpers that use instance-specific info (e.g., `visit` which accesses the container). This should be fixed, but what is the proper way to fix it?

My initial thought is that `visit` should be re-routed to use `app.visit` and when `app.visit` is called within the context of a test, it should update `__container__` and `__deprecatedInstance__` to point to the new app instance, but I'm not sure this is correct. Thoughts?

cc: @stefanpenner @pete-the-pete

**Comment by stefanpenner** [comment]
One idea is to make the test helpers available on the app itself rather then global. This would simplify and solve some of the existing issues.

Cc @teddyzeenny

**Comment by trentmwillis** [comment]
Do you mean registering them on the app instance? The test helpers currently get registered on the app indirectly via the `testHelpers` property (e.g., `app.testHelpers.find()`).

**Comment by rwjblue** [comment]
@stefanpenner - We do keep the helpers on the application instance, but they should be on the ApplicationInstance instances instead. They should also be changed to receive the app instance instances instead of application instance.

I will try to provide better feedback/suggestions this evening.

**Comment by stefanpenner** [comment]
> but they should be on the ApplicationInstance instances instead.

yes this

**Comment by teddyzeenny** [comment]
> they should be on the ApplicationInstance instances instead. They should also be changed to receive the app instance instances instead of application instance.

:+1: 

Maybe we should also start discouraging the use of globals.

**Comment by trentmwillis** [comment]
Sounds like there are two parts to this:

1. Move test helpers to use ApplicationInstance instead of Application,
2. Deprecate (or somehow discourage) use of global helpers

I'm picturing this unfolding like so:

```js
module('Acceptance Test', {
  before() { this.app = Application.create(); },
  beforeEach() {
    this.instance = run(this.app, 'buildTestInstance'); // Creates an instance and registers the test helpers
  },
  afterEach() { run(this.instance, 'destroy'); },
  after() { run(this.app, 'destroy'); }
});

test('some test', (assert) => {
  this.instance.visit('/route');
  click('button'); // Deprecation?
});
```

Does this make sense? Also, what do we do about back-compat? I'm assuming using instances instead of app in test helpers will break a bunch of stuff.

**Comment by stefanpenner** [comment]
Ya, i am in-favor of this.

**Comment by stefanpenner** [comment]
we could always enable shorthand of:

`this.instance.visit('/route')` => `this.visit`

**Comment by tim-evans** [comment]
Could we bundle this in such a way that it mirrors component integration tests? 'Cause that would be huge.

**Comment by stefanpenner** [comment]
@tim-evans +1

**Comment by trentmwillis** [comment]
@tim-evans something like `moduleForAcceptance` maybe?

I plan to start work on this either this weekend or Monday. @stefanpenner thoughts on backwards compatibility? If it's important, maybe have two methods of registering test helpers? One that uses the ApplicationInstance and the old one with the Application.

**Comment by tim-evans** [comment]
That sounds right in line with the current test helpers. Another option would be `moduleForApp`. I don't care as long as it provides some consistency. It would be wonderful to be able to do some of these things:

```javascript
this.$(); // alias for `find`
this.click(); // alias for `click`
// and so on...
```

**Comment by rwjblue** [comment]
Closing in favor of https://github.com/emberjs/rfcs/pull/119.
