### ISSUE TITLE
Will it ever be possible to have {{outlet}} with default content aka template inheritance?

### ISSUE THREAD

**Issue by erichonkanen** [emberjs/ember.js#12273]
Will something like this ever be possible natively? Template inheritance has come up more than once for me and would be a great feature to have...

 # app/templates/index.hbs
```
<h1>This always stays the same</h1>
{{#outlet}}<p>This is a default paragraph that will always render
 on this page unless a child route renders inside it and overrides it.</p>{{/outlet}}
```
ps I used what looks like component block form in the example but I am referring to the standard {{outlet}}

The use case is I have an index route and I'd like to display some default content on that route but have child routes override that content (currently they can only render inside an {{outlet}})

**Comment by bravely** [comment]
This functionality is already effectively there- create another child route called index. Index chains down as deeply as the route exists.

**Comment by erichonkanen** [comment]
hey @bravely, ok so say I have the following routes:

```
  @route 'products', ->
    @route 'products', path: ':product_id'
```
Right now have `templates/products/index.hbs` which has an `{{outlet}}` where the `templates/products/product.hbs` renders into. Is there a way to effectively have the `{{outlet}}` on the index.hbs page contain some content? The child route does render into the outlet but I'd like the {{outlet}} on the index page to also contain some default content.

just wondering if what you explained lines up with that!

**Comment by bravely** [comment]
So, there's one other template you want to have- `templates/products.hbs`. That route, if it has an outlet, will render to `templates/products/index.hbs` by default, and then render `templates/products/product.hbs` into it when you go into that 'show' route.

**Comment by erichonkanen** [comment]
@bravely ok cool I will try that out, thanks!
