### ISSUE TITLE
toggleProperty set all properties of a component to a default value

### ISSUE THREAD

**Issue by bratukham** [emberjs/ember.js#12287]
I'm trying to implement nested components in Ember 2.0.1, but I'm getting a strange behavior when use `toggleProperty` function inside of the action handler.

The first component looks like:

```javascript
// ./components/comp-1.js
import Ember from 'ember';

export default Ember.Component.extend({
  prop1: false,
  hello: "Default text of comp-1",
      
  _changeHello: function() {
    this.set('hello', 'Text set by comp-1');
  }.on("init"),
      
  actions: {
    customAction1() {
      this.toggleProperty('prop1');
    }
  }
});
```
```handlebars
{{! ./templates/components/comp-1.hbs }}
<button {{action 'customAction1'}}>{{hello}}</button>
```

The second one is:
```javascript
// ./components/comp-2.js
import Ember from 'ember';
    
export default Ember.Component.extend({
  data: [],
      
  _doSomeImportentStuff: function() {        
    var data = [
            {name: 'Text set by comp-2', bool: false}, 
            {name: 'Text set by comp-2', bool: true}
    ];
        
    this.set('data', data);
    }.on("init")
});
```
```handlebars
{{! ./templates/components/comp-2.hbs }}
{{#each data as |d|}}
    {{comp-1 hello=d.name prop1=d.bool}}
{{/each}}
```

The component `comp-2` creates two buttons with names _Text set by comp-**1**_. If I click on a button the text changes to _Text set by comp-**2**_ because of the execution of the function `this.toggleProperty('prop1')` that is called in the action handler `customAction1`. If I remove this function or remove the setting of `prop1` from `./templates/components/comp-2.hbs` then everything works as expected, i.e. text of the buttons stays always as _Text set by comp-**1**_.

Why does `toggleProperty` function set back other properties?

Am I doing something wrong?

The behavior in action can be seen here: http://ember-twiddle.com/90798b4952deb4a83de1

**Comment by pixelhandler** [comment]
@bratukham Looks like using `on('init')` to set data seems to introduce a race condition. I forked your example without using init to set the data in comp2 - http://ember-twiddle.com/578c45a08da4372423c4 and as I would expected that name passed in from d.name to the comp1#hello prop renders properly. In the example using the on init it appear that the passed in value for hello is changed by the on init usage, then when you click the data from comp2 is used again for the hello value of comp1.

**Comment by bratukham** [comment]
@pixelhandler The problem is that the data coming from `comp-2` should be changed a little bit in `comp-1` before the rendering. Is there any other possibility to do so and not have a race condition?
Is it actually an expected bahavior in Ember to have the race conditions when `on('init')` is used?

**Comment by rwjblue** [comment]
I do not really understand what the twiddle is trying to do.  Can you make it clearer with step by step explanation of what to do and when the error state happens?

**Comment by rwjblue** [comment]
There may be a bug here, as mentioned a few months ago I can't really tell what is going on in the demo. I'm going to close this for now, but I'm happy to reopen if the demo can be explained (along with steps to repro).
