### ISSUE TITLE
currentWhen.split is not a function

### ISSUE THREAD

**Issue by Dhaulagiri** [emberjs/ember.js#12296]
Upgrading from 1.12 to 1.13.9 I'm seeing a an issue using the `current-when` argument on a `link-to` helper resulting in an error `Uncaught TypeError: currentWhen.split is not a function`.  [This twiddle](http://ember-twiddle.com/c9cb299e54380e527fb6) demonstrates the problem which seems to occur regardless of if `currentWhen` is defined or not.

Note that the problem doesn't persist if I set `current-when` directly to a string in the template, but we need to be able to set this dynamically.

**Comment by xtian** [comment]
Looks like this is fixed in canary:
http://ember-twiddle.com/50efad9f9a81c9b5613b

**Comment by rwjblue** [comment]
Awesome, thanks for checking/confirming!

**Comment by Dhaulagiri** [comment]
Will that fix be back ported to 1.13 @rwjblue?

**Comment by rwjblue** [comment]
@Dhaulagiri - I'm not sure which commit fixes it.  I am not opposed to backporting if someone tracks it down, and it is safe enough for immediate release.

**Comment by Dhaulagiri** [comment]
I can try to look, but I'm not super familiar with the Ember code base.  This is a blocking issue for our 1.13 upgrade though so I will try to make some time.

**Comment by stefanpenner** [comment]
@rwjblue I would like for us to chat about this class of issue at the meeting today. We need a stance on upgrade blocking bugs, as they can undermine our ease of upgrade goals.

Obviously we cannot fix all. But I want to make sure everyone's understanding is aligned.

**Comment by Dhaulagiri** [comment]
This is also fixed in 2.0.  The difference seems to be in this particular case that `current-when` is an object in 1.13 wheres in >= 2.0 (and presumably 1.12), it is a string.

**Comment by stefanpenner** [comment]
A quick glance suggests we are leaking MutCells (or w/e they are called)

![screen shot 2015-09-11 at 2 46 09 pm](https://cloud.githubusercontent.com/assets/1377/9827113/fcf56228-5893-11e5-989a-d853792ee7d6.png)

**Comment by stefanpenner** [comment]
ya we are leaking it and potentially others [here](https://github.com/emberjs/ember.js/blob/v1.13.9/packages/ember-routing-views/lib/views/link.js#L423-L432)

**Comment by stefanpenner** [comment]
@wycats hinted at `get-value`

a quick check confirms `getValue` instead of direct attrs interaction will solve the issue.

```js
Ember.__loader.require("ember-htmlbars/hooks/get-value").default(view.attrs['current-when'])
```

**Comment by stefanpenner** [comment]
@Dhaulagiri do you have any spare cycles to do ^^ ?

**Comment by Dhaulagiri** [comment]
@stefanpenner provided I can get some guidance as needed I'm happy to do the leg work early next week

**Comment by Dhaulagiri** [comment]
Closed by #12344

**Comment by stefanpenner** [comment]
thanks @Dhaulagiri :)

**Comment by rlivsey** [comment]
I'm seeing this again in current canary, not sure when it regressed

**Comment by phcoliveira** [comment]
I am also seeing this again with Ember 2.8.0 LTS.
