### ISSUE TITLE
jQuery Version

### ISSUE THREAD

**Issue by KennedyTedesco** [emberjs/ember.js#12293]
Any particular reason as to why are we using jQuery `1.x` on `EmberJS 2.x` by default?

https://github.com/emberjs/ember.js/blob/master/bower.json#L8

I'm using `jQuery 2.x` in my application without bugs.

Cheers!

**Comment by pixelhandler** [comment]
@KennedyTedesco me too :) I think that in the past the 1.x series of jQuery was use to older browser support as 2.x does not support some older browsers. Offhand I have no idea when the plan is to use a 2.x version of jQuery by default. But that is a dependency that the app/addon developer is free to change at will.

**Comment by KennedyTedesco** [comment]
@pixelhandler Yes. I thought they had forgotten to change the core dependencies. :smile:

But, that's it. This issue is no so important to stand open. I'm closing for now.
