### ISSUE TITLE
Ember isArray returns false for an array proxy.

### ISSUE THREAD

**Issue by snewcomer** [emberjs/ember.js#12298]
`Ember.isArray(Ember.ArrayProxy.create({ content: [] }))` now returns false for Ember 2.0.0 and greater.  I noticed one change was replacing `_emberMetalUtils.isArray` with `Array.isArray` in isArray function.

**Comment by rwjblue** [comment]
I believe this is a duplicate, and already fixed in latest release and beta build's. I'll try to link the issue/pr later.

**Comment by swastik** [comment]
I think this is the one: https://github.com/emberjs/ember.js/pull/12103
