### ISSUE TITLE
Add deprecation about modifying properties inside the didInsertElement hook to the deprecations guide

### ISSUE THREAD

**Issue by courthead** [emberjs/ember.js#12290]
Issue #11493 mentioned that the following deprecation is not mentioned in [the deprecations guide](http://emberjs.com/deprecations/v1.x/):

```DEPRECATION: A property of <Ember.OutletView:ember1021> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation.```

I'd just like to request that someone who's knowledgeable about the reasons behind this deprecation add it to the guide (or at least, in the meantime, explain it below).

**Comment by rwjblue** [comment]
Can you confirm that this is on the list of deprecations pending addition to the deprecations guide? The list is in a large checklist issue in the emberjs/website issues.

**Comment by ultimatemonty** [comment]
@rwjblue it is not in the deprecations to add issue. I made a comment to request it to be added [here](https://github.com/emberjs/website/issues/2256#issuecomment-143101382)

**Comment by furkanayhan** [comment]
For handling that deprecation, I am currently using this implementation:
```js
myMethod: function () {
  Ember.run.schedule('afterRender', this, function () {
    // some code
  }); 
}.on('init')
```
instead of this:
```js
myMethod: function () {
  // some code
}.on('didInsertElement')
```
in some cases.

**Comment by ultimatemonty** [comment]
thanks @furkanayhan! that's the same solution I'm currently using and it definitely removes the deprecation. I'm interested to hear the reasoning behind this deprecation as well as if there are any other "officially" recommended alternatives.

**Comment by wifelette** [comment]
Added to the list, thanks!
