### ISSUE TITLE
Checkboxes and checked value interaction

### ISSUE THREAD

**Issue by aldhsu** [emberjs/ember.js#12307]
[Twiddle](http://ember-twiddle.com/5edc0d844244407adfb8)
## Replication:
1. Click on control checkbox
2. Control Checkbox is still checked even if `checked` property is now false
3. Unclicked checkbox that is a copy of the control checkbox unchecks correctly

## Issue:
Binding of `checked` value seems to be overwritten by the mutation of the `checked` property. If you step through the `clickAction` you can see Control Checkbox unchecks after the property is set but rechecks after some point in Ember. My guess is while it is the default of the `action` helper to `preventDefault`, the `checked` property is still trying to be set.

## Use Case:
I want to create checkboxes such as Check All, that read their checkedness from a helper or property, fire an action without themselves setting checked.

**Comment by xtian** [comment]
@aldhsu Using the default action helper on the checkbox intercepts the click behavior as you mention, but you can also bind the to the `change` event. I think this is what you're looking for:

http://ember-twiddle.com/e670150833536d53c10b

(Note: `{{action "clickCheck" on="change"}}` accomplishes the same thing)

**Comment by aldhsu** [comment]
Thanks @xtian that solves my issue. 

From the Emberjs guide:
> By default, the {{action}} helper listens for click events and triggers the action when the user clicks on the element.

However, it is not actually preventing the default of click. In the original [Twiddle](http://ember-twiddle.com/5edc0d844244407adfb8), you can see that the event is undefined.

**Comment by aldhsu** [comment]
I have constructed this [Twiddle](http://ember-twiddle.com/5edc0d844244407adfb8).
Bit surprised with the results.
1. Default action helper
  - doesn't work - as I expected, no event is passed
2. Action helper with click specified
  - also doesn't work, which is a little surprising - no event is passed
3. Template specified click 
  - works, surprising given the above, event is passed
4. Action helper with onchange specified - works as expected, no event is passed

**Comment by xtian** [comment]
@aldhsu Yeah, this is intended. Actions are at a higher-level of abstraction than event handlers and so don't receive the DOM event when using the normal helper style (`<div {{action "foo"}}>`).

I didn't realize that the action would receive the event when using the `onclick={{action "foo"}}` style, but it makes sense because the action function is explicitly being passed as the callback for that event.

Typically when you want to interact with DOM events, you'd create a component and bind to events there:

```js
import Component from 'ember-component';
import on from 'ember-evented/on';

export default Component.extend({
  click(ev) { ... },
  hander: on('click', function(ev) { ... })
});
```

**Comment by aldhsu** [comment]
Thanks for the clarification @xtian.
