### ISSUE TITLE
classNameBindings are not updated

### ISSUE THREAD

**Issue by ilkkao** [emberjs/ember.js#12300]
http://emberjs.jsbin.com/fekine/edit?html,js,output

Text doesn't change in canary. Do `s/canary/beta/g` and the text becomes green and underlined after the 1s timeout. This may be related to my previous report https://github.com/emberjs/ember.js/issues/12234. Not sure.

**Comment by xtian** [comment]
Looks like this works now.

**Comment by rwjblue** [comment]
@xtian - Thanks for checking!  Likely fixed by https://github.com/emberjs/ember.js/pull/12318.

**Comment by ilkkao** [comment]
Confirmed. Jsbin didn't work earlier yesterday so very likely #12318 was the fix.

Also my app where I saw this problem first works now again. Thanks!
