### ISSUE TITLE
[canary] Link component no longer binds href.

### ISSUE THREAD

**Issue by nathanhammond** [emberjs/ember.js#12302]
Working on a bisect, but the `link-to` component doesn't appear to trigger computed properties fired during the `willRender` hook. As a consequence there is no `href` property bound on the component.

Broken as of the [commit prior to my link-to cleanup work landing](https://github.com/emberjs/ember.js/commit/db23f4397555bc40bb7ac7d18250805f2f42589e), known to work as of the [base of my fork I started for cleanup](https://github.com/emberjs/ember.js/commit/a3fb7a1dd8a449bd8a157821789a8641ca079434).

**Comment by nathanhammond** [comment]
[This is the commit that breaks link-to.](https://github.com/emberjs/ember.js/commit/69637502435589fcfe063eaf0f21faf069f4a70d)

I'm assuming that all of the tests still pass (including the ones that inspect the `href` attribute), so this appears to be a very insidious bug.

/cc @wycats @rwjblue

**Comment by rwjblue** [comment]
Can you make a reproduction JSBin or submit a failing test PR? The test suite does indeed pass, which seems odd if link-to href is completely busted...

**Comment by nathanhammond** [comment]
[Repro](http://emberjs.jsbin.com/hivopacibo/1/edit?html,js,output) Inspect the anchor and note that it doesn't have an `href`.

It's literally as simple as it possibly could be. If you click on the link it still works (`_invoke` gets fired) so I'm imagining that's why tests still continue to pass. Also, maybe forced lazy evaluation of the computed property by accessing it is having the attr show up "just in time" in the tests?

**Comment by rwjblue** [comment]
I'm mobile ATM, can you test on 2.1.0-beta.3 also?

**Comment by nathanhammond** [comment]
Works on 2.1.0-beta.3, works on current beta channel.

**Comment by rwjblue** [comment]
Thank you!

**Comment by rwjblue** [comment]
Submitted https://github.com/emberjs/ember.js/pull/12318 with a writeup and a fix.
