### ISSUE TITLE
Query params maping to different controllers

### ISSUE THREAD

**Issue by ivaylopivanov** [emberjs/ember.js#12308]
I have the following structure
```javascript
Router.map(function() {
	this.resource('reports', function() {
		this.route('buyer', {path: '/buyer'});
		this.route('seller', {path: '/seller'});
	});
});
```
reports controller

```javascript
export default Ember.Controller.extend({
	queryParams: ['type'],
	type: null
});
````
buyer controller 

```javascript
export default Ember.Controller.extend({
	queryParams: ['type'],
	type: null
});
````
and when the app transition from reports to reports/buyer I receive 

```javascript
Error while processing route: reports.index Assertion Failed: You're not allowed to have more than one controller property map to the same query param key, but both `reports:type` and `reports.buyer:type` map to `type`. You can fix this by mapping one of the controller properties to a different query param key via the `as` config option, e.g. `type: { as: 'other-type' }` Error: Assertion Failed: You're not allowed to have more than one controller property map to the same query param key, but both `reports:type` and `reports.buyer:type` map to `type`. You can fix this by mapping one of the controller properties to a different query param key via the `as` config option, e.g. `type: { as: 'other-type' }`
````

ember -v

version: 1.13.8
node: 0.12.7
npm: 2.13.4
os: linux x64

**Comment by pixelhandler** [comment]
@pertinax the assertion is clear, can your app not define the same query param for the parent and child? Did this work in a prior version of Ember? If so, perhaps make an ember-twiddle example showing the working code.

**Comment by pertinax** [comment]
@pixelhandler I understand what the error means. 
https://github.com/pertinax/ember-issue-12308 for example app.

**Comment by QVongoc** [comment]
Do we have any solutions for this problem? I am facing to it. I think in real scenario, we still need to share queryParams between controllers.

**Comment by mmun** [comment]
I'm closing this issue because there is no bug here. Please reopen in the [RFCs repository](https://github.com/emberjs/rfcs) if you'd like to continue discussing this feature proposal. There's been some discussion about routing/query params services lately.
