### ISSUE TITLE
bump morph-range for better error messages

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#12316]
pending: https://github.com/krisselden/morph-range/pull/6

this gives a better error message if something attempts to bind to a function.

At worst, it will throw with:  `Unsupported Content: Cannot bind to function`
At best, it will throw with: `Unsupported Content: Cannot bind to function 'NameOfFunction'`

**Comment by rwjblue** [comment]
Does this address an existing issue (either in the repo or generally)?  I am not sure how the lack of this warning/error shows up today...

**Comment by stefanpenner** [comment]
it takes this branch: https://github.com/krisselden/morph-range/pull/6/files#diff-bceb465896d0aab7ea4d6f4ac953c5b8R71

**Comment by stefanpenner** [comment]
its released: https://github.com/krisselden/morph-range/pull/6

**Comment by rwjblue** [comment]
It needs to be included in an updated HTMLBars version, that is then released and updated here.

**Comment by stefanpenner** [comment]
such tiny modules – updated my todo list

**Comment by duggiefresh** [comment]
Hello @stefanpenner, two of the three prerequisites have been completed. All there is left to do is write a regression test within the Ember repo.

If you got enough on your plate, I don't mind closing this issue out (so long as you give me a hint to what that regression test would look like). :rose: :tulip: Thanks!

**Comment by stefanpenner** [comment]
@duggiefresh thanks, i believe it should be sufficient to try and do

```js
view = Ember.View.extend({
  foo(){ }
})
```

with a template of
```hbs
{{view.foo}}
```
