### ISSUE TITLE
Inner component action sent to wormhole component instead of outer component

### ISSUE THREAD

**Issue by mdehoog** [emberjs/ember.js#12317]
I use `ember-wormhole` (https://github.com/yapplabs/ember-wormhole) for modal dialogs in my app. When an "outer" component has an "inner" component that's inside a wormhole, and the "inner" component sends an action, the action used to be fired on the "outer" component. Since PR #12289, the action is fired on the wormhole itself, which causes the error:
```
Uncaught Error: <emberapp@component:ember-wormhole::ember609> had no action handler for: actionName
```

Note that this is only an error if the "inner" component and wormhole are defined in an "outer" component template; the action works fine if the component/wormhole are in a controller template.

This fiddle reproduces the issue: http://ember-twiddle.com/1c59a1dcdb18eec69a8e. Changing the ember dependency from `canary` to `release` in `twiddle.json` fixes the issue.

**Comment by stefanpenner** [comment]
this may be a regression

**Comment by rwjblue** [comment]
I tested the provided Twiddle against 2.4/2.5 and canary.  All seems to be working properly now.

Sorry for the delay here...
