### ISSUE TITLE
Observing nested objects properties in ArrayProxy fails when using @each, works with explicit index

### ISSUE THREAD

**Issue by Kuzirashi** [emberjs/ember.js#12328]
Observing nested objects properties in ArrayProxy fails when using @each, works with explicit index like 0.

Having ArrayProxy:
~~~
testData: Ember.ArrayProxy.create({
    content: [
      Ember.Object.create({
        secondValue: testObj.create({
          val: true
        })
      })
  ]
~~~

This fires correctly when property changes (using concrete index - 0 and content):
~~~
arrayChangedExplicitly: Ember.observer('testData.content.0.secondValue.val', function () {
    console.log('Array changed with 0 index explicitly');
}),
~~~

This doesn't (using each and content):
~~~
arrayChangedEach: Ember.observer('testData.content.@each.secondValue.val', function () {
    // this does not work!
    console.log('Array changed with each');
}),
~~~

Neither:
~~~
arrayChangedEachNoContent: Ember.observer('testData.@each.secondValue.val', function () {
    // this does not work!
    console.log('Array changed with each');
})
~~~

Using Ember version:
~~~
DEBUG: -------------------------------
DEBUG: Ember  : 2.1.0-beta.3
DEBUG: jQuery : 1.11.1
DEBUG: -------------------------------
~~~

1. [SEE DEMO ON JSBIN.](http://emberjs.jsbin.com/hologopulo/1/edit?html,js,output)
2. Open dev tools and console F12
3. Toggle checkbox by clicking on it
4. Following will be logged:
~~~
Array changed with 0 index explicitly - from array nested objects observer
valChanged observer in object - from observer in object
~~~

Issue is that:
~~~
Array changed with @each
~~~
isn't logged, and using `@each` in observing objects properties in `ArrayProxy` doesn't work.

**Comment by devinus** [comment]
I believe this might be related: https://github.com/emberjs/ember.js/issues/12329

**Comment by Kuzirashi** [comment]
Yes, I also thought of referencing this issue in your issue.

**Comment by pixelhandler** [comment]
@Kuzirashi I don't believe observing nested properties are supported `'testData.content.@each.secondValue.val'` but instead only `'testData.content.@each.secondValue'` is supported (but that should be property of the object not a object itself.

See: http://guides.emberjs.com/v1.13.0/object-model/computed-properties-and-aggregate-data/

> Note that @each only works one level deep. You cannot use nested forms like todos.@each.owner.name or todos.@each.owner.@each.name.

**Comment by stefanpenner** [comment]
> Note that @each only works one level deep. You cannot use nested forms like todos.@each.owner.name or todos.@each.owner.@each.name.

this is actually meant to say you cant do. `foo.@each.other.@each` but `foo.@each.prop.prop.prop` should work.

**Comment by krisselden** [comment]
Using dependencies `foo.@each.other.@each` and `foo.@each.prop.prop.prop` have never been supported by any version of Ember and not covered by any test.  Only thing is to work without issue is to decompose into multiple CPs.

**Comment by stefanpenner** [comment]
> Using dependencies foo.@each.other.@each and foo.@each.prop.prop.prop have never been supported by any version of Ember and not covered by any test. Only thing is to work without issue is to decompose into multiple CPs.

**Comment by stefanpenner** [comment]
i believe @rwjblue is going to be adding a warning
