### ISSUE TITLE
Observing array using `array.[]` is not working in v1.13.11

### ISSUE THREAD

**Issue by devinus** [emberjs/ember.js#12329]
Reproduced here: http://ember-twiddle.com/b663e28c60942f4c3d25

**Comment by stefanpenner** [comment]
nothing appears to be consuming `allValues` doing so makes everything work. This appears to be working as expected?

**Comment by stefanpenner** [comment]
also `'allValues', 'allValues.[]', ` is redundant, 

observing `'allValues.[]'`  is a superset of  `'allValues'`

**Comment by devinus** [comment]
@stefanpenner `valuesDidChange` is consuming `allValues`.

**Comment by devinus** [comment]
Is this a case of too aggressive optimization? I have an observer observing a computed property, is that not enough to trigger a consumption?

**Comment by devinus** [comment]
A simpler example: http://ember-twiddle.com/b663e28c60942f4c3d25

**Comment by stefanpenner** [comment]
> @stefanpenner valuesDidChange is consuming allValues.

yes, but `valuesDidChange` only fires, if `allValues` has already been consumed and then changes.

**Comment by devinus** [comment]
@stefanpenner So, the takeaway is you *cannot* observe a computed property unless that computed property is consumed elsewhere?

**Comment by stefanpenner** [comment]
> @stefanpenner So, the takeaway is you cannot observe a computed property unless that computed property is consumed elsewhere?

Yes correct, think of them as Schrödingers Computed Properties. Before consumed, the state is undefined, and as such no state change notification is possible.

The laziness invariant is actually quite nice, but results in the single caveat we just discussed.

**Comment by devinus** [comment]
@stefanpenner So what's the correct way to do this then? Am I going to have to `<div class="hidden">{{allValues}}</div>` to get this to work?

**Comment by stefanpenner** [comment]
@devinus or you can call `this.get('values')` in `init`
