### ISSUE TITLE
Broken childViews support

### ISSUE THREAD

**Issue by kanongil** [emberjs/ember.js#12327]
The `childViews` property does not trigger observers when new views are added in 1.13.

For my code, I have implemented a workaround by redefining `appendChild` on my component to:
```js
MyComponent.reopen({
  appendChild (view) {
    this.linkChild(view);
    this.childViews.pushObject(view);
  }
});
```

Note that the only difference from the ember implementation is the usage of `pushObject()` instead of `push()`.

**Comment by pixelhandler** [comment]
@kanongil how about creating a pull request to fix this in Ember? I believe you are correct, we should use `pushObject` not `push`; that is required for triggering observers.

**Comment by stefanpenner** [comment]
I do not believe we intend for childViews to be observable, the overhead supporting that in all possible cases is quite tricky.

**Comment by kanongil** [comment]
Well this is unfortunate, as it used to work pre 1.13 (excepting #12353), and has changed behavior without a deprecation notice. Afaik, `childViews` was documented as normal property with a restriction that you could not modify it directly.

**Comment by krisselden** [comment]
@kanongil even before this childViews was not array observable, it worked because we tried to call notifyProperty('childViews') after parentView changed, but even then it still had bugs, the blessed way in 1.x really was array observing a container view, and there was no way of doing this that didn't have breaking edge casing.  In general, to better future proof your app for, I would derive your hierarchy from your state and not derive your state from your component hierarchy

**Comment by kanongil** [comment]
@krisselden We exactly desire to derive the state from the view/component hierarchy, as it makes a very natural fit for our application, and I suspect others as well. In our case we use it to handle d-pad focus navigation, where a parent view determines the next focusable child view to gain focus on key presses.

**Comment by rwjblue** [comment]
I'm going to go ahead and close this.

* `childViews` was not intended to be observable (and often didn't work anyways)
* deriving state from view/component hierarchy will be error prone
* `ContainerView` has been completely removed from the framework as of 2.6.0-beta.1

I am sorry that we didn't get to this in time to figure out and fix...
