### ISSUE TITLE
Ember.CollectionView looses Controller Binding after rendering Child View

### ISSUE THREAD

**Issue by spinlock99** [emberjs/ember.js#12322]
I've put up an example of this behavior here: https://github.com/spinlock99/collection-view-test

Basically, the problem is that when a CollectionView is initially rendered, it is bound to a controller:

![screen shot 2015-09-10 at 12 52 14 pm](https://cloud.githubusercontent.com/assets/453431/9799242/c9ad75ba-57ba-11e5-95c2-cc1d4313ae9a.png)

However, after a child view is added to the collection, both the CollectionView and the childView lose their controller binding:

![screen shot 2015-09-10 at 12 53 08 pm](https://cloud.githubusercontent.com/assets/453431/9799257/e947c2cc-57ba-11e5-9b0b-bcf042ce481e.png)

It looks like this is a recent regression as the 1.13.0 release does not display this behavior:

![screen shot 2015-09-10 at 1 01 38 pm](https://cloud.githubusercontent.com/assets/453431/9799454/1a083b0c-57bc-11e5-89ed-0ee9385ec04a.png)

I suspect the issue was introduced in this PR: https://github.com/emberjs/ember.js/pull/11667/files#diff-332892fa9885a540521df8421e77c7c7L25.

**Comment by rwjblue** [comment]
CollectionView has been removed from the code base (as of 2.6.0-beta.1).

Sorry for not getting this fixed quickly when originally reported.
