### ISSUE TITLE
Issue with complex Right-to-Left Language

### ISSUE THREAD

**Issue by 6d696c** [emberjs/ember.js#12324]
I found <b>ember.js</b> just now, and it is cute, but when I tried the demo as what is in <i>emberjs.com</i> home page, there <i>"My name is and I want to learn Ember!"</i>... After I typed a text in <em>Persian</em>, then any text in <em>English</em> gets reverse...
<pre>Name: ایلدرمی
My name is ایلدرمی and I want to learn Ember!</pre>
then
<pre>Name: iLDEREMi
My name is iMEREDLi and I want to learn Ember!</pre>

**Comment by rwjblue** [comment]
Hmm, I don't personally have much experience with RTL languages in an Ember app though I am sure that it can be done well.

Perhaps others with experience can chime in (maybe with examples)?

**Comment by georgeyacoub** [comment]
@6d696c I can't reproduce the issue.

**Comment by stefanpenner** [comment]
> I found ember.js just now, and it is cute, but when I tried the demo as what is in emberjs.com home page, there "My name is and I want to learn Ember!"... After I typed a text in Persian, then any text in English gets reverse...

which browser?

**Comment by 6d696c** [comment]
It is ok with:
<pre>Firefox 40.0.3
Version 45.0.2454.85 m</pre>
but has problem with:
<pre>Firefox Nightly 43.0a1
Firefox 41.0b8</pre>
<pre>OS: Windows Server 2012 (v6.2 - build 9200)</pre>

**Comment by pixelhandler** [comment]
@6d696c the HTML for the emberjs.com website sets the lang for `en` `<html lang="en">` so browser are supposed to treat english as left-to-right, but it sounds like you browser (Firefox) is not playing nice. Building a web page/app for a right-to-left audience needs the locale configured properly and the browser needs to support that locale. This is not an Ember.js issue, but you've shown that the Ember.js site is not optimized for more than one locale. I am not sure that there is any team that will be supporting localization for the Ember website and documentation as that is significant effort. It would be best to treat the Emberjs.com website as one that is optimized for english only. Not sure why Firefox is having problems with that.

**Comment by 6d696c** [comment]
Thanks everyone :+1:
