### ISSUE TITLE
Public methods for 'private' object Ember.Map

### ISSUE THREAD

**Issue by htmldrum** [emberjs/ember.js#12332]
https://github.com/emberjs/ember.js/blob/v2.0.1/packages/ember-metal/lib/map.js#L226

Wanting to call #keys or #values on a map seems pretty innocuous. Can we get support for public 'keys' and 'values' methods rather than needing to inspect the map object's keys?

**Comment by stefanpenner** [comment]
We cannot. These have different experience in es6 which we can't polyfill.

Please use forEach to enumerate
