### ISSUE TITLE
There should be a way to route based on subdomain.

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember.js#12335]
For example:

help.domain.com routes to the help route with path '/'

**Comment by pixelhandler** [comment]
@NullVoxPopuli this is outside the scope of the Ember Router. The browser treats a subhuman as a reference to an IP address (DNS). the full domain, including subdomain are necessary for the browser to load your website, once loaded only the path can be used in the Ember Router (anything in the URL after the domain).

**Comment by NullVoxPopuli** [comment]
So then, would it be possible, say on page load, to transition to a particular route based on the current subdomain?

like:

x.mysite.com => route-x?
y.mysite.com => route-y?

**Comment by stefanpenner** [comment]
@NullVoxPopuli you could use a redirect in the ApplicationRoute.

This does not appear to be a bug, rather a question: Typically, we recommend stackoverflow for that, as it is more geared to Q/A. For feature requests, we have an RFC process: https://github.com/emberjs/rfcs
