### ISSUE TITLE
Bootstrap-select IE8

### ISSUE THREAD

**Issue by acid-srvnn** [emberjs/ember.js#12333]
Ember version : 1.13.10
In IE8, Ember.Array.filter has this line `if (this.hasOwnProperty(i)) ` and bootstap-select calls this method with a host object. IE8 doesn't define `hasOwnProperty` for host objects and this causes error.

I know IE8 isn't supported. Any chance that you guys can add a check if the object has the method in 1.13.x series?

**Comment by rwjblue** [comment]
We have a branch that you can target (release-1-13) for PR's that only affect 1.13 and would love to land a fix for this if you have the time to track it down and submit the PR.
