### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by rodfersou** [emberjs/ember.js#12343]
I'm sorry to say this way, but ember logo sucks.. it don't inspire confidence, and IMHO you should think about to replace it to something that represents what ember really is, (even the blueprint of eiffel tower image from main page do a better job than the actual logo)

**Comment by mixonic** [comment]
@rodfersou Unfortunately, it would be very difficult to disappoint [all the young programmers getting into Ember](https://twitter.com/koryteg/status/637813357391708164) with an immediate change :smile: Not to mention all the companies such as LinkedIn, Yahoo, Groupon, McGraw Hill, and Conde Nast who are happy to participate in the Ember ecosystem, logo and all.

Thanks for the constructive criticism. I would suggest a starting platform other than "X sucks" if you would like to motivate changes to a project in the future. Cheers!

**Comment by machty** [comment]
[This EmberConf vid](https://youtu.be/xsG0gDkvDPw?t=382) might offer some perspective / defense of the hamster mascot

**Comment by rodfersou** [comment]
@mixonic @machty thank you
