### ISSUE TITLE
route.transitionTo not working for queryParams

### ISSUE THREAD

**Issue by mike-post** [emberjs/ember.js#12349]
I can't seem to make a route transition to itself with the addition of queryParams.  For example, if you simply do `ember generate route foo` and then fill out `app/routes/foo.js` as so:

````
import Ember from 'ember';

export default Ember.Route.extend({
  afterModel (model, transition) {
    if (!transition.queryParams.fooParam) {
      return this.transitionTo({ queryParams: { fooParam: 'bar' }});
    }
  }
});
````

The internal route transitions are reported as follows:
````
ember.debug.js:5227DEBUG: -------------------------------
ember.debug.js:5227DEBUG: Ember      : 2.0.2
ember.debug.js:5227DEBUG: Ember Data : 2.0.0
ember.debug.js:5227DEBUG: jQuery     : 2.1.4
ember.debug.js:5227DEBUG: -------------------------------
Ember Inspector Active
Attempting URL transition to /foo
ember.debug.js:27245Preparing to transition from '' to ' foo'
ember.debug.js:49956Transition #0: application: calling beforeModel hook
ember.debug.js:49956Transition #0: application: calling deserialize hook
ember.debug.js:49956Transition #0: application: calling afterModel hook
ember.debug.js:49956Transition #0: foo: calling beforeModel hook
ember.debug.js:49956Transition #0: foo: calling deserialize hook
ember.debug.js:49956Transition #0: foo: calling afterModel hook
ember.debug.js:49959Attempting transition to foo
ember.debug.js:49956Transition #0: Resolved all models on destination route; finalizing transition.
ember.debug.js:27194Transitioned into 'foo'
ember.debug.js:49956Transition #0: TRANSITION COMPLETE.
````

The transition is clearly attempted after the afterModel hook, but it never completes.  I initially thought this was an issue with route parameters or nested routes, but eventually got it down to this pretty simple test case that shows this feature is not working. I get the same results whether I use beforeModel or afterModel.

**Comment by mike-post** [comment]
Or maybe I just need to read the routing guide. Adding

````
  quereyParams: {
    fooParam: {
      refreshModel: true
    }
  }
````

makes it behave as expected.

**Comment by xtian** [comment]
Yeah, I believe this is working as intended.

**Comment by pixelhandler** [comment]
@mike-post that is correct you need to use `refreshModel: true` to reload the model hooks when the value for a query param changes.

**Comment by lalitindoria** [comment]
I can still reproduce this. I have the following in my route:
`queryParams: {
        instance: {
            refreshModel: false
        }
    },`

and my `afterModel` hook has this:
`afterModel: function (model, transition) {
        var self = this;
        if(!transition.queryParams.instance || Ember.typeOf(transition.queryParams.instance) !== 'number') {
            self.transitionTo({queryParams: {instance: 193}});
        }
    },`

**Comment by dcohenb** [comment]
+1 Also happens to me, any news on this?
