### ISSUE TITLE
Actions not being caught by item controller in 1.13

### ISSUE THREAD

**Issue by gordonkristan** [emberjs/ember.js#12347]
I may have discovered another bug closely related to #12340. Below I have 2 JSBins that contain something like this:

```
{{#each item in list itemController='item'}}
    {{! This action will be caught by the controller in 1.13.3 but not in 1.13.4}}
    <a {{action 'something'}}>
        {{item.model}}
    </a>
{{/each}}
```

In Ember 1.12.0, the `something` action is caught by the item controller for the `each` loop, as one would expect. In Ember 1.13 the action bypasses the item controller and goes directly to the route controller. Unless this behavior was deprecated pre-1.0, I think this may be a regression.

[Working in 1.12.0](http://emberjs.jsbin.com/cejihubaro/1/edit?html,js,console,output)
[Broken in 1.13.0](http://emberjs.jsbin.com/sokakerami/1/edit?html,js,console,output)

(I filed this as a separate issue because it seems likely that these two have separate causes since they were introduced in different versions. But feel free to close this as a duplicate if need be.)

**Comment by stefanpenner** [comment]
Work around is to set the target manually to the item controller.

I am unsure if we should change the 1.13 semantics...

**Comment by rwjblue** [comment]
The prior behavior seems like a bug. In a non-context shifting ('each foo in bar' or 'each bar as |foo|') actions in the block should absolutely target the same thing as an action just outside the each. The block should have exactly the same context/target as outside the block.

**Comment by stefanpenner** [comment]
@rwjblue agreed, and if the 1.12 behavior is wanted, public API `{{action name value target=item}}` should d the trick.
