### ISSUE TITLE
ObjectProxy is private? What does this mean exactly?

### ISSUE THREAD

**Issue by toranb** [emberjs/ember.js#12355]
http://emberjs.com/api/classes/Ember.ObjectProxy.html

In the docs I see ObjectProxy is marked as "private" but I use this day-to-day so I can return from a route async, paint, then resolve and update the template. Is this "private" mention to keep people out who aren't library authors or will this/should this throw a dep warning of some kind?

I'm using ember 2.1 beta 4 and don't see any warnings or errors using this or ArrayProxy ...

**Comment by workmanw** [comment]
This might be relevant: #11599

**Comment by toranb** [comment]
@workmanw awesome find! thank you

**Comment by workmanw** [comment]
@toranb Yeap! We too use Ember.ObjectProxy from time to time, especially BufferProxy related things.
