### ISSUE TITLE
Properties are leaked into components

### ISSUE THREAD

**Issue by danwang** [emberjs/ember.js#12357]
##### JSBin example
http://emberjs.jsbin.com/lafumeduse/edit?html,js,console,output

On v1.13.5, I see `"childValue is incorrect from controller"`.

##### Description
When using a component with both a `layoutName` and `templateName`, the context of the `templateName` template is not from the component, but rather the context adjacent to it.

I know that `template` and `templateName` are deprecated, but I was unable to find the Correct Way of doing this.

Outside this example, I have several components that share surrounding template. For example (heavily simplified):

```
(app/components/component1.hbs)
{{#surrounding-component a=a b=b c=c ...}}
  Something custom to component1 here
{{/surrounding-component}}
```

```
(app/components/component2.hbs)
{{#surrounding-component a=a b=b c=c ...}}
  Something custom to component2 here
{{/surrounding-component}}
```

I'd like to DRY out the usage of `surrounding-component` and the properties passed in the template across all components that follow this pattern. What would be great is if I could instead do

```
(app/templates/partials/surrounding-component)
{{#surrounding-component a=a b=b c=c ...}}
  {{yield}}
{{/surrounding-component}}
```

```
(app/components/component1.hbs)
{{#partial "partials/surrounding-component"}}
  ...
{{/partial}}
```

**Comment by pixelhandler** [comment]
@danwang In your example bin it appear to time that the behavior is expected. see http://emberjs.jsbin.com/nebozimuge/1/edit?html,js,console,output

I added `childValue=childValue` to show that is what is happening. The layout (parent) and template (child) both use `childValue` which appears to shadow the childValue in the current scope (controller).

Seems to me it would be best to explicitly pass in values for component properties and avoid shadowing the properties. It appears that the controller is defining the `childValue` which is picked up by the layout and template.

Avoid using a templateName with components. Sounds like some refactoring is needed. If the partial works for you great, it may avoid repeating the variable assignments.

**Comment by danwang** [comment]
Agreed. I'd like to not use `{layout,template}Name` entirely. Block partials do not exist in Ember, so I'm unable to use that solution.

**Comment by locks** [comment]
@danwang does the `{{component}}` helper allow a path forward for you?
