### ISSUE TITLE
http-mock, bodyParser and Content-Type: application/vnd.api+json

### ISSUE THREAD

**Issue by rbemis** [emberjs/ember.js#12352]
It appears that http-mock needs the bodyParser middleware to read req.body, but bodyParser does not like the JSON API media type application/vnd.api+json, which is the content type generated by the JSONAPIAdapter and required by the [JSON API spec](http://jsonapi.org/format/). If you post a request to an http-mock with Content-Type: application/vnd.api+json, req.body will be {}, empty, but without bodyParser, req.body will be undefined. This seems like a bug to me. Please advise.

**Comment by xtian** [comment]
Did you mean to open this issue on the [Ember CLI](https://github.com/ember-cli/ember-cli) repo?
