### ISSUE TITLE
`Ember.trySet()` throws 'Assertion Failed: calling set on destroyed object'

### ISSUE THREAD

**Issue by XrXr** [emberjs/ember.js#12356]
From the documentation:

> Error-tolerant form of Ember.set. Will not blow up if any part of the chain is undefined, null, or **destroyed**.

1.13.10:
http://emberjs.jsbin.com/sufaji/edit?html,js,console

2.0.2:
http://emberjs.jsbin.com/yafacu/edit?html,js,console

Open up the console to see the assertion error.

**Comment by pixelhandler** [comment]
@XrXr indeed this looks like a bug. still there is a simple workaround, use `try` and `catch`. 

Your examples show that the case for tolerant set of a destroyed object does not work, the code doesn't seem to support the claim in the docs either.

See: https://github.com/emberjs/ember.js/blob/v2.0.1/packages/ember-metal/lib/property_set.js#L50

So either the docs are wrong or the implementation doesn't support the docs.

**Comment by Serabe** [comment]
A few points on the issue:

1. *Chain* may refer only to the path.
2. Though the [documentation](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/property_set.js#L133) does not say that `trySet` is deprecated, [its test](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/tests/accessors/set_path_test.js#L70) are under a [deprecated comment](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/tests/accessors/set_path_test.js#L47).

**Comment by rwjblue** [comment]
Submitted https://github.com/emberjs/ember.js/pull/13355 to fix this.

**Comment by afinne** [comment]
Is this going to be fixed, or should `trySet` be considered deprecated?

**Comment by amk221** [comment]
I would also like to know the answer. I'm currently using my own version of `trySet` which is `isDestroyed` tolerant whilst I wait for this to be fixed.

**Comment by ryanrishi** [comment]
+1
