### ISSUE TITLE
Promise Proxy Mixin exceptions are not catchable

### ISSUE THREAD

**Issue by acalfo** [emberjs/ember.js#12361]
Relates to issue #9888
"The proxied fail handler isn't called, and the exception that's rethrown in PromiseProxyMixin isn't caught by the application. This is causing our error handling acceptance tests to fail."

PromiseArray is experiencing the same issue as the linked related issue, where rethrown exceptions in the PromiseProxyMixin are not catchable at the application level. Thrown error reads 'Uncaught [Return Type]" in the console.

JSFiddle example: http://jsfiddle.net/pk54m2sx/12/

**Comment by pixelhandler** [comment]
@acalfo this is true I tried another example as well https://jsfiddle.net/pixelhandler/vo15wwf2/2/

However I'm not sure that this is a bug or the intended design. http://emberjs.com/api/classes/Ember.ProxyMixin.html is marked as Private. Which I disagree it should be public, it's a powerful mixin.

**Comment by stefanpenner** [comment]
This appears to be an issue with jQuery's promises, where are just broken.

changing your code to first make RSVP (which is a well behaved promise library) wrap the jQuery one, appears to solve your issue.

```js
Ember.RSVP.Promise.resolve(Ember.$.getJSON("/endpoint")).then(....)
```
