### ISSUE TITLE
Ember.run.once running several times when method is a function

### ISSUE THREAD

**Issue by Leooo** [emberjs/ember.js#12369]
I'm not good for jsfiddles, but the below is pretty clear:

`````javascript````
export default Ember.Controller.extend({
  ..
  _test1: function(){
    var arr=[1,1,1,1,1,1,1,1,1];
    var self=this;
    arr.forEach(function(i){
      Ember.run.once(self,'_testlog');
    });
  },
  _testlog: function(){
    console.log("_testlog");
  },
  _test2: function(){
    var arr=[1,1,1,1,1,1,1,1,1];
    var self=this;
    arr.forEach(function(i){
      Ember.run.once(self,function(){
        this._testlog();
      });
    });
  },
});
`````

`````javascript
  test1() //=> "_teslog"
  test2() //=> "_teslog,_teslog,_teslog,_teslog,_teslog,_teslog,_teslog,_teslog,_teslog,_teslog,_teslog"
`````

So this behaviour is very confusing and doesn't fit with the docs: http://emberjs.com/api/classes/Ember.run.html#method_once

tested with Ember 1.12.1.

**note:** 
arr and the forEach loop have no impact here, I just created them to show a clear example

**note2:** 
if I want to use a function as a method for `````Ember.run.once`````, it is because I want to nest an `````Ember.run.next````` inside it without writing still another CP for the Ember.run.next: there is no `````Ember.run.onceNext````` method available, while I tend to use it everywhere in my app (this is different than ````Ember.run.scheduleOnce('destroy',..)````

**note3:**
I had the same kind of confusing behavior with store.filter, where if I remember well I had in that case to use a function for the method, and not a property string to make it work.

**Comment by stefanpenner** [comment]
When passing an anonymous function to once, it receives a nice function each time. This prevents the once check from being possible.

**Comment by Leooo** [comment]
That totally makes sense, but the docs should be updated.

**Comment by stefanpenner** [comment]
looks like the issue was introduced https://github.com/emberjs/website/commit/ddbc9bc047cba3f4648d708b3b8d45e9b08480f2

**Comment by stefanpenner** [comment]
opened an issue, with suggestions for the fix. https://github.com/emberjs/guides/issues/776

Maybe you have some free cycles to test your new undestanding of `once` and related functions. I can gladly give feedback on the submission

**Comment by stefanpenner** [comment]
Also for reference, the API docs are accurate: http://emberjs.com/api/classes/Ember.run.html#method_scheduleOnce

**Comment by stefanpenner** [comment]
extra comment to ensure no confusion i the API docs: https://github.com/emberjs/ember.js/pull/12373

**Comment by Leooo** [comment]
Thanks, in the API docs http://emberjs.com/api/classes/Ember.run.html#method_scheduleOnce I would have just replaced ````method Function | String ```` with ````method String````. For testing this, I would do it had I time for learning Ember (and Rails) testing framework and testing my own website first.. :( I know you are overburdened with everything, the day I am less suffocated I will certainly add my fork of EmberSync / LocalStorage adapter this may be useful to some (https://github.com/kurko/ember-localstorage-adapter/issues/105 is very big issue on LS I believe, especially for new guys who are testing Ember's performance wih the LS adapter).

**Comment by Leooo** [comment]
OK got it, sorry, the docs for http://emberjs.com/api/classes/Ember.run.html#method_scheduleOnce are correct and the anonymous function case is dealt with, unfortunately I was only looking at the doc for the .once function without checking scheduleOnce: http://emberjs.com/api/classes/Ember.run.html#method_once

So technically, the docs are correct.. Replacing ````method Function | String```` with ````method String```` in the .once function docs would have helped in my case.
