### ISSUE TITLE
"Error calling method on NPObject!" on Firefox

### ISSUE THREAD

**Issue by YoranBrondsema** [emberjs/ember.js#12364]
The monitoring system of our application has been reporting occasional errors `Error calling method on NPObject!`. The method is `symcBFPerformOnDOMChangedHandler`. This is an error message specific to Firefox so it only happens on that browser. It happens sporadically for some of our users and unfortunately I haven't been able to replicate it.

However, from the stack trace I did figure out that it comes from https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/location/history_location.js#L162, i.e. the line `get(this, 'history').replaceState(state, null, path);` of the file `history_location.js`. Firefox is exposing its window objects through `NPObject` interface, I'm assuming including `window.history`, so I'm not even sure if this is a bug in Ember.js or in Firefox itself.

Given how little information I have about the bug, I'm not sure how much this issue is worth. But I thought I'd post it anyway in the case someone else has encountered similar issues or knows more about it.

**Comment by stefanpenner** [comment]
My first inclination is that this sounds like a FF issue. Although as you mentioned, without further info. I don't know what we can do...

**Comment by zourtney** [comment]
Any luck pinning this down? I'm using a different tech stack, but experiencing the same symptoms.

In my case, it also seems related to `window.history` manipulation. Equivalent offending code, [*angular.js/browser.js#145*](https://github.com/angular/angular.js/blob/v1.4.7/src/ng/browser.js#L145):

```javascript
history[replace ? 'replaceState' : 'pushState'](state, '', url);
```

**Comment by YoranBrondsema** [comment]
I think the fact that it appears in Angular.js too indicates event more that it's a Firefox issue, like @stefanpenner suggests.

@zourtney can you easily reproduce it? I couldn't manage, it only appeared sporadically in our Sentry logs.

**Comment by zourtney** [comment]
@YoranBrondsema: I have reproduced it yet (but not for lack of trying). All reports are timestamped within a few seconds of a recorded hash change. I have reports of it happening both:

- on initial page load
- deep within the app runtime (different hash-page)

Also, I dug a little deeper and found similar reports triggered by Safari (and one labeled Android). These had no stack trace attached, so may be unrelated.

**Comment by stefanpenner** [comment]
My guess is that this is actually some native extension (like flash) crashing/causing grief.

Unfortunately, I don't believe this is something we can address on our side... If someone can demonstrate some further information we can re-investigate.

In the interim, I would recommend opening a firefox issue.
