### ISSUE TITLE
Docs for .@each and .[] are unclear about use-cases

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/ember.js#12360]
The [docs for `.@each` and `.[]` properties](http://emberjs.com/api/classes/Ember.Array.html#property__each) aren't clear that `.@each` should *never* be used as a terminal and `.[]` should *only* be used as a terminal.

See https://github.com/emberjs/ember.js/pull/11994#issuecomment-131879238

**Comment by stefanpenner** [comment]
:+1:

**Comment by kellyselden** [comment]
I have this bookmarked for whenever I need a reminder.

https://github.com/emberjs/ember.js/issues/2016#issuecomment-14402033

**Comment by pixelhandler** [comment]
@jamesarosen true that will be helpful to clarify :)

**Comment by rwjblue** [comment]
Closed by https://github.com/emberjs/ember.js/commit/e0e8f7feec456587ecfb13cce81fa3c99c6d8706, and a fix by @krisselden (which I can't find the link for ATM) that makes terminal @each expand to .[].
