### ISSUE TITLE
updated_at and created_at returns undefined

### ISSUE THREAD

**Issue by GCorbel** [emberjs/ember.js#12376]
In an Ember 2.0.0 app, I have this simple model : 

    export default DS.Model.extend
      date: DS.attr('string')
      updated_at: DS.attr('string')
      created_at: DS.attr('string')

And this route : 

    export default Ember.Route.extend
      model: (params) ->
        @store.find('trail', params.id).then (trail) ->
          console.log trail.get('date')
          console.log trail.get('updated_at')
          console.log trail.get('created_at')
        @store.find('trail', params.id)

Data returned by the server, in JSON API format, is : 

    {"data":{"id":"1","type":"trails","attributes":{"date":"2015-08-24T08:03:12.547Z","updated_at":"2015-08-24T08:03:12.547Z","created_at":"2015-08-24T08:03:12.547Z"}}}

When I go to the path, only `data` returns the value, other returns `undefined`. Are `created_at` and `updated_at` protected?

Thanks!

**Comment by Serabe** [comment]
Maybe this is a question for [emberjs/data](https://github.com/emberjs/data)

**Comment by stefanpenner** [comment]
Depending on your serializer. Those attributes may get camelized

But yes this is likely a question better asked on stackoverflow as it does not appear like a bug. But if it is a bug, on the ember/data repo

**Comment by wecc** [comment]
*I wrote this answer a couple of hours ago but forgot to press "Comment"*

@GCorbel The `JSONAPISerializer` defaults to dasherized attribute and relationship members.

You can use http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html#method_keyForAttribute and http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html#method_keyForRelationship to customize this behavior.
