### ISSUE TITLE
[feature request] Allow to pass computed property to Ember.on

### ISSUE THREAD

**Issue by Kuzirashi** [emberjs/ember.js#12379]
Hi, I know new syntax for firing observer on certain event (this is actually a workaround for issue below with cp):

~~~
 orderingObserver: Ember.on('init', Ember.observer('ordering', function() {
    console.log('Ordering Array Compute');
    let ordering = this.get('ordering');
    let array = [];
    if (ordering) {
    	array.push(ordering);
    }
    this.set('orderingArray', ordering);
  })),
sortedProducts: Ember.computed.sort('model.category.products', 'orderingArray')
~~~

But I've encountered situation where I would like to pass `Ember.computed` to `Ember.on` (intuitively) and I wish it would just work (`orderingArray` should be cp, compued on `init`):

~~~
orderingArray: Ember.on('init', Ember.computed('ordering', function() {
    console.log('Ordering Array Compute');
    let ordering = this.get('ordering');
    let array = [];
    if (ordering) {
    	array.push(ordering);
    }
    return ordering;
  })),
sortedProducts: Ember.computed.sort('model.category.products', 'orderingArray')
~~~

Very important part is `Ember.computed.sort('model.category.products', 'orderingArray')`, because I think it doesn't cause `orderingArray` property to be computed (I didn't have any logs of `Ordering Array Compute`) and I have to use:
a) observer and another property
b) computed property referenced somewhere else (template or code)

Simple twiddle: http://ember-twiddle.com/44a6310ed5d0cad4c83b.

**Comment by stefanpenner** [comment]
I would recommend just getting the computed property in `init`. No need to add the extra work that on requires and as a bonus. It works today

**Comment by Kuzirashi** [comment]
Yeah sure, but if `Ember.on` works with observer then maybe it could also work with cp? If it's not worth doing it then close this issue, but I think it would be like `syntactic sugar` or `intuitive` approach to that. Also, it wouldn't require to create another method for `init`. If it's just me under illusion it would be worth to have such behavior then I'll understand it should be closed.

**Comment by stefanpenner** [comment]
On init should actually be call on afterInit. As such it happens just after init, and changes within it broadcast unexpected and costly change events. When what one typically wants, is merely the initial state of the object to be primed a specific way. ( which is what init is for ). Also on init doesn't provide any ordering assurances, especially when inheritance is involved. Which can lead to some very tricky bugs, or hard to work around issues.

Using init is both less error prone, deterministic and and more performant.

Also, it's worth noting. Allowing cp to remain lazy is advantages, forcing them to eager compute is typically the result of some other anti patterns. Encouraging this behavior with sugar seems like a :footprints: :gun:

**Comment by Kuzirashi** [comment]
Understood, thanks for information.
