### ISSUE TITLE
Ember.computed.filterBy + Ember.computed.notEmpty breaks if I use the returned value in an observes() / bind it to the UI

### ISSUE THREAD

**Issue by djmitchella** [emberjs/ember.js#12380]
Summary: 
object A has a property 'value', and a 'hasValue' computed property calculated from 'value'.
object B has a list of A objects, and computed properties based on if each A 'hasValue' or not, using Ember.computed.filterBy and notEmpty.

If I make change to the A objects so that their 'hasValue' is true, then the first time I make the change, B's "anyHaveValue" property is set correctly.

 If I have an observer function also watching 'anyHaveValue' and that observer function calls .get("anyHaveValue"), then the second time I change the value of A (so that hasValue is still true), then B's anyHaveValue becomes false, when it should still be true.

 Removing this.get("anyHaveValue") from the observes() function makes the problem go away, though that doesn't help because in our app we bind UI to this property so we need to be able to have it evaluated when its dependencies change.

 It's difficult to explain purely in words, so here's code that reproduces it:

http://ember-twiddle.com/2621c293ca96819f6a1b

    var Item = Ember.Object.extend({
      value: 0,
      hasValue: Ember.computed.gte("value", 1)
    });
    
    var ItemList = Ember.Object.extend({
      items: [],
      itemsWithValue: Ember.computed.filterBy("items", "hasValue", true),
      anyHaveValue: Ember.computed.notEmpty("itemsWithValue"),
  
      showState: function() {
        // Comment out the next line, and things start to work properly
        console.log("anyHaveValue: " + this.get("anyHaveValue"));
      }.observes("anyHaveValue")
    });

    var row = ItemList.create();
    row.get("items").pushObject(Item.create());
    console.log(row.get("anyHaveValue")); // false, none of them do
    
    row.get("items")[0].set("value", 1);
    console.log(row.get("anyHaveValue")); // true
    
    row.get("items")[0].set("value", 2); 
    console.log(row.get("anyHaveValue")); // should still be true, but if we have the console.log() line in the observes() function, it now shows incorrectly as false.
    
    row.get("items")[0].set("value", 3); 
    console.log(row.get("anyHaveValue")); // should still be true, but remains broken 

Note: the original (more complex) code in our app worked properly in Ember 1.11 -- after upgrading to Ember 1.13.8, our app started failing, and after some investigation, the bug reduces to code like this.

**Comment by krisselden** [comment]
Since observers is synchronous, consuming CPs in them sets up race conditions between the cached value and the observer that gets installed to invalidate the cached value.  Observers in Ember are generally a low level primitive and you should only set flags and schedule work, the easiest way to use them would be to use Ember.run.once() which would schedule work one time asynchronously to 'recompute' the value.

Why it worked before was some very complex bookkeeping that still was not free of race conditions.  We have given up on trying to make this work, removed the complex code that was trying to make it work but only partially succeeding.  You simply cannot force CPs to recompute with complex dependency graphs synchronously.

**Comment by djmitchella** [comment]
Okay, I can live with having to wrap .observes() in Ember.run.once if they use computed properties, now I know that.

But it still seems like a bug that it can break the actual value of the property just by reading it in an observer, but maybe this just needs to be documented somewhere? Or should it be a runtime warning or something?

**Comment by Serabe** [comment]
In seems to work in 2.5.1 ([Twiddle](https://ember-twiddle.com/e52fd44b99355e078545cbe6073fb144?numColumns=2&openFiles=twiddle.json%2Capplication.controller.js)) and LTS ([Twiddle](https://ember-twiddle.com/f77493f67748bcb250bc1ecf1942ac78?numColumns=2&openFiles=twiddle.json%2Capplication.controller.js)).

Closing this as it seems to only affect 1.13. Feel free to reopen if you find a case that is not working in current versions.

Thank you!
