### ISSUE TITLE
Node version info is out of date at emberjs.com getting starting page

### ISSUE THREAD

**Issue by chuckAtWork** [emberjs/ember.js#12406]
At the emberjs getting starting page (http://guides.emberjs.com/v2.0.0/getting-started/) an older version of node (0.12.x) is recommended compared to the version recommended at the ember-cli getting start ed page (4.0.x - http://www.ember-cli.com/user-guide/#getting-started).

**Comment by rwjblue** [comment]
The current release of ember-cli issued a warning when using Node 4.x. We should wait to update the docs here until that warning is resolved in the release version.

**Comment by chuckAtWork** [comment]
I'm good with that. Thanks
