### ISSUE TITLE
Explicit Array(index) syntax doesn't work with HTMLBars each loops

### ISSUE THREAD

**Issue by jfelchner** [emberjs/ember.js#12400]
What I would expect in the following twiddle would be for `here is a bar` to be printed 2 times just as `here is a foo` is.  And in fact, this worked in a recent version of Ember (I think `1.9` but I could be wrong).

http://ember-twiddle.com/a1d02c1dc8877e222ab3

**Comment by stefanpenner** [comment]
Although surprising, this is how `forEach` in JavaScript works. It does not enumerate `holes` in sparse arrays.

`{{each` in JavaScript really just represents (and under the hood is implemented by) JavaScript `forEach`

**Comment by jfelchner** [comment]
@stefanpenner I think that's extremely weird behavior, but I also don't think you all should do something differently than what JS does.  It's just odd that it worked previously.

For any coming after I ended up doing `new Array(foo).fill(0)` to give me my desired behavior.

**Comment by jfelchner** [comment]
@stefanpenner FWIW, the underlying problem is that handlebars doesn't have simple iterators.  In my case I'm getting a rating from my API and want to use that as a count to output ratings stars.

All I really need in handlebars is:

```handlebars
{{#for foo as |count|}}
  do stuff
{{/for}}
```
