### ISSUE TITLE
Component's Scope In A Component Block Is Incorrect 

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#12409]
I believe the scoping of actions with curly components is incorrect on canary. The canary JSBin illustrates that when a component is yielded in a component block that scope is changed.

Canary 
http://jsbin.com/xetufateju/edit?html,css,js,console,output

Beta
http://emberjs.jsbin.com/noyawedime/1/edit?html,css,js,output

Release
http://emberjs.jsbin.com/cezumomapi/edit?html,css,js,output

/cc @wycats @chancancode

**Comment by rwjblue** [comment]
Thanks for reporting, this is definitely an issue with the recent removal of the `controller` and `view` template locals (done in https://github.com/emberjs/ember.js/pull/12286 around [here](https://github.com/emberjs/ember.js/pull/12286/files#diff-2e99cc34f27b19d8ea5a7ab96aa70938R16)).

Enabling those legacy flags does make this work properly (and is why the test suite passes).  Will dig into it a bit more tonight...

**Comment by rwjblue** [comment]
Issue is with the [`@element_action` keyword](https://github.com/emberjs/ember.js/blob/e88eee778ee1a4c4319bf091dd6785023b868c63/packages/ember-routing-htmlbars/lib/keywords/element-action.js#L35) using `scope.getLocal('controller')`.

**Comment by rwjblue** [comment]
Created failing test in: https://github.com/emberjs/ember.js/compare/master...rwjblue:action-scoping.  Working on fix tonight....

**Comment by rwjblue** [comment]
Submitted https://github.com/emberjs/ember.js/pull/12416 with a potential solution...
