### ISSUE TITLE
Ember.isEmpty returns false when passing an empty string

### ISSUE THREAD

**Issue by jpoiri** [emberjs/ember.js#12405]
Hi,

I am using Ember 1.13.10 and Ember.isEmpty is returning false when I am passing an empty string

**Comment by rlivsey** [comment]
Are you sure it's an empty string and there's no hidden whitespace in there?

A quick [test on Ember Fiddle](http://ember-twiddle.com/dfb31c52a013f35d1e67) shows that `isEmpty` reports as true for `""` in 1.13.10.

**Comment by rwjblue** [comment]
Hmm, seems like we have a test specifically for this [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/tests/is_empty_test.js#L16) and that test is passing on the release-1-13 branch. 

Can you provide a JSBin showing the issue so we can track down what is going on?

**Comment by jpoiri** [comment]
Here's the code I have. The avatar_url is coming from the API as blank because when I do Ember.isBlank is returns true but if I check if its empty returns false.


/**
 * This model represents a league in momentum.
 */
export default DS.Model.extend(EmberValidations, {

    admins: DS.hasMany('user', {async: true}),
    max_team_size: DS.attr('number'),
    steps_per_point: DS.attr('number'),
    name_en:  DS.attr('string'),
	name_fr: DS.attr('string'),
    description_en: DS.attr('string'),
    description_fr: DS.attr('string'),
	slogan_en: DS.attr('string'),
	slogan_fr: DS.attr('string'),
    lingual: DS.attr('string'),
    avatar_url: DS.attr('string'), //blank string
    benefit: DS.belongsTo('benefit', {async: true}),

	/**
	 * Returns the avatar absolute url.
	 * @return {string}
	 */
	avatarAbsoluteUrl: Ember.computed('avatar_url', function() {
		let relativeUrl = this.get('avatar_url'), absoluteUrl = null;

               Ember.isBlank(relativeUrl) // returns true
 
		if (!Ember.isEmpty(relativeUrl)) { // returns false
			absoluteUrl = ENV.APP.BASE_AVATAR_DOWNLOAD_URL + this.get('avatar_url');
		}
		return absoluteUrl;
	}),

**Comment by rlivsey** [comment]
@jpoiri I'm going to guess that it's not an empty string, but a string containing just whitespace.

`isBlank` returns true if a string contains just whitespace, whereas `isEmpty` will only return true for a string if it has no content at all. In fact, [isBlank is simply isEmpty with a check for whitespace](https://github.com/emberjs/ember.js/blob/v2.0.1/packages/ember-metal/lib/is_blank.js#L28).

```javascript
// with just whitespace
Ember.isBlank(' '); // true
Ember.isEmpty(' '); // false

// with a completely blank string
Ember.isBlank(''); // true
Ember.isEmpty(''); // true
```

**Comment by jpoiri** [comment]
Ok thanks for the clarification
