### ISSUE TITLE
Binding to "size" fails

### ISSUE THREAD

**Issue by srsgores** [emberjs/ember.js#12413]
[jsbin here](http://emberjs.jsbin.com/todeqe/edit?html,css,js,output)

Try deleting the entire username, and you will see the error:

> Uncaught IndexSizeError: Failed to set the 'size' property on 'HTMLInputElement': The value provided is 0, which is an invalid size.

But this shouldn't occur, because the component passes in "auto", which [according to this post](http://stackoverflow.com/questions/27512073/remove-size-attribute-from-html-input), is a valid ``value`` for ``size``.

``document.getElementById("email").setAttribute("size", "auto")`` works, but the equivalent in the component does not.

**Comment by archit** [comment]
@srsgores seems like internally Ember uses `element[name] = value` instead of `element.setAttribute(name, value)`. No idea, why it does so.

**Comment by srsgores** [comment]
Still doesn't explain how ``"auto"`` is getting converted to ``0``...

**Comment by gordonkristan** [comment]
As far as I can tell based on the [MDN article](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) and the [W3 DOM documentation](http://www.w3.org/2003/01/dom2-javadoc/org/w3c/dom/html2/HTMLInputElement.html), `auto` is not a valid value for the `size` attribute. My guess is that `setAttribute()` does some kind of coercion that the `size` setter doesn't do.

**Comment by locks** [comment]
I am closing this issue as the previous comment seems to resolve the issue.
Feel free to re-open the issue if you think it's still justified, thank you!
