### ISSUE TITLE
Inconsistent behavior with transitioning to error substates

### ISSUE THREAD

**Issue by aquamme** [emberjs/ember.js#12424]
There appear to be some inconsistencies with the treatment of error substates. Assume the following route structure:

```
App.Router.map(function() {
  this.route('search', function () {
    this.route('results');    
  });
});
```

These oddities arise when attempting to link-to or transitionTo an error substate, or redirect to one during a transition.

#### link-to and transitionTo behavior

```
// app/templates/index.hbs

{{!-- this link-to can be created but the target is 
    '_unused_dummy_error_path_route_application/undefined' --}}
{{#link-to 'error'}}error{{/link-to}} 

{{!-- this route can't be link-to'd without an error being thrown when
     the app loads (though it appears in the ember inspector)--}}
{{#link-to 'search.error'}}search.error{{/link-to}}
```
Linking directly to error substates from the template is probably not a useful feature and likely isn't supposed to work. However, Ember will create a nonfunctional link to the 'error' substate if you ask it to. If you attempt to create a link to a non-toplevel error route, Ember will throw the error `Uncaught TypeError: Cannot read property 'shouldSupercede' of undefined`. If links to error substates aren't allowed, it would be good to throw an error that indicates that. 

This same behavior is exhibited when attempting to transition using `transitionTo`. For this case, I think it makes sense to allow manual transitions to error substates. For instance:

```
// app/routes/search.js
...
actions: {
  submit (params) {
    if (!params.areCorrect) {
      this.transitionTo('search.error');
    }
  }
},
...
```

#### redirecting during a transition
There is some strange behavior that happens when attempting to manually redirect to an error substate during a transition. Example:

```
// app/routes/search/new.js
...
  beforeModel: function (transition) {
    // ends up going to 'search', not 'error'
    //return this.transitionTo('error');
    
    // ends up going to 'search.results', not 'search.error'
    //return this.transitionTo('search.error');   
  },
...
```

You may wonder why the a developer would want to redirect to error substates directly with `transitionTo` instead of just returning a rejected promise as described in the guides. There is, however, a use case for it.

Ember provides only indirect control over which error substate is loaded when a promise is rejected. E.g. if a promise is rejected from the beforeModel/afterModel/model hook in the 'search.new' route and there is a 'search.error' template, the 'search.error' route will always be entered - there is no way to load the 'error' route instead via promise rejection if that happens to be desired for a particular failure state. For that reason allowing manual redirection during transitions is a useful feature.

Here's a [jsbin](http://emberjs.jsbin.com/qihogijobi/edit?html,js,output) that shows the behavior I've described above.

**Comment by pixelhandler** [comment]
@aquamme It does seem that the documentation for errors states indicates those states are intended to support failed promises. Which also indirectly suggests not being used to explicitly transition to the error state either in template code or via transitionTo.

> attempting to link-to or transitionTo an error substate, or redirect to one during a transition.

In my opinion the above is not necessarily the happy path for using the error states of a route.

> If links to error substates aren't allowed, it would be good to throw an error that indicates that.

That may be the case here. 

As an alternative to the jsbin implementation for error handling that you provided…

Since there is not any specific documentation of how to explicitly transition to the (promise failure) error states in routes, you may want to define your own routes for error pages. For example, your router may define a `not-found` page and in an error state of another route you could transition to the `not-found` route, or in your code could transition to that route (including with link-to).

**Comment by aquamme** [comment]
> Which also indirectly suggests not being used to explicitly transition to the error state either in template code or via transitionTo.
If there was an indirect suggestion, I didn't notice. :smiley:

I discovered that error substates can be transitioned to if a model is provided. E.g.

```
// app/routes/search.js
...
actions: {
  submit (params) {
    if (!params.areCorrect) {
      this.transitionTo('search.error', 'params aren't correct!');
    }
  }
},
...
```
This also works with the link-to helper. [Here is an updated jsbin](http://emberjs.jsbin.com/nolabuwine/edit?html,js,output) with examples of this behavior.

If manual transitions to error substates is intended as a feature:
- A descriptive error should be thrown if a model is not included when attempting to transition/link to an error substate, or a model should be optional

If manual transitions should be disallowed:
- A descriptive error should be thrown if an error substate is manually transitioned/linked to

Either way, I think it'd be good to update the guides to document this. I'd be glad to submit a PR once the correct behavior is determined.

> As an alternative to the jsbin implementation for error handling that you provided…

I did implement that as a workaround, but it has a drawback - the URL is updated to reflect the transition to the error route. If the user refreshes, they're being shown an error that may no longer be relevant. Using the built in error substate instead would mean that the user could refresh and be brought back to the last known good position in the application flow, at which point they can try again.

**Comment by rwjblue** [comment]
> I did implement that as a workaround, but it has a drawback - the URL is updated to reflect the transition to the error route.

To avoid this drawback, you should use `this.intermediateTransitionTo` instead of `this.transitionTo` in the route. 

I'm happy to have follow up discussions in emberjs/guides RE: better docs around substates, but I'm going to go ahead and close this for now..
