### ISSUE TITLE
[DOC beta] Deprecate and Warn Handlers

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#12428]
* [x] Requires API documentation for `Ember.Debug.registerDeprecationHandler`
* [x] Requires API documentation for `Ember.Debug.registerWarnHandler`
* [x] Guides should be reviewed.
* @rwjblue it seems reasonable to add a guide for the upgrade workflow now that this is in Ember proper. However I'm not interested in blocking on that.

The [2.1 beta blog post](http://emberjs.com/blog/2015/08/16/ember-2-1-beta-released.html#toc_deprecate-and-warn-handlers) is the best resource for this, along with the [RFC](https://github.com/emberjs/rfcs/blob/master/text/0065-deprecation-warning-handlers.md) and [implementation PR](https://github.com/emberjs/ember.js/pull/11833).

**Comment by toddjordan** [comment]
I have some bandwidth amidst the North Carolina rain this weekend 🚣I'll work on it.

**Comment by rwjblue** [comment]
Awesome, thank you! Please feel free to ping me here or in slack if you have any questions...

**Comment by toddjordan** [comment]
I've got this in progress, and hope to have a PR by end of day tomorrow.  I'm planning on an Ember.Debug class doc with explanations for each new function, something like this: 

![image](https://cloud.githubusercontent.com/assets/3609063/10265222/7904e45c-69f5-11e5-8e0a-b3ed88a467a4.png)

**Comment by rwjblue** [comment]
Sounds great!

**Comment by rwjblue** [comment]
API docs are added for the new handlers, and deprecation guides have been added for the new properties required for `Ember.deprecate` and friends.

I reviewed the guides repo for any usage of `Ember.deprecate` or `Ember.warn` and there were none. The Ember Inspector section talks about deprecations linking back to the deprecation guide, but I think that is still perfectly correct.

---

@mixonic - We should add an issue in the guides repo for fleshing out the process of tackling deprecations.

**Comment by rwjblue** [comment]
@mixonic - I *think* this issue is resolved, please confirm/close if you agree.

**Comment by mixonic** [comment]
@toddjordan Thanks so much for the hand this weekend :-) I really, really appreciate you having our back.

**Comment by toddjordan** [comment]
Happy to help 👍
