### ISSUE TITLE
Initial load of app will not work with Ember Inspector open w/ Ember 2.1

### ISSUE THREAD

**Issue by bttf** [emberjs/ember.js#12439]
Having Ember Inspector (v1.9.2) open while initial load of Ember v2.1 app will cause the app to not fully load (white screen of death; error-less).

Doing a hard refresh of the app with Ember Inspector open will also produce same results.

Closing Ember Inspector and refreshing will allow the app to load again.

**Comment by rwjblue** [comment]
Thank you for reporting!  I will try to dig in tonight...

**Comment by rwjblue** [comment]
Likely the same issue as https://github.com/emberjs/ember-inspector/issues/461 and https://github.com/emberjs/ember-inspector/issues/478.
