### ISSUE TITLE
Uncaught TypeError: Cannot read property 'reopen' of undefined

### ISSUE THREAD

**Issue by morgaan** [emberjs/ember.js#12437]
Just updated from 2.0.2 to 2.1.0 and get this TypeError at ember-template-compiler.js:7821

I downgrade then back to the 2.0.2 for the moment then. Just wanted to let you know

Cheers,

morgan

**Comment by rwjblue** [comment]
Can you please share a reproduction or more info on how to reproduce?

**Comment by morgaan** [comment]
Thank you for answering. Here it is:

I grabbed the following file from the [Ember.js Builds page] (http://emberjs.com/builds/#/release):

* ember-template-compiler.js
* ember.debug.js
* ember-data.min.js

I called them in this exact same order in the markup. The rest of the JS below is in the index.html but called in the markup after the three scripts above.

I do not use the Ember-CLI but more the Starter-Kit way.

I stripped down my code to the following minimum and still get this error:

    <main id="content">
    
      <script type="text/x-handlebars">
        <h2>Welcome to Ember.js</h2>
        {{outlet}}
      </script>

    </main>

    <script>
 /* APP
   ========================================================================== */


    App = Ember.Application.create({
      // Basic logging, e.g. "Transitioned into 'post'"
      LOG_TRANSITIONS: true,

      // Where we append the ClaimCheck app.
      rootElement: '#content',


    });




  /* ROUTER
     ========================================================================== */


    App.Router = Ember.Router.extend({
      rootURL: '/entschaedigung-pruefen-neu/'
    });

    App.Router.map(function() {
    });





  /* ROUTES
     ========================================================================== */

    App.IndexRoute = Ember.Route.extend({
      model: function() {
        return ['red', 'yellow', 'blue', 'brown'];
      }
    });

    </script>

Then I call the rootURL and get the error.

Hopefully this is enough to help you solve this issue.

Cheers,

morgan

**Comment by pixelhandler** [comment]
@morgaan this is not a bug in Ember. It may be a good idea to start using Ember CLI as soon as you can. 

I created a jsbin to show how to setup the #content element as well as reopen the App.Router to set the rootURL, see - http://emberjs.jsbin.com/pokugo/edit?html,js,output

**Comment by morgaan** [comment]
Hi,

Thank you for you feed back. After struggling a bit as a newbie, I came across the awesome resource that the Rock And Roll with Ember.js book is. And as in the book now I'm using the Ember CLI and loving it :)

Cheers,

morgan

**Comment by aertmann** [comment]
had the same issue, turned out I forgot to update ``ember-template-compiler.js`` to the matching version (only updated the ember lib)

so this issue can probably be closed?
