### ISSUE TITLE
Ember model with a property named "type" is wrongly mapped

### ISSUE THREAD

**Issue by fabienbk** [emberjs/ember.js#12446]
This only happens when the property value is equal to another Model name.

Example:

    MyApp.Foo = DS.Model.extend({
	    type: DS.attr('string')
        ...
    }

    MyApp.Bar = DS.Model.extend({
	    type: DS.attr('string')
        ...
    }

And Given this JSON:

    foo : {
        ...
        type : 'BAR'
        ...
    }
      

Ember Data seems to be confused and won't map correctly the Foo instance. All other fields except the id will be null. 

Renaming the property to something else will fix the problem.

Apologies if it's already logged/documented.

PS: tested on Ember 2.0.2.

**Comment by stefanpenner** [comment]
i believe this may be better opened on the ember-data repo github.com/ember/data

**Comment by fabienbk** [comment]
Oh, my bad.

**Comment by stefanpenner** [comment]
@fabienbk no problem, where 1 project starts and the other ends isn't always obvious
