### ISSUE TITLE
New computed property Getter/Setter is invalid in ember-cli Uglify

### ISSUE THREAD

**Issue by danshapir** [emberjs/ember.js#12447]
Hey, 

using the object literal shorthands isn't supported and doesn't work.

```javascript
prope: Ember.computed('title', {
get(key): {
return key;
}
}),
```

Leads to this:
Build failed.
File: assets/vendor.js (87231:13)
Unexpected token punc «)», expected punc «(»

and you've got to change it to:
```javascript
prope: Ember.computed('title', {
get: function(key): {
return key;
}
}),
```

**Comment by stefanpenner** [comment]
> prope: Ember.computed('title', {
> get(key): {
> return key;
> }
> }),

this isn't valid syntax.

you must either:

`get: function() { ...`
or
`get() { }`

**Comment by danshapir** [comment]
Ohh shame I can't do a :+1:  here ;-)

Note to self, don't try to figure out errors after 15H of work. Haha

Thanks and sorry :)

**Comment by stefanpenner** [comment]
> Note to self, don't try to figure out errors after 15H of work

not without a beer!
