### ISSUE TITLE
computed.filter no longer works ( > 2.0) when wrapped with .property()

### ISSUE THREAD

**Issue by Kilowhisky** [emberjs/ember.js#12453]
In previous versions of Ember when you needed a `Ember.computed.filter` property to recompute based on a second dependent key all you had to do was wrap the filter in a `.property()` like so: 

```
  filterStartRange: 0,
  filterStopRange: 5000,
  filterRecomputed: 0,
  filtered: Ember.computed.filter('model', function(item) {
     this.incrementProperty('filterRecomputed');
     return item.id > this.get('filterStartRange') && item.id < this.get('filterStopRange');
  }).property('model','filterStartRange','filterStopRange')
```

With this structure the behavior previously was this.
1. if new records were added to `model` the filter would only run for that new record. 
2. If the `filterStartRange`, or `filterStopRange` were modified then the entire filter would re-run. 

In ember > 2.0 wrapping the filter in a `.property()` breaks behavior # 1 as i described above.  If any additions occur the filter does not run for that new record and the UI is never updated to show the addition of that record. 

Now in both versions of ember you could have just changed the `.property()` to be this.
```
.property('model.[]','filterStartRange','filterStopRange')
```
And it would recompute if new additions were made to the `model` but this technique has a massive flaw. When an addition is made to the `model` the entire filter is re-run. Which if you happen to have a list that is constantly being added to can cause some serious performance problems. 

Here is a twindle showing the issue:  http://ember-twiddle.com/f5b3a5f20af5a825e684?numColumns=1

To replicate it in the twindle play around with the start and stop index to see that the filter is recomputing. Then try and add an item and see that the filter is not run again.

**Comment by stefanpenner** [comment]
What you describe seems to be working as expected

**Comment by Kilowhisky** [comment]
Ember twindle appears to be using ember 1.13.9 which worked this feature worked properly in. I'm not sure how to get twindle to use ember > 2.0

**Comment by Kilowhisky** [comment]
Looks like i manage to get it to use Ember 2.0 and now its showing the issue. Here is the updated twindle. Sorry for the stupidity on my part. 

http://ember-twiddle.com/f5b3a5f20af5a825e684?numColumns=1

**Comment by stefanpenner** [comment]
@Kilowhisky just minor pedantic correction, its `twiddle` not `twindle`.

**Comment by stefanpenner** [comment]
`.property('model.[]','filterStartRange','filterStopRange')`

**Comment by stefanpenner** [comment]
> 1. if new records were added to model the filter would only run for that new record.

This functionality is no longer part of these macros.

**Comment by Kilowhisky** [comment]
Oh.... i thought it was just the `store.filter` that was removed.

Does this mean `addArrayObserver` is no longer supported either in ember 2.0? 
http://emberjs.com/api/classes/Ember.MutableArray.html#method_addArrayObserver

I'm wondering what an acceptable replacement is then for actively filtering an array...

**Comment by stefanpenner** [comment]
> Does this mean addArrayObserver is no longer supported either in ember 2.0?

nope it is still there.



> Oh.... i thought it was just the store.filter that was removed.

computed.filter is still around, although its performance characteristics a different. Likely not as good in some very large lists, but much better in other scenarios.

This does not appear to be a bug report, I would like to recommend posting to stackoverflow, and cross linking here.
