### ISSUE TITLE
Component layout problem

### ISSUE THREAD

**Issue by vvsalmin** [emberjs/ember.js#12467]
I cannot get this to work: http://emberjs.com/deprecations/v2.x/#toc_ember-component-defaultlayout

http://ember-twiddle.com/40bf89888d33cc554671

Overwriting component's layout property doesn't seem to do anything with ember 2.1.

```
import Ember from 'ember';
import layout from '../templates/test';

export default Ember.Component.extend({
  
  layout: layout
  
});
```

**Comment by pixelhandler** [comment]
@vvsalmin yes this seems like a bug, It's working in 2.0.2 - http://ember-twiddle.com/badb828f14ae2c726bb1

**Comment by pixelhandler** [comment]
@vvsalmin I guess there was some chat last week in Slack, @rwjblue had some ideas about determining which behavior is actually the correct and desired behavior.

**Comment by vvsalmin** [comment]
thanks for the answer.. I found a work-a-round from slack and extended the component rather than using dynamic template. 

But I think that this issue is still a bug...

**Comment by vitch** [comment]
I've just run into this issue. 

In an older version of ember I was dynamically creating a template string, compiling it and setting it to the `layout` property in my Component's `init` function. 

My use case is a workaround until we get splat params in handlebars (see [here](https://github.com/wycats/handlebars.js/pull/1149)) - basically I need to invoke dynamic components with dynamic arguments e.g. given

```js
{
  componentName: 'x-foo',
  params: [
    bar: 'data.bar',
    bing: 'data.bing',
  ]
}
```

I would want to render as if the template was:

```handlebars
{{x-foo bar=data.bar bing=data.bing}}
```

Additionally I need to be able to render:

```js
{
  componentName: 'x-foo',
  params: [
    bar: 'data.bar',
    bing: 'data.bing',
  ],
  yield: '<p>Some stuff</p>'
}
```

As:

```handlebars
{{#x-foo bar=data.bar bing=data.bing}}<p>Some stuff<p>{{/x-foo}}
```

Is this use-case supported? Is the fact that `layout` doesn't do anything considered a bug? It is documented to work...

**Comment by rwjblue** [comment]
The example Twiddle doesn't demonstrate the issue any longer (seems like it was updated at some point), but if a template is resolved for a given component's layout it will always override whatever `layout` property you define.

**Comment by vitch** [comment]
My bad - here's an updated twiddle which shows that `layout` does work:

https://ember-twiddle.com/6c21bc10e1647197e0e2

I didn't get from the documentation that having a `template.hbs` in your component's folder would stop the `layout` property from working...

Also, the default blueprints add `import layout from './template';` which is unnecessary and probably added to my confusion (using pods in case that makes any difference).

**Comment by rwjblue** [comment]
The default blueprint for addons does the `import` and assign thing because the resolver will not find the layout from within the `addon/` dir of the addon.

**Comment by vitch** [comment]
Thanks for the clarification. 

I think this ticket can be closed because my twiddle demonstrates that what the original poster asked about is working...

**Comment by rwjblue** [comment]
Thanks @vitch
