### ISSUE TITLE
Can't Replace hasMany Relationship

### ISSUE THREAD

**Issue by IsaiahJTurner** [emberjs/ember.js#12461]
Doing something like: 
`ama.set("questions", [Question, Question, Question]);`
does not work.

**Comment by stefanpenner** [comment]
i suspect this may be related to ember-data and as such should likely be an issue posted [here](github.com/emberjs/data)

**Comment by IsaiahJTurner** [comment]
New issue: https://github.com/emberjs/data/issues/3833
