### ISSUE TITLE
Namespace vs component name hyphenation rule

### ISSUE THREAD

**Issue by trentmwillis** [emberjs/ember.js#12466]
Currently, [the check for hyphenation](https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/system/lookup-helper.js#L9-L11) in component names is fairly dumb. This means you can skirt the rules by defining a component that does not have a nested name if it lives in a namespace that contains a hyphen. For example, the component `form-inputs/select` is completely valid.

I'm not sure if this is intended to be a feature or not, but my understanding is that component names themselves are meant to be hyphenated, and not just their namespace. If that is the case, this should probably be improved.

[Here's an example JSBin](http://emberjs.jsbin.com/pifijumefo/1/edit?html,js,output).

cc: @nathanhammond

**Comment by stefanpenner** [comment]
Yes, dash after the last slash is likely the path we should take. Also, this was he original idea, but when `/` was enabled the corresponding check was not strengthened.

As you have identified the component name before the last `/` is likely to be considered purely a namespace of sorts.

Unfortunately, I suspect this would be a breaking change. But potentially worth warning/deprecating on?

@wycats @rwjblue @ef4 this is related to our component & pods story, your input would be appreciated.

**Comment by trentmwillis** [comment]
For what it is worth, I think it would be good to tighten up the behavior over a deprecation period (I can make the changes needed). Also, another side effect of the current check is that `-thing` or `thing-` can also be valid components.

**Comment by locks** [comment]
@wycats @rwjblue @ef4 poke

@trentmwillis `thing-` is fine, `-thing` isn't. see https://mothereff.in/custom-element-name

**Comment by williamweckl** [comment]
+1

**Comment by locks** [comment]
This discussion needs to be re-contextualized for a Module Unification universe.
Closing it for now!
