### ISSUE TITLE
'application.currentRouteName' doesn't change when switching routes.

### ISSUE THREAD

**Issue by Vatosteve** [emberjs/ember.js#12469]
It appears to be stuck in the first route it comes across, which is name the loading route I have setup. This was working with Ember 1.13, but not the currentRouteName appears to be stuck.

This also seems to be causing trouble with the link-to component not setting 'active' to the current page it is on.

I turned on LOG_TRANSITIONS and all transitions complete without error.

**Comment by pixelhandler** [comment]
@Vatosteve would you mind creating a working example using http://ember-twiddle.com ?

**Comment by pixelhandler** [comment]
@Vatosteve can you provide some steps to reproduce the issue or a code example to demonstrate the issue?

**Comment by Vatosteve** [comment]
PEBCAK error. Didn't include this._super(...arguments); on didTransition()
