### ISSUE TITLE
Ember.String underscore returns bad result

### ISSUE THREAD

**Issue by SeyZ** [emberjs/ember.js#12460]
I'm passing the string `justAQuestion` to `Ember.String undercore`:

- Current result: `just_aquestion`
- Expected result: `just_a_question`

Here's the JSBin to reproduce the problem:

http://emberjs.jsbin.com/tudepeceli/edit?html,js,output

**Comment by duggiefresh** [comment]
http://emberjs.com/api/classes/Ember.String.html#method_underscore

Seems that it is working as expected (note the example with `innerHTML`). You may have to write a custom method yourself.

**Comment by SeyZ** [comment]
@duggiefresh It works with all examples described in the doc. But my usecase does not work well :(

**Comment by stefanpenner** [comment]
I am inclined to think this is a bug.

I would expect the following:
`"justAQuestion".underscore()` => `"just_a_question"`
`"justAAQuestion".underscore()` => `"just_aa_question"`

This ensures funky acronyms work like `"innerHTML".underscore()` becomes `"inner_html"`

**Comment by rwjblue** [comment]
@stefanpenner - Seems ok to me, but means that initialisms must be greater than 2 chars or they get split via underscore.  Most common example where that might be an issue is with `Ember.String.underscore('CC')` (today this returns `cc`, but with your suggestion I would expect it to return `c_c`).

**Comment by stefanpenner** [comment]
> but with your suggestion I would expect it to return c_c

with my suggestion it should be `cc`

**Comment by josenberg** [comment]
Rails have some problems with `underscore` too. 
I personally prefer the version of ember's underscore.
```
// Rails
underscore 'HTTPS'           # => 'http_s'
// Ember
'HTTPS'.underscore()        > 'https'
```
(http://api.rubyonrails.org/classes/ActiveSupport/Inflector/Inflections.html#method-i-acronym)

**Comment by stefanpenner** [comment]
> underscore 'HTTPS'           # => 'http_s'

that is strange... i dislike that :P

**Comment by bcardarella** [comment]
@stefanpenner are you suggesting a special case being made for "A"?

**Comment by rlivsey** [comment]
@bcardarella I think @stefanpenner is proposing that underscores should only occur on case changes, there are no changes in HTTPS so "HTTPS".underscore() should -> "https", whereas "HTTPs".underscore() would => "http_s"

**Comment by rwjblue** [comment]
I'm unsure that we can make a change here that would make everyone happy (and not break things). I am also unsure of the specific proposed change (though what @rlivsey said sounded pretty good), and I think it may warrant a specific RFC to walk through the various permutations...

**Comment by bcardarella** [comment]
How about passing an optional parser so you can customize the strategy?

On Sunday, October 11, 2015, Robert Jackson <notifications@github.com>
wrote:

> I'm unsure that we can make a change here that would make everyone happy
> (and not break things). I am also unsure of the specific proposed change
> (though what @rlivsey <https://github.com/rlivsey> said sounded pretty
> good), and I think it may warrant a specific RFC to walk through the
> various permutations...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emberjs/ember.js/issues/12460#issuecomment-147249357>.
>


-- 

----------------------
Brian Cardarella
CEO of DockYard
Visit us: http://dockyard.com
Call us: (855) DOCK-YRD
Follow me on Twitter: http://twitter.com/bcardarella
Follow us on Twitter: http://twitter.com/DockYard

**Comment by Serabe** [comment]
I close this issue. Feel free to reopen or submit an RFC if you want to further discuss this.

Thank you!
