### ISSUE TITLE
AdapterError persisting despite route error-hook treatment

### ISSUE THREAD

**Issue by samcic** [emberjs/ember.js#12472]
Here are two JSbins:

http://emberjs.jsbin.com/qilozufiwa/1/edit?html,js,console,output
http://emberjs.jsbin.com/panodeneja/edit?html,js,console,output

Both are identical, except that the first uses Ember Data 2.0 and Ember 2.0, and the second uses Ember Data 2.1 and Ember 2.1.

Both just represent an app which enters a route 'Testroute' and tries to get a 'Testmodel' record as its model. The adapter fails to get this record, rejecting the promise with an AdapterError. Back in the route, we handle the error by transitioning to the 'servererror' route.

Although both versions successfully transition to the 'servererror' route, in the second (Ember(-data) 2.1) we see an error in the console.

This error-reporting/persistence in 2.1 seems to be breaking some of our tests. Is anybody able to comment on whether this is a regression, or if there's something wrong with the error handling on the route in the JSBin, or if dumping to the console is now expected?

**Comment by pixelhandler** [comment]
@samcic have you asked this question in the http://embercommunity.slack.com #ember-data channel?

**Comment by swalkinshaw** [comment]
Just wanted to add that we're experiencing the same behaviour and bug.

It also appears this has been reported before: https://github.com/emberjs/ember.js/issues/12166 (point #3 and this [comment](https://github.com/emberjs/ember.js/issues/12166#issuecomment-148391750) by @rwjblue).
