### ISSUE TITLE
Add options object to deprecate calls where its missing in 1.13

### ISSUE THREAD

**Issue by toddjordan** [emberjs/ember.js#12478]
My app is on 1.13.10, and I'm working on eliminating deprecations that are going end of life in 2.0.  I'm using ember-debug-handlers-polyfill to filter out anything not 2.0 and I'm noticing there are some depcrecations that do not provide options or until properties.  I'm going to list these here and go one by one and fix by adding options to these. 

ember-views/lib/views/view.js line 1356, 
```
Ember.deprecate(`A property of ${this} was modified inside the ${this._dispatching} hook. You should never change properties on components, services or models during ${this._dispatching} because it causes significant performance degradation.`, !this._dispatching);
```
line 1350, 
```
Ember.deprecate(`You modified ${label} twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0`);
```
1348
```
Ember.deprecate(`You manually rerendered ${label} (a parent component) from a child component during the rendering process. This rarely worked in Ember 1.x and will be removed in Ember 2.0`);
```

ember-views/lib/views/component.js line 160
```
Ember.deprecate(`Accessing 'template' in ${this} is deprecated. To determine if a block was specified to ${this} please use '{{#if hasBlock}}' in the components layout.`);
```

ember-application/lib/utils/validate-type.js line 23
```
Ember.deprecate(
      `In Ember 2.0 ${parsedName.type} factories must have an \`${factoryFlag}\` ` +
      `property set to true. You registered ${resolvedType} as a ${parsedName.type} ` +
      `factory. Either add the \`${factoryFlag}\` property to this factory or ` +
      `extend from ${expectedType}.`,
      resolvedType[factoryFlag]
);
```

container/lib/registry.js line 189
```
Ember.deprecate('`lookup` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container.', false, { url: "http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers" });
```
line 199
```
Ember.deprecate('`lookupFactory` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container.', false, { url: "http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers" });
```

ember-runtime/lib/controllers/object_controller.js line 31
```
Ember.deprecate(objectControllerDeprecation, this.isGenerated);
```

**Comment by rwjblue** [comment]
If you want to do the work of backporting these `id` / `until` values to 1.13, I will gladly merge, but `ember-cli-deprecation-workflow` does provide a way to match these (via `matchMessage: /Some RegExp/`).

**Comment by toddjordan** [comment]
So I would still have to figure out the untils for each and add them to the matchMessages?

**Comment by toddjordan** [comment]
@rwjblue I guess it depends on how many are out there.  If you think there are a ton more, then yeah maybe the workflow will be faster for me.  Otherwise I can fix these up pretty quick once I figure out when they go away

**Comment by toddjordan** [comment]
I got ambitious today so I did both: fixed up the un-optioned deprecations I was seeing, and started using ember-cli-deprecation workflow.

**Comment by mixonic** [comment]
closed in https://github.com/emberjs/ember.js/pull/12481
