### ISSUE TITLE
How to use hook such as didInsertElement

### ISSUE THREAD

**Issue by long800110** [emberjs/ember.js#12476]
When i used emberjs which version less than 1.13, i used some hook such as `didInsertElement()` in the `View`, but so far `View` function had been removed in Ember 2.0, what a solution to instead of it.
Thanks.

**Comment by stefanpenner** [comment]
didInsertElement hook continues to exist in components, you should be able to use them as before.

Please note, Q/A is better directed to Stackoverflow. As it is a better venue for such discussions, and we would like to keep the issue tracker focused on bug reports.
