### ISSUE TITLE
Helpers properties meta

### ISSUE THREAD

**Issue by g13013** [emberjs/ember.js#12474]
The meta information for a helper's properties was quite helpful in my case ! I wonder why they have been removed ! In my case many helpers that I wrote for my application are using the meta information to extract the key that was used, not the resolved value of that key

so my question is, is there a workaround ?

**Comment by pixelhandler** [comment]
@g13013 do you know of a link to the docs that shows the meta property of a help was public API?

**Comment by pixelhandler** [comment]
@g13013 have raised your question in the embercommunity.slack.com #needHelp channel?

**Comment by stefanpenner** [comment]
If i am understanding this correctly, this information was not public. It may be good to demonstrate what you are trying to accomplish on stackoverflow and cross link here. Maybe someone can help you.

**Comment by g13013** [comment]
Sorry for wasting your time ! thank you.
