### ISSUE TITLE
SortableMixin was never deprecated

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/ember.js#12470]
Please deprecate SortableMixin in an Ember 1.13 patch. As noted by @workmanw in https://github.com/emberjs/website/issues/2256, it was never deprecated, just removed without warning.

**Comment by workmanw** [comment]
Oh hey, that's me! I have some bandwidth this afternoon. Let me get this.

**Comment by workmanw** [comment]
@rwjblue @Gaurav0 We can close this one now.
