### ISSUE TITLE
Calling `notifyPropertyChange` for a watch property does not update the cached value

### ISSUE THREAD

**Issue by bmac** [emberjs/ember.js#12484]
If a record is being watched by a template or computed property it doesn't appear possible to update the cached value returned by `Ember.get(obj, 'propertyName')` unless there is a an `Ember.set(obj, 'propetyName')`. This makes it impossible to use `notifyPropertyChange` to signal that the value of a property has been updated outside of an `Ember.set`.

Looks like this [branch of code](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/property_get.js#L76-L78) always checks `meta.peekValues` for the value of a watched property. However, `meta.peekValues` is only updated by an Ember.set. 

Here is a jsbin that reproduces this issue.
http://emberjs.jsbin.com/nulene/edit?js,console,output

**Comment by stefanpenner** [comment]
@bmac we should take a look together

**Comment by pixelhandler** [comment]
@bmac is this still an issue in Ember 2.4.5 ? The bin repo used Ember 1.13 so I added that label.

If the issue doesn't persist into Ember v2 perhaps we can close this. It's pretty unlikely that Ember 1.13 will get any more patches, especially now that we have an LTS release.

**Comment by bmac** [comment]
I just tested my jsbin with Ember 2.4.5 and this is no longer an issue.
