### ISSUE TITLE
Object.keys(Ember.Object.create()) return values differ between development and production

### ISSUE THREAD

**Issue by jschniper** [emberjs/ember.js#12489]
I've tried this against the current master as well as the 2.1.0 release.

In development, the return value of Object.keys(Ember.Object.create()) is an empty array but when the same code is built for production the return value is ["_super"]. This is happening in the latest versions of Firefox and Chrome so it doesn't appear to be a browser issue.

Please let me know if you need any more information.

**Comment by stefanpenner** [comment]
This is expected, making properties non-enumerable is extremely slow.

**Comment by jschniper** [comment]
Out of curiosity, why does the behavior differ between the two environments?

**Comment by stefanpenner** [comment]
no idea

**Comment by jschniper** [comment]
Alright, I guess this can just be closed. Thanks for the rapid response.

**Comment by mixonic** [comment]
Similar issue: https://github.com/emberjs/ember.js/issues/12462

**Comment by rwjblue** [comment]
This was identified and fixed in #12462 no?

**Comment by rwjblue** [comment]
I'd like to release 2.1.1 soonish, but using latest `release` channel builds should fix this for you.

**Comment by jschniper** [comment]
Oh, excellent. Thank you.

**Comment by stefanpenner** [comment]
@rwjblue yup that was it, forgot about that one.
