### ISSUE TITLE
Ember.set clobbers ES5 Computed property setters

### ISSUE THREAD

**Issue by bmac** [emberjs/ember.js#12480]
In [this jsbin](http://emberjs.jsbin.com/nulene/1/edit?js,console,output) I would expect my ES5 setter to log `'computed set is called'` to the console. However, the setter code never gets run because [this line in Ember.set](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/property_set.js#L86) overrides the existing property descriptor for `id` on `model`. I have defined my property with `enumerable: false,` because otherwise ember tries to copy the value form the `id` property when subclassing the the `Model` class.

[edit: ES5 computed setter => ES5 Setter, as `computed` setter in ES is something different... `set [value](value) { ... }` which isn't directly this issue]

**Comment by rwjblue** [comment]
Thanks for writing this up, definitely seems like a bug.

**Comment by stefanpenner** [comment]
working on this one now.

**Comment by stefanpenner** [comment]
need sleep, will continue in the AM.

**Comment by tricknotes** [comment]
It this issue was fixed by https://github.com/emberjs/ember.js/commit/aed80aaa7620c8f5b7090fdd5089bbc22c3637fa ?
ref: https://github.com/emberjs/ember.js/pull/12491

**Comment by stefanpenner** [comment]
I believe so
