### ISSUE TITLE
[PERF] Having To Manually Force GC In Node

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#12499]
## Summary

We have noticed that in FastBoot there appears to be GC related issues. To quote my co-worker Prateek:

> Briefly, our app or Ember are allocating a lot of objects every request which triggers a pathological behavior in v8's garbage collector. My best guess is that v8 dynamically increases the new gen size and uses an incremental scavenging algorithm to GC it. However, larger new gen sizes require more iterations to collect. This results in the early requests with a small new gen being fast, but subsequent requests progressively getting slower until a full GC.

> Since v8 doesn't expose many GC tuning options, the only solution I've found so far is to force a full GC (new + old gen) on every request. This adds ~30ms/100MB to every request, but is still faster and more consistent than the normal behavior on average (and even in 50 percentile).

__Without Forced GC__
![without-gc](https://github-cloud.s3.amazonaws.com/assets/183799/10565051/985fac6e-757c-11e5-87a5-b0e1ea8e35d0.png)

__Forced GC__
![forced-gc](https://github-cloud.s3.amazonaws.com/assets/183799/10565052/9a8631de-757c-11e5-906b-0cbf6514ba6c.png)

The above graphs __do not__ include rendering and are simply just doing "resource discovery", meaning that we only execute all the of the route handlers. I would assume there would be more allocations if we rendered to a string.

## Questions

- What are steps that can be taken to make GC less of an issue in Ember land?
- What can be done in application land?
- Would transpiled ES6 classes allocate less?
- Re-write Ember to be functionally pure because everyone knows OOP is considered harmful? :wink:

/cc @wycats @kratiahuja @chancancode @krisselden @tomdale

**Comment by kratiahuja** [comment]
A few things that we noticed during this experiment (we took a heapsnapshot between two consecutive runs and looked at the difference between the two snapshots):
* Even though we were running the test in "resource discovery mode", there were template strings in the object allocation (that were the highest). These were per instance rather than on the application container (atleast from what we saw).
* There were object allocations for the entire router per instance. Shouldn't this be at the application level?

I will try to run the tests with a simpler and scaled down app too.

**Comment by chancancode** [comment]
The first thing seems odd but possibly easy to deal with. Can you confirm you are using the version in 2.2 beta?

Also, can you confirm the objects are not leaking?

Since you are not using fastboot, are you using contextify?

**Comment by rwjblue** [comment]
> Can you confirm you are using the version in 2.2 beta?

`beta` channel does not include optional features (including the `visit` API).  This should be running against `canary` channel.  Either way, the `Ember.VERSION` value would be helpful in tracking down exactly which commit/sha is being used.

**Comment by chadhietala** [comment]
@chancancode We should be running on a canary at #ab04e97a in these tests.

**Comment by stefanpenner** [comment]
I hope your trolling re: oop being harmful

**Comment by kratiahuja** [comment]
Yes we are using Node's vm module and *not* contextify.

**Comment by chadhietala** [comment]
To @kratiahuja's comment I think we should somehow bar templates from the registry when `shouldRender` is set to `false`.

**Comment by stefanpenner** [comment]
I believe by using `vm` one duplicates large swaths of things, putting extra pressure on the gc. If memory serves, using contextify aimed to mitigate this...

**Comment by stefanpenner** [comment]
If memory serves, this was the result of using aspects of node incorrectly. LI folks returned to contextify and did so without issues
