### ISSUE TITLE
HTML progress element value changes to 1 when rendered in the outlet in IE 11

### ISSUE THREAD

**Issue by lpaluszk** [emberjs/ember.js#12504]
I'm experiencing a weird issue where the HTML 5 progress element's value changes to one when it's rendered. The compiled templates coming from the server contain correct values but when rendered the value is always 1.

I don't know how to put a fiddle together from ember-cli ES6 syntax.

To replicate, use IE 11 on Windows and place the following code:

    <progress value="40" max="100"/>

in:
- index.html just under the opening body tag
- application.hbs at the end of file

The progress bar from index.html will render correctly while the one inside the application template will have its value changed to 1.

Ember 2.1.0
jQuery 2.1.4

![untitled-1](https://cloud.githubusercontent.com/assets/3707675/10594038/d7a88c70-76c0-11e5-842e-9e0f667a73c1.png)

**Comment by lpaluszk** [comment]
Right, this line is not doing what it's supposed to do:

https://github.com/tildeio/htmlbars/blob/90fa31f3bb574e915c687cc66d0365c71f6c705b/packages/dom-helper/lib/main.js#L276

In IE, this line doesn't actually set the value of this element. However, if the order of attributes is reverted:

    <progress max="100" value="40"/>

it does work. 

Here are the results of swapping the order of max and value attributes:
![val-first](https://cloud.githubusercontent.com/assets/3707675/10619285/bc28a9a6-776c-11e5-8a84-d96ae8f85b3b.png)

![max-first](https://cloud.githubusercontent.com/assets/3707675/10619298/c70be5c2-776c-11e5-9e0d-5aa1c97ef4d9.png)

**Comment by lpaluszk** [comment]
I believe this may be an IE bug. I've reproduced it outside of Ember in this JSBin:

http://jsbin.com/yehulofajo/1/edit?html,output

I guess nothing we can do here, but luckily I don't mind swapping attributes around.

Do you want to close this or is there something you think you can do?

**Comment by rwjblue** [comment]
Great job tracking down the issue!  I am unsure this is actually an Ember bug at this point (seems like an IE one to me). If attribute ordering matters to the specific browser, then I'm not sure what we can do about it. I think the best thing might be to try to provide a compile time assertion (for `progress` when `value` is before `max`), but even that seems like a bit of a stretch...

**Comment by lpaluszk** [comment]
@rwjblue I agree. It definitely looks like an IE bug to me (see my third comment). I'm going to raise this with MS Edge team (affected by this as well) as I don't believe it will actually get fixed in IE (I have hopes for Edge). 

Hopefully, now this has been discovered, people will see this if it ever happens to them. After all, swapping the order of attributes really isn't a big deal. I see this as an acceptable workaround.

**Comment by lpaluszk** [comment]
I've raised this with MS:
https://connect.microsoft.com/IE/feedback/details/1923275/progress-element-created-with-javascript-will-always-have-a-value-of-1-if-the-max-attribute-isnt-set-first
