### ISSUE TITLE
Parameter-less helper calls don't work inside of attributes

### ISSUE THREAD

**Issue by ebryn** [emberjs/ember.js#12506]
Example: http://ember-twiddle.com/098c793577e88f993e1d

Given a `foo-bar` helper, you aren't able to call it without parameters inside of an attribute: 
```
<a href={{foo-bar}}>look at my href</a>
```

Quick workaround is to specify a parameter that won't be used:
```
<a href={{foo-bar helper=true}}>look at my href</a>
```

**Comment by mmun** [comment]
This should be fixed now. Anyone mind writing a test to verify it?
