### ISSUE TITLE
Add gitter badge to README

### ISSUE THREAD

**Issue by dj-hedgehog** [emberjs/ember.js#12508]
I just discovered the official Gitter chatroom for this repo and was wondering why you don't add the badge to the README?

**Comment by mixonic** [comment]
@dj-hedgehog I don't believe we're inclined to suggest Gitter is "official" by linking to it so prominently. However we do link to Slack, IRC, and some other community resources on http://emberjs.com/community/ and I think that would be a great place to call out Gitter.

**Comment by dj-hedgehog** [comment]
Oh, I didn't know about the Slack channel either until now. You could have either one as a badge in the repo as a lot of people will never see the community-page on the homepage.

**Comment by stefanpenner** [comment]
Seems a good idea, to indicate this prominently on the readme.

**Comment by stefanpenner** [comment]
@dj-hedgehog mind submitting such a badge / readme entry PR?

**Comment by dj-hedgehog** [comment]
I did here https://github.com/emberjs/ember.js/pull/12523 but there is a problem with the badge's height related to Slackin deployments to Heroku. I will try to find a fix for it and keep you updated.

**Comment by dj-hedgehog** [comment]
Here's an example. The left Slackin badge is pointing to https://ember-community-slackin.herokuapp.com/badge.svg and the left one is from socket.io.

![ember js 2015-10-27 10-47-32](https://cloud.githubusercontent.com/assets/7140800/10754480/205cc116-7c98-11e5-855a-879c0af531da.png)

**Comment by mixonic** [comment]
Closing in favor of https://github.com/emberjs/ember.js/pull/12523
