### ISSUE TITLE
link-to current-when cannot be supplied as `true` as per docs

### ISSUE THREAD

**Issue by rlivsey** [emberjs/ember.js#12512]
The [docs specify][0] that:

```
  A link will be active if `current-when` is `true` or the current
  route is the route this link would transition to.
```

However, this currently does not appear to be the case, as `current-when` is always treated as a string and `split` [called on it][1].

Should the docs be updated to reflect that this is expected to just be a string separated list of route names, or should `true` work as documented? I shall PR either way!

[0]: https://github.com/emberjs/ember.js/blob/1743e317955f2957d07a7d749c2d02cdf7cad174/packages/ember-routing-views/lib/components/link-to.js#L158
[1]: https://github.com/emberjs/ember.js/blob/1743e317955f2957d07a7d749c2d02cdf7cad174/packages/ember-routing-views/lib/components/link-to.js#L561

**Comment by rwjblue** [comment]
The fact that it doesn't work seems like a regression, and I think we should make the docs correct.

**Comment by beerlington** [comment]
@rlivsey Did you find a work around for this?

**Comment by rwjblue** [comment]
I think https://github.com/emberjs/ember.js/pull/12630 should fix this.

**Comment by rlivsey** [comment]
@beerlington @rwjblue sorry I got sidetracked after opening this and then seem to have completely forgotten about it!

#12630 looks like it should do the trick though (could do with a test or two though to prevent future regressions)

**Comment by beerlington** [comment]
I'll keep an eye on that, thanks!

**Comment by locks** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/12344.
