### ISSUE TITLE
Allow query-params sub expression to reset all query params

### ISSUE THREAD

**Issue by jfelchner** [emberjs/ember.js#12510]
I'd also like to weigh in on this that in addition it would be great to be able to pass a simple `null` into `query-params`.

The use case for this would be, for example if you had a filter bar with multiple different options (`filterA`, `filterB`, `filterC`, `searchQuery`, `sortDirection`, `sortField`, etc).  Typically you want to "clear" these.  Currently the way you would do this would be:

```
{{link-to 'clear' 'whatever' (query-params filterA=<defaultFilterAValue> filterA=<defaultFilterAValue> filterB=<defaultFilterBValue> filterC=<defaultFilterCValue> searchQuery=<defaultSearchQueryValue> sortDirection=<defaultSortDirectionValue> sortField=<defaultSortFieldValue>)}}
```

Which is uhhhhh verbose.

You have to redefine every query param, which is a ton of duplication.  And you have to remember that if you add a new one or rename one that you need to go back to the "clear" link (or multiple clear links) and add/change it.

What would be great is if you could instead say:

```
{{link-to 'clear' 'whatever' (query-params null)}}
```

And have it know to simply remove all query params from the URL.

**Comment by rwjblue** [comment]
It should be possible to make a helper to auto generate that verbose version.

**Comment by rwjblue** [comment]
I briefly looked into some of the internals to see how that would be done, and it seems like it should be straightforward to add a (default-query-params 'route.name.here') (or something) helper using the existing primitives. It would basically just return a hash that represents the default values.

**Comment by jfelchner** [comment]
@rwjblue does this seem like something that someone with no knowledge of the ember code base could tackle? Id be happy to try to help.

**Comment by rwjblue** [comment]
Only one way to get knowledge ;)

I'll try to leave some breadcrumbs/notes tomorrow morning...

**Comment by jfelchner** [comment]
@rwjblue perfect. :) I'll also be at EmberATX on Thursday as well if you think you'll have a few minutes and would rather do it that way.

**Comment by jfelchner** [comment]
@rwjblue care to point me in the right direction? :) I'd also be down to pair for a few minutes if that'd be easier for you.

**Comment by jpadilla** [comment]
Also interested in making this happen.

**Comment by rwjblue** [comment]
@jfelchner - Lets try to schedule some time for a quick Hangout or ScreenHero session to make a path.  Ping me on community slack?

**Comment by AriaFallah** [comment]
Any progress here?

**Comment by mmun** [comment]
This is a new feature and so it should go through the RFC process and/or implemented as an addon. Please feel free to reopen the issue there and to link back to this issue.
