### ISSUE TITLE
Setter for Ember.computed doesn't fire when set to false

### ISSUE THREAD

**Issue by phcoliveira** [emberjs/ember.js#12515]
Hello, there!

Maybe I am missing something because I didn't find anyone else complaining about this, but I think I've found a bug.

I have a computed property that looks like this:

``` Javascript
import Ember from 'ember';

export default Ember.Component.extend({
  someProp: Ember.computed({
    get() {
      return Ember.isPresent(window.localStorage.getItem('someProp'));
    },
    set(key, value) {
      console.debug('someProp.set', value);
      if (value) {
        window.localStorage.setItem('someProp', window.sessionStorage.getItem('someProp'));
      } else {
        window.localStorage.removeItem('someProp');
      }
    }
  }).volatile()
});
```

Then, in my custom checkbox component, I have something like this:

``` Javascript
import Ember from 'ember';

export default Ember.Component.extend({
  checked: null, // The value which determines if the checkbox is checked.
  actions: {
    toggle: function() {
      // It really doesn't matter if I use "toggleProperty", the problem is still the same.
      this.set('checked', !this.get('checked'));
    }
  }
});
```

With such code, running ```Ember 2.0.2```, the setter for ```someProp``` doesn't get invoked when the value set is ```false```. To get around this problem, I am actually using:
```javascript
this.set('checked', !this.get('checked') || null);
```

Why is this happening? The value ```false``` should be a valid value to be set.

**Comment by stefanpenner** [comment]
I believe your setter does not return its value to be cached (strange yes, maybe someday this will change)

**Comment by phcoliveira** [comment]
I have updated the setter to return the value transformed to boolean, it looks like this:

```Javascript
set(key, value) {
  if (value) {
    window.localStorage.setItem('someProp', window.sessionStorage.getItem('someProp'));
  } else {
    window.localStorage.removeItem('someProp');
  }
  return !!value
}
```

Nevertheless, the setter still is not invoked when set to ```false```.

**Comment by pixelhandler** [comment]
@phcoliveira Can you try to create a simple ember-twiddle.com example that shows a bug?

**Comment by phcoliveira** [comment]
Well, I really must be doing something wrong because I wouldn't be the first to complain about this by now.

I didn't have to create a component, nor a service. The regular input helper, with type to checkbox, is showing the same behaviour.

To be clear, in my own code, I don't use an input of type checkbox. I use a custom component with a ```toggle``` action.

Here is the Twiddle:

http://ember-twiddle.com/ee5e3d01b2877dce89eb

As I had said in my previous post, the problem is not related to the value ```false```, but rather the original value returned by the getter in its first invocation.

**Comment by phcoliveira** [comment]
Got it!

I thought I had to use ```volatile()``` for ```someProp```, since its computed value doesn't depend on any other property, but it turns out just fine without it.

I am still not sure if this behaviour intentional. Shouldn't a computed property be volatile if it doesn't depend on anything else?

**Comment by Vincz** [comment]
I'm running into the same issue with Ember 2.2.
Trying to do a "reversed" checked property on a checkbox, like that :

    isHalf: Ember.computed('isFull', {
        get(key) {
            return !this.get('isFull');
        },
        set(key, value) {
            console.log("value is : ", value, !value);
            this.set('isFull', !value);
            return !value;
        }
    }) 

With a checkbox with "checked" set to this property, my setter is called when the checkbox is checked, but not when it is unchecked.

**Comment by raytiley** [comment]
@Vincz you shouldn't be returning `!value` from the setter. Your basically flipping it too many times. Your setter should return the same thing that your getter would return.

So you set the checkbox sets the value to `true` this means `isFull` should be `false`. So you that's fine, but you still want the checkbox to be true, so you should return `value` not `!value`.

Working example: https://ember-twiddle.com/eeaa2e338610d3a45778

**Comment by Serabe** [comment]
I'm closing this since original issue seems to have been resolved and @Vincz was fixed by last comment.

Feel free to reopen if there is still any issue.

Thank you all!
