### ISSUE TITLE
Memory leak with conditionally included components

### ISSUE THREAD

**Issue by ianbale** [emberjs/ember.js#12513]
[This twiddle](http://ember-twiddle.com/c9c3e6c5a9908bd2c438) demonstrates a simple example where, using two components with conditional logic to determine which one is included, appears to be causing a memory leak. In the application where this came to light, the memory usage climbs from 400Mb (we have a lot of data) to around 1.5Gb before the application crashes. The memory usage climbs as we change the underlying data which determines which components to include / remove. All we are doing is toggling the data back and forth so that various components are included / removed repeatedly.After each iteration, the data, and hence component use is returned to the initial state. I would, therefore, expect memory usage to also return (after GC) back to that initial amount. But, for each chunk of memory allocated, only a fraction is ever being released.

[This second twiddle](http://ember-twiddle.com/01b1abe7badea3ce3a16) produces the exact same output as the one above, but does so without the component which outputs the divs with the text - instead that text is conditionally included inline. With this example, memory is being released. Although I am not convinced that ALL the memory is...

A full description of the problem is [on StackOverflow](http://stackoverflow.com/questions/33264625/ember-component-memory-leak)

**Comment by pixelhandler** [comment]
@stefanpenner can you take a look at this one?

**Comment by stefanpenner** [comment]
I think this was fixed by: https://github.com/emberjs/ember.js/pull/11667

**Comment by ianbale** [comment]
I just cloned the project and can confirm that it's fine with the latest master (2.3.0-canary+08ae4d65). I then went back and tried the beta builds and it looks like its fine as of v2.2.0-Beta.1 latest incremental build.

Thanks for the other pointers too!

**Comment by stefanpenner** [comment]
@rwjblue if memory serves, we back-ported those fixes to 1.13?

**Comment by ianbale** [comment]
I've applied the canary build to the project I discovered the memory leak in. Whilst the leak is dramatically smaller, it is still there. I'll apply your other suggested improvements and then try to isolate another simple test to demonstrate where the remaining leak(s) is.

**Comment by ianbale** [comment]
I tried this with latest 1.13.8 which also exhibits the leak...

**Comment by stefanpenner** [comment]
@ianbale if you can demonstrate the leak isolated on the latest release/master that would be great.

**Comment by ianbale** [comment]
I'll do my best! It took me a fair while to isolate this one. I'm working on a very big project that handles a huge amount of data (Fresh load in the browser is using just under 500Mb according to Chrome Task Manager). Isolating one issue like this is far from easy! 

I'm was seeing pretty much a straight line of memory use. Now I'm seeing a saw tooth with larger drops here and there. But, unfortunately, still a steady upward climb in terms of retained memory, whereas it should be discarding objects at pretty much the same rate as it creates them. So it ought to be holding relatively steady at around 550-600Mb, instead it steadily climbs to 1.5Gb or so, slows to a crawl then dies.

Do you want me to post back here with a demo or create a new ticket? Either way, it's likely to be a few days before I can get another demo together since I have no idea off hand how to replicate this outside of my application...

Thanks for your help

Ian

**Comment by rwjblue** [comment]
> I tried this with latest 1.13.8 which also exhibits the leak...

Latest Ember version in the 1.13 series is 1.13.10.

> @rwjblue if memory serves, we back-ported those fixes to 1.13?

Yes, all known memory leak fixes were backported to release-1-13 branch.

**Comment by ianbale** [comment]
Not tried 1.13.10 sorry. I got as far as 1.13.8 then jumped to 2.0.1

**Comment by stefanpenner** [comment]
> Yes, all known memory leak fixes were backported to release-1-13 branch.

thanks

> Not tried 1.13.10 sorry. I got as far as 1.13.8 then jumped to 2.0.1

I suspect the primary leak will then be fixed once you try 1.13.10, i am curious about the secondary one you mentioned. Please confirm, and provide a reproduction on latest versions of a specific release line.

**Comment by ianbale** [comment]
Hi,

In trying to find the cause of what looked like another memory leak, I've found a problem with our code. Essentially, some old objects that should be been destroyed were not always. So over time, then number of these unexpected objects was growing and it was that consuming extra memory. The combination of fixing that and the latest code you suggested above now results in a pretty static memory use as we'd expect.

Many thanks for your help

Ian

**Comment by trumb1mj** [comment]
Hi @ianbale, could you expound on what exactly an "object" is in this scenario and how you manually "destroyed" them?  I'm on the latest stable ember and I'm also seeing these memory leaks you speak of.

**Comment by runspired** [comment]
@trumb1mj if you ping me in the #performance channel on Slack I can help you out there

**Comment by ianbale** [comment]
Hi @trumb1mj 

In my case the "objects" were just JavaScript data objects holding some additional data about component instances that Ember had created and subsequently destroyed in the normal course of the application's lifespan. 

There is an awful lot of creation / disposal of visible Ember components in our app and we keep some meta data about these in a common controller for performance / ease of access outside of the component reasons. 

Essentially, this meta data consisted of a lookup table so that we could locate the correct component instance via a range of search criteria. But even these small amounts of data being left behind quickly mounted up to the point it had a serious affect on performance.

Not sure if the helps you at all?
