### ISSUE TITLE
Make regexps in Ember.String configurable

### ISSUE THREAD

**Issue by nagits** [emberjs/ember.js#12529]
Ember.String methods have no support of Cyrillic letters:
```
'hello'.capitalize(); // returns 'Hello'
'привет'.capitalize() // returns 'привет' instead of 'Привет'.
```
http://ember-twiddle.com/e438dc2fb58fe1de2ad1

Add Cyrillic letters into regexps (https://github.com/emberjs/ember.js/blob/v2.1.0/packages/ember-runtime/lib/system/string.js#L20) is probably not a good idea, but it would be great to make regexps in Ember.String configurable.

**Comment by pixelhandler** [comment]
@nagits Sounds like a feature request, see https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature 

> Use RFC issues to propose a rough idea, basically a great place to test the waters.

**Comment by stefanpenner** [comment]
closing, RFC is likely a better approach. Although I am doubtful this should happen here, rather some i18n library should provide internationalized string helpers that does this.
