### ISSUE TITLE
guides issue: better doc on Ember.observer

### ISSUE THREAD

**Issue by kamilbiela** [emberjs/ember.js#12528]
(this page: http://guides.emberjs.com/v2.1.0/object-model/observers/ )
just lost 3hours of debugging because I was doing this:

```
Ember.observer('selectedFeatures' ...
```
instead of this: 
```
Ember.observer('selectedFeatures.[]'
```

where selectedFeatures is Ember.A()

**Comment by pixelhandler** [comment]
@kamalaknn perhaps create a Pull Request on the Guides project. https://github.com/emberjs/guides/blob/master/source/object-model/observers.md

**Comment by locks** [comment]
I am closing this issue as it should have gone into the `Guides` repository like mentioned.
Feel free to re-open the issue if you think it's still justified, thank you.
