### ISSUE TITLE
Action helper argument placeholders?

### ISSUE THREAD

**Issue by alexander-alvarez** [emberjs/ember.js#12520]
Currently in Ember 1.13

I have a simple component that has grid-like functionality
```
{{#each rows as |row i|}}
   {{my-row-component
      someAction=(action 'selectRow' i value="target.attributes['col-num'].value")
   }}
{{/each}}
// my-row-component.js
...
 click: (event)->
     this.attrs.someAction(event)
```
**What happens:**
`i` becomes the first argument to the action callback and the `value` by default reads from first argument, which in this case is the i instead of the jquery event, in which case my arguments to  `selectRow` are `(undefined, jQuery.Event)`

**What I have to do:**
To fix this I have to bypass the neatness of the value setting, and modify the click code.
```
 click: (event)->
     this.attrs.someAction(event.target.attributes['col-num'].value)
```

**It would be neat to be able to do:**
```
someAction=(action 'selectRow' _ i value="target.attributes['col-num'].value" )
```

This would also be quite powerful with currying etc, and also give you flexibility  if you are using someone else's API you can't control.

Is this far-fetched?

**Comment by pixelhandler** [comment]
@alexander-alvarez This sounds like a feature request, see https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature 

> Use RFC issues to propose a rough idea, basically a great place to test the waters.

**Comment by mixonic** [comment]
This kind of exists as `value=` for http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_action @alexander-alvarez. If you're suggesting an extension to that I suggest following up with an issue on the RFC repo!
