### ISSUE TITLE
Contextual components are not new instances

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#12537]
select-box.hbs
```
    {{yield (hash option=(component 'select-box-option'))}}
```
application.hbs
```
    {{#select-box as |sb|}}
        {{sb.option label='Foo'}}
        {{sb.option}}
        {{sb.option}}
    {{/select-box}
```

The above renders 'Foo' _three times_ ([fiddle](http://jsfiddle.net/amk221/xccg1ews/))
I expected `sb` (the select box's public 'api') to render a new instance of each select-box-option

**Comment by rwjblue** [comment]
Definitely seems like a bug.

@serabe - Do you happen to have any time to figure out what is going on?

**Comment by Serabe** [comment]
I have just landed in Madrid (I'm in the plane still). Let me take a look
this weekend.

**Comment by Serabe** [comment]
I'll submit a fix tomorrow.
