### ISSUE TITLE
Returning a rejected promise from the application route fails ungracefully.

### ISSUE THREAD

**Issue by nathanhammond** [emberjs/ember.js#12539]
Here's a reduced example:
http://emberjs.jsbin.com/zawipuvawe/edit?html,js,console

I don't know what we want this behavior to be, but current state is clearly less than ideal. What do you think?

/cc @nickiaconis @krisselden

**Comment by stefanpenner** [comment]
cc @machty

**Comment by machty** [comment]
I modified this example a bit: http://emberjs.jsbin.com/bekofecibi/1/edit?html,js,output

You can use the `error` action to catch errors from the model hooks and go elsewhere. I'm not really sure what non-graceful error handling of errors in application model hooks should even look like; most of the time it contains crucial boot / startup logic that really shouldn't fail. But at least the existing `error` hooks give you some opportunity to catch the bug, report to error notifying services, restart the page, etc. What do you think?

**Comment by krisselden** [comment]
@nathanhammond did you try having an application-error.hbs?  it will not have the application controller since application route doesn't succeed but I think it gets error

**Comment by krisselden** [comment]
@nathanhammond @stefanpenner I don't think this is a bug, though I don't think we've thought at all about it for pods /cc @wycats @rwjblue 

Here is an example with an error template above the application:

https://ember-twiddle.com/2814945560df1a5d000b

**Comment by pixelhandler** [comment]
Weird @krisselden twiddle link doesn't open in Safari, only Chrome.

**Comment by rwjblue** [comment]
There is an issue reported in ember-twiddle about not opening properly in Safari.

**Comment by nickiaconis** [comment]
@krisselden That works fine in the app code. If you tried to write an acceptance test to verify that the acceptance-error route was entered when an error was encountered, `currentRouteName()` would not work because there would be no application controller.

**Comment by krisselden** [comment]
@nickiaconis agreed, this is more of a hidden piece of code to workaround that because we decided to make application an implicit route name, there is no way to define a sibling to it.  This needs to be address with pods, /cc @rwjblue @wycats

**Comment by pixelhandler** [comment]
@nathanhammond this issue seems to be stale; I'll close for now feel free to reopen it if necessary.
