### ISSUE TITLE
Enumerable#any vs Array#some

### ISSUE THREAD

**Issue by bryanaka** [emberjs/ember.js#12533]
In the docs, it says `Enumerable#any` should return a boolean, but this isn't necessarily true. It returns the first truthy value returned or the last falsey value returned.

This is inconsistent with `Array#some` as well, which always returns `true` or `false`.

Is this correct functionality? Either way, I can make either a PR to the docs or this repo to correct the behavior/explanation.

**Comment by pixelhandler** [comment]
@bryanaka can you make a jsbin, jsfiddle, or ember-twiddle example of the #any behavior? Then perhaps try other versions of an Ember release to see if the behavior has changed in some way.

Sounds like a bug if #any is not returning a boolean. http://emberjs.com/api/classes/Ember.Array.html#method_any

**Comment by bryanaka** [comment]
A bit rough/simple, but here it is with 2.1.0 -

http://emberjs.jsbin.com/kanuxap/edit?js,console

**Comment by bryanaka** [comment]
@pixelhandler I believe the breaking change was introduced here https://github.com/emberjs/ember.js/pull/4144/files

**Comment by Serabe** [comment]
Seems like bug. Can you please open a PR @bryanaka? Add some tests to make sure this do not happen in the future.

Thank you, @bryanaka, for reporting this.

**Comment by bryanaka** [comment]
Alright @Serabe @pixelhandler opened a PR - #13363

**Comment by Serabe** [comment]
@bryanaka: thank you so much! Not let's wait for some core member to review it. Maybe @rwjblue can give a quick glance to #13363.

**Comment by pixelhandler** [comment]
@Serabe @rwjblue the PR #13363 is unmergable, also what is the specific question, that needs team response?

**Comment by Serabe** [comment]
Quite likely we'll need to take over it at this point :(

**Comment by locks** [comment]
Left a comment at https://github.com/emberjs/ember.js/pull/13363#issuecomment-331964866 with the explanation. Thanks for your patience @bryanaka!
