### ISSUE TITLE
Expose `superFunc` for test stubbing

### ISSUE THREAD

**Issue by trentmwillis** [emberjs/ember.js#12531]
Currently, `this._super` is [dynamically replaced](https://github.com/emberjs/ember.js/blob/28163882e229719f496f5cbd72fdc7e84c9431b9/packages/ember-metal/lib/utils.js#L311) at function invocation. While this makes sense, it doesn't currently lend itself to stubbing the `_super` method in tests, since whatever you stub will be replaced when you actually call the function. Additionally, since `superFunc` isn't exposed (it lives in the function closure), you can't just stub that directly.

I realize this might be a small use-case, but was wondering if it would be worthwhile to expose `superFunc` via a property on the returned function.

**Comment by stefanpenner** [comment]
I don't believe we will  support stubbing super directly, this isn't a feature of ES6 super nor does is it in any language that has super.

If you wish to test super chains (or mock some ancestor), likely the best way is to actually wire up the inheritance.

**Comment by rwjblue** [comment]
I agree with @stefanpenner here. I'm going to close this for now, but please let us know if there is something that we missed...
