### ISSUE TITLE
Contextual components and hash helper causes attribute assignments on prototypes

### ISSUE THREAD

**Issue by sohara** [emberjs/ember.js#12540]
I'm seeing some unexpected behaviour where using contextual components in conjunction with the `hash` helper causes `attrs` that are passed in to the component during template invocation appear to be assigned to the component's prototype, rather than the component itself. Is this a known issue? Or perhaps the way I'm invoking the components is off?

Here's a twiddle demonstrating the issue: https://ember-twiddle.com/858f77bbf81a249d2c8b?numColumns=3

cc @mixonic @ef4

**Comment by rwjblue** [comment]
I believe this is a duplicate of https://github.com/emberjs/ember.js/issues/12537.

@sohara - Can you confirm and close if it is?

**Comment by sohara** [comment]
@rwjblue yeah, you're correct. Missed that somehow.

**Comment by rwjblue** [comment]
@sohara - No worries, thanks for testing out the feature!  We'll get it sorted out shortly...
