### ISSUE TITLE
[BUG] Handling Route Error Hook in tests

### ISSUE THREAD

**Issue by minasmart** [emberjs/ember.js#12547]
Hey there!

It appears that there has been some change between how ember v1.X - 2.0, and ember 2.1 work regarding the error hook. In the older iterations of ember, if an error was handled in an error hook, it wasn't treated as a failed assertion in the test environment. Now, in version 2.1 it's treated as a failed assertion.

Based on [this integration test](https://github.com/emberjs/ember.js/blob/master/packages/ember/tests/routing/substates_test.js#L406-L408) it appears that throwing the error from the application is the intent, however, this is a change that isn't identified anywhere, or mentioned in the documentation.

This bug has been brought up in a few other issues:
- https://github.com/emberjs/ember.js/issues/12472
- https://github.com/emberjs/ember.js/issues/12166

It appears to be causing some confusion for those of us who are intent on testing our error behaviours.

In fact, the documentation states:
> error actions that bubble up all the way to ApplicationRoute will fire a default error handler that logs the error. You can specify your own global default error handler by overriding the error handler on ApplicationRoute

[source](http://emberjs.com/api/classes/Ember.Route.html#event_error)

Which would lead me to believe that if an error hook doesn't return true, then the error doesn't bubble, and it's not sent out through any default error handler.

I've written a [really basic test app](https://github.com/minasmart/ember-route-error-hook) that's building in circle CI on the two ember version branches, showing the differences between test outcomes.

I'm not sure if the correct fix here is to adjust the documentation, or if a test should be added to ensure the error does not throw from the application when the error hook returns false.

I'll attach a PR with the proposed test (which should fail, given that the error is being thrown regardless of error bubbling).

**Comment by minasmart** [comment]
The PR referenced fails in 2.1, but passes in 2.0. It identifies the differences in behaviour around bubbling and handled errors.

**Comment by minasmart** [comment]
After performing a git bisect on Ember, it looks like this commit: 854d3bef3c097196c1d5ad2ec0fc4661f260ca61 is what broke or changed the behaviour. And it looks like, at the time of this commit, there were no allowances made for handled errors.

**Comment by rwjblue** [comment]
Awesome, thanks for bisecting.
