### ISSUE TITLE
Tagless components issue on beta and canary

### ISSUE THREAD

**Issue by mike183** [emberjs/ember.js#12554]
A TypeError is triggered when attempting to use a tagless component, although it only seems to occur when the component has no JS file. Creating a JS file for the component makes the issue disappear.

The issue seems to have been introduced in this PR: https://github.com/emberjs/ember.js/pull/12503

Error:
`Uncaught TypeError: Cannot read property 'lookup' of undefined`

Twiddle showing error (No JS file):
https://ember-twiddle.com/aeb614b5b753fd9f562c

Twiddle with no error (Includes JS file):
https://ember-twiddle.com/33793eecdd0026d524a1

**Comment by tim-evans** [comment]
Found this as well. It seems that the `owner` property on the `RenderEnv` isn't being set for tests.

**Comment by tim-evans** [comment]
I've tracked it down to https://github.com/emberjs/ember.js/commit/9845a9a58704fac12dcd65afeeedd5267fa1eec9. Tests pass before this commit and fail afterwards. It may be that https://github.com/switchfly/ember-test-helpers/tree/master/lib/ember-test-helpers needs an update to handle this. (I'm not sure).

**Comment by tim-evans** [comment]
See https://github.com/emberjs/ember.js/issues/12555 for the checklist of this feature.

**Comment by rwjblue** [comment]
> It seems that the owner property on the RenderEnv isn't being set for tests.

Yes, ember-test-helpers definitely needs a few tweaks to work with canary, but the `owner` issue should not affect the beta branch (which is also demonstrating the issue).

**Comment by tim-evans** [comment]
Super! Anything I can do to help with this @rwjblue ?

**Comment by tim-evans** [comment]
The following configuration should fix this:

`package.json`
```json
  "ember-cli-qunit": "0.3.14"
```

`bower.json`
```json
  "ember": "ember#canary",
  "ember-data": "ember-data#canary"
```

**Comment by rwjblue** [comment]
Ok, closing for now.
