### ISSUE TITLE
potential deopt while reading

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#12552]
https://github.com/emberjs/ember.js/blob/master/packages/container/lib/container.js#L183-L184

**Comment by ptgamr** [comment]
Hi @stefanpenner , as I understand from the article: http://mrale.ph/blog/2015/11/02/crankshaft-vs-arguments-object.html , we should not allocate `arguments` if we can.

In the current code, I see `var injectionArgs = Array.prototype.slice.call(arguments, 1);`, so there is allocation of the `arguments` into `injectionArgs` here right? So the VM will have to materialize it...

I just can think of the solution to get rid of that allocation, if you think this work, I can make a PR:

```
function buildInjections(container) {
  var hash = {};

  if (arguments.length > 1) {
    var injections = [];
    var injection;

    for (var i = 1, l = arguments.length; i < l; i++) {
      if (arguments[i]) {
        injections = injections.concat(arguments[i]);
      }
    }

    container.registry.validateInjections(injections);

    for (i = 0, l = injections.length; i < l; i++) {
      injection = injections[i];
      hash[injection.property] = lookup(container, injection.fullName);
      if (!isSingleton(container, injection.fullName)) {
        markInjectionsAsDynamic(hash);
      }
    }
  }

  return hash;
}
```

**Comment by stefanpenner** [comment]
> We also aliasing container, but I think we should keep it for readability of the code.

I think since we never set to it, its not the end of the world.

Alternatively we could do

```js
function buildInjections(/*container, ...injections */) {
  var container = arguments[0];
  ....
```

**Comment by ptgamr** [comment]
@stefanpenner , are we allowed to use babel inside `/packages/container/lib/container.js`?

Babel now use the same approach for `rest arguments` 

```
function getArgs(container, ...list) {
  console.log(list)
}
```

turns into

```
"use strict";

function getArgs(container) {
  for (var _len = arguments.length, list = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
    list[_key - 1] = arguments[_key];
  }

  console.log(list);
}

getArgs(1, 2, 3);
```
