### ISSUE TITLE
for in issue with ember

### ISSUE THREAD

**Issue by Arunkumarvelu** [emberjs/ember.js#12553]
I am using for in (loop) in my javascript with ember js. It is returning all the methods which is attached to it prototype.

var a = []
for(i in a){console.log(i)}

it returns  _super,nextObject,firstObject,lastObject, etc...

How can i eliminate it from for in loop?

**Comment by mike183** [comment]
This isn't an issue with Ember. I believe for...in iterates over the enumerable properties of an object. I think you're looking for something like the following:

```js
var a = [];
a.forEach(function(item, index, array) {
  console.log(item);
});
```

**Comment by stefanpenner** [comment]
Setting EXTEND_PROTOTYPES to false will mitigate this

In theory we could define prop these to be non enumerable, but that comes with some perf issues :(

We do believe pollution of the prototype is a bad move, and have been working to move away.

Please note, when enumerating an array the idiomatic is via for loop, or for each. For in isn't the generally recommended way, unless you also want pollution. (The Mozilla docs even bring this point up)

**Comment by Arunkumarvelu** [comment]
Thanks for the reply

**Comment by stefanpenner** [comment]
I'm going to close this, as mentioned above future work is planned to continue to move away from poluting natives by default.
