### ISSUE TITLE
Windows XP blue screen with Adobe Air browser

### ISSUE THREAD

**Issue by victorleungtw** [emberjs/ember.js#12563]
I tried to open the EmberJS official website using Adobe Air browser in Windows XP3. 

The machine crashed right away with blue screen of death. Here is the dump error:

==================================================
Dump File         : Mini110415-01.dmp
Crash Time        : 11/4/2015 4:38:38 PM
Bug Check String  : RESOURCE_NOT_OWNED
Bug Check Code    : 0x000000e3
Parameter 1       : 0x8a2ef7f8
Parameter 2       : 0x891f4690
Parameter 3       : 0x00000000
Parameter 4       : 0x00000002
Caused By Driver  : win32k.sys
Caused By Address : win32k.sys+19f4
File Description  : 
Product Name      : 
Company           : 
File Version      : 
Processor         : 32-bit
Crash Address     : ntoskrnl.exe+22fa3
Stack Address 1   : ntoskrnl.exe+5ea49
Stack Address 2   : win32k.sys+19f4
Stack Address 3   : win32k.sys+157286
Computer Name     : 
Full Path         : E:\Mini110415-01.dmp
Processors Count  : 4
Major Version     : 15
Minor Version     : 2600
Dump File Size    : 94,208
Dump File Time    : 11/4/2015 4:52:10 PM
==================================================

**Comment by stefanpenner** [comment]
Is this a web control inside a flex app, or is there actually an official browser of some kind by Adobe. Can you provide additional references?

**Comment by stefanpenner** [comment]
A quick google reveals (if its a web control of some kind in flex) it may be using an old / stale version of Webkit https://forums.adobe.com/thread/1494000

If it is, it may also have issues loading/running adobe.com https://forums.adobe.com/message/7315135#7315135

**Comment by stefanpenner** [comment]
i gave http://lucentminds.com/archives/adobe-air-web-browser.html a try (maybe this is what you meant) on OSX and it seems to load stuff correctly, discuss.emberjs.com even works correctly.

**Comment by victorleungtw** [comment]
@stefanpenner thanks a lot for your reply. The problem is specific to Windows XP Service Pack 3, so won't able to replicate on OSX. I installed this browser on XP and able to replicate the blue screen issue as well -  http://lucentminds.com/archives/adobe-air-web-browser.html

**Comment by stefanpenner** [comment]
We need more information what this browser actually is. I suspect it is some old broken WebKit but would like to confirm before writing this off as won't fix. Ideally we support anything reasonable, so we need all the facts.  The fact that it's causing a blue screen. Would indicate a  very serious bug in the browser . Potentially even a security concern.

**Comment by victorleungtw** [comment]
@stefanpenner I spent further time to investigate, and found the root cause is actually from font-awesome! That's why angular js website also crashed the XP machine. I remove this library and my webpage loads now. This issue could be closed. Thanks again for your help :D
