### ISSUE TITLE
Mistake on documentation

### ISSUE THREAD

**Issue by ozanmuyes** [emberjs/ember.js#12560]
Hello,

Thanks for the awesome framework. I've been reading the documentation and I found a mistake. In the last topic of the page http://guides.emberjs.com/v2.1.0/object-model/classes-and-instances/ set method referred as accessor, while it's a mutator.

Regards,
Ozan MÜYESSEROĞLU

**Comment by josemarluedke** [comment]
Could you open this issue on the Guides repo? https://github.com/emberjs/guides

**Comment by ozanmuyes** [comment]
Hello Josemar,

Sorry for my mistake - which happend while reporting a mistake. I opened an issue on guides.

Regards,
Ozan MÜYESSEROĞLU
