### ISSUE TITLE
Warning on attribute binding in Ember 2.1 recommends an incompatible solution.

### ISSUE THREAD

**Issue by kitsunde** [emberjs/ember.js#12571]
The warnings links to 1.11 documentation which recommends using `Ember.Handlebars.SafeString` which doesn't work. The user should use `Ember.String.htmlSafe` instead. Example:

http://emberjs.jsbin.com/voyoro/1/edit?html,js,output

This was mentioned in https://github.com/emberjs/ember.js/issues/10783#issuecomment-133577666 but the issue was already closed. The deprecation warning should be updated for Ember 2.1.

**Comment by rwjblue** [comment]
The referenced warning points to http://emberjs.com/deprecations/v1.x/#toc_warning-when-binding-style-attributes.  The solution described there does work properly ([see here](http://rwjblue.jsbin.com/zuhive/edit?html,js,output)).  Your provided JSBin did not call `new` for `Ember.Handlebars.SafeString` (but the example in the deprecation guide does).

**Comment by kitsunde** [comment]
@rwjblue Ah I see, thanks.  :heart:
