### ISSUE TITLE
Closure actions bubble?

### ISSUE THREAD

**Issue by davidsteinberger** [emberjs/ember.js#12576]
My understanding of closure actions was, that they don't bubble. But it looks to me as if this is only true when actions are not attached to a nested html structure. Is this a bug or is this intended?

Here a little twiddle that demonstrates it: https://ember-twiddle.com/0b31c2ac3f1c74c66b8c

**Comment by mmun** [comment]
@davidsteinberger The twiddle is working as expected.

The click event bubbles through the DOM correctly. What is meant by "action's not bubbling" is that an action that is targetted at a controller will never be redirected to the router (which in turn would check if any of the active routes has defined an action, i.e. "bubbling through the routes").

**Comment by davidsteinberger** [comment]
@mmun Thanks for the explanation. Makes totally sense now. If I want to prevent the bubbling through the DOM is then the `ev.stopPropagation()` a *proper* solution?

**Comment by mmun** [comment]
@davidsteinberger Yes it is :)
