### ISSUE TITLE
Speeding up require in ember

### ISSUE THREAD

**Issue by SamSaffron** [emberjs/ember.js#12586]
@stefanpenner  been looking at requireInternal in Ember. 

Seems like we can get some perf here by preallocating the array http://jsperf.com/preallocating-array/23

```
var reified = [];
      var length = deps.length;

      for (var i=0; i<length; i++) {
        if (deps[i] === 'exports') {
          reified.push(exports);
        } else {
          reified.push(internalRequire(resolve(deps[i], name), name));
        }
      }
```

reified can be preallocated then you don't need to push 

Thoughts?

**Comment by SamSaffron** [comment]
Also I wonder if we can somehow get rid of the recursion there, it will make it way easier for js engines to optimize

**Comment by rwjblue** [comment]
Preallocating sounds fine (and easy enough to do), but I'd like to see via benchmarks if it makes a practical difference here.

**Comment by stefanpenner** [comment]
@SamSaffron -> https://github.com/emberjs/ember.js/pull/11576

**Comment by stefanpenner** [comment]
@SamSaffron yes, reified should/could be pre-allocated.

**Comment by stefanpenner** [comment]
@SamSaffron if you have time, I would love to get a quick and dirty benchmark suite for loader.js -> https://github.com/ember-cli/loader.js

**Comment by stefanpenner** [comment]
I patched embers heavily patched loader to do this, i was going to update loader.js proper but realized it already does this: https://github.com/ember-cli/loader.js/blob/master/loader.js#L72-L73

**Comment by krisselden** [comment]
So ember doesn't use the same loader?

**Comment by stefanpenner** [comment]
They begun life together. Embers loader has been hacked up, it would be nice to reconverge at some point

**Comment by gogogarrett** [comment]
Is there any information anywhere about the differences between the two and what context each are used for?

**Comment by rwjblue** [comment]
> So ember doesn't use the same loader?

No.

> They begun life together.

In the beginning, there was only Ember's loader.  We had like 5 different versions inlined in various projects before ember-cli/loader.js was extracted and made the primary one.

> Is there any information anywhere about the differences between the two

diff https://github.com/ember-cli/loader.js/blob/master/loader.js and https://github.com/emberjs/ember.js/blob/master/packages/loader/lib/main.js

**Comment by stefanpenner** [comment]
As we move to addonify ember, we will want the app and ember to sure a loader. (I believe) at which some form of unification must be done.
