### ISSUE TITLE
hash computed macro

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/ember.js#12595]
With the imminent arrival of closure-components and concept of "public api" exposed through "yield" using the new hash helper. I think there's a need for a "hash" computed macro.

```js
// component.js
Ember.Component.extend({
  api: Ember.computed.hash('firstName', 'lastName'), // {firstName: "Olivier", lastName: "Lesnicki"}
  firstName: 'Olivier',
  lastName: 'Lesnicki'
});
```

```
// template.hbs
{{yield api}}
```

**Comment by rwjblue** [comment]
In general, I think that using the hash helper in the template is a  better solution for this (there are a number of things you can't take advantage of in JS-land).

If you still would prefer to do this in JS definition instead, I think an addon providing this functionality makes more sense than adding another computed macro to core.

**Comment by olivierlesnicki** [comment]
I agree with the hash helper in the template - can't wait to play around with closure-components.
However I don't see why `collect` is a more suitable candidate than `hash`.

**Comment by mixonic** [comment]
@olivierlesnicki both closure components and actions can only be created in templates. Thus a hash macro in JS doesn't really provide a benefit in those use cases.

I would also prefer to see this in an addon or perhaps https://github.com/cibernox/ember-cpm before we would consider it for ember. We're trying to be conservative and add fewer macros.

Thank @olivierlesnicki!

**Comment by rwjblue** [comment]
> However I don't see why collect is a more suitable candidate than hash.

I'm not sure what you mean here.  At this point I would be opposed to almost any new macros being added to `Ember.computed`.  The giant grab bag that we have is mostly because it was extremely difficult to share utilities in the very early Ember 1.0.0 timeframe.  This is no longer true, it is trivial to make and consume an addon with this helpful macro.
