### ISSUE TITLE
Checkbox always checked

### ISSUE THREAD

**Issue by IAmJulianAcosta** [emberjs/ember.js#12598]
When setting checkbox `checked` property, the checkbox renders checked ☑: 

```
login-component.hbs
{{input type="checkbox" name="reminderMe" id="reminderMe" checked="remindMe"}}
```

```
login-component.js
import Ember from 'ember';

export default Ember.Component.extend(
		{
			remindMe : false
		}
);
```

I expect that if remindMe is false, checkbox will render without check: ☐

Not binding checked property will render ☐

**Comment by rwjblue** [comment]
`checked` is being passed as a non-empty string, it can never be false.  Perhaps you meant:

```
{{input type="checkbox" name="reminderMe" id="reminderMe" checked=remindMe}}
```

**Comment by IAmJulianAcosta** [comment]
You're right, closing :)
