### ISSUE TITLE
Missing API documentation for View.attributeBindings

### ISSUE THREAD

**Issue by mike-post** [emberjs/ember.js#12601]
Ember.View.attributeBindings is not documented as a property in the API. The view class pre-amble talks about it, but that's not so much help when you're looking at Ember.Component.

**Comment by pixelhandler** [comment]
@mike-post yeah http://emberjs.com/api/classes/Ember.View.html#toc_html-attributes should be mentioned at http://emberjs.com/api/classes/Ember.Component.html right?

Or, is this sufficient? http://guides.emberjs.com/v2.2.0/templates/binding-element-attributes/#toc_adding-data-attributes

@locks, @trek -  I'm curious if there are any more `Ember.View` concepts that need to be surfaced at the `Ember.Component` level of API Docs. What do you think?

**Comment by rwjblue** [comment]
Conversation about this in Slack:

saladfork [13:00] 
looks like it needs to be moved over from the `Ember.View` API docs and/or we need to add docs for the `Ember.AttributeBindingsSupport` mixin

rwjblue [13:13] 
@saladfork: docs should go in the mixin, then we should update Ember.Component to `@extends Ember.AttributeBindingSupport` (or whatever the name is)

**Comment by locks** [comment]
@SaladFork can you get a PR in?

**Comment by knownasilya** [comment]
Ping..

**Comment by pixelhandler** [comment]
@SaladFork @knownasilya @locks @rwjblue @mike-post is this still an issue, perhaps we should close; what do you think?

**Comment by knownasilya** [comment]
I'm fine with that, since we are closer to new semantics.

**Comment by pixelhandler** [comment]
@emberjs/learning-team-managers I'll close for now if you think we need to address guides/docs on `attributeBindings` please open on https://github.com/ember-learn/guides-source
