### ISSUE TITLE
Add some basic retry logic to sauce tests

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#12615]
We often experience intermittent sauce failures, it may be a good idea to add a small amount of re-try logic.

Something like:

if a given sauce run has failed, by all previous have ultimately succeeded, retry the current failure up to 3 times.
If all previous have failed, and the current failed leave it in a failed state and move to the next.

cc @seanpdoyle unsure if this interests you, but if you have cycles this should be a nice win.

**Comment by seanpdoyle** [comment]
@stefanpenner that sounds interesting.

Would that live in https://github.com/emberjs/ember.js/blob/04ec1c639e3ac7aa93ec24bf7fcf35e18c62fed6/bin/run-sauce-tests.js#L50-L52?

How do we detect how the previous runs have performed?

**Comment by stefanpenner** [comment]
> How do we detect how the previous runs have performed?

unsure

> Would that live in https://github.com/emberjs/ember.js/blob/04ec1c639e3ac7aa93ec24bf7fcf35e18c62fed6/bin/run-sauce-tests.js#L50-L52?

i think so

cc @fivetanley

**Comment by stefanpenner** [comment]
I believe we should pursue this as an addition to testem.

**Comment by bekzod** [comment]
this is no longer valid since sauce removed completely ?
