### ISSUE TITLE
attrs not updating correctly for contextual components

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#12613]
Please see the console on this twiddle https://ember-twiddle.com/a8022eac7bbe8eb52801

_Edit_: Sorry, badly named issue. Not sure what the actual problem is just yet.

**Comment by rwjblue** [comment]
Haven't dug into exactly what is happening just yet, but this is definitely a bug.

**Comment by Serabe** [comment]
While working on #12617 I'm also taking a look at this since both seem to touch the same classes.

I have notice that [`attrs`](https://github.com/emberjs/ember.js/blob/afdba0f334e761734c59a05b1312b061e1dd0faa/packages/ember-htmlbars/lib/node-managers/component-node-manager.js#L182) is different in each case on rerender. It contains the right value in `my-component` but not in `my-nested-component`. I need to see how the closure component relates to the rerender.

**Comment by Serabe** [comment]
I think I know what is happening. I'll check tonight (your this morning)

**Comment by Serabe** [comment]
Submitted a PR fixing this. The shortcat for rerendering was being done to soon preventing the arguments from the closure component to be passed to `state.manager.rerender`.

**Comment by amk221** [comment]
Thanks!

**Comment by amk221** [comment]
@Serabe Thanks for you work on the fix. Would you be able to look at the [updated twiddle](https://ember-twiddle.com/a8022eac7bbe8eb52801?numColumns=1). I've tried to clarify what I am expecting the behaviour to actually be (see the console).

Essentially, I think that `didReceiveAttrs` is not firing with the correct value. But I might be expecting the wrong thing.

**Comment by rwjblue** [comment]
Reopening for review.

**Comment by Serabe** [comment]
I think when Ember Twiddle updates with the fix it should be ok. @rwjblue do you know if there is a way to test a twiddle with current master?

**Comment by rwjblue** [comment]
https://ember-twiddle.com/5a29d14617527134ecad?numColumns=1 seems to be working properly (and using the correct SHA of Ember canary).

@amk221 - Can you confirm?

**Comment by amk221** [comment]
Confirm, it's working. Thanks!
_(Apologies, miscommunication between myself and rwjblue on Slack)_

**Comment by amk221** [comment]
[The RFC](https://github.com/emberjs/rfcs/blob/master/text/0064-contextual-component-lookup.md) suggests I should be able to send along additional attributes to contextual components.

If you add `foo='bar'` as an attr to the contextual component in the twiddle, then the 'additional attribute' is not additional, but seems to wipe out the closed over attributes.

**Comment by Serabe** [comment]
Please, can you send the updated tweedle? I did [this](https://ember-twiddle.com/363407699ced5eea9c1b?numColumns=1) and seems to work.

**Comment by amk221** [comment]
@Serabe Yup, that's what I did too. Notice the difference in the console when you add that extra attribute? myProp does not increment, but it should?

**Comment by Serabe** [comment]
I see now. Proper support for glimmer components are still in the making. I'll take this into account. Thank you.

**Comment by amk221** [comment]
Ok thanks, this blocks a feature I need to create a select box component - is there a place I can track this issue?

**Comment by Serabe** [comment]
The [PR referenced above](https://github.com/emberjs/ember.js/pull/12628)
