### ISSUE TITLE
Remove Ember. references from within internal modules

### ISSUE THREAD

**Issue by krisselden** [emberjs/ember.js#12611]
- [x] packages/ember-application/lib/system/resolver.js: -> https://github.com/emberjs/ember.js/pull/12616
   - this one depends on Ember.TEMPLATES, which can be rebound/replaced at will. (our tests do this all  over the place)
- [x] packages/ember-htmlbars/lib/system/bootstrap.js: -> https://github.com/emberjs/ember.js/pull/12616
   - this one depends on Ember.TEMPLATES, which can be rebound/replaced at will. (our tests do this all  over the place)
- [x] packages/ember-htmlbars/lib/utils/string.js: -> https://github.com/emberjs/ember.js/pull/12616
  - relies on Ember.STRINGS which can also be rebuild/replace at will
- [x] packages/ember-metal/lib/streams/stream.js: -> https://github.com/emberjs/ember.js/pull/12616
- [ ] packages/ember-routing/lib/system/route.js:
  - [ ] Ember.testing
  - [x] Ember.isEmpty -> https://github.com/emberjs/ember.js/pull/12616
- [ ] packages/ember-runtime/lib/ext/function.js:
  - [ ] Ember.EXTEND_PROTOTYPES
- [ ] packages/ember-runtime/lib/ext/rsvp.js:
  - [ ] Ember.testing
  - [ ] Ember.Test && Ember.Test.Adapter
  Should likely have Ember.Testing augment rsvp/ext rather then rsvp knowing about Ember.Test
- [ ] packages/ember-runtime/lib/ext/string.js:
   - [ ] Ember.EXTEND_PROTOTYPES
- [x] packages/ember-runtime/lib/mixins/array.js: -> https://github.com/emberjs/ember.js/pull/12616
- [x] packages/ember-runtime/lib/mixins/enumerable.js: -> https://github.com/emberjs/ember.js/pull/12616
  - [x] Ember.A cycle 
- [ ] packages/ember-runtime/lib/mixins/target_action_support.js:
  - [ ] Ember.lookup
  
- [x] packages/ember-runtime/lib/system/core_object.js: -> https://github.com/emberjs/ember.js/pull/12616
- [ ] packages/ember-runtime/lib/system/lazy_load.js:
   - [ ] Ember.ENV.EMBER_LOAD_HOOKS – basically legacy crap we should kill
- [ ] packages/ember-runtime/lib/system/namespace.js:
   - [ ] Ember.BOOTED
   - [ ] Ember.KEY_NAME
   - [ ] Ember.anyUnprocessedMixins
   - [ ] Ember.Lookup

    This file really has years of legacy behaviors, and multiple was to accomplish the same things.  It also has many performance hacks specific to the globals + toString world. Names should all be derived from the resolver, and most of this file should be phased out
- [ ] packages/ember-runtime/lib/system/native_array.js:
  - [ ] Ember.EXTEND_PROTOTYPES

- [ ] packages/ember-runtime/lib/system/string.js:
  - [ ] Ember.EXTEND_PROTOTYPES
- [X] packages/ember-views/lib/components/component.js:
- [ ] packages/ember-views/lib/system/jquery.js:
   - [ ] Ember.imports <-- legacy
   - [ ] Ember.ENV.FORCE_JQUERY <-- WAT?
- [ ] packages/ember-views/lib/views/collection_view.js:
  - [ ] Ember.ENV._ENABLE_LEGACY_VIEW_SUPPORT
- [ ] packages/ember-views/lib/views/container_view.js:
  - [x] isEmpty
  - [ ] Ember.ENV._ENABLE_LEGACY_VIEW_SUPPORT,
- [x] packages/ember-views/lib/views/core_view.js:
- [ ] packages/ember-views/lib/views/view.js:
   - [ ] Ember.ENV.* for deprecation hooks.
   - [x] Ember.TEMPLATES

[edit: remove extra path info, and convert to checkout - @stefanpenner]

**Comment by rwjblue** [comment]
:+1: - Thanks for putting together the list.

**Comment by stefanpenner** [comment]
im avoiding doing windows work, will take a stab.

**Comment by krisselden** [comment]
making a sublist is good, is good, maybe we can do export var?

**Comment by krisselden** [comment]
Also, I didn't include the template-compiler, I feel like it would be nice to use rollup for that

**Comment by stefanpenner** [comment]
I updated the checkout, to outline remaining work, and also completed some of the log hanging work.

Source of more global pains are:

* Ember.TEMPLATES
* Ember.STRINGS
* Ember.EXTEND_PROTOTYPES
* Ember.A cycles
* Ember.imports
* Ember.lookup

**Comment by locks** [comment]
Currently tracked elsewhere. @krisselden will work on a follow-up quest issue.
