### ISSUE TITLE
Positional params issue in contextual components

### ISSUE THREAD

**Issue by mike183** [emberjs/ember.js#12625]
An assertion is being triggered when attempting to use positional params with contextual components via the hash helper.

Imagine the following

```hbs
{{!-- templates/components/parent-component.hbs --}}
{{yield (hash childComponent=(component "child-component"))}}
```

```js
// components/child-component.js
import Ember from 'ember';

const childComponent = Ember.Component.extend({});

childComponent.reopenClass({
  positionalParams: "params"
});

export default childComponent;
```

If we attempt to instantiate `childComponent` directly, the assertion is triggered, if we instantiate `childComponent` using the component helper, everything works as expected. See below for examples:

```hbs
{{!-- Not Working --}}
{{#parent-component as |hash|}}
  {{hash.childComponent "param1" "param2"}}
{{/parent-component}}

{{!-- Working --}}
{{#parent-component as |hash|}}
  {{component hash.childComponent "param1" "param2"}}
{{/parent-component}}
```

I've also created a couple of Twiddles, one showing the error and one showing it working when used with the component helper.

**Working:**
https://ember-twiddle.com/331b165b525660a2307d

**Not Working:**
https://ember-twiddle.com/cef32d9fc97b265e824b

The assertion being thrown is:
```
Uncaught Error: Assertion Failed: You cannot specify positional parameters and the hash argument `params`.
```

I discovered the issue on v2.3.0-beta.1 although I suspect the issue could also affect v2.2.0.

**Comment by Serabe** [comment]
I think I know what's happening. If I'm right, it would be a quick fix. I'm having dinner, I'll check later.

**Comment by mixonic** [comment]
This feature does not exist in 2.2, so it would be a `[BUGFIX beta]`. It seems like this is related to `params` being an internal we use. Definitely a bug.

**Comment by mike183** [comment]
> This feature does not exist in 2.2, so it would be a [BUGFIX beta].

Of course! My mistake
