### ISSUE TITLE
component's parentView is null in both willDestroyElement and willClearRender

### ISSUE THREAD

**Issue by foxnewsnetwork** [emberjs/ember.js#12620]
Sometimes, it makes sense for nested components to tell their parent component they're being destroyed such as:

```javascript
willDestroyElement () { 
  this.get("parentView").disposeOfDeadChild(this);
}
```
However, `this.get("parentView")` returns `null` inside the `willDestroyElement` and `willClearRender` (it is present in `willInsertElement` and `didInsertElement` though). The following codepen illustrates this issue:

http://codepen.io/foxnewsnetwork/pen/Lpqeag?editors=101

Can we make `parentView` be present even in the destructive life-cycle callbacks?

**Comment by Emrvb** [comment]
The methods names imply they're called before removal, so one would indeed expect the parentView to be still available. This is potentially an issue for addon developers.

**Comment by pixelhandler** [comment]
@foxnewsnetwork `parentView` is private API, http://emberjs.com/api/classes/Ember.Component.html#property_parentView

Best not to reply on private API, perhaps the design need to change, maybe a closure action can be used instead. Then the parent component can call `destroy()` or whatever pubic API is needed for clean up http://emberjs.com/api/classes/Ember.Component.html#method_destroy

**Comment by foxnewsnetwork** [comment]
@pixelhandler good point.

But as I needed a bunch of properties on the parent component, I wound having to do the following:

In `templates/components/parent-component.hbs`
```handlebars
<!-- other stuff -->
{{yield this}}
```
In the templates where the components are used such as `templates/index.hbs`:
```handlebars
{{#parent-component as |parent|}}
  {{#each models as |child|}}
    {{child-component model=child parent=parent}}
  {{/each}}
{{/parent-component}}
```

Which is a bit reminiscent of how rails handles forms

**Comment by mixonic** [comment]
@foxnewsnetwork In Ember 2.3 the cases for yielding `this` will be much fewer- instead you can use [contextual components](http://emberjs.com/blog/2015/11/16/ember-2-2-released.html#toc_contextual-components) to create a closure over the private state you want those components to share.

I'm going to close this, and I doubt we will get much traction on adding `parentView` in for any particular hook. I strongly encourage you to explore the new component stuff @foxnewsnetwork :-)

Please re-open if I'm missing anything!
