### ISSUE TITLE
Ember.Object is `undefined`

### ISSUE THREAD

**Issue by rondale-sc** [emberjs/ember.js#12623]
Seems as if on canary `Ember.Object` is undefined. I discovered this when loading the following jsbin:

http://jsbin.com/qoyiyegava/edit?html,js,console

**Comment by rwjblue** [comment]
This is being caused by [this line](https://github.com/emberjs/ember.js/blob/6b3e6ea91f871cd55fe7215be8320b8d1c2ef77e/packages/ember-runtime/lib/system/namespace.js#L221):

```javascript
Mixin.prototype.toString = classToString;
```

In combination with [sealing](https://github.com/emberjs/ember.js/blob/6b3e6ea91f871cd55fe7215be8320b8d1c2ef77e/packages/ember-metal/lib/mixin.js#L505) inside `Mixin`'s `init`.

**Comment by rondale-sc** [comment]
Was able to reduce the jsbin's complexity a bit and still show the issue:

http://jsbin.com/dipipe/2/edit?html,js,console,output

**Comment by rwjblue** [comment]
After more toying around with this, the issue is with the load order of modules.

Working Demo: http://jsbin.com/kijavi/edit?html,js,console
Failing Demo: http://jsbin.com/yebonov/edit?html,js,console

---

Working:

```
<script src="http://builds.emberjs.com/canary/ember.debug.js"></script>
<script src="http://builds.emberjs.com/canary/ember-template-compiler.js"></script>
```

Failing:

```
<script src="http://builds.emberjs.com/canary/ember-template-compiler.js"></script>
<script src="http://builds.emberjs.com/canary/ember.debug.js"></script>
```

**Comment by rwjblue** [comment]
Basically, if `ember-template-compiler.js` (which only includes ember-metal, and not runtime) is loaded first then `ember-runtime` modules are loaded and try to add `toString` property to `Mixin` after its `init`.

**Comment by rondale-sc** [comment]
This wouldn't affect ember-cli applications then?

**Comment by rwjblue** [comment]
@rondale-sc - Correct.

**Comment by rondale-sc** [comment]
Interesting.  Is this a bug then?  Globals still work if specified in the correct order.  Should I close?

**Comment by rwjblue** [comment]
@rondale-sc - I am unsure. It is definitely not wonderful that what used to work now does not work.

**Comment by rondale-sc** [comment]
True, but I'm not sure how you'd get the `seal` effect without order dependence.

**Comment by krisselden** [comment]
Honestly I think we should just drop this for Mixins, it is rare in the ember cli world to assign them to a Namespace.

**Comment by krisselden** [comment]
@rwjblue do we strip 'use strict' in debug builds?

**Comment by krisselden** [comment]
so, I understand now what is going on, I didn't catch this because debugSeal is normally a noop, it is the template compiler that makes it not a noop.  I intended to do this, but I would have caught this error if the debug functions actually worked via the module import.

**Comment by rwjblue** [comment]
We strip use strict only on a small number of modules (5 I think?) as a work around to a nasty iOS bug.

**Comment by knownasilya** [comment]
Is this a related bug? https://github.com/firebase/emberfire/issues/340#issuecomment-163327747
