### ISSUE TITLE
Migrate application on hosting

### ISSUE THREAD

**Issue by sun-ks** [emberjs/ember.js#12639]
Hello. I recently started studying Ember.js. I installed Ember as stated in the manual(http://guides.emberjs.com/v2.1.0/getting-started/#toc_installation), and began to write using - <code>npm install -g ember-cli</code>. I wrote a small application example - hello world. How to run it without <code>ember serve</code>. I  tried copy folder - my-ember-app/dist in my test web server, but  it not work.

**Comment by stefanpenner** [comment]
We may be missing some docs on this topic.

**Comment by stefanpenner** [comment]
May actually be something to open on https://github.com/emberjs/guides

**Comment by locks** [comment]
We have a [Deploying](https://guides.emberjs.com/v2.5.0/tutorial/deploying/) guide on the tutorial at the moment. If you have improvement suggestions @sun-ks, please report issues to the repository stefan linked to above.
