### ISSUE TITLE
Action bubbling weirdness

### ISSUE THREAD

**Issue by courthead** [emberjs/ember.js#12632]
https://ember-twiddle.com/acd757144a86b00e3b81?numColumns=1

It seems that setting `bubbles=false` on the action helper used in template only works if `onclick=` is not specified on the target element or any of its parents. See attached Twiddle (look at application.hbs).

Is this intentional behavior or a bug? If intentional, it's a bit counterintuitive and probably should have some documentation around it, I think.

**Comment by rwjblue** [comment]
I do not believe that `bubbles` is a valid hash argument for closure style actions. We should update the docs to ensure that is clear.  

To make this work, you would need to create a wrapper helper to call `event.stopPropagation()`.

Example: https://ember-twiddle.com/d23e628ca75ae0fba16a?numColumns=1

**Comment by rwjblue** [comment]
I'm labeling this as a documentation issue...

**Comment by courthead** [comment]
Okay, thanks

**Comment by sweatypitts** [comment]
I'll take a shot at this.

**Comment by sweatypitts** [comment]
@rwjblue @mixonic This can be closed now, resolved in the above PR.

**Comment by rwjblue** [comment]
Awesome, thank you!
