### ISSUE TITLE
Can factoryFor cache misses? 

### ISSUE THREAD

**Issue by SamSaffron** [emberjs/ember.js#12634]
I am noticing tons of work in Discourse due to the way we internally use/abuse of the resolver. 

```
   var viewClass = Discourse.__container__.lookupFactory('view:' + templateName);
    if (viewClass) {
       params.view = viewClass.create(params);
    }
```

Internally `factoryFor` tries hard to cache the name of the factory, however it does not cache any information about misses. This mean that when we do hit a pathological case where a we keep looking up missing factories a very slow path is hit. 

Should missed be cached internally in Ember? 

cc @eviltrout

**Comment by stefanpenner** [comment]
The trick is finding/wiring up the eviction policy for those lazy loading.

**Comment by SamSaffron** [comment]
for the time being I took care of one big pain spot here: https://github.com/discourse/discourse/commit/7038d5f1c400d77dc8016a6279dc15ed8ceb5893

totally follow that lazy load is an issue.

**Comment by rwjblue** [comment]
We do cache misses for [resolve](https://github.com/emberjs/ember.js/blob/v2.2.0/packages/container/lib/registry.js#L726-L740), which is [checked early](https://github.com/emberjs/ember.js/blob/v2.2.0/packages/container/lib/container.js#L210-L216) in `factoryFor` (before any "real" work is done).  

I agree with @stefanpenner that cache miss eviction is definitely a problem, and we will likely have to expose an API for clearing [these caches](https://github.com/emberjs/ember.js/blob/v2.2.0/packages/container/lib/registry.js#L727-L737) when we actually make the lazy loading story better.

**Comment by rwjblue** [comment]
Unless this is being tested on a branch other than Discourse, y'all are [running Ember 1.12](https://github.com/discourse/discourse/blob/master/Gemfile#L32) which [does not cache misses](https://github.com/emberjs/ember.js/blob/v1.12.1/packages/container/lib/registry.js#L745-L746).

**Comment by SamSaffron** [comment]
@rwjblue great to know... I really want Discourse to dual boot with latest just need to find the time to make it happen, we would totally move to a new Ember if it is faster.

**Comment by rwjblue** [comment]
>  I really want Discourse to dual boot with latest

Yeah, definitely would be great to get y'all testing things out earlier so we can spot these sorts of issues before they ship in a version.

> we would totally move to a new Ember if it is faster

Indeed. We are definitely working on it.

**Comment by rwjblue** [comment]
I'm going to close this, since the suggestion (cache misses) is already implemented and released.

**Comment by SamSaffron** [comment]
No probs! Awesome this is improved in latest!
