### ISSUE TITLE
targetObject in integration tests on components

### ISSUE THREAD

**Issue by spruce** [emberjs/ember.js#12633]
Hey,
since Version 2.2.0 I'm not getting the testsuite for my ember-addon (https://github.com/piceaTech/ember-rapid-forms) to run. 
The problem I think lies that it doesn't get the correct targetObject from the test environment. 
To verify that I did some steps:
1. I added a debug statement just before using it
 ```
console.log(this.get('targetObject'), this.get('_targetObject'), this.get('action'), this.get('targetObject.model.asd'), this.get('targetObject').send);
```
2. Inside ember.debug.js ( inside ```targetObject: _emberMetalComputed.computed('controller', function (key) {```)
```
console.log('next');
      console.log(this._targetObject, this._controller);
```
Which yields the following results:
In Version 2.1.1:
<img width="1241" alt="2 1 1" src="https://cloud.githubusercontent.com/assets/709002/11317380/0299ffbe-9092-11e5-9054-6b7ce6d6d4bd.png">

Version 2.2.0
<img width="1241" alt="2 2 0" src="https://cloud.githubusercontent.com/assets/709002/11317383/13e9f3f0-9092-11e5-8648-903f2df9c8d8.png">

I think something is wrong there, right?
I can't create twiddle for this, because it needs the testing environment. With normal usage I don't get any errors.
Repo: https://github.com/piceaTech/ember-rapid-forms
Travis where this manifests: https://travis-ci.org/piceaTech/ember-rapid-forms/builds/91721364

Cheers
Spruce

**Comment by krisselden** [comment]
As far as I know, `targetObject` was not only private but undocumented.  I think this at one point though made it into some testing guides or maybe it was just an ember-cli test generator?  I'm not certain, maybe @rwjblue can shed more light.

**Comment by spruce** [comment]
I did change it to just call this.sendAction() and after some strange behaviour upgraded ember-cli-qunit to 1.0.4 and after that everything now works like a charm.
