### ISSUE TITLE
Observe DOM attribute changes

### ISSUE THREAD

**Issue by mahdaen** [emberjs/ember.js#12642]
Guys,

I'm trying to work with Ember 2x and Polymer 1x. 

**Polymer Element**

```hbs
<dom-module id="test-elm">
    <template>
        <p id="polymer-text">{{firstName::change}}</p>
        <input id="polymer-input" type="text" value="{{firstName::input}}">
    </template>
    <script>
        Polymer({
            is         : 'test-elm',
            properties : {
                firstName : {
                    type               : String,
                    notify             : true,
                    reflectToAttribute : true
                }
            }
        });
    </script>
</dom-module>
```

**application.hbs**
```hbs
<test-elm first-name="{{myName}}"></test-elm>
<p id="ember-text">{{myName}}</p>
{{input id="ember-input" type="text" value=myName}}
```

**application.js**
```js
import Ember from 'ember';

Ember.TextField.reopen({
    attributeBindings : [ 'value' ]
});

export default Ember.Controller.extend({
    myName     : 'John Smith'
});
```

When the page loaded, all `p` text and `input` values is `John Smith`. When I change the `input#ember-input` value to `Michael Smith`, all `p` and `input#polymer-input` is changed. But when I change the `input#polymer-input` value, only the `p#polymer-text` that changed.

So, my question is, how to observe the `first-name` attribute changes on the `<test-elm first-name="{{myName}}"></test-elm>` to makes the ember data changed after changes by `input#polymer-input`?

Thanks!

**Comment by krisselden** [comment]
The polymer element needs an event for the change and you can use the action helper to make a function to update the value from the event.

**Comment by krisselden** [comment]
Unfortunately, outside of polymer, to use the notify: true setting, you need to get a handle to the element so you can do `el.addEventListener(''firstName-changed", firstNameChanged )`.  If you have a component for this route it could add an event listener on didInsertElement.

**Comment by locks** [comment]
I am closing this issue as this does not seem like a bug in Ember.js and @krisselden provided a way forward in his comment bove.
Feel free to re-open the issue if you think it's still justified, thank you!
