### ISSUE TITLE
Add DS.Store base delegate method to the adapter

### ISSUE THREAD

**Issue by teckays** [emberjs/ember.js#12645]
I'm wondering if I need to extend the `DS.Store` class in order to add a query method like `this.store.search()` for example, would it be possible on the current version? 

This need comes from the fact that I have a `JSONAPIAdapter`-like backend API but with some minor changes.  For example I have a custom route to perform searches on the model `/{model}/search` and none of the existing methods, `findAll()`, `query()` and others help me achieve this functionality without overriding some of them which is not something I really like. 

The build-in `this.store.query()` method works great if I want to query on a specific model field, but for `search()` I'm using a `text` parameter which looks over multiple model fields to find a match.

The best approach in my opinion would be to extend the `DS.Store` class and add a `this.store.search()` method for example that would allow me to automatically search for records on any model.

**Comment by stefanpenner** [comment]
ember-data resides [here](github.com/emberjs/data) typically we encourage Q/A still issues be opened on stackoverflow or the forums.

**Comment by teckays** [comment]
@stefanpenner it supposed to be more like an improvement rather than Q/A. But thank you for pointing me out. Cheers.
