### ISSUE TITLE
URL changes before model is resolved

### ISSUE THREAD

**Issue by adambuczynski** [emberjs/ember.js#12655]
In Ember 1.13.10

For certain routes in our app, the URL of the browser changes before the route's model promise is resolved. This results in some odd behaviour. I would expect the URL to only be changed if the transition actually succeeds.

The transitions log also doesn't make much sense, as it says the app transitioned into stateA whereas it was preparing to transition to stateB:

```
Transitioned into 'stateA'
Preparing to transition from 'stateA' to ' stateB'
Transitioned into 'stateA' //Why stateA? I thought preparing to transition to stateB?
```

It seems to only affect routes which have queryParams defined in the controller.

**Comment by rwjblue** [comment]
Can you provide a demo that we can use to see what you are seeing? This is going to be hard to help on without one...

**Comment by adambuczynski** [comment]
Unfortunately I can't share the actual code as it's a proprietary and sensitive project... I can try to create a snippet on JS bin, but I don't know if I'll manage to reproduce it in an isolated setting.

For now, I've removed the queryParams from the controller, so that we don't run into this issue anymore.
