### ISSUE TITLE
Data binding not ready in `didInitAttrs`

### ISSUE THREAD

**Issue by ohcibi** [emberjs/ember.js#12654]
I'm trying to set properties in a `didInitAttr` hook of a component which should be visible in both the components template and the containing template. See this example: https://ember-twiddle.com/3059bc31648fe4b0a9cb

No matter if I trigger the change on the outside (DDAU with sendAction) or simply use 2way binding of curly components the change is always visible in only one of the templates.

The problem goes further in my app where the property is an array which is initially empty and receives an object in `didInitAttrs`. This is visible at least in the component as long as nothing gets rerendered. When the component gets rendered again, the binding suddenly overwrites what was set in the observer. Nothing changed the arrays contents, its just that the initial (empty) value, which was not updated because of the binding being not ready, now finally binds to the property in the component.

**Comment by GendelfLugansk** [comment]
I faced similar problems with `didInitAttrs` hook

**Comment by mixonic** [comment]
@ohcibi you setting `foo` on the controller but passing `foo=bar` to the component.

The [corrected twiddle](https://ember-twiddle.com/30adb673d195a6ecfa46) however confirms that emitting and action does not "work" during `didInitAttrs` which is basically just `init`. In fact I strongly encourage you to use `init` over `didInitAttrs` in every case. The timing of `didInitAttrs` is confusing.

Using `willInsertElement` will allow you to send an action. However I do not encourage you to build components this way: The application is in the middle of rendering, and going back to make fruther changes to state will cause an expensive/slow second render. Ember will in fact fire a warning when you do this.

Instead build components that reflect state, and have the parent reflect that same state. The presence of a child component should not alter the behavior of a parent, instead both the presence of the child and behavior of the parent should be reflections of a single source of truth.

I doubt we will do any work to ensure `sendAction` works during `init`.

**Comment by ohcibi** [comment]
@GendelfLugansk Could you elaborate your problems, to see how they differ to mine? My solution with the action actually was a work around. I'm rather concerned about the binding itself.

@mixonic I knew I would confuse some of those, but as you've seen, the problem is there. I have solved this problem now just the way you said it, by using DDAU.

But some questions remain

1. You're encouraging using `init` over `didInitAttrs` - why was the latter introduced then? The blog post reads like this is a new way to do (better) DDAU.
2. Will the binding be fixed in `didInitAttrs`? The name of that hook totally implies that the binding is the last thing that won't work in it. `didInitAttrs` is not throwing any warnings when setting properties like `didInsertElement` does; so it appears to be the right place to set attributes. But as shown it won't work with bound properties.

**Comment by mixonic** [comment]
> 1/ You're encouraging using `init` over `didInitAttrs` - why was the latter introduced then? The blog post reads like this is a new way to do (better) DDAU.

Not everything goes perfectly the first time around ;-) In general the hooks have been deemed quite immature, and probably will continue to be immature until glimmer components land.

> 2. Will the binding be fixed in `didInitAttrs`? The name of that hook totally implies that the binding is the last thing that won't work in it. `didInitAttrs` is not throwing any warnings when setting properties like `didInsertElement` does; so it appears to be the right place to set attributes. But as shown it won't work with bound properties.

I very much doubt we will add support for sending actions during `didInitAttrs`. All the hooks are hooks because of timing, right? For instance you expect there to not be an element during `willInsertElement` and an element to be present during `didInsertElement`. Well, it turns out another thing to expect is that you cannot send an action during `init`, and `didInitAttrs` happens during `init`. This is the nature of the hook, if it was after sending actions was available that would be later than we would like.

And again, the whole pattern of sending an action from a hook during init/render is to be avoided. These are two very strong reasons for us not to add the support you've asked to see.

I've seen no examples of "bound properties" here. However if they need to flow upstream, they are basically following the same anti-pattern described for sending actions.

**Comment by ohcibi** [comment]
@mixonic in the example there is a commented-out hook that sets the property directly instead of sending the action.

Please forget about the action, I am concerned about the binding (as it says in the issue-title). The action in fact actually even works (i.e. gets triggered). What is not working is the binding; no matter from which direction, thats why I put both directions into the example while commenting one out.

I understand that data up is an anti-pattern but as far as I understood 2way binding will nevertheless still be available via opt-in and I'd say that the attribute-binding (again: iff available) should simply work in a hook called didInitAttrs.

**Comment by GendelfLugansk** [comment]
@ohcibi I tried to set property inside `didInitAttrs` and failed. For now I moved my code to `didInsertElement` and thinking about sending an action instead of setting a property value.

**Comment by locks** [comment]
I am closing this issue because `didInitAttrs` was removed from the API for plain `init`.
Feel free to re-open the issue if you think it's still justified, thank you!
