### ISSUE TITLE
Add an assertion on the each helper param.

### ISSUE THREAD

**Issue by spectras** [emberjs/ember.js#12650]
The `{{#each}}` helper takes the first positional parameter as the list to iterate on, and silently ignores additional positional parameters. This can [make it harder](http://stackoverflow.com/questions/33926550) for beginners to see mistakes.

I suggest adding an assertion on `params.length` in the helper.

**Comment by rwjblue** [comment]
Ya, we should definitely have an assertion when you use `{{#each foo in bar}}` syntax.

Demo here: https://ember-twiddle.com/fe0ebffe18447aba9926
