### ISSUE TITLE
Spread helper

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/ember.js#12658]
I have a component that wraps `link-to`. Currently it only supports one model:
```hbs
{{! route/template.hbs }}
{{my-component route=route model=model}}
```
```hbs
{{! my-component/template.hbs}}
{{link-to route model}}
```

Supporting two model is not to hard:
```hbs
{{! route/template.hbs }}
{{my-component route=route model=firstModel sub-model=secondModel}}
```
```hbs
{{! my-component/template.hbs}}
{{link-to route firstModel secondModel}}
```

However, I don't see a cheap and obvious solution to support a dynamic number of models (hence the `spread` helper proposition)
```hbs
{{! route/template.hbs }}
{{my-component route=route models=models}}
```
```hbs
{{! my-component/template.hbs}}
{{link-to route (spread models)}}
```

- Is there an existing way for me to achieve my requirement?
- How feasible is the implementation of a spread helper? Intuitively it feels like the Ember templating framework doesn't allow that

**Comment by stefanpenner** [comment]
we have been talking about a splat or similar primitive for the template layer to accomplish this.

something like (but this is an early sketch, don't assume me saying this means this is the final form):
```
{{link-to route *models}}
```

i think @mmun had some ideas

**Comment by mmun** [comment]
This is a good use case.

**Comment by mmun** [comment]
There is some discuss at https://github.com/wycats/handlebars.js/issues/1050.

I'd like to see `*` for params spreading and `**` for hash spreading.

**Comment by rwjblue** [comment]
Link to with dynamic number of models is already possible as of 2.0.2 (but not as ergonomic). Will share JSBin shortly.

**Comment by rwjblue** [comment]
http://rwjblue.jsbin.com/higeso/edit?html,js,output

**Comment by mmun** [comment]
:+1:.

**Comment by stefanpenner** [comment]
im going to close this, as further exploration here is likely rfc/rfc issue
