### ISSUE TITLE
Controller's replaceRoute method not appearing in the API documentation

### ISSUE THREAD

**Issue by veebs** [emberjs/ember.js#12660]
There is a link to the method from the `transitionRoute` api: http://emberjs.com/api/classes/Ember.ControllerMixin.html#method_replaceRoute

However, the method description does not exists even though the description exists in the source code: https://github.com/emberjs/ember.js/blob/v2.2.0/packages/ember-routing/lib/ext/controller.js#L41

**Comment by pixelhandler** [comment]
@veebs perhaps open a pull request to remove that link. the replaceRoute looks like its `private` https://github.com/emberjs/ember.js/blob/v2.2.0/packages/ember-routing/lib/ext/controller.js#L120-L181

**Comment by jankrueger** [comment]
@pixelhandler Do you really want to remove the link? It is working fine for me. Otherwise i will create a pull request.

**Comment by locks** [comment]
I am closing this issue because OP's problem is they didn't have the private filter turned on. This behaviour is also being tweaked in the upcoming API viewer.
Feel free to re-open the issue if you think it's still justified, thank you!
