### ISSUE TITLE
if helper in tag's attributes crashes with exception

### ISSUE THREAD

**Issue by ruz** [emberjs/ember.js#12661]
example: https://ember-twiddle.com/4ce71c4414f44f11a6b8

```
$ ember version
version: 1.13.13
node: 4.2.2
npm: 2.14.10
os: darwin x64

ember 2.2.0
ember-data 2.2.1
```

**Comment by rwjblue** [comment]
This isn't really a bug, using `{{if}}` in element space is not allowed.  You can use the inline version of `{{if}}` in an element with assignment to an attribute though.

Using your demo, that would look like: 

```hbs
<br hidden={{if x "hidden" null}}>
```

The `null` value when falsey means the attribute will be removed.

**Comment by mmun** [comment]
a "to boolean" helper would make that a bit cleaner. `<br hidden={{bool x}}>`

**Comment by ruz** [comment]
Ok, then a wordy assert would save me tons of time. Runtime or compile time error, I don't care, but a human readable thing.

**Comment by ruz** [comment]
Ended up with:
```handlebars
hidden={{unless x true}}
```

**Comment by mmun** [comment]
@ruz absolutely agree with you there!

**Comment by trek** [comment]
@mixonic is this a warning that Glimmer should contain? If so, can we move this issue over there?

**Comment by mixonic** [comment]
@trek improving the error seems like a glimmer thing, adding a `bool` to Ember doesn't seem like something too controversial, but it needs discussion.

**Comment by GavinJoyce** [comment]
While not perfect, the runtime error for `<br {{if x "hidden" ""}}>` in Glimmer 2 is much better:

**Ember 2.10.beta.3:**

<img width="738" alt="screen shot 2016-11-26 at 12 45 26" src="https://cloud.githubusercontent.com/assets/2526/20640469/8289f77a-b3d6-11e6-9c49-f1c0d6fc69db.png">

**Ember 2.9:**

<img width="682" alt="screen shot 2016-11-26 at 12 46 57" src="https://cloud.githubusercontent.com/assets/2526/20640472/9b064394-b3d6-11e6-8228-c6b35a7ab04a.png">

**Comment by rwjblue** [comment]
Awesome, thanks @gavinjoyce!
