### ISSUE TITLE
Errors Thrown in Route Model Hooks Don't Hit Global Handler

### ISSUE THREAD

**Issue by jherdman** [emberjs/ember.js#12669]
I'm try to track down some issues with error handling and reporting, and it was brought to my attention via jherdman/ember-cli-trackjs#33 that errors thrown in the various model hooks don't hit the global error handler.

JSBin: http://emberjs.jsbin.com/lezekod/edit?js,console,output

**Comment by fivetanley** [comment]
This seems to be a bug in 1.13, but not 2.2.0 http://emberjs.jsbin.com/towewiqoja/1/edit?html,js,console,output

**Comment by rwjblue** [comment]
Confirm it was fixed in 2.1, but introduced another issue (being tracked in another issue/pr).

**Comment by fivetanley** [comment]
What's the issue/pr?

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/12549

**Comment by lolmaus** [comment]
Also this one is related to route errors: https://github.com/tildeio/router.js/issues/174

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
