### ISSUE TITLE
better way getting query params from router?

### ISSUE THREAD

**Issue by TangMonk** [emberjs/ember.js#12663]

**Comment by nightire** [comment]
@TangMonk 上次应该有人已经提醒你了，你这种问题是属于“如何使用”的范畴，而不是 Ember 自身的 Bug／缺陷／改进等等。

因此，此类问题请发到 SO／Slack 等地方寻求帮助，不要再发到 Github Issues，因为：1）这样的问题即使被看到也很少有机会得到答案；2）这样的问题只会干扰 Ember 的正常开发，于人于己都是弊大于利。

如果你不知道合适的地方在哪里，Ember 的官网上有集合很多丰富的资源链接：http://emberjs.com/community/

如果你担心英文沟通的问题，也可以发到 segmentfault.com 去，那里都是中文开发者。

**Comment by TangMonk** [comment]
@nightire , ok, thanks

**Comment by nightire** [comment]
@TangMonk Have you ever read the official documentation?

http://emberjs.com/api/classes/Ember.Route.html#method_model

**Comment by lcoq** [comment]
@nightire Will it help @TangMonk ? I do not see any `queryParams` remark into the link you gave

**Comment by TangMonk** [comment]
@nightire , thanks !

I got, I can get transition from second parameter
