### ISSUE TITLE
difference in layoutName behavior in 2.0.2 and 2.1

### ISSUE THREAD

**Issue by jcope2013** [emberjs/ember.js#12670]
I expect the bs-input component to show up in the template by changing out the layoutName in the init of another component

2.1, setting layoutName does nothing, bs-input component not rendered in template

https://ember-twiddle.com/70a5b77b6b7bb24976a0

2.0.2, setting layoutName works, bs-input component rendered in template

https://ember-twiddle.com/dad06f08b25c2ae1bd54

I believe it was related to this, is this intentional or a regression? https://github.com/emberjs/ember.js/pull/12299 

is there a new way to do this without having to use the component helper?

**Comment by rwjblue** [comment]
Work around for now is to set `layoutName` before calling `this._super`, but I believe that this is a regression we should fix.

**Comment by jcope2013** [comment]
this is still present in ember 2.5, the workaround still works properly

https://ember-twiddle.com/43c370747fc6c440e723b3d533c6da93

**Comment by jcope2013** [comment]
fixed in 2.8

https://ember-twiddle.com/9ecc420a620984e6874889454f7fd6d9?openFiles=twiddle.json%2C
