### ISSUE TITLE
actions has no access to event what is vital for some event types

### ISSUE THREAD

**Issue by ruz** [emberjs/ember.js#12679]
Without event ```{{action "x" on="keyDown"}}``` just makes no sense and other key event actions.

**Comment by pixelhandler** [comment]
@ruz have you asked about access to event using actions in the slack channel?

**Comment by ruz** [comment]
I have. Handlers on components are ok, but catch events from any elements within the comp. At the end ended up using ```onkeydown={{{action "x"}}```.

**Comment by ruz** [comment]
Just closed? It's perfectly valid issue. Still hasn't been addressed in the code neither in [https://guides.emberjs.com/v2.4.0/templates/actions/#toc_specifying-the-type-of-event](documentation). It's quite disturbing considering that the document mentions keyPress as example.

**Comment by rwjblue** [comment]
Closure actions get the event passed in, this is no longer an issue.
