### ISSUE TITLE
{{action}} as value of onxxx attribute crashes with exception

### ISSUE THREAD

**Issue by ruz** [emberjs/ember.js#12676]
demo: https://ember-twiddle.com/3213fd40aed2c0055799

focus on the input, exception in the console, Chrome browser

documented:
http://guides.emberjs.com/v2.0.0/templates/actions/#toc_modifying-the-action-s-first-parameter
http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_action

**Comment by mixonic** [comment]
`onfocusin` is not present on the element as an accessor:

![](https://api.monosnap.com/rpc/file/download?id=PHWNhuuIsSGhwRxTBUc0N3Kyxus9lt)

This means it is treated as an attribute and the stringified version of the function is being set, thus a syntax error. `<input onfocusin="console.log('foo')">` does work in Chrome.

@ruz the immediate workaround is to attach the event via jquery or native APIs in a wrapping component. We're looking at fixes to this part of Ember right now. [related RFC](https://github.com/emberjs/rfcs/pull/100)

**Comment by ruz** [comment]
Ok. onfocus and onblur work without exception. I've spent too much time in ember docs that I forgot that this pair is not focusin/focusout. Closing this.

**Comment by mixonic** [comment]
I'm actually going to leave this open @ruz, I think we need to land some work from the RFC before this would be addressed. It should have worked as expected IMO.

**Comment by ruz** [comment]
Agree. Discovered that focusIn/focusOut actually are part of DOM Level2 Events spec and slightly different from focus/blur pair.

I'm ok with focus/blur pairs and going to stick with ```onfocus={{action "focus}}``` syntax. RFC says it's the future, action receives event and I really like idea of keeping all interactions with events under actions rather than as methods on the control.

**Comment by pixelhandler** [comment]
@mixonic is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by ruz** [comment]
Just checked, this is still an issue and reproducible.

**Comment by locks** [comment]
Failed to reproduce in 3.4. Thanks for the feedback!
