### ISSUE TITLE
Guide: Tutorial - Ember Data

### ISSUE THREAD

**Issue by webgear** [emberjs/ember.js#12684]
Hello everybody,

I am trying to start with Ember and of course, I am going through the official guide. It's been all good so far, but there's a problem when adding Mirage into the mix. Specifically on this step: http://guides.emberjs.com/v2.2.0/tutorial/ember-data/

The errors I get are as follows:

```
Deprecations were detected, see the Ember Inspector deprecations tab for more details.
```

So I go do just that, and I see:

```
You are currently using the default DS.RESTAdapter adapter. For Ember 2.0 the default adapter will be DS.JSONAPIAdapter. If you would like to continue using DS.RESTAdapter please create an application adapter that extends DS.RESTAdapter.

The default behavior of shouldReloadAll will change in Ember Data 2.0 to always return false when there is at least one "rental" record in the store. If you would like to preserve the current behavior please override shouldReloadAll in your adapter:application and return true.
```

I assume those are only warnings, so I ignore them. But then there's an error too:

```
Mirage: Your Ember app tried to GET 'http://localhost:4200/assets/vendor.js', but there was no route defined to handle this request. Define a route that matches this path in your mirage/config.js file. Did you forget to add your namespace?
```

I followed the guide line by line, and only after adding Mirage and decoupling the hardcoded rentals array I get this error and no component is displayed what so ever. The data, however, gets pulled correctly from /rentals, but just won't be correctly mapped to the templates so I can use it.

Please help! Thanks.

**Comment by ptgamr** [comment]
@webgear it seems like your Mirage response does not returned as JSON API compliant, but REST compliant

If you still still want to use RESTAdapter, you should create a file `/app/adapters/application.js` which extends RESTAdapter:

```
///app/adapters/application.js
import DS from 'ember-data';

export default DS.RESTAdapter.extend({
  namespace: 'api'
});

```

**Comment by ptgamr** [comment]
You can read more about different types of Adapters here: http://guides.emberjs.com/v2.2.0/models/customizing-adapters/

**Comment by webgear** [comment]
@ptgamr Thanks for the response, that helped indeed. I had to rename a couple of things, but I got it working eventually (renamed data to rentals in mirage config, removed attributes & type subkeys). But I thought that the JSONAPIAdapter was used by default in Ember, and I find that this is not really the case. Either that, or my current Ember install didn't default to it for some reason.

After looking into the adapters a bit more, I have changed the app/adapters/application.js file to look like so:

```
import DS from 'ember-data';

export default DS.JSONAPIAdapter.extend({
  namespace: 'api'
});
```

And after that, the data structure returned by Mirage was correctly interpreted. Maybe this should be mentioned in the guide as well, so that future users won't get this bug, which could hinder their progress in learning this framework.

Thanks again. Cheers!

**Comment by nightire** [comment]
@webgear the answer for your last problem is in the documentation of Mirage itself, basically you don't need to uninstall it, instead, you need to change some configurations, read the manual carefully.

**Comment by mixonic** [comment]
This is not an issue with Ember.js, and is better brought up on StackOverflow, discourse, or the Slack channel. Thanks!

**Comment by sergiotapia** [comment]
@mixonic Can the guides be updated? I just ran into this exact same issue. Just following the guides from A to Z and hit this roadblock. :+1:

**Comment by mixonic** [comment]
@sergiotapia yeah, please open an issue or PR on https://github.com/emberjs/guides. I haven't looked at this closely and I'd prefer the someone who can explain the problem to describe it well.

Thanks! :-)
