### ISSUE TITLE
Ember.isArray return true for FileList object

### ISSUE THREAD

**Issue by joelcox** [emberjs/ember.js#12688]
Passing a FileList object to Ember.isArray returns true, even though it does not behave like an Ember Array/Enumerable. I'm not sure if this is within the scope of Ember.

JSBin: [http://emberjs.jsbin.com/ricokobotu/8/edit?js,console,output](http://emberjs.jsbin.com/ricokobotu/8/edit?js,console,output)

Interesting bit from the [File spec](http://www.w3.org/TR/file-upload/#filelist-section):

> The FileList interface should be considered "at risk" since the general trend on the Web Platform is to replace such interfaces with the Array platform object in ECMAScript [ECMA-262]. In particular, this means syntax of the sort filelist.item(0) is at risk; most other programmatic use of FileList is unlikely to be affected by the eventual migration to an Array type.

**Comment by pixelhandler** [comment]
@joelcox yeah seems like `Ember.isArray()` has a bug; using `Array.isArray(files)` is false. Perhaps avoid Ember.isArray() for now.

**Comment by mmun** [comment]
We should fix this bug. Ember.isArray is useful because it can be used to detect an `ArrayProxy`, whereas `Array.isArray` cannot.

**Comment by joelalejandro** [comment]
@mmun There was a fix apparently, but it didn't pass CI for IE9, for what I read in referenced PRs.

**Comment by mixonic** [comment]
The approach in https://github.com/emberjs/ember.js/pull/12708 seems quite legit
