### ISSUE TITLE
Bug or Feature? (run loop, render engine)

### ISSUE THREAD

**Issue by azsam** [emberjs/ember.js#12683]
Hello,

we have an array of ember objects which we render in a template with the component helper as follows:

```
{{each objects as |obj|}}
   {{component obj.name}}
{{/each}}
```

Now as we replace the array with another one that contains new objects and some of the old ones - the components which had underlying old objects are never destroyed, they show in the right order instead. Ember somehow figures out that the components render the same object and doesn't destroy them. Is that an expected behaviour?

Example:

Functions:

```
renderInitialObjects: ->
   objects = [ Obj1, Obj2, Obj3]
   @set 'objects', objects

stateChanged: ->
  
  objects  = [Obj4, Obj5, Obj1] //New Array
  @set 'objects', objects
```
 
In this case on 'stateChanged' Ember wouldn't render a new component with underlying Obj1, but will use the old one instead.

**Comment by mixonic** [comment]
@azsam this is indeed expected, and required for reasonable performance. If the model is the same, the component does not need to be destroyed/created and work is conserved.

You can change this behavior by using the `key=` option on `{{each}}`. Please see http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_each and feel free to look for more guidance on the StackOverflow, the Slack channel, or http://discuss.emberjs.com/
