### ISSUE TITLE
Poor performance during the initial render on the Android devices

### ISSUE THREAD

**Issue by dmagunov** [emberjs/ember.js#12689]
Good day,
At this  moment, our company developing  three applications with Ember (versions 1.12 and 2.2). Now we faced with the problem of the poor performance during the initialial render of the Ember application (version 2.2) on Android devices. I know that with Glimmer engine Ember made gains in the speed of update state, but loses performance of initialization state. And, accordingly to this, my question to the core team: have you plans to rewrite glimmer engine in order to increase performance of the initial render state of the application, and if so, when it is planned (in what Ember version)?

Thank you very much for your understanding.

**Comment by rwjblue** [comment]
We are working on a rewrite of the rendering engine.

* https://www.youtube.com/watch?v=DrFXw0QGDLM - @wycats describing the new system 
* https://github.com/tildeio/glimmer - The new repo (replacing tildeio/htmlbars repo)

There is no specific targeted Ember version, it will land in an Ember version when it is ready.

**Comment by dmagunov** [comment]
Thanks @rwjblue for quick response. I see that the new glimmer engine that You have been mentioned is in the early stage of development. Do You have any thoughts when it will be ready for release (month, two or maybe year)? I need this information for making right choice about  our development environment.

Thanks!

**Comment by rwjblue** [comment]
In my experience estimates and free software are generally a very bad pairing :smiling_imp: 

I can say that we are working as quickly as possible on the integration efforts, and I would expect a feature flag that can be used on canary by around the 2.5/2.6 canary cycle.  Perhaps that is completely finished by then, perhaps that is only the beginning, I'm not sure (and don't want to get yelled at for being wrong ;P ).

**Comment by mixonic** [comment]
@dmagunov Android/Chrome V8 performance is about more than just rendering. This discussion is perhaps useful:

https://meta.discourse.org/t/the-state-of-javascript-on-android-in-2015-is-poor/33889

In general this kind of discussion is probably better for http://discuss.emberjs.com/ or the Slack channel.

**Comment by wycats** [comment]
I wouldn't say it's in an early stage of development at all, but
integration with Ember has not quite begun (maybe that's what you mean?)

We have all of the core semantics complete, and a number of tests copied
from the Ember repository that test edge-cases already passing.

Keep an eye out!

**Comment by dmagunov** [comment]
Thanks guys!
