### ISSUE TITLE
Error thrown in ApplicationRoute cannot load error substate

### ISSUE THREAD

**Issue by gkaran** [emberjs/ember.js#12695]
I don't know whether that is something new or intentional but I came accross it and wanted to report it.

In my ApplicationRoute I have some data initialization in the beforeModel and model hooks (fetch data from the server) in order to display the base sceleton of the application. In the case that the server is not responding (server is down) and I get an error back instead of seeing the error (or application.error substate) the error gets logged in the browser's console and page is empty.

Showing the error substate works perfectly in any other route.

For demonstration purposes I created a jsbin which you can find [here](http://emberjs.jsbin.com/texusobeha/edit?html,js,output).

**Comment by pixelhandler** [comment]
@gkaran see this ember-twiddle example… https://ember-twiddle.com/2814945560df1a5d000b the application-error template does handle an error from the model hook of the application route

(The error sub-states are a bit tricky, also one think I noticed is that either the route error action or the applicaiton-errror template can be used, not both.)

**Comment by acorncom** [comment]
Closing this for now, feel free to comment if we need to reopen
