### ISSUE TITLE
Issue in allowing a group of attributes for {{input}} helper of Emberjs

### ISSUE THREAD

**Issue by sourvb** [emberjs/ember.js#12697]
I am trying to use <code>attributeBindings</code> for allowing several attributes for input field. For validating the form, I am using jquery.validate plugin. Jquery.validate plugin uses more than twenty <code>data-rule-</code> attributes for all type of form fields including input field. 

The issue is, it is very tedious to find all the possible attributes supported by jquery.validate for each form field and bind them to the input helper. Here is my sample code:
<code>export default Ember.TextField.extend({</code>
<code>    attributeBindings: ['data-rule-required', 'data-rule-minlength', 'data-rule-number', 'data-rule-url', ..... ]</code>
<code>});</code>

It will be much easier if I can use something like this,
<code>export default Ember.TextField.extend({</code>
<code>    attributeBindings: ['data-rule-*']    // This should allow any attributes starting with "data-rule-" string</code>
<code>});</code>

**Comment by aars** [comment]
That would be a feature request. But I don't think it is very useful. Especially for this use-case. Tediousness isn't a very good argument for this kind of feature.

Creating your own `{{my-jquery-validate-input}}` with all know attributeBindings is the way to go imho. Otherwise I'd suggest passing in the options as one object. Something like this:

```
// var rules = {username: {required: true, minLength: 3}, password: {required: true, minLength: 5}};
{{my-jquery-validate-input name="username" value=model.username rules=rules.username}}
```

And parse those rules into `attributeBindings` on `init`.

**Comment by sourvb** [comment]
@aars 
In that case, I do not have to even parse the rules. I can directly pass the rule object to jquery.validate which will take care of that.

If this is a one-time job, tediousness wouldn't have been a good point. But the issue is with maintaining the components too. For example, I have to update the attributes of each of the form field components, whenever there is jquery.validate updates and include a new attribute. 

More than that, my project uses lots of <code>data-</code> attributes too on the UI. We are migrating the client from jsp to emberjs. In that case, the above feature will be a useful one, as you can understand.

Any other simpler way to extend all the form field component in a single js file or a simpler alternative would have been a better way too.

**Comment by aars** [comment]
I don't see the issue in maintaining the component. It is one component that supports/defines all your data-rule- attributes. When jquery.validate introduces new attributes you'd add them once to the component so that it supports it. That is the only extra work you'll have to do then, right? Since using these new attributes on an X amount of fields would always mean defining it X times with some value, it doesn't matter if you're defining them on HTML <input> elements or Ember {{components}}.

**Comment by sourvb** [comment]
Ok. I am trying to use something like this in a initializer. But the <code>data-</code> attributes are not showing up. According to http://guides.emberjs.com/v1.11.0/templates/binding-element-attributes/, I have tried using <code>Ember.keys</code>. But its deprecated in the ember version I am using (1.13.6).
```javascript
Ember.Component.reopen({
    _addDataAttributes: function() {
      var self = this;
      // Allow arbitrary data attributes
      Object.keys(this).forEach(function(key) {
        if (key.substr(0, 5) === 'data-') {
          self.get('attributeBindings').pushObject(key);
        }
      });
    }.on('init')
  });

**Comment by aars** [comment]
Interesting approach! 

`Ember.keys` was just a polyfill I think. This is good.

This worked for me:

```
    _addDataAttributes: Ember.on('init', function () {
      Object.keys(this).forEach((key) => {
        if (key.match(/^data-/)) {
          this.get('attributeBindings').pushObject(key);
        }
      });
    })
```

Using an arrow function there is no need for `self`, and I suspect it also has to do with why yours is not working. But I'm not sure.

**Comment by sourvb** [comment]
Ok. Thanks.

**Comment by aars** [comment]
@sourvb Did it work for you as well?

If your current problem is resolved, could you close this issue?

If you still want to request this as a feature, have a look here: https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature

**Comment by sourvb** [comment]
Actually for some reason it is not working for me. I've even tried with,
```javascript
Ember.TextField.reopen({

But I am not getting <code>data-</code> attribute in the list of Object.keys. I am using the input like this in the template.
```javascript
{{input value=model.username id="username" class="form-control" name="username" data-rule-required="true"}}

Do not have any clue of how to debug this stuff.

**Comment by pixelhandler** [comment]
@sourvb Sounds like some guidance from the community regarding input fields, validation, etc is the topic of this thread. This is not bug in Ember, and if you want to propose a feature the RFC issue or proposal is the way to go.

Have you already joined the ember-community.slack.com chatroom to seem out other options for this topic?

**Comment by sourvb** [comment]
Thank @pixelhandler and @aars. I'll check that out.
