### ISSUE TITLE
Nested routes and reset namespace oddities

### ISSUE THREAD

**Issue by juggy** [emberjs/ember.js#12702]
Please consider:
https://ember-twiddle.com/e30d73a32b81e40db356

First, the page does not load as `projects.buildings.show` is not defined. Which is weird. 

Now comment that link-to that fails. The page will load and you will be able to click on the standalone link. Do it.

Look at the url for that new page, it is now `/projects/buildings/1` but it should be `/buildings/1` because `projects.buildings.show` does not exist as per above.

Another weird thing: after removing the last route (projects) in the `router.js`, the new transitioned url is `/contacts/buildings/1`! So it seems the last route defined takes precedence.

If this is the normal behavior, it is really confusing. Also http://guides.emberjs.com/v1.13.0/routing/defining-your-routes/#toc_resetting-nested-route-namespace states that:
```
This allows you to reference and reuse a given route in multiple route trees as well as keep the class name short.
```

**Comment by SirZach** [comment]
Just as an FYI - removing <code>{resetNamespace: true}</code> in the router resolves some of these problems. I think it's bad karma to declare multiple routes as starting with the same name.

**Comment by juggy** [comment]
The goal here is to reuse the buildings route on all other route but not have to repeat the controllers, templates, etc. 

Pretty much what the guides say in the link I shared.

**Comment by rwjblue** [comment]
I believe that this is a duplicate of https://github.com/emberjs/ember.js/issues/11692.  

@juggy - Can you confirm, and close if it is?

**Comment by juggy** [comment]
Confirm and close - No such button on github? oh well.
