### ISSUE TITLE
`hasBlock` only exposed to templates

### ISSUE THREAD

**Issue by Herriau** [emberjs/ember.js#12703]
Opening this issue since #11741 was closed.

`hasBlock` is listed as a property of `Component` (http://emberjs.com/api/classes/Ember.Component.html#property_hasBlock), and as such it should be possible to consume its value from JS like any other property.

**Comment by mmun** [comment]
It shouldn't be documented there.

**Comment by Herriau** [comment]
Then what is the recommended way of checking the presence of a block from JS?

**Comment by mmun** [comment]
There isn't a nice way right now but there is a hacky workaround. There's an open issues in the RFC repository that address it.

**Comment by rwjblue** [comment]
Closing in favor of https://github.com/emberjs/rfcs/pull/102.
