### ISSUE TITLE
Ember 2.2 - Getting attributes in components

### ISSUE THREAD

**Issue by drewclauson** [emberjs/ember.js#12713]
In Ember 2.2, it appears that getting an attribute passed into a component no longer works when just using `this.get('currentPage')`.  Instead, you must use `this.get('attrs.currentPage.value')` Was the syntax without `attrs` supposed to be removed in 2.2?  I couldn't find it in the changelog as being removed or deprecated, but did see back in 1.13 where it was added as an option.

**Comment by mmun** [comment]
Using `this.get('currentPage')` is still the correct way to do it. Can you reproduce it in an ember twiddle?

**Comment by sourvb** [comment]
Its working fine here > https://ember-twiddle.com/1b6208de37f80593ed88

**Comment by drewclauson** [comment]
I think I've tracked what's happening - I'm using a third party component (ember-cli-pagination) that uses some binding "magic" (not sure what it's officially called).  It looks like the precedence of how the data is returned changed from 2.1 to 2.2 (maybe it was intentional, I'm not sure).  Since I don't know exactly how to describe it, use this twiddle, (modified from @sourvb's example).  Try it on Ember 2.2 (returns Emberman) and then on Ember 2.1 (returns undefined).  Note the difference from @sourvb's example is the presence of `nameBinding` on the component to a value that is undefined.

Check this out: https://ember-twiddle.com/1b6208de37f80593ed88

**Comment by rwjblue** [comment]
Ember 2.1: https://ember-twiddle.com/d08bce4cbe89828d54d2
Ember 2.2: https://ember-twiddle.com/5d0ef9b0c23c60455881

Both report "Emberman", I'm not seeing `undefined` in either version.

@drewclauson - Can you please clarify?  Which demo is the failing example?

**Comment by drewclauson** [comment]
@rwjblue I must have not saved the twiddle.

Ember 2.2 (returns undefined) https://ember-twiddle.com/06a0b6c369368c032660
Ember 2.1 (returns Emberman) https://ember-twiddle.com/d2362cf84e53dcf565cb

**Comment by green-arrow** [comment]
Similar scenario for me. I have a dropdown component that relies on `optionValuePath` being set to extract out the identifiers for selected items. In 2.1, calling `this.get('optionValuePath')` in my `selectedItem` computed property returned the properly set value from the consuming component. In 2.2, the default value is returned instead. Ex:

```javascript
optionValuePath: 'id',
optionLabelPath: 'text',
selectedItem: computed('selectedValue', {
  get() {
    let selectedValue = this.get('selectedValue');
    return this._parseItemFromSelectedValue(selectedValue);
  },
  set(key, value) {
    let selectedItem = this._coerceItemBasedOnDropdownType(value);
    let selectedItemValue;

    // Following '_parse' statements retrieve the 'optionValuePath'
    if (Array.isArray(selectedItem)) {
      selectedItemValue = this._parseValueFromSelectedItemArray(selectedItem);
    } else {
      selectedItemValue = this._parseValueFromSelectedItem(selectedItem);
    }

    this._setElementValue(selectedItemValue);
    this.set('selectedValue', selectedItemValue);

    return selectedItem;
  }
}),
```

The `set` method is called with the correct value, but the `optionValuePath` remains as `'id'`, instead of what I have set in my template:

```handlebars
{{select-component optionValuePath="some_other_path"}}
```

**Comment by pixelhandler** [comment]
@drewclauson I don't understand why the binding in the component `nameBinding: 'undefined.target',` What benefit does that code provide?

**Comment by drewclauson** [comment]
@pixelhandler Sure, that's just a arbitrary string that resolves to an undefined binding on the component.  I updated the examples to further demonstrate that change between the versions:

Ember 2.2 (returns "Not Emberman") https://ember-twiddle.com/06a0b6c369368c032660
Ember 2.1 (returns "Emberman") https://ember-twiddle.com/d2362cf84e53dcf565cb

**Comment by drewclauson** [comment]
@pixelhandler Sorry, I think what you were asking is why would I need to do that?  The reason that the change in this behavior might be a concern is if someone has a component that can be created by either passing in an object or by settings attributes.  For a live example, see [ember-cli-pagination](https://github.com/mharris717/ember-cli-pagination/blob/master/app/components/page-numbers.js), where you can either pass in their PagedArray (which gets set to the component's content object) or you can pass in the page and totalPages attributes.  The move from Ember 2.1 to 2.2 seems to have changed something so that `currentPageBinding: "content.page"` causes that to have precedence over the passed in attribute.

**Comment by mixonic** [comment]
via #12799 

> The issue is mentioned here but not understood: #12713
>
> Before 2.2, you could overwrite a automatically created named binding (/^*Binding/) with the hash in a template.
>
> When testing a twiddle in the mentioned issue, make sure you manually select the correct Ember dependencies (test with 2.1.1 and 2.2.0).

**Comment by pixelhandler** [comment]
@drewclauson Now I understand why you had the example like `content.page` thanks.

Today I clicked both those ember-twiddle links and when I clicked the button, both alerts show "Emberman"…

> Ember 2.2 (returns "Not Emberman") https://ember-twiddle.com/06a0b6c369368c032660
Ember 2.1 (returns "Emberman") https://ember-twiddle.com/d2362cf84e53dcf565cb

**Comment by Serabe** [comment]
@drewclauson same here. Can you please check if this is still an issue for you? Thank you!

**Comment by drewclauson** [comment]
@Serabe It's no longer an issue for me, thanks!
