### ISSUE TITLE
2.2 Tutorial broken

### ISSUE THREAD

**Issue by nicozimmermann94** [emberjs/ember.js#12727]
Hey there! I am trying to complete the tutorial but the code examples seem to be a bit buggy. I came to the point where I have to install Mirage and edit the config file (https://guides.emberjs.com/v2.2.0/tutorial/ember-data/). First when copy pasting I get this error: `mirage/config.js: line 38, col 6, Missing semicolon.`. This is easy to fix. But then I want to replace the static array from my index.js with
`model: function (){
    return this.store.findAll('rental');
  },`. This does not work, the each loop does not loop, it seems that the Mirage data does not get returned. Even the Inspector reports `rental (0)`. What am I doing wrong? Here is my code:
http://pastebin.com/LDvjWLX9

**Comment by btecu** [comment]
Aren't you missing the model?

**Comment by nicozimmermann94** [comment]
Oh forgot to add to pastebin: http://pastebin.com/rmyAKZNw

**Comment by nicozimmermann94** [comment]
Found the error: I had the wrong ember version (1.3) installed. I guessed after using `ember new project` it would install the latest version, but no, I had to manually change the version of ember and ember-data in the bower.json and do a `bower install`
