### ISSUE TITLE
ember 2.2: the old way (1.10) to do a settable computed property doesn't work and no depreciation is thrown

### ISSUE THREAD

**Issue by ngouy** [emberjs/ember.js#12724]
i am updating a website from ember 1.11 to 2.2
I had a computed property  send (double-way biding) to a child. The but when the child set it, the parent computed property wasn't trigger.
I realized later (i'm a noob ember coder) that there was a new way to do it. But nothing talk about this depreciation.

My old code  working in 1.11 but not in 2.2:
parent.hbs :
```handlebars
{{fancy-checkbox-group
    content-data=model.activities
    labelPath='name'
    selection=selectedActivities
}}
```

parent.js
```javascript
   //triggered only one time, for passing value to child but never again after
  selectedActivities: function(key, selected) {
    if (arguments.length > 1) {
      [...]
    }
    return this.get('model.user.requested_activities').mapBy('activity.content');
  }.property('model.user.requested_activities.@each.activity'),
```

**Comment by runspired** [comment]
@ngouy did you update to 1.13 first and resolve deprecations there?

**Comment by runspired** [comment]
http://emberjs.com/deprecations/v1.x/#toc_computed-properties-with-a-shared-getter-and-setter

**Comment by ngouy** [comment]
nope.

My boses thought it's lost of time

**Comment by ngouy** [comment]
ty

**Comment by runspired** [comment]
@ngouy no deprecation warnings from 1.x will be thrown in the 2.x cycle, you need to update to 1.13, resolve deprecations, and then upgrade to the 2.x cycle.

**Comment by ngouy** [comment]
noticed.

**Comment by runspired** [comment]
There's also this addon for helping you work through the deprecations (as there are a lot of them): https://github.com/mixonic/ember-cli-deprecation-workflow

**Comment by ngouy** [comment]
Seems rlly great. Thank. U made my day.
