### ISSUE TITLE
Document `{{#each` index block parameter

### ISSUE THREAD

**Issue by drspaniel** [emberjs/ember.js#12721]
It is documented in the [guides](https://guides.emberjs.com/v2.2.0/templates/displaying-a-list-of-items/#toc_accessing-an-item-s-code-index-code) but not the [api](http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_each)

**Comment by drspaniel** [comment]
This should be added to https://github.com/emberjs/ember.js/blob/v2.2.0/packages/ember-htmlbars/lib/helpers/each.js#L9

**Comment by rwjblue** [comment]
:+1: - Would love a PR adding docs for it!

**Comment by drspaniel** [comment]
Will add soon if no one gets around to it!

**Comment by Charizard** [comment]
I would like to take this up. Will get back with a PR in a while.

**Comment by trek** [comment]
Closing in favor of #12722
