### ISSUE TITLE
Possible regression in 1.13.x handing a promise to a component via a template

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember.js#12732]
For reference: http://stackoverflow.com/questions/34338167/ember-update-causes-promises-in-templates-to-not-wait-to-resolve

This may be a non-issue/known issue of undefined behavior becoming fixed. I am just confused and want to understand more what happened.

I updated an app from 1.12 to 1.13, and it involved adding extra promise handling in the component.
```hbs
    {{a-component parent=model.parent}}
```
old
```js
    parentChanged: on('init', observer('parent', function() {
      var parent = this.get('parent');
      if (parent) {
        parent.get('child').then(child => {
          this.set('child', child);
        });
      }
    }))
```
The above worked previously, but after the update, `child` is undefined after the `then` call. I had to change it to
```js
    parentChanged: on('init', observer('parent', function() {
      var parent = this.get('parent');
      if (parent) {
        parent.then(parent => {
          parent.get('child').then(child => {
            this.set('child', child);
          });
        });
      }
    }))
```
I was able to work around it, but I'm really interested in what it was doing before.

**Comment by pixelhandler** [comment]
@kellyselden can you put together a js-bin or ember-twiddle example that reproduces the issue? If this is more of a question perhaps having a demoable example will help as well.

**Comment by kellyselden** [comment]
@pixelhandler Yeah I'll make some time to do that.

**Comment by rlivsey** [comment]
FWIW I've done something similar with a `promise-value` helper, so components don't have to care about promises.

```javascript
// app/helpers/promise-value.js
import Ember from 'ember';
export default Ember.Helper.extend({
  value: null,

  compute([promise]) {
    if (this._promise !== promise) {
      this._promise = promise;
      Ember.RSVP.resolve(promise).then(value => {
        this.set("value", value);
        this.recompute();
      });
    }

    return this.get("value");
  }
});
```

Usage:

```handlebars
{{a-component parent=(promise-value model.parent)}}
```

Then in your component you could simply have 

```javascript
child: Ember.computed.reads("parent.child")
```

And it'll update accordingly when the promise resolves

**Comment by kellyselden** [comment]
So after some digging and a repro http://emberjs.jsbin.com/ququdenari/edit?html,js,output, I can't get the initial working case in 1.12.1 working with just promises. This leads me to believe that it may have been the way ember-data was setting up the relationship promises, and since I was updating from 1.0.0-beta.19 to 1.13.15, any breaking change is fair game.

In conclusion, I better understand the issue which was my goal. Happy Holidays!

**Comment by kellyselden** [comment]
@rlivsey I turned your example into an [addon](https://github.com/kellyselden/ember-resolve-promise-helper) to use in multiple projects, FYI.
