### ISSUE TITLE
Ember.assign is undefined

### ISSUE THREAD

**Issue by jakedetels** [emberjs/ember.js#12739]
Using Ember 2.2, I'm trying to use `Ember.assign`, defined here: http://emberjs.com/api/#method_assign

However, `Ember.assign` seems to be undefined.  See twiddle here: https://ember-twiddle.com/30c30b4ad7f72ca84700

**Comment by tricknotes** [comment]
To use `Ember.assign`, you need to enable feature flag [`ember-metal-ember-assign`](https://github.com/emberjs/ember.js/blob/v2.2.0/features.json#L12).
See for detail: https://github.com/emberjs/ember.js/blob/master/FEATURES.md

**Comment by jakedetels** [comment]
@tricknotes, thanks for the tip.  It seems the API documentation would benefit by clarifying when a particular feature is only available via a particular feature flag.  The API documentation gave no hint that this was required for this method.

**Comment by stefanpenner** [comment]
@jakedetels that looks like a bug in the API doc...

**Comment by rwjblue** [comment]
Yeah, feature flagged API docs do not get properly stripped.

**Comment by runspired** [comment]
ugh, bumped into this

**Comment by mangatinanda** [comment]
@chancancode @rwjblue `Ember.assign` is available in `2.5.0-beta.1` but not in `2.5.0-beta.2`. Might be a bug, please check.

**Comment by chancancode** [comment]
@mangatinanda Thanks for reporting, I opened an issue to track it

**Comment by rwjblue** [comment]
2.5.0 will be shipped today, including `Ember.assign`
