### ISSUE TITLE
Objects with a length property of 0 evaluate to false in handlebars conditionals

### ISSUE THREAD

**Issue by kevinkucharczyk** [emberjs/ember.js#12738]
When using the `if` template conditional on objects that have a `length` property equal to `0` the conditonal evalutes to false and will not render what was expected.

Here's a twiddle with an example: https://ember-twiddle.com/7434ede64e1ed3888b2d

An object with `length` greater than `0` will evaluate to `true` and render properly.

I believe such objects might be treated as arrays, leading to this issue.

**Comment by pixelhandler** [comment]
@kevinkucharczyk This looks like a bug, seems that the check for length == 0 should only be done for an array. An object with a property of `length` that equals `0` should not be false, as in your example:

```js
{
  title: 'Test Track 1',
  artist: 'Test Artist 1',
  length: 0
}
```

**Comment by stefanpenner** [comment]
1. https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/streams/should_display.js#L66-L67
2. https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/utils.js#L51

**Comment by stefanpenner** [comment]
related issue: https://github.com/emberjs/ember.js/issues/12688

**Comment by tragiclifestories** [comment]
Digging around in `lodash.isArray`, I see they have a [much more heavily qualified check against the length property](https://github.com/lodash/lodash/blob/3.10.1/lodash.src.js#L4305) - basically, not only that it exists, but that it is a positive integer.

On the other hand, I would guess that a `length` property on some arbitrary object would be fairly likely to be a positive integer, so I'm not sure that would be perfectly satisfactory.

**Comment by locks** [comment]
I believe this is fixed by the related PRs.
