### ISSUE TITLE
The option "preventDefault" for the helper "action" only works with literals.

### ISSUE THREAD

**Issue by phcoliveira** [emberjs/ember.js#12740]
The title is self-explanatory.
Here is a twiddle for it.
https://ember-twiddle.com/fdde0eefb2086cc1794e

**Comment by Serabe** [comment]
:+1: Thank you for the report!

**Comment by mixonic** [comment]
@phcoliveira Some examples in the description might have gotten this attention more quickly- just a protip for the future :-)

You are correct that only literals work. We should either raise a better error or support bound values per @Serabe's work in https://github.com/emberjs/ember.js/pull/12764.
