### ISSUE TITLE
Website tutorial, mirage, json:api

### ISSUE THREAD

**Issue by auspayroll** [emberjs/ember.js#12742]
The tutorial on the website shows how to use mirage and gives
test data in json:api format. However this didn't work for me until 
I changed it to the same format as the dummy data in the router. 
Great framework, but this is a bit frustrating for a newbie trying to get started. 
Perhaps I have an incorrect setting somewhere? If so, can please make clearer.
Thanks.

**Comment by johnmrobinson** [comment]
Had the same issue. Solution, which was provided over EmberJS Community #needhelp slack channel,  is to include JSON serializer for ember-data. Add the following file to your app:
```
//app/serializers/application.js
import DS from 'ember-data';

export default DS.JSONAPISerializer.extend();
```

**Comment by kevgathuku** [comment]
Experienced the same issue just now and had to resort to changing the format of the data returned by Mirage, similar to what @auspayroll did.
Maybe this issue should also be opened in the [emberjs/guides](https://github.com/emberjs/guides) repo?

**Comment by mozeryansky** [comment]
This issue has been opened and closed multiple times on the guides repo and here. I do agree it's confusing, and a huge barrier to entry for Ember as I spent quite some time before figuring it out myself.

Check the version of the tutorial and the version of ember you're using.
The current tutorial that uses json:api format is for EmberJS 2.2.0, but the current version of ember-cli installs EmberJS 1.13 which does not have the JSON API Adapter. Ember 2.2.0 defaults to using json api, but ember 1.13 used just normal json formatted in their own way. json:api is supposed to unify the format.

References:
#12727
#12684
emberjs/guides#1062
emberjs/guides#1117
emberjs/guides#1118
emberjs/guides#1119
emberjs/guides#1120 (4 in a row!)

**Comment by acorncom** [comment]
Believe we've finally got this cleaned up in guides, please open an issue there if you're still having trouble :+1:
