### ISSUE TITLE
View deprecation version is not _ENABLE_LEGACY_VIEW_SUPPORT aware

### ISSUE THREAD

**Issue by justinaray** [emberjs/ember.js#12748]
While upgrading our app to 2.x, we realized that views are listed as deprecated until 2.4; however, that they will only work with the `ember-legacy-views` addon.

This is especially confusing if you are using the deprecation workflow and targeting 2.0 deprecations as you will have no deprecations but your app will throw errors because the View object will be undefined.

**Comment by justinaray** [comment]
I was originally going to PR a fix to make the deprecation unconditional and the `until` version dependent on the `_ENABLE_LEGACY_VIEW_SUPPORT` prop.  However, this will break both the `ember-lecay-views` addon tests and probably teams utilizing the deprecation workflow to silence these deprecations.

Thinking the right fix might be to just change the version to 2.0 and throw it if `_ENABLE_LEGACY_VIEW_SUPPORT` is not enabled.

**Comment by pixelhandler** [comment]
@justinaray prolly need to ping @mixonic ( https://github.com/mixonic/ember-cli-deprecation-workflow ) on this one.

**Comment by mixonic** [comment]
@justinaray I'm not sure if there is an issue here, or what is might be. The legacy views addon should silence any deprecation notices in 2.0, though in 2.4 it will again fire a deprecation notice.

Happy to reopen if I've missed something.
