### ISSUE TITLE
QUnit 1.20 `deepEqual` with EmptyObject

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#12756]
In versions of QUnit prior to 1.20 it was not possible to compare any object without a constructor against one with a constructor, but a special exemption was made for those with a `constructor` of `null`.  @stefanpenner reported this issue in https://github.com/jquery/qunit/issues/851 and goes into a bunch more detail there.  This was fixed upstream in QUnit in https://github.com/jquery/qunit/commit/b8f19267650be88c2b68d3d227d23314ddafe02c and released as part of QUnit 1.20.

Unfortunately, we do not perfectly matched the scenario that was fixed because we use `constructor` value of `undefined` (and QUnit 1.20.0 is specifically checking for `null`).

I am unsure if we should change our internal `EmptyObject` to use `null` or if we should update QUnit to detect falsey `constructor`.

I'd love @stefanpenner's and @leobalter's thoughts here.

**Comment by leobalter** [comment]
I'm game to updating QUnit, but I'm also interested to see @stefanpenner thoughts here. The EmptyObject using a null constructor seems like a good idea as well.

**Comment by stefanpenner** [comment]
> Unfortunately, we do not perfectly matched the scenario that was fixed because we use constructor value of undefined (and QUnit 1.20.0 is specifically checking for null).

do we need that?

**Comment by rwjblue** [comment]
Not sure what you mean. I'm not certain that Ember needs to use undefined as the constructor value (if that is what you mean).

It would certainly be nice to be able to use deepEqual with our EmptyObjects, and for that to work we either need to swap to use null or QUnit needs to do a falsey check. 

I'm just not sure who is "wrong" here...

**Comment by stefanpenner** [comment]
Ya I was curious about the undefined constructor bit

**Comment by rwjblue** [comment]
I have no clue why we ended up using undefined. I'll do some digging to see when it was introduced if there was any discussion about undefined vs null.

**Comment by stefanpenner** [comment]
i don't think its needed.

**Comment by pixelhandler** [comment]
@rwjblue I think using null is just fine. I often use `Object.create(null)` objects for a custom map of data that I don't want or need a prototype of `Object` for, nice for iterating with `for (let key in map) {}` (no need to check with `map.hasOwnProperty(key)` since there is no prototype.

```
var g = Object.create(null, {
  constructor: {
    value: null,
    writable: true,
    configurable: true
  }
});
> undefined
g.yo = "Yo";
> "yo"
g.ho = "Ho";
> "ho"
Object.freeze(g);
> Object {yo: "Yo", ho: "Ho", constructor: null}
```

**Comment by rwjblue** [comment]
@pixelhandler:

> Since that maps nicely to how that object was created using null as well.

not really.  Consider this:

```js
f = Object.create(null)
// => Object {}
f.constructor
// => undefined
```

Versus:

```js
// changes `EmptyObject` to use `null` instead of `undefined`

var proto = Object.create(null, {
  // without this, we will always still end up with (new
  // EmptyObject()).constructor === Object
  constructor: {
    value: null,
    enumerable: false,
    writable: true
  }
});

function EmptyObject() {}
EmptyObject.prototype = proto;

f = new EmptyObject()
// => EmptyObject {}
f.constructor
// => null
```

As you can see, the `.constructor` value of an `EmptyObject` when using `null` as the value, is `null` whereas with `Object.create(null)` the value is `undefined`.

**Comment by rwjblue** [comment]
I assumed that the above example was why `undefined` was chosen (because it resembles `Object.create(null)` a bit better).

In the end, I am personally fine with changing `undefined` to `null`. The goal of this issue is to decide if that is acceptable....

**Comment by pixelhandler** [comment]
@rwjblue Hum, But with setting a constructer value to `null`, this adds a property to EmptyObject vs. using `undefined` results in no `constructor` property. 

So I think the question is… should the `EmptyObject` be changed to have a `constructor` properly at all ?

**Comment by pixelhandler** [comment]
@rwjblue any update on whether this is still needed, or not? re: QUnit's special comparison of constructor == null

**Comment by rwjblue** [comment]
I'm going to close this, doesn't really cause problems in practice so far...
