### ISSUE TITLE
Can't require Node.js core modules.

### ISSUE THREAD

**Issue by barisnisanci** [emberjs/ember.js#12751]
Can't use any npm package that requires nodejs core modules like `require('fs')`.
Gives this error:  `Uncaught Error: Could not find module fs`
 Am I missing something or is there a way to use nodejs core modules with ember?

**Comment by rwjblue** [comment]
No, you can't use node packages (core or otherwise) in the browser at runtime.

**Comment by rwjblue** [comment]
It is possible (via ember-browserify I believe) to do this if you do need to...

**Comment by barisnisanci** [comment]
Yes. I am using ember-broserify to include node packages. Just wondering if there is a way to include core pacages too. I will move this issue to ember-browserify
