### ISSUE TITLE
Can't yield params to inverse

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#12775]
http://jsfiddle.net/amk221/ekk80jnn/

`{{yield 'foo' to='inverse'}}`  undefined

**Comment by alexspeller** [comment]
Oh I created a [twiddle of the same thing](https://ember-twiddle.com/95efabaf8aa8548f3dde?openFiles=application.template.hbs%2Cmy-component.template.hbs) to reproduce before I saw the jsfiddle :)

**Comment by mmun** [comment]
It does not make sense to assume the params for the inverse block are the same as the main block. We would need a syntax more like, but this is not currently supported in Handlebars:

```hbs
{{#my-component as |foo|}}
  Main: {{foo}}
{{else as |bar|}}
  Inverse: {{bar}}
{{/my-component}}
```

Can you describe your usecase @amk221? I'd like to hear some compelling reasons to add this feature to Handlebars.

**Comment by amk221** [comment]
Yes I found my self writing that, then realising it was't a thing.
My use case came about from working on [ember-cli-select-box](https://github.com/amk221/ember-cli-select-box)
e.g.
```
{{#select-box as |option result|}}
  {{#option value=result}}
    {{result.name}}
  {{/option}}
{{else |query|}}
  No matches found for {{query}}
{{/select-box}}
```

Instead for now I'm writing:
```
{{#select-box as |option query result|}}
  {{#if result}}
    {{option value=1 label='One'}}
  {{else}}
    No matches found for {{query}}
  {{/if}}
{{/select-box}}
```

**Comment by pixelhandler** [comment]
@amk221 I found https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/tests/integration/component_invocation_test.js#L635-L653 which seems to prove yield to inverse should work. I noticed your jsfiddle is on canary. Is this working in current beta and release?

**Comment by balinterdi** [comment]
@pixelhandler What does not work is yielding *a value* as a block param to the inverse slot, simply yielding back to the inverse (`{{yield to="inverse"}}`) works.

**Comment by amk221** [comment]
Came across a similar situation today

```handlebars
{{#view-more}}
  Full text goes here
{{else as |viewMore|}}
  Short text goes here
  <span onclick={{action viewMore}}>View more...</span>
{{/view-more}}
```

It wasn't possible to yield a `viewLess` action nicely in the main block

**Comment by mmun** [comment]
Can you please reopen this issue the RFCs repo (if there isn't one already) and link back here?

**Comment by mellatone** [comment]
What happened to this?

**Comment by mmun** [comment]
No changes. We'll be opening a new RFC repo for the handlebars language soon and I'll be sure to reopen it there.
