### ISSUE TITLE
Clarification on behavior of actions on links

### ISSUE THREAD

**Issue by karlfreeman** [emberjs/ember.js#12770]
I believe some clarification is needed with the default behavior of actions on links.

I'm developing a feature which requires a link to be marked as "read" when opened. I added an action to a link (making sure to [allow default browser actions](https://guides.emberjs.com/v2.2.0/templates/actions/#toc_allowing-default-browser-action)) and moved on with things. Afterwards though, I realised that it didn't work when opening links in a new tab using the ⌘ key. I figured I must've done something wrong and went digging turning up [how to allow modifier keys](https://guides.emberjs.com/v2.2.0/templates/actions/#toc_allowing-modifier-keys). Aside from [the "any" parameter not being documented](https://github.com/emberjs/ember.js/blob/1a2cd166a86219717a0cde1df4dab497d8dda3e3/packages/ember-routing-htmlbars/lib/keywords/element-action.js#L134-L136) _(side issue, happy to resolve)_. I then looked over the [tests for modifier keys](https://github.com/emberjs/ember.js/blob/56ac6a3e39762ca25145ffc877cdff680a7ca849/packages/ember-routing-htmlbars/tests/helpers/element_action_test.js#L227-L260). Modifier keys appear to be as tested but I couldn't figure out what the behavior is and isn't meant to be.

Most likely my edge case is minor and the interface for actions is overwhelming based on the 99% use case. That said, I felt this issue represents a tripping up point for beginners.

I've created a [JS Bin to illustrate this issue](http://output.jsbin.com/ruxudi). Click around and see what feels natural.
##### Thoughts:
- 1, 3, 4, 6 and 8 are misconfigured for the desired behavior.
- 2 and 3 feel weird. Try opening them in a new tab and then same window.
- 5 and 6 are solid. Even when opening in a new tab
##### Questions:
- Why is allowedKeys not defaulting to "any"?
- What is the best way to add an action to an external link? (with the basis of this updating the guides)
- Am I going crazy? Should I **not** be adding actions on links?

Thanks!

**Comment by rwjblue** [comment]
> Why is allowedKeys not defaulting to "any"?

TBH, I don't think there is a valid reason.  Likely just that `allowedKeys` was added later and changing it to `any` by default would have been a "breaking" change?

> What is the best way to add an action to an external link? (with the basis of this updating the guides)

I agree that 5 & 6 seem the best options.

> Am I going crazy? Should I not be adding actions on links?

Nah, seems like a good thing to do in some cases (where you want to track if a given thing has been reviewed even if it was opened in a new tab).

---

If there are applicable guides / api doc updates, that seems great! I'm going to close this for now, because I don't think there is a bug here (just some unintuitive behaviors that need thought/care to use together).
