### ISSUE TITLE
Glimmer integration stuff

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#12778]
* [x] we need to be able to build ember with or without glimmer (and by default without)
* [x] split glimmer compiler runtime

cc @stefanpenner

**Comment by fivetanley** [comment]
build ember...[with or without you](https://www.youtube.com/watch?v=XmSdTa9kaiQ)

**Comment by Cryrivers** [comment]
just asking, what do you mean by building ember without glimmer? why do we need ember without glimmer?

**Comment by devinus** [comment]
@Cryrivers I believe he's referring to Glimmer1 vs Glimmer2.

**Comment by stefanpenner** [comment]
During integration of glimmer2 we will be treating it as a regular feature flagged addition. So we will need to be able to toggle it on and off until it's ready to be enabled all the time

**Comment by chancancode** [comment]
I think we are done here 😄
