### ISSUE TITLE
How to extend a RecordArray for a specific model type

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/ember.js#12779]
We often require to derive computed properties from a set of models. These models are always accessed through the store, which returns RecordArrays. I was under the impression once could extend RecordArrays to place computed properties on them (and essentially have them behave like collections in BackBone) but couldn't find a way to do that.

Is there a way to do it? If not, I think it's really an enhancement ember.js should consider.

**Comment by stefanpenner** [comment]
StackOverflow is a much better venue for questions as per: https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#questions
Also please be sure to skim: https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md
