### ISSUE TITLE
this._super() broken after this.reopen()

### ISSUE THREAD

**Issue by Emrvb** [emberjs/ember.js#12786]
After a reopen() , super methods can no longer be called.

Works until (and including) 2.0.2 
Broken in 2.1.1

Example:
https://ember-twiddle.com/17156052c6d43e24168b

PS.

Considering this is an edge case. Documenting this behavior or triggering a warning/assertion when calling reopen on a constructed class is a fix to me.

**Comment by rwjblue** [comment]
We had a similar issue that was fixed in https://github.com/emberjs/ember-inspector/pull/481.  Calling `reopen` on an instantiated class seems "weird" at best.  I'm not sure that there is much to be done to actually fix the underlying issue here...

**Comment by stefanpenner** [comment]
this._super(); requires this._super.apply(this, arguments)

**Comment by stefanpenner** [comment]
> Documenting this behavior or triggering a warning/assertion when calling reopen on a constructed class is a fix to me.

We want to kill this feature, as it can't reasonable be made to work correctly in all scenarios, and still be performant.

**Comment by Emrvb** [comment]
Well, removal and hitting "undefined is not a function" is also a fix that would have saved me an hour debugging :P.
