### ISSUE TITLE
Documentation missing for HTMLbars expression which try to use an attribute on a variable

### ISSUE THREAD

**Issue by mdentremont** [emberjs/ember.js#12782]
We've started using Ember, and we've been burned a couple times when trying to use a variable inside of an expression. This is likely an issue with the HTMLBars docs, but I think it would go a long way to add Ember docs as well.

Most templates tend to do something as follows (taken from the Ember docs):
```
{{#each people as |person index|}}
    <li>Hello, {{person.name}}! You're number {{index}} in line</li>
  {{/each}}
```

This is fine, but what if I wanted to do (sorry, not the most useful example):
```
{{#each people as |person|}}
    <li>Click {{#link-to person.link}}here{{/link-to}} to view {{person.name}}'s profile</li>
{{/each}}
```

This unfortunately will not work. Instead we must add `person=person` inside of the `link-to`, ex: `{{#link-to person.link person=person}}`.

Adding a simple example like this to the docs would be very helpful, and would likely prevent many from waisting time trying to figure this out.

Hopefully I'm just missing something though :tongue:.

**Comment by rwjblue** [comment]
I don't understand what you mean.  Why would you have to pass `person=person` to `{{link-to}}` invocation?

**Comment by mdentremont** [comment]
@rwjblue Weird, I just tried this out again and it looks to be working wizard the `person=person` part.. It's likely that we were doing something completely wrong :stuck_out_tongue:
