### ISSUE TITLE
Router Not Cleaned Up After Acceptance Tests

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/ember.js#12780]
I've been doing some memory profiling on my Ember app's tests suite. Our tests suites were failing in CI without providing any error message. After eliminating many other possible causes, I started to focus on out-of-memory errors.

Here are two heap snapshots from the same test run, about 20 seconds (or about 20 tests) apart: [one](https://www.dropbox.com/s/3leiahbtthedtcw/tango-tests-1.heapsnapshot?dl=0), [two](https://www.dropbox.com/s/8n7nq0ef1srlxeb/tango-tests-2.heapsnapshot?dl=0)

 1. load these in Chrome
 1. select the second snapshot
 1. Click the dropdown that has the value "All Objects" and select "objects allocated between One and Two"
 1. Sort by Retained Size

The top entry, `Class` is dominated by instances of `router`. The second, `Array`, is dominated by `nextStates`.

It seems that `Ember.run(application, 'destroy');` does not properly clean up the `Router` and its internals.

**Comment by jamesarosen** [comment]
Rats. Those links are Fastly-only. Trying to find somewhere to put 250MB files...

**Comment by stefanpenner** [comment]
can you provide an isolated reproduction please

**Comment by jamesarosen** [comment]
A bare Ember 1.13.11 app does *not* have this problem. I don't have any idea how to identify what part of our app (or what addon) is holding on to router references.

**Comment by jamesarosen** [comment]
Mirage also uses routers. It could be that.

**Comment by stefanpenner** [comment]
@jamesarosen if you can't narrow it down, we could find some time to screen share?

**Comment by jamesarosen** [comment]
Yes please!

I'll coordinate on Slack 😀

**Comment by stefanpenner** [comment]
i believe the issue was in an addon, such as ember-cli-mirage

**Comment by JackCA** [comment]
@jamesarosen do you remember what the issue was for this and how you solved it?

**Comment by jamesarosen** [comment]
I had two cases:

 1. mirage, before https://github.com/samselikoff/ember-cli-mirage/pull/281
 1. Ember-I18n, though only when saving off `service:i18n` as `window.Ember.i18n` as required by https://github.com/DockYard/ember-validations
