### ISSUE TITLE
Ember Views require jQuery between 1.7 and 2.1

### ISSUE THREAD

**Issue by ohnnyj** [emberjs/ember.js#12790]
jQuery has recently updated to 1.12.x and 2.2.x. Anyone who has auto version upgrades in their bower.json file (i.e. ^1.11.3) will be updated.

The following check will fail:

https://github.com/emberjs/ember.js/blob/1a2cd166a86219717a0cde1df4dab497d8dda3e3/packages/ember-views/lib/system/jquery.js#L18

Is there a reason the regex is checking a hardcoded list of numbers rather than a true range check?

**Comment by stefanpenner** [comment]
dupe: https://github.com/emberjs/ember.js/pull/12787

**Comment by lordpixel** [comment]
In my case I'm getting the following errors:

Uncaught Error: Assertion Failed: Ember Views require jQuery between 1.7 and 2.1
Uncaught Error: Could not find module ember imported from x/app

As a temporary solution I did:

    Remove the ^ from my jQuery dependency in bower.js (is now "jquery": "1.11.3")
    Remove bower_components folder
    Perform a bower install

I hope this serves as a temporary remedy while we Ember's team provides a definitive solution.

Thank you!

**Comment by stefanpenner** [comment]
fixed by https://github.com/emberjs/ember.js/pull/12793, a new release will come out today.

**Comment by rafaeltnk** [comment]
Sorry for my stupid question, but how do I get this corrections in my ember?
Reinstalling it using npm it's enough or I need to pull the commit?
I tried to go to the ember path (the path I got using "ember which" command) inside the folder i tried to pull this correction, but this directory not seems to be correct to make some pull.

Thanks in advance!

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/issues/5316#issuecomment-170242558

**Comment by rafaeltnk** [comment]
it worked!
Thanks!

**Comment by diegoachury** [comment]
change bower.json  
`"jquery": "1.11"`
