### ISSUE TITLE
Template hash no longer overrides named binding

### ISSUE THREAD

**Issue by Emrvb** [emberjs/ember.js#12799]
The issue is mentioned here but not understood: https://github.com/emberjs/ember.js/issues/12713 

Before 2.2, you could overwrite a automatically created named binding (/^*Binding/) with the hash in a template.

When testing a twiddle in the mentioned issue, make sure you manually select the correct Ember dependencies (test with 2.1.1 and 2.2.0).

**Comment by pixelhandler** [comment]
@Emrvb If I understand correctly you are suggesting a name change to issue #12799 which should be "Template hash no longer overrides named binding" - is that correct?

If so, this could be considered a duplicate issue, correct?

**Comment by Emrvb** [comment]
I didn't want to clutter that issue since it's about passing attributes to components. If that issue gets renamed and gets a proper description of this specific problem, I'll close this issue.

**Comment by mixonic** [comment]
@Emrvb I'm concerned this is just going to be confusing. I've copied your comment over to the original issue and I'll close this as a duplicate. Let's keep the discussion there. Thanks!
