### ISSUE TITLE
Ember Views require jQuery between 1.7 and 2.1

### ISSUE THREAD

**Issue by outaTiME** [emberjs/ember.js#12792]
Hi guys, 

After install the last stable release of ember-cli: `1.13.13` (it uses the same ember version) and create an empty project using `ember new my-app` when i make application execution i get the following error:

``
Ember Views require jQuery between 1.7 and 2.1
``

whats wrong im using the last stable release ?? ... if i update the jquery version in bower.json to 2.x series it works ... this issue comes from `ember-cli` ??

thks !!

**Comment by outaTiME** [comment]
dupe: #12787

**Comment by stefanpenner** [comment]
fixed by https://github.com/emberjs/ember.js/pull/12793, a new release will come out today.

**Comment by alexdresko** [comment]
Whew... ember n00b here... Thought it was just me, my computer, or the internet's way of telling me I suck.

**Comment by twillis** [comment]
what version was this fix released in? I'm having trouble finding it.

**Comment by stefanpenner** [comment]
@twillis it has not been released yet, we are still pending the release.

if you update your `bower.json` as the [diff](https://github.com/ember-cli/ember-cli/commit/4cb6205015b443da0aabf36072a29f74723e09df) suggests, and run `bower install` you should be good.

**Comment by twillis** [comment]
:+1:  thanks
