### ISSUE TITLE
Ember 2.2.0 - JSONSerializer _normalizeResponse with array and meta problem.

### ISSUE THREAD

**Issue by NameX44** [emberjs/ember.js#12807]
Hi,
I use Ember 2.2.0
I need to paginate a list in my Web App. My server return the following response : 

```javascript
{
 'meta': {
   'count' : 10
}, 
'results' : [{
   'id': 1,
'name': 'the name'
}, 
...]
}
```

The problem is in https://github.com/emberjs/data/blob/v2.2.1/packages/ember-data/lib/serializers/json-serializer.js#L450 when trying to call map() function in payload. My array is in 'results' property of the payload var so I don't understand how it should work. 

It is impossible to set meta and to do a map on payload var.

I think that it is not the expected behaviour.. isn't it ?

We should have a special way when isSingle = False and when meta is set, no ?

Ask me questions if needed.

Thanks,

**Comment by raido** [comment]
Check out an addon i recently published - https://github.com/raido/ember-json-serializer-meta

**Comment by NameX44** [comment]
Hi @raido, 

Thanks for your response. We did a little patch into the normalizeResponse.

```javascript
_normalizeResponse: function(store, primaryModelClass, payload, id, requestType, isSingle) {
    let documentHash = {
      data: null,
      included: []
    };
     
    let meta = this.extractMeta(store, primaryModelClass, payload);
    if (meta) {
      Ember.assert('The `meta` returned from `extractMeta` has to be an object, not "' + Ember.typeOf(meta) + '".', Ember.typeOf(meta) === 'object');
      documentHash.meta = meta;
    }

    if (isSingle) {
      let { data, included } = this.normalize(primaryModelClass, payload);
      documentHash.data = data;
      if (included) {
        documentHash.included = included;
      }
    } else {
      if (payload.results) { // Here we could check if meta has been extracted.
        documentHash.data = payload.results.map((item) => {
          let { data, included } = this.normalize(primaryModelClass, item);
          if (included) {
            documentHash.included.push(...included);
          }
          return data;
        });
      } else {
        documentHash.data = payload.map((item) => {
          let { data, included } = this.normalize(primaryModelClass, item);
          if (included) {
            documentHash.included.push(...included);
          }
          return data;
        });
      }
    }

    return documentHash;
   },
```

This patch doesn't break anything and just add meta/results payload possibility.

Thanks,

**Comment by raido** [comment]
This is bad what you just did, you are overriding private method and your app probably is not upgradeable to newer versions of Ember Data. Why just not use the mixin i have created?

**Comment by wecc** [comment]
@NameX44 The support for meta with `JSONSerializer` is limited due to the nature of it's simple format. You can either use the `RESTSerializer` or do a simple customization like this:

```js
normalizeArrayResponse(store, primaryModelClass, payload, id, requestType) {
  let meta = payload.meta || {};
  let document = this._super(store, primaryModelClass, payload.results, id, requestType);
  document.meta = meta;
  return document;
}
```

Overriding private methods is generally not a good idea.

**Comment by wecc** [comment]
For future reference issues related to Ember Data should be opened in https://github.com/emberjs/data

**Comment by NameX44** [comment]
Hi Thanks to all of you for your help.

@raido Yes I know that it was ugly but I thought that it was an unwanted behavior inside the ember data JSONSerializer, so I just override this method in order to wait response.

@wecc I found a better way to implement this with JSONSerializer thanks to your exemple :+1: : 
```javascript
normalizeArrayResponse: function(store, primaryModelClass, payload, id, requestType) {
    let meta = payload.meta;
    
    if (!meta) {
      return this._super(store, primaryModelClass, payload, id, requestType);
      
    } 
    let document = this._super(store, primaryModelClass, payload.results, id, requestType);
    document.meta = meta;
    return document;
  }
```
Sorry for the wrong repo.

Thanks, this can be closed if you want.
