### ISSUE TITLE
Long list which dynamic updates make UI unusable.

### ISSUE THREAD

**Issue by auoiuiouio** [emberjs/ember.js#12806]
Hi,
I am using ember 1.0.1 in my project. I have a page which has nearly more then 200 list item. This list contains a small map which gets updated for every few seconds (without refreshing the page). We are using socket.io to do the updates. When the new date arrives the map gets updated but when this updation takes place the UI is not really usable. I am not able to scroll, there are few select box on page which I am not able to use. Its like UI is friezed. Please provide some solution for this issue.

**Comment by scottmessinger** [comment]
@auoiuiouio There are a few options like using `{{unbound}}` or generating the HTML directly from an Ember view. The Ember discourse forum has some useful discussions. The best idea is to upgrade to Ember 1.11 where these performance issues have been improved rather dramatically. Soon, Ember 2.x will offer even better performance than 1.11. For more information on the state of Ember performance, check out this issue: https://github.com/emberjs/ember.js/issues/11502

**Comment by auoiuiouio** [comment]
Using {{unbound}} will not update my list and upgrading ember we do not want to do at this point. I want my map to update but at the same time UI should not show poor performance. I even tried with ember list-view. But it didn't help much.

**Comment by stefanpenner** [comment]
Ember 1.0.1 is no longer supported. It is unlikely any changes or fixes will land their. If you are interest in improved performance, our 2.x series rendering engine handle the rapid update case quite well.

**Comment by auoiuiouio** [comment]
Thank you for quick response. No fixes no changes expecting for Ember 1.0.1. I just wanted to know if you have any solution to handle this kind of issues other than upgrading ember. Please let me know if any.
