### ISSUE TITLE
Changing values on mobile safari

### ISSUE THREAD

**Issue by MichaelSelberg** [emberjs/ember.js#12803]
On mobile safari, If you have an ember text field that has focus, and you programmatically change the value its bound to, the value in the text field will not change correctly.

**Comment by pixelhandler** [comment]
@MichaelSelberg please add a code example. Perhaps an ember-twiddle, jsbin or jsfiddle so people can try to reproduce the issue on their mobile safari browser

**Comment by pixelhandler** [comment]
@MichaelSelberg can you create a example with steps to reproduce the issue? try https://ember-twiddle.com

**Comment by pixelhandler** [comment]
@MichaelSelberg perhaps reach out in the community chatroom or even StackOverflow to see what solutions others have found.

If you do have a code example that reproduces the issue and a way others can view in mobile Safari then you might get more feedback. I know there are many developers working on apps that are using mobile Safari. So I would expect there should be some ideas available in the slack help channel.

I'll close this out for now. If you'd like to discuss further perhaps reach out in the http://embercommunity.slack.com #-help channel to chat regarding the specific version your app is using; and potential alternative solutions.
