### ISSUE TITLE
Update single li instead of enitre ul

### ISSUE THREAD

**Issue by auoiuiouio** [emberjs/ember.js#12809]
Hi,
I have one page which displays list of similar item using html ul and li combination. This list should get update in regular interval when ever any of li item(value) changes at backend. This is happening. My issue is I just want to update/redraw the particular list which was updated not the enitre html ul (all list item). I am using #each in my template. Is there any way to acheive this? Please guide on this.

**Comment by stefanpenner** [comment]
Each does this, questions though are best asked on stackoverflow or the forums, as the contributing.md articulates. This issue tracker aims to be a place to track bugs.
