### ISSUE TITLE
Ember Guides should default to latest version

### ISSUE THREAD

**Issue by mdentremont** [emberjs/ember.js#12801]
When following a link to the Ember Guides (ex: http://emberjs.com/guides/routing/), I am presented with the 1.10 version instead of the latest.

Since the API docs link without a specific version in the URL, this means all links from the API docs to the guides will show the old guides. 

This appears to be caused by the redirect from http://emberjs.com/guides/ to https://guides.emberjs.com/, as simply hitting https://guides.emberjs.com/ shows the latest version.

Example:
- Go to http://emberjs.com/api/classes/Ember.Route.html
- Click "routing guide"

Expected:
- Should see 2.2.0 guides, since the API documentation was for version 2.2.0

Actual:
- 1.10 guide is displayed

**Comment by btecu** [comment]
This would be nice. Hopefully it will also cause the search engines to index the latest version instead of 1.10.

**Comment by mdentremont** [comment]
@btecu that would be a huge win :smile:

**Comment by mdentremont** [comment]
Looks like I've filed this against the wrong repositories, and the other repositories have existing issues for this:

- https://github.com/emberjs/guides/issues/604
- https://github.com/emberjs/website/issues/2438
-
