### ISSUE TITLE
Ember 1.13.10 broken check for `isLegacyViewHelper` in "production"

### ISSUE THREAD

**Issue by herom** [emberjs/ember.js#12815]
We have an application up and running with Ember v1.13.10 and we see that the application fails to load on iPhone6(S) and Windows Phone devices (IE & Edge). iPhone5 is doing fine, as well as Chrome Android and any Desktop browser.

With the Safari debug tools we see the following message appear when we open the page with the iPhone6S:

`TypeError: undefined is not an object (evaluating 'l.isLegacyViewHelper')`

Thanks to the minification of the production environment the stacktrace is rather useless :disappointed: 

Has anybody seen the same behaviour and could provide me some insight as to why this is happening on specific devices (the iPhone5 and iPhone6S are on the same iOS Version 9.2)?

**Comment by pixelhandler** [comment]
@herom is it possible to create a code example with ember-twiddle, jsbin, or jsfiddle that would reproduce the issue. With a working example people could try to reproduce the issue. If not possible with those tools, perhaps a repo and hosting the app somewhere could help to reproduce the issue.

**Comment by herom** [comment]
Thanks a lot for your reply @pixelhandler - unfortunately I couldn't respond any sooner as this problem hit us hard in our production application. 

As I further investigated on the problem I found that the root cause was at our own precompiler implementation which used a file system cache to deliver template "bundles" on a "per request" basis, so I blamed ember.js too soon. Sorry for that.
