### ISSUE TITLE
Ember.CoreObject concatenatedProperties are overriden

### ISSUE THREAD

**Issue by kswilster** [emberjs/ember.js#12811]
From 1.13 onward changing unrelated properties on an object causes properties that are included in the `concatenatedProperties` array to be overwritten. This bug is demonstrated in [this fiddle](https://ember-twiddle.com/53c337be98163b5953d8?numColumns=1&openFiles=application.template.hbs%2C) by changing the value of the input.

This bug does not exist in 1.12

**Comment by pixelhandler** [comment]
@kswilster I'm a bit confused about the use of `concatenatedProperties` in your code example. How does `things` become `['1', '2']` when rendered? after the change to the input `things` becomes `"2"` which it was assigned to in the template. Are you expecting `things` to be a combination of `[1]` and "2". In the browser console `[1] + "2"` results in "12".

**Comment by kswilster** [comment]
@pixelhandler I agree. The `concatenatedProperties` docs say nothing about property assignment. I expected this to act like a computed, maintaining a record of default values and assigned values and concatenating them.
