### ISSUE TITLE
Support jquery 3.0.0-beta1

### ISSUE THREAD

**Issue by martndemus** [emberjs/ember.js#12821]
[jQuery 3.0.0-beta1 release blog post](http://blog.jquery.com/2016/01/14/jquery-3-0-beta-released/)

Currently installing jQuery 3 will generate an error that it isn't compatible with Ember. Whatever function that checks for this should be updated. 

jQuery 3 is a major update so there might be some breakage.

**Comment by rwjblue** [comment]
The assertion was already removed on canary/beta/release channels, using any jQuery version should not throw this error any longer.  I still need to release point versions with the assertion removed, but using one of the channels should work already.

**Comment by martndemus** [comment]
:beers:
