### ISSUE TITLE
Tutorial fails on Ember Data section due to wrong Ember version

### ISSUE THREAD

**Issue by camerenisonfire** [emberjs/ember.js#12837]
The default tutorial is for v2.2.0 but when you install with npm as instructed in the Getting Started section, you get Ember and Ember-data v1.13.11. In order for Mirage to work as instructed in the tutorial, I changed the dependency listed for ember and ember-data in bower.json to 2.2.0 and ember-data in package.json to 2.2.0.

I spent several hours trying to debug and understand why my data from Mirage was being displayed in the web console, but was not getting picked up by the model. Finally, one of my co-workers told my about this version fix. For someone who is trying to pick up and learn Ember, hitting a rode block like this can be detrimental to selling them on the tool.

**Comment by ryan4888** [comment]
I had the same issue.

**Comment by pixelhandler** [comment]
@camerenisonfire @ryan4888 Are you referring to this page? https://guides.emberjs.com/v2.3.0/getting-started/

If so, the " getting started" section of the guides is at https://github.com/emberjs/guides/tree/master/source/getting-started So to resolve this issue it may be a good idea to open this issue in the guides repo instead.

Also maybe a good idea to try a pull request for the guides repo, I'm sure the guides team would appreciate that.

**Comment by locks** [comment]
Guides problems should actually be filed at emberjs/guides. For what it's worth, the [Installation](https://guides.emberjs.com/v2.3.0/getting-started/#toc_installation) section has been updated to the current proper version.
