### ISSUE TITLE
Allow contextual components without nested component helper

### ISSUE THREAD

**Issue by max** [emberjs/ember.js#12836]
I'm not quite sure where to file this suggestion. Apologies in advance if this is the wrong place.

From the Ember 2.3 blog post:

> Contextual components are created using the nested form of the `component` helper, and may be passed attrs and positional params. Contextual components must be invoked with a `.` in their path, unless they are being passed to the invoking `{{component` helper.

For simple nested components this leads to something like:

```hbs
/* application.hbs */
{{some-component button=(component 'my-button' label='My Label')}}
```

```hbs
/* some-component.hbs */
{{component button}}
```

```hbs
/* my-button.hbs */
My awesome <button>{{label}}</button>.
```

We are already explicit when passing the component to the button attr of `some-component`. Instead of requiring the use of the component helper in `some-component` template would it be possible/desirable to detect it's a component and allow `{{button}}`?

P.S: Thanks for all the hard work on Ember. 2.3 is fantastic!

**Comment by max** [comment]
Right after filing this issue I realized that angle bracket components might fix the aesthetics of this already. It's my understanding that `attrs` will no longer be implied for _any_ passed properties. This would yield the following `some-component` template – which currently works:

```hbs
<p>Some other {{attrs.prop}}</p>
{{attrs.button}}
```

**Comment by mixonic** [comment]
@max right, exactly :-) This naturally improves as we move to glimmer components.

We will automatically render contextual components with a dot in their name, and will accept a patch that changes the behavior. It is the intended design.

I'm going to close this for now @max!
