### ISSUE TITLE
Error while not catching promise rejection in controller or component action

### ISSUE THREAD

**Issue by tsubik** [emberjs/ember.js#12835]
Hey, should I always catch promise rejection in controller or component action? Not doing this causing following error:
```
undefined
onerrorDefault @ ember.debug.js:32009
exports.default.trigger @ ember.debug.js:54070
(anonymous function) @ ember.debug.js:55319
Queue.invoke @ ember.debug.js:340
Queue.flush @ ember.debug.js:404
DeferredActionQueues.flush @ ember.debug.js:205
Backburner.end @ ember.debug.js:583
Backburner.run @ ember.debug.js:705
run @ ember.debug.js:21235
actions.push.handler @ ember.debug.js:29559
(anonymous function) @ ember.debug.js:44307
jQuery.event.dispatch @ jquery.js:4670
elemData.handle @ jquery.js:4338
```
Is this by design? Here is [ember twiddle](https://ember-twiddle.com/ad8a90667bfb2adb9986?numColumns=1&openFiles=application.controller.js%2C) for that.

**Comment by stefanpenner** [comment]
Sounds like by design. Also this seems like something better asked on SO of discourse (aka this is for bugs, not really q/a)

**Comment by tsubik** [comment]
Got it! Sorry and thanks!
