### ISSUE TITLE
template renders before findAll has finished

### ISSUE THREAD

**Issue by Hirtenknogger** [emberjs/ember.js#12834]
Since the update from 1.13 to 2.2. I have the following problem:

When i navigate to specific route from another route the template renders with all records which are already in the store. After a few seconds the other records which have loaded by the network request are displayed.
The documentation says "you'll continue to see the templates from the previous route until the model finish loading" but that does not happen. The template should be displayed when the model has already loaded.

**Comment by marcelvoss95** [comment]
Same Problem here

**Comment by raido** [comment]
http://emberjs.com/api/data/classes/DS.Adapter.html#method_shouldBackgroundReloadAll

**Comment by Hirtenknogger** [comment]
passing { reload: true } as parameter fixed it for me.
