### ISSUE TITLE
Issue a warning when using `something.@each.first.second` as a dep key.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#12840]
Per discussion with @krisselden this does not work properly, so we should warn people when they have more than one prop after `@each` in a dependent key.

It is possible that this may be made to work in the future, but for now it is a giant :footprints: :gun: and we should help people avoid it...

**Comment by stefanpenner** [comment]
We can make this work, although until it does (unless we decide not to) warning/asserting and documenting is likely a good idea
