### ISSUE TITLE
Two way binding on chained computed properties does not seem to work properly

### ISSUE THREAD

**Issue by brendan-rius** [emberjs/ember.js#12842]
I have a component that has a property `model` which is an array of elements.

`filteredResults` is a computed property depending on the model that return only the elements whose name matched a search query.

`numberOfMatchingResults` is basically the length of `filteredResults`.

Component's source:
```javascript
    // Return an array of elements that match the search
    filteredResults: Ember.computed('model.[]', 'searchQuery', function () {
        let searchQuery = this.getWithDefault('searchQuery', '').toLowerCase();
        let results = this.get('model');
        return results.filter(result => {
            var resultName = result.getWithDefault('name', '').toLowerCase();
            return resultName.indexOf(searchQuery) > -1;
        });
    }),
    // The number of elements that match the search
    numberOfMatchingResults: Ember.computed.oneWay('filteredResults.[]', function () {
        return this.get('filteredResults.length');
    })
```

Template where I use the component:
```handlebars
{{input type="text" value=search}}
There are {{nb}} matching results for '{{search}}'.
{{my-component model=something searchQuery=search numberOfMatchingResults=(mut nb)}}
```

Here `numberOfMatchingResults` is sync'ed with `nb` (from `numberOfMatchingResults=(mut nb)`). That means if `numberOfMatchingResults` changes in the component, `nb` should be updated accordingly.

BUT, it is not. In fact `numberOfMatchingResults` is "overridden" by `nb` the first time (because of the two-ways sync). But when I type something, `numberOfMatchingResults` should change (because it is a computed property), and update `nb` accordingly, which does not happen. I cannot figure out why.

Is it a bug? If not how to do what I want?

**Comment by stefanpenner** [comment]
Questions are better asked on stackoverflow or the discussion forma

**Comment by brendan-rius** [comment]
Thank you for your time.

I am not really trying to solve a personal problem here, I am rather discussing a behaviour that looks weird to me, that indeed came from a problem I had, but my code is here just so you can reproduce the same behaviour.

Would it have helped if I had written this issue in a more "I am sure it is a bug" fashion? If so I can rewrite my issue in a more conventional manner.

**Comment by stefanpenner** [comment]
> Would it have helped if I had written this issue in a more "I am sure it is a bug" fashion?

Yes likely (it would be nice of GH had a more structure issue submission form), but what would help more is a live reproduction https://ember-twiddle.com/ as that would make triaging much less overhead.

------

several issues while reading, that suggested to me this is a Q/A not a bug report:

* `Ember.computed.oneWay` does not take a second argument [docs](https://github.com/emberjs/ember.js/blob/afdba0f334e761734c59a05b1312b061e1dd0faa/packages/ember-metal/lib/computed_macros.js#L508-L543)
*  `oneWay` (and all computed properties) are mutable be default, setting to them will replace them. If you don't want that behavior you have two options, make a CP that has a setter, or make it as `readOnly`

I had advocated this behavior change for 2.0, but there was worry that adding yet another large deprecation would be to much pain. Maybe for 3.0?

**Comment by brendan-rius** [comment]
[I created a Twiddle](https://ember-twiddle.com/abadafb06b4e2789b737?openFiles=application.template.hbs%2Cmy-list.component.js): I would expect this to sync "numberOfFilteredElements" properly, but it does not and displays `There are elements matching your search` instead of `There are NUMBER elements matching your search`.

Concerning the `oneWay` that was an artefact left from attempts I made, sorry.

**Comment by pixelhandler** [comment]
@brendan-rius regarding your question on the fiddle "if you change "numberOfFilteredElements" in the component using the number imput (in red) in the component, it is effectively synchronized. Why?"

If you bind `numberOfFilteredElements` to an input and also use `numberOfFilteredElements` as a computed property in your component but do not define a getter and setter in the computed property my best guess is that your computed property is getting borked by the binding from the input.

This is not the best way to use an input with an computed property, you need a getter and setter in the computed property. See https://guides.emberjs.com/v2.3.0/object-model/computed-properties/#toc_setting-computed-properties

**Comment by brendan-rius** [comment]
@pixelhandler It looks like you are right and the computed property gets overridden by the binding of the input, because having a setter in the computed property works as if you was not using the input. Thank you.

However, the problem was not that. The thing is that **when a computed property gets updated, it should update the properties it is bound to outside the component**, just as it does with non-computed properties.

**Comment by stefanpenner** [comment]
Just reviewed the twiddle, and it appears my above statement is true.

> oneWay (and all computed properties) are mutable be default, setting to them will replace them. If you don't want that behavior you have two options, make a CP that has a setter, or make it as readOnly

by making `numberOfFilteredElements` `readOnly`:

```
numberOfFilteredElements: Ember.computed('filteredElements', function () {
    return this.get('filteredElements.length');
}).readOnly()
```

We see:

```
Uncaught Error: Cannot set read-only property "numberOfFilteredElements" on object: <demo-app@component:my-list::ember365>
```

As described above, CP are by default writable, if you wish to support the bi-directionality one must implement the setter, or the set will replace it. 

```
numberOfFilteredElements: Ember.computed('filteredElements',  {
  get() {
    return this.get('filteredElements.length');
  },
  set(key, value) {
     // decide what to do
     return value;
  }
}).readOnly()
```

As mentioned, I don't like this default, and as such mark all my CP readOnly. I hope as we move to JS decorators for this feature we can make the transition to what I believe to be a more sound default.

**Comment by stefanpenner** [comment]
I believe my earlier comment explains this issue, hopefully my latest one helps explain it further.

If I have missed something please let me know

**Comment by brendan-rius** [comment]
Thank you for your answer :)

I do not get how it explains the fact that `numberOfFilteredElements` inside the component and `numberOfFilteredElements` outside the component are not synchronised although they should be because of

```
{{my-list model=elements searchQuery=searchQuery numberOfFilteredElements=(mut numberOfFilteredElements)}}
```
