### ISSUE TITLE
Debounce runs twice - reproduceable on Ember Twiddle (included)

### ISSUE THREAD

**Issue by raido** [emberjs/ember.js#12841]
Hi, 

I have an issue with debounce being fired twice before starting to debounce.

See twiddle - https://ember-twiddle.com/1b356a46178909c3c48b

Update: If i increase debounce time to 500ms then it starts debounce like expected.

**Comment by halfdan** [comment]
Holding return will continuously call the runMe method - there seems to be an initial delay between first pressing (keyDown) and continuously holding (keyPress) the key which is greater than the 300ms debounce interval.

**Comment by raido** [comment]
The delay depends on how fast user has set the key repeat time in operating system configuration.

**Comment by pixelhandler** [comment]
@raido I forked your gist and varied the action and debounce time, see https://ember-twiddle.com/e9f4a9436948d51e81f1?openFiles=application.template.hbs%2Capplication.route.js

This is not a bug, it's just a matter of timing.

**Comment by raido** [comment]
I know it is a matter of timing. In my app went with 500ms as i mentioned here and then it debounces. I guess it can be closed. Should it be documented that one cannot use short debounce time with actions while holding keys?

**Comment by pixelhandler** [comment]
@raido I don't think that needs to be documented in the app, but may name for a good blog post on solving issues in Ember. I like this post how it tells the story of solving a problematic use of Ember features.
