### ISSUE TITLE
Asset fingerprints missed in generated HTML

### ISSUE THREAD

**Issue by jdmarshall** [emberjs/ember.js#12855]
I have code that parses CommonMark formatted text and emits it into my ember app.  I have a helper and the punchline of it looks like:

```
return Ember.String.htmlSafe(writer.render(parsed));
```

Which I then use like 

```
   {{commonMark objectName.markupFieldName}}
```

Everything is working pretty well, except if the generated HTML happens to refer to something in the asset directory.  In production mode, my images all have fingerprints on them, but Ember never adjusts the src tags in this generated HTML.  Right now I've turned off fingerprinting, and at some point I'll be storing these assets in the database.

But in the meantime, and for future reference, is there a way to ask Ember to link to files in the assets directory with their relevant fingerprints?  Can we have that if it doesn't exist?

**Comment by stefanpenner** [comment]
that is a good question, i believe https://github.com/rickharrison/broccoli-asset-rev might be the best place to ask.

**Comment by jdmarshall** [comment]
Oh, so it only happens at build time, then?

**Comment by stefanpenner** [comment]
Well, ember itself isn't aware of fingerprinting. That is a broccoli-asset-rev and ember-cli level concern.

**Comment by jdmarshall** [comment]
Okay, thanks for the info.  So it looks like I need to get my assets into RESTful URLs if I expect to use them without workarounds.

**Comment by stefanpenner** [comment]
> Okay, thanks for the info. So it looks like I need to get my assets into RESTful URLs if I expect to use them without workarounds.

I don't know what that means exactly. I think this seems more like a Question, as per our [contributing.md](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md) I would recommend this be opened on Stackoverflow or discourse. I

**Comment by jdmarshall** [comment]
@stefanpenner It means my long term plan is to serve the images from the backend instead of from ember, at which point I'm responsible for any fingerprinting or cache invalidation.  

>  I think this seems more like a Question

I thought ember was doing something special at run time with URLs and that it wasn't triggering.  I couldn't find the code to wire it up to my helper manually, because I misunderstood the mechanics and imagined a block of code that isn't there.
