### ISSUE TITLE
transitionToRoute(“some_route”) is being aborted ember 2.2.0

### ISSUE THREAD

**Issue by samtes** [emberjs/ember.js#12851]
app/router.js

    import Ember from 'ember';
    import config from './config/environment';

    const Router = Ember.Router.extend({
      location: config.locationType
    });

    Router.map(function() {
      this.route('questions');
      this.route('question', { path: "/questions/:question_id" });
    });

app/routes/questions.js

    import Ember from 'ember';
    import AuthenticatedRouteMixin from 'ember-simple-auth/mixins/authenticated-route-mixin';

    export default Ember.Route.extend(AuthenticatedRouteMixin, {
      correct: "",
      wrong: "",
      model () {
        return this.store.find("question").then(questions => {
          return this.store.find("key", this.get("session.data.authenticated.key")).then(key => {
            this.set("correct", key.get("correct"));
            this.set("wrong", key.get("wrong"));
            return key.get("questions");
          });
        });
      },

     afterModel (model, transition) {
        this.controllerFor("question").set("key", this.get("session.data.authenticated.key"));
        model = model.filter(item => {
         return  this.get("correct").indexOf(item.id) === -1 && this.get("wrong").indexOf(item.id) === -1;
        });
        this.transitionTo("question", model.get("firstObject"));
      }
    });

app/routes/question.js

    import Ember from 'ember';

    export default Ember.Route.extend({
      model (params) {
        return this.store.find("question", params.question_id);
      },

      setupController (controller, model) {
        controller.set("model", model);
      }
    });

app/controllers/question.js

    import Ember from 'ember';

    export default Ember.Controller.extend({
      key: "",
      option: "",
      actions: {
        submitQuiz () {
          this.store.findRecord("key", this.get("key")).then(key => {
            key.set("answer", this.get("option"));
            key.save();
          }).then(() => {
            this.transitionToRoute("questions");
          });
        },

        selected (option, elm) {
          this.set("option", option);
          Ember.$(".question_container").find(".selected").removeClass("selected");
          Ember.$("#".concat(elm)).addClass("selected");
        }
      }
    });

However, this.transitionToRoute("questions") in app/controllers/questions.js is being aborted in the middle of transition and continues to the current "questions/:question_id" route instead. Any idea why that's happening???? And is there a way to force transition???

**Comment by stefanpenner** [comment]
if you have a chance, reproducing this in ember-twiddle.com or similar would be handy for us to diagnose quickly.

**Comment by samtes** [comment]
That will take time with this implementation, but I will try to create a small example.

**Comment by samtes** [comment]
this project is too complex to reproduce in ember-twiddle.com but the issue is ` this.transitionToRoute("questions");` in the below code is being aborted.

    actions: {
      submitQuiz () {
        this.store.findRecord("key", this.get("key")).then(key => {
          key.set("answer", this.get("option"));
          key.save();
        }).then(() => {
          this.transitionToRoute("questions");
        });
      },
    }

**Comment by jcope2013** [comment]
@samtes your missing an argument ``` this.transitionToRoute("questions", questionId); ``` or  ``` this.transitionToRoute("questions", question); ``` with question being the question model

**Comment by samtes** [comment]
but what if I want to transition to the questions route?

**Comment by pixelhandler** [comment]
@samtes if it's too complicate to produce in an ember-twiddle example, how about a sample repo in github?

**Comment by pixelhandler** [comment]
@samtes were you able to create a demonstration of the issue in a repo? Did you find a workaround?

**Comment by pixelhandler** [comment]
@samtes perhaps reach out in the community chatroom. If you do have a code example that reproduces the issue and a way others can view the sample code in action, then you might get more feedback.

I'll close this out for now. If you'd like to discuss further perhaps reach out in the http://embercommunity.slack.com #-help channel to chat regarding the specific version your app is using; and potential solutions.

I know there are many developers working on non-trivial apps. So, I would expect there should be some ideas available in the slack help channel.

Perhaps see related docs…

- http://emberjs.com/api/classes/Ember.Route.html#method_intermediateTransitionTo
- http://emberjs.com/api/classes/Ember.Route.html#method_transitionTo

Maybe you need the full path to the route you want to transition to; or maybe the route needs a dynamic segment added. Others can't really troubleshoot, without some code snippets.
