### ISSUE TITLE
which js i should include in my file ( Just Question not a bug ) 

### ISSUE THREAD

**Issue by GaneshKandu** [emberjs/ember.js#12850]
Hi , I am a new here
i want to use emberjs but i am little bit confuse which one to use and why whereas its name describes where to use but just want to to confirm

release/ember-template-compiler.js
release/ember.debug.js
release/ember.js
release/ember.min.js
release/ember.prod.js

**Comment by stefanpenner** [comment]
As per https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#questions a better venue for questions is stackoverflow or discourse  discussion forum.

-----

A quick tl;dir of the files:

description of the files:

the following files are essentially the same, you will need only 1 of time (depending on the task).
* release/ember.debug.js <-- for development
* release/ember.js <-- for development
* release/ember.min.js <-- for production minified
* release/ember.prod.js  <-- for production unminified

This one is required if you wish to compile templates in the browser (good for hacking, bad for production).
* release/ember-template-compiler.js


best recommendation is to use ember-cli, which does all this for you auto-magically.
