### ISSUE TITLE
Cannot unregister component template

### ISSUE THREAD

**Issue by jakedetels** [emberjs/ember.js#12859]
The `Ember.ApplicationInstance#unregister` method fails to fully unregister a component template.  See twiddle here: https://ember-twiddle.com/47dd2375c095cd7e73e5

I can successfully register a component template using:

```js
let template = Ember.Handlebars.compile('<b>First x-foo</b>');
application.register('template:components/x-foo', template );
```

However, when I try unregistering this template followed by registering a different compiled template in its place, the original template is the one that gets rendered.

```js
application.unregister('template:components/x-foo');
let newTemplate = Ember.Handlebars.compile('<b>New x-foo</b>');
application.register('template:components/x-foo', newTemplate );
```

In the twiddle demo, clicking "Register Template" will register the first compiled template.  Then, clicking "Change Template" will first unregister the old template, followed by loading a new complied template.  Yet when the component template is rendered, we still see the original compiled template.  This demo utilizes the `{{component}}` helper to load the registered component template.

cc @dgeb (possibly related to commit https://github.com/emberjs/ember.js/commit/53267df64d1e11ce8312c129946e309667887215)

**Comment by GavinJoyce** [comment]
This behaviour is the same in ember 1.12.1 ([twiddle](https://ember-twiddle.com/8967afb5e46a7600991e)) and 1.13.11 ([twiddle](https://ember-twiddle.com/a12ce57fa4f5c9f0c7bd)). 

I've confirmed that the component is being unregistered in the container correctly.

**Comment by GavinJoyce** [comment]
https://embercommunity.slack.com/archives/dev-ember/p1454362713000478

![image](https://cloud.githubusercontent.com/assets/2526/12732396/451ac048-c92d-11e5-9c02-eebf23f85a44.png)

![image](https://cloud.githubusercontent.com/assets/2526/12732423/668a130a-c92d-11e5-8e80-e1f8209ad802.png)

**Comment by GavinJoyce** [comment]
@jakedetels how come you need to unregister a component and replace it at runtime?

**Comment by pixelhandler** [comment]
@jakedetels I think the suggestion by @GavinJoyce makes sense and may be an elegant way to swap the components with the component helper

**Comment by pixelhandler** [comment]
@mixonic do you think this is a bug?

**Comment by mixonic** [comment]
As we have no response from @jakedetels, I'm going to provisionally mark this wontfix and close it.

**Comment by andyhot** [comment]
I believe a valid use-case for this is to support template hot-swapping
