### ISSUE TITLE
typeOf is undefined in the source

### ISSUE THREAD

**Issue by knownasilya** [emberjs/ember.js#12862]
So I've tried nombom and everything but still get this:

The issue is that `typeOf` is undefined in the ember source and `pushObject` fails here because of it: https://github.com/emberjs/ember.js/blob/release-1-13/packages/ember-runtime/lib/system/each_proxy.js#L65

I have 1.13.13 and here is the stack:

```no-highlight
TypeError: typeOf is not a function
    at addObserverForContentKey (ember.js:35051)
    at null.<anonymous> (ember.js:35154)
    at Object.exports.tryFinally.tryFinally [as tryFinally] (ember.debug.js:23427)
    at changeProperties (ember.debug.js:20703)
    at /Users/iradchenko/sandbox/fit-forms/vendor/ember.js.EmberObject.extend.arrayDidChange (ember.js:35150)
    at Object.applyStr (ember.debug.js:23678)
    at Object.sendEvent (ember.debug.js:17190)
    at Array.exports.default._emberMetalMixin.Mixin.create.arrayContentDidChange (ember.debug.js:34472)
    at Array._emberMetalMixin.Mixin.create.replace (ember.debug.js:39506)
    at Array.exports.default._emberMetalMixin.Mixin.create.insertAt (ember.debug.js:36237)
```

Even if I put a breakpoint at the top of the module, the object from which `typeOf` comes from doesn't have `typeOf` but has the other keys.

**Comment by rwjblue** [comment]
Can you provide a demo/repro?

**Comment by knownasilya** [comment]
I'll try to deploy the issue so you can have a look at it later today.

**Comment by knownasilya** [comment]
@rwjblue pinged you on slack, let me know if you need anything else.

**Comment by knownasilya** [comment]
So I tried 1.13.12, regular build and prod build and the same thing happens (version changed in console). Could it be ember-cli-shims (0.0.6) and I'm using quite an old ember-cli (0.2.3).

Guess I could start by upgrading the cli..

**Comment by knownasilya** [comment]
So upgrading the cli didn't help. Removing an old way to do notifications (using views and collections) did, but I'm still unsure why.

I will close this, since I cannot recreate the issue or find a good reason why it was happening. Plus no one else experienced it, or so it seems.

**Comment by knownasilya** [comment]
Ok, the problem still persists.

**Comment by knownasilya** [comment]
It's in `ember-runtime/system/each_proxy`. I've tried 1.13.12 and 1.13.13. Will try 11 now. I have other apps that use these same versions and they work fine.. maybe it's an addon clobbering it? It's weird, the object `__dependency4__` has all of the other exports, except for `typeOf`..

**Comment by stefanpenner** [comment]
two embers where loaded, and strange things happened.

**Comment by knownasilya** [comment]
Looks like I was using an old version of ember-uploader, which required ember.js in the `vendor/` folder. I have been so out of touch with this project that I completely forgot that was the case.. Thanks @stefanpenner for the help!

**Comment by stefanpenner** [comment]
Np it was a fun mystery to debug

**Comment by rwjblue** [comment]
I wonder if we can detect this, and actually print a more helpful error/warning....

**Comment by stefanpenner** [comment]
@rwjblue ya we likely can

**Comment by stefanpenner** [comment]
its basically this code: https://github.com/emberjs/ember.js/blob/master/packages/loader/lib/index.js#L8-L14
