### ISSUE TITLE
Two way data binding for web components?

### ISSUE THREAD

**Issue by ofersadgat** [emberjs/ember.js#12863]
The following fiddle shows what I would like to do (tested in chrome):

http://emberjs.jsbin.com/zeminaneco/edit?html,js,output

Essentially I would like a web component to change a property and have ember change the data model. My current workaround is to attach a mutation observer onto the node and then do a set in the callback, but I was hoping that this could be handled by ember. Is there any plan for something like this?

Thanks!

**Comment by pixelhandler** [comment]
@ofersadgat any use of native components + ember components is still experimental, so yeah you'll need to use an observer, callback, event or some creative way to bridge the behavior between native and the ember component. Some people have experimented with a universal web component format e.g. https://github.com/jayphelps/graffiti

**Comment by locks** [comment]
This feature doesn't seem feasible. I think this is the same problem as when binding to a native `input`. The closest we will get is when Glimmer components are available from within Ember applications.
