### ISSUE TITLE
Some 1.13.x versions missing from changelog

### ISSUE THREAD

**Issue by johnnyshields** [emberjs/ember.js#12869]
Please include a changelog entry for each tiny version release. Can't tell what's changing.

**Comment by pixelhandler** [comment]
@johnnyshields you could open a PR for anything that is missing in the changelog.

Also [git whatchanged](https://www.kernel.org/pub/software/scm/git/docs/git-whatchanged.html) or [git show-branch](https://www.kernel.org/pub/software/scm/git/docs/git-show-branch.html) could help to see all the details.

**Comment by workmanw** [comment]
It seems pretty complete to me. https://github.com/emberjs/ember.js/blob/release-1-13/CHANGELOG.md . I've always thought Ember does a phenomenal job of managing it's changelog. If there are things missing, I'm sure it's a rarity.

**Comment by stefanpenner** [comment]
The changelog is automated, which things are missing?

**Comment by johnnyshields** [comment]
I was referring to this file: https://github.com/emberjs/ember.js/blob/master/CHANGELOG.md. Missing 1.13.13, .12, .10 and .9 (however .11 is present)

The missing versions are present in this file: https://github.com/emberjs/ember.js/blob/release-1-13/CHANGELOG.md, however I think they should be in master changelog as well.

**Comment by johnnyshields** [comment]
Raised PR https://github.com/emberjs/ember.js/pull/12874

**Comment by stefanpenner** [comment]
@johnnyshields after the branch point, these change-logs are non-linear.
