### ISSUE TITLE
title property binding does not work for checkbox input

### ISSUE THREAD

**Issue by justin-hackin** [emberjs/ember.js#12865]
Observed in several versions of ember

**Comment by pixelhandler** [comment]
@justin-hackin can you create an example of the bug? perhaps try ember-twiddle.com

**Comment by pixelhandler** [comment]
@justin-hackin Does a Checkbox have a `title` attribute? see http://www.w3.org/wiki/HTML/Elements/input/checkbox#HTML_Attributes and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input I don't see a `title` attribute.

I'll close this for now, if you have a reproduction of the issue or steps to reproduce this issue then please reopen it, thanks.

**Comment by rwjblue** [comment]
I believe that `title` is a "global attribute": https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes
