### ISSUE TITLE
Wrapper divs affecting the styles

### ISSUE THREAD

**Issue by rafaeltnk** [emberjs/ember.js#12871]
Hi, 

I don't know why but I'm not using any views on my Ember template and the Ember is creating the wrapping divs outside my divs. 

`<div id="ember522" class="ember-view"> <div id="myDiv">`

It's causing me some problems in some div's styles.
Why does Ember create these div's if i'm not using any view? What it does?

Is there any way to disable these div's, or remove of a specific div?

Thanks.

**Comment by runspired** [comment]
Support questions like these fit better on SO or in the #needhelp channel on the [Ember Community slack.](https://embercommunity.slack.com/messages/need-help)

If you ping me on that slack, I'd me more than happy to help you.  You can register [here](ember-community-slackin.herokuapp.com).

**Comment by stefanpenner** [comment]
> Why does Ember create these div's if i'm not using any view? What it does?

I'm pretty sure it only adds it if you are using a component/view, if/each/other bound data does not.

**Comment by rafaeltnk** [comment]
Hi, I solve my problem temporally unwrapping "myDiv" using jQuery, but i'll find out a best solution for it.

`$("#myDiv").unwrap();`

As you said, maybe I'm forgetting some point, but i'm pretty sure that there isn't any component or view in my template.
I'm using handlebars only in my header and footer, the page that the problem ocurrs is contained in outlet's application without components, views or handlebars tags.
I've tested my div in a single page without that header and footer for assure they aren't affecting my style, without success too.

I'm going to post that issue in Slack and StackOverflow.

Thanks!
