### ISSUE TITLE
Thrown Errors in Firefox doesn't include the error message

### ISSUE THREAD

**Issue by mozeryansky** [emberjs/ember.js#12876]
I posted this question while trying to figure it out myself:
http://stackoverflow.com/q/35071984/359532

From what I can tell, in chrome the 'stack' property contains the error message while Firefox does not. 

In my case, the error handler is from `ember-runtime/ext/rsvp`. I think to fix this, `onerrorDefault()` could print the error message and the stack trace, instead of just the stack trace. However, in chrome it would appear twice.

**Comment by pixelhandler** [comment]
@mozeryansky Is there a way you can create an ember-twiddle that reproduces this error?

Tips on debugger here - https://guides.emberjs.com/v2.3.0/configuring-ember/debugging/

There are some good answers on the SO link you posted. This doesn't sound like an ember issue / bug. Sounds more like a difference in browser vendors reporting the error stack.

**Comment by stefanpenner** [comment]
> I think to fix this, onerrorDefault() could print the error message and the stack trace, instead of just the stack trace. However, in chrome it would appear twice.

we could do some feature sniffing in onerrordefault to make the right choice

**Comment by rwjblue** [comment]
yeah, I think adding something using `ember-metal/environment`'s `isFirefox` flag from [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/environment.js#L28), should be straight forward....

**Comment by stefanpenner** [comment]
ya something like that.

**Comment by stefanpenner** [comment]
honestly, it would be nice if error messages where somewhat spec'd but, tricky business.

**Comment by Charizard** [comment]
Safari's `error.stack` also does not contain the proper error message. To make things consistent in all browsers (Chrome, Firefox and Safari. Have not tested others though.), we need to print `error.name + ": " + error.message + "\n" error.stack` in both Firefox and Safari and just the `error.stack` in Chrome.

**PS: ** Attaching the error message screen for Safari.
<img width="1279" alt="screen shot 2016-05-10 at 11 21 39 pm" src="https://cloud.githubusercontent.com/assets/1897178/15156736/07de1410-1706-11e6-9ae3-a4dd0187f740.png">

**Comment by Charizard** [comment]
There seems to be no flag to detect Safari [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-environment/lib/index.js#L106,L124).

**Comment by Turbo87** [comment]
this is how Mocha.js does it: https://github.com/mochajs/mocha/blob/master/lib/reporters/base.js#L169-L193

so essentially just see if the stack contains the message and if not you can add it. I think detecting it this way will be more robust compared to deciding based on the browser detection.
