### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getState' of undefined

### ISSUE THREAD

**Issue by mk-conn** [emberjs/ember.js#12885]
Not sure, if this is related to #12690 since I get this **no matter where I click** in my app... so I think its not really component-yield related. What can I do to provide more information for this? 

```
DEBUG: -------------------------------
DEBUG: Ember      : 2.3.0
DEBUG: Ember Data : 2.3.3
DEBUG: jQuery     : 2.1.4
DEBUG: -------------------------------
Ember Inspector Active
```

**Comment by stefanpenner** [comment]
can you provide an isolated reproduction?

**Comment by Cryrivers** [comment]
Is it because of Ember Inspector?

**Comment by rwjblue** [comment]
Most likely, there is an open issue/PR over in the inspector repo

**Comment by mk-conn** [comment]
I disabled the inspector, but error is not gone. I'll check if I can provide a reproduction some how...

**Comment by marcemira** [comment]
Confirmed, is the inspector :(
