### ISSUE TITLE
Unexpected behavior when using ES6-syntax in router.js

### ISSUE THREAD

**Issue by stonetwig** [emberjs/ember.js#12884]
Works:
```
this.route('search', function() {
    this.route('index');
    this.route('advanced');
  });
```

Does not:
```
this.route('search', () => {
    this.route('index');
    this.route('advanced');
  });
```

Can be very confusing for new users like me, is it intended? Because I know that the `this` keyword don't get redefined when using arrow functions.

This happened when using ember 2.3

**Comment by rwjblue** [comment]
The router DSL depends on being able to influence 'this' inside the various callbacks. If you use arrow functions, the inner callbacks will all be invoked with the wrong 'this' context. 

Tldr; arrow functions have lots of use cases, but there are definitely times that they work and times that they do not.

**Comment by stonetwig** [comment]
Alright, that makes sense. This maybe should be a report to update the guide with a warning label or something. Unless it's possible to implement it to work with arrow functions and the ember community thinks is something worthwhile to do.

**Comment by workmanw** [comment]
FWIW I always thought using `this` on router definitions was a little odd. One future option, that would be backwards compatible, could be to pass the DSLRouter as an argument.

```
Router.map(router => {
  router.route('search', router => {
    router.route('index');
    router.route('advanced');
  });
});
```

Meh, just a thought. That's what [ember-qunit](https://github.com/rwjblue/ember-qunit) started to do with it's `assert` helpers recently.

**Comment by rwjblue** [comment]
@workmanw - Ya, I agree that this sticks out a bit.  We don't often manipulate this in a way that feels unnatural like this.  I'm happy to discuss this as a new feature in an RFC issue/PR...

**Comment by workmanw** [comment]
@rwjblue Cool. I'll toss something together this afternoon.

**Comment by ctsstc** [comment]
I'm new and glad that this issue exists, I was going crazy trying to figure out why my nested route was breaking after I implemented an ES6 arrow function. Good stuff to know & learn.
