### ISSUE TITLE
transitionTo returns promise when passed a url

### ISSUE THREAD

**Issue by asakusuma** [emberjs/ember.js#12899]
In ember canary, [route.transitionTo](http://emberjs.com/api/classes/Ember.Route.html#method_transitionTo) returns a promise when passed a url. According to the docs, it should return a transition object.

From what I can tell, the issue seems to have been [introduced in this commit](https://github.com/emberjs/ember.js/commit/ef7108a8d1a97fc263918a0fd37db72889419b4c#diff-985dc4a078da4636eff18be21aa7f9e6L303).

I reproduced the issue in this [example app](https://github.com/asakusuma/transition-to-bug).

cc @minasmart @rwjblue

**Comment by rwjblue** [comment]
Thanks for the report @asakusuma, looks like @GavinJoyce is working on a fix in #12905.

**Comment by GavinJoyce** [comment]
I've been digging into the recent changes which reshuffled how the router deals with exceptions but I don't have enough context yet to be productive here. I'm going to close my skeleton PR and find something else to work on.

 * https://github.com/emberjs/ember.js/commit/ef7108a8d1a97fc263918a0fd37db72889419b4c#diff-985dc4a078da4636eff18be21aa7f9e6L303
 * https://github.com/emberjs/ember.js/pull/12752

**Comment by rwjblue** [comment]
@GavinJoyce - Understood. I'm trying to find a good path forward.  I realize this is a fairly bad regression, so I'll try to be quick about it...

**Comment by krisselden** [comment]
Mobile phone mishap

**Comment by krisselden** [comment]
Was just scrolling somehow registered as a tap on the close button

**Comment by stefanpenner** [comment]
> Mobile phone mishap

rofl

**Comment by minasmart** [comment]
@rwjblue & @GavinJoyce the skeleton PR looks good to me. I don't think it breaks exception handling. Did all the tests pass with the change?

**Comment by rwjblue** [comment]
@minasmart - It breaks most of the tests I added in the original PR.

**Comment by minasmart** [comment]
aw :cry:

**Comment by minasmart** [comment]
I'll spend some time and see if I can maybe come up with some ideas? I feel a little responsible having wrote the code that caused the regression.

**Comment by asakusuma** [comment]
@krisselden briefed me on the issue. I'm going to take a stab at a PR this afternoon and will give an update later today.

**Comment by asakusuma** [comment]
@rwjblue @krisselden @minasmart any objection to making router.transitionTo public? route.transitionTo is public, and it's pretty much just a proxy to router.transitionTo: https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/route.js#L1027
