### ISSUE TITLE
Observer not working after changing ember.select 3 times.

### ISSUE THREAD

**Issue by saidikondawar** [emberjs/ember.js#12893]
Using below versions :
Ember Inspector 1.9.4
Ember 1.13.8
jQuery 1.10.2

When I am changing locale in Ember.select it triggering localeNameDidChange function 3 times after that it not calling that function.

Please help me resolve this issue.

handler code : 
 <label class="form-label label-port-name" for="Locale">{{translations.login.localeField.label}}</label>
      {{view Em.Select class="input-locale" placeholder=translations.login.localeField.placeholder id="Locale" value=localeName content=availableLocales optionValuePath="content.name" optionLabelPath="content.label"}}

js:

  localeNameDidChange: function() {
        var localeName = this.get('localeName');

        this.loadLocaleResources(localeName);
        this.setCookie('localeName', localeName);
      }.observes('localeName').on('init'),

 init: function() {
        this._super();
        

        var storedLocaleName = this.getCookie('localeName');
        // English is by default
        var localeNameFound = 'en-us';
        // Try to find stored in cookies locale
        if (!Em.isEmpty(storedLocaleName)) {
          this.get('availableLocales').some(function(item) {
            if( item.name === storedLocaleName ) {
              localeNameFound = storedLocaleName;
              return true;
            }
          });
          // Store if something is found or default English version
          this.set('localeName', localeNameFound);
          return;
        }

        // If no cookies for locale found, try default language
        var defaultLocaleName = (window.navigator.language || window.navigator.userLanguage).toLowerCase();
        if (!Em.isEmpty(defaultLocaleName)) {
          // Use short locale name for all non English locale (ja)
          if( defaultLocaleName !== 'en-us' && defaultLocaleName !== 'en-ca' && defaultLocaleName !== 'en-gb') {
            defaultLocaleName = this.formatShortLocaleName(defaultLocaleName);
          }
          this.get('availableLocales').some(function(item) {
            if( item.name === defaultLocaleName ) {
              localeNameFound = defaultLocaleName;
              return true;
            }
          });
        }

        // Store if something is found or default English version
        this.set('localeName', localeNameFound);

      },

**Comment by rwjblue** [comment]
`Ember.Select` is no longer included as part of Ember 2.x due to exactly these types of bugs.  I would suggest using an alternate implementation (there are several nice addons for `<select>`).

**Comment by saidikondawar** [comment]
I am facing this issue with Ember 1.13.8

**Comment by rwjblue** [comment]
@saidikondawar - Yes, I understand that.  There were quite a few bugs in Ember.Select in all of 1.x which is why it was removed in 2.0.0. We will gladly accept pull requests for fixes to 1.13, but are very unlikely to try to dig in and fix this ourselves.
