### ISSUE TITLE
Undefined defaultValue in model property causes ds.defaultValue.complex-object deprecation.

### ISSUE THREAD

**Issue by aikixd** [emberjs/ember.js#12897]
Declaring models with properties without defining defaultValue, like so:
```
import DS from 'ember-data';
export default DS.Model.extend({
  name: DS.attr('string')
});
```
causes 'ds.defaultValue.complex-object' deprecation to appear.

**Comment by stefanpenner** [comment]
I believe this is something related to ember-data, the appropriate repo i believe is [here](https://github.com/emberjs/data). Sorry I realize the number of repo's can be confusing, hopefully this helps.
