### ISSUE TITLE
Weird each regression in 2.3.0

### ISSUE THREAD

**Issue by topaxi** [emberjs/ember.js#12906]
We ran into an issue with the `{{#each}}` helper after upgrading to 2.3.0.

I'm not 100% sure if it's only happening with DOM `File` objects but we made a reproducible twiddle here:
https://ember-twiddle.com/9c341eb331bb62b1256b

After selecting files, each filename should appear in the `<ul>` element. After adding a second one, all previous filenames magically disappear. This worked prior to version 2.3.0 (i.e. 2.2.1).

**Comment by mmun** [comment]
If you replace

```
let foobar = [ ...this.get('elements'), event.target.files[0] ]
```

with

```
let foobar = [ ...this.get('elements'), { name: event.target.files[0].name } ]
```

it works fine. I did a bit of digging and it looks like mandatory setter does not work correctly with the `File` object.

**Comment by topaxi** [comment]
Thanks, this way we can at least work around this issue for now :+1:

**Comment by stefanpenner** [comment]
https://github.com/emberjs/ember.js/pull/12491 may address this

**Comment by mmun** [comment]
@stefanpenner You're right. The ember-twiddle works on master and I bisected the fix to your PR.

**Comment by rwjblue** [comment]
Demo working against 2.4.0-beta.2: https://ember-twiddle.com/cfca58688d4e6c7f0e2b?openFiles=application.controller.js%2Capplication.template.hbs
