### ISSUE TITLE
Ember 2.3.0 and ace editor conflicting in My App

### ISSUE THREAD

**Issue by vinothwindows47** [emberjs/ember.js#12903]
Hi, I am Using Ace editor for our application. Previously I was using Ember 1.7.0 .My Component is

`export default Ember.Component.extend({

```
didInsertElement: function() {
    var self = this;
    var editorid = self.editorid; /*get editor name with unique id*/

    /*generate ace editor with the name of editor*/ 
    var editor = window.ace.edit(editorid);
    self.set('editor', editor);
    editor.setReadOnly(true);
    editor.setOptions({
        maxLines: 400000
    });
    /*set ace editor settings*/
    editor.setShowPrintMargin(false);
    editor.setTheme("ace/theme/monokai");
    editor.setFontSize('16px');
    editor.session.setMode("ace/mode/java");
},

contentChange: function() {
    var self = this,
        editor = self.get('editor');
    editor.setValue(self.get('fileContent'), -1);
}.observes('fileContent'),

actions: {

}
```

});`

After Migrating Ember 2.3.0, While Setting Acemode 

> editor.session.setMode("ace/mode/java");

I got Error From Ember Code .

The Error is ,

> Uncaught TypeError: Cannot set property 'isDescriptor' of undefined ... 

From ember-metal/properties ,  

> this is undefined
> 
>   /**
>     Objects of this type can implement an interface to respond to requests to
>     get and set. The default implementation handles simple properties.

```
@class Descriptor
@private
```

  */

  function Descriptor() {
    this.isDescriptor = true;
  }

**Comment by mmun** [comment]
Can you provide a demonstration of the bug in ember-twiddle.com?

You might also want to try using `self.get('editorid')` instead of `self.editorid`.

**Comment by stefanpenner** [comment]
> Uncaught TypeError: Cannot set property 'isDescriptor' of undefined ...

can you provide a stack for this?

**Comment by stefanpenner** [comment]
My guess is that the change to move descriptors to the properties is causing one to leak, and be unexpectedly interacted with.  as @mmun mentioned a reproduction (ember-twiddle.com) or even just a small ember-cli app that demonstrates this would likely lead to something very quickly debuggable.

**Comment by acorncom** [comment]
@vinothwindows47 Is this still a problem for you?  If so, it'd be great to see something reproducible so we can work on tracking it down ..

**Comment by stefanpenner** [comment]
> @vinothwindows47 Is this still a problem for you? If so, it'd be great to see something reproducible so we can work on tracking it down ..


will gladly reopen if ^ is addressed

**Comment by marclundgren** [comment]
@stefanpenner I can still reproduce this on ember `2.4.3`. I'll report back here with an ember-twiddle when I have some time.

**Comment by marclundgren** [comment]
update: I'm blocked by ember-twiddle an issue. 

https://github.com/ember-cli/ember-twiddle/issues/464

**Comment by marclundgren** [comment]
Thanks @stefanpenner. I was able to get `ace` on a twiddle, but I haven't been able to fully init the component. There's a runtime error in the `ace/document` module.

```
this.$detectNewLine = function(e) {
   var t = e.match(/^.*?(\r\n|\r|\n)/m); // e is undefined
   // ...
}
```

I don't have time to try and squash this bug today, but hopefully within the next week.

**Comment by pixelhandler** [comment]
Closing as this has been inactive for some time.
