### ISSUE TITLE
Code samples in quickstart are unreadable

### ISSUE THREAD

**Issue by uolot** [emberjs/ember.js#12913]
On following page of documentation:
https://guides.emberjs.com/v2.3.0/getting-started/quick-start/

Some code samples are unreadable, because of green/red diff background highlights.

![screen shot 2016-02-04 at 10 20 59](https://cloud.githubusercontent.com/assets/209847/12812265/711fac64-cb29-11e5-97c0-cf5082f9c795.png)
![screen shot 2016-02-04 at 10 21 12](https://cloud.githubusercontent.com/assets/209847/12812264/711d2340-cb29-11e5-8a15-4c9cd40e2d80.png)

**Comment by GavinJoyce** [comment]
I'm not sure what style the added and remove are supposed to have, but they only seem to be used in the recently added [quick start](https://github.com/emberjs/guides/commit/77aef2f3a31e8fc7d637d7456b8b4f82d1f8f221).

I'll cut a PR now which removes the highlighting as it's currently not very readable. We can follow up with an improved style if necessary

**Comment by acorncom** [comment]
@uolot If you see bugs like that in the future, we'll see notes about it faster over in the http://github.com/emberjs/guides repo.  Thanks!
