### ISSUE TITLE
inline {{if}} helper within a sub expression doesn't respect array updates

### ISSUE THREAD

**Issue by GavinJoyce** [emberjs/ember.js#12925]
twiddle: https://ember-twiddle.com/23c0f8a836d49b502cfa

`{{if items 'T' 'F'}}` correctly updates when the items array goes from empty to populated
`{{concat (if items 'T' 'F')}}` does not update when the items array goes from empty to populated

This is producing a failing test in https://github.com/emberjs/ember.js/pull/12920. Interestingly, these tests pass in glimmer 2

**Comment by GavinJoyce** [comment]
I'll work on adding a failing test now

**Comment by GavinJoyce** [comment]
I'm planning to work on this later today. Note to self: this looks like a bug in the stream dependencies with arrays

**Comment by GavinJoyce** [comment]
We may decide to not fix this as it seems to be an edge case, it may be impossible to fix in htmlbars and glimmer2 fixes it:

https://embercommunity.slack.com/archives/dev-ember/p1455038787000826

![image](https://cloud.githubusercontent.com/assets/2526/12925382/efee5d12-cf55-11e5-8542-b029a515adf5.png)

**Comment by stefanpenner** [comment]
If the fix is on the horizon, the current system doesn't seem to support this. Maybe we should introduce a warning?

**Comment by rwjblue** [comment]
I'm going to close this for now.  It is fixed in Glimmer2 and I highly doubt we will get around to addressing before that lands...
