### ISSUE TITLE
Components are always wrapped in divs, even if tagName is defined

### ISSUE THREAD

**Issue by mattbearman** [emberjs/ember.js#12937]
Not sure if this is by design, as I can't find anything about it in the guides.

When a component has its `tagName` property set to anything other than div, I'd expect the rendered tag to be that specified by tagName, but instead the required form is still wrapped in a div. Eg:

```javascript
// some-component.js
Ember.Component.extend({
  tagName: 'form'
})
```

Expected HTML
```html
<form id="ember123"></form>
```

Actual HTML
```html
<div id="ember123"><form id="ember124"></form></div>
```

I know it's not a huge issue, but it seems inefficient, and can make testing a little more complicated

**Comment by stefanpenner** [comment]
I don't believe this is true. I suspect you actually have a wrapping component/view

**Comment by mattbearman** [comment]
On further investigation it seems it only happens in integration tests, eg:

```javascript
this.render(hbs`
    {{#some-component}}
      some content
    {{/some-component}}
  `);

// form ends up wrapped in a div
this.$() // -> <div id="ember123"><form id="ember124"></form></div>
```

**Comment by rwjblue** [comment]
Yes, the testing harness itself is a component which uses a `div`.  I suppose we could avoid that extra tag though, would you mind opening an issue (or better yet, a failing test case) in ember-test-helpers library?

**Comment by rwjblue** [comment]
I'm going to close this issue now that we have determined that this is a testing library issue...

**Comment by stefanpenner** [comment]
@rwjblue I believe tagless would have been best, but I suspect many rely on that behavior right now.

**Comment by rwjblue** [comment]
@stefanpenner - I am unsure if it is a thing that cannot change (I had actually not noticed the extra tag since I generally use `this.$('.someselector')` as I assume most folks do). Either way, it should be taken into account in the new system that we create for https://github.com/emberjs/rfcs/pull/119...
