### ISSUE TITLE
`SCRIPT` tags are not allowed in HTMLBars templates

### ISSUE THREAD

**Issue by danconnell** [emberjs/ember.js#12935]
> `SCRIPT` tags are not allowed in HTMLBars templates

When upgrading from 2.2.2 to 2.3.1, I get this error when running my app.

I understand why script tags shouldn't be allowed, but they have been up to this point and I don't see anything in the deprecation guide about this being done and how I should best fix my code for it.

Any guidance on this would be appreciated. Thanks!

**Comment by mmun** [comment]
It was a bug that they were ever allowed. What does something like this even mean?

```hbs
<script>
  console.log("{{message}}");
</script>
```

Regardless, can you explain how you were using them? Then we can have a better idea of how to help you transition away from it

**Comment by danconnell** [comment]
One example was something like:

`<script data-startup="xxx" src="https://angel.co/javascripts/embed_jobs.js" id="angellist_embed" async></script>`

Actually didn't end up being too difficult to move that to a component and use didInsertElement and Ember.$.getScript. And my other couple cases were things that I probably shouldn't have put in the template anyways, so I moved them into the controller code and used Ember.run.scheduleOnce with 'afterRender'.

I guess I rushed into posting this as an issue, but I do think you should add it to the deprecation guide, since I was confused and looked over the guide, your blog posts, and the changelog multiple times trying to find documentation of this change.

Thanks!

**Comment by stefanpenner** [comment]
> Actually didn't end up being too difficult to move that to a component and use didInsertElement and Ember.$.getScript.

Yes  this is likely what I would have suggested.

> I guess I rushed into posting this as an issue, but I do think you should add it to the deprecation guide, since I was confused and looked over the guide, your blog posts, and the changelog multiple times trying to find documentation of this change.

You were correct to file, as it may not be obvious why this may have changed. Thank you for filing.

**Comment by mmun** [comment]
@danconnell Sorry, I forgot to reply earlier. You're right that this should be added in the guides somewhere. It falls under the heading of "removal of an intimate/private API" and not really a deprecation.

HTMLBars never supported this use case publicly, and in fact the HTML parsing library it uses even states that explicitly in its [README](https://github.com/tildeio/simple-html-tokenizer#simple-html-tokenizer-).

**Comment by ming-codes** [comment]
I'm getting a similar issue. There isn't any warning. Just the template breaking.

https://ember-twiddle.com/fb411ea030e6330dcd1bcd24573a67ca?fileTreeShown=false&openFiles=templates.application.hbs%2C
