### ISSUE TITLE
Install addon from URL fails with error

### ISSUE THREAD

**Issue by jaichandra** [emberjs/ember.js#12946]
I am trying to install a private addon from github enterprise url and it fails with below error: 

Command executed: 
`ember install git+ssh://git@url_to_git_repo.git `

Error:
`Install failed. Could not find addon with name: git+ssh://git@url_to_git_repo.git`

---
The command seems to work fine for other github public repos. I am able to access my private repo directly.

**Comment by rwjblue** [comment]
This is the issue tracker for Ember itself. 

Can you open an issue in ember-cli/ember-cli instead?

**Comment by jaichandra** [comment]
Sure. Thanks.
