### ISSUE TITLE
AdapterError should have ajax status

### ISSUE THREAD

**Issue by pavkum** [emberjs/ember.js#12943]
Hello,
  We are using Ember 1.13.10. On delete one our models return 412 status resulting in invocation of error callback. It receives instance of AdapterError which ignores ajax error status.

  On debugging I found in `normalizeErrorResponse` check for `errors` field in payload and returns as is if found else it creates object with status, payload and title. But here `payload` is forced to string by prep-ending `"` which destroys payload resulting in `[Object object]` 

  This issue is preventing us from accessing `status` in case 1 and `payload` in case 2

   Any guidance on this would be appreciated. Thanks!

**Comment by pixelhandler** [comment]
@pavkum Yes I agree that this would be a great feature recommendation. I've written up an article on using the error code as a property of the errors. This is how I build my apps. ( if interested on use cases see https://pixelhandler.com/posts/emberjs-handling-failure-using-route-error-substates )

Can you open up an RFC issue see https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature prolly doesn't need a full featured RFC proposal, but an RFC issue would be ideal.

I'm curious if you can use the ajaxError method in the adapter to set your error code value on the error?

**Comment by stefanpenner** [comment]
@pavkum hello, ya sorry for the confusion. Adapter related stuff isn't part of this package, rather [ember-data](https://github.com/emberjs/data)  and then everything else @pixelhandler said :)

**Comment by pavkum** [comment]
@pixelhandler Went through your blog and addon. I see you are doing exactly what I'm doing too. I have extended Error object and preparing a new Error object with all the required params. 

I'm using `adapter.ajaxError` to return an instance of Error. This way default `adapter.handleResponse` won't be invoked and my error callback gets invoked with Error instance.

I willl open an RFC regarding the same. 
Thank you @pixelhandler @stefanpenner
