### ISSUE TITLE
input event throwing JS error for {{input}}

### ISSUE THREAD

**Issue by seanjohnson08** [emberjs/ember.js#12956]
According to the docs, I should be able to hook into the `{{input}}` form field's native "input" event with the following syntax:

`{{input input="myAction"}}`

However, all I'm getting is a JS error.

Here's a twiddle: https://ember-twiddle.com/ebf5525e510e885864f6

Am I just doing something stupid, or is this completely broken?

Thanks!

**Comment by pixelhandler** [comment]
@seanjohnson08 I'm not sure where you found that example for input='action', have you seen this guides page? https://guides.emberjs.com/v2.3.0/templates/input-helpers/ And also have you seen the the events list for use with actions? (note that use of the event names requires you to dasherize them) http://emberjs.com/api/classes/Ember.View.html#toc_event-names

**Comment by seanjohnson08** [comment]
`input` is listed under `form` events - because it is a single word, it cannot be dasherized (can it?)

What's the correct syntax for triggering the `input` event on the `input` component?

**Comment by stefanpenner** [comment]
my recommendation is as follows, using a regular `input` tag, one can bind to it, and also connect a listener to it, example:


```
<input value={{val}} oninput={{action "myAction" value="target.value"}} >
```

example is fiddle form: https://ember-twiddle.com/43579380170ae6181754

**Comment by rwjblue** [comment]
@stefanpenner's solution works very well on 2.3.1, but for prior versions there is a "cursor position" issue (see [example](https://ember-twiddle.com/afd593c0bb0130b280c5)) that you need to be aware of.
