### ISSUE TITLE
Canary + defeatureify problems

### ISSUE THREAD

**Issue by asakusuma** [emberjs/ember.js#12952]
I tried running defeatureify against canary, but was still getting an asset size 60% bigger than the last canary I was using. Dug deeper and noticed a couple things:

1. From what I can tell, defeatureify works by identifying calls to `.isEnabled`. ([source](https://github.com/thomasboyt/defeatureify/blob/master/defeatureify.js#L37)). The way [ember-metal/features is setup](https://github.com/emberjs/ember.js/blob/240b8c2f5c7b001fe0d1714ecee387c25b84de2d/packages/ember-metal/lib/features.js) would seem to prevent defeatureify from working.

2. Canary ember.prod.js contains glimmer tests and I don't see any feature flagging going on around the tests. Either way it seems weird to have tests in a production asset. ([source](http://builds.emberjs.com/canary/ember.prod.js))

**Comment by rwjblue** [comment]
Ember canary does not use defeatureify at all.  We use a custom babel transform to strip debug statements and feature flags.

Ember canary will be larger as we continue working on Glimmer engine integration, both engines are being shipped which definitely increases the size.   Once canary rolls to beta, the glimmer feature flag will be disabled and the glimmer engine will be removed from the emitted assets.

**Comment by rwjblue** [comment]
> Canary ember.prod.js contains glimmer tests and I don't see any feature flagging going on around the tests.

This is absolutely a bug.  I'm looking into it now...

**Comment by asakusuma** [comment]
Thanks. Understood that the stock canary build does not use defeatureify and will be larger with the glimmer and engines stuff going into the build.

However, am I supposed to be able to apply defeatureify to canary to get a build without glimmer2 and engines? Or should I be using this custom babel transform? My goal is to be able to use canary without the size penalty of glimmer2 other features that I am not using.

**Comment by rwjblue** [comment]
@asakusuma - I am sorry for not making it clear.  My point is that no version of Ember (release, beta, or canary) use the defeatureify library.

> However, am I supposed to be able to apply defeatureify to canary to get a build without glimmer2 and engines?

No, that is not a feature of our build system.  

> My goal is to be able to use canary without the size penalty of glimmer2 other features that I am not using.

You might be able to use the babel transform, but since ember-cli apps do not build Ember you would have to manually run it on the bower assets. I think you'd be better off writing a recast script to striping modules starting with `ember-glimmer` and `glimmer-*`.

**Comment by rwjblue** [comment]
Glimmer tests being included in builds will be fixed by https://github.com/emberjs/ember.js/pull/12954.
