### ISSUE TITLE
How to get or access controller from component in latest Ember 2.3.0?

### ISSUE THREAD

**Issue by vinothwindows47** [emberjs/ember.js#12955]
Previously I was using Ember views to access controller . For Ex

` testController : Em.computed.alias("parentView.controller")`   like this ....

   In Latest Ember Version ember views concept deprecated despite supporting `**Ember-legacy-views**` .

In older Ember Components we can get Controller like this on didInsertElement ,

```
var self = this;
self.set("controller", this.get("controller"));
```

  So, now I am planning to migrate views to component . So now I cannot access my controller from componen

**Comment by wppurking** [comment]
Maybe you can try [#targetObject](https://github.com/emberjs/ember.js/blob/1a2cd166a86219717a0cde1df4dab497d8dda3e3/packages/ember-views/lib/components/component.js#L172) in Ember.Component

**Comment by vinothwindows47** [comment]
@wppurking is this proper way to get controller ?

**Comment by pavkum** [comment]
Components are completely isolated from surrounding context. You should consider passing required parameters to components.

**Comment by vinothwindows47** [comment]
@pavkum I discussed with my teammates about this before posting this issue . He also told to pass parameter to component . Is this proper way doing like this ? .Any slowness application happens because of this passing whole controller object to component ?

**Comment by pavkum** [comment]
@vinothwindows47 I'm not sure about performance, but its definitely not advisable to do so. It kills the whole purpose of writing a component which is supposed to be reusable. 

Yes, passing required parameters to component is the proper way.

**Comment by pixelhandler** [comment]
@vinothwindows47 This is more of a question than a bug/issue of Ember.js Looks like you've you've had some feedback. Have you joined the embercommunity.slack.com chatrooms, e.g. #needhelp yet?

The way for controllers to work together with (view) components is to pass down an action, that way the component can access the return value from that action of the parent context (usually the controller), see https://guides.emberjs.com/v2.3.0/components/triggering-changes-with-actions/#toc_passing-the-action-to-the-component

**Comment by stefanpenner** [comment]
> .Any slowness application happens because of this passing whole controller object to component ?

Nah, i suspect no real difference in JS
