### ISSUE TITLE
Documentation,Routing> Preventing and Retrying Transitions, leaf-most?

### ISSUE THREAD

**Issue by Ab1d** [emberjs/ember.js#12965]
In the documentation of routing> preventing and retrying transitions, it says "This gives each active route, starting with the **leaf-most** route" is this leaf-most or left most?, can i create a PR with the change?

**Comment by rwjblue** [comment]
It is not a typo. Your applications routes are a tree, the leaf most route is a route without branches/children.

**Comment by Ab1d** [comment]
Thanks for the clarification.
