### ISSUE TITLE
What are the semantics required by the legacy view and controller plugins?

### ISSUE THREAD

**Issue by wycats** [emberjs/ember.js#12963]
Today, the legacy view and controller plugins enable functionality that is implemented partly inside of Ember itself. This allowed us to defer moving the actual code out of Ember in the run-up to 2.0, but it means that the definition of the supported semantics is, currently, implementation-defined.

I would like to try to enumerate the supported semantics for views and controllers, so that if we need to reimplement part of the semantics in Glimmer, we know what we need to reimplement.

In the process of updating the test harness for new implementation work, we have noticed (again) that many of the legacy semantics are tested implicitly, and it's very easy to make tweaks to the tests that reduce coverage. It's important to know, at a high level, what we are trying to support.

I've started to enumerate some semantics -- please comment with additions and I will update the checklist.

(related to #12907)

## `ember-legacy-controllers`

- [ ] `ArrayController`
- [ ] `ObjectController`

## `ember-legacy-views`

- [ ] `{{view view-name}}` and `{{#view view-name}}`
- [ ] `{{view.prop}}`
- [ ] the `context` property on a view becomes its context in templates

**Comment by ebryn** [comment]
`{{#each foo itemController="bar" as |itemController|}}`

**Comment by pixelhandler** [comment]
`ContainerView`, `CollectionView`, `View` ?
