### ISSUE TITLE
Setting target propoerty on LinkComponent

### ISSUE THREAD

**Issue by willrax** [emberjs/ember.js#12972]
Hi there,

Adding the [target property](http://emberjs.com/api/classes/Ember.LinkComponent.html#property_target) to a link-to component seems to stop the link from working all together. Here's an ember-twiddle replicating the issue.

https://ember-twiddle.com/80ce3bd2223de064614c

**Comment by aigyptios** [comment]
Doesn't seem to be working in the ember-twiddle but I've gotten it to work in an ordinary app. It could just be a twiddle thing; I added `<a href="www.google.com" target="_blank">Google</a>` to your template file and that also didn't work.

**Comment by pixelhandler** [comment]
@willrax @aigyptios I am not able to reproduce a broken link that opens in a new tab. I added both an html anchor as well as an htmlbars link-to helper in my app. 

```hbs
<a href="/other" target="_blank">Other</a>
{{#link-to "index" target="_blank"}}Index{{/link-to}}
```

In Chrome, Safari, and Firefox (on mac) both links work as expected… I click and the links open in a new tab of the browser.

**Comment by rwjblue** [comment]
Yes, I believe that the twiddle sandboxing prevents popups and whatnot.

**Comment by willrax** [comment]
Ok. I't must be local to our application for some reason. I'll close this for now and then reopen if it's something deeper.

Thanks :)
