### ISSUE TITLE
Error in doco example: position -> position()

### ISSUE THREAD

**Issue by eddiesholl** [emberjs/ember.js#12981]
Just a minor issue I noticed. The [scroll example](https://guides.emberjs.com/v2.3.0/components/the-component-lifecycle/#toc_making-updates-to-the-rendered-dom-with-code-didrender-code) provided is awesome, just what I was looking for. I think there's a typo there though. It looks like position is actually a function call:

``this.$('.item-list').scrollTop(this.$('.selected-item').position.top);``

should be:

``this.$('.item-list').scrollTop(this.$('.selected-item').position().top);``

**Comment by pixelhandler** [comment]
@eddiesholl can you move this issue to the guides repo? https://github.com/emberjs/guides

**Comment by rwjblue** [comment]
Perhaps even a PR over there?
