### ISSUE TITLE
Getting Assertion Failed: A helper named 'each-in' could not be found

### ISSUE THREAD

**Issue by adithyan** [emberjs/ember.js#12992]
I'm developing an app using ember-cli, with ember version 2.3.0
When I use the **each-in** helper, getting the below error message in the dev console

> Assertion Failed: A helper named 'each-in' could not be found

I did as per this guide https://guides.emberjs.com/v2.3.0/templates/displaying-the-keys-in-an-object/

Thanks in advance
Adithyan

**Comment by devey** [comment]
Could you post some code?

**Comment by btecu** [comment]
I think an example will be required in order to see what the issue is.

**Comment by rwjblue** [comment]
Agreed, a demo would be very helpful. In general, this helper has been available since at least ember 2.1.0...
