### ISSUE TITLE
#with array yields boolean

### ISSUE THREAD

**Issue by spencer516** [emberjs/ember.js#12995]
In both Beta and Canary, if the value in the `with` helper is an array, it will yield `true` rather than the array itself. 

See [this twiddle](https://ember-twiddle.com/62a6d7176f003bec0fbd?openFiles=twiddle.json%2Capplication.template.hbs) for an example. (This behavior does not occur on 2.3 and down).

**Comment by fivetanley** [comment]
I had to modify some of the dependencies for this to load without errors, but this is indeed a bug. https://ember-twiddle.com/c956012ee7ad22e46436?openFiles=twiddle.json%2Capplication.template.hbs

**Comment by rwjblue** [comment]
Most likely due to https://github.com/emberjs/ember.js/pull/12922.  

@chadhietala - Do you happen to have spare time to look at this and see if it is related?
