### ISSUE TITLE
Should the container be serializable?

### ISSUE THREAD

**Issue by ibarrick** [emberjs/ember.js#13002]
I haven't done enough work on this to generate a full RFC, but I'm looking for some high level input from people more familiar with the internals of Ember. 

Ember has such a good story for handling application state, I wonder if it should have a similarly good story for handling app state serialization. I think it would help debugging ember apps in production if error reports could include full description of state.

**Comment by stefanpenner** [comment]
Some related work (in addition to the react/flux/redux atom) would be how cocoa controllers serialize.

My guess would be, if firm guidelines where followed (which would likely result in an app I would consider idiomatic) this should be possible, the question is can a happy path that enables this by default be codified. My thought is yes, but will require some more research. 

I don't think this is something that should be considered an issue, but rather something that requires more thought and exploration especially when it comes to some of the details.

This may also go hand in hand with fast boot rehydration

**Comment by ibarrick** [comment]
I appreciate the input. I'll do some research and submit a proper RFC when I have a working idea of how to accomplish this.

**Comment by stefanpenner** [comment]
@ibarrick I look forward to reading through a more detailed exploration of this topic. I believe it is a path worth exploring.
