### ISSUE TITLE
Replace JSHint/JSCS with ESLint

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#13006]
`ember-cli` has internally switched from using JSHint/JSCS to ESLint lately (see https://github.com/ember-cli/ember-cli/pull/5455) because it was considered unlikely that JSHint will include async/await support any time soon. I would like to propose switching to ESLint for `ember` too for similar reasons.

Note that this is not talking about forcing `ember` users to use ESLint in their project, this is only about linting the `ember` codebase itself.

**Comment by pixelhandler** [comment]
@Turbo87 I think the way to begin the discussion for a potential change from jshint to eslint for the Ember project would be to create an RFC issue, see - https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature

**Comment by stefanpenner** [comment]
we should bring this up at todays meeting.

@pixelhandler i think, because this is actually just discussing a tooling change on ember's own code-base, we can skip the RFC. Unless ofcourse it turns out to require more-indepth exploration or will change the externally observed experience for users.

**Comment by Turbo87** [comment]
@stefanpenner any news on this?

**Comment by adhamhf** [comment]
@stefanpenner I'd like to bump this... we are using eslint and every time we apply an upgrade we have some annoyances around the code format issues...

**Comment by rwjblue** [comment]
@adhamhf - This issue is for changing the Ember internals to use ESLint instead of JSHint, not related to an ember-cli apps default.
