### ISSUE TITLE
Ember.Object.create does not reset nested objects

### ISSUE THREAD

**Issue by jcbvm** [emberjs/ember.js#13001]
When having a nested object in Ember, calling create on the object does not reset any nested objects within this object.

See [this JSBin](http://emberjs.jsbin.com/noxikifufu/edit?js,output)

Tested this case from version 1.12.0 to 2.3.0.

**Comment by sly7-7** [comment]
This is a well known 'gotcha', see http://codebrief.com/2012/03/eight-ember-dot-js-gotchas-with-workarounds/ chapter 6

But I don't think it's a bug

**Comment by jcbvm** [comment]
Hmm never knew that, kinda tricky though. It's not what you would expect. Thanks anyway :)

**Comment by stefanpenner** [comment]
Extend is used as short hand to setup the prototype, any property on the prototype is shared with all instances.

Once decorators become a thing, we can to move to pure java script classes, we have been working to make those classes much more ergonomic and to make this scenario hopefully more obvious at first sight

**Comment by jcbvm** [comment]
Thanks for the clarification.
