### ISSUE TITLE
ES6 class getters broken in ember 2.3?

### ISSUE THREAD

**Issue by dwickern** [emberjs/ember.js#13011]
I'm having some weird behavior after upgrading from ember 2.2 to 2.3. I've narrowed it down to the getters in an ES6 class.

If I have a class like this, calling `foo.prop` from JS code will return `undefined` (!!)

```
class Foo {
  get prop() {
    return 10;
  }
}
```

Everything works if I change the class like so:

```
class Foo {
  constructor() {
    this.prop = 10;
  }
}
```

I'm using `foo.prop` in some computed properties and/or templates.

I originally posed this on [stackoverflow](http://stackoverflow.com/questions/34861361/es6-class-getters-broken-in-ember-2-3) but got no response. I wasn't able to reproduce this outside of my application, and I'm fine with the workaround. But at least it's on the radar in case someone else runs into this.

**Comment by btecu** [comment]
Are you using `ember-cli`?
For some reason this seems more likely to be a `babel` issue than `ember`.

**Comment by stefanpenner** [comment]
I made some fixes that should likely allow this further. Does your issue still arise when running with production builds, if not, then I suspect it is something already addressed. Although I am unclear when it was/will be released.

**Comment by YoranBrondsema** [comment]
We're seeing something similar in the `mobiledoc-kit` library that we use, after having upgraded to Ember.js 2.3. I don't have any more information at this time. I don't think it's a `babel` issue because we haven't upgraded `ember-cli-babel` during the Ember update.

**Comment by dwickern** [comment]
I don't suspect ember-cli or babel since all I did was upgrade ember from 2.2.1 to 2.3.0. I'll try reverting my workaround when the next ember release lands, to see if it's fixed now.

**Comment by mmun** [comment]
You could also try using the canary channel temporarily.

**Comment by stefanpenner** [comment]
please let us know if production builds have the same problem, or if the problem persists on canary.

**Comment by YoranBrondsema** [comment]
@mmun @stefanpenner I just tried on canary and the problem we had is gone there. Not sure if @dwickern can share the same good news.

**Comment by stefanpenner** [comment]
Unless otherwise reported, lets assume its fixed.
