### ISSUE TITLE
Add waitFor(selector) test helper

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember.js#13025]
A `waitFor` helper would be useful for components that wrap jQuery plugins that take a while to generate their html. The problem is expanded [here](http://stackoverflow.com/questions/35686006/ember-component-how-to-wait-for-random-jquery-plugin-initialization). It could convert this:

```js
let done = assert.async();

click('.button-to-show-component');

setTimeout(() => {
  andThen(function() {
    assert.strictEqual(find('.jquery-stuff').length, 1);
    done();
  });
}, 500);
```
to this:
```js
click('.button-to-show-component');

waitFor('.jquery-stuff');

andThen(function() {
  assert.strictEqual(find('.jquery-stuff').length, 1);
});
```

It would have the same basic signature as the `find` helper. A basic implementation is [here](https://github.com/kellyselden/ember-datetimepicker/blob/d7de77fcdf163a897ad90088d84a451499dd3d9f/tests/helpers/wait-for.js), and it in action is [here](https://github.com/kellyselden/ember-datetimepicker/blob/d7de77fcdf163a897ad90088d84a451499dd3d9f/tests/acceptance/date-time-picker-test-test.js#L23). I could submit a PR if you approve. I don't know if this is an extreme enough addition to warrant an RFC, I will defer to the experts :)

**Comment by pixelhandler** [comment]
@kellyselden perhaps make an RFC issue (not a proposal, just an issue type). See #1 second bullet here -> https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature

> Use RFC issues to propose a rough idea, basically a great place to test the waters

**Comment by stefanpenner** [comment]
RFC is ok, but this should (For now) just be something an addon provides.
