### ISSUE TITLE
willDestroyElement is called after the component is destroyed when using the component helper

### ISSUE THREAD

**Issue by chrisseto** [emberjs/ember.js#13028]
When a component is rendered with the component helper it's `willDestroyElement` hook is called after the element has been removed from the DOM rather than before.

The twiddle contains additional details.

[Ember Twiddle](https://ember-twiddle.com/a97a8db3529bb5899929)

**Comment by krisselden** [comment]
Seems like the teardown path is very different for `{{component "my-component"}}` than it is for `{{my-component}}` stepping through in a debugger.
