### ISSUE TITLE
Ember 2.2 - Components without layouts not working (including link-to)

### ISSUE THREAD

**Issue by cdoornink** [emberjs/ember.js#13020]
We're a bit behind, but I’m trying to update our app which is currently ember 2.1 and I’m running into an issue that is introduced in 2.2. 

I’m getting an error `Uncaught TypeError: Cannot read property 'fragmentReason' of undefined` thats triggered in the htmlbars `component-node-manager.js` file. 

I can get the app to render by adding empty templates for all my components that do not currently have a template but I know this cannot be the actual solution. The worst part is that this error is getting thrown for any instance of `link-to`, `input` and any other built in ember component as well.

It looks like this block of code from `component-node-manager.js` is returning a layout object even when it shouldn’t

```
   // If the component specifies its layout via the `layout` property
   // instead of using the template looked up in the container, get it
   // now that we have the component instance.
   if (!layout) {
      layout = _emberMetalProperty_get.get(component, 'layout');
   }
```

Then as a result, a few lines later when it should just return, it tries to dig into the above layout object which only contains some undefined properties and errors out because layout.meta is undefined

```
  if (!layout) {
    return;
  }

  var fragmentReason = layout.meta.fragmentReason;
```

Feels like I'm missing something really simple like a feature flag or something, especially since this has been out for months and I can't find any other issue close to this. Let me know what other info I might provide to help clear this up. Thanks!

**Comment by krisselden** [comment]
Sounds like the meta is missing from the template because it was compiled with the older version of the ember-template-compiler.  Please use the compiler that matches your ember version and let me know if this fixes the issue.

**Comment by stefanpenner** [comment]
Please be sure your version of the htmlbars compiler is the correct version.

if you are using ember-cli, try `rm -rf node_modules && npm install` in your project. There is a bug which may cause a new htmlbars compiler to use a stale compiled version of the template, but ^ should address.

**Comment by cdoornink** [comment]
I am using ember-cli. I was using `"ember-cli-htmlbars": "0.7.9",`

I switched to `"ember-cli-htmlbars": "^1.0.1",  "ember-cli-htmlbars-inline-precompile": "^0.3.1"` and ran `rm -rf node_modules && npm install` and still am getting the same result. 

I also tried upgrading to `"ember": "2.3.1"` with the same result.

**Comment by rwjblue** [comment]
We will likely need a demo/repro to dig in any more. We all have many apps that work properly on these versions so it is almost certainly something application specific...

**Comment by cdoornink** [comment]
I was stripping down the app to its skeleton and I found the issue. I had a service named 'layout', which I assume has become an internal service name in Ember now. Changing the name fixed everything.

**Comment by stefanpenner** [comment]
@cdoornink ah, seems like we need to assert against that collision somewhere..

**Comment by kbullaughey** [comment]
For others who might encounter the error, `Uncaught TypeError: Cannot read property 'fragmentReason' of undefined`, in my case, I just needed to blow away `tmp` and restart my app and it is working properly.

**Comment by mixonic** [comment]
We should have a better error message for when a property of layout exists on a component and is not a template. This much seems easy to add.

**Comment by locks** [comment]
Closing as there is a PR that addresses the agreed resolution for this problem. Thanks everyone!
