### ISSUE TITLE
Ember input values not being bound to controller when dynamically created from model

### ISSUE THREAD

**Issue by astronomersiva** [emberjs/ember.js#13035]
When I create an input with the value attribute generated from the model, accessing that value attribute from inside the controller using `this.get(valueName)` returns undefined.

[JSFiddle](http://emberjs.jsbin.com/luzisibuxo/edit?html,css,js,output)

**Comment by pixelhandler** [comment]
@astronomersiva 'red' is not a property defined in the controller in your example. There is no code dynamically creating a contoller's 'red' property in the jsfiddle example.

Perhaps join the embercommunity.slack.com chat rooms and ask about the behaviors you are trying develop.

**Comment by pixelhandler** [comment]
@astronomersiva I'll close this out as it doesn't appear to be an Ember.js bug
