### ISSUE TITLE
clippath is not working

### ISSUE THREAD

**Issue by BryanHunt** [emberjs/ember.js#13032]
I'm using Ember 2.3.1

I have code that defines a clippath under an svg and then later references that clippath in a group element by url, but the clip path is ignored:

```
<svg id="ember451" width="550" height="550" class="ember-view">  
  <defs>
    <clipPath id="ember460" class="ember-view">    
      <rect x="45" y="25" width="450" height="450"></rect>
    </clipPath>  
  </defs>
  <g id="ember508" transform="translate(45,35)" clip-path="url(#ember460)" class="ember-view">
    ...
  </g>
</svg>
```

If you cut/paste the Ember generated html, the clip path works just fine.  You can see an example of this in the repo: https://github.com/BryanHunt/ember-d3-components  Go the the xy plot route and you should see the line plot clipped, but it is not.  When pasting the html to a file, you get (ignore the lack of CSS):

<img width="538" alt="svg_html" src="https://cloud.githubusercontent.com/assets/504299/13438235/c6bcc952-dfad-11e5-8997-ffb05455beb1.png">

When rendered by Ember, you get:

<img width="550" alt="dummy" src="https://cloud.githubusercontent.com/assets/504299/13438254/dbe95c64-dfad-11e5-9171-5478e0b87ff8.png">

**Comment by SpikedKira** [comment]
Also, adding a working example svg element's html structure to this page will also not clip while the same html works on other pages. (static, non-ember-generated)

**Comment by BryanHunt** [comment]
I've pulled out the dummy app from the repo.  To reproduce this problem, grab the following commit: https://github.com/BryanHunt/ember-d3-components/tree/6f5dd0caf0f1b0308971aaee4ed62ecc3d631101

**Comment by BryanHunt** [comment]
After a discussion with @SpikedKira, I tried an experiment and found that clip path will work if the SVG is rendered on the application (root) route, but fails to work when the SVG is rendered on any other route.  Here is another option for reproducing the problem:  https://github.com/BryanHunt/ember-d3-charts

**Comment by mixonic** [comment]
@BryanHunt can you check the namespace and capitalization of a rendered `clipPath` element? The two things I expect could go wrong would be:

* Wrong namespace
* Capitalization HTML tags is not meaningful, but for SVG is meaningful. It is plausible the wrong fork of code is being run. This would mean `linearGradient` would also not render correctly.

**Comment by SpikedKira** [comment]
That has been checked.  I tried to build a twiddle, but it seems that all routes (including root) are handled like subroutes in twiddle.

You are welcome to double check: https://ember-twiddle.com/dbb60fb587943eb582f0?openFiles=test.template.hbs%2C&route=%2Ftest

If you copy the svg structure to a static page, you will certainly get a different image.

**Comment by mixonic** [comment]
@SpikedKira "That has been checked", sorry, what was checked? What was the outcome of checking?

**Comment by mixonic** [comment]
Ah, this seems related to `url(#ember460)`. There are known issues with `<base` and SVG ids: http://www.chriskrycho.com/2015/html5-location-base-and-svg.html I suggest creating an Ember demo without a `<base` tag and confirming correct behavior there.

Ember-Twiddle does not use `<base` inside the iframe, but does on the outer page. I'd like to see it eliminated completely as a possible culprit though, which probably means created a reproduction without Twiddle.

**Comment by SpikedKira** [comment]
Yeah, basically this: https://github.com/ember-cli/ember-cli/issues/2633#issuecomment-94961938

**Comment by BryanHunt** [comment]
Ok, use the the absolute URL for the clip-path seems to work:

```javascript
export default D3Group.extend({
  attributeBindings: ['transform', 'clip-path'],

  'clip-path': computed('parentView.clipPath', function() {
    return `url(${window.location.href}${this.get('parentView.clipPath')})`;
  })
});
```

**Comment by mixonic** [comment]
I'm going to close this in favor of https://github.com/ember-cli/ember-cli/issues/2633, as what is happening (regardless of how wise we think it is) remains a designed browser behavior for interaction with the `<base>` tag. Thanks!
