### ISSUE TITLE
API for iterating over computed properties

### ISSUE THREAD

**Issue by chrisjshull** [emberjs/ember.js#13039]
Please expose a public API for iterating over computed properties.

CoreObject.eachComputedProperty is marked private.

**Comment by rwjblue** [comment]
Can you please provide your use case?

**Comment by stefanpenner** [comment]
It's worth noting, ember-data and likely other libraries use this API, it is essentially public. We may want to consider making it so.

**Comment by pixelhandler** [comment]
:+1:  for eachComputedProperty as **public**. Here is my use case. In a data persistence library I need to set meta on computed properties and for some computed properties of the Ember Object instance I need to setup data for related objects. see -> https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/addon/models/resource.js#L495-L512

**Comment by mmun** [comment]
Could we expose it as a static method instead?

```js
Ember.Object.eachComputedProperty(obj, callback)
```

**Comment by stefanpenner** [comment]
Ember.Reflect.eachComputedProperty aligned with ES MOP functions

**Comment by stefanpenner** [comment]
Ember.Reflect.eachComputedProperty aligned with ES MOP functions

**Comment by rwjblue** [comment]
YA, I'd prefer a static method form as public.  Lets pursue this in an RFC though (as it adds new public API).

Closing this issue...

**Comment by lolmaus** [comment]
What happened to `eachComputedProperty` in Ember 3.x? It seems to still work, but it is no longer mentioned in API docs. Private again?

Also, I failed to find the RFC entry mentioned above.
