### ISSUE TITLE
API for iterating over component children

### ISSUE THREAD

**Issue by chrisjshull** [emberjs/ember.js#13040]
Please expose a public API for iterating over a component's child components.

#childViews is marked private.

#forEachChildView is not marked at all.

**Comment by rwjblue** [comment]
Child views doesn't actually work anyways :trollface:

**Comment by stefanpenner** [comment]
As views themselves are deprecated, this is unlikely to happen.

I think it is reasonable to ask for a snapshot of children (from a component) and provide something useful. That snapshot wont remain live, but each invocation would be accurate at invocation time.

If someone is interested, this should be proposed as an rfc
