### ISSUE TITLE
Regression in `Ember.String.classify` in ~2.1

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#13042]
In Ember 1.13 and 2.0, `Ember.String.classify("be a teacher");` generates `"BeATeacher"`
In Ember 2.4, `Ember.String.classify("be a teacher");` generates `"BeA Teacher"`

I've tracked the bug down to this commit: https://github.com/emberjs/ember.js/commit/85d725c61f3b43a630d1f806c7d0824b3c299d0e

Here is a jsbing containing the both codes to see the issue. Switch between the old and new implementation by commenting/uncommentiong to see the error in action.

http://jsbin.com/xeloxuw/edit?js,console

**Comment by cibernox** [comment]
@skeate I tried to play with the regular expression but it is really over my head. Perhaps you want to take a look at it.

**Comment by skeate** [comment]
Checking it out now.

**Comment by acorncom** [comment]
There is a PR for this issue, but we need help testing it (see the PR for details)

**Comment by kamilogorek** [comment]
It looks like mentioned PR has been already resolved – https://github.com/emberjs/ember.js/pull/13044

**Comment by cibernox** [comment]
@kamilogorek But it's not merged. The only concern was performance?

**Comment by kamilogorek** [comment]
@cibernox main issue was that tests were not passing on Travis and as you mentioned, performance. Tom already approved small performance decrease and tests are passing as well so it should be good to merge.

**Comment by rennomarcus** [comment]
Should this be closed? It looks like the core team decided to not merge the PR (?)

**Comment by Serabe** [comment]
Yes. Also there is the whole Ember.String deprecation thing going on.

Thank you all!
