### ISSUE TITLE
Regression 2.4.x wrong block param value {{with}} helper

### ISSUE THREAD

**Issue by jcbvm** [emberjs/ember.js#13045]
Block param used in with helper returns wrong value (truthy value instead of object) when used for example with a belongsTo relationship of a model as block param.

JSBin: http://emberjs.jsbin.com/vetezutapa/3/edit?html,js,output

**Comment by rwjblue** [comment]
Thank you for opening the issue, I'll take a look to see if I missed the fixing commit in the 2.4 branch.

**Comment by luxferresum** [comment]
I can confirm this. `{{#with objectProxy as |data|}}` will result in `data` being true.

**Comment by lozjackson** [comment]
I can also confirm this.  I have created an app that demonstrates the problem with a failing test.

**Comment by rwjblue** [comment]
We have a fix, which should be released in a couple days...

**Comment by lozjackson** [comment]
is there a branch I can try so I can (help) test the fix?

**Comment by rwjblue** [comment]
@lozjackson - The fix just landed and should be available for testing in canary, beta, and release builds within a few minutes.  You can test release via `bower install --save ember#release` (it will be what becomes 2.4.2).

**Comment by lozjackson** [comment]
thanks.. I can confirm that it fixes the bug.
