### ISSUE TITLE
Query params not available in controller until child model has finished loading

### ISSUE THREAD

**Issue by mdentremont** [emberjs/ember.js#13052]
I'm trying to set certain pieces of my template using the query param values on my controller.

The query params are only set once the model has returned, which is causing me some issues.

My workaround is to call the controller.setProperties, passing along the routes params.

See ember-twiddle demo here: https://ember-twiddle.com/640c651c247921a6ba66?openFiles=index.controller.js%2C&route=%2F%3Ftest%3DVALUE

EDIT:
I have updated the title to indicate that the issue is actually that the parent controller doesn't get its own query params until all its child routes have loaded.

See updated demo here:
https://ember-twiddle.com/d7170df50dd7734aff67?openFiles=root.nested.template.hbs%2C&route=%2Froot%2Fnested%3Ftest%3DPARAM

**Comment by pixelhandler** [comment]
@mdentremont Query params are passed to the model hook as the first argument in the route. The controller is not setup until the model hook(s) promises are resolved in the route's setupController method. So if you need to know the query params in the route you can, in the model hook. Otherwise the controller is not setup until the model hook is resolved. This is the design and expected behavior in Ember.

**Comment by mdentremont** [comment]
@pixelhandler: This case is a bit tricky, as the model for the parent route has already resolved, but for some reason the query params are not available to it until the child route has also resolved.

This seems wrong, as the parent route is rendered and onscreen before the query params are available to it.

**Comment by svox1** [comment]
I have the same bad behaviour:

In the application route in beforeModel:
```
console.log(transition.queryParams);
```

Output is:
```
Object {param: "something"}
Intermediate-transitioned into 'loading'
Object {}
Intermediate-transitioned into 'loading'
```

**Comment by pixelhandler** [comment]
@mdentremont it seems that the promise resolution and rendering timing contribute to the behavior you demonstrated in the example you provided. 

I forked the example here https://ember-twiddle.com/32d83d07597c9a0bcfd1a662e73cbb73?openFiles=root.template.hbs%2C&route=%2Froot%2Fnested%3Ftest%3DPARAM to show that you can access the params in the parent template. 

I'll close this for now. Feel free to reopen if necessary.
