### ISSUE TITLE
Input helper with input action throws error

### ISSUE THREAD

**Issue by danevans** [emberjs/ember.js#13058]
Using something like:
```hbs
{{input type="text" value=newName input="updateName"}}
```
Causes an exception (`Uncaught TypeError: method.apply is not a function`) to be thrown.

It's using [this form](https://guides.emberjs.com/v2.4.0/templates/input-helpers/#toc_actions) with the event name as `input` which is listed in [valid event names](http://emberjs.com/api/classes/Ember.View.html#toc_event-names).

It appears that in the `trigger` method within Ember's `CoreView`, `this[name]` is getting resolved to the string `"updateName"` instead of the method with that name.

Working example here: https://ember-twiddle.com/4bd4b572617660d467dd

**Comment by GCorbel** [comment]
I checked events available on inputs on Chrome and `input` is not listed. I'm not able to find a documentation on this event. Do you have something?

Here is the list of events available on Chrome : 
![capture du 2016-03-15 17 12 01](https://cloud.githubusercontent.com/assets/1296201/13794233/4a4e493e-ead1-11e5-8eef-dc45d8af280d.png)

**Comment by GCorbel** [comment]
Oups, sorry. `input` is in the list.

**Comment by pixelhandler** [comment]
I'm curious if this is related, https://github.com/emberjs/ember.js/issues/11678

**Comment by cibernox** [comment]
@danevans If your are in 2.3.1+ i'd strongly recommend to use this instead:

`<input type="text" value={{newName}} oninput={{action "updateName"}}>`

**Comment by danevans** [comment]
@cibernox is the recommendation to not use the `{{input}}` helper at all or just avoid it when using actions or just certain actions like this one?

**Comment by cibernox** [comment]
@danevans I don't use it anymore. `{{input}}` is harder to use an around 40x slower

**Comment by locks** [comment]
I am closing this issue because my understanding is a resolution has been reached.
Feel free to re-open the issue if you think it's still justified, thank you!
