### ISSUE TITLE
ds-references stripped from production?

### ISSUE THREAD

**Issue by richmolj** [emberjs/ember.js#13054]
I'm using the new `ds-references` feature flag from ember-data 2.4. Everything works in development, but in production it looks like the code is not being applied:

From console:

```
> EmberENV.FEATURES
>> Object {ds-references: true}
> model._internalModel.referenceFor
>> undefined
```

**Comment by rwjblue** [comment]
Seems bad, but is likely an issue in emberjs/data though. 

Would you mind reopening over there?
