### ISSUE TITLE
Can we make `lookupFactory` public on `ContainerProxyMixin`?

### ISSUE THREAD

**Issue by workmanw** [emberjs/ember.js#13065]
I'm not sure if this would be more appropriate as an RFC issue, if so I'd be happy to move it over there.

With [ember-data-model-fragments](https://github.com/lytics/ember-data-model-fragments) we have to rely on the private varation `_lookupFactory` to lookup fragment classes, see: [ember-data-model-fragments/.../ext.js](https://github.com/lytics/ember-data-model-fragments/blob/557f4a288a6966fb4e8df48a80871ae11a17eea0/packages/model-fragments/lib/fragments/ext.js#L319-L327)

This was part of the container API originally. And I know that was private and also we don't want to encourage users to be instantiating their own instances, but this is something we could really use for addons.

**Comment by stefanpenner** [comment]
Ya feature requests are rfc or rfc isshes

**Comment by workmanw** [comment]
I wasn't sure because there are a few issues of this nature still open eg #13039. But I'm happy to open this in the RFC repo.
