### ISSUE TITLE
Service Injection doesn't work in v2.4.1

### ISSUE THREAD

**Issue by iAchilles** [emberjs/ember.js#13063]
Ember v2.4.1
Steps to reproduce:

1. ember new app
2. ember g route index
3. ember g service srv
4. Edit /routes/index.js

```js
import Ember from 'ember';

export default Ember.Route.extend({
    srv: Ember.inject.service('srv'),
});
```

The next steps:
5. ember s
6. Open url: http://localhost:4200
7. Open console, you can see the error: 

> Error: Attempting to inject an unknown injection: service:srv

**Comment by iAchilles** [comment]
In Ember v2.3.1 it works fine without any errors.

**Comment by stefanpenner** [comment]
closed, is this resolved?

**Comment by justinhhorner** [comment]
I could not reproduce this issue.

**Comment by iAchilles** [comment]
@stefanpenner, yep, in my case the issue is resolved by upgrading ember-cli to the latest release:

    

> npm uninstall -g ember-cli -- Remove old global ember-cli
>     npm cache clean -- Clear NPM cache
>     bower cache clean -- Clear Bower cache
>     npm install -g ember-cli@2.4.2 -- Install new global ember-cli
> 
> Project Update
> 
>     rm -rf node_modules bower_components dist tmp -- Delete temporary development folders.
>     npm install --save-dev ember-cli@2.4.2 -- Update project's package.json to use latest version.
>     npm install -- Reinstall NPM dependencies.
>     bower install -- Reinstall bower dependencies.
>     ember init
