### ISSUE TITLE
2.4.1 Ember.run.later() does not execute 

### ISSUE THREAD

**Issue by EVASIVE** [emberjs/ember.js#13070]
Code that can you see below does not work. Tested with 2.4.1, 2.4.2. In 2.0.1 works fine.  
```
Ember.run.later(this, function(){
 //will not execute
}, 150);
```

**Comment by rwjblue** [comment]
Seems to work properly here: https://ember-twiddle.com/c4a66a088af0aa59db81?openFiles=application.route.js%2C.

Please provide a reproduction/demo showing the issue...

**Comment by EVASIVE** [comment]
Sorry guys for long answer. Yeah, thanks for example @rwjblue it really works in twiddle and in clear test project. But when i used mentioned code sample in existed project, it does not executes properly. Need some more time for debugging and researching problem.

**Comment by acorncom** [comment]
@EVASIVE We've been working on cleaning up the issue backlog for ember.js, so for now, I'll close this issue.  But if you find it's still an issue, feel free to comment here or open a new issue 👍
