### ISSUE TITLE
run.backburner.debug utility not clear from docs

### ISSUE THREAD

**Issue by chriskrycho** [emberjs/ember.js#13074]
I spent a bunch of time hunting down a bug yesterday which would have been _much_ easier to find with `Emberrun.backburner.DEBUG = true` set. Unfortunately, I only discovered that when I went looking for something _else_, because the docs only say this currently:

> #### Errors within Ember.run.later (Backburner.js)
> 
> Backburner has support for stitching the stacktraces together so that you can track down where an erroring Ember.run.later is being initiated from. Unfortunately, this is quite slow and is not appropriate for production or even normal development.
> 
> To enable this mode you can set:
> 
> ``` js
> Ember.run.backburner.DEBUG = true;
> ```

The source is a bit more illuminating:

``` js
//
//    ** Attention intrepid developer **
//
//    To find out the stack of this task when it was scheduled onto
//    the run loop, add the following to your app.js:
//
//    Ember.run.backburner.DEBUG = true; // NOTE: This slows your app, don't leave it on in production.
//
//    Once that is in place, when you are at a breakpoint and navigate
//    here in the stack explorer, you can look at `errorRecordedForStack.stack`,
//    which will be the captured stack when this job was scheduled.
//
```

In general, the debugging section is a little sparse. (I'm happy to expand on the Backburner bit with a PR that includes some of the description from the source, but don't yet know enough to elaborate other parts of the debugging material.)

**Comment by pixelhandler** [comment]
@chriskrycho This is documented here: https://guides.emberjs.com/v2.4.0/configuring-ember/debugging/#toc_errors-within-code-ember-run-later-code-a-href-https-github-com-ebryn-backburner-js-backburner-js-a

**Comment by chriskrycho** [comment]
@pixelhandler, that's my point—that's the section I quoted above!

**Comment by pixelhandler** [comment]
@chriskrycho perhaps join the embercommunity.slack.com #documentation chat room and ask about helping with making a PR on the topic of debugging in Backburner. The documentation team can point out where in the http://github.com/emberjs/guides repo you could update.

**Comment by pixelhandler** [comment]
@chriskrycho @locks this issue seems stale, I'll close it for now. Feel free to re-open if you feel it's necessary.
