### ISSUE TITLE
Object property retrieved through helper is not updating when value changes

### ISSUE THREAD

**Issue by elanclarkson** [emberjs/ember.js#13078]
I have created a helper in order to extract the value from an object when the property name is in a variable - this is a very similar set up to the question/answer I found here: http://stackoverflow.com/questions/22045461/get-property-by-variable-name

The problem is this value doesn't appear to be changing when it is updated once it has been run through the helper.

I have simplified this and created a demo script below. In this example, when you click the "Change value" button only the variable that was 'hard-coded' updates, and the value that is extracted through the helper remains as the old value.

https://ember-twiddle.com/ec18d0963218d692de02?numColumns=3&openFiles=helpers.get-value.js%2Capplication.controller.js%2Capplication.template.hbs

**Comment by btecu** [comment]
Can't you just use native helper?
`{{get testObject 'property1'}}`

**Comment by btecu** [comment]
If you must use your own, you could do:
`this.notifyPropertyChange('testObject');`

It doesn't work in current form because you're changing properties of an object but only the object is observed, not its properties.

**Comment by elanclarkson** [comment]
Ah I didn't realise there was a native helper for this - that works just great. Thanks so much!

Sorry this wasn't a bug; that makes sense that only the object is observed now that you mention it.

P.S. Feel free to take the stackoverflow points on that question I found, otherwise I might point out this answer there too. :)

**Comment by locks** [comment]
I am closing this issue as the above comment by OP seems to indicate the problem has been resolved.
Feel free to re-open the issue if you think it's still justified, thank you!
