### ISSUE TITLE
Data store queries overwrite if they are fetching the same model type 

### ISSUE THREAD

**Issue by vkoves** [emberjs/ember.js#13086]
To start off, let me explain what I am trying to do. I have an API that I am accessing that only lets me access items one at a time. To fetch ten items, I wrote an iterator to go through and call the API ten times. However, I found that although right after the calls returned, the values were correct, after storing the promises and calling Ember.RSVP.allSettled, all of the promises somehow had the same value.

Here's an example:
```
var iterPromise1 = thisTop.store.query('venue', '<venueID>'+(iterStart+1)+'</venueID>');
arr.push(iterPromise1);
var iterPromise2 = thisTop.store.query('venue', '<venueID>'+(iterStart+3)+'</venueID>');
arr.push(iterPromise2);
```

The second parameter is an XML statement that gets inserted into the API call, and thus these queries are distinct.

If I put a then statement after each promise and then print the values to the console, these yield distinct objects. However, no matter how many times or how I do this, the value of each promise transforms into the last fetched item. However, if I change the promises to fetch a different type of object, such as:

```
var iterPromise1 = thisTop.store.query('event', '<venueID>'+(iterStart+1)+'</venueID>');
var iterPromise2 = thisTop.store.query('venue', '<venueID>'+(iterStart+3)+'</venueID>');
```

Then they will have distinct values as I would expect. Is this behavior intentional? Am I somehow misusing promises? As mentioned before, I then try and print the values of these promises using allSettled, and the values are the same if the model is the same, even though the API returns different data, and the queries are different. If someone wants to look at our adapters, I'll happily post some details about that too.

**Comment by pixelhandler** [comment]
@vkoves it's difficult to troubleshoot without seeing a code example. The repos / docs are here https://github.com/tildeio/rsvp.js and http://emberjs.com/api/classes/RSVP.Promise.html 

```javascript
Promise.all([
  getJSON('/posts'),
  getJSON('/comments')
]).then(function(values){
  values[0] // => postsJSON
  values[1] // => commentsJSON

  return values;
});
```

each resolved promise should return it's data, and all the resolved promises should be available in the `values` array like so `Promise.all([...]).then(function(values))` .

**Comment by pixelhandler** [comment]
@vkoves I don't think this is a bug in Ember. I'm curious about how you used RSVP. Can you post an http://ember-twiddle.com code example to demonstrate your issue?

**Comment by pixelhandler** [comment]
@vkoves perhaps reach out in the community chatroom or even StackOverflow to see what solutions others have found. 

I know there are many developers working heavily with Promises; so, I expect there should be some ideas available in the slack help channel.

If you do have a code example that reproduces your issue; and a way others can view the sample code in action… then you might get more feedback.

I'll close this out for now. If you'd like to discuss further perhaps reach out in the http://embercommunity.slack.com #-help channel to chat regarding the specific version your app is using; and potential solutions.

(Also worth investigating is the ember-concurrency addon.)

**Comment by vkoves** [comment]
I'm afraid I'm not skilled enough with Ember to recreate the issue easily, but I'll take a look at that now. I ended up just using then statements to run the promises consequently instead of concurrently, but I'll take a look at this again.
