### ISSUE TITLE
Remove `ember-application-visit` feature guards

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#13088]
The feature has already been enabled on the release channel a while ago, so we should...

1. Remove it from FEATURES.md
2. Remove it from features.json
3. Remove all the `isEnabled('ember-application-visit')` guards (and fallback code) in the codebase

**Comment by shashwat91** [comment]
Created a PR #13100 for this issue.

**Comment by josemarluedke** [comment]
I think this can be closed as #13100 is merged.

**Comment by chancancode** [comment]
Thank you all!
