### ISSUE TITLE
Please release ember-source gem 2.4.2

### ISSUE THREAD

**Issue by tricknotes** [emberjs/ember.js#13111]
Could someone release ember-source 2.4.2 to rubygems.org?
This issue was reported as https://github.com/emberjs/ember-rails/issues/515 by @gerry3

**Comment by rwjblue** [comment]
Ya, we'll get it fixed (on Monday at the latest)...

**Comment by gerry3** [comment]
@rwjblue thanks! btw, was there an issue? is the process not automated? can i help somehow?

**Comment by pixelhandler** [comment]
@rwjblue @gerry3 would be great to automate the gem release process, this once pops its head up every so often.

**Comment by rwjblue** [comment]
This is published. We have reformed a release team, and have been adding pieces of automation during each run through. Completely automating gem publishing is definitely on our list.
