### ISSUE TITLE
NPM loops forever when starting new ember project

### ISSUE THREAD

**Issue by CodeStrider35** [emberjs/ember.js#13110]
![capture](https://cloud.githubusercontent.com/assets/12943278/13800398/23dd1996-eae6-11e5-9346-c7a33da7ef88.PNG)
ember new projectname -seems to work fine until "installing packages for tooling via NPM" then it loops forever, just keeps on saying the same thing over and over again. Node.js is up-to-date and NPM is on its current version. 3.8.2

**Comment by stefanpenner** [comment]
please provide all the information requested [here](https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md#reporting-a-bug)  (that link is the big yellow banner you see when submitting)

**Comment by CodeStrider35** [comment]
Thanks for the tip - I'll make sure to follow those instructions next time - I made sure all tools were up-to-date including git and I still got the same "looping" behavior in the git bash console. However it finished and making my new project and everything works as expected when running "ember serve". 

Closing issue.
