### ISSUE TITLE
Value Binding not working Ember 2.4

### ISSUE THREAD

**Issue by devotox** [emberjs/ember.js#13128]
```
import Ember from 'ember';

import AfterRender from 'platform-base/mixins/after-render';

export default Ember.Component.extend(AfterRender,{
	items: [],

	editableMaxLength: 100,

	editableClass: 'content',

	editModeBinding: 'platform-base.application.editMode',

	afterRenderEvent() {
		console.log(this.get('editMode'));
		this.$().on('click', '.content[contenteditable="true"]', event => {
			event.stopImmediatePropagation();
		});
	},
	actions: {
		endEdit(contentEditable, event) {
			event.preventDefault();
			contentEditable.element.blur();
			window.getSelection().removeAllRanges();
		},
		itemEdited(item) {
			Ember.run.cancel(this.edit_timeout);
			this.edit_timeout = Ember.run.debounce(this, () => { this.sendAction('item-edited', item); }, 1000);
		},
		itemClicked(item) {
			Ember.run.cancel(this.click_timeout);
			this.click_timeout = Ember.run.debounce(this, () => { this.sendAction('item-clicked', item); }, 0);
		},
		audioRecorded(item, meta) {
			Ember.run.cancel(this.audio_timeout);
			this.audio_timeout = Ember.run.debounce(this, () => { this.sendAction('audio-recorded', item, meta); }, 0);
		}
	}
});
```

I have a component with a value binding on the application controller editMode key. This does not seem to work at all

**Comment by rwjblue** [comment]
1) You should be using an alias (Ember.computed.alias) instead of the older legacy fooBinding syntax.
2) Your debounces will not work correctly, because you are passing an anonymous function to them. The way debounce works is by comparing the function equality (via ===) and since you are generating a new "() => {}" each time they will not be debounced. 
3) I do not see where 'platform-base' is defined in this component 
4) It is not generally a good idea to store arrays on the prototype (items above), you should instead set "this.items = []" in init.

**Comment by devotox** [comment]
@rwjblue Thank you for the quick feedback. I will update 

1. I don't see how Ember.computed.alias would help me get the value from the application controller.

2. I actually needed to use Ember.run.later as I need to send an action with a context and there is no way for debounce to work in this scenario.

3. platform-base is the name of the application it was the same thing i used in `import AfterRender from 'platform-base/mixins/after-render';`

4. items get set in the components hbs file but I wanted to have a default. and running on init overwrites what is sent into the component

**Comment by devotox** [comment]
@rwjblue thank you! you did lead me on the right path using a service I was able to connect changes across all object ... seems so obvious now!

My final solution was to create a global application service

```
	application: Ember.inject.service(),

	editMode: Ember.computed.alias('application.editMode'),
```

And within my application Route

```
         actions: {
	 	toggleEditMode(toggleOn, toggleName) {
			if(toggleName != 'editMode') { return; }
			this.get('application').set('editMode', toggleOn);
		},
```

I am really trying not to use controllers as much as possible to follow the component led path Ember is blazing and it just takes slightly different mindset. 

I also changed all the debounces to Ember.run.later and removed the items array and the template consuming the component will just have to make sure to define an items array.


Again thank you for this and if you think this is still a wrong way of doing it please inform me as I want to continuously make sure my code is compliant with up to date patterns.
