### ISSUE TITLE
Failed to run `npm start` - Cannot find module 'exists-sync'

### ISSUE THREAD

**Issue by code0100fun** [emberjs/ember.js#13142]
```
Could not require 'ember-cli-build.js': Cannot find module 'exists-sync'
```
Seems like c655638 caused a build error when it updated the [`package.json`](https://github.com/emberjs/ember.js/blob/c6556381a56f0c7fd72ed9c2ab8cf1bea08823fd/package.json#L41)

Looks like its related to `tildeio/glimmer` requiring [`exists-sync`](https://github.com/tildeio/glimmer/blob/9dff505688b917fdc7209f2dde4061d69464e50c/ember-cli-build.js#L4) in `ember-cli-build.js` but not listing it as a dependency in its `package.json`

**Comment by rwjblue** [comment]
Ya, glimmer needs to be updated with it as a dep.  This almost certianly works on npm 3 because everything ends up in the root/main `node_modules/` but on npm 2, you would be missing `exists-sync` at that level.

**Comment by Dhaulagiri** [comment]
Opened https://github.com/tildeio/glimmer/pull/115 for this

**Comment by HeroicEric** [comment]
@Dhaulagiri should this be closed now since https://github.com/tildeio/glimmer/pull/115?

**Comment by Dhaulagiri** [comment]
I think it would still be a problem in ember since ember is pointing at an older release, but there isn't much to be done about it until more glimmer work lands

**Comment by rwjblue** [comment]
Confirm, not much we can do until we get updated to a later SHA (and that requires some intricate knowledge of the changes in glimmer and how they relate to Ember).  Should be worked out in the next few days I believe...
