### ISSUE TITLE
queryRecord returns array, expect single record

### ISSUE THREAD

**Issue by MarkMT** [emberjs/ember.js#13155]
According to the description of `queryRecord` in the [guides](https://guides.emberjs.com/v2.4.0/models/finding-records/)  (emphasis added) -

> If you know your query will return only one result Ember Data provides a convenience method that will return a promise that resolves with **a single record**. Calling `store.queryRecord()` will make a `GET` request with the passed object serialized as query params.

However what I'm seeing in practice is that the return value actually resolves to an _array_ with as many elements as fit the query (and it appears to be a regular javascript array not an Ember.Array). So if I want to use the method in a model I have to do something like this -
```
export default Ember.Route.extend({
  model() {
    return this.store.queryRecord('person', {filter: {name: 'foo'}}).then(function(result) {
      return result[0].get('data');
    });
  }
});
```
It works, but it doesn't seem consistent with what's advertised. The only difference I'm seeing from `query` is that the latter returns an Ember.ArrayProxy rather than a javascript array.

**Comment by stefanpenner** [comment]
you likely meant: https://github.com/emberjs/data/issues/new

**Comment by MarkMT** [comment]
Ah, indeed, thank you!
