### ISSUE TITLE
Minor regression in 2.5+ (Test helpers firing native elements)

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#13153]
I discovered that https://github.com/emberjs/ember.js/pull/12575 (Implemented by me) introduced a subtle change.

After that PR,  `click(".btn-submit")` fires a click event on the first element with that class.
Previously it would trigger a many click, in all elements with that class.

I'd personally found this regression **beneficial** in my test suite. I caught three tests that where broken because there was more than one link that matched `:contains("Save")` (probably added after the test was originally written), but it turned out that the assertions after the click weren't specific enough and I was in a totally unexpected route.

I'd say that clicking several items at once is almost always not the intended behaviour and the new behaviour is less error prone, but still this is still a somehow breaking.

**Comment by rwjblue** [comment]
Thanks for opening this to get it out in the open. The current behavior (clicking the first item) seems more correct to me, and the old behavior seems more like a bug.

Acceptance tests are intended to emulate user behavior, and it generally isn't possible for a user to click in many different places at once (no matter how quick the user clicks were they would be separated by at least a millisecond)...

**Comment by cibernox** [comment]
Good, I also think this changes is for the better. 

I'm closing this so people with this problem can find a reference to why their test suite is failing and how to fix it.
