### ISSUE TITLE
QueryParams refreshModel does not work on route without dynamic segments

### ISSUE THREAD

**Issue by WimAtIHomer** [emberjs/ember.js#13150]
I am working on a index route with queryParams that control paging and sorting of table data. When changing the queryParams with the back button the queryParams on the controller are changed but the model is not refreshed.
On a similar page with detail data the refreshModel property on the queryParams are working as expected.
After some testing I found that adding a dynamic seqment (/:id) to my index route solves my problems with the refreshModel. But adding unused dynamic segments to my routes is not a solution that will be accepted in production.
I will try to find the root cause of the problem, but if someone with more knowledge on how the router works can help me that will be great.

**Comment by dennislaumen** [comment]
What does the "Needs Bug Verification" label mean? Is there anything we (I'm a colleague of @WimAtIHomer) can do to help speed up this verification? Thanks in advance!

**Comment by WimAtIHomer** [comment]
I have made a small project that shows the problem https://github.com/WimAtIHomer/queryParams

**Comment by WimAtIHomer** [comment]
@mmun is there anything else I can do for Bug Verification?

**Comment by rwjblue** [comment]
@dennislaumen - The "Needs Bug Verification" label is mostly about reproducing the error in a way we can see/understand (usually ember-twiddle.com or ember.jsbin.com).

**Comment by WimAtIHomer** [comment]
Hi @mmun,

I have made some improvements in my paging and sorting example and the problem I faced does not occur anymore. I believe that there still is a problem in the queryParams code but for now I don't have any problems. So I am closing the issue and will withdraw my PR.

Thanx.
