### ISSUE TITLE
Component's `attributeBindings` with boolean value don't behave as documented

### ISSUE THREAD

**Issue by SaladFork** [emberjs/ember.js#13154]
1) The [`attributeBindings` documentation](http://emberjs.com/api/classes/Ember.View.html#toc_html-attributes) states:
> If the return value of an `attributeBindings` monitored property is a boolean the property will follow HTML's pattern of repeating the attribute's name as its value

However, following the provided example:
```js
export default Ember.Component.extend({
  attributeBindings: [ 'disabled' ],
  disabled: true
});
```
results in:
```html
<div id="ember303" class="ember-view" disabled="true">
```
And not `disabled="disabled"`.

---

2) The documentation then provides an example that shows using a CP to toggle a property between `true` and `false`. When set to false, however, the attribute is not removed as you may expect but instead you get `disabled="false"`. This has been described as [working as intended](https://github.com/emberjs/ember.js/issues/10976#issuecomment-132417731), and `null` or `undefined` should be used instead.

---

We should probably update the documentation (and its examples) to reflect the expected behavior.

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/13157
