### ISSUE TITLE
Component positional params don't update when used with the component helper

### ISSUE THREAD

**Issue by GavinJoyce** [emberjs/ember.js#13158]
I came across this when [porting component helper tests to Glimmer2](https://github.com/emberjs/ember.js/pull/13140).

Twiddle: https://ember-twiddle.com/8bd17b5f64fdf1f400d8

When this is fixed, please uncomment https://github.com/emberjs/ember.js/pull/13140/files#r56916691

**Comment by rwjblue** [comment]
This works properly in the glimmer implementation but not HTMLBars or it doesn't work in either case?

**Comment by GavinJoyce** [comment]
I don't believe positional params have been implemented in glimmer yet

**Comment by GavinJoyce** [comment]
From https://github.com/emberjs/ember.js/issues/13127:

<img width="656" alt="screen shot 2016-03-21 at 19 42 23" src="https://cloud.githubusercontent.com/assets/2526/13940706/2aa348fc-ef9d-11e5-821a-c6c193775cd8.png">

**Comment by pixelhandler** [comment]
@GavinJoyce I'm curious in the twiddle example regarding using `positionalParams` in two separate component that both use `Ember.Component.reopenClass` to do the same thing. Is that how you would used positional params in an app? or would you extend the component then reopenClass ?

**Comment by GavinJoyce** [comment]
@pixelhandler thanks, my mistake. I've updated the twiddle, the bug is still present. I'll update the tests in ember.js too, the currently `Ember.Component.reopenClass`.

**Comment by locks** [comment]
@Serabe can you review?

**Comment by Serabe** [comment]
Yes. A [quick test](https://ember-twiddle.com/6752a23b8899ad87c2e2106be0b26f5d?numColumns=2&openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs) shows that for rest pos params it only updates for the first one (😲). I'm working on other parts of positional parameters, so I'll take a look while at it.

**Comment by Serabe** [comment]
#13435 fixes this problem in HTMLBars. Glimmer 2 support for positional parameters is on its way (#13393) and won't need a fix.
