### ISSUE TITLE
Sum macro does not works with hasMany

### ISSUE THREAD

**Issue by GCorbel** [emberjs/ember.js#13167]
I'm have this model : 

```
import DS from 'ember-data';
export default DS.Model.extend({
  groups: DS.hasMany('group'),
  nbPlaces: Ember.computed.sum('groups.@each.nbPlaces'),
});

```
When I do `model.get('nbPlaces')`, I always have 0. When I do this : 

```
import DS from 'ember-data';
export default DS.Model.extend({
  groups: DS.hasMany('group'),
  nbPlaces: Ember.computed('groups', function() {
    return this.get('groups').reduce(function(sum, group) {
      return sum + group.get('nbPlaces');
    }, 0);
  }),
});
```

it works.

Is there something wrong?

**Comment by jcope2013** [comment]
DS.hasMany('group') is async by default so it won't be resolved in time as it is a promise

**Comment by GCorbel** [comment]
Using `{async: false}` do the same. Data about groups is embed on the json.

**Comment by GCorbel** [comment]
At [this line](https://github.com/emberjs/ember.js/blob/4a404de21d70b780f2ac85b6fb265e037998d2d1/packages/ember-runtime/lib/computed/reduce_computed_macros.js#L22) `arr` is null because the value of `dependentKey` is "groups.@each.nbPlaces" and `this.get("groups.@each.nbPlaces"')` gives null.

**Comment by GCorbel** [comment]
I think adding : 

```
if (/@each/.test(dependentKey)) {
  dependentKeys = dependentKey.split('.@each.');
  this.get(dependentKeys[0]).mapBy(dependentKeys[1]);
}
```

if someone can confirm that there is no other way, I will contribute.

**Comment by rwjblue** [comment]
You should use separate computed properties. The first to make an array of the numbers (via Ember.computed.mapBy) and the second to do the sum on the first (via Ember.computed.sum).

**Comment by rwjblue** [comment]
Closing for now, see my recommendation for a path forward on this...

**Comment by dbinetti** [comment]
Having a slightly different problem, but might be related.  With...

```
export default DS.Model.extend({
  ...
  scores: DS.hasMany('score', {async: true}),
...

  officialScores: Ember.computed.filterBy('scores', 'kind', 'Official'),
  points: Ember.computed.mapBy('officialScores', 'points'),
  pointsSum: Ember.computed.sum('points'),
});
```

I am trying to filter out certain scores as a `hasMany`, map those by the `points` field, and then `sum` those points.  However, if I leave one of those `scores` blank (or, even just enter into the field to change it) the `pointsSum` turns into a large, seemingly random number.  Do I need to use a complicated native `reduce` function, am I missing something, or is this a bug?  

Here is a sample data from the inspector...

```
points: [55, 60, 58, 54, 62, 60, 54, 62, 57, 60, 59, 55, "", 62, 59, __each: EachProxy, __ember_meta__: Meta, __ember1464928822213: "ember16816"]

pointsSum: 6966259
```

Obviously one of the elements in the mapped `points` is returning an empty string; is `Ember.computed.sum` not able to handle this?
