### ISSUE TITLE
textPath not rendering in the right place with Ember

### ISSUE THREAD

**Issue by mikeazo** [emberjs/ember.js#13178]
Here is my twiddle illustrating the issue: https://ember-twiddle.com/fbf7831e0fc1eca012ae?openFiles=my-component.component.js%2C

Here is a fiddle showing what I would expect the output to look like: https://jsfiddle.net/j8ppcwp1/

Notice that the textPath does not show up in the twiddle with Ember (I tried with multiple versions). This is happening in Chrome 49.0.2623.108 and Firefox 45.0.1.

I don't know if this is related to #11091, I tried the suggestion there to change from the `tagName: 'svg'` to a div with the svg element in the template, that did not help.

**Comment by mikeazo** [comment]
I tried this out on a Linux machine running Chrome 48.0.2564.116. In that version of Chrome, the textPath renders in the correct location. In Firefox 45 on that machine the textPath does not show up.

Looking at the [Chrome changelog](https://chromium.googlesource.com/chromium/src/+log/48.0.2564.116..49.0.2623.75?pretty=fuller&n=10000) going from 48 to 49, I found [this issue that was fixed in 49](https://bugs.chromium.org/p/chromium/issues/detail?id=580809&can=1&q=580809&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) that may be related. The fix for that issue may have introduced this issue.

**Comment by pixelhandler** [comment]
@mikeazo that is odd that the SVG works fine in the jsfiddle but not in the ember component. I tried on mac current desktop versions of Chrome and Firefox, (looks like ember-twiddle doesn't work in Safari).

Not sure if that is related to Ember though. The template syntax is correctly rendered in the browser

**Comment by mikeazo** [comment]
@pixelhandler I agree, it is strange. As far as I can tell, the SVGs between the fiddle and twiddle are the same. I don't know if it is a namespace thing, or what. There have been other bugs with SVG namespaces relating to Ember that I found searching previous issues.

**Comment by mikeazo** [comment]
Digging through the Chrome changelog I also found [an issue related to ahem.js and SVG](https://bugs.chromium.org/p/chromium/issues/detail?id=545551#c20). It specifically mentions xlink:href. I mention this because I noticed when I changed my standalone SVG to not have the proper xlink:href I got similar behavior to what I was seeing in the Ember component version.

**Comment by mikeazo** [comment]
FWIW, I tried to recreate with jsbin and the textPath shows up correctly there: http://emberjs.jsbin.com/vabofejuni/edit?html,js,output

Granted, it is not in a separate component like in the other example. I tried making a twiddle that just has the SVG in the application template and I still saw the bug there.

**Comment by mikeazo** [comment]
There is no reason Ember would be [using srcdoc](https://bugs.chromium.org/p/chromium/issues/detail?id=598035#c7) in this case is there?

**Comment by Gaurav0** [comment]
Ember Twiddle is using srcdoc and sandboxed iframe for security reasons. Ember itself does not use srcdoc.

**Comment by mikeazo** [comment]
FYI, I did some more testing and I have figured out the issue. It is the `<base>` tag that Ember uses. There is some info [on this Chrome bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=470608). So, it looks like it is not an Ember specific thing. That said, any good ideas on how to work around this?

**Comment by mikeazo** [comment]
Fixing ember-cli/ember-cli#2633 would fix this even without any changes to Chrome/Firefox.
