### ISSUE TITLE
[Bug] Observing ember data has-many relationship is triggered multiple times

### ISSUE THREAD

**Issue by steffenbrem** [emberjs/ember.js#13170]
When you are observing on ember data `has-many` relationship changes it is called multiple times for a single change.

Here is a live demonstration of the bug (open the console and click on some select options): https://ember-twiddle.com/d848368a8cc5db072174

I've asked several people on Slack about this issue but none had an idea what might be wrong.

**Comment by pixelhandler** [comment]
@steffenbrem I'm pretty sure that is the nature of observers, and one of the reasons the community has a big push to avoid using observers. I would not trust that an observer would only be called once per change, it may be more (as in your example).

In your example I do see the difference between a the frequency of the calls to the observer. But, I think that is normal.

**Comment by krisselden** [comment]
@steffenbrem observers are invalidators, they aren't intended to do work, they are intended to schedule work once.

**Comment by steffenbrem** [comment]
:+1: Makes sense. I should use actions for this I guess instead of relying on the observer system.

**Comment by krisselden** [comment]
You can do `Ember.run.once(this, this.doWork);` inside the observer to schedule work to happen once asynchronously but ensure you don't pass that a new function each call or it will not be uniqued.
