### ISSUE TITLE
Confusing error when using `Ember.computed.or` incorrectly

### ISSUE THREAD

**Issue by courajs** [emberjs/ember.js#13176]
I wasn't thinking very hard, and tried to do:
`Ember.computed.or('someKey', 'tried to put a default string here')`
The error that popped up didn't really inform me what was going on:
> Error: Brace expanded properties cannot contain spaces, e.g. 'user.{firstName, lastName}' should be 'user.{firstName,lastName}'

More helpful would have been an assertion error, something like
> Assertion Failed: Dependent keys passed to Ember.computed.or() can't have spaces

**Comment by courajs** [comment]
Check the console on [this twiddle](https://ember-twiddle.com/f3d7d9d8f45cc8ca77ab?openFiles=application.controller.js%2C) to see current behavior

**Comment by pixelhandler** [comment]
@courajs yeah I see that error in the console of our twiddle example, seems near impossible to match that up to the offending code.

This seems like a feature/enhancement request. See [CONTRIBUTING.md#requesting-a-feature](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature) which suggests to use an RFC Issue to suggest a feature/enhancement (no need for a PR with RFC, only an issue in the repo)

**Comment by rwjblue** [comment]
Agreed, I think it should be possible to make this assertion more understandable.  I'm going to label this and leave it open for a bit to see if we have any takers...

**Comment by courajs** [comment]
@pixelhandler, from [the rfcs readme](https://github.com/emberjs/rfcs/blob/master/README.md):
> Many changes, including bug fixes and documentation improvements can be implemented and reviewed via the normal GitHub pull request workflow.
Some changes though are "substantial", and we ask that these be put through a bit of a design process and produce a consensus among the Ember core team.

This seemed more like a documentation improvement than a "substantial" feature that would need a design process. Maybe I'm wrong? [Requesting a feature](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature) does seem to imply that *all* feature requests require an rfc.

**Comment by rwjblue** [comment]
YA, agree. This is a "bad error message" bug.

**Comment by eddify** [comment]
I'll take a stab at this one

**Comment by courajs** [comment]
@eddify cool! If you didn't know, we do like to unit test asserts. For example, [here][expand-test] is the test for the confusing error we currently get.

[expand-test]: https://github.com/emberjs/ember.js/blob/ed298ced885b2f4b4435fbccb26b24b9a24bb68f/packages/ember-metal/tests/expand_properties_test.js#L89
