### ISSUE TITLE
Deprecate `Ember.Handlebars.SafeString`.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#13191]
Suggest using `Ember.String.htmlSafe` over `Ember.Handlebars.SafeString`: 

```js
// deprecated
new Ember.Handlebars.SafeString(someString);

// Non-deprecated
Ember.String.htmlSafe(someString);
```

For a few reasons:

* The `SafeString` API is a tad bit "trolly" (many questions arise from it "not working" due to forgetting to use `new`).
* The `Ember.Handlebars` namespace is basically legacy and going away

---

The steps needed for this are:

- [ ] Change [this](https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/compat.js#L9) to use `deprecateFunc`.
- [ ] Add an entry to the [2.x deprecation guide](https://github.com/emberjs/website/blob/master/source/deprecations/v2.x.html.md)
- [ ] Link to that deprecation guide entry in the deprecation added above.

**Comment by willrax** [comment]
Is this still up for grabs?

**Comment by acorncom** [comment]
Looks like this issue can be closed?
