### ISSUE TITLE
Wildcard / globbing routes broken on canary

### ISSUE THREAD

**Issue by workmanw** [emberjs/ember.js#13211]
I was trying to test out Ember 2.6 with our app. I noticed that all my deep links were broken and ended up at our 404 page. It turns out that ember was always transitioning to our wildcard routing regardless of other valid routes. I bisected the change down to this commit: 6bef08b45. Not surprisingly, changing the route-recognizer back to "0.1.5" and rebuilding ember, it seems to restore this functionality. 

I tried to build a reproduction, but the conference Lie-Fi isn't making this too easy. I will try later on tonight.

https://guides.emberjs.com/v2.4.0/routing/defining-your-routes/#toc_wildcard-globbing-routes

-----
EDIT:

Here is a repo of the issue: https://github.com/workmanw/wildcard-routing
Here is a build of that app running: https://workmanw.github.io/wildcard-routing

Reproduction is simple.

1. Click "Deep Link"
    ** Notice the URL

2. Refresh the page.
    ** Notice that the URL is the same, but you're on the "404" page.

3. Clicking the "Deep Link" again takes you to the right page again. Refreshing starts this process over.

One thing to note is that the "resource not found" page is using a globbed route and on initial load it seems that the globbed route has a higher priority with the latest version of route-recognizer. See: [.../app/router.js#L17](https://github.com/workmanw/wildcard-routing/blob/master/app/router.js#L17)

**Comment by workmanw** [comment]
I was finally able to create a failing test for the route-recognizer. So I added an issue over there and a PR with the test.

I'm not sure how to proceed with this issue because this dependency regression does result in an Ember regression.

**Comment by pixelhandler** [comment]
@workmanw that's great! prolly best to track the next steps on that PR. I'd keep this open as it may be helpful for other who run into this behavior and search the Ember.js issues. It's not always clear where the issue stems from so most start looking here, at least I do.

**Comment by rwjblue** [comment]
I submitted https://github.com/emberjs/ember.js/pull/13286 to downgrade route-recognizer to 0.1.5 (which is what is used in Ember 2.4) until we can get it fixed upstream (tracking in https://github.com/tildeio/route-recognizer/issues/82).

**Comment by jmeas** [comment]
@workmanw, I'm working to fix this. Out of curiosity, if you remove your explicit definition of the index route does it fix the problem (I'll fix it either way, just wonderin')?

**Comment by workmanw** [comment]
@jmeas I did you mean this line: https://github.com/workmanw/wildcard-routing/blob/master/app/router.js#L9 ? I tried removing that line, but the issue still happens :(.

**Comment by jmeas** [comment]
The issue should be fixed with this PR: https://github.com/tildeio/route-recognizer/pull/84

**Comment by workmanw** [comment]
@jmeas 😄 . I'm out running errands now. I'll make some time later to verify the fix with my demo repo and our app.

**Comment by rwjblue** [comment]
The Ember issue was resolved by rolling back for now (in https://github.com/emberjs/ember.js/pull/13286), so I'm going to close this issue.  I'd like at least one more reviewer on https://github.com/tildeio/route-recognizer/pull/84, and then we can merge+release and try updating here again.  That effort can be tracked in https://github.com/tildeio/route-recognizer/pull/84 though...
