### ISSUE TITLE
Component Backed By Collection Does Not Render All Elements After Item Removed

### ISSUE THREAD

**Issue by tojofo** [emberjs/ember.js#13212]
Apologies for the wordy title but I did not know how to describe it.

DEBUG: -------------------------------
DEBUG: Ember      : 2.4.0
DEBUG: Ember Data : 2.4.0
DEBUG: jQuery     : 1.12.0
DEBUG: -------------------------------

This bug requires jquery ui so I could not get a twiddle working, here is a repo with code demonstrating the bug https://github.com/tojofo/ember-component-jquery-ui-sortable-weirdness

**Steps To Repeat**
Clone the repo at https://github.com/tojofo/ember-component-jquery-ui-sortable-weirdness `git clone git@github.com:tojofo/ember-component-jquery-ui-sortable-weirdness.git`
`cd ember-component-jquery-ui-sortable-weirdness`
`ember server`
Navigate to http://localhost:4200/start
Drag Item 3 above Item 2
Click delete on Item 2

**What I Expected To Happen**
Item 2 to be removed from UI

**What Actually Happened**
Item 2 and Item 3 are removed from the UI

**Comment by pixelhandler** [comment]
@tojofo Its great that you've provided an example repo, will try to repo soon. I'm curious what you've tried  so far to resolve issue. Can you simplify the feature? Is there an Ember addon that can replace the jQuery UI behavior you are depending on?

**Comment by tojofo** [comment]
@pixelhandler we tried an addon at one point but had to switch it back out, that was some time ago.  The git logs don't tell me why we switched it back out, just that we did, it might have been an issue around Ember going from 1.x to 2.x.

The above repo is as simple as I can make the code to repeat the issue.

I do intend looking at the ember source to resolve the issue myself but in the mean time have raised this issue.

**Comment by krisselden** [comment]
@tojofo each and sortable can't be both mutating the dom, only one can.

In order to use this library plus each, you would need to subscribe to the update event, and send an action with the updated sorting (this action would then apply to the underlying array), and `this.$().sortable('cancel')` to prevent jquery UI from updating the dom, and let each do it.

**Comment by tojofo** [comment]
@krisselden thank you for the feedback - will try that.

**Comment by krisselden** [comment]
@tojofo so `cancel` doesn't actually restore the DOM quite right, but I did a workaround for you https://ember-twiddle.com/8b95fbde22b976ae3185ecf86b723388
