### ISSUE TITLE
Deprecation of Handlebars.SafeString caused it to break

### ISSUE THREAD

**Issue by markcharyk** [emberjs/ember.js#13225]
When this Pull Request was merged (https://github.com/emberjs/ember.js/commit/44d930c943a024307ea5e2081709b1e3160a2f1a) it ended up breaking the Handlebars.SafeString functionality instead of simply deprecating it. I can reproduce the issue with these two Ember Twiddles:

Working in Beta: https://ember-twiddle.com/44ac2a21705abc5486ed88f971465cad
Broken on Canary: https://ember-twiddle.com/3201249d747e6c29a20f521acaac65b7 (notice the title being changed to `[object Object]`

**Comment by rwjblue** [comment]
Thank you for testing and reporting!  https://github.com/emberjs/ember.js/pull/13226 should fix.

**Comment by dustyjewett** [comment]
There's still an issue with this deprecation. We can no longer check if a string is a SafeString.

`new Ember.Handlebars.SafeString('safe') instanceof Ember.Handlebars.SafeString === false`
as seen [here](https://ember-twiddle.com/3201249d747e6c29a20f521acaac65b7?openFiles=templates.application.hbs%2C)

Ember.Handlebars.SafeString needs to extend the internal SafeString class.... right now it's a constructor that returns the internal class, but the prototypes don't line-up, so instanceof returns false.

**Comment by rwjblue** [comment]
@dustyjewett - Please open a separate issue to track that (though when you do I will likely say that I don't think that doing an `instanceof` check is the right way to check if a thing is a `SafeString`).
