### ISSUE TITLE
Computed properties crash when used as query params

### ISSUE THREAD

**Issue by offirgolan** [emberjs/ember.js#13221]
Ember: 2.0+

I looked through open/closed issues but I didnt find anything about this nor have I seen anything in the docs/blog about this but ever since my upgrade to 2.x, I havent been able to use CPs as query params but instead was forced to use observers. 

[Ember Twiddle](https://ember-twiddle.com/f7955b67cf1c5a9f4155b48bb5a7a37c?openFiles=controllers.application.js%2C)

```js
import Ember from 'ember';

export default Ember.Controller.extend({
  appName: 'Ember Twiddle',
  
  queryParams: ['foo'],
  
  bar: 'bar',
  
  foo: Ember.computed('bar', {
    get() {
      return this.get('bar') + '_baz';
    },
    set(key, value) {
     return value;
    }
  })
});
```

<img width="1440" alt="screen shot 2016-03-30 at 4 51 21 pm" src="https://cloud.githubusercontent.com/assets/575938/14161343/aff61cea-f697-11e5-9981-af3b4838e6c4.png">

**Comment by offirgolan** [comment]
cc @stefanpenner @rwjblue

**Comment by stefanpenner** [comment]
ya, this is sorta known....

cc @machty / @trek

**Comment by rwjblue** [comment]
See discussion in https://github.com/emberjs/ember.js/issues/11592 for details/explanation.

I'm sorry this has been causing you trouble, but I think this is just something that we don't support.

**Comment by offirgolan** [comment]
No worries and thanks for the update!
