### ISSUE TITLE
Unresolved sourceMappingURL in the bower release of ember-template-compiler.js 

### ISSUE THREAD

**Issue by zoltan-nz** [emberjs/ember.js#13234]
In the bower release of Ember.js, there are two files, `ember-template-compiler.js` and `ember-runtime.js`, which contain unresolved sourceMappingURL.

For example, the last couple of lines from `ember-template-compiler.js` (line 20729-20732):

```
;
if (typeof exports === "object") {
  module.exports = Ember.__loader.require("ember-template-compiler");
 }//# sourceMappingURL=ember-template-compiler.map
```

This could cause problem in some build tools, for example `grunt-contrib-concat` fails when sourceMap feature is enabled, because the installed Ember.js package doesn't contain the linked source maps.

The false reference to the source map should be removed from the built version of Ember.js

**Comment by rwjblue** [comment]
Should be resolved by https://github.com/emberjs/ember.js/pull/13241.

**Comment by zoltan-nz** [comment]
@rwjblue Brilliant. I love it. Thank you!
