### ISSUE TITLE
Deprecate Ember.Binding

### ISSUE THREAD

**Issue by mmun** [emberjs/ember.js#13243]
This issue tracks the deprecation of Ember.Binding (and *Binding properties). They've not been needed for a very long time. The existing use cases are covered by computeds and service injections.

- [ ] Add an entry in the deprecation guides
- [ ] Add deprecations to core
  - Trigger a deprecation when the binding connects so that we can provide better upgrade suggestions. If its oneWay, suggest using a readOnly computed. Otherwise, suggest an alias. If the binding is to a global, suggest using a service.

**Comment by rwjblue** [comment]
@mmun - Sounds like a good plan, thanks for working on it...

**Comment by krisselden** [comment]
@mmun this alternatives are extend time, bindings are allowed at create time, I don't think we need an alternative, I'm just pointing it out for the guide.

**Comment by mmun** [comment]
Good point

**Comment by mmun** [comment]
If someone wants to give this a shot in the meantime, please do!

**Comment by robbiepitts** [comment]
I'll take a stab!

**Comment by mmun** [comment]
@robbiepitts Thanks so much! Hit me up in the #dev-ember channel of the community Slack if you have any problems.

**Comment by Serabe** [comment]
@mmun I see both PRs have been merged. Is there something left to do or can this be closed?

Thank you!

**Comment by robbiepitts** [comment]
@Serabe This can be closed, thanks!

**Comment by mmun** [comment]
Thanks all!
