### ISSUE TITLE
{{link-to}} deep linking to route paths that contain multiple dynamic segments creates invalid href URL

### ISSUE THREAD

**Issue by fknoll** [emberjs/ember.js#13254]
```
Ember: 2.4.4
Ember Data: 2.4.3
ember-cli: 2.4.3
node: 5.9.1
os: win32 x64
```

```{{link-to}}``` deep linking to route paths that contain multiple dynamic segments creates **invalid href URL**

Given...
```
Router.map(function() {
  this.route("photo", { path: ”photo/:id" }, function() {
    this.route("comment", { path: "comment/:id" });
  });
});
```

Then...
```
{{#link-to 'photo.comment' 111 222}}
  View comment...
{{/link-to}}
```

Creates a...
```
href="/photo/222/comment/222" 
```

And not the expected...
```
href="/photo/111/comment/222"
```

**Comment by rwjblue** [comment]
Both dynamic segments are the same name so the deepest one clobbers. All params are stored in a single POJO so the names need to be unique. Generally we would name these :post_id and :comment_id.

**Comment by fknoll** [comment]
I was not aware about the fact that names in dynamic segments must be unique. I do not find this constraint intuitive obvious, and I have read nothing about this constraint in documentation. However, changing to uniqueness fixed the problem :-) Thank you so much @rwjblue !

**Comment by rwjblue** [comment]
We should likely find a good place to document this...

**Comment by sly7-7** [comment]
@rwjblue maybe [here](https://guides.emberjs.com/v2.4.0/routing/defining-your-routes/#toc_dynamic-segments) we could precise that dynamic segment name must be unique in a route hierarchy ?

**Comment by pixelhandler** [comment]
@fknoll I created an issue in the guides repo regarding the "constraint intuitive not obvious" nature of using dynamic segments when defining your routes. Thanks for bring this up :)

**Comment by rwjblue** [comment]
Closing in favor of https://github.com/emberjs/guides/issues/1364
