### ISSUE TITLE
And this is where you lose me ...

### ISSUE THREAD

**Issue by adamdonahue** [emberjs/ember.js#13253]
It's this kind of thing -- seems minor, but it used to show up all over -- that turns me off of Ember:

> When we call this.store.findAll('rental'), Ember Data will make a GET request to /rentals. Since we're using Mirage in our development environment, Mirage will return the data we've provided. When we deploy our app to a production server, we will need to provide a backend for Ember Data to communicate with.

Why the need for this "magic"?  Why can't you just make it `rentals` to `/rentals` and avoid this kind of silliness?  It comes across as needless cognitive overhead.  Like I said, minor, but the kind of thing that can get annoying if done too often.

**Comment by mixonic** [comment]
Thanks @adamdonahue, but the Ember.js repo is not a helpful place to share this feedback. Ember-Data has its own repo, though you may want to try and rephrase the feedback to be specific and actionable if you follow up.

**Comment by stefanpenner** [comment]
> using Mirage in our development environment, Mirage will return the data we've provided.

I'm curious where this is written?

**Comment by rwjblue** [comment]
I believe the text is coming from the guides ([source here](https://github.com/emberjs/guides/blob/master/source/localizable/tutorial/ember-data.md#L125) / [guides link](https://guides.emberjs.com/v2.4.0/tutorial/ember-data/#toc_updating-the-model-hook)).

**Comment by stefanpenner** [comment]
Cc @locks   Where best to report this issue?

**Comment by greyhwndz** [comment]
@adamdonahue I think that issue should be posted in the guides:
https://github.com/emberjs/guides/issues

**Comment by bradleypriest** [comment]
From what I can understand he's missing clarity on why the `findAll` statement is  `this.store.findAll('rental')` instead of `this.store.findAll('rentals')`.

Most likely a misunderstanding in that the finder methods take the model class key rather than the route path itself.

**Comment by adamdonahue** [comment]
I was stating that the link between `rental` (singular) and `rentals` plural appears to be implied, not linked specifically.  Would it not be clearer to keep things consistent throughout without automagically pluralizing the URI path?

**Comment by adamdonahue** [comment]
Just food for thought.

**Comment by bradleypriest** [comment]
Originally the method definition was `store.findAll(App.Rental)` which leaves much less room for confusion.
However I can totally see how the move to modules and the change to using container keys has left this open to misunderstanding.

**Comment by locks** [comment]
What @bradleypriest said. You are "finding all records of rental type". The adapter is then responsible for translating that into an endpoint, and that transformation is dependent on the adapter you choose. For RESTAdapter and JSONAPIAdapter it happens to be `/<pluralized name>`, but it could be anything like a websocket.

I believe this is addressed in more detail in the `Models` section, to which I made a [small addendum](https://github.com/emberjs/guides/pull/1356/files). You can comment further there. We want to keep the Tutorial/Quick Start more practical so people can do through them at pace, and then delve deeper into the whys in the guides.
