### ISSUE TITLE
input event on HTML5 range does not fire in IE11 (change event incorrect behavior)

### ISSUE THREAD

**Issue by optikalefx** [emberjs/ember.js#13255]
I've confirmed this in a fresh install. In all other browsers > than IE11 'input' event fires for a component defined as a type range, but not for IE11. 

The change event on > IE11 browsers only fires once when the mouse is released. However in IE11 it is fired non stop as the `input` event should do.

So 2 things need to happen. the `input` event needs to fire non stop in IE11 and the `change` event should only fire when the mouse is released.

Chrome
![image](https://cloud.githubusercontent.com/assets/926885/14282741/c5167cb2-fb0d-11e5-9eaa-0f839a126eac.png)

IE11
![image](https://cloud.githubusercontent.com/assets/926885/14282790/ffca2e08-fb0d-11e5-85a6-a96917542144.png)

You can find this test here https://github.com/optikalefx/ember-range-test

**Comment by optikalefx** [comment]
This is a jQuery bug I guess http://stackoverflow.com/questions/18544890/onchange-event-on-input-type-range-is-not-triggering-in-firefox-while-dragging  should this be a will not fix?

**Comment by rwjblue** [comment]
This seems like browser inconsistency (or a bug if you review https://bugzilla.mozilla.org/show_bug.cgi?id=853670, https://html.spec.whatwg.org/multipage/indices.html#event-input-change, and https://html.spec.whatwg.org/multipage/indices.html#event-input), but not a bug in Ember itself (we have very little to no ability to modify the browser event behaviors).

**Comment by optikalefx** [comment]
So we can close this, but should this be a bug in for jQuery then you think? Ember uses jQuery eventing system. They should normalize the events I think.

**Comment by rwjblue** [comment]
It seems like a browser bug. It is possible that jQuery could try to normalize, but it should ideally be addressed by the IE team (possibly already fixed in Edge).
