### ISSUE TITLE
Active class missing after transition to child route, since latest beta

### ISSUE THREAD

**Issue by medokin** [emberjs/ember.js#13256]
since v2.5.0-beta.4

#13169 seems to break something. Active class is missing after transition to child route.
Twiddle example

https://ember-twiddle.com/8e38c8ca6ba43b6331a3b0ff4c5a4cf7?openFiles=templates.application.hbs%2C

**Comment by GavinJoyce** [comment]
thanks, looking...

**Comment by GavinJoyce** [comment]
TIL doing a `transitionTo` in a route model hook results in a `TransitionAborted` error. I was [using](https://github.com/emberjs/ember.js/pull/13169) that to reset the router target state to fix https://github.com/emberjs/ember.js/issues/13164. This won't work so I'm going to revert https://github.com/emberjs/ember.js/pull/13169 and add a test to cover this regression.
