### ISSUE TITLE
Assertion Failed: You're not allowed to have more than one controller property map to the same query param key

### ISSUE THREAD

**Issue by Arkham** [emberjs/ember.js#13258]
Hi there,

I just updated one of my apps to v2.4.4 and I saw this error popping up:

```
Error while processing route: other Assertion Failed: You're not allowed to have more
than one controller property map to the same query param key, but both
`application:perPage` and `application:perPage` map to `per_page`. You can fix this
by mapping one of the controller properties to a different query param key via the `as`
config option, e.g. `perPage: { as: 'other-perPage' }`
```

The weird thing is that it appears that the error is referring to the same queryParam. If I revert this commit (https://github.com/emberjs/ember.js/pull/13202) the code works as intended.

Here is an ember twiddle reproducing the error: https://ember-twiddle.com/23c9bc41197b73fc8874a35b04c1a635

The setup I've been running is:
```
Ember      : 2.4.4
Ember Data : 2.4.3
jQuery     : 1.11.3
```

**Comment by rwjblue** [comment]
Thank you for the issue and reproduction! Would you mind submitting a failing test? That way it will be easier to confirm that we squash it properly...

**Comment by raytiley** [comment]
This is because your remapping `perPage` to `per_page`. It seems like the `activeTransition` has it as the form it shows up in the url, but when the query params are finalized it puts them as they appear on the controller. 

Still need to work through this a bit more to see what the correct solution is. I'll at least get a failing test written later tonight.

**Comment by raytiley** [comment]
This fixes the issue for me: https://github.com/emberjs/ember.js/pull/13273

Still need to write tests / make sure I didn't break anything else.

**Comment by pixelhandler** [comment]
This past week I started working on a new app, was on Ember 2.4.3 and also tried LTS release 2.4.5. 

The error I saw is like… "You're not allowed to have more than one controller property map to the same query param key, but both `list.index:sortParam` and `list.index:sortParam` map to `sort`."

**Comment by pixelhandler** [comment]
@rwjblue will the fix for this issue be applied to the LTS release ?

**Comment by pixelhandler** [comment]
@rwjblue @chancancode any update on resolution for LTS version yet?

**Comment by jcbvm** [comment]
Seems like 2.4.3 is also affected by this.

**Comment by pixelhandler** [comment]
@jcbvm I've only seen the issue affecting versions 2.4.4 and 2.4.5, rolling back to 2.4.3 was my workaround.

**Comment by pixelhandler** [comment]
Perhaps this issue can be closed not that v2.4.6 has been cut, see: https://github.com/emberjs/ember.js/pull/13600

**Comment by pixelhandler** [comment]
I'll close this out since 2.4.6 fixes the issue by reverting

**Comment by Turbo87** [comment]
FWIW I'm still seeing a similar error with Ember 2.4.6 when I have two routes with identical query params and one route is redirecting to the other and overriding the query params in the transition options 🤔
