### ISSUE TITLE
QP does not get updated when model is refreshed

### ISSUE THREAD

**Issue by lan0** [emberjs/ember.js#13263]
Since 2.4.4 the query parameter does not get updated when refreshing the route.

See this twiddle: https://ember-twiddle.com/48d144fbb71cb96220e42dbd664eaef3 (works in 2.4.3 but not in 2.4.4)

I think this is because of #13202, after the second click the content of `queryParams` is `{foo: "2", application:foo: 3}` [here](https://github.com/raytiley/ember.js/blob/2b42d5659498df2bf725f09e65632bfe5c3161c0/packages/ember-routing/lib/system/router.js#L643). Subsequent changes on the QP increment `application:foo` but not `foo`.

**Comment by pixelhandler** [comment]
@lan0 @raytiley here is a working twiddle using Ember 2.4.3, https://ember-twiddle.com/4b7de2e49239591015e395946feb10df?openFiles=twiddle.json%2C&route=%2F%3Ffoo%3D3

**Comment by raytiley** [comment]
@pixelhandler thanks... I actually have an in-progress fix for this: https://github.com/emberjs/ember.js/pull/13273

I'm going to tidy it up / test it etc this weekend

**Comment by lan0** [comment]
Closing because of #13600
