### ISSUE TITLE
Why does my observer not trigger

### ISSUE THREAD

**Issue by konradjurk** [emberjs/ember.js#13260]
I have a controller with a `model` object. In the controllers template, I instantiate a component:

`{{#my-component confusingBehaviourProofObject=model controller=this}}{{/my-component}}`

In the component, this triggers if `model` changes

```
hasChanged: function () {
    //
  }.observes('controller.model.id'),
```

... and this don't:

```
hasChanged: function () {
    //
  }.observes('confusingBehaviourProofObject.id'),
```

I can see the changing model ID if I print out {{confusingBehaviourProofObject.id}} inside the component template...

Why is that? :) I'd like to understand it.

Thanks in advance!

**Comment by stefanpenner** [comment]
As per the CONTRIBUTING.md (the yellow banner you are suggested to click and read when you post this issue) Q/A and help are better directed to a more appropriate medium. Stackoverflow or discourse.

This talk of mine may be of help: https://www.youtube.com/watch?v=7PUX27RKCq0
