### ISSUE TITLE
`isStream` should be flagged as a reserved property on Components

### ISSUE THREAD

**Issue by noslouch** [emberjs/ember.js#13271]
[See this twiddle for a reduced test case.](https://ember-twiddle.com/02b921550f59393fbd6ce997253ce424?fileTreeShown=false&numColumns=2&openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs) Open the console to see the error message:
```
Uncaught TypeError: object.subscribe is not a function
```

If you set `isStream` as a property on a Component (at least, maybe other classes too), rendering borks because `isStream` is used internally. I can put together a failing test and possibly a  PR, just wanted to note it here in case anyone else wants to pick it up.

I'm imagining a helpful error message at run time that just states that `isStream` is a reserved property name.

**Comment by mmun** [comment]
We should not be reserving `isStream`, instead we should change this branding to a symbol to avoid interfering.
