### ISSUE TITLE
Ember.computed.sort behaviour changed

### ISSUE THREAD

**Issue by spruce** [emberjs/ember.js#13281]
As of ember 2.2.0 and 2.3.2 this worked but with 2.4.x it doesn't anymore. I haven't found any deprecation warnings prior upgrading to 2.4.x and just wanted to let you know that it happens.

```javascript
queue: Ember.computed.sort('all', 'id:desc')
```

See this twiddle (currently version 2.2.2 which works.):
https://ember-twiddle.com/2a0458fce791cda8973e5528e99231c4

**Comment by sly7-7** [comment]
Seems like your example does not work either.
Ember.computed.sort always required a 'sortProperty' referring to an array of properties.
see https://ember-twiddle.com/233eb19060263200e3c3f8f5aa9d6c21?openFiles=templates.application.hbs%2C

Though, I think `Ember.computed.sort('all', 'id:desc')` could be a nice shorthand for simple property

**Comment by rwjblue** [comment]
@sly7-7 - See https://github.com/emberjs/rfcs/pull/87 (long conversation, ultimately closed).

**Comment by spruce** [comment]
Ok thanks for clarifying that.

**Comment by sly7-7** [comment]
@rwjblue Yeah, I forgot it. 
@spruce  It seems like if we want to use the 'simpler' syntax, we can juste use https://github.com/workmanw/ember-computed-sortby
