### ISSUE TITLE
Controller Action Target is Bottom of the Router, not corresponding route.

### ISSUE THREAD

**Issue by hhff** [emberjs/ember.js#13288]
I've been at this Ember game for a while, but this one is surprising to me:

In a nested route structure, with `parent/child`:

Actions bubble through a controller to the bottom of the current router state like this:
`ParentTemplate action` -> `ParentController` -> `ChildRoute` -> `ParentRoute`

I had assumed they would bubble like this:
`ParentTemplate action` -> `ParentController` -> `ParentRoute`

This is important for my addon, Ember Infinity - as users want to have multiple infinite scroll containers on nested route structures.

Is there a clean way to achieve a bubbling flow like this (without touching the controller)?
`ParentTemplate action` -> `ParentController` -> `ParentRoute`

I tried doing:
```
setupController(controller) {
  this._super(...arguments);
  controller.set('target', this);
}
```
To no avail.

:heart:

**Comment by rwjblue** [comment]
No, I do not think this is possible.  The target for controllers is the `router` (not any specific `route` instance) and the router begins searching upwards from the leaf-most active route all the way to the top (generally `ApplicationRoute`).

In the absence of an example, I am assuming that you want to operate on a specific instance that is known in the template, but is specific to the lower controller.  In general, if you want to operate on a single thing that is available in the lexical scope of the template, you should pass it into the action you are invoking.

For example:

```hbs
<div {{action 'foo' someThing}}></div>
```

Instead of doing this, and trying to access `someThing` off of the templates context (controller/component/etc):

```hbs
<div {{action 'foo'}}></div>
```

**Comment by hhff** [comment]
Thanks @rwjblue !

In fact, what I'm doing is providing a route action (through an addon mixin) for a component that sends it upward to said route (the action is named internally in the component).

(For the sake of "no controllers")

When there's a nested route structure, both with the route mixin <-> component setup, the parent template component calls the child route action (as the action is named the same on the parent and child route), resulting in weird behavior.

We've got a public API for working around this (renaming the parent template's component sendAction & receiving/sending on the route, but wanted to investigate if there's a neater way to hide this from for addon consumer.

Also wanted to flag this as a confusion for a long time ember dev, as its associated with moving away from controllers.

I could of course use closure actions & the dockyard route-action helper, but that would break backward compat, and add a peer dep.

TY!!  Will add a note to our README :)

**Comment by hhff** [comment]
Hmmm ok, on further inspection I'm getting another unexpected behaviour.

For a nested `parent/child` route structure:
```
// parent.js

import Ember from 'ember';

export default Ember.Route({
  actions: {
    bar: {
      this.send('foo')
    },
    foo: {
      // I won't fire
    }
  }
});
```

```
// child.js

import Ember from 'ember';

export default Ember.Route({
  actions: {
    foo: {
      // I fired
    }
  }
})
```

Essentially, it appears that `this.send` from a route fires the action from the 'most active route', rather that itself, also.  I was under the impression that `this.send` prioritized it's own actions hash (as I believe this is how controllers behave).

My issue is that Route action bubbling behaves in a way I wouldn't expect (due to deprecated controllers still being the original action target).  Without knowing much about routeable components, it's hard to know how to architect a lib properly.

I'd love some further thoughts here :heart:

**Comment by rwjblue** [comment]
@hhff - That is definitely a different issue than what this was originally opened for, I created https://github.com/emberjs/ember.js/issues/13300 for that.

**Comment by hhff** [comment]
Got it - wasn't sure where it was stemming from :+1:
