### ISSUE TITLE
`Ember.A(null)` now returns `null` instead of `[]`

### ISSUE THREAD

**Issue by workmanw** [emberjs/ember.js#13284]
Here is a pretty clear snippet that explains the issue:

```javascript
// Ember 2.4.x
Ember.A(null);   // returns []

// Ember Beta
Ember.A(null);   // returns null
```

So what happened? It looks like this commit broke it: https://github.com/emberjs/ember.js/commit/586d4c6ab0a82abee0df1f331121e9c99433770e#diff-7 :(. It seems very harmless, but that code is transpiled as:

```javascript
A = A = function () {
  var arr = arguments.length <= 0 || arguments[0] === undefined ? [] : arguments[0];
  return arr;
};
```

The problem is that because `Ember.A(null)` has an argument length greater than 1, it's value [`null`] is ultimately returned. 

Unfortunately this did break a few tests in our application. Specifically with the fixture adapter, see here: https://github.com/emberjs/ember-data-fixture-adapter/blob/master/addon/index.js#L298-L300 . I believe this to be part of the public API and should be fixed. If so, I'd be happy to add a test and take care of it. 

-------

EDIT: As a side note, I feel like I should voice some my concern about the aforementioned commit ( https://github.com/emberjs/ember.js/commit/586d4c6ab0a82abee0df1f331121e9c99433770e ). There are several other places where `argValue || []` was replaced with default arguments, potentially leading to the same issue.

**Comment by mmun** [comment]
Yep. This should totally be fixed and a tested added.

Out of curiosity, which version of Ember.A(null) do you think makes more sense?

@thoov can you do a quick audit of what else might have broken?

**Comment by workmanw** [comment]
> Out of curiosity, which version of Ember.A(null) do you think makes more sense?

@mmun I was just asking myself that. I read the API docs to see if they indicated one way or another, but it was still kind of ambiguous. I could probably make an argument either way.

I sometimes use `Ember.A` as a safety guard for functions expecting a list argument. Eg:

```javascript

mapListValues(list) {
  return Ember.A(list).map(item => { /* ... */ });
})
```

But I could be convinced that this isn't the purpose of `Ember.A`.

**Comment by workmanw** [comment]
This issue was fixed with #13287 being merged in.

**Comment by rwjblue** [comment]
Thanks for catching this @workmanw!

**Comment by workmanw** [comment]
@rwjblue My pleasure! 

Random Fact: I just started using ember-try to test our app against "default", "stable", "beta" and "canary". Setting up a nightly cron to run the tests against all 4 scenarios and email me of any failures. On the first night, it caught this. If I can ever muster the cycles to write a blog post, it'll be about how to do this.
