### ISSUE TITLE
`Route.prototype.send` behavior inconsistent with `Controller.prototype.send`.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#13300]
From @hhff in https://github.com/emberjs/ember.js/issues/13288:

> Essentially, it appears that this.send from a route fires the action from the 'most active route', rather that itself, also. I was under the impression that this.send prioritized it's own actions hash (as I believe this is how controllers behave).

I agree.  The behavior is inconsistent.  Compare the following:

* [Route.prototype.send](https://github.com/emberjs/ember.js/blob/ac90fcf1d31619073a8c2eea6bd206e34d327fb8/packages/ember-routing/lib/system/route.js#L1151-L1162) - Sends directly to the `router` and only falls back to `this.actions` if the router is not present (for unit/integration testing).
* [Controller.prototype.send](https://github.com/emberjs/ember.js/blob/ac90fcf1d31619073a8c2eea6bd206e34d327fb8/packages/ember-runtime/lib/mixins/action_handler.js#L175-L191) - Looks for a local action first, then uses `target`.

**Comment by Serabe** [comment]
[Twiddle](https://ember-twiddle.com/43711363a47e470e3644c46198c7516d?fileTreeShown=false&numColumns=3&openFiles=routes.my.route.js%2Croutes.my.js%2Ctemplates.my.route.hbs&route=%2Fmy%2Froute)

**Comment by mmun** [comment]
I always understood it to work the way it does. All actions go to the active route. I think it would be quite breaking to change this.

**Comment by rwjblue** [comment]
@mmun - I do not disagree that it would be breaking, but it is certainly confusing. At the very least we should document the difference...

**Comment by hhff** [comment]
Agree - I don't think we should change it - but this was surprising to me after being in controller world for so long.  

Closure actions in combination w/ the `route-action` helper from dockyard definitely help the mental model here - but I think in the process of 1.xx apps removing controllers from their codebase a lot of folks will stumble on this (as they'll still be using named actions).

It's also relevant to addons that support back to 1.xx series, and can't rely on closure actions.

I feel like it would be nice for the sender of `Route.prototype.send` to opt-into prioritizing it's own actions hash (the unit/integration testing behavior).

PS - i above where you mention `Router.prototype.send` - i think you mean `Route.prototype.send`.  Don't wanna confuse folks!

**Comment by rwjblue** [comment]
Good catch, updated.

**Comment by pixelhandler** [comment]
@rwjblue seems that some clarity in docs is in order.

**Comment by locks** [comment]
Which docs?

**Comment by pixelhandler** [comment]
@locks I there here http://emberjs.com/api/classes/Ember.Route.html#method_send

But the description does seem sufficient… We could add something like, "the route using this.send does not check local actions prior to sending the action to the router."

> Sends an action to the router, which will delegate it to the currently active route hierarchy per the bubbling rules explained under actions.
