### ISSUE TITLE
Clarify test helpers not registered for unit tests

### ISSUE THREAD

**Issue by baron1405** [emberjs/ember.js#13301]
The Guides should clarify that the test helpers (e.g. pauseTest) are not registered in unit tests only integration and acceptance tests. I spent a lot of time trying to puzzle this out and from Googling it looks like a number of other developers have spent similar amounts of time. It would also be useful to describe how to register these helpers for unit tests, and why they would be needed.

**Comment by rwjblue** [comment]
Very sorry about this. We are actively working to remove the gap between unit/integration/acceptance tests.

**Comment by baron1405** [comment]
Thanks for the quick response and no worries.

**Comment by acorncom** [comment]
@baron1405 would you mind opening an issue in the guides repo (https://github.com/emberjs/guides) for this? That's where we'll need to have this info to make it easier to address. Thanks!
