### ISSUE TITLE
Ensure location information is propagated for inline link-to transformation.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#13313]
When we use the [syntax builders](https://github.com/tildeio/htmlbars/blob/master/packages/htmlbars-syntax/lib/builders.js) from HTMLBars/Glimmer for these:

* https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/transform-inline-link-to.js#L10
* https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/transform-inline-link-to.js#L16
* https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/transform-inline-link-to.js#L19
* https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/transform-inline-link-to.js#L28
* https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/transform-inline-link-to.js#L35

We do not provide `loc` to the builder functions (see [example b.mustache builder function](https://github.com/tildeio/htmlbars/blob/master/packages/htmlbars-syntax/lib/builders.js#L3-L12)), so it defaults to `null`.

We should update to ensure that `loc` information is preserved as much as possible...

**Comment by Serabe** [comment]
I'll try to give it a go this week. Tests need some love too.

**Comment by Serabe** [comment]
In the PR I did not add the loc to line 28 but to line 23.
