### ISSUE TITLE
Dynamically setting queryParams on controller

### ISSUE THREAD

**Issue by mapohjola** [emberjs/ember.js#13322]
We are trying to use query parameters for filtering loaded data. Our problem is that we have dynamic models and would like to have our filters show dynamically depending on what attributes it is possible to filter with.

So we load the info from our backend and then try to set queryParameters on the controller like in the twiddle https://ember-twiddle.com/1caead1325799a059d8954ae110f2043?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ccontrollers.application.js

I don't know if this should be an RFC or issue but I feel like supporting setting queryParameters dynamically like this (or as an computed property returning a promise) would make Ember much more modular.

**Comment by pixelhandler** [comment]
@mapohjola for now the controller is not setup until after the model hooks in the route have resolved. And the controller's queryParams are static (assigned an array of strings, which may relate to a computed property). To somehow allow the controller to treat queryParams as a computed property would be a new feature. For now you may need to define all possible [queryParams] and use computed properties to set the values for them.

[queryParams]: http://emberjs.com/api/classes/Ember.Controller.html#property_queryParams

If you think of a better way, a feature/enhancement, see [CONTRIBUTING.md#requesting-a-feature](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature) which recommends creating an RFC Issue (no need for a pull request with RFC, only an issue in the repo)

> if you have an idea that would be nice to have, create an issue on the emberjs/rfcs repo.

**Comment by mapohjola** [comment]
Thanks for the response will close this and do an RFC if I come up with some better way.
