### ISSUE TITLE
ProxyObject failed `.isEqual` when compared to the object it is proxying.

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/ember.js#13323]
ProxyObject failed `.isEqual` when compared to the object it is proxying.

https://ember-twiddle.com/ee7e8110efb1b090f2505fb75870d22c?openFiles=models.parent-model.js%2Ctemplates.components.my-component.hbs

The key here is that the relationship between the `parent` and the `child` is async. When async is set to true setting a record create a new ProxyObject (this is not the case when async is set to false)

**Comment by pixelhandler** [comment]
@olivierlesnicki Trying to understand the issue more, what exactly to you expect to be equal? and does the `isEqual` function work for that use case? See, http://emberjs.com/api/classes/Ember.html#method_isEqual
 
With this context on the index controller/template…

```js
  model() {
    return {
      child: this.store.createRecord('child-model'),
      parent: this.store.createRecord('parent-model')
    }
  },
```

And this comparison, given an asyc relation…

```hbs
  {{#if (eq model.parent.child model.child)}}
    It worked
  {{else}}
    It didn't work
  {{/if}}
```

… `model.child` is the new `child-model` and `model.parent.child` is the async relation; but you would expect the `isEqual` function to be truthy for comparing the `child` in the `content` of the relation to the original reference. right?

But a proxy object is not equal to it's own `content` that is is proxying to. So I think in this case the `proxy` is NOT equal to the original reference. 

See this twiddle, https://ember-twiddle.com/5384da721221ff3973f97f60f802bddc?openFiles=templates.index.hbs%2Ctemplates.components.my-component.hbs

**Comment by pixelhandler** [comment]
@olivierlesnicki Thanks for putting together a twiddle example, It helped me to see the issue you were looking into. It turns out not to be a bug, so I'll close this out for now.

I'm curious, are you in the http://embercommunity.slack.com/ chat rooms? I bet you'd get quicker feedback in #-help channel compared with the Ember.js Issue tracker here on github.
