### ISSUE TITLE
Ember.Array implements contains but not includes

### ISSUE THREAD

**Issue by alexspeller** [emberjs/ember.js#13336]
[`contains`](http://emberjs.com/api/classes/Ember.Array.html#method_contains) is implemented on `Ember.Array`, but [contains was renamed to includes in 2014](https://github.com/tc39/Array.prototype.includes/commit/4b6b9534582cb7991daea3980c26a34af0e76c6c) - should `contains` be deprecated in favour of an `includes` method in ember?

**Comment by Serabe** [comment]
Seem this was discussed on November, 2014 in #5670. It was closed then because [this reason](https://github.com/emberjs/ember.js/issues/5670#issuecomment-64084814). Since the [proposal is now Stage 4](https://github.com/tc39/Array.prototype.includes#status), I think it is worth revisiting.

**Comment by Serabe** [comment]
@stefanpenner did some work on this #9262

**Comment by pixelhandler** [comment]
@alexspeller I'm curious if you think this question should be an RFC issue, instead. See [CONTRIBUTING.md#requesting-a-feature](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature)

> if you have an idea that would be nice to have, create an issue on the emberjs/rfcs repo

**Comment by alexspeller** [comment]
Moved to RFC https://github.com/emberjs/rfcs/pull/136
