### ISSUE TITLE
Ember Computed.sort Memory Leak in Ember version < 2.4.

### ISSUE THREAD

**Issue by xcskier56** [emberjs/ember.js#13342]
Example Twiddle: https://ember-twiddle.com/c3a31d4999c89cd3b05846ee1c660c15

It seems that a `Ember.computed.sort()` in a component is causing the component to not be garbage collected. 

My app is using 1.13.13 and that is where I originally discovered it. However, testing in 2.4.4 this issue has been fixed. 

I have seen pr #13220 which deals with some memory issues being backported to 1.13, but I cannot tell if this will solve the issue. I believe that this has something to do with what was corrected in #12991 which is why > 2.4 does not leak.

In this image, I navigate to the route that has the sort, and then back to home. You can see that the node count climbs and does not come back down after leaving the route.
![screen shot 2016-04-15 at 11 57 01 am](https://cloud.githubusercontent.com/assets/2357871/14568899/35d84d04-0301-11e6-9046-a1e4113e48dd.png)

This is a view of the HTMLLiElements that are created when going to the leaky route that are not removed.
![screen shot 2016-04-15 at 11 23 05 am 3](https://cloud.githubusercontent.com/assets/2357871/14568940/66b14156-0301-11e6-9613-89f509e1a9e0.png)

This is a detached dom tree of the ~150 elements that are being leak
![screen shot 2016-04-15 at 11 22 27 am](https://cloud.githubusercontent.com/assets/2357871/14568919/517c32aa-0301-11e6-9d23-1553db184219.png)

**Comment by mmun** [comment]
Yes, this bug was fixed. Are you unable to upgrade to 2.5?

**Comment by stefanpenner** [comment]
it is unlikely that this will be back-ported to 1.13.x the implementation is very different.

**Comment by xcskier56** [comment]
Thanks for the quick response! We are stuck on 1.13 as we still have to support IE8. Since this is unlikely to be back ported to 1.13.x, what approach do you recommend to work around this bug?

**Comment by mmun** [comment]
You can keep computed.sort on controllers and other singletons, but not components. Instead you could try writing out a custom computed property that depends on all the possible fields that the dynamic computed.sort will every depend on...

```js
sortKey: 'createdAt', // default
Ember.computed('items.@each.{createdAt,name,rating}', function() {
  return this.get('items').sortBy(this.get('sortKey'));
});
```

**Comment by xcskier56** [comment]
@mmun, thanks for the advice! I will implement that.
