### ISSUE TITLE
Query Params are forced into route when link is clicked

### ISSUE THREAD

**Issue by larryh** [emberjs/ember.js#13340]
Hi,

I'm just starting to learn ember, so hopefully I am just doing something stupid that will be easy to fix.

(BTW: ember-cli 2.4.3 with a Rails 5 API-only back end)

I have defined the typical _band has_many albums_ and _album belongs_to band_ associations on both the front and back ends.

Here is what I have in my router.js file:
<pre><code>
this.route('bands', function() {
    this.route('albums',  {path: ':band_id/albums'}, function() {
        this.route('songs', {path: ':album_id/songs'}, function() {});
    });
});
</code></pre>

And here is what I have in my bands template. When I click on a band I want to display its list of albums:
<pre><code>
  {{#each model as |band|}}
    {{#link-to 'bands.albums' band.id}}
      {{band.name}}>
    {{/link-to}}
  {{/each}}
</code></pre>

That seems to be fine, because the generated HTML - specifically the `href` values for the links of each of my bands (below) - is exactly what I expect. Which is great, because I have defined matching routes in Rails to handle this form of url:
<pre><code>
href="/bands/1/albums"
href="/bands/2/albums"
href="/bands/3/albums"
</code></pre>

Now here is the part that I cannot figure out...

When I click on a link, this is how the urls above are actually getting sent to the server. (I have defined a `namespace` of `api/v1` in my `application.js` adapter, so that is fine.)

`Started GET "/api/v1/albums?band=2"`

As you can see, the path defined in my router.js file and in the links themselves are getting transformed into a call that uses query parameters - which my back end can't handle. And even if it could, this just seems wrong.

How can I get what I thought I had specified, i.e. 
`Started GET "/api/v1/bands/2/albums"`

Thanks,
Larry

**Comment by acorncom** [comment]
Hi @larryh, welcome to Ember and glad you're getting going on things!  We generally ask folks to reserve the issues here for specific bugs they find in Ember (to help us focus on improving the code when we're working in here).  Instead, we'd love it if you'd post questions like yours either on StackOverflow, the Ember forums or on the Ember Slack (in the `#needhelp` channel) and maybe answer a few questions while you're there! 😄.  You can find more details on all of that on the Community page on the Ember site: http://emberjs.com/community/

I'll close this issue for now, but if/when you find a bug in Ember in the future, we look forward to working on fixing it with you!

**Comment by larryh** [comment]
OK. I appreciate you taking the time to set me straight and help me out, as opposed to just letting me hang.

Thanks,
Larry

**Comment by acorncom** [comment]
Sure!  Also, a quick note now that I'm seeing your question with fresher eyes.

If you're using a Rails 5 api backend with JSONAPI::Resources, then your API should be able to handle exactly what Ember is sending back.  If you still have questions on this, get on to the Ember Slack, choose the `#topic-rails` channel and ping me there (same username)  Happy to help you work it out further :-)

**Comment by larryh** [comment]
Thanks for the offer - I really do appreciate it because I know how busy you must be. After looking at a few more resources I think I have a handle on the problem; at least I believe I know the direction to proceed.

I've been working with Rails for years and am familiar with jQuery (regular, mobile, and UI), but now realize I have to take the plunge into SPAs.

The biggest problem (for all of us newcomers, I imagine) was which JS framework to choose, as there seem to be dozens. But after looking at a bunch (and since I come from a Rails background) I decided to go with Ember.

So far I am _very_ impressed, and the fact that a busy expert offered to help a newbie added to that impression, as the user community is arguably as important as the platform itself.

Thanks again,
Larry

**Comment by acorncom** [comment]
> and the fact that a busy expert offered to help a newbie added to that impression, as the user community is arguably as important as the platform itself.

Busy, yes.  Expert?  No 😄 But yes, the community is part of the reason I'm here as well, these folks are fun to work with :-)
