### ISSUE TITLE
Contextual components does not carry information about source for local lookup

### ISSUE THREAD

**Issue by Serabe** [emberjs/ember.js#13346]
For reference, [Contextual Components RFC](https://github.com/emberjs/rfcs/blob/master/text/0064-contextual-component-lookup.md) and local lookup is being discussed as part of emberjs/rfcs#124.

Currently, when creating a contextual component, we only close over the path of the component, either by [reading it from the first param](https://github.com/emberjs/ember.js/blob/75cd6e3a1ff7d21112f7b3fd7f2208e5fa8c2b25/packages/ember-htmlbars/lib/keywords/closure-component.js#L104) or by getting it from the other contextual component (https://github.com/emberjs/ember.js/blob/75cd6e3a1ff7d21112f7b3fd7f2208e5fa8c2b25/packages/ember-htmlbars/lib/keywords/closure-component.js#L84).

Local Lookup needs to know the source as well. For that reason, a `COMPONENT_PATH_SOURCE` and **treat it exactly** like `COMPONENT_PATH`. Then the component hook needs to be updated to use it as source if it gets a component cell.

**Comment by rwjblue** [comment]
:+1: - Thanks for reporting, do you plan to pick up implementation of this?

**Comment by Serabe** [comment]
Yes.

**Comment by Serabe** [comment]
Fixed in #14421
