### ISSUE TITLE
Issue with Ember.lookup in canary

### ISSUE THREAD

**Issue by danmcclain** [emberjs/ember.js#13352]
While testing an addon, I came across the following issue: When using the current Ember canary with Ember-Data canary (via bower, not the ember-data addon version in package.json), Ember-Data throws an error when trying to set `Ember.lookup.DS`

```
_ember.default.lookup.DS = _emberDataPrivateCore.default;

Stacktrace:
ember-data.js:12881 Uncaught TypeError: Cannot set property 'DS' of undefined
    (anonymous function) @ ember-data.js:12881
    Module.exports @ ember-data.js:94
    Module.build @ ember-data.js:144
    findModule @ ember-data.js:192
    requireModule @ ember-data.js:179
    (anonymous function) @ ember-data.js:16707
    (anonymous function) @ ember-data.js:16708
```

Steps to reproduce: 

1. Create a new ember app
2. Add dependency for ember-data#canary in `bower.json`

**Comment by danmcclain** [comment]
@rwjblue Ping, as we discussed this prior to creating this issue

**Comment by rwjblue** [comment]
Likely related to https://github.com/emberjs/ember.js/pull/13319

**Comment by rwjblue** [comment]
Ember.lookup.DS = DS

Is done here: https://github.com/emberjs/data/blob/v2.5.2/addon/index.js#L159

**Comment by danmcclain** [comment]
I bet the reason I didn't see the addon version blow up is because the addon isn't used at all, where the bower version is evaluated whether or not it's used

**Comment by rwjblue** [comment]
The addon only does this if you do:

    import DS from 'ember-data'

But most of the time now (since it's an addon) you would just import the things you need from their real module paths.

**Comment by rwjblue** [comment]
I spoke with @krisselden about this and he is going to work on getting `Ember.lookup` reexposed (with a deprecation).

**Comment by rwjblue** [comment]
I submitted https://github.com/emberjs/data/pull/4343 in Ember Data to mitigate over there, we still need to set `Ember.lookup` / `Ember.imports` / `Ember.exports` back up (with a deprecation though).

**Comment by rwjblue** [comment]
@krisselden - Is this still on your radar?
