### ISSUE TITLE
Minor feature request: default for {{get}} helper

### ISSUE THREAD

**Issue by bierdybard** [emberjs/ember.js#13357]
Hello,

Please let me know if an RFC is necessary for this, it seems relatively minor but I'll write one up if needed.

Requesting the addition of an optional third parameter to the {{get}} helper which would serve as a default response in the case that the returned value is undefined or null, and be ignored otherwise. This would be functionally identical to the Python `getattr` builtin.

Example:
```
// /app/components/my-component.js
...
testObject: {
    keyOne: 'valueOne',
    keyTwo: 'valueTwo'
},
...

// /app/templates/components/my-component.hbs
Test 1: {{get testObject 'keyOne'}}<br>
Test 2: {{get testObject 'keyTwo' 'defaultValueTwo'}}<br>
Test 3: {{get testObject 'keyThree}}<br>
Test 4: {{get testObject 'keyFour' 'defaultValueFour'}}
```
Output:
```
valueOne
valueTwo

defaultValueFour
```

I do understand this can be accomplished using {{if}} helpers and subexpressions, I thought this could be a useful shorthand though. I understand this would be low priority and it's something I would be willing to try my hand at myself when I can find some time.

Please let me know if anything else is needed.

**Comment by rwjblue** [comment]
This does seem like a feature request, and features are generally discussed in the https://github.com/emberjs/rfcs/ repository. You can create an issue there for feature requests or a pull request to propose a new feature.  I'm closing this issue (this isn't really a bug in the framework), but please follow up with an RFC issue/PR if you are interested in taking this further.

I also think that I would prefer to avoid adding an additional arg to `{{get`, and instead make a `{{get-with-default` (to mirror `Ember.get` and `Ember.getWithDefault`).  I definitely look forward to your RFC about this, thanks for being willing to participate in the process!

**Comment by ptgamr** [comment]
This is an attempt for @rwjblue suggestion : https://gist.github.com/ptgamr/b5a3d34abb873d3e99cfc0e2c2f202e6
