### ISSUE TITLE
Routing error on IE8/9

### ISSUE THREAD

**Issue by vedharish** [emberjs/ember.js#13368]
Hey,
 I recently opened the issue testem/testem#846.

Basically, I created a new ember app with `ember new my-app`, added some logging to the testem server and ran the tests locally on IE8.
 I am getting errors similar to `error ENOENT: no such file or directory, stat 'C:\Users\win7\3568ae5193185c71aa283fd227489fc1\my-app\tmp\class-tests_dist-GUZ6dX1k.tmp\tests\assets\vendor.css'` (I checked on the file system and the file was present at `C:\Users\win7\3568ae5193185c71aa283fd227489fc1\my-app\tmp\class-tests_dist-GUZ6dX1k.tmp\assets\vendor.css`. Notice the missing `tests` folder for assets)

I could reproduce this for only IE8 and IE9 on BrowserStack. Please check the testem issue page for details on how I reproduce it on BrowserStack. I followed [this gist](https://gist.github.com/vedharish/3568ae5193185c71aa283fd227489fc1).

I can not figure out whether this is an issue with testem or with the app that ember creates, so I created a similar issue here. I can help debug the issue if someone points me in the right direction.

**Comment by locks** [comment]
@vedharish note that [IE8 is no longer supported](http://emberjs.com/blog/2015/04/20/ie8-support-update.html). And just to clarify, you tested on other browsers and didn't have the same problem?

**Comment by vedharish** [comment]
Yes, This works fine on chrome/firefox/IE10/IE11. It shows the above issue for IE8/IE9

**Comment by rwjblue** [comment]
That error appears to be a build time error, and seems unrelated to browser (browsers don't throw ENOENT, this is a node/build time error).

This repo is for bugs in Ember itself (not ember-cli). If this is an Ember bug you should be able to recreate the IE9 failure in JSBin or ember-twiddle.com (if those services support IE9 that is). If this is a build time error (unrelated to browser) then it should be reported to the ember-cli repo along with precise steps to recreate the error.

**Comment by vedharish** [comment]
Well, ENOENT roughly means 'no such file or directory found'.

In this case, this is the log from testem server. Here is what I think is happening - 
When running `ember test`, a testem server is started. It (ember? / testem?) creates a tmp directory in the current working directory and adds asset files and other temp file to serve to `tmp\class-tests_dist-{random hash}.tmp\assets\` directory. In specific case of IE8/IE9, the browser requests for the file `tmp\class-tests_dist-{random hash}.tmp\tests\assets\` instead of the aforementioned one. The files are not present in that directory, hence ENOENT. Thats why I tagged it as `routing error`.

I don't think the issue is with the testem server because it creates the file in the same location for other browsers too (Also the server couldn't know the browser it is being tested on before starting the tests).
I think the client javascript somehow creates the wrong absolute request url for asset files.

**Comment by rwjblue** [comment]
> Well, ENOENT roughly means 'no such file or directory found'.

Yep, I am aware.  As I mentioned, a browser can not throw this error.

Ember itself doesn't trigger any asset requests (at all), which is why I suggested that you create steps to reproduce this and submit an issue to ember-cli.

**Comment by vedharish** [comment]
Okay. I think I will create an issue there. Thanks!
