### ISSUE TITLE
Error from application adapter...

### ISSUE THREAD

**Issue by joetidee** [emberjs/ember.js#13379]
As per...

[https://guides.emberjs.com/v2.5.0/models/customizing-adapters/](https://guides.emberjs.com/v2.5.0/models/customizing-adapters/)

...I added a file 

`/adapters/application.js`

 with the following content (to remove the pluralisation of urls):

```
export default DS.JSONAPIAdapter.extend({
  pathForType: function(type) {
    var camelized = Ember.String.camelize(type);
    return camelized;
  }
});
```

Even though this seems to have worked, I receive the following errors in the console where Ember is running:

> adapters/application.js: line 1, col 16, 'DS' is not defined.
> adapters/application.js: line 3, col 21, 'Ember' is not defined.

**Comment by locks** [comment]
@joetidee if you use the generate command, you will have the imports included. In most of the guides, with the exclusion of the tutorial, we elide the imports for conciseness and because we are waiting for the module shims to be finalized.
We are hoping the shims get finalized soon so we are able to avoid this confusion :)

**Comment by locks** [comment]
P.S. I invite you to join our [Slack community](https://ember-community-slackin.herokuapp.com/), we have a #-help channel that is very responsive and can help you out!

**Comment by joetidee** [comment]
So, should I delete the `application.js` file and regenerate it using the `generate` command?

**Comment by locks** [comment]
If you add the following at the top the errors should go away:

```
import Ember from 'ember';
import DS from 'ember-data';
```

**Comment by joetidee** [comment]
Got it. Is there any way I can contribute to updating the docs as I see improvements?

**Comment by locks** [comment]
Indeed there is, you can open issues and send pull requests to https://github.com/emberjs/guides for the Guides, and to this repository for API documentation.
