### ISSUE TITLE
Documentation for 2.5 needs slight change...

### ISSUE THREAD

**Issue by joetidee** [emberjs/ember.js#13375]
On this page:

[https://guides.emberjs.com/v2.5.0/tutorial/ember-data/](https://guides.emberjs.com/v2.5.0/tutorial/ember-data/)

when I genenrate the Model using `ember g model rental`, the `rental.js` file looks like this:

```
import Model from 'ember-data/model';

export default Model.extend({

});
```

This is syntactically slightly different to the docs and affects subsequent references on this page.

**Comment by locks** [comment]
Thank you for the bug report, but this has already been addressed [by a PR in the Guides repository](https://github.com/emberjs/guides/issues/1373).
It should be updated at the latest with the 2.6 release.

**Comment by joetidee** [comment]
Are you able to provide some guidance with how the /app.models/rental.js file should look once the attributes have been added?

**Comment by joetidee** [comment]
Ok, I got it, just didn't know whether the code generated was incorect or the docs.

**Comment by locks** [comment]
The generated code is indeed correct! Glad you got it :)
