### ISSUE TITLE
Revert #13286

### ISSUE THREAD

**Issue by jmeas** [emberjs/ember.js#13380]
The issue that caused the regression has been fixed in https://github.com/tildeio/route-recognizer/pull/84

**Comment by workmanw** [comment]
@rwjblue @krisselden Should I open a PR to bump `route-recognizer` or do want to take care of it next time you make a pass over the dependencies?

**Comment by rwjblue** [comment]
Thanks for working on this @jmeas!

**Comment by jmeas** [comment]
✌️
