### ISSUE TITLE
Ember.computed.max/min: Date object turns back in timestamp 

### ISSUE THREAD

**Issue by tennisonchan** [emberjs/ember.js#13387]
When we use `Ember.computed.min` or `Ember.computed.max` for javascript date object, the returned value was in timestamp instead of a date object.

Demo:
https://ember-twiddle.com/fbb355b2a22bc92bdb3713ec59f866f3?fileTreeShown=false&openFiles=controllers.application.js%2C

```javascript
{
  dates: Ember.computed(function() {
    return [
      new Date("Apr 19 2016"),
      new Date("Apr 20 2016")
    ];
  }),
  earliestDate: Ember.computed.min('dates'),
}

this.get('earliestDate'); // return 1461095445000, the timestamp on 19th April 2016
```

**Comment by rwjblue** [comment]
Internally, we are using `Math.min` to determine the lowest ([see here](https://github.com/emberjs/ember.js/blob/6739196db628b26b403d66c4271715ec14747dfe/packages/ember-runtime/lib/computed/reduce_computed_macros.js#L151)), which [per the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-math.min) does:

> Given zero or more arguments, calls ToNumber on each of the arguments and returns the smallest of the resulting values.

> * If no arguments are given, the result is +∞.
> * If any value is NaN, the result is NaN.
> * The comparison of values to determine the smallest value is done using the Abstract Relational Comparison algorithm (7.2.11) except that +0 is considered to be larger than −0.

`ToNumber` defers to `ToPrimitive` (defined [here](http://www.ecma-international.org/ecma-262/6.0/#sec-toprimitive)) and in this case calls `valueOf` on the `Date` instance.

```js
let date = new Date();
console.log(date.valueOf());
// => 1461208340910
```

---

That was a very roundabout way of saying that I think the current behavior is correct (though somewhat unexpected).

**Comment by tennisonchan** [comment]
Hey @rwjblue, thanks for the details explanation. Yes, it is somewhat unexpected that it changed the datatype of the input values. 

Here is lodash min function returns the date object. 
```javascript
_.min([new Date(), new Date()])
// => Fri Apr 22 2016 08:44:30 GMT-0400 (EDT)
```

**Comment by rwjblue** [comment]
Hmm, did it change the input values or just return a value that isn't the same?

**Comment by tennisonchan** [comment]
It changed the datatype of the value, from a js date object to a number of timestamp.

**Comment by rwjblue** [comment]
It definitely is not changing the value inside the `dates` array in your twiddle above (see [modified demo](https://ember-twiddle.com/7a6db9595cd0a8ab4815dff2e933ecf6?fileTreeShown=false&openFiles=templates.application.hbs%2C) here).  The `computed.min` / `computed.max` return values are different than the input value.  That is the real issue here.

**Comment by tennisonchan** [comment]
Yes, we are on the same page.

**Comment by eshirazi** [comment]
Looks like _.min, _.max use a simple > or < comparison instead of Math.min, and Math.max, and this is an easy fix for this issue. I submitted a pull request https://github.com/emberjs/ember.js/pull/13406.
let me know what you think.

**Comment by stefanpenner** [comment]
> Looks like _.min, _.max use a simple > or < comparison instead of Math.min, and Math.max, and this is an easy fix for this issue

This would most likely break existing apps, that expect the current behavior. This most likely needs to be considered a new feature.

**Comment by joelalejandro** [comment]
What about a flag `{ preserveType: true }` or something like that?

**Comment by tennisonchan** [comment]
Any update here? @stefanpenner it will only break if the user update their ember. The change will only break if people use `computed.min/max` with javascript date and depends on its output as a timestamp. It shouldn't affect most of the use case, if not all.

**Comment by stefanpenner** [comment]
I believe my comment is still the current thought: https://github.com/emberjs/ember.js/issues/13387#issuecomment-214007630

**Comment by mixonic** [comment]
Closing per the documentation improvements in https://github.com/emberjs/ember.js/pull/13556
