### ISSUE TITLE
computed.and/or: Short-circuit behavior

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#13384]
Example: 

```js 
{
  a: Ember.computed(function() {
    console.log('a');
    return false;
  }),

  b: Ember.computed(function() {
    console.log('b');
    return 'b';
  }),

  c: Ember.computed(function() {
    console.log('c');
    return 'c';
  }),

  foo: Ember.computed.or('a', 'b', 'c'),
}
```

When I use `{{foo}}` in the corresponding template I correctly see `b` as a value. I did however see `a`, `b` and `c` get printed on the console, which indicates that the current implementation of the `Ember.computed.and/or` helpers are not using short-circuit behavior. In other words: since `b` returns something trueish in this example `c` shouldn't have been evaluated. The performance in this example is not that relevant but once the computed properties become more complex it might pay off to only evaluate the properties if they are really needed.

It looks like the current implementation is just calling `.getProperties()` on the object which leads to the current behavior. If that was replaced with a loop calling `.get()` for each property until one fulfills the "and/or" predicate the performance might be improved for complex properties.

/cc @rwjblue

**Comment by rwjblue** [comment]
👍  - Seems like a nice improvement.  I'd want to ensure the same change was done for `computed.and` if you wanted to tackle it...

**Comment by stefanpenner** [comment]
Ya this would be reasonable to expect.
I think this should go through a full cycle  (not a bugfix) as I believe it to be possible for some to rely on the behavior..

**Comment by rwjblue** [comment]
Makes sense, I agree.
