### ISSUE TITLE
Input autofocus only works on first render

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/ember.js#13391]
https://ember-twiddle.com/f5b03da876189e65370402daca33e56c?openFiles=controllers.application.js%2C

Steps to replicate:
- Click on autofocus once, the input is correctly autofocused
- Click twice, it is not anymore (unless app is reloaded)

**Comment by acorncom** [comment]
Confirmed, I'm seeing this behavior too.  The issue seems to be that the input once generated doesn't properly re-focus when it is hidden and then shown again ...

**Comment by Serabe** [comment]
I am not sure this is an Ember bug. [`autofocus` behaviour](https://w3c.github.io/html/sec-forms.html#autofocusing-a-form-control-the-autofocus-attribute) is not that simple to grasp, but this thing happens in the following contexts too:

- Firefox (it does not autofocus even the first time)
- Simple jQuery adding and removing html shows the same problem ([jsbin](http://jsbin.com/sedosu/edit?html,css,js,output))
- Same example but with just `<input autofocus>` ([twiddle](https://ember-twiddle.com/e41a5649b14adb15a064876fdaa24c4e?openFiles=templates.application.hbs%2C))

I am not sure this is a bug and, if it is, that is on our side.

**Comment by Serabe** [comment]
I am closing the issues for the reasons above. Feel free to reopen if you still think this is an Ember issue.

Thank you!

**Comment by Glarregle** [comment]
Experienced the same problem here.
Couldn't find better solution than calling 
`this.$('input').focus()` 
inside  `didInsertElement()` hook.

**Comment by Pieter-Rees** [comment]
I solved it like this without Jquery:
didInsertElement() {
    this.get('element')
      .querySelector('.selector')
      .focus();
  },

**Comment by annguyen97dev** [comment]
use settimeout
