### ISSUE TITLE
Should the click helper's 2nd argument be documented?

### ISSUE THREAD

**Issue by sethbrasile** [emberjs/ember.js#13397]
Looks like the `click` helper

http://emberjs.com/api/classes/Ember.Test.html#method_click
https://guides.emberjs.com/v2.5.0/testing/acceptance/#toc_asynchronous-helpers

Accepts `context` as a second arg.

The folks over on the guides repo are curious if the folks over here believe that it should be documented.

https://github.com/emberjs/guides/issues/1386

**Comment by mixonic** [comment]
Seems like the API documentation should definitely be updated. Regarding the guides we can defer to @locks @acorncom about if they think the content is appropriate.

**Comment by pixelhandler** [comment]
@mixonic @sethbrasile I belive the `context` (2nd) argument is due to using jQuery selectors, e.g. http://api.jquery.com/jQuery/#jQuery1 So aside from the client helper wouldn't the other test helpers also use this `context` too?

**Comment by pixelhandler** [comment]
@locks the guides show a context arguement for the `find` helper but the API docs do not, http://emberjs.com/api/classes/Ember.Test.html#method_find and https://guides.emberjs.com/v2.5.0/testing/acceptance/#toc_synchronous-helpers see `find(selector, context)` so perhaps we should have `click(selector, context)` as well and the API docs + guides should agree.
