### ISSUE TITLE
{{link-to}} doesn't work on touch devices

### ISSUE THREAD

**Issue by jmanuelrd** [emberjs/ember.js#13400]
I tested this on Android and iOS devices, FF, Chrome and native browsers.
Is there a way to get this helper catch touch events like tap, touchstart, touchend, etc? 

I'm using bootstrap's nav.

**Comment by locks** [comment]
Do you have a reproduction of what you tested? I have used several Ember sites on my mobile phone and they worked fine.

**Comment by rwjblue** [comment]
@jmanuelrd - Can you put together a ember-twiddle or JSBin demonstrating the issue (with steps to reproduce)?

**Comment by acorncom** [comment]
I'm going to close this issue for now. @jmanuelrd if you are still having the issue please let us know (we'd love to fix it if needed) and we can re-open this issue.
