### ISSUE TITLE
{{foo.bar}} should not do a container lookup

### ISSUE THREAD

**Issue by mmun** [emberjs/ember.js#13404]
`{{foo.bar ...}}` will attempt to lookup the `foo/bar` component/helper. Example ember-twiddle:

https://ember-twiddle.com/f61aba173ed7543271219868015fcfa7?openFiles=application.template.hbs%2C

It should be treated unambiguously as a property lookup. Instead, `{{foo/bar ...}}` should be used if you want to invoke a helper.

**Comment by Serabe** [comment]
It is quite likely that I am to blame for this. I had to change HTMLBars so the `handleRedirect` would take place for contextual components when rendered using the dot path. I think that the problem is caused by [these lines](https://github.com/emberjs/ember.js/blob/b79fa2fd0a0461e96a9edd6ac760806e11317873/packages/ember-application/lib/system/resolver.js#L142-L144) in the resolver.

**Comment by mmun** [comment]
Is there a version of Ember in which this bug is not present? I think it would be disingenuous to call it a BUGFIX unless the semantics accidentally changed sometime during 2.X.

**Comment by Serabe** [comment]
2.1 seems to produce the same output and the change was added later for sure. My (double) mistake!

**Comment by krisselden** [comment]
@Serabe aren't contextual components resolved from the value, why did that need the above change?

**Comment by Serabe** [comment]
@krisselden I was confused before. I thought this had to do with [this change](https://github.com/tildeio/htmlbars/commit/f32ccaea6b96efdb3e5efe5a4b0066f23d707109) in tildeio/htmlbars. This change had to be introduced given that contextual components could not be invoked with dot path and without arguments. I thought that this was causing the problem but previous versions of Ember were affected as well.

**Comment by krisselden** [comment]
@Serabe I don't know why that had to be changed, I thought contextual components used `componentCell[COMPONENT_PATH]`
