### ISSUE TITLE
Update changelog script to account for GH's "squash and merge".

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#13412]
The command listed https://github.com/emberjs/ember.js/blob/master/bin/changelog#L44 needs to be updated to match the newer PR style (where there is no merge commit).

**Comment by mdsib** [comment]
Moving forward, will ember be only allowing squash merging? Or will the option to merge PRs in the original way still be available?

**Comment by rwjblue** [comment]
We would need to allow both, since which button the merger hits is up to them (and I do not know of a way to disable one style).

**Comment by mdsib** [comment]
According to the blog post about it (https://github.com/blog/2141-squash-your-commits) either option can be enabled or disabled.

**Comment by rwjblue** [comment]
HA!  Apparently, I didn't pay attention :ton

**Comment by mdsib** [comment]
Yeah, it's a good idea to have the changelog work no materr which setting we use.

**Comment by rennomarcus** [comment]
Hi! I want to start to contribute to the awesome ember.js and I saw the way to start is with issues containing the label `help wanted`. 

@rwjblue, I saw the code you provided and the line you highlighted is for cherry pick and not for merge. I also read https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md but I'm still a little confused here.
Some facts I got:
- The current code get the difference between the current tag and head;
- Contributions come from PR's and Cherry picks;
- Contribution's messages come from PR messages and from the original commit that was cherry picked to the current branch;
- Information is added into contribution such as [PR number] and their links 

Could you provide some explanation or an example to what you want, so I can try to help? 

What I did so far:
``` 
$ git checkout -b 'update-changelog-script
$ export PRIOR_VERSION='v2.17.0-beta.1'
$ bin/changelog
```

**Comment by pixelhandler** [comment]
@mdsib @rennomarcus @rwjblue is this still an issue, perhaps we should close, what do you think?

**Comment by rwjblue** [comment]
Yes, I’d like to fix the Changelog script still.

**Comment by lifeart** [comment]
@rwjblue is it alive?
