### ISSUE TITLE
Dasherize attributeBindings for arbitrary attributes; match behavior of classNameBindings

### ISSUE THREAD

**Issue by cmtonkinson** [emberjs/ember.js#13421]
I'm requesting some additional convention-over-configuration for inflection of attribute bindings in customized Components.

I'm using Ember: 2.5.1 and jQuery: 2.2.3.

---
The "[Customizing a Component's Element](https://guides.emberjs.com/v2.5.0/components/customizing-a-components-element/#toc_customizing-the-element-s-class)" documentation for `classNameBindings` show that:

    export default Ember.Component.extend({
      classNameBindings: ['isUrgent'],
      isUrgent: true
    });

yields:

    <div class="ember-view is-urgent"></div>

where `isUrgent` is automatically dasherized when rendering. Thus, my expectation for `attributeBindings` was that:

    App.AnchorComponent = Ember.Component.extend
      tagName          : "a"
      href             : "#"
      title            : "Download"
      dataToggle       : "tooltip"
      dataPlacement    : "left"
      attributeBindings: ["dataToggle", "dataPlacement", "title"]

      #############################################################################
      didInsertElement: ->
        @$().tooltip()

would be dasherized to yield:

    <a href="#" title="Download" data-toggle="tooltip" data-placement="left"/>

but to my [astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), instead I see:

    <a href="#" title="Download" datatoggle="tooltip" dataplacement="left"/>

---
The actual behavior (currently) requires manually mapping each Compontent attribute name to its respective Element attribute name:

    App.AnchorComponent = Ember.Component.extend
      tagName          : "a"
      href             : "#"
      title            : "Download"
      dataToggle       : "tooltip"
      dataPlacement    : "left"
      attributeBindings: ["dataToggle:data-toggle", "dataPlacement:data-placement", "title"]

      #############################################################################
      didInsertElement: ->
        @$().tooltip()

which gets the desired:

    <a href="#" title="Download" data-toggle="tooltip" data-placement="left"/>

**Comment by workmanw** [comment]
:+1: from me. I just tripped over this on monday.

**Comment by rwjblue** [comment]
If we automatically did this, then camel case attributes/properties (there are a few) couldn't be set.

**Comment by cmtonkinson** [comment]
@rwjblue 

> there are a few

Which are you thinking of, specifically? I can't come up with any off the top of my head. There are a few multi-word attributes without dashes (such as `autoplay`, `contenteditable`, and `formaction` for example) however

  1. HTML element attributes are case insensitive. If someone is camelizing them, that's a [human] convention, not a web standard, and certainly not a language rule.
  2. They're much fewer and farther between than, say, `data-` attributes.

So I think it would make sense to set the default in-line with the majority of use cases. Which is a good point to clarify actually - I'm requesting a change to the _default_ (necessarily a major rev decision as it's a breaking change) but I'm not suggesting the ability to override should be removed.

**Comment by acorncom** [comment]
@cmtonkinson given that this is more of a feature request, could we move discussion of this to an RFC? We're trying to keep the issue tracker focused on bugs or features that have gone through the RFC process. Thanks! 

More details here: https://github.com/emberjs/rfcs/blob/master/README.md

**Comment by pixelhandler** [comment]
@cmtonkinson I often use the attribute mapping convention which seems more explicit anyway. Sometimes the conventions are a bit confusing. 

Here is an example of using explicit syntax and no mapping: https://ember-twiddle.com/a2bff79d324b1c792b6795c3b0444d65?openFiles=components.x-quote.js%2C

See the component source and in the output there is a text area with the HTML source.

Personally I like the defaults now, as it does force me to explicit for attribute bindings.

I agree with @acorncom this is a feature/enhancement request. See [CONTRIBUTING.md#requesting-a-feature](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature) which recommends creating an RFC Issue to request a feature/enhancement (no need for a PR with RFC, only an issue in the repo)

I'll close this for now, if you would like to move forward with proposing the enhancement please do move this over to the RFC repo. 

P.S. just case I like the defaults don't that that discourage you from proposing a new way :)
