### ISSUE TITLE
mouse event bubbles up to parent, not to element under this one

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/ember.js#13434]
Create 3 components.
A & B are next to each other
C is in B's template, same dimensions as B.
Now rotate C 45 degrees using `transform:rotateZ` so it partially overlaps A

Click in the triangle where C overlaps A

**Expected**
C receives mouse down, then bubbles to A

**Actual**
C receives mouse down, then bubbles to B

This means if C is partially transparent (in my case C is a circle in a png) then the user can't click on a button next to it if it's rotated.

![image](https://cloud.githubusercontent.com/assets/2016523/14935989/abcf14b0-0edd-11e6-8258-f6c4545a7b23.png)

**Comment by locks** [comment]
@BryanCrotaz can you reproduce the screenshot in a Twiddle? It would be very helpful to reviewers.

**Comment by rwjblue** [comment]
As demonstrated by @locks, I don't think this is an Ember bug (the same behavior appears with normal DOM). 

I'm happy to reopen this if we have missed something specific to the issue here, but I'm going to close it for now.
