### ISSUE TITLE
Ember Inflector irregular pluralizations do not work for Camel Cased words

### ISSUE THREAD

**Issue by ggayowsky** [emberjs/ember.js#13443]
I encountered this issue when trying to pluralize, `pointOfInterest` to `pointsOfInterest`.

However, it seems to be broken for all camel cased terms, for example

```
import Inflector from 'ember-inflector'

...

const inflector = Inflector.inflector;
inflector.irregular('mathFormula','mathFormulae');
```

I would expect that `inflector.pluralize('mathFormula')` to be equal to  `mathFormulae`, however, it returns `mathFormula`.

However, `inflector.pluralize('mathformula')` returns `mathFormulae` which is what I would expect

I believe this is a regression since I got the desired behaviour using ember data beta 1.0.0 v 14.

**Comment by stefanpenner** [comment]
The inflector is not part of core. Rather and addon, and bundled with ember-data
