### ISSUE TITLE
getWithDefault broken with chained properties

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/ember.js#13444]
Let's explore how `get(...) || y` and `getWithDefault(x, y)` compare.

```js
> o = Ember.Object.create()
> o.get('foo') || 'x'
"x"
> o.getWithDefault('foo', 'x')
"x"
```
👍 OK, that sounds totally right.

```js
> o.set('foo', 'bar')
> o.get('foo') || 'x'
"bar"
> o.getWithDefault('foo', 'x')
"bar"
```
👍 Cool. Makes sense.

```js
> o = Ember.Object.extend({ foo: null }).create()
> o.get('foo') || 'x'
"x"
> o.getWithDefault('foo', 'x')
null
```
😕 Hmm. That obeys the [API docs](http://emberjs.com/api/#method_getWithDefault) but it doesn't seem super intuitive. [Others agree with me, but there's also good reason to keep it as-is](https://github.com/emberjs/ember.js/pull/13056). In our app, we use `foo: null` as an indication that the client should pass `foo` in; maybe we should change that to `foo: undefined`. Oh well, let's press on.
```js
> o = Ember.Object.create()
> o.get('foo.bar')
undefined
> o.getWithDefault('foo.bar', 'x')
"x"
```
👍 Diggin' it.
```js
> o = Ember.Object.extend({ foo: null }).create()
> o.get('foo.bar') || 'x'
"x"
> o.getWithDefault('foo.bar', 'x')
null
```
WHAT!?!?!?!??!!? :trollface:

**Comment by mmun** [comment]
This is a bug in Ember.get:

```js
Ember.get({ foo: null }, 'bar') // null
```

It should be `undefined`.

**Comment by jamesarosen** [comment]
@mmun on Ember 1.13, I get
```js
> Ember.get({ foo: null }, 'bar')
undefined
```
which is correct as far as I can tell.

**Comment by mmun** [comment]
Oops. I was checking using the console on http://discuss.emberjs.com/ but it seems to be running 1.12 :P

**Comment by mmun** [comment]
You want `foo.bar` there, btw.

**Comment by mmun** [comment]
I just checked it against canary and `Ember.get({ foo: null }, 'foo.bar') === null` still.

**Comment by jamesarosen** [comment]
> You want foo.bar there, btw.

Ah!

**Comment by robbiepitts** [comment]
I have a failing test for this. I'll start a WIP PR.

**Comment by jamesarosen** [comment]
[Here](https://github.com/emberjs/ember.js/blob/783a656e105a7121fc0dc38374931880d14b6bc3/packages/ember-metal/lib/property_get.js#L78-L79) is the bad line as far as I can tell. My guess is that it should be something more like
```js
if (obj == null) {
  return i === parts.length - 1 ? obj : undefined;
}
```

**Comment by locks** [comment]
related: https://github.com/emberjs/ember.js/pull/13449

**Comment by robbiepitts** [comment]
@jamesarosen Yeah, that's where I ended up as well. This was my solution:

```js
if (obj == null) {
  if (i < parts.length) {
    return undefined;
  }
  return obj;
}
```

**Comment by robbiepitts** [comment]
I haven't committed it yet though because I'm not convinced it's the _best_ solution. Going to keep tinkering with this.

**Comment by robbiepitts** [comment]
Tried a recursive approach for `_getPath` but it didn't turn out to be the degree of improvement I had hoped for so I'm sticking with what's there already, but with the above fix. The PR is ready unless anyone has another suggestion. 💃

**Comment by robbiepitts** [comment]
@jamesarosen Looks like the fix will be in the next beta.

This issue can be closed now.
