### ISSUE TITLE
Fix issues with Ember.VERSION changes.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#13452]
Reviewing the diff after https://github.com/emberjs/ember.js/pull/13450 shows the following issues:

- [ ] The version is not properly updated manifest files like `bower.json`, `package.json`, `component.json`, `composer.json`.
- [ ] The header of the various output files (including `ember.debug.js`, `ember-runtime.js`, `ember.prod.js`) is not updated to include the version number (it still includes the `VERSION_STRING_PLACEHOLDER`).
- [ ] The documentation of the `VERSION` property no longer contains a default version.

See https://github.com/components/ember/commit/b32b72a557ce4ec31624ea886cb392a3462ebb59 for a good diff of the published output before/after the change.

**Comment by fivetanley** [comment]
Does this mean that #13450 should be reverted? I'm not sure how to do the string transformations other than through broccoli for the component files and code comments.

**Comment by krisselden** [comment]
I know how to address all of the above

**Comment by krisselden** [comment]
Working on this here https://github.com/emberjs/emberjs-build/pull/154

**Comment by krisselden** [comment]
The version is at the top of the http://builds.emberjs.com/canary/ember-docs.json output, I don't think it also needs to be documented as a 'default' tag, it is a readonly property.  The other issues are fixed in https://github.com/components/ember/commit/dccb3f542337dcd7ef462f27327c2091850800b3

**Comment by rwjblue** [comment]
Agreed. Thanks for tackling so quickly.
