### ISSUE TITLE
FastBoot Bug - Location none doesn't respect rootURL

### ISSUE THREAD

**Issue by jasonmit** [emberjs/ember.js#13464]
Location none doesn't respect the router's `rootURL`.  This causes issues while [generating urls](https://github.com/emberjs/ember.js/blob/45248e2fb2c71ec60bb879c7588beeaeffe6dc6c/packages/ember-routing/lib/location/none_location.js#L85-L90) (link-to's for example will omit the `rootURL`).  Compare this to [history's formatURL](https://github.com/emberjs/ember.js/blob/45248e2fb2c71ec60bb879c7588beeaeffe6dc6c/packages/ember-routing/lib/location/history_location.js#L216) and you'll see the difference between implementations.

This is causing issues within the non-browser path of the `visit` API since it [always defaults](https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/application-instance.js#L384-L388) to the `none` location.

I would be happy to help patch, but first would like to hear feedback though before venturing off.  For example, do we want to stub out the window.location API when in Node and stick with using the history location, do we patch the none location to respect rootURL in formatURL, or something I'm not thinking of?

Part of this is related to:
https://github.com/ember-fastboot/ember-fastboot-server/issues/53

**Comment by pixelhandler** [comment]
@jasonmit perhaps the first step is a failing test

**Comment by jasonmit** [comment]
Sure, I'll add some failing tests on the location none.  I was more interested in feedback to see how it should be fixed before going down that route.

The reproduction steps are:
* set rootURL to `/foo/`
* set location to `none`
* add a simple route `this.route('bar');`
* in application template `{{link-to 'bar' 'bar'}}`
* run app, observe the href of the bar link, notice no `/foo/` prefix
* switch location to `auto` and repeat last step

**Comment by jasonmit** [comment]
Here are two failing tests on formatURL and getURL: https://github.com/jasonmit/ember.js/commit/ae4e7b25240e1c52fdc07b5f313c2d46b0059cef

It didn't appear there was test coverage around location none.

**Comment by tomdale** [comment]
I think we should definitely add support for `rootURL` to the `none` location; the point is that it's an API-compatible version of the other Locations, but without side-effects. This IMO is clearly breaking compatibility with other locations, so should be considered a bug.

**Comment by jasonmit** [comment]
Thanks for getting back, I'll take a pass at fixing this either tonight or tomorrow.

**Comment by jasonmit** [comment]
@tomdale I am just about done but there is a deficiency in the current API that I'd like to get your feedback on.

The `visit` API takes in a url arg, sets it on the location, and then calls `handleURL` on the router with that same argument.  The issue here is we pass the visit API the full request URL which would include the rootURL and the router would attempt to transition to it and would result in no match.

https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/application-instance.js#L282-L284

There are a few solutions:
* The visit API lobs off the `rootURL` before the `setURL` and before the `handleURL`
* We expose a new API on the router to have the locations normalize the url and that return value is used in the `router.handleURL` instead of the input `url`
* The router's `handleURL` fn will lob off the `rootURL`

**Comment by jasonmit** [comment]
@tomdale ready for you to review.
