### ISSUE TITLE
Using raw d3 resulting in possible conflict between ember.copy() and d3.copy()

### ISSUE THREAD

**Issue by atonse** [emberjs/ember.js#13474]
I am currently using d3 in an ember app (via the c3 graphing library) and it's working just fine. I started creating another component elsewhere in the app, and this one involves raw drawing of svg using d3.

But I am getting an error `TypeError: s.domain is not a function. (In 's.domain()', 's.domain' is undefined)` (https://ember-twiddle.com/515a0c6ba90e1d200075a38c68209adb) – and when I try to debug and step through, it turns out that in the d3 code, d3 thinks it's making a copy of a `scale` object using the scale object's `copy` function, but when you introspect on that `copy` function, it's actually ember's `copy` function.

Could it be that ember is overriding d3's copy somehow? The weird thing is it's working just fine in my other route (same app, same d3 script, etc).

I might cross-post in the d3 repo as well if ember devs find that this isn't an issue.

**Comment by atonse** [comment]
Interestingly when I remove a particular line from the d3 code `.ticks(d3.time.day, 1)`, everything works. Something with the interaction between ember and d3?

**Comment by mike-north** [comment]
ticks returns an array. See: https://github.com/mbostock/d3/wiki/Quantitative-Scales#linear_ticks . This has nothing to do with ember. The copy method you're seeing is on the array prototype.

**Comment by atonse** [comment]
Thank you @mike-north! I thought `ticks` is a way to tell d3 that I want the ticks to be one week apart. I'll close this issue
