### ISSUE TITLE
TypeError: instance.container is not a function

### ISSUE THREAD

**Issue by vivian-ho** [emberjs/ember.js#13486]
I'm trying to upgrade to Ember 2.5 from 2.0 and getting this: TypeError: instance.container is not a function.  I have commented out all initializers in the app.  Thanks for any help.

**Comment by pixelhandler** [comment]
@vivian-ho Hi it sounds like you may need to use `getOwner` instead of `this.container`. But I think what you could use is some support. Have you asked this question in the embercommunity.slack.com #-help channel?

I'll close this out for now since it's not an Ember bug.
