### ISSUE TITLE
Checkbox needs title, value and hidden attribute's bindings

### ISSUE THREAD

**Issue by ykaragol** [emberjs/ember.js#13484]
Currently [checkbox ](https://github.com/emberjs/ember.js/blob/v2.5.0/packages/ember-views/lib/views/checkbox.js#L42)has following attributeBindings:
- 'type' 
- 'checked' : 
- 'indeterminate' :
- 'disabled' : 
- 'tabindex',
- 'name',
- 'autofocus',
- 'required',
- 'form'

From [checkbox definition](https://www.w3.org/TR/html-markup/input.checkbox.html) the following binding is missing:
- 'value'

And from [global properties](https://www.w3.org/TR/html-markup/global-attributes.html) the following bindings are missing:
- 'class'
- 'hidden'
- 'title'
- 'accesskey'

These attributes are need to be added to the checkbox. 

I saw an issue about ['title'](https://github.com/emberjs/ember.js/issues/12865) but it was closed. (IMO, closing that issue was a mistake.)

**Comment by Serabe** [comment]
`value` is [intentionally not supported](https://github.com/emberjs/ember.js/blob/74937c7631c5166cdfbd3c0a34bc2101fa47e4a0/packages/ember-htmlbars/lib/keywords/input.js#L160). `class` is supported through `classNames` (see [twiddle](https://ember-twiddle.com/4aaa9ddf1be1849bb3e004978d636af1?openFiles=styles.app.css%2C)).

**Comment by Artmann** [comment]
Should the input helpers for  `checkbox`, `textarea` and `textfield` support `hidden`, `title` and `accesskey` as attribute bindings?

**Comment by pixelhandler** [comment]
@Artmann @Serabe @locks @ykaragol is this still an issue, perhaps we should close; what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
