### ISSUE TITLE
[BETA and CANARY] `block` is undefined on tagless and blockless components

### ISSUE THREAD

**Issue by miguelcobain** [emberjs/ember.js#13494]
I'm getting a `TypeError: Cannot read property 'template' of undefined` because `block` is undefined in this line: https://github.com/emberjs/ember.js/blob/master/packages%2Fember-htmlbars%2Flib%2Fhooks%2Fcomponent.js#L57

The tests are ok in ember-release and fail on beta and canary channels.

The tests that fail involve tagless blockless components, so I assume the bug is related to that.

Build log: https://travis-ci.org/miguelcobain/ember-leaflet/jobs/129892214

**Comment by Serabe** [comment]
Seems related to local lookup. // @rwjblue

**Comment by rwjblue** [comment]
This was introduced by https://github.com/emberjs/ember.js/commit/869ed3084eb10ba32c8148fbc08c222b544eead1#diff-7d2b815a163f3a57292f65c26e98c051R56.  When no block is passed, there is no `state.manager.block`.  

The first step would be to submit a failing test PR (and also adding a test for a tagless blockless component using local lookup).  The fix *might* be as simple as guarding there, but I suspect to support local lookup in tagless/blockless we will need to tweak the logic.

**Comment by asakusuma** [comment]
Now that we have a simple repro I'll work on fixing this

**Comment by rwjblue** [comment]
Thanks @asakusuma

**Comment by rwjblue** [comment]
I believe this applies to 2.6.0, so it will likely warrant a point release once fixed.

**Comment by ForSpareParts** [comment]
If anybody else is having this problem, a temporary workaround is to add a tag to your tagless component until the point release lands.

**Comment by mixonic** [comment]
@rwjblue @asakusuma this can be closed?

**Comment by asakusuma** [comment]
@mixonic yes this can be closed

**Comment by mixonic** [comment]
Thanks @asakusuma :-)

**Comment by miguelcobain** [comment]
Looks like this problem isn't solved yet @asakusuma @rwjblue 

I get a `null is not an object (evaluating 'sm.scope._view.template.meta')` error.

Log: https://travis-ci.org/miguelcobain/ember-leaflet/jobs/146079848

Any idea?

**Comment by asakusuma** [comment]
@miguelcobain can you provide a failing test PR?

[We have a test that is supposed to guard](https://github.com/emberjs/ember.js/blob/5757ea5f8a7dd4e93113d1a195e18532656c07ea/packages/ember-glimmer/tests/integration/components/closure-components-test.js#L622) this problem but sounds like we are missing a case.

**Comment by miguelcobain** [comment]
I'll try to come up with a failing test for ember.

Meanwhile,
this is the failing test on ember-leaflet: https://github.com/miguelcobain/ember-leaflet/blob/master/tests/integration/components/tile-layer-test.js#L23-L48

and this is the component being tested: https://github.com/miguelcobain/ember-leaflet/blob/master/addon/components/tile-layer.js

which inherits from: https://github.com/miguelcobain/ember-leaflet/blob/master/addon/components/base-layer.js

Just in case you spot something odd there.

**Comment by miguelcobain** [comment]
I could reproduce the problem in a twiddle: https://ember-twiddle.com/d5f6fc09d9f2a86098012c7304c9e4a6?openFiles=controllers.application.js%2C

Click to change the value, and see an error coming up.
The component is tagless, blockless and templateless, if that has any importance.

@GavinJoyce or me will provide a failing test soon.
