### ISSUE TITLE
Cannot add third party functionality

### ISSUE THREAD

**Issue by arimiller67** [emberjs/ember.js#13496]
My company is working with a developer who has apparently used Ember to structure the site's JS. We have requested several third party functions to be added to the site - Juicer.io, Crazy Egg, etc. They are telling us that these interfere with Ember and cannot be used. 

If Ember is intended to **enhance** JS functionality, then this doesnt make sense to us. Im looking for an objective, outside opinion as to whether what we are being told is true and whether others are having this experience as well.

Thanks in advance for your patience and generosity in taking the time to reply!

**Comment by Serabe** [comment]
Hello, @arimiller67. I am closing this since it is not an Emberjs bug. Please, go to #general or #-help channels on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

Thank you!
