### ISSUE TITLE
How to send date as header param when sending a GET request to an API?

### ISSUE THREAD

**Issue by charuag** [emberjs/ember.js#13498]

**Comment by robbiepitts** [comment]
@charuag You can easily specify static and dynamic headers if you're using an adapter descended from the `RESTAdapter` by following the instructions here: http://emberjs.com/api/data/classes/DS.RESTAdapter.html#toc_headers-customization

It seems to me like you're looking for something like the following (replace `RESTAdapter` with the adapter you're actually using):

```js
import DS from 'ember-data';

export default DS.RESTAdapter.extend({
  dateHeaderValue: Ember.computed(function() {
    return new Date().toISOString();
  }).volatile(),

  headers: Ember.computed('dateHeaderValue', function() {
    return {
      "DATE": this.get('dateHeaderValue')
    };
  })
});
```

**Comment by Serabe** [comment]
Hello, @charuag. I am closing this since it is not an Emberjs bug. Please, go to #-help channel on Slack if you need more information. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

Thank you!
