### ISSUE TITLE
Using Ember with PDF.js

### ISSUE THREAD

**Issue by richkniles** [emberjs/ember.js#13509]
We've been trying to incorporate PDF.js into an Ember project and ran into an issue we raised on their repo.  The response was:

    It seems that the problem is caused by Ember, since it's adding a number of methods on 
    Arrays, but for some reason they are all enumerable which is the cause of the problem. 
    When adding methods on e.g. Arrays and Objects, they should be set to 
        enumerable = false, 
    just like the native methods are.
    Hence this seem to be the same underlying problem as in #7064, 
    please refer to the discussion there.

    This is an issue with Ember, and not PDF.js, hence I'm closing this issue.

**Comment by chadhietala** [comment]
You can turn off specific prototype extensions. https://guides.emberjs.com/v2.5.0/configuring-ember/disabling-prototype-extensions/

**Comment by chadhietala** [comment]
Feel free to reopen if this does not resolve your issues.

**Comment by richkniles** [comment]
For future reference to others interested in using PDF.js with Ember, turning off extensions for Array appears to fix the issue of incorrect pdf rendering of some pdf files. 

Thanks @chadhietala

**Comment by richkniles** [comment]
Actually turning off extensions for Array is a pretty big deal for our project as the extensions are used a lot.  I found a different possible solution: 

    var properties = Object.keys(Array.prototype);
    for (var i = 0; i < properties.length; i++) {
      property = properties[i];
      var descriptor = Object.getOwnPropertyDescriptor(Array.prototype, property);
      descriptor.enumerable = false;
      Object.defineProperty(Array.prototype, property, descriptor);
    }

Incidentally, without Ember Object.keys(Array.prototype) is empty, so this isn't "de-enumerating" any non-ember properties.

What do you think? Are ember's additions enumerable for a reason?

**Comment by stefanpenner** [comment]
@richkniles hmm, seems bad that we make them enumerable in the extend array prototypes case. I think that should be considered a bug.
