### ISSUE TITLE
Brace expansion in `addObserver` doesn't work

### ISSUE THREAD

**Issue by Asherlc** [emberjs/ember.js#13517]
This is a tortured example, but I believe it illustrates the problem:

https://ember-twiddle.com/fad06431ff6f578dd6b6762b6ef1282c?fileTreeShown=false&openFiles=controllers.application.js%2C

If given a property key with the brace expansion syntax, it won't update. Without it, it works fine.

**Comment by stefanpenner** [comment]
This isn't a bug, but rather not something low level API such as addObserver support. I can appreciate why this seems strange, but the brace expansion only exists for the high level API's used at class design time.

**Comment by Asherlc** [comment]
It would be great if this was documented in that case

**Comment by stefanpenner** [comment]
> It would be great if this was documented in that case

it is, by virtue of only being documented for the high level apis.

**Comment by Asherlc** [comment]
Technically in the API, it's not documented for either method: http://emberjs.com/api/classes/Ember.computed.html

Though I suppose it only references brace expansion in reference to CP's here: https://guides.emberjs.com/v2.3.0/object-model/computed-properties/

**Comment by stefanpenner** [comment]
> Technically in the API, it's not documented for either method: http://emberjs.com/api/classes/Ember.computed.html

might be good to document it at that level
