### ISSUE TITLE
Problem with setting and resetting value in component with a bound attribute

### ISSUE THREAD

**Issue by mhesler** [emberjs/ember.js#13512]
A problem appears when setting a component property to another value and then back to the original value within the same run loop when it is bound through an attribute.  The attribute remains as the new value rather than getting set back to the original value as would be expected.
[Example JsFiddle](http://jsfiddle.net/3nmwaqrj/)

**Comment by Serabe** [comment]
It changes to the last set value different than the original. This [fork from @mhesler's fiddle](http://jsfiddle.net/sf86jozz/) shows that.

**Comment by pixelhandler** [comment]
@mhesler is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
