### ISSUE TITLE
Improve EventDispatcher unable to attach to element assertion

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#13529]
https://github.com/emberjs/ember.js/blob/74937c7631c5166cdfbd3c0a34bc2101fa47e4a0/packages/ember-views/lib/system/event_dispatcher.js#L173

Should most likely also display the selector it was unable to attach to in the assertion message.

I also believe this should not be an assertion, rather a TypeError as it is helpful (and little cost) for all builds of an app.

**Comment by jmar910** [comment]
Wanted to take a stab at this and get my feet wet with contributing to ember. 

This is what I have based on if I'm understanding correctly:
```
if (rootElement.is(ROOT_ELEMENT_SELECTOR)) {
      throw new TypeError(`Unable to add '${ROOT_ELEMENT_CLASS}' class to root element (${rootElement.selector || rootElement[0].tagName}). Make sure you set rootElement to the body or an element in the body.`);
    }
```

Let me know if i'm on the right track 😄

**Comment by stefanpenner** [comment]
@jmar910 LGTM

**Comment by sukima** [comment]
@stefanpenner Is this issue done? Can it be closed?

**Comment by rwjblue** [comment]
Thanks @sukima!
