### ISSUE TITLE
Ember.computed.sort and async relationships

### ISSUE THREAD

**Issue by gzurbach** [emberjs/ember.js#13524]
Hey there! I am seing an issue that I am pretty sure did not exist a couple weeks ago (before upgrading Ember / Ember Data to 2+).

On page load the list of memberships (usually between 1 and 5) that belongs to a user are loaded asynchronously along with that user. I am sorting them by expire date to find a potential non-expired membership in the list.

Below is my (simplified) `models/user.js` file:
```javascript
export default DS.Model.extend({
  email: DS.attr('string'),
  name: DS.attr('string'),

  memberships: DS.hasMany('membership', { async: true }),

  // does NOT work
  expireAtSortingDesc: ['expireAt:desc'],
  sortedMemberships: computed.sort('memberships', 'expireAtSortingDesc'),
  
  // works
  sortedMemberships: computed('memberships.[]', function() {
    let memberships = this.get('memberships');
    return memberships.sortBy('expireAt').reverseObjects();
  })
});
```

The above workaround seems to work for me but I am pretty sure that `computed.sort` used to do the job with `async` `hasMany` relationships. Am I doing anything wrong?

Thanks!

**Comment by mmun** [comment]
What version of ember are you using specifically? There was an important bug fix for computed.sort that landed in 2.4.0.

**Comment by gzurbach** [comment]
I am using the following:
Ember 2.3.2
Ember Data 2.4.3

I will try to upgrade Ember tonight, see if it fixes the issue and let you know. Thanks for the heads up.

**Comment by gzurbach** [comment]
Updated to Ember 2.5 and everything works again. Sorry for the noise, and thanks for your help sir!

**Comment by mmun** [comment]
Good to hear!
