### ISSUE TITLE
Ember 1.13.x regression - render helper doesn't generate proxy controllers

### ISSUE THREAD

**Issue by MiguelMadero** [emberjs/ember.js#13538]
There is a fix for it on https://github.com/zenefits/ember.js/pull/1 I'm not sure how/if I can open a PR for a fix for 1.13. 

Prior to 1.13, ember used to generate an ObjectController or ArrayController when using `{{render 'name' objectOrArray}}`. 

Here is a twiddle where we can toggle between 1.12 and 1.13 to see the error
https://ember-twiddle.com/df75fe63672f01c4bf5f8f4b8a35ffc7?openFiles=controllers.application.js%2C

Proxy controller generation when returning and object or array from a route's model hooks still works as it did in old versions since the context is passed for that case, see https://github.com/emberjs/ember.js/blob/fixes-render-controller-generation/packages/ember-routing/lib/system/generate_controller.js#67. See test to prove this: https://ember-twiddle.com/a23bfd0e4223cdcc762a5ecfb1097cac?fileTreeShown=false&openFiles=templates.something.hbs%2C&route=%2Fsomething 

I know that the need to fix this can be a bit controversial since 1.13 is really old, but there are still a lot of users on it that will likely be there for some months and others that are just migrating (like us) and finding out these issues. 

Something to consider is breaking changes between is on 1.13.x and 1.13.14 (or some version with this fix), they will move from controller:basic, back to a proxy controller. I think the change is backwards compatible since the `model` property is still present, but there is something I might be missing. 

cc: @mmun @ebryn

**Comment by pixelhandler** [comment]
@MiguelMadero it's very unlikely that there will be any patches applied to v1.13; which was supported much longer than expected. Now that there is a LTS release that will be the focus for longer support and patches.

That said you may need to fork, patch, and build.

**Comment by pixelhandler** [comment]
@MiguelMadero We're in the process of closing out issue for v1.13 as unsupported. I'll close this out for now.

**Comment by MiguelMadero** [comment]
>  I'll close this out for now. 

Sounds good. If anyone cared, they could always use at their own risk the zenfits version of 1.13 with a bunch of fixes or cherry-pick the patch ^^.
