### ISSUE TITLE
Component attributes are not removed when dynamically set to null

### ISSUE THREAD

**Issue by mguterl** [emberjs/ember.js#13537]
This twiddle illustrates the issue pretty clearly if you inspect the rendered DOM.

https://ember-twiddle.com/ac6ac134c6646466e71e5cb7b2def69d?openFiles=templates.application.hbs%2Ctemplates.components.my-component.hbs

The component documentation states that if you set an attribute to null it won't be included. This works great for components that never change, but in the case where they do it is not removed and it's content is set to null.

**Comment by robbiepitts** [comment]
@mguterl Looks like this issue is due to `download` being a property as well as an attribute on the `<a>` element. [Here](https://github.com/tildeio/htmlbars/blob/ba212c9dc100e674b03b2fc78dbfb654395ae18f/packages/dom-helper/lib/prop.js#L14) is where we handle this situation.

I'm going to keep looking at this to verify whether or not I'm actually correct and try to get a failing test.

**Comment by mguterl** [comment]
Thanks @robbiepitts!

**Comment by robbiepitts** [comment]
Np, @mguterl! I've opened a PR in tildeio/htmlbars to address this.

Unrelated to the issue but I noticed that you are setting `download` to `"true"` which—through the digging I've done for this issue—I've discovered that [the value should be your recommended filename](https://html.spec.whatwg.org/multipage/semantics.html#attr-hyperlink-download). For example, maybe the actual filename has some ugly fingerprint on it. If you want to pre-populate the save prompt with a friendly filename you can do this with the `download` attribute.

**Comment by mguterl** [comment]
@robbiepitts you make an interesting point about the value of the download attribute. I actually don't want to supply any value at all `<a href='example.com/whatever' download>Download</a>`. Can you make any suggestions on how I should accomplish that?

**Comment by pixelhandler** [comment]
@mguterl I took a look at your Ember Twiddle in Safari and the `download` attribute is removed. But in Chrome it is not it's `null`.  I forked your twiddle and noticed the same issue with the `target` attribute. https://ember-twiddle.com/94d2a864f048ab08e8f5dbf59ea55f79?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs

**Comment by pixelhandler** [comment]
This issue duplicates: #12358

**Comment by pixelhandler** [comment]
I believe this is resolved and works fine current ember version, at this time v3.4.1
