### ISSUE TITLE
blueprints need tests here

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#13545]
most likely steal from: https://github.com/ember-cli/ember-cli-legacy-blueprints

**Comment by rwjblue** [comment]
Hmm. I thought we did have tests?

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/tree/master/node-tests/blueprints

**Comment by stefanpenner** [comment]
Oh ya

**Comment by stefanpenner** [comment]
I did notice they are fairly coupled to ember-cli, I'm going to work to decouple them.
