### ISSUE TITLE
ember.debug.js:32096Error: No model was found for 'case'

### ISSUE THREAD

**Issue by smitakiran25** [emberjs/ember.js#13569]
I am using the following ember versions

ember-cli :2.5.0
npm version: 3.9.2
bower version: 1.7.9
OS : Fedora 20

i am using patternfly

app/newcase.hbs:

<div class="container-fluid" id="enquiry">
      <div class="row">
        <div class="col-sm-9 col-md-10">
          <div class="col-sm-12 col-md-6">
            <form class="form-horizontal">

              <div class="form-group">
                <label class="col-md-4 control-label" for="textInput2">Location</label>
                <div class="col-md-8">
                  <input type="text"  id="textInput2" class="form-control" value= location>
                </div>
              </div>

    <div class="form-group">
    <label class="col-md-4 control-label" for="textInput2">Emergency Type</label>
    <div class="col-md-8">
      <select id="txtCallTime" name="prfrd" class="form-control" required="required">
          <option>Emergency</option>
          <option>Non Emergency</option>
          <option>Others</option>
    	</select>
    </div>
  </div>

    <div class="form-group">
    <label class="col-md-4 control-label" for="textInput2">Relationship</label>
    <div class="col-md-8">
      <select id="txtCallTime" name="prfrd" class="form-control" required="required">
					<option>Husband</option>
          <option>Father</option>
          <option>Mother</option>
          <option>Wife</option>
          <option>Brother</option>
          <option>Son</option>
          <option>Daughter</option>
        </select>
    </div>
  </div>

  <div class="form-group">
    <label class="col-md-4 control-label" for="textInput2">Contact Number</label>
    <div class="col-md-8">
      <input type="text"  id="textInput2" class="form-control">
    </div>
  </div>

  <div class="form-group">
    <label class="col-md-4 control-label" for="textInput2">Number of Patients</label>
    <div class="col-md-8">
      <input type="text"  id="textInput2" class="form-control">
    </div>
  </div>

<div class="form-group">
    <label class="col-md-4 control-label" for="textInput2">Number of Ambulance</label>
    <div class="col-md-8">
      <input type="text"  id="textInput2" class="form-control">
    </div>
  </div>

  <div class="form-group">
    <label class="col-md-4 control-label" for="textInput2">Address</label>
    <div class="col-md-8">
     <textarea name="comment" id="comment" placeholder="Address Hereâ€¦" tabindex="4" class="form-control" style="margin: 0px -55px 10px 0px; width: 100%; height: 90px;"></textarea>
    </div>
  </div>

    <div class="form-group">
    <label class="col-md-4 control-label" for="textInput2">Call From</label>
    <div class="col-md-8">
      <select id="txtCallTime" name="prfrd" class="form-control" required="required">
          <option>Family</option>
          <option>Friend</option>
          <option>Organisation</option>
      </select>
    </div>
  </div>

      <div class="form-group">
        <label class="col-md-4 control-label" for="textInput2">Date Of Call</label>
        <div class="col-md-8">
          <input type="date" name="usr_date" style="width:100%">
        </div>
      </div>

      <div class="form-group">
    <label class="col-md-4 control-label" for="textInput2">Time Of Call</label>
    <div class="col-md-8">
 <input type="time" name="usr_time" style="width:100%">

    </div>
  </div>

   <div class="form-group">
    <label class="col-md-4 control-label" for="textInput2">Call Alert </label>
    <div class="col-md-8">
      <input type="text"  id="textInput2" class="form-control">
    </div>
  </div>

  <div class="form-group">
    <label class="col-md-4 control-label" for="textInput2">Call Status</label>
    <div class="col-md-8">
      <input type="text"  id="textInput2" class="form-control">
    </div>
  </div>

          <div class="form-group">
    <label class="col-md-4 control-label" for="textInput2">Time Stamp</label>
    <div class="col-md-8">
      <input type="datetime-local" value="1985-04-12T23:20:50.52" class="form-control"/>
    </div>
  </div>

            <div class="form-group">
                 <label class="col-md-4 control-label" for="textInput2"></label>

    <div class="col-md-8">
      <button {{action 'addCase' model.id}} type="button" class="btn btn-primary">Submit</button>
      <button type="button" class="btn btn-default">Cancel</button>
    </div>
    <div class="col-md-10 col-md-offset-2">
    </div>
  </div>
</form>

 app/controller/newcase.js

import Ember from 'ember';
export default Ember.Controller.extend({
  actions:{
    addCase: function() {
      var location = this.get('location');
      var emergencytype = this.get('emergencytype');
      var relationship = this.get('relationship');
      var contact_number = this.get('contact_number');
      var num_of_patients = this.get('num_of_patients');
      var num_of_ambulance = this.get('num_of_ambulance');
      var address = this.get('address');
      var call_from = this.get('call_from');
      var date_of_call = this.get('date_of_call');
      var time_of_call = this.get('time_of_call');
      var call_alert = this.get('call_alert');
      var call_status = this.get('call_status');
      var time_stamp = this.get('time_stamp');

     var newCase = this.store.createRecord('case', {
       location : location,
       emergencytype : emergencytype,
       relationship : relationship,
       contact_number : contact_number,
       num_of_patients : num_of_patients,
       num_of_ambulance : num_of_ambulance,
       address : address,
       call_from : call_from,
       date_of_call : date_of_call,
       time_of_call : time_of_call,
       call_alert : call_alert,
       call_status : call_status,
       time_stamp : time_stamp
     });

    newCase.save();

  this.setProperties({
    location: ' ',
    emergencytype: ' ',
    relationship: ' ',
    contact_number: ' ',
    num_of_patients: ' ',
    num_of_ambulance: ' ',
    address: ' ',
    call_from: ' ',
    date_of_call: ' ',
    time_of_call:' ',
    call_alert:' ',
    call_status:' ',
    time_stamp: ' '
  });
  }
 }
});

app/model/newcase.js

import Model from 'ember-data/model';
import attr from 'ember-data/attr';
export default Model.extend({
  location: attr('string'),
  emergencytype: attr('string'),
  relationship: attr('string'),
  contact_number:attr('number'),
  num_of_patients: attr('number'),
  num_of_ambulance: attr('number'),
  address: attr('string'),
  call_from: attr('string'),
  date_of_call: attr('date'),
  time_of_call: attr('time'),
  call_alert: attr('string'),
  call_status: attr('string'),
  time_stamp: attr('time')
});

app/route/newcase.js

import Ember from 'ember';
export default Ember.Route.extend({
  model: function() {
    return this.get('store').findAll('case');
  }
});

app/router.js
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType
});
Router.map(function() {
this.route('newcase');
});
export default Router;
 

i am getting 'No model was found for 'case'' error

please tell me how to write the code for drop down select  for my code

**Comment by RobIsHere** [comment]
Your model is called "newcase" because it is stored in a file with name app/model/newcase.js
So creating a model called 'case' results in an error.
```
var newCase = this.store.createRecord('case', { ...
// rename your model file to 'case' or do this instead:
var newCase = this.store.createRecord('newcase', { ...
```

Creating a select is pretty straightforward nowadays. For example http://balinterdi.com/2015/08/29/how-to-do-a-select-dropdown-in-ember-20.html or some other tutorial on google helps. Just filter out google search results older than 1 year because old artikels are usually outdated and misleading.

As an alternative there are a lot of add-ons for select. You can find them e.g. here:
https://www.emberobserver.com/categories/select

**Comment by pixelhandler** [comment]
@smitakiran25 I'll close this out for now. This is not an Ember.js Bug. As @RobIsHere mentioned there are some good community solutions for using `select`, perhaps try the x-select or ember-power-select addons. Also feel free to join the #-help chat room in embercommunity.slack.com to get help.
