### ISSUE TITLE
Can we dynamically set environment config variables in ember from a parent application?

### ISSUE THREAD

**Issue by charuag** [emberjs/ember.js#13578]
I'm loading my ember app via an iframe from a parent application and sending config variables via postMessage to my ember app. Can I set those config variables received via window eventlistener receiveMessage to ember environment variables?

**Comment by pixelhandler** [comment]
@charuag that's a good question. Have you asked in the Ember chat at embercommunity.slack.com in the #-help channel yet?

**Comment by charuag** [comment]
Yup! I've already asked this question on help channel. But never received any reply. Can you point me in right direction to help me out with this.

**Comment by pixelhandler** [comment]
@charuag Since this is not a bug report for the Ember.js project I need to close out this issue. I also asked for help in the chatroom (in reference to this issue/question).

**Comment by pixelhandler** [comment]
@charuag I posted some ideas in the #-help channel on slack

**Comment by charuag** [comment]
Great! I'll check out the slack channel. Thanks @pixelhandler
