### ISSUE TITLE
Route Model Hook Returns a Copy and not a Refference

### ISSUE THREAD

**Issue by spinlock99** [emberjs/ember.js#13572]
I've just implemented a route which checks Ember Data to see if there are any records and, on a cache hit, returns a `DS.RecordArray`. It will also fire off a `store.query` to check the back-end for any new data that is not in the store (see write-up [here](http://discuss.emberjs.com/t/how-can-i-bind-data-returned-from-the-model-hook-to-the-template/10730)).

The issue is that the `DS.RecordArray` returned from the model hook is not updated with new records retrieved from the back-end. The expectation that I had is that a `DS.RecordArray` returned from the `model` hook would be updated when the store is updated.

The workaround is to create a computed array in the template's controller and bind to that. Now, when new records come back from the `model` hook, the `DS.RecordArray` grows to include the new data and the page is updated.

Q: Why is this an issue?
A: I'm writing this up because it seems to break the convention of returning data from the route's `model` hook to bind to the template. I expected a computed property returned from the `model` hook to update when it's dependent data changed.

**Comment by locks** [comment]
As far as I know, only `.peekAll` returns a live array.

**Comment by pixelhandler** [comment]
@spinlock99 this issue looks like a question rather than an Ember.js Bug. I'll close this out, but please do followup by reaching out to the ember community like you've done on discuss.emberjs.com also it would be good to reach out in the #-help channel of the embercommunity.slack.com chat room.

I took a look at your code on discuss, it looks like you're returning an RSVP hash from the model hook:

```
    model: ->
      @fetchContent(@store.peekAll('organization'))
      return Ember.RSVP.hash
        columns: @get('columns')
        content: @get('filteredAlerts')
```

The store.query returned from the fetchContent method is not returned from the model hook.

**Comment by spinlock99** [comment]
@pixelhandler, thanks for the reply. You are correct, I"m not returning the call from `store.query`. That call is used to fetch new records from the API. The idea is that I show the data already in `EmberData` then update the data when the API call returns. The reason I think this is a bug is here:

![screen shot 2016-05-20 at 11 23 39 am](https://cloud.githubusercontent.com/assets/453431/15684307/68c6403e-271b-11e6-97fc-f4e29344b47b.png)

Those two arrays should be the same. After all, the controller's `content.content` _is_ the route's `filteredAlerts`. The expected behavior (by me anyway :) is that returning `filteredAlerts` from the route's model hook will return a reference to `filteredAlerts` that will update when `filteredAlerts` is updated. But, the behavior is that a copy of `filteredAlerts` is being returned that is _not_ updated when `filteredAlerts` is updated.

If you look at the discus thread, I've updated it with a work-around. What I've done is to copy the logic to create `filteredAlerts` into the controller and bind the template to this computed property in the controller. This works as expected (i.e. the `DS.RecordArray` is updated when the API call returns and the user sees their data "grow"). It just feels wrong that binding to a computed property in the controller should behave differently than returning the same array from the route's model hook.

The hard thing about this bug is that you need an API that will return new data to recreate it. I'll work on a simple example to demonstrate what's going on.

**Comment by spinlock99** [comment]
@pixelhandler, here's a fresh repo that demonstrates the issue: https://github.com/spinlock99/ember-caching-issue.

The application template iterates over `filteredTasks` returned from the route's model hook and a computed property in the controller (I've used a mixin so that these are created with exactly the same logic). After the `findAll()` call returns, 10 new records are created in the store. The controller's `filteredTasks` is updated with this new data and you can see the records in the template. The `filteredTasks` returned from the model hook, however, remains empty.
