### ISSUE TITLE
Path reappended on refresh when using custom rootURL

### ISSUE THREAD

**Issue by rohmann** [emberjs/ember.js#13582]
I'm seeing an issue where if I'm embedding an app by setting  `rootURL` on the router, that base path will be duplicated if I refresh after changing URL. This is specific to the `history` location type.

I've tested this on 2.6.0-beta4, but had issues testing it with Canary. [Here's a twiddle](https://ember-twiddle.com/3853e6816392fcebddcb4a117992823a?openFiles=router.js%2C) with the code that can be used to reproduce it, but it doesn't help much since `rootURL` doesn't work there. 

These steps describe how the problem could be reproduced.
1. The Routers's `rootURL` is set to `/embed-path/`
2. The Routers's `location` is set to `history`
3. Enter the app via first route. `http://example.com/embed-path/first-route/`
4. Navigate to another route `http://example.com/embed-path/second-route/` using a `linkTo` helper.
5. Refresh the page.
6. The browser will show `http://example.com/embed-path/embed-path/second-route/` as the location, and the app fails to recognize the route.

**Comment by Turbo87** [comment]
@rohmann this whole rootURL/baseURL thing has been overhauled in the current Ember CLI canary branch (see http://emberjs.com/blog/2016/04/28/baseURL.html). you should probably try if updating to the canary fixes things for you.

**Comment by pixelhandler** [comment]
@rohmann I've been only using `baseURL` for hosting an Ember app in a specific directory, but when I do that I also use root relative paths to the assets by hardcoding that base url in the index.html file as well. Plus any paths in .css files for images, etc.

**Comment by rohmann** [comment]
Thanks @Turbo87 I created a brand new app from canary and can't reproduce the issue.
