### ISSUE TITLE
Should render helper be marked as deprecated?

### ISSUE THREAD

**Issue by alexspeller** [emberjs/ember.js#13583]
https://github.com/emberjs/ember.js/blob/v2.5.0/packages/ember-routing-htmlbars/lib/keywords/render.js#L16 is not marked as deprecated - I was surprised to learn it even still existed actually. Should it be deprecated at this point?

**Comment by ef4** [comment]
It is definitely a legacy from an earlier time. I doubt anyone will argue we want to keep it around.

It exists mostly because (1) we could only do so much in the run up to 2.0 and we prioritized shipping over completing the entire wishlist of changes, and (2) the volume of deprecations at that time was already very high and the tooling for managing them wasn't as good as it is today, so we deliberately backed off on deprecations for a while to give everybody time to adapt.

Now that we are well into the 2.x series, I am in favor of deprecating `render` with extreme prejudice.

**Comment by rwjblue** [comment]
Using `{{render 'foo' blah}}` (with two args) is already deprecated.  To deprecate the singleton use case, we will need to write a migration guide that shows how to use the combination of service and component.

**Comment by ErikCH** [comment]
I'd be interested in taking on some documentation. I found the deprecation guide for using a model in render [here](http://emberjs.com/deprecations/v2.x/#toc_model-param-in-code-render-code-helper).  I'm guessing the render deprecation guide would be about the same, although the render model deprecation doesn't mention using services just a component. It would probably make sense to use a service too.

**Comment by mixonic** [comment]
@ErikCH or anyone else who wants to champion this, please ping me I'm happy to review and help you move forward :-D

**Comment by ErikCH** [comment]
@mixonic Great! Let me know what I should do going forward? Is it just the change to the deprecation guide? What needs to be updated for the rest of the deprecation?

**Comment by mixonic** [comment]
@ErikCH the steps are going to be something like:

* [ ] Add the deprecation of `{{render 'foo'}}` in a PR.
  * [ ] This will likely be a new plugin ala the one for `{{render 'foo' someModel}}`: https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/deprecate-render-model.js Note that the old deprecation should be unaffected by the addition of the new one.
  * [ ] Add tests for the deprecation of `{{render 'foo'}}`.
  * [ ] Update any tests that still use `{{render 'foo'}}` to test unrelated behavior to use modern idioms (components).
  * [ ] Audit the codebase for any remaining usage, for example in documentation, and refactor that to modern idioms.
* [ ] Open a deprecation guide PR on the [website](https://github.com/emberjs/website).
* [ ] Audit the [guides](https://github.com/emberjs/guides) for any remaining usage of `{{render` that can be removed.

**Comment by mixonic** [comment]
It is done, in 2.11 beta shortly.
