### ISSUE TITLE
Missing documentation for Transition objects

### ISSUE THREAD

**Issue by kanongil** [emberjs/ember.js#13592]
`Transition` objects are used in various places as return values and arguments, and discussed in the guides using various method calls. However, this is not part of the compiled documentation.

I can only find some embedded documentation in an external project [here](https://github.com/tildeio/router.js/blob/master/lib/router/transition.js), which I assume applies?

**Comment by rwjblue** [comment]
Was fixed in https://github.com/emberjs/ember.js/pull/12211, which will be included in the 2.6.0 docs when they are published.
