### ISSUE TITLE
Maybe add an assertion if you use a built-in as as block param name

### ISSUE THREAD

**Issue by machty** [emberjs/ember.js#13595]
`{{#each logs as |log|}} {{log}} {{/each}}` won't print anything because `log` is a built-in and can't be used as a block param. `log` is admittedly the worst case where this could bite someone (no one's gonna make a block param called `if`) but might still be worth it to add an assert that don't use a built-in name as a block param name.

https://ember-twiddle.com/51195636eea97921cadbddf38ce961ba?openFiles=templates.application.hbs%2C

**Comment by rwjblue** [comment]
@chancancode - Any ideas where we might hook in on the Glimmer side to provide this warning?  I'm not sure where to get access to the specific block param args...

**Comment by bekzod** [comment]
@rwjblue this works in canary, I think it can be closed
