### ISSUE TITLE
_array_ queryParam converted to _string_ after transitionTo

### ISSUE THREAD

**Issue by arturkot** [emberjs/ember.js#13591]
Hi,

a demo: https://ember-twiddle.com/650b6fb3657bf037a40170f3b1e74b84

Steps to reproduce (here's a quick video: https://v.usetapes.com/V0vlZepqbw):

1. Use "My Route!" link.
2. Click either "Set array" or "Set all" to update the `array` parameter.
3. The `array` parameter is now a string (and should remain an array).

Notes:
* "my-route" route uses application controller `controllerName: 'application'` to access query parameters from the parent route/controller.
* When you comment out `this.transitionTo('application')` setting parameters will work as expected (`array` parameter remains an array).
* "reset params" sets an empty array and that doesn't trigger the error.
* I've noticed the error after updating from Ember **2.4.1** to **2.4.5**. I can confirm that *2.4.1* doesn't have this error.

Thanks,

Artur

**Comment by vomchik** [comment]
Ember 2.5.1 has the some problem.

**Comment by lolmaus** [comment]
This issue has been mentioned here: https://github.com/emberjs/ember.js/pull/13273#issuecomment-214739521

**Comment by acorncom** [comment]
@arturkot Further background can be found https://github.com/emberjs/ember.js/pull/13600  Your issue should be resolved with 2.4.6 (as the changes that were the issue were reverted).

For Ember 2.5+ I'm unclear on whether this issue continues to be a problem or not in the latest versions.

I'll close this issue for now

**Comment by arturkot** [comment]
Big thanks for looking into that!

**Comment by lolmaus** [comment]
@acorncom 

> For Ember 2.5+ I'm unclear on whether this issue continues to be a problem or not in the latest versions.

Quoting @Sinled from https://github.com/emberjs/ember.js/pull/13273#issuecomment-225882046 :

> 2.4.6 fixed my [problem](https://github.com/emberjs/ember.js/pull/13273#issuecomment-214739521) with query params serialisation, but it still present in 2.6.0

**Comment by lan0** [comment]
Can this issue be reopened?

The behavior of the twiddle in the OP differs slightly in 2.6.2 and 2.7.0:
While in 2.6.2 the array got converted to a string immediately after clicking on `Set array`, in 2.7.0 the initial `Set array` works fine but a subsequent click on `Set number` transforms the array into a string.
