### ISSUE TITLE
Does is-active-route or equivalent helper exist?

### ISSUE THREAD

**Issue by thedig** [emberjs/ember.js#13611]
Hi there,

Curious if there's already a helper in the works to check if something is the current route name?  Currently using the following solution local to my application:

```js
import Ember from 'ember';

const { inject } = Ember;

export default Ember.Helper.extend({
  routing: inject.service('-routing'),
  onRouteChange: Ember.observer('routing.currentRouteName', function() {
    this.recompute();
  }),
  compute([ routeName ]) {
    return this.get('routing.currentRouteName') === routeName;
  }
});
```

CC @taras 

Best,
.dig

**Comment by mixonic** [comment]
@thedig there is a proposal here to formalize the service: https://github.com/emberjs/rfcs/pull/95 but there is no public API proposed for a helper at this time.

Closing as this doesn't appear to be a bug- if there are comments regarding the addition of a new feature please see the RFCs repo! https://github.com/emberjs/rfcs

Thanks @thedig
