### ISSUE TITLE
[Beta regression] `this.elementId` is null in tagless component

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#13627]
In 2.6, `this.elementId` called from within a tagless component returned something like `ember123`.
In 2.7 the same call in 2.7.0-beta.0 returns `null`.

Intended or a regression?

**Comment by rwjblue** [comment]
Well, it seems unintentional, but the new behavior does seem logical. Why would something without an element have an elementId? Why do extra work to calculate an elementId when it isn't going to be used?

Is this a large issue for your addons?

**Comment by cibernox** [comment]
Not a big deal, it is an easy fix. 
I just needed a unique identifier from which derive ids for the trigger and the content so I can relate them (since the content may be rendered in the root of the page, A11y requires some hint). 
I could just as easy generate an autoincremental number myself, but since I had `this.elementId` I was using it, assuming that it was an identifier for the component, regardless of if the component had a DOM element or not.

I will stop relying on it, but I wanted to raise this change.

**Comment by rwjblue** [comment]
Thank you for reporting. 

I will check with others to see if we should bring it back or try and do a deprecation. I'm unsure how big of an issue it is for others though...

**Comment by rwjblue** [comment]
Thank you again for reporting the issue. If we have significant reports of this in future releases we can revisit, but for now I'm going to close...

**Comment by jmacqueen** [comment]
Add me to list as missing this ability. Building in accessibility relationships in tagless components was much easier with it!

**Comment by bigtone1284** [comment]
was this fixed?

**Comment by alias-mac** [comment]
Just for the record (for future reference), we can use `Ember.guidFor(this)` to generate the id and use it in the template.
