### ISSUE TITLE
Inconsistent DOM between fastboot and in-browser rendering

### ISSUE THREAD

**Issue by ef4** [emberjs/ember.js#13635]
This HTML:

``` hbs
<p><div></div></p>
```

is interpreted differently by Ember and browsers. Ember always requires balanced tags, so it doesn't implement tag omission, so the template results in a single paragraph containing a single div.

But browsers will generate DOM like:

``` hbs
    <p></p><div></div><p></p>
```

because of [tag omission](https://html.spec.whatwg.org/#the-p-element):

> A p element's end tag can be omitted if the p element is immediately followed by an address, article, aside, blockquote, details, div, dl, fieldset, figcaption, figure, footer, form, h1, h2, h3, h4, h5, h6, header, hgroup, hr, main, menu, nav, ol, p, pre, section, table, or ul element...

This hasn't been a problem in the past, because Ember templates were only interpreted by Ember and we were free to be stricter than browsers. But fastboot adds an additional requirement: the fastboot output needs to maintain its meaning even under browser's looser rules.

**Comment by locks** [comment]
@ef4 is this still true?

**Comment by Serabe** [comment]
![2017-07-13 at 19 44](https://user-images.githubusercontent.com/36221/28179896-b2bb73ce-6803-11e7-91fa-ed37a5f687f8.png)

Seems so. Should this be moved to fastboot repo?

**Comment by ef4** [comment]
IMO it's a core glimmer question: should glimmer implement tag omission so that it's more compliant with browser HTML handling?

**Comment by pixelhandler** [comment]
@ef4 @locks perhpaps this can be discussed and then reopened if needed, closing for now since it's been inactive for some time.
