### ISSUE TITLE
findWithAssert() and find() both have undocumented params

### ISSUE THREAD

**Issue by eglenfield** [emberjs/ember.js#13639]
*Link to PR opened for docs*:  #13641 (This does not cover changing the link to the methods themselves)

Looking at http://emberjs.com/api/classes/Ember.Test.html#method_findWithAssert and noticed that the `context` param isn't included in the docs, and it's not included in the `find()` documentation either. Also the link to the code itself is wrong, it takes you here: https://github.com/emberjs/ember.js/blob/v2.6.0/packages/ember-testing/lib/helpers.js#L414
when it should be here: https://github.com/emberjs/ember.js/blob/v2.6.0/packages/ember-testing/lib/helpers.js#L282

**Comment by pixelhandler** [comment]
@eglenfield closing as #14107 fixes this.
