### ISSUE TITLE
Using `deprecatingAlias` triggers additional deprecation warnings when used as instructed

### ISSUE THREAD

**Issue by luketheobscure** [emberjs/ember.js#13630]
Using `deprecatingAlias` [as instructed by the docs](http://emberjs.com/api/classes/Ember.computed.html#method_deprecatingAlias) triggers additional deprecation warnings. In order to use it without triggering additional deprecation warnings, you have to pass in an object with an id and an until property:

`oldAndBusted: computed.deprecatingAlias('newHotness', { id: 'foo', until: '1.42' });`

Documentation should be updated to express that.

**Comment by rwjblue** [comment]
Would love a PR updating.
