### ISSUE TITLE
Application.hbs template not generated with ember-cli 2.6.0

### ISSUE THREAD

**Issue by mscarchilli** [emberjs/ember.js#13646]
When using ember-cli to create a new project, it is not generating an application.hbs file anywhere. I have been trying to follow the tutorial on the site, and it doesn't say the user should generated this file. I generated new projects multiple times and the application.hbs file is always missing. No errors during the build. I have tried the build both as non-admin and as admin in the cli.

Command ran:
`ember new sitename`

I made sure everything was up to date via: https://guides.emberjs.com/v2.6.0/tutorial/ember-cli/#toc_upgrading-ember

Tutorial page where it says the file is generated: https://guides.emberjs.com/v2.6.0/tutorial/routes-and-templates/#toc_adding-a-banner-with-navigation

**Specs:**
ember-cli: 2.6.0
bower: 1.7.9
node: 6.2.1
npm: 3.9.3
os: Win7 win32 x64

**Comment by pixelhandler** [comment]
@mscarchilli perhaps this should be raised as a question in the slack chat room #-ember-cli

**Comment by pixelhandler** [comment]
@mscarchilli See the diff for ember-cli 2.6.0 at https://github.com/ember-cli/ember-new-output/compare/v2.5.1...v2.6.0 the application template was removed, perhaps in favor of using `ember-welcome-page`

**Comment by mscarchilli** [comment]
Will definitely check that out. Thank you. 

They might want to update their webpage docs to let people know so they don't sit staring at the computer scratching their head like a monkey... like I was doing. :)

**Comment by acorncom** [comment]
@mscarchilli We realized docs were out of date in that one area in the last few days.  Would you mind sending in a PR to help fix it?  We don't want folks stuck.  We'll be updating the tutorial here later today, so if you've got time, your fix should go in in short order ...

**Comment by acorncom** [comment]
The short fix is to do a `ember g template application` and you'll then have the file you need ...
