### ISSUE TITLE
EmberJS does not work with jQuery 3.0

### ISSUE THREAD

**Issue by cbou** [emberjs/ember.js#13661]
`jQuery.event.fixHooks` was removed in jQuery 3.0

https://jquery.com/upgrade-guide/3.0/#breaking-change-jquery-event-props-and-jquery-event-fixhooks-removed

https://github.com/emberjs/ember.js/blob/f6bad3dad476f952d79c3386bf9f7be12b075380/packages/ember-views/lib/system/jquery.js#L23

**Comment by SubashRamaiah** [comment]
HI.. I just upgraded to JQuery 3, jQuery.event.fixHooks was removed. I am using Ember js.. How to fix this..? or I need to upgrade Ember version? If yes, What is the exact version
