### ISSUE TITLE
Ember 2.6.0 render into outlet has erratic behavior after disconnectOutlet  is used. Ember 2.5 works

### ISSUE THREAD

**Issue by bterkuile** [emberjs/ember.js#13677]
I did not trace the source of the error, but created a demo application at:
http://jsbin.com/gopaqu/3/edit?html,js,output
isolating the issue.

Steps to reproduce:
1. click on the button 'abc'
2. click on the button 'Close'
3. click on the button 'def'

Expected result: The content of the modals/def view should be rendered into the modal outlet
Actual result: The render action does not show anything.

The jsbin is created/tested on an Ubuntu 16.04 machine with both Chromium and Firefox browsers

**Comment by krisselden** [comment]
@bterkuile thanks for the report, this was fixed in #13672 and will be in the next 2.6.x point release
