### ISSUE TITLE
Broken url used inline docs application.js 

### ISSUE THREAD

**Issue by mrosata** [emberjs/ember.js#13678]
The link to http://emberjs.com/guides/understanding-ember/the-view-layer/#toc_event-delegation is broken. It can be seen using the github link or documentation link below:

[Location in application.js - https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/application.js#L149](https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/application.js#L149)

[Broken link found here in API docs: http://emberjs.com/api/classes/Ember.Application.html](
http://emberjs.com/api/classes/Ember.Application.html)

The line to look for in the documentation is "To learn more about the advantages of event delegation and the Ember view layer, and a list of the event listeners that are setup by default, visit the Ember View Layer guide."

**Comment by pixelhandler** [comment]
The closest page I can think of is https://guides.emberjs.com/v2.6.0/components/handling-events/#toc_event-names However we may need to change that paragraph as `Ember.View` is deprecated. Perhaps we can use:

> To learn more about the events Ember components use, see [components/handling-events](https://guides.emberjs.com/v2.6.0/components/handling-events/#toc_event-names).

**Comment by mrosata** [comment]
Closing the issue because it has been adjusted.
