### ISSUE TITLE
Ember.Date.parse doesn't work with time zone designators without double colons

### ISSUE THREAD

**Issue by buschtoens** [emberjs/ember.js#13675]
Cross referencing this issue: https://github.com/csnover/js-iso8601/issues/27

**Comment by Serabe** [comment]
Hello:

Thank you for reporting this. `Ember.Date` is in [emberjs/data](github.com/emberjs/data). Can you please move the issue to that repo, please?

Thank you!

**Comment by buschtoens** [comment]
The issue has been closed upstream anyway, as it was a dupe of https://github.com/csnover/js-iso8601/issues/25.
