### ISSUE TITLE
Integration Tests -- this.set() no longer seems to be connected to the component being rendered

### ISSUE THREAD

**Issue by dustyjewett** [emberjs/ember.js#13673]
NOTE: This MAY be a duplicate of: #13557. 

When using this.set() in integration tests, the component does not seem to receive the bindings. (or, if it does get them, it gets them async, and out-of-band)

```
  this.set('title', "New Title")
  this.render(`{{test-thing title=title}}`);
  assert.equal(this.$('.theField').text(), 'New Title'); // false
```

jsbin: http://jsbin.com/cafujec/1/edit?html,js,output

This works in current/beta.

**Comment by rwjblue** [comment]
I haven't released an updated ember-qunit build (for JSBin usage) since ember-test-helpers@0.5.26 came out. But ember-cli apps should automatically get the latest version.

**Comment by dustyjewett** [comment]
Thanks, That does fix it.
