### ISSUE TITLE
Ember DEPRECATION warnings

### ISSUE THREAD

**Issue by chewedon** [emberjs/ember.js#13676]
I am following the ember guide, I have installed ember-cli@2.6 via:

    npm install -g ember-cli@2.6

I then typed:

    ember --version

and I get a bunch of yellow warnings:

```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` ember-data
    at Function.Addon.lookup (/Users/chewedon/Ember/Camp/node_modules/ember-cli/lib/models/addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` ember-cli-dependency-checker
    at Function.Addon.lookup (/Users/chewedon/Ember/Camp/node_modules/ember-cli/lib/models/addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` ember-cli-jshint
    at Function.Addon.lookup (/Users/chewedon/Ember/Camp/node_modules/ember-cli/lib/models/addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` Ember CLI QUnit
    at Function.Addon.lookup (/Users/chewedon/Ember/Camp/node_modules/ember-cli/lib/models/addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` release
    at /Users/chewedon/Ember/Camp/node_modules/ember-cli/lib/models/project.js:404:38
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.6.1
node: 5.4.0
os: darwin x64
```

I tried Googling but haven't seen anything resembling this.

Ember continues to work fine though, just a bit annoying seeing the yellow message.

Any ideas?

**Comment by Serabe** [comment]
This is coming from [ember-cli/core-object](https://github.com/ember-cli/core-object/blob/master/core-object.js#L53-L57). It seems an issue in ember-cli. Can you please check if it still happening in master and, if so, open an issue there?

**Comment by chewedon** [comment]
How do I check what version of core-object I am using ?

**Comment by chewedon** [comment]
I don't know if this is the right command but:

```bash
npm list core-object
super-rentals@0.0.0 /Users/chewedon/Ember/super-rentals
└─┬ ember-cli@2.6.1
  ├── core-object@2.0.3 
  └─┬ ember-try@0.2.2
    └── core-object@1.1.0 
```

**Comment by deanmraz** [comment]
@Serabe @chewedon tested master with npm link and looks good. 

```
git clone https://github.com/ember-cli/ember-cli.git
npm link ember-cli 
```

Running the version command
```
ember --version 
ember-cli: 2.7.0-beta.2
node: 5.11.0
os: darwin x64
```

**Comment by chewedon** [comment]
@deanmraz try going `ember --version` inside an newly generated ember project folder.

I notice if I typed `ember --version` outside of a project folder, the warnings don't appear.

**Comment by Ridermansb** [comment]
Same problem...
```
λ ember s
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` ember-cli-dependency-checker
    at Function.Addon.lookup (C:\Users\rider\Projects\tmp\emberTest\tes1\node_modules\ember-cli\lib\models\addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` ember-cli-jshint
    at Function.Addon.lookup (C:\Users\rider\Projects\tmp\emberTest\tes1\node_modules\ember-cli\lib\models\addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` Ember CLI QUnit
    at Function.Addon.lookup (C:\Users\rider\Projects\tmp\emberTest\tes1\node_modules\ember-cli\lib\models\addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` release
    at C:\Users\rider\Projects\tmp\emberTest\tes1\node_modules\ember-cli\lib\models\project.js:404:38
```

```
ember-cli: 2.6.1
node: 5.10.1
os: win32 x64
```

**Comment by stefanpenner** [comment]
These are deprecations, that must be address in the add-ons provided. This isn't an ember issue, please upgrade your dependencies (as many of them have updated), and in-cases where you discover an add-on has yet to be updated please submit an issue or pull request to that addon.

**Comment by choiway** [comment]
@stefanpenner I'm running into the same problem and I'm a little confused by your solution. Even though this it the first time I've installed Ember I have to go through and upgrade dependencies that are part of Ember?

**Comment by thomblake** [comment]
@choiway You're using add-ons that have some deprecated code in them.  They probably haven't been fixed upstream yet. This is not an Ember issue, but it might be an [ember-cli](https://github.com/ember-cli/ember-cli) issue.

**Comment by choiway** [comment]
@thomblake So just upgrade each add-on where the deprecated warning shows up?

**Comment by thomblake** [comment]
@choiway Yeah that should work except that I suspect some of those add-ons haven't fixed it themselves yet.  So the solution might be to file issues against those add-ons if they haven't released a newer version that fixes it.

**Comment by choiway** [comment]
@thomblake Alright, thanks!

**Comment by baylf2000** [comment]
I really feel the need to say that the answers provided here are pretty shitty, and are definitely the very best way to turn any new users away from Ember.

If a new user hops onto the official *EMBER* website, and follows the official *EMBER* tutorial telling me to run "npm install -g ember-cli@2.6" and then "ember new super-rentals" and then immediately gets a bunch of bright yellow warnings, then comes here for some advice and is essentially told to get lost because it's not an Ember problem, that seriously sucks.

At the very least someone could write an explanation here about what the issue is and whether or not it's important, because to new users it's bright yellow and scary.

Thanks guys.

**Comment by nathanhammond** [comment]
Hey @baylf2000: please remember that everybody involved on this is a person, the [decisions that we make](https://github.com/ember-cli/core-object/pull/33) all [have tradeoffs](https://github.com/ember-cli/ember-cli/pull/5972#issuecomment-225259799), and possibly most important, the amount of time we have to address these concerns are limited. A deprecation warning with a still-fully-functioning application is low on our priority list. Managing to move the entire Ember Addon ecosystem from an ancient version of core-object to the most recent is pretty high on our priority list.

Every release is a risk and we take that seriously. We're also far more likely to respond positively with a more measured approach from you. Please take a moment to review the [Ember Community Guidelines](http://emberjs.com/guidelines/).

**Comment by baylf2000** [comment]
@nathanhammond thanks for your response.

I don't think the bug itself is the issue, nor is my response, nor do I forget that people are involved, although I think perhaps remembering that Ember users are also people is equally as important.

The issue is that a relatively inexperienced user came to the official Ember community to ask a very sensible, justified and polite question about a simple problem that absolutely ought to be owned by the Ember community. Yet he was immediately met with a truly awful, dismissive "not our problem, go away" response.

Responses like that are certainly not a problem limited to the Ember community or its developers, but it's one of the worst examples I've seen for a while.

My comments were simply an attempt to remind people how damaging that kind of treatment of your users can be. It's easy to forget that this thread is now here forever, and it's likely that very many people will have the same issue as the OP, do a search like I did, and end up reading this awful thread where Ember devs seem to treat their users with disdain. Given that this will certainly be their first experience of Ember, they'll probably go and find another platform.

On the other hand, a polite, clear and simple response from a dev or community member explaining the issue and offering some clear advice would have the opposite effect.

The Ember community has obviously gone to a huge amount of effort to write some truly excellent tutorials which are clearly targeted towards inexperienced users. All that good work can so easily be thrown away by something as simple as the responses in this thread.

Anyway, just my thoughts.

**Comment by carols10cents** [comment]
It looks like these should all be fixed as of a few hours ago, so updating to at least these versions of these addons should get rid of the deprecation warnings: 

- ember-data v2.6.1 (contains [this commit](https://github.com/emberjs/data/commit/0d8686ebe756539e10e7be23680542f3c069c8a4))
- ember-cli-dependency-checker v1.3.0 (contains [this commit](https://github.com/quaertym/ember-cli-dependency-checker/commit/6c05a3316fde10b502baec5555502fd7b3212adf)
- ember-cli-jshint v1.0.4 (contains [this commit](https://github.com/ember-cli/ember-cli-jshint/commit/867edefdc9b24f661d359635ab5ec80438df4077))
- ember-cli-qunit v2.0.2 (contains [this commit](https://github.com/ember-cli/ember-cli-qunit/commit/45b80f6dc4745d2e0795196a642c166f4cf3d77f))
- release v0.2.9 (contains [this commit](https://github.com/lytics/ember-cli-release/commit/7a37f757e3e2fd2b82a786caf357e033ef3a27e8))

**Comment by baylf2000** [comment]
Thanks so much for that @carols10cents 

Doing an install on a fresh machine using "npm install -g ember-cli" and then "ember new testApp" as per the tutorial does install version 2.6.1, but that in itself doesn't correct the depreciation warnings, as several of the installed addons you mention are still older versions. Here are the deps from the package.json installed by ember-cli 2.6.1 in a new project:

`"devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "^2.0.1",
    "ember-cli": "2.6.1",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-qunit": "^1.4.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.6.0",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-resolver": "^2.0.3",
    "ember-welcome-page": "^1.0.1",
    "loader.js": "^4.0.1"
  }
`

The warnings seem to be coming from "ember-cli-release", as when that alone is changed to from `"0.2.8"` to `"0.2.9"` in package.json and then `npm install` is run from the project directory, the warnings disappear.

Hopefully this will help someone else having the same issues.

Lachlan.

**Comment by chewedon** [comment]
It certainly helped me :D

I ran `npm install` for each of the items mentioned in carols10cents and then changed ember-cli-release to `0.2.9` as suggested by @baylf2000. 

No more deprecation warnings for me.

Thank you all for your patience and understanding.

**Comment by jrohatiner** [comment]
Thank You!!! just please note that newest version ember cli is 2.7.0. So following this to set-up or update works perfectly just make sure to check your versions folks.

**Comment by Amerr** [comment]
@nathanhammond Can you explain the reason for warning . what is tradeoff and how these changes gives advantage in new versions . its  , by changing to `this._super(...arguments)` to `this._super.apply(this, ...arguments)`.
