### ISSUE TITLE
First parameter in Ember.inject.service() is optional?

### ISSUE THREAD

**Issue by mkay581** [emberjs/ember.js#13689]
[Your documentation](http://emberjs.com/api/classes/Ember.inject.html#method_service) says that the first parameter (`name`) is optional for the `Ember.inject.service`.

My guess of what's happening here is that Ember is detecting and storing the property via `set` descriptor behind the scenes and using this stored variable when the actual method is called? (I could be wrong here btw).

Either way, I think this parameter should be re-thought to be made required. For the future sanity for both the Ember team and the javascript community :)

This has lead to hard to find bugs within teams I've been on, where an Engineer A didn't specify this property, but Engineer B goes behind them and changes the property name entirely (via search and replace or otherwise) and boom... silent, hard-to-find bugs. Or if Engineer B would change the actual identifier of the service entirely, inadvertently thinking that they can do a search and replace in every file, but end up missing a few that don't pass the parameter. heh

Outside of the above scenarios, I'm just curious here...

What would you do when Ember wants to add an additional parameter in the future that is of string type, like this optional `name` first parameter? Seems like you'd have to add even more logic that makes sure that the string intended to the be "second" parameter is not actually used as the optional first parameter. Or check whether the first parameter IS actually intended to be a first parameter!?

**Comment by Serabe** [comment]
Thank you for reporting this. This is not a bug but a feature request and, as stated in the [contributing document](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature) it needs to be submit in [emberjs/rfcs](https://github.com/emberjs/rfcs/).

As for the problems you suggest the solution is quite easy: force your team to add the argument. I only use `Ember.inject.service()` for `store` and `session`. Adding a rule to jscs to check automatically for that should not be complicated.

About what would happen if Ember were to add a second string parameter, the solution would be much simpler than that: require the first one if you need to use the second.

Thank you for your comments!
