### ISSUE TITLE
How to set empty tagName for application route without views support?

### ISSUE THREAD

**Issue by dmagunov** [emberjs/ember.js#13690]
As we know Ember generate div elements for each route (<div id="ember1" class="ember-view"/>), but I need for some routes that Ember doesn't generate this elements, so how can I do it in new Ember version without ember-legacy-view support?

**Comment by rwjblue** [comment]
Firstly, Ember does not create a div for every route. It only creates one for the top level (application route). 

As of 2.6.0 there is no (non-hacks) mechanism to remove the application routes surrounding element.

**Comment by dmagunov** [comment]
OK, so what is the hack way?

**Comment by rwjblue** [comment]
In 2.6.0, you could put a component at `app/views/application.js` but that will not work in Ember 2.7 (and its horrible) so it isn't very useful...

**Comment by rwjblue** [comment]
Features are generally discussed in the https://github.com/emberjs/rfcs/ repository. You can create an issue there for feature requests or a pull request to propose a new feature.  I'm closing this issue (this is an intentional change in the framework), but please follow up with an RFC issue/PR if you are interested in taking this further.

**Comment by ohnnyj** [comment]
Sorry to bring this back from the grave. Just so I understand correctly, there is no way around our DOM looking something like:

```html
<body class="ember-application">
  <div id="ember297" class="ember-view">
    <my-application-view></my-application-view>
  </div>
</body>
```

no way to get?

```html
<body class="ember-application">
    <my-application-view></my-application-view>
</body>
```

If so, what exactly is the wrapping div for? Why is it being added?

**Comment by rwjblue** [comment]
Confirm.
