### ISSUE TITLE
DEPRECATION Warning suddenly come out...

### ISSUE THREAD

**Issue by cheng-jk** [emberjs/ember.js#13706]
> DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-dependency-checker`
>     at Function.Addon.lookup (/home/chengjk/Documents/projects/atlantis2u.com/atlantis-emberjs/node_modules/ember-cli/lib/models/addon.js:896:27)
> DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `release`
>     at /home/chengjk/Documents/projects/atlantis2u.com/atlantis-emberjs/node_modules/ember-cli/lib/models/project.js:404:38

my current node is 4.4.5 and ember-cli is version 2.6.1... everything has been ok since i start ember-cli about a week ago... but today this warning start to come out... no other plugins install manually, just npm -g install ember-cli, and daily run npm update... i am newbie...

**Comment by rwjblue** [comment]
I'm going to close this issue as it isn't a bug in the framework itself.  If anything it is an issue with ember-cli and the addons triggering the deprecation. These deprecations are being issued by addons during the ember-cli build process. Both ember-cli-release and ember-cli-dependency-checker have been updated, but need to be released (ping @slindberg and @quaertym).

**Comment by quaertym** [comment]
`ember-cli-dependency-checker` [1.3.0](https://github.com/quaertym/ember-cli-dependency-checker/releases/tag/v1.3.0) is released.

**Comment by rwjblue** [comment]
@quaertym - Thank you!
