### ISSUE TITLE
beforeModel hook called while typing in url location bar

### ISSUE THREAD

**Issue by kbullaughey** [emberjs/ember.js#13727]
I encountered a bizarre problem (only in Google Chrome) whereby while I was typing in the name of a route into the browser's URL location bar, the tab completion would fill in the rest, and before I pressed enter the `beforeModel` hook on that route would get called. 

The only reason I noticed this was because it was doing an ajax call to my backend and the call would show up in the log. If I put a breakpoint in the `beforeModel` hook or a `console.log` statement, it would neither break or print the message. Nonetheless, the ajax call was proof the `beforeModel` hook is getting called.

I can reproduce this problem on a clean app produced with `ember new test-app` and then only adding the following routes:

    Router.map(function() {
      this.route('sign-in');
      this.route('dashboard');
    });

Each route is defined symmetrically, with only the words `dashboard` changed to `sign-in` in the other route. The ajax call is just so I have evidence of this behavior (my backend happens to have an endpoint called `/api/error_sink` that I am abusing for this purpose).

    export default Ember.Route.extend({
      beforeModel: function(transition) {
        this._super.apply(this, arguments);
        console.log('dashboard beforeModel');
        Ember.$.ajax({
          type: 'POST',
          url: "/api/error_sink",
          success: function(result) {
            console.log('posted error');
          },
          data: { route: 'dashboard' },
        });
      },
    });

This strikes me as very bizarre. I can reproduce the behavior both in Chrome 51 and 53 on OS X (haven't tried any other OS). It's doubly weird (and hard to debug) because breakpoints and `console.log` statements don't work. 

I tried to figure out how `beforeModel` was getting called by posting a stack trace to my backend, but this wasn't much help given how asynchronous everything in Ember is (I would just see backburner stuff).

**Comment by rwjblue** [comment]
I'm guessing that chrome is trying to prefetch the page after some sort of debounce delay while typing in the location bar.

**Comment by kbullaughey** [comment]
Hm...so something I need to live with? 

That might explain why I can't put in a breakpoint. Maybe it's happening in some other thread. 

It's kind of a pain because in this particular case it messes up my app because the prefetch affects my session data, which is shared across threads via localstorage. What's happening is the user is accessing the app without being authenticated, and then when a route is requested that requires authentication, the person is authenticated. So the person ends up getting authenticated while typing into the location bar.

Maybe there's something fundamentally wrong with how I'm managing authentication and session state.

**Comment by kbullaughey** [comment]
I'll go ahead and close this. I appreciate the quick reply. Cheers.
