### ISSUE TITLE
getOwner missing from API Docs?

### ISSUE THREAD

**Issue by justinaray** [emberjs/ember.js#13734]
Please forgive the issue if I'm missing it or it's documented elsewhere, but I don't see the `getOwner` or `setOwner` methods in the `Ember` module API docs.

I obviously know about them from the blog posts and guides, but was surprised when I checked the API.

**Comment by rwjblue** [comment]
Hmm. Documentation was written for it ([here](https://github.com/emberjs/ember.js/blob/master/packages/container/lib/owner.js#L10-L48)), I am not sure why it isn't showing up though.

**Comment by justinaray** [comment]
Maybe the api generation needs a `@since` tag?  Or the order is important.  Only differences I can see with other methods that add to the `Ember` module.

https://github.com/emberjs/ember.js/blob/v2.6.0/packages/ember-metal/lib/utils.js#L415-L428

**Comment by rwjblue** [comment]
Since would be good to add, but it shouldn't be required. My guess is that it is either order dependent or that we aren't included docs from the container package.

**Comment by justinaray** [comment]
Yeah, just noticed that `@since` isn't on many of the other methods (e.g. `$`).  Agree about the other two likely causes.
