### ISSUE TITLE
input type="number" + one-way binding + constraining data appears buggy

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember.js#13747]
Using the new one-way binding of native inputs, I'm trying to stop the data at "999". It appears to constrain it once and reset it back to "999", but then the binding is lost and it continues unbounded.

``` hbs
<input type="number" value={{count}} oninput={{action "update" value="target.value"}} />
```

``` js
actions: {
  update(value) {
    if (value > 999) {
      this.set('count', 999);
    } else { 
      this.set('count', value);
    }
  }
}
```

twiddle that demonstrates issue: https://ember-twiddle.com/e4801208572aec5b0548553293a83afd

re here:
http://stackoverflow.com/questions/38003564/ember-js-native-input-type-number-binding-broke-when-constraining-value

**Comment by kellyselden** [comment]
I should add that if I change `value="target"` and then
```js
this.set('count', 999);
$(target).val(target.value);
```

it works as desired.

**Comment by vvscode** [comment]
@kellyselden  it's not ember-way. You just used jquery api ( I mean your workaround )

**Comment by kellyselden** [comment]
@vvscode correct, the workaround is not desired.

**Comment by rwjblue** [comment]
It isn't triggering a rerender because count is not changing value (and the underlying rendering system thinks it has not changed). The easiest work around at the moment is to always set to the user provided value, and then if needed schedule a set back to 999 in the afterRender queue. 

This topic came up in slack yesterday, and I made a demo Twiddle showing what I mean: https://gist.github.com/rwjblue/48da9c6a9ca59519e8b6ac229e476b31

This seems like a less than ideal situation, and I will keep noodling this to figure out a better solution with the glimmer rewrite.

**Comment by JackCA** [comment]
We've run into this at Heroku as well and have been using https://github.com/DockYard/ember-one-way-controls in place of the raw input tag.

**Comment by Serabe** [comment]
Seems fix now. @kellyselden can you confirm please? Thank you!

**Comment by kellyselden** [comment]
Nope, the problem still exists when I update that twiddle to 2.14.

**Comment by pixelhandler** [comment]
@JackCA @kellyselden @rwjblue @vvscode is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by kellyselden** [comment]
If you switch that twiddle to ember alpha, the issue still remains.

**Comment by pixelhandler** [comment]
@kellyselden I updated the twiddle with the current release, I see the issue.

How about making a component with events to mask input?

```javascript
  keyPress(event) {
    return event.key.match(/^[0-9]$/) !== null && event.target.value.length < 3;
  },
  input(event) {
    // for paste, truncate
    set(this, 'days', event.target.value.length > 4 ? event.target.value.slice(0, 4) : event.target.value);
  },
```

**Comment by locks** [comment]
Closing as no longer relevant. The framework has moved on to favour Glimmer components and the `{{on}}` modifier or event handling.
