### ISSUE TITLE
Prototype extensions are enumerable

### ISSUE THREAD

**Issue by EyMaddis** [emberjs/ember.js#13743]
Hi,
I noticed that native prototype extensions are enumerable, which means that they are listed in `for(var key in obj)` statements.
This is a problem since a lot of third party libraries use these statements (even though they mostly shouldn't). 
Is there a reasoning behind this not using `defineProperty` with `{ enumerable: false }` for the extensions? I would personally consider this a bug. 
And I am [not alone](https://github.com/emberjs/ember.js/issues/13509#issuecomment-219819679).

**Comment by locks** [comment]
Just want to note that this is a potential breaking change, as someone might be relying on that faulty behaviour.

**Comment by EyMaddis** [comment]
If anybody wants to work around the issue, just add this when the application loads (e.g. `app.js`)

```js
avoidEnumerableNativeExtensions(Array.prototype);
avoidEnumerableNativeExtensions(Function.prototype);
avoidEnumerableNativeExtensions(String.prototype);

function avoidEnumerableNativeExtensions(proto) {
    Object.keys(proto) // already gets all enumerables, no need to filter
        .map(key => {
            return { key, descriptor: Object.getOwnPropertyDescriptor(proto, key) };
        })
        .forEach(obj => {
            obj.descriptor.enumerable = false;
            Object.defineProperty(proto, obj.key, obj.descriptor);
        });
}
```

**Comment by bekzod** [comment]
this can be closed, it is no longer the case all extensions are non enum already https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/ext/function.js#L78
