### ISSUE TITLE
An attribute binding to an AliasedProperty doesn't propagate changes

### ISSUE THREAD

**Issue by mmpestorich** [emberjs/ember.js#13748]
A mutable binding to a component attribute that is also an aliased property on the component itself fails to propagate changes to the bound property.

``` js
App.XAliasComponent = Ember.Component.extend({
    value: null,
    alias: Ember.computed.alias('value'),
    click: function () { this.set('value', 'Goodbye'); }
});
```

``` hbs
<!-- `model.text` starts out as 'Hello' -->
{{x-alias alias=(mut model.text)}}
<!-- clicking on the component should set `model.text` to 'Goodbye' however it remains 'Hello' -->
```

Here are a couple jsbins that further illustrate the issue:
1. http://jsbin.com/zonibep/edit?html,js,output
2. http://jsbin.com/lufubin/edit?html,js,output

This happens because `AliasedProperty.set` doesn't trigger `PROPERTY_DID_CHANGE` for the alias itself (`alias` in the example above). The `AttrsProxyMixin` uses `PROPERTY_DID_CHANGE` to propagate changes from properties inside a component to properties on the outside that are bound to a component's attributes. In the example above, `PROPERTY_DID_CHANGE` is triggered for `value` but never for `alias`. Because the outside property `model.text` is bound to the attribute `alias` and not to `value`, it is never updated.

This is only a problem when a property is an `AliasedProperty`. In all other cases, `PROPERTY_DID_CHANGE` is triggered every time `set` is called on a given property.

In the example above, I would expect that if `value` is updated than any property bound to an attribute that aliases `value` should be updated as well...

**Comment by mixonic** [comment]
Hm, https://github.com/emberjs/ember.js/pull/11225 seems related but (as it was fixed) is obviously not the issue here.

**Comment by pixelhandler** [comment]
@mmpestorich @mixonic is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
