### ISSUE TITLE
Issues with PromiseProxyMixin: `Uncaught [object Object]` and `.catch is not a function`

### ISSUE THREAD

**Issue by cklimkowsky** [emberjs/ember.js#13750]
Using this example from the guides, I would expect the error to be caught as `reason` (since "/some/remote/data.json" is obviously invalid):

```
var ObjectPromiseProxy = Ember.ObjectProxy.extend(Ember.PromiseProxyMixin);

var proxy = ObjectPromiseProxy.create({
  promise: Ember.$.getJSON('/some/remote/data.json')
});

proxy.then(function(json) {
  // the json
}, function(reason) {
  // the reason why you have no json
});
```

Instead, the full error message is printed to the console, as well as `Uncaught [object Object]`. Is this documentation out of date, or is there an issue with `PromiseProxyMixin`?

Another related issue is that using the following code instead yields the error `Uncaught TypeError: proxy.then(...).catch is not a function`:
```
proxy.then(function(json) {
  // the json
}).catch(function (reason) {
  // the reason why you have no json
});
```

Guide for reference:
http://emberjs.com/api/classes/Ember.PromiseProxyMixin.html

I'm using Ember 2.6.0, and encountered the same issues at https://ember-twiddle.com/

**Comment by chadhietala** [comment]
@cklimkowsky I think this is because `Ember.$.getJSON()` does not return a ECMA specified promise, it's going to return a jquery Defered which is non-spec compliant. You should cast the jQuery deferred to a spec compliant promise.

```
const { cast } = Ember.RSVP; 
var proxy = ObjectPromiseProxy.create({
  promise: cast(Ember.$.getJSON('/some/remote/data.json'))
});
```

**Comment by mixonic** [comment]
The documentation should definitely be updated here. Perhaps simplest is to change the docs away from using a raw jQuery deferred.

However we should also confirm that the casted jQuery promise does the correct thing.

**Comment by habdelra** [comment]
Here is a twiddle that shows @chadhietala 's example works correctly in teh example above: https://ember-twiddle.com/55ae031da0bfe8647440410ce9016d67

I'll update the docs to reflect this.
