### ISSUE TITLE
Ember documentation is in mess.

### ISSUE THREAD

**Issue by RomanPerin** [emberjs/ember.js#13779]
It is very uncomfortable to work with such 'list':

![mess](https://cloud.githubusercontent.com/assets/8298800/16521129/6a30f7da-3f9d-11e6-8c57-dfb5a98e860c.png)

It will be great to see it like it was...

Thanks in advance)

**Comment by rwjblue** [comment]
Hmm, I'm not sure when this happened. 

@locks - Do you have a guess as to which change caused this?

**Comment by RomanPerin** [comment]
It is caused by next styles: 
.api ul.index-list li {
    ...
    display: inline-block;
    ...
}

**Comment by locks** [comment]
Likely related to https://github.com/emberjs/website/issues/2638. Closing this one and tracking the issue there.

**Comment by rwjblue** [comment]
This is still an issue after ensuring the latest is deployed.

**Comment by locks** [comment]
Done ;) Thanks for the tip @RomanPerin. It was a recent PR that introduced bourbon and tweaked a couple of styles, and an include was overriding the `display: block;`.

**Comment by rwjblue** [comment]
OH! I just realized this is in the emberjs/ember.js repo. I apologize for missing this earlier, issues with the website should have been opened on the emberjs/website repo instead.

**Comment by RomanPerin** [comment]
Oh, sorry for the mismatch. 
Also great thx for the quick fix)
