### ISSUE TITLE
Retrieving data from the dabase

### ISSUE THREAD

**Issue by smitakiran25** [emberjs/ember.js#13776]
Please tell me how to fetch the data from firebase 

app/template/gmap.hbs

{{#leaflet-map lat=lat lng=lng zoom=zoom}}

{{tile-layer url="http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"}}

{{#each model as |c|}}
{{#layers.marker lat=c.latitude lng=c.longitude draggable=true}}
{{/layers.marker}}
{{/each}}

{{/leaflet-map}}
app/controller/newcase.js
import Ember from 'ember';
export default Ember.Controller.extend({
actions:{
addCase: function() {
var hname = this.get('hname');
var location = this.get('location');
var latitude = this.get ('latitude');
var longitude = this.get('longitude');
var newCase = this.store.createRecord('case', {
hname : hname,
location : location,
latitude : latitude,
longitude : longitude
});
newCase.save();
this.setProperties({
hname: ' ',
location: ' ',
latitude: ' ',
longitude: ' '
});
}
}
});

app/controller/gmap.js

import Ember from 'ember';
export default Ember.Controller.extend ({
});

app/model/case.js
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
export default Model.extend({
hname : attr('string'),
location: attr('string'),
latitude: attr('number'),
longitude: attr('number')
});

app/route/newcase.js
import Ember from 'ember';
export default Ember.Route.extend({
model: function() {
return this.get('store').findAll('case');
}
});

![image](https://cloud.githubusercontent.com/assets/11611902/16477206/638212ca-3ead-11e6-9ed9-dbd7f41ed32b.png)

i want to display that location, lat and lng in map i am not getting how to display please tell me how to write code for that

**Comment by topaxi** [comment]
This isn't really the place to ask how to implement specific features. I'd suggest you ask the question on Stackoverflow: http://stackoverflow.com/questions/tagged/ember.js

Before you do that though, you might want to checkout https://www.firebase.com/docs/web/libraries/ember/quickstart.html :)

**Comment by Serabe** [comment]
Hello, @smitakiran25. I am closing this since, as @topaxi said, it is not an Emberjs bug. Please, either ask the question in StackOverflow or go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

Thank you!

**Comment by smitakiran25** [comment]
Ok Thank You :-)
