### ISSUE TITLE
no model was found for plural-model-name

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember.js#13786]
```
DEBUG: -------------------------------
DEBUG: Ember             : 2.6.1
DEBUG: Ember Data        : 2.6.1
DEBUG: jQuery            : 2.1.4
DEBUG: Ember Simple Auth : 1.1.0-beta.3
DEBUG: -------------------------------
```

![image](https://cloud.githubusercontent.com/assets/199018/16546413/73feeada-4117-11e6-9ded-1df8666a846b.png)

this only happens sometimes, but it seems like it's not trying to singularize the `events` type to `event`.

I have an `event` model, and if I refresh the page, I don't get `no model was found for 'events'`. So, not sure why this is happening only sometimes.

Here is the action that triggers the request:

```js

    refreshStripe() {
      let id = this.get('model.id');
      let url = ENV.host + '/api/orders/' + id  + '/refresh_stripe';
      let authToken = this.get('session.data.authenticated.token');

      Ember.$.ajax({
        url: url,
        type: 'GET',
        beforeSend(xhr) {
          xhr.setRequestHeader('Authorization', 'Bearer ' + authToken);
        }
      }).then(data => {
        this.get('store').push(data);
      }, error => {
        let json = JSON.parse(error.responseText);
        let errors = json.errors;
        this.get('flashMessages').alert(errors);
      });
    }
```

Any ideas?

If I find out any info that can help isolate, I'll post here.

**Comment by Serabe** [comment]
Hello, @NullVoxPopuli, this seems more like a question than an Ember.js bug. Can you please reproduce the problem in an ember-twiddle to check if it is a problem in the framework? Here you have a [twiddle](https://ember-twiddle.com/e17b37f4aa8e458546d5) using mockjax to mock ajax calls.

If what you are looking for is help with your code, please, go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

Thank you!

**Comment by NullVoxPopuli** [comment]
thanks, I'll try to re-create in a twiddle

**Comment by NullVoxPopuli** [comment]
here is a twiddle showing the error in the console: https://ember-twiddle.com/46a491da1f665904b4647f181a85aa2f

**Comment by NullVoxPopuli** [comment]
it might have something to do with polymorphic models.

**Comment by Serabe** [comment]
Seems like emberjs/data only accepts singularize `type` in `belongsTo` relationships. As of [JSONAPI Identification](http://jsonapi.org/format/#document-resource-object-identification), this might be a bug. Since this is emberjs/data related, can you please move the issue there?

Thank you!

**Comment by NullVoxPopuli** [comment]
posted here: https://github.com/emberjs/data/issues/4460

**Comment by Serabe** [comment]
Thank you!
