### ISSUE TITLE
Fix beta builds

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#13794]
Beta builds are failing on MS Edge with this error:

![MS Edge failure](https://assets.saucelabs.com/jobs/c0e622d62c3a411a8635d6e7d05f69ff/0255screenshot.png)

This might or might not be [a bug in the browser](https://github.com/emberjs/ember.js/pull/13328#issuecomment-218809667). Supposedly, another PR on master ["fixed"](https://github.com/emberjs/ember.js/pull/13328#issuecomment-220223613) the issue, so maybe we can backport the relevant stuff to beta.

**Comment by asakusuma** [comment]
Was there a code change that caused this? Looks like the same error. @jdalton said the issue looks familiar but we have not been able to provide him with a concise repo. Migrating the test to the new test harness if what "fixed" the issue.

**Comment by jdalton** [comment]
Can you see if this repros with the F12 dev tools open (debugger attached)

**Comment by Serabe** [comment]
@chancancode given that the beta at that time was 2.7, is this still an issue? Thank you!

**Comment by chancancode** [comment]
It can be closed
