### ISSUE TITLE
[BUG beta] `baseURL` incorrectly set in ember-routing/location/history-location

### ISSUE THREAD

**Issue by nathanhammond** [emberjs/ember.js#13795]
If a user adopts the 2.7 version of Ember CLI and applies the [`<base>` workaround we discuss](http://emberjs.com/blog/2016/04/28/baseURL.html#toc_everything-is-broken-help) without specifying a `baseURL` inside of their application the following breaks us:
https://github.com/emberjs/ember.js/blob/08dbada375a968f353a10a71aed95f87d372149f/packages/ember-routing/lib/location/history_location.js#L30

It assumes the `baseURL` from the content of the `<base>` tag rather than trying to get it out of the application's configuration. I consider this blocking to a 2.7 release.

/cc @Turbo87 @martinmalinda

**Comment by rwjblue** [comment]
I do not understand the issue here.  Can you please create a repo (or twiddle) that shows the failure scenario?

I believe that the linked line of code should continue to exist, but to get to the bottom of things we need to be talking about concrete scenarios.

**Comment by nathanhammond** [comment]
@martinmalinda Can you help us create a repository that runs through all of these permutations? (Even the ones that I added comments about "nobody should ever do this.")

| | Ember CLI 2.6 - autopopulated `<base>` | Ember CLI 2.7 - no `<base>` | Ember CLI 2.7 - manually added `<base>`
| --- | --- | --- | --- |
| **`baseURL` set, `rootURL` set** | | Nobody should ever do this. | If you do this and set a different `baseURL` from the `<base href="">` you deserve what you get. |
| **`baseURL` set, `rootURL` unset** | | Nobody should ever do this. | If you do this and set a different `baseURL` from the `<base href="">` you deserve what you get. |
| **`baseURL` unset, `rootURL` set** | | | **This is the one I believe may have a bug.** |
| **`baseURL` unset, `rootURL` unset** |

**Comment by nathanhammond** [comment]
Note: if we load `rootURL` and `baseURL` in from the config values every time I believe that we skirt the possibility of any issue, even in light of this comment from above:

> If you do this and set a different baseURL from the <base href=""> you deserve what you get.

The problem I see here is that we rely upon the `<base href="">` value to match the `baseURL` value, which it does in Ember CLI 2.6, but I believe that also magically includes things like `rootURL` and other strange build-time side effects.

I also know that @Turbo87 knows this _way_ better than me.

**Comment by rwjblue** [comment]
> The problem I see here is that we rely upon the <base href=""> value to match the baseURL value, which it does in Ember CLI 2.6, but I believe that also magically includes things like rootURL and other strange build-time side effects.

Ember has no concept of `baseURL`. That is an ember-cli only thing, and the result of specifying a `baseURL` in `config/environment.js` in all versions of ember-cli is to emit a `<base href="/the/value">`.  So I'm not sure what you mean about `<base>` not matching `baseURL`.

**Comment by nathanhammond** [comment]
I'm looking at these two places, which look like the same thing that we did in Ember CLI:
- https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/location/history_location.js#L70-L71
- https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/location/history_location.js#L218

**Comment by rwjblue** [comment]
Ya, the location implementations are honoring a `<base>` tag (just like an `<a>` or any other native asset loading would have to).  That internal property is definitely not public API.

In general, we cannot remove the concept of reading `<base>` from the document when starting routing unless we want to break any existing ember-cli apps with that Ember version (and break "the web" 😝).

**Comment by MartinMalinda** [comment]
> Ember has no concept of baseURL. That is an ember-cli only thing, and the result of specifying a baseURL in config/environment.js in all versions of ember-cli is to emit a <base href="/the/value">. So I'm not sure what you mean about <base> not matching baseURL.

I thought that's why rootURL was introduced. Since it's being set directly on the router it's more explicit. The fact that router is looking at DOM and reading from base tag is quite counter-intuitive to me.

I thought the point of deprecating baseURL is so we can move from `baseURL + rootURL` to just `rootURL` that gives freedom to put assets to different path without affecting routing url.

it could break apps that removed baseURL from config file and set base tag manually. As far as I know this never was a recommended practice. I don't see a reason why anyone would delete baseUrl from config and set base href value directly to achieve the exact same effect.

@nathanhammond I'll try to create that repo later today. I'll place the mentioned combinations in individual branches since I can't think of a different way how to do this more efficiently atm.

**Comment by Turbo87** [comment]
> I thought the point of deprecating baseURL is so we can move from baseURL + rootURL to just rootURL that gives freedom to put assets to different path without affecting routing url.

If I remember correctly `rootURL` is used primarily for the app routing, but is not so much related to the assets. You can use the `prepend` option of https://github.com/rickharrison/broccoli-asset-rev if your assets are deployed to a CDN and you want to adjust their paths.

**Comment by MartinMalinda** [comment]
@Turbo87 that works well if you know the path at build time. In my edge case I don't know where the app is served from. 

Anyways, here's the repo: https://github.com/MartinMalinda/ember-baseURL-test

And summary:

|                              | Ember CLI 2.6 - manually added `<base>`                                                                                                           | Ember CLI 2.6 - autopopulated `<base>`                                                                     | Ember CLI 2.7 - no `<base>` | Ember CLI 2.7 - manually added `<base>`                                                                                                            |
|------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------|---------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------|
| baseURL set, rootURL set     | `Uncaught Error: Assertion Failed: Path /base-test does not start with the provided rootURL /root-test/`                                        | `Uncaught Error: Assertion Failed: Path /base-test does not start with the provided rootURL /root-test/` | 404, can't find assets    | `Uncaught Error: Assertion Failed: Path /base-test does not start with the provided rootURL /root-test/`                                         |
| baseURL set, rootURL unset   | OK / two `<base>` tags                                                                                                                            | OK                                                                                                       | OK                        | OK / two `<base>` tags                                                                                                                             |
| baseURL unset, rootURL set   | error after hard refresh: `Uncaught Error: Assertion Failed: Path /manual-test/root-test/ does not start with the provided rootURL /root-test/` | 404, can't find assets                                                                                   | OK                        | error after hard refresh:  `Uncaught Error: Assertion Failed: Path /manual-test/root-test/ does not start with the provided rootURL /root-test/` |
| baseURL unset, rootURL unset | OK                                                                                                                                              | OK                                                                                                       | OK                        | OK                                                                                                                                               |

I am not sure if I've encountered any bugs. Maybe the error after hard refresh when rootURL is set. But it's probably just local server issue and isn't significant at all, as rootURL is usually set for production builds only.

I still think it that if baseURL is deprecated in Ember-CLI, reading from <base> tag could be deprecated in Ember as well and it could be used in the future to adjust the path to assets without affecting the routing url structure. For previous usecases, when base was used to affect routing url format, the string could just be moved to rootURL instead.

**Comment by nathanhammond** [comment]
@MartinMalinda I'm _incredibly_ grateful for the research you've done here. This is tremendous. If I ever have the privilege of meeting you in person your drinks are on me. 🍻

I'll dive in and analyze later today!

**Comment by MartinMalinda** [comment]
I think there's no need for urgency on this, I think there's no major bug, but I hope the repo will be useful anyway. It's still above my skill level to contribute to the core so I'm glad I could help somehow. :)

**Comment by Turbo87** [comment]
I'm afraid I still don't understand what the actual issue is here. The table above (thanks a lot @MartinMalinda!) indicates that everythings works as designed:

- `baseURL` and `rootURL` are not supposed to be used at the same time
- using only `baseURL` still works in all Ember CLI versions
- using only `rootURL` works in Ember CLI 2.7 and above
- using none of those options explicitly also works

> @Turbo87 that works well if you know the path at build time. In my edge case I don't know where the app is served from.

can you elaborate on that use case? I'd like to understand what you're trying to do so that we can come up with a plan to help you. Thanks again for looking into this!

**Comment by MartinMalinda** [comment]
@Turbo87 yes, sorry for the confusion I initially misunderstood what deprecating baseURL actually means. I thought it also means that reading from `<base>` by Ember is deprecated as well, but apparently it's not. 

I believe this can be closed. I can reach out on Slack about my particular use case later.

**Comment by Turbo87** [comment]
IMHO we should probably deprecate this too, but this presents us with the problem that using an Ember version where it is deprecated with a sub-2.7 version of Ember CLI will have no option to fix the deprecation (other than updating Ember CLI). this might be an artificial issue though and is probably not relevant in reality. we should however wait until Ember CLI 2.7 is the stable release and see if any other issues come up before deprecating this in Ember too.

**Comment by rwjblue** [comment]
> We should however wait until Ember CLI 2.7 is the stable release and see if any other issues come up before deprecating this in Ember too.

Sounds good to me.

**Comment by nathanhammond** [comment]
I _believe_ that I've confirmed that this can be closed. I just played around with all of the permutations. It's going to get wonky to explain what's going on to people who have weird setups, but we'll deal with it.
