### ISSUE TITLE
Get the DOM of a component with tagName=""

### ISSUE THREAD

**Issue by sourvb** [emberjs/ember.js#13798]
Hi,
I am setting tagName="" in my component. I cannot use any tagName, or else it will break the my page style. I want to access the DOM of that component. Using this.$() throws an error saying object not available for tagName=="". Is there any solution for this?

**Comment by mkay581** [comment]
Interesting... I'm just curious... does setting the `tagName` property to an empty string in the component JS file give you the same result?

**Comment by miguelcobain** [comment]
related: https://github.com/emberjs/ember.js/pull/12500

**Comment by pixelhandler** [comment]
@sourvb looks like #12500 will add the support your looking for, thanks @miguelcobain

**Comment by miguelcobain** [comment]
@pixelhandler you can see in that issue that @wycats had some problems with adding that feature.
Maybe we can have this functionality in an addon? /cc @runspired

**Comment by sourvb** [comment]
Thanks @pixelhandler and @miguelcobain. Is there any alternative solution for this?

**Comment by pixelhandler** [comment]
@sourvb personally I do not use `tagName=""` I would use a tag so I could access the DOM if needed. Which as you've mentioned requires fixing some style issues. I also avoid style libraries that prohibit how I can build HTML in my apps. But I get that is not always the case, is there a way you can use a tagName and fix the style issue some how?

**Comment by pixelhandler** [comment]
@sourvb see this comment, https://github.com/emberjs/ember.js/pull/4790#issuecomment-231211050 Which does answer your question…

> Is there any solution for this?

Closing this for now.
