### ISSUE TITLE
Cannot chain embers array functions when EXTEND_PROTOTYPE=false

### ISSUE THREAD

**Issue by thoov** [emberjs/ember.js#13809]
When disabling array prototype extensions the following occurs:

```js
var people = Ember.A([
  {name:  'John', age: 45, canDrive: true}, 
  {name:  'Jill', age: 40, canDrive: true},
  {name:  'Bob', age: 14, canDrive: false},
]);

var arrayMethodsAreMissing = people.compact();
```

This prevents you from chaining multiple methods off one another.

```js
var thisWillNotWork = people.compact().any('canDrive');
```

This means that you must wrap Ember.A's after each method which seems counterintuitive.

```js
// Your code starts looking like this:
var thisWillWork = Ember.A(Ember.A(people).compact()).any('canDrive');
```

**Comment by locks** [comment]
@thoov this is to be expected, as prototypes are turned off and Ember.A methods return regular arrays.

**Comment by stefanpenner** [comment]
This is expected, `Ember.A` is not intended to provide these methods that is a byproduct but not intended.

**Comment by thoov** [comment]
@stefanpenner I guess what I don't understand is if the docs are saying this: https://guides.emberjs.com/v2.6.0/configuring-ember/disabling-prototype-extensions/#toc_arrays

"You can manually coerce a native array into an array that implements the required interfaces using the convenience method Ember.A"

I don't get why simply calling one of these "convenience" methods removes them from the object? What is the expected workflow for fastboot users who cant use prototype extensions and cant rely on Ember.A?

**Comment by stefanpenner** [comment]
> I don't get why simply calling one of these "convenience" methods removes them from the object?

Each convenience returns a fresh array, which would then also need to be patched (which is slow and somewhat brittle). Why not leave EXTEND_PROTOTYPES on in fast-boot, and there is no issue (and no performance hit for constantly needing to patch array instances).

**Comment by thoov** [comment]
@stefanpenner There is an issue with fastboot + prototype extensions: 

`Ember Prototype extensions weren't available in an array created by an najax response - npm packages that are required are from the root node VM, which creates new realms and prevents requirements from being extended by Ember - Potential fix: create your own require that is with a known realm - This will bite people in the future (who are using prototype extensions) - Looks like a heisenbug: Extensions will only be available some of the time, depending on the origination of the object/array`

https://github.com/emberjs/core-notes/blob/master/fastboot-team/2016-05/may-25.md

Is there a better way of handling chaining that you know of? or is Ember.A(Ember.A(Ember.A(.... the best there is?
