### ISSUE TITLE
[Glimmer 2] Refactor references (metadata)

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#13803]
- Remove special const reference flag, use identity of CONST_TAG instead (tag dynamically return the const value is not the same thing – think compile time vs runtime for an analogy)
- Refactor how Ember install metadata on references
  - Avoid `Object.create`
  - Known metadata slots: `[EACH-IN]`, `[UPDATE]`, `[INVOKE]`
  - For most operations, you just drop the metadata; sometimes you would want to copy (places where we currently use `Object.create`)

**Comment by krisselden** [comment]
Can you just make one flags symbol as a bit set and every ref has it? Each megamorphic miss starts to add up.

**Comment by pixelhandler** [comment]
@chancancode is this still an issue, perhaps we should close; what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
