### ISSUE TITLE
Could helper `query-params` support object params 

### ISSUE THREAD

**Issue by chyxion** [emberjs/ember.js#13802]
For Example: 

> (query-params objParams)

I think it's necessary if we don't know how many params, thanks.

**Comment by pixelhandler** [comment]
@chyxion is this a feature suggestion? Or question? I'm curious if you've asked on the http://embercommunity.slack.com chat room.

**Comment by siva-abc** [comment]
We could write a custom helper to construct qp.

``` javascript
helpers/construct-qp.js

export function constructQueryParams ([params = {} ]){
 return Ember.Object.create({ isQueryParams: true, value: params });
}
export default Ember.Helper.helper(constructQueryParams);
```

```handlebars
{{#link-to 'comment.details' '1001' (construct-qp queryParamsObject)}}
   comment 1001
{{/link-to}}
```

**Comment by chyxion** [comment]
Well, this is a feature suggestion, I did not ask this issue before, I know we can write a custom helper, but I think this feature is necessary, thanks.

**Comment by Serabe** [comment]
Hello @chyxion.

Thank you for your suggestion. This repo is for Ember.js bugs only but you can submit this to [emberjs/rfcs](http://github.com/emberjs/rfcs) so the community can discuss it.

Thank you so much!
