### ISSUE TITLE
Different behavior for <elem {{action 'foo'}}> and <elem onclick={{action 'foo'}}>

### ISSUE THREAD

**Issue by nathanhammond** [emberjs/ember.js#13806]
I'm not entirely sure what expected behavior is, but this feels like something that should either: be consistent, or be clearly documented.

- [Reproduction by @shwoodard](https://ember-twiddle.com/452f76f0c24261795ba81ba00b07313d)
- [Reproduction by @oligriffiths](https://ember-twiddle.com/5087b7249d162fba1cb8560e229fd60a?openFiles=controllers.application.js%2C)

/cc @locks

**Comment by praxxis** [comment]
Depending on what you're referring to with "behaviour", https://github.com/emberjs/guides/issues/1345 is about the documentation side

**Comment by pixelhandler** [comment]
@nathanhammond @locks I think this should be moved to the guides repo, what do you think?

**Comment by nathanhammond** [comment]
Until I know what the actual behavior is supposed to be I can't answer that.

**Comment by zackthehuman** [comment]
To me the current behavior seems to make sense. The element modifier syntax (in other words, a "normal" action) binds the action to the event but basically discards the event object when calling the callback. The other syntax is essentially assigning a closure action (which is a function) to an inline event handler -- the typical DOM behavior is preserved: the callback receives the event argument.

I don't know if this was intentional, but it makes sense to me. However, I have seen this trip a lot of people up so maybe we should add some clarity around it.

**Comment by oligriffiths** [comment]
Zach

Would you mind detailing the implementation for those 2 approaches for clarity here? I want to make sure my issue is within that scope or out of it. 

Thanks

Oli

**Comment by pixelhandler** [comment]
Seems that we should clarify that if you need the event in your action handler then assign the action to an inline event handler.

The description @zackthehuman gave makes sense. @oligriffiths My guess is that this is not documented? Perhaps https://guides.emberjs.com/v2.7.0/components/handling-events/ needs a section on "treating an action like an event"? cc @locks 

>> The element modifier syntax (in other words, a "normal" action) binds the action to the event but basically discards the event object when calling the callback.

So `onclick={{action 'test'}}` https://ember-twiddle.com/4a939f5d0b208bcf34229670f635095a?openFiles=templates.application.hbs%2C DOES send the event as the 1st argument in the function (action) handler. 

>> a closure action (which is a function) to an inline event handler -- the typical DOM behavior is preserved: the callback receives the event argument

… `{{action 'test'}}` https://ember-twiddle.com/5087b7249d162fba1cb8560e229fd60a?openFiles=templates.application.hbs%2C does NOT send the event.

**Comment by pixelhandler** [comment]
@nathanhammond @zackthehuman @oligriffiths @locks what do you think? see https://github.com/emberjs/guides/pull/1624

**Comment by oligriffiths** [comment]
Will investigate and report

**Comment by pixelhandler** [comment]
@nathanhammond @oligriffiths I'll close this for now, a PR has been merged to the guides repo to address the documentation need, https://github.com/emberjs/guides/pull/1624
