### ISSUE TITLE
beforeModel() transition.queryParams always empty

### ISSUE THREAD

**Issue by FredUK** [emberjs/ember.js#13813]
I've just noticed that in `beforeModel(transition)` the `transition.queryParams` is always an empty object
![image](https://cloud.githubusercontent.com/assets/11888256/16798310/5e72ea62-48e3-11e6-82db-0cf3ef5cdcff.png)

Here's a twiddle demonstrating the issue: https://canary.ember-twiddle.com/ade8b543f299795dfd88ccbfb892ad20?openFiles=routes.article.show.js%2C&route=%2Farticle

Make sure to open the console so you can see when you transition to article/id.
Although I'm still able to access the params in beforeModel by using transitions.params[routeName] however I believe it's a bug that queryParams is always empty?

Cheers,
Fred

**Comment by Serabe** [comment]
Can you please add an example where the query parameters are needed in a `beforeModel`? IMHO, query parameters are related to the model in some way so the place to use them is `model`.

**Comment by pixelhandler** [comment]
@FredUK @Serabe I'm curious about the Transition class being `private` http://emberjs.com/api/classes/Transition.html#content the only methods that are recommended to use are `abort` and `retry` see https://guides.emberjs.com/v2.6.0/routing/preventing-and-retrying-transitions/#toc-toggle and http://emberjs.com/api/classes/Ember.Route.html#method_beforeModel 

I don't this it can be expected that the beforeModel hook has access to the query params as the model hook does receive them http://emberjs.com/api/classes/Ember.Route.html#method_model

**Comment by pixelhandler** [comment]
@FredUK this is not a bug in Ember, please reach out to the community in slack regarding your use case for working with query params, perhaps using the model hook will be fine.
