### ISSUE TITLE
Map and MapWithDefault marked as private

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#13815]
The `Map` and `MapWithDefault` classes are currently marked as `@private`, yet they are exported through the [shims](https://github.com/ember-cli/ember-cli-shims/blob/master/app-shims.js#L94-L97). It looks like the `@private` tag was added in https://github.com/emberjs/ember.js/pull/11362.

It seems inconsistent to me to export the classes but mark them as private so I'd like to propose marking them as public.

/cc @pangratz

**Comment by rwjblue** [comment]
The shims aren't guaranteed to all point to public things. 

I'm unsure if we intend to have these be public or not. I'd like to hear from other core team members...

**Comment by Turbo87** [comment]
> I'd like to hear from other core team members...

can I interpret the 👍  from @stefanpenner as acknowledgement? 😉

**Comment by Turbo87** [comment]
@rwjblue @stefanpenner any news on this?

**Comment by stefanpenner** [comment]
because ember-data uses them, they are at the very least intimate API. I would be fine to make them public, as Map is a pretty close to a strict subset of ES6 Map. So if we switch to ES6 map, it should "just work". We should confirm that MapWithDefault could be implemented as a subclass. If those are both true, I would push for making them public.

**Comment by pixelhandler** [comment]
@stefanpenner @rwjblue `MapWithDefault`  https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/map.js#L412-L446 extends `Map` so when it becomes the ES6 `Map` instead, using `Object.create(Map.prototype);` should still work for subclassing, correct?

**Comment by krisselden** [comment]
I'm strongly opposed to this, this should not be in core, they are not used by anything in core and currently only used in Ember Data.  This is the kind of thing we need to drop to lighten up core.

**Comment by rwjblue** [comment]
Seems good to me.  We should check in with the ember-data folks about a migration path...

**Comment by stefanpenner** [comment]
> I'm strongly opposed to this, this should not be in core, they are not used by anything in core and currently only used in Ember Data. This is the kind of thing we need to drop to lighten up core.

This is used in many add-ons and apps, regardless how we feel this is in core, it is defacto public. Marking it as private, and removing it wont yield much for apps as nearly everyone will pull it back in immediately, which will result in a pointless deprecation. We should be honest, make it public and as part of a future tree-shaking (or ES6 friendly) effort re-visit.

**Comment by Turbo87** [comment]
@rwjblue @stefanpenner has there been any discussion on this since last year? if the classes are not used by Ember itself IMHO we should remove them. we could build a sort of shim addon that checks the Ember version at buildtime and if Ember provides the classes ifself it would delegate to Ember, and otherwise provide the implementation itself (or even delegate to the native ES6 Map).

**Comment by rwjblue** [comment]
The basic plan forward here is:

* Create separate addons for:
  * `ember-ordered-set` - This would contain the implementation from [here](https://github.com/emberjs/ember.js/blob/0780f0e92537fb9a9665f9871f7e17cd96378548/packages/ember-metal/lib/map.js#L58-L202) in its `index.js`.
  * `ember-map-polyfill` - This would:
    * do nothing if all targets support native `Map`
    * include a `Map` polyfill (likely just bring over the implementation here in emberjs/ember.js)
  * `ember-map-with-default` -  Depends on `ember-map-polyfill` and extends native `Map`
* Update ember-data to use `ember-map-with-default` and `ember-ordered-set` (as needed).
* Once ember-data changes land in release version, land deprecations from #15119 (with `until: '3.5.0'`) .
* profit 💰

**Comment by Turbo87** [comment]
@rwjblue thanks for the detailed plan. I'll put it on the todo list :)

**Comment by locks** [comment]
Repos up:

- https://github.com/emberjs/ember-ordered-set
- https://github.com/emberjs/ember-map-polyfill
- https://github.com/emberjs/ember-map-with-default

**Comment by maxwerr** [comment]
Hopefully this is like Halfway to 🎯

**Comment by pixelhandler** [comment]
@rwjblue @locks Since the repops are up I'll close this for now.
