### ISSUE TITLE
Can`t get container in initializers.

### ISSUE THREAD

**Issue by magicismight** [emberjs/ember.js#13828]
This won`t work in 2.6.0
```
export function initialize(application) {
  console.log(getOwner(application));
}
````

**Comment by magicismight** [comment]
I can access container by using `application.__container__`.
Is this a bug or what?

**Comment by rwjblue** [comment]
The container/owner is not intended to be available in initializers, only the registry is. This effectively means that you cannot do `.lookup` in an initializer. If you need access to `.lookup` during the initialization system you would need to use an instance-initializer instead. 

Note: that the argument to initializers and instance-initializers can not have `Ember.getOwner` called on them. You would just call `.register` (in an initializer) or `.lookup` (in an instance-initializer) directly on the first argument.

**Comment by rwjblue** [comment]
Closing as this isn't a bug in the framework.
