### ISSUE TITLE
sortBy on Ember Array does not sort when ':asc' is added

### ISSUE THREAD

**Issue by blimmer** [emberjs/ember.js#13822]
[Demo](https://ember-twiddle.com/de424345c2fb44335709e4be9081f485)

I expected to be able to do something like this:
```javascript
Ember.A([el1, el2]).sortBy('fooProp:asc')
```
but I'm seeing different behavior when using `fooProp:asc` vs. just `fooProp`. The twiddle linked above shows the issue I'm experiencing.

**Comment by Serabe** [comment]
Hello, @blimmer,

thank you for this report. This is not a bug. [Enumerable#sortBy](http://emberjs.com/api/classes/Ember.Enumerable.html#method_sortBy) requires the name of the property/ies and does not accept `:asc` nor `:desc` modifiers. If you want to use those, take a look at [Ember.computed.sort](http://emberjs.com/api/classes/Ember.computed.html#method_sort).

Thank you!

**Comment by Blackening999** [comment]
You can always use .reverse() :)
