### ISSUE TITLE
scheduleRevalidate in canary is causing test failures

### ISSUE THREAD

**Issue by backspace** [emberjs/ember.js#13846]
Hello! `travis-web` has recently started failing to build on canary. One of the [errors](https://travis-ci.org/travis-ci/travis-web/jobs/145931925#L595) is this:

`Promise rejected after visiting /builds/branches-tab: null is not an object (evaluating 'node.ownerNode.emberView.scheduleRevalidate')`

Which looks to be from [this line](https://github.com/emberjs/ember.js/blob/28cedad1418bedd2dad44eb56668fa67b9769d86/packages/ember-htmlbars/lib/utils/subscribe.js#L24) in `ember-htmlbars/lib/utils/subscribe.js`:

`node.ownerNode.emberView.scheduleRevalidate(node, labelFor(stream));`

Looking at the history of that file, I don’t see any reason why recent changes would have produced this failure, but I’m wholly unfamiliar with this code.

Hopefully this is a helpful error report and not just a red herring. Let me know if you need any more information or if maybe it’s a problem in `travis-web`.

**Comment by Serabe** [comment]
Thank you for reporting this. I can confirm that this is failing and can be found in emberx-select (though canary is allowed to fail and therefore it was not noticed before). In that line:

* `node` is a `PropertyAttrMorph`. To be exact, a `selected` from an `x-option`.
* `node.ownerNode` is an `EmberMorph` whose `contextualElement` is `div#ember-testing`.

**Comment by backspace** [comment]
Thanks for the confirmation, @Serabe. I forked the repository for the built version of Ember and made a [commit](https://github.com/backspace/ember/commit/952149936ef942f225f70fab9c3d509a5d134422) that adds guards against the absence of `node.ownerNode.emberView`. I [changed `travis-web`’s `ember-try` configuration](https://github.com/travis-ci/travis-web/commit/b4fc37228c52b7958eace3317c5c933e330b2651) to use that fork as the Bower dependency and [the tests now pass](https://travis-ci.org/travis-ci/travis-web/jobs/146166038) with this modified version of canary.

I don’t know enough about this to know whether that type of guard is truly desirable or perhaps a deeper fix where `node.ownerNode.emberView` should _always_ be present is more the issue.

**Comment by rwjblue** [comment]
Can someone try to bisect and narrow down which change caused the issue?

**Comment by backspace** [comment]
I can try that tomorrow, @rwjblue. Is there an easier way than putting a local filesystem path in `bower.json` and repeatedly running `npm run build` during the bisection?

**Comment by rwjblue** [comment]
@backspace - Yes, definitely.

Something like this:

```js
# in one terminal
git clone git@github.com:components/ember.git components-ember
cd components-ember
git checkout canary
bower link

# in the app
bower link ember
ember serve # you will need to restart this after each bisect stage
```

Now you can `git bisect` in the components ember repo (though the SHA's are slightly different).  But at least this way you will not have to `nom` after every bisect step.

**Comment by backspace** [comment]
Thanks for the suggestion, looks like it’ll be much faster. I tried it and it said

`Bisecting: a merge base must be tested`

and then chose a commit from 2014. I think I’ve only used bisect once before, I’ll try to figure out what’s wrong tomorrow.

**Comment by backspace** [comment]
Never mind, I think the problem was that I ran `git bisect good canary` instead of a particular SHA.

`19d69b45a106d6e555c9f75db6354495635b34bf is the first bad commit`

I tried making a [build set to use that commit](https://travis-ci.org/travis-ci/travis-web/jobs/146285868) and the [one before it](https://travis-ci.org/travis-ci/travis-web/jobs/146286008) but I had Bower trouble and I should really not be working right now haha

Let me know if I can provide any more diagnostic information.

**Comment by rwjblue** [comment]
OK, based on the bisect it looks like https://github.com/emberjs/ember.js/pull/13775 introduced the failure.

**Comment by Serabe** [comment]
@rwjblue Thank you for bisecting this!

**Comment by rwjblue** [comment]
Yes, thanks to @backspace for that.  I just tracked down which Ember SHA matched the components/ember one he mentioned above.

**Comment by dustyjewett** [comment]
Any movement on this? It is now making our ember-beta builds fail.

**Comment by xdumaine** [comment]
+1

**Comment by backspace** [comment]
Maybe this thread should be locked to contributors to stem the inevitable tide of +1s?

**Comment by cibernox** [comment]
I bisected this myself for issue #14000 and also reached the conclusion that #13775 introduced this failure.

**Comment by Serabe** [comment]
Ember 2.8 is already beta 3 and this affects so far:

* travis-web
* ember-power-select
* ember-inspector

I've tried to fix this but is not simple and way above my level. Unless the fix is just guarding against `null`.

**Comment by Serabe** [comment]
Forgot emberx-select 😞

**Comment by pixelhandler** [comment]
So this could be a blocker for 2.8.0 release.

**Comment by rwjblue** [comment]
Yep, definitely is, and I labeled as such last night as I was poking at it a bit...

**Comment by miguelcobain** [comment]
Trying to help here.

I'm experiencing this bug on PhantomJS but not on Chrome.
Relevant log: https://travis-ci.org/miguelcobain/ember-leaflet/jobs/153965128

**Comment by rwjblue** [comment]
I have submitted https://github.com/emberjs/ember.js/pull/14110 to resolve this, I would really appreciate anyone having the issue to test out the builds I linked to in that PR.
