### ISSUE TITLE
Outdated documentation listing higher in search engines.

### ISSUE THREAD

**Issue by fewstera** [emberjs/ember.js#13848]
As a new user of Ember I find it rather annoying that when Googling Ember related queries, that outdated documentation is listed higher than the most recent and relevant documentation. 

I know this obviously isn't an easy fix as much of it is out of your control, but a few ways I'd consider:
- Have a link from the outdated documentation to the new page (extra internal links should boost that pages SEO ranking).
- Use a sitemap.xml, listing older version of the documentation with a lower priority value.
- Block old documentation using robots.txt (probably a terrible idea)

Thanks

**Comment by Serabe** [comment]
Thank you for this report. I think this is a dupicate/update of emberjs/guides#1185

Thank you for reporting this!
