### ISSUE TITLE
Move ember-testing helper docs to function definition.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#13862]
Currently the documentation for the `ember-testing` helpers (things like `click`, `andThen`, etc) are all in the same file [here](https://github.com/emberjs/ember.js/blob/5d6cf8d2c9f1db847c19a03e23edc98b561edbdc/packages/ember-testing/lib/helpers.js), but now that we have split the helpers themselves into separate files I'd like to have each helpers documentation moved into the helpers specific file.

For example, I would like the [click documentation](https://github.com/emberjs/ember.js/blob/5d6cf8d2c9f1db847c19a03e23edc98b561edbdc/packages/ember-testing/lib/helpers.js#L44-L60) to be moved into [this file](https://github.com/emberjs/ember.js/blob/5d6cf8d2c9f1db847c19a03e23edc98b561edbdc/packages/ember-testing/lib/helpers/click.js).

**Comment by pranjalk** [comment]
Hi! Can you assign this to me? This would be a nice way to start understanding ember.js

**Comment by mixonic** [comment]
Closed in https://github.com/emberjs/ember.js/pull/14107
