### ISSUE TITLE
Ember.js and Node.js route

### ISSUE THREAD

**Issue by hckhanh** [emberjs/ember.js#13884]
When I work with Ember.js, I realized that there is a problem between **Ember.js** and **Node.js** route.
If I had a route with Node like this: `http://localhost/api/users` and another route in Ember.js: `http://localhost/users`, how could I call the Ember.js route?

In my case, I host the Ember.js files as **static resources** in Node.js server.

Thank you in advanced.

**Comment by pixelhandler** [comment]
@hckhanh have your asked your question in the embercommunity.slack.com #-help channel?

We use the ember.js/issue tracker mainly for reporting bugs. You will get a better response to your questions in the slack chat room or ember forums, see http://emberjs.com/community/ (slack is very active)
