### ISSUE TITLE
[Glimmer2] Better solution for readDOMAttr

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#13908]
This is a public API that currently is just a wrapper around `getAttribute`. In Glimmer1 it read from a `renderNode` which is no longer a concept.

__Knowledge:__ Yehuda has a plan

**Comment by rwjblue** [comment]
I believe that this was resolved in https://github.com/emberjs/ember.js/pull/13987.

@chancancode - c/d?
