### ISSUE TITLE
[Glimmer2] Action instrumentation

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#13905]
Currently `ember-improved-instrumentation` is feature flagged and has not accounted for `ember-glimmer`.

__Failing Tests__: [Closure {{action}} improved instrumentation](https://github.com/emberjs/ember.js/blob/daa214d25ccdbbca7763340778ffbaf106aab6ec/packages/ember-glimmer/tests/integration/helpers/closure-action-test.js#L9)
__Knowledge__: Requires knowledge of how we want to instrument `{{action}}`

**Comment by rwjblue** [comment]
Tests have been updated, this is working now.
