### ISSUE TITLE
[Glimmer2] Instrumentation

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#13910]
__Failing test__: [Nodes without view instances are instrumented](https://github.com/emberjs/ember.js/blob/d638d524b55ebea5b77e662f9be84d3a4be18648/packages/ember/tests/view_instrumentation_test.js#L52)
__Knowledge__: This requires some thought from someone with knowledge of internals to do this efficiently

This probably required for the Ember Inspector

**Comment by chancancode** [comment]
Closed by #14130
