### ISSUE TITLE
Cannot Create Ember.Error in Chrome Canary

### ISSUE THREAD

**Issue by jherdman** [emberjs/ember.js#13919]
Any time an Ember.Error is raised in Chrome Canary (54.0.2809.0 canary (64-bit)), the following error is raised:

```
ember.debug.js:24824 Uncaught TypeError: Cannot assign to read only property 'stack' of object '[object Object]'
```

From what I can tell, the [temporary error object](https://github.com/emberjs/ember.js/blob/d56bc7bd9b488e5b3f54c47e987d24a0d67d3f53/packages/ember-metal/lib/error.js#L21) has an writable "stack" property:

<img width="342" alt="screen shot 2016-07-27 at 11 24 42 am" src="https://cloud.githubusercontent.com/assets/3300/17181103/dcf4fcd6-53ec-11e6-98ac-fc70a83da255.png">

Whereas the error subclass' "stack" property isn't:

<img width="357" alt="screen shot 2016-07-27 at 11 24 24 am" src="https://cloud.githubusercontent.com/assets/3300/17181127/f1640d6a-53ec-11e6-8cad-bfa7961d9919.png">

To cap things off, here's my reproduction app: https://github.com/jherdman/stack-sadness

**Comment by backspace** [comment]
This is affecting [Travis CI](https://travis-ci.org) in Chrome Canary, as well. It renders nothing when you’re logged in.

**Comment by wagenet** [comment]
I believe EmberError is extending the native Error class. However, it appears that Chrome 54 made the `stack` property readonly now.

**Comment by wagenet** [comment]
@chancancode says it's probably related to https://bugs.chromium.org/p/chromium/issues/detail?id=624285.

**Comment by stefanpenner** [comment]
@wagenet what makes you think that issue is related?

**Comment by chancancode** [comment]
It was just based on a quick search for things that landed on chrome recentish that has to do with errors

**Comment by stefanpenner** [comment]
@chancancode doesn't seems related.

----

Im poking around, findings so far:

1. not able to reproduce in isolation yet
1. in the error scenario in question, only after this line does the stack property get installed and when it does it is writable: false: https://github.com/emberjs/ember.js/blob/d56bc7bd9b488e5b3f54c47e987d24a0d67d3f53/packages/ember-metal/lib/error.js#L31
1. some relevant v8 code https://github.com/v8/v8/blob/b8229434c9fd3bfef81fb77d88779d0e78d06662/src/builtins/builtins-error.cc#L55-L62

**Comment by stefanpenner** [comment]
Appears to only happen in `"use strict";`

no failure:

```
(function() {
  function ErrorSubclass() {
      Error.apply(this, arguments);
      Error.captureStackTrace(this, ErrorSubclass);
      this.stack = 'hi';
  }

  ErrorSubclass.prototype = Object.create(Error.prototype);

   throw new ErrorSubclass()
}());
```

failure:

```
(function() {
  function ErrorSubclass() {
      Error.apply(this, arguments);
      Error.captureStackTrace(this, ErrorSubclass);
      this.stack = 'hi';
  }

  ErrorSubclass.prototype = Object.create(Error.prototype);

   throw new ErrorSubclass()
}());
```

**Comment by stefanpenner** [comment]
Offending commit: https://github.com/v8/v8/commit/02503b080fbda2d8a72581a4669ea400d5322670

**Comment by stefanpenner** [comment]
So, I believe this is primarily stupid ember code, but also likely a web incompatible v8 change...

**Comment by hishboy** [comment]
klsklskd

**Comment by stefanpenner** [comment]
Original source of each part:

1. copy error properties over from the error ancestor (I believe this is because people are not required to `new` errors. https://github.com/emberjs/ember.js/commit/2b28b204d5ea49cb2a132bbe58b9767492e1892e#diff-a23b3b4d803c29958e763306e7a2d02aR492 (circa May 17, 2011)
2. introduced `Error.captureStackTrace` in the position before stomping on it \w the above line of original code https://github.com/emberjs/ember.js/commit/65334d9942e33978ad3444b06274b62c62111514

**Comment by stefanpenner** [comment]
quick work around would be to do the following `Error.captureStackTrace = undefined;`

**Comment by stefanpenner** [comment]
Although very strange that we basically do.

```js

function E() {
  var tmp = Error.apply(this, arguments);
   Ember.captureStackTrace(this, E);
   this.stack = tmp.stack; // exist for when people dont `new` and don't have `captureStack`
}
```

`captureStackTrace` sets both `stack` and an internal slot `stack` that is used to display an untampered stack to the console. So although `error.stack` is likely incorrectly stomped, the intended behavior (logged message) does the right thing?

**Comment by stefanpenner** [comment]
One approach: https://github.com/emberjs/ember.js/pull/13939

I think we should also open a chrome/v8 issue, so they are aware and can explore if this consider this web compat issue or not.

**Comment by bmeurer** [comment]
We're going to have a look, and come up with a reasonable fix soonish.

**Comment by stefanpenner** [comment]
v8 issue: https://bugs.chromium.org/p/v8/issues/detail?id=5245

**Comment by addyosmani** [comment]
I think this should be fixed as of https://chromium.googlesource.com/v8/v8.git/+/1c7c0521f1f9b4e70e19b0999c613fdb3b262deb. Possible to verify?

**Comment by stefanpenner** [comment]
@addyosmani I'll give it a whirl after breakfast.

I dont mind building v8 myself to test but i was able to find win/linux prebuilds here
http://commondatastorage.googleapis.com/v8-asan/index.html do OSX ones also exist?

**Comment by stefanpenner** [comment]
@addyosmani Just verified locally that v8 a79ec0e does not have this issue any longer. Is there a predictable period of time before this is part of a chrome canary release (maybe nightly)?

**Comment by stefanpenner** [comment]
As this has been fixed in v8, at some point soon (maybe nightly) we will see a Chrome canary \w a fix. I believe this is closed on our end.

Thank you for reporting, and thanks to @benedikt and the rest of the chrome/v8 team for the fast turn around.

**Comment by backspace** [comment]
Thanks to everyone for their work on this! Currently, Chrome Canary tabs are crashing for me immediately upon open, but I’ll check in again later.

**Comment by stefanpenner** [comment]
> Thanks to everyone for their work on this! Currently, Chrome Canary tabs are crashing for me immediately upon open, but I’ll check in again later.

Yes, the published Canary does not appear to have the fix yet, but a custom build of v8 did demonstrate a fix.

**Comment by stefanpenner** [comment]
Oh i see, yes my most recent Chrome Canary "aw snaps" constantly on any random site...

**Comment by Redsandro** [comment]
I experienced the same problem. I was going to blame Ember, but good to know it's Chrome instead. :smile: 

Does anyone know when this was introduced to Chrome? I updated from 52 to get rid of the [scroll jump bug](https://bugs.chromium.org/p/chromium/issues/detail?id=616308), and rolling back further will bring back the defunct high precision scrolling.

Chrome is a bit like a minefield of bugs lately.

**Comment by natorion** [comment]
We shipped the fix in 54.0.2812.0 and are currently on 54.0.2815.0. This behavior change is not in Chrome 52.

The "aw snaps" were related to another bug.

**Comment by Redsandro** [comment]
@natorion Ah I see. I'm on Linux, the current package is `54.0.2810.2`. I guess I can expect it to auto-update anytime now. Thanks for the information.

**Comment by natorion** [comment]
You are likely running the Dev Channel which means it gets updated once a week (typically on Tuesdays).

**Comment by Redsandro** [comment]
Awesome! :+1: 
Dev channel indeed.
