### ISSUE TITLE
Ember.Route: this.render does resolve template path in pod structure

### ISSUE THREAD

**Issue by badazz91** [emberjs/ember.js#13918]
if the `foo` template looks like this:

```
<div>
{{outlet}}
{{outlet 'baz'}}
</div>
```

And you try to render two templates into different outlets with the ```renderTemplate``` hook like this:

```
  renderTemplate() {
    this.render({ into: 'foo' });
    this.render('bar',{
      into: 'foo',
      outlet: 'baz'
     });
  },
```

Then it only works if the ```bar.hbs``` is located in ```app/templates```. It does not work when it is nested inside a pod structured app like e.g. this ```app/pods/foo/bar.hbs```.

Maybe it should be possible to import a template via ```import bar from './bar'``` and that ```this.render``` accepts both a path and a imported template.

**Comment by pixelhandler** [comment]
@badazz91 Should the title of this issue be "Ember.Route: this.render does not resolve template path in pod structure" ?

**Comment by rwjblue** [comment]
`this.render('bar'` is looking for a template named `bar`, not `foo/bar` (which is where you have placed the template `app/pods/foo/bar.hbs`).  Also, `app/pods/foo/bar.hbs` isn't a valid location for pods resolver either (it should be `app/pods/foo/bar/template.hbs`).

If you want to render `app/pods/foo/bar/template.hbs` via `this.render`, you would have to do `this.render('foo/bar', {});`.

**Comment by badazz91** [comment]
Ok, this worked for me. Then it was simply miss-usage and not a bug. =)
