### ISSUE TITLE
[Glimmer 2] Ember Inspector

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#13929]
These tests need to pass: https://github.com/emberjs/ember.js/blob/b888104b9ac98d464105be02fae5b807a90bfd13/packages/ember-glimmer/tests/integration/components/utils-test.js

**Comment by chancancode** [comment]
Closed by https://github.com/emberjs/ember-inspector/pull/579, see also https://github.com/emberjs/ember-inspector/issues/582
