### ISSUE TITLE
Ember 1.13 broken in IE8

### ISSUE THREAD

**Issue by mattbearman** [emberjs/ember.js#13936]
The latest update to Uglify JS (2.7.0) no longer supports IE6 - 8 by default, it has to be enabled by setting `screw_ie8: false` in the options.

This means a default install of Ember 1.13 doesn't work in IE8 anymore.

My proposed fix would be to change the 1.13 branch of Ember's default `ember-cli-build.js` to have

```javascript
var app = new EmberApp(defaults, {
  // Force Uglify JS 2.7.0 + to support IE 6 - 8
  minifyJS: {
    options: {
      compress: { screw_ie8: false },
      mangle:   { screw_ie8: false },
      output:   { screw_ie8: false }
    }
  }
});
```

**Comment by Serabe** [comment]
Thank you for reporting this, @mattbearman. Sadly, 1.13 is no longer maintained and it is very unlikely that a new release is done at this point (there is a new LTS and the second one is a few months away).

Thank you!
