### ISSUE TITLE
[Glimmer 2] Difference in `willRender` semantics

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#13947]
Previously, `willRender` only fire when something _directly inside_ the component's template has changed (in other words, dynamic content rendered directly from the component's layout).

In Glimmer 2, this hook will fire when anything inside its template subtree has changed, regardless on the depth of the nesting (in other words, dynamic content rendered from the component's layout and also by the child components it invoked from within its layout,  _their_ child components, and so on).

Put it simply, the `willRender` hook will be called anytime something is about to be re-rendered _anywhere inside the component's element_.

In the new implementation, the rendering engine does not differenciate between whether some dynamic content is nested "directly" inside a component. (Future optimizations, such as inlining, will make the line even more blurry.) As such, there is no natural place to track that distinction and we cannot rely on the old huristic/semantics.

To our knowledge, the previous behavior is not guaranteed in official documentation. Since `willRender` is mostly used on "leaf" components, we believe the impact will be minimal. Incidentally, this will also enable some use cases that were not previously possible, such as a `{{#render-markdown}}...{{/render-markdown}}` component that converts its content from markdown to HTML.

If you believe you have usage patterns that are affected by this, please provide as much detail about your scenario as possible below. It is very possible that there can be alternatives and/or targeted solutions we can use that do not require a wholesale change to the engine. Therefore, it would be helpful if you can provide background information and context about your usage instead of just showing us small code snippets from your codebase.

**Comment by rwjblue** [comment]
I believe this was resolved by #14222.  

@chancancode - Can you confirm?

**Comment by chancancode** [comment]
@rwjblue #14222 correctly implemented what is described here, but this issue is describing the difference between htmlbars and glimmer 2 (before #14222, it was "somewhere in between")

**Comment by runspired** [comment]
Note that this also affects `didRender` semantics.
