### ISSUE TITLE
[Glimmer 2] (action (mut nonDefinedValue)) fails

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#13959]
Error:
> Action passed is null or undefined in (action)

Reproduction code:

```hbs
<input value={{nonDefinedProp}} oninput={{action (mut nonDefinedProp) value="target.value"}}>
```
_(note: the `value="target.value" is irrelevant`)_

Twiddle so you don't have to type the code above: 

https://ember-twiddle.com/56f80b7916bde51fb7d3ec47c7b39946?fileTreeShown=false&openFiles=templates.application.hbs%2C

**Comment by chancancode** [comment]
@cibernox can you try again with the latest build? (`rm -rf bower_components/ember && bower install --save ember#alpha`)

**Comment by cibernox** [comment]
After lunch 👍

**Comment by cibernox** [comment]
There is another problem with this, but I'll open a new issue.

**Comment by rwjblue** [comment]
Thank you @cibernox!
