### ISSUE TITLE
[Glimmer 2] Uses of `ember-runtime` throw an error

### ISSUE THREAD

**Issue by knownasilya** [emberjs/ember.js#13956]
Just did a search in my node_modules and got the following files:

```sh
node_modules//bootstrap-modal/node_modules/liquid-fire/addon/ember-internals.js
node_modules//ember-cli-page-object/_site/dist/assets/vendor.js
node_modules//ember-cli-page-object/_site/dist/assets/vendor.map
node_modules//google-maps-markup/node_modules/ember-wormhole/dist/assets/vendor.js
node_modules//google-maps-markup/node_modules/ember-wormhole/dist/assets/vendor.map
node_modules//liquid-fire/addon/ember-internals.js
node_modules//loader.js/benchmarks/scenarios/ember-just-modules.js
node_modules//loader.js/benchmarks/scenarios/ember.js
```

Looks like:
- liquid fire (which we already knew)
- loader.js (benchmarks, so small importance)
- ember-wormhole
- ember-cli-page-objects (tests only).

**Comment by rwjblue** [comment]
> ember-cli-page-object
> ember-wormhole

I can't find reference to ember-runtime / ember-htmlbars in these projects.

> loader.js (benchmarks, so small importance)

This is a test that is actually embedding ember's module graph for testing, so not something that should be shipping to users (package.json `files` filtering was recently added so new versions do not even include this file).

---

Closing this for now, as we are already tracking liquid-fire and ember-i18n separately.
