### ISSUE TITLE
[Glimmer 2] Cannot read property 'hasComponentDefinition' of undefined

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#13962]
I suspect that this is an issue when using contextual components like this:

```hbs
{{#basic-dropdown as |dropdown|}}
  {{#dropdown.trigger}}Click me{{/dropdown.trigger}}
  {{#dropdown.content}}<p>Content</p>{{/dropdown.content}}
{{/basic-dropdown}}
```

This problem is affecting Ember Basic Dropdown.

Sample app (doesn't render): https://glimmer2-basic-dropdown.development.pagefrontapp.com/
Code: https://github.com/cibernox/ebd-glimmer2-failure

**Comment by dfreeman** [comment]
I'm actually able to reproduce this in any case where the component's `layout` is explicitly set rather than being in a location where it's discovered by the resolver.

https://github.com/dfreeman/glimmer-explicit-layout-failure

**Comment by krisselden** [comment]
Fixed in #13967

**Comment by krisselden** [comment]
@dfreeman that is the only way this bug should be happening.  It is the same thing in ember-basic-dropdown

**Comment by cibernox** [comment]
I can confirm that this issue is fixed. Investigating another one.
