### ISSUE TITLE
[Glimmer 2] Binding `undefined` to a text input outputs "undefined"

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#13974]
Code:

```hbs
<input value={{nonDefinedProp}}/>
```

Result:

<img width="149" alt="screen shot 0028-07-30 at 17 29 05" src="https://cloud.githubusercontent.com/assets/265339/17271716/28b20cb4-567b-11e6-8e22-f42c58ec4b80.png">

Demo:

https://glimmer2-basic-dropdown.development.pagefrontapp.com

**Comment by chancancode** [comment]
cc @chadhietala

**Comment by chancancode** [comment]
@chadhietala I think you just want to call `normalizeTextValue` [here](https://github.com/tildeio/glimmer/blob/master/packages/glimmer-runtime/lib/dom/change-lists.ts#L126)

**Comment by chadhietala** [comment]
https://github.com/tildeio/glimmer/pull/245

**Comment by chancancode** [comment]
@cibernox can you confirm this is fixed? :smile:

**Comment by cibernox** [comment]
Fixed 👍
