### ISSUE TITLE
[DOCS] Ember.RSVP.cast is not documented

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#13984]

**Comment by rwjblue** [comment]
`RSVP.cast` is just `Ember.RSVP.resolve` AFAIK ([see here](https://github.com/tildeio/rsvp.js/blob/master/lib/rsvp.js#L26)). I think `Ember.RSVP.Promise.resolve` would be preferred over either, but @stefanpenner should chime in to confirm/deny...

**Comment by stefanpenner** [comment]
`cast` is dead, don't use it, as 100% of `cast` usages can be expressed as `Promise.resolve`. It exists purely as a deprecated compat thing.
