### ISSUE TITLE
[Glimmer 2] Array of objects bindings are not reflected in the DOM

### ISSUE THREAD

**Issue by astronomersiva** [emberjs/ember.js#13983]
In an array of objects, the corresponding DOM changes are not updated immediately when the object properties are modified. They are batched together and updated when some other element is modified/added in the array.

The issue happens only when the array elements are added dynamically(using pushObject or insertAt). 

Steps to reproduce in the [demo twiddle](https://ember-twiddle.com/c03e039a80cae64d7d779ff3cdecac76?openFiles=controllers.application.js%2C):

1. Click on Add field. Clicking on Append to Field will update the correspondong object in the array and the changes are displayed in the DOM.
2. Click on Add field again. Clicking on Append to Field will update the object(can be verified in the console) but the DOM isn't updated.
3. Click on Add field again. The changes that weren't updated in the DOM will be now updated.

**Comment by chancancode** [comment]
Thanks for the report! 

I can confirm the bug, here is a reduced-reduced test twiddle: https://ember-twiddle.com/b5d86afbf2be8496b0af8b9acef57959

Will look into it.

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/14082
