### ISSUE TITLE
[Glimmer 2] Updating a bound attr of a contextual component creates a new component

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#13982]
If a contextual component has some data bound, and that data is updated, any instances of that component gets complete reinitialized like if it was an entirely new component.

```hbs
<button onclick={{action "toggleIsOpen"}}>Toggle</button> {{!-- Clicking here causes the component's `init` hook to be called again. Creates a new component --}}
{{#with (hash ctxCmp=(component "my-comp" isOpen=isOpen)) as |thing|}}
  {{#thing.ctxCmp}}This is a contextual component{{/thing.ctxCmp}}
{{/with}}
```
This is a regression, since in 2.7 the same component is reused and the state just gets updated.

Live twiddle (works in stable, fails in alpha):

https://ember-twiddle.com/5b6ea116582202584db37a667a21b056?openFiles=templates.application.hbs%2Ctemplates.components.my-comp.hbs

**Comment by chancancode** [comment]
Thanks for reporting! This is definitely a bug we can/should fix 👍

**Comment by chancancode** [comment]
We currently rely on the ComponentDefinition (an internal object) being stable/`===`, but looks like the ones produced by the component helper is not. So we either have to fix the component helper to produce stable values, or to beef up the stability check to not rely on `===`. Currently I believe the first approach would be simplier.

**Comment by cibernox** [comment]
@chancancode In my mind that's how this worked already. I thought that the reference was stable unless the first argument (the component's name) changes.

**Comment by zackthehuman** [comment]
I'm looking in to this.

**Comment by rwjblue** [comment]
Should be closed by #13997, @cibernox can you confirm and close?

**Comment by cibernox** [comment]
@rwjblue It does work on one case, but not in other I believe. I'll check if I can narrow it down to another twiddle.

**Comment by cibernox** [comment]
@zackhall There is one case that still fails. If the name of the component is not a constant reference, the component keeps being initialized.

https://ember-twiddle.com/5b6ea116582202584db37a667a21b056?openFiles=templates.application.hbs%2Ctemplates.components.my-comp.hbs

**Comment by rwjblue** [comment]
Hehe, I think you meant @zackthehuman here.

**Comment by cibernox** [comment]
Indeed. Github's username suggestion is a bit drunk actually.

**Comment by rwjblue** [comment]
Just landed #14005 which should fix.  

@cibernox - Can you confirm and close (will be ~ 15-20 minutes until alpha build is updated).

**Comment by cibernox** [comment]
@rwjblue Just tested. It works finally 🎉

**Comment by rwjblue** [comment]
Awesome, thanks for testing!  Looking forward to the next round of issues from you now 😉
