### ISSUE TITLE
addObject/ pushObject is not a function

### ISSUE THREAD

**Issue by sibijohn72** [emberjs/ember.js#13998]
I recently moved from ember 1.x to 2.6. I am not able to use addObject/ pushObject like i used to.

```
import Ember from 'ember';

export default Ember.Controller.extend({
test:['sibi','john'],
init:function() {
this.get('test').pushObject('sebastian');
}
});
```

This throws an error like pushObject is not a function. What is the workaround? Thank you.

**Comment by Serabe** [comment]
Quite likely the extend prototypes option is false for some reason. Personally, I like it better: it makes switching between app and addon easier.

You can read more about disabling prototype extensions in  [the guide](https://guides.emberjs.com/v2.7.0/configuring-ember/disabling-prototype-extensions/).

Thank you!
