### ISSUE TITLE
Canary builds are versioned as 2.9.0-null+<sha> instead of 2.9.0-canary+<sha>

### ISSUE THREAD

**Issue by pgengler** [emberjs/ember.js#13993]
The Ember.js canary builds are appearing as version `2.9.0-null+<sha>` (e.g., `2.9.0-null+6449018e`) instead of `2.9.0-canary+6449018e`.

To see this, look at the version data in the output of [the builds.emberjs.com tests](http://builds.emberjs.com/canary/ember-tests-index.html).

**Comment by rwjblue** [comment]
Thanks for reporting! I'll get on it...

**Comment by rwjblue** [comment]
![screenshot](https://monosnap.com/file/mjs0gyDEAUsJ9sKG2A6XqKTUXZOGxf.png)
