### ISSUE TITLE
[Glimmer 2] Passing an undefined variable to a helper causes an error

### ISSUE THREAD

**Issue by martndemus** [emberjs/ember.js#13999]
```hbs
{{camelize undefined}}
```

raises: `TypeError: Cannot read property '0' of null`
It never reaches the helper code before the error is thrown.

Reproduction:
https://jsbin.com/hawerupatu/edit?html,js,output

**Comment by Cryrivers** [comment]
passing null causes the error as well
```js
{{helper null}}
{{helper key=null}}
```

**Comment by GavinJoyce** [comment]
It's easy to reproduce this in the glimmer visualizer:

<img width="1192" alt="screen shot 2016-08-02 at 21 20 47" src="https://cloud.githubusercontent.com/assets/2526/17343723/0e1672c2-58f7-11e6-8cdf-540693a4a97c.png">

`isArg(sexp)` fails as sexp is `[null]` and:

<img width="630" alt="screen shot 2016-08-02 at 21 01 57" src="https://cloud.githubusercontent.com/assets/2526/17343839/95fd06b0-58f7-11e6-8de8-eeb9310fa384.png">

<img width="483" alt="screen shot 2016-08-02 at 21 01 11" src="https://cloud.githubusercontent.com/assets/2526/17343853/a0c3c84a-58f7-11e6-8ee6-6519a025c6c3.png">

**Comment by GavinJoyce** [comment]
Failing test: https://github.com/tildeio/glimmer/pull/251

**Comment by bmeurant** [comment]
Here is another related failing test : https://github.com/bmeurant/ember-array-contains-helper/blob/master/tests/integration/helpers/array-contains-test.js#L48

With travis job errors : https://travis-ci.org/bmeurant/ember-array-contains-helper/jobs/149285829

I also have issues later but not necessarily related to this (maybe I am doing something wrong): it seems that updating the array (adding object or modifying existing object) does not rerun the helper compute function [here](https://github.com/bmeurant/ember-array-contains-helper/blob/master/tests/integration/helpers/array-contains-test.js#L225) and [here](https://github.com/bmeurant/ember-array-contains-helper/blob/master/tests/integration/helpers/array-contains-test.js#L245).

**Comment by rwjblue** [comment]
Fixed by https://github.com/tildeio/glimmer/pull/252 and https://github.com/tildeio/glimmer/pull/255.  Tracking updating in Ember.js in https://github.com/emberjs/ember.js/issues/14016.
