### ISSUE TITLE
[Glimmer 2] textarea renders "true" instead of ""

### ISSUE THREAD

**Issue by GavinJoyce** [emberjs/ember.js#14001]
The rendered value of `textarea` is `"true"` instead of `""` when the context value is `""`.

TODO:

 * [x] Create a failing test @gavinjoyce: https://github.com/tildeio/glimmer/pull/250
 * [x] Fix: https://github.com/tildeio/glimmer/pull/250

Given the following controller:

```js
export default Ember.Controller.extend({
  textareaContent1: '',
  textareaContent2: 'some default text',
});
```

And template:

```hbs
textareaContent1: {{textarea value=textareaContent1}} <br />
textareaContent2: {{textarea value=textareaContent2}} <br />
```

**htmlbars renders:**

<img width="626" alt="screen shot 2016-08-02 at 12 01 05" src="https://cloud.githubusercontent.com/assets/2526/17326459/753ebd86-58a9-11e6-8c02-d36919275173.png">

**glimmer renders:**

<img width="597" alt="screen shot 2016-08-02 at 12 00 36" src="https://cloud.githubusercontent.com/assets/2526/17326460/7906c12a-58a9-11e6-8a88-b009f22f8820.png">

Sample App: https://github.com/GavinJoyce/glammer (see http://localhost:4200/issue3)

This doesn't happen for `{{input}}`.

**Comment by GavinJoyce** [comment]
We're calling `normalizePropertyValue` for `value` on `textarea` which sets a `""` value to `true`:

https://github.com/tildeio/glimmer/blob/9ecc9ade7efa41cf7068729ddeea4b09c1ce51de/packages/glimmer-runtime/lib/dom/props.ts#L33-L39

**Comment by rwjblue** [comment]
Reopening here until we bump glimmer versions.

**Comment by cibernox** [comment]
This is the only bit preventing EPS from work in glimmer2. I've even reduced the reproduction even more: https://ember-twiddle.com/64618480b3b1507f8d73475007f9b2a0?openFiles=templates.application.hbs%2C
