### ISSUE TITLE
Engines + visit + shouldRender: false incompatible

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#14015]
It appears (debugging with @rwjblue) that  the follwing in an engine's route, will currently always assume `renderTemplate` should be invoked.

```js
if (!this._environment || this._environment.options.shouldRender) {
```

source: https://github.com/emberjs/ember.js/blob/13ea22bd54a5e967fd4638704bb55b348fb07d32/packages/ember-routing/lib/system/route.js#L1235

it may be that: https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/engine-instance.js#L170-L184 should also clone '-environment:main' forward.

----

### The failure scenarios:

* For one, we render (or attempt to render) even though we explicitly ask not to
* A hard failure is also possible:

```
Error in Ember run loop: TypeError: Cannot read property 'outlets' of undefined
```

That we are attempting to render (when are asked not ot), but for other reasons (not 100% yet) after the above branch fails, we attempt a render, then during `setupOutlets` we take [this branch](https://github.com/emberjs/ember.js/blob/9ebda97047be7f8ce2c5b3f4e4568cdc25844dea/packages/ember-routing/lib/system/router.js#L290) before `defaultParentState` has been [assigned](https://github.com/emberjs/ember.js/blob/9ebda97047be7f8ce2c5b3f4e4568cdc25844dea/packages/ember-routing/lib/system/router.js#L292), in this case `findLiveRoute` returns no live route [here](https://github.com/emberjs/ember.js/blob/9ebda97047be7f8ce2c5b3f4e4568cdc25844dea/packages/ember-routing/lib/system/router.js#L1325) which ends up \w us taking the [else](https://github.com/emberjs/ember.js/blob/9ebda97047be7f8ce2c5b3f4e4568cdc25844dea/packages/ember-routing/lib/system/router.js#L1335) and throwing because `defaultParentState` is still undefined

**Comment by stefanpenner** [comment]
action items:

- [ ] investigate if
- [ ] add assertion/throw to https://github.com/emberjs/ember.js/blob/9ebda97047be7f8ce2c5b3f4e4568cdc25844dea/packages/ember-routing/lib/system/router.js#L1332 when we end up in this case.
- [ ] refactor https://github.com/emberjs/ember.js/blob/9ebda97047be7f8ce2c5b3f4e4568cdc25844dea/packages/ember-routing/lib/system/router.js#L278-L293 to be a-bit easier to follow
- [ ] do some research to see if there are anymore obvious related issues

**Comment by stefanpenner** [comment]
Commit that introduced the `environment` concept and the branching: https://github.com/emberjs/ember.js/commit/8e317ee6ddd10493382d6e2ec9477bb457ce873c

**Comment by stefanpenner** [comment]
Also, although I usually also try and fix issues i discover. I don't believe I'll have time right now to bring this one to completion. Although I'll gladly help anyone who does tackle.

**Comment by rwjblue** [comment]
@stefanpenner - I think the ember-engines strike team can pick this up as it seems like it would be a growing issue in the 2.8.0-beta usage of engines.

@dgeb / @nathanhammond / @trentmwillis - Lets circle around about this soon.  I think step one is a failing test (preferably here, but possibly in the addon)...

**Comment by trentmwillis** [comment]
I'll look into this and try to pull together a failing test.

**Comment by ef4** [comment]
I agree on adding a smarter failure message when something attempts to render into a nonsensical destination.

**Comment by rwjblue** [comment]
I believe that this is resolved.

@trentmwillis - Can you confirm that #14025 fixed this?

**Comment by stefanpenner** [comment]
I believe it is resolved, we will reopen if it is not.
