### ISSUE TITLE
FillIn acceptance helper works only on the first matched input

### ISSUE THREAD

**Issue by piotrpalek** [emberjs/ember.js#14018]
I tried to `fillIn` multiple inputs in an acceptance test with one selector. So let's say my template was:

```
{{input value=someVal}}
{{input value=otherVal}}
```

And I was using `fillIn` like this: `fillIn('input', 'someval')`

The result would be that visually it would seem as if both inputs are filled in with the same value (html was updated), but the data binding would only be updated on `someVal`.

Replicated here: https://ember-twiddle.com/63d30b6cde4d82491c0def9bcc36ef28

(sidenote: I couldn't use Ember 2.7 due to a twiddle bug, but the same thing is happening in an app using Ember 2.7)

**Comment by piotrpalek** [comment]
Ok so the issue seems to be that the `fillIn` helper uses the first element of the collection it finds for most of the work, but uses the whole collection to set the value:

https://github.com/emberjs/ember.js/blob/86d68628b82a6ea2d850cef09776410cde38c4a7/packages/ember-testing/lib/helpers/fill_in.js#L14

Question is what's the expected behavior, to only work on the first element or to work on all found elements?

**Comment by pixelhandler** [comment]
@piotrpalek I'm curious if you are more explicit with the selector you use with `fillIn` to only find one input does the helper work as expected?

**Comment by piotrpalek** [comment]
@pixelhandler being able to make the selector more specific isn't the issue. The issue is that the behavior is bugged when having a selector that matches multiple inputs. It should either _only_ work for the first element in case of multiple inputs, or work consistently for all of them.
Right now when you try to `fillIn` multiple inputs _seems_ as if it's working but actually isn't, that is very clearly a bug in my opinion.
As for the question if it should work for multiple elements. I think that if the guides say that it expects a selector for the input, without specifying that it will only work for the first matched element, then it would be expected that it can work on all of the elements that the selector finds, not only for the first item. But that's something that can be agreed on.

**Comment by Serabe** [comment]
Thank you, @piotrpalek! The PR has just been merged and there is a [comment in the Grand Testing Unification RFC](https://github.com/emberjs/rfcs/pull/119#issuecomment-237914054) you might be interested in.

Thank you!

**Comment by piotrpalek** [comment]
@Serabe np :+1:
