### ISSUE TITLE
depending on "model.constructor.modelName" sets model.constructor to undefined

### ISSUE THREAD

**Issue by spruce** [emberjs/ember.js#14014]
In my app I use an computed property to state how many steps are left to do for creating the models. This depends on how many steps are already done and which kind of model it is currently creating. (We create different kind of coworkers)

In Ember 2.5 it did work. After upgrading or slightly after (not quite sure) it stopped working.

this is my cp

```
numberOfSubSteps: Ember.computed('model.constructor.modelName', function() {
    let valueBasedOnModel = 4;
    switch(this.get('model.constructor.modelName')) {
      case 'kurzfristig':
        valueBasedOnModel = 5;
        break;
      case 'geringfugig':
        valueBasedOnModel = 6;
        break;
...
    }
    return valueBasedOnModel;
  }),
```

I found the exact line where it changes the constructor. (It defines a new property which somehow is then returning undefined.)
https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/watch_key.js#L81

This is the callstack when it happens
![screenshot 2016-08-03 um 17 05 44](https://cloud.githubusercontent.com/assets/709002/17370595/f00012d8-599c-11e6-9666-e37d98313d17.png)

might be somewhat related to #9387

**Comment by Serabe** [comment]
Hello, @spruce.

Can you please reproduce the problem in an [ember-twiddle](https://ember-twiddle.com), please?

I tried but couldn't.

Thank you!

**Comment by Serabe** [comment]
I finally got two different reproductions. The first one by @cibernox can be found [here](https://ember-twiddle.com/#/b0568f1ac5eb2c940f7b3bc56212e88f?openFiles=controllers.application.js%2Ctemplates.components.my-component.hbs) and it raises the error as soon as the application renders.

The other example is a bit more convoluted but shows that a computed property can work if the model does not change. Instructions are found in the [twiddle](https://ember-twiddle.com/e4120c9185fd023fbeb206a086762108?openFiles=controllers.application.js%2C) itself.

**Comment by cibernox** [comment]
To clarify, the application fails as soon as the app renders because I'm passing the `post` model after it has been destroyed by observing his constructor to a component, and components perform an assertion to deperecate `didInitAttrs` that calls `.toString()` on that property.

**Comment by cibernox** [comment]
Another note. I understand that observing the constructor does seem like a weird pattern, given that the constructor can't change, so I'd accept as reasonable bugfix to add an assertion in development to instruct users to not do that.

**Comment by Sinled** [comment]
Also have problem with `this.constructor` `undefined` in `didInitAttrs` depreaction check

but in my case i only pass `model.constructor.modelName` as argument to component

**Comment by cibernox** [comment]
@Sinled Using that in a template is implicitly creating an observer to watch for changes, so it's the same issue.

**Comment by ToMoCoop** [comment]
I've recreated this too in a current project that upgraded, and it was the same cause. I amended the computed property to use the modelName, but not actually listen for the property (as, as you said, it doesn't actually change) and this seems to resolve it for me.

**Comment by urbany** [comment]
This just happened to me after upgrading to ember 2.10.0

replaced:
```js
computed.oneWay('owner.constructor.modelName')
```
by:
```js
computed('owner', function() {
  return this.get('owner.constructor.modelName');
})
```

and it's working now, thanks for the tips @cibernox

**Comment by ngouy** [comment]
how did u resolve it @Sinled ? I have the exact same issue

**Comment by stefanpenner** [comment]
So `modelName` being written (or having been written in the past) to the `constructor` is polluting a global. This ends up being at odds with several performance efforts, such as: https://github.com/emberjs/ember.js/pull/14360

**Comment by PowerP** [comment]
Is this a proper workaround?

```javascript
import DS from 'ember-data';
import Ember from 'ember';

export default {
  name: 'model-className',
  initialize() {
    DS.Model.reopen({
      className: Ember.computed(function() {
        return this.get('constructor.modelName');
      })
    });
  }
};
```

**Comment by pixelhandler** [comment]
@PowerP I think that is a sufficient workaround.

@stefanpenner @cibernox is this still an issue, perhaps we should close; what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
