### ISSUE TITLE
Exception thrown from _fullyScopeQueryParams

### ISSUE THREAD

**Issue by alisdair** [emberjs/ember.js#14010]
Since upgrading to 2.7, our app has been throwing errors in production on some transitions. We have around 600 errors recorded in the past week.

I haven't been able to reproduce these in a development environment, so all I have to go on is a stack trace. But it looks to me like there's something going askew on the path from `transitionTo` to the new `_fullyScopeQueryParams` introduced in #13273 by @raytiley.

The error we're seeing is:

> Cannot use 'in' operator to search for 'type' in undefined

(The exact query param searched for varies.)

Looking at [the definition of this method](https://github.com/emberjs/ember.js/blob/67081fa/packages/ember-routing/lib/system/router.js#L789-L813), the only use of the `in` operator is against its `queryParams` argument, which therefore must somehow be `undefined`.

Backing up the stack trace, [this parameter is set in `transitionTo`](https://github.com/emberjs/ember.js/blob/67081fa/packages/ember-routing/lib/system/router.js#L353-L368), and the only path I can see where it could possibly be undefined is this code:

```js
if (possibleQueryParams && possibleQueryParams.hasOwnProperty('queryParams')) {
  queryParams = args.pop().queryParams;
} else {
  queryParams = {};
}
```

I can't find anything in our app or dependencies that is doing strange things with queryParams in links or transitions, but my knowledge of the router guts ends here.

So while I'm stuck about the root cause, all I can suggest is that we could add a fallback. If the queryParams property of the popped arg isn't an object, default to `{}`, as in the other branch of the if statement.

Would that approach be acceptable? Or can anyone suggest further steps I could take to track down the root cause of the bug?

**Comment by jcbvm** [comment]
Having the same. But from what I can see it's a timing issue because of the inconsistent reproduction case.

**Comment by supersabillon** [comment]
Also having this issue since upgrading to 2.7

**Comment by chriscareycode** [comment]
Having the same issue after upgrading to 2.7.0

**Comment by Frozenfire92** [comment]
Still experiencing this bug in Ember 3.1.2 and not able to come up with a consistent reproduction strategy. As I've had this happen when transitioning between routes that don't have query parameters. (we have a global qp on the application controller, but has never been used when I experience this error

```
Uncaught TypeError: Cannot use 'in' operator to search for 'JWT' in undefined
    at Class._fullyScopeQueryParams (router.js:664)
    at Class._processActiveTransitionQueryParams (router.js:586)
    at Class._doTransition (router.js:556)
    at Class.transitionTo (routing.js:18)
```

which points to this line in `_fullyScopeQueryParams`
```
var presentProp = qp.prop in queryParams && qp.prop || qp.scopedPropertyName in queryParams && qp.scopedPropertyName || qp.urlKey in queryParams && qp.urlKey;
```

**Comment by Frozenfire92** [comment]
Thought of a possible easy fix

change this

https://github.com/emberjs/ember.js/blob/169ad488883f01fdfc3429fe154f4213cf27fa88/packages/ember-routing/lib/system/router.js#L937-L939

to check for `queryParams` existence first

```
(queryParams && qp.prop in queryParams && qp.prop) ||
(queryParams && qp.scopedPropertyName in queryParams && qp.scopedPropertyName) ||
(queryParams && qp.urlKey in queryParams && qp.urlKey);
```
