### ISSUE TITLE
Why use setAll is the most efficient way to do a setEach?

### ISSUE THREAD

**Issue by carlesnunez** [emberjs/ember.js#14022]
Hi, according to ember documentation Ember.enumerable setEach 'is more
    efficient than using other methods defined on this helper':

If we drop down to the ember code we can see a function that uses a vanila JS foreach and set method extracted from ember-metal.

```javascript
/**
    Sets the value on the named property for each member. This is more
    efficient than using other methods defined on this helper. If the object
    implements Ember.Observable, the value will be changed to `set(),` otherwise
    it will be set directly. `null` objects are skipped.
    @method setEach
    @param {String} key The key to set
    @param {Object} value The object to set
    @return {Object} receiver
    @public
  */
  setEach(key, value) {
    return this.forEach(function(item) {
      set(item, key, value);
    });
  },

```

Why this is the most 'efficient' way to do that? Its because we use set as a method instead of do item.set?

Thank you

**Comment by pixelhandler** [comment]
@carlesnunez Thank you for your question. Can you reach out to the ember community via one of the links here - http://emberjs.com/community/

Typically we use github for reporting bugs in Ember.  StackOverflow, the discussion forum, and Slack are all great ways to address questions.  Also using those resources, you'll be more likely to get an answer.

**Comment by stefanpenner** [comment]
this may be a doc error, this is more ergonomic not more efficient.

**Comment by pixelhandler** [comment]
See http://emberjs.com/api/classes/Ember.Enumerable.html#method_setEach as Stefan mentions the wording could be improved

>This is more efficient than using other methods defined on this helper

Perhaps should read

> This is more ergonomic than using other methods defined on this helper
