### ISSUE TITLE
If user presses browser back button while in the popup layer then close the layer

### ISSUE THREAD

**Issue by Shivprasad11** [emberjs/ember.js#14031]
1. Popup layer is open.

2. Hit browser back button.

Current Scenario:

Background page returns to previous page and overlays the popup with the previous data.

Expected Result:

Close the popup layer and stay on the current page.

**Comment by Serabe** [comment]
Hello, @Shivprasad11. I think you have open the issue in the wrong repo. If you need help with your ember project, please, go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

Thank you!
