### ISSUE TITLE
how to create component programmatically? 

### ISSUE THREAD

**Issue by houfeng0923** [emberjs/ember.js#14045]
i need to create component  manually , this is code: 

```
// alert.js 

export default Ember.Component.extend({
});

// alert.hbs 

<div>alert</div>


// other component 

import Alert from './alert';

Alert.create().append(); 

```

but , the child dom that created by alert component only has comment : 

```
<div id="ember592" class="ember-view"><!----></div>
```

what 's wrong ?  i 've no idea ..

------

ember version: 2.7.0

**Comment by locks** [comment]
Hi @houfeng0923, you cannot create components manually. The advise is to instead make a data structure that represents the component and render that.

I am closing this issue as it is not an Ember.js bug report. For questions like these please visit [#-help in Slack](https://embercommunity.slack.com/messages/-help/) or post on [StackOverflow](http://stackoverflow.com/) so we can better help you. Thank oyu!
