### ISSUE TITLE
Properties observed via @each not recalculated

### ISSUE THREAD

**Issue by eddiesholl** [emberjs/ember.js#14049]
I've noticed an issue around computed properties and whether they are considered 'observed'. If properties are included via @each syntax on a computed property definition, this is not sufficient to cause  them to be updated dynamically. If I reference the property explicitly in a template, they become dynamic. This relates to the ember doco on [observers](https://guides.emberjs.com/v2.7.0/object-model/observers/#toc_unconsumed-computed-properties-do-not-trigger-observers):

> If you never get() a computed property, its observers will not fire even if its dependent keys change.

Surely a property referenced as a dependency of another property is considered 'live'? It seems just as valid as a property being a dependency of a template.

As suggested by the doco, I have tried a get() in the init of my model, but no dice.

I have reproduced this behaviour in a standalone app in Ember 2.5.1, the repo is available at https://github.com/eddiesholl/ember-observers-each

This seems like a bug to me, but would be curious to here if there is a reason for this behaviour, and a better path home. There are a few ugly workarounds I have found (like referencing my property inside a hidden div)

**Comment by krisselden** [comment]
Dependent keys have to be something you consume in the computation in order for this to work correctly. if you filter by selected then your @each has to be selected it can't be anything else.
