### ISSUE TITLE
Documentation for render.into incorrect?

### ISSUE THREAD

**Issue by aaroncraigongithub** [emberjs/ember.js#14046]
From the documentation here http://emberjs.com/api/classes/Ember.Route.html#method_render it seems like I should be able to render content into any arbitrary template, for example, given the (admittedly contrived) file structure:
```
templates/
  application.hbs
  error.hbs
  errorpage.hbs
```

it seems I should be able to do the following from any route:

```
renderTemplate() {
  this.render('error', {
    into: 'errorpage',
    outlet: 'error-message'
  });
}
```

However, this results in the error `Assertion Failed: You attempted to render into 'errorpage' but it was not found`

Looking into the code, I find that in `appendLiveRoute()`, the `liveRoutes` parameters only contains the parents of the current route, and therefore any template outside of that path will not be found.

I think the documentation needs to be updated to specify that you can only render into templates that exist in the path between the default root template and the route you are attempting to render into from.

**Comment by Serabe** [comment]
Addressing it.

**Comment by Serabe** [comment]
Thank you for helping us improve the documentation!

**Comment by aaroncraigongithub** [comment]
My pleasure and thanks for the quick update!
