### ISSUE TITLE
What is the best practice of getting element's height in controller

### ISSUE THREAD

**Issue by tmclouisluk** [emberjs/ember.js#14050]
As I have a element which is position:fixed and its top(css) depends on another element's height, what is the best practice of getting that element's height in controller?

Or how can we do it dynamically?

**Comment by Serabe** [comment]
Hello, @tmclouisluk . I am closing this since it is not an Emberjs bug. Please, go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

Thank you!
