### ISSUE TITLE
{{#link-to 'undefinedRoute' prop}}... does not throw an error

### ISSUE THREAD

**Issue by mitchlloyd** [emberjs/ember.js#14064]
As mentioned in [another issue comment](https://github.com/emberjs/ember.js/issues/14052#issuecomment-239603684) it is strange that these first 2 examples throw an error originating from route-recognizer while the third does not:

```hbs
1. {{#link-to 'bogus'}}Error: There is no route named bogus{{/link-to}}
2. {{#link-to 'bogus' 1}}Error: There is no route named bogus{{/link-to}}
3. {{#link-to 'bogus' nothing}}/#{{/link-to}}
```

This is inconsistent and makes it harder to track down incorrect links.

**Comment by Serabe** [comment]
Closing this in favor of #14373 (it contains more information). Thank you for the report!
