### ISSUE TITLE
LinkComponent stuck in "ember-transitioning-in" class and not "active" after transition

### ISSUE THREAD

**Issue by apokinsocha** [emberjs/ember.js#14063]
Not sure yet if this is a bug but after many tests seems that it maybe.
When I attach an observer on the "**active**" computed property while overriding the LinkComponent, transitioning into the route (in my case dynamically) seems to keep the "**ember-transitioning-in**" class and does not change to the "active" class.

If I remove the observer on the "active" attribute, the link is updated correctly with the "active" class.
```
export default Ember.LinkComponent.extend({
    activeChanged: Ember.observer('active', function() { //->removing observer makes it work correctly
       //
    });
});
```

`{{#custom-link-to 'routeName' arg1}}Link{{/custom-link-to}}`

In my case I dynamically change **arg1** after it has been rendered. When I do, the "**ember-transitioning-in**" class sticks.

Currently on Ember version 2.3.
Have a good day.

**Comment by Serabe** [comment]
Can you please provide a quick implementation in an [ember-twiddle](https://ember-twiddle.com/) of what you are trying to do and the side effects?

Thank you!

**Comment by apokinsocha** [comment]
not complete (noted in comments), but very basic implementation here:

https://ember-twiddle.com/b3c3b814628079dc8c6dc07b9e92799d?openFiles=templates.application.hbs%2Ctemplates.components.custom-link.hbs

gist here: https://gist.github.com/apokinsocha/b3c3b814628079dc8c6dc07b9e92799d

From what I can tell, seems with new Ember version will probably work.

**Comment by apokinsocha** [comment]
Solved problem by setting observer on **didRender** event.

**Comment by Serabe** [comment]
Thank you :)
