### ISSUE TITLE
inline if-conditional at handlebars fails with TypeError: options.template is undefined

### ISSUE THREAD

**Issue by wuarmin** [emberjs/ember.js#14074]
I tried to use a simple inline-if-conditional: 
`<option {{if disablePrompt "disabled"}} selected>{{prompt}}</option>`, 
but ran into following error: 
`TypeError: options.template is undefined`

Following Ember Twiddle illustrates the issue:
https://goo.gl/p7PrC9

Does somebody know the reason for this behaviour?

thank you

**Comment by btecu** [comment]
I don't think that's how it works.
It should probably be `<option disabled={{disablePrompt}} selected>{{prompt}}</option>`.

**Comment by rwjblue** [comment]
Confirm. However, Ember should have an assertion if you attempt to use helpers in element space (other than attribute assignment). A better error message would have steered @wuarmin in the right direction.

**Comment by wuarmin** [comment]
thank you. I use materializecss and i.e. the markup of select-element requires the disabling in the manner I showed. Once there's an attribute called disabled (equal if set to true or to false), the option is disabled. 

So there I have to put the whole option-element in a separate if-block.

**Comment by chancancode** [comment]
@wuarmin the snippet @btecu suggested (`<option disabled={{disablePrompt}} selected>{{prompt}}</option>`) would do what you want. We just need to add a better error message, ideally that message would give you that suggestion.

**Comment by chancancode** [comment]
To be extra clear – you would not need to put the whole option-element in a separate if-block.

**Comment by wuarmin** [comment]
Yes you are right. I was mistaken. It works as you said.
