### ISSUE TITLE
ember-template-compiler error on self closing html 

### ISSUE THREAD

**Issue by thefuzz80** [emberjs/ember.js#14076]
Borrowing from issue https://github.com/emberjs/ember.js/issues/12769, self-closing an input tag such as:
`<input type="text" value={{favoriteBand}} onblur={{action "bandDidChange"}}/>`

Will issue a warning:
` File: my-app/components/search-results/template.hbs
The Broccoli Plugin: [TemplateCompiler] failed with:
Error: An unquoted attribute value must be a string or a mustache, preceeded by whitespace or a '=' character, and followed by whitespace or a '>' character (on line 5)
    at assembleAttributeValue (/home/xxx/ember-test/my-app/bower_components/ember/ember-template-compiler.js:23997:27)`

The resolution as suggested in  https://github.com/emberjs/ember.js/issues/12769 still applies by adding a space between `}` and `/`.
Although the `/` is optional on inputs, this is still valid HTML.

It seems from the commit history that this was broken in 2.0-2.4, working in 2.5-2.8-beta, but now breaks once again on 2.9-alpha

@rwjblue asked me to reference these issues/PR's:
* https://github.com/emberjs/ember.js/issues/12769
* https://github.com/tildeio/htmlbars/pull/443

And a twiddle for reproduction:
https://ember-twiddle.com/deb69df508e4cac58ba770b57788e607?numColumns=2&openFiles=controllers.application.js%2Ctemplates.application.hbs

**Comment by rwjblue** [comment]
Thanks for reporting!  This should be fixed by https://github.com/tildeio/glimmer/pull/269.

**Comment by rwjblue** [comment]
The upstream PR has been fixed, and this issue will be resolved once we bump the glimmer-engine version in our `package.json` to something > 0.8.1.

**Comment by thefuzz80** [comment]
Thanks!
