### ISSUE TITLE
Computed property with only an observer doesn't fire observer on change

### ISSUE THREAD

**Issue by aaronbhansen** [emberjs/ember.js#14081]
This is a very distilled example, but I would expect that the computed property would update and then fire the observer if the parameter the computed property is watching changed. 

https://ember-twiddle.com/dbd3db9ba9c4fb1d99f5b2f3f7347d54?openFiles=controllers.application.js%2C

In the real example, we need to have a computed property that has several parameters and results in a true/false scenario. We could move all the properties to the observer, but for performance I only wanted to fire the observer if the computed property actually changed. 

If you reference the computed property other than the observer, it works as expected.

**Comment by krisselden** [comment]
This is as designed, dependent keys are for invalidation, if the CP has never been computed, then it will never fire a change event.

The change events happen when the CP has computed a value and that has become stale.  An example is if you changed the template to render something, your change observer would fire when the template needs to schedule an update after rendering.

Observers are designed to schedule work that consumes a property and that is all they should be used for.

You could consume the CP on your observer and consume the CP on init, but you would make it recompute many times during a single frame.  This is very racy if you don't have the dependency keys correct or things mutate state synchronously on the observer.

**Comment by krisselden** [comment]
@locks can you check if the guides or documentation is clear on this?

**Comment by aaronbhansen** [comment]
Thanks, thats what I assumed once I found out it didn't work. It's a situation I haven't hit before, and so I wanted to double check.
