### ISSUE TITLE
Positional params behave differently with Alpha

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#14080]
It seems that with Release, I can use `get` or `getAttr` to access positional params. But with Alpha I can only use `get`.

[Example](https://ember-twiddle.com/6588d3c1e88eef0bf5df1a3805cd61f8?openFiles=templates.application.hbs%2Ctemplates.components.render-active-modal.hbs
) (Switch to alpha to see difference)

**Comment by krisselden** [comment]
getAttr is not in the API docs, it is private. Why would you use it instead of get?

**Comment by amk221** [comment]
It was mentioned in a blog post once, and I followed that blog post, used `getAttr`. And so, if other people did too, then their apps won't work, I was just bringing this difference in behaviour to to your attention.

**Comment by Serabe** [comment]
Can you please link to that blogpost so that we can addressed that? Thank you.

**Comment by pixelhandler** [comment]
@Serabe @amk221 - when I search the website repo (has source for blog posts) I find no results for `getAttr`, https://github.com/emberjs/website/search?utf8=✓&q=getAttr

**Comment by Serabe** [comment]
Me neither. Closing this. Thank you!

**Comment by amk221** [comment]
http://emberjs.com/blog/2015/05/10/run-up-to-two-oh.html#toc_the-code-attrs-code-property

When I first read that post I started to refer to `this.attrs`. Then, on Slack I got told not to refer `this.attrs` directly, but instead to go via `this.getAttr`. Now, I'm frequently told neither.

I don't want to make this issue about something else, but I still thought it worth mentioning.

**Comment by Serabe** [comment]
Yeah, but as the same blogspot states:

> Beginning with angle-bracket components in Ember 1.13, a component's attributes will be available in this.attrs rather than on the component itself.

And angle-bracket components has not landed yet and when they do, please refer to the up-to-date docs, guides and release blogpost.

Thank you!

**Comment by amk221** [comment]
Roger! But my other point remains...

> The fact that `didReceiveAttrs` and `didUpdateAttrs` are _public_ but we’re 'not supposed' to access `this.attrs` or `this.getAttr` is confusing.
