### ISSUE TITLE
Engines + visit test issue

### ISSUE THREAD

**Issue by asakusuma** [emberjs/ember.js#14086]
I noticed that https://github.com/emberjs/ember.js/pull/14055 if failing only on the prod and jquery suite. I dug further and it would appear that engines + `visit` + `shouldRender: true` causes some issues with the run loop in the tests, but only in prod and jquery extended prototype suites.

`Should not be in a run loop at end of test`
`Ember run should not have scheduled timers at end of test`
`Assertion Failed: You have turned on testing mode, which disabled the run-loop's autorun. You will need to wrap any code with asynchronous side-effects in a run`

Here is a failing PR to repro: https://github.com/emberjs/ember.js/pull/14085

cc @dgeb @krisselden @trentmwillis

**Comment by rwjblue** [comment]
@asakusuma - FWIW, the `eachPackageTests` were completely broken and running no tests until https://github.com/emberjs/ember.js/pull/14084.

**Comment by asakusuma** [comment]
Thanks @rwjblue. This issue was happening both before and after that PR.

I've confirmed locally that this issue happens when `enableoptionalfeatures` is both on and off, which would suggest that the issue is independent of glimmer.

**Comment by rwjblue** [comment]
I believe this is fixed (I closed the related failing test PR #14085).
