### ISSUE TITLE
Deprecate addArrayObserver 

### ISSUE THREAD

**Issue by krisselden** [emberjs/ember.js#14092]
Just a note to remind myself we need to deprecate `addArrayObserver` observer in favor of just observing `[]` changes.

This will make it trivial to make array methods equivalent to `Ember.set` to make the Array extensions off by default and would allow us to make the each proxy lazy, and likely just use the new tag system in glimmer.

Promising valid array indices makes array observers need to synchronously notify, array proxies then need to synchronously notify to ensure backing array will be valid with the indices, or the array proxy needs to snapshot the last view state (which honestly, likely would be more performant than what currently happens).

**Comment by chancancode** [comment]
@tomdale and @krisselden will work on a deprecation RFC for this.

**Comment by pixelhandler** [comment]
@chancancode @krisselden is this still an issue, perhaps we should close; what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
