### ISSUE TITLE
Add acceptance test for `getHandler` returning a Promise

### ISSUE THREAD

**Issue by trentmwillis** [emberjs/ember.js#14099]
Ref: https://github.com/emberjs/ember.js/pull/14087

We should add a test to make sure that everything works properly with `Router#getHandler` returning a Promise to ensure compatibility with Engines. This is currently blocked by figuring the best strategy for dealing with default query params in this scenario.

**Comment by rwjblue** [comment]
Added in https://github.com/emberjs/ember.js/pull/14471
