### ISSUE TITLE
(Glimmer2) Route template not calling namespaced (in sub-directory) component?

### ISSUE THREAD

**Issue by palmergs** [emberjs/ember.js#14103]
Here's the Twiddle (hope I did this correctly). The rendered output should (I think) include the output from both components (my-component.js and testing/my-component.js), but is only rendering the component that is not namespaced in a subdirectory.

https://ember-twiddle.com/ea29543b645076ac7861e47e323caeb1

-----

Below are the notes from my app:

I have a simply component that renders a glyphicon glyph. When placed in the root component directory and referenced from `application.hbs` it displays normally. However, when I place it in a subdirectory and try to reference it from there, it does not display but no errors or warnings are seen in the console log. 

For example:

/app/components/glyph-icon.js

    import Ember from 'ember';
    export default Ember.Component.extend({
      tagName: 'i',
      classNames: [ 'glyphicon'],
      classNameBindings: [ 'iconClass' ],
      iconClass: Ember.computed('icon', function() {
        const icon = this.get('icon');
        return icon ? `glyphicon-${ icon.toString() }` : null;
      })
    });

/app/templates/components/glyph-icon.hbs

    {{yield}}

/app/components/testing/glyph-icon.js

    ... same as above ....

In the `application.hbs` template:

    {{glyph-icon icon="trash"}}

works, but this:

    {{testing.glyph-icon icon="trash"}}

does not render anything.

Final notes: To try out the alpha branch, I had to remove ember-i18n from my package.json. Other than that (and updates to the version numbers in package.json) my app is the same as it was under 2.7.  It could still be a problem in my code however and not a Glimmer2 issue. I'm not that familiar with Ember internals. Thanks for all the hard work.

**Comment by rwjblue** [comment]
In general, I would expect this to work:

```
{{testing/glyph-icon icon="trash"}}
```

But `testing.glyph-icon` only works today because of the some internals to the current rendering engine. The dot syntax you are using is generally reserved for invoking contextual components, and since none is found for `testing.glyph-icon` we treat it the same as if you had any other mustache that was undefined/null.

**Comment by palmergs** [comment]
Thank you. I thought . was the proper way of doing this. Should I migrate all my component references to /?

**Comment by palmergs** [comment]
P.S. can confirm it works correctly as testing/my-component.

**Comment by Serabe** [comment]
Yes.

Closing this. Thank you!
