### ISSUE TITLE
Menu bar messed up on Safari

### ISSUE THREAD

**Issue by Ajeey** [emberjs/ember.js#14111]
Safari Version 8.0 (10600.1.25)

<img width="1440" alt="screen shot 2016-08-22 at 12 40 58 pm" src="https://cloud.githubusercontent.com/assets/1799117/17846429/f6b230d4-6865-11e6-9282-6b7f353a77ad.png">

**Comment by Serabe** [comment]
Can you please move this to [emberjs/website](https://github.com/emberjs/website)?

Thank you!

**Comment by Ajeey** [comment]
Sure, thanks.
