### ISSUE TITLE
Attempted to assign to readonly property on mobile safari

### ISSUE THREAD

**Issue by typeoneerror** [emberjs/ember.js#14124]
I'm noticing errors in our production app for users on iPad (and sometimes iPhone) iOS 8_1_2 and 8_2. I'm guessing it's probably https://github.com/emberjs/ember.js/issues/5606, but I wanted to post the stacktrace here to be sure. 

```
DEBUG: Ember      : 2.4.5
DEBUG: jQuery     : 2.2.4
```

https://gist.github.com/typeoneerror/14dd1e6f357d9721067a21ff18b0d5f3

I was able to repro http://emberjs.jsbin.com/vecuz/1/ on a device/simulator, but I'm unable to repro the error in our app on the any hardware/simulator, so I'm not sure it's the same issue? 

I did some poking around in Ember source and it looks like `REMOVE_USE_STRICT` made an appearance and then was pulled again once Apple fixed this bug (now I see "no use strict")? If I still wanted to support the slim percent of users still on iOS 8, is there an example of using the babel use strict plugin (http://babeljs.io/docs/plugins/transform-strict-mode/) somewhere so I can remove use strict in my ember-cli project, or do I need to make a custom broccoli plugin to remove use strict from vendor files on build?

Thanks for any guidance.

**Comment by Serabe** [comment]
Hello, @typeoneerror. I am closing this since it is not an Emberjs bug. Please, go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

If after removing the `use strict`s this is not yet working, we can reevaluate.

Thank you!
