### ISSUE TITLE
Relax component names must contain a hyphen restriction

### ISSUE THREAD

**Issue by Frozenfire92** [emberjs/ember.js#14120]
`Uncaught Error: Assertion Failed: You cannot use 'input' as a component name. Component names must contain a hyphen.`

I understand the restriction, but what about for built in helper components like `input`

Use case:

I have a component that contains an `{{input}}` but if a flag is set on that component I would like the input to be a different component, such as [{{focus-input}}](https://guides.emberjs.com/v1.10.0/cookbook/user_interface_and_interaction/focusing_a_textfield_after_its_been_inserted/)

My first thought was doing something like this in the template (which led to the error above)

```hbs
{{component (if focus "focus-input" "input") class="someclass" type="text" placeholder=placeholder value=textInput autocomplete="off"}}
```

Is this possible? Or will I have to do the more verbose handlebars conditionals and have each component in either side of the else

**Comment by rwjblue** [comment]
`{{input}}` is a bit special.  It actually switches component definition based on the `type` specified.  If you only need to support `text`, then I would create a component that extends from `Ember.TextField` and use that as your alternate (instead of `{{input}}`).

Something like:

```js
// app/components/non-focus-input.js

export default Ember.TextField.extend()
```

Then usage (based on your snippet above) would be:

```hbs
{{component 
  (if focus "focus-input" "non-focus-input") 
  type="text" 
  value=textInput 
  class="someclass" 
  placeholder=placeholder 
  autocomplete="off"
}}
```

**Comment by Frozenfire92** [comment]
Ok cool, thanks @rwjblue 

Would that be more performant than the following? or about the same

```hbs
{{#if focus}}
  {{focus-input class="someclass" type="text" placeholder=placeholder value=textInput autocomplete="off"}}
{{else}}
  {{input class="someclass" type="text" placeholder=placeholder value=textInput autocomplete="off"}}
{{/if}}
```

**Comment by rwjblue** [comment]
Hard to say for certain without benchmarking, seems like it should be about the same to me though.

**Comment by Frozenfire92** [comment]
Ok thanks, I'm going to close this issue given I don't think there is a straightforward way given the way `{{input}}` is implemented
