### ISSUE TITLE
Passing parameters with value path makes value null.

### ISSUE THREAD

**Issue by vshlos** [emberjs/ember.js#14127]
# About
If you pass parameters into the select "onchange" event with a value path, the first param which should be the value will be null always.

## This works correctly and alerts with the value
```
<select class="form-control" onchange={{action "selectWorkUnit" value="target.value" }}>
    <option value="days">Days</option>
    <option value="weeks">Weeks</option>
    <option value="months">Months</option>
</select>

actions: {
  selectWorkUnit: function (value) {
     alert(value) //will alert the correct value
  }
}
```

## This works incorrectly

```
<select class="form-control" onchange={{action "selectWorkUnit" "test1" "test2" value="target.value" }}>
    <option value="days">Days</option>
    <option value="weeks">Weeks</option>
    <option value="months">Months</option>
</select>


actions: {
  selectWorkUnit: function (value, param1, param2) {
      //value is null
      //param1 is "test2"
      //param2 is the event object
  }
}

```

## Remove the value path

```
<select class="form-control" onchange={{action "selectWorkUnit" "test1" "test2" }}>
    <option value="days">Days</option>
    <option value="weeks">Weeks</option>
    <option value="months">Months</option>
</select>


actions: {
  selectWorkUnit: function (param1, param2, event) {
      //param1 is "test1"
      //param2 is "test2"
      //event is the event object
  }
}

```

**Comment by Serabe** [comment]
Hello, @vshlos:

I think [the documentation](https://guides.emberjs.com/v2.7.0/templates/actions/#toc_modifying-the-action-s-first-parameter) solves the misunderstanding:

> If a `value` option for the `{{action}}` helper is specified, its value will be considered a property path that will be read off of the first parameter of the action.

Therefore, Ember is trying to get `target.value` from "test1" and since there is no property `target`, it is returning `null`.

You can try and rewrite `selectWorkUnit` as:

```js
selectWorkUnit(param1, param2, {target: { value }}) {
  // param1 is "test1"
  // param2 is "test2"
  // value is event.target.value
}
```

Thank you!
