### ISSUE TITLE
ember@1.13.11

### ISSUE THREAD

**Issue by junxtx** [emberjs/ember.js#14142]
Error in the IE browser to troubleshoot complex.
Personally suggest that we should be in ember-debug and ember-prod.
About setAttribute this method should be added "try-catch".
Avoid blocking when you go wrong.

**Comment by locks** [comment]
Hi @junxtx, you didn't include the error log.
Ember 1.13 does not receive updates anymore, you should update to the current LTS (Long-Term Support) release, which is Ember 2.4.

**Comment by junxtx** [comment]
error:IE browser in the ember-debug file 'element.setAttribute', once the null for element, will block the following rendering
thanks，
We take into account the low version of the IE browser, so with a low version

**Comment by pixelhandler** [comment]
@junxtx it would be best to see the error you are referring to (using code). Please try and make a reproduction of your issue. 

Many people use ember-twiddle.com or you can create a repository with an application created using ember-cli.  Please use a current version of Ember.js; v2.4.6 or newer, any prior version is no longer supported.

**Comment by pixelhandler** [comment]
@junxtx also the current release 2.8 is the release candidate for the next LTS release.

**Comment by Serabe** [comment]
Hello, @junxtx. Can you please provide a reproduction of this in a supported version of Ember? If not, I will close this issue.

Thank you!

**Comment by fivetanley** [comment]
Which version of IE are you using?

**Comment by junxtx** [comment]
Ie11 the following version

**Comment by junxtx** [comment]
Error message is an attribute that is not defined as a render, but he blocks the entire render.

**Comment by junxtx** [comment]
This is my modified code from ember-debug and ember-prod.

prototype.setAttribute = function (element, name, value) {
    try{
      element.setAttribute(name, String(value));
    }catch (e){
      console.log(e)
    }
  };

**Comment by rwjblue** [comment]
There are many unknowns here.  We really need a reproduction that shows the issue (JSBin or ember-twiddle.com are pretty easy to get going).

**Comment by rwjblue** [comment]
In general though, it seems very unlikely that we would wrap `setAttribute` in a try/catch block.

**Comment by junxtx** [comment]
Thank you, I understand.

**Comment by Serabe** [comment]
Hello!

Thank you for this report. Given that 1.13 is not being maintained, I'm closing this issue. Please, if you get any problems in the maintained versions open a new issue or reach out in Slack #-help / #dev-issue-triage (if you are not registered, you can use [the Slack-in app](https://ember-community-slackin.herokuapp.com/)) and we can help you getting a reproduction of the bug.

Thank you!
