### ISSUE TITLE
Do we need to warm guidFor?

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#14152]
@krisselden mentioned that we might need to warm `guidFor` after landing https://github.com/emberjs/ember.js/pull/14139

We don't have a lot of details right now, just don't want to lose track of this

**Comment by rwjblue** [comment]
@krisselden - Do you still think this is something we should do?

**Comment by stefanpenner** [comment]
Ya

**Comment by bekzod** [comment]
since `guidFor` using `WeakMap` https://github.com/emberjs/ember.js/blob/master/packages/ember-utils/lib/guid.js#L40 I think this is not valid anymore ?
