### ISSUE TITLE
Move templates cache to the owner

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#14157]
Benefits:
- No more composite key
- Compiled templates goes away when we destroy the owner (engine)

Measure with ember-bench

**Comment by rwjblue** [comment]
@krisselden / @chancancode: Can you help come up with exactly where to store the caches?

A few general ideas that I can think of:

* Create a cache (like `this._compilerCache`) on the environment that returns an object with the caches.
* Create properties on the owner itself for the specific caches needed.
* Register an object into each owner's registry, then look that object up as needed for `_compilerCache`, `_templateCache`, `_definitionCache`.  

In general the third option seems the most straight forward, but I am unsure what  impact it will have on performance.  If that approach seems along the lines of what y'all were thinking, I can try to work up a PR for it and we can measure with ember-bench...

**Comment by hakilebara** [comment]
@rwjblue @chancancode is this still an issue, perhaps we should close?

**Comment by rwjblue** [comment]
Ya, we are using a map with the owner as key already:

https://github.com/emberjs/ember.js/blob/93f4d26b2095876ecf2455298eabae86ce5028ab/packages/%40ember/-internals/glimmer/lib/resolver.ts#L98
