### ISSUE TITLE
Ember.Helper provides `data` as an EmptyObject w/ ember-alpha

### ISSUE THREAD

**Issue by workmanw** [emberjs/ember.js#14161]
Testing out ember-alpha today I discovered that the Ember.Helper is now passed an `EmptyObject`. The consequence of this is that you can no longer do `data.hasOwnProperty` to check if a value was provided. See here: [ember-twiddle#1de4d0cf3e9](https://ember-twiddle.com/1de4d0cf3e9e61427ef2b2302ef9879c?openFiles=helpers.x-foo.js%2C) (if you change the dep to ember.js/beta you'll see the helper works).

This actually caused an issue with ember-i18n's helper, see: [ember-i18n#helper](https://github.com/jamesarosen/ember-i18n/blob/master/addon/helper.js#L14) and [ember-i18n#service](https://github.com/jamesarosen/ember-i18n/blob/master/addon/services/i18n.js#L25).

We could easily work around this in ember-i18n, but I wanted to call it out because it seems likely other helpers may try to use `hasOwnProperty` to determine which key/values were provided.

**Comment by rwjblue** [comment]
Yes, thanks for calling this out (also, FWIW, ember-glimmer is enabled on canary now also so it is not just the alpha).

I am unsure the right path here.  The internals are actually using `Object.create(null)` type objects for the hash specifically to avoid requiring a `hasOwnProperty` check (and avoiding polluting the `hash`). I'm not sure if we should change this...

**Comment by workmanw** [comment]
@rwjblue So I looked through quite a few addons and it looks like a vast majority of helpers I saw aren't even using `namedArgs`. Let's just close this issue and fix it on the ember-i18n side.

**Comment by rwjblue** [comment]
@workmanw - OK, but we'll keep this in mind if it seems like a common issue..

**Comment by zzarcon** [comment]
Having similar issue with this on `2.9.0-beta.5`, for me the problem is that I'm trying to delete a key of the EmptyObject using the `delete` operator `delete hash.key` and that trows an error:

`Cannot delete property 'key' of [object Object]` 

I fixed it just doing

```javascript
const obj = Ember.merge({}, hash)
delete obj.key;
````

I'm not sure if more people will expect this to work, probably yes?

**Comment by rwjblue** [comment]
The hash is a frozen object in 2.9+, that is why the delete doesn't work.  If you are going manipulate the hash/params objects you need to copy them first (as you did with `Ember.merge` above).

**Comment by zzarcon** [comment]
Ok cool, then was just I didn't know about that was the expected behaviour. Thanks for the explanation!
