### ISSUE TITLE
Detailed API Documentation Review: ember-htmlbars -> ember-glimmer

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#14166]
All of the functionality of our templating system has been migrated from ember-htmlbars to ember-glimmer package.  We need to ensure that we have not lost significant documentation coverage.

At a minimum we need to review the following files in ember-htmlbars to confirm that all documentation contained within them has been migrated to the ember-glimmer package.

- [x] `packages/ember-htmlbars/lib/component.js`
- [x] `packages/ember-htmlbars/lib/helper.js`
- [x] `packages/ember-htmlbars/lib/helpers/-html-safe.js`
- [x] `packages/ember-htmlbars/lib/helpers/concat.js`
- [x] `packages/ember-htmlbars/lib/helpers/each-in.js`
- [x] `packages/ember-htmlbars/lib/helpers/each.js`
- [x] `packages/ember-htmlbars/lib/helpers/hash.js`
- [x] `packages/ember-htmlbars/lib/helpers/if_unless.js`
- [x] `packages/ember-htmlbars/lib/helpers/log.js`
- [x] `packages/ember-htmlbars/lib/helpers/query-params.js`
- [x] `packages/ember-htmlbars/lib/helpers/with.js`
- [x] `packages/ember-htmlbars/lib/helpers.js`
- [x] `packages/ember-htmlbars/lib/hooks/bind-local.js`
- [x] `packages/ember-htmlbars/lib/hooks/bind-self.js`
- [x] `packages/ember-htmlbars/lib/hooks/bind-shadow-scope.js`
- [x] `packages/ember-htmlbars/lib/hooks/classify.js`
- [x] `packages/ember-htmlbars/lib/hooks/cleanup-render-node.js`
- [x] `packages/ember-htmlbars/lib/hooks/concat.js`
- [x] `packages/ember-htmlbars/lib/hooks/destroy-render-node.js`
- [x] `packages/ember-htmlbars/lib/hooks/element.js`
- [x] `packages/ember-htmlbars/lib/hooks/get-child.js`
- [x] `packages/ember-htmlbars/lib/hooks/get-root.js`
- [x] `packages/ember-htmlbars/lib/hooks/get-value.js`
- [x] `packages/ember-htmlbars/lib/hooks/link-render-node.js`
- [x] `packages/ember-htmlbars/lib/hooks/subexpr.js`
- [x] `packages/ember-htmlbars/lib/hooks/update-self.js`
- [x] `packages/ember-htmlbars/lib/index.js`
- [x] `packages/ember-htmlbars/lib/keywords/action.js`
- [x] `packages/ember-htmlbars/lib/keywords/closure-component.js`
- [x] `packages/ember-htmlbars/lib/keywords/component.js`
- [x] `packages/ember-htmlbars/lib/keywords/debugger.js`
- [x] `packages/ember-htmlbars/lib/keywords/get.js`
- [x] `packages/ember-htmlbars/lib/keywords/input.js`
- [x] `packages/ember-htmlbars/lib/keywords/mount.js`
- [x] `packages/ember-htmlbars/lib/keywords/mut.js`
- [x] `packages/ember-htmlbars/lib/keywords/outlet.js`
- [x] `packages/ember-htmlbars/lib/keywords/partial.js`
- [x] `packages/ember-htmlbars/lib/keywords/readonly.js`
- [x] `packages/ember-htmlbars/lib/keywords/render.js`
- [x] `packages/ember-htmlbars/lib/keywords/textarea.js`
- [x] `packages/ember-htmlbars/lib/keywords/unbound.js`
- [x] `packages/ember-htmlbars/lib/keywords/with.js`
- [x] `packages/ember-htmlbars/lib/keywords.js`
- [x] `packages/ember-htmlbars/lib/streams/class_name_binding.js`
- [x] `packages/ember-htmlbars/lib/streams/dependency.js`
- [x] `packages/ember-htmlbars/lib/streams/stream.js`
- [x] `packages/ember-htmlbars/lib/streams/subscriber.js`
- [x] `packages/ember-htmlbars/lib/streams/utils.js`
- [x] `packages/ember-htmlbars/lib/system/instrumentation-support.js`
- [x] `packages/ember-htmlbars/lib/system/lookup-helper.js`
- [x] `packages/ember-htmlbars/lib/utils/is-component.js`
- [x] `packages/ember-htmlbars/lib/views/outlet.js`

More specifically, we need to do the following for each file listed above:

* Identify if the file contains any API documention (generally identified by the presence of a comment block with YUIDoc syntax).
* Check if the documentation is present somewhere within the `ember-glimmer` package.  If not, submit a pull request with the missing documentation (linking back here).  If it is, comment below so that we can mark the file complete.

@emberjs/learning-team-managers - Can you help coordinate this effort?

**Comment by rwjblue** [comment]
You can find the most recent version of the `ember-htmlbars` package (prior to removal) in the [backup/canary-2-9-with-htmlbars](https://github.com/emberjs/ember.js/tree/backup/canary-2-9-with-htmlbars/packages/ember-htmlbars) branch.

**Comment by toddjordan** [comment]
I can provide some help here... @rwjblue you mean "confirm that the documentation _is_ present", right?

**Comment by rwjblue** [comment]
LOL, yes. I mean that if it is already present we check the box next to the file name.  If it is not present we submit a PR adding it *then* check the box.

**Comment by krisselden** [comment]
Should we use ember-glimmer instead of ember-templates to document things?

Also, should we remap the global export for Ember.HTMLBars? to Ember.Template?

**Comment by chancancode** [comment]
@krisselden `ember-templates` has been removed on master, so I think it's a yes for the first question

**Comment by rwjblue** [comment]
@chancancode - The usage of `Ember.Templates` in the docs predates the presence of an `ember-templates` package in the codebase.

**Comment by toddjordan** [comment]
Working through `html-bars/lib/component.js`, `html-bars/lib/helper.js`, and `html-bars/lib/helpers/*` today.

**Comment by toddjordan** [comment]
took on the rest of these as well in pr #14200 

There was a few I wasn't sure about.  Will list these after I do a conflict resolve

**Comment by toddjordan** [comment]
pr #14200 should now address remaining checkboxes

**Comment by acorncom** [comment]
@toddjordan Should we close this issue now?

**Comment by toddjordan** [comment]
Think so if ok with @rwjblue

**Comment by rwjblue** [comment]
Sorry for the delay here, thanks for all the hard work here!
