### ISSUE TITLE
Remove ember-templates package.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#14165]
This package served as a way to absorb the differences between the ember-glimmer and ember-htmlbars import locations in the rest of the system.  As of https://github.com/emberjs/ember.js/pull/14163 `ember-htmlbars` is removed making this layer of indirection not useful/needed.  Removing it will make things much clearer throughout the rest of the system and reduce wasted bytes for the reexport modules.

**Comment by chancancode** [comment]
I believe this is done
