### ISSUE TITLE
Expand testing of Glimmer mount syntax.

### ISSUE THREAD

**Issue by dgeb** [emberjs/ember.js#14160]
From https://github.com/emberjs/ember.js/pull/14154#issuecomment-243339339

> @dgeb would you be able to circle back to this sometime this week to add more test? Things like looking up components, partials, helpers, etc; test that we have looked up/provided right scope (application controller); ensure we teardown correctly; what happens if you have routes, etc.

**Comment by rwjblue** [comment]
There was an existing test (just recently deleted) in the ember-htmlbars package ([see here](https://github.com/emberjs/ember.js/blob/backup/canary-2-9-with-htmlbars/packages/ember-htmlbars/tests/integration/mount_test.js)). @chancancode started porting this to the ember-glimmer infrastructure [in this branch](https://github.com/emberjs/ember.js/tree/port-mount-tests), but ran out of time to complete.  

@dgeb - This may help you (at the very least as a guide to some of the things to test).

**Comment by rwjblue** [comment]
@dgeb - Any progress here?

**Comment by dgeb** [comment]
@rwjblue - Sorry for the delays. Will move it up my list.
