### ISSUE TITLE
Deprecate usage of `targetObject`.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#14168]
We currently support having a `targetObject` property on components, but as of 2.9 we no longer use this property on components internally.

We should deprecate having a `targetObject` [here](https://github.com/emberjs/ember.js/blob/8112e7112ddabf871044fdce1a893d78e6852d3f/packages/ember-runtime/lib/mixins/target_action_support.js#L140-L141).

**Comment by Cryrivers** [comment]
Thanks for the clarification, although I wasn't able to explain clearly on Slack. :)

Basically we used targetObject in a component to get the controller that it belongs to. (Say you need to call a function in the controller, from your components. I wouldn't suggest to do so since Ember 2.3 introduced closure actions.)

However, as of 2.9, targetObject no longer exists. I tried with this._targetObject but it has a different behavior compared with the original targetObject. In 2.9, _targetObject in a component points to its parent component, if any, instead of the controller it belongs to.

So I believe this deprecation is needed and hopefully can help you if you are running into targetObject problem in 2.9

**Comment by rwjblue** [comment]
This issue represents deprecating having a `targetObject` specified (either via template invocation or in your component definition). The `targetObject` property on `Ember.Component` was intended as a "write only API" (as in you are supposed to define your own if you'd like, but not try to read from the default one). We certainly never intended for `this.get('targetObject')` to be used. 

> Basically we used targetObject in a component to get the controller that it belongs to.

It sounds to me like you were using `this.get('targetObject')`, is that right?

> I wouldn't suggest to do so since Ember 2.3 introduced closure actions.

FWIW, Ember 1.13 introduced closure actions.

@Cryrivers - Can you give me an example JSBin or ember-twiddle to show the behavior you are discussing so we can better understand if we need to deprecate *reading* from `targetObject` as well as specifying it?

**Comment by Cryrivers** [comment]
@rwjblue https://ember-twiddle.com/e2f017a62fb16c2163d267d49e2d0ed9?openFiles=components.component-b.js%2C

You can open the console and switch between Ember `2.7.0` and `canary`.

In `2.7.0`, targetObject points to `ApplicationController` whereas it points to its parent component in `canary`.

**Comment by rwjblue** [comment]
@Cryrivers - Thanks for working through this with me.  You have definitely identified a bug (action bubbling from within a component's block does not work correctly on canary), but I'm still not 100% sure if we should add a `targetObject` property back that issues a deprecation.

**Comment by rwjblue** [comment]
Created https://github.com/emberjs/ember.js/issues/14216 to track the block scoping issue in canary/2.9.

**Comment by jcope2013** [comment]
also using targetObject as well in a similar use case, is the conclusion that targetObject will be no longer available in >= 2.9?

**Comment by rwjblue** [comment]
`targetObject` is not available to read from in 2.9 (AFAIK that style of use was not something that we intended to support generally speaking), but if your components have a `targetObject` it will be respected. 

We could add it back for reading with a deprecation, but I would rather avoid that if possible. Hopefully others chime in that hit the issue so we can gauge impact...

**Comment by Dhaulagiri** [comment]
I found this broke for us in 2.8 but using `_targetObject` instead seemed to give synonymous behavior

**Comment by fooey** [comment]
We ran into this too, but it was fairly easy to fix once we figured out what was wrong.

**Comment by rwjblue** [comment]
We discussed this during the last core team meeting, and decided that based on community usage of reading the `targetObject` property we will bring it back with a deprecation (listed as `until: 2.12.0`) for both setting and retrieving.

**Comment by MiguelMadero** [comment]
Is the idea to use `target` instead? 

In Ember 2.7 we used to be able to read and set targetObject. It's gone in 2.9, but using _targetObject worked. While both are private they worked. By reading this, if I understood correctly the idea is to use `target` instead, but that didn't work in the way I was using it on https://github.com/toranb/ember-cli-hot-loader/pull/34

We have inside a component wrapper something like:

```
{{#component wrappedComponentName _targetObject =_targetObject 
```

I understand based on the deprecation warning that we were supposed to use `target` instead, however that didn't work either

```
{{#component wrappedComponentName target =target 
```

What worked across versions was, but that's supposed to be deprecated is reading from `_targetObject` and setting `targetObject`: 

```
{{#component wrappedComponentName ${positionalParams} ${attributesMap} targetObject =_targetObject 
```
