### ISSUE TITLE
LTS Latest Build is Incorrect

### ISSUE THREAD

**Issue by blimmer** [emberjs/ember.js#14162]
It's not in the main [changelog](https://github.com/emberjs/ember.js/blob/master/CHANGELOG.md) and the [website build page](http://emberjs.com/builds/) indicates that 2.4.5 is the latest, not 2.4.6.

![](https://i.imgur.com/q3Bd7DR.png)

**Comment by rwjblue** [comment]
Thanks for reporting, we'll get it fixed
