### ISSUE TITLE
[Glimmer 2] <option value="{{null}}"> renders as <option value="true">

### ISSUE THREAD

**Issue by nragaz** [emberjs/ember.js#14181]
e.g.
https://ember-twiddle.com/0b01e3d68f0f0287d28eab766d16ea21

This appears to be the same issue as https://github.com/emberjs/ember.js/issues/14001.

The quotes around the attribute are converting null to a blank string; and then `normalizePropertyValue` is coercing the blank string to "true". 

I don't really understand why that behaviour is ever desirable, given that "" is falsy.

**Comment by rwjblue** [comment]
Fixed by #14315.
