### ISSUE TITLE
TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#14187]
I'm seeing the following error when testing alpha or canary on one of my work apps that is using the `ember-page-title` addon. Since the error originates inside the `set()` function I'm assuming this is a bug in Ember, not in the addon.

```
Uncaught TypeError: Cannot convert object to primitive value
toString	@	ember.debug.js:21290
set	@	ember.debug.js:19693
push	@	page-title-list.js:64
compute	@	page-title.js:26
```

**Comment by rwjblue** [comment]
@turbo87 - Steps to reproduce? Does the ember-page-title addons test suite demonstrate the issue?

**Comment by Turbo87** [comment]
```
ember new canary-bug
cd canary-bug
ember install ember-page-title
bower i -S ember#canary
echo '{{title "foobar" prepend=true}}' > app/templates/application.hbs
ember s
```

if you remove the `prepend=true` the error changes to the following, which might be unrelated but can also be reproduced with their test suite on canary:

```
Uncaught TypeError: Can't add property id, object is not extensible
compute	@	page-title.js:24
compute	@	ember.debug.js:12902
value	@	ember.debug.js:12537
```

**Comment by Turbo87** [comment]
my guess is that the problem comes from reusing the `hash` argument in the `compute` method of the helper and trying to mutate it (see https://github.com/tim-evans/ember-page-title/blob/master/addon/helpers/page-title.js#L19-L23).

the problem on the Ember side however seems to be that the new `hash` impl in canary doesn't work with `toString()`, although I haven't verified that theory.

**Comment by rwjblue** [comment]
Hash arg is an Object.create(null) and doesn't have any method

**Comment by rwjblue** [comment]
Ya, definitely something going on.  However, we do know that `[Object.create(null)].toString()` fails with the message you describe.

Steps to reproduce:

```js
let array = [];
let hash = Object.create(null);
array.push(hash);
array.toString();
```

[Demo using Ember](https://jsbin.com/subigo/edit?js,output)
[Demo using plain JS](http://jsbin.com/webumup/edit?js,output)

---

I still think there is more going on here though.  Will dig a bit further...

**Comment by rwjblue** [comment]
Initial issue fixed upstream in ember-page-title (was related to helper mutation).
