### ISSUE TITLE
[Glimmer 2] didDestroyElement needs to be called during component teardown

### ISSUE THREAD

**Issue by mitchlloyd** [emberjs/ember.js#14185]
It seems there is a bug in current canary where `didDestroyElement` is not being called on teardown. Funny enough when I search for `didDestroyElement` in this repo I get no hits :)

@rwjblue Indicated that a similar issue may have been fixed earlier here and just need to be re-applied.

https://github.com/emberjs/ember.js/pull/14159/files

**Comment by rwjblue** [comment]
Thanks for reporting!  Yeah, we need to port forward the tests added in #14159 (which would be a good failing test for this).  Once we have the failing tests, we need to add a `view.trigger('didDestroyElement')` [around here](https://github.com/emberjs/ember.js/blob/6fd9afe2631ee5a1861d80be03bbd46a8b178703/packages/ember-glimmer/lib/renderer.js#L193-L219).  I need to check with @krisselden to see if `didDestroyElement` is supposed to be fired before `view.destroy()` is called though.

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/14227.
