### ISSUE TITLE
Error in findRecord when CORS 

### ISSUE THREAD

**Issue by dihar** [emberjs/ember.js#14188]
Hello!
I have the problem with CORS request by RESTAdapter. 

When I use `store.findAll` or `store.query` or another requests, which expect several parameters, it's all good: in devTools network showed TWO request OPTION and GET to api/posts/ :

<img width="685" alt="screen shot 2016-09-02 at 13 36 07" src="https://cloud.githubusercontent.com/assets/12913462/18201331/4159d4f2-7112-11e6-95f7-8715b30d43e7.png">
<img width="854" alt="screen shot 2016-09-02 at 13 36 42" src="https://cloud.githubusercontent.com/assets/12913462/18201350/569c5af6-7112-11e6-8829-2e251c6af58b.png">
<img width="1140" alt="screen shot 2016-09-02 at 13 37 16" src="https://cloud.githubusercontent.com/assets/12913462/18201371/665d4478-7112-11e6-9266-28f4552d1855.png">

But, when I try request one record by `store.findRecord`(GET posts/:id), CORS do TWO
 requests OPTION and GET, adapter expect in first request status 200 and JSON, but as first request is OPTION with status 200 and empty body, it's throw exception 
```console
WARNING: Encountered "id" in payload, but no model was found for model name "id" (resolved model name using i100g@serializer:application:.modelNameFromPayloadKey("id"))
WARNING: Encountered "media" in payload, but no model was found for model name "medium" (resolved model name using i100g@serializer:application:.modelNameFromPayloadKey("media"))
WARNING: Encountered "weight" in payload, but no model was found for model name "weight" (resolved model name using i100g@serializer:application:.modelNameFromPayloadKey("weight"))
WARNING: Encountered "liked" in payload, but no model was found for model name "liked" (resolved model name using i100g@serializer:application:.modelNameFromPayloadKey("liked"))
WARNING: Encountered "comments" in payload, but no model was found for model name "comment" (resolved model name using i100g@serializer:application:.modelNameFromPayloadKey("comments"))
...
TypeError: Cannot read property '_internalModel' of null
``` 

In devTools: 
<img width="1368" alt="screen shot 2016-09-02 at 13 31 31" src="https://cloud.githubusercontent.com/assets/12913462/18201233/9d721a48-7111-11e6-9158-fc13d80426af.png">

First request: 
<img width="761" alt="screen shot 2016-09-02 at 13 33 42" src="https://cloud.githubusercontent.com/assets/12913462/18201275/e9b19d48-7111-11e6-801b-e3b421871ff2.png">

Second request: 
<img width="850" alt="screen shot 2016-09-02 at 13 34 45" src="https://cloud.githubusercontent.com/assets/12913462/18201297/0ccd6014-7112-11e6-919d-e979530de2c9.png">
<img width="923" alt="screen shot 2016-09-02 at 13 35 16" src="https://cloud.githubusercontent.com/assets/12913462/18201307/22533b0c-7112-11e6-9555-5c1e5cb2a13b.png">

However server return data, but adapter doesn't see it and throw exception. 
I think have to add CORS parameter, which if do OPTION request must wait GET request.

Thanks!

**Comment by Serabe** [comment]
Hello, @dihar:

Can you please move this issue to [emberjs/data](https://github.com/emberjs/data) to better address it?

Thank you!

**Comment by btecu** [comment]
The problem it's your api endpoint for `/posts/{id}`.
You're returning just the content of the post, but it should be wrapped with `post`:
```
{
  post: {
    id: 1423,
    user_name: "sphex",
    ...
  }
}
```

**Comment by dihar** [comment]
@Serabe , sorry, but how I can do this?

**Comment by dihar** [comment]
@btecu , thanks! I asked developers fix api and check again this problem.

**Comment by rwjblue** [comment]
I'm going to close this here, if you believe it is still an issue in Ember Data please open a new issue in [emberjs/data](https://github.com/emberjs/data/issues/new).
