### ISSUE TITLE
Component rendering mutates module meta

### ISSUE THREAD

**Issue by trentmwillis** [emberjs/ember.js#14192]
We're attempting to upgrade our application to 2.7.2 and ran into an odd issue. Brief backstory, we rely on the `meta.moduleName` property from the compiled HTMLBars template to do some of our lookups for localization.

While attempting the upgrade, there are some tests that we have that are now failing after being run in a certain order. After a lot of debugging, the root issue is that the `meta.moduleName` property is being mutated which causes the value to be incorrect when we do our lookup for the translation.

The offending line of code seems to be this: https://github.com/emberjs/ember.js/blob/v2.7.2/packages/ember-htmlbars/lib/hooks/component.js#L62

I haven't narrowed down the exact circumstances under which this occurs, but in some cases it appears `env.meta` is the same reference as the `meta` property from a templates AMD module. Thus, if `templateMeta.moduleName` is used, the module is then mutated permanently.

cc @asakusuma @zackthehuman

**Comment by asakusuma** [comment]
@krisselden who should this issue be assigned to?

**Comment by pixelhandler** [comment]
@krisselden @rwjblue this can be closed now, right?

**Comment by rwjblue** [comment]
Ya, was fixed in 2.7.3 and 2.8.0
