### ISSUE TITLE
Recent change causes `Cannot set property 'EXTEND_PROTOTYPES' of undefined`

### ISSUE THREAD

**Issue by mitchlloyd** [emberjs/ember.js#14206]
When building the latest version of a project with Ember Canary as of today (afc6fced83e994eb372f8f71da3201d2f4812651) I get the error:

```
Cannot set property 'EXTEND_PROTOTYPES' of undefined
```

From the ember-cli-htmlbars package.  This works going back to Canary from 2 days ago (canary 29b2cc58f2a81ef566e677d05d2dbcb242ffab37).

**Comment by rwjblue** [comment]
Thanks @mitchlloyd, I think #14205 will fix. Can you confirm (I submitted on mobile in response to this error being reported in slack)?

**Comment by rwjblue** [comment]
Ok, just landed that PR. Updated build should be up in ~ 15 minutes, can you test and let me know if that resolves? I'll be back at a computer soon to jump on any residual issues...

**Comment by mitchlloyd** [comment]
Confirm, building with Canary now works again. Thanks!
