### ISSUE TITLE
link-to not working

### ISSUE THREAD

**Issue by mxrguspxrt** [emberjs/ember.js#14212]
I have 

`link-to 'page.new' 'Create a new page'`

That generates me

`<a id="ember450" href="/page/new" class="ember-view">Create a new page</a>`

But on click, link does not open. With right mouse click, open in new tab, works ok.

No debug log in console. This is so sad, my heart bleeds. :(

**Comment by tinyweasel** [comment]
Did you find a fix for this? It's happening to me too.

**Comment by mxrguspxrt** [comment]
I think, the issue was that Javascript in itself was broken - I tried to replace all page HTML, including root "<HTML id="all_page">" with new HTML - altought it worked (all page body HTML was rendered from Ember template) - but then, for some reason, targeting ember actions broken down.

If you have not broken the JavaScript (load order and rendering part is ok), try not loading data in routes, and as simple as possible page rendering and check if there links work ok. If not, just do it from scratch. :)

**Comment by shreyas098** [comment]
Try adding model.id as a param
