### ISSUE TITLE
[Glimmer 2] [Fastboot] `{{action 'foo'}}` causes error when rendering with Fastboot

### ISSUE THREAD

**Issue by bantic** [emberjs/ember.js#14220]
Using an action in a template (e.g. `<button {{action 'foo'}}>...`) with ember canary (as of d19df96) and ember-cli-fastboot (1.0.0-beta.8) throws the error `Cannot read property 'setAttribute' of undefined`.

This originates from the [`dom.setAttribute` line in `ActionModifierManager#install`](https://github.com/emberjs/ember.js/blob/504a6e05d1d895e3f1cb9552e414ae865c12380b/packages/ember-glimmer/lib/modifiers/action.js#L209). (Note that the `manager#install` method is called by Glimmer's `ModifierOpcode#evaluate` [here](https://github.com/tildeio/glimmer/blob/c0a92795b2df68bfed674683c2ae9c3d2b633835/packages/glimmer-runtime/lib/compiled/opcodes/dom.ts#L414).)

The original source of that `dom` variable being undefined appears to be due to [`setupRegistry` skipping the injection of `updateOperations`](https://github.com/emberjs/ember.js/blob/504a6e05d1d895e3f1cb9552e414ae865c12380b/packages/ember-glimmer/lib/setup-registry.js#L26-L28) when `environment.hasDOM` is false.

I'm not sure of the other ramifications of allowing that `updateOperations` to be injected, but when it is injected (when the conditional on `hasDOM` is removed) the Fastboot render works.

(Note that in order to test this you need to comment-out the two [dom-helper-patches in ember-cli-fastboot here](https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/app/initializers/fastboot/dom-helper-patches.js#L7-L15), see https://github.com/ember-fastboot/ember-cli-fastboot/issues/255).

**Comment by chancancode** [comment]
@wycats @chadhietala can you take a look? I believe the idea is that modifiers should not run on the server

**Comment by chadhietala** [comment]
Taking a look it looks like we were passing `updatingOperations` to `install` when we actually want tree construction. Will test locally.

**Comment by rwjblue** [comment]
The proper solution landed in https://github.com/emberjs/ember.js/pull/14232.
