### ISSUE TITLE
Does ember 2.9.0-beta.1 work with the inline hbs helper?

### ISSUE THREAD

**Issue by toranb** [emberjs/ember.js#14228]
I noticed this today when I was playing w/ the latest alpha (and now the beta.1)

`Template.create is not a function`

This was using the inline hbs helper inside a component.js file ... curious if anyone else has seen this or not :)

**Comment by rwjblue** [comment]
Should work fine. Make sure to use `bower install --save ember#alpha` or `bower install --save ember#canary` to get the latest set of changes, and also ensure that you are using the latest versions of `ember-cli-htmlbars` and `ember-cli-babel` (there were some caching bugs that caused errors if you did a build with one version then change Ember versions and do another build).

If all of those things do not help, please throw up a repo that we can poke at...

**Comment by toranb** [comment]
ah, likely I missedthe cli-babel and cli-htmlbars requirements :)

**Comment by toranb** [comment]
@rwjblue what should this look like today (now that 2.9.0-beta.1 is out) ? Also I installed ember-cli-htmlbars and ember-cli-babel (latest) as you suggested but I still get the same issue (just wanted to see if I can follow any other readme to label this "user error (likely)" or 2.9.0 error

thank you in advance!

**Comment by toranb** [comment]
![screen shot 2016-09-08 at 8 00 46 pm](https://cloud.githubusercontent.com/assets/147411/18372050/fadc8fb4-75fe-11e6-8e9c-c86199639334.png)

**Comment by rwjblue** [comment]
My guess is that you have layout as a CP, I do not think that is supported (and I believe it triggered deprecations in earlier versions).

**Comment by rwjblue** [comment]
Please provide a reproduction so we can try to help...

**Comment by toranb** [comment]
@rwjblue honestly each component in this app is a single file w/ this for `layout`

```js
import Ember from 'ember';
import hbs from 'htmlbars-inline-precompile';

export default Ember.Component.extend({
    layout: hbs`
      {{yield}}
    `
});
```

I'll see if I can get this into a twiddle or something simple that shows the bug in a silo. Thanks for the help on this Robert!

**Comment by rwjblue** [comment]
@toranb - Ya, that inline precompilation should be fine. Something is causing the `Template` var in your screenshot to be a `ComputedProperty` descriptor (which is why I was guessing something had `layout: Ember.computed(...)`).  Just above that part of the stack you see `templateFor` and/or `getTemplate`, it should tell you the template name that is being looked up which may help...

**Comment by rwjblue** [comment]
@toranb - Any luck on a repro for this?

**Comment by toranb** [comment]
@rwjblue I've got a private repo that I could share w/ you or any core member but my twiddle isn't showing this yet and it's darn close to the private repo. Does a change in the twiddle file to 2.9.0-beta.1 work as I assume it does?

**Comment by pixelhandler** [comment]
@toranb gitlab has free private repos you could share that and email invites

**Comment by toranb** [comment]
@rwjblue @pixelhandler I decided to throw the entire thing up on github until we nail down the regression. I pulled down the non essential stuff and this should be fine until we can determine root cause :)

Thanks again for the help on this!

https://github.com/toranb/glimmertwo/blob/master/bower.json#L4

**Comment by toranb** [comment]
@rwjblue looks like the hot reloader was using a CP for layout :( so it's not glimmer 2 friendly at the moment. I'll see what we can come up w/ that's both 2.8 and 2.9 friendly here. Thanks again for offering to look this over before I knew what caused the break :)

![screen shot 2016-09-10 at 6 56 48 am](https://cloud.githubusercontent.com/assets/147411/18410302/d6eda82e-7723-11e6-995f-f1000940006c.png)
