### ISSUE TITLE
Engine routes deactivated after destruction

### ISSUE THREAD

**Issue by trentmwillis** [emberjs/ember.js#14234]
In 2.8.0, there was a change introduced to [the order of teardown when Engines are involved](https://github.com/emberjs/ember.js/commit/447df33c4db30c475a08415196dbb7012f08cc07). The change in question seems to have fixed another issue, but causes routes in Engines to be destroyed prior to their `deactivate` hook being run (during the Router's `reset`).

This means that if you do something such as `set` a property on the Route during `deactivate`, then errors will propagate in Acceptance tests.

Unsure what the proper fix is here. Seems like maybe only the views from the Engines should be torn down prior to resetting the Router.

(Here's [the prior implementation](https://github.com/dgeb/ember-engines/blob/v0.2/addon/-private/router-ext.js#L129) from the ember-engines addon.)

cc @asakusuma @krisselden

**Comment by rwjblue** [comment]
@trentmwillis - Can you work up a failing test (best harness ATM for this is [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/tests/integration/application/engine-test.js))?

**Comment by trentmwillis** [comment]
@rwjblue reproduction added in #14237.

**Comment by trentmwillis** [comment]
@rwjblue / @asakusuma do you know if the original issue:

> Ensure that engines are destroyed _before_ top-level views so that top-level views are not re-instantiated during engine teardown.

Had tests to catch a regression? Because I looked into fixing this and just switching the order back seems to pass without failing any tests.

**Comment by rwjblue** [comment]
@trentmwillis - Yeah, I think the `isDestroying` guard added in https://github.com/emberjs/ember.js/pull/14123 actually fixed the regression (just before the PR changing the order landed).

**Comment by trentmwillis** [comment]
@rwjblue okay, so do you think switching the order back seems like the proper solution? If so, I'll update my PR with the failing test.

**Comment by rwjblue** [comment]
@trentmwillis - Yeah, lets switch it back and confirm both your regression tests pass.

**Comment by trentmwillis** [comment]
Fixed via #14237. Tested against the latest release build.
