### ISSUE TITLE
[Ember 2.9-beta1] Bug when transitioning from application/index route on boot

### ISSUE THREAD

**Issue by piotrpalek** [emberjs/ember.js#14248]
Hey I was trying out Ember 2.9 (wanted to try out glimmer) and had a case where I was transitioning in the "application/index route" on the `activate` hook (so basically right after booting the app). After trying to boot the app I got this error: `Uncaught TypeError: Cannot read property 'render' of null`.

Seems there is a bug which I was able to reproduce [in this twiddle](https://ember-twiddle.com/a5a8606ae4e0dc9b5aa527820c1d9edc?openFiles=templates.test-page.hbs%2C&route=%2Ftest-page).

**Comment by pixelhandler** [comment]
@piotrpalek did you have success transitioning in the activate hook before 2.9?

**Comment by workmanw** [comment]
@piotrpalek FWIW I typically do these type of "redirects" in the `beforeModel` hook. Using your twiddle, if you change `activate` to `beforeModel` it seems to work. Not saying this still isn't an issue, just pointing out an easy workaround.

**Comment by pixelhandler** [comment]
@workmanw I agree I've had issues with transitions in the activate hooks.

@piotrpalek the guides support using the `beforeModel` hook as well. See https://guides.emberjs.com/v2.8.0/routing/preventing-and-retrying-transitions/

I have not seen any traction on improving the use of transition in the activate hook. Can't recall offhand but this but this issues has appeared before and usually the best work around is to not use the `activate` hook to make a transition.

**Comment by rwjblue** [comment]
Ya, definitely a bug that we will fix. But beforeModel does make more sense in his case.

**Comment by piotrpalek** [comment]
Wow haha thanks for the suggestions on using `beforeModel` I'll keep that in mind. I actually specifically selected an app which I knew has weird stuff in it to test 2.9 :)
