### ISSUE TITLE
Ember 2.9-beta: Cannot read property 'getAttribute' of undefined

### ISSUE THREAD

**Issue by jamesdixon** [emberjs/ember.js#14242]
Running the 2.9 beta and seeing the following error:

![image](https://cloud.githubusercontent.com/assets/110114/18374737/91b1a246-760c-11e6-8f57-16a2b8d334e2.png)

Not sure exactly what `buildOutletTree` does 😢 

Thanks!

**Comment by rwjblue** [comment]
I _believe_ that this is an error in the inspector.  Can you provide a twiddle or JSBIn to help us track it down?

/cc @teddyzeenny

**Comment by teddyzeenny** [comment]
Yes this is due to the recent changes in the renderer's root view handling (I think it was adding support for multiple roots). Anyway it's fixed by https://github.com/emberjs/ember-inspector/pull/588.

Deploying today.

**Comment by teddyzeenny** [comment]
Published. This issue should be fixed. Let me know if for some reason it's still happening.

**Comment by jamesdixon** [comment]
@teddyzeenny I can confirm that this has been resolved. Thank you!

**Comment by allthesignals** [comment]
I'm seeing this again with `"ember-cli": "~2.15.1",`: Cannot read property 'getAttribute' of undefined.

I've uninstalled and reinstalled the latest Inspector.
