### ISSUE TITLE
[Ember 2.9-beta] hasBlock not available in partial

### ISSUE THREAD

**Issue by simonihmig** [emberjs/ember.js#14263]
Before Ember 2.9 it was possible to use the `partial` helper in a component's template. and use the special `hasBlock` property within that partial template. This seems to be broken with 2.9/Glimmer2, `hasBlock` is always false.

Here is a Twiddle: https://ember-twiddle.com/366a04e27903d0642260b48faf086749
This works in Ember < 2.9, but breaks if you switch to 2.9.

**Comment by simonihmig** [comment]
@rwjblue Unfortunately, I don't think this has actually been fixed! 

When switching to beta in the above mentioned twiddle, it loads 2.9.0-beta.3, which should include the fixing commit, right? But the bug is still there!

**Comment by rwjblue** [comment]
Will investigate! Thanks for testing again.

**Comment by rwjblue** [comment]
@chancancode - I just checked the twiddle and using `{{#if hasBlock}}` in the partial still seems to be broken.

**Comment by GavinJoyce** [comment]
> I just checked the twiddle and using {{#if hasBlock}} in the partial still seems to be broken.

In addition, using `{{yield}}` in a partial without `hasBlock` also [doesn't work](https://ember-twiddle.com/37650f5b0476bde07cb5fe544e424d9b?openFiles=templates.my-partial.hbs%2C). 

If there is anything I can do to help with this, please let me know.

**Comment by chancancode** [comment]
@simonihmig @GavinJoyce sorry for the delay! It should be fixed now!

**Comment by GavinJoyce** [comment]
Thanks @chancancode! 

Here's a [(now passing) test](https://github.com/emberjs/ember.js/pull/14617) if you feel like having some coverage in ember land is useful.

**Comment by simonihmig** [comment]
Thanks @chancancode from me as well! 

But...

your changes indeed fixed the problem that the first twiddle demonstrated. However this was extracted from an addon of me where I first observed this bug, and after running the build again with that addon, a new error appeared, this time a runtime exception within Glimmer itself! 

I just filed a new issue for that: #14642
