### ISSUE TITLE
Unexpected "Attempting to define property on object that is not extensible." on 2.9 beta

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember.js#14264]
I have a very simple [addon](https://github.com/kellyselden/ember-array-helper). It's latest master commit is from March. I deleted Travis cache and reran the master build. Here are the results:
https://travis-ci.org/kellyselden/ember-array-helper/builds/115857118
release working:
https://travis-ci.org/kellyselden/ember-array-helper/jobs/115857121
beta failing:
https://travis-ci.org/kellyselden/ember-array-helper/jobs/115857123

Here it is reproduced on twiddle:
working on release:
https://ember-twiddle.com/eb15180109e6467f27f88743245cf788/ab9ce64a8625d645b144795f930e10432e0c1816
broken on beta:
https://ember-twiddle.com/eb15180109e6467f27f88743245cf788/5d79be64c7da893b3fbce85e229fbed200b04963

Here is the relevant stack trace when testing locally:
![capture](https://cloud.githubusercontent.com/assets/602423/18414577/f89feea4-7783-11e6-87c9-f2cb4bb05c78.PNG)

It fails on this line https://github.com/emberjs/ember.js/blob/f97598ea6916dfa9094569715933a5e9c060a34d/packages/ember-metal/lib/meta.js#L365

Here is how I got it working:

``` js
import Ember from 'ember';

export function array(params/*, hash*/) {
  // this is the original failure
  // return params;

  // this also fails for the same reason (unexpectedly according to docs)
  // return Ember.A(params);

  // this makes it work
  let array = Ember.A();
  array.pushObjects(params);
  return array;
}

export default Ember.Helper.helper(array);
```

But there may be an unexpected change in beta that is causing the prototype extensions to act differently. This also only seems to be an issue with helpers.

**Comment by rwjblue** [comment]
This is a consequence of https://github.com/emberjs/ember.js/pull/14244.  When the params / hash are frozen, we cannot put a meta on the object (which is done if it is used in the template).

**Comment by krisselden** [comment]
You can't mutate the params array and we seal it in the debug build now.  You can just use slice. 

We made it fail fast when we realized people were doing this,  it prevents us from having to allocate tons of empty arrays.

**Comment by rwjblue** [comment]
@krisselden - The specific thing being done here is Ember mutating the array (by trying to put meta on it).

**Comment by krisselden** [comment]
Robert we should not try to observe a frozen object it isn't going to change

**Comment by rwjblue** [comment]
kk, good point, I'll look there to see how much work that will be for us to avoid observing frozen objects

**Comment by krisselden** [comment]
That is the appropriate fix rather than revert the other change

**Comment by krisselden** [comment]
Object.isFrozen on the add observer methods

**Comment by krisselden** [comment]
we should also use freeze instead of seal seal is shape changes not writes but we want to be readonly

**Comment by rwjblue** [comment]
Ya, we are freezing (done in https://github.com/emberjs/ember.js/pull/14244)

**Comment by mixonic** [comment]
@kellyselden I'm going to close this in favor of a PR with a reproduction: https://github.com/emberjs/ember.js/pull/14649 Thanks for keeping the oil burning on this.
