### ISSUE TITLE
Ember 2.8: Failed to execute 'createElement' on 'Document'

### ISSUE THREAD

**Issue by knownasilya** [emberjs/ember.js#14269]
Seeing this after upgrading to 2.8 when using 

```js
this.render('panels/' + panelName, {
        into: 'application',
        outlet: 'panel'
      });
```

But only in one situation, not sure what it is, but that one uses power-select addon and the others don't.

>ember.debug.js:3012 Uncaught InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('[object Object]') is not a valid name.prototype.createElement @ ember.debug.js:3012buildFragment @ ember.debug.js:46133getCachedFragment @ ember.debug.js:46366RenderResult.build @ ember.debug.js:46081render @ ember.debug.js:46045(anonymous function) @ ember.debug.js:46868renderAndCleanup @ ember.debug.js:46903Block._firstRender @ ember.debug.js:46865Block.invoke @ ember.debug.js:46843ComponentNodeManager_render_instrument @ ember.debug.js:14034instrument @ ember.debug.js:16375ComponentNodeManager_render @ ember.debug.js:14026componentHook @ ember.debug.js:10406handleRedirect @ ember.debug.js:45200block @ ember.debug.js:45172block @ ember.debug.js:45870RenderResult.populateNodes @ ember.debug.js:46300RenderResult.render @ ember.debug.js:46237render @ ember.debug.js:46046(anonymous function) @ ember.debug.js:46868renderAndCleanup @ ember.debug.js:46903Block._firstRender @ ember.debug.js:46865Block.invoke @ ember.debug.js:46843ViewNodeManager_render_instrument @ ember.debug.js:14249instrument @ ember.debug.js:16375ViewNodeManager_render @ ember.debug.js:14233render @ ember.debug.js:13093handleKeyword @ ember.debug.js:45264handleRedirect @ ember.debug.js:45211inline @ ember.debug.js:45354inline @ ember.debug.js:45881RenderResult.populateNodes @ ember.debug.js:46302RenderResult.render @ ember.debug.js:46237render @ ember.debug.js:46046(anonymous function) @ ember.debug.js:44804(anonymous function) @ ember-internals.js:148renderAndCleanup @ ember.debug.js:46903hostBlock @ ember.debug.js:45188render @ ember-internals.js:147handleKeyword @ ember.debug.js:45264handleRedirect @ ember.debug.js:45211block @ ember.debug.js:45172block @ ember.debug.js:45870RenderResult.populateNodes @ ember.debug.js:46300RenderResult.render @ ember.debug.js:46237render @ ember.debug.js:46046(anonymous function) @ ember.debug.js:46868renderAndCleanup @ ember.debug.js:46903Block._firstRender @ ember.debug.js:46865Block.invoke @ ember.debug.js:46843yieldKeyword @ ember.debug.js:13789handleKeyword @ ember.debug.js:45225handleRedirect @ ember.debug.js:45211inline @ ember.debug.js:45354inline @ ember.debug.js:45881RenderResult.populateNodes @ ember.debug.js:46302RenderResult.render @ ember.debug.js:46237render @ ember.debug.js:46046(anonymous function) @ ember.debug.js:44804ifUnless @ ember.debug.js:10008ifHelper @ ember.debug.js:9985compute @ ember.debug.js:14740value @ ember.debug.js:15365invokeHelper @ ember.debug.js:10895(anonymous function) @ ember.debug.js:45182renderAndCleanup @ ember.debug.js:46903hostBlock @ ember.debug.js:45188continueBlock @ ember.debug.js:45180block @ ember.debug.js:45176block @ ember.debug.js:45870RenderResult.populateNodes @ ember.debug.js:46300RenderResult.render @ ember.debug.js:46237render @ ember.debug.js:46046(anonymous function) @ ember.debug.js:46868renderAndCleanup @ ember.debug.js:46903Block._firstRender @ ember.debug.js:46865Block.invoke @ ember.debug.js:46843yieldKeyword @ ember.debug.js:13789handleKeyword @ ember.debug.js:45225handleRedirect @ ember.debug.js:45211inline @ ember.debug.js:45354inline @ ember.debug.js:45881RenderResult.populateNodes @ ember.debug.js:46302RenderResult.render @ ember.debug.js:46237render @ ember.debug.js:46046(anonymous function) @ ember.debug.js:46868renderAndCleanup @ ember.debug.js:46903Block._firstRender @ ember.debug.js:46865Block.invoke @ ember.debug.js:46843yieldKeyword @ ember.debug.js:13789handleKeyword @ ember.debug.js:45225handleRedirect @ ember.debug.js:45211inline @ ember.debug.js:45354content @ ember.debug.js:45890RenderResult.populateNodes @ ember.debug.js:46304RenderResult.render @ ember.debug.js:46237render @ ember.debug.js:46046(anonymous function) @ ember.debug.js:46868renderAndCleanup @ ember.debug.js:46903Block._firstRender @ ember.debug.js:46865Block.invoke @ ember.debug.js:46843ComponentNodeManager_render_instrument @ ember.debug.js:14034instrument @ ember.debug.js:16375ComponentNodeManager_render @ ember.debug.js:14026componentHook @ ember.debug.js:10406handleRedirect @ ember.debug.js:45200block @ ember.debug.js:45172block @ ember.debug.js:45870RenderResult.populateNodes @ ember.debug.js:46300RenderResult.render @ ember.debug.js:46237render @ ember.debug.js:46046(anonymous function) @ ember.debug.js:44804ifUnless @ ember.debug.js:10008ifHelper @ ember.debug.js:9985compute @ ember.debug.js:14740value @ ember.debug.js:15365invokeHelper @ ember.debug.js:10895(anonymous function) @ ember.debug.js:45182renderAndCleanup @ ember.debug.js:46903hostBlock @ ember.debug.js:45188continueBlock @ ember.debug.js:45180block @ ember.debug.js:45176block @ ember.debug.js:45870RenderResult.populateNodes @ ember.debug.js:46300RenderResult.render @ ember.debug.js:46237render @ ember.debug.js:46046(anonymous function) @ ember.debug.js:44804(anonymous function) @ ember.debug.js:44911(anonymous function) @ ember.debug.js:9869forEach @ ember.debug.js:9877eachHelper @ ember.debug.js:9866compute @ ember.debug.js:14740value @ ember.debug.js:15365invokeHelper @ ember.debug.js:10895(anonymous function) @ ember.debug.js:45182renderAndCleanup @ ember.debug.js:46903hostBlock @ ember.debug.js:45188continueBlock @ ember.debug.js:45180block @ ember.debug.js:45176block @ ember.debug.js:45870(anonymous function) @ ember.debug.js:45957dirtyCheck @ ember.debug.js:46006block @ ember.debug.js:45956RenderResult.populateNodes @ ember.debug.js:46300RenderResult.revalidateWith @ ember.debug.js:46274Block.invoke @ ember.debug.js:46841ComponentNodeManager_rerender_instrument @ ember.debug.js:14078instrument @ ember.debug.js:16375ComponentNodeManager_rerender @ ember.debug.js:14056componentHook @ ember.debug.js:10378handleRedirect @ ember.debug.js:45200block @ ember.debug.js:45172block @ ember.debug.js:45870(anonymous function) @ ember.debug.js:45957dirtyCheck @ ember.debug.js:46006block @ ember.debug.js:45956RenderResult.populateNodes @ ember.debug.js:46300RenderResult.revalidateWith @ ember.debug.js:46274validateChildMorphs @ ember.debug.js:46634dirtyCheck @ ember.debug.js:46011inline @ ember.debug.js:45962RenderResult.populateNodes @ ember.debug.js:46302RenderResult.revalidateWith @ ember.debug.js:46274validateChildMorphs @ ember.debug.js:46634dirtyCheck @ ember.debug.js:46011content @ ember.debug.js:45968RenderResult.populateNodes @ ember.debug.js:46304RenderResult.revalidateWith @ ember.debug.js:46274validateChildMorphs @ ember.debug.js:46634dirtyCheck @ ember.debug.js:46011block @ ember.debug.js:45956RenderResult.populateNodes @ ember.debug.js:46300RenderResult.revalidateWith @ ember.debug.js:46274validateChildMorphs @ ember.debug.js:46634dirtyCheck @ ember.debug.js:46011block @ ember.debug.js:45956RenderResult.populateNodes @ ember.debug.js:46300RenderResult.revalidateWith @ ember.debug.js:46274Block.invoke @ ember.debug.js:46841ComponentNodeManager_rerender_instrument @ ember.debug.js:14078instrument @ ember.debug.js:16375ComponentNodeManager_rerender @ ember.debug.js:14056componentHook @ ember.debug.js:10378handleRedirect @ ember.debug.js:45200block @ ember.debug.js:45172block @ ember.debug.js:45870(anonymous function) @ ember.debug.js:45957dirtyCheck @ ember.debug.js:46006block @ ember.debug.js:45956RenderResult.populateNodes @ ember.debug.js:46300RenderResult.revalidateWith @ ember.debug.js:46274validateChildMorphs @ ember.debug.js:46634handleKeyword @ ember.debug.js:45282handleRedirect @ ember.debug.js:45211block @ ember.debug.js:45172block @ ember.debug.js:45870(anonymous function) @ ember.debug.js:45957dirtyCheck @ ember.debug.js:46006block @ ember.debug.js:45956RenderResult.populateNodes @ ember.debug.js:46300

**Comment by rwjblue** [comment]
Hmm. Can you create a reproduction? It would also be helpful to know what the object being referenced there is (we expect a string for `tagName`)...

**Comment by knownasilya** [comment]
Looks like https://github.com/cibernox/ember-power-select/issues/659 is the same issue. Closing this.

**Comment by abirtley** [comment]
For what it's worth, this error is also thrown on 2.8.0 if the tagName property is an Ember.computed. Note that in 2.5.0, this merely triggered a deprecation warning advising (if I remember correctly) that in the future, computed tagNames would be respected on component creation, but any subsequent changes would have no effect.

I'm new to Ember but I had expected computed tagNames to be supported until 3.0? Also, I can't seem to find any reference to the original deprecation message on google or here in github, so maybe it's just me going crazy.
