### ISSUE TITLE
Ember 2.8.0: RSVP.Promise.reject uncaught exception when provided arguments

### ISSUE THREAD

**Issue by anssikin** [emberjs/ember.js#14277]
Fresh application with Ember-CLI 2.8.0, Node 6.3.1 and Ember 2.8.0 throws uncaught exception when `Ember.RSVP.Promise.reject` is called with one or more arguments. I did not find any mention of changed behavior in changelog, so I'm assuming this is a bug.

![screen shot 2016-09-13 at 13 31 51](https://cloud.githubusercontent.com/assets/8693728/18470757/e0fd5e5a-79b6-11e6-99e1-5567eb3dcf44.png)

**Comment by rwjblue** [comment]
Definitely seems bizarre. I do not think that 2.8.0 included an updated RSVP (but I believe 2.9 does), so it seems unlikely to be an RSVP bug. 

Can you share the full stack from that error?

**Comment by anssikin** [comment]
Sure. Here is another screen capture.

![screen shot 2016-09-13 at 14 41 05](https://cloud.githubusercontent.com/assets/8693728/18472439/30197b1e-79c0-11e6-981f-1babaf5fb452.png)

The exception seems to come from `ember-metal/error_handler` module, a function called`getStack`. I'm using Chrome Version 52.0.2743.116 (64-bit) on OSX, if that helps.

**Comment by rwjblue** [comment]
Perfect, thank you!

**Comment by rwjblue** [comment]
This was fixed by https://github.com/emberjs/ember.js/pull/14184 and pulled into beta, but I didn't realize it also needed to be fixed in release.  I'll get it pulled down and prepared for the next patch release.

**Comment by rwjblue** [comment]
OK, updated now, in a few minutes you can use the `release` channel to get a working build but I believe we will have 2.8.1 out in a couple days.

**Comment by anssikin** [comment]
Great. Thanks for the super quick help!
