### ISSUE TITLE
Change in behavior between Ember 2.7.0 and Ember 2.8.0 - return true from an action - integration testing template received unexpected action save

### ISSUE THREAD

**Issue by adam-knights** [emberjs/ember.js#14275]
In Ember 2.7.0 we have a component integration test that passed. There was a small piece of validation that returned early from a buttons 'save' action. It returned by doing

```
...
if (!isValid) {
  return true;
}
...
```

This same test started failing with Ember 2.8.0. It failed with ```integration testing template received unexpected action save```.

It seems returning true from an action causes the 'save' action to bubble upto the integration test.

If I change the above to

```
...
if (!isValid) {
  return;
}
...
```

Then it passes again because it doesn't bubble. So I have a workaround.

-----
I wanted to report this to find out if this change was expected?

-----

Reproduction twiddle:

https://ember-twiddle.com/a7953f50bfef3f09bf55d3c61ed79b8f?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs

If you set the versions to Ember 2.7.3 and Ember Data 2.7.0 and look in the console then there is no issue.

If you set the versions to Ember 2.8.0 and Ember Data 2.8.0 and look in the console then you get an error that the action is unhandled.

**Comment by rwjblue** [comment]
Thanks for reporting, definitely a regression.
