### ISSUE TITLE
[Glimmer 2] id attribute binding undefined

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#14278]
Release: `<div class="ember-view"><!----></div>`
Alpha:     `<div class="ember-view" id="undefined"><!----></div>`

https://ember-twiddle.com/6c8e19e4eebc900e40d73d6795e30a40?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs

**Comment by rwjblue** [comment]
Awesome, thank you for reporting!  

I believe that the 2.8 results are bad also.  If a component has an attribute binding for `id` it *must* be present (and not duplicated) or event dispatching will not work (i.e. no event methods in the component).  If `id` is not a valid value I believe we should coerce to a normal view's id (i.e. `id="ember1234"`).
