### ISSUE TITLE
property_set.js won't modify object if value and currentValue is undefined

### ISSUE THREAD

**Issue by makepanic** [emberjs/ember.js#14270]
In newer ember versions, `Ember.set(object, 'field', undefined)` won't set the `field` key on an object, because the value is `undefined`.
It exits earlier [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/property_set.js#L62-L63) which causes no object modification.

I think this is a regression (introduced in `v2.7.0-beta.1`), because [previously](https://github.com/emberjs/ember.js/commit/9471527454b30b9a892d6d40f21735365b5a2897#diff-2c6910b295639eb6f0ea3f0f2c9e3520L72) it wouldn't enter that condition, if the value was `undefined`.

Using a 2.7.0 ember app:
![20160912-190913](https://cloud.githubusercontent.com/assets/1205444/18447474/101731ce-7927-11e6-8444-151eebf1d598.png)

On discourse:
![20160912-200952](https://cloud.githubusercontent.com/assets/1205444/18447651/dbe63a5c-7927-11e6-9ae4-ef4fc3c2e99f.png)

A possible way to fix this would to reintroduce the `value !== undefined` check

**Comment by rwjblue** [comment]
After reviewing this a bit, I am not certain that `Ember.set` should actually be changed here.  `Ember.set` isn't about guaranteeing an objects own properties, its about setting the specified property to the given value.  If that property already is set to the new value, doing nothing seems like the correct thing to me.

I welcome thoughts from others (cc @krisselden / @stefanpenner), but I don't know that this is a bug...

**Comment by stefanpenner** [comment]
> Ember.set isn't about guaranteeing an objects own properties, its about setting the specified property to the given value. If that property already is set to the new value, doing nothing seems like the correct thing to me.

i would tend to agree.

**Comment by stefanpenner** [comment]
@rwjblue we could set the property and not have it emit a change event. This may align both the ES semantics, and the change tracking semantics.

cc @krisselden

**Comment by locks** [comment]
I opened the file to try and implement stef's suggestion and got intimidated by the code. Should I pursue it, and would it need new tests to be added?
