### ISSUE TITLE
[Glimmer 2] Conditional block gets last context of contextual component instead of each context

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#14284]
Best explained with a Twiddle

Toggle edit mode -> Notice the list -> Switch to alpha -> Try again -> See the difference

https://ember-twiddle.com/750065f63a0e64b68fc645f637b08b17?openFiles=templates.components.my-component.hbs%2C

**Comment by rwjblue** [comment]
Did more digging, and it appears that this is related to a component yielding multiple times.

Changing to use a straight up `{{#each` works as intended: https://ember-twiddle.com/215fa5d37088e9fdc6f0415b1f38e6de?openFiles=templates.application.hbs%2C.

**Comment by rwjblue** [comment]
This was fixed by tildeio/glimmer#317, and a regression test was added in #14285.
