### ISSUE TITLE
[Glimmer 2] appendTo (renderToElement) causes infinite loop.

### ISSUE THREAD

**Issue by runspired** [emberjs/ember.js#14287]
Reproduction: https://ember-twiddle.com/84af86aa5076f0c82da89778816129b9?openFiles=components.my-component.js%2Ctemplates.components.managed-component.hbs

**Comment by runspired** [comment]
cc @chancancode

**Comment by runspired** [comment]
Seems very likely related to this: https://github.com/emberjs/ember.js/pull/14241#issuecomment-246904032

**Comment by runspired** [comment]
Note that pushing this into a fully asynchronous run loop has undesirable consequences here, pushing it onto a new loop immediately after may work alright.

**Comment by runspired** [comment]
Confirmed that `run.schedule('afterRender', () => { component.renderToElement(); });` works. This unfortunately would have the side effect of preventing Flexi from integrating the component with the route's natural lifecycle, and causes Glimmer to flush render twice.

**Comment by rwjblue** [comment]
Yes, it is the same issue as https://github.com/emberjs/ember.js/pull/14241 is trying to address. Essentially, adding a root while rendering roots causes infinite recursion.  #14241 fixes that as it stands (by looping if new roots were added during the last `_renderRoots` invocation), but as mentioned in that comment I need to review more deeply with @krisselden.
