### ISSUE TITLE
[Glimmer 2] Basic component unit test not working

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#14286]
`TypeError: Template.create is not a function`

Twiddle: https://ember-twiddle.com/#/2f7703742f16e27d647c777701c2842b?openFiles=tests.unit.components.my-component-test.js%2Ctemplates.components.my-component.hbs (switch from release -> alpha to see failure)

Ember CLI demo: https://github.com/amk221/-ember-cli-component-unit-test/blob/master/tests/unit/my-component-test.js#L10

(rwjblue mentioned to file this here, even though likely a ember-test-helpers bug)

**Comment by rwjblue** [comment]
https://github.com/switchfly/ember-test-helpers/pull/179 shows this is working now (with one exception).
