### ISSUE TITLE
[Ember 2.9-beta2] Missing render revalidation in production build

### ISSUE THREAD

**Issue by kanongil** [emberjs/ember.js#14298]
I tried to update my app to v2.9.0-beta2 in which I encountered a rendering regression, where some of my UI failed to update after an initial render, deferring it until another part of the UI needed revalidation.

While I did expect some corner cases to have issues, I did not expect it to only appear when using the production builds, as this does!

I have spent some time to isolate the cause, and I ended up with this code on top of a brand new `ember init` project:

*app/templates/application.hbs*
```hbs
Value: {{value}}
```

*app/controllers/application.js*
```js
import Ember from 'ember';

export default Ember.Controller.extend({
    object: Ember.Object.create({ value: 'fail' }),
    value: Ember.computed.readOnly('object.value'),

    init() {
        this._super(...arguments);
        Ember.run.later(() => {
            this.set('object.value', 'ok');
        }, 200);
    },
});
```

* Rendered value using debug build: `ok`.
* Rendered value using production build: `fail`.

Notes:

* If I render `{{object.value}}` instead, it renders correctly in both cases.
* `this.get('value')` always gets the correct value.
* I have tried to replicate this in a jsbin, but it always renders correctly, even using the minified builds.
* This also fails on the latest `canary` build.

**Comment by rwjblue** [comment]
Thank you for the detailed error report! Would you mind creating a repo with a test that passes with `ember test` and fails with `ember test --environment=production`?  That would make it much easier for others to jump in and help debug...

**Comment by kanongil** [comment]
Yes, here you go: https://github.com/kanongil/render-fail

**Comment by rwjblue** [comment]
Awesome, thank you!

**Comment by ToMoCoop** [comment]
@rwjblue @kanongil I have a feeling that the removal/move of:

```
 AliasedProperty.prototype.willWatch = function (obj, keyName) {		
 -    _emberMetalDependent_keys.addDependentKeys(this, obj, keyName, _emberMetalMeta.meta(obj));		
 -  };		
 -		
 -  AliasedProperty.prototype.didUnwatch = function (obj, keyName) {		
 -    _emberMetalDependent_keys.removeDependentKeys(this, obj, keyName, _emberMetalMeta.meta(obj));		
 -  };
```
has caused some issues.

Our bower upgraded automatically from a working v2.9.0-beta.2 to v2.9.0-beta.3,, and a url binding against an image tag stopped working. I'd love to create some re-create some steps here, but it's an enormous app and hard to dig out, but basically switching back to beta2 in bower solves the issue.

Seen as this is largely the only change in the bower shim for beta3 (https://github.com/components/ember/commit/1721af7ffd58224827b90ef8146ec8cdf511f82f), I think this may cause issues.

I can't be of more help atm, but something to look out for, should others start reporting issues with bindings, specifically image src bindings.

**Comment by ToMoCoop** [comment]
That said, this also may be that we're still on -beta2 in npm though too, so this may throw it.

**Comment by rwjblue** [comment]
There is a separate issue open for img src issues (I don't think it's related to this change).

**Comment by ToMoCoop** [comment]
@rwjblue Ok, can you point me to it?

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/issues/14323

**Comment by ToMoCoop** [comment]
Perfect, thanks!
