### ISSUE TITLE
didInsertElement not fired in IE11

### ISSUE THREAD

**Issue by zxcware** [emberjs/ember.js#14292]
OS: Windows 7
Ember-cli: 2.6.3

didInsertElement not fired in IE11 but willRender was fired.

**Comment by rwjblue** [comment]
We have tests to confirm otherwise in general, we will need a reproduction to be able to dig into your specific case and help out.

**Comment by Serabe** [comment]
Hello, @zxcware,

did you had some time for creating a reproduction? A Twiddle would be ok but sometimes the bug needs to be reproduce in an ember CLI project.

If you need any help with it, ping me in Slack.

Thank you!

**Comment by Serabe** [comment]
Closing this according to [our triaging policy](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy). Please, provide a reproduction so we can dig in.

Thank you!
