### ISSUE TITLE
[Glimmer 2] {{input placeholder=''}} rendered as {{input placeholder=true}}

### ISSUE THREAD

**Issue by Cryrivers** [emberjs/ember.js#14290]
Reproduction here:
https://ember-twiddle.com/a401f3e972713d00302ad86b31148469?openFiles=templates.application.hbs%2C

**Comment by Serabe** [comment]
Seems similar to #14181 and #14001

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/14315.
