### ISSUE TITLE
didReceiveAttrs being called when parent component sets data

### ISSUE THREAD

**Issue by rlivsey** [emberjs/ember.js#14305]
Seen in beta & canary, if a child component fetches data in `didReceiveAttrs` and passes it to a parent component, when that parent component sets it on itself then it appears to be triggering `didReceiveAttrs` on the child again even though no attrs are changed at all.

Twiddle:
https://ember-twiddle.com/64820c0eac64c7be799d8de597bae0cd

Eg (from the twiddle) this causes an infinite loop of `didReceiveAttrs`:

```js
// inner-component.js
export default Ember.Component.extend({
  didReceiveAttrs() {
    this._super(...arguments);
    console.log("got attrs");

    Ember.run.later(() => {
      this.set("items", [1,2,3]);
      console.log("items set");
      this.get("on-update")(this.get("items"));
    }, 100);
  }
});
```

```js
// outer-component.js
export default Ember.Component.extend({
  items: null, 
  
  actions: {
    onUpdate(items) {
      console.log("got items", items);
      this.set("items", items);
    }
  }
});
```

```handlebars
<!-- outer-component template -->
{{inner-component 
  on-update=(action "onUpdate")
}}

{{items.length}} items
```

**Comment by rlivsey** [comment]
Summarising a discussion on Slack with @rwjblue:

It looks like this is currently as designed and that setting/changing properties in an outer component will call `didReceiveAttrs` in the inner components & that currently components will need to be aware of this and track the attr changes themselves if something expensive is to be performed as part of `didReceiveAttrs`.

Previously the exact number of times these fired and when was super poorly defined.

If all attrs are static, then this could potentially be optimised away in the future as we know that they will never change.

Feel free to close this, might be a documentation issue when 2.9.0 is released rather than a regression/bug?

**Comment by rwjblue** [comment]
Thanks for syncing up our convo here. I do think there are some things we should do when the hash args passed to a component are all constants, but that is a _slightly_ different thing than the original point of the issue.

**Comment by Serabe** [comment]
Closing this as suggested above.
