### ISSUE TITLE
Exceptions are not getting logged for bad imports or bad helpers.

### ISSUE THREAD

**Issue by adhamhf** [emberjs/ember.js#14309]
If you have a bad import name or a  bad helper name the related exceptions are not being logged.

Here is a twiddle that does reproduce the issue.  It looks like you have to be in a component hbs or js file for this to reproduce.

https://ember-twiddle.com/0ad84fc6be88c1a352e67accd13271de

**Comment by adam-knights** [comment]
I am also seeing this issue but unable to reproduce in a twiddle - seems that Error.captureStackTrace(this, EmberError); does get called - but where as on Ember Twiddle at the onEnd part it logs to the console, in my app it does not, if that helps anyone fix this..

**Comment by rwjblue** [comment]
I need a reproduction to be able to dig into this.  I'm not sure what is happening in the twiddle here, but it doesn't _seem_ like the issue reported.

Can someone create a demo repo to help track this down?

**Comment by adhamhf** [comment]
@rwjblue I'm pretty sure the twiddle is reproducing the issue as reported.  Can you help me understand what you are unsure about?  Perhaps if I understand better I can address it.

**Comment by tdyer-aio** [comment]
@adhamhf it appears you aren't using the my-component from within the `application.hbs` once you do it starts logging the appropriate exception.

**Comment by adhamhf** [comment]
@tdyer-aio doh.

**Comment by Serabe** [comment]
@adhamhf can you confirm that was the problem? Thank you!

**Comment by adam-knights** [comment]
@adhamhf @Serabe I couldnt repo this issue outside of my app, but I can confirm that Ember Data 2.8.1 resolves this issue for me. I think https://github.com/emberjs/data/pull/4537 may have resolved this. @adhamhf although your repo wasnt any good, you may have been seeing a real issue in your actual app - maybe try data 2.8.1?

**Comment by adhamhf** [comment]
I'm going to close, seems fixed.
