### ISSUE TITLE
Template parser fails to parse `<`

### ISSUE THREAD

**Issue by herom** [emberjs/ember.js#14304]
I don't think a simple string like `< back` embedded in HTML should cause an error like it's the case right now.

Please see this [twiddle](https://ember-twiddle.com/0ac661a043d7c8cc1338c975dc14e6eb?openFiles=templates.application.hbs%2C) for reproduction.

**Comment by Serabe** [comment]
Thank you for your report!

**Comment by rwjblue** [comment]
I don't really think this is a bug, if you need/want to use `<` / `>` / etc you would need to use the HTML entities.  Our tokenizer is based on the HTML spec and does not have the same auto-correcting behavior that browsers do (nor do we want it to!).  

It seems pretty unlikely that we will change the parsing behavior here, and unless @mmun / @krisselden / et al disagree I will likely close this...

**Comment by herom** [comment]
Thanks for taking a look at it @Serabe @rwjblue - I just thought I'd report this behaviour as it bugged me quite some time :smiling_imp: ... as you said, it's totally save to use the HTML entities so maybe not a real "bug" but worth to be mentioned (so I thought :smile: )

**Comment by rwjblue** [comment]
Ya, I agree that its good to discuss/review these sorts of assumptions over time. Our parser is a bit more strict than what you find in browsers, and in general that is a good thing (leads to much better structured and valid HTML).  This may be an annoyance at times, but overall I think the pros outweigh the cons...

**Comment by mmun** [comment]
I'm leaning towards allowing this.

**Comment by rwjblue** [comment]
Would love to see a PR to simple-HTML-tokenizer to understand the added complexity it would add. 

In the meantime, this definitely isn't a "bug" here.
