### ISSUE TITLE
Dynamic id not updating for input helper

### ISSUE THREAD

**Issue by sbatson5** [emberjs/ember.js#14318]
I am working on an app where a user can save a list of "todos".  We separate these `todos` by `course` and later allow the user to view all the `todos` they added throughout their courses.  The user can then check the todos  as `completed` once they want to finish them.

For accessibility, each "todo" has a checkbox with an id and a `label` that matches.  We then want to separate which ones the user has completed versus the ones they haven't.  Since we have a variable number of courses and todos for each user, we dynamically create the `id` based on the course name and the index in which it was added in our each loop.

The problem I run into is that the computed property for the `id` updates properly when an item is marked as "completed" (and therefore removed from the incomplete list), but the id of my input does not update.

I created a Twiddle here: https://ember-twiddle.com/b8c83a5dad5a30337e6e31b7ad92b1d8

![screen shot 2016-09-19 at 4 37 45 pm](https://cloud.githubusercontent.com/assets/881981/18648216/b2884690-7e87-11e6-90d6-155baa481fa3.png)

Checking the first item marks it as "complete".  This updates the index of the next item, the label is updated to `label for="English__0"` but the input still has its original id of `English__1`.

**Comment by Serabe** [comment]
Hello @sbatson5,

the component's id is fixed after the first render as you can see in [this twiddle](https://ember-twiddle.com/190e1b48f873c8622467bc7a11d522d2?openFiles=styles.app.css%2Ctemplates.components.my-component.hbs).

There are several ways to approach this. My favourite for checkboxes is including the input inside the label. If for whatever reason you cannot do this, look for an id where the order does not matter (maybe each task has an unique id somehow).

Thank you!

**Comment by AddisonG** [comment]
Is this still intended functionality? Is there any way to re-render with a new id?

**Comment by AddisonG** [comment]
Agh. This hit me again. This is super annoying.

**Comment by chancancode** [comment]
If you are using a not-ancient version of Ember then it should work. What Ember version are you using and what does the template look like?

**Comment by AddisonG** [comment]
Ember: `3.24.4`

The code is like this:
```
<Input
	aria-label={{concat "checkbox - " input_id}}
	@type="checkbox"
	@id={{input_id}} 
	@disabled={{disabled_value}} 
	@checked={{checked_value}} 
	@class={{input_class}}
/>
```

The checkbox label updates (e.g: `checkbox - id-4`), but the id stays the same (e.g: `id-1`).
This results in my browser throwing:

```
Uncaught Error: Assertion Failed: Attempted to register a view with an id already in use: id-1
```

I just have to strip away the ID completely for it to work.

I'm quite sure that this is cause by this one issue, as I've tried appending extra characters to the start of the ID, to ensure that NO other element on the page should ever match.

**Comment by chancancode** [comment]
If you change `@id` to `id` it should work I believe

**Comment by AddisonG** [comment]
Thanks @chancancode, you absolute legend - That fixed the issue perfectly.

**Comment by mmtbz** [comment]
I'm having the same issue as well in ember 3.8.3 -- this is happening to all other input fields as well. How can I fix this?
`{{input
      id=(concat "member-" id)
      type="checkbox"
      disabled=disabled
      change=(action "toggleMember")
    }}
    <label
      for={{concat "member-" id}}
    >
      Member
    </label>`

**Comment by NullVoxPopuli** [comment]
Does it work if you use the input httml tag instead?

```hbs
<input 
  id="member-{{this.id}}" 
  type="checkbox" 
  disabled={{this.disabled}}
  {{on 'change' this.toggleMember}}
>
<label for="member-{{this.id}}">
  Member
</label>
```

**Comment by mmtbz** [comment]
I get this compilation error because of {{on 'change' this.toggleMember}} `Compile Error on is not a modifier: Helpers may not be used in the element form.`

**Comment by NullVoxPopuli** [comment]
Ah, maybe 3.8 is before modifiers. Might need 3.11+

**Comment by mmtbz** [comment]
this works fine, I needed to change `{{on 'change' this.toggleMember}}` to `change={{action "toggleMember"}}"`
Thanks
