### ISSUE TITLE
Ember 2.8 regression with dynamically created components

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#14314]
We have the following service:

``` coffeescript
TemplateToDomService = Ember.Service.extend
  render: (template, context = {}) ->
    new Ember.RSVP.Promise (resolve) =>
      # create a new component
      component = Ember.Component.create
        style: 'display:none;' # hide it
        layout: Ember.HTMLBars.compile(template)
      Ember.setOwner(component, Ember.getOwner(this))

      component.setProperties(context)

      component.one 'didRender', ->
        element = @element.cloneNode(true)
        @remove()
        resolve(element)

      # append the component to the body to make it render
      component.append()
```

Which we use to dynamically render templates. It returns an HTML element that we can put somewhere and use. Sample usage shown here:

``` coffeescript
@get('templateToDom').render('{{#link-to "something"}}link!{{/link-to}}').then (element) ->
  # show somewhere the element
```

The issues:

1) `remove` is no longer a method on components in 2.8. It was in 2.7.3.

2) This code, no matter how we refactor it, is not doing the right thing on 2.8. The link is not working at all or is refreshing the page.

I tried fixing 1) by doing `@element.remove()` or `component.destroy()`. But I can't seem to do anything for the second issue. If the didRender handler is just a single `resolve(@element)`, then the page is refreshed, and in all other cases the `link-to` is not doing anything at all.

Here is a twiddle that showcases the problem:

https://ember-twiddle.com/ecfef8a1079e1b664e852c0962e2b924?openFiles=components.my-component.js%2C

You can change the versions in `twiddle.json` to 2.7 to see it working correctly.

Any ideas?

Edit: I've simplified even more the Twiddle - using `appendTo` instead of the `didRender` hook.

**Comment by krisselden** [comment]
`remove` was private API, link-to's use event delegation and data attributes, so that is why the cloning worked, the link-to component though registers the action.

This all though seems very hacky, have you see the other solutions for rendering far away?

We are more likely to solve and maintain ember-wormhole and ember-islands since they are popular solutions to the same problem.

**Comment by Serabe** [comment]
@krisselden any follow up to this issue? Can it be closed? Thank you!

**Comment by krisselden** [comment]
Discussed this at the core team call, `remove` was to support the reuse of a view in a `ContainerView`.  

Views were deprecated during 1.x, moved to an add-on at 2.0, then support was removed with 2.6.  While this may have happened to work, the work to support it now is non trivial just to deprecate a private API.

There are no plans to support this API but there is ongoing work to make `ember-wormhole` more first class.  This allows the data flow and render to continue down the tree, even though the subtree is placed elsewhere, which I believe satisfies this use case.

**Comment by wycats** [comment]
And for any future travelers, if this issue turns out to affect a significant number of users, we'd consider revisiting this decision.
