### ISSUE TITLE
Improve error messages for lookup vs _lookupFactory

### ISSUE THREAD

**Issue by rwwagner90** [emberjs/ember.js#14310]
As requested by @rwjblue I am posting an issue to track improving error message for using the wrong lookup for templates. Currently, the error message says something like `TypeError: Template.create is not a function`.

Should try to improve these messages, so the user knows to try:

`owner._lookupFactory('template:foo')`

instead of:

`owner.lookup('template:foo')`

**Comment by rwjblue** [comment]
Thank you for opening @rwwagner90! 

Basically, we need to add a couple assertions [right around here](https://github.com/emberjs/ember.js/blob/63da020481042d090deda8285883eafc08ed1441/packages/ember-glimmer/lib/environment.js#L89).  The main things we should check for right now are:

* Is `Template` a CP (give good assertion about not using `layout` as a computed property)
* Is `Template` an instance of `TemplateFactory` ([from here](https://github.com/tildeio/glimmer/blob/master/packages/glimmer-runtime/index.ts#L12))
* Does `Template` have `.create`

**Comment by rwwagner90** [comment]
@rwjblue do you want me to attempt a PR? Never submitted a PR to something as large as Ember before, but could give it a try.

**Comment by pixelhandler** [comment]
Can `_lookupFactory` can loose the underscore and go public?

**Comment by rwjblue** [comment]
@pixelhandler - There is an RFC open for this (the new method will be named factoryFor).

**Comment by rwjblue** [comment]
@rwwagner90 - Absolutely, if you have the time. Happy to help with guidance and whatnot...

**Comment by Serabe** [comment]
@rwwagner90 Still interested on the PR?

**Comment by rwjblue** [comment]
Closing for now, I think the largest issue was fixed in #14312 and we can continue to iterate if we have more pain around this...
