### ISSUE TITLE
Using computed.alias for parentView inside component triggers Ember.set error

### ISSUE THREAD

**Issue by dimul** [emberjs/ember.js#14327]
Using property like this inside nested component to observe parent components property which is boolean

    expandMenu: Ember.computed.alias 'parentView.expandMenu'

This esentially creates error 

    ember.debug.js:6778 Uncaught Error: Assertion Failed: You must use Ember.set() 
    to set the `parentView` property (of <appname@component:simple-menu::ember690>) 
    to `<appname@component:simple-menu-container::ember662>`.

`simple-menu-container` - is parent
`simple-menu` - is child ->  expandMenu property is here

Came in with Ember 2.8, 2.7.3 works just fine

This issue 
piceaTech/ember-rapid-forms/issues/134 
resolves similar but different issues.

I am doing something wrong or something needs fixing?

**Comment by rwjblue** [comment]
Should have been fixed in 2.8.1, please double check?

**Comment by workmanw** [comment]
Oh man, I spent an hour trying to make a fiddle to reproduce this. Turns I should have searched the issues first :(.

Good news though, I had this exact issue (`parentView` w/ `alias`) and 2.8.1 did fix this for me.

**Comment by dimul** [comment]
Yeap, and I had exactly same problem that I have written above and indeed ember 2.8.1 fixed that. but this is still here even with 2.8.1. Also 2.8.1 fixes problem with  setting parentView to null

This error is fixed with 2.8.1:

     Uncaught Error: Assertion Failed: You must use Ember.set() to set the `parentView` property (of 
     <myapp@component:em-input::ember619>) to `null`

This error IS NOT fixed with 2.8.1

    Uncaught  Error: Assertion Failed: You must use Ember.set() to set  `parentView` 
    property (of <appname@component:simple-menu::ember690>) to 
    `<appname@component:simple-menu-container::ember662>`.


It wants to set parentView property inside nested component to its parentComponent under which it is nested.

**Comment by dimul** [comment]
Did some digging and turns out that error comes from .observes('expandMenu')
