### ISSUE TITLE
`--dummy` flag doesn't work for route blueprint

### ISSUE THREAD

**Issue by SaladFork** [emberjs/ember.js#14324]
``` bash
$ ember --version
ember-cli: 2.8.0
node: 6.3.1
os: darwin x64

$ npm ls --depth=0 | grep ember-cli@
├── ember-cli@2.8.0

$ bower ls | grep -m1 ember#
├─┬ ember#2.8.1 (latest is 2.9.0-beta.3)

$ ember addon ember-cli-foo
installing addon
…
Successfully initialized git.
Installed packages for tooling via npm.
Installed browser packages via Bower.

$ ember g controller foo --dummy     # works as expected
installing controller
  create tests/dummy/app/controllers/foo.js

$ ember g route foo --dummy          # generates app route, not dummy
installing route
  create app/routes/foo.js
  create app/templates/foo.hbs
updating router
  add route foo
```

Was able to reproduce with `master` of both `ember-cli` and `ember` (though I suspect this might not matter since it seems we're not including `ember` as an addon in `package.json` yet):

``` bash
$ npm link ember-cli
$ ember --version

Missing symlinked npm packages:
Package: ember-cli
  * Specified: 2.8.0
  * Symlinked: 2.9.0-beta.2

ember-cli: 2.9.0-beta.2-master-70e480baf7
node: 6.3.1
os: darwin x64

$ bower install --save ember#master
…
    1) ember#master which resolved to 1721af7ffd
…

$ bower ls | grep -m1 ember#
├─┬ ember#1721af7ffd

$ ember g route foo --dummy          # generates app route, not dummy

Missing symlinked npm packages:
Package: ember-cli
  * Specified: 2.8.0
  * Symlinked: 2.9.0-beta.2

installing route
  create app/routes/foo.js
  create app/templates/foo.emblem
updating router
  add route foo
```

_(wasn't sure if to file this here or on `ember-cli`, but since the `route` blueprint seems to be living here now it seemed more appropriate)_

**Comment by locks** [comment]
@SaladFork ember-cli please. From what was explained to me, the blueprints in this repo aren't actually used by CLI, but ember-legacy-blueprints instead.

**Comment by SaladFork** [comment]
Should I repost to `ember-cli` or `ember-cli-legacy-blueprints`? Is it worth keeping this open so we can fix the blueprint here as well if/when the switch is made?

**Comment by rwjblue** [comment]
We need to fix in both legacy blueprints and here, I'm happy to keep this open as a meta issue though.

**Comment by pixelhandler** [comment]
@SaladFork @locks @rwjblue is this still an issue, perhaps we should close; what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
