### ISSUE TITLE
[2.9.0-beta.3] <img> elements can't produce dynamic `src` attribute

### ISSUE THREAD

**Issue by BrianSipple** [emberjs/ember.js#14323]
I'm using the current Glimmer 2 beta (2.9.0-beta.3) and it appears that any `<img>` element -- both those written directly or those rendered by a component with `tagName: img` and a `src` attribute binding -- can't produce its `src` attribute if the `src` attribute is computed dynamically. 

[This Twiddle](https://ember-twiddle.com/c9a61e05c8f3e472ac43aa62d6521c41?fileTreeShown=false&numColumns=2&openFiles=components.my-img.js%2Ctemplates.application.hbs) demos just about every combination of component/native-HTML + explicit/dynamic `src` attribute usage that I could think of. The only working combination is a native `<img>` with a hardcoded `src`.

**TIP:** Flip back to any previous version of Ember in the Twiddle -- 2.9.0-beta.2,  2.9.0-beta.1, or 2.8-, and everything will work as expected.

**Comment by rwjblue** [comment]
Thank you for reporting! I'll try to dig in tonight if others don't beat me to it...

**Comment by rwjblue** [comment]
Is addressed upstream by https://github.com/tildeio/glimmer/pull/323.

**Comment by rwjblue** [comment]
Just cherry-picked the fix into beta branch. Please test the latest beta build (in ~ 10 minutes) to confirm...

**Comment by BrianSipple** [comment]
@rwjblue Taken moments ago from the Twiddle (note that I flipped Ember version to `beta`):

<img width="879" alt="screen shot 2016-09-21 at 11 54 23 pm" src="https://cloud.githubusercontent.com/assets/5483853/18739229/f4c32d10-8056-11e6-84c5-ff9e8a1bf667.png">

Order appears to be restored to the universe 😄.
