### ISSUE TITLE
packages/ember-routing/lib/system/route.js in _disconnectOutlet -> this.connection is undefined

### ISSUE THREAD

**Issue by davelane** [emberjs/ember.js#14325]
Under certain circumstances this.connections is undefined in _disconnectOutlet and the for loop leads to an exception:

```
_disconnectOutlet(outletName, parentView) {
    let parent = parentRoute(this);
    if (parent && parentView === parent.routeName) {
      parentView = undefined;
    }
    for (let i = 0; i < this.connections.length; i++) {
```

This happens when we abort a transition in beforeModal and want to transition to an error page closing any open modals. AFAIK there is no way of testing if there are any or specific connected outlets.
i.e. it is not part of the api. At the moment we test for this.connections which could be flaky. Could there be a undefined check in there? Would be open to doing a pull request if wanted.

**Comment by Serabe** [comment]
Hello,

can you please provide a reproduction in a [jsbin](http://emberjs.jsbin.com/), [ember-twiddle](https://ember-twiddle.com/) or repo? Having as few dependencies as possible makes debugging simpler.

Thank you so much for your report!

**Comment by pixelhandler** [comment]
Closing as this has been inactive for some time
