### ISSUE TITLE
Ember 2.9.0 beta: Yielded value using with-helper in component block form breaks if null or undefined

### ISSUE THREAD

**Issue by anssikin** [emberjs/ember.js#14326]
Subject (and issue explanation) was slightly hard to come up with, sorry about that.

In short, the issue appears when yielding a value in component and referring to the value's property in the components block form in `with-helper`, if the given value is either null or undefined. This issue did not exist in Ember 2.8.1, so I'm assuming this has something to do with Glimmer 2. Here is a Ember Twiddle to demonstrate the issue: https://ember-twiddle.com/386db48506ac762153a3675bd6a39576/f4742940fc186cba83e70b5a235a7934ae84b379?openFiles=templates.application.hbs%2C . The issue can be seen via console, where a error should occur when switching Ember dependency to `beta` (and no error when switching to `release`).

As a practical use case, I'm using a `async-render component` which takes a promise as source property and internally uses a `Ember.PromiseProxyMixin` object, essentially rendering the content once the promise has resolved. If the promise had not resolved yet (the `prop.isFulfilled` was false), the component template would yield null. The `with-helper` was used to make reading the template a little easier. I acknowledge that this is potentially a design flaw on my part, but Ember 2.8.1 allowed this behavior, so a confirmation would be nice whether this is intended.

**Comment by Serabe** [comment]
Thank you for your report!

**Comment by foxnewsnetwork** [comment]
Currently on ember 2.10.0 and this bug seems to still be alive; consider the following twiddle:

https://ember-twiddle.com/18868df4738de43f6fdf99885dd53419?openFiles=templates.application.hbs%2C

Notably, the following handlebars snippet behaves incorrectly
```handlebars
{{#with false as |x|}}
  I should render, but I'm not {{x}}
{{/with}}
```

**Comment by Serabe** [comment]
The problem in your twiddle is that you are using different version in `"ember"` than in `"ember-template"`. If you match the version to 2.10 you will see no error.

Furthermore, that template should not render the text. As stated [in the documentation](http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_with):

> If the aliased property is "falsey", for example: false, undefined null, "", 0, NaN or an empty array, the block will not be rendered.

Thank you!

**Comment by foxnewsnetwork** [comment]
Thanks @Serabe, I was unaware `with` doubles as an `if` block
