### ISSUE TITLE
decamelize, dasherize fail when string is in the form XXXXxxxXxxx (part of word is all capitals)

### ISSUE THREAD

**Issue by vasilakisfil** [emberjs/ember.js#14321]
For instance:

```javascript
"CEOBirthYear".dasherize()
//returns "ceobirth-year", it should return "ceo-birth-year"
"CEOBirthYear".decamelize()
//returns "ceobirth_year", it should return "ceo_birth_year"
```

It's easy to figure out that because the capital letters end at letter `B`. So you can assume that all the previous capital letters before `B` is another word element.

(Rails does the same assumption)

**Comment by Serabe** [comment]
This is the behaviour since, at least, [1.13](https://ember-twiddle.com/8c20064cd693ca08af3e475f518d1c9a?openFiles=twiddle.json%2C). This is not a regression, like #13042.

**Comment by rwjblue** [comment]
Yeah, this doesn't really seem like a bug.  There are corner cases no matter which way we go, and the current behavior has existed for quite a long time.  Changing the result of these helper functions would be a breaking change to existing users.

Thank you for reporting, but I'm going to close this for now...

**Comment by vasilakisfil** [comment]
ok! Yes it's not a bug but I still think that these methods can be improved though and maybe this should be moved to the backlog for a later Ember version (like 3.0).

Thank you!
