### ISSUE TITLE
Array.includes documentation should mention ember-runtime-enumerable-includes flag

### ISSUE THREAD

**Issue by matthiasleitner** [emberjs/ember.js#14322]
We just stumbled across the issue that we where using Ember.Array.includes in our 2.7 apps finding it to be `undefined` in browser like IE 11 which do not have native Array.prototype.includes defined.

Is this the intended behaviour for 2.7? We are now using [ember-runtime-enumerable-includes-polyfill](https://github.com/rwjblue/ember-runtime-enumerable-includes-polyfill) which works perfectly fine but the documentation does not clearly indicate this. Just the[ deprecation guide for 2.8 ](http://emberjs.com/deprecations/v2.x/#toc_enumerable-contains) suggests the usage of the addon. 

I am happy to create a PR when the intended behaviour is clarified.

**Comment by Serabe** [comment]
Yes. `Enumerable#includes` and `Array#includes` were added in 2.8, therefore in 2.7 it relied on the implementation by the vendor. Until then, the method was `Enumerable#contains` and `Array#contains`.

Thank you!
