### ISSUE TITLE
EventDispatcher should never be instantiated in fastboot mode.

### ISSUE THREAD

**Issue by martndemus** [emberjs/ember.js#14333]
`EventDispatcher should never be instantiated in fastboot mode. Please report this as an Ember bug.`

So that is what I'm doing.

The error is triggered by https://github.com/ronco/ember-cli-head/blob/master/app-lt-2-9/instance-initializers/fastboot/head.js#L6

I tested this with versions `2.9.0-beta.3` and `2.10.0-canary+6ea3ed0c`.

See also: https://github.com/ember-fastboot/ember-cli-fastboot/issues/266

**Comment by rwjblue** [comment]
Please ensure that you are using the lastest version of ember-cli-head?

**Comment by martndemus** [comment]
@rwjblue I am using `0.1.1` of ember-cli-head.

**Comment by rwjblue** [comment]
You shouldn't be getting the lt-2-9 version, as it will cause this issue.

**Comment by martndemus** [comment]
After a bit more debugging, I found that ember-cli-meta-tags is the real cause of the error.

**Comment by martndemus** [comment]
```
# using ember-cli 2.9.0-beta.1
ember new test-app
cd test-app
ember install ember-cli-fastboot
ember install ember-cli-head
```

This works

```
ember install ember-cli-meta-tags
```

Now it stops working.

Tested using `fastboot-app-server`

**Comment by rwjblue** [comment]
Awesome, thanks for repro steps.

**Comment by martndemus** [comment]
Solution found: https://github.com/ronco/ember-cli-meta-tags/pull/44
