### ISSUE TITLE
Second level of service are not injected when calling from template

### ISSUE THREAD

**Issue by cbou** [emberjs/ember.js#14334]
When calling a service function from a template e.g. `onClick={{action myFirstLevel.hello}}`, the services which should be injected into `myFirstLevel` stay undefined.

The call through a component action is working.

```hbs
<button onClick={{action myFirstLevel.hello}}>Hello Service</button>
<button onClick={{action 'hello'}}>Hello Action</button>
```

```javascript
App = Ember.Application.create();

App.MyFirstLevelService = Ember.Service.extend({
  mySecondLevel: Ember.inject.service(),
  hello: function() {
    console.log('Hello first level');
    this.get('mySecondLevel').hello();
  }
});

App.MySecondLevelService = Ember.Service.extend({
  hello: function() {
    console.log('Hello second level');
  }
});

App.MyButtonComponent = Ember.Component.extend({
  myFirstLevel: Ember.inject.service(),
  
  actions: {
    hello:  function() {
      this.get('myFirstLevel').hello();
    }
  }
});
```

http://emberjs.jsbin.com/conaxaheno/1/edit?html,js,console,output

**Comment by locks** [comment]
If you log `this` from within the `hello` function of `MyFirstLevelService`, you'll notice that it's `MyButtonComponent`. So the problem isn't that the service isn't being injected, but that `{{action}}` binds the action to the current context, which is this case is `MyButtonComponent`.
Here's how to make it work:

    <button onClick={{action myFirstLevel.hello target=myFirstLevel}}>Hello Service</button>

Hope this helps!

**Comment by cbou** [comment]
Thanks for your help. Unfortunately it didn't worked.

**Comment by locks** [comment]
@cbou you can do `<button {{action myFirstLevel.hello}}>Hello Service</button>`. Doing the DOM event handler instead messes up the contexts.

**Comment by cbou** [comment]
@locks Yes this work now. Is that a bug?

I'm often confused between both syntax and I'm sure I'm not alone. Te me both should act exactly the same way. Is there a reason why it's not the case?

**Comment by locks** [comment]
`<button {{action 'actionName'}}>` defines an Ember action on the button. Ember is responsible for managing it.
`<button onClick={{action 'actionName'}}>` defines an event handler for the DOM `onClick` event. So it's basically the browser that manages it, and eventually triggers the event handler.

You can ask in our Slack channel for a more technical explanation, I don't know the nitty gritty.
