### ISSUE TITLE
each-in does not render a hash of closure components

### ISSUE THREAD

**Issue by poteto** [emberjs/ember.js#14336]
The use-case is that one of our apps makes liberal use of modals which need to be "pluggable" with different sections. We tried the following expecting it to work:

```hbs
{{x-modal
    sections=(hash
      general=(component "my-general-section")
      specific=(component "my-specific-section")
      ...)
}}
```

And then iterating over that hash in `x-modal/template.hbs`:

```hbs
{{#each-in sections as |title x-section|}}
  {{x-section title=title foo=foo}}
{{/each-in}}
```

However, this doesn't work, and I've made a reproduction in this [twiddle](https://ember-twiddle.com/ebcb5ec7c6eb6b2127ea03b9f2f4696d?openFiles=templates.application.hbs%2C)

I'm guessing that this use of the `each-in` helper with a hash of closure components was never really intended, but should it?

**Comment by rwjblue** [comment]
Work around for now is to use `{{component someClosureComponentHere}}`.  [Demo here](https://ember-twiddle.com/9ccd2eb7e6945d039975f6429c46ef5a?openFiles=templates.components.x-pluggable-each.hbs%2C)

**Comment by Serabe** [comment]
No, it shouldn't. For a contextual component to be rendered without the `{{component}}` helper it needs to have a dot in the path.

@rwjblue's twiddle is the right approach in this case. See [the original RFC](https://github.com/emberjs/rfcs/blob/master/text/0064-contextual-component-lookup.md#component-helper-shorthand) for more details on the shorthand.

Thank you!
