### ISSUE TITLE
 belongsTo relation call returns null within observer

### ISSUE THREAD

**Issue by apokinsocha** [emberjs/ember.js#14348]
Hi,

I have belongsTo relation on a model:

```
//book.js
export default DS.Model.extend({
    name: attr('string'),
    item: belongsTo('item', {async: true}),
});

//item.js
export default DS.Model.extend({
    name: attr('string')
});
```

When I call:
```

let b = store.createRecord('book', {name: 'test'});

b.save().then(function(b) {
  //b is saved correctly here

  b.get('item').then(function(item) {
    
  //item relation is gotten successfully - all works well

 });
```

});

(NOTE: I'm not initially setting the item relation when creating the book record, because this is determined by the backend response)

...everything works as expected so far.

now, somewhere else I have an observer that fires when a change to a books array is made.

when it fires I'm iterating over the books array with the newly saved book and calling the relation item the exact same way as I do right after saving the book.

but for some reason item relation on the book record is always null within the observer.
```

booksChanged: on('init', observer('books.[]', function() {
   
//this gets triggered
    let b = this.get('books').get('firstObject');//->just assume the book created is the first object
   
   b.get('item').then(function(item) {
     
     //item is null???

   });
   

}));
```

version 2.7 ember and ember-data.

any thoughts?

thanks

**Comment by btecu** [comment]
Wrong repo, should be `ember-data`.

You should avoid observers. However, you might want to observe changes to item if that's what you're after: `observer('books.@each.item',`.

**Comment by apokinsocha** [comment]
the observer (with the books.[]) is called when a book is added/removed.
when the observer fires it will transform the array into some other data structure, but will need to access the item relation in the process.
I don't see how else this could be done without an observer of some type, can you clarify?
unless what you seem to be saying is that the relation will not be called because the initial observer needs to also observe the relation?
thanks (and yes, I will take this up with ember data soon and close here)

**Comment by btecu** [comment]
You've kind of described a computed property.

**Comment by apokinsocha** [comment]
looks like the issue has been resolved, took another route to use actions instead of observer in this case.
