### ISSUE TITLE
tag-less component with bound id attribute throwing an error

### ISSUE THREAD

**Issue by ctusch** [emberjs/ember.js#14369]
I ran into this issue while updating our application from Ember 2.4.2 to 2.8.0. Suddenly our subroutes wouldn't render anymore. Turns out that while you can assign an id to a tag-less component, the id's value must be a constant. Unfortunately in our applicaton the id is bound to a property.

There is a related issue (and PR) by @rwjblue that fixed this behavior for constant values: #14105 

Here is a [twiddle](https://ember-twiddle.com/7d531ee89c0b39c6aeaa0d71b843c682?openFiles=templates.application.hbs%2Ctemplates.components.my-component.hbs) for easy reproduction. The error text reads:
> ember.debug.js:6778 Uncaught Error: Assertion Failed: You cannot use `elementId` on a tag-less component: <twiddle@component:my-component::ember354>

The assertion can be found [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/syntax/curly-component.js#L53).

**Comment by HeroicEric** [comment]
just wanted to add that this seems to be fixed in beta and canary

**Comment by ctusch** [comment]
Interesting, looking at the callstack and searching the sources the whole infrastructure changed. Does this have something to do with Glimmer 2?

**Comment by chancancode** [comment]
@HeroicEric as I mentioned yesterday, we should probably have a separate test for this scenario (id is used as a regular bound property, but not passed down to a child's elementId). Do you have time to tackle that? :smile:

**Comment by HeroicEric** [comment]
@chancancode I think I missed the conversation you're referring to but I can look into it 😄

**Comment by pixelhandler** [comment]
@HeroicEric should this be closed as #14382 was merged?

**Comment by rwjblue** [comment]
Yeah, closing this (as fixed in release branch).
