### ISSUE TITLE
Custom inflector rules are ignored on hasMany relations when testing

### ISSUE THREAD

**Issue by Znegl** [emberjs/ember.js#14368]
We have a model named 'slide' and a model named 'slide-data'.
A slide has many slide-data.

We've set up a custom inflector rule like this: `inflector.uncountable('slide-data');` and added it to our app.

It's all working as intended when using it in production.

However, when we try to run Embers tests, the error `No model was found for 'slide-datum'` is thrown in both the slide model unit test and the slide serializer unit test.

These are the guidelines we followed when creating the custom inflector rules: https://guides.emberjs.com/v2.8.0/models/customizing-adapters/

**Comment by btecu** [comment]
Should be under `ember-data` repository: https://github.com/emberjs/data

**Comment by Znegl** [comment]
Thanks! I've created it there and will close this ticket.

**Comment by Znegl** [comment]
Link if anyone else is interested: https://github.com/emberjs/data/issues/4557
