### ISSUE TITLE
Htmlbars readonly helper not documented

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/ember.js#14376]
The `readonly` helper as described in http://emberup.co/bindings-with-htmlbars-helpers/ is not documented in http://emberjs.com/api/classes/Ember.Templates.helpers.html. Is it private?

**Comment by btecu** [comment]
Most likely it was part of the `GlimmerComponent` effort that didn't get completed (`attrs`, `readonly`...)

**Comment by Serabe** [comment]
AFAIK, it is public.

**Comment by rwjblue** [comment]
I would consider it public, likely it just needs to be documented (and was a documentation oversight during 1.13).

**Comment by mwpastore** [comment]
It's documented, but it's still marked private. Can we just fix [this line](https://github.com/emberjs/ember.js/blob/d0de6ae3a77ab5a5156e62d3be7543302caf8c0f/packages/ember-glimmer/lib/helpers/readonly.js#L105)?

**Comment by locks** [comment]
@mwpastore We can not: https://github.com/emberjs/ember.js/pull/14377#issuecomment-260116327.
