### ISSUE TITLE
`(readonly array)` being treated as unbounded

### ISSUE THREAD

**Issue by locks** [emberjs/ember.js#14378]
Reproduction: https://ember-twiddle.com/46997e542fbb339a730316663a92653f/f7fedd5b76416efd147794f720a6b258f5e03ccb

**Comment by Serabe** [comment]
I don't think this is a bug. `readonly` only affects `foo` here, meaning that, from within the component: `this.set('foo', 'bar')` would not propagate upwards. Given that `foo` is an array, modifying it in place should make these changes visible from outside.

* [Twiddle for setting foo an not modifying it in place](https://ember-twiddle.com/264989033b8a1635373e291ae78609e3?openFiles=templates.components.my-component.hbs%2C).
* [Twiddle showing a similar case for non-array objects](https://ember-twiddle.com/f033656c2d870bf5e4c5276a67f46866?openFiles=templates.application.hbs%2C)

**Comment by locks** [comment]
@Serabe If you check the Twiddle, `{{#each childFoo as |i|}}` updates properly because of the array observer, but `{{foo}}` does not. That second binding is the one I'm saying is unbounded. Maybe it's calling `.toString` on the value and somehow severing the binding? @rwjblue said this needs some investigating to confirm, or not, the bug.

**Comment by Serabe** [comment]
Sorry, I was checking the vaues above and did not even notice the line below :(

**Comment by Serabe** [comment]
It does look ike a problem with using the property directly :$. [Twiddle](https://ember-twiddle.com/cc09226dafff244959c634fa58eb4773?openFiles=twiddle.json%2C)

**Comment by mitchlloyd** [comment]
@locks I don't think this is related to `readonly` because removing that helper from your Twiddle produces the same output. 

Adding `{{foo}}` to a template does not watch all of the additions, deletions, and changes to the items of the array, it only watches for the identity of `foo` to change. 

`{{#each foo as |i|}}` on the other hand watches for additions, deletions, and identity changes of `foo`.

Very tricky gotcha.

**Comment by pixelhandler** [comment]
@Serabe Your last Twiddle demonstrates the content of @locks PR, see #14377 

> When passing property that is a complex object vs. a primitive object, only the reference to the object is protected using the `readonly` helper. The contents of a bound property that is an `Object` or `Array` can be changed in both the `outerProperty` and the `componentProperty` simultaneously. This read only (or one-way) binding behaves similar to the `const` keyword in ES2015.

**Comment by locks** [comment]
@pixelhandler I disagree, I think the actual problem here is that array bindings are being turned into unbound ones because of the serialization of the Array. I need some more knowledgeable eyes on it.

**Comment by Serabe** [comment]
@locks: I don't think that is the problem. `foo` is not being updated, `foo.[]` is. This already happened when passing arrays to helpers and the workaround was to use `(get foo "[]")` as parameter. See [this tweedle](https://ember-twiddle.com/46997e542fbb339a730316663a92653f/f7fedd5b76416efd147794f720a6b258f5e03ccb?openFiles=templates.components.my-component.hbs%2C).

Sadly, `{{get foo "[]"}}` does not update either. I'll take a deeper look later this week.

**Comment by Serabe** [comment]
I had a quick (~2h) look this weekend but I got nothing. I'll try to document this to the triage meeting.

**Comment by locks** [comment]
Let's let this one slide into oblivion :P
