### ISSUE TITLE
[Beta Bug] Intermixing attrs and non-attrs on closure actions become mutable cells

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#14379]
Repro:
https://ember-twiddle.com/1be97289c3f77efac3ac851a22626595?openFiles=templates.application.hbs%2Ctemplates.components.my-middleman.hbs

I'm not sure how we did this before in HTMLBars, but when you go from `foo=(action 'foo')` and pass it to child as `fooAction` and that child tries to call it as `this.attrs.fooAction`, it will be a `MutableCell` and not the actual closure action.

**Comment by rwjblue** [comment]
@chadhietala - I believe this issue is basically what I have submitted a failing test PR in https://github.com/emberjs/ember.js/pull/13996 for.  Can you confirm?

**Comment by chadhietala** [comment]
Yes

**Comment by rwjblue** [comment]
Fixed by #13996
