### ISSUE TITLE
[Beta Bug] attrs in bindings are always truthy

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#14381]
*Repro*
https://ember-twiddle.com/7ed79a745f34ce66d44f6b23d5465758?openFiles=templates.application.hbs%2Ctemplates.components.my-component.hbs

We are likely not reading `value` from the `MutableCell` and thus the attribute bindings are always true.

**Comment by HeroicEric** [comment]
> We are likely not reading value from the MutableCell and thus the attribute bindings are always true.

Yep. It looks like https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/utils/bindings.js#L175, `inner` is a `NestedPropertyReference` and `inner.value()` is a `MutableCell`, like you said.

**Comment by chadhietala** [comment]
See #14384

**Comment by HeroicEric** [comment]
I believe this was fixed by ^^ https://github.com/emberjs/ember.js/pull/14384
