### ISSUE TITLE
Glimmer2 willInsertElement does not fire for tagless components.

### ISSUE THREAD

**Issue by runspired** [emberjs/ember.js#14398]
Replication: https://ember-twiddle.com/0196406cd88aac368ba8b82bd88393b4?openFiles=components.tagless-component.js%2Ctemplates.components.tagless-component.hbs

While true that `didInsertElement` and `willInsertElement` make less semantic sense for tagless components, they function as standings for `didRenderInitially` and `willRenderInitially`

**Comment by rwjblue** [comment]
Thanks for reporting!

For folks running into this a work around for now is willRender/didRender and track initial firing vs subsequent (obviously not ideal)..

**Comment by rwjblue** [comment]
The reason for this is that we are triggering the `willInsertElement` hook from within `didCreateElement` (in the curly component manager [here](https://github.com/emberjs/ember.js/blob/12f4fc0e6142e740a8cc4d566d9f3fbbc0b5a604/packages/ember-glimmer/lib/syntax/curly-component.js#L289)), and `didCreateElement` is only called on the manager when there is an actual element created.  However, `didInsertElement` is called inside `didCreate` ([here](https://github.com/emberjs/ember.js/blob/12f4fc0e6142e740a8cc4d566d9f3fbbc0b5a604/packages/ember-glimmer/lib/syntax/curly-component.js#L305)).  

To be compatible we need to correct `willInsertElement` to fire in tagless components...
