### ISSUE TITLE
explore/consider removal/deprecation of enumerable events (and hasArrayObservers/hasEnumerableObservers)

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#14405]
`@enumerable:change` et al

**Comment by chancancode** [comment]
@stefanpenner will work on this this week

**Comment by chancancode** [comment]
I folded #14406 into this

**Comment by mmun** [comment]
Enumerable events were removed in https://github.com/emberjs/ember.js/pull/16116. `hasArrayObserver` is still around but we can add a deprecation for that separately.
