### ISSUE TITLE
Positional parameters for components have two way binding in 2.9.0-beta

### ISSUE THREAD

**Issue by dzaman** [emberjs/ember.js#14408]
Positional parameters for components behave differently in `2.9.0-beta.4` than they do in `2.8.1`. In `2.8.1` they have a one-way binding and in `2.9.0-beta.4` they have a two-way binding. I looked around and couldn't find any documentation suggesting this change was intentional.

Click 'change' in [this twiddle](https://ember-twiddle.com/70b9354dca1429a87ed728b71fa61c7b) to reproduce and compare 'beta' (2.9.0-beta.4) to 'release' (2.8.1).

**Comment by Serabe** [comment]
AFAIK, this was a bug in previous versions.

**Comment by rwjblue** [comment]
Confirm. It was a bug that it was previously one way to begin with.

**Comment by Serabe** [comment]
Thank you. Closing this issue then.

Thank you all!
