### ISSUE TITLE
didInsertElement running twice on 2.8.0

### ISSUE THREAD

**Issue by miguelcobain** [emberjs/ember.js#14409]
While modifying a property inside the `didInsertElement` hook, I get a deprecation as expected. However, in ember versions 2.8.0 and above the `didInsertElement` hook runs twice.

Here is a reproduction:
https://ember-twiddle.com/0f24a991a90dd2c18dc97a790452436e?openFiles=twiddle.json%2C

You should be able to see two logs on ember versions 2.8.0 and above.

/cc @rwjblue

**Comment by rwjblue** [comment]
Just to confirm, you mean it's firing twice on 2.9 and above or 2.8 and above?

**Comment by miguelcobain** [comment]
@rwjblue 2.8 and above, so the bug was probably introduced in 2.8.

**Comment by rwjblue** [comment]
Hmm, I do not see two log messages in that twiddle for beta or release branches (which would indicate 2.9+ are working properly).  Can you confirm?

**Comment by miguelcobain** [comment]
You're right! I could almost swear that I've seen two log messages in beta. :open_mouth: 
Anyway, looks like beta is fine now.

Is a 2.8.x release "needed" to fix this?

**Comment by rwjblue** [comment]
@miguelcobain - Yeah, once we figure out what is going wrong 😝 ...

**Comment by Serabe** [comment]
If the `run` is scheduled for `afterRender` the log is only shown once. Might this be related to a rerender warning not being shown?

[Twiddle](https://ember-twiddle.com/8737af3d47b72265bf5e4e5fe56d756a?openFiles=components.my-component.js%2C)

**Comment by rwjblue** [comment]
Just re-reviewed this, and I am curious why you are using a nested run loop (`Ember.run(() => { })`) for this? As @Serabe mentioned, a work around for now is to either use `Ember.run.schedule('afterRender', () => {})` or just omit the `Ember.run` altogether (depending on why it was needed initially)...

**Comment by Serabe** [comment]
@miguelcobain: can you check rwjblue's comment please? Thank you!

**Comment by miguelcobain** [comment]
Let's close this for now. I'll reopen if I can come up with a more meaningful reproduction of the problem.
