### ISSUE TITLE
computed.sort doesn't update when the dependant array is set

### ISSUE THREAD

**Issue by aexmachina** [emberjs/ember.js#14404]
I've created an Ember Twiddle that shows the issue:

https://ember-twiddle.com/236ec5a7298b74b1847edcdccbf36f15?fileTreeShown=false&openFiles=controllers.application.js%2C

I would expect calling `this.set('rows')` would cause the computed property to update.

**Comment by rwjblue** [comment]
Setting to the same value (as determined by `===`) does not force CP's to invalidate.

In your Twiddle you can either use `pushObject` to add items to the array, or slice the array and set to the new instance.

This may be a gotcha (and a PR updating the documentation would definitely be welcome), but it isn't a bug so I am going to go ahead and close this out for now.  If I've misunderstood something please let me know and I can reopen...

**Comment by aexmachina** [comment]
Thanks Robert. The problem we're seeing is coming from a route transition that's setting the dependant property, but the `computed.sort` doesn't get updated. If I get a chance I'll try to reproduce.
