### ISSUE TITLE
[hidden] should be bound by default

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/ember.js#14412]
The `[hidden]` attribute is valid for all elements. It would be nice to be able to use it for components that need to be in the DOM, but not visible. The easiest way to do that is to add it to the default set of `attributeBindings` for `Ember.Component`.

You can see the current behavior in [this twiddle](https://ember-twiddle.com/3cc9a52f218a89b04b0710ec81f45152?openFiles=templates.application.hbs%2C).

**Comment by rwjblue** [comment]
Hmm.  I think that this would be a nice addon for todays components, but the "real" solution is the conceptual (but still super nebulous) "angle bracket components" where the top level tag of any component includes all things passed to it at invocation.  

My concern is that adding additional `attributeBindings` for all components where it is likely to only be used on a relatively small subset is going to have a negative performance impact.

**Comment by rwjblue** [comment]
Also, I think in general, this is a feature request so it should be an RFC issue?

**Comment by chancancode** [comment]
Is there a reason isVisible won't work? We causally brought up using the
hidden attribute for isVisible to avoid using inline styles

**Comment by jamesarosen** [comment]
> the "real" solution is the conceptual (but still super nebulous) "angle bracket components" where the top level tag of any component includes all things passed to it at invocation.

That seems far off.

> this is a feature request so it should be an RFC issue

I couldn't find any default set of bindings, but I wasn't sure if I had missed them, so I wasn't sure whether this was an accidental omission or just a new feature. I'm happy to open as RFC.

> Is there a reason isVisible won't work?

I was using that in older Ember versions, but was told to avoid it. Secondly because `[hidden]` is semantically correct. And lastly because you can write CSS for `[hidden]` such as animating the toggle.

**Comment by rwjblue** [comment]
> That seems far off.

Agreed, but an addon is just a command away :smiley:

**Comment by jamesarosen** [comment]
Closing. I'll open as an RFC with a list of all of the common attributes.
