### ISSUE TITLE
Using "send" as an action name breaks things

### ISSUE THREAD

**Issue by dwickern** [emberjs/ember.js#14424]
[Twiddle](https://ember-twiddle.com/397e1237ee04dca875a3d0de5c8924b8?openFiles=components.blog-post.js%2Ctemplates.components.blog-post.hbs)

This is an imaginary component of a blogging system where you can send or delete blog posts.
```
{{blog-post send=(action "sendBlogPost") delete=(action "deleteBlogPost")}}
```

Expected: Clicking the "Delete" button will `alert('delete')`
Actual: Clicking the "Delete" button will `alert('send')`

This template will replace `Ember.Component.prototype.send` on the component. As a result, all actions on the component will call the closure action `(action "sendBlogPost")`, which is super confusing!

Ideally this would just work, because "send" is a natural name to use for an action. Alternatively, ember could warn the user.

**Comment by pixelhandler** [comment]
@dwickern The twiddle example does show he confused behavior of defining an action named `send`. Also I noticed you have `sendAction` in the component. I just took a look at the guide page on actions for components, https://guides.emberjs.com/v2.8.0/components/triggering-changes-with-actions/ I can't find `sendAction` mentioned. Historically that was the primary way to fire an action in a component.  It seems these days the community is generally in favor or using closure actions, which are callable and you do have in the example. Perhaps replace `sendAction('send')` with `this.get('on-send')()` See this fork of your twiddle, https://ember-twiddle.com/3e51b44eb889a8e6b2cc21c35ad10819?openFiles=components.blog-post.js%2Ctemplates.components.blog-post.hbs

I'm not able to
