### ISSUE TITLE
[Beta Bug] `{{#each this.attrs.* as |item|}}{{/each}}` no longer works

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#14423]
Repro: https://ember-twiddle.com/e745d78ac6b44a6cfc1c891eaff04a1a?openFiles=templates.application.hbs%2Ctemplates.components.my-component.hbs

One use to be able to do this in a component:

```hbs
{{#each this.attrs.items as |item|}}
  {{item}}
{{/each}}
```

**Comment by rwjblue** [comment]
Fixed by #14425
