### ISSUE TITLE
Max callstack exceeded when calling destroy on component

### ISSUE THREAD

**Issue by tehmaestro** [emberjs/ember.js#14437]
Hi, on Ember 2.8.0, I get a Max callstack error when calling `this.destroy()` inside a component. It works on previous ember versions. Here's a twiddle https://ember-twiddle.com/e19414cff98805548152a6be13a8823c?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs

Thanks.

**Comment by rwjblue** [comment]
Hmm, why are you destroying the component manually?  This seems like a somewhat odd thing to do (as in the twiddle itself), are you doing something different in your app code?

**Comment by tehmaestro** [comment]
Hi, thanks for answering. I am destroying the component manually as a safety measure.
  I have a component that renders over the whole screen, it is something like a UI coach mark, and so, if I encounter any problems while animating the various elements of the coach mark, I manually destroy the component so that it doesn't block the UI of my app (with an empty, overlayed div over the main UI contents, the users cannot interact with the app anymore).

 I could probably do something like `sendAction('closeCoachMark')` which would set the `showCoachMark` property to false in the template, so the component is actually destroyed. Would this be a good way of handling this?

 However, just wanted to let you guys know of the problem, which wasn't there in previous ember versions. I actually discovered this by having a `this._super()` call inside a `.on('willDestroyElement')` listener I had in one of my components.

**Comment by Serabe** [comment]
Yes, that would work perfectly. Thank you for the report!
