### ISSUE TITLE
`didReceiveAttrs` `didInitAttrs` no longer called before `finishChains`

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#14439]
__Repro:__
https://ember-twiddle.com/ced7d38a0502c9df2d055f6bb91c5d0a?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs

[edit: updated title to be more accurate)

**Comment by stefanpenner** [comment]
previously, `didReceiveAttrs` `didInitAttrs` where invoked by `POST_INIT`, order was:

* `this.init();`
* `POST_INIT`
  * `didInitAttrs`
  * `didReceiveAttrs`
* `finishChains(this)`
* `send('init')`

This means, work done during `didInitAttrs` and `didRecieveAttrs` on initial render remained inert and did not emit change events. This also means, by the time the object construction completes both `didInitAttrs` and `didRecieveAttrs` will have been invoked.
