### ISSUE TITLE
Quest: Document Solutions to "Titlebar Problem"

### ISSUE THREAD

**Issue by ef4** [emberjs/ember.js#14430]
[RFC 143](https://github.com/emberjs/rfcs/pull/143) included discussion around properly configuring text editors so that it's easy for developers to distinguish filenames within a typical Ember app, even though those names necessarily have some repetition. The canonical example is that files like these:

```
src/components/date-picker/component.js
src/components/list-paginator/component.js
```

should be readily distinguishable despite sharing a common ending.

This quest issue exists so that people can chime in on what (if anything) is required to make all the popular editors do this nicely.
# Editors
- [x] Atom
- [x] Brackets
- [x] Chocolat
- [ ] Chrome Dev Tools
- [x] Emacs
- [x] JetBrains 
- [x] Sublime text
- [ ] Vim
- [x] Visual Studio Code

Please suggest others as long as you actually use them to work on Ember apps.
# Solutions
## Atom (@locks)

No configuration required:

![Atom: Titlebar problem](https://cloud.githubusercontent.com/assets/32344/19178372/08944ff0-8c4a-11e6-9e1e-cc9888aee743.png)
# Brackets (@locks)

No configuration required:

![Brackets - Titlebar problem](https://cloud.githubusercontent.com/assets/32344/19190968/35afb2d8-8c98-11e6-8f38-09615fd28cc0.png)
## Emacs

The out-of-the-box behavior since Emacs 24.4 for the two example files is that they appear as `component.js<date-picker>` and `component.js<list-paginator>`. So no configuration is required.

To see all the options for customizing this behavior, see `M-x customize-group uniquify`.
## Visual Studio Code (taken from @tomdale comment on RFC 143)

No configuration required:

<img width="423" alt="component js - starspot 2016-10-06 17-15-03" src="https://cloud.githubusercontent.com/assets/90888/19170984/9a8f3864-8be8-11e6-8b0d-e1b9a5e488ac.png">
## JetBrains family (PHPStorm, WebStorm, IntelliJ, RubyMine)

For the JetBrains family of IDEs make sure to uncheck the "Small labels in editor tabs" setting under `Preferences > Appearance & Behavior > Appearance`:

![image](https://cloud.githubusercontent.com/assets/1325249/19183769/2ff34710-8c7a-11e6-8654-90e1d982f7bc.png)

This will add the parent directory to the tab label (as soon as there is ambiguity):

![image](https://cloud.githubusercontent.com/assets/1325249/19183807/5dfb4bb2-8c7a-11e6-87a5-456b875a82c9.png)

Tested with PHPStorm 2016, but should probably apply to the whole familiy of IDEs (WebStorm, IntelliJ, RubyMine etc.)
## Sublime Text (@locks)

No configuration required:

![screen shot 2016-10-07 at 14 16 24](https://cloud.githubusercontent.com/assets/32344/19191119/ea2fe3ea-8c98-11e6-958b-86be9a60638d.png)
## Chocolat (@locks)

No configuration required:

![Chocolat: Titlebar problem](https://cloud.githubusercontent.com/assets/32344/19178284/375ca158-8c49-11e6-940f-2861cf77d5d7.png)

**Comment by DingoEatingFuzz** [comment]
Here's what it looks like in the chrome sources tab:

<img width="751" alt="screen shot 2016-10-06 at 7 24 11 pm" src="https://cloud.githubusercontent.com/assets/174740/19177054/9232046e-8bfa-11e6-9338-056878091470.png">

**Comment by ef4** [comment]
Ugh, yes, chrome dev tools. Added that to the list.

**Comment by rtm** [comment]
To my knowledge this problem is unsolvable in Chrome dev tools, which is a place where lots of folks spend quite a bit of their time.

> even though those names necessarily have some repetition

Not "necessarily", but rather "have been designed in a way which has".

**Comment by simonihmig** [comment]
For the JetBrains family of IDEs make sure to uncheck the "Small labels in editor tabs" setting under `Preferences > Appearance & Behavior > Appearance`:

![image](https://cloud.githubusercontent.com/assets/1325249/19183769/2ff34710-8c7a-11e6-8654-90e1d982f7bc.png)

This will add the parent directory to the tab label (as soon as there is ambiguity):

![image](https://cloud.githubusercontent.com/assets/1325249/19183807/5dfb4bb2-8c7a-11e6-87a5-456b875a82c9.png)

Tested with PHPStorm 2016, but should probably apply to the whole familiy of IDEs (WebStorm, IntelliJ, RubyMine etc.)

**Comment by rtm** [comment]
Whereas most of these techniques do solve the basic problem, it remains the case that substantial title bar real estate is being wasted by the meaningless and semantically vacuous "component" part of the title.

**Comment by workmanw** [comment]
@ef4 For Atom you've noted, _"No configuration required"_ . But I'm using Atom 1.10.2 and I do not see this behavior. Do you have an atom package installed?

**Comment by workmanw** [comment]
You might consider adding the IntelliJ IDE Editor suite to this list (WebStorm, PyCharm, RubyMine, etc). I know some full stack engineers, even work with a few, who prefer to use these IDEs.

**Comment by pichfl** [comment]
I work with Sublime Text 3 on Mac OS X and it shows the folder name in both sidebar and tabs if two files with the same filename are open.
![Cutout Screenshot of Sublime Text 3 Sidebar and Tab bar showing open files with the same name](https://cloud.githubusercontent.com/assets/194641/19189392/1c151426-8c98-11e6-9c0a-46680f52ffed.png)

**Comment by dgeb** [comment]
> Whereas most of these techniques do solve the basic problem, it remains the case that substantial title bar real estate is being wasted by the meaningless and semantically vacuous "component" part of the title.

@rtm `type` is not meaningless when distinguishing between a component, a model, and a route that share a common `name`.

**Comment by locks** [comment]
@workmanw I was the one that added Atom. I just tried it out on a clean environment and I see the same disambiguating behaviour. Reach me in #topic-editors.

**Comment by locks** [comment]
@pichfl thank you for the report, I didn't notice it and added my own screenshot. glad to see confirmation :)

**Comment by dfreeman** [comment]
One (weird) pain point with Atom is that it only disambiguates tabs with the same name when they're in the same pane.

![image](https://cloud.githubusercontent.com/assets/108688/19193515/4ef443be-8c78-11e6-9384-272b1a9cb297.png)

The `template.hbs` on the left is actually the same file as the one in the inactive tab on the right, but they have different labels :(

**Comment by simonihmig** [comment]
> @rtm type is not meaningless when distinguishing between a component, a model, and a route that share a common name.

@dgeb is absolutely right. When working on components you will most often have `component.js` and `template.hbs` open at the same time, so type and name are both equally relevant!

**Comment by HeroicEric** [comment]
While there a few existing vim plugins to modify the way tabs are displayed, I didn't see any that could easily be configured to match the examples from the other editors here but I also didn't look very deeply into them so it does probably exist 😛 .

Anyway, it's straightforward to modify your tabline settings in vim to get something nice like the others here so I threw together [a plugin that does it for you](https://github.com/HeroicEric/vim-tabline) that people can use (or copy code from and make into their own special snowflake tabs).

![](https://camo.githubusercontent.com/8ea161453e387c744253f5836093c8445c820fb3/68747470733a2f2f7261772e6769746875622e636f6d2f4865726f6963457269632f76696d2d7461626c696e652f6d61737465722f73637265656e73686f74732f73637265656e73686f742e706e67)

**Comment by willmanduffy** [comment]
Just a note to this being "solved" in Atom. Here's how it looks with [Seti-UI](https://atom.io/themes/seti-ui), one of the most popular Atom themes. This is with 3 files open, fullscreen on a 27" monitor.

![screen shot 2016-10-06 at 5 25 02 pm](https://cloud.githubusercontent.com/assets/782252/19203574/f9780384-8ca5-11e6-8495-901a071cf8a4.png)

**Comment by krisselden** [comment]
I'm not sure I would consider it solved in an editor that only did it when there is a name conflict among the files open.  I think it would be nice to be able to always show the parent directory.

**Comment by locks** [comment]
> I'm not sure I would consider it solved in an editor that only did it when there is a name conflict among the files open. I think it would be nice to be able to always show the parent directory.

Prior art on how to address this issue: [smart-tab-name](https://atom.io/packages/smart-tab-name) [custom-title](https://atom.io/packages/custom-title) [tab-foldername-index](https://atom.io/packages/tab-foldername-index)
I haven't found a setting to always enable it, but I'm not an Atom user.

**Comment by davelowensohn** [comment]
@workmanw I've been using [ember-tabs](https://atom.io/packages/ember-tabs) in Atom for a while now, and it solves 100% of my problems. The "No configuration required" behavior screenshotted above only kicks in when you have multiple files with the same name open, and only gives 9 characters before truncating, instead of ember-tabs' 23. It also has a handy keyboard shortcut to swap between template.hbs & component.js within a folder or subfolder.

At this point Chrome devtools is my only pain point, and it's unfortunately a big one.

**Comment by vlascik** [comment]
There's also a plugin for Jetbrains IDEs called Tabdir, https://plugins.jetbrains.com/idea/plugin/5045-tabdir , which lets you customize tabs even more (show more folders in a title, get rid of the component.js so that you can distinguish just by folder + Appearance -> File colors etc.)

**Comment by psteininger** [comment]
This may be slightly off-topic, but did anyone consider the impact of naming JS and hbs files not only on the title bar but search results? Say I have a `foo-bar` component and I want to type in "foo-bar" and open the `template.hbs` will the `template.hbs` show up? Or do I have to type in `template.hbs` and wade through a myriad of paths? Perhaps typing "foo-bar/template" would yield that with certainty, but that is a lot of typing.

Wit the above in mind would paths like these be better?
```
src/
  ui/
    library/   # <-- high level context
     listing/   # <-- sub-context (could have other sub-contexts)
       book-list.js
       book-list.hbs
     form/
      book-form.js
      book-form.hbs
```
Where the path provides "context" kind of like the idea in contexts in [Phoenix Framework](https://hexdocs.pm/phoenix/contexts.html), though those relate to models, not UI components. I think the above naming  could help both the title issue, and search/browse issue.

I would love to hear your comments

**Comment by yohanmishkin** [comment]
Hey @ef4 ! It looks like we were able to knock out most of the editors on the list. Do you think maybe we could close this out (and re-open editor-specific issues if others still need support)?

**Comment by sukima** [comment]
Here is what I use for **VIM**: https://github.com/sukima/vimrc/blob/master/_vimrc#L779-L833

```vim
" Custom 'tabline' {{{2
let g:ember_pod_types = {
      \"component": "C",
      \"template": "T",
      \"controller": "CN",
      \"route": "R",
      \"service": "S",
      \"model": "M"
      \}


if exists("+showtabline")
  function! TabNameFor(file)
    let isTest = v:false
    let name = fnamemodify(a:file, ':p:t')
    if name == ''
      return '[No Name]'
    endif
    let type = fnamemodify(a:file, ':p:t:r')
    if type =~ "-test$"
      let isTest = v:true
      let type = substitute(type, "-test$", "", "")
    endif
    if !has_key(g:ember_pod_types, type)
      return name
    endif
    let name = fnamemodify(a:file, ':p:h:t')
    let typeCode = g:ember_pod_types[type]
    if isTest
      let typeCode .= '-T'
    endif
    return typeCode . ':' . name
  endfunction


  function! MyTabLine()
    let s = ''
    let t = tabpagenr()
    let i = 1
    while i <= tabpagenr('$')
      let buflist = tabpagebuflist(i)
      let winnr = tabpagewinnr(i)
      let s .= '%' . i . 'T'
      let s .= (i == t ? '%1*' : '%2*')
      let s .= '[' . i . ']'
      let s .= '%*'
      let s .= (i == t ? '%#TabLineSel#' : '%#TabLine#')
      let s .= TabNameFor(bufname(buflist[winnr - 1]))
      let i = i + 1
    endwhile
    let s .= '%T%#TabLineFill#%='
    let s .= (tabpagenr('$') > 1 ? '%999XX' : 'X')
    return s
  endfunction
  set showtabline=1
  set tabline=%!MyTabLine()
endif
```
