### ISSUE TITLE
didReceiveAttrs firing incorrectly

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#14444]
There is a difference in behaviour between Release and Alpha

See this [Twiddle](https://ember-twiddle.com/3f485656d66e3299a5d064329ee42b13?openFiles=controllers.application.js%2Ctemplates.components.my-component.hbs)

To reproduce:
1. Click 'toggle' multiple times
2. Notice didReceiveAttrs doesn't fire
3. Switch to Alpha
4. Click 'toggle' multiple times
5. Notice didReceiveAttrs fires

**Comment by scottmessinger** [comment]
@amk221 I could be wrong, but this looks like it's related to #14335 and #14410. My guess is the controller is being invalidated by toggling the `foo` property. Since the controller is invalidated, it rerenders all it's children. If you switch to beta, didReceiveAttrs also fires multiple times.

**Comment by rwjblue** [comment]
Confirm, @scottmessinger seems like the same issue to me.  

@amk221 - I'm going to close this so we can track in a single place (likely https://github.com/emberjs/ember.js/pull/14410 since it has the most conversation ATM).

**Comment by amk221** [comment]
Ok :), I did try to find a dupe
Cheers
