### ISSUE TITLE
[Bug] willRender should be able to `set`

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#14458]
In <= 2.8.0 the hooks were ran in the following order:

- `willRender`
- `willInsertElement`

In 2.9.0 they are:

- `willInsertElement`
- `willRender`

Also in 2.9.0 these hooks were being called after some rendering was done e.g. applying `attributeBindings` thus a set in `willRender` would yield an error.

Repro:
https://ember-twiddle.com/2908909be33a648e06724f8c47b9af52?fileTreeShown=false&openFiles=templates.application.hbs%2Ctemplates.components.my-component.hbs

**Comment by pixelhandler** [comment]
@chadhietala Should this issue be closed now that the PR is merged? #14450
