### ISSUE TITLE
Updating a property supplied to a hash helper triggers observers on all properties

### ISSUE THREAD

**Issue by kanongil** [emberjs/ember.js#14468]
The `hash` helper is very trigger happy regarding changes to its properties, causing any change to fire observers on _all_ properties, even static ones.

Eg. changing `b` in this template triggers observers on the `hash.a` property in `my-component`:
```hbs
{{my-component hash=(hash a="static" b=b)}}
```

[Full twiddle.](https://ember-twiddle.com/3d806dacb9ec04aa12afcdce0d6bc742?openFiles=controllers.application.js%2Ctemplates.components.my-component.hbs)

Note that this can be solved with something like the stable hash helper from #14410, though other solutions might be better.

**Comment by pixelhandler** [comment]
@kanongil is there documentation available that says "Updating a property supplied to a hash helper should not trigger observers on all properties"?

**Comment by kanongil** [comment]
@pixelhandler This was not meant as a bug, but rather a notice regarding a performance issue with the current `hash` helper implementation, that is unintuitive and seems solvable. I am aware that ember makes no guarantees that a triggered observer has an updated value.

While I agree about a cautious approach, as far as I can tell a properly implemented `stable-hash` will always be superior to the current implementation. Ie. if I had a choice, I would probably always choose `stable-hash`.

**Comment by ef4** [comment]
In the interests of helping the folks who triage issues, I want to suggest closing this for now. There was no behavior change here (it has always worked this way), and I think we have now addressed the rerender scenario that made this behavior expensive enough to notice in the first place.

I would still be happy to review A PR that optimizes the hash helper's stability, as long as it can avoid forcing eager evaluation of the properties on the hash object and it doesn't impose undo cost & complexity. But my expectation is that as long as we're doing the rest of rerender & invalidation correctly, a more sophisticated hash helper is not a net gain.

**Comment by Serabe** [comment]
Thank you for the hint, @ef4. Closing this.

Thank you all for this thread. It was a pleasure to read it.

**Comment by kanongil** [comment]
I tried changing a use of the `hash` helper to a stable object computed on the parent component. This drastically improved the re-render performance.

The increase comes from not attempting to render 50+ components that is not actually changed.

Any chance we can look at this again?

**Comment by ef4** [comment]
Hi @kanongil, I would be happy to review a PR that optimizes the hash helper. The thing that it would need (that #14410 did not have) is that it shouldn't force eager evaluation of the values. It probably shouldn't need to look at the values at all.

I think the best way to get this change into Ember is to first ship a stable hash helper as an addon so that it's easy for people to evaluate the performance impact in their real apps.

**Comment by kanongil** [comment]
@ef4 Thanks for the support.

While I agree that it probably shouldn't need to evaluate all arguments, the existing helper already does this in `CurlyComponentManager#create()`. The only performance regression on initial render is due to the revision caching, which could be removed.

Regarding the addon path, this is not so simple, and definitely impossible using public api. I would need a way to access glimmer primitives and a way to register a builtin helper. Any ideas on how to this this in a sensible way?

**Comment by ef4** [comment]
You can get access to the glimmer internal modules using `Ember.__loader.require`. That is the typical way for experimental addons to do things that don't have public API.

**Comment by kanongil** [comment]
Thanks for the info. With some additional help from @rwjblue on slack, I created a published addon called `ember-stable-hash`, which provides a solution to this issue by exposing a `stable-hash` helper.

The actual implementation is a bit simpler than the one I provided in #14410, but the idea is the same. You can see the new implementation here: https://github.com/kanongil/ember-stable-hash/blob/master/addon/helpers/stable-hash.js.

In my app, where I use a total of 3 `hash` helpers that are only exposed once, this implementation provides a significant performance boost (for a specific operation) by avoiding re-rendering of a long list.
