### ISSUE TITLE
Shipping a "globals free" build of Ember for the browser

### ISSUE THREAD

**Issue by ebryn** [emberjs/ember.js#14478]
Let's explore what it would take for us to be able to ship a build of Ember that doesn't write out the `Ember` & `Em` globals. This would be beneficial for users trying to use Ember modularly within another web application where global pollution is considered a bad practice and in cases where an existing application may be embedding widgets that use different versions of Ember.

We're also using the `EmberENV` global to provide configuration flags from apps. It'd be nice to add another mechanism to configure Ember. Related issue in Ember-CLI: https://github.com/ember-cli/ember-cli/issues/6351

**Comment by ebryn** [comment]
Moved to https://github.com/emberjs/rfcs/issues/172

**Comment by rwjblue** [comment]
THANK YOU!
