### ISSUE TITLE
ember.js server 1 minute startup time on vagrant ubuntu

### ISSUE THREAD

**Issue by alanzheng88** [emberjs/ember.js#14483]
see: https://github.com/alanzheng88/vagrant-chef-emberjs-boilerplate

**Comment by Serabe** [comment]
Hello, @alanzheng88,

since this is an Ember CLI related request, can you please move it to [ember-cli/ember-cli](https://github.com/ember-cli/ember-cli)?

Thank you!

**Comment by Serabe** [comment]
I forgot, please, when you do so, reference this issue and then close it!

Thank you!

**Comment by alanzheng88** [comment]
Thanks @Serabe . Issue moved to ember-cli/ember-cli#6355
