### ISSUE TITLE
Update URL on error state

### ISSUE THREAD

**Issue by lnaravindan** [emberjs/ember.js#14495]
I am facing a similar issue to #10219 

My use case is similar as I need the URL to be updated whenever a transition goes to error state.

Whenever we end up at a error page, as a user we tend to do two things. 
1. Press back button to go the previous (working) page. 
2. Press refresh button to retry the failed page.

With url not updated, both these can't be done.

Any suggestions on how to handle this?

**Comment by pixelhandler** [comment]
@ivanvanderbyl perhaps reach out in the http://embercommunity.slack.com #-help channel to see if anyone has a suggestion. (We use the Issue Tracker for ember bugs.) Also it helps if you provide an example, such as using https://ember-twiddle.com or simple making a new app with ember-cli and sharing the repo.

I see your comment here https://github.com/emberjs/ember.js/issues/10219#issuecomment-254434483

I've been able to use error substates and provide the user a "back" link that uses history -1. Also if the URL hasn't changed doesn't a refresh work?

In case this can help, here are some general links on the subject of using Error substates:

- https://guides.emberjs.com/v2.8.0/routing/loading-and-error-substates/
- https://pixelhandler.com/posts/emberjs-handling-failure-using-route-error-substates
- https://github.com/pixelhandler/ember-jsonapi-resources/wiki/Error%20Handling

**Comment by lnaravindan** [comment]
@pixelhandler I have created a ember twiddle. Please see it. 

[https://ember-twiddle.com/4ecc0e6527dd77901233b0c28dd47876?openFiles=templates.application.hbs%2C&route=%2Fworking](url)

**Comment by rogatty** [comment]
I solved it by manually updating the URL in the error action:
```
error(error, transition) {
	const router = this.get('router._routerMicrolib');
	let url;

	if (transition.intent.url) {
		url = transition.intent.url;
	} else {
		const params = Object.values(transition.params).filter((param) => {
			return Object.values(param).length;
		});

		url = router.generate(transition.targetName, ...params);

		if (!isEmpty(transition.queryParams)) {
			url += getQueryString(transition.queryParams);
		}
	}

	router.updateURL(url);

	return true;
}
```
