### ISSUE TITLE
classNameBindings reset all classes that might have been added to the component

### ISSUE THREAD

**Issue by tehmaestro** [emberjs/ember.js#14497]
Hi, this is an issue starting with Ember 1.13. Here's an example of the issues: https://ember-twiddle.com/77746ec75589eb5347736427e46e296b?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs

In the example above, you can see that there are two classes set initially. Now, if you click the first button, a new class will be added to my component. This issues is that, when pressing the second button which toggles a class name binding, the class that was added using jQuery will be removed.

So this means that `classNameBindings` reset all component classes. Is this the desired behavior? Thanks.

**Comment by Serabe** [comment]
Yes, you should use `classNameBindings` to implement this behaviour. See [this twiddle](https://ember-twiddle.com/ac1b0c843e59662590611ad640e4c948?openFiles=components.my-component.js%2C)
