### ISSUE TITLE
Android Chrome (v53) + Swiftkey Breaks `{{textarea`

### ISSUE THREAD

**Issue by jherdman** [emberjs/ember.js#14502]
Using even the [simplest reproduction app](https://ember-twiddle.com/8ea5b78f38c0e29c77175e093327ddca), typing with Swiftkey in Chrome (v53.0.2785.134) is seen to be broken.
1. Type a word via swiping
2. Attempt to type another
## Expected

You now have two words in your text area.
## Actual

You have only your most recently typed word.
## Other Data
- Works fine with the built in keyboard with swiping
- Swiftkey + Firefox works just fine and dandy

**Comment by mixonic** [comment]
I've confirmed and issue related to Swiftkey on my own Android device and Chrome, although it manifests differently.

* Open the reproduction linked above
* Swiftkey in a word, it will appear
* Switftkey in a second word, **only a space will be added**

I also confirmed this does not occur in an input or textarea created by the browser's normal page parser.

**Comment by pixelhandler** [comment]
@jherdman @mixonic @locks is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
