### ISSUE TITLE
Possible documentation error for component helper

### ISSUE THREAD

**Issue by MarkMT** [emberjs/ember.js#14503]
The API documentation for the `component` helper includes a section on [Nested Usage](http://emberjs.com/api/classes/Ember.Templates.helpers.html#toc_nested-usage) ([source](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/helpers/component.js)) with an example that I suspect is incorrect.

A `person-form` component template defined as follows
```
{{yield (hash
    nameInput=(component "my-input-component" value=model.name placeholder="First Name"))}}
```
is shown being used like this:
```
{{#person-form as |form|}}
  {{component form.nameInput placeholder="Username"}}
{{/person-form}}
```
If my understanding is correct, the use of the `component` keyword in the block is an error, since `form.nameInput` is itself a component, not the name of a component.

The usage above also appears to be at odds with what is shown in the 2.4 beta [release note](http://emberjs.com/blog/2016/01/15/ember-2-3-released.html#toc_contextual-components) and in the [guides](https://guides.emberjs.com/v2.8.0/components/wrapping-content-in-a-component/#toc_sharing-component-data-with-its-wrapped-content).

I'm happy to provide the fix, but would like someone to confirm my interpretation, since I'm only just learning about contextual components for the first time.

**Comment by pixelhandler** [comment]
@MarkMT yeah you're correct, if `form.nameInput` is a component there is no need for the `component` helper. 

On the subject of contextual components here are a couple links I enjoy:

- http://www.serabe.com/2016/03/04/the-path-to-contextual-components-contextual-components/
- https://emberway.io/component-dependency-injection-in-ember-js-a46a39a5d30a#.ddhx2tkyl

**Comment by MarkMT** [comment]
Ha! You beat me to it!

**Comment by MarkMT** [comment]
Thanks for the confirmation @pixelhandler.

**Comment by pixelhandler** [comment]
@MarkMT oh sorry, figured it was easy so just PR'd it.

**Comment by MarkMT** [comment]
No problem :)
