### ISSUE TITLE
Clarify 'escapeCSS' in documentation.

### ISSUE THREAD

**Issue by tabeth** [emberjs/ember.js#14518]
Upon reading the documentation for binding style deprecations, I think we may want to clarify that `escapeCSS` isn't implemented by Ember. One may get that impression that it's implemented by Ember given its inclusion in the code snippet. 

> ```
myStyle: Ember.computed('color', function() {
    var color = escapeCSS(this.get('color'));
    return Ember.String.htmlSafe("color: " + color);
  })
```

[source](http://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes.)

**Comment by rwjblue** [comment]
I agree! Would you mind submitting a PR to emberjs/website for that?

**Comment by tabeth** [comment]
Not at all. I added a [quick note](https://github.com/emberjs/website/pull/2711).

**Comment by Serabe** [comment]
PR in emberjs/website was merged. Closing this.

Thank you, guys!

**Comment by QuantumInformation** [comment]
It caught me out today, I tend to ignore comments.

**Comment by janwerkhoven** [comment]
How does one import `escapeCSS` in Ember 3.17?

I'd expect `import { escapeCSS } from '@ember/template';` ...

**Comment by locks** [comment]
@janwerkhoven as mentioned in the thread, Ember never provided an `escapeCSS` function. The user must implement how they best see fit.

**Comment by janwerkhoven** [comment]
Thanks @locks , that makes sense now.

Returning `htmlSafe` seems to be sufficient to silence the `escapeCSS` warnings.

For those looking for an example that works:

```js
// Ember Octane 3.17

import Component from '@glimmer/component';
import { computed } from '@ember/object';
import { htmlSafe } from '@ember/template';

export default class SomeComponent extends Component {
  get safeStyle() {
    return htmlSafe(`top: ${this.escapeCSS(123)}px`);
  }

  escapeCSS(css) {
    return css; // do your own sanity check here
  }
}
```
```hbs
<div style={{safeStyle}}>
```
