### ISSUE TITLE
ember 2.9 2.8 not unregistering views correctly

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#14526]
2.9.0
* https://github.com/emberjs/ember.js/blob/v2.9.0/packages/ember-htmlbars/lib/renderer.js#L263
* https://github.com/emberjs/ember.js/blob/v2.9.0/packages/ember-glimmer/lib/renderer.js#L226

2.8.1
* https://github.com/emberjs/ember.js/blob/v2.8.1/packages/ember-htmlbars/lib/renderer.js#L263
* https://github.com/emberjs/ember.js/blob/v2.8.1/packages/ember-glimmer/lib/renderer.js#L226

2.8.0
* https://github.com/emberjs/ember.js/blob/v2.8.0/packages/ember-htmlbars/lib/renderer.js#L263
* https://github.com/emberjs/ember.js/blob/v2.8.1/packages/ember-glimmer/lib/renderer.js#L226

introduced `v2.8.0-beta.1` https://github.com/emberjs/ember.js/commit/2a233df8c6aa387898299d79dd4b2965b4266015

--

Root cause really that the original code appeared to not be covered by tests, so reasonable refactoring broke it, but without test failure.

--

issue to be sure we don't forget about a test on master: https://github.com/emberjs/ember.js/issues/14530

**Comment by stefanpenner** [comment]
working on PR now

**Comment by stefanpenner** [comment]
* fix for release-2-8 https://github.com/emberjs/ember.js/pull/14528
* fix for release-2-9 https://github.com/emberjs/ember.js/pull/14529

**Comment by rwjblue** [comment]
Both `lts-2-8` and `release` branches have been updated (via #14528 and #14529) and will be released in the next few days. Closing..
