### ISSUE TITLE
[DOC] - Additional pattern for {{action (mut ... ) }} 

### ISSUE THREAD

**Issue by mike-north** [emberjs/ember.js#14525]
(Moved from https://github.com/emberjs/guides/issues/1713)

Looking at the guides & published API docs, a very handy pattern for `{{mut}}` do not seem to be covered.

#### setting the value of a property to some **literal** value
```hbs
{{#if myToggle}}
   {{!-- Clicking this will set myToggle to false --}}   
   <button onClick={{action (mut myToggle) false}}>Hide</button>
{{else}}
   {{!-- Clicking this will set myToggle to true --}}
   <button onClick={{action (mut myToggle) true}}>Show</button>
{{/if}}
```

#### Variant - accessing a particular property off of the event
```hbs
<input type='range'
   onInput={{action (mut size) value="target.value"}} />
```
While the `value` option is part of the action helper, the way it works in conjunction with `mut` may make it worth mentioning explicitly as a use case 

For clarity, here examples of both: https://ember-twiddle.com/fc4179799bcf33c58f67d9cdd84111d0?openFiles=templates.application.hbs%2C

**Comment by Serabe** [comment]
Those patterns are a combination of `mut` being interoperable with `action` and `action` features. All of these are documented in the API (at least in the `ember-glimmer` part).

My fear here is creating an implicit dependency in the documentation. Maybe just stating that any option available to `action` works even if `mut` is being passed as the action?

**Comment by Serabe** [comment]
@mike-north can you please check the PR and comment on it? Thank you!
