### ISSUE TITLE
Backfill tests on master for #14526

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#14530]
this is a reminder to also add a test (or ensure an existing one exists) ensuring we don't regress on https://github.com/emberjs/ember.js/issues/14526 in the future.

**Comment by rwjblue** [comment]
This was fixed on master (and tested) in https://github.com/emberjs/ember.js/pull/14100. Unfortunately, I didn't properly mark that commit to be pulled into 2.8/2.9 branches. 😞
