### ISSUE TITLE
Adopt the `npm prepare` and `npm prepublishOnly` hooks.

### ISSUE THREAD

**Issue by nathanhammond** [emberjs/ember.js#14536]
In order to do the right thing for ember-source we should:
- [ ] Enforce publish on npm@4 only.
- [ ] Move the script which is currently in `release` to the correct location.

Goal would be that `npm publish` does exactly the right thing out of the box with no additional commands and that `npm install` doesn't trigger a build.

/cc @locks

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)

**Comment by rwjblue** [comment]
We went a different route here...
