### ISSUE TITLE
Improve error message "Assertion Failed: A helper named 'something-something' could not be found"

### ISSUE THREAD

**Issue by adam-knights** [emberjs/ember.js#14532]
Lets say you add

`{{something-something a=b}}`

to any Ember template.

The error you receive is `Assertion Failed: A helper named "something-something" could not be found`.

Why 'a helper'? The user could be trying to reference a component. For me the most common case is a user typo when referencing the component.

A couple of our new guys stumbled on this error, could/should it be improved to:

Assertion Failed: A component or helper named "something-something" could not be found

?

**Comment by rwjblue** [comment]
Sounds good to me, would you mind submitting a PR that we can review?

**Comment by adam-knights** [comment]
Will do :)

**Comment by serenaf** [comment]
@adam-knights Hey Adam, i created a PR for this, see here https://github.com/emberjs/ember.js/pull/14587

**Comment by adam-knights** [comment]
Thanks @serenaf , i hadnt found the time yet.
