### ISSUE TITLE
[DOC] Ember.Component#layout is not documented as public

### ISSUE THREAD

**Issue by mike-north** [emberjs/ember.js#14548]
Inspired by: https://github.com/ember-cli/ember-cli.github.io/issues/100

Currently the [default addon component blueprint](https://github.com/emberjs/ember.js/blob/v2.10.0-beta.2/blueprints/component/index.js#L59-L68) sets up the component template via the `layout` property. 

There is no evidence in the [API docs](http://emberjs.com/api/classes/Ember.Component.html) that it's public, or any mention or use of it in [the appropriate section of the guides](https://guides.emberjs.com/v2.9.0/components/defining-a-component/), leading to confusion as to whether it's ok to use. Add in [the deprecated `Ember.View` concept of the same name](http://emberjs.com/api/classes/Ember.View.html#toc_layouts), and it's understandable why people new to the framework are tripping up here.

**Comment by rwjblue** [comment]
Looks like a bunch of docs from `Ember.View` haven't been moved over to `Ember.Component` yet.  

Here is a small list (there are likely more things though):

* https://github.com/emberjs/ember.js/blob/v1.13.0/packages/ember-views/lib/views/view.js#L753-L767
* https://github.com/emberjs/ember.js/blob/v1.13.0/packages/ember-views/lib/views/view.js#L714-L725
* https://github.com/emberjs/ember.js/blob/v1.13.0/packages/ember-views/lib/views/view.js#L909-L921
* https://github.com/emberjs/ember.js/blob/v1.13.0/packages/ember-views/lib/views/view.js#L1093-L1119
* https://github.com/emberjs/ember.js/blob/v1.13.0/packages/ember-views/lib/views/view.js#L60-L673

Also, in reviewing here it seems that `layout` was indeed private in Ember 1.13.  We should probably fix that (or change the blueprint)...

**Comment by sclatter** [comment]
@rwjblue I'm going to take a crack at this. Just to clarify - do we want to document tagName API on Component also? Or, just classNames and classNameBindings?

**Comment by sclatter** [comment]
PR submitted: https://github.com/emberjs/ember.js/pull/14765
