### ISSUE TITLE
[DOC] modelFor documentation inaccurate

### ISSUE THREAD

**Issue by gauthierm** [emberjs/ember.js#14544]
Current documentation at http://emberjs.com/api/classes/Ember.Route.html#method_modelFor states

> Returns the resolved model of a parent (or any ancestor) route in a route hierarchy.

A more correct description is:

> Returns the resolved model of the current route, or a parent (or any ancestor) route in a route hierarchy.

An example of getting the current route model is `this.modelFor(this.routeName)` which can be used in a route action method.

**Comment by pixelhandler** [comment]
@gauthierm would you mind opening a PR to fix?

**Comment by ManrajGrover** [comment]
@pixelhandler I'll take this one up. 😄

**Comment by locks** [comment]
Merged!
