### ISSUE TITLE
Computed property not updating in component

### ISSUE THREAD

**Issue by dhawalbhanushali** [emberjs/ember.js#14542]
I have defined a computed property in component which gets its value from controller. Whenever I am changing value in controller computed property in the component does not change. Why does this happen?

`this.set('facetTagsOptions', filterOptions);` controller js - setting this in action

`{{#facet-search-tags facetTagsOptions=facetTagsOptions}}{{/facet-search-tags}}` - controller hbs

`
facetTags: Ember.computed('facetTagsOptions', function() {
	console.log('say something'));
});
` Component hbs

**Comment by sly7-7** [comment]
Do you invoke the `facetTags` cp somewhere, either in the component, or in the template ?

**Comment by dhawalbhanushali** [comment]
Oh! No I did not. Now I have used in template and it seems to work. However it does not work always. `facetTagsOptions` is a nested object.

**Comment by sly7-7** [comment]
Ok, in that case the cp will be recomputed only if `facetTagOptions` change (with `set`), and the cp is called.

**Comment by dhawalbhanushali** [comment]
I am updating `facetTagsOptions` using set but not sure why it isn't working.

**Comment by Serabe** [comment]
Hello, @dhawalbhanushali. I am closing this since it is not an Emberjs bug. Please, go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

Thank you!

**Comment by shreyas098** [comment]
Even I am facing this issue , did we have any solution for it
