### ISSUE TITLE
TypeError: Invalid value used as weak map key, in get() with canary

### ISSUE THREAD

**Issue by backspace** [emberjs/ember.js#14557]
Hey, I’ve been trying out the Ember beta and canary versions with [`travis-web`](https://github.com/travis-ci/travis-web) and getting a WeakMap error. When I run with `canary` in `bower.js` in Chrome 56, I get this stacktrace:

```
WeakMap_setMeta (ember.debug.js:19145)
meta (ember.debug.js:19246)
watchKey (ember.debug.js:22349)
RootPropertyReference (ember.debug.js:14278)
get (ember.debug.js:14184)
referenceFromParts (ember.debug.js:44196)
evaluate (ember.debug.js:46140)
evaluate (ember.debug.js:45613)
evaluateArgs (ember.debug.js:53312)
evaluate (ember.debug.js:48694)
execute (ember.debug.js:53279)
RootState.render (ember.debug.js:11301)
runInTransaction (ember.debug.js:22272)
_renderRoots (ember.debug.js:11566)
_renderRootsTransaction (ember.debug.js:11604)
_renderRoot (ember.debug.js:11525)
_appendDefinition (ember.debug.js:11438)
appendOutletView (ember.debug.js:11421)
invoke (ember.debug.js:337)
flush (ember.debug.js:407)
flush (ember.debug.js:531)
end (ember.debug.js:601)
run (ember.debug.js:724)
fire (jquery.js:3187)
fireWith (jquery.js:3317)
ready (jquery.js:3536)
completed (jquery.js:3552)
```

Similar errors happen with Safari, Firefox, and Chrome 53.

This can be reproduced with the repository running locally with `beta` or `canary` as the Ember version in `bower.json`. When I enable pausing on exceptions, I see that the `get` is on a property key of `config`:

![image](https://cloud.githubusercontent.com/assets/43280/19846566/d87e71ec-9f40-11e6-8d65-6e644136a248.png)

I’ve been working on permanent [beta](https://ember-beta.travis-ci.org/) and [canary](https://ember-canary.travis-ci.org/) production environment deployments of Ember, which are failing differently with this error:

```
ember.prod.js:20058 Uncaught TypeError: Cannot read property 'config' of undefined
```

The presence of `config` there makes me wonder if they’re somehow related though, but the stack trace is pretty different:

<details>
<summary>Production canary stacktrace</summary>
```
r (ember.prod.js:20058)
t.compute (ember.prod.js:13338)
t.value (ember.prod.js:13213)
t.compute (ember.prod.js:13376)
t.value (ember.prod.js:13213)
e.value (ember.prod.js:47770)
e.initialize (ember.prod.js:41539)
e.peek (ember.prod.js:41513)
t.evaluate (ember.prod.js:46085)
e.execute (ember.prod.js:50289)
d (ember.prod.js:49863)
render (ember.prod.js:10524)
h (ember.prod.js:10477)
e._renderRoots (ember.prod.js:10787)
e._renderRootsTransaction (ember.prod.js:10825)
e._renderRoot (ember.prod.js:10746)
e._appendDefinition (ember.prod.js:10659)
e.appendOutletView (ember.prod.js:10642)
invoke (ember.prod.js:326)
flush (ember.prod.js:396)
flush (ember.prod.js:520)
end (ember.prod.js:590)
run (ember.prod.js:713)
join (ember.prod.js:735)
l.join (ember.prod.js:20411)
(anonymous function) (ember.prod.js:20474)
l (jquery.js:3187)
fireWith (jquery.js:3317)
ready (jquery.js:3536)
a (jquery.js:3552)
```
</details>

I’m not familiar with this code so I haven’t gotten anywhere with trying to debug. Let me know if there’s any additional information I can provide.

**Comment by rwjblue** [comment]
I am not quite sure why yet, but we have a `RootPropertyReference` with a `_parentValue` of `undefined`.

When running `ember.debug.js` builds, we get the `WeakMap_setMeta` errors due to calling `watchKey(undefined, 'config')` (which then calls `metaFor(undefined)`).

When running `ember.prod.js` builds, we skip that and just call `Ember.get(undefined, 'config')` which errors (with the production config above).

A quick tour through the stack on ember-canary.travis-ci.org and the Ember codebase makes me think, that it is related to [these references to `config.enterprise`](https://github.com/travis-ci/travis-web/search?utf8=%E2%9C%93&q=language%3Ahandlebars+config.enterprise&type=Code) in the templates, but again I haven't dug too much deeper to figure out why.

**Comment by backspace** [comment]
hmm, well that `config` presumably comes from [here](https://github.com/travis-ci/travis-web/blob/f500c1eb225f087b9eed992ed970facacc71d611/app/initializers/config.js#L8). Is it a faux pas to reference the config in templates like this? This decision predates me and the addition of feature flags, which maybe could be used instead. But I see `config.` all over the place in templates. 😱

**Comment by rwjblue** [comment]
What y'all are doing seems fine, I was just doing a brain dump of my findings after a debugging session.

**Comment by krisselden** [comment]
@backspace if you `bower install ember#beta` it should have the fix

**Comment by backspace** [comment]
It’s true, excellent, thank you!

Sadly I’m getting another `Invalid value used as weak map key` seemingly related to `config` but it’s a different stacktrace, so I’ll open another issue.
