### ISSUE TITLE
Create "feature flag" for `if` conditional removal.

### ISSUE THREAD

**Issue by nathanhammond** [emberjs/ember.js#14555]
Currently in order to improve some of our error messages like in #14554 we pay a double cost in order to leverage `runInDebug`. In some future state we should be able to use a "feature flag" which allows us to strip things without needing to call it twice and so we can leave the code run in context. That would look something like this:

``` javascript
if (isDebugBuild()) {
  // Do the useful debug thing, probably including try/catch.
} else {
  // Do the performant thing.
}
```

Do we wish to add a "feature flag" like this? Related though to `if (testing)` , it _is_ a tremendous way to accidentally troll ourselves.

/cc @krisselden @rwjblue

**Comment by locks** [comment]
@nathanhammond I wonder if this should go through the RFC process instead?

**Comment by nathanhammond** [comment]
The thing is we could simply create a new feature flag in a single line of code, this is almost more of a question of "if we want to do it."

**Comment by Turbo87** [comment]
I think this has been implemented by now, right?

**Comment by chancancode** [comment]
Yep.
