### ISSUE TITLE
ensure d8-runner only uses  `Node dom helper` 

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#14551]
most likely the result of: https://github.com/stefanpenner/d8-ember/issues/1

**Comment by krisselden** [comment]
The issue is just you set a document as a global and which is used by too many libs to detect real dom.   The expected thing is to pass document to the `visit()` API.

**Comment by stefanpenner** [comment]
> The issue is just you set a document as a global

Well, its more complicated. As something is broken, requiring that document be set, so that will need to be addressed first. That being said, all of ember should not sniff independently rather it should allow globals such as this to be injected. That would tidy up this problem nice.

**Comment by krisselden** [comment]
https://github.com/emberjs/ember.js/pull/14559

**Comment by stefanpenner** [comment]
@krisselden does that address stefanpenner/d8-ember#1 ?

**Comment by krisselden** [comment]
@stefanpenner yes

**Comment by stefanpenner** [comment]
sweet

**Comment by stefanpenner** [comment]
ah, the one remaining this is `window.EmberEnv` but i believe that could just be `EmberENV` as it is already at the global scope.
