### ISSUE TITLE
Documentation for Guides>Models>Finding Records seems inconsistent

### ISSUE THREAD

**Issue by jkole** [emberjs/ember.js#14565]
The 2.9.0 Guides section for Models says:

> Note that Ember's default JSON API adapter does not provide the functionality needed to support queryRecord() directly as it relies on REST request definitions that return result data in the form of an array.

This does not seem consistent with either the JSON API spec or the API docs for DS.JSONAPIAdapter, both of which would seem to allow a single object to be returned (both at the top level response and in the response's data attribute).

I'm new to Ember, so apologies if I'm missing something obvious...

**Comment by locks** [comment]
Thank you for your feedback @jkole. I've moved it to the proper repository at https://github.com/emberjs/guides/issues/1717.
