### ISSUE TITLE
Better compatibility with async/await function in test

### ISSUE THREAD

**Issue by GCorbel** [emberjs/ember.js#14569]
Hi,

I like the next 'async/await' feature proposed in es7. My main goal is to have a cleaner syntax. I tried to do an action like this : 

```
  actions: {
    async clone(model) {
      const clone = await model.clone();

      clone.set('name', clone.get('name') + ' - copie');
      clone.set('activity', model.get('activity'));
      this._nestedSave(clone, 'groups');
    }
  }

```

It works but I cannot test it because I have the message "You have turned on testing mode, which disabled the run-loop's autorun. You will need to wrap any code with asynchronous side-effects in a run". I described the error in [this SO question](http://stackoverflow.com/questions/40338020/using-async-await-in-test-mode-without-ember-run). I know I can use `Ember.run` but async/await become useless.

I saw I can set `Ember.testing` to false but there will be problems later.

Is there a solution or plan to do that ?

Thanks.

**Comment by GCorbel** [comment]
I just saw [this article](https://karolgalanciak.com/blog/2015/12/18/ember-and-es7-async-slash-await/) and it seems to work with test in his code.

Here is my test : 

```
import destroyApp from '../helpers/destroy-app';
import {describe, it, beforeEach, afterEach} from 'mocha';
import {expect} from 'chai';
import startApp from '../helpers/start-app';
import {authenticateSession} from '../helpers/ember-simple-auth';
import page from 'tiny/tests/pages/courses';

describe('Acceptance: Courses', ()=> {
  let application;

  beforeEach(function () {
    $.Velocity.mock = true;
    application = startApp();
    authenticateSession(application, {data: {attributes: {fullaccess: true, 'access-token': 123}}});
  });

  afterEach(function () {
    destroyApp(application);
  });

  it('can clone a course', async function () {
    const activity = server.create('activity');

    server.create('course', {name: 'Course', activity});

    await page.visitIndex();

    await page.clone();

    expect(page.courseName).to.eq('Course');
  });
});
```

**Comment by Serabe** [comment]
Hi, @GCorbel:

We reserve the issues for bugs in Ember, so I'll be closing this since it is a feature request. A feature request requires the feature to go through the [RFC process](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature).

AFAIK, there is nothing planned for actions currently. Lucky us, there is an RFC for testing that includes support for async/await (emberjs/rfcs#119). This change would probably require to open an RFC. You might be interested in [ember concurrency](http://ember-concurrency.com/#/docs) as well.

Thank you!

**Comment by GCorbel** [comment]
Thanks for very fast answer. I already saw ember-concurrency but It's not compatible with Ember hooks.

**Comment by machty** [comment]
@GCorbel which hooks is e-c incompatible with?
