### ISSUE TITLE
Ember Computed with Math.abs()

### ISSUE THREAD

**Issue by JackEllis** [emberjs/ember.js#14578]
I've tried 3 times to create a http://emberjs.jsbin.com/ but whenever I tried to find a way to save it, it emptied my code.

Long story short, doing this:
```js
var TestObject = Ember.Object.extend({
    abs: Ember.computed('a', 'b', function() {
        return Math.abs(this.get('a'), this.get('b'));
    })
});
```

then doing 

```js
TestObject.create({
    a: 4,
    b: 5
});
```

And binding them to an `{{input value=testObjectInstance.a}}` and `{{input value=testObjectInstance.b}}`

[edit: formatting]

The computed property fires correctly when both a & b are updated, but the return value does not change when b is changed.

I may be overlooking something obvious but I wanted to create a ticket in case it's a bug... Also, I'm happy to create it on Ember JS Bin if somebody can tell me how to save ;)

**Comment by stefanpenner** [comment]
I don't believe `Math.abs` takes two arguments?

**Comment by stefanpenner** [comment]
I have created an example using `Math.min` as I suspect it may be more appropriate for the given example:


https://ember-twiddle.com/deec988d9272474f8ef1694c6dffaaff?numColumns=2&openFiles=controllers.application.js%2Ccontrollers.application.js

**Comment by JackEllis** [comment]
@stefanpenner Heh, sorry to waste your time, I had put a comma instead of a -. 

Apparently I need a break from coding & a cup of coffee, DOH.

**Comment by stefanpenner** [comment]
> Apparently I need a break from coding & a cup of coffee, DOH.

I often have this problem myself, just don't over caffeinate 

![](https://s3.amazonaws.com/lowres.cartoonstock.com/transport-pilot-coffee-caffeinated-over_caffeinated-aeroplane-nfkn565_low.jpg)
