### ISSUE TITLE
Issue with loading substates on Canary 

### ISSUE THREAD

**Issue by jcope2013** [emberjs/ember.js#14585]
it seems there was a change in behavior between 2.9 and canary with loading substates where declaring the same route name twice, one nested under a different route namespace and one at the top level causes an error with the loading substate

2.9.0 loads fine

https://ember-twiddle.com/fbdb07dd1bcc7817f87643b4a8d435fa

Canary (Uncaught Error: You may not add a duplicate route named `posts_loading`)

https://ember-twiddle.com/3b08aed8ebc95a5eec495e09ff781274

may be related to https://github.com/emberjs/ember.js/pull/14545

**Comment by rwjblue** [comment]
This is the error message that was added in https://github.com/tildeio/route-recognizer/pull/118.

/cc @nathanhammond

**Comment by rwjblue** [comment]
For easier discussion, the `Router.map` in question is:

```js
Router.map(function() {
    this.route('posts', { resetNamespace: true }, function(){
        this.route('all');
    });
  
  this.route('users', { resetNamespace: true }, function(){
    this.route('posts', { resetNamespace: true }, function(){
    });
  });  
});
```

**Comment by nathanhammond** [comment]
@jcope2013 You've created `undefined` behavior with this route map. Where would `{{#link-to 'posts'}}` take you? Answer: whichever one is defined second, though that is not guaranteed as it's an implementation detail.

This route map is incorrect because there becomes no way to get to `/posts` except by direct navigation via URL. This is something we consider to be obviously wrong and we want to alert users to their mistake earlier rather than later, thus the addition of the error.

**Comment by rwjblue** [comment]
@nathanhammond - Maybe we can keep track (i.e. an object with a list of "seen" routes) on Ember's side also so that we can provide a better assertion/error message?

**Comment by nathanhammond** [comment]
[We could just move where this gets invoked.](https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/dsl.js#L40-L43)

**Comment by jcope2013** [comment]
so this is what I am trying to do I have a posts.show nested under users (goes to users/posts/show) and a posts.all (goes to posts/all) at the top level, I want to keep both the templates under the posts folder and when linking to posts.show, I want to do ```{{#link-to "posts.show"}}Post show{{/link-to}} ``` 

here it is in 2.9

https://ember-twiddle.com/e23d8ce62b6c298126520ea2827bc748?openFiles=templates.application.hbs%2C&route=%2Fposts%2Fall

On canary, since I get the resetNamespace error, I now need to remove the resetNamespace in the inner posts route nested under users so now I can no longer access the show.hbs under the posts folder while still having the route nested under users, I need to move it into posts/users/show.hbs and I need to replace the ```{{#link-to "posts.show"}}Post show{{/link-to}} ``` to be instead ```{{#link-to "users.posts.show"}}Post show{{/link-to}} ```  to get similar behavior

https://ember-twiddle.com/e786044e2cafeeea95323ab180df515b?openFiles=templates.application.hbs%2C

I guess the trick is I was basing my routes off that second wins behavior and am wondering if there is a similar way to do what I was trying to achieve

**Comment by nathanhammond** [comment]
@jcope2013 Do you agree that you were leveraging `undefined` and hacky behavior previously? Do you believe that pattern should continue to be supported? (I'm asking this quite seriously, I'm curious of your opinion.)

I believe what you're looking for to address Item 1 is this: http://emberjs.com/api/classes/Ember.Route.html#property_templateName

Item 2 I don't believe is worth trying to solve as it confuses what is going on.

**Comment by jcope2013** [comment]
@nathanhammond addressing 1, templateName would fix the issue of where I could keep the templates in the same location but would cause the route file to now be under routes/users/posts/show.js instead of routes/posts/show.js and the controller to be under controller/users/posts/show.js instead of controller/posts/show.js which I feel is a little bit of a downside since I like having the posts folder have all relevant files instead of sprinkling them around, I know I could do some stuff importing and exporting to get around that if neccesary.

2 I could live with changing the link-to to have the fully qualified path name such as users.posts.show but the resetNamespace was sort of nice to shorten it up but could go either way there

I previously liked how I could layer resetNamespaces at multiple nested layers and have them all act as top level (both at the link-to/file layer) but if what I was doing was very uncommon then I am not against changing it in my apps, I would be interested to see if any others chime in over the next few weeks once more people test canary/beta once 2.10.0 comes out

**Comment by nathanhammond** [comment]
We'll monitor this. I'm pretty strongly of the opinion that combinatorially relying on unspecified and untested implementation details, less-frequently used features, and introducing _deliberately_ broken code paths (what happens in your application when a user directly visits `example.com/posts`?) should not be presented as a feature. Literally that it works at all is a coincidence as this wasn't intended.

One of the advantages Ember brings is that I can sit down in anybody's project and immediately be productive. Your _clever_ abuse of how Ember resolves modules in combination with how it handles routing subverts that goal except for the most familiar of users.

(You could also set up a custom resolver if you wished.)
