### ISSUE TITLE
Controller is not a "specialized Component" (documentation issue)

### ISSUE THREAD

**Issue by Senthe** [emberjs/ember.js#14589]
Controller is an Object, while Component is a View. Controller has no idea it has some DOM elements attached to it and it won't know its `this.$()` for example. It seems it's also unable to process events passed by actions. It's not "just a big Component" and shouldn't be described as such.

If I'm wrong in some way please explain. I'm fairly new to Ember.

**Comment by locks** [comment]
Moved to guides repository.
