### ISSUE TITLE
Cannot handle UnrecognizedURLError at the application level

### ISSUE THREAD

**Issue by vmalloc** [emberjs/ember.js#14584]
Trying with a fresh ember-cli application, version 2.9.1, and creating a few sample routes. Using `locationType: 'hash'`.

Then navigating to an unknown route yields an uncaught `UnrecognizedURLError`. Attempting to catch it at the application route (through the `error` event/action) doesn't seem to work.

Is this a known or intended behavior? If so, what is the Ember way of dealing with unknown routes?

Thanks in advance

**Comment by btecu** [comment]
You can use a route to catch all:
`this.route('four-oh-four', { path: '*:' });`

**Comment by vmalloc** [comment]
Is this covered anywhere in the guides? Also any explanation about the
asterisk-colon syntax?

**Comment by btecu** [comment]
I don't know about guides, but it's documented in the link I've included.

Doesn't have to be `:`, you can just name it. See example in the documentation.

**Comment by locks** [comment]
As mentioned, this is covered by the Routing section of the guides. If you have further questions on how to accomplish this, we have a good community presence on StackOverflow, and a help channel on our Slack group!

**Comment by vmalloc** [comment]
Oh sorry. Missed the link in the first comment. Thanks a lot and sorry for the trouble!

**Comment by locks** [comment]
No problem :) Seems like @btecu added the link after GitHub sent you the email notification, so you wouldn't have seen it until you visited the website.

**Comment by vmalloc** [comment]
That makes sense because I indeed read the comment only on email. Thanks again!
