### ISSUE TITLE
Ember.set & Ember.setProperties fail to set properties "enumerable" 

### ISSUE THREAD

**Issue by herom** [emberjs/ember.js#14594]
I'm currently using Ember `2.4.3` and wanted to upgrade, but the behaviour of `Ember.set` and `Ember.setProperties` in `2.7.0` onwards seems a bit buggy to me.

To reproduce the "bad" behaviour, do the following:
```javascript
const Test = Ember.Object.extend({
  myProp: null,
  didChangeMyProp: Ember.on('init', Ember.observer('myProp', function () {
    console.log('updated');
  })
});

const testInstance = Test.create();
Ember.setProperties(testInstance, {id: 3, myProp: {id: 1}});

// here, I would expect (and did get!) `['id', 'myProp']` in Ember v2.4.3
// from Ember v2.7.0 onwards, it prints `['id']`
console.log(Object.keys(testInstance));

// alternatively, if you just `set` the `myProp` property
// Ember.set(testInstance, 'myProp', {id: 1});
// the console will only print an empty array.

// however, if I don't initialize the `myProp` property in the `extend()` call, the Object.keys are set as usual
```

It seems, that somewhere - deep in the guts of `Ember.set` && `Ember.setProperties` the `meta` is declaring the property as "not enumerable"?!

I can't reproduce this "bug" at https://ember-twiddle.com as it seems to work over there, if I try these steps in the Chrome DevTools (interesstingly enough, it prints the Ember Version as `2.9.0` but if you call `Ember.VERSION` in the console, it prints `2.8.0` 😸 )

**Comment by rwjblue** [comment]
> interestingly enough, it prints the Ember Version as 2.9.0 but if you call Ember.VERSION in the console, it prints 2.8.0

This is because ember-twiddle.com itself is an Ember app (that runs Ember 2.9.0 ATM), and the app that the twiddle is creating is running in an iframe.  So asking the host application `Ember.VERSION` reports 2.9.0, but asking the app running inside the iframe for `Ember.VERSION` will report whatever version is being specified in `twiddle.json`.

Changing the console to use the right context will fix this for you.

![host application ember version](https://monosnap.com/file/G0ZOIGDWvfoUPrSDDsZnmrU9SZmTnp.png)

![iframe application ember version](https://monosnap.com/file/j75bmzxCCEdt9y9zKHrKJSrk1Lb43x.png)

**Comment by rwjblue** [comment]
I suspect what is happening is that the set determines that the values are the same and does not actually set the property (because there is no work to be done).

[Demo](https://jsbin.com/faqidi/edit?html,js,output)

```js
const Foo = Ember.Object.extend({
  prop1: null
});

let foo = Foo.create();

log('Keys:', Object.keys(foo));
foo.set('prop1', null);
log('Keys:', Object.keys(foo));
foo.set('prop1', 'value');
log('Keys:', Object.keys(foo));
```

**Comment by rwjblue** [comment]
I believe this is a duplicate of https://github.com/emberjs/ember.js/issues/14270, can you review and confirm?

**Comment by herom** [comment]
Thanks a lot for your response @rwjblue! At first I also thought it may be a duplicate of the issue you mentionend but I think it's slightly different here as the value will be set not enumerable as soon as an `Ember.observer` is declared for the `prop1` property.

See the [edited Demo](https://jsbin.com/jewaceraru/edit?html,js,output) of yours, where I declared an `Ember.observer` - the `Object.keys(foo);` call will always return an empty array...

**Comment by pixelhandler** [comment]
@herom I cloned your jsbin, https://jsbin.com/limuki/edit?html,js,output and set the version to 2.4.3 and do see the output that the object's property is available via `hasOwnProperty`. This looks like a bug to me.

**Comment by herom** [comment]
Thanks a lot @pixelhandler  - I totally forgot about that 😃

**Comment by herom** [comment]
Just a short sumup of the different code samples in order to understand/reproduce this bug for better readability:

[WORKING Demo (without `Ember.observer`) in Ember Canary](https://jsbin.com/faqidi/edit?html,js,output) from @rwjblue  (working, **does not fully reproduce the issue as it's lacking `Ember.observer`**)

[FAILING Demo (with `Ember.observer`) in Ember Canary](https://jsbin.com/fucube/4/edit?html,js,output) from @herom (not working, fully reproduces the issue)

[WORKING Demo (with `Ember.observer`) in Ember `v2.4.3`](https://jsbin.com/limuki/edit?html,js,output) from @pixelhandler (working, fully reproduces the issue)

**Comment by pixelhandler** [comment]
@herom @rwjblue is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
