### ISSUE TITLE
Optimization for Ember.Route.actions.queryParamsDidChange

### ISSUE THREAD

**Issue by urbany** [emberjs/ember.js#14597]
Hey, sorry if I'm seeing this wrong, but looking at this line:
https://github.com/emberjs/ember.js/blob/v2.9.1/packages/ember-routing/lib/system/route.js#L776
it seems that after finding one queryParam that needs to trigger a refresh the loop should break.
If 2 parameters changed there's no need to trigger 2 refreshes at the same time, right?
One refresh should be enough.

**Comment by stefanpenner** [comment]
@urbany seems reasonable to want an early exit right there!

**Comment by rwjblue** [comment]
Sounds like a great PR to me...

**Comment by pixelhandler** [comment]
@rwjblue this has a PR now.

**Comment by daibhin** [comment]
My tests were previously failing but a rebase had fixed that. Where should I be looking to include tests as part of my PR?

**Comment by daibhin** [comment]
Test added (and ensured it fails without change). Is there anything else required to merge this PR?
