### ISSUE TITLE
Cannot clear `<img src={{foo}}>` with `null` or `undefined`.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#14595]
In prior versions of Ember setting an `<img>`'s `src` to either `null` or `undefined` would clear the property.

Given the following template:

```hbs
<img src={{foo}}>
```

Setting `foo` to `null` does not remove the previously set `src` value.

[Demo](https://jsbin.com/fowomo/edit?html,js,output)

**Comment by stefanpenner** [comment]
So this most likely blocks stable release?

**Comment by rwjblue** [comment]
@stefanpenner - Absolutely, but I just fixed it in glimmer-engine@0.17.10 and am working on PR here now.
