### ISSUE TITLE
Properly serializing non-primitive / array query parameters

### ISSUE THREAD

**Issue by buschtoens** [emberjs/ember.js#14598]
Query parameters seems to be getting a lot of attention lately, so I wanted to chime in with a feature request.

Currently non-primitive query parameter values are just passed through `encodeURIComponent(JSON.stringify(value))`, which results in rather ugly URLs.

This example controller pushes a `'d'` onto the original array, triggering a QP change.

```js
export default Ember.Controller.extend({
  queryParams: ['array'],
  array: ['a' ,'b', 'c'],
  
  init() {
    this._super(...arguments);
    
    Ember.run.schedule('afterRender', null, () => {
      this.get('array').pushObject('d');
    });
  }
});
```

The URL I would expect is:

```
/?array[]=a&array[]=b&array[]=c&array[]=d
```

However the URL I get is:

```
/?array=%5B%22a%22%2C%22b%22%2C%22c%22%2C%22d%22%5D
```

Here's a [Twiddle](https://ember-twiddle.com/?openFiles=controllers.application.js%2C&route=%2F%3Farray%3D%255B%2522a%2522%252C%2522b%2522%252C%2522c%2522%252C%2522d%2522%255D).

**Comment by rwjblue** [comment]
I _believe_ this is a duplicate of https://github.com/emberjs/ember.js/issues/14174, can you review and confirm?

**Comment by nathanhammond** [comment]
I do consider this to be a duplicate of #14174. @buschtoens I'm working on this over here: https://github.com/nathanhammond/query-string-spec

**Comment by buschtoens** [comment]
Awesome! I'll keep an eye on your repo. Thaks a lot. :smiley:
