### ISSUE TITLE
HMR Hot Reload

### ISSUE THREAD

**Issue by hamzahio** [emberjs/ember.js#14608]
Good Day Ember Team,

I was building new tool to simplify creating ember app without files structure.

Everything we write in Ember-cli is an object so why not created it as json structure. then just fill the json with functions or variables or anything.

this JSON is your application file.

there is any javascript which convert all your json functions into js functions, and create AMD modules.

everything was working fine but when i want replace controller which already cached i can't remove it from app and load the new one.

i used 

```
app.unregister("controller:application")
```
but controller is still in memory and i can't 

```
 var dataApp = Ember.A([
    {
      "path": "app/application/controller",
      "import": ['exports', 'ember'],
      "arrg": ['exports','_ember'],
      "functions": "exports['default'] = _ember['default'].Controller.extend({\n   active: function(){ console.log('application controller')},\n    editing: false,\n    activeComponent: null\n  })\n"
    },
    {
      "path": "app/index/controller",
      "import": ['exports', 'ember'],
      "arrg": ['exports','_ember'],
      "functions": "exports['default'] = _ember['default'].Controller.extend({\n   active: function(){ console.log('index controller')},\n    editing: false,\n    activeComponent: null\n  })\n"
    }
  ]);
// all this is working fine
dataApp.forEach(function(i){
  define(i.path, i.import , new Function(i.arrg,i.functions))
})

// this function where problem is 
function hotReload(){
  console.log('hotReload');
  var i = {
      "path": "app/application/controller",
      "import": ['exports', 'ember'],
      "arrg": ['exports','_ember'],
      "functions": "exports['default'] = _ember['default'].Controller.extend({\n   active: function(){ console.log('application controller new')},\n    editing: false,\n    activeComponent: null\n  })\n"
    };
    var name = 'controller:application';
    app.unregister(name);
    console.log(Testapp.hasRegistration(name));
    delete requirejs.entries[i.path];
    define(i.path, i.import , new Function(i.arrg,i.functions));
    app.register(name);
}
 hotReload()



```

**Comment by Serabe** [comment]
Hello, @hamzahio!

Thank you for writing this. Originally, Ember apps were written in a similar way using global variables. That was a long time ago, though it is still supported, it is discouraged since you would be losing all the ecosystem that Ember CLI has.

Currently, hot reloading is not supported and as such, it would require opening an issue and following the RFC process.

Closing this since it is not an issue.

Thank you!

**Comment by hamzahio** [comment]
Thank you Serabe

i just want to remove controller and route then update it with new ones.
