### ISSUE TITLE
Ember 2.10 Blog Post Items

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#14600]
Things to call out:

* In development, `Ember.Helper.helper` and `Ember.Helper#compute` arguments are now frozen with `Object.freeze`. [issue#14189](https://github.com/emberjs/ember.js/issues/14189) [PR#14244](https://github.com/emberjs/ember.js/pull/14244)
  * Known [issue](https://github.com/emberjs/ember.js/pull/14649): you cannot just return the params passed into the helper. Will followup with a fix in a patch.
* Glimmer2 OMG
  * Should backtracking rerender be called out?
* Several QP bugfixes

**Comment by mixonic** [comment]
Closing in favor of https://github.com/emberjs/website/pull/2727
