### ISSUE TITLE
Ember 2.11 Blog Post Items

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#14601]
Things to call out:

* `concatenatedProperties` are now frozen in development. [PR#14389](https://github.com/emberjs/ember.js/pull/14389). In particular this means `Ember.Component`'s `classNames`, `attributeBindings`, `classNameBindings` are frozen in dev.
* `renderToElement` has been deprecated in 2.11 [issue#14158](https://github.com/emberjs/ember.js/issues/14158) [pr#14482](https://github.com/emberjs/ember.js/pull/14482) [deprecation guide PR](https://github.com/emberjs/website/pull/2702)
* `{{render}}` has been completely deprecated in 2.11. Previously, `{{render}}` with a model argument was deprecated. In 2.11 usage without an argument is also deprecated. Additionally `{{render 'someNamedOutlet'}}` with `this.render({into: 'someNamedOutlet'})` on a route has been deprecated. [issue#13583](https://github.com/emberjs/ember.js/issues/13583) [PR#14441](https://github.com/emberjs/ember.js/pull/14441) [deprecation guide PR](https://github.com/emberjs/website/pull/2700)

**Comment by mixonic** [comment]
Closing in favor of https://github.com/emberjs/website/pull/2727
