### ISSUE TITLE
Empty Maps don't trigger {{else}} clause in {{each}} helper

### ISSUE THREAD

**Issue by lllama** [emberjs/ember.js#14613]
As seen here: https://ember-twiddle.com/d5fc36aac83481a93c0eba3873eb8712

the `{{each}}` helper will let you loop over a `Map` but if the `Map` is empty, then the `{{else}}` clause is not entered. I believe that this is due to Maps using `size` rather than `length`.

I'm happy to try to work on a pull request for this, but would appreciate a steer on whether `Map`s should be supported in this way.

**Comment by pixelhandler** [comment]
@lllama I don't believe that Maps were intended to be enumerable with the each helper. See http://emberjs.com/api/classes/Ember.Map.html vs http://emberjs.com/api/classes/Ember.Array.html (which uses Enumerable)

**Comment by lllama** [comment]
Thanks @pixelhandler. Would the `each-in` helper be more appropriate? (also doesn't currently work.)
