### ISSUE TITLE
Glimmer2 handles `select` `attributeBindings` differently

### ISSUE THREAD

**Issue by dnachev** [emberjs/ember.js#14614]
Twiddle: https://ember-twiddle.com/537d91753ca5fb6f4ba704b496623e74

The twiddle has a component with `tagName: 'select'` and `attributeBinding: ['value']`. In Glimmer, if `value` is passed as `null` or `undefined`, the `element.value` property will be set, which will reset the value to empty. In case of Glimmer2, it will remove the `value` attribute from the element, which doesn't have any effect on the actual value of the `select` element.

Technically, setting `null`/`undefined` for `value` of an `input` or `select` is probably not advisable, but it seems there is call to handle it for `input`, so it should be handled for `select` as well.

**Comment by rwjblue** [comment]
Thank you for reporting! This is ultimately the same issue as https://github.com/emberjs/ember.js/issues/14612 (I know they seem very different).  We are working on the fix over in tildeio/glimmer repo, and will update here when things are resolved...
