### ISSUE TITLE
Error message: "Error: A non-recoverable condition has triggered.  Watchman needs your help!"

### ISSUE THREAD

**Issue by bobmulder** [emberjs/ember.js#14618]
Hi all!

I'm new to Ember.js, but found a bug and have a possible reason for this... When I tried to run `ember server` I got the following load in my terminal:

```
Error: A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1479505942: inotify-add-watch(/home/bob/Projects/Test/ember-quickstart/node_modules/ember-cli/node_modules/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/es6-symbol/node_modules/es5-ext/test/error) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch
```
> This message repeated around 50 times with several paths...

I think the following thing is wrong: watchman tries to watch on every folder, which requires an `user_instance` or `user_watch`. Watchman is trying to wath on folders inside `node_modules` which has a lot of dependencies!

I did the following in my `.watchmanconfig`:
```
{
  "ignore_dirs": ["tmp", "dist", "node_modules", "bower_components"]
}
```
> I've added `node_modules` and `bower_components`

This will ingore those package-folders, and no error raised...

I hope I helped you this way. If I did anything wrong, let me know :) 

Greetz,

Bob

**Comment by pixelhandler** [comment]
@bobmulder this is not an Ember.js bug, perhaps reach out in the http://embercommunity.slack.com #-help channel to chat regarding solutions to the issue you are experiencing with Ember CLI.

**Comment by acorncom** [comment]
We've been discussing this a bit on Slack, I'll close this for now
