### ISSUE TITLE
Standardize Template Error Structure

### ISSUE THREAD

**Issue by jfelchner** [emberjs/ember.js#14625]
I'd like to begin standardizing the template error structure returned by all of the various Ember components such that we can better utilize the plethora of information that is known at the time the error is thrown.

One of the major end results of this is the ability to generate a very user-friendly error page to developers: https://github.com/ember-cli/broccoli-middleware/pull/4#issuecomment-260112229

The error structure is still up for discussion, but will be documented [here](https://github.com/ember-cli/ember-cli/issues/6441) along with the work required on the various other parts of the Ember ecosystem.

Some of the notable locations here in Ember.js are:

* https://github.com/emberjs/ember.js/search?utf8=%E2%9C%93&q=path%3Apackages%2Fember-template-compiler%2Flib+assert&type=Code

/cc @rwjblue @stefanpenner

**Comment by rwjblue** [comment]
I'd definitely love to see progress here, but at this point I think this particular issue is a bit stale so I'm going to go ahead and close it out.

@jfelchner if you still intend to push this forward, let me know and I can reopen (and I'm happy to help with the specifics if you'd like to chat through them)...

**Comment by jfelchner** [comment]
@rwjblue I've asked multiple people multiple times to help get me started on this and haven't been able to connect.  So at this point there's nothing for me to do.
