### ISSUE TITLE
Route.replaceWith should support the "options" argument, like transitionTo

### ISSUE THREAD

**Issue by vmalloc** [emberjs/ember.js#14622]
Currently it is impossible to use replaceWith with query parameters, since it doesn't have the `options` argument that is supported by `transitionTo`

**Comment by nathanhammond** [comment]
@vmalloc See also: https://github.com/emberjs/rfcs/issues/170#issuecomment-256708564

**Comment by vmalloc** [comment]
@nathanhammond I'm not sure what the conclusion of that is... The end result I'm trying to achieve is to transition to a route, with specific query params, but without pushing another history state item. 

We ended up messing with the history API ourselves since we saw no built-in way to do this in Ember...

**Comment by locks** [comment]
I believe this has since been addressed.
