### ISSUE TITLE
Can't acceptance test error routes

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#14627]
I'm trying to test that the an error route is displayed correctly if an error occurs in our application.
Like so:

```javascript
import { skip } from 'qunit';
import moduleForAcceptance from 'foo-app/tests/helpers/module-for-acceptance';
import Pretender from 'pretender';

let server;

moduleForAcceptance('acceptance:error', {
  beforeEach() {
    server = new Pretender(function() {
      this.get('/api/foo', () => {
        return [500, {}, null];
      });
    });
  },
  afterEach() {
    server.shutdown();
  }
});

skip('error', function(assert) {
  assert.expect(1);

  visit('/');

  andThen(() => {
    // can't get here...
  });
});
```

The problem being that because an error has occurred, the suite fails regardless.

(Sorry if this has been submitted to the wrong repo, it's not clear where this belongs).

**Comment by pixelhandler** [comment]
@amk221 I think this duplicates #12791 see that issue for workarounds

**Comment by pixelhandler** [comment]
@amk221 did any of the recommendations in #12791 work for you, If so perhaps we can close this one. I have not seen any strong support for changing the testing behavior for the error handing case in acceptance testing. It seems the work around has been sufficient for most.

**Comment by amk221** [comment]
Sure, [this solution](https://github.com/emberjs/ember.js/issues/12791#issuecomment-170675020) is adequate - thanks.
