### ISSUE TITLE
Components - Stronger adherence to W3C requirements on valid names

### ISSUE THREAD

**Issue by bcardarella** [emberjs/ember.js#14635]
For example, the following disallowed (according to the spec) names can be used as component names in Ember:

* annotation-xml
* color-profile
* font-face
* font-face-src
* font-face-uri
* font-face-format
* font-face-name
* missing-glyph

There are other rules around how the naming requirements. If the goal of components is to eventually move from `{{foo-bar}}` to `<foo-bar>` I would assume the full spec would have to be respected:

https://www.w3.org/TR/2016/WD-custom-elements-20161013/#valid-custom-element-name

**Comment by pixelhandler** [comment]
@bcardarella do you think this needs to be an RFC issue?  [CONTRIBUTING.md#requesting-a-feature](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature) which recommends creating an RFC Issue to request a feature/enhancement (no need for a PR with RFC, only an issue in the repo)

**Comment by bcardarella** [comment]
¯\_(ツ)_/¯   this issue hasn't had any response from core so I am uncertain as to what direction, if any, should be taken

**Comment by tomdale** [comment]
@bcardarella Sorry for the lack of movement on this, I am just seeing the issue now. I agree it's weird to half-follow the spec and have the dash constraint but not the other constraints.

1. Is there an existing library that encodes the Custom Elements spec rules that we can reuse?
2. I would be open to a PR that issues a warning if you use one of the reserved names. I don't think we can hard error as it's a backwards-incompatible change.

**Comment by locks** [comment]
I am closing this issue given the recent change in direction away from using custom elements and towards `<CapitalCase />`.
