### ISSUE TITLE
element property does not exist in tests

### ISSUE THREAD

**Issue by mkay581** [emberjs/ember.js#14630]
Apologies if this has already been discussed. But why isn't the `element` property available on contexts in integration tests, but the jQuery version of it is. In other words, why does this happen when done in an integration test?

```js
test('element property is available', function(assert) {
  this.render(hbs`{{my-fake-component}}`);
  assert.ok(this.get('element')); // fails; undefined!
  assert.ok(this.$()[0]); // passes
});
```

**Comment by Serabe** [comment]
@Turbo87 should we close this issue and track it in the `ember-test-helpers` repo or should we keep this open?

**Comment by Turbo87** [comment]
@Serabe yes, I think that would be the right repo to track it.

@mkay581 we've moved your question/request over to https://github.com/emberjs/ember-test-helpers/issues/184

**Comment by Serabe** [comment]
Thank you, @mkay581 and @Turbo87! Closing this to track it in the linked issue.

**Comment by mkay581** [comment]
Awesome, thanks!
