### ISSUE TITLE
Add helpful assertion when using component helper with input or textarea. 

### ISSUE THREAD

**Issue by bcardarella** [emberjs/ember.js#14632]
How to recreate:

```hbs
{{component "input" value=foo}}
```

I'm assuming the same is for other non-hyphenated Ember components.

**Comment by Serabe** [comment]
`{{input}}` is not a component but a keyword. I wrote about it [here](http://www.serabe.com/2016/03/02/the-path-to-contextual-components-understanding-dynamic-components/)

Thank you!

**Comment by bcardarella** [comment]
For future reference, the solutions are:

```hbs
{{component "-text-field"}}
{{component "-text-area"}}
```

I'm not sure why these components are private. In any event, it might be helpful for people to get an error with `Ember.assert` if they try to use `input` or `textarea`. FWIW, it is not obvious at all to the developer that these are helpers. Furthermore, their implementations are buried pretty deep within the bowels of Ember itself. It took me a good long while to find them.

**Comment by rwjblue** [comment]
Agreed. Updated title and reopening. 

Would love someone to tackle this, it _should_ be fairly straightforward I think. Happy to help someone on implementation...

**Comment by bcardarella** [comment]
@rwjblue I can do it. I just want to confirm that the suggested assertion will be to use the private component names?

**Comment by Serabe** [comment]
IMHO, I would not suggest people to use private components.

In any case, it would be great to know what can we do to improve our documentation about the input helper to make clear that it is a helper. The current API section specifies so, but there might be some place we overlooked.

Thank you!

**Comment by bcardarella** [comment]
> I would not suggest people to use private components

confirm, I lean towards this as well. However, I do think the experience is confusing for `input` and `textarea`. If not a recommendation to use the private components would we be able to promote those components to the public or would there be some other assertion to raise to give some help to people? While improved documentation is great I do think the assertion would be the fastest feedback loop.

**Comment by rwjblue** [comment]
Well, we can definitely inform folks that you can't use `input` with the component helper. That would be better than what we have today already (since today it throws bizarre and unhelpful errors). 

The question is what do we suggest people do instead. I think for now the best thing to suggest is for folks to make their own components that extend from `Ember.TextArea` or `Ember.TextField` (since this is at least already public API). I realize that doesn't "feel" super good, and I'd definitely be in favor of figuring out a better solution.
