### ISSUE TITLE
Passing a model and queryParams to controller.replaceRoute

### ISSUE THREAD

**Issue by sivamahadevan** [emberjs/ember.js#14631]
From the ember docs for controller.replaceRoute, it states that "...beside that, it is identical to transitionToRoute in all other respects." I noticed that controller.transitionToRoute allows passing in an options object in which a queryParams object can be specified. In my current use case, I would like to use replaceRoute instead, but I cannot pass in that same options object (replaceRoute only seems to take in a route and a models argument). Is there a reason for omitting the options argument from replaceRoute?

**Comment by locks** [comment]
Thank you for reporting @sivamahadevan. Since this is a duplicate, we'll track this issue at https://github.com/emberjs/ember.js/issues/14622.
