### ISSUE TITLE
[Glimmer2] Runtime exception when yielding values within partial

### ISSUE THREAD

**Issue by simonihmig** [emberjs/ember.js#14642]
This is related to #14263, which was fixed by @chancancode recently. But a new error could be observed, that seems to be very much related.

After the changes from #14633 `hasBlock` worked again, but I started to get an exception of `TypeError: Cannot read property 'child' of null` in my build: https://travis-ci.org/kaliber5/ember-bootstrap/builds/179128906#L559. This is coming from `VM.pushChildScope`, so within Glimmer itself it seems.

Took me quite some time to isolate this, but it seems it happens when yielding values from the partial. Here is a Twiddle that reproduces this: https://ember-twiddle.com/5a29e54ab543a2668f1d725375d2e0ea

**Comment by simonihmig** [comment]
Just added a (failing) test: #14643

**Comment by chancancode** [comment]
Oops. Thank you for reporting! I am looking into it

**Comment by chancancode** [comment]
Should be fixed now!

**Comment by simonihmig** [comment]
Confirmed, this finally fixes the remaining failing tests for Glimmer2 in ember-bootstrap, all green now! Thanks a lot! 👍
