### ISSUE TITLE
Using triple braces to open and close html tags does not render properly

### ISSUE THREAD

**Issue by georges49** [emberjs/ember.js#14645]
In my controller javascript file I have the following:

```
"openTag": "<div>",
"closeTag": "</div>"
```

I want to be able to use them in my template like this:
```
{{{openTag}}}
    <button type="button" class="btn btn-default" >Button</button>
{{{closeTag}}}
```

The result I want is this:
```
<div>
    <button type="button" class="btn btn-default" >Button</button>
</div>
```

But instead it is rendering as this:
```
<div></div>
<button type="button" class="btn btn-default" >Button</button>
```

I want to run an each loop inside the openTag but the problem is the tag is not always a div, it could be a span,  p, section, ul or any other container tag, so I want it to be dynamic otherwise I have to insert an if block for each container.

Here is a twiddle showing the issue:
https://ember-twiddle.com/6215140de5cc4672593dcd26fcd4e415?openFiles=templates.application.hbs%2C

**Comment by stefanpenner** [comment]
I do not believe this is something we support, or plan to support.

**Comment by georges49** [comment]
Thanks for your quick reply.
So there is no way to make it work as it is?
I could write a helper that would return the whole block (loop over the array in the helper)
But I prefer to avoid this solution

**Comment by sly7-7** [comment]
@george49 Why not defining a component, passing it the tagName ? 
https://ember-twiddle.com/6215140de5cc4672593dcd26fcd4e415?openFiles=templates.application.hbs%2Ctemplates.components.x-foo.hbs

**Comment by georges49** [comment]
@sly7-7 Unfortunately the twiddle you posted is not working for me.
It is showing the same content of the twiddle I posted (without the component).

**Comment by georges49** [comment]
Btw my code depends heavily on the component I'm in. It is a bit complicated. At the moment I'm using partials(3 of them), if I replace the one partial in which I want to render the tagName with a component, I'll have to pass a lot of parameters.

**Comment by GavinJoyce** [comment]
@georges49 try this: https://ember-twiddle.com/7c2ef8de215e1aba6f1e87a0a3daa17e?openFiles=templates.application.hbs%2Ctemplates.components.my-component.hbs

**Comment by georges49** [comment]
Very neat, I wasn't aware that a component could be called this way. This solved my problem.
Many many thanks.

**Comment by GavinJoyce** [comment]
Nice one. @georges49 perhaps you can close this issue now?
