### ISSUE TITLE
Input checkbox component does not update the checked property

### ISSUE THREAD

**Issue by anijap** [emberjs/ember.js#14640]
[Code sample](https://ember-twiddle.com/9739fb98b97cc18c1d1b278c29c519f2)

Note how the console output will keep printing "true", instead of alternating between "true" and "false".

The initial value of the property is respected, if the code is changed to `foo: false,`, it will render a checkbox that is initially unchecked.

It appears that the property value (in this code sample, the property is `foo`) does not get updated when the user interacts with the checkbox.

**Comment by Serabe** [comment]
By setting `change` you are overwriting the logic that changes the property. [Here](https://guides.emberjs.com/v2.9.0/templates/input-helpers/#toc_checkboxes) you have a complete list of properties you can pass to the `input` helper. 

If you need the change event and are using a modern Ember (> 2.0), consider using plain HTML inputs. [Twiddle](https://ember-twiddle.com/2c083611aaaedfd978e1080104c03977?numColumns=2&openFiles=templates.components.my-component.hbs%2Ctemplates.application.hbs)

Thank you!
