### ISSUE TITLE
[CLEANUP] Remove enabled features

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#14647]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10213084-50269186_6-s1-v1.png?transparent=1&width=246)

https://github.com/emberjs/ember.js/blob/master/features.json

Example: https://github.com/emberjs/ember.js/commit/b8bc459dbcd808dbc66d8811eb7116fa0a01831b

- [ ] ember-runtime-computed-uniq-by
- [ ] ember-runtime-enumerable-includes
- [ ] ember-string-ishtmlsafe
- [ ] ember-testing-check-waiters

**Comment by GavinJoyce** [comment]
I'll cut a PR for `ember-runtime-computed-uniq-by` now

**Comment by Patsy-issa** [comment]
Working on a pr for all of the above.

**Comment by vvscode** [comment]
@chancancode  this issue can be closed?

**Comment by locks** [comment]
Yup, thanks for pointing out!
