### ISSUE TITLE
How to prevent manual browser unload/refresh when working with File and FileList

### ISSUE THREAD

**Issue by joelpresence** [emberjs/ember.js#14656]
Hi,

Thanks for the awesome framework Ember!  I really appreciate all of your hard work.  :-)

I'm building an Ember app that allows people to upload media files (e.g. audio and video) from their local computer to our server and manage that content and its metadata.  In order to do that I need to work with HTML `File` and `FileList` objects since the only way I can get access to the user's local files is through the `file input` which returns a `FileList` of `File` objects.

The app allows the user to multi-select up to 100 files and then it puts those `File` objects in a queue and starts uploading them.  The problem is, if the user manually reloads the web page or refreshes it using browser controls, then the Ember app is reloaded and I lose all of these `File` objects.  How to prevent this?

Here are solutions I *cannot* use:

* **Store `File` in Local Storage:** the files are large (20 MB - 1 GB) so Base64 encoding them as a string and storing them as local storage just won't be feasible.
* **Store the `File` Path or Name:** as a security measure, the browser sets the path to `C:/fakepath` so there's no way I can see the real path to programatically reload the file on Ember app reload.

I know that my app "should be robust with reloads / refreshes" but this is beyond my control - it's the HTML standard that prevents me from caching/storing/programatically fetching `File` objects representing local files - they're an opaque blob.

So, are there any other solutions?

What is the most robust way to prevent the user from unloading/reloading/refreshing the tab that is showing the Ember app?

All suggestions welcome!  Thanks.

P.S. I realize that this isn't so much a bug of Ember but instead a drawback of all JS SPA compared to native apps.  And I'm not trying to start any flame wars ... I just need help!  :-)

**Comment by sandstrom** [comment]
I think this is a better fit for StackOverflow, since this is a question and not related to a bug/issue in Ember. May I suggest that you close this issue and re-open a question there?

*(Slack or IRC would also work: http://emberjs.com/community/)*

**Comment by Serabe** [comment]
As @sandstrom said, we try to leave this section to bug reports. Please, ask the question in the #-help channel in the community Slack or, given the broader nature of the question, it might be more likely to get a great response in StackOverflow.

Thank you all!
