### ISSUE TITLE
{{log 'asd'}} breaks in Ember 2.10

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#14653]
I have a route and a simple template for it:

```hbs
{{log 'asd'}}
```

Which breaks with:

```
Uncaught Error: Assertion Failed: You attempted to overwrite the built-in helper "log" which is not allowed. Please rename the helper.
```

Unfortunately I cannot reproduce it easily with a simple application in an Ember Twiddle (I have more logic and nested routes, etc, however I am unsure what exactly causes the problem). I hope you can reproduce it somehow. I'm here to help any way I can.

**Comment by rwjblue** [comment]
The error is intended to report when you are providing a helper that is already provided by Ember itself.

See [this twiddle](https://ember-twiddle.com/76a1bfcc29afb74b51794aa99e411e86?openFiles=templates.application.hbs%2C) for a reproduction.

This assertion prevents apps/addons from overriding built-in helpers:

```
  "if",
  "action",
  "component",
  "concat",
  "debugger",
  "get",
  "hash",
  "loc",
  "log",
  "mut",
  "query-params",
  "readonly",
  "unbound",
  "unless",
  "-class",
  "-each-in",
  "-input-type",
  "-normalize-class",
  "-html-safe",
  "-get-dynamic-var"
```

---

My guess is that you have a `app/helpers/log.js`?

**Comment by boris-petrov** [comment]
Well, we don't have such a helper, however doing a find results in:

```
%  find . -wholename "*/helpers/log.*"
./tmp/broccoli_merge_trees-output_path-C92gwiLM.tmp/helpers/log.js
./tmp/coffee_script_filter-output_path-nzk9H1tO.tmp/frontend/helpers/log.js
./tmp/babel-output_path-1cMdL1T1.tmp/frontend/helpers/log.js
./tmp/coffee_script_linter-output_path-3wyt4RiT.tmp/frontend/helpers/log.js
./node_modules/bower/lib/node_modules/handlebars/dist/amd/handlebars/helpers/log.js
./node_modules/bower/lib/node_modules/handlebars/dist/cjs/handlebars/helpers/log.js
./node_modules/bower/lib/node_modules/handlebars/lib/handlebars/helpers/log.js
./node_modules/ember-drag-drop/app/helpers/log.js
./node_modules/handlebars/dist/amd/handlebars/helpers/log.js
./node_modules/handlebars/dist/cjs/handlebars/helpers/log.js
./node_modules/handlebars/lib/handlebars/helpers/log.js
```

Which makes the problem obvious - `ember-drag-drop` defines a `log` helper for some reason... thanks for the help, marking as resolved!
