### ISSUE TITLE
Ember 2.10.0 didUpdateAttrs firing incorrectly

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#14654]
Here is a Twiddle:
https://ember-twiddle.com/fd53b517896332db9f362195aefe588f?openFiles=components.my-component.js%2Ctemplates.components.my-component-option.hbs

- Run the twiddle with 2.9.0
- Click on some options and notice nothing is logged to the console.
- Switch to 2.10.0 and notice that `didUpdateAttrs` is being called unnecessarily.

This manifests itself as a [failing test](https://github.com/amk221/ember-select-box/blob/8278e0b26f7b1cd1f8384ad256c541e25a448dc5/tests/integration/components/select-box/selecting-test.js#L243) in my ember-select-box repo.

**Comment by chancancode** [comment]
Thanks for reporting! I'm looking into fixing this one

**Comment by amk221** [comment]
Thank you!

**Comment by chancancode** [comment]
@amk221 this was fixed in 2.10.1 😄
