### ISSUE TITLE
Cannot use a Handlebars comment in an attribute in Ember 2.10

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#14652]
We had the following working code in Ember 2.9.1:

```hbs
<span style={{!some-helper some-value}}></span>
```

In Ember 2.10 we get the following JavaScript error:

```
Uncaught Error: Using a Handlebars comment when in the `beforeAttributeValue` state is not supported: "some-helper some-value" on line 1:12
```

It this expected?

**Comment by rwjblue** [comment]
Hmm. I introduced that error message in https://github.com/tildeio/glimmer/pull/340. 

In this case, under 2.9 the following would be rendered:

```hbs
<span style></span>
```

Which seems pretty odd to me, I think the error is actually good but I welcome other's input...

**Comment by rwjblue** [comment]
@mmun / @mixonic - Thoughts here?

**Comment by mmun** [comment]
I think it would be nice to have a way to comment out attributes. We could make

```hbs
<span style={{!some-helper some-value}}></span>
```

become

```hbs
<span></span>
```

and

```hbs
<span style="foo{{!some-helper some-value}}bar"></span>
```

become

```hbs
<span style="foobar"></span>
```

It feels a bit bad to add more special cases, but I think they're intuitive in this case.

**Comment by Serabe** [comment]
After tildeio/glimmer#340, `<div style={{!something}}></div>` cannot be parsed (was trying to fix this).

**Comment by rwjblue** [comment]
@Serabe - Confirm, that is what this issue is referring to.

**Comment by Serabe** [comment]
I would say that for the first case, the result should be:

```html
<span style></span>
```

And if the user wants to remove the style completely, they can just do:

```hbs
<span {{! style={{! some-helper some-value}}>
```

For style might be a bit useless, but can be interesting for _props_.

**Comment by Serabe** [comment]
@rwjblue sorry I misunderstood :(

**Comment by pixelhandler** [comment]
@mmun I think that a commented out assignment for an HTML attribute that results in the disappearing of the attribute is an act of magic.

I'd rather that developers just comment out the entire attribute vs. a special and magical use case of a handlebars comment as an inline assignment for an HTML attribute.

**Comment by pixelhandler** [comment]
@rwjblue I think that the same behavior of Ember 2.9 would be sufficient and also doesn't introduce a change in behavior for handlebars comments.

**Comment by mmun** [comment]
@pixelhandler Yeah, I agree. I don't know why I ruled that out but it should be fine to do that syntactically.

**Comment by boris-petrov** [comment]
@pixelhandler - well, the issue remains as of Ember 3.4. The same error message still appears.

I personally think that what @mmun suggested in [his first post](https://github.com/emberjs/ember.js/issues/14652#issuecomment-263678250) makes sense the most and is also what I think should happen. But of course disallowing things like that as is right now is also fine.

**Comment by rwjblue** [comment]
I think its fine, but it would require someone who cares enough to champion the issue. 

As it stands now, the current behavior doesn't seem like a bug to me, we have a reasonable work around, so I'm going to close this issue...
