### ISSUE TITLE
Convenience property for current route

### ISSUE THREAD

**Issue by graham-sportsmgmt** [emberjs/ember.js#14662]
Having a string property available globally that can relay the current route (path + resource) is usable to create breadcrumbs-style visualizations and route-specific sections in templates.

Although there are workarounds for this, it would be great to have something that is readily accessible for developers that are new to EmberJS.

http://stackoverflow.com/questions/17244353/how-to-get-current-routename

EDIT - I've just found out that there is a currentPath in the router, this might need to be changed to a "please document this feature" request.

https://github.com/emberjs/ember.js/blob/v1.0.0-rc.5/packages/ember-routing/lib/system/router.js#L75

**Comment by locks** [comment]
Hi, thanks for you feedback. This should be addressed by the [Router service RFC](https://github.com/emberjs/rfcs/blob/master/text/0095-router-service.md) which is currently being implemented. For the moment you do have to resort to shenanigans with the application controller's `currentPath`.

**Comment by graham-sportsmgmt** [comment]
Thank you.
