### ISSUE TITLE
Ember 2.10.0 - Calling this.$() in willDestroyElement hooks during unit tests returns undefined

### ISSUE THREAD

**Issue by omarestrella** [emberjs/ember.js#14666]
After upgrading to Ember 2.10.0, our component unit tests started breaking when `willDestroyElement` runs because `this.$()` is now returning `undefined`. This was not happening in Ember 2.9.0.

You can see this happening in [this ember-twiddle](https://ember-twiddle.com/fb2369455c41b581444f4b34d92f0cf6?openFiles=tests.unit.components.my-component-test.js%2C).

**Comment by pixelhandler** [comment]
This looks like a Bug, we should be able to use `this.$()` in `willDestroyElement`, especially to remove event listeners.

**Comment by kamilogorek** [comment]
Bug flow:
- `Renderer` calls `remove` method which contains `_transitionTo('destroying')` function call [https://github.com/emberjs/ember.js/blob/45f1416d8a4fdf66102c0fb959087d3c733d0f21/packages/ember-glimmer/lib/renderer.js#L219-L233](link)
- `_transitionTo` change `currentState` to `destroying` [https://github.com/emberjs/ember.js/blob/aeeddf7c00b42a340494465252481b5414d87009/packages/ember-views/lib/mixins/view_state_support.js](link)
- `_states` lookup endup finding `destroying` state [https://github.com/emberjs/ember.js/blob/aeeddf7c00b42a340494465252481b5414d87009/packages/ember-views/lib/views/states.js](link)
- which is created using `default` state [https://github.com/emberjs/ember.js/blob/aeeddf7c00b42a340494465252481b5414d87009/packages/ember-views/lib/views/states/destroying.js](link1) [https://github.com/emberjs/ember.js/blob/aeeddf7c00b42a340494465252481b5414d87009/packages/ember-views/lib/views/states/default.js](link2)
- which on the other hand returns `undefined` for `$()` calls [https://github.com/emberjs/ember.js/blob/aeeddf7c00b42a340494465252481b5414d87009/packages/ember-views/lib/views/states/default.js#L17-L19](link)

**Comment by chancancode** [comment]
@omarestrella @kamilogorek this is fixed in 2.10.2, thanks for reporting!
