### ISSUE TITLE
Add blueprints for "ember-cli-mocha >= 0.12.0"

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#14667]
`ember-cli-mocha@0.12.0` introduced a [new testing API](https://github.com/emberjs/ember-mocha#upgrading) and deprecated the old `describeXXX()` helpers. The blueprints in this repository need to be updated to reflect those changes.

Instead of just updating we should make sure that uses with all versions of `ember-cli-mocha` get the right blueprints. We can accomplish that by checking the installed version of `ember-cli-mocha` using a [VersionChecker](https://github.com/rwjblue/ember-cli-version-checker) and then deciding whether to use the `mocha-files` or `mocha-0.12-files` blueprints folder.

The tracking issue for this is https://github.com/ember-cli/ember-cli-mocha/issues/142

**Comment by rwjblue** [comment]
Sounds like a good plan to me...

**Comment by Turbo87** [comment]
@rwjblue can we target the `beta` branch with this change?

**Comment by rwjblue** [comment]
Assuming it lands within the next couple weeks, yes.  But you would target `master` branch with a commit prefixed by `[BUGFIX beta]`.

**Comment by cs3b** [comment]
what about acceptance tests? shouldn't we add template for >= 0.12.0 ?

https://github.com/emberjs/ember.js/tree/master/blueprints/acceptance-test

**Comment by rwjblue** [comment]
@cs3b - In general, commenting on a previously closed issue is going to be missed. Please open a new issue with an explanation of the issue you are seeing...
