### ISSUE TITLE
Ember 2.10 - EmptyObject doesn't provide hasOwnProperty

### ISSUE THREAD

**Issue by aroberts** [emberjs/ember.js#14668]
This looks like an oversight, since every JS object descended from Object should provide this method. EmptyObject could implement this with `return false`, or via the Object prototype.

**Comment by rwjblue** [comment]
Definitely not an oversight.  `EmptyObject` is intended to emulate the result of `Object.create(null)` which definitely does not include `hasOwnProperty`.

**Comment by aroberts** [comment]
Interesting. I am getting `EmptyObject` from the last parameter of a helper, and attempting to pass it directly to a 3rd party library, which is using `isObject` to decide if a passed parameter supports `hasOwnProperty`. Is there a better solution for me than explicitly detecting `EmptyObject` in my helper and replace it with `{}`?

**Comment by rwjblue** [comment]
Firstly, I'd suggest that the third party lib should be updated and be made a bit smarter about this.  `Object.create(null)` is a pretty common technique to ensure no property collisions occur...

Secondly, you can use something like this to work around the issue until the lib gets updated:

```js
export default Ember.Helper.helper(function(params, hash) {
  let objectForLib = {};
  Ember.assign(objectForLib, hash);
  
  externalLib(objectForLib);
});
```

**Comment by aroberts** [comment]
Great, thanks for your help!
