### ISSUE TITLE
Ember 2.10 - Cannot bind list attribute to input

### ISSUE THREAD

**Issue by FilmKnurd** [emberjs/ember.js#14665]
**Expectation**: `list` attribute can be bound on input component `{{input list="list-id"}}`
**Result**: Error thrown in Chrome `Cannot assign to read only property 'list' of object '#<HTMLInputElement>'`

For example, check out this [fiddle](https://ember-twiddle.com/183b25389434a3920350fc9c0d918a30?openFiles=templates.application.hbs%2C)

It works in Safari but not in Chrome.

**Comment by GavinJoyce** [comment]
**Ember 2.10.0:**

<img width="1270" alt="screen shot 2016-12-01 at 19 04 19" src="https://cloud.githubusercontent.com/assets/2526/20808042/16be193c-b7f9-11e6-85d5-d0ee3ebc527e.png">

**Ember 2.9.0:**

<img width="1274" alt="screen shot 2016-12-01 at 19 04 38" src="https://cloud.githubusercontent.com/assets/2526/20808069/2a2d406a-b7f9-11e6-88a6-32e4ec163216.png">

**Comment by Serabe** [comment]
I would not consider this a bug given that `list` is not in [the documentation](https://guides.emberjs.com/v2.10.0/templates/input-helpers/) as one of the parameters accepted.

**Comment by GavinJoyce** [comment]
@Serabe it seems to be something more fundamental.

`<input list="{{foo}}" />` doesn't work either:

https://ember-twiddle.com/6304b98c3ad5d479d426a0c493e8b034?openFiles=templates.application.hbs%2C

<img width="1275" alt="screen shot 2016-12-01 at 20 07 14" src="https://cloud.githubusercontent.com/assets/2526/20810541/04b02858-b802-11e6-86ee-22d2c7bd025e.png">

**Comment by GavinJoyce** [comment]
<img width="856" alt="screen shot 2016-12-01 at 20 12 57" src="https://cloud.githubusercontent.com/assets/2526/20810688/98c3358a-b802-11e6-9e9d-423a8f697f81.png">

**Comment by GavinJoyce** [comment]
This has been fixed in Glimmer: https://github.com/tildeio/glimmer/pull/354

**Comment by FilmKnurd** [comment]
Thanks @GavinJoyce !

**Comment by FilmKnurd** [comment]
@Serabe I guess if you don't consider code documentation :wink: https://github.com/emberjs/ember.js/blob/v2.10.0/packages/ember-glimmer/lib/components/text_field.js#L74

**Comment by rwjblue** [comment]
@FilmKnurd - FWIW, code is definitely not documentation 😝

**Comment by pwnall** [comment]
This broke my app as well. Any chance we can get a point release that includes the glimmer fix? 😍

**Comment by rwjblue** [comment]
@pwnall - Yep, for sure.

**Comment by GavinJoyce** [comment]
This can be closed now that `2.10.1` is out
