### ISSUE TITLE
[Regression 2.10.0] Component `this.rerender` does not rerender `each-in`

### ISSUE THREAD

**Issue by SaladFork** [emberjs/ember.js#14661]
The [Ember.js guides mention](https://guides.emberjs.com/v2.10.0/templates/displaying-the-keys-in-an-object/#toc_re-rendering) that when using `each-in` in a template where the keys might change, you'll have to use `this.rerender()`. This worked as expected in 2.9.0. However, in 2.10.0, the `each-in` does not appear to be rerendered.

### Reproduction
https://ember-twiddle.com/335cb36aede080305dffa5efd7c14475

To reproduce the issue:
 1) Type something in the input field
 2) Hit the [Add] button
 3) Observe nothing changes visually
 4) Switch to Ember v2.9.0 (easiest way is dropdown at the top, Dependencies > Ember.js > 2.9.0)
 5) Repeat steps 1 and 2
 6) Observe template is updated as expected

This twiddle uses a component with an `each-in` loop in its template that loops over an object and displays its key/value pairs in a list. It also has a button which will add the contents of the input field next to it as a new key on the object, and call `rerender` on the component. In 2.9.0 this would result in the new key/value pair being displayed, but in 2.10.0 does not.

**Comment by rwjblue** [comment]
If the data is `set` it will be updated, also `this.rerender()` is no longer needed when adding new keys for `{{each-in`.

Demo without rerendering (with set): https://ember-twiddle.com/a64ad0093296b87e034d8da3279ca8f5?openFiles=components.my-component.js%2C

**Comment by SaladFork** [comment]
Hmm, my actual app code is quite a bit more complex (and also involves removing keys). Trying your approach results in: 
```
Assertion Failed: You must use Ember.set() to set the `CHILD_VIEW_IDS [id=__ember1480545924918304558307952]` property (of <mission-control@component:my-component::ember1757>) to `ember1759`."`
```
This error also breaks my ability to inspect the Component in the Ember Inspector. Will try and reproduce in ember-twiddle, but reverting to 2.9.0 does result in everything working again.

**Comment by rwjblue** [comment]
@SaladFork - Do you get that error when the console is closed?  I suspect that the inspector might be observing that private property for managing child views....

**Comment by SaladFork** [comment]
@rwjblue no 😞. Closing Ember Inspector (even with the console open) results in everything working as expected. Might have to move the issue over there.

If we no longer need to call `rerender` and the `set` approach is the recommended one, should we update the guides to reflect this?

**Comment by rwjblue** [comment]
> Might have to move the issue over there.

Agreed...

> If we no longer need to call rerender and the set approach is the recommended one, should we update the guides to reflect this?

Yes.

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
