### ISSUE TITLE
Edit the 'until' field on backtracking rerender deprecation for 2.8 LTS and 2.9

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/ember.js#14663]
Given #13948 if we are going to keep the assertion in Glimmer 2, should we release patches for 2.8 LTS and 2.9 to indicate that the deprecation will go away and behavior will stop working in 2.10 ?

**Comment by efx** [comment]
I think this would be helpful. I was confused by seeing our app's test suite break on 2.10 despite the deprecation warnings indicating until 3.0.

**Comment by rwjblue** [comment]
Agree that this whole situation was unfortunate and very annoying. I'm happy to accept PR's against those older branches if folks have time and care strongly.
