### ISSUE TITLE
ember v2.10.0 instllation issue

### ISSUE THREAD

**Issue by Anirudh-zemoso** [emberjs/ember.js#14679]
Could anyone please help me out in finding the issue. i tried to install latest node and npm . yet i still get this issue.

$ node -v
v6.9.1
$ npm -v
4.0.3
$ ember s --proxy http://localhost:5000 &
[1] 4412
$ No command 'ember' found, did you mean:
 Command 'enber' from package 'asn1c' (universe)
ember: command not found

**Comment by Serabe** [comment]
Hello, @Anirudh-zemoso:

We reserved the issues in Github for bugs. Please, use the Slack channel or discourse for asking questions.

In your case, try installing ember with `npm install -g ember`. For a more dynamic and fluid assistance, please, ask in the #-help channel in slack.

Thank you!

**Comment by tsing80** [comment]
> In your case, try installing ember with npm install -g ember

@Serabe should be ``npm install -g ember-cli``
