### ISSUE TITLE
[Regression] isVisible property undefined in Component in 2.10.0

### ISSUE THREAD

**Issue by tzellman** [emberjs/ember.js#14683]
https://ember-twiddle.com/d4792c20fe34bc3b5ec5330843ae4ffa

Switching to Ember 2.9.0 causes the example to render `No bug`.

**Comment by pixelhandler** [comment]
@tzellman the API docs indicates the default value for `isVisible` is `null`, see http://emberjs.com/api/classes/Ember.Component.html#property_isVisible 

Based on a `null` value I would expect the twiddle to render as it does using Ember 2.10, see http://emberjs.com/api/classes/Ember.Component.html#property_isVisible

**Comment by tzellman** [comment]
Thanks for the response/discussion. I was already aware of the documentation, and only posted here because my findings disagreed with what was stated.

I updated the twiddle to render (as a string) what the value is. It is never set `(value === undefined)`, which does not agree with the `null` expected value the documentation states.

Additionally, I have done other testing with `Ember.run.later` to check the value of `isVisible`, and it never appears to be set to anything other than `undefined`.

If `isVisible` is not the correct property to be using, is there a different/better option? I would like to avoid setting a bit for my Components after render/destroy events fire.

Thanks!

**Comment by rwjblue** [comment]
The value of `isVisible` will never be changed unless your application changes it. Ember uses this flag as a mechanism that allows you to easily add `display: none;` to a given component's element, but it never sets the property.

> If isVisible is not the correct property to be using, is there a different/better option? I would like to avoid setting a bit for my Components after render/destroy events fire.

Well, I think to answer the question properly, we need to be able to understand what you are trying to do.  Can you please describe your use case?

**Comment by tzellman** [comment]
Sure, no problem, and thanks again. This really isn't that big of a deal for me, as I only use the property within a `ResizeAware` mixin I have. Essentially, on a window resize event the handler does this type of check:

`if (!!this.get("isVisible") && !this.get("isDestroyed") && !this.get("isDestroying"))`

Again, not really a big deal. I thought I had found a bug, but it sounds like the fact that it was being set by Ember in previous versions prior to 2.10 must not have been the intention of the flag.

Thanks!

**Comment by gojefferson** [comment]
Perhaps the API documentation should clarify that a component's `isVisible` property will be `undefined` in certain cases? To me, the docs imply that checking this property is a reliable means of testing whether a component is visible in the DOM.

We had the following check, where `this` is a component:
```js
if (this.isVisible && !this.isDestroyed) {
  // do work
}
```
This worked before we upgraded to 2.10, but now fails because, in every instance, `this.isVisible` is undefined.

**Comment by pixelhandler** [comment]
Closing this out, the docs indicate that setting to`false` will hide from view, https://www.emberjs.com/api/ember/3.4/classes/Component/properties/isVisible?anchor=isVisible

> `isVisible` - If false, the view will appear hidden in DOM.
