### ISSUE TITLE
unable to install embefire :  connect ETIMEDOUT 

### ISSUE THREAD

**Issue by GuruCs1** [emberjs/ember.js#14680]
configuration
ember-cli : 2.8.0
node        : 6.5.0
os             : win32 x 64

I have tried the following commands 
1. npm install --save emberfire
2. ember install emberfire
3. npm cache clean and tried

I get the following error every time I try to install emberfire
"connect ETIMEDOUT 151.101.48.162:443
![capture](https://cloud.githubusercontent.com/assets/22782834/20903828/828ebf5c-bb02-11e6-9c35-08861d473a74.PNG)
"
can some one provide what's causing the issue and how to resolve it

**Comment by Serabe** [comment]
Hello, @GuruCs1. I am closing this since it is not an Emberjs bug. Please, go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

It seems a problem with the connection, since it is timing out.

Thank you!
