### ISSUE TITLE
Ember component never becomes visible after `isVisible` was set to `false`

### ISSUE THREAD

**Issue by monovertex** [emberjs/ember.js#14690]
In the `init` method of an Ember component, I set the `isVisible` property to `false` and it does not display, as expected. However, if I change this to true at any later moment, the component does not become visible again.

The weird part is that if you set the property to `false` in the component definition, this does not happen.

[Here is a simple Twiddle reproduction](https://ember-twiddle.com/af122e7ed71aa6134977cd33523328f2)

I'm not sure if I'm doing something wrong or this is a bug, the documentation is not really specific on this property.

I observed this first while using Ember 2.7, I think. It continued happening on 2.8 and 2.9.

**Comment by runspired** [comment]
I'm surprised this work prior to 2.7, based on how the visibility API is activatedI believe it needs to be present prior to `_super` in init. Changing your twiddle to do the set immediately prior to the _super fixes it.

**Comment by rwjblue** [comment]
As far as I can tell, the twiddle is working properly in Ember 2.10 (without the modification that @runspired suggested).

**Comment by monovertex** [comment]
@runspired, sorry, bad wording. I started using Ember around 2.7 and this project was created in that version, I just don't remember if it was 2.7 or 2.6. Thanks for the fix!

@rwjblue thanks, good news!

After reading around a bit, I saw that Ember is going towards dropping isVisible API support, so I went with a custom API for visibility instead, with classes.

Thanks for the help guys.
