### ISSUE TITLE
Problem with nested route, multiple outlet and renderTemplate

### ISSUE THREAD

**Issue by skaor** [emberjs/ember.js#14696]
If you have multiple template and a nested route there is a problem on the render. 

Take a look on the twiddle : https://ember-twiddle.com/ab594b12535d5a1f8405ecb1b537d567?openFiles=routes.second-entry.index.js%2C&route=%2Fsecond-entry

**Comment by skaor** [comment]
@nathanhammond

**Comment by pixelhandler** [comment]
@skaor Thanks for posting the twiddle example. Can you add more details to the description on this issue? E.g. what is the use case? What was the expected result? What was the actual result?

**Comment by nightire** [comment]
@skaor I don't know what's your final purpose, but perhaps you;ve forgot a `this._super(...arguments)` in `SecondEntryIndexRoute.renderTemplate()`.

Is this what you want?

https://ember-twiddle.com/ee8ac0daa55ab9c87a673fefe3727f11?openFiles=routes.second-entry.index.js

**Comment by nathanhammond** [comment]
Confirmed that this is a `_super` issue. Nominating for closure.

**Comment by skaor** [comment]
Yes sorry, i had the answer this morning. But why before it worked ? If you test without _super on 1.7 for example it works.
