### ISSUE TITLE
Ember 2.10.0 - Using "pods" structure will cause helpers not to register and render

### ISSUE THREAD

**Issue by rudymacias** [emberjs/ember.js#14699]
When using Ember CLI “pods” structure and updating to Ember 2.10.0 will cause Helpers not to work. No errors are given, just nothing is returned from helper. Seems as though Ember 2.10.0 looks for them in the “components” directory as if they were components.

Downgrading back to 2.9.0 (EmberJS), the Helpers worked as expected, no issues.

**Comment by locks** [comment]
Hi @rudymacias, thank you for your report but pods are currently considered EOL, so they're not actively supported as current efforts are being directed towards the [Module Unification RFC](https://github.com/emberjs/rfcs/blob/master/text/0143-module-unification.md).
If you have the time and inclination to chase this bug down, please reach us at the `#dev-ember` channel of our Slack group.

**Comment by nightire** [comment]
@rudymacias I upgrade three ember app to 2.10.0 recently, all helpers in these projects are behaving normally, maybe it's not because pods (we use pods as well).

**Comment by rwjblue** [comment]
@locks is a tad over zealous with the EOL label :smiling_imp:

Please provide a reproduction so that we can help you...

**Comment by locks** [comment]
Oops, sorry! I hope I didn't sound dismissive, the advice above of reaching us at `#dev-ember` still stands if you need help coming up with a reproduction!

**Comment by rudymacias** [comment]
All good @locks did not take it the wrong way, I'm definitely open to a new file structure. I think we should actually close this issue since trying to reproduce (again) on a new project with 2.10.0 (with pods setup) the helpers do work!

I thought I had tested this already so not sure what happened on my original test. I'll continue to troubleshoot my project that has the issue.

Thanks everyone @nightire @rwjblue @locks for your time.

**Comment by rudymacias** [comment]
Going to close now since my project is now working by updating 5 ember add-ons. One of them must caused the helpers issue I had.

- ember-cli-fastclick
- ember-cli-notifications
- ember-cordova
- ember-i18n
- ember-ted-select

Updating those dependencies to the latest versions seemed to do the trick.

**Comment by locks** [comment]
Thank you for the follow up! That list will come in handy if this issue pops up again, I'll try to reach out to the maintainers so they're aware.

**Comment by lrsnider** [comment]
Hi @locks, @rudymacias, and @nightire: 
I'm having trouble getting my test of a nested component within a pod findable by Qunit. I'm on Ember 2.8.0, so haven't upgraded to 2.10 just yet, but I wonder if you have any ideas.

The `component.js` file I want to test has this path (names substituted): `client/app/pods/component-name/sub-component,` and my test file is `client/tests/unit/pods/component-name/sub-component/component-test.js`. The test file starts out as:
```javascript
import { moduleForComponent, test } from 'ember-qunit';
import hbs from 'htmlbars-inline-precompile';

moduleForComponent('component-name/sub-component', 'Integration | Component | component-name/sub-component', {
  integration: true
});
```
But when I navigate to the test in the browser, it says `Error: Assertion Failed: A helper named "component-name" could not be found`.

When I tried generating a new component test with the command `ember g component-test sub-component -integration --pod`, the acceptance test passed but the next alert was the same as above, couldn't find that helper.
