### ISSUE TITLE
Improve "Backtracking re-render" assertion

### ISSUE THREAD

**Issue by GavinJoyce** [emberjs/ember.js#14709]
I've a few backtracking re-render issues to solve in my app and I'm interested in improving the assertions to make this easier for me and [others](https://github.com/emberjs/ember.js/issues/13948). This issue will serve as a place to capture any discussion or progress. 

The current assertion message for [this example](https://github.com/GavinJoyce/backtracking/pull/1) looks like:

`Assertion Failed: You modified model.name twice on [object Object] in a single render. This was unreliable and slow in Ember 1.x and is no longer supported...`

It would be nice to improve this to include more information on where the property was originally consumed as well as where it was then mutated. Something like this would be nice to aim for:

`Assertion Failed. You rendered "model.name" in "templates/example1.hbs" and modified it in "components/component-that-changes-name-on-init" in a single render. This was unreliable and slow in Ember 1.x and is no longer supported...`

Here are some thoughts from @chancancode on how we might do this.

https://embercommunity.slack.com/archives/dev-ember/p1481392322000438:

<img width="1025" alt="screen shot 2016-12-11 at 16 34 45" src="https://cloud.githubusercontent.com/assets/2526/21081479/c44583ba-bfbf-11e6-8f0e-e461ea93d362.png">

Useful links:

 * [ember-metal/lib/transaction.js](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/transaction.js)
 * [every time we consume](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/transaction.js#L36-L46)
 * [every time we set](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/transaction.js#L48-L78)

**Comment by GavinJoyce** [comment]
For the `You rendered "model.name" in "templates/example1.hbs"` part, we should aim to include this data in meta when in debug mode.

Looking at the available context where we currently set `lastRenderedFrom[key]`,  we don't appear to have easy access to anything that would allow us to identify the source template:

<img width="1054" alt="screen shot 2016-12-11 at 17 11 33" src="https://cloud.githubusercontent.com/assets/2526/21081750/e45686c2-bfc4-11e6-857e-a6c819065667.png">

We have easy access to:

 * the parent object and meta
 * the reference
 * the transaction context, which includes:

<img width="671" alt="screen shot 2016-12-11 at 17 21 23" src="https://cloud.githubusercontent.com/assets/2526/21081815/46da6006-bfc6-11e6-9325-43296f1ee319.png">

It's not immediately clear to me how we can get any source template details from this. Some ideas the I'm going to explore:

 * Can we calculate the last DOM node rendered that has the reference? If so, we should be able to work out the containing view
 * As we're rendering the view, can we store additional data in a new `lastRenderedIn` meta key?

**Comment by GavinJoyce** [comment]
https://embercommunity.slack.com/archives/dev-ember/p1481478414000479

<img width="997" alt="screen shot 2016-12-11 at 17 52 23" src="https://cloud.githubusercontent.com/assets/2526/21082034/9d66e922-bfca-11e6-96b9-bc7c86d5e5a3.png">

**Comment by GavinJoyce** [comment]
If we can find the last processed opcode which uses the same reference, we can access the DOM node:

<img width="750" alt="screen shot 2016-12-11 at 18 01 44" src="https://cloud.githubusercontent.com/assets/2526/21082100/09649150-bfcc-11e6-9a5e-f521578d2a78.png">

With the DOM node, we should be able to find a containing view.

**Comment by GavinJoyce** [comment]
We have a reference when setting `lastRenderedFrom`. We also have easy access to the transaction context:

<img width="741" alt="screen shot 2016-12-11 at 18 20 46" src="https://cloud.githubusercontent.com/assets/2526/21082190/9032a22e-bfce-11e6-93f5-293d2238e652.png">

Somewhere within the context, we have an opcode which also uses the same reference:

<img width="331" alt="screen shot 2016-12-11 at 18 16 33" src="https://cloud.githubusercontent.com/assets/2526/21082206/ce12e414-bfce-11e6-847b-30db090334f9.png">

This gives us access to `bounds` which includes pointers into the DOM. We can then determine which view this DOM belongs to and use this for the better assertion message.

Next steps:

 * [ ] how do we determine in the transaction context the last rendered opcode which uses the  reference?
 * [ ] will this work for other cases, eg. helpers and nested references 
 * [ ] can we map from DOM node to template identifer?

**Comment by chancancode** [comment]
@GavinJoyce another idea: we can potentially use `CurlyComponentManager#create` and `CurlyComponentManager#didRenderLayout` as a pair and keep a stack of "current component" (we currently use that for the component instrumentation, so I think it could work). So at least we can tell you which component's template was causing issues. Probably need to add more hooks to Glimmer if we want to get more granular than that.

**Comment by GavinJoyce** [comment]
@chancancode thanks, I've created a [quick spike](https://github.com/intercom/ember.js/compare/release...intercom:gj/2.10.0-with-backtracking-debugging?expand=1) (😷 using a global to track the last rendered component 😷) and it works pretty well in our app:

**Before:**

You modified `message.message_goal.description` twice on `<(subclass of Ember.Model):ember3486>` in a single render. This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.

**After:**

Assertion Failed: You rendered `message.message_goal.description` in `component:message-edit-expanding-container-component` and modified it in `component:rules/predicate-date-value-component (<(subclass of Ember.Model):ember3486>)` in a single render. This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.

**Comment by kiwiupover** [comment]
Thanks heaps Mr Joyce. @gavinjoyce
