### ISSUE TITLE
Ember 2.10.0 - Component from subfolder not work

### ISSUE THREAD

**Issue by 3AHAT0P** [emberjs/ember.js#14705]
After upgrading to Ember 2.10.0, can't usualy use components from subfolder.
Notation {{modal.test-one}} not working.
This was not happening in Ember 2.9.0.

You can see this happening in this [ember-twiddle.](https://ember-twiddle.com/538d66c92924f4f745117c34a8c2839d)

**Comment by rwjblue** [comment]
This type of invocation never intentionally worked actually. The proper way to invoke components from subfolders is:

```
{{modal/test-one}}
```

**Comment by 3AHAT0P** [comment]
Hmm. Thank you.

**Comment by locks** [comment]
For reference, this is a duplicate of https://github.com/emberjs/ember.js/issues/14224.
