### ISSUE TITLE
Feature request: queryParams isSticky option

### ISSUE THREAD

**Issue by alexmiddeleer** [emberjs/ember.js#14703]
Feature request for `queryParams` controller property: I'd love to see an isSticky query parameter rather than having to use the `resetController` hook. Having to explicitly pass a default value to `link-to` is inconvenient when a link is used in many places.

Adapted from https://guides.emberjs.com/v2.10.0/routing/query-params/

```
queryParams: ['page', 'filter',
  {
    showMagnifyingGlass: {
      scope: 'controller',
      as: 'glass',
      isSticky: false // <- new property
    }
  }
]
```

This seems less complex and mysterious than what is currently recommended in the guide:

```
// controllers/articles.js
import Ember from 'ember';

export default Ember.Controller.extend({
  queryParams: ['page', 'filter',
    {
      showMagnifyingGlass: {
        scope: 'controller',
        as: 'glass'
      }
    }
  ]
});

// routes/articles.js
import Ember from 'ember';

export default Ember.Route.extend({
  resetController(controller, isExiting, transition) {
    if (isExiting) {
      // isExiting would be false if only the route's model was changing
      controller.set('glass', 0);
    }
  }
});
```

Thanks very much :)

**Comment by locks** [comment]
Hi @alexmiddeleer, thanks for your interest! To propose new features you should file an issue on https://github.com/emberjs/rfcs, and if there's enough interest, you can graduate it into a proper RFC. Check the README for an explanation of the process.
Could you move this issue there? Gracias :)

**Comment by alexmiddeleer** [comment]
Thanks Locks, moved to https://github.com/emberjs/rfcs/issues/190
