### ISSUE TITLE
Outdated Observable.addObserver documentation

### ISSUE THREAD

**Issue by ctusch** [emberjs/ember.js#14714]
The [documentation for Observable.addObserver](http://emberjs.com/api/classes/Ember.Observable.html#method_addObserver) seems outdated. The optional _context_ parameter doesn't seem to exist anymore. The callback only has two arguments: _sender_ and _key_. The other 2 (or 3) arguments aren't passed to the callback.

**Comment by cyk** [comment]
@MelSumner resolved as of https://github.com/emberjs/ember.js/pull/14828

**Comment by MelSumner** [comment]
Thank you @cyk !!
