### ISSUE TITLE
Memory leaks with emberjs and Openlayers 3 

### ISSUE THREAD

**Issue by mariowilde** [emberjs/ember.js#14726]
We ran into strange memory leaks when using openlayers 3.20.0 in emberjs application.
Under certain conditions browsers are unable to release the memory of torn down maps, even on a full tab reload.
Please refer to the repository ember-ol3-leak for further information and a minimal example that demonstrates the behavior.
As I am unable to determine the reason for the problems I created issues here and at ol3 ([link to ol3 issue](https://github.com/openlayers/ol3/issues/6267)).

**Comment by pixelhandler** [comment]
What steps have you taken to debug the memory leak?

**Comment by mariowilde** [comment]
Tanks for looking at this and pointing me to the ember community slack.

As we were unable to determine an issue in the implementation of our application, we deconstructed the application to find the minimal configuration that still leads to the memory leak. This minimal example is what you can find under https://github.com/bvu-gmbh/ember-ol3-leak.

Initially we used the different browsers dev tools to track down the root of the problem. Sadly we were unable to get anything out of it, because Firefox turned out to be able to release the seemingly leaked memory eventually (which makes it disappear from heap snapshots), and the IE 11 dev tools are unsuitable to analyze a memory leak, as simply opening them seems to lead to IE leaking memory no matter what page you visit.

What really startled me is that it happens on page reload. Is it even possible that our implementation causes the leak in that case?
It could be a IE 11 bug, but we could not find anything in that direction. The known memory leaks were allegedly fixed by updates.

**Comment by mariowilde** [comment]
Excuse me, wrong button, I didn't mean to close the issue.

**Comment by runspired** [comment]
> The map shows only single vector layer that contains 24000 LineString elements.

Is the "leak" across tabs perhaps just a browser-level inline/parse cache?

**Comment by stefanpenner** [comment]
> What really startled me is that it happens on page reload. Is it even possible that our implementation causes the leak in that case?
> It could be a IE 11 bug, but we could not find anything in that direction. The known memory leaks were allegedly fixed by updates.

If the memory leaks between reloads, and the associated memory is not in a persistent place (localstore, cookie, indexdb etc..). It is without a doubt a browser bug.

**Comment by mariowilde** [comment]
Thank you. I considered that possibility, but was in doubt because Firefox 50 "almost leaks" as well. We actually believed that it also leaked on page reload, because it released the memory only after several reloads when the process had already allocated several 100 megabytes of ram.

**Comment by stefanpenner** [comment]
@mariowilde ya debugging these types of leaks vs a process just keeping memory around because it can is a tad tricky.

That being said, if memory stays around post reload it is not an ember issue, rather a browser issue that may not be solvable from user space.

**Comment by mariowilde** [comment]
@runspired Sorry for the late response, somehow I missed your comment. Admittedly, my knowledge of browser internals is quite poor. If it was just a browser internal cache, do you have a suspicion as to why the caches grow like that? When the same map is put into an ember-less html document, all the memory is released instantly on page reload.

**Comment by stefanpenner** [comment]
This doesn't seem to be a bug in ember so closing this.

That being said Q/A can continue here.

**Comment by mariowilde** [comment]
@runspired 

>  Is the "leak" across tabs perhaps just a browser-level inline/parse cache?

I don't want to bug you, but would you mind explaining that statement? I would really appreciate any hint.
