### ISSUE TITLE
Required input immediately marked invalid in Firefox with Ember 2.10

### ISSUE THREAD

**Issue by galfert** [emberjs/ember.js#14737]
There seems to be a regression in Ember 2.10.0 in regards to required input fields.

In Firefox an input field `{{input value=foo required=true}}` is immediately marked as invalid (showing a red border around the field).

This is not the case in Ember 2.9.0, where the field is only marked as invalid when trying to submit the form with the field being empty.

I created an [Ember Twiddle](https://ember-twiddle.com/c25bf06f16c4ae0ddfe7e5a3f081e881?openFiles=templates.application.hbs%2C) to reproduce it.

**Comment by galfert** [comment]
I'm willing to help fix this issue. Any pointers on where I should focus my search for the reason of this bug?

**Comment by bcardarella** [comment]
We are seeing this same issue

**Comment by bcardarella** [comment]
Has anyone reported this to Mozilla yet? Or do we think this can be worked around in Glimmer?

**Comment by martndemus** [comment]
Note that FireFox's implementation on the value + required attribute is actually correct.

https://www.w3.org/TR/html5/forms.html#dom-input-value-value
> On setting, it must set the element's value to the new value, set the element's dirty value flag to true, invoke the value sanitization algorithm

**Comment by skddc** [comment]
Should be possible to fix in Glimmer, if it's a regression:

> This is not the case in Ember 2.9.0, where the field is only marked as invalid when trying to submit the form with the field being empty.

@martndemus Is validation the same as sanitization there? Dirty value would just mean it changed, whereas the validation should only kick in when either asking for it via the DOM API, or submitting the form afaik.

**Comment by galfert** [comment]
This is just a hunch, but could it be that Glimmer first inserts the input into the DOM and only then sets the value to the bound property? That might trigger Firefox's validation.

**Comment by rwjblue** [comment]
Hmm, this is surprising actually. Can someone double check if the same thing happens with plain JS?

```js
let el = document.createElement('input');
el.setAttribute('type', 'input');
el.setAttribute('required', 'true');
el.setAttribute('value', '');
document.body.appendChild(el);
```

Does this have the same issue?

**Comment by galfert** [comment]
> Does this have the same issue?

No, the input element produced with that snippet doesn't have the same issue.

**Comment by rwjblue** [comment]
OK, so the following is what we are doing internally today:

```js
let el = document.createElement('input');
el.value = '';
el.setAttribute('required', '');
document.body.appendChild(el);
```

This shows the same issues as the twiddle.

However, the following _does_ work properly:

```js
let el = document.createElement('input');
el.setAttribute('value', '');
el.setAttribute('required', '');
document.body.appendChild(el);
```

**Comment by rwjblue** [comment]
AFAICT the only fix for this would be to move to using attributes first, but that requires broader changes (see https://github.com/emberjs/rfcs/pull/314).

**Comment by locks** [comment]
As mentioned by @rwjblue, fixing this has bigger implications that should be addressed by the linked to RFC. That is why I am marking this as wontfix and closing the issue.
Thanks for the discussion everyone! Go comment on the RFC 😁
