### ISSUE TITLE
`runInDebug` isn't available in `meta.js` module initialization

### ISSUE THREAD

**Issue by GavinJoyce** [emberjs/ember.js#14732]
Part of https://github.com/emberjs/ember.js/pull/14723

There's currently a `FIXME` in [`ember-metal/lib/meta.js`](https://github.com/emberjs/ember.js/blob/bbc79f0f80b2ea6f7909d30826856f0854bb6ab3/packages/ember-metal/lib/meta.js#L75):

<img width="794" alt="screen shot 2016-12-18 at 10 16 06" src="https://cloud.githubusercontent.com/assets/2526/21292882/0a42a244-c50b-11e6-98b7-8d72c1405ef9.png">

If we try to use `runInDebug` at that point, it's the default empty function meaning that the code will never run, even if we are in debug mode:

<img width="718" alt="screen shot 2016-12-18 at 10 08 06" src="https://cloud.githubusercontent.com/assets/2526/21292886/42f4f7ea-c50b-11e6-9707-1a2ab4bf7876.png">

In the `Meta` constructor, later in `ember-metal/lib/meta.js`, we can use `runInDebug` as the function in [`ember-debug/lib/index.js`](https://github.com/emberjs/ember.js/blob/530b2666b38aa4733a97965a914d3ac8eff7732c/packages/ember-debug/lib/index.js#L149-L151) has been set:

<img width="713" alt="screen shot 2016-12-18 at 10 08 23" src="https://cloud.githubusercontent.com/assets/2526/21292894/e1f28a10-c50b-11e6-9361-1ed9f901f291.png">

**Comment by GavinJoyce** [comment]
We conditionally require `ember-debug` at the bottom of [`ember-metal/lib/index.js`](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/index.js#L177-L184):

<img width="607" alt="screen shot 2016-12-18 at 10 29 10" src="https://cloud.githubusercontent.com/assets/2526/21292919/d5a0fdcc-c50c-11e6-8f06-e20e49746b03.png">

**Comment by GavinJoyce** [comment]
I can work around this issue in https://github.com/emberjs/ember.js/pull/14723 with:

<img width="888" alt="screen shot 2016-12-18 at 11 00 07" src="https://cloud.githubusercontent.com/assets/2526/21293063/33729c68-c511-11e6-8e16-5e5ddd6bcee3.png">

**Comment by rwjblue** [comment]
The issue here is basically that you are using `runInDebug` in closure scope before `ember-debug` version has been setup.

See comments around https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/index.js#L180-L184 for an example of where this has bit us in the past.

**Comment by rwjblue** [comment]
The solution is to refactor the build so that `lib/packages/ember-metal/lib/debug.js` is actually replaced completely between `ember.debug.js` and `ember.prod.js` (instead of conditionally including `lib/packages/ember-debug/` based on prod/non-prod).

@krisselden and I have talked about this for a while, but haven't had the time to shove it over the finish line...

**Comment by mixonic** [comment]
I believe this is superseded by https://github.com/emberjs/ember.js/pull/15043. Please re-open if I've missed something, thank you!
