### ISSUE TITLE
Glimmer 2 does not read properties on functions

### ISSUE THREAD

**Issue by kturney** [emberjs/ember.js#14739]
We encountered this while upgrading a project that uses https://github.com/LocusEnergy/ember-d3-helpers to Ember 2.10 and trying to bind to properties on D3 scales.

Twiddle: https://ember-twiddle.com/8bd17be80e30f6149bcdf644f3d1f68d?openFiles=templates.application.hbs%2C

If you change the Ember version in the twiddle to 2.9, the property renders as expected.

pr with failing test: https://github.com/emberjs/ember.js/pull/14729

**Comment by chancancode** [comment]
I think I know how to fix this, but I am on vacation. If anyone wants to look into it there are a few places where we do `if (typeof foo === "object")` that should include functions as well. I believe it probably needs both a glimmer fix and an ember fix to cover all the cases.

**Comment by chancancode** [comment]
PrimitiveReference and such

**Comment by Serabe** [comment]
@locks, any update on this?

**Comment by mixonic** [comment]
afaict this is still an issue.

**Comment by locks** [comment]
This should be fixed by https://github.com/emberjs/ember.js/pull/15535.
