### ISSUE TITLE
`makeArray` does not work as commented

### ISSUE THREAD

**Issue by pswai** [emberjs/ember.js#14741]
In `make-array`, it is commented as followed:

```javascript
 let controller = Ember.ArrayProxy.create({ content: [] });

 Ember.makeArray(controller) === controller;  // true
```

However it is not true. It seems `Ember.makeArray(controller)` is using `Array.isArray` now, which does not handle array-like object.

**Comment by rwjblue** [comment]
The documentation should be updated to reflect that an array proxy has no special behavior here.
