### ISSUE TITLE
Decamelize behaves incorrectly with numbers

### ISSUE THREAD

**Issue by JulianLeviston** [emberjs/ember.js#14743]
Observe:

    var x = 'grammar1And2Average'
    Ember.String.decamelize(x)
    > "grammar1_and2_average"

and 

    var x = 'grammar_1And_2Average'
    Ember.String.decamelize(x)
    > "grammar_1_and_2_average"

Ember's decamelize uses the following regex (https://github.com/emberjs/ember.js/blob/v2.10.0/packages/ember-runtime/lib/system/string.js#L71): (/([a-z\d])([A-Z])/g)

It should probably have an additional `\d` on the end:

    var x = 'grammar1And2Average'
    var STRING_DECAMELIZE_REGEXP = (/([a-z\d])([A-Z\d])/g)
    x.replace(STRING_DECAMELIZE_REGEXP, '$1_$2').toLowerCase();
    > "grammar_1_and_2_average"

Actually, no, that would then not work with this, either:

    var x = "readingComp1To4Attempted"
    x.replace(STRING_DECAMELIZE_REGEXP, '$1_$2').toLowerCase();
    "reading_comp_1to_4attempted"

**Comment by rwjblue** [comment]
At this point it is quite unlikely that we will be able to change these functions without the changes themselves being a breaking change.

Sorry for taking so long in getting back to this issue 😢
