### ISSUE TITLE
Deprecate `Ember.K`

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#14746]
Now that [the RFC to deprecate `Ember.K`](https://github.com/emberjs/rfcs/pull/178) has been merged, this is a pretty simple task to implement, and one that is perfect for a new contributor to perform since it's not technically complex and it balanced between documentation and implementation.

The tasks to perform are divided in a couple repositories:

- [x] Read [the RFC](https://github.com/emberjs/rfcs/pull/178), to understand the motivation and the outcome.
- [x] Amend the deprecations guide in the [website reporsitory](https://github.com/emberjs/website/blob/master/source/deprecations/v2.x.html.md).
  Information of the deprecation: 
  **id**: `ember-metal.ember-k`
  **until**: 3.0.0
  **explanation**:
  The entry must explain how to automatically remove usages of `Ember.K` in your codebase using [ember-watson](https://github.com/abuiles/ember-watson).
  It must also explain that there is two options on the command: `--empty` and `--return-this`
  and that while the second is 100% compatible, the first is probably what they want. Check the 
  addendum on the RFC for more information.
- [x] Create a PR in Ember.js itselt deprecating `Ember.K`. 
  As stated in the previous point, the id of the deprecation must be `ember-metal.ember-k` and the
  `url` must point to the entry in the deprecation guide you've just created.
  If you are not familiar with how deprecations are made, this is a [good example](https://github.com/emberjs/ember.js/blob/9cd0d390dfe6fa2bb09736e765859458f3b8b35d/packages/ember-glimmer/lib/utils/string.js#L23-L31) of how the **id**, **until** and **url** are used

If anyone wants to go and deprecate this, I can provide support or guidance on the process. Feel free to ping me in Slack on here anytime.

**Comment by sarupbanskota** [comment]
I'd like to take this one up; I'll look at it in 3 days :-)

**Comment by givanse** [comment]
PRs up, please let me know what changes should I make.

https://github.com/emberjs/ember.js/pull/14751
https://github.com/emberjs/website/pull/2774

**Comment by rwjblue** [comment]
I believe this is done, thanks to all those who helped out!
