### ISSUE TITLE
JSONApiAdapter sends all fields for PATCH

### ISSUE THREAD

**Issue by wayne-o** [emberjs/ember.js#14744]
I'm not sure if this is where I should be reporting this so appologies if I'm incorrect.

I've began using the Json Api Adapter in my app and have a compliant backend running and it's all smooth.

Only issue I have found is that when I update a property on a model and then `.save` it - i see that all of the properties on that model are sent to the server as a PATCH request. In my understanding this should be limited to the properties that have changed and require an update?

**Comment by btecu** [comment]
Here https://github.com/emberjs/data

**Comment by wayne-o** [comment]
Ah ok I'll close this and open a new one there
