### ISSUE TITLE
Components with a computed tagName throw an error when trying to render

### ISSUE THREAD

**Issue by danwenzel** [emberjs/ember.js#14749]
Having a computed property for `tagName` seems to break in recent Ember versions (2.8 and later).  Something like: 

```
export default Ember.Component.extend({
  isButton: true,

  tagName: Ember.computed('isButton', function () {
    return this.get('isButton') ? 'button' : 'a';
  }),
});
```

throws:

![image](https://cloud.githubusercontent.com/assets/11724146/21437839/c0c96ac8-c84b-11e6-8455-d23ed793023d.png)

Demonstrated by this ember-twiddle:

https://ember-twiddle.com/d54856b5f03e13bd2ccb66f07efc093b?openFiles=templates.application.hbs%2Ctemplates.components.my-component.hbs

Digging in, it looks like the `ComputedProperty` itself is being passed to the render instead of the computed string value for the tag name.

**Comment by GavinJoyce** [comment]
<img width="636" alt="screen shot 2016-12-22 at 19 31 47" src="https://cloud.githubusercontent.com/assets/2526/21437946/95871a8a-c87e-11e6-8ae6-cd7b0fba2b4c.png">

**Comment by GavinJoyce** [comment]
<img width="880" alt="screen shot 2016-12-22 at 21 17 06" src="https://cloud.githubusercontent.com/assets/2526/21440676/0ca6d9cc-c88c-11e6-946e-d7832b66c9b9.png">
<img width="884" alt="screen shot 2016-12-22 at 21 17 17" src="https://cloud.githubusercontent.com/assets/2526/21440678/0edb6c6c-c88c-11e6-8ba6-02edeeed4342.png">

https://github.com/emberjs/ember.js/pull/13145/files#r56779944

**Comment by GavinJoyce** [comment]
It was deprecated in 2014: https://github.com/emberjs/ember.js/pull/9905

TODO:

 * [ ] Add an assertion stating that `using a computed property to define tagName is not supported`

**Comment by danwenzel** [comment]
I see... good to know 😄    Luckily we only do this once in our app, and it can easily be refactored.  Thanks!

**Comment by rwjblue** [comment]
Thanks for tracking that down @GavinJoyce!
