### ISSUE TITLE
HTMLBars.compile not working in Ember 2.10

### ISSUE THREAD

**Issue by ahoyahoy** [emberjs/ember.js#14758]
In Ember **2.9.0**
`HTMLBars.compile(stringTemplate)`
return
```
{
  arity: 0,
  isMethod: false,
  isTop, true,
  meta: Object,
  raw: Object,
  render: (self, env, options, blockArguments)
}
```

but in Ember **^2.10.0**
`HTMLBars.compile(stringTemplate)`
return
```
{
  id: "client-0",
  meta: Object
}
```

Therefore I cannot make new component from string template like:

```
Ember.Component.extend({
  template: HTMLBars.compile(stringTemplate),
  container
}).create().appendTo(target)

```

**Comment by locks** [comment]
In Ember 2.10 we [switched to the Glimmer rendering engine](http://emberjs.com/blog/2016/11/30/ember-2-10-released.html#toc_changes-in-ember-js-2-10). Can you try https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile instead and see if you have a problem?

**Comment by ahoyahoy** [comment]
not working outside tests with ember-cli?

in package.js `"ember-cli-htmlbars-inline-precompile": "0.3.6",`

in component:
```
import hbs from 'htmlbars-inline-precompile';

console.log(hbs)
  -> hbs is not defined

console.log(hbs(stringTemplate))
  -> Build error: hbs should be invoked with a single argument: the template string

```

**Comment by boris-petrov** [comment]
I use something like:

```coffeescript
owner = Ember.getOwner(this)

component = Ember.Component.create
  layout: Ember.HTMLBars.compile(template)
  renderer: owner.lookup('renderer:-dom')
Ember.setOwner(component, owner)

component.setProperties({ a: 1, b: 2 })

component.appendTo(destination)
```

And this seems to work even in Ember 2.10. Not sure for how much more though.

**Comment by levint** [comment]
Shouldn't it be `Ember.HTMLBars.compile`? I'm on `2.11.0` (upgraded from `2.10.0`) and it has been working for me.

**Comment by mixonic** [comment]
@ahoyahoy Creating a component with a layout appears to work: http://jsbin.com/revayusumo/edit?html,js,output

Passing a `template` property to a component is not correct, you want to pass `layout`.

I'm going to close this, but feel free to re-open with more details if I have missed something.
