### ISSUE TITLE
[Glimmer] Ember 2.10: SVG <use> elements with dynamic `xlink:href` attribute fail to render

### ISSUE THREAD

**Issue by BrianSipple** [emberjs/ember.js#14752]
Replicated [here in this Twiddle](https://ember-twiddle.com/29d081c431ef919e814c31e5b7def2ad?fileTreeShown=false&numColumns=2&openFiles=twiddle.json%2Csvg-use-test.template.hbs).

Eerily similar to #14323.

When I have an `<svg>` with an inner `<use>` element that's attempting to render content from a separate SVG `<symbol>` (either from the same document, or from somewhere else in the file system), the content won't render when the `<use>`'s `xlink:href` attribute is being computed dynamically. 

As shown in the demo, though, hardcoding the same value for the attribute works just fine.

Even more curiously: inspecting the DOM shows no difference in the final markup. This is directly from the Twiddle:
<img width="298" alt="screen shot 2016-12-23 at 7 14 32 am" src="https://cloud.githubusercontent.com/assets/5483853/21456798/9872d7d2-c8df-11e6-9a4b-c75974d6b982.png">

No errors are thrown in the console, either, so my only hunch (and I'll admit to not being very familiar with Glimmer's internals) is that something is fundamentally different about the state of the DOM when the markup with a dynamically-computed attribute is being generated.

**Comment by nightire** [comment]
@BrianSipple 

You should write like this:

```htmlbars
<svg><use xlink:href="{{filePath}}"></use></svg>
```

**Comment by BrianSipple** [comment]
@nightire You're correct -- that does work! 

However, this wasn't necessary even just going back to 2.9, and I don't see any documentation about quotes being necessary for bound attributes (In fact, [our current documentation suggests the opposite](https://guides.emberjs.com/v2.10.0/templates/binding-element-attributes/)).

**Comment by rwjblue** [comment]
I do think that using quotes is appropriate here, but I'm not 100% sure why its required in this case.

Since we have a valid (and ergonomic) solution (and < 2.10 is long unsupported), I'm going to go ahead and close this out...
