### ISSUE TITLE
Ember.run.schedule('afterRender', ...) occurs in the next run loop instead of current

### ISSUE THREAD

**Issue by kybishop** [emberjs/ember.js#14773]
This is specific to Ember 2.9 and lower.

https://ember-twiddle.com/3ca76407c810fb0c6b066c638cc2e1e8?openFiles=templates.application.hbs%2Ctemplates.components.service-mutating-component.hbs

Note the order of console.log statements: `willDestroyElement` occurs before the function scheduled for `afterRender`.

Switching the dependency to Ember 2.10 resolves the issue.

**Comment by pixelhandler** [comment]
@kybishop I took a look at the example and noticed the order of log statements as you indicated.

I'm curious about what your use case? can you describe what you're trying to accomplish regarding order of scheduling when using `afterRender`. Also are you able to upgrade to 2.10 ?

**Comment by kybishop** [comment]
Hey @pixelhandler. The real issue is lack of consistency between both Ember versions and documentation. These differences made debugging https://github.com/html-next/flexi/issues/101 unnecessarily confusing. It is also unclear if the difference in run loop schedule is intentional (hence the bug report)

1. Ember 2.10 schedules tasks in the CURRENT run loop
2. Ember <= 2.9 schedules tasks in the NEXT run loop
3. [The API](https://github.com/emberjs/ember.js/blob/v2.10.0/packages/ember-metal/lib/run_loop.js#L234) suggests scheduled tasks will be run in the NEXT run loop
4. Editing [the example](https://guides.emberjs.com/v2.9.0/applications/run-loop/#toc_an-example-of-the-internals) in the guides shows scheduled tasks being run in the CURRENT run loop (regardless of guide version). Example edit below:

```javascript
Ember.run.schedule('actions', function task1(){
    console.log('processing: task #1');
    // add this line and note it is scheduled to run immediately after the current function
    // as opposed to on the NEXT run loop.
    Ember.run.schedule('actions', function custom() { console.log('custom') });
  });
``

We can always act defensively when dealing with run loop order issues, but it would make life a lot easier if the run loop was consistent between Ember versions (and if the docs noted the difference/were consistent with the ember version's behavior)

**Comment by krisselden** [comment]
@kybishop I likely could explain this, but your semantics are confusing me.  The run loop hasn't changed, the only thing really that has changed is didInsertElement is more like afterRender, in that it flushes immediately after rendering.  I would like to actually understand the complaint, depending on timing like this is a bit dubious.

I don't fully understand what you mean but CURRENT and NEXT and what is the task in your example.

**Comment by kybishop** [comment]
Hey @krisselden .

By CURRENT, I mean the current iteration of all queues in the run loop; `["sync", "actions", "routerTransitions", "render", "afterRender", "destroy"]`. By NEXT, I mean the next iteration of all the queues. I'm hoping the quick rundown below clears up what I mean by current and next.

In Ember 2.10:
1. From a function executing in the render queue, schedule a function to run with Ember.run.schedule('afterRender'...)
2. The run loop eventually finishes all tasks in the render queue, then moves on to afterRender
3. Our function scheduled in (1.) is eventually run whilst emptying the tasks from the afterRender queue

In Ember <= 2.9:
1. From a function executing in the render queue, schedule a function to run with Ember.run.schedule('afterRender'...)
2. The run loop eventually finishes all tasks in the render queue, then moves on to afterRender
3. Our function scheduled in (1.) is NOT run, it is instead schedule in the queues for the *next* iteration of all the queues. This means we first empty the afterRender queue, then the destroy queue, etc. until we arrive back in the afterRender queue. In effect, we have schedule our task for the next iteration of all run loop queues.

The task just show what to edit in [the guide's example](https://guides.emberjs.com/v2.9.0/applications/run-loop/#toc_an-example-of-the-internals) to see that the example executes scheduled tasks in the current run loop iteration (regardless of which ember version the guide is set to).

**Comment by krisselden** [comment]
The above depends on when you are scheduling 'afterRender' and your description of this isn't accurate, there has been no change in the run loop behavior, I think you are seeing the effect of some other interaction and when the afterRender is scheduled.

**Comment by kybishop** [comment]
@krisselden just going off what I see in the provided twiddle when switching between Ember versions, apologies for not describing what I'm seeing appropriately/accurately.

It sounds like this is considered a non-issue, and we've dealt with it as needed in flexi, so I'll close the issue.
