### ISSUE TITLE
Use TravisCI JWT addon to encrypt Sauce Labs credentials

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#14789]
instead of https://github.com/emberjs/ember.js/blob/master/.travis.yml#L39-L40

see https://docs.travis-ci.com/user/jwt

**Comment by pixelhandler** [comment]
@Turbo87 do you know who would be the primary person to make this change, my best guess is that it involves using the proper credentials for Sauce Labs. cc\ @rwjblue 

Maybe this one needs an assignee?

**Comment by Turbo87** [comment]
@pixelhandler I think we will need to cycle the current SauceLabs credentials and then use the new ones for the `travis` command line call to encrypt them. This needs to be done by someone that's able to log into SauceLabs and has write access to the `ember.js` repo.

**Comment by rwjblue** [comment]
Why? We intentionally left the clear text credentials in .travis.yml. If we encrypt then, we cannot run SL tests on PR's.

**Comment by Turbo87** [comment]
@rwjblue please read the link above. that is precisely what this feature is all about.

**Comment by Serabe** [comment]
Any update on this?

**Comment by rwjblue** [comment]
FWIW, just did some digging (to see about leveraging JWT during the swap to browserstack being worked on in https://github.com/emberjs/ember.js/pull/16047) and found https://github.com/travis-ci/travis-scheduler/pull/81#issuecomment-324352230 which indicates that JWT addon will be deprecated and removed in the future (and therefore the Travis folks wouldn't land this PR adding browserstack JWT support).

**Comment by bekzod** [comment]
is this still valid since sauce no longer used ?
