### ISSUE TITLE
Missing API documentation for Ember.Templates.helpers.html#method_yield

### ISSUE THREAD

**Issue by callovarne** [emberjs/ember.js#14797]
The docs for `{{yield}}` have gone missing. I'm not having much luck finding it in the source either. API change?

The page appears to have existed here at some point: http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_yield

Dead links:
* http://emberjs.com/api/classes/Ember.View.html#toc_layouts

The guides are thin on information, too, and don't link to the API page. I was looking for specifics on `{{yield to="inverse"}}`.

**Comment by locks** [comment]
Relatedly, we removed the "Layouts" section when moving the documentation to the Ember.Component class: https://github.com/emberjs/ember.js/pull/14765.

**Comment by mixonic** [comment]
Oh gee, 😬 there appear to be several issues here:

* The docs for yield are not appearing
* There are dead links in the Ember.View ToC
* The guides have no information on `{{yield to="inverse"}}`. I think this API should 100% be mentioned in the API docs, I'll defer to the learning team on if they want to present it in the guides. Regardless that would be an issue in the guides repo, lets keep it focused to API docs here. So do the API docs document this?
* The "Layouts" section was dropped. I'm not at all sure what this has to do this this issue.

**Comment by yogipatel** [comment]
@callovarne @mixonic I looked into this a bit, but I'm very much a beginner in Ember.js land. AFACIT, yield hasn't had documentation. I looked at 2.10, 2.7, even 2.0; the Ember.Templates.helpers.html#method_yield link has probably been dead for a while. Perhaps it lived somewhere in HTMLBars docs?

As @locks mentioned, the broken link is now in Ember.Component here: https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/component.js#L432

I'm probably not at the level where I should be doc'ing yield, but if you want a hand digging deeper, I'd be happy to help.

**Comment by elucid** [comment]
My best guess is that the yield docs disappeared here: https://github.com/emberjs/ember.js/commit/816f252580e0e83d7453d6284a0741e99747fee3

**Comment by yogipatel** [comment]
@elucid Nice find. Here it is: https://github.com/emberjs/ember.js/commit/816f252580e0e83d7453d6284a0741e99747fee3#diff-6de598048f2facdff459c26b8d8746da

Question is, where is it implemented / do the docs belong now?

**Comment by mattmarcum** [comment]
I think the problem is that `yield` is now in the glimmer package itself - `yield` is a glimmer statement: https://github.com/tildeio/glimmer/blob/82a2ab8400b54f118e2944f3cf6fed24dd8bd40c/packages/%40glimmer/compiler/lib/javascript-compiler.ts#L287

**Comment by mattmarcum** [comment]
Since the `yield` statement comes right before the `debugger` statement in glimmer, I think putting a yuidoc block for `yield` in the packages/ember-glimmer/lib/index.js@114 right before the yuidoc for debugger makes sense:  https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/index.js#L114

**Comment by elucid** [comment]
Makes sense to me. @mixonic thoughts?

**Comment by Serabe** [comment]
This has been fixed for a while. Thank you all!
