### ISSUE TITLE
Issue in the acceptance test with computed an object will be created in the runtime

### ISSUE THREAD

**Issue by jabraok** [emberjs/ember.js#14795]
Hi,

In my case, even though the code works fine, the acceptance test always throw the exception 

Here is scenario:

In the component, 

```
isClosed: Ember.computed.alias("preferencesService.data")
```

The code of preferencesService

```
export default Ember.Service.extend({

async init() {
     const data = await someAsyncFetcher();

     //Setting this causes an error
     this.set("data", data);
  },
});
```

Error message of acceptance test
```
Promise rejected during can add order item manually: Cannot read property 'dispatchEvent' of undefined
```

I think, the `preferencesService.data` object is re-set in the runtime is cause an error.
Is there any solution to solve it?

Thanks

**Comment by Serabe** [comment]
Can you please provide a reproduction in ember twiddle or in a repo? Thank you!

**Comment by Serabe** [comment]
@jabraok ping

**Comment by jabraok** [comment]
@Serabe,
I am so sorry. It's kind of too old stuff. I will close this issue.
Thanks for your help
