### ISSUE TITLE
Ember.computed.intersect doesn't work with DS.RecordArray

### ISSUE THREAD

**Issue by mvuckovic** [emberjs/ember.js#14798]
I've hit into this issue while trying to intersect (DS records) movie.roles and department.roles in application I'm developing. 

It seems that intersect uses for-loop with bracket notation to get array elements which RecordArray doesn't support.
It will kinda work if the last array is RecordArray and others are NativeArray or if you call toArray() on all instances of RecordArray first.

Twiddle here: https://ember-twiddle.com/e6dd46466a61e25c735adbe17fad72ad

Thanks!

**Comment by locks** [comment]
Marking this as inactive due to lack of discussion. Thanks for submitting the report!
