### ISSUE TITLE
Memory leak with Ember.ObjectProxy

### ISSUE THREAD

**Issue by denisovlev** [emberjs/ember.js#14802]
For example I use `Ember.ObjectProxy` to wrap model and then pass it into template for render. I don't know all the properties of the model that this proxy has subscribed to. If I want to remove the proxy later, the model retains references to the proxy in listeners and it causes memory leak.
There is no way to unsubscribe all the listeners that trigger change on a given target. It would be very nice to have such functionality.

**Comment by denisovlev** [comment]
Here is an example, it is leaking memory
http://jsfiddle.net/501w8c3a/18/

I create disposable proxies and model retains references to them. The logical step would be to unsubscribe the old proxy when I create the new one. The problem is that I cannot simply unsubscribe **all** the listeners for the target, only if I know **exactly what properties are being observed**.

**Comment by mixonic** [comment]
@denisovlev is this still an issue in newer versions of Ember? We've started using weakmaps, which would handle this case, in more places when they are available however I'm unsure anything has been done about this case.

Please test in 2.12 or 2.13?

**Comment by les2** [comment]
@denisnazarov ported your jsfiddle to an ember twiddle: https://ember-twiddle.com/5b083584c933e4c887fc1f0f7360e6df?openFiles=templates.application.hbs%2C (will allow easily swapping out the ember version)

**Comment by denisovlev** [comment]
Thank you, @les2 

@mixonic From what I see in the new twiddle is that heap is constantly growing, hence memory is still leaking.

**Comment by thomaswrenn** [comment]
+1 I'm on 2.4 and it seems we're getting the same issue.

**Comment by stefanpenner** [comment]
I don't believe this is a bug, proxies need to be destroyed explicitly.

```
 updateProxy() {
    this.incrementProperty('updateCount');
  	var model = this.get('model');
    if (model != null) {
      var proxy = Ember.ObjectProxy.create({content: model});
      let oldProxy = this.get('oldProxy');  // <--
      if (oldProxy) { oldProxy.destroy(); } // <-- we must cleanup
      this.set('modelProxy', proxy);
    }
    Ember.run.later(this, this.updateProxy, 4);
  },
```

**Comment by stefanpenner** [comment]
I'm going to close, but we can keep chatting about it and other approaches here.

I will gladly reopen if there is a proposal to implement differently, or if It turns out I am mistaken.
