### ISSUE TITLE
DOM order of rendering updated array by {{each}}

### ISSUE THREAD

**Issue by JennieJi** [emberjs/ember.js#14814]
Twiddle DEMO: https://ember-twiddle.com/3da809193fd5a5f9a032a9603868f151

This is an interesting case found recently. I believe it appears since 2.9 or 2.10.    
This case happens when I render an array with {{each}} and then update part of it. Then then rendering of this array will not follow its index any more, it will append the updated item to the end of this {{each}} block.

**Comment by GavinJoyce** [comment]
^ seems to have been introduced in 2.10

**Comment by krisselden** [comment]
I'm guessing it has something to do with the key being falsy and/or  falsy + the collision key generation.

**Comment by krisselden** [comment]
If I make the default value something that doesn't coerce to false then it works https://ember-twiddle.com/64e6925cbc56ecc82f5aa94e399351a6

**Comment by JennieJi** [comment]
@krisselden Lol, this is interesting. Thank you, at least it can be easily hacked right now.

**Comment by rwjblue** [comment]
You can also use `{{#each foo key="@index" as |bar|}}` to prevent the issue

**Comment by pixelhandler** [comment]
@sclatter as @rwjblue points out using a `key` works, I forked your twiddle as an example, https://ember-twiddle.com/ef8d4a820f6c587edde512438a7339e1?openFiles=templates.application.hbs%2C

**Comment by sclatter** [comment]
@pixelhandler I think you meant to cc @JennieJi ? ^

**Comment by JennieJi** [comment]
@sclatter @pixelhandler @rwjblue  thank you, it works very well.

**Comment by krisselden** [comment]
@rwjblue using `@index` also causes no falsy keys. There is definitely something off about `""` string key, I'm glad there are workarounds but this is still a bug.
