### ISSUE TITLE
"attributeBindings" is not documented on Ember.Component

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#14815]
I've been searching the docs for the `attributeBindings` property on `Ember.Component` but couldn't find any documentation on it. I just discovered http://emberjs.com/api/classes/Ember.View.html#toc_html-attributes, but that is not linked anywhere in the `Ember.Component` docs, so it is a little hard to find.

**Comment by locks** [comment]
https://github.com/emberjs/ember.js/pull/14765 fixes it :]

**Comment by Turbo87** [comment]
uuuhhhh, awesome! I'm assuming this will be uploaded together with the docs for the v2.11 release?
