### ISSUE TITLE
Update documentation with more information about setting rootURL

### ISSUE THREAD

**Issue by mtayl0r** [emberjs/ember.js#14812]
At the url below, the information provided for updating the rootURL is incomplete. It should at least mention setting the rootURL in config/environment.js to allow setting the correct {{rootURL}} in the index.html generated at build (for example), if that is the desired behavoir.

https://guides.emberjs.com/v2.10.0/configuring-ember/embedding-applications/

**Comment by locks** [comment]
Thanks for pointing it out, I have moved this issue to the Guides repository.
