### ISSUE TITLE
[DOC] Ember.Templates.helpers code examples not rendering filename correctly

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#14834]
I was under the impression that code examples with filenames were rendered "differently", but http://emberjs.com/api/classes/Ember.Templates.helpers.html#toc_specifying-a-target seems to not follow that rule.

/cc @locks @sclatter

**Comment by pixelhandler** [comment]
@locks should this be closed as #14841 was merged?

**Comment by locks** [comment]
Thanks @pixelhandler
