### ISSUE TITLE
Lookups in non-injected objects

### ISSUE THREAD

**Issue by ctusch** [emberjs/ember.js#14831]
I've repeatedly stumbled across the following problem:

If you create an object using `create` (instead of `ApplicationInstance.lookup`) you can't use `Ember.inject` inside of it. Also you can't use `Ember.getOwner(this)` within that object in order to use `lookup`.

I understand the technical reason why this is so and I also understand that I can set the owner of the object. But I don't think this is a satisfying "workaround".

My use case is as follows. I have a dashboard which can contain several widgets. The dashboard configuration (along with the widgets' class name) is stored in a database. Now the widget library can be extended by 3rd party developers by writing an Ember add-on. This is not important to the topic but the main point is those are mostly inexperienced developers.

The widgets can hold custom objects. The classes are extending `Ember.Object`. For those custom objects to use services they need to have an owner. Of course when creating such an object myself I will think of passing an owner most of the time. But I can't expect inexperienced developers to do so. If they forget or don't know about it the resulting error message won't help them much.

Another possibility would be to `register` all custom classes with the `Application` and then use `lookup` to create the instance. But 3rd party developers could also add custom classes and this is an advanced concept to explain.

I don't feel that creating custom classes is an "advanced technique" and should come with such limitations. The solutions seem very daring to a beginner. It puts the burden on the developer.

Sadly I can't really come up with a better solution so I guess this issue will get closed soon. If I'm not mistaken assigning a default owner wouldn't work because with engines you wouldn't know which instance is the right one.

But my hope is that some of you Ember developers might understand how unsatisfying the current situation is and maybe you can think of something that might be better.

Thank you for reading!

**Comment by Serabe** [comment]
Hello, @ctusch:

I understand your problem given that I had to deal with similar situations in the past.

I'm closing this issue by [our Triage Policy](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy) given it is a feature request, inviting you to follow [this process](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature) for it.

Thank you!
