### ISSUE TITLE
[Tutorial] templates/application.hbs should not contain a full HTML page

### ISSUE THREAD

**Issue by jmleroy** [emberjs/ember.js#14837]
In the tutorial, please mention that `templates/application.hbs` is itself included in a full HTML page (`templates/index.html`). The current text implies that `application.hbs` replaces the default page. 

When `templates/application.hbs` contains a full HTML page (with doctype, `<html>` and `<body>` tags), the page rendered is blank.

**Comment by locks** [comment]
Thanks for the report! For next time, we track Guides issues [at their own repository](https://github.com/emberjs/guides).
For the next release (2.11), we have changed how `application.hbs` and `ember-welcome-page` work. We now generate an `application.hbs` template by default that contains a `{{welcome-page}}`, which we hope helps users.
