### ISSUE TITLE
arrayContentDidChange will often call objectAt(0) and objectAt(len - 1)

### ISSUE THREAD

**Issue by hjdivad** [emberjs/ember.js#14843]
When subclassing `MutableArray` it is surprising that any mutation can trigger `objectAt(0)` and `objectAt(len -1)`.  This happens because of the checks [here](https://github.com/emberjs/ember.js/blob/03b9dbc21e1eef88bc5a080dbb500547fe6d55f7/packages/ember-runtime/lib/mixins/array.js#L143-L156) for triggering change events for `firstObject` and `lastObject`.

This causes some difficulties when dematerializing records in Ember Data, because removing unloaded records from relationships, which is done asynchronously, would cause other records to be rematerialized because the materialization is lazy and the records are retrieved for the sake of this check.

This was reported in #5379 which was never fixed, but was closed in favour of a more limited problem in #5591 which *was* fixed in #14493.

One possible solution is to trigger changes for `firstObject` and `lastObject` only based on the indices of deletions and additions.  This will mean that change events will be triggered even in the case of `[a,a,b].removeAt(0);` which is not the case today.

cc @igorT

**Comment by pixelhandler** [comment]
@hjdivad just curious do you know if anyone has a PR with a failing test on this issue?

**Comment by hjdivad** [comment]
@pixelhandler #15110 

https://github.com/emberjs/ember.js/pull/15110/commits/8b851162583963832e6f6662415adbe9ee4341a2  updates a test to illustrate

https://github.com/emberjs/ember.js/pull/15110/commits/dabcbc29ca605490f74f220c470d1d339c71d7fb illustrates the suggested fix

**Comment by mmun** [comment]
I like the proposed solution.

**Comment by bekzod** [comment]
I think this is fixed in https://github.com/emberjs/ember.js/pull/15510 no ?
