### ISSUE TITLE
[DOC] Ember Router - there is no documentation for any method

### ISSUE THREAD

**Issue by tniezurawski** [emberjs/ember.js#14847]
URL: http://emberjs.com/api/classes/Ember.Router.html

Scenario:
1. Go to the URL above
2. Click on any of methods
![Alt text](https://monosnap.com/file/sBXEHqaIaMAg2hzhpIx8yEWvvMYvpZ.png)
3. See - there is nothing there
![Alt text](https://monosnap.com/file/gvLsQ33FBHQ1vqtwVfuA7vF8uIbL9g.png)

**Comment by locks** [comment]
Thanks for reporting, this is being tracked at https://github.com/emberjs/website/issues/2785 :)
