### ISSUE TITLE
computed using index of array causes error when using removeAt

### ISSUE THREAD

**Issue by craigbilner** [emberjs/ember.js#14846]
Recreated in this [twiddle](https://ember-twiddle.com/f2adfa3225366a4703bf87d309f519b4), if you click **click to add** then click **click to remove** you'll get an assertion error.

``Assertion Failed: You must use Ember.set() to set the `0` property``

This is because it's using JS splice to remove the object, which fires the mandatory setter on the array's `0` property when it's being replaced with the object in position 1.

`Ember.computed('someArray.0.someProp'`... applies the watcher and `someArray` now has a mandatory `getter` and `setter` on it's `0` property.

There may be some benefits to applying mandatory setters to array positions rather than just the objects at that position but I can't see them. If there are none, perhaps mandatory setters shouldn't be set on `Arrays`? In the twiddle the underlying object property still has the setter applied and when that object has been removed the computed is no longer fired. As an aside I don't know if the computed should actually persist and be re-applied to the new object at position 0?

**Comment by locks** [comment]
Hi @craigbilner, `someArray.0.someProp` isn't actually valid syntax, it just happens to sometimes work. I'm not sure what you're trying to observe in the Twiddle, you just want to know if the first item in an array changed?

**Comment by craigbilner** [comment]
Thanks @locks. The twiddle is just to demonstrate the issue. You can use `firstObject` to avoid the error. I suppose that's what I was getting at with not adding the mandatory setters to arrays. Perhaps if it's actually **invalid** it should throw much earlier?

**Comment by mixonic** [comment]
😬 The correct thing is definitely `firstObject`. Using `0` in a path should not be documented anywhere.

Making this assert better seems very tricky.

**Comment by craigbilner** [comment]
@mixonic at the point the mandatory setter is applied the code knows it's being applied to an array's index. It could either fail silently or throw?

**Comment by pixelhandler** [comment]
@craigbilner @locks @mixonic is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
