### ISSUE TITLE
`mainContext` is undefined in ember-environment/lib/global.js

### ISSUE THREAD

**Issue by zoltan-nz** [emberjs/ember.js#14859]
After the ESLint warning cleanup the `mainContext` is `undefined` and brake the `ember-template-compiler.js` compilation in grunt environment.

Previous conversation about this issue:
https://github.com/emberjs/ember.js/commit/e24e403656b9de62d55b1a3111e4eb309276d4b8#diff-5b2ea89606fd2097e9e17d66ae54ed51L2

Opened issue in `grunt-ember-templates` repo: https://github.com/dgeb/grunt-ember-templates/issues/94

cc @Turbo87 @andyhot

**Comment by mixonic** [comment]
@zoltan-nz is this issue still valid?

**Comment by rwjblue** [comment]
No it was cleaned up in a followup pr
