### ISSUE TITLE
[Performance] ember-utils assign should expose Object.assign or polyfill

### ISSUE THREAD

**Issue by mateuspv** [emberjs/ember.js#14855]
Hello, 
Emberjs has a `assign` method that basicly polyfill's ES6 Object.assign:
https://github.com/emberjs/ember.js/blob/master/packages/ember-utils/lib/assign.js

`Ember.assign` is defined as `Object.assign`(if existent) or the `assign`  polyfill's(above).
https://github.com/emberjs/ember.js/blob/master/packages/ember/lib/index.js#L25

Many internal packages import `assign` function directly from ember-utils, the **native** implementation(when existent) is never used internally.

Ideia: `ember-utils/lib/assign.js` should exposes 2 functions
```js
export function assign(original) {
  // polyfill implementation
}

export default Object.assign || assign;
```
So we can import `assign` polyfill  and test it properly, `Object.assign` will be used internally through ember-utils `assign`.

Let me know what you guys think about it (y)

**Comment by rwjblue** [comment]
@mateuspv - I think the proposed solution sounds good, I'd love a PR for it!  When we get the PR, we should do some benchmarks to make sure that using native `Object.assign` doesn't cause regressions (since it has different constraints and may do more work than our simple polyfill).
