### ISSUE TITLE
Configure `?version=<customValue>` in index.html, e.g. <script src="assets/vendor.js?version=...

### ISSUE THREAD

**Issue by charneykaye** [emberjs/ember.js#14863]
In order to force updated static assets to load from a stubborn CDN, I'm looking for a method of adding a `?version=<customValue>` to the end of each of my `src="assets/...` references in **app/index.html**.

Maybe in index.html:

    <link rel="stylesheet" href="assets/vendor.css?version={{content-for 'version'}}">

And then somewhere else I might override a custom `content-for` value with a random number or a build tag.

Ideas? Thanks!

**Comment by charneykaye** [comment]
Asked this as a question on Stackoverflow: http://stackoverflow.com/questions/41798210/ember-js-version-customvalue-in-index-html-e-g-script-src-assets-vendor

**Comment by locks** [comment]
Closing for the StackOverflow question, thanks!
