### ISSUE TITLE
Ember snapshot belongsTo always return null on inverse relation

### ISSUE THREAD

**Issue by abbec** [emberjs/ember.js#14879]
I have a relationship between two models as A has many B and B belongs to A. When loading A, B is sideloaded and I can use the inverse relationship B->A just fine in the template. However, when I try to use `belongsTo()` on a snapshot for one of the loaded B models, it returns null. Is that supposed to work and how come it works in the template but not with a snapshot in the adapter?

As said above, it works fine in the template, but not with a snapshot in the adapter. I can also see in the debugger that `inverseRecord` is `null` on the relationship when stepping through the code for `belongsTo()`

EDIT:

Created a twiddle with an example of this. Check the adapter for `server` and the log output when pressing delete: https://ember-twiddle.com/71c98929c307284c78dae336d6cd040b. Expected is to be able to resolve the `belongsTo` relationship in the adapter but as seen it returns `null`. It can also be seen that it works fine in the template.

**Comment by Serabe** [comment]
Great report! Can you please move this to [emberjs/data](https://github.com/emberjs/data)?

Thank you!

**Comment by abbec** [comment]
Of course, sorry.

**Comment by Serabe** [comment]
No problem at all, thank you!
