### ISSUE TITLE
Ember.RSVP removed from emberjs.com/api documentation

### ISSUE THREAD

**Issue by kylemellander** [emberjs/ember.js#14874]
I discovered `Ember.RSVP` was missing from all lists when trying to access http://emberjs.com/api.  This update seems to have happened here:

https://github.com/emberjs/emberjs.github.com/commit/0702657c9f4b4dd051ffb38877b235bad589ffe1

**Comment by pfmmfp** [comment]
As a workaround, you can still access through the top nav search

**Comment by rwjblue** [comment]
Thanks for reporting! I'll take a look...
