### ISSUE TITLE
ember test - Could not find module ''module-for-acceptance"

### ISSUE THREAD

**Issue by ozbarshalom** [emberjs/ember.js#14885]
Hello,
I am using:
ember-cli: 2.11.0
node: 6.6.0
os: win32 x64

I started a new project with tests as documented in the tutorial.

```
test('should redirect to rentals route', function (assert) {
  visit('/');
  andThen(function() {
    assert.equal(currentURL(), '/rentals', 'should redirect automatically');
  });
});

test('should list available rentals.', function (assert) {
  visit('/');
  andThen(function() {
    assert.equal(find('.listing').length, 3, 'should see 3 listings');
  })
});
```

But, When I am running `ember test --server` I am getting this error:

> Uncaught Error: 
> Error: Could not find module `<projectname>/tests/helpers/module-for-acceptance.js` imported from `<projectname>/tests/acceptance/list-rentals-test` at http://localhost:7357/assets/test-support.js, line 4614

**Comment by marclundgren** [comment]
I'm having this problem too. Here are the [docs](https://guides.emberjs.com/v2.11.0/testing/acceptance/)

**Comment by marclundgren** [comment]
@ozbarshalom this is probably an ember-cli issue

**Comment by pixelhandler** [comment]
@locks is this an issue in the tutorial ? i.e. label: Documentation ?

**Comment by locks** [comment]
cc @Turbo87

**Comment by pixelhandler** [comment]
Anyone able to reproduce this issue?

**Comment by dmtask** [comment]
Yes, i´m having this Problem too

**Comment by dmtask** [comment]
Anyone a idea to fix this problem?

**Comment by rwjblue** [comment]
I don't think this is an issue (just tested with `ember new`), newly generated projects properly have a `tests/helpers/module-for-acceptance.js` file and it is importable in the testing system.

I'm going to close this (as it isn't an Ember bug), but if others are still hitting this we should either create an issue in the emberjs/guides repo (if it is while going through the tutorial) or we should create an issue in ember-cli/ember-cli repo.  In either case, a repo that demonstrates the issue will almost certainly be needed for us to figure out what is going on.
