### ISSUE TITLE
Store push / findRecord causes model to reload previously destroyed record

### ISSUE THREAD

**Issue by gregattra** [emberjs/ember.js#14895]
This is a bit complex to describe with out showing, but I do believe it is a bug.

I have a model, `feed`, which `hasMany` `feedTracks`. 

When a user takes a certain action, the top object in the `feedTracks` array is removed. But then, when I go to insert a new object into that array, the old object that was just removed, reappears. 

```
    skipFeedTrack(feedTrack) {
      feedTrack.skip().then((response) => {
        feedTrack.destroyRecord().then(() => {
          this.modelFor('master.feed').get('feedTracks').removeObject(feedTrack);
        });
        if (response != null) {
          this.store.pushPayload({feedTrack: response});
        }
      }.bind(this));
    }
```
The `feedTrack` is successfully removed from the `feedTracks` array (which is a `hasMany` relationship to the `feed`). But then, when `this.store.pushPayload({feedTrack: response});` or any variation of that (i.e. `findRecord`, or `push`) is called, the `feedTrack` that was just removed reappears on the template at the top.

I believe this is a bug as, when you call `destroy()` on a record, it should effectively remove it from the cache.

Ultimately at the end of the day, all I want to do is remove one record/object from the `hasMany` association and insert another which is given from the server response to the call to `skip()`.

**Comment by locks** [comment]
Thanks for filing an issue @gregattra, I have moved this issue to `emberjs/data` since that repository seems more relevant. Please follow up there!
