### ISSUE TITLE
Supported Active LTS version of Node is conflicting or obsolete in Ember docs

### ISSUE THREAD

**Issue by joelpresence** [emberjs/ember.js#14893]
At http://emberjs.com/blog/2016/09/07/ember-node-lts-support.html, it says that Ember prefers the current Active LTS version of node and specifies Node.js v4.5.0 and then links to the Nodejs downloads page.  However, the linked to page says that the current Active LTS is 6.9.2.  So, for maximum Ember compatibility, should we use Node.js 4.5.0 or 6.9.2?

I realize that this Ember doc may be out of date, but could we update it?  It's confusing to see conflicting statements about dep versions.  I'd be happy to help with edits if there's a desire ...

Thanks!

**Comment by locks** [comment]
Hi @joelpresence, I have moved the issue to the website repository where the blog posts source is and left a comment. Please follow up there, thank you :)
