### ISSUE TITLE
`Ember.compare` on objects with `valueOf` is always equal

### ISSUE THREAD

**Issue by ming-codes** [emberjs/ember.js#14892]
JavaScript convention to compare objects is to allow the object to implement the `valueOf` method to convert it into a primitive so it can be compared. It does not looks like `Ember.compare` respect this.

```js
Ember.compare({ valueOf() { return 1; } }, { valueOf() { return 2; } }); // actual 0; expected -1
```

**Comment by pixelhandler** [comment]
@ming-codes I think that the `Ember.compare` function does not use valueOf internally, https://github.com/emberjs/ember.js/blob/v2.11.0/packages/ember-runtime/lib/compare.js#L40 

But you're correct JavaScript should use it when comparing the primitive value of an object. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/valueOf

Perhaps the comparison here is not casting the object you expect as a primitive value?

> `Ember.compare({ valueOf() { return 1; } }, { valueOf() { return 2; } });`

I created a util object and unit tests as follows:

⚡ cat app/utils/compare.js

```javascript
import Ember from 'ember';

export default function compare(a, b) {
  let first = {
    valueOf() { return a; }
  };
  let second = {
    valueOf() { return b; }
  };
  return Ember.compare(first + 0, second + 0);
}
```

⚡ cat tests/unit/utils/compare-test.js

```javascript
import compare from 'compare-14892/utils/compare';
import { module, test } from 'qunit';

module('Unit | Utility | compare');

test('compare 1, 2 using valueOf', function(assert) {
  let result = compare(1, 2);
  assert.equal(result, -1);
});

test('compare 2, 1 using valueOf', function(assert) {
  let result = compare(2, 1);
  assert.equal(result, 1);
});

test('compare 3, 3 using valueOf', function(assert) {
  let result = compare(3, 3);
  assert.equal(result, 0);
});

test('valueOf normal behavior', function(assert) {
  let one = Object.create({
    valueOf() {
      return 1;
    }
  });
  let two = Object.create({
    valueOf() {
      return 2;
    }
  });
  assert.equal(one + 0, 1, 'one{} object primitive value is 1');
  assert.equal(two + 0, 2, 'two{} object primitive value is 2');
});
```

<img width="1037" alt="compare-test-output" src="https://cloud.githubusercontent.com/assets/17178/22600631/3ca90e4e-e9f0-11e6-9208-b644a206e683.png">

**Comment by pixelhandler** [comment]
@ming-codes This is not an Ember.js bug, I'll close this, feel free to reopen or discuss on in the http://embercommunity.slack.com #-help channel.

**Comment by ming-codes** [comment]
@pixelhandler I'm not using `Ember.compare` directly, so I can't do any type casting. `Ember.compare` is used by `Ember.computed.sort`, this is where I'm having issue with. I need to sort an array according to a property that contains enum objects. The enum objects are immutables that implements `valueOf` to provide a way of sorting them.

**Comment by pixelhandler** [comment]
@ming-codes thanks for moving this topic to an RFC :) seems like an enhancement would be good for `computed.sort`
