### ISSUE TITLE
Contextual component renders as `[object Object]` when passed as a named param

### ISSUE THREAD

**Issue by GavinJoyce** [emberjs/ember.js#14906]
There seems to be a rendering inconsistency between contextual components which come from parameters that use the `hash` helper and those that do not.

**[Demo twiddle](https://ember-twiddle.com/61cf80cb5c1ee8151458fbb45145c6a5?openFiles=templates.application.hbs%2Ctemplates.components.outer-component.hbs)**

When using the `hash` helper, the component is rendered as expected:

```hbs
{{#with (hash foo=(component 'foo-component')) as |components|}}
  {{components.foo}}
{{/with}}
```

renders:

```
I'm foo-component.
```

Without it, the component doesn't render which, from a user perspective, is surprising IMO:

```hbs
{{#with (component 'foo-component') as |foo|}}
  {{foo}}
{{/with}}
```

renders:

```
[object Object]
```

A work around is to use the `component` helper a second time in the block:

```hbs
{{#with (component 'foo-component') as |foo|}}
  {{component foo}}
{{/with}}
```

```
I'm foo-component.
```

**Comment by GavinJoyce** [comment]
I believe that the `[object Object]` comes from [here](https://github.com/tildeio/glimmer/blob/9d53cafa32c32c92c528a295abfbee72a6d51e99/packages/%40glimmer/runtime/lib/compiled/opcodes/content.ts#L59) as we cast the component definition to a string:

<img width="563" alt="screen shot 2017-02-04 at 21 04 45" src="https://cloud.githubusercontent.com/assets/2526/22621524/a32ac8b4-eb1d-11e6-998c-b6d95177b225.png">

**Comment by rwjblue** [comment]
Contextual components **must** be invoked with a period, `{{foo}}` will never be a contextual component invocation.  Your solution using `{{component` helper is the right path if you are not using a dotted path for invocation.

**Comment by GavinJoyce** [comment]
thanks for the explanation
