### ISSUE TITLE
Ember - Test on production build - Source: TypeError: visit is not a function

### ISSUE THREAD

**Issue by HariniNunduri** [emberjs/ember.js#14901]
I am trying to add a test on production build.
The test loads but fails at Visit/Click functions.
**Error

```
Died on test #1     ---
----
    at Array.forEach (native): visit is not a function@ 3 ms
Source: 	TypeError: visit is not a function
   
-----**
```

Code looks like this

```
import Ember from 'ember';
import { module, test, skip } from 'qunit';
import startApp from '../../helpers/start-app';

module('Prod tests', {
  beforeEach(assert) {
    this.application = startApp();
  },
  afterEach() {
    Ember.run(this.application, 'destroy');
  }
});

test('load the page', function(assert) {
  assert.expect(1);
  // Go to home tab
  visit('/');
---
----
});
```

------ Minified test.js (dists/assets) code snippet---

```
define("../tests/prod-test",["exports","ember","qunit","../tests/helpers/start-app", "../tests/helpers/test-helpers"],function(e,t,n,r,i){function a()
n.module("Prod tests",{beforeEach:function(e){this.application=r.default()
t.default.run(this.application,"destroy")}})
a("load the page",(function(e){e.expect(1)
visit("/search")
```

**Comment by pixelhandler** [comment]
@HariniNunduri I'm curious what is the motivation to test using `production` environment vs `test` ? Have you found any guidance for creating a test that works on a production build?

Perhaps reach out in the http://embercommunity.slack.com #-help channel you'll likely get more feedback there. 

This doesn't appear to be an Ember.js bug, perhaps more of a question about testing. To test a production build I typically use Selenium not Ember's test runner (for end-to-end tests)

**Comment by HariniNunduri** [comment]
Will do thanks.
