### ISSUE TITLE
Provide an option to use dasherized test names

### ISSUE THREAD

**Issue by GabrielCW** [emberjs/ember.js#14915]
When tests are generated, there name is [humanized](https://github.com/ember-cli/ember-cli-test-info/blob/master/index.js#L27) to make it more readable by humans. This process removes the dashes from the base strings, meaning `some-component`'s test name will be `some component`.

I recently had a problem where I couldn't run test for one of my components with `ember test --filter="some-component"`. To make it more confusing, jshint tests ran well for the expected files, but the test itself didn't run. @Turbo87 helped me figure out it was because the test name was `some component`, therefore not matching `some-component`.

Considering the test's name is humanized, it was counter intuitive to think that it may be used in resolution.

**Could an option be added to the generator, in order to allow for the string to stay dasherized?** With that option, a test generated for `some-name/space/some-component` would actually contain `some-name/space/some-component`.

Or could it even be used as default? Is the current humanized form relied upon?

**Comment by Turbo87** [comment]
I tend to agree that this is confusing default behavior and I often hand edit the name myself because the humanizer invented some bad looking name for the component or module. For a `foo-bar` component we already have the name `foo-bar` (or `component:foo-bar`) and the `FooBarComponent` when using globals. Why should there be a third name `foo bar` which does not related to the filename or the global? This seems confusing to me and I would support an effort to use the dasherized component/module name instead, which correlates with the filename it is stored in.

**Comment by pixelhandler** [comment]
@GabrielCW perhaps this is an issue that belongs on the ember-cli project instead of the ember.js project. The blueprints are part of https://github.com/ember-cli/ember-cli/issues

**Comment by locks** [comment]
@pixelhandler they shouldn't be? https://github.com/emberjs/ember.js/tree/master/blueprints

**Comment by Turbo87** [comment]
agreed, the relevant blueprints for this issue live in ember.js and ember-data now and that is where they should be discussed.

**Comment by pixelhandler** [comment]
@locks oh forgot, they used to live in ember-cli, my bad.

**Comment by pixelhandler** [comment]
@Turbo87 @GabrielCW @locks -  I'm curious if this should be discussed on an RFC issue instead of in two places ember.js and data issue trackers.

> Use RFC issues to propose a rough idea, basically a great place to test the waters.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature

**Comment by Turbo87** [comment]
@pixelhandler I'm not sure if this would actually need a full blown RFC to be honest, but feel free to write one 😉

**Comment by GabrielCW** [comment]
@pixelhandler @Turbo87 I went ahead and wrote the RFC, it is available [here](https://github.com/GabrielCW/rfcs/blob/master/0000-dasherized-test-name-generator-option.md).

**Comment by Turbo87** [comment]
@GabrielCW awesome, thanks!
