### ISSUE TITLE
Allow concatenated properties the {{component}} keyword

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#14914]
This feature is a nice to have. If it's computationally expensive it might not worth adding, but if added it would make a few composition patterns easier.

Say you are building a components that wraps another component that yields contextual components, and you want to bind some classes and allow users to bind their own.

```hbs
{{! imaginary datepicker component }}
{{#basic-dropdown as |dd|
  {{yield (hash
     trigger=(component dd.trigger class="datepicker-trigger")
     content=dd.content
  )}}
{{/basic-dropdown}}
```

You want the user to be able to add more classes to the trigger without removing the default one (`datepicker-trigger`):

```hbs
{{#my-datepicker as |dp|}}
  {{#dp.trigger class="extra-class"}}Foobar{{/dp.trigger}}
{{/my-datepicker}}
```

At the moment this code will generate
```hbs
<div class="basic-dropdown-trigger extra-class">Foobar</div>
{{! note that  "datepicker-trigger" is not present}}
```

One dirty-ish workaround is abuse the duality `class`/`classNames` un ember and do:

```hbs
{{! imaginary datepicker component }}
{{#basic-dropdown as |dd|
  {{yield (hash
     trigger=(component dd.trigger classNames="datepicker-trigger")
     content=dd.content
  )}}
{{/basic-dropdown}}
``` 

Since most people will use `class`, both will be present.

My feature request is to investigate if it's possible to consider special properties, like `class` concatenated properties in the `{{component}}` keyword, so the first example generates a div with both classes.

If this perf penalty it's significant disregard this request.

/cc @Serabe

**Comment by locks** [comment]
Does this not need an RFC?

**Comment by cibernox** [comment]
Unsure. @rwjblue said it could be considered a bug because it's not how components work, but it is indeed on the verge of being considered a breaking change.

**Comment by rwjblue** [comment]
IMO, it is a bug. It should work, and I was surprised it didn't....

**Comment by cibernox** [comment]
Concatenated properties is a feature to concatenate concatenate properties of a superclass with the ones defined in the class itself. 
This should work if se considering creating a creating a contextual component analogous to subclassing a component. If we consider that creating a contextual component (Technically that created a `ComponentDefinition` object) different this is working as expected.

**Comment by pixelhandler** [comment]
@rwjblue so should this be labeled a bug?

**Comment by mixonic** [comment]
Interesting. I don't think this is a bug, I'd still call it a feature request and definitely good feedback @cibernox. However it doesn't seem likely we would change the `(component` helper to have merge semantics specific to Ember components. Instead we should take this as a data-point when we figure out how to use dynamic or curried component invocation with glimmer components.

**Comment by cibernox** [comment]
FWIW, I don't consider this to be unexpected. I think it has signaled an area where the API of my component could be improved.

**Comment by pixelhandler** [comment]
@rwjblue @mixonic I added both labels for now Bug/Proposed Feature :)

**Comment by AnastasiyaYelets** [comment]
hello, does this bug still exists at last ember versions?

**Comment by Serabe** [comment]
As explained in [this comment to an old PR for this, this is being marked as wontfix](https://github.com/emberjs/ember.js/pull/14956#issuecomment-375496686).

Thank you all!
