### ISSUE TITLE
Ember 2.11 poor performance

### ISSUE THREAD

**Issue by devlo** [emberjs/ember.js#14926]
I've upgraded from Ember 2.4 to 2.11 and I am seeing longer route loading times. I have a routes that are loading around 20% slower than before, from around 800-900ms to 1000-1200. I also see that 92% of time is spent in scripting with Ember.  This is timeline from loading that route:

![screenshot from 2017-02-10 16-57-33](https://cloud.githubusercontent.com/assets/6026315/22840246/ff4eef5e-efcc-11e6-9513-b52f61600ec4.png)

**Comment by devlo** [comment]
@krisselden 

Why it doesn't look like production build? I've turned of minifying to show full functions name, it's that what you mean? It's built with --prod.

**Comment by devlo** [comment]
btw I am testing this on Ubuntu

**Comment by devlo** [comment]
Hmm It seems more like problem with chrome on linux. I see improvements on other box with windows 10.

**Comment by stefanpenner** [comment]
This seems to have gotten stale. We can gladly reopen, but will require a reproduction. That way, we can use the various profiling tools to see whatsup From whats provided, this isn't terribly actionable.

In addition, the apps I work on haven't seen a large regression (rather good improvements) which suggests it may not be affecting a wide range of use-cases. So a reproduction will be important to track down what you are seeing.
