### ISSUE TITLE
Uncaught TypeError: Can't add property __each, object is not extensible

### ISSUE THREAD

**Issue by caseklim** [emberjs/ember.js#14921]
Trying to upgrade to 2.11.0, I'm seeing the following error triggered by the following computed property. Note: I started seeing this error upgrading from 2.9 to 2.10, and continuing to 2.11 didn't solve it.

```
Uncaught TypeError: Can't add property __each, object is not extensible
``` 
```
allCheckboxValues: computed.mapBy('checkboxes', 'value'),
```

Writing the computed property as follows solves the issue, but I'd rather use the `mapBy` in the `computed` namespace:
```
allCheckboxValues: computed('checkboxes', function () {
  return this.get('checkboxes').mapBy('value');
}),
``` 

I created an Ember Twiddle but couldn't reproduce the issue:
https://ember-twiddle.com/bd592290e18a5517c714c15c6f789b7d?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs

Here's a screenshot of where the error occurs and the data it occurs with:
![screen shot 2017-02-09 at 3 22 43 pm](https://cloud.githubusercontent.com/assets/2915936/22807412/ab7da18c-eedb-11e6-901b-84d98dea06e8.png)

**Comment by Serabe** [comment]
How are you passing the checkboxes to the component? Are they defined in the component itself or are passed when invoking the component? If so, can you paste the exact expression being passed?

As an example, if you are doing `{{my-component checkboxes=checkboxes}}` and those checkboxes come from the parent invocation, I would like to see the parent's one, not just checkboxes.

I suspect this is a problem with the froze params but would like to confirm.

Thank you for your report!

**Comment by caseklim** [comment]
They're being passed when invoking the component. Here's how they're being passed in:
```
{{checkbox-component
  checkboxes=(group
    (hash label="Foo" value="foo")
    (hash label="Bar" value="bar")
  )
}}
```

Where `group` is a helper that simply returns the parameters that were passed into it as an array.

Thank you for the fast follow-up!

**Comment by Serabe** [comment]
`args` and `params` in helpers are frozen in dev mode since 2.10. See [Ember 2.10 release blogpost](http://emberjs.com/blog/2016/11/30/ember-2-10-released.html#toc_other-notable-changes).

Closing this as a non issue.

Thank you!
