### ISSUE TITLE
Triple stash with undefined content at top of template causes view to repeat

### ISSUE THREAD

**Issue by czosel** [emberjs/ember.js#14924]
I just stumbled over this bug that only seems to occur if your template starts with 
```handlebars
{{{somethingUndefined}}}
```
When you switch back and forth between views, the template is rendered multiple times. This only seems to affect Glimmer 2.

For a working reproduction please see this [ember-twiddle](https://ember-twiddle.com/f86acbc13e82a9dc7b7888aa47791dfa).

**Comment by rwjblue** [comment]
This is definitely pretty weird behavior, thank you for reporting (and for the reproduction)!

**Comment by mapeveri** [comment]
I would like to take this issue, I am new and I would like to know where to start if possible. Thanks!

**Comment by chancancode** [comment]
Sorry it took so long, this is fixed in 3.4.3 (#17003)
