### ISSUE TITLE
Test blueprints don't work with Ember 2.11.1

### ISSUE THREAD

**Issue by Dhaulagiri** [emberjs/ember.js#14935]
To reproduce, generate a new app with Ember 2.11.1/ember-cli 2.11.1:

```
ember new blueprint test
cd blueprint-test/
ember g acceptance-test foo
installing acceptance-test
```

No actual test is generated

/cc @Turbo87

**Comment by Turbo87** [comment]
@Dhaulagiri this only happens when using `ember-cli-mocha`, correct?

**Comment by Dhaulagiri** [comment]
This seems to happen with both in my testing

**Comment by Dhaulagiri** [comment]
Closing in favor of #14936 👌

**Comment by rwjblue** [comment]
oh darn, sorry for not checking first 😢
