### ISSUE TITLE
Help with load ember-testing on a production build 

### ISSUE THREAD

**Issue by HariniNunduri** [emberjs/ember.js#14949]
Any suggestion on how to load ember-testing on a production build or bundle it up with the live testing output .. I am new to this and need help figuring out this part.
**Problem**:
Live test loads on the page but fails due to missing ember-testing helpers that are only provided in emberjs source code in the dev build.

**Error**: Throws Cannot read property 'registerAsyncHelper' or '<any element'> of undefined ...
Because* _ember['default'].Test is undefined*

**Comment by rwjblue** [comment]
You need to load the `ember-testing.js` asset before attempting to run tests.

See [demo JSBin](https://jsbin.com/gadumar/edit?js,output) which uses `ember.prod.js` and still runs acceptance tests.

**Comment by HariniNunduri** [comment]
Thanks Robert, Just want to clarify from my side. We are having test deployed in production and hitting it with customized test route to serve the test/index.html.

**Comment by HariniNunduri** [comment]
I’ve tried to load ember testing files by including
*<script src=”https://s3.amazonaws.com/builds.emberjs.com/canary/ember-testing.js”></script>*  in *dist/core/index.html*
Still seeing the error

**Comment by stefanpenner** [comment]
@HariniNunduri could you provide a reproduction of your issue? 

@rwjblue's JSBin demonstrates how this is possible. But without an example, it isn't terribly actionable for us to help.

I'm going to close this for now, if you continue having issues please provide a reproduction. At which point we may be able to help debug, and help deduce whatsup.
