### ISSUE TITLE
Ember 2.5.0:  You're not allowed to have more than one controller property map to the same query param key.

### ISSUE THREAD

**Issue by aonawale** [emberjs/ember.js#14943]
Transitioning from a child route to another child route on the same route level triggers this error when the parent route have query parameter.

Here is a demonstration on twiddle: https://ember-twiddle.com/e086695d4c621cd3c4f4653dfe1a8963?openFiles=routes.checkout.payment.js%2C

**Comment by locks** [comment]
@aonawale I think you forgot to save, I only see the default Twiddle files.

**Comment by aonawale** [comment]
saved @locks

**Comment by rwjblue** [comment]
The link above does not include the Gist ID, I suspect that https://ember-twiddle.com/e086695d4c621cd3c4f4653dfe1a8963?openFiles=routes.checkout.payment.js%2C is the twiddle we are looking for...

**Comment by aonawale** [comment]
That's right @rwjblue. I have updated my comment to reflect this.

**Comment by Serabe** [comment]
This is working in both 2.8.3 ([twiddle for the latest LTS](https://ember-twiddle.com/e3afc13d9a6fb5d37a3745a80640f421?openFiles=twiddle.json%2C&route=%2Fcheckout%3Fqty%3D2)) and 2.11.2 ([example for latest version as of this writing](https://ember-twiddle.com/c25d573731a55fe0270830877ae197f0?openFiles=twiddle.json%2C)).

Version 2.5 is no longer supported. Please, upgrade to either LTS or latest version. Please review [the LTS announcement blogpost](http://emberjs.com/blog/2016/02/25/announcing-embers-first-lts.html).

Thank you!

**Comment by Turbo87** [comment]
This seems related to https://github.com/emberjs/ember.js/issues/13258 🤔
