### ISSUE TITLE
Having two template names, one plural one singular, ignores plural 

### ISSUE THREAD

**Issue by Alonski** [emberjs/ember.js#14944]
I have two different routes:
1. Template
2. Templates

This also generated two templates:
1. template.hbs
2. templates.hbs

When I go to the templates route. Ember tries to render the template.hbs template.
![pasted image at 2017_02_20 02_32 pm](https://cloud.githubusercontent.com/assets/452199/23125939/0cf64c26-f77d-11e6-85db-28532ca6fb1a.png)

Trying to use templateName or renderTemplate() doesn't work.
`
// app/routes/templates.js
 export default Ember.Route.extend({
    templateName: "templates",
    renderTemplate() {
        this.render("templates");
    }
});
`

Here is a twiddle made by @gmarquet 
https://ember-twiddle.com/c3f1c16b8fb0ca56248b767a09acd3c9?openFiles=twiddle.json%2C&route=%2Ftemplates

Got around this currently by renaming the template.hbs to something else and using templateName to set the name for the the template route

**Comment by pixelhandler** [comment]
@Alonski it may be worth sharing a work around example as well. I see the issue in the ember-twiddle example you provided, this looks like a bug.

**Comment by Alonski** [comment]
Hey my workaround was renaming template.hbs to template-single.hbs. Then in the tenplateRoute I have templateName: template-single.hbs.

**Comment by locks** [comment]
This is likely related to pods.

**Comment by Alonski** [comment]
@locks To clarify I am not using pods in my App.

**Comment by locks** [comment]
@Alonski the thing is that the resolver supports both structures at the same time, and as far as I know there's no way to "turn it off", so indirectly you are using pods ;x
What I think is happening here, since you don't have a "pod module prefix" set, it falls back to `/apps`, meaning `app/templates/template.hbs` translates to "this is the template file for the templates route".

**Comment by pixelhandler** [comment]
@Alonski yeah I was suspicious of the name `template.hbs` glad you had a work around using `template-single.hbs`. I'll close this for now.

**Comment by Alonski** [comment]
@pixelhandler I'm not sure this should be closed. Maybe add a workaround in the CLI so you can't create templates named template.hbs
