### ISSUE TITLE
`owner.inject` with model type is broken in beta

### ISSUE THREAD

**Issue by workmanw** [emberjs/ember.js#14941]
Ember-Release: [Working Twiddle](https://ember-twiddle.com/e3a9f016848e28174059c52fe42944d2/75f5cfe06f78f0fee31f747ce66b5963e001d31e?openFiles=templates.application.hbs%2C)
Ember-Beta: [Broken Twiddle](https://ember-twiddle.com/e3a9f016848e28174059c52fe42944d2/7f6eb3760848bb88616fef26e854dc8fc3a055fe?openFiles=templates.application.hbs%2C)

It seems that using `owner.inject` targeting a `model` type in an initializer is broken on beta. Example:

```javascript
// app/initializers/i18n.js
export default {
  name: 'i18n',
  after: 'ember-i18n',
  initialize: function(app) {
    app.inject('model', 'i18n', 'service:i18n')
  }
};
```

I have not had the chance to fulling investigate it yet. But it seems that these types of injections do work on other types (controller, component, etc).

**Comment by workmanw** [comment]
So using the `component/emberjs` builds to bisect and it seems to have broken with this build: https://github.com/components/ember/commit/c73cce48a272742af053941a4f52ca3266cd4a39 which is unfortunately not super helpful because that was the beginning of the beta cycle. 

I'll see if I can keep digging. Just looking at the diff it's hard to not see the `factory-for` feature and be suspicious about that.

**Comment by rwjblue** [comment]
I'm certain it is related to ember-factory-for feature, but I'm not exactly sure why yet.

**Comment by workmanw** [comment]
@rwjblue I have some cycles at the moment. If you have any hunches, I'd be happy to investigate further. I could also try to write a failing test.

**Comment by workmanw** [comment]
Talked with @rwjblue on slack. We agreed this was an ember-data issue and the issue should be moved over there. See: https://github.com/emberjs/data/issues/4807
