### ISSUE TITLE
Expose a configuration setting for exploring the metaStore

### ISSUE THREAD

**Issue by pieter-v** [emberjs/ember.js#14948]
Finding the cause of memory leaks is difficult if the metaStore is used: 
if you use the 3-snapshot method all objects allocated between snapshot-1 and snapshot-2 dissapear in the metaStore, which is a weakmap (and is not easy to explore).

As a workaround I redefine the method HAS_NATIVE_WEAKMAP to return always false.

It would be nice, to have this feature without making a 'custom' ember build

(originated in pull #14911)

**Comment by rwjblue** [comment]
Thanks for opening the issue! 

@stefanpenner / @krisselden - Thoughts?

**Comment by stefanpenner** [comment]
Im not apposed to this. Maybe `Ember.ENV.HAS_NATIVE_WEAKMAP` ?

**Comment by pixelhandler** [comment]
Does this need an RFC issue?

> Use RFC issues to propose a rough idea, basically a great place to test the waters.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature

**Comment by bekzod** [comment]
is this still valid since we use weakmap in ember 3.x already

**Comment by pixelhandler** [comment]
@pieter-v @stefanpenner is this still an issue, perhaps we should close; what do you think?

**Comment by rwjblue** [comment]
Thank you!
