### ISSUE TITLE
Case sensitive rootURL 

### ISSUE THREAD

**Issue by pawepaw** [emberjs/ember.js#14950]
Hello,

I found out that when i configure rootURL and type in browser same rootURL but i.e capitalized ember js will throw error. Is there any chance that you'll make it case insensitive? It's not user friendly because user got used to case insensitive urls. 

https://github.com/emberjs/ember.js/blob/78e3e0e7b32a0ef62dcc8badf6bc2e536db40975/packages/ember-routing/lib/location/auto_location.js#L242

I don't know if you rely on it somewhere else so i am not creating pr for it.

**Comment by tomasznapieralski** [comment]
I'm not sure if that would be possible, according to W3 URLs are case-sensitive.

> URLs in general are case-sensitive (with the exception of machine names). There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive. 

From https://www.w3.org/TR/WD-html40-970708/htmlweb.html

**Comment by pawepaw** [comment]
well 

> There may be URLs, or parts of URLs, where case doesn't matter

So it's not rule that url should be case sensitive. It's not user friendly from my point of view because domain by default is case insensitive so why user would expect the rest of address to be case sensitive?

**Comment by Serabe** [comment]
This behaviour is the same as the spec. Closing this as a non-bug.
