### ISSUE TITLE
Range Elements Report Wrong Initial Value

### ISSUE THREAD

**Issue by jherdman** [emberjs/ember.js#14958]
Range inputs report the wrong initial value for both the native `<input` and helper/component-based `{{input` since Ember 2.10.

Here's a demo Twiddle of the problem:

https://ember-twiddle.com/61645ec16fca7f5ff5a65c2b407ce94c?openFiles=components.range-element-spy.js%2Ctemplates.components.range-element-spy.hbs

And a JS Bin showing the expected behaviour:

http://output.jsbin.com/dodayozima

I'll see about writing up a failing test soon.

**Comment by locks** [comment]
Reproduction with DOM API: http://jsbin.com/luxuyi/edit?html,js,console,output

**Comment by jherdman** [comment]
OK, so using the example from @locks I can see that this happens in Chrome, and Firefox, but not Safari. I suppose I should be reporting this bug upstream to the various OEMs. Does anyone have guidance on this?

**Comment by Serabe** [comment]
Firefox and Chrome are doing it right following the spec.

In the absence of values for min, max and value, they get the values 0, 100 and `(max+min)/2`.

Closing this as a non issue.

Thank you!

**Comment by Serabe** [comment]
Reopening for further consideration.

Thank you!

**Comment by rwjblue** [comment]
@wycats / @chancancode created an issue over on the spec repo for this. Follow along at https://github.com/whatwg/html/issues/2427.

**Comment by chancancode** [comment]
For the foreseeable future, if we want to fix this bug, we probably need to
special case the input type attribute and set it last

**Comment by pixelhandler** [comment]
Could this be a work around for the time being, https://github.com/trek/ember-input-range ?
