### ISSUE TITLE
_super with mixin: _super points to wrong method

### ISSUE THREAD

**Issue by jpschober** [emberjs/ember.js#14965]
I've encountered a strange behavior in Embers `_super` implementation which I have reproduced in this Twiddle:
https://ember-twiddle.com/d343966966fe1a3308aef506eac92dd3?openFiles=adapters.document.js%2C

If you press the 'test' button to call the `updateRecord` method you'll see that `_super` inside of `headersForRequest` points to `updateRecord` which is obviously wrong. The bug is triggered due to the presence of the `this._super `call in `updateRecord`: If you remove the line 18 `return this._super();` in `adapters/document.js` `_super` is `ROOT`.

(I am aware of the plan to make `_super`calls without super methods deprecated. Nevertheless, I am not sure if this is the root of this bug).

**Bonus strangeness**: Because of the way the super wrapper is implemented it is not enough to comment the line out! Even a `// return this._super()` triggers the bug. This really gave me a headache as you wouldn't expect commented out code to have any effect at all

**Comment by jpschober** [comment]
Just realized that Mixins are not responsible for this behavior. I've updated the Twiddle accordingly:
https://ember-twiddle.com/d343966966fe1a3308aef506eac92dd3?openFiles=adapters.document.js%2C

**Comment by pixelhandler** [comment]
@jpschober I'm curious if this should be filed in the ember data issue tracker, https://github.com/emberjs/data/issues

**Comment by jpschober** [comment]
@pixelhandler I don't think that this is related to ember data: I've encountered the bug in an ember data scenario, but to me it looks like an error in the ember-utils/utils/super.js. 
If I'll find some time I'll dig further.

**Comment by jpschober** [comment]
I've updated the Twiddle once again: https://ember-twiddle.com/d343966966fe1a3308aef506eac92dd3?openFiles=models.document.js%2C
Now it should be obvious that ember data is not related to this bug. Additionally, I've added another test button: For one button the result is OK, for the other button the error is triggered. The only difference between the two methods is a comment! Therefore we have the situation that the mere presence of a comment affects the code execution!

**Comment by fastfedora** [comment]
While researching a similar issue (#15291), I was able to narrow this down to the text `._super` being the problem. That text triggers the regular expression optimization used to determine whether the function should be wrapped in `ember-utils/lib/super.js`. If this exists anywhere in the text of the function (e.g. a string, a comment, an actual function call), it triggers the function to be wrapped.

Since this is relying on a feature test (i.e. whether the function source can be retrieved), and falls back to always wrapping the function if the JavaScript engine doesn't support that, I'm wondering what impact this optimization has and if it can just be removed.

**Comment by stefanpenner** [comment]
@fastfedora provides an excellent workaround in #15291 my recommendation is to follow that.

Its a tricky balance getting that `_super` helper working, without a hefty performance penalty. We do have plans to transition to ES6 classes (that have there own super, that works essentially how @fastfedora's workaround works, but with nice ergonomics).

---

I suspect this is an unfortunate #WONTFIX, rather we will overtime be able to move away from `_super` entirely.
