### ISSUE TITLE
`mount` does not accept wildcard for path

### ISSUE THREAD

**Issue by sangm** [emberjs/ember.js#14971]
It's weird that mount accepts dynamic segments, but not wildcard. I've talked to @rwjblue and @trentmwillis about this, and seems to be a bug. 

```
this.mount('foo-engine', { path: '/foo/*wildcard' });
```

Submitting this issue so this is tracked, don't mind trying to fix it if it's acknowledged that this is a bug and not intended behavior

**Comment by rwjblue** [comment]
As mentioned in DM convo's `mount` should support the same basic functionality that `this.route` does for its `options.path`.
