### ISSUE TITLE
Experimenting with Mobx

### ISSUE THREAD

**Issue by mdebbar** [emberjs/ember.js#14973]
In general, I believe it's a good idea for OSS projects to benefit from each other whenever possible. [Mobx](https://github.com/mobxjs/mobx) is a library specialized in handling dependency graphs and computed properties. That means the implementation is likely more efficient than ones in a general-purpose frameworks such as Ember.

Mobx seems to have a few advantages that Ember can benefit from:
- Mobx observers don't have the caveats that Ember observers have.
- Mobx automatically maintains a graph of property dependencies that's very efficient and scalable.
- Devs don't need to specify dependent keys for computed properties, Mobx handles that automatically. This is a big source of problems from my experience with Ember.
- Ember doesn't have to maintain a lot of code that handles observers, computed, etc.

I'm curious if anyone has experimented with incorporating mobx into Ember Objects to track observers and computed properties. If not, would that be something of interest to the Ember team?

**Comment by locks** [comment]
Hi @mdebbar, could you transfer this to https://github.com/emberjs/rfcs/issues ? That's the best place to propose exploration such as this one, since we reserve this issue tracker for bugs with Ember itself.

**Comment by mdebbar** [comment]
Ok, created an issue here: https://github.com/emberjs/rfcs/issues/210

**Comment by locks** [comment]
Thank you!

**Comment by stefanpenner** [comment]
Is this intended to be an in-depth comparison analysis, or merely recommending others do that.

**Comment by mdebbar** [comment]
@stefanpenner this is intended as an idea to experiment with integrating mobx inside ember. I mainly want to answer a few questions before I attempt writing an RFC:
1. Has anyone thought about this before.
2. Is it worth doing such an experiment.
3. Are there any objections to doing an integration like this.

**Comment by stefanpenner** [comment]
I suspect is is very much useful to do an investigation, learn what the pros and cons are and apply the lessons to ember. Switching users to use something different, means we leave existing code-bases and apps without said improvements, which fails at the compounded value we aim to offer. 
It is also worth pointing out we have an on-going effort, to re-make the observation system in-terms of the primitives glimmer provides, as the ones glimmer provides are both extremely quick and there would be no interopt overhead any longer when working with glimmer.

As mentioned, there is always lots of learn from open-source projects and we should be sure to do a deep analysis, and apply said learning.

**Comment by auvipy** [comment]
https://discuss.emberjs.com/t/porting-mobx-ideas-to-ember-js-dependency-less-properties/10796/7
