### ISSUE TITLE
Ember.instrument misses compilation/lookup phase.

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#14974]
During initial render of a component the `render.component` subscription event does not include the compilation and module lookup times. 

As this only happens the first time a class of component is rendered, it should likely be a new event. Maybe `render.compile` or `render.setup`.

Flame graph demonstrating the unclaimed time. *Note: the darker/bolder highlights this unclaimed time*.

<img width="1142" alt="missing-instrumentation-event" src="https://cloud.githubusercontent.com/assets/1377/23440526/3e267712-fdd1-11e6-8922-fbdf71ddce22.png">

---

For reference, we noticed this while authoring [ember-perf-timeline](https://github.com/stefanpenner/ember-perf-timeline) addon

@hjdivad & @stefanpenner

**Comment by rwjblue** [comment]
Seems good to me, likely fine to PR so we can review specific details...

**Comment by stefanpenner** [comment]
Should be relatively straight forward, maybe someone has spare cycles to do this. (I don't really have cycles)
