### ISSUE TITLE
Ember.computed.rejectBy is not a function

### ISSUE THREAD

**Issue by remithomas** [emberjs/ember.js#14988]
hi,

Is it possible to add the computed properties `reject` and `rejectBy` ? 
`filter` and `filterBy` are already here.

thanks

**Comment by Serabe** [comment]
Sorry. At this point in time, adding computed macros is highly unlikely. [Read this post](http://emberjs.com/blog/2016/07/25/ember-2-7-and-2-8-beta-released.html#toc_code-ember-computed-uniqby-code) for more inforamtion.

Thank you!
