### ISSUE TITLE
Link-to helper not functioning with Ember Data model relationship

### ISSUE THREAD

**Issue by RossValler** [emberjs/ember.js#14984]
When attempting to use the `link-to` helper in 2.10+ with a model relationship property, an assertion error is thrown and the link fails to display. I have recreated it as a Twiddle here: https://ember-twiddle.com/16d9be91b310fe01ecbdc152e8aae292

Specifically this in `index.hbs`:
```
{{#each model as |invoice|}}
    {{#link-to "single" invoice.client}}
        {{invoice.number}}: {{invoice.client.name}}
    {{/link-to}}
{{/each}}
```

This previously worked on 2.9.1 and earlier but on 2.10.x and above, it throws an error.

**Comment by Serabe** [comment]
Thank you for the report!

**Comment by stefanpenner** [comment]
The error is the `client` object has no `id` so `link-to` can't construct a link from it. If you add an `id` to the client, all is well.

https://ember-twiddle.com/40ed04f63813be8312d8c274453b34bd?openFiles=routes.index.js%2C

**Comment by stefanpenner** [comment]
Actually something does seem strange, as this only works if you also specify `invoice.client.id` in the template.

**Comment by stefanpenner** [comment]
It seems the URL generation code is unable to read through EmberProxies.

`invoice.client.content` also works, but just naked `invoice.client` does not.

**Comment by stefanpenner** [comment]
This seems related to router related changes cc @krisselden / @scalvert

**Comment by stefanpenner** [comment]
i think the offending line is https://github.com/emberjs/ember.js/commit/f4b2723029d8d8ff40e962e5fdd8aa8f75a231c3#diff-14507db3dc0044b9c698c1e09ce44fd4R47 cc @trentmwillis

**Comment by trentmwillis** [comment]
In that diff I simply moved a function from its location further down in the file, so it feels unlikely that is the cause. The only change in behavior in that PR is for Engines.

**Comment by pixelhandler** [comment]
@RossValler @stefanpenner @trentmwillis is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by RossValler** [comment]
@pixelhandler in all honesty, I haven't worked with this application in over a year so I am unsure if this is still an issue _shrug_

**Comment by pixelhandler** [comment]
@RossValler thanks for the reply, I updated the twiddle example, https://ember-twiddle.com/9831b89a3cee9878c55b27e5b127f0e7?openFiles=templates.index.hbs%2C seems to work if I use the id for the link-to.

Closing this.
