### ISSUE TITLE
Error when trying to disable input with readonly value

### ISSUE THREAD

**Issue by escobera** [emberjs/ember.js#14996]
Hello there,

I'm having trouble when trying to disable an input field with a readonly value. The error I get is: 

Assertion Failed: You modified "value" twice on <twiddle@component:-text-field::ember324> in a single render. It was rendered in "component:-text-field" and modified in "component:-text-field".

This [twiddle](https://ember-twiddle.com/25ac9ed742d7c1b4bd7ba4038bfbee13?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs) shows the error better than I can explain, just write anything on the input, press "Enter" and watch the console.

**Comment by Serabe** [comment]
Strange. This did not happen in Chrome 56 but it does happen after upgrading to Chrome 57.

**Comment by Serabe** [comment]
As a workaround, you can use plain `<input>` tags (which are faster).

**Comment by escobera** [comment]
that workaround comes with a little more work as I have to check keycode on keypress, but no more errors!
Thanks a lot for the tip =)
