### ISSUE TITLE
Ember.Component#attributeBindings has disappeared from API docs

### ISSUE THREAD

**Issue by mike-north** [emberjs/ember.js#15003]
As of the v2.11 docs, at least this one property has disappeared from the Component API docs.

http://emberjs.com/api/classes/Ember.Component.html
<img width="518" alt="screen shot 2017-03-12 at 9 54 23 pm" src="https://cloud.githubusercontent.com/assets/558005/23841983/9e84dcec-076e-11e7-8689-076db60df807.png">

**Comment by pixelhandler** [comment]
@mike-north maybe this is still on the docs for 1.x views, http://emberjs.com/api/classes/Ember.View.html#toc_html-attributes

**Comment by yogipatel** [comment]
@mike-north Looks like they're back in 2.12: https://emberjs.com/api/classes/Ember.Component.html#property_attributeBindings

**Comment by rwjblue** [comment]
Awesome, thanks for checking on that @yogipatel!
