### ISSUE TITLE
Ember.Route#controllerFor api reference seems to be wrong

### ISSUE THREAD

**Issue by feanor07** [emberjs/ember.js#15004]
http://emberjs.com/api/classes/Ember.Route.html#method_controllerFor

controllerFor api documentation says "Returns the resolved model of the current route, or a parent (or any ancestor) route in a route hierarchy."; this seems to be wrong it returns the associate controller nothing realted with model I guess.

**Comment by feanor07** [comment]
opened an issue directly for the guides; hence closing this one.

**Comment by locks** [comment]
This was the correct place @feanor07 ;)

**Comment by feanor07** [comment]
my mistake :) sorry.

**Comment by mixonic** [comment]
Fixed in https://github.com/emberjs/ember.js/pull/15074
