### ISSUE TITLE
Ember.A seems to modify array instance

### ISSUE THREAD

**Issue by marcoow** [emberjs/ember.js#15020]
We're seeing a bug in the Ember Simple Auth dummy app (simplabs/ember-simple-auth#1260) that seems to be caused by the fact that ~Enumerable.uniq~`Ember.A` tries to modify the provided array. This only seems to affect addon projects where prototype extension is disabled (this is mostly an assumption for now though).

Reproduction steps:

```js
var array = ['a', 'a'];
Object.freeze(array);
Ember.A(array);

// =>
ember.debug.js:21542 Uncaught TypeError: Cannot add property nextObject, object is not extensible
    at Object.defineProperty (ember.debug.js:21542)
    at applyMixin (ember.debug.js:20576)
    at MixinPrototype.apply (ember.debug.js:20770)
    at Object.A (ember.debug.js:37397)
    at eval (eval at init (query-string.js:35), <anonymous>:1:7)
    at Class.init (query-string.js:35)
    at new Class (ember.debug.js:36118)
    at Function._ClassMixinProps.create (ember.debug.js:36306)
    at Class.buildQueryString (oauth2-code.js:110)
    at Class.buildUrl (oauth2-code.js:120)
```

This only seems to fail in addon dummy apps but not in real apps.

/cc @Turbo87

**Comment by stefanpenner** [comment]
I think its `Ember.A(array)` that is doing the modification

**Comment by marcoow** [comment]
Hm, right - @Turbo87 and me just debugged this and we were sure it was the `uniq` but you're right,

```
var array = ['a', 'a'];
Object.freeze(array);
Ember.A(array);
```

actually results in the same exception. Should I update the issue above?

I assume this is still a bug though as `Ember.A` should also not modify the passed array?

**Comment by Serabe** [comment]
[`Ember.A`'s definition when prototypes are not to be extended](https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/system/native_array.js#L141-L149) applies `NativeArray` to the object and that defines properties on it, so I would say this is suggested behaviour.

Did this behaviour changed between versions? If you extend prototypes, is it still there?

Thank you!

**Comment by stefanpenner** [comment]
`Ember.A()` has no choice but to modify the array prototype, even if frozen. That is the contract it has, if it cannot it will most likely produce downstream errors.

**Comment by Turbo87** [comment]
@stefanpenner @Serabe It says "Does not modify the original object." in the API documentation of that function though, which is a little misleading. If it said something like "Does not modify the contents of the array" it would be more clear, but this certainly does modify the array object by adding these properties.

I never knew that `Ember.A()` actually changed anything, I always thought it would just create some sort of wrapper objects that has all the necessary additional properties. Sort of like a `PromiseProxy` I guess...

**Comment by marcoow** [comment]
> One can think of `Ember.A(y)` as "casting" `y` as `Ember.A`.

Good to know - thanks!

I'd agree with @Turbo87 though that it might be good to update the docs. I was thinking as well that the passed object would not be touched in any way. I submitted a PR: #15032

**Comment by Serabe** [comment]
Reopening as docs issue. Thank you!

**Comment by rwjblue** [comment]
Closed by https://github.com/emberjs/ember.js/pull/15032.

**Comment by stefanpenner** [comment]
Ya it's strange. Those docs are accurate when prototype extensions are enabled, if they are disabled (like your addons default configuration) it does modify

**Comment by marcoow** [comment]
I guess the fix for actually making it so that the object wasn't modified at all would be to always clone the object before applying the mixin (if prototype extensions are disabled/the mixin hasn't already been applied on the prototype) but I guess the performance overhead for that is prohibitive?

**Comment by stefanpenner** [comment]
Ya. It's already mega costly. Copying would also likely break some code that expects the array to be The same.

Work should be done so that Ember.A can be phased out
