### ISSUE TITLE
Override default dataStore for specific route or model

### ISSUE THREAD

**Issue by Redsandro** [emberjs/ember.js#15023]
Is it possible to somehow change the store for a specific route? 

E.g. this **does not** work:
```js
export default Ember.Route.extend({
	store: Ember.inject.service('my-custom-store'),
	model() {
		return this.get('store').query('people');
	}
});
```

Overriding `store` does not seem to be possible. The default store is being used either way.

This **does** work:
```js
export default Ember.Route.extend({
	myStore: Ember.inject.service('my-custom-store'),
	model() {
		return this.get('myStore').query('people');
	}
});
```

Using a unique key for the custom store works fine. But most vendor plugins rely on `this.get('store')` to be available, and will request the data from the wrong store.

---

PS - I'm using a service to extend the dataStore with a custom adapter and serializer. It works, so it seems right. However, I haven't found any documentation on adding a store, so I am not sure if I'm using this the way it is intended.

```js
export default DS.Store.extend({
	adapterFor() {
		return this._super('my-custom-store');
	},
	serializerFor() {
		return this._super('my-custom-store');
	}
});
```

**Comment by Serabe** [comment]
Hello, @Redsandro. I am closing this since it is not an Emberjs bug. Please, go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

Thank you!
