### ISSUE TITLE
You attempted to access "nodeType" on a factory manager created by container#factoryFor. "nodeType" is not a member of a factory manager."

### ISSUE THREAD

**Issue by snewcomer** [emberjs/ember.js#15033]
While running a test

***
ember-source: 2.12.0
ember-data: 2.12.0
ember-cli: 2.12.0
***

<img width="925" alt="screen shot 2017-03-17 at 7 25 46 am" src="https://cloud.githubusercontent.com/assets/7374640/24048068/f46f056e-0ae4-11e7-9d4d-8def53b41ff6.png">

<img width="614" alt="screen shot 2017-03-17 at 7 27 09 am" src="https://cloud.githubusercontent.com/assets/7374640/24048077/00962fc0-0ae5-11e7-87d6-f2e1ff2c99d2.png">

**Comment by rwjblue** [comment]
Is it possible to create a demo showing the error? Either in ember-twiddle.com or a ember-cli app repo would work...

**Comment by snewcomer** [comment]
Yeah I should have done that before putting this up :(  I haven't been able to reproduce that error with a new app, but will keep debugging and playing around this weekend and open again/comment if I come to any solutions.

**Comment by lolmaus** [comment]
Ran into this cryptic issue when trying to do `store.createRecord()` in a component integration test.

Managed to work around it by using `store.push()` instead.

**Comment by lolmaus** [comment]
This issue is caused by `console.log`! :scream: 

Testem's `sendMessageToIframe` tries to `JSON.stringify(decycle(message, this.eventMaxDepth))`, `message` is a JSON-like object that contains an array of arguments originally passed to `console.log`.

Some arguments cause `decycle` to crash, you can see it in the trace of the top comment.

**Comment by lolmaus** [comment]
This may be related: https://github.com/testem/testem/issues/962

**Comment by lolmaus** [comment]
Started a new issue: https://github.com/testem/testem/issues/1105.
