### ISSUE TITLE
Cannot use (action 'actionName') on tag-less component

### ISSUE THREAD

**Issue by andreiciceu** [emberjs/ember.js#15031]
Hello,

It's currently not possible to send an action to a component, if tagName is set to null.
`ssertion Failed: You can not define a function that handles DOM events in the`

I want to use this in a component that is a wrapper for another component.

How could I be able to send the action?

**Comment by rwjblue** [comment]
It is very difficult to help out here without a more detailed explanation of what you are doing. At the moment this issue is not very actionable. In most cases, we need to see a demo (checkout ember-twiddle.com if you haven't seen it!) but sometimes code snippets can suffice.

**Comment by andreiciceu** [comment]
Hello,

This is an example of what I want to achieve

The base component:
```
//base-modal.js
...
actions: {
	ok(): {
		...
		this.get('okClick')();
	}
}
```

```
//base-modal.hbs
<div class="modal">
	<div class="body">
		{{yield}}
	</div>

	<div calss="footer">
		<button {{action 'ok'}}>OK</button>
	</div>
</div>
```


The modal with inheritance:
```
//child-modal.js
...
tagName: '',
actions: {
	modalSubmit() {
		//smth
	}
}
...
```

```
//child-modal.hbs
{{#child-modal okClick=(action 'modalSubmit') }}
	Content
{{/child-modal}}
```

What I want to achieve: send a named action from child-modal downwards to base-modal
With the current setup, I cannot use `(action 'actionName')` in child-modal.hbs, as the component has no DOM tag.

**Comment by kumkanillam** [comment]
I guess `ok(): {` this is not valid syntax. it would be awesome if you can provide reproduction in [ember-twiddle.com](http://ember-twiddle.com)

**Comment by andreiciceu** [comment]
Here is the twiddle (read comments in application.hbs for details)

https://ember-twiddle.com/6d4ef822384a06a252cdd55272d25a58?openFiles=templates.application.hbs

**Comment by kumkanillam** [comment]
Thank you for the twiddle. In your twiddle you are defining `submit` DOM event functions for `app-modal` component that's not supported when you use `tagName=''`  You can go through this [assertion test code](https://github.com/emberjs/ember.js/blob/7819409b7b6559e9fc0300a29e66a16356fb67a7/packages/ember-glimmer/tests/integration/components/fragment-components-test.js#L49) to confirm. I changed `submit` function name to `on-submit` everything is worked. here is the [twiddle link](https://ember-twiddle.com/607f0d5a4aff0788d6963e2c96a3473f?openFiles=templates.application.hbs%2C) . so this is not the ember bug. it's the price you have to pay when you use component with `tagName=''`

**Comment by andreiciceu** [comment]
@kumkanillam Didn't know that. Thank you, case closed
