### ISSUE TITLE
See about cleaning up OrderedSet

### ISSUE THREAD

**Issue by locks** [emberjs/ember.js#15041]
Source: https://github.com/emberjs/ember.js/blob/v2.11.0/packages/ember-metal/lib/map.js#L55

**Edited by @serabe with @locks consent**: See https://github.com/emberjs/ember.js/issues/15041#issuecomment-315065566 for latest information as of 2017-07-13.

**Comment by pixelhandler** [comment]
Not sure what actions are necessary regarding the comment `We plan to clean it up and add many tests soon.` means. What types of tests need to be added? I see https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/tests/map_test.js#L512-L527 What does clean it up mean, e.g. remove, polish, reorganize?

**Comment by mixonic** [comment]
@locks please provide more detail, or perhaps this can be closed.

**Comment by Serabe** [comment]
I created this #15119 and last thing I know is that some consensus was reached in core, and someone would update on the topic, but cannot find anything in notes.

**Comment by mixonic** [comment]
@Serabe from the conversation on that issue I think an addon is being requested as a transition plan for current users.

Would be great to land that PR. I'm still unclear about what this particular issue is tracking. Perhaps it has be superseded?

**Comment by pixelhandler** [comment]
@locks any update on this one?

**Comment by rwjblue** [comment]
Closing in favor of https://github.com/emberjs/ember.js/pull/15119
