### ISSUE TITLE
Cannot set property element of [object Object] which has only a getter

### ISSUE THREAD

**Issue by tiandavis** [emberjs/ember.js#15047]
Hi Folks,

Upgrading from ember-cli 2.9.1 to ember-cli 2.10.0, we're getting the following error as the app loads.

```
Uncaught TypeError: Cannot set property element of [object Object] which has only a getter
    at Object.defineProperty (ember.debug.js:20809)
    at new Class (ember.debug.js:35314)
    at Function.create (ember.debug.js:35614)
    at CurlyComponentManager.create (ember.debug.js:12048)
    at OpenComponentOpcode.evaluate (ember.debug.js:46862)
    at VM.execute (ember.debug.js:53440)
    at VM.resume (ember.debug.js:53419)
    at TryOpcode.handleException (ember.debug.js:53930)
    at UpdatingVMFrame.handleException (ember.debug.js:54110)
    at UpdatingVM._throw [as throw] (ember.debug.js:53823)
```

Tried creating a simplified ember-cli app to reproduce the issue, but couldn't reproduce the issue in the simplified app. Best we can tell, something changed between v2.9.1 and v2.10.0. :(

Any insight into what could cause this? Any thoughts on how I can resolve this?

Thanks Everyone!

RE: https://github.com/ember-cli/ember-cli/issues/6877

Output from `ember version --verbose && npm --version`:

```
ember-cli: 2.10.0
http_parser: 2.5.0
node: 4.2.6
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2e
os: darwin x64
2.14.12
```

**Comment by tiandavis** [comment]
Hi @rwjblue and Ember Team,

Turns out, we were having a similar issue to the folks in this ember.js issue thread https://github.com/emberjs/ember.js/issues/11125. 

For some time now, we've had a component we use to track clicks in our app for analytics reporting. It does things like:

```
{{#track-clicks element="#foo-bar"}}
      <a id="foo-bar" href='https://foobar.com' target='_new'>Foo Bar</a>
{{/track-clicks}}
```

We found that Ember components have a property called [element](http://emberjs.com/api/classes/Ember.Component.html#property_element), which indeed only has a [getter](https://github.com/emberjs/ember.js/blob/v2.12.0/packages/ember-views/lib/mixins/view_support.js#L192).

We've refactored our `track-clicks` component to use a property called `trackedElement` instead of `element` and everything works as expected now.

```
{{#track-clicks trackedElement="#foo-bar"}}
      <a id="foo-bar" href='https://foobar.com' target='_new'>Foo Bar</a>
{{/track-clicks}}
```

Side Note: I know we can toggle between different versions of the Ember Guides, but what's the best way to see different version of the [Ember API](http://emberjs.com/api/classes/Ember.Component.html)?

Thanks Folks!

**Comment by locks** [comment]
> Side Note: I know we can toggle between different versions of the Ember Guides, but what's the best way to see different version of the Ember API?

@tiandavis it is currently not possible, but we are working hard on a versioned api doc viewer that should be released soon! Drop by `#-team-learning` for a sneakpeek.

**Comment by tiandavis** [comment]
Thanks @locks!

**Comment by FutoRicky** [comment]
Same issue, had a component with a property called `element`. Changed it to `el` and everything working fine. Maybe the error message should be polished to handle this specific situation. Spent a couple of hours trying to figure out this issue. Thanks @tiandavis for this issue.
