### ISSUE TITLE
Allow running acceptance tests without jQuery

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#15063]
As part of the work of the work performed in https://github.com/cibernox/ember-native-dom-helpers to provide consistent jquery-free test helpers that work both in integration and acceptance I've found that acceptance tests don't work without jQuery.

The reason for that is (at least) this file: https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/setup_for_testing.js#L38-L44

The task is to feature-detect jquery and skip those lines if not present.

For those interested, you can see how to remove jquery from an ember-app in this commit: https://github.com/cibernox/ember-native-dom-helpers/pull/30/commits/5ebeeb61926240949b9a7a43bad9ebadde7dba95

**Comment by rwjblue** [comment]
I submitted #15065 for the specific thing mentioned, but I suspect there are more things that we need to do after that lands.

**Comment by pixelhandler** [comment]
@cibernox @rwjblue should this be in a RFC issue (not PR) instead of here? @Serabe are will still encouraging feature types of issues to go through the RFCs repo?

**Comment by rwjblue** [comment]
@pixelhandler - This isn't really adding a new feature at all.  Simply removing an error condition in one usage scenario.  We are definitely not saying that folks should drop jQuery (only they want to), and we are not modifying the default blueprint.

**Comment by mixonic** [comment]
Are there more items to cover here @cibernox, or can this issue be closed?

**Comment by rwjblue** [comment]
@mixonic - The first known issue was addressed but we need to test again against canary builds. I haven't had a chance yet TBH.

**Comment by cibernox** [comment]
I [just tried](https://github.com/cibernox/ember-native-dom-helpers/pull/48) and no, there is still more work to do.

**Comment by samjjc** [comment]
I would like to work on this. It might take a little time, though. I am new here. any advice to help me get started is welcome

**Comment by Serabe** [comment]
@cibernox ping!

**Comment by cibernox** [comment]
Can u ping me next week? This one I'm on the verge of collapse

**Comment by pixelhandler** [comment]
@cibernox does this issue need to stay open?

**Comment by cibernox** [comment]
Actually, no. Acceptance tests are fine, provided people don't use the built-in global helper (`find`, `fillIn`) but the ones in https://github.com/cibernox/ember-native-dom-helpers

I'll close it.
