### ISSUE TITLE
Ember 2.12 action handlers can fire twice for IE and Edge

### ISSUE THREAD

**Issue by workmanw** [emberjs/ember.js#15076]
Here is a JSBin: http://jsbin.com/cufupaw/edit?html,js,console,output

(JSBin instead of ember-twiddle because of IE)

If you click 'red', 'yellow' or 'blue' in chrome you'll notice the color of the text changes to green to reflect the "selected state", if you try this fiddle in IE it will not change. If you look at the JSBin console pane you'll see that the event handle logged that it was invoked twice. The first time toggled `selected: true`, the second back to false.

So why did this happen? The reason it happens is because the element with the action handler, also has a `class="{{if item.selected 'selected'}}"`. To understand what's happening you'll need to first look at: [event_dispatcher.js](https://github.com/emberjs/ember.js/blob/299c1ab3d804fd92b0ec9b9c2e7a1fa100335753/packages/ember-views/lib/system/event_dispatcher.js#L224-L238). Notice how it's looping over the element's attributes looking for an action handler. So here is the exact order of what happens:

1. Click
2. event_dispatcher finds the element and the action handler at `attributes.item(2)`
3. action handler is invoked and toggles state, which then changes the DOM by adding a class.
4. That DOM change shifts the action handlers position from `attributes.item(2)` to `attributes.item(3)`.
5. The action handler returns, the next loop moves to `attributes.item(3)` finding the exact same handler, and recalls it.

Here is screenshot of the first invocation of the action handler:
![image](https://cloud.githubusercontent.com/assets/825487/24371581/40026ea0-12f9-11e7-990f-ef10dc596d76.png)

Here is a screenshot of the second invocation of the action handler:
![image](https://cloud.githubusercontent.com/assets/825487/24371596/4a01577c-12f9-11e7-989a-51ec2d65c99e.png)

This works with Ember 2.11. So somewhere along the way something changed.

**Comment by workmanw** [comment]
So I bisected this and it turns out to that it was caused by this commit: https://github.com/emberjs/ember.js/commit/ce35e6cc68b11a5dd9ceb376b5ab03949b97af8f . Reading my original description and looking at the commit, it's obvious why it broke. But it was also a little bit of a coincidence that it just worked before. 

Honestly, I'm not sure why the loop over the element attributes continues after it finds a handler? I guess it's because you could have multiple `{{action}}` handlers? If that's the case it seems like the list be first filtered to matching action handlers, then each handler should be called.

CC: @GavinJoyce

**Comment by rwjblue** [comment]
I think the simplest fix would be to track the actions that have already been called during the single loop and if a given action were already ran, noop it.

**Comment by workmanw** [comment]
@rwjblue I'm 👍 on that. Shall I open a PR?

**Comment by rwjblue** [comment]
Yep, if you don't mind. Will need a test to help ensure we don't regress again in the future. I believe it should at least be `[BUGFIX release]`.

**Comment by workmanw** [comment]
@rwjblue Roger that! I'm on it, you'll have a PR tonight because it's an upgrade blocker for us. 

Side note, a test would be very easy to write, but does ember.js CI process test IE / Edge? Either way I'll test it, just curious.

**Comment by rwjblue** [comment]
Yes, we test in IE9, IE10, and Edge (as well as Chrome, Firefox, Safari, and phantom) in CI.

**Comment by Serabe** [comment]
@workmanw your PR has been merged. Can this be closed or is there anything left to do? Thank you!

**Comment by workmanw** [comment]
@Serabe Ooops, I thought it was autoclosed with the merge. Sorry about that.
