### ISSUE TITLE
TypeError when you fire replaceWith in route

### ISSUE THREAD

**Issue by michsindelar** [emberjs/ember.js#15072]
There is the TypeError when you fire replaceWith during the error action in route. I need to refresh route with changed query params when model promise is rejected.
My route action:

```
actions:{
  error: function(error, transition){
    if(transition.queryParams.qParam){
      transition.queryParams.qParam=null;
      this.replaceWith(transition.targetName, {queryParams: transition.queryParams});
    }
  }
}
```

Error:
```
TypeError: Cannot read property 'name' of undefined
    at Class._queryParamsFor (ember.debug.js:28689)
    at Class.finalizeQueryParamChange (ember.debug.js:26477)
    at Router.triggerEvent (ember.debug.js:29103)
    at trigger (ember.debug.js:56445)
    at finalizeQueryParamChange (ember.debug.js:58464)
    at Router.queryParamsTransition (ember.debug.js:57811)
    at Router.getTransitionByIntent (ember.debug.js:57720)
    at Router.transitionByIntent (ember.debug.js:57829)
    at doTransition (ember.debug.js:58431)
    at Router.transitionTo (ember.debug.js:57905)
```

**Comment by Serabe** [comment]
I am not able to reproduce it. This is [the twiddle with my try at it](https://ember-twiddle.com/74fc54e33dedc2478c2787db2c5e12b5?openFiles=routes.erroring.js%2C&route=%2Fsafe).

Can you send a reproduction, please?

**Comment by michsindelar** [comment]
Your twiddle is wrong because you're replacing "erroring" route by "safe" route. In my case I replaced erroring route with same route but with changed query params.
My router look like this:

```
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType,
  rootURL: config.rootURL
});

Router.map(function() {
  this.route('first', function(){
   this.route('second', function(){
     this.route('third');
   });
 });
});

export default Router;
```

The error is produced to console when your second route look like this:

```
import Ember from 'ember';

export default Ember.Route.extend({
  queryParams:{
    q: {}
  },

  model() {
    return Ember.RSVP.reject();
  },

   actions: {
     error(error, transition) {
       this.replaceWith(transition.targetName, { queryParams: { q: 'a' }});
     }
   }
});
```

I want to only replace the query param of second route and follow the transition.

**Comment by Serabe** [comment]
[I still cannot reproduce it](https://ember-twiddle.com/74fc54e33dedc2478c2787db2c5e12b5?openFiles=templates.application.hbs%2C&route=%2Fsafe%2Ferroring). Can you please send a reproduction that shows the issue in a Twiddle or a small repo?

Thank you

**Comment by michsindelar** [comment]
Yeah, here is ![repo](https://github.com/michsindelar/EmberIssue15072).

And  here is screen

![screen](https://cloud.githubusercontent.com/assets/22495823/26048587/0d119d60-3958-11e7-9097-973b08d8ef1a.png).

**Comment by pixelhandler** [comment]
@michaelklishin is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by pixelhandler** [comment]
Closing for now, feel free to re-open if you can reproduce in the current release of Ember.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
