### ISSUE TITLE
Ember.warn throws deprecation if optional argument is not specified

### ISSUE THREAD

**Issue by jelhan** [emberjs/ember.js#15096]
Following docs `test` argument of `Ember.warn` is optional but if it's not specified deprecation _ember-debug.warn-options-missing_ is thrown.

Following docs this syntax should work: `Ember.warn('A warning to display', { id: 'ember-debug.feature-flag-with-features-stripped' });`

**Comment by Serabe** [comment]
Thank you for your report!
