### ISSUE TITLE
route with capital letter not found, gives no feedback

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember.js#15108]
Example: https://ember-twiddle.com/72436e7401af89db7664788128ff446e

I spent a while debugging an issue. It turned out to be a camel-case route not rendering, but no feedback or error in the console. I did see a message in the console that said "template was not found" or something, but that didn't help me during my debugging session. I thought I had a swallowed error somewhere else that was causing the whole route to fail.

We should provide an error when this happens.

**Comment by netes** [comment]
I'm not sure if this should be treated as an issue. `ember generate` won't let you create uppercased routes and also the whole convention of naming particular elements, starting from routes and ending on components is based on lowercased names.
For me it looks like a perfect fit for a linter rule though. What do you think?

**Comment by netes** [comment]
I also found an identical issue here:
https://github.com/emberjs/ember.js/issues/14783

**Comment by kellyselden** [comment]
Closed as duplicate.
