### ISSUE TITLE
README.md for ember.js has a broken image at the top

### ISSUE THREAD

**Issue by jeffslofish** [emberjs/ember.js#15123]
The broken image links to http://emberjs.com/images/brand/ember_Ember-Light.png which doesn't exist.

![image](https://cloud.githubusercontent.com/assets/1240484/24833548/dc53bd96-1c80-11e7-9ed3-37beb07ecece.png)

**Comment by pythonquick** [comment]
Looks like that image is deployed at [https://emberjs.com/images/brand/ember_Ember-Light-e42a2b30.png](https://emberjs.com/images/brand/ember_Ember-Light-e42a2b30.png).

The image comes from the https://github.com/emberjs/website repository.

I guess we can just update the README.md file to link to:
[https://raw.githubusercontent.com/emberjs/website/master/source/images/brand/ember_Ember-Light.png](https://raw.githubusercontent.com/emberjs/website/master/source/images/brand/ember_Ember-Light.png)

**Comment by Serabe** [comment]
Thank you for the report!
