### ISSUE TITLE
async test helpers should respect ```fetch``` calls as well

### ISSUE THREAD

**Issue by manimis902** [emberjs/ember.js#15126]
So we are trying to integrate ```fetch``` APIs in our app, using ```ember-network```.
While running our tests we noticed that, ```andThen``` helper doesn't wait for ```fetch``` calls to finish.

After debugging we found that ember is only listening to ```xhr``` requests, in ```setupForTesting```
https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/setup_for_testing.js#L39

```fetch``` API doesn't seem to support global events like ```xhr```, so I'm not sure how trivial or complex it'll be to support fetch calls counter in testing.

**Comment by manimis902** [comment]
Found a way around this by maintaining a global fetchCount and using ```registerWaiter``` API.

```Ember.Test.registerWaiter(() => window.fetchCount === 0);```

**Comment by rwjblue** [comment]
See https://github.com/stefanpenner/ember-fetch/pull/25, this is not really a bug here in Ember though so I'm going to close this issue...
