### ISSUE TITLE
transitionToRoute() not calling model hook to refresh model when transitioning to parent route by providing the dynamic segments instead of model

### ISSUE THREAD

**Issue by newton3** [emberjs/ember.js#15120]
expecting it to work as excepted here - 
https://github.com/emberjs/ember.js/blob/65e66961c4cd7420c0a77ccae9592fd7793d4b74/packages/ember-routing/lib/ext/controller.js#L83

but seems like it is not happening. Is this a known issue or by design?

**Comment by Serabe** [comment]
Can you provide a twiddle reproducing this? Thank you!

**Comment by Serabe** [comment]
@newton3 ping!

**Comment by Serabe** [comment]
Closing this according to [our triage policy](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy). Please, provide a reproduction so we can follow up on this.

Thank you!
