### ISSUE TITLE
Template repeatedly added to DOM

### ISSUE THREAD

**Issue by MichalBryxi** [emberjs/ember.js#15130]
Problem: It's possible to create fairly simple Ember app that keeps spitting application template into DOM infinitely. See screenshot below:

---

<img width="999" alt="7a7c92c6-1e0d-11e7-887c-6e685485aea3" src="https://cloud.githubusercontent.com/assets/847473/24899501/694b219e-1e98-11e7-9893-ac62a9a37f36.png">

---

- Reproducible on: "ember-cli": "2.12.1"
- Seems to be fixed on: "ember-cli": "2.13.0-beta.2"

I'm reporting this issue just because 2.12 [is an LTS candidate](https://emberjs.com/blog/2017/03/19/ember-2-12-released.html#toc_changes-in-ember-js-2-12). Not sure what's the process here. Please feel free to close that if that's irrelevant.

I created sample app for that purpose: https://github.com/MichalBryxi/cryptopals.com/tree/ember-2.12-LTS. There is one caveat: It uses [ember-bootstrap](https://github.com/kaliber5/ember-bootstrap) library. I'm not sure how to reproduce that problem with bare Ember. I got a [conversation](https://github.com/kaliber5/ember-bootstrap/issues/298) with the addon author and he thinks this is Ember/Glimmer problem.

Observed conditions:
- ember 2.12.1.
- Put `bs-dropdown` component into your template with `toggle` component inside.
- Create `link-to` pointing to non-existing route
- Example of such can be found in [application template](https://github.com/MichalBryxi/cryptopals.com/blob/ember-2.12-LTS/app/application/template.hbs)

![screen shot 2017-04-11 at 08 41 15](https://cloud.githubusercontent.com/assets/847473/24900155/c9756474-1e9a-11e7-8cd0-e2526c2b5064.png)

**Comment by locks** [comment]
Hi @MichalBryxi, did you mean https://github.com/MichalBryxi/cryptopals.com/tree/bugreport_with_ember_2.12?

**Comment by MichalBryxi** [comment]
Hi @locks sorry for the confusing naming. The branch you mentioned was prior some cleanup I made for the purpose of this bugreport. I really meant https://github.com/MichalBryxi/cryptopals.com/tree/ember-2.12-LTS
Deleted all other branches (except for master). To make it less confusing.

**Comment by locks** [comment]
Hm, I was looking at https://github.com/MichalBryxi/cryptopals.com/blob/ember-2.12-LTS/app/templates/application.hbs, but you seem to be using pods and it happens to win.

**Comment by MichalBryxi** [comment]
😔  sorry for that. Altered the ticket description to make it more obvious.

**Comment by locks** [comment]
No worries, thank you for the reproduction repository! It'll make it much easier to diagnose.

**Comment by pixelhandler** [comment]
@MichalBryxi @locks is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by MichalBryxi** [comment]
Lastest LTS is "2.18.2". And that has the problem fixed (to my best knowledge). So I am happy closing this issue.
