### ISSUE TITLE
Bug: If hbs component name contains double underscore, ember can't find the template

### ISSUE THREAD

**Issue by lougreenwood** [emberjs/ember.js#15145]
Ember CLI `2.12.1`
Ember `2.12.0`

I use the BEM naming convention for my CSS components (http://getbem.com/introduction/), to keep things consistent I also would like to use the same naming scheme for my handlebars component templates.

e.g I'd like to use this name for a component: `_c-form__input`.

It seems that when I include a double underscore in a component name, Ember is unable to find this component and I see the following error in the console:

```Assertion Failed: A component or helper named "_c-form__input" could not be found```

If I rename the component to `_c-form-input` Ember is happy again.

**UPDATE**

It seems that placing two underscores anywhere in the component name triggers this, i.e `_c-form_input` also can't be found.

**Comment by locks** [comment]
Can you reproduce in https://ember-twiddle.com please? I don't seem able to. I'll just remind that templates starting with an underscore are supposed to be partials.

**Comment by Serabe** [comment]
@lougreenwood ping

**Comment by Serabe** [comment]
Closing this according to [our triage policy](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy). Please, provide a reproduction so we can follow up on this.

Thank you!
