### ISSUE TITLE
Internet Explorer (v11): Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by mk-conn** [emberjs/ember.js#15154]
I was about to deploy my ember app to our testing environment where I am able to test in Internet Explorer and this "browser" comes up with an error. I tracked it down to 

ember.js/packages/ember-metal/lib/error_handler.js

```
// To maintain stacktrace consistency across browsers
let getStack = error => {
  let stack = error.stack;
  let message = error.message;

  if (stack && !stack.includes(message)) {
    stack = `${message}\n${stack}`;
  }

  return stack;
};
```
But I don't have no clue how to fix it - I don't know If this is something caused by my code... In the IE debugger the variable 'error' is undefined... In every other browser there is no issue... :-/

**Comment by rwjblue** [comment]
Good catch! What version of Ember was this against? Would you mind taking a crack at a PR that fixes?

If you are interested, the fix would be to change [this line](https://github.com/emberjs/ember.js/blob/98e01ceb9308433023d4e0bc371422526082b2f7/packages/ember-metal/lib/error_handler.js#L9) to `if (stack && stack.indexOf(message) === -1) {`.

**Comment by mk-conn** [comment]
The Ember version is 2.12.1. I will try to create a PR ...
