### ISSUE TITLE
class ember-transitioning-out is set on wrong link

### ISSUE THREAD

**Issue by initram** [emberjs/ember.js#15158]
When I transistion from a route "/x/y/1/z" to "/x/y/2/z" then a link to "/x/y/2/z" on the target page has the ember-transitioning-out set even though i came from "/x/y/1/z".

I am using this to keep track of my current tab, and to not wish to highlight a tab that has ember-transitioning-out set as the user does not see the content for this tab yet.

I looked a bit at the source and test code, and could see there were only "positive tests" written for ember-transitioning-out.

Ember: 2.8.3
ember-cli: 2.10.0
node: 6.2.2
os: win32 x64

**Comment by topaxi** [comment]
Might be related to #12419, I've observed similar issues with links to the same route but different model.

**Comment by sandstrom** [comment]
Likely closed in https://github.com/emberjs/ember.js/pull/16335.

If not, feel free to re-open, ideally with a failing test case or a PR to fix the bug.
