### ISSUE TITLE
Unable to pass a helper as a callback when composing helpers

### ISSUE THREAD

**Issue by mwpastore** [emberjs/ember.js#15167]
Now that closure actions and composable helpers are all the rage, there's one use case that is not currently possible in Ember. Consider an app with the ember-composable-helpers and ember-math-helpers add-ons installed. The developer wants to sum an array of numbers and output the results. They add this to their template:

```hbs
{{reduce (action 'sum') 0 (array 1 2 3)}}
```

And this to their component/controller:

```javascript
actions: {
  sum: (a, b) => a + b
}
```

`reduce` sets the initial value to 0, registers the `sum` action as its callback, and is off to the races. The developer moseys on to the next task. 

Some time later, the developer has a lightbulb moment: "Wait a minute, I already have a function that takes two numbers and returns their sum: ember-math-helpers' `add` helper!" Wanting to stay DRY, they remove their bespoke `sum` action and dutiful amend the template change:

```hbs
{{reduce (action 'add') 0 (array 1 2 3)}}
```

Except that doesn't work, because `add` isn't an action on their component/controller. They try this instead:

```hbs
{{reduce (action add) 0 (array 1 2 3)}}
```

Which doesn't work either, because `add` is `undefined` in this context (i.e. when accessed like a property). 

It turns out that there's no way ([that I can find](https://ember-twiddle.com/7ffae736754da6361cc76e697c50bfb2)) to pass `add` as a callback for `reduce`. I'd like to propose that we introduce a `helper` helper that works like the `component` helper and can be used as needed to 1. close around helpers and 2. dynamically look up helpers. 

1. For the above use case:

    ```hbs
    {{reduce (helper 'add') 0 (array 1 2 3)}}
    ```

1. And, for example, given a property `inflector` that may be set to either `pluralize` or `singularlize`:

    ```hbs
    {{helper inflector 'widget'}}
    ```

My apologies in advance for using incorrect terminology and/or reporting this POLA-violating "bug" in the wrong place.

**Comment by Serabe** [comment]
Hello, @mwpastore. I am closing this since it is not an Emberjs bug. 

You might be interested on emberjs/rfcs#208

Thank you!

**Comment by mwpastore** [comment]
That's exactly what I was looking for. Thanks @Serabe!
