### ISSUE TITLE
In 2.13-beta.2, an item with an undefined key in #each helper throws an exception: EnterWithKeyOpcode expects a populated key register

### ISSUE THREAD

**Issue by paulcwatts** [emberjs/ember.js#15170]
This may not be a bug, but more of a behavior change due to Glimmer 2.2.

In previous versions of Ember, specifying a key to the #each helper that didn't exist in the iterated items seemed to work. In 2.13, it throws an exception. I created a repo that shows it:

https://github.com/paulcwatts/ember-bug-missing-key-each-helper/blob/master/tests/integration/components/key-opcode-test.js

You can use ember-try in this repo and it works on ember-release, but not on ember-beta or ember-canary.

I also created a Twiddle, although for some reason it can't switch to beta: https://ember-twiddle.com/3f1fd272cc0357e29258f6e4c72f177d

The exception thrown is "EnterWithKeyOpcode expects a populated key register"

```
        stack: >
            exception@http://localhost:7357/assets/test-support.js:7329:46
            adapterDispatch@http://localhost:7357/assets/vendor.js:52167:22
            dispatchError@http://localhost:7357/assets/vendor.js:30360:23
            invokeWithOnError@http://localhost:7357/assets/vendor.js:12772:14
            flush@http://localhost:7357/assets/vendor.js:12828:15
            flush@http://localhost:7357/assets/vendor.js:12952:20
            end@http://localhost:7357/assets/vendor.js:13022:28
            run@http://localhost:7357/assets/vendor.js:13136:19
            run@http://localhost:7357/assets/vendor.js:34988:32
            render@http://localhost:7357/assets/test-support.js:8429:27
            http://localhost:7357/assets/tests.js:148:16
            runTest@http://localhost:7357/assets/test-support.js:3291:34
            run@http://localhost:7357/assets/test-support.js:3277:13
            http://localhost:7357/assets/test-support.js:3469:15
            advance@http://localhost:7357/assets/test-support.js:2954:26
            begin@http://localhost:7357/assets/test-support.js:4645:27
            http://localhost:7357/assets/test-support.js:3839:11
        message: >
            Error: EnterWithKeyOpcode expects a populated key register
```

Like I said, I don't know if this is a bug _per se_ or some side-effect of Glimmer v2.2. It's certainly different behavior. In some ways the new behavior is more desirable, since it showed me a potential bug! However, a more helpful error message might be useful here.

**Comment by rwjblue** [comment]
I think throwing is the correct behavior, but the error message should be much better. 😸

**Comment by paulcwatts** [comment]
I don't mind having a go at fixing the error, but I'm not exactly sure where to begin. I can certainly write a failing test if that helps. That looks like it may be a Glimmer error, though? Would it be better in that repo?

**Comment by gudyo** [comment]
I'm an Ember newb and i get this error with 2.14. What does it mean :)?

**Comment by rwjblue** [comment]
When Ember's `{{#each` helper iterates over items, it uses a key for each item to represent the DOM of each iteration (which is then used for re-rendering and whatnot). By default, Ember will choose the key for you automatically (either by using a primitive value's value, or by using `Ember.guidFor(item)`).  In that default scenario, you should never see this error.

You will only see the error if you instruct the `{{#each` helper to use a **specific** key off of the items being iterated.  You would do that like:

```hbs
{{#each posts key="id" as |post|}}
{{/each}}
```

If any of the items in the `posts` array have `undefined` as a value for the `id` property, this error will be thrown.

**Comment by rwjblue** [comment]
That being said, as I mentioned above I think the error is actually correct so I'm going to close this issue...

**Comment by gudyo** [comment]
Thank you @rwjblue
