### ISSUE TITLE
`controller.replaceRoute` does not work in an Engine

### ISSUE THREAD

**Issue by spencer516** [emberjs/ember.js#15179]
When using the [`replaceRoute`](https://emberjs.com/api/classes/Ember.Controller.html#method_replaceRoute) method in a Controller inside of an Engine, the engine's mount point is not prefixed to the route name leading to a "not route defined" error. 

It appears it's a small bug that unintentionally used the incorrect argument. I've opened a PR here:

https://github.com/emberjs/ember.js/pull/15176

**Comment by Serabe** [comment]
Thank you!

**Comment by spencer516** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/15176
