### ISSUE TITLE
Aliased actions can be used in component templates without a controller

### ISSUE THREAD

**Issue by student020341** [emberjs/ember.js#15196]
Just want to confirm whether this is a feature or a bug based on the documentation before I end up using it all over my project. This is using an action in a component template passed down from another template's controller so that the component does not have to have a controller if all it's doing is performing an action from a parent controller. 

The main concern is... will this be patched out in the future? 

Example template

```
{{directory/template-name
    variable_alias = variable_from_controller
    action_alias = (action "action_from_controller")
}}
```

template-name component example

`<button {{action action_alias}}>{{variable_alias}}</button>`

**Comment by Serabe** [comment]
I'm not sure I understand what you are saying. Can you try to reproduce it in a Twiddle? So far it seems normal code to me.

**Comment by student020341** [comment]
If it looks normal, then this issue can be closed. I was merely having difficulty finding a documented example of passing an action to a component template and using it like that. All of the examples I found involved a controller, [like this](https://guides.emberjs.com/v1.10.0/components/sending-actions-from-components-to-your-application/). 

Do you have any examples you could link that pass actions to a component and use them without a controller, like the short snippet I posted? Thanks!

**Comment by Serabe** [comment]
Yep. They are called [closure actions](http://miguelcamba.com/blog/2016/01/24/ember-closure-actions-in-depth/).

Thank you!

**Comment by student020341** [comment]
Many thanks for the link, this is exactly what I was looking for.

> But did you know that you can extract any function from your component by passed an unquoted reference?
