### ISSUE TITLE
Ember appears indifferent to closing brace in computed property brace expansion

### ISSUE THREAD

**Issue by kennethdavidbuck** [emberjs/ember.js#15201]
This doesn't seem like a big deal, but I noticed that, when it comes to computed properties, Ember seems indifferent to the presence of a closing brace when doing brace expansion. Please see the following twiddle that demonstrates the behaviour (I would not expect model.bar or model.baz to be watched and updated, given that the end of the brace expansion is missing)

https://ember-twiddle.com/dc26de45263b444157865c7c7f6b7d28?openFiles=controllers.application.js%2C

**Comment by Serabe** [comment]
Thank you, this is fixed in 2.13. I am adding a test for this case and checking if a fix should be backported to 2.12.

Thank you!

**Comment by kennethdavidbuck** [comment]
Thats great, thank you!

**Comment by Serabe** [comment]
@stefanpenner any reason to keep this open?

**Comment by kennethdavidbuck** [comment]
Gonna assume it's safe to close this now :)
