### ISSUE TITLE
[Bug] Input checkbox value returns "on" in Internet Explorer 11

### ISSUE THREAD

**Issue by cspanring** [emberjs/ember.js#15203]
Binding the `value` attribute of an `input` (checkbox) tag to a controller/component property seems broken in IE11.

See a minimal example here: https://cspanring.github.io/ie11-input-value/ ([code](https://github.com/cspanring/ie11-input-value))

template:
```
<input value={{inputValue}} type="checkbox" onclick={{action "getCheckboxValue"}}>My value is {{inputValue}}
```

controller:
```
inputValue: 3,

  actions: {
    getCheckboxValue() {
      let value = document.querySelector('input[type=checkbox]').value;
      // in IE11 value will be "on"
      alert('My value is: ' + value);
    },
  },
```

**Comment by Serabe** [comment]
If you take Ember out of the equation, does it return 3?

**Comment by cspanring** [comment]
Yes, if I set the `value` attribute in the template just to `3` IE11 will return it correctly.

Also, tried to replicate in vanilla javascript: http://output.jsbin.com/xutilididi/1/

If you have a few pointers or instincts where to start looking, I'm happy to take this on and try to triage it a little bit further.

**Comment by Serabe** [comment]
Can confirm this. The problem is that `value` is not being set in the element at all. It can be checked looking at the element in the inspector panel.

**Comment by thirdwheel** [comment]
Perhaps a more pertinent question - if you change the order of the value and type attributes, do you get the same behaviour?

**Comment by aafaq-hassan-confiz** [comment]
I am having same issue in internet explorer 11. Yes,  the problem is that value is not being set in the element at all. It is issue with any element whether it is checkbox or not. If a constant value is assigned then it is being set like "value=3", but value binding is not working at all like "value={{somevar}}". I am using ember-cli 3.1.4

**Comment by jherdman** [comment]
Hey friends. I've worked around this in the past with radio buttons too (see #14712). The gist is that IE11 cares a _lot_ about the order of your attributes. In general I've wrapped up native radio buttons in a component that has a `didRender` hook that looks like this:

```javascript
  didRender() {
    // IE11 needs to have it value re-set
    this.element.value = this.value;
  },
```

**Comment by santanapaulo** [comment]
Any news on this? I am getting the same issue when I run tests in IE 11, which checks the values of my checkbox's.

![image](https://user-images.githubusercontent.com/15819810/44218378-f9309880-a14f-11e8-9ebb-76ea7ec4e43a.png)

**Comment by santanapaulo** [comment]
@jherdman Can you help me find a way to wrap up the native ember-radio-button?

**Comment by christianhaller3000** [comment]
> I stumbled on a solution for this. In IE11, if you set the value then change it to a checkbox, it will erase the value. So:
> 
> ```js
> oCheckBox=document.createElement('input');
> oCheckBox.name='testcheckbox';
> oCheckBox.value='123456789';
> oCheckBox.type='checkbox';
> alert(oCheckBox.value);
> ```
> 
> This will show the correct value in Chrome, but will say 'on' in IE11. The following will ensure correct behaviour in both browsers:
> 
> ```js
> oCheckBox=document.createElement('input');
> oCheckBox.name='testcheckbox';
> oCheckBox.type='checkbox';
> oCheckBox.value='123456789';
> alert(oCheckBox.value);
> ```
> 
> To quote someone in a chatroom when answering a hairy IE question, "did you properly light the incense? In which order did you chant and throw the chicken bones?" Instances like this make this question less silly the more insanity you find.

Thank you so much @thirdwheel 
You saved my day!

**Comment by locks** [comment]
Long live [IE11](https://blog.emberjs.com/ember-4-0-released/) 🙌
