### ISSUE TITLE
Parent route keeps calling `model` hook when visiting child routes

### ISSUE THREAD

**Issue by tsteuwer** [emberjs/ember.js#15200]
I'm not sure if this is a bug or something I'm just not understanding.

Say I have the following routes defined:

```
this.route('index');
this.route('person', {
    path: 'person/:id',
}, function() {
   this.route('edit');
});
```

My goal here is so that people can send direct links to edit a person. The issue comes in to the fact that the "person" route keeps calling the `model` function every time you click a link to edit the person. When this happens, the UI goes back to the loading state until it is reloaded.

Here's an example showing the `model` hook continuing to be called when visiting a child route:

https://ember-twiddle.com/c990e306ae2dcd4801e92c7f2f3dd243?openFiles=routes.person.js%2C&route=%2Fperson%2F53

Is this a bug or am I just not understanding how this works?

Here's the scenario:

User visits /people/
User clicks /person/5 - Page loads with info about person 5.
User clicks "edit" link which uses link-to helper to visit /person/5/edit - It shows the edit form next to the display of the person from the /person/5 route.
User can share the edit link.

**Comment by btecu** [comment]
There's an error in your code or an misunderstanding.

Your `person` route is `/person/53` from `{{#link-to "person" "53"}}`.

When you go the child route, you're setting asking it to go to `/person/55/add-stuff` in `{{#link-to "person.add-stuff" 55}}`.

`53 !== 55`.

**Comment by tsteuwer** [comment]
I actually found the issue. There was a task update in the didTransition. I thought the didTransition was only when you enter the route, not when you enter a child route.

Thanks for your help @btecu.
