### ISSUE TITLE
[Bug] service is an unknown injection within ApplicationController

### ISSUE THREAD

**Issue by bcardarella** [emberjs/ember.js#15209]
On Ember 2.13

I generated a new service: `ember g service tracking`

I have a custom ApplicationController `app/controllers/application.js`

The controller is just:

```js
import Controller, { inject }  from '@ember/controller';
import { get, getProperties } from '@ember/object';

export default Controller.extend({
  tracking: inject(),

  init() {
    this._super(...arguments);
    let tracking = get(this, 'tracking');
  }
});
````

But I get the error: `Attempting to inject an unknown injection: 'controller:tracking'`

**Comment by Turbo87** [comment]
@bcardarella I guess you need to import `inject` from `@ember/service` instead for this to work 😉

**Comment by bcardarella** [comment]
yeah, that was it. Coding at 4am has its penalties.
