### ISSUE TITLE
Production builds are running `runInDebug` callback.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#15212]
Using `Ember.runInDebug(someCallback)` is supposed to only call the callback if we are running in a debug build. It seems that we are currently running `runInDebug` callbacks for production builds.

Seems to be broken from 2.13+:

* Canary Demo: https://jsbin.com/soqemot/edit?html,js,output
* 2.13 Demo: https://jsbin.com/polotaj/edit?html,js,output

This is working properly in 2.12: https://jsbin.com/nayifa/edit?html,js,output.

**Comment by stefanpenner** [comment]
I thought I saw this, thought I built the wrong thing... guess i wasn't crazy.

**Comment by bjornharrtell** [comment]
Bisected to first bad commit db3394a04cc896e65bf22ddeefdfa24822a2e855, which had some breakage fixed with 6401f38f990c99f99937e197e9dd7eeabe563bf9 which exhibits this issue.
