### ISSUE TITLE
isCausedByInitialTransition property on Transition is either null or undefined

### ISSUE THREAD

**Issue by dbbk** [emberjs/ember.js#15214]
In my route's `redirect` hook, I'm inspecting the second argument `transition` to determine whether or not it was the first page a user landed on in the request. If it is, the `isCausedByInitialTransition` property of `transition` is `undefined`. If it is not, the property is `null`.

This method works, but it feels like a hack. Should this property not return either `true` or `false`? I've not encountered a situation where it does.

**Comment by rwjblue** [comment]
The intent of `isCausedByInitialTransition` was not actually to allow you to detect if the Transition itself is from the initial transition, but rather to detect if the transition was _caused_ by the initial transition (e.g. if the initial transition did a redirect that second redirect transition would be `isCausedByInitialTransition: true` but the first would not).

I do think that `isCausedByInitialTransition` seems better as a straight up `true` / `false` value though. Would appreciate a pull request fixing that [over here](https://github.com/tildeio/router.js/blob/master/lib/router/transition.js#L44-L54).  Note that when you do fix it, you will no longer be able to detect the initial transition itself so you may want to add another flag for that specifically.  I think that the following would do the trick:

```js
this.isInitialTransition = !previousTransition && router.currentSequence === 0;
```

---

I'm going to close this, as I do not believe it is a bug but I'm happy to help iterate with you over in router.js if you'd like to make a PR to make this a bit better...
