### ISSUE TITLE
EmberError or Error

### ISSUE THREAD

**Issue by lovetingyuan** [emberjs/ember.js#15237]
emberDebug does not contain `EmberError` key, but emberDebug.EmberDebug is called
you should change `emberDebug.Error` to `emberDebug.EmberError`

**Comment by rwjblue** [comment]
@lovetingyuan Awesome, thank you for reporting!

@Serabe - Maybe you have time to look at this?

**Comment by rwjblue** [comment]
@Serabe -
 I think https://github.com/emberjs/ember.js/commit/c845e809f64a719175546afe50118496f93237af#commitcomment-22113411 is related...

**Comment by Serabe** [comment]
The bug was added here https://github.com/emberjs/ember.js/commit/db3394a04cc896e65bf22ddeefdfa24822a2e855
Simple mistake when you are moving so many imports. Added a PR fixing it.

Thank you all!
