### ISSUE TITLE
"undefined is not an object (evaluating '_ember.default.deprecate.apply')" on beta and canary

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember.js#15236]
I started seeing this in Travis today on beta and canary:

`TypeError: undefined is not an object (evaluating '_ember.default.deprecate.apply')`

https://travis-ci.org/kellyselden/ember-tree/jobs/231351897#L1631

Last successful build was 2017-05-11T06:19:30Z, first time this error popped up 2017-05-11T22:49:00Z.

**Comment by kellyselden** [comment]
This is almost certainly an ember data issue

https://github.com/emberjs/data/issues/4983

**Comment by rwjblue** [comment]
Unsure @lukemelia reported similar error in another comment. I think this may be due to my recent (largeish) refactoring of ember-debug package (landed this morning sometime).

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/15224
