### ISSUE TITLE
IE11 and Edge have WeakMap issues

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember.js#15249]
Code like this:

```js
import Ember from 'ember';

export default Ember.Controller.extend({
  window: Ember.computed(function() {
    return window;
  }),
  url: Ember.computed.readOnly('window.location.href')
});
```

Gives the error:

![screen shot 2017-05-17 at 1 17 45 pm](https://cloud.githubusercontent.com/assets/602423/26174134/3d86d170-3b03-11e7-9f99-638b596bf6df.png)

Repro:

https://github.com/kellyselden/edge-weakmap-bug/commit/b9fc14d23eca226af127bab2d56cc2c146fb56b3

While debugging, I determined `key` in the error is `window.location`. It's most likely `window.location` is some kind of special object in Edge, and Edge's WeakMap implementation doesn't recognize it as a real object.

**Comment by stefanpenner** [comment]
Sounds like a bug in edge/chakra... cc @nolanlawson / @jdalton.

**Comment by jdalton** [comment]
Thanks for the heads up! This looks like left over from the host object 🐛 of old.

**Comment by stefanpenner** [comment]
@jdalton where is best for us to open an issue (or track said progress) ?

**Comment by stefanpenner** [comment]
reduced example is most likely:

```
let map = new WeakMap();
map.set(window.location, '1); // likely throws
```

**Comment by jdalton** [comment]
Let's file it on Chakra ([their github repo](https://github.com/Microsoft/ChakraCore/issues)) and see if it gets pushed back to Edge. Since it's dealing with the DOM hosted object `location` it can be a toss up.

Yes, your reduced repro is sufficient. (it throws)

**Comment by stefanpenner** [comment]
@jdalton awesome thanks, issue opened -> https://github.com/Microsoft/ChakraCore/issues/2983

@kellyselden thanks for the bug report, I don't think we (ember) should work around this issue. 
 
Rather the Chakra/Edge Folks  will have to fix, and you can work around it by not creating chain nodes to those objects (they turn out to be non-observable anyways.

```js
url: comptued(() => window.location.href).readOnly()
```

**Comment by stefanpenner** [comment]
IE Edge issue: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12112572/
