### ISSUE TITLE
Possible documentation issues container.factoryFor and applicationInstance.lookup

### ISSUE THREAD

**Issue by Emrvb** [emberjs/ember.js#15241]
Hello,

The container.factoryFor (https://emberjs.com/api/classes/Container.html#method_factoryFor) description states: "The consumer of the factory is responsible for the destruction of any factory instances" this is a bit unclear to me. I initially read this as "you need to destroy the instance of the factory" but I believe I should interpret this as "destroy instances created by the factory" which makes perfectly sense. It could be only I experience this ambiguity because I'm not a native English speaker.

I think it's good thing to remind developers that they need to destroy manually created objects so I'd suggest to add a similar remark to the description of applicationInstance.lookup (https://emberjs.com/api/classes/Ember.ApplicationInstance.html#method_lookup) that instances looked up with option { singleton: false} need to be destroyed manually.

**Comment by josiahbryan** [comment]
I could be just missing something here re: Javascript - but don't objects get destroyed/GCd when they fall out of scope? What situations would there be that need manual destruction of an object as opposed to just letting them "go away" when they fall out of scope?

**Comment by Emrvb** [comment]
@josiahbryan 

As you correctly point out, from a language point of view there is no real destruction in Javascript. But...

If you have observers and/or bindings tied to your object they could (read: probably will) prevent your object from falling out of scope. The destroy() method schedules "destruction", where Ember will clean these up for you so the object can get properly GCed.

Additionally, by having the isDestroyed flag set, you can no longer "set()" a property on the object. So when you accidentally have a reference to the object lingering and try to use it, you get a nice exception that implies you have a leak. (not as effective as it sounds, because personally I rarely try to set a property on a object that "should have been dereferenced" by design, but on occasion I do forget to actually dereference).

When your application can complete rely on features build into the framework (including addons like ember-data) I don't think there is ever any need to call destroy() manually. This is all done behind the scenes. However, when you're creating instances of objects yourself, you should once again take life cycle into consideration.

**Comment by rwjblue** [comment]
Agreed, the change suggested by this issue is definitely a welcome change.
