### ISSUE TITLE
2.13 custom elements regression once more

### ISSUE THREAD

**Issue by bjornharrtell** [emberjs/ember.js#15258]
Seems https://github.com/glimmerjs/glimmer-vm/issues/453 was only partially fixed.

I get `Error: expected an implementation for 6` with:
http://jsbin.com/nesosateji/edit?html,js,output

And I get `Error: expected an implementation for 1` with:
http://jsbin.com/batohesuyu/edit?html,css,js,output

**Comment by bjornharrtell** [comment]
Tracking issues for Glimmer:
https://github.com/glimmerjs/glimmer-vm/issues/493
https://github.com/glimmerjs/glimmer-vm/issues/494

**Comment by rwjblue** [comment]
Awesome, thank you!

**Comment by bjornharrtell** [comment]
JSBin links was wrong here (was corrected only in the glimmer issues), is now fixed.

**Comment by rwjblue** [comment]
Thank you

**Comment by bjornharrtell** [comment]
Bumping to 2.13.3 in the bins shows that this issue is no more:

http://jsbin.com/sesukafewa/edit?html,js,output
http://jsbin.com/lokuqacebe/edit?html,css,js,output
