### ISSUE TITLE
URL encoding does not use encodeURIComponent

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#15266]
Using Ember 2.13.2. This is more of a question than an issue. If I have the following route:

```javascript
this.route('foobar', { path: '/:id' });
```

And in `routes/foobar.js` I have:

```javascript
model (params) {
  console.log(params);
}
```

When I hit `/[@:` I will get `/%5B@:` in the browser URL and `id: "[@:"` in the console. If I hit `/%5B%40` I will get `/%5B@` in the browser URL and `id: "[@"` in the console. The console.logs are correct, but I'm wondering about the browser URL. Why are some symbols encoded? Why are some symbols decoded? Why isn't this consistent with `encodeURIComponent` which will actually encode all of these symbols (`[`, `@` and `:`)? Do you expose anywhere the function for encoding that you use internally so I could use it for my own routes which have globbed dynamic segments?

There is no "issue" here, it's just a strange inconsistency. And none of this is documented anywhere. :)

**Comment by Serabe** [comment]
Hello, @boris-petrov. I am closing this since it is not an Emberjs bug. Please, go to #-help or #dev-router channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

Thank you!
