### ISSUE TITLE
[FEATURE query-params] Allow associative array as parameter

### ISSUE THREAD

**Issue by homersimpsons** [emberjs/ember.js#15286]
I've got an associative array:
`parameters = { limit: 30, search: "test", page: 2 }`
Then I would like to be able to do a `(query-params parameters)` that would result in a `?limit=30&search=test&page=2`

Additionnaly a must have would be to be able to update the element, e.g. `(query-params parameters page=17)` would result in `?limit=30&search=test&page=17`
Or `(query-params parameters page=null)` would result in `?limit=30&search=test`

Currently setting `(query-params params=parameters)` result in `?params=[object Object]` it should, in my mind result in `?params[limit]=30&params[search]=test&params[page]=2`

**Comment by Serabe** [comment]
Hello, @homersimpsons. I am closing this since it is not an Emberjs bug.

Feature requests need to follow the process explained here https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature

Thank you!
