### ISSUE TITLE
Ember assertions can result in object computeds running before object init / Service injections do not appear to be idemponent

### ISSUE THREAD

**Issue by kennethdavidbuck** [emberjs/ember.js#15299]
Ok, I have a bit of a strange one here.  Ill do my best to explain this, so here goes:
1. It is known that Ember runs assertions when attempting to set a property on an object. An example assertion is whether or not the object having its property set is destroyed or not.
2. When making assertions Ember will eagerly call the #toString method of said object in order to prepare an informative message should the assertion fail.

3. It is possible that an ember object may call a computed property inside of its toString method.

In most situations this does not lead to unexpected behaviour, however I have come across a scenario that leads to an objects computed property getting computed before its init method has had a chance to run, leading to erroneous and unexpected behaviour. The scenario is as follows:

1. A custom object (non ember data model) has been registered into the container, which calls one of its own computeds in its #toString method.

2. The custom object uses Ember.inject.service('store') such that it has access to the store

3. Unknowingly there is a redundant initializer injection that runs and does the same work (injects the store on that property - I figured this would be idempotent)

4. The factory for the object is looked up using  #factoryFor on the container and then an instance is created.

**Result**: The redundant initializer leads to Ember calling Ember.set when providing the store, which leads to an assertion that checks whether or not the object has been destroyed. This in turn leads to an eager calling of the objects #toString method, which calls one of the objects own computeds before its own init method has run. In my particular case the computed needed a property that was being set in init and so was now computing an erroneous value.

If anything, this scenario raises the question as to whether it should be considered "safe" to eagerly call any methods on an Ember object before it is known that its init method has been executed. This is especially true in this case because the method is being called eagerly "just in case" the assertion fails. Further to that, I would expect that a redundant injection would be idempotent, where in this case it has, what appear to be, unintended side effects.

Please see the attached [twiddle](https://ember-twiddle.com/c7922e256f08e6db0b44c9ce3a0d39de?openFiles=tests.acceptance.my-acceptance-test.js%2C) that has a failing acceptance test demonstrating the scenario I am describing. I am more than happy to write and submit an actual failing test, but I wanted to get some feedback on the twiddle before proceeding.

Thank you for taking the time to look at this!

**Comment by rwjblue** [comment]
Thank you for writing up such a detailed issue! The current state of assertions are not ideal for the exact reason you mentioned: we are eagerly calculating the messages which often turns out to be costly.  

I had created https://github.com/chadhietala/babel-plugin-debug-macros/issues/36 to address this a while back, but I forgot to actually get around to fixing it.  I spent some time today digging in and submitting a PR to fix https://github.com/chadhietala/babel-plugin-debug-macros/pull/39.

Once that lands, and we update the version of that plugin that Ember's build uses the transpiled output for, the output for this assertion:

```js
  assert(`calling set on destroyed object: ${toString(obj)}.${keyName} = ${toString(value)}`, !obj.isDestroyed);
```

Will now become:

```js
(true && !(!obj.isDestroyed) && assert(`calling set on destroyed object: ${toString(obj)}.${keyName} = ${toString(value)}`, false);
```

As you can see, this would result in the message portion only being generated when it is actually required.

**Comment by kennethdavidbuck** [comment]
My pleasure @rwjblue , and thank you for the quick reply. So, is it safe to say that I should just close this issue and wait the fix to land?

**Comment by rwjblue** [comment]
Landed those changes upstream, and submitted a PR updating Ember to use the newer babel plugin version in #15310.
