### ISSUE TITLE
{{#each-in}} does not handle ES6 Maps

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#15304]
I just came up with a situation where I wanted to iterate the keys of an object having guaranteed order, but objects per spec don't guarantee key ordering (they do in practice for small objects in all engines tho).

It turns out `{{#each-in}}` does not support `Map`s, which do guarantee key insertion ordering.

Is this a feature you'd be interested in? 👍 / 👎 ?

**Comment by stefanpenner** [comment]
As they have iterators, we should likely add iterator support for `{{#each` or something.

**Comment by rwjblue** [comment]
@cibernox:

> Is this a feature you'd be interested in? 👍 / 👎 ?

Yes. FWIW, I think we do support Map's for `{{#each` (because we support anything that has a `.forEach` method that accepts a callback).

@stefanpenner:

> As they have iterators, we should likely add iterator support for {{#each or (maybe {{#each-in something.

Agreed, we should have support for native iterables in `{{#each` when `Symbol.iterator` is present...

**Comment by stefanpenner** [comment]
> Agreed, we should have support for native iterables in {{#each when Symbol.iterator is present...

👍

**Comment by rwjblue** [comment]
@cibernox - Progress?

**Comment by cibernox** [comment]
Not really, but should I have time this week, since I've finished fixing the inspector.

**Comment by bekzod** [comment]
this is already supported https://github.com/emberjs/ember.js/blob/6a6dcec63c3bc851b81be0f9f6155d8bc0fc4c76/packages/ember-glimmer/lib/utils/iterable.ts#L292-L293 we can close it ?
