### ISSUE TITLE
Ember crashes after encountering unexpected query param type

### ISSUE THREAD

**Issue by Etromania** [emberjs/ember.js#15306]
When a controller tries to deserialize an array based query param it can fail if the query param is not properly stringified, causing Ember to completely crash. This can occur when a user tries to edit the query param directly. It may be better to gracefully handle cases like this to keep the app alive since a simple refresh will not fix the issue. 

https://ember-twiddle.com/ea932831eba4f75f641f1a91f200712e?fileTreeShown=false&openFiles=controllers.index.js%2C

Change URL field to `/?arrayQueryParam=test`

**Comment by Serabe** [comment]
Reopening as this issue is not fully solved. We need a way for the App not to blow up. Still looking for a way to do so without just logging and defaulting to an empty value.

**Comment by cristi-badila** [comment]
@Serabe I recently encountered this issue and it's not really clear to me why it was closed. Was it fixed somewhere else? I'm still on 2.14 but I haven't seen anything in the 2.15 logs about it.
