### ISSUE TITLE
API Document

### ISSUE THREAD

**Issue by luweiCN** [emberjs/ember.js#15309]
There are no methods under Ember.Router in API Document

**Comment by btecu** [comment]
You mean these?
https://www.emberjs.com/api/classes/Ember.Router.html

**Comment by luweiCN** [comment]
yes!when i switch to the methods tab,thers is nothing below

**Comment by locks** [comment]
This is a known bug in the current implementation.
It hasn't been addressed because we are transitioning to ember-api-docs.
Check it out at https://www.emberjs.com/api-beta/ember/2.12.0/classes/Ember.Router!

**Comment by Serabe** [comment]
@locks shall we close this then?

**Comment by locks** [comment]
Confirm! Thanks for reporting, sorry about the confusion.
