### ISSUE TITLE
searchbar Chinese support problem 

### ISSUE THREAD

**Issue by baorr** [emberjs/ember.js#15313]
1. when I type English, it worked fine
<img width="439" alt="59c59df5-d0ce-498d-ad89-e53a16b42b10" src="https://cloud.githubusercontent.com/assets/553038/26672422/a6f53162-46eb-11e7-9dc3-ea9811657166.png">

2. when I changed to Chinese, when I type once, the result showed below:

<img width="396" alt="ad934d6f-b3c9-4155-b4eb-b411326646a2" src="https://cloud.githubusercontent.com/assets/553038/26672412/a0cb0960-46eb-11e7-817e-255347c5b80a.png">

**Comment by Cryrivers** [comment]
Can you show some code to re-produce it?

**Comment by baorr** [comment]
home.html

<ion-header>
  <ion-navbar>
    <ion-title>
      聊聊
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content>
  <ion-searchbar (ionInput)="getItems($event)" placeholder="搜索"></ion-searchbar>
  <ion-list>
    <ion-item *ngFor="let item of items">
      {{ item }}
    </ion-item>
  </ion-list>
</ion-content>

**Comment by Cryrivers** [comment]
Sorry but I mean the code of implementation for the text box.

**Comment by baorr** [comment]
home.html

![image](https://cloud.githubusercontent.com/assets/553038/26673037/0823ae94-46ee-11e7-9ab7-58216ee92af6.png)

**Comment by baorr** [comment]
import { Component } from '@angular/core';


@Component({
  templateUrl: 'home.html'
})
export class HomePage {
  items;

  constructor() {
    this.initializeItems();
  }

  initializeItems() {
    this.items = [
      'Amsterdam',
      'Bogota',
      'Buenos Aires',
      'Cairo',
      'Dhaka',
      '人民',
      'Geneva',
      'Genoa',
      'Glasglow',
      'Hanoi',
      'Hong Kong',
      'Islamabad',
      'Istanbul',
      'Jakarta',
      'Kiel',
      'Kyoto',
      'Le Havre',
      'Lebanon',
      'Lhasa',
      'Lima',
      'London',
      'Los Angeles',
      'Madrid',
      'Manila',
      'New York',
      'Olympia',
      'Oslo',
      'Panama City',
      'Peking',
      'Philadelphia',
      'San Francisco',
      'Seoul',
      'Taipeh',
      'Tel Aviv',
      'Tokio',
      'Uelzen',
      'Washington'
    ];
  }

  getItems(ev) {
    // Reset items back to all of the items
    this.initializeItems();

    // set val to the value of the ev target
    var val = ev.target.value;

    // if the value is an empty string don't filter the items
    if (val && val.trim() != '') {
      this.items = this.items.filter((item) => {
        return (item.toLowerCase().indexOf(val.toLowerCase()) > -1);
      })
    }
  }
}

**Comment by baorr** [comment]
it's enough?

**Comment by Cryrivers** [comment]
Well, this is not using Ember.js.

I suggest you file an issue to [Ionic](https://github.com/ionic-team/ionic) or [Angular](https://github.com/angular/angular).

Please close this issue.

**Comment by baorr** [comment]
ok

**Comment by Serabe** [comment]
Closing this. Thank yo @Cryrivers
