### ISSUE TITLE
Bug on input focusOut, event is missing

### ISSUE THREAD

**Issue by urbany** [emberjs/ember.js#15320]
Hi, the action called on focusOut only receives the current value and not the event.
Here it is being sent: https://github.com/emberjs/ember.js/blob/v2.13.3/packages/ember-views/lib/mixins/text_support.js#L276

But if you follow the path inside sendAction only the value is sent to the user action: https://github.com/emberjs/ember.js/blob/v2.13.3/packages/ember-views/lib/mixins/text_support.js#L348

This happens in to other events, some call directly this.sendAction other use this internal sendAction defined in text_support that only sends the value.

I think the event should always be sent.

**Comment by rwjblue** [comment]
I'm not 100% sure if this is addressed already or not, but I think the path forward is fairly clear: migrate to closure actions + sparkles-component / glimmer components etc.

Sorry for the super delayed response here :(, but I think we should close...
