### ISSUE TITLE
Improve Computed.setDiff efficiency

### ISSUE THREAD

**Issue by orf** [emberjs/ember.js#15329]
An application that relies on `setDiff` can be slowed down considerably [due to the current implementation, which is quite inefficient](https://github.com/emberjs/ember.js/blob/v2.12.0/packages/ember-runtime/lib/computed/reduce_computed_macros.js#L540). If you have lots of entries in `setB` and not many of them in `setA` Ember will perform a *lot* of linear scans on the arrays.

Could the implementation not be refactored to use the [Set object?](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Set) It's supported in all major browsers (with IE 11 offering some support).

The code should be fairly easy to add, something like this:

```js
let setA = this.get(setAProperty);
let setB = this.get(setBProperty);

if (!isArray(setA)) { return emberA(); }
if (!isArray(setB)) { return emberA(setA); }

setA = new Set(setA);
setB = new Set(setB);

return setA.filter(x => !setB.has(x));
```

**Comment by tsteuwer** [comment]
It is not supported in 9-10. Ember currently supports both IE 9 and 10 if im not mistaken. There would have to be a polyfill added which im not sure they would do.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by orf** [comment]
Could the existing implementation not be used for IE 9, 10 and 11? It sucks performance wise, but it does work.

**Comment by tsteuwer** [comment]
having to ensure comparability in two different algorithms, to me, is not worth it. but i am not on the core team ;)

**Comment by wesleycho** [comment]
Wouldn't a polyfill already be present? Later on in that script there is some usage of WeakSet.

**Comment by locks** [comment]
There seems to be a partial polyfill of WeakSet for the features used internally.
I suggest implementing your own computed macro that uses Set, as suggested!
