### ISSUE TITLE
Input fields cursor jumps automatically to the end when webpage is served as XHTML

### ISSUE THREAD

**Issue by cbou** [emberjs/ember.js#15333]
There is a bug in EmberJS `{{input}}` helper when using XHTML format.

The cursor automatically jumps to the end after each keydown.

There is an example here:
https://dl.dropboxusercontent.com/s/a7giae5ef4iab95/index.xhtml?dl=0

It's a generated app with `ember new cursor-at-end`.
I just removed the content of `application.hbs` by `{{input type="text" value='Edit me'}}`.

`ember build` and rename `index.html` into `index.xhtml` plus some changes to links in order to be opened inside Dropbox or open directly in the browser (file://).

Textareas and input field directly built with html tags are not affect by this issue.

**Comment by tomdale** [comment]
@cbou Just to satisfy my own curiosity, can you tell us more about where you need to support strict XHTML parsing? The Glimmer/Handlebars parser itself is based on the HTML5 parsing spec so I kind of wouldn't be surprised if there are other incompatibilities. I'd love to know more about what you're working on!

**Comment by cbou** [comment]
We are migrating an app which was written in XHTML (I don't know the reason why XHTML). We don't want to remove XHTML for now, but it will be do later for sure... I didn't notice any other incompatibilities.

**Comment by cbou** [comment]
Any chance for the PR to be merged?

**Comment by pixelhandler** [comment]
Closing for now, see https://github.com/glimmerjs/glimmer-vm/pull/764#issuecomment-365000363
