### ISSUE TITLE
Inline SVG in template not scaling according to viewbox

### ISSUE THREAD

**Issue by julienzakaib** [emberjs/ember.js#15336]
**Description** : When you put an inline SVG element inside an Ember.js template file, the `viewbox` attribute of the SVG, which normally causes the  content to be scaled to the size of the containing SVG viewport, seems to be ignored, causing the content to be displayed in viewport coordinates, rather than user coordinates. 

<img width="242" alt="screen shot 2017-06-07 at 12 12 47 pm" src="https://user-images.githubusercontent.com/1383603/26894267-21832298-4b7b-11e7-897a-55c03d0ba105.png">

The screenshot above is from the repo I've created and linked to below, where I've reproduced the issue in a minimal Ember app. Here's the code for those 3 divs 
```
<span><code>index.hbs</code></span>

<div style="display: block;">

    <div style="display: inline-block; width: 200px; height: 200px; border: 1px solid blue; margin-bottom: 20px;">
        <svg id="my-svg" width="100%" height="100%" viewbox="0 0 100 100">
            <circle cx="50" cy="50" r="50"/>
        </svg>
    </div>

    <div style="display: inline-block; width: 100px; height: 100px; border: 1px solid blue; margin-bottom: 20px;">
        <svg id="my-svg" width="100%" height="100%" viewbox="0 0 100 100">
            <circle cx="50" cy="50" r="50"/>
        </svg>
    </div>

    <div style="display: inline-block; width: 50px; height: 50px; border: 1px solid blue; margin-bottom: 20px;">
        <svg id="my-svg" width="100%" height="100%" viewbox="0 0 100 100">
            <circle cx="50" cy="50" r="50"/>
        </svg>
    </div>
  
</div>
```

The first row is the result of the above code placed in `index.html`, while the second row is the result of placing the same code in `index.hbs` route template. The issue is then seen to happen only when dealing with template files.

**My Environment** 

ember-cli: 2.12.1
node: 7.9.0
os: darwin x64

**Repro Steps** 

1. Create Ember app structure using ember-cli : `ember new test-app`
2. Create index route using ember-cli : `ember generate route index`
3. In `test-app/app/templates/index.hbs` , add the following code 
```
<svg width="200" height="200" viewbox="0 0 100 100">
  <circle cx="50" cy="50" r="50"/>
</svg>
```
4. Run the app with `ember server`

**Expected** : The circle in the SVG should be drawn based on the viewbox coordinates, and then the viewbox should be scaled to best fit the containing svg element. Since the viewbox and `<svg>` element both have the same width/height ratio, the viewbox should scale to completely cover the svg's area. The result should be a circle with a radius of 100 units (defaults to pixels), thus having a diameter equal to the height and width of the containing SVG. 

**Actual** : The circle only takes up half the width and height of the SVG element. It has a radius of 100 units (pixels), which would be expected if no `viewbox` attribute had been declared, since the circle's coordinates would then have been drawn in relation to viewport coordinates (i.e. the 200x200 `<svg>` element) .

Here is a repo I just created with the steps above, but I also added a few more examples to better illustrate the issue, wrapped the SVGs in `<div>`s for easier visual comparison, and made the `<svg>` elements' width and height "100%".    

https://github.com/julienzakaib/Emberjs-SVG-Bug

**Note** : It's interesting to note that this issue seems to only happen when the SVG is declared inline _inside a template_ . In the repo I linked, I also copied the same code in `test-app/index.html` (changing the border color of the containing `div`s) , and the viewbox is correctly scaled in that case.

**Comment by julienzakaib** [comment]
Solution to this issue for anyone looking at this : The `viewbox` attribute is actually `viewBox` with a capital 'b' . It looks like Chrome parsed the `svg` element and corrected the badly named attribute, which made it render properly. On the other hand, the `svg` inserted into the DOM by Ember did not get the same treatment by the browser, and the attribute was simply ignored. Curse you Chrome for trying to help me despite my making dumb mistakes !!!

**Comment by rwjblue** [comment]
Thank you for sharing the solution!
