### ISSUE TITLE
Depracation in new ember application. 

### ISSUE THREAD

**Issue by Vazgen7788** [emberjs/ember.js#15343]
There is a DEPRECATION in newly created ember application.
```
DEBUG: -------------------------------
DEBUG: Ember      : 2.13.3
DEBUG: Ember Data : 2.13.1
DEBUG: jQuery     : 3.2.1
DEBUG: -------------------------------
```
```
DEPRECATION: Ember.MODEL_FACTORY_INJECTIONS is no longer required [deprecation id: ember-metal.model_factory_injections] 
```

**Comment by kumkanillam** [comment]
You need to remove the below line from app.js 
`Ember.MODEL_FACTORY_INJECTIONS = true;`

This is the related pull request https://github.com/ember-cli/ember-cli/pull/7025 I am not sure is this released on which ember-cli version

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/pull/7025#issuecomment-307309813
