### ISSUE TITLE
Wrong depreciation url for MODEL_FACTORY_INJECTIONS REMOVED

### ISSUE THREAD

**Issue by gandalfar** [emberjs/ember.js#15352]
The url for https://emberjs.com/deprecations/v2.x#toc_code-ember-model-factory-injections changed to https://emberjs.com/deprecations/v2.x/#toc_ember-model-em-factory-em-injections-removed

I can do a quick PR against ember.js or is this something that should be fixed in docs?

Ref: https://github.com/emberjs/ember.js/blob/0a0959bea9a239aa2ef47834b840f07fd1b83513/packages/ember-runtime/lib/mixins/registry_proxy.js#L289

**Comment by Dhaulagiri** [comment]
I opened a Pr to fix the link in https://github.com/emberjs/ember.js/pull/15345

**Comment by btecu** [comment]
This can be closed now.
cc @rwjblue
