### ISSUE TITLE
Loading/Error templates not found for catch-all routes (has reproduction)

### ISSUE THREAD

**Issue by tsteuwer** [emberjs/ember.js#15355]
I have a catch-all route which uses a promise.hash to return the model for a catch-all route. I also have an error/loading template for showing that we're still loading but they never get used.

Here's a twiddle to show you this happening:

https://ember-twiddle.com/03d8d7fc75ee8e72f9bbe9f710ad823c?openFiles=my-catch-all.loading.hbs%2C

Just change the route to "/doesntexsist" and you'll see that I have a 3000ms timeout on that route which should show the loading substate.

**Comment by locks** [comment]
The loading substate has to be a sibling to the template that's being loaded, so they can then be switched out.
If you had a route nested inside `my-catch-all`, then `my-catch-all/loading.hbs` would show when transitioning between child routes.

cc @alexspeller

**Comment by tsteuwer** [comment]
So, then I would have to add a loading.hbs in my application route? That seems like it doesn't make sense.

**Comment by Serabe** [comment]
@tsteuwer I did a sample application. In https://github.com/Serabe/ember-issue-15355/tree/7ffbf514f517b584c257cb6444c31dcc486924b9, the catch-all route is top level (meaning path is `'*anything'`) and in https://github.com/Serabe/ember-issue-15355/tree/a3376f7434db4090931d44b670f5161cf0390065 the catch-all route is under the `me` route.

This is the expected behaviour. Not sure the behaviour you are running into is unexpected.

**Comment by tsteuwer** [comment]
Look at the twiddle I added. So what you're saying is it *has* to be under some other route for this to work? I can't just have a catch-all without first creating another route for the index?

**Comment by alexspeller** [comment]
@tsteuwer I think the route needs to be called `my-catch-all-loading` - have a look at the [guides page](https://guides.emberjs.com/v2.5.0/routing/loading-and-error-substates/) to see the lookup hierarchy for loading routes

**Comment by Serabe** [comment]
Ping @tsteuwer.

Are you satisfied with @alexspeller's answer?

**Comment by Serabe** [comment]
We are closing this issue according to [our triage policy](https://github.com/emberjs/ember.js/blob/9057741de71a7b261ef13a09920fe472919dd68b/CONTRIBUTING.md#triaging-policy).

You can reopen it with a follow up at any time.

Thank you!
