### ISSUE TITLE
LTS tag on npm

### ISSUE THREAD

**Issue by brlodi** [emberjs/ember.js#15363]
Would it be possible to add an 'lts' (or similar) tag for the applicable releases to NPM? My particular use-case where this has come up is working with ember-try, where it would be convenient to be able to test against the then-current LTS release instead of having to manually keep the LTS semver string up to date in the scenario definition. I imagine it could be useful to others as well, certainly enough to justify the slight administrative overhead.

**Comment by stefanpenner** [comment]
not a bad idea, @rwjblue / @chancancode what do you think?

**Comment by rwjblue** [comment]
Ya, seems reasonable.

**Comment by locks** [comment]
```
$ npm dist-tags ls ember-source
beta: 2.15.0-beta.1
latest: 2.14.0
lts: 2.12.2
```

**Comment by brlodi** [comment]
Thanks! Exactly what I was after! 👍
