### ISSUE TITLE
Passing a component class to the "component" helper

### ISSUE THREAD

**Issue by plcarmel** [emberjs/ember.js#15370]
I think this is a feature request.

I tried to pass a component class to the component helper, hoping it would work, but it silently fails (it renders nothing).

Is such a thing possible ? If not, how hard would it be to make it work ? I find it weird to have something as powerful as the component helper and not being able to easily generate an input for it (a contextual component) on the javascript side.

I had a look at the compute function of the helper and I see it is expecting either a string or a component definition. So... what is a component definition exactly and, more importantly, is it possible to generate one from a component class without to much effort, ideally using the public API ?

Thank you !

**Comment by locks** [comment]
What do you mean "pass a component class"?

**Comment by plcarmel** [comment]
Here's an artificial exemple, just to clarify:

```js
// controllers/index.js
export default Ember.Controller.extend({
  SomeComponentClass: Ember.Component.extend({ layout: /*...*/ }),
  // ...
});
```

```hbs
{{!templates/index.hbs}}
{{component
  (component SomeComponentClass someProperty=someValue)
  anotherProperty=anotherValue
}}
```

**Comment by Serabe** [comment]
That would be a feature request and would need to go through the RFC process described in the [contributing guide](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md).

The input is still easily generable by using a string (`"some-component").

**Comment by plcarmel** [comment]
Thank you @Serabe for pointing this out.

However, a string does not cut it in a lot of situations where it would save the day if you could pass a partially instantiated component to a third party library (a component + some parameters).  Possible with HTMLbars but not Javascript...
