### ISSUE TITLE
Reload route on clicking active link-to helper

### ISSUE THREAD

**Issue by krnbatta** [emberjs/ember.js#15393]
Suppose I am on a particular route. I reached there using a {{link-to}} helper. Now when i click on that button again, I want route to reload but it does not.
I need this because I am using nested components within that route which modifies the template. I want to click on link-to button to refresh the template(basically reloading that route).
One method is setting preventDefault=false, but that reloads the whole page.

**Comment by Serabe** [comment]
Hello, @krnbatta. I am closing this since it is not an Emberjs bug. Please, go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

Thank you!
