### ISSUE TITLE
API Reference Website Page Not Working

### ISSUE THREAD

**Issue by qarthandgi** [emberjs/ember.js#15405]
I'm trying to view all the methods of the `Ember.Router` Class at [this page](https://emberjs.com/api/classes/Ember.Router.html).

When I click on the methods, nothing appears. I presume there should be content of all of the methods of the index panel.

![screen shot 2017-06-24 at 5 22 11 pm](https://user-images.githubusercontent.com/25380187/27512022-b13dc3d2-5901-11e7-9749-fafe89c35074.png)

**Comment by locks** [comment]
Duplicate of https://github.com/emberjs/website/issues/2785.
