### ISSUE TITLE
addObserverForContentKey performance in 2.13.3

### ISSUE THREAD

**Issue by jlami** [emberjs/ember.js#15421]
Hi,

I ran into an issue with debug builds taking ages to run when using test data with somewhat large arrays. I tracked it down to `addObserverForContentKey`, which I believe was already an issue earlier #3156

https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/mixins/array.js#L735
```
 assert(`When using @each to observe the array ${content}, the array must return an object`, typeof item === 'object');
```
This is not a problem if content is an ArrayProxy, but a native array will do Array.toString() on this and will blow things up.

I know this is fixed in release builds, but not being able to test my app with large datasets is not good at all.

**Comment by rwjblue** [comment]
More recent versions of Ember (confirmed in 2.14.0) tweak the handling of assertions so that the message is only calculated if the assertions predicate is falsey.

For example, the transpiled code for `addObserverForContentKey` in debug builds of 2.14.0 looks like:

```js
  function addObserverForContentKey(content, keyName, proxy, idx, loc) {
    while (--loc >= idx) {
      var item = objectAt(content, loc);
      if (item) {
        (true && !(typeof item === 'object') && (0, _emberDebug.assert)('When using @each to observe the array ' + content + ', the array must return an object', typeof item === 'object'));

        (0, _emberMetal._addBeforeObserver)(item, keyName, proxy, 'contentKeyWillChange');
        (0, _emberMetal.addObserver)(item, keyName, proxy, 'contentKeyDidChange');
      }
    }
  }
```

As you can see, we are only calculating the message (e.g. `Array#toString()`ing) when actually needed now.  2.14 should completely alleviate this issue.

**Comment by jlami** [comment]
Thanks, that looks great!

**Comment by miketervela** [comment]
Not sure if anyone's still following this, but we are hitting this issue big time and probably won't be to 2.14 for several months - anyone have caveats about overriding Array.prototype.toString to return something static in the meantime?
