### ISSUE TITLE
Reopen Classes Causing Race Condition?

### ISSUE THREAD

**Issue by jacobjzhang** [emberjs/ember.js#15433]
Hi all, quick q regarding the internals of the `reopen` method. I have a block of code that looks like this:

```
import { a, b } from '../someLibrary';
import OneWayInputComponent from 'ember-one-way-controls/components/one-way-input';

OneWayInputComponent.reopen(a);
OneWayInputComponent.reopen(b);
```

I've seen some that on some loads, `b` will not be correctly added and its functionality won't be present on the page. Is it possible that using `reopen` twice in a row (as opposed to `reopen(a, b)`) would lead to a race condition?

**Comment by stefanpenner** [comment]
I am not aware of a race in this scenario.  Could you provide a reproducible example? Would love to debug what your seeing.

**Comment by jacobjzhang** [comment]
Hi Stefan,

Upon investigating more closely, the bug seems more likely to be caused by a JS error that breaks some Ember functionality, rather than something in Ember. The above code works as expected about 99% of the time, which raises doubts on the race condition. Thanks for checking this issue out, I'll close it for now.
