### ISSUE TITLE
Missing sourcemaps

### ISSUE THREAD

**Issue by simonihmig** [emberjs/ember.js#15464]
I get this error when upgrading to `ember-source@2.14.0` and building the app:

```
Warning: ignoring input sourcemap for vendor/ember/ember.debug.js because ENOENT: no such file or directory ...
Warning: ignoring input sourcemap for vendor/ember/ember-testing.js because ENOENT: no such file or directory, open ...
```

There are two problems with that:
* the supplied source maps are missing from the build (obviously)
* the warnings break our CI (but this is more related to https://github.com/ef4/fast-sourcemap-concat/issues/35)

I think the reason for this is that the `dist` files contain a reference to their sourcemap at the end of the file: `//# sourceMappingURL=ember.debug.map`. This seems to be new for 2.14, at least 2.13 did not have this.  While there is a `dist/ember.debug.map` in the published npm package, these files are not added to the `vendorTree` in [index.js](https://github.com/emberjs/ember.js/blob/master/index.js), so they are really missing in the tmp tree when `fast-sourcemap-concat` tries to read them.

I can put a PR together exporting those files in the `vendorTree` if that is the way to go? But given there is https://github.com/emberjs/ember.js/pull/15102, I am not so sure about it...

**Comment by olivierchatry** [comment]
I have the same issue.

**Comment by siriniok** [comment]
Using Ember CLI 2.14.0 with `ember-cli-babeli`. Same issue.

**Comment by siriniok** [comment]
I think, this issue relates rather to `ember-cli`.

https://github.com/ember-cli/ember-cli/issues/7212

**Comment by rwjblue** [comment]
No, this is definitely an issue here (perhaps in addition to ember-cli).

**Comment by simonihmig** [comment]
@rwjblue are you able to confirm that exporting those sourcemap files in the `vendorTree` is the right path to go forward (see my first comment, being a bit confused about #15102)? If that is the case, I should be able to provide a quick PR hopefully...

**Comment by Samsinite** [comment]
Any help we can provide on this to get sourcemaps working again? It is quite a pain for css to not point to the correct scss file when debugging.

**Comment by rwjblue** [comment]
I don't believe this issue relates to CSS sourcemaps at all.

**Comment by Samsinite** [comment]
Hmm... okay. Our sourcemaps broke after upgrading to 2.14, I'll take another look to help detect the problem. Thanks!

**Comment by bartocc** [comment]
Almost a year later, this warning pops up again in my codebase when upgrading from `ember-source@3.2.2` to `ember-source@3.3.0`

The exact warnings are:

```
Warning: ignoring input sourcemap for vendor/ember/ember.debug.js because ENOENT: no such file or directory, open '<hidden>/tmp/source_map_concat-input_base_path-gcU53ttn.tmp/vendor/ember/index.js.map'
Warning: ignoring input sourcemap for vendor/ember/ember-testing.js because ENOENT: no such file or directory, open '<hidden>/tmp/source_map_concat-input_base_path-VfRaj57E.tmp/vendor/ember/testing.js.map'
```

Googling about this only led me to this issue.

Has anyone else experienced this?
