### ISSUE TITLE
Cannot read methods or properties details about Router class

### ISSUE THREAD

**Issue by AleWin32** [emberjs/ember.js#15471]
The API Ember website has a problem.

Go to the documentation about the Router class:
[https://www.emberjs.com/api/classes/Ember.Router.html](https://www.emberjs.com/api/classes/Ember.Router.html)

Click on any method or property on it, for example, the **map** method:
[https://www.emberjs.com/api/classes/Ember.Router.html#method_map](https://www.emberjs.com/api/classes/Ember.Router.html#method_map)

The info will not be shown. Reading the source code of the page, the info is there but it is not shown, maybe a problem with layers or javascript not properly handling a style (display:none) to show it?

**Comment by Serabe** [comment]
Seems fix in the brand new API page. Thank you!

![2017-07-11 at 15 16](https://user-images.githubusercontent.com/36221/28072834-0977476a-664c-11e7-85c3-898f35cfc4fc.png)

**Comment by AleWin32** [comment]
Thanks! Although it has been half-fixed.

Now you can read the info about all methods and properties but the links don't work and it goes to the first method (addObserver). This happens to me on Firefox, mine is 54.0 (64-bit) on Ubuntu. In my Chrome it works well (Versión 59.0.3071.115 (Build oficial) (64 bits)) on Ubuntu.

Also, there is a difference watching the page [https://www.emberjs.com/api/ember/2.14/classes/Ember.Router](https://www.emberjs.com/api/ember/2.14/classes/Ember.Router) between Firefox and Chrome, maybe this is related to the problem of the links. Method listing in Chrome appears in two columns (i think this is the good one), but in Firefox it appears in one column (so the right space is wasted).

@Serabe can you try it on Firefox?

**Comment by locks** [comment]
Scrolling should now be fixed by https://github.com/ember-learn/ember-api-docs/pull/277.
Please open further issues in that repository, like the style difference between browsers. This repository is for bugs in the framework itself. We're thinking of a way to better inform contributors where to file issues and such, suggestions are welcome :)

Thank you for your time and feedback!
