### ISSUE TITLE
[beta] Negative integer literal causes null reference in positional params

### ISSUE THREAD

**Issue by ef4** [emberjs/ember.js#15480]
In ember beta, a component invocation like this:

```hbs
{{my-component "a-string-literal" (num-plus 1 -1) }}
```

Throws an exception. If you change the negative one to a positive number, the exception goes away.

The exception seems to be that the _first_ positional parameter (in this above case, the string literal) is replaced with a null reference in the positional arguments handled by glimmer. The stack trace is:

```
TypeError: Cannot read property 'tag' of null
    at combineTagged (reference.js:141)
    at PositionalArguments.get (runtime.js:500)
    at combineTagged (reference.js:141)
    at Arguments.get (runtime.js:443)
    at Arguments.capture (runtime.js:426)
    at CurlyComponentManager.prepareArgs (curly.js:126)
    at runtime.js:1631
    at AppendOpcodes.evaluate (runtime.js:70)
    at VM.next (runtime.js:7223)
    at TemplateIterator.next (runtime.js:7294)
```

Reproduction repo: https://github.com/ef4/ember-params-bug

**Comment by cibernox** [comment]
@ef4 This is a dup of https://github.com/emberjs/ember.js/issues/15470

**Comment by cibernox** [comment]
Although it's good to know that it's not only related with actions and helpers are also affected

**Comment by ef4** [comment]
Thanks, I saw that issue but wasn't sure it covered the same case. Now I
notice "negative" there, and I agree.

**Comment by Serabe** [comment]
Closing as dup. Thank you!
