### ISSUE TITLE
Properties/methods not added to Ember.Object using reopen() unless an object is subsequently created.

### ISSUE THREAD

**Issue by bdiz** [emberjs/ember.js#15488]
Hello,

I noticed when dynamically adding properties/methods to an existing Ember.Object class using reopen() that the properties/methods did not show up. After tinkering I found that an arbitrary object of that class type must be constructed before the properties/methods will be added to previously constructed objects of that class type.

For example, the reopen() example in documentation works fine:

```
const MyObject = Ember.Object.extend({
  name: 'an object'
});

o = MyObject.create();
o.get('name'); // 'an object'

MyObject.reopen({
  say(msg) {
    console.log(msg);
  }
});

o2 = MyObject.create();
o2.say('hello'); // logs "hello"

o.say('goodbye'); // logs "goodbye"
```
Unless, you remove the construction of o2...

```
const MyObject = Ember.Object.extend({
  name: 'an object'
});

o = MyObject.create();
o.get('name'); // 'an object'

MyObject.reopen({
  say(msg) {
    console.log(msg);
  }
});

// o2 = MyObject.create();
// o2.say('hello');

o.say('goodbye'); // TypeError
```

Then you get a TypeError, "o.say is not a function".

**Comment by stefanpenner** [comment]
In general, we strongly recommend all `reopen` and `reopenClass` occur before the first class of that type instantiated. There are other caveats in addition to the one you mentioned, fixing them and performance constraints are unfortunately at odds...
