### ISSUE TITLE
getOwner(this) is sometimes returning undefined after ember-2.14.0-beta2

### ISSUE THREAD

**Issue by psbanka** [emberjs/ember.js#15492]
This is related to:

https://github.com/intercom/ember-href-to/issues/81
and
https://github.com/Vestorly/torii/issues/349#issuecomment-302141236
and perhaps 
https://github.com/emberjs/ember.js/issues/15468

It appears that sometimes `getOwner(this)` returns `undefined`, and we are having to work around it with `const owner = getOwner(this) || this.container`

**Comment by rwjblue** [comment]
Is there a reproduction?

**Comment by krisselden** [comment]
reproduction https://github.com/simonihmig/ember-2-14-safari

**Comment by krisselden** [comment]
I've not see a reproduction on a production build.

**Comment by krisselden** [comment]
I need to know if this is a problem with production builds and if anyone has a reproduction in a production build.

**Comment by krisselden** [comment]
people have confirmed this affects production builds via error logs

**Comment by krisselden** [comment]
I still would like a production build reproduction, but I've also confirmed with the existing reproduction that WebKit nightly is not affected by this.

**Comment by krisselden** [comment]
Bisected to this https://github.com/emberjs/ember.js/commit/44e04baa7a9cfb31df46ba63e3a5b0268c2690dd then checked the cherry picked commit https://github.com/emberjs/ember.js/commit/986710f9c57a9ff4520034b600e7fea93b56b955 against its parent.

It seems to be this improved JIT but the JIT is deopting at some late point and not returning undefined from peekMeta

**Comment by krisselden** [comment]
This versions of Safari I've checked are Version 10.1.1 (12603.2.4) which has the problem and the WebKit Nightly Revision 219450 which is fixed.

**Comment by krisselden** [comment]
@stefanpenner just checked Release 35 (Safari 11.0, WebKit 12604.1.29) it is fixed there too.

**Comment by stefanpenner** [comment]
master: https://github.com/emberjs/ember.js/pull/15502 (green + merged)
beta: https://github.com/emberjs/ember.js/pull/15504 (running)
release: https://github.com/emberjs/ember.js/pull/15505 (running)
