### ISSUE TITLE
getting a classCallCheck is not a function error

### ISSUE THREAD

**Issue by nullrocket** [emberjs/ember.js#15506]
With   2.15.0-beta-1 or canary  I am seeing the following error only in production.  I don't have a reproduction but I did trace it down to maybe a couple classCallCheck's in RSVP that aren't being stripped. 

```
ember-metal.js:3482 TypeError: (0 , e.classCallCheck) is not a function
    at new n (rsvp.js:1504)
    at Object.K [as allSettled] (rsvp.js:1563)
    at o.<anonymous> (result-collection.js:339)
    at o.<anonymous> (cycle-breaker.js:13)
    at dt.Xe.get (ember-metal.js:2867)
    at nt (ember-metal.js:2250)
    at enumerable.js:240
    at enumerable.js:233
    at o.forEach (enumerable.js:205)
    at o.map (enumerable.js:232)
```

With sourcemaps enabled in production I can see this in rsvp.js
```
  var AllSettled = function (_Enumerator) {
    (0, _emberBabel.inherits)(AllSettled, _Enumerator);

    function AllSettled(Constructor, entries, label) {
      (0, _emberBabel.classCallCheck)(this, AllSettled); //<--- error is here.
      return (0, _emberBabel.possibleConstructorReturn)(this, _Enumerator.call(this, Constructor, entries, false /* don't abort on reject */, label));
    }

    return AllSettled;
  }(Enumerator);

**Comment by nullrocket** [comment]
Reproduction just click the make me error button in each twiddle.  Probably want to get rid of the try/catch and watch the console to see the actual stack trace.

With production build
https://ember-twiddle.com/f0d2ac7283a26e9354b5cccb173e338e

With debug build
https://ember-twiddle.com/a0cd59a8a1a63e001702f905a33ec6d1

**Comment by bekzod** [comment]
I think its babel issue in ember build, rsvp build does not add `classCallCheck` possible also reason why we reverted es6 classes in rsvp https://github.com/tildeio/rsvp.js/pull/486
