### ISSUE TITLE
[QUEST] Internals should prefer generic array methods over prototype_extensions

### ISSUE THREAD

**Issue by Serabe** [emberjs/ember.js#15501]
This supersedes  #10899 that is stale.

- [x] addArrayObserver
- [x] removeArrayObserver
- [x] `objectAt`
- [x] `replace`
- [x] `remoteAt`
- [ ] `insertAt` https://github.com/emberjs/ember.js/pull/16048
- [ ] pushObject
- [ ] pushObjects
- [ ] re-org public api
- [ ] etc ...
- [ ] docs
- [ ] all the tests

The goal here is merely to decouple the internals from the the observable based prototype extensions.
This will hopefully give us the flexibility to make a future call re: prototype extensions in general. This also eases the pain of using ember with prototype extensions disabled.

All this is accomplished without breaking semver in anyway.

More todo:
- [x] Merge Enumerable + NativeArray
- [x] Merge MutableEnumerable + MutableArray
- [ ] Deprecate Enumerable as [bugfix release]
- [ ] Deprecate MutableEnumerable as [bugfix release]

**Comment by alvincrespo** [comment]
@Serabe How can I help? This is my first time diving into Ember internals.

**Comment by Serabe** [comment]
This might be closed as per https://github.com/emberjs/ember.js/pull/16048#issuecomment-367929653

**Comment by Serabe** [comment]
Removing labels to avoid people working on this until there is some clarification on the goal.

**Comment by Serabe** [comment]
Don't really know. source needs to be checked.

**Comment by mmun** [comment]
@bekzod was working on this recently.

**Comment by locks** [comment]
Thanks everyone for your help! Closing as there's no more work required here :)
