### ISSUE TITLE
{{action}} handler get ignored in production

### ISSUE THREAD

**Issue by Blackening999** [emberjs/ember.js#15517]
for some mysterious reasons - {{action}} handler completely ignored in production.
Temp solution is onclick={{action "actionName"}}, but for cases like {{async-button}} it's not working.
v2.10

**Comment by Serabe** [comment]
Can you send a reproduction in a repo? Thank you!

**Comment by pixelhandler** [comment]
@Blackening999 We'll need an ember-twiddle.com example to verify there is a bug with Ember, vs. other mysterious reasons. Please provide a reproduction using a twiddle or example repo, without any way to reproduce the issue we'll need to close this out.

**Comment by Serabe** [comment]
We are closing this issue according to [our triage policy](https://github.com/emberjs/ember.js/blob/9057741de71a7b261ef13a09920fe472919dd68b/CONTRIBUTING.md#triaging-policy).

You can reopen it with a reproduction at any time.

Thank you!
