### ISSUE TITLE
Behavior around `Ember.inject.controller` changed in 2.14

### ISSUE THREAD

**Issue by rondale-sc** [emberjs/ember.js#15527]
If a controller is injected but the user hasn't specified it in Ember 2.13 the result of that injection is an empty controller (actively generated).  

In 2.14 this behavior now throws an error.

The solution if you find yourself in this predicament is to create said controller to restore previous behavior.

I'm only adding this issue in case it bites someone down the road.  Will immediately close.

**Comment by rwjblue** [comment]
Thanks @rondale-sc.
