### ISSUE TITLE
Error events fired twice

### ISSUE THREAD

**Issue by ohcibi** [emberjs/ember.js#15537]
I have this example, that uses mirage; but the problem is in fact independent from mirage: https://ember-twiddle.com/5f4256a757e87bfa6dd2e39a0b786f6e?openFiles=instance-initializers.error.js%2C

When looking into the developer tools one can see that the error thats responded by mirage (or - without mirage - the `404` that gets thrown by the browser) appears twice in the log. The `console.log` statement in the error handler however fires only once. In my real-world-app that handler is somehow also firing twice.

Whats going on there? Is it expected that this error is thrown twice in the console? What can cause the handler to be fired twice?

* Whenever I say "fired twice", that means that the stack trace of the error is the **exact same** for both appearances in the console
* I **have verified** that the handler is **not attached twice** in my real-world app!

**Comment by pixelhandler** [comment]
@ohcibi both `error: function (error, transition, originRoute)` in the route and `defaultDispatch(error)` use a logger to print to the console. I don't think the error event is firing twice, only once. This doesn't seem to be a bug.  I'll close this for now feel free, to reach out in the embercommunity.slack.com #-help channel if you have more questions. The example you provided is great for discussing the behavior.
