### ISSUE TITLE
Setting backing value in oninput action doesn't trigger textarea value update on newline-related change

### ISSUE THREAD

**Issue by baileyparker** [emberjs/ember.js#15531]
Sorry about the confusing title. Repro here: https://ember-twiddle.com/3d017b5d79fa64c8207a5381ef7a4cb9?numColumns=2&openFiles=templates.components.test-textarea.hbs%2Ccomponents.test-textarea.js

In the text box try the following:

  - Ember<kbd>ENTER</kbd>
  - Ember<kbd>ENTER</kbd>!

(For clarity, that's `"Ember\n"` and `"Ember\n!"` typed--on non-Windows since `\n`)

The textarea's value is backed by the property `value`. The action that runs `oninput` is:

```js
function(e) {
    let value = e.target.value,
        filteredValue = value.toUpperCase().replace(/[\r\n\v]/g, '');
    this.set('value', filteredValue);
}
```

I would expect that the result of the first would be (where `|` represents the text caret):
```
EMBER|
```

And the second would be:
```
EMBER!|
```

The second one works as expected. But the first leaves the caret on the second (despite the oninput removing all newlines--you can confirm this in the console output in my twiddle):
```
EMBER
|
```

The second case demonstrates that immediately when you add another (non-newline) character after the newline, the problem demonstrated by the first example is rectified. Try the first example but hit <KBD>ENTER</kbd> a bunch of times at the end. Notice the textarea's value is not rectified until a non-newline character is typed.

You can also try typing `Eber`, placing the caret between the `E` and `b` then hitting <kbd>ENTER</kbd> to see the same issue. But if you then type an `e` (or any other non-newline character), it is rectified.

It seems like despite the action always setting the `value` property, the textarea's value, which this property backs, isn't updated for newline changes.

As an interesting aside, if you paste in `"Ember\n"` it behaves as expect (the caret stays on the first line). You can try on macOS with `echo "Ember" | pbcopy` to make sure you have the right string copied with no trailing chars. Additionally, all arbitrary copied strings (with multiple newlines) behave as you would expect.

Temporary workaround is to just `preventDefault` on `keydown` where `e.keyCode === 13` (enter).

**Comment by baileyparker** [comment]
I'm also able to reproduce this with the two-way bound textarea helper `{{textarea value=value}}` with a getter and setter on the `value` property:

```js
Ember.computed('_value', {
  get(k) { return this.get('_value'); },
  set(k, v) { return this.set('_value', v.replace(/[\r\n\v]/g, '')); },
}),
```

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue.

This repo has a lot of open issues, some that that have been open for several years. 

The reality is that this is an open-source project, and the time of core team members is very limited. We all want them to focus on moving the framework forward (high-leverage things).

I'll be closing this for now, to keep the list of open issues manageable. I hope you understand!

If you disagree, we can reopen, but in that case, your help in fixing this would be appreciated (for example a PR with a bugfix).
