### ISSUE TITLE
Controller's init hook called on query param resolution

### ISSUE THREAD

**Issue by Dhaulagiri** [emberjs/ember.js#15534]
Similar to [this issue](https://github.com/emberjs/ember.js/issues/15495), the changes to refactor routes to lookup controllers for query params [made here](https://github.com/emberjs/ember.js/pull/15178) is causing an issue in our app I'm not sure how to remediate.

The problem is that we have a `link-to` to a route with query params and the route in question has a controller with an `init` hook that runs some setup for that controller.  Prior to 2.14 this hook was only run when on the route in question, but after 2.14 this hook is run as part of the query param resolution where this route is linked to, causing unintended side effects.

Is this something we need to figure out a way to refactor around or is there something else we can do here?

**Comment by Dhaulagiri** [comment]
It seems like I can work around this by moving the sensitive code to the route's `setupController` hook, avoiding any issues with the controller's `init` being called unexpectedly.

**Comment by kumkanillam** [comment]
Fine. Be aware that every time `model` hook is called, then `setupController` hook also will be called. but in case of `init` it will be called only once.

**Comment by Dhaulagiri** [comment]
I think that is ok in our case, thanks @kumkanillam for the reminder.
