### ISSUE TITLE
Images on templates missing prepend url

### ISSUE THREAD

**Issue by deividkamui** [emberjs/ember.js#15541]
Hi I upgrade my ember project from 2.12 to the latest version, and now my images and other assets are not being display. 

I have this template that used to work:

```
{{#if isAdmin}}

        <img src="/images/adminprofile.jpg" alt="app-icon" class="img-responsive img-thumbnail center-block" />
 
        {{/if}}

```

and on my enviroment.js file I have this on production

```
if (environment === 'production') {

    ENV.locationType = 'hash';
    ENV.rootURL = "/_catalogs/masterpage/ember";
    ENV.APP.rootElement = '#appMainContainer';

  }
```

and on my ember-cli-build I have this

```
fingerprint: {
      enabled: true,
      customHash: null,
      prepend: '/_catalogs/masterpage/ember/'
    },
```

but now all the images are missing any idea why?

**Comment by locks** [comment]
@deividkamui You don't seem to be prepending `{{rootURL}}` in the template,
