### ISSUE TITLE
[DOC] Explain "empty function" in Ember.isEmpty

### ISSUE THREAD

**Issue by nkgm** [emberjs/ember.js#15558]
https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/is_empty.js#L6

**Comment by rwjblue** [comment]
Ha! Just reviewed the implementation and I'm not actually certain how we are handling functions at all there.

**Comment by mmun** [comment]
Agreed. Seems like a doca bug. I don't think we want to get into the business of distinguishing empty function bodies.

**Comment by rwjblue** [comment]
@nkgm - mind submitting a PR updating the docs?

**Comment by nkgm** [comment]
No problem. In fact, it's only trying to avoid returning `true` for zero-arg functions.
