### ISSUE TITLE
Route / Controller: hooks not ran in order

### ISSUE THREAD

**Issue by btecu** [emberjs/ember.js#15565]
Version <= 2.13.x runs the hooks in the following order:
[Twiddle](https://ember-twiddle.com/c5417cc0ecdcf39b1db9ef310847eb8b/31a7fc180ea1ebd29673f435aebf37bf21521c42)

```
Application Model
Index Model
Application Controller Init
Index Controller Init
```

Version >= 2.14.x runs the hooks in the following order:
[Twiddle](https://ember-twiddle.com/c5417cc0ecdcf39b1db9ef310847eb8b)
```
Application Controller Init
Index Controller Init
Application Model
Index Model
```

Previous order makes sense since `afterModel` could transition somewhere else, therefore no need to initialize the controller.

**Comment by rwjblue** [comment]
See related issues:

* https://github.com/emberjs/ember.js/issues/15495
* https://github.com/emberjs/ember.js/issues/15534

The main crux of the matter (from https://github.com/emberjs/ember.js/issues/15495#issuecomment-315464778) is:

> In general, there has never been a guarantee that controllers would be created in any specific order related to the route structure.

**Comment by rwjblue** [comment]
The change was definitely a valid bug fix (and the right path forward), and I am quite sorry that this change has caused issues in your app.  😞

**Comment by btecu** [comment]
@rwjblue Any hope for this to be fixed?

I'm using the controller `init` to trigger a tour which should only be triggered the first time a user enters the route. I can't switch to components because the route has query params.
Ideas of how to get this working without `init` running after `model`?

**Comment by rwjblue** [comment]
> @rwjblue Any hope for this to be fixed?

Well, the thing is that I don't actually think anything is broken in Ember itself. The bug is basically in your application code which assumes `init` will only be ran after the route's `model` hook has ran.  Obviously, thats a sucky answer and I'm sorry, but I don't think there is much we can do internally to fix it...

**Comment by kumkanillam** [comment]
I don't think of any alternative way to solve your use case using the existing hook method. I think it's only possible by introducing `tourVisited` flag and check in `activate` hook.

**Comment by btecu** [comment]
@kumkanillam Using this approach would mean I have to add logic into the route (`activate`), which adds significant overhead when there's many routes that use this.

Right now I'm using a mixin on the controller for the tour.

**Comment by Serabe** [comment]
Hello all,

Closing this since there was no guarantees on the order the controllers are created and the routes' hooks are called.

As stated above, this answer is not ideal, and we are sorry for it.

Thank you so much.
