### ISSUE TITLE
lookup is not a helper

### ISSUE THREAD

**Issue by AustP** [emberjs/ember.js#15561]
I'm trying to access handlebars built-in helper `lookup` but when I do I get the error:

> lookup is not a helper

My .hbs file looks like:

    {{lookup model.sexes model.info.sex}}

And my route:

    return Ember.RSVP.hash({
      info: this.get('store').findRecord('lead', params.user_id),
      sexes: {
        1: 'female',
        2: 'male'
      }
    });

Do I need to do anything special to access the `lookup` helper?

**Comment by rwjblue** [comment]
Ember leverages handlebars syntax, but offers a different set of helpers than are built-in for a standard handlebars setup.  I believe that you are looking for the `get` helper (see [guides here](https://guides.emberjs.com/v2.14.0/templates/built-in-helpers/#toc_using-a-helper-to-get-a-property-dynamically) or [API Docs here](https://emberjs.com/api/ember/2.14/classes/Ember.Templates.helpers/methods/get?anchor=get)):

```hbs
{{get model.sexes model.info.sex}}
```

**Comment by AustP** [comment]
Thanks for the info. It looks like `get` requires that the 2nd parameter is a string. `model.info.sex` is an integer so I'm doing the following as a workaround:

    {{get model.sexes (concat "" model.info.sex)}}

Is this the suggested approach?

**Comment by rwjblue** [comment]
Yes, but I believe in more recent versions we now properly handle numbers as inputs for `get` helper.

**Comment by rwjblue** [comment]
Yep, its listed in the [CHANGELOG for 2.15.0-beta.1](https://github.com/emberjs/ember.js/blob/master/CHANGELOG.md#2150-beta1-july-5-2017).

**Comment by AustP** [comment]
Thanks. I look forward to that change.
