### ISSUE TITLE
Where can I submit documentation errors?

### ISSUE THREAD

**Issue by szaske** [emberjs/ember.js#15571]
I was reading the Ember documentation on [this page](https://emberjs.com/api/ember/2.14.1/classes/Ember.Templates.helpers/methods/action?anchor=action&show=inherited,protected,private,deprecated) and found a few errors on the page.  First, I was trying to find a list of acceptable DOM events that were supported by the Action helper.  The page includes a link to "Event Names", but the link gives me a strange "503" error.  

The second documentation bug I found is the pencil button on the top of the page.  It reads "View on Github" which links to "https://github.com/emberjs/ember.js/tree/v2.14.1/undefined#Lundefined" which is a dead page.  

Sorry if this is not the right channel for submitting documention errors.  It might be nice if you're documentation gave instructions on how to do it.

**Comment by Serabe** [comment]
In this case this is the right channel. Thank you so much! I'm on it. On the meantime, you can see it here:

https://emberjs.com/api/ember/2.14/classes/Ember.Component#event-names
