### ISSUE TITLE
Ember 2.15 beta fails to load if begin/end is used in initializer and jquery is not included.

### ISSUE THREAD

**Issue by webark** [emberjs/ember.js#15574]
It looks like in `ember 2.15.0-beta.2`, if you add a run loop `begin` with a delayed `end` in an initializer, and you are not including jquery, but using `ember-native-dom-event-dispatcher` instead, the application never loads. Here is a [sample repo](https://github.com/webark/ember-2-15-beta-no-jquery-initializer-run-loop-oddness).

Here is the basic diff for expediency
```diff
diff --git a/app/initializers/test-delay.js b/app/initializers/test-delay.js
new file mode 100644
index 0000000..545928e
--- /dev/null
+++ b/app/initializers/test-delay.js
@@ -0,0 +1,13 @@
+import { begin, end } from "@ember/runloop"
+
+export function initialize() {
+  begin();
+
+  setTimeout(function() {
+    end();
+  });
+}
+
+export default {
+  initialize
+};
diff --git a/ember-cli-build.js b/ember-cli-build.js
index 9a757ff..668f6ab 100644
--- a/ember-cli-build.js
+++ b/ember-cli-build.js
@@ -5,6 +5,9 @@ const EmberApp = require('ember-cli/lib/broccoli/ember-app');
 
 module.exports = function(defaults) {
   let app = new EmberApp(defaults, {
+    vendorFiles: {
+      'jquery.js': null
+    },
     // Add options here
   });
 
diff --git a/package.json b/package.json
index e93e1aa..142190a 100644
--- a/package.json
+++ b/package.json
@@ -32,6 +32,7 @@
     "ember-data": "~2.15.0-beta.2",
     "ember-export-application-global": "^2.0.0",
     "ember-load-initializers": "^1.0.0",
+    "ember-native-dom-event-dispatcher": "^0.6.3",
     "ember-resolver": "^4.0.0",
     "ember-source": "~2.15.0-beta.2",
     "ember-welcome-page": "^3.0.0",
```

**Comment by webark** [comment]
anyone have any thoughts on this one? What might have changed with 2.15 that could have caused this?

**Comment by locks** [comment]
Did this work in 2.14 @webark?

**Comment by webark** [comment]
@locks yep.

**Comment by pixelhandler** [comment]
@webark I'm curious if the bug is in [ember-native-dom-event-dispatcher](https://github.com/rwjblue/ember-native-dom-event-dispatcher) or in Ember. So without JQuery ember-native-dom-event-dispatcher is a must have. Maybe this one needs @rwjblue to investigate.

**Comment by webark** [comment]
@pixelhandler ya, I think that could be good. I dug in a little bit to ember-native-dom-event-dispatcher .. Maybe I will a little more. The reason why I filed it here was that it was working with 2.14 but not with 2.15... but maybe there is a disconnect with the new version.

**Comment by webark** [comment]
@pixelhandler and @rwjblue did a little more digging, and it looks like https://github.com/rwjblue/ember-native-dom-event-dispatcher is not even getting loaded with 2.15

**Comment by webark** [comment]
ping

**Comment by pixelhandler** [comment]
@webark any luck with 2.16.x ?

**Comment by webark** [comment]
@pixelhandler nope. The event dispatcher in https://github.com/rwjblue/ember-native-dom-event-dispatcher never gets loaded.. The whole file never gets loaded.

**Comment by rwjblue** [comment]
Not really sure what to do about this.  I haven't had time to clone the reproduction and test things out so I'm not 100% sure what is going on.  I think the general advice here is to essentially just avoid doing this.  For example, it would probably be better to do this work in the `model` hook of your application route instead of inside an initializer.  I know thats not a great answer, but I think it will unblock things for you for now...

**Comment by pixelhandler** [comment]
@locks @rwjblue @webark I'll close this for now.
