### ISSUE TITLE
[Fastboot] Cannot read property 'removeAttribute' of undefined

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#15578]
I am trying to get my addon to work with Fastboot.

Here is how it works:

```handlebars
{{#my-parent as |p|}}
  {{#p.child as |c|}}
    Child 1 (index {{c.index}})
  {{/p.child}}

  {{#p.child as |c|}}
    Child 2 (index {{c.index}})
  {{/p.child}}
{{/my-parent}}
```

- Child components register themselves with their parent component when initialised
- Parent waits until it has rendered each child, before building a final array of the known children
- During this time whilst each child is initialising, their index property is computed as -1
   (because at this point it is not known how many children there will be)
- A computed property on the children determines when each one is considered 'active'
  based on the current `activeChildIndex` set on the parent, and the index of each child.
- The aforementioned computed property is also bound as an attribute `isActive:aria-current`

What is happening:

- During the first few milliseconds of rendering no child is considered active because we don't know how many children there will be until their parent has finished rendering.
- Once the parent has finished rendering, the children then receive the active index as an attribute, and can then compute whether or each one is active or not.
- In Fastboot mode, during the initial phase of rendering each child, having an active index of -1 effectively tells the attribute binding that each child is _not active_
- This leads to the following error, which _I guess_ is Ember trying to remove an attribute binding for `aria-current`, but it can't.

```javascript
There was an error running your app in fastboot. More info about the error:
 TypeError: Cannot read property 'removeAttribute' of undefined
    at AttributeManager.updateAttribute ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:5973:1)
    at DynamicAttribute.patch ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:2596:1)
    at PatchElementOpcode.evaluate ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:2682:1)
    at UpdatingVM.execute ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:7060:1)
    at RenderResult.rerender ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:6470:1)
    at RootState._this.render ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:18529:1)
    at exports.runInTransaction ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:23139:1)
    at InertRenderer._renderRoots ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:18796:1)
    at InertRenderer._renderRootsTransaction ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:18834:1)
    at InertRenderer._revalidate ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:18873:1)
    at invokeWithOnError ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:9037:1)
    at Queue.flush ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:8923:1)
    at DeferredActionQueues.flush ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:9086:1)
    at Backburner.end ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:9165:1)
    at Backburner.run ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:9244:1)
    at Backburner.join ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:9257:1)
    at Array.loopEnd ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:18614:1)
    at Backburner._trigger ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:9564:1)
    at Backburner.end ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:9174:1)
    at Timeout.Backburner._boundAutorunEnd [as _onTimeout] ember-fastboot-register-pattern/tmp/broccoli_merge_trees-output_path-2uxoPV9E.tmp/assets/vendor/ember/ember.debug.js:9134:1)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

I've set up an example repo:

https://github.com/amk221/-ember-fastboot-register-pattern

**Comment by pixelhandler** [comment]
@amk221 did you find any help in the #-fastboot channel of embercommunity.slack.com ? The sample repo should help with troubleshooting. It sounds like there could be a bug in either the app/addon implementation, or maybe ember/fastboot codebases. Would need to identify steps to reproduce if you find that that bug lies in ember/fastboot vs the app/addon code. Also, I am curious about the use case it sounds very implementation specific. Is there another way to compute the index properties that does not result in an error?

**Comment by amk221** [comment]
The use case is a select box, in which the child components (aka options) need to be registered with their parent component in the correct order.

**Comment by amk221** [comment]
https://github.com/glimmerjs/glimmer-vm/blob/8409f1e8b6eae6ca323aea45ad0d69ab9d05e586/packages/glimmer-runtime/lib/dom/attribute-managers.ts#L86

The result of `getDOM()` is undefined

**Comment by amk221** [comment]
If I change this line to `if (true)`, this fixes the issue.
https://github.com/emberjs/ember.js/blob/3240b4a8756a066ff0afe67198b15f78ce66f426/packages/ember-glimmer/lib/setup-registry.ts#L55

**Comment by amk221** [comment]
I might be able to further narrow down this example repo to a simpler failure.

**Comment by amk221** [comment]
I think I understand the problem a bit more now.

Ember is set up with `appendOperations` (so it can build the initial DOM)
But it is _not_ set up with `updateOperations` (because it is assumed that any updating will be done in the browser, and not by fastboot.

So, it seems that this scenario is causing an update operation in Fastboot

**Comment by pixelhandler** [comment]
@amk221 is this still an issue, perhaps we should close, what do you think?

**Comment by amk221** [comment]
It's an issue for me as an addon author, I can't close [the issue](https://github.com/zestia/ember-select-box/issues/12) because otherwise my addon will never work with Fastboot.

**Comment by pixelhandler** [comment]
@amk221 well if you have a moment, can you update your example reproduction to the current release of ember-cli / ember, etc. ? https://github.com/amk221/-ember-fastboot-register-pattern

**Comment by amk221** [comment]
Good idea...

- Using the original demo repo the issue remains
- Upgrading just ember-cli-fastboot from `1.1.3` to `2` in the demo repo does not fix the issue
- Upgrading the entire app from ember/ember-cli `3` to `3.4` and ember-cli-fastboot to `2` fixes the issue

...so somewhere along the line, this has been fixed!

**Comment by locks** [comment]
According to the previous post, this issue has been fixed!
