### ISSUE TITLE
Documentation for RFC 176 modules

### ISSUE THREAD

**Issue by locks** [emberjs/ember.js#15587]
RFC: https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md
Conversion tables: https://github.com/ember-cli/ember-rfc176-data
Ember: https://github.com/emberjs/ember.js/pull/15552
Ember Data: https://github.com/emberjs/data/pull/5108
Ember API Docs: https://github.com/ember-learn/ember-api-docs/issues/299
Guides: https://github.com/emberjs/guides/pull/2004
Ember CLI: https://github.com/ember-cli/ember-cli.github.io/pull/169

## Ember
- [x] Normalize `""`/`''` in imports
- [x] Address minor documentation issues, like typos and formatting
- [x] Update documentation code blocks
- [ ] Update documentation cross-linking (e.g. `Ember.ApplicationInstance` to `ApplicationInstance`)
- [x] Update blueprints and tests
- [ ] Update meta-documentation (`@module`, `@submodule`, etc)

**Comment by jenweber** [comment]
I am going to experimentally try out the `@module/submodule` format in YUIDocs and see how/where it breaks things downstream in [ember-jsonapi-docs](https://github.com/ember-learn/ember-jsonapi-docs) and [ember-api-docs](https://github.com/ember-learn/ember-api-docs)

**Comment by jenweber** [comment]
Here's the impact on the api docs sites/tool chain.

[WIP writeup](https://github.com/ember-learn/ember-jsonapi-docs/issues/35) of how to get the full stack running locally, from ember.js yuidocs, to ember-jsonapi-docs, to ember-api-docs
[
Minimally viable example ](https://github.com/jenweber/ember-api-docs/tree/modules-hack-with-slashes) of @ember/component style modules 

[Minimally viable example](https://github.com/jenweber/ember-api-docs/tree/modules-hack-simple-names) of simply named modules, i.e. "component"

Both have broken modules links. I'm not sure why yet. Both repos should run locally with `ember s`.

**Comment by jenweber** [comment]
To summarize, we can switch the modules documentation to `@module @ember/component` or `@module component` without breaking the website api docs toolchain. We can run the whole stack locally. Website links will work for `@module component` with very slight changes on the front end. To make links work for `@module @ember/component` requires a change to the tooling in jsonapi-docs but I don't think it's anything major.

So this means what we do is dictated by how we want the docs themselves and the documentation blocks to look, not a technical barrier.

**Comment by jenweber** [comment]
Here are some samples of what documentation looks like now, in `packages/ember-routing/lib/system/route.js`
```
/**
@module ember
@submodule ember-routing
*/

/**
  The `Ember.Route` class is used to define individual routes. Refer to
  the [routing guide](https://emberjs.com/guides/routing/) for documentation.

  @class Route
  @namespace Ember
  @extends Ember.Object
  @uses Ember.ActionHandler
  @uses Ember.Evented
  @since 1.0.0
  @public
*/
....
```

Using nested module
```
/**
@module @ember/routing/route
@submodule ember-routing
*/
```

Using simple module names
```
/**
@module route
@submodule ember-routing
*/
```

One benefit of using the nested @ember/package type module names is that developers already need to know how to call for these packages in their code, so it might as well be documented as the module name. For beginner-intermediate Ember devs, it is not intuitive to know what the import line should look like for a given package. One drawback is that the links will need to be redone, so it's a bit more work.

**Comment by locks** [comment]
v2.16.0 is shipped, we'll track in a new issue if necessary.
Thank you so much for the help everyone 😍. There's still a bunch of edge cases, but we can do this 💪.
