### ISSUE TITLE
Ember component: variable set before calling init?

### ISSUE THREAD

**Issue by deepflame** [emberjs/ember.js#15584]
Hi everyone,

while upgrading our app from 1.13 to 2.14 I encountered the following problem described in this Twiddle:

https://ember-twiddle.com/6cfe1e995777bdec6b572108b3fcc939?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs

The expected behaviour is that the `init` function is called before the variable `message` is set in the `name` computed property.

This was working in 1.13 and seems to be a regression to me.

Thanks for all your work on Ember. This is truly a great framework!

Best
Andreas

**Comment by rwjblue** [comment]
This doesn't seem like a bug to me actually.  The properties that you pass into a component **must** be set before `init` (so that they can be accessed from within `init` itself).

**Comment by rwjblue** [comment]
Also, your `name` CP does not have a return value (you have to return from setter CP's or their values are `undefined`).

**Comment by deepflame** [comment]
Hi Robert,

thanks for the reply.
Then I guess I am not sure about the purpose of `didReceiveAttrs`. In my view the attributes were set after `init`, just before `didReceiveAttrs` was fired.

So in my understanding it was not possible to access the attributes at the `init` state, only after `did ReceiveAttrs`.
Guess I am wrong here?

Thanks
Andreas

**Comment by locks** [comment]
@deepflame I'd say that the biggest difference is that `init` is only run once, so you'd initialize any data you need there, but `didReceiveAttrs` runs on first render, and on rerender.

**Comment by deepflame** [comment]
@locks Yes, thanks. This is what I understand from the documentation. However I thought that `init` runs before all attributes are 'consumed'.

This is not a big deal for me currently anymore since I could refactor the code. It was just confusing because the behaviour seemed to change from 1.x to 2.x.

**Comment by locks** [comment]
Yeah, there was a slight changed because we deprecated `didInitAttrs` and moved that to `init`. It didn't make much sense to have both, and I believe there were some optimization concerns with setting the component's properties post-initializing, something about it changing shape?

Welcome to the 2.x series, sorry for the hiccups ;)

**Comment by deepflame** [comment]
I see, thanks for the insights! :)
