### ISSUE TITLE
 Ember should have a default toString for a Mixins that doesn't return the Mixin constructor source code

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#15586]
To track comment https://github.com/emberjs/ember-inspector/pull/704#pullrequestreview-56326413 
This saves a workaround in the ember inspector.

**Comment by meslater1030** [comment]
@cibernox I'd love to take this one. I'm a newbie contributor and it looks reasonably straightforward. Thanks for all your recent work on the inspector!

**Comment by cibernox** [comment]
Please, be my guest 😄 . 

If you need help ping me anytime on Slack.

**Comment by meslater1030** [comment]
Fixed by #15601
