### ISSUE TITLE
Make it possible to differentiate between helpers and properties

### ISSUE THREAD

**Issue by initram** [emberjs/ember.js#15595]
In template code to write out a property named "icon" you would do like this `{{icon}}`, this is fine. The problem is when someone comes along and defines a helper (either locally or in a dependent extension) called "icon" as well, then the code suddenly means something different (it will use the icon helper instead of the icon property). 

So I suggest that you add a way of specifying whether you reference a property or helper, or add the possibility to put extensions into "namespaces". Having all helpers from all extensions in "global scope" is just a name clash waiting to happen.

**Comment by locks** [comment]
Hi, feature requests should go to https://github.com/emberjs/rfcs/issues, can you move this issue there? Thank you.
