### ISSUE TITLE
[bug] Using the `set` inside `it` does not work on ember-mocha.

### ISSUE THREAD

**Issue by aureliosaraiva** [emberjs/ember.js#15590]
I could not simulate the problem using `ember-twiddle.com`, so I created an Ember application to simulate the problem.

https://github.com/aureliosaraiva/ember-app-bug-mocha

[my-component.js](https://github.com/aureliosaraiva/ember-app-bug-mocha/blob/master/app/components/my-component.js)
[my-component-test.js](https://github.com/aureliosaraiva/ember-app-bug-mocha/blob/master/tests/integration/components/my-component-test.js) 

```javascript
import { expect } from 'chai';
import { describe, it } from 'mocha';
import { setupComponentTest } from 'ember-mocha';
import hbs from 'htmlbars-inline-precompile';
import EmberObject, { set } from '@ember/object';


describe('Integration | Component | my component', function() {
  setupComponentTest('my-component', {
    integration: true
  });

  it('its working', function() {
    const modelFake = EmberObject.create({
      fullName: 'foo bar'
    });

    this.set('model', modelFake); // working
    this.render(hbs`{{my-component model=model}}`);
    expect(this.$()).to.have.length(1);
  });

  it('its not working', function() {
    const modelFake = EmberObject.create({
      fullName: 'foo bar'
    });

    set(this, 'model', modelFake); // not working
    this.render(hbs`{{my-component model=model}}`);
    expect(this.$()).to.have.length(1);
  });
});

```

![screenshot from 2017-08-17 22-57-54](https://user-images.githubusercontent.com/118861/29441147-981ba57c-839f-11e7-90b8-94f6ed928f83.png)

**Comment by aureliosaraiva** [comment]
For `Embe.set()` to function it needs `getContext()`
https://github.com/emberjs/ember-mocha/blob/master/lib/ember-mocha/setup-test-factory.js#L22

https://github.com/emberjs/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-component.js#L264

But, `this` available within it is not the same as the context needed for `Ember.set` to work.

**Comment by Turbo87** [comment]
this is a restriction of how Mocha tests work and can not be worked around in a reasonable way

**Comment by locks** [comment]
Closing according to @Turbo87's comment.
Thanks everyone!

**Comment by aureliosaraiva** [comment]
@Turbo87 
I agree with you, I analyzed the operation and I did not find a way to solve this problem in the mocha. Unfortunately this works on `ember-cli-qunit`. Another point is to have false/positive for this rule of eslint.

Https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/use-ember-get-and-set.md

But thanks for answering fast! :+1:

**Comment by Turbo87** [comment]
IMHO that eslint rule is stupid and should not be used...

**Comment by rwjblue** [comment]
HAHAHA, you know what they say about opinions...

**Comment by aureliosaraiva** [comment]
I even agree with you @Turbo87, for me this rule is enabled because it is enabled by default as a recommendation `eslint-plugin-ember`.

If it is a stupid rule, why do we have it enabled by default? hahaha :stuck_out_tongue_winking_eye:

I've also had problems with `ember-cli-mirage` where I needed to set the response of an api using` server.get ('my-url') `.

**Comment by Turbo87** [comment]
> this rule is enabled because it is enabled by default as a recommendation eslint-plugin-ember.

I said it before and I will say it again: `eslint-plugin-ember` should be unopinionated and only provide rules, but no recommended rulesets...

> I've also had problems with ember-cli-mirage where I needed to set the response of an api using server.get ('my-url').

`server.get()` is entirely unrelated to the `get()` function from Ember. replacing `anything.get(...)` with `get(anything, ...)` just doesn't work.
