### ISSUE TITLE
API docs for Ember.Test.wait have an incomplete markdown block

### ISSUE THREAD

**Issue by myartsev** [emberjs/ember.js#15617]
https://www.emberjs.com/api/ember/2.14/classes/Ember.Test/methods/wait?anchor=wait

I am assuming the API documentation is built from the source itself?
https://github.com/emberjs/ember.js/blob/9a9585fc8d8286a62baadce8b733534f94e38db5/packages/ember-testing/lib/helpers/wait.js

If so; everything appears to be fine there, but for some reason the API website is not rendering the _example_ markdown block for the wait helper correctly.

![screenshot - 08312017 - 10 41 28 am](https://user-images.githubusercontent.com/4885345/29942032-ea3d76f4-8e40-11e7-85e8-5b914773f3c5.png)

**Comment by locks** [comment]
Thank you for reporting, this was fixed in [2.15](https://www.emberjs.com/api/ember/2.15/classes/Ember.Test/methods/wait?anchor=wait), release just some hours ago :)
Due to the nature of releases, 2.14 is unlikely to be updated since it's unlikely that it gets another patch release.
