### ISSUE TITLE
[v2.16.0-beta.1] Bug: destroying components that use {{#-in-element}}

### ISSUE THREAD

**Issue by kybishop** [emberjs/ember.js#15619]
`Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`:

As discovered here https://travis-ci.org/kybishop/ember-attacher/jobs/270579964#L611

Context:

The test renders a component that uses `{{#-in-element}}` under the hood. The component is nested in an `{{#if}}` that toggles to `false` later in the test. When the component is subsequently destroyed, the above error is thrown and the test fails.

**Comment by kybishop** [comment]
Here is the closest I can provide to a reproduction: https://ember-twiddle.com/cea8fd6693c7fe4870e3243deafbfed0?fileTreeShown=false&openFiles=controllers.application.js%2C

Ember-twiddle is a bit behind on ember versions, so one can't actually switch to the beta yet, but that's an easy template to reproduce locally in a test or whatnot.

**Comment by urbany** [comment]
If you make your twiddle.json like this it will use the ember@beta:
```json
{
  "version": "0.12.1",
  "EmberENV": {
    "FEATURES": {}
  },
  "options": {
    "use_pods": false,
    "enable-testing": false
  },
  "dependencies": {
    "jquery": "https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.js",
    "ember": "beta",
    "ember-template-compiler": "beta",
    "ember-testing": "beta"
  }
}
```

In the console:
```
DEBUG: -------------------------------
DEBUG: Ember  : 2.16.0-beta.1
DEBUG: jQuery : 1.11.3
DEBUG: -------------------------------
```

I tried that with your twiddle and it seems to work fine, couldn't reproduce the issue.

**Comment by kybishop** [comment]
Thanks @urbany! I think my twiddle was borked from attempting to add ember-data.

I'll work on the repro to isolate what is wrong. I have a handful of ideas from my broken (only in beta) test. Closing this until I can narrow down the problem.
