### ISSUE TITLE
"EventDispatcher should never be instantiated in fastboot mode. Please report this as an Ember bug."

### ISSUE THREAD

**Issue by mdebbar** [emberjs/ember.js#15615]
Ember version: `ember-source@2.14.1`

When the app runs on the server side, I’m hitting few service injection errors of this kind:
```
Attempting to inject an unknown injection: 'service:xyz'
```

After some digging with @krisselden, we found that there's an error thrown (and swallowed) earlier in EngineInstance's `cloneParentDependencies()` method. The error is:
```
EventDispatcher should never be instantiated in fastboot mode. Please report this as an Ember bug.
```
So here I am, reporting an Ember bug as the error told me 🙂

I did some more digging and found an explanation to the swallowing of the real error. The error happens during the `boot` of an engine. The engine's `boot()` method correctly [returns a rejected promise](https://github.com/emberjs/ember.js/blob/v2.14.1/packages/ember-application/lib/system/engine-instance.js#L80) because of that error. Then that promise [is ignored](https://github.com/ember-engines/ember-engines/blob/master/addon/-private/router-ext.js#L254) and the app continues running as if nothing happened.

**Comment by mdebbar** [comment]
It seems like the issue was introduced by [this commit](https://github.com/emberjs/ember.js/commit/94f188ad47f1c58fe8444b837594c777d2b0d0cb). The `event_dispatcher` was moved from the `registrations` list to the `singletons` list. The difference being that registrations are only resolved at this point, but singletons are eagerly looked up and instantiated.

A possible fix would be to check if running in a server-side environment, don't add `event_dispatcher:main` to the singletons list.

**Comment by rwjblue** [comment]
Sorry for the delay here, but I finally got the fix submitted in https://github.com/emberjs/ember.js/pull/15695.
