### ISSUE TITLE
queryParams array attribute becomes a string if other attribute changes before model is resolved

### ISSUE THREAD

**Issue by mpugach** [emberjs/ember.js#15611]
See [this twiddle](https://ember-twiddle.com/4e746489c6021ed3ca6b20b7fecc47af) please.

There are two queryParams:
- `categories` array
- `searchQuery` string

The model resolves the current time with a 1-second timeout.

Steps:
1. Open the console and see the current value of `categories`.
2. Add at least one category by hitting the "Add category" button (do not enter anything into the text input on this stage).
3. Observe `categories` is still an array in the console.
4. Enter any text into the input field.
5. If the `searchQuery` is modified before the transition completes, the `categories` becomes a string. From this point, it becomes even worse with every modification because it escapes escape symbols on every iteration.

**Comment by MikiDi** [comment]
I can confirm above issue (with Ember 3.17, Firefox 79.0).  

Steps to reproduce:
- define 2 query params as described above
- Have some change to the array content trigger a model reload (make sure it's not in the default state, so it appears in the URL)
- In the `beforeModel`-hook, make a change to the `searchQuery` string ("the other query param")

From this point on, you should see the array query param getting escaped recursively

**Comment by rreckonerr** [comment]
Can you please check if #19236 fixes the issue?

**Comment by mpugach** [comment]
@rreckonerr, thank you for your contribution!

Have you tried modifying [twidle.json](https://ember-twiddle.com/4e746489c6021ed3ca6b20b7fecc47af)? Because constructing the dummy application locally in the nearest future is too much for me.

**Comment by rwjblue** [comment]
Ya still seems to be an issue with 3.22.1. https://ember-twiddle.com/2d80d71daa9a9a99676aef471cb55b90?openFiles=templates.application.hbs%2C

**Comment by rwjblue** [comment]
This seems like the same as what @mfeckie is working on over in https://github.com/emberjs/ember.js/pull/19145.

**Comment by sly7-7** [comment]
@rwjblue I've reproduced your twiddle in https://github.com/sly7-7/ember-repro-15611 (ember 3.25.1), and it looks like this is fixed.
So I guess this could be closed, and #19145 maybe not necessary

**Comment by rwjblue** [comment]
Thanks @sly7-7!
