### ISSUE TITLE
[v2.15.0] Bug declaring the same component attribute twice (creates a mutableCell)

### ISSUE THREAD

**Issue by urbany** [emberjs/ember.js#15618]
Hi, I just updated from 2.14 to 2.15 and found a weird "bug". By mistake I was rendering a component passing the same attr twice, like this: `{{my-component componentVar=myStringVar componentVar=myStringVar}}`

I know this makes no sense, but it was working correctly in 2.14
In 2.15 it doesn't work. Suddenly `componentVar` is no longer the `myStringVar` but instead is a mutable cell object.

I created a twiddle with a reproduction, check the console also.
https://ember-twiddle.com/c1f4d778120fe303436b0e5df029fcf2

Not saying this should be supported, but maybe throw an error? It can be difficult to debug the way it is.

**Comment by Gorzas** [comment]
@urbany I've found the same problem but with Ember version 2.14.

**Comment by Serabe** [comment]
Thank you for the report!

**Comment by bekzod** [comment]
probably related https://github.com/emberjs/ember.js/issues/11202

**Comment by kyleshay** [comment]
FYI - there is a new template linter rule against this issue:
https://github.com/rwjblue/ember-template-lint/blob/master/docs/rule/no-duplicate-attributes.md
