### ISSUE TITLE
Clarify Ember.run.scheduleOnce documentation

### ISSUE THREAD

**Issue by mwpastore** [emberjs/ember.js#15620]
The Ember.run.scheduleOnce documentation states that:

https://github.com/emberjs/ember.js/blob/04ac480e923ab7f345e30b7aad683bea2ffb7193/packages/ember-metal/lib/run_loop.js#L382-L391

I've been musing on this all evening, and I have a nit to pick. The problem isn't necessarily that it's an anonymous function, it's that the function is "instantiated" on each call of `scheduleIt()`. I could easily do this to "solve" the problem:

```javascript
function scheduleIt() {
  function logIt() {
    console.log('Closure');
  }

  run.scheduleOnce('actions', myContext, logIt);
}
```

My `logIt()` function is not anonymous, but I still have the same problem: scheduleOnce can't dedup it, because it's always a new instance. (Right?) 

Contrarily, I could easily do this to actually solve the problem:

```javascript
const logIt = function() {
  console.log('Closure');
};

function scheduleIt() {
  run.scheduleOnce('actions', myContext, logIt);
}
```

My `logIt()` function is anonymous, but scheduleOnce *can* dedup it, because it's always the same instance. (Right?)

Am I completely looney, or is there an opportunity to improve the documentation here?

**Comment by Serabe** [comment]
Thank you!

**Comment by mwpastore** [comment]
@Serabe Ah, fantastic. Thank YOU!
