### ISSUE TITLE
Feature suggestion: Percolate stack traces

### ISSUE THREAD

**Issue by rocifier** [emberjs/ember.js#15639]
Ember stacktraces are hard to debug due to the asynchronous nature of javascript and the run loop. Could we do something like https://www.npmjs.com/package/async-stacktrace does and track the stack traces right through the loop, even if it's only on ember debug builds or something? This would make tracking the origin of exceptions much easier, as this is a large hurdle for newcomers.

**Comment by locks** [comment]
Thanks for the suggestion, moved to the RFC repository.
