### ISSUE TITLE
link-to triggers didRender when leaving a route

### ISSUE THREAD

**Issue by fly1ted** [emberjs/ember.js#15642]
Any component with a link-to helper inside fires didRender when current route changes to a route with the model() containing a Promise with a delay.

I assume this is due to the fact that link-to wants to update its active class watcher. Current route's template is still displayed thus didRender happens.

It's not obvious that didRender may happen from not only attributes change but an internal helper's state. It feels like a hidden binding.

An [example on scrolling](https://guides.emberjs.com/v2.14.0/components/the-component-lifecycle/#toc_making-updates-to-the-rendered-dom-with-code-didrender-code) in Components Lifecycle will cause an error at `this.$('.item-list').scrollTop(this.$('.selected-item').position.top);` because this.$() doesn't exist anymore.

**Comment by pixelhandler** [comment]
@fly1ted thanks for posting the issue. to verify a bug in the Ember framework the next step is to create a working example. Can you create a reproduction of the issue using http://ember-twiddle.com (or with an example product using ember-cli) ?

Also one guard that I often use when there is a condition in my app that results in a component being destroyed, and/or also re-created, is to check if the state of the object is either `isDestroying` or `isDestroyed`. If the component has one of those properties as `true` then I block any attempt to `set` on the component, or use the DOM element (of the component itself).

**Comment by fly1ted** [comment]
I tried to reproduce it in [twiddle](https://ember-twiddle.com/1ee29c14a49fe8c27e250558ace6176e?route=%2Fr1) and it looks like `this.$()` is defined and doesn't cause any errs. I've checked the code I had and it turns out that I was using `run.debounce` and thus got an err. Canceling the debounce on `willDestroyElement` fixed it in the end. So, false alarm afterwards. Thanks for your attention.
