### ISSUE TITLE
2.14.1: MutableCells where there wasn't before

### ISSUE THREAD

**Issue by artcommacode** [emberjs/ember.js#15640]
Hi, 

In upgrading from 2.14.0 to 2.15.0 I noticed that calling `{{value}}` or `this.get('value')` in some of my code was now returning `MutableCell`s rather than the value directly. I downgraded all the way back to 2.14.0 and found the issue started occurring when the `ember-source` package was updated from `2.14.0` to `2.14.1`. 

This is possibly related to #15618 but I don't believe I'm passing the same attr more than once to a component.

Unfortunately I'm unable to provide a simple test-case as I'm not familiar enough with the code I'm working on or with Ember itself. Please let me know if there's anything else I can provide for you.

**Comment by pixelhandler** [comment]
@artcommacode it is really hard to trouble shoot without a working example, a reproduction of the issue to investicate. Perhaps you can reach out in the ember community slack to find help - https://embercommunity.slack.com/ `#-help` channel. To get an invite to join the slack channel visit: https://ember-community-slackin.herokuapp.com/

**Comment by rwjblue** [comment]
@artcommacode - Have you had a chance to create that reproduction yet?

**Comment by artcommacode** [comment]
Hi @rwjblue, thanks for the follow-up, I'm currently trying to learn as much as possible about Ember as I can so that I can reproduce it for you all!

**Comment by urbany** [comment]
Might be related to this? https://github.com/emberjs/ember.js/issues/15618

**Comment by Serabe** [comment]
We are closing this issue according to [our triage policy](https://github.com/emberjs/ember.js/blob/9057741de71a7b261ef13a09920fe472919dd68b/CONTRIBUTING.md#triaging-policy).

You can reopen it with a reproduction at any time.

Thank you!

**Comment by artcommacode** [comment]
I'm finally knowledgeable enough in Ember and our project to see what was going on here and it was indeed exactly the same as #15618. Thanks for your patience!

**Comment by fpauser** [comment]
Same issue here. Reproduction: https://github.com/fpauser/ember-mutable-cell-reproduction
