### ISSUE TITLE
Route ```model``` hook is not run on transition in Ember 2.15

### ISSUE THREAD

**Issue by mani-mishra** [emberjs/ember.js#15661]
In ember 2.15, route's ```model``` doesn't run when transitioning from a parent route.
For example:
If the app is currentnly, at ```/student``` and displays student list, selecting a student, transitions to ```student/<id>```. The ```model``` hook in route for ```student/<id>``` is not run. 
All other hooks run, in order of  ```beforeModel``` => ```afterModel``` => ```setupController``` 
 
This doesn't happen, when I directly load the route via hard refresh of ```student/<id>```.

Previous to ember 2.15, hooks run in ```beforeModel``` => ```model``` => ```afterModel``` => ```setupController``` in all cases.

**Comment by rwjblue** [comment]
We have a number of tests in this area that are not showing a regression so I suspect that what you are experiencing is situational or dependent on some other factors.  Can you create a reproduction that shows the problem you are describing?

**Comment by mani-mishra** [comment]
@rwjblue On more detailed debugging, the issue that we are seeing is a result of https://github.com/emberjs/ember.js/issues/15621. We are trying to pass the id param of the route, from a partial, which comes as ```undefined```. 

I'll close this issue.

**Comment by rwjblue** [comment]
Thanks for following up, we're trying to prioritize #15621 so we can get a fix out soonish. Sorry for the delays there.
