### ISSUE TITLE
Refreshing a data model does not update bound computed properties

### ISSUE THREAD

**Issue by myartsev** [emberjs/ember.js#15669]
I have a router which refreshes its data model on demand.

```
  actions: {
    invalidateModel() {
      this.refresh();
    }
  }
```

A component is passed this model, and if used directly, the changes are updated as expected:

```
{{#each model as |m|}}{{m.bar}}{{/each}}
```

However, if I use a computed property, the updates from a data model refresh in the router are not carried through to the computed property in a component.

```
  computedModel: Ember.computed('model', function() {
    return this.get('model').map(function(m) {
      return `Computed: ${m.data.bar}`;
    });
  }),
```

```
{{#each model as |m|}}{{m}}{{/each}}
```

I realize this is a contrived example, but it helps to illustrate the point.
Full reproduction at: https://github.com/myartsev/ember-computed-properties-on-data-model
The latest commit is using the non-updatable computed properties.
The [previous commit](https://github.com/myartsev/ember-computed-properties-on-data-model/commit/3e8a76d59e0981b62b92142b506e21be809c2739) is using the data model directly which is updating just fine.

Should I be digging deeper into the data structure to get the computed property to work properly (the data model is coming from a JSONAPI backend), or is there something else to this? I imagine digging into the data structure might be ugly and potentially error prone if its structure changes with future ember data updates.

**Comment by kumkanillam** [comment]
This [SO answer](https://stackoverflow.com/a/46211471/5771666) is the right answer to your question.

**Comment by pixelhandler** [comment]
@myartsev does using `'model.[]'` as the dependent key for your computedModel work?

- https://guides.emberjs.com/v2.15.0/object-model/computed-properties-and-aggregate-data/#toc_code-code-vs-code-each-code

**Comment by myartsev** [comment]
@kumkanillam the SO answer works for that scenario, but it is not *my* scenario. I didn't want to have an extended discussion on SO, as it's not the right place for a lengthy, usually it's a place to answer the question given and this time it happened to get derailed.

@pixelhandler using 'model.[]' does indeed work if the length of the array being returned changes; as is the case in the SO answer ember-twiddle, where each time the model is refreshed a new item is added. However, my situation is different. A model refresh does not alter the length of the array, only the contents inside of the array. In the case of the [contrived github repo](https://github.com/myartsev/ember-computed-properties-on-data-model/blob/master/server/index.js), it's the  *bar* property that gets updated with a random value.

Looking into it further, the way to accomplish that was to do:
`computedModel: Ember.computed('model.@each.bar', function() {`
