### ISSUE TITLE
Ember.Test.registerWaiter dev vs prod

### ISSUE THREAD

**Issue by bcardarella** [emberjs/ember.js#15670]
When destructuring `Ember.Test.registerWaiter` like so:

```js
const {
  Test: { registerWaiter }
} = Ember;
```

breaks prod due to `Ember.Test` being `undefined`.

I would move over to the `import` but I do not see `Ember.Test.registerWaiter` let alone `Ember.Test` defined anywhere in the RFC: https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md

It would seem reasonable for prod builds to have `Ember.Test === {}` for the purposes of maintaining code styling. I would suspect that the `import`s will require some exporting of `null`s.

**Comment by bcardarella** [comment]
If I recall anything wrapped in `if (Ember.testing)` is stripped from prod builds, right? I guess I could do:

```js
if (Ember.testing) {
  const {
    Test: { registerWaiter }
  } = Ember;
}
```

**Comment by rwjblue** [comment]
In general, this sort of destructuring shouldn't be needed (the imports should be used instead). 

```
import { registerWaiter } from '@ember/test';
import { DEBUG } from '@glimmer/env';

//...snip...

if (DEBUG) {
  registerWaiter(.....);
}
```

The register waiter import and invocation will be removed as dead code in production builds. I wrote a bit about this in http://rwjblue.com/2017/05/01/enabling-debug-code-stripping/.

**Comment by bcardarella** [comment]
@rwjblue as I mentioned in the issue, the RFC doesn't provide guidance for `ember/test` so the modules addon by @martndemus doesn't include it. AFAIK only beta channel has the modules implemented. I'd prefer not to use beta builds in production. With the global Ember import is there any way to destructure `registerWaiter` and not blow up prod builds?

**Comment by bcardarella** [comment]
FWIW, my temporary fix is to add the following to `app.js`:

```js
if (!Ember.testing) {
  Ember.Test = {
    registerWaiter() {

    }
  };
}
```

I'm OK with this until 2.16 is release, but if there is a better way I'm happy to do that as well :)

**Comment by rwjblue** [comment]
>  the RFC doesn't provide guidance for ember/test

Yep, we identified that somewhat early on in the implementation phase of the RFC.  RFC's are not maintained over time, and often times the final implementation is different due to issues found during implementation.  You can find the current canonical public "Ember Modules API" data in [ember-cli/ember-rfc176-data](https://github.com/ember-cli/ember-rfc176-data)'s README. This repo is used by tooling such as the ember-modules-codemod, eslint-plugin-ember, and ember-cli-babel so that they can all share the module mapping / definitions.

> the modules addon by @martndemus doesn't include it

I opened an issue over there (https://github.com/DockYard/ember-new-modules-shim/issues/5) to ensure we get a deprecation notice added to that package.  

> AFAIK only beta channel has the modules implemented. I'd prefer not to use beta builds in production. 

As I mentioned in my comment, the only requirement for my suggestion in https://github.com/emberjs/ember.js/issues/15670#issuecomment-329980787 is that the app or addon have a new enough ember-cli-babel version. Support for that snippet is completely unrelated to ember-source, ember-cli, ember-new-modules-shim, ember-cli-shims, etc.

**Comment by bcardarella** [comment]
Great, thank you!

**Comment by bcardarella** [comment]
Reopening. I have implemented as instructed above. ember-cli-babel 6.3 is installed. In prod I am getting: `TypeError: Cannot read property 'registerWaiter' of undefined`

**Comment by bcardarella** [comment]
correction, I have ember-cli-babel `^6.3.0` declared in `package.json` but `6.8.2` is installed

**Comment by rwjblue** [comment]
Ugh. Sorry. I'll try to repro and see what's going wrong...

**Comment by bcardarella** [comment]
Example repo: https://github.com/bcardarella/register-waiter-fail/blob/master/app/controllers/application.js#L2

Stack trace: 
<img width="1396" alt="screen shot 2017-09-18 at 4 11 43 am" src="https://user-images.githubusercontent.com/18524/30533478-8374cfa4-9c27-11e7-93ce-562c8b1122c2.png">

**Comment by bcardarella** [comment]
This is my temporary work-around to solve the import issue: (previous work around was for destructuring)

```js
/* eslint-disable ember-suave/no-direct-property-access, no-undef */
if (typeof Ember.Test === 'undefined') {
  Ember.Test = {
    registerWaiter() {

    }
  };
}
/* eslint-enable ember-suave/no-direct-property-access, no-undef */
```

**Comment by rwwagner90** [comment]
We're on ember-cli-babel 6.9.x and just hit this issue using `import { registerWaiter } from '@ember/test';`.

Any ideas?

**Comment by rwjblue** [comment]
Sorry for the delays here. I believe this is resolved in the latest version of `ember-cli-babel@6.11.0`.  

Thanks to @Serabe for fixing the underlying issue (in https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/pull/29).

**Comment by rwjblue** [comment]
Closing this for now, but I'm happy to reopen if I am mistaken about the fix...

**Comment by allthesignals** [comment]
Seeing this again, here are my versions:

```
    "ember-cli-babel": "^7.7.3",
    "ember-cli-qunit": "^4.3.2",
    "ember-source": "~3.10.0",
    "qunit-dom": "^0.8.4"
```
