### ISSUE TITLE
Observer is triggered only once in case observed property is not consumed during callback

### ISSUE THREAD

**Issue by janmisek** [emberjs/ember.js#15679]
In case observed computed in not consumed during observer callback further observing is not triggered. It is reproducible at least on 2.13 and 2.15.

Reproduction code from the docs (https://guides.emberjs.com/v2.15.0/object-model/observers/), 

slightly modified:

```
const Person = Ember.Object.extend({
  // these will be supplied by `create`
  firstName: null,
  lastName: null,

  fullName: Ember.computed('firstName', 'lastName', function() {
    return `${this.get('firstName')} ${this.get('lastName')}`;
  }),

  fullNameChanged: Ember.observer('fullName', function() {
    // deal with the change
    console.log('fullName changed'); // fullName not consumed
  })
});

let person = Person.create({
  firstName: 'Yehuda',
  lastName: 'Katz'
});

// observer won't fire until `fullName` is consumed first
person.get('fullName'); // "Yehuda Katz"

// we modify first name periodically to trigger observer
setInterval(function() {
  person.set('firstName', Math.random());
}, 1000);

```
Code above will log to console only first `fullName changed` entry. But it should log one each every second.

In case we modify code above to contain consumption of observed property it will start to work properly:
```
  fullNameChanged: Ember.observer('fullName', function() {
    console.log('fullName changed', this.get('fullName'));
  })
```

**Comment by bekzod** [comment]
@janmisek have you tried wrapping `person.set('firstName', Math.random());` `run loop`, 
like so 
```
setInterval(function() {
Ember.run(function() {
  person.set('firstName', Math.random());
})
}, 1000);
```

**Comment by janmisek** [comment]
@bekzod 

Even with Ember.run it behaves in same way.  The observer is triggered only once when computed property is not consumed in observing callback.

**Comment by bekzod** [comment]
@janmisek 

I think `ember` is correctly behaving here, since `computed` properties are lazily evaluated it value changes when consumed only, so observer is triggered only when consumed.
If you have real use-case with such scenario, I think you can use computed property instead of observer or observe on primitive value that first computed is observing.

**Comment by rwjblue** [comment]
Agreed. The computed property (fullName here) is essentially marked as dirty, but does not recompute its value to determine if it has changed until it is `.get`'ed again.
