### ISSUE TITLE
Misleading "backtracking re-render" assert message

### ISSUE THREAD

**Issue by myartsev** [emberjs/ember.js#15678]
See [this twiddle](https://ember-twiddle.com/8fb61e73a7fe8b6430c2cd83934e9da0?openFiles=controllers.application.js)

```javascript
fooButtonText: Ember.computed('x', function() {
    console.log('*');
    this.toggleProperty('isSavingDisabled');
    
    return "foo";
  }),
  
  actions: {
   toggleFoo() {
      //this.toggleProperty('isSavingDisabled');
      this.set('x', Math.random());
    }
  }
```

```html
<button type="button" {{action 'toggleFoo'}}>Disable/enable button below</button>
<br>
<br>
<button type="button" disabled={{isSavingDisabled}}>{{fooButtonText}}</button>
```

`Assertion Failed: You modified "isSavingDisabled" twice on <twiddle@controller:application::ember182> in a single render. It was rendered in "template:twiddle/templates/application" and modified in "template:twiddle/templates/application". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.`

I'm puzzled; how is this modifying _isSavingDisabled_ twice in a single render?

**Comment by myartsev** [comment]
My guess is that this assertion is hit because _fooButtonText_ has already been rendered in the template, and when the computed property gets updated, it is modifying _fooButtonText_ again. That makes sense, but it has nothing to do with _isSavingDisabled_.

What threw me off was the error message, and it took me a while to figure out.
It was easy to see what's going on when looking at this simplified example, but it was difficult to narrow down when working on a real world application.

**Comment by myartsev** [comment]
Also - as for the usage pattern; what can you do in such a situation? Am I not seeing an obvious design flaw in my sample code?

This is the only solution I've been able to come up by tricking Ember into updating these values at delayed render run loops, but of course it's not ideal...
```javascript
  fooButtonText: Ember.computed('x', function() {
    console.log('*');
    var self = this;
    Ember.run.schedule('afterRender', function() {
    	self.toggleProperty('isSavingDisabled');
    });
    
    return "foo";
  }),
  
  actions: {
  	toggleFoo() {
      //this.toggleProperty('isSavingDisabled');
      var self = this;
      Ember.run.schedule('afterRender', function() {
        self.set('x', Math.random());
      });
    }
```

See [this twiddle](https://ember-twiddle.com/2fd7575e4dd580082e07da1234e1cdb1?openFiles=controllers.application.js)

**Comment by Serabe** [comment]
I tend to use `Ember.run.once` when having these kind of strange side effects in a CP. Much more when the state of the CP would not change.

Given the example lacks meaning, I cannot propose a better design, but these kinds of relationships are strange in the real world IMHO.

See that the message is right because the thing being changed twice in a single render is `isSavingDisabled` and that change can come from different places.

Thank you!
