### ISSUE TITLE
Component isDestroying flag is false during willDestroyElement event function

### ISSUE THREAD

**Issue by williamhector** [emberjs/ember.js#15684]
In 2.15, during willDestroyElement, the isDestroying flag is false.
Here is a twiddle: https://ember-twiddle.com/212aa353e739fcdefd1d92ac6ba4d1ba?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs
(I'm not sure why, but on loading that twiddle into a new browser tab, I needed to choose an Ember version under Dependencies for it to properly render)

I was previously using 1.13 and this issue wasn't present. 
However, when I select 1.13 in the twiddle, the issue _**is**_ present.

This may not be a widespread issue because checking for isDestroying during the willDestroyElement function is redundant in many use cases.
I'm able to refactor my code to avoid this issue, but other's may not be able to.

**Comment by krisselden** [comment]
isDestroying has to do with the object model teardown not the component being removed from DOM.

**Comment by williamhector** [comment]
Fair enough. 
Then it would seem like isDestroying was simply coincidentally true during willDestroyElement in 1.13, unless I'm missing something.
