### ISSUE TITLE
Route actions `error` prevents error-template from rendering

### ISSUE THREAD

**Issue by sbatson5** [emberjs/ember.js#15682]
Hi All!

If I have a route `foo` with an error template `foo-error`, it will render when ever an error is thrown in my model hook. However, if I want to catch that error in the route through the `error` action, the template never appears. My first assumption was that `this._super(...arguments)` would take care of it as there may be some behind-the-scenes magic I'm not aware of, but that doesn't seem to be the case. Plus, I couldn't find anything documentation around the error action doing anything other than providing the error and the transition.

There is a twiddle here:
https://ember-twiddle.com/a853619b6f8cafea25c57c7d77faa1ff?openFiles=routes.foo.js%2C

Browse to the /foo route and notice that no error template appears.  Comment out the `error` action and it works as expected.

Let me know if I missed something obvious or if this behavior is documented anywhere.

**Comment by Serabe** [comment]
Error is an action and, as such, you need to let it bubble if you want to get the default behaviour. In this case, you `return true;`, `this_super` does not get the desired behaviour.

[This is a twiddle showing it](https://ember-twiddle.com/569187a1f8845f97969cf83b844d6af6?openFiles=routes.parent.child.js%2C).

I will improve the documentation to explicitly explain this.

**Comment by rwjblue** [comment]
Yes, @Serabe is totally correct here.  

@Serabe - Thanks for working on updating the documentation, I'm going to close this for now (since it isn't a bug)...
