### ISSUE TITLE
Range input does not work with negative values

### ISSUE THREAD

**Issue by locks** [emberjs/ember.js#15681]
Reproduction: https://ember-twiddle.com/6be2f6ac503c9248a991171c159b7f03?openFiles=templates.application.hbs%2C

**Comment by rwjblue** [comment]
Was already fixed by @Serabe's PR.  Demo: https://ember-twiddle.com/debe6062d7806aea6a7b95bcf46ae5b7?openFiles=twiddle.json%2C

**Comment by locks** [comment]
Derp derp, I wasn't finding any mentions through GitHub search. Thanks!
