### ISSUE TITLE
Binding actions to a component helper fails if the component is changed dynamically

### ISSUE THREAD

**Issue by annaemu** [emberjs/ember.js#15680]
In a route lives a slide-out panel that shows a 'quick quote' workflow. This initially shows a default component, but the user can navigate back and forth through a bunch of steps.

```
{{#component qqComponent onNavigate=(action 'navigateQuickQuotePanel')}}
    {{yield}}
{{/component}}
```

Which component is displayed is determined by the 'qqComponent' property. The action 'navigateQuickQuotePanel' changes the value of 'qqComponent' based on passed parameters:

```
navigateQuickQuotePanel(component) {
    set(this, 'qqComponent', component);
},
```

This works fine initially and when the value of qqComponent changes, a new component is displayed. However, at that point it appears that the 'onNavigate' property, which should be pointing to the 'navigateQuickQuotePanel' action, is actually null (as the action does not seem to have been rebound to the new displayed component).

Binding properties in this manner works fine. For example, where I have the below and the displayed component modifies these properties directly, it works fine.

```
{{#component qqComponent navigateComponent=qqComponent}}
     {{yield}}
{{/component}}
```

Please note the quick quote cannot be done through routes, as the overlay can appear over any route in the website.

I'm fairly new to emberjs so I'm not sure if I am missing something, if this is intended behaviour, or if it isn't working as intended.

**Comment by Serabe** [comment]
I worked a bit on this the other day and today, but I cannot really reproduce it.

[This is a working Twiddle](https://ember-twiddle.com/0dc84dbb8e0f3255eefd2d48efa9b4f1?openFiles=templates.application.hbs%2Ctemplates.components.b-component.hbs)

Can you send a reproduction, either via repo or via Ember Twiddle?

Thank you!

**Comment by Serabe** [comment]
@annaemu ping.

**Comment by Serabe** [comment]
Closing this according to [our triage policy](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy). Please, provide a reproduction so we can follow up on this.

Thank you!
