### ISSUE TITLE
Model state transition from `root.updated.invalid` to a clean state doesn't work

### ISSUE THREAD

**Issue by svenpl** [emberjs/ember.js#15693]
After updating an invalid record manually to a clean state, the state of the model is set as `root.updated.uncommited` instead of `root.loaded.saved` which will make `hasDirtyAttributes` return `true` even if the record is not dirty.

1. I got a saved record with the attribute 'name'. The state is `root.loaded.saved`. 
2. I change the attribute 'name'  and call `save` on the record (beforehand i ensured that the server would respond with an validation error on the attribute 'name'). 
After Ember got the server respond the state changes to `root.loaded.updated.invalid`. 
3. I update the attribute 'name' again to the original value. The state changes to `root.updated.uncommited` instead of `root.loaded.saved`.

The correct state will only be set after I update the record again.

Here is a [twiddle](https://ember-twiddle.com/ace646045610d33b15e54005123be217?openFiles=templates.application.hbs%2C) which reproduces this bug.

**Comment by locks** [comment]
Thanks for reporting with a reproduction. Moved to https://github.com/emberjs/data/issues/5201
