### ISSUE TITLE
(action) helper target with a DS.PromiseObject

### ISSUE THREAD

**Issue by mwpastore** [emberjs/ember.js#15708]
I have an action defined on a DS.Model, and a DS.PromiseObject of an instance in my template. With something like this:

```hbs
{{#with project.shippingAddress as |addr|}}
  {{one-way-select addr.country
      options=COUNTRIES_LIST
      update=(action 'setCountry' target=addr)}}
{{/with}}
```

I get the following error:

```console
Assertion Failed: An action named 'setCountry' was not found in <DS.PromiseObject:ember1224>
```

I'm working around it using the [ember-bind-helper](https://github.com/Serabe/ember-bind-helper) addon:

```hbs
{{#with project.shippingAddress as |addr|}}
  {{one-way-select addr.country
      options=COUNTRIES_LIST
      update=(bind addr.actions.setCountry)}}
{{/with}}
```

But it would be nice if I didn't need that!

**Comment by sly7-7** [comment]
Maybe `update=(action 'setCountry' target=addr.content)` ?

**Comment by Serabe** [comment]
Action expects an object with an actions hash. It is not going through `get` in any kind, so yes, in this case you would need to go by adding the target manually.

Thanks!
