### ISSUE TITLE
Incorporate auto-dist-tag into npm publishing scripts.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#15721]
Currently, if an older non-prerelease version is published after the next minor release is stable the npm `latest` tag is changed to the older release.

Example:

1. push 2.16.0 tag
2. CI auto-publishes and updates npm's `latest` tag to 2.16.0
3. push 2.15.3
4. CI auto-publishes and updates npm's `latest` tag to 2.15.3 
5. At this point the `latest` tag is invalid.  

Using `auto-dist-tag` will avoid this issue, by ensuring that the `latest` dist tag is only updated if the newer commit is `semver.gt` the old one.

I believe that all we need to do is update [this section](https://github.com/emberjs/ember.js/blob/de55b12a89ae497086b6a7aa02716ef2bc2faea1/bin/publish_npm_and_bower#L74-L78) of the publishing script to call `auto-dist-tag` binary first.

/cc @Turbo87

**Comment by Turbo87** [comment]
> I believe that all we need to do is update this section of the publishing script to call auto-dist-tag binary first.

`auto-dist-tag` has a `--write` option that writes the calculated dist tag to the `package.json`, but you can also use it without that option and in that case it will write the dist tag to stdout. tl;dr if you assign the stdout to `$CHANNEL` and use that unconditionally it should just work.

**Comment by Serabe** [comment]
Closed as fixed by https://github.com/emberjs/ember.js/pull/16122
