### ISSUE TITLE
Convert ember-glimmer package to typescript

### ISSUE THREAD

**Issue by krisselden** [emberjs/ember.js#15729]
Convert ember-glimmer to typescript.  Use d.ts files for imports from other packages for now.

**Comment by rwjblue** [comment]
There is some amount of work (on the build side) that is done for this. I’ll try to track down the branch names with the WIP.

**Comment by rwjblue** [comment]
The branch I was referring to was: https://github.com/emberjs/ember.js/compare/typed-ember-glimmer
