### ISSUE TITLE
Ember 2.16 router service unable to transition without all query parameters present

### ISSUE THREAD

**Issue by pgrippi** [emberjs/ember.js#15725]
I upgraded my app from 2.15 to 2.16 today and I think I've found a bug with the `transitionTo` method in the new routing service.

In 2.15 I was using the `ember-router-service-polyfill` addon that I have since removed. The following code was working fine but now appears to be broken:

```js
// controller
import Controller from '@ember/controller';

export default Controller.extend({
  queryParams: ['page', 'message'],
  page: 1,
  message: ''
});

// component
import Component from '@ember/component';
import { inject as service } from '@ember/service';

export default Component.extend({
  router: service(),

  actions: {
    jump() {
      let queryParams = { message: 'hello world!' };
      this.get('router').transitionTo('index', { queryParams });
    }
  }
});
```

The error I get in the `jump` action is: "You passed the `false` query parameter during a transition into index, please update to page", which I've narrowed down to be coming from [this line in router.js](https://github.com/emberjs/ember.js/blob/ed381d7003ce87dde032d6edae6c19bcf4d37c79/packages/ember-routing/lib/system/router.js#L968).

It does end up working if I include both `message` and `page` in the query params hash. In short:

```js
// broken
this.get('router').transitionTo('index', { queryParams: { message: '' } });
this.get('router').transitionTo('index', { queryParams: { page: 1 } });
this.get('router').transitionTo('index');

// works
this.get('router').transitionTo('index', { queryParams: { message: '', page: 1 } });
```

I have created this app that shows the broken behavior: https://github.com/pgrippi/ember-216-routing-service-bug

**Comment by hellobrett** [comment]
We are also being affected by this issue.  Any chance for a patch release?

**Comment by sly7-7** [comment]
@hellobrett seems like there will be soon one: https://github.com/emberjs/ember.js/pull/15613#issuecomment-335613077

@rwjblue maybe we can close this issue ?

**Comment by rwjblue** [comment]
Thanks @sly7-7!
