### ISSUE TITLE
Update documentation to link to new URL API docs structure

### ISSUE THREAD

**Issue by locks** [emberjs/ember.js#15723]
So for each package in ember source, we'd like to convert api doc links to our new  url structure (example: https://emberjs.com/api/ember/release/classes/Application)

Additionally we'd like to convert references to old Ember namespaced classes to their simplified post RFC 176 names.  
(example: documentation might refer to Ember.Object, while we'd want it to be EmberObject now)
See the readme for https://github.com/ember-cli/ember-rfc176-data for the mappings.

here's a list of all subdirectories in the `packages/` directory.  There may or may not be things to convert in some of these.  if you verify these are not in need of conversion we can check them too.

Indicate in comments when you want to work on a directory and its yours. We will add your name to the item.  Also when you submit a PR, mention this issue "#15723" so that the link shows up here.

Thanks and Happy coding!

- [x] container :lock: @Parrryy               
- [x] ember-glimmer :lock: @Parrryy           
- [x] ember-views :lock: @Parrryy 
- [x] ember  :lock: @MarcoUmpierrez     
- [x] ember-metal :lock: @karthiick        
- [x] external-helpers :lock: @Parrryy 
- [x] ember-application  🔒 @Parrryy 
- [x] ember-routing  🔒 @ynotdraw      
- [x]  internal-test-helpers 🔒 @ynotdraw  
- [x] ember-console 🔒 @ynotdraw            
- [x] ember-runtime 🔒 @ynotdraw            
- [x] loader 🔒 @ynotdraw 
- [x] ember-debug   🔒 @williamhaley           
- [x] ember-template-compiler 🔒 @ynotdraw 
- [x] node-module 🔒 @ynotdraw 
- [x] ember-environment 🔒 @ynotdraw 
- [x] ember-testing 🔒 @ynotdraw 
- [x] ember-extension-support 🔒 @ynotdraw 
- [x] ember-utils 🔒 @ynotdraw 
  
  
**Update:**  Be sure to prepend your commits to `[doc beta]`, so we can get these changes into 3.0!
See https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#documentation

**Comment by scissorsneedfoodtoo** [comment]
Hi there. I'd like to help out with this task, but I'm quite new to ember.js and contribution. Could you point me toward the documentation that needs to be updated and the new URL structure?

**Comment by juventinoromero** [comment]
Hi! Is this issue taken? I can help!

**Comment by toddjordan** [comment]
@scissorsneedfoodtoo @juventinoromero Thanks for your willingness to help!  What needs to happen is any link referring to a legacy API url, (such as `emberjs.com/api/ember/Ember.Application.html`) needs to be replaced with its new equivalent (`https://emberjs.com/api/ember/release/classes/Application`).  

Unfortunately, referring to links with `release` vs a specific version `2.17` has regressed, and we need to address this before proceeding with this fix. 

See: https://github.com/ember-learn/ember-api-docs/issues/407

Once fixed, we can split up the work by source folder.  Will create a quest-issue style checklist for this and you can grab sections of the source by folder.

**Comment by juventinoromero** [comment]
Ok. Thanks! I'll check that issue.

**Comment by scissorsneedfoodtoo** [comment]
@toddjordan, sorry for the late response.

@juventinoromero, why don't you go for it! I've gotten wrapped up in some other projects. Good luck with everything!

**Comment by juventinoromero** [comment]
@scissorsneedfoodtoo thanks! I'll be working on it once I get some time off another project. Feel free to work on it too :)

**Comment by CodingPower472** [comment]
@scissorsneedfoodtoo can I work on this?

**Comment by toddjordan** [comment]
@scissorsneedfoodtoo @juventinoromero @CodingPower472 The update to apidocs that supports the "release" url is just in and deployed today, so we can go ahead and convert links from the inline documentation. I'd suggest breaking up by directory so folks can work concurrently as they get band with.  I'll update the description to make it more "quest" style.  

But yes, feel free to start @CodingPower472

**Comment by CodingPower472** [comment]
@toddjordan Is this an issue with ember-learn/ember-api-docs or emberjs/ember.js?  (Sorry for the stupid question)

**Comment by Serabe** [comment]
Please, before starting with any part, ask here to lock it so we don't duplicate efforts.

Thank you!

**Comment by toddjordan** [comment]
@CodingPower472 its here in ember.js  because all the code changes need to be made in this repo, to the inline documentation.

**Comment by ynotdraw** [comment]
I can lend a hand.  I'll start with the bottom three:

- ember-testing
-  ember-extension-support
-  ember-utils

**Comment by scissorsneedfoodtoo** [comment]
@CodingPower472, @ynotdraw, go for it! I'm a bit wrapped up in another project now.

**Comment by juventinoromero** [comment]
@CodingPower472 @ynotdraw go ahead! I'm also busy with another project but a week or so. I'll catch up with you later. Thanks!

**Comment by williamhaley** [comment]
Can I take on `ember-debug`?

**Comment by toddjordan** [comment]
sure can @williamhaley let me know if you have questions!

**Comment by toddjordan** [comment]
check out @ynotdraw 's pr for an example of what needs to be done #16108

**Comment by jenweber** [comment]
Similar work being tracked in https://github.com/emberjs/guides/issues/2177 for the Guides

**Comment by ynotdraw** [comment]
I should have some bandwidth this week/weekend for another set.  Feel free to assign these to me:

-  ember-template-compiler
-  node-module
-  ember-environment
- loader

**Comment by ynotdraw** [comment]
Looks like the following **do not** require any RFC176 or url updates and can be marked off the list:

- ember-template-compiler
- node-module
- ember-environment
- loader

I'll move on to the next three that appear to need changes:

- ember-routing
- internal-test-helpers
- ember-console

**Comment by karthiick** [comment]
I will take `ember-metal` package.

**Comment by MarcoUmpierrez** [comment]
`ember` package looks like it doesn't require any change either. There's only one file in that package (index.js) and no links pointing to the API docs.

**Comment by Parrryy** [comment]
I can do the ember-application, it'll be my first one contribution. Seems like a good one to start.

**Comment by Parrryy** [comment]
I'll pick up `container`, `ember-views` and `external-helpers` today.

**Comment by toddjordan** [comment]
Thanks to everyone who's submitted prs/looked at packages :heart:  I'll be doing some reviews this evening.

**Comment by toddjordan** [comment]
Looks like we can close the book on this one.  Thanks so much @ynotdraw @Parrryy @karthiick @MarcoUmpierrez @williamhaley for making it happen.  It was cool to see it come together ❤️
