### ISSUE TITLE
computed.sort is not updated if the value of the itemsKey is null

### ISSUE THREAD

**Issue by pieter-v** [emberjs/ember.js#15732]
If the first time you 'get' the sorted property while the property itself is null, then the sorted property is never recalculated if the property receives a value afterwards (see attached file for a reproduction scenario).

works on 2.15.3, but fails on 2.16.0

The reason why this fails in our app, is that property is a sub-property of model (model.users and model.sortedUsers) and that rendering starts between the beforeModel and model hook. So, the value controller.model is still null.
[sorting.zip](https://github.com/emberjs/ember.js/files/1378708/sorting.zip)

**Comment by rwjblue** [comment]
I believe that this was fixed by https://github.com/emberjs/ember.js/pull/15733.

**Comment by pieter-v** [comment]
Thanks
