### ISSUE TITLE
All query parameters are required when using `transitionTo` in `RouterService`

### ISSUE THREAD

**Issue by brandynbennett** [emberjs/ember.js#15734]
You get the following error if you attempt to transition to a route with query params without providing a value for all of the query params:

`Assertion Failed: You passed the 'false' query parameter during a transition into 'myroute' please update to 'myQueryParam'`

The error is coming from https://github.com/emberjs/ember.js/blob/f4bbfe27d55caa5182fcd229f09a690fe11a9ca6/packages/ember-routing/lib/system/router.js

**Comment by pichfl** [comment]
I think this was adressed in #15726 (which replaced other tickets I followed closely as I encountered the same issue)

**Comment by brandynbennett** [comment]
@pichfl It doesn't look like that is part of a release yet. Do you know if the fix will be released soon?
