### ISSUE TITLE
Router Service transitionTo breaks with Query Params on Application Route

### ISSUE THREAD

**Issue by westlywright** [emberjs/ember.js#15735]
With query parameters on the application route/controller an assert is thrown when using the new router service's `transitionTo` method. The assert is throw in `_hydrateUnsuppliedQueryParams` because the query param does not exist in the query parameters argument passed down the treen during transitonTo. 

Specfically the assert was added at this [commit](https://github.com/emberjs/ember.js/commit/3b9489cf6acb61c5ee22f8016f7486ef1e7133d4#diff-985dc4a078da4636eff18be21aa7f9e6R968) 

Since Ember twiddle is not up to date with the latest release I've created a demo app that reproduces this scenario [here](https://github.com/westlywright/test-for-app-qp) that can be pulled. Star the app and follow the link tree down to sub route. You'll notice that the `Back  To Main Narp False` link-to works fine, but `Take Me Home Narp True` button causes the assertion. If you remove the query parameters from the application controller, everything works great!

**Comment by brandynbennett** [comment]
This commit might the issue, but it's not part of a release
https://github.com/emberjs/ember.js/commit/1c8c6ecad42228e94deffb7672fc6de905fca007

**Comment by brandynbennett** [comment]
You get the following error if you attempt to transition to a route with query params without providing a value for all of the query params:

Assertion Failed: You passed the 'false' query parameter during a transition into 'myroute' please update to 'myQueryParam'

The error is coming from https://github.com/emberjs/ember.js/blob/f4bbfe27d55caa5182fcd229f09a690fe11a9ca6/packages/ember-routing/lib/system/router.js

**Comment by brandynbennett** [comment]
@rwjblue is it possible to push a 2.16.1 with https://github.com/emberjs/ember.js/commit/1c8c6ecad42228e94deffb7672fc6de905fca007 in it

**Comment by brandynbennett** [comment]
Looks like #15726 includes the fix.

**Comment by brandynbennett** [comment]
more discussion here https://github.com/emberjs/ember.js/pull/15613

**Comment by westlywright** [comment]
@brandynbennett thanks for the follow up, seems the issue is already known so I'll close this one.
