### ISSUE TITLE
pluralize() and singularize() not available for '@ember/string'

### ISSUE THREAD

**Issue by izelnakri** [emberjs/ember.js#15731]
currently these methods are available under Ember.String, however they are not exposed/used under ```@ember/string```. I wanted to import these for my adapter and it currently breaks unless I use Ember.String.

**Comment by rwjblue** [comment]
These methods should not be on `Ember.String` at all (see https://github.com/emberjs/ember-inflector/pull/131), and are in fact from `ember-inflector`.

Look forward to an ember-inflector release deprecating these methods soon...

**Comment by Serabe** [comment]
Closing. Not an issue.

Thanks!
