### ISSUE TITLE
computed.sort broken in 2.16

### ISSUE THREAD

**Issue by mkamneng** [emberjs/ember.js#15745]
Hi Guys,

The sorting using Ember.computed.sort seems to be broken in 2.16. I had it working in 2.14 and since my upgrade, it's silently failing to sort.

There is already an issue on sort (https://github.com/emberjs/ember.js/issues/13037, computed.sort works incorrectly with empty sort properties array #13037), but it's not the same I'm experiencing.

I have created a demo for both scenarios:
Sorting with Ember.computed.sort working in 2.14.1: https://ember-twiddle.com/376dab39e1adfd11e93499049b035c41
Sorting with Ember.computed.sort broken in 2.16.0: https://ember-twiddle.com/f6ad4dfab81aa0989268596b0d88c38a

Thanks!

**Comment by Techn1x** [comment]
There is an issue on the 2.16 sort regression here;
https://github.com/emberjs/ember.js/issues/15732

And a merged PR here;
https://github.com/emberjs/ember.js/pull/15733

Just waiting on a hotfix release...

**Comment by mkamneng** [comment]
Ok, Thanks.

**Comment by locks** [comment]
Thanks for reporting, closing this one as it's a duplicate and the issue has been resolved.
