### ISSUE TITLE
Ember.A() docs is missing parameter description

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#15753]
It seems that `Ember.A()` accepts an optional parameter that is currently not documented.

**Comment by alexmiddeleer** [comment]
I would be happy to try to work on this.

**Comment by Serabe** [comment]
@alexmiddeleer it needs to be documented here https://github.com/emberjs/ember.js/blob/v2.16.0/packages/ember-runtime/lib/system/native_array.js#L109-L151

Ping me on Slack if you need help

**Comment by alexmiddeleer** [comment]
https://github.com/emberjs/ember.js/pull/15769 
I wasn't able to get yui server mode working (`ember serve --docs`), but `yarn docs` worked.
