### ISSUE TITLE
DOCS: Ember computed page is not loading

### ISSUE THREAD

**Issue by CESAR-Angular** [emberjs/ember.js#15750]
Hi,

Since 3 days ago, this page:

https://emberjs.com/api/classes/Ember.computed.html

... never loads.  Has this URL changed?

Thanks.

**Comment by bmac** [comment]
Hi @CESAR-Angular. It looks like the URL has changed. For the the new url is https://emberjs.com/api/ember/2.15/namespaces/Ember.computed/methods or https://emberjs.com/api/ember/2.16/classes/@ember%2Fobject/methods/computed?anchor=computed if you are looking for the new Ember 2.16 modules api for `Ember.computed`.

**Comment by pixelhandler** [comment]
@CESAR-Angular does the response from @bmac help? if so feel free to close out this issue.

**Comment by CESAR-Angular** [comment]
Yeap, it helps. Thanks @bmac. Closing it.

**Comment by BrettHoutz** [comment]
It looks like all the documentation for computed property macros (e.g. `Ember.computed.alias`) was removed for version 2.16+. The `computed` method documentation at https://emberjs.com/api/ember/2.16/classes/@ember%2Fobject/methods/computed?anchor=computed doesn't have any of that. Was it moved somewhere else?

**Comment by locks** [comment]
@BrettHoutz `computed` is no longer functioning as both a function and a namespace. You can find the entire list at https://emberjs.com/api/ember/2.16/modules/@ember%2Fobject.
