### ISSUE TITLE
Using actions on elements triggered by events piles up listeners

### ISSUE THREAD

**Issue by averydev** [emberjs/ember.js#15768]
Hi there, 

I've found that when elements are created and removed, for instance in an `{{if}}` statement, and include actions paired with native events, those events pile up (at least in chrome). 

If this is happening with a lot of elements at once, for instance showing a list of 200 items, each with 3 inputs and 2 buttons, this can happen quickly, and cause memory problems. 

You can also see the heap grow and never decrease on the example below of the "onClick" button. 

**Ember Twiddle**:
https://ember-twiddle.com/fb52fe588830908c7b12a0a396574434?fileTreeShown=false&numColumns=0

**Screencast**:
https://monosnap.com/file/iWoH8QfcMdDPJTPtpaAq3vmTrt5t5o

In particular the result observed in the performance > memory > listener panel of chrome is quite different between these two:
`<button onClick={{action "click"}}>Button With "onClick" Action</button>`
and
`<button {{action "click"}}>Button w/ simple action</button>`
@locks suggested I mention @stefanpenner and @krisselden 

Thanks!
![ember twiddle - listener test 2017-10-25 14-33-30](https://user-images.githubusercontent.com/477027/32024584-e890ca28-b991-11e7-89d7-f4b8d2e46c5e.png)
![image 2017-10-25 14-35-44](https://user-images.githubusercontent.com/477027/32024624-088d04c2-b992-11e7-9faa-be71b8bef92b.png)

**Comment by pixelhandler** [comment]
@averydev thanks for reporting the issue and providing a reproduction of the issue.

To summarize:

Conditional display of element with click handlers will result in the creating and destruction of elements with their associated handlers.

Though we can use `onClick` to attached an action handler to the DOM attribute of an element that event handler will not be torn down during the lifecycle of the element...

> `<button onClick={{action "click"}}>Button With "onClick" Action</button>`

However using an action not attached to a DOM attribute of an element will not create additional handlers each time the condition is met to render an element in the DOM...

> `<button {{action "click"}}>Button w/ simple action</button>`

The difference is that the latter does not attached the function to the DOM element's `onClick` attribute. 

It appears that there is no way to teardown the event handler attached to the attribute. In short we should prolly not use that style of attaching an event for items that will be destroyed and recreated, perhaps in a long list.

I think that the traditional use of the `action` (not attaching to `onClick` DOM attribute) only registers a callback for events that are listented to using event delegation. So yeah not adding extra event handlers :)

I'm not sure if there is a solution for this would need to lean on Core team.

There are other gotchas with using `onClick` as well. I think there is a clear work around, can avoid use of `onClick` for elements that need to be created and destroyed often.

The only benefit form using `onClick` is to recieve the `event` as an argument in the action handler. From the documentation:

> To utilize an event object as a function parameter:
> Define the event handler in the component (which is designed to receive the browser event object).
> Or, assign an action to an inline event handler in the template (which creates a closure action and does receive the event object as an argument).

See https://guides.emberjs.com/v2.16.0/components/handling-events/

**Comment by pixelhandler** [comment]
I'm inclined to think that this is not a bug. The frame work provides various ways to listen to events and they have their trade-offs. Using a component with an event handler will setup and teardown properly.

**Comment by pixelhandler** [comment]
Also mentioned is that `onClick` should be `onclick` I forked the twiddle example, https://ember-twiddle.com/d371f2880f4d3e5c5096821f72eaadd8?fileTreeShown=false&openFiles=controllers.application.js%2C

But the result is the same regarding adding handlers to the element's attribute.

**Comment by pixelhandler** [comment]
@averydev I updated the forked twiddle to show using a component's event handler, see https://ember-twiddle.com/d371f2880f4d3e5c5096821f72eaadd8?fileTreeShown=false&openFiles=templates.application.hbs%2Ctemplates.components.x-button.hbs

**Comment by averydev** [comment]
Hi there @pixelhandler thanks for looking into this!

The good thing here is that there are plenty of good alternatives to `<button onclick={{action 'doSomething'}}>` that are likely to be perfect alternatives without the listener downside. 

In particular, while re-reading the docs on `{{action}}` i noticed the following option for the first time:  `<button {{action "doSomething" on="onclick"}}>`

I forked the twiddle again here: https://ember-twiddle.com/00c059ecd222d5312fcb3188a06e71bd?openFiles=templates.application.hbs%2C
and the result of a quick test is that it cleans up after itself nicely. Great!

After thinking about it a bit, i'm not surprised that the `onclick={{action}}` option doesn't clean up after itself given the output html:
![ember twiddle - listener test 2017-11-03 09-17-47](https://user-images.githubusercontent.com/477027/32384372-f0218510-c077-11e7-8792-dc2f739c963d.png)

The reason that i would characterize this as a bug is for the following reasons: 

This falls into a "Use the framework" type of feature, and it is prevalent throughout the docs. As such, I personally expected it to not leak listeners or memory without additional effort, when in fact it does so. 

This formulation is found in docs throughout Ember... In fact the first two examples in the docs for the Action Helper show it in the form `onclick={{action ...}}`

![ember templates helpers - 2 16 - ember api documentation 2017-11-03 09-26-16](https://user-images.githubusercontent.com/477027/32384743-1a74ecd4-c079-11e7-81d7-c44178211343.png)

It is also widely found in addon docs, for instance here's ember-concurrency:
![ember-concurrency 2017-11-03 09-31-12](https://user-images.githubusercontent.com/477027/32384974-d86db96e-c079-11e7-9501-d847dbc16c5c.png)

Given the above, I doubt that 1 in 100 Ember developers think that the `onclick={{action}}` has a downside.

It is a particularly common formulation because it is more explicit than `button {{action 'doSomething'}}` and seems less magical, which is not a bad thing on its own.

Also, the same listener issue occurs regardless of if you're using a <button> <li> etc. Particularly if you need something like `mouseenter={{action "doSomething}} mouseleave={{action "somethingElse"` or `<input onchange={{action "doSomething"}}>`

Also, you don't need to be creating and destroying thousands of items for this to be an issue. The reason that I stumbled on this issue was that prolonged use of the app i'm working on currently was gobbling up tremendous amounts of memory to the point that prolonged usage would grind the app to a halt. The reason for this *I think* is that even a single listener that hasn't been cleaned up will be a reference to the parent leading to detached DOM trees that can't be garbage collected. 

I could be wrong, but I'm pretty sure that's what's going on here.

**Comment by averydev** [comment]
Also, there isn't anything specific about `{{#if}}` that causes this issue, it would be the same if for any reason an element was removed from the template that had had an `onclick={{action...}}` for instance:

```
//.js
results: computed('query', function (){
      const query = this.get('query');
      return this.get('items').filter( d => d.get('field').indexOf(query) !== -1);
}
//.hbs
{{#each results as |result|}}
       <div mousenter={{action 'resultHovered' result}};> {{result.title}}</div>
{{/each}}
```

**Comment by rtablada** [comment]
@averydev the `if` statement just makes it easier to add and remove elements.

**Comment by averydev** [comment]
@rtablada yep! Just confirming and isolating that the bug exists regardless of the element being removed from the DOM as the result of a change to the evaluation of a conditional in the template.

**Comment by stefanpenner** [comment]
> It appears that there is no way to teardown the event handler attached to the onclick attribute. In short, we should not use that style of attaching an event for items that will be destroyed and recreated (e.g. in a long list).

The browser cleans these up for us. Once an element who had an handler attached, is both:

* detached from the DOM
* unreachable from JavaScript

That elements DOM object and JS Wrapper is collected, at that point the browser can (and at some point will) collect the attached handler

**Comment by averydev** [comment]
I just ran through the examples again, and Chrome seems to have improved GC of these abandoned listeners since this bug was reported! Whew! Previously I've seen abandoned listeners last seemingly forever, but leaving it alone for ~10s was enough to have them GC'd.

I've been using the syntax of `<button {{action "doSomething" on="onclick"}}>` when lots of listeners are likely to be added/removed, but that is more of a blog post than a bug...

At this point I'd recommend closing this.

**Comment by krisselden** [comment]
@averydev the memory growth chart can climb simply because there is no GC pressure that does not mean there is a leak.  I just did a comparison heap snapshot between a snapshot after toggling on/off 4 times and toggling on/off 100 times, there is no leak of the closure action or dom that was removed.

![heapsnapshotcompare](https://user-images.githubusercontent.com/61024/34786405-f2e11198-f5e8-11e7-96df-d4ad2167938e.jpg)

**Comment by stefanpenner** [comment]
@krisselden thanks for confirming, i got distracted bugging our v8 friends re: existing open memory issues and forgot about this issue during those 5 minutes....

> I've been using the syntax of <button {{action "doSomething" on="onclick"}}> when lots of listeners are likely to be added/removed, but that is more of a blog post than a bug...

I would strongly recommend `<button onclick={{action "doSomething"}}>`

**Comment by averydev** [comment]
Oh!  @stefanpenner is there a downside i'm not aware of?

**Comment by stefanpenner** [comment]
`<button onclick={{action "doSomething"}}>` is just the simplest, and will work with any DOM specified API. It is also takes the form as any other data binding.

```
<button anyProperty={{anyValue}}>
```

And under the hood it just does:

```
button.onclick = callback // no magic, just sets a property the same as a developer would.
```

---

`<button {{action "doSomething" on="click"}}>`  is IMHO legacy, as it originates from before templates were aware of HTML syntax, and could do the above.

**Comment by averydev** [comment]
Ok good to know! Thanks!
