### ISSUE TITLE
Inconsistent Capitization with currentURL / rootURL vs urlFor in Router Service

### ISSUE THREAD

**Issue by malatin3** [emberjs/ember.js#15774]
I know it's a bit pedantic but if you're treating url as a whole word like it seems you are in urlFor the capitalization of currentURL and rootURL would be currentUrl and rootUrl respectively.

**Comment by Serabe** [comment]
They are consistent. Is a lower camel case and acronyms conserve the case of the first letter.

For further discussion, given this imply a change in the API, please, open an RFC.

Thank you!
