### ISSUE TITLE
I’m your secret admirer

### ISSUE THREAD

**Issue by zacksiri** [emberjs/ember.js#15804]
Hey Ember Community

Over the past 2 years I’ve been working with React applications. I followed the hype and I build with React, yes react itself is great but everything else around it is complicated, fragmented, and inconsistent. Needless to say looking back, I have to say I wish that I had started here at ember. The amount of hours I’ve wasted setting up React, Webpack, React Router (this is most infuriating because by the time I understood the router they released a new version which was totally different and IMO didn’t make things better) 

I’m just here to let you guys know if I start a new project today it would be in Ember. Keep doing what you guys are doing, you guys are on the right path. You provide a cohesive experience for building ambitious front end application just as advertised. Ember is by far the right choice, coming from a guy who now has to maintain a few React apps.

**Comment by Serabe** [comment]
Thank you so much for your kind words!

Please, join us in the Ember Community Slack, you can request an invite [in this Slackin](https://ember-community-slackin.herokuapp.com/).

Hope to see you soon in slack!

Thanks again!
