### ISSUE TITLE
#each index not available in partial after upgrade to 2.16.2

### ISSUE THREAD

**Issue by atomkirk** [emberjs/ember.js#15807]
```
{{#each model.items as |item idx|}}
  {{partial 'partials/bill-item'}}
{{/each}}
```
This is NOT double nested but idx is not making it into the partial. It was working in 2.14.2 but after simply upgrading to 2.16.2 (no other changes), it no longer works.

I'm still experiencing https://github.com/emberjs/ember.js/issues/15791 on 2.16.2, even though there are claims it is fixed in 2.16.2. I'm not sure if this is a manifestation of that same bug.

**Comment by rwjblue** [comment]
@atomkirk - Would you mind submitting a failing test PR like the few linked in #15791?

**Comment by rwjblue** [comment]
There are many different scenarios at play, and we _definitely_ have been fixing the ones reported (and confirmed by passing the previously failing test cases) as we do these patch releases.  I'm sorry that it is frustrating. 😞

**Comment by atomkirk** [comment]
Well, I can't reproduce it in a twiddle so maybe its just my installation somehow. Which might be related to my other errors

https://ember-twiddle.com/dc578e341683f6c2034d12086f675283?openFiles=templates.application.hbs%2C

**Comment by rwjblue** [comment]
@atomkirk - Please continue to try to isolate the issue, we are eager to help once we can reproduce. Also, feel free to make a full repo that we can clone if you suspect the issue to be twiddle itself...

**Comment by atomkirk** [comment]
I think its probably related to my version mitchmatch that you pointed out. Im still trying to verify that was the problem. Lets close for now. Many thanks for taking the time.

**Comment by rwjblue** [comment]
No problem. Let us know if it’s still an issue and we will try to keep digging with you...
