### ISSUE TITLE
Ember.Array and replace()

### ISSUE THREAD

**Issue by marxsk** [emberjs/ember.js#15812]
In the documentation, strings are used in Enumerables together with pushObject() [e.g. in https://guides.emberjs.com/v2.16.0/object-model/enumerables/]

`let arr = Ember.A(['first', 'second', 'third']);`
`arr.replace(0, 1, 'new-first');`
`arr.replace(1, 1, '');`
`arr.pushObject('')'`

The arr contains `['new-first', 'third', '']`. According to documentation (usage with objects) I would expect that it should just replace 'second' with an empty string. Am I right?

**Comment by Serabe** [comment]
The third argument for replace needs to be a collection.
