### ISSUE TITLE
Make canInvoke public

### ISSUE THREAD

**Issue by thec0keman** [emberjs/ember.js#15813]
This is kind of a minor request, but could `Ember.canInvoke` be made public and added to the `@ember/utils` module exports?

`tryInvoke` is already public, but we've found `canInvoke` to also be valuable, and it would be nice if it was publicly available.

**Comment by Serabe** [comment]
Feature [requires to follow the RFC process described in CONTRIBUTING](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature).

Thanks!
