### ISSUE TITLE
[2.16.0] Missing properties and methods in Ember.CoreView documentation and in descendant classes

### ISSUE THREAD

**Issue by juhyxx** [emberjs/ember.js#15839]
Compare:
https://emberjs.com/api/ember/2.15/classes/Ember.CoreView
https://emberjs.com/api/ember/2.16/classes/Ember.CoreView

Where did they go?

**Comment by MelSumner** [comment]
@toddjordan do we know what happened?

**Comment by locks** [comment]
This seems fixed in 2.18 which was the last release of the 2.x branch. Thanks for bringing it up!
