### ISSUE TITLE
Getting isDestroyed return "undefined" for nested keyPath

### ISSUE THREAD

**Issue by minhnq013** [emberjs/ember.js#15837]
If I attempt to get the "isDestroyed" attribute of a destroyed nested object using the getter, it will return "undefined" instead of "true" due to the loop in "_getPath" in property_get.js

```
var classX = Ember.Object.extend({
    child: Ember.computed(function() { 
        return Ember.Object.extend({
    })
});

var x = classX.create();
x.get('child').isDestroyed = true;

console.log(x.get('child.isDestroyed'); // Return undefined
```
This can cause some issue as the value is the opposite of what we expect and the code still treat the object as not destroyed.

Though, I understand the reason for why the getter would return undefined on destroyed object, maybe we can make an exception for "isDestroyed"?

**Comment by Serabe** [comment]
Did it ever work as your desired behaviour? If so, we could argue it is a regression but otherwise it would require an RFC.

**Comment by Serabe** [comment]
@minhnq013 ping.

**Comment by Serabe** [comment]
Closing this according to [our triage policy](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy). Please, answer previous comments to reopen it.

Thank you!

**Comment by edslocombe** [comment]
I would argue it doesn't matter what it used to do. It's misleading and not exactly intuitive.
