### ISSUE TITLE
link-to in integration tests throw: Cannot read property 'applyIntent' of undefined

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#15831]
The following error occurs on canary (but works properly on prior releases) for [this test](https://github.com/rwjblue/___demo-integration-test-with-link-to-bug/blob/master/tests/integration/components/can-render-link-to-test.js):

```
not ok 47 Chrome 62.0 - component:o it can render a link-to
    ---
        actual: >
            false
        expected: >
            true
        stack: >
            Error: Assertion Failed: You attempted to define a `{{link-to "index"}}` but did not pass the parameters required for generating its dynamic segments. Cannot read property 'applyIntent' of undefined
                at new EmberError (http://localhost:7357/assets/vendor.js:13925:25)
                at assert (http://localhost:7357/assets/vendor.js:14168:15)
                at Class.computeLinkToComponentHref (http://localhost:7357/assets/vendor.js:17044:65)
                at ComputedPropertyPrototype.get (http://localhost:7357/assets/vendor.js:25789:28)
                at get (http://localhost:7357/assets/vendor.js:25131:20)
                at RootPropertyReference.compute (http://localhost:7357/assets/vendor.js:21709:40)
                at RootPropertyReference.value (http://localhost:7357/assets/vendor.js:21590:53)
                at ReferenceCache.initialize (http://localhost:7357/assets/vendor.js:924:52)
                at ReferenceCache.peek (http://localhost:7357/assets/vendor.js:898:29)
                at DynamicAttribute.flush (http://localhost:7357/assets/vendor.js:2776:37)
        message: >
            Assertion Failed: You attempted to define a `{{link-to "index"}}` but did not pass the parameters required for generating its dynamic segments. Cannot read property 'applyIntent' of undefined
```

The test is attempting to ensure that a component integration test is capable of rendering a `{{link-to}}` even when the router is not booted/available.

[Demo repo here](https://github.com/rwjblue/___demo-integration-test-with-link-to-bug/blob/master/tests/integration/components/can-render-link-to-test.js)

---

I suspect it was caused by one of the following PR's which have changed things in the routing and/or link-to area:

* https://github.com/emberjs/ember.js/pull/15788
* https://github.com/emberjs/ember.js/pull/15779
* https://github.com/emberjs/ember.js/pull/15762
* https://github.com/emberjs/ember.js/pull/15811

**Comment by rwjblue** [comment]
@bekzod - Would you mind taking a look at these? This is exactly the scenario (e.g. `{{link-to` without routing) that I was referring to in  https://github.com/emberjs/ember.js/pull/15779/files#r148964352...

**Comment by bekzod** [comment]
@rwjblue sure I am looking

**Comment by bekzod** [comment]
@rwjblue sorry couldn't resolve this, dug a bit found `inline link-to` is ignoring first positional param 
when `didReceiveAttrs`  `params` has `index` only when `Hi` `index` passed https://github.com/emberjs/ember.js/find/master#L815 ,
I suspect it something to do with `transform-inline-link` `https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/transform-inline-link-to.js` which is unfamiliar zone for me :)

**Comment by rwjblue** [comment]
Hmm. I didn’t think the issue was only for inline link-to. I’ll test though.

**Comment by simonihmig** [comment]
Can confirm this.

> I didn’t think the issue was only for inline link-to. I’ll test though.

This as well: happens for inline as well as block form of `link-to`!
