### ISSUE TITLE
Blank page when combining templateName and renderTemplate in a route with subroutes

### ISSUE THREAD

**Issue by rmachielse** [emberjs/ember.js#15841]
We are having an application with multiple named outlets in `application.hbs`. For displaying reasons, we render a nested route next to their parent route instead of nested into it, by overriding the outlet in `renderTemplate`. Also, we override the `templateName` in the route. The route also has subroutes. Unfortunately this causes a blank screen with no errors in the console. See this ember-twiddle for a reproduction: https://ember-twiddle.com/95a7519dbf0db38f0d9416d1c62bfe32

The issue can be circumvented in three ways:
- Removing `templateName` and making sure the template with the right name exists
- Not overriding `renderTemplate` and fixing the display with css instead
- Removing any subroutes from the relevant route in the router

I would expect the combination of all three to work though, or at least to give an error message. Am I overlooking something? This is at least the case in ember 2.12, 2.14 and 2.16.

**Comment by Serabe** [comment]
Thank you!

**Comment by Boudewijn26** [comment]
Note you can workaround this issue by adding `this.render();` to the `renderTemplate`. It seems the passing of the state in the `[Router#_setOutlets](https://github.com/emberjs/ember.js/blob/92f664b98e8e03b51792ea0b708af212dc0188a3/packages/ember-routing/lib/system/router.js#L290)` checks for the main outlet and only then passes the state. only rendering in another outlet means the state given to the next routes is incorrect.

**Comment by pixelhandler** [comment]
@Boudewijn26 @rmachielse is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?
