### ISSUE TITLE
setUnknownProperty is not used as documented when return value is undefined

### ISSUE THREAD

**Issue by mikeu** [emberjs/ember.js#15856]
The "Unknown Properties" section of the [`set` documentation](https://emberjs.com/api/ember/2.15/classes/Ember.Object/methods?anchor=set) for 2.15 and at least a few earlier versions says:
> If `setUnknownProperty()` returns undefined, then `set()` will simply set the value on the object.

A [similar section for 2.16](https://emberjs.com/api/ember/2.16/classes/@ember%2Fobject/methods/set?anchor=set) says of `set`:
> Sets the value of a property on an object ... If the property is not defined but the object implements the setUnknownProperty method then that will be invoked as well.

However, when `set` invokes an object's `setUnknownProperty` method, nothing is done with the return value. In particular the property is not set on the object when the function returns undefined. This can be easily seen in [`property_set.js`](https://github.com/emberjs/ember.js/blob/v2.16.1/packages/ember-metal/lib/property_set.js#L59), where `setUnknownProperty` is called without assigning its return value to anything, and nothing else happens after the function call except returning from `set`. So rather than being invoked *as well*, `setUnknownProperty` is invoked *instead* of setting the property value on the object.

Is this an error in the docs or in my understanding of them, or is it a bug in the intended operation of the code? I'm happy to take a stab at a PR if it's the latter and there's interest.

**Comment by rwjblue** [comment]
I believe that the docs are wrong, would love a PR fixing...

**Comment by rwjblue** [comment]
@mikeu - Have any time to send a documentation PR fixing this up?

**Comment by mikeu** [comment]
@rwjblue Sorry, don't know why I didn't get notified of your comment in February... But better late than never I guess, so thanks for the ping.

Sure, I should be able to put something together some time in the next week or so. I'm assuming it's not urgent given how long this has been open, but if there's a reason such as an upcoming release that makes a certain deadline appealing, please let me know and I'll see what I can do.

Would you expect/hope for a PR such as this to update the docs for older versions, or just the most recent release?

**Comment by rwjblue** [comment]
Nope, no rush, just trying to not lose track...

> Would you expect/hope for a PR such as this to update the docs for older versions, or just the most recent release?

Most likely we would pull the docs changes down into the current release (3.1)...
