### ISSUE TITLE
Dynamic segment on application route

### ISSUE THREAD

**Issue by sankar-ganesh** [emberjs/ember.js#15852]
Need help on adding a dynamic segment at the application level. To make it backward compatible this require to be an optional dynamic segment or all existing URLs must be replaced with the dynamic segment which is available before it hits the router class. Appreciate help on this!!!

**Comment by locks** [comment]
Thank you for reaching out @sankar-ganesh, however we reserve the issue tracker for bugs in Ember. Check our [community page](https://emberjs.com/community/) for StackOverflow, Discuss, and Slack links where you can ask your question.
Good luck!
