### ISSUE TITLE
Adding custom css classes to #link-to component when it is not active

### ISSUE THREAD

**Issue by AbdullahDahmash** [emberjs/ember.js#15860]
Hi ember developers!

I would like to suggest a small improvement for `{{#link-to}}` component.

I think adding new attribute `nonActiveClass` will help ember developer to bind classes when `{{#link-to}}` is not active. It simple terms, it is the reverse of `activeClass`.

This will help developer writing custom css classes for nonActive `{{#link-to}}` and help avoiding writing `!important` and custom unnecessary jquery code.

Thank you

**Comment by Serabe** [comment]
Hello, @AbdullahDahmash:

Feature requests need to go through the RFC process, as explained in our [CONTRIBUTING guide](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature).

Thank you!
