### ISSUE TITLE
Computed Property not being correctly invalidated during tests.

### ISSUE THREAD

**Issue by cah-briangantzler** [emberjs/ember.js#15861]
I have a test for a computed property on a mixin. In the test we are setting a field value with obj.set that the computed property is based on and then testing that the computed property contains the correct value and then doing an assert on the computed property. We are doing a set, then assert, set then assert etc in the same test... This should work, the set should invalidate the computed property and the get in the assert invoke the computed property.

When ALL tests in the application are run, the computed property is not being invalidated, and thus the tests are failing because the cached value is incorrect. HOWEVER, when we filter and run JUST the tests in the MIXIN, they all pass. The computed property is invalidated correctly every time. (verified by putting a console log in the computed property. All tests log one time, filtered tests log the correct 5 times due to the 5 sets)

We stepped through code, when all tests are running, and we are setting the property that the computed is based on, the code to invalidate the cache is being skipped. Cant quite understand the code to determine whats different internally between running all tests and just the tests in the mixin.

The code starts here https://github.com/emberjs/ember.js/blob/5f4ac602813d8fbd78f26fc955acf693e0b3d62a/packages/ember-metal/lib/property_events.js#L119

On line 140 seen is set to DID_SEEN, on line 143, if top ( !seen or DID_SEEN null), seen AND DID_SEEN are set to {}  The cache is cleared in iterDeps line 147 where seen is passed in. DID_SEEN is nulled line 150, but only if it was null to begin with (top = true). What is this code actually doing? Where is DID_SEEN ever set to anything other than null?

When all tests run, DID_SEEN is NOT null, it is a large hash of objects and line 157 finds a value and line 167 early exits NEVER invalidating the cache. When the tests run filtered to the mixin, DID_SEEN is null, no value found, no early exit, cache gets invalidated.

What is the purpose of DID_SEEN and top, what are they trying to accomplish. Where is DID_SEEN ever set. Should it be a file level variable and not an instance level somewhere?

To get the tests to work we basically put ever set expect in its own test and it seems to work. Why, when multiple sets followed by gets in the same test is the computed property NOT being invalidated? This should work shouldn't it?

I should note that we are on Ember 2.4 but the code in master seems to look like the same code in 2.4 that we have stepped through.

**Comment by Serabe** [comment]
Can you provide a reproduction, please?

**Comment by Serabe** [comment]
@cah-briangantzler ping

**Comment by cah-briangantzler** [comment]
Sorry, must have missed the first one. Ill see if I can reproduce it in a small application

**Comment by cah-briangantzler** [comment]
I am sorry. I have search all my code (a lot of repos and commits) and I can not find where this was happening. I should have included some info in the request that would have reminded me where in my code this was happening. Guess I figured I would remember, but too much time has passed.

You might have to close this as I can not at this time give you an example.

Even without an example though, is someone able to explain the code as far as the use of DID_SEEN and how it was being set? Was just curious.

Thanks

**Comment by Serabe** [comment]
In my experience, when tests run in isolation but not when the whole suite is run, it means that your tests (quite likely, not the ones failing) are not side-effect free. There are many possible reasons, but on sneaky one is not using `RSVP` promises. Tests automatically wait for all `RSVP.Promise` to resolve but not plain `Promise`s. The `Promise` starts in one tests and settleds in another, causing the latter to fail.

Thank you!
