### ISSUE TITLE
Ember.Logger missing from API Docs

### ISSUE THREAD

**Issue by pixelhandler** [emberjs/ember.js#15866]
`Ember.Logger` is listed in the 2.0 API docs

* https://emberjs.com/api/ember/2.0/classes/Ember.Logger

However on 2.16 version of docs there is no Ember.Logger

* https://emberjs.com/api/ember/2.16/modules/@ember%2Fapplication

Also, seems to be missing from the RFC 276 list of new modules to globals reference 

* https://github.com/ember-cli/ember-rfc176-data

**Comment by hinti** [comment]
Related: https://discuss.emberjs.com/t/ember-2-16-modules-api-how-to-import-ember-onerror/13717

**Comment by toddjordan** [comment]
Looks like Ember.Logger is something that went away between version 2.6 and version 2.7.  Researching to figure out what happened there.

**Comment by toddjordan** [comment]
Ok, in April 2016 Logger was refactored into the ember-console directory, which doesn't have an `@module` specified, and therefore did not get picked up by the documentation build process in 2.7 forward...  Working on a fix to reintroduce.

Going to work a fix that addis it back.

**Comment by toddjordan** [comment]
Ha.  nevermind.  Its not because it doesn't have `@module`, its because the `ember-console` path is not included in the config in `yuidoc.json`.
