### ISSUE TITLE
Regression from 2.14.1 to 2.15.0 only on a certain browser

### ISSUE THREAD

**Issue by samcic** [emberjs/ember.js#15867]
I'd like to hesitantly report what could be understood as a regression from 2.14.1 to 2.15.0.

On the built-in browser of a Samsung TV (in our case, model UN32J4300AFXZX), basic handlebars rendering of a computed property was working correctly up to 2.14.1.

After upgrading to version 2.15.0, this rendering is failing. See the two screenshots below. Both pages are a bare-bones Ember app created from Ember CLI using "ember new". The only difference is the version of "ember-source" used. The test is just done in the application.hbs template. There's a computed property in the application.js controller, which just returns "render successful". The application.hbs template simply renders this property with `{{myProperty}}`.

![17](https://user-images.githubusercontent.com/9308871/33144837-ad435556-cfbe-11e7-9e65-b628241643ef.jpeg)

![18](https://user-images.githubusercontent.com/9308871/33144845-b58a4da0-cfbe-11e7-98af-0b3e2dc81b8d.jpeg)

Some further notes:

* No script errors seem to be occur (the test was listening to window.onerror and would have logged the result to a div).
* Interestingly, if the *debug* build is used rather than the *production* build, then the rendering works correctly.
* Motivation: one of our customers uses four of these TVs to display one of our product pages in a "kiosk-style" mode, and it is very important to them.

I know these aren't great reproduction steps, but I'm assuming that few people here have access to such a browser anyway.

I'm wondering if there's any chance that someone here knows...
1. which change in 2.15.0 might be responsible for this issue? I'm guessing that it has something to do with the update to Glimmer that was mentioned in the relevant [blog post](https://emberjs.com/blog/2017/09/01/ember-2-15-released.html).
2. why the issue might be happening on production but not on debug builds?
3. if there's some change I can make to the ember.js code (2.15.0) to further narrow down the issue? Here I'd have to say that it's extremely time-consuming to debug on such a browser (it belongs to a customer and we can only request that they take screenshots for us!)
4. if this is technically a regression at all? Presumably this kind of TV browser isn't officially supported? Were we just "lucky" that it worked on this TV at all up until now?

Any insight on this would be greatly appreciated!

**Comment by Serabe** [comment]
Which browser is being run? Version? Can you reproduce it in 2.16 or 2.17?

Not sure how to proceed in this case, given it will be hard to find the root cause

**Comment by samcic** [comment]
Thanks for the response Serabe. To answer your questions:

* Yes, the issue exists in 2.16 and also 2.17 (i.e. exists since 2.15).

* The browser is the proprietary "inbuilt" browser of that Samsung model. Version number unknown (there's no such information in the "help" or "about" menus). The browser is described to some extent in the [user manual](http://support-us.samsung.com/nas/storage/201306131733051%5Estorage_attachment%5EF6300_-_6350_e-Manual.pdf). This of course makes it difficult to debug.

I'm not really sure what I'd expect the team to do about this. I guess I thought I'd report it anyway, "just in case" something else related comes up or somebody knows how this might be best debugged (or someone who owns such a TV can repro!).

**Comment by pixelhandler** [comment]
@samcic is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by samcic** [comment]
@pixelhandler The affected user ended up purchasing a Chromecast to resolve this. I don't think we can expect Ember (or any other framework for that matter) to try to support such inbuilt TV browsers, so from my side this is fine to close.
