### ISSUE TITLE
Giving an object as param for `link-to` helper doesn't work as expected

### ISSUE THREAD

**Issue by svenpl** [emberjs/ember.js#15870]
Route params given via an object to the `link-to` helper won't appear in the `paramsFor(routeName)` of the route. This is also the case when calling `transitionTo` instead.

Example:
```javascript
// Route decleration
// this.route('my-route', { path: '/:foo/:bar/:baz' });

this.transitionTo('my-route', '1', '2', '3');
this.paramsFor('my-route');
// -> { foo: '1', bar: '2', baz: '3' };

this.transitionTo('my-route', { foo: '1', bar: '2', baz: '3' });
this.paramsFor('my-route');
// -> {}
```

The transition in both cases works fine and the url is build from the params as expected but the `paramsFor` method works differently.

Here is also a [Twiddle](https://ember-twiddle.com/7e1a7f78c3b3a5158c12d798c4112191?openFiles=templates.application.hbs%2C&route=%2F1%2F2%2F3) which reproduces this.

**Comment by Serabe** [comment]
@svenpl is that behaviour documented somewhere? I cannot find it.

Thank you!

**Comment by svenpl** [comment]
I cannot find it either. Maybe that this is even working with a plain object is already unwanted behaviour.

**Comment by Serabe** [comment]
Quite likely. Closing this then.

Please, change your code to the supported  method signature.

Thank you!
