### ISSUE TITLE
Document queryParamsDidChange (Regression Ember 2.15)

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/ember.js#15921]
This is a regression of https://github.com/emberjs/ember.js/issues/10877 which was fixed by https://github.com/emberjs/ember.js/pull/13398 but has reappeared since Ember 2.15

It looks like `queryParamsDidChange` no longer appears in the api site due the docs being moved in the source.

**Comment by shanebruggeman** [comment]
Wanted to mention that the fix you reference no longer seems to exist :(

**Comment by Gaurav0** [comment]
edited

**Comment by rwjblue** [comment]
Sorry for letting this linger, the documentation is available now:

https://api.emberjs.com/ember/3.10/classes/Route/methods/queryParamsDidChange?anchor=queryParamsDidChange&show=inherited%2Cprivate
