### ISSUE TITLE
Computed filter not recomputing

### ISSUE THREAD

**Issue by evoactivity** [emberjs/ember.js#15920]
Upgraded my app to 2.16.2 and noticed some of my filtered arrays were no longer filtering when I changed properties of the items in the array.

I have these setup and the computed reruns when I change prop1, but the filter only runs on render.

```
test: computed('model.@each.{prop1,prop2}', function(){
  console.log('running computed');
  return '';
}),

filterTest: filter('model.@each.{prop1,prop2}', function(item){
  console.log('filtering');

  if (item.get('prop1')) {
    return item;
  }
})
```

I've created a repository that shows the bug in action https://github.com/evoactivity/ember-broken-filters, here is a twiddle showing the same setup working as expected in 2.12 https://ember-twiddle.com/57d664edc79ac56b3011f2dd2763903b?openFiles=controllers.application.js%2Ctemplates.components.list-item.hbs

**Comment by karthiick** [comment]
@evoactivity I think, this regression is fixed in https://github.com/emberjs/ember.js/pull/15855

Changes are available in the latest release [v2.17.0](https://github.com/emberjs/ember.js/releases/tag/v2.17.0)

**Comment by Serabe** [comment]
@evoactivity can you please check that it is fixed in 2.17? If so, we can try to backport it to 2.16.

**Comment by evoactivity** [comment]
@Serabe I'll update my test app tomorrow to have a look

**Comment by evoactivity** [comment]
@Serabe sorry, I totally forgot to do this. I should have a bit of time this week to check it out.

**Comment by Serabe** [comment]
@evoactivity ping!

**Comment by evoactivity** [comment]
@Serabe I'm terrible aren't I! I actually had a few minutes just now so you're ping was timed well.

I can confirm updating to 2.17 did resolve the issue.

**Comment by Serabe** [comment]
Thank you!
