### ISSUE TITLE
Set-Only Computed property - behaviour mismatch

### ISSUE THREAD

**Issue by Exelord** [emberjs/ember.js#15939]
# Description
Hey, I noticed that in the case when we are creating `set-only` property and we want to access unexistent `get` we are getting an error `Cannot read property 'call' of undefined`. This is reasonable but how the user can know that is a set-only property instead of just assume that there is a bug. In case of `readOnly` we are notifying the user when he tries to access a setter that this property is read-only.

# Real use-case - problem
We want to override `set` function on our property. We are not forced to define a `get` (we don't know that this is required- not mentioned anywhere):
```js
sword: Ember.computed({
    set(key, value) {
      // some overrides here
      return value;
    },
})
```
and then we are just getting into the problem eg. during inspecting an object in ember-inspector or calling a `get` on it. 

We are just getting the error: `Cannot read property 'call' of undefined`

# Solution
Shouldn't we have sth similar to `readOnly` and inform the user that this property doesn't have a defined `getter` or it is a `writeOnly`?

In my opinion, in case of custom set-only properties, we should just return an `undefined` during the `getter` call and create analogically to `readOnly` the `writeOnly` which will rise an error in case of trying to get the `getter`.

What do think guys?

# Full Issue example
```js
let Lord = Ember.Object.extend({
  sword: Ember.computed({
    set(key, value) {
      return value;
    },
  })
});

let exe = Lord.create();

exe.get('sword'); // returns error ' Cannot read property 'call' of undefined'
```

**Comment by Serabe** [comment]
Thank you!

**Comment by bekzod** [comment]
@Serabe I think this https://github.com/emberjs/ember.js/pull/15962 was first :)

**Comment by rwjblue** [comment]
Closed by https://github.com/emberjs/ember.js/pull/15962
