### ISSUE TITLE
send('error') from controller blows up on route handler

### ISSUE THREAD

**Issue by yakmada** [emberjs/ember.js#15960]
hi,

i'm having an issue sending an error from my controller.

there is a twiddle here:
https://ember-twiddle.com/2fa6ab16ff1697ed652939df7261e347?openFiles=controllers.bar.baz.js%2C

application route calls `transitionTo('bar.baz')`
baz controller calls `this.send('error', new Error('controller error'));`
baz route action error handler blows up with `TypeError: Cannot read property 'state' of undefined`

baz route `error(error, transition, originRoute)` has no transition or originRoute when bubbled up from the controller.  

it seems to me like the controller should be able to send an error without providing these arguments.
perhaps the error action handler is not intended to handle errors from controllers.

let me know if you think this is an issue which should be resolved.  i'm happy to provide more context if needed.

thanks!

**Comment by Serabe** [comment]
The error substate and actions are reserved for error during the transition, so I would not considered this a bug.

You can create your own route where the user can be redirected if there is a problem.

Thank you!
