### ISSUE TITLE
Two-way bindings using the hash helper exhibit unexpected behavior

### ISSUE THREAD

**Issue by monovertex** [emberjs/ember.js#15969]
In our app, we've been using objects built with the `hash` helper, and relying on double bindings on the properties inside these objects (mutating a property inside the receiving component).

This worked as we expected, but I'm not sure if it's a designed behavior.

We recently needed to build a nested object using the `hash` helper. We discovered that if we have an object build like this `(hash foo=(hash bar=value))`, passing `value=foo.bar.value` to a component would create a two-way binding correctly; however, passing `bar=foo.bar` and trying to mutate `bar.value` would not update the original `value`.

Here's an Ember Twiddle showcasing this: https://ember-twiddle.com/b7e60e16f78c969e0a5031b99885dfc2

I'm not sure if there's any bug here or not, I'm looking for more details on how the `hash` helper is supposed to work and if it should create any two-way bindings at all.

**Comment by Serabe** [comment]
`hash` is not supposed to keep double data binding.

Thank you!

**Comment by monovertex** [comment]
@Serabe: Ok, I understand that, but it does keep double data binding in some situations, as seen in my twiddle. Isn't that a valid bug then?
