### ISSUE TITLE
Descendants of "Template-only components" has wrong `_targetObject`

### ISSUE THREAD

**Issue by kategengler** [emberjs/ember.js#15977]
As discussed here: https://github.com/emberjs/rfcs/pull/278#discussion_r156799344

For convenience sake, here is a [demo app](https://github.com/kategengler/template-only-components-inspector-test) using Ember canary and a tree of:
```
application.hbs
> template-only-component
>> non-template-only-component
>>> another regular component
> partial
>> another regular component
```

Partials are not visible in the tree in the Ember Inspector but components beneath them are visible. Template-only components are not visible in the Ember Inspector, as expected, but regular components used in those template-only components are also not visible (unexpected).

Edit: added link to demo app, oops

**Comment by chancancode** [comment]
I found the bug. The problem is that the (curly) component tries to [point its `_targetObject` to the outer scope's `{{this}}`](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/component-managers/curly.ts#L211), which is `null` in the case of a template-only component.

@rwjblue @krisselden what should be the right semantics here?

**Comment by rwjblue** [comment]
I mentioned this in slack, but just wanted to clarify here also.  I do not believe this is a bug in the feature. Having a `_targetObject` of `null` is exactly the semantics that I would expect.  If this breaks functionality in the inspector, we should absolutely provide a better mechanism than `_targetObject`...

**Comment by rwjblue** [comment]
@chancancode / @kategengler - Did we decide that this wasn't an issue, or is there still something that needs addressing here?

**Comment by kategengler** [comment]
I haven't checked the inspector's current behavior yet, but if it still does not show the tree of components beneath the template-only component, I'd say that's a problem.

**Comment by pixelhandler** [comment]
@chancancode @kategengler @rwjblue is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by kategengler** [comment]
I believe this is still an issue; we discussed it just last Thursday at the Release team meeting.

**Comment by rwjblue** [comment]
Concretely, the issue is that the inspector currently does not support displaying these files (the description here is out of date IMHO).

**Comment by rwjblue** [comment]
Maybe we could migrate to https://github.com/emberjs/ember-inspector/issues/870 though?

**Comment by rwwagner90** [comment]
@rwjblue I'm fine with tracking in inspector, we definitely need a game plan to support all the various possible component types, tagless, template only, etc.

**Comment by locks** [comment]
Tracking at Ember Inspector.
