### ISSUE TITLE
`ember serve`: Livereload port finding and binding is not atomic

### ISSUE THREAD

**Issue by paddor** [emberjs/ember.js#15975]
Starting two `ember serve` processes (e.g. to test a high availability setup) using a Procfile and Hivemind/Overmind (they're like Foreman), one of them usually fails like this:

```
Livereload failed on http://localhost:49153.  It is either in use or you do not have permission.
```

Relevant lines from the Procfile:
```
ember-primary: cd webui && ember serve --port 4200
ember-backup: cd webui && ember serve --port 4201
```

Running one of them with a prepended `sleep 10;` often helps, but not always. Maybe you could make that section atomic where Ember tries to find an available port and bind to it?

**Comment by btecu** [comment]
Probably belongs in https://github.com/ember-cli/ember-cli

**Comment by rwjblue** [comment]
Agreed, @paddor would you mind moving the issue over to ember-cli's repo?

**Comment by paddor** [comment]
Sure, just did. Thanks anyway!
