### ISSUE TITLE
Unify internal testing styles

### ISSUE THREAD

**Issue by thoov** [emberjs/ember.js#15988]
Currently there are two different styles that tests are written. [An older style](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/tests/alias_test.js) which uses a QUnit global to define the module and tests via `QUnit.module()` and `QUnit.test()`. The old style also uses globals for the assertion such as `ok`, `equal`, etc. [A newer style](https://github.com/emberjs/ember.js/blob/d3d3627554e437603f6311f94f75a024d3218caf/packages/ember/tests/view_instrumentation_test.js) which does not use QUnit globals is partially rolled out in some of the packages. This issue tracks the work needed to move all tests over to the newer style and the related work surrounding it.

A breakdown of how to complete the conversion:

1) QUnit.module becomes moduleFor

```js
// Old Style:
QUnit.module('<MODULE_NAME>');

// New Style:
import { moduleFor, AbstractTestCase } from 'internal-test-helpers';

moduleFor('<MODULE_NAME>', class extends AbstractTestCase {
  //...
});
```

Note: There are a few test case classes already so check [here](https://github.com/emberjs/ember.js/tree/master/packages/internal-test-helpers/lib/test-cases) for other options.

2) QUnit.test becomes a property on the test case class

```js
// Old Style:
QUnit.test('<TEST_NAME>', function() {
  // test case here
});

// New Style:
moduleFor('<MODULE_NAME>', class extends TestCase {
  ['@test <TEST_NAME>'](assert) {
    // test case here
  }
});
```

3) Assertions should be references off of the callback assert argument

```js
// Bad:
QUnit.test('<TEST_NAME>', function() {
  equal(1, 1);
});

// Bad:
moduleFor('<MODULE_NAME>', class extends TestCase {
  ['@test <TEST_NAME>']() {
    this.assert.equal(1, 1);
  }
});

// Good:
moduleFor('<MODULE_NAME>', class extends TestCase {
  ['@test <TEST_NAME>'](assert) {
    assert.equal(1,1)
  }
});
```

Below are the packages that need to be converted:
- [x] container (🔒 @t-sauer) https://github.com/emberjs/ember.js/pull/15990
- [x] ember-application (🔒 @locks)
- [x] ember-debug (🔒 @locks) https://github.com/emberjs/ember.js/pull/15998
- [x] ember-metal (🔒 @thoov) https://github.com/emberjs/ember.js/pull/16034 https://github.com/emberjs/ember.js/pull/16036 https://github.com/emberjs/ember.js/pull/16051
- [x] ember-routing (🔒 @thoov) https://github.com/emberjs/ember.js/pull/16015 https://github.com/emberjs/ember.js/pull/16029 https://github.com/emberjs/ember.js/pull/16030 https://github.com/emberjs/ember.js/pull/16072 https://github.com/emberjs/ember.js/pull/16105 https://github.com/emberjs/ember.js/pull/16106
- [x] ember-runtime (🔒 @thoov) 
- [x] ember-template-compiler (🔒  @karthiick) https://github.com/emberjs/ember.js/pull/16010
- [x] ember-utils (🔒 @locks) https://github.com/emberjs/ember.js/pull/15997
- [x] internal-test-helpers (🔒 @thoov) https://github.com/emberjs/ember.js/pull/16033
- [x] ember-testing (:lock: @cibernox) https://github.com/emberjs/ember.js/pull/16022
- [x] ember (🔒 @locks) #16019 #16449

Below is the test related cleanup that is needed:
- [ ] Move off of QUnit global (🔒 @thoov)
- [x] upgrade to QUnit 2 #16073
- [x] remove testBoth & testWithDefault (🔒 @thoov) #16450

**Comment by rwjblue** [comment]
Thanks for putting this together @thoov!

**Comment by locks** [comment]
I have taken `ember-application`, `ember-debug`, and `ember-utils`.

**Comment by t-sauer** [comment]
I will take a stab at container.

**Comment by mikerhyssmith** [comment]
Happy to take a stab at runtime!

**Comment by cibernox** [comment]
I can take `ember-testing`

**Comment by locks** [comment]
Took part of `ember`: https://github.com/emberjs/ember.js/pull/16019.

**Comment by Turbo87** [comment]
Can anyone tell me the advantages of the new testing API given that for Ember projects we're now explicitly moving away from moduleFor? 🤔

**Comment by rwjblue** [comment]
The `moduleFor` being used here is completely unrelated to the legacy `moduleFor` implementation that is provided by `ember-qunit`.

**Comment by Turbo87** [comment]
@rwjblue I'm aware of that, but it seems that the same pros and cons apply and I'm wondering why this decision was made

**Comment by Serabe** [comment]
Went through all the PRs and updated current state. Need to know a couple of details:

1. @thoov is ember-metal complete?
2. @mikerhyssmith do you need some help with ember-runtime?

Thank you!

**Comment by thoov** [comment]
@Serabe ember-metal is not complete yet. I will have the remaining work done in a PR either later today or sometime this weekend.

**Comment by mikerhyssmith** [comment]
Hi @Serabe sorry for the delay, I will have the PR done this weekend !

**Comment by Serabe** [comment]
np. Thank you both!

**Comment by rwjblue** [comment]
@thoov - Can we add some info for refactoring ember-runtime/packages/suites to use a more conventional system?  Specifically, I'd like to do something like what I described in https://github.com/emberjs/ember.js/pull/16072#discussion_r159994024....

**Comment by thoov** [comment]
@rwjblue Yes I will add an example for converting the ember-runtime `suite` over to your example

**Comment by thoov** [comment]
@mikerhyssmith For packages/ember-runtime/tests/suites:

It currently has a concept called SuiteBuilder that needs to be converted to the newer AbstractTestCase model. 

```js
// BEFORE
const suite = SuiteModuleBuilder.create();

suite.module('includes');

suite.test('includes returns correct value if startAt is positive', function(assert) {
  let data = this.newFixture(3);
  let obj  = this.newObject(data);

  assert.equal(obj.includes(data[1], 1), true, 'should return true if included');
  assert.equal(obj.includes(data[0], 1), false, 'should return false if not included');
});
```

```js
// AFTER

// this class should go in `internal-test-helpers/lib/test-cases`
class RuntimeTestCase extends AbstractTestCase {
  newFixture() {
    // ...
  }

  newObject() {
    // ...
  }

  // ...
}
```

```js
// now you can convert the test pretty much one to one

moduleFor('includes', class extends RuntimeTestCase {
  ['@test includes returns correct value if startAt is positive', function(assert) {
    let data = this.newFixture(3);
    let obj  = this.newObject(data);

    assert.equal(obj.includes(data[1], 1), true, 'should return true if included');
    assert.equal(obj.includes(data[0], 1), false, 'should return false if not included');
  }
});
```

Let me know if you need any help with this or anything in packages/ember-runtime

**Comment by mikerhyssmith** [comment]
@thoov thanks ! I noticed a fair few of the remaining tests have testBoth in and some work has been done in the ember-metal tests to support that. Do I need to wait for that to go in first ?

**Comment by thoov** [comment]
@michaelklishin We are moving away from testBoth as under the hood it is just converting it to this (https://github.com/emberjs/ember.js/blob/master/packages/internal-test-helpers/lib/test-groups.js#L15-L25) however in the second QUnit test it references USES_ACCESSORS which is never set and therefore it just does `assert.ok('SKIPPING ACCESSORS');` which isn't useful. Originally we were going to support both cases (which is probably what you saw) but realized that we could just kill that one off. Here is a PR I recently did that moved away from testBoth (https://github.com/emberjs/ember.js/pull/16072/files) that you can use as a guide and let me know if you need help with anything.

**Comment by pixelhandler** [comment]
@Turbo87 @cibernox @karthiicksiva @locks @mikerhyssmith @rwjblue @t-sauer @thoov is this still an issue, perhaps we should close, what do you think?
