### ISSUE TITLE
Ember.testing not set during imports

### ISSUE THREAD

**Issue by davelindquist-egistix** [emberjs/ember.js#16006]
## Summary

The `Ember.testing` flag (indicating we are in test mode) is not set to `true` when doing the imports from a test.  It is set to `true` ONLY when actually inside the test methods.

## Example

See the Ember Twiddle at https://ember-twiddle.com/71a3a8975a8dd60060edc1d359ac083e

This (above) Ember Twiddle SUCCEEDS, because Ember Twiddle supports only Ember 2.12.

If, however, you take the exact same code - specifically the files:
- `components/my-component.js`
- `templates/components/my-component.hbs`
- `tests/integration/components/my-component-test.js`
and place it into your own project using Ember 2.16, the second assert will fail.

## The Problem

The problem is that the Ember.testing flag is set somewhere between the imports and the actual starting of test methods (unlike Ember 2.12, where the Ember.testing flag was set before any imports occurred).

There are several places where this causes real-life problems for us, but perhaps the easiest case to understand and document is where we have something like:

```javascript
import Ember from 'ember';

const kDebounceDelay = Ember.testing ? 10 : 1000;

export default Ember.Component.extend({
    
    ...
    Ember.run.debounce(this, this.doSomething, kDebounceDelay);
    ...

})
```

This is used to make testing more efficient, preventing unnecessarily long waits when in testing mode.  Unfortunately, it stopped working at some point after 2.12 and before 2.16 due to this bug.

## Workaround

It is possible (though VERY ugly) to create a workaround from this by:

1. Create a new 'util' (`ember g util force-testing-mode`) with contents of:
```javascript
import Ember from 'ember';

Ember.testing = true;

export default function forceTestingMode() {
  return true;
}
```
2. Inside your test, import this file as the very FIRST import (then call the method to prevent lint errors):
```javascript
import forceTestingMode from 'myapp/utils/force-testing-mode';
import { module, test } from 'qunit';

forceTestingMode();

module('Unit | Mixin | something');
...
```

## Desired Behaviour

We would like to see this behaviour restored to the 2.12 and prior behaviour, where `Ember.testing` is set to `true` throughout the whole process (i.e., even when doing imports).

**Comment by rwjblue** [comment]
> The Ember.testing flag (indicating we are in test mode) is not set to true when doing the imports from a test. It is set to true ONLY when actually inside the test methods.

This is a wonderful summary of exactly how the system is supposed to work.

> unlike Ember 2.12, where the Ember.testing flag was set before any imports occurred

This is completely unrelated to Ember version. The change in behavior came from an update in ember-test-helpers (specifically https://github.com/emberjs/ember-test-helpers/pull/227).

`Ember.testing` is not intended to be a way to determine the current build environment, it has a very specific purpose. That is to answer the question: "are we actively running a test?".  

See a similar question from this morning over in an ember-qunit issue https://github.com/emberjs/ember-qunit/issues/297#issuecomment-352385666.  

The rough summary here is that when you want to do a different thing based on _environment_ you should import the environment config and use that as your conditional, and when you want to do something based on if a test is currently running you should use `Ember.testing`.

I do not believe this is a bug. 😄

**Comment by davelindquist-egistix** [comment]
Hmm, I'm not sure I agree (or perhaps I don't completely understand)

> `Ember.testing` is not intended to be a way to determine the current build environment, it has a very specific purpose. That is to answer the question: "are we actively running a test?".

That is exactly what I'm trying to determine -- I'm not trying to determine the current build environment, but rather trying to adjust behaviour based on whether I am actively running in a test.

> The rough summary here is that when you want to do a different thing based on environment you should import the environment config and use that as your conditional

Unfortunately, what we are trying to do cannot be done this way -- having (for example) a "test" environment that changes this type of thing instead of using `Ember.testing` would work great for automated tests on TeamCity, but won't work for developers -- switching environments just to run tests is just to prohibitive under nodejs.

I'm a bit confused as to why:
```javascript
import Ember from 'ember';

const kIsTesting = Ember.testing;

export default Ember.Component.extend({
    
    ...
    console.log(kIsTesting); // Returns false/unset
    console.log(Ember.testing); // Returns true
    ...

})
```
would be the desired behaviour?  This seems inconsistent?  (Or am I totally misunderstanding, and Ember.testing is always supposed to be false/unset inside all of my code except actual test code?)

I'm perfectly happy to say "not a bug" if I'm doing it wrong, but I don't see a viable alternative here?  Could you point me in the right direction?

Thanks!

**Comment by rwjblue** [comment]
> That is exactly what I'm trying to determine -- I'm not trying to determine the current build environment, but rather trying to adjust behaviour based on whether I am actively running in a test.

This doesn't seem to be in line with your example at all. Module imports are evaluated quite a bit earlier than when the tests themselves are actually running.  You can confirm this a few ways but maybe the easiest way is by throwing a debugger in the module at the same location and looking at the QUnit runner.  

> Unfortunately, what we are trying to do cannot be done this way -- having (for example) a "test" environment that changes this type of thing instead of using Ember.testing would work great for automated tests on TeamCity, but won't work for developers -- switching environments just to run tests is just to prohibitive under nodejs.

Hmm, I think we are talking a bit past each other here. I'm not suggesting folks close their running `ember serve` and start up a new one via `ember test --serve`. Navigating to `/tests/?hidepassed` with an `ember serve` sets things up in the test environment just fine. No server restart required...

As a matter of fact, I'm having a very very hard time figuring out how you could actually run tests (`ember s` + `/tests`, `ember test`, `ember test --serve`, etc) _**without**_ having `import config from '../config/environment'; console.log(config.environment);` printing `test` 😝 .

> I'm a bit confused as to why:
>
> ```
> import Ember from 'ember';
> 
> const kIsTesting = Ember.testing;
> 
> export default Ember.Component.extend({
>     
>     ...
>     console.log(kIsTesting); // Returns false/unset
>     console.log(Ember.testing); // Returns true
>     ...
> 
> })
> ```
> would be the desired behaviour? This seems inconsistent? (Or am I totally misunderstanding, and > Ember.testing is always supposed to be false/unset inside all of my code except actual test code?)

`Ember.testing` is not a constant, it changes to `true` when a test starts, and back to `false` when tests complete.  In the snippet you pasted above you are stashing off the `Ember.testing` value in module scope before testing has began (see my comment above about module evaluation time vs test start time) and as such it can _never_ change (it isn't bound, or a function that you are invoking).  In the snippet where you are using `Ember.testing` directly inside one of the components functions, you will get the current value (which may or may not be `true` depending on if you are running tests).

> I'm perfectly happy to say "not a bug" if I'm doing it wrong, but I don't see a viable alternative here? Could you point me in the right direction?

Hehe, thats what I've been trying to do! 😸   Did you review the comment thread I pasted to you above (here again https://github.com/emberjs/ember-qunit/issues/297#issuecomment-352385666)?  It describes _exactly_ the problem you are trying to solve, and my comment just below includes a snippet showing them how to properly detect the current environment in module scope...

**Comment by davelindquist-egistix** [comment]
Ah, so you are saying that `ember serve` itself does not set up the 'environment', but the 'environment' is determined by what I'm doing?

So when I browse to http://localhost/ I get the "development" environment, and when I browse to http://localhost/tests/ I get the "test" environment?  That would make sense, and would allow me to control things the way I want.  (Obviously I was misunderstanding the rigidity of "environment"!)

And now the other thread makes sense, too -- thanks for the clarification!

Oddly enough, as I was experimenting further with this, I found some truly weird behaviour:

In the example I posted a twiddle for, everything actually works correctly in ember 2.16 -- even the `const` at the top!  (Perhaps because it is an integration test?)  In other words, it proves the opposite of what I said. :simple_smile:

However, in a UNIT test against a "util" class, it seems like Ember.testing is:
* True within the test function itself
* False within all code inside the util, even when called from inside a test (and directly referenced as Ember.testing!)

Anyway, this is moot because I shouldn't be using `Ember.testing` -- I'll proceed with the "test environment" check.

Thanks!

**Comment by rwjblue** [comment]
> In the example I posted a twiddle for, everything actually works correctly in ember 2.16 -- even the const at the top! (Perhaps because it is an integration test?) In other words, it proves the opposite of what I said.

The behavior change you are witnessing is completely unrelated to Ember version. It is based on the version of ember-qunit (and therefore `@ember/test-helpers`) that is being used.  Twiddle is using the same version of ember-qunit across the board, so it is very unlikely to show the issue you saw.

> However, in a UNIT test against a "util" class, it seems like Ember.testing is:
>
> * True within the test function itself
> * False within all code inside the util, even when called from inside a test (and directly referenced as Ember.testing!)

FWIW, this was actually what fixed the issue I have linked to a few times now. The _exact_ issue was `Ember.testing` not being set properly _during_ a test of a utility function. That was fixed in https://github.com/emberjs/ember-qunit/pull/303 (and only released yesterday 🎉 )...
