### ISSUE TITLE
concatenatedProperties mishandles {} and false

### ISSUE THREAD

**Issue by nathanhammond** [emberjs/ember.js#16014]
In a naive attempt to turn off `concatenatedProperties` I discovered this:

```javascript
var a = Ember.Component.extend({
  classNames: ['parent'],
  concatenatedProperties: {} // false also fails
});

console.log(a.proto().concatenatedProperties);
// => ["classNames", "classNameBindings", "attributeBindings", {}]
```

**Comment by bekzod** [comment]
I think it should be disabled when `concatenatedProperties: null`,  can confirm such behavior exist for `mergedProperties` too, I can fix if we define right behavior first here :)

**Comment by rwjblue** [comment]
I do not think we intend to support disabling `concatenatedProperties`. The provided example should trigger an assertion (basically if the value passed as `concatenatedProperties` is not an array, we should assert).

**Comment by esbanarango** [comment]
@rwjblue @nathanhammond  Is this issue worth to be labeled with `Needs Team Discussion`? Or move this to [discuss](https://discuss.envoy.com/) and keep the conversation there?

I think we could close this as an issue.

**Comment by pixelhandler** [comment]
Closing for now.
