### ISSUE TITLE
application-loading does not work from an addon

### ISSUE THREAD

**Issue by BlueRaja** [emberjs/ember.js#16013]
I wanted to create an addon which adds a shared loading screen to our apps, but no matter what I do I cannot get it to work.  We are using `pods` in both the app and the addon, if that matters.

I thought the addon's `app` folder is merged with the app's `app` folder, so putting `application-loading/template.hbs` there should work, but it doesn't.  Copying+pasting the exact same `application-loading/template.hbs` directly into the app works fine, though.

Interestingly, if I edit the addon's `application-loading/template.hbs`, the app's console shows
```
file changed pods/application-loading/template.hbs
```
but the loading screen is still not shown.

**Comment by Serabe** [comment]
Not exactly. Not the whole tree is merged. I think the best approach would be to expose the loading page as a component and use it in your app.
