### ISSUE TITLE
Handle sorting null values using computed.sort

### ISSUE THREAD

**Issue by jvenezia** [emberjs/ember.js#16020]
Not sure if it's already possible to do that with the actual implementation, but it would be handy to choose how to sort "nulls".
Similar to SQL's `order by ... nulls last`

Something like this: 

```
  notesSorting: ['createdAt:asc:nullsLast'],
  sortedNotes: computed.sort('notes', 'notesSorting')
```

Right now `asc` put them at the beginning, and `desc` at the end.

**Comment by Serabe** [comment]
This is a feature request and, as such, requires to go through [the RFC process](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature).

Thank you!

**Comment by jvenezia** [comment]
Okay, thanks!
