### ISSUE TITLE
setting model for my route 

### ISSUE THREAD

**Issue by mehrajpasha** [emberjs/ember.js#16035]
Hi,I'm trying to create a quiz app..According to the id={1,2,3,4,5} in my route questions/id my template should generate the data of the each of the object of arrays data given manually my be in questions.Please tell me what queries to use ?

**Comment by Serabe** [comment]
Hello, @mehrajpasha . I am closing this since it is not an Emberjs bug. Please, go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

Thank you!
