### ISSUE TITLE
ember radio buttons prob

### ISSUE THREAD

**Issue by mehrajpasha** [emberjs/ember.js#16042]
Hi, I was following this "https://ember-twiddle.com/7e10351fed541a2056b5a3d9b145d915?openFiles=templates.application.hbs%2C" In the place of AVG and MAX I have binding values coming from another JSON object(i.e {{query.choice}})..while I'm getting values in controller I'm getting as {{query.choice}} I need actual binded value

**Comment by locks** [comment]
Thank you for reaching out @mehrajpasha, however, we reserve the issue tracker for bugs in Ember. Check our [community page](https://emberjs.com/community/) for StackOverflow, Discuss, and Slack links where you can ask your question.
Good luck!
