### ISSUE TITLE
'this' undefined from component integration test?

### ISSUE THREAD

**Issue by stephanebruckert** [emberjs/ember.js#16052]
Also posted on SO: https://stackoverflow.com/questions/48359509/this-undefined-only-from-component-integration-test

```
import Ember from 'ember';

const { Component, computed, inject: { service } } = Ember;

export default Component.extend({
  currentUser: service(),

  classNames: ['list-group-item'],
  tagName: 'li',

  visibleReagents: computed.filter('inventory.reagents', function(reagent) {
    return this.get('currentUser.showArchivedReagents') || reagent.get('archivedAt');
           ^ undefined only in tests
  })
});
```

This would work well ^, but not as part of the component integration tests where `this` would be undefined:

```
import { moduleForComponent, test } from 'ember-qunit';
import hbs from 'htmlbars-inline-precompile';
import startMirage from '../../../../helpers/start-mirage';

moduleForComponent('inventories/left-menu-item', 'Integration | Component | inventories/left menu item', {
  integration: true,
  setup() {
    startMirage(this.container);
  },
  afterEach() {
    window.server.shutdown();
  }
});

test('it renders', function(assert) {
  let inventory = window.server.create('inventory', {
    title: 'My inventory', createdAt: '12/01/2017'
  });
  inventory.reagents = window.server.createList('reagent', 15, { inventory });

  this.set('inventory', inventory);
  this.render(hbs`{{inventories/left-menu-item inventory=inventory}}`);
  assert.equal(this.$('li').length, 1);
  assert.equal(this.$('.badge').length, '1');
});
```

Why isn't `this` accessible from the test?

**Comment by rwjblue** [comment]
I'm not sure that this is an Ember bug, and so we may need to move it to a different issue tracker once we have done more investigation. Generally speaking, I don't see an obvious issue (though it is odd that you start routing in a component test) with the code snippets you shared, and this type of test is known to work.  I think we would need a reproduction in a repo that we could clone and test.

**Comment by stephanebruckert** [comment]
You are right, it could be linked to Mirage. Also yes the routing stuff was useless, I removed it. 

I'm still working hard on this issue and I am going to isolate it in a separate repo for you to have a look. Before I come back to you, I first need to upgrade my app to the latest (2.11 -> 2.18) and Mirage (0.3 -> 0.4), I realised this is something I need to do anyway and it might solve my current problem.

**Comment by stephanebruckert** [comment]
@rwjblue here is a dummy repo https://github.com/stephanebruckert/mirage-component-integration-test

Uncomment the debugger line 7 https://github.com/stephanebruckert/mirage-component-integration-test/blob/master/app/components/left-menu-item/component.js#L7

Run as usual and compare:
  - http://localhost:4200/inventories
    - In debug mode, type `this` and see that it is defined
 - http://localhost:4200/tests
    - In debug mode, type `this` and see that it is `undefined`

In this dummy app I don't need `this`, but in my app I need it to get my `service`.

Thanks in advance!

**Comment by rwjblue** [comment]
> Example:
> 
> ```js
> export default Component.extend({
>   visible: computed.filter('inventory.reagents', () => {
>     // debugger
>     return true;
>   })
> });
> ```

You cannot use arrow functions with an `Ember.computed` (if you want to have the correct `this`). Arrow functions intentionally modify the `this` context inside the function to match the `this` context from where they are created. In this case, you are creating the arrow function in module scope which (when in strict mode) has no `this` context at all.

To fix the issue you would need to update to:

```js
export default Component.extend({
  visible: computed.filter('inventory.reagents', function() {
    // debugger
    return true;
  })
});
```

**Comment by stephanebruckert** [comment]
Ha sorry, I think `eslint` changed that automatically, perhaps because I am not using any actual `this` inside that context.

However it gives the same result without arrow functions. :(

I've pushed the change.

**Comment by Serabe** [comment]
Hi, @stephanebruckert,

Your demo project adds a ton of deps, both in package.json and in bower.json. Can you try reproducing this with a brand new project (`ember new bug-reproduction`) and just using Mirage (`ember install ember-cli-mirage`) and add the model, route, etc.?

There are too many deps to track down what is happening easily.

Thanks!

**Comment by stephanebruckert** [comment]
Hi there, I'm back with a brand new project: https://github.com/stephanebruckert/ember-bug-16052

The 4th commit shows that `this` is available as expected.
The 5th commit shows that `this` is not available anymore, as soon as a relationship `sub-dummy` is added to my main model `dummy`.

Thanks for your time 👍

**Comment by luxferresum** [comment]
As explained on the SO-question there is no bug in ember. There might be a bug in mirage (they override `.filter()` on their custom collection type without proper `this`-management).

**Comment by stephanebruckert** [comment]
Thanks @luxferresum, as you suggested it can be worked around by doing:

```
filteredSubs: computed('dummy.subs', function() {
    return this.get('dummy.subs').filter(s => s);
})
```

Not an Ember issue, maybe an ember-cli-mirage issue being discussed here https://github.com/samselikoff/ember-cli-mirage/issues/1256

Thanks everyone
