### ISSUE TITLE
tryInvoke, canInvoke, compare, isEqual missing updated imports in docs

### ISSUE THREAD

**Issue by jenweber** [emberjs/ember.js#16079]
According to [RFC176](https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md) these should be part of the `@ember/utils` module, but API docs do not reflect this. I think they just got overlooked.

Documentation block [here](https://github.com/emberjs/ember.js/blob/241adea495be3363dfc4c09a749e73230fa80998/packages/ember-utils/lib/invoke.js)

Should follow the same pattern as [this example](https://github.com/emberjs/ember.js/blob/v2.18.0/packages/ember-metal/lib/is_blank.js#L5) with a class and fixed method

Update ought to target 2.18 LTS candidate and later

**Comment by jenweber** [comment]
https://github.com/emberjs/ember.js/pull/16080

**Comment by locks** [comment]
Addressed by PR mentioned above.
