### ISSUE TITLE
Can not use router service in route

### ISSUE THREAD

**Issue by bobisjan** [emberjs/ember.js#16088]
Hi,

when I inject [RouterService](https://emberjs.com/api/ember/2.18/classes/RouterService) into some route, this property is replaced by `router:main`.

```javascript
import Route from '@ember/routing';
import { inject } from '@ember/service';

export default Route.extend({
  router: inject()
});
```

[API](https://emberjs.com/api/ember/2.18/classes/Route?show=inherited%2Cprotected%2Cprivate) does not expose `router` property (public or private), I can use named inject like `routing: inject('router')`, but it seems to me, that this should work out of box?

The intent is to use `ember-cli-meta-tags` and [urlFor()](https://emberjs.com/api/ember/2.18/classes/RouterService/methods/urlFor?anchor=urlFor) to generate URL for `rel` meta tags and the `router:main` does not have this method available.

Thanks

**Comment by locks** [comment]
This is because `router` is already a private property of the `Route` class.
Hm, not sure what specifically is going on here… Can you provide an ember-twiddle.com reproduction?

**Comment by bobisjan** [comment]
I see that `router` is used in route's [codebase](https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/route.js#L1118), but I'm not sure if the injection should work (as other service injections) or `router` should be marked as private in API and maybe throw error when someone tries to inject router service into route using `router: inject()`?

[Here](https://ember-twiddle.com/3e8a06fbfd34066eaee87278268a464b?openFiles=routes.index.js%2C) is a basic Twiddle, see console with logged error, `router` is not a  router service instance.

**Comment by cibernox** [comment]
FWIW, since Route#router is private API, this seems a bug to me. That private API should be `_router` or something even more private that doesn't preclude users to inject the router service with the very reasonable name of "router".
