### ISSUE TITLE
Re-create DOM element from component

### ISSUE THREAD

**Issue by kanongil** [emberjs/ember.js#16111]
I have a custom component that wraps a `<video>` element:

```js
export Component.extend({
  tagName: 'video',
  …
});
```

When I change content, I need to reset the state of the element. Unfortunately, the DOM APIs does not allow all state to be reset (eg. there is an `addTextTrack()` method, but no way to remove it again).

This means that I need to remove the `<video>` element, and replace it with a new one, to reliably reset the state. I currently do this from a parent component by having a property that toggles the rendering in the template:

```hbs
{{#if isRendering}}{{my-video}}{{/if}}
```

```js
resetVideo() {
  this.set('isRendering', false);
  run.schedule('afterRender', () => {
    this.set('isRendering', true);
  });
}
```

However, this is not something that should concern the parent, and I would like a way to do it cleanly from the component itself. Maybe through a new component method?

**Comment by rwjblue** [comment]
I would make the main component `tagName: ''` and move the `<video>` element itself into the template, then it is quite easy to wrap that in a conditional.

**Comment by kanongil** [comment]
I know, but this comes with implementation issues as well. Eg., I can no longer use `classNames` and `attributeBindings`, and would have to traverse the DOM to find the actual `video` element to call my methods on.

This leads to my actual current solution, which is to use a wrapper parent component. Something I feel should not be needed.

**Comment by kanongil** [comment]
Note that the element reset issue also applies to other stateful DOM elements, like [`<input type="file">`](https://stackoverflow.com/questions/20549241/how-to-reset-input-type-file).

Maybe glimmer should handle this?

**Comment by rwjblue** [comment]
The solution that I suggested is almost certainly the path forward, as it will be much closer to what glimmer components (where the template includes the root element, instead of configuring it in JS). I definitely agree that there are still issues to be dealt with (RE: finding the element) but there are some decent work arounds for that as well.

For example, to grab the video element you could do something like:

```hbs
{{#if showVideo}}
  <video id="video-component-{{videoId}}" {{! other things here }}></video>
{{/if}}
```

```js
let videoId = 0;
export default Component.extend({
  tagName: '',

  init() {
    this._super(...arguments);

    this.videoId = videoId++;
    this.videoElement = undefined;
  },

  didInsertElement() {
    this.videoElement = document.getElementById(`video-component-${this.videoId}`);
  }
});
```

**Comment by Serabe** [comment]
@rwjblue shall we close this then?

**Comment by rwjblue** [comment]
Sure, will close for now.  Happy to reopen if the suggestion doesn't work...
