### ISSUE TITLE
Generated service cannot be injected until Ember serve is restarted 

### ISSUE THREAD

**Issue by myartsev** [emberjs/ember.js#16133]
I got stuck for a little while trying to figure out why I couldn't inject a newly created service. Turns out that restarting **ember serve** solved the issue, but still, here are the reduced steps to reproduce the problem every time:

`ember new super-rentals`  
`ember s`  

In another terminal:
`ember g service shopping-cart`  
`ember g component foo-cmp`  

_application.hbs_  
`{{foo-cmp}}`

_foo-cmp.js_
```
import Component from '@ember/component';
import { inject as service } from '@ember/service';

export default Component.extend({
  shoppingCart: service()
});
```  

The full error message in the browser console:

> "Error: Assertion Failed: Attempting to inject an unknown injection: 'service:shoppingCart'
>     at new EmberError (http://localhost:4200/assets/vendor.js:24147:25)
>     at assert (http://localhost:4200/assets/vendor.js:24390:15)
>     at Registry.validateInjections (http://localhost:4200/assets/vendor.js:21434:66)
>     at FactoryManager.create (http://localhost:4200/assets/vendor.js:21019:35)
>     at Proxy.create (http://localhost:4200/assets/vendor.js:20802:20)
>     at CurlyComponentManager.create (http://localhost:4200/assets/vendor.js:25615:37)
>     at http://localhost:4200/assets/vendor.js:13213:33
>     at AppendOpcodes.evaluate (http://localhost:4200/assets/vendor.js:11612:13)
>     at VM.next (http://localhost:4200/assets/vendor.js:18788:32)
>     at TemplateIterator.next (http://localhost:4200/assets/vendor.js:18859:28)"

**Comment by IvaWonderbush** [comment]
Thank you <3

**Comment by Serabe** [comment]
I've just checked and this is still happening.

**Comment by pixelhandler** [comment]
@IvaWonderbush @myartsev is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by pixelhandler** [comment]
@myartsev is this still happing in a current release of Ember?

**Comment by pixelhandler** [comment]
I was not able to reproduce using ember-cli v3.5, closing for now.
