### ISSUE TITLE
Array Prototype Extensions causing problems for jQuery File Upload Plugin

### ISSUE THREAD

**Issue by akondo06** [emberjs/ember.js#16141]
Hi, 
I tried to upgrade to Ember `3.0.0-beta.3` from `2.18` and got stuck only by this.

I have reproduced the issue in a new ember-cli project and can be found here: https://github.com/akondo06/file-upload-bug

What I tried is documented in the readme there.

**Comment by rwjblue** [comment]
Thanks for reporting! This is essentially the same issue as the following:

* https://github.com/emberjs/ember.js/issues/16141
* https://github.com/emberjs/ember.js/issues/16053
* https://github.com/emberjs/ember.js/issues/16049

**Comment by rwjblue** [comment]
I believe this is fixed in 3.0.0-beta.3. Closing for now, but happy to reopen if I'm mistaken...

**Comment by akondo06** [comment]
I tested it with the posted repo and no related errors pop up. Thanks :)
