### ISSUE TITLE
Memory leak with "action" helper and async/await tests

### ISSUE THREAD

**Issue by lstrzebinczyk** [emberjs/ember.js#16152]
# Memory leak

I believe I might have found a memory leak. I created an application that reproduces the problem available at https://github.com/KillaPL/ember-memory-leak.

There is a description of the issue in repository readme, here is a copy:

According to [this page](https://github.com/ember-best-practices/memory-leak-examples), after any tests execution, there should be no "Container" object in heap snapshot. If there is one, it means there is a memory leak.

I believe I found one reproducible case.

"action" helper in hbs, when used via a test implemented with async/await will leak memory.

This does not happen if the test is written in old style (with `waitFor`).

## Reproduction steps

1. `yarn`
2. `ember s`
3. open Chrome browser
4. visit "/tests"
5. select "Acceptance | memory leak" module
6. let the tests run
7. open console, Memory tab
8. Take heap snapshot
9. Filter for "Container"
10. There is a container object in heap

There should not be a container object in heap at this point. It does not happen if "action" helper is not used, or if the test is not async/await.

As far as I was able to confirm, this happens for all version of `ember-source` from 2.11 to 2.18, also on 3.0.0-beta.3.

In my application there is more than 1300 tests, compiling a lot of templates in which we use `{{action "actionName"}}`, all tests async. This seems to add to a lot of leaked memory.

## Additional notes

If Ember Twiddle or JSBin are preferred over reproduction repo, I will work on providing one.

**Comment by rwjblue** [comment]
Thanks for the detailed bug report!

Can you update the action usage to something more idiomatic? The exact usage in the demo app is basically a components template with `{{action ‘something’}}` in the root of the template (e.g. neither assigning a value or used in element space). I think this specific usage is something that Ember should assert on...

It is unclear if that is related to what you are seeing, but the closer we make this to what we expect the easier it will be to rule things out....

**Comment by KillaPL** [comment]
I initially found out that it's code like `<button onclick={{action "memoryLeak"}}></button>` that is leaking the memory, but `<button onclick={{memoryLeak}}></button>` is not leaking (assuming memoryLeak is function in the context). This is where the usage of `action` helper itself came to me.

I updated the example to `<button onclick={{action "memoryLeak"}}></button>`, and the leak is still there.

**Comment by KillaPL** [comment]
@rwjblue I can spend time further boiling this down and maybe looking for a fix if you could point me to a right direction, I would be very happy to dig into embers internals.

**Comment by dgavey** [comment]
Appears to be duped by this #16890

**Comment by rwjblue** [comment]
It wasn't clear from re-reading the report above: are we leaking a single container here or one container per test?

**Comment by lstrzebinczyk** [comment]
As I remember, this leaked a container per tests in which this case happened. However this seems to be gone now in ember 3.5! : )

So I'm going to close this issue as solved, please let me know if there is anything more I can do to help : )

**Comment by rwjblue** [comment]
Awesome, thank you for confirming!

**Comment by GeekSMN** [comment]
I don't see 16152 or 16890 anywhere in the changelog. Is there a workaround or a fix we can add to our projects to resolve this?
