### ISSUE TITLE
Enable ember-template-block-let-helper by default

### ISSUE THREAD

**Issue by locks** [emberjs/ember.js#16150]
The goal of this issue is to track the work still necessary to ship the block `let` helper in a release of Ember.
Consult the [RFC](https://github.com/emberjs/rfcs/blob/master/text/0286-block-let-template-helper.md) for reference.

- [x] Write API documentation
- [ ] Document in the Guides

**Comment by rwjblue** [comment]
Closing in favor of https://github.com/emberjs/ember.js/issues/16400
