### ISSUE TITLE
Class Documentation for Transition disappeared between Ember 2.16 and 2.17

### ISSUE THREAD

**Issue by toddjordan** [emberjs/ember.js#16153]
If you go to https://emberjs.com/api/ember/2.16/classes/Transition (select "show private" at the bottom of the nav menu.) You'll see the last time Transition was seen alive.

A little CSI forensic work is required to figure out what happened here. Could've been some refactoring that moved it way from a place where the yuidocs are being processed.

**Comment by efx** [comment]
@toddjordan could you elaborate on 

> You'll see the last time Transition was seen alive.

I followed the steps but do not notice anything odd. 
<img width="860" alt="screen shot 2018-04-02 at 10 21 20" src="https://user-images.githubusercontent.com/472721/38199699-b02439f4-365f-11e8-93ee-c72d7f431454.png">

**Comment by toddjordan** [comment]
@efx its because the steps above show where you can find it.

Try looking for it in 2.17, 2.18, or 3.0

**Comment by efx** [comment]
ah, thanks; I see the issue now. Selecting 2.18 once you have navigated to that page brings up a 404.

**Comment by efx** [comment]
The `Transition` docs now live here: https://github.com/tildeio/router.js/blob/master/lib/router/transition.js#L7-L21
Changes to https://github.com/tildeio/router.js's package.json probably are out of sync with ember's yuidoc.json (perhaps https://github.com/tildeio/router.js/blob/master/package.json#L26-L29 ?). I tried naively here:
https://github.com/efx/ember.js/commit/7a884338ada1ba3d7e853f417a6d61cafdb06227
Having some trouble linking this locally, so posting notes for public benefit.

**Comment by rwjblue** [comment]
Fixed by #16474
