### ISSUE TITLE
`focus-in` vs `focusIn` on text inputs vs checkboxes

### ISSUE THREAD

**Issue by gabrielgrant** [emberjs/ember.js#16171]
On text inputs, both `focus-in` and `focusIn` work (although the handlers are passed different arguments), while on checkboxes, only `focusIn` does. See: https://ember-twiddle.com/6f82aa1cce20e0831e285c172ca7e998

I found this difference fairly surprising (and wasted more time than I care to admit trying to track down why actions attached to `focus-in` on my checkboxes weren't firing)

The cause of the behavior difference is that [`focusIn` is the default event name](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/system/event_dispatcher.js#L73), while [the action assigned to `focus-in` is used as the default `focusIn` handler by the `TextSupport` mixin](https://github.com/emberjs/ember.js/blob/v2.0.1/packages/ember-views/lib/mixins/text_support.js#L253) (thanks for the pointer, @alexspeller!). I haven't really figured out _why_ this distinction exists (historical reasons, perhaps?), but it would be nice if this was consistent (or at least made more clear in the docs). At the moment the sections for [actions](https://guides.emberjs.com/v2.18.0/templates/input-helpers/#toc_actions) and [checkboxes](https://guides.emberjs.com/v2.18.0/templates/input-helpers/#toc_checkboxes) are actually adjacent on the input helpers page, so it literally reads:

> Event Names must be dasherized.
> 
> Checkboxes
> 
> You can also use the {{input}} helper to create a checkbox by setting its type

which is fairly misleading.

**Comment by Serabe** [comment]
Thank you!

**Comment by pixelhandler** [comment]
@gabrielgrant is this still an issue, perhaps we should close, what do you think?

**Comment by pixelhandler** [comment]
@emberjs/learning-team-managers has this been addressed already?

**Comment by gabrielgrant** [comment]
@pixelhandler I don't believe this has been changed in the code, and this has definitely not been fixed in the docs -- current version of the docs still gives the same misleading advice: https://guides.emberjs.com/release/templates/input-helpers/#toc_actions

**Comment by jessica-jordan** [comment]
@gabrielgrant Thank you for the descriptive issue and the reproduction in the Twiddle! I'm myself not aware why both event name styles exist for the `input[type=text]` helper, but from a learning perspective I think the Guides should just mention the one type of wording that works for all input helpers as you already suggested.

**Comment by mehulkar** [comment]
The language in the guides does call out the camelCase and dasherized cases now. I think this can be closed?

**Comment by locks** [comment]
Thanks for the update, closing it!
