### ISSUE TITLE
[3.0.0-beta.4] The result of a server query is immutable

### ISSUE THREAD

**Issue by Dhaulagiri** [emberjs/ember.js#16178]
I'll try to work up a reproduction if I can, but with 3.0.0-beta.4 attempts to remove an object from an array of Ember Data objects like this:

`this.get('emberDataArray').removeObject(object)`

is hitting [this line](https://github.com/emberjs/data/blob/109a05955372e94f59d7a96fd772c5c9a59c46ae/addon/-private/system/record-arrays/adapter-populated-record-array.js#L56) in Ember data:

`The result of a server query (on ${this.modelName}) is immutable.`

![screen shot 2018-01-26 at 08 18 55](https://user-images.githubusercontent.com/1672302/35443689-995b335c-0271-11e8-8762-5da5495d0de9.png)

We are using Ember Data 2.12 but it seems like this code exists in the most recent ED as well.

If I had to guess I would assume this came about as a side effect of https://github.com/emberjs/ember.js/pull/16131 but I'm not quite sure.

**Comment by rwjblue** [comment]
@mmun - Would you mind taking a look? 

Without a deeper dive myself, it does seem that the assertion is correct doesn’t it? You are manually mutating the ED record array, and (based on this long standing assertion) it seems that ED specifically takes the stance that these are supposed to be immutable...

**Comment by Dhaulagiri** [comment]
Yeah, that does make sense now that you point it out.  It seems like we have been doing this in this specific case due to the complex web of lies that ties together this model and its related records.  Perhaps we just can't get away with this any longer 🤢 .

**Comment by Dhaulagiri** [comment]
FWIW we are still able to mutate the array via `addObject`

**Comment by Dhaulagiri** [comment]
Closing as I think the explanation here makes sense and I've better understood why we were doing what we were doing and found a better solution
