### ISSUE TITLE
Docs on observers-and-object-initialization contradicts eslint-plugin-ember recommendations

### ISSUE THREAD

**Issue by dehuszar** [emberjs/ember.js#16170]
Reviewing the [documentation](https://guides.emberjs.com/v2.18.0/object-model/observers/#toc_observers-and-object-initialization) on setting up observers on init is sets off the [ember/eslint rule](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-on-calls-in-components.md) of not using `on()` in components.

Docs should be updated to provide a preferred-pattern example.

**Comment by Serabe** [comment]
This is the only way to get an observer to be called during object initialization. In this case you would need to use the `// eslint-disable-next-line no-on-calls-in-components`

Thank you!
