### ISSUE TITLE
Ember 2.18 - Not possible to test instance-initializers

### ISSUE THREAD

**Issue by Exelord** [emberjs/ember.js#16216]
Hey,
as from 2.18 it is not possible to test instance initializers using current blueprint.
There are 2 errors:

1. Creating Application
```
Error: Assertion Failed: You cannot make a new Ember.Application using a root element that is an ancestor of an existing Ember.Application
```
2. Booting Application
When we built app instance `application.buildInstance()` it automatically boots app and fires the tested instance-initializer. So because of that, we are not able to prepare the test eg by registering own containers before running the initializer.

**Comment by rwjblue** [comment]
Please provide a reproduction, this should absolutely be possible so maybe there is an error in the specific test in question...

**Comment by Exelord** [comment]
# 1. Code
```js
export function initialize(appInstance) {
  let loggerService = appInstance.lookup('service:logger');
  return loggerService.get('enabled');
}

export default {
  initialize
};
```

# 2. Test
```js
import Application from '@ember/application';
import { run } from '@ember/runloop';
import { initialize } from 'dummy/instance-initializers/my-init';
import { module, test } from 'qunit';
import destroyApp from '../../helpers/destroy-app';

import EmberObject from '@ember/object';

module('Unit | Instance Initializer | my init', {
  beforeEach() {
    run(() => {
      this.application = Application.create();
      this.appInstance = this.application.buildInstance();
    });
  },
  afterEach() {
    run(this.appInstance, 'destroy');
    destroyApp(this.application);
  }
});

test('it should return true', function(assert) {
  this.appInstance.register('service:logger', EmberObject.extend({enabled: true}))
  assert.ok(initialize(this.appInstance));
});
```

# 3. Error
<img width="536" alt="screen shot 2018-02-05 at 15 06 56" src="https://user-images.githubusercontent.com/1469375/35808502-3f8c9114-0a86-11e8-80fc-b0a9c20c5fe5.png">

# What happened
The `buildInstace` booted the app before the tests so it was not possible to mock service first.

**Comment by Serabe** [comment]
Yes, you can. See https://github.com/Serabe/ember-issue-16216

You need to use a Service to register a  service.

Closing this.

Thank you!

**Comment by Exelord** [comment]
@Serabe Could you try with the latest ember 2.18? on 2.16 it works perfectly.
After this change Im still getting an error 
`Assertion Failed: You cannot make a new Ember.Application using a root element that is an ancestor of an existing Ember.Application`

And also, I forgot to mention: this happening for me on an addon project.

**Comment by Exelord** [comment]
I think this is related with new rfc: https://github.com/emberjs/ember.js/blob/master/blueprints/instance-initializer-test/qunit-rfc-232-files/tests/unit/instance-initializers/__name__-test.js

**Comment by ziali088** [comment]
@stopdropandrew that worked and makes sense, thanks!

**Comment by Exelord** [comment]
So we should remove it from the blueprint. :)
