### ISSUE TITLE
DOM State Doesn't Respect Bound Property Values for Select

### ISSUE THREAD

**Issue by neborn** [emberjs/ember.js#16213]
The following is a twiddle that shows a couple ways a select element can get out of sync with bound properties.

https://ember-twiddle.com/e4599598b7ad804aa5fb992a7aa99a67?openFiles=templates.application.hbs%2C

The first example shows how the value property on the select element seems to be overridden during the render process, so the value of the bound property isn't correctly reflected (unless it is incidentally the same as the first option.)

The additional examples show that the selected property on the option elements can be used to have the select element initialize correctly. But, unless the bound property's value actually changes, the DOM gets out of sync after selecting a new option.

It may be in poor taste to mention this, but this seems to work in React:

https://codepen.io/neborn/pen/bawzWp

I've seen similar issues with other form elements (e.g. input[type=radio]).

**Comment by rwjblue** [comment]
I'm not quite sure what the goal here is, are you asking _how_ to do this correctly? Are you pointing out that it is harder than it should be? Are you suggesting there is a bug here?

**Comment by neborn** [comment]
Thanks Robert for the reply.

With regards to the goal, it seems like data binding breaks down in some circumstances for form elements. And, ideally even those cases could be covered.

But, perhaps the contract that applies to components and helpers isn't intended to apply to native elements.

I want to acknowledge that it's been a little while since I originally posted, and I am now sure how updates to Ember's templating engine, etc... may have affected the behavior described.

**Comment by neborn** [comment]
I wrote this awhile ago. Really it's more of a feature request to have Ember special case native form elements and/or an acknowledgement of the limitations of the existing data binding model.

I'm not sure if the diff'ing model used by React takes care of this automatically, or if the library special cases native form elements.

If it's alright, I will keep this issue open as a request. Also, if you do have any recommendations for how to more cleanly work with native form elements, please let me know.

But, feel free to close if it's not something the team wants to tackle at this time.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by locks** [comment]
I am closing the issue for now, thank you for reporting and for the discussion!
