### ISSUE TITLE
one-way binding can't be re-rendered when coexisting with two-way binding

### ISSUE THREAD

**Issue by nightire** [emberjs/ember.js#16236]
Reproduction twiddle:

https://ember-twiddle.com/8ea355e29321eba666ec70ea821dd9ac

This demo shows a bug which

a component takes an one-way binding value and a two-way binding value at the same time, when trying to mutate both of them: 

1. two-way binding value can be updated and re-rendered
2. one-way binding value can be updated (logged in console), but cannot be re-rendered properly

However, trying to mutate one-way binding value only doesn't have any problem.

---

P.S. I'd like to send a PR to provide a test case, but I'm not sure what kind of tests should be write. It would be helpful if someone can show me an example.

**Comment by Serabe** [comment]
This is expected behaviour. With a one-way binding, given you are not changing the external value, the internal one is being overwritten over and over again by it.

What you are looking is for local writes to shadow the external attributes. For that, you will need to have an internal variable you like `internalBar: reads('bar')` (`reads` comes from `'@ember/object/computed'`). Still, external value wouldn't be overwritten.

**Comment by Serabe** [comment]
Closing.

**Comment by nightire** [comment]
@Serabe I understand what you described about internally expected behaviour, but please look at the reproduction demo, especially example 3. How do you explain this with above theory? It has one-way binding (two properties both are one-way binding) and not changing the external value as well, but they both got updated correctly!

Compare with example 1, the only difference is **two one-way binding props** v.s. **one one-way + one two-way**. 

This issue doesn't questioning about how one-way binding works internally, it reveals an inconsistency about two-way and one-way mixed together.

**Comment by Serabe** [comment]
It doesn't really. What's happening is that given there is no change in the external state, the component is not rerendering, so the shadowing works (but as long as the external state does not change). You can see it [in this twiddle](https://ember-twiddle.com/8dc06244501860b104f6806da3e67fbc?openFiles=components.data-binding.js%2C) where the component lifecicle (update part) is logged.

**Comment by nightire** [comment]
After observing life cycles on those examples, we finally understand whats going on under the hood, thank you very much for your patience and clearer explanation, these makes us feels very warm in ember community, also give us more confident to use ember more and more.
