### ISSUE TITLE
transitionToRoute is gone from the API documentation

### ISSUE THREAD

**Issue by cbou** [emberjs/ember.js#16247]
What happens to `transitionToRoute ` in the API Documentation?

It was in the 2.18.0 but not in anymore in the 3.0.0.

https://emberjs.com/api/ember/2.18/classes/Controller
https://emberjs.com/api/ember/release/classes/Controller

**Comment by Gaurav0** [comment]
Please move to `ember-api-docs`

**Comment by cbou** [comment]
Thanks!

Moved to ember-learn/ember-api-docs#468

**Comment by toddjordan** [comment]
This _is_ actually a problem in the ember.js documentation.  transitionToRoute is now defined on ControllerMixin, which is marked private.
