### ISSUE TITLE
Uncaught TypeError: RSVP.cast is not a function

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#16257]
It seems that Ember v3.1.0-beta.1 silently updated RSVP to a version that no longer includes `RSVP.cast()`, but unfortunately there was no deprecation warning prior to this. `ember-intl` seems to use that function internally though which broke our tests :-/

/cc @jasonmit

**Comment by Turbo87** [comment]
thanks to https://github.com/emberjs/ember.js/issues/16257 the original issue in `ember-intl` is already fixed, but this could still use some sort of deprecation warning 🤔

**Comment by rwjblue** [comment]
Thanks for reporting! Seems weird that RSVP removed cast in https://github.com/tildeio/rsvp.js/pull/491 and released it as a minor version bump only. 

/cc @stefanpenner

**Comment by rwjblue** [comment]
Submitted https://github.com/tildeio/rsvp.js/pull/530 to bring it back...
