### ISSUE TITLE
Computed value doesn't get properly updated on input element

### ISSUE THREAD

**Issue by kfgodel** [emberjs/ember.js#16255]
This looks like an edge use case but a valid one nonetheless. (Please correct me if I'm wrong)
Twiddle to reproduce it: https://ember-twiddle.com/0b2052179b0cafea430478f4bf767231

User steps to reproduce:
1. Input a character on the input element. The value gets coerced to the expected value "World"
2. Do it again. The input element reflects what you input, but does not get coerced as expected. However the controller property gets the correct value. 
**Expected behavior:** Input element value should reflect the bound property value after any input

Key factors for the bug:
- A computed value whose setter function returns the same value twice consecutively (regardless of the function argument)
- An input element bound to that computed property so user input triggers the setter function

_Possible cause_ (I'm guessing)
There's a stop condition to prevent infinite loop when propagating binding events that checks whether a value changed or not. This stop condition is also stopping the update event on the dom (or something like that).

_Possible fix_ (Guessing again)
When an input element bound to a property triggers a change event, since that property may be computed and alter the original value, we should compare the dom element value vs the property value to decide if and update is needed on the dom. Regardless of the property value being changed or not.

- Real case scenario
We were trying to define a custom user input where the user value gets corrected and some special characters were cleaned out or changed.

Alternative to twiddle using **ember 3**: https://github.com/kfgodel/ember-dom-value-binding

**Comment by rwjblue** [comment]
This is a somewhat known issue, essentially you are trying to sanitize or enforce specific values in your input. Here is a functioning example of one way to solve this:

https://ember-twiddle.com/9719d6070f75da6b97fc262383ed22ab?openFiles=controllers.application.js%2C

Closing for now though, as I don't believe this is a framework bug, but instead is a (fairly annoying) nuance in dealing with the DOM...
