### ISSUE TITLE
Possible memory leak in 3.0+

### ISSUE THREAD

**Issue by simonihmig** [emberjs/ember.js#16273]
I am seeing a potential memory leak with Ember 3.0 and 3.1 beta. When running an acceptance test, I would expect that any instance of `Container` is garbage collected afterwards, as the `ApplicationInstance` has been teared down. However this is not the case. 

Here is a simple reproduction, see the Readme for the steps to reproduce this:
https://github.com/simonihmig/ember-memleak

As you can see a `Container` instance is left, with some `Meta` object in the retainer path.

When I downgrade to Ember 2.18 in that app, the container is correctly GCed!

**Comment by krisselden** [comment]
@simonihmig I'm aware of some leaks of the last run test, but if there are multiple acceptance tests do you leak multiple containers?

**Comment by simonihmig** [comment]
@krisselden No, just one leaked container, even with multiple tests!

**Comment by krisselden** [comment]
I think this is fixed now

**Comment by rwjblue** [comment]
(Happy to reopen if mistaken)
