### ISSUE TITLE
observers don't trigger in complex app

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/ember.js#16292]
OK, this is really weird. I have a complex app with lots of addons involved where no observers are triggering. If I create a simple test route with a simple observer watching a plain string property it doesn't fire.  If I put that same code into a new application it works every time.

Using `ember-source 2.16.2, 2.16.4, 2.18.2`

This change (commenting the else) to `ember-metal/lib/property_events` fixes the symptoms.
```
function notifyObservers(obj, keyName, meta$$1) {
    if (meta$$1.isSourceDestroying()) {
      return;
    }

    var eventName = keyName + ':change';
    var listeners = void 0;
    if (deferred > 0) {
      listeners = observerSet.add(obj, keyName, eventName);
      accumulateListeners(obj, eventName, listeners, meta$$1);
    }// else {
      sendEvent(obj, eventName, [obj, keyName]);
    //}
  }
```

What could I have broken in my code that would cause this fix to work?

Or have I uncovered an edge case around Ember observers?

**Comment by BryanCrotaz** [comment]
@rwjblue @cibernox - thoughts?

**Comment by BryanCrotaz** [comment]
See PR #16295

**Comment by BryanCrotaz** [comment]
@rwjblue @mmun as I suspected, the app is doing something to break the framework (e.g. deferring) - I would have been surprised if I'd found a bug in something this fundamental. However the app is huge with 20 or so addons so I can't reproduce this anywhere else.

What does the PR tell us about what the app has broken?

I'd like to find what pattern to search for in the source, and then to find a way to alert to a dev that they have broken the framework in this way, and add a warning to the appropriate docs.

**Comment by BryanCrotaz** [comment]
Is deferring done with `beginPropertyChanges` and `endPropertyChanges`?

If so these appear to be global, so forgetting to call `endPropertyChanges` would seem to break all observers, application wide?

**Comment by rwjblue** [comment]
My guess is an unbalanced call to `beginPropertyChanges`, you should add some logging around where the `deferred` variable is incremented and decremented. The thing to do is identify when it gets unbalanced and dig into what is doing things wrong...

**Comment by mmun** [comment]
@BryanCrotaz that's right. you can put logging statements there (i.e. put a conditional breakpoint that contains `console.log('beginPropertyChanges', deferred)`

**Comment by mmun** [comment]
You should also be able to put a debugger in `beginPropertyChange` and look up the callstack to see what is requesting the deferral.

**Comment by BryanCrotaz** [comment]
so you should always write...?

```
beginPropertyChanges();
try {
  // do stuff
} finally {
  endPropertyChanges();
}
```

**Comment by rwjblue** [comment]
Are you saying that your app is throwing errors? That would definitely assume that is related and should be addressed (as it’s likely related)...

**Comment by mmun** [comment]
@BryanCrotaz Conceptually, yes. But you shouldn't use those functions because they are private. You should be using `object.setProperties(...)` or

```js
changeProperties(() => {
  doStuff();
});
```

which does the try-finally for you. (Hmm, unfortunately it looks like `changeProperties` is accidentally marked private.)

**Comment by BryanCrotaz** [comment]
Looks like the only code using `beginPropertyChanges` is in `ember-auth` and `ember-data`

For example in ember-data:

```
_notifyProperties(keys) {
    Ember.beginPropertyChanges();
    let key;
    for (let i = 0, length = keys.length; i < length; i++) {
      key = keys[i];
      this.notifyPropertyChange(key);
    }
    Ember.endPropertyChanges();
  },
```

**Comment by BryanCrotaz** [comment]
Documentation for beginPropertyChanges doesn't jibe with it being a private method:

> Begins a grouping of property changes.
> 
> You can use this method to group property changes so that notifications will not be sent until the changes are finished. If you plan to make a large number of changes to an object at one time, you should call this method at the beginning of the changes to begin deferring change notifications. When you are done making changes, call endPropertyChanges() to deliver the deferred change notifications and end deferring.

Perhaps this documentation should point devs to the public method `changeProperties`?

**Comment by BryanCrotaz** [comment]
We should probably also include changeProperties in https://guides.emberjs.com/v2.18.0/object-model/observers/?

**Comment by BryanCrotaz** [comment]
And changeProperties needs to be promise aware. Here's the code in `ember-simple-auth`:
```
_setup(authenticator, authenticatedContent, trigger) {
    trigger = Boolean(trigger) && !this.get('isAuthenticated');
    this.beginPropertyChanges();
    this.setProperties({
      isAuthenticated: true,
      authenticator
    });
    set(this.content, 'authenticated', authenticatedContent);
    this._bindToAuthenticatorEvents();

    return this._updateStore()
    .then(() => {
      if (trigger) {
        this.trigger('authenticationSucceeded');
      }
    }, () => {
      this.setProperties({
        isAuthenticated: false,
        authenticator: null
      });
      set(this.content, 'authenticated', {});
      this.endPropertyChanges();
    });
  },
```

**Comment by mmun** [comment]
@BryanCrotaz Seems fine to update the docs, however `changeProperties` is not a major part of the programming model and doesn't belong in the guides.

**Comment by BryanCrotaz** [comment]
@mmun doesn't it sit alongside `setProperties` as a **make multiple changes without triggering lots of redraws**?

**Comment by mmun** [comment]
@BryanCrotaz Nope. Redraws are scheduled into run loop so you redraw the same amount with and without deferred observers.

**Comment by BryanCrotaz** [comment]
ok, fewer computed property calculations. TLDR Efficiency

**Comment by mmun** [comment]
Not even that.

**Comment by BryanCrotaz** [comment]
so why do we have beginPropertiesChange etc at all if the runloop does all the magic for us?

**Comment by mmun** [comment]
@BryanCrotaz Anyways, `changeProperties` absolutely doesn't need to be made promise-aware. What you are seeing in ember-simple-auth is an invalid usage of a private API.

**Comment by BryanCrotaz** [comment]
does the begin... end need to be there at all in ember-simple-auth? Is it providing any value?

**Comment by rwjblue** [comment]
Generally speaking that simple auth example should be using finally to end property changes

**Comment by rwjblue** [comment]
> does the begin... end need to be there at all in ember-simple-auth? Is it providing any value?

Dunno, you’d have to dig into why it was added over there. I personally wouldn’t have started with that (I wouldn’t have used {begin,end}PropertyChanges there at all) so I suspect digging into their issue tracker to see what edge case it satisfies...

**Comment by mmun** [comment]
@BryanCrotaz It shouldn't. That code is also 4 years old, which may be a factor :P

https://github.com/simplabs/ember-simple-auth/commit/9923b6084ab6c8170916d5c2a74a7c49608f39d4

**Comment by BryanCrotaz** [comment]
is this API surface that used to be public perhaps?

**Comment by mmun** [comment]
It was almost surely public, or at least unmarked, at that time.

**Comment by BryanCrotaz** [comment]
ok, off to dig and experiment. Will submit some docs PRs when I've worked out what the issue is, and I'll submit PRs to the addons

**Comment by mmun** [comment]
@BryanCrotaz Regarding what `changeProperties` actually does... it ensures that if a key on a object changes multiple times, there will only be a _single_ observer call, and it occurs after `changeProperties` has finished calling your callback.

**Comment by BryanCrotaz** [comment]
So indeed, the problem was an unbalanced begin/endPropertiesChange.

As this is private API which no one should be using, would it be right to add a deprecation with a recommendation to use `changeProperties` instead?

**Comment by mmun** [comment]
@BryanCrotaz Awesome. Who was unbalancing it?

I'm seems ok to deprecate them. What do you think @rwjblue? I'm just worried about introducing extra churn if we intend to make observers async (in which case the deferral functions can just be nooped) or if we deprecate observers entirely.

**Comment by rwjblue** [comment]
Agreed.  I don’t think changeProperrties is a reasonable replacement for all scenarios, and furthermore I don’t think we should introduce churn while we also intend to significantly change the internals of the observer system. Once that work is underway, we will have a much better picture of the best direction here....

Ultimately, this type of issue is actually pretty uncommon (I’m sorry you ran into it @BryanCrotaz ).

**Comment by BryanCrotaz** [comment]
If you end up with a similar mechanism I’m the new design, please try not to make it global. Having begin return a handle to be passed to end would be much easier to debug when looking for misuse. Especially if the defer counter wasn’t global (though that’s a pig to implement)

**Comment by mmun** [comment]
Strongly agree!

**Comment by BryanCrotaz** [comment]
which module is `changeProperties` in?

**Comment by BryanCrotaz** [comment]
https://github.com/emberjs/data/pull/5365

**Comment by krisselden** [comment]
I would suggest removing any deferring before switching to changeProperties.
