### ISSUE TITLE
Ember 3.0 - Failed assertion when JSON.stringify -ing an Ember Object 

### ISSUE THREAD

**Issue by mani-mishra** [emberjs/ember.js#16323]
Upgrading to Ember 3.0 and using ```JSON.stringify```, results in following failed assertion

```Assertion Failed: You attempted to access `someValue.toJSON` (on `<(unknown mixin):ember2486>`), but `someValue` is a computed property.↵↵Due to certain internal implementation details of Ember, ```

I read the linked [RFCs and discussion](https://github.com/emberjs/rfcs/pull/281) and I understand this is just a precautionary assertion, but this breaks ```JSON.stringify``` usage. 

https://github.com/douglascrockford/JSON-js/blob/master/json2.js#L237-L238

<img width="1032" alt="screen shot 2018-03-05 at 6 48 09 pm" src="https://user-images.githubusercontent.com/3315240/36976993-939f615c-20a5-11e8-925d-ee1086763043.png">

**Comment by rwjblue** [comment]
Thank you for reporting!

We need to add `toJSON` as an exception in this list:

https://github.com/emberjs/ember.js/blob/3240b4a8756a066ff0afe67198b15f78ce66f426/packages/ember-metal/lib/properties.js#L126-L130

**Comment by chancancode** [comment]
Probably here too? https://github.com/emberjs/ember.js/blob/3240b4a8756a066ff0afe67198b15f78ce66f426/packages/ember-metal/lib/properties.js#L150
