### ISSUE TITLE
HTMLbars: Cannot pass parameter array to loc helper

### ISSUE THREAD

**Issue by schlesingermatthias** [emberjs/ember.js#16337]
According to the [documentation](http://www.emberjs.com.cn/api/classes/Ember.String.html#method_loc) it should be possible to pass an array of parameters to the loc helper. While this works in JavaScript I was trying to do something similar in a template file. 

So for a parameterized localization string like this one: 
`Hello %@1, today is %@2 `

I'd like to use it like: 
`{{loc "greetings" myArray}}`

Unfortunately this results in
`Hello , today is `

`{{loc "greetings" "John" "Monday"}}`
works, but not with a dynamically created array. 

Would it be possible to implement a behaviour similar to the component helper by using a params property, like: 
`{{loc "greetings" params=myArray}}`

**Comment by rwjblue** [comment]
The facilities provided by `loc` are not sufficient for localization and it should be deprecated (frankly I thought it already was :thinking: ). I don’t think we will go about making changes to the helper other than deprecation...

**Comment by locks** [comment]
I will second @rwjblue, and suggest that you use one of the [internationalization addon](https://emberobserver.com/categories/internationalization) instead.
You can read more about the deprecation planned in the [Ember.String RFC](https://github.com/emberjs/rfcs/blob/master/text/0236-deprecation-ember-string.md#what-is-happening-for-framework-developers), and follow the implementation at https://github.com/emberjs/ember.js/issues/16231.
