### ISSUE TITLE
ember-source@3 + ember-cli@3 does not generate valid tests

### ISSUE THREAD

**Issue by nathanhammond** [emberjs/ember.js#16344]
As of https://github.com/ember-cli/ember-cli/pull/7546 landing, [we no longer have any helpers](https://github.com/ember-cli/ember-cli/tree/v3.0.0/blueprints/app/files/tests/helpers) in Ember CLI.

This breaks the blueprints for [instance-initializers](https://github.com/emberjs/ember.js/blob/master/blueprints/instance-initializer-test/qunit-rfc-232-files/tests/unit/instance-initializers/__name__-test.js) and [initializers](https://github.com/emberjs/ember.js/blob/master/blueprints/initializer-test/qunit-rfc-232-files/tests/unit/initializers/__name__-test.js).

It also is broken for Mocha acceptance tests:
https://github.com/emberjs/ember.js/blob/master/blueprints/acceptance-test/mocha-files/tests/acceptance/__name__-test.js

(I'm not sure that I've enumerated everywhere that it fails.)

This bug is effectively a duplicate of https://github.com/emberjs/ember.js/issues/16180, but exists because https://github.com/emberjs/ember.js/pull/16229 is incomplete.

**Comment by rwjblue** [comment]
@nathanhammond - RE: the Mocha point: ember-mocha re-regenerates the `start-app` and `destroy-app` helpers (because it isn't quite finished with support for the newer testing system).

**Comment by Serabe** [comment]
Thank you!
