### ISSUE TITLE
Bug in Emberjs api

### ISSUE THREAD

**Issue by patriCall** [emberjs/ember.js#16340]
Hi!! I want to notify a neccessary correction in the emberjs api. I´ve downloaded the repository for make a contribution, but I´ve seen that in master branch the bug is fixed. However, the yuidoc in the api web still have the bug:

https://emberjs.com/api/ember/2.18/classes/@ember%2Fobject%2Fcomputed/methods/union?anchor=union
<img width="352" alt="captura de pantalla 2018-03-08 a las 15 16 59" src="https://user-images.githubusercontent.com/37182655/37155736-57aacad8-22e4-11e8-8775-4c22a6ba53b7.png">

Here, we make the import in the following (and updated) way ([rft176](https://github.com/ember-cli/ember-rfc176-data)):
`import { union } from '@ember/object/computed';`

But below, we are using the old way of calling the computed properties:
`uniqueFruits: Ember.computed.union('fruits', 'vegetables')` 

If you use this combination, the code fails.

Can you please check this part? I´ve seen that more Emberjs methods in api web have exactly the same problem in description.

And here´s the branch master in your repository, where the code is correct:
https://github.com/emberjs/ember.js/blob/f19f1868f5da8998704c46e2b84fd3c6fac9d95f/packages/ember-runtime/lib/computed/reduce_computed_macros.js#L519

Thanks a lot.

P.S. - The _union_ computed property anchor of yuidoc is not correct either, it redirects to _sort_ computed property.

Edit: I´ve made a PR with the changes

**Comment by Serabe** [comment]
I've answered the PR, but let us know what you were trying to do so we can help you with it, because the PR seems to have some problem (too many commits already in master show up there).

It is not usual to update previous versions of the docs.

In any case, can you please open an issue here https://github.com/ember-learn/ember-api-docs about the anchor bug?

Thank you!

**Comment by Serabe** [comment]
@patriCall ping

**Comment by Serabe** [comment]
Closing this according to [our triage policy](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy).

Thank you!
