### ISSUE TITLE
Cannot use computed properties in node.js

### ISSUE THREAD

**Issue by izelnakri** [emberjs/ember.js#16356]
```js
require('ember-metal');
require('ember-runtime');

const EmberObject = Ember.Object;
const computed = Ember.computed;

const User = EmberObject.extend({
  firstName: 'Izel',
  lastName: 'Nakri',
  fullName: computed('firstName', 'lastName', function() {
    return `${this.get('firstName')} ${this.get('lastName')}`;
  })
});

let me = User.create();

console.log(me.get('firstName')); // works prints 'Izel'
console.log(me.get('lastName')); // works prints 'Nakri'
console.log(me.get('fullName')); // !! CRASHES: TypeError: this.func.call is not a function

// Stacktrace:
// at ComputedProperty.Cp.get (..myproject../node_modules/ember-metal/ember-metal.js:3738:21)
```

**Comment by izelnakri** [comment]
ok I figured ember-metal npm package is 6 years old :) I can do this instead and it works!

```js
require('ember-metal-node');
require('ember-runtime-node');

const EmberObject = Ember.Object;
const computed = Ember.computed;

const User = EmberObject.extend({
  firstName: 'Izel',
  lastName: 'Nakri',
  fullName: computed('firstName', 'lastName', function() {
    return `${this.get('firstName')} ${this.get('lastName')}`;
  })
});

let me = User.create();

console.log(me.get('firstName')); // works prints 'Izel'
console.log(me.get('lastName')); // works prints 'Nakri'
console.log(me.get('fullName')); // works prints 'Izel Nakri'
```

**Comment by rwjblue** [comment]
Generally speaking, we should make this better. The main package that should be used (and is current) is `ember-source`. We should make its main entry point export the global (right now you’d have to `require(‘ember-source/dist/ember.debug’)`)...

**Comment by k3n** [comment]
> right now you’d have to require(‘ember-source/dist/ember.debug’)

I tried that, in trying to get access to the main `Ember` object, and it only returns a literal `2`. 

I'm obviously missing something...

**Comment by izelnakri** [comment]
I tried it too, this is a odd return Ember dist gives in node environment. You've actually loaded Ember successfully in node, try ```Ember.Object``` you will see that it is loaded correctly in node.

**Comment by krisselden** [comment]
It’s not actually 2 it is printing 2 because node utils inspect is calling Ember.inspect with 2 as the arg

**Comment by k3n** [comment]
```bash
$ node -v
v8.11.1
$ node
> require('ember-source/dist/ember.debug');
2
> Ember
ReferenceError: Ember is not defined
```

Is it that I also need to `require()` the `ember-metal` and `ember-runtime` packages?

**Comment by pixelhandler** [comment]
@izelnakri @k3n @krisselden @rwjblue is this still an issue, perhaps we should close, what do you think?

**Comment by k3n** [comment]
No, I believe I was just doing it wrong ;)
