### ISSUE TITLE
How to properly get html property value with Ember input helper?

### ISSUE THREAD

**Issue by Pawlarius** [emberjs/ember.js#16360]
Hello, I'm having problems when tried to get defaultValue property value ->> https://www.w3schools.com/jsref/prop_text_defaultvalue.asp

if i use ember input helpers,the result always empty string like "" , while plain html return expected value.
using input helpers : 
```
{{input type="text" value="fishy123" id="myText"}}
document.getElementById("myText").defaultValue // return ""
```

```
using plain html : <input type="text" value="fishy123" id="myText" />
document.getElementById("myText").defaultValue // return "fishy123"
```

edit:
it turns out using {{value}} in input helpers and plain html cause defaultValue return ""

**Comment by rwjblue** [comment]
Hmm, the title of this issue points to the underlying issue you are seeing here. As described in the article you linked, the `defaultValue` is the initial `value` _attribute's content, and **will not** reflect the current `value` _property_. Ember's `{{input}}` helper will always set `value` as a property, and therefore `defaultValue` will not work.

This isn't really a bug per-se, so I'm going to go ahead and close the issue...
