### ISSUE TITLE
Tutorial: autocomplete component example documentation bug

### ISSUE THREAD

**Issue by rayascott** [emberjs/ember.js#16369]
From the [Autocomplete Component step](https://guides.emberjs.com/v3.0.0/tutorial/autocomplete-component/) under the heading "An Integration Test" the **second** code listing for `tests/integration/components/list-filter-test.js` (**19** lines of code), line 13 should be highlighted as green, because the `async` keyword has been added to the `function` declaration. Without it, the test fails once the `await` keyword is added in the next code example.

**Comment by acorncom** [comment]
@rayascott thanks for the feedback! I'm going to move these issues over to the guides repo, which is where we track issues with the guides and tutorial. Would love to get more feedback there (or help fixing those bugs)

**Comment by rayascott** [comment]
@acorncom Sorry, I didn't realise there is a guides repo!

**Comment by acorncom** [comment]
@rayascott No worries at all, it's not that clear 😀
