### ISSUE TITLE
`Ember.set` does not return the value returned by the setter of a computed value

### ISSUE THREAD

**Issue by dennis95stumm** [emberjs/ember.js#16364]
When setting a value with `Ember.set` on computed values the method does not return the value
returned by the setter of the computed property. Instead of that the passed value gets returned. See [this twiddle](https://ember-twiddle.com/5c245207e14b55c57f70527d8324b0a4?openFiles=controllers.application.js%2C) for more details.

**Comment by chancancode** [comment]
This is the documented behavior, I don’t think we can change it: https://emberjs.com/api/ember/3.0/functions/@ember%2Fobject/set
