### ISSUE TITLE
Tutorial: Integration test fails on triggerKeyEvent().

### ISSUE THREAD

**Issue by rayascott** [emberjs/ember.js#16371]
From [Autocomplete Component](https://guides.emberjs.com/v3.0.0/tutorial/autocomplete-component/) under the heading "An Integration Test" (and just before the heading "Application Tests") the test in file `tests/integration/components/list-filter-test.js` ("should update with matching listings") fails due to no element passed to `triggerKeyEvent()` call. This failure also applies to the test "should initially load all listings".

Although I've only looked at Ember for less than 2 days, I get the impression this error is caused by the fact that class `.list-filter` does not exist on the `input` HTML tag generated by the `list-filter` component.

**Comment by acorncom** [comment]
@rayascott Moving this as well.
