### ISSUE TITLE
[Question] Improved no phantom support errors?

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#16372]
CI failures such as: https://travis-ci.org/asakusuma/ember-spaniel/jobs/352458566 have become common, and seem to confuse users not intimately aware that WeakMap missing is most likely the user is using an unsupported browser, in this case Phantom.js

Thoughts on adding a quick "compat check" when ember loads, this compat check can  error something more actionable.

Open questions:

* other then `typeof self.WeakMap !== 'undefined'` what other checks should be done.
* what should the error message itself
* does this require us to finally post an official browser support list? https://github.com/emberjs/website/issues/2870 cc @locks

**Comment by rwjblue** [comment]
@stefanpenner - That particular case is even worse, as its still using Bower to try to get `release`, `beta`, and `canary` builds. We don't publish there **at all** any longer, and those builds are some hodgepodge version of a pre-3.0 canary (can't recall the exact SHA but its super old).

**Comment by pixelhandler** [comment]
@rwjblue @stefanpenner is this still an issue, perhaps we should close, what do you think?

**Comment by pixelhandler** [comment]
@stefanpenner any update?

**Comment by pixelhandler** [comment]
@stefanpenner any idea on what the next steps for this issue are?

**Comment by pixelhandler** [comment]
@stefanpenner I'll close this for now since it's a question and it's inactive, perhaps re-open when ready, cc @rwjblue
