### ISSUE TITLE
Tutorial: this.on referent does not exist.

### ISSUE THREAD

**Issue by rayascott** [emberjs/ember.js#16370]
From the [Autocomplete Component step](https://guides.emberjs.com/v3.0.0/tutorial/autocomplete-component/) under the heading "An Integration Test" after the first code example, the reference `this.on` has no referent. 

Unless I'm misreading the text, or it's down to my lack of knowledge regarding JavaScript & Ember development, I can't find where the `this.on` call is used. Is this a documentation bug?

**Comment by acorncom** [comment]
Closing this one in favor of the one in guides as well
