### ISSUE TITLE
[Pls send halp!] Cleaning up the test output

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#16391]
♻️ ♻️ ♻️ **Please consider the environment before printing this Github issue.** ♻️ ♻️ ♻️

<img width="1194" alt="screenshot_3_22_18__1_46_pm" src="https://user-images.githubusercontent.com/55829/37774258-a5253a34-2dd7-11e8-807b-2c720507c877.png">

Currently, the test output is very noisy – even for green builds. This makes it very difficult find any _actual_ failures, especially on small screens and on phones.

Let's try to clean it up!

Here are the useless output I have found based on [this test run](https://travis-ci.org/emberjs/ember.js/jobs/356695733). Leave a comment about what you are looking into (🔒) so others won't duplicate the effort.

A lot of these probably have the same root cause (for example, because of how the default `Ember.onError` works) and probably require some refactoring in the test infrastructure.

* Build phase
  * [ ] `'container' is imported by tmp/rollup-cache_path-I6PjJI6s.tmp/run_loop.js, but could not be resolved – treating it as an external dependency`
  * [ ] `'ember-debug' is imported by tmp/rollup-cache_path-l0Z4sygU.tmp/index.js, but could not be resolved – treating it as an external dependency`
  * [x] `'assert' is imported from external module '@glimmer/util' but never used`
  * [x] `'assert' and 'SERIALIZATION_FIRST_NODE_STRING' are imported from external module '@glimmer/util' but never used` (🔒 @James-Byrne)
* Test phase
  * [x] `WARNING: Library "magic" is already registered with Ember.`
  * [ ] `console.trace`
  * [x] `DEPRECATION: Should not throw [deprecation id: test]` (🔒 @Draggha )
  * [x] `(node:6689) Warning: Possible EventEmitter memory leak detected. * listeners added. Use emitter.setMaxListeners() to increase limit` (🔒 @lukecoy )
  * [x] `(node:6689) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: *): Error: Navigation Timeout Exceeded: 900ms exceeded`
  * [x] `Error: Element .does-not-exist not found.` (🔒 @KamiKillertO )
  * [x] `Error: Catch me` (🔒 @KamiKillertO )
  * [x] `Error: the error` (🔒 @KamiKillertO )
  * [x] `Testing paused. Use `resumeTest()` to continue.`
  * [x] The library version banner on app boot  (🔒 @Draggha )
    ```
    DEBUG: -------------------------------
    DEBUG: Ember  : *
    DEBUG: jQuery : *
    DEBUG: -------------------------------
    ```
  * [ ] `Error while processing route: *` (🔒 @allthesignals )
  * [ ] `More context objects were passed than there are dynamic segments for the route: stink-bomb`
`
  * [x] `WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see https://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes. Style affected: *`  (🔒 @KamiKillertO )

**Comment by James-Byrne** [comment]
I can have a look at 

#### Build Phase
‘’’
'assert' and 'SERIALIZATION_FIRST_NODE_STRING' are imported from external module '@glimmer/util' but never used
‘’’

**Comment by Draggha** [comment]
I'll take a stab at

**Test Phase**

```
Testing paused. Use resumeTest() to continue.
```

**Comment by Draggha** [comment]
I'd like to take a stab at

**Test Phase**

```
WARNING: Library "magic" is already registered with Ember.
```

**Comment by KamiKillertO** [comment]
I Can have a look at `Error: Element .does-not-exist not found.`

**Comment by acorncom** [comment]
Thanks folks, I’ve updated the issue accordingly

**Comment by KamiKillertO** [comment]
I'll also take `Error: Catch me` and `Error: the error`. They are related to `Error: Element .does-not-exist not found.`

**Comment by Draggha** [comment]
I think I have an idea how to handle the library version banner on app boot:
```
DEBUG: -------------------------------
DEBUG: Ember  : *
DEBUG: jQuery : *
DEBUG: -------------------------------
```

**Comment by Draggha** [comment]
I can have a look at:

```
DEPRECATION: Should not throw [deprecation id: test]
```

:)

**Comment by acorncom** [comment]
Thanks @Draggha, noted 👍

**Comment by KamiKillertO** [comment]
I take 

```
WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; ...
```

**Comment by allthesignals** [comment]
I'll take a stab at `Error while processing route: *`

**Comment by acorncom** [comment]
Thanks @allthesignals, noted

**Comment by acorncom** [comment]
Ok folks, we've got 8 items left here. Any takers? @James-Byrne looks like there isn't a PR yet for your task, did we miss linking the PR over? Do you still want to take the one with your name on it or should we unlock that and let someone else take a stab?

**Comment by KamiKillertO** [comment]
I can take :

`node:6689) UnhandledPromiseRejectionWarning: ` and ` More context objects were passed than there are dynamic segments for the route: stink-bomb` 😄

**Comment by allthesignals** [comment]
@acorncom this test actually checks for the window console for error messages: https://github.com/emberjs/ember.js/blob/master/packages/ember/tests/routing/decoupled_basic_test.js#L3471. Should it be rewritten to check these messages differently? Or skipped? Not sure how conservative I should try to be. Thx.

**Comment by lukecoy** [comment]
I wouldn't mind taking a look at this one:

**Test Phase**
`(node:6689) Warning: Possible EventEmitter memory leak detected. * listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by rwjblue** [comment]
@lukecoy - you got it!

**Comment by KamiKillertO** [comment]
It's seems that `(node:6689) UnhandledPromiseRejectionWarning: Unhandled promise rejection` is already fixed. I cannot find this error in the logs

**Comment by KamiKillertO** [comment]
I will have a look to `'container' is imported by tmp/rollup-cache_path-I6PjJI6s.tmp/run_loop.js, but could not be resolved – treating it as an external dependency` but i'm not sure where to look 😞

**Comment by acorncom** [comment]
Hey folks, we're getting close here. Anyone blocked on things and need help in a given area?

**Comment by KamiKillertO** [comment]
🙋I'm stuck with `'container' is imported by tmp/rollup-cache_path-I6PjJI6s.tmp/run_loop.js, but could not be resolved – treating it as an external dependency`

**Comment by chancancode** [comment]
Looks like a lot of these are addressed, I am okay closing the tracking issue and filing new ones as needed. I opened #17016 and #17017. Looks like a few of these still have outstanding PRs waiting for reviews also.
