### ISSUE TITLE
Document and support {{let}} helper

### ISSUE THREAD

**Issue by locks** [emberjs/ember.js#16400]
### Mandatory
- [x] Make ember-let-polyfill (@cafreeman)
- [x] Document `{{let}}` in the Guides. [Issue](https://github.com/emberjs/guides/issues/2308). [PR](https://github.com/ember-learn/guides-source/pull/49). (@kennethlarsen)

### Optional
- [ ] Base [ember-let](https://github.com/thefrontside/ember-let) off of ember-let-polyfill. (@cafreeman)

**Comment by chilicoder** [comment]
Does your first point mean to put some sort of check like (https://github.com/rwjblue/ember-getowner-polyfill/blob/master/index.js#L19)[here] somewhere (https://github.com/thefrontside/ember-let/blob/master/index.js#L42)[here]?

**Comment by jamesarosen** [comment]
The built-in `{{let}}` helper is [documented in the API docs](https://emberjs.com/api/ember/3.1/classes/Ember.Templates.helpers/methods/let?anchor=let).

I haven't gotten it working in an Ember 3.1.0 app, but I'm not sure why yet.

**Comment by rwjblue** [comment]
It was only added in 3.2, the API docs are missing our feature flagging `@category` pragma perhaps?

**Comment by locks** [comment]
Apologies! I have opened a PR correcting the problem 😅.

**Comment by cafreeman** [comment]
Forgot to mention that the polyfill is completed and published to npm!

https://github.com/cafreeman/ember-let-polyfill

**Comment by ryanlabouve** [comment]
@cafreeman does this mean we can close this issue? Or should we add a checkbox to do something additional with documentation?

**Comment by cafreeman** [comment]
@ryanlabouve Yep, the only outstanding thing is that I need to get the polyfill listed correctly on ember-observer. I've requested a correction from them so hopefully it'll be fixed soon.
