### ISSUE TITLE
startRouting issue?

### ISSUE THREAD

**Issue by CoIin** [emberjs/ember.js#16403]
I run Safari Technology Preview, and an update to that on March 22nd 2018 has broken sites that use ember_jquery. I reported the problem to Apple, but as it may be something in your code, I thought you should know about it.

Here's an example ember application forum, that loads fine in Safari, but not in yesterday's Safari Technology Preview update:

https://forums.sketchup.com/

**Comment by rwjblue** [comment]
I'm having trouble identifying an issue. I installed the latest tech preview, visit forums.sketchup.com, and things seem to be working properly.

Can you provide more details around what issues you were seeing?

**Comment by CoIin** [comment]
Thanks for checking. I'll include a screenshot of what I see with that link, in Release 53 (Safari 11.2, WebKit 13606.1.11.2), and then with Safari Version 11.1.1 (13605.2.1). Some of the console error messages may mean something! You'll see that in Safari the page fully renders, and there are not errors. In the technology preview only the header renders, and there are lots of errors.

<img width="945" alt="screen shot 2018-04-17 at 10 56 22 am" src="https://user-images.githubusercontent.com/1057109/38887721-77c5a22a-422e-11e8-8c5d-f0072e713923.png">
<img width="877" alt="screen shot 2018-04-17 at 10 56 47 am" src="https://user-images.githubusercontent.com/1057109/38887740-8151fa50-422e-11e8-8d4f-462c06fcac01.png">

**Comment by CoIin** [comment]
So guess what, Apple released a new build of Safari Technology Preview today, build 56, and this problem is now fixed. No idea if the fix really involved your code, but whatever they did it's now working ok.
