### ISSUE TITLE
[3.1.0-beta.5] notifyPropertyChange() fails for plain objects

### ISSUE THREAD

**Issue by kanongil** [emberjs/ember.js#16427]
This unit test will fail on the latest beta:

```js
test('notifies computed properties on plain objects', function (assert) {
  let obj = {
    a: 45,
    b: computed(function () {
      return ~~(this.a / 10);
    })
  };

  assert.equal(get(obj, 'b'), 4);

  obj.a = 10;
  Ember.notifyPropertyChange(obj, 'b');

  assert.equal(get(obj, 'b'), 1);      // fails - returned value is still 4
});
```

It works, as intended, if I do the same on an ember object.

**Comment by mmun** [comment]
I assume you mean `computed('a', function(){ ... })`?

**Comment by kanongil** [comment]
No, the code is as intended. Obviously, this is not what failed for me, but a reduced test case to expose the issue.

**Comment by mmun** [comment]
This is working as intended then. Since `b` has no dependency on `a`, notifying `a` will not cause `b` to be invalidated.

**Comment by kanongil** [comment]
Ah, so I did make an error. Yes `Ember.notifyPropertyChange(obj, 'b');` is the proper failing case.

Sorry about that. I have update the original post.

**Comment by kanongil** [comment]
A bit of further investigation reveals that this usage is [scheduled for deprecation](https://www.emberjs.com/deprecations/v3.x/#toc_ember-meta-descriptor-on-object), that it also fails on canary, and that it works correctly if I use `Ember.defineProperty(obj, 'b', …)` to define the computed value.

**Comment by mmun** [comment]
Yeah, but we still need to make it work for backwards compatibility. The fix should be relatively easy but I haven't had time to work on it.
