### ISSUE TITLE
Typo in shouldRender documentation

### ISSUE THREAD

**Issue by amessinger** [emberjs/ember.js#16455]
Currently, `shouldRender` documentation states that setting its value to `true` will disable rendering.

https://github.com/emberjs/ember.js/blob/84c8ecac85175571047690540f1dea7e62115c64/packages/ember-application/lib/system/application-instance.js#L377-L379

Setting its value to `false` will actually disable rendering. `true` is the default value and will cause the application to render.

**Comment by Serabe** [comment]
Thank you!
