### ISSUE TITLE
3.1-beta.5 changes to scheduling a task that causes a re-render

### ISSUE THREAD

**Issue by alexlafroscia** [emberjs/ember.js#16464]
I have an Ember contextual component that does some work during the initial render to register itself with its parent. This registration process can cause a CP to be updated, and I want to render the the updated value of the CP on the first "paint".

The code can be found [here](https://github.com/alexlafroscia/ember-steps/blob/a01fb02e7cff69528af01f187304d90ddcc2b638/addon/components/step-manager.js#L157-L166) for reference.

Before Ember 1.13 the CP would just be computed twice in a single render, which was fine. But Ember 2 breaks that behavior (for understandable reasons).

Right now, I schedule a callback in the `actions` queue during render which triggers the CP change, and the next run loop updates the DOM accordingly. This has been working fine until Ember 3.1, where that second "render" cycle doesn't happen during tests. An example test can be found [here](https://github.com/alexlafroscia/ember-steps/blob/a01fb02e7cff69528af01f187304d90ddcc2b638/tests/integration/step-manager-test.js#L160-L175).

Using that as an example, what was happening before was that the `render` function resolved once the run queue was empty, so that when I go to validate that the first step is visible, the CP has already updated and made the step visible. However, now the CP has not been re-computed yet, meaning that the step is not yet visible. This causes a lot of these tests to fail.

My question then is two-fold:
1. Was this change intentional?
2. If it was, what would be the right way to approach a declarative API like this now?

With so much of Ember's power coming from the template, it seems like moving in the wrong direction to break some of the behavior that allowed for declarative APIs like the one in that addon.

**Comment by rondale-sc** [comment]
I've run into this myself.  Very eager to hear the answers to these questions.

**Comment by rwjblue** [comment]
@alexlafroscia - I picked this up to poke at it, but cannot replicate a failure (outside of https://github.com/emberjs/ember.js/issues/16311).  I submitted https://github.com/alexlafroscia/ember-steps/pull/98 (with the upgrade to 3.1.0-beta.5) to check ember-steps' CI too (you can see the [passing CI run here](https://travis-ci.org/alexlafroscia/ember-steps/jobs/362167636)).

![help me help you 🙏](https://media.giphy.com/media/uRb2p09vY8lEs/giphy.gif)

**Comment by alexlafroscia** [comment]
Could the issue be related to a conversion of the addon to TypeScript (and thus, a move to ES6 classes)? It's actually my TypeScript re-write branch that's having this problem...

This build should show the issue correctly (although it's still running at the time of writing): https://travis-ci.org/alexlafroscia/ember-steps/jobs/362233312

Is ES6 class usage at a place right now where if that is broken, it's not a concern?

**Comment by rwjblue** [comment]
@alexlafroscia - https://github.com/emberjs/ember.js/pull/16466 may be related?

**Comment by rwjblue** [comment]
@alexlafroscia - I believe that the issue you are seeing is that you are attempting to add a computed property per-instance _without_ `Ember.defineProperty`. As of Ember 3.1 adding a computed property to an instance (e.g. without `Ember.Object.extend()` usage) will not setup a native ES5 getter, and it will not be properly notified of changes. See https://github.com/emberjs/ember.js/issues/16427 for some additional background on that...

**Comment by alexlafroscia** [comment]
Hmm, interesting. Is there a different way that an ES6 class should set computed properties rather than what I'm doing there, which is essentially

```
class Foo extends Ember.Object {
  someComputed = computed('dependent', function() {
     ...
  });
```

**Comment by alexlafroscia** [comment]
It looks like using `computed` from `@ember-decorators/object` will work instead. Thanks for helping me dig into this, @rwjblue!
