### ISSUE TITLE
[BUG][CANARY] Mixins throwing  `object is not extensible`

### ISSUE THREAD

**Issue by kiwiupover** [emberjs/ember.js#16479]
Both addon are throwing `TypeError: Cannot add property undefined, object is not extensible`
https://github.com/offirgolan/ember-cp-validations/blob/master/addon/validations/factory.js#L146
https://github.com/offirgolan/ember-parachute/blob/master/addon/query-params.js#L293

`ValidationsMixin[Ember.NAME_KEY] = 'Validations';`
Ember.NAME_KEY is `undefined`
ValidationsMixin seems to be immutable 

Addons using `Ember.NAME_KEY`
https://emberobserver.com/code-search?codeQuery=NAME_KEY&sort=score&sortAscending=false

**Comment by rwjblue** [comment]
Steps to fix:

1. Add `this[NAME_KEY] = null;` to the [Mixin constructor](https://github.com/emberjs/ember.js/blob/981d8744156065cdb005771292a9cf6f0a5ea9a2/packages/ember-metal/lib/mixin.js#L445) before calling `Object.seal(this)`.
2. Add a deprecation when accessing `Ember.NAME_KEY` (suggesting the usage of `toString` directly).
3. Profit? 💸
