### ISSUE TITLE
[Bug][Canary] Ember.NAME_KEY is undefined

### ISSUE THREAD

**Issue by kiwiupover** [emberjs/ember.js#16480]
`Ember.NAME_KEY` is undefined if pulled from `Ember` namespace

When called in an `init` `Ember.NAME_KEY`  will return the right thing.

https://github.com/kiwiupover/ember-name-key/blob/master/app/controllers/application.js#L5-L8

http://ember-name-key.surge.sh/

**Comment by rwjblue** [comment]
@kiwiupover - Can you double check with current canary build (will need to grab the newest SHA tarball URL from emberjs.com/builds/#/canary)?

**Comment by kiwiupover** [comment]
Will do Sir.

**Comment by kiwiupover** [comment]
closed by https://github.com/emberjs/ember.js/commit/3eeee106d3c31f89b7b96f3f2f89c1967e10c2d4
