### ISSUE TITLE
queryParams are no longer documented in API docs

### ISSUE THREAD

**Issue by toddjordan** [emberjs/ember.js#16481]
in 3.0, queryParams is no longer documented in Controller.

This is because that code was refactored out of mixins/controller and into: `packages/ember-routing/lib/ext/controller.js` (https://github.com/emberjs/ember.js/blob/ab975417c47d49cd183b1e0470aea3c77c162682/packages/ember-routing/lib/ext/controller.js)

To fix we just need to tie it back by adding `@for Ember.ControllerMixin` in the existing documentation for the queryParam property there and it should flow up to be viewable in controller.

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/16487
