### ISSUE TITLE
[3.1.0] getOwner returning false in ObjectProxy.init

### ISSUE THREAD

**Issue by lucacorti** [emberjs/ember.js#16484]
`getOwner(this)` in `ObjectProxy.init` was returning the container in 3.0. Since 3.1 it returns false. 
 `this` looks quite different:

3.0:
<img width="381" alt="screen shot 2018-04-11 at 16 33 57" src="https://user-images.githubusercontent.com/1076999/38630548-89684940-3db7-11e8-99e2-8c0a0e1a1e39.png">

3.1:
<img width="455" alt="screen shot 2018-04-11 at 16 41 28" src="https://user-images.githubusercontent.com/1076999/38630549-8981c6b8-3db7-11e8-9886-44d45a91fc2d.png">

**Comment by rwjblue** [comment]
@lucacorti - Thanks for reporting! Definitely a bug...

**Comment by rwjblue** [comment]
This is related to https://github.com/emberjs/ember.js/issues/16148...

**Comment by rwjblue** [comment]
@lucacorti - Can you share a code snippet showing how the object proxy is being created?

**Comment by gmurphey** [comment]
@rwjblue the issue was originally created for this service:

https://github.com/gmurphey/ember-config-service/blob/master/addon/services/config.js

**Comment by rwjblue** [comment]
Will be fixed by https://github.com/emberjs/ember.js/pull/16493...
