### ISSUE TITLE
Dynamically created computed property seems to be broken in 3.1

### ISSUE THREAD

**Issue by olivierchatry** [emberjs/ember.js#16504]
Hello !

I'm using dynamically generated computed property, and it seems to not work anymore in 3.1.

Here is a code sample of what I'm doing :

```js
	setupNormalUser(currentUser) {
		Ember.set(this, "projects",
			Ember.computed("currentUser.projects.[]", "demoAccounts.@each.projects",
				() => {
					let projects = [].concat(currentUser.get("projects"))
					const demoAccounts = this.get("demoAccounts.content")
					if (Ember.isArray(demoAccounts)) {
						demoAccounts.forEach(
							(demoAccount) => projects = projects.concat(demoAccount.get("projects"))
						)
					}
					return projects
				}
			)
		)
		Ember.set(this, "accounts",
			Ember.computed("currentUser.accounts.[]", "projects.[]", function() {
				const projects = currentUser.get("projects") || [];
				return projects
					.filter(project=>!Ember.isNone(project))
					.map(project=>project.get("account.content"))
					.concat( currentUser.get("accounts"))
					.filter(a => !Ember.isNone(a)).uniq()
			})
		)
		Ember.set(this, "assetLibraries",
			Ember.computed("accounts.@each.assetLibraries", function() {
				return currentUser.get("accounts").map(
					(account) => account.get("assetLibraries").toArray()
				).reduce(
					(prev, cur) => prev.concat(cur), []
				).uniq()
			})
		)
	},
	setupSuperAdmin(currentUser) {
		this.set("projects", this.get("store").findAll("project"))
		this.set("accounts", this.get("store").findAll("account"))
		this.set("assetLibraries", this.get("store").findAll("assetLibrary"))
	},
```

**Comment by rwjblue** [comment]
Can you provide a more simplified demo/example? What does “not working anymore” mean (not recomputing, throwing an error, etc)? 

Ultimately I believe this is essentially the same as the issue reported in https://github.com/emberjs/ember.js/issues/16427.  This pattern was not public API and only happened to work due to a refactor late in the 1.x cycle. Computed properties should be “design time” and not defined at runtime. The way to make this usage scenario to work would be to define a CP on an instance of an object through `Ember.defineProperty` (instead of `Ember.set` in your example).

**Comment by rwjblue** [comment]
I'm fairly sure my prior comment is correct, and this is a duplicate of https://github.com/emberjs/ember.js/issues/16427. Essentially doing this:

```js
Ember.set(someObject, Ember.computed('depKey', function() { /* some calculation */ }));
```

Is not a thing we actually support. The quick solution in your snippet above would be to move that `Ember.set` to `Ember.defineProperty` (which works all the way back to Ember 1.x).

**Comment by olivierchatry** [comment]
I will test ASAP and get back to you, thanks a lot for the support :).

**Comment by olivierchatry** [comment]
Works like a charm. Thanks a  lot. Should I close it ?

**Comment by olivierchatry** [comment]
Closing it, as it was a miss-use of the system.
