### ISSUE TITLE
expandProperties is documented in the wrong module

### ISSUE THREAD

**Issue by toddjordan** [emberjs/ember.js#16500]
![image](https://user-images.githubusercontent.com/3609063/38646063-7ce4e866-3db4-11e8-9c25-23a15880dc5f.png)

it should be under `@ember/object`, not `@ember/object/computed`.
it should fall under the sub-heading `@ember/object/computed`  on the `@ember/object` page.

To fix, go to https://github.com/emberjs/ember.js/blob/v3.1.0/packages/ember-metal/lib/expand_properties.js#L9

and set the `@for` to `@ember/object/computed`
and the `@module` to `@ember/object`

**Comment by rwjblue** [comment]
fixed by https://github.com/emberjs/ember.js/pull/16502
