### ISSUE TITLE
How to properly use InjectedProperties in ember 3.1

### ISSUE THREAD

**Issue by toranb** [emberjs/ember.js#16519]
I recently upgraded an ember addon from 3.0 => 3.1 and got this error regarding a service injection

```InjectedProperties should be defined with the inject computed property macros.```

It's worth mentioning that this project supports both es2015 class syntax and ember object and it was working fine as of ember 3. This exception only throws for the es2015 class tests and almost certainly because of how I used `inject`

```js
import { inject } from '@ember/service';

export default function wrapEs2015Class(stateToComputed, dispatchToActions, WrappedComponent) {

  WrappedComponent.prototype.redux = inject('redux');

  return class Connect extends WrappedComponent {
    constructor() {
      super(...arguments);
    }
// ...
```

https://github.com/ember-redux/ember-redux/blob/master/addon/es2015-class.js#L6

![error](https://user-images.githubusercontent.com/147411/38768682-2128e5da-3fbd-11e8-9f98-ffef828404c5.png)

Any pointers on a path forward here would be greatly appreciated. Thank you in advance :)

**Comment by toranb** [comment]
Update: it looks like the root cause here is that inside the `descriptorFor` we opt into the ES5GETTERS conditional first now in ember 3.1. If I set this to false the error is not thrown so I'm curious if this is just an edge case that we should support w/ ES5GETTERS that hasn't been caught yet.

![es5getters](https://user-images.githubusercontent.com/147411/38768802-ad837058-3fbe-11e8-9d5f-ffc99f1014d4.png)

The magic here is that `var possibleDesc = obj[keyName];` returns the injected service w/out error

**Comment by rwjblue** [comment]
This is roughly the same issue as described in https://github.com/emberjs/ember.js/issues/16504 and https://github.com/emberjs/ember.js/issues/16427.

**Comment by rwjblue** [comment]
Change this:

```
WrappedComponent.prototype.redux = inject('redux');
```

Into this:

```js
Ember.defineProperty(WrappedComponent.prototype, ‘redux’, inject('redux'));
```

Should fix the issue. The basic gist here is that setting properties on the prototype (or instance) does _not_ properly define a computed property, you must go through `Ember.defineProperty` (which `Ember.Object.extend(...)` does for you normally). The change I suggest above will work backwards and forwards compatibly...

I do consider it a general regression though (as mentioned in #16427). This specific use case is likely to be “fixed” with a private API deprecation in a patch release.

**Comment by toranb** [comment]
@rwjblue perfect -thanks for the quick reply dude! I've verified this works and I'm planning to ship a patch of ember redux this morning yet to solve it :)
