### ISSUE TITLE
[regression] Closure component dot rule is unenforced

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#16510]
Closure component invocations follow a "dot rule". The can be invoked either with the `{{component}}` helper, or with a path containing a `.`.

For example these are **valid** invocations:

```hbs
{{#some-component as |wrappingHash|}}
  {{wrappingHash.someComponent}}
{{/some-component}}

{{this.somePassedInComponent}}

{{component somePassedInComponent}}
```

For another example these are **invalid** invocations (should not invoke the component, usually they show `[object Object]`):

```hbs
{{#some-component as |closureComponent|}}
  {{closureComponent}}
{{/some-component}}

{{somePassedInComponent}}
```

As of Ember 2.15 invocations of block param closure components without a `.` has been permitted. A reproduction: https://ember-twiddle.com/92561d3be8128785682b50666e05c25f?fileTreeShown=false&openFiles=templates.application.hbs%2C

/cc @iezer @rwjblue

**Comment by chancancode** [comment]
dot rule was removed in #17135
