### ISSUE TITLE
[RFC 322] Ember.copy and Ember.Copyable Deprecation

### ISSUE THREAD

**Issue by lupestro** [emberjs/ember.js#16517]
This is a meta-issue to track the implementation of [https://github.com/emberjs/rfcs/pull/322]().

**ember-copy (addon)**
- [x] implement copy method and Copyable mix-in

**data**
- [x] remove use of copy() and Copyable from code and tests

**ember.js**
- [x]  adjust copy() to always copy arrays itself rather than delegating on Copyable
- [x]  remove use of copy() and Copyable from code and tests
- [x]  deprecate copy() and NativeArray.copy()
- [x]  deprecate Copyable() mixin use in object.extend() if feasible

**deprecation-app**
- [ ] document deprecation, Object.assign for shallow copies, and availability of add-in

**ember-cli-eslint**
- [x] ~~deprecation rules for copy() and Copyable~~ [ after discussion, decided not to do it ]

**ember-api**
- [ ] verify copy() and Copyable documentation reflect deprecation

I will link the requisite PRs here as they are opened.

**Comment by rwjblue** [comment]
Wheeeee! Thank you @lupestro!
