### ISSUE TITLE
Ember Route's model method swallows errors

### ISSUE THREAD

**Issue by kdamball** [emberjs/ember.js#16534]
Inside a route file, e.g: `routes/dog.js`

lets say it's for `/dogs/:dog_id`, if nothing is found - it should redirect you `/dogs`
```javascript
export default Ember.Route.extend({
  model(params){
    this.store.findRecord('dog', params.dogId).then(data => {
      if (!data){
        transition.abort();   // transition is undefined! It should throw an error - instead, nothing in the console is shown
        this.transitionTo('/dogs/index');
      }
      return data;
    });
  }
})
```

Basically, a simple `ReferenceError` isn't thrown in the console. This can lead to lots of time wasted on a simple typo.

**Comment by pixelhandler** [comment]
@kdamball the example code does not appear to be an bug in Ember.js. The function signature of the model hook is `model (params, transition)` which just wasn't referenced in the code example. Not exactly sure how there was no error (trying to invoke `abort` from `undefined` ).

Lately I've been using ember-cli-typescript which improves static type analysis of my application code and helps my editor lookup and autocomplete as well. In my opinion adding TypeScript improves developers ability to catch these types of errors. Also, do you think eslint would call out that syntax issue?

I'll close this for now.
