### ISSUE TITLE
[3.1.0] Cannot create new tag for model after its been destroyed error during test teardown

### ISSUE THREAD

**Issue by Dhaulagiri** [emberjs/ember.js#16541]
Beginning in Ember 3.1 we have a test that is failing on teardown with [this error](https://github.com/emberjs/ember.js/blob/d113c13a0f52edbd461dfa9784c21531b0cea028/packages/ember-metal/lib/meta.js#L287):

> Assertion Failed: Cannot create a new tag for `<model-b::ember2555:1>` after it has been destroyed.

Working up a reproduction is going to be hard so I'll do my best to describe the scenario:

There is a model A that has a `belongsTo` relationship with a model B.  

Model A also has `readOnly` properties that depend on properties in model B a la `isTrue: readOnly('modelB.someProp')`.  Where `someProp` on model B is an `equal` computed.

The above assertion seems to be getting triggered during teardown as `ember-metal` tries to `unwatch` each of the computed properties that depend on some property on the related model. As far as I can tell this _does not_ occur while running the app.

I can make the error go away by either removing these computed properties (not really a solution) or setting the relationship to `async: false`.

I'm not sure if this is a regression per se, but I'm also not really sure how to best dig in and figure out _how_ or _where_ to fix this.

**Comment by rwjblue** [comment]
I think it would be useful to see more of the stack (there are a couple of different pathways that end up calling `meta.writableTag` and we need to know which to dig into...).

The thing that seems somewhat odd in this case (and what we need to figure out) is _why_ unwatching would cause `meta.writeableTag` to be called at all. Personally, I would only expect it to be called when a given object is getting rendered in a template...

**Comment by Dhaulagiri** [comment]
@rwjblue here is the full stack

```
Error: Assertion Failed: Cannot create a new tag for `<model-b::ember2555:1>` after it has been destroyed.
    at new EmberError (http://localhost:7357/assets/vendor.js:35404:25)
    at Object.assert (http://localhost:7357/assets/vendor.js:35654:15)
    at Meta.writableTag (http://localhost:7357/assets/vendor.js:47269:54)
    at tagFor (http://localhost:7357/assets/vendor.js:45456:22)
    at contentFor (http://localhost:7357/assets/vendor.js:58496:60)
    at Proxy.unknownProperty (http://localhost:7357/assets/vendor.js:58540:21)
    at Object.get (http://localhost:7357/assets/vendor.js:60891:50)
    at removeListener (http://localhost:7357/assets/vendor.js:44554:42)
    at removeObserver (http://localhost:7357/assets/vendor.js:45824:5)
    at Proxy.didUnwatchProperty (http://localhost:7357/assets/vendor.js:58537:38)
```

**Comment by rwjblue** [comment]
Hmm, I think that should have been addressed by https://github.com/emberjs/ember.js/pull/16404 which I missed when doing 3.1.0 but @rondale-sc backported for us in https://github.com/emberjs/ember.js/pull/16496. Can you test the latest `release` build and see if this is already fixed there?

**Comment by Dhaulagiri** [comment]
I have a feeling I may have trolled us with this issue so for that I apologize.  I could have sworn I _did_ try the latest release build this morning and still saw the error.  However, in trying to reproduce this against ember master locally I couldn't reproduce it and now that I switch back to the latest release once again I also can't reproduce it.  I don't even know which way is up anymore! 😵 

Switching back to 3.1.0 release version _does_ exhibit the error so that I think we can consider this resolved and I'll await a new release.

**Comment by BryanCrotaz** [comment]
I'm seeing this in ember 3.8.3

**Comment by BryanCrotaz** [comment]
Seems to work every time with 

```
    unknownProperty(key) {
      if (this.isDestroying || this.isDestroyed) {
        return;
      }
      let content = this.content;
      if (content) {
        return get(content, key);
      }
    },
```

**Comment by AlexMayants** [comment]
We have encountered the same error as @BryanCrotaz in 3.8.3. I used a modified version of his solution:

```
    unknownProperty(key) {
      if (this.isDestroying || this.isDestroyed) {
        return;
      }

      let content = this.content;

      if (!content || content.isDestroying || content.isDestroyed) {
        return;
      }

      return this._super(key);
    },
```

It seems to work, but this should probably be fixed within the Ember core.

**Comment by Kilowhisky** [comment]
Just encountered this again on ember 3.19.0. @AlexMayants and @BryanCrotaz fixes appear to have worked. 

DEBUG: -------------------------------
DEBUG: Ember             : 3.19.0
DEBUG: Ember Data        : 3.19.0
DEBUG: jQuery            : 3.5.1
DEBUG: Ember Simple Auth : 3.0.0
DEBUG: Model Fragments   : 5.0.0-beta.0
DEBUG: -------------------------------

**Comment by nag5000** [comment]
octane version, otherwise autotracking is broken

```diff
    unknownProperty(key) {
      if (this.isDestroying || this.isDestroyed) {
        return;
      }

      let content = this.content;

-      if (!content || content.isDestroying || content.isDestroyed) {
+      if (content && (content.isDestroying || content.isDestroyed)) {
        return;
      }

      return this._super(key);
    },
```
