### ISSUE TITLE
Brace expansion should allow whitespace

### ISSUE THREAD

**Issue by ahopkins** [emberjs/ember.js#16585]
Consider this example:

```
someWeatherComputedProperty: computed(
    'someObj.{ \
      day1.currentforecast, \
      day2.currentforecast, \
      day3.currentforecast, \
      day4.currentforecast, \
      day5.currentforecast, \
      day6.currentforecast, \
      day7.currentforecast}',
    'otherStuff',
    'moreOtherStuff', function() {
```

versus

```
someWeatherComputedProperty: computed('someObj{day1.currentforecast,day2.currentforecast,day3.currentforecast,day4.currentforecast,day5.currentforecast,day6.currentforecast,day7.currentforecast}', 'otherStuff', 'moreOtherStuff', function() {
```

Which one is easier to read?

Even the Error message itself makes the case:

```
Assertion Failed: Brace expanded properties cannot contain spaces, e.g. "user.{firstName, lastName}" should be "user.{firstName,lastName}"
```

I would suggest that `user.{firstName, lastName}` is simpler and more readable than `user.{firstName,lastName}`.

Am I missing something? Is there a legitimate reason that whitespace cannot be stripped out?

**Comment by Serabe** [comment]
This is an intended behaviour. As such, changing it would require to follow the RFC process as describe in the [CONTRIBUTING file](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature)

Thank you!

**Comment by ahopkins** [comment]
I understand that it is intended from the error message. I am more interested in knowing the *why* this is intended. Allowing whitespace allows for cleaner code.

**Comment by rwjblue** [comment]
Basically because we have to parse it at runtime, and dealing with fewer exception led to faster/easier code. Feel free to dig through the last couple rounds of refactoring the underlying code: https://github.com/emberjs/ember.js/pull/13231 and https://github.com/emberjs/ember.js/pull/15219.

Also, FWIW, your expansion can be simplified to:

```
computed('someObj.{day1,day2,day3,day4,day5,day6,day7}. currentforecast', function() {})
```

**Comment by ahopkins** [comment]
Thanks for the links and for the heads up. 👍
