### ISSUE TITLE
Misleading error with an invalid import for computed

### ISSUE THREAD

**Issue by panthony** [emberjs/ember.js#16588]
Hi !

During development I stumbled upon an issue that took me quite some time to pinpoint.

The error message was: `Uncaught Error: infinite rendering invalidation detected`.

The actual error was that I had the following bad import:

```js
// should have been `@ember/object`
import { computed } from '@ember/computed';
```

Not sure if it was worth an issue, feel free to close if not.

But if there is an easy win that gives the developer a more helpful (= not misleading) error message that's always something !

**Comment by Serabe** [comment]
Can you provide a quick repo reproduction? I'm wondering why it is not complaining about computed not being a function.

**Comment by panthony** [comment]
@Serabe I can't reproduce on a new app (either 3.0 or 3.1), I have the expected:

`Could not find module @ember/computed imported from ...`

But I do have this "infinite rendering invalidation" with this import on my real app instead of the 'could not found module', weird.

But since I cannot give you a reproduction case I shall close this.
