### ISSUE TITLE
Improve documentation of unless template helper

### ISSUE THREAD

**Issue by jenweber** [emberjs/ember.js#16592]
Per discussion on the Learning Team channel, “unless” is a bit confusing, both for native English speakers and multilingual devs. We can improve the documentation to help.

Two improvements are:
- put a description of the logic in the docs (suggested language is “if not”)
- give a block form example too

[current docs](https://emberjs.com/api/ember/3.1/classes/Ember.Templates.helpers/methods/unless?anchor=unless) and [file to edit](https://github.com/emberjs/ember.js/blob/470dddb9bbea32f0bf71219740b22c8dc8ecf68d/packages/ember-glimmer/lib/helpers/if-unless.ts)

**Comment by axyxnz** [comment]
I will take a look at this issue.
