### ISSUE TITLE
mouseEnter/Leave event delegation broken w/o jQuery

### ISSUE THREAD

**Issue by simonihmig** [emberjs/ember.js#16591]
For components that have a `mouseEnter()` (and/or `mouseLeave()`) event handler, these are not called anymore when running without jQuery. 

I think this is because those events don't bubble, so event delegation based on the root element, which is what the  `EventDispatcher` is doing, does not work. Those events get only triggered for the element having the listener (the app's `rootElement` in this case). See https://developer.mozilla.org/en-US/docs/Web/Events/mouseenter

A possible workaround would be to use `mouseover` under the hood, to enable event delegation, and to make sure it behaves the same as the `mouseEnter` (i.e. doesn't trigger again for child elements). jQuery seems to do the same, that's why it works in jQuery mode: https://github.com/jquery/jquery/blob/899c56f6ada26821e8af12d9f35fa039100e838e/src/event.js#L666-L700

I could work on a PR, if we agree this ^ is the way forward!?

**Comment by rwjblue** [comment]
I'm somewhat hesitant to bake this in without other changes to event dispatching to make it more "pay as you go". I believe that _most_ applications don't use `mouseenter` / `mouseleave` / `mouseover` and always listening to them has non-trivial cost.

A couple "simple" (I know, not always simple) work arounds for folks suffering from this _right now_:

* Refactor your component to explicitly add an event listener in `didInsertElement`:

```js
export default Component.extend({
  didInsertElement() {
    let handler = this._mouseenter = Ember.run.bind(this, this.mouseEnter);
    this.element.addEventListener('mouseenter', handler);
  },
  willDestroyElement() {
    this.element.removeEventListener('mouseenter', this._mouseenter);
  }
});
```

* Refactor your template to use closure actions:

```hbs
<div onmouseenter={{action 'mouseEntered'}}>Hover over me!</div>
```

**Comment by rwjblue** [comment]
> Hm, in what way would that get baked in? If we can change the implementation to be more "pay as you go" without changing the public API, we can do this any time later.

I’m sold. :smiley: Would love a PR...

**Comment by rwjblue** [comment]
Would you mind opening a new issue to track that?
