### ISSUE TITLE
didUpdateAttrs called after setting internal properties on second route transition

### ISSUE THREAD

**Issue by snewcomer** [emberjs/ember.js#16601]
Using Ember 3.1.1 - When first rendering a route + child components, then clicking a button that calls `_onShowMore`, it does not call `didUpdateAttrs` (does call `didUpdate`).  However, after transitioning to another route (component is not torn down), calling `_onShowMore` via a button click again DOES call `didUpdateAttrs`.  

I'm not too happy with this `push based` intialization/update for this component so am looking to refactor.  But...is this a bug?  I can put up an example repo if so.

```
  // showFullText && moreShown are internal properties on this component

  didUpdateAttrs() {
    setProperties(this, {
      showFullText: false,
      moreShown: false
    });
  },

  // called from action in template
  _onShowMore() {
    setProperties(this, {
      showFullText: true,
      moreShown: true
    });
  },
```

**Comment by snewcomer** [comment]
I'm going to close this for now and reopen if I find something more.  There may be something else that is causing problems (htmlSafe + clamping some innerHTML.

**Comment by sunwrobert** [comment]
Hey @snewcomer , did you ever fix this issue? It's been popping up for our application as well.
