### ISSUE TITLE
Ember.computed functions that throw exception take down the ember engine

### ISSUE THREAD

**Issue by davelindquist-egistix** [emberjs/ember.js#16606]
When using Ember.computed (or any computed that accepts a function), if your method throws an exception, it will either:
* Take down the entire ember engine (with many 'glimmer' errors)
* Or (worse yet) SILENTLY CORRUPT the dependency tree so that things half stop working in incomprehensible ways.

Basically, the problem is (Ember 2.18, inside ```ember-metal```):
```js
  // called whenever a property has just changed to update dependent keys
  function dependentKeysDidChange(obj, depKey, meta$$1) {
    if (meta$$1.isSourceDestroying() || !meta$$1.hasDeps(depKey)) {
      return;
    }
    var seen = DID_SEEN;
    var top = !seen;

    if (top) {
      seen = DID_SEEN = {};
    }

    iterDeps(propertyDidChange, obj, depKey, seen, meta$$1);

    if (top) {
      DID_SEEN = null;
    }
  }
```

If anything blows up inside a computed property evaluation, it ends up blowing up inside ```iterDeps```, which means that ```iterDeps``` doesn't complete -- and the DID_SEEN doesn't get erased.

This seems excessively severe (and in one case, resulted in more than a day of tracking down a subtle functionality stop) -- instead, it seems like the best idea would be to make sure that whenever we evaluate a ```computed``` function, it is ```try```/```catch```ed (then the error can be logged or something less severe than total failure).

I've created a mitigation for this in our application by simply 'overriding' computed in our initializer:

```js
import EmberObject, { computed } from '@ember/object';
import { assign } from '@ember/polyfills';
import { typeOf } from '@ember/utils';

export function initialize() {
	// "Override" Ember's computed to do a try/catch -- this prevents complete blowup/shutdown when something goes wrong in a computed property.
	const oldComputed = computed;
	let newComputed = function() {
		let newArgs = Array.prototype.slice.call(arguments);
		const funcPos = newArgs.length-1;
		if(funcPos >= 0) {
			const oldFunc = newArgs[funcPos];
			if(typeOf(oldFunc) === 'function') {
				newArgs[funcPos] = function() {
					try {
						return oldFunc.apply(this,arguments);
					} catch(ex) {
						// do some form of logging here
					}
				};
			} else if('get' in oldFunc) {
				const prevFunc = oldFunc.get;
				oldFunc.get = function() {
					try {
						return prevFunc.apply(this,arguments);
					} catch(ex) {
						// do some form of logging here
					}
				};
			}
		}
		return oldComputed(...newArgs);
	};
	assign(newComputed,oldComputed);
	computed = newComputed;
}
```

I will be the first to admit that this is a bit of a hack, but it makes a major difference in development, and prevents costly "where the heck did something go wrong" sessions.

Any chance of having some sort of try/catch done around ```computed```s in a future Ember release?

**Comment by martletandco** [comment]
I found this issue while looking for a way to use `assert` from `@ember/debug` in a computed property without getting a double render, however because it throws when the condition isn't meet the same issue is caused. I was expecting `assert` to play nice with computed properties

**Comment by rwjblue** [comment]
I am definitely sensitive to this issue, can't believe I didn't comment on it when it was originally raised. Sorry about that @davelindquist-egistix. 😞 

There are two parts to the original report:

* a CP throwing resulting in near infinite glimmer-vm errors -- this should be fixed (we have made many changes to try and ensure that this can't happen any more)
* a CP throwing resulting in a corrupted `DID_SEEN` -- I think we should absolutely fix this!

A naive, but likely "good enough" solution would be to wrap the reset of `DID_SEEN` in a `try`/`finally` to ensure its always reset properly. A great place to start is with a failing test case PR, then we can attempt the fix I mentioned above to see if it resolves things...

**Comment by locks** [comment]
Closing as stale. The framework has since moved to tracked properties.
