### ISSUE TITLE
Version number discrepancy

### ISSUE THREAD

**Issue by plebeian-org** [emberjs/ember.js#16614]
This may be as-planned, but I'm seeing this and scratching head.

Installed ember-cli globally:
$ npm i -g ember-cli 
$ ember -v 
ember-cli: 3.1.4
node: 8.11.1
os: darwin x64

new ember project package.json shows:
 "ember-cli": "~3.1.3",
 "ember-data": "~3.1.0",
"ember-source": "~3.1.0",

DevTools Debug output on fresh $ ember serve 
DEBUG: -------------------------------
DEBUG: Ember : 3.1.1 
DEBUG: Ember Data : 3.1.1
DEBUG: jQuery : 3.3.1
DEBUG: -------------------------------

**Comment by Serabe** [comment]
Yep. This is right. More about the [tilde ranges in semver](https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1).

Thank you!

**Comment by rwjblue** [comment]
Also, just wanted to mention that your projects local Ember-cli dependency will **always** be used over your globally installed version. This functionality is what allows you to have multiple projects with various different ember-cli versions without having an issue...

**Comment by plebeian-org** [comment]
Excellent, thanks folks!  and yes, thanks @rwjblue for the info. I suspected as much but wasn't sure. Cheers!
