### ISSUE TITLE
link-to: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#16623]
We've been seeing errors on Sentry lately (with Ember v3.0.x and v3.1.2) that might indicate a bug in the `link-to` component. I have not been able to reproduce this yet, but here is what I've found out so far:

```
TypeError: Cannot read property 'length' of undefined
  at call(ember-glimmer.js:2497:1)   <- `_modelsAreLoaded` CP trying to lookup `models.length`
  at get(ember-metal.js:3440:1)
  at get(ember-metal.js:2868:1)
  at call(ember-glimmer.js:2488:1)   <- `loading` CP
  at get(ember-metal.js:3440:1)
  at get(ember-metal.js:2868:1)
  at call(ember-glimmer.js:2478:1)   <- `href` CP
  at get(ember-metal.js:3440:1)
  at get(ember-metal.js:2868:1)
  at compute(ember-glimmer.js:257:1)   <- most likely the code handling the `href` attribute binding
```

https://github.com/emberjs/ember.js/blob/v3.1.2/packages/ember-glimmer/lib/components/link-to.ts#L818-L823 indicates that `models` should not be `undefined` after the `didReceiveAttrs` hook has finished, and yet `models` is `undefined` according to the error message. It appears like on some systems the `href` CP might be calculated before the `didReceiveAttrs` hook had the chance to run. 🤔

**Comment by Turbo87** [comment]
I just noticed that it appears to be an issue with a very specific Chrome version on Android (`Chrome Mobile 50.0.2661`). It also seems to happen on `Opera Mobile 37.0.2192`, but I'm assuming that's likely due to the same underlying engine.

**Comment by Turbo87** [comment]
some of the UA strings in case it helps:
- Mozilla/5.0 (Linux; Android 5.1; HUAWEI CUN-L01 Build/HUAWEICUN-L01) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.89 Mobile Safari/537.36
- Mozilla/5.0 (Linux; Android 5.1.1; Redmi 3 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.89 Mobile Safari/537.36
- Mozilla/5.0 (Linux; Android 6.0.1; D6633 Build/23.5.A.1.291) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.89 Mobile Safari/537.36
- Mozilla/5.0 (Linux; Android 5.1; LG-X220 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.89 Mobile Safari/537.36

**Comment by rwjblue** [comment]
@Turbo87 is this still an issue in 3.4 / 3.6?

**Comment by Turbo87** [comment]
@rwjblue I am not working on that project anymore. We had ported it to Ember 3.4 shortly before I left the project, but I don't recall if it helped with this. Unfortunately we were not able to come up with a repro 😞

**Comment by rwjblue** [comment]
Hmm. Ok. I guess I’ll close this for now then, if someone else is affected and can help with a repro I’d definitely be happy to reopen and help dig in...
