### ISSUE TITLE
regression 3.0: ArrayProxy#pushObjects doesn't accept ArrayProxy

### ISSUE THREAD

**Issue by hjdivad** [emberjs/ember.js#16621]
#16131 cleaned up a lot of `Enumerable` and `Array` mixin code.

However it also changed the assertion in `pushObjects` from [checking for Enumerable or Array](https://github.com/emberjs/ember.js/blob/d9ed94e5989ee641b723e9d1a01a3814053a6540/packages/ember-runtime/lib/mixins/mutable_array.js#L190) to [only checking Array](https://github.com/emberjs/ember.js/blob/db1717b34dc92a266ae54c687bc350b7dcb07de2/packages/ember-runtime/lib/mixins/mutable_array.js#L189)

This assertion now throws when calling `hasMany.pushObjects(otherHasManyOrRecordArray)` even though ember-data's `ManyArray` can accept these objects.

After going over this with @rwjblue I think the path forward is

- [ ] Drop the assertion in `pushObjects` entirely
- [ ] docs: Implementations have to assert their arguments in `replace` (which is the method implementations of `MutableArray` are expected to implement)

`NativeArray` already does assert in `replace` and `ArrayProxy` doesn't need to as it delegates to `content`.

**Comment by rwjblue** [comment]
Thanks for writing this up, @hjdivad!  Agreed on the path forward...

@mmun - any objections?

**Comment by mmun** [comment]
@rwjblue Nope, this seems good.

It would also be useful if we could mark all the methods that are derived from `replace` as "final" so that people don't override them.

**Comment by runspired** [comment]
using `Ember.isArray` instead of `Array.isArray` is sufficient here.

**Comment by rwjblue** [comment]
@runspired - Yes, that would work right, but I believe that it muddies the waters a bit more than the proposed fix...

**Comment by devdemi** [comment]
I have same problem I can't use `pushObjects` passing RecordArray.

**Comment by nlfurniss** [comment]
@devdemi you can get around the issue currently by called `toArray` on the Enumerable you're trying to push in

```
myCollection.pushObjects(newElements.get('elements').toArray());
```
