### ISSUE TITLE
documentation link not working on ember test guide

### ISSUE THREAD

**Issue by abdullah2891** [emberjs/ember.js#16636]
Please go the link https://guides.emberjs.com/v3.1.0/testing/acceptance/

click on visit() helper . it is going no where

**Comment by Turbo87** [comment]
@abdullah2891 👋could you move this issue over to https://github.com/emberjs/guides? thanks :)

**Comment by locks** [comment]
Moved: https://github.com/ember-learn/guides-source/issues/56
