### ISSUE TITLE
Documentation missing for Component helper

### ISSUE THREAD

**Issue by GregoryAveryWeir** [emberjs/ember.js#16638]
In 3.1, the way the `{{component}}` helper works changed, resulting in the documentation apparently going away.

https://www.emberjs.com/api/ember/3.0/classes/Ember.Templates.helpers/methods/component?anchor=component does not exist in the 3.1 docs, despite being linked from https://guides.emberjs.com/v3.1.0/components/wrapping-content-in-a-component/#toc_sharing-component-data-with-its-wrapped-content

API docs should exist for contextual components and the guide above should link to them.

**Comment by rwjblue** [comment]
Fixed by #16766
