### ISSUE TITLE
Ember mapBy not persistent?

### ISSUE THREAD

**Issue by lifeart** [emberjs/ember.js#16631]
Gist to reproduce:

https://ember-twiddle.com/aa91a2dd3d5eda5133038e1b23d4b6ea?openFiles=templates.application.hbs%2C

Problem: mapBy on array not persistent 

Given: 
* array of emberObjects, named "items". (for example, user list)
* each item has "order" property
* sortedItems - computed property, depended on "array", "sortDirection"

How to reproduce:
1.) Open gist.
2.) By default no ordering for sortedItems
3.) Click on "Sort" button. Now "sortedItems" has logic to return sorted array, instead of original "list"
4.) Click on "Reset" button to get "original" sort (no sort).

--== ERROR ==--

Expected result: 
"sortedItems" ordering must equal "Items" ordering 

Output: 
sortedItems has prev sort result, even for "list".mapBy('order') - is should return 1,2,3 but returns 3,2,1

**Comment by lifeart** [comment]
mnemonic:
```
foo: [1,2,3]
bar: sortFunction(foo, sortKey)

sortFunction
   if sortKey
       result = (sortBy foo sortKey)
       log (mapBy result someUniqKey)
       return result;
   else 
       log (mapBy foo someUniqKey)
       return foo
```


* step 1
`sortKey = false`
`expectedConsoleResult: 1,2,3`
`realResult: 1,2,3`

* step 2
`sortKey = "baz"`
`expectedConsoleResult: 3,2,1`
`realResult: 3,2,1`

* step3
`sortKey = false`
`expectedConsoleResult: 1,2,3`
`realResult:` **3,2,1**

????? Why??

**Comment by lifeart** [comment]
One more twiddle: https://ember-twiddle.com/a1645a7d2c77d045ab622a16f72f38d5?openFiles=controllers.application.js%2C

@jenweber 

>  I swapped reverse for `return result.slice().reverse();` and the bug disappears

**Comment by jenweber** [comment]
Reverse is mutating the items array:

```

**Comment by lifeart** [comment]
@jenweber thank you! Going to close this issue
