### ISSUE TITLE
Confusing error message on invalid property name for routes

### ISSUE THREAD

**Issue by kennethlarsen** [emberjs/ember.js#16642]
I just helped out a colleague of mine who is new to Ember. He had an error stating `fullName must be a proper full name` which was pretty confusing. After some digging, it turned out he made a route like this: `this.route('reports/:report_id');` which triggered the error.

The error message was very confusing especially for him who was just starting out with Ember and could probably be improved.

I have made a reproduction in this repo: https://github.com/kennethlarsen/route-error-reproduction
(if you serve and visit `http://localhost:4200/reports/1` you should see the error)

**Comment by Serabe** [comment]
Thank you!

I submitted a PR, let me know what you think of the new wording.
