### ISSUE TITLE
Deprecate Ember.Map / Ember.MapWithDefault / Ember.OrderedSet

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#16678]
As agreed on in emberjs/rfcs#237, we need to deprecate creating the following objects:

* [`@ember/map`](https://github.com/emberjs/ember.js/blob/master/packages/%40ember/map/index.js) - Deprecation message should suggest to replace usage with native `Map` usage.
* [`@ember/map/with-default`](https://github.com/emberjs/ember.js/blob/master/packages/%40ember/map/with-default.js) - Deprecation should suggest to replace usage with native `Map` usage.
* [`@ember/ordered-set`](https://github.com/emberjs/ember.js/blob/master/packages/%40ember/map/lib/ordered-set.js) - Deprecation should mention adding `@ember/ordered-set` addon.
* Update the [conditional in @ember/ordered-set](https://github.com/emberjs/ember-ordered-set/blob/43ed8b5ce7b16e753503386ed9228b24b9d5cec3/addon/index.js#L6) to ensure it matches the version the removal lands in.

The deprecations should be `until: '3.5.0'`.

**Comment by sly7-7** [comment]
@rwjblue I'm currently trying to implement https://github.com/emberjs/ember.js/blob/master/packages/%40ember/map/with-default.js in my app, but I encounter this error during tests in CI: 
```
Constructor Map requires 'new' 
'TypeError: Constructor Map requires 'new'
 at MapWithDefault.Map (<anonymous>)\\n    at new MapWithDefault
```

My implementation is simply this one: 
```
export default class MapWithDefault extends Map {
  constructor(options) {
    super();
    this.defaultValue = options.defaultValue;
  }

  get(key) {
    let hasValue = this.has(key);
    if (hasValue) {
      return super.get(key);
    } else {
      let defaultValue = this.defaultValue(key);
      this.set(key, defaultValue);
      return defaultValue;
    }
  }
}
```

Is there something wrong with the compiler ? (I'm on "ember-cli-babel": "^7.1.3")

**Comment by rwjblue** [comment]
The basic issue is with transpilation. Its difficult to subclass native Map / Set / Error / Array objects and _also_ transpile away the `class` syntax (you will get the error message you reported when the transpiled `super()` call runs from the constructor).

I actually had handle this problem in ember-data when this issue was originally being worked on, my strategy there may be helpful to you.

* [Explanation of transpilation issues](https://github.com/emberjs/data/blob/36366ee779e27486a24635a02e609951429e4580/addon/-private/system/map.js#L30)
* Implementation:
  * https://github.com/emberjs/data/blob/v3.4.4/addon/-private/system/map.js
  * https://github.com/emberjs/data/blob/v3.4.4/addon/-private/system/map-with-default.js

**Comment by rwjblue** [comment]
I kinda doubt it for IE11, and all of the evergreen browsers can already handle it...
