### ISSUE TITLE
'Ember.onerror handler with invalid testing behavior detected' -- link doesn't contain a working solution

### ISSUE THREAD

**Issue by christophermlne** [emberjs/ember.js#16681]
I'm retrofitting an existing ember app with tests.

All tests are passing except I see this test at the end, warning that Ember's onerror handler is improperly configured.

But, the link (https://git.io/vbine) contains information that doesn't fully explain how to resolve the issue.

```
// app/app.js
import Ember from 'ember'; // is this still advised, now that ember is broken up into individial packages?

Ember.onerror = function(error) {
  if (Ember.testing) {  // this is always false, even in the test environment. IE., it doesn't work.
    throw error;
  }

  // ...desired development and production behaviors here...  <== ok, so now that we've nuked the default behaviour, how do we get it back?
};
```

**Comment by rwjblue** [comment]
> `if (Ember.testing) { // this is always false, even in the test environment. IE., it doesn't work.`

Can you share an example? What does your `Ember.onerror` actually look like?  In general, `Ember.testing` _is_ set to `true` while testing and back to `false` when testing is completed so I suspect some other culprit is at play...

**Comment by christophermlne** [comment]
Ember.onerror is undefined as is Ember.testing.

So you're right. Something else is definitely at play here.

I'm going to close this, and hunt down the real cause of my issue. Thanks for your help.
