### ISSUE TITLE
doc typo: Core Concepts

### ISSUE THREAD

**Issue by mikesamuel** [emberjs/ember.js#16682]
The `/` in line 5 of the code fragment below seems like a typo.

https://guides.emberjs.com/release/getting-started/core-concepts/ says

> /app/components/foo-did-render-example.js
> ```js
> import Component from '@ember/component';
> 
> export default Component.extend({
>   didRender() {
>     this._super(...arguments/);   // THIS LINE
>     console.log('I rendered!');
>   }
> });
> ```

**Comment by acorncom** [comment]
Thanks, that's been fixed. See the links above for the PRs if you're interested 😃
