### ISSUE TITLE
OrderedSet depreciation doesn't mention OrderedSet Addon 

### ISSUE THREAD

**Issue by bekzod** [emberjs/ember.js#16706]
here: https://github.com/emberjs/ember.js/blob/master/packages/@ember/map/lib/ordered-set.js#L17 it should mention https://github.com/emberjs/ember-ordered-set and not show depreciation when it is installed I think :)

**Comment by rwjblue** [comment]
Yep, totally agreed! https://github.com/emberjs/ember-ordered-set/issues/19 is related and tracking fixing the deprecation not showing when the addon is in use.
