### ISSUE TITLE
Angle Bracket Invocation allows implicit this with paths

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#16712]
Per the [angle bracket invocation RFC](https://github.com/emberjs/rfcs/blob/master/text/0311-angle-bracket-invocation.md#dynamic-invocations) using a path for invocation should not use “implicit this” fallback. 

Specifically, the following should _not_ render a curried component at `this.foo.bar`:

```hbs
<foo.bar />
```

**Comment by rwjblue** [comment]
The RFC's reasoning seemed to be about avoiding costly `this.div` type lookups in the non-path case (e.g. `<div></div>`), but it isn't completely clear to me that we also want to require `this.` for paths. 

Specifically, I think that it _may_ make more sense to limit the explicit `this.` requirement to cases that are not paths already (which satisfies the `<div></div>` case I mentioned above), and leave completely removing the implicit `this` to emberjs/rfcs#308.

@chancancode - What do you think?

**Comment by rwjblue** [comment]
Chatted with @chancancode, the RFC's language was intentional. https://github.com/glimmerjs/glimmer-vm/pull/827 should fix this for us once released.

**Comment by pixelhandler** [comment]
@rwjblue closing for now, that should have been released by now, correct?

> glimmerjs/glimmer-vm#827

**Comment by rwjblue** [comment]
Ya, perfect
