### ISSUE TITLE
How to fix EXTEND_PROTOTYPES deprecation ?

### ISSUE THREAD

**Issue by zorn-v** [emberjs/ember.js#16721]
Just updated deps and got
```
DEPRECATION: Accessing Ember.EXTEND_PROTOTYPES is deprecated, please migrate to Ember.ENV.EXTEND_PROTOTYPES [deprecation id: ember-env.old-extend-prototypes]
```
Nothing can find about it

I have standard config in `config/environment.js`
```javascript
   EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      },
      EXTEND_PROTOTYPES: {
        // Prevent Ember Data from overriding Date.parse.
        Date: false
      }
    },
```

**Comment by rwjblue** [comment]
Follow the deprecation stack trace, find out who/what is accessing `Ember.EXTEND_PROTOTYPES` and send out a PR...

The only case I have known about this was fixed in an update of `ember-inflector`, I’d check that first...

**Comment by zorn-v** [comment]
Stack trace
```
DEPRECATION: Accessing Ember.EXTEND_PROTOTYPES is deprecated, please migrate to Ember.ENV.EXTEND_PROTOTYPES [deprecation id: ember-env.old-extend-prototypes]
    registerHandler/HANDLERS[type]@http://localhost:4200/assets/vendor.js:25504:9
    raiseOnDeprecation@http://localhost:4200/assets/vendor.js:25306:9
    registerHandler/HANDLERS[type]@http://localhost:4200/assets/vendor.js:25504:9
    invoke@http://localhost:4200/assets/vendor.js:25516:9
    deprecate@http://localhost:4200/assets/vendor.js:25370:7
    get@http://localhost:4200/assets/vendor.js:56512:29
    @http://localhost:4200/assets/vendor.js:95573:1
    Module.prototype.exports@http://localhost:4200/assets/vendor.js:111:18
    Module.prototype._reify@http://localhost:4200/assets/vendor.js:148:48
    Module.prototype.reify@http://localhost:4200/assets/vendor.js:135:22
    Module.prototype.exports@http://localhost:4200/assets/vendor.js:109:5
    Module.prototype._reify@http://localhost:4200/assets/vendor.js:148:48
    Module.prototype.reify@http://localhost:4200/assets/vendor.js:135:22
    Module.prototype.exports@http://localhost:4200/assets/vendor.js:109:5
    Module.prototype._reify@http://localhost:4200/assets/vendor.js:148:48
    Module.prototype.reify@http://localhost:4200/assets/vendor.js:135:22
    Module.prototype.exports@http://localhost:4200/assets/vendor.js:109:5
    Module.prototype._reify@http://localhost:4200/assets/vendor.js:148:48
    Module.prototype.reify@http://localhost:4200/assets/vendor.js:135:22
    Module.prototype.exports@http://localhost:4200/assets/vendor.js:109:5
    requireModule@http://localhost:4200/assets/vendor.js:32:7
    resolveInitializer@http://localhost:4200/assets/vendor.js:96068:18
    registerInitializers@http://localhost:4200/assets/vendor.js:96081:23
    exports.default@http://localhost:4200/assets/vendor.js:96062:5
    @http://localhost:4200/assets/inter-cat.js:140:4
    Module.prototype.exports@http://localhost:4200/assets/vendor.js:111:18
    requireModule@http://localhost:4200/assets/vendor.js:32:7
    @http://localhost:4200/assets/inter-cat.js:876:3
```

**Comment by zorn-v** [comment]
`ember-source` was updated to 3.2.0
I think is the because

**Comment by rwjblue** [comment]
Yep, now look at those lines from the stack trace. You should be able to see which addon (or part of your app code) is triggering it.  I personally would start with a breakpoint at the `resolveInitializer` line and see which modules are using `Ember.EXPAND_PROTOTYPES`.  You could also grep/ag/rg in your node_modules for usages of `EXPAND_PROTOTYPES`...

**Comment by zorn-v** [comment]
Are you kidding me ?
I DID NOT use EXPAND_PROTOTYPES as well. It exists after standard ember skeleton. I'd tried removing it - no pasaran.
You tell like a troll.

**Comment by rwjblue** [comment]
A newly generated Ember app does not emit this deprecation message (I just tested via `ember new foo && cd foo && ember s`), so there is something different about your application that is triggering the deprecation. The things I've described above are just a few ways to track down deprecations like these. I'm sorry that you feel that I am trolling you 😞.

**Comment by bekzod** [comment]
could be ember inspector issue please try disabling ember inspector related: https://github.com/emberjs/ember-inspector/pull/810

**Comment by ro0gr** [comment]
I also use ember-source@3.2.0 and have the same `EXTEND_PROTOTYPES` deprecation with a similar stactrace. It comes from the [`ember-inflector/ext/string`](https://github.com/emberjs/ember-inflector/blob/master/addon/lib/ext/string.js#L8)

**Comment by rwjblue** [comment]
@ro0gr - That line was recently updated to avoid deprecation, can you please confirm that you are on the latest version?

**Comment by ro0gr** [comment]
So in my case it was an outdated transitive ember-inflector@2.2.0 dependency.

`yarn upgrade ember-cli-mirage ember-data` fixed the issue for me.

**Comment by rwjblue** [comment]
Awesome, thank you for chiming back in to confirm that fixed it for you!

**Comment by zorn-v** [comment]
I return "^"  to "~" on `ember-source`, `ember-data` and `ember-cli` to semver in package.json and 3.1.0 to `ember-source`
I think problem in ember-data, coz it use old version of `ember-inflector` which use `Ember.EXTEND_PROTOTYPES`

Should resolve when ember-data 3.2 released.

**Comment by urbany** [comment]
Might also be because of this, what was already fixed on ember-inspector but no release: https://github.com/emberjs/ember-inspector/issues/818

**Comment by urbany** [comment]
Might also be because of this, what was already fixed on ember-inspector but no release: https://github.com/emberjs/ember-inspector/pull/810

**Comment by Frozenfire92** [comment]
In the process of updating from `"ember-source": "~3.1.0",` to `"ember-source": "~3.3.0",` via [ember-cli-update](https://github.com/ember-cli/ember-cli-update/) I also started experiencing this issue

```
deprecate.js:102 DEPRECATION: Accessing Ember.EXTEND_PROTOTYPES is deprecated, please migrate to Ember.ENV.EXTEND_PROTOTYPES [deprecation id: ember-env.old-extend-prototypes]
```
which pointed to https://github.com/emberjs/ember-inflector/blob/master/addon/lib/ext/string.js#L8 as well

A fresh `yarn` was not enough (even though it showed the latest ember data in inspector). However disabling ember inspector did not fix for me, however similar to https://github.com/emberjs/ember.js/issues/16721#issuecomment-396604948 this did fix it for me

```
yarn upgrade ember-data
```

I wonder if something is missing in the ember-cli-update about what happens when you run yarn upgrade?

**Comment by locks** [comment]
Issue should be fixed for new apps.

**Comment by eternal191** [comment]
I just added "EXTEND_PROTOTYPES: 'true'," to the ENV object and the error went away.  Hope this helps someone.
