### ISSUE TITLE
After ember changed the page, all files were scanned after refurbished, resulting in slow restart.

### ISSUE THREAD

**Issue by daniel-lij** [emberjs/ember.js#16722]
After ember changed the page, after refurbished, every time you need to scan all the files, it's slow to restart, and sometimes it changes a little bit. It takes a long time to start the page. I put the picture I started with my shell on the bed. (**https://waifu2x.booru.pics/outfiles/432a4d809e670e06f3bf5dd0e956822924d43e46_s2_n1.jpg**), I want to see, I want to know why this situation, how to solve the problem, the problem is that the previous program runs very well, after changes, it will soon be able to refresh the page, there is no case of scanning all the files. . Thank you. I'd appreciate it.

**Comment by Serabe** [comment]
Where is that image folder?

**Comment by rwjblue** [comment]
I'm sorry, I really do not understand what is being reported here. Can you explain step by step what you are doing and what seems wrong?

**Comment by pixelhandler** [comment]
Closing for now per our triage policy, https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy feel free to reopen if you would like to discuss the issue further.
