### ISSUE TITLE
It appears '.addObserver' does not destructure and accepts only one path string

### ISSUE THREAD

**Issue by alexmasita** [emberjs/ember.js#16736]
I needed the ability to enable and disable observers in my controller by moving them to my route in the `setupController` and `deactivate` hook and using `addObserver` and `removeObserver`.  However, I was unable to use destructuring in the form below:

```
//Does not work
 addObserver(controller, 'model.{requestId,destinationLat,originLat,hasDirtyAttributes,state,end,action}', controller, function () {
});
```
I discovered it only works when I pass only one dot delimited string path in the following form:
```
//Works but only observes one path
  addObserver(controller, 'model.requestId', controller, function () {
});
```
Passing a series of dot delimited paths also fails:
```
//This fails as well
  addObserver(controller, 'model.requestId', 'model.destinationLat', controller, function () {
});
```
Any known workarounds to get the first example working with destructuring using the `addObserver`

**Environment**
Ember Inspector | 3.1.1
Ember | 3.1.2
Ember Data | 3.1.1
jQuery | 3.3.1

**Comment by rwjblue** [comment]
This confused me for a bit, until I realized what you meant.

This syntax:

```
computed('model.{requestId,destinationLat,originLat,hasDirtyAttributes,state,end,action}', function () {});
```

Is not actually destructuring, we call it property expansion.

---

The `addObserver` API is intentionally lower level than others (like `computed` and `observes`) that support property expansion. You can do what you need via something like:

```js
 function whateverFunction() {}

 addObserver(controller, 'model.requestId', controller, whateverFn);
 addObserver(controller, 'model.destinationLat', controller, whateverFn);
 addObserver(controller, 'model.originLat', controller, whateverFn);
 addObserver(controller, 'model.hasDirtyAttributes', controller, whateverFn);
 addObserver(controller, 'model.state', controller, whateverFn);
 addObserver(controller, 'model.end', controller, whateverFn);
 addObserver(controller, 'model.action', controller, whateverFn);
```

This is effectively what the more sugary API's of `computed` / `observes` are doing under the hood.

**Comment by rwjblue** [comment]
I'm going to close this now, but please let me know if I've misunderstood something. I'm happy to reopen if I have... 😺

**Comment by alexmasita** [comment]
@rwjblue, thank you,  I understand.  In the end I opted to use a flag set on setupController and unset on resetController on route change that is checked on the controller observer before execution.  It seems to work so far,  I hope there wont be a performance penalty when I have too many of such in my app.  Cheers.
