### ISSUE TITLE
Timeout no longer required for pauseTest in ember-mocha v0.14.0

### ISSUE THREAD

**Issue by caseywatts** [emberjs/ember.js#16738]
The timeout line isn't necessary in ember-mocha v0.14.0 or newer - it does that behavior for us automatically now :)
https://github.com/emberjs/ember.js/blob/44aaf276a01edc2b0f87367bd56fbc4aaa436b83/packages/ember-testing/lib/helpers/pause_test.js#L44-L51

**Comment by rwjblue** [comment]
🎉 - Thanks for pointing this out!

Mind sending a PR fixing?

**Comment by rwjblue** [comment]
@Devarajeshwaran sorry about not getting the labels fixed here, I think that @caseywatts has a PR open for this over in https://github.com/emberjs/ember.js/pull/16740
