### ISSUE TITLE
WIP Add ember-test-helpers package documentation into core API docs

### ISSUE THREAD

**Issue by jenweber** [emberjs/ember.js#16749]
We need to get the docs from [ember-test-helpers](https://github.com/emberjs/ember-test-helpers) into our main documentation site. The easiest/MVP way to do this would be to translate the current markdown format into YUIdoc and include it in the core codebase.

This approach should be discussed more before a contributor tries to tackle it. We would like to ultimately include it as a quest issue/call for community help in the Times etc.

**Current behavior:**
Users can't find testing documentation in our API docs

**Expected behavior:**
Users should be able to search and read about the test helpers just like any other docs. Docs should go into clearly marked files so that it is obvious that it's documentation for outside resources.

**Long term:**
We should ultimately solve how to bring in new repos, rather than coding it into Ember.js but our current architecture doesn't support it. When we break other parts of the API into separate packages, that may be the right time to build the necessary infra. Search is the hard part at the moment.

**Comment by jenweber** [comment]
cc @toddjordan

**Comment by rwjblue** [comment]
I am fairly opposed to moving the documentation into this repo, or otherwise making them appear to come from Ember itself.

The solution that I had always assumed was that we would add `@ember/test-helpers` to the list of projects on the top left side of emberjs.com/api and essentially treat it no differently than Ember, Ember Data, (hopefully ember-cli), etc.

**Comment by jenweber** [comment]
How much do you expect the ember test helpers to change in terms of new features?

**Comment by ballPointPenguin** [comment]
I agree with the sentiment "Users can't find testing documentation in our API docs."
The testing stuff is: 1. One of the best things about Ember, and 2. Unique enough to justify thorough and accessible documentation.
I would echo this same sentiment about ember-cli.

**Comment by jenweber** [comment]
We will get the testing docs into the API docs site eventually. The questions are, where do we put those docs in codebases, and how quickly can we do it. Right now I don’t know of anyone with the bandwidth to do more than the shortcut I proposed, but we’ll figure something else out. We can maybe make it a quest issue and get more community help.

Closed, will continue the discussion elsewhere.
