### ISSUE TITLE
Binding style attribute warning, invalid anchor

### ISSUE THREAD

**Issue by bekicot** [emberjs/ember.js#16746]
The anchor is invalid for 
```
ember-console.js:24 WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see https://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes.
```
![image](https://user-images.githubusercontent.com/1826884/41309532-33c11580-6ea9-11e8-91bf-22cb83ab5528.png)

https://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes
Is non existent

**Comment by kennethlarsen** [comment]
@bekicot Looks like the link works now. Must have been a hiccup with the guides. Can you confirm it works and then close the issue?

**Comment by bekicot** [comment]
It is working now :)
