### ISSUE TITLE
Updating to Ember 3.2 causes JavaScript heap out of memory exception on building production

### ISSUE THREAD

**Issue by maxzats** [emberjs/ember.js#16759]
In package.json, changing:

```"ember-source": "3.0.0",```
to 
```"ember-source": "3.2.0",```

gives this error message when running ```ember build --environment=production```:
```
<--- Last few GCs --->

[1120:0x415a6f0]   117355 ms: Mark-sweep 1373.1 (1429.1) -> 1373.1 (1429.1) MB, 1244.3 / 0.0 ms  allocation failure GC in old space requested
[1120:0x415a6f0]   118610 ms: Mark-sweep 1373.1 (1429.1) -> 1373.1 (1426.1) MB, 1255.1 / 0.0 ms  last resort GC in old space requested
[1120:0x415a6f0]   120299 ms: Mark-sweep 1373.1 (1426.1) -> 1373.1 (1425.6) MB, 1688.1 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1285ac425879 <JSObject>
    1: stringSlice(aka stringSlice) [buffer.js:560] [bytecode=0x2c7274063f49 offset=94](this=0x130af00022d1 <undefined>,buf=0x2285d1b678a1 <Uint8Array map = 0x207e151c35a1>,encoding=0x1285ac434ba1 <String[4]: utf8>,start=0,end=402168)
    2: toString [buffer.js:~609] [pc=0x11ce9fe9669e](this=0x2285d1b678a1 <Uint8Array map = 0x207e151c35a1>,encoding=0x1285ac434ba1 <String[4]: utf8>,start=0x130af0...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [ember]
 2: 0x8c21ec [ember]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [ember]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [ember]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [ember]
 6: v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [ember]
 7: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [ember]
 8: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [ember]
 9: 0x8e2526 [ember]
10: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [ember]
11: 0xad710c [ember]
12: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [ember]
13: 0x11ce9f4842fd
./build: line 20:  1120 Aborted                 ember build --environment=production```

**Comment by kennethlarsen** [comment]
@maxzats I tried reproducing this with no luck. Can you share some more info of your setup or share a repo with the failing app?

**Comment by string-areeb** [comment]
https://github.com/fossasia/open-event-frontend

Building this in production mode takes above 1 GB RAM and keeps increasing. Even after `JOB=1` workaround

**Comment by mactenm** [comment]
what i i eeally want is an app tjat makes all 3part happy costumer and team
plus und user . you should be able to folloe loved ones friends to eather
disko bars shopping malls snd restutany but thhen  free for everone from
start only the shops = costumers pay for add camerchal . user get point by
check in shops get more populare by checklns and so on

man. 14. jan. 2019 kl. 13.56 skrev Cyrille David <notifications@github.com>:

**Comment by string-areeb** [comment]
@dcyriller When building inside docker or CI, it throws OOM errors. On latest ember CLI as well. I can build it on my machine as well as it has 16 GB RAM, but it fills it up entirely during its building time 

`JOBS=1 ember build --environment=production  51.82s user 2.45s system 109% cpu 49.718 total`

**Comment by kinghrothgar** [comment]
@string-areeb I was getting indentical error messages and I had to do this `node --max-old-space-size=4096` to prevent the OOMs.

**Comment by rwjblue** [comment]
I don’t think there is much we can do here, though Node continues to improve its ability to use more memory (an application that I work on that used to require manual increase of old heap size, no longer requires it on Node 12).
