### ISSUE TITLE
Problem with `@each` at computed property

### ISSUE THREAD

**Issue by raphaelns-developer** [emberjs/ember.js#16753]
I'm using `@each` to filter an array by a value, but this value is inside another object:
 ```
filtered: computed('todos.@each.content.isDone', function ()   {
    return this.get('todos').filterBy('content.isDone', false);
  })
```
The computed is not updated when a changed the value `set(obj.content, 'isDone', false);`. The `@each` not suport nested values or this is an issue?

**Comment by atomkirk** [comment]
seems related to mine https://github.com/emberjs/ember.js/issues/16751

**Comment by atomkirk** [comment]
Maybe not, this might be a problem with your code:

> Note that @each only works one level deep. You cannot use nested forms like todos.@each.owner.name or todos.@each.owner.@each.name.

https://guides.emberjs.com/release/object-model/computed-properties-and-aggregate-data/#toc_multiple-dependent-keys

**Comment by raphaelns-developer** [comment]
Yes. My mistake. Thank You @atomkirk
