### ISSUE TITLE
regression in ember 3.0: computed filterBy observing ember data relationship (includes example app)

### ISSUE THREAD

**Issue by atomkirk** [emberjs/ember.js#16751]
Here's the example app with instructions:

[each-saved.zip](https://github.com/emberjs/ember.js/files/2111303/each-saved.zip) (updated 6/18/18 8:59 EST)

`ember server`, then go to `http://localhost:4200/demo-one` and follow the instructions.

I have a model tree, which hasMany bananas. I pass `model.bananas` to a component as a positional param. In that component, I have a computed property `savedRecords: filterBy('records', 'isNew', false)`

After isNew changes on the banana, the computed property does not update. The component shows a list of only saved bananas and no bananas get rendered after the save.

This worked on ember 2.18 and is now broken on ember 3.1.3

It also works if its not a relationship. If I pass an array of bananas directly, then it works. But if I pass bananas as a relationship on tree, it doesn't work

**Comment by mmun** [comment]
This is fixed on ember-data master and will be released in ember-data 3.2.0 (soon hopefully!)

In the mean time, as a workaround I think that you can change

```js
this.store.createRecord('banana', {
  color: 'yellow',
  tree: tree
})
```

to

```js
let banana = this.store.createRecord('banana', { color: 'yellow' });
banana.set('tree', tree);
```

**Comment by atomkirk** [comment]
Great! Was this already fixed before I posted the issue or did my example app help? Should we close this?

**Comment by mmun** [comment]
@atomkirk It's fixed a couple months ago but we can leave it open until an ember-data 3.2 is released.

**Comment by mmun** [comment]
Ember data 3.2 has been released.
