### ISSUE TITLE
How to create the thumbnail link?

### ISSUE THREAD

**Issue by bloodknight2010** [emberjs/ember.js#16764]
Hello All,
I would like to create the thumbnail link preview and then click that link We must go to the redirect url.
Ho to do?
Pls help me.

**Comment by kennethlarsen** [comment]
Hi @bloodknight2010 

This repo is mainly for reporting issues with Ember.js itself. You might have more luck with this if you write a post on the discussion forum (http://discuss.emberjs.com/) or the Ember Slack (https://embercommunity.slack.com/ - get an invite here -> https://ember-community-slackin.herokuapp.com/)
