### ISSUE TITLE
ember-source-channel-url is returning outdated URLs for beta & release

### ISSUE THREAD

**Issue by kategengler** [emberjs/ember.js#16765]
https://s3.amazonaws.com/builds.emberjs.com/beta.json (used by `ember-source-channel-url` and built on Travis by this repo) shows

```
{
  "version": "3.2.1-beta+a8d4767e",
  "buildType": "beta",
  "SHA": "a8d4767e0f1fa29897a3fc0b188e15bcf72dc64c",
  "assetPath": "/beta/shas/a8d4767e0f1fa29897a3fc0b188e15bcf72dc64c.tgz"
}
```
but the latest beta branch build on Travis built `beta/shas/1dd7cd601539b5c68a795fcefbef6c1af6ea4349.tgz` (https://travis-ci.org/emberjs/ember.js/jobs/393927258#L1303)

Similarly, https://s3.amazonaws.com/builds.emberjs.com/release.json shows 3.1.2-sha but the latest release is 3.2.1.

https://s3.amazonaws.com/builds.emberjs.com/canary.json looks correct

h/t @rwjblue

**Comment by rwjblue** [comment]
Should be fixed by https://github.com/emberjs/ember.js/commit/3f053be1886fd32598bb9a287c18138c799dbccf.

**Comment by kategengler** [comment]
Both are correct now, thanks!

**Comment by kategengler** [comment]
Beta is back to 3.0.0-beta-sha, release is 3.1.3-sha

**Comment by kategengler** [comment]
I think is happened because release-n branches were built https://travis-ci.org/emberjs/ember.js/builds/396648149

For now, I am going to rebuild beta & release to fix it. I think long term we need a better way to ensure that the data in the JSON files is correct.

**Comment by kategengler** [comment]
For beta and release, if we leave out BUILD_TYPE from the .travis.yml, I think that would solve some of the problem (https://github.com/emberjs/ember.js/blob/ab975417c47d49cd183b1e0470aea3c77c162682/bin/publish_to_s3.js#L20)

But I think, as it is, if someone rebuilds an older build, it will overwrite those files.

**Comment by ef4** [comment]
@kategengler https://s3.amazonaws.com/builds.emberjs.com/release.json is currently showing 2.18.2-release+dee83e87

Probably a patch release of LTS overwrote the real release channel?

This is probably causing lots of addons to get different test coverage results than they expect. In my case it is causing build failures because the release channel _should_ be new enough to work without jQuery, but we're actually get an old enough Ember that it needs jQuery.

**Comment by kategengler** [comment]
Yes -- I've been checking ~1x per day to make sure they are right. The temp fix is to rerun the relevant branch.

This is tricky to fix because the fix needs to be applied to every possible old branch that was at one time incorrect. My other thought would be to remove permission to write those files from the existing s3 keys and make new s3 keys that can write those files, only making them available on release & newer.
