### ISSUE TITLE
button component ignores disabled attribute when jquery is not included

### ISSUE THREAD

**Issue by timmorey** [emberjs/ember.js#16779]
I've noticed an inconsistent component behavior when jquery is included vs when it is excluded by adding `vendorFiles: { 'jquery.js': null }` to `ember-cli-build.js`

I have a component that looks like this:

my-button.js
```
export default Component.extend({
  tagName: 'button',
  attributeBindings: ['disabled'],
  disabled: false
});
```

my-button.hbs
```
{{yield}}
```

I'm using it with an svg icon as content, like this:

```
{{#my-button disabled=isButtonDisabled click=(action 'didClickButton')}}
  <svg viewBox="0 0 16 16" width="16" height="16">
    <circle cx="8" cy="8" r="6" stroke="red" fill="yellow" />
  </svg>
{{/my-button}}
```

The difference occurs when you click on the svg content, rather than the button itself.  If jquery is used, it will only fire `click` when `disabled=false`.  If jquery is excluded, it will fire `click` for any value of `disabled`.

I'm not sure which of these is correct - just pointing this out since the inconsistency recently tripped me up.

I attempted to repro in a jsbin and twiddle, but couldn't figure out how to toggle the inclusion of jquery in those contexts, so I built a simple example app: https://github.com/timmorey/click-inconsistency

It contains a single integration test that will fail if jquery is excluded (`vendorFiles: { 'jquery.js': null }`), and will pass if jquery is included.

**Comment by rwjblue** [comment]
@timmorey I'm very sorry for the delay here, I did glance at the demo setup, and nothing is _obviously_ wrong with what you are doing, I am surprised that the test doesn't pass without jQuery....

Would you mind updating that reproduction and leveraging the newer `@ember/optional-features` mechanism for disabling jQuery to see if this is still an issue?

**Comment by locks** [comment]
Tested on 3.10 and it is fixed!
