### ISSUE TITLE
appendChild() extension point deprecated without warning or replacement in 3.2

### ISSUE THREAD

**Issue by kanongil** [emberjs/ember.js#16782]
I am using the `childViews` property in my app for a custom key navigation implementation.

To know when it is changed, I have added an override of the `appendChild()` method to my component code:

```js
  appendChild() {
    once(this, this.notifyChildViewsChange);
    return this._super(...arguments);
  },
```

This stopped working with Ember 3.2 due to 7e623f2cf96a0eee2258666295621ff65946bcca, where it no longer calls the view function, but [mutates the array privately](https://github.com/emberjs/ember.js/commit/7e623f2cf96a0eee2258666295621ff65946bcca#diff-1d6263d5fa618e89a735e9df0fe95f81R259).

Can this be changed back? At least for curly components?

Alternatively, I would like a new hook to be added to know when a childView has been added. For now, I have reverted to 3.1.

**Comment by rwjblue** [comment]
From the issue title:

> appendChild() extension point deprecated without warning or replacement in 3.2

This does not seem correct, there is no deprecation that I can see.

> I am using the childViews property in my app for a custom key navigation implementation.
>
> To know when it is changed, I have added an override of the appendChild() method to my component code

Both `childViews` _and_ `appendChild` are private API's, there is no documentation that I can find that suggests these are user-land hooks.

A quick search on emberobserver.com shows very little usage of either in addons:

* [appendChild](https://emberobserver.com/code-search?codeQuery=appendChild&sort=score&sortAscending=false) (note: search includes results for `element.appendChild` also)
* [childViews](https://emberobserver.com/code-search?codeQuery=childViews&sort=score&sortAscending=false)

From the looks of these usages, I don't think this raises to the level of intimate API (which would require an LTS deprecation cycle).

**Comment by rwjblue** [comment]
> I am using the childViews property in my app for a custom key navigation implementation.

Lets focus on this part, can you share more information? How does monkey patching `appendChild` / `childViews` help your implementation?

**Comment by kanongil** [comment]
Yes, I know that it is both private and obscure usage.

My key navigation is based on ember components, which is either a `focusable` or a `focus-group` that contains other focusables / groups. In the `focus-group` component I iterate `childViews` to determine which elements are focusables, and thus targets for key navigation.

This used to work back in the 1.x cycle. At some point Ember stopped signalling changes to this property, which caused my `appendChild()` monkey patch.

I know that I can achieve the nested element detection in other ways, but not as performant.

**Comment by kanongil** [comment]
Somewhat condensed example of  template using this:
```hbs
{{#focus-group class="main" direction="horizontal"}}
  {{#focus-group class="highlights" direction="vertical"}}
    {{#each list as |item index|}}
      {{#focus-item}}{{item.label}}{{/focus-item}}
    {{/each}}
  {{/focus-group}}
  {{#focus-group direction="vertical"}}
    {{#focus-button class="search-button" action="showSearchDialogue"}}
      <span class="icon"></span>
      Search
    {{/focus-button}}
  {{/focus-group}}
{{/focus-group}}
```

It would suck to have to add explicit bindings to this code, as it is nicely represented with the implicit hierarchy.

Note that to work, the focus-group logic is added to any element that can contain other focusable elements.

**Comment by rwjblue** [comment]
That is a good question indeed :smiley:

AFAIK, the only real use is the ember inspector...

**Comment by kanongil** [comment]
childViews "support" should probably just be removed. It's not even used in ember inspector.

Anyway, this actual issue can be closed.
