### ISSUE TITLE
Can't use JS native Proxy with Ember object

### ISSUE THREAD

**Issue by ctusch** [emberjs/ember.js#16780]
Ember seems to strip the proxy when I use it as a prototype for a new Ember object. I've tested this with Ember 2.18.2, [here is the twiddle](https://ember-twiddle.com/3514dbade895e6972664bdc7cac25ee7?openFiles=controllers.application.js%2C).

It works when using the proxy as the prototype for a normal (non-Ember) object.

**Comment by rwjblue** [comment]
Passing an object to `Ember.Object.extend()` will result in the properties of that object being copied to the prototype of the newly created class.

I don't fully understand what you are trying to do here? Can you share a non-Ember.Object version of what you are trying?

**Comment by ctusch** [comment]
Ah, that explains it. I'm currently writing a query builder (as a fluent API) and using a proxy would have saved me some typing. I wanted to trap certain function calls and handle them in one generic function.

So probably the only way to do this with an Ember object is to use unknownProperty and then call the function using this.get('someFunction')(). But that would be too much overhead for me in this case. So I'll just write all function out.

Thanks for the swift response!
