### ISSUE TITLE
Bug? components are rerendered even when classNameBindings rely on properties that don't actually change

### ISSUE THREAD

**Issue by kristeehan** [emberjs/ember.js#16786]
`didRender` hook called even if class name would not change.

See https://ember-twiddle.com/649f1174eefcab6ba294688802936cdb?openFiles=components.broken-render.js%2Ctemplates.components.broken-render.hbs.

Click button and see console output.

Thanks,

Kris

**Comment by rwjblue** [comment]
There is definitely no specific guarantee on how many times `didRender` will be called (we do however confirm that we will always fire at least once whenever something has changed).

This isn't really a bug in the framework, so I'm going to close this for now. I think we'd definitely accept a PR to the API docs or Guides if you can think of a way to make this clearer to folks than we do currently.
