### ISSUE TITLE
infinite content-for body inserted on some errors (instead of crash and stop)

### ISSUE THREAD

**Issue by ngouy** [emberjs/ember.js#16789]
(issued in development env, not tested in production)

When there are some errors in the code such as component name typo or something like that, once 
the wrong content is reached (when it should be inserted on a certain url), the app re-insert content-for body infinitly until the tab is killed or it crash.
It should just crash and stop the process as any other common errors

exemple https://ember-twiddle.com/0109e442611d64e9b87142694dc69a4e

(Here, we need to click on a link to reproduce the bug)

Ember 3.x

**Comment by rwjblue** [comment]
With Ember 3.4 and higher this should be much better (still likely not perfect). We attempt to handle recovery and avoid the infinite recursive error throws, but its definitely possible there are specific scenarios that we still don't handle perfectly.

I'm going to go ahead and close this issue for now, but I'd love it if you could review the tests [around here](https://github.com/emberjs/ember.js/blob/4a98e1610b795edb544513f10a8870af1375141d/packages/%40ember/-internals/glimmer/tests/integration/components/error-handling-test.js#L8) and submit some more test cases that you are still struggling with. I'd really like to continue to beef up our resilience by adding more and more "real world" scenarios to that test module...
