### ISSUE TITLE
Missing docs for defineProperty

### ISSUE THREAD

**Issue by jenweber** [emberjs/ember.js#16790]
Help wanted: defineProperty is referenced as a solution to a 3.x deprecation, but it isn’t documented. It was last documented in 1.13.

To do:
- look up the 1.13 docs
- update them to use 3.x syntax for examples (the method is currently on @ember/object)
- update the yuidoc reference, using the same format as similar methods like computed. We changed yuidoc syntax since 1.13
- get a review of the PR from someone on Ember Core and the Learning Team

**Comment by ijlee2** [comment]
I can help with updating the 3.x doc to include defineProperty.

**Comment by jenweber** [comment]
PR https://github.com/emberjs/ember.js/pull/16791

**Comment by rwjblue** [comment]
Resolved by #16791
