### ISSUE TITLE
Ember v3.1.3 & Ember Engines v0.5.20 incompatible

### ISSUE THREAD

**Issue by toranb** [emberjs/ember.js#16799]
I couldn't reopen [this issue](https://github.com/emberjs/ember.js/issues/16610) so I'm creating a new issue to show it's still a defect in the latest ember v3.1

A full working repro can be seen here

https://github.com/toranb/-ember-engine-get-issue

**Comment by rwjblue** [comment]
Ember 3.2 has been out for a while now (which includes the fix), and Ember 3.1 is not the current release or an LTS so I don't think we would normally do patch releases for it...

**Comment by toranb** [comment]
😅
