### ISSUE TITLE
[Docs] AppInstance#register w/ instantiate: false

### ISSUE THREAD

**Issue by mike-north** [emberjs/ember.js#16796]
When registering some value to the container with options `{ instantiate: false }`, a subsequent `Ember.getOwner(this).lookup()` will hand the value back to you directly. 

Demo: https://ember-twiddle.com/991fcc164bff88f2bc1edcff9370e90c?openFiles=initializers.foo.js%2C

This has worked for at least 3-4 years, and IIRC ember templates end up in the container by this mechanism. @stefanpenner informs me that this is also part of how the `config/environment.js` module works, in that `ENV` object is stored in the container as a POJO (w/ `instantate: false`)

[The API docs indicate](https://www.emberjs.com/api/ember/3.2/classes/ApplicationInstance/methods/register?anchor=register) that you must pass a `Function` into `register(containerKey, Function)`. Can we regard something like this to be an "intimate API", allowing consumers the flexibility to use the container in this way with confidence?

```ts
// Factory case (current documentation)
register(containerKey: string, value: Function, options?: { instantiate?: boolean, singleton?: boolean })

// Arbitrary value case (instantiate: false --> container doesn't care what the value is)
register(containerKey: string, value: any, options: { instantiate: false })
```

It may also be worth clarifying that the registration API wants an **Ember** factory (something that has a `static create()`)

**Comment by rwjblue** [comment]
Seems fine to update the docs to `unknown` or `any`
