### ISSUE TITLE
[BUG] Inconsistent rendering in update from 3.1 to 3.2

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#16800]
I'm not sure what the minimum reproduction is, but it can be observed in Ember Power Select.

It can be observed in the first two selects in http://ember-power-select.com/docs/action-handling.

**Expected** (works in 2.10 through 3.1): When the select opens, the searchbox inside gains focus immediately (https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select/before-options.js#L11-L17)

**Result**: In 3.2, the input seems to never get focused. On a closer inspection, it *does* get focused but immediately after it looses it (an `onblur` event is triggered).

I'm not sure what have changed exactly in the rendering engine that makes the input loose the focus.
At first I suspected it could be related with the usage of `{{-in-element}}` but I can observe the problem when I pass `renderInPlace=true`, which doesn't make use of it.

A temporary workaround it to use `Ember.run.next` instead of `Ember.run.scheduleOnce('afterRender')`, but this seems a regression.

**Comment by cibernox** [comment]
The trace didn't show anything helpful, just that the `onblur={{action onBlur}}` is being called. 

`e.relatedTarget` of the blur event is the `.ember-power-select` trigger, but I don't know why that element would gain the focus.

**Comment by pixelhandler** [comment]
@cibernox I noticed you mentioned a fix here https://github.com/cibernox/ember-power-select/issues/1130#issuecomment-403457843 and also:

> A temporary workaround it to use `Ember.run.next` instead of `Ember.run.scheduleOnce('afterRender')`, but this seems a regression.

Can you link to the code that is an example of the fix?

**Comment by martin-hoger** [comment]
Also in the docs (https://ember-power-select.com/docs/custom-search-action), I open the select, it says "Type to search", I start to type, nothing. I need click the search field to type. :(

**Comment by pixelhandler** [comment]
@cibernox is this still an issue in the current release of Ember / power-select ?

**Comment by cibernox** [comment]
I belive it was fixed
