### ISSUE TITLE
[Bug] Ember API documentation links to source are broken

### ISSUE THREAD

**Issue by mike-north** [emberjs/ember.js#16809]
Travis-ci jobs are messing up API docs.

![screen shot 2018-07-10 at 11 37 22 pm](https://user-images.githubusercontent.com/558005/42554602-61e60144-849a-11e8-81bf-d428b95571fd.png)

**Comment by rwjblue** [comment]
I don’t understand, can you explain what is wrong in more detail?

Also, from the screenshot this seems like it may be related to ember-data (but this issue is in ember itself).

**Comment by mike-north** [comment]
TBH there are many repos, and particularly in the area of scripts for generating API docs based on comments in source, I don't know where the appropriate place to report this is.

Ember-data's references to source are URLs pointing to the `/tmp` folder within travis-ci build artifacts

**Comment by rwjblue** [comment]
> Ember-data's references to source are URLs pointing to the /tmp folder within travis-ci build artifacts

Thank you, I didn't spot the invalid URL when I poked at this this morning.

> TBH there are many repos, and particularly in the area of scripts for generating API docs based on comments in source, I don't know where the appropriate place to report this is.

Yep, totally understood! Since ember's own API docs don't have this issue, we should dig in to how ember-data's doc generation differs from ember-source's...

**Comment by hakilebara** [comment]
I think this issue has been fixed in https://github.com/emberjs/data/issues/5483#issuecomment-406310498 and can be closed.
