### ISSUE TITLE
Routes not Loading on Safari or Chrome for Mac

### ISSUE THREAD

**Issue by deividkamui** [emberjs/ember.js#16818]
I'm getting the next error on Safari and Chrome for Mac:

> Error: Module name "ember-demo/routes/items/index" has not been loaded yet for context: _. Use require([])

Sorry forgot to include de ember version: 

> ember-cli: 3.2.0
> node: 6.10.2
> os: darwin x64

How ever it is working on Chrome on Windows.

**Comment by bekzod** [comment]
ember version number would be helpful, or access to your `ember-demo` app

**Comment by pixelhandler** [comment]
@deividkamui have you resolved this issue yet? If not can you please create a reproduction of the issue, perhaps as @bekzod mentioned link a repo for an example application that demonstrates the issue you are having.

**Comment by rwjblue** [comment]
This issue isn't really very actionable, and its been quite a long time without feedback. I'm going to go ahead and close. Feel free to open a new issue with more details on how to reproduce if you are still hitting this...
