### ISSUE TITLE
@ember/routing | Uncaught TypeError: currentWhen.split is not a function

### ISSUE THREAD

**Issue by lifeart** [emberjs/ember.js#16819]
Uncaught TypeError: currentWhen.split is not a function

`ember` v3.2.2
Sometimes got this error:

```
vendor.js:32726 Uncaught TypeError: currentWhen.split is not a function
    at Class._isActive (vendor.js:32726)
    at Class.computeLinkToComponentActive (vendor.js:32757)
    at ComputedProperty.get (vendor.js:42745)
    at get (vendor.js:42074)
    at Class.get (vendor.js:54190)
    at Class.computeLinkToComponentActiveClass (vendor.js:32750)
    at ComputedProperty.get (vendor.js:42745)
    at get (vendor.js:42074)
    at RootPropertyReference.compute (vendor.js:31259)
    at RootPropertyReference.value (vendor.js:31136) 
```

debug:

```
currentWhen string protected.patients.index
currentWhen string protected.patients
currentWhen string protected.recipients
currentWhen string protected.statistics
currentWhen string protected.administration
currentWhen string protected.patients.index
currentWhen string protected.patients.index
currentWhen string protected.patients.index
currentWhen string protected.patients.index
currentWhen string protected.patients.patient.common
currentWhen string protected.patients.patient.common
currentWhen string protected.patients.patient.clinical-data
currentWhen string protected.patients.patient.clinical-data
currentWhen string protected.patients.patient.consilium
currentWhen string protected.patients.patient.consilium
currentWhen object ["protected.patients.patient.common"]
```

Faced, after ember-hot-load installation. @toranb any ideas?

![image](https://user-images.githubusercontent.com/1360552/42696978-7c787eb8-86c2-11e8-8330-c9f888988944.png)

somehow `current-when` became array, instead of boolean / string

can't find overrides for `link-to` component `currentWhen` or `current-when` proprerty in project and node modules

**Comment by toranb** [comment]
@lifeart I got you covered boss :) just add a config to exclude the link-to component from hot reloading like you see in the commit below 

https://github.com/toranb/ember-hot-reload-demo/commit/ec19d94ec742649be44948266301340c70aa9041

**Comment by toranb** [comment]
Core Team: this can be closed (its hot reload related and as that's not a supported/official addon I don't think we need to handle that here)

**Comment by rwjblue** [comment]
Thanks @toranb
