### ISSUE TITLE
"Each" template helper not rerendering

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#16812]
Having the following component in Ember 3.2:

```coffeescript
import Component from '@ember/component'
import { A } from '@ember/array'
import { later } from '@ember/runloop'

export default Component.extend
  init: ->
    @_super(arguments...)
    @set('array', A(['a', 'b', 'c']))
    @addObserver 'array', ->
      console.log 'changed'
    later =>
      @set('array.1', 'd')
    , 5000
```

```handlebars
{{#each array as |value index|}}
  {{value}} {{index}}
{{/each}}
```

Whenever the `later` occurs and the second element of the array is changed to 'd', neither does the observer get called, nor does the template rerender. For the observer I guess it is normal but is that so for the template?

Funnily enough, `each-in` doesn't work like that. Whenever a property in the object is replaced, `each-in` does rerender. Why is there such an inconsistency? Is this a bug?

**Comment by urbany** [comment]
Created a twiddle with your code and had the same problem you have, but not sure if it is a bug or not.
I don't think the observer should be triggered, because you are not changing the array, you are just changing it's content, so you should observe `array.[]`.

If you use `replace` instead of set it works: https://ember-twiddle.com/0b0f89f560d387e19a6989b9f4553e0d?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs

**Comment by boris-petrov** [comment]
@urbany - yes, I also think the observer should not trigger, but I also don't think that `array.[]` will be triggered. And, still, there is the trouble that the template is not rerendered which I think is a real bug.

I'll try using `replace`. That is strange - `set` should use `replace` internally.

**Comment by urbany** [comment]
Everything is working fine in my twiddle with `replace`, even the observer for `array.[]`.
But you are correct in saying that `.set` won't trigger the `array.[]`. But like I said, not sure if `set` should work here, never used to edit an array like that.

Let's wait until someone from the team can answer that question.

**Comment by btecu** [comment]
That's not how you're supposed to update array elements.

**Comment by boris-petrov** [comment]
How are you "supposed to update array elements"?

**Comment by btecu** [comment]
You can only update objects in an array. If you have values, you'd have to replace them (could add/remove element).

Also, `array.[]` only observes the length of the array, so even if you had objects, it wouldn't trigger an update unless you observe the specific key.

**Comment by boris-petrov** [comment]
@btecu - actually in our code we used objects inside of the array and it also didn't redraw when using `set`. I just gave here an example with values as it is simpler.

So am I to understand that `set` should *never* be used for the elements of the array, but rather `replace` should?

**Comment by btecu** [comment]
Set is fine. Here is an example where it updates the template and it also triggers the observer:
https://ember-twiddle.com/3e6e1710cc54079fa69c811586b9d950?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs

**Comment by boris-petrov** [comment]
This example is not doing the same thing. You’re not setting the whole element but rather an element’s property. Which I know works. My example is semantically different.

**Comment by pixelhandler** [comment]
@boris-petrov yeah `replace` should be used not `set` to change a member of an array.
