### ISSUE TITLE
Allow disabling EventDispatcher assertion for tagless components / opt out of EventDispatcher

### ISSUE THREAD

**Issue by buschtoens** [emberjs/ember.js#16816]
This assertion is a *major* annoyance when trying to build [container components](https://redux.js.org/basics/usage-with-react#presentational-and-container-components):

> **Assertion Failed:** You can not define a function that handles DOM events in the `<twiddle@component:wrapper-component::ember276>` tagless component since it doesn't have any DOM element.

— [ember-glimmer/lib/component.ts#L571](https://github.com/emberjs/ember.js/blob/2d6579a5637753838e616969904fc2a5eec9e631/packages/ember-glimmer/lib/component.ts#L571-L591)

It is triggered, when you define methods or pass actions named like the [default events](https://guides.emberjs.com/release/components/handling-events/#toc_event-names) or [custom events](https://www.emberjs.com/api/ember/release/classes/Application/properties/customEvents?anchor=customEvents) that are handled by the [`EventDispatcher`](https://github.com/emberjs/ember.js/blob/e76f5f8081d8003c59800fb44f6a9d748dc6b553/packages/ember-views/lib/system/event_dispatcher.js#L17).

```js
// components/wrapper-component/component.js
export default Ember.Component.extend({
  tagName: ''
});
```

```hbs
{{!-- components/wrapper-component/template.hbs --}}
<button onclick={{action click}}>Click me</button>
```

```hbs
{{wrapper-component click=(action "someAction")}}
```

[Ember Twiddle Demo](
https://ember-twiddle.com/bea611d55520ec5607e8cb4e994235d7)

While the assertion is technically correct, I explicitly want to opt out of it for some tagless components, in order to avoid having to use needlessly convoluted / verbose action names like `onClick`.

`EventDispatcher` calls [`handleEvent` on `ViewMixin`](https://github.com/emberjs/ember.js/blob/e52f85e47577b96ebb4cd03c3537433f9fa2bd5b/packages/ember-views/lib/mixins/view_support.js#L441-L451), which delegates to the `_currentState.handleEvent` of the component, which is [`handleEvent` of `has_element` (`in_dom`)](https://github.com/emberjs/ember.js/blob/e52f85e47577b96ebb4cd03c3537433f9fa2bd5b/packages/ember-views/lib/views/states/has_element.js#L17-L28).

This function needs to check, whether the proposed opt-out flag is enabled and immediately `return true` then.

I'd love to submit a PR for this. Will this get accepted?

What should we call the flag? `skipEventDispatcher` or something like this?

**Comment by rwjblue** [comment]
I think that a better longer term solution would be to just avoid the issues completely via a custom component manager.

**Comment by buschtoens** [comment]
I assume you're talking about [RFC #213](https://github.com/emberjs/rfcs/blob/master/text/0213-custom-components.md)?

**Comment by buschtoens** [comment]
You are correct. I'll try to join efforts there.
