### ISSUE TITLE
link-to cannot work properly if wrapped with an element which has bound event listener with ember v3.2+

### ISSUE THREAD

**Issue by nightire** [emberjs/ember.js#16821]
In our apps, we often use following pattern:

``` htmlbars
{{#basic-dropdown as |dropdown|}}
	{{#dropdown.trigger}} Open Menu {{/dropdown.trigger}}

	{{#dropdown.content}}
		<div onclick={{dropdown.actions.close}}>
			{{link-to "Go to Foo" "foo"}}
		</div>
	{{/dropdown.content}}
{{/basic-dropdown}}
```

in this way, you can jump to specific route and close basic-dropdown menu at the same time, otherwise you have to rely on `transitionTo`.

This pattern has always worked until we upgrade ember to v3.2+, we found that click the link-to will cause a full refresh, unless we remove the wrapped `div` element.

I cannot figure out all details, but a little debug/research shows that there will never be a chance to execute `_invoke` method of `link-to` component after clicking.

Since this issue only occurs in versions above v3.2, I consider it as a bug.

**Comment by rwjblue** [comment]
You mention the upgrade to 3.2 but not from what version you were on before? Are we talking 3.1 to 3.2 or some other version range?

Also can you provide a reproduction / demo (repo is totally fine) to make it easier to poke at things?

**Comment by nightire** [comment]
Yes sir, from v3.1 to v3.2.

I was trying to make a demo, but have issues with ember-twiddle, now it fixed:

https://ember-twiddle.com/88216926dc40f7b3af11fe1ec3d9abeb

**Comment by pixelhandler** [comment]
@nightire I'm curious, instead of using `onclick` does using the action helper work?

```
<div {{action dropdown.actions.close}}>
  {{link-to "Go to Foo" "foo"}}
</div>
```

**Comment by nightire** [comment]
@pixelhandler yes, traditional `action` helper did works.

https://ember-twiddle.com/88216926dc40f7b3af11fe1ec3d9abeb

**Comment by pixelhandler** [comment]
@nightire ah cool, yeah I think using `onclick` is for a very specific reason, like you need access to the `event` in the method that handles the click. I think that using `onclick` and assigning a function directly on the dom does bubble so the other thing may be using `return false`. 

This is a great resource on actions/events... https://medium.com/square-corner-blog/deep-dive-on-ember-events-cf684fd3b808

I'll close this for now.
