### ISSUE TITLE
Jquery included twice in vendor.js when upgrading from 2.9.0-beta.1 to 2.10.0

### ISSUE THREAD

**Issue by svkangal** [emberjs/ember.js#16829]
Hi while upgrading from 2.9.0-beta.1 to 2.10.0 for some reason Jquery is getting included twice in vendor.js which is causing some jquery plugins to break as Jquery is reinitialized later. Everything works fine in 2.9. I followed the steps for ember update and below is the only change that I have.
https://github.com/ember-cli/ember-new-output/compare/v2.9.0...v2.10.0

Is there any way to debug ember build process? Also any other known issue that I dont know of? Any pointers will be much appreciated.

**Comment by btecu** [comment]
Any reason to stay on `2.10`?

**Comment by rwjblue** [comment]
I’m not sure what would be causing the specific issue reported (doesn’t seem like any prior issues that I recall from the 2.10 era), but since neither 2.9 nor 2.10 are supported versions I’m not really sure what we can do here...

**Comment by pixelhandler** [comment]
If you'd like to discuss further perhaps reach out in the http://embercommunity.slack.com #-ember-cli channel to chat regarding how to debug the ember build.

**Comment by svkangal** [comment]
@pixelhandler Ye I have updated from 2.10 to 2.12, but I think since we still have bower.json with some packages in it I think thats causing the issue. 
I added  below to remove jquery from ember cli which resolves the issue for now. We can close this ticket, I will debug further and reach on slack for any help.
   ```
vendorFiles: {
      'jquery.js': false
    },
