### ISSUE TITLE
currentURL no longer working in acceptance tests

### ISSUE THREAD

**Issue by dbbk** [emberjs/ember.js#16828]
My app is currently on `v3.1.3`. As soon as I upgrade Ember higher than this, my test suite starts failing. I have a bunch of assertions like this;

```
await click('button[type="submit"]');
await settled();

assert.equal(currentURL(), '/dashboard');
```

However, the `currentURL` helper no longer seems to be updating after awaiting asynchronous things. It's always returning the previous URL. If I pause the test and console log out `currentURL` after a second, it returns the correct URL. So I'm thinking something might have changed with the settled async logic?

I've tried everything to pin down the cause of this error but it's only happening as soon as `ember-source` gets upgraded. Can anyone help?

Thanks

**Comment by pixelhandler** [comment]
@dbbk are you using the new testing setup with Ember? E.g. importing from ember-test helpers like so:

```
import { currentURL } from '@ember/test-helpers';
```
Also are you able to make an https://ember-twiddle.com reproduction of your issue ?

**Comment by dbbk** [comment]
It took a while but I managed to track down the issue to this; https://github.com/emberjs/ember-test-helpers/issues/401

Basically after upgrading my Ember app through `ember-cli-update` it didn't upgrade the underlying test helpers package.
