### ISSUE TITLE
"Attempted to call .send() with the action 'deactivate' on the destroyed object" in tests with Ember 3.2

### ISSUE THREAD

**Issue by pgengler** [emberjs/ember.js#16820]
(I tried to set up an ember-twiddle for this but it's not working once I add the `ember-modal-dialog` and `ember-power-select` addons, so I put together a minimal example in a repo: https://github.com/pgengler/ember-bug-send-deactivate)

**What's happening?**
Tests that passed in Ember 3.0 and 3.1 are now failing with Ember 3.2 with an error like this:
```
Uncaught Error: Assertion Failed: Attempted to call .send() with the action 'deactivate' on the destroyed object '<send-deactivate@component:power-select::ember327>'.
```

**To reproduce**
1) Clone the repo at https://github.com/pgengler/ember-bug-send-deactivate
2) `cd ember-bug-send-deactivate`
3) `yarn install`
4) `ember test`

The tests will fail with an error similar to the one above. If you change the version of `ember-source` to `~3.0.0` or `~3.1.0` and repeat steps 3 & 4, then everything passes.

The example (like the real app that's having this problem) has a modal dialog (from `ember-modal-dialog`) that contains a typeahead from `ember-power-select-typeahead`; when something is selected in the power-select-typeahead, the modal is closed.

**Comment by rwjblue** [comment]
Seems similar to https://github.com/emberjs/ember.js/issues/16778

**Comment by kategengler** [comment]
Also happening with canary https://pgengler-ember-bug-send-deactivate.glitch.me/tests

**Comment by FilmKnurd** [comment]
I am experiencing this as well.  All my acceptance tests are failing because asserts are running before awaited route transitions complete, or the app is being destroyed and Liquid-fire sends a notification to it's container.

**Comment by pixelhandler** [comment]
@pgengler did the workaround that Robert Jackson mentioned help? See https://github.com/emberjs/ember.js/issues/16778#issuecomment-400327053

**Comment by pgengler** [comment]
It seems like the various addons where I was hitting the problem have implemented the workaround (https://github.com/cibernox/ember-power-select/pull/1144, https://github.com/yapplabs/ember-modal-dialog/pull/255, https://github.com/sir-dunxalot/ember-tooltips/pull/258) so I've stopped hitting this problem any more.

**Comment by pixelhandler** [comment]
@pgengler I'll close this for now, if you continue to hit this issue feel free to reopen, have a great weekend :)
