### ISSUE TITLE
Rendering <button> in each loop breaks application

### ISSUE THREAD

**Issue by GendelfLugansk** [emberjs/ember.js#16826]
In ember 3.3.0 following template breaks application:

```
{{#each buttons as |button|}}
  <button>{{button}}</button>
{{/each}}
```

`buttons` is a simple array. In console I can see `Uncaught Error: unreachable`. This error does not happen with other tags (i.e. <input> works fine) and does not happen on ember 3.2.2

Repository with demonstration: https://github.com/GendelfLugansk/ember-rendering-bug

**Comment by nightire** [comment]
Yeah, confirmed, we've encountered same error after upgrade from 3.2.2 to 3.3.0

**Comment by rwjblue** [comment]
I'm somewhat surprised that this broke in 3.3, but I would have expected it to break in 3.4 (due to the custom components feature).

I'll try to dig in to confirm if it is related...

**Comment by rwjblue** [comment]
Changing to:

```hbs
{{#each buttons as |text|}}
  <button>{{text}}</button>
{{/each}}
```

Should resolve the issue (assuming that my guess RE: angle bracket invocation feature is correct).

**Comment by GendelfLugansk** [comment]
@rwjblue yes, changing from `button` to `text` or `btn` helps. Thank you for explanations.

**Comment by nfc036** [comment]
Just an informational message: I had the same problem with {{#each model as |img|}}. Changing img to i.e. "foto" resolves this error. Is this breaking change (ember-source 3.2.2 => 3.3.0) documented somewhere?

**Comment by nightire** [comment]
Just another information: this issue tricks me a lot, the key is: don't use html tag name as the `as` part of `each` helper.

``` htmlbars
{{#each apples as |a|}}
  {{a.name}} {{!-- don't, because `a` is a html tag name}}
{{/each}}

{{#each apples as |apple|}}
  {{apple.name}} {{!-- this is fine}}
{{/each}}
```

I'm not sure if it will be a breaking change, but I hope not.

**Comment by GendelfLugansk** [comment]
@nightire as I can tell, we can use html tag name in `as` part if that html tag is not used inside block. I also think it's not just for `each` but for any block helper that yields something, including our own components.

**Comment by rwjblue** [comment]
This change should **not** have happened during 3.3, and we will try to figure out why it did (and fix it). However, we _do_ intend for it to land as part of 3.4 (along with support for linting in applications as a general guide).

**Comment by hoboman313** [comment]
Should we be expecting this to be patched in 3.3.1?

**Comment by rwjblue** [comment]
> Is this considered a breaking change?

Yes, it is a breaking change and we are working on the fix.

> I'm also a little confused by the RFC as to whether this is allowed (and supposed to work), or allowed at build-time (but breaks at run-time).

The current behavior matches what the RFC stated (essentially that a block param named `button` + `<button></button>` in the blocks template, would assume that the block param was a yielded closure component and attempt to render it as such), but based on feedback (here and in other issues) we determined that the result is definitely something we consider a breaking change.

The current plan (after discussing with the core team on 2018-07-20) is:

* Ensure that all block params that "shadow" normal HTML elements inside their blocks, continue to render the HTML element (and do not assume they should "invoke" a yielded component).
* Issue a deprecation when this scenario is detected (with `until: '4.0.0'`)
* Ensure the linter is setup for newly generated Ember apps that will lint against using confusing block param names (where the block param _could be_ an HTML element name, and that HTML element is invoked in the blocks template).
* Backport these fixes to Ember 3.3

**Comment by nerdybeast** [comment]
I have been having this same issue for the last couple of days as well trying to figure out what was going on:
```
<select>
	{{#each options as |option|}} <!--I see now the issue is I named this "option" a valid html tag -->
		<option value="{{option.id}}">{{option.name}}</option>
	{{/each}}
</select>
```

Changing to this fixed the problem for as well:
```
<select>
	{{#each options as |opt|}} <!-- Renamed to "opt" -->
		<option value="{{opt.id}}">{{opt.name}}</option>
	{{/each}}
</select>
```

Just throwing this out there for more documentation on the issue.

**Comment by rwjblue** [comment]
> Just throwing this out there for more documentation on the issue.

👍 thanks for that (and sorry for the issue)

**Comment by cafreeman** [comment]
@rwjblue I'm not actually ables to find evidence of the `no-shadowed-elements` template lint rule in https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rules.md

Does it exist somewhere else?

**Comment by nlfurniss** [comment]
@cafreeman it's not listed there (though it should be), but the rule is [here](https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/rules/lint-no-shadowed-elements.js)

**Comment by cafreeman** [comment]
Ah, can't believe I missed that. Thank you!

**Comment by vothaison** [comment]
Hi everyone,

I am trying Ember 3.4.1;
It appears that only tag name li cannot be used in #each yielded block (2 vertical bars).

Here is my experiment:
I get this list to html tag from w3c 

> ['a', 'abbr', 'acronym', 'address', 'applet', 'area', 'article', 'aside', 'audio', 'b', 'base', 'basefont', 'bdi', 'bdo', 'big', 'blockquote', 'body', 'br', 'button', 'canvas', 'caption', 'center', 'cite', 'code', 'col', 'colgroup', 'datalist', 'dd', 'del', 'details', 'dfn', 'dialog', 'dir', 'div', 'dl', 'dt', 'em', 'embed', 'fieldset', 'figcaption', 'figure', 'font', 'footer', 'form', 'frame', 'frameset', 'h1', 'h2', 'h3', 'h4', 'head', 'header', 'hr', 'html', 'i', 'iframe', 'img', 'input', 'ins', 'kbd', 'keygen', 'label', 'legend', 'li', 'link', 'main', 'map', 'mark', 'menu', 'menuitem', 'meta', 'meter', 'nav', 'noframes', 'noscript', 'object', 'ol', 'optgroup', 'option', 'output', 'p', 'param', 'picture', 'pre', 'progress', 'q', 'rp', 'rt', 'ruby', 's', 'samp', 'script', 'section', 'select', 'small', 'source', 'span', 'strike', 'strong', 'style', 'sub', 'summary', 'sup', 'table', 'tbody', 'td', 'textarea', 'tfoot', 'th', 'thead', 'time', 'title', 'tr', 'track', 'tt', 'u', 'ul', 'var', 'video', 'wbr']

I put that in an Ember controller, write an hbs template to render that list  

```
<h1 class="login-title">TEST TAGS</h1>
    &#x3C;h1 class=&#x22;login-title&#x22;&#x3E;TEST TAGS&#x3C;/h1&#x3E;
    <ul>
      {{#each htmlTags as |htmlTag|}}
      <li style="list-style:none;">
        <div class="highlight">
          <pre>
          <code class="handlebars">
              &#x3C;h3&#x3E;tag {{htmlTag}}&#x3C;/h3&#x3E;
              &#x3C;ul&#x3E;
              \{{#each list as |{{htmlTag}}|}}
              &#x3C;li&#x3E;
              \{{ {{htmlTag}} }}
              &#x3C;/li&#x3E;
              \{{/each}}
              &#x3C;/ul&#x3E;
            </code>
          </pre>
        </div>
      </li>
      {{/each}}
    </ul>
    \{{outlet}}
```

That render another hbs content
(the `list `is an array [1,2,3])

>               <h1 class="login-title">TEST TAGS</h1>
>           
>               <h3>tag a</h3>
>               <ul>
>               {{#each list as |a|}}
>               <li>
>               {{ a }}
>               </li>
>               {{/each}}
>               </ul>
>           
>               <h3>tag abbr</h3>
>               <ul>
>               {{#each list as |abbr|}}
>               <li>
>               {{ abbr }}
>               </li>
>               {{/each}}
>               </ul>
> 
>               ( ... ... ... )
> 
>               <h3>tag wbr</h3>
>               <ul>
>               {{#each list as |wbr|}}
>               <li>
>               {{ wbr }}
>               </li>
>               {{/each}}
>               </ul>   


I copy that to another Ember hbs template, and the page rendering stops at li tag, with error:

> Uncaught Error: unreachable
>     at unreachable (util.js:16)
>     at Object.evaluate (runtime.js:1128)
>     at AppendOpcodes.evaluate (runtime.js:46)
>     at LowLevelVM.evaluateSyscall (runtime.js:2896)
>     at LowLevelVM.evaluateInner (runtime.js:2868)
>     at LowLevelVM.evaluateOuter (runtime.js:2860)
>     at VM.next (runtime.js:4788)
>     at TemplateIteratorImpl.next (runtime.js:4880)
>     at RootState.render (ember-glimmer.js:4070)
>     at TransactionRunner.runInTransaction (ember-metal.js:406)

I remove li tag from the array, and it renders all the way through without error.

I am not sure if the my experiment is correct. So, thanks in advance for all advices.
We are using "li" as hbs name in a lot of places (well, because it is "list item"). Hope Ember Team can fix that.

**Comment by robclancy** [comment]
The `no-shadowed-elements` rule isn't very descriptive, ended up here thinking the rule was another issue just with formatting (in vscode with the ember addon there is no difference between formatting issues and errors, I think with the linter too?).

My question is will this have a better error in future? Not everyone will be running the linter and I can imagine coworkers running into this and not knowing what's going on when there error isn't useful.

**Comment by rwjblue** [comment]
Ya, I mentioned above that we consider this a bug and totally want to 
make the ergonomics much better (e.g. issue a warning that has a helpful 
message instead of error).

**Comment by samselikoff** [comment]
I'm actually confused why this is ambiguous:

```hbs
{{#each options as |option|}}
  <option value={{option.value}}>{{option.label}}</option>
{{/each}}
```

Don't angle-bracket components need to be invoked with a capital letter?

**Comment by rwjblue** [comment]
> Don't angle-bracket components need to be invoked with a capital letter?

No, see [the dynamic invocation section](https://github.com/emberjs/rfcs/blob/master/text/0311-angle-bracket-invocation.md#dynamic-invocations) of the RFC for background.

**Comment by pzuraq** [comment]
Can anyone reproduce this on the latest stable release of Ember?

**Comment by GendelfLugansk** [comment]
@pzuraq yes, I can reproduce this error using 3.8.0

**Comment by Techn1x** [comment]
Just to make things incredibly confusing, this can happen (it happened to me)
Running Ember 3.4

```handlebars
{{#each someArray as |item i|}}
  {{#if (gt i 0)}}
    {{fa-icon item.icon}}
  {{/if}}
{{/each}}
```

Even though I wasn't using an `<i>`, the `{{fa-icon}}` component (from ember font awesome) creates one, and this caused the fun `Uncaught Error: unreachable` error

Also, this isn't caught by ember-template-lint's `no-shadowed-elements`, making it harder to find and diagnose :(

**Comment by rwjblue** [comment]
I can absolutely see how that would be pretty confusing. Internally `ember-font-awesome` modifies the output template and replaces the `{{fa-icon` component invocation directly with `<i>` which is the thing that caused the error you hit.

RE: this not being caught by `no-shadowed-elements`, I think we could do a bit of work in the ember-font-awesome AST transform to ensure that this specific scenario doesn't exist (basically error or automatically rewrite any block params named `i` while transpiling).

**Comment by lifeart** [comment]
@Techn1x. @rwjblue  Icon name cannot be dynamic in `fa-icon` (https://github.com/FortAwesome/ember-fontawesome/blob/master/lib/ast-transform.js#L37)

**Comment by robclancy** [comment]
We have dynamic `fa-icon` all over the place, it does work. Pretty sure what you linked will have had ember/glimmer already turn it into a string. Otherwise there is no chance we would even use the package.

**Comment by Techn1x** [comment]
Sorry - whether or not dynamic icon names work, that's just an issue with the example I gave, but the point still stands.

The basis of that particular example (using `i` as a block param, and `fa-icon` in the inner block) is used in a non-trivial amount of places throughout my codebase - I ended up renaming all block param uses of `i` to `index` to be sure

Also worth noting there's two ember font awesome projects going, depending on the FA version you're using. They probably have differences in what they support etc.
https://github.com/martndemus/ember-font-awesome
https://github.com/FortAwesome/ember-fontawesome

**Comment by Caltor** [comment]
Is this issue still being looked at? it appears to be nearly a year since it was reported but I encountered the 

> Uncaught Error: unreachable

message today with the following code in Ember v3.4.4 (which I believe is a current LTS version).

```javascript
<select>
    {{#each options as |option|}}
        <option value={{option.id}}>{{option.name}}</option>
    {{/each}}
</select>
```

P.S. I've since changed the code to:
```javascript
<select>
    {{#each options as |opt|}}
        <option value={{opt.id}}>{{opt.name}}</option>
    {{/each}}
</select>
```
which obviously works.

**Comment by lifeart** [comment]
@Caltor latest LTS - 3.8 https://emberjs.com/releases/

**Comment by Caltor** [comment]
@lifeart it also says 3.4 bugfixes until May 2019.

**Comment by rwjblue** [comment]
3.4 will only be receiving security fixes at this point, 3.8 will receive bugfixes

**Comment by Caltor** [comment]
@rwjblue So LTS actually means "we ignore the bug until the LTS period has elapsed"? Interesting. I would have thought bugs spotted within the LTS period would be fixed. Still I understand it's a community project etc etc and it's no big deal to workaround.

**Comment by lifeart** [comment]
@Caltor https://github.com/emberjs/ember.js/issues/16826#issuecomment-405654150 there is workaround for this case, and workaround pretty clear and it's following official linting rules https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-shadowed-elements.md

**Comment by rwjblue** [comment]
@Caltor - I am sorry that we didn't get this fixed for the LTS. 😩

The main issues here are that it has turned out to be gnarly to fix (I have spent a few hours on it), and in nearly all cases updating to avoid the conflict makes your code better and easier to understand which generally makes fixing this particular bug a bit lower priority than others that are actually blocking folks.

**Comment by Caltor** [comment]
@rwjblue No worries! If the linter picks it up then that is good. It is only a result of bad coding anyway.

**Comment by BobrImperator** [comment]
This issue also happens when a yielded components hash has the same name as helper, and linter doesn't catch that.

```
<AngleTable as |t|>
  <t.header />
  {{t "unreachable"}}
</AngleTable>
```

**Comment by pzuraq** [comment]
@BobrImperator I'm not sure that problem is something that is possible to catch ahead of time, and it should have always been a failure because local variables have always taken precedence over globals. The reason we can't catch it ahead of time is similar to why you can't lint against something like this in JS:

```js
function foo() {

}

function bar(foo = 'a string') {
  foo(); // Error: foo is not a function
}
```

While it's reasonable to assume that this is a shadowing mistake on the developer's part, because of JS's dynamic nature, we can't know for sure that `foo` is _not_ a function when being passed into `bar`. If we were using a typed language instead, then we may be able to, but unfortunately I don't think we can currently.

**Comment by BobrImperator** [comment]
I kind of expressed myself badly, I don't really expect this to be caught beforehand.
But if I remember correctly, there's a compile error for `action` helper when it's overwritten.
I don't remember the exact syntax, but it should be something like this, similar but with `action`. 
```hbs
<AngleTable as |action|>
  <t.header />
  {{action "unreachable"}}
</AngleTable>
```
it could be a different case though

**Comment by cah-briangantzler** [comment]
FYI just spent a couple hours on debugging til I finally googled and found this issue (was using option and the yielded name) so its still out there on 3.15

**Comment by houfeng0923** [comment]
in ember 3.16.6, it still happen in ios safari.

**Comment by locks** [comment]
I just went through all of the comments once again and I believe the linting rule and the current error message are sufficient to steer the developer in the right direction. Given that it also seems like fixing this issue might open up other wholes in the template compilation, I am closing the issue.
