### ISSUE TITLE
Packages missing from list on Ember API doc site for v3.3

### ISSUE THREAD

**Issue by pgengler** [emberjs/ember.js#16837]
A number of packages that show up for v3.2 are missing when v3.3 is selected on the Ember API doc site (https://www.emberjs.com/api/ember/release).

3.3:
<img width="332" alt="screen shot 2018-07-20 at 2 00 15 pm" src="https://user-images.githubusercontent.com/193435/43017753-56b16740-8c25-11e8-904b-fd80104b6ec9.png">

3.2:
<img width="329" alt="screen shot 2018-07-20 at 2 00 22 pm" src="https://user-images.githubusercontent.com/193435/43017756-59f4b204-8c25-11e8-913f-2f294746af9f.png">

It seems like maybe some of these have been marked as "private" in 3.3:
<img width="452" alt="screen shot 2018-07-20 at 2 01 26 pm" src="https://user-images.githubusercontent.com/193435/43017791-74031226-8c25-11e8-9994-8ce242edc98d.png">

**Comment by toddjordan** [comment]
fixed by #16836

**Comment by pixelhandler** [comment]
Closing looks like this is resolved now
