### ISSUE TITLE
"index.js.map" referenced in ember.prod.js, but it is not included in ember-source

### ISSUE THREAD

**Issue by pieter-v** [emberjs/ember.js#16844]
ember: 3.3.0
ember-cli: 3.3.0

create a new ember project
```
 ember new abc --yarn --skip-git
```
modify `ember-cli-build.js` to generate sourcemaps:
```js
  let app = new EmberApp(defaults, {
    sourcemaps: {
      enabled: true
    },
  });
```
A production build gives the following warning:
```
[WARN] (broccoli-uglify-sourcemap) "index.js.map" referenced in "assets/vendor.js" could not be found
```
The `index.js.map` is referenced in `ember.prod.js`

**Comment by pixelhandler** [comment]
@pieter-v perhaps this should be reported on the ember-cli project, https://github.com/ember-cli/ember-cli/issues

**Comment by pieter-v** [comment]
Reported as https://github.com/ember-cli/ember-cli/issues/7944
This issue can be closed.

Thanks

**Comment by pixelhandler** [comment]
@Turbo87 got it, thanks!

**Comment by Turbo87** [comment]
this might have been fixed by https://github.com/emberjs/ember.js/pull/17128 too. not released yet though.

**Comment by pixelhandler** [comment]
@pieter-v is this fixed in the current release of Ember?

**Comment by rwjblue** [comment]
I believe it is, closing for now (happy to reopen though)...
