### ISSUE TITLE
Ruby-gems is a bit behind

### ISSUE THREAD

**Issue by thec0keman** [emberjs/ember.js#16852]
Latest version on rubygems is 3.0.0-beta.2

Would it be possible to get 3.3 released?

Thanks!

**Comment by btecu** [comment]
Is the single package (Bower type) dead?
Meaning, you have to use the npm package via ember-cli now as opposed to getting a single .js file.

**Comment by rwjblue** [comment]
As of Ember 3.0.0 we no longer publish to rubygems, bower, s3, etc. Using `ember-source` from the npm registry is the approved mechanism for consuming...

**Comment by m-harnish** [comment]
Is there any type of a migration guide for transitioning a Rails app that was using the ember-source gem to use the npm module? Thanks!
