### ISSUE TITLE
[QUEST] Is it ok to listen to incoming "attrs" to re-compute computed property?

### ISSUE THREAD

**Issue by homeslicesolutions** [emberjs/ember.js#16855]
I found a trick that made my code lighter that re-invokes my computed function without the need of using `didReceiveAttrs` and setting extra variables in the scope of the component.  The trick is something like this:

```
  currentPage: computed('attrs.{offset},pageArray', function currentPage() {
    return get(this, 'pageArray').find(page => (
      isEqual(
        get(page, 'offset'),
        get(this, 'offset'),
      )
    ));
  }),
```

What this does is that the computed property will update and the component will refresh every time an attribute has changed outside of the injected.  Is there any bad repercussions on doing this?

**Comment by pixelhandler** [comment]
@homeslicesolutions Perhaps ask your question on the forum or in the ember community slack. Our use of the Issue tracker is main for bugs. I'll close this for now, perhaps as on the form or in slack, see https://www.emberjs.com/community
