### ISSUE TITLE
RouterService: rootURL is handled inconsistently

### ISSUE THREAD

**Issue by buschtoens** [emberjs/ember.js#16851]
It seems like the [`rootURL`](https://www.emberjs.com/api/ember/3.3/classes/EmberRouter/properties/rootURL?anchor=rootURL) property is handled inconsistently.

For example, [`currentURL`](https://www.emberjs.com/api/ember/3.3/classes/RouterService/properties/currentURL?anchor=currentURL) and [`urlFor(currentRouteName)`](https://www.emberjs.com/api/ember/3.3/classes/RouterService/methods?anchor=urlFor) return different results. The former one excludes the [`rootURL`](https://www.emberjs.com/api/ember/3.3/classes/RouterService/properties/rootURL?anchor=rootURL), while the latter one includes it:

```js
const Router = EmberRouter.extend({
  location: 'none',
  rootURL: '/some/prefix/'
});
```

```js
export default Controller.extend({
  router: service(),
  
  urlFor: computed(function() {
    return this.router.urlFor(this.router.currentRouteName);
  })
});
```

```hbs
{{router.rootURL}}:          '/some/prefix/'
{{router.currentRouteName}}: 'index'
{{router.currentURL}}:       ''
{{urlFor}}:                  '/some/prefix/'
```

In addition to that, [`transitionTo`](https://www.emberjs.com/api/ember/3.3/classes/RouterService/methods?anchor=transitionTo) and [`replaceWith`](https://www.emberjs.com/api/ember/3.3/classes/RouterService/methods?anchor=replaceWith) _do not_ accept the IMHO "correct" URL that includes the `/some/prefix/` and will throw an error if called like:

```js
this.router.transitionTo('/some/prefix/');
```

But will work fine for:

```js
this.router.transitionTo('/');
this.router.transitionTo('');
```

[Ember Twiddle](https://ember-twiddle.com/69dd1a79a3d8d8301d00c89370c347ef?openFiles=templates.application.hbs%2C)

**Comment by pixelhandler** [comment]
@buschtoens I believe that the original use case for using `rootUrl` is for an application that that is not hosted at the root folder on a specific domain, e.g. https://abc.xyz/some/prefix/here-lives-ember-app, so the Ember app's transitions are only concerned with the path to the route in the Ember app. And the transitions to not track the path to the ember app specifically. 

I'm pretty sure what you have described is the intended design.

Use `this.router.transitionTo('/');` not `this.router.transitionTo('/some/prefix/');`

**Comment by rwjblue** [comment]
I agree with @pixelhandler here. `urlFor` is attempting to provide you the URL you'd see in the location bar of your browser, whereas `currentURL` is attempting to provide you with the "in app URL".

@buschtoens - I think this is pretty confusing in the documentation, and would **love** help figuring out how we can make the docs here better...

**Comment by rwjblue** [comment]
Closing for now, but would still definitely welcome better docs for this confusing area...
