### ISSUE TITLE
ES6 constructor.name is not unique in production build

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/ember.js#16856]
I'm using `constructor.name` as a hash key to store class metadata from a property decorator.

When I compile for production all the classes have the same `constructor.name` of 'o'. Shouldn't this name be at least guaranteed unique, if not the actual classname?

**Comment by krisselden** [comment]
It's set by the browser to the variable name. When using Ember.Object.extend() this is going to be `Class` in dev and minified otherwise.

**Comment by krisselden** [comment]
If you want a name you need to do `class MyClass extends Ember.Object {}` still not going to be guaranteed to be unique, I would suggest you use a Map keyed on the constructor function.

**Comment by bartocc** [comment]
oh an BTW, I created a discuss topic before hitting this github issue

https://discuss.emberjs.com/t/constructor-name-behaves-differently-in-dev-and-prod-builds-for-models-defined-with-the-es6-class-syntax/15572
