### ISSUE TITLE
broken willChange ArrayObserver for ArrayProxy

### ISSUE THREAD

**Issue by mattraydub** [emberjs/ember.js#16862]
Not certain if this is a bug or is intended. We used to be on 2.17, and when observing (using `addArrayObserver`). The proxy would enter the willChange method with the array before it had actually been changed. Now it occurs after the change. See screenshots below with console logs shows what I was seeing vs now seeing.

btw, I will continue to dig through the code changes to see if this was intended, but wanted to get this out there in case there is a quick and easy answer.

My goal was/is to be able to see when a relationship (which is an ArrayProxy) is changing, Id like to know exactly what record was removed.

Before (version 2.17.0)

<img width="660" alt="pastedgraphic-3" src="https://user-images.githubusercontent.com/6732051/43662353-74f97710-971a-11e8-835d-53591efc60fe.png">

Now (version 3.3.1)

<img width="655" alt="pastedgraphic-4" src="https://user-images.githubusercontent.com/6732051/43662365-835a3c5e-971a-11e8-8df5-41b3fda582ff.png">

**Comment by mattraydub** [comment]
I found this commit
https://github.com/emberjs/ember.js/commit/2ddcbc930c035080b854603d250cd754630ba0e0

But why? Is there a way to find more explanation? This was handy functionality before, that no longer exists. And you can still do it properly on a regular array, just not an ArrayProxy, which I thought should act like an Array with some sugar on top.

:)

Thanks for any help or suggestions.

**Comment by krisselden** [comment]
The arrayWillChange happens before the proxy changes not the proxy backing array in content, you are supposed to not use content but use objectAt on the proxy. In general it is a mistake to observe one thing and make assumptions regarding another thing changing with it.

**Comment by krisselden** [comment]
Though looking more closely that at your example, this does seem to be a bug, the proxy is supposed to cache the last observed state before notifying will change. Using a proxy observer to know something about a different thing changing is not expected to keep working but the proxy itself should be keeping the last observed state. @mmun

**Comment by krisselden** [comment]
Actually looking at it closer, you never accessed the proxy, so no state had ever been observed by the proxy, so I'm surprised it even fired a change event.

**Comment by krisselden** [comment]
Here is an example of what is under test in ember's test suite.

https://ember-array-proxy-issue.glitch.me/

The issue is if you don't log() the proxy, it still fires a change event, but with the wrong info. Ideally would not fire any change event since the proxy has never been used, this would match the behavior of computed properties.

**Comment by mattraydub** [comment]
Thanks for the attention @krisselden 

In my actual environment my proxy is in a template so it is being observed, so the little test I had written wasn't quite right, as you pointed out I hadn't grabbed the proxy.toArray yet. However, I still have an issue in that, if I run your snippet of JS in my environment it still does not work. For some reason my toArray is returning a different result, and I have narrowed it down to that when in the proxy.willUpdate, the proxy now has a length of 2 instead of 3.

my proxy in willUpdate:

```js
{"content":["one","three"],"_objectsDirtyIndex":-1,"_objects":["one","two","three"],"_lengthDirty":true,"_length":0,"_arrangedContent":["one","three"],"length":2}
```

your proxy in willUpdate:

```js
{"content":["one","three"],"_objectsDirtyIndex":-1,"_objects":["one","two","three"],"_lengthDirty":false,"_length":3,"_arrangedContent":["one","three"]}
```

_length, _lengthDirty, and length are all different 

I will keep digging in my code to find out why my length is not providing the same value that your environment is.

**Comment by mattraydub** [comment]
sorry, no bug

I found what library we are using that is changing the length property on the ArrayProxy

@mmpestorich when I removed the lodash files from our app the `Ember.ArrayProxy` works as expected. Somewhere we must be overriding the length property that gets defined by the `Ember.ArrayProxy`
