### ISSUE TITLE
dist/ember.prod.js has multiple sourcemap declarations, breaking sourcemap build

### ISSUE THREAD

**Issue by kmoe** [emberjs/ember.js#16881]
## Summary

The current npm version of `ember-source`, 3.3.1 (**2018-09-07 update: issue remains in 3.4.0**), contains the file `dist/ember.prod.js`. This file contains multiple declarations of the form:

```
    //# sourceMappingURL=FILENAME.js.map
```

According to the [source map spec](https://sourcemaps.info/spec.html#h.lmz475t4mvbx), there should only be one line of this form, at the end of the file.

## Impact

This means any `vendor.js` file built with ember-cli will not have a valid  sourcemap file.

Please see https://github.com/emberjs/ember.js/issues/16844 for the error (the bug was erroneously closed as the issue was assumed to be with ember-cli, not ember-source).

## Cause

Including multiple `sourceMappingURL` declarations in `ember.prod.js` causes issues for fast-sourcemap-concat ([/lib/source-map.js#L91](https://github.com/ef4/fast-sourcemap-concat/blob/master/lib/source-map.js#L91)), since the `source-map-url` library only removes the first one.

This is valid behaviour since there should only be one `sourceMappingURL` declaration per file.

## Suggested fix

Remove the extra `sourceMappingURL` lines from `dist/ember.prod.js`.

## References and similar issues

https://github.com/broccolijs/broccoli-concat/issues/123
https://github.com/ef4/fast-sourcemap-concat/pull/54
https://github.com/ember-cli/ember-fetch/pull/120

**Comment by buschtoens** [comment]
Bug is still present in latest `v3.5.0` release: https://unpkg.com/ember-source@3.5.0/dist/ember.prod.js

This effectively prevents us from upgrading, because our Sentry stack traces for `vendor.js` are unparseable. I would love to help fixing this, but I know too little about Ember's internal build pipeline. If I could get some pointers of potential sites of interest, I'll start investigating. 🕵️

**Comment by Turbo87** [comment]
0af67912566b437cd96305af342b7be54fe98097 is the first bad commit
commit 0af67912566b437cd96305af342b7be54fe98097
Author: Robert Jackson <rjackson@linkedin.com>
Date:   Thu Apr 12 13:20:38 2018 -0400

    Move error handling code up into standalone package.

    This simplifies a possible cycle between ember-metal and @ember/runloop.

    Also migrate to typescript...

:040000 040000 c74895a3e2f2d81687e46f34dfe066d267eabc24 b9b5d25fcd8b797423a4a1eaabc3cfd2aacda3ad M	packages

**Comment by Turbo87** [comment]
a day earlier https://github.com/emberjs/ember.js/pull/16482 was merged, which is likely the actual cause of this issue 🤔
