### ISSUE TITLE
in-element helper not working

### ISSUE THREAD

**Issue by ashrafmajdee** [emberjs/ember.js#16886]
in-element helper is throwing the following error

> Uncaught TypeError: parent.insertBefore is not a function

i'm using ember version 3.3.1

**Comment by ashrafmajdee** [comment]
finally got this to work by passing the element from a computed property.

**Comment by btecu** [comment]
Indeed, I brought up this point in the RFC https://github.com/emberjs/rfcs/pull/287 but it was decided to go forward anyway. Most users will get tripped by this, since almost always you want to pass a selector, not a node.

**Comment by ashrafmajdee** [comment]
for me it only works when the element is returned from a computed property. if it's not from a computed property it doesn't work, don't know why.
