### ISSUE TITLE
Memory leak in ember-2.18.2 upon attaching action handler in a component

### ISSUE THREAD

**Issue by dnalagatla** [emberjs/ember.js#16890]
We noticed the memory leak in ember-2.18.2 upon attaching attaching action handler in component. 

## Repro Steps
* Created a simple component `my-button` and correcponding template.
* Template has click action handler defined.  
* Created integration test for the component.
* run `ember exam --server --filter="Integration | Component | my button"`
* Test pass, expected.
* In chrome Dev tools Memory heapshot notice `Container` class gets retained. 
  Not expected, as the `container` is expected to be destroy after the completion of the test.

Here is the Repository of sample app for repro - https://github.com/dnalagatla/ember-2.18.2-memory-leak

## Root cause
Glimmer runtime.js is retaining a reference to the Container instance. 

We believe the this `references` object in PositionalArguments, retains the reference to Container after test is finished.
https://github.com/glimmerjs/glimmer-vm/blob/v0.25.6/packages/%40glimmer/runtime/lib/vm/arguments.ts#L142

The instance of PositionalArguments is creates here:
https://github.com/glimmerjs/glimmer-vm/blob/v0.25.6/packages/%40glimmer/runtime/lib/vm/arguments.ts#L72

**Comment by pixelhandler** [comment]
@dnalagatla just curious is there any difference in behavior if you change:

```
<button onclick={{action "clicked"}}>Click me</button>
```

To

```
<button {{action "clicked"}}>Click me</button>
```

**Comment by dnalagatla** [comment]
changing to this format `<button {{action "clicked"}}>Click me</button>` had no effect on the behavior. I still noticed the leak.

**Comment by rwjblue** [comment]
I think this has been addressed, @dnalagatla can you confirm?

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/issues/16152#issuecomment-445790457 (an extremely similar bug report) mentioned that it was fixed in Ember 3.5.0. I suspect that means this is also fixed, but someone needs to verify by running through the repro steps...

**Comment by dnalagatla** [comment]
This bug is specific to Ember 2.18 version only. I verified in 3.5.0 version was not able to repro memory leak reported here. I will close this ticket. Thank you for looking into this.

**Comment by ryanhollister** [comment]
@rwjblue sorry to dig up a closed ticket but was wondering if you knew of the specific change that solved this memory leak? Running into this issue in our app and are a bit of a ways away from getting to 3.5.
