### ISSUE TITLE
Something about dynamic segments problem ?

### ISSUE THREAD

**Issue by SketchK** [emberjs/ember.js#16891]
Hello, I am a new starter in ember.js, and recently i get a problem like this

`Assertion Failed: You attempted to define a `{{link-to "cryptid"}}` but did not pass the parameters required for generating its dynamic segments. More context objects were passed than there are dynamic segments for the route: cryptid`

I will show my code below and **Anyone can explain what's wrong and how to fix it?**
My Ember.js version is 3.3

in models(cryptid.js)
```
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  cryptidType: DS.attr('string'),
  profileImg: DS.attr('string'),
  sightings: DS.hasMany('sighting')
});
```
in routes(crypteds.js)

```
import Route from '@ember/routing/route';

export default Route.extend({
  model(){
    return this.store.findAll('cryptid');
  }
});
```

in cryptids.hbs

```
<div class="row">
  {{#each model as |cryptid|}}
    <div class="col-xs-12 col-sm-3 text-center">
      <div class="media well">
        {{#link-to 'cryptid' cryptid.id}}
          <img class="media-object thumbnail" src="{{if cryptid.profileImg cryptid.profileImg 'assets/images/cryptids/blank_th.png'}}" alt="{{cryptid.name}}" width="100%" height="100%">
        {{/link-to}}
        <div class="caption">
          <h3>{{cryptid.name}}</h3>
        </div>
      </div>
    </div>
    {{else}}
      <div class="jumbotron">
        <h1>No Creatures</h1>
      </div>
  {{/each}}
</div>
```

in router.js
```
Router.map(function() {
  this.route('sightings', function() {
    this.route('new');
  });
  this.route('sighting', function() {
    this.route('edit');
  });
  this.route('cryptids');
  this.route('cryptid'), {path: 'cryptids/:cryptid_id'};
  this.route('witnesses');
  this.route('witness');
});

```

**Comment by nightire** [comment]
@SketchK Can you confirm that `cryptid.id` actually exists?

In addition, usage questions should not be posted here as development issues, welcome to ember slack channel or ember discuss community, you can find them here: https://emberjs.com/community/

And plus, do you use QQ? there's a local group, welcome to join us: 242650456

**Comment by SketchK** [comment]
@nightire Thank you very much! I will join the local group soon !
and I finally find my problem is round brackets 
code should be like this

    this.route('cryptid', {path: 'cryptids/:cryptid_id'});

but i wrote like this 

    this.route('cryptid'), {path: 'cryptids/:cryptid_id'};

**Comment by SketchK** [comment]
@nightire 242650456 means QQ Group Number? Why i use it to search and find nothing?
