### ISSUE TITLE
Dotted object lookup changed from 3.1 to 3.2

### ISSUE THREAD

**Issue by mydea** [emberjs/ember.js#16901]
Until Ember 3.1, `Ember.get()` would prefer nested objects over strings with dots in them:

```js
let obj = {
  'test.dotted': 'string object',
  test: {
    dotted: 'nested object'
  }
};
    
Ember.get(obj, 'test.dotted'); // -> 'nested object'
```

However, starting with 3.2, it would return `string object`.
I don't think this is necessarily a great problem, but it broke a test of ours.

I made an Ember Twiddle showing the change:
https://ember-twiddle.com/ad175792735143d1fd1260f271dbb158?openFiles=controllers.application.js%2C

**Comment by rwjblue** [comment]
That is definitely unfortunate that it broke things for you, I'm sorry about that. I do think that the current (new in 3.1) is actually correct though.

I'm going to close this for now, but it will hopefully be a nice googling point for any one else bitten by this change...
