### ISSUE TITLE
Exception on partials used as templateName

### ISSUE THREAD

**Issue by adrigzr** [emberjs/ember.js#16915]
Repro: [twiddle](https://ember-twiddle.com/c3c7d65a7f9e51992a32332581b24def)

Steps:
- Open devtools.
- Hit Route 2.
- Hit Route 1.
- Look console for the exception.

```
Uncaught TypeError: Cannot read property 'model' of null
```

Broken since Ember 3.2.2. Works fine in Ember 3.1

Temporal fix: change templateName to be use as a partial.

Best regards.

**Comment by emoryy** [comment]
I've run into this same issue while trying to update our app to Ember 3.4
Changing every usage of templateName to a template using a partial throughout our app would be troublesome, and I'd rather avoid it if I could.

Is there any chance of future activity on this?

**Comment by locks** [comment]
Partials have been deprecated so far, so I'll be closing this issue as no longer relevant. Sorry for the runaround!
