### ISSUE TITLE
[Docs] CoreObject::create does not appear in API docs website

### ISSUE THREAD

**Issue by jacobq** [emberjs/ember.js#16928]
Looks like the [jsdoc work has been done for `CoreObject::create`](https://github.com/emberjs/ember.js/blob/v3.4.0/packages/ember-runtime/lib/system/core_object.js#L682) but it doesn't appear on [the corresponding docs page](https://emberjs.com/api/ember/3.4/classes/CoreObject?show=inherited%2Cprotected%2Cprivate%2Cdeprecated). Is this because it's `static`? Is it hard to fix?

**Comment by rwjblue** [comment]
The docs suggest that `create` is a static method of `@ember/object` (notice the `@for` there?), and do seem to be showing up properly at https://emberjs.com/api/ember/3.4/functions/@ember%2Fobject/create.

Going to close this for now (we can reopen, but I think @ember/object is the right place to document it these days...)...

**Comment by jacobq** [comment]
I'm sure you're right. It just seems weird to me that an object would have methods not shown on its docs page even when all the "Show:" flags (inherited, protected, private, deprecated) are checked. Thanks for at least pointing out the `@for` directive. I didn't realize what that did.
