### ISSUE TITLE
Workaround for Buggy Weakmaps on Firefox

### ISSUE THREAD

**Issue by anlumo** [emberjs/ember.js#16943]
Ember uses weakmaps internally in “meta”, where the [value of a property is used as the key in a weakmap](https://github.com/emberjs/ember.js/blob/9bdc0075762ac24bf18629d562548b140d0309cd/packages/%40ember/-internals/meta/lib/meta.ts#L599). This is broken in Firefox for certain objects ([Bug 1428438](https://bugzilla.mozilla.org/show_bug.cgi?id=1428438)). It's possible to work around this by returning a single-entry array instead of the object directly, but it would be nice if ember would implement a workaround internally.

At the moment, the Firefox team doesn't seem to be inclined to fix this bug.

**Comment by rwjblue** [comment]
Hmm, our tests pass under Firefox, would you mind sending a failing test PR (or other reproduction) so that we can properly gauge impact?

**Comment by rwjblue** [comment]
@anlumo - Friendly ping 😺

**Comment by anlumo** [comment]
Oh sorry, forgot about this one. Anyways, it appears that the next release of Firefox will finally fix this bug after the ticket being open for two years, so implementing workarounds might not be a good use of development time any more.

I also recently realized that the bug is triggered by returning a WebGL texture inside a DS.PromiseObject only, so this ticket should probably have been created for ember-data anyways.

**Comment by rwjblue** [comment]
Ahh! Thank you for following up!

I'm going to go ahead and close (feel free to reopen over on ember-data if you think thats a good idea)...
