### ISSUE TITLE
Add `once` flag to observer

### ISSUE THREAD

**Issue by cbou** [emberjs/ember.js#16948]
`ember/object/events` `addListener` has a flag called `once`. I think this flag could be useful to `ember/object/observers` `addObserver ` as well.

**Comment by bekzod** [comment]
https://github.com/bekzod/ember-observer-macros ?

**Comment by cbou** [comment]
Thanks for the link, I was not aware about the addons.

Adding the flag still makes sense to me because it's there for `addListener`.

**Comment by pixelhandler** [comment]
@cbou Looks like the best way to continue with a request for a feature/change is to open an RFC issue, see https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature

> Use RFC issues to propose a rough idea, basically a great place to test the waters.

Please move this over to the RPC repo as an issue, https://github.com/emberjs/rfcs

**Comment by pixelhandler** [comment]
@cbou did you open an RFC issue? https://github.com/emberjs/rfcs/issues

**Comment by cbou** [comment]
My first RFC !

emberjs/rfcs/pull/427

**Comment by locks** [comment]
I'm closing this issue since the related RFC has already gone through the process :) Thanks for your work!
