### ISSUE TITLE
[docs] Syntax highlighting sometimes breaks

### ISSUE THREAD

**Issue by mike-north** [emberjs/ember.js#16954]
Whatever we're using for syntax highlighting seems to break around code with ES2015 language features

![screen_shot_2018-09-07_at_1_35_52_pm](https://user-images.githubusercontent.com/558005/45243426-9fcc0d00-b2a8-11e8-9da9-35ed6b396c5d.png)
![screen_shot_2018-09-07_at_1_36_10_pm](https://user-images.githubusercontent.com/558005/45243485-e883c600-b2a8-11e8-9a07-21afbce6569b.png)

**Comment by locks** [comment]
Gracias, moved to Ember API Docs.
