### ISSUE TITLE
[docs] @ember/debug - DataAdapter mixed signals about public API

### ISSUE THREAD

**Issue by mike-north** [emberjs/ember.js#16953]
[Documentation](https://www.emberjs.com/api/ember/3.4/classes/DataAdapter) reads
```
The methods likely to be overridden are:

getFilters
detect
columnsForType
getRecords
getRecordColumnValues
getRecordKeywords
getRecordFilterValues
getRecordColor
observeRecord

```

`getFilters` is the only thing that's both on this list, and is marked as a public method.

Here's what's public
![screen shot 2018-09-07 at 2 06 14 pm](https://user-images.githubusercontent.com/558005/45243070-54652f00-b2a7-11e8-9725-c0604e602fd3.png)

related source: https://github.com/emberjs/ember.js/blob/14f44d6fa72234eeed87cabf88a96d8064576220/packages/ember-extension-support/lib/data_adapter.js

**Comment by mike-north** [comment]
This looks better today. Not sure what changed to fix this

![screen shot 2018-09-11 at 1 26 51 pm](https://user-images.githubusercontent.com/558005/45385708-648e4e80-b5c6-11e8-8fcf-320917091a6f.png)

**Comment by toddjordan** [comment]
The inherited checkbox
