### ISSUE TITLE
factoryFor does not return a component with a layout

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#16963]
Using Ember 3.4.1. This code:

```coffeescript
console.log getOwner(this).factoryFor('component:my-component').create().get('layout')
```

Prints `undefined`. For some reason, when creating a component dynamically, it doesn't get the "static" layout that we have in `app/templates/components/my-component.hbs`. And, when we render this component on the page, we get an empty div instead of the stuff in the template. Is this a bug? How are we supposed to do this?

**Comment by rwjblue** [comment]
I'd need more information to be able to help the specific scenario, but the reported assumption is actually wrong. `owner.factoryFor('component:whatever-name').create().get('layout')` intentionally returns `undefined`. The `layout` property in `Ember.Component`'s are essentially "write only". In other words, the property is used to tell Ember to use a template _other than_ the default (which would be normally resolved). When a component just wants to use the resolver (99.99% of the time) it `layout` _should_ be undefined.

Going to close this for now (please let me know if you need help with that app issue you mentioned)...

**Comment by boris-petrov** [comment]
@rwjblue - thank you for the answer.

Actually the real issue is that when creating a component dynamically, it doesn't get the "static" layout that you have defined in `app/templates`. And from there follows the fact that it doesn't have the correct `layout` property.

I do think this is a bug and it doesn't make sense to be that way - why is there an inconsistency between using a component "statically" in an HBS template and creating one dynamically in JS? That is, if you have a file `app/templates/components/my-component.hbs`:

```handlebars
my cool template
```

And in another template `app/templates/components/other-component.hbs`:

```handlebars
{{my-component}}
```

This will render `my cool template`. But if I do:

```javascript
const component = getOwner(this).factoryFor('component:my-component').create();
component.one('didRender', function() {
  console.log(this.element.innerText);
});
component.appendTo('body');
```

This will print an empty string instead of `my cool template` (and in `body` there will be an empty `div` instead of the same text).

Our specific use case is a bit involved but we allow users to create their own HBS templates and we render them dynamically but we also have a static template defined for a fallback in case the user hasn't entered anything - and we use the same code to render these dynamically created user-templates and the fallback - but the fallback doesn't work because of the issue here - it doesn't get the layout we've defined in a static HBS file.

Does that make sense? Do you agree that this is inconsistent and perhaps should be revisited?

**Comment by rwjblue** [comment]
I’m not sure. In general, components should only be created by the renderer (by way of template invocation) and any other usage is likely to break over time. 

The system as it stands today is specifically geared to “fast pass” the “normal” setup (where layout is resolved and not manually set). This is why the layout property is `undefined` by default.

In your scenario, you could maintain the same behavior with something like:

```js
const layout = gerOwner(this).lookup(‘template:components/my-component’);
const component = getOwner(this).factoryFor('component:my-component').create({ layout });
component.one('didRender', function() {
  console.log(this.element.innerText);
});
component.appendTo('body');
```

Though, I think you would do better to figure out a mechanism to avoid manual creation and appending in the long run...

**Comment by boris-petrov** [comment]
@rwjblue - thank you for the response.

The workaround you suggest makes sense. Thank you for it.

On the topic of dynamically creating components - am I to understand that such a thing is not going to be supported at all at some point? There are usecases that mandate such a possibility - for example the templates that the users create we compile down to DOM (in the JS code) and then pass this DOM to a third-party library that accepts such elements. I don't see any other way we can do this right now. I'm thinking maybe something with the `component` helper - perhaps extend it and do something with it but I haven't researched it. Can you think of another *supported* way of getting DOM from a template in JS?
