### ISSUE TITLE
href attribute for svg use attribute not working when used without quotation marks

### ISSUE THREAD

**Issue by mhankus** [emberjs/ember.js#16968]
When setting attribute of SVG <use> without quotation marks, SVG is not rendered

Take a look at 
https://ember-twiddle.com/1433f1b137d34c9422dc88eda124c2d0

the only difference is

in first example
```
xlink:href="{{iconLink}}"
```
in second example
```
xlink:href={{iconLink}}
```

linter now complains about first example.

**Comment by rwjblue** [comment]
This does surprise me a tad, but I think that the quoted version is actually better anyways so it seems reasonable to me. 

Would you mind submitting a failing test to [glimmerjs/glimmer-vm](https://github.com/glimmerjs/glimmer-vm) repo so we can track this down and deal with it over there?

In the meantime, I'm going to go ahead and close this one...
