### ISSUE TITLE
Duplicate includes documentation in API documentation

### ISSUE THREAD

**Issue by adisbanda** [emberjs/ember.js#16969]
There's duplicate declaration of the `includes` `Ember.MutableArray` method in the API documentation, linked below:

https://www.emberjs.com/api/ember/2.14/classes/Ember.MutableArray/methods/includes?anchor=includes

**Comment by mike-north** [comment]
Recent versions of ember docs do not have this problem. 
* [2.16](https://www.emberjs.com/api/ember/2.16/classes/MutableArray/methods/includes?anchor=includes)
* [3.4](https://www.emberjs.com/api/ember/3.4/classes/MutableArray/methods/includes?anchor=includes)

**Comment by locks** [comment]
As noted by the previous comment, this is fixed is later versions!
