### ISSUE TITLE
Router Service: Default Query Param Values are Serialized to the URL

### ISSUE THREAD

**Issue by iezer** [emberjs/ember.js#16973]
I have a route with a default query param specified in the controller. If I transition to this route using a `link-to`, a controller action, or a route action, the default query param is not serialized to the URL. However, if I transition by using the router service, by calling `router.transitionTo(...)`, the default value does appear in the URL.

Here's a [reproduction twiddle](https://ember-twiddle.com/33b0f6f502cea8c109bcdaf2e7cb7dc9?openFiles=templates.application.hbs%2C&route=%2Fqp-route%3Fpage%3D1).

Possibly related to #16594, although I don't get any errors in the console.

**Comment by Exelord** [comment]
Confirmed!

**Comment by iezer** [comment]
Turns out this is deliberate behavior described in the [Router Service RFC](https://github.com/emberjs/rfcs/blob/master/text/0095-router-service.md#query-parameter-semantics). It's implemented [here](https://github.com/emberjs/ember.js/blob/6070ad8e612254c4b026f8f9ca4f0639469684cd/packages/%40ember/-internals/routing/lib/system/router.js#L822-L824) as part of [this commit](https://github.com/emberjs/ember.js/commit/3b9489cf6acb61c5ee22f8016f7486ef1e7133d4) and there's even a [test](https://github.com/emberjs/ember.js/commit/3b9489cf6acb61c5ee22f8016f7486ef1e7133d4#diff-ea57fd4a82042201aae1f12d12af03a8R241).

This behavior is not documented anywhere other than the RFC so I'll open a PR with some documentation.

**Comment by iezer** [comment]
@rwjblue the [Router Service RFC](https://github.com/emberjs/rfcs/blob/master/text/0095-router-service.md#query-parameter-semantics) describes adding a symbol `Ember.DEFAULT_VALUE` exposed as `import { DEFAULT_VALUE } from 'ember-routing';` for hiding default query params when using the Router service, but it seems like this was never implemented. Is it still part of the plan? If so I'd be happy to open work on it.

**Comment by iezer** [comment]
Adding @miguelcobain and @chadhietala since you've worked on the RFC and Router service and may have some comments.

**Comment by rwjblue** [comment]
Docs were fixed in 
https://github.com/emberjs/ember.js/pull/16977, considering this closed...
