### ISSUE TITLE
[docs] 'ember' module is incorrectly marked as private

### ISSUE THREAD

**Issue by mike-north** [emberjs/ember.js#16971]
![screen_shot_2018-09-12_at_9_44_41_pm](https://user-images.githubusercontent.com/558005/45467565-203da400-b6d5-11e8-88a8-e564bbd79a90.png)
@rwjblue indicates that it is neither deprecated nor private: https://discordapp.com/channels/480462759797063690/480777444203429888/489595257734955008

Until such time as we have officially moved away from `import Ember from 'ember';`, this should remain in the documentation as a public thing. There are some things that cannot be consumed through the new `@ember` namespace:
* `Ember.NativeArray`
* `Ember.Test`
* `Ember.Namespace`
etc...

**Comment by toddjordan** [comment]
I don't think we should document alternative calls to the `@ember` modules, though I do think we should make sure things that do not have rfc 176 based conversions are documented.   It would be worth finding these and making sure they are exposed.

A few things worth noting:

* We converted the source documentation of most things over to the RFC 176 way of importing things, so just making the ember namespace public will not bring that all back.
* We want users on new releases to use the new way, because that what will live on.
* Consumers of old releases can still get the documentation as it was pre 2.16

**Comment by mike-north** [comment]
> I don't think we should document alternative calls to the @ember modules, though I do think we should make sure things that do not have rfc 176 based conversions are documented.

I do understand that we're trying to de-emphasize `import Ember from 'ember';`, but this sounds like a bit of a hedge between private and public API, and could result in confusion. 

For example -- I'm working on [type information for Ember](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember/index.d.ts) and even as an experienced practitioner, I'm finding it difficult to determine exactly what the public API surface of the framework is in this area.

There are also plenty of people who are still using `import Ember from 'ember';` running on 3.x framework versions -- are they supposed to know that they should be referring to the v2.15 docs? Doesn't SemVer suggest that the 3.x API surface they're actually using _could_ be completely different from this documentation?

Maybe my thinking in this area is overly simplistic, but I feel like things should either be
- (A) **Public API** -- which includes documentation, test coverage and a guarantee that any breakage will come with a major version number change. Deprecated, soon-to-be-deprecated and "hope we can deprecate it eventually" stuff falls into this category. 
- (B) **Private API** -- No documentation, no guarantee of test coverage.

**Comment by mike-north** [comment]
Discord convo about this issue here https://discordapp.com/channels/480462759797063690/480777444203429888/492418190584840193

**Comment by toddjordan** [comment]
Also its important to note the classic stuff isn't marked public, its gone and would have to be reimplemented.

**Comment by locks** [comment]
Closing as no longer relevant. Thanks for the discussion!
