### ISSUE TITLE
[docs] @ember/routing module does not list public sub-modules

### ISSUE THREAD

**Issue by mike-north** [emberjs/ember.js#16972]
![screen_shot_2018-09-12_at_9_43_55_pm](https://user-images.githubusercontent.com/558005/45467760-0b154500-b6d6-11e8-9bfa-f85a93c44cfc.png)

At the very least, this should probably include

* `@ember/routing/route`
* `@ember/routing/router`
* `@ember/routing/router-service`
* `@ember/routing/link-component`

I was also surprised to see `HashLocation`, `HistoryLocation` and `NoneLocation` marked as `protected`. As a consumer of the API docs, I have no idea what this means in terms of my ability to rely on it, and how SemVer would reflect a breaking change.

**Comment by locks** [comment]
We currently do not list sub-modules. I understand the confusion it creates, but when you pick one of the classes, the import statements at the top seem to be correct, which hopefully helps 🤞. Thanks for the report.
