### ISSUE TITLE
defineProperty not triggering computed property observation

### ISSUE THREAD

**Issue by vcipriani** [emberjs/ember.js#16980]
It appears that setting when setting property "A" with `defineProperty` it does not trigger any other computed properties that are observing "A".  When using `this.set`,  the computed properties observing A will recalculate.  I assume that the `this.set` behavior is correct?  We currently depend on it. 

Here is a simple twiddle to illustrate the issue.  The computed property `textToShow` will recalculate when using `this.set`; however, if you disable that line and use `defineProperty`, the prop will not recalculate.  https://ember-twiddle.com/0661c149329ee4c647ca832bd0cad036?openFiles=controllers.application.js%2C

We're observing this in Ember 3.2.  I'm not sure when this behavior appeared, we ran into it because we we're trying to remove the use of `this.set` when setting computed properties programatically.

**Comment by pixelhandler** [comment]
@vcipriani `defineProperty` is marked as private and should not be used in application code.

- See https://github.com/emberjs/ember.js/blob/v3.5.0/packages/ember-metal/lib/properties.ts#L108-L174

**Comment by vcipriani** [comment]
In Ember 3.2, using `set` to set computed properties was deprecated.  The team's recommendation is to use defineProperty (see https://www.emberjs.com/deprecations/v3.x/#toc_ember-meta-descriptor-on-object).  

Based on the current messaging, if there is any intention of supporting programmatic setting of computed properties, it appears that this is a bug and defineProperty should not be private.

**Comment by rwjblue** [comment]
See https://github.com/emberjs/ember.js/pull/17028, `defineProperty` is public api now. 😈

**Comment by pixelhandler** [comment]
@vcipriani See this twiddle, defineProperty is working, just need to notify the change since the property is setup async via timeout.

- https://ember-twiddle.com/8dede2230a67edb02c0a1dabd6b548c4?openFiles=controllers.application.js%2C

**Comment by vcipriani** [comment]
Thank you.  This did fix the issue for us,
