### ISSUE TITLE
Using input helper, how can we pass both the `value` and `event` to the action? 

### ISSUE THREAD

**Issue by elimau** [emberjs/ember.js#16989]
As per the ember latest (3.4), in the docs
https://guides.emberjs.com/release/templates/input-helpers/
it says if you set the value, the value will be sent to the action as the first param.
Otherwise, it will send the event as the first param.

However, I need both the `value` and the `event` to be passed to the action.
How can I get that to work with the latest ember?

The below code shows an example of a template code and component (js) code.

hbs:
`    {{input placeholder=placeholder class="type-in" autocomplete="off" value=value key-up="keyUp" key-down="keyDown" insert-newline="enter" bubbles=false }}
`

js:
`
    actions: {
        keyUp(text, event) { ... }
    }
`

The above code used to work in ember 2.9.0. Both the `value` and `event` used to get passed to the `keyUp` action. Now, I upgrade to ember 3.4, it only sends the `value`, the second param (event) is null.
Thanks for any help.

**Comment by btecu** [comment]
I've also run into this in 3.4.

**Comment by raphaelns-developer** [comment]
Same here. After updated to Ember 3.4 the `key-down` and `key-up` action stop to sending the `event`. I made a simple twiddle to show the error: https://ember-twiddle.com/198760441072c804776732de6b68954b?openFiles=controllers.application.js%2C

**Comment by rwjblue** [comment]
the patch already landed, and will be included in the next 3.4.x version (hopefully releasing today/tomorrow)
