### ISSUE TITLE
Meta: missing docs in the API viewer from 3.3 -> 3.4

### ISSUE THREAD

**Issue by jenweber** [emberjs/ember.js#16993]
If anyone would like to help with a very important bugfix, there is a list of documentation that was dropped between Ember 3.3 and 3.4, in terms of what is rendered by the API docs viewer: https://github.com/emberjs/ember.js/pull/16910#issuecomment-422638799

We lost the following public APIs:
  "debugger"
  "deleteMeta"
  "descriptorFor"
  "getOwner"
  "partial"
  "setOwner"
  "with"
  "yield"

I, for one, am super duper pleased that we can catch this kinda stuff moving forward using tests!

**Missing docs are caused by one or multiple of the following:** 
- public static methods that are missing an @static (public meaning that you don't have to instantiate a class to use the method)
- a missing `@public` tag
- they are in a file that has no `@class` declaration in it
- they are in a directory that is not indexed by YUIdoc ([configured here](https://github.com/emberjs/ember.js/blob/master/yuidoc.json))
- they got moved to the wrong module
- generally incorrectly formatted yuidoc code comments

I think the action items here are, figure out why each got dropped, open a PR that fixes it and explains why it was being omitted.

It's a little bit tricky to get the hang of, but I think more people than me, Todd, and locks should be in the know about how it works, so if anyone wants to at least attempt detective work, that would be awesome.

You can see the basic yuidoc generated output by doing `yuidoc .` from the root of the ember.js repo and looking at `docs/data.json`. If a method doesn't show up somewhere in there, it has no chance of showing up in the API docs viewer. If it does show up there but still doesn't show up on the website, that's very possible because our website assumes a certain structure and hierarchy.

**Comment by Gaurav0** [comment]
"deleteMeta" and "descriptorFor" are marked private in source and aren't listed in ember-rfc176-data. I'm therefore not sure if these are public apis. If someone can confirm they are public, I can mark them appropriately and they should be given RFC176 imports.

**Comment by jelhan** [comment]
Not quite sure if this is important, but at least `yield` and `with` are missing in `Class Ember.Templates.helpers` docs since `3.2`.

**Comment by locks** [comment]
I think this is currently addressed.
