### ISSUE TITLE
factoryFor/lookup return undefined for template-only Glimmer components

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#16997]
Using Ember 3.4.1. This code:

```coffeescript
console.log getOwner(this).factoryFor('component:my-component')
```

Prints `undefined` when `my-component` is a template-only Glimmer component (i.e. there is no JS file and `template-only-glimmer-components` is `true`). Is this a bug? How are we supposed to get such components?

**Comment by rwjblue** [comment]
This does not seem like a bug to me, can you please explain your use case more?

**Comment by boris-petrov** [comment]
Well, our use case is a bit involved, but here goes.

We create component instances dynamically. These components can be dynamically generated using some user input data or, when no such data is available, we fallback to some static templates in our codebase. So we do something like:

```coffeescript
userData = ...
if userData?
  componentName = "component:#{userData}"
else
  componentName = 'component:static-component'

owner = getOwner(this)
componentFactory = owner.factoryFor(componentName)

componentFactory.create(tagName: 'div')
```

Which doesn't work for the fallback case because `factoryFor` returns `undefined`. I don't see any reason for this to be so. The component does exist and can be used "statically" in an HBS file. So why can't we get it dynamically? And why does it matter whether it has a JS file?

I think this is a totally valid scenario. :) Also, there is an inconsistency between template-only Glimmer component and "normal" components.

**Comment by pixelhandler** [comment]
@boris-petrov does this work if you add a component.js file? and not use template only component?

**Comment by boris-petrov** [comment]
@pixelhandler - if you add a `js` file then the issue goes away even with `template-only-glimmer-components` = true. This is how we worked around the problem. I haven't tried with `template-only-glimmer-components` = false - I'll get back to you about that on Monday if you need it as information. But in any case I don't see a reason for such a discrepancy between a component with and without a `js` file.

**Comment by chancancode** [comment]
This is working as intended. The feature is precisely about not generating a js class by default (which brings with it the div wrapper, attribute bindings, etc). There is also no good default class to generate since there are multiple component super classes now. If your use case needs a specific js class (Ember.Compinent it sounds like) then you should ensure it exists.
