### ISSUE TITLE
[docs] `Component.layout` property

### ISSUE THREAD

**Issue by ppcano** [emberjs/ember.js#16995]
1) `layout`

The documentation of the `component layout` property does not specify in which common cases the property could be used.

#15156 and [component addons](https://github.com/emberjs/ember.js/issues/12467#issuecomment-182993097) are two threads describing common cases of the `layout` property:

- an addon component
- a parent component whose child components want to inherit the parent template; if the layout property of the parent component is not defined, the parent template will not be inherited . 

The current [API Component doc](https://www.emberjs.com/api/ember/3.4/classes/Component/) describes how to use the property but in most of the cases developers don't need to use it because the layout will be injected by the app structure convention.

I think as #15156 that it may help to describe these examples on the docs. 

2) `layoutName` became private API in `v2.2` but it is recommended on some questions in SO. I wonder if there is the intention to deprecate `layoutName`. 

It looks `layout` and `layoutName` do the same job but `layoutName` allows to set the layout dinamically; in case someone needs a runtime template resolution, the `{{component}}` helper could do the work.

**Comment by ppcano** [comment]
@locks 

1. I have reviewed again this issue and it looks the documentation is not clear or wrong.

On the *Layouts* section of the [Component doc](https://www.emberjs.com/api/ember/3.5/classes/Component/), the following example looks to indicate that the `layout` template will be yielded into the component default template. 

```js
 //profile.js
  import Component from '@ember/component';
  import layout from '../templates/components/person-profile';

  export default Component.extend({
    layout
  });
```

```hbs
// profile.hbs
 <h1>Person's Title</h1>
  <div class='details'>{{yield}}</div>
```

```html
// output
  <h1>Person's Title</h1>
  <div class="details">
    <h2>Chief Basket Weaver</h2>
    <h3>Fisherman Industries</h3>
  </div>
```

Here a [Twiddle](https://ember-twiddle.com/99d0503c3480b272c9529f64034ea30d?numColumns=2&openFiles=templates.components.my-component.hbs%2Ccontrollers.application.js) to reproduce what it looks like to be an error based on the expected behaviour.

Is the above example wrong or a I have misunderstood something?


2. I commented previously about the `layoutName` property, if the plan is to deprecate it, I can write a RFC for that and work on it.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? Since this property doesn't exist on the "modern" component classes (glimmer / angle brackets), maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.
