### ISSUE TITLE
EmberObject.create(null) fails in 3.x

### ISSUE THREAD

**Issue by DLiblik** [emberjs/ember.js#17012]
EmberObject.create was rewritten and no longer supports passing null to create what is effectively an empty object: https://github.com/emberjs/ember.js/commit/4709935854d4c29b0d2c054614d53fa2c55309b1#diff-83aef7046279fbc5512d665c03bff129R128

Was this intended (in which case what's the proper way to do this now), or is it a bug?

(I edited this comment to change the link to the proper diff)

**Comment by rwjblue** [comment]
I’ll have to test what this used to do to give a more concrete answer for the best path forward. I do believe support was dropped intentionally though, and it’s unlikely that we would consider this a breaking change. 

If you are intending to create an object that has no properties / methods at all (and does not extend from anything), you should migrate to `Object.create(null)`. 

If you are trying to create a new `Ember.Object` with no _additional_ properties you can use `Ember.Object.create()`. 

Do either of those match what you were trying to do?

**Comment by pixelhandler** [comment]
@DLiblik I think the choices are `Object.create(null)` and `Ember.Object.create()`. I don't believe using `EmberObject.create(null)` was ever documented a use case for `.create()`

- See https://www.emberjs.com/api/ember/release/classes/@ember%2Fobject/methods/create?anchor=create

**Comment by DLiblik** [comment]
Sorry to have not responded sooner - somehow I missed the original response from @rwjblue.

The use case was for creating (deliberately) the type of object that's returned from the `hash` helper - basic, clean, immutable.

**Comment by DLiblik** [comment]
And so the obvious question: is there a way to do this - i.e. when writing custom helpers, how can an object congruent with those semantics be generated in code?

**Comment by rwjblue** [comment]
You should use `Object.create(null)` to create objects without prototype methods/properties/etc. I don't think we ever intended `Ember.Object.create(null)` to actually do this...
