### ISSUE TITLE
Having a Computed Property (CP) which depends on a oneWay CP doesn't work

### ISSUE THREAD

**Issue by leondmello** [emberjs/ember.js#17037]
Here is a twiddle which demonstrates the issue
https://ember-twiddle.com/1934386ad97e960cac37b36cf0068847?openFiles=templates.my-route.hbs%2C&route=%2Fmy-route

The controller has three CPs,
```
customRoutingType: oneWay('model.customRoutingType'),
isFixedRouted: equal('customRoutingType', 'fixed').volatile().readOnly(),
isDynamicRouted: equal('customRoutingType', 'dynamic').volatile().readOnly()
```

`customRoutingType` can take the values `fixed` & `dynamic` based on which radio button you click when you visit the `my-route` route in the twiddle

The route template displays the state of the three values.
`customRoutingType` updates as you toggle the radio buttons, but the other dependent CPs do not.

**Comment by luxferresum** [comment]
[Related SO Question](https://stackoverflow.com/questions/52635727/computed-properties-are-not-re-calculating-when-dependent-oneway-cp-updates)

It also *is* correctly explained in the [API specification](
https://www.emberjs.com/api/ember/3.3/classes/ComputedProperty/methods/volatile?anchor=volatile):

>It also does not automatically fire any change events. You must manually notify any changes if you want to observe this property.
>
>Dependency keys have no effect on volatile properties as they are for cache invalidation and notification when cached value is invalidated.

**Comment by leondmello** [comment]
I guess this can be safely withdrawn then 😃 
Thanks everyone for the explanations
