### ISSUE TITLE
[Documentation] Broken link "DEFINED IN" in Ember-Data

### ISSUE THREAD

**Issue by lifeart** [emberjs/ember.js#17030]
https://emberjs.com/api/ember-data/release/classes/DS.Store
Ver: 3.4 (latest at this moment)
Current url: https://github.com/emberjs/data/tree/v3.4.2/addon/-private/system/store.js#L125

![image](https://user-images.githubusercontent.com/1360552/46367631-c5b9b700-c686-11e8-8f22-140c880e9069.png)

**Comment by runspired** [comment]
@lifeart I would open this against ember-data repo.

**Comment by lifeart** [comment]
@runspired  Done, https://github.com/emberjs/data/issues/5662
