### ISSUE TITLE
`isEmpty` call on ProxyObject w/ `size` property throws '.get()' proxy assertion (3.1+)

### ISSUE THREAD

**Issue by nickschot** [emberjs/ember.js#17032]
Having an ObjectProxy (or any object using unknownProperty) with a property named 'size' of type String `isEmpty(myChangeset)` results in the `Assertion Failed: You attempted to access the 'size' property (of changeset:[object Object]). Since Ember 3.1 , this is usually fine as you no longer need to use '.get()'...` error.

This is caused at: https://github.com/emberjs/ember.js/blob/f73d8440d19cf86a10c61ddb89d45881acfcf974/packages/%40ember/-internals/metal/lib/is_empty.ts#L44 and only occurs in Ember 3.1+ (which is when the assertion was added) which also means that the assertion will trigger for any object with a "size" key that refers to a proxy.

Minimal reproduction: https://ember-twiddle.com/8e63470aa2e8ab8b07735334b169c96d?openFiles=controllers.application.js%2C

AFAIK `.size` is just used for Maps/Sets and the like? Might an extra check be necessary?

Somewhat similar to: https://github.com/emberjs/ember.js/issues/16259

cc @snewcomer

**Comment by pixelhandler** [comment]
@nickschot can you create an ember-twiddle as an example?

**Comment by nickschot** [comment]
@pixelhandler I did some more debugging and the test case is pretty simple. I will update the main post with my new findings. Meanwhile a reproduction can be found: https://ember-twiddle.com/d3b2742a7156454f2ece80d6c26d2581?openFiles=controllers.application.js%2C

**Comment by nickschot** [comment]
I have created an updated test case which doesn't use changeset but a normal ObjectProxy in the example (as this is the more general case).

Updated minimal reproduction: https://ember-twiddle.com/8e63470aa2e8ab8b07735334b169c96d?openFiles=controllers.application.js%2C

**Comment by nickschot** [comment]
I think the solution can be as simple as adding an `unknownProperty` check so that it falls through to the branch where `get(obj, 'size')` is used. This still conforms to the description: 

>   If the value is an object with a `size` property of type number, it is used
  to check emptiness.

Proposed fix:
```
  if (typeof obj.unknownProperty !== 'function' && typeof obj.size === 'number') {
    return !obj.size;
  }
```

**Comment by nickschot** [comment]
The same seems true for `length`
