### ISSUE TITLE
[DOC] Should computed properties been documented as properties or methods?

### ISSUE THREAD

**Issue by jelhan** [emberjs/ember.js#17039]
Computed properties are currently documented inconsistently. Some of them are documented as `property`, some of them as `method`. This should be normalized. I expected them to be documented as properties, but not quite sure if this is correct.

Examples for computed properties been documented as `method`:
- https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/routing/lib/system/route.ts#L2114-L2128
- https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/routing/lib/system/router.ts#L1855-L1865

Examples for computed properties been documented as `property`:
- https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/routing/lib/services/router.ts (all CPs in that file)
- https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/routing/lib/system/route.ts#L2171-L2176

**Comment by pixelhandler** [comment]
@emberjs/learning-team-managers Thoughts?

**Comment by ondrejsevcik** [comment]
Given that js properties are called without parentheses which is also true for computed properties, it makes sense. On top of that methods usually do something, thus they usually contain a verb in the name.
```
this.name // property
this.getName() // method
```
