### ISSUE TITLE
Implement + enable `array` Helper Feature

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#17052]
This is a tracking issue to enable the `array` helper as proposed in https://github.com/emberjs/rfcs/pull/318.

- [x] Implement
- [x] API Docs
- [x] Guides
- [x] Enable by default
- [ ] Author a polyfill (e.g. `ember-array-helper-polyfill`)?

**Comment by josemarluedke** [comment]
🔒 I will give this implementation a try.

**Comment by rwjblue** [comment]
Some general implementation notes, I believe this should roughly be implemented the same way as the `hash` helper (but using positional args instead of named args).

* [a helper like this one](https://github.com/emberjs/ember.js/blob/7116215ebda27c517c815da7b9f4330461125242/packages/%40ember/-internals/glimmer/lib/helpers/hash.ts#L46-L48) but with `args.positional.capture()`
* [add to this array of built-ins](https://github.com/emberjs/ember.js/blob/7116215ebda27c517c815da7b9f4330461125242/packages/%40ember/-internals/glimmer/lib/resolver.ts#L55-L75)
* [add a slew of tests like](https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/glimmer/tests/integration/helpers/hash-test.js)

**Comment by kanongil** [comment]
I really think you need to revisit the _an entirely new array is returned on changes_ thing on this (and the `hash` helper). The ember component system is not geared for this, as any change to any property, or sub-property, of any element triggers a re-validation of the whole array.

**Comment by rwjblue** [comment]
@kanongil - I'm not sure that I agree, the point is that revalidating the full array is not expensive.

**Comment by kanongil** [comment]
That is not my experience from the hash helper. I can’t see why this would be different.

**Comment by rwjblue** [comment]
Added a few more todo items:

* Guides
* Enable by default

**Comment by rwjblue** [comment]
@josemarluedke - Interested in picking up the guides work also?

**Comment by YoranBrondsema** [comment]
@rwjblue Saw this issue and don't think that @josemarluedke had picked up the guide yet. So wrote a short blurb in the guide in https://github.com/ember-learn/guides-source/pull/209.

**Comment by rwjblue** [comment]
Nice, thank you!

**Comment by SergeAstapov** [comment]
https://github.com/kellyselden/ember-array-helper may be considered as polyfill

**Comment by rwjblue** [comment]
@SergeAstapov - It certainly _could_ be, but it would need some changes. Specifically, it would need to be updated to _do nothing_ when it detects the newer Ember version that ships the helper by default.

**Comment by kategengler** [comment]
@kellyselden Any interest in updating your `ember-array-helper` addon (mentioned above) to be a polyfill?

**Comment by kellyselden** [comment]
Of course. I can donate it or just add people, whatever need be.

**Comment by locks** [comment]
This is le done.
