### ISSUE TITLE
[BUG] EmberArray#pushObjects fails when an ArrayProxy is passed

### ISSUE THREAD

**Issue by pieter-v** [emberjs/ember.js#17113]
```javascript
emberArray.pushObjects(ArrayProxy.create({ content: ['a','b']}))
```
throws an exception: `The third argument to replace needs to be an array.`

**Comment by pixelhandler** [comment]
@pieter-v why not push the content of the proxy? I think there is `.toArray()` 

```javascript
emberArray.pushObjects(ArrayProxy.create({ content: ['a','b']}).toArray())
```

- https://www.emberjs.com/api/ember/3.5/classes/ArrayProxy/methods/toArray?anchor=toArray

**Comment by pieter-v** [comment]
@pixelhandler I use already the workaround, thanks.

I don't agree that this is not a bug:
According the documentation of [`MutableArray#pushObjects`](https://www.emberjs.com/api/ember/3.5/classes/MutableArray/methods/pushObjects?anchor=pushObjects), it accepts an `EmberArray`. 
And according the documentation of [`ArrayProxy`](https://www.emberjs.com/api/ember/3.5/classes/ArrayProxy/) it is also an `MutableArray`

If the decision is to support only real arrays in `pushObjects`, then de documentation should be adapted.
