### ISSUE TITLE
"Could not find module" after upgrading to ember-cli 3.5.0

### ISSUE THREAD

**Issue by Nippius** [emberjs/ember.js#17119]
Hi everyone. 

I updated to ember-cli to version 3.5.0 and now I'm getting this error when building my application:

![image](https://user-images.githubusercontent.com/1528640/46974552-3c5da800-d0bc-11e8-9c31-b2eb38fcd1e4.png)

and this is the output of ```ember b````:

![image](https://user-images.githubusercontent.com/1528640/46974729-c1e15800-d0bc-11e8-99b8-a105a8a8bca7.png)

output for ```ember --version```:
```
WARNING:
WARNING: The 'package.json' file for the addon at D:\node_modules\chokidar
WARNING:   specifies a missing dependency 'fsevents'
WARNING:
WARNING: The 'package.json' file for the addon at D:\node_modules\ember-cli-broccoli-sane-watcher\node_modules\sane
WARNING:   specifies a missing dependency 'fsevents'
ember-cli: 3.5.0
node: 8.11.2
os: win32 x64
```

Any idea on how to solve this? I can't find anything in the release notes :/

Thank you.

**Comment by rwjblue** [comment]
Can you share a reproduction repo for this? ember-data itself tests against canary builds, and I just double checked that this isn't an issue on recent builds...

**Comment by Nippius** [comment]
Sure, you can use my project (the one where I took the screenshots from): https://github.com/Nippius/digitalillusion-frontend

**Comment by Nippius** [comment]
On side note, the travis build fails for a different reason. There seems to be an issue with the eslint:

![image](https://user-images.githubusercontent.com/1528640/47042889-3c28df80-d184-11e8-88d6-238deba5f994.png)

**Comment by Nippius** [comment]
Ok after a little testing I managed to "fix" the problem by updating the following packages:

* ember-ajax -> 3.1.2
* ember-cli-babel -> 6.17.2
* ember-cli-htmlbars -> 2.0.5
* ember-cli-htmlbars-inline-precompile -> 1.0.5
* ember-qunit -> 3.5.3

I'll see if I can pinpoint wich package in particular is causing the problem.

**Comment by Nippius** [comment]
It appears the issue is related to ember-cli-babel. Updating it to version 6.17.2 fixes the problem. I'll open an issue in their repository.

**Comment by locks** [comment]
Thanks for the update, closing the issue!
