### ISSUE TITLE
Bug with injection of a mocked service in tests when using ES6 classes

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#17116]
[Reproduction repo here](https://github.com/boris-petrov/ember-inject-mock-bug)

As you can see from the [last commit](https://github.com/boris-petrov/ember-inject-mock-bug/commit/9cc812a6af35813c77fe44b189037e68af85c233), when using an ES6 class, adding an (even empty) constructor causes the injection of the mocked service to fail.

**Comment by chriskrycho** [comment]
cc. @pzuraq: I’m thinking you probably have some insight into the behavior here.

**Comment by pzuraq** [comment]
You must pass `...arguments` to `super`, that’s how injections are assigned to the instance in current Ember. Once native classes officially land this will no longer be necessary, but services will also not be available during construction.

**Comment by boris-petrov** [comment]
@pzuraq - that fixed the problem. Thanks! There is so very little documentation about all of these things... I'm scrambling bits and pieces from here and there. :) Thanks again! I'll close this and the other issue.

**Comment by pzuraq** [comment]
Yep, it’s definitely fragmented, and we will fix that soon. Native classes haven’t officially shipped yet which is part of the reason for this, once they do we’ll officially document their usage.
