### ISSUE TITLE
Issue regarding precedence of helpers and properties in angle-bracket components

### ISSUE THREAD

**Issue by iezer** [emberjs/ember.js#17120]
If I have helper called `changeset` and also a property on a component called `changeset`, these two code examples work differently in Ember 3.4:

 1. `{{my-child changeset=changeset}}`  Passes in the "changeset" property
 1. `<MyChild @changeset={{changeset}} />` Calls the "changeset" helper with no arguments.

However, 2. works the same as 1. if you're using Ember 3.3 with [ember-angle-bracket-invocation-polyfill](https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill). As a result, users upgrading from Ember 3.3 with the polyfill to 3.4 might see some unexpected behavior.

This is the type of ambiguity that [RFC 308](https://github.com/emberjs/rfcs/pull/308) is trying to prevent but the deprecation and code mods haven't yet been implemented.

Reproduced in [this twiddle](https://ember-twiddle.com/6526c6906c05dd36cc5ff3937813c5c6?openFiles=templates.components.my-parent.hbs%2Ctemplates.components.my-child.hbs)

**Comment by rwjblue** [comment]
ember-template-lint includes a [no-implicit-this](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-implicit-this.md) specifically to catch this case in existing code. We should likely fix the polyfill to have consistent behavior to the real feature (always calling the helper), would you mind making an issue (or even a failing test PR)?

**Comment by iezer** [comment]
I've opened https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/issues/50 and when I have time I'll write the failing test.

**Comment by chancancode** [comment]
Unfortunately, this is probably "working as intended" (a.k.a. "probably too late to fix" now). [RFC 432](https://github.com/emberjs/rfcs/pull/432) propose to deprecate the second behavior. I would love to be proven wrong (about the "probably too late" part), but what I proposed in the RFC is probably the best we can do.

**Comment by chancancode** [comment]
(the polyfill should be updated to match the Ember behavior though)
