### ISSUE TITLE
Memory leak when changing routes

### ISSUE THREAD

**Issue by GavinJoyce** [emberjs/ember.js#17124]
It appears that there is a memory leak present in Ember versions 3.0, 3.1, 3.2, 3.3, 3.4 & 3.5 when changing routes which render hbs+js components. We first noticed this when looking into user reports of our app showing memory usage warnings in Safari.

I've created a reproduction in a simple Ember 3.5 app here: https://github.com/GavinJoyce/memory-lake. Every second, this app switches back and forth between an empty route and a route that renders 10k simple hbs+js components. When run in production build, you can see that the memory usage grows rapidly in clean installs of Chrome, Safari and Firefox:

**Chrome**

![chrome-canary](https://user-images.githubusercontent.com/2526/47076192-10ded880-d1f6-11e8-8eff-f685aa923d2d.gif)

the tab crashes after ~2 mins:

<img width="671" alt="screen shot 2018-10-17 at 09 58 19" src="https://user-images.githubusercontent.com/2526/47076317-58fdfb00-d1f6-11e8-978f-f3c8666f6bfc.png">

**Firefox**

![firefox](https://user-images.githubusercontent.com/2526/47076209-1b996d80-d1f6-11e8-9f1e-a3bcdac0a329.gif)

**Safari**

![safari](https://user-images.githubusercontent.com/2526/47076224-23591200-d1f6-11e8-8678-c53a000e9df4.gif)

I have yet to dig into why this might be happening, I'll do so later today

**Comment by rwjblue** [comment]
Thank you for reporting!

**Comment by GavinJoyce** [comment]
> The report says 3.0 -> 3.5, does that mean each version has the issue or that you noticed when going from 3.0 to 3.5

I've tested a few versions, 3.0, 3.1 and 3.5 I think. All exhibited the same memory leak.

> The repro has the template only glimmer components optional feature enabled, is the optional feature related (or was that just part of you tracking down a repro)

I don't believe that it's related, I added the option feature as part of my investigations. I believe that the  memory leak is present when rendering hbs+js components and not when rendering hbs only components. I'll verify both now

**Comment by GavinJoyce** [comment]
Actually, it does appear to happen with template only components too:

![template-only](https://user-images.githubusercontent.com/2526/47080856-037b1b80-d201-11e8-9408-71a9ebb849e1.gif)

**Comment by GavinJoyce** [comment]
I've confirmed it also happens with `"template-only-glimmer-components": false`

**Comment by GavinJoyce** [comment]
It does seem to be related to route transitions. Here's the same components being rendered and removed without a route transition, notice that the memory usage is static:

![without-route-transition](https://user-images.githubusercontent.com/2526/47081540-d0d22280-d202-11e8-9dcc-415ab75f58bc.gif)

**Comment by GavinJoyce** [comment]
I'm seeing a large number of BlockTrackers seemingly being retained:

<img width="1438" alt="screen shot 2018-10-17 at 12 01 37" src="https://user-images.githubusercontent.com/2526/47082106-818cf180-d204-11e8-9ea7-cdc4969fd543.png">

**Comment by GavinJoyce** [comment]
There's some context on efforts to track down and address recent memory leaks here:

https://discuss.emberjs.com/t/datadown-to-a-component-leads-to-memory-leak/14649

**Comment by GavinJoyce** [comment]
If I drill into the objects with the largest retained size, I come across many components are in a state of `"destroying"`:

<img width="1438" alt="screen shot 2018-10-17 at 13 42 14" src="https://user-images.githubusercontent.com/2526/47086954-ba33c780-d212-11e8-8aea-ed2409625085.png">

There seems to be a very large number of retained `ComponentStateBucket`s:

<img width="1440" alt="screen shot 2018-10-17 at 13 44 01" src="https://user-images.githubusercontent.com/2526/47086985-ccae0100-d212-11e8-8eeb-c6bad649d4db.png">

**Comment by GavinJoyce** [comment]
It looks like we may be leaking backburner timers, `timers.length` seems to grow each time I switch route and the memory profiler seems to point there too:

![timers](https://user-images.githubusercontent.com/2526/47241427-8fe53400-d3e3-11e8-8313-ef987bb68343.gif)

Here's the `timers` after switching in and out of the route one more time:

![timers2](https://user-images.githubusercontent.com/2526/47241498-cfac1b80-d3e3-11e8-8c58-82eb443e7435.gif)

**Comment by GavinJoyce** [comment]
Hmm, it appears that I may have caused the memory leak by incorrectly using a `run.later` in a component. I'm not using [`ember-lifeline`](https://github.com/ember-lifeline/ember-lifeline) or [`ember-concurrency`](http://ember-concurrency.com) in my test app and I forgot to ensure that the `run.later` was cancelled before the component was destroyed.

Without the `run.laters`, the browser tab memory seems too grow to about 1GB before being garbage collected and dropping down again:

![no-bug](https://user-images.githubusercontent.com/2526/47242343-55c96180-d3e6-11e8-89fe-55dc8566641e.gif)

**Comment by GavinJoyce** [comment]
I'm going to close this issue as it was my mistake in the test app which resulted in the significant memory leak (I [fixed it here](https://github.com/GavinJoyce/memory-lake/commit/59a3cdb44e64f10be46b9ebdf8f87624e3bb1bf8)). I've also verified that the significant memory growth is no longer present in chrome or safari:

![safari1](https://user-images.githubusercontent.com/2526/47242857-100d9880-d3e8-11e8-870e-c8bb8644f48f.gif)

We still have a memory leak in our app which I'll continue to look into. If I find what looks like a framework memory leak, and I can reproduce it, I'll open a new issue
