### ISSUE TITLE
Queryparam issue on long running transitions

### ISSUE THREAD

**Issue by thebala** [emberjs/ember.js#17123]
When transitioning from one route to other route, if the before transition is incomplete, the queryparams of the former route is being set to the latter route. This is because, we get the former route's transition object as active transition in [_processActiveTransitionQueryParams](https://github.com/emberjs/ember.js/blob/bef860222ac1ce8b86c9e2ed129e24beb0c07132/packages/%40ember/-internals/routing/lib/system/router.ts#L1016) and we merge those with the current targetRoute. 

The issue can be reproduced in this [twiddle](https://ember-twiddle.com/6498417d30cff88091709cab4cb5b995?openFiles=routes.contact.js%2C).

**Comment by gokatz** [comment]
Is it enough if we check [here](https://github.com/emberjs/ember.js/blob/bef860222ac1ce8b86c9e2ed129e24beb0c07132/packages/%40ember/-internals/routing/lib/system/router.ts#L1010) that the `activeTransition` is as same as that of the `targetRouteName`, as refreshing the route after qp being set will trigger the current route refresh?

like,
```js
this._routerMicrolib.activeTransition.targetName === targetRouteName
```

**Comment by pixelhandler** [comment]
@thebala I see the example twiddle you shared, can you explain your steps to reproduce, e.g. and what you expected, and what is actually happening? E.g. ...

Steps to reproduce
- click on about/contact route
- click on other one

Expected Result
- qp value is...

Actual Result
- qp did...

That would help clarify how to work on this issue

**Comment by gokatz** [comment]
**Steps to reproduce**

- click on **contact** route
- click on `setQp` button. This will set a quary param, `qp` with value "contact" in th contact route.
-  click on **about** route
-  click on **contact** route
-  click on **about** route before the loading state of **contact** route finishes (increasing the timeout may help)

**Expected Vs Actual Result**

After performing all the steps mentioned above, the url expected is `/about`. But, the actual url will be `/about?qp=contact` the query param value of the `contact` route is being set to the `about` route.

**Comment by gokatz** [comment]
any update on this?

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue.

This issue has been open for a while without anyone jumping in to fix it. The reality is that unless you want to fix the bug itself, it will likely stay that way.

The time of core team members is very limited, and we all want them to focus  on moving the framework forward (high-leverage things), leaving fixing of edge case bugs to "fringe volunteers", such as you and me.

By closing some old issues we reduce the list of open issues to a more manageable set. Let me know if you think this is a mistake and that the issue should stay open.
