### ISSUE TITLE
How to create dynamic model in ember data

### ISSUE THREAD

**Issue by pranavdubase** [emberjs/ember.js#17139]
I am trying to create a dynamic ember data models.I have tried this code in `route\user` like:
``` 
var tableColumns = {
   name: DS.attr('string'),
    surname: DS.attr('string')
};
let store = this.get('store');
Ember.getOwner(store).register('model: user', DS.Model.extend(tableColumns));
```
after creating a model for `this.store.findAll(user)`. but it's not working and it shows model user is not defined.

**Comment by pixelhandler** [comment]
@pranavdubase thanks for asking the question :)

The best place will be to reach out in the community forum or chat, see https://www.emberjs.com/community/ 

We use the issues here to track bugs in the Ember.js framework itself. You'll get more help using the Discord chat than on the GitHub issue tracker.

**Comment by pixelhandler** [comment]
@pranavdubase I'll close this for now, please reach out in the forums / chat for help with your question. We use the issue tracker for bug reports.
