### ISSUE TITLE
Question: Is there a way to force re-render a component?

### ISSUE THREAD

**Issue by sarbbottam** [emberjs/ember.js#17141]
Hi there,

With respect to https://github.com/linkedin/self-focused/issues/2, I am wondering if there is a way to force re-render a component so that `didRender` life cycle hook can be executed.

Also, I am a bit confused on the following behavior of the existing test app in https://github.com/linkedin/self-focused/tree/master/packages/ember-self-focused.

After loading:

- Click "Topics"
- Click "Components" (`didRender` is invoked )
- Click "Components" again. (`didRender` is not invoked )
- Observe focus state set at the "Topics" level.

However

- Click "Topics"
- Click "Router"
- Click "Components" (`didRender` is invoked )
- Click "Components" again. (`didRender` is invoked)
- Click "Components" again. (`didRender` is not invoked )
- Observe focus state set at the "Topics" level.

I am wondering how `didRender` is getting invoked differently in the above scenarios:

Any pointer would be helpful. Thanks!

**Comment by pixelhandler** [comment]
@sarbbottam thanks for asking the question :)

The best place will be to reach out in the community forum or chat, see https://www.emberjs.com/community/ 

We use the issues here to track bugs in the Ember.js framework itself. You'll get more help using the Discord chat than on the GitHub issue tracker.

**Comment by pixelhandler** [comment]
@sarbbottam I'll close this for now as it's more of a question than a bug report. Please reach out on the forum or chat
