### ISSUE TITLE
TransitionAbort raised in tests when redirecting

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember.js#17152]
See https://github.com/wagenet/ember-transition-abort-test which passes on latest and beta, but fails on canary, as visible here: https://travis-ci.com/wagenet/ember-transition-abort-test.

The commit that causes issues is 9b7e0f58542bb3bccbfdbb6cc2da1890b7ee4f06, though on the face of it, it should be unobjectionable.

**Comment by rwjblue** [comment]
Possible duplicate of #17150
