### ISSUE TITLE
v3.6.0-beta.2 RouterService doesn't update the currentRoute after a loading route is used

### ISSUE THREAD

**Issue by pieter-v** [emberjs/ember.js#17162]
If the route `slow` returns a promise, then the `slow-loading` route is entered.
After the promise is resolved, then transition to `slow` is completed.

The `currentRouteName` of the `RouterService` is correct updated, but the `currentRoute` still references the `slow-loading` route.

(I also tried it with canary)

See https://github.com/pieter-v/ember-loading for an example.

**Comment by pieter-v** [comment]
I added a child route with a param to the `slow` route.
In the `beforeModel` of the child route the `transition.to` points to the `slow_loading` route. So the parameter is not accessible in the beforeModel.

Run the example and use this url: http://localhost:4200/slow/123

**Comment by rwjblue** [comment]
Thank you for reporting! 

@chadhietala - Mind taking a look?

**Comment by chadhietala** [comment]
Looking into this now.

**Comment by pieter-v** [comment]
**ember@v3.6.0-beta.4**, 
I modified the example a little bit:
I added an `index` route which redirects to the `slow` route.
If I point my browser to  http://localhost:4200/slow, then everything works fine. If on the other hand I point my browser to  http://localhost:4200/ then when the `slow` route is active, the `currentRoute` still references the `slow_loading` route

@chadhietala @rwjblue I don't know if I should report this as a new bug or if this bug should be reopened
