### ISSUE TITLE
Contextual components invoked with angle-brackets don't work if they receive splattributes

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#17161]
I first thought it was a bug in [ember-element-helper](https://github.com/tildeio/ember-element-helper) so I reported it [here](https://github.com/tildeio/ember-element-helper/pull/1)

Then I found a reproduction that doesn't involve it at all, so this seems to be a bug in ember/glimmer with contextual component invoked with splattributes.

I created a failing test for this: https://github.com/emberjs/ember.js/pull/17160

**Comment by gabrielgrant** [comment]
IIUC according to #17160 this has been fixed in #17499 right?

**Comment by cibernox** [comment]
Yes, it is indeed fixed. I'll cose it now
