### ISSUE TITLE
 this.resource() with new this.route() in ember for highly nested routes not working

### ISSUE THREAD

**Issue by thilinadinith** [emberjs/ember.js#17175]
im in the process of upgrading ember1.x to 3.x and i have an issue with router where it was used this.resource for nested routes and now it is depreciated and changed to this.route

but when it comes to nested route its not working anymore if i futher explain, let say

```
this.resource( 'parent1', { path: '/' }, function() {

    this.route( 'someroute1', { path: '/' } );
    this.route( 'someroute2', { path: '/someroute2' } );


    this.resource( 'parent11', { path: '/app' }, function() {

      this.route( 'someroute11', { path: '/' } );
      this.route( 'someroute12', { path: '/someroute12' } );

      this.resource( 'parent111', { path: '/:paramid' }, function() {
      this.route( 'index', { path: '/' } );
      this.route( 'someroutewanttogo', { path: '/pathrouteiwanttogo' } 
  );
});
```
This was before and i was routing to the last route as
`
this.transitionTo('parent111', id)`
this worked perfectly.

then i changed resource to route as below

```
this.route( 'parent1', { path: '/' }, function() {

    this.route( 'someroute1', { path: '/' } );
    this.route( 'someroute2', { path: '/someroute2' } );


    this.route( 'parent11', { path: '/app' }, function() {

      this.route( 'someroute11', { path: '/' } );
      this.route( 'someroute12', { path: '/someroute12' } );

      this.route( 'parent111', { path: '/:paramid' }, function() {
      this.route( 'index', { path: '/' } );
      this.route( 'someroutewanttogo', { path: '/pathrouteiwanttogo' } 
  );
});
```
then the route was not found in the route transitionTo() so then i tried to call

`this.transitionTo('parent1.parent11.parent111', id );`

but this is lost is nowhere as its not triggering controller of parent111 or either children.

**Comment by locks** [comment]
@thilinadinith have you moved the files to the right place in the project structure? For `parent1.parent11.parent111 `'s controller, it should be `app/controllers/parent1/parent11/parent111.js`, for example.

**Comment by thilinadinith** [comment]
my project structure is like 
parent 1
parent 11
parent 111

according to you it should be 
parent1 
 -> parent11
    -> parent111

i will change and let you know. thanks for the fast response

**Comment by thilinadinith** [comment]
the child is trying to read parents model in its model(){} but where im extending parent's route to child. in there im getting issue for `this.modelFor( 'parent11' ).get( 'attribute' );`
child route is extended as 
```
Parent11 import from 'path'
export default Parent11.extend( {})
```

**Comment by thilinadinith** [comment]
@locks  i tried  `this.modelFor( 'parent1.parent11' ).get( 'attribute' ); `
as well but no luck.

error im getting is 

> "TypeError: Cannot read property 'get' of undefined
>     at Class.model (http://localhost:4204/assets/project.js:10387:73)
>     at Class.superWrapper [as model] (http://localhost:4204/assets/vendor.js:58028:28)
>     at Class.deserialize (http://localhost:4204/assets/vendor.js:50248:19)
>     at applyHook (http://localhost:4204/assets/vendor.js:62016:30)
>     at UnresolvedHandlerInfoByParam.runSharedModelHook (http://localhost:4204/assets/vendor.js:62467:20)
>     at UnresolvedHandlerInfoByParam.getModel (http://localhost:4204/assets/vendor.js:62692:19)
>     at tryCatcher (http://localhost:4204/assets/vendor.js:64032:21)
>     at invokeCallback (http://localhost:4204/assets/vendor.js:64204:33)
>     at publish (http://localhost:4204/assets/vendor.js:64190:9)
>     at http://localhost:4204/assets/vendor.js:56431:16"

**Comment by thilinadinith** [comment]
its is working i misspelled the parent1 in  ` this.modelFor( 'parent1.parent11' ).get( 'attribute' ); `

thank you for the support @locks
