### ISSUE TITLE
input type="range" shows unwanted value on the Edge browser

### ISSUE THREAD

**Issue by Edward-Chen-CN** [emberjs/ember.js#17181]
I have created a new project to test this. I have added 3 range slider, only the third one with pure html code work as it is on the edge browser. The rest of two give a current value above the range slider and mass the slider UI.  Ember version - 3.4.6. Edge browser version - 42.17134.1.0.

screenshot of result: https://ibb.co/jW8uYL

application.hbs
`{{!-- The following component displays Ember's default welcome message. --}}`
`{{input type="range"}}`
`<input type="range" min="0" max="10" value={{someVal}}>`
`<input type="range" min="0" max="10">`
`{{welcome-page}}`
`{{!-- Feel free to remove this! --}}`
`{{outlet}}`

**Comment by lolcatchuplol** [comment]
> @lolcatchuplol I created an ember-twiddle as an example reproduction, but that doesn't run in Edge.
> 
> * https://ember-twiddle.com/8c98e51e28a4d1610d434ea79c91c17e?openFiles=templates.application.hbs%2C
> 
> Have you reached out to the community forum or chat ? - https://emberjs.com/community/

Thanks, I have not reached out to the community forum as this is my first time of using ember. But I will try it.

**Comment by pixelhandler** [comment]
@lolcatchuplol if you found a work around can you update this issue?

**Comment by Kilowhisky** [comment]
I am also having this exact problem. It seems to have to do with setting any `value` on the slider. If value is omitted, everything works fine.  What is interesting is that the second to last one shouldn't have anything to do with ember and yet it still happens on ember only applications. 

It doesn't matter how the value is assigned either. As long as it is ember related the value will appear.

```
            <Input type="range" />
            <Input type="range" value="50" />
            <Input type="range" @value="50" />
            <input type="range" value="50" />
            <input type="range" />
```

![image](https://user-images.githubusercontent.com/7075666/75491180-612d8500-596a-11ea-8746-17f5c5dbd2ff.png)

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. 

This seem like more of a question than a bug report/issue, and therefore better suited for the forums: https://discuss.emberjs.com/

Also, the reality for any open-source framework, relying on individuals to put in the work, is that there isn't always time to answer all questions.

If you want to pay back to the community, one easy thing is to ask one question in the forum (your current one), and also try to answer 2 questions from other people.

If you think this is an error, a reproduction of the bug and a more extensive explanation would be a good start. Then, if others agree it's a bug, the second step is often to dig in and write a patch to fix the bug.

I'll be closing this for now though, to keep the list of open issues manageable. I hope you understand.
