### ISSUE TITLE
'debounce' shifts execution of 'later' callback

### ISSUE THREAD

**Issue by azhiv** [emberjs/ember.js#17210]
Good day!
Recently I've encountered a weird problem facing unexpected behaviour when using `debounce`.
More specifically: for an unknown reason the result is different for the two calls below:
`debounce(this, this.setIdle, 1000);`
`debounce(this, () => this.setIdle(), 1000);`
I know it may sound crazy but this is the only difference. The first statement shifts execution of another `later` callback (not that it's run with a little delay - it literally blocks the later's callback execution which is not expected) while the second one executes both callbacks independently.
Here is the [twiddle](https://ember-twiddle.com/ca3339ed2631bf958b47efe790e198d6?openFiles=controllers.application.js%2C).

**Comment by bekzod** [comment]
thanks for bug report, fixed in https://github.com/BackburnerJS/backburner.js/pull/357, 
you shouldn't be using debounce like `debounce(this, () => this.setIdle(), 1000);` with anonymous function it won't debounce `this.setIdle` since you are giving new function each time when you call `debounce(this, () => this.setIdle(), 1000);` and internally it cannot match up anonymous function with other anonymous functions so each debounce will be debounced separately, hope makes sense

**Comment by azhiv** [comment]
@bekzod  Makes perfect sense, thank you!

**Comment by andreyfel** [comment]
@rwjblue can we get a new 3.4 patch release containing this fix?

**Comment by rwjblue** [comment]
Whoops, shouldn't have closed this here yet. 

Yes, we will definitely backport the fix to 3.4.

**Comment by pixelhandler** [comment]
Looking at  https://www.emberjs.com/api/ember/release/functions/@ember%2Frunloop/debounce

> Delay calling the target method until the debounce period has elapsed with no additional debounce calls. If debounce is called again before the specified time has elapsed, the timer is reset and the entire period must pass again before the target method is called.

And the comment on the twiddle:

> The issue 'shifts' execution of the 'later' statement thus next log entry will only appear in 1 sec after you stop hitting the button 

How is that not the indented behavior of `debounce(this, this.setIdle, this.keepAliveTimeout)`

And the second `debounce(this, () => this.setIdle(), 1000)` gives a new function to `debounce` so every one of those we be called a second later.

Maybe I'm missing something.

**Comment by bekzod** [comment]
@pixelhandler there is bug verification as failing test https://github.com/BackburnerJS/backburner.js/commit/693250f5ee18a48f7c0a5b16256df5e71403e719#diff-4b3e9f2ef17528d4fa14e8ed544af272R432

agree usage of `debounce(this, () => this.setIdle(), 1000)` is not correct, even if it was correctly called like `debounce(this, this.setIdle, 1000)` debounce still behaving incorrectly, given twiddle is a bit convoluted, the issue can be illustrated with more simple logic which I can post if it is really needed

**Comment by bekzod** [comment]
this can be closed since fix merged, and released in 3.6.0 https://github.com/emberjs/ember.js/blob/master/CHANGELOG.md#v360-december-6-2018

**Comment by locks** [comment]
Closing, thank!
