### ISSUE TITLE
[Module Unification] Routes can only be nested two levels deep

### ISSUE THREAD

**Issue by buschtoens** [emberjs/ember.js#17217]
Defining routes nested more than two levels deep or even just providing a callback does not work MU applications and triggers the error below.

```
requirejs.js:74 Uncaught TypeError: Cannot read property 'defaultType' of undefined
    at RequireJSRegistry._checkDefaultType (requirejs.js:74)
    at RequireJSRegistry._detectModule (requirejs.js:63)
    at RequireJSRegistry.has (requirejs.js:85)
    at Resolver._serializeAndVerify (resolver.js:118)
    at Resolver.identify (resolver.js:94)
    at Resolver.resolve (resolver.js:104)
    at Class.resolve (index.js:149)
    at Class.resolve (index.js:15)
    at Class.superWrapper [as resolve] (utils.js:308)
    at _resolve (container.js:807)
```

Exemplary failing router:

```js
Router.map(function() {
  // this fails
  this.route('foo', function() {
    this.route('bar', function() {
      // You don't even need to register a third-level route. Just providing the
      // callback triggers the error, likely because of the implicit `index` route.
      // this.route('qux');
    });
  });

  // this works just fine
  this.route('one', function() {
    this.route('two');
  });
});
```

Reproduction repo: https://github.com/buschtoens/mu-nested-routes

**Comment by buschtoens** [comment]
I assume the [`glimmer-wrapper` in `ember-resolver`](https://github.com/ember-cli/ember-resolver/blob/master/mu-trees/tests/unit/resolvers/glimmer-wrapper/resolve-test.js) is the correct place to submit a failing test case to.

**Comment by NullVoxPopuli** [comment]
@buschtoens have you tried the fallback resolver?
the fallback resolver is currently what https://emberclear.io uses

**Comment by buschtoens** [comment]
@NullVoxPopuli I am already using the fallback resolver, as can [be seen here](https://github.com/buschtoens/mu-nested-routes/blob/master/src/resolver.js). But that is actually a very good point to make. I'll give the `glimmer-wrapper` a try instead. Thanks a lot!

**Comment by buschtoens** [comment]
@NullVoxPopuli No luck here. Apparently `fallback` and `glimmer-wrapper` use the same buggy code paths.

**Comment by NullVoxPopuli** [comment]
excellent! (one less thing to fix)

**Comment by buschtoens** [comment]
I think I've pinned down the issue. So in [L90](https://github.com/glimmerjs/glimmer-resolver/blob/42cfa17ad5bb9fe69a50f028707e58efa4bf91ba/src/resolver.ts#L89-L90) `s` looks like this:

```js
{
  type: "controller",
  name: "index",
  namespace: "foo/bar",
  collection: "routes",
  rootName: "dummy"
}
```

The resolver cannot find the `Controller`, as it is not explicitly defined and thus should be auto-generated. But before resorting to auto-generation, the resolver tries as to find a fitting addon first in [`L92-L100`](https://github.com/glimmerjs/glimmer-resolver/blob/42cfa17ad5bb9fe69a50f028707e58efa4bf91ba/src/resolver.ts#L92-L100).

`s` then looks like this:

```js
{
  type: "controller",
  name: "index",
  namespace: undefined,
  collection: "routes",
  rootName: "foo/bar"
}
```

This is then serialized as `controller:/foo/bar/routes/index` in [`_serializeAndVerify`](https://github.com/glimmerjs/glimmer-resolver/blob/42cfa17ad5bb9fe69a50f028707e58efa4bf91ba/src/resolver.ts#L123-L127) by [`serializeSpecifier`](https://github.com/glimmerjs/glimmer-di/blob/a0afcb0d87f06fde3c1870ec2466820434accfa9/src/specifier.ts#L23-L32). It is then deserialized in [`has`](https://github.com/ember-cli/ember-resolver/blob/7647d14d242b08d40305dfdbef2e028f1a19b4de/mu-trees/addon/module-registries/requirejs.js#L69) as:

```js
{
  type: "controller",
  name: "index",
  namespace: "routes",
  collection: "bar",
  rootName: "foo"
}
```

Notice how this differs from the prior specifier:

```diff
{
  type: "controller",
  name: "index",
-  namespace: undefined,
+  namespace: "routes",
-  collection: "routes",
+  collection: "bar",
-  rootName: "foo/bar"
+  rootName: "foo"
}
```

What ultimately causes the `TypeError` then is that that [`_checkDefaultType`](https://github.com/ember-cli/ember-resolver/blob/7647d14d242b08d40305dfdbef2e028f1a19b4de/mu-trees/addon/module-registries/requirejs.js#L64) expects the specified collection to always exist:

```js
  _checkDefaultType(specifier) {
    let {defaultType} = this._config.collections[specifier.collection];
    return defaultType && defaultType === specifier.type;
  }
```

A simple fix to make this safer would be:

```js
  _checkDefaultType(specifier) {
    let { defaultType } = this._config.collections[specifier.collection] || {};
    return defaultType && defaultType === specifier.type;
  }
```

However this does not fix the inconsistent de-/serialization. But is this actually a problem we need to worry about? The input specifier already looks off to me.

In any case, I'll prep a PR for the above fix and test it.

**Comment by gossi** [comment]
This can be marked as closed 😃  Maybe cut a release for ember-resolver that contains the fix (it's already on master)

**Comment by locks** [comment]
Closing, thanks!
