### ISSUE TITLE
mouseenter: Object doesn't support property or method 'contains'

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#17225]
With `"jquery-integration": false` I'm getting `Object doesn't support property or method 'contains'` in IE11. It may have something to do with SVG.

![screenshot 2018-11-22 at 12 22 49](https://user-images.githubusercontent.com/382061/48902775-83745100-ee51-11e8-951e-13dcb7c15fa5.png)

https://github.com/emberjs/ember.js/blob/62643188404d1b8398cb133ac30cc0e866318a8d/packages/%40ember/-internals/views/lib/system/event_dispatcher.js#L338

<br>
Having to delay our jQuery-removal celebrations :)

**Comment by rwjblue** [comment]
Thanks for reporting! 

@simonihmig - Any ideas off the top of your head?

**Comment by simonihmig** [comment]
@amk221 I assume this was an `mouseenter` event, not `mouseover` as in your title, right?

> It may have something to do with SVG.

Indeed. I quickly booted my VM with IE11, and it seems it doesn't support `Node#contains()` on SVG elements. 🙄

I had a quick look how the jQuery-based implementation works around this, and it seams jQuery (or rather Sizzle) has a fallback implementation here: https://github.com/jquery/jquery/blob/e743cbd28553267f955f71ea7248377915613fd9/external/sizzle/dist/sizzle.js#L860-L868

I guess we can flag this as a bug then! I can try to provide a fix hopefully soon...

**Comment by pixelhandler** [comment]
@rwjblue is ie11 w/o jquery officially supported ? if so this is a bug correct?

**Comment by rwjblue** [comment]
Yep, updated the labels.
