### ISSUE TITLE
Components created with a custom component manager cannot inject services

### ISSUE THREAD

**Issue by jordpo** [emberjs/ember.js#17236]
Because of the change made [here](https://github.com/emberjs/ember.js/pull/16854), when using a custom component manager, the `factory` argument in the `createComponent` is not 'container aware'. So when you create the component instance and try to access a property or method on an injected service, you get an error => `“Attempting to lookup an injected property on an object without a container, ensure that the object was instantiated via a container.”`.

Here's a simple example of a component that uses a basic component manager. In this case, the error happens when you try to access the `someString` property, which depends on the `intl` service. 

https://gist.github.com/patrickberkeley/6ebc14fab616b61ed4534d2ae588a5e9#file-component-js

Is this the intended behavior or should components created by a custom component manager have access to DI and injected services? If they should, is there an example of how to do that in this case?

**Comment by pixelhandler** [comment]
@jordpo is `setComponentManager` even public API? 

- https://gist.github.com/patrickberkeley/6ebc14fab616b61ed4534d2ae588a5e9#file-component-js-L2
- https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/glimmer/lib/utils/custom-component-manager.ts#L6-L15

**Comment by patrickberkeley** [comment]
@pixelhandler yup as far as we know `setComponentManager` is public. Custom component managers were released in 3.4. The release [notes](https://www.emberjs.com/blog/2018/10/07/ember-3-4-released.html#toc_new-features-2) and [RFC](https://github.com/emberjs/rfcs/blob/master/text/0213-custom-components.md) both mention it (that's all the info we've found on component managers).

Yes, we have reached out on Discord in the #help room numerous times over the past few weeks regarding our questions on component managers. But have gotten little/no response. It seems like there are only a few (core?) people who have used or know about this functionality.

The reason we opened an issue here is that is what was requested by @rwjblue here: https://github.com/emberjs/ember.js/pull/16854#issuecomment-442567954. We are happy to use the appropriate forum whatever that may be. We are just hoping to get clarity on how to use component managers.

**Comment by jordpo** [comment]
@pixelhandler Yeah I think this could be a documentation / clarity issue. It is public API but very cutting edge. I would imagine more people will get confused by this. 

My original question / comment on the associated PR was why we are passing in the super class as an argument to `createComponent` instead of the component class / factory itself. By passing in the super class, you need to explicitly `setOwner` on the instance which is confusing as a required step.

**Comment by jordpo** [comment]
Here's an example of this extra step that is required https://github.com/rwjblue/sparkles-component/blob/master/addon/component-managers/sparkles.ts#L29

**Comment by rwjblue** [comment]
Sounds good, I'll go ahead and close...
