### ISSUE TITLE
draggable attribute does not honor explicit false

### ISSUE THREAD

**Issue by lindem** [emberjs/ember.js#17232]
I have created a repository to show the issue at https://github.com/lindem/draggable-attr

Parts of that repository's README are reproduced here: 

---

The alleged bug affects [the `draggable` attribute on HTML elements](https://www.w3.org/TR/html51/editing.html#the-draggable-attribute).

It seems that ember does not allow to set the draggable attribute explicitly to
`"false"`, which is a legitimate value for the attribute and for example prevents `img` and
`a` elements from being draggable.

This repository uses a curly component with an `attributeBinding`. It seems that
whenever a non-null value is set to the property, the result is <strong>always</strong>
`draggable="true"`, which is wrong.

---

Is that a bug (according to spec, it is)? Is it expected? Can I remedy this for curly components? How? Can I help to fix it, if it is a bug?

And grand apologies if this is not a bug but clearly documented somewhere obvious.

**Comment by timo-lindemann-victors** [comment]
I extended the [example application](https://github.com/lindem/draggable-attr) to show that angle-brackets and normal (non-component) are also affected. "Static" HTML (not depending on properties) work, though.

This means that there is no workaround except making a tagless component and branching over static HTML in the template.

The property is correctly available in the template context, it also has the intended value. It is just the actual attribute that is set incorrectly, and it is the only attribute I have seen so far that does this.

**Comment by pixelhandler** [comment]
@lindem it appears there is a bug with using `attributeBindings` and a `draggable` attribute as `'true'` or `'false`. And the work around maybe to refactor to use a tagless component, `tagName: ''`.

**Comment by rwjblue** [comment]
I submitted https://github.com/lindem/draggable-attr/pull/3 to show how this needs to be done. In this case, since Ember is setting `el.draggable = value` you can't use the strings `'true'` and `'false'` (because both are TRUE!!!!!!), instead you have to use the values `true` and `false` directly.

Thanks for putting together such an awesome demo repo, it really was a pleasure to dig into. 😸

**Comment by lindem** [comment]
To clarify further: I am criticizing that it is not obvious that we cannot, as the spec mandates it, set these strings, but that ember tries to anticipate doing the right thing by reacting to `true`, `false`,  and `null` (the javascript values, not the strings).

I can live with it, and I actually have no idea where Ember should have documented that draggable *is being interpreted* instead of being "just another attribute that is freely settable", but I feel like it really should be documented somewhere.

But then again, `draggable` is such an oddball of an attribute anyway...
