### ISSUE TITLE
`Ember.computed.oneWay` teardown is "resetting" the property in an inner component

### ISSUE THREAD

**Issue by gitKrystan** [emberjs/ember.js#17243]
We’ve found a real stumper of a regression in our app that git bisect says is caused by this commit (https://github.com/emberjs/ember.js/commit/65c20ab632dcd1ecd1256a14fe5ccce83ebc6953) in 3.5.0-beta.3.

We have two components. A property is passed in to the outer component, where we use `computed.oneWay` to duplicate the property, then pass that into the inner component, where it is used directly (not aliased or mutated). Our setup is similar to what is shown in [this Twiddle](https://ember-twiddle.com/46abef18e16555576668b771c16cd45d), though I wasn’t able to repro the bug on Twiddle. The property is computed once with some default values, then again on `didInsertElement` after we have done some measuring.

In production only, it appears that the property gets set to the default, then updated to the correct final value…then set back to the original (incorrect) value. This only happens in the inner component, even though we just pass the value in directly from the outer component and do not alias it or mutate it in the inner component. 

Adding a no-op observer on the `oneWay` property appears to “fix” the issue, which makes sense given the PR description for that commit (https://github.com/emberjs/ember.js/pull/16978), though I admittedly don’t understand that code well enough to understand the mechanism.

**Comment by bekzod** [comment]
Will look when I get time for this :)

**Comment by bekzod** [comment]
@gitKrystan pocked around, couldn't reproduce can you post repro project here ?

**Comment by mupkoo** [comment]
I have similar issue with Ember version 3.5.1. I have aliased my model using the `alias` computed helper and whenever the model changes the property is not updating. If I use the model property instead of the alias, everything is working. This is happening only on production as well. It is working correctly in development and the tests are passing as well.

**Comment by bekzod** [comment]
@mupkoo would be nice if you share reproduction repo or make failing test for ember :)

**Comment by mupkoo** [comment]
I tried to reproduce it in a new project, but I couldn't.

---

Here is a snippet from my project

```javascript
import Controller from '@ember/controller';
import { computed } from '@ember/object';
import { alias } from '@ember/object/computed';

export default Controller.extend({
  queryParams: ['page', 'term'],
  page: 1,
  term: '',

  meetings: alias('model'),

  isEmptyStateVisible: computed('meetings.[]', 'term', function () {
    return !this.term && this.meetings.length === 0;
  })
});
```

```handlebars
{{#unless isEmptyStateVisible}}
  {{ search-input value=term onchange=(action "filter") }}
{{/unless}}

{{#each meetings key="id" as |meeting|}}
  {{ meeting-item
      meeting=meeting
      ondelete=(action "deleteMeeting" meeting)
      detailsLinkParams=(array 'meetings.show' meeting)
      editLinkParams=(array 'meetings.show.edit' meeting)
      class="test-meeting" }}
{{/each}}
```

If I remove the `isEmptyStateVisible` computed property, that depends on `meetings.[]`, the code list is re-rendered as expected.

**Comment by mupkoo** [comment]
Changing `computed('meetings.[]'...` to `computed('model.[]'...` is fixing the problem as well

**Comment by gitKrystan** [comment]
@chancancode and I are going to look into this either today or Wednesday.

**Comment by gitKrystan** [comment]
I deployed master since #17487 was merged, and this issue is fixed in our app. 👌
