### ISSUE TITLE
"run.next:  multiple calls to next share coalesce callbacks into same run loop" test is flaky

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#17367]
It seems that when run on IE11 the `run.next:  multiple calls to next share coalesce callbacks into same run loop` test is sometimes failing on CI for unknown reasons.

see https://travis-ci.org/emberjs/ember.js/jobs/467354719 for example

/cc @rwjblue

**Comment by locks** [comment]
Closing as no longer relevant.
