### ISSUE TITLE
"Assertion Failed: You modified "activatedModifier" twice...

### ISSUE THREAD

**Issue by anpenava** [emberjs/ember.js#17372]
`"Assertion Failed: You modified "activatedModifier" twice on <frontend-client@component:text-field::ember376> in a single render. It was rendered in "component:text-field" and modified in "component:text-field". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details."`

I was just wondering if this is different error or the same as "You modified [property] twice...".

**Comment by pixelhandler** [comment]
@anpenava have you reached out to the community https://emberjs.com/community/ perhaps this would get more feedback on the discussion form or the Discord chat. 

We typically use the issues here on Github for bug reports.

**Comment by anpenava** [comment]
Ok no problem thank you, I will check on discord .
