### ISSUE TITLE
Wrong assertion for local variable shadowing helper

### ISSUE THREAD

**Issue by dguettler** [emberjs/ember.js#17370]
Affected: Ember 3.6
Related PR: https://github.com/emberjs/ember.js/pull/17132

Code causing an issue:
```
{{#with (changeset model EditSiteGroupValidation) as |changeset|}}
  {{site-group-form changeset=changeset
                    onSubmit=(route-action "update")
                    onCancel=(route-action "cancel" changeset)}}
{{/with}}
```

Error raised: 
```
Cannot invoke the `changeset` helper because it was shadowed by a local variable (i.e. a block param) with the same name. Please rename the local variable to resolve the conflict.
```

Changing above code to:
```
{{#with (changeset model EditSiteGroupValidation) as |model|}}
  {{site-group-form changeset=model
                    onSubmit=(route-action "update")
                    onCancel=(route-action "cancel" model)}}
{{/with}}
```
passes compilation and does not raise an error.

Expected:
Original code should not raise an error as `changeset` is not invoked in the block.

**Comment by pixelhandler** [comment]
Well, I think it's a bad idea to use a block param and shadow a helper, I like the error. We ran into this and changed our block param variable name. I thought the error was helpful, but it was a little confusing at first, then I read `Please rename the local variable to resolve the conflict.` and it made more sense.

**Comment by chancancode** [comment]
@rwjblue yep this is a bug
