### ISSUE TITLE
[docs] dead link to w3.org wai-aria documentation

### ISSUE THREAD

**Issue by hakilebara** [emberjs/ember.js#17381]
https://github.com/emberjs/ember.js/blob/a5f870fd309e5008667b3ca2bf569721ac3c2f96/packages/%40ember/-internals/glimmer/lib/component.ts#L676

**Comment by hakilebara** [comment]
should be: https://www.w3.org/TR/wai-aria/#roles_categorization

**Comment by rwjblue** [comment]
Thank you for the issue! Would you have time to open a PR fixing the issue?

**Comment by kategengler** [comment]
Fixed by #17385
