### ISSUE TITLE
Services Tutorial Missing information.

### ISSUE THREAD

**Issue by BenReilly** [emberjs/ember.js#17417]
When running the tests on the [3.5.0 Services tutorial page](https://guides.emberjs.com/v3.5.0/tutorial/service/) I was getting multiple `Ajax authorization failed` errors on tests I hadn't touched. Naturally this had to do with the Simple Leaflet Maps service. The problem was that while the app was started with `LEAFLET_MAPS_API_KEY=<your key here> ember s` it didn't say anything about this in the test. it just says "restart `ember test --server` whenever you add a new service."

But some of the acceptance tests, since they are running the service (even if they are not testing it), need access to that environment variable to. The tutorial should be clear that the tests should be restarted with `LEAFLET_MAPS_API_KEY=<your key here> ember test --server`

FYI, running Windows 7, Bash command line.

**Comment by BenReilly** [comment]
Note that it looks like this may be the case with 3.6.0 as well

**Comment by locks** [comment]
Moved to referenced issue. Thanks for reporting!

**Comment by stephaniie2** [comment]
Writing as mentioned gives not required as an internal or external command. 

CMD: ember\super-rentals\LEAFLET_MAPS_API_KEY=mykey ember s

**Comment by BenReilly** [comment]
@stephaniie2 -- what terminal are you using? I have found that both CMD and PowerShell on windows fail frequently with most package managers and many CLIs. I recommend using GitBash

I also recommend this solution: https://stackoverflow.com/a/53980932/798348 as stubbing the service is a better solution than putting your api key in tests.

**Comment by kaisyversen** [comment]
I'm using Samsung note 8 Android phone .I do have a laptop but Windows
don't do it easy for me

Den tir. 22. jan. 2019, 16:16 skrev stephaniie2 <notifications@github.com:
