### ISSUE TITLE
ModelFor Issue in Engine’s Routes

### ISSUE THREAD

**Issue by kishoreyuvan** [emberjs/ember.js#17419]
Hi all, while working with modelFor in my engine, I got an issue. I have an engine ‘settings’ on my host Application. The settings’s routes.js looks like,

> this.route(‘users’, function() { 
>   this.route(‘list’, function() { 
>    this.route(‘details’, { path: ‘/:user_id’ }, function() { 
>     this.route(‘activities’); 
>    }); 
>   }); 
> });

when i try to get modelFor('users/list/details'). It will search the route with engine name like(settings.users/list/details). In Engine instance, Route(settings.users/list/details) is not available. it searching the route 'settings.users/list/details' instead of 'users/list/details'.

I found the reason is that route.js’s getEngineRouteName method will prepend the Engine name with Route Name(looks like settings.users/list/details). So the Route not found in Engine Instance.

I have tried this.controllerFor('users.list.details').model in activities route. It is working fine.

Is there any other way to retrieve the model of Parent Route? then why we need modelFor in route.js.

**Comment by rwjblue** [comment]
Can you provide a reproduction repo that we can use to understand the bug report better? As it stands, I'm not sure what we can do...

**Comment by kishoreyuvan** [comment]
@rwjblue I have tried this.modelFor('users.list.details') instead of this.modelFor('users/list/details') in settings engine. It's working fine. can you share the reasons behind this '/' to '.' conversion.

**Comment by kishoreyuvan** [comment]
While using dots, It's working fine. closing the issue.

**Comment by dguettler** [comment]
@rwjblue @kishoreyuvan 
IMO this is still a valid bug and causes an issue as far as I can tell
https://github.com/emberjs/ember.js/blob/52ddee883414f655511ef71d6f875f3fc16028e3/packages/%40ember/-internals/routing/lib/system/route.ts#L1412

`owner` is the engine. As far as I can tell the engine doesn't know of the prefixed route.
So if `owner.lookup('route:<full-name-here>')` gets called it returns `undefined`.
However if `owner.lookup('route:<name-within-engine>')` gets called it returns the correct route.

I have to override `modelFor` locally to make it work.

```
  modelFor(_name) {
    let name;
    let owner = getOwner(this);
    let transition =
      this._router && this._router._routerMicrolib
        ? this._router._routerMicrolib.activeTransition
        : undefined;

    // Only change the route name when there is an active transition.
    // Otherwise, use the passed in route name.
    if (owner.routable && transition !== null) {
      name = getEngineRouteName(owner, _name);
    } else {
      name = _name;
    }

    let route = owner.lookup(`route:${_name}`);
    // If we are mid-transition, we want to try and look up
    // resolved parent contexts on the current transitionEvent.
    if (transition !== null) {
      let modelLookupName = (route && route.routeName) || name;
      if (transition.resolvedModels.hasOwnProperty(modelLookupName)) {
        return transition.resolvedModels[modelLookupName];
      }
    }

    return route && route.currentModel;
  },
```
Only difference to the original is this line
```
let route = owner.lookup(`route:${_name}`);
```
where I'm passing `_name` instead of `name`

**Comment by ezy** [comment]
For anyone looking at this in future I adapted the above solution as follows with a manual transition as the `getEngineRouteName` method wasn't returning reliably for me.

```Javascript
import { getOwner } from '@ember/application';
import Route from '@ember/routing/route';

export default class NestedRoute extends Route {

  model() {
    const route = getOwner(this).lookup('route:index');
    return route && route.currentModel;
  }

  setupController(controller, model) {
    if (!model) {
      this.transitionExternalTo('home');
      return;
    }
    super.setupController(controller, model);
    controller.reset();
  }
}
```
