### ISSUE TITLE
`new A()` has been deprecated, please update to calling A as a function: `A()` - I am dont found in my app usage new..

### ISSUE THREAD

**Issue by eduscrakozabrus** [emberjs/ember.js#17427]
I am don't found in my app usage new..

**Comment by rwjblue** [comment]
The deprecation should print out the stack trace pointing at what in your application (or addons) is triggering the message.

Without a reproduction here, there is not much we can do to help you.  I'll leave this open for a couple of days (so you can gather that repro), but will close if we don't hear back with a demo.

**Comment by locks** [comment]
Closing due to lack of reproduction. If you encounter this problem again, let us know!
