### ISSUE TITLE
RouteInfo object is undefined in route/application.js

### ISSUE THREAD

**Issue by st-h** [emberjs/ember.js#17442]
Since the deprecation of `transition.queryParams` in ember 3.6 it seems there is no officially supported way to read the queryParams in `route/application` anymore. We currently make use of such to track application wide queryParams. (for instance we allow to set a token in order to accept an invitation which can be resolved from any route, or enable/disable the site tour which is not specific to one route)

The following application route leads to the output below within a otherwise fresh new ember app:

```
import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';

export default Route.extend({

  router: service(),

  beforeModel(transition) {
    console.warn("currentRoute in beforeModel: " + this.router.currentRoute);
  },

  model(params = {}) {
    console.warn("currentRoute in model: " + this.router.currentRoute);
    return {};
  },

  afterModel(model, transition) {
    console.warn("currentRoute in afterModel: " + this.router.currentRoute);
  }
});
```

```
currentRoute in beforeModel: undefined
currentRoute in model: undefined
currentRoute in afterModel: undefined
```

I am able to get `currentRoute` from any other route than the application route.

Is this intended and did I miss something?

**Comment by bastimeyer** [comment]
> I am able to get `currentRoute` from any other route than the application route.

That's because you already transitioned to another route. The application route itself is not the cause of this issue. Just call its model hooks again and see that it's working just fine.

#17430 seems to be related to this issue here. There's something wrong with the router's initialization and the state it is in before making/completing the first route transition.

**Comment by st-h** [comment]
> That's because you already transitioned to another route. The application route itself is not the cause of this issue. Just call its model hooks again and see that it's working just fine.

Phew, I wasn't aware that this would be the case. However, this clearly would be a breaking change, which would be really weird for a non major release, so I guess this actually is more of a regression here. 

And I can see another issue: If the transition away from the application route would be the problem, then there would be no way the application route could ever be the active route, as there is no other route defined in the application I used to reproduce (fresh new ember app with posted application route).

Actually I am not quite sure what would be a good place to call the model hook again. Afaik the model hook should be called by the framework and is used to invoke the actual implementation of the application.

Do you know of any resources which have more information about what you described, because I am actually a little confused right now, about what would be intended behaviour. I posted about this topic a few weeks ago in the discord channel, however haven't been able to get any input on this issues so far.

**Comment by st-h** [comment]
I think I misinterpreted the deprecation app in some way. Looks like making use of `transition.to.queryParams` is the correct replacement for queryparams that were read from `transition.queryParams`. Please feel free to close this issue in case the undefined currentRoute is intended.

**Comment by rwjblue** [comment]
I believe that is right, but maybe @chadhietala should confirm and close..
