### ISSUE TITLE
Google Translate doesn't work when collapsing whitespace ~

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#17458]
This is a bit of an odd one, I wasn't sure if to post or not....

Given:

```handlebars
{{#if this.viewMore}}
  {{~this.text~}}
{{else}}
  {{~this.text~}}
{{/if}}

<button onclick={{action "viewMore"}}>View more</button>
```

If the text has been translated with Google Translate in Chrome, then a `DOMException` is thrown when "View more" is clicked.

Remove the tidles however, and it works fine.

This is the simplest reproduction I could make: [demo repo](https://github.com/amk221/-ember-google-translate-dom-error/blob/master/app/templates/application.hbs). The real world app use case is slightly different but was discovered via entries in [sentry](http://getsentry.com).

I assume the issue isn't just limited to Google Translate, but rather that the DOM has changed and Ember was not expecting it to have.

<hr>

![screen recording 2019-01-09 at 10 36 am](https://user-images.githubusercontent.com/382061/50894763-fdf63180-13fb-11e9-9489-d395f453818a.gif)

**Comment by pixelhandler** [comment]
Can you describe the use of the `~` within the braces? e.g. `{{this.text~}}` Why is the `~` necessary?

**Comment by amk221** [comment]
I’ve since recreated this without the whitespace tildes. I’ll update with a
better example.

**Comment by amk221** [comment]
Ok updated.

**Comment by pixelhandler** [comment]
@amk221 once in awhile I run into bugs with stripping white space, not sure if it's a timing thing, is there a way you can not strip whitespace and ignore lint errors in the template?

**Comment by amk221** [comment]
👋🏻 did you see my previous message - I factored the white space out of
the reproduction.

**Comment by amk221** [comment]
@pixelhandler any idea on this?

**Comment by noahgelman** [comment]
@amk221 

Hey my dude, I fix your issue.

I forked your repo and fixed it for your example. Check the README.md.

I don't think this is something Ember can fix though. Google translate modifies the HTML of the page and you can only do so much when that happens.

**Description of Bug**
Displaying any static text in an Ember if-statement will break the rendering of that if-statement if Google Translate is used

**Fixing the Bug**
Move the static text into the Ember {{text}} variable. If only the {{text}} variable is inside if-statement, it won't break when you use Google Translate

https://github.com/noahgelman/-ember-google-translate-dom-error

**Comment by amk221** [comment]
Thanks, I thought that might be the case.

**Comment by amk221** [comment]
I thought I'd just mention why the proposed fix doesn't work for my use case:

See here that I need to use the `component` helper to renders the string, so I can't just build the string up front.

https://github.com/zestia/ember-wrap-urls/blob/master/addon/templates/components/wrap-urls.hbs#L3

**Comment by amk221** [comment]
Here is another example: 

https://ember-twiddle.com/75da56f221bb30ca67a35ae5d08e3f5f?openFiles=templates.components.my-component%5C.hbs%2Ctemplates.components.my-other-component%5C.hbs
