### ISSUE TITLE
join() in ArrayProxy

### ISSUE THREAD

**Issue by IAmJulianAcosta** [emberjs/ember.js#17450]
Currently ArrayProxy is missing a `join()` method, this is useful when you try to use it to concatenate a list of model names, trying to use [join helper](https://github.com/DockYard/ember-composable-helpers#join), but is failing because `PromiseManyArray` doesn't have implemented this method

Repro: https://ember-twiddle.com/067bd49f9dae87f20c8380162c01d70c

**Comment by pixelhandler** [comment]
@IAmJulianAcosta could you use the `content` of the proxy to `join` with?

```js
let a = ArrayProxy.create({
  content: A(["hello", "world"])
});
console.log(a.content.join(", "));
```

**Comment by IAmJulianAcosta** [comment]
Yes, that works, now the question is if is possible to implement `.join()` as an `ArrayProxy` method

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. 

Ember is moving away from ArrayProxy.

This issue has been open for a while without anyone jumping in to fix it. The reality is that unless you want to fix the bug itself, it will likely stay that way.

The time of core team members is very limited, and we all want them to focus  on moving the framework forward (high-leverage things), leaving fixing of edge case bugs to "fringe volunteers", such as you and me.

By closing some old issues we reduce the list of open issues to a more manageable set. Let me know if you think this is a mistake and that the issue should stay open.
