### ISSUE TITLE
Action as block parameter inside {{#each}} block

### ISSUE THREAD

**Issue by aamir-pk** [emberjs/ember.js#17473]
I have an action that is passed as block parameter. I can execute it is using a button from within component block but when it is inside {{#each}} loop, it is not executed when button is clicked. Please note that if I use a simple variable as block parameter that is well visible even inside {{#each}} loop. This problem only occurs in case of action.

```
{{#data-table toolbarID="#toolbar" editAction=(action "editUser")  as |editAction| }}
        <thead>....</thead>
        <button {{action editAction}}">Button</button> <!-- WORKS HERE -->
        <tbody>
            {{#each users as |user|}}
            <tr>
                <td>{{user.email}} </td>
                <td><button {{action editAction}} >Button</button><!-- DOESN'T WORK HERE PERHAPS BECAUSE IT IS INSIDE #EACH LOOP --></td>
            </tr>
            {{/each}}
        </tbody>
{{/data-table}}

```
And this is my super simple data-table component:

```
<table id="table" data-search="true" data-pagination="true" data-striped="true" data-toolbar={{toolbarID}}>
    {{yield this.editAction}}
</table>

```

**Comment by rwjblue** [comment]
This does indeed seem surprising. Would you happen to have a minute to put together a runnable demo (twiddle, demo repo, etc)?

**Comment by aamir-pk** [comment]
I have even simpler use case. It seems the problem is in {{#each}} helper. {{each}} block cannot even execute action that was defined in the component {{each}} helper belongs to. It cannot even execute/access action that was passed to the block and exist in controller.

I also tried a couple of other workarounds but there is no way an {{each}} block can invoke/access an action. 

I am wondering how come no one has ever came across this issue.

**Comment by aamir-pk** [comment]
Please close this issue. I figured out the reason. A third party Javascript library applied on table was capturing the click and that's why action was not executing.  Very sorry to raise this issue and wasting your valuable time.

**Comment by locks** [comment]
Thank you for the update @aamir-pk, and thank you for filling the issue! It is valuable feedback, even if the problem happened to be a third-party library :)
