### ISSUE TITLE
Empty `htmlSafe` string is treated as truthy

### ISSUE THREAD

**Issue by buschtoens** [emberjs/ember.js#17486]
The `{{if}}` (and `{{unless}}`, `{{with}}`) template helpers treat an empty `htmlSafe` string as truthy, while an empty string is treated as falsy and even an empty array is treated as falsy.

```hbs
{{if ''             'true' 'false'}} => false
{{if (html-safe '') 'true' 'false'}} => true
{{if (array)        'true' 'false'}} => false
```

[Ember Twiddle](https://ember-twiddle.com/f178e6a099aa8669b620e3b3c897a53f?numColumns=2&openFiles=controllers.application.js%2Ctemplates.application.hbs)

Interestingly I do not understand why an empty array is treated as falsy, when looking at the code:

https://github.com/emberjs/ember.js/blob/1bea9afaac785551a17bf7767ecf5468da63f97b/packages/%40ember/-internals/glimmer/lib/helpers/if-unless.ts#L41-L47

**Comment by rwjblue** [comment]
Empty arrays are a falsey value in Handlebars across the board ( see https://handlebarsjs.com/builtin_helpers.html for example).

I haven’t really thought much about the empty safe string scenario though. I’d have to check what Handlebars does there...

**Comment by buschtoens** [comment]
> Empty arrays are a falsey value in Handlebars across the board 

Sure! Sorry for expressing myself not clear enough. I know that `[]` is treated as `false` in Handlebars. I just don't understand how the `compute` method treats `[]` as `false`, since the ternary in L42 would treat `[]` as `true`.

**Comment by chancancode** [comment]
@buschtoens `this.cond` is wrapped to have the ember semantics (and return a JS boolean, not the raw value)

**Comment by chancancode** [comment]
I _think_ this is probably a bug.

https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/glimmer/lib/utils/to-bool.ts

(not sure what's up with that indentation)

**Comment by pzuraq** [comment]
This does seem like a bug, `htmlSafe` should be treated as transparent wrapper to strings conceptually, and an empty htmlSafe string should be falsy

**Comment by chancancode** [comment]
If anyone is interested in working on a fix, I believe adding a case to the function I linked above should fix it.
