### ISSUE TITLE
Tracking Issue for RFC #435 (forwarding modifiers via splattributes)

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#17493]
https://github.com/emberjs/rfcs/blob/master/text/0435-modifier-splattributes.md

**Comment by rwjblue** [comment]
Yes, IMHO this is just a bug that we should fix.

**Comment by rwjblue** [comment]
Specifically, I believe that we need to remove this:

https://github.com/glimmerjs/glimmer-vm/blob/11033eb39331e42068b9e7f35c19764ceb1f5737/packages/%40glimmer/compiler/lib/javascript-compiler.ts#L269-L271

And add some tests in glimmer-vm for this case.

**Comment by chancancode** [comment]
https://github.com/emberjs/rfcs/pull/435

**Comment by rwjblue** [comment]
This is done, and enabled by default in https://github.com/emberjs/ember.js/pull/17901
