### ISSUE TITLE
nested componets

### ISSUE THREAD

**Issue by yrah11** [emberjs/ember.js#17514]
Hi all,
I have some trouble with component communication. Lets say I have 3 nested components. Parent {{component-a}} -> which has child {{component-b}} -> which has child {{component-c}}.
How can I access component-c directly from component-a, if component-c is not rendered.
Is this even possible.
Thank you.

**Comment by btecu** [comment]
You can't access components from their parents or at least you should not.

**Comment by yrah11** [comment]
Thanks btecu
