### ISSUE TITLE
Show Angle Brackets component invocation in the docs

### ISSUE THREAD

**Issue by jenweber** [emberjs/ember.js#17524]
Angle Bracket component invocation has been available in Ember since 3.4 (???), but isn't in the API docs.

Based on Framework team feedback, we will show both regular and angle bracket invocation examples. The rule to apply here is that API docs should show our feature surface, minus deprecated things. Since hbs style isn't deprecated, we're showing both.

PRs should first target https://emberjs.com/api/ember/release/classes/Component and then the next step is to find other examples of invocation and fix them.

A PR should target `master`, include the [appropriate commit tags](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#commit-tagging), and a note in the issue that the work should be applied to more versions than master. The maintainers will help apply the changes to older versions, so multiple PRs aren't needed.

**Comment by cah-danmonroe** [comment]
I'll start working on this.

**Comment by ppcano** [comment]
@jenweber Related https://github.com/emberjs/ember.js/issues/17625

**Comment by jenweber** [comment]
All done, thanks!
