### ISSUE TITLE
ES6 class syntax in 3.4.X: `super.didReceiveAttrs` is not a function

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#17546]
Updating ember-basic-dropdown to octane I found that it fails in 3.4 (works in newer versions) because `super.didReceiveAttrs` doesn't exist.

The best reproduction I can submit right now is the PR itself: https://github.com/cibernox/ember-basic-dropdown/pull/446

Just clone, install dependencies, run `ember serve` and go to http://localhost:4200 and the error will be logged in the console.

**Comment by rwjblue** [comment]
This was fixed in https://github.com/emberjs/ember.js/pull/17169 which is included in 3.6+, but needs to be backported to lts-3-4 branch to fix 3.4.

**Comment by locks** [comment]
Closing as no longer relevant. Please move to v3.8 as its the nearest LTS!
