### ISSUE TITLE
Unreachable code in `jquery_event_deprecation`

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#17550]
In Firefox with Ember v3.7.0 I'm seeing the following warning on the console in production:
```
unreachable code after return statement (jquery_event_deprecation.js:10)
```

<img width="536" alt="bildschirmfoto 2019-02-02 um 10 53 00" src="https://user-images.githubusercontent.com/141300/52162738-bd2ac900-26d8-11e9-8319-4957f6cee722.png">

It looks like the minifier is not doing its thing here. We should try to find a way to restructure that code so that `terser` is dropping the dead code correctly.

**Comment by simonihmig** [comment]
I'll try to fix this!

**Comment by simonihmig** [comment]
Here's a PR that fixes this: #17555

The first iteration of this did not work as expected, so I played around a bit, to see what's happening, and found something weird.

Given the following code excerpt:
```
  console.log(DEBUG);
  if (JQUERY_INTEGRATION && DEBUG && HAS_NATIVE_PROXY) {
    let boundFunctions = new Map();
```

`ember.prod.js` looks like this:
```
    console.log(false
    /* DEBUG */
    );

    if (_deprecatedFeatures.JQUERY_INTEGRATION && false
    /* DEBUG */
    && _utils.HAS_NATIVE_PROXY) {
      let boundFunctions = new Map();
```

which is fine, so `DEBUG` has been replaced with `false`, and thus the `if` expression will always evaluate to `false` as well. So you would expect `terser` to completely remove that if block. But this is what `ember.min.js` will look like instead:

```
e.default=function(e){console.log(!1)
if((i.JQUERY_INTEGRATION,0)&&n.HAS_NATIVE_PROXY){let t=new Map
```

Not only did it not remove the `if` block, it removed `false` (from `DEBUG`) from the expression. Which is semantically totally wrong! Would have been ok if it was `true`. 😱

Note that it *does*  work when `DEBUG` is the first item in the if expression, as is the case in the PR!

Anyone can explain this, other than this being a bug in `terser`?

**Comment by rwjblue** [comment]
We should probably report over there I think...

**Comment by Turbo87** [comment]
you missed the `,0` part. `(i.JQUERY_INTEGRATION,0)` will evaluate the property and the return `0` because it's a comma expression.

**Comment by rwjblue** [comment]
Right. It’s still a bug IMHO.

**Comment by Turbo87** [comment]
@simonihmig yep, that is what I would expect to be the reason too.

it could remove the `&&n.HAS_NATIVE_PROXY` part as the first part is already falsy, but apparently it's not quite clever enough for that 😉
