### ISSUE TITLE
Deprecate ApplicationController#currentPath and ApplicationController#currentRouteName

### ISSUE THREAD

**Issue by locks** [emberjs/ember.js#17569]
Tracks https://github.com/emberjs/rfcs/master/text/0421-deprecate-application-controller-props.md.

## Tasks
- [ ] Implement deprecation in source code https://github.com/emberjs/ember.js/pull/17573
- [ ] Write deprecation guide https://github.com/ember-learn/deprecation-app/pull/276

**Comment by rwjblue** [comment]
We should migrate this to the corresponding emberjs/rfc-tracking issue now that they are created...

**Comment by locks** [comment]
See https://github.com/emberjs/rfc-tracking/issues/5.
