### ISSUE TITLE
Incorrect name for instance-initializer-test file

### ISSUE THREAD

**Issue by maciejmyslinski** [emberjs/ember.js#17582]
Howdy!
Thank you for creating and maintaining ember 🙇 

I'd like to report a small issue with instance-initializer-test blueprint.
![Alt text](https://monosnap.com/image/fgQnZksc1VY8UcaCU5k0bUcmuYApub.png)

Expected behavior:
A file `tests/unit/org/instance-initializer-test.js` is created

Actual behavior:
A file `tests/unit/org/instance-initializer-test-test.js` is created

**Comment by sewasewa777** [comment]
#17583 Fixed test file names

**Comment by kategengler** [comment]
`ember g instance-initializer-test foo` correctly generates `tests/until/instance-initializers/foo-test.js`
