### ISSUE TITLE
I can't use mut with nested object

### ISSUE THREAD

**Issue by akursat** [emberjs/ember.js#17601]
Hi,

When we using mut helper with action closure like 
`(action (mut model.foo) value="target.id" )`
 it works but 
`(action (mut model.foo.bazz) value="target.id" ) `
it is not working. It says "Could not find model.foo.bazz".
If making this improvement is wrong can you describe why it's?

Thank you,

**Comment by jelhan** [comment]
Could you please provide an Ember Twiddle reproducing that issue? I've tried but wasn't able.

Using this button `<button onclick={{action (mut foo.bar.baz)}}>nested mut</button>` in an Ember Twiddle running `ember@3.4.3` doesn't throw any error on render time. If action is executed and `foo.bar` is undefined it throws `Assertion Failed: Cannot call set with 'baz' on an undefined object.`. If `foo.bar` is an object everything works as expected.

**Comment by akursat** [comment]
I can't reproduce in twiddle also sorry about that. My mistake. I'm closing issue.
