### ISSUE TITLE
[3.8.0] Regression compiling to ES5

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#17643]
Not sure if this is the right title for this issue. [Here is a reproduction](https://github.com/boris-petrov/ember-classes-bug).

Since updating to Ember 3.8.0, `ember-ajax` stops working in an ES5 build. `isUnauthorizedError(new UnauthorizedError())` should return `true` (and does on ES6 builds on Ember 3.8 and any build on Ember 3.7-) but it returns `false` on ES5 on 3.8. [isUnauthorizedError](https://github.com/ember-cli/ember-ajax/blob/v4.0.2/addon/errors.ts#L90) just does an `instanceof` check so the issue is somewhere deeper.

It's a regression from 3.7.3.

**Comment by Turbo87** [comment]
this is most likely caused by https://github.com/emberjs/ember.js/pull/17216, since `ember-ajax` errors seem to extend `EmberError` 😞

**Comment by boris-petrov** [comment]
This has been fixed in `ember-ajax` 5, thanks to @Turbo87!
