### ISSUE TITLE
`EMBER_METAL_TRACKED_PROPERTIES` fails with Ember Data

### ISSUE THREAD

**Issue by ppcano** [emberjs/ember.js#17651]
@pzuraq 

Testing the `octane` blueprints with Ember Data; `update(propertyTag, tag)` triggers an exception.

<img width="774" alt="screen shot 2019-02-22 at 4 50 18 am" src="https://user-images.githubusercontent.com/825430/53218700-7425bf00-365d-11e9-968d-aca7ffd2250c.png">

Using a simple model like:

```
export default Model.extend({
  name: attr('string')
});
```

**Comment by pzuraq** [comment]
For sure, thanks for the report! So, all you’re doing is setting the attr? Can you possibly copy to code that causes the failure?

**Comment by ppcano** [comment]
@pzuraq The project https://github.com/ppcano/oct5

If you change the `EMBER_METAL_TRACKED_PROPERTIES`  at config/environment.js will trigger the error.

It looks the problem is triggered by ED when normalizing the server response.

**Comment by rwjblue** [comment]
Thank you for reporting @ppcano!
