### ISSUE TITLE
Unable to build ember from master 

### ISSUE THREAD

**Issue by dbrusilovsky** [emberjs/ember.js#17678]
I'm trying to build ember using `yarn install` and `yarn build`, and am running into the following error:
```
Build Error (broccoli-persistent-filter:Babel) in @ember/-internals/browser-environment.js
​
Cannot read property 'getHash' of null
```
A paste of my process:
https://dpaste.de/Ne8h

Node version: v10.15.0
Yarn version: v1.13.0
Operating system: macos 10.14.3

The issue was replicated on another machine by @efx on discord.

**Comment by dbrusilovsky** [comment]
Error log: https://dpaste.de/j3ZU

**Comment by dbrusilovsky** [comment]
Offending commit appears to be e90aee2d0

**Comment by mixonic** [comment]
@rwjblue @stefanpenner I ran into this as well tonight, seems related to the bump of hash-for-dep from 1.2.3 to 1.4.7. I opened a hacky quick fix for Ember in https://github.com/emberjs/ember.js/pull/17679.

**Comment by rwjblue** [comment]
Thanks for reporting! Will dig in to see what’s going on...

**Comment by stefanpenner** [comment]
I have an idea what the issues And with the reproduction it should be easy to tackle.

**Comment by ppcano** [comment]
I don't know if this is related but when using my local `ember-source` repo with an Octane app, an exception is thrown:

```
Directory not found: /Users/ppcano/dev/ember/ember.js/dist/legacy
```

Steps:

```
cd ember.js
yarn link
yarn start
```

```
// other terminal
ember new oct-app -b ember-octane-app-blueprint --yarn
cd oct-app
yarn link ember-source
ember s -p 4201
```

**Comment by pzuraq** [comment]
@ppcano You need to run `yarn start --environment="production"`, your app is targeting legacy browsers (IE11, etc) and looking for the legacy build, which is only built in production mode in the `ember-source` repo

**Comment by stefanpenner** [comment]
@ppcano that doesn't seem related

**Comment by stefanpenner** [comment]
@mixonic's revert addressed the issue and https://github.com/emberjs/ember.js/pull/17694 unreverts \w fix
