### ISSUE TITLE
Class names aren't merged correctly when `...attributes` is specified first

### ISSUE THREAD

**Issue by GavinJoyce** [emberjs/ember.js#17692]
There seems to be a difference in how attributes are merged depending on the position of `...attributes` within an element. The [RFC](https://emberjs.github.io/rfcs/0311-angle-bracket-invocation.html#html-attributes) doesn't seem to specify what the behaviour should be, I'm assuming that position shouldn't matter as otherwise it would likely be a source of confusion.

With the following `Foo` component template:

```hbs
<div class="inner" ...attributes />
<div ...attributes class="inner" />
```

And the following invocation:

```hbs
<Foo class="outer />
```

The result is:

```html
<div class="inner outer" />
<div class="outer" />
```

**update:** After trying to write a failing test in glimmer-vm, it appears that the classes should be merged and the order will be different. The output should be:

```html
<div class="inner outer" />
<div class="outer inner" />
```

**Comment by GavinJoyce** [comment]
Failing test: https://github.com/emberjs/ember.js/pull/17693

**Comment by GavinJoyce** [comment]
I tried to write a similar failing test in `glimmer-vm`, but it appears to pass:

https://github.com/GavinJoyce/glimmer-vm/pull/1

**Comment by rwjblue** [comment]
The order was actually intended to matter, though we do have a bug in class merging still (https://github.com/emberjs/ember.js/pull/17533 tracks that) which is what I think you are really reporting here.

The idea was that you could use the location of `...attributes` to control if a given attribute could or could not be "clobbered" by your caller.

For example, given these two possibilities:

```hbs
<div data-foo="inner" ...attributes></div>
<div ...attributes data-foo="inner"></div>
```

With this invocation:

```hbs
<Foo data-foo="outer" />
```

We expect the location of `...attributes` to affect the final result:

```hbs
<div data-foo="outer"></div>
<div data-foo="inner"></div>
```

**Comment by rwjblue** [comment]
Also, RE: this working correctly in glimmer-vm, thats because the system doing the merging was overhauled in glimmer-vm but we haven't gotten Ember updated to the newer version (there were breaking changes, and its a bit of work to figure out what exactly is needed to do an upgrade).

**Comment by GavinJoyce** [comment]
👍 thanks for the explanation.  It looks like the tests in https://github.com/emberjs/ember.js/pull/17533 are similar so I'll close https://github.com/emberjs/ember.js/pull/17693. 

I'll leave this issue open so that it's discoverable for anyone else hitting the bug

**Comment by MelSumner** [comment]
If it helps, this would also matter for `aria-labelledby` because you can concatenate a label from several text nodes- see https://www.w3.org/WAI/GL/wiki/Using_aria-labelledby_to_concatenate_a_label_from_several_text_nodes

**Comment by rwjblue** [comment]
@MelSumner - Good catch! I think we'll need a small RFC to tweak that behavior since the [merged RFC](https://emberjs.github.io/rfcs/0311-angle-bracket-invocation.html#html-attributes) explicitly states that `class` is the only execption:

> This means that attributes provided by the caller will override (replace) those added by the component (except for class, which is merged).

**Comment by MelSumner** [comment]
for attributes coming from ARIA, there are six whose value is an [ID reference list](https://www.w3.org/WAI/PF/aria/states_and_properties#valuetype_idref_list) (meaning, they can have one or more values): 

- [aria-controls](https://www.w3.org/WAI/PF/aria/states_and_properties#aria-controls) - It seems like the order could possibly matter in some instances.
- [aria-describedby](https://www.w3.org/WAI/PF/aria/states_and_properties#aria-describedby): order definitely matters
- [aria-flowto](https://www.w3.org/WAI/PF/aria/states_and_properties#aria-flowto) - the order could matter, depending on intent of content.
- [aria-labelledby](https://www.w3.org/WAI/PF/aria/states_and_properties#aria-labelledby) - order definitely matters
- [aria-owns](https://www.w3.org/WAI/PF/aria/states_and_properties#aria-owns) Order could matter, depending on design intent (if someone is using this, really we should make them stop and think twice tbh, it's smelly),

**Comment by rwjblue** [comment]
👍 thank you for researching that! We should totally do an RFC to get those added to the "plz merge, don't clobber" list.  During that RFC cycle we should try to see if there are other attributes like this that should be considered...

**Comment by chancancode** [comment]
This (the bug in the original thread) should now be fixed on canary and beta!
