### ISSUE TITLE
Should @ember/instrumentation be public API?

### ISSUE THREAD

**Issue by xg-wang** [emberjs/ember.js#17703]
[@ember/instrumentation](https://github.com/emberjs/ember.js/blob/v3.8.0/packages/%40ember/instrumentation/index.ts#L36) has been marked private since @rwjblue 's [PR](https://github.com/emberjs/ember.js/pull/11362) in 2015, should the module be considered as public API?

**Comment by runspired** [comment]
I think this is a question for RFC discussion

**Comment by xg-wang** [comment]
Would love to write one. Should this issue moved to rfc repo?

**Comment by xg-wang** [comment]
See comment https://github.com/emberjs/ember.js/pull/17848#issuecomment-480831971
