### ISSUE TITLE
`.volatile` deprecation in 3.9 needs an alternative for "classic" classes

### ISSUE THREAD

**Issue by kategengler** [emberjs/ember.js#17709]
In 3.9 `.volatile` is deprecated. The [deprecation guide](https://www.emberjs.com/deprecations/v3.x/#toc_computed-property-volatile) suggests moving to native classes, but that isn't yet possible in all cases, and so we need an alternative to `.volatile` to allow the deprecation to be resolved where native classes cannot yet be used. 

h/t @pzuraq

**Comment by rwjblue** [comment]
Over in the RFC I mentioned this as well (see https://github.com/emberjs/rfcs/pull/370#issuecomment-417782786):

---

> Because the only path forward involves using native classes, does the deprecation of .volatile() need to be tied to the deprecation of Ember.Object.extend({}) style syntax? 

No 😸, and native classes aren't the _only_ way forward (though the alternatives are less ergonomic than ES classes).

For example, you can migrate from:

```js
export default Component.extend({
  init() {
    this._super(...arguments);
    this._foo = 0;
  },

  foo: computed(function() {
    return this._foo++;
  }).volatile()
});
```

To:

```js
const FooBar = Component.extend({
  init() {
    this._super(...arguments);
    this._foo = 0;
  }
});

Object.defineProperty(FooBar.prototype, 'foo', {
  get() {
    return ++this._foo;
  }
});

export default FooBar;
```

**Comment by kategengler** [comment]
Then it may be that just the deprecation guide needs to change.

**Comment by kanongil** [comment]
I have 2 use cases that aren't covered:

Class extend inheritance:

```js
const A = Component.extend({
  foo: computed(function() {
    return { foo: true };
  }).volatile()
});

const B = Component.extend({
  foo: computed(function() {
    let obj = this._super();
    obj.bar = 123;
    return obj;
  }).volatile()
});
```

The second case is for an internal addon, which exposes a `ComputedProperty` instance that needs to call the _getter on all `get()` calls. This case fundamentally clashes with the deprecation.

**Comment by kanongil** [comment]
3rd case that is not covered: Relying on dependent properties.

Example:
```js
  currentLimitMs: computed('program.{start,duration}', function () {
    cancel(this._invalidateNow);

    let start = this.get('program.start');
    let duration = this.get('program.duration');

    let now = Date.now();
    let limitMs = now - start;
    if (limitMs < duration) {
      this._invalidateNow = later(() => this.notifyPropertyChange('currentLimitMs'), 1000);
    } else {
      limitMs = duration;
    }

    return limitMs;
  }).volatile(),
```

Any chance that the deprecation can be reverted?
