### ISSUE TITLE
Ember.js main ReadMe broken image

### ISSUE THREAD

**Issue by cdersky** [emberjs/ember.js#17724]
Image below the follow text is broken `Cross-browser testing provided by:`

<img width="1070" alt="Screen Shot 2019-03-12 at 4 45 02 PM" src="https://user-images.githubusercontent.com/11150858/54243664-9dac6a80-44e6-11e9-8aed-8b36da3cfcd9.png">

**Comment by rwjblue** [comment]
Thanks for reporting! Wanna send a PR to fix?

**Comment by yashdilip** [comment]
pull request #17746

**Comment by locks** [comment]
Closing as image was removed altogether, as far as I can tell.
