### ISSUE TITLE
date inputs with value are broken with edge

### ISSUE THREAD

**Issue by luxferresum** [emberjs/ember.js#17738]
Doing either `<input type="date" value="2019-02-15">` or `{{input type="date" value="2019-02-15"}}` does render this in Edge:

![image](https://user-images.githubusercontent.com/1208273/54371205-4d194680-4679-11e9-8dc2-c4624c2c059e.png)

Opening the datepicker works but selecting a value does not work.

It works in firefox and chrome. I could reproduce in ember 3.5 and 3.8.

creating a input without a `value` works. Later doing `domNode.value = "2019-02-15"` or `domNode.setAttribute('value', '2019-02-15')` works.

I've created a ember addon `ember-hacky-set-value` that adds a `{{set-value "..."}}` modifier which which works for now as a hack.

**Comment by btecu** [comment]
Seems to work fine using 3.8:
![image](https://user-images.githubusercontent.com/7517745/54391334-e9901880-467a-11e9-95cf-4e3935ecbc37.png)

Can you maybe post a reproduction?

**Comment by luxferresum** [comment]
@btecu [reproduction](https://github.com/luxferresum/ember-edge-input-date-bug)

It seems the bug *only* occurs when a `padding` is set on `input`. Thats a *very* strange combination.

**Comment by iamnathadian** [comment]
I am experiencing this issue using Ember 3.12. Any workaround?

**Comment by luxferresum** [comment]
You've tried my addon? Or remove the padding.

**Comment by ikirkpat** [comment]
@btecu set the input height to something like 400px. You should see the 2nd value below the first

**Comment by locks** [comment]
Is this still an issue? And is it a bug with Ember itself?

**Comment by luxferresum** [comment]
It only ever was a issue on legacy edge. Is this still in the support matrix? If not this basically solved itself.

**Comment by locks** [comment]
Good point! According to https://emberjs.com/browser-support I don't think we do, so I'll close this one. Thanks for pinging with an update.
