### ISSUE TITLE
eslint errors in fresh app generated with Octane blueprint

### ISSUE THREAD

**Issue by pgengler** [emberjs/ember.js#17792]
I generated a new app using `ember new octane-app -b @ember/octane-app-blueprint --yarn --no-welcome`, and the freshly-generated app has three eslint errors out-of-the-box:

```
$ yarn lint:js
yarn run v1.13.0
$ eslint .

/Users/pgengler/octane-app/.eslintrc.js
  45:40  error  "eslint-plugin-node" is not published  node/no-unpublished-require

/Users/pgengler/octane-app/config/environment.js
  50:37  error  Empty block statement  no-empty

/Users/pgengler/octane-app/ember-cli-build.js
  3:26  error  "ember-cli" is not published  node/no-unpublished-require

✖ 3 problems (3 errors, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I also tried again without the `--yarn --no-welcome` options (and using `npm run lint:js`) and got the same result.

**Comment by pzuraq** [comment]
Thanks for reporting this @pgengler! Are you still having these issues?

**Comment by tcaer** [comment]
Hi,

I am getting these issues still.

Thanks

**Comment by pgengler** [comment]
Yes, it's still an issue. Looks like it's being tracked on the ember-octane-blueprint repo: https://github.com/ember-cli/ember-octane-blueprint/issues/65

**Comment by rwjblue** [comment]
Going to close this (so we can track in https://github.com/ember-cli/ember-octane-blueprint/issues/65).
