### ISSUE TITLE
Port 4200 is already in use

### ISSUE THREAD

**Issue by svparijs** [emberjs/ember.js#17795]
Since a few days now my Mac cannot start `ember serve` properly.

```
 ❯ ember -v                                                                                                                     [14:08:43]
ember-cli: 3.4.4
node: 8.15.1
os: darwin x64
```
When I start a completely new ember project this also happens:
```
 ❯ ember server                                                                                                                [14:28:56]
Port 4200 is already in use.
```
Any idea's how to fix this?

**Comment by HEYGUL** [comment]
Can you run this terminal command:
`lsof -i :4200`

It will list any process which have already open 4200 port on your Mac.

**Comment by svparijs** [comment]
Yeah I've done a bit of googling to and did this aswel. 
```
 ❯ lsof -i :4200                                                                                                               [15:00:52]

```

After running this:
```
ember serve --port 0
```

The new app works, again with the regular ember serve command. The actual project works with --port 0 but no longer works when I use `ember s`.

**Comment by pzuraq** [comment]
Can you try running:

```js
killall node
```
?

You can also try fully restarting your computer, usually if something has locked the port that'll force it off

**Comment by locks** [comment]
I am closing this issue as it does not seem a bug in Ember itself.
Please refer to `#help` in our Discord server if you need further assistance!

**Comment by svparijs** [comment]
The issue is related to 1 single project. Not the ember project.

**Comment by rodrigoyoshida** [comment]
Just to mention that after a fresh install of Ubuntu, Node and Ember I am facing this issue, so it can be related to Ember itself.

**Comment by chancancode** [comment]
@rodrigoyoshida see https://github.com/ember-cli/ember-cli/issues/8794
