### ISSUE TITLE
Sort computed decorator in Octane gives "this.notifyPropertyChange is not a function" error

### ISSUE THREAD

**Issue by CodingItWrong** [emberjs/ember.js#17839]
I'm attempting to sort a list of Ember Data records, and add a new record to the list. In stable this works fine, but in Octane I get the following error (error shown is from Firefox):

```
TypeError: this.notifyPropertyChange is not a function
```

Minimal reproduction: https://github.com/CodingItWrong/octane-sort-test
Comparable stable app showing the error does not occur: https://github.com/CodingItWrong/ember-sort-test

Here's the class where the sorting happens:

```
import Component from '@glimmer/component';
import { action } from '@ember/object';
import { sort } from '@ember/object/computed';
import { inject as service } from '@ember/service';

export default class WidgetListComponent extends Component {
  @service store;

  sortProperties = Object.freeze(['id:desc']);

  @sort('args.widgets', 'sortProperties')
  sortedWidgets;

  @action
  addWidget() {
    const widget = this.store.createRecord('widget', { name: 'New Widget' });
    widget.save();
  }
}
```

**Comment by rwjblue** [comment]
Can you share the full stack trace?

**Comment by CodingItWrong** [comment]
@rwjblue Sure thing:

```
TypeError: this.notifyPropertyChange is not a functionreduce_computed_macros.js:983
    Ember 22
    invoke backburner.js:341
    flush backburner.js:233
    flush backburner.js:437
    _end backburner.js:1013
    end backburner.js:699
    _run backburner.js:1068
    _join backburner.js:1042
    join backburner.js:759
    createRecord Ember
    addWidget widget-list.js:29
    addWidget self-hosted:1003
```

**Comment by rwjblue** [comment]
The issue is here:
 	https://github.com/emberjs/ember.js/blob/5e4b58feee28201aa314951a38bdf60535f79395/packages/@ember/object/lib/computed/reduce_computed_macros.js#L971

The reduced macros can _absolutely_ not assume that `this.notifyPropertyChange` is "a thing". 

I've submitted https://github.com/emberjs/ember.js/pull/17841 to fix.

**Comment by CodingItWrong** [comment]
Thanks, running locally off of that PR's branch confirms that it fixes the issue for me
