### ISSUE TITLE
Releases Dropdown is not working in ember website

### ISSUE THREAD

**Issue by anpenava** [emberjs/ember.js#17854]
I saw website project is archived so I submited issue here
<img width="1276" alt="Screen Shot 2019-04-03 at 10 29 20" src="https://user-images.githubusercontent.com/18396201/55468720-e34ae780-55fb-11e9-9b48-524d2479a801.png">

**Comment by locks** [comment]
Thanks for the report, migrated to https://github.com/ember-learn/ember-api-docs/issues/605!
