### ISSUE TITLE
RouterService.urlFor() broken when sub-route has same param name as parent route

### ISSUE THREAD

**Issue by Herriau** [emberjs/ember.js#17861]
Given the following route definition:

```javascript
Router.map(function() {
  this.route('foo', {path: '/foo/:id'}, function() {
    this.route('bar', { path: '/bar/:id' });
  });
  this.route('baz', {path: '/baz/:bazId'}, function() {
    this.route('qux', { path: '/qux/:quxId' });
  });
});
```

`RouterService.urlFor()` will return an erroneous URL for the route `foo.bar`, seemingly because their respective parametrized `path` both contain a param with the same name. As a control test, `urlFor()` behaves properly for the route `baz.qux`. See below:

```javascript
Ember.Controller.extend({
  router: inject(),
  fooBarUrl: computed(function() {
    return this.router.urlFor('foo.bar', 123, 456);
    // evaluates to "/foo/456/bar/456"
  }),
  bazQuxUrl: computed(function() {
    return this.router.urlFor('baz.qux', 123, 456);
    // evaluates to "/baz/123/qux/456"
  })
})
```

Reproduction:
- [Twiddle](https://ember-twiddle.com/9476bd9be73ed9de2fd4b532af76b43f?openFiles=controllers.application.js%2C)
- [Gist](https://gist.github.com/Herriau/9476bd9be73ed9de2fd4b532af76b43f)

**Comment by locks** [comment]
This is working as intended. The way I think about dynamic segments is that there is a single `params` object, so if you have this situation both of the routes are setting the same param and the second will override the value.
Sorry for the confusion!

**Comment by Herriau** [comment]
@locks Interesting. I did not realize this was forbidden as most aspects of the framework work just fine under this condition. Perhaps dups in param names should result in a runtime error (at least on dev builds) so that others don't fall in the same trap.
