### ISSUE TITLE
Is 3.8 an LTS version?

### ISSUE THREAD

**Issue by ryanto** [emberjs/ember.js#17866]
Hello! I'm upgrading some addons today and one of my goals is to make sure they support the LTS versions of Ember. 

I'm unsure if 3.8 is a current LTS release, is planned to be one in the future, or is just a regular release? I think it is an LTS, but wasn't sure so figured I'd ask! Thanks in advance.

Ember releases page: https://emberjs.com/releases/
3.8 blog post: https://blog.emberjs.com/2019/02/27/ember-3-8-released.html

**Comment by rwjblue** [comment]
3.8 becomes an LTS when 3.9 is "officially" released (this is effectively the same as the way Node operates). The 3.9 blog post should be out soon though...

**Comment by ryanto** [comment]
Awesome & thanks! I'm testing against 3.8 for all my addons now.
