### ISSUE TITLE
Discuss: Trusted Types

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#17892]
To prevent Cross-Site Scripting, the chrome folks have added experimental support for Trusted Types:
https://developers.google.com/web/updates/2019/02/trusted-types

We should evaluate, think about if/how/when ember could benefit and provide feedback.

**Comment by rwjblue** [comment]
This is probably more of an RFC issue I think, as "adopting" would likely require an RFC (along with some API changes to things like `SafeString` / `htmlSafe` / etc).

**Comment by koto** [comment]
Hey, a Trusted Types representative here :) We're happy to help if you need any clarifications, have questions around the feature or suggestions for the API. We think it's a worthy addition to the platform, especially if popular frameworks adopt the approach.

**Comment by NullVoxPopuli** [comment]
@stefanpenner has an investigation happened? I am interested in trustedness

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue.

This repo has a lot of open issues, some that that have been open for several years. 

The reality is that this is an open-source project, and the time of core team members is very limited. We all want them to focus on moving the framework forward (high-leverage things).

I'll be closing this for now, to keep the list of open issues manageable. I hope you understand!

If this should be tackled, its likely via an RFC. Could be noted that no other browser has implemented trusted types yet though.

https://caniuse.com/trusted-types
