### ISSUE TITLE
<select> Infinite rendering loop (3.9, jQuery disabled)

### ISSUE THREAD

**Issue by paulcollett** [emberjs/ember.js#17893]
Trying out the 3.9 build with jQuery disabled. So far, all seems ok expect for one snag.

Any select `<option>` rendered in a loop will trigger an infinite rendering loop. It's possible it's simply just the following, at least in our setup.

```hbs
<select>
  {{#each options as |option|}}
    <option></option>
  {{/each}}
</select>
```

`options` in this case can be any kind of array, empty or not. `options` seems to mutate on each render causing another re-render. It's possible to attach an observer to `options` which will run indefinitely.

**Comment by pzuraq** [comment]
One thing to note here is that you're introducing a local variable named `option`, and with angle bracket invocation being a thing now, `<option></option>` is actually _using_ that variable to render. It should throw an error though, or do nothing if `option` is null or undefined, so infinite rerendering definitely seems like a bug.

**Comment by paulcollett** [comment]
Can confirm that this new local variable thing is the culprit for us. Any other variable name works as expected...

```hbs
<select>
  {{#each options as |myOption|}}
    <option></option>
  {{/each}}
</select>
```

**Comment by locks** [comment]
This now results in a different error, which I've filed under https://github.com/emberjs/ember.js/issues/20058..
