### ISSUE TITLE
3.10 {{input type='checkbox'}} triggering @value assertion

### ISSUE THREAD

**Issue by mastastealth** [emberjs/ember.js#17907]
I have [opened a repo](https://github.com/mastastealth/octane-checkbox) with an example of the issue. Basically I have a custom component that wraps the built-in {{input}}. When calling my custom checkbox (so component sets `type: 'checkbox' [in the JS](https://github.com/mastastealth/octane-checkbox/blob/master/app/components/my-box.js), and [in the template](https://github.com/mastastealth/octane-checkbox/blob/master/app/templates/components/my-box.hbs) I'm passing in all the standard params should I choose to customize them), invoking it via the curly style will result in [this error](https://github.com/emberjs/ember.js/blob/v3.10.0-beta.2/packages/%40ember/-internals/glimmer/lib/components/checkbox.ts#L151).

I'm not even setting a value in the example, and even if I were, shouldn't it map to the attribute? The [work around](https://github.com/mastastealth/octane-checkbox/blob/working/app/templates/components/my-box.hbs), which I've placed in the `working` branch, seems to be forcing an angle bracket invocation that looks more like:

```
<Input @type={{type}}
    @checked={{checked}}
    ...
    value={{value}}
}}
```

I would expect to still be able to use the curly invocation as I had it before. <= 3.9 does not exhibit the issue.

**Comment by rwjblue** [comment]
We have had an assertion to prevent passing `value` to checkbox:

https://github.com/emberjs/ember.js/blob/8df20e944ca83e5244df316587d3261c434a25ff/packages/%40ember/-internals/glimmer/lib/syntax/input.ts#L182-L190 

However, when passing `type` as a path or named argument as you have in that template, the assertion was avoided because we short circuit:

https://github.com/emberjs/ember.js/blob/8df20e944ca83e5244df316587d3261c434a25ff/packages/%40ember/-internals/glimmer/lib/syntax/input.ts#L175-L181

**Comment by rwjblue** [comment]
I'm sorry this bit you, but I honestly feel that the change here is fixing a bug in the long standing "helpful assertion".

**Comment by rwjblue** [comment]
@chancancode - Mind confirming my thoughts here? If you agree, I think we can close this...

**Comment by chancancode** [comment]
As long as <Input @type={{dynamic}} @value={{dynamic}} @checked={{dynamic}} /> “works” (when the right things are set to the right values bases on the type) then I think it’s all good. Not sure if we have a test for it.

**Comment by rwjblue** [comment]
@chancancode - No that specifically doesn't work, because (if you reference the links in my previous comment) the only thing you could do is set `value` to undefined which will not equal `UNSET` and will therefore assert.

**Comment by chancancode** [comment]
Right, should we fix that? Did it work before?

**Comment by rwjblue** [comment]
@chancancode - Kinda? If you follow along with https://github.com/emberjs/ember.js/issues/17907#issuecomment-482375090, it only worked because the assertion was not included in the dynamic type case. Which, IMHO, was a bug...

**Comment by rwjblue** [comment]
I don't really care if we make the provided repro case work, or call this a bugfix. Either thing is "easy enough", but I want us to agree on what we expect 😸.

**Comment by rwjblue** [comment]
IMHO, we should make what @chancancode said in https://github.com/emberjs/ember.js/issues/17907#issuecomment-486858208 work, specifically:

```hbs
<Input @type={{@providedType}} @value={{@providedValue}} @checked={{@providedIsChecked}} />
```

Should work. Specifically:

* when `@providedType` is `'checkbox'` and `@providedValue` is `undefined` / `null`, it should not assert
* when `@providedType` is `'input'` and `@providedIsChecked` is `undefined` / `null`, it should not assert
* when `@providedType` is `'checkbox'` and `@providedValue` is **not** `undefined` / `null`, it should assert
* when `@providedType` is `'input'` and `@providedIsChecked` is **not** `undefined` / `null`, it should assert

**Comment by locks** [comment]
Closing as no longer relevant. The `Input` component has been significantly reworked since.
