### ISSUE TITLE
Tagless components / DOM method error message could be more informative

### ISSUE THREAD

**Issue by lupestro** [emberjs/ember.js#17929]
The message:
```
You can not define a function that handles DOM events in the <...> tagless component since it doesn't have any DOM element.
```
can easily leave the user wondering what to look for specifically in their code. With different ways of invoking things within handlebars and within the code and new options available daily :), it is hard to know precisely to what this does or doesn't apply.

If the message were to identify to the user what it detected in the component that violated the rule, it would save the user from having to remove things one-by-one and edit/build/run until it starts working -- or it finds the next one and gives the same message, at which the user has to remove everything and put things back in one at a time until it falls over. This can be tedious.

@rwjblue pointed out the following points of interest in the source for whoever takes it up:

https://github.com/emberjs/ember.js/blob/2854463ec3aa191da4e035954dafea1be347cf2f/packages/%40ember/-internals/glimmer/lib/component.ts#L731-L750

https://github.com/emberjs/ember.js/blob/d88da1b61d8dfc15138958682252c3bd1f2a28fb/packages/%40ember/-internals/glimmer/tests/integration/components/fragment-components-test.js#L55

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/17930
