### ISSUE TITLE
Use native Error instead of custom Error subclass is breaking change

### ISSUE THREAD

**Issue by mydea** [emberjs/ember.js#17922]
After upgrading to 3.9, a lot of our tests started to fail. After digging around, it seems to be because of this commit: https://github.com/emberjs/ember.js/commit/407ea959b5373a0a7f20c45a93fd13ec5048c131#diff-814782b54518476cf7051d808b7c52cd

Basically, changing @ember/error to basically be Error. This changed a lot of subtle things about custom errors, as well as Ember Data.
In Ember Data, I could find this new comment https://github.com/emberjs/data/blob/1495b780952a1b1cb53060114490ba9554c1341d/packages/adapter/addon/error.js#L81: 

```js
// in ember 3.8+ Error is a Native Error and we don't
// gain these automatically from the EmberError.call
```

But this is only available in newer versions of Ember Data, which has some other issues which prevent us from updating.. so we are stuck on either buggy behavior, which is not ideal.

I could also not find any note, anywhere, about this change.

This twiddle shows the difference. I somewhat lifted the code to extend the EmberError. Once I extend from EmberError, once from native Error. When I output these, you can immediately see the different output: https://ember-twiddle.com/66f7c0a1ada2a07c2ade10b84c425037?openFiles=controllers.application.js%2C

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.
