### ISSUE TITLE
Document {{in-element}} helper

### ISSUE THREAD

**Issue by jayjayjpg** [emberjs/ember.js#17947]
With the implementation of [RFC#287](https://github.com/cibernox/rfcs/blob/20d2c89a11d20b7672291569efa2aa6e1697e2fe/text/0000-promote-in-element-to-public-api.md) a new built-in helper will be added to Ember's public API. To document this helper, please add a comprehensive description of the helper.

## Tasks

- [ ] add a description of the `{{in-element}}` helper to the source describing what it does functionally and which parameters it accepts
- [ ] annotate the helper as public API

**Comment by the-bionic** [comment]
Hello @jessica-jordan, is this still pending, can I look into it?
