### ISSUE TITLE
Error object is always undefined.

### ISSUE THREAD

**Issue by shamma** [emberjs/ember.js#17950]
https://github.com/emberjs/ember.js/blob/abf753a3d494830dc9e95b1337b3654b671b11be/packages/%40ember/error/index.ts#L36
Hey
We are using this new EmberError and expecting the code from it and it is coming undefined all the time. 
We had to explicitly do this,
           const error = new EmberError(`${url} failed with status: ${xhr.status}, message: ${xhr.statusText}`);
            error.code = xhr.status;
and reject(error);

**Comment by rwjblue** [comment]
I believe this is a duplicate of https://github.com/emberjs/ember.js/issues/17922, can you confirm? If so, lets close this one...

**Comment by locks** [comment]
Closing as duplicate due to inactivity. Thanks for reporting this!
