### ISSUE TITLE
(fn (mut ) ) throws on template eval

### ISSUE THREAD

**Issue by mike-north** [emberjs/ember.js#17966]
The following examples are explicitly called out in the [`{{fn }}` RFC](https://github.com/emberjs/rfcs/blob/master/text/0470-fn-helper.md) as equivalent `{{fn}}` code for things that are supported today w/ `{{action}}`. It's certainly implied that this syntax will be supported

```hbs
<button onclick={{fn (mut showModal) true}}>Click</button>
<button {{on "click" (fn (mut showModal) true)}}>Click</button>
```
The currently implementation doesn't seem to be happy with using these two helpers together.

##### component.js
```js
import Component from '@glimmer/component';
import { action } from '@ember/object';
import { tracked } from '@glimmer/tracking';

export default class XFooComponent extends Component {
  @tracked
  isShown = false;

  @action toggleShown() {
    this.isShown = !this.isShown;
  }
}
```

##### component.hbs
```hbs
<button {{on "click" this.toggleShown}}>
  {{if this.isShown "Hide" "Show" }}
</button>


{{#if this.isShown}}
  <p>
    My beautiful content
    <img src="http://placecorgi.com/300/314" alt="">
  </p>
{{/if}}
```

##### component.js
```js
import Component from '@glimmer/component';
import { tracked } from '@glimmer/tracking';

export default class XFooComponent extends Component {
  @tracked
  isShown = false;
}
```

##### component.hbs
```hbs
<button {{on "click" (fn (mut this.isShown) (not this.isShown))}}>
  {{if this.isShown "Hide" "Show" }}
</button>

{{#if this.isShown}}
  <p>
    My beautiful content
    <img src="http://placecorgi.com/300/314" alt="">
  </p>
{{/if}}
```
### The Error Message

```
Uncaught (in promise) Error: Assertion Failed: You must pass a function as the `fn` helpers first argument, you passed false
    at assert (index.js:163)
    at fnHelper (glimmer.js:7568)
    at InternalHelperReference.compute (glimmer.js:739)
    at InternalHelperReference.value (glimmer.js:343)
    at valueOf (runtime.js:4605)
    at Array.map (<anonymous>)
    at CapturedPositionalArguments.value (runtime.js:4582)
    at CapturedArguments.value (runtime.js:4463)
    at CustomModifierManager.create (glimmer.js:8584)
    at Object.evaluate (runtime.js:1025)
```

### Repro Case
**Code:** https://codesandbox.io/s/github/mike-north/octane-app-repro-cases/tree/fn-mut/?fontsize=14&module=%2Fapp%2Ftemplates%2Fcomponents%2Fx-failing.hbs
**Fullscreen App:** https://1o5471523j.sse.codesandbox.io/

**Comment by rwjblue** [comment]
Awesome bug report, thank you very much @mike-north! This is a bug in the implementation, I've labeled appropriately and will be working to get it fixed today/tomorrow.

**Comment by rwjblue** [comment]
Just wanted to clarify one thing: when you say `And this throws on compile` you are referring to it throwing at _runtime_ (not compile / aka build time) when the template is invoked.

**Comment by mike-north** [comment]
I mean that it's thrown when the template is initially rendered, but *not* when the event is fired. You're right, this is not compile-time

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/17968 explains the underlying issue and fixes
