### ISSUE TITLE
Ember uses deprecated features

### ISSUE THREAD

**Issue by kanongil** [emberjs/ember.js#17964]
The [events.inherited-function-listeners](https://deprecations.emberjs.com/v3.x/#toc_events-inherited-function-listeners) deprecation triggers from within ember itself.

The triggered method: https://github.com/emberjs/ember.js/blob/a7d861b950d31fe8e7f103b0cb678b2c2bc34b88/packages/%40ember/-internals/runtime/lib/mixins/-proxy.js#L21-L27

**Comment by pzuraq** [comment]
Listeners are inherited lazily, so there's no way for us to know ahead of time that they will cause a deprecation. When we first notify a property that causes the listener to fire, we collapse the inheritance tree and encounter the issue, throwing the deprecation message.

You should look through your code to see where you are doing `addListener` or `addObserver` with a function to see where this might be coming from. Alternatively, you can place a breakpoint at the deprecation itself, and log the function there, it should link you back to the actual function, which should help you find where it is being added.

**Comment by kanongil** [comment]
@pzuraq It is _not_ my code:

https://github.com/emberjs/ember.js/blob/a7d861b950d31fe8e7f103b0cb678b2c2bc34b88/packages/%40ember/-internals/runtime/lib/mixins/-proxy.js#L75

**Comment by pzuraq** [comment]
If that's the deprecation message you are seeing, I believe this is a _different_ listener that is being triggered by that observer. Those observers are only ever added to instances, the `willWatchProperty` function is never called on a prototype, and could not trigger this message.

If you still need to debug this, please put a breakpoint at the location of the deprecation and log the function, so we can be sure.

**Comment by kanongil** [comment]
It's an ember issue, replicated with this command:

```js
Ember.ObjectProxy.extend({ a: function () {}.observes('b') }).create()
```

**Comment by pzuraq** [comment]
That's not supported anymore, and trying that out locally I get a different deprecation:

```
DEPRECATION: Function prototype extensions have been deprecated, please migrate from function(){}.observes('foo') to observer('foo', function() {}). [deprecation id: function-prototype-extensions.observes]
```

I don't get the deprecation you're describing.

**Comment by pzuraq** [comment]
My mistake actually, I was able to reproduce this after switching to an older version of Ember. You are correct, this is a bug, will submit a fix shortly. Sorry again for the confusion, it's been a long week!

**Comment by BillyRayPreachersSon** [comment]
I'm working though upgrading our app from 3.4 LTS to 3.8 LTS. I've removed 7500+ of the `events.inherited-function-listeners` deprecation warnings from our CI test logs, but are left with 8, and they all come from the same internal code in `@ember/-internals/runtime/lib/mixins/-proxy.js`.

We're using `ember-cli` `3.8.3` and `ember-source` `3.8.0`.

Will this fix be backported, so that LT users get the benefit?

Thanks!

**Comment by rwjblue** [comment]
v3.8.2 already includes this fix, please update 😸

**Comment by BillyRayPreachersSon** [comment]
> `ember-source@3.8.2` already includes this fix, please update 😸

Perfect, down to 0 warnings (of that type, at least). Thanks!
