### ISSUE TITLE
Beta releases don't contain everything from master branch

### ISSUE THREAD

**Issue by leepfrog** [emberjs/ember.js#17994]
I have been upgrading my app to Octane using the latest Canary build.  As part of cleaning up my upgrade work, I set the current package version of ember-source to 3.10.0-beta.5 (built today).  When I run my test suite, things that were passing on Canary are no longer passing on the Beta build.  

On closer inspection, I've noticed that the files tagged on Beta do not match what is current on master.  

Compare:
- Master: https://github.com/emberjs/ember.js/tree/master/packages/%40ember/-internals/metal/lib
- Beta.5: https://github.com/emberjs/ember.js/tree/v3.10.0-beta.5/packages/@ember/-internals/metal/lib

According to the release process notes, this doesn't seem like it should be the case:
- https://github.com/emberjs/ember.js/blob/master/RELEASE.md#on-to-the-beta-release
- https://emberjs.com/releases/beta

**Comment by rwjblue** [comment]
Hmm, I don't think I understand. Can you describe the sorts of failures you are seeing?

The code between beta and master is pretty unlikely to be the same at any given time. Generally speaking all new changes land in master, and only things that are bugfixes are pulled into the beta branch.

**Comment by leepfrog** [comment]
The particular issue I'm running into is related to using `@tracked` properties.  In beta.5, they don't work in my application.  On canary, they work fine.  

I've checked my feature flag settings to make sure they're enabled:
```
        EMBER_NATIVE_DECORATOR_SUPPORT: true,
        EMBER_METAL_TRACKED_PROPERTIES: true,
        EMBER_GLIMMER_ANGLE_BRACKET_NESTED_LOOKUP: true,
        EMBER_GLIMMER_ANGLE_BRACKET_BUILT_INS: true,
        EMBER_GLIMMER_FN_HELPER: true,
        EMBER_GLIMMER_ON_MODIFIER: true,
```

I traced the issue down to a difference between versions in  `@ember/-internals/metal` between the beta and canary branches.  When computing whether a property is tracked, this `get` function is ran to establish whether a property is tracked:  https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/metal/lib/tracked.ts#L206

On beta, `CURRENT_TRACKER` is null
On canary, `CURRENT_TRACKER` has a tracker instance.  (so tracked properties work correctly)

**Comment by leepfrog** [comment]
The original question is more around this statement from the https://emberjs.com/releases/beta site:  "The master branches of Ember and Ember Data are promoted to beta every six weeks."  -- which doesn't seem to be the case, since there are differences between master branch and beta tag.

**Comment by rwjblue** [comment]
Tracked properties are not available in beta releases. Feature flagged items are off by default, and **can not** be enabled in beta/release builds.

This guide page describes the feature process (but needs some updates as I peruse it):

https://guides.emberjs.com/release/contributing/adding-new-features/

**Comment by leepfrog** [comment]
Thanks for the clarification!  Trying to catch up after being away for awhile :)
