### ISSUE TITLE
Ember Addons Name Conflict

### ISSUE THREAD

**Issue by bajcmartinez** [emberjs/ember.js#17997]
Hi everyone, I'm facing a big issue due to dependencies that idk how to resolve. I've been going through this quite a bit but still stuck. Hopefully, someone here can help me.

My project is running on ember 2.x.x and has installed several dependencies out of which one that is widely used in the app is:

https://github.com/btecu/ember-select

Now, my company is integrating another solution that comes with an ember addon which contains the following library as a dependency:

https://github.com/adopted-ember-addons/emberx-select

both of them are dropdowns, so far so good, but now, both of them have the same component name, so when I install the new addon, my old dropdowns stop working. Is there any solution for this other than forking one of the projects and rename the addon?

Thanks so much, I will really appreciate any help on this.

**Comment by lukemelia** [comment]
@bajcmartinez I would suggest trying to re-export the components in your app's `app` tree with distinct names. Something like creating the following two files in your app::

```js
// app/components/x-select.js
export { default } from 'ember-select/components/x-select';
```

and

```js
// app/components/emberx-select
export { default } from 'emberx-select/components/x-select';
```

Then use the component from ember-select as `{{x-select ...}}` and the componet from emberx-select as `{{emberx-select ...}}`

**Comment by lukemelia** [comment]
BTW, this is probably a better question for StackOverflow than this repository.

**Comment by bajcmartinez** [comment]
hi @lukemelia thanks for your response, I did a small test case with this and seems to be working fine. I'll do the changes on my main project now and test it there. 
And thanks for the tip on StackOverflow, I posted it on discord as well but with no luck that's why I came here.

I'll close the ticket as done :)
