### ISSUE TITLE
Angle bracket invocation with "id" attribute does not trigger click() handler

### ISSUE THREAD

**Issue by seungjoolee** [emberjs/ember.js#18006]
On Ember 3.4, I have a very basic button component that uses the click event to trigger the alert() function. When I invoke the button component with angle bracket syntax and set an "id" attribute, the click event never triggers. If I remove the "id" attribute then the click event triggers properly.

If I invoke the component with the classic syntax, the event also triggers properly.

Here's a simple twiddle illustrating the problem. Removing the "id" attribute will have the button behave as expected.

https://ember-twiddle.com/7923dc81876eb33337af534659987bfa?openFiles=templates.application.hbs%2Ctemplates.components.button-click.hbs

**Comment by simonihmig** [comment]
I *think* this should have been fixed by https://github.com/emberjs/ember.js/pull/17818. Can you try using Ember 3.10?

**Comment by seungjoolee** [comment]
@simonihmig works on 3.10!
