### ISSUE TITLE
(query-params) helper assertion failing if wrapped in (if) helper

### ISSUE THREAD

**Issue by theroncross** [emberjs/ember.js#18033]
`{{#link-to "a" (if foo (query-params b="c") (query-params d="e"))}}Some link{{/link-to}}`

is failing the following assertion: https://github.com/emberjs/ember.js/blob/eee02fb72a47ff1ffbc9919fcf3fc4b74b937093/packages/%40ember/-internals/glimmer/lib/components/link-to.ts#L870

which was added here: https://github.com/emberjs/ember.js/commit/e6c040ffe60f72c124f9698ca1712cb812655826

**Comment by erkie** [comment]
A workaround I found to work in this case is to use angle-brackets:

```hbs
<LinkTo @route="a" @query={{if foo (hash b="c") (hash d="e")}}>Some link</LinkTo>
```

**Comment by bekzod** [comment]
related #18076

**Comment by rwjblue** [comment]
Closing in favor of #18076, would you mind chiming in over there?
