### ISSUE TITLE
ember-engines & ember-source 3.10 "there is no route named..."

### ISSUE THREAD

**Issue by lennyburdette** [emberjs/ember.js#18034]
Reproduction: https://github.com/lennyburdette/engines-310

Using a `{{link-to}}` to reference an engine's route blows up with ember-source 3.10.

**Comment by lennyburdette** [comment]
Potential fix: https://github.com/ember-engines/ember-engines/pull/647

**Comment by rwjblue** [comment]
Closing this one as I believe this has been addressed and released, please let me know if I'm wrong/missing something.
