### ISSUE TITLE
@action decorator missing

### ISSUE THREAD

**Issue by dev-zetta** [emberjs/ember.js#18047]
Hello everyone,

after upgrading ember and ember-decorators to new versions, I cannot compile my code, because there is missing export for @action decorator from ember object.

`import { action } from '@ember/object'

class MyClass extends Component {
 @action 
 myAction() {

 }  
}`

It reports error ReferenceError: action is not defined.

Using ember-cli v3.10. When I remove the decorator, to make it compile, the action is not found.

Any ideas?

**Comment by rwjblue** [comment]
Most likely you are using out of date dependencies, can you ensure that you are on the latest version of `ember-rfc176-data` (by way of `npm ls ember-rfc176-data`)? Specifically, you need at least ember-rfc176-data@0.3.8 throughout.

**Comment by dev-zetta** [comment]
Here is the output, I'm using newer version:
```
├─┬ ember-cli-babel@7.7.3
│ └─┬ babel-plugin-ember-modules-api-polyfill@2.9.0
│   └── ember-rfc176-data@0.3.9  deduped
└─┬ eslint-plugin-ember@6.4.1
  └── ember-rfc176-data@0.3.9 
```

It seems that decorators are somehow broken, not even services are being injected:
https://github.com/ember-decorators/ember-decorators/issues/444

Is it

**Comment by dev-zetta** [comment]
Edit, that service was not found after I installed flow plugin for babel. But still, even after removing the plugin, I still get error with the action decorator not found.

**Comment by dev-zetta** [comment]
Okay, I did some debugging and found the source of the problem. It's quite silly :)

Here is my component's code:

```
import { action } from '@ember/object'

class GuiButton extends GuiWidget {
  @action
  onClick(e) {
    let action = this.get(`onClick`) // local var
    ...
  }
}
```
As you can see, I used a local variable named action. Somehow it replaced the action decorator/contant.

It got compiled as:
```
  }), _applyDecoratedDescriptor(_class.prototype, "onClick", [action], Object.getOwnPropertyDescriptor(_class.prototype, "onClick"), _class.prototype)), _class));
  var _default = GuiButton;
  _exports["default"] = _default;
```
Notice the **[action]**. When I rename the local variable to action2 or something else, then it gets compiled as **[Ember._action]**.

This is code was working normally when I was using ember-decorators and the action decorator from that package.

**Comment by rwjblue** [comment]
Yikes! This is surprising to me...

**Comment by bardzusny** [comment]
The above bug is still present in 3.14.1: can't use `action` param name in methods decorated with `@action` decorator.

This seems like a more general issue with class method decorators in the core package, though it may be less apparent with other ones than `@action`.

Consider the following example (where `someComputed` will be a getter function without params IRL, making it mostly theoretical):

```js
@computed(...)
someComputed(computed) { ... } // "computed" local variable name
```

Will break with:
```
Uncaught (in promise) ReferenceError: computed is not defined
```

**Comment by rwjblue** [comment]
I suspect the actual bug here is in https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill, if someone has time to submit a failing test that would be super helpful.

**Comment by maxhq** [comment]
@rwjblue Any hints on where to put a test? I tried to assemble a test directly for `babel-plugin-ember-modules-api-polyfill` but the tests there don't unterstand Ember's decorator syntax...

**Comment by dwickern** [comment]
I added a failing test in https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/pull/170

**Comment by rwjblue** [comment]
The fix landed in https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/releases/tag/v3.2.1. I'll work to update the minimum version in ember-cli-babel and release a patch (so folks can more easily guarantee they aren't trolled).
