### ISSUE TITLE
[CLEANUP] remove enabled feature flags on release

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#18060]
## PRs

- EMBER_GLIMMER_IN_ELEMENT https://github.com/emberjs/ember.js/pull/19196
- EMBER_DESTROYABLES https://github.com/emberjs/ember.js/pull/19203
- EMBER_CACHE_API https://github.com/emberjs/ember.js/pull/19204
- EMBER_ROUTING_MODEL_ARG https://github.com/emberjs/ember.js/pull/19206 
- EMBER_GLIMMER_INVOKE_HELPER https://github.com/emberjs/ember.js/pull/19207
- EMBER_GLIMMER_HELPER_MANAGER https://github.com/emberjs/ember.js/pull/19208
- EMBER_GLIMMER_SET_COMPONENT_TEMPLATE https://github.com/emberjs/ember.js/pull/19229

**Comment by mul53** [comment]
@chancancode can i have a crack at this?

**Comment by rajankumar549** [comment]
Hey, can i help to fix this issue. I want to contribute in this project. @chancancode

**Comment by chancancode** [comment]
@mul53 @rajankumar549 you don't need permission, just go ahead and open PR. Preferably one feature flag at a time and maybe add a note here on what you are working on so others can pick something else.

**Comment by neonick** [comment]
@chancancode seems it could be closed?

**Comment by praaatik** [comment]
Is the issue still open? Seems to be merged

**Comment by praaatik** [comment]
Hello @chancancode, I guess this issue could be closed now? Seems to be merged

**Comment by kanavpruthi** [comment]
I am a beginner, and id like to work on a new issue here

**Comment by chancancode** [comment]
@kanavpruthi the specific set of enabled features to remove has changed since this was opened, but there are now new ones that needed to be cleaned up https://github.com/emberjs/ember.js/blob/master/packages/@ember/canary-features/index.ts

**Comment by Alpine-lines** [comment]
Should all of the features in /packages/@ember/canary-features/index.ts have their respective feature flags removed?

**Comment by pzuraq** [comment]
@Alpine-lines any flag that has been set to `true`, and has been released in a minor version of Ember, should be removed. Currently, these ones: https://github.com/emberjs/ember.js/blob/master/packages/@ember/canary-features/index.ts#L19-L23

**Comment by pzuraq** [comment]
The best way to approach this is with one PR per feature flag, to make it easier to review quickly

**Comment by SOUMOJIT-CHAKRABORTY** [comment]
@chancancode Sir I have just learnt javascript and made an web calculator.I want to contribute on opensource, so can you tell me where from I should start?
