### ISSUE TITLE
Mixin.detect() does not work if Mixin is mixed on a parent class

### ISSUE THREAD

**Issue by Herriau** [emberjs/ember.js#18068]
```javascript
var MyMixin = Ember.Mixin.create();
var MyObject = Ember.Object.extend(MyMixin, {});
var MySubObject = MyObject.extend({});

console.log(MyMixin.detect(MyObject.PrototypeMixin)); // true
console.log(MyMixin.detect(MySubObject.PrototypeMixin)); // false, expected true
```

This seems to be the root cause of an issue I'm seeing with Ember Data:

```javascript
// mixins/versioned.js
export default Mixin.create({
  versions: hasMany('versions');
});

// models/version.js
export default DS.Model.extend({
  owner: belongsTo('versioned', { polymorphic: true, inverse: 'versions' }),
});

// models/my-base-class.js
export default DS.Model.extend(Versioned, {});

// models/my-concrete-class.js
export default MyBaseClass.extend({});
```

Usage of `my-concrete-class` causes a crash with the following error:

> `The 'my-concrete-class' type does not implement 'versioned' and thus cannot be assigned to the 'owner' relationship in 'version'. Make it a descendant of 'versioned' or use a mixin of the same name.`

**Comment by alexspeller** [comment]
I made this awful workaround, probably super brittle and sensitive to your ember version.

```js
// app/initializers/patch-mixin-detect.js

import Mixin from '@ember/object/mixin';

export function initialize() {
  let oldDetect = Mixin.prototype.detect;

  Mixin.prototype.detect = function(obj) {
    if (oldDetect.call(this, obj)) {
      return true;
    }

    let SuperClass =
      obj && obj.ownerConstructor && obj.ownerConstructor.superclass;

    while (SuperClass) {
      if (
        SuperClass &&
        SuperClass.PrototypeMixin &&
        (SuperClass.PrototypeMixin.mixins || []).some(m => m === this)
      ) {
        return true;
      }
      SuperClass = SuperClass.superclass;
    }

    return false;
  };
}
export default {
  name: 'patch-mixin-detect',
  initialize
};

```

**Comment by runspired** [comment]
We've actually fixed this in Data by accessing the PrototypeMixin directly

**Comment by alexspeller** [comment]
Hmm, so I'm using a slightly older ember-data version, however the code for assertPolymorphicType is the same - it's still accessing the PrototypeMixin in the version I'm using and is still an issue for me. I'll update here once I get to a more recent version, but AFAICT this is still and issue on latest ember-data

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? With mixins on their way out (doesn't work with ES6 classes), maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by alexspeller** [comment]
Makes sense to me, I think I still have this workaround in a few places but agreed that it's probably not worth fixing.
