### ISSUE TITLE
how to remove console.log from production builds?

### ISSUE THREAD

**Issue by santo74** [emberjs/ember.js#18062]
I was using ember-cli-defeatureify to get rid of console.log statements in my production builds.
This worked fine, despite some deprecation warnings, but now that I upgraded from ember 2.12 to 2.13 (required for an addon I need), it's not working anymore (I guess ES6 related).

Is there another way to get rid of console.log statements in production builds that's compatible with ember 2.13?

ember-cli-defeatureify isn't updated anymore since 2016, so it doesn't seem like it will be updated for newer ember versions any time soon.

**Comment by rwjblue** [comment]
I think in general, the advice here should be: don't include `console.log`'s in your code. If you *do* need them but for development only, you could use something akin to:

```js
import { DEBUG } from '@glimmer/env';

if (DEBUG) {
  console.log('foo');
}
```

^ assumes you have a fairly recent ember-cli-babel version...

**Comment by santo74** [comment]
You're absolutely right I shouldn't use console.log statements at all, but this is an older project where console.log statements are used to get around some issues where browsers provide totally wrong information about errors (wrong filenames, wrong positions in the files, ...)

So I was looking for a quick way to replace the old ember-cli-defeaturify functionality, but maybe this is a good opportunity to clean up the code and deal with possible errors in a different way.
In the end it might be as quick as searching for a working replacement.

Thanks for the advice.
