### ISSUE TITLE
why dependent keys cache is not cleared in dependentKeysDidChange method?

### ISSUE THREAD

**Issue by udhayakumargururaj** [emberjs/ember.js#18102]
Hi,

using ember - 2.14.2
Dependent keys cache is not cleared and the old object is returned everytime. is this expected behavior or is it issue.

**Comment by rwjblue** [comment]
I don't think we can answer in the abstract, can you provide us a demo or other reproduction?

**Comment by locks** [comment]
Closing due to lack of details.
