### ISSUE TITLE
error on invalid angle bracket invocation

### ISSUE THREAD

**Issue by efx** [emberjs/ember.js#18178]
As our team has started using angle bracket invocation for components, a few "invalid" patterns have started:
```hbs
<My-card @list={{this.list}} />
<My-other-thing>
</My-other-thing>
```

I consider this bug in the same group as https://github.com/emberjs/ember.js/issues/17998; developer experience.
As a developer, I would like to see an error about unexpected capitalization when using angle brackets.

**Comment by rwjblue** [comment]
I think this probably falls in the realm of things that we should address via linting tools. From Ember's perspective all of those should be basically equal, but I do agree we want to strongly suggest `<MyCard />` and `<MyOtherThing />` style.

**Comment by efx** [comment]
Moved issue to https://github.com/ember-template-lint/ember-cli-template-lint/issues/515
