### ISSUE TITLE
`@tracked` properties / class getters are ignored by `Object.assign()`

### ISSUE THREAD

**Issue by buschtoens** [emberjs/ember.js#18175]
This is a gotcha a colleague of mine has run into and maybe we should document this somewhere.

```ts
class Foo {
  untrackedProperty = 1234;

  @tracked
  trackedProperty = 5678;
}

const foo = new Foo();
const copyOfFoo = Object.assign({}, foo); // `{ ...foo }` has the same semantics

console.log(copyOfFoo); // => { untrackedProperty: 1234 }
```

> The `Object.assign()` method only copies _enumerable_ and _own_ properties from a source object to a target object. It uses `[[Get]]` on the source and `[[Set]]` on the target, so it will invoke getters and setters. Therefore it assigns properties versus just copying or defining new properties. This may make it unsuitable for merging new properties into a prototype if the merge sources contain getters.

— [MDN: `Object.assign()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Description)

Since `@tracked` places the property onto the class `prototype` and not the class instances and because `Object.assign()` only assigns _own properties_, `@tracked` properties are ignored by `Object.assign()`.

The same is true for all other decorated properties, that get placed on the `prototype`, e.g. `@computed`, or just plain class getters in general (`get prop() { ... }`).

It's just so especially "weird" for `@tracked`, since a `@tracked` property still _looks_ like a regular property assignment, but in fact is not.

I am in no way saying that this is a bug, but I think it could be counter-intuitive to some.

**Comment by pzuraq** [comment]
Yeah, this is unfortunate, but I don't think there's anything we can do about it 😕 no matter how we define the property, it is going to be on the prototype so we can't enumerate it on the instance, and this is required for autotracking.

Definitely agree this should be documented somewhere, maybe in an addendum to the tracked properties docs.

**Comment by locks** [comment]
Thanks for the report and the explanation! Closing as wontfix due to explanation.

**Comment by tehmaestro** [comment]
This is so important! I've been looking for an answer all day. Thanks.

**Comment by Unkrass** [comment]
So is there any workaround for assigning tracked properties to another object?

**Comment by Glarregle** [comment]
@Unkrass yes, you can define this `completeAssign` function and use it, is a shorter version of [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign): 

```
function completeAssign(target, ...sources) {	
  sources.forEach(source => {	
    let descriptors = Object.keys(source).reduce((descriptors, key) => {	
      descriptors[key] = Object.getOwnPropertyDescriptor(source, key);	
      return descriptors;	
    }, {});	
	
    Object.defineProperties(target, descriptors);	
  });	
  return target;	
}
```

```
  let myObj = {};
  let objectWithTracked = { 
    @tracked myProp: 'val',
  }

  completeAssign(myObj, objectWithTracked);
```
