### ISSUE TITLE
Action helper bubbles to route

### ISSUE THREAD

**Issue by huberts** [emberjs/ember.js#18180]
Hi!

If you use action helper in route template like this:

```<div {{action "clickMe"}}>Click me</div>```

then it bubbles the action directly to the Route. If the action is defined also in Controller, it goes to it (and can be bubbled to the Route by returning true, as one would expected).
This behavior does not occur when used with components, e.g.:

```{{test-component xyz=(action "clickMe")}}```

In this scenario the action must be defined in Controller.

[Here](https://github.com/huberts/notification-manager/tree/abd751693ee609cf3e97b2ff6245b6423ddb5eb1), I reproduced this in an example.

**Comment by jelhan** [comment]
If I didn't missed something, this is intended and documented behavior. Please have a look at https://api.emberjs.com/ember/3.10/classes/Ember.Templates.helpers/methods/action?anchor=action and pay special attention to difference in bubbling if used as _closure action_ in_attribute context_ and _handlebars value context_ or in _element space_ (like the new element modifier concept).

**Comment by pzuraq** [comment]
Yeah, so actions can bubble from the Controller -> Route and up the route hierarchy, but _component_ actions will _not_ do this. The _browser events_ will still bubble and propagate like normal, but actions must first go through the controller if you want them to bubble without manually linking up actions and sending them.

**Comment by huberts** [comment]
@jelhan Thank you for the link to the documentation. I see this is documented and (probably) well-thought behaviour, but it is hard for me to understand that the logic behind these two scenarios are not the same. I find the 'element space context' concept quite vague. I close this issue as it is not the bug, but I wish to read more about the three contexts.

**Comment by jelhan** [comment]
@huberts Personally I consider action in element space as legacy code even so it's not deprecated (yet). Will I considered assigning closure actions to element properties as best practice for a long time (e.g. `<button onclick={{action this.doSomething}}></button>`), I would recommend `{{on}}` element modifier ([RFC 471](https://github.com/emberjs/rfcs/blob/master/text/0471-on-modifier.md), [`ember-on-modifier`](https://github.com/buschtoens/ember-on-modifier)) together with `action` decorator these days (e.g. `<button {{on "click" this.doSomething}}></button>`, `class MyComponent extends Component { @action doSomething() {} }`). But have in mind that `{{on}}` modifier is not documented yet, even Octane Preview guides still recommend `action` in element space.
