### ISSUE TITLE
3.11.1: action handler triggers style binding warning

### ISSUE THREAD

**Issue by st-h** [emberjs/ember.js#18193]
❗️   **It seems like this issue only shows up when ember-hammertime is installed. please close if behaviour is intended**

```
<span class="trigger" aria-expanded={{_expanded}} {{action (toggle '_expanded' this)}} role="button">
```
This placed inside a component template triggers the following warning after upgrading to ember 3.11.1:
```
WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see https://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes. Style affected: "touch-action: manipulation; -ms-touch-action: manipulation; cursor: pointer;"
```
Now, if the `action` is removed, the warning goes away:
```
<span class="trigger" aria-expanded={{expanded}} role="button">
```

Stripping away other attributes does not make the warning go away. This still triggers the warning:
```
<span class="trigger" {{action (toggle '_expanded' this)}}>
```

However, binding the action to the onclick handler, fixes it. This does not display the warning:
```
<span class="trigger" aria-expanded={{_expanded}} onclick={{action (toggle '_expanded' this)}} role="button">
```

**Comment by rwjblue** [comment]
My guess is that ember-hammertime is doing something to rewrite the actual AST such that `style` attribute is being set. 

Maybe double check their code, and report over there?

**Comment by st-h** [comment]
@rwjblue I am fairly certain that this is what they are doing. I am just surprised that the warning starts to show up on a 3.11 release, whereas the deprecation seems to have been introduced in ember 1.x (at least according to the link). I already opened an issue over at the ember-hammertime repo. I left this issue here mainly for reasons to make sure there hasn't been any unintentional change from ember 3.10 to 3.11.

**Comment by rwjblue** [comment]
Hmm, I agree that does seem odd. Any way you could create a demo repo where we can swap between 3.10 and 3.11 to see the difference in behavior?

**Comment by eriktrom** [comment]
> My guess is that ember-hammertime is doing something to rewrite the actual AST such that style attribute is being set.

yes in a roundabout way - we set it when the `{{action` modifier is used on non input elements and elements that don't use `onclick=` -- I left a fuzzy memory explanation in his linked issue here https://github.com/html-next/ember-hammertime/issues/90#issuecomment-510527251

feel free to correct my improper usage of vocab (modifier?), its been a while, conceptually im pretty sure those thoughts are correct though -- they are what you presume is happening @rwjblue, but filled in some blanks, i hope its semi-clear :)

**Comment by st-h** [comment]
@rwjblue sure, I needed a simple reproducer to figure out which addon was causing the warning anyway: https://github.com/st-h/bind-warn
Just double checked. switching to ember 3.10 makes the warning go away.

**Comment by rwjblue** [comment]
Thank you! I'll try to poke at this soon.

**Comment by st-h** [comment]
@rwjblue thank you. I think this pretty much is a question of determining if the behaviour we are seeing in 3.11 is correct and intended. I do not see much troublesome here.
I did a few quick tests with adding inline style attributes and it seems that ember 3.11 is handling those warnings correctly. Maybe its just something like the place when those checks are run and it is now picking up the AST transform - but I am pretty much guessing here...

**Comment by rwjblue** [comment]
I completely agree, the troublesome thing (to me) is that the warning didn't show up in 3.10. We also didn't specifically make any changes to "fix" this, so I want to make sure that we don't have some other issue going on. 

tldr; In all likelihood, we'll confirm that the 3.11 state is correct and probably close this issue, but I want to root cause the change to make sure.

**Comment by st-h** [comment]
closing this in favour of more urgent issues
+ the only impact this issue has is a warning
+ this issue is becoming stale
+ hammertime is considered to be deprecated
+ no issues without hammertime
