### ISSUE TITLE
Cannot find module 'internal/fs'  when running ember 

### ISSUE THREAD

**Issue by OAmor** [emberjs/ember.js#18199]
Hello,
i'm facing a problem to run an existing ember project ( this is my first time with ember :) ) , i've installed ember but when i run  `ember serve`  gives me this 
`Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:40:20
    at Object.<anonymous> (/Users/oussama/Desktop/Workspace/backoffice/node_modules/ember-cli/node_modules/configstore/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)`

this is my package.json
`{
  "name": "myname",
  "version": "0.0.0",
  "description": "My name - Back office",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "1.13.1",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-htmlbars": "0.7.6",
    "ember-cli-i18n": "0.0.6",
    "ember-cli-ic-ajax": "1.0.0",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.13",
    "ember-cli-simple-auth": "0.8.0",
    "ember-cli-uglify": "^1.0.1",
    "ember-data": "1.0.0-beta.18",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.2"
  }
}
`
node version : 8.0
npm : 5.0
i tried to change node and npm versions many times with 12 and 11 and even 6 but always a new error appear :(

**Comment by acorncom** [comment]
Hey @OAmor, welcome! Looks like your issue got missed in the midst of everything, did you end up getting things sorted out?

If you did, great! If you didn’t and are able to use Discord, I’d suggest using the help channel in Discord (more details on how to get in here: https://emberjs.com/community) We generally find this type of question gets answered faster on StackOverflow or Discord where chat can help get to the root issue with you faster.
