### ISSUE TITLE
[3.11] Inconsistency between development and production builds

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#18221]
I used to have the following code in 3.10:

```typescript
class ObjectPromiseProxy<T> extends ObjectProxy.extend(PromiseProxyMixin) implements PromiseProxyMixin<T> {
  public constructor(someArgument: any) {
    super(someArgument);
    console.log(someArgument.foobar);
  }

  ...
```

Which was used by code like this:

```typescript
ObjectPromiseProxy.create({
  foobar: 1,
});
```

Updating to 3.11 the same code still works fine but only in development mode. In production `someArgument` is `undefined` and the `console.log` blows up.

I know that this usage is wrong and I've since fixed it but I would guess that this will blow up in development more than it would in production builds but the opposite happens.

**Comment by locks** [comment]
Thanks for the report! Can you reproduce is newer versions of Ember?

**Comment by boris-petrov** [comment]
@locks - yes, I just tried it in `ember-source` 3.18.0 and the same happens. In development it prints `undefined` (because `someArgument` is something) but in production `someArgument` is `undefined` and it blows up.

I'm not sure this really matters that much. It's a very minor thing. If you can "fix" it by some deprecation warning or something - great. If not, this can be closed with no second thoughts.

**Comment by rwjblue** [comment]
This seems to hit on the changes from [emberjs/rfcs#337](https://github.com/emberjs/rfcs/blob/master/text/0337-native-class-constructor-update.md). I'm sorry this bit you, but it is not a bug. The constructor receives a special sigil value in development, not the arguments. The goal of that first argument is to ensure that you are calling `super` properly (and not calling `new Foo()` directly).
