### ISSUE TITLE
Improve documentation of EmberArray

### ISSUE THREAD

**Issue by locks** [emberjs/ember.js#18228]
Going through http://api.emberjs.com/ember/release/classes/EmberArray, you will notice that some of the entries have minimal documentation and no code sample.
The goal is to review each entry, add code samples where missing, and optionally improve the prose.

Please comment in this thread if you pick one of the entries so it can be assigned to you!

## Methods
-  [x] addArrayObserver (@sdebarros) https://github.com/emberjs/ember.js/pull/18272
-  [x] any (@sukima) https://github.com/emberjs/ember.js/pull/18229
-  [ ] arrayContentDidChange
-  [ ] arrayContentWillChange
-  [ ] compact
-  [x] every (@sdebarros) https://github.com/emberjs/ember.js/pull/18236
-  [x] filter (@sdebarros) https://github.com/emberjs/ember.js/pull/18239
-  [x] filterBy (@sdebarros) https://github.com/emberjs/ember.js/pull/18239
-  [x] find (@brunoocasali) https://github.com/emberjs/ember.js/pull/18324
-  [x] findBy (@barryofguilder) https://github.com/emberjs/ember.js/pull/18233
-  [ ] forEach (@Frozenfire92) https://github.com/emberjs/ember.js/pull/18463
-  [x] getEach (@Frozenfire92) https://github.com/emberjs/ember.js/pull/18464
-  [x] includes (@Frozenfire92) https://github.com/emberjs/ember.js/pull/18465
-  [x] indexOf (@Frozenfire92) https://github.com/emberjs/ember.js/pull/18466
-  [x] invoke (@mukilane) https://github.com/emberjs/ember.js/pull/18283
-  [x] isAny (@mcfiredrill) https://github.com/emberjs/ember.js/pull/18505
-  [x] isEvery (@mcfiredrill) https://github.com/emberjs/ember.js/pull/18510
-  [x] lastIndexOf (@Charizard) https://github.com/emberjs/ember.js/pull/18511
-  [x] map (@imkathir) https://github.com/emberjs/ember.js/pull/18376
-  [x] mapBy (@imkathir) https://github.com/emberjs/ember.js/pull/18376
-  [x] objectAt
-  [x] objectsAt
-  [x] reduce
-  [x] reject (@mcfiredrill) https://github.com/emberjs/ember.js/pull/18503
-  [x] rejectBy (@beegan) https://github.com/emberjs/ember.js/pull/18447
-  [ ] removeArrayObserver 
-  [x] setEach (@mukilane) https://github.com/emberjs/ember.js/pull/18287
-  [ ] slice
-  [x] sortBy (@mukilane) https://github.com/emberjs/ember.js/pull/18340
-  [ ] toArray 
-  [ ] uniq
-  [ ] uniqBy
-  [ ] without

## Properties
-  [x] []
-  [x] firstObject (@mukilane) https://github.com/emberjs/ember.js/pull/18386
-  [x] hasArrayObservers (@mukilane) https://github.com/emberjs/ember.js/pull/18385
-  [ ] lastObject
-  [ ] length

**Comment by sukima** [comment]
```patch
From 01f70fce914b39f66edc708248a78bd4343a8ef5 Mon Sep 17 00:00:00 2001
From: Devin Weaver <suki@tritarget.org>
Date: Tue, 6 Aug 2019 11:40:54 -0400
Subject: [PATCH] Update documentation for EmberArray.any

Prior to this change, the wording was inaccurate. It was describing
filtering not the short circuit behaviour of `any()`.

This change attempts to fix that discrepancy and expand on the example
to include both context option and arrow function use.

Issue #18228
---
 .../@ember/-internals/runtime/lib/mixins/array.js   | 21 +++++++++++++++------
 1 file changed, 15 insertions(+), 6 deletions(-)

diff --git a/packages/@ember/-internals/runtime/lib/mixins/array.js b/packages/@ember/-internals/runtime/lib/mixins/array.js
index 2d6089c4c..f770495ea 100644
--- a/packages/@ember/-internals/runtime/lib/mixins/array.js
+++ b/packages/@ember/-internals/runtime/lib/mixins/array.js
@@ -874,18 +874,27 @@ const ArrayMixin = Mixin.create(Enumerable, {
     - `index` is the current index in the iteration.
     - `array` is the array object itself.
 
-    It must return a truthy value (i.e. `true`) to include an item in the
-    results. Any non-truthy return value will discard the item from the
-    results.
+    A return of a falsey value (i.e. `false`) will continue evaluating items in
+    the array until it reaches the end or encounters a truthy (i.e. `true`)
+    return value. If the evaluation reaches the end if the array the result
+    will be `false`. Conversely any evaluation that ends the loop (via
+    returning truthy) will result in `true`.
 
     Note that in addition to a callback, you can also pass an optional target
-    object that will be set as `this` on the context. This is a good way
-    to give your iterator function access to the current object.
+    object that will be set as `this` on the context. It can be a good way
+    to give your iterator function access to the current object in cases where
+    an ES6 arrow function is not appropriate.
 
     Usage Example:
 
     ```javascript
-    if (people.any(isManager)) {
+    let includesManager = people.any(function(person) {
+      return this.isManager(person);
+    }, session);
+
+    let includesStockHolder = people.any(person => person.isStockHolder);
+
+    if (includesManager || includesStockHolder) {
       Paychecks.addBiggerBonus();
     }
     ```
-- 
2.15.0.rc0

```

**Comment by barryofguilder** [comment]
I'd like to take a stab at `findBy`.

**Comment by sdebarros** [comment]
I've submitted a code example for `every`, and would also like to review/add example for  `filter`, `filterBy` and `addArrayObserver`.

**Comment by mukilane** [comment]
I'd like to take `invoke` and `setEach`.

**Comment by mukilane** [comment]
Added an example for `[]` property. #18293

**Comment by flashios09** [comment]
we can **stole** 🤓  some examples from [cakephp collection class](https://book.cakephp.org/3.0/en/core-libraries/collections.html)
![image](https://user-images.githubusercontent.com/1313482/63788286-1d8b8d00-c8ed-11e9-98a1-fd4c5b50963e.png)

**Comment by mukilane** [comment]
Can we add [@readonly](https://jsdoc.app/tags-readonly.html) tag for properties like `firstObject` and `lastObject` ?

**Comment by imkathir** [comment]
@locks  like to take `map` and `mapBy` methods.

**Comment by beegan** [comment]
Hey @locks. Picked up `rejectBy` there in https://github.com/emberjs/ember.js/pull/18447. Will try pick off a few others that look light at the minute.

**Comment by beegan** [comment]
`rejectBy` and `reduce` have been merged if you want to mark them off.

**Comment by Frozenfire92** [comment]
I'm going to start with `forEach`, `getEach`, `includes`, and `indexOf`

**Comment by vinodhrajamuralidharan** [comment]
@locks - I would like to take  forEach, getEach, includes and indexOf

**Comment by mcfiredrill** [comment]
I added an example for `reject`. https://github.com/emberjs/ember.js/pull/18503

**Comment by mcfiredrill** [comment]
Took a stab at `isAny` and `isEvery` as well. https://github.com/emberjs/ember.js/pull/18505 https://github.com/emberjs/ember.js/pull/18506

**Comment by locks** [comment]
@mcfiredrill can you send the whitespace changes separately? that way I can merge it once and you can rebase your PRs!

**Comment by mcfiredrill** [comment]
@locks Sure, that should make my PRs easier to read! 👍 
https://github.com/emberjs/ember.js/pull/18507

**Comment by Charizard** [comment]
@locks Would like to pickup `reject` and `rejectBy`.

**Comment by Charizard** [comment]
@locks Looks like `rejectBy` is already done

**Comment by mcfiredrill** [comment]
@Charizard I made one for reject here. 😅   https://github.com/emberjs/ember.js/pull/18503

**Comment by Charizard** [comment]
@mcfiredrill Oops! Sorry 😓

**Comment by locks** [comment]
Thank you for the help everyone :) I'm updating the issue at the moment.

**Comment by locks** [comment]
Excellent work everyone! Thank you once again for your help in pushing this forward :) Since most of the items are addressed, I'll be closing this issue and opening individual ones which are easier to keep track of.
