### ISSUE TITLE
[3.13.0-beta.1] Nested key dependency warning now throws an error

### ISSUE THREAD

**Issue by patocallaghan** [emberjs/ember.js#18235]
I'm not sure if this is a regression but I wanted to raise it anyway as others upgrading may encounter the issue. Feel free to close if you think it isn't a problem.

In ember-source 3.12 and earlier, having a computed property which has invalid nested key dependencies resulted in a warning, but in ember-source 3.13.0-beta.1 it results in an error.

Take the following example where using `@each` with `items.id` is invalid

``` js
badNestedDependency: computed('items.@each.subitems.id', function() {
  // ... snip ...
}),
```

#### In 3.12 and lower
![image](https://user-images.githubusercontent.com/685034/62701774-0556db00-b9dd-11e9-8188-f9c68c9eefb7.png)

#### In 3.13 beta
![image](https://user-images.githubusercontent.com/685034/62701817-1d2e5f00-b9dd-11e9-8ba4-8391522d679f.png)

I encountered this as currently our app has several instances of these invalid keys (which we definitely will be fixing!) but when trying out the beta our app broke and didn't render (in development).

My understanding was that to start throwing error assertions it needed to go through a deprecation cycle but it doesn't appear the nested key warning has. It was [never explicitly named as a deprecation warning when introduced](https://github.com/emberjs/ember.js/pull/12847).

The error assertion appeared with [the new `@tracked` work](https://github.com/emberjs/ember.js/commit/405d42388472c30e3d7d98c59a000b7ebe4a37c0#diff-5937a3265e321693b18813c382b0d698R75).

### Reproduction
[Code Sandbox Ember 3.12](https://codesandbox.io/s/nested-key-dependency-ember-312-o961m)
[Code Sandbox Ember 3.13 beta](https://codesandbox.io/s/nested-key-dependency-ember-313-beta-4o3z2)
Look in the console for the warning vs error, and the nested key code is in `app/components/nested-key-component.js`

**Comment by rwjblue** [comment]
@pzuraq - Do you recall why we moved the warning to an assertion? Can we migrate back?

**Comment by patocallaghan** [comment]
@rwjblue @pzuraq any update here? Is this an expected change?

**Comment by pzuraq** [comment]
Ah, I'd just thought that this was an invalid use case in general. We can add it back 👍

**Comment by rwjblue** [comment]
Chatted a bit with @pzuraq offline, I think we want to make this a deprecation (instead of an assert) which mitigates the immediate issue in 3.13. Since this was never documented (or even _functional_) the deprecation can be an intimate API one and the moved back to an assertion in 3.17 or later.

**Comment by patocallaghan** [comment]
Closing as this has now become a proper deprecation warning instead. Thanks!

**Comment by rwjblue** [comment]
Thanks for double checking!
