### ISSUE TITLE
v3.12-beta.1 wrong error on component invocation?

### ISSUE THREAD

**Issue by akondo06** [emberjs/ember.js#18231]
Given `user-actions`

**component.js**
```
export default Component.extend({
	actions: {
		editMe() {
			console.log('should show edit form');
		}
	}
});
```
**template.hbs**
```
<button {{action "editMe"}}>Edit<button>
```

If I render that component somewhere else in the app like: `{{user-actions}}` all is fine. But if by some mistake I do `{{user-ACTIONS}}`, an error that "editMe" could not be found on the `component-something` is triggered.

I would expect to get a "Component user-ACTIONS not found" or to properly find the component.

I am currently migrating to `v3.12` from `v2.18` with the `sendAction` deprecation being the biggest change.
This seems to work fine in `v2.18` with `sendAction` as it just worked (seems that I only did this with a single component).

**Comment by rwjblue** [comment]
I'm not certain I follow you on this one, mind making a small demo repo?

**Comment by akondo06** [comment]
https://github.com/akondo06/bug-case-sensitive-component

replace `{{user-actions}}` with `{{user-Actions}}` in `application.hbs`
The reason for it is the way the component is invoked. If you don't make the casing, the template will be loaded, but not the component.
Is this intended behavior?

Seems to happen on 3.8 too so I am not sure....

**Comment by rwjblue** [comment]
> If you don't match the casing, the template will be loaded, but not the component. Is this intended behavior?

No, not really. I think this is a consequence of the changes in https://github.com/ember-cli/ember-resolver/pull/392, we need to ensure we do not find either component templates or components with normalization there.

**Comment by rwjblue** [comment]
I submitted https://github.com/ember-cli/ember-resolver/pull/396 to fix.

**Comment by rwjblue** [comment]
Fixed in https://github.com/ember-cli/ember-resolver/releases/tag/v5.2.1

**Comment by akondo06** [comment]
cool :) thanks.
