### ISSUE TITLE
`helper-test --test-type unit` generates broken code in Ember 3.11

### ISSUE THREAD

**Issue by Windvis** [emberjs/ember.js#18245]
It looks like https://github.com/emberjs/ember.js/pull/15609 was merged without also adjusting the [`helper-test` blueprint](https://github.com/emberjs/ember.js/blob/fb60c41d1aab65be3a249b6c9ea9627c80d8e9c7/blueprints/helper-test/qunit-files/__root__/__testType__/__collection__/__name__-test.js#L16). Since the helper module no longer exports a named function the generated code is invalid by default.

I'm not sure how this should be solved. Unit tests can still be useful for helpers that return values which are not intended for rendering.

**Comment by locks** [comment]
I stumbled onto this myself. If you have a function that you want to call outside of the rendering context, my suggestion is to make a util that you can unit test, and that the helper can then import and use and you would still use a rendering test for the helper.

**Comment by rwjblue** [comment]
> I'm not sure how this should be solved. Unit tests can still be useful for helpers that return values which are not intended for rendering.

We should remove the `--test-type` option for the helper blueprint and associated code.
