### ISSUE TITLE
[Octane] Ember Data model @attr doesn't track

### ISSUE THREAD

**Issue by wongpeiyi** [emberjs/ember.js#18253]
I'm not sure if this is more an Ember Data issue or an unimplemented feature etc

I have a getter that computes off a DS `@attr`. When the attr changes, the template updates correctly once, but if it changes again subsequently the template doesn't update.

Switching from `@attr` to `@tracked` works perfectly however, and so does displaying the attr directly in the template. The only failing case is a getter based off an attr.

Repro here: https://github.com/wongpeiyi/octane-test/commit/6d8b8f18e709a48ee94109d1b7b71c0ffc12b004

**Comment by pzuraq** [comment]
I've confirmed that this is an issue with CPs in general, not just `@attr` (which is implemented as a CP under the hood). I've also confirmed that the work done in #18223 fixes this issue, so I'll add a test to that PR to ensure we cover it.

**Comment by wongpeiyi** [comment]
Thanks @pzuraq, looks like it's fixed in master after the merge
