### ISSUE TITLE
Router#url should not error when `location` is a string

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#18260]
This function should check if `location` is a string, and avoid calling `.getURL()` on it if it is. `location` on `Ember.Router` **starts** as a string, and is only converted to an object when routing itself is initialized. In many tests routing is _never_ initialized, yet we unconditionally call `.getURL()` on the string (usually `'none'.getURL()`).

For context, this is mostly only an issue because when you `assert.strictEqual(someEmberObject, someOtherObject)` we happen to try to print out the diff of the **entire `owner` object** 😩. We should fix that separately, but in the meantime this method should not have the assumption that `location` is an object with `getURL` on it:

https://github.com/emberjs/ember.js/blob/5c723255c17326ceda374992f5c340965ea245e6/packages/%40ember/-internals/routing/lib/system/router.ts#L1793-L1795

I'd love it if someone were to tweak this to _something_ like:

```
  url: computed(function(this: Router<Route>) {
    let { location } = this;
    if (typeof location !== 'string') {
      return location.getURL();
    }
  }),
```

And then add a unit test that instantiates the router and calls `router.url` and confirms it does not throw an error.

**Comment by ryanolsonx** [comment]
I'd love to pick up this one.

**Comment by ryanolsonx** [comment]
Can we close this since the PR has been merged?

**Comment by rwjblue** [comment]
Yep, thank you!!
