### ISSUE TITLE
`<LinkTo>` should allow `model` and `models` if either is `undefined` or `null`

### ISSUE THREAD

**Issue by luxzeitlos** [emberjs/ember.js#18265]
The current behavior is specified in the RFC. However its problematic when creating wrapper components that should behave the same way:

```
    <MyLink @title="Bla" @route="myroute" @model={{this.myModel}} />
    <MyLink @title="Bla" @route="otherRoute" @models={{arr this.firstModel this.secondModel}} />
```

Now `MyLink` would look like this:

```
    <LinkTo @route={{@route}} @model={{@model}} @models={{@models}}>
     ...
    </LinkTo>
```

but this will fail, because `LinkTo` fails when `@model` and `@models` is provided.

It could be very convenient if this would work.

**Comment by chancancode** [comment]
You can possibly do `@models={{if @model (array @model) @models}}`

**Comment by rwjblue** [comment]
I agree that we should try to come up with a solution here, but I'm not sure we should try to make `null` or `undefined` have special behaviors (they are _sometimes_ the actual value)...

**Comment by locks** [comment]
Hm, could the wrapper use the router service to avoid the problem?

**Comment by rwjblue** [comment]
I'm not sure how, have an idea of the pseudo code needed?

**Comment by locks** [comment]
@mehulkar [RFC #459](https://emberjs.github.io/rfcs/0459-angle-bracket-built-in-components.html) specifically introduced `@models` and `@model`, it is unlikely to get removed soon.

**Comment by elwayman02** [comment]
As a workaround until we get splarguments, wrapper components can implement a computed property like this:

```
  @computed('args.model', 'args.models')
  get modelOrModels() {
    let hasModel = 'model' in this.args;
    let hasModels = 'models' in this.args;

    assert(
      'You cannot provide both the `@model` and `@models` arguments.',
      !hasModel || !hasModels
    );

    if (hasModel) {
      return [this.args.model];
    } else if (hasModels) {
      return this.args.models;
    }
    return [];
  }
```

and then invoke like so in their template:

`<LinkTo  @models={{modelOrModels}} />`

It's not an ideal solution for LinkTo to force this much work just to create a wrapper component, but it *does* work and it also allows `undefined` and `null` as explicit values passed into the wrapper still, while making it so the wrapper can maintain the same API.

Inspiration: This is almost exactly [what LinkTo does](https://github.com/emberjs/ember.js/blob/v3.18.1/packages/%40ember/-internals/glimmer/lib/components/link-to.ts#L486) itself, but with a much cleaner, less wonky implementation.

**Comment by locks** [comment]
Closing as wontfix. There are a couple work arounds, and with the new [router helpers](https://rfcs.emberjs.com/id/0391-router-helpers) it is easier to build your own `LinkTo`, as well.
