### ISSUE TITLE
If passing hash helper as argument, @obj and this.obj are not the same

### ISSUE THREAD

**Issue by jelhan** [emberjs/ember.js#18279]
If invoking a component like `<MyComponent @obj={{hash}} />`, `{{@obj}}` and `{{this.obj}}` are not equal. Is this expected behavior or a bug?

You could find a reproduction in this CodeSandbox: https://codesandbox.io/s/my-app-gw0mu

It has an `equals` template helper that does a strict comparison of it's arguments. This one is used by a `<MyComponent>` as `{{equals @obj this.obj}}`. It's `false` for `<MyComponent @obj={{hash}} />`. I would have expected it to be `true`.

Please note that `<MyComponent @obj={{this.obj}} />` with `this.obj` being a POJO set on the controller, is `true`.

**Comment by chancancode** [comment]
Hi @jelhan! I think this is indeed "expected"; it's not guaranteed that they are never identical, but it's not guaranteed that are identical either. There is a good chance the empty case would happen to be identical for optimizations reasons, but in general I would expect most of the time they are not.

The reason being, the object is built each time we need to "cross into JavaScript" and we don't guarantee any kind of caching there. You would probably want to do something similar to QUnit's `deepEqual` instead.

**Comment by jelhan** [comment]
@chancancode Thanks for your detailed response. Do you see any chance to add an assertion or TemplateLint rule helping to avoid these edge cases? Equal comparison was just a very simplified show case. I was running into this with way more complex scenario in which a yielded component was expected to alter `{{@obj}}` and `this.obj` as passed to an action handler. In these case you need to lookup two different files to even notices that one time `{{@obj}}` and onetime `this.obj` is referenced.

Please have a look at https://github.com/kaliber5/ember-bootstrap/pull/877 for details. Relevant code pieces are theses ones (simplified):

```js
// addon/components/base/bs-form.js

export default Component.extend({
  submit() {
    let { model } = this;
    this.onSubmit(model);
  }
});
```

```hbs
// addon/templates/components/common/bs-form.hbs

{{yield
  (hash
    element=(component this.elementComponent
      model=@model
    )
  )
}}
```

Yielded `element` component is expected to mutate the object passed in as `model` argument. IMO it's very difficult to spot that this won't work if caller passes in `{{hash}}` helper as `model` argument.
