### ISSUE TITLE
Computed/Observer no longer watching properties when grouped

### ISSUE THREAD

**Issue by nezmen** [emberjs/ember.js#18295]
I am upgrading an app from 2.12 to 3.11 and ran into an issue where my observers and computed properties were no longer firing.  After some investigation, I found that it was due to how they were defined.  I was not able to find any issues or documentation that says to use one over the other.  I am familiar with using attributes on an object to trigger the property recomputation: `info: computed('obj.{name,height}', function()` which seems really similar.

Is this now the correct way to define computed/observer functions or is this an issue that needs to be resolved?

Works:
`compGood: computed('propA', 'propB', function()`
...
`ObserverGood: observer('propA', 'propB', function()`

Does not work anymore:
`compBad: computed('propA,propB', function()`
...
`ObserverBad: observer('propA,propB', function()`

Example of issue:
[Link to Twiddle](https://ember-twiddle.com/121eacff14eec373a5f9c030589b7489?openFiles=controllers.application.js%2C)

**Comment by btecu** [comment]
Was this documented as supported anywhere?

**Comment by pzuraq** [comment]
I'm actually pretty surprised that the `'propA,propB'` style worked before. The public API is definitely to pass in each individual key, unless you use the full `{}` braces style key definitions for multiple subkeys.

I would recommend updating your computed/observer definitions, I don't believe we'll introduce the old behavior, it was likely removed before Ember 3 was released.

**Comment by nezmen** [comment]
I ended up changing them all already.  It took me most of the day, but its done.  I mainly just wanted to make sure that a bug was not unintentionally introduced.  I assumed that if I had the issue then maybe others would too.

**Comment by pzuraq** [comment]
Oh yeah don’t get me wrong, thank you for opening up the issue! I was just really surprised it work at all, haha 😅

I’m going to close this issue for now since it’s a won’t fix, but it’ll be good to have this here so if anyone encounters it, they can find it in the issue tracker. Thanks again!
