### ISSUE TITLE
`Binding style attributes may introduce cross-site scripting vulnerabilities` false positive

### ISSUE THREAD

**Issue by Windvis** [emberjs/ember.js#18334]
Ember v3.11

The following Template only glimmer component triggers the `Binding style attributes may introduce cross-site scripting vulnerabilities` warning. 

```
{{!template-lint-disable no-inline-styles}}
<div
  class={{cx "absolute h-1/2 w-2 z-0" @color}}
  style="transform: translateX(3px);"
  ...attributes
></div>
```

Since I hardcode the styles, and don't bind any value to it at all, I don't think it should display the error.

It seems to be related to the splattributes. The warning disappears if I remove `...attributes`.

**Comment by rwjblue** [comment]
Is the invocation site passing `style` also?

**Comment by Windvis** [comment]
@rwjblue No only a class attribute:

```hbs
<ActiveMovingUnitStatus::ConvoyConnectionLine @color={{this.theme.convoyConnectionColor}} class="-bottom-1"/>
```

**Comment by mhankus** [comment]
In my case adding action to button causes the same false warning (ember 3.15)
```
<button style="margin: 0 0 0 13px;" class="button small alert" {{action "removeElement" element.id}}>
              <strong>remove</strong>
</button>
```
and the warning is
```
warn.js:59 WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see https://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes. Style affected: "margin: 0 0 0 13px;"
```
removing action modifier, removes warning.

**Comment by mhankus** [comment]
@rwjblue it looks like glimmer bug. I've added test to style-warning-test.js (glimmervm) which fails 

```
    test('Standard element with static style and  element modifier' , assert => {
        registerModifier(context.registry, 'foo');
        let template = compile('<button style="display: flex" {{foo}}>click me</button>');
        render(template,{});
        assert.strictEqual(warnings, 0);
    });
```
So maybe this issue should be moved to glimmer. I've tried to debug it, but I'm not sure what assumptions were made in templateCompiler.ts - openElement function (it looks like, simple elements with modifiers are treated like components - or at least its attributes are 
```
this.attribute([attrs[i]], !simple || actionIsComponent);
```
(simple is false, because element has modifiers). 
That is all I've managed to determine.

**Comment by mhankus** [comment]
I'll try to prepare Pull Request for glimmer-vm which fixes this issue. I'll add note here when it is ready.

**Comment by mhankus** [comment]
I've created pull request in glimmer-vm for static styles reported as possible XSS vulns
https://github.com/glimmerjs/glimmer-vm/pull/999
@rwjblue - can you take a look at it ?

**Comment by SergeAstapov** [comment]
Looks like this has just been fixed in https://github.com/glimmerjs/glimmer-vm/pull/1035
