### ISSUE TITLE
Glimmer Pods components are silently not rendering in Octane

### ISSUE THREAD

**Issue by lolmaus** [emberjs/ember.js#18350]
Hi!

## Description

Created a fresh app with the Octane blueprint.

Discovered that Glimmer components are not rendering when defined in the Pods structure. Instead, a `<!---->` comment is rendered.

## Steps to reproduce:

1. Create a fresh Octane app and a Glimmer component in Pods:

    ```
    npx ember-cli new glimmer-component-pods-bug -b @ember/octane-app-blueprint --yarn
    cd glimmer-component-pods-bug
    ember g component glimmer-component-pods -gc -cs -p
    ```

2. Enable optional Pods in `config/environment.js`:

```js
    modulePrefix: 'glimmer-component-pods-bug',
    podModulePrefix: 'glimmer-component-pods-bug/pods',
```

3. Add some text to the component's template:

        Soupy Twist!

4. Add the component to a parent template:

    ```
    Mr Music, will you play?
    <GlimmerComponentPods/>
    ```

5. Run the app with `ember s` and visit http://localhost:4200 .

## Expected result

I should see the following in the rendered HTML:

```
Mr Music, will you play?
Soupy Twist!
```

## Actual result

I see the following in the rendered HTML:

```
Mr Music, will you play?
<!---->
```

The component has not rendered. There is no error in the browser console.

## Reproduction

Reproduction repo: https://github.com/lolmaus/glimmer-component-pods-bug

#### config/environment.js:

```
    modulePrefix: 'glimmer-component-pods-bug',
    podModulePrefix: 'glimmer-component-pods-bug/pods',
```

#### Template:

```
<p>
  Glimmer Classic: <GlimmerComponentClassic/>
</p>

<p>
  Glimmer Flat: <GlimmerComponentFlat/>
</p>

<p>
  Glimmer Pods: <GlimmerComponentPods/>
</p>


<p>
  Classic Pods: <ClassicComponentPods/>
</p>
```

#### Rendered result:

![image](https://user-images.githubusercontent.com/200884/64153868-69cc5500-ce38-11e9-9572-f4672c6960fc.png)

![image](https://user-images.githubusercontent.com/200884/64153951-8bc5d780-ce38-11e9-9e7c-3099b7bddf1a.png)

#### Project structure:

![image](https://user-images.githubusercontent.com/200884/64154049-b9128580-ce38-11e9-9766-23235a5f8603.png)

## Comment

The worst thing about is that Octane does not support Glimmer Pods, and `ember-css-modules` [does not support Component Co-Location](https://github.com/salsify/ember-css-modules/issues/151).

On the bleeding edge, we're stuck with classically separated component files. :finnadie:

**Comment by buschtoens** [comment]
Can you try running this without a different `podModulePrefix`?

```
    modulePrefix: 'glimmer-component-pods-bug',
    podModulePrefix: 'glimmer-component-pods-bug',
```

The components need to be moved on directory up then.

**Comment by lolmaus** [comment]
@buschtoens Tried, same result.

**Comment by chancancode** [comment]
Can you gist dist/your-app.js after running ember build?

**Comment by lolmaus** [comment]
@chancancode https://gist.github.com/lolmaus/e08ad74c70f951e508f3557853bde346

**Comment by chancancode** [comment]
cc @rwjblue

**Comment by fpauser** [comment]
Same here, really annoying as component.ts and template.hbs cannot reside in the same directory...

**Comment by rwjblue** [comment]
@chancancode / @josemarluedke - Is this the same basic issue as https://github.com/ember-cli/ember-cli-htmlbars/issues/308 ?

**Comment by josemarluedke** [comment]
I can confirm that is something going on here. 

I just tested out in my octane app (using pods layout). I have moved one component to co-location (app/components/my-component/index.{hbs,js}), while leaving all other components in pods. That component now does not render, and It doesn't give any errors. It just doesn't render anything.

**Comment by rwjblue** [comment]
> That component now does not render, and It doesn't give any errors.

Sorry, which one doesn't render? The component you moved into the colocation setup?

**Comment by chancancode** [comment]
I tried to reproduce the issue at https://github.com/ember-learn/super-rentals-tutorial/pull/72 but everything seems to work correctly. If you are experiencing this issue please fork https://github.com/chancancode/super-rentals-pods-ish/ and see if you can make it fail!

**Comment by lolmaus** [comment]
I have upgraded the reproduction app to latest dependency versions from the Octane blueprint, and the issue is resolved.

![image](https://user-images.githubusercontent.com/200884/65851503-b6ce1900-e35b-11e9-8ce9-d66b5a4c1e85.png)

**Comment by chancancode** [comment]
👍👍👍
