### ISSUE TITLE
why this repo is not under ember topic when searching on github?

### ISSUE THREAD

**Issue by icyhat** [emberjs/ember.js#18373]
the ember.js repo can not be found under ember topic, which is hard to find find this repo.

**Comment by chancancode** [comment]
I do see it [on this page](https://github.com/topics/ember), for me it was the forth result. I'm not sure why it wasn't the first result, but I don't think that's something we can control.

**Comment by chancancode** [comment]
Closing this now, but if you think there are anything we are supposed to do other than adding the "ember" topic to the repo (it was already added), let us know.
