### ISSUE TITLE
Ember.get/Ember.getWithDefault don't work as expected when the key name has "." in it since version 3.8

### ISSUE THREAD

**Issue by snemh** [emberjs/ember.js#18377]
We have use case where the key name has "." in it. 

Eg: 
const unionSubContent = {
"id": 1,
"com.linkedin.campaignManager.subtreeNode": {
      conversationId: 2
 }
}
**getWithDefault(unionSubContent, "com.linkedin.campaignManager.subtreeNode", {});**

AND

{{leadgen-form-creation
data-test-defaultResponse={{question.typeSpecificQuestionDetails.[com.linkedin.voyager.feed.revenue.PreviewTextQuestionDetails].defaultResponse.string}}
}}

This worked as expected until 3.7. In 3.8 a commit was checked in to resolve path names correctly
https://github.com/emberjs/ember.js/pull/17166/commits/cbbc4c4fd014823df44fbdf2eceaec3520014beb
This has stopped working since then.

**Comment by pzuraq** [comment]
It looks like the original motivation for this was performance: https://github.com/emberjs/ember.js/pull/17166

I think given the perf improvements it's not really possible to revert that commit completely. It may be possible to do a check to see if that property exists in the object first before getting the path, but I feel like that would make the behavior of `get` a bit more ambiguous and confusing overall.

Short term, I would recommend converting to this:

```js
const unionSubContent = {
  "id": 1,
  "com.linkedin.campaignManager.subtreeNode": {
    conversationId: 2
  }
}

let value = unionSubContent['com.linkedin.campaignManager.subtreeNode'] || {};
```

if you need to have more strict nullish defaulting behavior (e.g. only default if null/undefined), you could write a simple `defaultTo` function to help out:

```js
function defaultTo(obj, key, defaultValue) {
  return (obj[key] === null || obj[key] === undefined) ? defaultValue : obj[key];
}

let value = defaultTo(unionSubContent, 'com.linkedin.campaignManager.subtreeNode', {});
```

In the future, [nullish coalescing](https://github.com/tc39/proposal-nullish-coalescing) will make this much easier:

```js
let value = unionSubContent['com.linkedin.campaignManager.subtreeNode'] ?? {};
```

**Comment by rwjblue** [comment]
`get` and `getWithDefault` _should_ have the same behaviors here, and both should be treating the argument as a property path (not a property name). The fix in 3.8 definitely seems correct to me...

**Comment by snemh** [comment]
Thanks for responding @pzuraq . Ya I already changed to use `unionSubContent['com.linkedin.campaignManager.subtreeNode'] || {};` . 

But given that the usage in template doesn't work too, we may have to fix this as it would surprise users. Right now, we have a workaround for templates too.

Eg usage for template
{{leadgen-form-creation
defaultResponse={{question.typeSpecificQuestionDetails.[com.linkedin.voyager.feed.revenue.PreviewTextQuestionDetails].defaultResponse.string}}
}}

**Comment by rwjblue** [comment]
This does not seem like a valid template snippet, can you double check what you are using?

```hbs
{{leadgen-form-creation
data-test-defaultResponse={{question.typeSpecificQuestionDetails.[com.linkedin.voyager.feed.revenue.PreviewTextQuestionDetails].defaultResponse.string}}
}}
```

**Comment by snemh** [comment]
Pasting from the real example

`{{#each formData.questions as |question idx|}}
                <div
                  data-test-question-object={{idx}}
                  data-test-question-id={{question.questionId}}
                  data-test-question={{question.question}}
                  data-test-name={{question.name}}
                  data-test-predefinedField={{question.predefinedField}}
                  data-test-responseEditable={{question.responseEditable}}
                  data-test-defaultResponse={{question.typeSpecificQuestionDetails.[com.linkedin.voyager.feed.revenue.PreviewTextQuestionDetails].defaultResponse.string}}
                >
                  {{#each question.typeSpecificQuestionDetails.[com.linkedin.voyager.feed.revenue.PreviewMultipleChoiceQuestionDetails].options as |option optionIdx|}}
                    <div
                      data-test-option-object={{optionIdx}}
                      data-test-option-text={{option.[com.linkedin.voyager.feed.revenue.PreviewTextOptionQuestion].text}}
                    />
                  {{/each}}
                </div>
              {{/each}}`

**Comment by locks** [comment]
`getWithDefault` is now [deprecated](https://deprecations.emberjs.com/v3.x#toc_ember-metal-get-with-default) and with the release of Octane, `get` is only necessary for Proxy object properties, so I'm not sure this is still relevant.
I'm closing but please re-open if necessary.
