### ISSUE TITLE
Checkbox with mut and get

### ISSUE THREAD

**Issue by arthur-s** [emberjs/ember.js#18391]
Ember version: 2.18
Checkbox with `mut` and `get`:
```
{{input type="checkbox" checked=(mut (get data key)) required=params.required }}
```
throws exception
```
message: "Assertion Failed: Cannot call set with 'foo' on an undefined object."
```

Here's twiddle for error: https://ember-twiddle.com/f18762866b47e35b118d6a857642fc31

**Comment by chancancode** [comment]
Seems like it’s saying `data` is undefined

**Comment by arthur-s** [comment]
@chancancode thanks, I was not carefull. Here's working example - https://ember-twiddle.com/f18762866b47e35b118d6a857642fc31?openFiles=templates.components.my-form.hbs%2C

**Comment by locks** [comment]
Hm, the Twiddle does not reproduce the problem stated at the top so I'm closing this.
