### ISSUE TITLE
cannot access values in a Map using Ember.get

### ISSUE THREAD

**Issue by efx** [emberjs/ember.js#18408]
As a developer I expect interoperability with some native JavaScript APIs. I found that `Ember.get` does not support accessing string keys in a `Map`. This tripped me up when using the `{{get myMap someKey}}` in a component.

I did some research in discord and @krainboltgreene ran into the same issue and provided a simpler example:
```js
Ember.get(
  new Map([['a', true]]),
  'a'
)
```

Executing the above snippet returns `undefined` but I expect it to return `true`. I tested on 3.12 and 3.13.0-beta.5.beta+a920922e.

## possible solutions

- for certain kinds of data used as keys support getter behavior
- do not support `Maps` but emit a warning that `Ember.get` does not support using Maps

This is a papercut but strives for eliminating more  ["conceptual complexity"](https://github.com/emberjs/rfcs/pull/519#issue-302184405).

**Comment by chancancode** [comment]
I'm not sure about this. You cannot access the map items with the dot or square bracket notations either, which is what `Ember.get` is.

```js
let m = new Map();

m.set('foo', 'FOO');
m.get('foo'); // => 'FOO'

m.foo; // => undefined
m['foo']; // => undefined
Ember.get(m, 'foo'); // => undefined
```

**Comment by efx** [comment]
That is a fair point; I had not realized Maps only support `get` and `set` to individually interact with values. There does seem to be conflation or overloading with what `get` means. I think it would be helpful to describe or warn of this incompatibility somewhere though so it does not appear to be an Emberism.  

What do you think the risks of warning about this with an `assert` in the source?
