### ISSUE TITLE
"...attributes" doesn't work with the "component" built-in helper.

### ISSUE THREAD

**Issue by BnitoBzh** [emberjs/ember.js#18402]
When a component is invoked by the `component` built-in helper, `...attributes` has no effect in the requested component template.

```handlebars
{{! templates/component/parent.hbs }}
{{component this.componentChildName class="foo" data-value="bar"}}
```
```handlebars
{{! templates/component/child.hbs }}
<div class="child-class" ...attributes> ... </div>
```

```html
<!-- The result must be -->
<div class="child-class foo" data-value="bar"> ... </div>
```

**Comment by pzuraq** [comment]
I think the issue here might be that `class` in the `component` helper is not an attribute, and neither is `data-value`. They are _arguments_. There currently isn't a way to add attributes via the component helper, we're working on it here: https://github.com/emberjs/rfcs/issues/497

**Comment by lupestro** [comment]
Should something like the following be an effective workaround? 
```
{{#let (component this.componentChildName) as | MyComponent | }}
<MyComponent class="foo" data-value="bar"/>
{{/let}}
```
It's a little wordy but it gets you out of a helper into a component.

**Comment by chancancode** [comment]
Yep. This is a missing feature already tracked in https://github.com/emberjs/rfcs/issues/497. 

@lupestro what you said would work, in fact you don't even need the `let`:

```
<this.componentChildName class="foo" data-value="bar" />
```

The problem is that you cannot add the attributes into `this.componentChildName` and pass it around.
