### ISSUE TITLE
Deprecate window.ENV

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#18413]
> We should only use window.EmberENV (usage of window.ENV is discouraged, and only exists as a form of legacy support). I’ll do a separate PR to add a deprecation if we find and use window.ENV.

_- @rwjblue in #18372_

**Comment by rwjblue** [comment]
The basic idea here is to refactor this:

https://github.com/emberjs/ember.js/blob/7e89ec19f9b54cf475861f312c34205fc1b3b98c/packages/%40ember/-internals/environment/lib/env.ts#L244

To check if we are falling back to `global.ENV` and issue a deprecation if we do. Something like:

```js
let providedEnv = global.EmberENV;
if (providedEnv === undefined) {
  providedEnv = global.ENV;

  deprecate(
    'Configuring Ember\'s boot options via `window.ENV` is deprecated, please migrate to `window.EmberENV` instead.',
    providedEnv === undefined,
    {
      id: 'ember-environment.window.env',
      until: '3.17.0',
    }
  );
}

(EmberENV => {
  // ...snip IIFE contents...
})(providedEnv);
```

**Comment by rwjblue** [comment]
Closed by https://github.com/emberjs/ember.js/pull/18441
