### ISSUE TITLE
feature:enable vs feature:enabled (message is misleading as the ...feature:enabled.... does not work

### ISSUE THREAD

**Issue by AvinishSharma** [emberjs/ember.js#18430]
"enabled" should be "enable" in the following...(ember feature:enabled template-only-glimmer-components)
           
    * The template-only-glimmer-components optional feature should be enabled under Octane, run `ember feature:enabled template-only-glimmer-components` to enable it

This is the message that was shown while trying to bring up ember server.

**Comment by chancancode** [comment]
#18429
