### ISSUE TITLE
[Deprecation Tests] Usage of window.ENV in tests/index.html

### ISSUE THREAD

**Issue by Alonski** [emberjs/ember.js#18459]
A recent PR introduced a deprecation for using window.ENV.
Tests Index.html is using this:
https://github.com/emberjs/ember.js/blob/master/tests/index.html#L41

Caused by: #18441

**Comment by rwjblue** [comment]
@astronomersiva - Think you might have a minute to shoot off a PR fixing?

**Comment by rwjblue** [comment]
Closed by #18521
