### ISSUE TITLE
CustomEvents documentation is confusing

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/ember.js#18456]
How does one add customEvents with modern ember-cli? I'm assuming it should be done in an initializer?

https://api.emberjs.com/ember/3.13/classes/Application/properties/customEvents?anchor=customEvents

It seems like it should be done where the application is created?

See also this stackoverflow question:

https://stackoverflow.com/questions/58200147/ember-add-customevents

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. 

Maybe this can help?

https://github.com/emberjs/ember.js/pull/12057

This issue has been open for a while without anyone jumping in to fix it. The reality is that unless you want to fix the bug itself, it will likely stay that way.

The time of core team members is very limited, and we all want them to focus  on moving the framework forward (high-leverage things), leaving fixing of edge case bugs to "fringe volunteers", such as you and me.

By closing some old issues we reduce the list of open issues to a more manageable set. Let me know if you think this is a mistake and that the issue should stay open.
