### ISSUE TITLE
Error when using `{{items.firstObject}}` with `array` helper

### ISSUE THREAD

**Issue by GavinJoyce** [emberjs/ember.js#18455]
The following template seems to throw a run time error in 3.14.0-beta.3:

```hbs
{{#let (array "one" "two" "three") as |items|}}
  first: {{items.firstObject}}
{{/let}}
```

The error is: `TypeError: Cannot read property 'tag' of undefined`

<img width="763" alt="Screenshot 2019-10-02 at 17 08 18" src="https://user-images.githubusercontent.com/2526/66061375-40860e00-e537-11e9-97f4-6fd2dfd2fee0.png">

**Comment by bertdeblock** [comment]
I'm seeing the same error on `3.13.2`.

**Comment by rwjblue** [comment]
Definitely seems like a bug to me.

**Comment by pzuraq** [comment]
This appears to have been a bug before 3.13 as well, I don't believe it's related to autotracking or recent refactors in general. I don't think these properties were ever defined on the result of the `(array)` helper, actually. This occurs for any other random value too.

This definitely shouldn't throw an error, but I'm not convinced we should include `firstObject` or `lastObject` as properties. Another option would be to return `undefined` for any value that wouldn't be on a standard JS array.

**Comment by sukima** [comment]
In case anyone — like me — finds this bizarre and unaddressed bug or are still stuck on old ember version (3.12 for me) here is the work around:

```hbs
{{#let (array "one" "two" "three") as |items|}}
  first: {{items.[0]}}
{{/let}}
```

**Comment by locks** [comment]
Issue has since been addressed.
