### ISSUE TITLE
API docs for Ember.Application need updating 

### ISSUE THREAD

**Issue by mehulkar** [emberjs/ember.js#18469]
https://api.emberjs.com/ember/release/classes/Application

The API docs are a bit outdated, referencing Ember.View, and outdated import syntax for initializers.

**Comment by acorncom** [comment]
@mehulkar they are indeed. Would you have time to help clean them up a bit? There's a lot to do, so more hands always makes the work lighter ...

**Comment by mehulkar** [comment]
made some updates in #18502
