### ISSUE TITLE
[3.13] Regression when using @each on an array with undefined elements

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#18474]
[Here is a reproduction repo](https://github.com/boris-petrov/ember-each-bug)

The last commit downgrades Ember to 3.12 and the example works. The previous is on Ember 3.13 and does not.

Having a computed property that depends on an array with `undefined` in it by using `@each` is broken in 3.13.

P.S. The error is something like `When using @each to observe the array ``, the items in the array must be objects`.

**Comment by pzuraq** [comment]
Can confirm this is a change in behavior, the original assertion this was based on only runs against non-falsy values (terribly inconsistent, but no reason it should have changed). Will try to get a fix in for this today.
