### ISSUE TITLE
focusIn/focusOut don't work when jQuery integration is disabled

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#18472]
[Here is a reproduction repo](https://github.com/boris-petrov/ember-jquery-integration-bug)

When the second commit is used (that is, before enabling the jQuery integration feature), clicking on the checkbox does not call the handler and the console.log doesn't show up. Checking out the last commit fixes the issue.

Note that this happens only on "old" browsers - I'm testing with Firefox 47.0.2. I would guess the same is true for Internet Explorer 11. On Chrome and the latest Firefox it works fine.

**Comment by boris-petrov** [comment]
In a [Discord discussion](https://discordapp.com/channels/480462759797063690/608346628163633192/631049583308439563) we found that this is due to Firefox 47 not supporting the `focusIn` and `focusOut` events. the jQuery integration used to wrap the existing events and expose those two. Without it, these events are no longer available.

This is not exactly a bug in Ember but it definitely is something to be aware of. Not sure if there is something that can be done. Maybe at least specify in the [documentation](https://guides.emberjs.com/release/components/handling-events/#toc_event-names) that some events might not be supported on some browsers without the jQuery integration...

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. It seems outdated and likely no longer relevant.

By closing some old issues we reduce the list of open issues to a more manageable set. Let me know if you think this is a mistake and that the issue should stay open.
