### ISSUE TITLE
@tracked decorator can create syntax error

### ISSUE THREAD

**Issue by kanongil** [emberjs/ember.js#18475]
The following will produce a runtime syntax error in the generated javascript:

```js
import { tracked } from '@glimmer/tracking';

class A {
  a = 1;
}

class B extends A {
  b = super.a;
}

class C extends B {
  @tracked c = super.b;
}
```

When run in Chrome it abort before running any code due to a syntax error. If I remove the `class C` declaration, it works fine.

```
Uncaught SyntaxError: 'super' keyword unexpected here
```

---

* ember: 3.13.2 (octane)
* ember-cli: 3.13.1

**Comment by pzuraq** [comment]
This is likely a bug with transpilation, so I'm unsure we'll be able to fix it in Ember directly, unfortunately. We should likely open an issue in Babel.

**Comment by locks** [comment]
I'm closing the issue based on the last message from pzuraq.
