### ISSUE TITLE
Pass instance to Application ready() hook

### ISSUE THREAD

**Issue by mehulkar** [emberjs/ember.js#18470]
Opening up for discussion, feel free to move to RFC repo.

I would like to boot my app at a specific URL. I am trying to achieve this by:

1. During an application initializer, set an `initialURL` on the `Application` instance.
  - I have to do this an an `initializer`, rather than an instance initializer, because I get this url from an event listener, so I need to be able to `deferReadiness` and `advanceReadiness`. 
1. In the `ready` hook, access `this.initialURL` and then use the `ApplicationInstance` to lookup the `router:main`  and set `initialURL`. 

This means that when the `ready()` hook finishes, and the `startRouting()` is called, Ember will read this `initialURL` and boot to that.

The only missing piece is having access to the `ApplicationInstance` object in the `ready` hook so that I can access `router:main`.

If there's a better way of achieving this, I'm open to that as well.

https://github.com/emberjs/ember.js/blob/998a47388c1c84f5e4492f5ae6e6ac14aaa7919c/packages/%40ember/application/lib/application.js#L804-L805

**Comment by chancancode** [comment]
Does the visit api not work for your use case?

**Comment by mehulkar** [comment]
I tried the visit API but couldn’t figure out where to call it. The way I tried it, It also didn’t prevent calling startRouting, so even though it worked, the app would then go back to /

**Comment by mehulkar** [comment]
I tried it in the ready() hook and also in instance initializer.

**Comment by mehulkar** [comment]
I should add, another reason I feel initialURL is appropriate because I need to track the initial URL of my app for instrumentation/metrics. That tracking happens in an initializer and if I could just read router.initialURL and it’s accurate for my case, it will be two birds with one stone.

**Comment by rwjblue** [comment]
In general, the way `initialURL` is set is an internal implementation detail and not something that an application should rely on. The `visit` API is _specifically_ intended for this purpose, and in fact you can see that the test harness used by most applications these days uses `.visit` directly:

https://github.com/emberjs/ember-test-helpers/blob/fdcf31ab04b908e4561eeea102fc07a6f483d640/addon-test-support/%40ember/test-helpers/setup-application-context.ts#L120

And that usage replaces the "legacy" `visit` helper ([see here](https://github.com/emberjs/ember.js/blob/016f8066d0b484f3f69ce8c337be3b8b8aa5fce4/packages/ember-testing/lib/helpers/visit.js#L33-L39)) which `initialURL` was created to support ([see here](https://github.com/emberjs/ember.js/commit/08d21307c2a37d21fca466ad2991398c1c42e12b)).

**Comment by mehulkar** [comment]
Closing this down as the `visit` seems to bet he right approach. Will file issues related to that API if I come across them. Thanks!
