### ISSUE TITLE
Potential regression with Ember.get

### ISSUE THREAD

**Issue by nlfurniss** [emberjs/ember.js#18528]
Starting somewhere after Ember > 3.1.4, this use of `Ember.get` started to work:

```
let data = {
  a: {
    'b.c.d': 13
  }
};

Ember.get(data.a, 'b.c.d'); // 13
```

[Example twiddle
](https://ember-twiddle.com/1ba02ef78ccba974edfe4dc1cef37560?openFiles=controllers.application.js%2C) (open the console and change the version of ember to observe this not working, then working)

Sometime after 3.4.8 it stopped working. Was this intended behavior that regressed, or was it never intended to work?

**Comment by pzuraq** [comment]
I've traced this and can see the change that introduced the functionality and the change that removed it. Based on those changes, I don't think this was intended (no tests or documentation were ever added to guarantee that this behavior would work), and given the nature of `get` I think this would be pretty confusing in general so I'm going to say it probably wasn't expected.

**Comment by nlfurniss** [comment]
@pzuraq mind sharing the PRs that added and removed this? Also, I'm not sure that a lack of tests indicates that its not intended :-P

**Comment by pzuraq** [comment]
The commit that introduced the behavior is [here](https://github.com/emberjs/ember.js/commit/a9ef6718bb341f9be9ccf0d34a055ce8d0a55250). We've generally been pretty good about adding tests for new behavior in recent years, so I think this was unintentional.
