### ISSUE TITLE
Errors during model hooks should emit to Ember.onerror

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#18533]
Currently, when a model hook rejects we bubble up the route hierarchy looking for any route that implements an `error` action. If we get to the top (above application route) we have some default behavior for the `error` action:

https://github.com/emberjs/ember.js/blob/1b0c903edb25c5cd11cb2cde4f58be5b74d98220/packages/@ember/-internals/routing/lib/system/router.ts#L1232-L1263

Which invokes `logError`, defined here:

https://github.com/emberjs/ember.js/blob/1b0c903edb25c5cd11cb2cde4f58be5b74d98220/packages/@ember/-internals/routing/lib/system/router.ts#L1296-L1323

As you can see, `logError` is a small layer on top of `console.error`. Unfortunately, this means that any errors during model hooks will not be sent to `Ember.onerror` (unless you also implement `error` on your application route).

We should fix this by checking if there is an `Ember.onerror` and invoking it with the error, falling back to `logError`.

**Comment by xg-wang** [comment]
The final error handling after `logError` is at L1610 promise chain. There if the error is not "handled" by any
- route `error` actions
- `<route>.error` state
- `<route>-error` substate
It is part of RSVP Promise rejection, which goes into `Ember.onerror`. The wrapper around `console.error` always executes.

https://github.com/emberjs/ember.js/blob/1b0c903edb25c5cd11cb2cde4f58be5b74d98220/packages/@ember/-internals/routing/lib/system/router.ts#L1601-L1616

@rwjblue are you suggesting the error should be thrown in the case that it's handled, but the action that handled the error specified to bubble it up?

**Comment by houfeng0923** [comment]
hi @rwjblue , i have other question about onerror: 

when use async and catch a reject promise(rsvp, not native), always an error in console.
unless i use native promise instead . 

https://ember-twiddle.com/8c7e71eeab8de3ca2a48345bc1058eb9?openFiles=routes.application%5C.js%2C

in ember, if rsvp Promise has no catch handler, it look has a default handler in development ? i have to use `Ember.onerror` to suppress it .

**Comment by rwjblue** [comment]
@houfeng0923 - https://github.com/emberjs/ember-qunit/issues/592 is a discussion about using native promises for these kinds of things

**Comment by Turbo87** [comment]
@rwjblue was the original issue resolved? I might be doing something wrong, but I'm still seeing the error in the logs of my test suite 🤔
