### ISSUE TITLE
Helpers prefixed with `this.` should not work, but do

### ISSUE THREAD

**Issue by kategengler** [emberjs/ember.js#18532]
I had a few helpers erroneously prefixed with `this.` due to a bug in a codemod. I missed fixing a few, because tests passed.
```hbs
Plain `or`: {{or true false}} -> true
`this.or`: {{this.or true false}} -> 
As attribute: <button disabled={{this.or true false}}>Click here</button> -> the button is disabled
<FooBar @thingy={{this.or true false}} /> -> the argument @thingy is true
```

This happens with other helpers as well, not only `or`

Reproduction: https://glitch.com/edit/#!/ember-cli-ember-new-output-1

**Comment by rwjblue** [comment]
Ugh. I forgot about this 🤦

**Comment by rwjblue** [comment]
This no longer works in 3.18+.
