### ISSUE TITLE
Issue with each-in helper not looping over data when the parent JSON key has a . (full-stop) in it

### ISSUE THREAD

**Issue by danr1979** [emberjs/ember.js#18552]
Hi.

We are using Ember 3.12.0 on one of our production applications and we noticed that one of our reports had some missing rows in it.  The missing data was present in the JSON response we were getting back from our API but was not being displayed in our template.  The template used the each-in helper to loop over the data.

I have created a gist based on an Ember Twiddle that I did that demonstrates the each-in helper failing.  You can find it here:

https://gist.github.com/danr1979/569864e31118b89964d8664cb2d6f324

You can see that the "testData" object property has names in groups.  Please note the group named "Group No. 1" as this is the group whose data (John, James, Joe and Jack) does not display correctly when the each-in helper tries to process it.  If I remove the full-stop (.) from the group name so it reads "Group No 1" the names in that group are correctly displayed by the each-in helper.

When I originally ran this example in Ember Twiddle it worked correctly even with the full-stop present in the group, but this was using version 3.4.3 of Ember.  As mentioned above our production application uses version 3.12.0 and the example does not work in that so the issue has been introduced sometime between version 3.4.3 and 3.12.0.

I hope this is enough information to be useful.

Thanks.

**Comment by pzuraq** [comment]
I believe this has been fixed on master, the fix should probably be backported.

**Comment by locks** [comment]
Closing as resolved.
