### ISSUE TITLE
Broken links for v.3.14.0 starter guides

### ISSUE THREAD

**Issue by theasteve** [emberjs/ember.js#18560]
I'm currently going over the Quick Start guided lines. When I start the server via `ember serve` the index page is shown with a couple of links.

<img width="1411" alt="Screen Shot 2019-11-18 at 4 56 18 PM" src="https://user-images.githubusercontent.com/14843767/69097370-6e121280-0a24-11ea-9650-f0882b222d2c.png">

When I click on the `Quick Start` link, which is 
`https://guides.emberjs.com/v3.14.0/getting-started/quick-start/` I get a `Page Not Found` error. but when I change the version in the URL to 13 it works.

**Ember version:**
ember-cli: 3.14.0
node: 12.12.0
os: darwin x64

Mac OS Mojave
v10.14.4

**Comment by Alonski** [comment]
This can be closed. @jenweber swooped in to save the day!

**Comment by jenweber** [comment]
Thank you for reporting! The issue was that we had not released the 3.14 guides, but they are now live on guides.emberjs.com. Sorry for the delay!
