### ISSUE TITLE
Possible dead code (or missing tests)

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#18578]
While reviewing the coverage statistics (to see if I've missed anything in #18572), I noticed that the following functions/branches are not covered by our current tests. We should double check if we are either missing a test or if the code is actually "dead code".

* `packages/loader/lib/index.js#L11-L17` and L37 - Should be wrapped in `DEBUG` guard's
* Looks like we are not testing the deprecations in `packages/@ember/-internals/console/index`
* `packages/@ember/-internals/container`
  * `isFactoryClass`
  * using the fallback registry with `Registry.prototype.getOptionsForType`
  * `Registry.prototype.getOptions`
* `_getObjectsOnNamespaces` in `@ember/-internals/extension-support/lib/container_debug_adapter` 
* `@ember/-internals/glimmer`
  * `ConditionalReference.prototype.toBool` when `isProxy(predicate)` returns true
  * `valueToRef` when the value is a function
  * `valueKeyToRef`
  * `ObjectIterator.fromIndexable` when the object is not empty and `isTracking` is true
  * `EachInIterable.prototype.iterate` when `hasForEach(iterable)` returns true (also `ObjectIterator.fromForEachable`)
  * `EachInIterable.prototype.keyFor` when `keyPath` is anything other than `@key` or `@identity`
  * `EachIterable.prototype.iterate` when `isNativeIterable` is true
  * `EachIterable.prototype.iterate` when `hasForEach(iterable)` is true
  * `Unique` returned function, when `seen` collisions occur
  * `escapeExpression`
  * `htmlSafe` when the argument is _not_ a string (e.g. it is an object with a toString method)
  * `ComponentStateBucket.prototype.destroy` when `environment.isInteractive` is true (this is somewhat surprising, should dig more)
  * `wrapComponentClassAttribute` when the `hash.values` for `class` attribute is either an `Ops.Get` or `Ops.MaybeLocal` (did we remove this due to refactors in glimmer-vm?)
  * `AttributeBinding.install` when `attribute` is `id`
  * `CurlyComponentManager.prototype.getLayout`
  * Adding or removing a root during `Renderer.prototype._renderRoots`
  * Using a custom modifier with `capabilities.disableAutoTracking === true`
  * `PathReference` class in `outlet.ts`
  * Adding a macro via `experimentalMacros`
  * `RuntimeResolver`
    * `_parseNameForNamespace`
    * `_lookupModifier` where `builtin` is undefined
  * `OutletView.extend` & `OutletView.reopenclass` - Do we actually support folks reaching in and extending this?
* `@ember/-internals/metal`
  * `revalidateObservers` when `ASYNC_OBSERVERS.has(target)`
  * `markTagAsConsumed` when `_tag.subtag` is truthy
  * `Tracker.prototype.combine` when `this.tags.size === 0`
  * `descriptorForField`'s returned setter when `propertyDidChange !== null`
  * `objectAt` when the passed in array has a custom `objectAt` method
  * `replace` when the passed in array has a custom `replace` method
  * `replaceInNativeArray` when the number of items to insert is > 60000 (`CHUNK_SIZE`)
  * `finishLazyChains` where the value is `null` or non-object non-function
  * `getChainTagsForKey` when using `@each.foo.bar`, should be testing deprecation
  * `getPossibleMandatoryProxyValue` when `obj[PROXY_CONTENT]` is not `undefined
  * `ComputedProperty.prototype.setWithSuspend`
  * `ComputedProperty.prototype._getter`
  * `AliasDecoratorImpl.prototype.meta`
  * `getProperties` when passing an array as the second argument (e.g. `getProperties(obj, ['some', 'other','props'])`
  * `willMergeMixins` support
  * `Mixin.applyPartial`
* `@ember/-internals/routing`
  * `lib/location/history_location` when `<base>` is used
  * `addQueryParamsObservers` when `lookupDescriptor` finds a descriptor (where we auto wrap with dependentKeyCompat)
  * `PrivateRouter.prototype.triggerWillChangeContext` and `PrivateRouter.prototype._triggerWillLeave`
  * `EmberRouter.prototype._setupLocation` when the `resolveLocation === undefined`
  * `representEmptyRoute` when `alreadyAppended` is true
  * `prefixRouteNameArg` where `owner.router` is truthy
  * `copy` where `obj` is an array and `deep` is set (this is deprecated, probably not a ton of value adding more tests now?)
* `@ember/-internals/runtime`
  * accessing or setting `.[]` on `ArrayMixin`
  * invoking `removeArrayObserver` on `ArrayMixin`
  * `.popObject`, `.reverseObjects` when no items remain (`ArrayMixin`)
  * `ArrayMixin.addObjects`
  * `lib/mixins/observable`
    * `beginPropertyChanges`
    * `endPropertyChanges`
  * `lib/system/core_object`
    * `initialize` merging `concatenatedProperties` when there is not an initial `baseValue`
    * `willReopen` when `wasApplied.has(p)`
    * `detect` when `obj` is not a function
    * `flattenProps` with `concatenatedProperties` or `mergedProperties`
  * `FrameworkObject`
* `@ember/-internals/utils`
  * `guidFor` with a native symbol
  * `getFunctionName` when `fn.name` is undefined
  * `setListeners` when the `listeners` argument is truthy
  * `Cache.prototype.purge`
  * `setupMandatorySetter` when `!desc.configurable || !desc.writable`
  * `setupMandatorySetter` where the original descriptor had a `get`
  * `teardownMandatorySetter` where there was a previous setter for the given property
  * `setWithMandatorySetter` when there was an original setter for the property
* `@ember/-internals/views`
  * `component_lookup` module
  * `ChildViewsSupport` `appendChild`
  * `lib/mixins/view_support`
    * `nearestOfType`
    * `nearestWithProperty`
  * `lib/system/action_manager`
  * `lib/system/utils` `getViewId` when `view.elementId` is present
* `@ember/debug`
  * `deprecateFunc` is not tested
* `@ember/object`
  * `lib/computed/computed_macros` -> `none`
  * `lib/computed/reduced_computed_macros` -> `setDiff` when `setA` and `setB` are not arrays
* `backburner`
  * `throttle`

**Comment by Nelias** [comment]
This issue should be closed already ^

**Comment by locks** [comment]
Much as changed! This list should be done anew if someone is looking to track down further dead code.
