### ISSUE TITLE
The ember-source@3.12.1 published module is broken

### ISSUE THREAD

**Issue by kanongil** [emberjs/ember.js#18575]
The published `dist/legacy/ember.*.js` uses `const`, which carries over to the ember-cli built `vendor.js` and causes it to break on eg. iOS 9.3.5 devices.

It seems that this is a babel issue in the `ember-source` publication process. A number of lines containing `const data = _taggedTemplateLiteralLoose(…);` is left in the files.
It seems that babel fails to properly apply `const => var` for tagged template literals.

I have not checked older versions than 3.12.1. For 3.13+ it works again due to a revised build process.

**Comment by kanongil** [comment]
I check the published packages, and this issue seems to have been introduced with `ember-source@3.8.2`. The `ember-source@3.8.1` package does not contain `const` expressions.

**Comment by kanongil** [comment]
Seems that this was introduced with #17859.

**Comment by rwjblue** [comment]
Fixed by #18576 and being released as v3.12.2 (currently pending CI for publishing).
