### ISSUE TITLE
Helper does not recompute on array content change

### ISSUE THREAD

**Issue by mukilane** [emberjs/ember.js#18588]
The [Ember.Helper](https://api.emberjs.com/ember/3.11/classes/Helper) does not recompute when any changes occur in EmberArray (pushObject, removeObject, etc). Changes are only triggered when explicitly calling `notifyPropertyChange` in the component.

Is this the expected behavior ?

Twiddle explaining the issue : https://ember-twiddle.com/b09f95f8ac305cd9aee8d503879059d4?openFiles=templates.application.hbs%2C

**Comment by pzuraq** [comment]
This was the expected before up until Ember 3.12. In 3.13+, changes to arrays should be autotracked, so you should see updates. If you’re on a higher version of Ember and you aren’t, this may be a bug.

**Comment by mukilane** [comment]
> This was the expected before up until Ember 3.12. In 3.13+, changes to arrays should be autotracked, so you should see updates. If you’re on a higher version of Ember and you aren’t, this may be a bug.

I've only tested in 3.8.
Closing it for now then.
