### ISSUE TITLE
Increased asset size from `-assert-implicit-component-helper-argument`

### ISSUE THREAD

**Issue by chriskrycho** [emberjs/ember.js#18598]
Unconditionally including the `-assert-implicit-component-helper-argument` (added in #17135) in builds can lead to significant increases in code size, especially in large apps with lots of components. Also related: #17251.

Given that Ember can now do different *template* builds for prod and dev, it would be great if we could pull this assertion back out of prod builds!

**Comment by rwjblue** [comment]
Thanks for reporting! @chancancode and I have discussed this a few times, we definitely need to fix it.

Now that we are a "real addon", we can actually do the same thing most other addons do RE: template compilation transforms.

**Comment by nlfurniss** [comment]
> Thanks for reporting! @chancancode and I have discussed this a few times, we definitely need to fix it.
> 
> Now that we are a "real addon", we can actually do the same thing most other addons do RE: template compilation transforms.

Any examples of how this is done? If this doesn’t require a Rob Jackson or Godfrey level of knowledge I can take a look at it.

**Comment by chriskrycho** [comment]
@rwjblue @krisselden did the recent fixes around templates include this?

**Comment by rwjblue** [comment]
@chriskrycho - No, those comparisons are from 3.16 to 3.17 (but 3.16 already included this growth).

**Comment by chriskrycho** [comment]
Ah, okay. For our app's sake, we'd still be happy to dig into it if we can steal a tiny bit of your mentoring time sometime Soon™! (It could help us mitigate the other 3.16→3.20 costs as well, even as you're all working on tackling those.)

**Comment by rwjblue** [comment]
Ya, I'd love the help (even if just to force "The Plan" into writing). Let's set up a deep dive session to chat through it when you have time...
