### ISSUE TITLE
Imported $ is not the same as window.$

### ISSUE THREAD

**Issue by btecu** [emberjs/ember.js#18591]
I have an addon that creates a modal using Bootstrap 3 JS which relies on jQuery.
While updating Ember to 3.14.x I changed from `this.$('.modal').modal()` to `$('.modal', this.element).modal()` to address the deprecation introduced in https://deprecations.emberjs.com/v3.x#toc_jquery-apis.

However, the `.modal()` is always undefined. After more investigation, I noticed that `$('.modal').modal()` also doesn't work.

It turns out `window.$` / `window.jQuery` is different than `import $ from 'jquery';` in Ember.

So, `this.$('.modal')` and `window.$('.modal')` works, but `$(this.element)` or `$('.modal')` does not work.

If it matters, in `config/optional-features.json` I do have 
```
{
  "jquery-integration": true
}
```

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. It seems outdated and likely no longer relevant.

By closing some old issues we reduce the list of open issues to a more manageable set. Let me know if you think this is a mistake and that the issue should stay open.
