### ISSUE TITLE
[DX] Improve user feedback around improper native class CP use

### ISSUE THREAD

**Issue by mike-north** [emberjs/ember.js#18604]
Although something like

```js
import { computed } from '@ember/object';

const fullName = computed('nameParts', function () {
   return [this.nameParts.first, this.nameParts.middle, this.nameParts.last].join(' ');
});
```
remains a totally valid way to create a computed property macro, the following would not be valid

```js
import Component from '@ember/component';

class XFoo extends Component {
   person = {
       first: 'Tom',
       middle: 'Danger',
       last: 'Sterr'
   }
   
   // not valid
    fullName1 = fullName('person')

   // not valid
    fullName2 = computed('person', function () { ... })
}
```

the mode of failure for the above invalid use is less than actionable

<img width="1178" alt="Screen Shot 2019-12-09 at 4 20 49 PM" src="https://user-images.githubusercontent.com/558005/70486543-1ad13400-1aa7-11ea-9dcd-43adf515cfe4.png">

Given that a significant part of our community may be new to ES6 classes, and that the difference between

```js
const Foo = Ember.Component.extend({
    fullName2: computed('person', function () { ... })
});
```
and

```js
class Foo extends Component {
   fullName2 = computed('person', function () { ... })
}
```
is subtle, we should explore what can be done to improve the mode of failure here.

Confusion between class fields and "properties of the arg passed to `.extend()`" is perhaps the most common sticking point I've seen as people make adjustments to their Ember mental model" for Octane.   

----

From informal discussion w/ @pzuraq 

- Feedback via lint may be an option
- Ultimately this is coming from `ComputedProperty.prototype.toString()`. Maybe this can be overridden? Maybe as an opt-in of there are concerns around breaking changes?

**Comment by locks** [comment]
Closing as stale. The framework has moved to tracked properties and getter since this issue was originally filed. Thanks for the detailed report!
