### ISSUE TITLE
Dependent keys with large objects after Ember 3.12

### ISSUE THREAD

**Issue by thec0keman** [emberjs/ember.js#18609]
We recently updated an app from 3.12 to 3.14, and this introduced a regression when observing dependent keys with `@each`.  However, this only happens with very large data sets.

For example, with a property that returns 125k items:
```
@computed
get foo() {
  const results = [];

  for (let i = 0; i < 125000; i++) {
    results.push({ id: i, name: `foo${ i }` });
  }

  return results;
}
```

When passed into a component:
```
<FooBar @foo={{foo}}/>
```

And the component has a dependent key with `@each` on that property:
```
import Component from '@ember/component';
import { computed } from '@ember/object';

export default class FooBar extends Component {
  @computed('foo.@each.{id,name}') // Needs at least one key to trigger
  get keyFilteredFields() {
    return this.foo;
  }
}
```

And that property is accessed:
```
{{log keyFilteredFields.length}}
```

=>

```
Uncaught RangeError: Maximum call stack size exceeded
    at getChainTagsForKeys (index.js:2523)
    at ComputedProperty.get (index.js:3332)
    at FooBar.CPGETTER_FUNCTION [as keyFilteredFields] (index.js:1044)
    at getPossibleMandatoryProxyValue (index.js:1269)
    at get (index.js:1342)
    at index.js:490
    at track (index.js:1224)
    at RootPropertyReference.compute (index.js:489)
    at RootPropertyReference.value (index.js:376)
    at NestedPropertyReference.compute (index.js:537)
```

Seems possibly related to [this](https://github.com/emberjs/ember.js/pull/17835)?

**Comment by pzuraq** [comment]
There have been a few bugfixes that landed fixing cases of infinite recursion, I'm not sure if those landed on 3.14 or 3.15. Can you reproduce with 3.15 as well?

**Comment by thec0keman** [comment]
Same issue happens on 3.15 and 3.16-beta.1

**Comment by pzuraq** [comment]
Thank you for verifying! I'll try to get on this asap

**Comment by locks** [comment]
Closing as no longer relevant. If you're running into this problem, please let us know to reopen!
