### ISSUE TITLE
[BUG] during a rerender, undefined this.args throws confusing error

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/ember.js#18617]
Possibly related to #18606 

Using `{{this.args.myArgument}}` instead of `{{@myArgument}}` when myArgument is undefined will throw a confusing error message upon rerendering a glimmer component:

```
Uncaught (in promise) Error: Assertion Failed: args proxies do not have real property descriptors, so you should never need to call getOwnPropertyDescriptor yourself. This code exists for enumerability, such as in for-in loops and Object.keys()
```

Reproduction:
https://github.com/Gaurav0/repro_confusing_error

**Comment by Gaurav0** [comment]
While this seems contrived, it is a simplified testcase. I've run into this with the menu component I'm developing in [ember-glue](https://github.com/gaurav0/ember-glue).

**Comment by rwjblue** [comment]
Ya, I'm pretty sure that this is the same underlying issue as #18606. We should definitely fix.

Also, just FYI, there is an `ember-template-lint` rule named [no-args-paths](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-args-paths.md) that will flag usage like `{{this.args.foo}}` (but not passing `this.args` out to another helper/component).

**Comment by pzuraq** [comment]
This should be fixed on the latest Ember release, thanks for the report! Let us know if it is not.
