### ISSUE TITLE
Question about how ember is bundled

### ISSUE THREAD

**Issue by lstrzebinczyk** [emberjs/ember.js#18611]
Hi

I absolutely love the work on Octane and how glimmer components + tracked are evolving the ergonomics of what I do in my application. I did notice something interesting, I took the snapshot of my bundle using https://github.com/kaliber5/ember-cli-bundle-analyzer, and I received this:

![Broccoli Concat Analyser](https://user-images.githubusercontent.com/1272828/70736993-db5a5000-1d11-11ea-9bf5-b5aaddcd1a6b.png)

It looks a little worrying to me. Does this mean by using `@glimmer/component` and `@glimmer/tracking` I'm doubling the amount of framework code I'm sending over the wire?

**Comment by pzuraq** [comment]
I'm not sure what's going wrong with the bundle analyzer, but Glimmer components don't include a second version of Ember. I think that just be a more detailed breakdown of Ember.js itself _within_ vendor.

**Comment by lstrzebinczyk** [comment]
@pzuraq I took a more detailed look on what actually is being built by my app currently (with glimmer) and some time ago when there was no glimmer, and there doesn't seem to be that large increase. 
Must be that bundle analyzer is creating confusing output.
Thank you for answering, I'm closing the issue.
