### ISSUE TITLE
[BUG] Issue ussing macros like sum and max over array of records

### ISSUE THREAD

**Issue by Subaku** [emberjs/ember.js#18618]
Sorry for crummy title. 

First the bug then my setup. I'm getting this deprecation:
```
Ember Inspector (Deprecation Trace): When using @each in a dependent-key or an 
observer, you can only chain one property level deep after the @each. That is, 
`locationAssets.@each.value` is allowed but `locationAssets.@each.value.[]` (which is 
what you passed) is not.
```

However, here are my properties:

```
@readOnly('assetLocationsTask.value') assetLocations;
@mapBy('assetLocations', 'asset') locationAssets;
@sum('locationAssets.@each.value') totalAssetValue;
```

So no `locationAssets.@each.value.[]` anywhere. The result by the way of the sum is always zero here. When I swap out for the max computed I get `Infinity`.

As you might surmise by the name `assetLocationsTask` is a TaskInstance from Ember-Concurrency and its value is an array of Ember-Data records. Each AssetLocation has a `belongsTo` to Asset which has the property `value`.

My current workaround that works is to define an explicit computed like so:
```
@computed('locationAssets.[]')
get totalAssetValue() {
  return this.locationAssets.reduce((total, asset) => { 
    return total + asset.get('value'); 
  }, 0)
}
```

Let me know if you need any more info.

Ember-Source: 3.14.1
Ember-Data: 3.14.0

**Comment by pzuraq** [comment]
The API for `sum` is it receives an array of values, and sums them: https://api.emberjs.com/ember/3.15/functions/@ember%2Fobject%2Fcomputed/sum

I believe the invocation should be 

```js
@readOnly('assetLocationsTask.value') assetLocations;
@mapBy('assetLocations', 'asset') locationAssets;
@sum('locationAssets') totalAssetValue;
```

**Comment by Subaku** [comment]
Ahh gotcha. Tricky. That does work for me thanks!
