### ISSUE TITLE
Ember 3.15 - Helper test always imports hbs from htmlbars-inline-precompile

### ISSUE THREAD

**Issue by ijlee2** [emberjs/ember.js#18626]
## Description

The blueprint for a helper test hardcoded the `hbs` import statement.

```javascript
import hbs from 'htmlbars-inline-precompile';
```

https://github.com/emberjs/ember.js/blob/master/blueprints/helper-test/qunit-rfc-232-files/__root__/__testType__/__collection__/__name__-test.js#L4

For Ember 3.15, which uses `ember-cli-htmlbars ^4.2.0`, I believe the blueprint would need to generate the line:

```javascript
import { hbs } from 'ember-cli-htmlbars';
```

https://github.com/ember-cli/ember-cli-htmlbars#tagged-template-usage--migrating-from-htmlbars-inline-precompile

## Proposed Solution

The blueprint for a component test shows how we can check the version of `ember-cli-htmlbars` in order to dynamically add the import statement:

https://github.com/emberjs/ember.js/blob/master/blueprints/component-test/index.js#L89-L97

https://github.com/emberjs/ember.js/blob/master/blueprints/component-test/qunit-rfc-232-files/__root__/__testType__/__path__/__test__.js#L4

Please check both QUnit and Mocha.

**Comment by rwjblue** [comment]
Yep, we should definitely fix! Thanks for reporting!
