### ISSUE TITLE
Changed source code not applied after ember build

### ISSUE THREAD

**Issue by broccoliInDB** [emberjs/ember.js#18631]
First of all, sorry for not given information for reproduction on this issue.

It happened to me on 12/23. and it still goes on.

ember-cli : 3.10.1
ember-framework: 3.10.2

I guess it happened as some build-relative addon's have been upgraded which has been done between 12/9~12/23. 

Let me say what I've experienced. I upgrade every 2weeks for our ember app.

and somehow dependent-addon is not applied properly. It looks I guess something old but not error. just not shown expected page but shown some old, not applied, page.

but the funny thing is when I looked that host's node_module to find out whether or not, it downloaded wrong addon. It has correct modified source code and downloaded correct addon. further more when I changed the sourcecode from the addon on node_modules. the watcher notified the change and show the detaction on terminal. but not applied on the browser.

but somehow it just fixed. i did not do anything just did this things over and over below.
-----------------------------
local server down
yarn cache clean
rm yarn.lock
yarn install
ember s
-----------------------------

It happened once on development environment as I said but not now..I cannot reproduce.

But It now happens on production-like environment as well.

but for now, If I change build option exactly same as development,
such as 
-------------------------------------------
sourcemaps {enabled : true}
fingerprint {enabled : false}
minifyjs {enabled : false}
minifycss {enabled : false}
ember-cli-uglify {enabled : false}
-------------------------------------------
then it works and applied.

any Ideas??
or
anyone who experienced the same thing?

Now I'm trying to find the upgraded-addon during those period to find out that it would be done well, if I change
the version back.

If anyone can give me any clue to solve this issue, please help me out~

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. It seems outdated and likely no longer relevant.

By closing some old issues we reduce the list of open issues to a more manageable set. Let me know if you think this is a mistake and that the issue should stay open.
