### ISSUE TITLE
3.15 breaks with no error if missing app/ file in addon

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/ember.js#18639]
ember-cli: 3.15.1
node: 10.15.0
os: darwin x64

To reproduce:
```
ember addon test-addon
cd test-addon
ember g component my-component

... in dummy app, use <MyComponent/>

rm app/components/my-component.js
ember s
```
No errors are shown. HTML is served, but the body has no content in it. Ember Inspector says this is not an Ember application.

Expected an error somewhere saying that the component couldn't be found.

**Comment by rwjblue** [comment]
Hmm, sorry about the delays here. Is this still an issue?

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. It seems outdated and likely no longer relevant.

By closing some old issues we reduce the list of open issues to a more manageable set. Let me know if you think this is a mistake and that the issue should stay open.
