### ISSUE TITLE
Text input helper not updating bound property on user input

### ISSUE THREAD

**Issue by Subaku** [emberjs/ember.js#18647]
`<Input @value={{this.textFilterInput}}>`

According to the API docs this should work. 
```
<Input @value={{this.searchWord}}>
"In this example, the initial value in the <input> will be set to the value of this.searchWord. If the user changes the text, the value of this.searchWord will also be updated."
```

But when I type in the input field no update occurs. Given past issues all over the internet it would seem the humble text input has been the cause of much confusion and unrest. Am I misreading how the input should work?

**Comment by pzuraq** [comment]
This should work. I've recreated this example in a [Glitch sandbox](https://glitch.com/edit/#!/deluxe-balmoral?path=app/templates/application.hbs:1:1) and it does appear to be working. Can you provide a reproduction of the issue you're experiencing, to help us debug it?

**Comment by Subaku** [comment]
Ah, testing it out further it appears my issue is being caused by another issue I'm currently debugging with a modal dialog eating events for some reason. Sorry for this. It does work as expected!

Thanks :)
