### ISSUE TITLE
Bug with co-location and inheriting components

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#18653]
[Here is a reproduction](https://github.com/boris-petrov/ember-co-location-bug).

Run `ember server` and open the page. You'll see:

```
Assertion Failed: Cannot call `setComponentTemplate` multiple times on the same class (`class extends _component.default {}`)
```

You can see component `a` has an `hbs` file and component `b` inherits from `a` and also has an `hbs` file. This doesn't work with co-location for some reason. I think this is a bug.

**Comment by chancancode** [comment]
This is expected behavior, you would have to do extend the class in b.js instead of just re-exporting it. The template is tied to the class, and since they are literally the same class, the templates would have been overwritten if not for the assertion.

**Comment by boris-petrov** [comment]
I see, thank you for the support!
