### ISSUE TITLE
Cannot read property 'outlets' of undefined

### ISSUE THREAD

**Issue by lougreenwood** [emberjs/ember.js#18679]
Ember 3.15
Ember Data 3.15
Ember CLI 3.15

We're seeing the error `Cannot read property 'outlets' of undefined` in our sentry logs, stack track attached below.

After looking at the effected devices, it _seems_ to be limited to touch devices.

<img width="857" alt="Screenshot 2020-01-13 at 17 15 53" src="https://user-images.githubusercontent.com/12051736/72276736-8ec3a680-3628-11ea-9bef-9ecaf6c481ff.png">

**Comment by locks** [comment]
Can you supply a reproduction?

**Comment by rwjblue** [comment]
I don't think we will be able to debug this without a repro. I'm going to close this for now, but I'm super keen to actually fix if we can figure out how to reproduce.

**Comment by lougreenwood** [comment]
We found a solution, it seems that it was an issue in our codebase where we were not awaiting on an `async` method in an `afterModel` which performed a redirect incase any intrepid explorer stumbles upon this in future.

**Comment by Samsinite** [comment]
@rwjblue Running into this on the latest 3.16 LTS when transitioning to a different on load in a setupController routine. Sounds similar to the other issue, is this expected behavior?

**Comment by Samsinite** [comment]
Anyone else running into this, was able to work around it by throwing the transition into the next runloop.

**Comment by kurkowski** [comment]
Is "defaultParentState" ever actually initialized? It's declared in the "_setOutlets" function [here](https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/routing/lib/system/router.ts#L450), and then passed into the "representEmptyRoute" function [here ](https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/routing/lib/system/router.ts#L1712). My IDE specifically says it might not have been initialized too.

Right before the usage of `defaultParentState`, if you do something like: `defaultParentState = { outlets: {}, render: { name: 'foo', outlet: 'bar' } };`, the error goes away.

So is this code path still valid? If not, it should be deleted. If so, the `defaultParentState` object needs to be initialized to something.
