### ISSUE TITLE
Route::Render method can't render components directly

### ISSUE THREAD

**Issue by abhishek97** [emberjs/ember.js#18677]
Docs state that you can use `this.render` to render into multiple outlets.
https://api.emberjs.com/ember/3.13/classes/Route/methods/render?anchor=render

However, when i try to use it got this error:

```
Could not find "XXXX" template, view, or component. Error: Assertion Failed: Could not find "XXXX" template, view, or component.
```

However, I found here: https://github.com/emberjs/ember.js/blob/822452c4432620fc67a777aba3b150098fd6812d/packages/%40ember/-internals/routing/lib/system/route.ts#L1870
that we only try lookup a template with the name. So effectively i can't use component name here (which was my intention).

We should update the error message or support component names. I'd say the latter.

How would i go about in the code, to support component names here too? Will this be sufficient?

```
let template = owner.lookup<TemplateFactory>(`component:${templateName}`);
```

**Comment by locks** [comment]
`Route#render` is deprecated by [RFC #418](https://emberjs.github.io/rfcs/0418-deprecate-route-render-methods.html), and I believe it did not support components on purpose.
I suggest reading the "Migration paths" portion of the RFC to get ideas how to update your application code. If you have further questions hop on Discord and we'll try to sort you out!

**Comment by abhishek97** [comment]
@locks Thanks for pointing out the RFC for me. However, I see that isn't merged into ember yet. The `in-element` mentioned in the RFC isn't available yet. So i see my only options right now is to rely on 
a plugin to polyfill this. Correct?
