### ISSUE TITLE
 BUG: attempted to update a tag with a tag that has a more recent revision as its value

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#18678]
In discussion with @pzuraq he explained the following error is an internal failure in Ember, and we should report occurrences of it from addon builds:

```
BUG: attempted to update a tag with a tag that has a more recent revision as its value
```

I see this in ember-table in the following build: https://travis-ci.org/Addepar/ember-table/jobs/636447971 The first test to fail is `Unit | Private | CollapseTree: can disable tree`.

**Comment by markcharyk** [comment]
I ran into this issue in a complicated project, and created [this](https://github.com/markcharyk/tag-with-a-tag-repro) rudimentary reproduction in the single solitary unit test.

**Comment by wagenet** [comment]
I'm seeing this is in my own complicated project as well. I will attempt to reproduce if time permits.

**Comment by wagenet** [comment]
I tried resolving @glimmer/validator to 0.47.0 and it did not resolve my issue.

**Comment by pzuraq** [comment]
The assertion shouldn't exist anymore in 0.47.0. Ember builds the glimmer packages prior to publish I believe, so it may be that simply resolving it won't actually update the code that is run.

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/18694 updates to include the fix linked above, and is cherry-picked into the beta branch. Once CI finishes publishing (approximately 20-30 min), new beta and canary test runs should avoid this issue.

**Comment by sandstrom** [comment]
Fixed in https://github.com/emberjs/ember.js/pull/18694
