### ISSUE TITLE
Should combination of {{#let (concat [component name]) as |ComponentName|}}{{/let}} work without using component helper

### ISSUE THREAD

**Issue by andrewfan** [emberjs/ember.js#18686]
Yesterday, I was asking @lifeart a question about https://github.com/lifeart/ember-ast-hot-load ability to work with Angle Brackets components and Octane.
And when I sent him a code snippet with code that did not hotload correctly I noticed that I forgot to use `component` helper in the combination with `let`. I did not receive any errors, so I tried to do the same in the freshly generated app, and both versions worked.

So my question is: is this a bug that first version works or is it intended behavior? 

```
{{!-- Why does this code work? --}}
{{#let (concat "button-component") as |Button|}}
  <Button>
    Click me
  </Button>
{{/let}}

{{#let (component (concat "button-component")) as |Button|}}
  <Button>
    Click me
  </Button>
{{/let}}
```
P.S In my real code, I used `concat` to build a component name in the runtime, in the example, I just simplified the code.

**Comment by lifeart** [comment]
looks related to https://github.com/emberjs/ember.js/issues/17744

**Comment by rwjblue** [comment]
Now that we have updated to the latest version of glimmer-vm here we should see if this still happens.

**Comment by locks** [comment]
It is happening in 3.17.

**Comment by rwjblue** [comment]
Ya, this is definitely not good. We should **not** be rendering a component without the `(component` helper here.

**Comment by rwjblue** [comment]
I'm going to close in favor of https://github.com/emberjs/ember.js/issues/17744 which has more info.
