### ISSUE TITLE
@tracked initializer does not have access to `this`

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#18690]
This started failing on canary since the Glimmer VM upgrade. The problem appears to be this line:

https://github.com/glimmerjs/glimmer-vm/blob/master/packages/@glimmer/validator/lib/tracking.ts#L118

This should probably be `initializer.call(self)`, or maybe the whoever made the initializer should have made it an arrow function closure. Either way, the result is that if you have something like `@tracked foo = this.bar`, it doesn't work anymore.

**Comment by chancancode** [comment]
![initializer](https://user-images.githubusercontent.com/55829/72656033-88e20400-394d-11ea-8e1f-3f26d3c1348b.gif)

**Comment by pzuraq** [comment]
That solution appears correct. Currently in the middle of debugging #18678 so if you have time to PR the fix that'd be helpful, if not I can add it to the backlog.

**Comment by chancancode** [comment]
I'm on vacation this week so probably won't be able to work on it! Sorry!

**Comment by wagenet** [comment]
I just ran into this issue as well. It's possible that I may be able to PR if no one else gets to it first.
