### ISSUE TITLE
[3.13+] ObjectProxy not rerendering

### ISSUE THREAD

**Issue by pzuraq** [emberjs/ember.js#18704]
Original report:

We're experienceing an almost identical issue when bumping an app from 3.12 to 3.13.

We have a utility function which returns a CP which returns an ObjectProxy which proxies the object passed to the utility (e.g. myUtil('model')). We've been using this primarily to store updates to form values locally.
```js
let myUtil = function (contentKey) {
  return computed(
    contentKey,
    function () {
      return MyProxyObject.create({ content: this.get(contentKey) });
    }
  );
}
```

We have a unit test (this is very abbreviated): 
```js
let foo = { bar: false };
let myController = Controller.extend({
  wrappedFoo: myUtil('foo'),
  computedBar: computed(
    'wrappedFoo.bar',
    function () { return this.get('wrappedFoo.bar'); }
  ),
  booledBar: bool('wrappedFoo.bar')
}).create({ foo });

assert.notOk(myController.get('aliasedBar'));
myController.set('wrappedFoo.bar', true);
assert.ok(myController.get('computedBar')); // was passing, now failing
assert.ok(myController.get('booledBar')); // was passing, now failing
```

cc @theroncross, [Original context](https://github.com/emberjs/ember.js/issues/18689#issuecomment-577294423)

I'm currently unable to reproduce this issue, with the following test case added to Ember directly:

```js
    '@test it should work when returned from a computed property'(assert) {
      function myUtil(contentKey) {
        return computed(contentKey, function() {
          return ObjectProxy.create({ content: this.get(contentKey) });
        });
      }

      let foo = { bar: false };
      let myController = EmberObject.extend({
        wrappedFoo: myUtil('foo'),
        computedBar: computed('wrappedFoo.bar', function() {
          return this.get('wrappedFoo.bar');
        }),
        booledBar: bool('wrappedFoo.bar'),
      }).create({ foo });

      assert.notOk(myController.get('aliasedBar'));
      myController.set('wrappedFoo.bar', true);
      assert.ok(myController.get('computedBar'));
      assert.ok(myController.get('booledBar'));
    }
```

**Comment by theroncross** [comment]
After further investigation, it looks like this may be an issue with the `setUnknownProperty` method. I've created a minimal reproduction that passes on 3.12 and fails on 3.13: https://github.com/theroncross/ember.js/tree/object-proxy-regression-at-3-13

The methods in question are in `{app,test/unit}/utils/`

**Comment by theroncross** [comment]
The above seems to now be reliably reproducing the problem by changing `ember-source` from `~3.12.0` to anything `~3.13.0`+.
