### ISSUE TITLE
Using the {{on}} helper in a <video> tag is clobbering the "controls" attribute

### ISSUE THREAD

**Issue by adc-mhaugen** [emberjs/ember.js#18712]
We recently upgraded our project to Ember 3.15.1 and a tagless component with a video tag root element is no longer showing the video controls (due to missing `controls` attribute):

```javascript
// component.js
import Component from '@ember/component';
import { action } from '@ember/object';

export default class TestVideo extends Component {
    tagName = '';

    @action
    doSomething() {
        window.console.log('done');
    }
}
```

```handlebars
// template.hbs
<video controls {{on 'canplay' this.doSomething once=true}}>
    <source src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" type="video/mp4" />
</video>
```

The `controls` attribute will not be present in the rendered output.  If I remove the `on` template helper it will be present again.  

A workaround suggested by [pzuraq](https://github.com/pzuraq) does work:

```handlebars
// template.hbs
<video controls={{true}} {{on 'canplay' this.doSomething once=true}}>
    <source src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" type="video/mp4" />
</video>
```

**Comment by locks** [comment]
Thank you for reporting! I'm closing this issue as the bug is being tracked at https://github.com/emberjs/ember.js/pull/18480.
