### ISSUE TITLE
Addon component blueprint generates invalid code

### ISSUE THREAD

**Issue by ef4** [emberjs/ember.js#18719]
1. Generate a new addon with ember-cli 3.15.2. 
2. In that addon run `ember g component --classic -cc foo`
3. Try to use that component, you'll see 

    > Error: Could not find module `example-addon/templates/components/foo` imported from `example-addon/components/foo`

The problem is that the generated hbs file is at `addon/components/foo.hbs`, but the layout import statement in `addon/components/foo.js` tries to import from `../templates/components/foo`.

I reproduced this bug on both ember-source 3.15 and 3.18.0-canary+f0fceae4. I was unable to reproduce while running `yarn link`ed to ember-source on either of those commits, which suggests there is some possibly-unrelated weirdness in the way the blueprints detect their environment when running symlinked.

**Comment by skaterdav85** [comment]
I ran into this too with the following:

```
ember-cli: 3.16.0
node: 13.8.0
v8: 7.9.317.25-node.28
uv: 1.34.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 79
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.4
openssl: 1.1.1d
cldr: 36.0
icu: 65.1
tz: 2019c
unicode: 12.1
os: darwin x64
6.13.6
1.21.1
```

Where should `layout` be imported from? If I do `ember g component modal -cc`, I will have the following:

```js
// addon/components/modal.js
import Component from '@ember/component';
import layout from '../templates/components/modal';

export default Component.extend({
  layout
});
```

I tried changing the import to the following but `undefined` is logged to the console.

```js
import Component from '@ember/component';
import layout from './modal';

console.log(layout); // undefined

export default Component.extend({
  layout
});
```

**Comment by locks** [comment]
Fixed.
