### ISSUE TITLE
I get an error in the browser console for my app on from the router.js file

### ISSUE THREAD

**Issue by vinodhrajamuralidharan** [emberjs/ember.js#18711]
The error I get is:  Error caught: Cannot use 'in' operator to search for 'start' in undefined

The file and the line is: https://github.com/emberjs/ember.js/blob/99e796a0ae52bc161b8541d0e481d27b7f21164c/packages/%40ember/-internals/routing/lib/system/router.ts#L1013
![Screenshot 2020-01-30 at 14 26 40](https://user-images.githubusercontent.com/8244992/73453555-8f6c7480-436c-11ea-981d-88f344ed8ab2.png)

**Comment by lvegerano** [comment]
Do you have any examples of code that is causing this? Or better yet a reproducible repo 😄

**Comment by vinodhrajamuralidharan** [comment]
I don't have an example code for this and the repo is actually a private one.  shall I share a video and error console expanded plus where the error happen?

**Comment by rwjblue** [comment]
This must be situation based on some condition in the app in question.

@vinodhrajamuralidharan - If you are still hitting this, I think the next steps would be to create a separate (public) repo and make it fail in the same way. The process of doing that will almost certainly shed some light on the specific circumstances that cause the issue, and it will help us debug / triage.

At the momemnt, this bug report isn't super actionable so I'm going to go ahead and close, but I'm super happy to reopen if you can provide us with that reproduction.
