### ISSUE TITLE
issues with setting up ember error substates

### ISSUE THREAD

**Issue by ahemed-haneen** [emberjs/ember.js#18731]
guys im trying to use ember error substates and im able to catch the error and console.log it. 
and from there two things happen

1. if i don't let the error bubble(no return true) all my route transitions don't work, that is , the console.logs in the models hooks do work but neither my template nor the urls change from then on.

2. if i let the error bubble and reroute to an error page, once the error page is rendered...exception is thrown and execution stops

any solutions? or ideas why this is happening?

**Comment by rwjblue** [comment]
This seems pretty surprising, can you make a small reproduction that we can poke at?

**Comment by locks** [comment]
Closed as stale. We can re-open if you provide a reproduction!
