### ISSUE TITLE
activeClass not working on <LinkTo/>

### ISSUE THREAD

**Issue by gvocale** [emberjs/ember.js#18734]
The following is not working on Ember 3.13
```
<LinkTo activeClass='is-active'/>
```
As opposed to:
```
{{link-to activeClass='is-active'}}
```

**Comment by btecu** [comment]
Have you tried `@activeClass="is-active"`?

**Comment by gvocale** [comment]
@btecu yep! It works! Sorry, my bad!

Thank you
