### ISSUE TITLE
Action decorator not working with functions that have an argument called 'action'

### ISSUE THREAD

**Issue by fpauser** [emberjs/ember.js#18748]
The following controller code produces a `ReferenceError: action is not defined.`

My environment:
ember: 3.12.2
ember-cli: 3.12.1
node: 10.19.0

```js
import { action } from '@ember/object';

export default class DummyController extends Controller {
  @action callAction(action) {
    return { action };
  }
}
```

Changing the `callAction` parameter name from `action` to e.g. `aktion` solves this problem.
Looks like the transpilation is doing something wrong:

Non working transpiled code (excerpt):
```js
(Ember.Controller), (_applyDecoratedDescriptor(_class.prototype, "callAction", [action], Object.getOwnPropertyDescriptor(_class.prototype, "callAction"), _class.prototype)), _class);
  _exports.default = DummyController;
});
```

Working transpiled code with renamed argument (excerpt):
```js
(Ember.Controller), (_applyDecoratedDescriptor(_class.prototype, "callAction", [Ember._action], Object.getOwnPropertyDescriptor(_class.prototype, "callAction"), _class.prototype)), _class);
  _exports.default = DummyController;
});
```

**Comment by fpauser** [comment]
I tried to create a failing unit-test without success (my supposed-to-fail test works as expected, both on master and v3.12.2).

Here is a repop of this error: https://github.com/fpauser/ember-action-decorator-test
Just run and watch the browser console.

**Comment by btecu** [comment]
Can you try calling the argument something other than `action`?

**Comment by fpauser** [comment]
Yes, I did - but it's still a nasty bug.

Am Fr., 21. Feb. 2020 um 00:02 Uhr schrieb btecu <notifications@github.com>:

**Comment by pzuraq** [comment]
FWIW this has been reported before, and it appears to be an issue with `babel-plugin-ember-modules-api-polyfill`, since it occurs for any decorator, not just `@action`

**Comment by fpauser** [comment]
This seems to be the interesting part in `babel-plugin-ember-modules-api-polyfill`:
https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/blob/fd6ffbb6a8514f547114ad5727907a3470df2843/src/index.js#L121

```js
if (path.scope.bindings[local.name].referencePaths.find(rp => rp.parent.type === 'ExportSpecifier')) {
  // not safe to use path.scope.rename directly
  declarations.push(t.variableDeclaration('var', [
    t.variableDeclarator(
      t.identifier(local.name),
      t.identifier(global)
    ),
  ]));
} else {
  // Replace the occurences of the imported name with the global name.
  replacements.push([
    local.name,
    global,
  ]);
}
```
In my case `path.scope.bindings[local.name].referencePaths` is empty which leads to the replacement.

When I change this block to always create a declaration my code works (but all tests break due to the missing inline replacement for global vars):

```js
declarations.push(t.variableDeclaration('var', [
  t.variableDeclarator(
    t.identifier(local.name),
    t.identifier(global)
  )
}
```

**Comment by sandstrom** [comment]
> FWIW this has been reported before, and it appears to be an issue with babel-plugin-ember-modules-api-polyfill, since it occurs for any decorator, not just @action

I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. 

By closing some old issues we reduce the list of open issues to a more manageable set. 

People can still google and find this, but it doesn't make sense to keep it open if the bug isn't in this repo.
