### ISSUE TITLE
External attribute Computed Property changes not recognized by component in ember test

### ISSUE THREAD

**Issue by theseyi** [emberjs/ember.js#18744]
I have a computed property on a class, e.g. service, rendered in a component template.
The property is updated via a method, outside of the component.
I expect, the component to register the change on the computed property and rerender it's value.

This is failing to happen in a test case.
However, if I have say a <button> rendered within the component and click it, the component will recognize the diff, and rerender

I have a repro here: https://github.com/theseyi/ember-repro/blob/master/tests/integration/components/my-component-test.js

the test is simple enough  to add here:
```js
module('Integration | Component | my-component', function(hooks) {
  setupRenderingTest(hooks);

  test('it renders', async function(assert) {
    class MyService extends Service {
      value = true;

      @computed('value')
      get flag() {
        return this.value;
      }

      notify() {
        set(this, 'value', !this.value);
      }
    }
    this.owner.register('service:my-service', MyService);

    @layout(hbs`
    <div>
      {{@service.flag}}
      <button type="button"></button>
    </div>
    `)
    class MyComponent extends Component {}

    this.owner.register('component:my-component', MyComponent);

    const myService = this.owner.lookup('service:my-service');

    this.set('myService', myService);
    await render(hbs`
      <MyComponent @service={{this.myService}}/>
    `);

    assert.dom().hasText('true');
    myService.notify();
    // await click('button'); // uncommenting this will force the component to register the computed property change which should not be needed
    assert.dom().hasText('false');
  });
});

```

EDITED to add ember version:     "ember-source": "~3.16.0",

**Comment by jnfingerle** [comment]
I believe you've got to `await settled()`  where you commented out the click. Otherwise you test the text before the change had a chance to propagate.

see https://github.com/emberjs/ember-test-helpers/blob/master/API.md#settled

**Comment by theseyi** [comment]
Thanks for taking a look @jnfingerle but that's a little strange given my understanding of computed properties. The docs even have a similar test that works as expected when the computed property is on the component, I don;t see why this should be different when the computed property is on a service or external to the component itself. I've used the `settled()` api, when promises, timers or asynchronousity is at play. Does not immediately seem to be the case here

from https://guides.emberjs.com/release/testing/testing-components/

> We might also test this component to ensure that the content of its template is being rendered properly:

```js
import { module, test } from 'qunit';
import { setupRenderingTest } from 'ember-qunit';
import { render } from '@ember/test-helpers';
import { hbs } from 'ember-cli-htmlbars';

module('Integration | Component | pretty-color', function(hooks) {
  setupRenderingTest(hooks);

  test('it renders', async function(assert) {
    assert.expect(2);

    this.set('colorValue', 'orange');

    await render(hbs`<PrettyColor @name={{this.colorValue}} />`);

    assert.equal(this.element.textContent.trim(), 'Pretty Color: orange', 'text starts as orange');

    this.set('colorValue', 'green');

    assert.equal(this.element.textContent.trim(), 'Pretty Color: green', 'text switches to green');
  });
});
```

**Comment by theseyi** [comment]
Some additional context, the actual test case was passing as expected in ember 3.11, and even 3.12, but fails in 3.13 (octane preview), 3.14, 3.15 and 3.16!
So most likely a regression or bug it seems?

@locks this is as per you request for a repro on discord

**Comment by theseyi** [comment]
Seems that `await settled();` is the way to resolve this. I will attempt to create a separate ticket to update the Ember guides / docs to communicate this change to readers if that hasn't been done already. Thanks @jnfingerle

**Comment by pzuraq** [comment]
For some additional context here, in tests the `this.set()` for the test itself _is_ wrapped in a runloop, for backwards compatibility reasons, but other objects' `set` methods are _not_ wrapped in one, which is why this likely isn't working despite what the guides suggest. I agree that the guides should be updated to show `await settled()` because of this.

I'm not sure how this was working before though, it seems like this always should have failed because of that. Nothing we changed should have affected this, I believe..

**Comment by theseyi** [comment]
It's a little curious the actual test has been in our codebase for at least a year, and never failed once without awaiting settlement. However, running the test unchanged in every successive version *.0 version since 3.11, i.e. 3.12 - 3.16 failed.
But, thanks for confirming my suspicions about the `this.set` being async
