### ISSUE TITLE
length (and probably size) column name cause an error

### ISSUE THREAD

**Issue by sinankeskin** [emberjs/ember.js#18745]
Hi.

It's really hard to explain but I'll try.

I have a model and this model has a column named **length** ( I know but I have to).

If I create a **changeset** from this model and if I check the **changeset** is present with isPresent helper function cause an error which basicly says that you can't reach .length directly because .length is a Proxy object now.

isPresent calls isBlank and isBlank calls isEmpty and I believe the below line is the responsible for this error.

https://github.com/emberjs/ember.js/blob/1f08044fbdbbdffc9cc014b43861eeb4a2f4803f/packages/%40ember/-internals/metal/lib/is_empty.ts#L57

Also in the same context I believe if I use the column name size it will throw an error also because of the below line.

https://github.com/emberjs/ember.js/blob/1f08044fbdbbdffc9cc014b43861eeb4a2f4803f/packages/%40ember/-internals/metal/lib/is_empty.ts#L44

Thank you.

**Comment by rwjblue** [comment]
FWIW, you are going to have a pretty rough time with a `length` property. I personally would try to avoid it by using a different name internally.

**Comment by sinankeskin** [comment]
You are right. We should consider these properties as no-no keywords.

Thank you.
