### ISSUE TITLE
Regression pushing to array proxy

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#18749]
In 3.16.0 pushing to an ember array proxy re-renders with the new item
In 3.16.3 this does not happen.

Here is a [demo repo](https://github.com/amk221/-ember-array-proxy/commit/c9ddf5959202a102785e0a042afdb327f0fe483e#diff-a9a19ee37ba8619bc68db992b637dd05R34).

- Run the app, click the button, and compare the console output to what is on screen
- Then update the app to 3.16.3
- Run the app, click the button, and compare the console output to what is on screen

**Comment by pzuraq** [comment]
Looks like a duplicate of #18750, going to close and consolidate, but will make sure that the solution for that works for this case as well.

**Comment by amk221** [comment]
Oh poo. I did do a search, promise.

**Comment by pzuraq** [comment]
No worries, you were first, just luck of the draw on which one I closed. Thanks for this bug report, it's very helpful!

**Comment by patocallaghan** [comment]
oh sorry @amk221, indeed you did open this issue first. I just had my WIP issue open in a tab for a few hours before posting it 🙈
