### ISSUE TITLE
Wrong use of typeof in `installProtocolForURL` and module undefined

### ISSUE THREAD

**Issue by markusm7** [emberjs/ember.js#18757]
Im not sure why im getting this error only on one of my published applications (maybe different use of stict mode) but im getting a reference error

`module is not defined`

digging into the code it's a problem in this file
https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/glimmer/lib/protocol-for-url.ts

`typeof module !== undefined` should probably be `typeof module !== 'undefined'`

Still not sure why `module` on my end is `undefined` in the first place. Any ideas or hints where i could check something?

**Comment by markusm7** [comment]
I found the reason our application ran into this:
The ember application is used as a widget on a third party website. That website uses moo tools as an additional framework. Sadly it ovverides global Constructors like `Window` and `Document`. Therefore the check `self.constructor === Window` for `hasDOM` is no more valid and the application tries to apply different parsing logic hence trying to enter this case.

Just to put it out: is it necessary to have this check in place (self.constructor === Window)?
Im ok if it stays and we push the ball to the consuming website, just exploring options.

But the wrong typeof check should still get a fix at some point :)

**Comment by rwjblue** [comment]
Welp, I fail at GitHubing today. I made that change inline and accidentally committed it directly to master 😩 

https://github.com/emberjs/ember.js/commit/696948cb813c08927df57c18c87040e4bbb009e1
