### ISSUE TITLE
[3.16.2] Regression with ember-power-select

### ISSUE THREAD

**Issue by Bouke** [emberjs/ember.js#18763]
I'm using ember-power-select (latest v3) to show a select element with options provided by ember-data.

With ember 3.16.1, this used to work to populate the dropdown. After upgrading to 3.16.2 or 3.16.3, this no longer works. No error or warning, just a dropdown with only the current element shown. There is an API call being performed, but the result seems to be ignored.

Upgrading between patch versions shouldn't cause such regressions I suppose?

As there's no console output, I'm not sure what else to report. Please advice.

`select-customer.ts`:
```ts
export default class SelectCustomer extends Component {
    @inject store!: DS.Store;
    options: any
    init() {
        super.init()
        this.options = this.store.findAll('customer')
    }
}
```

`select-customer.hbs`:
```hbs
<PowerSelect @options={{this.options}} @searchEnabled={{true}} @search={{this.search}}
    @selected={{this.selected}} @onChange={{this.onChange}} as |customer|>
    {{customer.name}}
</PowerSelect>
```

```
00:15:14.521 DEBUG: -------------------------------
00:15:14.550 DEBUG: Ember      : 3.16.2 index.js:194
00:15:14.551 DEBUG: Ember Data : 3.16.0 index.js:194
00:15:14.551 DEBUG: jQuery     : 2.1.1 index.js:194
00:15:14.551 DEBUG: -------------------------------
```

**Comment by patocallaghan** [comment]
@Bouke I think this is being caused by https://github.com/emberjs/ember.js/issues/18750 as I believe `this.store.findAll` is an `ArrayProxy`
