### ISSUE TITLE
Missing error when attributes passed to nowhere

### ISSUE THREAD

**Issue by ro0gr** [emberjs/ember.js#18799]
Here is what [Angle Bracket Invocation](https://github.com/emberjs/rfcs/blob/master/text/0311-angle-bracket-invocation.md#html-attributes) RFC tells:

>  If attributes are passed but the component template does not contain `...attributes` (i.e. the invoker passed some attributes, but the invokee does not take them), it will be a development mode error.

Not sure if implementing this part of RFC should be considered a breaking change now, but it seems like a good thing to have. 

Are there any blockers to do it?

**Comment by pzuraq** [comment]
This was part of the RFC that was changed during implementation, as I discovered recently myself. This is one of the things we're hoping to change with the RFC Stages RFC, which would give us a history for any changes that happen during implementation. This is not the only occurrence of a change, FWIW, and part of the reason the process needs to be updated.

**Comment by ro0gr** [comment]
@pzuraq do you know if it was an intentional change during implementation, or is it something that should be implemented to match the RFC?

**Comment by pzuraq** [comment]
It was an intentional change during implementation, I learned about it when discussing with @rwjblue.

This was before we had a process to _capture_ such implementation changes in RFCs, so the original spec was never updated. This is why we built updates into the upcoming RFC stages process, which should make the whole process of development itself much more transparent (or at least, that's the goal!)

**Comment by pzuraq** [comment]
I'm going to close this because I think it has been answered, but feel free to reopen if you still have questions/concerns!

**Comment by ro0gr** [comment]
@pzuraq thank you for your response.

TBH, this design decision seems unclear to me, and it strongly smells like a foot gun.. I'd really like to understand the reasons for it to avoid a conflict with my current mindset.

Basically, i still believe, `...attributes` on anything other than a top-most element, or even missing attributes is something very confusing and limiting for any consumer of such a component. For instance, if my `class` is set somewhere deep inside the component, I just cant style it w/o breaking encapsulation. I hope, I do miss smth, but I don't believe so. Would really appreciate to know some context around this decision, or real use cases..

@rwjblue maybe you can shed some light here?

**Comment by pzuraq** [comment]
> Basically, i still believe, ...attributes on anything other than a top-most element, or even missing attributes is something very confusing and limiting for any consumer of such a component

This seems unrelated to the change in the RFC. If the feature had been implemented as described, it still would have been possible to specify `...attributes` on any element within the component. It just would have been an error if the component did _not_ specify `...attributes`, and then the user tried to pass attributes. As it is currently, passing attributes in a component which does not use them is a no-op, which is the same behavior as passing arguments to a component which does not use them.

It's also worth noting that you can have components which do not have _any_ elements within them at all, so its possible that there is no top-most element to apply `...attributes` to. That is a bit of a separate concern though. I agree that `...attributes` presents some thorny issues with regards to encapsulation, but I think that those issues exist regardless of the change, unfortunately.

**Comment by ro0gr** [comment]
@pzuraq 

> This seems unrelated to the change in the RFC.

Ya, agree. Seems to be out of the scope, sorry. For me, these just perceived as a similar issues with the current `...attributes` state, so I've lost the focus a bit.
> As it is currently, passing attributes in a component which does not use them is a no-op, which is the same behavior as passing arguments to a component which does not use them.

Arguments and attributes are a bit different currently. Arguments can be only consumed by name, while the attributes are completely anonymous. Components are just unable to use any attribute, it can just apply everything to an element. So IMO, it's not about a specific attributes, it's just about if the component forgot to provide a proper support for `...attributes`. During refactoring, it may cause problems, and it happened to me few times.

> you can have components which do not have any elements within them at all

Me as as component user, wants to be notified somehow, that's the `...attributes` are not allowed, if I try to pass some.

> so its possible that there is no top-most element to apply ...attributes to. 

yes, it's also applicable for the case of multiple roots_(I haven't seen a good reason still, and think it looks like an antipattern)_, but if neither of roots have an `...attributes` applied, I think it also confusing for a user to have a feedback about it.

---

That being said, I'm still unsure about the reason to not follow the RFC here. Cause when I pass attributes, and it's just ignored silently, that'd be unexpected at least.
