### ISSUE TITLE
Helper doesn't recompute after a changed tracked value

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#18802]
[Here is a reproduction](https://github.com/boris-petrov/tracked-bug).

Check the `t-static` helper. In its `compute` a method is called (`computeResult`) in which `this.i18n.locale` is used. It is later changed but the helper doesn't recompute. If you uncomment line 10 where `this.i18n.locale` is used directly in `compute` (rather than transitively in a method called by `compute`) - the helper does recompute.

I believe this is a bug. Happens on both 3.16 and 3.17.

**Comment by pzuraq** [comment]
This isn't a bug. Helpers autotrack their last computation, so if you have a new computation where the helper does not use a particular value, it will not be tracked.

You should, in general, not be using the `recompute()` method anymore. It's not deprecated yet, but it shouldn't be necessary with autotracking, and is a major codesmell.

I think the main issue here is that the code flow is not working _with_ autotracking. Here's an example of how you could do this in a better way:

```js
import Helper from '@ember/component/helper';
import { inject as service } from '@ember/service';
import { next } from '@ember/runloop';

class Task {
  @tracked value;

  constructor(promise) {
    promise.then(() => (this.value = value));
  }
}

class TaskFactory {
  constructor(fn) {
    this.taskFn = fn;
  }

  state(...args) {
    if (
      !this._lastArgs ||
      this._lastArgs.length !== args.length ||
      this._lastArgs.some((arg, i) => arg !== args[i])
    ) {
      this._currentTask = new Task(this.taskFn(...args));
    }

    this._currentTask.value;
  }
}

export default class TStatic extends Helper {
  @service
  i18n;

  localize = new TaskFactory(async (message, locale) => {
    return await fetchTranslation(message, locale);
  });

  compute([message]) {
    return this.localize.state(message, this.i18n.locale);
  }
}
```

This pattern is something that is pretty generalizable, and importantly it ensures that the correct tracked state is always used when deriving state.

**Comment by boris-petrov** [comment]
Thanks for the explanation!
