### ISSUE TITLE
(0 , _emberBabel.createSuper) is not a function. Recent babel 7.9.0 seems to break all apps

### ISSUE THREAD

**Issue by EWhite613** [emberjs/ember.js#18827]
Looks like even all apps are broken that pickup `@babel` `7.9.0` stuff which was recently published.

If you do `ember new tester-if-broken`. Then remove the `config/target.js` file you'll get that error after you visit the page after a `ember s`

Not sure if this is the right repo (let me know if I should move it)

But definitely seems related to the recent @babel 7.9.0 (pushed 3 hours ago).  If have the 7.8.3 in my app, works fine. But as soon as I upgrade something that has babel it will pick up the new 7.9.0 and it will break.

**Comment by EWhite613** [comment]
Example repo added here: https://github.com/EWhite613/ember-broken-super-example

**Comment by jherdman** [comment]
You are a saint. I've been fighting this all day.

**Comment by dgeb** [comment]
I've noticed that this is related to targeting IE 11. Removing that target (if you're able to) seems to resolve the issue.

**Comment by rwjblue** [comment]
I'm looking into fixing this. Unfortunately, it will require changes to `ember-source` so the fix will likely only land for 3.16 and 3.17 (I don't think 3.12 is affected).

**Comment by rwjblue** [comment]
@EWhite613 - Doing:

```sh
git clone git@github.com:EWhite613/ember-broken-super-example.git
cd ember-broken-super-example
npm ci
ember b # also tried ember s
```

Does not have a build error.

**Comment by rwjblue** [comment]
D'oh 🤦‍♂, it is a runtime error not a build error. Sorry.

**Comment by rwjblue** [comment]
Should be resolved by https://github.com/emberjs/ember.js/pull/18831, which will be backported for 3.16, 3.17, and 3.18.

**Comment by bendemboski** [comment]
Not sure if all of these are needed, but if you're using `yarn`,

```
  "resolutions": {
    "@babel/core": "7.8.7",
    "@babel/helpers": "7.8.4",
    "@babel/plugin-transform-classes": "7.8.6",
    "@babel/runtime": "7.8.7",
  }
```

will get things working until this fix is released.
