### ISSUE TITLE
getOwner().rootElement is not the same as APP.rootElement in config

### ISSUE THREAD

**Issue by andrewfan** [emberjs/ember.js#18833]
I'm building a chrome extension using ember, thus to bootstrap ember I have to append stringify config to the meta tag with custom rootElement. 
However when I'm getting rootElement from `getOwner().rootElement` it is still `body`. Also `event_dispatcher` does not extend the rootElement from the config (it is always 'body').

**Comment by andrewfan** [comment]
Looks like it happens because ember does not set `rootElement` to the application in `app.js` file from config automatically. Is this done for some reason?

**Comment by rwjblue** [comment]
When the app boots the `rootElement` is read, are you setting it before the app boots?

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. 

This seem like more of a question than a bug report/issue, and therefore better suited for the forums: https://discuss.emberjs.com/

Also, the reality for any open-source framework, relying on individuals to put in the work, is that there isn't always time to answer all questions.

If you want to pay back to the community, one easy thing is to ask one question in the forum (your current one), and also try to answer 2 questions from other people.

If you think this is an error, a reproduction of the bug and a more extensive explanation would be a good start. Then, if others agree it's a bug, the second step is often to dig in and write a patch to fix the bug.

I'll be closing this for now though, to keep the list of open issues manageable. I hope you understand.
