### ISSUE TITLE
runtime.js:2003 Uncaught (in promise) TypeError: Cannot read property 'syscall' of null

### ISSUE THREAD

**Issue by jiridanek** [emberjs/ember.js#18844]
In dev mode with `ember serve`, when there is an undefined component used in a template, I get a white screen and an error in browser console.

Instead, I would like to get a better error message, explaining that (in case of the linked reproducer repository) the component `no-such-component` is not defined. In addition, I would like to still see the working parts of the page rendered, again, in the reproducer, that would be the `<h1>I am here</h1>`.

The current behavior is problematic because it makes hunting for undefined components difficult. I have to resort to going back to last working state and incrementally re-add new things until the exception appears.

Exception in Chrome 80

```
runtime.js:2003 Uncaught (in promise) TypeError: Cannot read property 'syscall' of null
    at AppendOpcodes.evaluate (runtime.js:2003)
    at LowLevelVM.evaluateSyscall (runtime.js:4906)
    at LowLevelVM.evaluateInner (runtime.js:4862)
    at LowLevelVM.evaluateOuter (runtime.js:4854)
    at JitVM.next (runtime.js:5798)
    at TemplateIteratorImpl.next (runtime.js:5927)
    at RootState.render (index.js:8771)
    at runInAutotrackingTransaction (validator.js:102)
    at index.js:9069
    at inTransaction (runtime.js:1959)
```

Exception in Firefox 73

```
DEBUG: ------------------------------- index.js:194
DEBUG: Ember      : 3.17.2 index.js:194
DEBUG: Ember Data : 3.17.0 index.js:194
DEBUG: ------------------------------- index.js:194
TypeError: operation is null
runtime.js:2003
Ember Inspector Active debugger eval called from moz-extension://a55ba405-f22b-4933-8a82-1aa952cc3c77/ - eval code:90:22
TypeError: operation is null
3 runtime.js:2003
```

Reproducer repository

https://github.com/jirkadanek/emberjs-issues-16503

Related issues

* https://github.com/emberjs/ember.js/issues/16503

**Comment by mansona** [comment]
Is there any movement on getting a better error for this? I just came across this when I was working on an addon that forgot to add `ember-composible-helpers` to its dependencies, so the helper couldn't be found when that addon was being used in another app. 

I had no way to debug this other than trial and error 🙈

**Comment by locks** [comment]
Thanks for the reproduction! Forked to https://github.com/ember-triage/emberjs-issues-16503 for archival purposes.

**Comment by lolmaus** [comment]
Saw this when upgrading from `3.13` to `3.18`, but `3.19` is fine.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. It seems outdated and likely no longer relevant.

By closing some old issues we reduce the list of open issues to a more manageable set. Let me know if you think this is a mistake and that the issue should stay open.

Seems to be solved according to parent comment.
