### ISSUE TITLE
Assertion Error : App Version has already been registered

### ISSUE THREAD

**Issue by SridharMurali1995** [emberjs/ember.js#18843]
Im using ember to develop a project. Please help me with this error. Im unable to run my project on local. After hitting ember server the build is successful. But on hitting the http://localhost:4200 Loads empty page with console error.

Unable to understand what to do. Any help regarding this would be appreciated.
Checked online on other sites for a solution, but could not find anything. Please help.

`Uncaught Error: Assertion Failed: The initializer 'App Version' has already been registered
    at assert (index.js:172)
    at Function.initializer (index.js:420)
    at registerInitializers (index.js:27)
    at loadInitializers (index.js:68)
    at Module.callback (app.js:25)
    at Module.exports (loader.js:106)
    at requireModule (loader.js:27)
    at app-boot.js:3`

**Comment by rwjblue** [comment]
Hmm, not sure what exactly is going on here. This specific error would likely only be triggered when you load your initializers twice. The best guess I would have is that for some reason you have called `loadInitializers(App, config.modulePrefix)` twice in your `app/app.js` file.

**Comment by SridharMurali1995** [comment]
> app.js
`loadInitializers(App, config.modulePrefix)`
it is only called once in my app.js file.

**Comment by SridharMurali1995** [comment]
When I first found this issue, Running `npm install` solved this. 
But now, again the issue resurfaced and `npm install` does not seem to solve this issue. 
Any possible workaround you can suggest to overcome this?

**Comment by rwjblue** [comment]
Sorry, I'm really not sure what is going on. Its probably going to take a reproduction for someone to be able to tell you what is going on. 

We can absolutely continue to discuss here, but I'm going to close this issue (as doesn't seem like a bug in Ember to me).

**Comment by SridharMurali1995** [comment]
@DanLeininger Thanks a lot. 
This is exactly what was happening to me. I turned off iCloud sync and now it is working fine for me.
