### ISSUE TITLE
Regression in behavior of `delete` after 3.13 from mandatory setters

### ISSUE THREAD

**Issue by chriskrycho** [emberjs/ember.js#18856]
In 405d4238, we introduced mandatory setters to native properties. Previously, users could call `delete this.foo` and then later call `set(this, 'foo', 'some value')`, and it would work correctly. Because the setters are set on the instance (as they must be), this no longer works: if a user calls `delete this.foo`, it deletes the *getter and setter*, meaning that all future calls to `set(this, 'foo', ...)` fail.

Workaround: using `set(this, 'foo', undefined)`.

Related: #18769

**Comment by rwjblue** [comment]
The mandatory setter changes have landed now, we should reevaluate...

**Comment by knownasilya** [comment]
Wonder if this is fixed.

**Comment by rwjblue** [comment]
@chriskrycho - Mind double checking (or throwing together a repro that we could use to check in on this in the future)?

**Comment by chriskrycho** [comment]
Seems to be fixed!

<details><summary>test code to demonstrate</summary>

`controllers/application.js`:

```js
import Controller from "@ember/controller";
import { set } from "@ember/object";

export default class ApplicationController extends Controller {
  foo;

  constructor() {
    super(...arguments);
    set(this, "foo", "huh");
  }

  baleted = () => {
    delete this.foo;
  };

  setItBack = () => {
    set(this, "foo", "hey, it's back!");
  };
}
```

`templates/application.hbs`:

```hbs
<h2 id="title">
  baleted
</h2>
<p>
  <code>
    this.foo
  </code>
  is
  {{describe this.foo}}
</p>
<div>
  <button {{on "click" this.baleted}}>
    BALETED
  </button>
</div>
<div>
  <button {{on "click" this.setItBack}}>
    Put it back
  </button>
</div>
```

`helpers/describe.js`:

```js
import { helper } from "@ember/component/helper";

export default helper(function describe([value] /*, hash*/) {
  return value === undefined ? "undefined" : JSON.stringify(value);
});
```

</details>
