### ISSUE TITLE
Computed macros doesn't play well with getters

### ISSUE THREAD

**Issue by stukalin** [emberjs/ember.js#18851]
I've discovered this issue during the octanifying of my project.
Currently we have the following
```
Ember      : 3.16.3
Ember Data : 3.15.1
```
but I could also repro that on ember twiddle with 3.17.0/3.16.2 accordingly.

Let's say we have a model `user` which has 2 properties and a getter:

```
export default class extends Model {
  @attr('string') name;
  @hasMany('tag', {async: false}) tags;
  
  get hasOwnerTag() {
    return !isEmpty(this.tags) && !isEmpty(this.tags.findBy('type', 1));
  }
}
```

Now I want to create a new property which basically works as an alias for the `hasOwnerTag`. We used to have the `@bool` macros for that purpose but it doesn't work anymore, however if I declare a getter everything works fine.

```
  // neither of those work
  @bool('hasOwnerTag') isOwnerBool;
  @bool('{hasOwnerTag}') isOwnerBoolCurly;

  // but this one does
  get isOwner() {
    return this.hasOwnerTag;
  }
```

Now I want to have a property which negates the value of this getter. Again, we used to have the `@not` macros for that and the problem is basically the same:

```
   // neither of those work
  @not('{isOwner}') notOwnerCurly;
  @not('isOwner') notOwnerMacro;
  
  // but this one does
  get notOwnerGet() {
    return !this.isOwner;
  }
```

I am not 100% sure how legal macroses are in Octane (I guess they are not mentioned in the current version of guides), so apart from reporting a bug I'd also like to know the current state of things with macroses and if I should get rid of them and use regular getters.

Here is the twiddle which runs a test which demoes the issue: https://ember-twiddle.com/bfa385e26ef6f9bc13167a9d0067ad3c?openFiles=twiddle%5C.json%2C

**Comment by stukalin** [comment]
Ok, I guess I figured this one out. It looks like I need to use the `dependentKeyCompat` decorator to make everything work. Another thing: I tried to make this example as small as possible but in reality these `@bool`s and `@not`s are in another model and the dependencies lie there. I've updated my twiddle to reflect this fact. The thing is that the `dependentKeyCompat` seems not to work within the same class (like I described above).

Long story short, if I have the
```
export default class extends Model {
  @attr('string') name;
  @hasMany('tag', {async: false}) tags;
  
// not the decorator
  @dependentKeyCompat
  get hasOwnerTag() {
    return !isEmpty(this.tags) && !isEmpty(this.tags.findBy('type', 1));
  }
}
```
and then in another model
```
export default class extends Model {
  @belongsTo('user', {async: false}) user;
  
  @bool('user.hasOwnerTag') isOwnerBool;
	@not('isOwnerBool') notOwnerMacro;
}
```
then everything works as expected

**Comment by pzuraq** [comment]
Yup, this is a known limitation of computed macros, and dependentKeyCompat is the correct solution.

You should also consider looking into the [macro-decorators](https://pzuraq.github.io/macro-decorators/) library. It’s a vanilla JS replacement which doesn’t have these issues or require `dependentKeyCompat`, and is a contender to be the replacement solution once computed/macros are removed.
