### ISSUE TITLE
Ability to configure "usePods" for everything apart from co-located components

### ISSUE THREAD

**Issue by mansona** [emberjs/ember.js#18850]
Hi folks 👋 

There was a bit of a [discussion about this in the #topic-octane-migration](https://discordapp.com/channels/480462759797063690/608346628163633192/694189776437510145) channel yesterday and I wanted to open up an issue to describe the request and try to figure out a way forward. 

Essentially with Octane we have co-located components (which are amazing 😍) but we still need to use the "classic" style for controllers, routes, templates etc. 

A lot of people have had success using Pods while we have been waiting for Module Unification and other forms of co-location, and most of the projects that I work on have `"usePods": true` configured in their `.ember-cli` files because of this. 

The issue that I have is that if you define `"usePods": true` in your `.ember-cli` config then generating a new component will use the pod structure instead of the new co-location structure 😢 

What I would ideally like would be for some way to say "use pods but not for components". While discussing this in #topic-octane-migration on Discord some other people mentioned that it might be good to be able to define what you would like to use pods for, that way you could configure the app to use pods for Routes and Controllers, but tell it to leave Models in a non-pod structure.

I'm not sure what the best way to define this would be, i don't have any **good** proposals but my naive  idea would be to add something like: 

```json
{
  "disableAnalytics": false,
  "usePodsFor": [ "controllers", "routes" ]
}
```

Any thoughts?

**Comment by rwjblue** [comment]
Seems pretty unlikely that we will change this in the short term. I think that you should probably just pass the flag to disable your global `usePods` when you generate a component.

**Comment by mansona** [comment]
@rwjblue I'm happy to do the work if that's the blocker 😂 but if you mean that we probably don't **want** to do this then that's of course a different thing

I understand that the pods structure is "lightly deprecated" or at least discouraged at this point so I understand if we don't want to add more complexity to this situation 👍

**Comment by mydea** [comment]
We have exactly the same use case - for us, the classic layout for controllers/routes/route templates doesn't work at all, and we're quite happy with using pods for them, and co-location for components. I would also appreciate a way to set this more permanently, as it happens rather frequently that I do e.g.:

```bash
ember g controller my-controller
# Oops, this is classic...
ember d controller my-controller
ember g controller my-controller --pods
```

I've heard a few times that the recommended solution is kind of "do not use pods", but IMHO pods are vastly easier for us to work with than the classic layout, so that's not really a solution for us.

**Comment by locks** [comment]
Closing as stale. Please re-open if I got it wrong 🙇
