### ISSUE TITLE
[3.17] [REGRESSION] re-rendering an `{{#each}}` with multiple null values only renders one iteration

### ISSUE THREAD

**Issue by bendemboski** [emberjs/ember.js#18864]
When updating an `{{#each}}`-rendered array to be `[ null, null, null ]`, only one iteration of the array is rendered, as if it just contained `[ null ]`. This rendering test passes in 3.16 and fails in 3.17:

```javascript
  test('rerendering array of nulls works', async function(assert) {
    this.set('items', [ false, false, false ]);
    await render(hbs`
      {{#each this.items as |item|}}
        <p>item: {{item}}</p>
      {{/each}}
    `);
    assert.dom('p').exists({ count: 3 });

    this.set('items', [ null, null, null ]);
    await settled();
    assert.dom('p').exists({ count: 3 });
  });
```

[here](https://github.com/bendemboski/rerender-null-array) is an app that reproduces the issue and demonstrates that it's a regression since 3.16.

**Comment by pzuraq** [comment]
Bugfix submitted upstream, pending review
