### ISSUE TITLE
[3.17] breaking change in ember-template-compiler#syntax.builders.element()

### ISSUE THREAD

**Issue by simonihmig** [emberjs/ember.js#18862]
When an addon provides a template AST transform, it receives the AST builder helpers from `@glimmer/syntax` as `this.syntax.builders`. The `element()` helper shows a breaking change between Ember 3.16 and 3.17. I assume because of the GlimmerVM updates that happened there!?

The breaking change seems to be related to this 1.5y old PR: https://github.com/glimmerjs/glimmer-vm/commit/64ceeee8a605712ccd8432bd98ca0ec81e600bcc

As you can see the signature of that `buildElement()` function has changed, from receiving a bunch of positional arguments to named args basically (a `BuildElementOptions` hash). A call like [this](https://github.com/kaliber5/ember-ecsy-babylon/blob/master/lib/ast-transform.js#L68-L78) relying on the old signature, that worked correctly for all Ember versions < 3.17 is now returning a wrong AST node object, causing the transform to break.

**Comment by pzuraq** [comment]
As I understand it, the AST structure and builders, and AST transforms themselves, are not considered public API. I experienced similar breakage in some of my transforms.

cc @rwjblue for confirmation here.

**Comment by rwjblue** [comment]
Confirm, the AST itself and the builders are not public API from Ember's standpoint. However, if there is a straightforward fix we are open to accepting it...

**Comment by simonihmig** [comment]
Hm, ok, in this case I'll close this. But it feels a bit chilling, with the vital role that e.g. polyfills play in the ecosystem, which rely on this, that there are no stability guarantees...

**Comment by pzuraq** [comment]
FWIW, the breakage here was caused by adding Named Blocks and setting up the AST for strict mode. It would not have been possible to do these changes without some minor breakage, which is in part why the API is considered private I believe - its a place where we really do need some flexibility to absorb change.

**Comment by rwjblue** [comment]
> But it feels a bit chilling, with the vital role that e.g. polyfills play in the ecosystem, which rely on this, that there are no stability guarantees...

Ya, I definitely understand. Those polyfills (we both maintain a number of them) are critical, and their goal is specifically to absorb this sort of churn for their consumers. In most cases it is pretty trivial to check what version of the AST is being used and change the output to accommodate.
