### ISSUE TITLE
Dead link in getting-started/quick-start/ 3.17 §-Next steps

### ISSUE THREAD

**Issue by jjff** [emberjs/ember.js#18868]
"There is an official, free tutorial here in the Guides that delves deeper into some of the features you used today. Give it a try!."
Link "Give it a try!"  to https://guides.emberjs.com/release/getting-started/quick-start/tutorial  is broken / no more possible.

**Comment by locks** [comment]
Thanks for reporting, I have moved this issue to the correct repo: https://github.com/ember-learn/guides-source/issues/1389.
