### ISSUE TITLE
findRecord with a very large include parameter

### ISSUE THREAD

**Issue by corrspt** [emberjs/ember.js#18863]
Hi everyone,

In my app I have a model with LOTS of relations, which when I need to load on a particular route I need to do `this.store.findRecord('model-name', ID, { include: LOTS_HERE });`

Up until Ember 3.12, this worked fine. But I'm trying to upgrade to Ember 3.13 (and have tried 3.14, 3.14, 3.15, 3.16 and 3.17 without luck). From Ember 3.13+, whenever I do that request I get a "400 bad request" (it doesn't even touch my server, so it's somewhere ember throwing an error)

I've made a reproduction (it doesn't give exactly the same error)
[https://github.com/corrspt/example-error-app-emberjs-3.13](https://github.com/corrspt/example-error-app-emberjs-3.13). If on the `route/application.js` you reduce the size of the `include` part, it will throw a different error (due to missing backend).

This is currently blocking from upgrading to Ember 3.13+

EDIT: For reference here's my actual code that performs the findRecord. If I cut the `include` parameter to about 1/3 of it's size, it works (maybe 2/3, I'll try to provide the correct number).
```
return this.store.findRecord('pqr', id, {
      include:
        'construction-standard,company,examining-body,shielding-root-gas-test-piece,shielding-root-gas-commercial-designation-test-piece,shielding-root-flux-test-piece,shielding-root-flux-commercial-designation-test-piece,shielding-fill-gas-test-piece,shielding-fill-gas-commercial-designation-test-piece,shielding-fill-flux-test-piece,shielding-fill-flux-commercial-designation-test-piece,backing-gas-test-piece,backing-gas-commercial-designation-test-piece,backing-flux-test-piece,backing-flux-commercial-designation-test-piece,post-weld-heat-treatment-method-test-piece,base-material1-test-document,base-material2-test-document,filler-material-root-test-document,filler-material-fill-test-document,filler-material-cap-test-document,visual-test-document,penetrant-test-document,magnetic-test-document,ultrasonic-test-document,radiographic-test-document,tensile-test-document,bend-test-document,macroscopic-test-document,impact-test-document,hardness-test-document,chemical-analysis-test-document,pqr-report-document,pqr-document,shielding-cap-gas-test-piece,shielding-cap-gas-commercial-designation-test-piece,shielding-cap-flux-test-piece,shielding-cap-flux-commercial-designation-test-piece,wps,written-by,weld-type-approval-range,welding-process-root-approval-range,welding-process-fill-approval-range,welding-details-test-piece,welding-details-approval-range,welding-position-root-approval-range,welding-position-fill-approval-range,arc-transfer-mode-root-approval-range,arc-transfer-mode-fill-approval-range,type-current-root-approval-range,type-current-fill-approval-range,base-material1-approval-range,base-material2-approval-range,preparation-methods-test-piece,filler-material-root-commercial-designation-approval-range,filler-material-fill-commercial-designation-approval-range,shielding-root-gas-approval-range,shielding-root-gas-commercial-designation-approval-range,shielding-root-flux-approval-range,shielding-root-flux-commercial-designation-approval-range,shielding-fill-gas-approval-range,shielding-fill-gas-commercial-designation-approval-range,shielding-fill-flux-approval-range,shielding-fill-flux-commercial-designation-approval-range,backing-gas-approval-range,backing-gas-commercial-designation-approval-range,backing-flux-approval-range,backing-flux-commercial-designation-approval-range,tensile-test-lines,bend-test-lines,impact-test-lines,hardness-test-lines,groove-designs,weld-layer-configurations,process-mecanization-root-approval-range,process-mecanization-fill-approval-range,welding-process-cap-approval-range,arc-transfer-mode-cap-approval-range,process-mecanization-cap-approval-range,welding-position-cap-approval-range,type-current-cap-approval-range,filler-material-cap-commercial-designation-approval-range,shielding-cap-gas-approval-range,shielding-cap-gas-commercial-designation-approval-range,shielding-cap-flux-approval-range,shielding-cap-flux-commercial-designation-approval-range,special-requirements,welders,welding-parameters'
    });
```

EDIT2: Ok, so It seems this might not just related to EmberJS as I was using Chrome/Firefox and this happens. I tried Opera/Safari and it all works. If I bring down my "include" parameter to be around 2500 chars it works on all of them, if I go pass that (l go to 2570/2600 it breaks on Chrome/Firefox but not on Safari/Opera).

Now the bigger issue is that I have my app on production working (with Ember 3.12), and I'm running locally with Ember 3.12 (with updates on other dependencies as well) and it's not working. Really confused here... Investigation continues.

**Comment by pzuraq** [comment]
Can you clarify if this issue appeared due to the _Ember_ upgrade, or due to the _Ember Data_ upgrade? This seems like it may belong on the Ember Data issue tracker.

**Comment by corrspt** [comment]
Initially I thought it was ember data. So I downgraded just ember data (to 3.12) but it didn’t work as well. So I downgraded ember to 3.12 and it worked again. Then I tried upgrading ember to 3.13 all the way to 3.17 (one version at a time) but without success (keeping ember data at 3.12)

Now I’m currently on ember 3.12/data3.12 and cli 3.12

Thanks for looking at my issue

**Comment by pzuraq** [comment]
Ok, good to know. Will try to dig in as soon as we have time.

**Comment by corrspt** [comment]
Thanks @pzuraq. I'll try to add more information tomorrow (I've updated with the actual offending code on my `model()` hook.)

**Comment by corrspt** [comment]
Made another edit... situation is stranger. Looking into it.

**Comment by corrspt** [comment]
Hold off any looking into this issue. I now have been able to fix the issue of long urls with Private Windows of Chrome/Firefox (not sure why, though)

**Comment by corrspt** [comment]
Ok,  I'm closing this. Sorry for the trouble. 
I still don't know what happened, but I've been able to upgrade to Ember 3.13 (had to downgrade to Data 3.12, but I'll get to it when I can:).
