### ISSUE TITLE
component keyword regression starting in 3.17

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember.js#18881]
This is either a regression or an undefined behaviour becoming defined. I have a dummy app template using `component` as a variable name. Starting in 3.17, it now throws with

```
Error: Expected block head to be a string, got [27,[24,2],[]] opcode-compiler.js:2107
    expectString opcode-compiler.js:2107
```

https://github.com/ember-vr/ember-aframe/blob/f1c61c841e/tests/dummy/app/templates/components/primitive-list.hbs#L10

https://github.com/ember-vr/ember-aframe/pull/246

working before https://travis-ci.org/github/ember-vr/ember-aframe/builds/676621337
failing after https://travis-ci.org/github/ember-vr/ember-aframe/builds/676621605
after workaround https://travis-ci.org/github/ember-vr/ember-aframe/builds/676629183

**Comment by rwjblue** [comment]
Ya, this definitely seems like a bug to me. If you have a block param named `component` it should **definitely** "win" out over the built in `{{component` helper.

**Comment by rahulk94** [comment]
We've also run into this when upgrading to Ember 3.20.x. I've checked out our trunk and only upgraded to Ember 3.17.0 and still run into this.
```
Uncaught (in promise) Error: Expected call head to be a string, got [27,[24,15],[]]
    at expectString (opcode-compiler.js:2354)
    at opcode-compiler.js:960
    at ExpressionCompilers.compile (opcode-compiler.js:897)
    at expr (opcode-compiler.js:1168)
    at pushResolutionOp (opcode-compiler.js:1077)
    at concatExpressions (opcode-compiler.js:1308)
    at concatExpressions (opcode-compiler.js:1303)
    at concatExpressions (opcode-compiler.js:1303)
    at pushResolutionOp (opcode-compiler.js:1071)
    at concatExpressions (opcode-compiler.js:1308)
...
```

It appears to be a very similar issue, if not the same root cause.

**Comment by rahulk94** [comment]
Ignore me... found the issue root cause of our issue was someone putting `@not` instead of `not` in our templates... 🤦🏾‍♂️ the Ember upgrade to 3.17 highlights this whereas 3.16 doesn't, I'm assuming because it has more stringent checks in place.
