### ISSUE TITLE
Should not transform a block param named `action` to receive arguments

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#18901]
Given this template:

```hbs
{{#let "foo" as |action|}}
  {{action}}
{{/let}}
```

We will get an error because of this code:

https://github.com/emberjs/ember.js/blob/39bfa9a9e0ca3ce7ba2c73e9844e4202dec1e774/packages/ember-template-compiler/lib/plugins/transform-action-syntax.ts#L36-L54

This is transforming modifier and helper usages to add a `this` argument (that is how `{{action 'foo'}}` "magically" has access to `this`.

---

We should update this AST transform to track block params properly (to avoid wrapping a yielded block param).

**Comment by locks** [comment]
Fixed!
