### ISSUE TITLE
Create an Issue Template for the project

### ISSUE THREAD

**Issue by alexeykostevich** [emberjs/ember.js#18906]
According to the project's [Community Profile](https://github.com/emberjs/ember.js/community), the repository setup can be improved to match the recommended community standards. 

<img width="756" alt="Screen Shot 2020-04-21 at 11 51 57 pm" src="https://user-images.githubusercontent.com/5205189/79873966-235d5200-842b-11ea-8ec6-45ab8ad4d6ca.png">

One of the valuable improvements can be creating an [Issue Template](https://help.github.com/en/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests) to encourage useful issues, simplify reporting and subsequent investigation.

Here are some examples from other repositories:
- [microsoft/TypeScript](https://github.com/microsoft/TypeScript/issues/new/choose)
- [angular/angular](https://github.com/angular/angular/issues/new/choose)
- [aurelia/aurelia](https://github.com/aurelia/aurelia/issues/new/choose)
- [telerik/kendo-angular](https://github.com/telerik/kendo-angular/issues/new/choose)

The template can be potentially used across the whole organization (e.g. for Ember Data and Ember CLI, etc.).

**Comment by alexeykostevich** [comment]
Here is a draft version of a bug template based on the examples above and Ember's [CONTRIBUTING - Reporting a Bug](https://help.github.com/en/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests) doc.

```
<!---
Thank you for filing your contribution! Before you create a new issue, please search for similar issues. It's possible somebody has encountered this bug already.
-->

## 🐛 Issue Description


## 🤔 Expected Behavior


## 😕 Current Behavior


## 🔬 Minimal Reproduction
<!--
Please, provide minimal reproduction of the issue using one of the following:
- Ember Twiddle: http://ember-twiddle.com/
- JSBin: http://emberjs.jsbin.com/
- Create a GitHub repository: https://guides.emberjs.com/release/getting-started/quick-start/
-->


## 🌍 Environment

- Ember version: -
- OS: -
- Browser: -
- NPM/Node/Yarn: -
```

**Comment by rwjblue** [comment]
Seems like a great suggestion! Mind sending a PR?

**Comment by alexeykostevich** [comment]
Thank you, @rwjblue ! I'll create a PR today/tomorrow.

**Comment by alexeykostevich** [comment]
@rwjblue , I've created a PR. Please, let me know if you have any concerns.

When we the templates are adapted, it might make sense to integrate them into other Ember repositories (Ember Data, Ember CLI, Ember Inspector, etc.) with some project-specific adjustments.
