### ISSUE TITLE
Issue with the getting started quick start guide

### ISSUE THREAD

**Issue by sant0shg** [emberjs/ember.js#18940]
I am following the getting [started quick start guide](https://guides.emberjs.com/release/getting-started/quick-start/)

I have created the ember app, and generated the route of scientists as well. But in the guide, it is mentioned that after defining the model and the route of scientists, the list would be available in the `/scientists` route.
But for me, the `@model` is undefined in the template file of `scientists` (`scientists.hbs`). 

*router.js*
```
...
Router.map(function() {
  this.route('scientists');
});
...
```

*scientists.js*
```
import Route from '@ember/routing/route';

export default class ScientistsRoute extends Route {
  model() {
    return ['Marie Curie', 'Mae Jemison', 'Albert Hofmann'];
  }
}
```

*scientists.hbs*
```
<h2>List of Scientists</h2>
{{log "model" @model}} <!-- this returns undefined, and list is not rendered -->
<ul>
  {{#each @model as |scientist|}}
    <li>{{scientist}}</li>
  {{/each}}
</ul>
```

**Comment by sant0shg** [comment]
Its version mismatch. I was seeing the latest guide, while CLI installed an older version(don't know why I followed the steps and thought it had the latest CLI installed as the. guide). Sorry.

**Comment by locks** [comment]
Sorry you ran into a problem, but I'm glad you sorted it out!
