### ISSUE TITLE
super function not correctly bound with action decorator on Edge 18

### ISSUE THREAD

**Issue by manufitoussiwit** [emberjs/ember.js#18955]
Hello, 

I have a glimmer component and a sub component class with a function overided like this :
```js

class BaseClass extends Component {
  @action
  doSomething() {
    // something.
  }
}

class SubClass extends BaseClass {
  @action
  doSomething() {
    super.doSomething();
    // something else.
  }
}
```
In Edge v18 and less, the super function is not bound to an instance of BaseClass (i think it is bound to the prototype). 
When i remove action decorator on BaseClass, i have the good behavior...

In all other browsers and Edge chromium, it's ok.

**Comment by rwjblue** [comment]
Hmm, this is pretty odd. Some questions:

* What are you `config/targets.js`?
* Is this the same in dev vs prod builds?
* Can you share the transpiled output of both files?

**Comment by dcyriller** [comment]
@rwjblue I think I ran into this issue using the addon `ember-link` (more details in link just above). I could reproduce the issue with ember-source v3.20.5 and v3.22.0 in Edge <= 18.

#### Questions

> What are you config/targets.js?
```
  ["Edge >= 16", ...],
```
> Is this the same in dev vs prod builds?

yes I have the issue with both dev and prod builds

> Can you share the transpiled output of both files?

#### [a method in a base class](https://github.com/buschtoens/ember-link/blob/8f0fab3428b9a06d9e61f3ecf75286d68f2e40b0/addon/link.ts#L220-L228)
```js
export default class Link {
  @action
  transitionTo(): Transition {
    return this._linkManager.router.transitionTo(...this._routeArgs);
  }
}
```
will be transpiled to:
```js
  var Link = (_dec4 = Ember._tracked, _dec5 = Ember._action, _dec6 = Ember._action, (_class3 = (_temp2 = class Link {
    transitionTo() {
      return this._linkManager.router.transitionTo(...this._routeArgs);
    }
  }, _temp2), (_descriptor2 = _applyDecoratedDescriptor(_class3.prototype, "_params", [_dec4], {
    configurable: true,
    enumerable: true,
    writable: true,
    initializer: null
  }), _applyDecoratedDescriptor(_class3.prototype, "transitionTo", [_dec5], Object.getOwnPropertyDescriptor(_class3.prototype, "transitionTo"), _class3.prototype), _applyDecoratedDescriptor(_class3.prototype, "replaceWith", [_dec6], Object.getOwnPropertyDescriptor(_class3.prototype, "replaceWith"), _class3.prototype)), _class3))
```
#### [a method using super in a sub class](https://github.com/buschtoens/ember-link/blob/8f0fab3428b9a06d9e61f3ecf75286d68f2e40b0/addon/link.ts#L276-L283)
```js
export class UILink extends Link {
  @action
  transitionTo(event?: Event | unknown): Transition {
    this.preventDefault(event);
    return super.transitionTo();
  }
}
```
will be transpiled to:
```js
var UILink = (_dec = Ember._tracked, _dec2 = Ember._action, _dec3 = Ember._action, (_class = (_temp = class UILink extends Link {
    transitionTo(event) {
      this.preventDefault(event);
      return super.transitionTo();
    }
  }, _temp), (_descriptor = _applyDecoratedDescriptor(_class.prototype, "_params", [_dec], {
    configurable: true,
    enumerable: true,
    writable: true,
    initializer: null
  }), _applyDecoratedDescriptor(_class.prototype, "transitionTo", [_dec2], Object.getOwnPropertyDescriptor(_class.prototype, "transitionTo"), _class.prototype), _applyDecoratedDescriptor(_class.prototype, "replaceWith", [_dec3], Object.getOwnPropertyDescriptor(_class.prototype, "replaceWith"), _class.prototype)), _class));
```

**Comment by rwjblue** [comment]
Hmm, conceptually it is still being transpiled to use native `super.transitionTo` which means this is _probably_ a browser bug. 🤔

**Comment by dcyriller** [comment]
makes sense, thanks for having a look a it

**Comment by rwjblue** [comment]
I think you could get around the issue by either forcing `class` to be transpiled down (e.g. adding `ie 11` to targets) or not calling `super` and doing it how you'd do it in pre-class days:

```js
export class UILink extends Link {
  @action
  transitionTo(event?: Event | unknown): Transition {
    this.preventDefault(event);
    return Link.prototype.transitionTo.call(this, event);
  }
}
```

**Comment by rwjblue** [comment]
Given those work arounds, and that this is no longer an issue with current Edge versions I'm going to close...

**Comment by Turbo87** [comment]
@rwjblue I've just tried out the proposed workaround in https://github.com/buschtoens/ember-link/pull/519, but it does not seem to work. when using `Link.prototype.transitionTo.call(this)` the `this` that is arriving in the parent class method implementation is for some weird reason not the same `this` that we pass into the `call()` call. It seems like the `@action` modifier on the parent class is doing something to `this` which prevents `call(this)` from working correctly.
