### ISSUE TITLE
updateComponent hook bug with {{each}} helpers in v3.18

### ISSUE THREAD

**Issue by sandydoo** [emberjs/ember.js#18968]
Live reproduction of both versions: https://sandydoo.github.io/ember-test-update-hook-rendered/ 
Reproduction repo: https://github.com/sandydoo/ember-test-update-hook/

**TL;DR** In v3.18, the `updateComponent` hook is called on every nested component in an `{{each}}` and `{{each-in}}` helper when a single element or key/value pair is modified.

I've been testing out a custom component manager with the `updateHook` enabled.

```js
capabilities = capabilities('3.13', {
    updateHook: true // <- Hook enabled
});
```

The `updateComponent` hook behaves strangely with `{{each}}` and `{{each-in}}` helpers.

If I render a custom component for every element in an array and append/remove an element, then the `updateComponent` hook is called on every component in the array.

If I render a TrackedMap and modify a single key/value pair, then the hook is called on every single component **except** for the one actually modified.

Here are the test examples:

### Modify a value in a TrackedMap

v3.16: the `updateComponent` hook is called on the one component whose key/value pair was modified. 👍 
v3.18: the `updateComponent` hook is called on every single key/value pair in the TrackedMap **except** for the one modified. 👎 

```hbs
<button class="button" {{on 'click' this.updateMap}}>Update</button>

{{#each-in this.testMap as |key value|}}
  {{!-- Just displays the key and value --}}
  <Test @key={{key}} @value={{value}} />
{{/each-in}}
```

### Append to an Ember array

v3.16: the `updateComponent` hook is not called. 👍 
v3.18: the `updateComponent` hook is called for every single existing component. 👎 

```hbs
<button class="button" {{on 'click' this.updateArray}}>Update</button>

{{#each this.testArray as |value key|}}
  <Test @key={{key}} @value={{value}} />
{{/each}}
```

Links to a reproduction of the issue are at the top.
Not yet sure if this is specific to custom component managers or a more general issue.

**Comment by rwjblue** [comment]
This is likely another result from the rendering engine update in 3.17, the entire iterable system was revamped (we’ve already fixed a few bugs in this space in 3.18.1).

@sandydoo - Do you think you could try to put together a failing test case here (or in glimmer-vm)? It would probably make it a bit easier for us to dig in...

@pzuraq - would you mind reviewing? Maybe the specific symptoms might jump out at you and point to the culprit...

**Comment by sandydoo** [comment]
@rwjblue I've added [two failing test cases](https://github.com/sandydoo/ember.js/tree/add-update-hook-test-case) to the component manager test suite: modifying a key/value pair in an object and pushing an item to an array. They pass on v3.16.8 and fail on v3.18.1.

**Comment by sandydoo** [comment]
### Update

I can replicate this with render modifiers as well.

v3.16.8: The `{{did-update}}` modifier is *not* triggered when pushing to the array.
v3.18.1: The `{{did-update}}` modifier is triggered for every existing rendered value when pushing to the array.

```hbs
<button {{on 'click' this.updateArray}}>Update</button

{{#each this.testArray as |value index|}}
  <div {{did-update this.didUpdateElement index}}>{{value}}</div>
{{/each}}
```

```js
testArray = A();

@action
updateArray() {
  this.testArray.pushObject('test');
}

@action
didUpdateElement(_element, index) {
  console.log(`Updating ${index}`);
}
```

**Comment by rwjblue** [comment]
Awesome, thank you for those test cases!

**Comment by sandydoo** [comment]
Btw, I was digging around in glimmer-vm and something caught my eye. Now I could be totally off-track here, but is it possible that the check for whether the iterable item has actually changed was misplaced in the move to the new iterable system?

It seems like, either here or somewhere further upstream, we're forcefully marking the tag as dirty. Then, as the VM is going through its list of opcodes, it ends up calling the update component opcode, thinking that something has changed. The old property.ts file used to do a comparison between values before marking it as dirty. 🤷 

https://github.com/glimmerjs/glimmer-vm/blob/e8e2fc6f39a60baac2b72c1a19aea9585b162c47/packages/%40glimmer/reference/lib/template.ts#L310

**Comment by sandydoo** [comment]
Here's a simple test:

```hbs
{{#each this.list as |item|}}
  {{item}}
{{/each}}
```
```js
this.list = A(['one', 'two']);
// ...
this.list.pushObject('dynamic');
```

I've printed out the opcodes into the console. Notice the `lastRevision`.

**v3.16.8** Existing items aren't marked as dirty. Revision is not bumped.
![3 16-ish](https://user-images.githubusercontent.com/7572407/81960783-23133980-961a-11ea-81b0-a49dfd0d9f4a.jpg)

**v3.18.1** Existing items *are* marked as dirty. All items now at revision 6.
![3 18](https://user-images.githubusercontent.com/7572407/81960790-27d7ed80-961a-11ea-9b9c-c753a3d58aeb.jpg)

**Comment by sandydoo** [comment]
So the following works https://github.com/sandydoo/glimmer-vm/commit/4a3613ffa2f9be76fa1757c363c14419355f5635, but it will break a bunch of Glimmer tests. [These were ported from Ember's test suite ](https://github.com/emberjs/ember.js/blob/v3.16.8/packages/%40ember/-internals/glimmer/tests/integration/syntax/each-test.js) and obviously no longer use Ember arrays or `set` to update values. As a result, any test that modifies a value in an array of objects fails; it is not longer forcefully updated. [Here's an example of what I mean.](https://github.com/glimmerjs/glimmer-vm/blob/8d9cbb74b78be99af8355e651c2072f0be6bed9a/packages/%40glimmer/integration-tests/lib/suites/each.ts#L175)

Anyways, not much else I can do. Are these iterable items intentionally updated, but are now triggering side-effects (like did-update callbacks) back in Ember? Or are we just missing an equality check? Need a review from someone working on the vm.

Any thoughts, @rwjblue & @pzuraq?

**Comment by pzuraq** [comment]
@sandydoo sorry just getting to this today. I think you are correct there, and I can't currently remember why that changed during the update - looking back, Iterables definitely used to check the value of the reference before dirtying it.

The tests in the VM I think are wrong here, part of the mismatch between Ember.js and the test internals. You're correct, they don't have a set function or another way of tracking. I'm going to add a `@tracked` decorator to the test helpers, because we should be unifying the test behavior so it reflects the actual embedding environment moreso.

Thanks for all the work here, it would have taken me a while to follow this all the way down! This has been a huge help 😄

**Comment by sandydoo** [comment]
@pzuraq Awesome! I'm glad this was useful 😄
