### ISSUE TITLE
input helper does not accept aria-label

### ISSUE THREAD

**Issue by seemajune** [emberjs/ember.js#18977]
https://dequeuniversity.com/rules/axe/3.5/label?application=RuleDescription

adding @aria-label to this helper does not add the attribute to the DOM.

**Comment by locks** [comment]
When specifying HTML attributes you should not prefix with `@`. I tried like this and it seems to work:

```
<Input aria-labelledby="temperature low">
```

Let us know if you have further troubles!

**Comment by seemajune** [comment]
> When specifying HTML attributes you should not prefix with `@`. I tried like this and it seems to work:
> 
> ```
> <Input aria-labelledby="temperature low">
> ```
> 
> Let us know if you have further troubles!

Thanks for your quick reply, Ricardo 🙂
When using angle brackets with dynamic values w/out the decorator, aria-label={{ariaLabel}}, will cause a template error.

**Comment by seemajune** [comment]
one more thing, aria-labelled by should only be used in conjunction with an id elsewhere on the page.

**Comment by locks** [comment]
What error did you get? I could not reproduce

**Comment by seemajune** [comment]
> What error did you get? I could not reproduce

you're a lifesaver! apologies, i just tried aria-label again and i didn't get the error. must have been rushing. thank you for looking into this!

**Comment by locks** [comment]
Happy to help! 😁
