### ISSUE TITLE
_EmberAssign not defined

### ISSUE THREAD

**Issue by poplevente** [emberjs/ember.js#18992]
Hi Guys,

since yesterday we are getting the following error after build, during runtime.

ReferenceError: _EmberAssign is not defined

was something changed or are we missing something?

we are using:
Ember            : 3.12.3
Ember Data       : 3.12.2

thanks!

**Comment by lukemelia** [comment]
I'm seeing a similar thing since yesterday in ember-keyboard builds against ember 3.8 and 3.12 ember-try configs but with _EmberObject instead of _EmberAssign.

**Comment by rwjblue** [comment]
Almost certainly related to the Babel release yesterday. We are going to have to actually fix the issue with our reference rewriting.

**Comment by rwjblue** [comment]
Sorry, I meant to cross link. 

https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/issues/64

**Comment by poplevente** [comment]
@rwjblue thanks. is there a quick fix, or we shall wait for your inhouse fix?

**Comment by rwjblue** [comment]
ember-cli-babel@7.20.1 was just released, and should fix the underlying issue.

https://github.com/babel/ember-cli-babel/releases/tag/v7.20.1

**Comment by poplevente** [comment]
it's far to be fixed. i'm also getting the same error as other is the other topic 
Update babel-plugin-ember-modules-api-polyfill to fix issues with invalid identifiers. #338

`Build Error (broccoli-persistent-filter:Babel > [Babel: @ember-data/store]) in -private/system/model/internal-model.ts

C:\projects\bluedolphin\-private\system\model\internal-model.ts: Property left of TSQualifiedName expected node to be of a type ["TSEntityName"] but instead got "MemberExpression"`
