### ISSUE TITLE
[Bug] Build Error (broccoli-persistent-filter:Babel > [Babel: @glimmer/component]) in @glimmer/component/-private/ember-component-manager.ts

### ISSUE THREAD

**Issue by kredde** [emberjs/ember.js#18995]
I am getting the same build error across all my repositories
```
Build Error (broccoli-persistent-filter:Babel > [Babel: @glimmer/component]) in @glimmer/component/-private/ember-component-manager.ts
```

Reproduction:

Create a new ember project `ember new ember-quickstart`  and run `ember start`

- Ember: 3.17.0

**Comment by tzellman** [comment]
I see the same error in an existing 3.19 project where `renovatebot` attempted to bump `ember-cli-babel`.

![image](https://user-images.githubusercontent.com/174619/83256270-27923300-a180-11ea-99c7-18e55afa3027.png)

**Comment by rwjblue** [comment]
Oiy. Sorry about that y’all. This is related to a fix that I landed in `babel-plugin-ember-modules-api-polyfill` last night. I’m digging in to see what is going on (and decide if we should revert or fix forward).

**Comment by rwjblue** [comment]
https://github.com/babel/ember-cli-babel/releases/tag/v7.20.2 is out with the fix for the TS issue (thank you @fivetanley!).
