### ISSUE TITLE
`get` helper doesn't work with Map

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#19007]
In `controllers/application.js`:

```javascript
export default class ApplicationController extends Controller {
  x = new Map();
  y = {};

  constructor() {
    super(...arguments);
    this.x.set("a", 1);
    this.y.a = 1;
  }
}
```

In `templates/application.hbs`:

```hbs
{{log (get this.x "a")}}
{{log (get this.y "a")}}
```

The first logs `undefined`, the second - `1`.

I see no reason for this to not work.

**Comment by rwjblue** [comment]
The `get` helper is an analogue for `Ember.get`, which does not have special behavior for `Map`. 

This could plausibly be a feature request (should move it to emberjs/rfcs repo though), but it’s definitely not a bug.
