### ISSUE TITLE
Using the Evented mixin in an Ember Octane class

### ISSUE THREAD

**Issue by yoavfranco** [emberjs/ember.js#19019]
Hello!
We've just migrated to Ember 3.18 and are looking for a way to use Ember Eveneted functionality.
However, as recommended, we're trying to move away from mixins altogether and are looking for a way to incorporate Evented functionality in an Octane class.

Can you please advise on a proper implementation using Evented on Octane components?

Thanks in advance
Yoav

**Comment by rwjblue** [comment]
I think the only mechanism you have available is to use the mixin, or don't use `Ember.Evented` itself (e.g. use a third party evented system, which are quite common on NPM).

**Comment by rwjblue** [comment]
At some point, our internal mixins will likely either be deprecated or migrated to a non-mixin style API. We haven't settled on a path forward for that just yet, and its perfectly safe to continue to use the Ember provided mixins in the meantime.

**Comment by taltcher** [comment]
The question is - how can we use them on glimmer components? since we can extend only from one class?

**Comment by richard-viney** [comment]
Mixins are discouraged when writing new code these days as they will probably be deprecated in future and don't work well with native classes as you point out. There's no real need to rely on Ember for evented functionality though, so one can instead use an NPM library which provides this kind of functionality, e.g.:

* https://github.com/primus/eventemitter3#readme
* https://github.com/ai/nanoevents

**Comment by taltcher** [comment]
I see - and using them inside ember components by adding event listeners in the components themselves? (and removing them once the component gets destroyed)?

**Comment by richard-viney** [comment]
Exactly, previous calls to `off()` would be replaced with whatever call is needed to remove an event listener in the library that you're using.

**Comment by richard-viney** [comment]
@taltcher Did that work for you? And if so, can we close this issue?

**Comment by yoavfranco** [comment]
@richard-viney We'll test this and come back with a reply very soon.
Thanks for the patience 🙏

**Comment by yoavfranco** [comment]
@richard-viney We started to use [ember-render-modifiers](https://github.com/emberjs/ember-render-modifiers) and it's amazing :)
You can close this issue.
Thanks for the help!

**Comment by locks** [comment]
Thanks for the update, I'll close it!
