### ISSUE TITLE
Provision to prevent child route executions from parent route.

### ISSUE THREAD

**Issue by chendraayan** [emberjs/ember.js#19014]
`{{outlet}}` helper lets us to display and position the child route templates. Without the helper, child route templates are not rendered. Say if I have the `{{outlet}}` helper in a conditional block in the parent route template like the following, I can stop rendering the child route templates, but cannot stop the execution of the child route hooks.

```
{{!-- parent.hbs --}}
{{#if showChildRoutes}}
    {{outlet}}
{{else}}
    ....
{{/if}}
```

In my opinion, the order of execution of routes is similar to that of browser events which has child->parent order of bubbling. Child can decide whether the event should be bubbled to the parent or not. 
Likewise, Ember routes has parent->child order of execution and the parent route should be able to stop the execution of the child routes

**Comment by rwjblue** [comment]
I'm not sure I follow what the suggestion here is concretely, but it does seem pretty clear that this is _basically_ a feature request (not a bug which is what we keep in this issue tracker).

Mind making an issue over in emberjs/rfcs to kick off a conversation about your proposal?
