### ISSUE TITLE
ambiguous debug log in console

### ISSUE THREAD

**Issue by houfeng0923** [emberjs/ember.js#19017]
ember 3.16.8,  i have a trouble in development. 

when i declare a action in hbs like `{{xxxx onShow=(action 'action1') }}` and there is no `action1` existed (or maybe i had a spell mistake on it) .the debug info can't help me to resolve the problem。 

and this log is not only appear in this case。 

```
vendor.js:48600 Uncaught Error: Assertion Failed: BUG: expecting [object Object], got [object Object]
    at assert (vendor.js:48600)
    at DebugRenderTree.didRender (vendor.js:18379)
    at OutletComponentManager.didUpdateLayout (vendor.js:18842)
    at DidUpdateLayoutOpcode.evaluate (vendor.js:61423)
    at UpdatingVM.execute (vendor.js:63783)
    at RenderResult.rerender (vendor.js:64101)
    at RootState._this23.render (vendor.js:19985)
    at runInAutotrackingTransaction (vendor.js:26682)
    at InteractiveRenderer._renderRoots (vendor.js:20287)
    at InteractiveRenderer._renderRootsTransaction (vendor.js:20325)
```
![image](https://user-images.githubusercontent.com/1825420/84978543-c72f5980-b15f-11ea-8088-1379c10b19d6.png)

**Comment by chancancode** [comment]
Was this the *only* error you got in the console? Was there another error shown prior to this?

**Comment by rwjblue** [comment]
Ya, _in general_ the error you see there happens after some earlier thing throws an error (and therefore the debug render tree stack is not maintained properly).

**Comment by houfeng0923** [comment]
@chancancode  @rwjblue  there are  two many same errors in console. 
now i try to only reproduce this by missing action ,but the error info is exact. 
it happened after lots files change and saved, now sorry i am not sure how to reproduce it.  

I will keep looking at how to reproduce it.

**Comment by houfeng0923** [comment]
when type a mistake `angle bracket` name  like: `<Common:InlineButton>` (the right is <Common::InlineButton>),

debug log like below:

```
Uncaught (in promise) Error: Assertion Failed: fullName must be a proper full name
    at assert (vendor.js:48600)
    at Registry.expandLocalLookup (vendor.js:13355)
    at Registry.expandLocalLookup (vendor.js:13361)
    at Container.factoryFor (vendor.js:12443)
    at Class.factoryFor (vendor.js:39826)
    at componentFor (vendor.js:24461)
    at lookupComponentPair (vendor.js:24470)
    at lookupComponent (vendor.js:24497)
    at RuntimeResolver._lookupComponentDefinition (vendor.js:24778)
    at RuntimeResolver.lookupComponentHandle (vendor.js:24623)
```

![image](https://user-images.githubusercontent.com/1825420/85500922-f8ec6880-b616-11ea-9eea-6bbe938ab9e8.png)

**Comment by rwjblue** [comment]
> when type a mistake angle bracket name like: <Common:InlineButton> (the right is Common::InlineButton),

This seems quite a bit different from the first issue...

**Comment by houfeng0923** [comment]
@rwjblue 😂

ye, it seems to be so .  but i have the same trouble in debugging what's the reason .

now i upgrade 3.16 from 3.3, i have more puzzle in those console error informations.
it will be more great if the debug info more friendly .


- [error angle bracket twiddle case](https://ember-twiddle.com/3447ae857246048da095d3de3f0204ed?openFiles=templates.application%5C.hbs%2Ctemplates.components.common.hard-spell-component%5C.hbs)

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. 

This seem like more of a question than a bug report/issue, and therefore better suited for the forums: https://discuss.emberjs.com/

Also, the reality for any open-source framework, relying on individuals to put in the work, is that there isn't always time to answer all questions.

If you want to pay back to the community, one easy thing is to ask one question in the forum (your current one), and also try to answer 2 questions from other people.

If you think this is an error, a reproduction of the bug and a more extensive explanation would be a good start. Then, if others agree it's a bug, the second step is often to dig in and write a patch to fix the bug.

I'll be closing this for now though, to keep the list of open issues manageable. I hope you understand.
