### ISSUE TITLE
[Beta] Named blocks empty void

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#19016]
### 🐞 Describe the Bug
Imagine a component:

```handlebars
<Modal as |modal|>
  {{log modal}}

  {{! stuff here gets lost in the ether }}

  <:header>
    Title
  </:header>

  <:content>
    Hello World
  </:content>

  <:footer>
    <button type="button" {{on "click" modal.close}}>
      Close
    </button>
  </:footer>

</Modal>
```
...log is not output, but it's more than just that...

### 🔬 Minimal Reproduction
See above code

### 😕 Actual Behavior
No log

### 🤔 Expected Behavior
* I would expect log to log out.
* I would also expect the default yield `|modal|` to work
   But, if there is one or more `<:namedblock>`, then anything outside of those named blocks gets swallowed.

As you can see in the above use case, it does not make sense to yield 3 separate APIs (one for header, content and footer). And it also doesn't make sense to yield the same API 3 times.

### 🌍 Environment

- Ember: 3.20.0-beta.2
- Node.js/npm: -
- OS: -
- Browser: -

### ➕ Additional Context
1. Sorry for bad title, not sure how to describe this.
2. This is a component being migrated from using child components, like `<modal.Header>` to named blocks `<:header>` to simplify its codebase and usage.
3. Side note: This particular example outputs `BUG: Attempted to create a log for a path reference, but no node exist for that reference` (which isn't particularly helpful). It happens because `model.close` is undefined.

**Comment by rwjblue** [comment]
In your example, you have `{{log` invocation in the root of the block. When using named blocks, you can _only_ pass named blocks. If we find _any_ other content (other than white space,  comments, or named blocks to be passed) we should be either erroring or bailing out of named block mode (I think). It seems that we aren’t?

**Comment by amk221** [comment]
> we should be either erroring or bailing out of named block mode (I think). It seems that we aren’t?

Ok, I'll let higher powers decide :)

> When using named blocks, you can only pass named blocks

In that case, it seems the 'win' I thought named blocks were going to give me is undermined by the inability to have that common api (see point 3 in Additional Context)

**Comment by rwjblue** [comment]
@chancancode can you confirm my thoughts above?

**Comment by chancancode** [comment]
Yep this should be a syntax error (and is a syntax error in the polyfill)

**Comment by chancancode** [comment]
You _can_ have a `<:default as |modal|>` block, just that everything has to be declared using the named blocks syntax if you are going to use it.

**Comment by amk221** [comment]
Interesting thanks.. you can close if you want :)

**Comment by rwjblue** [comment]
Thanks for your patience here @amk221
