### ISSUE TITLE
add/remove input fields dynamically in emberjs

### ISSUE THREAD

**Issue by yksa** [emberjs/ember.js#19018]
When I press add button >> new input field added
When I press remove button >> added input field removed
I can do with traditional html input element but don't know with <PaperInput />

Template
`<button onclick={{action "add"}}> {{paper-icon "add_location"}}</button>
<button onclick={{action "remove"}}> {{paper-icon "wrong_location"}}</button>
<p id="para">
    <input /> To <input /> 
</p>
`

Controller
`@action
    add() {
        var br = document.createElement("BR");
        var input1 = document.createElement("INPUT");
        var input2 = document.createElement("INPUT");
        
        var para = document.getElementById('para');
        para.appendChild(br);
        para.appendChild(input1);
        para.appendChild(input2);
    }
@action
    remove() {
        
        var para = document.getElementById('para');
        var count = para.childElementCount;
        var j = 0;
        console.log(count);

        for (var i=count; i > 2; i--) {
            var lastChild = document.getElementById('para').lastChild;
            lastChild.remove();
            j++;
            if(j>2) break;
        }
    }
`

I want to know ember native way of adding removing ember paper input (<PaperInput />

**Comment by richard-viney** [comment]
I'd suggest an `isInputVisible ` boolean that you use in the template to conditionally render the extra elements.

The following code uses Ember Octane and requires Ember 3.13 or later.

Component JS:

```js
import Component from "@glimmer/component";
import { tracked } from "@glimmer/tracking";
import { action } from "@ember/object";

class MyComponent extends Component {
  @tracked isInputVisible;

  @action add() {
    this.isInputVisible = true;
  }

  @action remove() {
    this.isInputVisible = false;
  }
}
```

Component template:

```hbs
<button {{on "click" this.add}}> {{paper-icon "add_location"}}
<button {{on "click" this.remove}}> {{paper-icon "wrong_location"}}

<div id="para">
  <p>
    Content
  </p>

  {{#if this.isInputVisible}}
    <br>
    <input>
    <input>
  {{/if}}
</div>
```

Note: requests for help using Ember are best-suited for other platforms such as Ember's Discord Server.

**Comment by yksa** [comment]
Thanks for reply.
If I use "isInputVisible" boolean value, only one input element is visible/invisible. The problem is "I want to add more than one".

**Comment by richard-viney** [comment]
You can use an array and `{{each}}` in the template.

Framework usage questions like this don't really belong in this issue tracker, either https://discuss.emberjs.com or Ember's Discord Server are better places to ask these questions. There are also the guides at https://guides.emberjs.com/release/ which cover all of these topics and much more.

---

```js
import Component from "@glimmer/component";
import { tracked } from "@glimmer/tracking";
import { action } from "@ember/object";

class MyComponent extends Component {
  @tracked inputFields = [];

  @action add() {
    this.inputFields.pushObject({ name: "Test" });
  }

  @action remove() {
    this.inputFields.popObject();
  }
}
```

```hbs
<button {{on "click" this.add}}> {{paper-icon "add_location"}}
<button {{on "click" this.remove}}> {{paper-icon "wrong_location"}}

<p>
  Content
</p>

{{#each this.inputFields as |inputField|}}
  <p>
    {{inputField.name}}
  </p>
  <input>
{{/each}}
```

**Comment by yksa** [comment]
Ok, Thanks.
