### ISSUE TITLE
[Bug] activate hook doesn't receive transition as an argument

### ISSUE THREAD

**Issue by mehulkar** [emberjs/ember.js#19022]
The `activate` hook is called by the private `enter` method:

https://github.com/emberjs/ember.js/blob/v3.20.0-beta.2/packages/@ember/-internals/routing/lib/system/route.ts#L380-L384

which is called by the underlying router.js library

https://github.com/tildeio/router.js/blob/v6.2.5/lib/router/router.ts#L520

Passing along the `transition` would allow the activate hook to know if the _leaf_ route was activated (i.e. if `this.fullRouteName === transition.targetName`).

I'm not sure if this is an oversight or not, but it did not seem significant enough to file a feature request / RFC.

**Comment by rwjblue** [comment]
Hmm, seems reasonable to me. Not sure exactly why we didn't do that before 🤔. 

Wanna send in a pull request? Then I can add it to a future core team meeting agenda to 👍 / 👎
