### ISSUE TITLE
Uncaught TypeError when `<base>` tag doesnt have a `href` attribute 

### ISSUE THREAD

**Issue by emattias** [emberjs/ember.js#19038]
In storybook I get this error 

```
Uncaught TypeError: Cannot read property 'replace' of null
```

on this line

https://github.com/emberjs/ember.js/blob/d96d9aad52e010da977d813f479494397ee53ec6/packages/%40ember/-internals/routing/lib/location/history_location.ts#L124

because `baseUrl` is `null` and not a string like it look like that line is assuming.

The base tag looks like this (from [here](https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/templates/base-preview-head.html#L1)):

```html
<base target="_parent">
```

## solution suggestions

Would it work to change this line

https://github.com/emberjs/ember.js/blob/d96d9aad52e010da977d813f479494397ee53ec6/packages/%40ember/-internals/routing/lib/location/history_location.ts#L81

to

```js
      baseURL = base.getAttribute('href') || '';
```
or is there a problem with setting `baseUrl` to `''`?

**Comment by rwjblue** [comment]
Hmm, I think the more appropriate solution here would be to treat having a `<base>` without an `href` as having no `<base>` at all. What do you think?
