### ISSUE TITLE
[Bug] Existing query params lost when entering loading route

### ISSUE THREAD

**Issue by jrjohnson** [emberjs/ember.js#19039]
### 🐞 Describe the Bug

When an index-loading route is entered during a query param only transition the existing QPs are lost and only the newly set param is retained.

### 🔬 Minimal Reproduction
I've created a reproduction at https://github.com/jrjohnson/qp-replacement-loading-route-reproduction running the tests will show the failures. You can also navigate to the `broken` route and click the query param setting buttons.

### 😕 Actual Behavior
Setting a QP re-sets the existing params to their default value.

### 🤔 Expected Behavior
Setting a new param should not change existing params.

### 🌍 Environment

- Ember: - 3.19.0
- Node.js/npm: - v12.18.2 / 6.14.5
- OS: - OSX
- Browser: - Chrome / Firefox

### ➕ Additional Context
This was originally reported as a new issue with 3.13 by @jakebixbyavalara in https://github.com/emberjs/ember.js/issues/18683%23issuecomment-578919592 but I wasn't able to find a linked issue.

Tagging @pzuraq as he was involved in the original issue (and this is probably a result of tracked properties for QPs being introduced in 3.13).

**Comment by jrjohnson** [comment]
I'm no longer sure this is a 3.13 issue, I went all the way back to 2.18 and it still happens there. I've never had a loading route on both an index and main route before with query params so I'm not sure this has ever worked. It still reads as a bug to me, but maybe not a new one.

**Comment by rreckonerr** [comment]
Ran your reproduction on `3.27.0` and seems like it's already fixed
![Feb-13-2021 19-15-08](https://user-images.githubusercontent.com/30495731/107857650-52203b00-6e38-11eb-854c-b642e570664d.gif)

**Comment by jrjohnson** [comment]
Agreed! Working with 3.25.1 for sure. Thanks for updating!
