### ISSUE TITLE
[3.20] Deprecation warnings when using @glimmer/component

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#19042]
The current version of `@glimmer/component` (1.0.0) in `EmberGlimmerComponentManager.destroyComponent` calls `setSourceDestroying` which has been deprecated since Ember 3.20. So using Glimmer components in Ember 3.20 leads to a deprecation warning.

cc @rwjblue, @pzuraq

**Comment by rwjblue** [comment]
Thanks for reporting this (will help others to find it). The fix will be over in `@glimmer/component` (in glimmerjs/glimmer.js monorepo). I'm hoping to have a PR and release out in a couple hours.

**Comment by jordpo** [comment]
@rwjblue I wanted to make an attempt at the PR. I have no idea if anything else is needed and I did the ternary expression to support ember versions that don't have the new `meta` API. 

https://github.com/glimmerjs/glimmer.js/pull/292

**Comment by rwjblue** [comment]
Sorry for the delays here y'all, finally got https://github.com/glimmerjs/glimmer.js/pull/293 pushed up with the changes that I think are needed.

**Comment by jacobq** [comment]
> Sorry for the delays here y'all, finally got [glimmerjs/glimmer.js#293](https://github.com/glimmerjs/glimmer.js/pull/293) pushed up with the changes that I think are needed.

Looks like that PR is still awaiting merge. Is there a way this be used/tested right now or should I be waiting for another release (or perhaps the closure of this issue)?

**Comment by rwjblue** [comment]
Fix was just released in https://github.com/glimmerjs/glimmer.js/releases/tag/v1.0.1.
