### ISSUE TITLE
[Bug] Default initializer test shows globals-resolver deprecation

### ISSUE THREAD

**Issue by mehulkar** [emberjs/ember.js#19046]
### 🐞 Describe the Bug
Initializer tests logs deprecation warning for usage of `globals-resolver`.

### 🔬 Minimal Reproduction

```bash
ember new
ember g initializer foo
ember test --filter="initializer"
```

### 😕 Actual Behavior
A deprecation warning is logged

### 🤔 Expected Behavior
No deprecation should be logged for code the user has not written

### 🌍 Environment

- Ember: - 3.18 (pretty sure same behavior in later build too)

### ➕ Additional Context

The problem is that `Application.create()` is called with only the `autoboot: false` properties:

https://github.com/emberjs/ember.js/blob/v3.20.1/blueprints/initializer-test/qunit-rfc-232-files/__root__/__testType__/__path__/__name__-test.js#L15

Since a `Resolver` from ember-resolver is not passed, the DefaultResolver is used, which is the globals resolver. 

Either the default should change, or the right Resolver can be imported and passed into the test application in the blueprint.

**Comment by rwjblue** [comment]
Ya, we should update the test that is generated to add `import Resolver from 'ember-resolver'` and pass that to the .extend invocation.

**Comment by mehulkar** [comment]
@rwjblue that might be a quick fix, but is it possible to change the default resolver? I think I'm getting this deprecation from a couple other places as well that I haven't traced yet. I don't know what else changing the default here might break: https://github.com/emberjs/ember.js/blob/v3.20.1/packages/@ember/engine/index.js#L455

**Comment by rwjblue** [comment]
> @rwjblue that might be a quick fix, but is it possible to change the default resolver

No, changing the default would be a breaking change.
