### ISSUE TITLE
Checkbox checked state not immediately updated when using actions

### ISSUE THREAD

**Issue by aatauil** [emberjs/ember.js#19052]
### 🐞 Describe the Bug

I made a checkbox list with an [ All ] option at the top. When checking the [ All ] checkbox I attached an event listener with an action to it so that the rest of the items in the checkbox-list get checked. See Twiddle for example. 

The issue is that when I click the [ All ] checkbox and console log its value, it still shows the previous value. So if the [ All ] checkbox state was initially unchecked/false and I click the [ All ] checkbox expecting it now to console-log: "true" , then it does not change. But if I click it again expecting it to become "false" again, then it console-logs "true". 

The action basically triggers before the tracked value gets updated. 

### 🔬 Minimal Reproduction

Follow Ember guide for checkbox component & attach an event listener to it that triggers and action.
https://guides.emberjs.com/release/components/built-in-components/#toc_checkboxes

Please see the Ember Twiddle that I made 
- Ember Twiddle: https://ember-twiddle.com/6fea5d7bcbe0c9f970516e6c49c64471?openFiles=components.my-issue%5C.js%2C

### 😕 Actual Behavior

Checkbox state not updated before action fires

### 🤔 Expected Behavior

Checkbox value should update before action fires

### 🌍 Environment

- Ember: - 3.19
- Node.js/npm_: v12.18.2 / 6.13.6
- OS: - Windows 10
- Browser: - Chrome

### ➕ Additional Context

The two-way binding becomes obsolete in my eyes if you can not attach custom logic to the event. I highly doubt that this was intended and therefore label it as a bug.

**Comment by jonathannewman** [comment]
The state of the checkbox is available in the event associated with the action and avoids any timing issues with reading the bound value.  In your twiddle, if you change the simplified action handler to:
```
@action logState(event){
        console.log(event.target.checked);
  	console.log("Simplified checkbox state = " + this.checkedState)
  }
```
You will see the correct state being reflected in the event.    In your action handler in the more complex example, you can do the same.

**Comment by rwjblue** [comment]
Ya, I think the suggestion from @jonathannewman is the right path forward here. Specifically, the timing relationship between the DOM event (which is what `{{on 'change'` is going to be using) and when the two-way bound value is updated is not something that you can rely on.

**Comment by aatauil** [comment]
Thank you for clearing it up @jonathannewman. Of course, I hoped that the timing for the action & tracked value would be the other way around but your answer is also satisfying and I therefor close this issue. Thank you again
