### ISSUE TITLE
[Bug] Ember.onerror does not handle exceptions thrown in component action

### ISSUE THREAD

**Issue by skarger** [emberjs/ember.js#19053]
### Description
When an `action` throws an uncaught exception, `Ember.onerror` does not execute.

As shown by the demo app below, there are several other situations where `Ember.onerror` does not apply, for Promise rejections in various cases. Those may not be bugs? Overall it's unclear to me what `Ember.onerror` is supposed to cover and whether using it is a best practice.

### Reproduction
https://github.com/skarger/ember-on-error

![screenshot](https://user-images.githubusercontent.com/1040764/88212061-a0fc4e00-cc24-11ea-84b3-e4cb0499d91c.png)

### Environment

- Ember: - 3.19.0
- Node.js/npm: - 12.14.0
- OS: - darwin x64
- Browser: - Tested in Firefox 78.0.2 and Chrome 84.0.4147.89.

### Other Context
* Docs: https://guides.emberjs.com/release/configuring-ember/debugging/
* Potentially related issues:
  * https://github.com/emberjs/ember.js/issues/18818
  * https://github.com/emberjs/ember.js/issues/18533

**Comment by rwjblue** [comment]
Thanks for putting this together! We are chatting through this over in https://github.com/emberjs/ember-qunit/issues/592. This demo app is a good starting point for the evaluation of scenarios that I was mentioning in my recent comments over there.

I'm going to close this issue for now (don't want to bifurcate the conversation), but I fully expect for this to result in some changes here (even if just for API docs).
