### ISSUE TITLE
[Bug] "Error: Cycles in tags are not allowed" with queryParams

### ISSUE THREAD

**Issue by velrest** [emberjs/ember.js#19078]
### 🐞 Describe the Bug
If two `queryParams` are defined in a controller and both are set to `@tracked` and one is initiated with a default value of `[]` , the following error occurs:
`validator.js:294 Uncaught (in promise) Error: Cycles in tags are not allowed`

Both params are passed via `hash` to a component which then renders both. If one render call to either of those params is commented out, the error does not occur.

If the params are rendered directly in the `application.hbs` the error does not occur.

### 🔬 Minimal Reproduction
https://ember-twiddle.com/caa471592cc3e3b86a5e61857c99ea00?openFiles=templates.application%5C.hbs%2Ctemplates.components.my-component%5C.hbs
The twiddle has some cases which work and the initially described case which does not work.

### 😕 Actual Behavior
The template renders and an error occurs which then stops code execution.
### 🤔 Expected Behavior
The templates renders and no error is thrown.
### 🌍 Environment

- Ember: 3.18.1-
- Node.js/npm: 14.4.0-
- OS: Arch Linux-
- Browser: Chrome Version 83.0.4103.116 (Official Build) Arch Linux (64-bit)-

**Comment by rwjblue** [comment]
Seems like this is a duplicate of https://github.com/emberjs/ember.js/issues/18981, would you mind chiming in over there?
