### ISSUE TITLE
[Bug] Template Namespace Conflict When Using Pods

### ISSUE THREAD

**Issue by roomman** [emberjs/ember.js#19079]
### 🐞 Describe the Bug
We have encountered a template namespace conflict when:
* using Angle Bracket Invocation;
* using pods project layout; and
* a Route's template and Component's template share the same namespace.

### 🔬 Minimal Reproduction
[The issue has been reproduced here.](https://github.com/roomman/ember-bug-report-naming-conflict)

### 😕 Actual Behavior
When invoking `<Video::View>`, the 'video.view' Route's template is rendered.

### 🤔 Expected Behavior
When invoking `<Video::View>`, the 'component/video/view' template is rendered. 

### 🌍 Environment

- Ember: 3.20.0
- Node.js/npm: 10.15.3
- OS: darwin x64
- Browser: Safari 13.1.1

**Comment by rwjblue** [comment]
Unfortunately, I don't think we consider this a bug. This conflict is the result of the two things sharing the same general namespace and the fact that you aren't leveraging template colocation. You can work around this fairly handily by migrating your components and their templates into the colocation setup (which isn't terribly far from what you have):

You can either do this:

* `app/components/video/view/component.js` -> `app/components/video/view/index.js`
* `app/components/video/view/template.hbs` -> `app/componments/video/view/index.hbs`

Or this setup (only difference is no nested folder):

* `app/components/video/view/component.js` -> `app/components/video/view.js`
* `app/components/video/view/template.hbs` -> `app/componments/video/view.hbs`

Either of these should alleviate the issue you reported, **and** are nicely the default result of `ember g component` now :smile:.

**Comment by rwjblue** [comment]
Closing (as mentioned above, I don't think its a bug per-se) but happy to reopen if my suggestion turns out to be missing something (or wrong 😛).

**Comment by roomman** [comment]
Thanks @rwjblue, I really appreciate your feedback. You're not missing anything. 👍

**Comment by rwjblue** [comment]
Awesome, glad that worked for ya!
