### ISSUE TITLE
[Bug] set may silently fail in debug builds

### ISSUE THREAD

**Issue by elgordino** [emberjs/ember.js#19083]
### 🐞 Describe the Bug
When a key is `delete`ed from an object a subsequent `set` on that key may silently fail on debug builds.

It may not be possible to support `delete` in this manner in a debug build but Ember should throw an error rather than silently failing.

see discussion with @pzuraq  in discord: https://discordapp.com/channels/480462759797063690/608346628163633192/739042080785039360

### 🔬 Minimal Reproduction

Please see this twiddle: https://ember-twiddle.com/18fedf8eb39d87aff642dff06f5e870a?openFiles=controllers.application%5C.js%2C

When run you will see it throws on line 28 which is when `set` is called after `save` has run which deleted the key.

If you replace

    delete this._localAttributes.capacity;
        
with 

    set(this._localAttributes, 'capacity', undefined);

Then it will run successfully but the behaviour is not the same as they key remains in `_localAttributes`

### 😕 Actual Behavior
The call to `set`in line 26 of the twiddle fails to set a value when the key was previously deleted by line 12.

### 🤔 Expected Behavior
Ideally the `set` should set the value but if this is not possible then an exception should be thrown so they user knows they have something to address.

### 🌍 Environment

- Ember: - 3.12 and above (tested up to 3.20.2)
- Node.js/npm: -12.16.3
- OS: - Catalina
- Browser: - Chrome

**Comment by rwjblue** [comment]
I assume this only happens when the property in question was a dependent key in a computed property or observer? Specifically, it seems likely that the mandatory setter may ultimately cause the issue here...

**Comment by elgordino** [comment]
@rwjblue yes that's right. There is a computed property like this:

        @computed('_localAttributes.capacity', '_remoteAttributes.capacity')

**Comment by rwjblue** [comment]
@elgordino - Just confirming (since this seems like it would have been the behavior for quite a long time) that this isn't a new regression, right?

**Comment by elgordino** [comment]
@rwjblue It's been present since 3.13. I was upgrading my 3.12 app to 3.16 and hit the issue.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue.

Ember is moving away from set/get, towards native ES6 classes. So I'm going to close this.

By closing some old issues we reduce the list of open issues to a more manageable set.
