### ISSUE TITLE
[Bug] Ember 3.20.4 Does not Update When ED related records are removed

### ISSUE THREAD

**Issue by jrjohnson** [emberjs/ember.js#19105]
### 🐞 Describe the Bug
When records are removed from an ember data relationship the change is not being reflected in a template.

### 🔬 Minimal Reproduction
Reproduced in https://github.com/jrjohnson/reproduction-template-model-relationships
Steps: 
1) `npm start`
2) Visit http://localhost:4200/tests?devmode
3) Open Console
4) Clicking Add POSTs a new record and re-computes the count and then `{{log}}` output.
5) Clicking Clear PATCHs and removes the records, but does not update the count of the `{{log}}`.

### 😕 Actual Behavior
Removing all records from an Ember Data relationship array does not update the template.

### 🤔 Expected Behavior
Changing this array should always change the template.

### 🌍 Environment

- Ember: 3.20.4
- Node.js/npm: v12.18.2 / 6.14.6
- OS: OSX
- Browser: FF/Safari/Chrome

**Comment by jrjohnson** [comment]
May be related to or a duplicate of #19101, but I'm not sure so I created this new issue with the reproduction.

**Comment by rwjblue** [comment]
@pzuraq this seems like a similar issue to https://github.com/emberjs/data/pull/7273, would you mind taking a look to see what is going on? This is broken between 3.20.3 and 3.20.4.

**Comment by pzuraq** [comment]
Dug into this, and figured out the issue. Have a fix ready, just need to write a test, will be doing that in the morning

**Comment by jrjohnson** [comment]
Confirmed. This is fixed in `v3.20.5`. Thanks!

**Comment by jrjohnson** [comment]
@pzuraq I'm seeing a related issue when not depending on `.length`, but just watching the array. Something like 
```
{{did-update this.load @post.comments}}
```

Should I open a new issue and reproduction? Or should that have been covered in this fix?
