### ISSUE TITLE
[Bug] Misleading rootURL assertion

### ISSUE THREAD

**Issue by lindyhopchris** [emberjs/ember.js#19102]
### 🐞 Describe the Bug

I have an app that has a `rootURL` of `/d/`. I'm rendering the Ember app HTML from my backend application (Laravel PHP), which has a convention of stripping trailing slashes. So the backend app will serve the Ember app from both `http://example.com/d` and `http://example.com/d/`, but when creating redirects/URLs it uses the version without trailing slashes - i.e. `http://example.com/d`.

If I deploy a `development` build of the Ember application, the Ember app fails to load with the following assertion message:

```
Uncaught Error: Assertion Failed: Path /d does not start with the provided rootURL /d/
```

However if I deploy a `production` build of the Ember application, the Ember app does load. This is because the assertion is not performed, and Ember handles the routing fine. The Ember routing seems to append the missing trailing slash.

The bug is that the assertion is misleading - it will work with a production build, so the assertion should not fail in a development build.

### 🔬 Minimal Reproduction

1. New Ember app, set the `rootURL` to something with a trailing slash, e.g. `/d/`.
2. Deploy a development build of the Ember app to a server that will serve it from `/d`.
3. Assertion will fail in development build.

### 😕 Actual Behavior

The assertion does not match `/d` and `/d/`, however this does actually work in a production build.

### 🤔 Expected Behavior

The assertion should either append a `/` to the `/d` when performing the assertion, or match the rootURL without trailing slashes. I.e. `/d` and `/d/` should be considered a match as the routing works fine.

### 🌍 Environment

- Ember: 3.19
- Node.js/npm: 12.14.1 / 6.14.3
- OS: Ubuntu 18.04
- Browser: Chrome 84.0.4147.105

### ➕ Additional Context

I'm using Laravel (PHP) on the backend, which has a convention of removing trailing slashes from URLs. The Laravel app is rendering the Ember HTML, i.e. I'm not serving the `index.html` built by Ember.

**Comment by rajasegar-c** [comment]
I am also facing the same issue. I think the possible fix is to replace this line:
https://github.com/emberjs/ember.js/blob/66c56e44b85f315bd0a5ed11787d563a11ebe835/packages/%40ember/-internals/routing/lib/location/auto_location.ts#L284
with:
```
let rootURLIndex = rootURL.indexOf(path);
```

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by lindyhopchris** [comment]
This is still an issue for me, but I'm still on 3.28 - so I don't know if it occurs in a more recent version of Ember. I'm planning on upgrading my Ember apps later this year, but not sure exactly when.

**Comment by sandstrom** [comment]
@lindyhopchris I'm also on an older version. Do you want me to re-open, or should I keep it closed until you've checked on a newer version?

Either way, the reality is probably that unless you want to fix the bug itself, it won't get fixed, because it's only you and one other person that has discussed this, and it was a while ago. The time for core team members is very limited, and I think we all want them to focus primarily on moving the framework forward, leaving the fixing of edge case bugs to "fringe volunteers", such as you and me (it's important for all of us that core members spend their time on high-leverage stuff).

**Comment by lindyhopchris** [comment]
Hmmm yeah that's fair. Unfortunately I'm drowning in admin on the open source projects that I maintain, so I'm unlikely to get to this any time soon.

I wouldn't describe it as a critical problem, so if you're preference is to close the ticket then I'd understand.
