### ISSUE TITLE
[Bug] `fn` does not accept helpers

### ISSUE THREAD

**Issue by chriskrycho** [emberjs/ember.js#19108]
### 🐞 Describe the Bug

The `fn` helper fails immediately on rendering a template where you pass it a *helper* instead of a *method on a backing class*. The problem appears to have a few layers to it, but the first is that Ember (I think the resolver, but haven't gotten to the bottom of it yet) attempts to resolve the argument passed to it as if it were *always* on the backing class, i.e. treats it as `this.foo` instead of resolving it as a helper. Once you get past that, e.g. if you try to bind it with block `let`, you'll find that it blows up because it gets back a helper *object* (with a `.compute()` method) instead.

### 🔬 Minimal Reproduction

See [this Twiddle](https://ember-twiddle.com/595ca77223cf19401451c04f828908b9?openFiles=helpers.fn-go-boom%5C.js%2C) for a working reproduction. Minimally, though:

1. `ember g helper foo`

2. Put this in a template (the `application.hbs`):

    ```hbs
    <button {{on "click" (fn foo)}}>boom</button>
    ```

3. Serve the app.

4. Open the inspector. 

### 😕 Actual Behavior

You'll see the error:

> Unhandled Promise Rejection: Error: Assertion Failed: You must pass a function as the `fn` helpers first argument, you passed undefined. While rendering:

> application
>  this.foo

### 🤔 Expected Behavior

`fn` should work with *functions*, whether they're methods on classes or not.

### 🌍 Environment

- Ember: 3.20
- Node.js/npm: 12.16.1
- OS: macOS 10.15.16
- Browser: any

### ➕ Additional Context

N/A.

**Comment by rwjblue** [comment]
Sorry, I’m not fully following the expected behavior here, do you expect to invoke `foo` and have that helper return a function that is passed to `fn`?

At the moment, helpers are not discrete values themselves (at least not until [emberjs/rfcs#432](https://github.com/emberjs/rfcs/blob/master/text/0432-contextual-helpers.md)), and can’t be passed / curried in the same way that components can (with the `(component` helper); at least not until that RFC is implemented. Additionally related is [emberjs/rfcs#626](https://github.com/emberjs/rfcs/blob/master/text/0626-invoke-helper.md) which allows you to invoke a helper from JS land. These two RFC’s combined provide for the functionality that you are after (if I’ve understood you correctly).

In the end, I don’t think this is a bug so I’m going to close for now. I’m happy to reopen if I’ve misunderstood something here though.

**Comment by chriskrycho** [comment]
Thanks for the response, and—after sleeping on it and reading the first-class helpers and modifiers RFC—I agree that this is as expected. I think it's *surprising* in some ways that these are separate concepts/primitives (somehow that hadn't fully clicked for me until this morning! 🤦‍♂️), but given that they are, I agree this is *not a bug*.

To clarify, what I originally expected is that `fn` to support partial application of arguments to helpers, because the mental model for helpers is that they're functions. From the Helper guides:

> Helper functions are JavaScript functions that you can call from your template.

And from the `fn` API docs:

> The `fn` helper allows you to ensure a function that you are passing off to another component, helper, or modifier has access to arguments that are available in the template.

While it's clear enough to me after loading up the *whole* mental model—recognizing that (a) helpers are not normal functions but are reactive functions and (b) can be classes as well as functions—I think we might want to tweak the docs a bit. I'll mull on *how* and possibly open an issue on the learning repo instead.

**Comment by rwjblue** [comment]
> While it's clear enough to me after loading up the whole mental model—recognizing that (a) helpers are not normal functions but are reactive functions and (b) can be classes as well as functions—I think we might want to tweak the docs a bit.

Yep, totally agree! I think that to curry a helper with some arguments (in the hopefully near future) you'd use `(helper my-helper-name whateverArg goes=here)` and it will be _basically_ symmetrical with how you'd do the same thing with `(component`.

Also, I didn't mention this, but the Helper Manager RFC ([emberjs/rfcs#625](https://github.com/emberjs/rfcs/blob/master/text/0625-helper-managers.md)) will allow you to treat "regular functions" as a helper (assuming you do `setHelperManager(Function, (owner) => new MySpecialPlainFunctionManager())`). Which would actually enable the thing you originally typed up.
