### ISSUE TITLE
[Bug/Regression] 3.22.0-beta.1 `@computed("args.foo")` throws when foo not provided

### ISSUE THREAD

**Issue by Herriau** [emberjs/ember.js#19112]
### 🐞 Describe the Bug
Getters decorated with `@computed("args.<someArg>")` throw when `<someArg>` is not supplied at the call site.

### 🔬 Minimal Reproduction

**app/components/my-dummy-component/component.ts:**
```typescript
import Component from "@glimmer/component";
import { computed } from "@ember/object";

export default class MyDummyComponent extends Component<{ foo?: boolean }> {
  @computed("args.foo")
  get foo(): boolean {
    return this.args.foo ?? false;
  }
}
```

**app/components/my-dummy-component/template.hbs:**
```htmlbars
Foo value = {{if this.foo "true" "false"}}
```

**app/templates/application.hbs:**
```htmlbars
<MyDummyComponent/>
```

### 😕 Actual Behavior

```
index.js:5268 Uncaught (in promise) TypeError: Cannot read property 'value' of undefined
    at index.js:5268
    at track (validator.js:789)
    at Proxy.getTag (index.js:5268)
    at tagForProperty (index.js:517)
    at getChainTags (index.js:877)
    at getChainTagsForKeys (index.js:805)
    at ComputedProperty.get (index.js:1896)
    at MyDummyComponent.CPGETTER_FUNCTION [as foo] (index.js:992)
    at getPossibleMandatoryProxyValue (index.js:1285)
    at _getProp (index.js:1350)
```

### 🤔 Expected Behavior

No exception thrown. The rendered HTML should be:

```
Foo value = false
```

### 🌍 Environment

- ember: 3.22.0-beta.1
- ember-cli: 3.20.0
- node: 10.19.0
- os: darwin x64
- browser: Chrome 84.0.4147.135

### ➕ Additional Context

This is perhaps seen as a niche problem in the realm of auto-tracked props, but as an add-on author who needs to provide backward support to pre-octane apps, this has started to break my `ember-try` matrix.

**Comment by Exelord** [comment]
Confirmed: https://travis-ci.com/github/Exelord/ember-await/jobs/391177752

**Comment by pzuraq** [comment]
I believe this should be fixed by https://github.com/emberjs/ember.js/pull/19163

**Comment by locks** [comment]
Closing as no longer relevant as getters are now supported without the `@computed` decorator.

**Comment by locks** [comment]
Actually, it was also fixed by the PR mentioned in the latest comment!
