### ISSUE TITLE
[Bug] FastBoot broken in Ember 3.22 Beta

### ISSUE THREAD

**Issue by simonihmig** [emberjs/ember.js#19113]
Any FastBoot request fails with `TypeError: Cannot read property 'require' of null` for Ember 3.22 beta or canary.

This has already (rightly) been reported upstream at https://github.com/glimmerjs/glimmer-vm/issues/1141. But opening this here also for better visibility and tracking. From my point of view, unless this is fixed this seems to be a blocker for releasing the next stable version!

**Comment by rwjblue** [comment]
> From my point of view, unless this is fixed this seems to be a blocker for releasing the next stable version!

Me too!
