### ISSUE TITLE
[Bug] Select tag value trouble in Firefox

### ISSUE THREAD

**Issue by frank-technologies** [emberjs/ember.js#19120]
### 🐞 Describe the Bug
When options array for select tag reassign than select value changes.
This behavior happens in Firefox but in Chrome it works normally.

### 🔬 Minimal Reproduction
Minimal example: https://ember-twiddle.com/1bc3241b18048392fe353fbc8916ea3a?openFiles=controllers.application%5C.js%2C
If to press test than value of the select will to change. But in really the value isn't change.

```hbs
<button {{on "click" test}}>test</button>
<select>
  {{#each values as |v|}}
    <option value={{v.id}} selected={{eq value v.id}}>
      {{v.label}}
    </option>
  {{/each}}
</select>
```

### 😕 Actual Behavior
The value of a select switches.

### 🤔 Expected Behavior
The value of a select stays without changes.

### 🌍 Environment

- Ember: 3.18 (Twiddle), 3.20 (project)
- Node.js/npm: 12.18.3/6.14.6
- OS: Windows, Linux
- Browser: Firefox

**Comment by czosel** [comment]
This issue is still occuring in Ember 4.11 and current versions of Firefox (tested in v110). Any pointers on what could cause this are much appreciated.

**Comment by sandstrom** [comment]
Closed since it's fixed in FF according to parent comment.
