### ISSUE TITLE
[Documentation] Onboarding developer frustration

### ISSUE THREAD

**Issue by lmf-git** [emberjs/ember.js#19127]
I started to use Ember.js, very excited about its ability to create good landing pages...

The process of creating a single (simple) application via Ember has been a nightmare.

There is an index.html, application template, "hello-world" files that are being created via the env/package properties, and there is no easy way to stop the generation of this first route that was created via Vercel.

I am going to stick with Ember for this project despite having many different framework choices and hope that it gets easier, but I just wanted to tell you what I went through so it can be made easier for those who hit your marketing funnel for this exact purpose.

Thanks for the framework

**Comment by lmf-git** [comment]
Every directory in the world has been created but nowhere to put assets?

**Comment by lmf-git** [comment]
Where to put arbitrary js for a landing page:
https://stackoverflow.com/questions/43259095/ember-js-include-custom-js

Where to put images: (Checking first)
https://stackoverflow.com/questions/32629787/ember-cli-where-to-put-images

![Screenshot 2020-09-03 at 22 31 10](https://user-images.githubusercontent.com/67340984/92175829-31899900-ee35-11ea-92b9-604741294cf1.png)

**Comment by lmf-git** [comment]
Are you morally serious?

![Screenshot 2020-09-05 at 21 21 37](https://user-images.githubusercontent.com/67340984/92312944-db942d00-efbd-11ea-9564-41a49e9451c4.png)

**Comment by lmf-git** [comment]
Sort this out guys. You're scaring off the nubs like me.

**Comment by lmf-git** [comment]
You people don't want me to finish anything do you? Jeez

![Screenshot 2020-09-05 at 23 33 56](https://user-images.githubusercontent.com/67340984/92314511-5c5c2480-efd0-11ea-8afe-98621af9bf29.png)

![Screenshot 2020-09-05 at 23 34 04](https://user-images.githubusercontent.com/67340984/92314512-5cf4bb00-efd0-11ea-8094-e985842c0e3a.png)

**Comment by pabloascarza** [comment]
Calm your horses, you can reach help in [discord ](https://discord.gg/emberjs). There is a community happy to help you.

**Comment by lmf-git** [comment]
> Calm your horses, you can reach help in [discord ](https://discord.gg/emberjs). There is a community happy to help you.

I don't own any horses. I own a very slow to develop on framework called EmberJS

**Comment by lmf-git** [comment]
This framework sucks.

**Comment by lmf-git** [comment]
Caution to other developers: Don't use this if you want to programmatically change routes, involves setting up controllers and messing with routes. Lol.

Absolutely nothing can be done in this framework in under 10 minutes.

**Comment by MelSumner** [comment]
After a discussion with this user on Discord, they are going to try the [Ember Tutorial](https://guides.emberjs.com/release/tutorial/part-1/). Closing this issue. 

If future issues arise with the documentation, please file an issue on the Guides repository- https://github.com/ember-learn/guides-source/issues.
