### ISSUE TITLE
Vercel Template out of sync with ember-new-output

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember.js#19132]
The left is a brand new vercel ember app.

the public folder is missing.
Also ember is on 3.11, instead of 3.21.x+

![image](https://user-images.githubusercontent.com/199018/92417630-24202780-f131-11ea-973f-c00e948d2442.png)

(I don't know where to report these types of issues (I know this isn't ember-source related))

**Comment by NullVoxPopuli** [comment]
Ah, looks like the template is here: https://github.com/vercel/vercel/tree/master/examples/ember

**Comment by NullVoxPopuli** [comment]
@mcsdevv, @styfle, @TooTallnade, @chibicode, @AndyBitz
^ folks on the git history for the vercel/examples/ember folder

**Comment by styfle** [comment]
Looks like the public directory was ignored when the Ember example was imported.

This will fix it: https://github.com/vercel/vercel/pull/5164
