### ISSUE TITLE
App booted before DOM ready without jQuery

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#19134]
https://github.com/emberjs/ember.js/blob/b049c37e66587718cef38cde63b59b0789505d43/packages/%40ember/application/lib/application.js#L485-L491

Without jQuery, this code no longer works and boots the app immediately (as soon as the bundle is loaded, but possibly before DOM read).

Workaround for now using an initializer:

```js
export function initialize(app) {
  if (document.readyState === 'loading') {
    app.deferReadiness();

    let callback = () => {
      if (document.readyState !== 'loading') {
        app.advanceReadiness();
        document.removeEventListener('readystatechange', callback);
      }
    };

    document.addEventListener('readystatechange', callback);
  }
}

export default {
  initialize
};
```

We should reimplement `$.ready()` without relying on jQuery.

**Comment by kanavpruthi** [comment]
I am a beginner at contributing and would like to work on an issue here.
