### ISSUE TITLE
[Bug] <LinkTo> bubbles up even if @bubbles={{false}}

### ISSUE THREAD

**Issue by schorke** [emberjs/ember.js#19144]
### 🐞 Describe the Bug
When having a `<LinkTo>` inside an HTML tag that has an action on it (defined with the `{{on "click"}}` modifier), the outer action is triggered when clicking on `<LinkTo>` (even with the `<LinkTo @bubbles={{false}}>` set). This should not be the case as defined in the [LinkTo code](https://github.com/emberjs/ember.js/blob/0a9e13ad894b704b1b5ac5073aaf4bb0112b1bec/packages/%40ember/-internals/glimmer/lib/components/link-to.ts#L668)).

### 🔬 Minimal Reproduction
This bug is shown in [this Twiddle](https://ember-twiddle.com/3524dfaab10656417c3fa2f36e337169?openFiles=templates.index%5C.hbs%2C) by simply clicking on the `Link to edit` button; the outer div action is triggered (console log).
```
<div {{on "click" this.logMessageToConsole}}>
  This is the outside div
  <br>
  <LinkTo
      @route={{"edit"}}
      @bubbles={{false}}>
    Link to edit
  </LinkTo>
</div>
```

### 😕 Actual Behavior
Outer action is triggered when clicking on inner LinkTo (bubbles up).

### 🤔 Expected Behavior
Outer action should not be triggered when clicking on inner LinkTo (should not bubble up).

### 🌍 Environment

- Ember: 3.20.0
- Node.js/npm: 14.8.0/6.14.8
- OS: MacOS Catalina 10.15.6
- Browser: Google Chrome  85.0.4183.102

### ➕ Additional Context
Did I miss something obvious or this is definitely a bug ? There's no official documentation on the LinkTo `bubbles` parameter but it appears to follow the [same path](https://github.com/emberjs/ember.js/blob/0a9e13ad894b704b1b5ac5073aaf4bb0112b1bec/packages/%40ember/-internals/glimmer/lib/components/link-to.ts#L660) as the `preventDefault` parameter which is [documented](https://api.emberjs.com/ember/release/classes/Ember.Templates.components/methods/LinkTo?anchor=LinkTo).

**Comment by schorke** [comment]
I found out that the [_invoke()](https://github.com/emberjs/ember.js/blob/0a9e13ad894b704b1b5ac5073aaf4bb0112b1bec/packages/%40ember/-internals/glimmer/lib/components/link-to.ts#L655) method is called (on click on `<LinkTo>`) **AFTER** the action called in outer HTML div `{{on "click" this.logMessageToConsole}}`, hence the `event.stopPropagation();` is not doing anything since it is called after the outer action call.

The only working workaround is :
```
@action
logMessageToConsole() {
  console.log('Outer HTML click');
}

@action
stopPropagation(event) {
  event.stopPropagation();
}

<div {{on "click" this.logMessageToConsole}}>
  This is the outside div
  <br>
  <LinkTo
      @route={{"edit"}}
      {{on "click" this.stopPropagation}}>
    Link to edit
  </LinkTo>
</div>
```

Any idea to why the `_invoke()` method is not called first and before the outer action (handler is set in [init()](https://github.com/emberjs/ember.js/blob/0a9e13ad894b704b1b5ac5073aaf4bb0112b1bec/packages/%40ember/-internals/glimmer/lib/components/link-to.ts#L473) method ?

**Comment by locks** [comment]
`bubbles` has been deprecated and removed, so this issue is no longer relevant. Thanks for reporting!
