### ISSUE TITLE
[Bug] Error messages regarding undefined fn parameters do not indicate line numbers

### ISSUE THREAD

**Issue by eddylu94** [emberjs/ember.js#19169]
### 🐞 Describe the Bug
Currently, in component template logic, developers have the privilege of using the {{fn}} helper. This {{fn}} helper requires a function as its first parameter:

```
{{fn <functionName> <optionalParameters>}}
```

When the first parameter of this {{fn}} helper call is deemed to be undefined, the developer will see the following error message in their browser debugger:

```
You must pass a function as the `fn` helpers first argument, you passed undefined
```

Unfortunately, this error message does not indicate the specific {{fn}} helper that is causing the error to be displayed. This is extremely problematic when developers work with many changes in complex codebases. There needs to be line numbers printed in the error messages, similar to how React displays line numbers for JSX/TSX logic.

### 🔬 Minimal Reproduction
Describe steps to reproduce. If possible, please, share a link with a minimal reproduction.

The reproduction procedure is very straight forward.

Simply add the following logic in a template

```
{{fn foo}}
```

and ensure that `foo` is not defined.

### 😕 Actual Behavior

The developer will see the following error message in their browser debugger:

```
You must pass a function as the `fn` helpers first argument, you passed undefined
```

### 🤔 Expected Behavior

The developer should see the same error message along with the line numbers of the offending template logic.

### 🌍 Environment

This issue should reproduce for all Ember and Node.js versions that include the {{fn}} helper across all operating systems and browsers.

### ➕ Additional Context

N/A

**Comment by pzuraq** [comment]
Thanks for reaching out @eddylu94! This is definitely something we've been looking to get better at, error messages while rendering can be very frustrating as is today.

Getting exact line numbers is going to be a larger overhaul, it's something that absolutely should be done but that may take a while. In the meantime though, I think we can use some of the recent autotracking overhauls to provide at least some better context. Basically, we will be able to show you what was rendering when the error occurred, so you can at least narrow it down to the component that is causing the issue:

<img width="806" alt="Screen Shot 2020-09-29 at 6 23 58 PM" src="https://user-images.githubusercontent.com/685518/94633345-d905ba00-0281-11eb-92e8-b28ab3393027.png">

I have this spiked out locally, hopefully we'll be able to get it into the next LTS!

**Comment by kamalkech** [comment]
still getting this error

**Comment by pzuraq** [comment]
@kamalkech the error itself is expected, in more recent versions of Ember you should get better messages. Eventually we hope to get to the point where we can give you an exact line number of where the failure occurred.

**Comment by kamalkech** [comment]
so what we can do if working on real project ?!! with this issue i cannot finish to dev the app :(

**Comment by Mithrilhall** [comment]
@kamalkech Does something like `@save={{fn this.actions.save}}` work?

**Comment by nlfurniss** [comment]
> so what we can do if working on real project ?!! with this issue i cannot finish to dev the app :(

This is an unsatisfying answer I know, but based on the error you should know which file it's coming from. At that point you can comment out each line with an `fn` and run the test until you find the offending line, **or** `{{log}}`ing each arg to fn will tell you which one needs fixing

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue.

> kamalkech the error itself is expected, in more recent versions of Ember you should get better messages. Eventually we hope to get to the point where we can give you an exact line number of where the failure occurred.

As mentioned above, the error message is better in more recent versions of Ember. I'm going to go ahead and close this, but happy to reopen if people strongly disagree and this is still a problem on the most recent version of Ember.

By closing some old issues we reduce the list of open issues to a more manageable set. Let me know if you think this is a mistake and that the issue should stay open.
