### ISSUE TITLE
[Documentation] Document return types for Controller#{replaceRoute, transitionToRoute}

### ISSUE THREAD

**Issue by eramod** [emberjs/ember.js#19181]
### 📙 Describe the Issue
On the `Controller` class, `replaceRoute` and `transitionToRoute` both return a `Transition` object, but the documentation does not include this. 

### 🔬 Minimal Reproduction
https://api.emberjs.com/ember/3.21/classes/Controller/methods/replaceRoute?anchor=replaceRoute
https://api.emberjs.com/ember/3.21/classes/Controller/methods/replaceRoute?anchor=transitionToRoute

### 😕 Actual Behavior
The documentation for the methods do not include a return type

### 🤔 Expected Behavior
The methods should have their return types documented, just like their corresponding route APIs e.g. https://api.emberjs.com/ember/3.21/classes/Route/methods/replaceWith?anchor=replaceWith

**Comment by rwjblue** [comment]
Totally agree, thanks for reporting @eramod!
