### ISSUE TITLE
[Documentation] Show using `{{on}}` for input components

### ISSUE THREAD

**Issue by jenweber** [emberjs/ember.js#19201]
In the [API guides for input](https://api.emberjs.com/ember/release/classes/Ember.Templates.components/methods/Input?anchor=Input), we show passing actions like this:

```
<Input @value={{this.searchWord}} @enter={{this.query}} />
```

However, for Octane-style apps, the preferred way of adding actions to inputs is to use `{{on}}`, as shown in [this part of the Guides](https://guides.emberjs.com/release/components/built-in-components/#toc_actions):

```
<label for="input-name">Name:</label>
<Input
  @id="input-name"
  @value={{this.name}}
  @input={{this.validateName}}
/>
```

To-do:
- Add a brief example using `{{on}}` to the Input API docs page. It's [here](https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/glimmer/lib/components/input.ts). Do not remove any existing explanation of other events/styles. If there is an example from the Guides that you think works well here, use that instead of writing something new.

**Comment by romance939913** [comment]
Hi @jenweber - Can I take a stab at this??

**Comment by jenweber** [comment]
@romance939913  that would be awesome! Please get in touch if you have questions.

**Comment by romance939913** [comment]
Hi @jenweber - Yes, a little guidance would be great. I'm fairly new to open source:).

Correct me if I'm wrong, but for this issue, all I need to do is add a sentence or two in ember.js/packages/@ember/-internals/glimmer/lib/components/input.ts/ explaining that with Ember Octane, the {{on}} modifier is recommended for calling actions on specific events. And then add an example like this:

<label for="input-name">Name:</label>
<Input
  @id="input-name"
  @value={{this.name}}
  {{on "input" this.validateName}}
/>

Is that correctly? Also, what are the steps for setting up the dev environment for this project?? (installations, commands, etc.)

Please let me know. Also any other information you think would be helpful is greatly appreciated. Thanks!!

**Comment by GuptaTanisha** [comment]
@jenweber Can I work on this issue?

**Comment by bertdeblock** [comment]
Since #19314 is merged, I think we can close this?

**Comment by jenweber** [comment]
Yes, that's correct. Sorry we forgot to close this issue when the PR was merged. Thanks everyone for your willingness to help :)
