### ISSUE TITLE
Quest - Remove canary feature flags that have been enabled for at least one version

### ISSUE THREAD

**Issue by jenweber** [emberjs/ember.js#19202]
When new features are in development, they are often feature flagged. When they are done, the feature flag is set to true. After the flag has been `true` in at least one minor release, the feature flag can be removed.

This ticket can be worked on by multiple people. If you would like to help, please comment with which flag you are working on.

To-do:
- Read the comments on this issue to see which flags are already being worked on by other contributors
- Find a feature flag listed in [this file](https://github.com/emberjs/ember.js/blob/master/packages/@ember/canary-features/index.ts#L16-L25) that is set to true. Look at the previous minor release of Ember. If it was true in that version too, go to the next step! If not, please comment on this issue to say so, and then choose another flag.
- Search the codebase for all uses of that feature flag. Remove the code that would not have been hit if the flag was true. Then, remove the flag itself from the code as well as from the [canary-features list](https://github.com/emberjs/ember.js/blob/master/packages/@ember/canary-features/index.ts#L16-L25)
- Open a PR and link to this issue from it

  - [ ] EMBER_GLIMMER_SET_COMPONENT_TEMPLATE
  - [ ] EMBER_ROUTING_MODEL_ARG
  - [ ] EMBER_CACHE_API
  - [ ] EMBER_DESTROYABLES
  - [ ] EMBER_GLIMMER_HELPER_MANAGER
  - [ ] EMBER_GLIMMER_INVOKE_HELPER

**Comment by andreisebastianc** [comment]
EMBER_GLIMMER_INVOKE_HELPER was added after [3.2.2](https://github.com/emberjs/ember.js/blob/v3.22.0/packages/@ember/canary-features/index.ts)

**Comment by andreisebastianc** [comment]
EMBER_GLIMMER_HELPER_MANAGER was added after [3.2.2](https://github.com/emberjs/ember.js/blob/v3.22.0/packages/@ember/canary-features/index.ts)

**Comment by locks** [comment]
All done for some time!
