### ISSUE TITLE
[Bug] (capabilities 3.22) Custom modifier-manager#update not called when tracked property is updated

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember.js#19215]
### 🐞 Describe the Bug
Been working on updating the modifier addons:
 - https://github.com/emberjs/ember-render-modifiers/pull/25
 - https://github.com/ember-modifier/ember-modifier/pull/63

In order to fix the issue for consuming apps/addons:
- described by: https://github.com/emberjs/ember.js/issues/19162
- fixed by: https://github.com/emberjs/ember.js/pull/19163

### 🔬 Minimal Reproduction
in https://github.com/emberjs/ember-render-modifiers/pull/25 (before and after the re-arrangment of the of the way the modifier is constructed (absolute minimum reproduction is to change the capabilities to 3.22).

and then this test:
```ts
module('Integration | Modifier | did-update', function(hooks) {
  setupRenderingTest(hooks);

  if (gte('3.22.0')) {
    module('capabilities(3.22)', function() {
      class Context {
        @tracked boundValue = 'initial';
      }

      test('it basically works', async function(assert) {
        assert.expect(4);

        this.setProperties({
          ctx: new Context() ,
          someMethod(element, positional, named) {
            assert.equal(element.tagName, 'DIV', 'correct element tagName');
            assert.dom(element).hasAttribute('data-foo', 'some-thing');

            assert.namedArgsEqual(named, {}, 'named args match');
            assert.equal(positional.length, 1);
            assert.equal(positional[0], 'update', 'positional args match');
          },
        });


        await render(
          hbs`
            <div
              data-foo="some-thing"
              {{did-update this.someMethod this.ctx.boundValue}}
            >
            </div>`
        );

        this.set('ctx.boundValue', 'update');

        await settled();
      });
    });
//...
```

### 😕 Actual Behavior
update hook in custom modifier-manager is never called

this method: https://github.com/emberjs/ember.js/blob/66fb044408d44649989902e9f85933cdf86f8cc8/packages/%40ember/-internals/glimmer/lib/modifiers/custom.ts#L187

place a breakpoint on or above the if within the method. the breakpoint is never hit.

### 🤔 Expected Behavior
update hook in custom modifier manager is called

### 🌍 Environment

```
- Ember: 3.22+
ember -v
ember-cli: 3.20.0
node: 12.18.3
os: linux x64

browser: chrome and firefox
```

**Comment by NullVoxPopuli** [comment]
It seems that if I consume args in `install`, that `update` will run. _maybe_ that's fine?

**Comment by NullVoxPopuli** [comment]
doing this (so far) has been the only way I've been able to get teh updateModifier hook to run:
```ts

    installModifier(instance, element, args) {
      // save element into state bucket
      // save element into state bucket
      state.element = element;
      instance.element = element;

      if (gte('3.22.0')) {
        // consume all args
        for (let i = 0; i < args.positional.length; i++) {
          // "noop" / consume the arg
          args.positional[i];
        }

        for (let key of Object.keys(args.named)) {
          // "noop" / consume the arg
          args.named[key];
        }
      }
    },
    },
```

**Comment by NullVoxPopuli** [comment]
maybe this is a non-issue? and me just learning what capabilities 3.22 _actually means?_

**Comment by NullVoxPopuli** [comment]
I think this means I can apply the same sort of "fix(?)" to https://github.com/ember-modifier/ember-modifier/pull/63

seems kinda wonky implementation wise, but... maybe that's fine? since it really only affects addon-authors of custom modifier managers?

**Comment by rwjblue** [comment]
The entire point of the 3.22 capability was to make the consumption of the passed in arguments actually reflect what was used in the modifier (the 3.13 capabilities always consumes everything, that's the original issue). 

We definitely should **not** eagerly consume everything (like in that snippet) over in ember-modifier (or ember-render-modifiers)...

**Comment by NullVoxPopuli** [comment]
🤔 I'm working on some tests to try to better explore the problem
