### ISSUE TITLE
[Bug] Component Invocation should not work with hyphens

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember.js#19220]
### 🐞 Describe the Bug
Both `<HyphenatedComponent />` and `<Hyphenated-Component />` refer to the same component, and are both currently valid.

### 🔬 Minimal Reproduction
- `yarn ember g component hyphenated-component`
- place `<Hyphenated-Component />` in application.hbs

Repro
https://codesandbox.io/s/modern-architecture-6o9hh?file=/app/templates/application.hbs:0-24
- note: this codesandbox will probably not live on forever, because I don't pay for codesandbox (so I have a finite number of container sandboxes)

### 😕 Actual Behavior
Component is rendered

### 🤔 Expected Behavior
Some assertion / build-time error that says something like, "yo, use PascalCase"

### 🌍 Environment

- Ember: 3.16+
- Node.js/npm: - :shrug:
- OS: - any
- Browser: - any

**Comment by rwjblue** [comment]
I don't think this is a bug, it _is_ unfortunate though.

**Comment by rwjblue** [comment]
This is explicitly tested here:

https://github.com/emberjs/ember.js/blob/3a866f974b6605db8a9a2b32355a7388de6ed536/packages/ember-template-compiler/tests/system/dasherize-component-name-test.js#L15-L16

Changing would be breaking.

**Comment by NullVoxPopuli** [comment]
Would a deprecation RFC be of interest?

**Comment by pzuraq** [comment]
This is effectively deprecated via strict mode. In strict mode, you will only be able to reference JS identifiers by design.

**Comment by NullVoxPopuli** [comment]
Awesome, thanks!
