### ISSUE TITLE
[Documentation] Documentation doesn't include options argument for Adapter query method

### ISSUE THREAD

**Issue by alexborovkov** [emberjs/ember.js#19235]
### 📙 Describe the Issue

Documentation doesn't include that adapter query method has 5 arguments, not 4.
Fifth argument is object that might have adapterOptions.

Adapter - query
https://api.emberjs.com/ember-data/3.22/classes/Adapter/methods/query?anchor=query
![image](https://user-images.githubusercontent.com/22237897/97308276-c034f800-1871-11eb-8cbd-4890c87706da.png)

Store - query
https://api.emberjs.com/ember-data/3.22/classes/Store/methods/query?anchor=query
![image](https://user-images.githubusercontent.com/22237897/97309103-a942d580-1872-11eb-8300-552bec13870b.png)

Expected:
Documentation includes options argument for adapter query method

**Comment by bertdeblock** [comment]
@alexborovkov [This is fixed](https://api.emberjs.com/ember-data/3.25/classes/Adapter/methods/query?anchor=query) so I think we can close this.

**Comment by rwjblue** [comment]
Thanks @bertdeblock!
