### ISSUE TITLE
[Bug] "Assertion Failed" Error thrown while updating ember from 3.0.0 to 3.22

### ISSUE THREAD

**Issue by mariselvanm** [emberjs/ember.js#19252]
After updating the ember CLI version from 3.0.0 to 3.22. The build was successful but while trying to load the app in the browser will throw the below error.

![Screen Shot 2020-11-06 at 2 22 16 PM](https://user-images.githubusercontent.com/23354819/98346100-874c0e80-203b-11eb-98c2-cfb2b1502f12.png)

Tried to search my application to find the init issue. But everything seems fine. Can anybody tell me where these errors came from and how to get rid of it?

**Comment by rreckonerr** [comment]
In general, it's a good idea to upgrade ember app step by step following the lts versions. In your case it should be `3.0 -> 3.4 -> 3.8 -> 3.12 -> 3.16 -> 3.20`. In case you'll get an error while moving to another lts version its gonna be much easier to debug what went wrong. Aslo, don't forget to deal with depreciations along the way.

As for your error, seems like it's coming from ember-responsive addon, which provides your app with media service. 

### Resources 
https://cli.emberjs.com/release/basic-use/upgrading/
https://emberjs.com/releases/lts/

**Comment by mariselvanm** [comment]
@rreckonerr How can you say that this error came from "ember-responsive"? Just wanted to know that...

**Comment by rreckonerr** [comment]
Because media service is mentioned in the error stack. But anyways it's an assumption

**Comment by rwjblue** [comment]
Ya, seems like a reasonable assumption to me as well. 

The assertion is there to point out these situations that are actually not functioning properly (not supering in init of framework classes will introduce a whole host of issues).

I'm going to close, as this isn't really a bug in Ember (which is what we use this issue tracker for). Please feel free to continue discussion here though!
