### ISSUE TITLE
[Bug] [3.23.0] Using a dynamic component with angle-brackets is broken

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#19276]
### 🔬 Minimal Reproduction
This used to work on 3.22.x:
```hbs
{{#with "some-component-name" as |Component|}}
  <Component>{{yield}}</Component>
{{/with}}
```

On 3.23.0 leads to an error and instead the `component` component must be used:
```hbs
{{#component "some-component-name"}}{{yield}}{{/component}}
```

### 😕 Actual Behavior
There is an error:
```
Error: Expected a curried component definition, but received some-component-name. You may have accidentally done <(result of a `get` helper)>, where "(result of a `get` helper)" was a string instead of a curried component definition. You must use the {{component}} helper to create a component definition when invoking dynamically.
```

### 🤔 Expected Behavior
The code to work. I'm not *really* sure that was supposed to work though. If not, please close the issue. Otherwise that's a regression. I'm not sure where I read that this was supported, perhaps in the documentation somewhere?

**Comment by rwjblue** [comment]
This is a bug fix, the original code should never have worked. 🤔

**Comment by rwjblue** [comment]
This was fixed by https://github.com/emberjs/ember.js/pull/19122.

Sorry this bit you, but I'm going to close (since this was a bug fix).

**Comment by alvarocastro** [comment]
Leaving this here in case someone else has the same issue, since this fix also broke part of my code because I was using a variable as the name of the angle bracket component.

This was my hbs before the fix:
```hbs
<this.baseComponent
  @foo="bar"
  {{did-insert this.setup}}
  {{will-destroy this.teardown}}
  ...attributes
>
  {{yield}}
</this.baseComponent>
```
> `this.baseComponent` is a string with the name of the component

Was using this approach since you can't pass modifiers to the `{{component}}` helper.

This is how I have the template after this fix:
```hbs
{{#let (component this.baseComponent) as |BaseComponent|}}
  <BaseComponent
    @foo="bar"
    {{did-insert this.setup}}
    {{will-destroy this.teardown}}
    ...attributes
  >
    {{yield}}
  </BaseComponent>
{{/let}}
```

**Comment by rogeraraujo90** [comment]
@alvarocastro Thank you for share! This help me a lot! 😄
