### ISSUE TITLE
Why ember-source@3.22.2 not available on npmjs ?

### ISSUE THREAD

**Issue by BnitoBzh** [emberjs/ember.js#19288]

**Comment by rwjblue** [comment]
Publishing happens in CI and the CI job had an error.

**Comment by rwjblue** [comment]
I just fixed the linting issue and triggered another build. Should be published once https://github.com/emberjs/ember.js/actions/runs/391896947 completes successfully.

**Comment by rwjblue** [comment]
[v3.22.2 is published now](https://www.npmjs.com/package/ember-source/v/3.22.2)
