### ISSUE TITLE
[Bug] <datalist> <option> causes Uncaught Error: unreachable

### ISSUE THREAD

**Issue by srsgores** [emberjs/ember.js#19283]
### 🐞 Describe the Bug
Templating the [`<datalist>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) element with [`<option>`s](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option) causes the error `Uncaught Error: uncrechable`:

> util.js:165 Uncaught Error: unreachable
    at unreachable (util.js:165)
    at Object.evaluate (runtime.js:3182)
    at AppendOpcodes.evaluate (runtime.js:2008)
    at LowLevelVM.evaluateSyscall (runtime.js:4927)
    at LowLevelVM.evaluateInner (runtime.js:4883)
    at LowLevelVM.evaluateOuter (runtime.js:4875)
    at JitVM.next (runtime.js:5824)
    at JitVM.execute (runtime.js:5799)
    at TryOpcode.handleException (runtime.js:5054)
    at UpdatingVMFrame.handleException (runtime.js:5224)

### 🔬 Minimal Reproduction
Write a template that generates `<option>`s within a `<datalist>` element:

`autocomplete-input.hbs`
```hbs
<form action="" role="search" aria-label="Search for {{this.modelName}}...>
	<label for="{{this.elementId}}-autocomplete">{{this.autocompletePrompt}}</label>
	<input type="search" id="{{this.elementId}}-autocomplete" autocomplete required list="{{this.elementId}}-options" autofocus {{on "keydown" this.fetchMatches}}/>
</form>

{{#if this.options.length}}
	<datalist id="{{this.elementId}}-options">
		{{#each this.options as |option|}}
			<option>{{option.name}}</option>
		{{/each}}
	</datalist>
{{/if}}

{{yield}}
```

### 🌍 Environment

- Ember: - `3.18.1`
- Node.js/npm: - `15.1.0`
- OS: - Windows 10 x64
- Browser: - Chromium 85

### ➕ Additional Context
Replacing `<option>` with `<x-option>` causes the error to no longer get thrown and renders as expected with glimmer.

**Comment by locks** [comment]
Hi @srsgores, the error message could be a bit more useful here, but I'm certain there's at least a linting warning against this. The problem is that when you do `<option>` Ember is actually trying to render the value of the block argument `|option|`. The way to avoid it is to not name block arguments the same as HTML tags, so something like `opt` should work!
