### ISSUE TITLE
[Bug] Property "_super" is enumerable on Array, creating conflicts with external libs (ex : Quantcast Choice RGPD)

### ISSUE THREAD

**Issue by OsaAjani** [emberjs/ember.js#19289]
### 🐞 Describe the Bug
When extending javascript's native Array object, ember.js add a property _super to Array, and this property is enumerable, making it appear as a user property when using `for..in` on an array.

This behavior may conduct to unexpected results and so create conflicts with externals libraries.

### 🔬 Minimal Reproduction

Iterating over an array of objects with `for..in` and setting a new property to the current object will raise an error.

- Ember Twiddle: https://ember-twiddle.com/0a1aeb1142d7a07981f9203fb8836984

### 😕 Actual Behavior
This particular code will create an exception : Uncaught TypeError: can't define property "newproperty": Function is not extensible.

This is because the `for..in` loop will pass `_super` as an enumerable entry, and so we will try creating a new property name `newproperty` on the entry associated with `_super`, which is the function ROOT(), which is not extensible, and so an exception is raised.

### 🤔 Expected Behavior
`_super` should not be iterable as this is creating a strong conflict with normal JS's arrays behavior, and risk to introduce conflict with externals libs.

### 🌍 Environment

- Ember: 3.18.1 (and probably many other, originally discovered using Discourse forum which use ember.js in version 
- Node.js/npm: -
- OS: Linux (maybe others)
- Browser: Firefox, Chromium, probably others

### ➕ Additional Context
As an example of a conflict with externals libraries, i've discovered this bug because of an issue using the Quantcast's Choice.js solution for RPGD consent on a Discourse forum.

You can actually find the issue i've opened on the Discourse forum : https://meta.discourse.org/t/conflict-with-quantcast-rgpd-solution-choice-and-ember-js/170896/6

This issue offer a more detailed description of the bug, and also **a quickfix i've found to make `_super` not enumerable anymore and so fix this bug even on old versions.**

PS : I would really need someone to confirm if this is a bug or a strange but expected behavior ?

**Comment by rwjblue** [comment]
I wouldn't have expected `Array.prototype._super` to be enumerable... 🤔

**Comment by velrest** [comment]
What is the current state of this bug? I also ran into this issue a while ago and may only be able to resolve this by the mercy of the library authors accepting a fix which is caused by this issue.

**Comment by pabloascarza** [comment]
Any updates on this bug?? i have the same issue using pdfjs

**Comment by kategengler** [comment]
Thanks for pointing that out, @Windvis
