### ISSUE TITLE
[Bug] action is firing on a disabled button which has child HTML elements

### ISSUE THREAD

**Issue by nag5000** [emberjs/ember.js#19285]
### 🐞 Describe the Bug

`{{action ...}}` fires on a disabled button only under the following conditions:
- jquery integration is off
- when clicking on an inner html element

```hbs
NOT OK <button {{action "foo"}} disabled><span>span is clickable!</span></button>
OK <button {{action "foo"}} disabled>not clickable</button>
OK vanilla: <button disabled onclick="alert(1)"><span>not clickable</span></button>
```

I have reproduced this on different ember versions between 3.4 and 3.18 on ember-twiddle.
It does not reproduce if jquery integration is enabled.

Possibly related to #16779.

### 🔬 Minimal Reproduction
https://ember-twiddle.com/93301a950a603f3ca5ea2657eb72b71a?openFiles=templates.application%5C.hbs%2C

### 😕 Actual Behavior
`{{action ...}}` fires on a disabled button when clicking inner span (w/o jquery integration).

### 🤔 Expected Behavior
`{{action ...}}` does not fire on a disabled button when clicking inner span (w/o jquery integration).

### 🌍 Environment

- Ember: any 3.x?
- Node.js/npm: -
- OS: linux
- Browser: chrome 86, 87

### ➕ Additional Context

Tmp workaround?
```css
button[disabled] > * { pointer-events: none }
```

**Comment by lifeart** [comment]
@nag5000 is it working for:

```hbs
<button {{on "click" (action "foo")}} disabled><span>span is clickable!</span></button>
```

?

**Comment by nag5000** [comment]
@lifeart Hmm, everything seems ok with `{{on "click"}}` - it does not fire on a disabled button with span.
So, the problem only with old classic `{{action}}`.

**Comment by kboucher** [comment]
@nag5000 I am able to reproduce this issue using the `on` modifier (as long as there is inner HTML in the button).

**Comment by locks** [comment]
Thanks for reporting and the follow up! Since `{{on}}` seems to work and it is the current recommendation, I am closing this issue as stale.
