### ISSUE TITLE
Remove unused projects?

### ISSUE THREAD

**Issue by sandstrom** [emberjs/ember.js#19294]
These doesn't seem to be used. Maybe they can be removed?

Having stale data is confusing + makes the project seem less active than it is.

https://github.com/emberjs/ember.js/projects/5
https://github.com/emberjs/ember.js/projects/1
https://github.com/emberjs/ember.js/projects/6
https://github.com/emberjs/ember.js/projects

**Comment by locks** [comment]
Removed irrelevant ones, thanks for the ping.
