### ISSUE TITLE
[Bug] aria-labelledby is not acknowledged

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#19301]
### 🐞 Describe the Bug
Screen reader announces stale `aria-labelledby`.

### 🔬 Minimal Reproduction
At first, I thought this was a Chrome bug - because it only happens in Chrome.

But, I have created a minimal reproduction in [Ember Twiddle](https://ember-twiddle.com/c5cbb3cd7b3d3a031b6f88a18fef5c52?openFiles=templates.application%5C.hbs%2C) and [JS Fiddle](https://jsfiddle.net/amk221/zx6Lvhs2/), and only the Ember one has the issue.

### 😕 Actual Behavior
* Tab into the list box
* Listen to Voice Over announce the text content for the element associated with `aria-labelledby` ✅
* Tab out of the list box
* Hit Enter on the button (This changes the text content of the label)
* Tab back into the list box
* Listen to Voice Over announce stale text content ❌

### 🤔 Expected Behavior
* Tab into the list box
* Listen to Voice Over announce the text content for the element associated with `aria-labelledby` ✅
* Tab out of the list box
* Hit Enter on the button (This changes the text content of the label)
* Tab back into the list box
* Listen to Voice Over announce the text content for the element associated with `aria-labelledby` ✅

### 🌍 Environment

- Ember: 3.18
- Node.js/npm: 10.16.0/6.14.9
- OS: Big Sur
- Browser: Chrome 87.0.4280.88

### ➕ Additional Context
* It works as expected in Safari
* Removing the `role` attribute from the label fixes the issue, but I need it.

**Comment by rwjblue** [comment]
@MelSumner - Have you seen this before?

**Comment by amk221** [comment]
@MelSumner Would be fab if you have time to confirm my demonstrations!

**Comment by MelSumner** [comment]
I'm adding this to my todo list now- thanks for the ping (and apologies for the delay!).

**Comment by MelSumner** [comment]
@amk221 there's a few issues going on here; if any browser does make this (not valid) code work then it's doing some extra work for you. But I would not expect this code to work. 

1. the label should be outside the listbox, not inside of it. 
2. the label should not have `role="button"`
3. if you absolutely must use listbox and can't use a native select element, see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role

**Comment by amk221** [comment]
Thanks for investigating.

In a real world app, of course selecting an option would set `aria-selected="true"` and the label element would be updated to contain replica text content of the option that was just selected. But it was intended to be a minimal reproduction. I should have made it more minimal and excluded more markup to make my point.

Anyway.... it seems to be working now so I can only assume it was in fact a Chrome issue after all.

Thanks
