### ISSUE TITLE
[Bug] Infinite rendering invalidation detected

### ISSUE THREAD

**Issue by spicalous** [emberjs/ember.js#19311]
### 🐞 Describe the Bug

I am observing the result of a boolean generated by the following method on a Model by referencing it in a template
```
// models/parent.js
export default class extends Model {
  @hasMany('child') children;

  get childrenLoading() {
      return this.hasMany('children').load().isPending;
  }
}
```
This seems to work in Ember 3.20.3 but causes infinite rendering invalidation in 3.20.4. 
I have narrowed it down to this commit https://github.com/emberjs/ember.js/commit/ec8f1503562b738da885ab91daa3dc4828fbc039 which updates glimmer from 0.55.2 to 0.55.3

### 🔬 Minimal Reproduction

Ember app with minimal example https://github.com/spicalous/ember-rerender-invalidation-example
Use case reference https://stackoverflow.com/questions/65278813/how-to-detect-if-included-relationship-is-loading
Relevant code to reproduce bug https://ember-twiddle.com/af0a823fc73474db1c09083c429fef4f (ember twiddle is using Ember 3.18 which works)

### 😕 Actual Behavior
Infinite rendering invalidation error thrown

### 🤔 Expected Behavior
Ember does not infinitely rerender

### 🌍 Environment

- Ember: 3.20.4
- Node.js/npm: 10.19.0/6.14.4
- OS: Ubuntu
- Browser: FF

**Comment by lifeart** [comment]
@spicalous async logic not supported in getters, you should avoid calling `load()` inside it.

**Comment by spicalous** [comment]
@lifeart Thanks for the alternative example!  

Unfortunately for me this still throws an assertion error 😔

> Uncaught Error: Assertion Failed: You attempted to update `numRunning` on `<Task:childrenLoadTask>`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.

I am using the property in the template like so
```
{{#if this.model.childrenLoading}}
  // show spinner
{{else}}
  // show model.children
{{/if}}
```

Using `ember-concurrency@1.3.0`

I found an issue raised in ember-concurrency repo that describes the same error: https://github.com/machty/ember-concurrency/issues/378

**Comment by NullVoxPopuli** [comment]
is this still an issue?
