### ISSUE TITLE
[Documentation] `templateOnly` appears in the wrong area, under `Controller` methods

### ISSUE THREAD

**Issue by pzuraq** [emberjs/ember.js#19325]
### 📙 Describe the Issue

`templateOnly` is importable from `@ember/component/template-only` according to the documentation, but it shows up in the API docs for Controller as a method.

### 🔬 Minimal Reproduction

https://api.emberjs.com/ember/3.23/classes/Controller/methods/templateOnly?anchor=templateOnly

### 😕 Actual Behavior

Appears in the Controller API docs

### 🤔 Expected Behavior

Should appear as a submodule of `@ember/component`

**Comment by Windvis** [comment]
I think I figured out what causes this. The templateOnly doc comment describes a `@method` but the  `@ember/component/template-only` module doesn't define a class. By default YUIDoc seems to link methods to the class that was last parsed (and in this case that seems to be the Controller class).

From the YUIDoc syntax reference:
> `@method` Indicates that the block describes a method for the current class. By default, the "current" class is the last class that YUIDoc parsed, but you can reset this with the @for tag.

So the fix would be to add a `@for` to the doc comment. Itt seems that other exports are documented that way as well. [For example the runloop exports.](https://github.com/emberjs/ember.js/blob/79f130f779a58969b98d079acf7d0e83c81dae63/packages/%40ember/runloop/index.js#L257-L261)
