### ISSUE TITLE
[Bug] Helper crashes renderer with current beta (regression)

### ISSUE THREAD

**Issue by kanongil** [emberjs/ember.js#19331]
### 🐞 Describe the Bug

CI suddenly fails for https://github.com/kanongil/ember-stable-hash on beta and canary.

### 🔬 Minimal Reproduction

Failing [helper](https://github.com/kanongil/ember-stable-hash/blob/master/addon/helpers/stable-hash.js):
```js
import { setProperties } from '@ember/object';
import Helper from '@ember/component/helper';

export default class StableHash extends Helper {
  constructor(...args) {
    super(...args);

    this.obj = {};
  }

  compute(positional, named) {
    setProperties(this.obj, named);
    return this.obj;
  }
}
```

Fails the tests in [stable-hash-test.js](https://github.com/kanongil/ember-stable-hash/blob/master/tests/integration/helpers/stable-hash-test.js). Eg. this:
```js
test('returns a hash with the right key-value', async function(assert) {
  await render(hbs`{{#with (stable-hash name=\"Sergio\") as |person|}}{{person.name}}{{/with}}`);

  assert.dom().hasText('Sergio');
});
```

### 😕 Actual Behavior

```
not ok 1 Chrome 62.0 - [138 ms] - helper:stable-hash: returns a hash with the right key-value
    ---
        actual: >
            [object Object]
        stack: >
            TypeError: _a.call is not a function
                at meta (http://localhost:7357/assets/vendor.js:43790:86)
                at compilable (http://localhost:7357/assets/vendor.js:45534:51)
                at TemplateImpl.asLayout (http://localhost:7357/assets/vendor.js:46242:28)
                at new OutletComponentDefinition (http://localhost:7357/assets/vendor.js:7444:150)
                at http://localhost:7357/assets/vendor.js:9062:13
                at http://localhost:7357/assets/vendor.js:47061:37
                at track (http://localhost:7357/assets/vendor.js:57034:7)
                at valueForRef (http://localhost:7357/assets/vendor.js:47060:44)
                at Assert.evaluate (http://localhost:7357/assets/vendor.js:50032:48)
                at UpdatingVM._execute (http://localhost:7357/assets/vendor.js:52711:16)
        message: >
            _a.call is not a function
        negative: >
            false
        browser log: |
            ERROR:

            Error occurred:

            - While rendering:
              -top-level
                application
```
### 🤔 Expected Behavior

Pass the test, like the current release.

### 🌍 Environment

- Ember: current beta & canary
- Node.js/npm: v10.23.1 / 6.14.10
- OS: trusty

**Comment by pzuraq** [comment]
FWIW, `{{hash}}` should now also be more stable, in the sense that it will only generate a new object whenever the arguments change. It seems like this helper does go a step further though, using the same object always.

**Comment by pzuraq** [comment]
So this is being caused by an older version of `babel-plugin-htmlbars-inline-precompile`. Specifically, this code causes the issue: https://github.com/ember-cli/babel-plugin-htmlbars-inline-precompile/blob/v3.2.0/index.js#L22

It doesn't account for values that could either be `null`, or `function` values, and so it changes anything that was potentially null or a function into an object. This results in our code seeing a value called `scope`, which should be `null` but is instead an object, and then attempting to call it as a function.

Updating `ember-cli-htmlbars` fixes this problem in this repository. I'm unsure if we should try to fix this from the Ember side, thoughts @rwjblue?

**Comment by rwjblue** [comment]
> Updating ember-cli-htmlbars fixes this problem in this repository. I'm unsure if we should try to fix this from the Ember side, thoughts @rwjblue?

@pzuraq - We should probably not emit a function (or null) if we aren't in strict mode, that _should_ fix the issue right?

**Comment by Kennie-create** [comment]
Public example of this bug can be found here : https://github.com/ember-learn/ember-styleguide/pull/361
