### ISSUE TITLE
Vulnerability found in one of the dependency - Cache-base

### ISSUE THREAD

**Issue by karthiksubbiah1983** [emberjs/ember.js#19335]
└─┬ ember-cli@3.24.0
└─┬ sane@4.1.0
└─┬ micromatch@3.1.10
└─┬ snapdragon@0.8.2
└─┬ base@0.11.2
└── cache-base@1.0.1

Would the ember team prioritize this to resolve?

**Comment by lifeart** [comment]
@karthiksubbiah1983  could you open issue for https://github.com/ember-cli/ember-cli ?
