### ISSUE TITLE
ember-source@3.24.x - wrong building of vendor.js (effects only in chrome)

### ISSUE THREAD

**Issue by Timbuktu1982** [emberjs/ember.js#19340]
### 🐞 Describe the Bug
When i install the version 3.24.x, i become a problem in the generated file "vendor.js" (dist). Inside the function invoke() the generator builds problematically code. The browser "chrome" cannot handle this problem. The browser "FireFox" has no problem with this code.

### 🔬 Minimal Reproduction
Build a app with ember-source@3.24.x.

[Problematically code since ember-source@3.24.x]
invoke(methodName, ...args) {
      var ret = A();
      this.forEach(item => ret.push(item[methodName]?.(...args)));
      return ret;
    },
    
[Functionallity code - eg with ember-source@3.23.1]
invoke(methodName, ...args) {
      var ret = A();
      this.forEach(item => ret.push((0, _utils.tryInvoke)(item, methodName, args)));
      return ret;
    },
    
### 🌍 Environment

ember-cli: 3.24.0
node: 14.1.0
os: linux x64

{
  "name": "xxx",
  "version": "0.2.0",
  "private": true,
  "description": "The general app for the project of ....",
  "repository": "",
  "license": "MIT",
  "author": "Oliver Schmidt | Time4Innovation",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build --environment=production",
    "lint:hbs": "ember-template-lint .",
    "lint:js": "eslint .",
    "start": "ember serve",
    "test": "ember test"
  },
  "devDependencies": {
    "@ember/jquery": "^1.1.0",
    "@ember/optional-features": "2.0.0",
    "@glimmer/component": "1.0.3",
    "@glimmer/tracking": "1.0.3",
    "@mdi/svg": "5.9.55",
    "babel-eslint": "^10.1.0",
    "broccoli-asset-rev": "^3.0.0",
    "ember-auto-import": "^1.6.0",
    "ember-cli": "3.24.0",
    "ember-cli-app-version": "4.0.0",
    "ember-cli-babel": "7.23.0",
    "ember-cli-dependency-checker": "^3.2.0",
    "ember-cli-eslint": "^5.1.0",
    "ember-cli-htmlbars": "5.3.1",
    "ember-cli-inject-live-reload": "^2.0.2",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-template-lint": "^2.0.2",
    "ember-cli-uglify": "^3.0.0",
    "ember-data": "3.24.0",
    "ember-export-application-global": "^2.0.1",
    "ember-fetch": "8.0.3",
    "ember-hammertime": "^1.6.0",
    "ember-load-initializers": "^2.1.1",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-mdi": "^0.8.2",
    "ember-qunit": "5.1.1",
    "ember-resolver": "8.0.2",
    "ember-source": "^3.23.1",
    "ember-welcome-page": "^4.0.0",
    "eslint-plugin-ember": "10.1.2",
    "eslint-plugin-node": "^11.1.0",
    "loader.js": "^4.7.0",
    "qunit-dom": "1.6.0",
  },
  "engines": {
    "node": "10.* || >= 12"
  },
  "ember": {
    "edition": "octane"
  },
  "dependencies": {
    "@ember/test-helpers": "^2.1.4",
    "ember-cli-sass": "^10.0.1",
    "ember-concurrency": "1.3.0",
    "liquid-fire": "^0.31.0",
    "qunit": "^2.14.0",
    "sass": "1.32.4"
  }
}

**Comment by rwjblue** [comment]
I'm not sure I really understand the issue being reported here. Are you getting an error? If so, please share the stack trace. What versions of Chrome / FireFox? Is this development build or production build?

---

The main thing that I note in the snippet differences is the usage of optional chaining where there was previously using the `tryInvoke` utility method. Chrome fully supports the optional chaining syntax though, so that shouldn't be an issue.

**Comment by Timbuktu1982** [comment]
Hey rwjblue.
Thank you for your feedback.
The problem is, the builds (dev and prod) are not usable in chrome. You get a syntax error (.? - the point is not allowed) and as second failure  "define is not defined" (in the [appName].js) in the console and a white screen will be showed in browser, because its a fatal error. 
I use Chrome Version 79.0.3945.130 (Offizieller Build) (64-Bit).
The same problem i have on mobilephones. By using the normal browser and also the inappbrowser of cordova builds.

**Comment by Timbuktu1982** [comment]
Do you need more informations?

**Comment by pzuraq** [comment]
@Timbuktu1982 it sounds like you are using an older version of Chrome which does not support optional chaining. See the support matrix for optional chaining [here](https://caniuse.com/mdn-javascript_operators_optional_chaining).

Google Chrome does not have LTS support and the general recommendation is to use the most up to date version of Chrome, currently 87. By default, Ember only transpiles to support the current and last version of all browsers. If you need to use an older version of Chrome for some reason, then you can modify your `config/targets.js` file to match the Chrome version that you need to support, and the JavaScript will be transpiled for that version instead. See the documentation for [browserslist](https://github.com/browserslist/browserslist#full-list) for more information about how to specify transpilation targets.

**Comment by rwjblue** [comment]
At the moment, you can also add Chrome 79 to your `config/targets.js` if you really must maintain that specific chrome version.

**Comment by Timbuktu1982** [comment]
**Hey pzuraq and rwjblue,**

thank you for the solution. I have updated chrome and now it works fine :-)
For my customers with older version i give the recommendation to update their browsers.

**Comment by locks** [comment]
Thanks for the update, glad to see the problem resolved!
