### ISSUE TITLE
[Bug] Babel build error when using specific targets

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#19354]
### 🐞 Describe the Bug
When using `firefox 47` in `targets.js` I get this error: `Expected type "Expression" with option undefined, but instead got "SpreadElement"`.

### 🔬 Minimal Reproduction
[Here is a reproduction](https://github.com/boris-petrov/ember-babel-bug). Clone, `npm install`, `ember serve`. Funnily enough, `firefox 35` in `targets.js` works.

### 😕 Actual Behavior

```
Build Error (broccoli-persistent-filter:Babel > [Babel: ember-babel-bug]) in ember-babel-bug/components/foo-component.js

/home/boris/code/ember-babel-bug/ember-babel-bug/components/foo-component.js: Expected type "Expression" with option undefined, but instead got "SpreadElement".


Stack Trace and Error Report: /tmp/error.dump.a96b4e10d285dc5084d3aa19d6cb1e36.log
```

### 🤔 Expected Behavior
`ember serve` should work and no Babel error should happen.

### 🌍 Environment

- Ember: 3.24.1
- Node.js/npm: v15.6.0
- OS: Linux
- Browser: -

P.S. Not sure if this is an Ember.js problem or rather an `ember-cli` one but feel free to move the issue to the appropriate place.

**Comment by rwjblue** [comment]
Hmm, this doesn't really seem like an Ember / ember-cli bug to me (it may be an issue with Babel though). Can you test the same code with plain Babel (+ @babel/preset-env)?

**Comment by boris-petrov** [comment]
@rwjblue - I did try it on the [Babel REPL](https://babeljs.io/repl#?browsers=firefox%2047&build=&builtIns=false&spec=false&loose=true&code_lz=JYWwDg9gTgLgBAYQuCA7Apq-AzKy4DkAAgOYA2oI6UA9AMbKQZYEDcAUKJLHMFtQGd0dGMDRxc-AmQgATAIYCAFjT4xBw0Wjbt26AB7d4s9NnkBXMvDplFAuADEIEJCmbwD61LPuummeABvdjg4RQBPVDoJZwAKAEo4YNDQtQ0RMVRYgDpc2PkAd3lgeAAFPBBgIWz5MjJYgG0AXXjWjlCAX3YOoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-1&prettier=true&targets=Node-14.14&version=7.12.12&externalPlugins=) and it seems to work fine. I'm not sure, however, if the options are the same that Ember uses.

**Comment by boris-petrov** [comment]
You are correct. I hadn't set the options correctly in the Babel REPL. I've opened an [issue there](https://github.com/babel/babel/issues/12690).
