### ISSUE TITLE
[Bug] 3.25.0-beta.3: curly component names are normalized differently

### ISSUE THREAD

**Issue by dfreeman** [emberjs/ember.js#19360]
### 🐞 Describe the Bug
In `ember-source@3.25.0-beta.2` and prior, a component invoked in block form like `{{#pkg::component-name}}` would be looked up via the resolver as `pkg::component-name`.

Starting with `beta.3` with the upgrade to `glimmer-vm@0.73.2`, that name is normalized via `customizeComponentName` to become `pkg/component-name`. For a customized resolver where `::` is a meaningful token, such components no longer resolve correctly.

### 🔬 Minimal Reproduction

The following is resolved as `component:pkg::component-name` in beta.2, but `component:pkg/component-name` in beta.3:

```hbs
{{#pkg::component-name}}
  hello!
{{/pkg::component-name}}
```

Note that an inline invocation like `{{pkg::component-name}}` does not go through `customizeComponentName` and so still resolves as before.

### 😕 Actual Behavior
Block curly component names have `::` normalized to `/`.

### 🤔 Expected Behavior
Block curly component names aren't subjected to the same normalization rules as angle-bracket components, as in prior releases.

### 🌍 Environment

- Ember: 3.25.0-beta.3

### ➕ Additional Context

Additional discussion of the details of this issue is at https://github.com/glimmerjs/glimmer-vm/pull/1255

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/19363
