### ISSUE TITLE
[Question] Uncaught Error: Assertion Failed: Config object passed to computed can only contain `get` and `set` keys.

### ISSUE THREAD

**Issue by AravinthAro** [emberjs/ember.js#19394]
Unable to run Ember addon's dummy app.

- Ember: - 3.8.1
- Node.js/npm: - 10.22.0/6.12.0
- OS: - Windows 64
- Browser: - All major browsers

Tried clean re-install of node_modules.

**Comment by rwjblue** [comment]
Hmm, this issue doesn't really have any details. What is the code in question? The error message seems to indicate exactly what is wrong (someone is passing additional properties to `computed` as far as I can tell).

What leads you to believe this is a bug in Ember itself (and not a bug in your add-ons code)?

**Comment by AravinthAro** [comment]
Oops, I have edited my question. I don't think it's a bug in Ember. This same addon works fine for my teammates. But I'm getting this error. I can't find any proper fix for this. Even couldn't find anyone reported the same error. I haven't made any change in code, so there is no code in question particularly. I believe this has to do with the configuration of the app. Thought if anyone who have faced the same issue might provide a solution.

**Comment by coderShah11** [comment]
I 

> Oops, I have edited my question. I don't think it's a bug in Ember. This same addon works fine for my teammates. But I'm getting this error. I can't find any proper fix for this. Even couldn't find anyone reported the same error. I haven't made any change in code, so there is no code in question particularly. I believe this has to do with the configuration of the app. Thought if anyone who have faced the same issue might provide a solution.

I am facing the same issue.  I have Upgraded node-version from 10 to 12 and with out changing and underlying ember code. Then I get this error
