### ISSUE TITLE
[Bug] Incorrect "import htmlSafe from '@ember/string'" deprecation warning when importing from '@ember/template' 

### ISSUE THREAD

**Issue by urbany** [emberjs/ember.js#19393]
Hi everyone, after upgrating to latest stable ember-source@3.25.1 I'm getting:

> DEPRECATION: Importing htmlSafe from '@ember/string' is deprecated. Please import htmlSafe from '@ember/template' instead. [deprecation id: ember-string.htmlsafe-ishtmlsafe]

the thing is my helper is importing correctly:
`import { htmlSafe } from '@ember/template';
`
but when i check the compiled version on the browser it is compiling to:
`Ember.String.htmlSafe`

which is triggering the deprecation warning.

@locks suggested on Discord it might be related to https://github.com/ember-cli/ember-rfc176-data needing an update

**Comment by locks** [comment]
We seem to have missed some necessary work for the correct implementation of the deprecation. I will be using this comment to track the necessary work.

## Tracking

- [ ] Nerf deprecation in a patch
- [ ] export non-deprecated `htmlSafe` and `isHTMLSafe` from a private namespace in the `Ember` global, e.g. `Ember._Template`
- [ ] figure out how to have per-Ember version mappings in ember-rfc176-data
- [ ] incorporate change in [babel-plugin-ember-modules-api-polyfill](https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill) and [ember-cli-babel](https://github.com/babel/ember-cli-babel)
- [ ] re-introduce deprecations for `htmlSafe` and `isHTMLSafe`
  - [ ] make sure that `String.prototype.htmlSafe` is deprecated

**Comment by jamescdavis** [comment]
As the person who did the [original deprecation PR](https://github.com/emberjs/ember.js/pull/19339), I apologize for the inconvenience!

**Comment by nadnoslen** [comment]
Not that big of a deal @jamescdavis 😉

**Comment by DLiblik** [comment]
> Not that big of a deal @jamescdavis 😉

Tell that to our CI server test logger LOL... just found this out today when our log files went super-nova recently

All good!
