### ISSUE TITLE
[Bug] Since 3.22 {{did-update does not trigger when value changed on insert

### ISSUE THREAD

**Issue by st-h** [emberjs/ember.js#19403]
### 🐞 Describe the Bug
With ember <= 3.21, the `{{did-update` modifier would fire, when a value would be changed on `{{did-insert`. Starting with ember 3.22 this no longer seems to be the case (tested up to 3.25)

### 🔬 Minimal Reproduction

A simple component to reproduce this issue:

```
<div {{did-insert this.onInsert}}
     {{did-update this.onChange this.testValue}}>
     If you do not see an alert, this test failed....
</div>
```

```
import Component from '@glimmer/component';
import { action } from '@ember/object';
import { tracked } from '@glimmer/tracking';

export default class TestBoxComponent extends Component {

  @tracked testValue = false;

  @action
  onInsert() {
    this.testValue = true;
  }

  @action
  onChange() {
    alert('test successful');
  }
}
```

Repro:
https://github.com/st-h/ember-did-update
Change ember-source in `package.json` to `3.22.0` in order to make it fail.

### 😕 Actual Behavior
`{{did-update` does no longer fire when the value is changed from within `{{did-insert`.

### 🤔 Expected Behaviour
`{{did-update` triggers whenever the value changes.

### 🌍 Environment

- Ember: >= 3.22
- Node.js/npm: v15.4.0/7.0.15
- OS: MacOS 10.15.7
- Browser: -

**Comment by st-h** [comment]
Had some help in discord and we figured that it would be better to move what I had in `did-insert` into the constructor of the component. It was somewhat considered expected behaviour when a value that is updated in `did-insert` did not fire `did-update`. I'll leave this issue open, so it can be decided if the change from ember 3.21 to 3.22 is considered a regression.

**Comment by patricklx** [comment]
might be same issue as https://github.com/emberjs/ember-render-modifiers/issues/20

**Comment by st-h** [comment]
I'll close this issue as there is no point in deciding if a change that happened more than a year ago would be considered a regression.
