### ISSUE TITLE
[Bug] 3.24.2: `href` missing from links in rendering tests

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#19408]
### 🐞 Describe the Bug

In a rendering test that calls `this.owner.setupRouter()` the `href` of a `LinkTo` component could be tested in 3.24.1 and below, but with 3.24.2 this no longer works and the `href` is missing.

### 🔬 Minimal Reproduction

```js
    test('foo', async function (assert) {
      this.owner.setupRouter();

      await render(hbs`<LinkTo @route="login">test</LinkTo>`);
      assert.dom('a').hasAttribute('href', `/login`);
    });
```

### 😕 Actual Behavior

> Actual: Element a does not have attribute "href"

### 🤔 Expected Behavior

> Expected: Element a has attribute "href" with value "/login"

### 🌍 Environment

- Ember: 3.24.2

/cc @rwjblue @xg-wang

**Comment by xg-wang** [comment]
This regression should be fixed by https://github.com/emberjs/ember.js/pull/19395 once we have a release out

**Comment by boris-petrov** [comment]
What about 3.25.1?

**Comment by Turbo87** [comment]
@xg-wang great, thanks. must've missed that PR when I searched for related issues 🙈

**Comment by rwjblue** [comment]
@boris-petrov - Both 3.24 and 3.25 should have patch releases with the fix. There are a number of regressions that I'm trying to coalesce into a patch release (for both), will try to do releases either tomorrow or Wednesday with whatever has landed by then.

**Comment by igbopie** [comment]
Same here. 3.24.1 works fine were as 3.24.2 breaks the tests.

**Comment by esbanarango** [comment]
👋 Same issue with `ember-source` `3.25.1`.

**Comment by esbanarango** [comment]
I just tried with `3.26.0-beta.3` and the `href` is there BUT it is ALWAYS blank.

**Comment by rwjblue** [comment]
Hmm, that is odd. We have explicit tests for this over in https://github.com/emberjs/ember.js/pull/19395.

@esbanarango - Do you have a basic reproduction?

@xg-wang - Mind taking a look?

**Comment by rwjblue** [comment]
Other than the report above (for 3.26.0-beta.3) the fixes have been released for 3.24.3 and 3.25.3. Leaving this open so we can investigate @esbanarango's report above (if correct we will need further fixes for 3.24 + 3.25).

**Comment by xg-wang** [comment]
This should have been fixed by new releases today. I just reran the super-rental-tutorial https://github.com/ember-learn/super-rentals-tutorial/pull/176

**Comment by esbanarango** [comment]
@xg-wang @rwjblue The issue I was having is actually related with https://github.com/buschtoens/ember-link https://github.com/buschtoens/ember-link/issues/554

So I think we can close this.
