### ISSUE TITLE
[Bug] `if` helper returns `null` instead of `undefined`

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#19409]
### 🐞 Describe the Bug

The `else` path of an inline `if` helper used to return `undefined`, but starting with v3.25 it now returns `null`, which can be problematic in components that check for the existence of an argument via `this.args.foo !== undefined`.

### 🔬 Minimal Reproduction

```hbs
<SomeComponent @foo={{if this.bar "baz"}} />
```

### 😕 Actual Behavior

When `bar` is truthy then `foo` will be `"bar"`, if not, then it will be `null`.

### 🤔 Expected Behavior

When `bar` is truthy then `foo` will be `"bar"`, if not, then it will be `undefined`.

### 🌍 Environment

- Ember: 3.25.1

**Comment by rwjblue** [comment]
This is a bit unfortunate to care about 🤔. We definitely *can* fix it, but I'm not sure that this is something that we had explicitly intended. 🤔

**Comment by rwjblue** [comment]
The inline if implementation is here:

https://github.com/glimmerjs/glimmer-vm/blob/e4be62c16360fba63388a4316a6562a57954bbb4/packages/%40glimmer/runtime/lib/compiled/opcodes/expressions.ts#L245-L259

But the thing that returns `null` I think is done at compilation time here:

https://github.com/glimmerjs/glimmer-vm/blob/e4be62c16360fba63388a4316a6562a57954bbb4/packages/%40glimmer/compiler/lib/passes/2-encoding/expressions.ts#L153

**Comment by rwjblue** [comment]
Oh, also, you can work around this by explicitly returning undefined in the else:

```hbs
<SomeComponent @foo={{if this.bar "baz" undefined}} />
```

**Comment by Turbo87** [comment]
> This is a bit unfortunate to care about

maybe, but it looks like we're not the only ones who got bitten by this: https://discord.com/channels/480462759797063690/480462759797063692/809912104240545812

in our case about 900 tests are failing in the test suite due to this unintentional change 😅 

I guess usually I would just do `if (this.arg.foo) {...}`, but since `@foo` can be a number in our case and that number is allowed to be zero we went for the `this.arg.foo !== undefined` check.
