### ISSUE TITLE
[Bug] Inline if eagerly evaluates both results before test clause returns

### ISSUE THREAD

**Issue by rtablada** [emberjs/ember.js#19404]
### 🐞 Describe the Bug
In 3.17-3.21 (importantly this includes LTS 3.20) the inline `if` helper eagerly evaluates both return actions regardless of the value of the test clause. This appears to only happen when one of the result actions uses a helper and that helper is passed in a component argument.

### 🔬 Minimal Reproduction

1. Create a new Ember app
2. Create a component `my-component` that uses and inline `if` and helpers for the return values (the test condition does not seem to matter)
3. Invoke the component with an arg used by the if statement results

[Github Repo](https://github.com/rtablada/ember-if-question)
[Code Sandbox](https://codesandbox.io/s/affectionate-waterfall-ko8qu?file=/app/components/navigation.hbs)

### 😕 Actual Behavior
When the inline `if` statement uses a helper with a component argument as a param as one of the possible results, both results are evaluated.

### 🤔 Expected Behavior
The expected behavior (and behavior in 3.16 or >3.22) would be that only the subtree/action for the correct value would be evaluated, and that this would only be evaluated after the logic test was assessed.

### 🌍 Environment

- Ember: - 3.17-3.21
- Node.js/npm: - Node 14
- OS: - OSX
- Browser: - Chrome

**Comment by rtablada** [comment]
I should clarify, for most use cases this likely won't matter since helpers are often stateless. However in the case where a helper could throw an error this would stop rendering and cause a potential app crash.

Example:

```hbs
{{if @param (my-angry-helper @param) (some-safe-helper @value)
```

If `my-angry-helper` throws an error when `@param` is falsey (or more likely undefined) then this error in the VM causes rendering errors.

**Comment by locks** [comment]
Addressed by making user-created helpers lazily computed in the linked PR.
