### ISSUE TITLE
[Bug] Nested LinkTo is rendered as child of parent LinkTo via FastBoot but not otherwise

### ISSUE THREAD

**Issue by barelyknown** [emberjs/ember.js#19413]
### 🐞 Describe the Bug
A nested `LinkTo` is rendered outside of its parent by FastBoot, but not otherwise.

### 🔬 Minimal Reproduction
Reproduction [available here](https://github.com/x-b-e/link-to-leak).

This is the template code that results in the unexpected (and new) behavior:

```
<LinkTo @route="application" style="font-weight: bold;">
  <LinkTo @route="application">
    I should be bold because I should be nested in the other anchor.
  </LinkTo>
</LinkTo>
```

### 🤔 Expected Behavior
I'd expect that the behavior would be the same. If that's not possible, then I'd expect a warning re: the nested `LinkTo`.

### 🌍 Environment

- Ember: 3.25.0 (FastBoot)

### ➕ Additional Context
Yes, yes... [nested anchor tags are illegal](https://www.w3.org/TR/html401/struct/links.html#h-12.2.2), and so maybe this isn't a bug, but the difference is unexpected, and so maybe it is.

**Comment by rwjblue** [comment]
Have you confirmed that the "over the wire" content is different? I expect that what you'll find is that the difference you are noticing is the result of the browsers default auto correction which happens upon parsing the invalid HTML. When not running in the server context, we never parse from HTML into DOM. Instead we build DOM up manually with things like document.createElement /.appendChild / etc, this means that the auto-correction that happens during the HTML parsing phase of the browser does not happen in the same way. I suspect this is the reason for the discrepancy. 

---

If you can confirm that the actual string returned from FastBoot (e.g. when curling the url) is structured differently than what you see when not using FastBoot, we should dig into it. However, if that curl result matches your client side rendered content but when you inspect the DOM after it has been parsed doesn't match: this isn't a bug (well, it's still a bug, but it's in your template 😆).

**Comment by barelyknown** [comment]
Oh, interesting. I’ll check/confirm. I bet you’re right.

**Comment by barelyknown** [comment]
Yeah, you were correct. The content from the server is as expected, but I was seeing the auto-corrected markup when I inspected the page, and then that was changed by the Ember app after it booted. Thanks!
