### ISSUE TITLE
[Documentation] List built in template helpers available to the developers

### ISSUE THREAD

**Issue by ianmann56** [emberjs/ember.js#19411]
### 📙 Describe the Issue
A page describing what template helpers are available to developers for use in templates. If it does already exist, it would be great to have the page linked from https://guides.emberjs.com/release/components/helper-functions/ since that page seems to be the only page that I can find that talks about helpers.

### 🔬 Minimal Reproduction
https://guides.emberjs.com/release/components/helper-functions/

### 😕 Actual Behavior
Not seeing anything about what built in helpers I have at my disposal

### 🤔 Expected Behavior
I should be able to find a document listing the different helpers that I have at my disposal.

### ➕ Additional Context
NA

**Comment by locks** [comment]
Thanks for the detailed reporting! If you scroll to the bottom of the page you can find the following:

> To consult all available built-in helpers, you can check the [template helpers API documentation](https://api.emberjs.com/ember/release/classes/Ember.Templates.helpers/).

This takes you to [https://api.emberjs.com/ember/release/classes/Ember.Templates.helpers/](https://api.emberjs.com/ember/release/classes/Ember.Templates.helpers/) where all available helpers should be listed.
I will give it a tweak because it looks a bit like part of the `{{hash}}` documentation

**Comment by ianmann56** [comment]
> Thanks for the detailed reporting! If you scroll to the bottom of the page you can find the following:
> 
> > To consult all available built-in helpers, you can check the [template helpers API documentation](https://api.emberjs.com/ember/release/classes/Ember.Templates.helpers/).
> 
> This takes you to https://api.emberjs.com/ember/release/classes/Ember.Templates.helpers/ where all available helpers should be listed.
> I will give it a tweak because it looks a bit like part of the `{{hash}}` documentation

Apparently I don't know how to read. I really have no idea how I didn't see that. Thanks so much!

It might be helpful to have a quick link at the top in case other people come to that page for the same reason and are just quickly skimming like I apparently was. Although most people would scroll the entire page I guess haha.

**Comment by locks** [comment]
The linked PR was merged with a change to hopefully make the link a bit easier to find, so I'm closing the issue as resolved :)
