### ISSUE TITLE
[Bug] Canary fails build with "unable to locate global object" 

### ISSUE THREAD

**Issue by simonihmig** [emberjs/ember.js#19431]
### 🐞 Describe the Bug
It seems pretty much all my addons are failing to build as of today at least (scheduled CI runs) with that error at build-time.

### 🔬 Minimal Reproduction

Just a small sample of addons failing CI:
* https://github.com/kaliber5/ember-window-mock/runs/1984804246?check_suite_focus=true#step:5:137
* https://github.com/kaliber5/ember-cli-bundle-analyzer/runs/1984838330?check_suite_focus=true#step:5:141
* https://github.com/kaliber5/ember-stargate/runs/1984795141?check_suite_focus=true#step:5:137
* https://github.com/kaliber5/ember-cli-yadda/runs/1984851200?check_suite_focus=true#step:5:139

### 😕 Actual Behavior

Ember-try scenario for current canary is failing with that build error.

### 🤔 Expected Behavior

Uh, build successfully? 😆

### 🌍 Environment

See CI env.

**Comment by rwjblue** [comment]
This is during template compilation, and I see the changes from https://github.com/ember-cli/ember-cli-htmlbars/pull/660 in the stack. That PR does change what Global’s are available and might be what is causing this. The other changes that I landed here for the template compiler seem somewhat less likely to be the culprit but are possibly combining with that change in a bad way 🤔

**Comment by rwjblue** [comment]
I think that this detection no longer works (combined with that ember-cli-htmlbars PR):

https://github.com/emberjs/ember.js/blob/7c39e15f09b24855bab64579e0b71729c511f5e0/packages/loader/lib/index.js#L6-L19

I will dig in this morning, I thought that `globalThis` would be defined by the vm context itself but I guess it isn’t.

**Comment by rwjblue** [comment]
Ya, so basically in Node < 12 `globalThis` isn't available (either naturally or within a `vm.createContext`).

I tested the following:

```js
const { inspect } = require('util');
const vm = require('vm');

let script = new vm.Script('(() => globalThis)()');

let context = vm.createContext({});

console.log(script.runInContext(context));
```

When running on < 12 you get:

```
ReferenceError: globalThis is not defined
    at evalmachine.<anonymous>:1:8
    at evalmachine.<anonymous>:1:19
    at Script.runInContext (vm.js:135:20)
    at Object.<anonymous> (/Users/rwjblue/src/ember-cli/ember-cli-htmlbars/test.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by rwjblue** [comment]
The fix is released in https://github.com/ember-cli/ember-cli-htmlbars/releases/tag/v5.6.1, sorry about that @simonihmig!

**Comment by rwjblue** [comment]
Oh, also, thank you very much for reporting!

**Comment by simonihmig** [comment]
Np, thanks for the quick fix! 👍
