### ISSUE TITLE
[Bug] Router Service doesn't update currentRoute on loading states

### ISSUE THREAD

**Issue by kevinkucharczyk** [emberjs/ember.js#19449]
### 🐞 Describe the Bug
The Router Service's `currentRoute` property doesn't update on loading states, even though `currentRouteName` does.

### 🔬 Minimal Reproduction
https://ember-twiddle.com/5dbab877e11a84a2ede3267d27f58c40

An example is provided in the Ember Twiddle. Note that the Twiddle is on Ember 3.18.1, but this also happens in the app I work on at Ember 3.24.1.

### 😕 Actual Behavior
When a route has a loading state and there are computeds/observers that rely on `router.currentRoute`, the `currentRoute` never shows loading state routes.

### 🤔 Expected Behavior
There should be loading routes in `currentRoute`.

### 🌍 Environment
- Ember: - 3.18.1, 3.24.1
- Node.js/npm: -
- OS: -
- Browser: -

### ➕ Additional Context
I found the same bug reported in the past at https://github.com/emberjs/ember.js/issues/17162, and it's closed now as seemingly fixed, but the bug is still present.

**Comment by sly7-7** [comment]
So I've reproduced on 3.25.1 too. 
This is at least an inconsistency, but I can't tell what the expected result should be.
Indeed, during a transition, the 'current path' properties are updated, even within a intermediate loading transition
see  
  https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/routing/lib/system/router.ts#L552
and
  https://github.com/emberjs/ember.js/blob/b64b292fbb6ab5da0255bfdb8ba87509d03780af/packages/%40ember/-internals/routing/lib/system/router.ts#L1495

But, the currentRoute is set only durin `routeDidChange` hook (https://github.com/emberjs/ember.js/blob/b64b292fbb6ab5da0255bfdb8ba87509d03780af/packages/%40ember/-internals/routing/lib/system/router.ts#L292), which is not triggered on intermediate transition.

So I would say either we should `routeDidChange` on intermediate loading transition, or we should not update the path properties during intermediate.

But looking at the underlying router.js (and also if I remember what @rwjblue said to me), it seems like it's by purpose the routeDidChange event is not triggered on intermediates (loading) transitions, or maybe we were wrong about updating this test:
https://github.com/tildeio/router.js/commit/6ba71b1a2c8ee1f3b0d3f25d700eac1b1425ddd5 when I explicitely removed the check of routeDidChange called on intermediate transitions. (before that I think the test was green only by 'luck')

cc/ @acorncom maybe tag this issue as router bug, or even discussion ?

**Comment by rwjblue** [comment]
Thanks for digging into this @sly7-7! Ultimately, I do not think we should have treated loading/error states as valid states in the router itself but obviously that ship has sailed 😝. 

> But looking at the underlying router.js (and also if I remember what @rwjblue said to me), it seems like it's by purpose the routeDidChange event is not triggered on intermediates (loading) transitions

Correct. We do not want to update intermediate transitions to emit `routeDidChange` (`routeDidChange` should only be fired for "final" route destinations, not for intermediate states).

> Finally, I don't understand why in the ember router we have an 'independant' currentRouteName not beeing just a property derived from the currentRoute

Ya, we can fix this I think.

---

I believe the best path forward here is to update `currentRouteName` directly in `intermediateTransitionTo`.

**Comment by rwjblue** [comment]
Sorry, I misspoke (thanks to @sly7-7 for pointing this out in discord). I'm suggesting that we update `currentRoute` in `intermediateTransitionTo`.
