### ISSUE TITLE
[Bug] with ember-source 3.25.3: `href` empty from links in rendering tests

### ISSUE THREAD

**Issue by esbanarango** [emberjs/ember.js#19451]
### 🐞 Describe the Bug
In a rendering tests the `href` returned from the `link` helper is always empty.

### 🔬 Minimal Reproduction
```js
  test('href test', async function (assert) {
    assert.expect(1);
    await render(hbs`
      {{#let (link route="login") as |l|}}
        <a href={{l.url}}>Login</a>
      {{/let}}
    `);
    assert.dom('a').hasAttribute('href', `/login`);
  });
```

<img width="660" alt="Screen Shot 2021-03-08 at 9 29 56 AM" src="https://user-images.githubusercontent.com/1156865/110334533-e1141380-7ff0-11eb-9a09-41d3ee720308.png">

### 😕 Actual Behavior
Actual: Element has an empty attribute "href".

### 🤔 Expected Behavior
Element a has attribute "href" with value "/login"

### 🌍 Environment
Ember: 3.25.3

### ➕ Additional Context
https://github.com/emberjs/ember.js/issues/19408

**Comment by rwjblue** [comment]
Hmm, I _think_ this was an accidental issue? Since you opened the same thing over on https://github.com/buschtoens/ember-link/issues/554, and Ember itself does not provide a `(link` helper.

I'm going to go ahead and close...

**Comment by esbanarango** [comment]
🤦‍♂️ Totally! Sorry about it
