### ISSUE TITLE
[Bug] Assertion in `link-component` is incorrectly running when using `link-to-external`

### ISSUE THREAD

**Issue by hmajoros** [emberjs/ember.js#19459]
### 🐞 Describe the Bug
[This change](https://github.com/emberjs/ember.js/commit/56af48bb413f89766e0b355ca94c029e62695667#diff-4ef2173974821b22319e3588d4b1fbba945c84e9997aad54e722787802fbdaa9R493) was added to provide better boundaries for linking inside/between engines with the `<LinkTo>` component. However, `link-to-external` extends `link-component`, and thus this assertion runs on the `init` of any `LinkToExternal` usage. When inside of a routeless engine, there is currently no way to link out, as both `<LinkTo>` and `<LinkToExternal>` throw this assertion.

### 🔬 Minimal Reproduction
Using `ember-engines`, create a routeless engine & use `<LinkToExternal>` inside this routeless engine

### 😕 Actual Behavior
Assertion fails when using link-to-external inside of a routeless engine

### 🤔 Expected Behavior
routeless engines should allow the usage of link-to-externala

### 🌍 Environment

- Ember: 3.24.3
- Node.js/npm: 14.15.1
- OS: Big Sur
- Browser: All

**Comment by hmajoros** [comment]
@chancancode I think the best way to fix this is to move this assertion check into a method inside `link-component`, and then have `link-to-external` overwrite this method with a noop. Thoughts?

**Comment by rwjblue** [comment]
@hmajoros - Ya, that seems ok to me (I really do want to get rid of `<LinkToExternal />` all together, that is just a massively different problem 😝 ). Happy to land + backport a fix for this.

**Comment by hmajoros** [comment]
ember.js PR: https://github.com/emberjs/ember.js/pull/19477
ember-engines PR: https://github.com/ember-engines/ember-engines/pull/761

**Comment by hmajoros** [comment]
Closing issue as both ember & ember-engines fixes have now landed & been backported to 3.24.
