### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ?

### ISSUE THREAD

**Issue by AravinthAro** [emberjs/ember.js#19455]
I'm getting this error in an ember addon. My ember application is working fine.
- Ember: - 3.8.1
- Node.js/npm: - 10.22.0/6.14.6
- OS: - mac OS darwin x64
- Browser: - All

**Comment by rwjblue** [comment]
Hmm, what makes you think this is a bug in Ember itself? Can you create a reproduction? 

It might be a good thing to reach out in our discord server's #help channel as well.

**Comment by AravinthAro** [comment]
This is not a bug report. Thought I will get some help to run my application. I will close this issue and check the channell. Thanks.
