### ISSUE TITLE
[Documentation] Add page-title to the list of template helpers

### ISSUE THREAD

**Issue by jenweber** [emberjs/ember.js#19484]
### 📙 Describe the Issue
Newly generated routes for the latest version of Ember include `{{page-title}}`, but if you search our API docs, there are zero results. We should add a documentation block so that page-title shows up in [Ember Template Helpers](https://api.emberjs.com/ember/3.25/classes/Ember.Templates.helpers), and the explanation links to the addon's docs.

This ticket is part of this epic: https://github.com/ember-learn/guides-source/issues/1608

### To close this ticket:
- Create a new file, `packages/@ember/-internals/glimmer/lib/helpers/page-title.ts`
- The new file should have a very short code comment - one sentence saying what the helper is, and a second sentence directing devs to the documentation for https://github.com/ember-cli/ember-page-title  To see how to write this code comment, you can copy the [`{{log}}` helper](https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/glimmer/lib/helpers/log.ts) and edit it to be about page-title
- Add `page-title` to the list of [expected docs](https://github.com/emberjs/ember.js/blob/master/tests/docs/expected.js). This list helps us make sure we don't accidentally drop API docs when files get rearranged.
- Follow [these instructions](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#pull-requests) for your commit message and PR.

It's a little weird to add documentation to this codebase for methods that don't live in it, but this is the same approach that we use for documenting APIs that come from the `glimmer` package instead of the ember.js source code. It's the easiest way to help developers find what they need in our API docs.

**Comment by reidysj** [comment]
Heya, can I pick this up?

**Comment by jenweber** [comment]
@reidysj that would be awesome! Please let me know if you need any help or have questions!

**Comment by knownasilya** [comment]
Can probably close this

**Comment by jenweber** [comment]
Thanks Ilya!
