### ISSUE TITLE
[Bug] Textarea's text doesn't redraw

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#19495]
### 🐞 Describe the Bug
Check out the repo. Clicking the button is supposed to set the text in the textarea. And it does if text wasn't "manually" inserted by typing. If it was, then clicking the button does nothing.

Using the built-in `Textarea` component with a `value={{this.text}}` works as expected in both cases - i.e. it sets the text in the textarea when the button is pressed. It doesn't set it as a text-node in the `textarea` element but that's another story.

### 🔬 Minimal Reproduction
```typescript
import Controller from '@ember/controller';
import { action } from '@ember/object';
import { tracked } from '@glimmer/tracking';

export default class ApplicationController extends Controller {
  @tracked
  text = '';

  @action
  setText() {
    this.text = 'new text';
  }
}
```

```hbs
<textarea>{{this.text}}</textarea>

<button {{on "click" this.setText}}>Set text!</button>
```

### 😕 Actual Behavior
The text area's text is unchanged.

### 🤔 Expected Behavior
The text area's text to be changed.

### 🌍 Environment

- Ember: 3.26
- Node.js/npm: 15
- OS: Linux
- Browser: Any

**Comment by boris-petrov** [comment]
hm, actually this is how HTML works... once you change a textarea's text, changing the value in the HTML doesn't set it in the textarea itself. Very strange. So apart from using the `Textarea` component, is there a way to use the native `textarea` element?

**Comment by bertdeblock** [comment]
Binding to the `value` attribute should work:
```hbs
<textarea value={{this.text}} />
```

**Comment by boris-petrov** [comment]
@bertdeblock - right, but according to [this HTML validator](https://www.freeformatter.com/html-validator.html), that's not valid HTML. Paste that in there to check:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>asd</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
    <textarea value="asd"></textarea>
  </body>
</html>
```

**Comment by bertdeblock** [comment]
Correct, I know that `value` is not a valid attribute for the textarea tag but it is a valid property which you can update and this works using the approach I shared. That's the only alternative I'm aware of though, thought I'd just mention it.

**Comment by boris-petrov** [comment]
Yes, thanks! I'll leave this open a bit longer if someone else has anything other to say.
