### ISSUE TITLE
[Bug] Observer doesn't trigger when used with native Proxy

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#19498]
### 🐞 Describe the Bug
Check out the repo. There is a native class with a tracked property and a getter (annotated with `dependentKeyCompat`) using it. Then I create an instance of that class and observe the getter. All works fine if using a plain `Model` instance. However, if a JavaScript Proxy is used, things stop working as expected.

Removing both the getter and setter from the Proxy - all works again as expected - i.e. the value is rerendered in the template and the observer fires.
Removing either the getter *or* the setter makes things stop working all together - neither the template is rerendered, nor the observer fires.
Leaving both the getter and the setter is some middle ground - the template rerenders, however the observer doesn't fire.

I need the observer to fire when the getter and setter are there. Why doesn't it?

### 🔬 Minimal Reproduction
[This repo](https://github.com/boris-petrov/ember-observer-bug).

### 😕 Actual Behavior
The observer is not triggered.

### 🤔 Expected Behavior
The observer to be triggered.

### 🌍 Environment

- Ember: 3.26.1
- Node.js/npm: 15
- OS: Linux
- Browser: Chrome

**Comment by pzuraq** [comment]
This is expected behavior, native Proxies do not forward notifications. Observers really are not part of the programming model going forward, and you should migrate away from them toward other autotracking based solutions, probably prior to switching to use native proxies.

**Comment by boris-petrov** [comment]
OK, thanks for the response!
