### ISSUE TITLE
[Documentation] Remove link to register for outdated event on fastboot docs page

### ISSUE THREAD

**Issue by akankshadharkar** [emberjs/ember.js#19508]
### 📙 Describe the Issue
Removing the link to register for an event ( Ember Fastboot SSR & Beyond) that ended 2 weeks days back which is showing on the page

https://ember-fastboot.com/

**Comment by nlfurniss** [comment]
This should be filed in https://github.com/ember-fastboot/fastboot-website

**Comment by akankshadharkar** [comment]
Ah, thanks for that
I'll move the issue there :)
