### ISSUE TITLE
Undefined property documentMode

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember.js#19515]
https://github.com/emberjs/ember.js/blob/0b2e72825b438961bef9c3e2c6d8f82a2fb2ff8a/packages/%40ember/-internals/routing/lib/location/auto_location.ts#L92

AFAICT, that is not ever set.

**Comment by Shimpali** [comment]
Hi,

I would like to work on this. Could I get a few more details?

**Comment by wagenet** [comment]
@Shimpali apologies for the delay. I just returned from leave. I believe the issue was that `this.documentMode` is `undefined`. So this line is essentially useless.

**Comment by Shimpali** [comment]
@wagenet No worries. Thanks for responding.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. 

AFAIK autoLocation is now removed. Closing this. Let me know if anyone disagree.
