### ISSUE TITLE
[Bug Canary] class helper invocation fails in dev mode

### ISSUE THREAD

**Issue by patricklx** [emberjs/ember.js#19518]
### 🐞 Describe the Bug
the invocation of the helper fails here https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/glimmer/lib/helper.ts#L194

before its also checked if .class actually exists or not. I guess it should also happen in getDebugName
https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/glimmer/lib/helper.ts#L164

**Comment by pzuraq** [comment]
Can you provide a reproduction or some steps for producing this error? As is, I'm not sure how to diagnose/fix this issue.

**Comment by patricklx** [comment]
okay, right, i just noticed this happens when using helpers coming from local variables.
https://ember-twiddle.com/e03f28ed71a45e0e9daf7da76ff295fd?numColumns=2&openFiles=templates.application%5C.hbs%2Chelpers.my-helper%5C.js
I was unable to get it to build in ember-twiddle...
https://gitpod.io#snapshot/a23f617d-5ef3-4057-aa4a-24692b15fc5f

**Comment by NullVoxPopuli** [comment]
Is this still an issue? looks like a bugfix PR was merged
