### ISSUE TITLE
Glimmer/Handlebars: Clarify glimmer handlebars template syntax (array access by index)

### ISSUE THREAD

**Issue by fpauser** [emberjs/ember.js#19519]
In a project (ember-3.16) I just came across the following snippet:

```hbs
{{#with item.properties.[0] as |firstProp|}}
  <span>
    {{firstProp.label}}
  </span>
{{/with}}
```

This works so far, but formatting this thing with the vsc plugin `Prettier for handlebars` got me

```hbs
{{#with item.properties.0 as |firstProp|}}
  <span>
    {{firstProp.label}}
  </span>
{{/with}}
```

which no longer works and triggers a parse error. 

To clarify things I looked though the ember docs, but array access by index is not mentioned.

Research in the prettier glimmer/ember-template-lint space resulted in the following statements:
* `.[index]` syntax is invalid (but works)
* `.[index]` syntax is bad practise
* `.index` syntax is invalid and does not work

So the question remains: What is valid/invalid/bad/deprecated glimmer handlebars template syntax? What we are really missing here is a proper glimmer handlebars template syntax specification.

**Comment by jamescdavis** [comment]
The recommended way to access an array by index in a template is to use the [get helper](https://guides.emberjs.com/v3.28.0/components/helper-functions/#toc_the-get-helper), e.g.:
```hbs
{{#with (get item.properties 0) as |firstProp|}}
  <span>
    {{firstProp.label}}
  </span>
{{/with}}
```

**Comment by jamescdavis** [comment]
Also note that [the `with` helper is deprecated](https://emberjs.github.io/rfcs/0445-deprecate-with.html) in favor of [the `let` helper](https://emberjs.github.io/rfcs/0286-block-let-template-helper.html).
```hbs
{{#let (get item.properties 0) as |firstProp|}}
  <span>
    {{firstProp.label}}
  </span>
{{/let}}
```

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. 

Fixed in https://github.com/ember-learn/guides-source/pull/1750
