### ISSUE TITLE
[Documentation] Glimmer component docs

### ISSUE THREAD

**Issue by chrisgame** [emberjs/ember.js#19531]
### 📙 Describe the Issue
In the section on passing parameters to named blocks an example is shown as `{{yield to="title" @person.name}}` this gives an error. 
`to="title"` needs to be the last argument passed to yield.

### 🔬 Minimal Reproduction
Visit https://api.emberjs.com/ember/release/modules/@glimmer%2Fcomponent and scroll to the "Passing parameters to named blocks" section to see the examples

### 😕 Actual Behavior
The example is shown as {{yield to="title" @person.name}}

### 🤔 Expected Behavior
The example should be {{yield @person.name to="title"}}

### ➕ Additional Context
PR to fix here https://github.com/emberjs/ember.js/pull/19530

**Comment by MelSumner** [comment]
Closed with PR #19530
