### ISSUE TITLE
[Bug] String injection with `instantiate: false` no longer works on ember 3.27.0

### ISSUE THREAD

**Issue by romgere** [emberjs/ember.js#19532]
### 🐞 Describe the Bug
Injecting a string via dependency injection raise an error.

### 🔬 Minimal Reproduction
Minimal reproduction on fresh app : https://github.com/romgere/test-ember-string-injection
- Currently on ember 3.26 : working
- Update to ember-source@3.27.0 : breaking

To sum-up
Try to inject a string into a service with an initializer : 

```js
// initializer.js
export function initialize(application) {
  application.register('config:a-string', 'My great injected string', {
    instantiate: false,
  });

  application.inject(
    'service:test-injection',
    'injectedString',
    'config:a-string'
  );
}

export default {
  initialize,
};
```

```js
// service.js
import Service from '@ember/service';

export default class TestInjectionService extends Service {
  injectedString = null; // injected by initializer
}
```

### 😕 Actual Behavior
When trying to use the service property got the following error : 

`Uncaught TypeError: Cannot create property 'Symbol(INIT_FACTORY)' on string 'My great injected string'`

### 🤔 Expected Behavior
The property is setted with injected string.

### 🌍 Environment

- Ember: 3.27.0
- Node.js/npm: v12.20.2 (npm v6.14.11)
- OS: ubuntu
- Browser: chrome

### ➕ Additional Context
Related to what is done in https://github.com/yapplabs/ember-modal-dialog, see https://github.com/yapplabs/ember-modal-dialog/issues/320.

**Comment by lifeart** [comment]
as workaround, 

```js
 application.register('config:a-string', { toString() => 'My great injected string' }, {
    instantiate: false,
  });
```

may work

**Comment by makepanic** [comment]
The mentioned workaround fixes the issue in modal-dialog for me

**Comment by CvX** [comment]
The same issue affects [ember-model-validator](https://github.com/esbanarango/ember-model-validator/blob/ee8441fc378c1df035757100e8cc85ed36c538d3/addon/initializers/model-locale.js#L5).

**Comment by andsmedeiros** [comment]
I have the same issue with 3.28.0, but while trying to inject some numeric constants in components.
`Cannot create property 'Symbol(INIT_FACTORY)' on number '6.375'`

**Comment by lifeart** [comment]
@andsmedeiros your case will be:

```js
 application.register('config:a-number', { [Symbol.toPrimitive]() { return 42 } }, {
    instantiate: false,
  });
```

**Comment by andsmedeiros** [comment]
Thanks @lifeart, this does the trick.
