### ISSUE TITLE
[Documentation] Documentation issue report

### ISSUE THREAD

**Issue by nonopolarity** [emberjs/ember.js#19549]
I think I don't see the docs in this repo... any method to do a PR for the docs?

**Comment by bertdeblock** [comment]
Which part of the docs do you want to make a PR for? Can you include a link?

**Comment by nonopolarity** [comment]
such as  https://guides.emberjs.com/release/getting-started/quick-start/  ?

**Comment by bertdeblock** [comment]
👍 The source for the guides can be found here => https://github.com/ember-learn/guides-source

**Comment by acorncom** [comment]
Closing this issue for now, feel free to re-open if needed
