### ISSUE TITLE
[Bug] template-compiler is not usable with Embroider(staticAddonTrees: true) + ember 3.27

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember.js#19568]
### 🐞 Describe the Bug
The template compiler cannot be used with Ember 3.27 (modules! 🎉 ) and embroider:

### 🔬 Minimal Reproduction
https://github.com/NullVoxPopuli/repro-emberjs-16568

### 😕 Actual Behavior

This error occurs when calling compile:
```
Error: Cannot call `compile` with only the template compiler loaded. Please load `ember.debug.js` or `ember.prod.js` prior to calling `compile`.
```

### 🤔 Expected Behavior

compile succeeds as it does with Ember 3.26

### 🌍 Environment

- Ember: - 3.27.2
- Node.js/npm: - 4.17.0
- OS: - Ubuntu 20.04
- Browser: - FireFox Developer Edition 89.0b15 (64-bit)

### ➕ Additional Context

deployed repro here: 
 - https://github.com/NullVoxPopuli/limber/pull/60
 - https://60b116dddcec312d2a935201--limber.netlify.app/

**Comment by ef4** [comment]
All ember internal use of this pattern:

https://github.com/emberjs/ember.js/blob/21bd70c773dcc4bfe4883d7943e8a68d203b5bad/packages/ember-template-compiler/lib/system/compile.ts#L4

Needs to stop. We have replacements already (in @embroider/macros) that work in both non-embroider and embroider builds.

**Comment by NullVoxPopuli** [comment]
@ef4 do you have an example Pr or anything of what it takes to swap out that require stuff with `@embroider/macros`? I could try PRing those changes to the template-compiler and other places in ember

**Comment by NullVoxPopuli** [comment]
wip: https://github.com/emberjs/ember.js/pull/19569

**Comment by rwjblue** [comment]
> All ember internal use of this pattern:
> 
> https://github.com/emberjs/ember.js/blob/21bd70c773dcc4bfe4883d7943e8a68d203b5bad/packages/ember-template-compiler/lib/system/compile.ts#L4
> 
> Needs to stop. We have replacements already (in @embroider/macros) that work in both non-embroider and embroider builds.

Obviously you are correct, but the compat adapter that Embroider ships could easily handle these cases.

**Comment by NullVoxPopuli** [comment]
I've tried reproing here: https://github.com/NullVoxPopuli/repro-emberjs-16568/blob/main/app/routes/application.js#L25
but it's _working_, so I have more digging to do

**Comment by NullVoxPopuli** [comment]
ah! success! 
all I needed was to add this:
```
    staticAddonTrees: true,
    staticAddonTestSupportTrees: true,
    staticHelpers: true,
    staticComponents: true,
    splitControllers: true,
    splitRouteClasses: true,
```
to my embroider config: https://github.com/NullVoxPopuli/repro-emberjs-16568/commit/89e869907308c200246e9f1cc4f51879edd83a4b

**Comment by NullVoxPopuli** [comment]
in particular, `staticAddonTrees: true` causes this error

**Comment by NullVoxPopuli** [comment]
This is no longer an issue with https://github.com/NullVoxPopuli/ember-repl/
