### ISSUE TITLE
[Bug] Bug report default test fails in wsl2 with Ubuntu

### ISSUE THREAD

**Issue by benhalverson** [emberjs/ember.js#19598]
### 🐞 Describe the Bug
I created a new app with the the current Ember-cli in wsl2 with Ubuntu and Chrome installed in wsl2. When I run `npm test` it times out with an error
### 🔬 Minimal Reproduction
```bash
npm install -g ember-cli
ember new super-rentals
cd super-rentals
npm test
```

### 😕 Actual Behavior
```bash
Environment: test
cleaning up...
Built project successfully. Stored in "/tmp/tests-dist-2021510-5507-z99xmw.h82v".
not ok 1 Chrome - [undefined ms] - error
    ---
        message: >
            Error: Browser failed to connect within 120s. testem.js not loaded?
            Stderr: 
             [0610/205021.134705:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
            
            DevTools listening on ws://127.0.0.1:42267/devtools/browser/b5588762-ac0d-4555-a68c-5969a1a5d380
            
            
        browser log: |
            {"type":"error","text":"Error: Browser failed to connect within 120s. testem.js not loaded?"}
            {"type":"error","text":"[0610/205021.134705:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n\nDevTools listening on ws://127.0.0.1:42267/devtools/browser/b5588762-ac0d-4555-a68c-5969a1a5d380\n"}
    ...

1..1
# tests 1
# pass  0
# skip  0
# todo  0
# fail  1
Testem finished with non-zero exit code. Tests failed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! super-rentals@0.0.0 test:ember: `ember test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the super-rentals@0.0.0 test:ember script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ben/.npm/_logs/2021-06-11T04_03_56_486Z-debug.log
ERROR: "test:ember" exited with 1.
npm ERR! Test failed.  See above for more details.
```
### 🤔 Expected Behavior
No errors or hanging
### 🌍 Environment

- Ember: - 3.26.1
- Node.js/npm: - 14.16.0/6.14.11
- OS: - linux x64
- Browser: - chrome

**Comment by rstudner** [comment]
Seeing this same error, only on our CI server, when going from 3.17.x to 3.18.x

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue.

This issue has been open for a while without anyone jumping in to fix it. The reality is that unless you want to fix the bug itself, it will likely stay that way.

The time of core team members is very limited, and we all want them to focus  on moving the framework forward (high-leverage things), leaving fixing of edge case bugs to "fringe volunteers", such as you and me.

By closing some old issues we reduce the list of open issues to a more manageable set. Let me know if you think this is a mistake and that the issue should stay open.
