### ISSUE TITLE
es-lint error in generated tests

### ISSUE THREAD

**Issue by Cartmanishere** [emberjs/ember.js#19593]
When generating any kind of tests using cli, the generated tests show the following error:

<img width="797" alt="Screen Shot 2021-06-05 at 9 35 18 PM" src="https://user-images.githubusercontent.com/23312366/120897977-810c2800-c646-11eb-9619-74b3ac3dac7d.png">

Note: This is with the eslint/prettier settings that get generated with the ember app generator.

Is it okay if I modify the test blueprints and add that `<space>` after function keyword?

**Comment by NullVoxPopuli** [comment]
Is this still an issue? I noticed latest ember runs the lint fix command after blueprint stuff

**Comment by locks** [comment]
I believe this has been addressed since we now run Prettier after generating blueprints.
