### ISSUE TITLE
[Bug] route-recognizer dependency is scrambled in embroider

### ISSUE THREAD

**Issue by mydea** [emberjs/ember.js#19601]
### 🐞 Describe the Bug

When updating from ember-source 3.26 to 3.27, I get this error in my addon:

```
Build Error (PackagerRunner) in ember-cognito-identity/node_modules/pretender/dist/pretender.es.js

Module not found: Error: Can't resolve 'ember-source/route-recognizer/index.js' in 'ember-cognito-identity/node_modules/pretender/dist/pretender.es.js'
```

We have a dependency on Pretender, which itself has a dependency on `route-recognizer`. I am not sure why this is resolved like this, but I suspect it probably has something to do with ember-source re-exporting route-recognizer somehow, or something like this? I am also not 100% sure if this belongs here or in embroider (or in ember-auto-import?), but since it was triggered by the update to ember-source 3.27 I figured this is as good a place as any. Please let me know if I should move this somewhere else.

### 🔬 Minimal Reproduction

I made a minimal reproduction here:
https://github.com/mydea/ember-issue-reproductions/tree/fn/pretender

* Install ember-auto-import & pretender
* Use embroider
* Update ember-source from 3.26 to 3.27 to see it fail

### 😕 Actual Behavior

route-recognizer seems to be somehow confused.

### 🤔 Expected Behavior

route-recognizer import should work for Pretender.

### 🌍 Environment

- Ember: 3.27.5
- Node.js/npm: 14.15.0 / 6.14.8
- OS: Ubuntu 20.04
- Browser: MS Edge

### ➕ Additional Context

You can see this fail in action here: https://github.com/fabscale/ember-cognito-identity/pull/538/checks?check_run_id=2821649808

**Comment by esbanarango** [comment]
https://github.com/embroider-build/embroider/issues/849#issuecomment-861836116

**Comment by esbanarango** [comment]
From @ef4 

> We can probably do a fancier CompatAdapter for ember-source that would fix its own references to these packages without leaking rules that change everybody else's references to them.

> But ultimately ember-source needs to ship something that makes more sense: either stop bundling in these dependencies, or keep bundling them but import them via relative paths instead of expecting them to be resolvable by their original package names.

**Comment by sandstrom** [comment]
Let's track this in the correct repo. https://github.com/embroider-build/embroider/issues/849#issuecomment-861836116
