### ISSUE TITLE
[Bug] 3.20.3 => 3.20.4 regression? Overwriting a property defined in a mixin with 'undefined' does not work anymore

### ISSUE THREAD

**Issue by mpirio** [emberjs/ember.js#19619]
### 🐞 Describe the Bug
I have a mixin with a property `prop` equal to "value" string. I use this mixin with one of my controller where I overwrite this property with `undefined`. Before 3.20.4, I had `prop === undefined`. After, we have `prop === "value"`

I don't know if this behavior (`prop === "value"`) is intended.

### 🔬 Minimal Reproduction

```javascript
// app/mixins/mymixin.js
import Mixin from '@ember/object/mixin';

export default Mixin.create({
  prop: "value"
});

// app/controllers/application.js
import Controller from '@ember/controller';
import { computed } from '@ember/object';
import MyMixin from '../mixins/mymixin';

const AppController = Controller.extend(MyMixin, {
  prop: undefined,

  type: computed('prop', function() {
    return  typeof(this.prop);
  })
});

// app/templates/application.js
<p>prop = {{this.prop}}</p>
<p>typeof prop = {{this.type}}</p>
```

### 😕 Actual Behavior
With 3.20.3:
```
prop =
typeof prop = undefined
```

With 3.20.4:
```
prop = value
typeof prop = string
```
### 🤔 Expected Behavior
Like in 3.20.3 and before:
```
prop =
typeof prop = undefined
```

### 🌍 Environment

- Ember: 3.20.4 to current (issue doesn't exist in 3.20.3)
- Node.js/npm: 14.16.1/6.14.12
- OS: macOS Mojave
- Browser: Chrome (91.0.4472.114)

### ➕ Additional Context
I found where the prop is ignored : https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/metal/lib/mixin.ts#L307

**Comment by locks** [comment]
Closing has no longer relevant and since the last comment proovides a working alternative. Thanks everyone!
