### ISSUE TITLE
Deprecation Cleanup for 4.0

### ISSUE THREAD

**Issue by kategengler** [emberjs/ember.js#19617]
**PLEASE FLAG REMOVAL/CLEANUP PRs WITH `[CLEANUP beta]` IN THE PR TITLE.**

The following are the deprecations in ember.js that are `until` 4.0 or earlier. Each item includes the id of the deprecation in backticks. Searching for this id in the source will find the invocations of that deprecation.

## Remaining

- [x] https://github.com/emberjs/ember.js/pull/19846 - Optional feature: `application-template-wrapper` https://github.com/emberjs/ember.js/blob/5a36048abfda243a7715cc6304d69ecc7cc9bddb/lib/index.js#L131
- [x] https://github.com/emberjs/ember.js/pull/19846 - Optional feature: Unspecified or specified `classic` edition https://github.com/emberjs/ember.js/blob/5a36048abfda243a7715cc6304d69ecc7cc9bddb/lib/index.js#L123
- [x] https://github.com/emberjs/ember.js/pull/19838 - Change `bower` usage to a `throw` instead of warn at https://github.com/emberjs/ember.js/blob/ce98e570d21f74348fb64ebd9fd4624a3fba7d92/lib/index.js#L47
- [x] https://github.com/emberjs/ember.js/pull/19836 - Optional feature: `template-only-glimmer-components` https://github.com/emberjs/ember.js/blob/5a36048abfda243a7715cc6304d69ecc7cc9bddb/lib/index.js#L140
- [x] https://github.com/emberjs/ember.js/pull/19833 Array Observers `array-observers` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_array-observers) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/71f9cd0c2212cbce988a6056bac08bf2c6c9db6c/packages/@ember/-internals/metal/lib/array.ts#L99) + 1 other in same file
- [x] Ember.Component.reopen `ember.component.reopen`[Deprecation Guide]() [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/9609b8f30e0cdbc2235063f571af619f4362f73b/packages/@ember/-internals/glimmer/lib/component.ts#L1156) see also https://github.com/emberjs/ember.js/pull/19744#issuecomment-954956205
- [x] https://github.com/emberjs/ember.js/pull/19762 - Component manager capabilities prior to 3.13 `manager-capabilities.components-3-4` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_manager-capabilities-components-3-4) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/566af4941eb7ecaa4679e295ecfc38263d5ee1fe/packages/@ember/-internals/glimmer/lib/utils/managers.ts#L47)
- [x] https://github.com/emberjs/ember.js/pull/19762 - Modifier manager capabilities prior to 3.22 `manager-capabilities.modifiers-3-13` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_manager-capabilities-modifiers-3-13) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/566af4941eb7ecaa4679e295ecfc38263d5ee1fe/packages/@ember/-internals/glimmer/lib/utils/managers.ts#L65)
- [x] https://github.com/emberjs/ember.js/pull/19749 - Router Events `deprecate-router-events` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_deprecate-router-events) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/802476f5fdc6e8688d36e82c24d20af494dfa934/packages/@ember/-internals/routing/lib/system/route.ts#L2770) + a few other locations

### VM Deprecations 

- [x] https://github.com/emberjs/ember.js/pull/19843 - Helper invocations without arguments or parens `argument-less-helper-paren-less-invocation` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_argument-less-helper-paren-less-invocation) Deprecation Invocation Site: ([1](https://github.com/glimmerjs/glimmer-vm/blob/ed2223698f1b37aeeab75def6406cf6b105d1188/packages/%40glimmer/opcode-compiler/lib/syntax/expressions.ts#L93-L109)/[2](https://github.com/emberjs/ember.js/blob/0402268c836d930c250e5bb5cacbc948b9e94d78/packages/%40ember/-internals/glimmer/lib/environment.ts#L120))
- [x] https://github.com/emberjs/ember.js/pull/19762 - Mutation after consumption `autotracking.mutation-after-consumption` [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/0402268c836d930c250e5bb5cacbc948b9e94d78/packages/%40ember/-internals/glimmer/lib/environment.ts#L102)
- [x] https://github.com/emberjs/ember.js/pull/19762 - `this.` property fallback `this-property-fallback` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_this-property-fallback) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/0402268c836d930c250e5bb5cacbc948b9e94d78/packages/%40ember/-internals/glimmer/lib/environment.ts#L110)

### 🔒 Built-in Components

All should be :lock: in https://github.com/emberjs/ember.js/pull/19806

- [x] https://github.com/emberjs/ember.js/pull/19662 - Passing tagName to LinkTo `ember.link-to.tag-name` [Deprecation Guide]() [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/57907a4d7d91aa58b3b3ac1258e639ce221f9492/packages/@ember/-internals/glimmer/lib/components/link-to.ts#L432)
- [x] Importing legacy built-in components `ember.built-in-components.import` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_ember-built-in-components-import) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/efd066ce45b45af96f921c02b58c8d44931222d8/packages/@ember/component/checkbox.ts#L5) + other locations
- [x] Legacy Attributes to built-in Components `ember.built-in-components.legacy-attribute-arguments` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_ember-built-in-components-legacy-attribute-arguments) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/efd066ce45b45af96f921c02b58c8d44931222d8/packages/@ember/-internals/glimmer/lib/components/internal.ts#L355) + 2 more in the same file
- [x] Legacy Arguments to built-in Components `ember.built-in-components.legacy-arguments` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_ember-built-in-components-legacy-arguments) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/efd066ce45b45af96f921c02b58c8d44931222d8/packages/@ember/-internals/glimmer/lib/components/internal.ts#L274) + several more
- [x] https://github.com/emberjs/ember.js/pull/19664 - Reopening Built In Components `ember.built-in-components.reopen` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_ember-built-in-components-reopen) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/efd066ce45b45af96f921c02b58c8d44931222d8/packages/@ember/-internals/glimmer/lib/components/-link-to.ts#L1031) + several more
- [x] LinkTo Positional Arguments `ember-glimmer.link-to.positional-arguments` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_ember-glimmer-link-to-positional-arguments) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/efd066ce45b45af96f921c02b58c8d44931222d8/packages/@ember/-internals/glimmer/lib/components/-link-to.ts#L997) + other locations
- [x] :lock: https://github.com/emberjs/ember.js/pull/19669 (NOTE: This PR was merged and reverted) - Passing disabledWhen to LinkTo `ember.link-to.disabled-when` [Deprecation Guide]() [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/57907a4d7d91aa58b3b3ac1258e639ce221f9492/packages/@ember/-internals/glimmer/lib/components/link-to.ts#L627) + 1 more in the same file

## Completed

- [x] :lock: https://github.com/emberjs/ember.js/pull/19678 - The Ember Global `ember-global` [Deprecation Guide](https://deprecations.emberjs.com/v3.x/#toc_ember-global) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/35689f9c4fe27f810895aeeec1ebb5ef5700ce38/packages/@ember/-internals/bootstrap/index.ts#L31)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19528 - Ember.Logger `ember-console.deprecate-logger` [Deprecation Guide](https://deprecations.emberjs.com/v3.x/#toc_ember-console-deprecate-logger) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/566af4941eb7ecaa4679e295ecfc38263d5ee1fe/packages/@ember/-internals/console/index.js#L44) + other locations in this file
- [x] :lock: https://github.com/emberjs/ember.js/pull/19650 - mouseEnter Leave Move Handler Methods `ember-views.event-dispatcher.mouseenter-leave-move` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_component-mouseenter-leave-move) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/9609b8f30e0cdbc2235063f571af619f4362f73b/packages/@ember/-internals/glimmer/lib/component.ts#L712) + other locations in this file + [one other file](https://github.com/emberjs/ember.js/blob/9609b8f30e0cdbc2235063f571af619f4362f73b/packages/@ember/-internals/glimmer/lib/modifiers/action.ts#L221)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19695 - {{partial}} `ember-views.partial` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_ember-views-partial) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/397d6b990fdf2e46bdc97a4424419706184e4e0a/packages/@ember/-internals/glimmer/lib/resolver.ts#L123)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19658 - sendAction `ember.component.send-action` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_ember-component-send-action) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/566af4941eb7ecaa4679e295ecfc38263d5ee1fe/packages/@ember/-internals/glimmer/lib/components/abstract-input.ts#L233) + one other in the same file + other locations
- [x] :lock: https://github.com/emberjs/ember.js/pull/19639 - Private INVOKE API `actions.custom-invoke-invokable` [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/e37a265c2b428d4010069a465d100691f022a401/packages/@ember/-internals/glimmer/lib/helpers/action.ts#L416) + other locations
- [x] :lock: https://github.com/emberjs/ember.js/pull/19629 - isVisible on Classic Components `ember-component.is-visible` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_ember-component-is-visible) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/1f420ce8857276a1ba4bce976fc5a1321bec3490/packages/@ember/-internals/glimmer/lib/utils/bindings.ts#L108)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19656 - String-based component manager `deprecate-string-based-component-manager` [Deprecation Guide](https://deprecations.emberjs.com/v3.x/#toc_component-manager-string-lookup) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/566af4941eb7ecaa4679e295ecfc38263d5ee1fe/packages/@ember/-internals/glimmer/lib/utils/managers.ts#L19)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19655 - Meta destruction APIs `meta-destruction-apis` [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/49d5291600a0b6d70ff9913e10ff9f2f23e2eb7b/packages/@ember/-internals/meta/lib/meta.ts#L139) + 4 more in same file
- [x] :lock: https://github.com/emberjs/ember.js/pull/19673 - Computed Deep Each `ember-metal.computed-deep-each` [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/03b20d8370d2a71928ffc40b558f751e276c6850/packages/@ember/-internals/metal/lib/chain-tags.ts#L94) + 1 other location
- [x] :lock: https://github.com/emberjs/ember.js/pull/19674 - Clobbering Computed Properties `computed-property.override` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_computed-property-override) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/566af4941eb7ecaa4679e295ecfc38263d5ee1fe/packages/@ember/-internals/metal/lib/computed.ts#L505)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19670 - Volatile Computed Properties `computed-property.volatile` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_computed-property-volatile) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/566af4941eb7ecaa4679e295ecfc38263d5ee1fe/packages/@ember/-internals/metal/lib/computed.ts#L719)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19671 - `.property()` on Computed Properties `computed-property.property` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_computed-property-property) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/566af4941eb7ecaa4679e295ecfc38263d5ee1fe/packages/@ember/-internals/metal/lib/computed.ts#L794)
- [x] :lock:  https://github.com/emberjs/ember.js/pull/19628 - `aliasMethod` `object.alias-method` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_object-alias-method) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/802476f5fdc6e8688d36e82c24d20af494dfa934/packages/@ember/-internals/metal/lib/mixin.ts#L846)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19648 - `getWithDefault` `ember-metal.get-with-default` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_ember-metal-get-with-default) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/1f420ce8857276a1ba4bce976fc5a1321bec3490/packages/@ember/-internals/metal/lib/property_get.ts#L185)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19651 - Legacy Owner Injection `owner.legacy-owner-injection` [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/a80b54ebbb28ef746abbd0e332d34fe6e93001b8/packages/@ember/-internals/owner/index.ts#L96)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19659 - `renderTemplate` `route-render-template` [Deprecation Guide](https://deprecations.emberjs.com/v3.x/#toc_route-render-template) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/802476f5fdc6e8688d36e82c24d20af494dfa934/packages/@ember/-internals/routing/lib/system/route.ts#L1141) + 1 more location in same file, `disconnectOutlet` `route-disconnect-outlet` [Deprecation Guide](https://deprecations.emberjs.com/v3.x/#toc_route-disconnect-outlet) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/802476f5fdc6e8688d36e82c24d20af494dfa934/packages/@ember/-internals/routing/lib/system/route.ts#L1901)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19707 - Application Controller Router Properties `application-controller.router-properties` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_application-controller-router-properties) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/802476f5fdc6e8688d36e82c24d20af494dfa934/packages/@ember/-internals/routing/lib/system/router.ts#L1743) + 1 other in same file
- [x] :lock: https://github.com/emberjs/ember.js/pull/19636 -  Ember Copy and Copyable `ember-runtime.deprecate-copy-copyable` [Deprecation Guide](https://deprecations.emberjs.com/v3.x/#toc_ember-runtime-deprecate-copy-copyable) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/566af4941eb7ecaa4679e295ecfc38263d5ee1fe/packages/@ember/-internals/runtime/lib/copy.js#L100)
- [x] 🔒 https://github.com/emberjs/ember.js/pull/19663 - Function Prototype Property Extension `function-prototype-extensions.property` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_function-prototype-extensions-property) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/f79f226b778b10372216e4693106d1375970eff4/packages/@ember/-internals/runtime/lib/ext/function.js#L82), Function Prototype Observes Extension `function-prototype-extensions.observes` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_function-prototype-extensions-observes) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/f79f226b778b10372216e4693106d1375970eff4/packages/@ember/-internals/runtime/lib/ext/function.js#L131), Function Prototype On Extension `function-prototype-extensions.on` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_function-prototype-extensions-on) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/f79f226b778b10372216e4693106d1375970eff4/packages/@ember/-internals/runtime/lib/ext/function.js#L179)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19680 - Implicit Injections `implicit-injections` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_implicit-injections) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/a80b54ebbb28ef746abbd0e332d34fe6e93001b8/packages/@ember/-internals/runtime/lib/system/core_object.js#L1235)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19645 - `tryInvoke` `ember-utils.try-invoke` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_ember-utils-try-invoke) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/d0673c4af1fa52f23b58448f232e7a25f3974c12/packages/@ember/-internals/utils/lib/invoke.ts#L58)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19665 - `Ember.$` and `this.$` APIs `ember-views.curly-components.jquery-element` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_jquery-apis) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/566af4941eb7ecaa4679e295ecfc38263d5ee1fe/packages/@ember/-internals/views/lib/mixins/view_support.js#L446)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19666 - jQuery events `ember-views.event-dispatcher.jquery-event` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_jquery-event) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/566af4941eb7ecaa4679e295ecfc38263d5ee1fe/packages/@ember/-internals/views/lib/system/jquery_event_deprecation.js#L19)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19652 -  Globals Resolver `globals-resolver` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_ember-deprecate-globals-resolver) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/a80b54ebbb28ef746abbd0e332d34fe6e93001b8/packages/@ember/application/globals-resolver.js#L106) + other locations
- [x] :lock: https://github.com/emberjs/ember.js/pull/19653 - Run loop and computed dot access `deprecated-run-loop-and-computed-dot-access` [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/35689f9c4fe27f810895aeeec1ebb5ef5700ce38/packages/@ember/object/index.js#L72) + other locations
- [x] :lock: https://github.com/emberjs/ember.js/pull/19647 - `merge` `ember-polyfills.deprecate-merge` [Deprecation Guide](https://deprecations.emberjs.com/v3.x/#toc_ember-polyfills-deprecate-merge) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/566af4941eb7ecaa4679e295ecfc38263d5ee1fe/packages/@ember/polyfills/lib/merge.ts#L31)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19646 - Ember String loc `ember-string.loc` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_ember-string-loc) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/a61143b5a7dc5cb0f2cb331c227de5539b139791/packages/@ember/string/index.ts#L122)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19654 - Ember String Prototype Extensions [Deprecation Guide](https://deprecations.emberjs.com/v3.x/#toc_ember-string-prototype_extensions) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/a61143b5a7dc5cb0f2cb331c227de5539b139791/packages/@ember/string/index.ts#L339)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19558 https://github.com/emberjs/ember.js/pull/19667 -  IE11 `3-0-browser-support-policy` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_3-0-browser-support-policy) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/566af4941eb7ecaa4679e295ecfc38263d5ee1fe/packages/ember/index.js#L141)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19632 - `{{#with` `ember-glimmer.with-syntax` [Deprecation Guide](https://deprecations.emberjs.com/v3.x/#toc_ember-glimmer-with-syntax) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/eb88fde44846dc0e4a20b16fb64ed562b7abe2d5/packages/ember-template-compiler/lib/plugins/deprecate-with.ts#L108)
- [x] 🔒 https://github.com/emberjs/ember.js/pull/19660 - `attrs` `attrs-arg-access` [Deprecation Guide](https://deprecations.emberjs.com/v3.x/#toc_attrs-arg-access) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/eb88fde44846dc0e4a20b16fb64ed562b7abe2d5/packages/ember-template-compiler/lib/plugins/transform-attrs-into-args.ts#L67)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19657 -  `{{hasBlock}}` and `{{hasBlockParams}}` `has-block-and-has-block-params` [Deprecation Guide](https://deprecations.emberjs.com/v3.x#toc_has-block-and-has-block-params) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/566af4941eb7ecaa4679e295ecfc38263d5ee1fe/packages/ember-template-compiler/lib/plugins/transform-has-block-syntax.ts#L39)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19644 - Private `{{-in-element}}` `glimmer.private-in-element` [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/eb88fde44846dc0e4a20b16fb64ed562b7abe2d5/packages/ember-template-compiler/lib/plugins/transform-in-element.ts#L77)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19708 - Passing `classBinding` and `classNameBindings` to components in templates `class-binding-and-class-name-bindings-in-templates` [Deprecation Guide](https://deprecations.emberjs.com/v3.x/#toc_class-binding-and-class-name-bindings-in-templates) [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/eb88fde44846dc0e4a20b16fb64ed562b7abe2d5/packages/ember-template-compiler/lib/plugins/transform-old-class-binding-syntax.ts#L38)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19640 - Old deprecate method imports `old-deprecate-method-paths` [Deprecation Guide]() [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/22bfcfdac0aeefcf333fb2d6697772934201b43b/packages/@ember/application/deprecations.ts#L8) + 1 other location in the same file 
- [x] :lock: https://github.com/emberjs/ember.js/pull/19643 - Deprecate without `since` `ember-source-deprecation-without-since` [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/4984045459bc9f5f34f1ae8b51fc6522fb72cbf4/packages/@ember/debug/lib/deprecate.ts#L224), Deprecate without `for` `ember-source-deprecation-without-for` [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/4984045459bc9f5f34f1ae8b51fc6522fb72cbf4/packages/@ember/debug/lib/deprecate.ts#L211) 
- [x] https://github.com/emberjs/ember.js/pull/19661 - EXTEND_PROTOTYPES `ember-env.old-extend-prototypes` [Deprecation Guide]() [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/566af4941eb7ecaa4679e295ecfc38263d5ee1fe/packages/ember/index.js#L175)
- [x] :lock: https://github.com/emberjs/ember.js/pull/19704 - Class-based template compilation plugins `template-compiler.registerPlugin` [Deprecation Guide]() [Deprecation Invocation Site](https://github.com/emberjs/ember.js/blob/e28a201b9ccfb16f93089cea9207fca9b552d98c/packages/ember-template-compiler/lib/system/compile-options.ts#L93)

**Comment by sandstrom** [comment]
What do you think about deprecating Auto Location, is that something you'd like to get in before 4.0?

https://github.com/emberjs/ember.js/pull/19510

It's a fairly low-impact deprecation, in that the change required is a one-line change in the config. More details in that PR and the associated RFC.

But there is also no real rush, deprecating it doesn't "unlock" any new functionality, so could also wait until after 4.0 with merging it.

**Comment by kategengler** [comment]
@sandstrom This is a list of already deprecated APIs that need to be removed for 4.0. At this point, the master branch is already 4.0, and so no newly added deprecations will make it into 3.x.

**Comment by nlfurniss** [comment]
IE11 was removed in #19558

**Comment by snewcomer** [comment]
I can take this one since I did the original PR!

> Implicit Injections implicit-injections

**Comment by snewcomer** [comment]
I understand we are all busy.  It is commendable even finding time to track issues, review and contribute code in our spare time.  But is there any urgency to get this issue across the line in the coming weeks or is there an often talked about timeline not publicized?  I have a few PRs open in glimmer that need review and would be happy to help with any remaining ones (once this tracking checkboxes are updated with where we are at).

**Comment by kategengler** [comment]
There's definitely some urgency. 4.0 is the next release and ideally we would have gotten this all done before it even branched to beta. 

Participation definitely drops over the summer and a few have commented that in the future we should avoid summer for major release pushes. We probably need to find a way to not have time-bound work for major releases.

**Comment by nlfurniss** [comment]
Both `Component manager capabilities prior to 3.13` and `Modifier manager capabilities prior to 3.22` are covered by https://github.com/emberjs/ember.js/pull/19762

**Comment by kategengler** [comment]
This is done! Thank you to everybody who participated in deprecation removal <3
