### ISSUE TITLE
[Bug] The function helper inside the if helper is always evaluated

### ISSUE THREAD

**Issue by pieter-v** [emberjs/ember.js#19610]
### 🐞 Describe the Bug
In the template below, the `fn` helper is evaluated even if the `if` helper evaluates to `false` since `this.undefinedAction` is `undefined`.

The template
```hbs
(if this.undefinedAction (fn this.undefinedAction "Hello") this.existingAction)
```
results in a runtime exception

### 🔬 Minimal Reproduction
See [ember-if](https://github.com/pieter-v/ember-if) for a simple example

### 😕 Actual Behavior
A runtime exception
```
runtime.js:7112 Uncaught Error: You must pass a function as the `fn` helpers first argument, you passed undefined. While rendering:

this.undefinedAction
    at assertCallbackIsFn (runtime.js:7112)
    at runtime.js:7091
    at Object.evaluate (runtime.js:2051)
    at AppendOpcodes.evaluate (runtime.js:1284)
    at LowLevelVM.evaluateSyscall (runtime.js:5177)
    at LowLevelVM.evaluateInner (runtime.js:5133)
    at LowLevelVM.evaluateOuter (runtime.js:5125)
    at VM.next (runtime.js:6257)
    at VM._execute (runtime.js:6241)
    at VM.execute (runtime.js:6211)
```

### 🤔 Expected Behavior
No exception

### 🌍 Environment
- Ember: 3.27.5
- Node.js/npm: 14.17.0
- OS: macos 11.4
- Browser: chrome 91.0.4472.114

### ➕ Additional Context
This did work in ember 3.23.1
Also fails in ember 3.24.4, 3.25.4, 3.26.1

**Comment by MrChocolatine** [comment]
Both branches of the `if` helper are evaluated, this has always been mentioned in the documentation.

- In v3.27
  https://github.com/emberjs/ember.js/blob/v3.27.5/packages/@ember/-internals/glimmer/lib/helpers/if-unless.ts#L88-L90

- In v3.26
  https://github.com/emberjs/ember.js/blob/v3.26.1/packages/@ember/-internals/glimmer/lib/helpers/if-unless.ts#L88-L90

- In v3.25
  https://github.com/emberjs/ember.js/blob/v3.25.4/packages/@ember/-internals/glimmer/lib/helpers/if-unless.ts#L88-L90

- In v3.24
  https://github.com/emberjs/ember.js/blob/v3.24.4/packages/@ember/-internals/glimmer/lib/helpers/if-unless.ts#L93-L95

- In v3.20
  https://github.com/emberjs/ember.js/blob/v3.20.7/packages/@ember/-internals/glimmer/lib/helpers/if-unless.ts#L127-L129

- In v3.12
  https://github.com/emberjs/ember.js/blob/v3.12.4/packages/@ember/-internals/glimmer/lib/helpers/if-unless.ts#L130-L132
