### ISSUE TITLE
[Bug] New ember app in cli 3.27.0 - blank screen

### ISSUE THREAD

**Issue by mdokupil** [emberjs/ember.js#19618]
### 🐞 Describe the Bug
After upgrading ember-cli to 3.27.0 and generating new app with ember new testapp --embroider after completion starting with ember s I get error with Cannot read property 'prototype' of undefined

### 🔬 Minimal Reproduction
npm install -g ember-cli 
ember new testapp --embroider 
cd testapp && ember s

### 😕 Actual Behavior
Blank screen. In browser console I can see this error `setup.js:20 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at eval (setup.js:20)
    at Object../node_modules/@ember-data/debug/setup.js (chunk.2d6e424bda0dae96afa5.js:160)
    at __webpack_require__ (chunk.43ae4f2aad47d63c9f29.js:31)
    at eval (ember-data-data-adapter.js:5)
    at Object../initializers/ember-data-data-adapter.js (chunk.e727f8edceb7abe16121.js:182)
    at __webpack_require__ (chunk.43ae4f2aad47d63c9f29.js:31)
    at Module.eval [as callback] (testapp327.js:25)
    at Module.exports (loader.js:106)
    at requireModule (loader.js:27)
    at resolveInitializer (index.js:10)`

### 🤔 Expected Behavior
Actual starting app :( ?

### 🌍 Environment
- ember-cli: 3.27.0
- Node.js/npm: 14.17.0 / 6.14.13
- OS: darwin x64
- Browser: Any

**Comment by locks** [comment]
Hi! Is this still a problem?

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. 

This seem like more of a question than a bug report/issue, and therefore better suited for the forums: https://discuss.emberjs.com/

Also, the reality for any open-source framework, relying on individuals to put in the work, is that there isn't always time to answer all questions.

If you want to pay back to the community, one easy thing is to ask one question in the forum (your current one), and also try to answer 2 questions from other people.

If you think this is an error, a reproduction of the bug and a more extensive explanation would be a good start. Then, if others agree it's a bug, the second step is often to dig in and write a patch to fix the bug.

I'll be closing this for now though, to keep the list of open issues manageable. I hope you understand.
