### ISSUE TITLE
LinkTo doesn't generate nothing

### ISSUE THREAD

**Issue by kafir-coder** [emberjs/ember.js#19710]
I just installed Ember version 3.27.0 and started to follow the guides in embers' site and when it was time to add some routing I was surprised with the inablity of <LinkTo></LinkTo> component works 

I used the bellow sintax:
<LinkTo @route="/ANY_ROUTE">ANY_ROUTE</LinkTo>

**Comment by bertdeblock** [comment]
Is the leading slash in your example by accident? Because route names shouldn't start with leading slashes. Is the route also registered with the router?

(I think you accidentally tagged a user with username `@route` as well).

**Comment by kafir-coder** [comment]
> Is the leading slash in your example by accident? Because route names shouldn't start with leading slashes. Is the route also registered with the router?
> 
> (I think you accidentally tagged a user with username `@route` as well).

@bertdeblock 

I just saw my code and this what it has:

`<div class="main-navbar">
  <div class="scafrando-logo">{{"</Scafrándo>"}}</div>
  <nav class="menu">
    <LinkTo @route={{1}}>
      Olá mundo
    </LinkTo>
    <LinkTo @route="about">About</LinkTo>
    <LinkTo @route="">Search</LinkTo>
  </nav>
</div>`

I already generated the about route with the command: ember generate route about

**Comment by kafir-coder** [comment]
Sorry

I just fixed it
