### ISSUE TITLE
[Bug] Random errors in brand new 3.28 app `TypeError: Cannot read property '_application' of undefined`

### ISSUE THREAD

**Issue by charlesfries** [emberjs/ember.js#19737]
### 🐞 Describe the Bug
I'm getting random errors every two page reloads or so in a brand new 3.28 Ember app.

`Uncaught RangeError: Maximum call stack size exceeded.`
`Uncaught TypeError: Cannot read property '_application' of undefined`
`Uncaught Error: Assertion Failed: The initializer 'ember-inspector-booted' has already been registered`

### 🔬 Minimal Reproduction

`ember -v`
> ember-cli: 3.28.0
> node: 14.17.1
> os: win32 x64

`ember new my-app`
`cd my-app`
`ember s`

### 😕 Actual Behavior
The app encounters runtime errors seemingly at random, about every two page reloads.

### 🤔 Expected Behavior
A new Ember app should run without errors.

### 🌍 Environment

- Ember: 3.28.0
- Node.js/npm: 14.17.1
- OS: win32 x64
- Browser: Chrome 92.0.4515.159

I've also tested this on macOS with the same result.

**Comment by kpfefferle** [comment]
@charlesfries I've also seen this error - but ONLY when I try to load my app with the Ember Inspector open. This makes me think this may be an issue with the Ember Inspector rather than with Ember itself (or a compatibility issue between the two) 🤔

**Comment by nlfurniss** [comment]
Seems like this issue is similar to yours: https://github.com/emberjs/ember-inspector/issues/1634

**Comment by charlesfries** [comment]
Closing in favor of emberjs/ember-inspector#1634
