### ISSUE TITLE
[Bug] [3.23.0+] Updating property value via yielded reference fails

### ISSUE THREAD

**Issue by dxmo** [emberjs/ember.js#19732]
### 🐞 Describe the Bug
I'm yielding a hash with a property that references a model property. When I then try to update this value in parent component via yielded hash reference it does not update the value on the model. This used to work prior to 3.23.0.

### 🔬 Minimal Reproduction
https://github.com/dxmo/ember-cp-bug

### 😕 Actual Behavior
When you modify the value in the first input, it does not update the value on the model - it seems to only update the value on the passed in hash?

### 🤔 Expected Behavior
Editing the value in either of the inputs should update the model property

### 🌍 Environment

- Ember: 3.23.0
- Node.js/npm: 14.17.5
- OS: MacOS Big Sur 11.5.2
- Browser: Chrome

**Comment by locks** [comment]
Linked PR above has been merged, so I believe this has been solved!
