### ISSUE TITLE
[Bug] A bunch of code gets written out on page instead of just the pretended error message

### ISSUE THREAD

**Issue by imartin-MT** [emberjs/ember.js#19742]
### 🐞 Describe the Bug
A bunch of code gets written out on page instead of the pretended message "Only one computed property decorator can be applied to a class field or accessor, but '${key}' was decorated twice. You may have added the decorator to both a getter and setter, which is unnecessary."

### 🔬 Minimal Reproduction
I just started working on this app so don't know how to set it up but this seems to be the offending code
EDIT: THIS WAS NOT THE OFFENDING CODE, ANSWER IN COMMENTS
![image](https://user-images.githubusercontent.com/57625850/132015441-ea9019fd-6fcc-493d-8343-d48d9a32587b.png)

### 😕 Actual Behavior
![image](https://user-images.githubusercontent.com/57625850/132014255-3ab92375-d557-4370-afae-04cf9d473206.png)
![image](https://user-images.githubusercontent.com/57625850/132014301-2027fd5b-351f-428b-843a-997bb4684b1f.png)

### 🤔 Expected Behavior
Only the message should be shown

### 🌍 Environment

- Ember: - 3.24.0
- Node.js/npm: - v14.17.5/6.14.14
- OS: - Ubuntu 20.04
- Browser: - Brave

**Comment by spicalous** [comment]
Not sure if it makes a difference, shouldn't `filterFunction` be written like the following when using classes?

filterFunction() {
  return true;
}

**Comment by imartin-MT** [comment]
I found this was the offending code 
`this.set('badge', Ember.computed('x.y.hasDirtyAttributes', 'x.y.requiresValidation', function() {
            if (this.get('x.y.requiresValidation')) {
                return 'unvalidated';
            } else if (this.get('x.y.hasDirtyAttributes')) {
                return 'not saved';
            }

            return null;
        }));`
        
       this works fine 
       
       `badge: computed('x.y.hasDirtyAttributes', 'x.y.requiresValidation', function() {
        if (this.get('x.y.requiresValidation')) {
            return 'unvalidated';
        } else if (this.get('x.y.hasDirtyAttributes')) {
            return 'not saved';
        }

        return null;
    }),`
