### ISSUE TITLE
tracked decorator documentation out of date

### ISSUE THREAD

**Issue by gilpinheiro** [emberjs/ember.js#19803]
https://github.com/emberjs/ember.js/blob/67d465f7603685b20a4dc27833164ceab7003559/packages/%40ember/-internals/metal/lib/tracked.ts#L46-L73

The in-code documentation seems to be out of date, specifically the @example Dependents (unsure, maybe my reading is wrong).

The 'tracked' decorator doesn't seem to handle dependencies in this way, and injecting this example into a project results in an error: 

> Error: Assertion Failed: tracked() may only receive an options object containing 'value' or 'initializer', received eatenApples

**Comment by jelhan** [comment]
@SergeAstapov I'm not sure if #19822 fixed the issue reported here. It addressed the wrong important. But if I got it right, this one was mainly about something else.

The docs cited by @gilpinheiro discuss that `@tracked` should be used on a getter, if that one relies on another tracked property. I think that's just wrong. Unless I fully misunderstood how autotracking works.

**Comment by SergeAstapov** [comment]
@jelhan Thank you for diligence! Indeed `@tracked` decorator should not be used on getters, it's intended to be added to the *root* tracked state property and all the getters just get recomputed on the assignment to the tracked property.

Created another PR #19827
