### ISSUE TITLE
Ember octane development build is not working or loading application in IE 11 browser

### ISSUE THREAD

**Issue by amit199309** [emberjs/ember.js#19829]
Ember octane development build is not working or loading application in IE 11 browser, set the target ie 11 in target.js inside browser array..after change build still not loading in ie, but production build working in IE.. do we have any way to work ember app in ie browser with development build..

### 😕 Actual Behavior
Application not loading in IE 11 with development build

### 🤔 Expected Behavior
Application should be load in ie with development build

### 🌍 Environment

- Ember: - ember octane 3.24

**Comment by snewcomer** [comment]
Do you have a reproduction we could look at?  Specifically an `ember new` app?

**Comment by amit199309** [comment]
@snewcomer yes we can reproduce with fresh app using ember new .. if we are building app ember build  --environment=Dev then app will not load in ie11 and if we use build environment prod then app will load.. so I am looking for solution to load app in ie11 with dev build. Thank you

**Comment by snewcomer** [comment]
Great!  Check your config/targets.js.  In there you will likely see ie11 only included in the prod build. You can reconfigure this file to make ie11 work in development.

**Comment by locks** [comment]
Thanks for the help @snewcomer! Closing as answered.

**Comment by amit199309** [comment]
@locks  Could you please open this issue, this is not fixed.

@snewcomer Yes I already changed target.js and included ie11 in target browser json array like below

'use strict';

const browsers = [
  'ie 9',
  'ie 11',
  'last 1 Chrome versions',
  'last 1 Firefox versions',
  'last 1 Safari versions'
];

const isCI = !!process.env.CI;
const isProduction = process.env.EMBER_ENV === 'production';

if (isCI || isProduction) {
  browsers.push('ie 11');
}

module.exports = {
  browsers
};

but this is not loading app in IE11 with dev build. Please help me out on this, Thank you
