### ISSUE TITLE
Production build or bundle size difference in Classic and Octane 

### ISSUE THREAD

**Issue by amit199309** [emberjs/ember.js#19889]
### 🐞 Describe the Bug
Hi Team,

Today I just created 2 fresh application one with ember classic version ( ember 3.2 ) and one with ember octane with glimmer comp ( ember 3.24 ). I build both the app with production flag and if we observe dist folder size or minified size of JavaScript then there is difference. 

Noticeable point is here while upgrading to latest version build or bundle size increased ( shall not be happen while upgrading to higher version ), because of that final app size increased and reason being app size increase and performance decreased to load the increased size app. 

### 🔬 Minimal Reproduction
1. create 2 fresh application with ember 3.2 and ember 3.24. 
2. Create the production build.
3. Compare the dist folder or minified js size.

### 😕 Actual Behavior
When we upgrade to higher version build size increased.

### 🤔 Expected Behavior
Build size should be decreased while upgrading to higher version..

### 🌍 Environment

- Ember: - 3.2 and 3.24
- Node.js/npm: - 14* / 6*
- OS: - Windows
- Browser: - Chrome

### ➕ Additional Context
Please refer below screen shot for reference. 
![image](https://user-images.githubusercontent.com/34087223/147931037-5925ba20-9a4c-4efa-9994-dbe6954437ad.png)
![image](https://user-images.githubusercontent.com/34087223/147931159-f67d56da-f200-42ed-9ff7-077de905944a.png)

**Comment by mehulkar** [comment]
You can use [source-map-explorer](https://www.npmjs.com/package/source-map-explorer) to see what exactly changed between the two bundles and report a more specific issue! It may just be that the size of one of the default dependencies changed or, more likely the way that glimmer templates are compiled changed, producing a bigger size.

**Comment by locks** [comment]
Thanks for reporting @amit199309. There are some known increases in bundle size, and you have to keep in mind that from 3.2 to 3.24 many new features were introduced (30, according to the [Upgrade](https://upgrade.emberjs.com/changes?fromVersion=3.2&toVersion=3.24) page), which can increase the size of the application.
Like @mehulkar said, I would take a deeper look into the build if this a concern for you.

The good news is that 3.28 seems to be smaller than 3.24, so the situation should improve when you upgrade!
I am closing as bundle size is something the team is very aware of, continuously monitors and tried to improve. I hope this is not a blocking issue, and if you try upgrading an application with a lot of templates, you should see the overall size drop!
