### ISSUE TITLE
Tooling: migrate from TSLint to ESLint for TypeScript internals

### ISSUE THREAD

**Issue by chriskrycho** [emberjs/ember.js#19899]
TSLint has been deprecated for a couple years. It’s well past time to move over to the `@typescript-eslint`-powered tooling.

Tasks that need doing here (and which most anyone in the community should be able to do):

0. Add the `@typescript-eslint/parser`, `@typescript-eslint/plugin`, etc. dependencies as documented on [the TypeScript ESLint website](https://typescript-eslint.io).
1. Create a mapping from [the tslint config](https://github.com/emberjs/ember.js/blob/master/tslint.json) to a modified version of the `@typescript-eslint/recommended` config, which should probably be our baseline.
2. Add the correct configuration to the existing [repo-wide ESLint config](https://github.com/emberjs/ember.js/blob/master/.eslintrc.js), using `@typescript-eslint/parser` for `.ts` files only so that there’s no impact on `.js` files from switching parsers.
3. Create a PR landing the above!

Given the rules in use, this should be fairly straightforward; the majority of the work is in step (1), and in particular making sure that we set things to the corresponding *level* of warning.

Feel free to reach out to Typed Ember folks (@dfreeman, @jamescdavis, and me) [on Discord](https://discord.com/channels/480462759797063690/484421406659182603) as well as current maintainers of Ember.

**Comment by wagenet** [comment]
Looks like we're actually using both. This removes TSLint: https://github.com/emberjs/ember.js/issues/19899
