### ISSUE TITLE
[Documentation] RouterService.transitionTo() API docs refer to API docs of deprecated Route.transitionTo() method

### ISSUE THREAD

**Issue by jelhan** [emberjs/ember.js#19896]
### 📙 Describe the Issue

The API docs for `transitionTo` method of `RouterService` refer the reader to API docs of `transitionTo` method of `Route`, which is deprecated "for more info".

The embedded link is also broken and does _not_ open the API docs of the deprecated method directly because deprecated methods are not shown by default

### 🔬 Minimal Reproduction

Source code: https://github.com/emberjs/ember.js/blob/b81e32407b9ed0191cb4d09dcfce9825db320570/packages/%40ember/-internals/routing/lib/services/router.ts#L75

API docs for Ember 4.1 (latest release by time of reporting this): https://api.emberjs.com/ember/release/classes/Route/methods/transitionTo?anchor=transitionTo&show=inherited%2Cdeprecated

### 😕 Actual Behavior

API docs point user to deprecated method for more information.

### 🤔 Expected Behavior

Information, which are present on API docs for `Route.transitionTo()` should be copied over to `RouterService.transitionTo()`.

### ➕ Additional Context

`Route.transitionTo` was deprecated by [RFC 674](https://github.com/emberjs/rfcs/blob/master/text/0674-deprecate-transition-methods-of-controller-and-route.md).

**Comment by Alzamer** [comment]
I'm interested in taking this on. It would be my first contribution for this project. Can you assign me?

**Comment by Satyap1766** [comment]
Hi, is anyone working in this ?

**Comment by locks** [comment]
Hi, I assigned @Alzamer as they asked before.

**Comment by gustavonikov** [comment]
Is someone taking this issue?

**Comment by kirtan-desai** [comment]
Looks like this issue is resolved @jelhan

**Comment by jelhan** [comment]
Thanks a lot for the heads up. Checked for `RouterService.transitionTo` and `RouterService.replaceWith`. Both are fixed. Thanks a lot to whoever took care of it!
