### ISSUE TITLE
[Bug] LinkTo inside inline SVG should use xlink:href attribute

### ISSUE THREAD

**Issue by vihai** [emberjs/ember.js#19892]
### 🐞 Describe the Bug
Anchors inside inline SVG are supported, however the xlink namespace should be used for the href attribute. It would be nice to have some sort of autodetection or, in alternative, a parameter to specify how to generate the tag or a LinkTo component specifically for inline SVG.

### 🔬 Minimal Reproduction
```
<svg version="1.1" viewBox="0 0 200 100" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
  <LinkTo @route="agui.network.uplinks">
    <rect x="0" y="0" width="200" height="100"></rect>
  </LinkTo>
</svg>
```

### 🌍 Environment

- Ember: 4.1
- Node.js/npm: 16.13.1
- OS: Ubuntu 21.10
- Browser: Firefox 95 / Chrome 97

**Comment by mhankus** [comment]
According to MDN xlink should not be used [https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href)
