### ISSUE TITLE
[Bug] New ember app fails in production build

### ISSUE THREAD

**Issue by miguelcobain** [emberjs/ember.js#19912]
### 🐞 Describe the Bug
After creating a new ember app and running the production build, there is a **runtime** error:
```
Uncaught TypeError: Cannot destructure property 'manager' of 'e' as it is null.
```

Disabling `ember-cli-terser` doesn't fix the problem, and I get the more readable version of the error:
```
Uncaught TypeError: Cannot destructure property 'manager' of 'resolvedDefinition' as it is null.
```

### 🔬 Minimal Reproduction

Run `ember new my-app && cd my-app && ember s --environment=production`

### 😕 Actual Behavior
We get a runtime error.

### 🤔 Expected Behavior
App should work without errors.

### 🌍 Environment

- Ember: 4.1.0
- Node.js/npm: 14.18.2 / 6.14.15
- OS: MacOS Monterey
- Browser: Chrome 97.0.4692.99

**Comment by NullVoxPopuli** [comment]
It's the welcome page! 
![image](https://user-images.githubusercontent.com/199018/150623431-4446e508-fc38-4ed6-93a2-fc5444022876.png)

**Comment by NullVoxPopuli** [comment]
Opened issue on welcome page here: https://github.com/ember-cli/ember-welcome-page/issues/385

So, if anyone else comes across this issue, the fix is to delete `<WelcomePage />` from application.hbs

**Comment by locks** [comment]
This is known and intentional.

**Comment by NullVoxPopuli** [comment]
Could use a more descriptive error tho.

This bug report could actually be: 

Error is incorrect for situation. Not directly actionable

**Comment by miguelcobain** [comment]
I think showing a build time warning if welcome-page addon is used in production would be enough.
Some people came to me on discord asking if I found the solution.
