### ISSUE TITLE
[Bug] Not allowed to remove app.css

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember.js#19915]
### 🐞 Describe the Bug

I tried deleting {{app}}.css and vendor.css, and got this error:
```
Could not find app css: "/assets/wordle.css" in index.html. Found the following instead:
```

Error appears in `ember s` terminal.

_using embroider_.

### 🔬 Minimal Reproduction
Any app, delete the two links to the default CSS

### 😕 Actual Behavior
error

### 🤔 Expected Behavior
no error, request not made

### 🌍 Environment

- Ember: - 4.1.0
- Node.js/npm: - n/a
- OS: - n/a
- Browser: - n/a

### ➕ Additional Context

I'm using tailwind via `npx ember-apply tailwind`, so I don't need app.css

**Comment by Windvis** [comment]
I think this is an Embroider issue and there is an issue in that repo that is related: https://github.com/embroider-build/embroider/issues/1033

Quote from a reply in there that explains the error message: 
> I think the main feature we will need is the ability to disable the classic CSS support for the app (while keeping it for any addons that are relying on it). That is what is forcing app/styles/app.css to exist.

**Comment by NullVoxPopuli** [comment]
I don't think i was using embroider 🤔

**Comment by Windvis** [comment]
Oh, I assumed you were since the description mentions "_using embroider._" :smile:

**Comment by NullVoxPopuli** [comment]
Oh shoot, i am! I missed that in re-reading my issue '😅

**Comment by kategengler** [comment]
@NullVoxPopuli Should we close this issue since it is covered by the embroider issue?

**Comment by NullVoxPopuli** [comment]
I suppose, ya

**Comment by NullVoxPopuli** [comment]
Because the embroider issue is a bit more focused on sass, I moved this issue to the embroider repo: https://github.com/embroider-build/embroider/issues/1093
