### ISSUE TITLE
[Bug] [ember@3.27+] "jquery" is broken with IE11 and "embroider" enabled

### ISSUE THREAD

**Issue by ro0gr** [emberjs/ember.js#19927]
### 🐞 Describe the Bug

I've noticed a strange issue with `jquery` as an addon dependency with embroider enabled starting from the [ember-source@3.27.0-beta.1](https://github.com/emberjs/ember.js/releases/tag/v3.27.0-beta.1) and up to the latest version.

if enable `IE11` build target,
```js
// tests/dummy/config/targets.js
...
browsers.push('ie 11');
```
which is commented out starting from the ember@3.27 https://github.com/ember-cli/ember-addon-output/blob/v3.27.0/tests/dummy/config/targets.js, all the `jquery` imports just stop working.

This might be an embroider issue(please let me know if I should report there), but it's still somehow related to the changes maden in the 3.27.0-beta.1 of ember-source specifically.

### 🔬 Minimal Reproduction

- Generate ember addon higher than ember@~3.26.0
- Setup `embroider`
- Install `jquery` as a dependency
- Enable `IE11` in the "tests/dummy/config/targets.js"
- Run and execute:
```js
import $ from 'jquery';
$();
```

Reproduction https://github.com/ro0gr/ember-3.27-_ie11_jquery_reproduction/pull/1

### 😕 Actual Behavior

```js
import $ from 'jquery';

$ === undefined;
```

In the build output I can see the following message:

> export 'default' (imported as '$') was not found in 'jquery' (module has no exports)

### 🤔 Expected Behavior

I expect a dependency to be just importable, especially under `embroider`.

```js
import $ from 'jquery';

assert($ instanceof Function);
```

### 🌍 Environment

- Ember: 3.27.0-beta.1, 3.28+
- Node.js/npm: 12,14,17/6,8
- OS: macOS
- Browser: Chrome

### ➕ Additional Context

I've discovered it during embreoider upgrade in the ember-cli-page-object lib, which uses plain jquery for some stuff still. I guess I'd just disable IE build target, but I'm not sure if it would cause an issue for the users with IE11 build target enabled? if such this technically looks like a breaking change within ember@3 lifecycle.

**Comment by ro0gr** [comment]
changes here look potentially related https://github.com/emberjs/ember.js/pull/19463/files#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1R227

**Comment by kategengler** [comment]
This could potentially be related https://github.com/embroider-build/embroider/issues/673

What happens if you add [@ember/jquery](https://github.com/emberjs/ember-jquery) in place of `jquery`?

**Comment by ro0gr** [comment]
@kategengler Thanks! Ya, this issue looks quite related, but in my case instead of import error I have an import warning message + runtime error, like described above. I'd check if the scenario reported in the embroider repo reproduces against the ember-source@3.26, which could provide some more context.

> What happens if you add @ember/jquery in place of jquery?

it seems to work. But I don't think that's an option in my case. I just like to use pure `jquery`.

**Comment by kategengler** [comment]
@ro0gr So long as you have `"jquery-integration": false` in your optional features, all `@ember/jquery` will do is provide pure `jquery` available as imported from `jquery` https://github.com/emberjs/ember-jquery#usage

**Comment by kategengler** [comment]
Closing in favor of the embroider issue.

**Comment by ro0gr** [comment]
@kategengler as I mentioned before, jquery is used by addon internally. I don't think there is a way to affect app's optional features from addon. That's why I say "that's not an option for me".

Ok, I'll try to get some more info from the embroider side, but it seems suspicious to me that the problem starts to happen with specific version of ember, not embroider.

**Comment by kategengler** [comment]
@ro0gr I believe you can safely add `@ember/jquery` to an addon with `jquery-integration: false` and not affect the host project that is using your addon other than to merely add `jquery`.

**Comment by ro0gr** [comment]
> and not affect the host project

@kategengler I must have have been confusing with my exlanations, sorry! I do want to affect the host in test environment. 

There are some jquery utils which are used by ec-page-object internally to operate in the app tests. That's why I believe `@ember/jquery` is not an option for me, and I really need to use pure `jquery`.

However, I don't want to bother you anymore. Thanks for your time. I'd try to investigate it a bit more on my own for now.

**Comment by kategengler** [comment]
If your addon has @ember/jquery as a dependency, it will put pure jquery into the build available as `import jquery from 'jquery'`, any addon code will be able to use that.

**Comment by ro0gr** [comment]
@kategengler didn't know that. Thank you!
