### ISSUE TITLE
[QUEST] Future Public TypeScript Types

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember.js#19946]
The plan is eventually for Ember to export all of its own TypeScript types. In preparation for this, we'd like to have the internal Ember modules export the correct types.

## RFC 0176 Types

These are the full set of APIs Ember has exposed, per [the officially maintained data](https://github.com/ember-cli/ember-rfc176-data). This may include items that have been deprecated or removed!

<details><summary><b>Detailed Status breakdown</b></summary>

Unchecked items are one of the following:
* Unimplemented
* Untested
* Things we don't want to export

### `@ember/application`
* [x] `import Application from '@ember/application':` - `Ember.Application`
* [x] `import { getOwner } from '@ember/application';` - `Ember.getOwner`
* [ ] ~`import { onLoad } from '@ember/application';` - `Ember.onLoad`~
* [ ] ~`import { runLoadHooks } from '@ember/application';` - `Ember.runLoadHooks`~
* [x] `import { setOwner } from '@ember/application';` - `Ember.setOwner`
* [ ] ~`import GlobalsResolver from '@ember/application/globals-resolver';` - `Ember.DefaultResolver`~
* [x] `import ApplicationInstance from '@ember/application/instance';` - `Ember.ApplicationInstance`
* [x] `import Namespace from '@ember/application/namespace';` - `Ember.Namespace`
* [ ] ~`import Resolver from '@ember/application/resolver';` - `Ember.Resolver`~

### `@ember/array`
* [x] `import EmberArray from '@ember/array';` - `Ember.Array`
* [x] `import { A } from '@ember/array';` - `Ember.A`
* [x] `import { isArray } from '@ember/array';` - `Ember.isArray`
* [x] `import { makeArray } from '@ember/array';` - `Ember.makeArray`
* [x] `import MutableArray from '@ember/array/mutable';` - `Ember.MutableArray`
* [x] `import ArrayProxy from '@ember/array/proxy';` - `Ember.ArrayProxy`

### `@ember/canary-features` (PR: #19947)
* [x] `import { FEATURES } from '@ember/canary-features';` - `Ember.FEATURES`
* [x] `import { isEnabled } from '@ember/canary-features';` - `Ember.FEATURES.isEnabled`

### `@ember/component` (PR: #19948)
* [x] `import Component from '@ember/component';` - `Ember.Component`
* [x] `import { Input } from '@ember/component';` - `Ember._Input`
* [x] `import { Textarea } from '@ember/component';` - `Ember._TextArea`
* [x] `import { capabilities } from '@ember/component';` - `Ember._componentManagerCapabilities`
* [x] **UNTESTED** `import { getComponentTemplate } from '@ember/component';` - `Ember._getComponentTemplate`
* [x] **UNTESTED** `import { setComponentManager } from '@ember/component';` - `Ember._setComponentManager`
* [x] `import { setComponentTemplate } from '@ember/component';` - `Ember._setComponentTemplate`
* [ ] ~`import Checkbox from '@ember/component/checkbox';` - `Ember.Checkbox`~
* [x] `import Helper from '@ember/component/helper';` - `Ember.Helper`
* [x] `import { helper as buildHelper } from '@ember/component/helper';` - `Ember.Helper.helper`
* [x] `import templateOnlyComponent from '@ember/component/template-only';` - `Ember._templateOnlyComponent`
* [ ] ~`import TextArea from '@ember/component/text-area';` - `Ember.TextArea`~
* [ ] ~`import TextField from '@ember/component/text-field';` - `Ember.TextField`~

### `@ember/controller`
* [x] `import Controller from '@ember/controller';` - `Ember.Controller`
* [x] `import { inject } from '@ember/controller';` - `Ember.inject.controller`

### `@ember/debug` (PR: #19947)
* [x] `import { assert } from '@ember/debug';` - `Ember.assert`
* [x] `import { debug } from '@ember/debug';` - `Ember.debug`
* [ ] ~`import { inspect } from '@ember/debug';` - `Ember.inspect`~
* [x] `import { registerDeprecationHandler } from '@ember/debug';` - `Ember.Debug.registerDeprecationHandler`
* [x] `import { registerWarnHandler } from '@ember/debug';` - `Ember.Debug.registerWarnHandler`
* [x] `import { runInDebug } from '@ember/debug';` - `Ember.runInDebug`
* [x] `import { warn } from '@ember/debug';` - `Ember.warn`
* [x] `import ContainerDebugAdapter from '@ember/debug/container-debug-adapter';` - `Ember.ContainerDebugAdapter`
* [x] `import DataAdapter from '@ember/debug/data-adapter';` - `Ember.DataAdapter`

### `@ember/destroyable` (PR: #19947)
* [x] `import { assertDestroyablesDestroyed } from '@ember/destroyable';` - `Ember._assertDestroyablesDestroyed`
* [x] `import { associateDestroyableChild } from '@ember/destroyable';` - `Ember._associateDestroyableChild`
* [x] `import { destroy } from '@ember/destroyable';` - `Ember.destroy`
* [x] `import { enableDestroyableTracking } from '@ember/destroyable';` - `Ember._enableDestroyableTracking`
* [x] `import { isDestroyed } from '@ember/destroyable';` - `Ember._isDestroyed`
* [x] `import { isDestroying } from '@ember/destroyable';` - `Ember._isDestroying`
* [x] `import { registerDestructor } from '@ember/destroyable';` - `Ember._registerDestructor`
* [x] `import { unregisterDestructor } from '@ember/destroyable';` - `Ember._unregisterDestructor`

### `@ember/engine` (PR: #19923)
* [x] `import Engine from '@ember/engine';` - `Ember.Engine`
* [x] `import { getEngineParent } from '@ember/engine';` - `Ember.getEngineParent`
* [x] `import EngineInstance from '@ember/engine/instance';` - `Ember.EngineInstance`

### `@ember/enumerable`
* [x] `import Enumerable from '@ember/enumerable';` - `Ember.Enumerable`

### `@ember/error` (PR: #19947)
* [x] `import EmberError from '@ember/error';` - `Ember.Error`

### `@ember/helper` (PR: #19947)
* [x] `import { array } from '@ember/helper';` - `Ember._array`
* [x] `import { capabilities } from '@ember/helper';` - `Ember._helperManagerCapabilities`
* [x] `import { concat } from '@ember/helper';` - `Ember._concat`
* [x] `import { fn } from '@ember/helper';` - `Ember._fn`
* [x] `import { get } from '@ember/helper';` - `Ember._get`
* [x] `import { hash } from '@ember/helper';` - `Ember._hash`
* [x] `import { invokeHelper } from '@ember/helper';` - `Ember._invokeHelper`
* [x] `import { setHelperManager } from '@ember/helper';` - `Ember._setHelperManager`

### `@ember/instrumentation`
* [ ] `import { instrument } from '@ember/instrumentation';` - `Ember.Instrumentation.instrument`
* [ ] `import { reset } from '@ember/instrumentation';` - `Ember.Instrumentation.reset`
* [ ] `import { subscribe } from '@ember/instrumentation';` - `Ember.Instrumentation.subscribe`
* [ ] `import { unsubscribe } from '@ember/instrumentation';` - `Ember.Instrumentation.unsubscribe`

### `@ember/map`
* [ ] `import EmberMap from '@ember/map';` - `Ember.Map`
* [ ] `import MapWithDefault from '@ember/map/with-default';` - `Ember.MapWithDefault`

### `@ember/modifier`
* [x] `import { capabilities } from '@ember/modifier';` - `Ember._modifierManagerCapabilities`
* [x] `import { on } from '@ember/modifier';` - `Ember._on`
* [x] `import { setModifierManager } from '@ember/modifier';` - `Ember._setModifierManager`

### `@ember/object`
* [x] `import EmberObject from '@ember/object';` - `Ember.Object`
* [x] `import { action } from '@ember/object';` - `Ember._action`
* [ ] ~`import { aliasMethod } from '@ember/object';` - `Ember.aliasMethod`~
* [x] `import { computed } from '@ember/object';` - `Ember.computed`
* [x] `import { defineProperty } from '@ember/object';` - `Ember.defineProperty`
* [x] `import { get } from '@ember/object';` - `Ember.get`
* [x] `import { getProperties } from '@ember/object';` - `Ember.getProperties`
* [ ] ~`import { getWithDefault } from '@ember/object';` - `Ember.getWithDefault`~
* [x] `import { notifyPropertyChange } from '@ember/object';` - `Ember.notifyPropertyChange`
* [x] `import { observer } from '@ember/object';` - `Ember.observer`
* [x] `import { set } from '@ember/object';` - `Ember.set`
* [x] `import { setProperties } from '@ember/object';` - `Ember.setProperties`
* [x] `import { trySet } from '@ember/object';` - `Ember.trySet`
* [x] `import { dependentKeyCompat } from '@ember/object/compat';` - `Ember._dependentKeyCompat`
* [x] `import ComputedProperty from '@ember/object/computed';` - `Ember.ComputedProperty`
* [x] `import { alias } from '@ember/object/computed';` - `Ember.computed.alias`
* [x] `import { and } from '@ember/object/computed';` - `Ember.computed.and`
* [x] `import { bool } from '@ember/object/computed';` - `Ember.computed.bool`
* [x] `import { collect } from '@ember/object/computed';` - `Ember.computed.collect`
* [x] `import { deprecatingAlias } from '@ember/object/computed';` - `Ember.computed.deprecatingAlias`
* [x] `import { empty } from '@ember/object/computed';` - `Ember.computed.empty`
* [x] `import { equal } from '@ember/object/computed';` - `Ember.computed.equal`
* [x] `import { expandProperties } from '@ember/object/computed';` - `Ember.expandProperties`
* [x] `import { filter } from '@ember/object/computed';` - `Ember.computed.filter`
* [x] `import { filterBy } from '@ember/object/computed';` - `Ember.computed.filterBy`
* [ ] ~`import { filterProperty } from '@ember/object/computed';` - `Ember.computed.filterProperty`~
* [x] `import { gt } from '@ember/object/computed';` - `Ember.computed.gt`
* [x] `import { gte } from '@ember/object/computed';` - `Ember.computed.gte`
* [x] `import { intersect } from '@ember/object/computed';` - `Ember.computed.intersect`
* [x] `import { lt } from '@ember/object/computed';` - `Ember.computed.lt`
* [x] `import { lte } from '@ember/object/computed';` - `Ember.computed.lte`
* [x] `import { map } from '@ember/object/computed';` - `Ember.computed.map`
* [x] `import { mapBy } from '@ember/object/computed';` - `Ember.computed.mapBy`
* [ ] ~`import { mapProperty } from '@ember/object/computed';` - `Ember.computed.mapProperty`~
* [x] `import { match } from '@ember/object/computed';` - `Ember.computed.match`
* [x] `import { max } from '@ember/object/computed';` - `Ember.computed.max`
* [x] `import { min } from '@ember/object/computed';` - `Ember.computed.min`
* [x] `import { none } from '@ember/object/computed';` - `Ember.computed.none`
* [x] `import { not } from '@ember/object/computed';` - `Ember.computed.not`
* [x] `import { notEmpty } from '@ember/object/computed';` - `Ember.computed.notEmpty`
* [x] `import { oneWay } from '@ember/object/computed';` - `Ember.computed.oneWay`
* [x] `import { or } from '@ember/object/computed';` - `Ember.computed.or`
* [x] `import { readOnly } from '@ember/object/computed';` - `Ember.computed.readOnly`
* [x] `import { reads } from '@ember/object/computed';` - `Ember.computed.reads`
* [x] `import { setDiff } from '@ember/object/computed';` - `Ember.computed.setDiff`
* [x] `import { sort } from '@ember/object/computed';` - `Ember.computed.sort`
* [x] `import { sum } from '@ember/object/computed';` - `Ember.computed.sum`
* [x] `import { union } from '@ember/object/computed';` - `Ember.computed.union`
* [x] `import { uniq } from '@ember/object/computed';` - `Ember.computed.uniq`
* [x] `import { uniqBy } from '@ember/object/computed';` - `Ember.computed.uniqBy`
* [x] `import CoreObject from '@ember/object/core';` - `Ember.CoreObject`
* [x] `import Evented from '@ember/object/evented';` - `Ember.Evented`
* [x] `import { on } from '@ember/object/evented';` - `Ember.on`
* [x] `import { addListener } from '@ember/object/events';` - `Ember.addListener`
* [x] `import { removeListener } from '@ember/object/events';` - `Ember.removeListener`
* [x] `import { sendEvent } from '@ember/object/events';` - `Ember.sendEvent`
* [x] `import { cacheFor } from '@ember/object/internals';` - `Ember.cacheFor`
* [ ] ~`import { copy } from '@ember/object/internals';` - `Ember.copy`~
* [x] `import { guidFor } from '@ember/object/internals';` - `Ember.guidFor`
* [x] `import Mixin from '@ember/object/mixin';` - `Ember.Mixin`
* [x] `import Observable from '@ember/object/observable';` - `Ember.Observable`
* [x] `import { addObserver } from '@ember/object/observers';` - `Ember.addObserver`
* [x] `import { removeObserver } from '@ember/object/observers';` - `Ember.removeObserver`
* [x] **UNTESTED** `import PromiseProxyMixin from '@ember/object/promise-proxy-mixin';` - `Ember.PromiseProxyMixin`
* [x] **UNTESTED INTERNALLY**`import ObjectProxy from '@ember/object/proxy';` - `Ember.ObjectProxy`

### `@ember/polyfills` (PR: #19947)
* [x] `import { assign } from '@ember/polyfills';` - `Ember.assign`
* [ ] ~`import { create } from '@ember/polyfills';` - `Ember.create`~
* [x] **UNTESTED** `import { hasPropertyAccessors } from '@ember/polyfills';` - `Ember.platform.hasPropertyAccessors`
* [ ] ~`import { keys } from '@ember/polyfills';` - `Ember.keys`~
* [ ] ~`import { merge } from '@ember/polyfills';` - `Ember.merge`~

### `@ember/routing`
* [x] `import { LinkTo } from '@ember/routing';` - `Ember.LinkComponent`
* [x] `import AutoLocation from '@ember/routing/auto-location';` - `Ember.AutoLocation`
* [x] `import HashLocation from '@ember/routing/hash-location';` - `Ember.HashLocation`
* [x] `import HistoryLocation from '@ember/routing/history-location';` - `Ember.HistoryLocation`
* [ ] ~`import LinkComponent from '@ember/routing/link-component';` - `Ember.LinkComponent`~
* [x] `import Location from '@ember/routing/location';` - `Ember.Location`
* [x] `import NoneLocation from '@ember/routing/none-location';` - `Ember.NoneLocation`
* [x] `import Route from '@ember/routing/route';` - `Ember.Route`
* [x] `import EmberRouter from '@ember/routing/router';` - `Ember.Router`
* [x] `import RouterService from '@ember/routing/router-service';` - `Ember.RouterService`

### `@ember/runloop` (PR: #19947)
* [ ] `import { _backburner } from '@ember/runloop';` - `Ember.run.backburner`
* [ ] `import { _cancelTimers } from '@ember/runloop';` - `Ember.run.cancelTimers`
* [ ] `import { _getCurrentRunLoop } from '@ember/runloop';` - `Ember.run._getCurrentRunLoop`
* [ ] `import { _hasScheduledTimers } from '@ember/runloop';` - `Ember.run.hasScheduledTimers`
* [x] `import { begin } from '@ember/runloop';` - `Ember.run.begin`
* [x] `import { bind } from '@ember/runloop';` - `Ember.run.bind`
* [x] `import { cancel } from '@ember/runloop';` - `Ember.run.cancel`
* [x] `import { debounce } from '@ember/runloop';` - `Ember.run.debounce`
* [x] `import { end } from '@ember/runloop';` - `Ember.run.end`
* [x] `import { join } from '@ember/runloop';` - `Ember.run.join`
* [x] `import { later } from '@ember/runloop';` - `Ember.run.later`
* [x] `import { next } from '@ember/runloop';` - `Ember.run.next`
* [x] `import { once } from '@ember/runloop';` - `Ember.run.once`
* [x] `import { run } from '@ember/runloop';` - `Ember.run`
* [x] `import { schedule } from '@ember/runloop';` - `Ember.run.schedule`
* [x] `import { scheduleOnce } from '@ember/runloop';` - `Ember.run.scheduleOnce`
* [x] `import { throttle } from '@ember/runloop';` - `Ember.run.throttle`

### `@ember/service`
* [x] `import Service from '@ember/service';` - `Ember.Service`
* [x] `import { inject } from '@ember/service';` - `Ember.inject.service`
* [x] `import { service } from '@ember/service';`

### `@ember/template` (PR: #19947)
* [x] `import { htmlSafe } from '@ember/template';` - `Ember.String.htmlSafe`
* [x] `import { isHTMLSafe } from '@ember/template';` - `Ember.String.isHTMLSafe`

### `@ember/template-compilation` **NO EXTERNAL TYPES**
* [ ] `import { compileTemplate } from '@ember/template-compilation';` - `Ember.HTMLBars.compile`
* [ ] `import { precompileTemplate } from '@ember/template-compilation';` - `Ember.HTMLBars.precompile`

### `@ember/template-factory` **NO EXTERNAL TYPES**
* [ ] `import { createTemplateFactory } from '@ember/template-factory';` - `Ember.HTMLBars.template`

### `@ember/utils` (PR: #19947)
* [x] `import { compare } from '@ember/utils';` - `Ember.compare`
* [x] `import { isBlank } from '@ember/utils';` - `Ember.isBlank`
* [x] `import { isEmpty } from '@ember/utils';` - `Ember.isEmpty`
* [x] `import { isEqual } from '@ember/utils';` - `Ember.isEqual`
* [x] `import { isNone } from '@ember/utils';` - `Ember.isNone`
* [x] `import { isPresent } from '@ember/utils';` - `Ember.isPresent`
* [ ] ~`import { tryInvoke } from '@ember/utils';` - `Ember.tryInvoke`~
* [x] `import { typeOf } from '@ember/utils';` - `Ember.typeOf`

### `@ember/version` (PR: #19947)
* [x] `import { VERSION } from '@ember/version';` - `Ember.VERSION`

</details>

## Packages to stabilize

This is a list of all types exported by DT. Items should be marked here when they've been compared to the DT types and validated as correct. Note that the DT types could be incorrect in some cases.

- [x] `ember` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/application` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/application/instance` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/array` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/array/mutable` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/array/proxy` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/component` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/component/helper` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/component/template-only` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/controller` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/debug` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/debug/container-debug-adapter` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/debug/data-adapter` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/destroyable` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/engine` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/engine/instance` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/error` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/helper` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/modifier` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/object` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/object/compat` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/object/computed` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/object/core` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/object/evented` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/object/events` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/object/internals` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/object/mixin` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/object/observable` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/object/observers` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/object/promise-proxy-mixin` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/object/proxy` https://github.com/emberjs/ember.js/pull/20449
- [-] `@ember/ordered-set`
- [x] `@ember/owner`: https://github.com/emberjs/ember.js/pull/20288
- [-] `@ember/polyfills` – removed in Ember 5.0
- [x] `@ember/routing` https://github.com/emberjs/ember.js/pull/20449
- [-] `@ember/routing/auto-location` – removed in Ember 5.0
- [x] `@ember/routing/hash-location` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/routing/history-location` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/routing/none-location` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/routing/route` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/routing/router-service` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/routing/router` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/runloop` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/service` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/string` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/template` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/test` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/test/adapter` https://github.com/emberjs/ember.js/pull/20449
- [x] `@ember/utils` https://github.com/emberjs/ember.js/pull/20449

**Comment by chriskrycho** [comment]
@wagenet what's the status on the open items in this one?

**Comment by wagenet** [comment]
Good question. I'll try to give an update this week.

**Comment by chriskrycho** [comment]
We actually *do* need the `import Ember from 'ember'` types, because at least some of them are not actually available anywhere else (e.g. `Ember.testing`). We should, separately, close any remaining gaps and deprecate the `Ember` namespace export for removal (presumably in 6.0).

**Comment by chriskrycho** [comment]
Mechanically, for validating a package for stability, here is a rough guide to workflow for anyone who wants to contribute:

- Copy the type tests for any given package from `type-tests/preview` over to `type-tests/stable`. (There are also type tests colocated with the package source code, but those often test internal type details, and we'll want to be able to evolve them separately from our checks of the public API, which is what the others represent.)

- Update `types/publish.mjs` to remove the package you are working on from the `PREVIEW_MODULES` definition. For example, if you were working on stabilizing `@ember/application`, you would apply the following diff:

    ```diff
      './@ember/-internals/views/lib/views/states.d.ts',
      './@ember/-internals/views/lib/views/states/default.d.ts',
      './@ember/-internals/views/lib/views/states/destroying.d.ts',
      './@ember/-internals/views/lib/views/states/has_element.d.ts',
      './@ember/-internals/views/lib/views/states/in_dom.d.ts',
      './@ember/-internals/views/lib/views/states/pre_render.d.ts',
    - './@ember/application/index.d.ts',
    - './@ember/application/instance.d.ts',
    - './@ember/application/lib/lazy_load.d.ts',
    - './@ember/application/namespace.d.ts',
      './@ember/array/index.d.ts',
      './@ember/array/mutable.d.ts',
      './@ember/array/proxy.d.ts',
    ```

- Run the type tests against the published types:

    ```sh
    yarn types
    yarn type-check:stable
    ```

- Figure out whether discrepancies are the fault of the preview types or Ember's own types (with a presumption that it's the former, for obvious reasons; but there's enough any and unsafe casting in Ember that it's not a guarantee for sure) and fix them in the appropriate spot.
