### ISSUE TITLE
`{{outlet}}` implementation still contains code for supporting named outlets

### ISSUE THREAD

**Issue by bertdeblock** [emberjs/ember.js#19942]
For example:
https://github.com/emberjs/ember.js/blob/v4.1.0/packages/%40ember/-internals/glimmer/lib/syntax/outlet.ts#L52-L58

Noticed this when creating #19941.

Related RFC:
https://emberjs.github.io/rfcs/0418-deprecate-route-render-methods.html

**Comment by yencvt** [comment]
why remove outlet named?

**Comment by bertdeblock** [comment]
You can read the merged RFC if you need more info:
https://rfcs.emberjs.com/id/0418-deprecate-route-render-methods/
