### ISSUE TITLE
[Bug] Creating multiple records without saving delete the relationship

### ISSUE THREAD

**Issue by khaled-s** [emberjs/ember.js#20006]
I'm using a button to create multiple records on the client-side and store them in a list
these records have a relationship with other models, 
each time I create a record, the previously created record set the relation to null if it's the same id 

for example:

```
let commentList = [] \n
for(let x=0, x<3, x++) {
    let comment = this.store.createRecord('comment', {
                data: {id:2}, // not fixed
                post: {id: 1}, // fixed id
            });
   commentList.push(comment)
}
```

printing this list shows that the first two records post ids is null and the third is set to 1

- Ember: 3.28
- Node.js/npm: 14.16.1
- OS: Ubuntu
- Browser: Chrome

**Comment by bertdeblock** [comment]
This seems like an Ember Data issue. Ember Data has its own separate issue tracker here: https://github.com/emberjs/data/issues.

**Comment by khaled-s** [comment]
Thanks, @bertdeblock , I will open an issue there
