### ISSUE TITLE
[Bug] Deprecation warnings with an empty, newly created app with LTS (3.28.8) version

### ISSUE THREAD

**Issue by emoryy** [emberjs/ember.js#20021]
### 🐞 Describe the Bug
When generating a new Ember app with the current LTS version (3.28.8) the app produces a bunch of deprecation warnings in the browser. This happens with the empty app, that is nothing was yet added or modified.
At this point the deprecation warnings are more descriptive, suggesting that updating dependencies could help, however updating the one dependency that it mentions explicitly (ember-maybe-import-regenerator) doesn't help.
![image](https://user-images.githubusercontent.com/5493763/158195344-026e818d-71bf-4c73-954b-606333582d97.png)
After updating some more of the dependencies and adding webpack for the newer ember-auto-import the relevant part of `package.json` looks as follows:
```
  "devDependencies": {
    "@ember/optional-features": "^2.0.0",
    "@ember/test-helpers": "^2.6.0",
    "@glimmer/component": "^1.0.4",
    "@glimmer/tracking": "^1.0.4",
    "babel-eslint": "^10.1.0",
    "broccoli-asset-rev": "^3.0.0",
    "ember-auto-import": "^2.4.0",
    "ember-cli": "~3.28.5",
    "ember-cli-app-version": "^5.0.0",
    "ember-cli-babel": "^7.26.11",
    "ember-cli-dependency-checker": "^3.2.0",
    "ember-cli-htmlbars": "^6.0.1",
    "ember-cli-inject-live-reload": "^2.1.0",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-terser": "^4.0.2",
    "ember-data": "~3.28.6",
    "ember-export-application-global": "^2.0.1",
    "ember-fetch": "^8.1.1",
    "ember-load-initializers": "^2.1.2",
    "ember-maybe-import-regenerator": "^1.0.0",
    "ember-page-title": "^7.0.0",
    "ember-qunit": "^5.1.5",
    "ember-resolver": "^8.0.3",
    "ember-source": "~3.28.8",
    "ember-template-lint": "^3.15.0",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-ember": "^10.5.8",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^3.4.1",
    "eslint-plugin-qunit": "^6.2.0",
    "loader.js": "^4.7.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.5.1",
    "qunit": "^2.18.0",
    "qunit-dom": "^2.0.0",
    "webpack": "^5.70.0"
  },
```
At this point the deprecation warnings are still present however they are more compact.
There are 5 warnings for "Ember Global" and then one for each for the computed macros like `computed.alias`, one each for methods on run, like `run.backburner` and at last one warning for `Ember.TargetActionSupport`
![image](https://user-images.githubusercontent.com/5493763/158195192-4881d4a5-1a01-4c6c-ac63-41db4c0276cf.png)
For example the first warning seems to be coming from `http://localhost:4200/assets/@ember/-internals/bootstrap/index.js`

### 🔬 Minimal Reproduction
Install ember-cli 3.28.8, and create a new Ember app, open it in the browser and open DevTools

### 😕 Actual Behavior
The newly created app prints a lot of unexpected deprecation warnings.

### 🤔 Expected Behavior
A newly created, empty app shouldn't self deprecate.

### 🌍 Environment

- Ember: 3.28.8
- Node.js/npm: 16.14.0

**Comment by Windvis** [comment]
I think the issue is caused by the Ember Inspector. Can you try disabling the extension and see if the deprecations are still shown?

I opened an issue in the Ember Inspector repo: https://github.com/emberjs/ember-inspector/issues/1939

**Comment by emoryy** [comment]
Indeed, it seems warnings aren't shown until the Ember Inspector is enabled and opened.

**Comment by locks** [comment]
According to the linked PR, this issue should be addressed.
