### ISSUE TITLE
[Bug] `has-block` not wrapped in parentheses fails silently

### ISSUE THREAD

**Issue by emattias** [emberjs/ember.js#20057]
### 🐞 Describe the Bug
If you do `{{#if has-block}}` its accepted but doesnt work. This condition is always false. You have to do `{{#if (has-block)}}`

### 🔬 Minimal Reproduction
https://ember-twiddle.com/3a241109e750e32ea2e639063e71c81d?openFiles=templates.application%5C.hbs%2C

### 😕 Actual Behavior
`{{#if has-block}}` is always false and is accepted code

### 🤔 Expected Behavior
Either that the template compilation fails or that you can have a `ember-template-lint` rule to make this an error/warning

**Comment by bertdeblock** [comment]
@emattias Which `ember-source` version are you using? 
Starting from v3.26, `{{#if has-block}}` should trigger the `this-property-fallback` deprecation.
Starting from v4, `{{#if has-block}}` should throw.

**Comment by emattias** [comment]
We are running `3.28.8` and this doesnt trigger `this-property-fallback` when I run `ember-template-lint` :/

**Comment by bertdeblock** [comment]
The deprecation should be logged in your browser's console.

**Comment by emattias** [comment]
> The deprecation should be logged in your browser's console.

Aha ok, I would prefer if it could be done by the linter so you can block merging of this code that breaks the logic

> Starting from v4, {{#if has-block}} should throw.

Are you saying that from v4  just `{{#if has-block}}` without parentheses will throw or `{{#if (has-block)}}` also?

**Comment by bertdeblock** [comment]
I think you will need to update the `no-implicit-this` rule for that, because at the moment it seems to [ignore `has-block`](https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/rules/no-implicit-this.js#L33).

Only `{{#if has-block}}` will throw in v4, `{{#if (has-block)}}` is okay.

**Comment by emattias** [comment]
Ok, since this is fixed in latest ember version I guess this can be closed?

**Comment by bertdeblock** [comment]
I think so yes, though I'm wondering if the `no-implicit-this` rule should updated over in `ember-template-lint`.
If `{{#if has-block}}` doesn't work, I would expect for it to be flagged by the rule.

**Comment by emattias** [comment]
Close in favor of https://github.com/ember-template-lint/ember-template-lint/issues/2470
