### ISSUE TITLE
Ember.js 3.28 and class based template compilation deprecation

### ISSUE THREAD

**Issue by vmoglan** [emberjs/ember.js#20069]
We're upgrading Ember.js from version 3.16 to version 3.28. We're getting an error that looks like:

> Using class based template compilation plugins is deprecated, please update to the functional style

I found [this section](https://deprecations.emberjs.com/v3.x/#toc_template-compiler-registerPlugin) on the deprecations web page, but it doesn't give more information. Any idea what this could mean? When I'm running `ember test`, the output is flooded with it, can barely read anything. Thank you.

**Comment by bertdeblock** [comment]
Normally that message should contain the name of the plugin.

E.g.:
```
DEPRECATION: Using class based template compilation plugins is deprecated, please update to the functional style: SetTransform [deprecation id: template-compiler.registerPlugin]
```

`SetTransform` here is the name of the plugin. What name do you have?

**Comment by vmoglan** [comment]
It's `RemoveConfigurationHtmlCommentsPlugin` for me.

**Comment by bertdeblock** [comment]
That one seems to come from `ember-cli-template-lint`.

You can always use Ember Observer's code search to find things like this:
https://emberobserver.com/code-search?codeQuery=RemoveConfigurationHtmlCommentsPlugin.

The solution here would be to remove `ember-cli-template-lint` and use `ember-template-lint` directly instead.
`ember-cli-template-lint` is deprecated and won't be updated to fix this.

But if you are updating via `ember-cli-update`, normally this should've been taken care of via blueprint updates.

**Comment by vmoglan** [comment]
I really appreciate the effort and I'm sure it will help other confused Ember newbies like me. I will close this issue since I restarted the upgrade process from scratch and didn't come across it anymore. 

Thanks a lot!
