### ISSUE TITLE
[Bug] Ember 3.28 upgrade - yarn test fails with "registerPlugin is deprecated, please pass plugins directly via compile and/or precompile"

### ISSUE THREAD

**Issue by vmoglan** [emberjs/ember.js#20067]
### 🐞 Describe the Bug
We are updating our app from 3.16 to the latest Ember.js LTS release, which seems to be v3.28. I ran the `ember-update-cli` as such:

```
ember-update-cli --to 3.28
```

Everything seemed to be fined, solved the merge conflicts. When running `yarn test` though, the command fails with:

> registerPlugin is deprecated, please pass plugins directly via `compile` and/or `precompile`. Stack Trace and Error Report: C:\Users\<usr>\AppData\Local\Temp/error.dump.7c3a70346331923d26d407566300fdab.log

<details>
  <summary>
    Error report
  </summary>
ENV Summary:

  TIME: Wed Apr 27 2022 13:23:54 GMT+0200 (Central European Summer Time)
  TITLE: ember
  ARGV:
  - C:\Program Files\nodejs\node.exe
  - C:\Users\<usr>\source\repos\<project>\node_modules\ember-cli\bin\ember
  - test
  EXEC_PATH: C:\Program Files\nodejs\node.exe
  TMPDIR: C:\Users\<usr>\AppData\Local\Temp
  SHELL: null
  PATH:
  - C
  - \Users\<usr>\AppData\Local\Temp\yarn--1651058544869-0.3749358684759947;C
  - \Users\<usr>\source\repos\<project>l\node_modules\.bin;C
  - \Users\<usr>\AppData\Local\Yarn\Data\link\node_modules\.bin;C
  - \Users\<usr>\AppData\Local\Yarn\bin;C
  - \Program Files\libexec\lib\node_modules\npm\bin\node-gyp-bin;C
  - \Program Files\lib\node_modules\npm\bin\node-gyp-bin;C
  - \Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C
  - \Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin;C
  - \Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C
  - \Python310\Scripts\;C
  - \Python310\;C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0\;C
  - \WINDOWS\System32\OpenSSH\;C
  - \Program Files\1E\Client\Extensibility\NomadBranch;C
  - \Program Files\Microsoft SQL Server\150\Tools\Binn\;C
  - \Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C
  - \Program Files\dotnet\;C
  - \ProgramData\chocolatey\bin;C
  - \Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C
  - \Program Files\Microsoft SQL Server\150\DTS\Binn\;C
  - \Program Files (x86)\Red Gate\SQL Compare 14;C
  - \Program Files\Microsoft\Azure Functions Core Tools\;C
  - \Program Files\nodejs\;C
  - \Users\<usr>\AppData\Local\Microsoft\WindowsApps;C
  - \Users\<usr>\AppData\Local\Programs\Microsoft VS Code\bin;C
  - \Users\<usr>\AppData\Local\Programs\Git\cmd;C
  - \Users\<usr>\.dotnet\tools;C
  - \Users\<usr>\AppData\Local\Programs\Azure Data Studio\bin;C
  - \Users\<usr>\DotNetVersions;C
  - \Users\<usr>\AppData\Roaming\npm
  PLATFORM: win32 x64
  FREEMEM: 17523884032
  TOTALMEM: 34121031680
  UPTIME: 14697
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz - 2712
  - Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz - 2712
  - Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz - 2712
  - Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz - 2712
  - Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz - 2712
  - Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz - 2712
  - Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz - 2712
  - Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz - 2712
  - Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz - 2712
  - Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz - 2712
  - Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz - 2712
  - Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz - 2712
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.18.1
  - brotli: 1.0.9
  - cldr: 40.0
  - icu: 70.1
  - llhttp: 2.1.4
  - modules: 83
  - napi: 8
  - nghttp2: 1.42.0
  - node: 14.19.1
  - openssl: 1.1.1n
  - tz: 2021a3
  - unicode: 14.0
  - uv: 1.42.0
  - v8: 8.4.371.23-node.85
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: registerPlugin is deprecated, please pass plugins directly via `compile` and/or `precompile`.
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: registerPlugin is deprecated, please pass plugins directly via `compile` and/or `precompile`.
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: registerPlugin is deprecated, please pass plugins directly via `compile` and/or `precompile`.
    at raiseOnDeprecation (C:\Users\<usr>\source\repos\<project>\node_modules\ember-source\dist\ember-template-compiler.js:2009:15)
    at HANDLERS.<computed> (C:\Users\<usr>\source\repos\<project>l\node_modules\ember-source\dist\ember-template-compiler.js:2117:9)
    at invoke (C:\Users\<usr>\source\repos\<project>l\node_modules\ember-source\dist\ember-template-compiler.js:2129:9)
    at deprecate (C:\Users\<usr>\source\repos\<project>\node_modules\ember-source\dist\ember-template-compiler.js:2085:28)
    at TemplateCompiler.registerPlugin (C:\Users\<usr>\source\repos\<project>\node_modules\ember-source\dist\ember-template-compiler.js:20535:47)
    at TemplateCompiler.registerPlugins (C:\Users\<usr>\source\repos\<project>\node_modules\ember-composability-tools\node_modules\ember-cli-htmlbars\index.js:63:16)
    at new TemplateCompiler (C:\Users\<usr>\source\repos\<project>\node_modules\ember-composability-tools\node_modules\ember-cli-htmlbars\index.js:42:10)
    at Object.toTree (C:\Users\<usr>\source\repos\<project>\node_modules\ember-composability-tools\node_modules\ember-cli-htmlbars\ember-addon-main.js:47:16)
    at C:\Users\<usr>\source\repos\<project>\node_modules\ember-cli-preprocess-registry\preprocessors.js:188:26
    at Array.forEach (<anonymous>)
    at processPlugins (C:\Users\<usr>\source\repos\<project>\node_modules\ember-cli-preprocess-registry\preprocessors.js:186:11)
    at module.exports.preprocessTemplates (C:\Users\<usr>\source\repos\<project>\node_modules\ember-cli-preprocess-registry\preprocessors.js:169:10)
    at Class.compileTemplates (C:\Users\<usr>\source\repos\<project>\node_modules\ember-cli\lib\models\addon.js:1138:35)
    at Class.compileAddon (C:\Users\<usr>\source\repos\<project>\node_modules\ember-cli\lib\models\addon.js:1200:42)
    at Class.treeForAddon (C:\Users\<usr>\source\repos\<project>\node_modules\ember-cli\lib\models\addon.js:856:26)
    at Class._treeFor (C:\Users\<usr>\source\repos\<project>\node_modules\ember-cli\lib\models\addon.js:668:33)
</details>

Tried to google this issue and I found some mentions here and there but I did not understand the solutions. 

### 😕 Actual Behavior

`yarn test` fails after update to latest LTS with "registerPlugin is deprecated, please pass plugins directly via `compile` and/or `precompile`."

### 🤔 Expected Behavior
Not fail.

### 🌍 Environment

- Ember: - 3.28
- Node.js/npm: - v14, but also failed on latest LTS v16
- OS: - Windows 10 64bit
- Browser: - N/A

### ➕ Additional Context
<details>
    <summary>Additional warnings after the upgrade</summary>

WARNING: [DEPRECATION] [DEPRECATION] Usage of the Ember Global is deprecated. You should import the Ember module or the specific API instead.

See https://deprecations.emberjs.com/v3.x/#toc_ember-global for details.

Usages of the Ember Global may be caused by an outdated ember-cli-babel dependency. The following steps may help:

* Upgrade the following addons to the latest version:
  * ember-cli-mirage
  * ember-cli-app-version
  * ember-cli-file-saver
  * moment
  * ember-moment
  * ember-cli-string-helpers
  * ember-concurrency
  * ember-leaflet
  * ember-power-select
  * ember-power-select-with-create
  * ember-radio-button
  * ember-responsive
  * ember-route-action-helper
  * ember-truth-helpers
  * ember-concurrency-test-waiter
  * ember-tooltips
  * ember-wormhole

### Important ###

In order to avoid repeatedly showing the same deprecation messages, no further deprecation messages will be shown for usages of the Ember Global until ember-cli-babel is upgraded to v7.26.6 or above.

To see all instances of this deprecation message, set the `EMBER_GLOBAL_DEPRECATIONS` environment variable to "all", e.g. `EMBER_GLOBAL_DEPRECATIONS=all ember test`.

### Details ###

Prior to v7.26.6, ember-cli-babel sometimes transpiled imports into the equivalent Ember Global API, potentially triggering this deprecation message indirectly, even when you did not observe these deprecated usages in your code.

The following outdated versions are found in your project:

* ember-cli-babel@6.18.0, currently used by:
  * ember-assign-polyfill@2.6.0 (Dormant)
    * Depends on ember-cli-babel@^6.16.0
    * Added by ember-qunit@4.6.0 > @ember/test-helpers@1.7.1
  * ember-auto-import@1.5.3 (Dormant)
    * Depends on ember-cli-babel@^6.6.0
    * Added by ember-cli-mirage@1.1.4
  * ember-cli-app-version@3.2.0
    * Depends on ember-cli-babel@^6.12.0
  * ember-cli-code-coverage@0.4.2 (Dormant)
    * Depends on ember-cli-babel@^6.8.2
  * ember-cli-file-saver@1.2.4
    * Depends on ember-cli-babel@^6.3.0
  * ember-cli-string-helpers@1.10.0
    * Depends on ember-cli-babel@^6.6.0
  * ember-cli-test-loader@2.2.0 (Dormant)
    * Depends on ember-cli-babel@^6.8.1
    * Added by ember-qunit@4.6.0
  * ember-concurrency-test-waiter@0.3.1
    * Depends on ember-cli-babel@^6.6.0
  * ember-concurrency@1.0.0
    * Depends on ember-cli-babel@^6.8.2
    * Added by ember-power-select@2.3.5
    * Added by ember-power-select-with-create@0.6.2 > ember-power-select@2.3.5
  * ember-get-config@0.2.4
    * Depends on ember-cli-babel@^6.3.0
    * Added by ember-cli-mirage@1.1.4
    * Added by ember-leaflet@4.1.1
    * Added by ember-tooltips@3.4.0
  * ember-inflector@3.0.1
    * Depends on ember-cli-babel@^6.6.0
    * Added by ember-cli-mirage@1.1.4
  * ember-invoke-action@1.5.1
    * Depends on ember-cli-babel@^6.6.0
    * Added by ember-leaflet@4.1.1
  * ember-let-polyfill@0.1.0 (Dormant)
    * Depends on ember-cli-babel@^6.16.0
    * Added by ember-leaflet@4.1.1
  * ember-macro-helpers@2.2.0
    * Depends on ember-cli-babel@^6.18.0
    * Added by ember-moment@7.8.1
  * ember-maybe-import-regenerator@0.1.6 (Dormant)
    * Depends on ember-cli-babel@^6.0.0-beta.4
    * Added by ember-concurrency@1.0.0
    * Added by ember-power-select@2.3.5 > ember-concurrency@1.0.0
    * Added by ember-power-select-with-create@0.6.2 > ember-power-select@2.3.5 > ember-concurrency@1.0.0
  * ember-moment@7.8.1
    * Depends on ember-cli-babel@^6.7.2
  * ember-radio-button@2.0.1
    * Depends on ember-cli-babel@^6.9.2
  * ember-responsive@3.0.5
    * Depends on ember-cli-babel@^6.6.0
  * ember-route-action-helper@2.0.7
    * Depends on ember-cli-babel@^6.8.1
  * ember-truth-helpers@2.1.0
    * Depends on ember-cli-babel@^6.6.0
    * Added by ember-power-select@2.3.5
    * Added by ember-power-select-with-create@0.6.2 > ember-power-select@2.3.5
  * ember-weakmap@3.3.2 (Dormant)
    * Depends on ember-cli-babel@^6.6.0
    * Added by ember-moment@7.8.1 > ember-macro-helpers@2.2.0
  * ember-wormhole@0.5.5
    * Depends on ember-cli-babel@^6.10.0
    * Added by ember-tooltips@3.4.0
  * moment@3.7.1
    * Depends on ember-cli-babel@^6.6.0

Note: Addons marked as "Dormant" does not appear to have any JavaScript files. Therefore, even if they are using an old version ember-cli-babel, they are unlikely to be the culprit of this deprecation and can likely be ignored.

WARNING: Setting the `jquery-integration` optional feature flag to `true`, or not providing a setting at all, has been deprecated. You must add the `@ember/optional-features` addon and set this feature to `false`. This warning will become an error in Ember 4.0.0.

For more information, see the deprecation guide: https://deprecations.emberjs.com/v3.x/#toc_optional-feature-jquery-integration
WARNING: Internet Explorer 11 is listed in your compilation targets, but it will no longer be supported in the next major version of Ember. Please update your targets to remove IE 11 and include new targets that are within the updated support policy. For details on the new browser support policy, see:

 - The official documentation: http://emberjs.com/browser-support
 - the deprecation guide: https://deprecations.emberjs.com/v3.x#toc_3-0-browser-support-policy

</details>

**Comment by bertdeblock** [comment]
Any change you have `RAISE_ON_DEPRECATION` set to `true` somewhere?

**Comment by vmoglan** [comment]
Hi, found this `environment.js` file which contains:

```js
ENV.EmberENV.RAISE_ON_DEPRECATION = true;
```

I'm mainly a .NET developer, so I'm not exactly sure what the implications of settings this to false are. Also, I tried updating the dependencies that ember was saying were deprecated and at least got the thing to build, even if tests are failing because of rule failures. Looks good, but I'm afraid updating those dependencies could also cause problems that are hidden to me know...

**Comment by vmoglan** [comment]
Seems so, after updating all the aforementioned addons it went away. Thanks a lot for the help!
