### ISSUE TITLE
Bug.ember.js

### ISSUE THREAD

**Issue by AriesTriputranto9** [emberjs/ember.js#20083]
### 📙 Describe the Issue
A clear and concise description of what the issue is.

### 🔬 Minimal Reproduction
Please, share a link to the page with the documentation and share steps to reproduce.

### 😕 Actual Behavior
A clear and concise description of what is happening.

**Comment by MelSumner** [comment]
Unsure what the issue is, please re-open with more details if this is a problem. For now, I'm closing the issue since it is essentially blank. Thank you!
