### ISSUE TITLE
Reactivity: resources

### ISSUE THREAD

**Issue by wycats** [emberjs/ember.js#20096]
Currently being explored (API and design) by @NullVoxPopuli and @wycats via https://github.com/NullVoxPopuli/ember-resources 

There's a design sketch for some of the ideas at https://wycats.github.io/polaris-sketchwork/reactivity.html with some supporting information at https://wycats.github.io/polaris-sketchwork/match.html

**Comment by wycats** [comment]
@wycats is working (with @NullVoxPopuli) on a design that includes something like Resource Manager (this defines "resource constructor", which is used in https://github.com/emberjs/ember.js/issues/20095)

**Comment by knownasilya** [comment]
Is this being resolved with starbeam? Or is ember-resources still the plan (with starbeam underneath maybe)? @wycats

**Comment by ef4** [comment]
One near-term step to make progress here is to do a minimum viable integration for starbeam in ember. @NullVoxPopuli has said he's interested in working on that in the post-emberconf timeframe.

**Comment by kategengler** [comment]
Closing in favor of https://github.com/emberjs/tracking-polaris/issues/31
