### ISSUE TITLE
[Bug] Bug report

{ "scripts": { "precompress": "{{ executes BEFORE the `compress` script }}", "compress": "{{ run command to compress files }}", "postcompress": "{{ executes AFTER `compress` script }}" } }

### ISSUE THREAD

**Issue by AriesTriputranto9** [emberjs/ember.js#20093]
### 🔬 Minimal Reproduction
Describe steps to reproduce. If possible, please, share a link with a minimal reproduction.

### 😕 Actual Behavior
A clear and concise description of what is happening.

### 🌍 Environment

- Ember: -
- Node.js/npm: -
- OS: -
- Browser: -

**Comment by MelSumner** [comment]
Closing this issue because it has no details. Please re-open with details in the issue if you feel as though this is still relevant. Thank you!
