### ISSUE TITLE
[Bug] app booting multiple times following a live reload

### ISSUE THREAD

**Issue by roomman** [emberjs/ember.js#20111]
### 🐞 Describe the Bug
`Error: Assertion Failed: You cannot use the same root element (body) multiple times in an Ember.Application` is appearing in my console, after a live reload.

### 🔬 Minimal Reproduction
* Run `ember s` to launch app.
* Open inspector (Safari and/or Chrome).
* Refresh page and check console for errors.
* Make random change to template and save.
* Wait for live reload and check console for errors.

### 😕 Actual Behavior
After a manual page refresh there are no errors. After a live reload `Error: Assertion Failed: You cannot use the same root element (body) multiple times in an Ember.Application` is shown.

### 🤔 Expected Behavior
No errors in console.

### 🌍 Environment

- Ember: 4.4.0
- Node.js/npm: 16.13.2/8.4.1
- OS: Mac OSX
- Browser: Safari / Chrome, latest releases

### ➕ Additional Context
The error is preventing updates being rendered. As a result, I need to re-run `ember s` after each change is saved.

**Comment by bertdeblock** [comment]
@roomman Are you using Embroider? If so, you might be running into https://github.com/embroider-build/embroider/issues/1211

**Comment by roomman** [comment]
> @roomman Are you using Embroider?

Yes I am, thanks @bertdeblock, will close this down and roll back Embroider now. Many thanks!
