### ISSUE TITLE
[Bug] invokeHelper does not allow destruction (related to Polaris)

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember.js#20123]
cc @wycats for vis -- reconciling Polaris sketchbook ergonomics with Ember APIs :sweat_smile: 

### 🐞 Describe the Bug

when using invokeHelper there is no way to trigger the `hasDestoryable` behavior of a helper.

### 🔬 Minimal Reproduction

1. clone https://github.com/NullVoxPopuli/helper-destroyable-test
2. pnpm install
3. pnpm start
4. open browser console
5. click the toggle button a few times

### 😕 Actual Behavior

destruction never occurs

### 🤔 Expected Behavior

destruction would happen, and `destroying` is printed in the demo

### 🌍 Environment

- Ember: - 4.5
- Node.js/npm: - 16.x.y
- OS: - Ubuntu
- Browser: - Firefox

### ➕ Additional Context

This is related to Resources, and I think we may need to solve this for Polaris

Why is this needed though? Resources are "helpers with destruction" and provide their own helper manager, right?

Well, a common way (we think) folks will want to use resources, is to compose them with regular functions -- wrapping in some setup or state that lives outside of the resource itself.

For example
```js
import { resource } from "ember-resources/util/function-resource";

function cell {
  // ... snip
}

function RemoteData(url) {
  return Resource((resource) => {
    const value = cell({ type: "loading" });
    const controller = new AbortController();

    resource.on.cleanup(() => controller.abort());

    fetch(url, { signal: controller.signal })
      .then((response) => {
        if (response.ok) {
          return response.json();
        } else {
          value.current = { type: "error", value: response.statusText };
        }
      })
      .then((data) => {
        value.current = { type: "success", value: data };
      });

    return valu;
  });
}
}
```
A similar example can be found in the Polaris sketchbook: https://wycats.github.io/polaris-sketchwork/reactivity.html#example

atm, when using this in a template, it's most ergonomic to immediately invokeHelper on the Resource
via something like this (after registering the above function with this manager): 
```ts
class ResourceInvokerManager {
  capabilities = helperCapabilities('3.23', {
    hasValue: true,
    hasDestroyable: true,
  });

  constructor(protected owner: unknown) {}

  createHelper(fn: ResourceFactory, args: any): Cache {
    let thisFn = fn.bind(null);

    // return { fn: thisFn, args };
    let helper: object;

    let cache: Cache = createCache(() => {
      let result;

      if (helper === undefined) {
        helper = thisFn(...args.positional) as object;
        result = invokeHelper(this, helper);

        associateDestroyableChild(cache, helper);
      }

      return getValue(result);
    });

    return cache;
  }

  getValue(cache: Cache) {
    return getValue(cache);
  }

  getDestroyable(cache: Cache) {
    return cache;
  }
}
```

but `getDestroyable` is never called.

## An alternative

One way we could ave this problem, is to push complexity on to the consuming API by way of using the newly landed default Helper Manager.
```hbs
{{#let (RemoteData @url) as |theResource|}}
  {{#let (theResource) as |state|}}
    now the returned data can be used
  {{/let}}
{{/let}}
```

but this isn't great, because we have to invoke two function for every resource that is used like this.

What would be great, is if we had some way of _automatically_ invoking the resource and hooking up all the lifecycle bits of it.

in the Polaris sketchbook, `@use` is proposed as a way to wire in the reactivity, and a "framework" stuff for the what would otherwise be "just another function".

However, `@use` has no way to tie in destruction when a resource is no longer used.

This could be intentional if it were the only problem, but! in testing, it appears that `clearRender` and _destruction of the test as a whole_, also do not trigger destruction (because invokeHelper has no way to associateDestroyableChild to the parent object).

## Another alternative (likely what is unblocking in Ember today)

The `ResourceInvokerManager` will probably need to inline all the same manager code for the Resource in itself, and avoid the use if invokeHelper entirely.

## What could be ideal

Given the above RemoteData resource (without `@use`, because `<template>` enables non-class based usage), it'd be great to 
```hbs
{{#let (RemoteData "some url") as |state|}} <- resource is immediately invoked in here
  {{state.value}}
  {{state.type}}
{{/let}}
```

I don't know if this means that starbeam's proposed "Cell" needs to work slightly differently than how data is read in Ember, or? :shrug: 

But also, I can just double up on on the resource manager responsibilities -- even if, implementation wise, it's a bit messy

## However, I don't know if this is actually possible

Given this example:
https://wycats.github.io/polaris-sketchwork/reactivity.html#example

and how it's used in the templates -- idk if template-based destruction is possible.

It seems that final destruction would have to occur when the component is destroyed -- which is totally fine -- I think we'd just want to like... decide that. 

## Additional additional context:

I found this while trying to fix some cleanup / destruction stuff with the function-based `resource` , here: https://github.com/NullVoxPopuli/ember-resources/pull/531/files#diff-9844b112ac42413c48fa38f90efea1a9f7e172ae6a2874bee574461048d1ce47R266

in the linked line, `destroy 7` is never called, because of the current invokeHelper usage.
(which I'm going to look at maybe conditionally avoiding invokeHelper for `@use` in the short-term)

**Comment by NullVoxPopuli** [comment]
Confirming that component destruction destroys the helper:

![image](https://user-images.githubusercontent.com/199018/174138825-a701be5a-f353-4cca-8d29-e2867556aa9b.png)

(update repro)

**Comment by NullVoxPopuli** [comment]
Ok, so no more issue with invokeHelper -- i understand what it's doing now. :partying_face: 
(thanks for the discussions, @ef4)

**Comment by NullVoxPopuli** [comment]
Gonna close for now -- I think my issue is now just with my own implementation of things

**Comment by wycats** [comment]
@NullVoxPopuli Thanks for the documentation of your thoughts 😄
