### ISSUE TITLE
Add public import for `uniqueId` helper

### ISSUE THREAD

**Issue by chriskrycho** [emberjs/ember.js#20165]
This landed as available via string resolution at `unique-id` but did not come with a public import, meaning it doesn't currently work in `<template>`/strict mode. Per discussion at the Framework team meeting a few weeks ago, it should be exported from `@ember/helper`, the same as the other public helpers which are not built-ins (`hash`, `array`, `concat`, `get`, and `fn` etc.).

It needs two things to be public:

- [ ] #20171
- [ ] A note in the blog post for that release (which should be 4.8).

Additionally, we'll want to update ecosystem support for it:

- [x] add it to [the list of allowed built-ins](https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/rules/no-curly-component-invocation.js#L14) for the `no-curly-component-invocation` rule in `ember-template-lint`
    - ember-template-lint/ember-template-lint#2592
    - ember-template-lint/ember-template-lint#2593

**Comment by geneukum** [comment]
I should be able to take a look at this within a day or two. Should we also add it to the [list of 'allowed' built-ins](https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/rules/no-curly-component-invocation.js#L14) for the no-curly-component-invocation ember-template-lint rule?

**Comment by chriskrycho** [comment]
@geneukum good call. Let me add that to the list of tasks – and also, a colleague mentioned to me late Friday that he’s also interested in helping; let's coordinate efforts in [#dev-ember-js on Discord](https://discord.com/channels/480462759797063690/485447409296736276)!

**Comment by geneukum** [comment]
I've opened up the issue: https://github.com/ember-template-lint/ember-template-lint/issues/2592 and PR: https://github.com/ember-template-lint/ember-template-lint/pull/2593 to hopefully get the ember-template-lint part of this handled.

**Comment by TechieQian** [comment]
That colleague is me! That discord channel link doesn't seem to work.

**Comment by oscareng** [comment]
does this issue still need fixing?
