### ISSUE TITLE
Follow-up Notes from #20092

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember.js#20163]
We should probably track these differently, but something is better than nothing!

## Revisit -internal re-exports from public packages
* https://github.com/emberjs/ember.js/pull/20092#discussion_r875297739
* https://github.com/emberjs/ember.js/pull/20092#discussion_r875297773

## Maybe import from public RSVP
* https://github.com/emberjs/ember.js/pull/20092#discussion_r953105148

## Organize imports
* https://github.com/emberjs/ember.js/pull/20092#discussion_r953139613

## Clean up export
* https://github.com/emberjs/ember.js/pull/20092#discussion_r953229168

## Interface merging
* https://github.com/emberjs/ember.js/pull/20092#discussion_r953295940

**Comment by locks** [comment]
All listed PRs are merged!
