### ISSUE TITLE
`{{action}}` used as a modifier does not trigger on components

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember.js#20178]
https://github.com/emberjs/ember.js/blob/bbe46ef4b98a37d01b81923be1a81cc9477017ab/packages/%40ember/-internals/views/lib/system/event_dispatcher.ts#L330-L345

The old jQuery version would trigger both on the component and then the action handler.

**Comment by chriskrycho** [comment]
Granting the report (I haven't dug in)—with jQuery integration removed, Ember 3.28 nearing end of LTS, and the ability to swap over to using `{{on}}` instead, I think this is likely in the "Bug, *won't fix*" category, right?

**Comment by wagenet** [comment]
If action can still be used as a modifier in 4.x then this is an active bug.

**Comment by chriskrycho** [comment]
Hmm, maybe? It absolutely can be used that way (though we should deprecate it!), but it's not clear to me that we have to match the jQuery-based semantics. I'm not opposed to fixing it in the meantime, just noting that "change in behavior from jQuery version" isn't a slam dunk must-fix behavior, when there are other things we might spend that time on instead!

Can you show the invocation code that would trigger the issue? I assume it's something like `{{action "foo" on="click"}}`?

**Comment by wagenet** [comment]
I chatted with @chriskrycho out of band and I think I'm prepared to say we're not likely to fix this. I'm going to go ahead and close it. If anyone else encounters this issue and thinks we should do something about it, please let me know.
