### ISSUE TITLE
Enable `EMBER_TYPESCRIPT_BLUEPRINTS` feature

### ISSUE THREAD

**Issue by bertdeblock** [emberjs/ember.js#20177]
Currently, this feature is [turned off](https://github.com/emberjs/ember.js/blob/master/blueprints/-maybe-polyfill-typescript-blueprints.js#L2) and users need to explicitly run `EMBER_TYPESCRIPT_BLUEPRINTS=true ember g ...` to generate TS files. This can be confusing when people also set `"isTypeScriptProject": true` in their `.ember-cli` file.
This issue serves as a reminder to enable this feature or to determine what's needed to enable it.

/cc @chriskrycho

**Comment by chriskrycho** [comment]
@bertdeblock is this still the case? I don't remember where this landed!

**Comment by bertdeblock** [comment]
@chriskrycho Yup, to enable them by default we need to [enable this flag](https://github.com/emberjs/ember.js/blob/master/blueprints/-maybe-polyfill-typescript-blueprints.js#L2).

**Comment by chriskrycho** [comment]
Thanks for clarifying. Do you happen to know if that's the *only* thing we're blocked on (you've been way more closely involved in the implementation than I have 🙏🏼😅)? If so, I'll bring it up at the next Framework meeting as well as discuss it async with the Typed Ember team and we can see about a path to turning on that flag!

**Comment by bertdeblock** [comment]
AFAIK, that's the only remaining thing to do, to have TS blueprints just work indeed.
