### ISSUE TITLE
Documentation of dreprecations is missing since ember 4.1

### ISSUE THREAD

**Issue by Timbuktu1982** [emberjs/ember.js#20198]
Hey there,

https://deprecations.emberjs.com/ is very useful, but deprecations since ember 4.1 are not described. Gives another source for deprecations of ember now?

Thank you

**Comment by bertdeblock** [comment]
AFAICT, there haven't been any new deprecations since v4.1.0.

**Comment by Timbuktu1982** [comment]
Hi Bert,
thank you.
