### ISSUE TITLE
[Bug] Build error enabling Octane Edition on Ember 3.14

### ISSUE THREAD

**Issue by xtagon** [emberjs/ember.js#20225]
### 🐞 Describe the Bug

When attempting to update my Ember 3.14 application to 3.15, or alternatively simply enabling the Octane preview on 3.14 before doing any 3.15 update, `ember start` shows the following error:

```
Build Error (broccoli-persistent-filter:Babel > [Babel: @glimmer/component]) in @glimmer/component/index.ts

/home/user/my-ember-app/@glimmer/component/index.ts: Unexpected token (2:12)

  1 | import { DEBUG } from '@glimmer/env';
> 2 | import type ApplicationInstance from '@ember/application/instance';
    |             ^
  3 | import { setComponentManager } from '@ember/component';
  4 | import { gte } from 'ember-compatibility-helpers';
  5 | 
```

### 🔬 Minimal Reproduction

The steps I followed were the steps to enable Octane in this release log: https://blog.emberjs.com/ember-3-14-released/#toc_the-octane-preview-continued

I apologize for not having minimal steps to reproduce as the application itself is private, so I'm not sure if this is something that would be affected in a fresh application.

### 😕 Actual Behavior

The application throws the error describe above when booting

### 🤔 Expected Behavior

The application boots with Octane Edition enabled

### 🌍 Environment

- Ember: 3.14.1
- Node.js/npm: Node 12.22.8, npm 8.19.2
- OS: Ubuntu 20.04.5
- Browser: N/A

### ➕ Additional Context

- Error looks similar to (but not quite the same as) https://github.com/emberjs/ember.js/issues/18995
- My application does not use TypeScript directly (dependencies might). Not sure if this is relevant, but the error does come from a .ts file in Glimmer.

**Comment by chriskrycho** [comment]
Hmm, sorry you've hit this. That specific error looks wholly unrelated to the Octane edition itself—it's normally an indication you need to update your Babel config to a more recent version, but Glimmer itself *should* be built correctly so as not to have this issue. What version of `@glimmer/component` do you have in your app's dependencies?

**Comment by xtagon** [comment]
> What version of @glimmer/component do you have in your app's dependencies?

I was installing `@glimmer/component@^1.0.0-beta.1` as recommended in these release notes: https://blog.emberjs.com/ember-3-14-released/#toc_the-octane-preview-continued

**Comment by chriskrycho** [comment]
What version did that resolve in your lock file?

**Comment by xtagon** [comment]
Oh you're right I didn't notice it was pinned that way... resolved to 1.1.2

**Comment by tomwayson** [comment]
I had the same error upgrading from Ember 3.16.1 to ~3.20.0 and after seeing this I was able to resolve it w/:

```diff
-    "@glimmer/component": "^1.0.1",
 +   "@glimmer/component": "1.0.1",
```

**Comment by kategengler** [comment]
Closing -- this is quite a long time ago.
