### ISSUE TITLE
[Preview Types Bug] `map` on an `EmberArray` returns `EmberArray` but shouldn't

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#20230]
### 🐞 Describe the Bug
This applies for the preview-types from Ember 4.8.0.

### 🔬 Minimal Reproduction
```ts
const x: NativeArray<string> = A();
const y = x.map(z => z);
```

### 😕 Actual Behavior
`y` is typed as `NativeArray`.

### 🤔 Expected Behavior
`y` is typed as `Array`.

Note that this is true at runtime only for modern browsers. For old browsers, the current types are correct... see [here](https://github.com/emberjs/ember.js/blob/v4.8.0/packages/@ember/array/index.ts#L1941). In modern browsers, `map` comes from the browser. It returns a native JS array. Otherwise an Ember version of [map](https://github.com/emberjs/ember.js/blob/v4.8.0/packages/@ember/array/index.ts#L721) is used which actually returns an `EmberArray`. I believe that should be fixed and the types should be changed to return native JS arrays.

Same applies for `mapBy` (which uses `map`), `filter`, `filterBy` and perhaps others.

### 🌍 Environment

- Ember: - 4.8.0

cc @chriskrycho, @wagenet

**Comment by chriskrycho** [comment]
Thanks for filing this! I'll take a look next week. Our behavior here is… odd. It’s not actually obvious to me intuitively what we *should* do here, though something along the lines of [what @wagenet came up with here](https://github.com/emberjs/ember.js/blob/v4.8.0/packages/@ember/array/index.ts#L1912-L1915) is probably *actually* it.

**Comment by wagenet** [comment]
Turns out that I didn't actually omit enough stuff from that NativeArray interface. The actual list is pretty large.
