### ISSUE TITLE
Deprecate `inject` export from `@ember/service`

### ISSUE THREAD

**Issue by bertdeblock** [emberjs/ember.js#20262]
Since [Ember v4.1.0](https://github.com/emberjs/ember.js/blob/master/CHANGELOG.md#v410-december-28-2021), it's possible to use the `service` export coming from `@ember/service`.
This feature was suggested in [RFC 752](https://github.com/emberjs/rfcs/pull/752) and implemented in [PR 19776](https://github.com/emberjs/ember.js/pull/19776).
This means that, at some point, we can deprecate `inject` in favor of `service` as having two things to accomplish the same thing is redundant. This issue serves as a reminder to implement that deprecation.

**Comment by bertdeblock** [comment]
I'm guessing the main thing here is timing? The RFC states that the deprecation should be until v5, but introducing the deprecation too soon might be annoying for addons that want/need to support Ember versions older than v4.1?

**Comment by chriskrycho** [comment]
I can bring it up at a Framework meeting soon. I don’t think the timing issue should be a big deal: by the time 5.0 comes out 3.28 will no longer be an LTS, and in fact 4.4 will be nearing the end of its LTS.

**Comment by bertdeblock** [comment]
Great, feel free to ping me once discussed, I can do the implementation.
