### ISSUE TITLE
how to identify if same route is triggered, do refresh instead of transition 

### ISSUE THREAD

**Issue by praveeno** [emberjs/ember.js#20264]
I have additional logic in routeDIdtransition, to switch to ember container, from legacy pjax container,
but if ember already opened the same route previously, and I switch to pjax container and try to do transition to come back to ember, 
nothing is happening, and transition object also not indicating that this is a blank transition, 
so how to identify if its same route transition?

**Comment by chriskrycho** [comment]
Hi @praveeno – sorry about the delayed response. We don't use GitHub issues for general Q&A, only for bug reports, feature requests, etc. You might ask this on [the forum](http://discuss.emberjs.com/) or [in Discord](https://discord.gg/emberjs). And, as a tip, the API docs for [the Router service](https://api.emberjs.com/ember/release/classes/RouterService) may be helpful in understanding this part of the framework’s design. Good luck!
