### ISSUE TITLE
[Bug] ContainerDebugAdapter typedef is missing Ember Object import

### ISSUE THREAD

**Issue by bwbuchanan** [emberjs/ember.js#20320]
### 🐞 Describe the Bug
[ember-source/types/preview/@ember/debug/container-debug-adapter.d.ts](https://github.com/emberjs/ember.js/blob/master/types/preview/@ember/debug/container-debug-adapter.d.ts) appears to be missing this line:

`import Object from '@ember/object';`

As a result, ContainerDebugAdapter is incorrectly typed as inheriting from JavaScript's `Object` instead of `EmberObject`.

This is blocking https://github.com/ember-cli/ember-resolver/issues/795

### 🌍 Environment

- Ember: 4.9.2

**Comment by chriskrycho** [comment]
Thanks for the report! Should be resolved in a bit, and I'll publish the back-ports this afternoon or (more likely) tomorrow morning!

**Comment by chriskrycho** [comment]
Fix going out in the latest versions of LTS, stable, and beta (all just released)!
