### ISSUE TITLE
deprecation id: ember-string.add-packag does not go away when applying suggested fix

### ISSUE THREAD

**Issue by st-h** [emberjs/ember.js#20377]
### 🐞 Describe the Bug
After upgrading to 4.10 I am seeing thousands of deprecation messages
```
DEPRECATION: Importing from `@ember/string` without having the `@ember/string` package in your project is deprecated. Please add `@ember/string` to your `package.json [deprecation id: ember-string.add-package] This will be removed in ember-source 5.0.0. See https://deprecations.emberjs.com/v4.x/#toc_ember-string-add-package for more details.
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:16199:21)
        at HANDLERS.<computed> (http://localhost:4200/assets/vendor.js:16322:9)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16225:9)
        at HANDLERS.<computed> (http://localhost:4200/assets/vendor.js:16322:9)
        at invoke (http://localhost:4200/assets/vendor.js:16331:9)
        at deprecate (http://localhost:4200/assets/vendor.js:16298:28)
        at deprecateImportFromInternalString (http://localhost:4200/assets/vendor.js:27379:47)
        at Object.dasherize (http://localhost:4200/assets/vendor.js:27281:5)
        at normalizeModelName (http://localhost:4200/assets/vendor.js:78133:19)
```
However, I have `"@ember/string": "^3.0.1"` in `devDependencies` of my `package.json`.

After discussing this issue in discord, it seems that for some reason the ember implementation of the string functions is being invoked instead of the ones that are contained in @ember/string

There has been a comment, describing similar behaviour in another issue: https://github.com/emberjs/ember-string/issues/235#issuecomment-1061413761 
In my case I am seeing this issue in the browser, but not on the fastboot server

I have also opened an issue over at @ember/string: https://github.com/emberjs/ember-string/issues/370

However, it seems that it would also be necessary to fix the misleading deprecation message

### 🔬 Minimal Reproduction
Describe steps to reproduce. If possible, please, share a link with a minimal reproduction.
---

### 😕 Actual Behavior
Thousands of deprecation warnings are printed

### 🤔 Expected Behavior
When the fix described in the deprecation message is applied, thousands of deprecation warning would no longer be printed

### 🌍 Environment

- Ember: 4.10
- Node.js/npm: -
- OS: -
- Browser: -

**Comment by boris-petrov** [comment]
Any chance you've hit [this](https://github.com/emberjs/ember-classic-decorator/issues/107)?

**Comment by st-h** [comment]
> Any chance you've hit [this](https://github.com/emberjs/ember-classic-decorator/issues/107)?

I don't have `ember-classic-decorator` installed. I have `ember-decorators` installed though, in case that matters as well? Also, a lot of the traces seem to originate from ember data functions, so I do not think this is an issue with a single addon. There are traces from other addons as well. It looks like all of the addons call the deprecated ember string functions instead of the ones in @ember/string

**Comment by kategengler** [comment]
@st-h What version of `ember-data` are you using? `ember-data` itself was not using the correct external `@ember/string` until this issue was resolved recently https://github.com/emberjs/data/issues/8393

**Comment by st-h** [comment]
@st-h I am still on ember-data 4.6, because starting from 4.7 there has been a regression, which prevents me from upgrading. I just tried 4.11, but then I get an error when building the app. 

`@embroider/macros/runtime.js: @babel/template placeholder "SAMPLE_FEATURE_FLAG": Expected string substitutionError: @babel/template placeholder "SAMPLE_FEATURE_FLAG": Expected string substitution`

I'll try to see if I can get the upgrade to 4.11 working - hopefully the regression from 4.7 also is gone now. 

However, the stack trace do not only come from ember data.

**Comment by kategengler** [comment]
@st-h I mentioned in another issue you filed, but do you have `ember-resolver` v10.0 in your package.json? It is a version bump that would have come with the blueprint update to v4.10.

**Comment by st-h** [comment]
I tried with latest ember-data version, but the deprecations have not changed. I am still getting thousands of deprecations when rendering the app. Yes, resolver is at 10.0.

<img width="477" alt="Screenshot 2023-03-28 at 15 19 40" src="https://user-images.githubusercontent.com/5768353/228250447-ff1d467d-61bf-4802-9144-7104cc04c48c.png">

**Comment by kategengler** [comment]
@st-h You can use 5.0 today by pointing to the `alpha` tag on npm or by using the canary builds. Please try it, but I suspect it will not solve your problem and it will error instead looking for `@ember/string`.

**Comment by kategengler** [comment]
Closing as this is resolved with Ember v5
