### ISSUE TITLE
Canary ember-try scenarios fail "Count not find module `@ember/string`..."

### ISSUE THREAD

**Issue by kategengler** [emberjs/ember.js#20418]
On addons, and other projects that were generated with ember-cli older than 4.10 , canary scenarios have started failing with 

```
Global error: Uncaught Error: Could not find module `@ember/string` imported from `ember-resolver/resolvers/classic/index`
```

This is due to the removal of the deprecation on canary (will be 5.0) that would have said something about `@ember/string` now needs to be installed `npm install --save-dev @ember/string`. 

This error is unlikely to happen to projects upgrading with the blueprint to `v5.0` because the blueprint in `v4.10` and later includes `@ember/string`, so this is a problem **most likely to happen when bumping only `ember-source`, as happens with ember-try scenarios.** 

To fix the issue for ember-try scenarios, there are a few options:

A) Bump `ember-resolver` to version `10.0.0` and add `@ember/string` version `3.0.1` to your `devDependencies`.  It is unlikely, but your project may have other reasons you cannot yet bump to these versions, if so, follow option B.
B) Update the ember-canary scenario in your `config/ember-try.js` to be the following:
```
{
        name: 'ember-canary',
        npm: {
          devDependencies: {
            'ember-source': await getChannelURL('canary'),
            'ember-resolver': '10.0.0',
            '@ember/string': '3.0.1'
          },
        },
      },
```
Note as v5.0 moves to beta and to release you will similarly have to update the beta and release scenarios. 

C) Update the test app to the blueprint for `v4.10` or later

---

We want to improve the error that is seen when this happens. `ember-source` v5.0 and newer should error when used with `ember-resolver` earlier than v10.0. In the error, it should explain that `@ember/string` also needs to be added to `devDependencies`.

**Comment by Panman82** [comment]
That one was easy to figure out and fix, but I'm running into other weird errors with canary. Ex:

> Error: Attempted to load a component, but there wasn't a component manager associated with the definition.

https://github.com/froala/ember-froala-editor/actions/runs/4515459509/jobs/7952797449#step:5:45

**Comment by NullVoxPopuli** [comment]
@Panman82 that error usually has to do with a `<@dynamicReference>` or `{{dynamicReference}}` that is an Object, but Object's can't be rendered as components -- is something goofy happening in the templates with Objects?

**Comment by Panman82** [comment]
> @Panman82 that error usually has to do with a `<@dynamicReference>` or `{{dynamicReference}}` that is an Object, but Object's can't be rendered as components -- is something goofy happening in the templates with Objects?

I don't think anything out of the ordinary: https://github.com/froala/ember-froala-editor/blob/test-canary-channel/addon/components/froala-editor.hbs

**Comment by NullVoxPopuli** [comment]
is `@content` ever an object?

**Comment by Panman82** [comment]
@NullVoxPopuli `@content` is always a `SafeString` or `null`. https://github.com/froala/ember-froala-editor/blob/test-canary-channel/addon/components/froala-editor.js#L214-L219

**Comment by Panman82** [comment]
Alright, I took a fresh look after stepping away for a couple days and noticed that there is a [warning about the `ember-source` peer dep not being met](https://github.com/froala/ember-froala-editor/actions/runs/4556908179/jobs/8037889722#step:5:6);

> npm WARN @ember/render-modifiers@2.0.5 requires a peer of ember-source@^3.8 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

Since [canary is moving to v5](https://github.com/emberjs/ember.js/commit/7e482015b051240c3a7b791855c917ecdc3c8db3), I'm assuming that plays into this warning. While I did [change this addon's peer dep to be just `>=3.20.0`](https://github.com/froala/ember-froala-editor/pull/141/commits/2b5ce4f7d35877c1e54f2626b006485f301a0ef5), I'm wondering if the requirement from `render-modifiers` is holding it back from being installed/acceptable.?.

_PS. Let me know if we need to take this elsewhere, since it's not completely related to the OP._

**Comment by kategengler** [comment]
Closing since this was opened as a warning for a particular in-between time.
