### ISSUE TITLE
Ember 3.2.0  -  Are you using Ember Route Own Encode Method or Browser Encode Method for "Dynamic Segment Param" & "Query Param" ? 

### ISSUE THREAD

**Issue by vinothkumarkp** [emberjs/ember.js#20420]
If you use Ember Route Own Encode Method logic, how can we disable it in our side. Because we are not satisfied that you use for Encoder. You use "EncodeURI" instead of "EncodeURIComponent". We need only "EncodeURIComponent" for encoding dynamic segment param and query params. is it possible to override your logic ? any configuration there to restrict it ?

**Comment by vinothkumarkp** [comment]
Example dynamic segment : "first-product/Vinoth Kumar &searchFile=value.html". 

You encode it like this "first-product/Vinoth%20Kumar%20&searchFile=value.html". 

But we need mixed of encodeURI & encodeURIComponent result like this.

"first-product/Vinoth%20Kumar%20%26searchFile%3Dvalue.html"

**Comment by vinothkumarkp** [comment]
@wycats @brynary @topfunky @hassox

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. 

This seem like a question better suited for the forums:
https://discuss.emberjs.com/

By closing some old issues we reduce the list of open issues to a more manageable set. I hope you understand.
