### ISSUE TITLE
[Bug] Ember Canary and Ember Beta breaks build

### ISSUE THREAD

**Issue by BobrImperator** [emberjs/ember.js#20458]
🐞 Describe the Bug
Since few days ago I've noticed that `ember-simple-auth` started failing for these scenarios.
- `ember-canary``ember-source: 5.1.0-alpha.1.canary+4f8ae0`
- `ember-beta` `ember-source: 5.0.0-beta.3.beta+df58d914`

Likely related to similar problem like here: https://github.com/emberjs/ember.js/issues/20281

🔬 Minimal Reproduction
See the test suite over here: https://github.com/mainmatter/ember-simple-auth/pull/2556
Or https://github.com/mainmatter/ember-simple-auth/actions/runs/4938637079/jobs/8828777158

Running locally:
- `CI=false yarn workspace ember-simple-auth test:one ember-canary`

😕 Actual Behavior
Unchanged tests do not complete.

🤔 Expected Behavior
Canary shouldn't fail my tests.

🌍 Environment
Ember: ember-source: 5.1.0-alpha.1.canary+4f8ae0
Node.js/npm: 16.18.1
OS: -
Browser: -

**Comment by gilest** [comment]
@BobrImperator try removing IE 11 from your [test apps targets](https://github.com/mainmatter/ember-simple-auth/blob/master/packages/test-app/config/targets.js#L9-L14)

Reference: https://github.com/adopted-ember-addons/ember-file-upload/pull/941

**Comment by BobrImperator** [comment]
Thanks for the suggestion and also a PR :)
