### ISSUE TITLE
[Documentation] The 4.12 docs on `Disabling Prototype Extensions` are not updated according to `RFC: Deprecate array prototype extensions #848`

### ISSUE THREAD

**Issue by johanrd** [emberjs/ember.js#20465]
### 📙 Describe the Issue
The [4.12 docs on Disabling Prototype Extensions](https://guides.emberjs.com/v4.12.0/configuring-ember/disabling-prototype-extensions/) are not updated according to [RFC: Deprecate array prototype extensions #848](https://github.com/emberjs/rfcs/pull/848) 

### 🔬 Minimal Reproduction
[From the Ember 4.12.0 docs on Disabling Prototype Extensions](https://guides.emberjs.com/v4.12.0/configuring-ember/disabling-prototype-extensions/):
>By default, Ember.js will extend the prototypes of native JavaScript arrays to implement the Ember.Enumerable, Ember.MutableEnumerable, Ember.MutableArray and Ember.Array interfaces. This polyfills ECMAScript 5 array methods in browsers that do not implement them, adds convenience methods and properties to built-in arrays, and makes array mutations observable.

### 🤔 Expected Behavior
No longer mention that ember by default extends the prototypes of native JavaScript arrays to implement the Ember.Enumerable, Ember.MutableEnumerable, Ember.MutableArray and Ember.Array interfaces.

Perhaps also mention in [the docs of the MutableArray class](https://api.emberjs.com/ember/4.12.0/classes/MutableArray) that ember no longer has Array prototype extension enabled by default?

**Comment by kategengler** [comment]
This RFC has not yet been implemented. You can track progress here https://github.com/emberjs/rfcs/pull/1020
