### ISSUE TITLE
[Documentation] Mention `tracked-tools` in Autotracking Guide

### ISSUE THREAD

**Issue by ChaiWithJai** [emberjs/ember.js#20476]
### 📙 Describe the Issue
The Autotracking In-Depth Guides in the Ember documentation currently do not mention the usage of `tracked-tools` (https://github.com/tracked-tools). This library provides additional utilities for autotracking in Ember and could be beneficial to developers working with Ember's autotracking feature with composite data types (arrays and objects in particular).

### 🔬 Minimal Reproduction
1. Visit the Autotracking In-Depth Guides page: https://guides.emberjs.com/release/in-depth-topics/autotracking-in-depth/
2. Read through the guides. Read the section about tracking arrays and objects. There might be an opportunity to enhance the following copy "Instead, you can continue to use EmberArray, which will continue to work with tracking and will cause any dependencies that use it to invalidate correctly.".

### 😕 Actual Behavior
The current Ember guides do not reference or mention the use of `tracked-tools` in the context of autotracking, potentially leaving developers unaware of these additional, helpful utilities.

### 🤔 Expected Behavior
Should we mention `tracked-tools`? I realize this may be addressed when Polaris is released, however, its a common enough use case for folks new to Ember or new to Octane.

### ➕ Additional Context
`tracked-tools` is a library that provides additional utilities for autotracking in Ember. It is an important tool that can enhance the developer experience when working with autotracking, hence it would be beneficial for this tool to be included in the Ember documentation.

_Predominately written by ChatGPT, so pardon the tone._

**Comment by kategengler** [comment]
Hi, this is a good question. The guides are over in this repo https://github.com/ember-learn/guides-source

Would you mind opening the issue over there?

**Comment by ChaiWithJai** [comment]
OK, opened the issue in the correct place. Will close this out now. https://github.com/ember-learn/guides-source/issues/1936
