### ISSUE TITLE
[Bug] `createTemplateFactory` accepts an argument of a type that is not exported in the stable types

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#20488]
### 🐞 Describe the Bug
Pretty much what the title is.

### 🔬 Minimal Reproduction
Just use `createTemplateFactory`.

### 😕 Actual Behavior
No way to create a variable of that type to pass it to `createTemplateFactory`.

### 🤔 Expected Behavior
The type to be exported.

### 🌍 Environment

- Ember: 5.1.0
- Node.js/npm: 20.3.1/9.7.2
- OS: Linux
- Browser: N/A

cc @chriskrycho

**Comment by chriskrycho** [comment]
This is a private API, so the types to invoke it do not need to be named in the public types as far as I can tell. Is there some context where that is not true?

**Comment by boris-petrov** [comment]
I didn't know it's a private API. My use case is that I pre-compile some templates on the backend (using `precompile` from `ember-source/dist/ember-template-compiler.js`) and send them to the frontend at runtime. I then want to use these templates. How else would I do that apart from using `createTemplateFactory`?

**Comment by chriskrycho** [comment]
I am not entirely sure, and you may even need to go through the RFC cycle! But fair warning: that's the *opposite* direction from where the framework is moving. In any case, it is absolutely private API, so is out of scope in terms of treating it as a TS bug: the types are accurately representing the reality of the public API. As a workaround, you can of course type cast or write your own types for it.

**Comment by boris-petrov** [comment]
Could you elaborate on what you mean by "that's the opposite direction from where the framework is moving"? What direction is the framework moving towards that is incompatible with what I described?

**Comment by chancancode** [comment]
https://github.com/emberjs/rfcs/blob/master/text/0931-template-compiler-api.md

I think a couple of things,

1. Generally, shifting towards components (including template-only components) as the atomic unit for "a renderable thing", and phasing out standalone templates as a concept
2. Phasing out the low-level APIs in favor of those proposed in the RFC (which produces components, not standalone templates)

In the meantime you could probably try to compile your templates into opaque modules on the backend and load them as such in runtime? (As opposed to a particular type of value) That's probably the least "get your hands dirty" approach, but as Chris said if you want to stick with what you are already doing there isn't necessary anything stopping you just yet.

**Comment by NullVoxPopuli** [comment]
@boris-petrov not that it helps you _now_, but it's one of my goals to demonstrate dynamic-ESM building of components over at https://limber.glimdown.com/ so, it's possible you could eventually ship ESM modules to your app, rather than the compiled templates you are today (which would kind of make your frontend app work a bit like Vite (at a high level squinting conceptual level)).
(of course, I need to find some time to actually implement this, and I'm backed up atm)

**Comment by boris-petrov** [comment]
Thanks both of you for the answer!

@chancancode 
What do you mean by "components" and what is a "standalone template"? How is a "standalone template" different from a "template-only components"?

Also, what do you mean by "compile your templates into opaque modules"? Is it the same that @NullVoxPopuli means by "dynamic-ESM building of components"? How do I do these things, could any of you give a simple example?
