### ISSUE TITLE
TypeScript errors when `exactOptionalPropertyTypes` is enabled

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#20500]
### 🐞 Describe the Bug
Enabling `exactOptionalPropertyTypes` in `tsconfig.json` leads to a couple of errors:

```
node_modules/@glimmer/runtime/dist/types/lib/environment.d.ts:15:22 - error TS2420: Class 'EnvironmentImpl' incorrectly implements interface 'Environment'.
  Types of property 'debugRenderTree' are incompatible.
    Type 'DebugRenderTreeImpl<object> | undefined' is not assignable to type 'DebugRenderTree<object>'.
      Type 'undefined' is not assignable to type 'DebugRenderTree<object>'.

15 export declare class EnvironmentImpl implements Environment {
                        ~~~~~~~~~~~~~~~

node_modules/ember-source/node_modules/router_js/dist/modules/route-info.d.ts:71:22 - error TS2415: Class 'ResolvedRouteInfo<R>' incorrectly extends base class 'InternalRouteInfo<R>'.
  Types of property 'context' are incompatible.
    Type 'ModelFor<R> | undefined' is not assignable to type 'ModelFor<R> | PromiseLike<ModelFor<R>>'.
      Type 'undefined' is not assignable to type 'ModelFor<R> | PromiseLike<ModelFor<R>>'.

71 export declare class ResolvedRouteInfo<R extends Route> extends InternalRouteInfo<R> {
                        ~~~~~~~~~~~~~~~~~
```

### 🔬 Minimal Reproduction
[Repo](https://github.com/boris-petrov/ember-type-bugs).

Run `npm install` and then `./node_modules/.bin/tsc`.

### 😕 Actual Behavior
Type errors in `node_modules`.

### 🤔 Expected Behavior
No errors.

### 🌍 Environment

- Ember: 5.1.2
- Node.js/npm: 20.3.1/9.7.2
- OS: Linux
- Browser: N/A

cc @chriskrycho

**Comment by chriskrycho** [comment]
Hmm. I need to check whether we commit to supporting that flag—I do not think so, as it is intentionally excluded from the semver-ts spec, and is also not in `@tsconfig/ember`. I'm aware that you use it from previous discussions, but since we have not committed to supporting it, we will need to do some evaluation of whether it makes sense to do so, including what the cost/benefit level of effort is. cc. @jamescdavis @wagenet @gitKrystan

**Comment by gitKrystan** [comment]
I am in favor of accepting PRs to support it, but don't have time to commit to _writing_ the PRs to support it. 😂
