### ISSUE TITLE
[Bug] Un-rendering certain components causes memory leak

### ISSUE THREAD

**Issue by bendemboski** [emberjs/ember.js#20533]
### 🐞 Describe the Bug
Components meeting a couple of bizarrely specific conditions will leak after being un-rendered. Those conditions are:

1. The component invokes a local helper function from its template
2. The component registers a destructor that references `this`

### 🔬 Minimal Reproduction
[This repository](https://github.com/bendemboski/unrender-memory-leak/tree/scope-pollution-leak)'s `scope-pollution-leak` branch contains a minimal reproduction of the issue, both via an integration test, and steps for a manual repro in the dummy app.

### 😕 Actual Behavior
When a component that meets the above conditions is un-rendered, it will not be garbage collected as long as the app is still running.

### 🤔 Expected Behavior
All components should be garbage collected once they have been un-rendered.

### 🌍 Environment

- Ember: 5.2.0
- Node.js/npm: 16.15.1
- OS: MacOS
- Browser: Chrome

**Comment by acorncom** [comment]
Per discussions on Discord (https://discord.com/channels/480462759797063690/485447409296736276/1146624323868692520) Chris Thoburn is going to be posting an update here soon

**Comment by bendemboski** [comment]
Closing in favor of #20535 which is the issue in Ember -- this issue mixes it together with some weird closure-retaining behavior that's not actually about Ember/Glimmer.
