### ISSUE TITLE
Drop Node 16 in ember-source 5.4

### ISSUE THREAD

**Issue by kategengler** [emberjs/ember.js#20549]
Node 16 was only supported through early September. A new app on the 5.4 beta already does not work on Node 16 due to transitive dependencies that have updated engines.

**Comment by NullVoxPopuli** [comment]
(iirc) if we can get ember to a v2 addon, the node version will stop mattering for consumers, and in development, we can use "current" instead of "oldest supported LTS"

**Comment by kategengler** [comment]
Ok, but for now this is something that needs to be done in the next couple of weeks

**Comment by SergeAstapov** [comment]
@kategengler looks like this happened in https://github.com/emberjs/ember.js/pull/20716 which was part of v5.11.0 so can be closed?

**Comment by kategengler** [comment]
Thanks!
