### ISSUE TITLE
[Bug] application.inject undefined for dependency injection from initializer

### ISSUE THREAD

**Issue by hilljh82** [emberjs/ember.js#20633]
### 🐞 Describe the Bug

`application.inject` is undefined on the application parameter passed to the initializer.

### 🔬 Minimal Reproduction

I just created a new ember application using Ember 5.5 on Node 20.11.0. I then created an initializer using ember-cli. If you print the value of `application.inject`, it will be `undefined`. Here is the example initializer using Ember 5.5.0:

```javascript
export function initialize(application) {
  console.log (application);
  console.log (application.inject);    // prints undefined
}

export default {
  initialize,
};
```

### 😕 Actual Behavior

`application.inject` is `undefined`.

### 🤔 Expected Behavior

`application.inject` is defined and you can perform dependency injection.

### 🌍 Environment

- Ember: - 5.5.0
- Node.js/npm: - 20.11.0
- OS: - darwin arm64
- Browser: 
-- Chrome 120.0.6099.234
-- Safari 16.4, WebKit 18616.1.10.2)

### ➕ Additional Context

This bug was reported via my plugin [@onehilltech/ember-cli-google-analytics](https://github.com/onehilltech/ember-cli-google/tree/master/packages/ember-cli-google-analytics). I tried to update the plugin to 5.5, and was able to reproduce the problem. I then created a new Ember application that only has an initializer, and was able to track the problem down to the `application` parameter not have the `inject(app)` function defined.

**Comment by NullVoxPopuli** [comment]
Hey, sorry you ran in to this, but `application.inject` (aka "implicit injections") isn't recommended and was deprecated in 3.x  for removal in 4.x

Here is the deprecation guide: https://deprecations.emberjs.com/v3.x#toc_implicit-injections

**Comment by hilljh82** [comment]
@NullVoxPopuli Thanks for the prompt response. That explains what it was working on Ember 4 and not Ember 5. 

Question: Can you point me to the recommended way for handling deprecated logics between major versions? For example, some of our users are still on Ember 4, but we want to support Ember 5 as well.

**Comment by NullVoxPopuli** [comment]
to support both, you probably want to do something like:

```js
function myInitializer(app) {
  if (app.inject) {
    app.inject(....)
  }
}
```
that way, in environments that don't have `inject`, you can recommend folks directly inject the service, as the deprecation guide recommends:
```
class X {
  @service theService;
}
```

**Comment by hilljh82** [comment]
I was thinking of that approach, but I second guessed myself. Clearly, I failed to follow the KISS (Keep It Simple Silly) method I teach my students in this situation. 

Thanks for your assistance. I now have several add-ons that I need to make compatible with Ember 5.
