### ISSUE TITLE
[Bug] "func is not a function" rendering helper

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#20638]
### 🐞 Describe the Bug
Rendering `{{(page-title "foo")}}` outputs `"func is not a function"`

### 😕 Actual Behavior
Error

### 🤔 Expected Behavior
No error

### 🌍 Environment

- Ember: - 5.5.0
- Node.js/npm: - 18.16.0/9.5.1
- OS: Mac
- Browser: Chrome

**Comment by NullVoxPopuli** [comment]
do you have a repro repo?

I've seen page-title work well in new projects :sweat_smile:

**Comment by kategengler** [comment]
I'm going to close this -- please reopen if you have a repro but as `page-title` is in every application we see that it is working so there must be something else going on here.
