### ISSUE TITLE
[Bug] Key-pair not treated as identity in #each over a Map

### ISSUE THREAD

**Issue by AlexEdgcomb** [emberjs/ember.js#20661]
### 🐞 Describe the Bug

Ember does not seem to treat a Map's key-pair as the identity in an `#each`, as a component associated with a particular key-pair is destroyed when a new key-pair is added to the Map.

### 🔬 Minimal Reproduction

The app adds a person on-click and starts a timer for that person.

1. Pull down https://github.com/AlexEdgcomb/ember-each-array-vs-map
2. `git checkout -b map origin/map`
3. `npm install`
4. `ember s`
5. Go to http://localhost:4200/
6. Click `Add person`
7. Wait a second
8. Click `Add person`

### 😕 Actual Behavior
Albert Hofmann's timer reset
<img width="357" alt="image" src="https://github.com/emberjs/ember.js/assets/3512898/e66fa5bc-8314-4a5c-9196-d92bb40239bf">

### 🤔 Expected Behavior
Albert Hofmann's timer to NOT reset

### 🌍 Environment

- Ember: `ember-cli-app-version@5.0.0`
- Node.js/npm: `node -v` v18.14.2.`npm -v` 9.5.0
- OS: MacOS 13.4
- Browser: Firefox 123.0.1

### ➕ Additional Context

Array does not have this issue: https://github.com/AlexEdgcomb/ember-each-array-vs-map/tree/array

`#each`'s documentation uses the word "collection" 2 times and "array" 11 times, so maybe `#each` is intended to only support an Array:
https://api.emberjs.com/ember/release/classes/Ember.Templates.helpers/methods/each?anchor=each

**Comment by NullVoxPopuli** [comment]
is the same behavior experienced if you use each-in instead of each? (since map is more object-like than arrays?)

**Comment by AlexEdgcomb** [comment]
@NullVoxPopuli , no, the behavior is not experienced with each-in. each-in makes more sense for a Map. I recant the bug report!
