### ISSUE TITLE
[Question] : Ember JS in existing nodejs mobile 

### ISSUE THREAD

**Issue by jhay06** [emberjs/ember.js#20665]
Hi , is there a way i can include ember js on existing nodejs mobile without building it to APK ? what should i need to add in libs to run ember js ? 

I have a mobile app created in different language , QT , then i just added nodejs library there because the app has a webserver intended to be localhost only ,   so building emberjs app directly to apk is not an option because the one that creates the apk is the qt compiler . 

is there any instruction or just the standard ember cli works out of the box ? im confused on the .bin folder because there has a lot of windows executable dependency there . 

any way ? thanks in advance

**Comment by evoactivity** [comment]
Is your QT app creating a webview that loads the localhost nodejs server?

If so you should have nodejs server return the build output of an ember app just like you would if deploying to a normal web server. Part of your build script should first build the ember app and copy it's output to a directory of your preference and have your nodejs server load the index.html.

**Comment by jhay06** [comment]
I see , thanks will try
