### ISSUE TITLE
circular import between @ember/object/index and @ember/object/observable

### ISSUE THREAD

**Issue by patricklx** [emberjs/ember.js#20709]
### 🐞 Describe the Bug
there is a circular import between 
`'@ember/object/index';`
and
`'@ember/object/observable';`
and 
`@ember/array/index`.

those files are actually also importing from `@ember/-internals/metal`, so they could use that directly to access `get, set`

https://github.com/emberjs/ember.js/blob/main/packages/%40ember/object/observable.ts#L14
https://github.com/emberjs/ember.js/blob/main/packages/%40ember/object/index.ts#L13

this causes rollup to sometimes build it wrong and have runtime errors later. (testing with vite+dep optimizer)

**Comment by kategengler** [comment]
cc @ef4

**Comment by ef4** [comment]
Fixed in #20734
