### ISSUE TITLE
Limited documentation for Ember.Select component

### ISSUE THREAD

**Issue by marvfinsy** [emberjs/ember.js#20705]
### 📙 Describe the Issue

Using ember select. your documentation seems to indicate that i can give the select object a custom view for handling <option> tags by passing the class or class name to the optionView property. 

I've tried this a number of different ways, each time thing just hang. There seems to be no documentation on how to do this?

1) Ive created a new class extending the Ember.SelectOption class. When i try to set the optionView property of the Ember.Select things just hang no crash no logging.

So is simple/basic example on how to do this to get me started...

thx ~Marvin Foster
marvinfoster@finsync.com or mmarvb7@gmail.com

**Comment by NullVoxPopuli** [comment]
What's "ember select"?

This is how I do `<select>`: https://tutorial.glimdown.com/8-form-data-controlled/4-select
Or using: form-data-utils: https://github.com/nullVoxPopuli/form-data-utils?tab=readme-ov-file#non-primitive-values

**Comment by marvfinsy** [comment]
Thx...

Don't know if this is still used or available but this was way back in early ember and it could  used as follows:

SelectCategories = Ember.Select.extend(
)

In the .hbs you would have:

{{view SelectCategories
    contentBinding='my.data'
    optionLabelPath='content.indentedMenuDisplay'
    optionValuePath='content'
    prompt='Select account...'
    selectionBinding='content.category'
    disabledBinding='disabled'
    classNames='classNames'
    }}

One of the options (no shown) is: optionView. This is supposed to allow be to give a custom class that will be used by Ember.Select when writing html for the <option> tag.

Ember.Select was back a while ago... (ember v2) maybe... The code i'm modifying is old and business does not want expense of a complete re-write.

**Comment by NullVoxPopuli** [comment]
using native `<select>` in a component should still work -- probably less work than using "view"s and "Ember.Select", neither of which exist anymore.

**Comment by NullVoxPopuli** [comment]
that said, if you hop in the ember discord, https://discord.gg/emberjs, there are others stuck on older ember that could help you out with specifics.

Alternatively, you can use the version switcher to view old guides and api documentation:

![image](https://github.com/emberjs/ember.js/assets/199018/7df50d02-5199-4a45-9467-7a32a19c1c01)
![image](https://github.com/emberjs/ember.js/assets/199018/1815ab50-5c75-4893-8498-3114745905e5)


https://api.emberjs.com/ember/1.13/classes/Ember.Select

I had to click "show private and deprecated" to view this.
It's probably not supposed to be used in Ember v2 -- it was removed in 2.5 (according to the docs)

**Comment by kategengler** [comment]
Ember.Select is indeed long gone. It was deprecated in 1.x https://deprecations.emberjs.com/id/ember-select The `view` helper you demonstrate is also long gone. 

I agree with @NullVoxPopuli that your best bet is to ask in the Ember Discord to see if you can get answers from others using older versions of Ember. Be sure to share what version you are on. My memory is that native selects did not work well until the 3.x version of Ember, but before that there were a few addons that replaced Ember.Select.
