### ISSUE TITLE
[5.10] Can't import the template-compiler

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#20718]
### 🐞 Describe the Bug
Upgrading from 5.9 to 5.10 and importing the template compiler leads to:
```
Uncaught TypeError: Application.initializer is not a function
    at ember-template-compiler.js:2100:1
    at ember-template-compiler.js:2108:1
```

### 🔬 Minimal Reproduction
```
ember new --pnpm ember-template-compiler-bug
cd ember-template-compiler-bug
# add `app.import('vendor/ember/ember-template-compiler.js');` to `ember-cli-build.js`
ember test
```

### 😕 Actual Behavior
That error.

### 🤔 Expected Behavior
No error.

### 🌍 Environment

- Ember: 5.10.0
- Ember-CLI: 5.10.0
- Node.js/npm: 22.4.1
- OS: Linux
- Browser: N/A

**Comment by NullVoxPopuli** [comment]
I've reproduced the issue over at https://github.com/NullVoxPopuli/limber/pull/1787

**Comment by NullVoxPopuli** [comment]
so far, it seems the the fix is to remove the `app.import`

**Comment by boris-petrov** [comment]
I'm confused... how can I remove it if I need it?

**Comment by NullVoxPopuli** [comment]
A couple tests,

**Comment by NullVoxPopuli** [comment]
for hbs-only compiling, I use:
```js
const { precompileJSON } = importSync('@glimmer/compiler');
const { getTemplateLocals } = importSync('@glimmer/syntax');
```

and for gjs compiling, I use:
```js
const compiler = importSync('ember-source/dist/ember-template-compiler.js');
```

**Comment by ef4** [comment]
This should be fixed by https://github.com/emberjs/ember.js/pull/20726 which is about to go out as 5.10.2

**Comment by kategengler** [comment]
The fix is released in v5.10.2 and v5.11.0-beta.2

**Comment by NullVoxPopuli** [comment]
I don't think this is fixed.

For example,
```bash
npx ember-cli@latest new my-template-compiler-app --pnpm --embroider
cd my-template-compiler-app
pnpm add @embroider/macros
pnpm start
```

then, in `app/app.js`
```js
import { importSync } from '@embroider/macros';

console.log(importSync('ember-source/dist/ember-template-compiler.js'));
```

and after visiting `/`, it prints:

![image](https://github.com/user-attachments/assets/a88b2e22-bccd-460e-9a19-623fa863d0dc)

which is the empty module object :thinking:

**Comment by ef4** [comment]
The documented way to add the runtime template compiler to ember is to use `app.import`. All the stuff above telling people to switch away from it is not helpful. The limber PR linked above also shows `app.import` was in use before this PR, so I have no reason to believe that trying to directly `importSync` it ever worked.

**Comment by NullVoxPopuli** [comment]
![roger roger](https://media1.tenor.com/m/HeoBYssKhqgAAAAC/battle-droid-roger-roger.gif)

So, getting rid of `importSync(...)`, and re-adding the `app.import()` got me further, but I also had to 
1. Change my import of the compiler to `import * as compiler from 'ember-template-compiler'`
1. Add `"externals": ["ember-template-compiler"],` to `"ember-addon"` in my addon's package.json


This makes everything work
