### ISSUE TITLE
In 6.1-alpha, importing `ember-source/types` doesn't work, but the types: [] method does

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember.js#20789]
idk if this is just how TS is changing, but in one PR: https://github.com/NullVoxPopuli/limber/pull/1864

I noticed that all of the `import 'ember-source/types'` lines no longer define the types of the ember-source modules.

Now, I know the blueprint, and other ecosystems have been preferring types (in tsconfig.json#compilerOptions#types):
```
"types": ["./node_modules/ember-source/types/stable"]
```

it's just a bit lengthy as this doesn't respect package.json#exports.

It is suspicious that changing the ember version caused the difference in behavior.

**Comment by simonihmig** [comment]
Shouldn't the `exports` have to cover these type imports, seems there are not? https://github.com/emberjs/ember.js/blob/main/package.json#L8-L12

**Comment by NullVoxPopuli** [comment]
correct -- and fwiw, ember-data has been having the same problem (for much longer) -- finding that their type declarations are only loaded via this `types: [ ./node_modules/* ]` sillyness.

So, I wonder if, in order to support `types: [ "pkg/export-name" ]` _or_ `import 'pkg/export-name'`, we're missing something in our declaration output in both ember-source and ember-data's packages

**Comment by simonihmig** [comment]
Wouldn't an additional entry like `"./types/*": "./types/*"` work?

> And maybe "typesVersions" is what stopped worked in TS?

AFAIK, this is used if you don't have some "modern" value for `moduleResolution` like `node16` or `bundler`. So either `exports` or `typesVersions` is used, depending on that config.

**Comment by Windvis** [comment]
> correct -- and fwiw, ember-data has been having the same problem (for much longer) -- finding that their type declarations are only loaded via this types: [ ./node_modules/* ] sillyness.

FWIW, EmberData chooses to not publish the type `exports` config until the types themselves are considered stable, so the `./node_modules/` prefix is needed for that reason.

Discussion: https://discord.com/channels/480462759797063690/1290318997040005234/1290367110744379445

**Comment by NullVoxPopuli** [comment]
Fix here https://github.com/emberjs/ember.js/pull/20792
