### ISSUE TITLE
Improve Readability of Static for() Method Implementation

### ISSUE THREAD

**Issue by sson68x** [emberjs/ember.js#20802]
During a code review of the `static for()` method in [overrides.js](https://github.com/emberjs/ember.js/blob/main/lib/overrides.js), I observed that while the method effectively manages add-on overrides, the readability could be improved. Specifically, the method contains nested loops and conditions that make the code harder to follow and maintain, especially for new contributors. Simplifying the structure and reducing nesting could improve code clarity and facilitate easier contribution from developers with varying experience levels.

I recommend refactoring the method to reduce complexity, improve readability, and make it more approachable for developers who may be unfamiliar with the current implementation.

**Comment by NullVoxPopuli** [comment]
Are you ai... From a different project?

What overrides?
What static for?

**Comment by kategengler** [comment]
I do see the method and the file, however I think it is fine. I do think that this entire file could probably be removed -- cc @ef4 to check that assumption?
