### ISSUE TITLE
itemViewClass in CollectionView does not work with ArrayController

### ISSUE THREAD

**Issue by johnkpaul** [emberjs/ember.js#3086]
Thanks so much to @stefanpenner for his help in debugging this so far.

You can see this issue in this jsbin - http://jsbin.com/apawap/12/edit

I expect the itemViewClass to be instantiated, but it is not. I am able to get it to be instantiated if I add `content: Ember.computed.alias('controller.content')` to the ItemsView, but then there are further issues.

http://jsbin.com/apawap/18/edit

After adding that line, I do get individual item views, but the data is empty and for some reason, the controller is the ItemsController (plural) instead of the ItemController.

I'd love to be told that I was doing something wrong here, but I'm pretty sure that this is a bug in how CollectionViews interact with ArrayControllers. 

Thank you!

**Comment by wagenet** [comment]
This stuff isn't really in line with the direction Ember is headed now. If someone wants to PR this, great, but I'm going to close it, since I don't think we're likely to spend any more time on this.
