### ISSUE TITLE
Wrong assertion: The value that #each loops over must be an Array.

### ISSUE THREAD

**Issue by earthquakesan** [emberjs/ember.js#4365]
The problem is that I can't pass the object to {{#each}} Handlebarsjs conditional, because it raises exception in ember.js code. Handlebarsjs {{#each}} can iterate through objects, here is the excerpt from Handlebars v1.3.0: http://pastebin.com/UTtvnhcB

The place in ember.js where this occurs:

```
@module ember 
@submodule ember-handlebars

Ember.Handlebars.EachView = Ember.CollectionView.extend(Ember._Metamorph, {
...
_assertArrayLike: function(content) {
    Ember.assert("The value that #each loops over must be an Array. You passed " + content.constructor + ", but it should have been an ArrayController", !Ember.ControllerMixin.detect(content) || (content && content.isGenerated) || content instanceof Ember.ArrayController);
    Ember.assert("The value that #each loops over must be an Array. You passed " + ((Ember.ControllerMixin.detect(content) && content.get('model') !== undefined) ? ("" + content.get('model') + " (wrapped in " + content + ")") : ("" + content)), Ember.Array.detect(content));
  },
...
```

```
@module ember
@submodule ember-views

Ember.CollectionView = Ember.ContainerView.extend({
...
  _contentDidChange: Ember.observer('content', function() {
    var content = get(this, 'content');

    if (content) {
      this._assertArrayLike(content);
      content.addArrayObserver(this);
    }

    var len = content ? get(content, 'length') : 0;
    this.arrayDidChange(content, 0, null, len);
  }),
...
```

**Comment by jlesquembre** [comment]
@rwjblue Is there any documentation where I can see the differences between standard handlebars and the ember version? I was getting the same error and finding the reason was frustrating, since according to the handlebars docs, it should work. And now I'm not sure anymore what features can I use.

**Comment by wagenet** [comment]
I'm reopening this but as a documentation issue instead of a bug. It definitely seems like there's some confusion here about behavior that we should try to clear up.

**Comment by mmun** [comment]
Object keys are stable on all modern browsers. Once diffing lands we'll lbe able to support this fairly simply. Presently it is difficult because we don't observe insertion/deletion of keys on objects.

**Comment by sandstrom** [comment]
The ability to run `{{#each}}` on an `Ember.Enumerable` would be awesome :)

**Comment by stefanpenner** [comment]
the {{each stuff now just blindly enumerates over forEachs
