### ISSUE TITLE
Helper to add css class based on active route 

### ISSUE THREAD

**Issue by manuelmitasch** [emberjs/ember.js#4387]
# Issue
As discussed in https://github.com/emberjs/ember.js/issues/1822, https://github.com/emberjs/ember.js/pull/1849, and lately in https://github.com/manuelmitasch/ghost-admin-ember-demo/commit/fba3ab0a59238290c85d4fa0d7c6ed1be2a8a82e#commitcomment-5396470 there is currently no clean way to have an active css class (depending on active route) on a tag other than a link-to helper. This markup is used by bootstrap for example.

## Desired output:
```
<li class="active>
  <a href="post">...</a>
</li>
```

# Current Workaround
```
{{#link-to 'post' this tagName="li"}}
  {{#link-to 'post' this class="permalink" title="Edit this post"}}
    ...
  {{/link-to}}
{{/link-to}}
```

This double nesting is ugly.

# Proposal
We should add an `active-route` helper, that adds an active class to the enclosing tag. The existing active route detection functionality of the `Ember.LinkView` should be moved into a mixin that can be reused for an `Ember.ActiveRouteView`. 

# Proposed usage
```
<li {{active-route 'post' this}}>
  {{#link-to 'post' this}}
    ...  
  {{/link-to}}
</li>
```

# Other fancy usage
```
<body {{active-route view.classNames}}>
```
Sometimes, designers put classes on body to distinguish between styles for different templates. When the first parameter is no string (no route) it could lookup/add css classes from the handed property (eg. a views classNames property). 

If you guys are happy with this proposal, I can try to implement a first draft.

PING @trek @stefanpenner

**Comment by wagenet** [comment]
@machty Services are in. Any further thoughts?

**Comment by chrisjstephens** [comment]
Thanks Panman8201 for the link

That post seemed to work for me and wasn't too complicated.

**Comment by rwjblue** [comment]
@manuelmitasch - Thanks for the taking the time to submit this.  As you can see we aren't terribly good at handling feature requests in the main repo's issues. Due to that, we have created the http://github.com/emberjs/rfcs repo to track proposals (as PR's) and requests for features (as issues).  If you are still interested in pushing this forward, could you re-open this over there?
