### ISSUE TITLE
AMD detection and define by default

### ISSUE THREAD

**Issue by jayphelps** [emberjs/ember.js#4402]
Almost the same thing previously here: https://github.com/emberjs/ember.js/pull/776 but while the resolution was great, removing Ember's `window` reliance, it still doesn't detect AMD environments and define itself automatically.

Literally something as simple as this would mostly satisfy me...which I'd gladly PR if core is down with the sickness.

```javascript
if (typeof require === "function" && typeof define === "function") {
    define("ember", 
      ["exports"],
      function(__exports__) {
        "use strict";
        __exports__["default"] = Ember;
      });
  }
```
If supported, it begs the question whether it should still leak `Ember` globally or not if running in an AMD-supported environment...or if there is some sort of `Ember.noConflict()` for global variable nazis. Personally, I vote still go global and no need for `noConflict`...was just being devil's advocate.

btw I do realize https://github.com/emberjs/ember.js/commit/305202fa51aca55ce1ff935aa9fb8ebe3da4a0d4 has an example for people who want to wrap Ember as a module, this issue is that I believe Ember should detect and do it automatically. Especially since the source is being ported to ES6 -> AMD and EAK is the same, I think we should buy into it completely.

**Comment by sandstrom** [comment]
With ember-cli + ES6 modules I think it's safe to close this. @jayphelps totally up to you, but if you feel this is resolved feel free to close.
