### ISSUE TITLE
dynamic binding declaration ("dereferenced" binding)

### ISSUE THREAD

**Issue by tkellen** [emberjs/ember.js#4619]
Is there currently a way to declare a binding to a dynamically assigned property name in a template?

Here is a contrived example:
```js
var App = Ember.Application.create({});

App.ApplicationController = Ember.ObjectController.extend({
  fields:  ['name', 'email'],
  name: 'tyler kellen',
  email: 'tyler@sleekcode.net'
});
```
```html
{{#each field in fields}}
  {{field}}: {{input type="text" valueBinding="*field"}}<br>
{{/each}}
```

The resulting input elements should be bound to the `name` and `email` properties of the application controller instance used as context for the template.

Here is a JSBin showing that this does not currently work:
http://jsbin.com/toyih/8

If there is not currently a way to do this, would the Ember team be open to a PR that introduces a dereferencing operator as I've shown above?  If yes, where is the logic for *Binding?

**Comment by rwjblue** [comment]
This is possible now: http://rwjblue.jsbin.com/gavana/edit?html,js,output

```
    {{#each-in model as |field|}}
      <div>
        {{field}}: {{input value=(mut (get model field))}}
      </div>
    {{/each-in}}
```
