### ISSUE TITLE
Avoid suggesting the usage of native Promise

### ISSUE THREAD

**Issue by asaf** [emberjs/ember.js#4711]
Hey,

As long as Ember supports IE8, it is more correct to avoid suggesting the usage of native `Promise` object as it's not supported in IE8 and currently documented here: http://emberjs.com/api/classes/Ember.RSVP.Promise.html

Thanks.

**Comment by happycollision** [comment]
I was thinking about taking a crack at this issue, but the link to edit from the RSVP part of the documentation on the site is broken...

**Comment by wagenet** [comment]
@happycollision I'm pretty sure @rwjblue is the person to coordinate with here. Sounds like he has a specific plan in mind.

**Comment by sguha00** [comment]
@happycollision Here is the link to the documentation http://emberjs.com/api/classes/RSVP.Promise.html

**Comment by sandstrom** [comment]
> As long as Ember supports IE8

Perhaps this issue can be closed. Ember 2.0 won't support IE8 (and the browser has a nanoscopic market share these days).

**Comment by runspired** [comment]
I do think it'd be useful to explicitly point out / document that the deconstruction pattern is very useful for being able to quickly refactor to use native Promises or smaller bits of Ember in the future.

e.g.

```
import Ember from 'ember';

const {
  RSVP
} = Ember;

const {
  Promise
} = RSVP;

var aPromise = new Promise(...);
```

or in globals

```
var Promise = Ember.RSVP.Promise;
var aPromise = new Promise(...);
```

In either case, when you can use the native `Promise` implementation it is now only necessary to drop the `const` (ES6) or the `var` (globals) definition from the top of the file to use it.

@elwayman02 has mentioned wanting to blog about architecting this way with me.

**Comment by elwayman02** [comment]
:+1: I think one of the best strategies of the Ember community is future-proofing by aligning with future specs. It would definitely be useful to document the advantages of these patterns and what they enable.

**Comment by rwjblue** [comment]
closing for now, this has gone stale

**Comment by QuantumInformation** [comment]
> RSVP also integrates with ember dev tools and I think acceptance tests wait for all RSVP promises to settle

So basically we should keep using RSVP for all ember apps?
