### ISSUE TITLE
[Feature request] Pass to `propertyDidChange` the DK that triggered the change.

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#4776]
I'm tying to make a feature in computed properties and I've found myself saying "I wish that `didChange` would receive the name of the dependency that triggered the change".

I spoked to @hjdivad and he doesn't see any reason why this is no so.
Also told me that @krisselden would be he gatekeeper on this.

Changes to add this feature are pretty minimal (apparently).

```js
// https://github.com/emberjs/ember.js/blob/master/packages_es6/ember-metal/lib/property_events.js#L96-L111
function iterDeps(method, obj, depKey, seen, meta) {
  var guid = guidFor(obj);
  if (!seen[guid]) seen[guid] = {};
  if (seen[guid][depKey]) return;
  seen[guid][depKey] = true;

  var deps = meta.deps;
  deps = deps && deps[depKey];
  if (deps) {
    for(var key in deps) {
      var desc = meta.descs[key];
      if (desc && desc._suspended === obj) continue;
      method(obj, key); // ===> method is `propertyDidChange`.
    }
  }
}

// ember-metal/lib/property_events.js#L57-L72
function propertyDidChange(obj, keyName) {
  var m = obj[META_KEY],
      watching = (m && m.watching[keyName] > 0) || keyName === 'length',
      proto = m && m.proto,
      desc = m && m.descs[keyName];

  if (proto === obj) { return; }

  // shouldn't this mean that we're watching this key?
  if (desc && desc.didChange) { desc.didChange(obj, keyName); } // ===> Pass along DK name
  if (!watching && keyName !== 'length') { return; }

  dependentKeysDidChange(obj, keyName, m);
  chainsDidChange(obj, keyName, m, false);
  notifyObservers(obj, keyName);
}
```

Since we already have the data in the context, it's free to pass them along, and could be an general-purpose addition that might be helpful. 

This extra argument (then name of the dependentKey that triggered the change) would be optional of course, and `propertyWillChange` should be updated as well to keep coherence. 

I'm ready to make this happen but I prefer to ask before make any changes in so delicate parts.

**Comment by rwjblue** [comment]
I don't really think this is a direction we want to go.  Also if it is, we should open a PR against RFCS now.  

@cibernox - Sorry for sitting on this so long.

**Comment by cibernox** [comment]
Neither do I. This is mostly motivated by array/reduce computed black magic, I never felt the need again.
