### ISSUE TITLE
Dynamic route segments aren't URL-encoded

### ISSUE THREAD

**Issue by dfreeman** [emberjs/ember.js#4794]
I've read through #3263 and the associated PR (#3545), and while it looks like everybody involved agreed that URL encoding should 'just work', it doesn't look like that's where things ultimately landed.

Those issues were closed in favor of rolling in a fix that was part of @alexspeller's query params work, but unfortunately it appears URL encoding is _only_ handled for query parameters, not dynamic route segments.

As a quick example of where things can go wrong, take a look at [this JS Bin example](http://jsbin.com/ucanam/4819). It has two models, one with ID `'A B'` (Raw) and one with ID `'A%20B'` (Encoded). If you click the link for the 'Encoded' model and then refresh the page, you'll see it loads the 'Raw' one instead.

`HashLocation` and `HistoryLocation` both appear to have this behavior. I would expect them always to encode dynamic path segments to avoid this kind of ambiguity.

**Comment by MichalBryxi** [comment]
Got also hit by this one. I think Ember should handle this as I'm now supposed to encode and decode each potentially "dangerous" dynamic segment I'm using by hand. I don't see a reason why the user should care about this - should work out-of-box.

**Comment by rwjblue** [comment]
I updated the provided JSBin to current canary setup:

http://rwjblue.jsbin.com/dusuti/edit?html,js

The reported issue of clicking on "Encoded" and being transitioned into "Raw" after a refresh remains.

**Comment by dfreeman** [comment]
I haven't dug in to be certain yet, but it looks like this may have been fixed in 2.7?

**Comment by Serabe** [comment]
It seems so. Closing this as fixed, though I think there is a related issue :(
