### ISSUE TITLE
Route render into/outlet doesn't work when specifying viewName

### ISSUE THREAD

**Issue by gdub22** [emberjs/ember.js#4797]
http://emberjs.jsbin.com/fowusere/2/edit

The main view for the route doesn't appear to be set up in time to render additional views into it, when using `viewName`.

**Comment by rwjblue** [comment]
I don't believe that this is supported any longer (`Ember.View` itself is not exposed as part of 2.0.0).

I'm happy to reopen if its still an issue with idiomatic 2.0.0 style Ember...
