### ISSUE TITLE
Improve error message 'Error while loading route: Error: Assertion Failed: ArrayProxy expects an Array or Ember.ArrayProxy, but you passed object'

### ISSUE THREAD

**Issue by eccegordo** [emberjs/ember.js#4805]
This error message:

```
Error while loading route: Error: Assertion Failed: ArrayProxy expects an Array or Ember.ArrayProxy, but you passed object
```

Pretty obvious what it means and how to fix. But sometimes not so obvious what specific route is being referred to. If would be useful if these kinds of errors could provide the name or path of the route in the error message. Would make the error less confusing and easier to act upon.

Not sure the exact implementation needed, searching through the source I could only find this:

https://github.com/emberjs/ember.js/blob/master/packages_es6/ember-routing/lib/system/router.js#L539

**Comment by rwjblue** [comment]
I'd happily review a PR for this, but that doesn't seem likely at this point.  Closing...

**Comment by GetContented** [comment]
Wow that's an old issue! Nicely closed, @rwjblue :+1:
