### ISSUE TITLE
No way of binding nested component actions programmatically?

### ISSUE THREAD

**Issue by orochi235** [emberjs/ember.js#4859]
Is there a clean/public way to dynamically bind the actions of two nested Ember components in JS? I've spent a fair amount of time digging through docs and Stack Exchange posts, and it seems like there's no way to do this via Ember's public API. Is this an overlooked feature, an architectural constraint, or a deliberate design decision?

Some background: We've created a number of Ember components that dynamically instantiate each other. For instance, we have two called "dropdown-list" and "choice-list". When clicked, dropdown-list instantiates and displays a choice-list, and receives an action when an item in the choice-list is selected. 

This is obviously easy to do in a Handlebars template: you just declare the component and map the child's action to the name of the parent's action handler. But this isn't really an option for us, largely because the child component's DOM structure isn't a subtree of the parent component's DOM tree (it's being displayed in a global modal layer instead).

__I'm basically looking for a JS equivalent for the second half of this Handlebars declaration:__

	{{choice-list userSelect='handleUserSelection'}}

If it helps, here's how we're dynamically instantiating child components (from within an action handler on the parent component):

	this.set('list', App.ChoiceListComponent.createWithMixins(App.ModalMixin, {
		/* ... */
	}));

**Comment by oriSomething** [comment]
hi, i got similar issue when i'm trying to make some kind of smart forms. it's not exactly the same problem but i wish i could find a way to catch actions with components (maybe there is but i can't find?).
```

**Comment by oriSomething** [comment]
sorry about the missed post pressed, anyway…

hi, i got similar issue when i'm trying to make some kind of smart forms. it's not exactly the same problem but i wish i could find a way to catch actions with components (maybe there is but i can't find?).

the idea is that component `<form-top>` will catch action from `<form-bottom>` without having the controller as a mediator.

```handlebars
{{#form-top}}
    {{#form-bottom actionChange="actionChange"}}Will fire actionChange on some event{{/form-bottom}}
{{/form-top}}
```

if there was for example an option for example to declare on `<form-top>` actions that it catches. for example:

```handlebars
{{#form-top actions="actionChange"}}
    {{#form-bottom actionChange="actionChange"}}Will fire actionChange on some event{{/form-bottom}}
{{/form-top}}
```

it still doesn't solve all the problem, because i will still have to have a property in the controller that will be binded to both component to connect. but it at least can make the controller less bloated.

**Comment by mikeazo** [comment]
I am running into the same issue. I have a component, say ```foo```. In one place in my application, I create it using handlebars ```{{foo someAction='doSomething'}}```. That works fine.

In another place, I create the component programmatically:
```
Foo.create({someAction: 'doSomething'});
```

Inside the foo component's click, I call ```this.sendAction('someAction');```

For the component created via handlebars, everything works. For the component created programmatically, the actions never occur.

**Comment by orochi235** [comment]
I think you can get around this by setting the targetObject property of the “sending” component to reference the “receiving” component. Not sure how kosher of a solution this is, but it’s worked for me in the past.

**Comment by mikeazo** [comment]
@orochi235 You are correct, this does fix it. If I print the **targetObject** for the handlebars created component, it's **targetObject** is set. If I print it for the programmatically created one, it is null. Once I set it manually, everything worked.

**Comment by stefanpenner** [comment]
> {{#form-top actions="actionChange"}}
>     {{#form-bottom actionChange="actionChange"}}Will fire actionChange on some event{{/form-bottom}}
> {{/form-top}}

the way context shifting works now, this isn't a problem anymore, yielded block actions bubble up lexically

**Comment by stefanpenner** [comment]
> Foo.create({someAction: 'doSomething'});

passing these to create is also legit.

Will reopen, if some other example can be provided that is a pain.

**Comment by mikeazo** [comment]
@stefanpenner so are you saying that in newer versions of ember I don't have to set the *targetObject*? I'm on 1.8.1 right now.
