### ISSUE TITLE
run.bind only returns values *sometimes*

### ISSUE THREAD

**Issue by tim-evans** [emberjs/ember.js#4897]
I'm using `run.bind` for promise callbacks. When I return another promise from the bound function, it simply drops it. Doing some digging, I found that is because `run.join` returns values if it's not in the current run loop. (https://github.com/emberjs/ember.js/blob/master/packages_es6/ember-metal/lib/run_loop.js#L107)

**Comment by stefanpenner** [comment]
fixed now
