### ISSUE TITLE
Using each helper with Enumerable

### ISSUE THREAD

**Issue by quaertym** [emberjs/ember.js#4903]
I have a linked list implementation which implements Enumerable Mixin interface and I want to use that with each helper in my templates. The problem is each helper only works with an array. I am currently using toArray function of Enumerable however that is not efficient. Can each helper be changed to work with Enumerable or what's the recommended way of using Enumerable in templates?

**Comment by stefanpenner** [comment]
this wont be supported. Enumerable is private, the planned future of this will be to use `@@iterable`
