### ISSUE TITLE
Why do the testing helpers wait for timers to flush?

### ISSUE THREAD

**Issue by tomdale** [emberjs/ember.js#4906]
I'm working on a project where the current testing helpers aren't able to be used. I have some ideas for how we might be able to fix it, but I want to understand the current thinking first.

In our case, we have a list of items that is kept in sync via change notifications over WebSockets. If another user deletes an item in the list, we want to briefly show a notification overlay, then remove the item from the list after a view seconds.

![flow](https://cloud.githubusercontent.com/assets/90888/3039753/2ccd69c0-e0e3-11e3-9189-eb587cd4edc6.png)

We want to write a test that verifies that when an item is removed, the "Deleted" overlay is shown. Unfortunately, all of the existing test helpers (`click`, `andThen`, etc.) wait for _all_ deferred behavior to finish, including pending timers.

In our case, we show the overlay and immediately schedule the timer to remove it after a  few seconds. By the time our test helpers are invoked, the results we wanted to test have been removed.

My initial feeling is that we should carve out an exception for timers in the "wait for deferred" behavior in our helpers, but maybe there are use cases that I'm not thinking of.

**Comment by stefanpenner** [comment]
moving to async/await and 100% sync helpers really does fix this.

https://github.com/ember-cli/ember-cli/issues/3529

**Comment by rwjblue** [comment]
I'm going to close this for now.  I believe that async/await is the best path forward, but if we do want to do something about it without async/await it will need an RFC proposal/issue to track.

@tomdale - Please reopen over in RFCS if you are still interseted in pushing this forward.
