### ISSUE TITLE
[BUG] reduce computed  not updating correctly when depending on other reduce computed

### ISSUE THREAD

**Issue by patricklx** [emberjs/ember.js#4941]
I have some trouble getting computed.sum to work correctly.
I have a setup where a reduced property depends on another reduced property and both are referenced in a template.

I was able to create a small example:http://emberjs.jsbin.com/kuficima/9/edit

After the array changes the value of the sum is still the same. Only on the next array change i get the value from the previous change...
If "valSum" is removed from the template the other value is correctly updated.

I was searching for a cause, don't know if this is related, but seems strange anyway:

In [ReduceComputedPropertyInstanceMeta.setValue()](https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/computed/reduce_computed.js#L433)
the cache is set to the new value.

Later [propertyDidChange](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/computed.js#L362) is called which the sets the cached value to "undefined".

But on the next property request it has the old one again...

**Comment by stefanpenner** [comment]
reduce computed is gone, glimmer allows us to simpler sort/filter/reduce simple arrays and return a fresh one each time!
