### ISSUE TITLE
add "currentUri" to application controller

### ISSUE THREAD

**Issue by ilovett** [emberjs/ember.js#4963]
Would be fantastic if you could some how build a url based on the currentPath... from within that function...  Does a reverse look up of the model for controller and fills in the dynamic url pieces

    Ember.Router.map(function() {
        this.route('index', { 'path' : '/' });
        this.resource('translation', { 'path' : '/t' }, function() {
            this.route('index', { 'path' : '/:translation_hash' });
        });
    });

    Ember.Router.reopen({
        'location' : (GLOBALS.location) ? GLOBALS.location : 'history',
        'onTransition' : function() {
            console.log(this.get('router.reverseUrl'));
            // "/t/cXwsd5"
        }.on('didTransition')
    });

Why?  Running apps on Phonegap / Cordova you will quickly find that "window.location" don't work so well... nah mean?

**Comment by sandstrom** [comment]
I think it's safe to close this issue in favour of the RFC on a routing service: https://github.com/emberjs/rfcs/pull/38

*It isn't solved, but the RFC would be the right place to continue the discussion.*
