### ISSUE TITLE
childViews state never updates

### ISSUE THREAD

**Issue by ryanflorence** [emberjs/ember.js#4981]
http://emberjs.jsbin.com/liziq/1

Why it matters:

When building components with keyboard accessibility you need to know the order of the child views to be able to focus/select the next item in the list.

There are two sane approaches:

1. Use `childViews`. Unfortunately, this is unreliable.

2. Register child views on `didInsertElement` with the parent and mange the list yourself. The problem here is that you don't know which position in the array to insert the new item.

But since neither of these work we bail out of ember and use the DOM to find the items, get their IDs, and then map them back to ember components.

**Comment by rwjblue** [comment]
Seems to be working properly now.  Demo: http://rwjblue.jsbin.com/rifuza/edit?html,js,output
