### ISSUE TITLE
Deferred listener is not called if a suspended listener has already been added to the observerSet

### ISSUE THREAD

**Issue by glennsl** [emberjs/ember.js#5034]
See the scenario at http://jsfiddle.net/CX3TD/. My understanding is that both buttons should exhibit the same behavior, that is they should both increment the counter by exactly one.

The reason the deferred button does not is as follows:
- The first call to propertyDidChange (within suspendObserver) adds the listener to the observerSet with the suspended flag.
- The second call then sees the listener already present in the observer set, and so does nothing, disregarding the suspended flag.
- When the observerSet is later flushed, sendEvent sees it is suspended and ignores it.

I've fixed the issue temporarily by modifying listenersUnion so as not to add suspended listeners to the observer set, but since listenersUnion is very internal and has to be modified in place, it's a terrible solution.

**Comment by rwjblue** [comment]
Updated the JSFiddle to use 2.5.0: http://jsfiddle.net/CX3TD/2/

Seeing the same behavior as originally reported.

**Comment by rwjblue** [comment]
@glennsl - If you are still interested here, I think a PR with the small / targetted fix would be great.

**Comment by Serabe** [comment]
Tried to fix it. Have a test for it but too metal for my knowledge:

```js
testBoth('suspending observers should not fire during callback even if deferred', function(get, set) {
  let obj = {};
  let target, otherTarget;

  target = {
    values: [],
    method() { this.values.push(get(obj, 'foo')); }
  };

  otherTarget = {
    values: [],
    method() { this.values.push(get(obj, 'foo')); }
  };

  addObserver(obj, 'foo', target, target.method);
  addObserver(obj, 'foo', otherTarget, otherTarget.method);

  function callback() {
    /*jshint validthis:true */
    equal(this, target);

    set(obj, 'foo', '2');

    return 'result';
  }

  set(obj, 'foo', '1');

  equal(_suspendObservers(obj, ['foo'], target, target.method, callback), 'result');

  set(obj, 'foo', '3');

  deepEqual(target.values, ['1', '3'], 'should invoke');
  deepEqual(otherTarget.values, ['1', '2', '3'], 'should invoke');
})
```

Marking issue as Old.
