### ISSUE TITLE
itemViewClass should use the model of the itemController, not the ArrayController

### ISSUE THREAD

**Issue by mehulkar** [emberjs/ember.js#5125]
When I use the `{{render}}` view helper to render an ArrayController, and I define the associated view to be a `Em.CollectionView`, I expect that the `content` of the `childViews` will be bound to the model of the respective `itemController`. This does not currently seem to be the case. 

Here's a JSFiddle to demonstrate: http://emberjs.jsbin.com/vificasu/1/edit

I imagine the goal is to set the controller context of itemViewClasses to the itemController?

**Comment by stefanpenner** [comment]
itemController / arrayController are deprecated
