### ISSUE TITLE
Detect and warn on goofy use of `sendAction(undefined)`

### ISSUE THREAD

**Issue by trek** [emberjs/ember.js#5163]
This came across my desk today:
```handlebars
  {{x-foo on-bar=baz}}
```

When they meant 
```handlebars
  {{x-foo on-bar="baz"}}
```

so

```
export default Component.extend({
   click: function(){
     this.sendAction('on-bar', someArg);
   }
});
```

Was just silently failing, which is confusing.

**Comment by rwjblue** [comment]
Closing for now.  `sendAction` is likely going to be completely deprecated at some point in the 2.x cycle (and can mostly be avoided today with closure actions).

**Comment by yanzixiang** [comment]
In the v2.2.0 guide,
 http://guides.emberjs.com/v2.2.0/components/handling-events/
there is no topic that talks about how to sendActions to the controller,
can somebody add some guide....

**Comment by nightire** [comment]
@yanzixiang You don't _sendActions_ from components to controller, just to reference an existed action as a attribute of component by its name.

`{{my-component needAction=(action 'actionName')}}`

In your component `this.attrs.needAction` is the action itself with the context bound, this is called **Closure Actions**. In the meantime, this is the recommended way to use actions.

Just remember, don't _send actions_, try to _bind actions to your components_, as possible as you can.
