### ISSUE TITLE
computed @each leaks observers

### ISSUE THREAD

**Issue by fengb** [emberjs/ember.js#5181]
When using computed with @each, there is a problem with the observers not being removed.

Example: http://jsbin.com/tevobike/1/edit

Test within console:

1. `testParent.timedPoke()` should be very fast
2. `testParent.copyLeak(10000)`
3. `testParent.timedPoke()` is noticeably slower
4. `testParent.copyNoLeak(10000)`
5. `testParent.timedPoke()` is unchanged

**Comment by rwjblue** [comment]
Against `release` branch (will become 1.13.7): http://rwjblue.jsbin.com/vofalu/1/edit?html,js
```
testParent.timedPoke()
9
testParent.copyLeak(10000)
undefined
testParent.timedPoke()
692
testParent.copyNoLeak(10000)
testParent.timedPoke()
undefined
141
```

After `copyNoLeak` time reduces from 692 to 141.
