### ISSUE TITLE
transition.retry() only captures previous router state if transition was aborted.

### ISSUE THREAD

**Issue by TrevTheDev** [emberjs/ember.js#5208]
transition.retry() does not seem to be always working [In this example](http://jsbin.com/radok/5/). If one follows the links sequentially and then finally clicks the button to do a transition.retry() the URL reflects that product is 'undefined'.

**Comment by rwjblue** [comment]
I do not think that `transition.retry()` is documented to work in this way (i.e. we only document calling `.retry()` after an `.abort()`).  I agree that it would be nice to actually work, and I would happily accept a PR fixing, but there doesn't seem to be much activity here so I'm going to close for now...

**Comment by dwickern** [comment]
I worked around this by replacing `transition.retry()` with:
```
function * params(transition) {
  for (const info of transition.handlerInfos) {
    for (const value of Object.values(info.params)) {
      yield value;
    }
  }
}

const { url, name, queryParams } = transition.intent;
if (url) {
  this.transitionTo(url);
} else {
  this.transitionTo(name, ...params(transition), { queryParams });
}
```
