### ISSUE TITLE
Cannot access computed properties on itemController after sorting multiple times

### ISSUE THREAD

**Issue by blessenm** [emberjs/ember.js#5239]
I am trying combine sorting + filtering on an array controller. Its works in the beginning. But If I keep changing the sortProperties, the template fails to render CP's from the item controller.

[Here is a failing bin.](http://emberjs.jsbin.com/qoyim/5/edit) (Click the sort button multiple times, the template stops showing the computed properties from the item controller)

I already asked about this on SO. [Here is the link](http://stackoverflow.com/questions/24967367/ember-sorting-fails-after-couple-of-times/) There are multiple work arounds to get this working. Its listed in the answers and comments on SO. But I feel that this should just work as it works OK in the beginning.

I am not sure if this is related to #4308. I tried to debug this myself but ember's computed code is out my league.

**Comment by josephchappell** [comment]
+1

**Comment by blessenm** [comment]
Based on @stefanpenner response on https://github.com/emberjs/ember.js/issues/5267 I dont think this issue will be fixed. @wagenet is this correct? If so, we could close this issue.
