### ISSUE TITLE
Cleanup/refactor CollectionView and ArrayController

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember.js#5267]
These two things are pretty tightly coupled, but we may want to split this up more.

---

* [ ] CollectionView does not work with itemController - #4137 
* [ ] Be able to sort ArrayController by computed property in itemController - #4308

**Comment by albertjan** [comment]
:+1: would like to be able sort an array on the computed property of the item controller.

**Comment by stefanpenner** [comment]
array controller / itemControllers are deprecated and will go away in 2.0. I don't believe we will be fixing this.
