### ISSUE TITLE
Rendering hierarchy out of place, toggleProperty toggles all items in array when called on itemController.

### ISSUE THREAD

**Issue by philn5d** [emberjs/ember.js#5330]
2 issues:

1. Updated to latest, now the plus (toggleProperty action) causes each item in the array to toggle.

2. Nested components/views rendering out of place when clicking from ma1 to ma2 (or similar). Reloading the page causes proper rendering.

http://jsbin.com/wijigo/1/edit

**Comment by stefanpenner** [comment]
itemController and arrayControllers are deprecated
