### ISSUE TITLE
HistoryLocation doesn't use baseURL correctly

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/ember.js#5334]
`Ember.HistoryLocation` [sets](https://github.com/emberjs/ember.js/blob/6615f727deac55e5cc96c489aa57568835826fdd/packages/ember-routing/lib/location/history_location.js#L30) `baseURL` to `jQuery('base').attr('href') || ''`. That means that `baseURL` is something like `https://mysite.com/root/`.

That's totally reasonable, except `HistoryLocation#getURL` [uses](https://github.com/emberjs/ember.js/blob/6615f727deac55e5cc96c489aa57568835826fdd/packages/ember-routing/lib/location/history_location.js#L62-L68) `baseURL` as if it were just a *path*. That is, it calls (more or less) `location.pathname.replace(baseURL, '')`. `location.pathname` will never include the protocol and domain, so that `replace` will never do anything.

I believe the correct thing to do would be to extract `rootURL` from `baseURL` on initialization:

```js
rootURL: null,

init: function() {
  var location = get(this, 'location') || window.location;
  set(this, 'location', location);

  var baseURL = get(this, 'baseURL') || jQuery('base').attr('href') || '';
  set(this, 'baseURL', baseURL);

  var origin = location.origin ||
               "%@//%@%@".fmt(location.protocol, location.hostname, (location.port ? ':' + location.port : ''));
  var rootURL = get(this, 'rootURL') ||
                baseURL.replace(origin, '');
  set(this, 'rootURL', rootURL);
},
```
Then, only use `rootURL` in `getURL`:
```js
getURL: function() {
  var location = get(this, 'location'),
      path = location.pathname,
      baseURL = get(this, 'baseURL');

  baseURL = baseURL.replace(/\/$/, '');
  var url = path.replace(rootURL, '');

  return url;
},
```

**Comment by rwjblue** [comment]
@jayphelps / @jamesarosen - Is this still an issue?  Any chance one of you would try whipping up a PR?

**Comment by jayphelps** [comment]
@rwjblue I don't have the cycles to dig in right now :disappointed:

**Comment by jamesarosen** [comment]
Yes, I can take this on. Our next sprint starts next Monday. I can try to slate it in there.

**Comment by jamesarosen** [comment]
OK, so my plan is

## AutoLocation

 * add `rootPath`
 * change `rootURL` to return `rootPath` and emit a deprecation warning
 * change the rest to use `rootPath` instead of `rootURL`

## HistoryLocation
 * keep `baseURL`, but use `.prop('.href')` so it's always a full URL
 * add `rootPath`
 * change `rootURL` to return `rootPath` and emit a deprecation warning
 * change the rest to use `rootPath` instead of `rootURL`

**Comment by sandstrom** [comment]
@jamesarosen this would be a great addition, happy when I saw a fix is in the works! :boat:

**Comment by locks** [comment]
@jamesarosen anything happening here?
cc @rwjblue

**Comment by jamesarosen** [comment]
I had a [PR](https://github.com/emberjs/ember.js/pull/12338), but it lingered and was closed. I stopped working on the app that this was a problem for about a year and a half ago.

**Comment by locks** [comment]
@jamesarosen thanks for the work! I'm closing this issue, sorry the PR didn't get merged at the time.
