### ISSUE TITLE
CoreObject.reopen doesn't handle actions hash

### ISSUE THREAD

**Issue by davewasmer** [emberjs/ember.js#5394]
I would expect:

```js
Ember.Route.reopen({
  actions: {
    someActionName: function(){
      alert('Firing someActionName')
    }
  }
})
```

to cause all Routes to have an action called `someActionName`. Instead, it seems that the action isn't picked up by instances of the reopened class. Here's a [JSBin with the setup](http://emberjs.jsbin.com/husomupahidi/1/edit).

Not sure if this is intended functionality or a bug. Even if it's intended, it would be useful to call that out in the docs somewhere, especially since extending classes with an actions hash, or even mixing in an actions hash, works as expected ([jsbin](http://emberjs.jsbin.com/wacawacogiho/1/edit)):

```js
ActionMixin = Ember.Mixin.create({
  actions: {
    mixedInAction: function(){
      alert('mixed in action - this will fire')
    }
  }
})

App.IndexRoute = Ember.Route.extend(ActionMixin, {
  
  actions: {
    mixedInAction: function(){
      alert('subclassed action - this will fire')
      this._super()
    }
  }
  
})
```

**Comment by Asgaroth** [comment]
This also happens when extending regulary not just with `reopen`

This would work ([jsbin](http://emberjs.jsbin.com/makeka/1/edit?js,console
http://emberjs.jsbin.com/mivosu/1/edit?js,console)):

```javascript
var Actionable = Ember.Object.extend(Ember.ActionHandler);
var someTarget = Actionable.extend({ actions: ... }).create();
```

But this won't ([jsbin](http://emberjs.jsbin.com/mivosu/1/edit?js,console
)):

```javascript
var someTarget = Ember.Object.extend(Ember.ActionHandler, { actions: ... }).create();
```

**Comment by Asgaroth** [comment]
I have been debugging this down to [mergeMixins](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/mixin.js#L280) it seems that `ActionHandler` sets the `willMergeMixin` on the prototype only after the current mixin chain has been applied, so it doesn't get the chance to modify an `actions` hash that is part of the same mixin chain.

When  extending from another class `willMergeMixin` already exists in the [base](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/mixin.js#L298) and at that point it can safely work with the `actions`.

I cannot think of an easy way to fix, seems to me that not so many people mix `ActionHandler` often. 

Do you guys thing this is important to fix in code, or maybeupdate [the docs](http://emberjs.com/api/classes/Ember.ActionHandler.html) to specify that this mixing only works when applied to *"Abstract"* classes?

**Comment by mixonic** [comment]
`reopen` is a minefield, and `actions` initialization is also unfortunately a minefield.

There has been discussion about deprecating `reopen`, or at least deprecating it after an instance has been created. I think they real answers lie there.

**Comment by davewasmer** [comment]
@mixonic not sure I follow - why would `reopen` be deprecated? I use it extensively in addons especially - the ability to modify a class after initializing is hugely useful. I could understand throwing a warning if an instance has already been created (I assume mixins applied via `reopen` don't impact any existing instances?).

**Comment by mixonic** [comment]
I'm personally wary of using `reopen` in an addon to change Ember base classes. It will quickly open your library up to conflicts with other libraries. Instead I suggest exporting an extended version of the Ember class. I don't want to nit pick the specifics here though.

The class model maintains a lot of complexity to allow reopening of a class already instantiated. We can improve the performance of Ember as a whole if we don't do this.

**Comment by sir-dunxalot** [comment]
@mixonic So do you do something similar to the method of extending an Ember addon's base classes by registering the view in the Ember namespace at a path like `ember/views/base.js` that your app will automatically use?

Or, for example, instead of reopening `Ember.View` and then extending your app's view's from  `Ember.View`, you'd export a new view called something like `BaseView` and extend all of your app's views from `BaseView`? For example:

```
// views/base.js
import Ember from 'ember';

export default Ember.View.extend({
  // Stuff you would have done in reopen here
});
```

```
// views/index.js
import Ember from 'ember';
import BaseView from 'app-name/views/base';

export default BaseView.extend({
});
```

**Comment by mixonic** [comment]
@sir-dunxalot exactly. Better yet the functionality can be exported as a mixin instead of a base class. That way you can merge the behaviors of several mixins from several addons.

**Comment by oriSomething** [comment]
@mixonic i use the `reopen` feature so i can monitor when every time there is a `component` / `view` that had `didInsertElement`. do you have a recommendation how to do that without `reopen`?

**Comment by Asgaroth** [comment]
@oriSomething what is it you need to do with those components/views?

**Comment by oriSomething** [comment]
@Asgaroth i use it to inform `<iframe>` parent that it needs to resize. i have every edge case that i have to use an `<iframe>`, and a scrollable `<iframe>` is not good for this case and as far as i search there is no resizable `<iframe>`.
if i had to create a child class to `view` / `component`, it would mean i can only use my `component`s / `view`s

**Comment by sir-dunxalot** [comment]
@mixonic Whilst I agree with most cases of reopen being equally as maintainable as mixins or class extensions a valid use case for `reopen` is A/B tests. We have an A/B testing framework where each test has a mixin with methods/properties that change the class' original functionality. We use reopen something like:

```
export default Ember.Controller.extend({

  checkForTest: function() {
    if (this.get('testID')) {
     this.reopen(this.get('container').lookup('someMixinWithTestID'));
   }
  }.on('init')

});
```

That would fall into the category of running after the original class has initiated. I don't see an Emberish alternative and ES6 doesn't allow for dynamic module names (though it's hackable). Thus, one would argue for `reopen()` to exist in some form - maybe there's another way?

I don't mean to get off topic but if we believe the root of this issue is in the `reopen()` method I think this discussion is acceptable (maybe I'm wrong?).

**Comment by klclee** [comment]
I just got bitten by this too! :+1: for just using ```actions``` I think it will make more sense to new people coming to the framework. So you just learn what ```reopen``` means then that's it...

**Comment by BenjaminHorn** [comment]
I run into this problem too. See #11477. 
+1 to make change _actions to action.

**Comment by stefanpenner** [comment]
We should revisit this, as part of how ember objects look in the land of ES6 classes.

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/12028 moves `_actions` to `actions`.
