### ISSUE TITLE
Input type=checkbox isn't a component

### ISSUE THREAD

**Issue by ctataryn** [emberjs/ember.js#5433]
Although this issue was closed (https://github.com/emberjs/ember.js/pull/3935), I think it would be worthwhile to support `{{input type="checkbox" action="someaction"}}`.

In developing my app I could not actually wire up an action to a checkbox in this manner.

Although according to the referenced issue this would be a "breaking change", I believe it would add symmetry (and reduce confusion)

cc @stefanpenner (this even confused the mighty one)

**Comment by petrvolny** [comment]
Any news on this one?

**Comment by Restuta** [comment]
Yeah, just got hit by that..

**Comment by stefanpenner** [comment]
- [ ] see what glimmer changed here
- [ ] we MUST fix this for 2.0

**Comment by ef4** [comment]
I reviewed this on the glimmer branch, it is not yet fixed. Checkbox still inherits `View` and not `Component`, despite being registered in the container under the name `component:-checkbox`.

**Comment by stefanpenner** [comment]
cc @tomdale @wycats

**Comment by ronco** [comment]
:+1: would love to see this behavior consistent in 2.0.

**Comment by SirZach** [comment]
just want to comment on @rwjblue x-checkbox component, you need to add <code>'checked'</code> to the <code>attributeBindings</code> array if you want to be able to programmatically set the checked value of the element. You'll also need to pass it in: <code>{{x-checkbox checked=propertyBoundToCheckedState}}</code>.

**Comment by valk** [comment]
Hi guys, please explain to me how should I use input checkbox in my component so it will eventually work? You guys are doing a great work, but new users of ember.js are stuck with these issues an they are undocumented. I could add the steps into guides if you explain me what should I do. I found an answer of @hewsonism on (http://stackoverflow.com/questions/24154974/trigger-an-action-on-the-change-event-with-ember-js-checkbox-input-helper) but even there I don't understand how to use the code. I'm a newbie and I've read a large part of the guides, but apparently that's not enough. Any help will be greatly appreciated.

**Comment by JKGisMe** [comment]
Wasted *so* much time on this. 

At least put a warning, in bold, in the docs. It's a little misleading considering the 'actions' usage is explained only a line before 'checkboxes' on the Input Helpers guide page.

**Comment by SirZach** [comment]
@JKGisMe i feel ya, don't give up on ember due to this problem. i fully believe ember core team is going to make this a non-issue with ember 2.0!

**Comment by JKGisMe** [comment]
Well, I have a working, saving to the backend, checkbox. I used combination of the x-checkbox JSBin here and the explanation at http://www.thesoftwaresimpleton.com/blog/2015/02/12/emberjs-data-down/  The explanation was really helpful.

I don't know when Ember 2.0 will come out but it seems like a slippery slope to delay workable solutions. Especially when the situation is not well documented. It's already hard enough for a noob when the internets are full of the 'old Ember way' and you're trying to implement things in the 'new Ember way'. There is no reason something like this checkbox debacle couldn't have been included on the Ember guides. Checkboxes are a pretty basic element.  I guess I find this to be equal part issue with Ember itself and issue with Ember documentation.

**Comment by rwjblue** [comment]
> I don't know when Ember 2.0 will come out

The [recent blog post](http://emberjs.com/blog/2015/05/10/run-up-to-two-oh.html) should provide more detail.

**Comment by Restuta** [comment]
@JKGisMe this is open source project, so please help to improve documentation or really anything in the code. Community would greatly appreciate that.

**Comment by knownasilya** [comment]
@rwjblue thanks for that link.

**Comment by JKGisMe** [comment]
@Restuta I spent half my Sunday trying to make a checkbox. I don't think Ember wants me touching their code. ;)

Since Ember 2.0 is so close. Let's just pause our work projects and come back after it's here. We can contribute to Ember in the meantime.

**Comment by jfelchner** [comment]
I just ran into this and spent an hour on it until I gave up and finally found this.  I hope this gets fixed for 2.0.

**Comment by rwjblue** [comment]
Fixed in #11396

**Comment by JKGisMe** [comment]
Yay, future generations of ember noobs will not know the struggle. :+1:

**Comment by gzurbach** [comment]
Hey guys, quick question here to clear out some confusion. I was looking at the code change (#11396) to make checkbox extend from `view` to `component` and I was wondering what the implications are...

Does this change mean that with the next release of Ember we will be able to write:
```
{{input type="checkbox" value=isChecked action="foo"}}
```
If so, when will `foo` be triggered? On `change` or on `click` or... something else?

Related question: are we gonna be able to write something like:
```
{{input type="checkbox" value=isChecked action="foo" on="click"}}
```

My issue right now is that I'd like to be notified when the user toggles the checkbox but not when I programmatically change its value. The only way for now to be notified of a change is to set an observer on the checkbox's value. But this is being triggered both when the user clicks on the checkbox **and** when I toggle its value programmatically. I was therefore wondering is that change will help me accomplish what I'm trying to do.

**Comment by stefanpenner** [comment]
in ember 1.13.3 you can do the following

```
<input type="checkbox" value={{isChecked}} onclick={{action "foo" value="target.checked" />
```

**Comment by gzurbach** [comment]
Awesome, I will do that then. Thanks for your quick reply @stefanpenner, as always!

**Comment by tcjr** [comment]
@stefanpenner After an embarrassing amount of debugging, I can verify this should be 

```
checked={{isChecked}}
```

instead of 

```
value={{isChecked}}
```
