### ISSUE TITLE
Applied mixins do not define the __nextSuper property correctly

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#5463]
See [jsbin](http://emberjs.jsbin.com/xuwag/1/edit?js,output).

```JavaScript
var item = { foo: 'bar' }
var array = [item];
var MyArrayMixin = Ember.Mixin.create({
  contains: function(){
    return this._super();
  }
});

MyArrayMixin.apply(array);

// Should be true, false is false, false
console.log(
  array.hasOwnProperty('__nextSuper'),
  array.propertyIsEnumerable('__nextSuper')
);

array.contains();

// Should be true, false is true, true
console.log(
  array.hasOwnProperty('__nextSuper'),
  array.propertyIsEnumerable('__nextSuper')
);
```

Currently `__nextSuper` is defined in the `makeCtor` function, which is only called when creating a new object. Array are really just mixins applied to array instance, and as such never call the constructor. `__nextSuper` should be set on them during instantiation with the correct non-enumerable configuration.

Is similar to #4970, but this is for the general case. That specific issue on `contains` was addressed by #5444.

Could be addressed by #5430. May ref #5464

**Comment by rwjblue** [comment]
Closed by https://github.com/emberjs/ember.js/pull/12062.
