### ISSUE TITLE
Calling _super on a frozen object results in a violation of the freeze

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#5464]
In 1.5, it was possible to:

```JavaScript
var a = Ember.A([]);
var MyArrayMixin = Ember.Mixin.create({
  contains: function(){
    return this._super();
  }
});
MyArrayMixin.apply(a);
Object.freeze(a);
a.contains();
```

By 1.6, this raised an exception about modifying the frozen object. The exception is raised by `__nextSuper`, though `__nextSuper` was already in 1.5.

http://emberjs.jsbin.com/mixowa/1/edit?html,js,output

Replaces #5324 as a general case, could be addressed by #5430. May ref #5463.

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/12062.

Demo: http://emberjs.jsbin.com/yonuvi/edit?html,js,output
