### ISSUE TITLE
Route with query-parameters that reject the model, doesn't fire the error state with history router

### ISSUE THREAD

**Issue by Costent** [emberjs/ember.js#5478]
My index route has a query parameter with the `refreshModel` option set to true.
The model of this route, always fails (for test purpose only of course).

An exemple can be found here : http://emberjs.jsbin.com/cuvama/10/
As expected, the application go to the error state. But if you add query parameter, then the application doesn't go the error state. Try this link > http://emberjs.jsbin.com/cuvama/10/?foo=bar.

Note that it only happens when the query parameter is in `refreshModel` mode and when the router location is `history`.

**Comment by rwjblue** [comment]
Updated the provided JSBin here: http://rwjblue.jsbin.com/nutare/edit?html,js

Seems to be properly using the error template when a query param is used. Closing...
