### ISSUE TITLE
Query params set before model promise has resolved

### ISSUE THREAD

**Issue by opsb** [emberjs/ember.js#5479]
Been trying out beta 1.8.0-beta.1, it looks like query-params are set on the controller before the model hook has resolved (when using a promise). I'll try to put a jsbin together for it. I presume the intended behaviour is that the model hook and setupController should be called before the query-params are set?

**Comment by machty** [comment]
This is pretty old, closing for now; I'm tempted to say I'd reopen if a breaking JSBin were provided but I think this and other bugs are all going to be fixed in an upcoming QP facelift, possibly when the API shifts toward routeable components.
