### ISSUE TITLE
No "change" event in inputs or textareas

### ISSUE THREAD

**Issue by aexmachina** [emberjs/ember.js#5492]
This is quite a handy event - it indicates that focusOut has happened *and* that the value has changed. The only way to achieve this AFAICT is to store the previous value and compare, which is pretty tedious. Also it seems quite unexpected that `focus-out="doSomething"` works, but `change="doSomething"` doesn't.

I know that I can use observers, but in my case I only want to run the action on focusOut.

**Comment by sandstrom** [comment]
@aexmachina I think this works now: http://guides.emberjs.com/v2.0.0/templates/input-helpers/#toc_actions

Feel free to close this issue if you feel that this has been resolved.

**Comment by aexmachina** [comment]
I've tried this but it doesn't appear to work. Also, there's no mention of the `change` event in the doc link you sent.

I'm using the latest ember-cli and components/ember#canary. I can send you the example project, but it's as simple as this:

templates/application.hbs

```
{{input change='foo'}}
```

If I change this to `{{input key-press='foo'}}` it works.

controllers/application.js

```
import Ember from 'ember';

export default Ember.Controller.extend({
  actions: {
    foo: console.log.bind(console)
  }
})
```

A few other things:

- The action seems to receive only the last value, not an `Event` instance as indicated in the docs
- The same behaviour happens when I use a component
- Is there a JSBin template that can be used for Ember 2? I've always used emberjs.jsbin.com in the past, but this is using Ember 1.13.5

**Comment by rainerfrey** [comment]
Why has this simply been closed? I'm missing exactly this feature right now. IMO the request is reasonable, no-one has objected to that, and there was even a pull request. And still, it was closed without even any reasoning as to why not supporting it.

At least it could be kept open, if there is no time to fix it now.
