### ISSUE TITLE
Ember testing, wait for modal window

### ISSUE THREAD

**Issue by lrdevries** [emberjs/ember.js#5494]
In my application i use bootbox (http://bootboxjs.com/) for confirming to delete some models.
In my test i click on the button with an {{ action }}, in this action i open a bootbox.
In the text i click the OK button on the bootbox.

But the andThen method does not wait for the bootbox to dissapear. The check if a model is removed is therefore always false. I tried to return an promise but the andThen helpen also doesn't wait for promisses.

Is there a way to let the test wait untill the promise of the bootbox is resolved, or the callback of the bootbox is finished?

Extra information:
My template is:
```
        <button class="btn btn-default" {{action 'askDelete' target="view"}} data-toggle="tooltip" data-placement="right" {{translateAttr title="trips.remove"}}><i class="fa fa-trash-o"></i></button>
```

My View is:
```
	actions: {
		askDelete: function(){
			var self = this;
			self.$('td').slideUp('500').promise().then(function(){
				self.get('controller').send('delete');
			});
		}
	}
```
My controller:
```
    actions: {
        save: function(){
                    self.get('content').save().then(function(){
                    self.get('controllers.history').transitionToPrevious('trips.index');
                });
```

My test:
```
    click(".specific-row .action-buttons button");

    andThen(function() {
        // Check if the row is indeed removed from the table
        ok(find(".content-row table tr:contains('content-of-row')").length === 0, "deleted and removed from the table");
    });
```

But the latest ok is called before the save action in the controller is triggered, and therefore alwasy false.

**Comment by benkiefer** [comment]
Sorry to wake this back up, but is there a best practice for this? We are seeing the same issue when launching a foundation modal from an action:

     actions: {
         openModal: function () {
               $("#some_modal_id").foundation("reveal", "open");
         }
     }

**Comment by michaeldeitcher** [comment]
I'm running into this issue as well benkiefer.

**Comment by lrdevries** [comment]
If i remember correctly i noticed a difference between click($(..)); and $(..).click();. And if i'm right i solved it with this.

**Comment by benkiefer** [comment]
$(..).click() works occasionally for me. I ended up solving it with the answer to this question:

http://stackoverflow.com/questions/25512168/async-call-in-ember-testing

My code looks like this:

     click("#modal-launch-btn");

     andThen(function () {
         waitFor(function () {
             assert.ok(!find("#myModal").is(":hidden"));
         });
     });


runAndWaitFor looks like this:

     function waitFor(callback, timeout) {
         timeout = timeout || 500;
         stop();
         Ember.run.later(function(){
              callback();
              start();
         }, timeout);
     }

Which basically just means I pause the test and take a nap. Not ideal, but at least I can test drive my modals now.

**Comment by michaeldeitcher** [comment]
Thanks @benkiefer

**Comment by rwjblue** [comment]
From the last few comments this issue looks to be resolved.
