### ISSUE TITLE
mapBy produces OUT_OF_RANGE_EXCEPTION on App.reset() if model was set to null

### ISSUE THREAD

**Issue by kbullaughey** [emberjs/ember.js#5500]
I ran into a problem using mapBy like so:

    App.ThingController = Ember.ObjectController.extend({                                                 
      componentNames: Ember.computed.mapBy('components', 'name')                                          
    });

When I do an `App.reset()` after setting the controller model to null, there is an  `OUT_OF_RANGE_EXCEPTION` exception raised in `MutableArray#removeAt`. It's not a problem unless I do App.reset(), so it only surfaces in my specs.

I've coded up a [full gist demonstrating the issue](https://gist.github.com/kbullaughey/d2b821803fead471cf62).

I'm using ember data beta.9 and the latest ember canary. This problem only surfaced when I upgraded from ember data beta.8 to beta.9. 

The workaround is to not use mapBy and manually make a computed property do what I want.

**Comment by rwjblue** [comment]
`mapBy` has been rewritten in 2.0.0+ to avoid usage of reduce computed / array computed.  This was likely fixed with that refactor.  Closing now, but will reopen if a failing JSBin/ember-twiddle is shared.
