### ISSUE TITLE
Timing of query-params updates to controllers can be confusing with deep slow route models

### ISSUE THREAD

**Issue by go1dfish** [emberjs/ember.js#5506]
JSFiddle here:

http://jsfiddle.net/a21e0508/11/

Actual demonstration of problem requires manually hitting a route directly via this url:

http://fiddle.jshell.net/a21e0508/11/show/#/developers/1?search=Alex

The weirdness I'm trying to demonstrate here, is that if loading routes are used; and a route below a query parameters route takes a while to resolve this prevents the query params from updating on the lower level controller until the deeper routes resolve.

If you are doing client side filtering this can cause weird issues, like double renders etc...

At the link above you should see the list of all developers render initially (even though search=Alex is passed in the url) before filtering down to the desired results.

To further demonstrate problems this can cause, the deep route is attempting to use the controller with query params to do the search, expecting that the query params would have been updated in the shallower route allowing the use of controller filtering code.

In my actual application the interactions are a lot more complex and difficult to describe, but I think this fiddle touches on the core of the problems I've been running into.

Earlier versions (1.7.0-beta.1+canary.f77bb11d) of the query params did not exhibit this issue as far as I can tell.

**Comment by mdentremont** [comment]
+1

**Comment by Serabe** [comment]
Marking issue a inactive as per our [triage policy](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy).

**Comment by pixelhandler** [comment]
Closing as previously marked inactive
