### ISSUE TITLE
currentRouteName return previous route name in didTransition hook

### ISSUE THREAD

**Issue by hwwan80** [emberjs/ember.js#5533]
The following code
```
`import Ember from 'ember'`
route = Ember.Route.extend
 actions:
    didTransition: ->
         currentRoute = @controllerFor('application').get('currentRouteName')
         console.log "current Route = #{currentRoute}"
`export default route`
```

return the route of previous Route instead of the current Route  due to Router.updatePaths is called after the didTransition hook. The name of the hook "didTransition" indicate the route transition is completed. So return the previous route name in the currentRouteName property seem confusing.

**Comment by bndw** [comment]
Also verified

**Comment by gdub22** [comment]
The `run.next` hack is even unreliable

**Comment by ear** [comment]
I do not have a codebase to try this on anymore but here is an idea that ones who do might try to copy to see if it works for them on their codebase:

ember-crumbly (a breadcrumbs component add on by @poteto) [uses injection](https://github.com/poteto/ember-crumbly/blob/develop/addon/initializers/crumbly.js) to access `currentRouteName` and then [makes a computed property](https://github.com/poteto/ember-crumbly/blob/develop/addon/components/bread-crumbs.js#L31) on top of it.

I do wonder: does the issue still present itself in your app when the information is gathered in this particular way?

**Comment by gdub22** [comment]
Looks like accessing `currentRouteName` directly on the router instance is reliable.  However, `url` is not in sync.
```js
didTransition() {
  this._super(...arguments);

  Ember.run.once(this, function() {
    console.log(this.currentRouteName); // accurate
    console.log(this.get('url')); // stale
  });
}
```

**Comment by rwjblue** [comment]
This needs to be turned into an RFC to expose the routing service (instead of folks grabbing this out of the application controller which will be going away anyways).  

Closing in favor of future routing service RFC.
