### ISSUE TITLE
Rendering 'into' an ancestor template and then navigating back raises exception

### ISSUE THREAD

**Issue by mziwisky** [emberjs/ember.js#5542]
If you have a nested resource that you try to render into an ancestor (higher than the parent), then navigate back in the browser, Ember raises `Cannot read property 'connectOutlet' of undefined`

Seems to have something to do with route.router._lookupActiveView() being called to try to find a view that isn't actually active.

See this jsbin for a minimal example:  http://emberjs.jsbin.com/kipefiyeyuxo/1/edit?html,js,output

**Comment by alexdiliberto** [comment]
Little confused why this one is closed? I ran into a similar issue recently (Except mine is IE9 only) and I'm still looking for the optimal solution, @mziwisky has a valid point from everything I'm reading.

**Comment by rwjblue** [comment]
I updated the JSBin to use Ember 2.5.0, and all seems to be working properly (no errors thrown): http://rwjblue.jsbin.com/nejaxa/edit?html,js.

Closing (again ;P )....
