### ISSUE TITLE
Cannot read property of undefined error in chains.js caused by model with capitalized attributes.

### ISSUE THREAD

**Issue by ajbogh** [emberjs/ember.js#5570]
Ember fails to transition routes when it tries to clean up objects with capitalized object properties.

This plnk shows how it should work: http://plnkr.co/edit/v1h2QrHY905R34CGMHaR?p=preview

Here is the same code with capital letters for the model object's properties: http://plnkr.co/edit/t8P09exDLz1VTEG8IR9p?p=preview

I would consider this a bug is that we cannot guarantee that the model won't have capitalized properties. Ember should be able to clean up models that have capitalized properties which are objects themselves.

**Comment by rwjblue** [comment]
Works without error in 2.0.0: http://plnkr.co/edit/SIVZZqZdo61u39Ol3DZd?p=preview
