### ISSUE TITLE
Fast track transition.abort() promise rejection

### ISSUE THREAD

**Issue by kanongil** [emberjs/ember.js#5589]
The `abort()` method will tell the transition that it is aborted but if it is busy fetching a model or similar, the promise won't reject until the fetching is complete. This is later than I would expect.

This behavior actually works fine most of the time, e.g. when the transition is aborted to start another transition, or is aborted before it begins fetching the model. However, it becomes problematic when you have a visual loading indicator and you want to enable the user to abort slow loading routes by pressing the escape key (standard browser behavior). In this case there is no immediate hook that will notify that the transition has been aborted, and allow me to cancel the indicator.

I see 2 ways to fix this issue. Either follow my suggestion and somehow reject the promise immediately, or add an additional hook like `didAbortTransition`.

**Comment by rwjblue** [comment]
@machty - Thoughts?

**Comment by kanongil** [comment]
Any update on this? I think that this is a useful feature, and if need be I am willing to implement it myself. 

However, I do need some feedback as to which direction is the most viable.

**Comment by rwjblue** [comment]
A `didAbortTransition` hook seems reasonable to me for this.

@kanongil - I'd happily review a PR implementing.  The new API will need to be feature flagged.

**Comment by Serabe** [comment]
I am closing this. If any of the participants are interested on pursuing this feature, feel free to reopen.

Thank you!
