### ISSUE TITLE
Changing query param to default value & 'appController.currentRouteName'

### ISSUE THREAD

**Issue by asaf** [emberjs/ember.js#5598]
I have some nested routes such:

`resource 'level1' -> resource 'level2', resource 'level3'`

The controller of level3 have a query param with default value and route's `refresh` is invoked when it changes.

When changing the query param value the route gets refreshed and observing `appController.currentRouteName` changes to the correct value (i.e level1.level2.level3)

But when changing the query param value back to its original value, the `appController.currentRouteName` changes to `level1.level2`

This only happens when returning back to the default query param value defined initially in the controller.

@machty Thoughts?

**Comment by rwjblue** [comment]
Closing for now.  Happy to reopen with a reproduction.
