### ISSUE TITLE
Inconsistent behaviour when calling helpers more than once from another helper

### ISSUE THREAD

**Issue by domchristie** [emberjs/ember.js#5602]
The first call to a view helper behaves as expected. Successive calls render, but don’t appear to observe the passed in options, as demonstrated here: http://emberjs.jsbin.com/masara/6/edit

    Ember.Handlebars.registerHelper('wrapping-helper', function (options) {
      Ember.Handlebars.helpers.view.call(this, App.MyChildComponent, options);
      Ember.Handlebars.helpers.view.call(this, App.MyChildComponent, options); 
      Ember.Handlebars.helpers.view.call(this, App.AnotherChildComponent, options);
    });

Tested with Ember v1.7, 1.8beta, and Canary, Handlebars v1.3.0

**Comment by stefanpenner** [comment]
helpers calling helpers is no more
