### ISSUE TITLE
Ember observer on Ember.computed.alias throws "some of the associated records were not loaded" error

### ISSUE THREAD

**Issue by DEfusion** [emberjs/ember.js#5623]
With these models:

    App.Foo = DS.Model.extend
        bars: DS.hasMany('bars', {inverse: 'bar'})
        type: DS.attr('string')

    App.Bar = DS.Model.extend
        foo: DS.belongsTo('bar', {inverse: 'foos'})

        type: Ember.computed.alias('foo.type')
        value: DS.attr('string')

        defaultValueForType: (->
            # Logic here to set a default value based on the type if not set.
            # The line getting the type throws the error
            type = @get('type')
        ).observes('type')

This throws the following error:

    Assertion Failed: You looked up the 'foo' relationship on a 'bar' with id 1 but some of the associated records were not loaded.

The data is all sideloaded as part of a bigger request for something further up the chain of objects. If I comment out the defaultValueForType everything works and the ember inspector shows all the foo's loaded as expected.

This wasn't happening on Canary from June and I have just upgraded to ember 1.7 and ember-data 1.0.0-beta.10 to fix another issue I was having.

I've figured out a fudge workaround for now instead of doing `@get('type')` I can do 

    @get('_data.foo.type') 

Trying to observe on `foo.type` and/or `@get('foo.type')` didn't make any difference to the error.

**Comment by rwjblue** [comment]
Closing this issue.  Will happily reopen with a reproduction against current versions of ED and Ember.
