### ISSUE TITLE
Reduce computed macros don't get delta callbacks from aliased DKs

### ISSUE THREAD

**Issue by kumavis** [emberjs/ember.js#5650]
`Em.computed.sort` and other macros utilize the delta callbacks `addedItem` and `removedItem`

These callbacks are not triggered when the DK is an alias of an array.

```
originalArray -alias-> newArray -sort-> sortedArray (BROKEN)
originalArray -sort-> sortedArray (CORRECT)
```

**Comment by stefanpenner** [comment]
RC/AC is gone, in-favor of glimmers data diffing, and naive sort/filters
