### ISSUE TITLE
Ember's enumerable `contains` should align with ES7 Array#contains.

### ISSUE THREAD

**Issue by jdalton** [emberjs/ember.js#5670]
At the moment Ember's [contains](http://emberjs.com/api/classes/Ember.Array.html#method_contains) does not match `NaN` values or support a `fromIndex` like the [ES7 Array#contains](https://github.com/domenic/Array.prototype.contains/blob/master/spec.md) does. This can cause an inconsistency when Ember adds `Array.prototype.contains`.

**Comment by wycats** [comment]
@jdalton :+1:
