### ISSUE TITLE
queryParams doesn't work with lazy loaded code

### ISSUE THREAD

**Issue by guilhermeaiolfi** [emberjs/ember.js#5672]
Hi,

so, queryParams simply doesn't work with lazy loaded code as shown in this JSBin: http://jsbin.com/fevibahujajo/1#/page/edit?query=test

This is a step backwards from one of the previously queryParams implementation where this code worked fine (I don't remember the flag I had to enable, sorry). And it'll get in the way of making ember more modular so I guess that's something that needs to be fixed.

Meanwhile, is there any possible workaround for this? 

Any hint will be helpful. Thanks.

**Comment by stephenjelli** [comment]
here's an example
http://jsbin.com/rivice/#/page/11?query=test
you can click the link and it won't get the query param.

if you remove the setTimeout it will work fine.

**Comment by stefanpenner** [comment]
Ya this is a known bug. It really should have been a blocker for query params entering the system. I suspect ember 2.0's approach will help solve this issue.

**Comment by Serabe** [comment]
Marking issue a inactive as per our [triage policy](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy).

@stefanpenner is this solved in Ember 2.x?

**Comment by pixelhandler** [comment]
@stefanpenner closing since this has been inactive for some time
