### ISSUE TITLE
Route transition doesn't work when working with modal.

### ISSUE THREAD

**Issue by synthresin** [emberjs/ember.js#9294]
I'm working with modal using tutorial in ember website.

Only difference is that I'm trying to make the 'modal' template have an outlet for another template so make it reusable.

But after I opened modal(rendered modal outlet, exactly), when I try to make transition to another route, It just doesn't work.
but If I write default behavior of renderTemplate in target route. It works again.(I've commented it out in my JSBin)

Is it a bug? or did I handled this.render not properly?

http://emberjs.jsbin.com/romigi/5/edit

**Comment by rwjblue** [comment]
I'm not really sure if this is is a bug or not.

@ef4 - Would you happen to have time to review (you are much more in tune with what we support with outlets)?

**Comment by ef4** [comment]
Thar be dragons in the corner cases of the old named outlet semantics. I don't know if there's a bug here, and if the issue has been silent for 10 months, we should close it, and people can reopen if they have current examples.

The overall takeaway is: stop using named outlets. They give you no benefits over services and components, while creating massive hidden pitfalls.
