### ISSUE TITLE
Ember.Component attributeBindings doesn't work with namespaced attributes? (e.g. xlink:href)

### ISSUE THREAD

**Issue by blesh** [emberjs/ember.js#9298]
The following code produces undesired results:

```js
export default Ember.Component.extend({
  tagName: 'image',

  attributeBindings: ['src:xlink:href', 'x', 'y', 'width', 'height'],

  src: '/mericuh-flag.gif'
});
```

It ends up setting `xlink="/mericuh-flag.gif"` rather than `xlink:href="/mericuh-flag.gif"`

Suggested workaround from @ebryn was to use an observer and manually set, which I'm fine with for now.

**Comment by mixonic** [comment]
@oneeman is going to implement a plan described at https://github.com/emberjs/ember.js/pull/10186#discussion_r22911832, I believe.
