### ISSUE TITLE
reduceComputed recomputes everything on a single change of a dependant property

### ISSUE THREAD

**Issue by ahacking** [emberjs/ember.js#9313]
Please see the following [JSBIN](http://emberjs.jsbin.com/cekakeririta/1/) which reproduces the issue.

If you open the console and then toggle any checkbox, you will see that ``reduceComputed`` first calls ``removedItem`` then effectively throws away the result and calls ``addedItem`` 50 times, thus recomputing based on **all** items in the array.

This doesn't seem to be the expected behaviour, nor does it match the API design which *appears* to be intended to minimize computation.  If it *is* by chance the expected behaviour then ``reduceComputed`` should be simplified and instead just mirror ``Ember.Enumerable.reduce`` and avoid the current complex api.

I would also like to note that it was not at all clear from the documentation what happens when a dependent property changes, is it an ``addedItem`` or a ``removedItem`` or both? or something else not said?  Why isn't there a ``changedItem`` callback? My JSBIN example is my best guess at something that seems to work.  It was only all the question marks that drove me to start logging what callbacks occur that I discovered this issue.

**Comment by stefanpenner** [comment]
RC/AC is gone, glimmer data diffing + simple map/sort/reduce in a CP replaces it, with wonderful results.
