### ISSUE TITLE
Redirect hook on the parent route does not fired in the transition to it from а child route

### ISSUE THREAD

**Issue by nikpachoo** [emberjs/ember.js#9338]
Hi

In the version Ember.JS 1.6.0-beta.4, been fixed:
> [BUGFIX] Don't fire redirect on parent routes during transitions from one child route to another.

This fix causes an error in the following situation ([jsBin](http://jsbin.com/xegugo/2/watch?js,output)):
In  the route "Posts" declared redirect to a child route "post" using the hook "redirect". 
When you first transition to "posts" using navigation, redirect works correctly.
However, if you then use the navigation to go back to the "posts" is expected redirect does not happen, because the method "redirect" is not called.

**Comment by treyhunner** [comment]
This seems to still be an issue in 1.11 ([jsBin][])

[jsBin]: http://jsbin.com/volimufaju/2/

**Comment by rwjblue** [comment]
In the JSBin provided, you should be using `App.PostsIndexRoute` to redirect (instead of manually checking the transition against the current routes name + '.index').

Reworked the JSBin to work properly: http://rwjblue.jsbin.com/zewuna/edit?html,js
