### ISSUE TITLE
Programmatic DOM Manipulation Not Triggering Actions

### ISSUE THREAD

**Issue by jefflage** [emberjs/ember.js#9350]
we are trying to improve our unit test coverage and are adding tests what `click()` on particular DOM elements.  when we use the `click` test helper, nothing happens.  and by nothing, we mean no `actions` get triggered.  if we use jQuery to add a click handler, the click event is happening.  its not just clicking.  using jQuery to enter text into an element also doesn't trigger any actions.

the issues does not seem to be isolated to tests either.  meaning, if in our running application, we use jQuery to click / enter text, the application does not seem to notice.

can you helps us understand why there seems to be this disconnect and what we can do to get it to work?

**Comment by rwjblue** [comment]
Seems to have been resolved already.
