### ISSUE TITLE
Performance Regression from Ember 1.6 to 1.8

### ISSUE THREAD

**Issue by SamSaffron** [emberjs/ember.js#9381]
@eviltrout and myself are looking into perf regressions in ember 1.8. 

To move stuff forward I would like to start a bug here that shows specific regressions.

I "butchered" https://github.com/eviltrout/ember-performance so it now works on 1.5.1 - 1.6.1 - 1.7.0 and 1.8 beta

Running the tests it looks like the "HTML Bindings" test is the worst one off

<strike>
1.5.1 -> 28.9ms
1.6.1 -> 24.2ms
1.7.0 -> 25.9ms
1.8.0-beta -> 135ms 
</strike>

In the "real world" Discourse seems to be running at half speed, we can not afford to upgrade (as much as we would love to) until we resolve this perf regression.

**Comment by rwjblue** [comment]
Closing this (1.8 is a bit old and we have another issue tracking perf issues with 1.13).
