### ISSUE TITLE
Setting meta on computed property replaces existing meta

### ISSUE THREAD

**Issue by ahacking** [emberjs/ember.js#9423]
Currently it is not possible to add your own meta data to a computed property that itself uses meta.

For example, creating properties with Ember Data using DS.attr/DS.belongsTo/DS.hasMany uses meta and therefore it is not available for the application to also use.  This issue is not specific to Ember Data and rather an Ember limitation of the current computed property api [as it simply replaces ``_meta`` with the provided argument](https://github.com/emberjs/ember.js/blob/v1.8.0/packages/ember-metal/lib/computed.js#L273).

My use case is simply needing to track some additional property specific meta data for properties that are dynamically created using Ember Data (which also happens to use meta). Currently I must access ``_meta`` directly on the CP to set my meta data which is evil but given the API its the only solution currently.

I would like to rectify the situation via a PR that allows merging of CP meta data.

Two obvious approaches:
 1. use ``Ember.merge`` to merge in meta data instead of replacing it as the current api does. (Cannot remove keys with this approach).
 1.  add an accessor ``getMeta`` that returns ``_meta`` to allow the caller to manipulate as required.

I prefer option 2, what is the preference and consensus of having such a change accepted?

**Comment by rwjblue** [comment]
I think we came to an agreement here (that merge/assign would be fine), and this would be welcome in a PR with tests.

Closing this issue (since its a bit more like a feature request/proposal)...
