### ISSUE TITLE
Cannot provide custom options.data object to template

### ISSUE THREAD

**Issue by bmeurant** [emberjs/ember.js#9431]
Hi, I tried to add [formatjs](http://formatjs.io/) in an Ember app but it uses `options.data.intl` to store i18n messages (cf. http://formatjs.io/handlebars/#formatMessage) and providing a such object to template seams impossible because `View.render` defines itself `options.data` (https://github.com/emberjs/ember.js/blob/v1.8.0/packages/ember-views/lib/views/view.js#L1048)

Can we imagine a clean integration ?

**Comment by stefanpenner** [comment]
this API is no more.
