### ISSUE TITLE
notifyPropertyChange makes DS.hasMany or DS.belongsTo properties null

### ISSUE THREAD

**Issue by continuata** [emberjs/ember.js#9453]
any call to notifyPropertyChange on a property that is a  DS.hasMany or DS.belongsTo forces that property to null. This is obviously a bug.

e.g.
foo: DS.belongsTo('bar')
...
this.notifyPropertyChange('foo'); // this will force foo to null

**Comment by stefanpenner** [comment]
if this is a problem, it would appear to be an ember-data issue
