### ISSUE TITLE
Ember 1.8 Metal Views creates dummy list elements on reorder

### ISSUE THREAD

**Issue by jasalguero** [emberjs/ember.js#9480]
I found this strange issue when upgraded an application to 1.8:

I'm using jQuery UI to reorder a list through drag and drop. Dragging an element triggers the change of the attribute I'm using to order the list and this triggers a repaint.

With the new version 1.8 Ember seems to create a copy of the element being reordered and inserts it in the target position.

http://emberjs.jsbin.com/relola/1/edit?html,js,output

**Comment by Vincz** [comment]
I can confirm the strange behavior. Also, it seems to bug only when moving item from top to bottom. Moving items from bottom to top doesn't seem to trigger the problem. Also interesting is that the extra items created don't appear in the Ember View Tree (in the debugger extension). It's like if the dom associated to this views wasn't remove.

**Comment by mixonic** [comment]
@Vincz can you confirm this persists in 1.9 and 1.10-beta?

**Comment by Vincz** [comment]
@mixonic Yes, i do. I made the test from the current canary, current beta and current release.

**Comment by jasalguero** [comment]
Ember 1.10 has been released but the issue is still present, any new timeline?

**Comment by stefanpenner** [comment]
should be fixed

**Comment by jasalguero** [comment]
Yay, seems to be working :) http://emberjs.jsbin.com/ximeqatomu/edit?js,console,output

Thanks a lot for the hard work!
