### ISSUE TITLE
Dynamic segment value it's not returned as params attribute

### ISSUE THREAD

**Issue by fnando** [emberjs/ember.js#9486]
Given the following routes definition:

```javascript
App.Router.map(function(){
  this.resource('post', {path: ':slug'}, function(){
    this.route('edit');
  });
});
```

When creating the `AppPostIndexRoute` route like this will fail, since the `params.slug` value will be `undefined`:

```javascript
App.PostIndexRoute = Em.Route.extend({
  model: function(params) {
    Ember.assert('Must define the slug param', params.slug);
  }
});
```

Notice that I can access the slug parameter by accessing `this.paramsFor('post').slug`. Also notice that ember-inspector doesn't list the `post` route path, which is confusing.

![ember-inspector](https://dl.dropboxusercontent.com/s/ti5kreymctc0s1m/2014-11-04%20at%207.40%20AM.png?dl=0)

The expected behavior is that `params` always return the dynamic segment values that are used on a given route.

Here's a sample reproducing this issue: http://emberjs.jsbin.com/latemo/6/edit

**Comment by rwjblue** [comment]
Thanks for explaining @thriqon!
