### ISSUE TITLE
Broken routing in Ember 1.7.0 due to `_qpDelegate`

### ISSUE THREAD

**Issue by herom** [emberjs/ember.js#9496]
I'm using Ember 1.6.1 right now and wanted to upgrade my project step by step to Ember 1.8.1, but as I upgraded to 1.7.0 my routing got broken so that I'm not able to transition to a route out of my current "context". Instead I always get the following Error:

```javascript
TypeError: Cannot set property '_qpDelegate' of undefined
    at EmberObject.extend._reset (http://192.168.0.1:3010/vendor/ember/ember.js:22324:34)
    at applyHook ((http://192.168.0.1:3010/vendor/ember/ember.js:45489:30)
    at callHook (http://192.168.0.1:3010/vendor/ember/ember.js:45483:14)
    at http://192.168.0.1:3010/vendor/ember/ember.js:44193:9
    at forEach (http://192.168.0.1:3010/vendor/ember/ember.js:45373:54)
    at setupContexts (http://192.168.0.1:3010/vendor/ember/ember.js:44189:7)
    at finalizeTransition (http://192.168.0.1:3010/vendor/ember/ember.js:44384:9)
    at http://192.168.0.1:3010/vendor/ember/ember.js:43884:20
    at tryCatch (http://192.168.0.1:3010/vendor/ember/ember.js:45817:16)
    at invokeCallback (http://192.168.0.1:3010/vendor/ember/ember.js:45829:17) 
```

This only happens when I'm in a "nested" route and I want to transition to another route in a different resource. So let's say I'm in "users/todos/find" and I'm transitioning via `{{link-to}}` to "todos/todo/someId".

The "users" Route will throw this error because its `controller` value is `undefined` though its explicitly declared (`export default Ember.Controller.extend({});`).

**Comment by cfstras** [comment]
Using Ember 1.9.1,  when I use `queryParams` in a controller and change a param via this.set() in an action handler on the controller, I get the same error, but only on the second invocation of the action. The first one always works.

I'm too time constrained to debug this for now, just noting it for anyone following.

**Comment by patmood** [comment]
I've also had this issue since ember 1.6.0 which has prevented any updates... until now. The fix was to remove my `App.LoadingRoute` which used to display a spinner overlay graphic. Looks like the loading route has been [deprecated](http://emberjs.com/guides/routing/loading-and-error-substates/#toc_legacy-code-loadingroute-code).

I haven't been able to replicate it in JSBin but I hope this helps others fix the issue.

**Comment by rwjblue** [comment]
If this is still an issue we need a reproduction to be able to track it down.  

Happy to reopen with a reproduction on current versions...
