### ISSUE TITLE
multiple propertyDidChange triggering observers only once

### ISSUE THREAD

**Issue by patricklx** [emberjs/ember.js#9497]
See this jsbin:
http://jsbin.com/mipibunusu/1/edit?html,js,console,output 
This jsbin mimics the behaviour of reduce computed and ember data.
In the console output you can see the counter increasing, but then only decreases once.

I encountered this issue while working on https://github.com/emberjs/ember.js/pull/9492 .

reduce computed counts the number of willChange and didChange. see this [line](https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/computed/reduce_computed.js#L328)

However, sometimes it did not receive the didChange event, which then causes it not to flush the changes. Especially when ember data is used.

**Comment by rwjblue** [comment]
reduce computed has been removed (as have before observers) so I believe this issue is likely resolved.
