### ISSUE TITLE
Remove MODEL_FACTORY_INJECTIONS

### ISSUE THREAD

**Issue by wycats** [emberjs/ember.js#9500]
What are the blockers for normalizing model instantiation to be like all other injections?

**Comment by stefanpenner** [comment]
@igorT @bmac @fivetanley whats the status for ember-data on this one?

**Comment by rwjblue** [comment]
I believe a bunch of work in ED has been done on this.  I'd like to get some feedback from @emberjs/ember-data-contributors...

**Comment by stefanpenner** [comment]
The remaining work was removing the fact the subclasses are returned from lookup factory. Unfortunately others decided this was for some reason to much of a breaking change during 2.0 transition

**Comment by stefanpenner** [comment]
https://github.com/emberjs/data/pull/4810 + https://github.com/emberjs/ember.js/pull/14360 together make `Ember.MODEL_FACTORY_INJECTIONS` have no more power. We likely can't remove it for some time from the blueprints for compatibility with individuals on older versions of ember or ember-data.

**Comment by rwjblue** [comment]
We can deprecate having it set though. This sets us up for removal at some future point (sometime after 2.16).

**Comment by mmun** [comment]
MODEL_FACTORY_INJECTIONS was removed in 2.14.
