### ISSUE TITLE
IE9 location auto + base url === redirect back to /

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#9501]
I _believe_ this isn't user-error.

@jayphelps thoughts?

**Comment by connerfritz** [comment]
What's the status on this one? Experiencing it too.

**Comment by jayphelps** [comment]
Can someone create a repo with an ember app I can install and reproduce?

**Comment by connerfritz** [comment]
It seems the easiest way to reproduce is adding
    <base href="/base/" />
to the index.html file of an app, then trying to access an URL in your app through it.

**Comment by rwjblue** [comment]
@stefanpenner is correct in:

> I think ember-cli should drop baseURL entirely and merely re-write asset urls as needed...
> you are right, rootURL should be all ember cares about in this case. (and seems to work in my case)

Agreed.  I believe that this is an ember-cli issue though, not an Ember one.
