### ISSUE TITLE
Expose `_parentView` logic

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/ember.js#9528]
`Ember.View#parentView` and `_parentView` behave differently. Specifically, the latter respects route views as separate root views, while the former just falls through to `ApplicationView`. The `_parentView` logic would be really helpful in Ember-I18n, where we want to know within a helper which main template we're inside.

cf jamesarosen/ember-i18n#155

**Comment by rwjblue** [comment]
`_parentView` is gone, `Ember.View` is gone, the referenced issue is closed, and ember-i18n is working well with latest versions.  Closing this, as I think we have moved on (I can reopen if folks disagree)...
