### ISSUE TITLE
ArrayController.itemController results in inconsistent ArrayProxy behavior

### ISSUE THREAD

**Issue by davewasmer** [emberjs/ember.js#9534]
[Demonstration jsbin](http://emberjs.jsbin.com/numekudeci/2/edit)

The docs describe how providing an `itemController` property on an `ArrayController` will result in the items of the `ArrayController` being wrapped with instances of that `itemController`.

The jsbin above demonstrates the inconsistency. I loop over the contents of the `ArrayController` three ways:

```hbs
<!-- Works as expected - item is an ObjectController proxying an underlying model -->
{{#each item in controller}}
```

```hbs
<!-- wrappedModels is a map over arrangedContent, calling objectAt for each one -->
<!-- Works as expected - item is an ObjectController proxying an underlying model -->
{{#each item in wrappedModels}}
```

```hbs
<!-- Does *not* work as expected - item is just the model, not wrapped with an ObjectController -->
{{#each item in arrangedContent}}
```

**Expected result:**

Each method of looping produces the same result.

**Actual result:**

Looping over arrangedContent directly loops over models, not ObjectController instances

**Comment by stefanpenner** [comment]
arraycontroller + itemController are deprecated
