### ISSUE TITLE
Accessing the view from within a #with helper is broken in 1.7 and 1.8?

### ISSUE THREAD

**Issue by shawnam** [emberjs/ember.js#9535]
I'm seeing strange behavior when I attempt to access view elements from within a #with helper. Maybe this is expected, but looking through the Changelog for the latest Ember versions, I'm not finding anything that I expect to cause this behavior.

Here's my toy template:

```
{{#with model as "bar"}}
  <label {{bind-attr for="view.inputField.elementId"}}>My Label</label><br/>
  {{input type="text" viewName="inputField" valueBinding="bar"}}<br/><br/>
  The id for the input field is {{view.inputField.elementId}}
{{/with}}
```

For Ember 1.6.1, the input field id is correctly displayed and the label's for attribute is set correctly.

For Ember 1.7.1, rendering fails entirely because "Uncaught Error: Assertion Failed: Cannot call get with 'inputField.elementId' on an undefined object"

For Ember 1.8.1, the page is rendered, but the input field id isn't displayed and the label's for attribute isn't set.

For Ember 1.9.0-beta.1 we're back to the behavior in Ember 1.6.1.

Here are jsbins for each ember version:
Ember 1.6.1 -- http://jsbin.com/lozape/4/edit
Ember 1.7.1 -- http://jsbin.com/xicove/1/edit
Ember 1.8.1 -- http://jsbin.com/nuliyo/1/edit
Ember 1.9.0-beta.1 -- http://jsbin.com/cagula/1/edit

What should I expect to be happening here? Is the behavior in 1.7 and 1.8 buggy, and a fix was put in for 1.9? Is there a workaround to get this to work correctly in 1.8? Or is the behavior in 1.7 and 1.8 expected and I'm just missing how to do this correctly in those versions? I discovered this while attempting to update my application running 1.6.1 to 1.8.1.

**Comment by rwjblue** [comment]
@shawnam - Sorry for the lack of response and delay here.

I agree that this is odd, but since 1.9.1 (http://jsbin.com/ducili/3/edit) and 1.10.0-beta.3 (http://jsbin.com/ducili/2/edit) are both working properly, I'm going to close.
