### ISSUE TITLE
Render Helper cannot accept dynamic property as its first parameter, though the Partial Helper can?

### ISSUE THREAD

**Issue by SimonKaluza** [emberjs/ember.js#9545]
Can I pass in a dynamic template name to a `render` call in Handlebars for Ember.js?

I'm attempting to create a component (a filter table) that accepts a run-time property that specifies exactly what template to render while looping over a collection of objects.  My code works fine when  using the `partial` helper to leverage a dynamic property parameter for the first parameter passing in a a `bodyTemplate` property on the parent component like:

    {{#each r in records}}
      <tr>
      {{partial bodyTemplate}}
      </tr>
    {{/each}}

but fails when I use the `render` helper call in the same way like:

    {{#each r in records}}
      <tr>
      {{render bodyTemplate r}}
      </tr>
    {{/each}}

The error that gets logged to the console is:

    Uncaught Error: Assertion Failed: You used `{{render 'bodyTemplate'}}`, but 'bodyTemplate' can not be found as either a template or a view.

Though this seems to be a separate issue from the inability to set up controller bindings in render helper calls like https://github.com/emberjs/ember.js/issues/1914 describes, but are these two issues related?  I intend to debug look into this further, but I wanted to see if anyone had some initial feedback.

**Comment by rwjblue** [comment]
Sorry for taking so long on a response here, but I'm going to close this now...

`{{render}}` will be deprecated in 2.0, so I do not think we will be changing the way this works in the interim.

**Comment by petermumford** [comment]
@rwjblue if your deprecating `{{render}}` in Ember 2.0 what should we start using instead. I find the `{{render}}` helper really useful. It's just a real shame we can't use the first property as a dynamic property.

**Comment by jbrown** [comment]
@petermumford Is #10093 not a suitable replacement?

**Comment by jasonmit** [comment]
@petermumford if controllers are going away naturally this would go away.  I am guessing, the recently merged `component` helper would be its replacement.

**Comment by petermumford** [comment]
@jbrown @jasonmit Thanks for pointing me to this, I really like the way it can swap components form a dynamic property, very useful. I'll need to revise what I've currently got as I'm using the `{{render}}` controller for data but no biggie.

**Comment by Krutius** [comment]
@jbrown well, components have side effects, you can not use the same from a route then inside a template with {{render}}.
Also, and more important, a controller is more isolated. So for example no access to the store.

**Comment by wagenet** [comment]
@Krutius I'm not sure what you mean by components having side effects. I also don't understand your comment about controllers being more isolated. See also https://github.com/emberjs/rfcs/pull/38/ for future direction.
