### ISSUE TITLE
Please add note to changelog/release notes that Ember.assert can now take a function

### ISSUE THREAD

**Issue by fivetanley** [emberjs/ember.js#9575]
Had a very confusing error in Ember Data when testing against the canary branch that `this.fixturesForType` or something wasn't defined. This will probably be useful to confused library authors like myself wondering why the scope/`this` binding of a method is wrong inside Ember.Object.extend, or just anywhere now that the function gets called, rather than checking for truthiness.

https://github.com/emberjs/ember.js/commit/2daec0b758593083041a80c037e5996219480dcf

seems maybe worth drawing some attention to, but I don't know how many authors in the wild are using it.

**Comment by stefanpenner** [comment]
to late
