### ISSUE TITLE
Can't calculate queryParams after controller loads

### ISSUE THREAD

**Issue by corinna000** [emberjs/ember.js#9580]
My use case: Create a faceted search widget from an array of facets from a remote source and store the selected facet state as queryParams.

Problem: I don't know what the facet categories will be until after the FacetsController has received the data. By that time it's too late to setup `queryParams` on the controller (the empty cacheMeta property causes _qpChanged to throw a TypeError.)

I don't have a lot of good solutions. I'm looking at either hard coding all the possible facet categories into the controller (which will cause future headaches if new facet categories appear), or else not use queryParams at all for saving facet state.

Suggestions very welcome,

Thanks

**Comment by corinna000** [comment]
Sorry for the long delay in reporting back!

Yes, I'm doing all the setup in init now on both the routes and the controllers.

**Comment by wagenet** [comment]
@corinna000 are things resolved to your satisfaction then?

**Comment by corinna000** [comment]
More or less. I wasn't able to satisfactorily solve the problem of setting up a primary controller to use the queryParams defined in a secondary controller. The default value for the queryParam in the secondary controller ('null') was not used in the primary controller (in fact, null was converted to its string value in the primary controller!), so I had to manually set the default value of the queryParam to empty string in both controllers. 

This is working for now, but queryParams are so useful that it seems like there should be a better supported option for sharing them between controllers.

**Comment by knownasilya** [comment]
:+1: agreed! I wonder if you can use a mixin..

**Comment by wagenet** [comment]
I'm going to go ahead and close this. However, if someone has a proposal for making things better here, please do share it.
