### ISSUE TITLE
Removing ES6 AMD Loader Regression

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#9588]
@eventualbuddha and I met today and this is the lists of TODOs we currently think are needed to remove the regression mentioned in #9381. Before Ember can be transpiled into the bundle format, we need to update the micro-libs it depends on to use the new transpiler.  This involves updating each Brocfile to use `broccoli-compile-modules`.  Luckily majority of the micro-libs can be compiled to the bundle format.

- [x] Update htmlbars https://github.com/tildeio/htmlbars/pull/129
- [x] Update route-recognizer https://github.com/tildeio/route-recognizer/pull/35
- [x] Update router.js
- [x] Pull in new versions of micro-libs
- [ ] Update Ember path resolution ( Divide and conquer opportunity )
- [x] Remove any `module` key words and replace with `import * from <MODULE>`
- [x] Update Ember Brocfile to transpile using broccoli-compile-modules

/cc @eviltrout @SamSaffron

**Comment by salzhrani** [comment]
Would love to help, any suggestions ?

**Comment by eventualbuddha** [comment]
The ground has shifted a little bit since we opened this. My proposal is to continue updating ember's dependencies, but instead of updating to the latest es6-module-transpiler to move to [esperanto](http://esperantojs.org/). I'm a contributor to that project as well and am eager to find and fix any bugs that may be present, so don't hesitate to file issues if you find a behavior you do not expect.

**Comment by chadhietala** [comment]
@salzhrani Since I opened this ticket a lot has changed.  I would want to here from @eviltrout or @SamSaffron on how much of a problem this is with newer versions of the loader.  We should do our upmost to move the micro-libraries to Esperanto.

**Comment by rwjblue** [comment]
@eventualbuddha - I have Ember itself passing all tests using esperanto (required many fixes/changes) locally.  The last major hurdle is https://github.com/esperantojs/esperanto/issues/84#issuecomment-71931222, which I plan to try and implement today.

**Comment by chadhietala** [comment]
LOL had this issue cached from last night and didn't have Brian's comment in it.

**Comment by stefanpenner** [comment]
now that we dropped IE8 i believe i have a solution for this. I have  WIP, hopefully get it to completion and test #'s this weekend

**Comment by chadhietala** [comment]
Forgot about this... :smile:

**Comment by rwjblue** [comment]
Closing this issue, in favor of Stef's WIP PR.
