### ISSUE TITLE
actions with actionName binding which binds to undefined results in much EWUT

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#9621]
strange issue noticed in ember-performance:

Since we deprecated `{{action foo`  interpreting `foo` literally, ember-performance exhibited this problem

given:

```hbs
{{action bindingToUndefined otherBinding}}
```
the action being sent is the result of `otherBinding`. This is absolutely wrong. Instead an error should be thrown that `bindingToUndefined` actually bound to `undefined`. The question is, should that error happen eagerly or when the action is triggered.

I also suspect in development mode an assertion may have caught this earlier. But since bindings are run-time and data changes, we need this to be a production error as well.

related: https://github.com/eviltrout/ember-performance/pull/8

**Comment by rwjblue** [comment]
![screenshot](http://assets.rwjblue.com/snapshots/2016-04-13-18-50-15_JS_Bin_-_Collaborative_JavaScript_Debugging.png)
