### ISSUE TITLE
support for dots in json keys

### ISSUE THREAD

**Issue by MacFlecknoe** [emberjs/ember.js#9630]
Ember.js doesnt seem to support json objects with dots in the objects attribute names (e.g.):

{ "ns1.id" : 14, "ns2.name" : "mike" };

Is this an omission or am i overlooking something? We have services that we are required to consume that support namespaces in this way.

**Comment by rwjblue** [comment]
I think we should avoid changing `Ember.get` to support this, and suggest that folks having to deal with API's with this structure use a transformation layer to convert the source format into something that works.

**Comment by locks** [comment]
@k3n in your Twiddle it's your code that defines the `'dynamicForm.show'` property with a dot in the name, am I misunderstanding?

**Comment by k3n** [comment]
@locks `'dynamicForm.show'` is from a nested route in which I was needing to access the params.

Regardless, my point is that sometimes your object keys may use a dot, and whether it originates from Ember or not is ultimately inconsequential -- I just pointed it out because it was ironic in the context of this conversation that "those API's" was actually Ember itself. The fact that Ember doesn't support property keys with dots is troubling in light of no other means of interacting with these objects via a standard API.

**Comment by chancancode** [comment]
@qarthandgi was that tone really necessary?

Anyway. To answer your question, you don’t really need `.get` anymore so you can just do `foo[“bar.baz”]` if you need to.

We _could_ make `.get` support dots in property name, perhaps with a syntax like `foo.get(“bar\.baz”)`. But doing that is not free, `get` is (was?) a really hot path, and support this would require much more sophisticated parsing which adds up very quickly across all the calls in an app.

I think even you would agree that property names with dots are rather uncommon, so having to pay that penalty across the whole app just so this could work in the few spots they need to is not going to be acceptable either.

**Comment by ruckc** [comment]
So, this is kinda annoying.

I've got two use-cases where in handlebars I need to access a nested object with a dotted key; in one case, i'm iterating through all keys, and trying to display the values.  In the 2nd case I have a specific hardcoded key.

The JSON document is externally provided, the app's job is to visualize it, and let a reviewer edit it, before sending it back to the external system.

In handlebars, though I can't access the key's value; not with any of these options:
```
{{get record.document 'some.key'}}
{{record.document[some.key]}}
{{record.document['some.key']}}
```

I don't really care if we don't modify get, maybe a secondary get helper, i.e. get-with-encoded-dots.

**Comment by k3n** [comment]
That sounds like a different issue (though I'm not positive), since that's handlebars.

Have you tried the `with` helper?

https://handlebarsjs.com/block_helpers.html

**Comment by ruckc** [comment]
@k3n - my testing https://ember-twiddle.com/b92cb0d082f3d3282fdaeea39e4cbb5f?openFiles=templates.application.hbs%2C

it definetly doesn't work and is the same symptoms.  My solution is below, which i find extremely annoying that I had to write; although it is simple.  
```js
import { helper } from '@ember/component/helper';

export function getValue([object, key]) {
  return object[key];
}

export default helper(getValue);
```

**Comment by jsfuchs** [comment]
I just ran into this as a weird edge case where I'm rendering data coming from an API I don't really control. I'm fine with a workaround - @ruckc's solution seems good; would it make sense to put this edge case in as a disclaimer or side note on the "get" documentation? 

https://api.emberjs.com/ember/release/classes/Ember.Templates.helpers/methods/get?anchor=get
