### ISSUE TITLE
Allow using hidden for toggling visibility

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/ember.js#9634]
Currently, `Ember.View` uses `style="display: none;"` to hide elements and jQuery's `$.fn.toggle` to add and remove that style attribute value. HTML5 defines a [hidden attribute](http://davidwalsh.name/html5-hidden) that serves this purpose just as well, if not better.

I'm not suggesting that Ember *switch* to `hidden` -- the browser support isn't as strong and there is still debate in the community about the attribute. Still, I'd like to be able to easily patch Ember to let me use it. Complex CSS rules -- especially animations -- are often easier to write when you don't have to override properties set in the `style` attribute.

There are two places that are tightly tied to the current implementation:

 1. [`applyAttributesToBuffer `](https://github.com/emberjs/ember.js/blob/91741b4d58b2aa2781d6a7478bf38ddc3df3a8a1/packages/ember-views/lib/views/view.js#L1603-L1605)
 2. [`_toggleVisibility`](https://github.com/emberjs/ember.js/blob/91741b4d58b2aa2781d6a7478bf38ddc3df3a8a1/packages/ember-views/lib/views/view.js#L1928-L1949)

One idea would be to extract two new helpers:

```js
_applyVisibilityToBuffer: function(buffer) {
  if (get(this, 'isVisible') === false) {
    buffer.style('display', 'none');
  }
},

_toggleElementVisibility: function(isVisible) {
  $el.toggle(isVisible);
}
```

Those would be easy to monkey-patch for `hidden` support:

```js
_applyVisibilityToBuffer: function(buffer) {
  if (get(this, 'isVisible') === false) {
    buffer.attr('hidden', true);
  }
},

_toggleElementVisibility: function(isVisible) {
  $el.attr('hidden', !isVisible);
}
```

**Comment by jamesarosen** [comment]
I discussed this briefly with @marcysutton today. She had some good insights. I may not do them justice, but here's my summary:

 * The [HTML5 spec](http://www.w3.org/TR/html5/editing.html#the-hidden-attribute) has this to say about the `hidden` attribute: "When specified on an element, it indicates that the element is not yet, or is no longer, directly relevant to the page's current state, or that it is being used to declare content to be reused by other parts of the page as opposed to being directly accessed by the user. User agents should not render elements that have the hidden attribute specified. This requirement may be implemented indirectly through the style layer."
 * The [ARIA spec](http://www.w3.org/TR/wai-aria/states_and_properties#aria-hidden) says that the `aria-hidden` attribute "[i]ndicates that the element and all of its descendants are not visible or perceivable to any user as implemented by the author."
 * @marcysutton said that in her experience, using `aria-hidden` required doing other things to the element, such as marking links and form elements with `tabindex=0` lest the user experience "phantom elements" that are not *perceivable* but show up while navigating the page.

I suggest we think through the accessibility concerns here more carefully. We may end up with a few different properties that we want to use in conjunction.

**Comment by marcysutton** [comment]
One correction: focusable child elements inside of `aria-hidden` need `tabindex="-1"` to remove them from the tab order, otherwise they show up as "mystery controls". That is bad. 

I don't see any reason not to use the HTML5 `hidden` attribute for marking things as completely hidden, but as the spec notes, it depends on CSS implementation with `display: none` to really hide something. Compound this with the fact that `display` is not an animatable property like `max-height`–it usually has to be set after a `timeout` so that transitions have time to occur. That might be a nice thing to work in, actually.

**Comment by stefanpenner** [comment]
closed for the same reason as the RFC.

we also plan to ensure `<my-component hidden="{{isHIdden}}"`  "just works"
