### ISSUE TITLE
{{#with}} block after {{outlet}} causes MANDATORY_SETTER to trigger in 1.8.1

### ISSUE THREAD

**Issue by totallymike** [emberjs/ember.js#9654]
That's pretty much the gist of it. 

Here's a JSBIN demonstrating the problem.  http://emberjs.jsbin.com/nolisuyuva/1/edit?html,js,console,output

It seems that `{{outlet}}` adds a watcher to the `keywords` property, and when [this line](https://github.com/emberjs/ember.js/blob/master/packages/ember-handlebars/lib/helpers/with.js#L79) is executed, it triggers the MANDATORY_SETTER exception

**Comment by rwjblue** [comment]
Working with 1.9.1 (http://emberjs.jsbin.com/wuroke/7/edit) and 1.10.0-beta.3 (http://emberjs.jsbin.com/wuroke/6/edit).
