### ISSUE TITLE
prod perf suggestion

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#9656]
our micro-loader supports relative paths, but it appears our build tooling already resolves them at build time, yet we incur the relative path resolution path constantly.

I suspect: https://github.com/emberjs/ember.js/blob/master/packages/loader/lib/main.js#L39-L53 can likely just be removed.

cc @chadhietala I know you doing some work re: build related boot time improvements, this is likely going to be a nice little win with little effort.

**Comment by stefanpenner** [comment]
@eviltrout @Samsafron this may interest you

**Comment by rwjblue** [comment]
Closing, recursion was removed by https://github.com/emberjs/ember.js/pull/12228.
