### ISSUE TITLE
performance issue related to view rendering (and maybe sideloading)

### ISSUE THREAD

**Issue by feitian124** [emberjs/ember.js#9722]
Recently I met performance issue in my project, it is very slow in chrome and other modern browsers. And what worse, ie8 will popup "long-running script warn" to user to abort it.

Suppose i have post and comment resources(routes, controllers, models etc), for simple only show the templates like below:

post template
```hbs
{{author}} : {{text}}
{{#each comment in comments}}
   {{render 'comment' comment}}
{{/each}}
```

comment template
```hbs
{{author}} reply {{text}}
```

when  i have only 10 posts and each post has only 1 comment, it takes more than 6 seconds to render page and ie8 gives warn.

i tried use chrome timeline for profiling then find:

1. parseHTML event used almost 1s, mostly wasted on a function, the callback of sub event "XHR State Change".
2. then another function call, callback of  "XHR State Change" used almost 1 s.

my post and comment resources is quit small, both have less than 10 attrs like author, createdAt, avatar etc. 

1. i'm using sidelining so the first time fetching data is a little more(json of users, posts, comments and images). but the data only cotains 10 posts, 10 comments , one or two users and images. It should not
be so slow.
2. I tried remove `{{render 'comment' comment}}` in post  template, if so it is still slow but ie8 never give long-running warning.
3. i will try `unbound` help, not sure if it will help.
4. i noticed @stefanpenner 's [group-helper](https://github.com/emberjs/group-helper), but did not update for sometime. is it useful in my case?

is it ok put a render in another render? any suggestion for performance tuning ember app?  thanks.

**Comment by stefanpenner** [comment]
should be largely fixed with glimmer, and the newly refactored AC/RC helpers
