### ISSUE TITLE
[Perf] Array property changes not being coalesced (for reduceComputed?)

### ISSUE THREAD

**Issue by SohumB** [emberjs/ember.js#9739]
See [this jsbin](http://emberjs.jsbin.com/jetevigahu/1/edit).

The `source` array changes often and in large batches. We rely on array property change coalescing for this to not be a performance issue.

The dependent `items` array has elements that each have a property `dep`, that is dependent on some property of the full `items` array - in this case, `length`. Then we have an `{{#each}}` that iterates over these dependent values.

All of this behaves fine, so far.

This breaks down, however, when you add an `Em.computed.max` on the resulting `items.dep` values. Click the button, and see how many times the `length` property gets called. 

In our codebase, the equivalent of `length` is an expensive operation that we really would have wanted and expected to run with coalesced changes, once per runloop. The expected flow is: `items` is generated, with no value for each `item.dep` yet, then `length` is computed once, then the `items.dep` values are computed, _then_ the `max` property is computed. But Ember appears to be recomputing `max` and thus forcing recomputes of everything upto `length` on every array change operation.

Thanks!

**Comment by aexmachina** [comment]
So just wanted to return this fascinating conversation to the original issue: what should we do about this bear-trap lurking in the Ember codebase? Is there a plan of action or should I PR a warning in the docs for this feature.

**Comment by ef4** [comment]
I'd favor a PR deprecating arrayComputed and reduceComputed. People who want to keep using them could be directed to an add-on. 

This would be a warning only for now, with removal at 2.0.

**Comment by aexmachina** [comment]
We have simple replacements that are not broken too, but they map/reduce
over the whole array on each change.

**Comment by patricklx** [comment]
hey, i extracted RPC into an addon with some changes to fix various issues i had. if anyone is interested: https://github.com/patricklx/ember-cli-reduce-computed
