### ISSUE TITLE
`classNameBindings` don’t work on a component which has `tagName: 'svg'`

### ISSUE THREAD

**Issue by timohofmeijer** [emberjs/ember.js#9745]
You can change the tagName to see that it does work with other elements:
http://jsbin.com/zajeteheyi/1/

**Comment by superlou** [comment]
This issue still exists on the released 1.10.0.

**Comment by mixonic** [comment]
@superlou Right. We did have this support, but it must have regressed while I polished the implementation of attrNodes for the renderer.

I've landed a refactor of attributeBindings into 1.11 beta. It needs further work before graduating to release, and part of that is porting classNameBindings over to the new system. I'm expecting 1.11 will introduce this classNameBindings for svg elements.

**Comment by rwjblue** [comment]
The original JSBin (updated to 1.10.0) does apply the class to the `svg` element.  Updated: JSBin: http://jsbin.com/dataso/3/edit

**Comment by blesh** [comment]
I'm hitting this bug [right now with ember-nf-graph](https://github.com/Netflix/ember-nf-graph/issues/16). This actually is actually a regression from 1.8.1 and Handlebars (where we had it working for a long time).

Currently I'm seeing this with 1.11.1 and HTMLBars. http://emberjs.jsbin.com/melayoruro/1/edit

**Comment by ebryn** [comment]
We shouldn't be using jQuery when dealing with SVG elements, it doesn't support SVG. We'll likely have to use the DOM APIs directly.

**Comment by mixonic** [comment]
> We shouldn't be using jQuery when dealing with SVG elements, it doesn't support SVG. We'll likely have to use the DOM APIs directly.

Obviously. Our use of jQuery predates any understanding of this issue though. Ember has always used jQuery for setting classes.

Should be addressed in Glimmer.

**Comment by stefanpenner** [comment]
glimer is in, i believe this is addressed. If not, feel free to report/reopen
