### ISSUE TITLE
Ember 1.9.0-beta.3 - Unable to run integration tests w/ AJAX error 

### ISSUE THREAD

**Issue by workmanw** [emberjs/ember.js#9746]
When I upgraded to Ember 1.9.0-beta.3 I discovered that my integration tests which exercise server errors (404, 401, 403) were all broken. I tracked the problem down to this change: https://github.com/emberjs/ember.js/pull/9474

The heart of the problem is that a promise on the `model` hook is failing. Both `beforeModel` and `afterModel` install rejection handlers via `then`, `model` does not however. This results in `Ember.RSVP.onerrorDefault` being triggered when a model promise is rejected. With recent changes in to that function, this ultimately will result in `Test.adapter.exception` being called. In some cases, that might be what you want, but in other cases you really need a way to exercise server error logic without creating a failing test. [ember-runtime/lib/ext/rsvp.js](https://github.com/emberjs/ember.js/blob/322fc0e371a6df88c1c29d80db8cb545be5315a8/packages/ember-runtime/lib/ext/rsvp.js#L46-L57)

Here is a JSBin that demonstrates the issue. http://emberjs.jsbin.com/kihokodare/4/edit?html,js,output In this JSBin, I'm overriding Ember.$.ajax to simulate a status of 404.

**Comment by stefanpenner** [comment]
fixed due to RSVP upgrade.
