### ISSUE TITLE
Map's values + keys property conflict with ES6 features

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#9747]
we should move them to have an underscore, and someday we can add the iterable versions of them

https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/map.js#L257-L259

**Comment by igorT** [comment]
Aren't the es6 `keys` and `values` methods, and ours properties? Not really a conflict?

**Comment by rwjblue** [comment]
@igorT - If we have something that does not comply with what the the ES6 spec says `keys` is that is definitely a conflict.

**Comment by igorT** [comment]
But `keys` doesn't exist in es6 spec, only `keys()`?

**Comment by rwjblue** [comment]
@igorT - If our internal key listing is a prop at `map.keys`, then we can never implement `map.keys()` method from the spec (because as you know an object can only have a single thing named `keys`).

**Comment by stefanpenner** [comment]
> But keys doesn't exist in es6 spec, only keys()?

since functions are pinned to properties, this conflicts
