### ISSUE TITLE
globals resolver should convert foo-bar to fooBar for ember-data

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#9751]
this allows ember-data globals users have the same conventions as cli users, and eases the migration path.

**Comment by rwjblue** [comment]
@stefanpenner - Can you flesh this out more?  I assume you mean to modify `resolveModel` [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/resolver.js#L338-L343), but it is not clear what translation would be needed.

**Comment by rwjblue** [comment]
Many changes to the naming structure in ED have landed. This is likely resolved, but if not please provide a checklist or something so it can be actionable.

Closing for now, will reopen if still an issue...
