### ISSUE TITLE
Query Params - replaceState doesn't work when refreshModel is true

### ISSUE THREAD

**Issue by shripathee** [emberjs/ember.js#9771]
JSBin: http://emberjs.jsbin.com/gihajufuxe/1/edit?html,js,console

I am not sure if this limitation was introduced by design, but there are certain use cases such as sorting in which both replaceState and refreshModel are needed.

cc: @machty

**Comment by dustinfarris** [comment]
I've noticed this as well.

**Comment by machty** [comment]
Seems like a dup of #10577, will reopen if not.
