### ISSUE TITLE
Equally named controller properties for nested query parameters influence each other

### ISSUE THREAD

**Issue by ElteHupkes** [emberjs/ember.js#9794]
There's an issue with using the same controller properties for different query parameters in the same route hierarchy. I've created a JSFiddle to illustrate this issue: http://jsfiddle.net/ElteHupkes/s7ahuu74/2/

To shortly explain, in this fiddle I have an `OuterRoute` and an `InnerRoute`. The `OuterController` binds the `sort` query parameter to its local property `listSort`. The `InnerController` binds the `inner_sort` query parameter, also to its local property `listSort`. In the fiddle, click on "Change outer params" first. This changes the outer "sort" property to some value, in this case "id". Now click on "Move to inner", which is a link to the inner route without any query parameter argument. However, after the transition the `listSort` property of the `InnerController` now also mysteriously equals `id`, where it should have remained unchanged.

Edit: This is using Ember 1.8.1

**Comment by stefanpenner** [comment]
QP are moving to the routes

**Comment by Techbrunch** [comment]
@stefanpenner Shouldn't this issue be reopened ? I'm looking at the [2.8.0 documentation](https://guides.emberjs.com/v2.8.0/routing/query-params/) and query params are still set on the controller.
