### ISSUE TITLE
If statement crashing whole page

### ISSUE THREAD

**Issue by Lilibuth12** [emberjs/ember.js#9795]
I use ember data to load in a large amount of readership stats to show who has viewed posts on my website, however some people do not have the permissions to view these, I previously had used an {{if readership}}{{/if}} which worked fine with no issues, I am using Ember-1.7.0 with Ember Data and it caused my whole chrome tab to crash.

**Comment by rwjblue** [comment]
@Lilibuth12 - Can you please provide a reproduction?  I don't think we can do much without one...

**Comment by stefanpenner** [comment]
seems to have gone stale, if a reproduction can be provided we will gladly look into this.
