### ISSUE TITLE
Handlebars selecting the wrong option

### ISSUE THREAD

**Issue by eviltrout** [emberjs/ember.js#9813]
Here's a JSBin to illustrate it:

http://emberjs.jsbin.com/detamuruki/1/edit

It seems there is some kind on Ember that is selecting the wrong element in a `<select>` list. Note this without using `Ember.Select`, just a regular view with a `tagName: 'select'`

It does not happen in Ember 1.7.1 and does not seem to happen in canary when HTMLBars is turned on, so I believe it is a regression introduced in 1.8.0 when metamorphs were removed.

**Comment by stefanpenner** [comment]
components form inputs now "just work" as the DOM intended: http://jsbin.com/febafarova/1/edit?html,css,js,output

if an issue with this exists, please report it with a repro
