### ISSUE TITLE
Confusing HTMLBars error: What template caused the error?

### ISSUE THREAD

**Issue by eviltrout** [emberjs/ember.js#9821]
HTMLBars seems to lint the structure of your HTML, (which is insanely awesome, btw!) and provides error messages. 

Here's one I got when testing on Discourse:

![screen shot 2014-12-05 at 1 13 03 pm](https://cloud.githubusercontent.com/assets/17538/5320476/7d8b81a6-7c80-11e4-88ea-9aa9c640adba.png)

The error message is useful, but it is confusing because I have to look all the way at the bottom to determine what template it came from. It would be really nice if it mentioned the name of the template on the first line along with the error message.

I realize this might be tough as most templates are compiled like `Ember.TEMPLATES["quote"] = ... compiler ...` but perhaps the template or file name could be passed as a parameter to the compile method in development mode?

(Note: I am using ember-rails, if this already exists the actual issue might be to get ember-rails to support it)

**Comment by rwjblue** [comment]
I realize you have probably moved on from this issue, but we have finally landed support to supply the `moduleName` down into the compiler (which is then embedded in the final templates):

https://github.com/emberjs/ember.js/pull/11095
https://github.com/emberjs/ember.js/pull/11097
