### ISSUE TITLE
Update ContainerView preamble docs

### ISSUE THREAD

**Issue by trek** [emberjs/ember.js#9833]
changes in https://github.com/emberjs/ember.js/pull/9472 (deprecated initial definition of child views upon extend) make the preamble incorrect, but we're blocked by lack of versioned API docs. Changing this now means someone using <= 1.8 will not have access to accurate docs for their version

**Comment by givanse** [comment]
In the meantime, issues are documentation, what is the proper way of adding child views?

**Comment by rauhryan** [comment]
Ditto what @givanse 

It's unclear what to do instead

**Comment by givanse** [comment]
@rauhryan What I did was to go from:

    Ember.ContainerView.create({
      childViews: ['aView'],
      aView: Ember.View.create()
    });

To something like:

    import FoobarView from '...'; 
    Ember.ContainerView.create({
      _anInitListener: function() {
        var foobar = FoobarView.create({});
        this.pushObject(foobar);
      }.on('init')
    });

**Comment by rwjblue** [comment]
`Ember.ContainerView` is no longer present as of 2.0.0.
