### ISSUE TITLE
{{#each}} loop with passed itemController-wrapped array shifts context of actions

### ISSUE THREAD

**Issue by SaladFork** [emberjs/ember.js#9836]
**JSBin**: http://emberjs.jsbin.com/ripanu/1/edit?html,js,console,output

Explanation from JSBin:
> In our application, we have a service that is responsible for maintaining state for a collection of items. Some of that state is app state that isn't to be persisted (so not part of the model). We're using item controllers to encompass these extra states and expose them through the service.
>
> It seems that using item controllers causes the context (of actions, at least) within an `#each` loop to shift away from the controller of that template. Below the buttons outside the `#each` loop fire an action on `IndexController`, but the exact same actions inside the `#each` loop do not. Notice also that the action fails silently (when typically these uncaught actions result in a console error).
>
> I believe the issue to be that the context is considered to be the service, rather than the containing template.

The relevant template in question (excerpted):
```handlebars
{{!-- this action works --}}
<button {{action "selectColor" colors.firstObject}}>
  {{colors.firstObject.name}}
</button>

{{#each color in colors}}
  {{!-- this action does not work and fails silently --}}
  <button {{action "selectColor" color}}>
    {{color.name}}
  </button>
{{/each}}
```

**Comment by hcatlin** [comment]
I had this bug today. :(

**Comment by stefanpenner** [comment]
ya its lame, with 2.0 shifting goes away entirely, and item controllers become deprecated. As such, I suspect we may not see a fix for this, unless someone has spare time to dig in.
