### ISSUE TITLE
remove need for loader.resolve with build step

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#9844]
- [ ] backburner
- [ ] rsvp
- [ ] router?
- [ ] route recognizer?

**Comment by stefanpenner** [comment]
@eviltrout maybe be of interest

**Comment by rwjblue** [comment]
We moved from Esperanto (which had this as an option) to Babel (which AFAIK does not have the ability to replace relative imports).  

@stefanpenner - Are you aware of an option in Babel to do this?

**Comment by stefanpenner** [comment]
> @stefanpenner - Are you aware of an option in Babel to do this?

Unfortunately babel does not support this out of the box, but they did expose a function for us, So we can implement it in user-land.

**Comment by rwjblue** [comment]
Gotcha. When you have time, could you drop a link or reference to aid in researching that?

**Comment by stefanpenner** [comment]
it was `getModuleId` and here is a test in babel that demonstrates usage: https://github.com/babel/babel/blob/30be1317e6b3d83e7a22328ca4baf37b218470da/packages/babel/test/api.js#L278-L305
