### ISSUE TITLE
Create a style-guide for contributing

### ISSUE THREAD

**Issue by knownasilya** [emberjs/ember.js#9849]
This should include the following (or something close):

- [ ] Come up with standards that Ember projects should follow
- [x] Setup JsHint - Have it run on PRs with Travis
- [x] Setup JSCS - Cover things that jshint doesn't handle, also run on Travis for PRs
- [ ] Convert existing code/examples to follow the standards set
- [x] STYLEGUIDE.md - Basic rundown of styles to follow when contributing, linked to from CONTRIBUTING.md
- [ ] Add styleguide to website

**Comment by rwjblue** [comment]
Initial implementation done in https://github.com/emberjs/ember.js/pull/10072.  Definitely still room for improvement, PR's/Issues welcome.
