### ISSUE TITLE
Properties with a first capital letter produces: Uncaught TypeError: Cannot call method 'unchain' of undefined

### ISSUE THREAD

**Issue by shama** [emberjs/ember.js#9851]
Likely related to #2031 

Here is a JSBin to reproduce the error: http://emberjs.jsbin.com/vuvijocoxa/1/edit?html,js,output

Click the `test` link and the error should appear in the console.

Changing to the global, `{{#if FEATURES.colors}}` to `{{#if GLOBAL_FEATURES.colors}}` avoids the error but global lookups are deprecated in Ember 1.8.

Un-capitalizing the first letter, `{{#if FEATURES.colors}}` to `{{#if fEATURES.colors}}` avoids the error as much expected.

**Expected**

To be able to use properties with upper case first letters or if this is not allowed for some reason, throw an error that tells me so.

Thanks!

**Comment by stefanpenner** [comment]
@mixonic I believe you may know if this is still valid or not

**Comment by mixonic** [comment]
This appears to work correctly in 1.13.3: http://emberjs.jsbin.com/xedukoroba/1/edit?html,js,output

**Comment by shama** [comment]
:+1: Thanks!
