### ISSUE TITLE
various instrumentation hooks are extremely non-performant

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#9865]
This will serve as a tracking issue for various pain points.

Some of the performance issues even leak out and affect the app when its not being instrumented
- [ ] view instrumentation

**Comment by rwjblue** [comment]
@stefanpenner - What needs to be done here?

**Comment by stefanpenner** [comment]
they need to be made performant

**Comment by rwjblue** [comment]
Can we make this actionable or close it?

**Comment by stefanpenner** [comment]
> they need to be made performant

**Comment by Serabe** [comment]
Marking issue a inactive as per our [triage policy](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy).

@stefanpenner what is the state of this?

**Comment by pixelhandler** [comment]
Closing as this has been inactive for some time
