### ISSUE TITLE
1.9 & requirejs: Uncaught Error: Could not find module handlebars 

### ISSUE THREAD

**Issue by jacdx** [emberjs/ember.js#9879]
Hello, 

Started a new project today with Ember 1.9 + requireJS 2.1.15 + Handlebars 2. I can't get Ember to load without the handlebars error. Handlebars gets loaded fine by requireJS, it just isn't recognized by Ember. If I downgrade to Ember 1.8.1 and Handlebars 1.3 with bower, it magically starts working. I fiddled with shims to no avail. 

```
require.config({
	baseUrl: 'bower_components',
	paths: {
		modernizr: 'modernizr/modernizr',
		jquery: 'jquery/dist/jquery.min',
		handlebars: 'handlebars/handlebars',
		ember: 'ember/ember',
	},
	shim: {
		modernizr: 'Modernizr',
		handlebars: {
			exports: 'Handlebars'
		},
		'ember': {
			deps: ['handlebars'],
			exports: 'Ember'
		},
	},
	config: {
	}
});

require(['jquery', 'handlebars', 'ember'], function($k, Handlebars, Ember){
	'use strict';

	console.log('Howdy pard!');
	console.log(Handlebars);
	console.log(Ember);
});
```

**Comment by nikolas** [comment]
I solved this issue by not using require.js.

**Comment by nikolas** [comment]
@jcbvm that's what I ended up doing. For anyone curious, you can change this line:

    if (typeof define === 'function' && define.amd) {

To this:

    // require.js workaround: https://github.com/emberjs/ember.js/issues/9879
    if (typeof define === 'function' && define.amd && false) {

**Comment by tfga** [comment]
Same thing with me.

I tried a variation of  @courthead's solution. It works, but:

1. Only in Chrome
2. Only half of the time (really).

I wrote a Jasmine spec. If I keep pressing F5 in the browser, half of the times the spec passes, the other half it fails with this error.

I guess some sort or racing condition is involved...

**Comment by RuslanZavacky** [comment]
Guys, I suggest to update other libraries that you are using. For me problem solved when I've updated several libraries to the latest versions, as they where incompatible with current ember version.

**Comment by nikolas** [comment]
@RuslanZavacky which libraries are you talking about? The only libraries I'm using are Ember, require.js, and jQuery - which are each at the latest versions: 1.9.1, 2.1.15, and 1.11.2.

**Comment by RuslanZavacky** [comment]
@nikolas for me it was ember-i18n which throw such error. After update there was no error.

**Comment by rwjblue** [comment]
We no longer require the `Handlebars` package (as of 1.10.0-beta.*), so this should no longer be an issue in 1.10+.

Closing for now but happy to reopen with a repro repo on latest canary.

**Comment by krisselden** [comment]
@jacdx you don't need to shim Handlebars in your requirejs config if newer handlebars defines a module via UMD.

**Comment by krisselden** [comment]
to everyone else on the thread make should you aren't including any shims in your vendor that is clobbering the handlebars module, if you update to a handlebars that will export the module if it sees an amd define instead of the global, since a shim would end up breaking it.

**Comment by tfga** [comment]
> We no longer require the Handlebars package (as of 1.10.0-beta.*)

@rwjblue Just curious: how do templates get compiled in beta? (assuming I want to compile them in the browser -- which, I know, is not recommended)

Currently we use ```Ember.Handlebars.compile()```. Now that Handlebars is gone... is there a ```Ember.Htmlbars.compile()```?

**Comment by rwjblue** [comment]
@tfga - Yes there is, and `Ember.Handlebars.compile` is actually aliased to `Ember.HTMLBars.compile` internally.

**Comment by matthewoates** [comment]
An even easier fix is to include the handlebars.js file before almond.js

here is the order of my relevant includes:
```
    <script src="/vendor/es5-shim/es5-shim.js"></script>
    <script src="/vendor/handlebars/handlebars.js"></script>
    <script src="/vendor/almond.js"></script>
    <script src="/vendor/jquery/dist/jquery.js"></script>
    <script src="/vendor/ember/ember.js"></script>
    <script src="/vendor/ember-data/ember-data.js"></script>
    <script src="/vendor/ember-resolver/dist/ember-resolver.js"></script>
    <script src="/vendor/ember-i18n/lib/i18n.js"></script>
    <script src="/vendor/ember-i18n/lib/i18n-plurals.js"></script>
```
