### ISSUE TITLE
Components can break encapsulation to access controller properties.

### ISSUE THREAD

**Issue by SohumB** [emberjs/ember.js#9880]
See [this jsbin](http://emberjs.jsbin.com/civenecega/1/edit?html,js,output). 

In short, the `fooBinding: 'controller.someValue'` syntax inside a component gives it access to its _calling controller's properties_, even as `Em.computed.alias` will correctly return `undefined`.

**Comment by stefanpenner** [comment]
needs and controller property are deprecated
