### ISSUE TITLE
[FEATURE storage-params] Query-Params except using Local/Session Storage

### ISSUE THREAD

**Issue by Glavin001** [emberjs/ember.js#9885]
## Thank you!

Query params are awesome in Ember! I love using them now. Thank you very much for everyone involved!

## Concept

I have been thinking about a new feature for Ember: `storage-params`. Instead of putting serialized data into `query-params` you could persist it between transitions/refreshes/sessions with [Local/Session Storage in HTML5](http://www.w3schools.com/html/html5_webstorage.asp).

### Example

**Note**: `localStorageParams` might not make sense for key name.

```javascript
App.ExampleController = Ember.Controller.extend({
   // queryParams: [ 'commentBody' ],
   localStorageParams: [ 'commentBody' ]
});
```

The contents of `commentBody` would be persisted to `localStorage` and scoped by each route.
Serialization/deserialization of the params could be identical to that of `queryParams`, since name/value pairs are also always stored as strings in Local/Session Storage.

#### Commenting - Long Body Messages

Query-params are great for small pieces of information, such as filters or sorting parameters, and persist between page refreshes. However, long messages, such as when commenting (think GitHub commenting) do not make sense to persist in Query Parameters. It would be great to have data like this automatically synchronized to Local/Session Storage in the same, easy-to-use fashion as Ember's Query-Params!

---

As always, this could be implemented on a developer-by-developer or app-by-app basis, however it would be great to have built-in to Ember.js! Thank you!

**Comment by machty** [comment]
Agree w @knownasilya. 

Also worth mentioning that this may show up in some from via an Ember-provided session service.
