### ISSUE TITLE
Proxied promise fail handler in PromiseProxyMixin doesn't execute and exception thrown in fail handler isn't caught by application

### ISSUE THREAD

**Issue by cristinawithout** [emberjs/ember.js#9888]
Example: http://jsfiddle.net/f6rzw5z9/3/

The proxied fail handler isn't called, and the exception that's rethrown in PromiseProxyMixin isn't caught by the application. This is causing our error handling acceptance tests to fail.

**Comment by stefanpenner** [comment]
this should work correctly now
