### ISSUE TITLE
Deprecate `buffer.pushChildView`

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#9920]
The buffer methods `pushChildView` and `hydrateMorphs` are now completely legacy.

The are however still required by several tests. These tests should be updated to use morphs and dom fragments, or htmlbars itself, and the features should be marked deprecated or possibly even be removed.

**Comment by krisselden** [comment]
why does it need to be deprecated? this wasn't ever public API, this was for legacy support of appendChild() for a string buffer

**Comment by mixonic** [comment]
@seanpdoyle sorry for losing track of this over the holidays :-( I'll look for a moment to regroup on it.

**Comment by mixonic** [comment]
In glimmer this api has been removed. @seanpdoyle. Thank you for the effort and research pushing it forward!
