### ISSUE TITLE
Port `applyClassNameBindings` to use attr nodes

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#9922]
`applyClassNameBindings` is slow. It should be ported to use streams and an attr node. Related to #9921, but class name bindings are their own weird world. The class name bindings code in general should be consolidated- the same steps are repeated in the each/collection helper, in bind-attr, and in applyClassNameBindings.

The `bind-attr` implementation has been ported already.

**Comment by rwjblue** [comment]
@mixonic - I believe that this is something you are working on currently, c/d?

**Comment by mixonic** [comment]
Focusing on attr bindings re: #9921, but after that this will be a piece of cake.

**Comment by rwjblue** [comment]
`attributeBindings` landed in https://github.com/emberjs/ember.js/pull/10186.  I believe that this is next on the chopping block.

**Comment by rwjblue** [comment]
Closing this, as I believe that AttrNode's are gone in Glimmer world.
