### ISSUE TITLE
Implement Server-Side Rendering for SEO

### ISSUE THREAD

**Issue by tomdale** [emberjs/ember.js#9938]
Currently, Ember apps must be downloaded in their entirety, evaluated, and executed before the end user sees any UI. Typically, most Ember apps serve a static "loading" page that is replaced by the framework when the app boots up.

This can lead to degraded experiences as the user has to wait for JS and other assets to load before they get any actionable UI. The issue is exacerbated for mobile devices, which can take up to 10x longer than the desktop to boot the app, and are often connected via high-latency mobile networks. Users in the developing world may be using slow connections and older browsers and suffer a degraded experience. Fetching the initial data payload as a separate request on these high-latency networks imposes an additional penalty.

SEO is also a problem for client-side rendered apps. Despite Google recently announcing that their search crawler would evaluate JavaScript when scraping sites, the secrecy around ranking algorithms leads many organizations to distrust relying on this new system vs. the well-understood behavior of server-rendered pages.

Additionally, crawlers or other tools like curl can't fetch content from JavaScript apps (without embedding a JavaScript engine, anyway). This ability to remix and scrape content is one of the strengths of the web.

We would like to address all of these shortcomings, and **we're starting with SEO**. 

Thanks to the generous sponsorship of [Bustle](http://www.bustle.com/), @wycats and I will be working on booting and rendering Ember apps on the server. While we've designed Ember from the beginning for server-side rendering, the initial work will largely be infrastructural, getting all of the pieces in place for Ember apps to run statelessly on the server.

This work is a prerequisite for the more ambitious goal of rendering apps on the server, then downloading JavaScript in the background, and having it take over control once loaded. (This is sometimes referred to as "rehydrating" the client, a.k.a. "FastBoot™".)

This issue tracks the infrastructure changes needed to achieve the SEO server rendering MVP.

- [x] Abstract browser environment necessary for executing the Ember library (#9941)
- [x] Abstract browser environment necessary for booting an Ember application (#9941)
- [x] Incorporate tests to verify node compatibility of built output
- [x] Support booting application in node environments
- [x] Split container into code registry (stateless) and session store (stateful)
- [ ] Remove 1-to-1 application <-> session coupling
- [x] Render component to string instead of DOM element
- [x] Render a route to string
- [ ] API for asynchronously initializing an Application (`Application.boot().then(callback)`)
- [ ] API for asynchronously rendering multiple sessions using single Application (`app.visit('/my-route').then(callback)`)
- [x] Audit and disable assertions that are browser specific when running in server-rendering mode
- [ ] Build demo app showing the feature working
- [ ] ~~Compile Ember into a directory of CommonJS modules~~ It turned out to not be too difficult to use the same compiled output that's sent to the browser in Node. We will revisit this later.
- [ ] ~~Distribute CommonJS Ember build on npm~~ 
- [ ] ~~Implement boot lifecycle hooks (entered loading state, application state has settled, application has rendered). These will be useful for things like analytics integration as well.~~ Still want to get to this, but we discovered it is not on the critical path.

Expect this list to expand over time as we start to dig in.

**Comment by Fed03** [comment]
So, right know, there is no way google can undertand our app?

**Comment by taras** [comment]
@Fed03 Google crawler executes JavaScript so Google can crawl Ember apps, but other search engines can't.

**Comment by nathanpalmer** [comment]
@Fed03 @taras in practice I've had little success with google crawler on an ember app. Seems like it may only work on simpler ones. I admit I haven't spent much time digging into it.

**Comment by duizendnegen** [comment]
Prerender.io worked their magic for me, also available as an open source package

**Comment by Yankovsky** [comment]
@tomdale Server side rendering is a great feature, it is a game changer! Can you estimate when it will be ready?

**Comment by mkoxio** [comment]
@Yankovsky as Tomhuda said in emberconf all thing will be released in June this year keep tuned.

**Comment by tsteuwer** [comment]
My only concern here is that you're only building this for node. Not everyone uses node with ember. There's ruby, php, and asp, to name a few.

**Comment by dschmidt** [comment]
Just because you build your REST API with PHP, ASP, Ruby or what not, it does not mean you can't serve Ember with node.js

**Comment by tsteuwer** [comment]
Yes, but making it a requirement is my concern.

**Comment by aprescott** [comment]
What's the root concern you see with having a node requirement for this feature? What do you see as the actual problem?

**Comment by topaxi** [comment]
@tsteuwer how would you run **javascript code** on ruby, php and asp? There is no way, emberjs could be run on those runtimes (without the obvious **enormous** work of a maybe possible transpilation)...

**Comment by tsteuwer** [comment]
I work for a large company and I'm in the prototyping phase of using ember. We won't be converting over our consumer facing portion for about 6 months if we find that ember will work well with our site. Currently we have a large framework which builds out the HTML payload the user will see on load using php, then we have objects which handle the interaction and moving forward in js. I don't see the Arch's agreeing that we must install node and use it to render our HTML so that we can get seo when we have all the tools currently in php. Now, if it were a php plugin as well, I can see them understanding and allowing its implementation. However, having to install another runtime on top of what we already have and use may be an entirely different story.

**Comment by tsteuwer** [comment]
@topaxi, thats exactly it. So ember users will only get the benefits of seo only if they use node? That's basically the root of the issue.

**Comment by NuckChorris** [comment]
@tsteuwer With ember-cli we should all already be using a static index.html (generated by node, it's already in your stack!) which is served by your web server, not by PHP.

The addition of Node to prerender the ember app makes sense and is an easy integration. What you're asking for (prerendering in PHP) is effectively impossible and honestly makes no sense.

Your server side code has one purpose in Ember: providing a REST API.

**Comment by tsteuwer** [comment]
@NuckChorris I completely agree. However, lots of us don't get to choose the stack we get to work in. I'm all for node, but u fortunately we've had a lamp stack for the past 15 years and wouldn't be able to get that switched over. I may just have to find aa workaround. Is it possible to point controllers at specific ids or tags and let ember initiate on doc.ready à la angular?

**Comment by mixonic** [comment]
@tsteuwer I'm willing to bet your company also uses memcached, redis, or nginx and thus C as part of their stack. Despite this you don't think of yourself as running C, you think of these servers as utilities you put in place and forget about.

The goal for FastBoot is largely the same. You need to write Ember code, but the intent is that you do not need to write Node.js as such. It just happens to be that your Ember code works on the server as a utility you can point nginx at.

You will need to run that utility as part of your stack though, and if it is rejected (just like they might reject MongoDB or any other server) then you will need to find an alternative solution.

> I don't see the Arch's agreeing that we must install node and use it to render our HTML so that we can get seo when we have all the tools currently in php.

And I don't suggest that you make that the pitch. FastBoot allows you to write your application once and run it for offline clients, mobile clients, and web apps as we think of them today. It encourages your organization to adopt a service-oriented architecture with a single API used by all clients. This pitch takes you into a discussion about the benefits of a JavaScript application and API architecture, and I hope that the benefits of those strategies outweighs installing a new daemon and language.

This might not be a trivial discussion, and might represent a change in direction for your organization. I don't suggest it is a small thing.

Lastly, if your business does not require an SEO strategy then FastBoot is not needed. The current deployment solutions will suit you just fine. In fact even if you do need SEO, there are a number of other strategies used by apps today (noscript, prerendering, dynamic server-side HTML) that will still be viable.

**Comment by NuckChorris** [comment]
>Is it possible to point controllers at specific ids or tags and let ember initiate on doc.ready à la angular?

I'm no expert but I'm pretty sure Ember isn't built to run _part_ of an app. it's huge and all the concepts inside it (like the Router) don't really make sense if it's just managing a chunk of DOM. It's a big opinionated framework for your entire application.

**Comment by tsteuwer** [comment]
@mixonic, that's a very valid point. Thanks all for your help

**Comment by tomdale** [comment]
@tsteuwer We want to support as many platforms as possible. However, FastBoot requires running your Ember.js application on the server, which is, of course, written in JavaScript. That means you must have a JavaScript runtime.

We hope that the community will build many packages to make integrating into existing stacks very easy. Ultimately, though, there is a hard requirement for a JavaScript runtime. You just can't evaluate JavaScript without one.

**Comment by rwjblue** [comment]
@tomdale - I believe that this issue is completed (all the checklist items seem to be done), and we are just waiting to "go" the feature (hopefully for 2.2).   Can you confirm and close?

**Comment by Master244** [comment]
I guess a demo app is pretty important in this case. I'm stuck on the problem getting Facebook to see my meta tags in my head that change dynamically when I go to a new news item. I got this al working but then I noticed idd FB does not run any Javascript so i'm kinda stuck. And should probably be looking for something like this. Where a working demo would come in very handy :)

**Comment by duizendnegen** [comment]
@Master244 https://github.com/zipfworks/ember-prerender / www.prerender.io combined with https://www.npmjs.com/package/ember-cli-meta-tags can help you out with that, while we're waiting for FastBoot to land
The packages feature some demos themselves, should be enough to help you on your way.

**Comment by wcurtis** [comment]
To add to @duizendnegen's suggestion, the ember-cli heroku buildpack supports prerender.io config https://github.com/tonycoco/heroku-buildpack-ember-cli#prerenderio. That's my current setup and works fine (still can't wait for fastboot though!).

**Comment by Master244** [comment]
@duizendnegen dankjewel :), that will defiantly help me on my way. I did find prerender.io and http://www.emberjsseo.com/ . I was already setting this up to test it out with Docker ill post my findings here if someone wants to use my Docker setup and flow.

**Comment by Fed03** [comment]
@Master244 let us know!

**Comment by JamesMGreene** [comment]
Yes, please! :+1:

**Comment by mariendries** [comment]
Is there an estimated landing time for ember Fastboot?

**Comment by rwjblue** [comment]
The Ember internal feature that fastboot takes advantage of (the new visit API) is enabled by default on canary builds and is planned to be in Ember 2.3.0. 

This will allow ember-cli-fastboot to continue to improve stability and eventually graduate to a 1.0.0 version itself.

**Comment by rwjblue** [comment]
@tomdale - Closing this since ember-application-visit is enabled now. Please reopen (and update checklist above) if there are additional items you would like to track in this issue.
