### ISSUE TITLE
Duplicate definitions in YUIDoc output

### ISSUE THREAD

**Issue by danmcclain** [emberjs/ember.js#9946]
I've been working with the `ember-docs.json` and found some functions that have 2 definitions. I have not checked all of them, but a cursory glance of `Ember.Application#buildContainer` has 2 *different* definitions

```
RSVP#all
RSVP#race
RSVP#reject
RSVP#resolve
Ember.Application#resolver
Ember.Application#buildContainer
Ember.DefaultResolver#namespace
Ember.Handlebars.helpers#helperMissing
Ember.Binding#oneWay
Ember.LinkView#currentWhen
Ember.Test#setupForTesting
```

/cc @rwjblue

**Comment by locks** [comment]
@toddjordan can you poke into this and check if it's still relevant?

**Comment by pixelhandler** [comment]
@toddjordan @locks closing this, seems not relevant for now.
