### ISSUE TITLE
SVG component prevents triple mustache from rendering text

### ISSUE THREAD

**Issue by SufferForYourArt** [emberjs/ember.js#9948]
Tested in Ember v1.9.0 and Chrome V39. 

When an SVG component exists as a sibling element to a triple mustache tag it no longer renders the provided text. See http://codepen.io/sufferforyourart/pen/81617a9a9f5939d476d7d63bedcacd11?editors=101.

After a little digging it looks like domHelper.parseHTML function is attempting to parse the text as an SVG instead of HTML

**Comment by rwjblue** [comment]
I tried to take a look, but couldn't figure out how to change the codepen's Ember version (likely I'm just being obtuse).  Can you test against 1.10.0-beta.3?

**Comment by rwjblue** [comment]
OK, made a JSBin against canary: http://emberjs.jsbin.com/rwjblue/194/edit?html,js.

**Comment by oneeman** [comment]
Thanks, Robert, I'll see what I can do, got a rough idea of where the problem lies.

**Comment by mixonic** [comment]
https://github.com/tildeio/htmlbars/pull/237 is merged, this will be fixed with an HTMLBars version bump.

**Comment by rwjblue** [comment]
Updated canary and beta to v0.8.1 of HTMLBars.  http://emberjs.jsbin.com/rwjblue/194/edit?html,js,output seems to be working properly now.
