### ISSUE TITLE
Can't `export default Router.map()`

### ISSUE THREAD

**Issue by devinrhode2** [emberjs/ember.js#9966]
I searched issues for: Router map return "router:main" - and got no results.
Confirmed on canary here: http://emberjs.jsbin.com/niceculasu/3/

Use case:
```javascript
import Ember from 'ember';
export default Ember.Router.extend({
  location: config.locationType
}).map(function(){
  this.resource('todos');
});
```
Error:
```
Uncaught Error: Failed to create an instance of 'router:main'. Most likely an improperly defined class or an invalid module export.
```
Expected:
To be able to return the result from Router.map - that is, I expected it to return the Router instance. I think this would be a great API. I would assume Ember supports method chaining on any and every object, I'm (grumpily) curious what else doesn't have straightforward jQuery-like chaining

<sub>Disclosure: I actually discovered this error when using `ember-cli-coffees6` and documented it all here:https://github.com/devinrhode2/major-domo/issues/1</sub>

**Comment by petrvolny** [comment]
#9994 is merged. Can this issue be closed?
