### ISSUE TITLE
QueryParams - `paramsFor` does not return updated values within `queryParamsDidChange`

### ISSUE THREAD

**Issue by kamalaknn** [emberjs/ember.js#9969]
Calling `paramsFor` within `queryParamsDidChange` does not return updated queryParam values. 

[This bin](http://emberjs.jsbin.com/sopid/3/edit?html,js,console,output) shows `paramsFor` returns correct values only after a full transition for the route has taken place.

This is not allowing me to get the complete current qp state.

cc @machty 

PS: My use case - I am trying to reload a routes model within queryParamsDidChange, without setting `refreshModel:true`, because a full re-render(of this and its child routes)  is not always needed.

**Comment by meggers** [comment]
I am experiencing this as well (with the same use case). @kamalaknn, did you find a solution?

**Comment by kamalaknn** [comment]
@meggers Yup, the first argument is the changed params. But the caveat is in dealing with removed params. We use a couple of hacks to get the current state(but it is not a clean solution). It would be neat if `this.paramsFor(this.routeName)` actually returned the current state. 

@machty Is there a best practice you would suggest to reloading a model for a route, for `qp` changes without `refreshModel:true` - just because we do not want child routes to re-render. Or a path to follow with the new component hooks `qp` rewrite ?

**Comment by meggers** [comment]
Out of curiosity, how do you get the current state?

**Comment by kamalaknn** [comment]
@meggers It is basically
```js
let controller = this.get('controller');
let qps;
Ember.run.next(function() {
  qps = controller.getProperties(controller.get('queryParams')); //might need type checking for non array form
});
```
wrapped in a couple of hacks. This may not be the best solution. But it is what we use to make do for `this.paramsFor(this.routeName)`

**Comment by pixelhandler** [comment]
@kamalaknn I noticed that the link for reproduction of the issue is using Ember 1.8. Do you still have this issue in a current release, or in the LTS version (2.4.6) of Ember?

**Comment by Serabe** [comment]
Marking issue a inactive as per our [triage policy](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy).
