### ISSUE TITLE
SVG - need to use setAttributeNS when setting 'xlink:href'

### ISSUE THREAD

**Issue by salzhrani** [emberjs/ember.js#9970]
SVG sprites utilize the `<use xlink:href="#some-shape">`, and for it to work properly the `xlink:href` attribute must be set using `setAttributeNS` instead of `setAttribute`. here is a [jsbin](http://emberjs.jsbin.com/zuxopesogi/2/edit?html,js,console,output) that demonstrates the issue and fix.

**Comment by rwjblue** [comment]
Was chatting this through with @oneeman in IRC, and I am fairly sure that we can fix this now (after all the awesome work that @salzhrani and @oneeman have done upstream in HTMLBars) for `{{bind-attr}}` in beta (1.10).

This [line](https://github.com/emberjs/ember.js/blob/4df827e57a68e75a74fdd63c1123dddedf5a36ad/packages/ember-htmlbars/lib/helpers/bind-attr.js#L192) needs to updated to parse the namespace and pass it as a third parameter to the `createAttrMorph` call.

**Comment by rwjblue** [comment]
As mentioned by @oneeman the following does work on canary today:

```
    {{#each item in model}}
      <li>{{item.clr}}<svg viewBox="0 0 25 25"><use xlink:href={{item.url}}></use></svg></li>
    {{/each}}
```

http://emberjs.jsbin.com/tohiyu/2/edit.

**Comment by oneeman** [comment]
(thanks to @salzhrani )

At first I thought this issue should be closed now, but maybe keep it open until it also works with `bind-attr`.

**Comment by rwjblue** [comment]
Seems to be working properly now: http://emberjs.jsbin.com/poropo/1/edit?html,js
