### ISSUE TITLE
the index parameter of computed.map callback function is undefined

### ISSUE THREAD

**Issue by feitian124** [emberjs/ember.js#9979]
as per document, the callback method for computed.map should have the following signature:
```js
function(item, index);
```
the problem is that the index is always undefined. I showed this problem in my repo, [this commit](https://github.com/feitian124/ember-problems/commit/b63f3663e733c90f16e7d5933895131c6455c98d).

```js
myposts: Ember.computed.map('model', function(item, index){
     console.log("item:", item);
     console.log('map index:', index);
     return item;
  })
```
above code get below logs:
```sh
 item: Class {id: "69", store: Class, container: Container,…}  
 map index: undefined
```
my ember version is:
```
DEBUG: -------------------------------
vendor.js:28044 DEBUG: Ember      : 1.7.0
vendor.js:28044 DEBUG: Ember Data : 1.0.0-beta.10
vendor.js:28044 DEBUG: Handlebars : 1.3.0
vendor.js:28044 DEBUG: jQuery     : 1.11.1
vendor.js:28044 DEBUG: -------------------------------
```

**Comment by stefanpenner** [comment]
can you:

1. test on the latest stable + canary
2. provide an example JSBin or a failing test for us to dive in quickly.

**Comment by rwjblue** [comment]
I made a super simple demo showing that it does pass the index (in general): http://emberjs.jsbin.com/rwjblue/191/edit

We will definitely need a JSBin reproduction showing the issue to be able to track down what is happening in your situation.

**Comment by feitian124** [comment]
i created a jsbin at  http://emberjs.jsbin.com/rirabazuva/1/ and find with later ember release, it does work.
when I tried to use http://builds.emberjs.com/tags/v1.7.0/ember.js, it report error not sure why.
```
"error"
"Script error. (line 0)"
"error"
"TypeError: Cannot read property 'create' of undefined
```
i am not quite good at jsbin and as later version works, it is fine to close this issue.
thanks.

**Comment by rwjblue** [comment]
@feitian124 - Thanks for confirming this for us!
