### ISSUE TITLE
1.10 Release Blog Post

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#9985]
This ticket is a summary of items to be discussed for the 1.10 release post. **Repo followers, please do not consider this a guarantee or even prediction of 1.10 behavior**. Just a place for notes.

This issue is locked to keep us focused. If you have commit bit please edit the description.

---
1.10:

* [FEATURE] HTMLBars
* [FEATURE] block params
* [FEATURE] ember-metal-injected-properties
* Filesize change? basically a wash (within 1kb of 1.9)
* Talk about current state of boolean attrs
* review performance profiles, changes in common situations.
* Enumerate the tools that support HTMLBars compilation today
* Cross-link to a blog post about how to write your own compilation tools for Node (@rwjblue)
* discuss the mental model for attributes, noting svg as an exception
* use the "Attribute Rules" doc for reference

1.10 deprecations:

* deprecated quoteless outlet names
* deprecate setting container childViews
* deprecate private {{bind}} helper (it was always private and is removed in 1.11)

---
1.11 beta:

* [FEATURE] inline if
* [FEATURE] ember-routing-named-substates
* [FEATURE] htmlbars attr syntax (still pending "go" decision) (must go in-depth)
* Deprecate Ember.ObjectController (https://github.com/emberjs/ember.js/pull/10062)
* Remove previously deprecated private `{{bind}}` helper.

**Comment by trek** [comment]
Commenting just so this stops showing up in my [needs attention list](https://github.com/emberjs/ember.js/issues?q=is%3Aopen+no%3Alabel+no%3Aassignee+comments%3A0)
